### ISSUE TITLE
bitnami/discourse

### ISSUE THREAD

**Issue by sonal-jatav** [bitnami/charts#10004]
### Name and Version

bitnami/bitnami-docker-discourse 2.8.3-debian-10-r16

### What is the problem this feature will solve?

Require image and chart for discourse to support for redis external service SSL port 6380.
Currently the image and chart for discourse support Non SSL port 6379.

### What is the feature you are proposing to solve the problem?

The chart should be able to connect to external redis service via the SSL port.

### What alternatives have you considered?

Currently using external redis service via Non SSL port 6379

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
