### ISSUE TITLE
[bitnami/elasticsearch] Validation Failed: 1: type is missing

### ISSUE THREAD

**Issue by dheeth** [bitnami/charts#10003]
### Name and Version

bitnami/elasticsearch-curator:5.8.4-debian-10-r321

### What steps will reproduce the bug?

1. I uncommented the values elasticsearch-s3-repository here https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/values.yaml#L1533
2. Changed the bucket etc. values and deployed
3. I get this error every time
```
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"},"status":400}
```
4. Is there any pre-requisite for this to work?
5. I have already enabled repository-s3 plugin

### What is the expected behavior?

It should backup my logs to S3 every time the cronjob runs

### What do you see instead?

I see the error given above in the description

**Comment by carrodher** [comment]
Could you provide the `elasticsearch-s3-repository` block you're using?
