### ISSUE TITLE
[bitnami/jenkins] Deployment template missing sidecars to add additional containers

### ISSUE THREAD

**Issue by NominalTrajectory** [bitnami/charts#10020]
### Name and Version

bitnami/jenkins 10.0.6

### What steps will reproduce the bug?

1. Navigate to the values file https://github.com/bitnami/charts/blob/master/bitnami/jenkins/values.yaml - the file contains a key "sidecars" that should be used to add additional containers to the Pod.
2. Navigate to file https://github.com/bitnami/charts/blob/master/bitnami/jenkins/templates/deployment.yaml - the file does not render the values passed under the sidecars key.

### What is the expected behavior?

The file deployment.yaml must render additional containers based values passed under the sidecars key. 
https://github.com/bitnami/charts/blob/master/bitnami/jenkins/templates/deployment.yaml

### What do you see instead?

Sidecars key is available in values but it does not get rendered in the Deployment template.

**Comment by carrodher** [comment]
Thanks for reporting this issue, you're totally right. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by NominalTrajectory** [comment]
Hi @carrodher! Yes, I'd be glad to pick it up, you can assign it to me.

**Comment by carrodher** [comment]
Thanks! [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines, the process shouldn't be complex, but feel free to ping us if you have any question
