### ISSUE TITLE
Kafka should advertise DNS names instead of POD_IP

### ISSUE THREAD

**Issue by dedsm** [bitnami/charts#1002]
**Which chart**: kafka

**Description**: by advertising IPs instead of DNS names, in case of upgrades/redeployments that cause the brokers to change IP, some clients will keep trying the old IPs to reconnect.

***Related Issues***
https://github.com/dpkp/kafka-python/issues/1683
https://github.com/aio-libs/aiokafka/issues/456

**Steps to reproduce the issue:**

1. Run a client connected to kafka
2. Delete the kafka installation
3. Recreate the kafka installation

**Describe the results you received:**

After the 3rd step, the clients are still trying to connect to the old broker IPs

**Describe the results you expected:**

Clients would notice the new brokers in place and connect to those

**Additional information you deem important (e.g. issue happens only occasionally):**

Solved by setting advertisedListeners to the DNS name of the headless service, maybe this should be the default?

**Version of Helm and Kubernetes**:

- rancher 2.1.4

```
(paste your output here)
```

- Output of `rancher kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @dedsm,

Thanks for submitting this issue. After a first look, it makes sense to use DNS names for the reasons that you are describing. We'll try to implement this.

Thanks again!

**Comment by dedsm** [comment]
@andresbono great, maybe the PR can help :)

**Comment by andresbono** [comment]
Thanks for submitting it! My colleagues will review and merge it!
