### ISSUE TITLE
The bitnami ASP.NET Core helm chart in version 3.1.18 are not correct: extraHosts the ingress configuration is incorrect

### ISSUE THREAD

**Issue by adaumann** [bitnami/charts#10032]
### Name and Version

bitnami/aspnet-core 3.1.18

### What steps will reproduce the bug?

Using following input in the Ingress configuration part:

    [...]
    ingress:
      enabled: true
      selfSigned: false
      ingressClassName: nginx
      hostname: apigateway.hcv-cluster-local.net
      servicePort: http
      tls: true
      selfsigned: false
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        #certmanager.k8s.io/issuer: "letsencrypt-prod"
        #certmanager.k8s.io/acme-challenge-type: http01    
      pathType: ImplementationSpecific
      extraHosts:
        - name: apigateway.hcv-cluster-local.net
          path: /api
      extraTls:
        - hosts:
            - apigateway.hcv-cluster-local.net
          secretName: apigateway.local-tls
      secrets: 
        - name: apigateway.local-tls
          certificate: |-
            ---- BEGIN CERT...
          key: |-
            ---- BEGIN RSA...

### Are you using any custom parameters or values?

See above

### What is the expected behavior?

* Extracted helm template is correct
* Connection to Ingress DNS name with certificates as defined in extraHosts

### What do you see instead?

he "helm template" than fails with 'nil pointer evaluating interface {}' on extraPaths. Furthermore the ingress uses old names for the service link. Therefore the ingress.yaml in asp.net need to be adjusted. Seems to be a bug in the bitnami asp.net core chart:

### Additional information

I extracted the chart and made following adjustments marked with ### HCV (taken from bitnami keycloak chart)

    {{- if .Values.ingress.enabled -}}
    apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
    kind: Ingress
    metadata:
      name: {{ include "aspnet-core.fullname" . }}
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
        {{- end }}
      annotations:
        {{- if .Values.ingress.certManager }}
        kubernetes.io/tls-acme: "true"
        {{- end }}
        {{- if .Values.ingress.annotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
        {{- end }}
    spec:
      {{- if and .Values.ingress.ingressClassName (include "common.ingress.supportsIngressClassname" .) }}
      ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
      {{- end }}
      rules:
        {{- if .Values.ingress.hostname }}
        - host: {{ .Values.ingress.hostname }}
          http:
            paths:
    ### HCV Start
              {{- if .Values.ingress.extraPaths }}
              {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
              {{- end }}
    ### HCV End
              - path: {{ .Values.ingress.path }}
                {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
                pathType: {{ .Values.ingress.pathType }}
                {{- end }}
                backend: {{- include "common.ingress.backend" (dict "serviceName" (include "aspnet-core.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
        {{- end }}
        {{- range .Values.ingress.extraHosts }}
        - host: {{ .name }}
          http:
            paths:
    ### HCV Start remove extrapaths
    ### HCV End
    ### HCV Start
              - path: {{ default "/" .path }}
                {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
                pathType: {{ default "ImplementationSpecific" .pathType }}
                {{- end }}
                backend: {{- include "common.ingress.backend" (dict "serviceName" (include "aspnet-core.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
    ### HCV End
        {{- end }}
      {{- if or .Values.ingress.tls .Values.ingress.extraTls .Values.ingress.hosts }}
      tls:
        {{- if .Values.ingress.tls }}
        - hosts:
            - {{ .Values.ingress.hostname }}
          secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
        {{- end }}
        {{- if .Values.ingress.extraTls }}
        {{- toYaml .Values.ingress.extraTls | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}

**Comment by rafariossaa** [comment]
Hi,
 Would you like to send a PR with the changes ? We will be glad to review and merge it.

**Comment by adaumann** [comment]
PR is available

**Comment by rafariossaa** [comment]
Hi,
  Let's wait until it get reviewed and merged.
  The PR is: https://github.com/bitnami/charts/pull/10244
