### ISSUE TITLE
Will replicas serve read traffic in redis-cluster

### ISSUE THREAD

**Issue by rajyadav911** [bitnami/charts#10033]
### Name and Version

bitnami/redis-cluster

### What steps will reproduce the bug?

Launched a cluster with 3masters and 3 replicas.

When we do cluster slots all slots are distributed among three masters and 0 slots on replicas.

Also, I have a common load-balancer for all 6 nodes( 3Master,3replicas)
So whenever a get is done and request falls to replica nodes then it gets directed to master nodes with that slot or replicas also have data and can serve the traffic. 

### What do you see instead?

Need clarification on whether the read request is directly served from replica nodes or it gets redirected to master only for get request also.

**Comment by FraPazGal** [comment]
Hello @rajyadav911,

The replicas should be able to serve the read request without having to redirect it to the master. As explained in the chart's doc, said redirection is done for write operations that arrive in a replica:

> The replicas will be read-only replicas of the masters. By default only one service is exposed (when not using the external access mode). You will connect your client to the exposed service, regardless you need to read or write. When a write operation arrives to a replica it will redirect the client to the proper master node. For example, using redis-cli you will need to provide the -c flag for redis-cli to follow the redirection automatically.
