### ISSUE TITLE
bitnami/keycloak 7.1.18 - keycloak-config-cli cannot find/connect to Keycloak service

### ISSUE THREAD

**Issue by sotiriougeorge** [bitnami/charts#10034]
### Name and Version

bitnami/keycloak 7.1.18

### What steps will reproduce the bug?

I am using EKS cluster with Helm. My requirement was to use Keycloak chart as a sub-chart of a larger custom chart that I am trying to make to install multiple services on the cluster at once. An additional requirement is that Keycloak is configured automatically after deployment. I opted to go with the `keycloakConfigCli` value in order to provide an already existing/exported Keycloak configuration that I had and move from there.

1. I installed my chart (bitnami/keycloak being a dependency in it):

```
helm install app-layer app-layer/
```
2. The configcli job gets created and it creates the first Pod for the job (the backoff limit is 1). The Pod fails with the following message in the logs:
```
$ kubectl logs app-layer-keycloak-keycloak-config-cli-lzjg5
2022-05-05 08:31:18.402  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v4.9.0 using Java 11.0.14 on app-layer-keycloak-keycloak-config-cli-lzjg5 with PID 1 (/opt/bitnami/keycloak-config-cli/keycloak-config-cli-16.1.1.jar started by ? in /opt/bitnami/keycloak-config-cli)
2022-05-05 08:31:18.407  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2022-05-05 08:31:19.479  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 2.033 seconds (JVM running for 2.933)
2022-05-05 08:31:21.022  INFO 1 --- [           main] d.a.k.c.provider.KeycloakImportProvider  : 1 configuration files found.
2022-05-05 08:31:21.026  INFO 1 --- [           main] d.a.k.c.provider.KeycloakImportProvider  : Loading file '/config/realm.json'
2022-05-05 08:31:21.357  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file '/config/realm.json'
2022-05-05 08:31:21.368  INFO 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Wait 120 seconds until http://app-layer-keycloak-headless.default.svc:8080/auth/ is available ...
2022-05-05 08:33:11.682 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Create method returned status Not Found (Code: 404); expected status: Created (201)
2022-05-05 08:33:11.682  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 01:50.668.
```

### Are you using any custom parameters or values?

As already mentioned I am building my own chart using bitnami/keycloak as a dependecy. These are the values of my chart that pertain to keycloak: 
```yaml
keycloak:
  enabled: true
  auth:
    createAdminUser: true
    adminUser: admin
    adminPassword: "someadminpass123"
    managementPassword: "somemanagementpass123"
    existingSecret:
      name: keycloak-user-secret
      keyMapping:
        admin-password: admin-password
        management-password: management-password
        password: password
  proxyAddressForwarding: true
  extraStartupArgs: |
    -Dkeycloak.frontendUrl=https://keycloak.mydomain.com/auth
  service:
    type: ClusterIP
    ports:
      http: 8080
      https: 8443
  ingress:
    enabled: true
    ingressClassName: "kong"
    hostname: keycloak.mydomain.com
    annotations:
      konghq.com/protocols: "https"
      konghq.com/https-redirect-status-code: "308"
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  rbac:
    create: true
  keycloakConfigCli:
    enabled: true
    existingConfigmap: "test-keycloak-configuration"
  postgresql:
    enabled: true
    auth:
      password: "abcd55"
```

I have also  tried the exact same configuration but I also added the following inside `keycloakConfigCli`:
```yaml
  keycloakConfigCli:
    extraEnvVars:
      - name: KEYCLOAK_URL
        value: "http://app-layer-keycloak-headless.default.svc:8080/auth/" #tried this with and without trailing slash - no difference
```

### What is the expected behavior?

I expected Keycloak to be deployed according to my values and the realm settings provided through my configMap to be applied.

### What do you see instead?

```
$ helm install app-layer app-layer/
coalesce.go:203: warning: destination for existingSecret is a table. Ignoring non-table value
coalesce.go:203: warning: destination for existingSecret is a table. Ignoring non-table value
coalesce.go:203: warning: destination for existingSecret is a table. Ignoring non-table value
Error: failed post-install: job failed: BackoffLimitExceeded
```

### Additional information

I am using a ConfigMap and my own Secret to pass certain values. The Secret I only had to use as it seems to be required by the Job (according to the Keycloak helm chart code - if I read it correctly) - the Job won't get the value for the adminPassword directly from the values but only looks for it inside a secret. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-keycloak-configuration
  namespace: default
data:
  realm.json: |
    {
      redacted-for-brevity
    }
```
I am not sure if I did ok here, my secret values don't seem to be respected in the final deployment and for sure I know that linking secret values back to exposed values is not a good practice but for the tests I am conducting now it will suffice. In any case I don't think my issue is related to the secret per se.
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-user-secret
  namespace: default
type: Opaque
data:
    admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
    management-password: {{ .Values.keycloak.auth.managementPassword | b64enc | quote }}
    password: {{ .Values.keycloak.postgresql.auth.password | b64enc | quote }}
```

**Comment by rafariossaa** [comment]
Hi,
  It seems it is not an issue related to the Bitnami ASSET container image or Helm chart but about how the application or environment is being used/configured.
  For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.
  That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by sotiriougeorge** [comment]
Hi, thank you for your prompt reply. After spending an entire work day on it, turns out that funny enough the problem was laying in my ConfigMap - aka my provided `realm.json` import file. 

Apparently a file exported from another Keycloak instance contains UUIDs and other types of information that are not inherently acceptable "as-is" through the `configCLI` functionality. So when the configCLI program was trying to connect to the current Keycloak instance it was kind of trying to "find" the realm that it was meant to import , rather than "create" it and it was trying to do that by searching past the `/auth` endpoint going into `/auth/realms/<realm_name>` and therein somewhere lied the error above.

I made an example with a simple vanilla realm not coming from a configMap but in the `configuration: {}` section as such:
```yaml
    configuration:
      realm1.json: |
        {
          "realm": "realm1",
          "clients": []
        }
```
and it worked just fine. So I will be closing this one down and I hope with this reply I am helping some unfortunate soul in the future.

**Comment by manuschillerdev** [comment]
> Hi, thank you for your prompt reply. After spending an entire work day on it, turns out that funny enough the problem was laying in my ConfigMap - aka my provided `realm.json` import file.
> 
> Apparently a file exported from another Keycloak instance contains UUIDs and other types of information that are not inherently acceptable "as-is" through the `configCLI` functionality. So when the configCLI program was trying to connect to the current Keycloak instance it was kind of trying to "find" the realm that it was meant to import , rather than "create" it and it was trying to do that by searching past the `/auth` endpoint going into `/auth/realms/<realm_name>` and therein somewhere lied the error above.
> 
> I made an example with a simple vanilla realm not coming from a configMap but in the `configuration: {}` section as such:
> 
> ```yaml
>     configuration:
>       realm1.json: |
>         {
>           "realm": "realm1",
>           "clients": []
>         }
> ```
> 
> and it worked just fine. So I will be closing this one down and I hope with this reply I am helping some unfortunate soul in the future.

can confirm this. if you want to import a realm you can remove all ids from your exported realm with a regex
