### ISSUE TITLE
resources: put ephemeral-storage into requests

### ISSUE THREAD

**Issue by shaunc** [bitnami/charts#10043]
### Name and Version

bitnami/memcached 6.0.17

### What is the problem this feature will solve?

I had a memcached pod evicted with following error:

```
Message:        The node was low on resource: ephemeral-storage. Container memcached was using 16Ki, which exceeds its request of 0. 
```

I would like to specify a ephemeral-storage resource request to avoid this.

### What is the feature you are proposing to solve the problem?

Add `ephemeral-storage` to resource requests & values.

**Comment by rafariossaa** [comment]
Hi,
  Hi, thanks for the suggestions, but as we are a small team with different priorities I can't provide you an ETA for this addition. Anyways, I just created an internal task to evaluate this feature and work on it when we have some bandwidth.
  Meanwhile maybe you can consider sending a PR implementing this. We will be glad to review and merge it.
