### ISSUE TITLE
[bitnami/redis] helm status doesn't show redis port correctly

### ISSUE THREAD

**Issue by willww64** [bitnami/charts#10040]
### Name and Version

bitnami/redis 16.8.5

### What steps will reproduce the bug?

1. `helm install redis bitnami/redis`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

After the installation finished, it should output the correct command to connect to redis.

### What do you see instead?

No redis port in the output commands:

```
...

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace toolapp svc/redis-master : &
    REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h 127.0.0.1 -p
```

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will review it and provide feedback
