### ISSUE TITLE
[bitnami/rabbitmq] Cannot create fresh install with volumePermissions.enabled=true

### ISSUE THREAD

**Issue by link-webcreations** [bitnami/charts#10045]
### Name and Version

bitnami/rabbitmq 9.0.1

### What steps will reproduce the bug?

* On a fresh install
* `helm install bitnami/rabbitmq --generate-name --set volumePermissions.enabled=true`

The init container on the Kafka broker will fail with the following error:

```
/bin/chown: missing operand after '1001:1001'
Try '/bin/chown --help' for more information.
```

### Are you using any custom parameters or values?

volumePermissions.enabled=true

### What is the expected behavior?

The RabbitMQ is successfully initialized and the service starts up.

### What do you see instead?

The volume permissions init container crashes because the chown command is invalid.

**Comment by carrodher** [comment]
Thanks for letting us know, I just reproduced the issue. We recently refactored this Helm chart (https://github.com/bitnami/charts/pull/9817) so probably there is some misconfiguration. We will take a look at the changes and send a PR fixing the issue.
