### ISSUE TITLE
bitnami/grafana Helm chart TLS with Kubernetes secret isn't working as documented

### ISSUE THREAD

**Issue by magnetar82** [bitnami/charts#10050]
### Name and Version

bitnami/grafana-7.6.31

### What steps will reproduce the bug?

**Helm Chart** 
grafana-7.6.31

Kubernetes cluster is configured with a TLS secret, attempting to deploy the Bitnami Grafana with Helm using the TLS Secret configured on the cluster. 

Below is a copy of the default values.yaml documentation on enabling TLS.  

<pre><code>
  @param ingress.tls Enable TLS configuration for the hostname defined at ingress.hostname parameter
  TLS certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.ingress.hostname }}
  You can use the ingress.secrets parameter to create this TLS secret or relay on cert-manager to create it`
  tls: false
</code></pre>

**Here is the cluster secret attempting to use** 
grafana.corpdomain.local-tls  

**Example on how I'm deploying helm chart**
helm install my-release bitnami/grafana  --values=grafana-values.yaml

### Are you using any custom parameters or values?

**The custom values file that is being used in the helm install command**
<pre><code>
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: grafana.corpdomain.local
  tls: true
persistence:
  enabled: true
  size: 20Gi
</code></pre>

### What is the expected behavior?

Expected the helm deployment to check the Kubernetes secrets and use a secret that matched the ingress.hostname option with -tls 
**TLS Secret name**
grafana.corpdomain.local-tls

**ingress.hostname**
grafana.corpdomain.local

### What do you see instead?

Don't see port 443 configured for the ingress service

**kubectl get ingress**
[user@server]$ kubectl get ingress
NAME                CLASS    HOSTS                       ADDRESS                                        PORTS     AGE
my-release         <none>   grafana.corpdomain.local   server1-ip,server2-ip,server3-ip   80        35m

### Additional information

Maybe I'm miss understanding how this helm chart should work. Sorry if this is a repost, I wasn't able to find information on this particular configuration. 

Thanks for the help

**Comment by joancafom** [comment]
Hi @magnetar82 

If I understood it correctly, you are using an already existing secret containing the TLS certificates. In that case, you may need to use the `extraTLS` param:

```yaml
ingress:
  enabled: true
  hostname: grafana.corpdomain.local
  tls: true
  extraTls:
    - hosts:
        - "{{ .Values.ingress.hostname }}"
      secretName: YOUR-SECRET-NAME
```
That should make it 😁

**Comment by magnetar82** [comment]
Hi @joancafom, 

Yes, extraTLS example above worked.  I'm able to proceed, thank you. 

I'll leave it up to you to decided if this is bug, but I found the documentation to be confusing when attempting to use a TLS secret with this helm chart. 

Thanks,

**Comment by joancafom** [comment]
Maybe it would be a good idea to rephrase and add something like:

```diff
  ## @param ingress.tls Enable TLS configuration for the hostname defined at ingress.hostname parameter
  ## TLS certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.ingress.hostname }}
-  ## You can use the ingress.secrets parameter to create this TLS secret or relay on cert-manager to create it
+  ## You can:
+  ##   - Use the `ingress.secrets` parameter to create this TLS secret
+  ##   - Rely on cert-manager to create it by setting the corresponding annotations
+  ##   - Rely on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
+  ##
+  ## Alternatively, you can provide an existing secret with your certificate and key using the `ingress.extraTLS` param.
+  ##
  tls: false
```

WDYT? Is it clearer now? Would you like to contribute with a PR?

**Comment by magnetar82** [comment]
Sorry about the delay. Yes, that's helpful to me. Looks good.
