### ISSUE TITLE
issue with rabbitmq upgrade.

### ISSUE THREAD

**Issue by nadellasai** [bitnami/charts#10063]
### Name and Version

chart 9.0.3 rabbitmq

### What steps will reproduce the bug?

try to upgrade rabbitmq using helm

### Are you using any custom parameters or values?

yes. My values file was good until the previous upgrade. Now it has an issue with customLabels

### What do you see instead?

when I try to upgrade rabbitmq using helm, It is throwing the following error:
```
Error: UPGRADE FAILED: template: rabbitmq/templates/statefulset.yaml:37:28: executing "rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: rabbitmq/templates/secrets.yaml:39:18: executing "rabbitmq/templates/secrets.yaml" at <.Values.commonLabels>: nil pointer evaluating interface {}.commonLabels
helm.go:84: [debug] template: rabbitmq/templates/statefulset.yaml:37:28: executing "rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: rabbitmq/templates/secrets.yaml:39:18: executing "rabbitmq/templates/secrets.yaml" at <.Values.commonLabels>: nil pointer evaluating interface {}.commonLabels
UPGRADE FAILED
```
I believe that there is an error in line 39 of secrets.yaml file. (probably missing $sign)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
