### ISSUE TITLE
[bitnami/nginx-ingress-controller] Error in PodDisruptionBudget

### ISSUE THREAD

**Issue by RenaudDemarneffe** [bitnami/charts#10060]
### Name and Version

bitnami/nginx-ingress-controller 9.1.27

### What steps will reproduce the bug?

1. Enable pdb for default backend
```
defaultBackend:
  pdb:
    create: true
    minAvailable: 1
```
2. Deploy `helm install nginx bitnami/nginx-ingress-controller -f values.yaml`

### Are you using any custom parameters or values?

defaultBackend:
  pdb:
    create: true
    minAvailable: 1

### What is the expected behavior?

The deployment of the PodDisruptionBudget resource.

### What do you see instead?

The error
```
Error: YAML parse error on nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
helm.go:88: [debug] error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
YAML parse error on nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml
```

### Additional information

It seems a tabulation is missing for the match labels added with the `include`.
Replacing `{{- include "common.labels.matchLabels" . | nindent 4 }}` with `{{- include "common.labels.matchLabels" . | nindent 6 }}` should solve the problem.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
