### ISSUE TITLE
[bitnami/etcd] Provide Helm override for --quota-backend-bytes and cronjob for defragmentation 

### ISSUE THREAD

**Issue by gauresh10** [bitnami/charts#10064]
### Name and Version

bitnami/etcd:8.1.30

### What is the problem this feature will solve?

This feature will solve two problems:
1. it will allow the users to configure DB cache to a higher value than the default 2GB. (8 GB is the limit)
2. A cronjob for defragmentation will it easier to maintain the etcd. https://etcd.io/docs/v3.2/op-guide/maintenance/

### What is the feature you are proposing to solve the problem?

Helm override to configure --quota-backend-bytes.
A cron job manifest which is user-controlled.

**Comment by javsalgar** [comment]
Hi,

You don't need to enable the diagnostic mode. The diagnostic mode is for peforming manual repair operations. By default, the diagnostic mode will set the command to a sleep infinity so you can enter without issues.

**Comment by gauresh10** [comment]
ohh Thanks! This worked :) @javsalgar 
I am closing the issue.
