### ISSUE TITLE
Permission Denied when defining securityContext.runAsGroup

### ISSUE THREAD

**Issue by sebastien-helbert** [bitnami/charts#10075]
### Name and Version

bitnami/rabbitmq v9.0.3

### What steps will reproduce the bug?

With this command : `helm upgrade --install --create-namespace --namespace test --set containerSecurityContext.runAsGroup=1001 rabbitmq bitnami/rabbitmq`

### Are you using any custom parameters or values?

containerSecurityContext.runAsGroup=1001

### What is the expected behavior?

Pods should start without error even if runAsGroup is not the default one (root?)

### What do you see instead?

Pods statup fails with Permission denied error.

Pod logs : 
  
```
Subscribe to project updates by watching  
Submit issues and feature requests at  
 
 ==> ** Starting RabbitMQ setup ** 
 ==> Validating settings in RABBITMQ_* env vars.. 
 ==> Initializing RabbitMQ... 
cp: cannot create regular file '/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf': Permission denied 

```

### Additional information

The [chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) does not describe the container parameter SecurityContext.runAsGroup (is it because it is not supported?) but defining this parameter becomes mandatory when a cluster pod security policy do not allow any group to be used.

Defining volumePermissions.enabled does not help because the initContainer should run as root which is usally not permitted by pod security policies.

May be related to https://github.com/bitnami/charts/issues/8379

**Comment by alemorcuq** [comment]
To be able to run as any user, containers expect the group of that user to be 0 so that processes can use group permissions to write files. Being able to support any group ID is not trivial.

Supporting `read only` filesystems may be a solution for this, but unfortunately [it is not a priority for us at the moment](https://github.com/bitnami/charts/issues/8500#issuecomment-1057118831).
