### ISSUE TITLE
Redis sentinel spawning on a different pod instead of as a container

### ISSUE THREAD

**Issue by juanborre** [bitnami/charts#10081]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

We currently use the redis chart to spawn a redis sentinel cluster on Kubernetes.

Sentinels are booted as a container in the redis pods. If the pod is deleted, the sentinel goes away with the redis.
As a consequence, when multiple redis pods are deleted, there are cases where sentinels are unable to perform a failover because the majority of votes can’t be reached.

In our particular example, we have 3 replicas and a quorum of 2. The pods run on preemptible nodes, that are cheaper and can be killed by the K8s engine more frequently than primary nodes. If 2 pods are not available at the same time, the system is locked until another pod is available.
This is because the sentinels go away with the pods but, if the sentinels had a different lifecycle, they could still elect the remaining redis replica to become the master.

### What is the feature you are proposing to solve the problem?

The sentinels could be spawned on different pods, so that their lifecycle was decoupled from that of the redis.

Redis sentinels would act as overseers of the system, switching from one redis replica to another as they are killed and respawned by the Kubernetes engine.

Redis sentinels have very little CPU/memory consumption, so they should be more stable and run on any spare room on nodes. The redis are the ones doing the actual job and demanding resources. This would allow for a scenario where redises are spawned on preemptible nodes and sentinels on primary nodes.
The redises can live on preemptible nodes, being deleted anytime, and the sentinels would switch from one to the other.
The sentinels would be more stable on primary nodes and the system would be more resilient overall.

Don't hesitate if I can provide more detail. 
Thanks

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this and for providing a clear use case example.
  I agree, I think this would be a good idea.
  I have created an internal task to study this further and eventually implement this.
  I am sorry I can not provide an ETA, but we will come back as soon as we have news.
  Meanwhile, maybe you would like to send a PR implementing this. We will be glad to review and merge it.

**Comment by juanborre** [comment]
Hi @rafariossaa ,

Thanks for your answer and for taking this suggestion into consideration.

We will think about making the PR but I'm afraid I can't provide a certainty nor an ETA.

Thanks again!

**Comment by rafariossaa** [comment]
Hi,
  You are welcome.

**Comment by vfiset** [comment]
We have been facing the exact same problem on our side for more than a year. The solution @juanborre proposes would only reduce the chances of occurence but would not fix the real problem which is the fact that a sentinel is not capable of respawing with the exact same config from the other sentinels POV.

**Comment by carrodher** [comment]
Unfortunately, this suggestion was added some time ago and although there is an internal task to evaluate it, it was not planned as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

**Comment by PatelVishalJ** [comment]
Looks like this issue is marked `solved` and moved to `closed` status by mistake. Can it be reopened for visibility?
