### ISSUE TITLE
[bitnami/rabbitmq] Automatic liveness probe fails in Kubernetes, but runs ok if I do manually from cli of the pod

### ISSUE THREAD

**Issue by dburgos92** [bitnami/charts#10086]
### Name and Version

bitnami/rabbitmq 8.32

### What steps will reproduce the bug?

I am using the bitmani chart of rabbitmq 8.32 inside Azure Kubernetes. The Kubernetes version is 1.22.6

### Are you using any custom parameters or values?

No more parameters than `auth.password` and `auth.erlangCookie`

### What is the expected behavior?

Kubernetes should set up a ReplicaSet with two replicas

### What do you see instead?

Node 0 starts ok. When node 1 finishes set up, suddenly liveness probe of the container of rabbitmq in the pod '0' fails, but if I run `rabbitmqctl cluster_status` everything is ok. Also, if I access into /bin/bash console of the node '0', and then runs `rabbitmq-diagnostics -q ping` and `rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics` the results are fine

```
I have no name!@rabbitmq-0:/$ rabbitmq-diagnostics -q ping
Ping succeeded
I have no name!@rabbitmq-0:/$ rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
RabbitMQ on node rabbit@motorcloud-rabbitmq-0.motorcloud-rabbitmq-headless.motorcloud.svc.cluster.local is fully booted and running
Node rabbit@motorcloud-rabbitmq-0.motorcloud-rabbitmq-headless.motorcloud.svc.cluster.local reported no local alarm
```

**Comment by dburgos92** [comment]
I solved the problem. It was that the livennes and readiness probes died by the default timeout of the chart.

I customized the timeouts by default with these parameters:

`
livenessProbe.timeoutSeconds=50
readinessProbe.timeoutSeconds=70
`

**Comment by carrodher** [comment]
I'm glad to see you were able to solve the issue. 🎉 
Feel free to reopen this issue if you find any other similar issue or create a new one if needed
