### ISSUE TITLE
Zookeeper - `metrics.enabled` - do not install an additional metric service 

### ISSUE THREAD

**Issue by guidoiaquinti** [bitnami/charts#10101]
### Name and Version

bitnami/zookeeper latest

### What is the problem this feature will solve?

👋 Hi! First of all thank you very much for the great work you've been doing with the charts. They are great!

In `bitnami/zookeeper` we allow users to enable Prometheus metrics monitoring via the `metrics.enabled` variable.

By enabling it, we enable the Prometheus interface in Zookeeper (via env variables) as well as creating an additional `zookeeper-metrics` service.  

### What is the feature you are proposing to solve the problem?

As the additional service is not always necessary, I think we could make it opt-in.

### What alternatives have you considered?

Do nothing.

**Comment by javsalgar** [comment]
Hi,

Could you explain the use case where you wouldn't want to enable the service?

**Comment by guidoiaquinti** [comment]
> Could you explain the use case where you wouldn't want to enable the service?

If we are already scraping the metrics from the ZK pods, does it make sense to enable the service? My answer would be no but I might be missing something. Thank you!

**Comment by fmulero** [comment]
Probably you right,  linking the creation of the service with the creation of the ServiceMonitor could be a better idea. Would you like to contribute by creating a PR to solve the issue? We will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines
