### ISSUE TITLE
elasticsearch plugin configuration (repository-gcs)

### ISSUE THREAD

**Issue by hawksight** [bitnami/charts#1011]
Firstly, really good chart and base docker images for elasticsearch, a lot of work has clearly gone into the current setup. I am trying to add configuration specifically to the repository-gcs plugin in a container like fashion and coming up empty atm.

**Which chart**:

bitnami/elasticsearch --version 4.2.6
Would affect all versions later  (<4.2.8) as they are just app version bumps

**Description**

I have been able to install elasticsearch using the mentioned helm chart and install the `repository-gcs` plugin with:
```yaml
plugins: "repository-gcs"
```

My issue from here is how can I now configure the plugin, specifically in relation to the elasticsearch.keystore (`/opt/bitnami/elasticsearch/config/elasticsearch.keystore`).

From reading, this is a dynamic configuration and therefore cannot really be supplied via a configmap or secret and mounted to the container at runtime. And I think that's only possible by creating it elsewhere and then copying it over in a binary format (theoretical). Point being that this differs to `elasticsearch.yml` configuration.

So I have created a bucket and a service account (with the right permission) and applied them the the bucket and downloaded my json key. At this point I have moved over to running a single docker container built locally from [here](https://github.com/bitnami/bitnami-docker-elasticsearch/tree/master/6/debian-9) and creating a compose file that looks like this:

```yaml
version: '2'

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:custom-sp'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
     - ELASTICSEARCH_PLUGINS=repository-gcs
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
      - ${PWD}/creds.json:/tmp/creds.json
volumes:
  elasticsearch_data:
    driver: local
```

Where custom-sp is just a tag I used when I built that dockerfile locally.
I then shell into said container and do the following:
```
# Add the creds to the keystore
/opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file gcs.client.snappy.credentials_file /tmp/creds.json
# Reload the keystore on the node
curl -X POST "localhost:9200/_nodes/reload_secure_settings"
# And after getting the right creds on gcloud IAM
curl -X PUT "localhost:9200/_snapshot/test" -H 'Content-Type: application/json' -d'
{
  "type": "gcs",
  "settings": {
    "bucket": "<BUCKET_NAME>",
    "client": "snappy"
  }
}
```

This is config directory after that:
```
I have no name!@eeecae641dee:/$ ls -ltr /opt/bitnami/elasticsearch/config/
total 24
-rw-rw---- 1 root root 5156 Dec 20 16:06 log4j2.properties
drwxrwxr-x 2 root root 4096 Jan  3 11:35 scripts
-rw-rw---- 1 1001 root 3206 Jan  3 13:23 jvm.options
-rw-rw---- 1 root root  315 Jan  3 13:23 elasticsearch.yml
-rw-rw---- 1 1001 root 2564 Jan  3 13:35 elasticsearch.keystore
```

I was able to see content in my bucket and everything is ok. But now I am a little stuck, because all of this was manual. I would like to provide the configuration to elasticsearch via the helm chart is possible. So:

Is there any way to provide `elasticsearch.keystore` configuration to the helm chart currently?
Eg. via `config`?

According to ES docs:
https://www.elastic.co/guide/en/elasticsearch/plugins/6.5/repository-gcs-usage.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.5/secure-settings.html#add-string-to-keystore
https://www.elastic.co/guide/en/elasticsearch/plugins/6.5/repository-gcs-client.html

The config needs to be applied to each node and the keystore needs to be written to.
My current thoughts are the following:
1) Add service account creds in a secret
2) Mount the secret as volume on all nodes to somewhere like `/var/creds.json` or `/tmp/creds.json`
3) Add something to the startup of ES to look for a creds file and load accordingly, eg: `/opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file SETTING FILE`
4) Post install hook or job to reload secure settings. eg:
`curl -X POST "COORDINATINGNODES_SERVICE:9200/_nodes/reload_secure_settings"`
5) Post install hook or job to add my client config based on some pre-filled vars, eg.
`curl -X PUT "COORDINATINGNODES_SERVICE:9200/_snapshot/test" -H 'Content-Type: application/json' -d'
{
  "type": "gcs",
  "settings": {
    "bucket": "<BUCKET_NAME>",
    "client": "snappy"
  }
}`

As I am relatively new to elasticsearch plugins, and helm, i'm really hoping I've missed something obvious as what seemed like a simple configuration appears to require a while host of extra resources and config.
Would it be easier to go and find a curator helm chart and install that to do snapshots for me?

Appreciate all thoughts or suggestions on possible approaches.

**Steps to reproduce the issue:**

Please see above for recreating steps thus far, although this it not really a bug, more of potentially missing features.

**Describe the results you received:**

N/A

**Describe the results you expected:**

N/A

**Additional information you deem important (e.g. issue happens only occasionally):**

In my case, the bucket I am accessing resides in a separate gcloud project and currently the ES install resides in another subnet within its own k8s cluster. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
❯ helm version                                                                                                             ⏎

Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
❯ k version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.7", GitCommit:"572a070abf31a08a8f0d104220da467ea1e3d5f2", GitTreeState:"clean", BuildDate:"2018-11-14T05:26:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

***Side Note***
I don't understand why the elasticsearch.keystore resides in a config directory, yet its dynamic so you can't set without interacting with elasticsearch. ES say it only obfuscates config, so it seems to just make life difficult for very little gain.
The k8s model would seem to suggest that file could be secret and mounted at runtime if it was a regular config file.

**Comment by tompizmor** [comment]
I think you can add a postStart hook to the elasticsearch containers and add the commands you used to run manually.

```
      containers:
      - name: "elasticsearch"
        image: {{ template "elasticsearch.image" . }}
        lifecycle:
          postStart:
            exec:
              command:
                - bash
                - -ec
                - |
                   # Add the creds to the keystore
                   /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file gcs.client.snappy.credentials_file /tmp/creds.json
                   # Reload the keystore on the node
                   curl -X POST "localhost:9200/_nodes/reload_secure_settings"
                   # And after getting the right creds on gcloud IAM
                   curl -X PUT "localhost:9200/_snapshot/test" -H 'Content-Type: application/json' -d'
                   {
                     "type": "gcs",
                     "settings": {
                       "bucket": "<BUCKET_NAME>",
                       "client": "snappy"
                     }
                   }
```

**Comment by tompizmor** [comment]
Hello @hawksight!

To get more info about why the pods are in `PodInitializing` steps forever you can run `kubectl describe`. For example:

```
$ kubectl describe pod elastic-elasticsearch-coordinating-only-597fc9c9b9-9882s
```

And for the second problem, as the postStart hook is running before ES is ready, maybe you can add some logic to wait while ES is not ready (checking if the process is running, if the pid file exists, if the port accepts connections,... )

**Comment by hawksight** [comment]
Thanks I've just re-ran with that config so I can share some extra info from various terminals:

`helm history elastic`

```
11      	Tue Jan  8 18:10:57 2019	DEPLOYED       	elastic-cluster-0.1.0	Rollback to 9
12      	Wed Jan  9 11:27:36 2019	PENDING_UPGRADE	elastic-cluster-0.1.0	Preparing upgrade
```

Pods after running upgrade:
```
NAME                                                       READY     STATUS            RESTARTS   AGE
alpine-python-deploy-5c4d45bf97-gqd5p                      1/1       Running           0          20d
elastic-elasticsearch-coordinating-only-597fc9c9b9-4ztnm   0/1       PodInitializing   0          3m
elastic-elasticsearch-coordinating-only-597fc9c9b9-ph7m7   0/1       PodInitializing   0          3m
elastic-elasticsearch-coordinating-only-c498b56b-r7vpn     1/1       Running           0          16d
elastic-elasticsearch-data-0                               1/1       Running           0          16d
elastic-elasticsearch-data-1                               1/1       Running           0          16d
elastic-elasticsearch-data-2                               0/1       PodInitializing   0          3m
elastic-elasticsearch-master-78fc67b749-f4wcn              1/1       Running           0          16d
elastic-elasticsearch-master-78fc67b749-m4pmz              1/1       Running           0          16d
elastic-elasticsearch-master-849d656f5b-9t97l              0/1       PodInitializing   0          3m
elastic-elasticsearch-master-849d656f5b-dvmtk              0/1       PodInitializing   0          3m
elastic-elasticsearch-metrics-5bb594dfff-bqnsq             1/1       Running           0          3m
```

Events from describing one of the upgrading pods:
```
Events:
  Type    Reason                 Age   From                                                          Message
  ----    ------                 ----  ----                                                          -------
  Normal  Scheduled              1m    default-scheduler                                             Successfully assigned elastic-elasticsearch-coordinating-only-597fc9c9b9-ph7m7 to gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp
  Normal  SuccessfulMountVolume  1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  MountVolume.SetUp succeeded for volume "data"
  Normal  SuccessfulMountVolume  1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  MountVolume.SetUp succeeded for volume "config"
  Normal  SuccessfulMountVolume  1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  MountVolume.SetUp succeeded for volume "default-token-zxkvc"
  Normal  SuccessfulMountVolume  1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  MountVolume.SetUp succeeded for volume "creds"
  Normal  Pulled                 1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  Container image "docker.io/bitnami/minideb:latest" already present on machine
  Normal  Created                1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  Created container
  Normal  Started                1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  Started container
  Normal  Pulled                 1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  Container image "docker.io/bitnami/elasticsearch:6.5.2" already present on machine
  Normal  Created                1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  Created container
  Normal  Started                1m    kubelet, gke-vpc-se-es-cluste-vpc-se-es-cluste-896bb3b8-rdfp  Started container
```

Shelled into a container to check processes etc:
```
$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
1001           1       0 81 11:27 ?        00:00:12 /opt/bitnami/java/bin/java -Xms128m -Xmx128m -XX:+UseConcMarkSweepGC -XX:
1001          31       0  0 11:27 ?        00:00:00 sh -ec /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file gcs
1001          36      31  0 11:27 ?        00:00:00 /bin/bash /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file
1001          38      36 11 11:27 ?        00:00:01 /opt/bitnami/java/bin/java -Des.path.home=/opt/bitnami/elasticsearch -Des
1001         236       0  0 11:27 ?        00:00:00 /bin/sh
1001         241     236  0 11:28 ?        00:00:00 ps -ef
$ /opt/bitnami/elasticsearch/bin/elasticsearch-keystore list
keystore.seed
$ ^[[A^C
$ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
1001           1       0 40 11:27 ?        00:00:21 /opt/bitnami/java/bin/java -Xms128m -Xmx128m -XX:+UseConcMarkSweepGC -XX:
1001          31       0  0 11:27 ?        00:00:00 sh -ec /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file gcs
1001          36      31  0 11:27 ?        00:00:00 /bin/bash /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file
1001          38      36  3 11:27 ?        00:00:01 /opt/bitnami/java/bin/java -Des.path.home=/opt/bitnami/elasticsearch -Des
1001         236       0  0 11:27 ?        00:00:00 /bin/sh
1001         309     236  0 11:28 ?        00:00:00 ps -ef
```

I realised here that the processes were just hanging, possibly because the command to add was too early for ES and it may have just been hanging waiting for a response.

## Next attempt.
After getting that debug info, i've hacked in a sleep into the `postStart` command, eg:
```
        {{- if .Values.snapshot.enabled }}
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -ec
                - sleep 60 && /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file gcs.client.{{ .Values.snapshot.clientName }}.credentials_file /secrets/creds.json
        {{- end }}
```

This seems to work for adding the credential to the keystore. I tried 10s which was fine for data and co-ordinating nodes, but not long enough for master... hence upped to 60 across the board just to be sure ES would be running when the `elasticsearch-keystore` command runs. This works ok during an upgrade.

I'm left with one problem with the helm hooks. As soon as the first data node (stateful set) upgrades, the helm hooks kick in. Problem is that I still have all the other data nodes, and possibly other master / co-ord nodes to complete upgrading before I'm ready to run any hooks.
The jobs currently 'fail' in their intention as not all the ES nodes have the config required in order to do snapshots.

So I've got a few option that I can think of:
1) Run the post-install jobs separately to the helm chart once Im happy they're upgraded. Possibly write the job into the helm upgrade help text for easy copy / apply
2) Figure out some way to have the first job poll the status of the StatefulSet upgrade (ask k8s for something).

I'd preferably go the route of 2. I think I'd need a serviceAccount pre-created with rbac permission to get info from k8s and add that to any Job spec I generate with helm. And then a custom script or something to poll stateful set data and execute the settings reload and client update.

Is it possible for helm to template a script, or am I better off reading env vars / inputs to the script?

**Comment by tompizmor** [comment]
> 1. Run the post-install jobs separately to the helm chart once Im happy they're upgraded. Possibly write the job into the helm upgrade help text for easy copy / apply

Yes. That is an acceptable option.

> 2. Figure out some way to have the first job poll the status of the StatefulSet upgrade (ask k8s for something).

Sincerely I don't know how to do that. In any case, you would need to ask for the upgrade status of the three statefulset no? Data, coordinating and master pods.

My understanding is that you only need to execute the commands from the Jobs one single time once all the statefulset has been upgraded. Is that right?

**Comment by hawksight** [comment]
1 will be the fallback option.

I got a pointer on helm slack channel to [this repo](https://github.com/groundnuty/k8s-wait-for) so I'm going to attempt to use that as my first helm `post-install` hook.

Your right, technically I should wait for all to update, but ingest, coordinating & master are all deployment resources which update much quicker in my relatively small setup.
The data nodes go one at a time and are the slowest. So I figure if I watch them, or maybe watch the statefulset resource I might have a chance of getting something back like.. 1/3, or 2/3 or done or whatever.. will need to look more closely at the upgrade process.

Yer the two curl commands only need run once, but only when every node has the exact same config, otherwise they complete but fail. I'll see if I can work out the details.

I don't suppose Bitnami has any plans for making the elasticsearch chart more customizable?
I'm just trying to think if any of this would be useful to people installing other plugins. As this is the only plugin I've used not sure if many others use the `elasticsearch-keystore`.
Or is is more a case of let people include the chart as a dependency or fork it to their own needs?

**Comment by tompizmor** [comment]
I think there is a way that you only execute the code you want in the latest data node (so at that point all the cluster should have been already updated). 

You know the number of data node replicas and the name of the pod because we are using a statefulset and so the pod name is stable. Hence, as the hostname is stable, you know that if you have 3 data nodes, the hostnames will be datanode-0, datanode-1, datanode-2. And you could do something like:

```
if hostname === {{ "elasticsearch.data.fullname" }}-{{  dataNodeReplicas - 1 }}
   // your code here
fi
```

There is a similar example in the etcd chart, where we want to only enable the authentication in the first node. See https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L104

> I don't suppose Bitnami has any plans for making the elasticsearch chart more customizable?

We are open to make it more customizable as long as the features can be reused and are not tight to a specific use case. I also don't know how common is to use `elasticsearch-keystore` files. I guess for cases like this we check how many users request a feature before including it in the chart.

**Comment by hawksight** [comment]
> I think there is a way that you only execute the code you want in the latest data node (so at that point all the cluster should have been already updated).

That's a brilliant idea, thanks!

I've also found that updates to stateful sets are always done in termination order (from [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates)) so `{{ "elasticsearch.data.fullname" }}-0` should be sufficient as 0 should always update last.

**Comment by tompizmor** [comment]
> I've also found that updates to stateful sets are always done in termination order

Nice! I didn't know it! Did you have time to check if it works?

**Comment by hawksight** [comment]
I had trouble putting more than 1 command into the args section of the `postStart` lifecycle action and the conditional if was making it more difficult again. 
So instead I open to write some python code to talk to the k8s api and get the status of the stateful set. Will share a gist or something when I've tested a little more.

So I now have:
0) `postStart` lifecycle action to add the keystore creds.
1) `post-install` / `post-upgrade` hook 1 - custom python script waiting for all data nodes to be updated & ready.
2) `post-install` / `post-upgrade` hook 2 - basic container with curl to reload-secure settings.
3) `post-install` / `post-upgrade` hook 3 - basic container - sleeps for a tiny bit (because I found the last step was executing too soon and failing)
4) `post-install` / `post-upgrade` hook 4 - basic container with curl to apply the client details.

I've ran that a couple times upgrading the cluster between various 6.5.X versions and so far it's worked. Also have to pass a longer timeout to helm, in the region of `--timeout=600` for 3 data nodes. And I settled for using the notes section to write in the various snapshot commands for future reference.

Looking back I'd probably condense steps 1-4 into a single script with a single helm hook, or even just a separate job entirely.

With the amount of changes I've applied to the original chart, I'm really not sure if it's general enough to contribute much back, other than as an example. I think the requirement may be niche and stem from a not particularly helpful elasticsearch-keystore. If this had been ES on VM's it would be a few ansible (or other CM tool) tasks dropped into a playbook and job done.

Thank you for your help though, this has been my first undertaking with helm and actually adding to the bitnami chart was easier than I thought it would be.

**Comment by hawksight** [comment]
Thanks for the example @tompizmor that's really helpful. I'm happy to close the issue given I have a solution currently. I will post back links at some point, I just think my use case is a little too specific to port back into the chart currently.

**Comment by anton-chuhunou** [comment]
Same issue here. We were not able to configure chart to work with bucket.

**Comment by javsalgar** [comment]
Hi,

Did you try using the init scripts feature of the chart? There you could add commands to configure the bucket.  https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/values.yaml#L155

**Comment by polymorpher** [comment]
> Hi,
> 
> Did you try using the init scripts feature of the chart? There you could add commands to configure the bucket. https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/values.yaml#L155

I have, using configMaps in combination with extraVolume(Mount). It works, which makes it a much cleaner solution.

I tried building my own custom image from bitnami/elasticsearch but my entrypoint was somehow always ignored by Kubernetes. Took me at least a day trying to fix it.

**Comment by javsalgar** [comment]
> Took me at least a day trying to fix it.

Were you able to find out the cause?

**Comment by polymorpher** [comment]
> > Took me at least a day trying to fix it.
> 
> Were you able to find out the cause?

No. I tried many things but none of them worked. Had to move on. Would love to see if someone eventually found out why.

**Comment by evandro-morini** [comment]
I did it using initScripts and initContainers this way:
```yaml
initScripts:
  keystore_add_script.sh: |
    #!/bin/sh
    if [[ $(hostname -s) = elasticsearch-master-* ]]; then
      /opt/bitnami/elasticsearch/bin/elasticsearch-keystore add-file gcs.client.default.credentials_file /service-account/credentials.json --force
    fi
master:
  initContainers:
    - name: snapshot-init
      image: bitnami/minideb
      imagePullPolicy: "IfNotPresent"
      command:
      - "/bin/bash"
      - "-c"
      args:
      - |
        sleep 90 && \
        install_packages curl && \
        curl -X POST 'http://elasticsearch-master.default.svc.cluster.local:9200/_nodes/reload_secure_settings' && \
        curl -X PUT 'http://elasticsearch-master.default.svc.cluster.local:9200/_snapshot/extraction-manager' -H 'Content-Type: application/json' -d '{ "type": "gcs", "settings": { "client": "default", "bucket": "your-storage-bucket", "compress": true }}'
```
And a cronjob to do the snapshots:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-elastic-snapshot
spec:
  schedule: "0 2,8,14,20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: snapshot-init
            image: bitnami/minideb
            imagePullPolicy: "IfNotPresent"
            command:
            - "/bin/bash"
            - "-c"
            args:
            - |
              install_packages curl && \
              curl -X PUT "http://elasticsearch-master.default.svc.cluster.local:9200/_snapshot/extraction-manager/$(date -u +%Y%m%d.%H%M)?wait_for_completion=true&pretty"
          restartPolicy: OnFailure
```

**Comment by MarcinGinszt** [comment]
Sorry to necro this topic.
If keystore would not be wiped out on pod start, we wouldn't have to deal with it. I created [issue about that](https://github.com/bitnami/containers/issues/64115).

For a workaround, I think I found elegant solution- overriding the ElasticSearch  container command to create keystore and wait for start. 
You would have to patch `elasticsearch` container with 
```
          command:
            - bash
            - -c
          args:
            - |
              ( # this process should wait in the background for the ES to start and then configure the keystore
                cd ./opt/bitnami/elasticsearch/bin/
                echo "waiting for elastic search to start"
                # wait for the elasticsearch to be ready before editing keystore
                # S3 repository won't work before this time
                sleep 120
                echo $AWS_SECRET_ACCESS_KEY | ./elasticsearch-keystore add -f --stdin s3.client.default.secret_key
                echo $AWS_ACCESS_KEY_ID | ./elasticsearch-keystore add -f --stdin s3.client.default.access_key
                echo "added AWS credentials to keystore"
                curl -X POST "elasticsearch:9200/_nodes/reload_secure_settings"
                echo "refreshed keystore"
              ) &
              /opt/bitnami/scripts/elasticsearch/entrypoint.sh /opt/bitnami/scripts/elasticsearch/run.sh
```

**Comment by MarcinGinszt** [comment]
Sorry to necro this topic- another solution which doesn't require creating additional resources, would be overriding the container enterypoint to start background process, which reload settings after some time

```yaml
          command:
            - bash
            - -c
          args:
            - |
              ( # this process should wait in the background for the ES to start and then configure the keystore
                cd ./opt/bitnami/elasticsearch/bin/
                echo "waiting for elastic search to start"
                # wait for the elasticsearch to be ready before editing keystore 
                # S3 repository won't work before this time
                sleep 120 
                echo $AWS_SECRET_ACCESS_KEY | ./elasticsearch-keystore add -f --stdin s3.client.default.secret_key
                echo $AWS_ACCESS_KEY_ID | ./elasticsearch-keystore add -f --stdin s3.client.default.access_key
                echo "added AWS credentials to keystore"
                curl -X POST "elasticsearch:9200/_nodes/reload_secure_settings" 
                echo "refreshed keystore"
              ) &
              /opt/bitnami/scripts/elasticsearch/entrypoint.sh /opt/bitnami/scripts/elasticsearch/run.sh
```
