### ISSUE TITLE
[bitnami/mongodb] stuck in "Validating settings in MONGODB_* env  vars... when running in minikube or docker-desktop

### ISSUE THREAD

**Issue by mcanaleta** [bitnami/charts#10126]
### Name and Version

bitnami/mongodb 12.x

### What steps will reproduce the bug?

Environment: docker-desktop or minikube (in OSX)

Commands: 

`helm install mongodb-test bitnami/mongodb`

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

Mongodb should start.

### What do you see instead?

```
% kubectl  logs -l app.kubernetes.io/name=mongodb  
mongodb 11:12:12.78 
mongodb 11:12:12.80 Welcome to the Bitnami mongodb container
mongodb 11:12:12.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 11:12:12.85 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 11:12:12.87 
mongodb 11:12:12.89 INFO  ==> ** Starting MongoDB setup **
mongodb 11:12:13.08 INFO  ==> Validating settings in MONGODB_* env vars...
```

And that's all I get. No more errors, the container is just waiting for something. I tried to see more logs but was not able to see anything else (tried LOG_LEVEL=debug, BITNAMI_DEBUG=true, systemLogVerbosity: 5).

Any idea?

### Additional information

When trying the same default install in GKE it works without problems.

Thanks!

**Comment by carrodher** [comment]
Is your Macbook an M1 based on ARM? Please note that Bitnami images are not ready for ARM

**Comment by mcanaleta** [comment]
Actually yes. Ok then I guess that's the issue. Thanks!
