### ISSUE TITLE
[bitnami/kibana] Duplicated environment variables and possibly wrong environment variable name

### ISSUE THREAD

**Issue by burjandedes** [bitnami/charts#10121]
### Name and Version

bitnami/kibana 10.0.6

### What steps will reproduce the bug?

1. Environment: doesn't matter
2. Config: see below
3. Run helm template or helm install
4. Errors: duplicated environment variables and possibly wrong environment variable name.

### Are you using any custom parameters or values?

--set elasticsearch.security.auth.enabled=**true** 
--set elasticsearch.security.auth.createSystemUser=**true**

### What is the expected behavior?

I think this environment variable meant to be **ELASTICSEARCH_PASSWORD**.

### What do you see instead?

I see two **KIBANA_PASSWORD** environment.

https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/deployment.yaml#L157

### Additional information

I want to create an Umbrella Helm chart.
I generated the elastic password with the Elasticsearch Helm chart. The secret created successfully and the key is **elastic-password** (https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/secrets.yaml#L16).
I used the elasticsearch.security.auth.elasticsearchPasswordSecret parameter, but the key used by the Kibana Helm Chart is **password** (https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/deployment.yaml#L161).

![kép](https://user-images.githubusercontent.com/1625558/167832704-1c156944-a565-4044-8e23-3d99480bd436.png)

**Comment by migruiz4** [comment]
Hi @burjandedes,

I'm sorry for the inconvenience. I have submitted this PR #10237 fixing this issue.

**Comment by burjandedes** [comment]
Hi @migruiz4,
Thank you very much.
