### ISSUE TITLE
[bitnami/logstash] Add securityContext to metric container (logstash exporter)

### ISSUE THREAD

**Issue by rubyalwaystaken** [bitnami/charts#10186]
### Name and Version

bitnami/logstash

### What is the problem this feature will solve?

The securityContext on the metrics container containing the logstash-exporter can't be configured. 

Some securityContext settings (runAsUser, runAsNonroot) can be applied to the PodSecurityContext, which then is inherited by the metrics container.

ContainerSecurityContext-locked settings like ReadOnlyRootFilesystem can't be applied to the metrics container though. 3rd-Party Tools are needed to achieve this

### What is the feature you are proposing to solve the problem?

Add a 2nd containerSecurityContext for the metrics container

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the input! Would you like to submit a PR adding this section?

**Comment by migruiz4** [comment]
Hi @rubyalwaystaken,

I'm sorry but the latest major of the `bitnami/logstash` chart ([5.0.0](https://github.com/bitnami/charts/blob/master/bitnami/logstash/README.md#to-500)) deprecates the logstash-exporter container and the `metrics.*` parameters, so this feature request no longer applies.

Logstash exporter can still be configured using the values `sidecars` and `extraDeploys`, but we won't continue releasing updates of the [bitnami/logstash-exporter](https://github.com/bitnami/bitnami-docker-logstash-exporter) image.
