### ISSUE TITLE
[bitnami/kube-prometheus] Not able to install prometheus

### ISSUE THREAD

**Issue by kridafans** [bitnami/charts#10218]
### Name and Version

bitnami/kube-prometheus

### What steps will reproduce the bug?
```
helm install prometheus bitnami/kube-prometheus
```
### Are you using any custom parameters or values?

NO

### What do you see instead?
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "probeNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "probeSelector" in com.coreos.monitoring.v1.Prometheus.spec]
```

**Comment by FraPazGal** [comment]
Hello @kridafans,

I have been able to install the latest chart version in a fresh cluster. Could you try on your side using a new cluster? If you can't, please make sure to remove any dangling CRDs before doing the `helm install`.
