### ISSUE TITLE
Customize redis-cluster metrics container name

### ISSUE THREAD

**Issue by apena-matriz** [bitnami/charts#10219]
### Name and Version

bitnami/redis-cluster 7.5.3

### What is the problem this feature will solve?

Metrics container name is not customizable.

### What is the feature you are proposing to solve the problem?

Allow the name of the metric container to be customizable

### What alternatives have you considered?

Add "containreName" option into metrics section on values.yaml file.

**Comment by rafariossaa** [comment]
Hi,
  Changing the container name is something that is not configurable in all our chart catalogue.
  Could you provide some feedback about your use case and why this is needed ?

**Comment by apena-matriz** [comment]
Hi @rafariossaa, thansk for your reply.
If it's not posible to customize the container name, at least could you change the name to **redis-metrics** so it's a little more descriptive ?? In many cases (if not all) it's not the only metrics container in a k8s cluster.

**Comment by rafariossaa** [comment]
Hi,
  In this case the same would happen if there is several redis-cluster deployments in the same k8s cluster.
  If you are using prometheus operator you can use `metrics.serviceMonitor.enabled` to create the needed CRD, but in the case you are reaching directly the containers you can identify them because they have a name like `k8s_metrics_myredisclus-redis-cluster-0_default_c595d089-2d38-4476-b06f-78999a28d77e_0` (in this case this is the name of the container  `metrics` in the pod `redis-cluste-0` from the `myredisclus` chart deployment).

**Comment by apena-matriz** [comment]
Yes, it's true if there are severaks redis-clusters, but just "metrics" it's very generic. At least, with redis-metrics you can differentiate it from other metric containers.
Another way is to call the contaier [redis-cluster-name]-metrics, where [redis-cluster-name] is set in the helm installation command.

**Comment by rafariossaa** [comment]
Could not be possible to use something like `label: my-release AND namespace: my-ns AND app-name: redis-cluster AND container: metrics` ?

**Comment by apena-matriz** [comment]
I'm already using the label and the namespace. Yes, I can identify from a list of containers or even in Grafana having an exclusive dashboard but something like ´redis-metrics´ would be great... just 'metrics' it's very generic.

**Comment by rafariossaa** [comment]
Hi,
  Currently, that naming is the standard that we have used for all our charts. Also, I think it has the advantage that, with a query similar to the above, one you can get all the metrics container form different charts without needing to know the name of the deployments.
  This could be a matter on how each one organize the deployments to suit its own use case. Maybe you want to consider changing it the template before performing your deployment.

**Comment by nixancha** [comment]
@apena-matriz Can you please share the grafana dashboard you are using for [bitnami/redis-cluster] ? I can't seem to find one that works with bitnami/redis-cluster. I always get 502 for it.

**Comment by devops-matriz** [comment]
FYI... the Redis Exporter is based in [this one](https://github.com/oliver006/redis_exporter).
