### ISSUE TITLE
MySQL in Kubernetes cluster keeps restarting

### ISSUE THREAD

**Issue by dh9dat** [bitnami/charts#10227]
### Name and Version

bitnami/mysql

### What steps will reproduce the bug?

I have a single-node Kubernetes cluster (see version info below) running on my Linux Mint 19 (Tara) box, and I'm trying to deploy mysql with helm. The installation runs, and it seems that the database is coming up - but, a few minutes later it's shut down and restarted, and the POD changes from Running to CrashLoop, and it never enters the ready state.
Some more info, output of "kubectl version":
```console
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
```
Command used for installation (see also content of mysqldb.yml below):
```console
$ helm install mysql-test -f mysqldb.yml bitnami/mysql
```
And finally, some log output:
```console
kubectl logs -f mysql-test-0
mysql 12:56:06.10 
mysql 12:56:06.11 Welcome to the Bitnami mysql container
mysql 12:56:06.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 12:56:06.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 12:56:06.12 
mysql 12:56:06.12 INFO  ==> ** Starting MySQL setup **
mysql 12:56:06.17 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 12:56:06.18 INFO  ==> Initializing mysql database
mysql 12:56:06.19 DEBUG ==> Ensuring expected directories/files exist
mysql 12:56:06.21 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 12:56:06.21 INFO  ==> Using persisted data
mysql 12:56:06.26 INFO  ==> Running mysql_upgrade
mysql 12:56:06.27 INFO  ==> Starting mysql in background
2022-05-15T12:56:06.727764Z 0 [Warning] [MY-011068] [Server] The syntax 'skip_slave_start' is deprecated and will be removed in a future release. Please use skip_replica_start instead.
2022-05-15T12:56:06.728012Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-05-15T12:56:06.728065Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.28) starting as process 50
2022-05-15T12:56:06.733412Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-05-15T12:56:06.733438Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-05-15T12:56:06.750794Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-05-15T12:56:07.880224Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-05-15T12:56:08.279784Z 4 [System] [MY-013381] [Server] Server upgrade from '80028' to '80028' started.
2022-05-15T12:57:38.714858Z 4 [System] [MY-013381] [Server] Server upgrade from '80028' to '80028' completed.
2022-05-15T12:57:39.272917Z 0 [System] [MY-010229] [Server] Starting XA crash recovery...
2022-05-15T12:57:39.296477Z 0 [System] [MY-010232] [Server] XA crash recovery finished.
2022-05-15T12:57:39.691424Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2022-05-15T12:57:39.691543Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2022-05-15T12:57:39.781694Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.28'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.
2022-05-15T12:57:39.781578Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock
find: '/docker-entrypoint-startdb.d/': No such file or directory
mysql 12:57:40.51 INFO  ==> Stopping mysql
2022-05-15T12:57:40.518654Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.28).
mysql 12:57:50.54 DEBUG ==> Waiting for mysql to unlock db files
/bitnami/mysql/data/ibdata1:
/bitnami/mysql/data/ib_logfile1:
/bitnami/mysql/data/ib_logfile0:
/bitnami/mysql/data/ibdata1:
/bitnami/mysql/data/ib_logfile1:
/bitnami/mysql/data/ib_logfile0:
/bitnami/mysql/data/ibdata1:
/bitnami/mysql/data/ib_logfile1:
/bitnami/mysql/data/ib_logfile0:
/bitnami/mysql/data/ibdata1:
/bitnami/mysql/data/ib_logfile1:
/bitnami/mysql/data/ib_logfile0:
    50    50    50    50    50    50    50    50    50    50    50    502022-05-15T12:58:08.750717Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.28)  Source distribution.
```

### Are you using any custom parameters or values?
```yaml
# Disabled Startup and Liveness probe
auth:
  database: testdb
  username: testuser
  password: test123
  rootPassword: test123
primary:
  persistence:
    existingClaim: mysql-pvc
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
image:
  debug: true
```
PV-Claim is present and ready to use:
```console
$ kubectl get pvc
NAME        STATUS   VOLUME     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mysql-pvc   Bound    mysql-pv   2Gi        RWO,ROX                       133m
```

### What is the expected behavior?

The database started and pod in "ready" state

### What do you see instead?

the database is restarted, again and again, pod never reaches a ready state

### Additional information

I'm a bit new to Kubernetes and containers (it's my first try), so please apologize if I've made some stupid errors, thanks!

Regards from Germany,

Harald

**Comment by dh9dat** [comment]
Hm, interesting: I've left my installation for some time, and guess what, MySQL is running and the POD is ready:
hhuseman@gandalf:~$ kubectl get pods
NAME           READY   STATUS    RESTARTS         AGE
mysql-test-0   1/1     Running   21 (3h14m ago)   4h37m
So, it took 21 restarts and more than an hour to get mySQL up and running...

**Comment by carrodher** [comment]
I'm not able to reproduce this issue in my environment. Are you able to reproduce the issue with out using an existing PVC? Not sure if the issue can be related to attaching an already existing PVC with some data on it

**Comment by carrodher** [comment]
That shouldn't be the issue at least for a "regular" deployment, but if the PVC contains a huge amount of data maybe you need to fine-tune the liveness/readiness probes, just in case the container needs more time to complete the initialization due to 1) amount data in the PVC and 2) low system resources.

**Comment by dh9dat** [comment]
Hi,

hm, the PVC should be empty since I just created it for this test.

Concerning probes, here's my YAML controlfile used to setup the POD:

=============/snip/============

auth:
   database: testdb
   username: testuser
   password: ***
   rootPassword: ***
primary:
   persistence:
     existingClaim: mysql-pvc
     startupProbe:
       enabled: false
     livenessProbe:
       enabled: false
image:
   debug: true

============/snap/==============

So, I'd suppose that liveness and readiness probes should be disabled 
already, don't they?

Am 18.05.22 um 07:56 schrieb Carlos Rodríguez Hernández:

**Comment by carrodher** [comment]
Are you able to reproduce the issue with out using an existing claim? Maybe there is an issue with the permission in the already existing PV and you need to use the pre-configured init container in order to set them in the proper way, see https://github.com/bitnami/charts/tree/master/bitnami/mysql#volume-permissions-parameters

**Comment by dh9dat** [comment]
Hello Carlos,

thanks for your reply, and please excuse my late answer. I was a bit 
busy in the last days... I've tried to install the DB without an 
existing claim, but now it persists in "Pending", so, I'd suppose I made 
a mistake somewhere (as said, I'm a bit new to Kubernetes).

Here's my current YAML-file:

auth:
   database: testdb
   username: testuser
   password: ***
   rootPassword: test123
primary:
   persistence:
     startupProbe:
       enabled: false
     livenessProbe:
       enabled: false
image:
   debug: true

And that's the command I've used to deploy the POD: "helm install 
mysql-test -f mysqldb-wo_pvc.yml bitnami/mysql"

Thanks and best regards from Germany,

Harald

Am 19.05.22 um 14:19 schrieb Carlos Rodríguez Hernández:

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MySQL container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
