### ISSUE TITLE
Changing from standalone to replication mode is not performed automatically

### ISSUE THREAD

**Issue by ListentoNews** [bitnami/charts#10229]
### Name and Version

bitnami/postgresql 11.1.29

### What steps will reproduce the bug?

1. Deploy postgres in standalone mode first. With/out replication password
2. Then change architecture to replication mode.
3. Try to deploy, it shows error about missing key `replication-password` in posgtres-secret.

### What is the expected behavior?

It should update the architecture

### What do you see instead?

Error: template: postgresql/templates/secrets.yaml:23:27: executing "postgresql/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "replication-password" "providedValues" (list "auth.replicationPassword") "context" $)>: error calling include: template: postgresql/charts/common/templates/_secrets.tpl:98:103: executing "common.secrets.passwords.manage" at <fail>: error calling fail:
PASSWORDS ERROR: The secret "postgres-staging-nv2uma-postgresql" does not contain the key "replication-password"

**Comment by rafariossaa** [comment]
Hi,
  Updating from standalone to replication is something that is not allowed because the configuration is only performed the first time the chart is deployed.
