### ISSUE TITLE
MongoDB Chart does not run on bare metal

### ISSUE THREAD

**Issue by ongurd** [bitnami/charts#1022]
**Which chart**:
stable/mondogb 

**Description**
When I want to install stable/mongodb to a Kubernetes cluster running on a bare metal, Mongodb is not starting.  BTW It is running perfectly fine on AWS. 

Here is the kubectl logs PODNAME output;
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> Configuration files found...
```

Nothing happens after Configuration files found INFO

All the persistent volume claims are bound successfully. 

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @ongurd 

Could you install the chart enabling the debug mode in the MongoDB images? This way we can obtain more information in the logs so we can identify the issue.

Please install the chart using the commands below:

```
$ helm repo update 
$ helm install --name mongo stable/mongodb --set image.debug=true
```

**Comment by ongurd** [comment]
Hi @juan131 
Even it was for the debugging thank you very much for your suggestion. Because honestly running repo update did the trick.

**Comment by juan131** [comment]
Great @ongurd 

I'm glad you could solved the issue updating your charts repositories!
