### ISSUE TITLE
external-dns - no hetzner with chart version 6.4.0

### ISSUE THREAD

**Issue by is2admin** [bitnami/charts#10230]
### Name and Version

bitnami/external-dns:6.4.0

### What steps will reproduce the bug?

Use Helm Chart 6.4.0

Use Provider "hetzner"

Deploy

### What is the expected behavior?

It deploys and adds DNS Entries - working with Version 5.5.0

### What do you see instead?

Error - CrashLoopBackOff on Deployment
```
level=fatal msg="flag parsing error: enum value must be one of aws,aws-sd,google,azure,azure-dns,azure-private-dns,alibabacloud,cloudflare,rcodezero,digitalocean,dnsimple,akamai,infoblox,dyn,designate,coredns,skydns,inmemory,ovh,pdns,oci,exoscale,linode,rfc2136,ns1,transip,vinyldns,rdns,scaleway,vultr,ultradns,godaddy,bluecat,gandi,safedns, got 'hetzner'"
```

**Comment by is2admin** [comment]
Version 5.6.0 is working too

**Comment by is2admin** [comment]
Version 6.1.0 and 6.2.0 is working too - with 6.3.0 this issue happens

**Comment by javsalgar** [comment]
Hi,

Could you check with the upstream external-dns devs? Maybe the flag was removed

**Comment by is2admin** [comment]
i think i found it:

- https://github.com/kubernetes-sigs/external-dns/issues/2653
- https://github.com/kubernetes-sigs/external-dns/issues/2660

![image](https://user-images.githubusercontent.com/100195667/168582342-d4488b91-f6aa-43f1-b33e-3a57ade99dcc.png)
