### ISSUE TITLE
AOF file size greater than memory allocated to redis nodes

### ISSUE THREAD

**Issue by rajyadav911** [bitnami/charts#10247]
### Name and Version

bitnami/redis-cluster

### What steps will reproduce the bug?

AOF file size greater than memory allocated to redis nodes.

I have redis nodes with 16Gi each but aof file size is going greater than 16Gi and has reached 24Gi.

1. Is aof file journey of all the keys ?
2. I am adding keys processing it and deleting it and adding new keys. So will aof keep sync of all the deleted keys as well ?

### What do you see instead?

AOF file size greater than memory allocated to redis nodes.

I have redis nodes with 16Gi each but aof file size is going greater than 16Gi and has reached 24Gi.

1. Is aof file journey of all the keys ?
2. I am adding keys processing it and deleting it and adding new keys. So will aof keep sync of all the deleted keys as well ?

**Comment by rafariossaa** [comment]
Hi,
  As this is not really an issue with the chart, I would suggest you to ask in redis forums. I think they can provided better help with all the ins and outs of the AOF files.
