### ISSUE TITLE
bitnami/elasticsearch upgrade failed

### ISSUE THREAD

**Issue by ismail-sener** [bitnami/charts#10240]
### Name and Version

bitnami/elasticsearch

### What steps will reproduce the bug?

My elasticsearch chart version is 8.0.0. I want to upgrade this version to 8.0.1.

I get an error when I run the following command.

helm upgrade elasticsearch bitnami/elasticsearch --version 8.0.1 -n elastic

### What is the expected behavior?

Upgrade of bitnami/elasticsearch 

### What do you see instead?
```
 UPGRADE FAILED: template: elasticsearch/templates/master-statefulset.yaml:31:10: executing "elasticsearch/templates/master-statefulset.yaml" at <include "elasticsearch.imagePullSecrets" .>: error calling include: template: elasticsearch/templates/_helpers.tpl:168:41: executing "elasticsearch.imagePullSecrets" at <.Values.image.pullSecrets>: can't evaluate field pullSecrets in type interface {}
```

**Comment by rafariossaa** [comment]
Hi,
 When upgrading you need to use the same password. Not sure if this is your case here. 
  Could you indicate how you deployed it the first time ?
