### ISSUE TITLE
mongodb can't be installed by helm install

### ISSUE THREAD

**Issue by kenny19850514** [bitnami/charts#10255]
### Name and Version

bitnami/mongdb v12.1.3

### What steps will reproduce the bug?
```console
helm repo add bitnami https://charts.bitnami.com/bitnami
helm search repo bitnami
helm install mongodb --values test-mongodb-values.yaml bitnami/mongodb
```
test-mongodb-values.yaml just as below
```yaml
architecture: replicaset
replicaCount: 3
persistence:
    storageClass: "nfs-client"
auth:
    rootPassword: xxxxxxxxxxx
```

### What is the expected behavior?

3 mongodb pods created successfully.
It works days before.. 

### What do you see instead?
```
mongodb 07:43:59.64
mongodb 07:43:59.64 Welcome to the Bitnami mongodb container
mongodb 07:43:59.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 07:43:59.64 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 07:43:59.64
mongodb 07:43:59.64 INFO  ==> ** Starting MongoDB setup **
mongodb 07:43:59.67 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 07:43:59.88 INFO  ==> Initializing MongoDB...
mongodb 07:44:00.90 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 336:    41 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
```

### Additional information

Ubuntu 20.04 TLS
Storage Class: nfs-client
NFS server ready and mounted on every nodes

**Comment by javsalgar** [comment]
Hi,

Could you try it again without using the NFS storage class? Just to confirm that the issue is there

**Comment by Lucaber** [comment]
mongodb 5 on x86 requires a cpu with avx, check your cpu flags of the kubernetes node with `lscpu | grep avx`

**Comment by barisvelioglu** [comment]
> 

This was my problem. I went back to the 4.4 version

**Comment by barisvelioglu** [comment]
> mongodb 5 on x86 requires a cpu with avx, check your cpu flags of the kubernetes node with `lscpu | grep avx`


This was my problem. I went back to the 4.4 version

**Comment by fmulero** [comment]
As Luca explained, mongodb 5.0 requires a [CPU with AVX support on x86 architectures](https://www.mongodb.com/docs/manual/administration/production-notes/#platform-support)

**Comment by guhuajun** [comment]
> mongodb 5 on x86 requires a cpu with avx, check your cpu flags of the kubernetes node with `lscpu | grep avx`

Brilliant! Failed to deploy mongodb on an Intel J6412/K3D setup, let me fallback to csv data source for running my backtesting apps. LOL

**Comment by jadsy2107** [comment]
> As Luca explained, mongodb 5.0 requires a [CPU with AVX support on x86 architectures](https://www.mongodb.com/docs/manual/administration/production-notes/#platform-support)

Hi @fmulero  

How did you manager to change the version ? 
helm install mongodb TrueCharts/mongodb 

Do you use values.yaml file ? I can't see the parameter for version in there
https://github.com/truecharts/charts/blob/master/charts/dependency/mongodb/values.yaml

**Comment by fmulero** [comment]
Please see [helm documentation](https://helm.sh/docs/helm/helm_install/#helm-install)

**Comment by GermanAizek** [comment]
@fmulero, 
There is an option to take my patch to automate the build without Sandy Bridge optimizations.
https://github.com/GermanAizek/mongodb-without-avx

**Comment by 0x1def** [comment]
Hi,
we compile binaries and build images without AVX requirement for our needs.
If those artifacts suit you, give it a try.
https://github.com/flakybitnet/mongodb-docker
