### ISSUE TITLE
Question: How do you sync the upstreamed charts?

### ISSUE THREAD

**Issue by alonl** [bitnami/charts#1027]
**Which chart**:

upstreamed/*

**Description**

Hi guys,
I'm sorry if this is not the right channel for this kind of questions (unfortunately I saw that the Slack team is closed). Feel free to close this issue if it's not.
My question is - how are the upstreamed charts kept in sync with [helm/charts](https://github.com/helm/charts/)? I see this [comment here](https://github.com/bitnami/charts/issues/753#issuecomment-413586627), for example - where is this CI logic stored?
We are trying to set up a similar mechanism...

Thanks in advance,

**Comment by javsalgar** [comment]
cc @andresrc

**Comment by andresrc** [comment]
Hi @alonl ,

The CI logic is executed in an internal CI system, but the logic is as follows:

- The contents of the `upstreamed` folder are removed.
- Those stable charts from  https://github.com/helm/charts/ that are maintained by Bitnami are copied.
- If there is ay change in the git index, a new commit is generated and pushed to this repo.

**Comment by alonl** [comment]
Many thanks guys <3
