### ISSUE TITLE
Deploying wordpress with autoscalling (and targets) errors on `unknown field "targetAverageUtilization"`

### ISSUE THREAD

**Issue by ExploHash** [bitnami/charts#10272]
### Name and Version

bitname/wordpress 14.2.1

### What steps will reproduce the bug?

helm install the wordpress chart with autoscaling true and memory and cpu target set

### Are you using any custom parameters or values?

Values.yaml:
```
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPU: 80
  targetMemory: 80
```

### What is the expected behavior?

It will install the provided chart

### What do you see instead?

It failed with the error:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource]
```

### Additional information

We use kubernetes version `v1.22.8` and our suspicions are that the the if statement at [Line 26](https://github.com/bitnami/charts/blob/c830c5efb2063113a8e56251306dfdd9e2206ebf/bitnami/wordpress/templates/hpa.yaml#L26) and [Line 38](https://github.com/bitnami/charts/blob/c830c5efb2063113a8e56251306dfdd9e2206ebf/bitnami/wordpress/templates/hpa.yaml#L38) of the hpa template should be changed to a lower version. I can't really pinpoint which version of kubernetes changes this though

**Comment by diranged** [comment]
I just ran into this problem with the thanos chart as well - it has the same lines, and they are wrong. We're also on Kubernetes 1.22.

**Comment by javsalgar** [comment]
Hi,

@miguelaeh is working on fixing issues with the HPA yaml. This should be solved in a future revision

**Comment by ExploHash** [comment]
Nice, thanks!

**Comment by javsalgar** [comment]
AFAIK, @miguelaeh already fixed this, so the issue can be closed.
