### ISSUE TITLE
[bitnami/elasticsearch] (18.0.4) Error enabling autoscaling

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#10276]
### Name and Version

bitnami/elasticsearch 18.0.4

### What steps will reproduce the bug?

1. AWS EKS
2. Kubernetes 1.21

### Are you using any custom parameters or values?

```yaml
master:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPU: 80
    targetMemory: 60
```

### What is the expected behavior?

Success :laughing: 

### What do you see instead?

```
error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[1].resource): missing required field "target" in io.k8s.api.autoscaling.v2beta2.ResourceMetricSource] 
```

### Additional information

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#resourcemetricsource-v2beta1-autoscaling

![image](https://user-images.githubusercontent.com/1277613/168833329-075790c9-d0e4-4ee4-b586-05bd366c6a81.png)

**Comment by marcosbc** [comment]
Hi @carlosjgp, sorry for the delay. This issue should have been fixed already. Let us know if you find any issues.
