### ISSUE TITLE
I need mariadb, redis, minio, es, rabbitmq, postgresql, etcd that support arm64

### ISSUE THREAD

**Issue by hamishliu** [bitnami/charts#10285]
### Name and Version

1

### What is the problem this feature will solve?

I need mariadb, redis, minio, es, rabbitmq, postgresql, etcd that support arm64 helm charts and images， Is there source code available for me to build？

### What is the feature you are proposing to solve the problem?

I need mariadb, redis, minio, es, rabbitmq, postgresql, etcd that support arm64 helm charts and images， Is there source code available for me to build？

### What alternatives have you considered?

I need mariadb, redis, minio, es, rabbitmq, postgresql, etcd that support arm64 helm charts and images， Is there source code available for me to build？

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by hamishliu** [comment]
Which social software can I use to communicate with you in time?

**Comment by carrodher** [comment]
At this moment, we provide support via GitHub issues, this is the right support channel

**Comment by hamishliu** [comment]
https://downloads.bitnami.com/files/stacksmith/mariadb-10.5.15-4-linux-amd64-debian-10.tar.gz

**Comment by hamishliu** [comment]
Can you tell me where the binary source code you used to build mariadb is? I want to compile and adapt to arm by myself, thank you!

**Comment by carrodher** [comment]
The source code is downloaded from https://archive.mariadb.org/mariadb-VERSION/source/mariadb-VERSION.tar.gz, where `VERSION` is a placeholder for the different MariaDB versions supported

**Comment by hamishliu** [comment]
Can you give me permission for a product library? I want to upload the adapted arm64 binaries to the https://downloads.bitnami.com/files/stacksmith/ artifact warehouse so that I can reuse your code base to build the image.

**Comment by carrodher** [comment]
Unfortunately, it is not possible, in that server only the automated test & release pipeline is able to push those intermediate artifacts.
If you want to customize the container in order to support ARM we can't provide this kind of support in terms of infra or guidance. If at some point it is decided to go ahead with this project, we will support ARM end-to-end in the automated test & release pipeline, but not via workarounds or exceptions.

**Comment by hamishliu** [comment]
Hello, I have successfully adapted the image of arm64, which are mariadb and redis, respectively. I want to give back to the community. What is the best way for me to integrate? I will continue to adapt more services that support the arm64 architecture later.

**Comment by hamishliu** [comment]
![image](https://user-images.githubusercontent.com/79596614/170168023-e0bc5e27-2c9b-4b3f-9cd5-5ecc2d8a5bab.png)

**Comment by hamishliu** [comment]
I can deploy the arm64 application directly using bitnami's existing helm charts package without modifying any configuration, just specify the docker image tag of arm64

**Comment by hamishliu** [comment]
hello

**Comment by carrodher** [comment]
I'm glad you were able to have some images based on ARM64 working; but as previously mentioned, there is not any way at this moment to integrate this kind of image into the official Bitnami Application Catalog.
