### ISSUE TITLE
[bitnami/harbor] (13.1.0) upgrade fails

### ISSUE THREAD

**Issue by tfoks** [bitnami/charts#10289]
### Name and Version

bitnami/harbor 13.1.0

### What steps will reproduce the bug?

1. Environment: k8s running helm chart harbor:12.3.7
2. helm upgrade to verison 13.1.0 fails with PostgresQL bailing out.
Log:
```
postgresql 07:59:18.31
postgresql 07:59:18.31 Welcome to the Bitnami postgresql container
postgresql 07:59:18.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 07:59:18.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 07:59:18.32
postgresql 07:59:18.37 INFO  ==> ** Starting PostgreSQL setup **
postgresql 07:59:18.41 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 07:59:18.42 INFO  ==> Loading custom pre-init scripts...
postgresql 07:59:18.46 INFO  ==> Initializing PostgreSQL database...
postgresql 07:59:18.51 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 07:59:18.52 INFO  ==> Generating local authentication configuration
postgresql 07:59:18.55 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 07:59:18.71 INFO  ==> Configuring replication parameters
postgresql 07:59:18.76 INFO  ==> Configuring fsync
postgresql 07:59:18.78 INFO  ==> Configuring synchronous_replication
postgresql 07:59:18.84 INFO  ==> Loading custom scripts...
postgresql 07:59:18.85 INFO  ==> Enabling remote connections

postgresql 07:59:18.87 INFO  ==> ** PostgreSQL setup finished! **
postgresql 07:59:18.91 INFO  ==> ** Starting PostgreSQL **
2022-05-18 07:59:19.051 GMT [1] FATAL:  database files are incompatible with server
2022-05-18 07:59:19.051 GMT [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 13.7.
```

### What is the expected behavior?

Clean update of PostgreSQL version performed

### What do you see instead?

above error

**Comment by carrodher** [comment]
Please note the bundled PostgreSQL major version was updated from 11 to 13, [here](https://docs.bitnami.com/kubernetes/infrastructure/harbor/administration/upgrade/#to-13xx) you can find the upgrade instructions

**Comment by tfoks** [comment]
As chart version 12.3.7 is apparently using PostgresQL 11.15.0: can is be updated directly to 13.x or need it to be upgraded to version 12.x first? If the later is the case: which chart is using PostgresQL version 12.x?

**Comment by carrodher** [comment]
A version using PostgreSQL 12 was not released, those upgrade notes should work to upgrade the Harbor Helm chart from 13.x.x (bundling PostgreSQL 11) from 12.x.x (bundling PostgreSQL 13)

**Comment by tfoks** [comment]
The notes mentioned above seem to contain some errors:

`POSTGRESQL_PVC=$(kubectl get pvc --namespace "${HARBOR_NAMESPACE:?}" -l app.kubernetes.io/instance=harbor,app.kubernetes.io/name=postgresql,role=primary -o jsonpath="{.items[0].metadata.name}")`

should be

`POSTGRESQL_PVC=$(kubectl get pvc --namespace "${HARBOR_NAMESPACE:?}" -l app.kubernetes.io/instance=harbor,app.kubernetes.io/name=postgresql -o jsonpath="{.items[0].metadata.name}")`

`CURRENT_PG_VERSION=$(kubectl exec --namespace "${HARBOR_NAMESPACE:?}" harbor-postgresql-0 -c harbor-postgresql -- bash -c 'printenv APP_VERSION')`

should be

`CURRENT_PG_VERSION=$(kubectl exec --namespace "${HARBOR_NAMESPACE:?}" harbor-postgresql-0 -c postgresql -- bash -c 'printenv APP_VERSION')`

Besides that: Am I right that these notes do **not** upgrade PostgresQL to version 13 (resp. upgrade the DB) but make sure that the PostgresQL pod is not updated? I.e. stays on version 11.

**Comment by carrodher** [comment]
Thanks for letting us know; that documentation is publicly available at https://github.com/bitnami/charts-docs, would you like to create a PR fixing the issues you found.

> Besides that: Am I right that these notes do not upgrade PostgreSQL to version 13 (resp. upgrade the DB) but make sure that the PostgreSQL pod is not updated? I.e. stays on version 11.

Following the upgrade notes, the PostgreSQL Helm chart is updated to the latest version of the Helm chart itself but overrides the container image to use the one from the previous PostgreSQL version.
Since the schema of the database changed between both versions, in order to upgrade the database pod/container from 11 to 13, you will need to follow the recommended path provided by PostgreSQL for this kind of data migration.
