### ISSUE TITLE
Allow to specify annotation on Kafka service

### ISSUE THREAD

**Issue by mimol91** [bitnami/charts#1028]
**Which chart**:
Kafka 1.2.6
**Description**

I would be amazing if there will be possible to set custom annotation for kafka service.
My use case it that I want to setup internal LoadBalancer on AWS, and the way to do it require to add `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` annotation.

Currently I see that it is possible to change Kafka service type, but there is no way to set custom annotation

**Comment by javsalgar** [comment]
Hi,

See here https://github.com/bitnami/charts/pull/1029

**Comment by mimol91** [comment]
Wow, so quick! Thanks!
