### ISSUE TITLE
[bitnami/rabbitmq] extraSecretsPrependReleaseName not working as expected

### ISSUE THREAD

**Issue by hrvatskibogmars** [bitnami/charts#10290]
### Name and Version
Helm Chart version: 9.1.0
bitnami/rabbitmq:3.9.17-debian-10-r0

### What steps will reproduce the bug?

Deploying with this value it should name secret by using release name like in 8.x (8.15.2) chart version. But in 9.x Chart version it is using namespace instead of ReleaseName.

Chart - 8.15.2
---
secrets.yaml
```
apiVersion: v1
kind: Secret
metadata:
  {{- if $extraSecretsPrependReleaseName }}
  name: {{ $.Release.Name }}-{{ $key }}
  {{- else }}
  name: {{ $key }}
  {{- end }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
type: Opaque
stringData: {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 2 }}
{{- end }}
```

Chart - 9.1.0.
secrets.yaml

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ ternary (printf "%s-%s" (include "common.names.namespace" $) $key) $key $.Values.extraSecretsPrependReleaseName }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData: {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 2 }}
{{- end }}
```

Everything worked as expected in 8.x versions of the chart. Not sure if this is an intended change or is a mistake when refactoring chart values? 

### Are you using any custom parameters or values?

extraSecretsPrependReleaseName: true

### What is the expected behavior?

Secret for load_definitions is created as
{namespace}-load-definitions instead of 
{releasename}-load-definitions

### What do you see instead?

I see secret created with Namespace prefix instead of ReleaseName

**Comment by fmulero** [comment]
Thanks @hrvatskibogmars !

I think this is a mistake occurred when refactoring the chart. Prepend the namespace doesn't make sense when the variable is called `extraSecretsPrependReleaseName`.

Would you like to contribute by creating a PR to solve the issue? We will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by hrvatskibogmars** [comment]
@fmulero Sure, PR opened :)
