### ISSUE TITLE
Setting server.containerPort to a value other than 8080 breaks the deployment

### ISSUE THREAD

**Issue by herblet** [bitnami/charts#10301]
### Name and Version

bitnami/spring-cloud-dataflow 4.0.1

### What steps will reproduce the bug?

1. Using the bitnami/spring-cloud-dataflow Chart
2. Set "server.containerPort: 9393" (for Example).
3. Deploy the chart to a cluster.
4. The dataflow-server pod will never be ready, because the Spring application starts on 8080 since SERVER_POR is harcoded to this value. The readyness probe tries 9393.

### Are you using any custom parameters or values?

server.containerPort: 9393

### What is the expected behavior?

The spring dataflow server should start at the Port specified in server.containerPort.

### What do you see instead?

The spring dataflow server always starts at 8080.

**Comment by alemorcuq** [comment]
Thanks for reporting this, @herblet. Would you be interested in contributing with a PR?

**Comment by herblet** [comment]
Sure, will do.

**Comment by herblet** [comment]
See referenced PR for fix.
