### ISSUE TITLE
Private ELB?

### ISSUE THREAD

**Issue by andrewhadji-michael** [bitnami/charts#10317]
### Name and Version

bitnami/solr 0.3.3

### What is the problem this feature will solve?

Can some one give me some pointers how I can deploy the LoadBalancer as a private loadblancer?

I.e in the private subnets.

Thanks

### What is the feature you are proposing to solve the problem?

Private ELB

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Solr container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
