### ISSUE TITLE
[bitnami/wordpress] wordpressExtraConfigContent doesn't work!

### ISSUE THREAD

**Issue by mokhos** [bitnami/charts#10329]
### Name and Version

bitnami/wordpress 14.2.2

### What steps will reproduce the bug?

I took the helm chart and added some custom values to `wordpressExtraConfigContent` in order to set my desired values to the `wp-config` file. But It doesn't seem to pick up those.

### Are you using any custom parameters or values?
```yaml
wordpressExtraConfigContent: | 
         @ini_set( 'upload_max_size' , '128M' );
         @ini_set( 'post_max_size', '128M');
         @ini_set( 'memory_limit', '256M' );
         @ini_set( 'max_execution_time', '300' );
         @ini_set( 'max_input_time', '300' );
```

### What is the expected behavior?

At least the upload size must be increased from 80MB to 128MB. 

### What do you see instead?

On the WordPress health page and in the Info tab the maximum upload size is still 80MB.

**Comment by mokhos** [comment]
Hi @rafariossaa 

thanks for your response.
I tested these settings as you said in a new deployment. Please take a look at these photos:
<img width="759" alt="Bildschirmfoto 2022-05-25 um 10 04 18" src="https://user-images.githubusercontent.com/60837530/170213152-7da0feec-ac34-432e-867a-b2c50b25bc12.png">

<img width="867" alt="Bildschirmfoto 2022-05-25 um 10 04 39" src="https://user-images.githubusercontent.com/60837530/170213241-88e49db5-5c66-4b6a-ba71-85ef0941f1d6.png">

**Comment by rafariossaa** [comment]
Hi,
  The problem here is that you need to increase the limit at php level too.
  Could you try this ?
```diff
diff --git a/bitnami/wordpress/values.yaml b/bitnami/wordpress/values.yaml
index 0770d2d86..40a04cb3c 100644
--- a/bitnami/wordpress/values.yaml
+++ b/bitnami/wordpress/values.yaml
@@ -136,7 +136,13 @@ wordpressSkipInstall: false
 ##   @ini_set( 'post_max_size', '128M');
 ##   @ini_set( 'memory_limit', '256M' );
 ##
-wordpressExtraConfigContent: ""
+wordpressExtraConfigContent: |
+    @ini_set( 'upload_max_size' , '128M' );
+    @ini_set( 'post_max_size', '128M');
+    @ini_set( 'memory_limit', '256M' );
+    @ini_set( 'max_execution_time', '300' );
+    @ini_set( 'max_input_time', '300' );
+
 ## @param wordpressConfiguration The content for your custom wp-config.php file (advanced feature)
 ## NOTE: This will override configuring WordPress based on environment variables (including those set by the chart)
 ## NOTE: Currently only supported when `wordpressSkipInstall=true`
@@ -228,7 +234,11 @@ args: []
 ##   - name: FOO
 ##     value: "bar"
 ##
-extraEnvVars: []
+extraEnvVars:
+  - name: PHP_POST_MAX_SIZE
+    value: 128M
+  - name: PHP_UPLOAD_MAX_FILESIZE
+    value: 128M
 ## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
 ##
 extraEnvVarsCM: ""
```

**Comment by mokhos** [comment]
Hi @rafariossaa 

Sorry I had to open this issue again, because something else in `wordpressExtraConfigContent` doesn't work. 
So as you said I defined my required directives in `wordpressExtraConfigContent` and `extraEnvVars` and now the problem is that I need to add some directives to my `wp-config.php` file. So as a start, the chart says for a custom wp-config, I can use `wordpressConfiguration`, so I did below. But then the logs say: `wp-config is not writable!`
```

wordpressConfiguration:  
    define( 'WP_AUTO_UPDATE_CORE', true );
```

So I added that to my `wordpressExtraConfigContent` like below, it works until the logs say: 

```
Constant WP_AUTO_UPDATE_CORE already defined in /bitnami/wordpress/wp-config.php on line 179
```

Would you please help on this?
Thanks in advance.

**Comment by rafariossaa** [comment]
As the content is `worpdressExtraConfigContent` is copied at the end of the file, I think that for this you can add it to this setting.

```diff
diff --git a/bitnami/wordpress/values.yaml b/bitnami/wordpress/values.yaml
index 5ce84aaad..9dfa66594 100644
--- a/bitnami/wordpress/values.yaml
+++ b/bitnami/wordpress/values.yaml
@@ -136,7 +136,15 @@ wordpressSkipInstall: false
 ##   @ini_set( 'post_max_size', '128M');
 ##   @ini_set( 'memory_limit', '256M' );
 ##
-wordpressExtraConfigContent: ""
+wordpressExtraConfigContent: |
+  @ini_set( 'upload_max_size' , '128M' );
+  @ini_set( 'post_max_size', '128M');
+  @ini_set( 'memory_limit', '256M' );
+  @ini_set( 'max_execution_time', '300' );
+  @ini_set( 'max_input_time', '300' );
+  define( 'WP_AUTO_UPDATE_CORE', true );
+
+
 ## @param wordpressConfiguration The content for your custom wp-config.php file (advanced feature)
 ## NOTE: This will override configuring WordPress based on environment variables (including those set by the chart)
 ## NOTE: Currently only supported when `wordpressSkipInstall=true`
@@ -228,7 +236,12 @@ args: []
 ##   - name: FOO
 ##     value: "bar"
 ##
-extraEnvVars: []
+extraEnvVars:
+  - name: PHP_POST_MAX_SIZE
+    value: 128M
+  - name: PHP_UPLOAD_MAX_FILESIZE
+    value: 128M
+
 ## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
 ##
 extraEnvVarsCM: ""
```

Have you tried this ?

**Comment by mokhos** [comment]
Yes, I already added the required directives in `wordpressExtraConfigContent` as you said. But still the error persists.
You don't get such error? 
```
Constant WP_AUTO_UPDATE_CORE already defined in /bitnami/wordpress/wp-config.php on line 179
```

**Comment by rafariossaa** [comment]
Yes, I am getting a warning because `WP_AUTO_UPDATE_CORE` is twice in the file.
It is getting the indicated value as it is the last one.
Let me check if there is a way of not having the warning.

**Comment by rafariossaa** [comment]
I am opening a internal task in order to address this.
We will come back as soon as we have news.

**Comment by CeliaGMqrz** [comment]
Hi @mokhos, sorry for the delay. 

We have studied this case and the most successful way to avoid this duplication is to use `WORDPRESS_AUTO_UPDATE_LEVEL` as `major` in the section `extraEnvVars` if you want to set `WP_AUTO_UPDATE_CORE` as `true`.

```
extraEnvVars:
  - name: PHP_POST_MAX_SIZE
    value: 128M
  - name: PHP_UPLOAD_MAX_FILESIZE
    value: 128M
  - name: WORDPRESS_AUTO_UPDATE_LEVEL
    value: "major" 
```
You also have the possibility to use your own `wp-config.php` file with the parameter `wordpressConfiguration`

```
## @param wordpressConfiguration The content for your custom wp-config.php file (advanced feature)
## NOTE: This will override configuring WordPress based on environment variables (including those set by the chart)
## NOTE: Currently only supported when `wordpressSkipInstall=true`
##
wordpressConfiguration: ""
```
 or `existingWordPressConfigurationSecret` 

```
## @param existingWordPressConfigurationSecret The name of an existing secret with your custom wp-config.php file (advanced feature)
## NOTE: When it's set the `wordpressConfiguration` parameter is ignored
##
existingWordPressConfigurationSecret: ""
```

**Comment by WyskyNet** [comment]
PHP limits can also be set by custom postInitScript:
```yaml
customPostInitScripts:
  custom-php..sh: |
    #!/bin/bash
    echo -e "upload_max_filesize=1G\npost_max_size=1G\nmemory_limit=1G\nmax_execution_time=600" > /opt/bitnami/php/etc/conf.d/custom.ini
```

**Comment by xyfleet** [comment]
I just want to update the wp-home and wp-siteurl, but did not work. How can I fix it?


```
wordpressExtraConfigContent:
  define('WP_HOME',      'http://www.example.com/blog');
  define('WP_SITEURL',   'http://www.example.com/blog');
```

**Comment by dgomezleon** [comment]
Hi @xyfleet 

You need to use: 

```
wordpressExtraConfigContent: |
  define('WP_HOME',      'http://www.example.com/blog');
  define('WP_SITEURL',   'http://www.example.com/blog');
```

**Comment by xyfleet** [comment]
@dgomezleon Thanks for your update. I tried on my site and these 2 variables, WP_HOME, WP_SITEURL got updated. 
How about the default settings (WP_HOME and WP_SITEURL) here? Do we need to delete and how?
<img width="913" alt="image" src="https://github.com/bitnami/charts/assets/113627389/cf814afe-5e92-43ee-bd07-aeb295a81e5f">




When I visited www.example.com/blog/, lots of contents are 404 not found. I have an ingress configured here:
```
ingress:
    enabled: true
    ingressClassName: alb
    hostname: www.example.com
    path: /blog/*
```

<img width="1283" alt="image" src="https://github.com/bitnami/charts/assets/113627389/47e919ec-c30e-4a2e-93f1-186497f49cc3">

**Comment by dgomezleon** [comment]
Hi @xyfleet 

In order to properly track issues and avoid duplicity, could you please add all your questions to that ticket? Also, let me share with you [this previous case](https://github.com/bitnami/charts/issues/13018).
