### ISSUE TITLE
bitnami/keycloak 9.0.* keycloak-config-cli fails to run, can't find configuration

### ISSUE THREAD

**Issue by aaroniscode** [bitnami/charts#10320]
### Name and Version

bitnami/keycloak 9.0.1

### What steps will reproduce the bug?

In major version 5.0.0 of keycloak-config-cli, all of the import properties were reordered. Documentation can be found in the [CHANGELOG](https://github.com/adorsys/keycloak-config-cli/blob/main/CHANGELOG.md#500---2022-03-25). 

The ENV variable `IMPORT_PATH` needs to be changed to `IMPORT_FILES_LOCATIONS`.

And the value `/config/` need to be changed to `/config/*`.

The Helm chart has hard coded the values [here](https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/keycloak-config-cli-job.yaml#L77-L78).

### What is the expected behavior?

Expected behavior is for the the keycloak-config-cli applicaiton to run.

### What do you see instead?

Instead it crashes with the error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'import' to de.adorsys.keycloak.config.properties.ImportConfigProperties failed:

    Property: import.files.locations
    Value: null
    Reason: must not be null


Action:

Update your application's configuration
```

**Comment by aaroniscode** [comment]
Working on a PR...

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will review it and provide feedback
