### ISSUE TITLE
[bitnami/consul] Server not usable outside of k8s

### ISSUE THREAD

**Issue by r65535** [bitnami/charts#10325]
### Name and Version

bitnami/consul v1.12.0

### What steps will reproduce the bug?

1. Deploy consul with the helm chart
2. Expose all the ports as NodePorts
3. Try to connect an external consul agent to the nodeports

### What do you see instead?

The agent begins connection but is told to reconnect to the internal k8s pod IP - which causes a no route to host

### Additional information

The hashicorp helm chart supports this by exposing hostIP and hostPorts - [docs](https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes#auto-join-via-host-ports)

**Comment by fmulero** [comment]
Hi @r65535 Could you share your configuration?

With current version of the chart we can pass additional ENV vars to the container to enable some features using the `extraEnvVars` value. Have you taken it a look?

**Comment by fmulero** [comment]
Sorry @r65535 I was revisiting this issue and it seems there is no an easy solution.

This is an interesting feature already implemented in other charts like [mongodb] (https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L74). I'll open an internal discussion. In the meantime, if you would like to contribute any PR will be welcomed

**Comment by fmulero** [comment]
Hi @r65535.

Unfortunately we don't have planned to implement this feature (at the moment). If you would like to contribute to this Helm chart by adding this feature (or any other), feel free to create a PR. We will be happy to review it and provide feedback.
