### ISSUE TITLE
[parse] app not working with ingress disabled

### ISSUE THREAD

**Issue by Morriz** [bitnami/charts#10348]
### Name and Version

bitnami/parse

### What steps will reproduce the bug?

Deploy the chart with ingress disabled.

### What do you see instead?

deployments not working correctly, and dashboard not configured to talk to parse server.

### Additional information

The whole setup without ingress seems to assume deployment with docker-compose, as the PARSE_HOST for the dashboard deployment is then set to 127.0.0.1.

This chart seems to not have tests for the scenarios it offers, but that disabling ingress is not working is a gross oversight imo.

**Comment by Morriz** [comment]
this snippet shows that setting the svc to ClusterIP will break comms with server:
```
{{- define "parse.serviceIP" -}}
{{- if eq .Values.dashboard.service.type "ClusterIP" -}}
127.0.0.1
{{- else -}}
{{- default "" .Values.dashboard.service.loadBalancerIP -}}
{{- end -}}
{{- end -}}
```

**Comment by javsalgar** [comment]
Hi,

We test our solutions with LoadBalancerIP, which requires a two-step deployment: first to get the LoadBalancerIP and then to set it. Could you explain the steps you followed to deploy?

**Comment by Morriz** [comment]
The more I worked with your chart, the more I see it is convoluted and not at all allowing for different scenarios:
- external db
- disable ingress
- tls configuration is not possible

Strange, because I see a lot of awesome bitnami charts that are crafted with care. Not this one.

**Comment by javsalgar** [comment]
Hi!

We'd be very grateful if you could share with us all that you needed to improve so we can fix as many issues as possible in the chart.

**Comment by Morriz** [comment]
To do it right for the world to see involves rework still, but I could hand it over as I made it now (it works, but might have broken other scenarios).
Where would I send it?

**Comment by javsalgar** [comment]
If you have the improvements already in a fork, you could send a PR and we could integrate them in our current chart.
