### ISSUE TITLE
Redis pod crashes due readonly fs

### ISSUE THREAD

**Issue by scbay** [bitnami/charts#10359]
### Name and Version

bitnami/redis:10.6.5

### What steps will reproduce the bug?

1. Install redis helm chart from bitnami helm repo
2. Pod crashes after some time with readonly filesystem

### Are you using any custom parameters or values?

No

### What is the expected behavior?

I expect to have not any pod crashes due this issue

### What do you see instead?

In the pod logs I can see the following:
```
1:C 23 May 2022 09:24:07.727 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 23 May 2022 09:24:07.727 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 23 May 2022 09:24:07.727 # Configuration loaded
1:M 23 May 2022 09:24:07.730 # Can't open the append-only file: Read-only file system
```

### Additional information

After redeployment / recreating the pods the issue seems to disappear.

**Comment by carrodher** [comment]
Maybe it was some kind of transient error, I was not able to reproduce it when deploying the Helm chart from scratch. In the same way, in your case, it seems it was fixed with a redeploy. Are you still facing this issue?

**Comment by scbay** [comment]
The issue still occurs, even with the latest helm release, I get `Can't open the append-only file: Input/output error`. I experienced that this does not happen with every pod restart.

**Comment by FraPazGal** [comment]
Hello @scbay,

I checked this and couldn't reproduce the issue after several chart installations. Keep in mind we are using the latest chart version `bitnami/redis@16.9.11` that uses `redis@6.2.7`. If you are still experiencing those issues using a fresh instance of our latest chart version please share with us your kubectl and helm versions as well as the cluster provider where you are installing the chart.

**Comment by scbay** [comment]
@FraPazGal , we are using kubectl in version 1.24 and helm version v3.7.0 to manage a kubernetes cluster based on RKE1. (k8s version is v1.20.12)

**Comment by FraPazGal** [comment]
Hello @scbay,

After taking a look we couldn't reproduce the issue in our testing on different platforms like GKE, AKS, IKS, or TKG. It seems it is not an issue related to the `bintami/redis` chart but a very specific use case related to the platform. 

For information regarding the cluster provider, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the platform or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
