### ISSUE TITLE
 mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied

### ISSUE THREAD

**Issue by Shilagrawal** [bitnami/charts#10354]
### Name and Version

Latest mongo db release 4.4.13, 5.x is the latest available to pull when we don't give any image tag

### What steps will reproduce the bug?

Env: Rhel 8.5  with Kubernetes 1.22.8 (also tried 1.23 ) and CSI drivers (tried multiple CSI drivers and tried on GKE as well with standard CSI drivers) 
Deployment type: Mongodb Sharded deployment.
Command used to install:
```
helm install my-release bitnami/mongodb-sharded --namespace=mongodb --set global.storageClass=vxflexos-xfs --set mongodbRootPassword=mongodb123,mongodbUsername=mongodb,mongodbPassword=mongodb123,mongodbDatabase=ycsb  --set volumePermissions.enabled=true --set replicaSet.enabled=true --set shards=8 --set configsvr.replicas=1 --set configsvr.persistence.size=100Gi --set mongos.replicas=1 --set shardsvr.dataNode.replicas=1 --set shardsvr.persistence.size=1.5Ti --set shardsvr.dataNode.resources.requests.memory=64Gi --set shardsvr.dataNode.resources.requests.cpu=16 --set configsvr.resources.requests.memory=16Gi --set mongos.resources.requests.memory=16Gi
```
After this, I see all pods are crashing in loop and when I check the logs it gets the following message 
System has enough resources:
```
[root@Mongo-K8Master ec2-user]# kubectl logs -n mongodb my-release-mongodb-sharded-shard1-data-0
13:22:29.35 INFO ==> Setting node as primary
mongodb 13:22:29.38
mongodb 13:22:29.38 Welcome to the Bitnami mongodb-sharded container
mongodb 13:22:29.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 13:22:29.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 13:22:29.38
mongodb 13:22:29.38 INFO ==> ** Starting MongoDB Sharded setup **
mongodb 13:22:29.42 INFO ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb': Permission denied
```
if i run the pods without  `--set volumePermissions.enabled=true` or run with option  `diagnosticMode.enabled=true`, the pods dont crashloop run fine but after I exec and try to login to mongodb it says Authentication denied again permission issue
```
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$ mongo admin --username root -p mongodb123 --host 10.244.1.35 --port 27017
MongoDB shell version v4.4.13
connecting to: mongodb://10.244.1.35:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 10.244.1.35:27017, connection attempt failed: SocketException: Error connecting to 10.244.1.35:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$
```
how do I resolve the permission issue? It seems there is some issue with the charts or some of the latest changes I tried editing the values in the init container of the stateful set chown it to 770 instead of 700 however still I see I cant have then run clean or able to login to db  

### Are you using any custom parameters or values?
```
helm install my-release bitnami/mongodb-sharded --namespace=mongodb --set global.storageClass=vxflexos-xfs --set mongodbRootPassword=mongodb123,mongodbUsername=mongodb,mongodbPassword=mongodb123,mongodbDatabase=ycsb  --set volumePermissions.enabled=true --set replicaSet.enabled=true --set shards=8 --set configsvr.replicas=1 --set configsvr.persistence.size=100Gi --set mongos.replicas=1 --set shardsvr.dataNode.replicas=1 --set shardsvr.persistence.size=1.5Ti --set shardsvr.dataNode.resources.requests.memory=64Gi --set shardsvr.dataNode.resources.requests.cpu=16 --set configsvr.resources.requests.memory=16Gi --set mongos.resources.requests.memory=16Gi
```
### What is the expected behavior?

all pods should run fine, user should be able to exec and login to database so that one can load values and check the database 

### What do you see instead?

pods are crashing in loop and kubectl logs gives permission denied messages in /bitnami/mongodb
 
if I dont use `--set volumePermissions.enabled=true` option the pods run fine but after exec and trying to login to the database it gives an error
```
mongo admin --username root -p mongodb123 --host 10.244.4.11 --port 27017
MongoDB shell version v5.0.8
connecting to: mongodb://10.244.4.11:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 10.244.4.11:27017, connection attempt failed: SocketException: Error connecting to 10.244.4.11:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1
```
### Additional information

When I run pods in diagnostic mode with `--set diagnosticmode true` 
```
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$ ls -la
total 0
drwxr-xr-x   1 root root  35 May 17 08:33 .
drwxr-xr-x   1 root root  35 May 17 08:33 ..
-rw-rw-r--   1 root root   0 Apr 29 18:08 .dbshell
-rwxr-xr-x   1 root root   0 May 17 08:33 .dockerenv
drwxrwxr-x   2 root root   6 Apr 29 18:08 .mongodb
-rw-rw-r--   1 root root   0 Apr 29 18:08 .mongorc.js
-rw-rw-r--   1 root root   0 Apr 29 18:08 .mongoshrc.js
drwxr-xr-x   1 root root  71 Apr 29 18:08 bin
drwxr-xr-x   3 root root  21 Apr 29 18:08 bitnami
drwxr-xr-x   2 root root   6 Mar 19 13:44 boot
drwxr-xr-x   5 root root 360 May 17 08:33 dev
drwxrwxr-x   2 root root   6 Apr 29 18:08 docker-entrypoint-initdb.d
drwxrwsrwx   3 root 1001  91 May 17 08:33 entrypoint
lrwxrwxrwx   1 root root  50 Apr 29 18:08 entrypoint.sh -> /opt/bitnami/scripts/mongodb-sharded/entrypoint.sh
drwxr-xr-x   1 root root  66 May 17 08:33 etc
drwxr-xr-x   2 root root   6 Mar 19 13:44 home
drwxr-xr-x   1 root root  30 Sep 25  2017 lib
drwxr-xr-x   2 root root  34 Apr 15 18:16 lib64
lrwxrwxrwx   1 root root  30 Apr 29 18:08 liblog.sh -> /opt/bitnami/scripts/liblog.sh
drwxr-xr-x   2 root root   6 Apr 15 18:16 media
drwxr-xr-x   2 root root   6 Apr 15 18:16 mnt
drwxrwxr-x   1 root root  21 Apr 29 18:07 opt
dr-xr-xr-x 786 root root   0 May 17 08:33 proc
drwx------   2 root root  37 Apr 15 18:16 root
drwxr-xr-x   1 root root  21 May 17 08:33 run
lrwxrwxrwx   1 root root  43 Apr 29 18:08 run.sh -> /opt/bitnami/scripts/mongodb-sharded/run.sh
drwxr-xr-x   1 root root  20 Apr 29 18:08 sbin
drwxr-xr-x   2 root root   6 Apr 15 18:16 srv
dr-xr-xr-x  13 root root   0 May 17 08:33 sys
drwxrwxrwt   1 root root   6 Apr 29 18:08 tmp
drwxrwxr-x   1 root root  66 Apr 29 18:07 usr
drwxr-xr-x   1 root root  30 Apr 15 18:16 var
I have no name!@my-release-mongodb-sharded-shard0-data-0:/$

@my-release-mongodb-sharded-shard1-data-0:/$ ls /bitnami/mongodb/ -la

ls: cannot open directory '/bitnami/mongodb/': Permission denied
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ ls -l
total 0
drwxr-xr-x.    1 root root  71 Apr 29 18:08 bin
drwxr-xr-x.    3 root root  21 Apr 29 18:08 bitnami
drwxr-xr-x.    2 root root   6 Mar 19 13:44 boot
drwxr-xr-x.    5 root root 360 May 18 14:17 dev
drwxrwxr-x.    2 root root   6 Apr 29 18:08 docker-entrypoint-initdb.d
drwxrwsrwx.    3 root 1001  91 May 18 14:17 entrypoint
lrwxrwxrwx.    1 root root  50 Apr 29 18:08 entrypoint.sh -> /opt/bitnami/scripts/mongodb-sharded/entrypoint.sh
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ ls /bitnami/ -la
total 0
drwxr-xr-x. 3 root root 21 Apr 29 18:08 .
drwxr-xr-x. 1 root root 35 May 18 14:17 ..
drwx--S---. 2 root 1001  6 May 18 14:17 mongodb
```

**Comment by carrodher** [comment]
The non-root user (1001 by default, but any other random UID is allowed) belongs to the root group. This is the approach used to have permissions in the different directories without being a root user.

Because of that, it is needed that any directory inside the mounted PV/PVC belongs to the root user. This can be done manually or using the volumePermission initcontainer.

According to the latest logs, it seems that is not the case for example at
```
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ ls /bitnami/ -la
total 0
drwxr-xr-x. 3 root root 21 Apr 29 18:08 .
drwxr-xr-x. 1 root root 35 May 18 14:17 ..
drwx--S---. 2 root 1001  6 May 18 14:17 mongodb
```

It can work if the non-root user is 1001, but if the UID is changed to something else, it won't work

**Comment by Shilagrawal** [comment]
@carrodher I have no name!@my-release-mongodb-sharded-shard1-data-0:/$ id
uid=1001 gid=0(root) groups=0(root),1001
I have no name!@my-release-mongodb-sharded-shard1-data-0:/$
the is is not changed i blv

**Comment by Shilagrawal** [comment]
. This can be done manually or using the volumePermission initcontainer  --> Can you suggest what changes one can do to make it work ?

**Comment by abhishekgupta2205** [comment]
set runasuser=0 in values.yaml . it may solve the issue.

**Comment by Shilagrawal** [comment]
@abhishekgupta2205  these charts doesnt get downloaded like a git clone etc after adding a repo and installing how do you change the any parameter in values.yaml?

**Comment by abhishekgupta2205** [comment]
you can download it on your machine using helm pull command . it will download a tar file which you can untar and there you can change values.yaml

**Comment by Shilagrawal** [comment]
[root@k8master chart-bitnami]# helm pull https://charts.bitnami.com/bitnami/mongodb-sharded --insecure-skip-tls-verify
Error: failed to fetch https://charts.bitnami.com/bitnami/mongodb-sharded : 403 Forbidden
 if you can share the exact command to pul teh chart will be helpful if at all it needs teh ca-file then i am not sure where to get it from or how to accomplish helm pull for bitnami

**Comment by abhishekgupta2205** [comment]
helm pull bitnami/mongodb-sharded

**Comment by Shilagrawal** [comment]
@abhishekgupta2205  Thanks for teh quick response it worked and i changed he file parameters too , however now during install to make sure it refers the one we have locally pulled how do we do that ? 

my command line requirement is 
helm install my-release bitnami/mongodb-sharded --namespace=test6 --set global.storageClass=vxflexos-xfs --set auth.rootPassword=mongodb123,auth.mongodbUsername=mongodb,auth.mongodbPassword=mongodb123,auth.mongodbDatabase=ycsb  --set volumePermissions.enabled=true  --set replicaSet.enabled=true --set shards=2 --set configsvr.replicas=1  --set configsvr.persistence.size=60Gi --set mongos.replicas=1 --set shardsvr.dataNode.replicas=1 --set shardsvr.persistence.size=100Gi --set shardsvr.dataNode.resources.requests.memory=16Gi --set shardsvr.dataNode.resources.requests.cpu=8 --set configsvr.resources.requests.memory=8Gi --set mongos.resources.requests.memory=8Gi

**Comment by abhishekgupta2205** [comment]
helm install my-release mongodb-sharded --namespace=test6 --set global.storageClass=vxflexos-xfs --set auth.rootPassword=mongodb123,auth.mongodbUsername=mongodb,auth.mongodbPassword=mongodb123,auth.mongodbDatabase=ycsb  --set volumePermissions.enabled=true  --set replicaSet.enabled=true --set shards=2 --set configsvr.replicas=1  --set configsvr.persistence.size=60Gi --set mongos.replicas=1 --set shardsvr.dataNode.replicas=1 --set shardsvr.persistence.size=100Gi --set shardsvr.dataNode.resources.requests.memory=16Gi --set shardsvr.dataNode.resources.requests.cpu=8 --set configsvr.resources.requests.memory=8Gi --set mongos.resources.requests.memory=8Gi

**Comment by Shilagrawal** [comment]
@abhishekgupta2205  I dont see any diff between the command i shared and you shared, 
Query :
During helm install command if i want to create a user say mongodb and a password for user how do i do that ?
what --set option can i use?
earlier i used helm install my-release bitnami/mongodb-sharded --namespace=mongodb --set global.storageClass=vxflexos-xfs --set mongodbRootPassword=mongodb123,mongodbUsername=mongodb,mongodbPassword=mongodb123,mongodbDatabase=ycsb
which worked 2 months back, now it looks like some params have changed so i use
--set auth.RootPassword=mongodbtest,mongodbUsername=mongodb,mongodbPassword=mongodbtest,mongodbDatabase=ycsb
so to sets the root password what i want to however doesn't create any user called mongodb to login to the pod
Hence after we exec to pod only root user login works and no other user is created it seems
 
PS auth.rootPassword - works all other following auth arguments **",auth.mongodbUsername=mongodb,auth.mongodbPassword=mongodb123"**  doesn't work ..   (with our without auth. added to it

**Comment by Shilagrawal** [comment]
Example this is one of the old chart : 
[root@k8master 1.1.3]# cd mongodb-sharded/
[root@k8master mongodb-sharded]# cat README.md | grep password
| `mongodbRootPassword`                         | MongoDB admin password                                                                                                                                    | `random alphanumeric string (10)`                        |
  **--set mongodbRootPassword=secretpassword,mongodbUsername=my-user,mongodbPassword=my-password,mongodbDatabase=my-database \**
The above command sets the MongoDB `root` account password to `secretpassword`. Additionally, it creates a standard database user named `my-user`,

This uses similar command to what i use however i am looking for equivalent command to be able to set a dbuser and credentials that later allows me to login

**Comment by abhishekgupta2205** [comment]
instead of helm install my-release bitnami/mongo , you can use helm install my-release mongo
For creating user , you can run mongo and then create user by db.createuser() command.

**Comment by Shilagrawal** [comment]
> instead of helm install my-release bitnami/mongo , you can use helm install my-release mongo For creating user , you can run mongo and then create user by db.createuser() command.

I would prefer user getting created in helm common itself else i will have t login to each shard and create user etc in s large setup that's quite a task

**Comment by tranxuanthin** [comment]
Do you have volume permissions enabled? you can try that way.
