### ISSUE TITLE
Unable to deploy Postgres HA cluster with External DNS disabled

### ISSUE THREAD

**Issue by krp2** [bitnami/charts#10351]
### Name and Version

bitnami/postgresql-ha:9.0.12  | App version - 14.3.0

### What steps will reproduce the bug?

Environment - Rancher RKE2 kubernetes cluster v1.23.1+rke2r1
Deploy a 3 node cluster with External DNS disabled.
Helm Chart used - https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha

### What is the expected behavior?

3 Postgres Pods should be deployed and should be in running state

### What do you see instead?

Postgres first pod comes up but second and third pod (Standby pods) goes to CrashloopBackoff state
[postgres-1.log](https://github.com/bitnami/charts/files/8749550/postgres-1.log)
[postgres-2.log](https://github.com/bitnami/charts/files/8749551/postgres-2.log)
[postgres-0.log](https://github.com/bitnami/charts/files/8749552/postgres-0.log)

**Comment by javsalgar** [comment]
Hi,

Could you add more details about External DNS being disabled? Does the cluster have an internal DNS that can resolve service names? This is necessary for the chart to work.
