### ISSUE TITLE
[RabbitMQ] 

### ISSUE THREAD

**Issue by alankan-finocomp** [bitnami/charts#10356]
### Name and Version

bitnami/rabbitmq:9.1.2

### What is the problem this feature will solve?

https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L221
There is an option `clustering.rebalance` to enable running `rabbitmq-queues rebalance` but not `rabbitmq-queues grow`. 

When a definition file is used to create queues, the first instance of RabbitMQ must be the leader of every single quorum queue.
![image](https://user-images.githubusercontent.com/79436574/169740551-c13d708f-2bb7-4af7-8faa-c4a62a15efe1.png)

Running `rabbitmq-queues rebalance` in subsequent instances won't do anything as they didn't join the quorum yet.
![image](https://user-images.githubusercontent.com/79436574/169740977-a7f03991-e9a6-4283-b4f7-555f9b8df1c1.png)

### What is the feature you are proposing to solve the problem?

Provide another Helm value option to enable nodes to run `rabbitmq-queues grow` on startup.
https://www.rabbitmq.com/rabbitmq-queues.8.html#grow

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your comments. I am opening an internal task in order to study and eventually implement this.
  However, I can not provide an ETA. Meanwhile maybe you consider to send a PR implementing this, we will be glad to review and merge it.
  We will come back as soon as we have news.

**Comment by Jojoooo1** [comment]
Seems a pretty critic issue for using the chart. Please let use know!

**Comment by carrodher** [comment]
Unfortunately due to other priorities and given, we are a small team we didn't find the bandwidth to work on this feature and it is very unlikely we find it to work on it in the short term.

I will close this Issue but we can reopen it if there is any contribution from the community adding the desired feature.
