### ISSUE TITLE
[bitnami/thanos] Enable which ports are exposed for Receiver Service 

### ISSUE THREAD

**Issue by vCra** [bitnami/charts#10363]
### Name and Version

bitnami/thanos 10.4.2

### What is the problem this feature will solve?

Currently, the service that is created for the thanos Receiver exposes the GRPC/HTTP endpoint of the receiver instances, instead of just the remote-write endpoint

In an environment where we we would just like to push metrics to Receive, changing the service to use an LB also exposes the ports which should just be available internally

### What is the feature you are proposing to solve the problem?

Allow for the exposed ports to be configurable

### What alternatives have you considered?

We could also create a separate service just for external querying, as we will still need the GRPC endpoint for query to continue to be able to scrape Receive.

We can also manually create a service outside of the Helm Chart - I feel like having Receive exposed externally is a common use case (probably the main use case IMO)

**Comment by vCra** [comment]
Note to add that if we're using `receive-distributor` then we shouldn't need the GRPC service - the Headless service for receive should be enough

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR with the feature?
