### ISSUE TITLE
Unable to deploy Postgres HA cluster with External DNS disabled

### ISSUE THREAD

**Issue by krp2** [bitnami/charts#10360]
### Name and Version

14/debian-10

### What steps will reproduce the bug?

Environment - Rancher RKE2 kubernetes cluster v1.23.1+rke2r1
Deploy a 3 node cluster with External DNS disabled.
Helm Chart used - https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha

### What is the expected behavior?

3 Postgres Pods should be deployed and should be in running state

### What do you see instead?

Postgres first pod comes up but second and third pod (Standby pods) goes to CrashloopBackoff state

[postgres-0.log](https://github.com/bitnami/bitnami-docker-postgresql/files/8749542/postgres-0.log)
[postgres-1.log](https://github.com/bitnami/bitnami-docker-postgresql/files/8749543/postgres-1.log)
[postgres-2.log](https://github.com/bitnami/bitnami-docker-postgresql/files/8749544/postgres-2.log)

**Comment by carrodher** [comment]
Could you share with us the parameter you're using to deploy the bitnami/postgresql-ha Helm chart?
