### ISSUE TITLE
[bitnami/kafka] Statefulset broker id keeps incrementing on restart

### ISSUE THREAD

**Issue by abknanda** [bitnami/charts#10361]
### Name and Version

bitnami/kafka:16.3.2

### What steps will reproduce the bug?

This is with reference to a similar issue https://github.com/bitnami/charts/pull/2028
where the broker id keeps incrementing after restart of pod in statefulset.
A fresh installation assigns broker id 1001,1002,1003 for a 3 broker kafka configuration.
On restarting any pod the new instance gets broker id of 1004 instead of the statefulset pod number
This makes topics created earlier inaccessible once all pods gets restarted and kafka leader election for a partition always fails as broker with that broker id doesn't exist anymore.

### Are you using any custom parameters or values?

NA

### What is the expected behavior?

Broker id should stay consistent for every statefulset restart and only increment if new brokers are added

### What do you see instead?

Broker id keeps increasing for every restart

### Additional information

Similar issue reported earlier:
https://github.com/ghShu/kafka-notes/blob/master/notes/20200310-achieve-consistent-broker-ids-in-kafka-cluster.md
https://github.com/bitnami/charts/pull/2028

**Comment by javsalgar** [comment]
Hi!

Thank you for using Bitnami! Could you provide exact steps to reproduce the issue?

**Comment by abknanda** [comment]
On a closer look it seems that kafka is not using /bitnami/kafka/data as its log directory
Instead it is defaulting to /tmp/kafka-logs which is lost everytime the pod restarts
Adding
`log.dirs=/bitnami/kafka/data` to the `config` section in helm values persists the same in PVC and the broker id remains constant on restarts as well
Maybe the `logsDirs` value is not being applied to the server.properties

**Comment by abknanda** [comment]
Found that config section totally overrides all configurations provided through helm.
It should either have all required properties for server.properties or all should be configured through helm.
Closing the bug

**Comment by abknanda** [comment]
I was providing the helm values through **config:** as well which was overwriting all the configs and setting the **log.dirs** to empty
To fix it, I added the extra config 
`log.dirs=/bitnami/kafka/data`
This is the default path in the PV
