### ISSUE TITLE
Issue with using COS(Cloud Object Storage) as Persistent Volume(PV)

### ISSUE THREAD

**Issue by Bhargav6611** [bitnami/charts#10370]
### Name and Version

Bitnami Elasticsearch Stack chart version 7.17.2204031352

### What steps will reproduce the bug?

Bitnami Elasticsearch Stack is being used for IBM Kubernetes v1.21 to use Cloud Object Storage (COS) as PV.
The PV does not get created while using the Object Storage.
All the pods i.e. Master and Data goes to 0/1 State.

Please suggest what steps are required for using COS as Persistent Volume.

### Are you using any custom parameters or values?
```
global.storageClass=ibmc-s3fs-standard-perf-cross-region
```

### What do you see instead?

All the pods i.e. Master and Data are in 0/1 State.
The PVC is also in the pending State and the below error can be seen:

```data-elasticsearch2-841af245-data-0     Pending                                                                        ibmc-s3fs-standard-perf-cross-region   7m17s
data-elasticsearch2-841af245-data-1     Pending                                                                        ibmc-s3fs-standard-perf-cross-region   7m17s
data-elasticsearch2-841af245-master-0   Pending                                                                        ibmc-s3fs-standard-perf-cross-region   7m17s
data-elasticsearch2-841af245-master-1   Pending                                                                        ibmc-s3fs-standard-perf-cross-region   7m17s
data-elasticsearch2-841af245-master-2   Pending                                                                        ibmc-s3fs-standard-perf-cross-region   7m17s`
```

```
Events:
  Type     Reason                Age                  From                                                                                                   Message
  ----     ------                ----                 ----                                                                                                   -------
  Warning  ProvisioningFailed    30m (x13 over 35m)   ibm.io/ibmc-s3fs_ibmcloud-object-storage-plugin-59f67dddc7-nnnh7_f6c07faa-ea7d-4860-8c29-1ac8dfb1c688  failed to provision volume with StorageClass "ibmc-s3fs-standard-perf-cross-region": data-elasticsearch2-841af245-master-1:bmb4umqw0rg5bot0unn0:cannot validate annotations: data-elasticsearch2-841af245-master-1:bmb4umqw0rg5bot0unn0:secret-name not specified
  Normal   ExternalProvisioning  38s (x142 over 35m)  persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "ibm.io/ibmc-s3fs" or manually created by system administrator
  Normal   Provisioning          26s (x73 over 35m)   ibm.io/ibmc-s3fs_ibmcloud-object-storage-plugin-59f67dddc7-nnnh7_f6c07faa-ea7d-4860-8c29-1ac8dfb1c688  External provisioner is provisioning volume for claim "sumit-dev/data-elasticsearch2-841af245-master-1"
```

**Comment by rafariossaa** [comment]
Hi,
  In this case I would ask first IBM support about how to use COS, maybe it has some requirements for the PV / PVC.

**Comment by Bhargav6611** [comment]
Hi @rafariossaa , Thank you for your reply, I would like to know in general can we use the Object Storage as the PV for the Bitnami Elasticsearch.

Thanks.

**Comment by rafariossaa** [comment]
We don't test it using all the storage possibilities in all the major cloud providers.
Each storage has its own particularities. I guess yes, but I can not guarantee it.

**Comment by Bhargav6611** [comment]
Hi @rafariossaa, As guided I did contact the IBM support and I got the below response:

This is provisioned by a third-party provider so I unfortunately we do not provide support for this product. I can tell you that Object Storage itself can be used on a classic cluster, at least if provisioned through IBM Cloud directly, which is the storage type you are attempting to use. 
I have found a support portal for Bitnami issues specifically dealing with IBM:
https://bitnami.com/support/ibm
You should be able to get any assistance you need for this issue through that portal. Just to recap, you have issues with provisioning object storage through Bitnami, but since this is a third party add-on, we do not support it. This case will be marked as resolved.

**Comment by Bhargav6611** [comment]
Considering the above context is it possible to test this particular storage use-case. @rafariossaa 

Thanks.

**Comment by rafariossaa** [comment]
Hi,
  COS is an storage created by IBM and it is used in their kubernetes clusters. 
  That page indicate page is for VMs not for kubernetes.
  Maybe  you can create a minimal PVC yaml and try to get the COS provisioned and report them with a minimal example and not with a full chart.

**Comment by Bhargav6611** [comment]
Hi, 
We are able to provision COS backed PV but the same PVC when using during installation of the ELK stack using the Helm chart the Elastic-search pods are not available. In both these scenarios(above mentioned) and creating a custom PVC of COS storage and using the same during installation the elastic search pods are not available.  
Is there any solution/alternative for the same or should we use the "Block storage" itself as default storage type?

Thanks.

**Comment by rafariossaa** [comment]
Hi,
  Let's see if someone from the community can provide help here. 
  Have you had issues with block storage ? If not, I would suggest to use that one.
