### ISSUE TITLE
[bitnami/airflow] Airflow worker readinessProbe connection refused

### ISSUE THREAD

**Issue by junaidnasir-ps** [bitnami/charts#10371]
### Name and Version

bitnami/airflow 12.3.0

### What steps will reproduce the bug?

1. using "KubernetesExecutor" and default readinessProbe settings
2. Create a long running dag
3. describe airflow worker pod

### What do you see instead?

```
  Normal   Pulled     43s   kubelet            Container image "docker.io/bitnami/airflow-worker:2.2.5" already present on machine
  Normal   Created    43s   kubelet            Created container base
  Normal   Started    42s   kubelet            Started container base
  Warning  Unhealthy  10s   kubelet            Readiness probe failed: dial tcp 10.12.7.96:8793: connect: connection refused
```

### Additional information

is it expected behaviour? should liveness and readiness probes on worker pods be disabled?

**Comment by javsalgar** [comment]
Does the container get restarted because of the probes? Could you share the logs of the worker?

**Comment by fmulero** [comment]
Hi Junaid

This behaviour could be in some manner expected. By default this readiness probe starts 30 seconds after the pod startup, and the main container could not be ready at the very beginning. In your case, maybe the long running dag is causing the readinessProbe is taking more than expected. It might be worth increasing the `worker.readinessProbe.initialDelaySeconds `

From your comment above:
> It says up for retry if i set the retry in dag, otherwise it just fails the job.

I am assuming that your worker pod is not restarting but the dag job yes. Could you share the configuration and how long it is taking?

**Comment by bdsoha** [comment]
I am having the same issue on version 2.3.2 and 2.3.3

**Comment by junaidnasir-ps** [comment]
@bdsoha no, still an issue. I think what's happening is k8 executor doesn't need http endpoint to report the status of job. we will need to modify the readiness probe with some kubectl command. I haven't got around to do that yet

**Comment by fmulero** [comment]
You can increase the initial delay for the readiness probe setting the value `worker.readinessProbe.initialDelaySeconds` in your values file or adding it with `--set` in your `helm` command

**Comment by bdsoha** [comment]
I needed to completely remove both the `readiness` and `liveness` probes from my chart.

**Comment by MainRo** [comment]
> I needed to completely disable both the `readiness` and `liveness` probes from my chart.

I use the same fix for now. In my case, I have a PythonOperator task that runs for more than 5 minutes.

The current readiness and liveness probes are TCP probes on the worker logs port (8793 by default). I am not sure but my understanding of the airflow doc (https://airflow.apache.org/docs/apache-airflow/2.3.3/logging-monitoring/logging-tasks.html#serving-logs-from-workers) is that the log server is not started when using the k8s executor.

**Comment by junaidnasir-ps** [comment]
Any update on this? It was moved from in progress to Solved?

**Comment by mujiannan** [comment]
According to documents: [airflow-configurations-kubernetes-executor](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/configurations-ref.html#kubernetes-executor)  
Consider the default configuration:  
```conf
[kubernetes-executor]
enable_tcp_keepalive = True
tcp_keep_cnt = 6
tcp_keep_intvl = 30
```

6 × 30 = 300 seconds = 5 minutes  
These default configurations caused a long-running pod can't survive for 5 minutes.  
After 5 mins, the scheduler treat non-response pods as "broken", and mark refered task instances as "failed".

**Comment by mujiannan** [comment]
> I assume that there is nothing providing any liveness/readiness/health check for a pod running a task in kubernetes when we use KubernetesExecutor and PythonOperator?

So just disable `readinessProbe` and  `livenessProbe` of workers in deployment?  
When we use `CeleryKubernetesExecutor`, we expect that:  
1. `celery-worker-pods` have `readinessProbe`  and `livenessProbe`  
2. `kubernetes-pods` running with `LocalExecutor` have no `readinessProbe` and  `livenessProbe`, or respond to `readinessProbe` and  `livenessProbe`  

Maybe we can customize the `pod_template.yaml` to implement above.  
But for convenience, we just disable all `readinessProbe` and  `livenessProbe`, to support pod running a long-time task.

**Comment by fmulero** [comment]
Hi @mujiannan

You can set liveness and readiness probes for worker nodes with these values: https://github.com/bitnami/charts/blob/bb98b43256eb4479bbc2623835e6aca070daa6bb/bitnami/airflow/values.yaml#L716-L745

Please note that the liveness and readiness logic depends on the executor you chose.

**Comment by GavinColwell** [comment]
My company's k8s clusters had strict rules requiring all containers to have `readinessProbe` and `livenessProbe` enabled so disabling was not an option.

We resolved this by modifying the `pod_template.yaml` to use an `exec` probe instead of a `tcpSocket` which I've recreated in my personal fork https://github.com/GavinColwell/charts/commit/66898a700a5f40b25d1a93c9f445d184397bdba6

You can also probably resolve it without modifying the chart directly by setting custom probes in your values files
```yaml
worker:
  customStartupProbe:
    exec:
      command:
        - airlfow
        - jobs
        - check
        - --local
        - --job-type
        - LocalTaskJob
  customReadinessProbe:
    exec:
      command:
        - airlfow
        - jobs
        - check
        - --local
        - --job-type
        - LocalTaskJob
  customLivenessProbe:
    exec:
      command:
        - airlfow
        - jobs
        - check
        - --local
        - --job-type
        - LocalTaskJob
   
```
