### ISSUE TITLE
segmentation fault when running bitnami solr helm chart

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#10380]
### Name and Version

bitnami/solr  , 4.0.10

### What steps will reproduce the bug?

helm install solr bitnami/solr

### Are you using any custom parameters or values?

no

### What is the expected behavior?

solr pods should be running.

### What do you see instead?

crashloopbackoff error in solr pods .

### Additional information

output of logs of solr pod 
kubectl logs solr-0
```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f567bbf9514, pid=7, tid=0x00007f567b45a700
#
# JRE version:  (8.0_322-b06) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x61b514]  CodeHeap::allocate(unsigned long, bool)+0x2b4
#
# Core dump written. Default location: /opt/bitnami/solr/server/core or core.7
#
# An error report file with more information is saved as:
# /opt/bitnami/solr/server/hs_err_pid7.log
/scripts/setup.sh: line 8:     7 Segmentation fault      (core dumped) /opt/bitnami/scripts/solr/entrypoint.sh /opt/bitnami/scripts/solr/run.sh
```

**Comment by rafariossaa** [comment]
Hi,
  Could you provide in which kubernetes cluster are you deploying this ? 
  could you take a look to the log in: `/opt/bitnami/solr/server/hs_err_pid7.log` ? Maybe there is some useful information.

**Comment by abhishekgupta2205** [comment]
i am deploying it in minikube . container is not created .

**Comment by rafariossaa** [comment]
Is the host machine an AMD64 architecture ? could you check if you have enough ram ?
I am deploying it in minikube and I am not able to reproduce the issue.

**Comment by abhishekgupta2205** [comment]
yes . i have almost 4gb free ram

**Comment by abhishekgupta2205** [comment]
/opt/bitnami/solr/bin/solr: line 688:   116 Segmentation fault      (core dumped) nohup "$JAVA" "${SOLR_START_OPTS[@]}" $SOLR_ADDL_ARGS -Dsolr.log.muteconsole -jar start.jar "${SOLR_JETTY_CONFIG[@]}" $SOLR_JETTY_ADDL_CONFIG > "$SOLR_LOGS_DIR/solr-$SOLR_PORT-console.log" 2>&1


these are some additional logs i found

**Comment by rafariossaa** [comment]
Thanks for sharing this,
In general segmentation faults errors are not very helpful because usually there is not info about the cause.
Could you tried what I indicated in my previous comment ? 
Also, I have a follow up question, In which architecture (ARM, AMD64, ...) are you running this ?

**Comment by abhishekgupta2205** [comment]
@rafariossaa i can not reduce the no of replicas it is giving error because min 3 is required for election voting

**Comment by rafariossaa** [comment]
@abhishekgupta2205 It is just to triage the issue. Could you try that and then start increasing the number of nodes. 
I think this is a resources (memory) related issue.

> AMD64

Ok, thanks.
