### ISSUE TITLE
Docker images for JupyterHub 2.x

### ISSUE THREAD

**Issue by rmoreas** [bitnami/charts#10398]
### Name and Version

bitnami/jupyterhub

### What is the problem this feature will solve?

Hi,
I love the bitnami helm chart for jupyterhub, but it seems to only support jupyterhub 1.5.0. Any idea when bitnami packaged images for JupyterHub 2.x will be available for use with the bitnami jupyterhub helm chart?

### What is the feature you are proposing to solve the problem?

Build docker images for jupyterhub 2.3 for use with the bitnami jupyterhub helm chart.

**Comment by carrodher** [comment]
Regarding the JupyterHub 2.x branch release, we are waiting for upstream to release a 2.x for jupyterhub-for-k8s, that is why the release process was stopped on our side.
We will keep this issue open and update it once the release is resumed.

**Comment by rmoreas** [comment]
Great. Thanks for the update!

**Comment by carrodher** [comment]
Not tested on our side but it can works, yes
