### ISSUE TITLE
Operator 1.13.x should use RabbitMQ 3.10.x

### ISSUE THREAD

**Issue by discostur** [bitnami/charts#10413]
### Name and Version

rabbitmq-cluster-operator-2.6.3 

### What is the problem this feature will solve?

Regarding this commit rabbitmq cluster operator 13.x should deploy newly created clusters with rabbitmq version 3.10.x:

https://github.com/rabbitmq/cluster-operator/commit/d8fb5177fe1a572bbc746a28a86b76ccffdb4286

Just tried and bitnami operator still creates new clusters with old version 3.9.x.

**Comment by carrodher** [comment]
Thanks for letting us know, I just created an internal task to bump the RabbitMQ version, but please take into account according to the mentioned comment, the current RabbitMQ 3.9.x is fully supported:
> The operator deploys RabbitMQ `3.10.2` by default and **supports versions from `3.8.8` upwards**. The operator requires Kubernetes `1.19` or newer.

**Comment by carrodher** [comment]
A new version was released using RabbitMQ 3.10, see https://github.com/bitnami/charts/commit/cf3305fb24452e0ee159dfb1851c9cd3648df972. Please note it can take some time between the changes published in GitHub and the new version appearing in the Bitnami Helm repository (`helm repo update bitnami` is needed).

Don't hesitate to reopen this issue if something doesn't work as expected or if you have any other questions.
