### ISSUE TITLE
wordpress showing Access denied for user 'root'@'localhost', after 79 days of uptime

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#10439]
### Name and Version

wordpress:13.0.16

### What steps will reproduce the bug?

deploy bitnami wordpress site and wait

### Are you using any custom parameters or values?
```yaml
    helm:
      parameters:
      - name: ingress.enabled
        value: "true"
      - name: ingress.pathType
        value: "Prefix"
      - name: ingress.ingressClassName
        value: "nginx"
      - name: ingress.hostname
        value: "www.website123.xyz"
      - name: ingress.tls
        value: "true"
      - name: wordpressScheme
        value: "https"
      - name: persistence.size
        value: "200Gi"
      - name: ingress.annotations.cert-manager\.io/issuer
        value: "cluster-letsencrypt-issuer"
      - name: ingress.annotations.cert-manager\.io/issuer-kind
        value: "ClusterIssuer"
```
### What is the expected behavior?

Working wordpress website

### What do you see instead?

It worked until it didn't

```
mariadb 19:59:50.47 Welcome to the Bitnami mariadb container
mariadb 19:59:50.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 19:59:50.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 19:59:50.47 
mariadb 19:59:50.47 INFO  ==> ** Starting MariaDB setup **
mariadb 19:59:50.49 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 19:59:50.50 INFO  ==> Initializing mariadb database
mariadb 19:59:50.50 DEBUG ==> Ensuring expected directories/files exist
mariadb 19:59:50.51 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 19:59:50.51 INFO  ==> Using persisted data
mariadb 19:59:50.52 INFO  ==> Running mysql_upgrade
mariadb 19:59:50.53 INFO  ==> Starting mariadb in background
2022-05-25 19:59:50 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.5.15-MariaDB) starting as process 48 ...
2022-05-25 19:59:50 0 [Note] InnoDB: Uses event mutexes
2022-05-25 19:59:50 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-05-25 19:59:50 0 [Note] InnoDB: Number of pools: 1
2022-05-25 19:59:50 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-05-25 19:59:50 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
2022-05-25 19:59:50 0 [Note] InnoDB: Using Linux native AIO
2022-05-25 19:59:50 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2022-05-25 19:59:50 0 [Note] InnoDB: Completed initialization of buffer pool
2022-05-25 19:59:50 0 [Note] InnoDB: 128 rollback segments are active.
2022-05-25 19:59:50 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-05-25 19:59:50 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-05-25 19:59:50 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-05-25 19:59:50 0 [Note] InnoDB: 10.5.15 started; log sequence number 2026459638; transaction id 2212065
2022-05-25 19:59:50 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2022-05-25 19:59:50 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-05-25 19:59:50 0 [Note] Server socket created on IP: '127.0.0.1'.
2022-05-25 19:59:51 0 [Warning] 'proxies_priv' entry '@% root@wordpress-xyz-travisloyd-www-mariadb-0' ignored in --skip-name-resolve mode.
2022-05-25 19:59:51 0 [Note] InnoDB: Buffer pool(s) load completed at 220525 19:59:51
2022-05-25 19:59:51 0 [Note] Reading of all Master_info entries succeeded
2022-05-25 19:59:51 0 [Note] Added new Master_info '' to hash table
2022-05-25 19:59:51 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.5.15-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2022-05-25 19:59:52 3 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
Reading datadir from the MariaDB server failed. Got the following error when executing the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
FATAL ERROR: Upgrade failed
mariadb 19:59:52.55 INFO  ==> Stopping mariadb
2022-05-25 19:59:52 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
2022-05-25 19:59:52 0 [Note] Event Scheduler: Purging the queue. 0 events
2022-05-25 19:59:52 0 [Note] InnoDB: FTS optimize thread exiting.
2022-05-25 19:59:52 0 [Note] InnoDB: Starting shutdown...
2022-05-25 19:59:52 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
2022-05-25 19:59:52 0 [Note] InnoDB: Buffer pool(s) dump completed at 220525 19:59:52
2022-05-25 19:59:52 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-05-25 19:59:52 0 [Note] InnoDB: Shutdown completed; log sequence number 2026459678; transaction id 2212066
2022-05-25 19:59:52 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
```

### Additional information

I saw an article that suggested if there was a "redeployment" that it could cause the password to change.  I'm posting next a listing of the deployment to show all values are all 79 days old ... except the two pods which I've restarted in an attempt to fix.  So, I think the password should not have been regenerated.

**Comment by lknite** [comment]
For someone who comes across this later, I was able to get things back up and working by:
1. edit the mariadb statefulset
```
kubectl edit statefulset wordpress-<website>-mariadb & setting a command to run:
```

2. set a command to be run instead of the default from the container
```
        - /opt/bitnami/mariadb/bin/mysqld_safe
        - --skip-grant-tables
        - --skip-networking
        - --datadir=/bitnami/mariadb/data
```
3. now reset the root@% password
```
k exec -it wordpress-<website>-mariadb-0 -- bash

mysql -u root
> use mysql;
> FLUSH PRIVILEGES;
> ALTER USER 'root'@'%' IDENTIFIED BY '<password to use from your secret>';
```
4. modify the statefulset to remove the command added earlier & kill the pod

**Comment by javsalgar** [comment]
Hi,

This is very strange. It seems to me that maybe someone/some process accessed the database manually and performed changes in the credentials, causing the configuration to break.

**Comment by lknite** [comment]
We can eliminate another person doing something.  Some sort of race condition maybe?

It is possible a control plane node or worker node may have been restarted.  (I lost the chance to gather evidence.)

**Comment by SeidChr** [comment]
just had the same issue after installing, uninstalling, installing again of the wordpress helm chart
assuming helm generated a new password for mariadb and the statefulset still contained the old one?
probably not the same issue here.

**Comment by sandipndev** [comment]
I can confirm, this is not yet fixed. This issue persists.

**Comment by apriil15** [comment]
same issue here

--

my solution:
I use Docker desktop & Windows. Just `reset` the cluster, and it worked.

But I don't think this should be a good way to solve it.

![image](https://user-images.githubusercontent.com/24965046/216670128-794e2f1e-8c31-4ed8-9888-7c3fc7541a9d.png)

**Comment by grissly-man** [comment]
Just experienced this same issue, many thanks to @lknite for that solution

**Comment by grissly-man** [comment]
@carrodher I see this was marked as `Solved` - is that only accounting for the manual steps outlined in this issue? Or does a later version safeguard against this behavior?

**Comment by grissly-man** [comment]
We have been affected by this bug again, is there a long term fix in the cards?

**Comment by NiklasRosenstein** [comment]
For me the issue was that the MariaDB PVC still existed, and a fresh install of the chart into the same namespace and release name had the MariaDB pod use the data of the previous MariaDB instance which was initialized with a different password. Deleting the PVC fixed it. This had me stumped for a while until I realized `kubectl get all` doesn't show PVCs, so I didn't notice the resource was still present.

**Comment by SeidChr** [comment]
The correct fix for this would be to have an option to provide existing user data on deployment, and not fail if the user exists.

**Comment by NiklasRosenstein** [comment]
I haven't tried this mind you, but I expect that this is what `mariadb.auth` is for? To use pass in credentials via Helm values instead of relying on Helm generating a random string for you.

![image](https://github.com/bitnami/charts/assets/1318438/b5f01dae-83b3-41e4-bfc8-6c5a2adfca82)

**Comment by serafdev** [comment]
@lknite 
> Can someone help me to understand why all this was necessary? I'd like to avoid an outage like this in the future.

I'm suspecting when the mariadb goes down, or there is a redeployment, the secret is replaced but since the database table is persistent we have the old password there.

The database is going down because of multiple failures, the failures come from the livenessProbe that the Kubernetes cluster is sending every x seconds, if you look at the definition of the livenessProbe inside the StatefulSet you can see it's using the password from the Secret.

The correct fix would be to not redeploy a randomly generated Secret every time the Helm Chart is upgraded, simply "ignoring" that resource if it exists would do the thing if that's even a thing!

All that was necessary to update the root password to match the newly updated Secret

**Comment by serafdev** [comment]
> For someone who comes across this later, I was able to get things back up and working by:
> 
> 1. edit the mariadb statefulset
> 
> ```
> kubectl edit statefulset wordpress-<website>-mariadb & setting a command to run:
> ```
> 
> 2. set a command to be run instead of the default from the container
> 
> ```
>         - /opt/bitnami/mariadb/bin/mysqld_safe
>         - --skip-grant-tables
>         - --skip-networking
>         - --datadir=/bitnami/mariadb/data
> ```
> 
> 3. now reset the root@% password
> 
> ```
> k exec -it wordpress-<website>-mariadb-0 -- bash
> 
> mysql -u root
> > use mysql;
> > FLUSH PRIVILEGES;
> > ALTER USER 'root'@'%' IDENTIFIED BY '<password to use from your secret>';
> ```
> 
> 4. modify the statefulset to remove the command added earlier & kill the pod

Thanks for this, this happened to me in 2 other different charts (moodle and mariadb itself)

The solution I found for all the charts is to always use the `externalDatabase` or `existingSecret` parameter in the `values.yaml`, depending on the case

**Comment by arvinep** [comment]
To fix this issue, `persistentVolumeClaimRetentionPolicy` needs to be set from its default value of `Retain` to `Delete`, which means the volume and data will still survive the crashes, but PVC/PV will be deleted in the user planned deletion such as `helm uninstall` of the MariaDB statefulSet. 

```
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
```

1. Make sure the StatefulSetAutoDeletePVC feature gate is enabled on the API server and the controller manager. https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

```
minikube start --feature-gates=StatefulSetAutoDeletePVC=true
```

2. Helm chart has to include the `persistentVolumeClaimRetentionPolicy` field in its templates.


I have opened this https://github.com/bitnami/charts/pull/35007 to fix this behavior.

3. Once the PR is merged, you can set the Retention Policy to Delete when you need it, such as in your dev environment.

```
helm install wordpress --set primary.persistentVolumeClaimRetentionPolicy.whenDeleted=Delete ./wordpress
```

After this, once you `helm uninstall wordpress`, the related PVC and PVs will also be deleted automatically.
