### ISSUE TITLE
How to enable a Private Load balancer in AWS to poll events internally (within VPC)

### ISSUE THREAD

**Issue by vikrantsundriyal** [bitnami/charts#10442]
### Name and Version

bitnami/kafka 14.0.2

### What is the problem this feature will solve?

Hi,

We have launched Kafka in AWS EKS with default cluster iP service. Other services hosted on EKS can consume / publish events using ClusterIP.
As an additional requirement, we are targeting to open polling for other services in same network (VPC) but hosted outside Kubernetes. The documented way to enable external access creates a publicly accessible classic load balancer. 
I am opening this feature request since i dont see any direct documented way to achieve what we wish.

### What is the feature you are proposing to solve the problem?

Provision / Enable an internal load balancer outside Kubernetes which can be consumed by a service hosted outside K8S but is in same private network. This load balancer should not be public-facing one since we need to allow only intra VPC calls.

 

### What alternatives have you considered?

An alternate approach could be to fine-tune the security group of load balancers manually or use some configurations to restrict the security group.

**Comment by rafariossaa** [comment]
Hi,
  I ma not sure if I understood correctly, but if the LB need to be outside kubernetes there is nothing that can be done inside kubernetes (this chart).
  In any case this is very particular use case. If it were possible to implement this in the chart, I would suggest you to create your own version of the chart.

**Comment by vikrantsundriyal** [comment]
@rafariossaa Rafael Ríos Saavedra
Thanks for your response. Yes LB has to be outside K8S. However, being outside doesn't mean it has to always be public (Exposed to the internet). And thats my problem statement/feature request: Can we launch a LB outside K8S but within the network where K8S is launched. 
e.g In general AWS VPC is launched with Private and Public Subnet. Inside VPC's Private Subnet I have K8S Cluster and many other non containerised services on virtual machines. I want LB to be in same Private Subnet but outside K8S so that it can be reached by other non-containerised services. There is no need to make it totally public as only services in the private subnet will interface.

**Comment by rafariossaa** [comment]
@vikrantsundriyal, the thing is that  with a chart you can not create a LB that is outside k8s. A chart is a .yaml that create a bunch of k8s objects (services, deployment, PVC, etc.) and all this objects are inside k8s.

**Comment by vikrantsundriyal** [comment]
@rafariossaa ,
I think you are missing something, there is a way to create a loadbalancer outside K8S. Please check the link below, it clearly mentions how to launch a load balancer by passing a few additional params with chart. I have myself tried it multiple times. In K8S, it creates a service of type LoadBalancer and in AWS it creates a load_balancer of type "Classic". 

Hope with this you can relate the  relevance of my query/feature request.

https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/external-access/
=============
Command that i use
=============
helm install my-release bitnami/kafka --version 14.0.2  --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer --set externalAccess.service.ports.external=9094 --set externalAccess.autoDiscovery.enabled=true --set serviceAccount.create=true --set rbac.create=true
=============

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the miss understanding here. For me `outside the k8s cluster` meant that it is not controlled by k8s cluster. Service type `LoadBalancer` is controlled and it is, kind of,  `in` the cluster. I thought you were thinking in an extra layer on top of k8s.
  
  >  Can we launch a LB outside K8S but within the network where K8S is launched.
`LoadBalancer` is going to have an external IP from the k8s. Maybe there is something that can be done with some parameters in the case of AWS. 
 For this particular need I would suggest to ask in AWS forums if there is such possibility. 
  I found [this link ](https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0)more illustrative than the official kubernetes documentation.
Would a `Nodeport` type  work for you ?

**Comment by vikrantsundriyal** [comment]
Closing the issue with the final note on the working solution:
**Approach**: Creating a Private NLB for accessing events with network (in AWS case VPC) can be achieved by using proper annotations with Kafka Service. These annotations can be passed as config values.
**Documentation to be referred.**
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/
**Command:**
helm install test-release bitnami/kafka --version 14.0.2  
	--set externalAccess.enabled=true 
	--set externalAccess.service.type=LoadBalancer 
	--set externalAccess.service.ports.external=9094 
	--set externalAccess.autoDiscovery.enabled=true 
	--set serviceAccount.create=true 
	--set rbac.create=true 
	--set-string externalAccess.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=nlb 
	--set-string externalAccess.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-nlb-target-type"=ip
    --set-string externalAccess.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"=true 
	--set-string externalAccess.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-subnets"="subnet-011yyyyyyyyyyy909\,subnet-011xxxxxxxxxxxxxe909

**Comment by vikrantsundriyal** [comment]
Closing as issue is fixed.

**Comment by rafariossaa** [comment]
Thanks for coming back and sharing your findings.
