### ISSUE TITLE
bitnami/mongodb-exporter displays only one mongodb_ up metric

### ISSUE THREAD

**Issue by 77557231** [bitnami/charts#10440]
### Name and Version

bitnami/mongodb-exporter:0.32.0-debian-10-r24

### What steps will reproduce the bug?

Hello, after deploying different mongog versions for many times, only one mongodb is displayed in metrics_ Up indicator, so Prometheus can only display one mongodb_ Up, grafana can't fully monitor Mongo. However, the deployment of mongodb shard metrics is normal.

Please help guide where the operation is not standardized, or there is a problem with chart. I really can't find the cause of the problem. Please ask for help.

The operation is as follows:
helm pull bitnami/mongodb (APP VERSION:5.0.8)

Turn on metrics
![image](https://user-images.githubusercontent.com/24469889/170406437-81b67a38-fc98-4781-92dc-5cb744a32de2.png)

The single instance Mongo is deployed successfully, and the metrics log is normal.
![image](https://user-images.githubusercontent.com/24469889/170406325-3b17b1f1-d66d-4514-b43a-43b94071e3bc.png)

 kubectl port-forward --namespace test1 svc/ts-mongodb-metrics 9216:9216 &
 echo "Prometheus Metrics URL: http://127.0.0.1:9216/metrics"

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Mongodb-shared metrics are normal. There are a large number of metrics, such as mongodb_ connections,mongodb_ asserts_ total.

for example：
![image](https://user-images.githubusercontent.com/24469889/170409162-f1066611-c4bd-4b7b-9fa9-0c87306715b3.png)

### What do you see instead?

There is only one mongodb_ up.
![image](https://user-images.githubusercontent.com/24469889/170409294-5ff83936-673e-49b1-ab08-2fda182b603a.png)

### Additional information

We tested different versions of bitnami/mongodb-exporter and found this phenomenon.

**Comment by patrickmslatteryvt** [comment]
I found this earlier today as well and was able to determine that the `0.30.x` release of the `bitnami/mongodb-exporter` image worked as expected, but that the `0.31.x` and `0.32.x` releases were affected.

**Comment by FraPazGal** [comment]
Hello @patrickmslatteryvt, @77557231,

This should be related to the change introduced in `mongodb-exporter@0.31.2` that we are currently discussing in #9877. To avoid having duplicated issues, let's close this one and continue the discussion in the other thread.
