### ISSUE TITLE
How to use the Bitnami template？

### ISSUE THREAD

**Issue by xcbeyond** [bitnami/charts#10454]
### Name and Version

bitnami/template

### What is the problem this feature will solve?

create a new chart  base on [template directory](https://github.com/bitnami/charts/tree/master/template)). If the `helm create <helm-name> -starter` command is used to create the helm, no additional configuration is required?

### What is the feature you are proposing to solve the problem?

As above

**Comment by carrodher** [comment]
It is just a basic scaffolding to be copied in a different place and modify the placeholders in order to create a new Helm chart. Some templates or sections may not be necessary, in the same way, it is possible something else may need to be added

**Comment by xcbeyond** [comment]
@carrodher  The placeholders inside are not manually replaced and modified, I guess through tools or something, if so, how to replace

**Comment by xcbeyond** [comment]
@carrodher thank you.

**Comment by stepanselyuk** [comment]
crossposting https://github.com/bitnami/charts/issues/20350#issuecomment-1930084848
