### ISSUE TITLE
[external-dns] Duplicate yaml key - service.type

### ISSUE THREAD

**Issue by allanhung** [bitnami/charts#10468]
### Name and Version

bitnami/external-dns 6.5.0

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/service.yaml#L15
https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/service.yaml#L49

### What do you see instead?
```
yaml: unmarshal errors:
  line 25: mapping key "type" already defined at line 15
```
### Additional information

This might not a bug for helm, but some yaml parser does not accept duplicate keys.

**Comment by carrodher** [comment]
Thanks for letting us know, I just created the above PR to solve this issue
