### ISSUE TITLE
[kafka] labels issues when both jmx-exporter & kafka-exporter are enabled

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#10470]
### Name and Version

bitnami/kafka: 17.1.0

### What steps will reproduce the bug?

instanciate a kafka with the configuration from below

### Are you using any custom parameters or values?

```
metrics:
  kafka:
    enabled: true
  jmx:
    enabled: true
```

### What is the expected behavior?

2 services monitors & 2 services are created , each service monitor matches it's associated service

### What do you see instead?

both service have the same labels & both service monitors have the same selector,

so the 2 services monitors each match the 2 labels

**Comment by jouve** [comment]
introduced in https://github.com/bitnami/charts/pull/8666

**Comment by jouve** [comment]
I think of 2 solutions:
* using `app.kubernetes.io/component` :
  - jmx-exporter : keep `app.kubernetes.io/component: metrics` 
  - kafka-exporter: `app.kubernetes.io/component: cluster-metrics` 

* using a new label:
  - jmx-exporter : 
    ```
    app.kubernetes.io/component: metrics
    scope: broker
    ```
  - kafka-exporter: 
    ```
    app.kubernetes.io/component: metrics
    scope: cluster
    ```

wdyt ?

**Comment by javsalgar** [comment]
I'd go for the first approach

**Comment by jouve** [comment]
great, I'll submit a PR :)
