### ISSUE TITLE
grafana-loki | Labels of index-gateway for Service & StatefulSet don't match (it's quick to fix)

### ISSUE THREAD

**Issue by Dima-Diachenko-work** [bitnami/charts#10471]
### Name and Version

bintami/grafana-loki

### What steps will reproduce the bug?

Hi! 
I really like your charts, thanks for your work! 
I can live with this bug but I decided to share it with you guys.

Just look at these labels for **index-gateway** Service and STS:

https://github.com/bitnami/charts/blob/0140c31a2ad1c31f520d940bad4be903927926ae/bitnami/grafana-loki/templates/index-gateway/statefulset.yaml#L9

and 

https://github.com/bitnami/charts/blob/0140c31a2ad1c31f520d940bad4be903927926ae/bitnami/grafana-loki/templates/index-gateway/service.yaml#L9

Traffic will not route.

### What do you see instead?

Could you do the same label for both?

**Comment by rafariossaa** [comment]
Hi,
  Thanks for reporting this, but I was not able to see that string in the `redendered.yaml`:

```bash
$ helm template myloki bitnami/grafana-loki  > rendered.yaml

$ ag "app.kubernetes.io/component" rendered.yaml 
14:    app.kubernetes.io/component: loki
30:    app.kubernetes.io/component: loki
121:    app.kubernetes.io/component: gateway
218:    app.kubernetes.io/component: loki
343:    app.kubernetes.io/component: promtail
369:    app.kubernetes.io/component: promtail
464:    app.kubernetes.io/component: distributor
484:    app.kubernetes.io/component: distributor
498:    app.kubernetes.io/component: gateway
512:    app.kubernetes.io/component: gateway
526:    app.kubernetes.io/component: loki
553:    app.kubernetes.io/component: ingester
573:    app.kubernetes.io/component: ingester
587:    app.kubernetes.io/component: promtail
602:    app.kubernetes.io/component: promtail
616:    app.kubernetes.io/component: querier
636:    app.kubernetes.io/component: querier
650:    app.kubernetes.io/component: query-frontend
669:    app.kubernetes.io/component: query-frontend
683:    app.kubernetes.io/component: query-frontend
704:    app.kubernetes.io/component: query-frontend
718:    app.kubernetes.io/component: promtail
728:      app.kubernetes.io/component: promtail
739:        app.kubernetes.io/component: promtail
754:                    app.kubernetes.io/component: promtail
841:    app.kubernetes.io/component: distributor
853:      app.kubernetes.io/component: distributor
865:        app.kubernetes.io/component: distributor
880:                    app.kubernetes.io/component: distributor
950:    app.kubernetes.io/component: gateway
958:      app.kubernetes.io/component: gateway
970:        app.kubernetes.io/component: gateway
985:                    app.kubernetes.io/component: gateway
1057:    app.kubernetes.io/component: query-frontend
1068:      app.kubernetes.io/component: query-frontend
1079:        app.kubernetes.io/component: query-frontend
1094:                    app.kubernetes.io/component: query-frontend
1435:    app.kubernetes.io/component: ingester
1446:      app.kubernetes.io/component: ingester
1459:        app.kubernetes.io/component: ingester
1474:                    app.kubernetes.io/component: ingester
1554:    app.kubernetes.io/component: querier
1567:      app.kubernetes.io/component: querier
1580:        app.kubernetes.io/component: querier
1595:                    app.kubernetes.io/component: querier
```

**Comment by Dima-Diachenko-work** [comment]
@rafariossaa 
sure thing you will not see using defaults. :) 

You use default values config, without index-gateway, that is why your renders do not contain it. 
You should first enable `index-gateway` in the values file to see that. 

Please, just look at templates into **charts/bitnami/grafana-loki/templates/index-gateway** folder. 
Your service and statefulset have different labels! 
Why do you use render to see that?

**Comment by rafariossaa** [comment]
Hi,
 I have just merged a fix for this.
 Could you give it a try ?

**Comment by Dima-Diachenko-work** [comment]
Yes, why not. Have you published version: 2.0.4? I can't pull it via Helm.

And if you want to ask me to test based on the current repo code - yes, looks like it works!

**Comment by carrodher** [comment]
Please note before pushing the Helm charts themselves (the .targz package) into the Helm registry, we perform some internal tests on top of different k8s clusters such as AKS, IKS, TKG, GKE, etc.

In terms of time, may be a slight difference between the appearance of the code in GitHub and the chart in the registry.
In this case, it is taking longer than usual since we detected an issue testing the Helm chart and we need to fix it. Being said that, it shouldn't take long to be released

**Comment by Dima-Diachenko-work** [comment]
Just realized that we missed one more point. :( 

https://github.com/bitnami/charts/blob/96f447cd8654b6db51d9301c841bacb3a13089b3/bitnami/grafana-loki/templates/index-gateway/statefulset.yaml#L55

<img width="477" alt="image" src="https://user-images.githubusercontent.com/104848965/171385801-1b903ca3-f3a2-4cfa-865d-83daf01a182a.png">
Need to actualize it also. 
Not critical at all but need to finish with it.

**Comment by carrodher** [comment]
😭  thanks for letting us know, would you like to create a PR as @rafariossaa did?
