### ISSUE TITLE
add telegram config in alertmanager crd

### ISSUE THREAD

**Issue by kconde2** [bitnami/charts#10474]
### Name and Version

bitnami/kube-prometheus 0.56.3

### What is the problem this feature will solve?

allow using telegram config in alert manager receivers section 

### What is the feature you are proposing to solve the problem?

Allow telegram configuration in telegram CRD

https://prometheus.io/docs/alerting/latest/configuration/#telegram_config

### What alternatives have you considered?

Using webhook like described here
https://muetsch.io/sending-prometheus-alerts-to-telegram-with-telepush.html

**Comment by javsalgar** [comment]
Hi,

Looking at the yaml, I see this:

```
  {{- if .Values.alertmanager.configuration }}
  alertmanagerConfiguration: {{- include "common.tplvalues.render" (dict "value" .Values.alertmanager.configuration "context" $) | nindent 4 }}
  {{- end }}
```

Would this work for your case?

**Comment by kconde2** [comment]
Hello,

This works might works. Will give a try. 

Thanks for your answer.
