### ISSUE TITLE
odoo15 chart in the k8s environment can not be directly accessed through the address of static resources,

### ISSUE THREAD

**Issue by caesar168** [bitnami/charts#10479]
### Name and Version

bitnami/odoo 

### What steps will reproduce the bug?

1,odoo15 chart in the k8s environment can not be directly accessed through the address of static resources, you must log in to the system to access these images, 
2,the system will give a prompt: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. 
3,However, in docker and docker-compose environments, it can be directly accessed. This can have a negative impact on the business. In many business scenarios, some images are to be able to be accessed and displayed directly from the address, but now they cannot be directly accessed and therefore cannot be displayed. 
4,These images are stored in the filestore directory.

### Are you using any custom parameters or values?

The default values are adopted exactly and no changes have been made.

### What is the expected behavior?

In a k8s environment, odoo15 should be able to access, open, or display directly through the url address of the resource.

### What do you see instead?

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
