### ISSUE TITLE
[bitnami/keycloak] Keycloak behind ALB session problem when replica > 1

### ISSUE THREAD

**Issue by Navapon** [bitnami/charts#10482]
### Name and Version

bitnami/keycloak:9.0.5

### What steps will reproduce the bug?

I was using chart version 5.0.1 before which is no issue with clustering mode by use reference [5.0.1](https://artifacthub.io/packages/helm/bitnami/keycloak/5.0.1)
```
proxyAddressForwarding: true
```

But when I've upgrading to version 9.0.2 the key 'proxyAddressForwarding' was outdated and using env instead by extraENv

```
- name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
  value: "true"
- name: KEYCLOAK_FRONTEND_URL
  value: "https://keycloak.domain.dev
```

## Problem

It works as expected when set replica just 1
But when creating the replica of more than **1** there have problem like an example

- when first request login to **_bitnami-keycloak-pod-1_** it fine but when the session expire or have to refresh or check the code mechanism in the keycloak app happen when the request go to another **_pods_** there is always shown error like
```
failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Code not valid"}
```

it looks like a session or cookie problem try with proxy not working

So, I use the [sticky session ](https://www.keycloak.org/docs/latest/server_installation/index.html#sticky-sessions)  but still have the same problem below is config [alb](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-group-attributes) I used for the sticky session

```
alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
alb.ingress.kubernetes.io/target-type: ip
```

Please help give an idea and suggestion if you need more information please let me know

### Are you using any custom parameters or values?

```
keycloak:
  replicaCount: 1
  pdb:
    create: true
    minAvailable: 1
  postgresql:
    enabled: false
  externalDatabase:
    host: aaaa.ap-southeast-1.rds.amazonaws.com
    user: keycloak
    database: keycloak_new
    port: 5432
    existingSecret: "keycloak"
    existingSecretPasswordKey: "DB_PASSWORD"
  serviceDiscovery:
    enabled: true
  extraEnvVars:
    - name: KC_LOG_CONSOLE_OUTPUT
      value: "json"
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_FRONTEND_URL
      value: "https://keycloak.domain.dev"
  image:
    debug: false
  auth:
    createAdminUser: true
    adminUser: admin
    existingSecret:
      name: keycloak
      keyMapping:
        admin-password: KEYCLOAK_PASSWORD
        management-password: WILDFLY_PASSWORD
  tls:
    enabled: false
    autoGenerated: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: keycloak.domain.dev
    path: /*
    tls: false
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-group-attributes: "stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=36000"
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:111111111:certificate/22222222222
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/group.name: alb-apps
  rbac:
    create: true
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list


```

### What is the expected behavior?

Application work with Pods scalable

### What do you see instead?

Cannot set replica more than 1

### Additional information

upgrade keycloak v15 - chart 5.0.1
to
keycloak v18 - chart - 9.0.2

**Comment by miguelaeh** [comment]
>upgrade keycloak v15 - chart 5.0.1
>to
>keycloak v18 - chart - 9.0.2

Upgrading 4 major versions at once is not recommended. Every major version introduces a non-backward compatible change, so you would be introducing 4 non-backward compatible changes at once.
My recommendation would be to update one by one, adapting whatever is required as described [here](https://docs.bitnami.com/kubernetes/apps/keycloak/administration/upgrade/). 
Then, if the issue persists, you can share more concrete information about the exact step to reproduce it.

**Comment by zanitete** [comment]
I'm having the same issue.
I think the issue was introduced with in v8.0.0, specifically with the migration to the Quarkus Mode here: https://github.com/bitnami/charts/pull/10095
