### ISSUE TITLE
[bitnami/redis] Using existingClaim for replicas as well

### ISSUE THREAD

**Issue by AssenDimitrov** [bitnami/charts#10498]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

This will allow users to specify on which pre-created volume claim their replica can be stored. Right now this options is available for master only, but would be nice if replica can also be created on something pre-configured. 
Replica "kind" is also something that can be used as workaround, but still "kind" can be changed only for master, but not for replicas.

### What is the feature you are proposing to solve the problem?

Eliminating the need of using 3rd party automatic provisioners when deploying production ready Redis helm chart on premise.

### What alternatives have you considered?

Using 3rd party provisioner for local NFS storage.

**Comment by carrodher** [comment]
Thanks for the suggestion, I just created the above PR implementing that feature. Could you give it a try?
