### ISSUE TITLE
[bitnami/harbor] Ingress certificates

### ISSUE THREAD

**Issue by egrist** [bitnami/charts#10518]
### Name and Version

bitnami/harbor 13.2.0

### What steps will reproduce the bug?

I would like to access Harbor with a valid certificate through Ingress (https://harbor.domain.redacted)
We have a certificate issued from Letsencrypt and I would like to make the Harbor ingress deploy in kubernetes use that certificate.

Through the documentation to my understanding is to set:
exposureType: ingress
externalURL: https://harbor.domain.redacted
ingress.core.hostname: harbor.domain.redacted
ingress.core.tls: true
ingress.notary.hostname: notary.domain.redacted
ingress.notary.tls: true

But I'm confused on how to configure it to use a certificate, should I deploy a tls secret, or a generic secret and then point to that beforehand, or do I put the content of ca.crt/tls.crt/tls.key in some predetermined format.

Any pointers?

### Are you using any custom parameters or values?

exposureType: ingress
externalURL: https://harbor.domain.redacted
ingress.core.hostname: harbor.domain.redacted
ingress.core.tls: true
ingress.notary.hostname: harbor.domain.redacted
ingress.notary.tls: true

### What is the expected behavior?

Reaching https://harbor.domain.redacted with the valid certificate that I got from letsencrypt

### What do you see instead?

I get an Acme Co ingress certificate instead of letsencrypt

### Additional information

Not really a bug report but ask for a clarification how to do.

**Comment by egrist** [comment]
Never mind, I found details in the documentation at https://github.com/bitnami/charts/blob/master/bitnami/harbor/values.yaml

**Comment by Roia5** [comment]
Can you share what you found in the docs? I couldn't find a way to create the secret without putting it in the values.yaml file.
(Putting it in the values.yaml file is not possible since it is saved in Git for ArgoCD deployment)

**Comment by egrist** [comment]
@Roia5 I first deployed a kubernetes tls secret with the certificate and private key like so:

`kubectl create secret tls harbor.example.com-tls --cert ./certificate.crt --key ./private.key --namespace <namespace>`

And changed these values when deploying the chart:
```
externalURL: https://harbor.example.com
ingress:
  core:
    extraTls:
      - hosts:
          - harbor.example.com
        secretName: harbor.example.com-tls
    hostname: harbor.example.com
    tls: true
```
Hope this helps.

**Comment by Roia5** [comment]
Thank you very much!
