### ISSUE TITLE
Custom name of Redis PVC

### ISSUE THREAD

**Issue by michalgozdowski** [bitnami/charts#10515]
### Name and Version

bitnami/redis 16.9.10

### What is the problem this feature will solve?

Currently there is no easy way to overwrite the name of the redis pvc. This is painful when it comes to different naming policies or even trying to stick with the naming convention/pattern of application. The pvc name is now created as: {`{ printf "redis-data-%s-master" (include "common.names.fullname" .) }}`.

### What is the feature you are proposing to solve the problem?

Adding `master.perstistance.name` parameter.

### What alternatives have you considered?

Creating PVC outside of the charts and using `master.persistence.existingClaim`.

**Comment by carrodher** [comment]
Thanks for the suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by michalgozdowski** [comment]
Thank you for response, basically the issue is that pvc for redis is created with "redis-data-*" prefix. Is there any purpose of setting pvc in redis chart as "redis-data-%s-master"? I can see in other charts i.e. mongodb that pvc is created using only "common.names.fullname".

**Comment by carrodher** [comment]
If there is no collision with other PVC name the common function can be used without problem
