### ISSUE TITLE
helm install bitnami/elasticsearch with persistent storage CreateContainer error

### ISSUE THREAD

**Issue by KennethNagin** [bitnami/charts#1053]
**Which chart**:

bitnami/elasticsearch

**Description**
helm install bitnami/elasticsearch with persistent storage is unable to create its data pods.
The one data pod is failing with a status of CreateContainerError.

BTW: It succeeds when I install with data.persistence.enabled=false.  Two data pods are created.

**Steps to reproduce the issue:**
1. created host pv with storageClass=local-storage.  Its path is /bitnami/elasticsearch/data
2. helm install bitnami/elasticsearch --name skydive-elasticsearch --replace --tls --set master.replicas=1 --set coordinating.service.type=NodePort --set master.service.type=NodePort --set data.persistence.storageClass=local-storage
3.$ kubectl get pods
NAME                                                              READY     STATUS                 RESTARTS   AGE
skydive-elasticsearch-elasticsearch-coordinating-only-769cfjsft   1/1       Running                0          20m
skydive-elasticsearch-elasticsearch-coordinating-only-769crmj6f   1/1       Running                0          20m
skydive-elasticsearch-elasticsearch-data-0                        0/1       CreateContainerError   0          20m
skydive-elasticsearch-elasticsearch-master-758c9cbdd9-897nc       1/1       Running                0          20m
4.$kubectl describe  pod skydive-elasticsearch-elasticsearch-data-0
Events:
  Type     Reason            Age                 From                   Message
  ----     ------            ----                ----                   -------
  Warning  FailedScheduling  21m (x2 over 21m)   default-scheduler      pod has unbound PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled         21m                 default-scheduler      Successfully assigned default/skydive-elasticsearch-elasticsearch-data-0 to 9.148.244.26
  Warning  Failed            20m (x8 over 21m)   kubelet, 9.148.244.26  Error: Error response from daemon: create  /bitnami/elasticsearch/data/: " /bitnami/elasticsearch/data/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
  Normal   Pulled            16m (x22 over 21m)  kubelet, 9.148.244.26  Successfully pulled image "docker.io/bitnami/elasticsearch:6.6.0"
  Normal   Pulling           1m (x82 over 21m)   kubelet, 9.148.244.26  pulling image "docker.io/bitnami/elasticsearch:6.6.0"

**Describe the results you received:**

data pod fails to be created

**Describe the results you expected:**

Deployment would succeed and pvcs related to data pods would be bound to pvs created prior to helm install.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1+icp", GitCommit:"843201eceab24e7102ebb87cb00d82bc973d84a7", GitTreeState:"clean"}

```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by javsalgar** [comment]
Hi,
Could you let us know which platform you used? I never saw this error: `includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]"`
