### ISSUE TITLE
Clearer documentation about "existingSecret"

### ISSUE THREAD

**Issue by lamenawuer** [bitnami/charts#10544]
### Name and Version

bitnami/keycloak:9.2.1

### What is the problem this feature will solve?

The documentation as in how to add existing secrets to the chart is very poor. On top of that, the values.yaml file with the default values reflects what is supposed to be an indication on how to populate your secret, but it looks like it is the configuration that has to be included in the chart itself. Overall very confusing and not clear, I managed to get my instance working by headbutting the wall but it wasn't pretty

### What is the feature you are proposing to solve the problem?

Clearer documentation regarding existing secrets for admin and psql passwords and a better explanation in the values.yaml

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by sulaimon-lilt** [comment]
@lamenawuer can you share an example or explanation of how you got this to work? That would help others like me running into the same issue and not getting any where with the documentation.

**Comment by lamenawuer** [comment]
@sulaimon-lilt hello, basically you have to just give the name of the existing secret to the variable, not defining it the secret under it (like in a helm way). So:
`existingSecret: MY_EXTRA_SECRET`

Then, create a secret called MY_EXTRA_SECRET in the usual kube way, but under data you organise your password like so:

```
data:
    admin-password: myPasswordKey
    management-password: myManagementPasswordKey
    tls-keystore-password: myTlsKeystorePasswordKey
    tls-truststore-password: myTlsTruststorePasswordKey
```

@carrodher . I cannot modify this documentation https://docs.bitnami.com/kubernetes/apps/keycloak/configuration/manage-passwords/, which is the most confusing one. I can eventually make a PR for the "values.yaml" file

**Comment by carrodher** [comment]
This documentation is publicly available at https://github.com/bitnami/charts-docs/blob/main/charts/keycloak/_manage_passwords.md.erb, are you facing any issues when trying to modify it or send a PR?

**Comment by lamenawuer** [comment]
@carrodher I'm getting an access denied when pushing my changes, just to my branch

**Comment by carrodher** [comment]
There shouldn't be issues, I mean, it is a regular GH repository where several PRs were created by pushing changes to a personal branch, see https://github.com/bitnami/charts-docs/pulls?q=is%3Apr+is%3Aclosed.

What are the steps you are doing?
