### ISSUE TITLE
postgresql validations in common chart broken (and no longer used)

### ISSUE THREAD

**Issue by fenech** [bitnami/charts#10559]
### Name and Version

bitnami/postgresql 10.12.9 (failure) 
bitnami/postgresql 11.6.2 (no longer used)

### What steps will reproduce the bug?

Running `helm upgrade` on an older version of the Postgresql chart (e.g. 10.12.9) using the latest Common chart fails, due to a validation failure.

### Are you using any custom parameters or values?

Passing value to subchart:

```yaml
postgresql:
  existingSecret: my-secret-name
```

### What do you see instead?

Helm Upgrade fails due to a validation error:

```
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
```

### Additional information

The validations in `bitnami/common/templates/validations/_postgresql.tpl` cause an error during `helm upgrade` on older versions of the Postgresql chart. This is because:

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/validations/_postgresql.tpl#L42

Returns a non-empty string. Due to the use of `quote`, it produces a literal string of length 2 `""`.

This in turn causes:

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/validations/_postgresql.tpl#L59

To ignore `existingSecret`, since `$globalValue` is non-empty.

This problem was previously hidden, since the code that checked the value used to only assert that it was non-empty. But in newer versions of the chart (since de27be6e649472608f076a04a36be3674fe3b84e), it also checks explicitly against this nearly-empty string: 

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/validations/_postgresql.tpl#L16

So on old versions of the Postgresql chart (e.g. 10.12.9) that pick up the newer version of the Common chart (since it [depends on `1.x.x`](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/Chart.yaml#L8)), we get a failure in validation at upgrade time.

---

On the one hand, that's causing a problem on older charts, whereas on the other hand, this part of the library is no longer used in newer charts (since they just removed the validation step from `NOTES.txt`).

So perhaps it would make sense to fix the original issue (I think removing `| quote` would be sufficient) in Common 1.x.x and consider releasing a new Common 2.x.x without these unused validations?

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay.
  I think I am missing something here.
  Postgresql chart version `10.12.9` depends on common `1.10.0`, and it is that exact version and not a newer/older one. If you update the dependency weird things can happen because that version of the postgresql chart is not intended to be used with any other version of common. 
  I understand what you suggest of using `1.x.x` and `2.x.x.`, but also could lead to similar problems if some changes introduced in `2.3.0` are not compatible with `2.2.0`.

**Comment by fenech** [comment]
Hi, thanks for your response. 

First of all, I was looking in `Chart.yaml` and saw `1.x.x`, whereas of course I should've looked in `Chart.lock` to see the exact version (`1.10.0`, as you say). To be clear, I am not _trying_ to use postgres 10.12.9 with any other version of Common (though it is possible that I am doing so inadvertently). Sorry for any confusion there.

I can see that the check I mentioned was introduced in Common 1.10.3, so it seems like either my attempts at diagnosing the issue were along the wrong lines, or that I was somehow using a newer, incompatible version of the common chart. To be honest I'm a bit confused about what happened to cause this to fail, and during my attempts to debug this, I couldn't actually find the Common chart files that were being used on my system. I was making changes to the ones that I thought were in use and they weren't having any effect on the result.

I am now using a newer version of the Postgresql chart and it is working without issue, so I'm not sure if there's much value to debugging this issue, especially given that I'm not sure how to reproduce it and it only affects a quite old version of the chart.

In any case, perhaps it still makes sense to remove these validations from the latest versions of Common, since they appear to be unused.

**Comment by rafariossaa** [comment]
Don't worry, I would suggest to close this issue and reopen it or open a new one in the case  you reproduce the issue.

We are in a process of standardization of the chart catalog, I will notify about this to the teammates that working on that.
Thanks for noticing it !
