### ISSUE TITLE
Readiness Probe not updating

### ISSUE THREAD

**Issue by PiyushRaj02** [bitnami/charts#10555]
### Name and Version

bitnami/keycloak 8.0.0

### What steps will reproduce the bug?

I am using Keycloak version 17.0.1 and trying to update the existing readiness probe from /realms/master to /auth/realms/master but the changes are not reflecting in the pod definition which is causing the readiness probe to fail with HTTP status 404.

Readiness Probe configuration in the values.yaml file is as below -
```
readinessProbe:
  enabled: true
  httpGet:
    path: /auth/realms/master
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 20
```

Default Readiness Probe -
```
Readiness:  http-get http://:http/realms/master delay=60s timeout=5s period=10s #success=1 #failure=20
```

Trying to update readiness probe to -
```
Readiness:  http-get http://:http/auth/realms/master delay=60s timeout=5s period=10s #success=1 #failure=20
```

PS - I have set the KC_HTTP_RELATIVE_PATH="/auth" in the dockerfile and have tested readiness with curl -v http://0.0.0.0:8080/auth/realms/master to be working by logging onto the pod.

Kubectl Event Logs -

Events:
```
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m51s                  default-scheduler  Successfully assigned keycloak-ns/keycloak-0 to ip-x-x-x-x.ap-southeast-2.compute.internal
  Normal   Pulling    6m50s                  kubelet            Pulling image "<Image Name>"
  Normal   Pulled     6m50s                  kubelet            Successfully pulled image "<Image Name>" in 123.323554ms
  Normal   Created    6m50s                  kubelet            Created container keycloak
  Normal   Started    6m50s                  kubelet            Started container keycloak
  Warning  Unhealthy  101s (x25 over 5m41s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
```

### Are you using any custom parameters or values?

KC_HTTP_RELATIVE_PATH="/auth"

Even enabling Health check via the environment variable doesn't update the default readiness url
KC_HEALTH_ENABLED=true

### What is the expected behavior?

Readiness Probe url should update to the custom url

### What do you see instead?

Readiness probe doesn't update to the custom url and remains to the default configuration.

**Comment by marcosbc** [comment]
Hi @PiyushRaj02, the current chart is not adapted for the use of `KC_HTTP_RELATIVE_PATH`. However, we are happy to review any contribution that adds support for that feature. If you want, feel free to send a PR with these changes!

**Comment by hwaastad** [comment]
Should work if defining your: customLivenessProbe and customReadinessProbe to use /auth in path (and disable default probes)
