### ISSUE TITLE
Enable the replication factor in kafka for topic

### ISSUE THREAD

**Issue by abhi-dwivedi** [bitnami/charts#1055]
Hi

How can i enable the replication factor for topic by default is 1 i need to make it 3 .

Regards
Abhinav D

**Comment by abhi-dwivedi** [comment]
@bitnami any update /?

**Comment by tompizmor** [comment]
Hi @abhi-dwivedi,

AFAIK, you set the desired replication factor when you create the topic:

From the [kafka quickstart guide](https://kafka.apache.org/quickstart#quickstart_multibroker):

```
$ kafka-topics.sh --create --zookeeper ZOOKEEPER_SVC_NAME:2181 --replication-factor 3 --partitions 1 --topic my-replicated-topic
```
Please note you will need to update the ZOOKEEPER_SVC_NAME placeholder by the name of your zookeeper kubernetes service.

**Comment by abhi-dwivedi** [comment]
Hi

Thanks for update but is there any way I can't set default value of replication factor which is currently set as 1 .

And how can I do it dynamically.

Regards
Abhinav D

**Comment by rjemanuele** [comment]
@abhi-dwivedi   Just to clarify this you're looking to set `default.replication.factor` in the broker configuration?  https://kafka.apache.org/documentation/#brokerconfigs

AFAIK, this chart lacks that capability easily.  I've been trying to do that myself also.  If @bitnami-apps-team knows of a way that'd be great. 

@abhi-dwivedi  I'm looking at adding it but I highly doubt it is something that can be changed dynamically as it is set into the config files.  There is a work-around but it comes with a caveat.  You can specify the config setting to be put into the config files by setting https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L35.  The drawback to this is that it will only use those settings in the config files and nothing self from the helm chart.

PS.  I am in no way affiliated with bitnami, I just use their tools.

**Comment by rjemanuele** [comment]
@abhi-dwivedi So... here's what I know:

Currently there is no way to set `default.replication.factor` from the helm chart.

Kafka is installed into the container using the bitnami-pkg tool https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-9/Dockerfile#L10

This helm cart utilizes the toolsets from https://github.com/bitnami/nami and https://github.com/bitnami/nami-core to build the config.  The nami tools are used by bitnami to ease deployments and make them consistent to a variety of systems (cloud, docker, kubernetes, etc.).  In this case the nami tools handle the conversion of values set in the environment into the `server.properties` config file for kafka.

The nami tools are installed into the minideb-extras docker image using https://github.com/bitnami/minideb-extras/blob/master/stretch/Dockerfile . It seems that upon running `nami_initialize` from within `app-entrypoint.sh` that will configure the already unpacked kafka image at `/opt/bitnami/kafka` using the above nami tools and the definitions in `/kafka-inputs.json` with the package definitions the nami tools use in `/.nami/components/com.bitnami.kafka/`.

To make this image "just work", it will require modifying the docker image to support a variable for the default replication factor (its on Github), modify the bitnami package to support it (not sure if they're public), and then modify the helm chart with that env value (on Github).

**Comment by tompizmor** [comment]
@rjemanuele! Wow! You indeed did an excellent research job and basically, all you said is right! 

We need to add a new environment variable to expose that configuration option but as you said that part of the code is not published on GitHub right now so we will work on adding it and update this issue once it is available.

**Comment by tompizmor** [comment]
@abhi-dwivedi @rjemanuele I just updated the kafka container image so it supports the KAFKA_DEFAULT_REPLICATION_FACTOR environment variable.

Also, the chart has been updated to set this same configuration using the value `kafkaDefaultReplicationFactor`

**Comment by rjemanuele** [comment]
@tompizmor Thank you for the turn around on this.  I had hacked together a container image derived from the bitnami kafka image over the weekend that inserted the setting right into `server.properties` during `run.sh` but this will be better.

**Comment by tompizmor** [comment]
I am glad you find it useful! 
I am going to close this issue, please open a new one if you find something else.

**Comment by Akashs12345** [comment]
what about new chart how can we set replication factor in new chart of kafka bitnami chart version 28.0.4
(11 Apr, 2024)

**Comment by carrodher** [comment]
Thank you for reaching out and for your interest in our project. We'd be happy to assist you, but to do so effectively, we'll need some more details. Could you please create a separate issue filling the Issue template?

Providing this information will help us better understand your situation and assist you in a more targeted manner.
