### ISSUE TITLE
chown: changing ownership of '/bitnami/odoo': Operation not permitted

### ISSUE THREAD

**Issue by ddevops** [bitnami/charts#10550]
### Name and Version

bitnami/odoo 15.0.20211010-debian-10-r0

### What steps will reproduce the bug?

basic helm chart giving below error while application getting started

chown: changing ownership of '/bitnami/odoo': Operation not permitted

### What do you see instead?

odoo 17:15:47.52 
odoo 17:15:47.54 Welcome to the Bitnami odoo container
odoo 17:15:47.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
odoo 17:15:47.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
odoo 17:15:47.55 
odoo 17:15:47.56 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
odoo 17:15:47.71 INFO  ==> Ensuring Odoo directories exist
chown: changing ownership of '/bitnami/odoo': Operation not permitted

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/odoo#community-supported-solution).
This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
