### ISSUE TITLE
auth not working for v3

### ISSUE THREAD

**Issue by herbalizer404** [bitnami/charts#1056]
When I start a new cluster by setting the auth enable and rootpassword, it works with v2, but the authentication is not working with v3. So I try to enable it by etcdctl v3 but the cluster dont work well anymore, I have to disabe auth v3.
How can I configure auth with helm chart parameters?

**Comment by javsalgar** [comment]
Hi,

Thanks for opening a ticket. Could you let us know the parameters you used to deploy the chart? We want to reproduce the issue in our side

**Comment by raoofm** [comment]
@herbalizer404 ?
