### ISSUE TITLE
Adding Falco to catalog

### ISSUE THREAD

**Issue by Jeremy-Boyle** [bitnami/charts#10578]
### Name and Version

Falco Container + Helm Chart

### What is the problem this feature will solve?

Falco is the open source standard tool for continuous risk and threat detection across Kubernetes, containers and cloud. Falco continuously detects unexpected behavior, configuration changes, intrusions, and data theft in real time.

Falco has been downloaded over 30 million times and has a strong, rapidly-increasing community of contributors and adopters .

Additionally adding Falco would help organizations who actively utilize VMware enterprise Tanzu Application Catalog. 

### What is the feature you are proposing to solve the problem?

Bitnami image created for Falco

Bitnami Helm chart created for Falco

Possibly Support Falco Exporter + Falco Sidekick / other charts aswell

### What alternatives have you considered?

Falco has a few helm charts currently , alternative is to install those with there containers.

**Comment by Jeremy-Boyle** [comment]
I have no issue supporting a MR for the helm chart, 

I may need assistance with the container creation and the guidelines for that .

**Comment by Jeremy-Boyle** [comment]
I have created the following for preparation:
- https://github.com/Jeremy-Boyle/bitnami-docker-falco
- https://github.com/Jeremy-Boyle/bitnami-docker-falcosidekick
- https://github.com/Jeremy-Boyle/bitnami-docker-falco-exporter
- https://github.com/Jeremy-Boyle/bitnami-docker-falco-event-generator
  
Fork:
- https://github.com/Jeremy-Boyle/charts/tree/falco-chart

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this. I am adding it to our internal list for consideration.
  We will come back when we have news.

  You could find the contributing guidelines [here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md).

**Comment by Jeremy-Boyle** [comment]
Thank you @rafariossaa 

I started with the first major deployment which is falco itself.

Work can be seen in this [commit](https://github.com/bitnami/charts/commit/502bf198a10e9d2462181d5065c2033764cb5a67)

**Comment by rafariossaa** [comment]
ok, thanks for sharing.

**Comment by Jeremy-Boyle** [comment]
Hello , 

Any movement on this? 

I can create the helm chart no problem, however there is no public way that I see to create a container for you guys.

If you have any information on now to build a container the way bitnami does I would be more than happy to assist, with every process . 

I see examples with something referencing stack-smith , looks like a internal repository/ tool that bitnami is using. 

If you supply the Falco library's and versions , I could possibly build the container using the same practices.

I would really like to pull this into TAC Enterprise.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
