### ISSUE TITLE
Master service in Redis with replication architecture and sentinel

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#10575]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

I want to have external RW access and now it doesn't create service for just master.

### What is the feature you are proposing to solve the problem?

create service that only redirect to master.

**Comment by joancafom** [comment]
Hi @arezvani 

I am afraid I do not understand your issue. Could you please provide more details?

> I want to have external RW access and now it doesn't create service for just master.

I have successfully deployed a `bitnami/redis` chart using the default values and I can see a service being created for the master pod:

```bash
$ helm install theta bitnami/redis
$ kubectl get pods 
NAME                     READY   STATUS    RESTARTS   AGE
theta-redis-master-0     1/1     Running   0          2m32s
theta-redis-replicas-0   1/1     Running   0          2m32s
theta-redis-replicas-1   1/1     Running   0          104s
theta-redis-replicas-2   1/1     Running   0          76s
$ kubectl get svc
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
kubernetes             ClusterIP   10.96.0.1        <none>        443/TCP    7d8h
theta-redis-headless   ClusterIP   None             <none>        6379/TCP   2m55s
theta-redis-master     ClusterIP   10.96.225.62     <none>        6379/TCP   2m55s
theta-redis-replicas   ClusterIP   10.104.242.108   <none>        6379/TCP   2m55s
```

Are you using any custom values?

**Comment by teklabania** [comment]
@joancafom, you started the cluster with the defaults as you stated, so sentinel is disabled. @arezvani requested for redis-master service with sentinel enabled. It would be really handy to have (if possible) redis-master service to let applications that don't support sentinel write to master.

**Comment by carrodher** [comment]
Could you please create a new issue filling the template with your specific scenario so we can provide better support? Thanks in advance
