### ISSUE TITLE
Atomic pod commands were incorrectly separated

### ISSUE THREAD

**Issue by apeschel** [bitnami/charts#10574]
### Name and Version

Most charts in the last year

### What steps will reproduce the bug?

So there's this PR that's quite large: https://github.com/bitnami/charts/pull/6102/

One of the many things done in this PR was to split the "command" field for many charts into "command" and "args". This change was not noted in the PR notes, or any comments on the PR. It seems to have been included ad-hoc by the PR author. The problem is that the commands that were split were mostly atomic, and splitting them not only doesn't make sense, but prevents users from being able to add arguments onto the commands to customize the behavior.

I'll quickly point out the elephant in the room and move on: mega PRs that touch a ton of stuff at once lead to problems that are impractical to catch at review, and are difficult to revert when caught later. With the sheer scope of the PR, it's easy to see why this change was overlooked. 

Here's an example of a split that break things:

https://github.com/bitnami/charts/pull/6102/files#diff-a340de1525573cda43aadf4e249215a9b78d57f319d18f1ac792bdc1289833a0L83-L86

The atomic command should be

```
command:
  - /bin/bash
  - -c
  - /opt/bitnami/scripts/start-scripts/start-master.sh
```

The script `start-master.sh` is a startup script that starts redis. It is the core command that needs to be run for the pod, and "bash -c" is just there to ensure it gets run. `start-master.sh` has logic to handle any additional arguments that are passed to the pod, which allows users to customize the redis configuration with something like the following:

```
args:
  - "--loadmodule"
  - "/usr/lib/redis/modules/redisgraph.so"
```

Unfortunately, the PR in question splits the command as follows:

```
command:
  - /bin/bash
args:
  - -c
  - /opt/bitnami/scripts/start-scripts/start-master.sh
```

This is bad for a couple of reasons:
1. It doesn't make sense to have a redis pod that is only running bash. `start-master.sh` is the actual command that users want to run.
2. It is no longer possible to pass arguments to the `start-master.sh` script.

### What do you see instead?

How to fix:

This command split should be reverted for all the charts where it was done. Atomic commands should be combined into a single command, and `args` should be reserved for arguments to the atomic command.

### Additional information

There is a workaround possible. The user can set args as follows:

```
args:
  - -c
  - /opt/bitnami/scripts/start-scripts/start-master.sh
  - "--loadmodule"
  - "/usr/lib/redis/modules/redisgraph.so"
```

This is less ideal than having start-master.sh be part of the command, since it requires users to peak behind the scenes of the chart to know what they need to copy into their variant of the args. But it does work.

**Comment by apeschel** [comment]
Not stale.

**Comment by alemorcuq** [comment]
Hi, @apeschel. You are right about this not making much sense. However, changing these commands now would result in breaking changes and would require a new major for every. Since there's a workaround that works, I'd say this has low priority for us. We will keep this in mind for future majors. Thanks for creating this ticket.
