### ISSUE TITLE
[Feature Request] MongoDB allow specify some parameters for arbiters separately

### ISSUE THREAD

**Issue by md2k** [bitnami/charts#1057]
Hi guys, it is possible to allow setup for arbiters separately resources `limits`, `podafinity`, `nodeselector`, `tolerations` separately. 
Currently if we setup Limits and other parameters from above `arbiter` pods gets parameters same as primary and masters, what is useless because this type of pods not include any data and just helps maintain election's flow. it will be a westing of resources to grant them same cpu/memory limits, also probably `arbiters` can be placed on different nodes which is for example much smaller versus nodes who gets mongodb primary and slaves

Thank you in advance.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. Regarding the PR, you need to do it in the helm/charts repo (where Bitnami mongodb is) in order to work. The upstreamed folder just syncs with the helm/charts repo
