### ISSUE TITLE
How to upgrade bitnami/external-dns from 4.11.0 to latest version

### ISSUE THREAD

**Issue by vsana1** [bitnami/charts#10582]
### Name and Version

bitnami/external-dns 4.11.0

### What steps will reproduce the bug?

As  Bitnami has removed all Helm chart versions older than six months from their repository, we want to know how to upgrade from 4.11.0 to latest stable version without any outage ? please help us to understand the detailed steps.

### What do you see instead?

Steps for Upgrade from 4.11.0 to latest stable version

**Comment by javsalgar** [comment]
Hi,

If you want to upgrade to the latest version, a `helm upgrade` command should be enough. If you need to use a version that was removed from the current index, then you need to follow the instructions here: https://github.com/bitnami/charts/issues/10539
