### ISSUE TITLE
Elasticsearch x-pack enabled documentation

### ISSUE THREAD

**Issue by stratos-fasly** [bitnami/charts#10584]
### Name and Version

bitnami/elasticsearch-18.2.5

### What is the problem this feature will solve?

After enable elasticsearch x-pack security feature kibana dashboard only giving "Kibana server is not ready yet." 
is there any clear steps and documentation for how to deploy x-pack enabled helm chart ?

### What is the feature you are proposing to solve the problem?

elasticsearch helm chart deployment steps with x-pack enabled stable version

**Comment by stratos-fasly** [comment]
It's giving below error
[ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED

**Comment by javsalgar** [comment]
Hi,

Could you provide the set of values that trigger the issue?

**Comment by stratos-fasly** [comment]
Hi,

@javsalgar 
please fin the command, could you please check and let me know any misconfigurations here 

helm upgrade --install my-kibana  . --set global.kibanaEnabled=True \
--set kibana.ingress.enabled=true \
--set kibana.ingress.ingressClassName="nginx" \
--set kibana.ingress.path="/my-kibana(/|$)(.*)" \
--set kibana.extraConfiguration."server\.basePath"=/my-kibana \
--set kibana.ingress.hostname="*" \
--set kibana.ingress.annotations."nginx\.ingress\.kubernetes\.io/rewrite-target"=/$2 \
--set security.enabled=true \
--set security.elasticPassword="password" \
--set security.tls.autoGenerated=true \
--set kibana.tls.enabled=true \
--set kibana.tls.autoGenerated=true \
--set kibana.elasticsearch.security.auth.enabled=true \
--set kibana.elasticsearch.security.auth.kibanaPassword="password" \
--set kibana.elasticsearch.security.auth.elasticsearchPasswordSecret="my-kibana-elasticsearch" \
--set kibana.elasticsearch.security.auth.tls.enabled=true

**Comment by javsalgar** [comment]
Hi,

If it is getting a connection refused, it may be because the elasticsearch node may not be running, could you check the output of `kubectl get pods`?
