### ISSUE TITLE
Advice on WordPress Chart is incorrect

### ISSUE THREAD

**Issue by EvanCarroll** [bitnami/charts#10583]
### Name and Version

bitnami/wordpress v14.3.2

### What steps will reproduce the bug?

On line 58 of the chart you have this

```
export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ include "common.names.fullname" . }} --include "{{ "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}" }}")
```

It prompts
That will **not** work with k3s's kubectl.

### Are you using any custom parameters or values?

Nope

### What is the expected behavior?

Not sure what --include should do. It just doesn't work at all on my system.

### What do you see instead?

```console
$ k3s kubectl get svc --namespace default my-wordpress --include "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}"
error: unknown flag: --include
See 'kubectl get --help' for usage.
```

**Comment by FraPazGal** [comment]
Hello @EvanCarroll,

You are right, it seems this is a typo on our `NOTES.txt`. The correct command would be:

```
kubectl get svc --namespace default my-wordpress --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}"
```

Could you please verify this new command works as expected on your side? If you want, you can also create a PR fixing this and we'll be happy to review it before merging it.

**Comment by FraPazGal** [comment]
Hello @EvanCarroll,

Could you please try installing the chart in a fresh cluster? That error shouldn't be related to an issue in the chart but to an issue assigning an IP when using local clusters like the K8s docker one.

**Comment by jmcausing** [comment]
Hi. So this doesn't work using Minikube + Docker + Windows WSL? I got the same error and it doesn't have the loadbalancer IP. 

`kubectl get svc --namespace jmwp1 jmwp-wordpress -o wide
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR
jmwp-wordpress   LoadBalancer   10.105.36.154   <pending>     80:30544/TCP,443:32420/TCP   13m   app.kubernetes.io/instance=jmwp,app.kubernetes.io/name=wordpress`

`export SERVICE_IP=$(kubectl get svc --namespace jmwp1 jmwp-wordpress --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil`

`minikube ip
192.168.49.2`

no LB IP

`kubectl get svc --namespace jmwp1 jmwp-wordpress -o yaml`
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jmwp
    meta.helm.sh/release-namespace: jmwp1
  creationTimestamp: "2022-07-03T22:33:41Z"
  labels:
    app.kubernetes.io/instance: jmwp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-15.0.7
  name: jmwp-wordpress
  namespace: jmwp1
  resourceVersion: "25423"
  uid: 3c1c74ff-96e3-4ae1-97c6-9ae8da46d103
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.36.154
  clusterIPs:
  - 10.105.36.154
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30544
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32420
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: jmwp
    app.kubernetes.io/name: wordpress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

**Comment by FraPazGal** [comment]
Hello @jmcausing,

Please note that is a limitation of your K8s cluster, minikube in this case. It doesn't include a Load Balancer and that is why the external IP stays `pending`. In this case, please refer to [minikube's documentation](https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-tunnel) for a solution on this or its community for further support about their platform.
