### ISSUE TITLE
[bitnami/postgresql-ha] pgpool child processes exit with status 256, keep on respawning.

### ISSUE THREAD

**Issue by jonathon2nd** [bitnami/charts#10596]
### Name and Version

bitnami/postgresql-ha/9.1.1

### What steps will reproduce the bug?

Install with standard values, only setting up Auth

### What do you see instead?

Exact same as https://github.com/bitnami/charts/issues/4862

Here is the full log from pgpool, fresh install and restart
[postgresql-ha-2-pgpool-5dc5565669-8nwxf_pgpool.log](https://github.com/bitnami/charts/files/8846123/postgresql-ha-2-pgpool-5dc5565669-8nwxf_pgpool.log)

**Comment by jonathon2nd** [comment]
My mistake. During testing and reding the referenced issue, I was setting `childLifeTime` to 60 or other values like that and it was making no difference. Upon setting it to `0` things seems to be behaving again. 

Not sure why this started happening either, we have been running the same postgresql-ha for almost a year with no issue, then it just started last friday.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing your findings.
