### ISSUE TITLE
solr liveness and readiness probes are checking for cloud even if cloudEnabled=false

### ISSUE THREAD

**Issue by RichardSufliarsky** [bitnami/charts#10592]
### Name and Version

bitnami/solr 4.0.9 (5.1.2 also)

### What steps will reproduce the bug?

1. disable cloud
2. let liveness and readiness probes enabled (default)
3. helm install
4. pod gets restarted every few minutes (probes failing)

You can see exceptions in pod logs "Solr instance is not running in SolrCloud mode." when probes are calling solr assert --cloud.

### Are you using any custom parameters or values?

--set cloudEnabled=false --set cloudBootstrap=false

### What is the expected behavior?

Probes should work regardless of solr mode.

### What do you see instead?

Exceptions in pod logs: "Solr instance is not running in SolrCloud mode."

### Additional information

This proposal could help: https://github.com/bitnami/charts/issues/10502#issuecomment-1143299712

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will review it and provide feedback
