### ISSUE TITLE
Mazor bug at headless service [MongoDB-sharded]

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#10591]
### Name and Version

bitnami/mongo-sharded    ---   version: 5.0.0

### What steps will reproduce the bug?

Basic helm install

### What is the expected behavior?

Headless service should be connected to all associate pods. Whereas it isn't showing all mongos pods!!

### What do you see instead?
```
root@file-upload-service-7c94857757-4bs7d:/# nc -vz userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc 27017
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != 10-42-12-80.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-shard0-data-1.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-shard1-data-0.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-mongos-1.userrealm-iot83-mongodb-sharded.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-configsvr-0.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-shard0-data-0.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-shard2-data-1.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
DNS fwd/rev mismatch: userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local != userrealm-iot83-mongodb-sharded-shard2-data-0.userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local
userrealm-iot83-mongodb-sharded-headless.userrealm-iot83.svc.cluster.local [10.42.12.80] 27017 (?) open
```

### Additional information

I am reaching to MongoDB-sharded headless service from another pod .

**Comment by marcosbc** [comment]
Hi @pankaj-dahiya, could you describe what you mean by this?

>Headless service should be connected to all associate pods. Whereas it isn't showing all mongos pods!!

Note that the headless service is meant to serve as an entrypoint for connecting to MongoDB pods, meaning you specify the hostname of the headless service when connecting your applications (or CLI) to the MongoDB cluster.

Have you tried connecting to the headless service with the `mongo-shell` CLI?

**Comment by pankaj-dahiya** [comment]
"Note that the headless service is meant to serve as an entrypoint for connecting to MongoDB pods" ----- This is what I am stating above. The headless service is connected to mongos-1 but not to mongos-0 !!

**Comment by marcosbc** [comment]
@pankaj-dahiya Unfortunately I could not reproduce your issue. When deploying the service, the headless one is linked to both mongos instances.

Could you share more information on how you are deploying your chart?

In addition, if you are able to find the issue on your side, feel free to contribute as a PR, we'd be happy to check it.
