### ISSUE TITLE
tomcat missing help files (host manager)

### ISSUE THREAD

**Issue by mykaelnguyen** [bitnami/charts#106]
Description:  When clicking on this link: http://<host>/docs/html-host-manager-howto.html?org.apache.catalina.filters.CSRF_NONCE=F3DAEEADB91D1517391ECF6F8ECD0782 the resource is not available (404).

Steps to Reproduce:
1. Login to Tomcat through External-IP
2. Click on "Host Manager"
3. Click on "HTML Host Manager Help (TODO)" or "Host Manager Help (TODO)"
See error

**Comment by prydonius** [comment]
This looks to be fixed in the latest version - closing.
