### ISSUE TITLE
[rabbitmq] chart not installing when added to already running cluster

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#10609]
### Name and Version

version: 10.1.5

### What steps will reproduce the bug?

1. we have a running cluster with our helm charts. Now we need to add rabbitmq to that.
2. Add rabbitmq chart in our parent chart, chart's directory and add the required dependencies.
3. Assign auth.password to rabbitmq
4. Helm upgrade my parent chart

### What is the expected behavior?

Helm upgrade successful with rabbitmq added in our cluster

### What do you see instead?
```
Error: UPGRADE FAILED: execution error at (benchone-iac-caep/charts/rabbitmq/templates/statefulset.yaml:37:28): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.erlangCookie' must not be empty, please add '--set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE' to the command. To get the current value:

        export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace "benchoneiac" rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
```

**Comment by rafariossaa** [comment]
Hi,
  Yes, when upgrading you need to pass old the credentials.
  For you case, maybe you need to install and the upgrade.

**Comment by pankaj-dahiya** [comment]
I am upgrading my already installed chart which previously didn't have rabbit mq!

**Comment by rafariossaa** [comment]
Hi,
  Helm doesn't know that you are installing rabbitmq for first time in your chart, it only knows that you are using `helm upgrade` so it will trigger all the validations for the upgrade.

**Comment by pankaj-dahiya** [comment]
I guess I am talikng to someone from "Bitnami" .. right ? Every single helm chart present in the entire IT-Helm portfolio, no chart will ever--ever-ever fail in this above condition! Go and try with any of your own bitnami charts and check if this is happening with any of them too. I am using and have used bitnami - MySQL, MongoDB, mongodb-sharded, vault, consul and never had that type of issue . EVER!

**Comment by carrodher** [comment]
When upgrading the bitnami/rabbitmq Helm chart it's necessary to set the `auth.password` and `auth.erlangCookie` parameters when for readiness/liveness probes to work properly.
When you install this chart for the first time, some notes will be displayed providing the credentials you must use in successive upgrades. If you're running a `helm upgrade` without a previous installation, you can provide any value, but `auth.password` and `auth.erlangCookie` need to be set.

In terms of code, this check is done in the _secrets.yaml_ template by calling a function defined in the bitnami/common library Helm chart:
https://github.com/bitnami/charts/blob/a147c28d75ce5436441116459967e604a05960cb/bitnami/rabbitmq/templates/secrets.yaml#L17
https://github.com/bitnami/charts/blob/a147c28d75ce5436441116459967e604a05960cb/bitnami/rabbitmq/templates/secrets.yaml#L20

In the end, you need to add something like the following in your parent Helm chart:
```yaml
rabbitmq:
  auth:
    password: "foo"
    erlangCookie: "bar"
```

Something similar is done in other Helm charts, see
```console
$ ag 'common.secrets.passwords.manage' -l
metallb/templates/speaker/secret.yaml
harbor/templates/core/core-secret.yaml
harbor/templates/core/core-secret-envvars.yaml
harbor/templates/registry/registry-secret.yaml
harbor/templates/jobservice/jobservice-secrets.yaml
jenkins/templates/secrets.yaml
odoo/templates/secrets.yaml
airflow/templates/config/secret.yaml
wordpress/templates/secrets.yaml
rabbitmq/templates/secrets.yaml
mongodb/templates/secrets.yaml
keycloak/templates/secrets.yaml
elasticsearch/templates/secrets.yaml
parse/templates/secrets.yaml
postgresql/templates/secrets.yaml
mariadb/templates/secrets.yaml
grafana-loki/templates/gateway/secret.yaml
mysql/templates/secrets.yaml
common/templates/_secrets.tpl
discourse/templates/secrets-discourse.yaml
redmine/templates/secrets.yaml
```
