### ISSUE TITLE
Unable to specify KAFKA_LOG_MESSAGE_FORMAT_VERSION

### ISSUE THREAD

**Issue by rjanovski** [bitnami/charts#1061]
**Which chart**:

bitnami/kafka

**Description**

the KAFKA_LOG_MESSAGE_FORMAT_VERSION is expose in the docker, but helm does not expose it to the user to config.

This is needed when configuring brokers to work with older clients (while upgrading prod env client by client)

**Steps to reproduce the issue:**

no way to configure e.g. KAFKA_LOG_MESSAGE_FORMAT_VERSION=0.9.0.1

**Comment by javsalgar** [comment]
Hi

Thanks for reporting. I created this PR that solves the issue https://github.com/bitnami/charts/pull/1065

**Comment by rjanovski** [comment]
Thanks @javsalgar !

**Comment by juan131** [comment]
Hi @rjanovski 

We just merged the PR which addresses this issue. Could you please confirm it solved your problem?

**Comment by rjanovski** [comment]
just tried it, works great!
thanks for the quick fix :)
