### ISSUE TITLE
[phpmyadmin] Constant Gateway time-out on a 39M DB import

### ISSUE THREAD

**Issue by icebrian** [bitnami/charts#10662]
### Name and Version

bitnami/phpmyadmin 10.1.8

### What steps will reproduce the bug?

Just deploy chart as normal and add the required custom parameters shown bellow. In my case I am also using an nginx ingress with a self-signed cert.

### Are you using any custom parameters or values?

Added

```
extraEnvVars: #
- name: PHP_UPLOAD_MAX_FILESIZE
  value: "128M"
- name: PHP_MAX_EXECUTION_TIME
  value: "600"
- name: PHP_MAX_INPUT_TIME
  value: "600"
```

Add for the nginx ingress also added:

```
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600s
    nginx.ingress.kubernetes.io/server-snippet: |-
      client_max_body_size 128M;
      client_body_timeout 600s;
      client_header_timeout 600s;
      fastcgi_buffers 8 128K;
      fastcgi_buffer_size 128k;
      fastcgi_read_timeout 600;
      proxy_connect_timeout 600;
      proxy_send_timeout 600;
      proxy_read_timeout 600;
      send_timeout 600;
      keepalive_timeout 240s;
```

### What is the expected behavior?

The 39MB database import should conclude without any error

### What do you see instead?

I get a "504 Gateway Time-out" even thou I have set every setting I could think of to resolve said issue.

**Comment by javsalgar** [comment]
Hi,

Does the issue happen without Ingress?

**Comment by icebrian** [comment]
Hi, 

No, just tested via NodePort and no issue with import. It completes successfully.

**Comment by javsalgar** [comment]
Hi,

So the issue lies on missing nginx parameters. It seems to me that it may be worth checking the nginx ingress devs to see what could be missing in this case.
