### ISSUE TITLE
[ghost] configuration doesn't update after 1st install when `persistence` is enabled

### ISSUE THREAD

**Issue by jalberto** [bitnami/charts#10664]
### Name and Version

bitnami/ghost 19

### What steps will reproduce the bug?

1. set `smtpHost` to `foo`
2. install ghost with persistence enabled (default)
3. set `smtpHost` to `bar`
4. upgrade
5. `smtpHost` must be `bar` in config file, but it is `foo`

### What is the expected behavior?

config file must get new params

### What do you see instead?

config file have old params

**Comment by jalberto** [comment]
Related: https://github.com/bitnami/bitnami-docker-ghost/issues/105

This should be clearly stated in this Chart instructions and the process to reset the config without losing all the content in the volume

**Comment by rafariossaa** [comment]
Hi,
  As explained in that issue, the configuration is only generated on the first run.
  If you want change it you only need to change that in the file and restart the pod. I would say that it is pretty similar to what you need to do if you have a local deployment.

**Comment by jalberto** [comment]
hi @rafariossaa 

It is explained in the issue, but not in the chart itself, so it set wrong expectations.
In other hand, a helm chart that cannot update its own config is kind of defy helm goals.

What if the chart included a script to recreate the config in each boot?

**Comment by rafariossaa** [comment]
> In other hand, a helm chart that cannot update its own config is kind of defy helm goals.

Reconfiguration can be dangerous depending on the kind of asset. For example, if you se config settings that are then later changed during the use, so when restarted you get an unexpected results. Also, what would happen if some pods are restarted and other not, you will end with mixed things. If the chart is also used as a subchart this can lead to other issues where the parent chart is not able to access the subchart, or it is with an expected configuration.

> What if the chart included a script to recreate the config in each boot? 

Some charts, like wordpress, includes a `customPostInitScripts` where an user can provide an script and perform the actions and user may needed that are not possible with the parameters.
Maybe you want to consider sending a PR to add this functionality to ghost chart. We will be glad to review and merge it.

**Comment by jalberto** [comment]
> Reconfiguration can be dangerous depending on the kind of asset.

Not in this case

> Some charts, like wordpress, includes ...

Sorry but I do not understand, this is "not other software" it is Ghost, and the configuration set by helm is not in a DB but in a text file and the only way to change it is manually.

If the direction of this chart is to do not take care of the configuration, maybe remove it completely from the chart and just add instructions to mount a configmap or similar.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by vanthome** [comment]
I also think it should be mentioned in thee docs.

**Comment by JamesHawkinss** [comment]
+1 on this issue, it is expected that changing settings in the Helm values file should update the settings on Ghost automatically. As it stands, the only way to update settings is to manually overwrite the file in the container, which is made even more difficult by the lack of any file editor in the pod.
