### ISSUE TITLE
[bitnami/mongodb] persistence.volumeClaimTemplates.dataSource will not be renderd in standalone deployment

### ISSUE THREAD

**Issue by apo2k7** [bitnami/charts#10684]
### Name and Version

bitnami/mongodb 12.1.19

### What steps will reproduce the bug?

Missing interpretation for persistence.volumeClaimTemplates.dataSource. 

### What is the expected behavior?

If you provide the persistence.volumeClaimTemplates.dataSource object it should be renderd into the pvc object. 

### What do you see instead?

Nothing gets renderd into the pvc.

**Comment by javsalgar** [comment]
Hi,

In this case, the volumeClaimTemplates are to be used in the `StatefulSet` definition. I believe that we should add a `persistence.dataSource` value in this case so it gets rendered in the PVC when using deployments, thoughts?
