### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] RabbitMQ server's logs are written to file instead of stdout

### ISSUE THREAD

**Issue by acidroper** [bitnami/charts#10687]
### Name and Version

bitnami/rabbitmq-cluster-operator 2.6.6

### What steps will reproduce the bug?

1. Deploy bitnami/rabbitmq-cluster-operator with deafult values.
2. Deploy RabbitmqCluster with default settings.

### What is the expected behavior?

RabbitMQ server logs should be written to standart output.

### What do you see instead?

Logs are written to files in container's filesystem.
```
<...>
2022-06-10 10:51:48.793702+00:00 [notice] <0.221.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
<...>
Logs: /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@test-server-0.test-nodes.rabbitmq.log
/opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@test-server-0.test-nodes.rabbitmq_upgrade.log
<stdout>
```

### Additional information

I think it's because setting the environment variable `RABBITMQ_LOGS` was removed from the image `bitnami/rabbitmq`. See https://github.com/bitnami/bitnami-docker-rabbitmq/commit/1433a2ec9ef2191dc5a9d0e7f30d1fcc5b05e740

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Indeed, this may have caused an issue with the container. The thing is that setting that value by default to `-` also causes issues in the helm chart. Maybe the change should go to the RabbitMQ operator itself, so it's the one that sets that environment variable to `-`. Thoughts?
