### ISSUE TITLE
Wordpress styling is broken when accessing Wordpress using Safari on Mac

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/charts#107]
Steps to reproduce:
helm install wordpress
open http://<serviceip>

Page is correctly styled when accessed used Chrome.
When using Safari:
* Page is not styled
* Errors in web console
* Cannot login due to cookies being disabled.

![screen shot 2016-09-01 at 3 11 54 pm](https://cloud.githubusercontent.com/assets/7146644/18186259/b6410766-7056-11e6-96e5-49a3108c6972.png)
![screen shot 2016-09-01 at 3 11 15 pm](https://cloud.githubusercontent.com/assets/7146644/18186256/b63653ac-7056-11e6-9268-f2b2df8b835d.png)
![screen shot 2016-09-01 at 3 11 12 pm](https://cloud.githubusercontent.com/assets/7146644/18186257/b6391e5c-7056-11e6-8308-1e1310c055c3.png)
![screen shot 2016-09-01 at 3 09 32 pm](https://cloud.githubusercontent.com/assets/7146644/18186258/b63c1602-7056-11e6-8ccd-217b96345cb4.png)

**Comment by sameersbn** [comment]
Fixed in https://github.com/bitnami/charts/commit/b993f922a95d31a75a96c7336e0d6234ae7f9fc1

**Comment by prydonius** [comment]
confirmed it's fixed
