### ISSUE TITLE
Enhancement: Please provide options to control the `ETCD_AUTO_COMPACTION_RETENTION`, `ETCD_AUTO_COMPACTION_MODE`

### ISSUE THREAD

**Issue by ozomer** [bitnami/charts#1071]
**Which chart**:

etcd

**Description**

Enhancement: Please provide options to control the `ETCD_AUTO_COMPACTION_RETENTION`, `ETCD_AUTO_COMPACTION_MODE` or configure them with proper default values. I'm relatively new to etcd, but as far as I understand compaction crucial, especially for production systems.
I've noticed that these options are configured in the [configmap.yaml](https://github.com/bitnami/charts/blob/22305221cd11a909fc5ef9f1f67f59b78d6b1d8f/bitnami/etcd/templates/configmap.yaml#L106-L107), but I could not find any documentation (example?) regarding the `useConfigmap` option.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. I am preparing a PR that will improve the configuration parameters of the chart. Stay tuned!

**Comment by javsalgar** [comment]
Hi, 

I created a PR that covers your use case. I added a README section explaining how to use it.
