### ISSUE TITLE
[bitnami/airflow] worker podTemplate's configmap should be rendered using common.tplvalues.render

### ISSUE THREAD

**Issue by nothing5lose** [bitnami/charts#10720]
### Name and Version

bitnami/airflow 12.5.7

### What steps will reproduce the bug?

1. Override worker podTemplate using **.Values.worker.podTemplate**.
2. Worker podTemplate Configmap rendered as literal instead of fill up by template.

### What is the expected behavior?

worker podTemplate's configmap should be rendered using common.tplvalues.render.

should be like 
`{{- include "common.tplvalues.render" (dict "value" .Values.worker.podTemplate "context" $) | nindent 4 }}`

instead of
`{{ .Values.worker.podTemplate | nindent 4 }}`

### What do you see instead?

worker podTemplate's configmap rendered as literal values passed in (template string without filled up with values)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
