### ISSUE TITLE
Connection to LDAP after helm upgrade

### ISSUE THREAD

**Issue by monegim** [bitnami/charts#10725]
### Name and Version

bitnami/harbor 11.0.2

### What steps will reproduce the bug?

1. deploy helm chart
2. add ldap/dockerhub integration over web
3. update helm chart
4. login with ldap not working (invalid credentials)/ pull over harbor from dockerhub not working

### What do you see instead?

LDAP login should work/Pull over harbor from dockerhub is working

### Additional information

In #8889, it is mentioned that this problem has been resolved in version 2.5. However, we need to use the chartmeuseum feature and do not want to upgrade the version(it is 2.3.3 now).

**Comment by javsalgar** [comment]
Hi,

I'm afraid that then you would need to deploy the chartmuseum instance separately from the chart. You could try rendering the chartmuseum deployment yaml from the 2.3.3 version and then add it as part of the `extraDeploy` value in the 2.5 version of the chart.
