### ISSUE TITLE
Pods restarting continously

### ISSUE THREAD

**Issue by tarakaprabhuchinta** [bitnami/charts#10742]
### Name and Version

bitnami/external-dns 6.5.5

### What steps will reproduce the bug?

I have installed external-dns helm chart to update my dns records. I am using Azure dns zone and updating dns using service principal. I have passed "azure.json" file with credentials in helm values. External dns updates my records without any problem. But the external-dns instance pods are continously restarting after checking my dns records.The log values are pasted below. Ideally, I would like a single pod to check my dns records without restarting several times. But, with this chart new pods are recreated continously.

### What do you see instead?
```
time="2022-06-14T13:41:36Z" level=info msg="Instantiating new Kubernetes client"
time="2022-06-14T13:41:36Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2022-06-14T13:41:36Z" level=info msg="Created Kubernetes client https://10.0.0.1:443"
time="2022-06-14T13:41:36Z" level=info msg="Using client_id+client_secret to retrieve access token for Azure API."
time="2022-06-14T13:41:43Z" level=info msg="All records are already up to date"
time="2022-06-14T13:42:00Z" level=info msg="Received SIGTERM. Terminating..."
time="2022-06-14T13:42:00Z" level=info msg="Terminating main controller loop"
```

**Comment by javsalgar** [comment]
Hi,

When you say they are restarting, it is because of the liveness/readiness probes?
