### ISSUE TITLE
please add flink and clickhouse

### ISSUE THREAD

**Issue by Peakchen** [bitnami/charts#10769]
### Name and Version

bitnami

### What is the problem this feature will solve?

rt

### What is the feature you are proposing to solve the problem?

k8s develop

### What alternatives have you considered?

has not any more.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. I will forward this to the team for considering it in the future.

**Comment by carrodher** [comment]
Hi, ClickHouse was added some time ago, [here](https://github.com/bitnami/charts/tree/main/bitnami/clickhouse) you can find it. We are still evaluating Flink
