### ISSUE TITLE
missing tls autogenerated

### ISSUE THREAD

**Issue by marknesterovych** [bitnami/charts#10763]
### Name and Version

bitnami/keycloak-2.9.8

### What steps will reproduce the bug?

When `auth.tls.autoGenerated` is set to true, variables `KEYCLOAK_TLS_KEYSTORE_PASSWORD` and `KEYCLOAK_TLS_TRUSTSTORE_PASSWORD` are not set for container keycloak in statefulset.

I guess https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/statefulset.yaml#L233 should be like:
```
 {{- if or .Values.auth.tls.keystorePassword .Values.auth.existingSecretPerPassword .Values.auth.tls.autoGenerated }}
```

### What is the expected behavior?

Expected to have mentioned variables set with corresponding autogenerated values.

### What do you see instead?

Variables are not set.
Keycoak is failing to start

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by marknesterovych** [comment]
@carrodher I've made the PR. But looks like automatic checks can not identify a module that was updated in PR.

https://github.com/bitnami/charts/pull/10811

**Comment by carrodher** [comment]
Thanks for the PR, we will take a look and provide feedback
