### ISSUE TITLE
[bitnami/prometheus] runAsGroup is not an exposed option for podSecurityContext

### ISSUE THREAD

**Issue by ProNibs** [bitnami/charts#10775]
### Name and Version

bitnami/prometheus latest version

### What is the problem this feature will solve?

Currently, the prometheus chart has runAsUser exposed and depending on the prometheus component some other options.

This enhances the security posture possible for prometheus chart users.

Not related, but super minor thing: Would like consistent helm values for k8s requests+limits on prometheus objects..
The resource requests+limits is exposed differently for Blackbox-exporter; resources.requests and resources.limits are in the values.yaml as opposed to every other component just having resources exposed in the values.yaml and expecting the consumer to manually put it in themselves.

### What is the feature you are proposing to solve the problem?

Would like runAsGroup to be added to all the podSecurityContext sections.

### What alternatives have you considered?

The open-source helm chart collections for prometheus already have this set as a default, so could swap to that.

**Comment by fmulero** [comment]
Hi Andrew. Thanks for your suggestion.

I have look to the chart and I think you can set `podSecurityContext.runAsGroup` in all the components. This value is not in the default values  file but the code allows you to set it. Could you give it a try?
