### ISSUE TITLE
How to monitor PSQL-HA cluster ?

### ISSUE THREAD

**Issue by emoxam** [bitnami/charts#10782]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

Hello
I've installed bitnami/postgresql-ha chart via rancher, how to monitor healt of the PSQl cluster ? Who is master and replica and how's it's health ?
Thanks

### What do you see instead?

Hello
I've installed bitnami/postgresql-ha chart via rancher, how to monitor healt of the PSQl cluster ? Who is master and replica and how's it's health ?
Thanks

**Comment by marcosbc** [comment]
Hi @emoxam, unfortunately I lack experience with Rancher, but since it should be running Kubernetes under the hood, you can check whether the pods passed the health and readiness checks via `kubectl get pods`.

As for which node is the primary, you may need to enter the shell of one of the `repmgr` nodes and follow [these steps](https://repmgr.org/docs/4.0/follow-new-primary.html).

**Comment by emoxam** [comment]
@marcosbc Hi! Thanks for the answer. I think a have some info now.

Run it on nod where PSQL pod works
crictl ps | grep postgresql
crictl exec -it d25 /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show

 ID   | Name                            | Role    | Status    | Upstream                        | Location | Priority | Timeline | Connection string                                               
------+---------------------------------+---------+-----------+---------------------------------+----------+----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | psql-postgresql-ha-postgresql-0 | primary | * running |                                 | default  | 100      | 1        | user=repmgr password=lJyvP5Xlwq host=psql-postgresql-ha-postgresql-0.psql-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | psql-postgresql-ha-postgresql-1 | standby |   running | psql-postgresql-ha-postgresql-0 | default  | 100      | 1        | user=repmgr password=lJyvP5Xlwq host=psql-postgresql-ha-postgresql-1.psql-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1002 | psql-postgresql-ha-postgresql-2 | standby |   running | psql-postgresql-ha-postgresql-0 | default  | 100      | 1        | user=repmgr password=lJyvP5Xlwq host=psql-postgresql-ha-postgresql-2.psql-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

where d25 is a part of container ID

In that output we can see who is master and who is slave at the Role column, and it's statuses.
Replication stat can be viewed by running this DDL at the PGAdmin for example
select * from pg_stat_replication;

Don't know why it's not mentioned in the manual.
