### ISSUE TITLE
400: Bad Request. node [test-elasticsearch-coordinating-0] does not have the [remote_cluster_client] role

### ISSUE THREAD

**Issue by zhangwei900808** [bitnami/charts#10785]
### Name and Version

bitnami/elasticsearch18.2.9 bitnami/kibana10.1.9

### What steps will reproduce the bug?

1、helm install bitnami/elasticsearch
2、helm install bitnami/kibana
3、open kibana and visit 
4、400: Bad Request. node [test-elasticsearch-coordinating-0] does not have the [remote_cluster_client] role

### What do you see instead?

400: Bad Request. node [test-elasticsearch-coordinating-0] does not have the [remote_cluster_client] role

**Comment by javsalgar** [comment]
Hi,

Could you check if the issue happens with kibana chart version 10.1.12?
