### ISSUE TITLE
Metrics sidecar container is missing on keycloak statefulset

### ISSUE THREAD

**Issue by ajammali** [bitnami/charts#10786]
### Name and Version

bitnami/keycloak:9.2.10

### What is the problem this feature will solve?

Metrics sidecar container is missing.

### What is the feature you are proposing to solve the problem?

Add the sidecar container for metrics exporter.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by marknesterovych** [comment]
What sidecar are you talking about ? Metrics should be exposed via keycloak itself.

**Comment by ajammali** [comment]
@marknesterovych since keycloak is not capable of doing so, we'll need to add a sidecar to expose metrics out.
