### ISSUE TITLE
Facing issue while restoring the DB more than 100GB

### ISSUE THREAD

**Issue by raghumg2133** [bitnami/charts#10788]
### Name and Version

bitnami/posgres

### What steps will reproduce the bug?

I have tried to restore the postgrace and i can see data is not getting copied,
need suggestion how we can perform the db restore
I followed below way.

pg_dump -h host1 -U postgrace -W |  psql -U artifactory

I was able to restore only 40 GB, any suggestions please help 

### What do you see instead?

NA

**Comment by javsalgar** [comment]
Hi,

Could you provide more details on the error shown?

**Comment by raghumg2133** [comment]
Hello, 
I can see below errors. 

pg_restore:` [archiver (db)] Error from TOC entry 16731; 1259 567326 INDEX

pg_restore: [archiver (db)] could not execute query: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

**Comment by joancafom** [comment]
Hi @raghumg2133 

> pg_dump -h host1 -U postgrace -W | psql -U artifactory

Using a pipe over such a big data source may not be ideal. In order to discard this is related to that, I recommend you to create a file with the DB data and then use it to restore:

```
$ pg_dump -h host1 -U postgrace -W -f /tmp/dump.sql
$ psql -U artifactory < /tmp/dump.sql
```
