### ISSUE TITLE
Moodle: Cannot connect to database on k8s cluster

### ISSUE THREAD

**Issue by pravin-yipl** [bitnami/charts#10795]
### Name and Version

bitnami/moodle:latest

### What steps will reproduce the bug?

I'm using bitnami/moodle image to build images for my moodle application. When, deploying to kubernetes, with the same host, same username and pasword I can connect to database server which is within the same kubernetes cluster, but I cannot connect to database from moodle.

In my config.php, the connection is done as <service_name>.<namespace>.svc.cluster.local
`$CFG->dbhost    = 'mysql-service.mysql.svc.cluster.local';`
All other application are able to connect this way, but only moodle cannot connect

### What do you see instead?

![image](https://user-images.githubusercontent.com/103093168/174273817-7175af16-1a13-4192-a518-bfa27c8befbd.png)

**Comment by pravin-yipl** [comment]
Issue also in here:
https://community.bitnami.com/t/pods-moodle-cannot-connect-to-mariadb-server-on-kubernetes/106081

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
