### ISSUE TITLE
Ghost RSS Subscribe pointing to different IP then "External IP"

### ISSUE THREAD

**Issue by mykaelnguyen** [bitnami/charts#108]
Description:
When clicking on "Subscribe" in the Menu for Ghost, the RSS feed page that it links to is incorrect.

Steps to Reproduce:
1. Click on "Menu"
2. Click on "Subscribe"
Observe Error

![image](https://cloud.githubusercontent.com/assets/2592371/18187751/247925e2-7061-11e6-9a32-51214e5cec0d.png)
![screen shot 2016-09-01 at 4 33 01 pm](https://cloud.githubusercontent.com/assets/2592371/18187831/ccbc469e-7061-11e6-85f6-fbabcec7cdc1.png)

**Comment by mykaelnguyen** [comment]
Clicking on this link is an issue too:  "User's Blog" -> http://10.12.0.5/ (Instead of the right External IP)

**Comment by mykaelnguyen** [comment]
Another issue after trying to manage the blog:

![image](https://cloud.githubusercontent.com/assets/2592371/18188345/53ed6450-7066-11e6-9abe-100c4b1507ff.png)

**Comment by mykaelnguyen** [comment]
All the default navigation is set to the wrong Host:

![image](https://cloud.githubusercontent.com/assets/2592371/18188866/7e699bc8-706a-11e6-96c2-2ed3c355f3c1.png)

**Comment by sameersbn** [comment]
For the Ghost application function correctly, you should specify the `ghostHost` parameter to specify the FQDN (recommended) or the public IP address of the Ghost service.

Optionally, you can specify the `ghostLoadBalancerIP` parameter to assign a reserved IP address to the Ghost service of the chart. However please note that this feature is only available on a few cloud providers (f.e. GKE).

To reserve a public IP address on GKE:

```bash
$ gcloud compute addresses create ghost-public-ip
```

The reserved IP address can be associated to the Ghost service by specifying it as the value of the `ghostLoadBalancerIP` parameter while installing the chart.

**Comment by sameersbn** [comment]
Hi @mykaelnguyen, were you able to resolve the issue?

**Comment by prydonius** [comment]
Closing this as it has been resolved with the `ghostHost` param.
