### ISSUE TITLE
[bitnami/common]  _affinities

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#10804]
### Name and Version

bitnami/common 1.16.0

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/16569e01802bf3cd358da8a2d63669b0bb7bca31/bitnami/common/templates/_affinities.tpl#L66

this should be `common.names.namespace`

### What do you see instead?

https://github.com/bitnami/charts/blob/16569e01802bf3cd358da8a2d63669b0bb7bca31/bitnami/common/templates/_affinities.tpl#L66

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Would you like to submit a PR with the fix?

**Comment by maxisam** [comment]
well, I would like to but there are just too many hoops for a simple PR, so I will just let you guys do it.

**Comment by aoterolorenzo** [comment]
Hey @maxisam, just to inform that the issue has been addressed on the above mentioned PR (https://github.com/bitnami/charts/pull/11137). Thakns for your report!

**Comment by dosmanak** [comment]
Hello. I struggle with the helmchart inside kustomize. The namespace transformer can't reach this value and change it accordingly.

Here is the question: Why even have the `podAffinityTerm` populated with `namespaces` list with this single value? It seems to me this setup has the same effect as not defined at all.

```
   namespaces	<[]string>
     namespaces specifies a static list of namespace names that the term applies
     to. The term is applied to the union of the namespaces listed in this field
     and the ones selected by namespaceSelector. null or empty namespaces list
     and null namespaceSelector means "this pod's namespace"
```

**Comment by carrodher** [comment]
In order to provide better support so the whole community could benefit from the answers, could you please post your question in a new ticket?
