### ISSUE TITLE
Chart contain contradicting default values

### ISSUE THREAD

**Issue by johnwc** [bitnami/charts#10807]
### Name and Version

bitnami/harbor

### What steps will reproduce the bug?

Install most of any bitnami charts using default values for accessModes and updateStrategy.

### What is the expected behavior?

Be able to be install, and upgrade without PVC attach errors.

### What do you see instead?

Get errors as `Multi-Attach error for volume "..." Volume is already used by pod(s) harbor-...`

### Additional information

The default setting of `ReadWriteOnce` for `accessModes` contradicts the default setting for `updateStrategy.type` being set to `RollingUpdate`.

When changing `updateStrategy.type` to `Recreate` and leaving `accessModes` to `ReadWriteOnce`, upgrades run without error.
When changing `accessModes` to `ReadWriteMany` and leaving `updateStrategy.type` to `RollingUpdate`, upgrades run without error.

**Comment by javsalgar** [comment]
Try with this

```
                    'jobservice.podAffinityPreset=hard',
                    'registry.podAffinityPreset=hard',
                    'chartmuseum.podAffinityPreset=hard',
     
```
