### ISSUE TITLE
Chart docs are missing all available options for parameters

### ISSUE THREAD

**Issue by johnwc** [bitnami/charts#10806]
### Name and Version

bitnami/wordpress

### What steps will reproduce the bug?

Example: Within [wordpress chart docs](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#wordpress-deployment-parameters), there is setting for `updateStrategy.type` with a default value of `RollingUpdate` But, the other options are not listed. There is quite a few parameters in the docs like this.

### What is the expected behavior?

Each parameter that allows different options have all options documented. If it is a kubernetes parameter, then link to kubernetes docs for parameter. Ex: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

### What do you see instead?

Quite a few parameters are not fully documented with all options..

**Comment by carrodher** [comment]
Thanks for reporting this issue. Please note, that this table is generated automatically by [this tool](https://github.com/bitnami-labs/readme-generator-for-helm) using the metadata present in the [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml) for each parameter.
Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by johnwc** [comment]
When I have free time I may, but there is a ton of charts with this issue.
