### ISSUE TITLE
spark master/worker container has no spark logs or jobs execution logs

### ISSUE THREAD

**Issue by chwongeric** [bitnami/charts#10812]
### Name and Version

spark/3.1.2

### What steps will reproduce the bug?

1. in spark master/worker node, inside container there is no logs even submitted spark jobs
```
I have no name!@spark-worker-0:/opt/bitnami/spark$ ls -l
total 176
-rw-r--r-- 1 root root 23235 Mar  3  2021 LICENSE
-rw-r--r-- 1 root root 57677 Mar  3  2021 NOTICE
drwxr-xr-x 3 root root  4096 Mar  3  2021 R
-rw-r--r-- 1 root root  4488 Mar  3  2021 README.md
-rw-r--r-- 1 root root   183 Mar  3  2021 RELEASE
drwxr-xr-x 2 root root  4096 Mar  3  2021 bin
drwxrwxr-x 1 root root  4096 Jun 20 05:42 conf
drwxr-xr-x 5 root root  4096 Mar  3  2021 data
drwxr-xr-x 4 root root  4096 Mar  3  2021 examples
drwxrwxr-x 1 root root 20480 Mar  3  2021 jars
drwxr-xr-x 4 root root  4096 Mar  3  2021 kubernetes
drwxr-xr-x 2 root root  4096 Mar  3  2021 licenses
drwxrwxr-x 1 root root  4096 Jun 20 05:42 logs
drwxr-xr-x 8 root root  4096 Mar  3  2021 python
drwxr-xr-x 2 root root  4096 Mar  3  2021 sbin
drwxrwxr-x 1 root root  4096 Jun 20 05:42 tmp
drwxr-xr-x 4 root root  4096 Mar  3  2021 venv
drwxrwxr-x 2 root root  4096 Apr 16  2021 work
drwxr-xr-x 2 root root  4096 Mar  3  2021 yarn
```
```
I have no name!@spark-worker-0:/opt/bitnami/spark$ ls logs
I have no name!@spark-worker-0:/opt/bitnami/spark$
```

### What is the expected behavior?

please info me where should be log files generated inside the container. Wish to learn how spark bitnami image different from spark node and where can find all logs for debugging.

thanks!

### What do you see instead?

there is no way to find spark logs inside container

**Comment by joancafom** [comment]
Hi @chwongeric 

You can easily retrieve the logs of a pod by using the following command:

```bash
$ kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
cairo-spark-master-0   1/1     Running   0          18m
cairo-spark-worker-0   1/1     Running   0          18m
cairo-spark-worker-1   1/1     Running   0          17m

$ kubectl logs cairo-spark-worker-1
 08:09:08.81
 08:09:08.82 Welcome to the Bitnami spark container
 08:09:08.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 08:09:08.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 08:09:08.82
 08:09:08.83 INFO  ==> ** Starting Spark setup **
realpath: /bitnami/spark/conf: No such file or directory
 08:09:08.85 INFO  ==> Generating Spark configuration file...
 08:09:08.86 INFO  ==> ** Spark setup finished! **

 08:09:08.88 INFO  ==> ** Starting Spark in worker mode **
...
```

**Comment by chwongeric** [comment]
@joancafom  thanks a lot for your reply.   Before I submit this support ticket, I already looked at all container and k8s logs with no luck.   what I need is logs of spark connections and spark jobs received by master and processing, but could not find any from bitnami images.

my bitnami spark master and worker nodes are all working fine without any problem.  however, there is no log info for submitted jobs as all seems silently dropped.   thank you very much for help!


` 05:40:20.92 
 05:40:20.92 Welcome to the Bitnami spark container
 05:40:20.92 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-spark
 05:40:20.92 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-spark/issues
 05:40:20.93 
 05:40:20.94 INFO  ==> ** Starting Spark setup **
 05:40:20.96 INFO  ==> Generating Spark configuration file...
 05:40:20.97 INFO  ==> Enabling metrics...

 05:40:20.99 INFO  ==> ** Spark setup finished! **
 05:40:21.01 INFO  ==> ** Starting Spark in master mode **
starting org.apache.spark.deploy.master.Master, logging to /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.master.Master-1-spark-master-0.out
Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.master.Master --host 0.0.0.0 --port 7077 --webui-port 8080
========================================
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/06/20 05:40:22 INFO Master: Started daemon with process name: 43@spark-master-0
22/06/20 05:40:22 INFO SignalUtils: Registering signal handler for TERM
22/06/20 05:40:22 INFO SignalUtils: Registering signal handler for HUP
22/06/20 05:40:22 INFO SignalUtils: Registering signal handler for INT
22/06/20 05:40:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/06/20 05:40:23 INFO SecurityManager: Changing view acls to: spark
22/06/20 05:40:23 INFO SecurityManager: Changing modify acls to: spark
22/06/20 05:40:23 INFO SecurityManager: Changing view acls groups to: 
22/06/20 05:40:23 INFO SecurityManager: Changing modify acls groups to: 
22/06/20 05:40:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
22/06/20 05:40:23 INFO Utils: Successfully started service 'sparkMaster' on port 7077.
22/06/20 05:40:23 INFO Master: Starting Spark master at spark://0.0.0.0:7077
22/06/20 05:40:23 INFO Master: Running Spark version 3.1.1
22/06/20 05:40:23 INFO Utils: Successfully started service 'MasterUI' on port 8080.
22/06/20 05:40:24 INFO MasterWebUI: Bound MasterWebUI to 0.0.0.0, and started at http://spark-master-0.spark-headless.analytics.svc.cluster.local:8080
22/06/20 05:40:24 INFO Master: I have been elected leader! New state: ALIVE
22/06/20 05:41:13 INFO Master: Registering worker 100.96.98.86:39169 with 1 cores, 14.5 GiB RAM
22/06/20 05:41:37 INFO Master: Registering worker 100.96.9.23:43217 with 1 cores, 14.5 GiB RAM
22/06/20 05:42:47 INFO Master: Registering worker 100.96.99.204:34263 with 1 cores, 14.5 GiB RAM
22/06/20 05:54:30 INFO Master: 127.0.0.6:45007 got disassociated, removing it.
22/06/20 05:54:30 INFO Master: 100.96.98.86:39169 got disassociated, removing it.
22/06/20 05:54:30 INFO Master: Removing worker worker-20220620054027-100.96.98.86-39169 on 100.96.98.86:39169
22/06/20 05:54:30 INFO Master: Telling app of lost worker: worker-20220620054027-100.96.98.86-39169
22/06/20 05:54:31 INFO Master: Registering worker 100.96.38.24:42111 with 1 cores, 14.5 GiB RAM
`

**Comment by joancafom** [comment]
My pleasure @chwongeric !

I reckon this is the default logging verbosity level and behavior for Spark itself. However, Spark relies on Log4J for logging and hence settings are configurable 😁 (this is not something directly related to the chart, but the application)

According to [their official configuration reference](https://spark.apache.org/docs/latest/configuration.html#configuring-logging), if you need to customize what gets logged, where it is stored (if desired) and more options, you can configure all of these in by adding a `log4j2.properties` file to `/opt/bitnami/spark/conf/`.

**Comment by chwongeric** [comment]
Thank you @joancafom .  However, I am running this chart with bitnami spark image.  How can I even modify container adding `log4j2.properties` file to `/opt/bitnami/spark/conf/ `. inside container?

**Comment by chwongeric** [comment]
@joancafom    thank you very much for reply.   I do have the log4j property inside spark container:

`
I have no name!@spark-master-0:/opt/bitnami/spark$ ls -l /opt/bitnami/spark/conf/
total 44
-rw-rw-r-- 1 root root 1105 Mar  3  2021 fairscheduler.xml.template
-rw-rw-r-- 1 root root 2023 Mar  3  2021 log4j.properties.template
-rw-r--r-- 1 root 1337  548 Jul 16 23:13 log4j2.properties
-rw-rw-r-- 1 root root 9141 Mar  3  2021 metrics.properties.template
-rw-rw-r-- 1 root root 1292 Mar  3  2021 spark-defaults.conf
-rw-r--r-- 1 1001 root   53 Jul 16 23:13 spark-env.sh
-rwxrwxr-x 1 root root 4428 Mar  3  2021 spark-env.sh.template
-rw-rw-r-- 1 root root  865 Mar  3  2021 workers.template
I have no name!@spark-master-0:/opt/bitnami/spark$ cat /opt/bitnami/spark/conf/log4j2.properties
# Extra logging related to initialization of Log4j
# Set to debug or trace if log4j initialization is failing
status = warn
# Name of the configuration
name = ConsoleLogConfigDemo

# Console appender configuration
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Root logger level
rootLogger.level = debug
# Root logger referring to console appender
rootLogger.appenderRef.stdout.ref = consoleLogger
`
However, still has no logs inside spark-master or spark-worker pod, anything I can "force" bitnami spark container to generate logs?  should all spark logs supposed to be inside 

> /opt/bitnami/spark/logs

`
I have no name!@spark-master-0:/opt/bitnami/spark$ ls -l logs/
total 0
`

Thanks a lot for further help!

**Comment by joancafom** [comment]
Hi again @chwongeric 

>However, still has no logs inside spark-master or spark-worker pod, anything I can "force" bitnami spark container to generate logs? should all spark logs supposed to be inside

Well, the settings you have specified in your `log4j2.properties` do not seem to enable logging to a file, but rather to the console. You will need to specify the correct settings.  

For instance, these are some sample ones I found on the internet (please, refer to the application guide for further/exact instructions):

```
log4j.rootCategory=INFO,FILE
log4j.appender.FILE=org.apache.log4j.FileAppender
log4j.appender.FILE.File=/opt/bitnami/spark/logs/bitnami.log
log4j.appender.FILE.MaxFileSize=10MB
log4j.appender.FILE.MaxBackupIndex=10
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L – %m%n
```

You will also need to specify this extra environment variable, apparently:

```
SPARK_DAEMON_JAVA_OPTS=-Dlog4j.configuration=file:/opt/bitnami/spark/conf/log4j2.properties
```

That should make it!

**Comment by chwongeric** [comment]
@joancafom thanks a lot!  However, I still don't see any logs, not sure if there is anyway or pointers I can debug further?  thank you

**Comment by chwongeric** [comment]
@joancafom   the problem is how to customize 

> log4j2.properties

looks like after doing those above, the container still not "customize" the conf/log4j2.properties

> $ cat /opt/bitnami/spark/conf/log4j2.properties
# Extra logging related to initialization of Log4j
# Set to debug or trace if log4j initialization is failing
status = warn
# Name of the configuration
name = ConsoleLogConfigDemo

# Console appender configuration
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Root logger level
rootLogger.level = debug
# Root logger referring to console appender
rootLogger.appenderRef.stdout.ref = consoleLogger

**Comment by GergelyMolnar** [comment]
I installed Binami/Spark with Helm for a local dev env, so this might not be applicable directly to all. 
Yet some might figure out how to do this by reading through it.

1. create a ConfigMap with your log4j2.properties YAML file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-logging-config
  namespace: spark
data:
  log4j2.properties: |
    # Logging configuration
    rootLogger.level = info
    rootLogger.appenderRef.stdout.ref = console
    appender.console.type = Console
    appender.console.name = console
    appender.console.target = SYSTEM_ERR
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex
```

2. Apply the ConfigMap to your cluster
`kubectl apply -f spark-logging-config.yaml`


3. Modify the Helm values file (usually something like `values.yaml`)
```
master:
  extraVolumes:
    - name: log-config
      configMap:
        name: spark-logging-config
  extraVolumeMounts:
    - name: log-config
      mountPath: /opt/bitnami/spark/conf/log4j2.properties
      subPath: log4j2.properties

worker:
  extraVolumes:
    - name: log-config
      configMap:
        name: spark-logging-config
  extraVolumeMounts:
    - name: log-config
      mountPath: /opt/bitnami/spark/conf/log4j2.properties
      subPath: log4j2.properties
```

You can export the current values with:
`helm get values <spark deployment name>  > spark-values.yaml`

Where the <spark deployment name> is the name you see in the output of 
`helm list`


4. Upgrade the Helm Release
`helm upgrade <release-name> bitnami/spark -f values.yaml`

Note: 
TBH these logs won't be much help if you are looking to debug errors and other issues.
In that case, you are probably looking for the `/opt/bitnami/spark/work` content on the pods.
That dir contains the driver and app logs STDOUT and STDERR logs.

You can have quick peek into them:
```
kubectl exec -it <spark pod name>  -- ls -l /opt/bitnami/spark/work/
# and 
kubectl exec -it <spark pod name>  -- cat /opt/bitnami/spark/work/<path to the file you want to see>
```
The same applies to the `/opt/bitnami/spark/logs/` dir.


you can get the pod names with
`kubectl get pods -n <namespace>`
