### ISSUE TITLE
How to add extensions to postgresql-ha 

### ISSUE THREAD

**Issue by dnsisme** [bitnami/charts#10814]
### Name and Version

postgresql-ha-12.6.0-v1.2.1.24

### What is the problem this feature will solve?

How to add the following extensions to Postgresql-ha managerd by chart under helm deployment mode？
plpgsql
timescaledb
pgcrypto

### What is the feature you are proposing to solve the problem?

i have an idea: Download plug-ins in dockerfile to implement the installation of dependent plug-ins

However, the specific implementation details are not clear. Is there a directly available solution

What is the recommended solution?

### What alternatives have you considered?

dockerfile
images

**Comment by marcosbc** [comment]
Hi @dnsisme, to do that you would need to extend the Dockerfile of the `bitnami/postgresql-repmgr` container image to follow [these steps](https://www.postgresql.org/docs/current/extend-pgxs.html) for each of the extensions, keeping in mind that the installation directory is `/opt/bitnami/postgresql`. You will also need to modify the chart's parameters to point to the newly built image.

**Comment by nkreiger** [comment]
@marcosbc I'm trying to add the `wal2json` extension, per your comments above.

```
FROM bitnami/postgresql-repmgr:15.2.0-debian-11-r0 as base

COPY wal2json.control /opt/bitnami/postgresql/share/extension/wal2json.control

USER root

RUN apt-get update
RUN apt-get install -y make build-essential

ADD "https://github.com/eulerto/wal2json/archive/refs/tags/wal2json_2_5.tar.gz" \
    /tmp/wal2json.tar.gz
RUN tar -xvf /tmp/wal2json.tar.gz -C /tmp --one-top-level --strip-components 1 && \
    rm -rf /tmp/wal2json.tar.gz

WORKDIR /tmp/wal2json

RUN make -j$(nproc)

COPY wal2json.so /opt/bitnami/postgresql/lib/wal2json.so

EXPOSE 5432
```

Keeps throwing this error:

```
postgresql-repmgr 20:05:49.43 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2023-03-03 20:05:49.452 GMT [157] FATAL:  could not load library "/opt/bitnami/postgresql/lib/wal2json.so": /opt/bitnami/postgresql/lib/wal2json.so: invalid ELF header
```

Any chance you have an example file, or better way to do this?
