### ISSUE TITLE
[Bitnami-Mysql] Connection string to connect to mysql replicated cluster

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#10845]
### Name and Version

bitnami/mysql -- version: 9.1.7

### What steps will reproduce the bug?

helm install my-release bitnami/mysql

### Are you using any custom parameters or values?

architecture : replication

### What is the expected behavior?

There should be an headless service to connect to MySQL podsa

### What do you see instead?

There are two headless services, one for primary and another one for secondary.
When my Java application needs to connect to MySQL for its read/write operations, I can only give that either primary or secondary service (I am giving it primary). Due to this, all the load is on primary and nothing on secondary!

### Additional information

For MongoDB we have this: https://www.mongodb.com/docs/manual/reference/connection-string/#dns-seed-list-connection-format

With SRV records, the MongoDB client can connect with the respective pods. Is there anything similar for MySQL? And how can that be achieved by this chart?

**Comment by pankaj-dahiya** [comment]
I don't think any application provides that functionality provides a different MySQL URI for reading and writing! Can you share an example, please?

**Comment by pankaj-dahiya** [comment]
I found this : https://dev.mysql.com/doc/refman/8.0/en/connecting-using-dns-srv.html#:~:text=MySQL%20supports%20the%20use%20of,host%20by%20the%20DNS%20administrator.

So mysql also supports "srv" but bitnami-mysql headless service isn't supporting this!

**Comment by javsalgar** [comment]
Hi,

I'm not an expert on this, but I've seen connectors like this, where it seems you specify the primary and the secondary nodes

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-source-replica-replication-connection.html

Would this work for your case?

**Comment by pankaj-dahiya** [comment]
Hi @javsalgar thanks for the reply, but there is a flaw in this particular way of connecting to MySQL via the method stated by you. 
The flaw is that we need to update the connection string every time when we are increasing or decreasing the number of MySQL replica sets!!

I want to connect to MySQL with srv records
https://dev.mysql.com/doc/refman/8.0/en/connecting-using-dns-srv.html
via this, there is no need to specify any primary/secondar/nodes , nothing. Just a service URL will work.

(Just like in bitnami/mongodb - replicates mongo, we can use headless service for srv records which will connect to all MongoDB instances and our MongoDB client will itself create list of all mongo instances)

**Comment by javsalgar** [comment]
Hi,

So, what you mention is that there should be a headless service for all of the nodes. Right now, as a workaround, you could use the `extraDeploy` value and add the headless service you are currently missing. Did you try that?
