### ISSUE TITLE
Redirect to HTTPS with Irregular Port

### ISSUE THREAD

**Issue by metro2000** [bitnami/charts#10844]
### Name and Version

bitnami/redmine 5.0.0-1

### What steps will reproduce the bug?

I try to use ...

HTTP : 82
HTTPS : 446

And I want to redirect all HTTP traffics to HTTPS.

### What do you see instead?

![2022-06-22 094348](https://user-images.githubusercontent.com/107968129/174920693-ac09daf6-4744-4836-991e-ee10e2aad853.png)
![2022-06-22 094240](https://user-images.githubusercontent.com/107968129/174920702-c8ba7e36-ab18-464d-a44d-5123424d3f9b.png)
![2022-06-22 094308](https://user-images.githubusercontent.com/107968129/174920705-34a82c4d-f86c-41ab-a7a8-a80c844ad912.png)

But I see an error when I try to connect with HTTP.

How can i resolve this problem?

**Comment by metro2000** [comment]
I cannot understand why back_url called HTTP, not HTTPS.

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
