### ISSUE TITLE
[bitnami/mongodb] readiness-probe uses deprecated `db.isMaster()` call instead of `db.hello()`

### ISSUE THREAD

**Issue by roddicks** [bitnami/charts#10855]
### Name and Version

bitnami/mongodb 12.1.19 (all versions w/ MongoDB 5)

### What steps will reproduce the bug?

1. Using `bitnami/mongodb` Helm Chart.
_any version that includes the MongoDB 5 major version will be affected_
2. Ensure readiness-probe is enabled.
3. Deploy MongoDB.

**to verify:**
1. Open shell session on machine where MongoDB is running.
2. Run `top` and press `C` to see full commands.

### What is the expected behavior?

When MongoDB 5.x is deployed, the readiness probe should use `db.hello()`.

### What do you see instead?

The readiness probe is using `db.isMaster()`.
![readiness probe running ismaster](https://user-images.githubusercontent.com/8923618/175100630-ba6984c8-05c0-46f3-af9c-84998a3c8ecd.png)

### Additional information

The readiness probe script is defined in [mongodb/templates/common-scripts-cm.yaml](https://github.com/bitnami/charts/blob/9e2d3cc39d1f4bf5b4c930af47822eecd789f178/bitnami/mongodb/templates/common-scripts-cm.yaml) (link is to the file as of `12.1.20`). 
```
  readiness-probe.sh: |
    #!/bin/bash

    -snip-

    if [[ "$VERSION_MAJOR" -ge 5 ]] || [[ "$VERSION_MAJOR" -ge 4 ]] && [[ "$VERSION_MINOR" -ge 4 ]] && [[ "$VERSION_PATCH" -ge 2 ]]; then
        mongosh $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
    else
        mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.isMaster().ismaster || db.isMaster().secondary' | grep -q 'true'
    fi
```
The condition for this `if` statement will evaluate to `false` for any version where `VERSION_MINOR < 4` or `VERSION_PATCH < 2` (such as `5.0.9`).

**Comment by javsalgar** [comment]
Thank you so much for reporting! I created a task to fix it. We will update the ticket as soon as there are news.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by roddicks** [comment]
> Would you like to contribute by creating a PR to solve the issue? 

Sure thing, thanks 😄

**Comment by roddicks** [comment]
PR is open [here](https://github.com/bitnami/charts/pull/10865).

**Comment by roddicks** [comment]
I pulled the latest helm chart and can verify the change. 
![verify](https://user-images.githubusercontent.com/8923618/176287342-17b2bd63-8cdc-4c71-a8b5-fec30c796ca3.png)

**Comment by carrodher** [comment]
Glad to see the issue solved, don't hesitate to reopen it if needed
