### ISSUE TITLE
[bitnami/mongodb-sharded] extraEnvVarsSecret for mongos maps as configmap

### ISSUE THREAD

**Issue by artur-bolt** [bitnami/charts#10856]
### Name and Version

bitnami/mongodb-sharded 5.0.12

### What steps will reproduce the bug?

1. Set mongos.extraEnvVarsSecret
2. Run helm install
3. extraEnvVarsSecret values is mapped as configMap, not secret

### Are you using any custom parameters or values?

`
mongos:
  extraEnvVarsSecret: secret-mongo
`

### What is the expected behavior?

Secret should be mounted as secret

### What do you see instead?

Error stating that secret is trying to be mounted as configMap

### Additional information

Instead of this config in templates/mongos/mongos-dep-sts.yaml:

`
            {{- if .Values.mongos.extraEnvVarsSecret }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.mongos.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
`

Should be this:

`
            {{- if .Values.mongos.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.mongos.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
`

**Comment by javsalgar** [comment]
Thank you so much for reporting! I will create a task for the engineering team. As soon as there are news, we will let you know.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by artur-bolt** [comment]
Sure, added PR for this issue, and #10847

**Comment by carrodher** [comment]
Thanks! We will review it and provide feedback
