### ISSUE TITLE
RFE: Allow Apache vhostsConfigMap to reference non-default namespace

### ISSUE THREAD

**Issue by FGasper** [bitnami/charts#10864]
### Name and Version

bitnami/apache 2.4.54

### What is the problem this feature will solve?

Right now if you want all of the configmaps & secrets given to a release to live inside a single namespace, this doesn’t seem possible with bitnami/apache since the config-map settings all seem to presume the default namespace.

### What is the feature you are proposing to solve the problem?

Add a `configMapNamespace` setting that will indicate which namespace to consult for ConfigMaps referenced in the variables given to `helm install`.

### What alternatives have you considered?

Forking the charts project & using that instead … but of course it would be nice to use upstream directly.

**Comment by migruiz4** [comment]
Hi @FGasper,

Thanks for your feature request. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
