### ISSUE TITLE
Add a JSON schema for the Zookeeper Helm Chart

### ISSUE THREAD

**Issue by bilbof** [bitnami/charts#10863]
### Name and Version

bitnami/zookeeper 10.0.0

### What is the problem this feature will solve?

It would enable us to validate the values we provide to the Zookeeper chart

### What is the feature you are proposing to solve the problem?

Add values.schema.json to the Zookeeper chart.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
