### ISSUE TITLE
phpmyadmin: cert-manager flag deprecated but needed

### ISSUE THREAD

**Issue by grieshaber** [bitnami/charts#10867]
### Name and Version

bitnami/phpmyadmin 10.1.9

### What steps will reproduce the bug?

Install phpmyadmin in v10.1.9 with tls enabled and cluster-issuer annotation on the ingress ressource. Skip `cert-manager` Flag, as it is marked as deprecated.
See invalid certificate delivered instead of cert-manager generated one.

### Are you using any custom parameters or values?

ingress:
  enabled: true

  hostname: pma.example.com

  annotations:
    cert-manager.io/cluster-issuer: prod-cluster-issuer

  tls: true

### What is the expected behavior?

Valid, cert-manager generated Certificate will be delivered and managed in a secret called pma.example.com-tls.

### What do you see instead?

Invalid, self signed certifcate is delivered.

### Additional information

https://github.com/bitnami/charts/blob/master/bitnami/phpmyadmin/templates/tls-secrets.yaml#L22 still uses the cert-manager flag to decide, whether the self signed cert should be created and used.
As the flag is deprecated, it should at least exist a new check for the new, alternative way using annotations.

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/phpmyadmin#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by grieshaber** [comment]
I'll try to find time for an MR this week.

**Comment by rafariossaa** [comment]
That would be great, thanks !
