### ISSUE TITLE
Ability to use redis without password

### ISSUE THREAD

**Issue by myl82** [bitnami/charts#10873]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

In  bitnami/redis version 10.9 had ability to use it without password with  "usePassword": false

Unfortunately, the earliest version I've got now is:
```
NAME            CHART VERSION   APP VERSION     DESCRIPTION
bitnami/redis   15.7.0          6.2.6           Open source, advanced key-value store. It is of...
```
Without feature above in it.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Connect to redis without password

### What do you see instead?

wrong redis password in app log

### Additional information

We use bitnami/redis in our chart like dependency component
Please, consider the  possibility to get it back.
This quite useful for test environments. Not need to do some additional settings.

**Comment by alemorcuq** [comment]
Please, check the `auth.enabled` parameter: https://github.com/bitnami/charts/tree/master/bitnami/redis#redis-common-configuration-parameters
