### ISSUE TITLE
Before starting kafka container we need to add a sleep or wait till zookeeper is ready

### ISSUE THREAD

**Issue by lewiswilliam** [bitnami/charts#10872]
### Name and Version

bitname/kafka

### What steps will reproduce the bug?

Before starting kafka container we need to add a sleep or wait till zookeeper is ready in order to handle the following:

https://github.com/wurstmeister/kafka-docker/issues/389

How do we do this with bitnami kafka container?

### What do you see instead?

Not able to start kafka service

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Kafka container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
