### ISSUE TITLE
Cassandra cross cluster datacenters

### ISSUE THREAD

**Issue by fabry00** [bitnami/charts#10879]
### Name and Version

bitnami/cassandra:latest

### What steps will reproduce the bug?

We have deployed cassandra helm chart in 2 Openshift clusters.
The question is: How can we configure the 2 cassandra data centers to communicate each other and synchronize the data?

We tried to export the service `myrelease-cassandra-headless` port 9042/TCP (cql) using an Openshift Route.
Then we added the route dns in cluster.extraSeed but reading the logs it seems that the cassandra datacenter tries to connect to the extraSeed using the port 9042, but all the Openshift routes are exposed to the port 443.

If I try to set the extraSeed with dns:port then I get an error: host could not be resolved

Basically we would like to replicate a similar architecture that you can see in these 2 links:

- https://docs.k8ssandra.io/components/k8ssandra-operator/
- https://itnext.io/managing-a-multi-site-cassandra-cluster-on-multiple-kubernetes-with-casskop-multicasskop-cf407c297701

but without using the operator and with only 2 Openshift clusters

Is it possible? How can we achieve that?

Thanks

### Are you using any custom parameters or values?

    cluster:
       extraSeeds: [my-other-openshift-cluster-route-dns-headless-service-cql]
    tls:
       internodeEncryption: all
       clientEncryption: true
       autoGenerated: true

### What is the expected behavior?

The 2 cassandra clusters should be able to comunicate

### What do you see instead?

if I specify the port 443 in extraSeeds:

    cluster:
       extraSeeds: [my-other-openshift-cluster-route-dns-headless-service-cql:443]

I get an error: host  my-other-openshift-cluster-route-dns-headless-service-cql:443 could not be resolved

if I do not specify any port in extraSeeds, the host is resolved but cassandra is trying to connect to the port 9042, but the Openshift route in the other cluster is listening on port 443

     cluster:
        extraSeeds: [my-other-openshift-cluster-route-dns-headless-service-cql]

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
