### ISSUE TITLE
[bitnami/minio] Possibility to create a PV selector for PVC

### ISSUE THREAD

**Issue by kashapovd** [bitnami/charts#10887]
### Name and Version

bitnami/minio

### What is the problem this feature will solve?

This feature will solve the problem of creating PVCs in storage classes that cannot provision PVs automatically (e.g. local-storage class). 

### What is the feature you are proposing to solve the problem?

I suggest to add parameter "persistent.selector" to values and add following lines to https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/pvc.yaml:
```
{{- if .Values.persistence.selector }}
selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.selector "context" $) | nindent 4 }}
{{- end -}}
```

### What alternatives have you considered?

I checked using "persistent.existingClaim" variable, but it cannot be used with multiple PVs, so I cannot deploy multiple node statefulset.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by kashapovd** [comment]
Yeah! I will create a PR soon

**Comment by carrodher** [comment]
Thanks! We will review it and provide feedback
