### ISSUE TITLE
How to setmin.insync.replicas

### ISSUE THREAD

**Issue by hyt05** [bitnami/charts#10896]
### Name and Version

bitnami/kafka 18.0.0

### What is the problem this feature will solve?

This parameter cannot be set in bitnami kafka. In extreme cases, the topic will lose data

### What is the feature you are proposing to solve the problem?

Improve topics high availability

### What alternatives have you considered?

https://github.com/bitnami/charts/issues/8638#issue-1100194767

minInsyncReplicas: 1

extraEnvVars:
  - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
    value: "1"

**Comment by javsalgar** [comment]
Hi,

Just to confirm, did any of the alternatives mentioned here work as a workaround?

**Comment by hyt05** [comment]
> Hi,
> 
> Just to confirm, did any of the alternatives mentioned here work as a workaround?

Yes, as a workaround, but this functionality is currently missing

**Comment by hyt05** [comment]
> Would you like to submit a PR adding the value? This value would configure the `KAFKA_CFG_MIN_INSYNC_REPLICAS` variable

To be honest, I don't know how to develop code. I see that there are good PRs, but they are not accepted for some reason. The min.insync.replicas parameter should be very necessary in kafka production.

**Comment by javsalgar** [comment]
Hi!

Ok, let me create an internal task to address it.

**Comment by javsalgar** [comment]
Hi,

Looking at the code, it seems that the value should have been set

```
    for var in "${!KAFKA_CFG_@}"; do
        key="$(echo "$var" | sed -e 's/^KAFKA_CFG_//g' -e 's/_/\./g' | tr '[:upper:]' '[:lower:]')"

        # Exception for the camel case in this environment variable
        [[ "$var" == "KAFKA_CFG_ZOOKEEPER_CLIENTCNXNSOCKET" ]] && key="zookeeper.clientCnxnSocket"

        # Apply exception regexps
        for regex in "${exception_regexps[@]}"; do
            key="$(echo "$key" | sed "$regex")"
        done

        value="${!var}"
        kafka_server_conf_set "$key" "$value"
    done

```

Could you double check the contents of the kafka.conf file?

**Comment by hyt05** [comment]
> Reference

I successfully use that environment variable to set

**Comment by hyt05** [comment]
extraEnvVars:
  - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
    value: "3"

**Comment by hyt05** [comment]
> Hi,
> 
> Looking at the code, it seems that the value should have been set
> 
> ```
>     for var in "${!KAFKA_CFG_@}"; do
>         key="$(echo "$var" | sed -e 's/^KAFKA_CFG_//g' -e 's/_/\./g' | tr '[:upper:]' '[:lower:]')"
> 
>         # Exception for the camel case in this environment variable
>         [[ "$var" == "KAFKA_CFG_ZOOKEEPER_CLIENTCNXNSOCKET" ]] && key="zookeeper.clientCnxnSocket"
> 
>         # Apply exception regexps
>         for regex in "${exception_regexps[@]}"; do
>             key="$(echo "$key" | sed "$regex")"
>         done
> 
>         value="${!var}"
>         kafka_server_conf_set "$key" "$value"
>     done
> ```
> 
> Could you double check the contents of the kafka.conf file?

thank you very much
