### ISSUE TITLE
RabbitMQ wrong Erlang version?

### ISSUE THREAD

**Issue by joaquinjsb** [bitnami/charts#10898]
### Name and Version

Bitnami/erlang:latest

### What steps will reproduce the bug?

1. run rabbitMQ on AArch64 (in my case apple silicon)
2. when container is spinned up, the liveness and probeness will fail

### Are you using any custom parameters or values?

no

### What is the expected behavior?

the check to pass properly and the service to startup properly

### What do you see instead?

segmentation fault errors.

### Additional information

the same problem also happens on
/opt/bitnami/scripts/libos.sh

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
