### ISSUE TITLE
[bitnami/minio] add filesystem group change policy for large minio deployments

### ISSUE THREAD

**Issue by maartenjanvangool** [bitnami/charts#10919]
### Name and Version

bitnami/minio

### What steps will reproduce the bug?

See https://github.com/minio/minio/pull/14528. I'm encountering exactly this issue with the bitnami chart. I'm not sure there is another workaround (I could not find it), but otherwise, being able to set the fsGroupChangePolicy would be neat!

I'm not sure if [this](https://github.com/bitnami/charts/tree/master/bitnami/minio#adjust-permissions-of-persistent-volume-mountpoint) init container setting would fix the issue? If so, perhaps some more documentation would be neat? I am kind of hesitant to try it out until I'm sure, it right now takes up to 3 hours to start minio in our environment.... 

### What do you see instead?

Mounting a large disk takes an excessive amount of time.

**Comment by migruiz4** [comment]
Hi @maartenjanvangool,

The values `podSecurityContext` and `containerSecurityContext` are evaluated as a YAML object, meaning that you can add additional subfields without having to change the chart logic.
```
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
```

See:
```
$ helm install my-release bitnami/minio --set podSecurityContext.fsGroupChangePolicy=onRootMismatch --dry-run
...          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: onRootMismatch
      containers:
        - name: minio
          image: docker.io/bitnami/minio:2022.6.20-debian-11-r0
          imagePullPolicy: "IfNotPresent"
...
```

**Comment by maartenjanvangool** [comment]
Hi @migruiz4. Thanks for your response. I'm going to try this out. 

I'm leaving the issue open, since I still think this should be documented... I am guessing I would not be the only one running into this.
