### ISSUE TITLE
[bitnami/mongodb-replicaset]

### ISSUE THREAD

**Issue by Dssssds** [bitnami/charts#10926]
### Name and Version

bitnami/mongodb 3.6.0

### What steps will reproduce the bug?

Hello, everyone. I want to ask you how to access the mongodb replica set installed by helm through the public network.

### Are you using any custom parameters or values?

helm command is as follows:

```
helm install mongodb-set -n ai-mongodb bitnami/mongodb --set architecture="replicaset",auth.rootUser="aigamify",auth.rootPassword="aigamify_666",persistence.storageClass="ai-mongodb-nas",replicaCount=2,externalAccess.enabled=true,externalAccess.service.type="LoadBalancer",externalAccess.service.port=27017,externalAccess.service.externalTrafficPolicy="Cluster",externalAccess.autoDiscovery.enabled=true,serviceAccount.create=true,rbac.create=true
```
After that, the external network cannot be connected. Check it out rs.conf()
```
"members" : [
		{
			"_id" : 0,
			"host" : "mongodb-set-arbiter-0.mongodb-set-headless.ai-mongodb.svc.cluster.local:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 5,
			"tags" : {
				
			},
			"secondaryDelaySecs" : 0,
			"votes" : 1
		},
		{
			"_id" : 1,
			"host" : "mongodb-set-arbiter-0.mongodb-set-arbiter-headless.ai-mongodb.svc.cluster.local:27017",
			"arbiterOnly" : true,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 0,
			"tags" : {
				
			},
			"secondaryDelaySecs" : 0,
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "mongodb-set-arbiter-1.mongodb-set-arbiter-headless.ai-mongodb.svc.cluster.local:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"secondaryDelaySecs" : 0,
			"votes" : 1
		}
	],
```

### What is the expected behavior?

Do I need to modify the rs.conf() host address?

I don't know if you can understand what I mean. (I am Chinese and my English is not very good. Sorry)

### What do you see instead?

Or how to use this place.

![image](https://user-images.githubusercontent.com/17268259/176472829-5d90baf0-3b71-4e0a-b97e-1c2e63044962.png)

**Comment by javsalgar** [comment]
Hi,

In principle, using externalAccess should create one public service per pod. Could you add more details about the Kubernetes cluster you are using?

**Comment by Dssssds** [comment]
Thank you. The problem has been solved thank you

**Comment by javsalgar** [comment]
Thanks for letting us know!
