### ISSUE TITLE
Set PVC on Bitnami/mongodb in replicaset mode

### ISSUE THREAD

**Issue by erniker** [bitnami/charts#10928]
### Name and Version

bitnami/mongodb 12.1.20

### What steps will reproduce the bug?

I started with kubernetes few months ago, and need some help. I am trying to deploy the helm bitnami/monogdb in replicaset mode, but seting the pvc for tell to mongo where I want it puts the data (in a azure file share, for example).

But I cant find the way… Y have a kind kluster to tests this (azure iis just for production and I cant do tests) in this cluster, I want put the data in a diretory in a hard disk

I hope someone could help me, and sorry if the question is not appropate in some way.

Thanks!

### What is the expected behavior?

I would like find the way for indicate the pvc in replicaset mode

### What do you see instead?

I see that mongo use a internal k8s storage

**Comment by rafariossaa** [comment]
Hi,
  Have you tried using the parameters of [this section](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#user-content-persistence-parameters) ?

**Comment by erniker** [comment]
Y configures this parameter: "persistence.existingClaim" but is just for standalone mode. I see another parametrs like "persistence.volumeClaimTemplates.requests" but, sincerely, y dont know how to, use it...

**Comment by rafariossaa** [comment]
As you are starting with kubernetes, I would suggest you to get familiar with the all the volume provisioning documentation in the kubernetes site. Also, you can play with rendering the chart `helm template mymongo bitnami/mongodb > rendered.yaml`  and check the different sections in `rendered.yaml` to see how it create the volume sections.
