### ISSUE TITLE
helm install rabbitmq-cluster-operator failed

### ISSUE THREAD

**Issue by dnsisme** [bitnami/charts#10937]
### Name and Version

bitnami/rabbitmq-cluster-operator-1.16.0

### What is the problem this feature will solve?

When rabbitmq cluster operator is installed under helm, the following error messages are displayed:
```
Error: UPGRADE FAILED: template: rabbitmq-cluster-operator/charts/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml:4:14: executing "rabbitmq-cluster-operator/charts/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml" at <include "common.labels.standard" .>: error calling include: template: no template "common.labels.standard" associated with template "gotpl"
```

### What is the feature you are proposing to solve the problem?

Maybe we can fix the problem by installing the missing templates, but I don't know the specific implementation details and whether it is feasible to do so。Under normal circumstances, I think rabbitmq cluster operator can be deployed directly. Let me see what is wrong with the configuration information I downloaded，thx~

### What alternatives have you considered?

Update a more comprehensive and available helm deployment chart package

**Comment by carrodher** [comment]
It seems the image is not rendered, can you please copy and paste the error?

**Comment by dnsisme** [comment]
> 

Error: UPGRADE FAILED: template: rabbitmq-cluster-operator/charts/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml:4:14: executing "rabbitmq-cluster-operator/charts/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml" at <include "common.labels.standard" .>: error calling include: template: no template "common.labels.standard" associated with template "gotpl"

**Comment by carrodher** [comment]
Thanks, I just added the error log into the main message.

Can you share with us the `helm upgrade` command you are executing? In fact, it would be nice to know both commands, the one to deploy the helm chart the first time (`helm install ...`) and the one used to upgrade the deployment (`helm upgrade ...`)

**Comment by dnsisme** [comment]
The following error messages will be prompted after replacing the update command

Error: file '/home/work/middle/rabbitmq-cluster-operator/values.yaml' seems to be a YAML file, but expected a gzipped archive

The commands for installing updates are as follows

helm install rabbitmq ./rabbitmq-cluster-operator/values.yaml -n tmp
helm upgrade rabbitmq ./rabbitmq-cluster-operator/values.yaml -n tmp

helm version as follows

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami RabbitMQ Cluster Operator container image or Helm chart but about how the application or environment is being used/configured.

For information about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the technology maintainers.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by dnsisme** [comment]
OK, thank you. Would you like to know more about how you can normally deploy successfully in the k8s cluster using the chart deployment package I provide
