### ISSUE TITLE
Sunset container images releases in GCR

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#10931]
Currently, container images are published in different container registries, being Google Container Registry (GCR) and DockerHub the most popular ones.

In order to unify the source of truth, we decided to not publish new versions in GCR, keeping DockerHub as the only official registry at this time.

**Helm charts use by default DockerHub (`image:registry: docker.io`) which means there is not any impact in default deployments.**

Please note that Bitnami is a [verified publisher since the past year](https://blog.bitnami.com/2021/07/vmware-joins-docker-verified-publisher.html) which means that container images under the Bitnami organization are exempt from rates limiting.

For now, and until further notice, **container images already present in the `gcr.io/bitnami-containers/` repositories won't be deleted**, just no new ones will appear. If at some point we decide to remove this registry and its images, we will update this issue.

**Comment by agomezmoron** [comment]
After deprecated the repository 3 months ago and not being updated, on 29th September we will perform a cleanup of it. Please remember our helm charts use by default DockerHub (image:registry: docker.io) and you can find all our containers at DockerHub.

Thanks
