### ISSUE TITLE
[bitnami/keycloak] Wrong port on metrics service monitor

### ISSUE THREAD

**Issue by marknesterovych** [bitnami/charts#10936]
### Name and Version

bitnami/keycloak-9.3.2

### What steps will reproduce the bug?

Install chart.
curl http://keycloak_ip:9990/metrics -> no responce
curl http://keycloak_ip:8080/metrics -> metrics are shown

metrics-service exposes 9990 which would be correct port for old keycloak based on widefly, but based on quarkus instance exposes metrics on the same port as the main application.

### What is the expected behavior?

metrics-service should expose port 8080, not 9990

### What do you see instead?

Nothing is listening on port 9990

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Would you like to submit a PR with the fix?

**Comment by marknesterovych** [comment]
Will try to prepare one.

**Comment by marknesterovych** [comment]
https://github.com/bitnami/charts/pull/10976

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
