### ISSUE TITLE
etcd cluster 3 replicas one member changes id for unknown reason and goes into CrashLoopBackOff

### ISSUE THREAD

**Issue by c-seeger** [bitnami/charts#10935]
### Name and Version

bitnami/etcd:8.3.2

### What steps will reproduce the bug?

Currently we are running 2 etcd clusters with 3 replica's. They are configured exaclty the same. Only difference is that the production version gets a daily backup using velero and a cron script that makes an hourly snapshot and copies it to some backup location (from exactly the node that starts to get issues with it's member id within the cluster)

```
#!/bin/bash

set -x

bkp_file=/home/bkpuser/backups/etcd-prod.db

/usr/bin/kubectl exec -it etcd-prod-0 -n etcd-prod -- etcdctl snapshot save /tmp/backup.db --user=root --password=<redacted>
/usr/bin/kubectl -n etcd-prod cp etcd-prod-0:/tmp/backup.db $bkp_file
chown bkpuser:bkpuser $bkp_file 
```

The etcd node starts failing with "Cluster id missmatch" and it's member id changed which not exists in the cluster anymore.

Initialy the cluster was setup and worked properly for around a day until consistently this one node (used for backups) starts failing.

The other cluster without backups doesn't have any issues at all.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

cluster stays in sync and member id does not change

### What do you see instead?

etcd-prod-0 member changes it's id for unknown reason starting to fail with "Cluster id missmatch" and going into CrashLoopBackOff

### Additional information

values.yaml replica set to 3, pesistence 20Gi PVC using rook-ceph provisioner, metrics enabled

**Comment by c-seeger** [comment]
I changed the backup script to use
```
/usr/bin/kubectl -n etcd-prod cp etcd-prod-1:/bitnami/etcd/data/member/snap/db* $bkp_file
```
as described in [etcd disaster recovery](https://etcd.io/docs/v3.5/op-guide/recovery/) as another option
instead of using `etcdctl snapshot save` 
for now this seems to do better. 

Any idea if hourly `etcdctl snapshot save` can have an impact on the node member?

**Comment by c-seeger** [comment]
found the issue. the member by default remove themself but setting `removeMemberOnContainerTermination: false` seems to do the trick will keep an eye on that for a while and see if it now runs stable.

Is there a reason to set this to true on default?

**Comment by joancafom** [comment]
Hi @c-seeger 

Thanks for reporting the issue and sharing your findings.

> Is there a reason to set this to true on default?

Yes, as explained in the [Scalability section](https://docs.bitnami.com/kubernetes/infrastructure/etcd/get-started/understand-default-configuration/#scalability) of the documentation, this is set to true so that the pre-stop hook is executed whenever a pod is removed.

That said, there must be something triggering the container termination. Maybe an error during the `snapshot save` operation?

**Comment by c-seeger** [comment]
Hey @joancafom no not really it seems to me that the following happend.

- container got restarted/recreated (maybe due to rescedule of the pod or some node issue) triggering pre-stop hook and removing the member
- container restarted and tried to connect to the cluster but falsely asuming that is is still part of the cluster
- cluster ignores requests from removed member

the current default configuration seems to have issues with recreation of pods using the same persistent data. 

I currently disabled the pre-stop hook termination and now the pods that crash can be recreated without any issue.

I gues what should happen is:
- container got restarted/recreated triggering pre-stop hook removing the member
- **container gets recreated and should add itself back to the cluster (this seems not to happen)**

My initial assumtion was that the snapshot somehow relates to this behaviour but we also started to see this behaviour on our staging cluster that has no snapshots or backups systems running against it. After some testing i found out that the snapshot seems not to interfere.

We had some node issues these days causing some pods to be rescheduled to other nodes but this should not break the cluster.

The current behaviour seems to work for now (we will see how it goes the next days). Since we use the same data independent from the node the pod can be restarted using it's data and its back online, no need to remove and add the member back within this process.

**Comment by c-seeger** [comment]
@joancafom a small update on this one. We found out that the crash of the pods were related to a high storage latency of the underlying storage system causing the cluster to break. Due to this behaviour it wasn't able to remove itself properly from etcd since the member wasn't able to write.


maybe a check can make sense, when the member removes itself from the cluster successfully and local data/cluster data are in sync (maybe just checking if local storage is writable before sending remove request)

**Comment by joancafom** [comment]
Thanks again for updating the thread with your more recent findings.

> maybe a check can make sense, if the member removes itself from the cluster successfully and local data/cluster data are in sync (maybe just checking if local storage is writable before sending remove request)

Hmm this might be indeed tricky. We are already performing a syscall to ensure that the data is in sync:

https://github.com/bitnami/bitnami-docker-etcd/blob/0088082c23287c2b1a4db69ad3bb1876ae318c1b/3.5/debian-11/rootfs/opt/bitnami/scripts/etcd/prestop.sh#L25-L29

in your case (if I understood it right), the path is writable but the problem is the high latency. I don't think we can do much more on this one...
