### ISSUE TITLE
pgpool POD service.type nodeport option needed

### ISSUE THREAD

**Issue by emoxam** [bitnami/charts#10975]
### Name and Version

bitnami/postgresql-ha:9.1.9

### What is the problem this feature will solve?

Set up Pgpool service type at the helm installation

### What is the feature you are proposing to solve the problem?

To change a service type we need to use kubectl edit svc psql-postgresql-ha-pgpool and change clusterip to nodeport
some option kind of pgpool.servicetype will be good, and pgpool.servicetype.port too so after chart install we;ve got what we need

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami! We have values for this. Did you try setting `service.type` and `service.ports.postgresql` values?

**Comment by emoxam** [comment]
values for what ? I am not sure service.type and service.ports.postgresql is for the pgpool. Is "traffic exposure" here meaning pgpool ? https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha/#traffic-exposure-parameters

**Comment by javsalgar** [comment]
Hi, 

Yes, this one is meant for pgpool
