### ISSUE TITLE
Postgres pgaudit not masking passwords for error statements

### ISSUE THREAD

**Issue by govindkailas** [bitnami/charts#10972]
### Name and Version

bitnami/postgresql-11.6.6

### What steps will reproduce the bug?

Environment - v1.22.9 eks-cluster

`helm install psql-pass-test --set audit.pgAuditLog='role' bitnami/postgresql`

I ran a create user statement twice and in the second attempt it showed the password instead of showing `<REDACTED>`
Below are the logs,

`CREATE USER test1 WITH PASSWORD 'test1';`

`2022-06-30 09:38:05.108 GMT [210] LOG: AUDIT: SESSION,1,1,ROLE,CREATE ROLE,,,CREATE USER test1 WITH PASSWORD <REDACTED>,<not logged>`  --- password is REDACTED which is expected and happy with this 💯

Ran the same once again, `CREATE USER test1 WITH PASSWORD 'test1';`

`2022-06-30 09:38:29.653 GMT [210] ERROR: role "test1" already exists 2022-06-30 09:38:29.653 GMT [210] STATEMENT: CREATE USER test1 WITH PASSWORD 'test1';`
 -- Now for the error statement it's showing clear text password. What should I do to REDACT the passwords in error statements as well?

### Are you using any custom parameters or values?

`--set audit.pgAuditLog='role'`

### What is the expected behavior?

All the Passwords should be REDACTED irrespective of the ERROR/INFO statement

### What do you see instead?

The clear-text password is shown in the logs.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami PostgreSQL container image or Helm chart but about how the application works or is being used.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by yukha-dw** [comment]
hello @govindkailas, do you find any solution for this issue? Thank you in advance!
