### ISSUE TITLE
[bitnami/mysql] initdbscripts not run on secondary in mysql replicated cluster 

### ISSUE THREAD

**Issue by matt-hammond-001** [bitnami/charts#10984]
### Name and Version

bitnami/mysql 8.8.26

### What steps will reproduce the bug?

Create cluster with `architecture: replication` and set  a `initdbScriptsConfigMap` that includes a shell script, e.g:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-mysql-initscripts-configmap
data: 
  test.sh: |
    #!/bin/bash

    if [[ "$DB_REPLICATION_MODE" != "slave" ]]; then
        echo "Running init script on a primary"
    else
        echo "Running init script on a secondary"
    fi
```

### What is the expected behavior?

When examining logs from primary and secondary pods in the cluster, we expect to see the two messages above displayed when appropriate. 

### What do you see instead?

The message is displayed in the logs for the primary, but not for the secondary.

### Additional information

The [documentation](https://docs.bitnami.com/kubernetes/infrastructure/mysql/configuration/customize-new-instance/) for the chart states that:

> While .sh scripts are executed on all the nodes, .sql and .sql.gz scripts are only executed on the primary nodes.

But this seems to be at odds with the actual behaviour and implementation. I looked at the chart [definition for the seconday statefulset](https://github.com/bitnami/charts/blob/master/bitnami/mysql/templates/secondary/statefulset.yaml), and as far as I can tell, it is missing the code needed to implement init scripts. This code is present on the definition for the primary statefulset.

**Comment by migruiz4** [comment]
Hi @matt-hammond-001,

Thank you for reporting this issue! I have created #10994 fixing this
