### ISSUE TITLE
bitnami/spring-cloud-dataflow - Unable to redeploy a stream after undeploying

### ISSUE THREAD

**Issue by pravinkumarb84** [bitnami/charts#10981]
### Name and Version

bitnami/spring-cloud-dataflow 11.0.4

### What steps will reproduce the bug?

Deployed bitnami/spring-cloud-dataflow 11.0.4 with external DB as postgres.

Deployed a sample stream - logtest=rabbit-source | log-sink

It got deployed and when try to undeploy it and redeploy it. I have 2 issues.

1. I am unable to deploy. Error from skipper log

```
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 27, column 5:
        "spring.cloud.deployer.kubernete ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 28, column 740:
     ... From: { fieldRef: { fieldPath: "metadata.labels['spring-group-id ...                                          ^
```

Issue 2: In the dashboard, when I view stream definition, I see additional properties getting added for metrics and wavefront which adds difficulty in getting stream definition. How to disable this feature of adding additional properties for metrics and wavefront.

```
rabbit-source --wavefront.application.service=${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --management.metrics.tags.application.type=${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.stream.name=${spring.cloud.dataflow.stream.name:unknown} --management.metrics.tags.application=${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.application.guid=${spring.cloud.application.guid:unknown} --rabbit.queues=test1 --management.metrics.tags.application.name=${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}} --management.metrics.tags.instance.index=${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --wavefront.application.name=${spring.cloud.dataflow.stream.name:unknown} | log-sink --wavefront.application.service=${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --management.metrics.tags.application.type=${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.stream.name=${spring.cloud.dataflow.stream.name:unknown} --management.metrics.tags.application=${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.application.guid=${spring.cloud.application.guid:unknown} --management.metrics.tags.application.name=${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}} --management.metrics.tags.instance.index=${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --wavefront.application.name=${spring.cloud.dataflow.stream.name:unknown}
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Streams should be redeployed

### What do you see instead?

```
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 27, column 5:
        "spring.cloud.deployer.kubernete ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 28, column 740:
     ... From: { fieldRef: { fieldPath: "metadata.labels['spring-group-id ... 
```

**Comment by carrodher** [comment]
[optional/customizable] It seems it is not an issue related to the Bitnami spring-cloud-dataflow container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by pravinkumarb84** [comment]
@carrodher  we have been using the https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow chart since 2019 for the dev and prod environments and have been running 30-40 streams. recently we are trying to move to "https://charts.bitnami.com/bitnami/spring-cloud-dataflow chart. we are facing this issue only with this helm charts, not with the previous ones. we are testing this new chart in dev environment with sample streams and we are facing this issue.

Also, please address on disabling the additional parameters being added to stream properties on deploy. the below query as well.

Issue 2: In the dashboard, when I view stream definition, I see additional properties getting added for metrics and wavefront which adds difficulty in getting stream definition. How to disable this feature of adding additional properties for metrics and wavefront.

**Comment by pravinkumarb84** [comment]
@carrodher  we have been using the https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow chart since 2019 for the dev and prod environments and have been running 30-40 streams. recently we are trying to move to "https://charts.bitnami.com/bitnami/spring-cloud-dataflow chart. we are facing this issue only with this helm charts, not with the previous ones. we are testing this new chart in dev environment with sample streams and we are facing this issue.

Also, please address on disabling the additional parameters being added to stream properties on deploy. the below query as well.

Issue 2: In the dashboard, when I view stream definition, I see additional properties getting added for metrics and wavefront which adds difficulty in getting stream definition. How to disable this feature of adding additional properties for metrics and wavefront.
