### ISSUE TITLE
keycloak: keystore/truststore appears to not be working

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#11007]
### Name and Version

keycloak:9.2.7

### What steps will reproduce the bug?

typical helm install, see next section for values.yaml edits and steps to create keystore/truststore

### Are you using any custom parameters or values?

Configure secret in values.yaml:
```
  auth:
    tls:
      enabled: true
      existingSecret: keycloak-certs
      keystorePassword: changeit
      truststorePassword: changeit
```

Create secret using instructions provided in values.yaml:
```
kubectl create secret generic SECRET_NAME --from-file=./keycloak.truststore.jks --from-file=./keycloak-0.keystore.jks
```

### What is the expected behavior?

This used to work in past installations.  Pretty sure I've got the right procedure.  I've recreated the files involved several times.  I believe they are as they should be.

I should see success when configuring ldaps and clicking on Test Authentication

### What do you see instead?

2022-07-02 21:52:05,479 ERROR [org.keycloak.services] (executor-thread-40) KC-SERVICES0055: Error when authenticating to LDAP: simple bind failed: dc.home.net:636: javax.naming.CommunicationException: simple bind failed: dc.home.net:636 [Root exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

### Additional information

While troubleshooting I exec'd into the pod and downloaded this class to test with:
https://www.itsfullofstars.de/2015/03/test-if-certificate-is-correctly-installed-in-keystore/

The result of the testing is such:
```
keycloak@keycloak-0:/tmp$ !find
find / -name "*.jks"
...
/opt/bitnami/keycloak/certs/keycloak.truststore.jks
/opt/bitnami/keycloak/certs/keycloak.keystore.jks
...
keycloak@keycloak-0:/tmp$ java -Djavax.net.ssl.trustStore=/opt/bitnami/keycloak/certs/keycloak.keystore.jks SSLPoke dc.home.net 636
Successfully connected
keycloak@keycloak-0:/tmp$ java -Djavax.net.ssl.trustStore=/opt/bitnami/keycloak/certs/keycloak.truststore.jks SSLPoke dc.home.net 636
Successfully connected
```

I believe this verifies that the keystore/truststore both work to verify the ldaps location.

**Comment by lknite** [comment]
I've been troubleshooting this and it looks to me like the truststore parameter is missing from the container root java command:

```
keycloak@keycloak-0:/tmp$ echo $(ps ax)
PID TTY STAT TIME COMMAND 1 ? Ssl 1:01 java -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dkc.home.dir=/opt/bitnami/keycloak/bin/../ -Djboss.server.config.dir=/opt/bitnami/keycloak/bin/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp /opt/bitnami/keycloak/bin/../lib/quarkus-run.jar io.quarkus.bootstrap.runner.QuarkusEntryPoint -cf /opt/bitnami/keycloak/conf/keycloak.conf --profile=dev start-dev --auto-build
```

Should it have the '-Djavax.net.ssl.trustStore' like in this test command?
```
keycloak@keycloak-0:/tmp$ java -Djavax.net.ssl.trustStore=/opt/bitnami/keycloak/certs/keycloak.truststore.jks SSLPoke www.google.com 443
```

Also, is there another parameter to add the keystore?

**Comment by lknite** [comment]
values.yaml
```
keycloak:

  # use to increase logging
  image:
    debug: false

  # required otherwise you get a blank page when visiting the admin console
  proxyAddressForwarding: true

  extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"

  # to specify the ad ca public certificate in order to access ldaps
  auth:
    tls:
      enabled: true
      existingSecret: keycloak-certs
      keystorePassword: changeit
      truststorePassword: changeit

  ingress:
    enabled: true
    hostname: keycloak.k.home.net
    ingressClassName: nginx
    pathType: Prefix
    tls: true
    annotations:
      cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
      cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
      cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m

  postgresql:
    enabled: true
    auth:
      password: <passwd_goes_here>
```

**Comment by lknite** [comment]
I went back to chart version 7.1.18 and things started working again.  Maybe the truststore/keystore stopped working after that?

**Comment by javsalgar** [comment]
In order to ensure if the issue has to do with the image, could you try with version 7.1.18 and the latest keycloak image version? Not sure if the change to Qarkus caused incompatibilities with the current procedure.

**Comment by lknite** [comment]
Maybe you missed my note, I already did that test.  I'll give some additional detail.

I started with 9.2.7, then went back to 8.0.2, then went back to 7.1.18 .

Each time I completely wiped the install, deleting the namespace any any pvc.  I did the three different environments twice.  7.1.18 always worked, the other two did not.

The above testing I did with SSLPoke was only on 9.2.7 .  Pretty sure it shows everything is setup correctly as far as the truststore/keystore which was mounted within the pod.  Only that keycloak wasn't seeing the truststore/keystore, apparently.

**Comment by FraPazGal** [comment]
Hello @lknite,

I wasn't able to reproduce this issue in the latest `v9.4.0` for the `bitnami/keycloak` chart. In my test environment, I created my keystore and truststore files and modified the params detailed below before installing the chart:

```
$ kubectl create secret generic keycloak-jks \
--from-file=jks/keycloak.truststore.jks --from-file=jks/keycloak-0.keystore.jks

$ git diff -U0 values.yaml
--- a/bitnami/keycloak/values.yaml
+++ b/bitnami/keycloak/values.yaml
@@ -144 +144 @@ auth:
-    enabled: false
+    enabled: true
@@ -156 +156 @@ auth:
-    existingSecret: ""
+    existingSecret: "keycloak-jks"
@@ -175 +175 @@ auth:
-    keystorePassword: ""
+    keystorePassword: "bitnami1"
@@ -178 +178 @@ auth:
-    truststorePassword: ""
+    truststorePassword: "bitnami1"

$ helm install keycloak bitnami/keycloak -f values.yaml
$ kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
keycloak-0              1/1     Running   0          8m38s
keycloak-postgresql-0   1/1     Running   0          8m38s
$ kubectl logs keycloak-0
...
keycloak 16:35:15.46 INFO  ==> Configuring TLS by setting keystore and truststore

keycloak 16:35:15.48 INFO  ==> ** keycloak setup finished! **
keycloak 16:35:15.49 INFO  ==> ** Starting keycloak **
...
```

Are you using any additional custom params for your `v9` installation? I'm not sure the values at https://github.com/bitnami/charts/issues/11007#issuecomment-1173002448 can be used n the latest major. For example, `proxyAddressForwarding` is no longer present in the chart. Also, if it's possible please double-check the issue persists on your side using the latest chart version.

**Comment by lknite** [comment]
Maybe I just needed to do a 'helm repo update' ... thought I was on the latest.

I'll give 9.4 a shot.

**Comment by keliansb** [comment]
I'm facing the same issue with the version 9.4.1 of the chart.

**Comment by migruiz4** [comment]
Hi there,

With Quarkus, the configuration method used to provide the SPI truststore has changed: https://www.keycloak.org/server/keycloak-truststore
I have created an internal task to fix this issue.

As a temporary workaround, you can use the env var `KEYCLOAK_EXTRA_ARGS` to provide the flags: 

```yaml
- name: KEYCLOAK_EXTRA_ARGS
  value: "--spi-truststore-file-file=path/to/truststore.jks --spi-truststore-file-password=change_me --spi-truststore-file-hostname-verification-policy=WILDCARD"
```

Or use `KEYCLOAK_MOUNTED_CONF_DIR` to mount a `keycloak.conf` file with the settings `spi-truststore-file-password`, `spi-truststore-file-password` and `spi-truststore-file-hostname-verification-policy` preconfigured.

Please let me know if the suggested workaround worked for you, and I'm sorry for the inconvenience.

**Comment by keliansb** [comment]
Just tried your workaround @migruiz4, with the following changes in the Helm chart :
```
extraStartupArgs: >-
  --spi-truststore-file-file=/opt/bitnami/keycloak/certs/keycloak.truststore.jks
  --spi-truststore-file-password=change_me
  --spi-truststore-file-hostname-verification-policy=WILDCARD
```
And the LDAPS connection works now!
But we will wait for a fix because we don't want to set the password in the Helm chart.

**Comment by keliansb** [comment]
Hi, any news regarding this issue? Thank you.

**Comment by migruiz4** [comment]
Hi @keliansb,

We have an internal task to address this issue, but due to other priorities, it is in our backlog at the moment. 
If you'd like to contribute, do not hesitate to send a PR to [bitnami/charts](https://github.com/bitnami/charts) and [bitnami/containers](https://github.com/bitnami/containers) and we will be glad to review them.

**Comment by lknite** [comment]
Folks can use chart version 7.1.18 while waiting until the fix is in place.
