### ISSUE TITLE
Can't see metrics 

### ISSUE THREAD

**Issue by abyssmemes** [bitnami/charts#11005]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

So I just try to see metrics in Prometheus but keep seeing a 404 message

![Screen Shot 2022-07-02 at 16 43 10](https://user-images.githubusercontent.com/48200002/177003518-a6a7d5de-4c5a-4588-9c5d-c93edded021a.png)

### What do you see instead?

404

**Comment by abyssmemes** [comment]
And yes, i did all what need to see metrics

**Comment by carrodher** [comment]
Can you share the custom values used during the deployment?

**Comment by abyssmemes** [comment]
affinity: {}
args: []
auth:
  adminPassword: Tuexbv76&Tbsrhh74
  adminUser: admin
  createAdminUser: false
  existingSecret: ""
  existingSecretPerPassword: {}
  managementPassword: ""
  managementUser: manager
  tls:
    autoGenerated: true
    enabled: true
    existingSecret: ""
    jksSecret: ""
    keystoreFilename: ""
    keystorePassword: ""
    resources:
      limits: {}
      requests: {}
    truststoreFilename: ""
    truststorePassword: ""
autoscaling:
  enabled: true
  maxReplicas: 11
  minReplicas: 1
  targetCPU: ""
  targetMemory: ""
cache:
  authOwnersCount: 1
  ownersCount: 1
clusterDomain: cluster.local
command: []
common:
  exampleValue: common-chart
  global:
    imagePullSecrets: []
    imageRegistry: ""
    storageClass: ""
commonAnnotations: {}
commonLabels: {}
configuration: ""
containerPorts:
  http: 8080
  https: 8443
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}
existingConfigmap: ""
externalDatabase:
  database: keycloak
  existingSecret: ""
  host: database-1.cchxjvhm9mn7.eu-central-1.rds.amazonaws.com
  password: r00t
  port: 5432
  user: keycloak
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ""
extraEnvVarsSecret: ""
extraStartupArgs: ""
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ""
global:
  imagePullSecrets: []
  imageRegistry: ""
  storageClass: ""
hostAliases: []
image:
  debug: false
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/keycloak
  tag: 16.1.0-debian-10-r0
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  apiVersion: ""
  enabled: true
  existingSecret: unpluggedsystems.app-tls
  extraHosts: []
  extraTls: []
  hostname: keycloak.unpluggedsystems.app
  ingressClassName: ""
  path: /
  pathType: Prefix
  secrets: []
  servicePort: http
  tls: true
initContainers: []
initdbScripts: {}
initdbScriptsConfigMap: ""
keycloakConfigCli:
  annotations:
    helm.sh/hook: post-install,post-upgrade,post-rollback
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "5"
  args: []
  backoffLimit: 1
  command: []
  configuration: {}
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: false
  existingConfigmap: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/keycloak-config-cli
    tag: 4.5.0-debian-10-r8
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  resources:
    limits: {}
    requests: {}
kubeVersion: ""
lifecycleHooks: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /auth/
    port: http
  initialDelaySeconds: 300
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 5
metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/port: '{{ .Values.metrics.service.port }}'
      prometheus.io/scrape: "true"
    port: 9990
  serviceMonitor:
    additionalLabels: {}
    enabled: true
    honorLabels: false
    interval: 30s
    namespace: "monitoring"
    relabellings: []
    scrapeTimeout: ""
nameOverride: ""
networkPolicy:
  additionalRules: {}
  allowExternal: true
  enabled: false
nodeAffinityPreset:
  key: ""
  type: ""
  values: []
nodeSelector: {}
pdb:
  create: false
  maxUnavailable: ""
  minAvailable: 1
podAffinityPreset: ""
podAnnotations: {}
podAntiAffinityPreset: soft
podLabels: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
postgresql:
  enabled: false
  existingSecret: ""
  persistence:
    enabled: true
  postgresqlDatabase: bitnami_keycloak
  postgresqlPassword: ""
  postgresqlUsername: bn_keycloak
priorityClassName: ""
proxyAddressForwarding: true
rbac:
  create: false
  rules: []
readinessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /auth/realms/master
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
replicaCount: 1
resources:
  limits: {}
  requests: {}
service:
  annotations: {}
  clusterIP: ""
  externalTrafficPolicy: Cluster
  httpsPort: 443
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  nodePorts:
    http: ""
    https: ""
  port: 8080
  type: ClusterIP
serviceAccount:
  automountServiceAccountToken: false
  create: true
  name: ""
serviceDiscovery:
  enabled: false
  properties: []
  protocol: kubernetes.KUBE_PING
  transportStack: tcp
sidecars: []
startupProbe:
  enabled: false
  failureThreshold: 60
  httpGet:
    path: /auth/
    port: http
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
tolerations: []
updateStrategy:
  type: RollingUpdate

**Comment by joancafom** [comment]
Hi @abyssmemes 

Hmm I believe this could be caused by the recent major that changed WildFly for Quarkus. Now, the endpoint should be `/metrics`, on the same port used as in HTTP. Could you please check it?

```bash
$ curl http://localhost:80/metrics                                                                                                                                                                                
# HELP base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the Java virtual machine.
# TYPE base_classloader_loadedClasses_count gauge
base_classloader_loadedClasses_count 18359.0
...
```

**Comment by abyssmemes** [comment]
> Hi @abyssmemes 
> 
> 
> 
> Hmm I believe this could be caused by the recent major that changed WildFly for Quarkus. Now, the endpoint should be `/metrics`, on the same port used as in HTTP. Could you please check it?
> 
> 
> 
> ```bash
> 
> $ curl http://localhost:80/metrics                                                                                                                                                                                
> 
> # HELP base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the Java virtual machine.
> 
> # TYPE base_classloader_loadedClasses_count gauge
> 
> base_classloader_loadedClasses_count 18359.0
> 
> ...
> 
> ```

Yes, i can see metrics from /metrics path, but this is metric just from WildFly, not from keycloak( I mean we need to see login calls, registration and etd)

**Comment by abyssmemes** [comment]
Anybody just know how can i just see metrics from keycloak? not from wildly?
