### ISSUE TITLE
OpenLDAP chart

### ISSUE THREAD

**Issue by jcbeppler** [bitnami/charts#11003]
### Name and Version

bitnami/openldap

### What is the problem this feature will solve?

There isn't a helm chart for OpenLDAP.

### What is the feature you are proposing to solve the problem?

Bitnami already have an OpenLDAP image and a docker-compose solution so maybe it wouldn't be so complex to implement it on a chart and, in the end, it would be a great addition.

**Comment by rafariossaa** [comment]
Thanks for your suggestion. I am passing this request to our team.
  However I can not guarantee this is going to be implemented, nor provide an ETA.

**Comment by carrodher** [comment]
It is on-hold, this request is being internally analyzed. There are several factors taken into account when adding new products to the catalog and several teams are involved. We will update the ticket with more info.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Comment by Ripolin** [comment]
Hi @carrodher, there is a possibility to submit a PR to init work on this subject ?

**Comment by carrodher** [comment]
Thanks for the suggestion. Unfortunately, it is not only the creation of the PR but the inclusion of a new asset in our CI/CD process that is more time-consuming. At this moment and given other priorities the team has the creation of a bitnami/openldap Helm chart is not something we can tackle.
