### ISSUE TITLE
Allow passing the Elastic Search Configurations from Helm char

### ISSUE THREAD

**Issue by gowthamprabhus** [bitnami/charts#11000]
### Name and Version

airflow/2.3.2

### What is the problem this feature will solve?

Allow passing the Elastic Search Configurations from Helm chart so that it gets updated in airflow.cfg

### What is the feature you are proposing to solve the problem?

Adding the Elastic Search Configs via Helm

**Comment by carrodher** [comment]
Thanks for this suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
