### ISSUE TITLE
what is Best Practices of kafka mirror maker 2

### ISSUE THREAD

**Issue by phongtatyaemsomphong** [bitnami/charts#11012]
### Name and Version

bitnami/kafka 18.0.0

### What steps will reproduce the bug?

-

### Are you using any custom parameters or values?

Now, i config mm2,properties this below
```
clusters=DC1,DC2
DC1.bootstrap.servers = broker1-dev1:30011, broker2-dev1:30012, broker3-dev1:30013
DC2.bootstrap.servers = broker1-dev2:30011, broker2-dev2:30012, broker3-dev2:30013

DC1.config.storage.replication.factor = 3
DC2.config.storage.replication.factor = 3

DC1.offset.storage.replication.factor = 3
DC2.offset.storage.replication.factor = 3

DC1.status.storage.replication.factor = 3
DC2.status.storage.replication.factor = 3

DC1->DC2.enabled = true
DC2->DC1.enabled = true

offset-syncs.topic.replication.factor = 3
heartbeats.topic.replication.factor = 3
checkpoints.topic.replication.factor = 3

topics = .*
groups = .*

task.max = 2
replication.factor = 3
refresh.topics.enabled = true
sync.topics.configs.enabled = true
refresh.topics.interval.seconds = 10


topic.blacklist = .*[\-\.]internal, .*\.replica, __consumer_offsets
groups.blacklist = console-consumer-.*, connect-.*, __.*

DC1->DC2.emit.heartbeats.enabled = true
DC1->DC2.emit.checkpoints.enabled = true

DC2->DC1.emit.heartbeats.enabled = true
DC2->DC1.emit.checkpoints.enabled = true
```
### What is the expected behavior?

I have a test case this below.
1.  Create topic on DC1 name topicTest1, It will replica sync to DC2  and on the DC2 will have topic in name DC1.testTopic1.
2.  next step, I produce message to topicTest1 on DC1 and message will sync to DC1.testTopic1 on DC2.
3.  last step I produce  message to  DC1.testTopic1 on DC2 but message not able sync to topicTest1 on DC1.

I have a question. in test last step at bullet 3. the message is produced to DC1.testTopic1 on DC2 should already sync to topicTest1 on DC1, or not sync ?

If not sync, please explain me

### What do you see instead?

-

### Additional information

thank you.

**Comment by OneCricketeer** [comment]
> produce message to DC1.testTopic1 on DC2 but message not able sync to topicTest1 on DC1

This would cause a loop because `DC1` is being mirrored to `DC1.testTopic1`. 

So, no, it will not sync this way.
