### ISSUE TITLE
LDAP integration with bitnami mariadb

### ISSUE THREAD

**Issue by san4ever** [bitnami/charts#11015]
### Name and Version

bitnami/mariadb

### What is the problem this feature will solve?

Would like to know can i integrate LDAP with mariadb operator.
If yes, what is the configuration i need to  tweak ?

### What is the feature you are proposing to solve the problem?

Would like to know can i integrate LDAP with mariadb operator.
If yes, what is the configuration i need to  tweak ?

**Comment by rafariossaa** [comment]
Hi,
  Not sure what you mean here. The maria chart is not an operator but  a regular chart, so maybe you are looking for other kind of kubernetes deployment.
  In any case, nor this chart neither the mariadb container image are prepared to make LDAP configuration easy.

**Comment by san4ever** [comment]
Hi Rafari,
I just want to know whether this image is capable of AD integration ?
As i don't see any AD/LDPA Related parameters in values.yaml

**Comment by rafariossaa** [comment]
Hi, 
  Yes, that is what I mentioned in my previous comment. There is not integration with AD/LDAP.

**Comment by san4ever** [comment]
Thanks for the reply

**Comment by rafariossaa** [comment]
I am closing this issue.
