### ISSUE TITLE
there is no log file found after installing zookeeper & kafka by helm

### ISSUE THREAD

**Issue by sumpf** [bitnami/charts#11029]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

1. helm install zookeeper bitnami/zookeeper

### Are you using any custom parameters or values?

no, I don't

### What is the expected behavior?

there should be log file under /opt/bitnami/kafka/logs directory but, no files are found.

### What do you see instead?

there is no log files under /opt/bitnami/kafka/logs directory
[kafka pod]
```
I have no name!@kafka-0:/opt/bitnami/kafka/logs$ ls -altr
total 12
drwxrwxr-x 1 root root 4096 Jun 11 05:29 ..
drwxrwsrwx 2 root 1001 4096 Jul  4 02:00 .
```
but I can see kafka log under worker node in kubernete cluster.

[worker node]
```
root@w1:/var/log/pods/kafka_kafka-1_663ac3ac-86c3-4b9a-9af5-d98a5bd79941/kafka# ls
0.log 

ubuntu@project2-dev1:~$ kubectl logs kafka-0 -n kafka
kafka 02:00:32.45
kafka 02:00:32.46 Welcome to the Bitnami kafka container
kafka 02:00:32.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 02:00:32.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 02:00:32.46
kafka 02:00:32.46 INFO  ==> ** Starting Kafka setup **
```

**Comment by javsalgar** [comment]
Hi,

We configured the kafka chart to redirect all logs to standard output and standard error. Do you see any logs when executing `kubectl logs` ?

**Comment by sumpf** [comment]
hello javsalgar, sorry for late reply. yes I can see log with kubectl logs. I wonder if there is option to write kafka log in container or container volume such as PV with values.yaml in helm chart.

**Comment by hqthinh26** [comment]
Hi guys,

I am hitting the same problem. My tried to set **ZOO_LOG4J_PROP = 'INFO, ROLLINGFILE' and ZOO_LOG_LEVEL='INFO'** under containers.zookeeper.env. However, no logs are found in the /opt/bitnami/zookeeper/log directory.

Have anyone met and resolved this before.

Thanks :)

**Comment by sumpf** [comment]
it seems container default output is standard output. so it doesn't log in container side but kubernetes node side.
https://kubernetes.io/docs/concepts/cluster-administration/logging/

**Comment by mshivanna** [comment]
newer version of kafka charts have slightly modified log4j.properties now
