### ISSUE TITLE
Other Kafka environment variables

### ISSUE THREAD

**Issue by justpolidor** [bitnami/charts#1103]
Is there a way to set the OFFSETS_TOPIC_REPLICATION_FACTOR and other environment variables not listed in the guide ? At the moment, if I try to set it, the image ignores the existence of that environment variable.

For example I want to set these variables
```
- name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
value: "3"
- name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
 value: "3"
- name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
value: "2"
- name: KAFKA_MIN_INSYNC_REPLICAS
value: "2"
```

When Kafka goes up, it shows the server.properties file but these values aren't in it.

**Comment by juan131** [comment]
Hi @justpolidor 

In this JSON file you can check the current env. variables supported in the Bitnami Kafka image:

https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-9/rootfs/kafka-inputs.json

I saw you created another issue (https://github.com/bitnami/bitnami-docker-kafka/issues/41) at the image repository. I'll follow the conversation there and close this issue.
