### ISSUE TITLE
[bitnami/keycloak] initial admin user not being created

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#11047]
### Name and Version

bitnami/keycloak 8.0.2

### What steps will reproduce the bug?

1. helm install keycloak # fresh database
2. Go to the admin console
3. can't login as no admin user has been created yet

### What is the expected behavior?

Previously (wildfly) allowed an initial admin user to be created but this doesn't appear to happen under quarkus (even the readme about this chart refers to wildfly for the adminUser/password).

I'd like to ensure that setting the `auth.adminUser` and `auth.adminPassword` still result in an admin user being created on a fresh install.

### What do you see instead?

![image](https://user-images.githubusercontent.com/39212456/177342929-6bdb9e83-e2d8-4e2e-a18a-6658943fa62b.png)

### Additional information

Documentation about this: https://www.keycloak.org/getting-started/getting-started-zip#_create_an_admin_user

Appears this might of been overlooked in the upgrades from previous versions of keycloak and the majority of the users of keycloak will already have an admin user hence why this would have been missed (I'm freshingly installing it and ran into this, previously I had been upgrading in place)

Having looked at https://github.com/bitnami/bitnami-docker-keycloak/blob/edbbf4d49149fc1e89755d5b0b0d560dd7b61f1d/18/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L245 I don't see anything about "creating initial user" or anything like that either

**This happens in the latest version aswell**

**Comment by jack1902** [comment]
ok so this is because i was overriding the command/args piece of the chart.

I think it would be beneficial to ensure that the "proper" env-vars are used over the ones keycloak have:
- `KEYCLOAK_ADMIN_USER` -> `KEYCLOAK_ADMIN` 
https://www.keycloak.org/server/configuration#_setup_of_the_initial_admin_user

This would avoid running into weird issues when overriding the command/args (entrypoint/cmd) of the underlying containers.

I'd happily get a PR in to update env-vars to the ones that are known to keycloak vs ones that get mapped to keycloak ones within the scripts from bitnami (which will be fine to keep as it maintains a level of backwards compatibility)

**Comment by javsalgar** [comment]
Hi!

Thanks for letting us know. Would you like to submit a PR in the https://github.com/bitnami/bitnami-docker-keycloak/ repo?

**Comment by jack1902** [comment]
Will raise a PR shortly to address the variable being used within the chart (the script isn't the issue here)

The variable that is currently used is only useful to the script which maps it to the variable known to keycloak. Using the variable that is known to keycloak straight away makes more sense

**Comment by jack1902** [comment]
I've got a pr open,how can there be a lack of activity
