### ISSUE TITLE
[bitnami/pinniped] impersonation proxy service not working

### ISSUE THREAD

**Issue by wolffberg** [bitnami/charts#11054]
### Name and Version

bitnami/pinniped 0.1.5

### What steps will reproduce the bug?

Deploy Pinniped using the Bitnami Helm Chart in a Kubernetes cluster without a `kube-controller-manager` pod running and with the following configuration:

```hcl
credentialIssuerConfig = <<EOT
impersonationProxy:
  mode: enabled
  service:
    type: ClusterIP
EOT
```
_We deploy the chart using the Terraform Helm provider_

### Are you using any custom parameters or values?

```hcl
credentialIssuerConfig = <<EOT
impersonationProxy:
  mode: enabled
  service:
    type: ClusterIP
EOT
```
_We deploy the chart using the Terraform Helm provider_

### What is the expected behavior?

The `pinniped-concierge-impersonation-proxy-cluster-ip` service created by Pinniped should have targets with the port `8444` exposed.

### What do you see instead?

1. The service have no targets as the selector does not match the `pinniped-concierge` pod.
```yaml
selector:                                 
  app: ""
```
2. The `pinniped-concierge` pod does not expose port `8444`

### Additional information

Any solutions to this from the Helm Chart side could be considered to be a bit hacky as the service is created by Pinniped itself.
A fix could be to expose port `8444` if `impersonationProxy mode = enabled` and add the label `app = ""` to the `pinniped-concierge` deployment.

**Comment by javsalgar** [comment]
Hi,

It is not clear to me whether this is something to be done by the helm chart or by pinniped-concierge itself. If it is the latter, then my advice would be to open a ticket to the pinniped devs. 

https://github.com/vmware-tanzu/pinniped

**Comment by wolffberg** [comment]
I raised https://github.com/vmware-tanzu/pinniped/issues/1220 yesterday for that reason but I think the issue should be solved on both sides.

As the deployment is created by Helm the chart should make sure that port `8444` is exposed, either by default or with a switch.
As Pinniped decides whether the impersonation proxy should be used I'm not sure you can make the decision automatically.

The pod labels should also match the service and for that I see two solutions.
1. Add the `app=""` label to the pinniped pod to allow the service to pick it up.
2. Make Pinniped copy labels from the pod to the service it creates.

I think solution 2 is the better option so I will add that to https://github.com/vmware-tanzu/pinniped/issues/1220.

**Comment by javsalgar** [comment]
Hi,

If I'm not mistaken, that option 2 you are proposing is something to be implemented in Pinniped, right?

**Comment by wolffberg** [comment]
That is correct. Do you want to close this issue or keep it open to track https://github.com/vmware-tanzu/pinniped/issues/1220?

**Comment by javsalgar** [comment]
If there's nothing to do in our side, I'd close this issue then.

**Comment by cfryanr** [comment]
@javsalgar,

Would it be possible to reopen this issue? See https://github.com/vmware-tanzu/pinniped/issues/1220#issuecomment-1377613439 for more details.
