### ISSUE TITLE
Unable to create non-persisted redis-cluster

### ISSUE THREAD

**Issue by mehdipourfar** [bitnami/charts#11050]
### Name and Version

bitnami/redis-cluster 7.6.4

### What steps will reproduce the bug?

Just installing redis-cluster with my custom values which are not important really.

### Are you using any custom parameters or values?

persistence:
  enabled: false

### What is the expected behavior?

Not trying to create pvc

### What do you see instead?

creates pvcs

### Additional information

Hi. I want to have a redis cluster just for sharding and I don't want any persistence. Neither rdb nor appendonly. How can I achieve that?

**Comment by javsalgar** [comment]
Hi,

From the time being, the persistence is necessary for storing the cluster data, otherwise it won't be able to recover form restart. We are open to suggestions on how to guarantee cluster recovery without using persistence.

**Comment by javsalgar** [comment]
I currently mean the `nodes.sh` file.

**Comment by mehdipourfar** [comment]
Okay. What I mean by non-persisted is that I'll be able to comment out those save commands in [configmap](https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/configmap.yaml#L302) file. Is there any way to do that?

**Comment by javsalgar** [comment]
Hi,

I believe that the contents of that configmap should be moved to the values.yaml file so they can be modified. Thoughts?

**Comment by mehdipourfar** [comment]
Yes. I also think so.

**Comment by javsalgar** [comment]
Great, I will open a task for this. If you want to speed up the process, would you like to submit a PR?

**Comment by mehdipourfar** [comment]
It's the first time I'm using helm. I don't think I can be a good contributor for this task:)
