### ISSUE TITLE
Cannot install from scratch on GKE - metrics.image.pullSecrets

### ISSUE THREAD

**Issue by ozomer** [bitnami/charts#1105]
**Which chart**:

etcd 2.2.0

**Description**

Cannot install from scratch on GKE.

**Steps to reproduce the issue:**

`helm install --name=my-release bitnami/etcd --set auth.rbac.enabled=false`

**Describe the results you received:**

```
Error: render error in "etcd/templates/statefulset.yaml": template: etcd/templates/statefulset.yaml:42:4: executing "etcd/templates/statefulset.yaml" at <include "etcd.imageP...>: error calling include: template: etcd/templates/_helpers.tpl:137:48: executing "etcd.imagePullSecrets" at <.Values.metrics.imag...>: can't evaluate field pullSecrets in type interface {}
```

**Describe the results you expected:**

Successful installation?

**Additional information you deem important (e.g. issue happens only occasionally):**

Solved by calling:

```sh
helm install --name=sportclub1-staging bitnami/etcd --set auth.rbac.enabled=false --set metrics.image.pullSecrets=
```

I'm new to helm, so I don't understand its internals, but I guess `metrics.image.pullSecrets` should have a default empty value.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.5-gke.10", GitCommit:"d0686b9f0adfcf759cde9f1d2d80fd52ab01d58f", GitTreeState:"clean", BuildDate:"2019-02-22T20:02:13Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"
```

**Comment by carrodher** [comment]
Thanks for report the issue @ozomer, we just fixed it in the above Pull Request.
The source of the issue was due to we were trying to use a `.Values.metrics.image.pullSecrets` as part of a function in the `_helpers.tpl`, but in the `values.yaml` the `metrics` object didn't have `image` property (and of course nor `pullSecrets` under it)
```yaml
metrics:
  enabled: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2379"
```
