### ISSUE TITLE
Restore OrangeHRM and update OrangeHRM Chart to v5.0

### ISSUE THREAD

**Issue by Handfish** [bitnami/charts#11066]
### Name and Version

bitnami/orangehrm

### What is the problem this feature will solve?

[OrangeHRM was deprecated and removed since the upstream project only supported deprecated PHP versions](https://github.com/bitnami/charts/pull/8697)

[OrangeHRM v5 migrated to php 8.x](https://github.com/orangehrm/orangehrm/issues/1089#issuecomment-1010750628)

[OrangeHRM has released version 5.0.](https://github.com/orangehrm/orangehrm/tree/5.0)

### What is the feature you are proposing to solve the problem?

[OrangeHRM has released version 5.0.](https://github.com/orangehrm/orangehrm/tree/5.0)

The deprecated helm chart can be updated to OrangeHRM 5.0 and therefore utilize [Php 8.0](https://github.com/orangehrm/orangehrm/blob/5.0/src/composer.json#L10)

**Comment by javsalgar** [comment]
Hi!

Thanks for the input! We are working on adding new applications into the catalog like grafana-loki or pinniped, and re-enabling deprecated Helm charts is not something on our roadmap
