### ISSUE TITLE
Keycloak upgrade failed 9.3.3 to 9.4.0

### ISSUE THREAD

**Issue by jeluizferreira** [bitnami/charts#11067]
### Name and Version

bitnami/keycloak 9.4.0

### What steps will reproduce the bug?

1. Upgrade from 9.3.3 to 9.4.0 (also happens when updating from 9.3.3 to 9.3.4).

### Are you using any custom parameters or values?

yes, a lot of them.
```yaml
externalDatabase:
  database: bitnami_keycloak
  existingSecret: ''
  existingSecretPasswordKey: ''
  host: postgresql-dev.postgresql-dev
  password: S3nh@Usu@r10S3rv1c0C0t3c
  port: 5432
  user: bn_keycloak
postgresql:
  architecture: standalone
  auth:
    database: bitnami_keycloak
    existingSecret: ''
    password: ''
    username: bn_keycloak
  enabled: false
```

### What do you see instead?

```
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.44
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.45 Welcome to the Bitnami keycloak container
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.45 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-keycloak
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.45 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-keycloak/issues
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.46
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.46 INFO ==> ** Starting keycloak setup **
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.47 INFO ==> Validating settings in KEYCLOAK_* env vars...
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.49 INFO ==> Trying to connect to PostgreSQL server postgresql-dev.postgresql-dev...
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.51 INFO ==> Found PostgreSQL server listening at postgresql-dev.postgresql-dev:5432
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.51 INFO ==> Configuring database settings
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.56 INFO ==> Enabling statistics
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.57 INFO ==> Configuring http settings
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.59 INFO ==> Configuring hostname settings
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.60 INFO ==> Configuring cache count
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.62 INFO ==> Configuring log level
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.63 INFO ==> Configuring proxy
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.65 INFO ==> Configuring TLS by setting keystore and truststore
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.68 INFO ==> ** keycloak setup finished! **
Wed, Jul 6 2022 1:40:26 pm |  
Wed, Jul 6 2022 1:40:26 pm | keycloak 16:40:26.69 INFO ==> ** Starting keycloak **
Wed, Jul 6 2022 1:40:26 pm | Appending additional Java properties to JAVA_OPTS: -Djgroups.dns.query=keycloak-dev-headless.keycloak-dev.svc.cluster.local
Wed, Jul 6 2022 1:40:29 pm | 2022-07-06 16:40:29,026 WARN [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
Wed, Jul 6 2022 1:40:29 pm | - quarkus.datasource.jdbc.driver is set to 'org.h2.jdbcx.JdbcDataSource' but it is build time fixed to 'org.postgresql.xa.PGXADataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
Wed, Jul 6 2022 1:40:29 pm | 2022-07-06 16:40:29,318 INFO [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
Wed, Jul 6 2022 1:40:29 pm | 2022-07-06 16:40:29,401 WARN [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://postgresql-dev.postgresql-dev:5432/bitnami_keycloak?currentSchema=public
Wed, Jul 6 2022 1:40:29 pm | 2022-07-06 16:40:29,402 WARN [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://postgresql-dev.postgresql-dev:5432/bitnami_keycloak?currentSchema=public
Wed, Jul 6 2022 1:40:29 pm | at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
Wed, Jul 6 2022 1:40:29 pm | at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
Wed, Jul 6 2022 1:40:29 pm | at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
Wed, Jul 6 2022 1:40:29 pm | at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
Wed, Jul 6 2022 1:40:29 pm | at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
Wed, Jul 6 2022 1:40:29 pm | at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Wed, Jul 6 2022 1:40:29 pm | at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
Wed, Jul 6 2022 1:40:29 pm | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
Wed, Jul 6 2022 1:40:29 pm | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Wed, Jul 6 2022 1:40:29 pm | at java.base/java.lang.Thread.run(Thread.java:829)
Wed, Jul 6 2022 1:40:29 pm |  
Wed, Jul 6 2022 1:40:29 pm | 2022-07-06 16:40:29,897 WARN [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://postgresql-dev.postgresql-dev:5432/bitnami_keycloak?currentSchema=public
Wed, Jul 6 2022 1:40:30 pm | 2022-07-06 16:40:30,032 WARN [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
Wed, Jul 6 2022 1:40:30 pm | 2022-07-06 16:40:30,037 WARN [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
Wed, Jul 6 2022 1:40:30 pm | 2022-07-06 16:40:30,051 INFO [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
Wed, Jul 6 2022 1:40:30 pm | 2022-07-06 16:40:30,202 INFO [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
Wed, Jul 6 2022 1:40:30 pm | 2022-07-06 16:40:30,298 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
Wed, Jul 6 2022 1:40:32 pm | 2022-07-06 16:40:32,419 INFO [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-dev-1-50861: no members discovered after 2003 ms: creating cluster as coordinator
Wed, Jul 6 2022 1:40:32 pm | 2022-07-06 16:40:32,437 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-dev-1-50861\|0] (1) [keycloak-dev-1-50861]
Wed, Jul 6 2022 1:40:32 pm | 2022-07-06 16:40:32,442 INFO [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-dev-1-50861`, physical addresses are `[172.27.5.144:7800]`
Wed, Jul 6 2022 1:40:32 pm | 2022-07-06 16:40:32,942 INFO [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
Wed, Jul 6 2022 1:40:33 pm | 2022-07-06 16:40:33,104 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
Wed, Jul 6 2022 1:40:33 pm | 2022-07-06 16:40:33,104 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
Wed, Jul 6 2022 1:40:33 pm | 2022-07-06 16:40:33,105 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:postgresql://postgresql-dev.postgresql-dev:5432/bitnami_keycloak?currentSchema=public
Wed, Jul 6 2022 1:40:33 pm | 2022-07-06 16:40:33,106 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Additional information

Looks like the jdbc driver for postgres was not included when external databases is used instead of embended postgres database.

**Comment by polter05** [comment]
We have the same issue

**Comment by rpiecyk** [comment]
I am also encountering the same issue. Currently, for the recent docker image (18.0.2-debian-11-r1 and higher) there is no
`kc.sh build --db=${DB_TYPE:-postgres}` command run during entrypoint execution. 
As a result there is a conflict - build time option `quarkus.datasource.jdbc.driver` does not match `--db` option from the kc.sh start command.

I think as a solution `--auto-build` parameter needs to be added to start command here: https://github.com/bitnami/bitnami-docker-keycloak/blob/18.0.2-debian-11-r4/18/debian-11/rootfs/opt/bitnami/scripts/keycloak/run.sh#L22

Right now I am trying to fit it in `${KEYCLOAK_EXTRA_ARGS}` variable. If it works I will give an update

**Comment by polter05** [comment]
> I am also encountering the same issue. Currently, for the recent docker image (18.0.2-debian-11-r1 and higher) there is no `kc.sh build --db=${DB_TYPE:-postgres}` command run during entrypoint execution. As a result there is a conflict - build time option `quarkus.datasource.jdbc.driver` does not match `--db` option from the kc.sh start command.
> 
> I think as a solution `--auto-build` parameter needs to be added to start command here: https://github.com/bitnami/bitnami-docker-keycloak/blob/18.0.2-debian-11-r4/18/debian-11/rootfs/opt/bitnami/scripts/keycloak/run.sh#L22
> 
> Right now I am trying to fit it in `${KEYCLOAK_EXTRA_ARGS}` variable. If it works I will give an update

added in charts values

```
- name: KEYCLOAK_EXTRA_ARGS
value: "--auto-build"
```

**Comment by migruiz4** [comment]
Hi there,

We are currently investigating an issue with Keycloak when `KEYCLOAK_PRODUCTION` is enabled. 
As @polter05, setting the flag `--auto-build` appears to fix the issue.

Could you please confirm if you are deploying Keycloak with `KEYCLOAK_PRODUCTION=yes`?

**Comment by polter05** [comment]
Hi

I confirm we are deploying in production mode
Tks
________________________________
De : Miguel Ruiz ***@***.***>
Envoyé : Friday, July 15, 2022 6:06:56 PM
À : bitnami/charts ***@***.***>
Cc : Benoit Waldmann ***@***.***>; Mention ***@***.***>
Objet : Re: [bitnami/charts] Keycloak upgrade failed 9.3.3 to 9.4.0 (Issue #11067)


Hi there,

We are currently investigating an issue with Keycloak when KEYCLOAK_PRODUCTION is enabled.
As @polter05<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolter05&data=05%7C01%7Cbenoit.waldmann%40siagilus.fr%7C0d6e98f1b60a4194f2d308da667c0b98%7C6a8a7862481b4f6c8236058d5f89a731%7C0%7C0%7C637934980212619582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OUzI%2FctmSg3FpTw4Z4yz8aOKZbCJ%2F4eyxSuQ2kA3jMI%3D&reserved=0>, setting the flag --auto-build appears to fix the issue.

Could you please confirm if you are deploying Keycloak with KEYCLOAK_PRODUCTION=yes?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbitnami%2Fcharts%2Fissues%2F11067%23issuecomment-1185687242&data=05%7C01%7Cbenoit.waldmann%40siagilus.fr%7C0d6e98f1b60a4194f2d308da667c0b98%7C6a8a7862481b4f6c8236058d5f89a731%7C0%7C0%7C637934980212619582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yrj%2FHH98JlBbvtL1Xsd5yUS6jwOdJ7Qh78sil608aHA%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQOLP4C46W734K7FROMO63LVUGECBANCNFSM522MYUVQ&data=05%7C01%7Cbenoit.waldmann%40siagilus.fr%7C0d6e98f1b60a4194f2d308da667c0b98%7C6a8a7862481b4f6c8236058d5f89a731%7C0%7C0%7C637934980212619582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rYR9J0ChLIC500k%2FlOmMRQLrlQmmRiL5B3f96DIhu4U%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


Diffusion restreinte

**Comment by rpiecyk** [comment]
I kind of slept on the issue - it works for me too, as PR was declined I used `KEYCLOAK_EXTRA_ARGS`. 
Probably will rewrite it kind of more in bitnami way to get it approved, like setting a new env variable

**Comment by migruiz4** [comment]
Thank you very much for your feedback!
I'm adding the on-hold label so the bot does not close this, we will share any updates here

**Comment by bh-tt** [comment]
Just tried it with --auto-build, which fixes this issue. However, keycloak appears to forget any infinispan clustering parameters given. This is a large issue for HA deployments. We are setting `-Djgroups.dns.query=keycloak-headless`, `-Djava.net.preferIPv4Stack=true`, `KC_CACHE_STACK=kubernetes` and `KEYCLOAK_PRODUCTION=true`. If we add `KEYCLOAK_EXTRA_ARGS=--auto-build`, no clustering is done. If we remove it clustering works fine.

**Comment by migruiz4** [comment]
Hi there,

I'm sorry for the late response.

Starting Keycloak 19 the flag `--auto-build` was deprecated and instead the `auto-build` is embedded in the `start` command, so the workaround `KEYCLOAK_EXTRA_ARGS=--auto-build` is no longer necessary: https://www.keycloak.org/2022/07/keycloak-1900-released

In addition, we are adding support for the KEYCLOAK_PRODUCTION=true using the value `production` in the next major of the bitnami/keycloak chart: #13103
