### ISSUE TITLE
Charts repository behavior prevent proxification through artifactory

### ISSUE THREAD

**Issue by Lunik** [bitnami/charts#11060]
### What steps will reproduce the bug?

Using the "remote repository" and "virtual repository" to proxy Bitnami charts repo "https://charts.bitnami.com/" in Artifactory we are having issues with the current behavior of the repository.

Bitnami service always responds 200 even if the URL is not correct (it returns the index.yaml file), for example: "https://charts.bitnami.com/bitnami/not/working". Artifactory thinks that the artifact exists in bitnami but it's not. This leads to overlapping when having multiple helm proxies in the same "virtual repository"

### What is the expected behavior?

Bitnami chart repository should return 404 when accessing an invalid URL

### What do you see instead?

Bitnami chart repository returns 200 with the index.yaml when accessing an invalid URL

**Comment by Lunik** [comment]
Related issue in Jfrog bug tracker : https://www.jfrog.com/jira/browse/RTFACT-27257

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. I will forward this to the engineering team for consideration.

**Comment by Lunik** [comment]
This is still an ongoing issue

**Comment by olwe0002** [comment]
this behavior still exists and still breaks artifactory

**Comment by Lunik** [comment]
this behavior still exists and still breaks artifactory

**Comment by Lunik** [comment]
this behavior still exists and still breaks artifactory

**Comment by krisztianharagos** [comment]
I think it might be a bad cloudfront configuration:

curl -k -I https://charts.bitnami.com/doesnt-matter-what-is-here
HTTP/1.0 200 Connection established

HTTP/2 200 
content-type: text/plain
**content-length: 5800390**
last-modified: Tue, 13 Sep 2022 14:30:12 GMT
x-amz-server-side-encryption: AES256
x-amz-meta-s3cmd-attrs: atime:1663079403/ctime:1663079403/gid:121/gname:docker/md5:eebd444bb727fca29ed0ab244c9da44f/mode:33188/mtime:1663079403/uid:1001/uname:runner
x-amz-version-id: jIEW0XT.TyTsXsVBQW1l6grrsie0eZly
accept-ranges: bytes
server: AmazonS3
date: Tue, 13 Sep 2022 15:35:33 GMT
etag: "eebd444bb727fca29ed0ab244c9da44f"
vary: Accept-Encoding
**x-cache: Error from cloudfront**
via: 1.1 d92debab8d9ca0518390aebaec8733a6.cloudfront.net (CloudFront)
x-amz-cf-pop: ZRH50-C1
x-amz-cf-id: ZDTh8a_CsW3VtVxs7u59WHqU73__58MhHfTYmyE58N0-AX7Dap1BoQ==
age: 7

**Comment by krisztianharagos** [comment]
Looks like the default handler (in case of non-existing files) is giving back the content of the index.yaml instead of giving back 404.

**Comment by mcdonagj** [comment]
Sorry, but was there a resolution to this behavior?

I can see the issue was closed, but my team is continuing to see this behavior exclusively with a remote Helm repository we've configured to target `charts.bitnami.com`.

I confirmed that I get the same `curl` response from Cloudfront as @krisztianharagos' response:
![image](https://user-images.githubusercontent.com/20607878/195910682-d3c71952-6cea-47a1-baa3-64fce51aca2d.png)

**Comment by Lunik** [comment]
The issue is not resolved but the evil bot decided otherwise.
By the count of messages from the bitnami team, it may suggest that this is not one of theirs priorities.

**Comment by mcdonagj** [comment]
@javsalgar, any chance you could check on the status of this issue with the engineering team?

I'm not familiar with the workflow of the team, but if this happened to get moved to Closed by mistake, I'd appreciate if it could be reopened to reflect the current status of the issue.

Glad to help verify any changes made towards fixing this issue! :)

**Comment by mcdonagj** [comment]
:( Bumping for an answer; maybe I can open another issue for more visibility?

**Comment by justinmchase** [comment]
Can someone share their jfrog configuration for this?

**Comment by justinmchase** [comment]
I can confirm for people here that bitnami is now returning 403 in the above curl cases not 200. I'm not sure if that will create another problem or not, but it is different.

I am unable to currently mirror the bitnami repository, but not sure why. If anyone could some of the settings they are using that would help a lot.

**Comment by carrodher** [comment]
This URL is designed to be used with `curl` or web browsers, it only works when adding it to the Helm client:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
```

The only browsable URL is https://charts.bitnami.com/ which redirects you to a static page with some instructions about how to add the repository to the Helm client.

With `curl` you can fetch the _index.yaml_, but that's all
```console
$ curl https://charts.bitnami.com/bitnami/index.yaml
...
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 3.8.0
    created: "2022-06-02T01:56:22.118314024Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Apache ZooKeeper provides a reliable, centralized register of configuration
      data and services for distributed applications.
    digest: sha256:f57fe57cfe2280fe4ca87ffd546b64625cf650c02cdb5b849ee0ddad06302a9b
    home: https://github.com/bitnami/charts/tree/master/bitnami/zookeeper
    icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
    keywords:
    - zookeeper
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: zookeeper
    sources:
    - https://github.com/bitnami/bitnami-docker-zookeeper
    - https://zookeeper.apache.org/
    urls:
    - https://charts.bitnami.com/bitnami/zookeeper-9.2.1.tgz
    version: 9.2.1
generated: "2023-01-09T18:56:51.100542554Z"
```

**Comment by justinmchase** [comment]
We figured it out, turns out you have to create a remote with rewriting enabled then also a virtual that includes that remote. Pulling from the virtual works.

I can confirm this issue is resolved.
