### ISSUE TITLE
Adding modules for apache

### ISSUE THREAD

**Issue by nairagit** [bitnami/charts#11068]
### Name and Version

bitnami/apache 2.4.54

### What is the problem this feature will solve?

We want to add additional modules to the apache httpd configuration.
- lbmethod_byrequests_module.so
- lbmethod_bytraffic_module.so
- lbmethod_bybusyness_module.so

### What is the feature you are proposing to solve the problem?

Add functionality to load additional modules:

**Comment by javsalgar** [comment]
Hi,

Right now, several options come to mind. 

- If you already have the modules compiled (and compatible with Debian 11), then you could try mounting them
- Create your own fork of the container where you compile the modules and add them to the container
