### ISSUE TITLE
unable to set key in redis-cluster deployed using helm charts

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#11063]
### Name and Version

bitnami/redis-cluster , latest

### What steps will reproduce the bug?

helm install redis bitnami/redis-cluster

### Are you using any custom parameters or values?

set service .type=NodePort and service.nodePorts.redis=30102

### What is the expected behavior?

when using redis-cli and setting key , i should be able to set ant get key

### What do you see instead?

Could not connect to Redis at 172.17.0.4:6379: No route to host

**Comment by abhishekgupta2205** [comment]
-> Redirected to slot [5798] located at 172.17.0.6:6379
Could not connect to Redis at 172.17.0.6:6379: No route to host
(3.08s)

same keys get added  while some are not

**Comment by javsalgar** [comment]
Did you follow the instructions after deploying the chart? You may need to upgrade the deployment so the list of service IPs are added

**Comment by abhishekgupta2205** [comment]
no external ips are created . hence i cannot upgrade it

**Comment by abhishekgupta2205** [comment]
I tried using a custom nodeport. When i connect to redis-cli inside the pod , i am able to set and get the keys(in case of rerouting due to sharding also). Due to it i think internal routing is happening correctly inside pods . But when i try to set or get key from redis-cli (redis-cli -c -h {my-ip} -p (expose nodeport) -a (password))  , redis-cli is connected and i am able to run every command like cluster info etc. which means redis-cli is properly connected to pod . BUt when i try to set and get key from other master or slave  (due to sharding ) i am unable to set or get key .

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-07-12 11-38-59](https://user-images.githubusercontent.com/68244292/178420811-9b03fce5-d00b-4e4b-ae9b-04c9bb02c765.png)

**Comment by abhishekgupta2205** [comment]
can you tell me what is the error?
![Screenshot from 2022-07-12 11-41-38](https://user-images.githubusercontent.com/68244292/178421023-cd5a6f89-3895-471d-af37-01ff7cea9d7f.png)

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-07-12 13-14-43](https://user-images.githubusercontent.com/68244292/178436921-226450e8-ca66-40fe-9d6c-4dffc685c0a8.png)

**Comment by javsalgar** [comment]
Hi,

Are you using minikube? You could try using the MetalLb addon to have external IPs: https://faun.pub/metallb-configuration-in-minikube-to-enable-kubernetes-service-of-type-loadbalancer-9559739787df

**Comment by abhishekgupta2205** [comment]
After using metallb also same error is coming . metallb is proving external ip and cluster is also craeted sucessfully but same error is coming . when setting key no route to host is coming

**Comment by abhishekgupta2205** [comment]
when i tried accesing through redis-cli outside the cluster , it gives error.
![Uploading Screenshot from 2022-08-28 12-36-53.png…]()
