### ISSUE TITLE
[bitnami/external-dns] Cannot apply psp ClusterRoles

### ISSUE THREAD

**Issue by lftgl** [bitnami/charts#11079]
### Name and Version

bitname/external-dns-6.6.0

### What steps will reproduce the bug?

1. helm diff/install
2. see custom values below
3. Error: ` Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ClusterRole.rules[0].resourceNames[0]): invalid type for io.k8s.api.rbac.v1.PolicyRule.resourceNames: got "array", expected "string"`
4. Error in bitnami/external-dns/templates/psp-clusterrole.yaml, double dash, see: https://github.com/bitnami/charts/commit/de4f3996ed7798f360e43a019afc7a36624bbafd#diff-db308782098adc019ffef38a713880e02f483b99d464b4799cd66a63efb18b7aR20

### Are you using any custom parameters or values?

```
rbac:
  pspEnabled: true
```

### What do you see instead?

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ClusterRole.rules[0].resourceNames[0]): invalid type for io.k8s.api.rbac.v1.PolicyRule.resourceNames: got "array", expected "string"

**Comment by akshatcx** [comment]
same issue, was not happening last week
