### ISSUE TITLE
[bitnami/minio] Allow empty for s3 gateway auth

### ISSUE THREAD

**Issue by kyue1005** [bitnami/charts#11087]
### Name and Version

bitnami/minio:11.7.7

### What steps will reproduce the bug?

There is an unnecessary empty values check for s3 gateway auth when using in AWS EKS with IRSA

https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/_helpers.tpl#L287-L296
```template
{{/*
Validate values of MinIO&reg; - when using MinIO&reg; as a S3 Gateway, the Access & Secret keys are required
*/}}
{{- define "minio.validateValues.gateway.s3.credentials" -}}
{{- if and .Values.gateway.enabled (eq .Values.gateway.type "s3") (or (empty .Values.gateway.auth.s3.accessKey) (empty .Values.gateway.auth.s3.secretKey)) }}
minio: gateway.auth.s3
    The Access & Secret keys are required to use MinIO&reg; as a S3 Gateway.
    Please set valid keys (--set gateway.auth.s3.accessKey="xxxx",gateway.auth.s3.secretKey="yyyy")
{{- end -}}
{{- end -}}
```

### What is the expected behavior?

allow empty for ateway.auth.s3.accessKey and gateway.auth.s3.secretKey

### What do you see instead?

forced to supply for both value

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input! Would you like to submit a PR fixing the issue?

**Comment by kyue1005** [comment]
@javsalgar hey, here you go
https://github.com/bitnami/charts/pull/11212

**Comment by rafariossaa** [comment]
Hi, 
  Thanks, we will review and merge it.
