### ISSUE TITLE
Redis with default topology (master-replica) is not working as expected

### ISSUE THREAD

**Issue by mgomse** [bitnami/charts#11083]
### Name and Version

bitnami/redis:16.13.2

### What steps will reproduce the bug?

```
cat <<EOF > my-values.yaml                                                                                                                                               
>   persistence:
>     enabled: false
>
> architecture: replication
>
> replica:
>   replicaCount: 3
>   persistence:
>     enabled: false
>
> auth:
>   enabled: false
>
> metrics:
>   enabled: false
>
> commonConfiguration: |-
>   maxmemory 1024mb
>   maxmemory-policy volatile-lru
>   # Disable RDB persistence (ref: https://redis.io/topics/persistence)
>   save ""
>   # Disable AOF persistence (ref: https://redis.io/topics/persistence)
>   appendonly no
> EOF

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install --values=my-values.yaml my-release bitnami/redis

#set some value 
kubectl exec -it my-release-redis-master-0 redis-cli set a "myvalue"
#check is this value on master and replica - here everything is OK
kubectl exec -it my-release-redis-master-0 redis-cli get a
kubectl exec -it my-release-redis-replicas-1 redis-cli get a
#delete master pod (simulate disaster)
kubectl  delete po my-release-redis-master-0
#check is this value on master and replica - here we don't have anymore our values (replicas containers were restarted)
kubectl exec -it my-release-redis-master-0 redis-cli get a
kubectl exec -it my-release-redis-replicas-1 redis-cli get a

kubectl get po
NAME                          READY   STATUS    RESTARTS      AGE
my-release-redis-master-0     1/1     Running   0             58s
my-release-redis-replicas-0   1/1     Running   1 (36s ago)   3m16s
my-release-redis-replicas-1   1/1     Running   1 (36s ago)   2m41s
my-release-redis-replicas-2   1/1     Running   1 (31s ago)   2m16s

```

### Are you using any custom parameters or values?
```
master:
  persistence:
    enabled: false

architecture: replication

replica:
  replicaCount: 3
  persistence:
    enabled: false

auth:
  enabled: false

metrics:
  enabled: false

commonConfiguration: |-
  maxmemory 1024mb
  maxmemory-policy volatile-lru
  # Disable RDB persistence (ref: https://redis.io/topics/persistence)
  save ""
  # Disable AOF persistence (ref: https://redis.io/topics/persistence)
  appendonly no
```
### What is the expected behavior?

Even without persistance I'll expect that replicas will keep the data and when master is rolled out then it will fetch data from replicas (initialize with replicas data).

As it is written in the readme:

> Default: Master-Replicas
> When installing the chart with architecture=replication, it will deploy a Redis® master StatefulSet and a Redis® replicas StatefulSet. The replicas will be read-replicas of the master. Two services will be exposed:

> Redis® Master service: Points to the master, where read-write operations can be performed
> Redis® Replicas service: Points to the replicas, where only read operations are allowed by default.
> **In case the master crashes, the replicas will wait until the master node is respawned again by the Kubernetes Controller Manager.**

### What do you see instead?

In can see that master is initialized with empty data (not getting data from replicas)

### Additional information

I tried to set `livenessProbe: disabled` for replicas (because I thought that it is because of replicas liveness probes) but it doesn't help

**Comment by javsalgar** [comment]
Hi,

Does Redis have this feature of syncing the master with the replicas data when the master is down?
