### ISSUE TITLE
Kafka serviceType NodePort

### ISSUE THREAD

**Issue by csifinos** [bitnami/charts#1110]
Hello,

This is not a bug.
Since I have noticed that in kafka svc.yaml there is not an option to specify the nodeport if you have selected service type NodePort.
Will you add this functionality?

**Which chart**:

bitnami/kafka

**Description**

Want to specify the nodeport that will be exposed in kafka service.

**Steps to reproduce the issue:**

helm install --set image.tag=2.1.1,service.type=NodePort,service.nodePort=30903 bitnami/kafka

**Describe the results you received:**

Starts a Kafka node port service with port 31779

**Describe the results you expected:**

Starts a Kafka node port service with port 30903

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by juan131** [comment]
Hi @csifinos 

Thanks for the suggestion! I just created a PR to address it.

**Comment by juan131** [comment]
Hi @csifinos 

We just merged the changes and there's a new chart (version 1.8.0) where you can specify the nodePort. You just need to follow the steps below:

```bash
$ helm repo update
$ helm search bitnami/kafka
$ helm install --set service.type=NodePort,service.nodePort=39092 --name kafka bitnami/kafka
...
$ echo "NODE_PORT is $(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services kafka)"
NODE_PORT is 30092
```
