### ISSUE TITLE
Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock (same issue as #9083)

### ISSUE THREAD

**Issue by malupo** [bitnami/charts#11105]
### Name and Version

bitnami/mysql

### What steps will reproduce the bug?

helm install mysql bitnami/mysql --namespace mysql --create-namespace --set global.storageClass=standard
Mysql startup probe fails -- and I see this behavior via a display:
```
NAME      READY   STATUS    RESTARTS   AGE
mysql-0   0/1     Running   0          8s
mysql-0   0/1     Running   1 (1s ago)   114s
```
Never goes to 1/1

### Are you using any custom parameters or values?

See steps above
--- Please note that each time I have run the Helm install, -- I have first deleted the old PV and PVC -- as well as the namespace 'mysql',

### What is the expected behavior?

for the pod to go to status  1/1

### What do you see instead?
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  35s               default-scheduler  Successfully assigned mysql/mysql-0 to minikube-m02
  Normal   Pulled     34s               kubelet            Container image "docker.io/bitnami/bitnami-shell:11-debian-11-r10" already present on machine
  Normal   Created    34s               kubelet            Created container volume-permissions
  Normal   Started    33s               kubelet            Started container volume-permissions
  Normal   Pulled     33s               kubelet            Container image "docker.io/bitnami/mysql:8.0.29-debian-11-r9" already present on machine
  Normal   Created    33s               kubelet            Created container mysql
  Normal   Started    33s               kubelet            Started container mysql
  Warning  Unhealthy  5s (x2 over 15s)  kubelet            Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
```
### Additional information

If I edit the statefulset yaml -- and rip out all the probes and save, -- I can get mysql to come up --- but that is putting a bandaid on the problem.

**Comment by malupo** [comment]
Huh.... well that's wierd.   I was running with Minikube and 2 nodes.   I deleted my "m02" node and just ran minikube with 1 node.
I still see the "can't login to local Mysql server through the socket" error ---- But the pod does initialize to 1/1 so it is usable,
I've deleted MYSQL a number of times -- and it is initializing successfully now.

**Comment by javsalgar** [comment]
Hi,

That unhealth status could be something transient due to the container initialization. If the node is usable then the `mysql` command is working properly.

**Comment by KamToHung** [comment]
Hi,
if you use nfs, you can restart your nfs-server
