### ISSUE TITLE
Keycloak chart still references obsolete Wildfly features

### ISSUE THREAD

**Issue by kherock** [bitnami/charts#11129]
### Name and Version

bitnami/keycloak 9.4.0

### What steps will reproduce the bug?

This issue occurs for any configuration of the chart.

### What do you see instead?

After deploying the chart with the default values, the following resources are created

* A `management` listener for Wildfly management on port 9990 on the pod container
* a management-password in the keycloak secret
  * Leaving this field empty can cause the chart to report
    ```
     PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
     ```
     when an upgrade modifies the keycloak secret (for example, toggling TLS on/off)

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! Would you like to submit a PR fixing the outdated references?

**Comment by kherock** [comment]
Yes I should be able to in the near future, though this is low priority for me at the moment in case someone else has the time!
