### ISSUE TITLE
k8 pods are not created in redis-cluster helm chart

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#11123]
### Name and Version

bitnami/redis-cluster , 7.6.4

### What steps will reproduce the bug?

installing helm chart

### Are you using any custom parameters or values?

cluster.externalAcess.enbled=true

### What is the expected behavior?

pods should be created 

### What do you see instead?

no pods are created and external ip also remains pending

**Comment by javsalgar** [comment]
Hi,

If the external IP is pending, then it seems to me that there kubernetes cluster is missing the proper external IP configuration. Which cluster are you using?

**Comment by abhishekgupta2205** [comment]
minikube

**Comment by javsalgar** [comment]
Hi,

In this case, you need to enable addons like metallb in order to have external IPs. This link should help you https://faun.pub/metallb-configuration-in-minikube-to-enable-kubernetes-service-of-type-loadbalancer-9559739787df

**Comment by abhishekgupta2205** [comment]
if i remove cluster.externalAccess.enabled =true then dump.rdb file is created

**Comment by abhishekgupta2205** [comment]
also many masters are not allotted any slots .
![Screenshot from 2022-07-14 17-48-04](https://user-images.githubusercontent.com/68244292/178980619-b782fcd9-142a-48eb-895a-fbe822ab98d2.png)

**Comment by abhishekgupta2205** [comment]
Steps i did - 
1) install helm chart using externalacess.enabled =true parameter
2) when i go inside the pod and execute redis-cli , i shows only one nodes. so i sent cluster meet command to connect to other nodes.
3) when i tried using redis-cli to set the keys  it show clusterdown hashslot not served. to solve it , i used (redis-cli --cluster fix) command to  solve it
4) now probelems which i am facing is that all the nodes are now masters and some nodes have no slot allocated and dump.rdb file is not created

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-07-15 12-32-03](https://user-images.githubusercontent.com/68244292/179169835-acb8a009-9052-42cb-a923-8184bbbedf6e.png)

**Comment by fmulero** [comment]
Hi @abhishekgupta2205

When `externalacess.enabled =true` you need to perform some additional steps to set the external IPs. These steps are exposed in the notes after installing the helm chart. Example:
```
$ helm install redis-cluster bitnami/redis-cluster --set cluster.externalAccess.enabled=true
NAME: redis-cluster
LAST DEPLOYED: Fri Jul 15 10:07:05 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: redis-cluster
CHART VERSION: 8.0.0
APP VERSION: 7.0.3** Please be patient while the chart is being deployed **


To get your password run:
    export REDIS_PASSWORD=$(kubectl get secret --namespace "default" redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis&reg; server from outside the cluster check the following information:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w redis-cluster'

    You will have a different external IP for each Redis&reg; node. Get the external ip from `-external` suffixed services: `kubectl get svc`.
    Redis&reg; port: 6379
    Once the LoadBalancerIPs are ready, you need to provide them and perform a Helm Upgrade:

    helm upgrade --namespace default redis-cluster --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=load-balancerip-0,cluster.externalAccess.service.loadBalancerIP[1]=load-balancerip-1,cluster.externalAccess.service.loadBalancerIP[2]=load-balancerip-2,cluster.externalAccess.service.loadBalancerIP[3]=load-balancerip-3,cluster.externalAccess.service.loadBalancerIP[4]=load-balancerip-4,cluster.externalAccess.service.loadBalancerIP[5]=load-balancerip-5" bitnami/redis-cluster
    Where loadbalancer-ip-i are the LoadBalancerIPs provided by the cluster.
```

**Comment by abhishekgupta2205** [comment]
hi @fmulero i tried connecting to  individual redis nodes through redis-cli by using external ip and nodeport provided , but could not connect to it.
But i am able to connect through redis-cluster svc. is there any error or am i missing something.
![Screenshot from 2022-07-21 11-18-59](https://user-images.githubusercontent.com/68244292/180139024-15295e58-bb15-4bd6-bbba-a1c0f4b507ee.png)

**Comment by abhishekgupta2205** [comment]
sir, external ip is also not created in kubernetes cluster. is there any alternate like metallb addon in minikube  that i can use on kubernetes cluster so that external ip is created there also

**Comment by abhishekgupta2205** [comment]
Also can you suggest some other way to do the same functioning as cluster.externalaccess.enabled parameter is performing.

**Comment by abhishekgupta2205** [comment]
means without load balancer
