### ISSUE TITLE
I can't use any other wsrep_provider_options except for gcahe_size in mariadb-galera chart

### ISSUE THREAD

**Issue by gybaek** [bitnami/charts#11122]
### Name and Version

 bitnami/mariadb-galera- 7.3.5 

### What steps will reproduce the bug?

1. On the Kubernetes, I've installed bitnami/mariadb-galera for the test. And I want to config wsrep_provider_options in the values.yaml. But any paramter except for gcache.size, I can't add. 

For example,

wsrep_provider_options="gcache.size=2G;gcache.recovery=yes"
  
2. The Kubernets log outputs like below.
![제목 없음](https://user-images.githubusercontent.com/109051075/178176237-edda32da-6cc6-47ee-9906-d27580da9154.png)

and stop the installation. pod is crashing and restart over and over again. 
so I  eliminate gcache.recovery, then it installed normaly. I tested every other parameters like evs.delay_margin=PT2S, gcs.recv_q_soft_limit=0.5. 
I don't know the reason.  is this what helm intended? 

### What do you see instead?

...

**Comment by javsalgar** [comment]
Hi,

Did you try the value `mariadbConfiguration` with your custom config?

**Comment by gybaek** [comment]
> Hi,
> 
> Did you try the value `mariadbConfiguration` with your custom config?

**Comment by gybaek** [comment]
what do you mean custom config? I use default values.yaml in helm chart. 


![제목 없음](https://user-images.githubusercontent.com/109051075/178380787-51489310-0d98-4945-891e-cdb3c242f0df.png)

**Comment by javsalgar** [comment]
So, let me see if I understand it correctly. Are you changing any parameters in the values.yaml file?

**Comment by gybaek** [comment]
oh, I use image parameter below. That's all parameter I use. 
Image and wsrep_provider_options in mariadbConfiguration in the yaml.file.

image:
  registry: docker.io
  repository: bitnami/mariadb-galera
  tag: 10.6.8-debian-11-r3

**Comment by javsalgar** [comment]
Could you launch the chart with image.debug=true to see if we can see more debugging information?
