### ISSUE TITLE
Pod stops with initialization of magento on Azure Kubernetes service

### ISSUE THREAD

**Issue by kbulte** [bitnami/charts#1112]
**Which chart**:

magento-4.1.5

**Description**

While installing the magento helm chart on my AKS cluster(v1.12.6) the pod stops running when the magento initialization process reaches the Cleaning up cache folders after installing step. Afterwards pods are constantly restarted without success.

**Steps to reproduce the issue:**

1. helm install stable/magento
2. helm upgrade clunky-wildebeest stable/magento --set magentoHost=myhost,magentoPassword=mymagentopass,mariadb.db.password=mymariapass

**Describe the results you received:**
kubectl logs clunky-wildebeest-magento-5cc8894cd4-zfr7k
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing magento
magento INFO  Preparing PHP environment...
magento INFO  Preparing webserver environment...
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at clunky-wildebeest-mariadb:3306
mysql-c INFO  MySQL server listening and working at clunky-wildebeest-mariadb:3306
magento INFO  Installing Magento...
magento INFO  Deploying to developer mode...
magento INFO  Reindexing...
magento INFO  Flushing cache...
magento INFO  Cleaning up cache folders after installing

kubectl get pods
NAME                                         READY     STATUS    RESTARTS   
clunky-wildebeest-magento-5cc8894cd4-zfr7k   0/1       Running   19         
clunky-wildebeest-mariadb-0                  1/1       Running   0          

**Describe the results you expected:**

To be able to access the magento installation.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tompizmor** [comment]
Hi @kbulte,

Can you install the chart with debug options to see what is failing? 

I just updated the magento chart so it is easy to enable debug during initialization, you just need to pass `--set image.debug=true` option. 

Make sure you install the magento chart version 4.4.1 or newer. (Run `helm repo update` to fetch the latest charts)

Also, it is possible that kubernetes readiness or liveness probes is killing the pod because magento takes a lot of time to initialize. You can try to deploy the chart increasing the timeouts for these checks or disable them completely. There are options exposed in the [values.yaml](https://github.com/helm/charts/blob/master/stable/magento/values.yaml#L170-L186) to control it.

**Comment by kbulte** [comment]
Thanks for the reply @tompizmor,

I used magento chart 4.4.1, enabled debugging and disabled the liveness probes on AKS. It was still not able to start a pod. It seems it stopped add the configurePermissions step:
nami --log-level trace initialize libphp
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
for module in "${@}"
 nami_initialize_one magento
local module=magento
grep -q '"lifecycle": "unpacked"'
nami inspect magento
local inputs=
[[ -f /magento-inputs.json ]]
inputs=--inputs-file=/magento-inputs.json
nami --log-level trace initialize magento --inputs-file=/magento-inputs.json
nami    INFO  Initializing magento
apache  TRACE Skipping reload: com.bitnami.apache not running
apache  TRACE [runProgram] Executing: null /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
apache  TRACE code: 0
apache  TRACE stdout:

apache  TRACE stderr:

magento TRACE [runProgram] Executing: usermod -g,daemon,bitnami
magento TRACE [runProgram] Executing: usermod -G,bitnami,bitnami
magento INFO  Preparing Magento environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at your-toad-mariadb:3306
mysql-c TRACE [canConnect] Testing connection with 'xxxxx' user
mysql-c TRACE [showDatabases] Getting databases for 'xxxxx' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hyour-toad-mariadb -ubn_magento -p3nJ6Apih9Q -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_magento\ninformation_schema\ntest\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: bitnami_magento
information_schema
test

mysql-c TRACE [canConnect] Connection with 'xxxxx' user is successful
mysql-c INFO  MySQL server listening and working at your-toad-mariadb:3306
magento TRACE [restorePersistedData] Restoring /bitnami/magento/htdocs/pub/static to /opt/bitnami/magento/htdocs/pub/static
magento TRACE [restorePersistedData] Restoring /bitnami/magento/htdocs/pub/media to /opt/bitnami/magento/htdocs/pub/media
magento TRACE [restorePersistedData] Restoring /bitnami/magento/htdocs/var to /opt/bitnami/magento/htdocs/var
magento TRACE [restorePersistedData] Restoring /bitnami/magento/htdocs/app/etc to /opt/bitnami/magento/htdocs/app/etc
apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
magento TRACE [configurePermissions] File to chown: /opt/bitnami/magento/htdocs

AKS was continuously trying to start pods and always the debug logs stopped at the configurePermissions step. I increased the `readinessProbe.timeoutSeconds` and gave up the next morning I checked and AKS had all requested pods running.  So it seems it is related to timeouts. This doesn't give me much confidence for a production workload. It should not take that much time to start the magento pod.

So I tested on a local kubernetes cluster on my dev machine and it stopped at the same  configurePermissions step for a couple of minutes but the local cluster doesn't time out and after a while the first magento pod was started. Is there a way to fasten the initialization?

**Comment by tompizmor** [comment]
Hi @kbulte,

I just wanted to let you know that I have been checking the Magento chart and it is also slow for me. Other users reported similar issues in the past, especially in AKS, and at the end, it seems the issue was that changing the permissions of all Magento files was very slow.

Because of that, we moved some logic to the [Dockerfile](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/Dockerfile#L15) and it was a bit faster.

I will try to take a deeper look and update this issue once I have more information.

**Comment by tompizmor** [comment]
@kbulte I just released a new version of the Magento container that should initialize faster. The fix is included in `2.3.1-debian-9-r12` tag and `2.3.1-ol-7-r13` so make sure you use those tags or a rolling tag that actually pulls those images or newer.

**Comment by kbulte** [comment]
Hey @tompizmor,

I finally found some time to switch to the new version of the Magento container it is indeed a littlebit faster. Thanks for all the help.

**Comment by tompizmor** [comment]
Thanks for writing back! It's good to know
