### ISSUE TITLE
kafka chart missing internal topic configuration

### ISSUE THREAD

**Issue by rjanovski** [bitnami/charts#1116]
**Which chart**:

kafka-1.5.0 (appVersion 2.1.1)

**Description**

Critical section of the configuration cannot be changed by the chart:
from kafka's server.properties:
```
############################# Internal Topic Settings  #############################
# The replication factor for the group metadata internal topics "__consumer_offsets" and "__transaction_state"
# For anything other than development testing, a value greater than 1 is recommended for to ensure availability such as 3.
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
```

basically, replication factors for internal topics need to be changed for cluster usage:
> For anything other than development testing, a value greater than 1 is recommended for to ensure availability

so the chart needs to expose these values, or give a proper defaults according to the number of brokers

**Additional information you deem important (e.g. issue happens only occasionally):**

kafka-docker related bug: https://github.com/bitnami/bitnami-docker-kafka/issues/43

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tompizmor** [comment]
I will update the chart after making a new release of the kafka container as I said in  https://github.com/bitnami/bitnami-docker-kafka/issues/43

**Comment by tompizmor** [comment]
Done! The PR https://github.com/bitnami/charts/pull/1118 has been merged
