### ISSUE TITLE
Invalid command in the chart causes the controller failed to start

### ISSUE THREAD

**Issue by elvishsu66** [bitnami/charts#11168]
### Name and Version

bitnami/sealed-secrets

### What steps will reproduce the bug?

The original value from bitnami-labs
https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/deployment.yaml#L55

The current value of this chart
https://github.com/bitnami/charts/blob/master/bitnami/sealed-secrets/templates/deployment.yaml#L89

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The container should start successfully instead of the following error

```
Error: failed to start container "sealed-secrets": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/controller": stat /controller: no such file or directory: unknown
```

### What do you see instead?

In the value.yaml, override the command to 

```
## @param command Override default container command
##
command:
  - controller
```

### Additional information

Can you please update the default value in the template?

**Comment by alemorcuq** [comment]
Thanks for reporting this.

Unfortunately, I couldn't reproduce your issue. I installed the latest version of the chart `1.0.10` and it worked:

```
$ helm install ss bitnami/sealed-secrets
...

$ k get po
NAME                                READY   STATUS    RESTARTS   AGE
ss-sealed-secrets-98fc87dcf-wf59v   1/1     Running   0          3m45s
```

Did you try with the latest version as well?

**Comment by elvishsu66** [comment]
Well, interesting
So I was using `bitnami/sealed-secrets-controller` instead of `bitnami/sealed-secrets`

So this chart uses `bitnami-docker-sealed-secrets`
https://github.com/bitnami/bitnami-docker-sealed-secrets/blob/master/0/scratch/Dockerfile

Where the chart from  `bitnami-labs`
https://github.com/bitnami-labs/sealed-secrets

which the application is located at  `/usr/local/bin/`
https://github.com/bitnami-labs/sealed-secrets/blob/main/Dockerfile

My bad, I was confused 🙇‍♂️ 

So anyway, eventually I rolled back to use `bitnami-labs's` chart instead.
