### ISSUE TITLE
how to use auth.usePasswordFile helm variable

### ISSUE THREAD

**Issue by alirezarpi** [bitnami/charts#11169]
### Name and Version

bitnami/mongodb-sharded

### What steps will reproduce the bug?

how do I use `auth.passwordFile` ?

where do I set the passwordFile directory

### What do you see instead?

no screenshots

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
