### ISSUE TITLE
zookeeper can not start in k3s

### ISSUE THREAD

**Issue by zigaai** [bitnami/charts#11188]
### Name and Version

docker.io/bitnami/zookeeper:3.8.0-debian-11-r6

### What steps will reproduce the bug?

1. `helm install zookeeper bitnami/zookeeper  -n zookeeper`
2. the pod still `In Progress` status and the error message is `0/1 nodes are available: 1 Insufficient cpu.`, but the resource is enough
3. `kubectl get all -o wide `
```
NAME              READY   STATUS    RESTARTS   AGE    IP       NODE     NOMINATED NODE   READINESS GATES
pod/zookeeper-0   0/1     Pending   0          118s   <none>   <none>   <none>           <none>

NAME                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE    SELECTOR
service/zookeeper-headless   ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   118s   app.kubernetes.io/component=zookeeper,app.kubernetes.io/instance=zookeeper,app.kubernetes.io/name=zookeeper
service/zookeeper            ClusterIP   10.43.233.218   <none>        2181/TCP,2888/TCP,3888/TCP   118s   app.kubernetes.io/component=zookeeper,app.kubernetes.io/instance=zookeeper,app.kubernetes.io/name=zookeeper

NAME                         READY   AGE    CONTAINERS   IMAGES
statefulset.apps/zookeeper   0/1     118s   zookeeper    docker.io/bitnami/zookeeper:3.8.0-debian-11-r6
```
4. `kubectl top node`
```
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
debian   354m         8%     10878Mi         67% 
```

### Are you using any custom parameters or values?

```yaml
global:
  ...
  storageClass: "longhorn"
...
persistence:
  ...
  storageClass: "longhorn"
  size: 1Gi
```

### What do you see instead?

what's the problem with this?

**Comment by rafariossaa** [comment]
Hi @zigaai 
  I think the error is pretty clear here, there is not enough resources (CPU), it doesn't seem related to the chart itself.

**Comment by rafariossaa** [comment]
No sure about the screenshot, but according to the output of `kubectl describe node`, you are already at 94% of CPU resources.

**Comment by zigaai** [comment]
> No sure about the screenshot, but according to the output of `kubectl describe node`, you are already at 94% of CPU resources.

i see, thank you for your reply
