### ISSUE TITLE
All Solr Collection Data is by default stored on /solr  folder

### ISSUE THREAD

**Issue by Aadarsh-Verma** [bitnami/charts#11184]
### Name and Version

bitnami/solr 5.0.0

### What steps will reproduce the bug?

helm install solr --version 5.0.0

### Are you using any custom parameters or values?

None

### What is the expected behavior?

I want my znode to be root at /

### What do you see instead?

All collectons are stored in /solr

**Comment by Aadarsh-Verma** [comment]
![image](https://user-images.githubusercontent.com/65499911/178934969-037d0cfd-41f9-4b67-b056-084947d93330.png)

**Comment by javsalgar** [comment]
Hi,

This is the default solr configuration, do you know which parameters needs to be changed at solr level in order to allow that?

**Comment by Aadarsh-Verma** [comment]
yes we need to change the ZK_HOST in solr.in.sh file to change the default namespace. How to plant my own solr.in.sh through k8s so that my configs are loaded.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but the container initialization scripts uses the default solr zookeeper node. To be able to change it by using ZK_HOST some changes need to be performed in the container scripts.
  Please feel free to send a PR implementing this. We will be glad to review and merge it.
