### ISSUE TITLE
can you please add an angular 7 pkg

### ISSUE THREAD

**Issue by kushwahashiv** [bitnami/charts#1119]
**Which chart**:

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by carrodher** [comment]
Hi, can you develop your request a little more? Thanks
