### ISSUE TITLE
bitnami/Matomo- PVCs are not creating automatically when `replicaCount` grows

### ISSUE THREAD

**Issue by rakeshnambiar** [bitnami/charts#11199]
### Name and Version

bitnami/Matomo

### What steps will reproduce the bug?

I applied the https://github.com/bitnami/charts/blob/master/bitnami/matomo/values.yaml with `replicaCount: 2` but it creates only one PVC and the second POD ended up with the `error` state. May I ask how I create multiple PVCs through the values.yaml file, please?

### Are you using any custom parameters or values?

https://github.com/bitnami/charts/blob/master/bitnami/matomo/values.yaml 

### What is the expected behavior?

Based on the bitnamic/rabbitmq experience it should create multiple PVCs based on the `replicaCount`

### What do you see instead?

Ended up with an error stating the PVC is already in use by another POD.

**Comment by fmulero** [comment]
Hi @rakeshnambiar

Unfortunately I am not able to reproduce your issue, so we are going to need more information:
* Are you setting any other value in your release?
* About the failing pod, Could you share the logs? Could you also share the events associated to that pod (`kubectl describe pod <name of your pod>`)?

**Comment by rakeshnambiar** [comment]
@fmulero here's the error message:

```
Events:
  Type     Reason              Age    From                     Message
  ----     ------              ----   ----                     -------
  Normal   Scheduled           3m19s  default-scheduler        Successfully assigned demo/epmc-piwik-new-matomo-76c7965dcf-l7dsp to lit-ehk-cluster-stg-wezoggxitjjy-node-2
  Warning  FailedAttachVolume  3m15s  attachdetach-controller  Multi-Attach error for volume "pvc-884a2a2f-0d75-4c87-b2bc-055da17d9f32" Volume is already used by pod(s) epmc-piwik-new-matomo-76c7965dcf-7xd9r
  Warning  FailedMount         76s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[matomo-data], unattached volumes=[matomo-data kube-api-access-rmsrl]: timed out waiting for the condition
```
PVC:
```
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
data-epmc-piwik-new-mariadb-0   Bound    pvc-926f8fc5-c2d9-4a16-a7ba-9d14c33e0b85   8Gi        RWO            default-cinder   4m58s
epmc-piwik-new-matomo-matomo    Bound    pvc-884a2a2f-0d75-4c87-b2bc-055da17d9f32   8Gi        RWO            default-cinder   5m1s
```

PODs:
```
NAME                                                                 READY   STATUS              RESTARTS        AGE
epmc-piwik-new-mariadb-0                                 1/1     Running             0                         4m44s
epmc-piwik-new-matomo-76c7965dcf-7xd9r   1/1     Running             1 (3m29s ago)   4m44s
epmc-piwik-new-matomo-76c7965dcf-l7dsp   0/1     ContainerCreating   0                  4m44s
```

**Comment by fmulero** [comment]
It seems your configuration doesn't allow to attach the same volume to multiple pods. Please have a look to [cinder documentation](https://docs.openstack.org/cinder/latest/admin/blockstorage-volume-multiattach.html)
