### ISSUE TITLE
Will bitnami/wordpress support runAsGroup feature?

### ISSUE THREAD

**Issue by weiliang1216** [bitnami/charts#11205]
### Name and Version

bitnami/wordpress 1.2.3

### What is the problem this feature will solve?

Some container clouds doesn't support gid: 0. So wordpress will have a permission denied error. I hope to support non-root group to resolve this issue.

### What is the feature you are proposing to solve the problem?

to support non-root group, and add runAsGroup feature in the helm values.

**Comment by fmulero** [comment]
Hi @weiliang1216 

Have you tried setting `podSecurityContext.runAsGroup`? For instance:
```yaml
podSecurityContext:
  enabled: true
  runAsGroup: 1100
```

**Comment by weiliang1216** [comment]
yes, I tired. But it meet some permission denied issue.

**Comment by migruiz4** [comment]
Hi @weiliang1216,

This issue has been previously discussed here: https://github.com/bitnami/bitnami-docker-postgresql/issues/242

As of today, it is necessary to build your own custom image modifying the ownership of `/otp/bitnami` in order to run with a different GID.

**Comment by weiliang1216** [comment]
Thanks migruiz4, haven't seen this discussion before.
So there seem that will be no such feature in the short term. Am I right?
It seems I can only customize the image, which makes the installation and deployment more troublesome.
