### ISSUE TITLE
[bitnami/nginx] Unable to override default readinessProbe with customReadinessProbe

### ISSUE THREAD

**Issue by sreenivas-ps** [bitnami/charts#11210]
### Name and Version

bitnami/nginx 13.1.2

### What steps will reproduce the bug?

GKE cluster v1.21.12-gke.1500
Terraform 0.15.5

```
resource "helm_release" "dbt-docs" {
  for_each   = var.environments
  name       = "${var.deployment}-dbt-docs-${each.value.name}"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "nginx"
  version    = "13.1.2"
  namespace  = local.core[each.value.name].namespace

  timeout       = 900
  wait_for_jobs = true

  set {
    name  = "service.type"
    value = "ClusterIP"
  }

  set {
    name  = "readinessProbe.enabled"
    value = "false"
  }

  set {
    name  = "customReadinessProbe.enabled"
    value = "true"
  }

  set {
    name  = "customReadinessProbe.initialDelaySeconds"
    value = "5"
  }

  set {
    name  = "customReadinessProbe.timeoutSeconds"
    value = "3"
  }

  set {
    name  = "customReadinessProbe.timeoutSeconds"
    value = "3"
  }

  set {
    name  = "customReadinessProbe.periodSeconds"
    value = "5"
  }

  set {
    name  = "customReadinessProbe.failureThreshold"
    value = "3"
  }

  set {
    name  = "customReadinessProbe.successThreshold"
    value = "1"
  }

  set {
    name  = "customReadinessProbe.httpGet.path"
    value = "/index.html"
  }

  set {
    name  = "customReadinessProbe.httpGet.port"
    value = "http"
  }
}
```

Error I get when I run terraform:

`│ Error: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe`

### What is the expected behavior?

mentioned above

### What do you see instead?

`│ Error: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe`

### Additional information

I'd like to set up a readiness probe with HTTP GET  instead of tcpSocket which is needed for google global load balancer.

**Comment by fmulero** [comment]
Hi @sreenivas-ps

Have you try removing this piece of code from your terraform file? You don't need it to enable the `customReadinessProbe`
```
set {
    name  = "customReadinessProbe.enabled"
    value = "true"
  }
```

**Comment by sreenivas-ps** [comment]
@fmulero : sorry for the late response but removing the piece of code you mentioned above worked. thanks.
