### ISSUE TITLE
MongoDB: replicaset architecture + external access, should Arbiter be advertised?

### ISSUE THREAD

**Issue by NMichas** [bitnami/charts#11222]
### Name and Version

bitnami/mongodb 12.1.26

### What steps will reproduce the bug?

I've setup a demo replicaset architecture enabling external access with LB. Everything works fine and I get my two "-external" services with their IPs assigned correctly. 

However, when I try to connect from my client (a Quarkus app, outside of my Kubernetes cluster) passing the IPs of the two "-external" services as the location of the MongoDB, it seems the address of the arbiter is also advertised back to the client. My application works, however my application's log is filled with:
![__dev-tag_sh](https://user-images.githubusercontent.com/2218296/179457796-a6a4d7f3-cce8-40e2-8220-b988f47c087d.png)

Is there a way to tell to the chart to not advertise the arbiter back to clients? If not, is there a way to disable the arbiter? Thanks!

### What do you see instead?

Error logs as indicated above.

**Comment by NMichas** [comment]
To disable the arbiter, just set: `arbiter.enabled=false`.

**Comment by rafariossaa** [comment]
Hi,
  I am not sure about the arbiter IP advertising. I am glad you found the way to disable the arbiter.
  In the case you want to use it, I would recommend you to ask this in mongoDB forums.
