### ISSUE TITLE
Support rack awareness (a.k.a. multiple availability zones)

### ISSUE THREAD

**Issue by janvanbesien-ngdata** [bitnami/charts#11226]
### Name and Version

bitnami/kafka 18.0.3

### What is the problem this feature will solve?

Deploying a Kafka cluster in multiple availability zones and correctly configuring kafka's rack awareness feature accordingly (cfr https://kafka.apache.org/documentation/#brokerconfigs_broker.rack). 

### What is the feature you are proposing to solve the problem?

For Kafka's rack awareness feature, we need to configure `broker.rack` in the broker configuration. To map this on availability zones, the value should correspond to the availability zone in which the pod is deployed. Given that this is not (always) known up front, it should be provided by a script on the pod (that obtains it from the k8s api).

This could all be built-in in bitnami/kafka, but I'm equally happy with configuration extension points that allow me to do it myself.

### What alternatives have you considered?

I tried to make it work as follows:

- `extraDeploy` (https://github.com/bitnami/charts/tree/master/bitnami/kafka#deploying-extra-resources) to deploy a custom configmap with a script that obtains the availability zone of the pod.
- `extraVolumes` and `extraVolumeMounts` to mount this script

`kafka-env.sh` has a feature to load environment values from a file, but not for KAFKA_CFG_BROKER_RACK_FILE. So that's where this approach breaks.

Directly setting KAFKA_CFG_BROKER_RACK does not work either, because the availability zone is only known after the pod is scheduled.

**Comment by migruiz4** [comment]
Hi @janvanbesien-ngdata,

I would have suggested that same approach, I'm glad you could find a solution that fulfilled your use case.

> This could all be built-in in bitnami/kafka, but I'm equally happy with configuration extension points that allow me to do it myself.
I'm not sure if this would be a feature we could add built into the bitnami/kafka image considering how the rack configuration needs may vary from one use case to another. 
If you would like to, feel free to send a PR at https://github.com/bitnami/bitnami-docker-kafka/ so we can discuss and evaluate it.

> but this is rather cumbersome and it feels like I am going way too deep under the hood of Bitnami's abstractions.
Your approach looks great to me and I really appreciate you shared it here so other users could benefit from it.
I don't see any inconvenience in using `kafka_server_conf_set`, which under the hood is simply a `sed` command with extra steps.

**Comment by janvanbesien-ngdata** [comment]
Thanks for your feedback. Is there a reason why kafka-env.sh does not have "broker.rack" as one of the settings it can load from a file (i.e. load environment variable KAFKA_CFG_BROKER_RACK from a file defined in KAFKA_CFG_BROKER_RACK_FILE)? I I think that would make it a bit cleaner already. I can make a PR for that.
