### ISSUE TITLE
affinity support for Kafka/Zookeeper Helm Charts

### ISSUE THREAD

**Issue by antimack** [bitnami/charts#1124]
Helm Chart: Kafka/Zookeeper

This is an improvement request.

For better fail tolerance in order to control and allocate Kafka/Zookeeper pods on a different nodes, it would be nice to have affinity support.

**Comment by tompizmor** [comment]
I implemented the changes in the PR https://github.com/bitnami/charts/pull/1129, once it is reviewed and merged you could start using it!

**Comment by tompizmor** [comment]
Done!
