### ISSUE TITLE
[bitnami/etcd] Multi replica cluster can't recover when all replicas fail

### ISSUE THREAD

**Issue by yanivoliver** [bitnami/charts#1125]
**Which chart**:
bitnami/etcd:2.2.2

**Description**
When the chart is deployed in a multi replica (with persistent storage) configuration it isn't able to recover when all of the replicas fail.
This scenario is critical when you encounter an infrastructure failure that causes all of the replica pods to fail simultaneously (e.g. all of the pods are scheduled on the same failing Kubernetes node).

**Steps to reproduce the issue:**
(This test was performed on AKS, but with replacing the storageClass below should reproduce in any Kubernetes environment)
1. helm install bitnami/etcd --set-string persistence.storageClass=managed-premium,statefulset.replicaCount=2
2. Wait for all of the replicas to come online
3. kubectl delete pod -l chart=etcd-2.2.2

**Describe the results you received:**
All of the pods enter a CrashLoopBackOff state.
Both replicas expect to be able to connect to the other. For example, the logs of the first replica:
```
>> kubectl get pods
NAME                    READY   STATUS             RESTARTS   AGE
dunking-rodent-etcd-0   0/1     CrashLoopBackOff   5          6m

>> kubectl logs dunking-rodent-etcd-0
==> The ID of the host is 0
==> Adding member to existing cluster.
client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.244.7.150:2379: connect: connection refused
; error #1: dial tcp: lookup dunking-rodent-etcd-1.dunking-rodent-etcd-headless.etcd-test.svc.cluster.local on 10.0.0.10:53: no such host
; error #2: http: no Host in request URL

>> kubectl get statefulsets
NAME                  DESIRED   CURRENT   AGE
dunking-rodent-etcd   2         1         17m
```

**Describe the results you expected:**
The etcd cluster to come back online successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tompizmor** [comment]
@yanivoliver I was able to reproduce the issue. We will take a deeper look and let you know once we have more information.

**Comment by materemias** [comment]
I had the same situation with 3 replicas. if all fail it gets in a loop not being able to recover

**Comment by yanivoliver** [comment]
@tompizmor Any update?

**Comment by tompizmor** [comment]
Hi @yanivoliver, I am afraid we couldn't find the time to work on this issue yet.
