### ISSUE TITLE
[mongodb] How can i create a database on a mongodb helm, k8s terraform?

### ISSUE THREAD

**Issue by guilherme-golaio** [bitnami/charts#11250]
### Name and Version

hashicorp/helm 2.5.1

### What steps will reproduce the bug?

I am on a GCP project using terraform and I deployed a mongo instance but I cant create a DB there. I saw the documentation, and I used this command:
```
 set {
    name  = "auth.databases"
    value = ["PPM"]
  }
````
And I getting this error:
```
Error: Incorrect attribute value type
│ 
│   on modules/k8s/mongodb/main.tf line 46, in resource "helm_release" "monogodb":
│   46:     value = ["PPM"]
│ 
│ Inappropriate value for attribute "value": string required.
```

Am I forgetting something? 

### Are you using any custom parameters or values?
```
set {
    name  = "auth.databases"
    value = ["PPM"]
  }
```

### What do you see instead?
```
 Error: Incorrect attribute value type
│ 
│   on modules/k8s/mongodb/main.tf line 46, in resource "helm_release" "monogodb":
│   46:     value = ["PPM"]
│ 
│ Inappropriate value for attribute "value": string required.
```
**then i tryed this:**
```
 set {
    name  = "auth.databases"
    value = "PPM"   
  }
```
**And now I am getting this error:**
```
│ Error: template: mongodb/templates/replicaset/statefulset.yaml:231:36: executing "mongodb/templates/replicaset/statefulset.yaml" at <include "mongodb.customDatabases" .>: error calling include: template: mongodb/templates/_helpers.tpl:156:21: executing "mongodb.customDatabases" at <.Values.auth.databases>: range can't iterate over PPMm
│ 
│   with module.k8s.module.mongodb.helm_release.monogodb,
│   on modules/k8s/mongodb/main.tf line 18, in resource "helm_release" "monogodb":
│   18: resource "helm_release" "monogodb" {
│ 
```

**Comment by javsalgar** [comment]
Hi!

Note that, according to the parameter list https://github.com/bitnami/charts/tree/master/bitnami/mongodb#mongodb-parameters, the `auth.databases` value should be an array, not a single value. Could you try using an array instead?

**Comment by guilherme-golaio** [comment]
`  set {
    name  = "auth.enabled"
    value = false
  }
  set {
    name = "auth.usernames[0]"
    value = "root"
  }
   set {
    name = "auth.passwords[0]"
    value = "root"
  }
  set {
    name = "auth.databases[0]"
    value = "PPM"
  }`
  
  
  i changed to this, the error disappeared but i still withou BD inside.
  i entered the pod, then i used "mongo" command and then "show dbs", mine still not there...

**Comment by menvol3** [comment]
Hi
I have mostly the same issue, but with  the helm values
As it says in values.yaml description I create a configuration like below, but after deploying it I have no custom user and custom DB..
Can someone please help?
``` YAML 
auth:
  rootUser: root
  rootPassword: qwert123
  usernames:
    - admin
  passwords:
    - admin123
  databases:
    - aadmin

**Comment by menvol3** [comment]
I have mostly the same issue, but with Helm
I’ve edited values file according to the comments in it, and it looks like below
After deploying i also can’t see any newly created custom user or database
``` yaml
auth:
  rootUser: root
  rootPassword: toor
  usernames:
    - admin
  passwords:
    - qwerty123
  databases:
    - aadmin

**Comment by javsalgar** [comment]
Hi,

Could you show the pod logs to see if there's anything meaningful? Also, could you try launching it with `image.debug=true`?

**Comment by menvol3** [comment]
Here is the log file, captured after deploying 

[mongo.log](https://github.com/bitnami/charts/files/9166941/mongo.log)


Also output of **show** commands
```
test> show users
[]
test> show dbs
admin   100.00 KiB
config   12.00 KiB
local    72.00 KiB
test>

**Comment by guilherme-golaio** [comment]
I tryed to create a DB on mongoCompass and i couldn 't too, dont know if i am doing something bad...

**Comment by javsalgar** [comment]
Hi,

I was not able to reproduce the issue. I tried this command and it worked using the values you provided

```
I have no name!@mongo-mongodb-6789bbc74c-x8sxw:/$ mongosh -u admin -p admin123 aadmin
Current Mongosh Log ID:	62de51e6718905ad032527b0
Connecting to:		mongodb://<credentials>@127.0.0.1:27017/aadmin?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.1
Using MongoDB:		5.0.9
Using Mongosh:		1.5.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

aadmin>
```

**Comment by guilherme-golaio** [comment]
My problem is solved, but sometimes i can use the DB, sometimes no, dont know why, but it already creates a BD, thank you

**Comment by javsalgar** [comment]
Thanks for letting us know!
