### ISSUE TITLE
AspNet-Core, add ExtraVolumeMounts as option for the Publish Init Container in the Clone from repo configuration

### ISSUE THREAD

**Issue by oliverkane** [bitnami/charts#11255]
### Name and Version

bitnami/aspnet-core latest

### What is the problem this feature will solve?

I have a .net application which during build time, requires a private nuget feed to get some paid-for dependencies (Hangfire Pro in this case). 

### What is the feature you are proposing to solve the problem?

I would like to be able to mount a custom NuGet.Config file into that container so that I may achieve this.  Currently there's no option to add extra volumes to that container, but there is for the git-clone container. I'm guessing this is an easy add.  I've created a fork with the relevant three lines added here:

### What alternatives have you considered?

hardcoding the credentials into the repository so that they don't need to be passed during runtime.  This is not ideal as that violates a principle we follow of not committing credentials into our source repos.

I have started a fork which has the relevant 3 lines added to make this change:
https://github.com/oliverkane/bitnami-charts/blob/master/bitnami/aspnet-core/templates/deployment.yaml#L100

This branch also contains updates to the ReadMe.md, and the values.yaml file.

**Comment by alemorcuq** [comment]
Hi, @oliverkane ! Would you like to create a PR adding this feature?

**Comment by oliverkane** [comment]
I would, though it may be a few weeks before I get around to doing this one.  Should I leave the Issue open if that's the case, or should I close and reopen when I get around to making a PR?

**Comment by alemorcuq** [comment]
We can leave it open. Worst case the stale bot will close it.
