### ISSUE TITLE
[bitnami/postgresql-ha] How to create custom database user with passwords

### ISSUE THREAD

**Issue by thangamani-arun** [bitnami/charts#11260]
### Name and Version

bitnami/postgresql-ha-9.2.0

### What is the problem this feature will solve?

There are no options to specify custom database usernames. If there are options to set custom username and password to access the database, the documentation is not very clear.

### What is the feature you are proposing to solve the problem?

Please provide configurable options in helm charts to set custom username and password for applications to consume.

**Comment by thangamani-arun** [comment]
Please note that this request is in addition to default `postgres` user.

**Comment by alemorcuq** [comment]
Is [this feature from the container](https://github.com/bitnami/containers/tree/main/bitnami/postgresql-repmgr#creating-a-database-user-on-first-run) the one you are looking for?

**Comment by thangamani-arun** [comment]
@alemorcuq: yes.
