### ISSUE TITLE
Alternative way of populating odoo.conf .

### ISSUE THREAD

**Issue by KamranValijonov** [bitnami/charts#11268]
### Name and Version

bitnami/odoo:15.0.20211010-debian-10-r14

### What is the problem this feature will solve?

odoo.conf file can be populated only via Values.yaml ? I need to populate more fields than the ones provided in Values.yaml. 

### What is the feature you are proposing to solve the problem?

How can I populate the fields of odoo.conf which are not present in Values.yaml of odoo chart ?

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
