### ISSUE TITLE
How can make mariadb galera cluster initialization faster?

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#11264]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

When I want to deploy 3 instance of mariadb-galera it takes 5 minutes to all pods get ready. What can I do to reduce this time?

### What is the feature you are proposing to solve the problem?

Reduce the time of running all pods of mariadb-galera cluster and it's initialization gets faster.

**Comment by javsalgar** [comment]
Hi,

That would depend on the platform you are using to initialize the solution. Please also note this solution has dependencies on other nodes so it would also take more time to get initialized. You can also try tweaking the probes in case they are too conservative. 

I will leave the ticket open in case someone from the community wants to participate as well.
