### ISSUE TITLE
[bitnami/thanos]: Receiver still can not start with no object store config

### ISSUE THREAD

**Issue by badrabubker** [bitnami/charts#11272]
### Name and Version

bitnami/thanos 11.1.2

### What steps will reproduce the bug?

*    install Thanos helm chart
*    Enable Thanos receiver
*    See the error

```
Error: secret "test-thanos-objstore-secret" not found
```

### Are you using any custom parameters or values?

```
    receive:
      enabled: true
```

### What is the expected behavior?

thanos receiver can start without the object store config file

### What do you see instead?

Error about missing secret

### Additional information

In #10995 we disabled the validation check for thanos receive to start without object store config, however when we start Thanos receive without `.Values.objstoreConfig` and  `.Values.existingObjstoreSecret`
In the deployment:

* https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L155-L159 Needs `thanos.objstoreSecretName`  which is defined here:  https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/_helpers.tpl#L43-L48

* Now since there is no `Values.existingObjstoreSecret` it will fall to the `else` condition and it will search for `{{- printf "%s-objstore-secret" (include "common.names.fullname" .) -}}` 

* that secret is defined in https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/objstore-secret.yaml
* The secret will be created only and only if 
```
{{- if (include "thanos.createObjstoreSecret" .) }}
```
* the condition is defined in: 
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/_helpers.tpl#L54-L58

* Since there are no  `.Values.objstoreConfig` the condition will not be met and the error will happen.

I will open a PR with a suggested solution

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will review it and provide feedback
