### ISSUE TITLE
Cannot edit DATABASE_HOST from envFrom secrets

### ISSUE THREAD

**Issue by filipprosovsky** [bitnami/charts#11277]
### Name and Version

bitnami/phpmyadmin 10.2.1

### What steps will reproduce the bug?

Using the flow to insert RDS host created in terraform, insert into parameter store resource and fetched using external-secrets which is being inserted using value attribute `extraEnvVarsSecret`. Key in secret is named DATABASE_HOST.

### Are you using any custom parameters or values?

extraEnvVarsSecret

### What is the expected behavior?

If db.host and other host spec values are empty, allow to bypass this `env` in deployment manifest and allow DATABASE_HOST env to be inserted from `envFrom`

### What do you see instead?

Due to precedence of `env` values taken, hardcoded DATABASE_HOST is rather empty - db.host and envFrom is not taken into consideration.

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpmyadmin#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
