### ISSUE TITLE
Zookeeper log messages show malformed connections from the readiness probe

### ISSUE THREAD

**Issue by rjemanuele** [bitnami/charts#1130]
**Which chart**:

bitnami/zookeeper

**Description**

The log messages contain many sequences such as this:
```
2019-04-09 04:58:12,368 [myid:6] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@215] - Accepted socket connection from /10.46.128.0:53334
2019-04-09 04:58:12,368 [myid:6] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@376] - Unable to read additional data from client sessionid 0x0, likely client has closed socket
2019-04-09 04:58:12,369 [myid:6] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1056] - Closed socket connection for client /10.46.128.0:53334 (no session established for client)
```
These connections without sessions are the Kubernetes readiness probes checking the process in order to include it in a Kubernetes Service.

**Steps to reproduce the issue:**

1. Install Zookeeper using the helm chart
2. Check the logs using `kubectl logs`

**Describe the results you received:**

See the Description above.

**Describe the results you expected:**

These extraneous message should not be in the log as they are noise and distract from actual , important log message.

**Potential Solution**

I would suggest doing something like this with an ncat or such.  https://stackoverflow.com/questions/29106546/how-to-check-if-zookeeper-is-running-or-up-from-command-prompt

Over ssl you could use ncat and stunnel to do the same test.

**Comment by rjemanuele** [comment]
Some of this was discussed in #1097 off-topic

**Comment by javsalgar** [comment]
Hi,

I agree that we should do something about it. I do not know if changing the readiness probe or maybe changing the log level. That's something we will need to investigate

**Comment by miguelaeh** [comment]
Hi @rjemanuele ,
I have done a new update on the image to support the log level, and the pull request to Chart. I put the log level on `ERROR` by default, so the readiness probes's logs will not appear, but the drawback is that only ERROR messages will be shown.
Link to the pull request: https://github.com/bitnami/charts/pull/1187

**Comment by carrodher** [comment]
I am closing this issue as it should be fixed in the mentioned PR, please reopen it if needed.
