### ISSUE TITLE
[bitnami/discourse] Add ability to specify Redis db number

### ISSUE THREAD

**Issue by maxpain** [bitnami/charts#11303]
### Name and Version

bitnami/discourse 8.0.1

### What is the problem this feature will solve?

I have one Redis deployment for all my workloads in the Kubernetes cluster, and I use different databases in this Redis deployment.
Currently, it is impossible to specify DB number in helm values (`externalRedis`).

### What is the feature you are proposing to solve the problem?

Add ability to specify `externalRedis.dbNumber` helm value.

**Comment by fmulero** [comment]
This Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
