### ISSUE TITLE
harbor-registry communication issue with AWS S3 with tls 1.3

### ISSUE THREAD

**Issue by ranjithkumar2106** [bitnami/charts#11314]
### Name and Version

[bitnami/Harbor] 

### What steps will reproduce the bug?

Deploying Harbor in a private EKS cluster with bitnami/harbor helm chart and storage end as AWS S3 bucket.

bitnami-docker-harbor-registry pod should communicate to s3 bucket with tls.

- Does this image support communicating to AWS S3 bucket with tls 1.3???
- Is there anything which i have to enable to configure the communication to S3 bucket with tls 1.3...

### What do you see instead?

When I disable tls 1.3 in s3, I was able to establish the communication as it should be. This is a security issue.

**Comment by javsalgar** [comment]
Hi,

As it can be seen here https://github.com/bitnami/bitnami-docker-harbor-registry/blob/master/2/debian-11/rootfs/opt/bitnami/scripts/harbor-registry/run.sh

```
#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace

# Load libraries
. /opt/bitnami/scripts/liblog.sh

readonly cmd=$(command -v registry)
readonly flags=("serve" "/etc/registry/config.yml" "$@")

info "** Starting Harbor Registry **"
exec "${cmd}" "${flags[@]}"

```

We just execute the command with the config.yml. In this sense, could you try checking the upstream documentation how the configuration should look like? https://goharbor.io/docs/1.10/install-config/configure-yml-file/
