### ISSUE TITLE
Error executing 'postInstallation': "size" argument must not be negative

### ISSUE THREAD

**Issue by cosieanalytics** [bitnami/charts#1131]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
```
Welcome to the Bitnami prestashop container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues
 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing prestashop
Error executing 'postInstallation': "size" argument must not be negative
```
**Steps to reproduce the issue:**

1. Install Prestashop with helm
2. Kill pod

**Describe the results you received:**

Pod won't restart

**Describe the results you expected:**

Pod should restart !

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Thanks

**Comment by juan131** [comment]
Hi @cosieanalytics 

I'm unable to reproduce your issue. These are the steps I followed

```bash
## Install chart
$ helm install stable/prestashop --name prestashop --set service.type=ClusterIP
## Wait until PrestaShop finishes the initialization
$ kubectl logs -f $(kubectl get pods -l app=prestashop -o jsonpath='{.items[0].metadata.name}')
...
nami    INFO  prestashop successfully initialized
INFO  ==> Starting prestashop...
...
## Kill Pod
$ kubectl delete pod $(kubectl get pods -l app=prestashop -o jsonpath='{.items[0].metadata.name}')
## Check the logs of the new pod
$ kubectl logs -f $(kubectl get pods -l app=prestashop -o jsonpath='{.items[0].metadata.name}')

Welcome to the Bitnami prestashop container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing prestashop
prestas INFO
prestas INFO  ########################################################################
prestas INFO   Installation parameters for prestashop:
prestas INFO     Persisted data and properties have been restored.
prestas INFO     Any input specified will not take effect.
prestas INFO   This installation requires no credentials.
prestas INFO  ########################################################################
prestas INFO
nami    INFO  prestashop successfully initialized
INFO  ==> Starting prestashop...
```

As you can check the new pod gets started without any issues.

**Comment by juan131** [comment]
Did you kill the pod before it finished initialising PrestaShop for the 1st time?

**Comment by cosieanalytics** [comment]
Hello,

no I didn't. Pod finished initialising prestashop for the first time. And it also had been successfully killed and restarted several times.

I am not able to reproduce each time.

But sometimes, when pod is killed, it is not able to restart from itself with the above mentionned error.

I can't confirm the following but it seems to happen when you have several pods running and all of them are killed at the same time.

**Comment by cosieanalytics** [comment]
Basically, it seems to happen randomly upon killing the pod.
It will never restart if it fails once.

Only edits which were done:
php.ini in /opt/bitnami/etc/
php.ini in /opt/bitnami/lib/
prestashop-htaccess.conf in /opt/bitnami/apache/conf/vhosts/htaccess/
Plus some theme customisation and modules installations.
(php.ini changes never reflect after pod restart by the way.)

Any clue where I can find this: 'postInstallation': "size" argument

Thank you

**Comment by juan131** [comment]
That's very weird.. Could you set the env. variable **NAMI_DEBUG** to **--log-level=trace** to increase the verbosity of the logs? We might get more information about the error you're facing.

Just edit the PrestaShop deployment (container's env. section) and add the env. variable:

```yaml
       env:
       - name: NAMI_DEBUG
         value: "--log-level=trace"
```

**Comment by cosieanalytics** [comment]
Sorry, I was on Holidays but my team still had the issue several times.

I will do this as soon as I can:
       env:
       - name: NAMI_DEBUG
         value: "--log-level=trace"

thank you !

**Comment by juan131** [comment]
Thanks @cosieanalytics 
Please share the logs once you have them!

**Comment by zccrs** [comment]
> Thanks @cosieanalytics
> Please share the logs once you have them!

➜  Docker docker-compose logs --tail=100 -f phabricator
WARNING: Some networks were defined but are not used by any service: custom
Attaching to docker_phabricator_1
phabricator_1  | app-entrypoint.sh 02:34:41.84
phabricator_1  | app-entrypoint.sh 02:34:41.86 Welcome to the Bitnami phabricator container
phabricator_1  | app-entrypoint.sh 02:34:41.87 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
phabricator_1  | app-entrypoint.sh 02:34:41.87 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
phabricator_1  | app-entrypoint.sh 02:34:41.87
phabricator_1  | nami    INFO  Initializing php
phabricator_1  | php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/tmp"]
phabricator_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/tmp
phabricator_1  | php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
phabricator_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
phabricator_1  | php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
phabricator_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
phabricator_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
phabricator_1  | php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
phabricator_1  | nami    INFO  php successfully initialized
phabricator_1  | nami    INFO  Initializing apache
phabricator_1  | nami    INFO  apache successfully initialized
phabricator_1  | nami    INFO  Initializing phabricator
phabricator_1  | phabric INFO  Creating Phabricator system users...
phabricator_1  | phabric TRACE [runProgram] Executing: usermod -p,*,git
phabricator_1  | phabric TRACE [configurePermissions] File to chown: /home/phabricator
phabricator_1  | phabric TRACE [configurePermissions] File to chmod: /home/phabricator
phabricator_1  | phabric INFO  Creating Phabricator temporary folders...
phabricator_1  | apache  TRACE Skipping reload: com.bitnami.apache not running
phabricator_1  | apache  TRACE [runProgram] Executing: null /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
phabricator_1  | Error executing 'postInstallation': "size" argument must not be negative
phabricator_1  | nami    TRACE RangeError: Error executing 'postInstallation': "size" argument must not be negative
phabricator_1  |     at Function.Buffer.alloc (buffer.js:233:3)
phabricator_1  |     at new Buffer (buffer.js:156:19)
phabricator_1  |     at FileReader.read (/opt/bitnami/nami/node_modules/nami-utils/lib/file/FileReader.js:53:20)
phabricator_1  |     at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:151:50)
phabricator_1  |     at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
phabricator_1  |     at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
phabricator_1  |     at Service.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
phabricator_1  |     at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
phabricator_1  |     at ApacheHandler.start (/root/.nami/components/com.bitnami.phabricator/lib/handlers/webservers/apache/index.js:66:23)
phabricator_1  |     at Service.$app.postInstallation (/root/.nami/components/com.bitnami.phabricator/main.js:47:20)
docker_phabricator_1 exited with code 1

**Comment by juan131** [comment]
That looks like an issue starting Apache server probably related with lack of memory:

```
phabricator_1  |     at Function.Buffer.alloc (buffer.js:233:3)
```

Did you set any value for the `resources` parameter or are you using the default one? As you can see [here](https://github.com/bitnami/charts/blob/master/bitnami/phabricator/values.yaml#L215) the default values are:

```yaml
resources:
  requests:
    memory: 512Mi
    cpu: 300m
```

You might need to increase a little bit the requested memory.
