### ISSUE TITLE
[bitnami/redis-cluster] Unable to connect through external-ip and port in redis-cluster helm chart

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#11336]
### Name and Version

bitnami/redis-cluster , 7.1.0

### What steps will reproduce the bug?

helm install redis redis-cluster

### Are you using any custom parameters or values?

cluster.externalaccess.enabled=true

### What is the expected behavior?

i should be able to connect through the external ips which i am getting .
![Screenshot from 2022-07-25 15-25-27](https://user-images.githubusercontent.com/68244292/180750460-0568e581-7da2-48c8-b475-3d99507d12c6.png)

### What do you see instead?

i am able to connect to servic eof type node port by using redis-cli
(redis-cli -c -a password -h ip of machine -p nodeport)
 But when i tried using the same thing with external ip provided and nodeport using same above command, it is not connected.
![Screenshot from 2022-07-25 15-29-07](https://user-images.githubusercontent.com/68244292/180751096-78fbfad0-458b-44cc-b8e5-6b3142c1ed4a.png)

**Comment by abhishekgupta2205** [comment]
i need to know why it is not connecting and if we cant connect to it then what is its purpose(external ip)

**Comment by fmulero** [comment]
Hi @abhishekgupta2205 

Once you have the external IPs for the load balancers you have to upgrade your helm release with those ips as it is explained in the [documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology). If you are using helm to deploy the chart you can also see this message (please be aware about the camelCase in the name of the value `cluster.externalAccess.enabled`):

```console
$ helm install rc bitnami/redis-cluster --set cluster.externalAccess.enabled=true
NAME: rc
LAST DEPLOYED: Tue Jul 26 19:07:05 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: redis-cluster
CHART VERSION: 8.1.1
APP VERSION: 7.0.4** Please be patient while the chart is being deployed **


To get your password run:
    export REDIS_PASSWORD=$(kubectl get secret --namespace "default" rc-redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis&reg; server from outside the cluster check the following information:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w rc-redis-cluster'

    You will have a different external IP for each Redis&reg; node. Get the external ip from `-external` suffixed services: `kubectl get svc`.
    Redis&reg; port: 6379
    Once the LoadBalancerIPs are ready, you need to provide them and perform a Helm Upgrade:

    helm upgrade --namespace default rc --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=load-balancerip-0,cluster.externalAccess.service.loadBalancerIP[1]=load-balancerip-1,cluster.externalAccess.service.loadBalancerIP[2]=load-balancerip-2,cluster.externalAccess.service.loadBalancerIP[3]=load-balancerip-3,cluster.externalAccess.service.loadBalancerIP[4]=load-balancerip-4,cluster.externalAccess.service.loadBalancerIP[5]=load-balancerip-5" bitnami/redis-cluster
    Where loadbalancer-ip-i are the LoadBalancerIPs provided by the cluster.
```

**Comment by abhishekgupta2205** [comment]
i have already upgraded and pods are created . BUt when i tried to connect to one of the pods using its craeted external-ip and port as described above , the connection is refused. how to solve it

**Comment by abhishekgupta2205** [comment]
@fmulero please reply
