### ISSUE TITLE
[bitnami/redis] Redis best practices

### ISSUE THREAD

**Issue by gustavo-montero** [bitnami/charts#11346]
### Name and Version

bitnami/redis 16.6.0

### What is the problem this feature will solve?

I am looking for Redis Cluster best practices with multiple microservices in K8s (sitting on AWS EKS) that don't end up creating tons of Redis namespaces and/or clusters in a single environment (dev, staging, prod). Any suggestions on how to deal with this?

We want to avoid having multiple Redis clusters shared by tons of microservices to potentially avoid collisions (if any?).

What are the Redis cluster best practices in a microservices architecture?

### What is the feature you are proposing to solve the problem?

Trying to get feedback, suggestions and best practices used in the market.

**Comment by rafariossaa** [comment]
Hi,
  For this kind of questions I would suggest you to ask better in redis forums, I think they could provide a better answer to architectural design of solutions based on redis.
