### ISSUE TITLE
Restarting a shutdown cluster results in :0@0 noaddr

### ISSUE THREAD

**Issue by avcad** [bitnami/charts#11341]
### Name and Version

bitnami/redis-cluster:7.0.3

### What steps will reproduce the bug?

We are running tests on GCP with the bitnami/redis-cluster helm chart.  3 masters + 3 replicas. To save on resources we scale down the redis deployment when done testing, and scale back again when needed.

Every few days we find clusters that don't come back properly, with some nodes showing `:0@0 noaddr` for other nodes. This only impacts some nodes.  We then run CLUSTER MEET and the system comes back to normal.

It appears to be a timing issue.  Maybe similar to this? https://github.com/bitnami/containers/issues/1013

Do you have any suggestions for how to avoid this situation? I am concerned that if there is a node crash in production, the same can happen. I am not sure what the best solution is, but the idea is to avoid manual intervention.  Maybe by scheduling a cluster meet command? 

```
NAME 	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART              	APP VERSION
redis	redisc   	1       	2022-07-18 10:57:38.3297352 -0400 EDT	deployed	redis-cluster-8.1.0	7.0.3      
NAME                  READY   AGE     CONTAINERS                    IMAGES
redis-redis-cluster   6/6     6d22h   redis-redis-cluster,metrics   docker.io/bitnami/redis-cluster:7.0.3-debian-11-r1,docker.io/bitnami/redis-exporter:1.43.0-debian-11-r7
```

### What do you see instead?

Example:
```
redis-redis-cluster-0 - cluster nodes 
-------------------------------------------------
1291205ab764376342e18550ed619fa0400be4ad 127.0.0.4:6379@16379 slave e839a12fbed631de867016f636d773e644562e72 0 1658755604426 1 connected
752d150249c157c7cb312b6b056517bbbecb42d2 :0@0 master,noaddr - 1658754833817 1658754833000 3 disconnected 5461-10922
e839a12fbed631de867016f636d773e644562e72 127.0.0.0:6379@16379 myself,master - 0 1658755601000 1 connected 0-5460
87f785c4a51f58c06e4be55de8c112210a811db9 127.0.0.2:6379@16379 master - 0 1658755602418 3 connected 10923-16383
9c5408cd24ae29f7eb001f9d6b8d14393fc94cd0 127.0.0.5:6379@16379 slave 752d150249c157c7cb312b6b056517bbbecb42d2 0 1658755602000 3 connected
0cbf9724182aa0cbfa8f97b848b6cc7d75018a27 127.0.0.3:6379@16379 slave 87f785c4a51f58c06e4be55de8c112210a811db9 0 1658755603421 3 connected

redis-redis-cluster-1 - cluster nodes 
-------------------------------------------------
9c5408cd24ae29f7eb001f9d6b8d14393fc94cd0 127.0.0.5:6379@16379 slave 752d150249c157c7cb312b6b056517bbbecb42d2 0 1658755613873 2 connected
1291205ab764376342e18550ed619fa0400be4ad 127.0.0.4:6379@16379 slave e839a12fbed631de867016f636d773e644562e72 0 1658755612870 2 connected
0cbf9724182aa0cbfa8f97b848b6cc7d75018a27 127.0.0.3:6379@16379 slave 87f785c4a51f58c06e4be55de8c112210a811db9 0 1658755611866 3 connected
87f785c4a51f58c06e4be55de8c112210a811db9 127.0.0.2:6379@16379 master - 0 1658755611000 3 connected 10923-16383
e839a12fbed631de867016f636d773e644562e72 :0@0 master,noaddr - 1658754834117 1658754833851 2 disconnected 0-5460
752d150249c157c7cb312b6b056517bbbecb42d2 127.0.0.1:6379@16379 myself,master - 0 1658755612000 2 connected 5461-10922
```

**Comment by avcad** [comment]
[noaddr.zip](https://github.com/bitnami/charts/files/9185326/noaddr.zip)

attached complete log include .sh used to gather the data. 

IPs were changed

**Comment by javsalgar** [comment]
Hi!

In order for us to reproduce the issue, do you have any steps that consistently lead to the issue?

**Comment by avcad** [comment]
Hi @javsalgar, Thanks!

It's not easy to reproduce. 
Starting with a working cluster we scale down the statefulset and then the Kubernetes nodes.  

kubectl scale statefulset.apps/redis-redis-cluster -n redis --replicas=0
gcloud container clusters resize perf-cluster-1 --num-nodes=0 --zone us-east1-b --node-pool redis-pool --project redis-test --quiet

We re-start 4 environments daily and the issue happens maybe once every week or two weeks.  Except for noaddr, the environment is OK and CLUSTER MEET fixes it. 

I used the script I uploaded earlier to collect as much info from the environment as possible. If you can think of other troubleshooting steps I can follow, I'll be glad to.

**Comment by carrodher** [comment]
I was trying to reproduce the issue but had no luck, it is going to be difficult to reproduce on our side.
You can use the `image.debug=true` value just in case it helps. With this value, the verbosity of the container logs is increased just in case you can see any hint about what's happening.

**Comment by avcad** [comment]
Thanks! I restarted 100 times and I couldn't reproduce, but then it happened the next day.
We'll enable image.debug.true.

**Comment by avcad** [comment]
The problem happened again a few more times. Now I am waiting to reproduce with logLevel debug in Redis, but it might take some time 'cos I can only enable in one environment.  If you have other suggestions, let me know. thanks!

**Comment by avcad** [comment]
@carrodher I think I see the issue (bug)

This is the state after startup:

MASTER:  redis-redis-cluster-0 - b35eada340744aea2f77d5321f64dbbaa7fc3e8f 10.232.1.5
  SLAVE: redis-redis-cluster-4 - c14828669353c96da41018363cbcc798dca4f7ff 10.232.3.8
MASTER:  redis-redis-cluster-1 - e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5
  SLAVE: redis-redis-cluster-5 - 506b69c81e72f08058e51950c8ffec6ea11b4277 10.232.1.4
MASTER:  redis-redis-cluster-2 - 40dc089f51077fa7a91e0b2b4c5e971635a5911d 10.232.0.5
  SLAVE: redis-redis-cluster-3 - fb1db6513b754fc16bf58def9db4f53f9df46ab4 10.232.2.4

Running cluster nodes on each server shows that redis-redis-cluster-0 doesn't see 1 and 1 doesn't see 0

cluster nodes from redis-redis-cluster-0 has:
 e464641fe273428413e1bb7c5fcfaedad2a6f9ee :0@0 master,noaddr - 1661952523302 1661952522311 3 disconnected 5461-10922

cluster nodes from redis-redis-cluster-1 has:
b35eada340744aea2f77d5321f64dbbaa7fc3e8f :0@0 master,noaddr - 1661952523165 1661952522000 3 disconnected 0-5460

This is the trace form cluster-0. Gossip is returning the right IP for cluster-1, but the server has originally a different IP, 
1:M 31 Aug 2022 13:28:42.797 - Connection wth Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:43.352 . PONG contains mismatching sender ID. About node e464641fe273428413e1bb7c5fcfaedad2a6f9ee added 1041 ms ago, having flags 257
....
GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master

I think the problem is here 
(https://github.com/bitnami/bitnami-docker-redis-cluster/blob/9516094a9c7297b6bbba8fbb16bbd2a1fe838ac4/7.0/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh#L206)

The script is correctly updating the IP here
Changing old IP 10.232.0.5 by the new one 10.232.4.5
but  then it changes it back
Changing old IP 10.232.4.5 by the new one 10.232.3.8

I am not sure if we can expect each node to be on a specific line and then sed update that line only?

-------------------
Changing old IP 10.232.2.7 by the new one 10.232.1.5
Changing old IP 10.232.0.5 by the new one 10.232.4.5
Changing old IP 10.232.3.5 by the new one 10.232.0.5
Changing old IP 10.232.1.5 by the new one 10.232.2.4
Changing old IP 10.232.4.5 by the new one 10.232.3.8
Changing old IP 10.232.3.6 by the new one 10.232.1.4

1:M 31 Aug 2022 13:28:42.694 - Connection with Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:42.722 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.3.8:6379@16379 master
1:M 31 Aug 2022 13:28:42.797 - Connection wth Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:42.898 - Connection with Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:42.999 - Connection with Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:43.100 - Connection with Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:43.201 - Connection with Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379 failed: Connection refused
1:M 31 Aug 2022 13:28:43.302 . Connecting with Node e464641fe273428413e1bb7c5fcfaedad2a6f9ee at 10.232.3.8:16379
1:M 31 Aug 2022 13:28:43.352 . pong packet received: e464641fe273428413e1bb7c5fcfaedad2a6f9ee
1:M 31 Aug 2022 13:28:43.352 . PONG contains mismatching sender ID. About node e464641fe273428413e1bb7c5fcfaedad2a6f9ee added 1041 ms ago, having flags 257
1:M 31 Aug 2022 13:28:43.451 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master
1:M 31 Aug 2022 13:28:45.276 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master
1:M 31 Aug 2022 13:28:45.730 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master
1:M 31 Aug 2022 13:28:46.028 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master
1:M 31 Aug 2022 13:28:46.074 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master
1:M 31 Aug 2022 13:28:46.630 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master
1:M 31 Aug 2022 13:28:47.636 . GOSSIP e464641fe273428413e1bb7c5fcfaedad2a6f9ee 10.232.4.5:6379@16379 master

**Comment by avcad** [comment]
maybe something like this?

        for node in "${nodes[@]}"; do
            newIP=$(wait_for_dns_lookup "$node" "$REDIS_DNS_RETRIES" 5)
            # The node can be new if we are updating the cluster, so catch the unbound variable error
            if [[ ${host_2_ip_array[$node]+true} ]]; then
                echo "Changing old IP ${host_2_ip_array[$node]} by the new one ${newIP}"
                nodesFile=$(sed "s/ ${host_2_ip_array[$node]}:/ $newIP<NEWIP>:/g" "${REDIS_DATA_DIR}/nodes.conf")
                echo "$nodesFile" >"${REDIS_DATA_DIR}/nodes.conf"
            fi
            host_2_ip_array["$node"]="$newIP"
        done
		
	sed -i "s/<NEWIP>//g" "${REDIS_DATA_DIR}/nodes.conf

**Comment by carrodher** [comment]
Thanks for the research, would you like to contribute by creating a PR implementing that fix? The team will be happy to review it and provide feedback
