### ISSUE TITLE
Missing upgrade notes on Redis 17.x

### ISSUE THREAD

**Issue by juan131** [bitnami/charts#11357]
### Name and Version

bitnami/redis 17.x

### What steps will reproduce the bug?

Visit the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/redis#upgrading

The instruction to upgrade from `16.x` to `17.x` are missing.

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

Upgrading notes should be provided since there was a major version bump including a major version bump in Redis (from `6.x` series to `7.x`), see:

- https://github.com/bitnami/charts/commit/a1e0d3bd4075eb95bb5796183580ff0f5dd430ac

### What do you see instead?

No instructions.

### Additional information

N/A

**Comment by FraPazGal** [comment]
Hi @juan131!

There are instances where there is no breaking change between majors and we do not add new entries to the upgrading notes, as a simple `helm upgrade` suffices. I briefly checked this case and I could upgrade the chart to the new major without issues. 

Have you encountered any breaking changes between these 2 majors?

**Comment by juan131** [comment]
If that's the case, then I expect the README.md to contain that specific information, see WildFly for instance:

- https://github.com/bitnami/charts/tree/master/bitnami/wildfly#to-1000

As a user, I want to know that's safe to upgrade.

**Comment by FraPazGal** [comment]
Hi @juan131,

Thanks for the feedback, I do understand your concerns with this. Unfortunately, our current automated release process doesn't contemplate adding such entries and thus requires manual input from our devs via PRs. With the objective of not blocking new major releases, we prefer not to have as a requisite manually adding an entry in the upgrades for non-breaking upgrades.

Having said that, we will try to revisit this in the future to avoid confusion regarding non-breaking major upgrades.

**Comment by juan131** [comment]
> Unfortunately, our current automated release process doesn't contemplate adding such entries and thus requires manual input from our devs via PRs. With the objective of not blocking new major releases, we prefer not to have as a requisite manually adding an entry in the upgrades for non-breaking upgrades.

Does your automated release process handle **major** upgrades without any human intervention? Do you wake up one morning and you find that Redis chart was bumped to a new major because your system detected there's a new Redis major version?

> Having said that, we will try to revisit this in the future to avoid confusion regarding non-breaking major upgrades.

Honestly, I don't understand what's the issue here @FraPazGal ... Here are my points:

1. I expect that Bitnami, as software provider, provides some changelog or release notes or upgrade notes (name it as you prefer), so users understand what implies to upgrade chart releases to newest versions. **Specially when there are changes in the chart that implied bumping the major version**. This is not asking for a crazy feature, this is basically the standard of the software industry.
2. The previous point is even more important on "infrastructure" charts such as Redis that are used as subcharts on many other charts.
3. There's no mention in the chart's readme(s) nor Bitnami docs site that says "if we don't add upgrade notes, assume you can safely upgrade".
4. You're not being consistent across the catalog. In my previous response I shared a link to WildFly upgrade notes where it says "upgrading from version `9.x.x` should be possible without any extra required step (...)". Why do you include them for WildFly and you don't do it for Redis?
5. Please please please **put yourself in the users shoes**: you detect Bitnami released a new major version, you need to decide whether to upgrade your production workloads that use that chart and **you find there's nothing** in the upgrade notes to help you decide whether it's safe to upgrade or not. Terrible UX.

**Comment by juan131** [comment]
Friendly reminder @FraPazGal

**Comment by FraPazGal** [comment]
Hello @juan131,

> Does your automated release process handle major upgrades without any human intervention? Do you wake up one morning and you find that Redis chart was bumped to a new major because your system detected there's a new Redis major version?

I think you misunderstood my words. There is manual intervention when releasing a new major version but there is minimal input for Chart releases. With the objective of minimizing that intervention, we are currently following the explained workflow.

As I said, even though we currently do not have the capacity to change our approach we'll try to revisit it in the future. In any case, these upgrade notes could always be added retroactively if necessary as done for Redis [17.x](https://github.com/bitnami/charts/tree/master/bitnami/redis#to-1700).

**Comment by juan131** [comment]
Closing this issue since it was solved at https://github.com/bitnami/charts/pull/11710

> There is manual intervention when releasing a new major version but there is minimal input for Chart releases. With the objective of minimizing that intervention, we are currently following the explained workflow.
> As I said, even though we currently do not have the capacity to change our approach we'll try to revisit it in the future.

I understand the benefits for Bitnami in terms of saving costs. That said, IMHO Bitnami, as a popular OSS provider, should also understand that providing a changelog/release notes/upgrade notes is a basic standard of software industry that you're failing to accomplish given your current approach. This is just my feedback.
