### ISSUE TITLE
[bitnami/keycloak] Proxy mode

### ISSUE THREAD

**Issue by roderik** [bitnami/charts#11358]
### Name and Version

bitnami/keycloak 9.6.0

### What steps will reproduce the bug?

1. kind cluster
2. nginx ingress with ssl termination

### Are you using any custom parameters or values?
```
proxy: edge
```
### What is the expected behavior?

Keycloak should be configured to run in edge mode.
This makes the URL's used to be https and not http

### What do you see instead?

```
2022-07-26 14:31:08,734 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: 
<request>, Port: -1, Proxied: false  
```

proxied should be true

### Additional information

I tried literally everything until I figured out that setting proxy to edge, sets an env var `KEYCLOAK_PROXY` to edge.
All good so far, except, this is not the env var Keycloak is looking for, that should be `KC_PROXY`

A workaround is setting the following

```yaml
  extraEnvVars:
    - name: KC_PROXY
      value: edge
```

**Comment by migruiz4** [comment]
Hi @roderik,

When using the image `bitnami/keycloak` correct env variable is `KEYCLOAK_PROXY`. 
I'm sorry for the inconvenience, we have not updated all of our env variables to match the upstream after the Quarkus update.

In case it helps you, the proxy mode can also be configured by using the `proxy` value instead of `extraEnvVars`.

**Comment by migruiz4** [comment]
Using the latest version of the chart, I haven't been able to reproduce the issue:
```
$ helm install test bitnami/keycloak --set proxy=edge
...
$ kubectl logs test-keycloak-0
...
2022-07-26 15:04:16,701 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
...
```

**Comment by roderik** [comment]
Oh, I am using the ARM build from https://github.com/ZCube/bitnami-compat

It patches the docker file like this https://github.com/ZCube/bitnami-compat/blob/main/patches/keycloak/18.0/docker/Dockerfile.install but I guess https://github.com/bitnami/bitnami-docker-keycloak/blob/e7b46bcd1839e96d7afb9842231b6f4fc5be1b1c/18/debian-11/Dockerfile#L15 is a custom version of Keycloak?

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support. The repo and the image you mention are not developed nor supported by Bitnami.

We will close the rest of the existing issues related to ARM just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
