### ISSUE TITLE
[bitnami/mysql] The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable

### ISSUE THREAD

**Issue by johnnylei** [bitnami/charts#11369]
### Name and Version

bitnami/mysql:9.2.0

```
$ kubectl get pods -nmysql
mysql-0   0/1     CrashLoopBackOff   6          10m
```

```
$ kubectl logs -f -nmysql mysql-0
mysql 07:58:40.01 
mysql 07:58:40.02 Welcome to the Bitnami mysql container
mysql 07:58:40.02 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 07:58:40.02 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 07:58:40.02 
mysql 07:58:40.03 INFO  ==> ** Starting MySQL setup **
mysql 07:58:40.04 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 07:58:40.07 INFO  ==> Initializing mysql database
mysql 07:58:40.08 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. 
Configurations based on environment variables will not be applied for this file.
mysql 07:58:40.08 INFO  ==> Using persisted data
mysql 07:58:40.18 INFO  ==> Running mysql_upgrade
mysql 07:58:40.19 INFO  ==> Starting mysql in background
```

```
# descibe pods
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              13m                default-scheduler  Successfully assigned mysql/mysql-0 to 172.16.10.248
  Normal   SuccessfulMountVolume  12m (x2 over 12m)  kubelet            Successfully mounted volumes for pod "mysql-0_mysql(69034ae6-c804-4b91-af8d-a902ac508e55)"
  Normal   Killing                12m                kubelet            Container mysql failed liveness probe, will be restarted
  Normal   Pulled                 11m (x2 over 12m)  kubelet            Container image "docker.io/bitnami/mysql:8.0.29-debian-11-r9" already present on machine
  Normal   SuccessfulCreate       11m (x2 over 12m)  kubelet            Created container mysql
  Normal   Started                11m (x2 over 12m)  kubelet            Started container mysql
  Warning  Unhealthy              11m                kubelet            Readiness probe errored: rpc error: code = Unknown desc = container not running (ba1719de7bbad8b19db29805d72b12fc58278f566b868b8d79b1e57beec9a233)
  Warning  Unhealthy              11m (x6 over 12m)  kubelet            Liveness probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
  Warning  Unhealthy  7m55s (x30 over 12m)  kubelet  Readiness probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
  Warning  BackOffStart  2m43s (x18 over 6m55s)  kubelet  the failed container exited with ExitCode: 137
```

**Comment by fmulero** [comment]
Hi @johnnylei

Have you tried with latest version (9.2.2)? Could you share the values that you are using for your release?

**Comment by maxisam** [comment]
having the same issue with 9.4.4

**Comment by fmulero** [comment]
Could you share your `values.yaml` file or any information about how did you deploy the chart? We are not able to reproduce the issue with the information provided

**Comment by carrodher** [comment]
Bitnami containers are non-root by default, which means any file/dir used by the application should belong to the _root_ group since the random user (_1001_ by default) is part of this _root_ group. You should adapt the permission of your local directory so the _root_ group is the owner.

You can find more info about non-root containers at
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

**Comment by javsalgar** [comment]
Hi,

It seems to me that there could be permission issues due to the longhorn storage class, could you try enabling the `volumePermissions` init container?

**Comment by udf2457** [comment]
Happy to give `volumePermissions` container a go @javsalgar but I'm confused as to why it (might) be needed ? 

Surely you shoud be setting:

```
securityContext:
  fsGroup: x
```

On then actual underlying containers instead instead of relying on an (optional?) init container ?  My understanding is that with `fsGroup` set, the chmod is set for you ?  That's certainly been the results of my own experiments wth Kubernetes ?

From https://kubernetes.io/docs/tasks/configure-pod-container/security-context/:
> Kubernetes recursively changes ownership and permissions for the contents of each volume to match the fsGroup specified in a Pod's securityContext when that volume is mounted.

**Comment by javsalgar** [comment]
The thing is that not all StorageClasses are compatible with the `fsGroup` option, for example nfs. Therefore, we need to rely on the init container when the Storage Class does not work with the `fsGroup` setting.

**Comment by zerowebcorp** [comment]
Just encountered this issue. I use longhorn as well. I tried enabling the volumePermission init container and I can see it did the chmod, however the pod is in continuous restart loop.

```
helm upgrade --install mysql --set auth.rootPassword="secretPassword"  \
  --set auth.createDatabase=true \
  --set auth.database="sample" \
  --set primary.persistence.size="2Gi" \
  --set secondary.persistence.size="2Gi" \
  --set image.debug="true" \
  --set volumePermissions.enabled="true" \
  oci://registry-1.docker.io/bitnamicharts/mysql
```


```
mysql 20:39:29.42 INFO  ==> 
mysql 20:39:29.43 INFO  ==> Welcome to the Bitnami mysql container
mysql 20:39:29.43 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 20:39:29.43 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 20:39:29.43 INFO  ==> 
mysql 20:39:29.43 DEBUG ==> Copying files from /opt/bitnami/mysql/conf.default to /opt/bitnami/mysql/conf
mysql 20:39:29.44 INFO  ==> ** Starting MySQL setup **
mysql 20:39:29.45 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 20:39:29.46 INFO  ==> Initializing mysql database
mysql 20:39:29.46 DEBUG ==> Ensuring expected directories/files exist
mysql 20:39:29.47 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 20:39:29.47 INFO  ==> Using persisted data
mysql 20:39:29.50 INFO  ==> Running mysql_upgrade
mysql 20:39:29.50 INFO  ==> Starting mysql in background
```

**Comment by javsalgar** [comment]
Could you launch it with `diagnosticMode.enabled=true`, enter the container and try running this command?

```
/opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh
```

This should help you to find the cause of the issue

**Comment by bhagyesh1** [comment]
mysql 17:34:40.91 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
mysql 17:34:40.91 INFO  ==> 
mysql 17:34:40.92 INFO  ==> ** Starting MySQL setup **
mysql 17:34:40.95 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 17:34:40.96 INFO  ==> Initializing mysql database
mysql 17:34:40.99 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 17:34:41.01 INFO  ==> Using persisted data
mysql 17:34:41.06 INFO  ==> Running mysql_upgrade
mysql 17:34:41.08 INFO  ==> Starting mysql in background
2024-11-07T17:34:41.116830Z 0 [System] [MY-015015] [Server] MySQL Server - start.
2024-11-07T17:34:41.430109Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.4.0) starting as process 42
2024-11-07T17:34:41.435890Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2024-11-07T17:35:16.020585Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.

**Comment by skyler** [comment]
This is happening to me as well in MySQL version 8.4.3. I can also reproduce it in 8.4.4 (and I'd like to stay in 8.x). Starting the container with diagnostic mode enabled, I run the requested command and get the following (abbreviated) logs:

```sh
$ /opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh
mysql 03:39:41.01 INFO  ==>
mysql 03:39:41.02 INFO  ==> Welcome to the Bitnami mysql container
mysql 03:39:41.04 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 03:39:41.05 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 03:39:41.06 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
mysql 03:39:41.07 INFO  ==>
mysql 03:39:41.08 DEBUG ==> Copying files from /opt/bitnami/mysql/conf.default to /opt/bitnami/mysql/conf
mysql 03:39:41.11 INFO  ==> ** Starting MySQL setup **
mysql 03:39:41.28 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 03:39:41.33 INFO  ==> Initializing mysql database
mysql 03:39:41.37 DEBUG ==> Ensuring expected directories/files exist
mysql 03:39:41.48 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 03:39:41.49 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 03:39:41.51 INFO  ==> Installing database
mysql 03:40:00.54 INFO  ==> Starting mysql in background
```

I didn't copy the output of my database creation, the run of my init scripts, etc.

I'm running this in k3s using the "local-path" storage class with Helm chart version 12.2.1. Prior to copying these logs, I deleted the MySQL container's PVC: This is a fresh run on an empty volume.

I see that this issue was closed. Is it resolved in an unlinked change?

**Comment by frankieci** [comment]
This is happening to me in  MySQL version 8.4.5, the StorageClasse is nfs, log such as:
```
$ kubectl logs -f mysql-0
mysql 02:59:34.16 INFO  ==> 
mysql 02:59:34.17 INFO  ==> Welcome to the Bitnami mysql container
mysql 02:59:34.17 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 02:59:34.17 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
mysql 02:59:34.17 INFO  ==> 
mysql 02:59:34.17 INFO  ==> ** Starting MySQL setup **
mysql 02:59:34.19 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 02:59:34.19 INFO  ==> Initializing mysql database
mysql 02:59:34.20 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 02:59:34.21 INFO  ==> Installing database
2025-05-07T02:59:34.225616Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start.
2025-05-07T02:59:34.227010Z 0 [System] [MY-013169] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.4.5) initializing of server in progress as process 29
2025-05-07T02:59:34.228378Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2025-05-07T02:59:34.242417Z 0 [Warning] [MY-010001] [Server] Can't create thread to handle bootstrap (errno: 1)
2025-05-07T02:59:34.242469Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2025-05-07T02:59:34.242476Z 0 [ERROR] [MY-013236] [Server] The designated data directory /bitnami/mysql/data/ is unusable. You can remove all files that the server added to it.
2025-05-07T02:59:34.242482Z 0 [ERROR] [MY-010119] [Server] Aborting
2025-05-07T02:59:34.243232Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
```

How to resovle it? help me

**Comment by frankieci** [comment]
> This is happening to me in MySQL version 8.4.5, the StorageClasse is nfs, log such as:
> 
> ```
> $ kubectl logs -f mysql-0
> mysql 02:59:34.16 INFO  ==> 
> mysql 02:59:34.17 INFO  ==> Welcome to the Bitnami mysql container
> mysql 02:59:34.17 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
> mysql 02:59:34.17 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
> mysql 02:59:34.17 INFO  ==> 
> mysql 02:59:34.17 INFO  ==> ** Starting MySQL setup **
> mysql 02:59:34.19 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
> mysql 02:59:34.19 INFO  ==> Initializing mysql database
> mysql 02:59:34.20 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
> mysql 02:59:34.21 INFO  ==> Installing database
> 2025-05-07T02:59:34.225616Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start.
> 2025-05-07T02:59:34.227010Z 0 [System] [MY-013169] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.4.5) initializing of server in progress as process 29
> 2025-05-07T02:59:34.228378Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
> 2025-05-07T02:59:34.242417Z 0 [Warning] [MY-010001] [Server] Can't create thread to handle bootstrap (errno: 1)
> 2025-05-07T02:59:34.242469Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
> 2025-05-07T02:59:34.242476Z 0 [ERROR] [MY-013236] [Server] The designated data directory /bitnami/mysql/data/ is unusable. You can remove all files that the server added to it.
> 2025-05-07T02:59:34.242482Z 0 [ERROR] [MY-010119] [Server] Aborting
> 2025-05-07T02:59:34.243232Z 0 [System] [MY-015018] [Server] MySQL Server Initialization - end.
> ```
> 
> How to resovle it? help me

This is a permission issue, and you need to modify runAsUser and runAsGroup as root，default 1001,

**Comment by det101** [comment]
This problem still exists

**Comment by javsalgar** [comment]
Hi,

Did enabling the volumePermissions init container help with the issue?

**Comment by benifbond** [comment]
I am having similar issue does anyone knows how to fix this?

below is a sample of my kubernetes.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: services-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: bitnami/moodle:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /login/index.php
              port: 8080
            periodSeconds: 15
            failureThreshold: 8
          env:
            - name: MOODLE_URL
              value: "https://x.com/moodle-test"
            - name: MOODLE_DATABASE_TYPE
              value: "pgsql"
            - name: MOODLE_DATABASE_HOST
              value: "x-postgres.postgres.database.azure.com"
            - name: MOODLE_DATABASE_PORT_NUMBER
              value: "5432"
            - name: MOODLE_DATABASE_NAME
              value: "moodle-test"
            - name: MOODLE_DATABASE_USER
              value: "x-admin"
            - name: MOODLE_DATABASE_PASSWORD
              value: "6Fnobtv"
            - name: MOODLE_USERNAME
              value: "admin"
            - name: MOODLE_PASSWORD
              value: "RDUKTRH6fs"
            - name: MOODLE_SITE_NAME
              value: "Moodle Test Server"
            - name: MOODLE_DATABASE_SSL
              value: "true"
            - name: MOODLE_DATABASE_SSLMODE
              value: "require"
            - name: MOODLE_DATABASE_SSLROOTCERT
              value: "/certs/postgres/ca.crt"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: MOODLE_REVERSEPROXY
              value: "true"
            - name: MOODLE_SSLPROXY
              value: "true"

          volumeMounts:
            - name: moodle-data
              mountPath: /bitnami/moodle
            - name: services-cert
              mountPath: /certs
              readOnly: true

      volumes:
        - name: moodle-data
          emptyDir: {}
        - name: services-cert
          secret:
            secretName: services-tls

---
apiVersion: v1
kind: Service
metadata:
  name: moodle-srv
  namespace: services-ns
spec:
  selector:
    app: moodle
  ports:
    - name: moodle
      protocol: TCP
      port: 8080
      targetPort: 8080
`
Here is the error
 `kubectl logs moodle-c77d5cd5-qj42l -n services-ns
Defaulted container "moodle" out of: moodle, init-moodle-dirs (init)
moodle 07:36:57.91 INFO  ==>
moodle 07:36:57.91 INFO  ==> Welcome to the Bitnami moodle container
moodle 07:36:57.92 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
moodle 07:36:57.92 INFO  ==> NOTICE: Starting August 28th, 2025, only a limited subset of images/charts will remain available for free. Backup will be available for some time at the 'Bitnami Legacy' repository. More info at https://github.com/bitnami/containers/issues/83267
moodle 07:36:57.92 INFO  ==>
moodle 07:36:57.92 INFO  ==> ** Starting Moodle setup **
moodle 07:36:57.93 DEBUG ==> Validating settings in APACHE_* environment variables
moodle 07:36:57.93 WARN  ==> The Apache configuration file '/opt/bitnami/apache/conf/httpd.conf' is not writable. Configurations based on environment variables will not be applied.
moodle 07:36:57.94 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
mkdir: cannot create directory ‘/opt/bitnami/apache/conf/bitnami/certs’: Permission denied`
