### ISSUE TITLE
Error: INSTALLATION FAILED: failed to download "tac-bitnami/airflow"

### ISSUE THREAD

**Issue by Ashwin07** [bitnami/charts#11361]
### Name and Version

airflow

### What steps will reproduce the bug?

1. All pre requisites are met,
    **helm version**
      version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", 
      GoVersion:"go1.17.5"}
   **kubectl version**
     Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", 
     GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", 
     GoVersion:"go1.15.10", Compiler:"gc", Platform:"windows/amd64"}
     Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+vmware.1", 
     GitCommit:"088f01db2ffab397a290be443902918b59ee032c", GitTreeState:"clean", BuildDate:"2021-04-17T01:01:00Z", 
     GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
3. Added bitnami repo 
    **helm repo add bitnami https://charts.bitnami.com/bitnami**
4. Facing error while running install command
    **helm install my-release tac-bitnami/airflow**

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Install should be successful

### What do you see instead?

Error: INSTALLATION FAILED: failed to download "tac-bitnami/airflow"

**Comment by Ashwin07** [comment]
Below commands are also successful,

helm repo list
NAME    URL
bitnami https://charts.bitnami.com/bitnami

helm fetch bitnami/airflow

helm install my-release tac-bitnami/airflow
Error: INSTALLATION FAILED: failed to download "tac-bitnami/airflow"

**Comment by javsalgar** [comment]
Hi,

It seems that you are using an incorrect repository. Could you try `helm install bitnami/airflow`?

**Comment by Ashwin07** [comment]
Thanks! that worked!
