### ISSUE TITLE
[mongodb] mongodb+srv dns record doesn’t work properly 

### ISSUE THREAD

**Issue by menvol3** [bitnami/charts#11377]
### Name and Version

bitnami/mongodb 12.1.27

### What steps will reproduce the bug?

My mongodb replicaset has 2 replicas in the local cluster, also there are 2 DNS records created after deployment

mongodb-0.mongodb-headless.common.svc.cluster.local:27017
mongodb-1.mongodb-headless.common.svc.cluster.local:27017

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The +srv indicates to the client that the hostname that follows corresponds to a DNS SRV record. The driver or [mongosh](https://www.mongodb.com/docs/mongodb-shell/#mongodb-binary-bin.mongosh) will then query the DNS for the record to determine which hosts are running the [mongod](https://www.mongodb.com/docs/manual/reference/program/mongod/#mongodb-binary-bin.mongod) instances.

### What do you see instead?

When I'm trying to connect to DB using connection string with srv type **mongo "mongodb+srv://admin:qwert123@mongodb-headless.common.svc.cluster.local:27017/admin",** I always receive an error below
`FailedToParse: Hostname MongoDB-1.mongodb-headless.common.svc.cluster.local. is not within the domain common.svc.cluster.local
try 'mongo --help' for more information`

**Comment by rafariossaa** [comment]
Hi,
  DNS handling is an internal service in kubernetes, so I guess this will depend on the DNS you have in the cluster and how kubernetes handle it.
  I think there is nothing that can be done in the chart to fix this.
