### ISSUE TITLE
[mongodb] Add role for custom users

### ISSUE THREAD

**Issue by menvol3** [bitnami/charts#11379]
### Name and Version

bitnami/mongodb 12.1.27

### What is the problem this feature will solve?

I didn’t find property in values.yaml that could give the possibility to create custom roles such as **dbAdmin** for custom-created users 

### What is the feature you are proposing to solve the problem?

Some modifications for helm template

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but there is not parameter for this. 
  If you want to send a PR implementing this we will be glad to review and merge it.
