### ISSUE TITLE
[postgresql] read-only replica is not created

### ISSUE THREAD

**Issue by alexey-anufriev** [bitnami/charts#11394]
### Name and Version

bitnami/postgresql 11.6.19

### What steps will reproduce the bug?

I have a k8s cluster with mater and two worker nodes.
I want to install PostgreSQL on a single worker node.
I use the following command to perform the installation:
```
helm install postgresql \
    --set global.postgresql.auth.database=postgres \
    --set metrics.enabled=true \
    --set primary.nodeSelector."role"=app \
    --set readReplicas.nodeSelector."role"=app \
    --set volumePermissions.enabled=true \
    bitnami/postgresql
```
but in the end I have only one pod `postgresql-0` and do not see any RO replicas.

### Are you using any custom parameters or values?

```
--set global.postgresql.auth.database=postgres
--set metrics.enabled=true
--set primary.nodeSelector."role"=app
--set readReplicas.nodeSelector."role"=app
--set volumePermissions.enabled=true
```

### What is the expected behavior?

I would expect besides `postgresql-0` to have also one pod for read-only replica running on the same node.

### What do you see instead?

Only one pod - `postgresql-0` is running.

**Comment by alexey-anufriev** [comment]
I think I have found the cause: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/primary/statefulset.yaml#L23, I suspect here must be not 1 but `{{ .Values.readReplicas.replicaCount }}`

**Comment by alexey-anufriev** [comment]
I found a root cause, the following config was missing: `--set architecture=replication`. Might be important to mention in the documentation.

**Comment by fmulero** [comment]
Thanks @alexey-anufriev for sharing it.

I've been checking the documentation and you are right. Would you like to contribute by creating a PR? We will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines

**Comment by alexey-anufriev** [comment]
@fmulero, sure, prepared a slight adjustment.
