### ISSUE TITLE
nginx-ingress-controller: Helm install -  invalid type for io.k8s.api.core.v1.ConfigMap.data: got "array", expected "map"

### ISSUE THREAD

**Issue by BharathkumarHM** [bitnami/charts#11399]
### Name and Version

bitnami/nginx-ingress-controller

### What steps will reproduce the bug?

Try to install nginx-Ingress with TCP/UDP & nodeport configuration.

```
helm upgrade --install --dry-run --debug --set tcp='{6502:test-namespace/test-service:6502}',service.nodePorts.tcp='{31891}' --wait test-ingress bitnami/nginx-ingress-controller
```

### Are you using any custom parameters or values?
```
--set tcp='{6502:test-namespace/test-service:6502}',service.nodePorts.tcp='{31891}'
```
### What is the expected behavior?

Ingress should be configured with the correct TCP & nodeport configuration

### What do you see instead?

Getting - **_invalid type for io.k8s.api.core.v1.ConfigMap.data: got "array", expected "map"_** error on **_service.nodePorts.tcp_** values.

![image](https://user-images.githubusercontent.com/110159619/181456492-4fc31c11-77f5-4cf7-9010-e36f7936cdc8.png)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
