### ISSUE TITLE
Error Magento deploy ibm cloud private

### ISSUE THREAD

**Issue by jgra26** [bitnami/charts#1140]
during the deployment in ibm private cloud the deployment does not create the pod due to these logs

```
pod.ip:10.1.239.69 offset:1,569 log:[0m[38;5;2mINFO [0m ==> Stopping mariadb... kubernetes.pod:my-magento-mariadb-0 kubernetes.container_name:mariadb input_type:log source:/var/log/containers/my-magento-mariadb-0_default_mariadb-0a4c33e6b6e5658772482503fa56edea2de18decb3f4a62ef829e65ac8322f6b.log type:kube-logs tags:k8s-app, beats_input_raw_event kubernetes.container_id:0a4c33e6b6e5658772482503fa56edea2de18decb3f4a62ef829e65ac8322f6b node.hostname:192.168.42.130 @timestamp:April 22nd 2019, 16:20:17.798 stream:stderr kubernetes.namespace:default beat.hostname:logging-elk-filebeat-ds-kswk5 beat.name:logging-elk-filebeat-ds-kswk5 beat.version:5.5.1 @version:1 time:April 22nd 2019, 16:20:17.798 _id:AWpG6-Xjv36I0xIEio8V _type:kube-logs _index:logstash-2019.04.22 _score: -
```

**Comment by jgra26** [comment]
logs 

{"log":"\u001b[0m\n","stream":"stderr","time":"2019-04-22T23:28:50.713913815Z"}
{"log":"\u001b[0m\u001b[1mWelcome to the Bitnami mariadb container\u001b[0m\n","stream":"stderr","time":"2019-04-22T23:28:50.714139596Z"}
{"log":"\u001b[0mSubscribe to project updates by watching \u001b[1mhttps://github.com/bitnami/bitnami-docker-mariadb\u001b[0m\n","stream":"stderr","time":"2019-04-22T23:28:50.714157186Z"}
{"log":"\u001b[0mSubmit issues and feature requests at \u001b[1mhttps://github.com/bitnami/bitnami-docker-mariadb/issues\u001b[0m\n","stream":"stderr","time":"2019-04-22T23:28:50.7150825Z"}
{"log":"\u001b[0mSend us your feedback at \u001b[1mcontainers@bitnami.com\u001b[0m\n","stream":"stderr","time":"2019-04-22T23:28:50.715120801Z"}
{"log":"\u001b[0m\n","stream":"stderr","time":"2019-04-22T23:28:50.715140983Z"}
{"log":"\u001b[0m\u001b[38;5;2mINFO \u001b[0m ==\u003e ** Starting MariaDB setup **\n","stream":"stderr","time":"2019-04-22T23:28:50.715151337Z"}
{"log":"\u001b[0m\u001b[38;5;2mINFO \u001b[0m ==\u003e Validating settings in MYSQL_*/MARIADB_* env vars..\n","stream":"stderr","time":"2019-04-22T23:28:50.781860656Z"}
{"log":"\u001b[0m\u001b[38;5;2mINFO \u001b[0m ==\u003e Initializing mariadb database...\n","stream":"stderr","time":"2019-04-22T23:28:50.786136333Z"}
{"log":"mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied\n","stream":"stderr","time":"2019-04-22T23:28:50.792428947Z"}
{"log":"\u001b[0m\u001b[38;5;2mINFO \u001b[0m ==\u003e Stopping mariadb...\n","stream":"stderr","time":"2019-04-22T23:28:50.793042225Z"}

**Comment by tompizmor** [comment]
@jgra26 we are already talking about this issue in https://github.com/bitnami/charts/issues/1138.
Let's keep the conversation there.
