### ISSUE TITLE
[bitnami/kafka] KRaft server.properties not set

### ISSUE THREAD

**Issue by steveliem** [bitnami/charts#11407]
### Name and Version

bitnami/bitnami-docker-kafka

### What steps will reproduce the bug?

Hi,

I want to run Kafka with Kraft. For this I was hoping to use the Helm chart from bitnami. However the Helm chart doesn't include Kraft configuration yet. So I extended on top of the known implementation the missing bits for Kraft using the guidelines from bitnami/kafka.

After spinning up "bitnami/kafka:3.2.0-debian-11-r15" with the following properties:
```yaml
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
        - name: KAFKA_CFG_LISTENERS
          value: 'PLAINTEXT://:9092,CONTROLLER://:9093'
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: >-
            INTERNAL://$(MY_POD_NAME).kafka-kraft-headless***svc.cluster.local:9093,CLIENT://$(MY_POD_NAME).kafka-kraft-headless.***.svc.cluster.local:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: 'yes'
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: PLAINTEXT
        - name: KAFKA_VOLUME_DIR
          value: /bitnami/kafka
        - name: KAFKA_LOG_DIR
          value: /opt/bitnami/kafka/logs
        - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
          value: 'false'
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: 'true'
        - name: KAFKA_HEAP_OPTS
          value: '-Xmx1024m -Xms1024m'
        - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
          value: '10000'
        - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MS
          value: '1000'
        - name: KAFKA_CFG_LOG_RETENTION_BYTES
          value: '1073741824'
        - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS
          value: '300000'
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: '168'
        - name: KAFKA_CFG_MESSAGE_MAX_BYTES
          value: '1000012'
        - name: KAFKA_CFG_LOG_SEGMENT_BYTES
          value: '1073741824'
        - name: KAFKA_CFG_LOG_DIRS
          value: /bitnami/kafka/data
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: '1'
        - name: KAFKA_CFG_NUM_IO_THREADS
          value: '8'
        - name: KAFKA_CFG_NUM_NETWORK_THREADS
          value: '3'
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: '1'
        - name: KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR
          value: '1'
        - name: KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES
          value: '102400'
        - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
          value: '104857600'
        - name: KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES
          value: '102400'
        - name: KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: '6000'
        - name: KAFKA_CFG_AUTHORIZER_CLASS_NAME
        - name: KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND
          value: 'true'
        - name: KAFKA_CFG_SUPER_USERS
          value: 'User:admin'
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: ittsv1HYJzttdz5ojdss
        - name: KAFKA_ENABLE_KRAFT
          value: 'yes'
        - name: KAFKA_CFG_PROCESS_ROLES
          value: 'broker,controller'
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
```
and a bit of script for composing the KAFKA_CFG_CONTROLLER_QUORUM_VOTERS:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-kraft-scripts
  namespace: ***
  uid: 7dbe4e4a-9546-4a8b-99af-7a9a78f70c40
  resourceVersion: '184432246'
  creationTimestamp: '2022-07-19T09:31:53Z'
  labels:
    app.kubernetes.io/instance: kafka-kraft
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-18.0.3
  annotations:
    meta.helm.sh/release-name: kafka-kraft
    meta.helm.sh/release-namespace: ***
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2022-07-19T09:31:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:setup.sh': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:helm.sh/chart': {}
data:
  setup.sh: |-
    #!/bin/bash

    ID="${MY_POD_NAME#"kafka-kraft-"}"
    if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
        export KAFKA_CFG_BROKER_ID="$(grep "broker.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')"
    else
        export KAFKA_CFG_BROKER_ID="$((ID + 0))"
    fi

    # Configure KRaft mode enabled variables
    export KAFKA_ENABLE_KRAFT="yes"
    export KAFKA_CFG_PROCESS_ROLES="broker,controller"
    export KAFKA_CFG_CONTROLLER_LISTENER_NAMES="CONTROLLER"
    CONTROLLER_QUORUM_VOTERS=""
    REPLICAS=3
    for i in $( seq 0 $REPLICAS); do
        if [[ $i != $REPLICAS ]]; then
            BROKER_ID="$((i + 0))"
            CONTROLLER_QUORUM_VOTERS="$CONTROLLER_QUORUM_VOTERS$BROKER_ID@kafka-kraft-$i.kafka-kraft-headless.***.cluster.local:9093,"
        else
            CONTROLLER_QUORUM_VOTERS=${CONTROLLER_QUORUM_VOTERS::-1}
        fi
    done
    export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="${CONTROLLER_QUORUM_VOTERS}"

    # Configure zookeeper client

    exec /entrypoint.sh /run.sh
```

the Helm chart is able to provision.
However, the Docker containers don't spin up and fail eventually on CrashLoopBackoff.

I noticed that the server.properties specifically for Kraft are not set inside kafka/config/kraft/.
It takes the default values delivered with the vanilla installation of Kafka. Also I don't see any part of a script inside the support shell scripts from the Docker image that this is happening.

Here for clarification the Apache Kafka guidelines where it is mentioned that above property file needs to be configured in order to let Kafka work with KRaft: https://github.com/apache/kafka/blob/trunk/config/kraft/README.md

### What do you see instead?

By opening shell interface to docker container navigate and cat opt/bitnami/kafka/config/kraft/server.properties,
none of the properties are set with the correct references.

Eventually there are no listeners for the controller and broker part active for a container to pass on readiness.

**Comment by javsalgar** [comment]
Hi,

It seems to me that maybe the changes the in the scripting should occur in the Kafka container, did you try creating a fork that tweaks the container logic?

**Comment by javsalgar** [comment]
I forwarded this to the team and there are plans to work on KRaft support, especially when this feature becomes production-ready. We will update this ticket when there are updates on this.

**Comment by flikkflakk** [comment]
> I forwarded this to the team and there are plans to work on KRaft support, especially when this feature becomes production-ready. We will update this ticket when there are updates on this.

Apache Kafka 3.3 is [released](https://github.com/apache/kafka/releases/tag/3.3.0) and KRaft is marked production-ready.

**Comment by javsalgar** [comment]
Thank you so much! I will forward this to the team so we can plan it for future work iterations.

**Comment by mprimeaux** [comment]
Please keep alive.

**Comment by OneCricketeer** [comment]
Linking #13624

**Comment by jotamartos** [comment]
Hi all,

Just a quick note to let you know that we recently updated the Bitnami Kafka Chart to use Kraft by default 

https://github.com/bitnami/charts/pull/15768

Regards.

**Comment by n5nk** [comment]
Not sure if this is fixed or not in which version. I see an issue with 3.4.0 bitnami image. If i start adding listener properties, the kafka container just crashes.

```
docker run --name kafka -e ALLOW_PLAINTEXT_LISTENER=yes \
    -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094 \
    -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094 \
    -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT \
    -e KAFKA_CFG_BROKER_ID=1 -e KAFKA_ENABLE_KRAFT=yes \
    -e KAFKA_CFG_PROCESS_ROLES=broker,controller \
    -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
    -p 9094:9094 bitnami/kafka:3.4.0
```

Console o/p:
```
kafka 18:01:21.77 
kafka 18:01:21.77 Welcome to the Bitnami kafka container
kafka 18:01:21.78 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 18:01:21.78 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 18:01:21.78 
kafka 18:01:21.78 INFO  ==> ** Starting Kafka setup **
kafka 18:01:21.84 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 18:01:21.85 INFO  ==> Initializing Kafka...
kafka 18:01:21.86 INFO  ==> No injected configuration files found, creating default config files
kafka 18:01:21.98 INFO  ==> Initializing KRaft...
kafka 18:01:21.98 WARN  ==> KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
kafka 18:01:22.93 INFO  ==> Generated Kafka cluster ID '3owaZInaSga8rav0rF57rQ'
kafka 18:01:22.93 INFO  ==> Formatting storage directories to add metadata...
```

What is missing here ?

**Comment by OneCricketeer** [comment]
Is that a crash? Looks like it said it's formatting a directory.

Is there an exit code?

**Comment by JurisU** [comment]
I have the same issue, it's happening, when `EXTERNAL` is added

**Comment by OneCricketeer** [comment]
The string `EXTERNAL` doesn't really mean anything specific. You will need to add `EXTERNAL:PLAINTEXT` to list in `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP`, however. (I.e. remove/replace `INSIDE` and `OUTSIDE` as they aren't doing anything)

**Comment by OneCricketeer** [comment]
Thanks. I use Strimzi, instead of these charts 

The issue reported in this issue is being discussed in  https://github.com/bitnami/containers/issues

**Comment by fouadsemaan** [comment]
Thanks @OneCricketeer! Which is the specific issue in https://github.com/bitnami/containers/issues?

**Comment by OneCricketeer** [comment]
There's several. Filter by Kafka tag

**Comment by mwitteveen** [comment]
i was just struggling with the same issue but I looks like I resolved it:

first of all the chart crashes when you have kraft enabled and hostNetwork: true, locally I'm developing with Kind the hostNetwork I needed for this. 

For this issue while deploying it on kubernetes in the events you can see that the liveness and readiness probes are being triggered to fast. It might be that the initialization of kraft is taking to long making these probes reset the container. If there is no clean exit handler present in the init stage of kraft this would look like an instant error code exit in docker. 

I disabled the hostNetwork and increased the initial delay for the probes, that resolved the issue for me.

**Comment by migruiz4** [comment]
Hi there!

We have released a new major of the bitnami/kafka chart which refactors the chart architecture and configuration.

Could you please confirm if this issue persists in the latest version?

You can find all the changes introduced in this version as well as some guidance on how to upgrade in the [Upgrading notes](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400)

**Comment by emmeowzing** [comment]
Please open again.

**Comment by migruiz4** [comment]
Hi @emmeowzing,

The `bitnami/kafka` image and chart now include support for KRaft mode, could you please provide more details about why this issue should be reopened?
