### ISSUE TITLE
Add fullnameOverride value to zookeeper chart

### ISSUE THREAD

**Issue by Vapsel** [bitnami/charts#1141]
**Which chart**:

zookeeper

**Description**

I need to override full name of service (I don't want to include release name).
Please add *fullnameOverride* value to zookeeper chart as it was done for kafka - #998.

I assume that setting *fullnameOverride* value in kafka chart will propagate it to the zookeeper chart.

**Comment by javsalgar** [comment]
Hi,

Thanks for lettting us know. We will consider this feature in future releases of the chart. Could you give us more details about your use case? We would like to understand more about your set up and why this feature is essential to you.

**Comment by Vapsel** [comment]
Hi @javsalgar,
currently I'm working on CI/CD processes in my project. I use helm charts to deploy my application at k8s.

I have a requirement to deploy multiple environments in k8s. Environment = namespace in k8s. I would like to keep my values in charts (especially service names) same for each environment. As helm doesn't allow same release names in different namespaces (more details at [this issue](https://github.com/helm/helm/issues/2060)), I use `namespace--app` pattern to name helm releases.

But zookeeper append release name to service name and truncate 24 chars. It causes for me two problems:

1. my namespaces could have up to 20 chars, so using kafka chart will cause zookeeper service name will be  **namespace--kafka**. It isn't right semantic name for zookeeper.
2. It breaks my convention for service names  - to be same in each environment.

It was done in Kafka (#998 ), so it would be nice to keep charts similar.

Thanks

**Comment by javsalgar** [comment]
Thanks, I created this PR that covers your use case: https://github.com/bitnami/charts/pull/1152

**Comment by juan131** [comment]
Sorry I missed that PR, I just requested changes on both PR!

**Comment by juan131** [comment]
The PR was accepted and now the Zookeeper chart has support for the paramteer **fullnameOverride**.
