### ISSUE TITLE
Change upstream kubernetes-event-exporter repository

### ISSUE THREAD

**Issue by bdols** [bitnami/charts#11412]
### Name and Version

bitnami/kubernetes-event-exporter 1.4.16

### What is the problem this feature will solve?

per https://github.com/opsgenie/kubernetes-event-exporter/issues/203, the main maintainer has changed companies, and I'm looking to get some changes that they've made in their forked repo.

### What is the feature you are proposing to solve the problem?

change upstream repo to https://github.com/resmoio/kubernetes-event-exporter

**Comment by rafariossaa** [comment]
Hi,
  Thanks for reporting this. I am opening a internal task in order to study this and make the needed changes in our internal CI/CD pipeline.
  We will come back as soon as we have news.

**Comment by corico44** [comment]
We inform you that the upstream repo has been updated for kubernetes-event-exporter, and the future versions will ship that code.

Thank you very much for the contribution!

**Comment by lucj** [comment]
On the artifacthub (https://artifacthub.io/packages/helm/bitnami/kubernetes-event-exporter) the first link "Overview Of Kubernetes Event Exporter" still references https://github.com/opsgenie/kubernetes-event-exporter instead of https://github.com/resmoio/kubernetes-event-exporter

**Comment by carrodher** [comment]
We just created the above PR updating the metadata used by the ArtifactHub

**Comment by lucj** [comment]
Thanks for the update. Just another thing, I might be wrong on that one though...
When I run the latest version of the chart, the pod's logs keep referencing the previous repo, for instance:

```
2022-08-12T12:14:57Z INF bitnami/blacksmith-sandox/kubernetes-event-exporter-0.11.0/src/github.com/opsgenie/kubernetes-event-exporter/pkg/exporter/engine.go:25 > Registering sink name=webhooks type=*sinks.Webhook
```

**Comment by bdols** [comment]
looks like there is a new release tagged here: https://github.com/resmoio/kubernetes-event-exporter/releases/tag/v1.0-alpha
is that the release that is being packaged by bitnami?

**Comment by carrodher** [comment]
No, at this moment and until there is a new version available at https://github.com/resmoio/kubernetes-event-exporter/releases, the source code bundled in the container is the one from https://github.com/opsgenie/kubernetes-event-exporter.

The latest release at https://github.com/resmoio/kubernetes-event-exporter/releases is marked as `alpha` and we don't track alpha, beta, release-candidate, etc releases. So once there is a new stable release, our track & download system will fetch that code and release a new container image bundling that code, in the meantime, the metadata and the tracking system was updated but the already downloaded source code is the one from the original source.

**Comment by lucj** [comment]
Thanks for the details @carrodher

**Comment by bdols** [comment]
it looks like there's a v1.0 release now @carrodher

**Comment by fmulero** [comment]
We are working on it. We hope having it soon
