### ISSUE TITLE
[bitnami/mongodb-sharded] Getting permission denied when using Minikube with volumePermissions set to true

### ISSUE THREAD

**Issue by jdholtz** [bitnami/charts#11430]
### Name and Version

bitnami/mongodb-sharded 5.1.1

### What steps will reproduce the bug?

1. Install Minikube (I am using the latest version - v1.26.0)
2. Install MongoDB-sharded helm chart and enable volumePermissions: `helm install mongodb-test bitnami/mongodb-sharded --set volumePermissions.enabled=true`
3. Within a few seconds, you will see the shard and config server pods crashing. If you check the logs, it says `mkdir: cannot create directory '/bitnami/mongodb': Permission denied`

### Are you using any custom parameters or values?

volumePermissions.enabled=true

### What is the expected behavior?

Without enabling `volumePermissions`, the helm chart installs as expected without any crashes. It is expected that MongoDB sharded should start the same way when enabling `volumePermissions`.

### What do you see instead?

Here are the logs of the `mongodb-sharded-configsvr-0 `:
<details>
<summary>Config server logs</summary>
<br>
Defaulted container "mongodb" out of: mongodb, volume-permissions (init)  <br>
 21:21:55.33 INFO  ==> Setting node as primary <br>
mongodb 21:21:55.35 <br>
mongodb 21:21:55.35 Welcome to the Bitnami mongodb-sharded container <br>
mongodb 21:21:55.36 Subscribe to project updates by watching https://github.com/bitnami/containers <br>
mongodb 21:21:55.36 Submit issues and feature requests at https://github.com/bitnami/containers/issues <br>
mongodb 21:21:55.36 <br>
mongodb 21:21:55.36 INFO  ==> ** Starting MongoDB Sharded setup ** <br>
mongodb 21:21:55.38 INFO  ==> Validating settings in MONGODB_* env vars... <br>
mkdir: cannot create directory '/bitnami/mongodb': Permission denied
</details>

### Additional information

This seems to be related to [this](https://github.com/kubernetes/minikube/issues/1990) issue in Minikube using host path provisioners.

The problem with the volumePermissions container seems to be that it never changes the mountPath directory permissions, only the subdirectory permissions. This creates a conflict with Minikube because the host path volume created by the Minikube provisioner is only writable by root unless changed. 

A fix for this can be to simply change the ownership of the mountPath directory, as done in the MongoDB chart ([here](https://github.com/bitnami/charts/blob/090977eb0ed7edafc10886eda67c55a79def89b3/bitnami/mongodb/templates/hidden/statefulset.yaml#L100)). I have tested this locally and it fixes this issue. 

Let me know if you want me to submit a PR to fix this by implementing the above change.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Indeed, contributions are welcome so It would be awesome if you could submit a PR! :D
