### ISSUE TITLE
[postgresql] readReplicas.persistence.existingClaim

### ISSUE THREAD

**Issue by alexey-anufriev** [bitnami/charts#11449]
### Name and Version

bitnami/postgresql 11.6.19

### What is the problem this feature will solve?

Reinstalling the PostgreSQL cluster required a bit of cleanup. In particular PVC for replica needs to be removed first. This is not a problem for the master as `primary.persistence.existingClaim` configuration exists.

### What is the feature you are proposing to solve the problem?

Introduce `readReplicas.persistence.existingClaim` to be able to specify PVC.

**Comment by alexey-anufriev** [comment]
I have create a PR if this may help: https://github.com/bitnami/charts/pull/11460

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will take a look and provide feedback
