### ISSUE TITLE
Add the ability to move or link files to the wordpress root directory

### ISSUE THREAD

**Issue by jakechristie** [bitnami/charts#11459]
### Name and Version

bitnami/wordpress 15.0.10

### What is the problem this feature will solve?

I am migrating a wordpress website from a VM to kubernetes and we chose this bitnami chart as a starting point. On our original website we had a variety of files sitting in the wordpress root directory, and it doesn't seem like there's any way to copy or link them there with the chart as is.

### What is the feature you are proposing to solve the problem?

Ideally a command could be run at pod start or restart so that I could do e.g.:
`ln -s /bitnami/wordpress/example.txt /opt/bitnami/wordpress/example.txt`

### What alternatives have you considered?

I tried `customPostInitScripts` which either didn't work or didn't work as expected (nothing happened after a helm upgrade, perhaps a new deploy would work though).

Long term I can move those files out of the root directory. This isn't urgent and hopefully I've just missed something along the way that will allow me to do this.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami WordPress container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by ZeldOcarina** [comment]
Hi! Did anyone ever figure out how to do this?
