### ISSUE TITLE
[postgresql] readReplicas.extendedConfiguration

### ISSUE THREAD

**Issue by alexey-anufriev** [bitnami/charts#11450]
### Name and Version

bitnami/postgresql 11.6.19

### What is the problem this feature will solve?

Having the following config set `primary.extendedConfiguration=max_connections=1024` causes errors on read-replicas. In fact, it is not possible to create those normally. The error is: `max_connections = 100 is a lower setting than on the primary server, where its value was 1024.`. And it is not possible to resolve the problem without the possibility to set configuration for replicas.

### What is the feature you are proposing to solve the problem?

Introduce `readReplicas.extendedConfiguration`.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by alexey-anufriev** [comment]
hi @carrodher, I tried my best here: https://github.com/bitnami/charts/pull/11458

**Comment by carrodher** [comment]
Thanks for the PR! We will take a look and provide feedback if needed

**Comment by alexey-anufriev** [comment]
hi @carrodher, are there any news of this PR?

**Comment by carrodher** [comment]
@rafariossaa is doing an initial triage to ensure it met the CONTRIBUTING guidelines and someone else on the team will take a look at it
