### ISSUE TITLE
[bitnami/thanos] Small typo in checksum/ojbstore-configuration annotation

### ISSUE THREAD

**Issue by dccarbone** [bitnami/charts#11457]
### Name and Version

bitnami/thanos 11.1.2

### What steps will reproduce the bug?

I found a typo in the annotation "checksum/**ojbstore**-configuration" where I think shoud be checksum/**objstore**-configuration.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

checksum/objstore-configuration

### What do you see instead?

checksum/ojbstore-configuration

### Additional information

Files:
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/bucketweb/deployment.yaml#L36
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/compactor/deployment.yaml#L34
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/ruler/statefulset.yaml#L39
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/storegateway/statefulset.yaml#L38
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L38
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/storegateway/statefulset-sharded.yaml#L52

**Comment by migruiz4** [comment]
Hi @dccarbone,

Thank you for reporting this issue. It should not have a functional impact if the annotation is named `checksum/ojbstore-configuration` or `checksum/ojbstore-configuration`.

Its function is to roll the deployment when the configuration is updated using `helm upgrade` and is not affected by its name: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

If you would like to contribute, please send a PR fixing the typo. We will be very happy to review it and help with anything if needed.

**Comment by dccarbone** [comment]
Thanks for the reply, @migruiz4! As this is my first contribution to an Open Source project could you please check if everything is ok?
