### ISSUE TITLE
Discourse readiness probe failed

### ISSUE THREAD

**Issue by junoriosity** [bitnami/charts#11456]
### Name and Version

bitnami/discourse

### What steps will reproduce the bug?

I am currently installing Discourse with [helm charts](https://artifacthub.io/packages/helm/bitnami/discourse). I run

```
kubectl create ns discourse
helm install my-release bitnami/discourse --namespace discourse
```

### What do you see instead?

Sadly, when I run it, the deployment fails, saying for the `discourse` container in the `discourse` pod has the issue

```
Readiness probe failed: Get "http://192.168.4.41:8080/srv/status": dial tcp 192.168.4.41:8080: connect: connection refused
```

Do you know how to fix that?

**Comment by javsalgar** [comment]
Hi,

Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.
