### ISSUE TITLE
How to define tomcat-users.xml configurations ?

### ISSUE THREAD

**Issue by lduparc** [bitnami/charts#1148]
How can we define role and user like configurations under tomcat-users.xml file to enable manager-gui for example and more ?

```
...
<role rolename="manager-gui"/>
<role rolename="manager-script"/>
<role rolename="manager-jmx"/>
<role rolename="manager-status"/>
<user username="my_manager" password="my_manager_password" roles="manager-gui,manager-script,manager-jmx,manager-status"/>
<user username="my_simple_user" password="my_simple_user_password" roles="manager-jmx,manager-status"/>

```

**Comment by javsalgar** [comment]
Hi,

I assume you would like to mount custom configuration files, is that right? If so, which files you think it would make more sense to be mountable?

**Comment by lduparc** [comment]
well, I would like to configure tomcat-users to be able to access manager-gui....etc. With bitnami where are store these kind of configurations files ? I can mount or is it possible to override tomcat config using Values.yaml ?

**Comment by juan131** [comment]
Hi @lduparc 

Currently, this chart is persisting both the Tomcat data (`/bitnami/tomcat/data`) and configuration (`/bitnami/tomcat/conf` )under the same persistent volume. See:

https://github.com/bitnami/charts/blob/master/bitnami/tomcat/templates/deployment.yaml#L61

We could adapt it so it only persist the data. Then, we could make it possible to use some **configmaps** to mount some of the configuration files in the container such as **tomcat-users.xml**, **server.xml** or **web.xml**.
