### ISSUE TITLE
redis pod are continuosly restarting 

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#11499]
### Name and Version

bitnami, redis

### What steps will reproduce the bug?

 helm install redis redis

### Are you using any custom parameters or values?

architecture=replication
1 master + 2 slave architecture
sentinels =enabled

### What is the expected behavior?

redis pods should run fine without any restarts

### What do you see instead?

redis pods are restarting automatically without any error in logs.

### Additional information

![Screenshot from 2022-08-02 15-30-37](https://user-images.githubusercontent.com/68244292/182348241-fe531b1d-a261-4b71-93c2-35148af8db6b.png)
![Screenshot from 2022-08-02 15-30-23](https://user-images.githubusercontent.com/68244292/182348252-8095d248-2f15-4e86-bd87-5f63204664da.png)
![Screenshot from 2022-08-02 15-30-12](https://user-images.githubusercontent.com/68244292/182348257-28c161fc-810a-45e8-85ba-629e0d640b2e.png)
![Screenshot from 2022-08-02 15-30-02](https://user-images.githubusercontent.com/68244292/182348261-4510fc53-b5fe-434b-ad7f-a1f89defa467.png)

**Comment by abhishekgupta2205** [comment]
these are the logs of redis master pod

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-08-02 15-32-33](https://user-images.githubusercontent.com/68244292/182348552-f67af3e6-d231-470b-b53f-026441e616a4.png)

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-08-02 15-37-38](https://user-images.githubusercontent.com/68244292/182349716-a145fe0c-75fb-4c2d-b36f-662de716fe5f.png)

**Comment by abhishekgupta2205** [comment]
due to this restart process sentinels are changing the master  , which is craeting a problem
i cant find any cause for these restarts in the logs

**Comment by migruiz4** [comment]
Hi @abhishekgupta2205,

Can you please share what version of the `bitnami/redis` chart are you using?

The `bitnami/redis` have recently received some changes that should fix this issue.

If possible, please update to the latest version and let me know if the issue persists?

To update to the latest version, run `helm repo update` and run `helm search repo redis`, at this moment, latest version is `17.0.6`:
```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo redis
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/redis        	17.0.6       	7.0.4      	Redis(R) is an open source, advanced key-value ...
bitnami/redis-cluster	8.1.2        	7.0.4      	Redis(R) is an open source, scalable, distribut...
```

**Comment by abhishekgupta2205** [comment]
redis-16.4.0 
Can you tell me some reason why it is happening

**Comment by migruiz4** [comment]
> Can you tell me some reason why it is happening
The pod liveness/readiness probes are failing repeatedly, causing the pod to restart.

> redis-16.4.0

Version 16.4.0 was released 6 months ago, and during that time the `bitnami/redis` chart have received several fixes and improvements.
In order to help help you, we need you to use a recent version of the chart, otherwise, it is difficult to determine if it is a bug that has already been addressed, a configuration error, or a bug existing in the latest version of the chart.
In addition, if a fix were applied, you would need to upgrade to the latest version to benefit from it.

**Comment by abhishekgupta2205** [comment]
actuall i have already deployed and traffic is comijng on it. so it is not possible to change the helm chart version . 
it will be really helpful if you can provide any solution or info about any previous bugs related to it

**Comment by abhishekgupta2205** [comment]
@migruiz4 can you give any other suggestion?

**Comment by migruiz4** [comment]
Hi @abhishekgupta2205,

> actuall i have already deployed and traffic is comijng on it. so it is not possible to change the helm chart version .

The version of the Redis Cluster can be upgraded by using the command `helm upgrade`.

I would suggest troubleshooting why the livenessProbe is timing out (and restarting the pod), you can log into the pod and run the redis-cli command manually.
