### ISSUE TITLE
[bitnami/mariadb] Restoring data failed with docker-entrypoint

### ISSUE THREAD

**Issue by lduparc** [bitnami/charts#1149]
Using helm initContainer I restore data to /bitnami/mariadb/data. When mariadb start I can see 
```
INFO  ==> Persisted data detected. Restoring...
```

But I also have sql file into `/docker-entrypoint-initdb.d` that load sql requests based on existing data restored before. In this case entrypoint is load before data has been restored and it failed.

**Comment by tompizmor** [comment]
@lduparc Why do you need to manually restore the data with an initContainer? 
The MariaDB chart should already handle data persistence without user intervention. 

Also, the scripts at `/docker-entrypoint-initdb.d` are only executed once (during the first initialization).  After that, they create a `.user_scripts_initialized` file in the volume dir so the execution of these scripts is skipped in future runs.

You can see the logic regarding custom initialization files [here](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.2/debian-9/rootfs/libmysql.sh#L718-L746)

**Comment by lduparc** [comment]
I have existing data dir and running a mysql backup is too slow to restore data and I'm not able to use `/docker-entrypoint-initdb.d` with a .sql.gz file because the archive is too large for helm. So I have create an archive (using tar) of the mysql data dir and before start bitnami/mariadb I copy it to /bitnami/mariadb/data. At this point everything is ok, mariadb start and detect existing data, so the log `... Restoring...` appear. But just after it try to load simple sql files from `/docker-entrypoint-initdb.d` without success because databases don't exist yet. So data resptoration is not finished...

What do you mean by : 
```
The MariaDB chart should already handle data persistence without user intervention.
```

**Comment by tompizmor** [comment]
Thanks for the details! It is clearer for me now. However, there is a thing I don't understand yet. 

Why the simple SQL files from `/docker-entrypoint-initdb.d` complain about non-existent databases if you have already restore your data. If you have already load your data, the databases should exist no? Am I missing something else? 

> The MariaDB chart should already handle data persistence without user intervention.

I mean that the chart already creates a PVC an attach it to the pod if persistence is enabled.

**Comment by lduparc** [comment]
OK I understand. Using a persistent volume everything is working as expected but in one case I run mariadb without  PV (for ephemeral namespace/environement for dev). In this case copying the existing data and start mariadb cause an error because existing data is not loaded before running sql migrations files.What I have done is to modify `setup.sh` and `run.sh`scripts like this.

setup.sh -> remove
```
msyql_custom_init_scripts line 
```

run.sh  ->  add
```
info "** Starting MariaDB **"
mysql_start_bg
mysql_upgrade
msyql_custom_init_scripts
mysql_stop

if am_i_root; then
    exec gosu "$DB_DAEMON_USER" "${DB_SBINDIR}/mysqld" "${flags[@]}"
else
    exec "${DB_SBINDIR}/mysqld" "${flags[@]}"
fi

```

In this case, bdd is started and load existing data then execute sql migrations

**Comment by tompizmor** [comment]
@lduparc I am glad you were able to find a workaround for your use case.
