### ISSUE TITLE
[bitnami/elasticsearch] configurable service names

### ISSUE THREAD

**Issue by mFranz82** [bitnami/charts#11505]
bitnami/elasticsearch >= 18

### When upgrading from chart version 17.x to 18.x the upgrade fails with the following errors:

```
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden ...
```

This is due to the fact that the ```statefulset.spec.serviceName``` changed from: ```{elasticsearch.[...].fullname}``` to ```{elasticsearch.[...].fullname}-hl```

A rolling cluster upgrade is therefore not possible. 
We need to destroy the current release first which is what we don't want.

### What is the feature you are proposing to solve the problem?

Before writing code I would like to discuss our idea. Maybe someone has better ideas. 

Introduce a new variable in ```values.yaml``` for each node type section (master, data, coordinating, ingest) 

```
master: 
  # The name of the headless service
  # default to: {elasticsearch.master.fullname}-hl
  serviceName: ""

```

Provide a new ```_helper.tpl``` function for each node type which defines the defaults.
```
{{- define "elasticsearch.master.servicename" -}}
{{- if .Values.master.servicename-}}
{{- .Values.master.servicename | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-hl" (include "elasticsearch.master.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

What do you think about this? I know that no other bitnami chart currently uses configurable service names but in our case it would make sense.

**Comment by carrodher** [comment]
Sorry for the delay, we missed the notification about this issue. The team will take a look

**Comment by fmulero** [comment]
Hi @mFranz82 I'm so sorry for my very late response.

Chart version 18.X.X includes an [elasticsearch upgrade](https://www.elastic.co/guide/en/elastic-stack/8.4/upgrading-elastic-stack.html#prepare-to-upgrade). Not sure if it's worth to fix the issue with the `serviceName` when you have to upgrade the data or configuration to ensure compatibility with the new version of elastic and probably elastic pods in version 7 won't work with nodes in 8.

**Comment by mFranz82** [comment]
> Hi @mFranz82 I'm so sorry for my very late response.
> 
> Chart version 18.X.X includes an [elasticsearch upgrade](https://www.elastic.co/guide/en/elastic-stack/8.4/upgrading-elastic-stack.html#prepare-to-upgrade). Not sure if it's worth to fix the issue with the `serviceName` when you have to upgrade the data or configuration to ensure compatibility with the new version of elastic and probably elastic pods in version 7 won't work with nodes in 8.

What was your workflow when upgrading from chart version 16.x to 18.x while keeping data in the cluster?

**Comment by mFranz82** [comment]
There is another part in the chart which blocks an upgrade vom 16.x to 18.x:

```
spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set
```

In former versions auf the chart the clusterIP was not defined:
```
spec:
  type: {{ .Values.master.service.type | quote }}
  {{- if and (eq .Values.master.service.type "LoadBalancer") (not (empty .Values.master.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.master.service.loadBalancerIP }}
  {{- end }}
  publishNotReadyAddresses: true
```

Now it is set to *None*
```
spec:
  type: ClusterIP
  clusterIP: None
