### ISSUE TITLE
Configuring controlled.shutdown.max.retries  on kafka chart

### ISSUE THREAD

**Issue by gbl-michell** [bitnami/charts#11513]
### Name and Version

bitnami/kafka 14.9.3

### What steps will reproduce the bug?

I haven't found documentation about how to set the `controlled.shutdown.max.retries` value on kafka charts.

I have tried setting it up with the `config:` attribute but it doesn't change the actual value being loaded.

### What is the expected behavior?

I expect the value loaded on the pod to be `controlled.shutdown.max.retries = <whatever-I-set-here>`.

### What do you see instead?

controlled.shutdown.max.retries always load with the default value of 3.

**Comment by carrodher** [comment]
Did you try [this](https://github.com/bitnami/charts/tree/master/bitnami/kafka#setting-custom-parameters)?

**Comment by gbl-michell** [comment]
Hey @carrodher. Thanks, setting the config as 
```
extraEnvVars:
  - name: KAFKA_CFG_CONTROLLED_SHUTDOWN_MAX_RETRIES
    value: '100' 
```

on the values files did it.

**Comment by carrodher** [comment]
Glad to see it worked!
