### ISSUE TITLE
Rabbitmq readiness/liveness probes fail with custom management path

### ISSUE THREAD

**Issue by msolberg8** [bitnami/charts#11551]
### Name and Version

bitnami/rabbitmq 10.1.16

### What steps will reproduce the bug?

Run the rabbitmq chart with the following extra configuration:
```
extraConfiguration: |-
  management.path_prefix = /rabbit
```
We use this to modify the ingress path to our management console. That being said if you set this value, the healthchecks will fail as they are trying to hit the `/api` path as specified here: https://github.com/bitnami/charts/commit/73966c67ff6d3386721cf1f42a6493f961c56792

### Are you using any custom parameters or values?
```
extraConfiguration: |-
  management.path_prefix = /rabbit
```
### What is the expected behavior?

It would be nice if this were something that could be handled by the chart natively. Currently we need to set custom probes to get around this.

### What do you see instead?

Healthchecks failing as they aren't aware of the `management.path_prefix` set in the extra configuration section.

### Additional information

I may be able to take a stab here as I don't think there are many folks using the `management.path_prefix` but wanted to record so I don't forget.

**Comment by rafariossaa** [comment]
Hi,
  The `extraConfiguration` parameter is a parameter where you are free to set whatever is needed and it is passed directly as configuration to rabbitmq. The chart is not "aware", it doesn't now about specific paramaters,  of what you are setting there.
  The way to go when this kind of settings are used is what you indicated, create a custom health check and add what is needed.

  In the other hand, if this is very commonly changed, a specific parameter for `path_prefix` could be created and handled properly by the chart.

  Maybe you want to send a PR implementing this. We will be glad to review and merge it.
