### ISSUE TITLE
Allow setting default_toast_compression to lz4 in postgres easily

### ISSUE THREAD

**Issue by MTRNord** [bitnami/charts#11562]
### Name and Version

bitnami/postgres

### What is the problem this feature will solve?

Currently to set the default compression you need to manually alter the database or have a script do it.

Using lz4 for default_toast_compression is supposed to slightly improve disk space making it desirable to use it.

Simplifying this to be able to be set at chart level would make usage of this a lot easier

### What is the feature you are proposing to solve the problem?

A variable for setting default_toast_compression for the default tables.

**Comment by marcosbc** [comment]
Hi @MTRNord, unfortunately we have a lot of things on our plate currently, and this is a feature that while it's great to have, we won't be able to implement in the short term.

Would you be open to contributing these changes? We would gladly help with the review and release of such changes, if you were able to.

**Comment by MTRNord** [comment]
I currently dont really have time to implement it myself, but I also have no urgent need for it. :) So it's fine with me if it just stays in the backlog for now :)

**Comment by marcosbc** [comment]
Hi, just letting you know that we created the issue for implementing the feature. Unfortunately I cannot guarantee if this feature will be selected, nor give an ETA for when it would be done if accepted.

**Comment by corico44** [comment]
@MTRNord We inform you that you can now use lz4 for default_toast_compression for postgresql. All the related information on how to configure it correctly can be found in the README: https://github.com/bitnami/containers/tree/main/bitnami/postgresql

Thank you very much for the contribution!
