### ISSUE TITLE
[stable/kubewatch] missing namespace filter support

### ISSUE THREAD

**Issue by rjanovski** [bitnami/charts#1159]
**Which chart**:

stable/kubewatch (latest, 0.0.4)

**Description**

the chart is missing the `namespace: "default"` config value.
even when adding it manually this does not seem to work.
for some reason, no filtration is happening

messages flooding the slack channel are preventing me from installing this chart altogether.

**Steps to reproduce the issue:**

1. install chart with proper slack token,channel
2. change kubewatch configmap manually to have namespace: default

**Describe the results you received:**

still flooded with all events from all namespaces

**Describe the results you expected:**

just events from default namespace sent to slack

**Additional information you deem important (e.g. issue happens only occasionally):**

Also: the README is not accurate in the use of --set. the example simply does not work.

**Comment by juan131** [comment]
Hi @rjanovski 

If I understood you correctly, you want the chart to set the configuration parameter below to the namespace where the chart is installed, don't you? Wouldn't it be better to have a parameter in the chart to modify that value?

https://github.com/bitnami-labs/kubewatch/blob/master/kubewatch-configmap.yaml#L7

> Also: the README is not accurate in the use of --set. the example simply does not work.

Do you mean the example below:

>  Specify each parameter using the `--set key=value[,key=value]` argument to `helm install`. For example,

> ```console
> $ helm install stable/kubewatch --name my-release \
>  --set=slack.channel="#bots",slack.token="XXXX-XXXX-XXXX"
> ```
```

What is wrong in that example? I don't see anything weird.

**Comment by rjanovski** [comment]
the namespace to limit resource events (not where chart should be installed) is not configurable from the chart, so no way to `--set namespace=default` or something like that. 
I need to manually go to the config map you mentioned and add it, as it is not there by default. 
and it still does not work; see https://github.com/bitnami-labs/kubewatch/issues/171

do not to confuse this request with the namespace of the chart deployment (helm install --namespace kube-system) which is totally independent. I'd rather install the chart to 'kube-system' and monitor events in 'default' in my case.

---
the `--set` that didn't work for me was actually in the kubewatch repo: https://github.com/bitnami-labs/kubewatch/blame/master/README.md#L48, (the additional quotes in `--set='...'` don't work)

**Comment by juan131** [comment]
Hi @rjanovski could you please check the PR I created to add a parameter so you can configure the namespace to watch with Kubewatch?

**Comment by juan131** [comment]
Hi @rjanovski 

We just merged the PR including the parameter for the namespace. Could you please give it a try?

**Comment by rjanovski** [comment]
the chart seems to be doing the right thing, but the behavior is the same. no filter by namespace and events poring from all namespaces.

also there is a PR in the queue (still open, 6mo old) to change/fix the namespace handling and syntax: https://github.com/bitnami-labs/kubewatch/pull/152/commits/82416b4feadd3bb37373745ec3d9cbd758a215e1

there seem to be no action on their side for some time now

**Comment by juan131** [comment]
I agree with you and I think the configuration is following the documentation provided at https://github.com/bitnami-labs/kubewatch/#resources

I'll ping the Kubewatch maintainers

**Comment by rosskusler** [comment]
I have a similar problem.  I specified a namespace in the .kubewatch.yaml file but it continued reporting on resource changes for all namespaces.

However filtering events from irrelevant namespaces isn't really sufficient, I don't watch kubewatch to even have access to view/get/watch events from other namespaces.  So I set rbac.create to false and manually created a Role and RoleBinding, but kubewatch just reports:

ERROR: logging before flag.Parse: E0514 18:05:07.853452       1 reflector.go:205] github.com/bitnami-labs/kubewatch/pkg/controller/controller.go:377: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:external-certs:external-certs-kubewatch" cannot list pods at the cluster scope

Is kubewatch capable of just watching for events from a single namespace (or set of namespaces) without listing things at the global scope?

**Comment by juan131** [comment]
Hi @rosskusler 

You should contact Kubewatch developers, they'll be able to provide you more information about that kind of configuration details.

For instance, you can reach them by opening an issue at https://github.com/bitnami-labs/kubewatch/issues

**Comment by rjanovski** [comment]
Good luck with that. See https://github.com/bitnami-labs/kubewatch/issues/144
