### ISSUE TITLE
[bitnami/postgresql-ha] Configure users

### ISSUE THREAD

**Issue by rerime** [bitnami/charts#11615]
### Name and Version

bitnami/postgresql-ha

### What is the problem this feature will solve?

Hi,
I was trying create users via initScript, but it is a little bit tricky.

I don’t want to duplicate configuration for postgres and pgpool.
It is not easy configure both of them via same values yaml section.

Could you provide the best way to do it?

### What is the feature you are proposing to solve the problem?

Easy configure custom user and database creation

**Comment by carrodher** [comment]
How are you trying to configure them via values.yaml? [Here](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#parameters) you can find the different parameters you have available. Apart from that, you can also customize the application by using custom init scripts or sidecars containers
