### ISSUE TITLE
[bitnami/redis] Replica config grows with each restart

### ISSUE THREAD

**Issue by armsnyder** [bitnami/charts#11629]
### Name and Version

bitnami/redis 17.0.8

### What steps will reproduce the bug?

1. Install the chart with Sentinel enabled, then trigger a container restart:

   ```shell
   helm install redis bitnami/redis --version 17.0.8 --set auth.enabled=false --set sentinel.enabled=true
   kubectl port-forward redis-node-0 6379
   redis-cli shutdown
   ```

2. Check the `replica.conf` and see that the same data was appended twice:

   ```shell
   kubectl exec redis-node-0 -c redis -- cat /opt/bitnami/redis/etc/replica.conf

   dir /data
   # User-supplied replica configuration:
   rename-command FLUSHDB ""
   rename-command FLUSHALL ""
   # End of replica configuration
   replica-announce-port 6379
   replica-announce-ip redis-node-0.redis-headless.default.svc.cluster.local

   replica-announce-port 6379
   replica-announce-ip redis-node-0.redis-headless.default.svc.cluster.local
   ```

### What do you see instead?

The `replica.conf` file grows with the same appended data after each container restart.

### Additional information

Issue appears to be caused by these lines:

https://github.com/bitnami/charts/blob/74e05c5c3e31b53508cba7365388b6710ba9c854/bitnami/redis/templates/scripts-configmap.yaml#L183-L185

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
