### ISSUE TITLE
Schema registry chart templating fails when using external kafka

### ISSUE THREAD

**Issue by romilpunetha** [bitnami/charts#11630]
### Name and Version

bitnami/schema-registry:4.x.x

### What steps will reproduce the bug?

1. Clone the chart.
2. in values.yaml, disable kafka and use external kafka.
3. template the chart.

### What is the expected behavior?

K8s templates should be created.

### What do you see instead?
```
Error: no template "commons.fullname" associated with template "gotpl"

Note: Error in Line no: https://github.com/bitnami/charts/blob/master/bitnami/schema-registry/templates/external-kafka-secrets.yaml#L19
```

**Comment by joancafom** [comment]
Hi @romilpunetha 

Thanks for reporting the issue! It seems this problem was already addressed in https://github.com/bitnami/charts/pull/11431.

Could you please check if it is working for you now?

**Comment by spanglerco** [comment]
It looks like the chart version got bumped in parallel to #11431 going in, so it didn't actually build a new version of the chart with the fix: https://github.com/bitnami/charts/actions/runs/2838925682
