### ISSUE TITLE
Override namespace with variable

### ISSUE THREAD

**Issue by SeglaSamaty** [bitnami/charts#11631]
### Name and Version

bitnami/postgresql 11.6.25

### What is the problem this feature will solve?

Hi all!
I'm trying to create chart that has postgresql and keycloak as subcharts with both deployed in their own namespaces.

To create my setup, it seems like the subcharts should have defined a variable to override the .metadata.namespace in every template file. 
Keycloak chart has one such variable (called 'namespaceOverride'), but Postgresql chart does not.

Is there any workaround to achieve my goal?

Can you consider adding such variable?

### What is the feature you are proposing to solve the problem?

Defining "namespaceOverride" variable to values.yaml that is used to override  .metadata.namespace in every template file.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
