### ISSUE TITLE
bitnami/postgresql "could not locate my own executable path" (m1 / rancher desktop)

### ISSUE THREAD

**Issue by vincentserpoul** [bitnami/charts#11640]
### Name and Version

bitnami/postgresql all versions

### What steps will reproduce the bug?

apple M1 arm
k3s running in rancher-desktop

### Are you using any custom parameters or values?

bare

helm install postgres bitnami/postgresql

### What is the expected behavior?

just running postgres

### What do you see instead?

The first pod crashes quickly with this log:

```
postgresql Mon 08 Aug 2022 12:05:23 PM UTCINFO  ==> ** Starting PostgreSQL **
LOG:  58P01: could not find a "-D" to execute
LOCATION:  find_my_exec, exec.c:217
LOG:  58P01: could not find a "-D" to execute
LOCATION:  find_my_exec, exec.c:217
FATAL:  XX000: -D: could not locate my own executable path
LOCATION:  getInstallationPaths, postmaster.c:1486
```

**Comment by vincentserpoul** [comment]
working on x86 linux k8s, so it is highly likely related to the m1 architecture.

**Comment by fmulero** [comment]
Hi

Could you take a look to #7305 ? At the moment we don't have support for ARM

**Comment by vincentserpoul** [comment]
I don't think it requires arm images, as it's running in rancher desktop, so through qemu?

**Comment by vincentserpoul** [comment]
I actually reverted back to rancher-desktop 1.4.1 and things are working as expected.
The issue probably lies in rancher-desktop.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
