### ISSUE TITLE
chart "airflow" version "8.0.7" not found in https://charts.bitnami.com/bitnami repository

### ISSUE THREAD

**Issue by romankydybets** [bitnami/charts#11643]
### Name and Version

bitnami/airflow:8.0.7

### What steps will reproduce the bug?

chart "airflow" version "8.0.7" not found in https://charts.bitnami.com/bitnami repository

### What do you see instead?

i would like to use this chart, cause in the new version it is having breaking changes, and engineer which is maintained DAGs is leave

**Comment by rafariossaa** [comment]
Hi,
  Could you take a [look to this pinned](https://github.com/bitnami/charts/issues/10833) issue ?
