### ISSUE TITLE
Variable "fullname" not found in node chart

### ISSUE THREAD

**Issue by lwj5** [bitnami/charts#1166]
**Which chart**: node (8.1.4)

**Description**

- [ ] Change claimName: {{ template "fullname" . }} to claimName: {{ template "node.fullname" . }} in charts/bitnami/node/templates/deployment.yaml

or define fullname in _helpers.tpl
- [ ] Increment chart version

**Steps to reproduce the issue:**

1. persistence.enabled = true

**Describe the results you received:**

Helm template failed. Error: render error in "node/templates/deployment.yaml": template: node/templates/deployment.yaml:147:33: executing "node/templates/deployment.yaml" at <{{template "fullname...>: template "fullname" not defined : exit status 1

**Describe the results you expected:**

Install

**Comment by juan131** [comment]
Thanks for reporting this issue @lwj5 !!!

I just created a PR to address it.

**Comment by juan131** [comment]
We just merged the changes addressing this issue @lwj5 
Thanks again for reporting it!
