### ISSUE TITLE
Kafka helm, prometheus monitor not working,metrics api request time out

### ISSUE THREAD

**Issue by arleex** [bitnami/charts#11690]
### Name and Version

bitnami/kafka-18.0.7

### What steps will reproduce the bug?

1. env
    k8s version:v1.21.5
2. run command
    kubectl create namespace kafka
    helm install saas bitnami/kafka --namespace kafka --version 18.0.7 --set metrics.serviceMonitor.enabled=true  --set metrics.kafka.enabled=true --set metrics.serviceMonitor.namespace=monitoring  --set metrics.serviceMonitor.interval=15s --set metrics.kafka.containerPorts.metrics=9309 --set metrics.kafka.service.ports.metrics=9309
3. prometheus request metrics api time out    
    Get "http://10.233.66.45:9309/metrics": context deadline exceeded

### Are you using any custom parameters or values?

--set metrics.serviceMonitor.enabled=true  --set metrics.kafka.enabled=true --set metrics.serviceMonitor.namespace=monitoring  --set metrics.serviceMonitor.interval=15s --set metrics.kafka.containerPorts.metrics=9309 --set metrics.kafka.service.ports.metrics=9309

### What is the expected behavior?

Prometheus monitor normally

### What do you see instead?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/24441899/183708282-fd2370cf-e297-46a2-b83f-134f01a6a44a.png">

### Additional information

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/24441899/183708509-30245a60-35d2-418c-ae1f-b35b4a83329f.png">

metrics api request time out

**Comment by migruiz4** [comment]
Hi @arleex,

Have you tried increasing the value `metrics.serviceMonitor.scrapeTimeout`?

I have found the following discussions reporting the same error and in both cases increasing the timeout was suggested: 
- https://discuss.prometheus.io/t/context-dealine-exceeded/975/3
- https://stackoverflow.com/questions/49817558/context-deadline-exceeded-prometheus
