### ISSUE TITLE
Adding maven dependency to ALL SCDF prepackaged apps via Helm charts.

### ISSUE THREAD

**Issue by marios390** [bitnami/charts#11699]
### Name and Version

bitnami/spring-cloud-data-flow

### What is the problem this feature will solve?

We need to add the following maven dependency to ALL prepackaged apps provided by SCDF.

<dependency>
    <groupId>software.amazon.msk</groupId>
    <artifactId>aws-msk-iam-auth</artifactId>
    <version>1.0.0</version>		
</dependency>

### What is the feature you are proposing to solve the problem?

Could you please provide the solution if already exists.

**Comment by rafariossaa** [comment]
HI,
  I am not familiar with SCDF development, but I guess you would need to add that to the image.
  I would suggest you to ask in SCDF forums, I think they could provide a better answer to this kind of questions.

**Comment by marios390** [comment]
Thanks a lot!
