### ISSUE TITLE
[binami/nginx-ingress-controller] RBAC role is misconfigured when using nameOverride

### ISSUE THREAD

**Issue by d-shi** [bitnami/charts#11716]
### Name and Version

bitnami/nginx-ingress-controller 9.2.27

### What steps will reproduce the bug?

1. use any value for `nameOverride` in `values.yaml`
2. add the nameOverride to the end of `electionID`
3. set `create: true` for both `serviceAccount` and `rbac`
4. apply the chart

### Are you using any custom parameters or values?

no

### What is the expected behavior?

The correct RBAC role is created, using the value provided for `nameOverride` in the `resourceName`.

### What do you see instead?

The RBAC role that gets created only allows updating the lease named `ingress-controller-leader` always, regardless of what is used for `nameOverride` or `electionID`, which results in the following in the logs because the name of the configmap that is created uses `nameOverride`:

```
E0810 21:25:27.083430       1 leaderelection.go:330] error retrieving resource lock kube-system/ingress-controller-leader-internal: leases.coordination.k8s.io "ingress-controller-leader-internal" is forbidden: User "system:serviceaccount:kube-system:ingress-nginx-internal" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

I believe the problem is here https://github.com/bitnami/charts/blob/1ae90e5fbcd3e96a04d03b950c2b821c29976cb6/bitnami/nginx-ingress-controller/templates/role.yaml#L100

**Comment by d-shi** [comment]
Ah, I think I may have been confused by various versions running in our environment... will close this for now.

**Comment by d-shi** [comment]
OK, this is still a problem in the latest version, but with leases instead of configmaps... re-opening this, and I udpated the info in the original post.

**Comment by rafariossaa** [comment]
Hi,
  [This PR](https://github.com/bitnami/charts/pull/11761) was merged. I think it should fix this issue. 
  Could you check it ?
