### ISSUE TITLE
Add Helm Chart to install Skooner on Kubernetes clusters

### ISSUE THREAD

**Issue by pcgeek86** [bitnami/charts#11721]
### Name and Version

doesntexistyet

### What is the problem this feature will solve?

Skooner is a Kubernetes cluster monitoring web UI. The Kubernetes community would benefit from having this installable via a Bitnami Helm Chart.

https://github.com/skooner-k8s/skooner/

<img width="1670" alt="Screen Shot 2022-08-11 at 2 10 35 AM" src="https://user-images.githubusercontent.com/466713/184091060-12512031-1640-4114-98c8-2694bba64bb0.png">

### What is the feature you are proposing to solve the problem?

Add a new Helm Chart for Skooner

### What alternatives have you considered?

n/a

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
