### ISSUE TITLE
extraVolumeMount

### ISSUE THREAD

**Issue by anilnokia** [bitnami/charts#11729]
### Name and Version

airflow

### What steps will reproduce the bug?

Trying to mount a volume from hostpath. Do you have proper syntax? It does not work for me. 

### Are you using any custom parameters or values?

no

### What is the expected behavior?

It does not mount hostpath volume.

### What do you see instead?

no volume in the container

**Comment by carrodher** [comment]
Could you please elaborate a bit more on how are you trying to do it?
