### ISSUE TITLE
how to access redis sentinel out of kubernetes cluster?

### ISSUE THREAD

**Issue by willzhang** [bitnami/charts#11753]
### Name and Version

bitnami/redis v7.0.4

### What steps will reproduce the bug?

install redis sentinel
```
helm upgrade --install redis redis/redis --namespace redis --create-namespace \
  --set architecture=replication \
  --set global.redis.password=redis \
  --set sentinel.enabled=true \
  --set sentinel.service.type=NodePort \
  --set sentinel.service.nodePorts.redis=31331 \
  --set sentinel.service.nodePorts.sentinel=32331
```

Get service, here so many ports, i want know which ports should be used for connect to sentinel out of kubernetes cluster?
```
root@node01 # kubectl -n redis get svc
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                                                          AGE
redis            NodePort    10.96.2.61    <none>        31331:31331/TCP,32331:32331/TCP,26379:30768/TCP,6379:32276/TCP   25m
redis-headless   ClusterIP   None          <none>        6379/TCP,26379/TCP                                               25m
redis-node-0     NodePort    10.96.1.178   <none>        32332:32332/TCP,31332:31332/TCP,26379:32604/TCP,6379:32254/TCP   25m
redis-node-1     NodePort    10.96.1.189   <none>        32333:32333/TCP,31333:31333/TCP,26379:30816/TCP,6379:32217/TCP   25m
redis-node-2     NodePort    10.96.2.103   <none>        32334:32334/TCP,31334:31334/TCP,26379:32064/TCP,6379:31483/TCP   25m
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Use nodeport connect success.

### What do you see instead?

connect failed,  i use [AnotherRedisDesktopManager ](https://github.com/qishibo/AnotherRedisDesktopManager/releases)

192.168.72.50 is one of Kubernetes cluster node ip

![redis-02.png](https://s2.loli.net/2022/08/14/qQlzI6tmWU9FnTC.png)

![redis-01.png](https://s2.loli.net/2022/08/14/6QPthgikdG7e4l2.png)

**Comment by carrodher** [comment]
When deploying the Helm chart some installation notes appear in the console showing information about how to connect/access the application based on the parameters you used to deploy the Helm chart. You can see those notes at any time after the installation by running `helm get notes RELEASE_NAME`.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by srinivasmummareddy** [comment]
Any breakthrough on this?
