### ISSUE TITLE
Can not create grafana on different namespace from grafana-operator namespace

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#11754]
### Name and Version

bitnami/grafana-operator

### What steps will reproduce the bug?

I have set
```yaml
          args:
            - --grafana-image=docker.io/bitnami/grafana
            - --grafana-image-tag=8.5.2-debian-10-r4
            - --grafana-plugins-init-container-image=docker.io/bitnami/grafana
            - --grafana-plugins-init-container-tag=8.5.2-debian-10-r4
            - --leader-elect=True
            - --scan-all=True
```
and I have clusterRole and clusterRoleBinding but I can't create grafana instance of a different namespace.
What should I do?

I also do this job with helm:
`helm template all bitnami/grafana-operator --set grafana.enabled=false --set operator.scanAllNamespaces=true -n grafana`

and then apply yaml file of Grafana.
but nothing changed.

### What do you see instead?

Grafana instance not created in another namespace.

**Comment by carrodher** [comment]
Please note this Grafana Helm chart is designed to work with Grafana 9, being at this moment `9.0.7` the version used.
We do not guarantee that using an older Grafana major will work out of the box.

Apart from that, support is provided for deployments using `helm` and the regular installation process, for any other kind of deployments we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by arezvani** [comment]
I think this problem not from my version and when I change my version, my problem doesn't solve.
If I don't want to have grafana-operator and grafana in same namespace what should I do?

**Comment by carrodher** [comment]
At this moment this is not a scenario supported by the Helm chart, the different resources are deployed within the same namespace. Would you like to contribute by creating a PR adding this feature? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
