### ISSUE TITLE
Support using image digests and not only tags

### ISSUE THREAD

**Issue by vrabbi** [bitnami/charts#11752]
### Name and Version

All Charts

### What is the problem this feature will solve?

currently the bitnami charts require us to use tags for image references and we cant use digests without also including a tag which is not very user friendly.
It would be great if the Helm Charts supported passing in a digest or a tag and accrodingly would set the correct image references in the attempt to support more secure, stable and best practices developed over the last years where image digests are becoming the preferred method of referencing an image.

### What is the feature you are proposing to solve the problem?

Add a digest field to the image structs in the helm charts and if it is set, it overrides the tag value and is used.

### What alternatives have you considered?

not using digests and having a less optimal situation in our environments

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this.
  I am creating an internal issue to discuss and implement it if considered.
  We will come back as soon as we have news.
