### ISSUE TITLE
SeaweedFS(MinIO alternative) helm chart

### ISSUE THREAD

**Issue by Oyelowo** [bitnami/charts#11758]
### Name and Version

None yet Available

### What is the problem this feature will solve?

Presently, we only have only one option for deploying a distributed object storage using  `MinIO`'s bitnami's helm-chart.
Having an alternative is generally a good thing for the community for those that want to leverage capabilities that `SeaWeed` offers but not `MinIO`

For example, `SeaweedFS` - an open-source distributed storage solution - still supports S3 API Gateway which is being deprecated by MinIO (https://github.com/minio/minio/issues/14331) amongst others. 

While I understand MinIO's decision to transition away from S3 backend, having a viable alternative would be good for the community for those that need those extra features to be actively maintained

### What is the feature you are proposing to solve the problem?

- Create a robust helm chart for `SeaweedFS` using the official operator(https://github.com/seaweedfs/seaweedfs-operator) and current MinIO's helm chart as inspirations.

Link to SeaWeedFS: https://github.com/seaweedfs/seaweedfs

### What alternatives have you considered?

Using the seaweedfs's kuberentes operator: https://github.com/seaweedfs/seaweedfs-operator

**Comment by fmulero** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources that could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by Oyelowo** [comment]
Awesome! You guys are amazing!

**Comment by Oyelowo** [comment]
Let me know if there's anything I can do to hrlp

**Comment by wibed** [comment]
@Oyelowo 

reading the documentation of https://github.com/seaweedfs/seaweedfs#quick-start-for-s3-api-on-docker
the comparison puts minio as a possible gateway to seaweedfs, not providing a gateway itself.

maybe i have misread. if you could clarify would be appreciated.

**Comment by Oyelowo** [comment]
@wibed Not sure I understand you correctly but it’s possible to use s3 api with seaweedfs and also mount it to a cloud storage in cloud drive mode, this way it caches some files locally and asynchronously write back to the cloud storage. 
https://github.com/seaweedfs/seaweedfs/wiki/Cloud-Drive-Architecture. 


Let me know if this answers your question

**Comment by Stonedge** [comment]
> @Oyelowo
> 
> reading the documentation of https://github.com/seaweedfs/seaweedfs#quick-start-for-s3-api-on-docker the comparison puts minio as a possible gateway to seaweedfs, not providing a gateway itself.
> 
> maybe i have misread. if you could clarify would be appreciated.

I think you talk about the example of using "mino gateway"(now deprecated) in front seaweedfs to be able to leverage a better gui... minio gateway was a feature of mino that enable people to use minio as a proxy to another storage ( in the mode minio is NOT the storage provider but another service is). For example the mode enable you to get minio (good UI, policies, versionings,s3 api) in front of an azure storage account.

Using it as a frontend gui of seaweedfs would has been great, but now that feature is deprecated I don't know if the "minio distributed" mode could achieve the same behavior...

Hope it help

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
