### ISSUE TITLE
Metrics support for bitnami/oauth2-proxy helm chart

### ISSUE THREAD

**Issue by navingunaratne** [bitnami/charts#11751]
### Name and Version

bitnami/oauth2-proxy 3.1.0

### What is the problem this feature will solve?

Exposing metrics and service monitor features in bitnami/oauth2-proxy chart

### What is the feature you are proposing to solve the problem?

adding metrics support to bitmani/oauth2-proxy chart.

### What alternatives have you considered?

oauth2-proxy default helm chart has support for enabling metrics and service monitor. https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy

**Comment by carrodher** [comment]
Thanks for the suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
