### ISSUE TITLE
bitnami/kafka upgrade deletes all data

### ISSUE THREAD

**Issue by ZeroVocabulary** [bitnami/charts#11755]
### Name and Version

bitnami/kafka 18.0.7 to 18.0.8 upgrade

### What steps will reproduce the bug?

I upgraded kafka with helm upgrade and the upgrade wiped all data. I think it recreated the pvc, which deleted the pv due to the default reclaim policy "delete", but I'm not sure. Very painful 😅😭.

I was able to consistently reproduce the deletion by following the steps below. Please let me know if I am taking the wrong approach, I am a bit new to helm.
```
# install old version of bitnami/kafka
helm upgrade --install kafka-main bitnami/kafka --version 18.0.7

# adding data
# start kafka-client
kubectl run kafka-main-client --restart='Never' --image docker.io/bitnami/kafka:3.2.1-debian-11-r4 --namespace default --command -- sleep infinity

# get shell to kafka-client
kubectl exec --tty -i kafka-main-client --namespace default -- bash

# start producer script
kafka-console-producer.sh --broker-list kafka-main-0.kafka-main-headless.default.svc.cluster.local:9092 --topic test

#add some message
abc123

# then exit the producer script
# read from consumer with consumer script, you will see your message
kafka-console-consumer.sh --bootstrap-server kafka-main.default.svc.cluster.local:9092 --topic test --from-beginning


# exit kafka-client shell
# now upgrade helm installation
helm upgrade --install kafka-main bitnami/kafka

# go back into kafka-client shell
kubectl exec --tty -i kafka-main-client --namespace default -- bash

# read from consumer again, the message is no longer there
kafka-console-consumer.sh --bootstrap-server kafka-main.default.svc.cluster.local:9092 --topic test --from-beginning
```

### What is the expected behavior?

Kafka upgrades without deleting data and continues as normal.

### What do you see instead?

The upgrade wipes existing data.

**Comment by alemorcuq** [comment]
Hi, @ZeroVocabulary. I have reproduced this. It doesn't look like the PVCs are being recreated, in fact the topic seems to be there after the upgrade. However, as you say, after performing the upgrade I am unable to read the previous messages. I will create an internal ticket to investigate this.
