### ISSUE TITLE
[bitnami/schema-registry] Empty password error on upgrade when using external Kafka with plaintext auth

### ISSUE THREAD

**Issue by spanglerco** [bitnami/charts#11762]
### Name and Version

bitnami/schema-registry 4.0.5

### What steps will reproduce the bug?

Contrived example for demonstration that doesn't require a separate chart:

1. `helm install my-registry bitnami/schema-registry --set kafka.enabled=false`
2. `kubectl delete secret my-registry-external-kafka`
3. `helm upgrade my-registry bitnami/schema-registry --set kafka.enabled=false`

The actual scenario where I'm running into this issue:

1. Install some helm chart
2. Add schema-registry as a subchart to the chart you previously installed
3. Upgrade your helm deployment with `--set kafka.enabled=false`

### Are you using any custom parameters or values?

values.yaml of a chart that includes schema-registry as a subchart:

```yaml
schema-registry:
  nameOverride: dfs-schema-registry
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  pdb:
    create: true
  kafka:
    enabled: false
  externalKafka:
    brokers: PLAINTEXT://dfs-kafka-cluster-kafka-bootstrap:9092
```

### What is the expected behavior?

Installation succeeds. Since `externalKafka.auth.protocol` defaults to `plaintext`, the `externalKafka.auth.jaas.password` value should be irrelevant and the `%s-external-kafka` secret should not get created.

### What do you see instead?

(Note that "dfs" is the top-level chart that includes schema-registry and mongodb as subcharts)

```
Error: UPGRADE FAILED: template: dfs/charts/schema-registry/templates/external-kafka-secrets.yaml:19:23: executing "dfs/charts/schema-registry/templates/external-kafka-secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "client-password" "providedValues" (list "externalKafka.auth.jaas.password") "context" $)>: error calling include: template: dfs/charts/mongodb/charts/common/templates/_secrets.tpl:111:6: executing "common.secrets.passwords.manage" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $.context)>: error calling include: template: dfs/charts/mongodb/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'externalKafka.auth.jaas.password' must not be empty, please add '--set externalKafka.auth.jaas.password=$CLIENT_PASSWORD' to the command. To get the current value:

        export CLIENT_PASSWORD=$(kubectl get secret --namespace "default" dfs-dfs-schema-registry -o jsonpath="{.data.client-password}" | base64 -d)
```

### Additional information

It seems like the external-kafka-secrets.yaml template should skip creating the secret (and the password validation) if `externalKafka.auth.protocol` isn't `sasl` or `sasl_tls`. The statefulset.yaml template doesn't even reference the secret unless the protocol is one of the `sasl` ones.

**Comment by fmulero** [comment]
Sorry @spanglerco I don't have any news yet, please bear with me

**Comment by fmulero** [comment]
Thanks @spanglerco for such detailed explanation. I've just created a PR to fix this issue
