### ISSUE TITLE
Getting mongoDB chart error updating chart version from 7.13.0 to 10.30.12

### ISSUE THREAD

**Issue by dcvtruong** [bitnami/charts#11766]
### Name and Version

bitnami/mongodb 10.30.12

### What steps will reproduce the bug?

1. mongoDB chart verion 7.13.0 no longer exist
2. update the chart version 10.30.12
3. getting error from history.go

```
Error: history.go:56: [debug] getting history for release mongodb
Error: found in Chart.yaml, but missing in charts/ directory: common
helm.go:88: [debug] found in Chart.yaml, but missing in charts/ directory: common
```

### Are you using any custom parameters or values?

```
Command: ./shellai-jenkins-shared-lib/utilities/helm_deploy.py --namespace lithosenz --chartName mongodb --chartPath ./finalcharts/mongodb --operation upgrade --revision 0 --dryRun true 
```

### What is the expected behavior?

The command was working correctly with mongoDB chart 7.13.0 until the chart no longer exist.  Replaced the chart version with 10.30.12

### What do you see instead?

Error: history.go:56: [debug] getting history for release mongodb
Error: found in Chart.yaml, but missing in charts/ directory: common
helm.go:88: [debug] found in Chart.yaml, but missing in charts/ directory: common

**Comment by fmulero** [comment]
Hi @dcvtruong 

I think you are installing the chart from a local copy, Have you updated the dependencies in your copy?

```
$ helm dep build ./finalcharts/mongodb
```

**Comment by dcvtruong** [comment]
@fmulero I was able to update the chart.  Thanks for the feedback!
