### ISSUE TITLE
Support Keycloak 19

### ISSUE THREAD

**Issue by martincolladodev** [bitnami/charts#11779]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Keycloak v19 was released a few weeks ago and would be really nice to have support for that version on the Keycloak helm chart. 

https://www.keycloak.org/2022/07/keycloak-1900-released

### What is the feature you are proposing to solve the problem?

Add support for Keycloak v19 to the bitnami/keycloak helm chart

**Comment by carrodher** [comment]
As it is a new major version we need to perform different manual actions in our internal test & release pipeline, that's why the new version is not automatically released. Once done those actions, we will release a new version and update this GH issue.

**Comment by gongomgra** [comment]
Hi @martincolladodev,

Thanks for using Bitnami. Just a quick note to let you know that we have just released a new major version of our Keycloak chart (version 10.0.0) including Keycloak version 19.0.1.

Best regards,
Gonzalo
