### ISSUE TITLE
[bitnami/apache] [Question] Why initialDelaySeconds is needed?

### ISSUE THREAD

**Issue by JoniJnm** [bitnami/charts#11770]
### Name and Version

bitnami/apache

### What is the problem this feature will solve?

Why the `readinessProbe.initialDelaySeconds` is needed?

https://github.com/bitnami/charts/blob/6cb91fc2558d21754357e5ef2b1dee6fdb93e272/bitnami/apache/values.yaml#L298

The apache chart uses 30 seconds

If the `readinessProbe` is doing a `http` request to `/`, why the `initialDelaySeconds` is needed? If the call is success, why not just to use 0 delay?

Is there a problem in kubernetes services or apache and that's why the chart uses a high initialDelaySeconds? Your [nginx chart](https://github.com/bitnami/charts/blob/b786e6e7e7d2431c61aa6bd2dacef14e29c24768/bitnami/nginx/values.yaml#L317) uses 5 seconds.

### What is the feature you are proposing to solve the problem?

set `initialDelaySeconds=0` in `startupProbe`, `livenessProbe` and `readinessProbe`

If the container needs to do a migration or an [initial setup](https://github.com/bitnami/containers/blob/main/bitnami/apache/2.4/debian-11/rootfs/opt/bitnami/scripts/apache/entrypoint.sh#L22) maybe the chart should enable `startupProbe`. So the entry point migrates or do the initial setup and then starts apache? `startupProbe.failureThreshold` could be very high to let the migration/setup ends, but with an initial daily = 0

**Comment by JoniJnm** [comment]
@fmulero maybe something like this?

**Comment by fmulero** [comment]
👍  Let me check the PRs

**Comment by JoniJnm** [comment]
:(

**Comment by fmulero** [comment]
I have to work on it this week. Sorry Jónatan

**Comment by JoniJnm** [comment]
Oh my god...
