### ISSUE TITLE
bitnami/postgresql does not support mixed-case database names

### ISSUE THREAD

**Issue by docktermj** [bitnami/charts#1179]
**Which chart**:

bitnami/postgresql

**Description**

Using the bitnami/postgresql chart (https://github.com/bitnami/charts/tree/master/upstreamed/postgresql), I'm trying to make a PostgreSQL database named "G2"  (uppercase "G").   No matter what I've tried, it always seems to result in a database named "g2" (Lowercase "g").   ...and that breaks all down-stream database access.

By the way, this docker-compose file does show that PostgreSQL supports a mixed-case "G2" database name:  https://github.com/Senzing/docker-compose-demo/blob/ffb8fa2967f81ac2520530ac8636a7e46b7d6a2b/docker-compose-kafka-postgresql.yaml#L49-L62

According to PostgreSQL documentation,  mixed-case database names need to be quoted.

**Steps to reproduce the issue:**

```
helm install \
  --values ${VALUES_FILE} \
  bitnami/postgresql
```

Where ${VALUES_FILE} is https://github.com/Senzing/kubernetes-demo/blob/7e05bfb683937a41014017bf307d4dc5c49140aa/helm-values-templates/postgresql.yaml

Notice that the database name requested in the ${VALUES_FILE} is "G2", but the database created is "g2"

**Describe the results you received:**

A database incorrectly named "g2".

**Describe the results you expected:**

A database named "G2".

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/bitnami/charts/blob/b64915ad9bff784b32cf363fd613cb27682a6c62/upstreamed/postgresql/values.yaml#L97-L100

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @docktermj 

What version of the Bitnami PostgreSQL image are you using? That error should have been fixed on this PR:

https://github.com/bitnami/bitnami-docker-postgresql/pull/135

In other words, if you're using any of the PostgreSQL versions below, it should work!

- 9.6 series: **9.6.12-r73**
- 10 series: **10.7.0-r72**
- 11 series: **11.2.0-r73**

**Comment by docktermj** [comment]
I didn't specify, so I must have been using the default `10.7.0`.

Reference:  https://github.com/bitnami/charts/blob/285cebb4652fe041026986274927cca53bb8f133/upstreamed/postgresql/values.yaml#L14-L17

**Comment by juan131** [comment]
Hi @docktermj 

What's the pullPolicy you're using on your statefulset? Is it 'Always'? 
Could you ensure it downloads the latest version `bitnami/postgresql:10.7.0`? Please note that `10.7.0` is a rolling tag and it points to the latest revision published when pulling the image.

**Comment by docktermj** [comment]
Yes,  `pullPolicy: Always", is used

Reference from initial `--values helm-values-templates/postgresql.yaml` parameter:
https://github.com/Senzing/kubernetes-demo/blob/7e05bfb683937a41014017bf307d4dc5c49140aa/helm-values-templates/postgresql.yaml

**Comment by docktermj** [comment]
```
image:
  pullPolicy: Always
  tag: 10.7.0-r72
```
Worked.   Will now try without a `tag:`, but continue with `Always`.

**Comment by docktermj** [comment]
OK,  Now

```
image:
  pullPolicy: Always
```
is working.   I'm not exactly sure what changed,  maybe a stuck cached docker image on my side.   In any case, I'm considering this issue closed.

@juan131 Thanks for the guidance!!!

**Comment by juan131** [comment]
You're welcome @docktermj 

I'm glad you were able to solve the issue once the latest image was pulled!
