### ISSUE TITLE
Issue in Upgrading Bitnami Postgres chart from 10.16.2 to 11.6.26:CreateContainerConfig error

### ISSUE THREAD

**Issue by jramneet** [bitnami/charts#11799]
### Name and Version

bitnami/postgres 11.6.26

### What steps will reproduce the bug?

Upgrading the Bitnami chart version from 10.16.2 to 11.6.26, the pod error with CreateContainerConfig
with error `Error: couldn’t find key password in Secret`

### What do you see instead?

The chart is updated with the new version but the pod creation fails with the error mentioned above

Are there any extra steps to be taken for the upgrade from 10 to 11?

**Comment by carrodher** [comment]
Can you share with us the command you are running for the upgrade?

[Here](https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#to-1100) you can find the upgrade notes for this version and the recommended process
