### ISSUE TITLE
Error: "no template "common.names.fullname" associated with template "gotpl"" while doing "helm lint" from "charts/bitnami/argo-workflows" directory

### ISSUE THREAD

**Issue by queensaikia** [bitnami/charts#11832]
### Name and Version

bitnami/argo-workflow-controller:3.3.8-scratch-r5

### What steps will reproduce the bug?

1. Cloned the git repo
2. Went inside charts/bitnami/argo-workflows directory
3. helm lint

### What is the expected behavior?

Successfully packaged chart and saved it to: /home/dell/argo-workflows-2.3.7.tgz

### What do you see instead?

[ERROR] templates/: template: argo-workflows/templates/server/service.yaml:4:11: executing "argo-workflows/templates/server/service.yaml" at <include "argo-workflows.server.fullname" .>: error calling include: template: argo-workflows/templates/_helpers.tpl:26:26: executing "argo-workflows.server.fullname" at <include "common.names.fullname" .>: error calling include: template: no template "common.names.fullname" associated with template "gotpl"
[WARNING] /home/dell/bitnami-sample-argo/charts/bitnami/argo-workflows: chart directory is missing these dependencies: postgresql,mysql,common
![Screenshot (1016)](https://user-images.githubusercontent.com/39208364/185406308-6f67f49f-0877-4dba-8002-3f73ad98fddf.png)

**Comment by rafariossaa** [comment]
Hi,
  As you can see bye the error, you are missing the dependencies. You would need to download them first.
  Try running `helm dependency build` before running `helm lint`.
