### ISSUE TITLE
Not able to copy 100 percent data and ttl from one redis cluster to another redis cluster

### ISSUE THREAD

**Issue by Shujja1746** [bitnami/charts#11839]
### Name and Version

bitnami/redis-cluster and version 8.1.4

### What steps will reproduce the bug?

deploy redis cluster with 6 nodes and try to transfer/copy data from source redis cluster to destination redis cluster 

Use Riot redis to transfer data 
https://developer.redis.com/riot/riot-redis/

### Are you using any custom parameters or values?

./riot-redis [source redis-cluster] [destination-redis-cluster]

### What is the expected behavior?

Data is not transfering 100 percent

### What do you see instead?

only 96 to 98 percent data is getting copy with ttl

### Additional information

Looking for any migration or copy command to transfer data for bitnami redis clusters

**Comment by rafariossaa** [comment]
Hi,
  I think this is not related to the chart. 
  I would suggest to post this issue in the riot-redis forums, I think they could provide a better support for this.

**Comment by Shujja1746** [comment]
what are the tool best to copy data from redis-clusters.

Can you please let me know on this.

Thanks

**Comment by rafariossaa** [comment]
Hi,
  Not sure why riot is changing the number of nodes in the cluster, I am not familiar with that tool. Depending how tool is doing that it could lead to nodes without the proper parameters hence they are not starting properly.
  It would be very helpful to have a sequence of steps to reproduce this issue, if not, it is very hard to reproduce it on our side.
  Regarding the copy tool, I can not suggest one I am not familiar with them, I would suggest you to better ask for this in redis forums, they could give you a better recommendation for your use case.
