### ISSUE TITLE
about common/2.x backward imcompatibility

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#11858]
### Name and Version

bitnami/common 2.0.0

### What is the problem this feature will solve?

as https://github.com/bitnami/charts/pull/11844 was closed,
I wonder about the reasonning of the 2 imcompatible changes:
* remove support of empty repositoryName
* make `image.digest`  mandatory (at least defined as an empty string)

### What is the feature you are proposing to solve the problem?

the behavior 1.x behavior can be reintroduced in  2.x :)

### What alternatives have you considered?

I could have changed the Chart.yaml version to 2.0.1 (instead of 1.7.2) to make 2.x compatible with 1.x in the closed PR

**Comment by carrodher** [comment]
> remove support of empty `repositoryName`
You mean `registryName`, right?

By default, this parameter is set to `docker.io` in all the charts; but, in the future, it could be a different registry, `docker.io` is just an option and the default one nowadays.

Apart from that, this allows users to customize the registry with any other valid registry to pull the container images from.
If the user changes it to a custom registry it will work as usual, but if it is modified leaving it empty there is not any reason to do a fallback to `docker.io` which is what is set by default so it is not needed to remove the default value.

In this way, we always should have a registry defined in an explicit way without relying on assumptions like default registry = docker.io. With the current approach, the image pull will fail with a descriptive message 

> make `image.digest` mandatory (at least defined as an empty string)
It will be mandatory in all the `values.yaml` files once bumped the bitnami/common subchart version in a major pointing to 2.x.x. We prefer to keep all the available parameters listed in the `values.yaml` and `README.md` although its default value is empty, in that way users know about its existence and can use them.

**Comment by jouve** [comment]
Thanks for explaining the rationale 👍

**Comment by sbienkow-ninja** [comment]
> > remove support of empty `repositoryName`
> 
> You mean `registryName`, right?
> 
> By default, this parameter is set to `docker.io` in all the charts; but, in the future, it could be a different registry, `docker.io` is just an option and the default one nowadays.
> 
> Apart from that, this allows users to customize the registry with any other valid registry to pull the container images from. If the user changes it to a custom registry it will work as usual, but if it is modified leaving it empty there is not any reason to do a fallback to `docker.io` which is what is set by default so it is not needed to remove the default value.
> 
> In this way, we always should have a registry defined in an explicit way without relying on assumptions like default registry = docker.io. With the current approach, the image pull will fail with a descriptive message

I'm not sure I follow the rationale here - whether a chart defined `docker.io` as a registry or not, you can still override it yourself in the values file. There was no fallback to `docker.io` in the common code - if the image name lacked host, then the container daemon (be it docker or whatever else) fall back to using `docker.io` as the host. 

This change broke our flow, as we do pass the whole image name - i.e. `gcr.io/example-bucket/example-image` as `repositoryName`. This greatly simplifies our setup, and we'd prefer to keep it this way if possible. Would a PR restoring this behavior be accepted?

If not, would a PR making it so that empty `registryName` raises a clear error be accepted?
