### ISSUE TITLE
[bitnami/nginx] Load JS Module - How ?

### ISSUE THREAD

**Issue by noelashford** [bitnami/charts#11851]
### Name and Version

nginx/latest

### What steps will reproduce the bug?
```console
$ ls -la /opt/bitnami/nginx/modules
total 844
drwxr-xr-x. 2 root root    154 Aug  8 20:43 .
drwxrwxr-x. 1 root root     29 Aug  9 06:28 ..
-rwxr-xr-x. 1 root root 806696 Jul 19 21:46 ngx_http_brotli_filter_module.so
-rwxr-xr-x. 1 root root  14784 Jul 19 21:46 ngx_http_brotli_static_module.so
-rwxr-xr-x. 1 root root  19144 Jul 19 21:46 ngx_http_geoip2_module.so
-rwxr-xr-x. 1 root root  19032 Jul 19 21:46 ngx_stream_geoip2_module.so
```

### Are you using any custom parameters or values?

No - This is what I need help on

### What is the expected behavior?

It should include these as files + load the module in standard config::
```console
$ ls -la /opt/bitnami/nginx/modules
total 844
drwxr-xr-x. 2 root root    154 Aug  8 20:43 .
drwxrwxr-x. 1 root root     29 Aug  9 06:28 ..
-rwxr-xr-x. 1 root root 806696 Jul 19 21:46 ngx_http_brotli_filter_module.so
-rwxr-xr-x. 1 root root  14784 Jul 19 21:46 ngx_http_brotli_static_module.so
-rwxr-xr-x. 1 root root  19144 Jul 19 21:46 ngx_http_geoip2_module.so
-rwxr-xr-x. 1 root root  19032 Jul 19 21:46 ngx_stream_geoip2_module.so
```

### What do you see instead?

The files are missing & the module is not loaded so index.js is impossible as such

### Additional information

Help is needed with clear exact steps on how to do this

**Comment by fmulero** [comment]
Hi @noelashford 

Just to confirm, You need support about how to add JS (or any) module and enable it for your site. Is that correct?

Have you taken a look to issues like #4857 or #4121?

**Comment by noelashford** [comment]
That is correct. Seeing the module is not there, firstly how do I add it,
second - how do I enable it / load it config wise.

**Comment by carrodher** [comment]
Could you check those existing issues? 
- https://github.com/bitnami/charts/issues/4857
- https://github.com/bitnami/charts/issues/4121
