### ISSUE TITLE
[bitnami/mongodb] Mongodb with tls.enabled=true mongosh not able to connect

### ISSUE THREAD

**Issue by ginofrid** [bitnami/charts#11965]
### Name and Version

bitnami/mongodb 13.0.2

### What steps will reproduce the bug?

In K8S (version 1.23) using most default chart parameters and `tls.enabled=true`. Following the instructions output by the chart install. `mongosh` command fails to connect. 
Instructions: `mongosh admin --host "mongodb-0.mongodb-headless.mongo2.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongo2.svc.cluster.local:27017,mongodb-2.mongodb-headless.mongo2.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD`

### Are you using any custom parameters or values?
```
--set architecture=replicaset,auth.replicaSetKey=*******,replicaCount=3 
--set auth.enabled=true,auth.rootPassword=****,auth.usernames[0]=mongo,auth.passwords[0]=****,auth.databases[0]=www
--set tls.enabled=true
```
### What is the expected behavior?

For `mongosh` to connect successfully. 

### What do you see instead?
```
Connecting to:		mongodb://<credentials>@mongodb-0.mongodb-headless.mongo2.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongo2.svc.cluster.local:27017,mongodb-2.mongodb-headless.mongo2.svc.cluster.local:27017/admin?authSource=admin&appName=mongosh+1.5.4
MongoServerSelectionError: connection <monitor> to 10.100.250.55:27017 closed
```

**Comment by fmulero** [comment]
Hi @ginofrid 

Thanks for raising this issue. `tls.enabled=true` enables mutual tls, so your client should specify a certificate (`--tls --tlsCertificateKeyFile <client-keyfile-pem-format> --tlsCAFile <ca-file-pem-format>`). In this case, by default the certificates are autogenerated, so you can find these certificates/keys in the <release>-mongodb-ca secret.
