### ISSUE TITLE
How to monitor kafka in promethous-operator

### ISSUE THREAD

**Issue by abhi-dwivedi** [bitnami/charts#1197]
hi 

How to monitor kafka in Prometheus-operator

How can i export from kafka exporter

**Comment by juan131** [comment]
Hi @abhi-dwivedi 

As you'll find in the [Kafka REAMD.md file](https://github.com/bitnami/charts/blob/master/bitnami/kafka/README.md), you just need to set the parameter `metrics.kafka.enabled` to true. After that, the corresponding Prometheus exporter would be created so Prometheus can collect the metrics from your containers.

**Comment by abhi-dwivedi** [comment]
Hi

I did the same but not able to see the Target in Prometheus operator 

Could you please lil bit explain how to configure.

Regards
Abhinav D

**Comment by abhi-dwivedi** [comment]
any update?

**Comment by juan131** [comment]
Hi @abhi-dwivedi 

As you can see when you install the chart with that parameter enabled, a deployment with the Kafka exporter is created:

```
$ helm install bitnami/kafka --name kafka --set metrics.kafka.enabled=true
$ kubectl get deploy
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
kafka-exporter   1/1     1            1           1m5s
$ kubectl get pods
NAME                              READY   STATUS        RESTARTS   AGE
kafka-0                           1/1     Running       0          1m21s
kafka-exporter-7874688cfc-59wfp   1/1     Running       1          1m21s
kafka-zookeeper-0                 1/1     Running       0          1m21s
```

Therefore, you should be able to retrieve the metrics from the exporter by port-forwarding to the exporter pod in the port **9308**:

```
$ kubectl port-forward kafka-exporter-7874688cfc-59wfp 9308:9308 &
$ curl 127.0.0.1:9308/metrics
Handling connection for 9308
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 10
...
```

**Comment by abhi-dwivedi** [comment]
I have seen my Kafka exporter is up and running now how can I see these matrix in Prometheus operator

**Comment by abhi-dwivedi** [comment]
any update ?

**Comment by abhi-dwivedi** [comment]
when i run above curl command i am getting the metrix

Handling connection for 9308
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 11
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.162216e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.162216e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.443293e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 1176
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 169984
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.162216e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 540672
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 2.113536e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 11918


BUT dont know how to see in Prometheous-operator

**Comment by abhi-dwivedi** [comment]
any updat e??

**Comment by abhi-dwivedi** [comment]
Hi 

Could you please tell me how JMX metrix will populate in kafka exporter and then in Grafana

**Comment by juan131** [comment]
Hi @abhi-dwivedi 

I installed Prometheus using Helm:

```
$ helm install stable/prometheus --name=prometheus --namespace=monitoring
```

Then I installed Kafka with the Prometheus exported enabled as shown below:

```
$ helm install bitnami/kafka --name kafka --set metrics.kafka.enabled=true
```

After that, I accessed to Prometheus using `port-forward`:

```
$ export POD_NAME=$(kubectl get pods --namespace monitoring -l "app=prometheus,component=server" -o jsonpath="{.items[0].metadata.name}")
$ kubectl --namespace monitoring port-forward $POD_NAME 9090
```

Open a browser and go to http://127.0.0.1:9090. Then click "Status->Targets":

<img width="437" alt="Screenshot 2019-05-27 at 11 17 18" src="https://user-images.githubusercontent.com/6740773/58411894-a0dedd80-8075-11e9-86b5-7b1f8cacd12e.png">

Under "kubernetes-pods" section, you should see kafka pod as a "metrics source":

![Screenshot 2019-05-27 at 11 51 37](https://user-images.githubusercontent.com/6740773/58411998-db487a80-8075-11e9-8c83-e5dbc374c814.png)

Go back to http://127.0.0.1:9090/graph and query for kafka:

![Screenshot 2019-05-27 at 11 53 12](https://user-images.githubusercontent.com/6740773/58412091-0b901900-8076-11e9-851a-b632c4bdc1d4.png)

You should be able to see the metrics

**Comment by abhi-dwivedi** [comment]
Hi 

Thanks for update but I am using the Prometheus operator so how can I see all metrics related to the jmx , Kafka and jvm related also? And the how I see the dashbaord in grafana

**Comment by juan131** [comment]
Hi @abhi-dwivedi 

Prometheus operator install Prometheus in your K8s cluster in a very similar way the Helm chart does. Therefore, the process should be very similar.

Are you able to see "Kafka" as a Target in your Prometheus server? 

> And the how I see the dashbaord in grafana

Did you already configured your Grafana Dashboard to use your Prometheus as a "Datasource"?

> how can I see all metrics related to the jmx , Kafka and jvm related also

If your Prometheus is able to recognise Kafka as a "target" you should be able to query for all those metrics.

**Comment by pandvan** [comment]
I'm sorry to post on a closed issue but we're running the same problem.
Prometheus Operator, installed using Helm chart from official repository, doesn't support annotation-based discovery as described here: https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheusioscrape
For what I can understand, Kafka chart didn't create Service resources that points to exporter's ports so it's not possible to create a custom _ServiceMonitor_ that instructs Prometheus to discover services that exposes Kafka metrics.
Is there any suggestion of how we can proceed to use this Kafka Helm chart with _ServiceMonitor_ logic needed by Prometheus Operator?

**Comment by juan131** [comment]
Hi @pandvan 

> For what I can understand, Kafka chart didn't create Service resources that points to exporter's ports so it's not possible to create a custom ServiceMonitor that instructs Prometheus to discover services that exposes Kafka metrics.
> Is there any suggestion of how we can proceed to use this Kafka Helm chart with ServiceMonitor logic needed by Prometheus Operator?

We already support for this feature to other charts (e.g. https://github.com/bitnami/charts/tree/master/upstreamed/redis) by adding some parameters (see the table below) that allow to configure a ServiceMonitor:

Parameter | Description | Default
-- | -- | --
metrics.serviceMonitor.enabled | if true, creates a Prometheus Operator ServiceMonitor (also requires metrics.enabled to be true) | false
metrics.serviceMonitor.namespace | Optional namespace which Prometheus is running in | nil
metrics.serviceMonitor.interval | How frequently to scrape metrics (use by default, falling back to Prometheus' default) | nil
metrics.serviceMonitor.selector |  Default to kube-prometheus install (CoreOS recommended), but should be set according to Prometheus install | { prometheus: kube-prometheus }

Would a solution like this work for you? I can create a PR to add this if so.

**Comment by pandvan** [comment]
Yes, it sounds like it will solve the issue we're facing.
At the moment we're working using the "workaround" described in https://github.com/coreos/prometheus-operator/issues/1547#issuecomment-446711073 but your proposed solution should be much more clear and coherent with ServiceMonitor's usage pattern.

**Comment by juan131** [comment]
Hi @pandvan 

I just created the PR to add this feature. Please find it in the above link

**Comment by juan131** [comment]
Hi @pandvan 

The PR was merged. Could you give the latest Kafka chart version a try?

**Comment by victoryNap** [comment]
@juan131 

I'm running into the same issues that the guys above were -

Running on GKE, I've installed kafka with the following configuration:

```
metrics:
  jmx:
    enabled: true
  kafka:
    enabled: true
  serviceMonitor:
    enabled: true
```

And prometheus with the default configuration, in the `monitoring` namespace.

I can get to the jmx (for each kafka instance) and serviceMonitor output on 5556 and 9308.

While the services appear in prometheus, they dont appear as active targets, which means no stats come through :(

<img width="391" alt="Screen Shot 2020-03-28 at 5 55 31 PM" src="https://user-images.githubusercontent.com/1377320/77835707-54dd4900-711d-11ea-89d4-e8c98524106a.png">

Is there any way to manually add them through a config map?

**Comment by juan131** [comment]
Hi @victoryNap 

This should have been fixed at https://github.com/bitnami/charts/pull/2145
Please check latest version and let us know if that PR solved the issue for you

**Comment by SulaymonHursanov** [comment]
for example you want add your **exporter** to prometheus which you installed by **kube-prometheus-stack**
you should enable servicemonitor on your values.yaml of exporter and set additionalLabels 

1. helm upgrade --namespace monitoring --install kube-stack-prometheus prometheus-community/kube-prometheus-stack
2. helm upgrade --namespace monitoring --install kafka-exporter prometheus-community/prometheus-kafka-exporter -f [values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-kafka-exporter/values.yaml)


```
$ cat values.yaml  # values from kafka-exporter

image:
  repository: danielqsj/kafka-exporter
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

kafkaServer:
  - kafka-server:9092

....

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: "30s"
    # If serviceMonitor is enabled and you want prometheus to automatically register
    # target using serviceMonitor, add additionalLabels with prometheus release name
    # e.g. If you have deployed kube-prometheus-stack with release name kube-prometheus
    # then additionalLabels will be
    # additionalLabels:
    #   release: kube-stack-prometheus
    additionalLabels:
       release: kube-stack-prometheus
    targetLabels: []

....

```
