### ISSUE TITLE
Matomo with Cloud SQL Proxy and Service Account

### ISSUE THREAD

**Issue by amirsaber** [bitnami/charts#11978]
### Name and Version

bitnami/matomo 0.1.13

### What is the problem this feature will solve?

In order to connect to MySQL on GCP best practice is use of Cloud SQL Proxy sidecar, however this will require a service account attached to sidecar. For Matomo to connect to Cloud SQL we would need to have a sidecar running with an specific service account, having the sidecar was not a problem but I couldn't find a way to associate a service account to it.

### What is the feature you are proposing to solve the problem?

Adding a field for serviceAccountName that attaches to sidecars running

### What alternatives have you considered?

Deploying Cloud SQL Proxy as a deployment with a service and connect to that instead of sidecars

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! Would you like to submit a PR with the value?

**Comment by amirsaber** [comment]
Thanks @javsalgar I created a PR for this however having hard time to understand what is wrong with the metadata.
