### ISSUE TITLE
etcd truncated release name to 24

### ISSUE THREAD

**Issue by kfox1111** [bitnami/charts#1200]
I'm trying to use the etcd chart in a ci pipeline and the chart currently truncates the release name to 24 characters. This is not enough for the branch/build identifiers I'm using. Could this number be bumped up larger please?

**Comment by tompizmor** [comment]
@kfox1111 I just sent a PR with the change. Will let you know once it is merged

**Comment by tompizmor** [comment]
@kfox1111 It is merged now!
