### ISSUE TITLE
all redis pods turned into master in redis cluster 

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#12009]
### Name and Version

bitnami/redis-cluster , 7.1.0

### What steps will reproduce the bug?

helm install redis-cluster redis-cluster

### Are you using any custom parameters or values?

external.acess=enabled
service.type=nodeport

### What is the expected behavior?

in a cluster of 6 nodes i expect that 3 pods should turn into master and rest 3 into slaves.

### What do you see instead?

all nodes are turned into master. clusterdown hash slot error is coming. also i am unable to connect to any pod individually using its own externalip and port

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-08-23 11-47-13](https://user-images.githubusercontent.com/68244292/186084428-a7e765b6-e5f1-4a4b-a3af-b90ab72925de.png)
![Screenshot from 2022-08-23 11-46-11](https://user-images.githubusercontent.com/68244292/186084438-049ffee3-0974-4000-80f8-13ab58d1dac2.png)
![Screenshot from 2022-08-23 11-45-21](https://user-images.githubusercontent.com/68244292/186084441-d4a4d64a-5ba1-4379-9b52-ee7cccfb5602.png)

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-08-23 12-13-17](https://user-images.githubusercontent.com/68244292/186088968-8819bf6f-edfe-4de6-afee-a24d1d318400.png)

**Comment by abhishekgupta2205** [comment]
also i am unabel to conect to redis pod when runnig cluster fix or check command

**Comment by carrodher** [comment]
There is already an issue created about this topic, see 
- https://github.com/bitnami/charts/issues/11359

In order to unify the conversations in a single place and provide better support, we will close the rest of the issues for the same topic converging them in the original one. Feel free to comment at https://github.com/bitnami/charts/issues/11359

**Comment by abhishekgupta2205** [comment]
https://github.com/bitnami/charts/issues/11359#issuecomment-1208334628   
i run this command in my pods and the output is 
![Screenshot from 2022-08-23 12-24-29](https://user-images.githubusercontent.com/68244292/186091003-a5a85b27-3cf7-48cc-a311-13b916f13232.png)
