### ISSUE TITLE
Can't override /config/envoy.json with a custom configMap of my choosing

### ISSUE THREAD

**Issue by brycekottke** [bitnami/charts#12006]
### Name and Version

bitnami/envoy 1.23.0-debian-11-r4

### What is the problem this feature will solve?

Allow users to override the `/config/envoy.json` file with a configMap they have created themselves.

### What is the feature you are proposing to solve the problem?

Allow users to override the `/config/envoy.json` file with a configMap they have created themselves.

### What alternatives have you considered?

build our own envoy pod with our custom `/config/envoy.json`

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Would you like to submit a PR with the feature?

**Comment by brycekottke** [comment]
I will see if i can get a PR in for this feature later today. Thanks for listening to our feedback! This would really help us out if we could use our own custom `envoy.json` :+1:
