### ISSUE TITLE
Multiple vulnerabilities found in [bitnami/redis:7.0.4-debian-11-r11] during JFrog scan.

### ISSUE THREAD

**Issue by HimanshuPanwarSF** [bitnami/charts#12011]
### Name and Version

bitnami/redis:7.0.4-debian-11-r11

### What steps will reproduce the bug?

Scanning the Redis with an X-ray scan on JFrog gave us several vulnerabilities including **4 critical severity** security issues and the rest were high & low severity.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

0 security issues.

### What do you see instead?

- 4 Critical Severity Issues
- 9 High Severity Issues

### Additional information

- Screenshots:
![image](https://user-images.githubusercontent.com/83944925/186099448-d40aefe7-2225-4add-9c62-acc6305f1f9a.png)
![image](https://user-images.githubusercontent.com/83944925/186099763-0a00d2f2-0cbf-4441-87da-4cdf3ca2c83e.png)

- JFrog Security Report:
[redis:7.0.4-debian-11-r11 Security Report.csv](https://github.com/bitnami/charts/files/9400364/redis.7.0.4-debian-11-r11.Security.Report.csv)

**We request you to fix the issues as we have to move our project to the production stage.**

**Comment by javsalgar** [comment]
Hi,

I tried performing the same scan, and indeed we can see 4 critical vulnerabilities. However, it seems that these vulnerabilities were not yet fixed by the upstream OS. As soon as they are fixed, we will release a new revision of the container.

**Comment by wibed** [comment]
@HimanshuPanwarSF 
could you put the chart in the title as follows?
ex.: [bitnami/wordpress]

**Comment by HimanshuPanwarSF** [comment]
Thank you. @javsalgar
