### ISSUE TITLE
[General]

### ISSUE THREAD

**Issue by wibed** [bitnami/charts#12025]
### Name and Version

bitnami/charts

### What is the problem this feature will solve?

due to the multidimensionality of this repo i notice issues going stale because of limited filter capabilities.

### What is the feature you are proposing to solve the problem?

can we enforce people to put the chart in the title of their issues as follows
ex.: [bitnami/wordpress]

**Comment by fmulero** [comment]
Thanks @wibed for pointing out.

Our templates have the title as you said, the contribution guidelines mention it and we usually edit the title and/or add labels with the app during the triage. To be honest I don't know how can we enforce it more.

I am worried about this:

> i notice issues going stale because of limited filter capabilities

What do you mean? Could you share an example?

**Comment by carrodher** [comment]
You can filter issues/PRs by the app using the labels. The title is something that can vary and it is not mandatory to follow a specific format in the title of the issues. For that, we make use of labels, which better model this use case.

For instance, you can filter all the issues/PRs related to WordPress by looking at https://github.com/bitnami/charts/labels/wordpress

**Comment by wibed** [comment]
alright, id consider this answered thank you
