### ISSUE TITLE
[bitnami/wordpress] replace prefork and mod_php modules

### ISSUE THREAD

**Issue by wibed** [bitnami/charts#12023]
### Name and Version

bitnami/wordpress 15.1.0

### What steps will reproduce the bug?

Running a default installation.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

using 
- event instead of prefork
- php-fpm instead of mod-php 

### What do you see instead?

The opposite

### Additional information

https://www.php.net/manual/en/faq.installation.php#faq.installation.apache2

> The [event](https://httpd.apache.org/docs/2.4/mod/event.html) Multi-Processing Module (MPM) is designed to allow more requests to be served simultaneously by passing off some processing work to the listeners threads, freeing up the worker threads to serve new requests.
> 
> To use the [event](https://httpd.apache.org/docs/2.4/mod/event.html) MPM, add `--with-mpm=event` to the [configure](https://httpd.apache.org/docs/2.4/programs/configure.html) script's arguments when building the [httpd](https://httpd.apache.org/docs/2.4/programs/httpd.html).

**Comment by fmulero** [comment]
Sorry @wibed I don't have any news yet, please bear with me
