### ISSUE TITLE
[bitnami/*] Wrong installation notes for helm charts in bitnami.com

### ISSUE THREAD

**Issue by sayedimac** [bitnami/charts#12024]
### Name and Version

bitnami/wordpress

### What steps will reproduce the bug?

https://bitnami.com/stack/wordpress/helm

The first set of commands has a bug - it should be 2 commands.
There are two helm commands there, but someone prbs hit backspace on the bottom command now it is part of the top option :)

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/25403967/186181504-cd8717c1-3698-4c68-89d2-561a41735ded.png)

### What do you see instead?

I see a bug...

**Comment by fmulero** [comment]
Thanks @sayedimac for reporting this issue. It seems general to all helm charts promoted in bitnami.com.

[Here](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#readme) you can find more complete installation notes

**Comment by fmulero** [comment]
Simple installation notes in bitnami.com are now fixed. Thanks @sayedimac for reporting it.
