### ISSUE TITLE
Providing an "auth.adminpassword" longer than 10 characters does not work

### ISSUE THREAD

**Issue by DaliGossrani** [bitnami/charts#12022]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

1. `helm install my-release --set auth.adminPassword=secretpassword bitnami/keycloak`

### Are you using any custom parameters or values?

`--set auth.adminPassword=secretpassword`

### What is the expected behavior?

The admin password should be set to "secretpassword" but as it is longer than 10 characters it does not work.

### What do you see instead?

The old password persists, even after deleting the PV.

**Comment by wibed** [comment]
@DaliGossrani could you put the chart in the title as follows?
ex.: [bitnami/wordpress]

**Comment by alemorcuq** [comment]
> The old password persists, even after deleting the PV.

What do you mean by this? You have to remove the PVC, otherwise the old password will always persist. If you have indeed removed the PVC, the old password should not be there. Could you please double check?
