### ISSUE TITLE
[bitnami/cassandra] How can I pul Custom cassandra.yaml in k8s pod

### ISSUE THREAD

**Issue by shashank-omre-cldcvr** [bitnami/charts#12168]
### Name and Version

bitnami/cassandra 9.3.2

### What is the problem this feature will solve?

I want to use customer cassandra.yaml and mount it on /etc/cassandra/cassandra.yaml.

### What is the feature you are proposing to solve the problem?

There should be option to mount it.

**Comment by javsalgar** [comment]
Hi

Did you try the `existingConfiguration` value? There you can put a custom configmap with the configuration
