### ISSUE TITLE
name of pod is displayed instead of ip in redis sentinel master ip command

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#12166]
### Name and Version

bitnami, redis

### What steps will reproduce the bug?

helm install redis redis 

### Are you using any custom parameters or values?

sentinel.enabled=true

### What is the expected behavior?

when connecting to sentinel and check sentinel masters , in IP parameter it should return pod ip .

### What do you see instead?

IP parameter is showing pod name.
![Screenshot from 2022-08-26 12-37-36](https://user-images.githubusercontent.com/68244292/186843419-12b9d7e7-eee0-4fbb-b3ca-58a62e7198f3.png)

**Comment by abhishekgupta2205** [comment]
in IP parameter it should not print redis-test-node-0.qa

**Comment by abhishekgupta2205** [comment]
Due to this , i cannot access pod from outside  as we need ip to access. can you suggest how to change this parameter

**Comment by javsalgar** [comment]
Hi,

Could you please change the title of the issue according to the guidelines?

`[bitnami/redis] Descriptive Title`
