### ISSUE TITLE
[bitnami/kafka] typo in KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS

### ISSUE THREAD

**Issue by tsgit** [bitnami/charts#12164]
### Name and Version

bitnami kafka 3.2.1 helm chart 18.0.3  and later

### What steps will reproduce the bug?
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-kafka bitnami/kafka --version 18.3.0

$ kubectl exec -it my-kafka-0 -- grep log.retention.check.interval /opt/bitnami/kafka/config/server.properties
log.retention.check.interval.ms=300000
log.retention.check.intervals.ms=300000
```
the second line should not be there

### What is the expected behavior?

the generated server.properties file should contain default value
`log.retention.check.interval.ms=300000`

### What do you see instead?

the generated server.properties contains 2 entries
`log.retention.check.interval.ms=300000`
`log.retention.check.intervals.ms=300000`

### Additional information

https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L319-L320

the variable name should be singular, obvious typo

**Comment by fmulero** [comment]
Thanks a lot @tsgit for reporting this issue. It will be fixed soon
