### ISSUE TITLE
[bitnami/redis] redis-master.api.svc.cluster.local missing in auto generated cert altnames

### ISSUE THREAD

**Issue by denissabramovs** [bitnami/charts#12172]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

1. deploy redis chart with replication setup and with `tls.enabled: true` + `autoGenerated: true`
2. connect using `redis-master.api.svc.cluster.local` any client with rejectUnauthorized: true flag which rejects if provided host is not enlisted in certs altnames
3. see error, that used host is not in cert altnames

### Are you using any custom parameters or values?

helm -n api install redis . \
  --set "auth.password=acpnHergoiNH8z8857EFIplozk13fbozpg123khnopkHNhbzWE8AzO457EFI66lJnHergoiNH8z88AzO4acp66lJplozk13fbozpg123khnopkHNhbzWEIOFNHB12IOFNHB128"

### What is the expected behavior?

`redis-master.api.svc.cluster.local` to be enlisted into altnames when generating certs, to connect without issues and errors via `redis-master.api.svc.cluster.local` hostname.

### What do you see instead?
```
Host: redis-master.api.svc.cluster.local. is not in the cert's altnames:
DNS:*.redis.api.svc.cluster.local, 
DNS:redis.api.svc.cluster.local, 
DNS:*.redis-headless.api.svc.cluster.local, 
DNS:redis-headless.api.svc.cluster.local, 
DNS:127.0.0.1, 
DNS:localhost, 
DNS:redis
```

### Additional information

Connecting without error if host `redis-headless.api.svc.cluster.local` is provided, but the problem is, that it is doing dns round-robin selection of pods and hit READ-ONLY slaves as well, so our app can't write when it hits a slave through that headless sub-domain resolve.

**Comment by denissabramovs** [comment]
there are 3 services:

- redis-headless
- redis-master
- redis-replicas


i suspect that problem is here:
https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/tls-secret.yaml#L10

**Comment by denissabramovs** [comment]
`redis` should replaced with `redis-master`

**Comment by denissabramovs** [comment]
here is the fix:
```
{{- $masterServiceName := printf "%s-master" (include "common.names.fullname" .) }}
{{- $altNames := list (printf "*.%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) "127.0.0.1" "localhost" $fullname }}
```

**Comment by denissabramovs** [comment]
Adding few additional altnames for master-redis subdomain and re-deploying fixed issues for me.

**Comment by javsalgar** [comment]
Hi,

The thing is that we would need, when autogenerating the certificate, the IP addresses of the services, so they are added to the cert. This would require doing like a two-step deployment, in the first deployment knowing the IP addresses of the services and then adding them to the certs doing helm upgrade. Would that make sense?

**Comment by denissabramovs** [comment]
Not sure what do you mean. I have added fix above. Just add additional subdomain to cert, by modifying helm template.

**Comment by javsalgar** [comment]
Would you like to submit a PR with the fix, now that you discovered it?

**Comment by denissabramovs** [comment]
nice way to fix bugs :+1:

**Comment by javsalgar** [comment]
Reopening. So, the only necessary item to fix the issue, is to add this to the chart yaml, right?

```
{{- $masterServiceName := printf "%s-master" (include "common.names.fullname" .) }}
{{- $altNames := list (printf "*.%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) "127.0.0.1" "localhost" $fullname }}
```

If you confirm we will create the PR.

**Comment by denissabramovs** [comment]
Yes, this way, it will add `-master` service subdomain into certs.

**Comment by CeliaGMqrz** [comment]
Hi @denissabramovs!

Sorry for the delay. We updated the chart with the required [changes](https://github.com/bitnami/charts/pull/13053). 

Thanks for your help on this!
