### ISSUE TITLE
[bitnami/apache] cannot serve images from a PVC using the SMB CSI 

### ISSUE THREAD

**Issue by ktivdv** [bitnami/charts#12173]
### Name and Version

bitnami/wordpress:15.1.3

### What steps will reproduce the bug?

1. Deploy Bitnami Wordpress helm chart on a PVC using this CSI https://github.com/kubernetes-csi/csi-driver-smb
2. Image uploads work fine
3. Files exist and are intact on the PVC
4. Images do not load (neither do various other downloads) and respond with HTTP 400 error

### What is the expected behavior?

Image loads in the browser and is visible.

### What do you see instead?

Broken links and error 400 on images

### Additional information

Everything works fine using any other CSI (Longhorn, NFS, etc). I believe this may have to do with these mmap+Debian-related issues:

https://github.com/bitnami/charts/issues/5535

Does anyone have any experience dealing with this issue? Should my approach be disabling MMAP via the Apache httpd.conf, or is the issue wider in scope? The issue above links out to this topic:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900821

...in which someone reported being able to reproduce it on NGINX as well, so perhaps it's a Debian/kernel issue, and not specific to Apache. 

Also potentially related: https://github.com/bitnami/charts/issues/5450

Thanks in advance!

**Comment by migruiz4** [comment]
Hi @ktivdv,

Could you please share the permissions of the folder `/bitnami/wordpress/wp-content/`?
There, you should see `775` for folders and `664` for files, owned by `1001:root`.

It would be helpful if you could also share the permissions of the root folder `/bitnami/wordpress`:
```
$ ls -la /bitnami/wordpress/                   
total 20
drwxrwxrwx 3 root root 4096 Aug 31 14:42 .
drwxr-xr-x 3 root root 4096 Aug 30 22:58 ..
-r--r----- 1 1001 root 4354 Aug 31 14:42 wp-config.php
drwxrwxr-x 7 1001 root 4096 Aug 31 14:42 wp-content
```

In addition, please perform other tests while running as user `1001`, like creating a file inside the volume, reading its content and deleting it.

**Comment by ktivdv** [comment]
Hullo @migruiz4,

`I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/$ whoami
whoami: cannot find name for user ID 1001
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/$ ls -la /bitnami/wordpress/  
total 68
drwxrwxrwx 2 1001 1001    0 Aug 24 18:50 .
drwxr-xr-x 3 root root 4096 Aug 23 17:46 ..
-r-xr-xr-x 1 1001 1001 4361 Aug 24 18:50 wp-config.php
drwxrwxrwx 2 1001 1001    0 Aug 24 19:39 wp-content
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/$ 
Display all 542 possibilities? (y or n)
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/$ ls -la /bitnami/wordpress/wp-content
total 65
drwxrwxrwx 2 1001 1001 65536 Aug 24 19:39 .
drwxrwxrwx 2 1001 1001     0 Aug 24 18:50 ..
-rwxrwxrwx 1 1001 1001    28 Aug 24 18:50 index.php
drwxrwxrwx 2 1001 1001     0 Aug 24 18:50 languages
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 plugins
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 themes
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 upgrade
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 uploads
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/$ cd /bitnami/wordpress/wp-content
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/bitnami/wordpress/wp-content$ mkdir test
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/bitnami/wordpress/wp-content$ touch test/test.txt
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/bitnami/wordpress/wp-content$ rm test -R
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/bitnami/wordpress/wp-content$ ls -la
total 65
drwxrwxrwx 2 1001 1001 65536 Sep  8 16:55 .
drwxrwxrwx 2 1001 1001     0 Aug 24 18:50 ..
-rwxrwxrwx 1 1001 1001    28 Aug 24 18:50 index.php
drwxrwxrwx 2 1001 1001     0 Aug 24 18:50 languages
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 plugins
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 themes
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 upgrade
drwxrwxrwx 2 1001 1001     0 Aug 24 18:52 uploads
I have no name!@wp-img-test-wordpress-74c67849f9-g9msw:/bitnami/wordpress/wp-content$ `

thanks!

**Comment by ktivdv** [comment]
Hello @migruiz4 I understand your position, but I was hoping to find out if and how i can disable MMAP on Apache for the bitnami charts. I have also asked for help from the SMB CSI provider (and others have had the same issue as me), so I will update here if I resolve it. However, given what I found during my research and log reviews (pointing at MMAP + Apache), I'd like to try that approach of disabling it if possible. Other apps work perfectly using the SMB CSI, and for the record Wordpress has no problem reading or writing from the SMB stores - it's just that Apache throws a 400 when serving images. Could you please help me with instructions on disabling MMAP in Apache and I'll report back with the results (and close the case either way :)? Thank you!

**Comment by migruiz4** [comment]
Hi @ktivdv, sorry for the late response.

You can easily modify the apache configuration by overriding the default Wordpress container command:
```
command:
  - /bin/bash
  - -ec
  - |-
    . /opt/bitnami/scripts/apache-env.sh
    echo "EnableMMAP off" >> $APACHE_CONF_FILE
    /opt/bitnami/scripts/wordpress/entrypoint.sh /opt/bitnami/scripts/apache/run.sh
```

Or, alternatively, use the values `apacheConfiguration` or `existingApacheConfigurationConfigMap` to provide your own apache configuration file.

Please give it a try and let us know if it works

**Comment by ktivdv** [comment]
Hi Miguel - thank you so much! I added a configmap with my custom httpd.conf with MMAP disabled, and all images are now loading correctly. As it states in the httpd.conf comments:

# EnableMMAP and EnableSendfile: On systems that support it, 
# memory-mapping or the sendfile syscall may be used to deliver
# files.  This usually improves server performance, but must
# be turned off when serving from networked-mounted 
# filesystems or if support for these functions is otherwise
# broken on your system.
# Defaults: EnableMMAP On, EnableSendfile Off
#
EnableMMAP off
#EnableSendfile on

MMAP should likely be disabled by default (or at least the option easily exposed in the helm chart) for k8s deployments - I will suggest this change to Bitnami, who I opened a case with as well. thanks again
