### ISSUE TITLE
[bitnami/mongodb] Replicaset unable to reach healthcheck after 13.1.2 upgrade

### ISSUE THREAD

**Issue by leejona16** [bitnami/charts#12174]
### Name and Version

bitnami/mongodb 13.1.2

### What steps will reproduce the bug?

Create a mongodb deployment with replicaset architecture

### What is the expected behavior?

On a clean helm install/upgrade, the cluster comes up and is available.

### What do you see instead?

The first node comes up, but is unable to reach other nodes for healthcheck, blocking the install. This was seen in the first node's logs consistently after boot:

```{"t":{"$date":"2022-08-26T21:15:45.952+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-4","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-1:27017","maxHeartbeatRetries":2,"error":{"code":6,"codeName":"HostUnreachable","errmsg":"Error connecting to mongodb-1:27017 (10.255.139.108:27017) :: caused by :: Connection refused"}}}```

The logs from node-1 stall out after it's added to the cluster and eventually starts spamming connection refused (IP address is of node-0):

```mongodb 20:41:43.25 INFO  ==> Creating users...
mongodb 20:41:43.26 INFO  ==> Users created
mongodb 20:41:43.27 INFO  ==> Writing keyfile for replica set authentication...
mongodb 20:41:43.33 INFO  ==> Configuring MongoDB replica set...
mongodb 20:41:43.37 INFO  ==> Stopping MongoDB...
mongodb 20:41:48.06 INFO  ==> Trying to connect to MongoDB server mongodb-0...
mongodb 20:41:48.08 INFO  ==> Found MongoDB server listening at mongodb-0:27017 !
mongodb 20:41:50.22 INFO  ==> MongoDB server listening and working at mongodb-0:27017 !
mongodb 20:41:52.29 INFO  ==> Primary node ready.
mongodb 20:41:54.49 INFO  ==> Adding node to the cluster
mongodb 20:42:05.26 INFO  ==> Node mongodb-1:27017 is confirmed!
MongoNetworkError: connect ECONNREFUSED 10.255.241.185:27017
MongoNetworkError: connect ECONNREFUSED 10.255.241.185:27017
MongoNetworkError: connect ECONNREFUSED 10.255.241.185:27017
```

### Additional information

Reverting our chart version back to 13.1.0 fixed this issue and our deployment is coming up.

**Comment by javsalgar** [comment]
Hi,

Could you provide more details on the k8s platform you are using? Does it happen consistently in other k8s installations?
