### ISSUE TITLE
[bitnami/wordpress] on K8s 1.24.2 blanc screen

### ISSUE THREAD

**Issue by fgcgithub** [bitnami/charts#12176]
### Name and Version

bitnami/wordpress-15.1.0  app version 6.0.1

### What steps will reproduce the bug?

1. Kubernetes 4 nodes cluster with "nfs-subdir-external-provisioner", kubernetes version 1.24.2
2. `helm install my-release bitnami/wordpress --set global.storageClass=nfs-client`
3. all Kubernetes objects are running:
```
   NAME                                                   READY   STATUS    RESTARTS      AGE
   pod/my-release-mariadb-0                               1/1     Running   0             36m
   pod/my-release-wordpress-ffd547bcf-kmfv6               1/1     Running   1 (33m ago)   36m
   pod/nfs-subdir-external-provisioner-59d666cd8f-v7twd   1/1     Running   2 (26h ago)   33h

   NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
   service/kubernetes             ClusterIP   10.96.0.1       <none>        443/TCP                      69d
   service/my-release-mariadb     ClusterIP   10.99.226.120   <none>        3306/TCP                     36m
   service/my-release-wordpress   NodePort    10.110.32.44    <none>        80:30829/TCP,443:30167/TCP   36m

   NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
   deployment.apps/my-release-wordpress              1/1     1            1           36m
   deployment.apps/nfs-subdir-external-provisioner   1/1     1            1           33h

   NAME                                                         DESIRED   CURRENT   READY   AGE
   replicaset.apps/my-release-wordpress-ffd547bcf               1         1         1       36m
   replicaset.apps/nfs-subdir-external-provisioner-59d666cd8f   1         1         1       33h

   NAME                                  READY   AGE
   statefulset.apps/my-release-mariadb   1/1     36m
```
The persistent volume claims are successfully bound.

### Are you using any custom parameters or values?
```
--set global.storageClass=nfs-client
```

### What is the expected behavior?

Webbrowser should show 1. configuration of WordPress...

### What do you see instead?

Webbrowser showing a blank page, but the tab in the browser is showing the WordPress icon.

**Comment by fmulero** [comment]
Hi @fgcgithub

Could you share the logs from `pod/my-release-wordpress-ffd547bcf-kmfv6`?

**Comment by fgcgithub** [comment]
Hi Fran,

here the logs from the wordpress pod:

hint: everything is in running state – have a look…

NAME                                                   READY   STATUS    RESTARTS        AGE
pod/my-release-mariadb-0                               1/1     Running   0               33m
pod/my-release-wordpress-7666695cb6-24dkz              1/1     Running   1 (29m ago)     33m
pod/nfs-subdir-external-provisioner-59d666cd8f-v7twd   1/1     Running   2 (3d15h ago)   3d22h

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/kubernetes             ClusterIP   10.96.0.1       <none>        443/TCP                      72d
service/my-release-mariadb     ClusterIP   10.106.143.36   <none>        3306/TCP                     33m
service/my-release-wordpress   NodePort    10.107.56.243   <none>        80:31140/TCP,443:31362/TCP   33m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-release-wordpress              1/1     1            1           33m
deployment.apps/nfs-subdir-external-provisioner   1/1     1            1           3d22h

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/my-release-wordpress-7666695cb6              1         1         1       33m
replicaset.apps/nfs-subdir-external-provisioner-59d666cd8f   1         1         1       3d22h

NAME                                  READY   AGE
statefulset.apps/my-release-mariadb   1/1     33m


kubectl get pvc
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-my-release-mariadb-0   Bound    pvc-428f5389-bc80-47c0-a060-10ccc63ee500   8Gi        RWO            nfs-client     34m
my-release-wordpress        Bound    pvc-1ceae0bf-fbbc-4b44-b34c-3b6675280b96   10Gi       RWO            nfs-client     34m

kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS   REASON   AGE
pvc-1ceae0bf-fbbc-4b44-b34c-3b6675280b96   10Gi       RWO            Delete           Bound    default/my-release-wordpress        nfs-client              35m
pvc-428f5389-bc80-47c0-a060-10ccc63ee500   8Gi        RWO            Delete           Bound    default/data-my-release-mariadb-0   nfs-client              35m

HERE THE LOGS OF THE WORDPRESS POD:

kubectl logs my-release-wordpress-7666695cb6-24dkz
wordpress 07:25:20.76
wordpress 07:25:20.76 Welcome to the Bitnami wordpress container
wordpress 07:25:20.76 Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 07:25:20.77 Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 07:25:20.77
wordpress 07:25:20.77 INFO  ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 07:25:20.82 INFO  ==> Configuring the HTTP port
wordpress 07:25:20.83 INFO  ==> Configuring the HTTPS port
wordpress 07:25:20.84 INFO  ==> Configuring Apache ServerTokens directive
wordpress 07:25:20.88 INFO  ==> Configuring PHP options
wordpress 07:25:20.88 INFO  ==> Setting PHP expose_php option
wordpress 07:25:20.91 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 07:25:20.99 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress 07:25:21.15 INFO  ==> Restoring persisted WordPress installation
wordpress 07:25:22.69 INFO  ==> Trying to connect to the database server
wordpress 07:25:24.13 INFO  ==> ** WordPress setup finished! **

wordpress 07:25:24.15 INFO  ==> ** Starting Apache **
[Tue Aug 30 07:25:24.246071 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 30 07:25:24.246589 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 30 07:25:24.280285 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 30 07:25:24.280724 2022] [ssl:warn] [pid 1] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Aug 30 07:25:24.300062 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Tue Aug 30 07:25:24.300104 2022] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
172.16.249.146 - - [30/Aug/2022:07:25:50 +0000] "\x16\x03\x01\x02" 400 226
172.16.249.146 - - [30/Aug/2022:07:25:50 +0000] "\x16\x03\x01\x02" 400 226
192.168.1.103 - - [30/Aug/2022:07:25:50 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
172.16.249.146 - - [30/Aug/2022:07:25:50 +0000] "POST /wp-cron.php?doing_wp_cron=1661844350.6590049266815185546875 HTTP/1.1" 200 -
192.168.1.103 - - [30/Aug/2022:07:26:00 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:26:10 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:26:20 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:26:30 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:26:40 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:26:50 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:00 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:10 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:20 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:20 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:27:30 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:30 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:27:40 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:40 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:27:50 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:27:50 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:28:00 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:28:00 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:28:10 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:28:10 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:28:20 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:28:20 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:28:30 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:28:30 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317
192.168.1.103 - - [30/Aug/2022:07:28:40 +0000] "GET /wp-login.php HTTP/1.1" 200 5788
192.168.1.103 - - [30/Aug/2022:07:28:40 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 1317

Yours
Fgc


Von: Fran Mulero ***@***.***>
Gesendet: Montag, 29. August 2022 15:05
An: bitnami/charts ***@***.***>
Cc: fgcgithub ***@***.***>; Mention ***@***.***>
Betreff: Re: [bitnami/charts] wordpress on K8s 1.24.2 blanc screen (Issue #12176)


Hi @fgcgithub<https://github.com/fgcgithub>

Could you share the logs from pod/my-release-wordpress-ffd547bcf-kmfv6?

**Comment by carrodher** [comment]
Unfortunately, I am not able to reproduce the issue on top of different k8s clusters, could you check your NFS configuration? Could you try using the default parameters?

**Comment by fgcgithub** [comment]
Hallo Carlos Rodriguez Hernández,

you are right, ich will check my NFS config.
I just created a K8S-Cluster in Azure and started the bitmani/wordpress chart without any problems.

Yours
Franz-Georg

Von: Carlos Rodríguez Hernández ***@***.***>
Gesendet: Donnerstag, 1. September 2022 18:38
An: bitnami/charts ***@***.***>
Cc: fgcgithub ***@***.***>; Mention ***@***.***>
Betreff: Re: [bitnami/charts] [bitnami/wordpress] on K8s 1.24.2 blanc screen (Issue #12176)


Unfortunately, I am not able to reproduce the issue on top of different k8s clusters, could you check your NFS configuration? Could you try using the default parameters?
