### ISSUE TITLE
[bitnami/etcd] GOMAXPROCS is not been setted on statefulset env

### ISSUE THREAD

**Issue by fandujar** [bitnami/charts#1218]
**Which chart**: 
bitnami/etcd

**Description**
GOMAXPROCS is not setted on statefulset template, so etcdmain is using all cpu's available on node.

**Steps to reproduce the issue:**

1. Install etcd using this chart
2. Check logs for message of available cpus

**Describe the results you received:**

etcdmain is using all cpus available

**Describe the results you expected:**

etcdmain should use a minimal number of cpus

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a

**Comment by juan131** [comment]
Hi @fandujar 

Thanks so much for opening the issue. I just created a PR to address it so you have a parameter that will allow you to set the env. variable properly.
