### ISSUE TITLE
[bitnami/kibana]: Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by Braineanear** [bitnami/charts#12208]
### Name and Version

bitnami/kibana 10.2.1

### What steps will reproduce the bug?

I have an issue with the Kibana installation.
After installing everything from elasticsearch and it's running and installing kibana it runs but produces this error
```
[ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. Hostname/IP does not match certificate's altnames: IP: "IP" is not in the cert's list: 
```

This is the command used to install elasticsearch using helm chart
```bash
helm install elasticsearch bitnami/elasticsearch --set data.persistence.size=64Gi --set security.enabled=true --set security.elasticPassword=T1100 --set security.tls.restEncryption=true --set security.tls.autoGenerated=true -n dev --create-namespace
```

and this is the command used to install kibana using the helm chart

```bash
helm install kibana --set elasticsearch.hosts[0]=elasticsearchServiceIP --set elasticsearch.port=9200 --set elasticsearch.security.auth.enabled=true --set elasticsearch.security.auth.createSystemUser=true --set elasticsearch.security.auth.kibanaPassword=T1100 --set elasticsearch.security.tls.enabled=true --set elasticsearch.security.tls.existingSecret=elasticsearch-coordinating-crt --set elasticsearch.security.tls.usePemCerts=true bitnami/kibana -n dev
```

### What is the expected behavior?

Kibana Running

### What do you see instead?
```console
[ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. Hostname/IP does not match certificate's altnames: IP: "IP" is not in the cert's list: 
```

**Comment by carrodher** [comment]
It seems the host address you specified in the Kibana deployment is not correct since the service is not properly reaching the container.
When deploying those Helm charts some notes are shown in the console, in those notes, you will find some instructions about how to access the different services deployed. Could you check that?

**Comment by Braineanear** [comment]
i fixed the hosting issue and followed the notes and it worked but now kibana logs showing me this error a lot 
[2022-09-02T04:41:51.919+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. socket hang up - Local: 10.28.3.42:46118, Remote: 10.32.0.169:9200

**Comment by Braineanear** [comment]
Okay i think it's not now from kibana. It's with elasticsearch, it sends socket hang up when i try to connect to it.
![2](https://user-images.githubusercontent.com/17293532/188061467-e10c66f6-9e29-444b-b084-7495b9bff380.png)
![1](https://user-images.githubusercontent.com/17293532/188061469-81e1d844-aa0c-4f41-bc77-d22a6c3333f2.png)
I'm connecting to the elasticsearch service using port forwarding.

And the elastic coordinating pod returns in log this
[2022-09-02T04:52:32,109][WARN ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [elasticsearch-coordinating-0] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/10.28.2.17:9200, remoteAddress=/10.28.3.43:41412}
And also for the other nodes like master, data, and ingest they are returning the same with different ports and ips

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Kibana container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
