### ISSUE TITLE
[bitnami/keycloak] error when load test

### ISSUE THREAD

**Issue by hnhai** [bitnami/charts#12209]
### Name and Version

bitnami/keycloak 18.0.2

### What steps will reproduce the bug?

- Install Keycloak by Helm 3 instances, 2 core, 4gb memory each instance. External Postgres Database
- Load test login with 500 difference accounts by Jmeter in 3 minutes
- Pod restart. 503 error reponse to client

### What do you see instead?

Log of Pod:
- Uncaught server error: org.infinispan.commons.IllegalLifecycleStateException: ISPN000324: Cache 'realms' is in 'STOPPING' state and this is an invocation not belonging to an on-going transaction, so it does not accept new invocations. Either restart it or recreate the cache container
- [io.agroal.pool] (executor-thread-248) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)

**Comment by javsalgar** [comment]
Hi,

Does the same issue happen when using the internal database deployed with the chart?

**Comment by hnhai** [comment]
Hi @javsalgar, I have not try DB in chart yet.
I will try try and response later. Thanks

**Comment by hnhai** [comment]
Dear @javsalgar I found problem. 
Because Keycloak using PBKDF2 hash algorithm, this algorithm using too much CPU. It affect to performance.

**Comment by navinkaushik** [comment]
> Hi @javsalgar, I have not try DB in chart yet. I will try try and response later. Thanks



> Dear @javsalgar I found problem. Because Keycloak using PBKDF2 hash algorithm, this algorithm using too much CPU (iterator default 26500). It affect to performance.

Were you able to resolve the issue ? I am facing the same problem during keycloak performance testing, pods get restarted with caching related errors.
