### ISSUE TITLE
[bitnami/etcd] unable to validate against any security context constraint

### ISSUE THREAD

**Issue by zanderwong** [bitnami/charts#12215]
### Name and Version

bitnami/etcd 3.5.4

### What steps will reproduce the bug?

- Setup an rhel8 server environment with openshift4.6 and helm installed
- Run helm install etcd-test bitnami/etcd
- openshift StatefulSet will then prompt the error message:
```
create Pod etcd-0 in StatefulSet etcd failed error: pods "etcd-0" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000600000, 1000609999]]
```

### Are you using any custom parameters or values?

no

### What is the expected behavior?

etcd installed successfully without any issue.

### What do you see instead?

```
create Pod etcd-0 in StatefulSet etcd failed error: pods "etcd-0" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000600000, 1000609999]]
```

**Comment by migruiz4** [comment]
Hi @zanderwong,

To run the `bitnami/etcd` chart in OpenShift, you need to disable both `podSecurityContext` and `containerSecurityContext` to not set runAsUser and fsGroup values. 

Please try installing using the following values:
```
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: false
```
