### ISSUE TITLE
[bitnami/redis] instance is not configured to use an ACL file

### ISSUE THREAD

**Issue by jmajeedsh** [bitnami/charts#12229]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

I'm having a trouble configuring aclfile in redis/bitnami chart 
I know steps that I have to do
1- configuring aclfile
2- add extra volume
3- add extra volume Mount

this is what I'm ting to do but I'm still getting "(error) ERR This Redis instance is not configured to use an ACL file."

can anyone explain how exactly should we do it?

### Are you using any custom parameters or values?

extraVolumeMounts:
  - mountPath: data/users
    name: users
  extraVolumes:
  - name: users

### What do you see instead?

(error) ERR This Redis instance is not configured to use an ACL file.

**Comment by fmulero** [comment]
Hi @jmajeedsh 

Probably you see them, but could have a look to the following links?
* #4772
* From Redis container [Enabling access control list](https://github.com/bitnami/containers/tree/main/bitnami/redis#enabling-access-control-list)

If previous links didn't help, we will need some additional data to reproduce your issue. Could you share your `values.yaml` file or the values you are setting when installing the chart and the logs from the failing pods?
