### ISSUE TITLE
[bitnami/keycloak] Chart needs caching config parameters to set persistence store

### ISSUE THREAD

**Issue by anand-kulk** [bitnami/charts#12221]
### Name and Version

bitnami/keycloak 9.7.2

### What is the problem this feature will solve?

Currently, there is only one param for distributed cache, enable or disable. In our case we need to persist sessions in JDBC store like Postgres, I don't see a way to specify that through current available parameters. If chart can expose more options for caching like persistent store, remote cache instead of embedded etc then it would be great.
It would be useful for systems that can't tolerate any session loss. Even with current distributed caching, there are situations when sessions are lost during deployments or infrastructure upgrades.

### What is the feature you are proposing to solve the problem?

Expose config parameters for caching for whether to use embedded or a remote cache, configure persistence store(JDBC/JPA/File)

### What alternatives have you considered?

We have experimented the offline sessions but they are designed for a different purpose. Although they give us ability to refresh tokens, active user sessions are still expired and user needs to re-login.

**Comment by migruiz4** [comment]
Hi @anand-kulk,

Could you please provide more details about your use case?

Keycloak does only provide 3 settings for cache, as described in [the documentation](https://www.keycloak.org/server/caching):
- `cache`
- `cache-stack`
- `cache-config-file`

Two of these options are configured when `cache.enabled=true/false`, as you can see here (PRs #10387 and #10724):
https://github.com/bitnami/charts/blob/a0f2ba8b70567c230088407134526c1453492c5c/bitnami/keycloak/templates/configmap-env-vars.yaml#L29-L35

Additional options would have to be configured through `cache-config-file` which is not yet supported.

I have created an internal task for this feature request, but I can not provide an ETA for when the new feature will be added.
If you'd like to contribute, feel free to add send a PR and we will be happy to review it and help with anything if needed. 

As a temporary workaround, you could use the values `extraDeploy`, `extraVolumeMounts`, `extraVolumes` and `extraEnvVars`, to mount a your cache configuration in a configmap, mount it as a volume and declare the env variable `KC_CACHE_CONFIG_FILE` with its mountpath.

**Comment by anand-kulk** [comment]
@migruiz4, I am looking for a cache-config-file, to customize in more detail. Thanks for the workaround though. A follow up questions is, when you enable the caching and how can one specify the Cache owners count currently?

**Comment by migruiz4** [comment]
From Keycloak documentation:
> Each distributed cache has two owners per default, which means that two nodes have a copy of the specific cache entries. Non-owner nodes query the owners of a specific cache to obtain data. When both owner nodes are offline, all data is lost. This situation usually leads to users being logged out at the next request and having to log in again.

You may find the following link helpful: https://infinispan.org/docs/stable/titles/configuring/configuring.html#cache-configuration_cache-configuration

There, the `<distributed-cache owners="2"` would set the number of owners.

For more information about how to configure cache, I would recommend asking the Keycloak community.

**Comment by anand-kulk** [comment]
Thanks @migruiz4, looks like if we can support cache config file, we'll be able to specify that through it.
