### ISSUE TITLE
Unable to remove default value from auth_backends

### ISSUE THREAD

**Issue by Shubham3009** [bitnami/charts#12234]
### Name and Version

bitnami/airflow 11.1.14

### What steps will reproduce the bug?

Hi,
I am using Airflow 2.3.2 and getting below Warning while calling Airflow APIs,

airflow jobs check
```
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:356: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0. warnings.warn(

Found one alive job.
```

airflow version
```
/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py:356: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.  warnings.warn(
2.3.2
```
I tried to override `AUTH_BACKENDS` as below, but default values are still in use and not getting overridden by my value.
```
name: AIRFLOW__API__AUTH_BACKENDS
value: "airflow.api.auth.backend.basic_auth"
In airflow.cfg , Currently I see two values for auth_backends as below ,
auth_backends : airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
-- | --
```
Because of this behavior, am unable to apply the liveness probe on SCHEDULER to auto restart if a heartbeat is not received.

Please help to resolve this warning or override the `auth_backend` default value.

### Are you using any custom parameters or values?
```
name: AIRFLOW__API__AUTH_BACKENDS
value: "airflow.api.auth.backend.basic_auth"
```

### What is the expected behavior?
```
auth_backends : airflow.api.auth.backend.basic_auth
```
### What do you see instead?
```
auth_backends : airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
```

**Comment by carrodher** [comment]
As part of the triage, I just edited the description a bit. Please use [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to apply a readable format in your description and comments, mainly if you are pasting code, console output, logs, etc
