### ISSUE TITLE
[bitnami/redis] insufficient memory and cpu on a cluster outpilot

### ISSUE THREAD

**Issue by guilherme-golaio** [bitnami/charts#12253]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

I want to decrease the requests and limits of cpu and memory but i cant do it on terraform, can someone help me?
I tryed this:

` set {
     name = "master.resources.requests"
     value = {
            limits = {
              cpu    = "100m"
              memory = "300Mi"
            }
            requests = {
              cpu    = "10m"
              memory = "100Mi"
            }
          }
     }`

And then another question, is this the right way to get the connection string to that redis instance? :

`output "redis_host" {
  description = "The IP address of the redis instance"
  value       = "redis://${local.serviceName}.${local.namespace}"
}

output "redis_port" {
  description = "The port of the redis instance"
  value       = local.port
}`

### What do you see instead?

` 
│   on modules/redis/main.tf line 22, in resource "helm_release" "redis":
│   22:      value = {
│   23:             limits = {
│   24:               cpu    = "100m"
│   25:               memory = "300Mi"
│   26:             }
│   27:             requests = {
│   28:               cpu    = "10m"
│   29:               memory = "100Mi"
│   30:             }
│   31:           }
│ 
│ Inappropriate value for attribute "value": string required.`

**Comment by javsalgar** [comment]
Hi,

I'm afraid we don't officially support Terraform. However, we will leave the ticket open in case someone from the community wants to participate.
