### ISSUE TITLE
[common] fails to render HPA api version

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#12274]
### Name and Version

bitnami/common 2.0.1

### What steps will reproduce the bug?

1. apiVersion: {{ include "common.capabilities.hpa.apiVersion" . }}
2. it will fail

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

it should render api version

### What do you see instead?

```shell
Error: INSTALLATION FAILED: template: fss-webapp/templates/hpa.yaml:2:15: executing "fss-webapp/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" .>: error calling include: template: fss-webapp/charts/fss-commonlib/charts/common/templates/_capabilities.tpl:133:7: executing "common.capabilities.hpa.apiVersion" at <semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .context)>: error calling semverCompare: Invalid Semantic Version
```

### Additional information

I think the .context is errornous, compare it to the other templates in _capabilities.

**Comment by davidkarlsen** [comment]
related: https://github.com/bitnami/charts/issues/11340

**Comment by javsalgar** [comment]
Hi,

Indeed, the issue lies there. Instead of `.context` it should be `.`

Thank you so much for reporting, would you like to contribute with a PR?

**Comment by davidkarlsen** [comment]
@javsalgar yes, just assign it to me
