### ISSUE TITLE
[bitnami/etcd]: new cluster fails to properly discover that it is new

### ISSUE THREAD

**Issue by jan-xyz** [bitnami/charts#12288]
### Name and Version

bitnami/etcd: 8.4.5

### What steps will reproduce the bug?

1. Have an existing etcd cluster
2. spawn the new cluster

### Are you using any custom parameters or values?

This works flawlessly:
```sh
helm install \
  --repo https://charts.bitnami.com/bitnami \
  --version 8.4.5 \
  --set auth.rbac.rootPassword=secretpassword \
  --set replicaCount=3 \
etcd etcd
```

However, when I add it as a dependency to an application chart which already has an etcd cluster in it with

```yaml
# Chart.yaml
apiVersion: v2
name: foo
dependencies:
- name: etcd
  version: 8.4.5
  repository: https://charts.bitnami.com/bitnami
---
# values.yaml
etcd:
  auth:
    rbac:
      rootPassword: secretpassword
  replicaCount: 3
```
then the new cluster starts with
```sh
I have no name!@foo-etcd-0:/opt/bitnami/etcd$ echo $ETCD_INITIAL_CLUSTER_STATE
existing
```

### What is the expected behavior?

The cluster should bootstrap a new cluster

```sh
INFO  ==> ** Starting etcd setup **
INFO  ==> Validating settings in ETCD_* env vars..
INFO  ==> Initializing etcd
INFO  ==> Generating etcd config file using env variables
INFO  ==> There is no data from previous deployments
INFO  ==> Bootstrapping a new cluster
```

### What do you see instead?

The cluster tries to join an existing cluster

```sh
INFO  ==> ** Starting etcd setup **
INFO  ==> Validating settings in ETCD_* env vars..
INFO  ==> Initializing etcd
INFO  ==> Generating etcd config file using env variables
INFO  ==> There is no data from previous deployments
INFO  ==> Adding new member to existing cluster
```

### Additional information

The existing cluster is called `foo-etcd-cluster` with pods called something like `foo-etcd-cluster-abc1234` and the new cluster is called `foo-etcd` with pods called `foo-etcd-0`. It seems that the initial cluster discovery picks up the existing cluster nodes and _thinks_ it should join that cluster instead of bootstrapping the new cluster.

I logged into the cluster and saw that `$ETCD_INITIAL_CLUSTER_STATE` is set to `existing` instead of `new` so it seems that it discovers the other nodes from the existing cluster. The environment variables `$ETCD_INITIAL_CLUSTER` and `$ETCD_INITIAL_ADVERTISE_PEER_URLS` contain correctly only the new cluster nodes.

The existing cluster is using the [`coreos/etcd-operator`](https://github.com/coreos/etcd-operator) and this is an attempt to migrate away from that deprecated operator through a graceful migration.

**Comment by jan-xyz** [comment]
@carrodher could it be that it is due to [this line in the statefulset](https://github.com/bitnami/charts/blob/d36311748078c08e2ad5a8cc64b2c02007304636/bitnami/etcd/templates/statefulset.yaml#L191-L192)? I read it that it is basically determining it automatically based on if it is a new helm chart installation or not, so adding it retroactively to a chart won't work?

**Comment by carrodher** [comment]
Can you try setting the `initialClusterState` to `existing`?
```yaml
## @param initialClusterState Initial cluster state. Allowed values: 'new' or 'existing'
## If this values is not set, the default values below are set:
## - 'new': when installing the chart ('helm install ...')
## - 'existing': when upgrading the chart ('helm upgrade ...')
##
initialClusterState: ""
```

Otherwise, the default value when running `helm install` will be `new`

**Comment by jan-xyz** [comment]
It works initially to bootstrap the cluster if I set `initialClusterState: new`, but after that I can't touch the cluster anymore. I can't leave it in new because any modification will mean that new pods are trying to bootstrap their own new cluster.
```sh
INFO  ==> ** Starting etcd setup **
INFO ==> Validating settings in ETCD_* env vars..
INFO  ==> Initializing etcd
INFO  ==> Generating etcd config file using env variables
INFO  ==> There is no data from previous deployments
INFO  ==> Bootstrapping a new cluster
INFO  ==> Obtaining cluster member ID
INFO  ==> Starting etcd in background
```
and then just hang, unable to join the existing cluster. But I also can't remove the `initialClusterState` because it then crashes with:
```sh
INFO  ==> ** Starting etcd setup **
INFO  ==> Validating settings in ETCD_* env vars..
INFO  ==> Initializing etcd
INFO  ==> Generating etcd config file using env variables
INFO  ==> There is no data from previous deployments
INFO  ==> Adding new member to existing cluster
/opt/bitnami/scripts/libetcd.sh: line 732: ETCD_ACTIVE_ENDPOINTS: unbound variable
```

**Comment by carrodher** [comment]
According to that, the parameter used should be `initialClusterState: new`, that is the only way to deploy the Helm chart from scratch. Then you can also add the `image.debug: true` parameter so more information will appear in the container logs so you can see what actions are being taken during the etcd initialization.

**Comment by jan-xyz** [comment]
> According to that, the parameter used should be initialClusterState: new, that is the only way to deploy the Helm chart from scratch.

That's clear, however I can leave it like that. On subsequent deployments of the chart I need to handle that parameter and whatever I do with it, the cluster hangs in a limbo as described above.

**Comment by fmulero** [comment]
Hi @jan-xyz I'll try to explain the steps I followed and share my results

1. I have a simple `my-app` (created with `helm create my-app`) chart with my application already installed on my cluster as `test` release. (without any dependency with `bitnami/etcd`)
2. I added `bitnami/etcd` dependency to my chart with following default values:
```yaml
etcd:
  auth:
    rbac:
      rootPassword: secretpassword
  replicaCount: 3
```
3. I upgraded the chart setting  `etcd.initialClusterState=new` to create a new etcd cluster
```console
$ helm upgrade test my-app --set etcd.initialClusterState=new
```
4. At this point we can see how the etcd cluster is created as new:
```
etcd 10:51:45.55 INFO  ==> ** Starting etcd setup **
etcd 10:51:45.56 INFO  ==> Validating settings in ETCD_* env vars..
etcd 10:51:45.56 INFO  ==> Initializing etcd
etcd 10:51:45.57 INFO  ==> Generating etcd config file using env variables
etcd 10:51:45.58 INFO  ==> There is no data from previous deployments
etcd 10:51:45.58 INFO  ==> Bootstrapping a new cluster
```
5. Upgrade again the release without setting the `etcd.initialClusterState`:
```console
$ helm upgrade test my-app
```
6. At this point the etcd cluster is rebuild but the new pods are joining to the existing cluster:
```
etcd 11:17:05.46 INFO  ==> ** Starting etcd setup **
etcd 11:17:05.47 INFO  ==> Validating settings in ETCD_* env vars..
etcd 11:17:05.47 INFO  ==> Initializing etcd
etcd 11:17:05.47 INFO  ==> Generating etcd config file using env variables
etcd 11:17:05.49 INFO  ==> Detected data from previous deployments
etcd 11:17:05.74 INFO  ==> Adding new member to existing cluster
etcd 11:17:05.87 INFO  ==> Obtaining cluster member ID
etcd 11:17:05.87 INFO  ==> Starting etcd in background
etcd 11:17:09.13 INFO  ==> Stored member ID: a837300082a412d6
```

I won't be able to reproduce your issue, please amend me if miss any step or something is wrong in my assumptions.

**Comment by jan-xyz** [comment]
I had to park work on the ticket for now, but I am planning to come back to this, I just don't have the capacity for now to continue here. Is it fine to leave it open until then?

I was wondering if it makes a difference for Kubernetes if I set the variable as a helm flag
```
$ helm upgrade test my-app --set etcd.initialClusterState=new
```
vs adding it to the values.yaml
```
etcd:
  initialClusterState: new
  auth:
    rbac:
      rootPassword: secretpassword
  replicaCount: 3
```

I'm running
```
❯ kubectl version --short
Client Version: v1.25.1
Kustomize Version: v4.5.7
Server Version: v1.24.5
❯ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```
I'm not sure if that makes a difference.

**Comment by fmulero** [comment]
My versions are slightly different, maybe is worth to upgrade
```console
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.24.0
$ helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```
