### ISSUE TITLE
[bitnami/kafka] advertisedListeners cannot be set unless externalAccess.enabled is set to true.

### ISSUE THREAD

**Issue by DmitryZakharov** [bitnami/charts#12280]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

Custom configuration values for advertisedListeners and listeners are configured. But I am forced to set externalAccess.service.type to either LoadBalancer or NodePort.

### Are you using any custom parameters or values?

Custom configuration values for advertisedListeners and listeners are configured.

### What is the expected behavior?

I should be able to set custom listeners and advertisedListeners without the need to set externalAccess.enabled to true.

### What do you see instead?

I am forced to set externalAccess to true: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L85 as the following block (https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L111-L117) is inside the if statement above. Which is not what is desired as externalAccess forces to use service type either LoadBalancer or NodePort.

### Additional information

In my eyes if I want to configure custom/advanced schemas of listeners and advertisedListeners I must not be bound to the basic configuration or must not be force to have specific service types unless there is a very good reason for that.

there is a proposed extension of the current charts : https://github.com/bitnami/charts/pull/11853
however, I would think adding ClusterIP to the ExternalAccess service types makes externalAccess unclear. However it is understandable that it is required when we use ingress on top of it.

I would rather see that advertisedListeners configuration (https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L111-L117) is moved out from ExternalAccess **if** statement  https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L85 - https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml#L117

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! Would you like to try that proposed change in the chart and submit a PR?

**Comment by DmitryZakharov** [comment]
Yes, I would be happy to try it out, but I would like to first understand if my train of thoughts is in general correct. 
Would you be able to provide a critique of what i am saying ?

**Comment by javsalgar** [comment]
I think it makes sense to move that part out of the if. Right now I don't see a reason to keep it inside.
