### ISSUE TITLE
[bitnami/cassandra] Adding a volumeMounts subPath setting to a deployment/statefulset

### ISSUE THREAD

**Issue by lbrpsoftware** [bitnami/charts#12297]
### Name and Version

bitnami/cassandra:9.4.2

### What is the problem this feature will solve?

I'm mounting nodes in a kind cluster on my local desktop using hostpath.
Every persistent application mounts to the same directory with a subdirectory named after the application.
This will keep application data separated from others.

### What is the feature you are proposing to solve the problem?

This is done by setting a subPath in the helm deployment values.
MariaDB, MongoDB, PostgreSql, ... all have a setting to override.

### What alternatives have you considered?

I could create a new total new mount I guess.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I'm not sure I fully understand the feature you are requesting. Would it be that each statefulset node has its own hostpath volume mount? This would work if each pod gets deployed in a different k8s node or there would be conflicts, right?
