### ISSUE TITLE
[bitnami/wordpress] Deploying a htaccess file via a config-map does not seem to work

### ISSUE THREAD

**Issue by EugenMayer** [bitnami/charts#12293]
### Name and Version

bitname/wordpress 15.2.0

### What steps will reproduce the bug?

1. deploy a config map including the `wordpress-htaccess.conf` including your htaccess file content
2. set customHTAccessCM in the chart to reference the configMap name
3. set / leave allowOverrideNone to false

You should see the config map to be deployed to 
```
/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf
```
and see that it is included from `/opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf`

### Are you using any custom parameters or values?
```yaml
customHTAccessCM: ${customHtAccessCM}
allowOverrideNone: false
```
### What is the expected behavior?

The statements of the htaccess file should be respected, but neither the expiry nor the CORS headers are set.

### What do you see instead?

No cores headers/expiry headers are set in the response.

You can test it yourself: `curl -I https://drupal-wiki.com/wp-content/uploads/quotes-white.png`

Should allow any origin due to these statements in the htaccess file

```
# Send CORS headers if browsers request them; enabled by default for images.
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
# mod_headers, y u no match by Content-Type?!
<FilesMatch "\.(avifs?|cur|gif|png|jpe?g|svgz?|ico|webp)$">
SetEnvIf Origin ":" IS_CORS
Header set Access-Control-Allow-Origin "*" env=IS_CORS
</FilesMatch>
</IfModule>
</IfModule>
```

**Comment by carrodher** [comment]
Could you check if the file is properly copied but then it's removed/overwritten? There is a `htaccessPersistenceEnabled` value which is specific for persisting this file, could you try enabling it?

[Here](https://docs.bitnami.com/kubernetes/apps/wordpress/configuration/understand-htaccess/) you can find more info about this topic.

**Comment by EugenMayer** [comment]
As written above, the file is on the container and has the proper expected content on the path that is included by the vhost configuration

**Comment by wibed** [comment]
here is an example that worked for me
@EugenMayer https://github.com/bitnami/charts/issues/8120
