### ISSUE TITLE
 [bitnami/tomcat] Unclear enforcement of tomcatPassword on upgrades

### ISSUE THREAD

**Issue by danielhass** [bitnami/charts#12296]
### Name and Version

bitnami/tomcat 10.4.3

### What steps will reproduce the bug?

1. Install the bitnami/tomcat chart onto a cluster with a values.yaml that contains an empty `tomcatPassword` value (which is the default)
2. Attempt an upgrade of this deployment

### What is the expected behavior?

The upgrade should proceed without and error. In the described case (`tomcatPassword` is empty) the Helm Chart auto generates a password for the Tomcat Manager User.

See: https://github.com/bitnami/charts/blob/master/bitnami/tomcat/templates/secrets.yaml#L18

This secret is should be technically enough to attempt subsequent upgrades without an manual input by the user. The password based on my knowledge of the Chart is only used in the `libtomcat.sh` during startup: https://github.com/bitnami/containers/blob/6b0581771bf13be39df66a372508d195b6367464/bitnami/tomcat/10/debian-11/rootfs/opt/bitnami/scripts/libtomcat.sh#L89

This alters the `tomcat-users.xml` that is only persisted in the containers ephemeral storage (nothing is saved to a PV). This fact contradicts with the reasoning in the link that should provide further information regarding the error (see below). There the following is stated:
> Bitnami containers configure/initialize applications the first time they are deployed. However, they skip this configuration/initialization step and reuse persisted data if detected on subsequent deployments or upgrades.

From my perspective this doesn't seem to be the case with the tomcat chart. Here the secret is exported as environment variable on every startup. Additionally the `tomcat-users.xml` needs to be generated on every container startup as it is located in the ephemeral storage.

The PV (per default mounted under `/bitnami/tomcat`) only contains the tomcats `webapps` directory.

### What do you see instead?

A error is present to the user claiming that the `tomcatPassword` must be set in order to proceed.

For further information the error points to: https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

### Additional information

From my understanding this enforcement of the `tomcatPassword` being set on subsequent upgrades is not necessary as the password is stored properly inside a Kubernetes Secret that is evaluated automatically on every container startup.

I would vote for the removal of this check in https://github.com/bitnami/charts/blob/master/bitnami/tomcat/templates/NOTES.txt

This might be related to #6250

**Comment by javsalgar** [comment]
Hi,

In other charts we use the `fetch` function to detect if the secret exists. If the secret exists, then do not generate a new password. Would this work for the issue described here?

**Comment by danielhass** [comment]
Hi @javsalgar, thanks for your fast reply. Could you point me to one of the existing charts that make use of the described `fetch` function? This information provided I'm happy to check if this could help with this issue.

**Comment by danielhass** [comment]
@javsalgar - thanks for pointing me to the postgresql chart. That helped a lot.

I pushed a draft to the following PR: #12401

From my point of view the results of my local testing look promising. However I noticed a certain behaviour of the `"common.secrets.passwords.manage"` function that might not produce the results wanted in this particular situation.

From the docs found here https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_secrets.tpl#L62 the common function will always read the value from the existing secret if it already exists. In a situation where users want to change the password provided via the values.yaml in `tomcatPassword`, this value wouldn't be updated in the secret. Technically such an update would work provided the associated pod is restarted to re-read the values from the secret.

Is this behaviour already addressed by some other common function or bitnami general best practices?

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look. Normally, because of the nature of the applications (which store the secret in their data volumes), a change in the secret won't imply a change in the password in a wide variety of applications, such as PostgreSQL, WordPress, MariaDB or similar. This is something we are aware of and currently we don't have plans to make the secret fully declarative, because of the inherent complexity in each application automated configuratien.

**Comment by danielhass** [comment]
@javsalgar - as I was away for the last few weeks I didn't notice this issue and the associated PR getting closed as stale. Can this issue and the PR be reopended again?
