### ISSUE TITLE
Not able to push the code to bitnami/charts

### ISSUE THREAD

**Issue by vinokuma** [bitnami/charts#12302]
### Name and Version

bitnami/charts

### What steps will reproduce the bug?

1. I have made the changes in bitnami/charts/consul
2. I have tested in our environment, and we are able to see the changes affected in the running pods.
3. I did git commit and sign-offed with my email and user name.
4. When I am trying to push the changes which is in my local, I am getting the below error
`ERROR: Permission to bitnami/charts.git denied to vinokuma`

### Are you using any custom parameters or values?

I have added one parameter to the consul/values.yaml

### What is the expected behavior?

Should be able to push the changes successfully, without any errors

### What do you see instead?
```
ERROR: Permission to bitnami/charts.git denied to vinokuma.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by carrodher** [comment]
In order to contribute to this repo you need to do it from a personal fork, see the [CONTRIBUTING guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md)

**Comment by vinokuma** [comment]
Okay, got it. Thank you so much for helping me out
