### ISSUE TITLE
[bitnami/rabbitmq] how to configure rabbitmq-auth-backend-http 

### ISSUE THREAD

**Issue by janiu-001** [bitnami/charts#12304]
### Name and Version

master

### What steps will reproduce the bug?

i planed to use plugin  rabbitmq-auth-backend-http , but i do not find any doc about how to config the following param

auth_http.http_method   = post
auth_http.user_path     = http://backend:8083/mqtt/user
auth_http.vhost_path    = http://backend:8083/mqtt/vhost
auth_http.resource_path = http://backend:8083/mqtt/resource
auth_http.topic_path    = http://backend:8083/mqtt/topic

### What do you see instead?

no

**Comment by janiu-001** [comment]
@javsalgar would you help  on this issue?

**Comment by janiu-001** [comment]
the issue is solved by :

<img width="780" alt="image" src="https://user-images.githubusercontent.com/19970581/189058731-5c3baf48-7831-4016-a3a0-7187562654bb.png">

**Comment by janiu-001** [comment]
Another question:
i tested the authentication with command:
mqtt pub  -u "niubaoke" -P "666666" -t '/shadow/update/walabot_home_gen2/id_MzA6QUU6QTQ6RTM6RTc6RkM' -h '127.0.0.1' -m "Hello World"


I could not get the username and password from the request body

**Comment by javsalgar** [comment]
Hi!

Thanks for sharing your solution! Can we close this issue then?

**Comment by janiu-001** [comment]
Could  you help  another question? 

i tested the authentication with command: mqtt pub -u "niubaoke" -P "666666" -t '/shadow/update/test' -h '127.0.0.1' -m "Hello World"
I could not get the username and password from the request body

**Comment by javsalgar** [comment]
Hi,

It seems to me that this follow-up question now more orientated on how RabbitMQ works rather than the Bitnami packaging itself, right? Did you try asking to the RabbitMQ devs in this case?
