### ISSUE TITLE
[bitnami/kong] Kong Proxy service gets External IP as pending

### ISSUE THREAD

**Issue by suchits07** [bitnami/charts#12306]
### Name and Version

bitnami/kong 2.5

### What steps will reproduce the bug?

1. Deploy kong in the AWS EKS clusters
2. The kong proxy created service waits for the AWS NLB to be attached infinitely due to the following error;

`service-controller Error syncing load balancer: failed to ensure load balancer: error describing load balancer: \"Throttling: Rate exceeded\\n\\tstatus code: 400, request id: e196bb82-7787-4f0f-a3d6-24a71aa99269\"`

### Are you using any custom parameters or values?

Nope

### What is the expected behavior?

Kong should wait for making this API call when it faces the throttle. Is there any configration/plugin at kong level to reduce the API call or increase the interval in between two calls?

### What do you see instead?

When the kong ingress controller gets deployed with service type as LoadBalancer, the external IP remains in pending state due to the following error:

service-controller Error syncing load balancer: failed to ensure load balancer: error describing load balancer: \"Throttling: Rate exceeded\\n\\tstatus code: 400, request id: e196bb82-7787-4f0f-a3d6-24a71aa99269\"

We are using Kong on AWS EKS cluster with NLB Load Balancer. We are seeing this behaviour whenever kong is deployed in our cluster. On consulting with AWS, we got to know that EKS is making DescribeELB API Calls on the behest of the kong.

**Comment by javsalgar** [comment]
Hi,

I believe that, in this case, the kong developers should be the ones to step in and provide insight on configurations and plugins. Did you try asking the upstream kong developers?
