### ISSUE TITLE
[bitnami/keycloak] cannot configure initContainers for keycloakConfigCli job

### ISSUE THREAD

**Issue by davgia** [bitnami/charts#12310]
### Name and Version

bitnami/keycloak 9.8.0

### What is the problem this feature will solve?

Currently it's not possible to configure initContainers for keycloakConfigCli job.

### What is the feature you are proposing to solve the problem?

Enable to configure initcontainers from chart values.

**Comment by carrodher** [comment]
Thanks for the suggestion. At this moment, you can add generic initContainers, see https://github.com/bitnami/charts/tree/master/bitnami/keycloak#use-sidecars-and-init-containers 

In the case of any other more specific feature, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by DaviGia** [comment]
Hi @carrodher,

I am aware of the possibility to configure initContainers and sidecars for the keycloak statefulset. Nevertheless the request is related to the included k8s job template to execute keycloak-config-cli application.

I will create a PR to address this as soon as possible.
