### ISSUE TITLE
[bitnami/solr] Persistent Volume is not used in solr deployment

### ISSUE THREAD

**Issue by PascalTurbo** [bitnami/charts#12315]
### Name and Version

bitnami/solr

### What steps will reproduce the bug?

Use the solr helm chart as is and enable persistence by setting `persistence.enable = true`

### What is the expected behavior?

Should create and use PV for storing data.

### What do you see instead?

It's not using PV for storing data.

### Additional information

Have a look at https://github.com/bitnami/charts/blob/master/bitnami/solr/templates/statefulset.yaml#L359 
This condition says, that volume with name "data" is only created and bound to the PV if "existingClaim" is set (or if persistence is disabled, it's created as emptydir).

What is missing here is that volume with name data is bound to the automatically created PV.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for spotting the issue! I think it should be

```
        {{- if or .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . | default "data" }}
        {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}

```

Would you like to submit a PR with the fix?

**Comment by javsalgar** [comment]
Ok, after a second review, I thought I was checking the volumeMounts section and I was actually checking the alternative part of the volume definition. 

The persistent volume name is set in the persistentVolumeClaimTemplate section, where you set a prefix for the PVCs and it will create one for pod.

**Comment by javsalgar** [comment]
I will close the issue as, indeed, the YAML was correct.
