### ISSUE TITLE
[bitnami/reportserver] - create kubernetes charts

### ISSUE THREAD

**Issue by chrispward** [bitnami/charts#12317]
### Name and Version

ReportServer:latest

### What is the problem this feature will solve?

Would like to deploy Reportserver to Kuberenetes.
You've done created it for docker.  Would like u to do the same to run on kubernetes.

### What is the feature you are proposing to solve the problem?

Using ReportServer on Kubernetees

### What alternatives have you considered?

None. We dont use docker on its own.
We have huge k8 cluster.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! I will forward it to the team for evaluation. However, at the moment there are already new products in the pipeline so we cannot guarantee it in the short/mid term. In case the team decides to go ahead with this chart, we will update the ticket.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
