### ISSUE TITLE
[bitnami/redis-cluster] restore cluster from snapshot.rdb file

### ISSUE THREAD

**Issue by liad-haber** [bitnami/charts#12334]
### Name and Version

bitnami/redis-cluster 7.5.3

### What steps will reproduce the bug?

When trying to create a new cluster from previous created cluster snapshots I get the following error messages:
[ERR] Node X.X.X.X:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.

The cluster was already created, the nodes should have recovered it

My flow:
initcontainer to check if /bitnami/redis/data/snapshot.rdb file exists, if not - downloads at from S3.

What am I missing / doing wrong ?

### Are you using any custom parameters or values?

      configmap: |
          save ""
          save "86400 1"
          maxmemory 439804651110
          appendonly no
          maxclients 20000
          slave-read-only yes
          dbfilename snapshot.rdb
          dir /bitnami/redis/data
          io-threads 8
          io-threads-do-reads yes
          repl-backlog-size 204800

### What is the expected behavior?

Redis cluster up and running with data from older snapshots. 

### What do you see instead?

Each node is created in standalone mode -
45e83aa221597f38627097bc22a9ef582f4261fe X.X.X.X:6379@16379 myself,master - 0 0 0 connected 2048-4095

**Comment by javsalgar** [comment]
Hi,

Could you provide a sample rdb file that triggers the issue?

**Comment by liad-haber** [comment]
Hi,
Unfortunately due to GDPR we cannot share our data. I assume the issue will reproduce with any .rdb file(Nothing special in our data / keys).
