### ISSUE TITLE
[bitnami/contour] HPA for envoy can't use capabilities to detect API version

### ISSUE THREAD

**Issue by demikl** [bitnami/charts#12338]
### Name and Version

bitnami/contour 9.1.2

### What steps will reproduce the bug?

Use chart bitnami/contour 9.1.2 and enable HPA on envoy, then `helm template` will fail

### What is the expected behavior?

helm templating function `common.capabilities.hpa.apiVersion` should return apigroup & version for detected K8S version

### What do you see instead?

```
Error: template: contour/templates/envoy/hpa.yaml:2:15: executing "contour/templates/envoy/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" (dict "context" $)>: error calling include: template: contour/charts/common/templates/_capabilities.tpl:133:32: executing "common.capabilities.hpa.apiVersion" at <include "common.capabilities.kubeVersion" .>: error calling include: template: contour/charts/common/templates/_capabilities.tpl:7:14: executing "common.capabilities.kubeVersion" at <.Values.global>: nil pointer evaluating interface {}.global
```

### Additional information

Since upgrading the dependency to bitnami/common 2.0.2, you need to modify :

`templates/envoy/hpa.yaml`

```
- apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
+ apiVersion: {{ include "common.capabilities.hpa.apiVersion" . }}
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by demikl** [comment]
Sure, here is the PR : https://github.com/bitnami/charts/pull/12352

**Comment by carrodher** [comment]
Thanks for the PR, the team will review it and provide feedback!
