### ISSUE TITLE
Make ETCD_LOG_LEVEL configurable

### ISSUE THREAD

**Issue by alop** [bitnami/charts#12346]
### Name and Version

bitnami/etcd 8.4.5

### What is the problem this feature will solve?

Reduction in the amount of logs.
etcd has only 2 choices for log_level: debug and info.

Using simple tokens, the amount of logs generated in the info level is astronomical. Miles and miles of:

```
{"level":"info","ts":"2022-09-09T04:54:24.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"xSBDnbKRadIZGIXh.1891539"}
{"level":"info","ts":"2022-09-09T04:54:26.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"SzDpeQIngIvrGDIE.1891541"}
{"level":"info","ts":"2022-09-09T04:54:30.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"kfoUHSsJeOeoMgSJ.1891543"}
{"level":"info","ts":"2022-09-09T04:54:30.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"LQsaeIcwjvBOfInT.1891545"}
{"level":"info","ts":"2022-09-09T04:54:32.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"sYDwqxmePPKFEnoO.1891547"}
{"level":"info","ts":"2022-09-09T04:54:33.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"fsPDdQQdrRDOOykL.1891549"}
{"level":"info","ts":"2022-09-09T04:54:33.331Z","caller":"auth/simple_token.go:165","msg":"deleted a simple token","user-name":"root","token":"ZOFYtSjixVbqCRSP.1891551"}
```

I want to be able to set etcd to 'warn' - which I can do if I manually edit the sts/etcd and change ETCD_LOG_LEVEL to warn. The problem is during a fresh deploy or redeploy, the value of ETCD_LOG_LEVEL is based on ternary between debug and info.

Please Please, this should be a standard helm value that can be set to any valid log level that etcd supports.

### What is the feature you are proposing to solve the problem?

ETCD_LOG_LEVEL should be a standard parameter that can be set in values.yaml or via --set

### What alternatives have you considered?

manually editing the sts/etcd after deployment, but this is not tenable.

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR. The team will review it and provide feedback
