### ISSUE TITLE
BGSAVE error on redis cluster

### ISSUE THREAD

**Issue by Shujja1746** [bitnami/charts#12342]
### Name and Version

bitnami/redis-cluster 7.4.3

### What steps will reproduce the bug?

Deploy 22 nodes cluster with 1 master and 1 slave on aks.

Ingest data to redis cluster, each node must contain in-memory data around 40GB or more

AKS nodes 3 instances of size m128, total ram 6TB

### Are you using any custom parameters or values?

Using values.yaml file and --version 7.4.3
```yaml
nodes: 22
replica: 1
type: LoadBalancer

storageClass: "Premium"
size: 256Gi
```

### What is the expected behavior?

BGSAVE and SAVE should work as expected with 40GI data or more for each redis nodes

### What do you see instead?

![image](https://user-images.githubusercontent.com/100185414/189215130-32e604b1-383c-41ba-8f83-ad20d8735fa3.png)

### Additional information

![image](https://user-images.githubusercontent.com/100185414/189215319-d6d084da-c4ea-4450-bfd1-7fa9f05f1508.png)

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Redis container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
