### ISSUE TITLE
Failed to pull image "docker.io/bitnami/spark:3.3.0-debian-11-r26": rpc error: code = Unknown desc = context deadline exceeded

### ISSUE THREAD

**Issue by charles138** [bitnami/charts#12359]
### Name and Version

bitnami/spark

### What steps will reproduce the bug?

Commands:
```
kubectl create namespace spark
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install spark3 --namespace spark bitnami/spark
```
Error Message from minikube dashboard:
```
Failed to pull image "docker.io/bitnami/spark:3.3.0-debian-11-r26": rpc error: code = Unknown desc = context deadline exceeded
```
I checked the version number from https://hub.docker.com/r/bitnami/spark and it should be 3.3.0-debian-11-r27.

org.opencontainers.image.ref.name="3.3.0-debian-11-r27"
https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/Dockerfile

### Are you using any custom parameters or values?

None.

### What is the expected behavior?

Please pull the latest version: 3.3.0-debian-11-r27.

### What do you see instead?

Error Message from minikube dashboard:
```
Failed to pull image "docker.io/bitnami/spark:3.3.0-debian-11-r26": rpc error: code = Unknown desc = context deadline exceeded
```

**Comment by carrodher** [comment]
I am not able to reproduce the issue. Both images are present in DockerHub and pullable:
```console
$ docker pull docker.io/bitnami/spark:3.3.0-debian-11-r27
3.3.0-debian-11-r27: Pulling from bitnami/spark
Digest: sha256:2aa5e17f707a9411560028605f7f37864fc66894523dc83d301d5047e2cf8a1f
Status: Image is up to date for bitnami/spark:3.3.0-debian-11-r27
docker.io/bitnami/spark:3.3.0-debian-11-r27

$ docker pull docker.io/bitnami/spark:3.3.0-debian-11-r26
3.3.0-debian-11-r26: Pulling from bitnami/spark
Digest: sha256:7cffa0737b9ae7313b0aee78489a7a4af3ccdb477609d8cc9e17ca8769251a87
Status: Image is up to date for bitnami/spark:3.3.0-debian-11-r26
docker.io/bitnami/spark:3.3.0-debian-11-r26
```

**Comment by charles138** [comment]
I pulled the image "docker pull docker.io/bitnami/spark:3.3.0-debian-11-r26" like you suggested and it's working now.
Thank you for your quick reply.
