### ISSUE TITLE
minecraft server hosting application?

### ISSUE THREAD

**Issue by adsbv** [bitnami/charts#12367]
application for minecraft server hosting

bitnami 1.38

### What is the problem this feature will solve?

since minecraft server hosting is complicated enough, why not make an application that hosts the server for you and you can also put plugin files by dragging or selecting the plugin file! 

### What is the feature you are proposing to solve the problem?

many people cannot figure out how to host a minecraft server so an application that does just that just like how you guys made one for mediawiki would help SO many people and make everything easier.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Do you have any open source project in mind that solves that issue? If there is one, I could forward the request for evaluation.

**Comment by nilathedragon** [comment]
Perhaps the charts and images here can be used to make such a thing? https://github.com/qumine
Specifically https://github.com/qumine/ingress-controller and https://github.com/qumine/minecraft-server

**Comment by javsalgar** [comment]
Thank you! I will forward these projects for evaluation

**Comment by 0SkillAllLuck** [comment]
As the maintainer of those charts, I just want to inform you that they are currently being reworked with better documentation, values.schema.json files and new images that allow for more functionality

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
