### ISSUE TITLE
argo-workflows image index

### ISSUE THREAD

**Issue by Modzog** [bitnami/charts#12376]
### Name and Version

bitnami/argo-workflows 2.3.2

### What is the problem this feature will solve?

Hi,

In your chart values I'm missing options for image index as mentioned in here:
https://argoproj.github.io/argo-workflows/workflow-executors/#image-index

Even if I manually edit argo-workflows-controller config map the section images: is completely ignored.

Thanks

Best Regards
Michal

### What is the feature you are proposing to solve the problem?

Add Argo Workflows Controller configuration parameters
```yaml
controller.images: {}
```

### What alternatives have you considered?

Manually editing config using `kubectl edit cm`.

Using option `controller.config`

Neither of the above makes the controller pick up the image command.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
