### ISSUE TITLE
[bitnami/common] common.secrets.passwords.manage and quotes

### ISSUE THREAD

**Issue by MikeVL** [bitnami/charts#12371]
### Name and Version

bitnami/rabbitmq 10.3.5

### What steps will reproduce the bug?

rabbitmq restart on every update.

StatefulSet annotations update hash of checksum/secret

### What do you see instead?

```diff
vluki, rabbitmq, Secret (v1) has changed:
  # Source: vluki-backend/charts/rabbitmq/templates/secrets.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: rabbitmq
    namespace: "vluki"
    labels:
      app.kubernetes.io/name: rabbitmq
      helm.sh/chart: rabbitmq-10.3.5
      app.kubernetes.io/instance: backend
      app.kubernetes.io/managed-by: Helm
  type: Opaque
  data:
-   rabbitmq-password: WFliMzMzUEtzVA==
+   rabbitmq-password: "WFliMzMzUEtzVA=="

-   rabbitmq-erlang-cookie: UVJmaGhsM05BYVdvQnh5OHpyUjVGYmxrWWdQdTJsWm0=
+   rabbitmq-erlang-cookie: "UVJmaGhsM05BYVdvQnh5OHpyUjVGYmxrWWdQdTJsWm0="
```

### Additional information

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_secrets.tpl#L122

Raplace with: {{- $password -}}

**Comment by fmulero** [comment]
Good catch!! Thanks @MikeVL

**Comment by baksha97** [comment]
Having the same issue. Current workaround was to set the auth cookie to some arbitrary value to prevent the StatefulSet diff. Looking for a more appropriate solution, if possible.

**Comment by fmulero** [comment]
Hi Alfayed

Could you open a new issue with more details? Could the chart you are using be outdated and it is using an old version of common chart?
