### ISSUE TITLE
Using postgresql extendedConfiguration doesn't update in the existing release.

### ISSUE THREAD

**Issue by anandanand84** [bitnami/charts#12399]
### Name and Version

bitnami/postgresql 11.8.1

### What steps will reproduce the bug?

Create postgresql as a dependency to an existing chart. 

Create and run the chart with default values for postgresql. 

Once the app is created, change the config file by adding extendedConfiguration. The new configuration is not reflected. 

### Are you using any custom parameters or values?

```
--set postgres.image.repository=postgres \
--set postgres.image.tag=11.6 \
--set postgres.primary.persistence.existingClaim=data-sandbox-postgres-0 \
```
and extendedConfiguration
```
postgres:
  primary:
      extendedConfiguration: |
        max_connections = 1024
        shared_buffers = 512MB
        effective_cache_size = 1536MB
        maintenance_work_mem = 128MB
        checkpoint_completion_target = 0.9
        wal_buffers = 16MB
        default_statistics_target = 100
        random_page_cost = 1.1
        effective_io_concurrency = 200
        work_mem = 256kB
        min_wal_size = 1GB
        max_wal_size = 4GB
        log_directory = '/bitnami/postgresql/pg_log'
        logging_collector = on
        log_min_duration_statement = 500
        max_standby_streaming_delay = -1
        tcp_keepalives_idle = 180
        tcp_keepalives_interval = 10
        tcp_keepalives_count = 3
```

### What is the expected behavior?

Expect the show max_connections; to return 1024 instead it still has 100.

### What do you see instead?

dont see the updated max_connections only the default value of 100 is seen.

**Comment by rafariossaa** [comment]
Hi,
  Once the chart is deployed with one configuration you can not change it. In order to do this, you need to create a new deployment with the desired configuration and import the data.

**Comment by travnewmatic** [comment]
I was able to change `max_connections` after the fact.

In my argocd application, I set:
```
      - name: primary.extendedConfiguration
        value: |
          max_connections = 1024
```
application synced, got a shell into postgres and checked:
```
I have no name!@postgresql-0:/$ PGPASSWORD=xxxxxx psql -Upostgres
psql (14.5)
Type "help" for help.

postgres=# SHOW max_connections;
 max_connections
-----------------
 1024
(1 row)

postgres=#
```

i'm on chart ver 11.9.13
