### ISSUE TITLE
Feature request: custom plugins for fluentd containers

### ISSUE THREAD

**Issue by jeffb4** [bitnami/charts#12409]
### Name and Version

bitnami/fluentd 5.4.1

### What is the problem this feature will solve?

At this time, using fluentd plugins not baked into the fluentd image requires baking a custom image. Often, that's an undesirable hurdle.

### What is the feature you are proposing to solve the problem?

Add an optional init container for fluentd containers that runs as root and allows `fluent-gem` install of necessary plugins, with a shared volume mount that is then used by the main fluentd containers.

### What alternatives have you considered?

An alternative would be baking my own container. `fluent-gem` in the running container fails due to running as non-root for aggregator, so a custom command/args would not work there (but might in forwarder pods).

**Comment by fmulero** [comment]
Hi @jeffb4 Thanks for opening this issue.

We have an internal task to allow users install new plugins but to be perfectly blunt, we are not able to give any ETA to address it. You can find more information in bitnami/containers#990 even some tricks to install the gems overriding the `command` and the `args` for the deployment.

Also you can define and use your own `initContainer` to build/download your gems and share them with the other fluentd containers. In this [comment](https://github.com/bitnami/charts/issues/12178#issuecomment-1235613535) you have an example where we define new `initContainers` and new `extraVolumes` in values file to modify and share a jks file with the main container.
