### ISSUE TITLE
[bitnami/keycloak] HPA can't use capabilities to detect API version

### ISSUE THREAD

**Issue by hendrik-schaffer** [bitnami/charts#12421]
### Name and Version

bitnami/keycloak 10.0.0

### What steps will reproduce the bug?

Use chart bitnami/keycloak 10.0.0 and enable autoscaling `--set autosacling.enabled=true` then a `helm template` will fail.

### What is the expected behavior?

helm templating function common.capabilities.hpa.apiVersion should return apigroup & version for detected K8S version

### What do you see instead?

Error Log 
`Error: template: keycloak/charts/keycloak/templates/hpa.yaml:2:15: executing "keycloak/charts/keycloak/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" (dict "context" $)>: error calling include: template: keycloak/charts/keycloak/charts/common/templates/_capabilities.tpl:133:32: executing "common.capabilities.hpa.apiVersion" at <include "common.capabilities.kubeVersion" .>: error calling include: template: keycloak/charts/keycloak/charts/common/templates/_capabilities.tpl:7:14: executing "common.capabilities.kubeVersion" at <.Values.global>: nil pointer evaluating interface {}`

### Additional information

Seems likely to be the same issue as in https://github.com/bitnami/charts/issues/12338 or https://github.com/bitnami/charts/issues/12309

**Comment by erickaby** [comment]
Fixed in this pr https://github.com/bitnami/charts/pull/12423

**Comment by fmulero** [comment]
In a few hours the new chart will be released
