### ISSUE TITLE
[bitnami/mongodb-sharded] - Cluster-to-Cluster Sync - Data Synchronization between K8s Cluster

### ISSUE THREAD

**Issue by zohebs341** [bitnami/charts#12436]
### Name and Version

bitnami/mongodb-sharded 4.4.9-debian-10-r20

### What is the problem this feature will solve?

I've deployed MongoDB using bitnami charts in Azure AKS 1.22.11.

Scenario:

Currently, in AKS Cluster-A: I've deployed MongoDB using bitnami charts in Azure AKS 1.22.11
As MongoDB is having PVCs/Data. 

I am looking for an option to sync data/replicate MongoDB data to another AKS Cluster-B. Is it possible or is there any feasible way to achieve this?

### What is the feature you are proposing to solve the problem?

Cluster-to-Cluster Sync - Data Synchronization between K8s Cluster

Data Replication/Synchronization between two AKS Clusters. Like AKS Cluster-A to AKS Cluster-B.

**Comment by javsalgar** [comment]
Hi,

The chart itself does not have an automated way to do it. I would consult in the MongoDB forums what the best way to achieve cluster-to-cluster sync is.

**Comment by zohebs341** [comment]
@javsalgar Thank you Javier, it would be of great help. If we can achieve this. We can use this solution for DR as well as for multi clusters.
