### ISSUE TITLE
helm  solr cloud cluster 8.4.1 version    How do I pull it?

### ISSUE THREAD

**Issue by kingvip** [bitnami/charts#12434]
### Name and Version

 bitnami/solr

### What is the problem this feature will solve?

How to get helm solr version 8.4.1?

### What is the feature you are proposing to solve the problem?

There is no solr 8.4.1 in the helm history version

**Comment by rafariossaa** [comment]
Hi,
  Have you tried to set the `image.tag` parameter ?

**Comment by kingvip** [comment]
helm3.exe  install  solr-cluster  bitnami/solr --version=4.1.2

**Comment by kingvip** [comment]
Modify values.yaml

image:
  registry: docker.io
  repository: bitnami/solr
  tag: 8.4.1

**Comment by kingvip** [comment]
PS C:\Users\sup.n.ji\solr-cluster> helm3.exe  -n solr install  solr-cluster  bitnami/solr --version=4.1.2   -f values.yaml
NAME: solr-cluster
LAST DEPLOYED: Thu Sep 15 08:43:54 2022
NAMESPACE: solr
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: solr
CHART VERSION: 4.1.2
APP VERSION: 8.11.1

** Please be patient while the chart is being deployed **

Solr can be accessed via port 8983 on the following DNS name from within your cluster:

    solr-cluster.rome.svc.cluster.local:8983

To connect to your Solr cluster from outside the cluster, perform the following steps:

1. Create a port-forward to the Solr client port:

    kubectl port-forward --namespace rome svc/solr-cluster 8983:8983 &
    echo "Solr URL: 127.0.0.1:8983"

2. Access the Solr cluster using using the obtained URL.
WARNING: Rolling tag detected (bitnami/solr:8.4.1), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/


Back-off restarting failed container

**Comment by kingvip** [comment]
PS C:\Users\sup.n.ji\solr-cluster> helm3.exe  -n solr install  solr-cluster  bitnami/solr --version=4.1.2   -f values.yaml
NAME: solr-cluster
LAST DEPLOYED: Thu Sep 15 08:43:54 2022
NAMESPACE: solr
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: solr
CHART VERSION: 4.1.2
APP VERSION: 8.11.1

** Please be patient while the chart is being deployed **

Solr can be accessed via port 8983 on the following DNS name from within your cluster:

    solr-cluster.rome.svc.cluster.local:8983

To connect to your Solr cluster from outside the cluster, perform the following steps:

1. Create a port-forward to the Solr client port:

    kubectl port-forward --namespace rome svc/solr-cluster 8983:8983 &
    echo "Solr URL: 127.0.0.1:8983"

2. Access the Solr cluster using using the obtained URL.
WARNING: Rolling tag detected (bitnami/solr:8.4.1), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/


Back-off restarting failed container

**Comment by kingvip** [comment]
@rafariossaa

**Comment by kingvip** [comment]
PS C:\Users\sup.n.ji\solr-cluster> helm3.exe -n solr install solr-cluster bitnami/solr --version=4.1.2 -f values.yaml
NAME: solr-cluster
LAST DEPLOYED: Thu Sep 15 08:43:54 2022
NAMESPACE: solr
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: solr
CHART VERSION: 4.1.2
APP VERSION: 8.11.1

** Please be patient while the chart is being deployed **

Solr can be accessed via port 8983 on the following DNS name from within your cluster:

solr-cluster.rome.svc.cluster.local:8983
To connect to your Solr cluster from outside the cluster, perform the following steps:

Create a port-forward to the Solr client port:

kubectl port-forward --namespace solr svc/solr-cluster 8983:8983 &
echo "Solr URL: 127.0.0.1:8983"

Access the Solr cluster using using the obtained URL.
WARNING: Rolling tag detected (bitnami/solr:8.4.1), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/

Back-off restarting failed container

**Comment by kingvip** [comment]
helm3  -n solr install solr-cluster bitnami/solr --version=4.1.2 -f values.yaml
NAME: solr-cluster
LAST DEPLOYED: Thu Sep 15 08:43:54 2022
NAMESPACE: solr
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: solr
CHART VERSION: 4.1.2
APP VERSION: 8.11.1

** Please be patient while the chart is being deployed **

Solr can be accessed via port 8983 on the following DNS name from within your cluster:

solr-cluster.rome.svc.cluster.local:8983
To connect to your Solr cluster from outside the cluster, perform the following steps:

Create a port-forward to the Solr client port:

kubectl port-forward --namespace solr svc/solr-cluster 8983:8983 &
echo "Solr URL: 127.0.0.1:8983"

Access the Solr cluster using using the obtained URL.
WARNING: Rolling tag detected (bitnami/solr:8.4.1), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/

Back-off restarting failed container

**Comment by rafariossaa** [comment]
Could you try this ?
```
$ helm install solr-cluster bitnami/solr --set image.tag=8.4.1

$ kubectl describe pod solr-cluster-0 | grep Image
    Image:         docker.io/bitnami/solr:8.4.1
```

**Comment by kingvip** [comment]
Can I download the mirror down to the modulation file?    helm pull   bitnami/solr --set image.tag=8.4.1  --untar

**Comment by rafariossaa** [comment]
Hi,
  You could do:
```
$ helm pull bitnami/solr --untar
$ cd solr/
$ helm install mysolr -f values.yaml --set image.tag=8.4.1 .
```

**Comment by kingvip** [comment]
Thanks, please ask how to fix on helm solr    Dlog4j2.formatMsgNoLookups=true  or   Replacement  log4j  2.17.1 file

**Comment by kingvip** [comment]
statefulset.yaml
          env:
            - name: "SOLR_OPTS"
              value: "-Dlog4j2.formatMsgNoLookups=true"

**Comment by kingvip** [comment]
Is it possible to do this

**Comment by rafariossaa** [comment]
Please, take a look to the [parameters section](https://github.com/bitnami/charts/tree/master/bitnami/solr#user-content-parameters) in the readme. 
For this I think you could use `extraEnvVars`.

**Comment by kingvip** [comment]
thank you

**Comment by rafariossaa** [comment]
I am closing this issue now.
Please, feel free to reopen it if needed.
