### ISSUE TITLE
[bitnami/mongodb] can't upgrade from 11.2.0 to 12.1.3

### ISSUE THREAD

**Issue by bitfisher** [bitnami/charts#12440]
### Name and Version

bitnami/mongodb 12.1.3

### What steps will reproduce the bug?

1. install bitnami/mongodb 11.2.0 in standalone
2. upgrade to bitnami/mongodb 12.1.3 in standalone

### Are you using any custom parameters or values?

--set updateStrategy.type=Recreate

### What is the expected behavior?

seamless upgrade

### What do you see instead?

`{"t":{"$date":"2022-09-15T12:30:23.432+00:00"},"s":"F", "c":"CONTROL", "id":20573, "ctx":"initandlisten","msg":"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"4.2\" }. See https://docs.mongodb.com/master/release-notes/4.4-compatibility/#feature-compatibility. :: caused by :: Invalid value for featureCompatibilityVersiondocument in admin.system.version, found 4.2, expected '4.4' or '4.9' or '5.0. See https://docs.mongodb.com/master/release-notes/4.4-compatibility/#feature-compatibility.). If the current featureCompatibilityVersion is below 4.4, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/4.4/#upgrade-procedures."}}`

### Additional information

previously upgraded from latest version of https://github.com/helm/charts/tree/master/stable/mongodb to bitnami/mongodb 11.2.0

**Comment by marcosbc** [comment]
Hi @bitfisher, you can see the upgrade notes for 12.0.0 [here](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#to-1200).

As for your issue, I'm afraid that in this case there is a major version change in the MongoDB version in your cluster, so it is likely to find compatibility issues like the ones you are mentioning.

Instead of upgrading, we would recommend to migrate the data to the new version. Also, please note that this is something that will affect any user's MongoDB installation.

**Comment by bitfisher** [comment]
Hi @marcosbc !

I read the upgrade notes but unfortunately there was no hint regarding compatibilityVersion of MongoDB.

Maybe some hint about this precondition or some sort of pre-install hook would be helpfull.

I mitigated this by adding
```yaml
initdbScripts:
  setFeatureCompatibilityVersion.js: |
    db.adminCommand({ setFeatureCompatibilityVersion: "4.4" });
```
to values.yaml of previous release and now update worked!

**Comment by marcosbc** [comment]
Great to hear @bitfisher! If you think it makes sense to add to the upgrade notes, feel free to send a PR, we'd be happy to help with the code review.
