### ISSUE TITLE
[bitnami/kubernetes-event-exporter] can't fetch new release image

### ISSUE THREAD

**Issue by lusson-luo** [bitnami/charts#12454]
### Name and Version

bitnami/kubernetes-event-exporter:lastest

### What is the problem this feature will solve?

I want to use the latest ARM64 image

the diff between official and bitnami
1. Kubernetes-event-exporter is an official version of 1.0.0. The latest version of Bitnami is 0.11.0-Debian-11-R33, which is a lot less than the exporter.
<img width="997" alt="image" src="https://user-images.githubusercontent.com/19859400/190604140-be247ee5-af66-40b0-b322-43078c2c2f64.png">
2. The official image supports AMD64 and ARM64, while Bitnami only supports AMD64
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/19859400/190604211-df1e01a5-a7b6-4a36-be32-ced31eb354d3.png">
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/19859400/190604288-745a66f4-d821-4dc6-b7d8-65ff74157671.png">

### What is the feature you are proposing to solve the problem?

Fix the official pull address of the component
Kubernetes-event-exporter official src change https://github.com/opsgenie/kubernetes-event-exporter to https://github.com/resmoio/kubernetes-event-exporter

**Comment by fmulero** [comment]
Hi, we have created [this issue](https://github.com/bitnami/charts/issues/7305) that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

About the updating the upstream project, we have created an internal task to address it. I'll keep this task on-hold to avoid the stale-bot closes it

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by lusson-luo** [comment]
🎉 🎉
