### ISSUE TITLE
[bitnami/odoo] no location for extra addons and config file

### ISSUE THREAD

**Issue by mah007** [bitnami/charts#12470]
### Name and Version

 bitnami/odoo:15

### What steps will reproduce the bug?

kubernates
where i can add the extra addons ?

### What do you see instead?

where i can add the extra addons ?

**Comment by fmulero** [comment]
Hi @mah007

You can use an `initContainer` to download the addons in an `volume` and share them with the main container. [Here](https://stackoverflow.com/questions/69405454/bitnami-odoo-addons-over-init-container-not-work) you've got a similar case in stackoverflow.

Please keep in mind that this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.
