### ISSUE TITLE
bitnami/external-dns -> stable/external-dns

### ISSUE THREAD

**Issue by MPV** [bitnami/charts#1247]
**Which chart**:

external-dns

**Description**

What's the view on merging/upstreaming `bitnami/external-dns` with `stable/external-dns`?

**Steps to reproduce the issue:**

1. Find that I am missing features in the `stable/external-dns` chart. 
   _(such as Prometheus metrics for ExternalDNS)_
2. Find that [there aren't any outstanding issues/PRs for adding metrics to the chart](https://github.com/helm/charts/issues?utf8=%E2%9C%93&q=%22external-dns%22+is%3Aopen+).
3. Find that [there isn't any `OWNERS` (file) defined for `stable/external-dns`](https://github.com/helm/charts/tree/master/stable/external-dns).
4. Find that [they're looking for maintainers on the `stable/external-dns` chart](https://github.com/helm/charts/issues/13869).
5. Find this version of the chart that contains `external-dns`, with at least a few improvements over `stable/external-dns`.

**Comment by tompizmor** [comment]
Hello @MPV,

Thanks for your interest in the bitnami/external-dns chart. After reading all the points you expose here, I think it makes sense trying to adopt the official external-dns chart. That way, the community can benefit that Bitnami is maintaining the chart.

We will work on creating an issue/PR in the official helm chart repository to hear the opinion from other users.

**Comment by juan131** [comment]
I think we can close this issue since we already moved the chart and it's available under `stable/external-dns` now!

Feel free to reopen it!
