### ISSUE TITLE
[bitnami/ghost] starting ghost with enabled https, https passthrough, results in `eadr in use` error

### ISSUE THREAD

**Issue by wibed** [bitnami/charts#12474]
previous issue resorting to tls termination
and then adapting correct configuration worked out.
enabled by this pr https://github.com/bitnami/charts/pull/11852
#10912

continuation on https passthrough

```
Note: I think the problem here is a misconfiguraion in the container or the deployment, because we are enabling HTTPS in the container to do the https redirects but we are not setting any certificate in the container, so we have an inconsistence there
```

i reopened your request on a different issue.
there is no misconfiguration on bitnamis side, afaik but more on the container image itself. 
trying to bootstrap ghost on https results in a
`eaddr in use error`

more information can be retrieved from the the link at the top

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
