### ISSUE TITLE
[bitnami/cassandra] dbUser.user not used, always uses "cassandra"

### ISSUE THREAD

**Issue by pselden** [bitnami/charts#1248]
**Which chart**:

cassandra, 2.3.8

**Description**

**Steps to reproduce the issue:**

`dbUser.user` is not used in the chart, always uses `cassandra`

1. Install Chart with different username/password
```
helm install --name my-release \                                           
  --set dbUser.user=admin,dbUser.password=password\
    bitnami/cassandra
```
2. Try to connect to service

```
kubectl port-forward --namespace default svc/my-release-cassandra 9042:9042 &
cqlsh -u admin -p password 127.0.0.1 9042
```

**Describe the results you received:**

```
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',)})
```

Now try with cassandra user
```
cqlsh -u cassandra -p password 127.0.0.1 9042
Connected to cassandra at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.4 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> 
```

It works

**Describe the results you expected:**

Should connect using admin/password, and not with cassandra/password

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. I created a PR that covers your use case.

**Comment by carrodher** [comment]
It seems this issue was addressed in this PR (https://github.com/bitnami/charts/pull/1249), please feel free to reopen it if needed, in the meantime, I will close it as resolved.

Thanks for reporting it!

**Comment by madhupnvl** [comment]
Hi Team,

I'm facing issue to connect to CQLSH. 
once the charts up, 

> kubectl get pods --namespace $NAMESPACE

> kubectl exec -it $(ABOVE CASSNADRA POD NAME) bash --namespace $NAMESPACE

then 

> cqlsh -u cassandra -p cassandra 

I'm unable to connect to cqlsh, here is the error.
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"',)})

Here is the yaml changes
> dbUser:
>  > user: cassandra
>   forcePassword: false
>   password: cassandra

After i tried with 
>kubectl run --namespace derm derm-cassandra-client --rm --tty -i --restart="Never" --labels="cassandra-client=true"  --image docker.io/bitnami/cassandra:3.11.5-debian-9-r57 -- bash

But no luck.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce it

```
(reverse-i-search)`helm': helm install bitnami/cassandra --set dbUser.password=cassandra --set dbUser.user=myuser --generate-name
```

```
 130 ❯ helm ls
NAME            	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
chart-1579523103	default  	1       	2020-01-20 13:25:04.443618 +0100 CET	deployed	cassandra-4.1.14	3.11.5
```

```
I have no name!@chart-1579523103-cassandra-0:/$ cqlsh -u myuser -p cassandra
Connected to cassandra at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.5 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
myuser@cqlsh>
```

Just like I mentioned in https://github.com/bitnami/charts/issues/1838, it seems you are using an older version of the chart. Could you please double check?

**Comment by yury-kozlov** [comment]
I got the same issue after deleting the helm chart and then installing it with a new password. This is because password is saved in persistent volume claim, which is not deleted by helm. 
So in order to reset the password, you might want to delete the claim (but be careful as it deletes the data!)

**Comment by javsalgar** [comment]
@yury-kozlov currently the passwords are stored in persistence (because it is normally part of the data), so you need to pass the password when upgrading as well.
