### ISSUE TITLE
Bitnami/Odoo + Enterprise

### ISSUE THREAD

**Issue by Mosscuat** [bitnami/charts#1250]
Hello everyone!

I'm new in the kubernetes world, so I'm having a lot of doubts, I hope you could help me!

I'M using the command helm install Odoo stable/Odoo to implement the Bitnami Odoo image in my cluster. With that image everything goes well, but the problem is that I want to add the Enterprise apps into the image and I already tried a lot of things without success.

Do you have any option?

Thanks!

**Comment by andresbono** [comment]
Hi @Mosscuat, can you tell us which app are you trying to install? Can you describe the steps that you are following?

**Comment by Mosscuat** [comment]
Hi! Andres!

I'm trying to install stable/odoo (Bitnami's Odoo Image).

Literally the process that I'm following is executing the command: helm install odoo stable/odoo.

This deployment has the addons path in the route /opt/bitnami/odoo/odoo/addons and I need to add the path /opt/bitnami/odoo/odoo/enterpise to that deployment. Also, I need to modify the odoo.conf to give it the new files path info.

Is there anyway to make it? Or maybe anyway to modify that image and have the same result: functional pods! 

I'll be pending for your answer and thank a lot for your support.

Regards

Samuel Olvera

**Comment by andresbono** [comment]
Thanks for the information, @Mosscuat.

What are those _Enterprise apps_ that you mention in your first message? Can you point us to a link of one of those apps/addons?

Is it possible that what you want to get it running is the Enterprise edition of Odoo? https://www.odoo.com/page/editions Note that we distribute the open source version only.

**Comment by Mosscuat** [comment]
Hello Andres!

Sorry for the delay! 

As you can see in the URL that you sent me, the Enterprise edition is just the access to more apps.

You need to download all of them (if you have the enterprise access) and load them in some path of the Odoo's image.

Thats why I'm asking you if you have any recommendation of how I can do it without sacrifice the image function.

I already tried using the Dockerfile, modifying and adding this apps and the new configuration in the odoo-server.conf, but when I used the KUBECTL RUN, it didn't work.

I hope you can help me!

Regards

**Comment by miguelaeh** [comment]
Hi @Mosscuat ,
You can try to add your own volume on the chart template. To mount the files, if they are single files you can do it using a configMap with the file name as the key, and then mount the volume from the configMap. If they are a bundle of files you can try to create an initContainer and download those files into the volume directory.
