### ISSUE TITLE
Kafka chart

### ISSUE THREAD

**Issue by justare** [bitnami/charts#1251]
When using extraEnvVars, this fails:
extraEnvVars:
  - name: KAFKA_CFG_MAX_POLL_RECORDS
    value: 50

But this works....:
extraEnvVars:
  - name: KAFKA_CFG_MAX_POLL_RECORDS
    value: "50"

Is this a bug "by design" values.yml says to use without "

Best Regards
Jakob

**Comment by alemorcuq** [comment]
Hi, @justare.

You should quote the value. Could you point me to where it is said to use it without quotes so we can fix it?

Regards,
Alejandro

**Comment by justare** [comment]
https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml

## All the parameters from the configuration file can be overwritten by using environment variables with this format: KAFKA_CFG_{KEY}
##
# extraEnvVars:
#   - name: KAFKA_CFG_BACKGROUND_THREADS
#     value: 10

**Comment by alemorcuq** [comment]
Thank you, @justare, it's fixed now.

Regards,
Alejandro
