### ISSUE TITLE
Kafka charts

### ISSUE THREAD

**Issue by xytnba** [bitnami/charts#1255]
How did it generate in kafka>requirements.lock? what do I need to do to have these? It's the 'digest' and the 'generated'.
![weixin_20190625165018](https://user-images.githubusercontent.com/49108263/60084400-081da980-976a-11e9-84b2-7df900d167b4.png)

**Comment by carrodher** [comment]
Creating the initial _requirements.yaml_ file and after run `helm install`, Helm creates the requirements.lock file as it builds the dependency tree. On the next `helm install`, Helm will ensure that it uses the same versions present in the _requirements.lock_ file.
Updating the _requirements.yaml_ file and running `helm install` (or `helm upgrade`), Helm will notice the changes and update the _requirements.lock_ file to reflect them.

In the same way, you can update the dependencies statically by running
```
rm -rf requirements.lock
helm dependency update
```
above commands generate a new _requirements.lock_ (if there are no changes in the dependency version only the date is updated): 
```diff
   repository: https://charts.bitnami.com/bitnami
   version: 2.2.4
 digest: sha256:4b7d7df2e607cd3ddafd1d5eec4377cc23b96ea25a7e5a7dafea76acc2590579
-generated: 2019-06-10T12:37:29.032667048Z
+generated: "2019-06-25T09:35:52.626619056Z"
```

You can find more information about this topic in the official documentation: https://helm.sh/docs/developing_charts/#chart-dependencies

**Comment by xytnba** [comment]
Thanks a lot, I searched it in google but no useful information about it. I get  it ,thanks
