### ISSUE TITLE
Adding stream support for Nginx chart

### ISSUE THREAD

**Issue by gokhansengun** [bitnami/charts#1257]
Nginx chart supports custom `serverBlock` to be provided like below. This block is added inside `nginx` `http` config block.

```
serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location / {
      return 200 "hello!";
    }
  }
```

Would it make sense to add `streamBlock` like `serverBlock` and put it inside `nginx` `stream` config block.

If that sounds OK, I can send a PR adding the functionality.

**Comment by miguelaeh** [comment]
Hi @gokhansengun ,
Feel free to send a PR with the feature, 
thank you very much.

**Comment by gokhansengun** [comment]
Thanks, closing this for now then.

**Comment by BonySmoke** [comment]
@gokhansengun Hello! Do I understand correctly that you stopped working on the `streamBlock` feature?
Were there some blockers that made it hard to implement?
It's a very useful feature:)
