### ISSUE TITLE
[bitnami/redis] Modules such as ReJson for bitnami image

### ISSUE THREAD

**Issue by xtianus79** [bitnami/charts#12572]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

Under the RSAL license from Redis states that usage of modules in an application is permitted. As long, as your not creating a DB to sell or a DB into cloud service using open source work to profit. I get that 100% and I agree with it. 

However, what I am not getting is why we can't have a bitnami image with access to modules. 

[This post here,](https://github.com/bitnami/bitnami-docker-redis/issues/92) when read, has a an odd tone to it which suggests the obviousness of what is being asked for but no real earnest attempt at providing what is being asked for in an official bitnami image. 

So the question will you support Bitnami images for redis / redis-cluster that has access to modules? 

### What is the feature you are proposing to solve the problem?

Getting the full usage of the Redis platform

### What alternatives have you considered?

This thread here is not a working solution but rather various hacks.

**Comment by fmulero** [comment]
Hi @xtianus79, thanks for opening this issue

We tried to implement [this feature](https://github.com/bitnami/bitnami-docker-redis/pull/134) but our resources are limited.

This is a recurrent topic (here some examples: https://github.com/bitnami/bitnami-docker-redis/issues/124, https://github.com/bitnami/bitnami-docker-redis/issues/92, #2917),  we will try to prioritize it, but we can't give you any ETA. Would you like to contribute and continue https://github.com/bitnami/bitnami-docker-redis/pull/134? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by xtianus79** [comment]
hi @fmulero it was suggested the best (most feature version) of Redis image is called Redis stack. 

redis/redis-stack:7.0.2-RC2

I'd love to contribute. Let me read it and I will ask questions. 

What's interesting is that Redis themselves only have a Redis Enterprise operator. Do you have to purchase that? It seems that enterprise is only a commercial license hence why I think everyone uses this Bitnami controller.

**Comment by xtianus79** [comment]
@fmulero that git is closed. Would it be useful to utilize the core image for Bitnami as that Stack image?

**Comment by fmulero** [comment]
You can find the code of our [redis containter image](https://github.com/bitnami/containers/tree/main/bitnami/redis)  in the  [bitnami/containers](https://github.com/bitnami/containers) repository.

In our charts we has to use our images, if you want to use the redis-stack one, you can do it setting the image in your values, but we can not accept any contribution about that.

Please focus on your need. If I am not wrong, you are requesting a feature to load modules during initialisation.

**Comment by xtianus79** [comment]
@fmulero Got you. to answer your question yes load them during initialization or just have them there and I can edit the conf afterward to control loading the module. Either or both is fine. Does it matter if the modules are from an image that wasn't bulls eye? I have heard that is an issue.

**Comment by fmulero** [comment]
I am not sure what you mean here:
> Does it matter if the modules are from an image that wasn't bulls eye?
If you want to compile the modules I'd say yes, is better to use the same OS version as your destination.

**Comment by Preen** [comment]
Is this solved?

**Comment by xtianus79** [comment]
@Preen No, and it is something I really want. I will revisit in a day or so.

**Comment by xtianus79** [comment]
@fmulero Hi can we reopen this or should I start a new thread? I'd like to try and tackle this now.  I think below is a way to add the module both bitnami and redis. However, I am going in an looking at the container repo you gave and thinking this can be done there. My question should I fork and then use and then I can submit a pull request if everything goes well? 

```
ARG redisVersion

FROM docker.io/redislabs/redisearch:latest as redisearch
FROM bitnami/redis:$redisVersion

COPY --from=redisearch /usr/lib/redis/modules/redisearch.so /usr/lib/redis/modules/redisearch.so

CMD ["/run.sh", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
```

**Comment by xtianus79** [comment]
hi @carrodher  How is this solved?
