### ISSUE TITLE
CASSANDRA_SEEDS always have cluster.local

### ISSUE THREAD

**Issue by shaders** [bitnami/charts#1259]
CASSANDRA_SEEDS value always have **cluster.local** hardcoded. Could you please move this into the vars?

https://github.com/bitnami/charts/blob/master/bitnami/cassandra/

https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/statefulset.yaml

```
 - name: CASSANDRA_SEEDS
          {{- $global := . }}
          {{- $replicas := .Values.cluster.seedCount | int }}
          value: "{{- range $i, $e := until $replicas }}{{ template "cassandra.fullname" $global }}-{{ $i }}.{{ template "cassandra.fullname" $global }}-headless.{{ $global.Release.Namespace }}.svc.cluster.local{{- if (lt ( add1 $i ) $replicas ) }},{{- end }}{{- end }}"
```

```
WARN  [main] 2019-06-27 14:11:48,883 SimpleSeedProvider.java:60 - Seed provider couldn't lookup host cassandra-0.cassandra-headless.default.svc.cluster.local
ERROR [main] 2019-06-27 14:11:48,885 CassandraDaemon.java:749 - Exception encountered during startup: The seed provider lists no seeds.
```

**Comment by miguelaeh** [comment]
Hi @shaders ,
You are right, this is an issue we found on some of our Helm Charts, thank you for reporting.

**Comment by carrodher** [comment]
> Hi @shaders ,
> You are right, this is an issue we found on some of our Helm Charts, thank you for reporting.

What other charts? We should fix all of them if necessary

**Comment by miguelaeh** [comment]
The list is:
- zookeeper
- memcached
- kafka
- consul
- minio
- elasticsearch
- mysql
