### ISSUE TITLE
[bitnami/discourse] Issues regarding Backup and Restore

### ISSUE THREAD

**Issue by ByteInSpace** [bitnami/charts#12592]
### Name and Version

bitnami/discourse

### What steps will reproduce the bug?

We currently deploy Discourse Kubernetes Bitnami image in the 8.1.4 version on our Kubernetes cluster and encounter some issues relating to Backup / Restore procedure.

### 1. Development cluster
Here we have a regular installation with Postgres and Redis embedded. Immediately after clean installation I start backup and receive this error:
```
[2022-09-20 07:56:30] 'user' has started the backup!
[2022-09-20 07:56:30] Marking backup as running...
[2022-09-20 07:56:30] Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-09-20-075629' exists...
[2022-09-20 07:56:30] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2022-09-20 07:56:30] Updating metadata...
[2022-09-20 07:56:30] Dumping the public schema of the database...
[2022-09-20 07:56:30] pg_dump: error: server version: 14.5; pg_dump version: 13.8
[2022-09-20 07:56:30] EXCEPTION: pg_dump failed
[2022-09-20 07:56:30] /opt/bitnami/discourse/lib/backup_restore/backuper.rb:152:in `dump_public_schema'
/opt/bitnami/discourse/lib/backup_restore/backuper.rb:36:in `run'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:9:in `backup'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:34:in `block in <main>'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `fork'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `<main>'
[2022-09-20 07:56:30] Deleting old backups...
[2022-09-20 07:56:30] Cleaning stuff up...
[2022-09-20 07:56:30] Removing '.tar' leftovers...
[2022-09-20 07:56:30] Marking backup as finished...
[2022-09-20 07:56:30] Refreshing disk stats...
[2022-09-20 07:56:30] Notifying 'user' of the end of the backup...
[2022-09-20 07:56:35] Finished!
```

### 2. Test cluster
On this we use a Managed PostgreSQL with a different port (22334 instead of default 54327). When I start backup there is:
```
[2022-09-20 08:40:32] 'user' has started the backup!
[2022-09-20 08:40:32] Marking backup as running...
[2022-09-20 08:40:32] Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-09-20-084031' exists...
[2022-09-20 08:40:32] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2022-09-20 08:40:32] Updating metadata...
[2022-09-20 08:40:32] Dumping the public schema of the database...
[2022-09-20 08:42:42] pg_dump: error: connection to database "alpha-test" failed: could not connect to server: Connection timed out
[2022-09-20 08:42:42] EXCEPTION: pg_dump failed
[2022-09-20 08:42:42] /opt/bitnami/discourse/lib/backup_restore/backuper.rb:152:in `dump_public_schema'
/opt/bitnami/discourse/lib/backup_restore/backuper.rb:36:in `run'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:9:in `backup'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:34:in `block in <main>'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `fork'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `<main>'
[2022-09-20 08:42:42] Deleting old backups...
[2022-09-20 08:42:42] Cleaning stuff up...
[2022-09-20 08:42:42] Removing '.tar' leftovers...
[2022-09-20 08:42:42] Marking backup as finished...
[2022-09-20 08:42:42] Refreshing disk stats...
[2022-09-20 08:42:42] Notifying 'user' of the end of the backup...
[2022-09-20 08:42:48] Finished!
```

In the sidekiq log there is:

```
[STARTED]
'system' has started the backup!
Marking backup as running...
Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-09-20-033948' exists...
Making sure '/opt/bitnami/discourse/public/backups/default' exists...
Updating metadata...
Dumping the public schema of the database...
pg_dump: error: connection to database "alpha-test" failed: could not connect to server: Connection timed out
Is the server running on host "$IPADRESS" and accepting
**TCP/IP connections on port 5432?**
EXCEPTION: pg_dump failed
```

Discourse application itself can connect to Postgre and is running fine.

Is it possible that the backup routine is not using the defined PostgreSQL port but still the default 5432 regardless of what is defined?

### Development cluster:

```yaml
postgresql:
  serviceAccount:
    create: true
  rbac:
    create: true
```

### Test cluster*
```yaml
postgresql:
  enabled: false

externalDatabase:
  host: "{{POSTGRES_DB_HOST}}"
  port: "{{POSTGRES_DB_PORT}}"
  user: "{{POSTGRES_DB_USER}}"
  password: "{{POSTGRES_DB_PASSWORD}}"
  database: "{{POSTGRES_DB_DATABASE}}"
  create: true
  postgresUser: "{{POSTGRES_DB_USER}}"
  postgresPassword: "{{POSTGRES_DB_PASSWORD}}"
```

### What is the expected behavior?

Create backup without any issues

### What do you see instead?

Errors as described above

**Comment by ByteInSpace** [comment]
Additional comment: 
I can confirm that pg_dump in Discourse always uses default port only, regardless of what is configured externalDatabase.port. There is in chart no way of defining a different port used for pg_dump. 
I found some posts that there is a separate parameter DISCOURSE_DB_BACKUP_PORT (See https://github.com/bitnami/charts/issues/4456) but it seems that it is not implemented in Bitnami Kubernetes Chart?

**Comment by CeliaGMqrz** [comment]
Hi @ByteInSpace,

Sorry for the delay. Could you try what this [issue](https://github.com/bitnami/charts/issues/4456) says?
Please add this to your `extraEnvVars` in `values.yaml`.
```
extraEnvVars:
    - name: DISCOURSE_DB_BACKUP_PORT
      value: "{{POSTGRES_DB_PORT}}"
```
If the error persists let us know.
Thanks for your feedback.

**Comment by ByteInSpace** [comment]
Could you please re-open this ticket? It is not fixed yet, sorry.
I installed the current chart version  9.0.2. PostgreSQL run on different machine on port 32010. Configuration in yaml:

externalDatabase:
  host: "192.168.178.62"
  port: "32010"
  user: "discourse"
  password: "******"
  database: "discourse"
  create: true
  postgresUser: "discourse"
  postgresPassword: "******"

Works fine for Discourse itself. When starting backup, I receive the error 

**pg_dump: error: connection to server at "192.168.178.62", port 5432 failed: Connection refused**

This shows that pg_dump still connects to 5432 instead of 32010. As requested by you, I added the extraVars, for discourse, for sidekiq, and also for itself. After some Codereview from discourse (sorry, I am not very much into rails) I also added db_port.

discourse:
  extraEnvVars:
    - name: DISCOURSE_DB_BACKUP_PORT
      value: "32010"  
    - name: DISCOURSE_DB_BACKUP_HOST
      value: "192.168.178.62" 
    - name: DISCOURSE_DB_PORT
      value: "32010"
      
sidekiq:
  extraEnvVars:
    - name: DISCOURSE_DB_BACKUP_PORT
      value: "32010"  
    - name: DISCOURSE_DB_BACKUP_HOST
      value: "192.168.178.62"
    - name: DISCOURSE_DB_PORT
      value: "32010"
      
extraEnvVars:
  - name: DISCOURSE_DB_BACKUP_PORT
    value: "32010"  
  - name: DISCOURSE_DB_BACKUP_HOST
    value: "192.168.178.62"
  - name: DISCOURSE_DB_PORT
    value: "32010"

Complete deployment re-installed. Still:

[2022-11-24 09:21:50] 'user' has started the backup!
[2022-11-24 09:21:50] Marking backup as running...
[2022-11-24 09:21:50] Making sure '/opt/bitnami/discourse/tmp/backups/default/2022-11-24-092149' exists...
[2022-11-24 09:21:50] Making sure '/opt/bitnami/discourse/public/backups/default' exists...
[2022-11-24 09:21:50] Updating metadata...
[2022-11-24 09:21:50] Dumping the public schema of the database...
**[2022-11-24 09:21:50] pg_dump: error: connection to server at "192.168.178.62", port 5432 failed: Connection refused**
[2022-11-24 09:21:50] EXCEPTION: pg_dump failed
[2022-11-24 09:21:50] /opt/bitnami/discourse/lib/backup_restore/backuper.rb:152:in `dump_public_schema'
/opt/bitnami/discourse/lib/backup_restore/backuper.rb:36:in `run'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:9:in `backup'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:34:in `block in <main>'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `fork'
/opt/bitnami/discourse/script/spawn_backup_restore.rb:4:in `<main>'
[2022-11-24 09:21:50] Deleting old backups...
[2022-11-24 09:21:50] Cleaning stuff up...
[2022-11-24 09:21:50] Removing '.tar' leftovers...
[2022-11-24 09:21:50] Marking backup as finished...
[2022-11-24 09:21:50] Refreshing disk stats...
[2022-11-24 09:21:50] Notifying 'user' of the end of the backup...
[2022-11-24 09:21:55] Finished!

**Comment by ncreuschling** [comment]
I can confirm this issue aswell:

In `discourse-env.sh`, `discourse_env_vars` (see [GitHub](https://github.com/bitnami/containers/blob/main/bitnami/discourse/2/debian-11/rootfs/opt/bitnami/scripts/discourse-env.sh)) seems to miss 

```
DISCOURSE_DB_BACKUP_PORT
DISCOURSE_DB_BACKUP_HOST
```

Consequently both variable are not available for Discourse and Sidekiq processes.

**Comment by ncreuschling** [comment]
Please consider my PR at #bitnami/containers#14838.

**Comment by CeliaGMqrz** [comment]
Hi @ByteInSpace, sorry for the delay. We reopened the case and will investigate it further. We will consider your PR @ncreuschling, thanks.

**Comment by ByteInSpace** [comment]
I would also add one point: with the Chart 9.0.2 you again deliver a pg_client version 14.6 which do not work with the corresponding PostgreSQL version 15.1. It was the same also with 8.1.4. Because of this, backup and restore also do not work if one used delivered PostgreSQL installation instead of a external one.
Please kindly make sure to deliver pg_client at least in same version as of the PostgreSQL backend

**Comment by ncreuschling** [comment]
@ByteInSpace Other ran into this pg_client issue as well: https://github.com/bitnami/containers/issues/14632

**Comment by ByteInSpace** [comment]
From my point of view this is a major bug rendering usage of Bitnami Discourse Kubernetes images in production environment virtually impossible, as you cannot create and restore backup using pg_client, both in own provided database (version incompatibilities between pg_client and PostgreSQL) and in case of external database, which in large production environment often listens on another point then default.

**Comment by carrodher** [comment]
We just created an internal task to fix the issue and release a new [bitnami/discourse container image](https://github.com/bitnami/containers/tree/main/bitnami/discourse) bundling postgresql-client 15.x.x in order to match with the PostgreSQL version used by the bitnami/discourse Helm chart.

**Comment by carrodher** [comment]
Hi, we just released a new bitnami/discourse container image bundling postgresql-client 15.1.0, see https://github.com/bitnami/containers/pull/15327. This image was released as `bitnami/discourse:2.8.11-debian-11-r4`.

In the same way, at https://github.com/bitnami/charts/pull/13740, a new version of the Helm chart (`9.0.3`) was released including the new container image:
```yaml
image:
  registry: docker.io
  repository: bitnami/discourse
  tag: 2.8.11-debian-11-r4
```

Please let us know if that solve your issue.

**Comment by CeliaGMqrz** [comment]
Hi @ByteInSpace 

Thanks for your patience, discourse chart has been updated with the changes to configure `db_backup`

```
    DISCOURSE_DB_BACKUP_HOST
    DISCOURSE_DB_BACKUP_PORT
```
This is the latest with this change
```
image:
  registry: docker.io
  repository: bitnami/discourse
  tag: 2.8.11-debian-11-r5
```

**Comment by ByteInSpace** [comment]
With the new version I was able to create a dump from our server running at 32010. Issue is therefore solved and can be closed

Thank you very much for your quick support!

**Comment by CeliaGMqrz** [comment]
Thanks for your feedback!
