### ISSUE TITLE
etcd won't start with rbac disabled

### ISSUE THREAD

**Issue by polivbr** [bitnami/charts#1260]
**Which chart**:

etcd - 3.1.0

**Description**

Etcd won't start if auth.rbac.enabled is set to false.

**Steps to reproduce the issue:**

1. Set auth.rbac.enabled=false when installing helm release

**Describe the results you received:**

Fails with the error:

`/scripts/setup.sh: line 25: ETCD_ROOT_PASSWORD: unbound variable`

**Describe the results you expected:**

Etcd starts without issue

**Additional information you deem important (e.g. issue happens only occasionally):**

This is due to the fact that ETCD_ROOT_PASSWORD doesn't get set in the StatefulSet definition, but the setup.sh script defined in the ConfigMap enables the "nounset" option.

**Comment by juan131** [comment]
Hi @polivbr 

Thanks so much for reporting it! I just created a PR to address it!

**Comment by polivbr** [comment]
Impressively fast turnaround! Thanks!
