### ISSUE TITLE
Allow setting loadBalancerClass on service configurations

### ISSUE THREAD

**Issue by oliver-ni** [bitnami/charts#12603]
### Name and Version

lots; example: bitnami/mongodb 13.1.5

### What is the problem this feature will solve?

If you run multiple LoadBalancer controller implementations in a single cluster, there is currently no way to configure services created by bitnami Helm charts to use specific implementations.

### What is the feature you are proposing to solve the problem?

The [`spec.loadBalancerClass`](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) lets you specify which implementation to use. I am proposing to add a field similar to `service.loadBalancerIPs` called `service.loadBalancerClass` that is forwarded into the service configuration.

**Comment by javsalgar** [comment]
Hi!

Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.

**Comment by javsalgar** [comment]
Hi! 

Thank you so much for the feature request! Would you like to submit a PR with the new feature?

**Comment by oliver-ni** [comment]
I can work on one, yes. However, I haven’t worked on any Helm charts before. Please let me know if there are any caveats I should watch out for with this feature

**Comment by javsalgar** [comment]
It is adding a non-breaking feature, so you should ensure that the values is only added to the YAML when set. Apart from that, I don't see many issues. Make sure you read the development guidelines in the repo. Thank you so much!

**Comment by oliver-ni** [comment]
This is not solved

**Comment by javsalgar** [comment]
Reopened as the PR is still open
