### ISSUE TITLE
Kafka with name "kafka" fails

### ISSUE THREAD

**Issue by megfigura** [bitnami/charts#1261]
**Which chart**:

kafka-3.0.11 2.3.0

**Description**

If I use the name "kafka", Kafka fails to start due to an error parsing the configuration.

**Steps to reproduce the issue:**

Using helm on minikube, I run the following command:
`helm install --name kafka bitnami/kafka`

I can see using "kubectl get pods" that 'kafka-0' is failing to start, so I check the logs:
```
[root@lobster1 ~]# kubectl logs kafka-0

Welcome to the Bitnami kafka container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Kafka setup **
WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing Kafka...
INFO  ==> No injected configuration files found, creating default config files
INFO  ==> ** Kafka setup finished! **

INFO  ==> ** Starting Kafka **
[2019-06-27 17:43:09,843] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2019-06-27 17:43:10,172] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value tcp://10.108.41.92:9092 for configuration port: Not a number of type INT
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:473)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:466)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1111)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
        at kafka.Kafka$.main(Kafka.scala:68)
        at kafka.Kafka.main(Kafka.scala)
```

If I give anything else besides "kafka" as the name, it works fine. The same behavior happens if I set the name in a different way, such as through fullnameOverride -- "kafka" fails, anything else succeeds.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks! :)

**Comment by tompizmor** [comment]
Hi @megfigura,

Thanks for reporting the issue. This is just a quick note to let you know that I was able to reproduce. 

The issue is that Kubernetes creates a KAFKA_PORT env var with `tcp://10.108.41.92:9092` as value when the service name is called `kafka`.
Later on, the Kafka docker image is consuming that KAFKA_PORT env var to configure the port. This is a bug recently introduced in the docker image as it should take the value from the KAFKA_PORT_NUMBER environment variable and ignore KAFKA_PORT.

We will work on fixing this and update the issue once a new release of kafka is available.

**Comment by tompizmor** [comment]
@megfigura The new kafka images and helm chart are available.

This is the [commit](https://github.com/bitnami/charts/commit/6b0b69ca163bc2738730056305674c38dcd29b16) with the chart update. Make sure you install helm version `3.0.12`

**Comment by megfigura** [comment]
Hi @tompizmor,

The new version is working great. Thank you for the speedy fix!
