### ISSUE TITLE
[bitnami/redis] serviceAccount can't be set for the redis-master or redis-replicas statefulsets

### ISSUE THREAD

**Issue by Dragane** [bitnami/charts#12629]
### Name and Version

bitnami/redis 7.0.4

### What steps will reproduce the bug?

I cannot set the serviceAccount for either master or replicas statefulset. It always just defaults to the name "redis". The statefulset never starts by using this serviceAccount as it lacks permisisons

It starts up normally if I manually edit both master and replicas statefulsets and add my correct serviceAccound.

I tried editing the values.yaml file and adding my serviceAccount there but it is just ignored. Defaults back to redis.
Same issue if i do the --set master.serviceAccount.name=myaccount

### Are you using any custom parameters or values?

 --set master.serviceAccount.name=myaccount
 --set replica.serviceAccount.name=myaccount

### What is the expected behavior?

By editing either values.yaml or using the --set I would expect to provide my own serviceAccount.

### What do you see instead?

The serviceAccount used keeps defaulting to "redis".

**Comment by fmulero** [comment]
Hi @Dragane 

To set your own `serviceAccount` you have to set `serviceAccount.create=false` to avoid the creation of the default one.  Could you give it a try?

**Comment by Dragane** [comment]
This has indeed helped. Thank you so much Fran!

For everyone who gets across the same issue, this is the command I used now

helm install redis --set serviceAccount.create=false,
master.serviceAccount.name=<myaccount>,replica.serviceAccount.name=<myaccount>,auth.username=admin,auth.password=admin,rbac.create=false,replicaCount=3
bitnami/redis -n <my-namespace>
