### ISSUE TITLE
[bitnami/wordpress] Cannot use Recreate Deployment Strategy

### ISSUE THREAD

**Issue by mconnley** [bitnami/charts#12639]
### Name and Version

bitnami/wordpress 15.2.4

### What steps will reproduce the bug?

Set updateStrategy.type = Recreate and attempt to deploy.

### What is the expected behavior?

The release should deploy.

### What do you see instead?

`Error: INSTALLATION FAILED: Deployment.apps "wptest-wordpress" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy 'type' is 'Recreate'`

### Additional information

Including `rollingUpdate: {}` in the strategy makes it impossible to deploy with a Recreate strategy. This is identical to  #8539 and possibly others -- a cursory review of other charts indicates this may be widespread.

I am working on a PR for this.

**Comment by fmulero** [comment]
Great! thanks a lot @mconnley for opening the issue and provide a PR fixing it.

**Comment by alemorcuq** [comment]
In Helm, [you can set a value to `null` to remove it](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key). You can set `updateStrategy.type=Recreate` and `updateStrategy.rollingUpdate=null` and you should be able to deploy the chart.

**Comment by zewelor** [comment]
Looks like null values doesn't play nice with ArgoCD ( https://github.com/argoproj/argo-cd/issues/6303#issuecomment-1249592653 ). Would be good to skip rollingUpdate field if updateStrategy is set to Recreate

**Comment by fmulero** [comment]
Thanks @zewelor  for the heads up.
