### ISSUE TITLE
[bitnami/argo-cd] wait-for-redis init container is hard to configure

### ISSUE THREAD

**Issue by bh-tt** [bitnami/charts#12645]
### Name and Version

bitnami/argocd

### What is the problem this feature will solve?

I'm running argocd and want to encrypt the connection to redis. The 3 argocd components themselves offer plenty of support for that using the `extraArgs` parameter, however the init container fails because it does not expect redis to use TLS. I cannot disable the init container or change its arguments. I tried to use istio service mesh for TLS, but that disables networking capabilities of the init container unless it runs as UID 1337. The securityContext for the init container is not configurable either.

### What is the feature you are proposing to solve the problem?

Several improvements:
 - allow disabling the init container
 - allow setting the securitycontext for the init container
 - allow adding parameters to the redis-cli call

### What alternatives have you considered?

We could simply not encrypt the connection to redis, but since it handles caching of argocd (which might contain some Secrets) that is not acceptable from a security perspective.

It might be possible to configure the container using an extra initContainer with the same name as the wait-for-redis container, which then contains the extra configuration. This is an alternative solution but is harder to understand (you'll end up with half an init container defined in the values) than a few parameters defined in the chart.

**Comment by bh-tt** [comment]
Using an extra init container with the same name works partially, but to use TLS you still need to override the entire script defined [here](https://github.com/bitnami/charts/blob/cc7e00b66d0c3166329bf4a2aa4c131843552fbe/bitnami/argo-cd/templates/server/deployment.yaml#L94) and in the other 2 components. Disabling the init container is possible using this method (simply use a different script).

**Comment by bh-tt** [comment]
Using an init container with the same name only works if the deployment already exists, otherwise you end up with duplicate value errors on the initContainer name while deploying.

**Comment by bh-tt** [comment]
I have pushed a PR containing the above changes.

**Comment by fmulero** [comment]
Great! thanks a lot for sharing your findings. We will be happy to review it and provide feedback
