### ISSUE TITLE
[bitnami/metallb] Chart installs deprecated addresspools CRD 

### ISSUE THREAD

**Issue by SammyA** [bitnami/charts#12657]
### Name and Version

bitnami/metallb v4.1.3

### What steps will reproduce the bug?

Install chart

### What is the expected behavior?

CRD's should contain atleast one version that isn't deprecated

### What do you see instead?

addresspools.metallb.io CRD is installed, which is deprecated.

### Additional information

This chart installs a CustomResourceDefinition that contains only versions that are marked as deprecated: 
https://github.com/bitnami/charts/blob/master/bitnami/metallb/templates/controller/crds.yaml#L30

**Comment by yardenshoham** [comment]
This CRD is the same as the source CRD. I see no issue with it (especially as it includes v1beta1 which is not deprecated).

**Comment by SammyA** [comment]
It says "deprecated" right [here](https://github.com/bitnami/charts/blob/master/bitnami/metallb/templates/controller/crds.yaml#L117)

**Comment by javsalgar** [comment]
Hi,

Our policy is to follow the exact procedures as the upstream installation instructions are. If the upstream solution still install the CRDs even if they are deprecated, we will follow their approach. As soon as they change the CRDs, we will sync with them.

**Comment by SammyA** [comment]
Ok, good enough. I'll wait for upstream to update the crds.
