### ISSUE TITLE
[bitnami/common] _affinities namespace

### ISSUE THREAD

**Issue by dosmanak** [bitnami/charts#12668]
### Name and Version

bitnami/common 1.16.0

### What steps will reproduce the bug?

related to https://github.com/bitnami/charts/issues/10804

Hello. I struggle with the helmchart inside kustomize. The namespace transformer can't reach this value and change it accordingly.

Here is the question: Why even have the podAffinityTerm populated with namespaces list with this single value? It seems to me this setup has the same effect as not defined at all.

### What is the expected behavior?

The podAffinityTerm applies to namespace of redis deployment as in case where namespace is not specified in the podAffinityTerm docs.

```
   namespaces	<[]string>
     namespaces specifies a static list of namespace names that the term applies
     to. The term is applied to the union of the namespaces listed in this field
     and the ones selected by namespaceSelector. null or empty namespaces list
     and null namespaceSelector means "this pod's namespace"
```

### What do you see instead?

If the resource is created for different kubectl context than the current. The current namespace is injected into `podAffinityTerm.namespaces` which does not correspond with the namespace of pod.

### Additional information

I suggest the template

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_affinities.tpl#L65

should not contain 
```
    namespaces:
      - {{ include "common.names.namespace" .context | quote }}
```

**Comment by fmulero** [comment]
Thanks a lot for sharing your concerns.

Sorry but I don't fully understand this:

> If the resource is created for different kubectl context than the current. The current namespace is injected into podAffinityTerm.namespaces which does not correspond with the namespace of pod.

If the chart is released in a particular namespace (`helm install -n test ....`), that namespace should be injected in `podAffinityTerm.namespaces`. Have you find any issue? Could you provide the steps to reproduce it?

**Comment by dosmanak** [comment]
As I stated before, I am using the helm chart with kustomize. The flag you mention should be handed to helm binary here
https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go#L275

In kustomize there is [namespace transformer](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/namespace/) that can override the namespace in lower layers of kustomize hierarchy.

Unfortunately the kustomize can not modify helm parameteters specified in [helmchart generator](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_) and patching the final resource is very troublesome here.

I doubt it will be resolved quickly in kustomize (see [long term helm support issue](https://github.com/kubernetes-sigs/kustomize/issues/4401)).

From my description in this issue, the current behavior of AffinityTerm is indentical as if `namespaces` were not declared at all and so if you omit it, that would be helpful for me :-).

**Comment by fmulero** [comment]
OK, I got it. Could you open a PR linking this issue? I think that's the best option to include the changes, our capacity is limited and we couldn't give you an ETA.

**Comment by dosmanak** [comment]
> OK, I got it. Could you open a PR linking this issue? I think that's the best option to include the changes, our capacity is limited and we couldn't give you an ETA.

Hi. I was ill. I pushed the PR I hope I will handle all the bureaucracy.

**Comment by fmulero** [comment]
Thanks a lot Petr! We will come back soon with the review
