### ISSUE TITLE
[bitnami/redis] Allow empty clusterDomain

### ISSUE THREAD

**Issue by mwithheld** [bitnami/charts#12664]
### Name and Version

bitnami/redis 17.1.6

### What is the problem this feature will solve?

Some setups will not resolve *.svc.cluster.local properly, and setting an alternative clusterDomain is not desirable bc the deploy might go to different nodes, e.g. *.svc.dev.domain or *.svc.prod.domain.  Simply omitting the domain part (everything after *.svc) defaults to resolving to the local node.

If you override the default by setting clusterDomain="" DNS lookup fails because the template leaves a trailing dot (.) in the URN value after the word "svc".

```
$ helm template bitnami-redis bitnami/redis --namespace=myns  --set clusterDomain="" | grep myns.svc
              value: bitnami-redis-master-0.bitnami-redis-headless.myns.svc.
```
The DNS name will resolve if the trailing dot (.) is removed.

### What is the feature you are proposing to solve the problem?

To support using an empty clusterDomain value, this change omits the trailing dot after the word "svc" wherever it occurs IF the clusterDomain is empty:

```
$ helm template bitnami-redis bitnami/redis --namespace=myns  --set clusterDomain="" | grep myns.svc
              value: bitnami-redis-master-0.bitnami-redis-headless.myns.svc
```

### What alternatives have you considered?

One workaround is to make sure /etc/resolv.conf is setup to resolve cluster.local. 
Another workaround is to remove the .cluster.local part from the helm-generated YAML, e.g. using sed.

**Comment by fmulero** [comment]
Great! thanks a lot for sharing the PR, we will be happy to review it and provide feedback

**Comment by mwithheld** [comment]
Can this one get a look at?  It is still an issue on the latest chart.

**Comment by carrodher** [comment]
Could you please create a new issue describing your specific use case and conditions? Thank you!

**Comment by carrodher** [comment]
It seems the PR https://github.com/bitnami/charts/pull/12665 was abandoned. Would you like to continue with the contribution in a new PR in order to solve the issue?
