### ISSUE TITLE
[bitnami/rabbitmq] No Node upscaling when using replicaCount>1 and topology constraints

### ISSUE THREAD

**Issue by michelhugo** [bitnami/charts#12672]
### Name and Version

bitnami/rabbitmq

### What steps will reproduce the bug?

1. Setup a Kubernetes Cluster with 1 node and 3 maximal nodes
2. Install rabbitmq helm chart by specifying:
- replicas > 1
- a topology constraint to split replicas evenly among nodes (1 per node if possible)

### Are you using any custom parameters or values?

Here is the `topologySpreadConstraints` parameters set via `--set-file`
```
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
```

### What is the expected behavior?

Trigger the nodes up-scaling on kubernetes (via auto-scaler) to have 1 replica per node (with 2 or 3 replicas)[](url)

### What do you see instead?

All the replicas are created on the same node, regardless of the parameters I try with my topology:
- Custom labels
- Different topology keys

The parameters are passed to the pods but no upscaling happens.

When looking at the auto-scaler log, I can see `0/1 nodes are available: 1 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate`

### Additional information

With the exact same setup and same topology constraints, I can make other deployments trigger the scale-up.
These deployments have the same taint tolerations as the rabbitmq chart, which is why I think the log of the auto-scaler is misleading. I tried to add this toleration to the chart, even with the `nodeTaintsPolicy: Ignore` in the topology constraints, but it does not work.

I tried as well to use the podAntiAffinity, but same results.

When I have let's say 3 nodes running though, and I install my chart, the pods are distributed evenly. But I have 1 node running, I install my chart and then I up-scale manually, the pods do not split.

**Comment by javsalgar** [comment]
Hi,

Could you add more details on the auto-scaler you are using?

**Comment by michelhugo** [comment]
Sure, here is the config we pass to the auto-scaler via terraform:
```
auto_scaler_profile {
        balance_similar_node_groups       = false
        empty_bulk_delete_max             = "10"
        expander                          = "random"
        max_graceful_termination_sec      = "600"
        max_node_provisioning_time        = "15m"
        max_unready_nodes                 = 3
        max_unready_percentage            = 45
        new_pod_scale_up_delay            = "0s"
        scale_down_delay_after_add        = "10m"
        scale_down_delay_after_delete     = "10s"
        scale_down_delay_after_failure    = "3m"
        scale_down_unneeded               = "10m"
        scale_down_unready                = "20m"
        scale_down_utilization_threshold  = "0.5"
        scan_interval                     = "10s"
        skip_nodes_with_local_storage     = false
        skip_nodes_with_system_pods       = true
    }
```

And once again, this works with other deployments we have

**Comment by javsalgar** [comment]
I imagine that the same issue should happen when running `kubectl scale` right?

**Comment by michelhugo** [comment]
Exaclty! As mentioned, when scaling manually, I have more nodes but the pods do not split. But if I have more nodes starting with, then when I deploy my chart, the pods split accordingly

**Comment by aoterolorenzo** [comment]
Hey @michelhugo,

After trying to reproduce your issue, I can say that in a `kind` multi-node k8's cluster (2 worker nodes), using your very same values and topology constraints, I'm up and downscaling correctly BUT always within that topology constrains. We are forcing that a maximum pods of 1 are able to run per each node, so if for example you set your application with 3 replicas, only 2 of the pods will go up, while the other one will remain pending (since there are only 2 nodes and the limit is 1 for each node).

Are you maybe trying to scale to more replicas than the allowed by your topology constraints, it means, are you trying to scale to more replicas than nodes?

Some outputs of the process:

```
admin@ip-172-31-26-89:~$ kubectl get pods -w
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   1/1     Running   0          5m40s
rabbitmq-1   1/1     Running   0          4m49s
rabbitmq-2   0/1     Pending   0          4m12s

admin@ip-172-31-26-89:~$ kubectl scale --replicas=2 statefulset.apps/rabbitmq
statefulset.apps/rabbitmq scaled
admin@ip-172-31-26-89:~$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   1/1     Running   0          22m
rabbitmq-1   1/1     Running   0          22m

admin@ip-172-31-26-89:~$ kubectl scale --replicas=1 statefulset.apps/rabbitmq
statefulset.apps/rabbitmq scaled
admin@ip-172-31-26-89:~$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   1/1     Running   0          23m

admin@ip-172-31-26-89:~$ kubectl scale --replicas=2 statefulset.apps/rabbitmq
statefulset.apps/rabbitmq scaled
admin@ip-172-31-26-89:~$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   1/1     Running   0          24m
rabbitmq-1   1/1     Running   0          58s

admin@ip-172-31-26-89:~$ kubectl scale --replicas=4 statefulset.apps/rabbitmq
statefulset.apps/rabbitmq scaled
admin@ip-172-31-26-89:~$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   1/1     Running   0          28m
rabbitmq-1   1/1     Running   0          5m5s
rabbitmq-2   0/1     Pending   0          47s
```
