### ISSUE TITLE
[bitnami/thanos] Getting error on observer cluster

### ISSUE THREAD

**Issue by aravind-bet** [bitnami/charts#12673]
### Name and Version

bitnami/thanos

### What steps will reproduce the bug?

1. In this https://tanzu.vmware.com/developer/guides/prometheus-multicluster-monitoring/  document when I run the second step, two pods thanos-storegateway and thanos-compactor not coming up

### What is the expected behavior?

two pods thanos-storegateway and thanos-compactor  should come up

### What do you see instead?

two pods thanos-storegateway and thanos-compactor  not coming up. error below
```
level=warn ts=2022-09-26T07:03:39.37240905Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://my-release-thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup my-release-thanos-minio.monitoring.svc.cluster.local on 10.100.0.10:53: no such host"
```

**Comment by aoterolorenzo** [comment]
Hi @aravind-bet,

I'm having exactly the same behaviour, but the fix seems not trivial, so I'm creating an internal task for the team to address it. You will being informed in this same issue when it reach and outcome. Thanks for your contribution!

**Comment by carrodher** [comment]
Unfortunately due to other priorities and given that we are a small team, we didn't find the bandwidth to work on this issue and it is very unlikely we find it to work on it in the short term.

I will close this Issue but we can reopen it if there is any contribution from the community adding the desired feature.
