### ISSUE TITLE
[redis-cluster] redis cluster startup stuck when deployed in kubernetes 1.24

### ISSUE THREAD

**Issue by bhiravabhatla** [bitnami/charts#12682]
### Name and Version

bitnami/redis-cluster-7.5.2
Image version - 6.2.7-debian-10-r0 and 7.0.5-debian-11-r1

### What steps will reproduce the bug?

Install redis-cluster in kubernetes version - 1.24.5.
```console
CRI - containerd, Version:  v1.6.8

$ cat /etc/redhat-release
CentOS Linux release 8.5.2111

$  kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5", GitCommit:"e979822c185a14537054f15808a118d7fcce1d6e", GitTreeState:"clean", BuildDate:"2022-09-14T16:35:41Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

$ helm upgrade --install redis-cluster redis-cluster

$ kc logs -f redis-cluster-0
redis-cluster 14:46:36.81
redis-cluster 14:46:36.81 Welcome to the Bitnami redis-cluster container
redis-cluster 14:46:36.81 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 14:46:36.81 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 14:46:36.81
redis-cluster 14:46:36.81 INFO  ==> ** Starting Redis setup **
redis-cluster 14:46:36.84 INFO  ==> Initializing Redis
redis-cluster 14:46:36.85 INFO  ==> Setting Redis config file
```
All redis-cluster pods are stuck at initializing state and crashloop. Enabled BITNAMI_DEBUG as well, could not see any more logs.

### What is the expected behavior?

Expected the cluster to be formed and all pods to be healthy.

### What do you see instead?

All pods are crashlooping

```console
$ kc get po
NAME              READY   STATUS             RESTARTS            AGE
redis-cluster-0   0/1     CrashLoopBackOff   7 (37s ago)         12m
redis-cluster-1   0/1     CrashLoopBackOff   7 (22s ago)         12m
redis-cluster-2   0/1     CrashLoopBackOff   7 (42s ago)         12m
redis-cluster-3   0/1     CrashLoopBackOff   7 (32s ago)         12m
redis-cluster-4   0/1     CrashLoopBackOff   7 (17s ago)         12m
redis-cluster-5   0/1     CrashLoopBackOff   7 (<invalid> ago)   12m
```

### Additional information

Already tried removing readiness & liveness probes and giving the cluster time to form. It looks like the entrypoint scripts are stuck and not running for some reason

**Comment by bhiravabhatla** [comment]
@carrodher  Looks like dns lookup function used to retrieve the IPs of the hosts is not stuck in loop. I have enabled bash trace and I see that wait_for_dns_lookup() is stuck and is not able to retrieve IP.

+++ dns_lookup redis-cluster-0.redis-cluster-headless
+++ local host=redis-cluster-0.redis-cluster-headless
+++ local ip_version=
+++ getent ahosts redis-cluster-0.redis-cluster-headless
+++ head -n 1
+++ awk '/STREAM/ {print $1 }'
++ [[ '' == '' ]]
++ false
++ sleep 5
dns_lookup++ (( i += 1 ))
++ (( i <= retries ))
++ check_host redis-cluster-0.redis-cluster-headless
+++ dns_lookup redis-cluster-0

On further analysis - I see that `getent ahosts redis-cluster-0.redis-cluster-headless` is not returning anything in current setup (K8s 1.24.5). But I do see `getent ahosts redis-cluster-0.redis-cluster-headless`  returning IP in older version of k8s.

**K8s 1.24.5**

<img width="645" alt="image" src="https://user-images.githubusercontent.com/36130219/192434051-e6d5747c-8324-4b72-953b-d14733d64ea7.png">

I had to give the entire DNS (including .default.svc.cluster.local) to get a response. Not sure its something that was changed in latest version of coredns

<img width="674" alt="image" src="https://user-images.githubusercontent.com/36130219/192434232-23d1cbe8-d701-417e-a740-ca0beca8d3f2.png">

** K8s 1.16 **

Same version of redis-cluster is running fine in older version of k8s. getent works as expected here.

![image](https://user-images.githubusercontent.com/36130219/192434569-5e793899-7e0f-41f8-bc5d-f93293bcec4d.png)

**Comment by bhiravabhatla** [comment]
As a workaround for now - I made couple of changes, one in the redis-cluster image another in helm chart

redis-cluster image change - 

```
❯ cat /tmp/redis-patch
diff --git a/bitnami/redis-cluster/6.2/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh b/bitnami/redis-cluster/6.2/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
index 8bbf165e3e2..577ab36e172 100644
--- a/bitnami/redis-cluster/6.2/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
+++ b/bitnami/redis-cluster/6.2/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh
@@ -37,7 +37,7 @@ wait_for_dns_lookup() {
     local retries="${2:-5}"
     local seconds="${3:-1}"
     check_host() {
-        if [[ $(dns_lookup "$hostname") == "" ]]; then
+        if [[ $(dns_lookup "$hostname", v4) == "" ]]; then
             false
         else
             true
```
Redis helm chart change -

```
diff --git a/bitnami/redis-cluster/templates/redis-statefulset.yaml b/bitnami/redis-cluster/templates/redis-statefulset.yaml
index 197ccd423..300aec86d 100644
--- a/bitnami/redis-cluster/templates/redis-statefulset.yaml
+++ b/bitnami/redis-cluster/templates/redis-statefulset.yaml
@@ -1,3 +1,4 @@
+{{ $namespace:= .Release.Namespace }}
 {{- if (include "redis-cluster.createStatefulSet" .) }}
 apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
 kind: StatefulSet
@@ -145,7 +146,7 @@ spec:
               value: "no"
             {{- else }}
             - name: REDIS_NODES
-              value: "{{ $count := .Values.cluster.nodes | int }}{{ range $i, $v := until $count }}{{ include "common.names.fullname" $ }}-{{ $i }}.{{ template "common.names.fullname" $ }}-headless {{ end }}"
+              value: "{{ $count := .Values.cluster.nodes | int }}{{ range $i, $v := until $count }}{{ include "common.names.fullname" $ }}-{{ $i }}.{{ template "common.names.fullname" $ }}-headless.{{ $namespace }}.svc.cluster.local {{ end }}"
             {{- end }}
```

**Comment by bhiravabhatla** [comment]
Am not sure if we have a better way of fixing it and have not tested it for backward compatibility ( although in my view it should work).

Please let me know if this works. if yes I can raise a PR

**Comment by bhiravabhatla** [comment]
Ok. I just wasted couple of days. It was a issue with my CNI setup. Able to spin up cluster without any issue now. Please ignore this issue, closing.

**Comment by corico44** [comment]
@bhiravabhatla 
I'm glad it was resolved. Don't hesitate to open another issue if necessary!

**Comment by xiaoxuanyo** [comment]
> Ok. I just wasted couple of days. It was a issue with my CNI setup. Able to spin up cluster without any issue now. Please ignore this issue, closing.

Hello, could you please tell me how you made the final changes to take effect? ​​I'm currently encountering the same problem.
