### ISSUE TITLE
[bitnami/kibana] Not available after 30 retries happening while trying to import kibana dashboard using configmap

### ISSUE THREAD

**Issue by Sahalats** [bitnami/charts#12698]
### Name and Version

bitnami/elasticsearch 8.4.1

### What steps will reproduce the bug?

Deployed Elasticsearch with kibana and security enabled
Added xpack encription key to kibana subchart
exported kibana dashboard as ndjson file and created a configmap using it
added this config map as savedobject.config map to import it to kibana

### Are you using any custom parameters or values?
```yaml
savedObjects:
    configmap: "kibana-dashboard1"
```

### What is the expected behavior?

kibana running successfully withimported dashboard

### What do you see instead?

```
 kibana 10:36:18.64 INFO  ==> ** Starting Kibana setup **                                                                                                 
 kibana 10:36:18.65 INFO  ==> Configuring/Initializing Kibana...                                                                                          
kibana 10:36:18.66 INFO  ==> Found mounted configuration directory                                                                                       kibana 10:36:18.74 INFO  ==> Waiting for Elasticsearch to be ready.                                                                                     
kibana 10:36:18.83 INFO  ==> Skipping 'kibana_system' user creation. User already exists. Status code: 200                                               kibana 10:36:18.83 INFO  ==> Starting Kibana in background                                                                                             
 kibana 10:36:18.84 INFO  ==> Waiting for Kibana to be started and ready                                                                                   kibana 10:37:20.98 ERROR ==> Kibana is not available after 30 retries                                                                                   
 Stream closed EOF for elk/elasticsearch-kibana-68dbb9c8db-glt85 (kibana)  
```

**Comment by fmulero** [comment]
Sorry @Sahalats but there is not enough information to reproduce your issue.

I would suggest the following:

* You could use `image.debug=true` for additional information about the deployment.
* Use `diagnosticMode.enabled=true` to deploy the pods without running a sleep infinity, then open a bash terminal and initialize them manually, you can run  '/opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh'
