### ISSUE TITLE
bitnami/zookeeper is broken after clusterDomain parameter has been added

### ISSUE THREAD

**Issue by VladyslavTokar** [bitnami/charts#1270]
**Which chart**:

zookeeper

**Description**

After clusterDomain parameter has been added we can't install the chart due to an issue with templating.

**Steps to reproduce the issue:**
```
helm install bitnami/zookeeper
```
**Describe the results you received:**
```
Error: render error in "zookeeper/templates/statefulset.yaml": template: zookeeper/templates/statefulset.yaml:97:166: executing "zookeeper/templates/statefulset.yaml" at <.Values.clusterDomai...>: can't evaluate field Values in type int
```
**Describe the results you expected:**

Apply fix to the `statefulset.yaml` and `metrics-deployment.yaml` files
```diff
+ {{- $clusterDomain := .Values.clusterDomain }}
-         value: {{ range $i, $e := until $replicaCount }}{{ $zookeeperFullname }}-{{ $e }}.{{ $zookeeperHeadlessServiceName }}.{{ $releaseNamespace }}.svc.{{ .Values.clusterDomain }}:{{ $followerPort }}:{{ $electionPort }} {{ end }}
+         value: {{ range $i, $e := until $replicaCount }}{{ $zookeeperFullname }}-{{ $e }}.{{ $zookeeperHeadlessServiceName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}:{{ $followerPort }}:{{ $electionPort }} {{ end }}
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, thanks for reporting it, changes were introduced [here](https://github.com/bitnami/charts/pull/1266/files#diff-6b063ad92827264b128cc05c45bd9232), we are taking in a look in order to fix it.

We will update this thread with more information. Thanks again!

**Comment by carrodher** [comment]
@VladyslavTokar it should be fixed in the above PR, please, feel free to reopen the case if the issue persists.
Thanks!

**Comment by VladyslavTokar** [comment]
Hi @carrodher,

Thanks a lot for the quick response. Unfortunately, the issue is reproducing when metrics.enabled parameter set to true. Could you apply a fix to the metrics-deployment.yaml file as well?

**{{- $clusterDomain := .Values.clusterDomain }}**
          - {{range $i, $e := until $replicaCount }}{{ $zookeeperFullname }}-{{ $e }}.{{ $zookeeperHeadlessServiceName }}.{{ $releaseNamespace }}.svc.**{{ $clusterDomain }}**:{{ $servicePort }}{{- if (lt $e ( sub $replicaCount 1)) -}},{{- end -}}{{ end }}

Thanks in advance.

**Comment by carrodher** [comment]
🤦‍♂ It's true, we're sending a new PR adding the same changes to the `metrics-deployment.yaml`, sorry for the noise. Thanks!
