### ISSUE TITLE
wrong type for value: clickhouse/charts/common/templates/_tplvalues.tpl

### ISSUE THREAD

**Issue by davidshanghai** [bitnami/charts#12714]
### Name and Version

bitnami / clickhouse 0.2.0

### What steps will reproduce the bug?

Install the 0.2.0  chart, with adding the following customization:
```yaml
variable "tolerations" {
  type = any
  default = [{
    key                     = "group"
    operator                = "Equal"
    value                   = "common"
    effect                  = "NoSchedule"
  }]
}
```

Helm installation will fail with the following error message:
```
Error: template: clickhouse/templates/statefulset.yaml:60:23: executing "clickhouse/templates/statefulset.yaml" at <include "common.tplvalues.render" (dict "value" $.Values.tolerations "context" .)>: error calling include: template: clickhouse/charts/common/templates/_tplvalues.tpl:11:34: executing "common.tplvalues.render" at <.context>: wrong type for value; expected chartutil.Values; got int
```

### What do you see instead?

Error: template: clickhouse/templates/statefulset.yaml:60:23: executing "clickhouse/templates/statefulset.yaml" at <include "common.tplvalues.render" (dict "value" $.Values.tolerations "context" .)>: error calling include: template: clickhouse/charts/common/templates/_tplvalues.tpl:11:34: executing "common.tplvalues.render" at <.context>: wrong type for value; expected chartutil.Values; got int

**Comment by rafariossaa** [comment]
Thanks for reporting this.
I have just created a PR to fix it.
