### ISSUE TITLE
bitnami/redis-cluster can't get flow of adding nodes to cluster

### ISSUE THREAD

**Issue by kost2191** [bitnami/charts#12738]
### Name and Version

bitnami/redis-cluster 7.0.5

### What is the problem this feature will solve?

How can I increase amount of node and automatically add them to the cluster?

### What is the feature you are proposing to solve the problem?

Can you provide more concrete steps to make it?

**Comment by carrodher** [comment]
In the README, you can take a look at the different configuration parameters, for instance at https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-management-parameters
