### ISSUE TITLE
[bitnami/keycloak] Latest Chart Not Published

### ISSUE THREAD

**Issue by msvechla** [bitnami/charts#12745]
### Name and Version

bitnami/keyloak 10.1.3

### What steps will reproduce the bug?

The latest Keycloak Chart version has not been published on the default branch. The changes have been merged, but the pipeline failed: https://github.com/bitnami/charts/actions/runs/3141966802/jobs/5105016557

See also: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/Chart.yaml#L29, which shows 10.1.3

in comparison to:

```bash
helm search repo bitnami/keycloak
```

```
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/keycloak        10.1.2          19.0.2          Keycloak is a high performance Java-based ident...
```

Looks like a similar thing happened 3 days ago: https://github.com/bitnami/charts/issues/12590

Thanks & best regards!

### What is the expected behavior?

bitnami/keycloak version 10.1.3 is published

### What do you see instead?

bitnami/keycloak version 10.1.3 is not published

**Comment by fmulero** [comment]
Thanks @msvechla  for the heads up. We are currently facing an issue in the publish pipelines. We'll back soon with news

**Comment by msvechla** [comment]
Any update on this? The latest keycloak chart is still not available and we are waiting for this release as it contains a blocking bugfix.

Can you simply re-trigger the latest keycloak pipeline while working on fixing the root-cause?
Thanks a lot for your help!

**Comment by fmulero** [comment]
Hi @msvechla I forced this morning a new release. It is now in the helm repository

**Comment by msvechla** [comment]
Thanks, I can confirm this is working since yesterday. Feel free to close this issue if the root-cause is fixed!

**Comment by fmulero** [comment]
Yes, our CD pipeline was failing for all charts #12748
