### ISSUE TITLE
[bitnami/kafka] External access document Using ClusterIP services

### ISSUE THREAD

**Issue by yhjhoo** [bitnami/charts#12741]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

I couldn't follow the document to config kafka in minikube and allow me to access from my dev IDE intellij

### What is the feature you are proposing to solve the problem?

add more details of this document or a details tutorial.

### What alternatives have you considered?

reading a lot of document and stackoverflow.

**Comment by yhjhoo** [comment]
I followed this document https://github.com/bitnami/charts/tree/master/bitnami/kafka to config external access. I got this problem resolved. 
Here is my solution
https://github.com/yhjhoo/kafka-demo/tree/main/minikube-config

**Comment by javsalgar** [comment]
Thanks for letting us know. If you believe that your findings could be helpful to the documentation, would you like to submit a PR improving the README?
