### ISSUE TITLE
[bitnami/thanos] HPA can't use capabilities to detect API version

### ISSUE THREAD

**Issue by lewandowskim1988** [bitnami/charts#12747]
### Name and Version

bitnami/thanos 11.5.3

### What steps will reproduce the bug?

Use chart bitnami/thanos 11.5.3 and running `helm template` fail.

### Are you using any custom parameters or values?

`helm template . --set existingObjstoreSecret=thanos --set storegateway.enabled=true --set storegateway.autoscaling.enabled=true`

### What is the expected behavior?

helm templating function common.capabilities.hpa.apiVersion should return apigroup & version for detected K8S version

### What do you see instead?

`Error: template: thanos/templates/storegateway/hpa.yaml:2:15: executing "thanos/templates/storegateway/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" (dict "context" $)>: error calling include: template: thanos/charts/common/templates/_capabilities.tpl:133:32: executing "common.capabilities.hpa.apiVersion" at <include "common.capabilities.kubeVersion" .>: error calling include: template: thanos/charts/common/templates/_capabilities.tpl:7:14: executing "common.capabilities.kubeVersion" at <.Values.global>: nil pointer evaluating interface {}.global`

### Additional information

The same behavior is present for `query`, `query-frontend` and `receive` components.
Following change fix this issue

What is in `helm chart`
```
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
```
Fix
```
apiVersion: {{ include "common.capabilities.hpa.apiVersion" . }}
```

**Comment by fmulero** [comment]
It seems to be related to #12372, I've just created a PR to upgrade the dependencies
