### ISSUE TITLE
README isntructions not clear for externalDatabase.type

### ISSUE THREAD

**Issue by kslacroix** [bitnami/charts#12776]
### Name and Version

bitnami/moodle

### What is the problem this feature will solve?

The definition for the field externalDatabase.type is `Type of the existing database`. What are the possible values for it?

I have a MySQL database server managed by Vultr. I know that MariaDB is no longer a drop in replacement for MySQL. Do I need to specify MySQL? 

### What is the feature you are proposing to solve the problem?

Adding the list of possible values in the README.

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
