### ISSUE TITLE
[bitnami/argo-cd] Not found: "static-assets"

### ISSUE THREAD

**Issue by alexey-anufriev** [bitnami/charts#12785]
### Name and Version

bitnami/argo-cd 2.4.11

### What steps will reproduce the bug?

1. Create PV
2. Run
```
helm install argocd -n argocd --create-namespace \
  --set volumePermissions.enabled=true \
  bitnami/argo-cd
  ```

### Are you using any custom parameters or values?

volumePermissions.enabled=true

### What do you see instead?

Installation fails with the following error:
`Deployment.apps "argocd-argo-cd-server" is invalid: spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "static-assets"`

**Comment by fmulero** [comment]
We can reproduce the issue without running the step 1

**Comment by jotamartos** [comment]
Hi @alexey-anufriev,

I found that the volume-permissions initContainers were erroneously defined in the chart. I created this PR to fix the issues 

https://github.com/bitnami/charts/pull/12853

**Comment by alexey-anufriev** [comment]
@jotamartos, could you please rebase your fix branch?

**Comment by jotamartos** [comment]
Hi @alexey-anufriev,

The PR is now closed. A new version of the chart will be released soon! 

Thanks!

**Comment by alexey-anufriev** [comment]
Thank you for help!
