### ISSUE TITLE
[bitnami/airflow] unable to connect psycopg2, already installed in pod but unable to connect this.

### ISSUE THREAD

**Issue by venkatzoomcar** [bitnami/charts#12796]
### Name and Version

bitnami/airflow 2.3.4

### What steps will reproduce the bug?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110613089/193746541-b89dc60b-874d-469f-8534-105c76b1ff33.png">

### Are you using any custom parameters or values?

no

### What is the expected behavior?

getting error in logs

### What do you see instead?

run properly

**Comment by venkatzoomcar** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110613089/193746739-c77bf89a-4da1-4714-ada5-84ae48bc0eaf.png">

**Comment by migruiz4** [comment]
Hi @venkatzoomcar,

The issue is caused because `python3.8` is calling the system's while airflow is installed using `virtualenv` under `/opt/bitnami/airflow/venv`.

You could workaround this issue by calling `/opt/bitnami/airflow/venv/bin/python3.8` instead of `python3.8`.
