### ISSUE TITLE
[bitnami/memcached] The metrics container need to have securityContext configured

### ISSUE THREAD

**Issue by shoujun** [bitnami/charts#12807]
### Name and Version

bitnami/memcached

### What is the problem this feature will solve?

The metrics container need to have securityContext configured.

### What is the feature you are proposing to solve the problem?

The metrics container need to have securityContext configured, it should similar to memcached container.

**Comment by fmulero** [comment]
Hi @shoujun 

Thanks for reporting this issue. Unfortunately we don't have enough capacity and we can't give you an ETA. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by cleverhu** [comment]
I'd like to add the securityContext for it.

**Comment by fmulero** [comment]
Thanks a lot @cleverhu
