### ISSUE TITLE
[bitnami/matomo] GeoIP database to persistent volume

### ISSUE THREAD

**Issue by kajla** [bitnami/charts#12801]
### Name and Version

bitnami/matomo 0.2.8

### What steps will reproduce the bug?

The GeoIP database store path is /opt/bitnami/matomo/misc/ which is in the container, so it will be lost when creating a new pod.
I recommend moving the /bitnami/matomo/misc persistent volume to survive the pod.

### What is the expected behavior?

The GeoIP database should be on a persistent volume.

### What do you see instead?

In the case of a new pod, you will receive the following warning:

**The configured geolocation provider geoip2php is not available anymore, please configure another one.**
![geoiperror](https://user-images.githubusercontent.com/5457824/193809413-60c72a5f-4151-4d28-b673-597c3c942e65.png)

**Comment by aoterolorenzo** [comment]
Hi @kajla! Thanks for filing this issue.

Makes complete sense. I will create an internal task for the team to address it, marking this as on-hold meanwhile to avoid the @bitnami-bot marking is as stale and closing it. We will be back to you as this task is implemented.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jotamartos** [comment]
Hi @kajla,

The entire misc folder is now part of the persisted volume. The chart included this change in the latest version 

https://github.com/bitnami/charts/pull/14456

You can get more info [here](https://github.com/bitnami/containers/commit/be743f1f0d5806ca15602146e5f172e1b48e713f)
