### ISSUE TITLE
[bitnami/logstash] cannot find or move mssql-jdbc

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/charts#12825]
### Name and Version

bitnami/logstash 5.1.4

### What steps will reproduce the bug?

1. I need connect to mssql and sync db to Elastic search with Logstash. But I cannot find mssql-jdbc inside container
2. I try down a mssql-jdbc from Microsoft but I cannot copy into container because it Permission Denied. Maybe I can copy it into container, I will remove after it create again to run script??
How can I work it??

### What do you see instead?

How can I work it??

**Comment by rafariossaa** [comment]
Hi,
  Depending on how you need to install the driver, you would need to generate your own image adding it.

**Comment by thanhtai9606** [comment]
> Hi, Depending on how you need to install the driver, you would need to generate your own image adding it.

Oh, Do I have to make my own  image and install driver base on bitnami image??

**Comment by rafariossaa** [comment]
The image have support for jdbc:
```
$ % docker run --rm -it bitnami/logstash bash
logstash 09:04:44.63
logstash 09:04:44.64 Welcome to the Bitnami logstash container
logstash 09:04:44.64 Subscribe to project updates by watching https://github.com/bitnami/containers
logstash 09:04:44.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
logstash 09:04:44.64

I have no name!@3b379035592c:/opt/bitnami/logstash$ logstash-plugin list
Using system java: /opt/bitnami/java/bin/java
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
...
logstash-integration-jdbc
 ├── logstash-input-jdbc
 ├── logstash-filter-jdbc_streaming
 └── logstash-filter-jdbc_static
...
```
However, you need to include the [driver](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#_drivers).

How did you tried to copy the file into the image ?

**Comment by thanhtai9606** [comment]
> The image have support for jdbc:
> 
> ```
> $ % docker run --rm -it bitnami/logstash bash
> logstash 09:04:44.63
> logstash 09:04:44.64 Welcome to the Bitnami logstash container
> logstash 09:04:44.64 Subscribe to project updates by watching https://github.com/bitnami/containers
> logstash 09:04:44.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
> logstash 09:04:44.64
> 
> I have no name!@3b379035592c:/opt/bitnami/logstash$ logstash-plugin list
> Using system java: /opt/bitnami/java/bin/java
> OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> ...
> logstash-integration-jdbc
>  ├── logstash-input-jdbc
>  ├── logstash-filter-jdbc_streaming
>  └── logstash-filter-jdbc_static
> ...
> ```
> 
> However, you need to include the [driver](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#_drivers).
> 
> How did you tried to copy the file into the image ?

I create a pod base on bitnami logstash, I can use kubectl cp or create with map files when use docker-compose file

**Comment by thanhtai9606** [comment]
`                                                                                                     Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                                                                                                        │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_integration_minus_jdbc_minus_5_dot_3_dot_0.lib.logstash.plugin_mixins.jdbc.jdbc.RUBY$method$execute_statement$0(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-j │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_integration_minus_jdbc_minus_5_dot_3_dot_0.lib.logstash.plugin_mixins.jdbc.jdbc.RUBY$method$execute_statement$0$__VARARGS__(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-i │
│     at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139) [jruby.jar:?]                                                                                                                                                                       │
│     at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112) [jruby.jar:?]                                                                                                                                                                     │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198) [jruby.jar:?]                                                                                                                                                                                          │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_integration_minus_jdbc_minus_5_dot_3_dot_0.lib.logstash.inputs.jdbc.RUBY$method$execute_query$0(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-jdbc-5.3.0/lib/lo │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_integration_minus_jdbc_minus_5_dot_3_dot_0.lib.logstash.inputs.jdbc.RUBY$method$execute_query$0$__VARARGS__(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-jdbc- │
│     at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139) [jruby.jar:?]                                                                                                                                                                       │
│     at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112) [jruby.jar:?]                                                                                                                                                                     │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208) [jruby.jar:?]                                                                                                                                                                                          │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_integration_minus_jdbc_minus_5_dot_3_dot_0.lib.logstash.inputs.jdbc.RUBY$block$run$1(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-jdbc-5.3.0/lib/logstash/inpu │
│     at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:141) [jruby.jar:?]                                                                                                                                                                            │
│     at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:64) [jruby.jar:?]                                                                                                                                                                                                   │
│     at org.jruby.runtime.Block.call(Block.java:147) [jruby.jar:?]                                                                                                                                                                                                              │
│     at org.jruby.RubyProc.call(RubyProc.java:272) [jruby.jar:?]                                                                                                                                                                                                                │
│     at org.jruby.RubyProc$INVOKER$i$call.call(RubyProc$INVOKER$i$call.gen) ~[jruby.jar:?]                                                                                                                                                                                      │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208) ~[jruby.jar:?]                                                                                                                                                                                         │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$method$do_call$0(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234) [?:?] │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$method$do_call$0$__VARARGS__(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.r │
│     at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139) [jruby.jar:?]                                                                                                                                                                       │
│     at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112) [jruby.jar:?]                                                                                                                                                                     │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208) [jruby.jar:?]                                                                                                                                                                                          │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$method$do_trigger$0(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258) [? │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$method$do_trigger$0$__VARARGS__(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/job │
│     at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139) [jruby.jar:?]                                                                                                                                                                       │
│     at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112) [jruby.jar:?]                                                                                                                                                                     │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208) [jruby.jar:?]                                                                                                                                                                                          │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$block$start_work_thread$3(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:3 │
│     at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:141) [jruby.jar:?]                                                                                                                                                                            │
│     at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:64) [jruby.jar:?]                                                                                                                                                                                                   │
│     at org.jruby.runtime.Block.call(Block.java:147) [jruby.jar:?]                                                                                                                                                                                                              │
│     at org.jruby.RubyProc.call(RubyProc.java:272) [jruby.jar:?]                                                                                                                                                                                                                │
│     at org.jruby.RubyProc$INVOKER$i$call.call(RubyProc$INVOKER$i$call.gen) ~[jruby.jar:?]                                                                                                                                                                                      │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208) ~[jruby.jar:?]                                                                                                                                                                                         │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$block$start_work_thread$2(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:3 │
│     at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151) [jruby.jar:?]                                                                                                                                                                           │
│     at org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:72) [jruby.jar:?]                                                                                                                                                                                          │
│     at org.jruby.runtime.Block.yieldSpecific(Block.java:157) [jruby.jar:?]                                                                                                                                                                                                     │
│     at org.jruby.RubyKernel.loop(RubyKernel.java:1507) [jruby.jar:?]                                                                                                                                                                                                           │
│     at org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen) [jruby.jar:?]                                                                                                                                                                           │
│     at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:560) [jruby.jar:?]                                                                                                                                                               │
│     at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198) [jruby.jar:?]                                                                                                                                                                                          │
│     at opt.bitnami.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.rufus_minus_scheduler_minus_3_dot_0_dot_9.lib.rufus.scheduler.jobs.RUBY$block$start_work_thread$1(/opt/bitnami/logstash/vendor/bundle/jruby/2.6.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:2 │
│     at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:141) [jruby.jar:?]                                                                                                                                                                            │
│     at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:64) [jruby.jar:?]                                                                                                                                                                                                   │
│     at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) [jruby.jar:?]                                                                                                                                                                                                   │
│     at org.jruby.runtime.Block.call(Block.java:143) [jruby.jar:?]                                                                                                                                                                                                              │
│     at org.jruby.RubyProc.call(RubyProc.java:309) [jruby.jar:?]                                                                                                                                                                                                                │
│     at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:107) [jruby.jar:?]                                                                                                                                                                                        │
│     at java.lang.Thread.run(Thread.java:829) ~[?:?]                                                                                                                                                                                                                            │
│ [2022-10-11T07:35:30,656][ERROR][logstash.inputs.jdbc     ][main][451e1d31d0bd3966bfd86ca580c92dc54232ed8636f4eacc98a237c8b50189e9] Unable to connect to database. Tried 1 times {:message=>"Java::ComMicrosoftSqlserverJdbc::SQLServerException: This driver is not configure │
│ [2022-10-11T07:35:30,657][WARN ][logstash.inputs.jdbc     ][main][451e1d31d0bd3966bfd86ca580c92dc54232ed8636f4eacc98a237c8b50189e9] Exception when executing JDBC query {:exception=>Sequel::DatabaseConnectionError, :message=>"Java::ComMicrosoftSqlserverJdbc::SQLServerExc │
│                                                                                                                                                                                                                                                                                `
I tried copy mssql-jdbc.jar into **/opt/bitnami/logstash/logstash-core/lib/jars**
and config in logstash
`
 jdbc {
        jdbc_connection_string => "jdbc:sqlserver://192.168.103.96:1433;databaseName=UAT_Becamex_ArchiveCenter;integratedSecurity=true;"
        jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        jdbc_driver_library => "/opt/bitnami/logstash/logstash-core/lib/jars/mssql-jdbc.jar" 
        jdbc_user => "sa"
        jdbc_password => "Becamex@1234"
        jdbc_paging_enabled => "true"
        jdbc_page_size => "5000"
        schedule => "* * * * *"
        statement => "SELECT * FROM Documents"
    }
`
But it not working!!!

**Comment by rafariossaa** [comment]
Hi,
  It seems that the messages got truncated. From what I can see:
```
 [2022-10-11T07:35:30,656][ERROR][logstash.inputs.jdbc     ][main][451e1d31d0bd3966bfd86ca580c92dc54232ed8636f4eacc98a237c8b50189e9] Unable to connect to database. Tried 1 times {:message=>"Java::ComMicrosoftSqlserverJdbc::SQLServerException: This driver is not configure │
 [2022-10-11T07:35:30,657][WARN ][logstash.inputs.jdbc     ][main][451e1d31d0bd3966bfd86ca580c92dc54232ed8636f4eacc98a237c8b50189e9] Exception when executing JDBC query {:exception=>Sequel::DatabaseConnectionError, :message=>"Java::ComMicrosoftSqlserverJdbc::SQLServerExc │
```
  It seems that the classes are loaded but there are other issues. I would suggest you to ask in logstash forums about this error. I think the could provide better help for this errors.

**Comment by carrodher** [comment]
Glad you were able to fix the issue by applying that workaround
