### ISSUE TITLE
[bitnami/etcd] when can i use etcdutl?

### ISSUE THREAD

**Issue by dpa456** [bitnami/charts#12831]
### Name and Version

bitnami/etcd 3.5.0

### What is the problem this feature will solve?

etcdctl restore is deprecated, so instead etcdutl by 3.5 etcd version

![스크린샷 2022-10-06 오후 2 27 31](https://user-images.githubusercontent.com/10584073/194221644-35855aa4-9006-435d-84d6-560f931aa27e.png)

rep : 
https://etcd.io/docs/v3.5/op-guide/recovery/

### What is the feature you are proposing to solve the problem?

mount etcdutl by bitnami/etcd

**Comment by dpa456** [comment]
Oh, i found etcdutl but this is not global(bin path)

I think it needs to be moved.

/opt/bitnami/etc -> /opt/bitnami/etc/bin

**Comment by fmulero** [comment]
Thanks a lot @dpa456, for sharing this issue.

This PR https://github.com/bitnami/containers/pull/10867 should fix the issue.
