### ISSUE TITLE
Add tolerations for pods in keycloakCli job

### ISSUE THREAD

**Issue by valentinavav** [bitnami/charts#12839]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Pods created by keycloakCli job are not assigned to the tainted nodes as needed.

### What is the feature you are proposing to solve the problem?

Add `keycloakConfigCli.tolerations` to `values.yaml` similar to already defined `tolerations` value

**Comment by rafariossaa** [comment]
Hi,
  Would you like to send a PR adding this ?
  We will be glad of reviewing and merging it.

**Comment by cleverhu** [comment]
I'd like to add tolerations for pods in keycloakCli job.

**Comment by valentinavav** [comment]
> I'd like to add tolerations for pods in keycloakCli job.

That would be great as I could do it a little later.
