### ISSUE TITLE
[bitnami/redis] Redis startup scripts overwrite multiple configuration settings

### ISSUE THREAD

**Issue by JDKnobloch** [bitnami/charts#12843]
### Name and Version

bitnami/redis 17.3.2

### What steps will reproduce the bug?

Currently you are unable to overwrite certain values within the Values.sentinel.configuration as they are automatically overwritten in scripts-configmap.yaml

For example, we desire to not use hostnames and instead return IP's as we have a redis install being used cross k8s clusters.
To accomplish this, we must set the configuration `sentinel announce-hostnames no`, a value that is automatically overwritten currently [here](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/scripts-configmap.yaml#L386).

Functionality should be added so that these values can be overwritten as desired.

### Are you using any custom parameters or values?

```
sentinel:
  configuration: |-
    sentinel announce-hostnames no
```

### What is the expected behavior?

Configuration file contains `sentinel announce-hostnames no`

### What do you see instead?

Configuration file is overwritten to contain `sentinel announce-hostnames yes`

### Additional information

I am submitting a PR to address this.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
