### ISSUE TITLE
[bitnami/kafka] Issue installing chart 

### ISSUE THREAD

**Issue by devnarenku** [bitnami/charts#12840]
### Name and Version

bitnami/kafka 

### What steps will reproduce the bug?

Hi All, 

I have installed kafka as below, but zookeeper pod is not coming up, it got struck at init container `mkdir` itself. 

```
helm install mykafka bitnami/kafka

mykafka-0                                    0/1     CrashLoopBackOff   14         37m
mykafka-zookeeper-0                          0/1     CrashLoopBackOff   12         37m

zookeeper 12:19:32.86 Welcome to the Bitnami zookeeper container
zookeeper 12:19:32.86 Subscribe to project updates by watching https://github.com/bitnami/containers
zookeeper 12:19:32.86 Submit issues and feature requests at https://github.com/bitnami/containers/issues
zookeeper 12:19:32.86
zookeeper 12:19:32.86 INFO  ==> ** Starting ZooKeeper setup **
zookeeper 12:19:32.89 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
mkdir: cannot create directory '/bitnami/zookeeper': Permission denied
```
 
 could anyone of you help on this?
 
 Thanks in advances. 
 

### What do you see instead?

mkdir: cannot create directory '/bitnami/zookeeper': Permission denied

**Comment by devnarenku** [comment]
Hi, Have you any idea/update to fix this issue?

**Comment by zhenzh** [comment]
Are you specified your onw pvc for persitence? You can try setting volumePermission to true

**Comment by devnarenku** [comment]
yes, I have specified my local storage class name. 

It started working after specifying the volume Permission to true.

thanks

**Comment by javsalgar** [comment]
Hi,

Could you provide more details on the Kubernetes installation you are using? It seems to me that there are issues with the volume provider.

**Comment by devnarenku** [comment]
```
kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.14
```
