### ISSUE TITLE
Zookeeper Metrics Exporter defaults to an image repository without tags

### ISSUE THREAD

**Issue by austince** [bitnami/charts#1284]
**Which chart**:

zookeeper, version 3.5.5

**Description**

The [default Prometheus metrics exporter image repository](https://hub.docker.com/r/javsalgar/zookeeper-exporter) does not have any versioned tagged images, making it impossible to pin a version, which is unsuitable for production environments. I also cannot find the source repo for the `latest` tag.

Does anyone on this team control that repo / could push some tags? Or perhaps we could switch over [to a different repository](https://hub.docker.com/r/dabealu/zookeeper-exporter)?

**Comment by austince** [comment]
Ah, I see that the repo with tags is in the `values-production.yaml` file - though it still might be nice to use the same repository for both values files.

**Comment by carrodher** [comment]
Both files (_values.yaml_ and _values-production.yaml_) are using the [dabealu/zookeeper-exporter](https://hub.docker.com/r/dabealu/zookeeper-exporter) with an specific tag:

- https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml#L206
- https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values-production.yaml#L206

Are you using the latest version of the chart? Those changes were done 3 months ago https://github.com/bitnami/charts/commit/eb14061eaca39f5f5d5a88056305d4f143c1366b

**Comment by austince** [comment]
I must have grabbed an old version, thank you + sorry for the mixup!

**Comment by carrodher** [comment]
No problem, happy to help!

**Comment by austince** [comment]
I've got everything up and running, but am running into this problem (https://github.com/dabealu/zookeeper-exporter/issues/10) - is this also something that's already handled in the default config somehow or should I open up a new ticket?

**Comment by austince** [comment]
I have found it is possible to get around with the `jvmFlags` config option, but maybe we should look into setting this by default?

**Comment by carrodher** [comment]
ZooKeeper chart supports two ways to customize the default configuration:
- `jvmFlags` (set the default `JVMFLAGS` for the ZooKeeper process)
- `config` (configure ZooKeeper with a custom _zoo.conf_ file)

You can use it by setting the `--set` flag in the `helm install` command or by modifying the _values.yaml_ file.

In the image, the configuration file is hosted in _/opt/bitnami/zookeeper/conf/zoo.cfg_, [here](https://github.com/bitnami/bitnami-docker-zookeeper#configuration-1) you can find more information about how to modify this file at the image level.
