### ISSUE TITLE
[Elasticsearch] pods unable to start when scaling up the replicas

### ISSUE THREAD

**Issue by Bhargav6611** [bitnami/charts#12850]
### Name and Version

Bitnami Elasticsearch Stack/8.4.2209280752

### What steps will reproduce the bug?

Hi Team,

We are using the Catalog Offering: **Bitnami Elasticsearch Stack** having Offering version: **8.4.2209280752** deployed on IBM Cloud Kubernetes service, once deployed all the pods are in Running State while for the data pod, it is unable to start due to the below error seen while describing the pod.

The same error occurs while I try to scale up any of the other pods.

```
Failed to pull image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to resolve reference "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to do request: Head "https://registry-1.docker.io/v2/bitnami/bitnami-shell/manifests/11-debian-11-r37": dial tcp 34.205.13.154:443: connect: no route to host
```

Another Q we have is -- I am unable to change the variable value of the Terraform Template for the variables `data.containerSecurityContext.runAsNonRoot` : I get the error as below:

```
Terraform apply | Error: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext.runAsNonRoot): invalid type for io.k8s.api.core.v1.SecurityContext.runAsNonRoot: got "string", expected "boolean"
```

Kindly assist regarding the same.

Thanks.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

pods to Run

### What do you see instead?

```
Failed to pull image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to resolve reference "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to do request: Head "https://registry-1.docker.io/v2/bitnami/bitnami-shell/manifests/11-debian-11-r37": dial tcp 34.205.13.154:443: connect: no route to host
```

### Additional information

NA

**Comment by rafariossaa** [comment]
Hi,
  Could you try to pull the image manually ? Maybe there was a transient error from where you were trying to pull the image:
```
$ docker pull bitnami/bitnami-shell:11-debian-11-r37
11-debian-11-r37: Pulling from bitnami/bitnami-shell
1d8866550bdd: Already exists 
28719dadcb3f: Pull complete 
Digest: sha256:0946f1d16c010bed0a47e3c09ff193d898c868044bb4c1b037c83b7c53c26deb
Status: Downloaded newer image for bitnami/bitnami-shell:11-debian-11-r37
docker.io/bitnami/bitnami-shell:11-debian-11-r37
```
  Regarding `data.containerSecurityContext.runAsNonRoot`, it seems you are not passing the right value for it. [It needs a boolean](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/README.md#user-content-data-only-nodes-parameters).

**Comment by Bhargav6611** [comment]
Hi,

This error is seen when the Kubernetes replica is scaled, error shown below:

Pod Name: elasticsearchd-ea36ddbe-data-1

`Failed to pull image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to resolve reference "docker.io/bitnami/bitnami-shell:11-debian-11-r37": failed to do request: Head "https://registry-1.docker.io/v2/bitnami/bitnami-shell/manifests/11-debian-11-r37": dial tcp 3.216.34.172:443: connect: no route to host`

`Back-off pulling image "docker.io/bitnami/bitnami-shell:11-debian-11-r37"`

`Error: ImagePullBackOff`

For `data.containerSecurityContext.runAsNonRoot`, I did pass the value as false.
Is the value for this variable fixed to "true" because if I pass as "false", I am seeing this error:

`Terraform apply | Error: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext.runAsNonRoot): invalid type for io.k8s.api.core.v1.SecurityContext.runAsNonRoot: got "string", expected "boolean"`

**Comment by Bhargav6611** [comment]
Hi Team,

Any insights to above query.

**Comment by Bhargav6611** [comment]
Hi Team,

Reminder for the above issue which we are facing.

**Comment by Bhargav6611** [comment]
Hi Team

**Comment by corico44** [comment]
Hello,
As Rafa said, could you try to pull the image manually ? Maybe there was a transient error from where you were trying to pull the image:

```
$ docker pull bitnami/bitnami-shell:11-debian-11-r37
11-debian-11-r37: Pulling from bitnami/bitnami-shell
1d8866550bdd: Already exists 
28719dadcb3f: Pull complete 
Digest: sha256:0946f1d16c010bed0a47e3c09ff193d898c868044bb4c1b037c83b7c53c26deb
Status: Downloaded newer image for bitnami/bitnami-shell:11-debian-11-r37
docker.io/bitnami/bitnami-shell:11-debian-11-r37
```

And as for the terraform error, you should indicate the value in the following way:
```
containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: false
```
Do not put the value between double quotes, because it will detect the value as a string and not a boolean.
