### ISSUE TITLE
[bitnami/zookeeper] Allow setting "extendedTypesEnabled" config in Zookeeper chart

### ISSUE THREAD

**Issue by maxim-slavutsky** [bitnami/charts#12851]
### Name and Version

bitnami/zookeeper 3.8.0

### What is the problem this feature will solve?

Currently, I am unable to set those config values with chart configuration and I have to override the whole zoo.cfg file in order to modify those settings.

### What is the feature you are proposing to solve the problem?

I would like to set extendedTypesEnabled=true and emulate353TTLNodes=true through chart values

### What alternatives have you considered?

Overriding zoo.cfg config file

**Comment by javsalgar** [comment]
Hi,

In the zookeeper container we have [this function | https://github.com/bitnami/containers/blob/main/bitnami/zookeeper/3.8/debian-11/rootfs/opt/bitnami/scripts/libzookeeper.sh#L277]

```
########################
# Configure Zookeeper configuration files from environment variables
# Globals:
#   ZOO_*
# Arguments:
#   None
# Returns:
#   None
#########################
zookeeper_configure_from_environment_variables() {
    # Map environment variables to config properties
    for var in "${!ZOO_CFG_@}"; do
        key="$(echo "$var" | sed -e 's/^ZOO_CFG_//g' -e 's/_/\./g')"
        value="${!var}"
        zookeeper_conf_set "$ZOO_CONF_FILE" "$key" "$value"
    done
}

```

The variables with the format `ZOO_CFG_nameofthesetting` are mapped in the zoo.cfg file. Could you try it with your variables? You can use the `extraEnvVars` value of the chart.

**Comment by maxim-slavutsky** [comment]
Hello, @javsalgar thanks for the explanation, I admit I didn't dig that deep into the chart. But unfortunately, it didn't work for me.
I've added extra ENVs as you recommended:
`
extraEnvVars:
  - name: "ZOO_CFG_extendedTypesEnabled"
    value: "true"
  - name: "ZOO_CFG_emulate353TTLNodes"
    value: "true"
`

I see those ENV variables in the pod:
`
I have no name!@authzookeeper-0:/$ env | grep extendedTypesEnabled
ZOO_CFG_extendedTypesEnabled=true
`

But they do not appear in the /opt/bitnami/zookeeper/conf/zoo.cfg

**Comment by maxim-slavutsky** [comment]
Yes, thank you very much with new 3.8 image it works.
