### ISSUE TITLE
[bitnami/influxdb] Https problem with Influxdb

### ISSUE THREAD

**Issue by vssnake** [bitnami/charts#12854]
### Name and Version

bitnami/influxdb 5.4.6

### What steps will reproduce the bug?

When you need to enable "HTTPS", the documentation shows the values to put to enable "HTTPS" but doesn't work. I keep looking at the code and found the error. 

In the ingress.yaml at line 57 you have the `ingress.certManager` value but in the documentation doesn't show anymore because is deprecated.
```
{{- if or (and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned)) .Values.ingress.extraTls }}
```

I put `ingress.certManager` value to true in my yaml at it works.

### What is the expected behavior?

You have access through HTTPS

### What do you see instead?

You only have access through HTTP and HTTPS with Kubernetes certificates.

**Comment by fmulero** [comment]
Thanks a lot @vssnake for reporting it and identify where is the problem. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by cleverhu** [comment]
@fmulero PTAL

**Comment by carrodher** [comment]
Thanks for creating the associated PR, the team will take a look and provide feedback
