### ISSUE TITLE
[bitnami/etcd] liveness/readiness checks fail for all nodes if one node is down

### ISSUE THREAD

**Issue by pantaoran** [bitnami/charts#1286]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Which chart**:

etcd

**Description**

The liveness and readiness checks of this chart seem completely broken by design to me when running this as a statefulset on Kubernetes. The script executes the `etcdctl endpoint health` command with all configured nodes listed in the `ETCDCTL_ENDPOINTS` environment variable. The consequence of this is that when one pod is temporarily down (a normal occurrence on Kubernetes), then the liveness and readiness checks of every single pod in the etcd cluster will fail! So any pod going down will tear down the whole cluster.

The idea of liveness and readiness checks on Kubernetes is to have a customized method to determine when a pod needs to be removed/restarted (liveness check) or when a pod should not receive traffic because it's not ready (readiness check). This must be pod-specific, otherwise it defeats the purpose of its existence.

**Steps to reproduce the issue:**

1. Spin up a statefulset with 3 replicas and liveness checks enabled
2. Wait for the cluster to initialize
3. Scale the statefulset down to 2 replicas

**Describe the results you received:**

All cluster pods go into a crash loop as soon as the next liveness check executes.

**Describe the results you expected:**

The liveness of the remaining 2 pods should be OK and the cluster should continue to serve clients.

**Additional information you deem important:**

For full transparency I'll say that I'm not using Tiller at all because I don't have enough permissions on our corporate Kubernetes cluster for that. I'm only using the templating engine of Helm to create the manifests locally and then submit those via kubectl, but that shouldn't matter for this bug that I'm reporting.

I have tried with and without persistence (I also found separate bugs in that, but if I decide to report those it will be in a separate issue. 

I have `allowNoneAuthentication: true` set during my experiments, but RBAC is enabled.

Metrics and disasterRecovery are off.

**Version of Helm and Kubernetes**:

I'm using this the bitnami etcd docker image with the tag `3.3.13-debian-9-r44` for this.

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Error: Get https://redacted/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: Not Found
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pantaoran** [comment]
This bug is very closely related to my other submission at #1287
Whoever tries to fix one should also think about the other.

**Comment by andresbono** [comment]
Hi @pantaoran, thanks for this valuable feedback. We will try to reproduce it on our side and we will update the chart to address the issue.

Thanks again!
