### ISSUE TITLE
[bitnami/etcd] Cluster cannot start with readiness checks configured

### ISSUE THREAD

**Issue by pantaoran** [bitnami/charts#1287]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Which chart**:

etcd

**Description**

I'm trying to spin up a brand new cluster of etcd (3 replicas), with readiness checks set to enabled. I cannot seem to do it though, because the failing readiness check of the first pod prevents the statefulset from starting the second pod, and as long as the second pod is not started the readiness check cannot succeed. It's a chicken and egg problem.

The readiness checks of this chart seem completely broken by design to me when running this as a statefulset on Kubernetes. The script executes the `etcdctl endpoint health` command with all configured nodes listed in the `ETCDCTL_ENDPOINTS` environment variable. The consequence of this is that when only the first node is up during a normal startup sequence, then the readiness checks can never succeed since it only succeeds when the whole cluster is up and healthy.

The idea of readiness checks on Kubernetes is to have a customized method to determine when a single pod should start to receive traffic because it's ready. This must be pod-specific, otherwise it defeats the purpose of its existence.

**Steps to reproduce the issue:**

1. Install this chart with 3 replicas and readiness checks enabled

**Describe the results you received:**

The first pod/replica will never be viewed as ready, so the 2nd and 3rd pods will never be started.

**Describe the results you expected:**

All 3 pods should come up in sequence as intended by the rules of the statefulset.

**Additional information you deem important:**

For full transparency I'll say that I'm not using Tiller at all because I don't have enough permissions on our corporate Kubernetes cluster for that. I'm only using the templating engine of Helm to create the manifests locally and then submit those via kubectl, but that shouldn't matter for this bug that I'm reporting.

I have tried with and without persistence (I also found separate bugs in that, but if I decide to report those it will be in a separate issue. 

I have `allowNoneAuthentication: true` set during my experiments, but RBAC is enabled.

Metrics and disasterRecovery are off.

**Version of Helm and Kubernetes**:

I'm using this the bitnami etcd docker image with the tag `3.3.13-debian-9-r44` for this.

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Error: Get https://redacted/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: Not Found
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pantaoran** [comment]
This bug is very closely related to my other submission at #1286
Whoever tries to fix one should also think about the other.

**Comment by andresbono** [comment]
Hi @pantaoran, as said in #1286, we will investigate these two issues and we will get back to you.
