### ISSUE TITLE
[bitnami/grafana-operator] update crds to 4.7.0

### ISSUE THREAD

**Issue by Jeremy-Boyle** [bitnami/charts#12875]
### Name and Version

bitnami/grafana-operator

### What steps will reproduce the bug?

Upstream has updated to 4.7.0, this is causing the operator to fail on deployment because a new resource called GrafanaFolder was introduced.

### What do you see instead?

Grafana Operator is in crashloop backoff due to missing CRD 

### Additional information

How can this be automated / Improved for the future ?

I've noticed that this issue seems to happen frequently between multiple bitnami charts, sometimes breaking functionality until its updated. My suggestion is that some sort of automation should be created with resources that require CRDS, and or some e2e testing to ensure the stability of resources.

#12308
#12285
#11344
#10860

**Comment by juan131** [comment]
I'm also hitting this issue after upgrading to latest chart version. cc @carrodher
