### ISSUE TITLE
[bitnami/discourse] New local install of Discourse has multiple CSP errors

### ISSUE THREAD

**Issue by stevejr** [bitnami/charts#12906]
### Name and Version

bitnami/discourse-8.1.8

### What steps will reproduce the bug?

1. Create new Minikube environment
2. Create new namespace `discourse`
3. Install discourse - `helm install discourse bitnami/discourse --set serviceAccount.create=true --set serviceAccount.name=discourse --namespace=discourse`
4. Once discourse pod is started do `kubectl port-forward --namespace discourse svc/discourse 80:8080`

### Are you using any custom parameters or values?
```
--set serviceAccount.create=true 
--set serviceAccount.name=discourse 
--namespace=discourse
```
### What is the expected behavior?

Discourse should start and be accessible

### What do you see instead?
```
[Error] Refused to load http://localhost:51532/assets/start-discourse-330ecabb99d562b3be656b4bfb638312addb2e0ee5f5780aa47d519efd0b53f4.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load http://localhost:51532/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load http://localhost:51532/assets/browser-detect-16ca87077aead9f656700e192992122d3a7eee8c1bb76da992127945464d4777.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/locales/en-7d6e2ddc656f2dfbcb23552c15fdcecb07dbbd0ca23e64bb314a9aa8de499a10.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/vendor-e356674b67559130cbeca4530a0a5a00e71144f5e7556902f8a5efc8ac3f2282.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/application-ac4559e6c00dd9dba9d43d1d45d2ae68f856d62dbf2cf8586ad869941beeb2f9.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/plugins/discourse-details-a5c71c75398c735e851440262e3c9ba43f9d8a2a7d81d8ecec16c8b2dbf452c3.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/plugins/discourse-local-dates-1174dd8ec34df1ac87004a7699b363e4bca1e3acae8e1bf5133051ab4956fea5.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/plugins/discourse-narrative-bot-7648c8e9699610bc9a41dc34d627f0227a7501feb863a8d84ec0ab1bdc745e3d.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/plugins/discourse-presence-bc826a395189b32e4676ad0c4414f821f9bab8245747789b6d555fc16581dacd.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/plugins/lazy-yt-362fd991a752ebdc53b9b3b70aea43cb46676f634c323d6c79c0bef4c6bebad3.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/plugins/poll-3dc2e1034f464aa9411181503b8e1d9c52d1a76a8e70e93aaf1c4bdf320b3409.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] Refused to load http://localhost:51532/assets/start-discourse-330ecabb99d562b3be656b4bfb638312addb2e0ee5f5780aa47d519efd0b53f4.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load http://localhost:51532/assets/browser-update-eec13eb6f8386f18f10b5dd6ebb7a3598d28421bb796e539b91a7e4a4c5d4c08.js because it does not appear in the script-src directive of the Content Security Policy.
```

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

As a side-note, I was unable to reproduce the issue, I was able to install the chart without problems.

**Comment by stevejr** [comment]
Thanks for the update.

Can I ask what k8s cluster type you installed the chart into and did you use port-forwarding or create an ingress for the chart?

**Comment by javsalgar** [comment]
Hi,

Same environment as you. Minikube and port-forwarding.

**Comment by stevejr** [comment]
Hmmm, interesting. Will give it another try.

**Comment by mikeseese** [comment]
@stevejr I know it's been awhile, but did you get this to work?

**Comment by mikeseese** [comment]
False alarm. Sorry for the useless necro 😅 Not sure how to trigger @bitnami-bot to mark this as solved again.

The `host` parameter must be set to the exact host you're going to use in the dev environment (i.e. if you're going to portforward 8080 and access it from localhost, host should be `localhost:8080`).

In addition to not having it set correctly, I had misconfigured it to be `auth.host` instead of just `host`.
