### ISSUE TITLE
[bitnami/redis-cluster] Need to know how can we downscale the redis cluster

### ISSUE THREAD

**Issue by cmreddyv** [bitnami/charts#12921]
### Name and Version

btnami/redis-cliuster 6.2.6

### What steps will reproduce the bug?

1. Create a cluster with 9 masters and no replication
2.  Change the number of nodes to 3 nodes i.e. we want to reduce the over provisioned cluster
3. manually tried to rebalance the cluster, rebalance is failing because as the pods got deleted because of the step 2 and the config has the ip of the deleted pods

### What do you see instead?

cluster is going to un useful state

**Comment by fmulero** [comment]
Hi @cmreddyv 

Have you taken a look into [Scale down the cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#scale-down-the-cluster)?
