### ISSUE TITLE
[bitnami/rabbitmq] Using loadDefinition feature has become impossible

### ISSUE THREAD

**Issue by g-chcht** [bitnami/charts#12924]
### Name and Version

bitnami/rabbitmq 11.0.0

### What steps will reproduce the bug?

set `.Values.loadDefinition.enabled` to true

### Are you using any custom parameters or values?

no

### What is the expected behavior?

Being able to load definition from json file

### What do you see instead?

Rabbitmq engine does not start. Error message is :
`rabbitmq 15:25:39.90 ERROR ==> The RABBITMQ_LOAD_DEFINITIONS and RABBITMQ_SECURE_PASSWORD environment variables cannot be enabled at once.`

### Additional information

RABBITMQ_SECURE_PASSWORD is hardcoded to "yes" here:
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/statefulset.yaml#L226

Should be a variable to be able to set it to "no" so we could use load definition feature

**Comment by aoterolorenzo** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by cleverhu** [comment]
I'd like to fix it!
