### ISSUE TITLE
[bitnami/metallb] Mismatched container versions in last automatic update

### ISSUE THREAD

**Issue by mac-chaffee** [bitnami/charts#12922]
### Name and Version

bitnami/metallb 4.1.6

### What steps will reproduce the bug?

1. `helm install -n metallb-system metallb bitnami/metallb --version 4.1.6`
2. Observe that the controller is running version `0.13.6-debian-11-r0` but the speakers are running version `0.13.5-debian-11-r13`

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

When a new version of metallb is released, both the speaker and the controller should be updated at the same time. That way you don't get versions of the chart that contain potentially incompatible versions.

### What do you see instead?

This commit didn't seem to upgrade the speaker image correctly: https://github.com/bitnami/charts/commit/8c7d49707b1dd84362e10376461c1777448f7d5b

Even though the underlying image did get updated to 0.13.6: https://github.com/bitnami/containers/pull/9825

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! It seems that version 4.1.7 now has all its dependencies in place.
