### ISSUE TITLE
[bitnami/kube-prometheus] Duplicate kubelet-0|1 target, bug or working as intended?

### ISSUE THREAD

**Issue by sheperdsonbrown** [bitnami/charts#12953]
### Name and Version

bitnami/8.0.16

### What steps will reproduce the bug?

I made sure to delete any old k8s services left in kube-system which could be causing the duplicate target as investigated here: https://github.com/prometheus-community/helm-charts/issues/614#issuecomment-1083572953

There are still two instances of kubelet-0, kubelet-1. I can see that one of the jobs references cadvisor while the other is only for kubelet. Initially I thought this was duplicated metrics which would be causing some performance impact, but is this working as intended?

Other helm charts have taken this into consideration, and removed any service monitor from appearing to have duplicates like so: https://github.com/prometheus-community/helm-charts/blob/53f1ae41247976fae3bba6b4e5acc9138f58aeca/charts/kube-prometheus-stack/values.yaml#L856-L861

### Are you using any custom parameters or values?

values.yaml

### What is the expected behavior?

Only have one kubelet-0 displayed, unless this is working as intended

![image](https://user-images.githubusercontent.com/16447427/195694236-6d9ce7b6-b483-42ba-b783-800eff5a5bd4.png)

### What do you see instead?

Duplicated entries

![image](https://user-images.githubusercontent.com/16447427/195692790-503e4dd9-2bc7-4fc0-af92-f293fbcd5469.png)

**Comment by fmulero** [comment]
I assume this issue related to the [bitnami/kube-prometheus](https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus) chart.

Please @sheperdsonbrown amend me if I am wrong

**Comment by sheperdsonbrown** [comment]
> I assume this issue related to the [bitnami/kube-prometheus](https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus) chart.
> 
> Please @sheperdsonbrown amend me if I am wrong

That is correct

**Comment by fmulero** [comment]
I've got your point.

It seems you have more or less clear where is the issue and we are not able to provide a ETA at the momento to solve this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by CeliaGMqrz** [comment]
Hi @sheperdsonbrown, 

Thank you for your patience. A new version of the chart has been released. You can now disable the endpoint related to `kubelet.serviceMonitor.cAdvisor`. Replying to your latest question:

> Duplicate kubelet-0|1 target, bug, or working as intended?

There is no duplication, it is intended for both endpoints to show separated metrics. Nevertheless, we have changed the logic so you can deactivate the metrics of cAdvisor if you want.
