### ISSUE TITLE
[bitnami/redis] master.count Not works

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#12969]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

master.count Not works in redis chart.

### What do you see instead?

There isn't any document for architecture that have multiple masters and when I set master.count to the value above of 1, this doesn't work and It set replicas=1.

**Comment by javsalgar** [comment]
Hi,

Did you check this section on the README? https://github.com/bitnami/charts/tree/master/bitnami/redis#multiple-masters-experimental

**Comment by arezvani** [comment]
@javsalgar  Yes but it doesn't work. I have set master.count to 3 and after that I have just 1 master. 
I have 3 master and 3 worker in k8s.

**Comment by javsalgar** [comment]
Could you share the exact set of values that you changed? Including the affinity settings
