### ISSUE TITLE
[bitnami/redis] Error accepting a client SSL connection

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#12967]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

I use that:
```
helm install my-release bitnami/redis --set global.storageClass=rook-cephfs --set global.redis.password=1234 --set master.count=3 --set tls.enabled=true --set tls.autoGenerated=true
```

I got this error:
```
Error accepting a client connection: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
```

### What do you see instead?

I need to replica that can successfully connect to the master and I can have an SSL connection to Redis after that.

**Comment by fmulero** [comment]
Hi @arezvani 

Could you provide instructions to reproduce the issue? I'm not able to reproduce it with the information above

**Comment by arezvani** [comment]
Hi @fmulero 
I didn't do anything more. I just use that command and after that I get that error.

**Comment by fmulero** [comment]
Sorry @arezvani  but we'd need concrete steps to reproduce the error.

Where are you seeing this error? in an external client? How did you configure the connection? have you  configure the autogenerated cert?

**Comment by arezvani** [comment]
@fmulero I use this command:

helm install my-release bitnami/redis --set global.storageClass=rook-cephfs --set global.redis.password=1234 --set master.count=3 --set tls.enabled=true --set tls.autoGenerated=true

In logs of pods, I see that
If I want to create certificates what should I do?
What is the best and easiest and fastest solution for do this job?

**Comment by fmulero** [comment]
I am assuming you are seeing the error when you are trying to connect to the cluster.

`tls.authClients` is enabled by default, this means that clients have to use a certificate to authenticate (This is also the [default behaviour in Redis](https://redis.io/docs/manual/security/encryption/#client-certificate-authentication)). This authentication is against the trusted root CA configured, so if you are running this:

```console
helm install my-release bitnami/redis --set global.storageClass=rook-cephfs --set global.redis.password=1234 --set master.count=3 --set tls.enabled=true --set tls.autoGenerated=true
```

You have to export the autogenerated certs and use them in your clients (Please note this is not a good practice, we recommend you use your own CA to manage properly the client certificates):

```
$ kubectl get secret my-release-redis-crt -o "jsonpath={.data['ca\.crt']}" |base64 -d > ca.crt
$ kubectl get secret my-release-redis-crt -o "jsonpath={.data['tls\.crt']}" |base64 -d > tls.crt
$ kubectl get secret my-release-redis-crt -o "jsonpath={.data['tls\.key']}" |base64 -d > tls.key
```

Create a client a copy the certificates into the new pod:

```
$ kubectl run --namespace default redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image docker.io/bitnami/redis:7.0.5-debian-11-r7 --command -- sleep infinity
$ kubectl cp --namespace default ./tls.crt  redis-client:/tmp/tls.crt
$ kubectl cp --namespace default ./tls.key redis-client:/tmp/tls.key
$ kubectl cp --namespace default ./ca.crt redis-client:/tmp/ca.crt
$ kubectl exec --tty -i redis-client  --namespace default -- bash
I have no name!@redis-client:/$ REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h my-release-redis-master --tls --cert /tmp/tls.crt --key /tmp/tls.key --cacert /tmp/ca.crt
my-release-redis-master:6379> PING
PONG
```

About your questions:

> If I want to create certificates what should I do?
> What is the best and easiest and fastest solution for doing this job?

The answer will depend on your case of use and your requirements. If you want to use TLS only to encrypt the traffic in a development environment without any kind of requirement about the certificates or protocols used, I'd deploy my cluster with the following command:

```console
helm install my-release bitnami/redis --set global.redis.password=1234 --set master.count=3 --set tls.enabled=true --set tls.autoGenerated=true --set tls.authClients=false
```
In this case I'd need to export only the CA and use it in my clients (I don't need the private certificate and key to stablish the connection). More information [here](https://github.com/bitnami/charts/tree/main/bitnami/redis#securing-traffic-using-tls)
