### ISSUE TITLE
Kong chart is missing latest changes to CRD

### ISSUE THREAD

**Issue by jeroen-vankelecom** [bitnami/charts#12971]
### Name and Version

bitnami/kong 

### What steps will reproduce the bug?

1. create an empty cluster (e.g. `k3d cluster create test`)
2. install the latest bitnami/kong chart (`helm install -n kong --create-namespace kong --version 7.0.0 bitnami/kong`)
3. check the logs of the ingress-controller:
```
error="no matches for kind \"IngressClassParameters\" in version \"configuration.konghq.com/v1alpha1\"
...
Error: failed to wait for KongV1Alpha1IngressClassParameters caches to sync: timed out waiting for cache to be synced
```
4. Readiness probe on kong pods will fail as well, resulting in restarts.
```
Warning  Unhealthy  3m4s (x6 over 3m54s)  kubelet    Readiness probe failed: /health/kong-container-health.sh: line 12: kong_env: command not found 
```

### What is the expected behavior?

Kong Pods are stable, and the IngressClassParameters CRD exists.

### What do you see instead?

```
error="no matches for kind \"IngressClassParameters\" in version \"configuration.konghq.com/v1alpha1\"
...
Error: failed to wait for KongV1Alpha1IngressClassParameters caches to sync: timed out waiting for cache to be synced
```

### Additional information

Check this commit to see the latest changes to CRDs in Kong: https://github.com/Kong/charts/commit/d3b799e4ef0c66ee2040beda7146fc792e941c4d

**Comment by carrodher** [comment]
Thanks for letting us know, we just created the above PR updating the CRDs
