### ISSUE TITLE
create extension and cron jobs on initdb

### ISSUE THREAD

**Issue by ricardonunosr** [bitnami/charts#12983]
### Name and Version

bitnami/postgres 14.2.0

### What steps will reproduce the bug?

1. Created a values.yaml with custom script initdb(primary.initdb.scripts) 
2. Also present in values.yaml   ``postgresqlSharedPreloadLibraries: "pg_cron,pgaudit"``
3. Do helm upgrade
4. See extension failed to create and setup cron jobs

### Are you using any custom parameters or values?

```yaml
...
postgresqlSharedPreloadLibraries: "pg_cron,pgaudit"
...
primary:   
 initdb:
      scripts:
        create_extension.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRESQL_PASSWORD
          
          # Set up pg_cron in its default db, postgres 
          psql -Upostgres postgres << EOF
          SHOW shared_preload_libraries;
          CREATE EXTENSION IF NOT EXISTS pg_cron;
          EOF

          # Schedule pg_cron in its default db 
          psql -Upostgres -d postgres << EOF
          GRANT USAGE ON SCHEMA cron TO postgres;
          SELECT cron.schedule_in_database('table0', '*/45 * * * *',
          'SELECT update_table0_table();', 'postgres');
          SELECT cron.schedule_in_database('table1', '*/25 * * * *',
          'SELECT update_table1_table();', 'postgres');
          EOF
...
```

### What is the expected behavior?

I expect the pg_cron extension to be created and cron jobs setup.

### What do you see instead?

``ERROR: pg_cron can only be loaded via shared_preload_libraries``
``HINT:Add pg_cron to the shared_preload_libraries configuration variable in postgresql.conf``

### Additional information

From what i see when postgres is started in the background the shared_preload_libraries aren't still available (from the output of ``SHOW shared_preload_libraries``). Is this normal behavior? if so what it is the correct solution to have the cron jobs setup on creation?

**Comment by ricardonunosr** [comment]
Any updates on this?

**Comment by CeliaGMqrz** [comment]
Hi @ricardonunosr 

Sorry for the delay. I have been able to reproduce the issue. It seems that the `pg_cron` module is not included in our image but you can apply the solution listed [here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/64#issuecomment-810350150). 

If you have any other problems, please do not hesitate to contact us on this issue.

Thanks for your comments.

**Comment by ricardonunosr** [comment]
Hi @CeliaGMqrz 
yes i already previous have installed pg_cron in the image as that issue suggested.

My DockerFile
```
FROM bitnami/postgresql:14.2.0
...
## Install pg_cron
RUN install_packages postgresql-14-cron \
    && cp /usr/lib/postgresql/14/lib/pg_cron.so /opt/bitnami/postgresql/lib \
    && cp /usr/share/postgresql/14/extension/pg_cron* /opt/bitnami/postgresql/share/extension \
    && chmod +x /opt/bitnami/postgresql/lib/pg_cron.so
...
```

The extension is installed is just not being loaded at startup with postgres, causing the init script to fail.

**Comment by lvillaca** [comment]
> Hi @CeliaGMqrz yes, I already previous have installed `pg_cron` in the image as that issue suggested.
> 
> My DockerFile
> 
> ```dockerfile
> FROM bitnami/postgresql:14.2.0
> ...
> ## Install pg_cron
> RUN install_packages postgresql-14-cron \
>     && cp /usr/lib/postgresql/14/lib/pg_cron.so /opt/bitnami/postgresql/lib \
>     && cp /usr/share/postgresql/14/extension/pg_cron* /opt/bitnami/postgresql/share/extension \
>     && chmod +x /opt/bitnami/postgresql/lib/pg_cron.so
> ...
> ```
> 
> The extension installed is just not being loaded at startup with postgres, causing the init script to fail.

Hi, I am also facing the same issue. I tried the same process as mentioned above and the extension fails to be created with the indicated error below:
`ERROR: pg_cron can only be loaded via shared_preload_libraries`
This only happens for the script that runs within initdb. After postgres is restarted the postgres extension is created (so postgresqlSharedPreloadLibraries is not working at that moment).

Any updates?

**Comment by CeliaGMqrz** [comment]
Hi @ricardonunosr @lvillaca 

Sorry for the delay.

Thanks for reporting this. We found a bug, the Postgres initScripts are not using the final configuration. I have created an internal task to investigate this. We'll leave this issue on-hold until our dev team works on the related task.

Alternatively, you can create a job with `extraDeploy`, so you can run your script.

**Comment by ricardonunosr** [comment]
Hi @CeliaGMqrz, from what i understand a job creates a separate pod that we can run. How would you suggest to run a script inside the postgres pod and not inside this "job pod". 

Thanks in advance

**Comment by rafariossaa** [comment]
A new release of the postgresql images was made that includes an update that enabled this usage.

Could you try the following steps:

- Create the a new image that enables pg_cron by using:
```
$ cat $ cat Dockerfile_mypgcron
FROM  bitnami/postgresql:13.9.0-debian-11-r11

USER root

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        postgresql-13-cron \
    && rm -rf /var/lib/apt/lists/ \
    && cp /usr/lib/postgresql/13/lib/pg_cron.so /opt/bitnami/postgresql/lib \
    && cp /usr/share/postgresql/13/extension/pg_cron* /opt/bitnami/postgresql/share/extension \
    && chmod +x /opt/bitnami/postgresql/lib/pg_cron.so

USER 1001


$ docker build -t mypgcron:v13 -f Dockerfile_myimg .
```

- Deploy the chart, (there was no changes in the values.yaml file. Note also the changes due to pg_cron version):
```
$ cat user.yaml
image:
  debug: true

postgresqlSharedPreloadLibraries: "pg_cron,pgaudit"

primary:
 initdb:
      scripts:
        create_extension.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRESQL_PASSWORD
          cat /opt/bitnami/postgresql/conf/postgresql.conf | grep shared_preload_libraries

          # Set up pg_cron in its default db, postgres
          psql -Upostgres postgres << EOF
          SHOW shared_preload_libraries;
          CREATE EXTENSION IF NOT EXISTS pg_cron;
          EOF

          # Schedule pg_cron in its default db
          psql -Upostgres -d postgres << EOF
          GRANT USAGE ON SCHEMA cron TO postgres;
          SELECT cron.schedule('nightly-vacuum', '0 10 * * *', 'VACUUM');
          EOF
          # SELECT cron.schedule_in_database('table0', '*/45 * * * *','SELECT update_table0_table();', 'postgres');
          # SELECT cron.schedule_in_database('table1', '*/25 * * * *','SELECT update_table1_table();', 'postgres');
          #EOF



$ helm install mypgcron -f values.yaml -f user.yaml --set image.repository=mypgcron --set image.tag=v13 .
```

- Check the jobs:
```
$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default mypgcron-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)

$ kubectl run mypgcron-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/mypg:v13-2 --env="PGPASSWORD=$POSTGRES_PASSWORD"       --command -- psql --host mypgcron-postgresql -U postgres -d postgres -p 5432 -c "select * from cron.job;"

 jobid |  schedule  | command | nodename  | nodeport | database | username | active |    jobname
-------+------------+---------+-----------+----------+----------+----------+--------+----------------
     1 | 0 10 * * * | VACUUM  | localhost |     5432 | postgres | postgres | t      | nightly-vacuum
(1 row)

pod "mypgcron-postgresql-client" deleted
```

**Comment by ricardonunosr** [comment]
@rafariossaa thank you so much for your effort , question but why do i have to use the postgres 13 image? I'm currently using the `bitnami/postgresql:14.2.0` i would like to use version 14 for other reasons. Is it because you did a fix on that specific version?

**Comment by rafariossaa** [comment]
Hi,
  It is because the method used to add pg_cron, building a new image that adds the extension using `bitnami/postgresql` as base for that new image.
  The image `bitnami/postgresql:14.2.0` [uses](https://github.com/bitnami/containers/blob/main/bitnami/postgresql/14/debian-11/Dockerfile) `bitnami/minideb:bullseye` as base, and if you try:
```
$ docker run -it bitnami/minideb:bullseye bash

# install_packages postgresql-14-cron
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package postgresql-14-cron
apt failed, retrying
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package postgresql-14-cron
apt failed, retrying
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package postgresql-14-cron


root@8db14c34dc25:/# apt-cache search postgresql | grep -i cron
postgresql-13-cron - Run periodic jobs in PostgreSQL
```
  You can see that there is not package for `postgresql-14-cron`. If you try to use `postgresql-13-cron` with postgresql v14 you will get errors (missing symbols and such).

**Comment by ricardonunosr** [comment]
@rafariossaa Just tried and it successfully created the extension on startup. Thanks for your efforts :100:
