### ISSUE TITLE
Error: parse error at (jupyterhub/templates/_helpers.tpl:38): function "dig" not defined

### ISSUE THREAD

**Issue by KevinMcCoy4119** [bitnami/charts#12996]
### Name and Version

bitnami/jupyterhub

### What steps will reproduce the bug?

std install will reproduce the error:

Error: parse error at (jupyterhub/templates/_helpers.tpl:38): function "dig" not defined

install:
```console
$ helm repo add my-repo https://charts.bitnami.com/bitnami
$ helm install my-release my-repo/jupyterhub
```
### Are you using any custom parameters or values?

No

### What is the expected behavior?

Install

### What do you see instead?
```console
$ helm repo add my-repo https://charts.bitnami.com/bitnami
"my-repo" has been added to your repositories

$ helm install my-release my-repo/jupyterhub
Error: parse error at (jupyterhub/templates/_helpers.tpl:38): function "dig" not defined
```

**Comment by carrodher** [comment]
Can you run the `helm version` command and check if your version is not too old?
Usually, this kind of issue is related to old versions of the Helm CLI and you should update to a more recent one. [Here](https://github.com/helm/helm/releases) you can find the Helm releases page
