### ISSUE TITLE
[bitnami/kong] Chart does not include RBAC role for new CRDs

### ISSUE THREAD

**Issue by jeroen-vankelecom** [bitnami/charts#13005]
### Name and Version

bitnami/kong 7.0.1

### What steps will reproduce the bug?

1. create an empty cluster (e.g. k3d cluster create test)
2. install the latest bitnami/kong chart (helm install -n kong --create-namespace kong --version 7.0.0 bitnami/kong)
3. check the logs of the ingress-controller

The controller crashes as it has no permissions to watch the new `ingressClassParameterses` CRD.

### Are you using any custom parameters or values?

default chart values

### What do you see instead?

The ingress controller logs show it cannot list the `ingressClassParameterses` resource:
```
User "system:serviceaccount:kong:kong" cannot list resource "ingressclassparameterses" in API group "configuration.konghq.com" at the cluster scope
```

### Additional information

Seems this permission is missing:
https://github.com/Kong/charts/blob/main/charts/kong/templates/_helpers.tpl#L1080-L1087

**Comment by fmulero** [comment]
Fixed in #13095
