### ISSUE TITLE
users created in redis will delete after pod restart

### ISSUE THREAD

**Issue by nishantgreendeck** [bitnami/charts#13007]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

Add the bitnami helm repo by `helm repo add bitnami https://charts.bitnami.com/bitnami`
Install Redis by `helm install redis bitnami/redis`
Now go inside Redis container by `kubectl exec -it redis-master-0 bash`
Connect with Redis by `redis-cli --pass <password> --user default -h localhost`
Create a new user in Redis by command `ACL SETUSER username on allkeys +@all +SADD >password`.
Now, if we run the command `ACL LIST`,  user created above will be visible but if I delete/restart the pod user created by `ACL SETUSER` will be lost.

### Are you using any custom parameters or values?
```yaml
architecture: standalone
master:
  count: 1
```

### What is the expected behavior?

users created by `ACL createuser` should be available even if the pod restart.

### What do you see instead?

users created by `ACL createuser ......` are not available after the pod restarts.

**Comment by carrodher** [comment]
I was not able to reproduce the issue. I installed the Helm chart with the mentioned values by running:
```console
$ helm install redis bitnami/redis --set architecture=standalone --set master.count=1
```

Then, I followed the process described in the installation notes in order to access Redis:
```console
$ export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 -d)
$ kubectl run --namespace default redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD  --image docker.io/bitnami/redis:7.0.5-debian-11-r7 --command -- sleep infinity
pod/redis-client created
$ kubectl exec --tty -i redis-client --namespace default -- bash
I have no name!@redis-client:/$ REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis-master
redis-master:6379>
```

Now, I executed the commands you suggested:
```console
redis-master:6379> ACL LIST
1) "user default on #1b3f7b12f17ddfd5e3b22577b67189dbe23321ccc22bcf6ea81340011b5a6053 ~* &* +@all"

redis-master:6379> ACL SETUSER username on allkeys +@all +SADD >password
OK

redis-master:6379> ACL LIST
1) "user default on #1b3f7b12f17ddfd5e3b22577b67189dbe23321ccc22bcf6ea81340011b5a6053 ~* &* +@all"
2) "user username on #5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 ~* resetchannels +@all"
```

Now I restarted the pod by running
```console
$ kubectl get statefulset
NAME           READY   AGE
redis-master   1/1     5m36s
$ kubectl get pods
NAME             READY   STATUS    RESTARTS   AGE
redis-master-0   1/1     Running   0          6m18s

$ kubectl rollout restart sts/redis-master
statefulset.apps/redis-master restarted

$ kubectl get statefulset
NAME           READY   AGE
redis-master   0/1     7m7s
$ kubectl get pods
NAME             READY   STATUS    RESTARTS   AGE
redis-master-0   0/1     Running   0          5s 
```

Once restarted the data is present since it lives in the PV
```console
$ kubectl get pvc
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
redis-data-redis-master-0   Bound    pvc-9d170d47-3df0-4506-a62a-a128a939ac55   8Gi        RWO            standard       10m
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS   REASON   AGE
pvc-9d170d47-3df0-4506-a62a-a128a939ac55   8Gi        RWO            Delete           Bound    default/redis-data-redis-master-0   standard                10m
```

What is the process you are following to restart the pod?

**Comment by nishantgreendeck** [comment]
i use "kubectl delete pod redis-master-0" to delete the pod.

**Comment by nishantgreendeck** [comment]
connect to redis and run command "ACL LIST", user that you created manually after installing the redis will be lost

**Comment by breimers** [comment]
Can confirm

From application connecting to Redis:
`redis.exceptions.ResponseError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?`

From Redis-cli:
Before restart
```
127.0.0.1:6379> CONFIG SET requirepass "PpzkEnIT8S"
OK
127.0.0.1:6379> AUTH PpzkEnIT8S
OK
```
After restart
```
127.0.0.1:6379> AUTH PpzkEnIT8S
(error) ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
127.0.0.1:6379> CONFIG SET requirepass "PpzkEnIT8S"
OK
127.0.0.1:6379> AUTH PpzkEnIT8S
OK
127.0.0.1:6379> command terminated with exit code 137
```

**Comment by nishantgreendeck** [comment]
yes

**Comment by fmulero** [comment]
Sorry @nishantgreendeck

I am not able to reproduce your issue neither. Could your check your default storage class? Are volumes removed?
