### ISSUE TITLE
[bitnami/wordpress] Env for wp_home and wp_siteurl

### ISSUE THREAD

**Issue by corincorvus** [bitnami/charts#13018]
### Name and Version

bitnami/wordpress:6

### What is the problem this feature will solve?

At the moment i need to change the config.php after rollout, cause by example the Plugin Jetpack every time identify the Docker IP Address and goes in Safe Mode.
https://jetpack.com/support/safe-mode/

### What is the feature you are proposing to solve the problem?

If i can add wp_home and wp_siteurl in env, i dont have this problem.

### What alternatives have you considered?

If i can use another way, pls tell me.

**Comment by corincorvus** [comment]
Hey,

may this error is the root of the problem?
cURL error 7: Failed to connect to webaddress port 443: Connection refused

If i go in the pod i can curl google.com, but i cant curl my website on https or http.

Crons dont run with this error message.
(Plugin wp control tell me this)

I remove the wp-config configmap of my website now. Jetpack went in safe mode instantly. 

How i add the wp_home and siteurl correctly in the wordpressConfiguration: ""?

I struggle with the syntax.

second i red the disctription but i wont skip the install:
```
## @param wordpressConfiguration The content for your custom wp-config.php file (advanced feature)
## NOTE: This will override configuring WordPress based on environment variables (including those set by the chart)
**## NOTE: Currently only supported when `wordpressSkipInstall=true`**
##
wordpressConfiguration: ""
```

**Comment by fmulero** [comment]
Sorry @corincorvus, 

I tried this scenario and the outcome is interesting:

1. Install wordpress helm chart
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install wordpress bitnami/wordpress
```
2. Enable port forwarding in kuberntes to access to the wordpress service:
```console
$ kubectl port-forward svc/wordpress 8080:80
```
3. Install jetpack plugin from console using http://localhost:8080
![image](https://user-images.githubusercontent.com/23502572/197194682-c153f347-3d38-489e-802f-3dfd75be7272.png)

4. In previous picture we can see the offline mode as you said, but What will happen if we use my hostname instead of localhost?
![image](https://user-images.githubusercontent.com/23502572/197195488-58b622a2-0534-48fd-9523-655a3e9c67f3.png)

The plugin offers the set up option but obviously it fails because my site is not public. This is the error I've got:
```json
{"code":"siteurl_private_ip","message":"Your site host \"ghost.local\" is on a private network. Jetpack can only connect to public sites.","data":400}
```

Could you share the instructions as detailed as you can to reproduce your issue?

**Comment by corincorvus** [comment]
Hey, yes for the Plugin you need a Website in the Internet, cause the Plugin check the availability and speedup or backup some things.

First i fill the Chart. Here are my Changes: 
```
wordpressUsername: user
## @param wordpressPassword WordPress user password
## Defaults to a random 10-character alphanumeric string if not set
##
wordpressPassword: "super safety password"
## @param existingSecret Name of existing secret containing WordPress credentials
## NOTE: Must contain key `wordpress-password`
## NOTE: When it's set, the `wordpressPassword` parameter is ignored
##
existingSecret: ""
## @param wordpressEmail WordPress user email
##
wordpressEmail: user@example.com
## @param wordpressFirstName WordPress user first name
##
wordpressFirstName: FirstName
## @param wordpressLastName WordPress user last name
##
wordpressLastName: LastName
## @param wordpressBlogName Blog name
##
wordpressBlogName: User's Blog!
## @param wordpressTablePrefix Prefix to use for WordPress database tables
##
wordpressTablePrefix: wp_
## @param wordpressScheme Scheme to use to generate WordPress URLs
##
wordpressScheme: http
---
---
## @param wordpressConfiguration The content for your custom wp-config.php file (advanced feature)
## NOTE: This will override configuring WordPress based on environment variables (including those set by the chart)
## NOTE: Currently only supported when `wordpressSkipInstall=true`
##
wordpressConfiguration: ""
---
---
smtpHost: "host"
smtpPort: "port"
smtpUser: "user"
smtpPassword: "password"
smtpProtocol: ""
## @param smtpExistingSecret The name of an existing secret with SMTP credentials
## NOTE: Must contain key `smtp-password`
## NOTE: When it's set, the `smtpPassword` parameter is ignored
##
smtpExistingSecret: ""
## @param allowEmptyPassword Allow the container to be started with blank passwords
##
allowEmptyPassword: false
---
---
ingress:
  ## @param ingress.enabled Enable ingress record generation for WordPress
  ##
  enabled: true
  ## @param ingress.pathType Ingress path type
  ##
  pathType: ImplementationSpecific
  ## @param ingress.apiVersion Force Ingress API version (automatically detected if not set)
  ##
  apiVersion: ""
  ## @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+)
  ## This is supported in Kubernetes 1.18+ and required if you have more than one IngressClass marked as the default for your cluster .
  ## ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
  ##
  ingressClassName: ""
  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: webdomain for the internet
---
---
mariadb:
  ## @param mariadb.enabled Deploy a MariaDB server to satisfy the applications database requirements
  ## To use an external database set this to false and configure the `externalDatabase.*` parameters
  ##
  enabled: true
  ## @param mariadb.architecture MariaDB architecture. Allowed values: `standalone` or `replication`
  ##
  architecture: standalone
  ## MariaDB Authentication parameters
  ## @param mariadb.auth.rootPassword MariaDB root password
  ## @param mariadb.auth.database MariaDB custom database
  ## @param mariadb.auth.username MariaDB custom user name
  ## @param mariadb.auth.password MariaDB custom user password
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mariadb#setting-the-root-password-on-first-run
  ##      https://github.com/bitnami/containers/blob/main/bitnami/mariadb/README.md#creating-a-database-on-first-run
  ##      https://github.com/bitnami/containers/blob/main/bitnami/mariadb/README.md#creating-a-database-user-on-first-run
  ##
  auth:
    rootPassword: "passsword"
    database: bitnami_wordpress
    username: bn_wordpress
    password: "passsword"
```
I dont change any other of the Chart.
![grafik](https://user-images.githubusercontent.com/21257329/197255181-6338265e-fe80-4d26-93b5-5037f53bf9f0.png)

I install the Chart and open the Website over the Service Port to check.
I add a config in my nginx reverse proxy with the service ports, cause i cant use traefik (double reverse proxy dont run good) and i tried to use the ingress connection, but it never worked.

Nginx Config:
HTTP:
```
server {
	listen 80;
	listen   [::]:80;
	server_name docu.domain.tld;
	client_max_body_size 20m;
	access_log            /var/log/nginx/docu-access.log adv;
	error_log            /var/log/nginx/docu-error.log notice;

    location /.well-known {
     root /var/www/letsencrypt;
    }    

    location / {
    return 301 https://docu.domain.tld$request_uri
;	}
}
```

HTTPS:
```
upstream docu {
	server 10.1.0.41:10002 weight=5;
	server 10.1.0.42:10002;
	server 10.1.0.43:10002 backup;
}


server {
	listen 443 ssl;
	listen   [::]:443;

	server_name docu.domain.tld;
	ssl_certificate           /root/.acme.sh/docu.domain.tld/fullchain.cer; 
	ssl_certificate_key       /root/.acme.sh/docu.domain.tld/docu.domain.tld.key;
	ssl_protocols TLSv1.2 TLSv1.3;
	client_max_body_size 200m;

	access_log            /var/log/nginx/docu-access.log adv;
	error_log            /var/log/nginx/docu-error.log notice;



	location / {
		proxy_pass          http://docu;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_redirect off;
	}


        # Enable output buffering
        try_files $uri = 404;
        fastcgi_buffering          on;
        fastcgi_buffer_size        4k;
        fastcgi_buffers            64 4k;
        fastcgi_max_temp_file_size 0;
        #gzip off;

}
```
Now the Website is available outside over the Webaddress. I can use the Webaddress i added in the nginx config, the same in the chart config for Ingress.

i install jetpack, configure jetpack, 
![grafik](https://user-images.githubusercontent.com/21257329/197256583-f7929ad2-5b46-474e-902b-b6e7d73408c0.png)


jetpack tell me after configure safe mode:
![grafik](https://user-images.githubusercontent.com/21257329/197256819-ea1e1669-001b-4993-b9a4-d7690ddb37b7.png)


The IP is the Pod IP of the Wordpress Pod.
![grafik](https://user-images.githubusercontent.com/21257329/197256940-9c59a483-d502-4a3d-8a3d-b881cd54b52d.png)

Site Health tell me, curl could not resolve host (if i add the configmap connection refused and cronjobs dont work anymore)
![grafik](https://user-images.githubusercontent.com/21257329/197257322-1ec9ac53-0406-4e49-802c-63f98a0f2810.png)

I hope you can find what i do wrong or fail of the deployment.

**Comment by fmulero** [comment]
It seems a DNS resolution problem, not sure how setting `wp_home` or `wp_siteurl` could solve it. Have you tried adding [hostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#adding-additional-entries-with-hostaliases)?

```yaml
hostAliases:
  - ip: <your public ip>
    hostnames:
    - <your fqdn name>
```

**Comment by corincorvus** [comment]
Yes i tried Hostalias. It didnt solve the Problem.

**Comment by fmulero** [comment]
To be honest I am not sure how can we help here. If you need to set explicitly WP_HOME and/or WP_SITEURL you can do it setting your [own wp-config.php](https://github.com/bitnami/charts/issues/13018#issuecomment-1283557285)

For information regarding the plugin itself; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

**Comment by corincorvus** [comment]
If i add my own config, the Install is skipped. What do the install? Its not described.

**Comment by corincorvus** [comment]
If i add the wordpressconfiguration and set true on skipinstallation the pod doesnt start:
wordpressconfiguration:"define('WP_SITEURL', 'http://test.domain.one');define('WP_HOME', 'http://test.domain.one');"

```
wordpress 05:32:32.57 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 05:32:32.59 WARN  ==> The WordPress configuration file '/opt/bitnami/wordpress/wp-config.php' is not writable. Configurations based on environment variables will not be applied for this file.
wordpress 05:32:32.65 INFO  ==> Restoring persisted WordPress installation
rm: cannot remove '/opt/bitnami/wordpress/wp-config.php': Device or resource busy
```

I didnt change any user or permissions

**Comment by fmulero** [comment]
It seems `wordpressConfiguration` and `existingWordPressConfigurationSecret` are not working as expected.

About the 'install', the `wordpressSkipInstall` value will skip the wizard installation. It means that you will need to configure everything in your `wp-config.php` and run the 'wp-cli' to install the site.
