### ISSUE TITLE
bitnami/mysql charts fails to deploy pod on an arm64 node with Ubuntu 22.04.1 LTS but not with Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by fernando-almeida-sprinklr** [bitnami/charts#13047]
### Name and Version

bitnami/mysql 9.4.1

### What steps will reproduce the bug?

Deploying the pod to a node with the following traits FAILS:
```
  Kernel Version:             5.15.0-1020-azure
  OS Image:                   Ubuntu 22.04.1 LTS
  Operating System:           linux
  Architecture:               arm64
  Container Runtime Version:  containerd://1.6.4+azure-4
  Kubelet Version:            v1.24.6
  Kube-Proxy Version:         v1.24.6
```
Deploying the pod to a node with the following traits WORKS:
```
  Kernel Version:             5.4.0-1091-azure
  OS Image:                   Ubuntu 18.04.6 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.4+azure-4
  Kubelet Version:            v1.24.6
  Kube-Proxy Version:         v1.24.6
```

The only differences I'm seeing are in the OS image being more recent and the Kernel version of the node is different.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The pod gets deployed to the node

### What do you see instead?

The pod keeps "Back-off restarting failed container" and I see the following log in the pod:
```
standard_init_linux.go:228: exec user process caused: exec format error
```
### Additional information

I'm assuming the open issue https://github.com/bitnami/charts/issues/7305 is no longer relevant as I have one of the images running on ARM64 or perhaps I'm misinterpreting something on that issue

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversations in a single place regarding ARM64 support.

This is totally related to this topic, you can see how the `Architecture` is different in both use cases. You can have some AMD containers running in ARM without issues, but others no; it will depend on the logic used by the application itself.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any news (when possible) about this topic.

**Comment by fernando-almeida-sprinklr** [comment]
Sorry I had misread arm64 and amd64 just noticed :(
Thanks for the quick reply

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
