### ISSUE TITLE
Redis password is not taking from secrets it  creates its own

### ISSUE THREAD

**Issue by resulraveendran** [bitnami/charts#13046]
### Name and Version

bitnami/redis  redis-17.3.5

### What is the problem this feature will solve?

I tried deploying redis using helm and I could also notice that the redis nodes are taking the default secrets of its own from the chart-configuration and not from secrets even though âexistingSecret: redis-config' parameter is added in the yaml file.

### What is the feature you are proposing to solve the problem?

is there any configuration to solve this

**Comment by javsalgar** [comment]
Hi!

Closing this as a duplicate of https://github.com/bitnami/charts/issues/13049
