### ISSUE TITLE
[bitnami/nginx-ingress-controller] Use existing service with load balancer instead of creating a new one

### ISSUE THREAD

**Issue by JustDoItSascha** [bitnami/charts#13042]
### Name and Version

bitnami/nginx-ingress-controller 9.3.18

### What is the problem this feature will solve?

Because the helm chart recommends to reinstall the whole chart when I want to upgrade from 7 to 9, I'm looking for a solution to reuse my existing load balancer.

### What is the feature you are proposing to solve the problem?

Would be nice if theres an option to create a service manually and to configure the helm chart to use this manually created service instead of creating a new one.

**Comment by JustDoItSascha** [comment]
@CeliaGMqrz I would, but I dont know how to solve this...

**Comment by CeliaGMqrz** [comment]
Sorry for the delay.  I am sorry to tell you that right now due to lack of resources we have no short-term mid-term plans to work on it. However, if this request becomes a big demand, we might consider prioritizing it.

Thank you for your comments.
