### ISSUE TITLE
[bitnami/tomcat] Unclear enforcement of tomcatPassword on upgrades

### ISSUE THREAD

**Issue by danielhass** [bitnami/charts#13048]
### Name and Version

bitnami/tomcat 10.4.3

### What steps will reproduce the bug?

Dear Maintainers, this is another attempt to bring the unfortunately closed issue #12296 and associated PR #12401 back to live.

Sadly due an office absence on my side I didn't notice in time that the `bitnami-bot` marked the issue as stale and closed it afterwards.

Multiple pings towards the maintainers haven't been answered yet.

Currently, the PR #12401 is pending a review from the maintainers. I'm happy to pick the work back up on this if anything needs to be change before this change can be considered and hopefully merged.

**Comment by javsalgar** [comment]
Hi!

We performed a change in the master branch, being `main` now, so it won't allow us to reopen the PR. Could you create a new one? Thank you so much!
