### ISSUE TITLE
Airflow Web BaseUrl cannot be set if ingress is configured

### ISSUE THREAD

**Issue by si-te** [bitnami/charts#13050]
### Name and Version

bitnami/airflow 13.1.7

### What steps will reproduce the bug?

Setting the `web.baseUrl` is ignored when an ingress with a host is configured. 

```yaml
    web: 
      baseUrl: "https://airflow.sample.com"
    ingress:
      hostname: airflow.sample.com
```

The resulting deployment will have http://airflow.sample.com (not HTTPS) as a `baseurl` set to the web container, which causes a problem for example during login into airflow (as we are redirected to the HTTP port which might not be available). 

The issue is this code-snipped:
https://github.com/bitnami/charts/blob/a44e476880fcca7c8c11207e6efa48adb7273503/bitnami/airflow/templates/_helpers.tpl#L420-L442

In this snippet, web.baseUrl is only considered if no host is set. But I think that `web.baseUrl` should always take precedence if configured explicitly over any derivation logic for the baseUrl. This could also be necessary if there are further reverse-proxies or gateways in the deployment setup.

### What is the expected behavior?

I think that `web.baseUrl` should always take precedence if configured explicitly over any derivation logic for the `baseUrl`. 

### What do you see instead?

The chart will always concatenate `http://` with the ingress hostname. But I would like to have `https://` and have no way of achieving this.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by si-te** [comment]
> Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

Sorry, i am currently not able to do that.
