### ISSUE TITLE
Allow securityContext override for redis-cluster init-containers

### ISSUE THREAD

**Issue by fellipecmwbc** [bitnami/charts#13061]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

For highly regulated environments using security policies it is important that all containers allow overrides for securityContext, specially to drop insecure capabilities such as NET_RAW.

### What is the feature you are proposing to solve the problem?

The same way overriding securityContext is allowed for the main containers, there should be an option to do it for init containers, i.e. `volumes-permissions` that has `runAsUser: 0` hardcoded at the moment. Adding a global containerSecurityContext would also be very helpful so we could do generic ones (like drop capabilities and runAs) in one go.

### What alternatives have you considered?

At the moment we have to exclude this in our security policies, but it makes very hard to identify with init containers.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by cleverhu** [comment]
I'd like to work on it.

**Comment by cleverhu** [comment]
@carrodher I have pulled a request for this, PTAL.

**Comment by carrodher** [comment]
Thanks! The team will review it and provide feedbach
