### ISSUE TITLE
[bitnami/minio] Ingress not working for Minio with s3 gateway 

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#13063]
### Name and Version

bitnami/minio

### What steps will reproduce the bug?

I use this command:

```
helm install s3 bitnami/minio --set global.storageClass=rook-cephfs --set apiIngress.ingressClassName=nginx --set gateway.enabled=true --set gateway.auth.s3.acces sKey=########## --set gateway.auth.s3.secretKey=********** --set gateway.auth.s3.serviceEndpoint=http://ip:port --set ingress.enabled=true --set apiIngress.enabled=true  --set ingress.ingressClassName=nginx --set apiIngress.hostname=api-minio.local
```

I want to see my objects in a bucket of s3.

### What do you see instead?

In console ingress:
First comes the Login page and after login in with the s3 access key and s3 secret key, it redirects me to the login page again. When I add buckets after my ingress path, It goes to this page but immediately redirects me to the login page again.

In API ingress:
It shows access denied and in logs show me `bucket not found` and when I add my bucket name after the ingress path it shows access denied but it doesn't log anything.

I think all of the permission on the side of s3 is OK because I can connect to my s3 from another pod with s3curl and aws s3 command and I can connect with the s3 browser from my windows.

**Comment by javsalgar** [comment]
Hi!

Does the issue happen without ingress? For example with a Loadbalancer IP or with a port-forward. Just to ensure that the issue is not related to Ingress.

**Comment by arezvani** [comment]
@javsalgar I have this problem also with NodePort.

**Comment by CeliaGMqrz** [comment]
Hi @arezvani.
First, sorry for the delay. We have reopened the case.  Have you been able to solve the issue?
Thank you for your report.
