### ISSUE TITLE
Repository always responds with 200 OK regardless if the chart exists or not

### ISSUE THREAD

**Issue by PeterMue** [bitnami/charts#13139]
### Name and Version

any non existent chart

### What steps will reproduce the bug?

1. curl https://charts.bitnami.com/bitnami/ANY_NON_EXISTANT_CHART -v -o /dev/null
2. response contains 200 OK with the index yaml as response body

### What is the expected behavior?

When trying to load a non existent chart I would expect that the response is a 404 not found.

### What do you see instead?

200 OK with response body containing the index yaml

### Additional information

This leads to some serious problems with our corporate artifactory that acts as a proxy to https://charts.bitnami.com/bitnami.
We have multiple different helm charts aggregated to a big virtual repository.
Artifactory tries to load the chart from all configured remote repos in a predefined order. If the remote does not contain the chart (i.e. response is a 404) artifactory tries the next.
As soon as the bitnami remote is queried, the response is always a 200 OK regardless if the chart exists or not.
Artifactory then stores the response body wrongly (index yaml) as tgz with the requested charts name as filename and serves this to helm.
Helm expects a tgz but instead encounters a plain text file with yaml content and fails.

**Comment by javsalgar** [comment]
Hi,

We performed changes in our Cloudfront configuration, could you try again?

**Comment by PeterMue** [comment]
Hello,

thanks for the quick reply, I can confirm that it now works as expected - at least with our Artifactory configuration.

Although I'm not sure if the correct behavior is to reply with a 403 instead of 404, which I think would be at least semantically clearer.

Cheers
