### ISSUE TITLE
c.ServerApp.root_dir is ignored

### ISSUE THREAD

**Issue by rabejens** [bitnami/charts#13136]
### Name and Version

bitnami/jupyterhub:2.0.2

### What steps will reproduce the bug?

 1. Add this to the `hub` section:
     ```yaml
     extraConfig:
        00-root-dir: |
          c.ServerApp.root_dir = "{{ .Values.singleuser.notebookDir }}"
          print("c.ServerApp.root_dir = " + c.ServerApp.root_dir)
    ```
 2. Install / upgrade the chart
 3. Access your Jupyterhub and log in

### What is the expected behavior?

The starting directory is set to `/opt/bitnami/jupyterhub/singleuser`

### What do you see instead?

The starting directory is set to `/`

### Additional information

The `print` statement in the `extraConfig` correctly prints the setting, so the configuration *IS* actually applied.

**Comment by rabejens** [comment]
I solved this using `c.Spawner.notebook_dir` like so:

```yaml
      extraConfig:
        00-root-dir: |
          c.Spawner.notebook_dir = "{{ .Values.singleuser.notebookDir }}"
```

This also has the side effect that the user cannot access anything outside this dir, what is fine and what I want.

**Comment by carrodher** [comment]
Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
