### ISSUE TITLE
Mongosh connections ReadinessProbe is always failing. Why is it necessary and what is it doing exactly to cause so many errors

### ISSUE THREAD

**Issue by xtianus79** [bitnami/charts#13130]
### Name and Version

bitnami/mongodb/6.0.2-debian-11-r9

### What steps will reproduce the bug?

Run `readinessProbe` on instance and arbiter in kubernetes replica set.

### What is the expected behavior?

to not error out and restart the pods multiple times

### What do you see instead?

The pods restarting multiple times. It seems like zombie processes are running and killing the container. 

I can run the `livenessProbe` but as soon as I run the `readinessProbe` it fails. 

Also, why does the `readinessProbe` `| grep -q 'true'` I mean, it is completely pointless, to be honest. 

Isn't that the main issue? You are running it but never getting an outcome. for example wouldn't it be better to run 

`'db.hello().isWritablePrimary || db.hello().secondary' | grep 'true'`

At least that actually emits something and you aren't silently doing nothing effectively. For example, 
`db.hello()... | grep -q 'true'` whether it is true or fails will just go away. How does that tell anybody anything? Literally, don't you want to know if it connected and it was true? 

For example: 

This outputs nothing
```
mongosh $TLS_OPTIONS --host <redacted> --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep 'false'
```
And therefore is equivalent to this with `-q`
```
mongosh $TLS_OPTIONS --host <redacted> --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
```

This outputs true
```
mongosh $TLS_OPTIONS --host <redacted> --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep 'true'
```
```
Connecting to:          mongodb://<redacted>:27017/?directConnection=true&appName=mongosh+1.6.0
true
```
<img width="626" alt="Screenshot 2022-10-24 165910-v3" src="https://user-images.githubusercontent.com/8476336/197642057-5aa950c9-ea53-42eb-8d47-9d8749ac58cd.png">

With all of that said, what is the `readinessProbe` really doing anyway. 

From the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes)

> The kubelet uses readiness probes to know when a container is ready to start accepting traffic. A Pod is considered ready when all of its containers are ready. One use of this signal is to control which Pods are used as backends for Services. When a Pod is not ready, it is removed from Service load balancers.

> Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don't want to kill the application, but you don't want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services.

> Note: Readiness probes runs on the container during its whole lifecycle.

> Caution: Incorrect implementation of readiness probes may result in an ever growing number of processes in the container, and resource starvation if this is left unchecked.

To me, the point of a readiness probe would indicate a process that has run and is verified. Well, you can't verify a hidden `grep` call. Wouldn't it make sense to either run the ping to the db or if using the `db.hello()` it would just run a normal process instead of quelling any and all outputs even if they are an error i.e. grep -p. 

For now, I just turned it off and the `livenessProbe` works fine. 

What I don't understand is when the readiness probe is processed. Is it just once or is it over multiple random times? The whole life cycle comment is confusing because it contradicts the `successThreshold` of running once and then quitting. 

Again, do you really need the `db.hello` wouldn't `db.adminCommand` just suffice?  Or if you're going to run the true then it can't have a `-p`.

```yaml
data:
  {{- $fullname := include "mongodb.fullname" . }}
  startup-probe.sh: |
    #!/bin/bash
    {{- if .Values.tls.enabled }}
    TLS_OPTIONS='--tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert'
    {{- end }}
    mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true$'
  readiness-probe.sh: |
    #!/bin/bash
    {{- if .Values.tls.enabled }}
    TLS_OPTIONS='--tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert'
    {{- end }}
    # Run the proper check depending on the version
    [[ $(mongod -version | grep "db version") =~ ([0-9]+\.[0-9]+\.[0-9]+) ]] && VERSION=${BASH_REMATCH[1]}
    . /opt/bitnami/scripts/libversion.sh
    VERSION_MAJOR="$(get_sematic_version "$VERSION" 1)"
    VERSION_MINOR="$(get_sematic_version "$VERSION" 2)"
    VERSION_PATCH="$(get_sematic_version "$VERSION" 3)"
    if [[ ( "$VERSION_MAJOR" -ge 5 ) || ( "$VERSION_MAJOR" -ge 4 && "$VERSION_MINOR" -ge 4 && "$VERSION_PATCH" -ge 2 ) ]]; then
        mongosh $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true$'
    else
        mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.isMaster().ismaster || db.isMaster().secondary' | grep -q 'true$'
    fi
```

This is the primary difference between the liveliness vs readiness/startup probes. 

### Additional information

I'll do a PR and see if it makes it in. 

This is the [related issue](https://github.com/bitnami/charts/issues/10264)

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback
