### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Chart ignores global.storageClass param

### ISSUE THREAD

**Issue by ArsenAbayan** [bitnami/charts#13156]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.1.0

### What steps will reproduce the bug?

1. Install helm chart and set specific "local-path" storage class instead of default "longhorn" storage class
```
helm install bitnami-rabbitmq-operator \
  --namespace rabbitmq-operator-system --create-namespace \
  --set global.storageClass=local-path \
    bitnami/rabbitmq-cluster-operator
```

2. Create rabbitmq cluster whitout setting storageClassName=local-path
```
cat <<EOF | tee rabbitmq-cluster-test.yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
EOF

kubectl create ns rabbitmq-test
kubectl -n rabbitmq-test apply -f rabbitmq-cluster-test.yaml
```

### Are you using any custom parameters or values?

--set global.storageClass=local-path

### What is the expected behavior?

New rabbitmq clusters should use "local-path" storage class

### What do you see instead?

New rabbitmq clusters used default "longhorn" storage class

**Comment by javsalgar** [comment]
Hi,

Please note that, unlike other helm charts, this one deploys an Operator. Therefore, the `global.storageClass` parameter will not be passed to the created `RabbitmqCluster` objects unless the `rabbitmq-cluster-operator` allows configuring a default storage class inside its parameters. As far as I know, this is something not currently supported by the operator, so my advice would be to check with the rabbitmq devs and request that feature. Then we can add it to the chart.

https://github.com/rabbitmq/cluster-operator
