### ISSUE TITLE
Not able to connect to sentinel address from jedis client.

### ISSUE THREAD

**Issue by madhushreegc** [bitnami/charts#13167]
### Name and Version

https://artifacthub.io/packages/helm/bitnami/redis redis 17.3.7 

### What steps will reproduce the bug?

EKS Kubernetes environment
Helm chart Redis with sentinels enabled is installed.
Only one sentinel service is exposed, with this if we give the sentinel address in the below code, it is throwing below error 

> Caused by: redis.clients.jedis.exceptions.JedisConnectionException: All sentinels down, cannot determine where is mymaster master is running..."}}

```
public class App
{
    public static void main( String[] args )
    {
        try {
            String sentinels = "lpde-redis-node:26379";
            String masterName = "mymaster";
            String password = "password";
            System.out.println("Inside main");
            Set<String> sentinelURIs = new HashSet<String>();
            sentinelURIs.addAll(Arrays.asList(sentinels.split(",")));
            Pool<Jedis> pool =  new JedisSentinelPool(masterName, sentinelURIs, password);
            
            String timerProfilekey = "test";
            try (Jedis jedis = pool.getResource()) {
                jedis.set(timerProfilekey, "abcd");
            }
            
            try (Jedis jedis = pool.getResource()) {
                String abcd = jedis.get(timerProfilekey);
                System.out.println(abcd);
            }
            
        } catch (Exception e) {
            System.out.println(e);
            
        }
    }
}
```

What the actual sentinel address are exposed? how to get the sentinel address with 3 nodes? Please help us with the command to access the address of sentinels cluster IPs so we configure it within our application.

### Are you using any custom parameters or values?

yes using values.

```yaml
fullnameOverride: "lpde-redis"
auth:
  password: password
replica:
  replicaCount: 3
sentinel:
  enabled: true
  masterSet: mymaster
```

### What is the expected behavior?

Successfully able to connect with the sentinel address

### What do you see instead?

All sentinels are down error, connection exception.

**Comment by carrodher** [comment]
When the Helm chart is installed there are some installation notes shown in the console with information about how to connect to the different services based on the parameters used to deploy the Helm chart.

You can also see those installation notes at any time by running `helm get notes RELEASE_NAME`

**Comment by madhushreegc** [comment]
Thank you, issue was in the code, sentinel password was not set . It is working now. Closing the issue.
