### ISSUE TITLE
unable to push images in private docker registry in jenkins pipeline

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#13174]
### Name and Version

bitnami/jenkins, latest

### What steps will reproduce the bug?

1) helm install jenkins
2) created a pod with dind image and linked jenkins with this dind pod (docker daemon).
3) login into docker private registry using username and password

### What is the expected behavior?

i am to pull and push image from my private docker registry . also i should be able to run a pipeline in jenkins involving pulling and pushing of images to provate registry.

### What do you see instead?

unable to push the image to docker registry and throwing error of unauthorised access.

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
