### ISSUE TITLE
<.Values.clusterDomain>: can't evaluate field Values in type int

### ISSUE THREAD

**Issue by deyaeddin** [bitnami/charts#1317]
**Which chart**:

minio 1.1.2

**Description**

I'm getting:
`rpc error: code = Unknown desc = render error in "minio/templates/statefulset.yaml": template: minio/templates/statefulset.yaml:98:157: executing "minio/templates/statefulset.yaml" at <.Values.clusterDomain>: can't evaluate field Values in type int`

**Steps to reproduce the issue:**
I'm using Kubeapps and just copy/past the values-production.yaml 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by miguelaeh** [comment]
Hi @deyaeddin ,
Thank you very much for reporting you are right, there is a mistake on the `values-production.yaml`
