### ISSUE TITLE
External access configuration fails

### ISSUE THREAD

**Issue by buchanantim** [bitnami/charts#13201]
### Name and Version

bitnami/mongodb 13.3.0

### What steps will reproduce the bug?

Per documentation for [external access](https://docs.bitnami.com/kubernetes/infrastructure/mongodb/configuration/configure-external-access-replicaset/), execute the following Powershell script (or equivalent in *nix):

```powershell
helm install mongodb bitnami/mongodb
    --version "13.3.0"
    --set architecture=replicaset
    --set replicaCount=2
    --set externalAccess.enabled=true
    --set externalAccess.service.type=LoadBalancer
    --set externalAccess.service.port=27017
    --set externalAccess.autoDiscovery.enabled=true
    --set serviceAccount.create=true
    --set rbac.create=true
```

### What is the expected behavior?

Notes from a successful install. For example, change the version in the above script to 13.1.7, and the chart is installed successfully.

### What do you see instead?
```
Error: INSTALLATION FAILED: template: mongodb/templates/replicaset/external-access-svc.yaml:35:19: executing "mongodb/templates/replicaset/external-access-svc.yaml" at <$root.Values.externalAccess.service.type>: type is not a method but has arguments
```
### Additional information

Related to: https://github.com/bitnami/charts/pull/13092

**Comment by jotamartos** [comment]
Hi @buchanantim ,

Thank you for reporting this issue. I just found the typo and will create a new PR to fix it.

**Comment by jotamartos** [comment]
The PR is now merged and the new version of the chart should be available soon. Please reopen this issue if you continue running into it.
