### ISSUE TITLE
bitnami/dokuwiki: render error in "dokuwiki/templates/tls-secrets.yaml"

### ISSUE THREAD

**Issue by henzestplus** [bitnami/charts#1320]
**Which chart**:

dokuwiki-5.1.0

**Description**

I am trying to setup dokuwiki on minikube (1.2) with the ingress controller and TLS enabled. I have the addon ingress enabled.

**Steps to reproduce the issue:**
```
helm install stable/dokuwiki --name=dokuwiki --namespace dokuwiki --set ingress.secrets[0].certificate="$(cat mycert.pem)",ingress.secrets[0].key="$(cat mycert.key)",ingress.hosts[0].name="wiki-test.example.com",ingress.enabled=true,ingress.hosts[0].tls=true
```

**Describe the results you received:**
```
Error: render error in "dokuwiki/templates/tls-secrets.yaml": template: dokuwiki/templates/_helpers.tpl:6:18: executing "dokuwiki.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```
**Describe the results you expected:**

That the dokuwiki was installed and ready for use.

**Additional information you deem important (e.g. issue happens only occasionally):**

The installation is confirmed to be working when installing with ingress without the tls options.

I have also tried using overrideName and overrideFullname, but that did not work.

In case anyone wonders: there is a workaround, it is after all just a scripted/templated engine to do all actions automatically instead of by hand. Use the templates and the options list in the docs to build up your tls secrets file and add the needed parameters to the ingress controller.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

- Output of `kubectl version`:
Warning: minikube version: v1.2.0 installation!
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by alemorcuq** [comment]
Hi, @henzestplus.

Thank you for reporting this. I've created a Pull Request to fix it. You can try those changes locally if you want to see if it solves your problem.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Hi again, @henzestplus. 

The pull request have been merged. Changes are live in version `5.1.1`. Let me know if it works for you.

Regards,
Alejandro

**Comment by henzestplus** [comment]
I have just verified that this worked for me! Thank you!

**Comment by alemorcuq** [comment]
I'm glad it works now, @henzestplus. Let us know if you find any other issue in the future.

Regards,
Alejandro
