### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by scorpius81** [bitnami/charts#13231]
### Name and Version

bitnami/phpmyadmin

### What steps will reproduce the bug?

I installed the bitnami / phpmyadmin chart via helm.
I set:

`extraEnvVars: [{"name": "PHP_UPLOAD_MAX_FILESIZE", "value": "1000M"}]`

But if I try to import a 2 MB .sql file it fails

413 Request Entity Too Large

### Are you using any custom parameters or values?

`extraEnvVars: [{"name": "PHP_UPLOAD_MAX_FILESIZE", "value": "1000M"}]`

### What do you see instead?

413 Request Entity Too Large

**Comment by scorpius81** [comment]
I have resolved.

I have set In ingress section:

`  annotations:
    {
      "nginx.ingress.kubernetes.io/proxy-body-size": "100m"
    }`

**Comment by siegy22** [comment]
For anyone running into this:

- Check your (nginx) ingress configuration. (There will normally be an indication that it is actually nginx blocking the request on the HTML page)
- If you need more than 80MB for uploads, increase the php.ini config, by following https://github.com/bitnami/charts/issues/5929#issuecomment-809421103
- If you need more than 1GB, increase the [apache's default limit "LimitRequestBody"](https://httpd.apache.org/docs/2.4/mod/core.html) temporarily by setting the `apacheConfiguration:` value (for inspiration see https://github.com/siegy22/k8s-gitops/commit/461ab79c031dc66ca45407278bc467806666afa1) 

If you're asking why I would even need > 1GB upload sizes: I dumped a wp instance (which was pretty much a photo library) using the All-in-One WP Migration. This created a zip that was 1.7GB in size. Thus I was hitting the limit of apache, not PHP, not my nginx ingress 😞
