### ISSUE TITLE
external-dns

### ISSUE THREAD

**Issue by HaroonSaid** [bitnami/charts#13241]
### Name and Version

external-dns 4.3.1

### What steps will reproduce the bug?

Which chart:
external-dns

Describe the bug
The external-dns chart in the chart repo is not up to date.

To Reproduce
https://artifacthub.io/packages/helm/bitnami/external-dns lists version 4.0.0 is current.

### What is the expected behavior?

should work

### What do you see instead?

nothing

**Comment by carrodher** [comment]
At this moment the version present in the Helm repository is 6.11.2:
```console
$ helm search repo bitnami/external
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/external-dns	6.11.2       	0.13.1     	ExternalDNS is a Kubernetes addon that configur...
```
Which is the same present in GitHub:

https://github.com/bitnami/charts/blob/530ceaa3c6c8aa9fa545ea236999a04636d1310a/bitnami/external-dns/Chart.yaml#L27

In the same way, taking a look at https://artifacthub.io/packages/helm/bitnami/external-dns, the same version is listed so it seems everything is updated:
<img width="1385" alt="Screenshot 2022-10-30 at 08 55 47" src="https://user-images.githubusercontent.com/13216600/198868292-ec782c3a-d2d7-4281-abc7-4afbf1477130.png">
