### ISSUE TITLE
etcd-cluster - Can't enable client authentication in the cluster

### ISSUE THREAD

**Issue by mordf** [bitnami/charts#1326]
**Which chart**:

etcd
**Description**

I can't enable client authentication with my self signed certificated pod logs show me the current errors:
```
error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority", ServerName ""
error "remote error: tls: bad certificate", ServerName "etcd-cluster-2.etcd-cluster-headless.default.svc.cluster.local"
```
I created the certificated according to this document: https://coreos.com/os/docs/latest/generate-self-signed-certificates.html and created the secret as described in the docs
That's how it is in etcd-cluster-1 as well and in etcd-clsuter-0 pod it's stuck on:
```
==> Creating data dir...
==> There is no data at all. Initializing a new member of the cluster...
==> Configuring RBAC authentication!
```
**Steps to reproduce the issue:**
```
helm install --name etcd-cluster --set auth.peer.secureTransport=true --set auth.peer.useAutoTLS=true --set auth.client.secureTransport=true --set auth.client.enableAuthentication=true --set auth.client.existingSecret=etcd-client-certs --set persistence.enable=true --set persistence.size=1Gi --set disasterRecovery.enabled=true --set disasterRecovery.pvc.size=1Gi --set disasterRecovery.cronjob.schedule="* * * * *" --set statefulset.replicaCount=3 bitnami/etcd
```
**Describe the results you received:**
pods are running but i'm getting the certificate errors I described above

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:
2.14.1
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @mordf ,
It seems that you use a wrong certificate. I found a thread that could be useful [here](https://github.com/etcd-io/etcd/issues/9785)

**Comment by mordf** [comment]
Hi @miguelaeh there is one thing that eludes me:
`kubectl create secret generic etcd-client-certs --from-file=ca.crt=path/to/ca.crt --from-file=cert.pem=path/to/cert.pem --from-file=key.pem=path/to/key.pem`

The `--from-file=ca.crt=path/to/ca.crt` does the **ca.crt** should be in binary or text format?
If it's supposed to be in a binary format so I guess I need to use this kind of command on my **ca.pem**:
`openssl x509 -outform der -in ca.pem -out ca.crt`

Right?

**Comment by miguelaeh** [comment]
Hi @mordf ,
I am not sure about he format to be honest. The best thing you can do is try with both and see if it works with one of them.

**Comment by mordf** [comment]
**Update**

I had managed to make it work, thanks @miguelaeh the post you referenced me to did the job.
What I did is that I added to the server profile in the **ca-config.json** client auth and generated the certificates with the server profile, I also added to the **server.json** the following URL under hosts: https://etcd-cluster-0.etcd-cluster-headless.default.svc.cluster.local

And the ca.crt should be in text format and not der.
ca-config.json:
`{
  "signing": {
    "default": {
      "expiry": "8760h"
    },
    "profiles": {
      "server": {
        "expiry": "8760h",
        "usages": [
          "signing",
          "key encipherment",
          "server auth",
          "client auth"
        ]
      },
      "client": {
        "expiry": "8760h",
        "usages": [
          "signing",
          "key encipherment",
          "client auth"
        ]
      },
      "peer": {
        "expiry": "8760h",
        "usages": [
          "signing",
          "key encipherment",
          "server auth",
          "client auth"
        ]
      }
    }
  }
}`

server.json:
`{
  "CN": "etcd",
  "hosts": [
    "etcd-cluster-0.etcd-cluster-headless.default.svc.cluster.local"
  ],
  "key": {
    "algo": "ecdsa",
    "size": 256
  },
  "names": [
    {
        "C": "US",
        "L": "CA",
        "ST": "San Francisco"
    }
  ]
}`

everything started to work afterwards, what I don't understand is why did I have to support hosts in the certificate since in the documentation is says that you don't need to specify hosts for client certificates? and how did the other etcd nodes managed to work? since I generated the certificate only to: https://etcd-cluster-0.etcd-cluster-headless.default.svc.cluster.local

**Comment by miguelaeh** [comment]
Hi @mordf ,
About the error you are facing it seems that the traffic that that command uses is trying to access without the TLS credentials, there is another workaround [here](https://github.com/etcd-io/etcd/issues/9917).
 
About the client certificate you can check [this](https://github.com/etcd-io/etcd/issues/9785#issuecomment-432446613)

**Comment by mordf** [comment]
Thanks @miguelaeh, It seems that I had a mistake with addressing the etcd from etcdctl, I `kubectl exec ectd-cluster-0 sh` and ran etcdctl without the --cert --key and --cacert, I thought that when running from within the pod you don't need it, but I guess you do.
