### ISSUE TITLE
elasticsearch chart failed to deploy

### ISSUE THREAD

**Issue by ylvmw** [bitnami/charts#1327]
**Which chart**: bitnami/elasticsearch 6.0.0

**Description**
All pods failed to start with exceptions.

**Steps to reproduce the issue:**

1. Install with: helm install --name elasticsearch bitnami/elasticsearch
2. Check if the deployment succeeds.

**Describe the results you received:**
The deployment failed. All pods failed. To check the logs with: kubectl logs elasticsearch-elasticsearch-coordinating-only-57f9658849-tr9r2, I could see the errors:
```
INFO  ==> ** Starting Elasticsearch **
future versions of Elasticsearch will require Java 11; your Java version from [/opt/bitnami/java] does not meet this requirement
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.NoSuchFileException: /opt/bitnami/elasticsearch/config/es_config.sample
Likely root cause: java.nio.file.NoSuchFileException: /opt/bitnami/elasticsearch/config/es_config.sample
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
```

**Describe the results you expected:**

The deployment could succeed.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
v2.14.2
```

- Output of `kubectl version`: 

```
v1.14.0
```

**Comment by andresbono** [comment]
Hi @ylvmw, is it a fresh install? Does it only happen with the version `6.0.0` of the chart?

As you can see in the initialization logic that file is deleted or moved depending on your initial configuration:

https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/7/debian-9/rootfs/libelasticsearch.sh#L397-L400

But we have not seen any errors related to that.

**Comment by ylvmw** [comment]
@andresbono I tried installing ES several times and also saw the issues in previous version of the chart.
Do you mean I need to to clean the env? If so, could you give some hints on how to clean it or any workaround? Thanks!

**Comment by andresbono** [comment]
Hi @ylvmw, to do a full clean-up of the chart, you can do:

```
helm delete --purge elasticsearch
```

And also delete the PVC associated to that chart. To list all of them:

```
kubectl get pvc
```
You will need to delete the ones with the name `data-elasticsearch-elasticsearch-data-*`.

Please note that you will loose any data related to elasticsearch.
