### ISSUE TITLE
[bitnami/redis-cluster] Can't change redis port from 6379

### ISSUE THREAD

**Issue by jmthomas** [bitnami/charts#13270]
### Name and Version

binami/redis-cluster 8.2.4

### What steps will reproduce the bug?

I'm running locally on k3s. I can deploy redis-cluster by itself successfully but my application has two separate redis clusters: one for persistant data and one for ephemeral data which we do not backup. When trying to deploy two clusters, the ephemeral cluster fails because it appears to be trying to use port 6379 even though I've changed the port to 6380. I think it has something to do with the port being a name `tcp-redis` which the ephemeral cluster is matching against the regular cluster. Is there an easy way to distinguish that?

### Are you using any custom parameters or values?

chart.yaml:

        apiVersion: v2
        name: openc3
        description: A Helm chart for Kubernetes
        type: application
        version: 0.1.0
        appVersion: "latest"
        dependencies:
        - name: redis-cluster
          version: 8.2.4
          repository: "@bitnami"
          alias: redis
        - name: redis-cluster
          version: 8.2.4
          repository: "@bitnami"
          alias: redis-ephemeral

values.yaml:

        redis:
          service:
            ports:
              redis: 6379
          redis:
            containerPorts:
              redis: 6379
              bus: 16379
            configmap: |-
              port 6379
              appendonly yes
              user healthcheck on nopass -@all +cluster|info +ping
        redis-ephemeral:
          service:
            ports:
              redis: 6380
          redis:
            containerPorts:
              redis: 6380
              bus: 16380
            configmap: |-
              save ""
              port 6380
              appendonly yes
              user healthcheck on nopass -@all +cluster|info +ping

### What is the expected behavior?

Two redis-clusters up and running.

### What do you see instead?

redis-ephemeral-0 logs:

        371:M 31 Oct 2022 20:03:04.952 * Ready to accept connections
        Could not connect to Redis at openc3-redis-ephemeral-1.openc3-redis-ephemeral-headless:6379: Connection refused
        Node openc3-redis-ephemeral-1.openc3-redis-ephemeral-headless not ready, waiting for all the nodes to be ready...

redis-ephemeral-3 logs:

        1:M 31 Oct 2022 20:04:16.692 * Ready to accept connections
        1:S 31 Oct 2022 20:04:16.698 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
        1:S 31 Oct 2022 20:04:16.698 * Connecting to MASTER 10.42.1.8:6379
        1:S 31 Oct 2022 20:04:16.698 * MASTER <-> REPLICA sync started
        1:S 31 Oct 2022 20:04:16.698 # Cluster state changed: ok

They all seem to be using 6379 when I need them to be 6380.

**Comment by jmthomas** [comment]
kubectl describe service openc3-redis-headless

        Name:              openc3-redis-headless
        Namespace:         openc3
        Labels:            app.kubernetes.io/instance=openc3
                           app.kubernetes.io/managed-by=Helm
                           app.kubernetes.io/name=redis
                           helm.sh/chart=redis-8.2.4
        Annotations:       meta.helm.sh/release-name: openc3
                           meta.helm.sh/release-namespace: openc3
        Selector:          app.kubernetes.io/instance=openc3,app.kubernetes.io/name=redis
        Type:              ClusterIP
        IP Family Policy:  SingleStack
        IP Families:       IPv4
        IP:                None
        IPs:               None
        Port:              tcp-redis  6379/TCP
        TargetPort:        tcp-redis/TCP
        Endpoints:         10.42.0.8:6379,10.42.1.11:6379,10.42.1.5:6379 + 3 more...
        Port:              tcp-redis-bus  16379/TCP
        TargetPort:        tcp-redis-bus/TCP
        Endpoints:         10.42.0.8:16379,10.42.1.11:16379,10.42.1.5:16379 + 3 more...
        Session Affinity:  None
        Events:            <none>

kubectl describe service openc3-redis-ephemeral-headless

        Name:              openc3-redis-ephemeral-headless
        Namespace:         openc3
        Labels:            app.kubernetes.io/instance=openc3
                           app.kubernetes.io/managed-by=Helm
                           app.kubernetes.io/name=redis-ephemeral
                           helm.sh/chart=redis-ephemeral-8.2.4
        Annotations:       meta.helm.sh/release-name: openc3
                           meta.helm.sh/release-namespace: openc3
        Selector:          app.kubernetes.io/instance=openc3,app.kubernetes.io/name=redis-ephemeral
        Type:              ClusterIP
        IP Family Policy:  SingleStack
        IP Families:       IPv4
        IP:                None
        IPs:               None
        Port:              tcp-redis  6380/TCP
        TargetPort:        tcp-redis/TCP
        Endpoints:         10.42.0.9:6380,10.42.1.12:6380,10.42.1.8:6380 + 3 more...
        Port:              tcp-redis-bus  16380/TCP
        TargetPort:        tcp-redis-bus/TCP
        Endpoints:         10.42.0.9:16380,10.42.1.12:16380,10.42.1.8:16380 + 3 more...
        Session Affinity:  None
        Events:            <none>

**Comment by jmthomas** [comment]
Also I've noticed when my ephemeral nodes boot I see the following:

                        _._                                                  
                   _.-``__ ''-._                                             
              _.-``    `.  `_.  ''-._           Redis 7.0.5 (00000000/0) 64 bit
          .-`` .-```.  ```\/    _.,_ ''-._                                  
         (    '      ,       .-`  | `,    )     Running in cluster mode
         |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
         |    `-._   `._    /     _.-'    |     PID: 1
          `-._    `-._  `-./  _.-'    _.-'                                   
         |`-._`-._    `-.__.-'    _.-'_.-'|                                  
         |    `-._`-._        _.-'_.-'    |           https://redis.io       
          `-._    `-._`-.__.-'_.-'    _.-'                                   
         |`-._`-._    `-.__.-'    _.-'_.-'|                                  
         |    `-._`-._        _.-'_.-'    |                                  
          `-._    `-._`-.__.-'_.-'    _.-'                                   
              `-._    `-.__.-'    _.-'                                       
                  `-._        _.-'                                           
                      `-.__.-'                                               
        
The interesting part is the port is still 6379. So apparently this:

        redis-ephemeral:
          service:
            ports:
              redis: 6380
          redis:
            containerPorts:
              redis: 6380
              bus: 16380
            configmap: |-
              port 6380

Is not overriding the actual port that Redis itself is using. Obviously the port is already defined in the [config map](https://github.com/bitnami/charts/blob/04a144858cd35140aeb75a715dc1281887819055/bitnami/redis-cluster/templates/configmap.yaml#L105) as 6379 so apparently setting again at the end doesn't work? How else can we change that port?

**Comment by rafariossaa** [comment]
Hi,
  I think the issue here is that the name of the [environment variable here](https://github.com/bitnami/charts/blob/5b805211ca9c96692c06fed75ae033bc444d4279/bitnami/redis-cluster/templates/redis-statefulset.yaml#L190) is wrong.

**Comment by rafariossaa** [comment]
This should be fixed now.
Could you give it a try ?

**Comment by jmthomas** [comment]
This appears to have fixed it. Thanks! I'm the only one changing the port number?
