### ISSUE TITLE
Adding python packages on the go

### ISSUE THREAD

**Issue by alon050** [bitnami/charts#13284]
### Name and Version

bitnami/charts/airflow

### What is the problem this feature will solve?

The problem is you need to install packages manually if you need to add more python packages after deploying the Helm chart.
Right now, from my understanding, the only way to pip install is to attach a volume and it will install it only in the deployment/on container start.

I put packages in a GitLab repository, and the airflow pulls the folder of the packages to the pod, but then I need to enter each pod and manually download it.
There's an option to add a command that installs the git packages directory on container startup but if I add another package, I need to restart all the pod for it to update, which requires manual doing and gets the system offline for a while.

### What is the feature you are proposing to solve the problem?

I don't know how can I solve it, but I've been struggling with it for the last couple of weeks and I can't figure out a way to do it automatically.

**Comment by carrodher** [comment]
I'm not sure if there is a solution for this use case without implying the restart of the container. There are certain actions that need to be executed at a specific time during the deployment and because of that, a restart is needed.

**Comment by alon050** [comment]
an option we thought of is when a package is added, to run a gitlab runner that would trigger the installation of the requirements.txt file, but the whole reason to use the git cloning automaticlly is to not use a gitlab runner and avoid unnecessary pipelines. but if you dont think there is any possible way of doing it right, than i will do it that way.

**Comment by carrodher** [comment]
Not sure if using [`initContainers`](https://github.com/bitnami/charts/blob/main/bitnami/airflow/values.yaml#L155) or [`sidecarContainers`](https://github.com/bitnami/charts/blob/main/bitnami/airflow/values.yaml#L144) could help to solve your use case, just in case you would like to investigate that path.
