### ISSUE TITLE
[bitnami/redis] Ability to leave namespace empty

### ISSUE THREAD

**Issue by brunocascio** [bitnami/charts#13287]
### Name and Version

bitnami/redis:17.3.7

### What is the problem this feature will solve?

Ability to deploy Redis in the "current" namespace without hardcode it or passing it through helm args, explicitly. 

An example is using ArgoCD. In my current setup, the namespaces are created by ArgoCD, and every object is placed into it automatically unless the chart explicitly says something else.

Mostly, the helm charts use something like `.Release.Namespace | "default"` but it's problematic when you don't want default values.

### What is the feature you are proposing to solve the problem?

I don't know how insane is this idea, but something like this, would works:

Instead of adding the namespace like this:

```yaml
metadata:
  namespace: {{ .Release.Namespace | quote }}
```

It might expose a sort of "template" in order to hook that logic from a parent chart

```yaml
metadata:
  {{ template "namespace" }}
```

So, since templates can be overridden from a parent chart, it could just be written like this:

```yaml
{{- define "namespace" }}
#  don't print anything :P
{{- end }}
```

Whit this solution, `namespace: <value>` is not injected on any manifest

**Comment by brunocascio** [comment]
Sure @javsalgar

**Comment by brunocascio** [comment]
> Hi!
> 
> Thank you so much for the suggestion. Would you like to propose a PR for this? I think that the bitnami/common library chart should be the one to have this change

After doing some tests, I figured out ArgoCD only changes the` metadata.namespace` property only.
It means other places where the namespace is required, like:

```yaml
requiredDuringSchedulingIgnoredDuringExecution:
....
  - labelSelector:
    namespaces:
      - <argocd-do-not-replace-here>
...
```

will not work, so I think there's no way to do it right now automatically via ArgoCD without explicitly setting the `namespace` property.


I think we can close this issue. 

Thanks!

**Comment by javsalgar** [comment]
Thank you so much for the insight!
