### ISSUE TITLE
[bitnami/spark] shared-certs volume wrong mount path

### ISSUE THREAD

**Issue by anebi** [bitnami/charts#13290]
### Name and Version

bitnami/spark 6.3.9

### What steps will reproduce the bug?

Kubernetes/Rancher 2.5.9

### Are you using any custom parameters or values?
```
security:
  certificatesSecretName: ''
  passwordsSecretName: apache-spark-credentials
  rpc:
    authenticationEnabled: true
    encryptionEnabled: true
  ssl:
    autoGenerated: true
    enabled: true
    existingSecret: ''
    keystorePassword: ''
    needClientAuth: true
    protocol: TLSv1.2
    resources:
      limits: {}
      requests: {}
    truststorePassword: ''
  storageEncryptionEnabled: true
```
### What is the expected behavior?

Apache Spark mounts the certificates to the correct path so Apache Spark can start correctly

### What do you see instead?

On Master and Worker pods the shared-cert volume is mounted to /bitnami/spark/conf/certs/ instead of /opt/bitnami/spark/conf/certs/

Only Master cert-init container mounts to /opt/bitnami/spark/conf/certs/ but all the rest mounts to /bitnami/spark/conf/certs/

When Master and Worker pods strart, they complain that they cannot find the certificates under /opt/bitnami/spark/conf/certs/ location.

Master spark-master container:

```
Welcome to the Bitnami spark container
 18:30:59.69 Subscribe to project updates by watching https://github.com/bitnami/containers
 18:30:59.69 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 18:30:59.69 
 18:30:59.70 INFO  ==> ** Starting Spark setup **
 18:30:59.71 ERROR ==> If you enable SSL configuration, you must mount your keystore file and specify the location in SPARK_SSL_KEYSTORE_FILE. Default value: /opt/bitnami/spark/conf/certs/spark-keystore.jks
 18:30:59.71 ERROR ==> If you enable SSL configuration, you must mount your trutstore file and specify the location in SPARK_SSL_TRUSTSTORE_FILE. Default value: /opt/bitnami/spark/conf/certs/spark-truststore.jks"`
```
Worker containers result:

cert-init:

```
writing RSA key
Importing keystore /tmp/keystore.p12 to /opt/bitnami/spark/conf/certs/spark-keystore.jks...
Entry for alias 1 successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
keytool error: java.io.FileNotFoundException: /opt/bitnami/spark/conf/certs/spark-keystore.jks (No such file or directory)
```

worker-spark: Most probably it will fail too but it is on Waiting mode, waiting for the cert-init to complete.

**Comment by anebi** [comment]
Checking the deployment chart for master I see this:

`volumeMounts:
            {{- if .Values.master.existingConfigmap }}
            - name: config
              mountPath: /bitnami/spark/conf/
            {{- end }}
            {{- if .Values.security.ssl.enabled }}
            - name: shared-certs
              mountPath: /bitnami/spark/conf/certs
              readOnly: true
            {{- end }}`
            
For worker init cert

`volumeMounts:
          - name: certs
            mountPath: /certs
          - name: shared-certs
            mountPath: /bitnami/spark/conf/certs
        {{- end }}`

worker-spark

`volumeMounts:
            {{- if .Values.worker.existingConfigmap }}
            - name: config
              mountPath: '/bitnami/spark/conf/'
            {{- end }}
            {{- if .Values.security.ssl.enabled }}
            - name: shared-certs
              mountPath: '/bitnami/spark/conf/certs'
              readOnly: true
            - name: certs
              mountPath: /certs
            {{- end }}`

**Comment by javsalgar** [comment]
Hi,

I see that you are using a secret, could you share the name of the certificate filenames?

**Comment by anebi** [comment]
Hello,

I use secret only for the passwords called 'apache-spark-credentials'. If i remove this secret and set passwordsSecretName to ''. Then the chart generates a new secret with name 'spark-secret' with "rpc-authentication-secret, ssl-keystore-password, ssl-truststore-password" keys (those are the keys i used in my own secret as well). Even in this case the deployment fails with same errors described bellow.

 
I just checked the sandbox deployment I have and I see following. When autoGenerated is set to true, a certificate is generated with name spark-crt but there is no secret generated with the keystore or truststore files.

The master pod init cert container finish its job ok. Spark master container complains:

`INFO  ==> ** Starting Spark setup **
 10:24:24.80 ERROR ==> If you enable SSL configuration, you must mount your keystore file and specify the location in SPARK_SSL_KEYSTORE_FILE. Default value: /opt/bitnami/spark/conf/certs/spark-keystore.jks
 10:24:24.80 ERROR ==> If you enable SSL configuration, you must mount your trutstore file and specify the location in SPARK_SSL_TRUSTSTORE_FILE. Default value: /opt/bitnami/spark/conf/certs/spark-truststore.jks"`
 
 When i change the deployment of the master the way that I can exec to the container, I see that /opt/bitnami/spark/conf/certs doesn't exist. The reason for this is because the shared-certs volume is set to moint to /bitnami/spark/conf/certs.
 
 `ls /opt/bitnami/spark/conf/certs
ls: cannot access '/opt/bitnami/spark/conf/certs': No such file or directory`

`ls /bitnami/spark/conf/certs
spark-keystore.jks  spark-truststore.jks`
 
 Worker cert-init and worker-spark containers don't work at all because on both the mount point is set to: /bitnami/spark/conf/certs
 
 
 If i create manually the trustore and keystore files and create a secret with their data, then set certificatesSecretName with autoGenerated=false. I see the same problem like above. It cannot find the files because they are still mounted to wrong location.
 
 Yesterday I did the following test. Cloned the Bitnami chart and created my own customized chart where I fix the mount points to be /opt/bitnami/spark/conf/certs, then the error was gone. All containers were able to find the keystore and truststore files. With this test I experienced a different problem. Liveness/Readiness health check was failing with error 'tls error: bad certficiate'. Most probably related to self-signed cert or something like that, I haven't done any troubleshooting to this yet.
 
 Fow now i try to figure out if i do something wrong of there is problem in the chart itself related to certificates.

**Comment by javsalgar** [comment]
Hi!

If you see that this could be an issue with the chart and you created a fix, would you like to submit it?

**Comment by anebi** [comment]
Hello,

Yes, I can create a PR and send it for review.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
