### ISSUE TITLE
[nginx] add support for nodeselector or affinity

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#1329]
**Which chart**:

nginx,  v. latest

**Description**
Need support for nodeSelector / affinity in order to run on wanted target nodes

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
run on target . nodes

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by juan131** [comment]
Hi @davidkarlsen 

Thanks so much for the suggestion! I just create a PR to address this feature which is missing in the chart.

**Comment by juan131** [comment]
Hi @davidkarlsen 

We just merged the PR adding support to 'nodeSelector', 'affinity' and 'tolerations' . Please feel free to give it a try!

**Comment by davidkarlsen** [comment]
Thanks - I will!
