### ISSUE TITLE
[bitnami/postgresql] - sub charts deploying postgres are able to select pods that are unaffiliated with them

### ISSUE THREAD

**Issue by cberg-aot** [bitnami/charts#13326]
### Name and Version

postgresql

### What is the problem this feature will solve?

Chart A 
```
- Subchart B
  -- Sub-subchart Postgresql
- Subchart C
  -- Sub-subchart Postgresql
```
A.B.Postgresql & A.C.Postgresql will generate labels and selectors based on bitnami common lib.   

In particular common.labels.matchLabels defaults to .Release.Name.
![image](https://user-images.githubusercontent.com/93226309/199624373-a717b822-b3c6-4d59-9781-5d9215c94ef4.png)

This is a problem, as in the hierarchy above A.B.postgresql & A.C.postgresql share a common release name.  

**Problem Feature Will Solve**

Currently, for project formsflow, hierarchy is such that 
```
formsflow
  - forms-flow-ai
    -- postgresql
  - forms-flow-idm
    -- keycloak
      --- postgresql
```
In the above hierarchy, formsflow.forms-flow-ai.postgresql.service & formsflow.forms-flow-idm.keycloak.postgres.service will be able to select postgresql pods that do not belong to them. 

e.g
![image](https://user-images.githubusercontent.com/93226309/199624562-85d8f1f5-4ae4-466e-8bec-f3ecc4155240.png)
![image](https://user-images.githubusercontent.com/93226309/199624762-09829cf2-3a20-4048-9d12-d48fde7a550a.png)
![image](https://user-images.githubusercontent.com/93226309/199624866-795a720f-5943-4269-a1fd-272d6d9e3f91.png)
![image](https://user-images.githubusercontent.com/93226309/199624953-a3f5b0d3-6977-4183-bb1c-a7368d1d8748.png)

 

### What is the feature you are proposing to solve the problem?

- Allow common.labels.matchLabels to overwrite default map
- set app.kubernetes.io/instance={{.Chart.Name}} instead. (would avoid the need to overwrite)
- Add primary.service.selector={} to values.yaml (Why not?)

### What alternatives have you considered?

Tried overwriting common.labels.matchLables.  Proved fruitless, not sure if possible to override template functions like variables?  Not templated in code. (should be imo)

**Comment by javsalgar** [comment]
Hi,

Do you have a sample project that triggers the issue? It would help us to reproduce it

**Comment by cberg-aot** [comment]
@jotamartos where you able to investigate/validate if this was a issue that affects other users/charts?

**Comment by jotamartos** [comment]
Hi @cberg-aot,

After evaluating this case, it seems a very specific use case very tied to your scenario.

We highly recommend you check the Kubernetes documentation and try to find a solution for your use case. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
