### ISSUE TITLE
[bitnami/keycloak] Build SPI truststore from plaintext certificate files instead of mounting jks directly

### ISSUE THREAD

**Issue by maxnitze** [bitnami/charts#13353]
### Name and Version

[bitnami/keycloak] 12.1.0

### What is the problem this feature will solve?

Adding additional CA certificates to the trust store requires manual steps to create a secret with the store and its password.

I currently have a script in place, that I need to execute to create a secret with the truststore from a directory containing the certificates (in PEM):

```bash
#!/usr/bin/env bash

BASE_DIR=$(dirname $0)

read -e -i 'keycloak' -p 'Release Name: ' KEYCLOAK_RELEASE_NAME
read -e -i 'keycloak' -p 'Release Namespace: ' KEYCLOAK_RELEASE_NAMESPACE
KEYCLOAK_SPI_KUBERNETES_SECRET_NAME="${KEYCLOAK_RELEASE_NAME}-spi-truststore"
KEYCLOAK_SPI_TRUSTSTORE_TMP_FILE_NAME=/tmp/keycloak-spi.truststore-$(date +"%s").jks
KEYCLOAK_SPI_TRUSTSTORE_PASSWORD=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w10 | head -n 1)

for CERT in ${BASE_DIR}/ca-certificates/*.pem; do
  CERT_NAME=$(basename -- "$CERT" .pem)
  keytool -import -file "${CERT}" -alias "${CERT_NAME}" \
          -keystore ${KEYCLOAK_SPI_TRUSTSTORE_TMP_FILE_NAME} \
          -storepass ${KEYCLOAK_SPI_TRUSTSTORE_PASSWORD} \
          -noprompt -trustcacerts
done

kubectl -n ${KEYCLOAK_RELEASE_NAMESPACE} \
  delete secret ${KEYCLOAK_SPI_KUBERNETES_SECRET_NAME} || true
kubectl -n ${KEYCLOAK_RELEASE_NAMESPACE} \
  create secret generic ${KEYCLOAK_SPI_KUBERNETES_SECRET_NAME} \
  --from-file=keycloak-spi.truststore.jks=${KEYCLOAK_SPI_TRUSTSTORE_TMP_FILE_NAME} \
  --from-literal=spi-truststore-password="${KEYCLOAK_SPI_TRUSTSTORE_PASSWORD}"

rm ${KEYCLOAK_SPI_TRUSTSTORE_TMP_FILE_NAME}

exit 0
```

### What is the feature you are proposing to solve the problem?

I would like to add the CAs as secrets or config maps in the chart and create the truststore on the fly.

There was something like that for the TLS truststore before #13103 was merged.

Most convenient way would be to have a list of secrets and/or configmaps as a new value with CA certificates. This list can then be used in an init container, that creates a new trust store from them.

A "less invasive" approach would be to support getting the truststore from an arbitrary volume instead of a configmap only. Then one can configure an own init container creating the truststore somehow and mounting it into the actual container afterwards.

What do you guys think?

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! Is this something that can be currently achieved by using init containers and the extraDeploy parameters? We may consider doing it in an easier way for users but at least want to confirm this is something currently doable.

**Comment by maxnitze** [comment]
I think technically it is doable right now. But with some overhead/boilerplate. You'd need to create the secret with the certificates, create the keystore from it in an init container, mount that store to the actual container and set the env variable `KEYCLOAK_SPI_TRUSTSTORE_FILE` yourself.

I'd gladly create a PR for this request. Just want to discuss what the desired feature would be: all automated including the init container or just the possibility to provide the truststore file from a volume or any source (not only a secret).

**Comment by javsalgar** [comment]
Hi,

I think that a PR with a new solution would be great. In my opinion, if we add automation to this, I would add all the necessary steps

**Comment by maxnitze** [comment]
Hey, I'm currently preparing a PR for this feature. Can someone remove the stale label? Thanks :)

**Comment by javsalgar** [comment]
Done!
