### ISSUE TITLE
[bitnami/postgresql] Allow a second PVC for backups and pgdumps 

### ISSUE THREAD

**Issue by leelilleorg-meilleur** [bitnami/charts#13351]
### Name and Version

bitnami/postgresql-11.7.1

### What is the problem this feature will solve?

I tried to mount a PVC with the extravolumes and extravolumemounts optin but they don't support creating a new PVC , they seem limited to a config map.

THis will allow the use of an addition PVC  for automated pgdump backups to restore a DB in the future

### What is the feature you are proposing to solve the problem?

To implement a backup strategy for the DB . (I tend to do the pgdumps from the read secondary) 

Allow the use of the storage-CSI driver to manage and provision the extra mount. mount the volume and then schedule  pgdumps to the new volume. 

that way in the event of a db issue  a restore is easy to implement. 

### What alternatives have you considered?

spin up another container and have a cront task to run the pgdump that already has the pv created and mounted. 

down side is it requires another pod

**Comment by javsalgar** [comment]
Hi!

Did you try creating a new PVC using the `extraDeploy` section? There you can add any extra YAML
