### ISSUE TITLE
spark deployment error

### ISSUE THREAD

**Issue by niravdesai5** [bitnami/charts#1335]
Error: render error in "spark/templates/hpa-worker.yaml": template: spark/templates/hpa-worker.yaml:22:10: executing "spark/templates/hpa-worker.yaml" at <tpl>: wrong number of args for tpl: want 2 got 1

**Which chart**:

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by rafariossaa** [comment]
Hi @niravdesai5,
  By adding the bitnami repo and running `helm install bitnami/spark` I got no errors.

  Could you give more information of the steps needed to reproduce this issue ? Also, if you have made changes to the default values.yml, could you provide them ?

**Comment by niravdesai5** [comment]
If I use values-production.yaml to install this image I get error mentioning : expecting 2 got 1 parameter for tpl.

Thank You
Nirav Desai
