### ISSUE TITLE
[bitnami/mariadb-galera] Why I can connect with any ca certificate to MariaDB?

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#13369]
### Name and Version

bitnami/mariadb-galera

### What steps will reproduce the bug?

Hi,
I use this command:
`helm install rezvani bitnami/mariadb-galera --set global.storageClass=rook-cephfs --set tls.enabled=true --set tls.autoGenerated=true --set metrics.enabled=true`

After that I create user with this command:
`create user 'ali'@'%' identified by '123456' REQUIRE SSL;`
 After that when I want to connect to my mariadb instrance from dbeaver, I can connect with any ca certificate that is different from ca cert in secret of mariadb 

### What do you see instead?

I want to have just encryption and not client authentication.
So if I use just ca cert in mariadb secret I can achieve this goal but I can use any cert to connect and It isn't correct!

**Comment by arezvani** [comment]
@javsalgar No I have set password and pass this password. I mean that if I create user and set require ssl, I should connect with tls.
My problem is I can connect with different ca.crt from ca that I that has been set in secret that mariadb helm chart create and I don't get any error.

**Comment by rafariossaa** [comment]
Hi,
  This is what I tried:
```
$ helm install mymysql bitnami/mariadb-galera --set tls.enabled=true --set tls.autoGenerated=true 
```
  Then used the folowing to connect and create the user:
```
$ kubectl run mymysql-mariadb-galera-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/mariadb-galera:10.6.10-debian-11-r11 --command \
-- mysql -h mymysql-mariadb-galera -P 3306 -uroot -p$(kubectl get secret --namespace default mymysql-mariadb-galera -o jsonpath="{.data.mariadb-root-password}" | base64 -d) my_database
If you don't see a command prompt, try pressing enter.
MariaDB [my_database]> create user 'ali'@'%' identified by '123456' REQUIRE SSL;
Query OK, 0 rows affected (0.023 sec)

MariaDB [my_database]> Bye
```
  To check the connection I created a pod and run the commands from there:
```
$ kubectl run mymysql-mariadb-galera-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/mariadb-galera:10.6.10-debian-11-r11 --command -- bash

If you don't see a command prompt, try pressing enter.
I have no name!@mymysql-mariadb-galera-client:/$  mysql -uali -h mymysql-mariadb-galera -P 3306 --ssl -p123456
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 144
Server version: 10.6.10-MariaDB-log Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> Bye



I have no name!@mymysql-mariadb-galera-client:/$  mysql -uali -h mymysql-mariadb-galera -P 3306 -p123456
ERROR 1045 (28000): Access denied for user 'ali'@'172.17.0.1' (using password: YES)
```
  In this new pod I have not certificates.

I am not very sure what you mean with:

> I can connect with any ca certificate that is different from ca cert in secret of mariadb

Could you indicate the command you are using to connect to the database ?

  To connect to mysql using TLS you don't need certs in the client side, is pretty similar to connect to an `https` using your browser.

**Comment by arezvani** [comment]
@rafariossaa Thank you. In this way, how do you prevent Man in the middle attack?

**Comment by rafariossaa** [comment]
Hi @arezvani ,
  I think you could use `--ssl-verify-server-cert` in the client side to check the server certificate. 
  In any case, I would suggest you to ask about those details in mariadb-galera forums. I think they could provide a better answer this.
