### ISSUE TITLE
[bitnami/mariadb] How to load plugin in MariaDB?

### ISSUE THREAD

**Issue by arezvani** [bitnami/charts#13370]
### Name and Version

bitnami/mariadb-galera

### What steps will reproduce the bug?

Hi,
I add
```
[mariadb]
...
plugin_load_add = simple_password_check
```
in to MariaDB configMap and after that liveness probe trrigger and pod restart and log of pod stuck on Starting mariadb in background

I set my replica to 0 and All of PVCs are deleted before apply this changes then change replica to 3.

### What do you see instead?

I want to enable this plugin without any command.

**Comment by javsalgar** [comment]
Hi,

Could you deploy it with `image.debug=true`. This should provide more insight on the issue.
