### ISSUE TITLE
[bitnami/postgresql-ha] Values.metrics.annotations 'annotations is not a method but has arguments'

### ISSUE THREAD

**Issue by B1ue-W01f** [bitnami/charts#13373]
### Name and Version

bitnami/postgresql-ha 10.0.1

### What steps will reproduce the bug?

1. Helm install
2. Using `metrics.enabled: true`
3. Errors out

### Are you using any custom parameters or values?

metrics.enabled: true

### What is the expected behavior?

Should deploy metrics server

### What do you see instead?

Helm install or template fails with the below error.
```
executing "postgresql-ha/templates/postgresql/metrics-service.yaml" at <.Values.metrics.annotations>: annotations is not a method but has arguments
```

**Comment by javsalgar** [comment]
Hi,

I can see the issue

```
    {{- if .Values.metrics.annotations .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}

```

The first line should be

```
    {{- if  or .Values.metrics.annotations .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}

```

Thank you so much for spotting it. Would you like to submit a PR with the fix?

**Comment by xorilog** [comment]
I allowed myself to suggest a PR to fix it, do not hesitate to refuse it if you want to do it @B1ue-W01f

**Comment by javsalgar** [comment]
Thank you so much for the PR!

**Comment by abhilashbs1981** [comment]
I Have this same issue in **9.4.11** chart version as below when service monitor is enabled 

    stderr: Error: Failed to render chart: exit status 1: Error: template: ems-cd-postgres/charts/postgresql-ha/templates/postgresql/servicemonitor.yaml:1                      5:16: executing "ems-cd-postgres/charts/postgresql-ha/templates/postgresql/servicemonitor.yaml" at <.Values.commonAnnotations>: commonAnnotations is not a                       method but has arguments

Seems the same fix need to be put for templates/postgresql/metrics-service.yaml also 

`  annotations:
    {{- if .Values.metrics.annotations .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
`

TO 

```
  annotations:
    {{- if or .Values.metrics.annotations .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.metrics.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}

```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! Would you like to submit a PR? If not we will work on it but we cannot guarantee an ETA.

**Comment by abhilashbs1981** [comment]
No issue , this can be keep aside and include if any future release is planned for 9,4,x
