### ISSUE TITLE
[bitnami/fluentd] Make servicemonitor URL/Path configurable

### ISSUE THREAD

**Issue by tonyjsolano** [bitnami/charts#13388]
### Name and Version

bitnami/fluentd

### What is the problem this feature will solve?

GIves the user the ability to to scrape aggregated_metrics via Prometheus

### What is the feature you are proposing to solve the problem?

Currently, the metrics path is hard coded and would like to make it configurable in servicemonitor.yaml

Hardcoded
`spec:endpoints:path: /metrics`

Please make path configurable

### What alternatives have you considered?

Overriding the fluentd.conf files /aggregated_metrics path with /metrics

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. This could be a configurable value under the `metrics` section. Would you like to submit a PR?
