### ISSUE TITLE
[bitnami/elasticsearch]: cannot add sensitive values to the elastic search keystore in order to configure oidc

### ISSUE THREAD

**Issue by Fabio1177** [bitnami/charts#13384]
### Name and Version

bitnami/elasticsearch 19.4.6

### What is the problem this feature will solve?

While configuring an extra config to configure xpack.security.authc.realms.oidc.oidc1 values, I get an error saying that the value **xpack.security.authc.realms.oidc.oidc1.rp.client_secret** is a sensitive value and should not be found in the elasticsearch.yml file, should be added to the elasticsearch keystore instead. I looked in the default values.yaml file but could not find a way to add this value to the elasticsearch keystore and I need it in order to configure the oidc sso authentication in elastic search, otherwise it is shown an error saying that the value **xpack.security.authc.realms.oidc.oidc1.rp.client_secret** cannot be empty.

### What is the feature you are proposing to solve the problem?

A value in the values.yaml file that could easily be used to add passwords/sensitive data to the elastic search keystore.

**Comment by javsalgar** [comment]
Hi,

Do know which commands are necessary for adding this value to the keystore? Maybe it's something that can be added via init scripts.

**Comment by Fabio1177** [comment]
Hello, I do it's **elasticsearch-keystore add xpack.security.authc.realms.oidc.oidc1.rp.client_secret <<< $"<client-secret>"**.
How can I use/create an init script? Or rather where can I find a way to do it?

**Comment by javsalgar** [comment]
Hi!

Yes, we have init script support in the chart

```
## @param initScripts Dictionary of init scripts. Evaluated as a template.
## Specify dictionary of scripts to be run at first boot
## Alternatively, you can put your scripts under the files/docker-entrypoint-initdb.d directory
## For example:
## initScripts:
##   my_init_script.sh: |
##      #!/bin/sh
##      echo "Do something."
##
initScripts: {}
## @param initScriptsCM ConfigMap with the init scripts. Evaluated as a template.
## Note: This will override initScripts
##
initScriptsCM: ""
## @param initScriptsSecret Secret containing `/docker-entrypoint-initdb.d` scripts to be executed at initialization time that contain sensitive data. Evaluated as a template.
##
initScriptsSecret: ""
## @param extraEnvVars Array containing extra env vars to be added to all pods (evaluated as a template)
## For example:
## extraEnvVars:
##  - name: MY_ENV_VAR
##    value: env_var_value
##

```

**Comment by Fabio1177** [comment]
Sorry for the late response, yes I tried that and it worked, now I can see the value added in the keystore. Thank you so much for your help.

**Comment by javsalgar** [comment]
Awesome! Thanks for letting us know!
