### ISSUE TITLE
[bitnami/keycloak] Upgrade default image tag to release 20

### ISSUE THREAD

**Issue by davgia** [bitnami/charts#13407]
### Name and Version

bitnami/keycloak 12.1.1

### What is the problem this feature will solve?

Multiple new features and bug fixes for new admin console

### What is the feature you are proposing to solve the problem?

Just create a new major chart release bumping default image.tag version to 20.0.1-debian-11-r0 (already available)

### What alternatives have you considered?

overriding the image.tag value

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by carrodher** [comment]
We are happy to share with you that the new Keycloak major version (20.x.x) was already released, see https://github.com/bitnami/charts/pull/14031.

You can find it as usual after updating the Bitnami Helm repo
```console
$ helm repo update bitnami && helm search repo keycloak
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/keycloak	13.0.0       	20.0.2     	Keycloak is a high performance Java-based ident...
```

Thanks for your patience!
