### ISSUE TITLE
Make redis-cluster chart backwards compatible for Redis 6 (not only Redis 7)

### ISSUE THREAD

**Issue by anessi** [bitnami/charts#13409]
### Name and Version

bitnami/redis-cluster 8.2.7

### What is the problem this feature will solve?

Currently the bitnami/redis-cluster chart version 8.2.7 only supports Redis 7 but I still need to support Redis 6. I can't just use the old chart version that was still supporting Redis 6 because that version (7.6.4) does not have additional features implemented in the meantime (e.g. `securityContext` on the `metrics` image).

Looking at the changes that have been implemented between the last version that supported Redis 6 (chart version 7.6.4, https://github.com/bitnami/charts/commit/d1b297eb06a01c57194e9434cd5b3d026038f7cf) and the current version, there seems to be only one incompatible change which is the default configuration used in https://github.com/anessi/bitnami-charts/blob/main/bitnami/redis-cluster/templates/configmap.yaml
This configuration is specific to Redis 7 and does not work for Redis 6. There is no way to override this configuration in the chart values file.

### What is the feature you are proposing to solve the problem?

A possible approach could be to provide both default configurations and use the correct one depending on an optional property in the values file (e.g. `redis.majorVersion`). If this property is not provided, one could revert back to the `appVersion` in the `Chart.yaml` file.

Please let me know if you're willing to receive a PR for this or if this should be addressed differently.

### What alternatives have you considered?

It would be possible to back-port the changes done on chart version 8.2.7 to the 7.6.4 version, but I did not see any way how to do this (e.g. how to fix issues on older chart versions). Is this supported or not?

Another approach could be to allow to set the default config in the values file and not have it hardcoded in the chart.

**Comment by carrodher** [comment]
Hi, unfortunately, this is not something we plan to do in the short term.

If you would like to use a previous version of the application you have two options:
- Use a previous version of the Helm chart where the App version is the one you would like to deploy
- Use the current Helm chart but override the `image.tag` parameter to use a previous container image (although this path is not something tested nor verified by our CI/CD)

**Comment by anessi** [comment]
Hi @carrodher, thanks for the feedback. Unfortunately both approaches don't work because the older chart versions are missing some features which are implemented in the newest chart version already and just overriding the image tag also does not work because the embedded config in the chart only works for Redis 7 but not for Redis 6.

Would you accept a pull request that add the possibility to choose between two default configs (Redis 6 or Redis 7) or allow to override the initial config using a properties in the values file? If yes, let me know what you prefer and I can implement this.

**Comment by carrodher** [comment]
Currently, there is a `redis.configmap` parameter that adds addition configuration for the nodes, but probably the new configuration is appended to the existing one. Feel free to create a PR adding a parameter to fully override the default configuration.

**Comment by anessi** [comment]
fixed with #13545

The default configuration can now be set with
```
redis:
  defaultConfigOverride: |-
    # ....
```
