### ISSUE TITLE
[bitnami/kafka] UseCGroupMemoryLimitForHeap not supported by JMX exporter

### ISSUE THREAD

**Issue by Kebree** [bitnami/charts#13428]
### Name and Version

bitnami/kafka 19.1.2

### What steps will reproduce the bug?

In the values.yaml, activate the jmx exporter thanks to the option :
```
kafka:
  metrics:
    jmx:
      enabled: true
```

### What is the expected behavior?

JMX metrics should be exposed.

### What do you see instead?

The JMX containter is crash looping with an error saying UseCGroupMemoryLimitForHeap  is an unsupported option, and thus preventing the kafka pod to be healthy.

### Additional information

I think the faulty line is : [bitnami/kafka/templates/statefulset.yaml#L476](https://github.com/bitnami/charts/blob/b95989761f3feccc073f6739d4df62bf59ae34b7/bitnami/kafka/templates/statefulset.yaml#L476)

**Comment by javsalgar** [comment]
Hi!

Thanks for spotting the issue. Would you like to submit a PR with the fix?

**Comment by jouve** [comment]
change in bitnami/containers:  https://github.com/bitnami/containers/commit/202ecbff3faf1a9606f2f511da95745e0c356a3a that upgraded java from 8 to 11

and this repo: https://github.com/bitnami/charts/commit/fa439b2f32a6052e4da68d6be7f4a50e31c3fc43

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PRs! The team will take a look
