### ISSUE TITLE
How to add odoo memory configuration?

### ISSUE THREAD

**Issue by jas-odoo** [bitnami/charts#13427]
### Name and Version

bitname/odoo

### What steps will reproduce the bug?

How to add odoo memory related configuration?

- limit_memory_hard
- limit_memory_soft
- workers

### What do you see instead?

Not able to find any related values in https://github.com/bitnami/charts/blob/main/bitnami/odoo/values.yaml

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
