### ISSUE TITLE
[bitnami/solr] pod is in container creating state due to  FailedCreatePodContainer error

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#13454]
### Name and Version

bitnami/solr , latest

### What steps will reproduce the bug?

helm install solr 

### What is the expected behavior?

pod should be created successfully.

### What do you see instead?

pod was working fine but after some data indexing operation from mysql , it crashed . it is in container creating state .

### Additional information

output of kubectl describe pod 
![Screenshot from 2022-11-10 15-59-47](https://user-images.githubusercontent.com/68244292/201067507-5914d385-ce37-4e02-bd40-56d4cdc319ad.png)

**Comment by javsalgar** [comment]
Hi,

Looking at the `describe` output, it seems to me that the issue lies in the Kubernetes cluster, which is out of memory. Could you check the issue in the cluster to see why it is out of memory?
