### ISSUE TITLE
bitnami/redis-cluster  pod启动时候，报错/bitnami/redis/data/nodes.sh: Permission denied，如何解决？

### ISSUE THREAD

**Issue by leqii-com** [bitnami/charts#13453]
### Name and Version

bitnami/redis-cluster --version 8.2.7

### What steps will reproduce the bug?

你好：
我在用如下链接中的helm部署redis-cluster
https://artifacthub.io/packages/helm/bitnami/redis-cluster

其他的都正常，唯独pod启动失败了，报错内容：
/opt/bitnami/scripts/librediscluster.sh: line 202: /bitnami/redis/data/nodes.sh: Permission denied

### Are you using any custom parameters or values?

null

### What is the expected behavior?

null

### What do you see instead?

null

**Comment by carrodher** [comment]
Could you please provide a more descriptive paragraph (in English) about the issue? Also, it would be nice to have more info about the environment and the commands you are executing to deploy the solution.

**Comment by leqii-com** [comment]
use command in K8S node：
helm install redis-cluster bitnami/redis-cluster -ndev

everyone pod, echo 'error'：
/opt/bitnami/scripts/librediscluster.sh: line 202: /bitnami/redis/data/nodes.sh: Permission denied

**Comment by carrodher** [comment]
We are not able to reproduce the issue, are you using any customization or parameter?

**Comment by frankieci** [comment]
> ### Name and Version
> bitnami/redis-cluster --version 8.2.7
> 
> ### What steps will reproduce the bug?
> 你好： 我在用如下链接中的helm部署redis-cluster https://artifacthub.io/packages/helm/bitnami/redis-cluster
> 
> 其他的都正常，唯独pod启动失败了，报错内容： /opt/bitnami/scripts/librediscluster.sh: line 202: /bitnami/redis/data/nodes.sh: Permission denied
> 
> ### Are you using any custom parameters or values?
> null
> 
> ### What is the expected behavior?
> null
> 
> ### What do you see instead?
> null
> 
> ### Additional information
> _No response_

@leqii-com how to resovle it ? You resolved? Can you share your answer？
