### ISSUE TITLE
bitnami/redis Setting up behind ELB

### ISSUE THREAD

**Issue by royassis** [bitnami/charts#13483]
### Describe your issue as much as you can

Hey there

I'm trying to set up bitnami/redis chart using helm on aws eks, behind an elb.

```shell
#when running:
kubectl describe svc/redis-master -n redis-ns

# I get:
Error syncing load balancer: failed to ensure load balancer: could not find any suitable subnets for creating the ELB
```

Any help will be appreciated
Roy

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Redis container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by royassis** [comment]
@carrodher can you please reference me to the guides and the user forums?

**Comment by prince11jose** [comment]
> ### Describe your issue as much as you can
> Hey there
> 
> I'm trying to set up bitnami/redis chart using helm on aws eks, behind an elb.
> 
> ```shell
> #when running:
> kubectl describe svc/redis-master -n redis-ns
> 
> # I get:
> Error syncing load balancer: failed to ensure load balancer: could not find any suitable subnets for creating the ELB
> ```
> 
> Any help will be appreciated Roy

Were you able to find a solution for this. ? I'm doing the same thing trying to deploy redis helm chart with master.service.type=LoadBalancer and replica.service.type=LoadBalancer. 

{"level":"error","ts":"2023-12-21T15:16:12Z","msg":"Reconciler error","controller":"service","object":{"name":"redis-master","namespace":"backend"},"namespace":"backend","name":"redis-  │
│master","reconcileID":"e2ae829d-5a24-472b-90b0-b3822606a850","error":"unable to resolve at least one subnet (0 match VPC and tags)"}
