### ISSUE TITLE
[bitnami/spark] Spark Web UI redirect to wrong path after clicking an icon of either stages, storage, environment, or executors

### ISSUE THREAD

**Issue by omygod613** [bitnami/charts#13498]
### Name and Version

bitnami/spark:6.3.9

### What steps will reproduce the bug?

I deployed bitnami/spark:6.3.9 with the following config:
```
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://<my-spark-domain>
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://<my-spark-domain>
```

then run `spark-submit --master spark://my-spark-master-svc:7077   --class org.apache.spark.examples.SparkPi examples/jars/spark-examples_2.12-3.3.0.jar 1000` inside the spark master pod

### What do you see instead?

After I click the running application, it redirects to `http://<my-spark-domain>/<app-xxxx>/jobs` which is correct. However, I clicks any of the icons including stages, storage, environment, or executors. it redirects to `http://<my-spark-domain>/stages`, `http://<my-spark-domain>/storage`, etc..., then back to the main page. I have to manually add the `app_id` to the url. 

### What is the expected behavior?

When I click a icon on the top bar, it should redirect to the right path like `http://<my-spark-domain>/<app-xxxx>/<icon_name>` instead of `http://<my-spark-domain>/<icon_name>`

**Comment by javsalgar** [comment]
Hi!

Looking at the configuration, it is not clear to me if this is an issue with the Spark configuration done by the Bitnami chart or Spark itself. Did you try checking with the upstream Spark devs?
