### ISSUE TITLE
[rabbitmq-cluster-operator/messaging-topology-operator] Missing secret edit clusterrole permission

### ISSUE THREAD

**Issue by SupermanAdam007** [bitnami/charts#13497]
### Name and Version

bitnami/rabbitmq-cluster-operator

### What steps will reproduce the bug?

Since [messaging-topology-operator/user_controller.go](https://github.com/rabbitmq/messaging-topology-operator/blob/main/controllers/user_controller.go#L57) introduce autogenerated user password when it's empty in predefined secret, the operator has to be able to update this secret.

### What is the expected behavior?

Successful User reconciliation.

### What do you see instead?

```
{"level":"error","ts":1668375603.9739568,"msg":"Reconciler error","controller":"user","controllerGroup":"rabbitmq.com","controllerKind":"User","user":{"name":"test-user-0","namespace":"playground"},"namespace":"playground","name":"test-user-0","reconcileID":"f51ba5d1-4af8-40e2-b3c8-afb6fbf4ee96","error":"secrets \"test-user-0-user-credentials\" is forbidden: User \"system:serviceaccount:playground:rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator\" cannot update resource \"secrets\" in API group \"\" in the namespace \"playground\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

**Comment by SupermanAdam007** [comment]
I would like to contribute but it's not clear to me how to even create a branch. <img width="1440" alt="Screenshot 2022-11-13 at 23 16 14" src="https://user-images.githubusercontent.com/24621199/201547270-02156a1d-24a3-4984-8261-86571418bd95.png">

The solution is to add:
```
      - patch
      - update
```
after [this line](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrole.yaml#L31).

Thanks!

**Comment by javsalgar** [comment]
Hi!!

Thank you so much for the proposed solution. You should create a fork of the repo, then create your custom branch inside it and then create a PR. Did you check the Contributing guidelines? https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md

**Comment by SupermanAdam007** [comment]
@javsalgar Sorry I'm noob in open-source. It did look like a pain process but it was pretty smooth at the end. Thank you! 👍 
https://github.com/bitnami/charts/pull/13613
