### ISSUE TITLE
Support kube-prometheus co-existence with the prometheus-operator in 'openshift-monitoring'

### ISSUE THREAD

**Issue by mlashley** [bitnami/charts#13525]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

If you deploy the kube-prometheus chart to an Openshift cluster already running RH's cluster-monitoring functionality - you end up with 2 prometheus-operators fighting of the same kind:Prometheus and you break the existing openshift-controlled prometheus-etc. instances.

### What is the feature you are proposing to solve the problem?

Expose the existing operator's `-namespace` argument in the helm chart. Not specifying a value causes the existing behaviour (no argument is added, all namespaces are watched.), specifying a value injects the `-namespaces` argument to the operator, and causes it to watch the specific NS only (allowlist)

### What alternatives have you considered?

operator.args _could_ be used here, but then I have to keep all the the other currently-templated-args under my control - it is a hammer to crack a nut.
Better, have the chart support the upstream operator configurable explicitly.

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback
