### ISSUE TITLE
metallb controller missing argument --webhook-mode=enabled 

### ISSUE THREAD

**Issue by AndreasDeCrinis** [bitnami/charts#13524]
### Name and Version

bitnami/metallb

### What steps will reproduce the bug?

1. OnPrem kubernetes cluster with version 1.24.8
2. install bitnami/metallb helm chart  version > 4.0.0
3. apply an address pool
4. update bitnami/metallb helm chart version to something newer
5. reapply address pool
6. fails with error x509: certificate signed by unknown authority

### What is the expected behavior?

no certificate error, addresspool is applicable without error 

### What do you see instead?

```
Failed to patch object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://metallb-webhook-service.caas-metallb.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": x509: certificate signed by unknown authority","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://metallb-webhook-service.caas-metallb.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": x509: certificate signed by unknown authority"}]},"code":500}
```

### Additional information

https://github.com/bitnami/charts/blob/main/bitnami/metallb/templates/controller/deployment.yaml#L90-L92

adding `--webhook-mode=enabled` as additional argument solved it
this is the values.yaml we have to provide to make it work.
```yaml
controller:
  args:  
  - --port=7472
  - --cert-service-name=metallb-webhook-service
  - --webhook-mode=enabled
```

upstream metallb chart makes webhook-mode parametrizeable
https://github.com/metallb/metallb/blob/main/charts/metallb/templates/controller.yaml#L66

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
