### ISSUE TITLE
ClickHouse does not have cluster authentication set up by default.

### ISSUE THREAD

**Issue by RossRothenstine** [bitnami/charts#13541]
### Name and Version

bitnami/clickhouse 1.0.3

### What steps will reproduce the bug?

1. Install the chart via helm with default values. 
```
helm3 install clickhouse bitnami/clickhouse --namespace clickhouse --create-namespace
```

2. Exec into a ClickHouse shard.
```
k exec -n clickhouse clickhouse-shard0-0 -it -- clickhouse-client --user default --password $(kubectl get secret --namespace clickhouse clickhouse -o jsonpath="{.data.admin-password}" | base64 -d)
```

3. Create a database. Note the on cluster and engine are important.
```
 CREATE DATABASE my_database ON CLUSTER default ENGINE=Atomic;
USE my_database;
```

4. Create a table. This will be the local part of the distributed table.
```
 CREATE TABLE logs_local ON CLUSTER default(ts DateTime, text String) ENGINE=MergeTree ORDER BY ts PARTITION BY toStartOfHour(ts) TTL ts + toIntervalWeek(1);
```

5. Create the distributed table.

```
CREATE TABLE logs ON CLUSTER default AS logs_local ENGINE = Distributed(default, my_database, logs_local, rand());
```

6. Attempt to select.

```
 SELECT * FROM logs;
```
 
 7. Observe the following output:
 
 ```
clickhouse-shard0-0.clickhouse-headless.clickhouse.svc.cluster.local :) SELECT * FROM logs;

SELECT *
FROM logs

Query id: 34e3d725-8ce4-433c-a778-779d7b29f5b7


0 rows in set. Elapsed: 0.060 sec.

Received exception from server (version 22.9.4):
Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: Received from clickhouse-shard1-1.clickhouse-headless.clickhouse.svc.cluster.local:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)
```

### What is the expected behavior?

Shards should be able to communicate with each other.

### What do you see instead?

There are permission problems talking to other shards.

### Additional information

The default user should have access to all other shards. Its possible to achieve this by overriding the config and the user. However this is unintuitive to new users who would use ClickHouse.

**Comment by RossRothenstine** [comment]
It seems like this could be solved in the container by modifying the users.xml inside the [postunpack.sh](https://github.com/bitnami/containers/blob/eeb6bebcf74fcb366636c9329b43f4b68ac5d56b/bitnami/clickhouse/22.6/debian-11/rootfs/opt/bitnami/scripts/clickhouse/postunpack.sh#L60) script.

**Comment by RossRothenstine** [comment]
Hey! I won't have time to take a look at this with the upcoming holidays and my vacation. Sorry about that. :pray:

**Comment by yywing** [comment]
zookeeper does not have authentication too .

**Comment by yywing** [comment]
And, clickhouse will use [clickhouse keeper](https://clickhouse.com/docs/en/operations/clickhouse-keeper/) to replace zookeeper.

Official docs remove pre-production in [this commit](https://github.com/ClickHouse/ClickHouse/commit/fb08c5b7e14d9c5e54d8151f98f37192dd89c348) on Apr 15, 2022.. 

But this issue [In a degenerate scenario with concurrent writes, Keeper performance is about 10x lower than zookeeper](https://github.com/ClickHouse/ClickHouse/issues/41045#top) is not close.

**Comment by marcosbc** [comment]
Hi everyone, I have created an internal task for looking into this. Unfortunately I cannot provide an ETA for when we will be able to look into this. In the meantime, if you happen to find a solution to this issue, feel free to contribute it via a PR.

**Comment by KevinLiangX** [comment]
Hello  any solution for this issue?

**Comment by dgomezleon** [comment]
Unfortunately, after analyzing internally our priorities and due to other issues/initiatives we are working on, we didn’t find the bandwidth to implement this feature yet. Of course, we encourage anyone interested to create a PR that solves the issue.
