### ISSUE TITLE
when CeleryKubernetesExecutor is not allowing scheduler to run

### ISSUE THREAD

**Issue by alon050** [bitnami/charts#13544]
### Name and Version

bitnami/airflow:2.4.2

### What steps will reproduce the bug?

change executor to `CeleryKubernetesExecutor`, and `helm install` it on openshift.

### What is the expected behavior?

the expected behavior is for it to run properly and when needed more worker pods to go up to shut down

### What do you see instead?

instead, I get and Error
```
Kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response body: {kind:Status, apiVersion:v1,metadata:{},status:failure,message:pods is forbidden: User \system:serviceaccount:<namespace>:default\ cannot list resource pods in API group \ in the namespace <namespace> reason: Forbidden, details: {kind:pods} code: 403
```
I have full permissions on my cluster and when I'm connected to the namespace I can run `oc get pods` in my cmd.
I also tried to enable the `serviceAccount` feature but it doesn't work also.

**Comment by corico44** [comment]
Hello @alon050, I can't reproduce the error. Using the indicated parameters, it works fine for me. Could you tell me if you have applied any other changes and what version of helm and airflow are you using?
