### ISSUE TITLE
[bitnami/redis-cluster] Cluster topology failed with 4 master and 8 replicas

### ISSUE THREAD

**Issue by benmathy** [bitnami/charts#13564]
### Name and Version

bitnami/redis-cluster version redis 7.0.5

### What steps will reproduce the bug?

i want to create redis cluster with sharding mode ( 4 master and 8 slaves) by using helm command.

result:
12 pods was created but i obtain cluster topology like this:
3 masters with 1 replicas ( default cluster when you don't set cluster.nodes and cluster.replicas in my mind)
6 master standalone with no slot

  

### Are you using any custom parameters or values?

command use:
```
./helm upgrade --install releasev1 --set podSecurityContext.enabled=false --set containerSecurityContext.enabled=false --set containerSecurityContext.runAsUser=auto --set password=XXXX --set cluster.nodes=12 --set cluster.replicas=2 bitnami/redis-cluster
```
### What is the expected behavior?

i need topology 4 master with 2 replicas

### What do you see instead?

i see cluster redis sharding mode with 3 master/1 replicas and 6 master in standalone mode ( not include in cluster)

**Comment by aoterolorenzo** [comment]
Hi @benmathy,

Could you give us more details about the environment (k8s cluster, number of nodes...) and custom values you are using?
