### ISSUE TITLE
[bitnami/nginx] HPA failure when cloneStaticSiteFromGit and Autocaling are both enabled

### ISSUE THREAD

**Issue by nikolaystoynov85** [bitnami/charts#13579]
### Name and Version

bitnami/nginx 13.2.13

### What steps will reproduce the bug?

1. Enable Autoscaling by setting it to true.
2. Enable cloneStaticSiteFromGit by setting in to true.

### What is the expected behavior?

The helm chart to expose params to define the `git-repo-syncer` resources 

### What do you see instead?

No such params are exposed 

### Additional information

The issue is that the HPA is stuck with unknown metrics due to the fact that the main nginx container resources are defined, but the sidecar container are unbound breaking the HPA

**Comment by jotamartos** [comment]
Hi @nikolaystoynov85,

Thank you for reporting the issue. I think it's related with this other issue https://github.com/bitnami/charts/issues/13626 and its PR

https://github.com/bitnami/charts/pull/13627

Can you take a look at the changes and provide feedback?

Thanks

**Comment by nikolaystoynov85** [comment]
Hi @jotamartos,

The issue in the ticket you've shared is completely unrelated. I do appologize for the brief ticket details but there is not much more to mention really. 

When `cloneStaticSiteFromGit` is enabled, that forces adding the sidecar container that monitor the git repository and refresh repo assets in the pod. Then enabling `Autocalling` alongside that create a HPA which in order to create valid metrics requires both the main (nginx) and sidecar (git syncer) containers to have explicitly defined request/limit resources. 

From what I've found in the chart's source code is the resources for the side car container (https://github.com/bitnami/charts/blob/d776600cb83a01fc0b5f8241e60bc1b70d809acc/bitnami/nginx/templates/deployment.yaml#L113) is not either exporsed, nor set by default contrary to the nginx container (https://github.com/bitnami/charts/blob/d776600cb83a01fc0b5f8241e60bc1b70d809acc/bitnami/nginx/templates/deployment.yaml#L219)

Thanks,
Nikolay

**Comment by jotamartos** [comment]
Just a quick note that we continue evaluating this.

**Comment by jotamartos** [comment]
Hi @nikolaystoynov85, 

I just created a PR to solve this issue. I noticed the .git folder was not copied correctly and the deployment was failing. I tested the changes and the solution worked properly 

```
$ kubectl get all
NAME                              READY   STATUS    RESTARTS   AGE
pod/jota-nginx-5bd84b6864-ln9j8   2/2     Running   0          7m12s
pod/jota-nginx-5bd84b6864-xmk42   2/2     Running   0          7m29s

NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE
service/jota-nginx   LoadBalancer   10.159.27.248   34.85.237.39   80:32238/TCP   7m29s

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jota-nginx   2/2     2            2           7m29s

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/jota-nginx-5bd84b6864   2         2         2       7m29s

NAME                                             REFERENCE               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/jota-nginx   Deployment/jota-nginx   <unknown>/80%   2         4         2          7m29s
```

**Comment by nikolaystoynov85** [comment]
Hi @jotamartos,

What you've just shared, and I didn't which I appologise for, is exactly where the issue lies. The chart deployed all fine for me, but because the HPA Target is `<unknown>/80%` that'll never scale up. As I pointed earlier, that's due to the chart not setting default/exposing the `git-repo-synce` container resources, so they're unbound breaking the HPA calculations.

Many Thanks,
Nikolay

**Comment by jotamartos** [comment]
According to the kubernetes documentation 

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

>For per-pod resource metrics (like CPU), the controller fetches the metrics from the resource metrics API for each Pod targeted by the HorizontalPodAutoscaler. Then, if a target utilization value is set, the controller calculates the utilization value as a percentage of the equivalent resource request on the containers in each Pod. If a target raw value is set, the raw metric values are used directly. The controller then takes the mean of the utilization or the raw value (depending on the type of target specified) across all targeted Pods, and produces a ratio used to scale the number of desired replicas.

>Please note that if some of the Pod's containers do not have the relevant resource request set, CPU utilization for the Pod will not be defined and the autoscaler will not take any action for that metric. See the algorithm details section below for more information about how the autoscaling algorithm works.

That said, if you configure the `resources.requests` parameter in the chart, the horizontalpodautoscaler resource will be able to calculate the percentage of CPU the solution is using based on the usage of the nginx container that is the one that is configuring the resources parameters.

```
NAME          REFERENCE                TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
jota-nginx   Deployment/jota-nginx   4%/50%    2         4         2          9m32s
```

We believe that monitoring the nginx container is the right way to go here but if you think that the solution should also monitor the syncer container, we welcome you to create a PR (contributing guide is [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md)) in this repository to configure the limits and requests parameters in that container. You can copy the `resources.limits` and `resources.requests` block in the values.yaml file and include it in the `cloneStaticSiteFromGit` block. After that, you can update the deployment.yaml file to use those values if they are defined.

**Comment by jotamartos** [comment]
>As a result the CPU driven scaling is not working as per your initial shared state HPA Targets set to unknown for the current metrics.

Metrics worked for me as I showed above. I can't confirm this 100% but I understand that if a container inside a pod is configuring the "Requests" parameter, that's enough for the HPA to calculate the target value. That's something to ask to the kubernetes' developers to know more about but in my case, metrics worked and the auto scaling would work when necessary.
