### ISSUE TITLE
Is there a way to persist task logs in Airflow?

### ISSUE THREAD

**Issue by anadkatmeet** [bitnami/charts#1358]
**Which chart**:  Airflow

**No way to persist tasks logs**

**Steps to reproduce the issue:**

1. Helm install airflow
2. Run some dags which will create logs under /opt/bitnami/airflow/logs and also saves last run information.
3. Do helm upgrade
4. Logs or last run info, all gone.

Thanks in advance.

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

The only directory that gets persisted by default is `/opt/bitnami/airflow/data`. I'm thinking about two possible solutions:

- Store your logs under the `/opt/bitnami/airflow/data` directory.
- Redirect all your logs to stdout/stderr and use a logging backend (such as ELK) to process and store them.

Regards,
Alejandro

**Comment by anadkatmeet** [comment]
Hello Alejandro,
Worker logs are stored under /opt/bitnami/airflow/logs. I tried to persist this directory, was able to persist, BUT airflow-web doesn't show any previous runs or logs.

Thanks,
Meet

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

Can you check if the volume is mounted to the `airflow-web` container?

Regards,

**Comment by anadkatmeet** [comment]
Okay I noticed that if I restart any one of the pod, it will UI will lose the track of past runs. Now the question is, which directories needs persistence for each pod.
e.g. For airflow-worker, I suppose its /opt/bitnami/airflow/logs
What directories would it be for scheduler and web-server ?

**Comment by alemorcuq** [comment]
Hi, @anadkatmeet.

All the airflow pods use the same image ([bitnami-docker-airflow](https://github.com/bitnami/bitnami-docker-airflow/)), so the `logs` directory is the same (`/opt/bitnami/airflow/logs`) for all of them.

Regards,
Alejandro
