### ISSUE TITLE
[bitnami/fluentd] Plugin 'tail' does not support multi workers configuration

### ISSUE THREAD

**Issue by wanadjanan-kl** [bitnami/charts#13617]
### Name and Version

bitnami/fluentd:1.15.3

### What steps will reproduce the bug?

1. `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. `helm install fluentd -f values.yaml bitnami/fluentd -n log-agents`

### What is the expected behavior?

Can run with Multi-Process worker

### What do you see instead?

I got this line

```
config error file="/opt/bitnami/fluentd/conf/fluentd.conf" error_class=Fluent::ConfigError error="Plugin 'tail' does not support multi workers configuration (Fluent::Plugin::TailInput)"
```

### Additional information

here is a fluentd-inputs.conf:
```
      <system>
        workers 2
      </system>
      
      <source>
        @type http
        port 9880
      </source>

      # Get the logs from the containers running in the node
      <worker 0-1>
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
          tag kubernetes.*
          read_from_head true
          <parse>
            @type json
            time_format %Y-%m-%dT%H:%M:%S.%NZ
            keep_time_key true
            timezone +07:00
          </parse>
        </source>
      </worker>
```
fluentd-output.conf
```
      <match **>
        @type elasticsearch
        host xxxxxx
        port 12345
        user xxxxxx
        password *******
        scheme https
        index_name mylog_index-%Y.%m.%d
        reload_connections false
        reconnect_on_error true
        reload_on_failure true
        request_timeout 15s
        time_key time
        compression_level best_speed
        <buffer tag, time>
          @type file
          path /opt/bitnami/fluentd/logs/buffers/myBuffer.buffer
          chunk_limit_size 200MB
          total_limit_size 10GB
          flush_thread_count 8
          overflow_action throw_exception
          retry_wait 30s
          flush_at_shutdown true
          # flush_interval 5s
          timekey 10s
          timekey_wait 0s
          timekey_use_utc false
          timekey_zone +07:00
          compress gzip
        </buffer>
      </match>
```
and I also config the replicaCount of aggregator to **2**

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by wanadjanan-kl** [comment]
Thank I realized that it's an unsupported feature.

>###  feature unsupported
 plugins do not work on multi-process workers. For example, tail input does not work because in_tail cannot be implemented with multi process.
You can run these plugins with <worker N> directive. See "Configuration" section.

ref. [https://docs.fluentd.org/deployment/multi-process-workers](url)
