### ISSUE TITLE
[bitnami/mysql] Is have MySQL 5.7. x ?

### ISSUE THREAD

**Issue by sfeng1996** [bitnami/charts#13625]
### Name and Version

bitami/mysql

### What is the problem this feature will solve?

none

### What is the feature you are proposing to solve the problem?

none

**Comment by javsalgar** [comment]
Hi,

Could you elaborate more on the issue you are having?

**Comment by sfeng1996** [comment]
> Hi,
> 
> Could you elaborate more on the issue you are having?

I mean, is there any MySQL 5.7. x？，i just found 8.0.x
