### ISSUE TITLE
[bitnami/nginx] Init container fails to clone the git repo

### ISSUE THREAD

**Issue by varac** [bitnami/charts#13626]
### Name and Version

bitnami/nginx:13.2.13

### What steps will reproduce the bug?

1. Environment: K3s `v1.25.2+k3s1`, [fluxcd](https://fluxcd.io) `0.36.0`
2. Using a fluxcd `helmRelease` like this to deploy a static site from a git repo:

<details>
  <summary>helmrelease.yaml</summary>
 
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: website
    namespace: varac
  spec:
    releaseName: website
    chart:
      spec:
        chart: nginx
        version: 13.2.13
        sourceRef:
          kind: HelmRepository
          name: bitnami
          namespace: flux-system
    interval: 24h
    values:
       # See below
</details>

3. Push config to repo, reconcile it with flux.
4. helmrelease will stay in a `CrashLoopBackOff` 

### Are you using any custom parameters or values?

<details>
  <summary>helmrelease values:</summary>
 
    values:
      service:
        type: ClusterIP
      cloneStaticSiteFromGit:
        enabled: true
        repository: https://0xacab.org/varac-projects/hugo-site.git
        branch: production
        interval: 3600
      ingress:
        enabled: true
        hostname: www.varac.net
        extraTls:
          - hosts:
              - varac.net
            secretName: varac.net-tls
          - hosts:
              - www.varac.net
            secretName: www.varac.net-tls
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: zerossl
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
        extraHosts:
          - name: varac.net
            path: /
            annotations:
              kubernetes.io/tls-acme: "true"
              cert-manager.io/cluster-issuer: zerossl
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

</details>

### What is the expected behavior?

The helmrelease pod should start without an error.

### What do you see instead?

4. The helmrelease pod will stay in a `CrashLoopBackOff` with the init container error log of: `fatal: destination path '/app' already exists and is not an empty directory.`

### Additional information

This is similar to #7966 (apache) and has been fixed for the apache chart in #7970.
I propose the same fix for the nginx chart.

**Comment by javsalgar** [comment]
Hi! Thank you so much for the PR! The team will take a look

**Comment by varac** [comment]
@javsalgar I pushed to the PR again, it should be ready now.
