### ISSUE TITLE
etcd-cluster etcd-cluster doesn't start up normally after workers restart

### ISSUE THREAD

**Issue by mordf** [bitnami/charts#1362]
**Which chart**:

- **bitnami/etcd**

**Description**

After restarting one or more Kubernetes workers **etcd-cluster** doesn't retain it's usual state and pods stuck on `CrashLoopBackOf`f, in order to get back to it's normal state you must delete one or more pods, only then they manage to retrieve the data from the snapshot and start.

This is the error:

```console
panic: tocommit(12) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?
goroutine 146 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc42000aa60, 0xe53b29, 0x5d, 0xc42211a360, 0x2, 0x2)                                   /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x162                                                             
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc4201e3650, 0xc)                                                                                                               
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c                                                                      
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc4202a8200, 0x8, 0x328cc94719020e99, 0x3e1ecc146f9a5f45, 0x7a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                               
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:1194 +0x54                                                                     
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.stepFollower(0xc4202a8200, 0x8, 0x328cc94719020e99, 0x3e1ecc146f9a5f45, 0x7a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                          
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:1140 +0x3ff                                                                    
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4202a8200, 0x8, 0x328cc94719020e99, 0x3e1ecc146f9a5f45, 0x7a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                          
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raft.go:868 +0x12f1                                                                    
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*node).run(0xc42007c3c0, 0xc4202a8200)                                                                                                              
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:323 +0x1059                                                                    
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.RestartNode                                                                                                                               
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:223 +0x321
```

**Steps to reproduce the issue:**

1) Install the chart with disasterRecovery and TLS:

```console
$ helm install --name etcd-cluster \
    --set auth.client.secureTransport=true \
    --set auth.client.enableAuthentication=true \
    --set auth.client.existingSecret=etcd-client-certs \
    --set auth.peer.secureTransport=true \
    --set auth.peer.useAutoTLS=true \
    --set auth.rbac.enabled=false \
    --set statefulset.replicaCount=3 \
    --set disasterRecovery.enabled=true \
    --set disasterRecovery.pvc.size=1Gi \
    --set disasterRecovery.cronjob.schedule="*/3 * * * *"  \
    --set persistence.enable=true  \
    --set persistence.size=2Gi \
   --set disasterRecovery.pvc.storageClassName=nfs \
    --set auth.client.existingSecret=etcd-client-certs bitnami/etcd
```

2) Restart one ore more of your Kubernetes workers

Pods are on Error/CrashLoopBackOff states and won't go back to Running unless you delete them manually, also sometimes you need to delete not only the problematic pod but also another pod which is running

**Describe the results you expected:**

Pods would go back to their Running state

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8", GitCommit:"0c6d31a99f81476dfc9871ba3cf3f597bec29b58", GitTreeState:"clean", BuildDate:"2019-07-08T08:38:54Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`
```

**Comment by juan131** [comment]
Hi @mordf 

> Pods are on Error/CrashLoopBackOff states and won't go back to Running unless you delete them manually, also sometimes you need to delete not only the problematic pod but also another pod which is running

The reason why you need a certain number of etcd pods deleted can be found in the function `is_disastrous_failure` (check the link below). When there are less than **(N+1)/2** pods, the recovery process is triggered.

- https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/scripts-configmap.yaml#L72

However, when a worker is restarted, they shouldn't stuck on `CrashLoopBackOf`. As you can check in the `prestop-hook.sh` function (check the link below), members are supposed to leave the cluster (`etcdctl member remove`) when the pods are deleted. Therefore, once they start again, they're added to the cluster as a new member and everything should work.

- https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/scripts-configmap.yaml#L184

How did you restarted those workers? Did you delete the pods?

**Comment by mordf** [comment]
I’m working on AKS in Azure so I just restarted the worker instances

**Comment by juan131** [comment]
Hi @mordf 

I guess that whatever process restart the workers is not deleting the pods following the "standard" approach (guaranteeing the grace period) so the `prestop-hook.sh` is executed:

https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods

Honestly, I'm not sure what can we do in the case that **(N+1)/2** pods are running on a specific worker and it's removed/restarted without allowing the pods to execute the "prestop" hooks. I guess the only thing you can do is to "drain" the node before restarting it (more information at https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)

**Comment by mordf** [comment]
Everything seems to be working now, when I restarted all of my 3 workers etcd-cluster started up normally and managed to retrieve the data.
After that, I restarted only 1-2 of the workers and then 1-2 of the pods were on **STATUS: Error** 
I decided to wait for a few minutes and  K8S restarted them and the cluster was healthy again with the data.

Closing the issue.
