### ISSUE TITLE
[bitnami/elasticsearch] Separate Elasticsearch TLS certificate and CA configuration

### ISSUE THREAD

**Issue by carolili** [bitnami/charts#13635]
### Name and Version

bitnami/elasticsearch 19.5.2

### What is the problem this feature will solve?

- At the moment it seems like you can only provide [a TLS secret that contains the three files](https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml#L247) to the Elasticsearch Helm chart
  - `tls.crt`
  - `tls.key`
  - `ca.crt`
- In the current cluster I am using the TLS certificate (crt, key) is automatically renewed with regular intervals
- It would require a manual intervention each time to copy the new certificate and key to a secret that has the correct format for the Elasticsearch Helm chart (crt, key, CA)
- It would be better to be able to provide the TLS certificate in a separate secret from the CA certificate

### What is the feature you are proposing to solve the problem?

- Allow a more fine-grained certificate configuration as follows with two separate secrets
  - Elasticsearch certificate (`tls.crt`, `tls.key`)
  - CA certificate (`ca.crt`) -- this can also be a configmap
 - If the CA certificate secret (or configmap) is not given, then the behavior would be the same as now to not break backwards compatibility, i.e. expecting one `existingSecret` with `tls.crt`, `tls.key` and `ca.crt`.

### What alternatives have you considered?

- The certificate (crt, key) and CA certificate can perhaps be mounted and manually configured from the Elasticsearch configuration file using `extraVolumes`, `extraVolumeMounts` and `extraConfig` in the Helm chart.
- This seems to be quite complicated as there are many settings for TLS and existing secrets in the Elasticsearch Helm chart. The correct settings also need to be added to the Elasticsearch configuration file. Reaching a working configuration where the chart settings do not interfere with extra file mounts and changes to the configuration seems difficult compared to being able to set the CA certificate separately and fully taking advantage of the Helm chart.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I think it makes sense. If you want to speed up the process, would you like to submit a PR?

**Comment by carolili** [comment]
Hi, thanks for the quick response and for having a look. I think it would be better if someone with more insights into how the chart handles the certificates would create the PR as there seems to be quite a lot of logic surrounding the certificates throughout the chart depending on the configuration. Meanwhile, if I find a way to configure a separate CA certificate with the current chart I can post it back here in case it's useful for someone else.

**Comment by javsalgar** [comment]
Hi,

I think the community will value the alternative method for configuring a separate CA. I will forward this to the team but we cannot guarantee an ETA.

**Comment by dwrss** [comment]
I may be missing something, but I'm note sure that this was solved? I can't see [any config](https://github.com/bitnami/charts/blob/f8249bf1cca9198fd42c23d02409b774b18d3e60/bitnami/elasticsearch/values.yaml#L236) supporting a separate CA cert or any commits/PRs referencing this issue?
