### ISSUE TITLE
Where is "use_redmine" in redmine helm installation?

### ISSUE THREAD

**Issue by iWangJiaxiang** [bitnami/charts#1364]
Hi there,

I have install redmine by helm chart. But I didn't find the bitnami env file `use_redmine` referred to [https://community.bitnami.com/t/how-to-install-plugin/55305/3](https://community.bitnami.com/t/how-to-install-plugin/55305/3) . How can I solve the problem?

Thank you~

**Comment by alemorcuq** [comment]
Hi, @iWangJiaxiang.

There is no `use_redmine` file in the container, those files are only present in our SingleVMs and installers. On containers you don't need them as all the binaries are in the path and all environment variables are loaded by default.

Regards,
Alejandro

**Comment by iWangJiaxiang** [comment]
@alemorcuq Thank you!

Due to many differences in container version, how can I manage the bitnami app inside the container? Such as restart~

**Comment by iWangJiaxiang** [comment]
When I installed plugin inside the  redmine pod container and restarted the redmine, I got error as below:

```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
nami INFO Initializing redmine
redmine INFO Redmine has been already initialized, restoring...
mysql-c INFO Trying to connect to MySQL server
mysql-c INFO Found MySQL server listening at 10.108.139.139:3306
mysql-c INFO MySQL server listening and working at 10.108.139.139:3306
redmine INFO Generating new secret...
Error executing 'postInstallation': bundler: failed to load command: rake (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/rake)
Bundler::ProductionError: You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
by running `bundle install --no-deployment`.
The dependencies in your gemfile changed
You have added to the Gemfile:
* httparty (~> 0.13.7)
/opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile'
/opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:13:in `setup'
/opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
/opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/bitnami/ruby/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

How can I solve this issue?

**Comment by alemorcuq** [comment]
Hi, @iWangJiaxiang.

In Kubernetes, you can just kill the pod in order to restart the service, as it will automatically create a new one.

Regarding your error installing the plugin, can you share the steps you took to install it so I can reproduce the problem?

Regards,
Alejandro

**Comment by iWangJiaxiang** [comment]
Hi, @alemorcuq 

Thanks for your reply. 

---

#### Below is the steps:

1. I installed bitnami redmine chart (v12.0.1) from rancher ui with customised external database and persistent PVC. And until now everything works perfectly :D

```
---
  mariadb: 
    enabled: false
  postgresql: 
    enabled: false
  externalDatabase: 
    host: "10.108.139.139"
    user: "root"
    password: "09WabImBgt"
    port: 3306
  persistence: 
    enabled: true
    existingClaim: "pvc-redmine"
  databaseType: 
    postgresql: false
    mariadb: true
```
2. I tried to install the plugin [redmine_openid_connect](https://github.com/devopskube/redmine_openid_connect). All files were copied to plugin folder correctly.

```
├── plugins
│   ├── README
│   └── redmine_openid_connect-master
│       ├── app
│       │   ├── models
│       │   │   └── oic_session.rb
│       │   └── views
│       │       ├── account
│       │       │   ├── oic_local_login.html.erb
│       │       │   ├── oic_local_logout.html.erb
│       │       │   ├── rpiframe.html.erb
│       │       │   └── sha256.html.erb
│       │       ├── hooks
│       │       │   └── redmine_openid_connect
│       │       │       └── _view_layouts_base_body_bottom.html.erb
│       │       └── settings
│       │           └── _redmine_openid_connect_settings.html.erb
│       ├── CHANGELOG.md
│       ├── config
...
```

3. I used `kubectl exec -it <podname> -n <namespace> -- /bin/bash` to enter ther shell. And then executed commands to install dependencies and mirage database.

```
cd <redmine root path>
bundle install --no-deployment
```

**This step would get interrupted by fatal error about json package version conflict. So I run the following command to work around**

```
apt-get install -y default-libmysqlclient-dev
apt-get install -y libmagickwand-dev imagemagick
...<other commands to install dependencies>
bundle update
```

Finally, migrate the db.

    bundle exec rake redmine:plugins:migrate RAILS_ENV=production

4. Restart redmine by creating `restart.txt`

```
touch tmp/restart.txt
```

Then, refresh your browser

5. Got Error.

```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 10.108.139.139:3306
mysql-c INFO  MySQL server listening and working at 10.108.139.139:3306
redmine INFO  Generating new secret...
Error executing 'postInstallation': bundler: failed to load command: rake (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/rake)
Bundler::ProductionError: You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
by running `bundle install --no-deployment`.
The dependencies in your gemfile changed
You have added to the Gemfile:
* httparty (~> 0.1.07)
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:13:in `setup'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
  /opt/bitnami/ruby/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/bitnami/ruby/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

---

Could you help me out?

Regards,
Wang Jiaxaing

**Comment by andresbono** [comment]
Hi @iWangJiaxiang, as soon as your pod gets restarted, you are going to loose the installed packages because they are not being stored in a persisting volume. Can you try a different approach in which you create your own container image including the plugin that you want to install?

You have this approach explained in detail here: https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005.

I hope you find it useful and you get to install the plugin following the steps.

**Comment by andresbono** [comment]
Hi @iWangJiaxiang, there is another issue opened very related to what you want to do: https://github.com/bitnami/charts/issues/1380. Just mentioning in case you want to keep track of it.

**Comment by iWangJiaxiang** [comment]
Hi @andresbono , thank you for your useful infomation.

According to my helm parameters, I have set a exsiting PVC for storage. My goal is to setup an redmine env that could store all useful data. And could get restored when pod restarted.

To install plugins, there are two main steps:
1. install gem dependencies.
2. migrate db.

After plugins were installed, then db tables ware migrated. So when geting restored, the redmine should read the plugins/themes/configs from PVC and install the plugin dependencies, after which the redmine env would be exactly same as before~

I think I could find further instruction from your infomation. So I just close this issue~
