### ISSUE TITLE
[bitnami/thanos] Upgrade Thanos to 0.29.0

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/charts#13640]
### Name and Version

bitnami/thanos 11.6.2

### What is the problem this feature will solve?

Thanos will be up to date

### What is the feature you are proposing to solve the problem?

Upgrade thanos to 0.29.0

### What alternatives have you considered?

Wait for some more time

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by corico44** [comment]
Hello @Antiarchitect,

We inform you that the issues have been fixed and that version 0.29.0 of Thanos is now available.

Thank you very much for the contribution!

**Comment by Antiarchitect** [comment]
Thank you so much @corico44 :)
