### ISSUE TITLE
[bitnami/ghost] Provide example values.yaml for working Ingress - Bitnami/Ghost

### ISSUE THREAD

**Issue by boscloud** [bitnami/charts#13645]
### Name and Version

bitnami/ghost:19.1.39

### What is the problem this feature will solve?

Setting up an Ingress that works properly via the Helm values is extremely difficult with the current documentation. 

### What is the feature you are proposing to solve the problem?

Please provide a sample value.YAML file that shows the Ingress values needed for Ghost + Ingress to work, that the user can easily copy and use to deploy Ghost + Ingress + CertManager on a K8s cluster.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
