### ISSUE TITLE
[bitnami/keycloak] Keycloak Helm chart not up to date with the app version 20 ?

### ISSUE THREAD

**Issue by baptiste-gaillet** [bitnami/charts#13659]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

We can see that here : https://bitnami.com/stack/keycloak/helm that the app version for keyclaok is 20.0.1.

But if I click on the link on the page (redirected to this git), the last chart on the main branch has the app version 19 ?

### What is the expected behavior?

Have the helm chart on this git with the latest version : 20.0.1

### What do you see instead?

I see the version 19....

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

There is an already existing open ticket that we will update once released the new major version. I'm closing this one in favor of the existing one. See https://github.com/bitnami/charts/issues/13407

**Comment by baptiste-gaillet** [comment]
Thx a lot for your answer @carrodher .

Il will check frequently the chart for the new version ;p
