### ISSUE TITLE
Ability to specify extra arguments to metrics-server in declarative configuration

### ISSUE THREAD

**Issue by georgefintechstudioscom** [bitnami/charts#1365]
**Which chart**:
metrics-server (chart version 3.0.0, app version 0.3.3)

**Description**
I would like to be able to specify arguments like --kublet-insecure-tls in declarative configuration using values.yaml

When specifying the configuration for metrics-server, it is very convenient to be able to include all non-standard configuration in the values.yaml file.  However, after looking at the source of the chart for metrics-server, I did not see a way to specify additional arguments, in a way similar to how helm/charts/stable/cluster-autoscaler does in the deployment.yaml.

If I am not missing something that already exists or is being worked on, I would be happy to submit a PR for this change.

**Steps to reproduce the issue:**

1. Clone bitnami/charts
2. Go to bitnami/metrics-server
3. Go to templates
4. Examine deployment.yaml, spec.template.spec.containers.command

**Describe the results you received:**

After "metrics-server" command and "--secure-port" argument, the template does not use any values to specify additional arguments.

**Describe the results you expected:**

I expect the template language to allow specification of additional arguments from the values file.

**Additional information you deem important (e.g. issue happens only occasionally):**

I will be happy to submit a PR with changes to supply this functionality.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:57:42Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-25T23:53:13Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Hi, @georgefintechstudioscom.

Thank you very much for suggesting this feature and contributing! Feel free to submit a PR implementing this functionality and we will be happy to review it.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
I'm closing this since it's been resolved, thanks!
