### ISSUE TITLE
[bitnami/argo-cd] ApplicationSet controller is missing from deployment

### ISSUE THREAD

**Issue by RichardSufliarsky** [bitnami/charts#13663]
### Name and Version

bitnami/argo-cd

### What is the problem this feature will solve?

Bitnami ArgoCD helm chart is missing ApplicationSet controller deployment definition (https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd/templates/argocd-applicationset). 
Here is the doc: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
This pull request https://github.com/bitnami/charts/pull/9413 added ApplicationSet CRD, but controller deployment is missing.

### What is the feature you are proposing to solve the problem?

Add ApplicationSet controller deployment to helm chart.

### What alternatives have you considered?

Manual installation of ApplicationSet controller is needed when using Bitnami ArgoCD helm chart.

**Comment by javsalgar** [comment]
Hi,

Is this applicationSet controller part of the argo-cd container? Just to ensure we don't have to package an extra binary

**Comment by RichardSufliarsky** [comment]
@javsalgar I hope I understood your question correctly. ApplicationSet controller is same argocd image/container, it just uses different arguments:
```
        - command:
            - entrypoint.sh
            - argocd-applicationset-controller
```
Here is kustomization for it: https://github.com/argoproj/argo-cd/tree/master/manifests/base/applicationset-controller

**Comment by javsalgar** [comment]
Hi!

Thank you so much for letting us know. I will forward this information to the engineering team. If you want to speed up the process (we have a lot on our plate at the moment), would you like to submit a PR with the new controller?
