### ISSUE TITLE
postgresql-ha secret structure

### ISSUE THREAD

**Issue by giuliocalzolari** [bitnami/charts#13660]
### Name and Version

postgresql-ha 10.0.4

### What is the problem this feature will solve?

Secret struture for [postgresql-ha](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/postgresql/secrets.yaml#L18) and [postgresql](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/secrets.yaml#L17) are completely different, and makes it impossible to switch from postgresql to postgresql-ha seamlessly

with a quick adjustment postgresql-ha we can have a better compatibility

### What is the feature you are proposing to solve the problem?

updating [postgresql-ha/templates/postgresql/secrets.yaml](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/postgresql/secrets.yaml#L18) structure can solve the problem and avoid the unclear key in the secret "postgresql-postgres-password"

**Comment by giuliocalzolari** [comment]
PR on his way

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by giuliocalzolari** [comment]
hi @carrodher is on my to-do-list
