### ISSUE TITLE
[bitnami/keycloak] Cannot change Postgres port

### ISSUE THREAD

**Issue by nnobelis** [bitnami/charts#13661]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

I am running Keycloak chart with, Postgres subchart, within Minikube,
Since I want to access the database on my Host, I define Postgres' service to be of type `LoadBalancer`.
Additionally, I want to use another port for the database. Hence I use the following configuration.

### Are you using any custom parameters or values?
```yaml
  postgresql:
    primary:
      service:
        type: "LoadBalancer"
        ports:
          postgresql: 5433
```

### What is the expected behavior?

In Keycloak pod log:
```
keycloak 08:50:45.29 INFO  ==> ** Starting keycloak setup **
keycloak 08:50:45.35 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 08:50:45.46 INFO  ==> Trying to connect to PostgreSQL server my-server-postgresql...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
```

### What do you see instead?

Keycloak should be able to connect to DB:

```
keycloak 08:53:18.28 
keycloak 08:53:18.28 Welcome to the Bitnami keycloak container
keycloak 08:53:18.29 Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 08:53:18.29 Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 08:53:18.29 
keycloak 08:53:18.30 INFO  ==> ** Starting keycloak setup **
keycloak 08:53:18.33 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 08:53:18.39 INFO  ==> Trying to connect to PostgreSQL server my-server-postgresql...
keycloak 08:53:18.43 INFO  ==> Found PostgreSQL server listening at my-server-postgresql:5433
keycloak 08:53:18.48 INFO  ==> Configuring database settings
```

### Additional information

Minikube:
```
minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f
```

Helm version:
```
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```

I think the error lies in `_helpers.tpl`:
```
{{/*
Return the Database port
*/}}
{{- define "keycloak.databasePort" -}}
{{- ternary "5432" .Values.externalDatabase.port .Values.postgresql.enabled | quote -}}
{{- end -}}
```

If I understand the ternary right, the port is always 5432 unless an external database is configured.

**Comment by javsalgar** [comment]
Hi,

I agree that the issue lies there. It should be a reference to the subchart value in that case, however, the ternary operation may crash if the subchart is not enabled. We may need to use an if statement instead. Would you like to submit a PR with the fix ?

Thank you so much for reporting!

**Comment by nnobelis** [comment]
I would love to do a PR !

Please leave me some time though :)

**Comment by javsalgar** [comment]
Awesome, thanks!

**Comment by nnobelis** [comment]
Keep alive please. I am in the process of getting authorization to contribute to the project :)
