### ISSUE TITLE
[bitnami/postgresql-ha] psql-ha/repmgr and huge databases pods liveness/readiness timeouts

### ISSUE THREAD

**Issue by Mihai-CMM** [bitnami/charts#13677]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

In postgresql-ha with a DB of 255 GB any "statefulset" pod destruction or helm upgrade or SS manipulation it takes more than the "default" liveness and readiness probes timeouts and retry schemas to the repmanager to finish the bakup so in the end the pod is killed and enters in this loop : try to replicate data; k8s kills pod

This is not optimal for production envs. If for whatever reason I need to change something in the SS i will need to wait for hours for data to be in sync + I need to manipulate the above checks every time I do this change

Is there any other way to manipulate the cluster? Is there a way to instruct repmgr to do only delta syncs?

```
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: deleting existing directory "/bitnami/postgresql/data"
DEBUG: replication slot "repmgr_slot_1002" exists but is inactive; reusing
NOTICE: starting backup (using pg_basebackup)...
INFO: executing:
  /opt/bitnami/postgresql/bin/pg_basebackup -l "repmgr base backup"  -D /bitnami/postgresql/data -h psql-ha-postgresql-ha-postgresql-0.psql-ha-postgresql-ha-postgresql-headless.psql-ha.svc.datalake-cr-sit -p 5432 -U repmgr -c fast -X stream -S repmgr_slot_1002
```

Thanks 

### Are you using any custom parameters or values?

I am using values.yaml but i dont think this is relevant now. The question is more about the usability

### What is the expected behavior?

to be able to operate psql cluster with huge amount of data

### What do you see instead?

restart loops because that is not replicated fast enough

**Comment by javsalgar** [comment]
Hi,

We enabled an experimental feature that enables pg_rewind, in order to avoid performing huge database syncs. We don't want to enable it in production because it is not tested enough in the community. I think this could be aligned with your use case, could you give it a go?

**Comment by Mihai-CMM** [comment]
pg_rewind for standby failover . Ok I see it now.

Will give a try and report back 
Thanks

**Comment by Mihai-CMM** [comment]
Any clue what I am doing wrong?
I've enabled pg_rewind. Anything else I should do?

```
  ## @param postgresql.usePgRewind Use pg_rewind for standby failover (experimental)
  ##
  usePgRewind: true
```

then I run:

`/usr/local/bin/helm upgrade --namespace psql-ha psql-ha    -f /home/psql/psql.yaml /home/psql/charts/postgresql-ha --set postgresql.password=$POSTGRESQL_PASSWORD --set postgresql.repmgrPassword=$REPMGR_PASSWORD --set pgpool.adminPassword=$ADMIN_PASSWORD
`


```
postgresql-repmgr 13:42:04.16 DEBUG ==> Schema repmgr.repmgr exists!
postgresql-repmgr 13:42:04.17 INFO  ==> Rejoining node...
postgresql-repmgr 13:42:04.17 INFO  ==> Using pg_rewind to primary node...
postgresql-repmgr 13:42:04.17 INFO  ==> Running pg_rewind data to primary node...
pg_rewind: error: could not open file "/bitnami/postgresql/data/global/pg_control" for reading: No such file or directory
postgresql-repmgr 13:42:04.19 WARN  ==> pg_rewind failed, resorting to data cloning
postgresql-repmgr 13:42:04.20 INFO  ==> Cloning data from primary node...
WARNING: following problems with command line parameters detected:
  -D/--pgdata will be ignored if a repmgr configuration file is provided
NOTICE: destination directory "/bitnami/postgresql/data" provided
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
WARNING: data checksums are not enabled and "wal_log_hints" is "off"
DETAIL: pg_rewind requires "wal_log_hints" to be enabled
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: deleting existing directory "/bitnami/postgresql/data"
NOTICE: starting backup (using pg_basebackup)...
```

**Comment by Mihai-CMM** [comment]
Ok,
I've deleted the initial namespace (delete pvc - clean all )/
New install with "usePgRewind: true" and i also needed to provide      wal_log_hints = on under   extendedConf: |- section and now for 156 GB database all seems to be fine
Thank you very much for suggestion
