### ISSUE TITLE
[bitnami/cassandra] Unable to set password in values.yaml or with a secret

### ISSUE THREAD

**Issue by WillUdstrand** [bitnami/charts#1369]
**Which chart**:

chart: binami/cassandra
version: 3.2.0

**Description**
When deploying the cassandra chart on minikube I am unable to successfully set login credentials via the value.yaml file or via a secret.

OS: Windows 10
cqlsh version: 3.11.4
VM: Hyper-V
VM Parameters
```
cpus: 4 cores
ram: 4 GB
memory: 4 GB
```

Cassandra cluster configuration
**values.yaml**
``` values.yaml
resources: 
  requests:
    memory: 2Gi
    cpu: 2
  limits:
    memory: 8Gi
    cpu: 2
...
cluster:
  name: cassandra
  replicaCount: 1
  seedCount: 1
  numTokens: 256
  datacenter: dc1
  rack: rack1
  enableRPC: true
  endpointSnitch: SimpleSnitch
  minimumAvailable: 1
  ## Encryption values. NOTE: They require tlsEncryptionSecretName
  internodeEncryption: none
  clientEncryption: false
  domain: cluster.local
```

**values.yaml**
``` values.yaml
dbUser:
  user: admin
  forcePassword: true
  password: password
```

**values.yaml with secret**
``` values.yaml
dbUser:
  user: admin
  forcePassword: true
  existingSecret: cassandra-3.2.0
```

**secret.yaml**
``` secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-3.2.0
  labels:
    app: cassandra
    chart: cassandra-3.2.0
    release: cassandra
    heritage: Tiller
type: Opaque
data:
  # password
  cassandra-password: password
``` 
**NOTE:** I have tried the secret with username inside, and I have used all possible combination with the forcePassword flag on and off for both approaches.

**Steps to reproduce the issue:**
Without Secret
1. Start the chart using the values.yaml
` helm upgrade --force --install cassandra bitnami/cassandra --values values.yaml --timeout=3600`
2. Once the cassandra is running, port forward it to port 9042
`kubectl port-forward --namespace default svc/cassandra 9042:9042 `
3. Try to connect to cassandra via the cqlsh client
`cqlsh -u admin -p "password" localhost`

**RESULT**
```
Connection error: ('Unable to connect to any servers', {'::1': AuthenticationFailed('Failed to authenticate to ::1: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',), '127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',)})
```
**NOTE:** I get the same result when using the following command rather than port forwarding
`kubectl run --namespace default cassandra-client --rm --tty -i --restart='Never' --env CASSANDRA_PASSWORD=password --labels="cassandra-client=true" --image docker.io/bitnami/cassandra:3.11.4-debian-9-r147 -- bash `

With Secret
1. Create the secret
`kubectl apply -f .\secret.yaml`
2. Follow steps 1-3 from the previous set of steps with the different values.yaml

**RESULT**
```
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',), '::1': AuthenticationFailed('Failed to authenticate to ::1: Error from server: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',)})
```

**Describe the results you received:**
I am unable to sign in and access cassandra through the cqlsh command.

**Describe the results you expected:**
I should be able to sign in and access cassandra through the cqlsh command.

**Additional information you deem important (e.g. issue happens only occasionally):**
I am able to login into cassandra when the password **test** is base64 encoded and placed in the values.yaml file. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}                                                                                                   

Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"} 
```

- Output of `kubectl version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}                                                                                     

Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"} 
```

**Comment by miguelaeh** [comment]
Hi @WillUdstrand ,
Did you try to remove the PVC? They can maintain the old password so you can get an unauthorized error even if you are forcing the password change.
