### ISSUE TITLE
[bitnami/postgresql] Liveness and Readiness Probes are not working in postgresql pod after getting error

### ISSUE THREAD

**Issue by shashiprakashmishra** [bitnami/charts#13693]
### Name and Version

bitnami/postgres-10.16.2

### What steps will reproduce the bug?

we are using the Bitnami chart as service dependency  but we found postgresdb  was not responding  due to error below. but postgres db not restarted . Any reason why why db pod  not restarted after the error
```
022-07-22 06:30:43.487 GMT [96] LOG: could not open temporary statistics file "pg_stat_tmp/global.tmp": Read-only file system
2022-07-22 06:30:43.487 GMT [96] LOG: could not open temporary statistics file "pg_stat_tmp/global.tmp": Read-only file system
2022-07-22 06:30:43.489 GMT [1901207] ERROR: could not open file "base/16384/2601": Read-only file system
2022-07-22 06:30:43.489 GMT [96] LOG: could not open temporary statistics file "pg_stat_tmp/global.tmp": Read-only file system
```

### What is the expected behavior?

pod should restart automatically

### What do you see instead?

I need to restart pod to fix the issue

**Comment by javsalgar** [comment]
Hi,

It seems that you are using `readOnlyRootFilesystem: true`. Please note that our stateful charts are not compatible with that feature.

**Comment by shashiprakashmishra** [comment]
@javsalgar  I checked the value.yaml does not have readOnlyRootFilesystem variable. How to check whether this variable value  is true or false

**Comment by shashiprakashmishra** [comment]
we are using  secutity context only
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - NET_RAW

**Comment by javsalgar** [comment]
Could you try launching the chart with `diagnosticMode.enabled=true`, enter the container and check if you can write in folders the expected folders or not? That should give clues whether the readOnlyRootFilesystem mode is enabled or not.

**Comment by shashiprakashmishra** [comment]
@javsalgar  Thanks for replying, let me update that, I will update you once done

**Comment by shashiprakashmishra** [comment]
@javsalgar I enabled diagnosticMode.enabled=true  at root folder I can't create file at most of folder except tmp showing access denied. another issue I am getting I am not able to connect postgresql with client

**Comment by shashiprakashmishra** [comment]
@aoterolorenzo actually the issue is very random we are not sure when will this issue again appear? sometimes after 1 month or sometimes more than 3 month time frame. after restarting the PostgreSQL pod issue got fix.
if you want to run some specific test then please let me know

**Comment by aoterolorenzo** [comment]
@shashiprakashmishra let's do this: I will open a task for the team to investigate this and at least ensure that the probes are working properly and they obtain at least a database row when performed to ensure the database is alive. I will put the issue in `on-hold` and one of my teammates will reach you here with the outcome.

**Comment by shashiprakashmishra** [comment]
@aoterolorenzo  thanks you for looking into this issue

**Comment by kirankumarkp** [comment]
Hi All, I am also facing similar issue and as part of search i ended up in this thread. In my case even when pod was up still we were unable to connect to the postgres from client  and when checked service logs  could see below error.
**2022-12-07 06:20:44.963 GMT [71] LOG:  could not open temporary statistics file "pg_stat_tmp/global.tmp": Read-only file system**
Went inside the pod to /bitnami/postgresql/data folder and tried to touch a file but its say read only. 
Another observation is , without any changes everything started working fine for some time and again same issue repeats for unknown reason in some uncertain intervals or operations. Not sure why the path or files /bitnami/postgresql/data goes to read only mode. Happy to know this issue is being looked up and thank you. It will be great help.

**Comment by aoterolorenzo** [comment]
@kirankumarkp @shashiprakashmishra Could you provide more information about your clusters? ¿What storageClass are you using?

A describe of the pod/s would be also welcome.


Could your volumes are getting out of space / full?

**Comment by shashiprakashmishra** [comment]
@aoterolorenzo I am using longhorn storage class

**Comment by aoterolorenzo** [comment]
Could you try `kubectl -n <namespace> exec sts/postgresql -- df -ah`? Also a describe for the pod and the volume.

@kirankumarkp in your case the probes are also failing when the error presents?

**Comment by aoterolorenzo** [comment]
Seems also not bitnami-related. Could you give a look into this thread? https://stackoverflow.com/a/32193782 

Seems not an isolated error.

**Comment by shashiprakashmishra** [comment]
/dev/longhorn/test  7.8G  264M  7.6G   4% /bitnami/postgresql

**Comment by aoterolorenzo** [comment]
I'm afraid I'm still unable to reproduce the issue. As mentioned, there is [some literature](https://stackoverflow.com/a/32193782) upstream (in the postgresql native forums and repos), and the probes are also supported upstream (there are not bitnami's), so I only could recommend you to open a ticket to Postgres
