### ISSUE TITLE
[bitnami/postgresql] Postgres chart won't start using NFS volume

### ISSUE THREAD

**Issue by MaxDiOrio** [bitnami/charts#13702]
### Name and Version

bitnami/postgresql:12.1.2

### What steps will reproduce the bug?

1. Rancher 2.7, running an RKE1 cluster on Suse Tumbleweed with K8S 1.24.6
2. Helm install of bitnami:postgresql using mostly default settings.  PVC provisioner is NFS.
3. NFS is shared from Unraid with rw,sync,no_subtree_check,no_root_squash

### Are you using any custom parameters or values?

Helm chart is completely stock other than setting the db, username and password.

### What is the expected behavior?

Pod turns up successfully, data can be written and PGSQL is running

### What do you see instead?
```
postgresql 19:22:28.02
--
postgresql 19:22:28.03 Welcome to the Bitnami postgresql container
postgresql 19:22:28.03 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 19:22:28.03 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 19:22:28.03
postgresql 19:22:28.04 DEBUG ==> Configuring libnss_wrapper...
postgresql 19:22:28.05 INFO  ==> ** Starting PostgreSQL setup **
postgresql 19:22:28.07 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 19:22:28.07 INFO  ==> Loading custom pre-init scripts...
postgresql 19:22:28.08 INFO  ==> Initializing PostgreSQL database...
postgresql 19:22:28.08 DEBUG ==> Ensuring expected directories/files exist...
postgresql 19:22:28.10 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 19:22:28.10 INFO  ==> Generating local authentication configuration
postgresql 19:22:28.16 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 19:22:28.25 INFO  ==> Configuring replication parameters
postgresql 19:22:28.31 INFO  ==> Configuring fsync
postgresql 19:22:28.32 INFO  ==> Configuring synchronous_replication
postgresql 19:22:28.38 INFO  ==> Loading custom scripts...
postgresql 19:22:28.39 INFO  ==> Enabling remote connections
 
postgresql 19:22:28.41 INFO  ==> ** PostgreSQL setup finished! **
postgresql 19:22:28.44 INFO  ==> ** Starting PostgreSQL **
2022-11-25 19:22:28.501 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/data/postgresql.auto.conf"
2022-11-25 19:22:28.511 GMT [1] FATAL:  "/bitnami/postgresql/data" is not a valid data directory
2022-11-25 19:22:28.511 GMT [1] DETAIL:  File "/bitnami/postgresql/data/PG_VERSION" is missing.
```

### Additional information

I have tried setting the volumePermissions.enabled: true but that didn't help at all either.  It creates the data directory in the nfs share, looks like it has the right permissions, but for some reason it's saying the data directory is not valid (it's empty).  No idea why.
```

drwxrwxrwx  1 1001      1001           36B Nov 25 13:41 mastodon-data-postgres-postgresql-0-pvc-109ac5cb-4c39-4c20-8fb4-a256227ca201

drwx------  1 1001      1001            6B Nov 25 14:12 data

```

**Comment by javsalgar** [comment]
Hi,

I'm afraid that NFS volumes is not something we currently test and support. We test our charts in all major Kubernetes distributions with their default filesystems. In this case I'm not sure if it's some sort of incompatibility of PostgreSQL with this kind of volumes. Did you try checking with the upstream PostgreSQL devs for more advice?
