### ISSUE TITLE
cannot start kafka with sasl_tls

### ISSUE THREAD

**Issue by envy16** [bitnami/charts#13708]
### Name and Version

bitnami/kafka 19.1.3

### What steps will reproduce the bug?

I am trying to install kafka with SASL_TLS and I am using the bitnami kafka HELM chart. When I define values for the provisioning job (which is the client) and set `auth.clientProtocol: sasl_tls`, its try to execute the following code:

```
 kafka_common_conf_set "$CLIENT_CONF" security.protocol {{ include "kafka.listenerType" ( dict "protocol" .Values.auth.clientProtocol ) | quote }}
{{- if (include "kafka.client.tlsEncryption" .) }}
kafka_common_conf_set "$CLIENT_CONF" ssl.keystore.type {{ upper .Values.provisioning.auth.tls.type | quote }}
kafka_common_conf_set "$CLIENT_CONF" ssl.truststore.type {{ upper .Values.provisioning.auth.tls.type | quote }}
! is_empty_value "$KAFKA_CLIENT_KEY_PASSWORD" && kafka_common_conf_set "$CLIENT_CONF" ssl.key.password
"$KAFKA_CLIENT_KEY_PASSWORD"
```

### What is the expected behavior?

I expect to provide for provisioning job or any other clients only trustore.jks and pass for it.

### What do you see instead?

I don't need to use keystore and secret key, because I am not using mTLS. All I need for SASL_TLS - trustore and password for it.

It's happened because in _helpers.tpl:

```
{{/*
Return true if encryption via TLS for client connections should be configured
*/}}
{{- define "kafka.client.tlsEncryption" -}}
{{- $tlsProtocols := list "tls" "mtls" "sasl_tls" -}}
{{- if (has .Values.auth.clientProtocol $tlsProtocols) -}}
    {{- true -}}
{{- end -}}
{{- end -}}
```

Please, can you fix this?

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by OneCricketeer** [comment]
As a workaround, have you tried Strimzi Kafka Operator instead of using a Helm Chart?

**Comment by envy16** [comment]
> As a workaround, have you tried Strimzi Kafka Operator instead of using a Helm Chart?

I didn't. This chart meets all my needs. It is only necessary to correct the use of sasl_sl.

**Comment by OneCricketeer** [comment]
How do you plan on managing Kafka itself, or associated resources like Connectors? Strimzi has custom resources for Topics, ACLs, Connectors, it's own REST interface for Kafka, etc. And also supports SASL_SSL setup.

Worth a try/look.

**Comment by envy16** [comment]
> How do you plan on managing Kafka itself, or associated resources like Connectors? Strimzi has custom resources for Topics, ACLs, Connectors, it's own REST interface for Kafka, etc. And also supports SASL_SSL setup.
> 
> Worth a try/look.

I'm sorry, but how is this related to the described problem? Now we are talking about the incorrect implementation of sasl_ssl in this chart.
