### ISSUE TITLE
[bitnami/*] Disable data volumes all together

### ISSUE THREAD

**Issue by rlewkowicz** [bitnami/charts#13715]
### Name and Version

All of them

### What steps will reproduce the bug?

You can disable persistence, but it will still mount an empty volume. If I repackage your container, it overrides all my stuff.

### What is the expected behavior?

If I don't enable persistence, I don't want you mounting empty volumes.

### What do you see instead?

I'd like the base data dirs to be left alone. If I don't enable persistence, I want whats in the container. Not nothing.

**Comment by javsalgar** [comment]
Hi,

Could you explain your use case in more detail? It seems that you are creating a fork with custom data in the volume folder, is that correct?

**Comment by OneCricketeer** [comment]
What specific images are you trying to use? Container volumes should already mostly be empty directories, not locations where the applications already hold configurations.

**Comment by rlewkowicz** [comment]
@javsalgar Correct, but the fork is of the container. So I repackage and store the container and all the wordpress data right on docker hub and I pull it as an entire artifact. It would have been valuable to orchestrate that container with the bitnami helm charts. Even if I don't enable persistence, it will still override that data. 

While the database is small enough, I do the same thing there as well. 

Both mariadb and wordpress helm charts overwrite the data dirs with an empty folder.

I have a work around for now so I'll close this.
