### ISSUE TITLE
Provide provenance files for integrity checks

### ISSUE THREAD

**Issue by dan-m8t** [bitnami/charts#13718]
### Name and Version

bitnami/*

### What is the problem this feature will solve?

As a bitnami user, I want to add an extra security mechanism.
Helm supports the `verify` command which verifies a Helm chart against a provenance file. This file is created by the developers with gpg keys. The helm packages need to be signed at build time with the `--sign` option.

More context here:

https://helm.sh/docs/topics/provenance/
https://helm.sh/docs/helm/helm_verify/

### What is the feature you are proposing to solve the problem?

Sign all the helm packages

**Comment by carrodher** [comment]
Hi, thanks for the suggestion. We are currently working on supporting OCI Helm charts and distribute the whole catalog using OCI
