### ISSUE TITLE
How much memory, CPU Postgres needs to run in a production on prem kubernetes cluster?

### ISSUE THREAD

**Issue by sanasz91mdev** [bitnami/charts#13712]
### Name and Version

bitnami/postgresql latest

### What steps will reproduce the bug?

How much memory, CPU Postgres needs to run in a production on prem kubernetes cluster?
Assuming cluster with 3 worker and master nodes.

Is there and documentation?

### What do you see instead?

- i would have opened it as a discussion instead if there was an option.

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
