### ISSUE TITLE
No option to enable query analytics for slow operations (PMM query analytics)

### ISSUE THREAD

**Issue by cap-pardeepsingh** [bitnami/charts#13719]
### Name and Version

bitnami/mongo 12.0.0

### What is the problem this feature will solve?

Mongo DB allows monitoring with PMM (percona monitoring tool) for query analytics. 
https://www.percona.com/doc/percona-monitoring-and-management/1.x/conf-mongodb.html 
You can enable profiling using `mongod` command when you are starting mongo or you can control it via `mongod.conf` file.

But as of now, in the chart, it seems there is no option to control this behavior. If someone wants to enable query analytics, the chart is not allowing it. Is there a way to achieve this?

### What is the feature you are proposing to solve the problem?

Have configuration in the chart to control the MongoDB profiling which helps further in query analytics.
https://www.percona.com/doc/percona-monitoring-and-management/1.x/conf-mongodb.html 

command way: `mongod --dbpath=DATABASEDIR --profile 2 --slowms 200 --rateLimit 100`
Mongod.conf file:
```yaml
operationProfiling:
   slowOpThresholdMs: 200
   mode: slowOp
   rateLimit: 100
```

**Comment by marcosbc** [comment]
Hi @cap-pardeepsingh, currently this is not something supported by the chart (via parameters). However, you could always define your own configuration file, enabling those options, using the `configuration` parameter.

Also, if you wish, you could contribute this feature to the chart. We are open for contributions and would gladly help with the review and release of the feature.
