### ISSUE TITLE
Unable to "unset" `fsGroup` and `runAsUser`

### ISSUE THREAD

**Issue by ctron** [bitnami/charts#13720]
### Name and Version

bitnami/postresql 12.1.2

### What steps will reproduce the bug?

1. Use `postgresql` chart as dependency
2. Set values in `values.yaml`
   * Set `postgresql.primary.podSecurityContext.fsGroup` to `null`
   * Set `postgresql.primary.containerSecurityContext.runAsUser` to `null`
3. Render template

### Are you using any custom parameters or values?

```yaml
postgresql:
  primary:
    podSecurityContext:
      fsGroup: null
    containerSecurityContext:
      runAsUser: null
      foo: bar
```

### What is the expected behavior?

There should be no `fsGroup` and `runAsUser`  in the final security context.

### What do you see instead?

```console
$ helm template . | grep -A 5 -B 5 security
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      hostNetwork: false
      hostIPC: false
      initContainers:
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:15.1.0-debian-11-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            foo: bar
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
```

**Comment by marcosbc** [comment]
Hi @ctron, I believe there is a typo in one of your parameters. It should be `containerSecurityContext` and not `contextSecurityContext`. Apart from that, don't forget to also set the same values for `readReplicas`.

With these parameters I was able to get no `securityContext` parameters added at all:

```
--set architecture=replication,primary.podSecurityContext.fsGroup=null,primary.containerSecurityContext.runAsUser=null,readReplicas.podSecurityContext.fsGroup=null,readReplicas.containerSecurityContext.runAsUser=null
```

Or:

```
--set architecture=replication,primary.podSecurityContext.enabled=false,primary.containerSecurityContext.enabled=false,readReplicas.podSecurityContext.enabled=false,readReplicas.containerSecurityContext.enabled=false
```

**Comment by ctron** [comment]
True, the typo was in the bullet point list. But not in the `values.yaml` I posted.

Still, I one sets the values in the YAML file to `null`, it is not possible to unset these values.

**Comment by ctron** [comment]
I created a reproducer repository: https://github.com/ctron/postgres-helm-repro

**Comment by marcosbc** [comment]
Thanks for sharing the repo. I am able to reproduce your issues now, but not yet sure why it happens.

Is it not an option for you to use the `enabled: false` options for `podSecurityContext` and `containerSecurityContext`? For example:

```yaml
postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
```

**Comment by marcosbc** [comment]
Hi @ctron, it seems like this is an actual bug of Helm, see: https://github.com/helm/helm/issues/9136

There seems to be a WIP contribution in https://github.com/helm/helm/pull/11440 in case you want to have a look at it and apply it locally on your side, in the meantime.

**Comment by ctron** [comment]
Yea, I am running this with ArgoCD, I have no idea how I could try this out.

**Comment by marcosbc** [comment]
For now, unless you are able to build [helm](https://github.com/helm/helm) on your side with the patch, the best option is to wait until a new release of Helm is published with it.
