### ISSUE TITLE
[bitnami/redmine] Redmine startup problem with external database

### ISSUE THREAD

**Issue by c23omega** [bitnami/charts#13736]
### Name and Version

bitnami/redmine:5.0.3-debian-11-r10

### What steps will reproduce the bug?

i recently installed the redmine helm chart and i want to use it with an external database, so i set the external parameters as listed below. The container doesn't get ready, it gets stuck in the validation. It gets stuck there:
```
redmine 12:12:40.94 
redmine 12:12:40.94 Welcome to the Bitnami redmine container
redmine 12:12:40.94 Subscribe to project updates by watching https://github.com/bitnami/containers
redmine 12:12:40.94 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine 12:12:40.95 
redmine 12:12:40.96 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 12:12:40.97 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 12:12:41.04 INFO  ==> Restoring persisted Redmine installation
redmine 12:12:41.11 INFO  ==> Trying to connect to the database server
```
With that the container gets in a CrashLoopBackOff state.

In the database first nothing was placed, later i placed there a backup of some other redmine backup. Both didn't work.

### Are you using any custom parameters or values?

```
externalDatabase.database: redmine
externalDatabase.host: <host>
externalDatabase.user: redmine
externalDatabase.port: 3306
externalDatabase.password: <hidden>
mariadb.enabled: false
postgresql.enabled: false
```

Besides that some parameters are set regarding ingress and mailing (smtp + email), that should not matter here.

### What is the expected behavior?

The pod should go in a Ready state.

### What do you see instead?

CrashLoopBackOff state of the pod

### Additional information

After some debugging and figuring out how stuff works i found that the issue seems to be in libredmine.sh:144 / libredmine.sh:374. I've added some debug print statements as follows (libredmine.sh:374):
```
    check_mysql_connection() {
        echo "mysql_remote_execute" $db_host $db_port $db_name $db_user $db_pass
        echo "$REDMINE_DATABASE_HOST" "$REDMINE_DATABASE_PORT_NUMBER" "$REDMINE_DATABASE_NAME" "$REDMINE_DATABASE_USER" "$REDMINE_DATABASE_PASSWORD"
        echo "SELECT 1" | mysql_remote_execute "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
    }
```
when i run now redmine again i see
```
root@redmine-564cff57fb-4z2fd:/opt/bitnami/scripts# /opt/bitnami/scripts/redmine/entrypoint.sh /opt/bitnami/scripts/redmine/run.sh
redmine 12:12:40.94 
redmine 12:12:40.94 Welcome to the Bitnami redmine container
redmine 12:12:40.94 Subscribe to project updates by watching https://github.com/bitnami/containers
redmine 12:12:40.94 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine 12:12:40.95 
redmine 12:12:40.96 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 12:12:40.97 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 12:12:41.04 INFO  ==> Restoring persisted Redmine installation
redmine 12:12:41.11 INFO  ==> Trying to connect to the database server
mysql_remote_execute redmine-mariadb 3306 my_database bn_redmine 9WPuBoZ2aq
<host> 3306 redmine redmine <password>
```
It seems that the parameters are not provided as they should, so the database validation fails. The printed database access configuration at last is the right one as it should be. It seems the command does not use the external configuration, but uses the initial automated mariadb configuration, which needs to fail with external databases.

Since there doesn't seem to be a logical problem in the bash code, it seems more like that there is something going wired with the local variables and the local setting on this snippet (libredmine:369-373):
```
    local -r db_host="${1:?missing database host}"
    local -r db_port="${2:?missing database port}"
    local -r db_name="${3:?missing database name}"
    local -r db_user="${4:?missing database user}"
    local -r db_pass="${5:-}"
```

Thank you very much in advance!

**Comment by jotamartos** [comment]
Hi @c23omega,

It seems you did not remove the volumes that were previously generated and that's why Redmine is using the old database configuration instead of the new one. I can see this line in your log 

```
redmine 12:12:41.04 INFO  ==> Restoring persisted Redmine installation
```

https://github.com/bitnami/containers/blob/main/bitnami/redmine/5/debian-11/rootfs/opt/bitnami/scripts/libredmine.sh#L221

As you can see in the libredmine.sh file, the database configuration is obtained from the persisted Redmine's conf file. 

You can try using a different name for your helm installation or remove the old PV and PVC related to this installation to solve this issue. 

Thanks

**Comment by c23omega** [comment]
Hi @jotamartos,

thank you very much for your information. Deleting the pvc did the job, redmine is working now as expected.

Does this mean whenever a helm chart setting on redmine is changed which is stored in the settings, that the pv / pvc needs to be recreated? How to deal there with environments where one wants to keep the data like uploaded files etc, what is there the recommended approach?

Thanks
