### ISSUE TITLE
mariadb-galera readinessProbe

### ISSUE THREAD

**Issue by diepes** [bitnami/charts#13730]
### Name and Version

bitnami/mariadb-galera  7.3.6

### What steps will reproduce the bug?

1. depoy 3 node mariadb-galera cluster.
2. on 3rd node galera-2 disable sync to rest of cluster. ```bash -c "${mysqlCommand} --execute \"SET GLOBAL wsrep_desync = ON\""```
3.  Look at service - infra-mariadb-galera and all 3 nodes are still in service.

### What is the expected behavior?

When a galera node is not available to accept mysql connections it should be removed from the service.

### What do you see instead?

It is still part of the serivce as the readinesProbe passes.

### Additional information

https://github.com/bitnami/charts/blob/e8807baebb42894b2b1f529e3546d224efb68560/bitnami/mariadb-galera/templates/statefulset.yaml#L288

Suggestion is to update the readinessProbe to look at the galera(wsrep) state
 e.g. wsrep_local_state  != 4 
```
I have no name!@tm-infra-mariadb-galera-2:/opt/bitnami/scripts$                                   
mysql -u"${MARIADB_ROOT_USER}" -p"${MARIADB_ROOT_PASSWORD}" --execute="SHOW STATUS LIKE 'wsrep_local_state%';"
+---------------------------+--------------------------------------+
| Variable_name             | Value                                |
+---------------------------+--------------------------------------+
| wsrep_local_state_uuid    | f8f1a730-58fa-11ed-8f2a-efa6be33f9d5 |
| wsrep_local_state         | 2                                    |
| wsrep_local_state_comment | Donor/Desynced                       |
+---------------------------+--------------------------------------+
I have no name!@tm-infra-mariadb-galera-2:/opt/bitnami/scripts$ 
```

**Comment by migruiz4** [comment]
Hi @diepes,

I'm sorry for the late response.

Thank you very much for your suggestion. I have submitted this PR #13929 adding the proposed change.

I would appreciate it if you could take a look and let me know if it would work for you.

**Comment by diepes** [comment]
Hi @migruiz4 thanks for that.

Deployed the chart from git local and it works great ! 💯 %

Interesting observation, probably more of a generic k8s item.
* When i disable 1 node in 2node mariadb-galera cluster
   * With
           mysql -h 127.0.0.1 --user="$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" --execute "SET GLOBAL wsrep_desync = ON"
          mysqladmin extended-status -h 127.0.0.1 --user="$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" | grep " wsrep_local_state "
    
   *  the LB returns only the live ip (mariadb-galera)
   *  the headless lb returns both ip's (mariadb-galera-headless)
 
This makes sens as i think the headless is used by the cluster members to find each other.

**Comment by migruiz4** [comment]
Thanks for the feedback @diepes!

> the headless lb returns both ip's (mariadb-galera-headless)

The headless service is intended for peer-to-peer communication using the nodes FQDN and has `publishNotReadyAddresses=true` by default so nodes can communicate with each other even if they are not in 'Ready' status.
