### ISSUE TITLE
[bitnami/suitecrm] Helm upgrade does not alter the config 

### ISSUE THREAD

**Issue by sgl-mnrch** [bitnami/charts#13738]
### Name and Version

suitecrm-11.2.6

### What steps will reproduce the bug?

1. install chart via helm install -f values.yaml bitnami/suitecrm
2. log into the UI with the credentials and check if the smtp config is empty 
3. update the values yaml with new config settings, see below
4. run `helm upgrade helm-suitecrm --set mariadb.auth.password=$MARIADB_PASSWORD --set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD --set suitecrmPassword=$SUITECRM_PASSWORD -f values.yaml bitnami/suitecrm`
5. check the deployment for the new values: new values are part of the deployment
6. check if the smtp settings are picked up -> result: no

### Are you using any custom parameters or values?
```
suitecrmSmtpHost: "smtp.example.com"
suitecrmSmtpPort: "587"
suitecrmSmtpUser: "smtp-user"
suitecrmSmtpPassword: "smtp-pass"
suitecrmSmtpProtocol: "tls"
suitecrmNotifyAddress: "noreply@example.com"
suitecrmNotifyName: "CRM NAME"
```
### What is the expected behavior?

After changing the values and upgrading the chart, the new values should be picked up by suitecrm and used. 

### What do you see instead?

The new settings are not present in the deployment. 

### Additional information

I am not sure if this is really a bug in the chart or if i did something wrong. But I could not find any related information. 

EDIT: ON a fresh install, after helm uninstall, removal of all PVC, the settings are picked up.

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.
