### ISSUE TITLE
fluentd:    Unknown output plugin 'mongo_replset'

### ISSUE THREAD

**Issue by Mihai-CMM** [bitnami/charts#13741]
### Name and Version

bitnami/fluentd

### What steps will reproduce the bug?

Actually, this is more a question than a bug.
How can I use bitnami/fluentd and add needed plugins?

I can't follow how this might work 
```
`As an example, using the above configmap, you should specify the required parameters when upgrading or installing the chart:

aggregator.configMap=elasticsearch-output
aggregator.extraEnv[0].name=ELASTICSEARCH_HOST
aggregator.extraEnv[0].value=your-ip-here
aggregator.extraEnv[1].name=ELASTICSEARCH_PORT
aggregator.extraEnv[1].value=your-port-here`
```

In my case, I've added it under fluentd-output.conf: |
```yaml
fluentd-output.conf: |
.......left intact anything else ......
      <match triplets.application>
        @type mongo_replset
        database fluentd
        collection test
        nodes node1, node2,node3
            
        # The name of the replica set
        replica_set r0
        <buffer>
          # flush
          flush_interval 10s
        </buffer>
      </match>
```
   

but I am getting this error

```
2022-11-29 15:38:22 +0000 [error]: config error file="/opt/bitnami/fluentd/conf/fluentd.conf" error_class=Fluent::NotFoundPluginError error="Unknown output plugin 'mongo_replset'. Run 'gem search -rd fluent-plugin' to find plugins"
```

Can you please advice?

### Are you using any custom parameters or values?

per above

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami fluentd container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by Mihai-CMM** [comment]
Hmm, not sure if this statement is true": It seems it is not an issue related to the Bitnami fluentd container image or Helm chart but about how the application or environment is being used/configured.""

it is an issue of using bitnami/fluent. It lacks needed plugins and the documentation on how to use / enhance if missing.
 Of course you can play this game and just ignore a help request on your product. I am not asking how to run fluentd I ask how to enable plugins in your "flavor" of fluentd

For me to play same game I would say per your instructions i run :gem search -rd fluent-plugin' to find plugins: it doesn't work

Again thanks for your effort, maybe somebody else knows how to use your chart

**Comment by Mihai-CMM** [comment]
In fact the problem is more with the docker image rather than the chart though would have been nice to have an "usable" chart not with limited functionality (maybe you will accept a feature request)

What needs to be done is this part
https://github.com/bitnami/containers/tree/main/bitnami/fluentd

```
FROM bitnami/fluentd

### Install custom Fluentd plugins
RUN fluent-gem install 'fluent-plugin-mongo'
```
.. which unfortunately fails also  but clearly a different issue

Thanks again for looking at this
