### ISSUE TITLE
[bitnami/solr] solr pod is restarting due to connection issues with zookeeper

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#13757]
### Name and Version

bitnami/solr , latest

### What steps will reproduce the bug?

```
helm install solr bitnami/solr
```
### Are you using any custom parameters or values?

```
zookeeper.enabled=false
```
external zookeeper is given which are creted through bitnami zookeeper chart

### What is the expected behavior?

solr pods should run fine

### What do you see instead?

pods are restarting due to failed connection with zookeeper.
![Screenshot from 2022-11-30 16-17-40](https://user-images.githubusercontent.com/68244292/204776514-976efa21-cfbf-4852-8ab1-832de2c5c309.png)
![Screenshot from 2022-11-30 15-46-00](https://user-images.githubusercontent.com/68244292/204776539-262d4e43-7b2c-4eb3-9695-080454cdb09e.png)

### Additional information

i am also able to ping the zookeeper dns from solr pod inside 
![Screenshot from 2022-11-30 16-18-36](https://user-images.githubusercontent.com/68244292/204776700-dd026e93-ed94-4ab8-9c0f-8a9f8925edba.png)

**Comment by abhishekgupta2205** [comment]
output of zookeeper pods logs .  it is only receiving mntr and ruok command but not conf comand

![Screenshot from 2022-11-30 16-21-14](https://user-images.githubusercontent.com/68244292/204777258-22ab02f4-88f8-4c47-9fd7-8be5c74fe3b1.png)

**Comment by rafariossaa** [comment]
Hi,
  This worked for me:
```bash
  $ helm install myzoo bitnami/zookeeper

  ##wait until it is deployed. Then from the solr chart cloned directory:

  $ helm install mysolr -f values.yaml -f p1.yaml .
```
  where p1.yaml is:

```yaml
zookeeper:
  enabled: false
externalZookeeper:
  servers:
    - myzoo-zookeeper
```
 Could you give it a try ?
