### ISSUE TITLE
Redis with sentinel goes into crashloop when the leader pod is terminated

### ISSUE THREAD

**Issue by suchits07** [bitnami/charts#13764]
### Name and Version

bitnami/redis 16.8.2

### What steps will reproduce the bug?

1. We are running 3 pods of the redis in the master-sentinel config. The pods are running as statefulset. 
2. When the leader pod is terminated, the remaining two pods get into the `CrashLoopBackoff` state. 
3. Kubernetes does not restart the terminated leader pod since the default pod management policy is `Ordered` which will not allow the restart of terminated pods and the redis cluster does not come up.
4. To get the cluster back, we need to delete the remaining pods so that kubernetes can restart the pods one by one and cluster is available.
4. To overcome this issue, we changed the pod management policy to `Parallel`.
5. With this, when we deploy the redis cluster, all 3 pods start simultaneously and all tries to be master at the same time.
6. This leads to the unhealthy redis cluster.

### Are you using any custom parameters or values?

Nope

### What is the expected behavior?

The expected behaviour is whenever a leader pod is terminated for any reason, the redis cluster should be stable and the terminated pod should be started again. Also, when the deployment of redis happens, only of the all statefulset, should be leader so that the cluster is healthy.

Is there any flag that we can set so that so that the other pods of statefulset wait till one of them is started as leader and at the same time whenever a leader pod is terminated, kubernetes should be able to restart it again.

### What do you see instead?

Logs when PodManagementPolicy is set to `Parallel`
```
1:X 30 Nov 2022 09:20:19.296 # +monitor master mymaster redis-node-0.redis-headless.redis.svc.cluster.local 6379 quorum 2
1:X 30 Nov 2022 09:20:33.553 * +convert-to-slave slave redis-node-2.redis-headless.redis.svc.cluster.local:6379 redis-node-2.redis-headless.redis.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.redis.svc.cluster.local 6379
1:X 30 Nov 2022 09:20:40.814 * +convert-to-slave slave redis-node-1.redis-headless.redis.svc.cluster.local:6379 redis-node-1.redis-headless.redis.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.redis.svc.cluster.local 6379
1:X 30 Nov 2022 09:22:09.433 # +sdown master mymaster redis-node-0.redis-headless.redis.svc.cluster.local 6379
```
```
1:X 30 Nov 2022 09:20:30.067 # +monitor master mymaster redis-node-1.redis-headless.redis.svc.cluster.local 6379 quorum 2
1:X 30 Nov 2022 09:20:40.109 * +convert-to-slave slave redis-node-0.redis-headless.redis.svc.cluster.local:6379 redis-node-0.redis-headless.redis.svc.cluster.local 6379 @ mymaster redis-node-1.redis-headless.redis.svc.cluster.local 6379
1:X 30 Nov 2022 09:22:10.227 # +sdown master mymaster redis-node-1.redis-headless.redis.svc.cluster.local 6379
```
```
1:X 30 Nov 2022 09:20:23.811 # +monitor master mymaster redis-node-2.redis-headless.redis.svc.cluster.local 6379 quorum 2
1:X 30 Nov 2022 09:21:53.878 # +sdown master mymaster redis-node-2.redis-headless.redis.svc.cluster.local 6379
```

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
