### ISSUE TITLE
[bitnami/wordpress] MySql service not starting after reboot. Failed to find valid data directory. Data Dictionary initialization failed

### ISSUE THREAD

**Issue by rushi-dave** [bitnami/charts#13761]
### Name and Version

bitnami/WordPress 5.6.0

### What steps will reproduce the bug?

We are facing issue in after service reboot and MySql service not string up.

Below is log file details:
```
0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld.bin (mysqld 8.0.22) starting as process 10036
1 [ERROR] [MY-011011] [Server] Failed to find valid data directory.
0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
0 [ERROR] [MY-010119] [Server] Aborting
0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld.bin: Shutdown complete (mysqld 8.0.22)  MySQL Community Server - GPL.
0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld.bin (mysqld 8.0.22) starting as process 10534
1 [ERROR] [MY-011011] [Server] Failed to find valid data directory.
0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
0 [ERROR] [MY-010119] [Server] Aborting
0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld.bin: Shutdown complete (mysqld 8.0.22)  MySQL Community Server - GPL.
```
Need  your support to fix this.

Thanks,

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Mysql service should be up and db needs to be running

### What do you see instead?

Failed to find valid data directory. Data Dictionary initialization failed

**Comment by javsalgar** [comment]
Hi,

Could you add more details on the Kubernetes platform you are using and the volume provider? It seems there may be some volume corruption.
