### ISSUE TITLE
[bitnami/nginx] Vault injector sidecar

### ISSUE THREAD

**Issue by omarkalloush** [bitnami/charts#13763]
### Name and Version

bitnami/nginx 13.2.13

### What steps will reproduce the bug?

Try to use the vault-injector with the nginx helm chart

The container is not generated inside the Pod. is there a value or a parameter that should be changed in order to generate it?

### Are you using any custom parameters or values?

No custom parameters.

### What is the expected behavior?

To inject vault side car into the Nginx pod and pull secrets from hashicorp vault.

### What do you see instead?

The pods starts fine but there is no `vault-init` or `vault` containers inside the pod.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami NGINX container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by omarkalloush** [comment]
The issue here was that `serviceAccount.automountServiceAccountToken` was set to false, after setting to true the vault injector was able to inject the secrets.
