### ISSUE TITLE
[bitnami/redis] Master and Replica deployment with sentinel and manual scheduling issue 

### ISSUE THREAD

**Issue by Deepanshu6dec** [bitnami/charts#13776]
### Name and Version

bitnami/redis 17.3.11

### What steps will reproduce the bug?

Deploy Redis along with Sentinel 

1. When We testing the failure condition master went down and replica will going to became master as mention the doc
When installing the chart with architecture=replication and sentinel.enabled=true, it will deploy a Redis® master StatefulSet (only one master allowed) and a Redis® replicas StatefulSet. In this case, the pods will contain an extra container with Redis® Sentinel. This container will form a cluster of Redis® Sentinel nodes, which will promote a new master in case the actual one fails. In addition to this, only one service is exposed:

Redis® service: Exposes port 6379 for Redis® read-only operations and port 26379 for accessing Redis® Sentinel.

when master went down redis-node-01 is going to master and then after we able to did read and write operation with the `REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379 # Read only operations `
without failure condition we just able to do read operation not write one but after failure we able to did both  the requirement  will `REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379 can only do read operations even if master got change`

This example is when master is change to node-1 and we able to write it as well in read only operations 

```
I have no name!@redis-client:/$ REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379 
redis:6379> keys *
1) "hello"
redis:6379> get hello
"keys"
redis:6379> set hello1 key
OK
redis:6379> 
redis:6379> keys *
1) "hello"
2) "hello1"
```
when we deploy a fresh deployment and trying the same we getting (error) READONLY You can't write against a read only replica. probably its correct as this command can only be used for read operations 
```
I have no name!@redis-client:/$ REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379
redis:6379> keys *
(empty array)
redis:6379> set hello key
(error) READONLY You can't write against a read only replica.
redis:6379>
```

2. We are using node affinity to schedule our master and replica in different-Different nodes but when we are scheduling master and replica, deployment is following the replicas node affinity  and all nodes deploy into replica node affinity only 

How we can we schedule master and 2 replicas on different nodes with the help of node affinity or pod affinity 

```
redis-repl-node-0   2/2     Running   0          4m42s   10.244.2.21 csmsc-redis-cal1   <none>           <none>
redis-repl-node-1   2/2     Running   0          51s     10.244.2.22   csmsc-redis-cal1   <none>           <none>
redis-repl-node-2   2/2     Running   0          51s     10.244.2.22   csmsc-redis-cal1   <none>           <none>
```

Expected output:

```
redis-repl-node-0   2/2     Running   0          4m42s   10.244.2.21 csmsc-redis-cal1   <none>           <none>
redis-repl-node-1   2/2     Running   0          51s     10.244.2.22   csmsc-redis-cal1( Should deploy in different node)   <none>           <none>
redis-repl-node-2   2/2     Running   0          51s     10.244.2.22   csmsc-redis-cal1( should deploy in different node based on the nodes defined)   <none>           <none>
``` 

it should deploy one master in our required nodes and other 2 replicas in specific nodes which we want it 

### Are you using any custom parameters or values?

```
# Common Parameters
clusterDomain: cluster.local

commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  # # Enable maxmemory  
  # Maxmemory 600mb              #Maxmemory configuration get it from redis instance
  # # Enable Maxclient
  # Maxclient 10                # Maxclient configuration get it from redis instance

# Redis Image parameters
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.5-debian-10-r71
  #tag: 7.0.4-debian-11-r11
  debug: true

# Redis common configuration parameters
architecture: replication
auth:
  enabled: true
  password: "smsc123"

# Redis master configuration parameters
master:
  count: 1
  livenessProbe:
     enabled: true
     initialDelaySeconds: 30
     periodSeconds: 10
     timeoutSeconds: 5
     failureThreshold: 5
     successThreshold: 1
  readinessProbe:
     enabled: true
     initialDelaySeconds: 30
     periodSeconds: 10
     timeoutSeconds: 5
     failureThreshold: 5
     successThreshold: 1
  nodeAffinityPreset:                    # With the help of this we want master to schedule on Worker node1 
    type: hard
    key: type
    values:
     - K8SMSG
  
  persistence:
     enabled: false
    #  storageClass: local-storage
    #  size: 8Gi

# Redis replicas configuration parameters
replica:
   replicaCount: 3
   startupProbe:
    enabled: true
    initialDelaySeconds: 50
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 22
   livenessProbe:
     enabled: true
     initialDelaySeconds: 50
     periodSeconds: 10
     timeoutSeconds: 5
     failureThreshold: 5
     successThreshold: 1
   readinessProbe:
     enabled: true
     initialDelaySeconds: 50
     periodSeconds: 10
     timeoutSeconds: 5
     failureThreshold: 5
     successThreshold: 1
   persistence:
     enabled: false
    #  size: 8Gi
    #  storageClass: local-storage

   nodeAffinityPreset:            # We want replica to be schedule on different nodes
    type: hard
    key: type
    values:
     - K8SWN

  

sentinel:
    startupProbe:
      enabled: true
      initialDelaySeconds: 50
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 22
    livenessProbe:
      enabled: true
      initialDelaySeconds: 50
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 50
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    enabled: true
    # persistence:
    #     enabled: 
```

### What is the expected behavior?

Expected output:

```
redis-repl-node-0   2/2     Running   0          4m42s   10.244.2.21 csmsc-redis-cal1   <none>           <none>
redis-repl-node-1   2/2     Running   0          51s     10.244.2.22   csmsc-redis-cal1( Should deploy in different node)   <none>           <none>
redis-repl-node-2   2/2     Running   0          51s     10.244.2.22   csmsc-redis-cal1( should deploy in different node based on the nodes defined)   <none>           <none>
``` 

### What do you see instead?

scheduling not working 

### Additional information

Please take a look on the code

**Comment by Deepanshu6dec** [comment]
@aoterolorenzo can you please assist on this issue

**Comment by aoterolorenzo** [comment]
Hi @Deepanshu6dec, 

Sorry for the delay. Could you describe the steps to try to reproduce the issue? Also a describe of the pods, k8s version and kind of cluster would be welcome

**Comment by Deepanshu6dec** [comment]
Hi @aoterolorenzo 

You can use this values.yaml file and deploy helm 

`CMD: helm install redis -f values.yaml bitnami/redis`

It will deploy 

1. fail-over scenario: If master went down next replica became master with the help of read only command we also able to write it  `REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379 # Read only operations`

2. When sentinel enable it will do one deployment with 3 replicas out of 3 one will became master NOW i want to schedule master in different node and replicas on different nodes but when `Sentinel enable`  redis master configuration parameter is not applicable 

Kubernetes version
`Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Deepanshu6dec** [comment]
Can not we used this redis chart as master and replica separate configuration along with sentinel

**Comment by aoterolorenzo** [comment]
Thank you @Deepanshu6dec,

I will open a task for the team to dig into this. We will reach back to you in this issue, meanwhile I will leave it as on-hold.

**Comment by Deepanshu6dec** [comment]
Do we get any update on this issue. 
Issue is:

When deploying redis with sentinel  and checking failover scenario 

terminating redis-0 

with read only ``` REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379 # Read only operations ```

We able to write keys 

```
I have no name!@redis-client:/$ REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h redis -p 6379
redis:6379> keys *
(empty array)
redis:6379> set key hello
OK
redis:6379> 

```

**Comment by aoterolorenzo** [comment]
Thanks for providing a little more information and keep debugging the issue! 

As said, the internal task is created and will be addressed as soon as our workload allow that.

**Comment by hervedevos** [comment]
Hello, I also would like to be able to set node affinitiy to master and replicas but with sentinel enabled. Is there anything planned ?
