### ISSUE TITLE
Is there a way access kafka from another network outside the K8s cluster?

### ISSUE THREAD

**Issue by hueidou** [bitnami/charts#13777]
### Name and Version

bitnami/kafka 3.3.1

### What is the problem this feature will solve?

> This chart allows you to automatically configure Kafka with 3 listeners:
> * One for inter-broker communications.
> * A second one for communications with clients within the K8s cluster.
> * (optional) a third listener for communications with clients outside the K8s cluster. Check this section for more information.

Is there a way to access Kafka from another network outside the K8s cluster? For example in the following image, both `IP1:PORT1`(the 3rd way) and `IP2:PORT2` (no limit port)can access.

![image](https://user-images.githubusercontent.com/712892/205001051-171a9136-cba5-4ac4-aea4-bbb5c17b4eab.png)

### What is the feature you are proposing to solve the problem?

Add multiple externalAccesses.

### What alternatives have you considered?

Use name/domain+hosts instead of ip. (PORT1 and PORT2 are same,  PORT2 has limit)

```yaml
externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      - 30001
    domain: kafka1
```

```
# hosts in LAN
IP1 kafka1

# hosts out LAN
IP2 kafka1
```

**Comment by rafariossaa** [comment]
Hi,
  I guess I am missing something, I am not very sure of the question here. 
  Once you expose the service you can reach it from all the IPs you want, there is not limitation on this. However, how to reach it would change depending on type of service you are using.
  I am not a networking expert, but AFAIK, NAT translates IP2:PORT2 to IP1:PORT1, and this can not be changed on the fly. If you need to expose IP3:PORT3 on IP2:PORT2, you will need to delete the NAT and recreate it.
  Maybe you can elaborate a bit more on the scenario.

**Comment by OneCricketeer** [comment]
You can refer the [README of the Kafka folder in this repo](https://github.com/bitnami/charts/tree/main/bitnami/kafka#traffic-exposure-parameters) to see value configuration for `externalAccess.enabled`, which defines some of these settings. 


This page covers accessing Kafka in Kubernetes in more detail: https://strimzi.io/blog/2019/04/17/accessing-kafka-part-1/

**Comment by OneCricketeer** [comment]
If you want to introduce NAT-ing, then that would be handled by your router, not any Helm values. 

Note that `advertised.listeners` gets returned to your remote clients, so it's not only ports that need configured. Your brokers will need to therefore know that the are being NAT-ed.

**Comment by rafariossaa** [comment]
Hi @OneCricketeer ,
  Thanks for links and the info.
