### ISSUE TITLE
[bitnami/postgresql] livenessProbe and readiness probes fail

### ISSUE THREAD

**Issue by Xnyle** [bitnami/charts#13789]
### Name and Version

bitnami/postgresql 12.1.2

### What steps will reproduce the bug?

Just deployed this chart on a fresh bare metall cluster with cri-o (not docker) and the services do not startup because the readinessProbe (and also livenessProbe) keeps failing, from the logs:

```
kubelet[15676]: E1201 15:29:50.841673   15676 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1" containerID="ec6950605c367f8a537746462562751ab97261f5214e0bcd67f2d0f7562e7404" cmd=<
kubelet[15676]: #011[/bin/sh -c -e exec pg_isready -U "gitlab" -d "gitlabhq_production" -h 127.0.0.1 -p 5432
kubelet[15676]: #011[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
kubelet[15676]: #011]
kubelet[15676]:  >
```

/bin/sh links to dash inside container, not bash, not sure if that's a problem.

Strangely  if I execute

```
/bin/sh -c -e exec pg_isready -U "gitlab" -d "gitlabhq_production" -h 127.0.0.1 -p 54301 [ -f /opt/bitnami/postgresql/tmp/.initializedxxxxx ] || [ -f /bitnami/postgresql/.initializedxxxxx ]
```
(wrong port and wrong files) I still get returncode 0

So I'm confused what's going on here
 

### Are you using any custom parameters or values?

Not that I know of, bare metall 1.24 Cluster on Debian Bullseye

### What is the expected behavior?

readinessProbe should succeed after Database is running (which it is)

### What do you see instead?

readinessProbe failing, see above.

**Comment by javsalgar** [comment]
Hi,

We are unable to reproduce the issue in our platforms. I'm not sure if it has to do with how the contanier runtime is configured. Did you try the same configuration in other kubernetes platform?

**Comment by Xnyle** [comment]
@javsalgar actually in order to properly debug this I need some help how to reproduce the exit code from kubectl.

I don't even understand how the probe is supposed to even work in the first place.

If I understand the k8s documentation correctly the following would be executed inside the pod/container:

```/bin/sh -c -e "exec pg_isready -U \"gitlab\" -d \"gitlabhq_production\" -h 127.0.0.1 -p 5432" "[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]" ```

Probably not correct?

This would result in the following debug statement:

kubectl exec -it -n gitlab gitlab-server-postgresql-0 -- /bin/sh -c -e "exec pg_isready -U \"gitlab\" -d \"gitlabhq_production\" -h 127.0.0.1 -p 5432" "[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]" 

Probably also not correct?

Because that always returns with 0 exit code as long as pg_isready is found.

So I'm totally lost, what was the intention with the shell construct and how to reproduce it properly using kubectl.

**Comment by javsalgar** [comment]
Hi,

Indeed, that shell construct is done to verify that the PostgreSQL instance works correctly. You could try entering the container with and exec -- /bin/bash and try to execute the command inside to see if it returns 0 in that case as well.

**Comment by Xnyle** [comment]
@javsalgar ticket as such can be closed (or not, see below) as the problem has nothing to do with this chart but with my setup.

BUT now that i have seen it, i'm pretty sure this liveness probe can not fail unless pg_isready is not found.
You can also test that via kubectl exec, it doesn't matter what comes after the exec pg_isready, as long as pg_isready is there, exec will always return 0 exitcode. And the additional test statements make even less sense to me in that context?
