### ISSUE TITLE
[Timescaledb] Helm chart fails with the message:- "Readiness probe failed: /var/run/postgresql:5432 - no response" on K8s

### ISSUE THREAD

**Issue by KRISHNA-VKS** [bitnami/charts#13806]
### Name and Version

timescale/timescaledb-single    0.24.1

### What steps will reproduce the bug?

1. Created a K8s environment inside Azure Windows server 2022 Data Center. Kubernetes version is v1.22.6.
2. Installed the helm chart using:- 
helm install ldl-timescaledb timescale/timescaledb-single --namespace "ldl-infra-ns" --set replicaCount=1 --set persistentVolumes.data.storageClass="local-path" --set persistentVolumes.wal.storageClass="local-path" --set service.primary.type="LoadBalancer"

Pre-requisites:- local-path is installed using 
https://github.com/rancher/local-path-provisioner#installation

3. Describing the pod give the error details as "Warning  Unhealthy  4m31s (x56 over 24m)  kubelet            Readiness probe failed: /var/run/postgresql:5432 - no response".
4. Checking at the Pod logs gives the following 2 types of error information:-
5. ```
"ERROR: create_config_service failed" -> HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:ldl-infra-ns:ldl-timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"ldl-infra-ns\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'
```
 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1
 HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:ldl-infra-ns:ldl-timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"ldl-infra-ns\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'
 
 
 Attaching the Entire logs and command as word document for reference:-
[TimeScaledb-HelmChart-Issue.docx](https://github.com/bitnami/charts/files/10140399/TimeScaledb-HelmChart-Issue.docx)



### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

_No response_

### What do you see instead?

- Describing the pod give the error details as "Warning  Unhealthy  4m31s (x56 over 24m)  kubelet            Readiness probe failed: /var/run/postgresql:5432 - no response".
- Checking at the Pod logs gives the following 2 types of error information:-
"ERROR: create_config_service failed" -> HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:ldl-infra-ns:ldl-timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"ldl-infra-ns\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1
 HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:ldl-infra-ns:ldl-timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"ldl-infra-ns\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'
 

### Additional information

_No response_

**Comment by javsalgar** [comment]
Hi,

Please note that we are not the owners of the timescaledb chart. Could you check with the developers of that chart?
