### ISSUE TITLE
[bitnami/postgresql-ha] Change of postgres password key avoids startup

### ISSUE THREAD

**Issue by sjoukedv** [bitnami/charts#13800]
### Name and Version

bitnami/postgresql-ha 10.0.6

### What steps will reproduce the bug?

This PR #13733 renamed `postgres-password` to `password` which is fine in essence, but the statefulset use envFrom with the new key. I am using a custom secret for these values (so that it is managed outside of the chart) and therefore the key does not exist. 

### Are you using any custom parameters or values?

n.a.

### What do you see instead?

I was unable to upgrade because of `CreateConfigError` on the pod as the key did not exist. We should have an if statement to check if the new value exists and otherwise default to `postgres-password`

**Comment by CeliaGMqrz** [comment]
Hi @sjoukedv,

Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by sjoukedv** [comment]
> Hi @sjoukedv,
> 
> Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

Yes, I have created a PR which looks up the `postgres-password` in the secret and defaults to the new `password` key

```
- name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-postgresql-ha-postgresql
                  key: password
```

I will link the PR here in a sec

**Comment by sjoukedv** [comment]
Sorry for the duplicate PR I was using commitizen which did not sign my commits by default anymore. The open PR is ready for review.

**Comment by CeliaGMqrz** [comment]
Thanks for the contribution! Our team will review your PR.
