### ISSUE TITLE
Adding Plugins to the Redmine Helm Chart

### ISSUE THREAD

**Issue by austinbv** [bitnami/charts#1380]
**Which chart**:
redmine - latest

**Description**
Installing plugins. We are using all default values for redmine to install the chart and everything works great but we cannot install plugins.

Our first attempt to install a plugin was to create our own container. It looks like the PV overrides any plugins we add. We use `kubectl cp` to move the plugins into the PV and then try to follow the standard install process. 

```
export POD_NAME=$(kubectl get pod -lapp=redmine -n redmine -o jsonpath='{.items[0].metadata.name}')
kubectl cp plugins/redmine_highlightjs redmine/${POD_NAME}:/bitnami/redmine/plugins/
kubectl exec -it ${POD_NAME} --namespace redmine -- /bin/bash
```

Once you're in the pod

```
cd /opt/bitnami/redmine
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

now exit the pod with `exit` and restart the POD

```
export POD_NAME=$(kubectl get pod -lapp=redmine -n redmine -o jsonpath='{.items[0].metadata.name}')
kubectl delete pod $POD_NAME
```

**Steps to reproduce the issue:**

see above

**Describe the results you received:**

After running the rake command in `/opt/bitnami/redmine/` we get this error

```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
by running `bundle install --no-deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* redmine_crm
```

Running `bundle install --no-deployment`
yields an error compiling nokogiri

If we restart the POD the pod will fail to start with missing bundle depenencies.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @austinbv, I'd say the correct approach is creating your own image, something like what is explained here:

https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005

However, you said that the PV overrides the plugins. Can you give more details about this? It shouldn't be happening.

**Comment by austinbv** [comment]
Thanks for responding so quickly!

I have been putting plugins in the `/bitnami/redmine/plugins` directory which looks like it is symlinked to `/opt/bitnami/redmine/plugins`.

If you look at https://github.com/helm/charts/blob/master/stable/redmine/templates/deployment.yaml#L148

Then if you look at `/opt/bitnami/redmine/`

```
root@redmine-6c66d948b7-rxpht:/opt/bitnami/redmine# ls -al
total 52
drwxr-xr-x 1 bitnami root    4096 Aug 29 15:07 .
drwxr-xr-x 1 root    root      21 Jul  1 13:35 ..
drwxr-xr-x 1 bitnami root      20 Jul  1 13:35 .bundle
drwxr-xr-x 1 bitnami root      38 Jul  1 13:35 .github
-rw-r--r-- 1 bitnami root     761 Jun 10 19:06 .gitignore
-rw-r--r-- 1 bitnami root     635 Jun 10 19:06 .hgignore
-rw-r--r-- 1 bitnami root     241 Jun 10 19:06 CONTRIBUTING.md
-rw-r--r-- 1 bitnami root    2903 Jun 10 19:06 Gemfile
-rw-r--r-- 1 bitnami root    4819 Jun 10 19:07 Gemfile.lock
-rw-r--r-- 1 bitnami root     205 Jun 10 19:06 README.rdoc
-rw-r--r-- 1 bitnami root     275 Jun 10 19:06 Rakefile
drwxr-xr-x 1 bitnami root      67 Jul  1 13:35 app
-rw-r--r-- 1 bitnami root     860 Jun 10 19:06 appveyor.yml
drwxr-xr-x 1 bitnami root    4096 Jul  1 13:35 bin
drwxr-xr-x 5 bitnami root     243 Aug 29 15:07 conf
lrwxrwxrwx 1 root    root      25 Aug 29 15:07 config -> /opt/bitnami/redmine/conf
-rw-r--r-- 1 bitnami root     154 Jun 10 19:06 config.ru
drwxr-xr-x 1 bitnami root      38 Aug 29 15:07 db
drwxr-xr-x 1 bitnami root      98 Aug 29 15:08 extra
lrwxrwxrwx 1 root    root      22 Aug 29 15:07 files -> /bitnami/redmine/files
drwxr-xr-x 1 bitnami root     100 Jul  1 13:35 lib
drwxr-xr-x 1 bitnami root      31 Jul  1 13:35 licenses
lrwxrwxrwx 1 root    root      25 Aug 29 15:07 log -> /opt/bitnami/redmine/logs
drwxrwxr-x 2 bitnami redmine   28 Aug 29 15:07 logs
-rw-r--r-- 1 bitnami root       0 Jun 10 19:08 passenger.3000.pid.lock
lrwxrwxrwx 1 root    root      24 Aug 29 15:07 plugins -> /bitnami/redmine/plugins
drwxr-xr-x 1 bitnami root     214 Aug 29 15:07 public
drwxr-xr-x 1 bitnami root    4096 Jul  1 13:35 test
drwxrwxrwt 1 redmine redmine  118 Aug 29 15:08 tmp
drwxr-xr-x 1 bitnami root      20 Jul  1 13:35 vendor
```

I've been digging around your Dockerfiles and am not seeing where the symlink is happening. I will try turning off PV in the helm chart and report back

Cheers

**Comment by andresbono** [comment]
The symbolic link is done at runtime when application is initialized. Try the following:

```
docker run --rm -it bitnami/redmine ls -la /opt/bitnami/redmine/
```

There, you won't see the symbolic links because the we are overriding the `CMD` from the Dockerfile by specifying the command `ls -la /opt/bitnami/redmine/`. See https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-9/rootfs/app-entrypoint.sh#L8.

So, if you create a new container image including the plugins in `/opt/bitnami/redmine/plugins` the volume `/bitnami/redmine` will be populated with that content by:
  1) Moving the data from `/opt/bitnami/redmine/plugins` to `/bitnami/redmine`.
  2) Creating a symlink `/opt/bitnami/redmine/plugins -> /bitnami/redmine/plugins`.

If the PV is already initialized, then, step `1.` is skipped.


This is more or less what I mention in https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005

> Note that this process assumes a first initialization of the container and you will need to remove the persistent volumes. If you prefer to maintain the current data in your volumes, you just need to follow some extra steps [...]

**Comment by abhi1git** [comment]
How are these symlinks by default getting configured from the PVC mount path (/bitnami/redmine) to actual redmine path (/opt/bitnami/redmine)
I cannot see any such configuration in helm chart about creation of symlinks.
I want to add symlinks for Gemfile and Gemfile.lock so that these files get updated after plugins are pasted in /bitnami/redmine/plugin folder and bundle install command is executed in /bitnami/redmine/ directory

@andresbono  @austinbv 
can you please help if you have been successful in adding plugins for the helm chart deployment.

**Comment by austinbv** [comment]
@abhi1git we extended the image. Another way we found was to use our own volumes with the plugins in it then use a config map with a startup script that will allow us to install plugins

**Comment by andresbono** [comment]
@abhi1git, the symlinks are created as part of the initialization process of the container. Let us know if @austinbv approaches work for you.

**Comment by thanhtai9606** [comment]
can somebody help me?? I wanna add plugin redmine_aglie. I install redmine on kubernetes, but I cannot install plugin agile_light. I tried build docker image, but it not working. 
Please help me. Can help me build an image container plugin agile is ok.!!

**Comment by andresbono** [comment]
Hi @thanhtai9606, please check this comment: https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005. If you still face issues after following those steps, please continue the conversation in the container issue, as it is more related to the container than to the chart.

**Comment by skliarie** [comment]
bitnami reorganized their charts project, so opened a feature request with them:
https://github.com/bitnami/charts/issues/15389

**Comment by s0l4r** [comment]
I have the same issue after trying to get this working for a few days.. Forking the image seems way too much work for the simple use case to add extra plugins to Redmine :(
