### ISSUE TITLE
[bitnami/drupal] Feature request Ability to set affinity for deployment

### ISSUE THREAD

**Issue by junkiebev** [bitnami/charts#1381]
I've multiple storage classes which are tied to specific data centers - it'd be cool if it was possible to set affinities for drupal's deployment to insure that it would be able to connect to persistent volumes.

**Comment by alemorcuq** [comment]
Hi, @junkiebev.

I agree this would be a nice feature. Are you interested on making a PR implementing it? We already have some charts supporting it (like `wordpress` or `joomla`). If not, we can add it ourselves.

Regards,
Alejandro

**Comment by junkiebev** [comment]
I can try 🙃 - go templating isn’t my strong suit, so review the heck out of it...

Apropos of nothing, but is there some tool y’all use to verify go templating?

**Comment by alemorcuq** [comment]
Thank you, @junkiebev! We will gladly review your PR. You can use the `template` command of `helm` to render the template locally. See:

```
$ helm template --help
```

And remember you can use other charts such as `wordpress` or `joomla` as examples.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Hi, @junkiebev.

Just wanted to tell you that we implemented affinities on Drupal. Let us know if you find any issues.

Regards,
Alejandro
