### ISSUE TITLE
[bitnami/solr] Solr volume-permissions won't chown dir on first use

### ISSUE THREAD

**Issue by jam01-lb** [bitnami/charts#13829]
### Name and Version

bitnami/solr 6.3.2

### What steps will reproduce the bug?

1. enabling `volumePermissions` as below
2. provide an empty /bitnami/solr directory

### Are you using any custom parameters or values?

    volumePermissions:
      enabled: true

### What is the expected behavior?

To chown the /bitnami/solr directory even if empty

### What do you see instead?

The following command from https://github.com/bitnami/charts/blob/main/bitnami/solr/templates/statefulset.yaml#L88 
```
find /bitnami/solr -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found"
```
has empty results if the directory is empty, so when piped to `xargs -r chown` the directory is not `chown`'ed

### Additional information

We could just adopt what the drupal volume-permissions does and just plain `chown` the whole directory without using `find`

https://github.com/bitnami/charts/blob/main/bitnami/drupal/templates/deployment.yaml#L81

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Would you like to submit a PR with the fix?
