### ISSUE TITLE
[bitnami/rabbitmq] Error: Unable to create worker process, insufficient resources

### ISSUE THREAD

**Issue by sagimann** [bitnami/charts#13830]
### Name and Version

bitnami/rabbitmq 11.1.1 (rabbit 3.11.2)

### What steps will reproduce the bug?

* Env: GCP cluster on n2-standard CPU on GKE 1.22
* Attached values.yaml used during the installation of the chart 
[v.txt](https://github.com/bitnami/charts/files/10150980/v.txt)
* Install using `helm install --version 11.1.1 my-rabbitmq -f values.yaml bitnami/rabbitmq -n myproject`

Every once in a while, we're seeing `Does not have minimum availability` error next to the rabbitmq pod in the GKE workload view. When looking at the log explorer around the time of unavailability, we see the following failed startup attempt:

```
Welcome to the Bitnami rabbitmq container
Subscribe to project updates by watching https://github.com/bitnami/containers
Submit issues and feature requests at https://github.com/bitnami/containers/issues
==> ** Starting RabbitMQ setup **
==> Validating settings in RABBITMQ_* env vars..
==> Initializing RabbitMQ...
==> Persisted data detected. Restoring...
==> No custom scripts in /docker-entrypoint-initdb.d
==> ** RabbitMQ setup finished! **
{}
==> ** Starting RabbitMQ **
Failed to create poll thread
Aborted
Welcome to the Bitnami rabbitmq container
Subscribe to project updates by watching https://github.com/bitnami/containers
Submit issues and feature requests at https://github.com/bitnami/containers/issues
==> ** Starting RabbitMQ setup **
==> Validating settings in RABBITMQ_* env vars..
==> Initializing RabbitMQ...
==> Persisted data detected. Restoring...
==> No custom scripts in /docker-entrypoint-initdb.d
==> ** RabbitMQ setup finished! **
==> ** Starting RabbitMQ **
/opt/bitnami/erlang/lib/erlang/erts-13.1.1/bin/inet_gethost[83]: WARNING:Could not fork(), errno = 11
/opt/bitnami/erlang/lib/erlang/erts-13.1.1/bin/inet_gethost[83]: WARNING:Unable to create worker process, insufficient resources
```

Looking at erlang code, this is a result of a `fork()` attempt that fails during [create_worker](https://github.com/erlang/otp/blob/OTP-25.0/erts/etc/common/inet_gethost.c#L1629) function.

limits inside the container are as follows:
```
$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 29789
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```
But these don't show host limits which I could not find how to access within a k8s node. Where ever I looked, it says direct node access is not available (GCP blocks root access to containerd or so it seems)

### Are you using any custom parameters or values?

attached above

### What is the expected behavior?

rabbitmq server should continue running and not crash the container

### What do you see instead?

the container appears down in the workload view and the log explorer shows the mentioned problem fork()ing inet_host workers

**Comment by javsalgar** [comment]
Hi,

Thank you so much for using Bitnami charts. However, this error seems to be more related with RabbitMQ itself than the Bitnami packaging of the container. Did you try checking with the upstream RabbitMQ devs? https://github.com/rabbitmq/rabbitmq-server

**Comment by sagimann** [comment]
Hard to say, the error seems to be reported by eglang runtime - is this considered part of the rabbitmq-server project or more like bitnami/rabbitmq docker?

**Comment by lukebakken** [comment]
https://groups.google.com/g/rabbitmq-users/c/ObSOWnXN_OI
