### ISSUE TITLE
[bitnami/external-dns] InvalidChangeBatch error in v6.7.1 

### ISSUE THREAD

**Issue by rachit-srivastava** [bitnami/charts#13843]
### Name and Version

bitnami/external-dns 6.7.1

### What steps will reproduce the bug?

we are currently on version 6.4.1 and trying to upgrade to 6.12.1.
We were able to upgrade till 6.7.0 but upgrading it to 6.7.1 or beyond breaks with InvalidChangeBatch error.
v6.7.0 uses [docker.io/bitnami/external-dns:0.12.0-debian-11-r9](http://docker.io/bitnami/external-dns:0.12.0-debian-11-r9) as docker image.
v6.7.1 uses [docker.io/bitnami/external-dns:0.12.1-debian-11-r0](http://docker.io/bitnami/external-dns:0.12.1-debian-11-r0) as docker image.

### Are you using any custom parameters or values?

```
external-dns:
  triggerLoopOnEvent: true
  interval: 12h
  logLevel: info
  policy: sync
  txtPrefix: ABCD
  txtOwnerId: ABCD

  aws:
    assumeRoleArn: ""
    batchChangeSize: 1000
    zoneTags: []
```

### What do you see instead?

Upon updating the helm chart to version6.12.1 I found the following error in logs of external dns pod

```
time="2022-12-05T09:20:29Z" level=info msg="Desired change: CREATE ABCDcname-URL1.internal.COMPANYNAME.com TXT [Id: /hostedzone/HOSTEDZONEID]"

time="2022-12-05T09:20:29Z" level=info msg="Desired change: CREATE ABCDcname-URL1.internal.COMPANYNAME.com TXT [Id: /hostedzone/HOSTEDZONEID]"

time="2022-12-05T09:20:30Z" level=error msg="Failure in zone COMPANYNAME.com. [Id: /hostedzone/HOSTEDZONEID]"

time="2022-12-05T09:20:30Z" level=error msg="InvalidChangeBatch: [The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL1.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL2.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL3.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL5.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL6.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL7.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL8.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL9.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL10.COMPANYNAME.com.', The request contains an invalid set of changes for a resource record set 'TXT ABCDcname-URL11.COMPANYNAME.com.', ... 31 more exception(s).]\n\tstatus code: 400, request id: 3c845905-7f43-4965-ac51-30b9cceba64d"
```

Although The external DNS pod is in "Running" state.
``` kubectl -n extdns get pods
NAME                            READY   STATUS    RESTARTS   AGE

external-dns-5d5957d895-pbgm4   1/1     Running   0          150m
```

There are few things which we noted and might be helpful for debugging
1.  "cname-" gets appended after the PREFIX for every DNS
2.  "Desired change: CREATE " is being printed twice for each DNS in logs
3. We have "Public" as well as and "Private" hosted zone.

Any help will be greatly appreciated.
Kindly let me know in case any other information is required.

**Comment by javsalgar** [comment]
Hi,

It looks to me that, if the change is only in the external-dns image, then there might be a regression in external dns itself. Did you try reporting this to the upstream external-dns devs?
