### ISSUE TITLE
[bitnami/redmine] How could I install Bitnami Redmine for Linux?

### ISSUE THREAD

**Issue by hide393939** [bitnami/charts#13859]
### Name and Version

bitnami/Redmine

### What steps will reproduce the bug?

https://bitnami.com/stack/redmine/installer

### What do you see instead?

only an app for Mac

**Comment by javsalgar** [comment]
Hi,

In the Bitnami page you can see different options such as Containers, Single VM, Kubernetes or OVA. Note that we do not provide installers for Linux any more.
