### ISSUE TITLE
[bitnami/clickhouse] install failed

### ISSUE THREAD

**Issue by lusson-luo** [bitnami/charts#13855]
### Name and Version

bitnami/clickhouse 2.0.0

### What steps will reproduce the bug?

helm install clickhouse, throw err
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.PodSecurityContext`

kube version: v1.18.16

### Are you using any custom parameters or values?

no

### What do you see instead?

delete seccompProfile in values is ok
![image](https://user-images.githubusercontent.com/19859400/206075033-05c2310c-420c-4f5a-9a27-a1c91331b0ac.png)

**Comment by javsalgar** [comment]
Hi!

Please note that you are using a non-supported Kubernetes version. From the README.md:

```
### Prerequisites

- Kubernetes 1.19+
- Helm 3.2.0+
```

**Comment by lusson-luo** [comment]
> 你好！
> 
> 请注意，您使用的是不受支持的 Kubernetes 版本。来自 README.md：
> 
> ```
> ### Prerequisites
> 
> - Kubernetes 1.19+
> - Helm 3.2.0+
> ```

Ok, can you add it in readme need to block seccompProfile with Kubernetes 1.18,marybe someone use Kubernetes 1.18

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by lusson-luo** [comment]
ok, i write in readme this day

**Comment by lusson-luo** [comment]
@carrodher i had put pr in #14003
