### ISSUE TITLE
[bitnami/redmine] Plugins that require specific gems don't work

### ISSUE THREAD

**Issue by c23omega** [bitnami/charts#13863]
### Name and Version

bitnami/redmine:5.0.3-debian-11-r10

### What steps will reproduce the bug?

i've installed Redmine with a custom mysql database which works nicely. Now i added some plugins from RedmineUp, which have as dependency the redmine_crm gem. Redmine plugins might be shipped with a own gemfile, i have: `/opt/bitnami/redmine/plugins/redmine_agile/Gemfile` with the content `gem "redmine_crm"`.

The container got into a Crash LoopBackOff with the logs:
```redmine 10:18:36.79 
redmine 10:18:36.80 Welcome to the Bitnami redmine container
redmine 10:18:36.80 Subscribe to project updates by watching https://github.com/bitnami/containers
redmine 10:18:36.80 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redmine 10:18:36.80 
redmine 10:18:36.81 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 10:18:36.82 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 10:18:36.89 INFO  ==> Restoring persisted Redmine installation
redmine 10:18:36.96 INFO  ==> Trying to connect to the database server
redmine 10:18:37.06 INFO  ==> Executing database migrations
```

When running on the container in the diagnostic mode, and executing there `RAILS_ENV=production bundle exec rake db:migrate:status` manually i see:
```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze 
by running `bundle config unset deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* redmine_crm
```
Once i have done a `bundle config unset deployment && bundle install` the command `RAILS_ENV=production bundle exec rake db:migrate:status` succeeds. Also `/opt/bitnami/scripts/redmine/entrypoint.sh /opt/bitnami/scripts/redmine/run.sh` continues now over the Executing database migrations state and the passenger server is started.

Downside of the manual installation of the gems is for sure that the container doesn't start reliably, so there should be a possibility to add gems before that. Is such a way already existent and i just didn't see it, or is there more to be done?

### Are you using any custom parameters or values?

ingress and mariadb related ones, not of relevance for plugins.

### What is the expected behavior?

redmine should start fine and install the gems on demand

### What do you see instead?

gems are not installed as they should

### Additional information

Grepping through the scripts i don't see any logic regarding bundler installations. I suppose a good place would be somewhere in `/opt/bitnami/scripts/redmine/setup.sh`?

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

Answering your question, you could try adding extra logic in `setup.sh` that covers your use case and, if you think it is useful for the community, provide a PR in bitnami/containers.
