### ISSUE TITLE
[bitnami/jenkins] pod is not restarting on deletion

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#13871]
### Name and Version

bitnami/jenkins, latest

### What steps will reproduce the bug?

helm install jenkins jenkins
copied 50 jobs in jobs folder in jenkins home
deleted the pod 

### Are you using any custom parameters or values?

![Screenshot from 2022-12-08 11-09-50](https://user-images.githubusercontent.com/68244292/206366174-428627fc-c352-4443-86f6-a6d03db370aa.png)
 also allocated 200gi space which is way more than jobs size.

### What is the expected behavior?

i should be able to run all the jobs and also be able to restart the pod on deletion.

### What do you see instead?

jobs are running fine . But when i restart pod , pod does not come in runing state.

### Additional information

![Screenshot from 2022-12-08 11-13-46](https://user-images.githubusercontent.com/68244292/206367101-2dafc674-31d3-4b01-b53a-5a9121694556.png)
![Screenshot from 2022-12-08 11-13-29](https://user-images.githubusercontent.com/68244292/206367112-694cdbd2-0b60-4ea0-9ca1-42a0dae84bc5.png)

**Comment by abhishekgupta2205** [comment]
also when i copy only 5-10 jobs , all things are running fine .

**Comment by abhishekgupta2205** [comment]
also nothing is coming on logs

**Comment by javsalgar** [comment]
Hi,

Do you have an example of job that you configured in the instance?

**Comment by abhishekgupta2205** [comment]
they are simple java jobs that are used to deploy java services in pods in k8s.

**Comment by abhishekgupta2205** [comment]
Actually i am trying to migrate the jobs from one jenkins server to jenkins server running on k8s(helm charts) . For that i copy my jobs folder from 1 server to 2 server  and then reload the disk from ui(manage jennkins). Also when i try to run them they are running fine . But whenever i try to restart the pod after loading of jobs , the pod is not able to come in running condition. it keeps on restarting again and again.

**Comment by abhishekgupta2205** [comment]
@javsalgar any suggestion

**Comment by javsalgar** [comment]
Hi,

Could you share the logs of the restarting container? Could you also try updating the chart with `image.debug=true`?

**Comment by abhishekgupta2205** [comment]
there is no logs coming in time of restarting container.Also i have tried debug parameter earlier . no effect same issue

**Comment by javsalgar** [comment]
Looking at the probes it says `Connection Refused`. Did you change the container ports?

**Comment by abhishekgupta2205** [comment]
no i donot change the container ports
![Screenshot from 2022-12-15 21-39-47](https://user-images.githubusercontent.com/68244292/207910476-cb3ad6cf-a298-4256-8499-62283a0278f1.png)
i think this error is coming because pod is not starting and that is why it is giving connection refused

**Comment by abhishekgupta2205** [comment]
Also when i did some experiments , i found out that my pod restarts fine till my jobs folder size is around 1.1 gb but as soon as iit reaches 1.5 gb around it creates problem .

**Comment by abhishekgupta2205** [comment]
@javsalgar @migruiz4  any suggestion to solve this

**Comment by migruiz4** [comment]
Maybe the `liveness`/`readiness` probes are not long enough for the pod to restart.

That could explain why depending on the folder size it will come up or not.

I would suggest enabling the `startupProbe`, using a longer timer than the default, maybe something like this to ensure the pods have enough time to initialize:

```
startupProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 42
```

The liveness probe gives the pod 270 seconds (4,5 min.) to initialize, by enabling the startupProbe with the above settings, you will be giving the pods additional 600 seconds (10 min.) during its initialization.

The startupProbe does not necessarily slow down the pod initialization of successful restarts for 10 minutes, but failures will take longer to confirm as failed restarts.

**Comment by abhishekgupta2205** [comment]
i tried your suggestion but now it comes in running state and then again went 0/1 condition . this is happening many times

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-12-21 14-17-27](https://user-images.githubusercontent.com/68244292/208860544-faca44a2-9c1e-4362-883b-1feadf96962c.png)

**Comment by migruiz4** [comment]
Could you please share the output of the following commands?

```
# Pod description, especially interested in the pod events to see if the liveness probe failed or the container process failed
kubectl describe pod <pod_name>
# Logs from the pod previous to the restart 
kubectl logs -p <pod_name>
```

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-12-21 15-01-24](https://user-images.githubusercontent.com/68244292/208871756-2cf2e352-59f3-4d0c-9abe-64039681d71c.png)
logs of previous pod

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2022-12-21 15-00-12](https://user-images.githubusercontent.com/68244292/208871825-69e1bef8-019c-4113-9458-f65f8ae3487a.png)
describe pod

**Comment by migruiz4** [comment]
Hi @abhishekgupta2205,

In the Pod description, I see the message `Back-off restarting failed container`, which would mean the container main process exited with a non-zero status, causing the pod to restart.

In the logs from the pod that stopped working, there is a SEVERE log 'Failed loading plugin Email Extension Plugin', which could be the cause of the failure.

**Comment by abhishekgupta2205** [comment]
this is also shown in logs when pod is working fine . i don think this is the cause of the issue here

**Comment by abhishekgupta2205** [comment]
@migruiz4  any suggestion

**Comment by abhishekgupta2205** [comment]
@javsalgar @migruiz4  is there anything i can do to solve this problem
