### ISSUE TITLE
[bitnami/logstash] fails to restart when in a bad state

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#13873]
### Name and Version

bitnami/logstash

### What steps will reproduce the bug?

1. Deploy elasticsearch and kafka to a cluster
2. Deploy logstash to take messages from kafka into elasticsearch
3. Perform a rolling restart of kafka or elasticsearch
4. Logstash no longer puts messages into elasticsearch because a connection within itself is lost between elastic and/or kafka
5. Logstash appears running when in fact it should be restarted (probes only hit `/monitoring` which will always give information back, even though logstash is technically unhappy)

### What is the expected behavior?

I would expect that when logstash encounters an error, it would result in it restarting because it failed a `liveness` probe (requires kubernetes to restart the pod, since it doesn't actually recieve traffic)

### What do you see instead?

Logstash remains running, even though it has lost a connection to an upstream and/or downstream service (kafka <-- logstash --> elasticsearch)

**Comment by javsalgar** [comment]
Hi!

Is there any endpoint in logstash that can provide information about the bad state of the installation? It is not clear to me how to fix it as logstash is technically running but cannot connect to the other installations.
