### ISSUE TITLE
[bitnami/airflow] Please provide support for configurable/customizable airflow_local_settings.py

### ISSUE THREAD

**Issue by vincentwen1995** [bitnami/charts#13882]
### Name and Version

bitnami/airflow 14.0.5

### What is the problem this feature will solve?

Currently, there is not interface to allow users customize the `airflow_local_settings.py`, which provides the functionality to [define `pod_mutation_hook` that is applied to all the worker pods spinned up by `KubernetesExecutor` / `KubernetesPodOperator`](https://airflow.apache.org/docs/apache-airflow/stable/kubernetes.html#pod-mutation-hook).

This is especially useful for cloud use cases, where Airflow is deployed to the cloud Kubernetes cluster and a sidecar container is needed to sync the pod's filesystem with external storage like GCS buckets.

### What is the feature you are proposing to solve the problem?

One possible solution is to expose the string content of the `airflow_local_settings.py` as a configurable parameter, similar to the [implementation by airflow-helm](https://github.com/airflow-helm/charts/blob/3514394dec77e0004538365fbd4f82f6625928c6/charts/airflow/docs/faq/configuration/airflow-configs.md#airflow_local_settingspy)

### What alternatives have you considered?

Another possible solution would be to expose the parameters under `airflow_local_settings.py` separately under "Airflow common parameters", similar to templating `airflow.cfg` currently.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
