### ISSUE TITLE
[bitnami/mongodb] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+

### ISSUE THREAD

**Issue by sagimann** [bitnami/charts#13886]
### Name and Version

bitnami/mongodb 13.1.3

### What steps will reproduce the bug?

1. env: GKE 1.23 single-node cluster

If I run the following in cloud shell:
```
$ kubectl -n fab describe hpa my-mongo
```
The result first line shows:
```
Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
```
My cluster autoscaler isn't adding nodes for some reason and I'm trying to understand if it's related to this message.

When I look for such an object in your chart's repo, I can't find one. I didn't install this chart on the cloud so I'm not sure whether someone added it manually. All I know is that the chart was installed at the same day when this HPA object was created in the cluster.

Where is it coming from and is it ok to disable it under the assumption that the cluster autoscaler cannot do its job because the HPA is blocking it?
[values.txt](https://github.com/bitnami/charts/files/10195979/values.txt)

### Are you using any custom parameters or values?

attached above

### What is the expected behavior?

we can skip HPA and let cluster autoscaling work

### What do you see instead?

HPA is installed and has the above warning, cluster autoscaler does not change node count

**Comment by javsalgar** [comment]
Hi,

I can confirm that the HPA is not part of the MongoDB chart, therefore someone added it manually. In principle, removing it should not make the chart crash, but I recommend you to check with your team about the object and the reasons why it is added.
