### ISSUE TITLE
[bitnami/etcd] Ideal time for snapshot cron job

### ISSUE THREAD

**Issue by srivastav-abhishek** [bitnami/charts#1389]
**Which chart**:
version: 4.3.5

**Description**

In our deployments, we are having several microservices writing huge data onto etcd cluster continuously.
Disaster recovery is an essential process there. However, current scheduled time for snapshot cron job is 30 mins in values.yaml. By this time, data collected is going to huge (in GBs). Also, in case etcd crashes in between (scheduled cron job time ~ 30 mins) then snapshot wont be having updated values at all and we may end up loosing some relevant data for that time. 

We can't keep less snapshot  interval as it reduces system performance.

It would be helpful, if anyone can suggest an effective solution to this problem.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

I am no expert in etcd, but maybe the etcd snapshot job for your case would not be the best option, given your constraints. I am not sure which your cloud provider is, but maybe you can try checking their included options for volumes. For example, if you use AWS, and you are using an ebs provider, maybe you can check with them the options for EBS volume backups.
