### ISSUE TITLE
{bitnami/rabbitmq] Add persistentVolumeClaimRetentionPolicy

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#13917]
### Name and Version

rabbitmq latest

### What is the problem this feature will solve?

K8s has added persistentVolumeClaimRetentionPolicy to allow aytomated volume deletion when a stateful set is downsized or deleted. There was a request to add this capability to the bitnami etcd helm chart. This resulted in a merged PR. I'd ask to extend this capability to rabbitmq as well.

### What is the feature you are proposing to solve the problem?

Simply to allow persistentVolumeClaimRetentionPolicy in values such that it gets passed through to the statefulset spec.

### What alternatives have you considered?

None. It's a feature. Just want to be able to use it.

**Comment by Dragane** [comment]
Hi, is there any news regarding this feature?

**Comment by zenbones** [comment]
This got added to the etcd chart, any hope for rabbit?

**Comment by javsalgar** [comment]
Hi,

As mentioned, this is something in our backlog but we cannot guarantee an ETA. Feel free to replicate what it has been done in etcd to this chart with a PR and we will review it.

**Comment by zenbones** [comment]
This was marked solved but I see no PR for it and nothing in the docs for the chart. Has it actually been solved?

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement!  It was closed automatically by the stale bot given there were no new comments in the thread.

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
