### ISSUE TITLE
Enable both TLS and plain endpoints.

### ISSUE THREAD

**Issue by ztazz** [bitnami/charts#13913]
### Name and Version

bitnami/redis 17.2.0

### What is the problem this feature will solve?

Access Redis by TLS protocol from external components and plain inside of k8s.

### What is the feature you are proposing to solve the problem?

Implement "enablePlain" configuration key in HELM chart.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
