### ISSUE TITLE
[bitnami/redis] Expose Redis as Openshift Route

### ISSUE THREAD

**Issue by fabry00** [bitnami/charts#13914]
### Name and Version

bitnami/redis:7.0.5-debian-11-r25

### What steps will reproduce the bug?
```console
$ helm repo add my-repo https://charts.bitnami.com/bitnami

$ helm upgrade --install redis-ms my-repo/redis \
--set master.podSecurityContext.enabled=false \
--set master.containerSecurityContext.enabled=false \
--set auth.enabled=false \
--set image.debug=true \
--set architecture=standalone

$ echo "kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: redis 
spec:
  host: redis-ms.apps-crc.testing
  to:
    kind: Service
    name: redis-ms-master
  port:
    targetPort: tcp-redis
  wildcardPolicy: None" | oc create -f -
```

### What do you see instead?

I would like to expose an Openshift Route in order to connect to Redis from outside Openshift cluster

but if I connect with the external route I see the following error:

`"Unknown reply: H"`

while if I try to port-forward the traffic with `oc` and then connect to localhost the connection works as expected

Can you help me figure out how to expose Redis as a Route?
thanks

**Comment by javsalgar** [comment]
Hi,

I'm not an expert on Openshift routes, but if they are similar as Ingress rules, the issue may be that Routes expect http/https endpoints and you are exposing a redis protocol endpoint. Could you confirm with Openshift developers that Routes are compatible with non-http protocols?
