### ISSUE TITLE
[bitnami/airflow] how to configure airflow webserver password from a file.

### ISSUE THREAD

**Issue by denishant** [bitnami/charts#13926]
### Name and Version

bitnami/airflow

### What steps will reproduce the bug?

I am trying to install airflow using bitnami helm chart.

And currently, the bitnami/airflow helm chart provides two/three ways to configure passwords for the WebUI of the airflow webserver (i.e using secret, configmap and passing passwords directly into values.yaml).

But I want to configure the password for the WebUI of the airflow webserver using a file(like we can do in some other helm charts of bitnami, for example, we can do it in bitnami/redis using auth.usePasswordFiles).

Is there any way we can pass the password for the WebUI of the airflow webserver from a file?

### What do you see instead?

not able to pass password for airflow-webui from a file

**Comment by javsalgar** [comment]
Hi,

I believe we don't currently have a value that enables that setting in the airflow helm chart. However, the container allows setting a `_FILE` version for all the environment variables. We would need to add a `usePasswordFile` variable that, depending on that, sets the `*_PASSWORD`  variables using the `*_PASSWORD_FILE` counterpart. I will forward this to the engineering team but I cannot guarantee an ETA. If you want to speed up the process, you  can submit a PR and the team will take a look.

**Comment by denishant** [comment]
Hi,
I am not able to find the option/setting _FILE that allows setting all the environmental variables using a helm. Could you please refer me some articles on it.

**Comment by javsalgar** [comment]
Here you can see the reference

https://github.com/bitnami/containers/blob/main/bitnami/airflow/2/debian-11/rootfs/opt/bitnami/scripts/airflow-env.sh#L67
