### ISSUE TITLE
[bitnami/mariadb-galera] Several [Warning] in log of PODs regarding unauthenticated user

### ISSUE THREAD

**Issue by F43RY** [bitnami/charts#13925]
### Name and Version

bitnami/mariadb-galera:7.4.8

### What steps will reproduce the bug?

Fresh installation with replicas=3.
Observe logs in PODs.

### Are you using any custom parameters or values?

no custom values

### What do you see instead?

Several log every few seconds like the following:
```
[Warning] Aborted connection 686297 to db: 'unconnected' user: 'unauthenticated' host: '10.244.0.0' (This connection closed normally without authentication)
```

### Additional information

IP in log suggests the problem could come from livenessProbe/readynessProbe.

**Comment by javsalgar** [comment]
Hi,

This seems to be related with the liveness/readiness probes. Could you try disabling it to see if the messages continue appearing? This would give us a hint on the next steps to fix the isuse.

**Comment by F43RY** [comment]
Hi,
thanks for your reply. 
I think this is not an issue from chart because changing port number of NodePort the problem disappears so I have to dig better within my kube. I'm closing the issue
Thx again
