### ISSUE TITLE
Option to supply service name and pvc name from values.yaml

### ISSUE THREAD

**Issue by gumtreeautesting** [bitnami/charts#1394]
Can we have options to supply service name and pvc name from values.yaml so that
- An app can use that fixed service name to connect to db.
- new persistence claim does not happen in different releases.

I am new to k8s and helm so please guide if this is still possible with existing options.

Thanks a lot.

**Comment by andresbono** [comment]
Hi @gumtreeautesting, in general, it should be possible.

For instance, see:
https://github.com/bitnami/charts/blob/94926ab314a6ae5d24fe2d9fd8c454b0f282a8d9/bitnami/zookeeper/templates/svc.yaml#L4

You will be able to override that value by setting the `fullnameOverride` parameter:

```
helm install bitnami/zookeeper --set fullnameOverride=myzk
```
You can find the full list of parameters in the [README.md](https://github.com/bitnami/charts/tree/master/bitnami/zookeeper#configuration) of each chart.

I hope this is what you are looking for.
