### ISSUE TITLE
[bitnami/mariadb-galera] fails to init custom sql files from PV in docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by ledroide** [bitnami/charts#1395]
**Which chart**:
bitnami/mariadb-galera
Modified to mount a volume from a PVC instead of a ConfigMap - that misfits for sql files.

**Description**
* The first instance correctly finds *.sql.gz in a volmume mounted on /docker-entrypoint-initdb.d
* It tries to inject the database in mariadb
* MariaDB fails to find mysql.sock with error 2002

**Steps to reproduce the issue:**
1. replace the configmap mount by a persistentVolumeClaim :
```
--- a/mariadb-galera/templates/statefulset.yaml
+++ b/mariadb-galera/templates/statefulset.yaml
@@ -202,7 +202,7 @@ spec:
           {{- if .Values.persistence.subPath }}
           subPath: {{ .Values.persistence.subPath }}
           {{- end }}
-        {{- if or (.Files.Glob "files/docker-entrypoint-initdb.d/*.{sh,sql,sql.gz}") .Values.initdbScriptsConfigMap .Values.initdbScripts }}
+        {{- if or (.Files.Glob "files/docker-entrypoint-initdb.d/*.{sh,sql,sql.gz}") .Values.initdbScriptsConfigMap .Values.initdbScripts .Values.initdbScriptsVolume }}
         - name: custom-init-scripts
           mountPath: /docker-entrypoint-initdb.d
         {{- end }}
@@ -255,6 +255,11 @@ spec:
           configMap:
             name: {{ template "mariadb-galera.initdbScriptsCM" . }}
         {{- end }}
+        {{- if .Values.initdbScriptsVolume }}
+        - name: custom-init-scripts
+          persistentVolumeClaim:
+            claimName: {{ .Values.initdbScriptsVolume }}
+        {{- end }}
 {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
         - name: data
           persistentVolumeClaim:
```
2. populate the volume with and sql file (from another pod with identical UID/GID)
3. start the galera cluster : helm install --name db --values myvalues.yaml mariadb-galera

**Describe the results you received:**

Logs :
```
 15:13:20.72 INFO  ==> ** Starting MariaDB setup **
 15:13:20.84 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 15:13:20.84 INFO  ==> Initializing mariadb database...
 15:13:20.85 DEBUG ==> Ensuring expected directories/files exist...
 15:13:20.92 INFO  ==> Persisted data detected. Restoring...
 15:13:20.92 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
 15:13:20.92 DEBUG ==> Executing /docker-entrypoint-initdb.d/10-timezone.sql.gz
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)
 15:13:20.93 INFO  ==> Stopping mariadb...
```

**Describe the results you expected:**
Injecting a timezone database into mysql adabase in order to set up time_zone 'Europe/Paris'.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried :
* 10-timezone.sql file instead of 10-timezone.sql.gz (no difference)
* start with replication disabled : helm install --name db --values myvalues.yaml --set replication.enabled=false mariadb-galera (no difference)
* check permissions and owner of 10-timezone.sql.gz (same owner than mariadb PID)
* check read permissions on /docker-entrypoint-initdb.d

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @ledroide, thanks for reporting this issue. we will try to reproduce the issue and we will get back to you.

**Comment by sameersbn** [comment]
@ledroide Sorry for the delay. the custom init scripts are expected to be executed on the first boot only. There is a bug in the code that causes the custom scripts to be executed on every launch. A fix in being worked on to fix this

**Comment by ledroide** [comment]
That's good news, anyway I'm almost sure this issue "every launch" has no relation with the error "Can't connect to local mysql.sock with error 2002"

**Comment by sameersbn** [comment]
> "Can't connect to local mysql.sock with error 2002"

On first boot the `mysqld` server is started internally to perform initialization tasks which includes the execution of the custom scripts. On subsequent runs, the initialization part is skipped, which means the `mysqld` server is not running, but the custom init scripts are being executed and as the `mysqld` server is not started we are seeing this error.

Does that make sense?

**Comment by ledroide** [comment]
> Does that make sense?

Much more. :-)  Thanks

**Comment by drewhemm** [comment]
Just hit this issue...

```
 13:59:01.90 
 13:59:01.90 Welcome to the Bitnami mariadb-galera container
 13:59:01.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 13:59:01.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 13:59:01.90 Send us your feedback at containers@bitnami.com
 13:59:01.90 
 13:59:01.90 INFO  ==> ** Starting MariaDB setup **
 13:59:01.99 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 13:59:02.07 INFO  ==> Initializing mariadb database...
 13:59:02.09 DEBUG ==> Ensuring expected directories/files exist...
 13:59:02.11 INFO  ==> Persisted data detected. Restoring...
 13:59:02.12 INFO  ==> Configuring LDAP connection
 13:59:02.13 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
 13:59:02.13 DEBUG ==> Executing /docker-entrypoint-initdb.d/init.sql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)
```

Any progress on a fix since it was initially reported? How about a workaround?

**Comment by drewhemm** [comment]
I've found a workaround for this - will post the details tomorrow.

**Comment by ledroide** [comment]
My "workaround" is to automate the database injection once the galera cluster is already up and running, and ready to accept connctions. So I have to add many steps to avoid incomming requests to a  database that does not yet exist. It's more a "lesser evil" than a workaround. Don't do this ;-)

**Comment by drewhemm** [comment]
My workaround focuses on the logic described by @sameersbn:

> > "Can't connect to local mysql.sock with error 2002"
> 
> On first boot the `mysqld` server is started internally to perform initialization tasks which includes the execution of the custom scripts. On subsequent runs, the initialization part is skipped, which means the `mysqld` server is not running, but the custom init scripts are being executed and as the `mysqld` server is not started we are seeing this error.
> 

Instead of a native SQL init script, I wrote a bash script that first checks for the existence of the socket: If it exists, we are in initialisation mode and the SQL should be executed; if not, the script should exit without doing anything:

```
#!/bin/bash

echo "Checking for DB initialisation"

if [ -S /opt/bitnami/mariadb/tmp/mysql.sock ]; then
  echo "Running DB initialisation..."

  # I use a heredoc for easy formatting of the SQL.
  # The root password is conveniently available inside the container as an environment variable. 
  /opt/bitnami/mariadb/bin/mysql --user="root" --password="${MARIADB_ROOT_PASSWORD}" <<SQL
  --
  -- Initialisation script for mariadb-galera cluster
  --

  USE mysql;

  # More SQL here to create users and databases etc...
SQL

  echo "DB initialisation complete"

else
  echo "Not running initialisation, exiting..."
fi
```

I then used this script as the content of a Kubernetes ConfigMap (later changed to a Secret as in my use-case it contains passwords) and defined the name of the resource as the value of `initdbScriptsConfigMap`. 

This results in the following (abbreviated logs):

```
 09:51:31.62 INFO  ==> ** Starting MariaDB setup **
 09:51:31.68 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 09:51:31.73 INFO  ==> Initializing mariadb database...
 09:51:44.67 INFO  ==> Starting mariadb in background
/libmysqlgalera.sh: line 539: DB_REPLICATION_MODE: unbound variable
 09:51:46.36 INFO  ==> Configuring LDAP connection
 09:51:46.39 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
Checking for DB initialisation...
Running DB initialisation...
DB initialisation complete
 09:51:47.43 INFO  ==> Stopping mariadb
 09:51:51.44 INFO  ==> ** MariaDB setup finished! **
```

For changes post-first-boot, I am thinking about having a Kubernetes CronJob routinely execute an idempotent SQL script.

**Comment by andresbono** [comment]
Thanks @ledroide and @drewhemm for sharing your workarounds.

**Comment by jonahbohlmann** [comment]
Hello,

As describes, I added a file called "init.sql" to the folder "files/docker-entrypoint-initdb.d", next to my values.yaml with default values from this repo.
![image](https://user-images.githubusercontent.com/9147768/87349643-ed75c880-c556-11ea-98fd-1f43a5c25c09.png)

content of init.sql:
```
create database MyUserName;

CREATE USER 'MyUserName'@'%' IDENTIFIED BY 'MyPassword';

GRANT ALL PRIVILEGES ON MyUserName.* TO 'MyUserName'@'%';
```

To find more information I enabled the debug:
`debug: true`

But I was not able to see any output about executing my init.sql script. No error, no warning, no debug info. Nothing about any script or the lookup in "files/docker-entrypoint-initdb.d".
Also no configmap with the scripts are created in kubernetes.

I use minikube v1.11.0 as environment:  kubernetes v1.18.3 on docker 19.03.8

Any idea?

**Comment by andresbono** [comment]
Hi @jonahbohlmann, these are the commands that we executed, everything seems correct. Can you check them?

```bash
$ cd bitnami/mariadb-galera
$ mkdir -p files/docker-entrypoint-initdb.d/
$ cat >files/docker-entrypoint-initdb.d/init.sql <<EOF
create database MyUserName;

CREATE USER 'MyUserName'@'%' IDENTIFIED BY 'MyPassword';

GRANT ALL PRIVILEGES ON MyUserName.* TO 'MyUserName'@'%';
EOF
```
```
$ helm template . | grep -A17 initialization-configmap.yaml
# Source: mariadb-galera/templates/initialization-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-mariadb-galera-init-scripts
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-4.0.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
data:
  init.sql: |
    create database MyUserName;

    CREATE USER 'MyUserName'@'%' IDENTIFIED BY 'MyPassword';

    GRANT ALL PRIVILEGES ON MyUserName.* TO 'MyUserName'@'%';
---
```
```bash
$ helm install galera . --set image.debug=true

$ kubectl get configmap galera-mariadb-galera-init-scripts
NAME                                 DATA   AGE
galera-mariadb-galera-init-scripts   1      47s

$ kubectl logs galera-mariadb-galera-0 | grep -A7 "Loading user's custom files from"
mariadb 07:13:12.92 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mariadb 07:13:12.92 DEBUG ==> Executing /docker-entrypoint-initdb.d/init.sql
mariadb 07:13:12.92 DEBUG ==> Executing SQL command:
create database MyUserName;

CREATE USER 'MyUserName'@'%' IDENTIFIED BY 'MyPassword';

GRANT ALL PRIVILEGES ON MyUserName.* TO 'MyUserName'@'%';
```

Are you creating a new chart deployment from scratch or are you keeping PVCs from a previous test?

**Comment by jonahbohlmann** [comment]
Hi @andresbono , thank you!

I checked out this bitnami repo and executed your commands. I had the same output as you described.

From my repo folder I used the following command:
```
helm template database-cluster -f values.yaml --create-namespace -n core bitnami/mariadb-galera | grep -A17 initialization-configmap.yaml
```
And had no output.

Do I have to copy the whole "bitnami/mariadb-galera" folder content to my deployment repo? 
I thought I just need the repository and my own values file.

I am new to helm, so maybe it's my fault. It's just my understanding based on the helm documentation.

**Comment by andresbono** [comment]
Hi @jonahbohlmann, it seems it is required, but then you won't be receiving updates that we do in the chart. You might want to use the alternative values properties:

`initdbScriptsConfigMap` or `initdbScripts`.

**Comment by FighterLD** [comment]
i use helm chart version: 5.6.8 install，logs：
-debian-10-r52" already present on machine
  Normal   Created    37s (x2 over 41s)  kubelet            Created container mariadb-galera
  Normal   Started    37s (x2 over 41s)  kubelet            Started container mariadb-galera
  Warning  Unhealthy  6s                 kubelet            Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists!

**Comment by Mauraza** [comment]
Hi @FighterLD, 

Could you add more information about your issue, for example, the values are you using?

**Comment by FighterLD** [comment]
Hi @Mauraza :
$ cd bitnami/mariadb-galera
$ mkdir -p files/docker-entrypoint-initdb.d/
$ cat >files/docker-entrypoint-initdb.d/init-db.sql <<EOF
create database db_sync default character set utf8 collate utf8_general_ci; 
create database cloud-iot-atom default character set utf8 collate utf8_general_ci; 

$ helm3 template . | grep -A17 initialization-configmap.yaml
# Source: mariadb-galera/templates/initialization-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-mariadb-galera-init-scripts
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.6.8
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
data:
  init.sql: "create database db_sync default character set utf8 collate utf8_general_ci;
    \ncreate database cloud-iot-atom default character set utf8 collate utf8_general_ci;
    \ncreate user 'db_sync'@'%' identified by '0X2PiBWCfCdyGHP8Grn';\ncreate user 'cloud-iot-atom'@'%'
    identified by '0X2PiBWCfCdyGHP8Grn';\ngrant all privileges on db_sync.* to 'db_sync'@'%';\ngrant
    all privileges on dcloud-iot-atom.* to 'cloud-iot-atom'@'%';\""
---
# Source: mariadb-galera/templates/headless-svc.yaml

set values.yaml:
initdbScriptsConfigMap: mariadb-galera-init-scripts


kubectl get cm -n component |grep mariadb-galera
mariadb-galera-configuration   1      2m10s

error log：
  Warning  FailedMount  26s (x8 over 90s)  kubelet            MountVolume.SetUp failed for volume "custom-init-scripts" : configmap "mariadb-galera-init-scripts" not found

**Comment by FighterLD** [comment]
Hi @andresbono @Mauraza

$ cd bitnami/mariadb-galera
$ mkdir -p files/docker-entrypoint-initdb.d/
$ cat >files/docker-entrypoint-initdb.d/init-db.sql <<EOF
create database db_sync default character set utf8 collate utf8_general_ci;
create database cloud-iot-atom default character set utf8 collate utf8_general_ci;

$ helm3 template . | grep -A17 initialization-configmap.yaml
Source: mariadb-galera/templates/initialization-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: RELEASE-NAME-mariadb-galera-init-scripts
labels:
app.kubernetes.io/name: mariadb-galera
helm.sh/chart: mariadb-galera-5.6.8
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/managed-by: Helm
data:
init.sql: "create database db_sync default character set utf8 collate utf8_general_ci;
\ncreate database cloud-iot-atom default character set utf8 collate utf8_general_ci;
\ncreate user 'db_sync'@'%' identified by '0X2PiBWCfCdyGHP8Grn';\ncreate user 'cloud-iot-atom'@'%'
identified by '0X2PiBWCfCdyGHP8Grn';\ngrant all privileges on db_sync.* to 'db_sync'@'%';\ngrant
all privileges on dcloud-iot-atom.* to 'cloud-iot-atom'@'%';""

I set values.yaml:
# initdbScriptsConfigMap:

$ kubectl get cm -n component |grep mariadb-galera
mariadb-galera-configuration   1      3m1s
mariadb-galera-init-scripts    1      3m1s

describe po:
  Normal   Pulled     41s (x2 over 46s)  kubelet            Container image "docker.io/bitnami/mariadb-galera:10.5.9-debian-10-r52" already present on machine
  Normal   Created    41s (x2 over 46s)  kubelet            Created container mariadb-galera
  Normal   Started    40s (x2 over 46s)  kubelet            Started container mariadb-galera
  Warning  Unhealthy  2s                 kubelet            Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)'

logs -f :
mariadb 12:30:49.69 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable or does not exist. Configurations based on environment variables will not be applied for this file.
mariadb 12:30:49.69 INFO  ==> Persisted data detected. Restoring
mariadb 12:30:49.71 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mariadb 12:30:49.72 DEBUG ==> Executing SQL command:
select 1
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)
mariadb 12:30:51.74 DEBUG ==> Executing SQL command:
select 1
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)
mariadb 12:30:53.75 DEBUG ==> Executing SQL command:

**Comment by ljohnston** [comment]
Any news? This is a pretty big issue.

**Comment by Mauraza** [comment]
Hi @ljohnston,

Sorry, we still do not have any news. I created an internal task and we will update the issue when we have made progress.

**Comment by javsalgar** [comment]
Hi, 

I detected a race condition when using init scripts. Adding this PR to fix it https://github.com/bitnami/charts/pull/9161

Maybe this helps with the issue described here.
