### ISSUE TITLE
syntax error in bitnami/redis/templates/scripts-configmap.yaml

### ISSUE THREAD

**Issue by ftagada** [bitnami/charts#13956]
Hi,

while debugging an issue with the Redis helm package where the pods keep crashing, I found a syntax error in bitnami/redis/templates/scripts-configmap.yaml

there is a missing "; then" after the "if retry_while "failover_finished" ...

It was introduced there: https://github.com/bitnami/charts/pull/13021/commits/aac3cd3af56728f4a47f9d9b026d0bdd6a935e14  (line 500)

_Originally posted by @ftagada in https://github.com/bitnami/charts/issues/13021#issuecomment-1346264529_

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
