### ISSUE TITLE
[bitnami/clickhouse] zookeeper cluster replica is 2 

### ISSUE THREAD

**Issue by lusson-luo** [bitnami/charts#13954]
### Name and Version

bitnami/clickhouse 2.0.0

### What is the problem this feature will solve?

zookeeper cluster replica is 2 will cause cluster split brain, zookeeper cluster least replica is 3.

### What is the feature you are proposing to solve the problem?

zookeeper cluster error

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by lusson-luo** [comment]
ok, i will put a pr this day

**Comment by lusson-luo** [comment]
@carrodher #14002 
I put this pr
