### ISSUE TITLE
Secondary persistence must also have an option for existing claim

### ISSUE THREAD

**Issue by prasannjeet** [bitnami/charts#13962]
### Name and Version

bitnami/mariadb 11.4.1

### What is the problem this feature will solve?

Currently for secondary server, there is no option for providing an existing persistent volume claim.

### What is the feature you are proposing to solve the problem?

For cases where we need an existing claim to be used for secondary replications, a helm chart option of `secondary.persistence.existingClaim` must be given, just like it is provided for primary server.

### What alternatives have you considered?

As an alternative, I have used other helm chart options so that the claim that will be created can be bound to my persistent volume properly.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
