### ISSUE TITLE
[bitnami/harbor] adding annotations causes pods not to deploy

### ISSUE THREAD

**Issue by iamaverrick** [bitnami/charts#13979]
### Name and Version

bitnami/harbor 16.1.0

### What steps will reproduce the bug?

1. deploy default helm chart
2. add annotations to core via podAnnotations:
3. added the following 
```yaml
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/agent-inject-secret-harbor-creds: "database/creds/harbor"
vault.hashicorp.com/agent-inject-template-harbor-creds: |
      {{`{{- with secret "database/creds/harbor" -}}
        export POSTGRESQL_USERNAME="{{ .Data.username }}"
        export POSTGRESQL_PASSWORD="{{ .Data.password }}"
      {{- end }}`}}
vault.hashicorp.com/service: "https://vault.example.com"
vault.hashicorp.com/role: "internal-app"
vault.hashicorp.com/agent-limits-ephemeral: "1Gi"
```
6. harbor core pod is stuck in deployment
7. the same thing is relevant when trying to do the same to the following services
```yaml
notary:
   server:
       podAnnotations:
   signer:
        podAnnotations:
```

### What is the expected behavior?

We want to use hasicorp vault as a secret engine and inject it into the pods that require PostgreSQL connect and AWS creds. the only way to do this is to add proper annotations values to each service that relay on the secret engine.

### What do you see instead?

the error I've when adding annotations

```
2022-12-15 11:49:31 ERROR: command for release [harbor] failed: Install release [ harbor ] version [ 16.0.0 ] in namespace [ registry ] failed with non-zero exit code 1: exit status 1
output: 
--- stdout ---
Release "harbor" does not exist. Installing it now.
--- stderr ---
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Deployment.spec.template.metadata.annotations.annotations
```

**Comment by javsalgar** [comment]
Hi,

Could you try running with helm template to see the rendered output?

**Comment by iamaverrick** [comment]
Hi,

So that's what I'm saying the pods fails when adding the annotations.

helm fails completely when adding annotations to 
```
notary:
   server:
   signer:
```

when adding annotations to core helm doesn't fail but the pod doesn't deploy. this is what is get when i describe the deployment though.



```
Name:                   harbor-core
Namespace:              registry
CreationTimestamp:      Fri, 16 Dec 2022 12:24:07 -0500
Labels:                 app.kubernetes.io/component=core
                        app.kubernetes.io/instance=harbor
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=harbor
                        helm.sh/chart=harbor-16.0.0
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: harbor
                        meta.helm.sh/release-namespace: registry
Selector:               app.kubernetes.io/component=core,app.kubernetes.io/instance=harbor,app.kubernetes.io/name=harbor
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app.kubernetes.io/component=core
                app.kubernetes.io/instance=harbor
                app.kubernetes.io/name=harbor
  Annotations:  checksum/configmap: 41a9b949f37c6afcedab21e287564e274ad56a4b666252163426efc0f376cc2e
                checksum/configmap-envvars: 78ad17778a4691165bd82e96f4bc899473c2a0f0192f6307324b43c07ab82b43
                checksum/secret: 99e4d9842716e2dd4ca237bfb5571590ff4c955c934798991925d3360b973d5c
                checksum/secret-envvars: 30967628e115e556f85fdf97ceb4b17c3f2d3d0faa1f587ae318a47ee2d1b860
                checksum/secret-jobservice: 10df654e5070a9adc2b9bc7b7c9626e232a11fd38923d517bd3a03aaee2f8af3
                vault.hashicorp.com/agent-inject: true
                vault.hashicorp.com/agent-inject-secret-harbor-creds: database/creds/harbor
                vault.hashicorp.com/agent-inject-template-harbor-creds:
                  {{- with secret "database/creds/harbor" -}}
                    export POSTGRESQL_USERNAME="{{ .Data.username }}"
                    export POSTGRESQL_PASSWORD="{{ .Data.password }}"
                  {{- end }}
                vault.hashicorp.com/agent-limits-ephemeral: 1Gi
                vault.hashicorp.com/role: internal-app
                vault.hashicorp.com/service: https://vault.example.com
  Containers:
   core:
    Image:       docker.io/bitnami/harbor-core:2.6.2-debian-11-r5
    Ports:       8080/TCP, 8001/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
    Args:
      source /vault/secrets/harbor-creds && /opt/bitnami/scripts/harbor-core/entrypoint.sh harbor_core
    Liveness:   http-get http://:http/api/v2.0/ping delay=20s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/api/v2.0/ping delay=20s timeout=5s period=10s #success=1 #failure=6
    Environment Variables from:
      harbor-core-envvars  ConfigMap  Optional: false
      harbor-core-envvars  Secret     Optional: false
    Environment:
      BITNAMI_DEBUG:      false
      CORE_SECRET:        <set to the key 'secret' in secret 'harbor-core'>        Optional: false
      JOBSERVICE_SECRET:  <set to the key 'secret' in secret 'harbor-jobservice'>  Optional: false
    Mounts:
      /etc/core/app.conf from config (rw,path="app.conf")
      /etc/core/key from secret-key (rw,path="key")
      /etc/core/private_key.pem from token-service-private-key (rw,path="tls.key")
      /etc/core/token from psc (rw)
  Volumes:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      harbor-core
    Optional:  false
   secret-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  harbor-core
    Optional:    false
   token-service-private-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  harbor-core
    Optional:    false
   psc:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     harbor-core-744988fff (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  22s   deployment-controller  Scaled up replica set harbor-core-744988fff to 1
```

**Comment by Mauraza** [comment]
Hi @iamaverrick,

Did you try to add the annotation to the deployment of the charts and try to run a `helm template`?

**Comment by iamaverrick** [comment]
Hello @Mauraza 

We deploy our services using [Helmsman](https://github.com/Praqma/helmsman). But I have also tried the helm deployment and came up with the same result. But after further investigation, I noticed the following error when I described the Replica Sets for harbor core service.
`Warning  FailedCreate  14s (x13 over 36s)  replicaset-controller  Error creating: admission webhook "vault.hashicorp.com" denied the request: error creating new agent sidecar: failed to find service account volume mount`

It turns out that there is no service accounts for the deployments or a way to modify the name to match the one configured in the vault service. I guess this will fall into a feature request where we can have the ability to add service accounts to each service found in the harbor service and the ability to override the name. At least the most important ones which are harbor core, notary server, and notary signer.

**Comment by Mauraza** [comment]
Hi @iamaverrick,

I'm glad you find a solution. The serviceAccount no longer creates the secret (since [kubernetes 1.24](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes))

**Comment by iamaverrick** [comment]
Hi @Mauraza,

Yes thats correct since [K8s 1.24](https://developer.hashicorp.com/vault/tutorials/auth-methods/agent-kubernetes#kubernetes-1-24-only) but does this mean that going forward all services packaged by bitnami will not have a service account? I do see other services do deploy a service account e.g [keycloak](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/serviceaccount.yaml). In the [vault docs](https://developer.hashicorp.com/vault/tutorials/auth-methods/agent-kubernetes#kubernetes-1-24-only) even if I create a secret explicitly. the helm chart doesn't allow me to add it to the service which still causes the service to fail. please advise. thanks

```
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
```

**Comment by Mauraza** [comment]
Hi @iamaverrick,

Could you open another issue with keycloak, so as not to mix different assets in the same thread?

**Comment by iamaverrick** [comment]
@Mauraza 


Hey I'm not saying that there is an issue with keycloak. I'm showing you how keycloak has the ability to create serviceAccounts, and harbor does not. I successfully implemented Vault secret engine on keycloak already. 


I'm requesting the ability to create serviceAccounts with harbor services as well. That's why I'm saying that this isn't an issue but more like a feature request.

**Comment by Mauraza** [comment]
Hi @iamaverrick,

sorry for the misunderstanding. In that case, would you like to make a contribution by adding this to harbor? we would be happy to review it and improve the chart!!

**Comment by iamaverrick** [comment]
Yes will give it a shot.

**Comment by iamaverrick** [comment]
Hi @Mauraza,


I have worked on this and submitted a [PR](https://github.com/bitnami/charts/pull/14093); I'm not sure what I'm doing wrong maybe you can help. But all work was done using an organization account on GitHub, and the [PR](https://github.com/bitnami/charts/pull/14093) fails in one step because of this.

**Comment by Mauraza** [comment]
Hi @iamaverrick,

For sign, you can check the [details](https://github.com/bitnami/charts/pull/14093/checks?check_run_id=10283788735) of the job and follow the instructions.
