### ISSUE TITLE
[bitnami/airflow] worker doesn't have git command

### ISSUE THREAD

**Issue by syed-gilani** [bitnami/charts#13984]
### Name and Version

bitnami/airflow 14.0.4

### What steps will reproduce the bug?

I installed the bitnami airflow helm chart version 14.0.4 on a kubernetes cluster running in Rancher. I have added a task using BashOperator to a DAG that clones a git repo. The task fails with error git command not found. The airflow worker node doesn't have git installed.

Here is an image of the task that tries to clone a repository using git

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/59292422/207976786-ae11326f-d837-4311-83c0-ca1279a5f50f.png">

### What is the expected behavior?

The Task should be able to use git to clone the repository

### What do you see instead?

an error in the log that says girt command not found

### Additional information

I looked at the /usr/bin folder contents on the airflow-worker and it doesn't have git.

Here is an image of the contents in the /usr/bin folder

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/59292422/207976887-4de78eb5-8001-4d5b-89fb-c21e1f6d7b3c.png">

**Comment by corico44** [comment]
@syed-gilani Reviewing what you mention, I have been able to verify that for airflow-worker, the git package is not included, so it makes sense that the error that it doesn't exist is thrown. So I'll create an internal task so we can add the git package to airflow-worker. We will notify you in this same issue when the error has been solved.

**Comment by gongomgra** [comment]
Hi @syed-gilani,

Sorry for the delay on getting back to you. We have just released a new version of our Airflow chart bumping the airflow-worker image to a newer one including the `git` system package.

```
$ docker run --rm -i -u root bitnami/airflow-worker:2.7.2-debian-11-r1 dpkg -l git
airflow-worker 07:19:29.37
airflow-worker 07:19:29.37 Welcome to the Bitnami airflow-worker container
airflow-worker 07:19:29.38 Subscribe to project updates by watching https://github.com/bitnami/containers
airflow-worker 07:19:29.38 Submit issues and feature requests at https://github.com/bitnami/containers/issues
airflow-worker 07:19:29.38

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version            Architecture Description
+++-==============-==================-============-===================================================
ii  git            1:2.30.2-1+deb11u2 amd64        fast, scalable, distributed revision control system
```

I'm also linking here the PR to the container image for further references: [containers/PR51926](https://github.com/bitnami/containers/pull/51926).

Hope it helps!
