### ISSUE TITLE
What factors lead to the preference of storing all these helm charts in a single repo

### ISSUE THREAD

**Issue by IRobL** [bitnami/charts#1399]
Does anyone know where this pattern comes from?  It seems like it would make it much harder for people to contribute to helm charts if they have to clone so many unrelated projects to their local, doesn't it?

**Comment by juan131** [comment]
Hi @IRobL 

Thanks so much for your feedback.

We decided to have a single repository to store all the charts developed by Bitnami so it's easier for users to discover what new projects we're adding to our current catalog. It also simplifies our support since we need to track all the issues/PRs in a single repo.

The whole repository is about 20MB, therefore I don't think it means any problem regarding the amount of data to be cloned in order to contribute.

The file structure is pretty simple too so it should be really simple to find/contribute on the specific chart you're interested on.

**Comment by TheNotary** [comment]
I see, thanks for the response.  

I'm still new to Helm, but I think the most efficient workflow for when coming to a large chart repo is to clone to `~/tmp` and then copy the relevant chart folder to `~/dev/k8s_deployments/new_chart` where it gets it's own git repo and CI/ CD scripts added.  In the situation where I have something to contribute back to the open source community, my solution is to copy the entire folder back to the original clone, make a commit and then use ordinary github development.  If I make any custom changes that only apply exclusively to me (eg CI/CD stuff) and my home/ work k8s infrastructure, it becomes complicated to separate these non-reusable changes from actual features that I'd like to contribute.  

I think if support is finding things easier (and you're doing a great job, thanks!) then it's an understandable decision, especially if PRs from the community are not terribly helpful to the software delivery process.

**Comment by IRobL** [comment]
I see, thanks for the response.  

I'm still new to Helm, but I think the most efficient workflow for when coming to a large chart repo is to clone to `~/tmp` and then copy the relevant chart folder to `~/dev/k8s_deployments/new_chart` where it gets it's own git repo and CI/ CD scripts added.  In the situation where I have something to contribute back to the open source community, my solution is to copy the entire folder back to the original clone, make a commit and then use ordinary github development.  If I make any custom changes that only apply exclusively to me (eg CI/CD stuff) and my home/ work k8s infrastructure, it becomes complicated to separate these non-reusable changes from actual features that I'd like to contribute.  When this is the case, I've noticed that I tend to not bother moving down the contribution process.  

I think if support is finding things easier (and you're doing a great job, thanks!) then it's an understandable decision, especially if PRs from the community are not terribly helpful to the software delivery process.

**Comment by juan131** [comment]
HI @IRobL 

> I think the most efficient workflow for when coming to a large chart repo is to clone to ~/tmp and then copy the relevant chart folder to `~/dev/k8s_deployments/new_chart` where it gets it's own git repo and CI/ CD scripts added.

I guess that depends on the workflow you're used to follow when comes to develop software. There are many ways to setup your CI/CD pipeline it's also possible to use a single repo with multiple charts (it's possible to configure your scripts so they detect what chart(s) are affected by your changes so it only triggers the corresponding CI/CD jobs).

> I think if support is finding things easier (and you're doing a great job, thanks!) then it's an understandable decision, especially if PRs from the community are not terribly helpful to the software delivery process.

Indeed, the community is essential on these projects. Our charts have been improved significantly thanks to the contributions and suggestions the community did.

**Comment by IRobL** [comment]
I don't totally follow what you're suggesting.  What CI/ CD system do you use that doesn't track configurations into the repo as code artifacts?  I currently use Jenkins and GitLab and am using some variation of the pattern I detailed above.
