### ISSUE TITLE
Configure HTTPS port when `tls.enabled` is true. 

### ISSUE THREAD

**Issue by ooraini** [bitnami/charts#14023]
### Name and Version

bitnami/clickhouse

### What is the problem this feature will solve?

Right now, when you enable TLS the HTTPS port in not configured.

There are three places that I think of that need to change:

- https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#http-porthttps-port
- The Service objects(internal and external)
-  The container ports

### What is the feature you are proposing to solve the problem?

HTTPS

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
