### ISSUE TITLE
caBundleSecret not working when using core.runAsUser

### ISSUE THREAD

**Issue by druppertbcee** [bitnami/charts#14049]
### Name and Version

bitnami/harbor 16.1.1

### What steps will reproduce the bug?

When deploying on Openshift with `core.containerSecurityContext.runAsUser` set to another non-privileged user than 1001 and with `internalTLS.cabundleSecret` set, the script `libharbor.sh` is unable to install the custom `/etc/ssl/certs/ca-certificates.crt` on the container harbor-core

This seems due to the file being set as 644 which does not provide sufficient permissions for the other user to modify it.

### Are you using any custom parameters or values?

`core.containerSecurityContext.runAsUser` set to Openshift namespace ID
`internalTLS.cabundleSecret` for our webproxy

### What is the expected behavior?

Custom CA is installed and webproxy traffic works

### What do you see instead?

Webproxy is rejected
Manual run: `/opt/bitnami/scripts/libharbor.sh: line 55: /etc/ssl/certs/ca-certificates.crt: Permission denied`

### Additional information

No issue or error message appears even on debug-mode, manual run required

**Comment by carrodher** [comment]
The user should belong to the root group regardless of the UID, it could be any random user but it should be part of the root group, see https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift

**Comment by druppertbcee** [comment]
Apologies for the confusing description. The user belongs to the root group (as default for Openshift). but the file permissions are owner root:root with chmod 644 so being root-group seems insufficient to append certificates as done by /opt/bitnami/scripts/libharbor.sh function install_cert()

```
$ id
uid=1000XX0000(1000XX0000) gid=0(root) groups=0(root),1000XX0000
```

Is internalTLS.cabundleSecret confirmed working with default 1001 UID? Unless I'm completely mistaken the permission error should arise whenever internalTLS.cabundleSecret is used with a non-root container on this version?

**Comment by fmulero** [comment]
Hi @druppertbcee 

I am trying to reproduce your issue, but I am not able to do it. If you log in the harbor-core container and try to run the  install_cert() function from /opt/bitnami/scripts/libharbor.sh, are you getting any error?

**Comment by druppertbcee** [comment]
My apologies for the delayed response! Unfortunately yes, please find a console output below. 
As it works for you, it's possible that something in my setup is particular but I don't see what

`$ source /opt/bitnami/scripts/libharbor.sh
$ install_cert /harbor_cust_cert/custom-ca.crt
bash: /etc/ssl/certs/ca-certificates.crt: Permission denied

$ id
uid=1000XX0000(1000XX0000) gid=0(root) groups=0(root),1000XX0000

$ ls -altr /etc/ssl/certs/ca-certificates.crt
-rw-r--r--. 1 root root 200313 Dec 19 04:02 /etc/ssl/certs/ca-certificates.crt`

**Comment by druppertbcee** [comment]
While it's probably ovious, I want to confirm that a workaround by using a subPath volume-mount directly on /etc/ssl/certs/ca-certificates.crt does work to resolve the issue of untrusted CA. Naturally this replaces the CA file instead of appending it, which works fine for my specific use case but is not a perfect solution.

```
oc -n harbor patch deployment/harbor-core -p '{ "spec": { "template": { "spec": { "volumes": [ { "name": "ca-patch", "secret": { "secretName": "MY_CA_SECRET", "defaultMode": 420 } } ] } }} }'
oc -n harbor patch deployment/harbor-core -p '{ "spec": { "template": { "spec": { "containers": [ { "name": "core" , "volumeMounts": [ { "name": "ca-patch" , "mountPath": "/etc/ssl/certs/ca-certificates.crt", "subPath": "ca.crt" } ]}  ] } } } }'
```

**Comment by fmulero** [comment]
Hi @druppertbcee 

You are completely right, it doesn't work with user 1001 either. We are working on it, I'll back with any news.

**Comment by fmulero** [comment]
PR #14332 should fix this issue
