### ISSUE TITLE
Wordpress Chart PHP TimeLimit / PHP Max Input Vars increase

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#14047]
### Name and Version

bitnami/wordpress:latest

### What is the problem this feature will solve?

Can we increase the PHP Time limit and PHP Max Input Vars, this is necessary for Installation with lot's of Plugins and large Themes with Sample Content.

### What is the feature you are proposing to solve the problem?

Increase PHP Time Limit and Max Input Vars

**Comment by Mauraza** [comment]
Hi @pomland-94,

You can use your wp-config.php  with your values including the change of TimeLimit and Max Input Vars or the variable 'wordpressExtraConfigContent' to add extra content to the wp-config.php. 
Please check the [READMe.md](https://github.com/bitnami/charts/tree/main/bitnami/wordpress#wordpress-configuration-parameters)  for the different variables.

**Comment by pomland-94** [comment]
I think it's not releated to WordPress directly, it's releated to the PHP Proccess which runs WordPress.

https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars

https://www.php.net/manual/de/function.set-time-limit.php

**Comment by Mauraza** [comment]
Hi @pomland-94,

This is another alternative to the PHP.ini method. Simply add/edit the following line in the wp-config.php of your WordPress
For example:
```
set_time_limit(300);
```
The same with max input vars 
For example:
```
@ini_set( 'max_input_vars' , 3000 );
```
If you want to change the php.ini you can create a script `customPostInitScripts` 
Please check this old issue https://github.com/bitnami/charts/issues/10329
