### ISSUE TITLE
[postgresql-ha] Data loss occurred on Postgres DB

### ISSUE THREAD

**Issue by decipher27** [bitnami/charts#14044]
### Name and Version

bitnami/postgresql-ha:9.0.14

### What steps will reproduce the bug?

This might help to reproduce the issue: [90%]

Ingest data into Postgres - between 15-16Gi [[fake-data](https://vnegrisolo.github.io/postgresql/generate-fake-data-using-sql)]

**Test-1:** 
Restart the standby pods together and you will notice the cloning from primary data starts from the logs. The primary pod searches for the child nodes until the cloning by standby pods is complete. After this, all 3 pods lose the data

**Test-2:**
Restart the standby pods and after the cloning completes the primary outputs state it's connected to both standby pods. At this state, restart the primary pod. Leader election happens and one of the standby is promoted to Primary. 
During this state ^ the other standby starts following the newer primary and the older primary will be "Running as Primary"  Newer primary and new standby lose data at this point. 

This is highly likely should help to replicate the behavior. 

### Are you using any custom parameters or values?

``` yaml
postgresql:
  repmgrFenceOldPrimary: true

  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120
```

### What is the expected behavior?

The expected behavior is that the data should persist even after restarting Postgres pods, be it primary or standby pods.

### What do you see instead?

I noticed complete data loss occurring.

### Additional information

We run 3 replicas postgresql-ha on an AWS EKS Cluster. One pod is the primary and the other two as standby.   Currently running version of postgresql-ha: 14.3.0-debian-10-r11
**Attaching the logs of primary and standby pod logs:**
[standby-pod-2.log](https://github.com/bitnami/charts/files/10268865/standby-pod-2.log)
[standby-pod-0.log](https://github.com/bitnami/charts/files/10268867/standby-pod-0.log)
[primary-pod-1.log](https://github.com/bitnami/charts/files/10268873/primary-pod-1.log)

Here data got wiped from pod-0 and pod-2 and data persisted in primary pod i.e pod-1
If you check the status of the pods after exec into pod-0  - shows  pod-0 being the new primary and pod-2 the standby and pod-0 don't know if pod-1 exists which was the older primary. See the screenshot below:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/30067293/208667956-c6097e26-78b9-4fb3-b613-c8efbce730cd.png">

The below screenshot is from pod-1 which was the older primary. 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/30067293/208668528-3ddc070e-171e-4696-ba90-dd649cef72dc.png">

**Comment by decipher27** [comment]
Hi folks, any updates?

**Comment by jotamartos** [comment]
Hi @decipher27,

Thank you for reporting this issue. We are going to work on reproducing and evaluating it. If we need more details, we will ask you for that.

Please also note that due to the upcoming holidays period, response times will inevitably suffer. We will update this ticket again once we have more information. 

Thanks

**Comment by decipher27** [comment]
Hello, any updates here? @jotamartos

**Comment by jotamartos** [comment]
Sorry for the delay here @decipher27. I started working on reproducing this issue during these days and I wanted to give you an update today. 

Unfortunately, I couldn't reproduce the issue. I tried many different times (either with the default values or with the ones you mentioned) and everything worked as expected. I followed the guide you posted and created a table with 10 million entries 

```
CREATE DATABASE test_db;
\c test_db
CREATE TABLE users(
  id    SERIAL PRIMARY KEY,
  email VARCHAR(40) NOT NULL UNIQUE
);
INSERT INTO users(email)
SELECT
  'user_' || seq || '@' || (
    CASE (RANDOM() * 2)::INT
      WHEN 0 THEN 'gmail'
      WHEN 1 THEN 'hotmail'
      WHEN 2 THEN 'yahoo'
    END
  ) || '.com' AS email
FROM GENERATE_SERIES(1, 10000000) seq;
```

This generates a 1.5GB table which I assume should be enough to reproduce this issue

```
test_db=# SELECT pg_size_pretty( pg_database_size('test_db') );
 pg_size_pretty
----------------
 1543 MB
(1 row)
```

No matter if I follow the "Test 1" or "Test 2" approaches, all data is persisted. 

> Leader election happens and one of the standby is promoted to Primary.
> During this state ^ the other standby starts following the newer primary and the older primary will be "Running as Primary" Newer primary and new standby lose data at this point.

I saw the promotion message 

```
NOTICE: waiting up to 60 seconds (parameter "promote_check_timeout") for promotion to complete
DEBUG: get_recovery_type(): SELECT pg_catalog.pg_is_in_recovery()
2023-01-10 11:30:09.487 GMT [236] LOG:  selected new timeline ID: 2
2023-01-10 11:30:09.590 GMT [236] LOG:  archive recovery complete
2023-01-10 11:30:09.597 GMT [234] LOG:  checkpoint starting: force
2023-01-10 11:30:09.605 GMT [232] LOG:  database system is ready to accept connections
2023-01-10 11:30:10.215 GMT [234] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.606 s, sync=0.005 s, total=0.618 s; sync files=7, longest=0.003 s, average=0.001 s; distance=32768 kB, estimate=32768 kB
DEBUG: get_recovery_type(): SELECT pg_catalog.pg_is_in_recovery()
INFO: standby promoted to primary after 1 second(s)
DEBUG: setting node 1001 as primary and marking existing primary as failed
DEBUG: begin_transaction()
DEBUG: commit_transaction()
NOTICE: STANDBY PROMOTE successful
DETAIL: server "jota-psqlha-postgresql-ha-postgresql-1" (ID: 1001) was successfully promoted to primary
```

However, I didn't see any "Running as Primary" message in "pod-0" (I checked your log file and didn't see that message either) but I found this line in the log file

```
$ kubectl logs -f jota-psqlha-postgresql-ha-postgresql-0
postgresql-repmgr 11:30:15.83
postgresql-repmgr 11:30:15.83 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:30:15.84 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 11:30:15.84 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-repmgr 11:30:15.84
postgresql-repmgr 11:30:15.87 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:30:15.90 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:30:15.91 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:30:15.92 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:30:16.10 INFO  ==> Auto-detected primary node: 'jota-psqlha-postgresql-ha-postgresql-1.jota-psqlha-postgresql-ha-postgresql-headless.jotamartos.svc.cluster.local:5432'
...
```

**Comment by decipher27** [comment]
Can you try adding 15-20 GB data? and then reproduce with the steps provided above?

**Comment by decipher27** [comment]
"Running as Primary" is noticed when you get the status of postgresql cluster from inside the pod.  I believe it won't show up in the logs. 
```Ruby
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
````

**Comment by jotamartos** [comment]
Hi @decipher27,

To confirm there is not any problem with your environment, can you try to reproduce the issue with the "1.5GB example" I posted above? As I mentioned I tried to reproduce the issue many times and everything worked well. Let's see if the issue is reproducible with that amount of data in your environment first. 

Thanks

**Comment by exfly** [comment]
My data exceeds 100g and this problem is reproduced. I would like to ask if there is any progress on this issue.

**Comment by rafariossaa** [comment]
Hi @exfly 
  Would you like to elaborate on your use case ?
  Not sure if this the exact same case because this could change depending on your cluster speed and such.
