### ISSUE TITLE
[bitnami/elasticsearch] Status is red after deploying the solution

### ISSUE THREAD

**Issue by axelczk** [bitnami/charts#14055]
### Name and Version

Bitnami/elasticsearch 19.5.5

### What steps will reproduce the bug?

1. Launch the chart with at least one data node
2. Check the cluster health
3. Cluster is RED because there is no data node

### Are you using any custom parameters or values?

No

### What is the expected behavior?

It should have a least one data node. 

### What do you see instead?

0 data node. 

### Additional information

Since your chart is using your docker image (https://hub.docker.com/r/bitnami/elasticsearch), node role should be defined using the env variable ELASTICSEARCH_NODE_TYPE. In the current chart, you are using ELASTICSERACH_NODE_ROLE to set the role. 

Is the error inside the documentation of your docker image or in the chart ? 

If this change was also made on the docker image, to have both use the ELASTICSEARCH_NODE_ROLE env variable, you should add a note in the chart documentation to inform user that the chart isn't backward compatible with ES 7.17 docker image since these use the ELASTICSEARCH_NODE_TYPE env variable.

**Comment by jotamartos** [comment]
Hi @axelczk,

I just tried to reproduce the issue but I couldn't do so. I just installed the latest version of the bitnami/elasticsearch solution (with no customizations) and the status is green 

```
{
  "cluster_name": "elastic",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 8,
  "number_of_data_nodes": 2,
  "active_primary_shards": 1,
  "active_shards": 2,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```

Regarding the env vars you mentioned, the chart configures the NODE_ROLES env var because it's the env var to use when using Elasticsearch 8.x. The container shows this warning

```
Setting ELASTICSEARCH_NODE_TYPE is not available when using Elasticsearch 8, use ELASTICSEARCH_NODE_ROLES instead.
```

**Comment by axelczk** [comment]
So there is an error in the documentation of the docker image I have linked ?

I was using this chart with a version of elastic 7.17 since you have removed all the previous chart from your repository. Maybe you could add a warning in the documentation to warn user about backward compatibility between this chart and a version of elasticsearch before 8.X. 

Anyway, you can close this issue

**Comment by jotamartos** [comment]
I'll work on updating the information in the README, ELASTICSEARCH_NODE_ROLES must be the env var to use and that one also works with Elasticsearch 7.x as you can see here:

https://github.com/bitnami/containers/blob/main/bitnami/elasticsearch/8/debian-11/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L284
