### ISSUE TITLE
slave is following older master after failover 

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#14056]
### Name and Version

bitnami/redis , latest

### What steps will reproduce the bug?

helm install redis
sentinel enabled - true

### Are you using any custom parameters or values?

when i install these helm chart with the given parameters , it work fine and all the functionalities are working i.e master filure is handed correctly . 
also when i connect to sentinel i get masters info in the fom
ip - redis-node-0.qa 
port - 30106

but I want the actual IP should be shown in the column instead of redis-node-0.qa . so I made some changes in scripts.configmap.yaml file in getting the full hostname function. 
```diff
 {{- else if eq .Values.sentinel.service.type "NodePort" }}
-       echo "${hostname}.{{- .Release.Namespace }}"
+       echo "192.168.49.2"   // this is my minikube ip
```
### What is the expected behavior?

when I connect to sentinel and see master info, it shows
```
ip -192.168.49.2
-p 30106
```
but when I do master failover by deleting the pod, the slaves is following the older master.
eg - let's say I have master, slave 1, slave 2 .  after failover it should be like 
new master- slave1
new slaves - master ,slave 2

### What do you see instead?

after failover 
new master- slave1
new slaves - master
and now slave 2 is slave of masterpod
  slave1->master->slave2

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Redis container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by abhishekgupta2205** [comment]
is there a way that i can get my node ip instead of redis-node-0.qa in ip field .
