### ISSUE TITLE
[bitnami/minio]: helm upgrade fails and reports rootPassword is not set

### ISSUE THREAD

**Issue by kapilgarg1996** [bitnami/charts#14069]
### Name and Version

bitnami/minio: 11.9.1

### What steps will reproduce the bug?

1. Install bitnami/minio chart
2. Upgrade bitnami/minio chart

### Are you using any custom parameters or values?

values.yaml
```yaml
fullnameOverride: "minio"
mode: standalone
defaultBuckets: "logs"  
```

### What is the expected behavior?

Upgrades without any problem

### What do you see instead?
```
Error: UPGRADE FAILED: template: test/charts/minio/templates/NOTES.txt:91:4: executing "test/charts/minio/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredMinioPasswordErrors) "context" $)>: error calling include: template: test/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$ROOT_PASSWORD' to the command. To get the current value:

export ROOT_PASSWORD=$(kubectl get secret --namespace "test" minio -o jsonpath="{.data.root-password}" | base64 -d)
```
### Additional information

This is not an issue in the templates itself, 
standalone deployment is configured to use the secret value from auto-generated secret
```yaml
- name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" . }}
                  key: root-password
```
This is an issue in the NOTES.txt file. The following checks fail the upgrade.
```
{{- if and (not .Values.auth.existingSecret) (not .Values.auth.forceNewKeys) (not .Values.gateway.enabled) -}}
  {{- $requiredRootUser := dict "valueKey" "auth.rootUser" "secret" $secretName "field" "root-user" -}}
  {{- $requiredRootPassword := dict "valueKey" "auth.rootPassword" "secret" $secretName "field" "root-password" -}}
  {{- $requiredPasswords = append $requiredPasswords $requiredRootUser -}}
  {{- $requiredPasswords = append $requiredPasswords $requiredRootPassword -}}
{{- end -}}
```

**Comment by carrodher** [comment]
Are you setting the password from the existing deployment before upgrading using `--set auth.rootPassword=$ROOT_PASSWORD`?

The value for `ROOT_PASSWORD` can be obtained by running
```
$ export ROOT_PASSWORD=$(kubectl get secret --namespace "test" minio -o jsonpath="{.data.root-password}" | base64 -d)
```

**Comment by kapilgarg1996** [comment]
Nope, there is no requirement to do so from the chart's perspective as chart automatically gets the value from the secret.

But NOTES.txt doesn't understand that and forces to set the password using `--set auth.rootPassword=$ROOT_PASSWORD`

**Comment by carrodher** [comment]
I see, thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by kapilgarg1996** [comment]
Sure, I will raise the PR. Thanks

**Comment by beasteers** [comment]
I'm also experiencing this with the redis chart

**Comment by kapilgarg1996** [comment]
@beasteers I am almost done with the changes
