### ISSUE TITLE
kafka not coming up after aws instance restart in minikube

### ISSUE THREAD

**Issue by revoorunischal** [bitnami/charts#1406]
Hi,
I have installed kafka in aws t3a medium server using minikube,kubernates and helm chart, Its up properly and accessible. But when i bring down the AWS instance and bring it up and start the minikube the pods kafka and zookeeper are not starting and having the following errors

Zookeeper

> Welcome to the Bitnami zookeeper container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
> 
> WARN ==> You set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
> nami INFO Initializing zookeeper
> zookeep INFO ==> No injected configuration files found. Creating default config file...
> zookeep INFO ==> Setting '-Xmx1024m -Xms1024mm' as heap size...
> zookeep INFO ==> Deploying ZooKeeper from scratch...
> zookeep INFO ==> Validating inputs...
> Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/zookeeper/data'
> 

Kafka

> 11:03:42.29
> 11:03:42.29 Welcome to the Bitnami kafka container
> 11:03:42.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
> 11:03:42.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
> 11:03:42.29 Send us your feedback at containers@bitnami.com
> 11:03:42.29
> 11:03:42.29 INFO ==> ** Starting Kafka setup **
> 11:03:42.34 WARN ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
> mkdir: cannot create directory '/bitnami/kafka/data': Permission denied
> 

The following is the command used to install kafka

helm install bitnami/kafka

Can you please help me what should be changed?

**Comment by carrodher** [comment]
In order to check the volumes, can you run the following commands and share here the output?

- `kubectl get pvc
- `kubectl describe pvc {NAME}`
- `kubectl describe pv {VOLUME}`

Take into account you need to replace the placeholders by the values obtained in your specific case via the first command.

Apart from that, can you share some hints about how did you deploy the application?

**Comment by revoorunischal** [comment]
Th following are the outputs for each of the commands 

**kubectl get pvc**
> NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> data-dangling-mouse-kafka-0       Bound    pvc-2cb084ff-c860-492a-9a2f-87e253ba89fe   8Gi        RWO            standard       16h
> data-dangling-mouse-zookeeper-0   Bound    pvc-a3637a11-c854-460d-a1a3-92bb7d72f30c   8Gi        RWO            standard       16h


 **kubectl describe pvc data-odd-owl-kafka-0**

> Name:          data-odd-owl-kafka-0
> Namespace:     default
> StorageClass:  standard
> Status:        Bound
> Volume:        pvc-76759d97-5fc6-45c1-a334-8802e2701f23
> Labels:        app.kubernetes.io/component=kafka
>                app.kubernetes.io/instance=odd-owl
>                app.kubernetes.io/name=kafka
> Annotations:   control-plane.alpha.kubernetes.io/leader:
>                  {"holderIdentity":"18071165-d2fa-11e9-ab5c-0a37286bd73c","leaseDurationSeconds":15,"acquireTime":"2019-09-09T12:12:43Z","renewTime":"2019-...
>                pv.kubernetes.io/bind-completed: yes
>                pv.kubernetes.io/bound-by-controller: yes
>                volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
> Finalizers:    [kubernetes.io/pvc-protection]
> Capacity:      8Gi
> Access Modes:  RWO
> VolumeMode:    Filesystem
> Mounted By:    <none>
> Events:        <none>


**kubectl describe pvc data-dangling-mouse-kafka-0** 

> Name:          data-dangling-mouse-kafka-0
> Namespace:     default
> StorageClass:  standard
> Status:        Bound
> Volume:        pvc-2cb084ff-c860-492a-9a2f-87e253ba89fe
> Labels:        app.kubernetes.io/component=kafka
>                app.kubernetes.io/instance=dangling-mouse
>                app.kubernetes.io/name=kafka
> Annotations:   control-plane.alpha.kubernetes.io/leader:
>                  {"holderIdentity":"cc3193b2-d323-11e9-a73c-0a37286bd73c","leaseDurationSeconds":15,"acquireTime":"2019-09-09T17:04:51Z","renewTime":"2019-...
>                pv.kubernetes.io/bind-completed: yes
>                pv.kubernetes.io/bound-by-controller: yes
>                volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
> Finalizers:    [kubernetes.io/pvc-protection]
> Capacity:      8Gi
> Access Modes:  RWO
> VolumeMode:    Filesystem
> Mounted By:    dangling-mouse-kafka-0
> Events:
>   Type    Reason                 Age                From                                                           Message
>   ----    ------                 ----               ----                                                           -------
>   Normal  ExternalProvisioning   16h (x2 over 16h)  persistentvolume-controller                                    waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
>   Normal  Provisioning           16h                k8s.io/minikube-hostpath cc3193b2-d323-11e9-a73c-0a37286bd73c  External provisioner is provisioning volume for claim "default/data-dangling-mouse-kafka-0"
>   Normal  ProvisioningSucceeded  16h                k8s.io/minikube-hostpath cc3193b2-d323-11e9-a73c-0a37286bd73c  Successfully provisioned volume pvc-2cb084ff-c860-492a-9a2f-87e253ba89fe


**kubectl describe pv pvc-2cb084ff-c860-492a-9a2f-87e253ba89fe**

> Name:            pvc-2cb084ff-c860-492a-9a2f-87e253ba89fe
> Labels:          <none>
> Annotations:     hostPathProvisionerIdentity: cc3192f8-d323-11e9-a73c-0a37286bd73c
>                  pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
> Finalizers:      [kubernetes.io/pv-protection]
> StorageClass:    standard
> Status:          Bound
> Claim:           default/data-dangling-mouse-kafka-0
> Reclaim Policy:  Delete
> Access Modes:    RWO
> VolumeMode:      Filesystem
> Capacity:        8Gi
> Node Affinity:   <none>
> Message:         
> Source:
>     Type:          HostPath (bare host directory volume)
>     Path:          /tmp/hostpath-provisioner/pvc-2cb084ff-c860-492a-9a2f-87e253ba89fe
>     HostPathType:  
> Events:            <none>
>

**Comment by andresbono** [comment]
Additional info: https://github.com/bitnami/bitnami-docker-zookeeper/issues/16#issuecomment-529917466

**Comment by carrodher** [comment]
Hi, it seems we are duplicating the threads, let's continue talking on https://github.com/bitnami/bitnami-docker-zookeeper/issues/16
