### ISSUE TITLE
[bitnami/redis-cluster] Redis Cluster Pods Stuck in Setting Redis config file and keep CrashLoopBack

### ISSUE THREAD

**Issue by irefaat** [bitnami/charts#14079]
### Name and Version

bitnami/redis-cluster 7.0.7-debian-11-r0

### What steps will reproduce the bug?

`helm install  redis -f values.yaml ./redis-cluster --namespace "redis"`

### Are you using any custom parameters or values?

[redis_values.yaml.txt](https://github.com/bitnami/charts/files/10289288/redis_values.yaml.txt)

### What is the expected behavior?

Cluster to successfully start up without error.

### What do you see instead?

1. 6 _PersistentVolumeClaims_ created and Bound Successfully
2. A _StatefulSet_ is created with 6 Pods created as well and Running but always CrashLoopBack with **following Logs** on every Pod due to "Readiness probe failed: Could not connect to Redis at localhost:6379: Connection refused".

```
redis-cluster 17:23:25.23
redis-cluster 17:23:25.23 Welcome to the Bitnami redis-cluster container
redis-cluster 17:23:25.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 17:23:25.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 17:23:25.23
redis-cluster 17:23:25.23 INFO ==> ** Starting Redis setup **
redis-cluster 17:23:25.53 INFO ==> Initializing Redis
redis-cluster 17:23:25.72 INFO ==> Setting Redis config file
```
### Additional information

We Run the Helm on OpenShift Cluster with Kubernetes version v1.24.6+5157800

And This is the Storage Class that the 6 Cluster's PVC created successfully based on:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: thin
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by carrodher** [comment]
Could you set the `image.debug` parameter to true (see [params doc](https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster#redis-cluster-common-parameters)) in order to increase the verbosity of the container logs? Just in case there is more info about the point where it is stuck

**Comment by irefaat** [comment]
> Could you set the `image.debug` parameter to true (see [params doc](https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster#redis-cluster-common-parameters)) in order to increase the verbosity of the container logs? Just in case there is more info about the point where it is stuck

I have set the `image.debug` parameter to `true` and the below it he First Run Log:


COPYING FILE
redis-cluster 19:14:49.46
redis-cluster 19:14:49.46 Welcome to the Bitnami redis-cluster container
redis-cluster 19:14:49.46 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 19:14:49.46 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 19:14:49.46
redis-cluster 19:14:49.46 INFO ==> ** Starting Redis setup **
redis-cluster 19:14:49.66 INFO ==> Initializing Redis
redis-cluster 19:14:49.76 INFO ==> Setting Redis config file



The below is the Logs after the first Crash Restart:

redis-cluster 19:17:39.36
redis-cluster 19:17:39.36 Welcome to the Bitnami redis-cluster container
redis-cluster 19:17:39.36 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 19:17:39.46 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 19:17:39.46
redis-cluster 19:17:39.46 INFO ==> ** Starting Redis setup **
redis-cluster 19:17:39.66 INFO ==> Initializing Redis
redis-cluster 19:17:39.76 INFO ==> Setting Redis config file


I can't see more Info except "COPYING FILE".

**Comment by Mauraza** [comment]
Hi @irefaat,

Could you tell us what appears if you do a `kubectl describe` from one of the pods that are failing?

**Comment by irefaat** [comment]
Hello @Mauraza ,

I'm able to describe a Pod, please find the result below:


`[devops@vsrisdmnhlp02 ~]$ kubectl describe pod redis-cluster-4
Name:         redis-cluster-4
Namespace:    caching-system-cluster
Priority:     0
Node:         ocp-prod-main-tqk5q-worker-2flpc/10.10.16.113
Start Time:   Sun, 25 Dec 2022 12:43:32 +0200
Labels:       app.kubernetes.io/instance=redis
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=redis-cluster
              controller-revision-hash=onebank-redis-cluster-67bfd7bb8c
              helm.sh/chart=redis-cluster-8.3.3
              statefulset.kubernetes.io/pod-name=onebank-redis-cluster-4
Annotations:  checksum/config: c733dc685667b833646fb4419562b7110e9fa677641efba6620e55c82b3e2cd6
              checksum/scripts: 7e1fa7b9ab3ddc1470cb4ab0d35492b40fd226aca69469ac90ac9e0c9fc60732
              checksum/secret: 965a878eab0b20dfe2de72f4209575fcde701ec9fb3976c684029468dd1c70d3
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.128.4.97"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.128.4.97"
                    ],
                    "default": true,
                    "dns": {}
                }]
              kubernetes.io/limit-ranger:
                LimitRanger plugin set: cpu, ephemeral-storage, memory request for container onebank-redis-cluster; cpu, ephemeral-storage, memory limit f...
              openshift.io/scc: anyuid
Status:       Running
IP:           10.128.4.97
IPs:
  IP:           10.128.4.97
Controlled By:  StatefulSet/onebank-redis-cluster
Containers:
  onebank-redis-cluster:
    Container ID:  cri-o://27e87a67381274c09a1baac26a422a75825a1b3b98399d19d3fccc0cb15ee90f
    Image:         docker.io/bitnami/redis-cluster:7.0.7-debian-11-r0
    Image ID:      docker.io/bitnami/redis-cluster@sha256:58c8bb1fb20c27125ba02473c36c81c203258c751dff3868c221e14d92b3eaff
    Ports:         6379/TCP, 16379/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
    Args:
      # Backwards compatibility change
      if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
          echo COPYING FILE
          cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
      fi
      pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
      pod_index="${pod_index[-1]}"
      if [[ "$pod_index" == "0" ]]; then
        export REDIS_CLUSTER_CREATOR="yes"
        export REDIS_CLUSTER_REPLICAS="1"
      fi
      /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh

    State:          Running
      Started:      Thu, 29 Dec 2022 15:12:45 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 29 Dec 2022 15:11:19 +0200
      Finished:     Thu, 29 Dec 2022 15:12:43 +0200
    Ready:          False
    Restart Count:  1491
    Limits:
      cpu:                100m
      ephemeral-storage:  2Gi
      memory:             100Mi
    Requests:
      cpu:                30m
      ephemeral-storage:  1Gi
      memory:             30Mi
    Liveness:             exec [sh -c /scripts/ping_liveness_local.sh 5] delay=30s timeout=6s period=5s #success=1 #failure=5
    Readiness:            exec [sh -c /scripts/ping_readiness_local.sh 1] delay=60s timeout=2s period=5s #success=1 #failure=5
    Environment:
      POD_NAME:           onebank-redis-cluster-4 (v1:metadata.name)
      REDIS_NODES:        onebank-redis-cluster-0.onebank-redis-cluster-headless onebank-redis-cluster-1.onebank-redis-cluster-headless onebank-redis-cluster-2.onebank-redis-cluster-headless onebank-redis-cluster-3.onebank-redis-cluster-headless onebank-redis-cluster-4.onebank-redis-cluster-headless onebank-redis-cluster-5.onebank-redis-cluster-headless
      REDISCLI_AUTH:      <set to the key 'redis-password' in secret 'onebank-redis-cluster'>  Optional: false
      REDIS_PASSWORD:     <set to the key 'redis-password' in secret 'onebank-redis-cluster'>  Optional: false
      REDIS_AOF_ENABLED:  yes
      REDIS_TLS_ENABLED:  no
      REDIS_PORT_NUMBER:  6379
    Mounts:
      /bitnami/redis/data from redis-data (rw)
      /opt/bitnami/redis/etc/ from redis-tmp-conf (rw)
      /opt/bitnami/redis/etc/redis-default.conf from default-config (rw,path="redis-default.conf")
      /scripts from scripts (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  redis-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redis-data-onebank-redis-cluster-4
    ReadOnly:   false
  scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      onebank-redis-cluster-scripts
    Optional:  false
  default-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      onebank-redis-cluster-default
    Optional:  false
  redis-tmp-conf:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                       From     Message
  ----     ------     ----                      ----     -------
  Normal   Created    50m (x1479 over 4d2h)     kubelet  Created container onebank-redis-cluster
  Warning  Unhealthy  10m (x7429 over 4d2h)     kubelet  Liveness probe failed: Could not connect to Redis at localhost:6379: Connection refused
  Warning  BackOff    5m19s (x18694 over 4d2h)  kubelet  Back-off restarting failed container
  Warning  Unhealthy  18s (x7425 over 4d2h)     kubelet  Readiness probe failed: Could not connect to Redis at localhost:6379: Connection refused
`

**Comment by Tieantono** [comment]
I have the same issue on AKS, with `storageClass` is set to `azurefile-csi` and the `readinessProbe.timeoutSeconds` is set to `30` seconds.

Chart version is `8.3.3` while the Redis version is `7.0.7`.

**Comment by Mauraza** [comment]
Hi @irefaat and @Tieantono, 

Cloud you try to deploy Redis without persistence to check if the same error appears? To check if the error is related to the storageClass or not.

**Comment by irefaat** [comment]
Hello @Mauraza 

Thanks a lot for your support

We changed the `persistence.enabled` to `false` in values.yaml so no PVC created.

Unfortunately, we have the same error:

```


Name:         co-redis-cluster-4
Namespace:    caching-system-cluster
Priority:     0
Node:         ocp-prod-main-tqk5q-worker-6fshb/10.10.16.112
Start Time:   Wed, 11 Jan 2023 14:45:03 +0200
Labels:       app.kubernetes.io/instance=co
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=redis-cluster
              controller-revision-hash=co-redis-cluster-f56cbf5db
              helm.sh/chart=redis-cluster-8.3.3
              statefulset.kubernetes.io/pod-name=co-redis-cluster-4
Annotations:  checksum/config: c733dc685667b833646fb4419562b7110e9fa677641efba6620e55c82b3e2cd6
              checksum/scripts: 7e1fa7b9ab3ddc1470cb4ab0d35492b40fd226aca69469ac90ac9e0c9fc60732
              checksum/secret: 800abbeabdd14a75e9ee0dd5eb392c0ced415ec45867457ebe7acb7b4efbb0fd
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.129.2.40"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.129.2.40"
                    ],
                    "default": true,
                    "dns": {}
                }]
              kubernetes.io/limit-ranger:
                LimitRanger plugin set: cpu, ephemeral-storage, memory request for container co-redis-cluster; cpu, ephemeral-storage, memory limit f...
              openshift.io/scc: anyuid
Status:       Running
IP:           10.129.2.40
IPs:
  IP:           10.129.2.40
Controlled By:  StatefulSet/co-redis-cluster
Containers:
  co-redis-cluster:
    Container ID:  cri-o://ef8f50ab045ff37bbf4d9d5b499354d794ef147dc2f0675cfdbb7cb48c69ac54
    Image:         docker.io/bitnami/redis-cluster:7.0.7-debian-11-r0
    Image ID:      docker.io/bitnami/redis-cluster@sha256:58c8bb1fb20c27125ba02473c36c81c203258c751dff3868c221e14d92b3eaff
    Ports:         6379/TCP, 16379/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
    Args:
      # Backwards compatibility change
      if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
          echo COPYING FILE
          cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
      fi
      pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
      pod_index="${pod_index[-1]}"
      if [[ "$pod_index" == "0" ]]; then
        export REDIS_CLUSTER_CREATOR="yes"
        export REDIS_CLUSTER_REPLICAS="1"
      fi
      /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh

    State:          Running
      Started:      Wed, 11 Jan 2023 14:47:57 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 11 Jan 2023 14:46:32 +0200
      Finished:     Wed, 11 Jan 2023 14:47:54 +0200
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:                100m
      ephemeral-storage:  2Gi
      memory:             100Mi
    Requests:
      cpu:                30m
      ephemeral-storage:  1Gi
      memory:             30Mi
    Liveness:             exec [sh -c /scripts/ping_liveness_local.sh 5] delay=30s timeout=6s period=5s #success=1 #failure=5
    Readiness:            exec [sh -c /scripts/ping_readiness_local.sh 1] delay=60s timeout=2s period=5s #success=1 #failure=5
    Environment:
      POD_NAME:           co-redis-cluster-4 (v1:metadata.name)
      REDIS_NODES:        co-redis-cluster-0.co-redis-cluster-headless co-redis-cluster-1.co-redis-cluster-headless co-redis-cluster-2.co-redis-cluster-headless co-redis-cluster-3.co-redis-cluster-headless co-redis-cluster-4.co-redis-cluster-headless co-redis-cluster-5.co-redis-cluster-headless
      REDISCLI_AUTH:      <set to the key 'redis-password' in secret 'co-redis-cluster'>  Optional: false
      REDIS_PASSWORD:     <set to the key 'redis-password' in secret 'co-redis-cluster'>  Optional: false
      REDIS_AOF_ENABLED:  yes
      REDIS_TLS_ENABLED:  no
      REDIS_PORT_NUMBER:  6379
    Mounts:
      /bitnami/redis/data from redis-data (rw)
      /opt/bitnami/redis/etc/ from redis-tmp-conf (rw)
      /opt/bitnami/redis/etc/redis-default.conf from default-config (rw,path="redis-default.conf")
      /scripts from scripts (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      co-redis-cluster-scripts
    Optional:  false
  default-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      co-redis-cluster-default
    Optional:  false
  redis-tmp-conf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  redis-data:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   Scheduled       3m5s                  default-scheduler  Successfully assigned caching-system-cluster/co-redis-cluster-4 to ocp-prod-main-tqk5q-worker-6fshb by ocp-prod-main-tqk5q-master-2
  Normal   AddedInterface  3m4s                  multus             Add eth0 [10.129.2.40/23] from openshift-sdn
  Normal   Pulled          100s (x2 over 3m4s)   kubelet            Container image "docker.io/bitnami/redis-cluster:7.0.7-debian-11-r0" already present on machine
  Normal   Created         97s (x2 over 3m1s)    kubelet            Created container co-redis-cluster
  Normal   Started         97s (x2 over 3m1s)    kubelet            Started container co-redis-cluster
  Warning  Unhealthy       45s (x10 over 2m30s)  kubelet            Liveness probe failed: Could not connect to Redis at localhost:6379: Connection refused
  Normal   Killing         45s (x2 over 2m10s)   kubelet            Container co-redis-cluster failed liveness probe, will be restarted
  Warning  Unhealthy       30s (x7 over 2m)      kubelet            Readiness probe failed: Could not connect to Redis at localhost:6379: Connection refused


```

**Comment by Mauraza** [comment]
Hi @irefaat,

I wasn't able to reproduce it. Could you try to increase the `initialDelaySeconds` of readiness?
```yaml
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30 
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
```

**Comment by alexandre-imaginacom** [comment]
For anyone googling, I just had the same error, and found the solution.
The problem was that I didn't had enough ready replicas active, however that error was not made clear.

redis-cluster *only accepts connection* once there are *at least* 3 pods ready.
Otherwise, "readinessProbe" will fail to connect and restart the pod every 30 seconds.

The console will get stucked at "redis-cluster 14:03:33.50 INFO ==> Setting Redis config file", until readinessProbe fails *OR* until there are total of 3 replicas of redis-cluster ready, so all of them will start at the exactly same time.

Interstingly enough, after they are ready, you can scale down to just one replica, and that pod will still work.
However, if you increase another replica, the second one WILL NOT start, until you add the third one.

So, in details:
- First node: freezes at "Setting Redis config file" and restarts every 30s.
- Second node: freezes at "Setting Redis config file" and restarts every 30s.
- Third node: loads correctly and unfreeze everybody else.
*Scale down to the first node*
- First node: still works
*Add second node*
- First node: still works
- Second node: freezes at "Setting Redis config file" and restarts every 30s.
- Third node: loads correctly and unfreeze second node.

I think the big problem here is  that the console shows "Setting redis config file" instead of "Waiting for at least 3 nodes to be available".

**Comment by barbu110** [comment]
Hi, this is still happening on Minikube runnign in a Podman machine on macOS Ventura (Apple Silicon). Is there any suggested resolution? 

I found it to be working to delete the Podman machine, but that's not something I wish to be doing every day.

**Comment by mandrean** [comment]
Also seeing the issue (Linux, `kind` cluster)

**Comment by wenchao5211** [comment]
I have the same issue on k3s  v1.25.12+k3s-724616dd & increase the time of readinessProbe, but failed

redis version: redis-cluster:7.0.12-debian-11-r2

helm version: 8.6.9

```
redis-cluster 03:30:35.67 
2024-02-29T11:30:35.674052358+08:00 redis-cluster 03:30:35.67 Welcome to the Bitnami redis-cluster container
redis-cluster 03:30:35.67 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 03:30:35.67 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 03:30:35.68 
redis-cluster 03:30:35.68 INFO  ==> ** Starting Redis setup **
2024-02-29T11:30:35.720940509+08:00 redis-cluster 03:30:35.72 DEBUG ==> Validating settings in REDIS_* env vars..
redis-cluster 03:30:35.72 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis-cluster 03:30:35.72 INFO  ==> Initializing Redis
redis-cluster 03:30:35.73 DEBUG ==> Ensuring expected directories/files exist
redis-cluster 03:30:35.75 INFO  ==> Setting Redis config file
```

**Comment by wenchao5211** [comment]
reopen

**Comment by javsalgar** [comment]
Hi!

Could you launch the chart with image.debug=true?

**Comment by wenchao5211** [comment]
i set it. 'image.debug=true' 
i solved it
in k8s reason： nodes num = replicas, This is a must
I recommend providing more detailed information during the startup process

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing to improving the documentation, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
