### ISSUE TITLE
[bitnami/mongodb] Failure when trying to install VIM using "install_packages"

### ISSUE THREAD

**Issue by wasiucionek** [bitnami/charts#14077]
### Name and Version

bitnami/mongodb:13.6.1

### What steps will reproduce the bug?

1. Deploy MongoDB using Helm Chart of version 13.6.1 in the diagnostic mode
2. SSH into the main container as a root user
3. Try to install VIM using "install_packages"

### Are you using any custom parameters or values?

```yaml
diagnosticMode:
  enabled: true
containerSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
```

### What is the expected behavior?

VIM package installed. 

### What do you see instead?

```
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
```

### Additional information

It is not possible to install VIM using install_packages on the MongoDB container deployed with Bitnami MongoDB Helm Chart version 13.6.1. 

For debugging purposes I wanted to enable:
```
set -o xtrace # Uncomment this line for debugging purposes
```
in the:
```
/opt/bitnami/scripts/mongodb/entrypoint.sh
```

When using `whoami` command, I can see that I am a root user:
```console
$ whoami
root
```
but I cannot debug the issue without the text editor. 

When looking for the logs without trace enabled, the only thing that I can see is: 
```
│ mongodb 16:22:36.23                                                                                                                                                                                     │
│ mongodb 16:22:36.23 Welcome to the Bitnami mongodb container                                                                                                                                            │
│ mongodb 16:22:36.24 Subscribe to project updates by watching https://github.com/bitnami/containers                                                                                                      │
│ mongodb 16:22:36.24 Submit issues and feature requests at https://github.com/bitnami/containers/issues                                                                                                  │
│ mongodb 16:22:36.24                                                                                                                                                                                     │
│ mongodb 16:22:36.24 INFO  ==> ** Starting MongoDB setup **                                                                                                                                              │
│ mongodb 16:22:36.26 INFO  ==> Validating settings in MONGODB_* env vars...    
```

And when trying to start MongoDB manually
`./opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh`
I can only see: 
```
about to fork child process, waiting until server is ready for connections.
forked process: 401
ERROR: child process failed, exited with error number 48
To see additional information in this output, start without the “–fork” option.
```

It is hard to proceed with debugging process without VIM or Nano installed on a pod to remove --fork flag and enable trace.

**Comment by OneCricketeer** [comment]
> remove --fork flag and enable trace.

Have you tried mounting a file over the existing ones rather than trying to exec into the container to edit them?

**Comment by wasiucionek** [comment]
@OneCricketeer, I tried mounting a new file by using:
`  extraVolumeMounts:
    - name: script
      mountPath: /opt/bitnami/scripts/mongodb/
  extraVolumes:
    - name: script
      configMap:
        name: entrypoint-script
`
and a ConfigMap with the needed changes, so
` set -o xtrace`
but when trying to start MongoDB I was getting
`container_linux.go:290: starting container process caused "exec: \"/opt/bitnami/scripts/mongodb/entrypoint.sh\": permission denied"`

I cannot chmod it easily, because of read-only file system.

**Comment by Mauraza** [comment]
Hi @wasiucionek,

Could you try version 13.7.1 of the chart? I just installed with your values and try to install vim and everything went well.

**Comment by OneCricketeer** [comment]
Mounting a file as text won't make it executable. You'd need to create a shell script, chmod it locally, then place it in the container. If your kubelet host has a read only filesystem, that seems problematic since you wouldn't easily get logs or local storage

**Comment by OneCricketeer** [comment]
My main question is - how will a text editor help? You'd need to stop the Mongo process, then edit the script, right? In the meantime, kubernetes is running a health/liveness probe and will kill/restart the pod

**Comment by Mauraza** [comment]
You can use `image.debug` to see extra information on logs

**Comment by wasiucionek** [comment]
@OneCricketeer Yes, you are right about the filesystem and the logs. As I am debugging it in diagnostic mode, I do not care that much about the liveness and readiness probes for now - it is possible for me to restart the process without killing the pod.

@Mauraza thank you, I will verify it after the New Year's Eve and post the output here.

**Comment by wasiucionek** [comment]
@Mauraza did you mean 13.6.2 or 13.7.1? I will test it tomorrow.

**Comment by Mauraza** [comment]
@wasiucionek the 13.7.1.

**Comment by wasiucionek** [comment]
Thank you, this issue can be closed.
