### ISSUE TITLE
Can't reach Wordpress behind NGINX Ingress Controller

### ISSUE THREAD

**Issue by tobys-playground** [bitnami/charts#14095]

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami WordPress container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
