### ISSUE TITLE
Cannot change the default password for Postgres deployment

### ISSUE THREAD

**Issue by pavelzag** [bitnami/charts#14107]
### Name and Version

bitnami/postgres15.1

### What steps will reproduce the bug?

1. Trying to deploy Postgres on a Kubernetes cluster with a password taken from the values.yaml file
2. The command is: `helm install postgresql-pavelzag -f /tmp/values.yaml bitnami/postgresql --namespace server-pavelzag --set volumePermissions.enabled=true --set image.tag=14`
3. The deployment starts with the default password instead
4. I am able to log into the db with "mysecretpassword" default password but not with "somepassword".
5. The log shows:
 ```
FATAL:  password authentication failed for user "myuser"
DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```                  

### Are you using any custom parameters or values?

`--set volumePermissions.enabled=true --set image.tag=14`

values.yaml:
```yaml
auth:
  enablePostgresUser: true
  postgresPassword: "somepassword"
  username: "myuser"
  password: "somepassword"
  database: "my-db"
```
### What is the expected behavior?

I want to be able to log into the DB with the provided password

### What do you see instead?

The log shows:
```
FATAL:  password authentication failed for user "myuser"
DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

**Comment by carrodher** [comment]
If you are reusing the name and namespace used in a previous deployment, please note Helm is not removing the PV/PVCs between different deployments so the password stored in the PVC is the one set during the first deployment. Could you try by using a different name/namespace or deleting the PV/PVC?

**Comment by pavelzag** [comment]
Hi Carlos, thanks for the reply!
I use a new namespaces/PV/PVC for each deployment.

**Comment by fmulero** [comment]
Hi @pavelzag 

What do you mean with the default password "mysecretpassword" ? By default the chart will generate a random password, not that one. Are you using any secret with that password? Please note that the password stored in that secret takes precedence. You can check it running:
```console
$ kubectl get secret --namespace server-pavelzag postgresql-pavelzag -o jsonpath="{.data.postgres-password}" | base64 -d
```
