### ISSUE TITLE
[bitnami/rabbitmq] v10.3.9 Chart version issue

### ISSUE THREAD

**Issue by guy-microsoft** [bitnami/charts#14102]
### Name and Version

bitnami/rabbitmq 10.3.9

### What steps will reproduce the bug?

I used to use version 8.24.13 of the chart using this command for setting custom erlang cookie and app password:
```
helm upgrade --install guy --kubeconfig=aksConnectionConfig --version 8.24.13 --set auth.username=app,auth.password={MY_PASSWORD},auth.erlangCookie={MY_COOKIE}
```
I found out that this version of the chart doesn't exist anymore, and I tried to use the same command with chart version 10.3.9 (according to changelog, the changes are not relevant for my uses), but I get the following error:

```
Error: UPGRADE FAILED: template: rabbitmq/templates/statefulset.yaml:37:28: executing "rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: rabbitmq/templates/secrets.yaml:17:24: executing "rabbitmq/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "rabbitmq-password" "length" 16 "providedValues" (list "auth.password") "context" $)>: error calling include: template: rabbitmq/charts/common/templates/_secrets.tpl:98:103: executing "common.secrets.passwords.manage" at <fail>: error calling fail: 
PASSWORDS ERROR: The secret "guy-rabbitmq-ha" does not contain the key "rabbitmq-password"
```

How can it be solved?

### What do you see instead?

```
Error: UPGRADE FAILED: template: rabbitmq/templates/statefulset.yaml:37:28: executing "rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: rabbitmq/templates/secrets.yaml:17:24: executing "rabbitmq/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "rabbitmq-password" "length" 16 "providedValues" (list "auth.password") "context" $)>: error calling include: template: rabbitmq/charts/common/templates/_secrets.tpl:98:103: executing "common.secrets.passwords.manage" at <fail>: error calling fail: 
PASSWORDS ERROR: The secret "guy-rabbitmq-ha" does not contain the key "rabbitmq-password"
```

**Comment by aoterolorenzo** [comment]
Hi @guy-microsoft. Unfortunately I've been unable to reproduce the issue with the last chart version, so till I could see, seems to work properly:

The example steps I follow:

```
$> helm install rabbitmq bitnami/rabbitmq
$> helm upgrade rabbitmq . --set auth.username=app --set auth.password=abc123w.. --set auth.erlangCookie=9132973912731
```

I can't see any error or issue after that. Are you setting `guy-rabbitmq-ha` or `.Values.auth.existingPasswordSecret` in any way possible?

In case you want to get back to your prefered version, you can:

```
$> git clone https://github.com/bitnami/charts.git
$> git checkout d1680a524f65c0194fec188c77eb35a9cec0cd4b
```

Where commit `d1680a524f65c0194fec188c77eb35a9cec0cd4b` is the [8.24.13 Release commit](https://github.com/bitnami/charts/commit/d1680a524f65c0194fec188c77eb35a9cec0cd4b)

**Comment by zetaab** [comment]
@guy-microsoft how did you solve this issue? We are hitting same issue. Currently we have 8.20.x chart and trying to update to 10. 

```
% helm upgrade rabbit-prod bitnami/rabbitmq --values=values.yaml --set auth.erlangCookie=$ERLANG_COOKIE --set auth.password=$AUTHPW --version 10.3.9
Error: UPGRADE FAILED: execution error at (rabbitmq/templates/statefulset.yaml:37:28):
PASSWORDS ERROR: The secret "rabbit-prod-rabbitmq" does not contain the key "rabbitmq-password"
```

**Comment by zetaab** [comment]
I added that password manually to secret and it started to work

**Comment by guy-microsoft** [comment]
@zetaab I didn't, we had to uninstall and install the newer version.

**Comment by fmulero** [comment]
I think the issue could come from this change https://github.com/bitnami/charts/pull/9638 I think versions older than 8.31.0 didn't require the key `rabbitmq-password` in the rabbitmq secret.

Could you patch the secret, adding a key with your rabbitmq password? Something like this should work:
```console
password=<your rabbitmq password>
kubectl patch secret <your rabbitmq secret> -p="{\"data\":{\"rabbitmq-password\": \"$(echo $password | base64)\"}}"
```
