### ISSUE TITLE
[bitnami-redis-cluster] Deploy new cluster from .rdb backup files

### ISSUE THREAD

**Issue by liad-haber** [bitnami/charts#14108]
### Name and Version

bitnami/redis-cluster:8.3.3

### What steps will reproduce the bug?

Not really a bug more of a clarification, Could not find related documentation. 
We have a Redis cluster of 16 nodes(8 masters, 8 replicas) and have created 8 .rdb backup files and uploaded them to s3. 
I wrote an init container that downloads the backups and places them at each of the corresponding hosts according to their redis slots.(E.G 20221225_0-2047.rdb).

Once the nodes are done loading the data into the memory they break their cluster formation and each node is in its own "standalone cluster". 

### Are you using any custom parameters or values?
```yaml
redis configmap - 
          save ""
          save "86400 1"
          maxmemory 439804651110
          maxmemory-policy volatile-lru
          appendonly no
          maxclients 20000
          slave-serve-stale-data yes
          slave-read-only yes
          dbfilename snapshot.rdb
          dir /bitnami/redis/data
          client-output-buffer-limit slave 536870912000 536870912000 0
          repl-timeout 72000
          io-threads 8
          io-threads-do-reads yes
          repl-backlog-size 204800
```
### What is the expected behavior?

New redis cluster with "old" cluster data.

### What do you see instead?

Broken 16 standalone clusters.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Redis cluster container image or Helm chart but about how the application or environment is being used/configured.
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by bamaas** [comment]
@liad-haber  Have you ever found a solution for this?

**Comment by Ilan-StartIO** [comment]
@bamaas the solution we found was starting the cluster without data, this way the do start as a cluster.
downloading the .rdb files (according to the slots) from the backup and swapping them with the empty ones and finally restarting the nods.
When the nodes restart they load the .rdb files with the backup data.
The process does take time, depending on the amount of data your files have.
