### ISSUE TITLE
Can MySQL automatically switch between master and slave

### ISSUE THREAD

**Issue by sfeng1996** [bitnami/charts#14101]
### Name and Version

bitaami/mysql

### What is the problem this feature will solve?

Can MySQL automatically switch between master and slave? For example, can slave switch to master automatically when the master is down

### What is the feature you are proposing to solve the problem?

none

**Comment by Mauraza** [comment]
Hi @sfeng1996, if you want that property, I recommend you to use bitnami/mariadb-galera

**Comment by sfeng1996** [comment]
> Hi @sfeng1996, if you want that property, I recommend you to use bitnami/mariadb-galera

ok，i will try it，thks

**Comment by Mauraza** [comment]
I going to close this issue. 
If you have another question, please open a new issue.
