### ISSUE TITLE
Unable to use Bitnami/externalDNS in Docker for Desktop

### ISSUE THREAD

**Issue by VenkateshSrini** [bitnami/charts#14115]
### Name and Version

bitname/external-dns 6.12.2

### What steps will reproduce the bug?

1. Environment:- Docker for Desktop (Kubernetes version v1.25.2)

2. Installed bitname/external-dns using the instruction given [at](https://artifacthub.io/packages/helm/bitnami/external-dns#:~:text=2%20%C2%B7%20bitnami%2Fbitnami&text=ExternalDNS%20is%20a%20Kubernetes%20addon,services%20to%20make%20them%20discoverable.&text=Here%20you'll%20be%20able,using%20this%20package%20in%20production.)

3. The charts gets installed in default namespace.
4. Then used the attached service.yaml ([file-grpc-service.yaml](https://github.com/bitnami/charts/files/10311825/file-grpc-service.yaml.txt)) file.
5. When running nslookup it is failing

### Are you using any custom parameters or values?

No

### What is the expected behavior?

nslookup should succeed

### What do you see instead?

nslookup fails

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami external DNS container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by VenkateshSrini** [comment]
@carrodher , 
As you can see my service is just deploying a simple application. Can you please provide me some insights on what is wrong with the application.  After setting up the external-dns the nslookup fails. If you need additional details to help, I will be happier to share the same.
