### ISSUE TITLE
[bitnami/harbor] - jobservice is missing pvc and volume definitions for scandata_exports

### ISSUE THREAD

**Issue by rajan123456** [bitnami/charts#14113]
### Name and Version

bitnami/harbor 16.1.2

### What steps will reproduce the bug?

1. Install the bitnami/harbor chart
2. Login to admin console -> Create new project -> Create new repository -> Push an image -> Scan the image using trivy
3. Navigate to project -> Select project -> Action -> Export CVE
4. Wait for job to fail
5. Check logs of jobservice, which show /var/scandata_exports not found

### What is the expected behavior?

/var/scandata_exports should be mounted as a pvc on the jobservice pod in order to allow CVE reports to be saved and exported from the UI

### What do you see instead?

Export CVE jobs fail

### Additional information

https://github.com/goharbor/harbor-helm/blob/master/templates/jobservice/jobservice-dpl.yaml#L110

**Comment by rajan123456** [comment]
Please let me know if you would like me to work on the fix for this issue. Thanks!

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by rajan123456** [comment]
Hi - I have raised a PR for fixing this issue. Please let me know if any feedback.

**Comment by carrodher** [comment]
Thanks the team will review it and provide feedback although it can take longer than usual due to the Christmas holidays period

**Comment by rajan123456** [comment]
Hi @carrodher - any updates on this please?

**Comment by javsalgar** [comment]
The team will take a look. There was a vacation period and therefore our support/code review was limited.

**Comment by rajan123456** [comment]
Thanks @javsalgar , I have merged the code again. Any chance for it to be reviewed soon?
