### ISSUE TITLE
[bitnami/clickhouse] It's not possible to create additional users

### ISSUE THREAD

**Issue by marcessodelux** [bitnami/charts#14120]
### Name and Version

bitnami/clickhouse 2.1.1

### What steps will reproduce the bug?

1. Install chart
2. Get shell in one of the containers and login with `default` user and password
3. Attempt to create a new user: `CREATE USER test1 IDENTIFIED WITH plaintext_password BY 'qwerty';`

### Are you using any custom parameters or values?

auth.password

### What is the expected behavior?

User is correctly created

### What do you see instead?

```
I have no name!@clickhouse-shard0-0:/$ clickhouse-client --password password
ClickHouse client version 22.12.1.1752 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.12.1 revision 54461.

clickhouse-shard0-0.clickhouse-headless.common.svc.cluster.local :) CREATE USER test1 IDENTIFIED WITH plaintext_password BY 'qwerty';

CREATE USER test1 IDENTIFIED WITH plaintext_password BY 'qwerty'

Query id: ed5b8a24-cd5d-49ea-bea2-78f2f551db6c


0 rows in set. Elapsed: 0.046 sec. 

Received exception from server (version 22.12.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE USER ON *.*. (ACCESS_DENIED)
```

### Additional information

Tried to pass 

```
CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
```

But I get same result

**Comment by Archonr** [comment]
I find is not the best but workable solution:
Try to use extraOverrides param, where insert your additional user configuration.

**Comment by CeliaGMqrz** [comment]
Hi @marcessodelux, 
Thanks for your patience, after the Christmas vacations the response has been delayed, sorry.
I have reproduced the issue. It seems that upstream has also opened this [issue](https://github.com/ClickHouse/ClickHouse/issues/13057). We will leave this issue on hold until the upstream provides a solution.

**Comment by marcessodelux** [comment]
Hello @CeliaGMqrz , why this has been closed?
The issue in the upstream suggests the solution: `default_access_management` should be set to 1.

Also suggested here https://hub.docker.com/r/clickhouse/clickhouse-server/ with env variable `CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT`

It seems chart should support ability to inject such env variable

**Comment by CeliaGMqrz** [comment]
Hi @marcessodelux, 

Sorry but this is not a bug, as the [upstream](https://clickhouse.com/docs/en/operations/access-rights/#enabling-access-control) says, is expected because this feature is disabled by default:

> Enable SQL-driven access control and account management for at least one user account. By default, SQL-driven access control and account management is disabled for all users. You need to configure at least one user in the users.xml configuration file and set the value of the access_management setting to 1.

You can edit the file `/etc/clickhouse-server/users.xml`  and uncomment this line:
```.xml
            <!-- User can create other users and grant rights to them. -->
            <!-- <access_management>1</access_management> -->
```
You can also provide your additional user configuration in the extraOverrides param as @Archonr says.
```
## @param extraOverrides Extra configuration overrides (evaluated as a template) apart from the default
##
extraOverrides: ""

## @param extraOverridesConfigmap The name of an existing ConfigMap with extra configuration for ClickHouse
##
extraOverridesConfigmap: ""
```
What you propose looks good to me but it is a new feature. Would you like to contribute by creating a PR? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Guillem-Borrell** [comment]
Just in case someone stumbles upon this question, to let the `default` user create additional accounts add the following to the `extraOverrides` key:

```
extraOverrides: |
  <clickhouse>
    <users>
      <default>
        <access_management>1</access_management>
      </default>
    </users>
  </clickhouse>
```

**Comment by KevinLiangX** [comment]
@Guillem-Borrell  hello sir ,  
extraOverrides: |
  <clickhouse>
    <users>
      <default>
        <access_management>1</access_management>
      </default>
    </users>
  </clickhouse>

this configuration updated in the conf.d directory, right ?  i used the config ,but also can't create the new user , no privlliedge.

clickhouse-shard0-0.clickhouse-headless.default.svc.cluster.local :) GRANT ALL ON *.* TO 'newuser';

GRANT ALL ON *.* TO newuser

Query id: a6428f9c-326a-48f5-a116-a68aac48e8e9


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 23.3.2):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, NAMED COLLECTION CONTROL, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.* WITH GRANT OPTION. (ACCESS_DENIED)

clickhouse-shard0-0.clickhouse-headless.default.svc.cluster.local :)

info as below:

I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ ls
00_default_overrides.xml  01_extra_overrides.xml
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ cat 01_extra_overrides.xml 
<clickhouse>
  <users>
    <default>
      <access_management>1</access_management>
      <named_collection_control>1</named_collection_control>
    </default>
  </users>
</clickhouse>
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ pwd
/etc/clickhouse-server/conf.d
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ ll /bitnami/clickhouse/
data/ etc/  
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ ll /bitnami/clickhouse/
data/ etc/  
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ ll /bitnami/clickhouse/etc/conf.d/
bash: ll: command not found
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ ls /bitnami/clickhouse/etc/conf.d/
default  extra-configmap
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ ls /bitnami/clickhouse/etc/conf.d/extra-configmap/
01_extra_overrides.xml
I have no name!@clickhouse-shard0-0:/etc/clickhouse-server/conf.d$ 

is there any other options ,need to set ?

**Comment by WillMeng** [comment]
I got the same issue, CH version 23.3.2.37

**Comment by CeliaGMqrz** [comment]
Hi @marcessodelux, @WillMeng, @KevinLiangX

After the changes in #17110, it is possible to add custom users. If the problem persists, please let us know.

Thanks for your feedback!

**Comment by FedericoCeratto** [comment]
The problem appears to be still unsolved on 23.8.2.7

**Comment by javsalgar** [comment]
Hi,

Could you let us know the steps to reproduce the issue? We performed changes to allow this situation.
