### ISSUE TITLE
create db hung when deploy HA pg

### ISSUE THREAD

**Issue by daixiang0** [bitnami/charts#1414]
**Which chart**:
postgresql-5.3.0
appversion: 11.3.0

**Description**
I use `helm install` with below config:
```
image:
  pullPolicy: IfNotPresent
  debug: true
  repository: bitnami/postgresql
  tag: 9.6.15

replication:
  enabled: true
  slaveReplicas: 2
  synchronousCommit: "on"
  numSynchronousReplicas: 1

postgresqlPassword: xxx

persistence:
  enabled: true
  size: 100Gi

volumePermissions:
  image:
    pullPolicy: IfNotPresent

```

**Steps to reproduce the issue:**

1. helm install
2. `kubectl run pg-client --rm --tty -i --restart='Never' --image bitnami/postgresql:9.6.15 --env="PGPASSWORD=xxx" --labels="pg-client=true" -- bash`
3. connect pg then create database grafana;

The cmd hung, i wait 10 min but no return.

Then i crtl + C:
```
^CCancel request sent
WARNING:  canceling wait for synchronous replication due to user request
DETAIL:  The transaction has already committed locally, but might not have been replicated to the standby.
CREATE DATABASE
```

**Describe the results you expected:**

create successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by juan131** [comment]
Hi @daixiang0 

It seems the issue disappears if you remove the changes introduced at `replication.synchronousCommit` and `replication.numSynchronousReplicas` parameters. 

There must be something wrong in the synchronous commit replication configuration. Thanks for reporting the issue, I will create a task to investigate it properly.

It's probably related with the configuration setting (`synchronous_standby_names`) in PostgreSQL. The line below can provide you more information:

https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/4/debian-9/rootfs/libpostgresql.sh#L384

**Comment by guillaume-harvey** [comment]
Hello, after looking at the source code, I think the mistake is the following:

```
if (( POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS > 0 )); then
        postgresql_set_property "synchronous_commit" "$POSTGRESQL_SYNCHRONOUS_COMMIT_MODE"
        postgresql_set_property "synchronous_standby_names" "${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS} (\"${POSTGRESQL_CLUSTER_APP_NAME}\")"
 fi
```

should be :
```
if (( $POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS > 0 )); then
        postgresql_set_property "synchronous_commit" "$POSTGRESQL_SYNCHRONOUS_COMMIT_MODE"
        postgresql_set_property "synchronous_standby_names" "${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS} (\"${POSTGRESQL_CLUSTER_APP_NAME}\")"
 fi```

**Comment by daixiang0** [comment]
@guillaume-harvey not sure:
```
$ a=1
$ (( a > 0 )) && echo yes
yes
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by daixiang0** [comment]
I maybe find root [reason](url), if already has data, we could not create related users so that sync failed.

**Comment by juan131** [comment]
Hi @guillaume-harvey 

> $/${} is unnecessary on arithmetic variables.

Check https://github.com/koalaman/shellcheck/wiki/SC2004 for more information

@daixiang0 the link to the "reason" you shared seems to be broken. Could you check it?

**Comment by daixiang0** [comment]
I update it

**Comment by juan131** [comment]
Thanks for updating it @daixiang0 

I don't think the problem is related with existing data, I mean, I'm able to reproduce it even if I install the chart from scratch. 

I think we're not configuring the "synchronous commit" configuration correctly, but we need to investigate what's going on.

**Comment by daixiang0** [comment]
The existing data would be one reason i think. Let us work on it.

**Comment by daixiang0** [comment]
@juan131 is there quote issue:
```
diff --git a/10/centos-7/rootfs/libpostgresql.sh b/10/centos-7/rootfs/libpostgresql.sh
index 7bcd0530..a8df3ef1 100644
--- a/10/centos-7/rootfs/libpostgresql.sh
+++ b/10/centos-7/rootfs/libpostgresql.sh
@@ -385,7 +385,7 @@ postgresql_configure_replication_parameters() {
     postgresql_set_property "hot_standby" "on"
     if (( POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS > 0 )); then
         postgresql_set_property "synchronous_commit" "$POSTGRESQL_SYNCHRONOUS_COMMIT_MODE"
-        postgresql_set_property "synchronous_standby_names" "$POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS ($POSTGRESQL_CLUSTER_APP_NAME)"
+        postgresql_set_property "synchronous_standby_names" "${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS} (\"${POSTGRESQL_CLUSTER_APP_NAME}\")"

```
Do not know why need quote here.

**Comment by daixiang0** [comment]
@juan131 the reason is that POSTGRES_NUM_SYNCHRONOUS_REPLICAS in slave does not set, then synchronous_standby_names always empty!
Rrefer to https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/4/debian-9/rootfs/libpostgresql.sh#L383-L385

**Comment by juan131** [comment]
Checking your PR @daixiang0 !

**Comment by daixiang0** [comment]
@juan131 hi, after many test, i confirm that the tag `9.6.15-debian-9-r32` is broken, i test `9.6.15-debian-9-r31` and it works fine, i am looking difference between them.

**Comment by daixiang0** [comment]
```
$ git diff 9.6.15-debian-9-r31 9.6.15-debian-9-r32
...
-    postgresql_set_property "primary_conninfo" "host=$POSTGRESQL_MASTER_HOST port=$POSTGRESQL_MASTER_PORT_NUMBER user=$POSTGRESQL_REPLICATION_USER password=$POSTGRESQL_REPLICATION_PASSWORD application_name=$POSTGRESQL_CLUSTER_APP_NAME" "$POSTGRESQL_RECOVERY_FILE"
-    postgresql_set_property "trigger_file" "/tmp/postgresql.trigger.$POSTGRESQL_MASTER_PORT_NUMBER" "$POSTGRESQL_RECOVERY_FILE"
+    postgresql_set_property "primary_conninfo" "host=${POSTGRESQL_MASTER_HOST} port=${POSTGRESQL_MASTER_PORT_NUMBER} user=${POSTGRESQL_REPLICATION_USER} password=${POSTGRESQL_REPLICATION_PASSWORD} application_name=\"${POSTGRESQL_CLUSTER_APP_NAME}\"" "$POSTGRESQL_RECOVERY_FILE"
+    postgresql_set_property "trigger_file" "/tmp/postgresql.trigger.${POSTGRESQL_MASTER_PORT_NUMBER}" "$POSTGRESQL_RECOVERY_FILE"
...
```
The quota cover POSTGRESQL_CLUSTER_APP_NAME make slaves can not connect to master.
@juan131 i do know where to file a PR, test at local use tag `9.6.15-debian-9-r32` with change of remove quota works, you can test at your env, wait for your feedback!

**Comment by daixiang0** [comment]
also test  `9.6.15-debian-9-r58` which alse named as `9.6.15` with same change, works too!

**Comment by juan131** [comment]
Hi @daixiang0 

Thanks so much for debugging it! I can confirm that removing the escaped double quotes around POSTGRESQL_CLUSTER_APP_NAME fixes the issue:

```diff
-        postgresql_set_property "synchronous_standby_names" "${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS} (\"${POSTGRESQL_CLUSTER_APP_NAME}\")"
+        postgresql_set_property "synchronous_standby_names" "${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS} (${POSTGRESQL_CLUSTER_APP_NAME})"
...
-    postgresql_set_property "primary_conninfo" "host=${POSTGRESQL_MASTER_HOST} port=${POSTGRESQL_MASTER_PORT_NUMBER} user=${POSTGRESQL_REPLICATION_USER} password=${POSTGRESQL_REPLICATION_PASSWORD} application_name=\"${POSTGRESQL_CLUSTER_APP_NAME}\"" "$POSTGRESQL_RECOVERY_FILE"
+    postgresql_set_property "primary_conninfo" "host=${POSTGRESQL_MASTER_HOST} port=${POSTGRESQL_MASTER_PORT_NUMBER} user=${POSTGRESQL_REPLICATION_USER} password=${POSTGRESQL_REPLICATION_PASSWORD} application_name=${POSTGRESQL_CLUSTER_APP_NAME}" "$POSTGRESQL_RECOVERY_FILE"
```

This regression was introduced by me on this commit: https://github.com/bitnami/bitnami-docker-postgresql/commit/f515e738f99d8395fcd294c8602071d7c73658e9 (see PR https://github.com/bitnami/bitnami-docker-postgresql/pull/167)

Since you found the bug, I think it's you the one who should sent the PR fixing it at https://github.com/bitnami/bitnami-docker-postgresql/pulls. I can do it otherwise

**Comment by daixiang0** [comment]
@juan131 hi, i file a PR here.

**Comment by juan131** [comment]
Your PR was merged. Now waiting for containers to be released and chart to be updated. I already triggered the release process

**Comment by juan131** [comment]
@daixiang0 the containers including the fix were released on each branch:

- 11.5.0-r59
- 10.10.0-r60
- 9.6.15-r60

Next step, update the values.yaml in the PostgreSQL chart to use these revisions by default.

**Comment by juan131** [comment]
Hi @daixiang0 

The default image revisions will be updated on this PR: https://github.com/helm/charts/pull/17692
