### ISSUE TITLE
[bitnami/harbor] Allow setting sensitive information in K8S Secrets instead of values.yaml

### ISSUE THREAD

**Issue by Roia5** [bitnami/charts#14150]
### Name and Version

bitnami/harbor

### What is the problem this feature will solve?

As described in [this issue](https://github.com/bitnami/charts/issues/2010)
and attempted to fix in [this PR](https://github.com/bitnami/charts/pull/8183)
I would love an option to keep sensitive data away from a plain-text solution in values.yaml.

Context: I am trying to set up Harbor in a GitOps manner using ArgoCD.
Since the values file will appear in a git repository, it is very discouraged to save any sensitive data in it and instead we should use Kubernetes secrets.

Some other sensitive fields like certificates can already be set using a 'secretName' field referencing a secret that already exists.

Yet fields like **persistence.imageChartStorage.s3.secretkey** are still plain-text and I could not find any workarounds to keeping them in the file.

### What is the feature you are proposing to solve the problem?

Allow usage of 'secretName' style parameters in the values.yaml file, for any sensitive information like passwords, certificates and access keys.
This parameter will allow us to use an existing Kubernetes secret with the needed data.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by lusu007** [comment]
Is this implemented in #14341? If it is how do I have to use it?
