### ISSUE TITLE
[bitnami/kafka] How to set custom params for Kafka 

### ISSUE THREAD

**Issue by ksemele** [bitnami/charts#14157]
### Name and Version

bitnami/kafka 19.1.3

### What steps will reproduce the bug?

For those steps all are OK:
1. setup gke server
2. install fluxcd v2
3. add HelmRepo https://charts.bitnami.com/bitnami
4. add HelmRelease 
```
chart: kafka
version: 19.1.3
```
5. reconcile it

After that I tried to use any custom configs from [https://github.com/bitnami/charts/tree/main/bitnami/kafka#kafka-parameters](https://github.com/bitnami/charts/tree/main/bitnami/kafka#kafka-parameters)
All works perfect.

But if I try to configure [log.roll.hours](https://kafka.apache.org/documentation/#brokerconfigs_log.roll.hours) via `config:` section, Kafka has been failed to start.

If I manually copy and paste `server.config` file to `config:` section - Kafka works, but it looks strange, because I can't manage brokers by different params...

### What do you see instead?

brokers not started when I use partial config in `config:` section

### Additional information

How I can to configure [log.roll.hours](https://kafka.apache.org/documentation/#brokerconfigs_log.roll.hours) param in bitnami chart?

**Comment by javsalgar** [comment]
Hi,

Could you share an exact values.yaml section that triggers the issue and the values.yaml section that fixes it? Just to properly reproduce the issue.

**Comment by ksemele** [comment]
sure.
that is works:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 1m0s
  releaseName: kafka
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: kafka
      version: 19.1.3
      sourceRef:
        kind: HelmRepository
        name: kafka-repo
        namespace: flux-system
  values:
    networkPolicy:
      enabled: true
    rbac:
      create: true
    externalAccess:
      enabled: true
      autoDiscovery:
        enabled: true
    replicaCount: 1
    deleteTopicEnable: true
    auth:
      protocol: PlainText
      saslMechanism: ""
      username: ""
      password: ""
    provisioning:
      enabled: true
      replicationFactor: 1
      numPartitions: 1
      topics:
        - name: topic-1
        - name: topic-2
    persistence:
      size: 1Gi
    config: |
      log.roll.hours=24

      broker.id=0
      listeners=INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094
      advertised.listeners=INTERNAL://kafka-0.kafka-headless.default.svc.cluster.local:9093,CLIENT://kafka-0.kafka-headless.default.svc.cluster.local:9092,EXTERNAL://34.28.87.129:9094
      listener.security.protocol.map=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      num.network.threads=3
      num.io.threads=8
      socket.send.buffer.bytes=102400
      socket.receive.buffer.bytes=102400
      socket.request.max.bytes=104857600
      log.dirs=/bitnami/kafka/data
      num.partitions=1
      num.recovery.threads.per.data.dir=1
      offsets.topic.replication.factor=1
      transaction.state.log.replication.factor=1
      transaction.state.log.min.isr=1
      log.flush.interval.messages=10000
      log.flush.interval.ms=1000
      log.retention.hours=168
      log.retention.bytes=1073741824
      log.segment.bytes=1073741824
      log.retention.check.interval.ms=300000
      zookeeper.connect=kafka-zookeeper
      zookeeper.connection.timeout.ms=6000
      group.initial.rebalance.delay.ms=0
      allow.everyone.if.no.acl.found=true
      authorizer.class.name=
      auto.create.topics.enable=true
      default.replication.factor=1
      delete.topic.enable=true
      inter.broker.listener.name=INTERNAL
      max.partition.fetch.bytes=1048576
      max.request.size=1048576
      message.max.bytes=1000012
      sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      sasl.mechanism.inter.broker.protocol=
      super.users=User:admin
```

but if I use only this section in config - all brokes
```
# same config as above
    config: |
      log.roll.hours=24
```

**Comment by aoterolorenzo** [comment]
Hi @ksemele,

Could you try to reproduce the issue changing:

```
  server.properties: |-
    {{ .Values.config | nindent 4 }}
```

To just:
```
  server.properties: |
    {{ .Values.config | nindent 4 }}
```

Removing the hyphen? I think It could be the reason for the script to acquire a different behavior using single line or multiline config strings.

**Comment by ksemele** [comment]
I'll try to use
```
  server.properties: |
    {{ .Values.config | nindent 4 }}
```

but I don't understand where :)
syntax looks like part of chart... But I hasn't find any `server.properties` occurrences in bitnami repo...

**Comment by aoterolorenzo** [comment]
I meant in `templates/configmap.yaml`. I think the problem is there.
