### ISSUE TITLE
[bitnami/kube-prometheus][bitnami/thanos] inconsistent replicaLabel

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#14167]
### Name and Version

bitnami/prometheus 8.3.1

### What steps will reproduce the bug?

in kube-prometheus, replicaExternalLabelName is empty which default to `prometheus_replica`

ref:
* https://github.com/bitnami/charts/blob/main/bitnami/kube-prometheus/values.yaml#L877
* https://github.com/bitnami/charts/blob/main/bitnami/kube-prometheus/crds/crd-prometheus.yaml#L5220

in thanos values.yaml, it is set in various place to `replica`:

ref:
* https://github.com/bitnami/charts/blob/main/bitnami/thanos/values.yaml#L167 , etc

this label is used by thanos for deduplication : https://thanos.io/tip/components/query.md/#deduplication, as the value is different in kube-prometheus and thanos, it won't work.

I would expect that when installing kube-prometheus and thanos with default values, they work together "by default".

### What do you see instead?

--

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by RalphSleighK** [comment]
I can confirm this issue is still present and is not "solved"

**Comment by jouve** [comment]
I suggest changing thanos to use `prometheus_replica` by default with a major digit bump

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
