### ISSUE TITLE
Kafka consumers fail With "partitions have leader brokers without a matching listener, including"

### ISSUE THREAD

**Issue by revoorunischal** [bitnami/charts#1416]
Hi ,
    I have setup bitnami/kafka in my minikube and works fine on first go. But on stopping minikube and starting minikube back my Consumers fail with the following error. 

> 2019-09-19 06:04:43.397  WARN 1 --- [ internal-0-C-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-4, groupId=UNIQUE-1] 1 **partitions have leader brokers without a matching listener, including** [INTERNAL-0]

Even if i increase the number of partition i am getting the same error 

> 2019-09-19 06:12:42.267  WARN 1 --- [ external-0-C-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-2, groupId=EXTERNAL] 10 **partitions have leader brokers without a matching listener, including** [FINCACHE-0, FINCACHE-5, FINCACHE-8, FINCACHE-2, FINCACHE-9, FINCACHE-1, FINCACHE-4, FINCACHE-6, FINCACHE-7, FINCACHE-3]

**Comment by javsalgar** [comment]
Hi,

Could you provide with the values you used for deploying kafka? We would like to fully reproduce the issue

**Comment by revoorunischal** [comment]
helm install  --set deleteTopicEnable=true bitnami/kafka

**Comment by javsalgar** [comment]
I tried doing something similar and I did not see anything strange. Could you provide me with the consumer's code so I can check if the issue happens?
