### ISSUE TITLE
[bitnami/argo-cd] Github knownhosts missing variations from helm

### ISSUE THREAD

**Issue by hnougher** [bitnami/charts#14160]
### Name and Version

bitnami/argo-cd:4.4.0

### What steps will reproduce the bug?

TL'DR Helm default needs all three github knownhosts/ssh-keys found in https://api.github.com/meta

2. Install Argo-CD using Helm.
3. Attempt to add GitHub repository using the SSH mode.
4. Get error in logs of "argo-cd-repo-server" of "knownhosts: key mismatch".
5. Adjust installed knownhosts ConfigMap to use all 3 ssh-keys instead of just one.
6. Repository is now working.

### What is the expected behavior?

The supplied GitHub knownhosts list should be complete to avoid long debug sessions.

### What do you see instead?

Getting error in logs of "argo-cd-repo-server" of "knownhosts: key mismatch".

### Additional information

I lodge this issue here since it is an issue with the helm chart rather than any code.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the report! If this is something that can be changed in the configmap YAML, would you like to submit a PR with the fix?
