### ISSUE TITLE
[bitnami/mariadb-galera]: MariaDB Galera's service ports should have application protocol

### ISSUE THREAD

**Issue by ptcar2009** [bitnami/charts#14168]
### Name and Version

bitnami/mariadb-galera 7.4.9

### What is the problem this feature will solve?

When working with `istio`, clustering does not work currently because the proxy is not able to determine the protocol for the `gcomm://` connection, making any replica other then the first fail.

### What is the feature you are proposing to solve the problem?

Add `appProtocol: mysql` to service ports so the operator/proxy is aware of how to resolve the clustering.

### What alternatives have you considered?

Disabling `istio` when in HA

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback
