### ISSUE TITLE
[bitnami/postgresql] auth.database cannot be templated

### ISSUE THREAD

**Issue by benoitdm-oslandia** [bitnami/charts#14165]
### Name and Version

bitnami/postgresql 12.1.6

### What is the problem this feature will solve?

This is the same issue than #13503 but for `.Values.global.postgresql.auth.database` or `Values.auth.database` used by `postgresql.database` in `_helpers.tpl`

### What is the feature you are proposing to solve the problem?

Same solution than #13504 

### What alternatives have you considered?

repeat the db name every where I need it

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback
