### ISSUE TITLE
clickhouse: auto restart for configmap / secret changes in statefulset not configured

### ISSUE THREAD

**Issue by pyromaniac3010** [bitnami/charts#14189]
### Name and Version

bitnami/clickhouse 2.2.1

### What steps will reproduce the bug?

If you change any setting in the referenced configmaps or secrets, the statefulset should automatically restart to use these new settings.
I found this, while I was changing `logLevel: information` to `logLevel: warning` and nothing happened to get this activated.
Most other bitnami charts do this by using a statefulset annotation like this for each referenced configmap / secret:
```
checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{- if (include "zookeeper.createConfigmap" .) }}
checksum/configuration: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- end }}
```

### What is the expected behavior?

automatic restart of the statefulset, if any setting in a referenced secret or configmap changes

### What do you see instead?

no restart. clickhouse operates with the old config until a manual restart by kubectl is triggered.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
