### ISSUE TITLE
[bitnami/argo-workflows] 3.4.3 controller/server are not starting when metrics/serviceMonitor are enabled

### ISSUE THREAD

**Issue by mikulass** [bitnami/charts#14185]
### Name and Version

bitnami/argo-workflows 5.0.1

### What steps will reproduce the bug?

Hello all,

I apologize for wide distribution. Please, I need help or small advice. Maybe it is not a bug.. I'm experiencing error when installing argo workflow with metrics and serviceMonitor enabled to true. Controller and server fails (pods stuck in CrashLoopBackoff/Error state) .

To reproduce please enable serviceMonitor and metrics in values.yaml

Thanks in advance, best regards. Mikulas.

### Are you using any custom parameters or values?

My values.yaml  contains following settings:
```yaml
  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: true
```
controller error is:
```
time="2023-01-04T15:10:15.428Z" level=info msg="Get configmaps 200"                                                                                                                            
time="2023-01-04T15:10:15.438Z" level=fatal msg="Failed to register watch for controller config map: error unmarshaling JSON: while decoding JSON: json: unknown field \"serviceMonitor\""  
```
server error is:
```
time="2023-01-04T15:10:31.298Z" level=info msg="SSO disabled"                                                                                                                                    time="2023-01-04T15:10:31.315Z" level=fatal msg="error unmarshaling JSON: while decoding JSON: json: unknown field \"serviceMonitor\""  
```
I'm running argo workflows 3.4.3 also with argo-events in same namespace called argo-events. 

When I change parameters above from true to false in everything is is running. But in that "false" case Prometheus does not see serviceMonitor/metrics from argo workflow.   

### What is the expected behavior?

I expected to have controller an server started in Running state with  metrics and serviceMonitor enabled. Then I've expected to see in Prometheus serviceMonitor and metrics for argo workflows.  

### What do you see instead?

controller error is:
```
time="2023-01-04T15:10:15.428Z" level=info msg="Get configmaps 200"                                                                                                                            
time="2023-01-04T15:10:15.438Z" level=fatal msg="Failed to register watch for controller config map: error unmarshaling JSON: while decoding JSON: json: unknown field \"serviceMonitor\""  
```
server error is:
```
time="2023-01-04T15:10:31.298Z" level=info msg="SSO disabled"                                                                                                                                    time="2023-01-04T15:10:31.315Z" level=fatal msg="error unmarshaling JSON: while decoding JSON: json: unknown field \"serviceMonitor\""
```

**Comment by mikulass** [comment]
Hello, 
small update, maybe workaround, but not solution.. When I've tried two helm commands:

1. helm template with above values set to true, I've received file1.yaml , then 
2. helm template with values set to false, I've receive file2.yaml file.
 
After comparing file1.yaml and file2.yaml I've seen, that differences are in 2 parts: 
apiVersion: monitoring.coreos.com/v1 kind: ServiceMonitor  and apiVersion: v1, kind: Service.

For this two parts I've created two "new" yaml files and then applied these files to the already installed workflows with values set to false. And it started to work..

Best regards, Mikulas.

**Comment by corico44** [comment]
Hello @mikulass, sorry for the delay. With the workaround you mention, have you managed to solve it?

**Comment by thanhtai9606** [comment]
> Hello @mikulass, sorry for the delay. With the workaround you mention, have you managed to solve it?

I received the same error, when I enable 
`Error: error unmarshaling JSON: while decoding JSON: json: unknown field "serviceMonitor"`

**Comment by sonnysideup** [comment]
This problem is still unsolved with the latest version of the Chart (v5.2.1), so why was this issue closed? If another one was opened with the details, can you reference it here?

**Comment by fouadsemaan** [comment]
Why is this issue closed? @carrodher can you please help shed some light?

**Comment by carrodher** [comment]
Since the original issue was created a long time ago, [I suggested creating a new one](https://github.com/bitnami/charts/issues/14185#issuecomment-1502734755) with the specific details of the issues faced at this moment

**Comment by mikulass** [comment]
Hello, we've recently upgraded to `app version 3.5.1` and `chart version 6.2.0`. We've used  same workaround like last year, mentioned above, using helm template.

**Comment by sonnysideup** [comment]
I can't really track your solution @mikulass, so I'm going to offer the following diagnosis and workaround for other folks.

## Problem

The main issue is that the `controller.metrics` values are being used to (a) controller the rendering of different templates and (b) also used as the content for the ConfigMap template; the latter part is the design flaw that is causing this error.

When you set `controller.metrics.enabled=true`, the template string contained in `controller.config` will use the contents of `controller.metrics` to render what gets passed to the argo-worfklows controller. This configuration is invalid because the controller does not expect a `serviceMonitor` field nested under its `metricsConfig`.

The `controller.config` template current does this

```tpl
{{- if .Values.controller.metrics.enabled }}
metricsConfig: {{- include "common.tplvalues.render" (dict "value" .Values.controller.metrics "context" $) | nindent 2 }}
{{- end }}
```

which renders this

```yaml
metricsConfig:
  enabled: true
  path: /metrics
  serviceMonitor: # this is the erroneous field
    enabled: false
```

## Workaround

Copy over the full-contents of `controller.config` and make 1 minor change

```tpl
{{- if .Values.controller.metrics.enabled }}
metricsConfig:
  enabled: true
  path: {{ .Values.controller.metrics.path }}
{{- end }}
```

so that you no longer pass an invalid config to the controller.

## Solution

@carrodher I'd either uncouple this by creating separate _control_ and _content_ values, or perform a limited render like I've done up above.

**Comment by KrisF-Midnight** [comment]
This is still an issue unfortunately!

**Comment by EugeneChep** [comment]
Still issue with the most recent chart version (9.1.14)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by KrisF-Midnight** [comment]
i.e. "fix it yourself, we won't bother."

**Comment by Nexus2k** [comment]
Issue is still there... greedy bitnami guys want money to fix I guess?
