### ISSUE TITLE
[bitnami/postgresql] TLS and custom configuration cannot be used together

### ISSUE THREAD

**Issue by ausias-armesto** [bitnami/charts#14190]
### Name and Version

bitnami/postgresql 12.1.6

### What steps will reproduce the bug?

The problem is detected when I try to enable TLS in the helm chart and want to change the default authentication mechanism used for `hostssl` connections from `cert` to `md5`. I don't want my clients to use client-certificates, just SSL connection with passwords and therefore I would like to change the authentication mechanism from `cert` to `md5`.

1. Configure a helm chart release with TLS and custom configuration
2. Initially I would like to specify only the contents of the pg_hba.conf file by setting `primary. pgHbaConfiguration`, but as per design of the Helm chart, the volume is mounted on the directory, and then these two properties need to be set: `primary.configuration` and `primary. pgHbaConfiguration`. This could be considered a bug and the solution would imply modify the way that is mounted and do it at a file basis.
3. I provide a default contents for `primary.configuration` setting
4.  On the startup of the postgresql container, the scripts that are in charge of setting up the database and users, do not work propertly because a custom pgHbaConfiguartion has been set which indicates that connections need to be done using `md5` authentication mechanism instead of the initial mechanism set in the [scripts](https://github.com/bitnami/containers/blob/main/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L220) `trust`.
5. This probes that using custom TLS configuration using `md5` authentication mechanism is not posible. 

### Are you using any custom parameters or values?

Custom values
````yaml
    image:
      tag: 15.1.0-debian-11-r12
      debug: true
    auth:      
      postgresPassword: XXXXXXX
    volumePermissions:
      enabled: true
    tls:
      enabled: true
      certificatesSecret: postgres-tls
      certFilename: tls.crt
      certKeyFilename: tls.key
      certCAFilename: ca.crt
    primary:
      configuration: "{{ lookup('ansible.builtin.template','postgresql.conf.j2') }}"
      pgHbaConfiguration: |
        hostssl  all             all             0.0.0.0/0               md5
        host     all             all             0.0.0.0/0               md5
        local    all             all                                     md5
        host     all             all        127.0.0.1/32                 md5
        host     replication     all             0.0.0.0/0               md5
````

### What is the expected behavior?

I would like to be able to setup a TLS configuration with `md5` authentication mechanism

### What do you see instead?

The logs show that password authentication failed
```console
$ kubectl logs -n postgres postgres-postgresql-0 -p -c postgresql
postgresql 09:52:17.23 
postgresql 09:52:17.23 Welcome to the Bitnami postgresql container
postgresql 09:52:17.23 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 09:52:17.24 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 09:52:17.24 
postgresql 09:52:17.24 DEBUG ==> Configuring libnss_wrapper...
postgresql 09:52:17.26 INFO  ==> ** Starting PostgreSQL setup **
postgresql 09:52:17.28 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 09:52:17.29 INFO  ==> Loading custom pre-init scripts...
postgresql 09:52:17.29 INFO  ==> Initializing PostgreSQL database...
postgresql 09:52:17.30 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgresql 09:52:17.30 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql 09:52:17.30 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 09:52:17.31 DEBUG ==> Ensuring expected directories/files exist...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    /opt/bitnami/postgresql/bin/pg_ctl -D /bitnami/postgresql/data -l logfile start

postgresql 09:52:21.05 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2023-01-05 09:52:21.209 GMT [69] LOG:  pgaudit extension initialized
2023-01-05 09:52:21.299 GMT [69] LOG:  starting PostgreSQL 15.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-01-05 09:52:21.299 GMT [69] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-01-05 09:52:21.299 GMT [69] LOG:  listening on IPv6 address "::", port 5432
2023-01-05 09:52:21.357 GMT [69] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-01-05 09:52:21.487 GMT [72] LOG:  database system was shut down at 2023-01-05 09:52:19 GMT
2023-01-05 09:52:21.661 GMT [69] LOG:  database system is ready to accept connections
 done
server started
2023-01-05 09:52:21.723 GMT [77] FATAL:  password authentication failed for user "postgres"
2023-01-05 09:52:21.723 GMT [77] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
2023-01-05 09:52:21.723 GMT [77] LOG:  could not send data to client: Broken pipe
postgresql 09:52:21.72 INFO  ==> Changing password of postgres
Password for user postgres: 
2023-01-05 09:52:21.742 GMT [82] FATAL:  password authentication failed for user "postgres"
2023-01-05 09:52:21.742 GMT [82] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
2023-01-05 09:52:21.743 GMT [82] LOG:  could not send data to client: Broken pipe
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
2023-01-05 09:52:21.755 GMT [83] FATAL:  password authentication failed for user "postgres"
2023-01-05 09:52:21.755 GMT [83] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
postgresql 09:52:21.75 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down....2023-01-05 09:52:21.766 GMT [69] LOG:  received fast shutdown request
2023-01-05 09:52:21.820 GMT [69] LOG:  aborting any active transactions
2023-01-05 09:52:21.824 GMT [69] LOG:  background worker "logical replication launcher" (PID 75) exited with exit code 1
2023-01-05 09:52:21.824 GMT [70] LOG:  shutting down
2023-01-05 09:52:21.877 GMT [70] LOG:  checkpoint starting: shutdown immediate
2023-01-05 09:52:22.264 GMT [70] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.107 s, total=0.441 s; sync files=2, longest=0.054 s, average=0.054 s; distance=0 kB, estimate=0 kB
2023-01-05 09:52:22.270 GMT [69] LOG:  database system is shut down
 done
server stopped
````

### Additional information

In order to fix this problem, I would prefer the script to change the way that is setting the pg_hba.conf file, and do the following:
* If postgresql_is_file_external is provided then copy the contents of it
* Perform the initial setup of the database (create users and changing password) with the `trust` mechanism using the method `postgresql_create_pghba`
* The last step would be, replace the current pg_hba.conf with the provided initially.
* Then we can skip the pg_hba.conf configuration on startup scripts, and avoid this issue.

**Comment by jotamartos** [comment]
Hi @ausias-armesto,

This issue is related to these 2 other issues. Can you take a look at them?

https://github.com/bitnami/charts/issues/13386
https://github.com/bitnami/charts/issues/8650

Thanks

**Comment by ausias-armesto** [comment]
Hi @jotamartos ,
You're right the issue is related but here there is no workaround, as the only authentication mechanism for TLS is cert.

Best regards,
Ausiàs.

**Comment by jotamartos** [comment]
Hi @ausias-armesto,

As Fran mentioned [here](https://github.com/bitnami/charts/issues/8650#issuecomment-1014475123), would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jotamartos** [comment]
Hi @ausias-armesto,

As Fran mentioned [here](https://github.com/bitnami/charts/issues/8650#issuecomment-1014475123), would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ausias-armesto** [comment]
Hi,
Thanks, but I don't think that I will have time to do it now.

**Comment by jotamartos** [comment]
In that case, we will keep the ticket open in case someone from the community wants to contribute or add more information. Otherwise, the team will be waiting for the PR in case you have some time in the future. 

Thanks
