### ISSUE TITLE
Firestore support for node.js chart

### ISSUE THREAD

**Issue by LP0101** [bitnami/charts#1420]
Unless I'm mistaken, it seems there's no way to use a firebase firestore as the database for the node.js chart, and by extension the bitnami node.js image. It would be fantastic if this was an option.

**Comment by juan131** [comment]
Hi @LP0101 

I guess it'd be enough with providing support for external databases (so the MongoDB dependency is optional). 

We already have support for this in other charts (e.g. Wordpress, see https://github.com/bitnami/charts/blob/master/upstreamed/wordpress/README.md#using-an-external-database). Would a solution like this work for you?

**Comment by LP0101** [comment]
Unfortunately, we'd already looked at the external DB option, and it won't work with Firestore.

Firestore (and Firebase as a whole) uses its own module to connect the node app to the database. See [here](https://firebase.google.com/docs/firestore/quickstart) for more information, under "Initialize on your own server."

**Comment by javsalgar** [comment]
From what I read, you would need to mount your own secrets with the firebase credentials, and then you would be able to use it within your application, right? You could also use the extraEnv settings to have environment variables with the value. Would that work?
