### ISSUE TITLE
[Redis] redis_exporter: Command not found

### ISSUE THREAD

**Issue by simonszu** [bitnami/charts#14206]
### Name and Version

bitnami/redis 17.4.1

### What steps will reproduce the bug?

1. Deploy the redis chart with vanilla values.yaml
2. The redis-master pod comes up with only one container as ready
3. Investigate with getting logs from the metrics container: `k logs -f redis-master-0 -c metrics`
4. `/bin/bash: line 4: redis_exporter: command not found`
5. Pod goes into CrashLoopBackOff, the replicas-pod as well. 

### Are you using any custom parameters or values?

No, the vanilla values.yaml is used

### What is the expected behavior?

The pod comes up with the metrics container working.

### What do you see instead?

```

❯ k get pods | grep redis
redis-master-0                                    1/2     CrashLoopBackOff   7 (4m29s ago)    15m
redis-replicas-0                                  0/2     CrashLoopBackOff   15 (4m55s ago)   15m

```
The ready container in the master-pod is the actual redis master container, not the metrics pod. 
```
❯ k logs -f redis-master-0 -c metrics
/bin/bash: line 4: redis_exporter: command not found
```

### Additional information

 Even disabling the metrics feature via the values.yaml makes no difference. This is counter-intuitive since that should advise the chart not to deploy any metrics container.

**Comment by marcosbc** [comment]
Hi @simonszu, could you `kubectl describe` the pod and check which container image is being run?

I have checked the `bitnami/redis-exporter:1.45.0-debian-11-r22` container does include the `redis_exporter` command in the PATH and the chart is not making any modifications to the environment variable. You should be able to verify this on your side by executing this:

```
$ docker run -ti --entrypoint= bitnami/redis-exporter:1.45.0-debian-11-r22 which redis_exporter
/opt/bitnami/redis-exporter/bin/redis_exporter
```

**Comment by simonszu** [comment]
Sorry, my bad. For a harbor instance i implemented terraform manifests for both postgresql and redis for the same apply run, and accidentally provided the postgresql values.yaml to the redis manifest. Fixed that, now it's working.
