### ISSUE TITLE
[bitnami/postgresql-ha] pgpoolAdmin support

### ISSUE THREAD

**Issue by peske** [bitnami/charts#14205]
### Name and Version

bitnami/postgresql-ha 10.0.7

### What is the problem this feature will solve?

Easier administration of pgpool via web interface.

### What is the feature you are proposing to solve the problem?

The existing pgpoolAdmin web interface should be somehow included in the chart.

### What alternatives have you considered?

N/A

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feedback! I will forward this information to the engineering team. For the time being, you can use the `extraDeploy` section to add a deployment of an existing pgpooladmin container.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
