### ISSUE TITLE
[bitnami/keycloak] Post Keycloak Installation Console is Not Accessible Remotely(same network host)

### ISSUE THREAD

**Issue by fauzankhanak** [bitnami/charts#14204]
### Name and Version

bitnami/keycloak:20.0.2-debian-11-r2

### What steps will reproduce the bug?

k8s version: "v1.19.9"
docker version: 19.03.15
helm version: "v3.7.0"

1. Install keycloak using bitnami Helm chart and use the service type NodePort
2. Facing issue for both production and development Setup
3. only 1 replica
4. kubenetes is single node cluster

### Are you using any custom parameters or values?
```
JAVA_OPTS: -Xms2048m -Xmx4096m
KC_HTTP_HOST: 0.0.0.0
Proxy: passthrough
cache: true, type: kubernetes
Production: true
```
### What is the expected behavior?

Url should be accessible from remote host in same network
As of now only accessible from local host(same host)

### What do you see instead?

As of now only accessible from local host(same host)

### Additional information

Tried all the cache type: Kubenetes, tcp,udp
tried all the proxy type: None, passthrough,edge, reencrypt

**Comment by marcosbc** [comment]
Could you share more information about your issue? E.g. HTTP error code and/or screenshots. In addition, have you tried using other service types and/or ingress?
