### ISSUE TITLE
[bitnami/oauth2-proxy] Google Provider issue

### ISSUE THREAD

**Issue by vvdaal** [bitnami/charts#14208]
### Name and Version

bitnami/oauth2-proxy 3.4.2

### What steps will reproduce the bug?

* Deploy chart with Google provider and a JSON
* Pod will never start due to the JSON file not being mounted as the secret is referenced incorrectly

### What is the expected behavior?

Secret name should be appended with -google as that is how the secret is created

### What do you see instead?

Secret name does not have -google appended and thus can't be referenced

**Comment by vvdaal** [comment]
Proposed fix https://github.com/bitnami/charts/pull/14210

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, the team will review it and provide feedback
