### ISSUE TITLE
Harbor deployment fails due to chartmuseumImage pullPolicy variable name mismatch

### ISSUE THREAD

**Issue by wojciechka** [bitnami/charts#1422]
**Which chart**: 

Harbor 2.6.8

**Description**

The `values.yaml` defines `pullPolicy: IfNotPresent in` `chartMuseumImage:` section; the deployment is doing `imagePullPolicy: {{ .Values.chartMuseumImage.imagePullPolicy | quote }}` and it fails.

**Steps to reproduce the issue:**

Try to deploy the chart; doing `helm template` also returns `imagePullPolicy: <nil>`.

**Describe the results you received:**

When trying to deploy using `helm install`:
```
Deployment.apps "harbor1-chartmuseum" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "<nil>": supported values: "Always", "IfNotPresent", "Never"
```

`helm template` renders `imagePullPolicy: <nil>`.

**Describe the results you expected:**

I expected a working harbor installation

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens all the time.

**Version of Helm and Kubernetes**:

```
$ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

K8s version:
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-7f15cc", GitCommit:"7f15ccb4e58f112866f7ddcfebf563f199558488", GitTreeState:"clean", BuildDate:"2019-08-19T17:46:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Thanks for reporting the issue @wojciechka 

I just created a PR to address it.
