### ISSUE TITLE
[bitnami/redis] Add commonLabels also to redis pods when deploying master, replicas or sentinel

### ISSUE THREAD

**Issue by byroncollins** [bitnami/charts#14245]
### Name and Version

bitnami/redis 7.0.7

### What steps will reproduce the bug?

1. Deploy Redis with a label set via the values.yaml commonLabels

### Are you using any custom parameters or values?

```
commonLabels:
    someLabel: "someLabel"
```

### What is the expected behavior?

As stated in the documentation, I would expect all deployed resources to have the label:

Add labels to all the deployed resources (sub-charts are not considered). Evaluated as a template

### What do you see instead?

Redis pods do not get the label

### Additional information

Maybe I misunderstand the documentation, but I would expect the redis pods also to have the label. This would be easily achievable by adding the commonLabels to the pods and not only the podLabels here: 

- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/master/application.yaml#L35
- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/replicas/statefulset.yaml#L34
- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/sentinel/statefulset.yaml#L33

If you agree I could prepare a PR for this.

**Comment by javsalgar** [comment]
Hi!

Thank you for raising this. I think it makes sense to fix this issue in the chart. Feel free to submit a PR following the contributing guidelines: https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md

The community will benefit from this! :D
