### ISSUE TITLE
Why is Bitnami deleting all charts older than a few months?

### ISSUE THREAD

**Issue by JVMartin** [bitnami/charts#14243]
### Name and Version

bitnami/mongodb, bitnami/redis, many others

### What steps will reproduce the bug?

My team has a serious problem - we use Helm charts from ArtifactHub, many of which are built and maintained by Bitnami.

We're talking major components like mongodb and redis.

If you look at any of these, you'll see someone is deleting all versions of the chart older than just a few months:
https://artifacthub.io/packages/helm/bitnami/mongodb
https://artifacthub.io/packages/helm/bitnami/redis

So if you're using a chart from just 1 year ago, you are totally hosed in the event of a disaster recovery scenario, the charts are nowhere to be found and you are unable to migrate your cluster.

Why is this happening? Can Bitnami please stop deleting these charts? Is there somewhere else we're supposed to be using for charts older than a few months?

Why shouldn't all versions be available in perpetuity? These things are just a few kilobytes of templates.

### What do you see instead?

I want to see all charts available in perpetuity so that we aren't left completely stranded in a disaster scenario for any workloads we have running charts older than a few months.

**Comment by JVMartin** [comment]
Apologies, didn't see the FAQ.

**Comment by johanphilips** [comment]
@JVMartin Could you point me to the article in the FAQ that solved it for you. I am banging my head over this issue and unable to download any old version. We were using mongodb 10.7.1...

**Comment by JVMartin** [comment]
@johanphilips Sure no problem, it's the pinned issue on this issue board:
https://github.com/bitnami/charts/issues/10833
