### ISSUE TITLE
Unable to disable auth for the etcd

### ISSUE THREAD

**Issue by XSAM** [bitnami/charts#14249]
### Name and Version

bitnami/etcd 8.5.11

### What steps will reproduce the bug?

1. Render etcd chart with default config.

### What is the expected behavior?

The chart should provide a way to disable the etcd auth feature.

### What do you see instead?

No way to prevent rendering `ETCD_AUTH_TOKEN`. It seems no way to disable auth for etcd.

### Additional information

https://github.com/bitnami/charts/tree/main/bitnami/etcd#etcd-parameters

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
