### ISSUE TITLE
[bitnami/rabbitmq] GKE pod crash: "eagain" error in open_port

### ISSUE THREAD

**Issue by sagimann** [bitnami/charts#14257]
### Name and Version

bitnami/rabbitmq 11.1.1 (rabbit 3.11.2)

### What steps will reproduce the bug?

1. using 1.23 GKE cluster node 2 vcpu, 15GB RAM
2. install helm chart with values.yaml (and apply custom ingress due to some TLS config)
3. try to connect via AMQP client - usually works but sometimes fails and GKE console shows the pod not running
4. upon failure, observe the pod log in the GCP console

### Are you using any custom parameters or values?

attached values.yaml (redacted). Notice ingress is off, I'm using a different ingress because we need to use a wildcard certificate which doesn't seem to be supported by the chart.

[rabbitmq-values.txt](https://github.com/bitnami/charts/files/10386051/rabbitmq-values.txt)

### What is the expected behavior?

connection should succeed, pod should not crash over and over

### What do you see instead?

sometimes, and it seems really sporadic, connections fail, GKE shows 0/1 instances running and rabbitmq keeps restarting while showing the following error repeatedly:
```
         *** argument 1: invalid port name
                              exit_status,stderr_to_stdout,use_stdio])"
                                   ""erlang"",""halt""]},"
                                   ""epmd-starter-374974361"",""-noinput"",""-s"","
                                  [""-boot"",""no_dot_erlang"",""-sname"","
                             [{args,"
                                 ""/opt/bitnami/erlang/lib/erlang/erts-13.1.1/bin/erl""},"
         called as open_port({spawn_executable,"
      in function  open_port/2
    exception error: eagain
```
attaching a log (500 lines from the crash)
[downloaded-logs-20230110-205827.csv](https://github.com/bitnami/charts/files/10386036/downloaded-logs-20230110-205827.csv)

### Additional information

"eagain" usually means some resource is unavailable but it's unclear which once. I suspected that since it happens during "open port", it's something to do with network connections or sockets. CPU and disk space seem ok in the GCP dashboard, no load whatsoever.

RAM shows around 11/15GB used long before, during and after the crash so hard to say if it's related. There are 2 mongo charts on that node. Only one takes up a lot of memory (around 9.5GB). The other one takes up around 400M. There are also other pods, unrelated to mongo, on that node.

GKE doesn't let me access the host itself to check ulimits and the likes - all I can see are the ulimits of the container:
```
ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 64
process              unlimited
nofiles              1048576
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
```

**Comment by javsalgar** [comment]
Hi,

Looking at the issue, it is not fully clear to me that problem lies in the Bitnami packaging. In this sense, I think that the RabbitMQ team should take a look first to understand if the issue could be in the application itself. Did you check with the RabbitMQ devs?

**Comment by sagimann** [comment]
Not yet, will do
