### ISSUE TITLE
[thanos] Client/server TLS certificate keys not compatible with certs issued by cert-manager

### ISSUE THREAD

**Issue by danielfm** [bitnami/charts#14262]
### Name and Version

bitnami/thanos 11.6.4

### What is the problem this feature will solve?

Ref: https://github.com/bitnami/charts/blob/d5577f41e99f7e7ec07d3131a9f9d829c53a0a92/bitnami/thanos/templates/query/deployment.yaml#L141-L151

The way the chart is structured, we can't use Secrets created by `cert-manager` in the `(query|storegateway).grpc.(server|client).tls.existingSecret` parameters. The current chart version assume the CA, cert and key files are exposed through the `ca-cert`, `tls-cert` and `tls-key` attributes, instead of the standard `ca.crt`, `tls.crt` and `tls.key` attributes for Secrets of type `kubernetes.io/tls`.

This chart should use the same convention for compatibility with other projects, such as `cert-manager`.

### What is the feature you are proposing to solve the problem?

We need a way to specify the correct file path for the client/server secrets, in a way that we can reference the Secret fields `ca.crt`, `tls.crt` and `tls.key`, which are the keys populated by `cert-manager`.

### What alternatives have you considered?

I managed to make this work by disabling the client/server TLS configuration in the chart, mounting the certificate secrets via the `volumes` and `volumeMounts` settings, and providing the TLS flags manually.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by danielfm** [comment]
The suggested approach, which is to change the reference from the old keys (`ca-cert`, `tls-cert` and `tls-key`) to the new (`ca.crt`, `tls.crt` and `tls.key`) acceptable? This will break existing setups.

Or maybe making these key names configurable via flags exposed in the `values.yaml` file? If so, do you suggest how to name those, or where in the existing configuration structure to place those?

**Comment by danielfm** [comment]
Actually, upon close inspection of the `values.yaml` file, it seems that functionality for mapping the secret key is already in place, but it's not documented.

https://github.com/bitnami/charts/blob/c529a0a30abe1ff47c1b09beaf48011e2ea9504a/bitnami/thanos/values.yaml#L413-L418

I'll test this and, if it works as expected, I'll close this issue afterwards.

**Comment by rafariossaa** [comment]
Hi @danielfm,
  Thanks for checking it out.
  What changes do you suggest ? Feel free to send a PR, we will be glad to review and merge it.

**Comment by junoriosity** [comment]
I also have question, that might suit this discussion. I am currently trying to setup a Multi-Cluster Prometheus monitoring with Thanos. I managed to install Prometheus with sidecar in each cluster. Also, I managed to install the Thanos querier in each cluster and it finds Prometheus in the respective cluster. 🙂

Now here is the hard part: For all observee clusters Thanos Query should use ingress via nginx and grpc. So far my configuration seems okay, but for the observer cluster I would need three crt like objects: ca.crt, tls.crt and tls.key
However, I am using Cloudflare and from these guys I just got the last two.

My question is now, when using nginx and Cloudflare for my current setup, where do I get also the right ca.crt from? It would be great if you could help me here. 🙂

**Comment by danielfm** [comment]
> Hi @danielfm, Thanks for checking it out. What changes do you suggest ? Feel free to send a PR, we will be glad to review and merge it.

Maybe some change to README on how to map keys of an existing secret to comply with what's expected by the chart.

**Comment by rafariossaa** [comment]
> Now here is the hard part: For all observee clusters Thanos Query should use ingress via nginx and grpc. So far my configuration seems okay, but for the observer cluster I would need three crt like objects: ca.crt, tls.crt and tls.key However, I am using Cloudflare and from these guys I just got the last two.

Maybe you can ask them where you can get the ca.crt file. I think sometime the servers provide the full certs chain and maybe you can extract it from there. But my suggestion is to better ask them.

**Comment by rafariossaa** [comment]
@danielfm What do you think about [this](https://github.com/bitnami/charts/pull/14396) ?
