### ISSUE TITLE
[bitnami/metallb] networkpolicy prevents webhook from working

### ISSUE THREAD

**Issue by funkypenguin** [bitnami/charts#14272]
### Name and Version

bitnami/metallb 4.1.13

### What steps will reproduce the bug?

1. Deploy the helm chart with `networkPolicy.enabled = true`
2. Attempt to deploy a CR based on the [metallb CRDs](https://metallb.universe.tf/configuration/migration_to_crds/)
3. CRDs will fail to deploy because the validating webhook (running on the controller) can't be reached, due to  https://github.com/bitnami/charts/blob/main/bitnami/metallb/templates/networkpolicy.yaml

### Are you using any custom parameters or values?

```
networkPolicy:
  enabled: true
```

### What is the expected behavior?

The networkPolicy should permit the webhook to still function

### What do you see instead?

The networkPolicy only permits the controller to be scraped for metrics, but doesn't permit port `9443` to be accessed

**Comment by rafariossaa** [comment]
Hi,
  Not very sure on how to reproduce the issue.
  To test it, I deployed a wordpress chart, that uses LoadBalancer and that loadbalancer got an IP assigned.
- Install wordpress (with default values.yaml)  
```
$ cd bitnami/wordpress
$ helm install mywp -f values.yaml .
$ kubectl get pods
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
service/kubernetes       ClusterIP      10.96.0.1        <none>           443/TCP                      126m
service/mywp-mariadb     ClusterIP      10.101.254.160   <none>           3306/TCP                     5m34s
service/mywp-wordpress   LoadBalancer   10.111.10.169    pending          80:31351/TCP,443:31958/TCP   5m34s
```
- Deploy the metallb (with default values.yaml)
```
$ helm install mymetal -f values.yaml -n metallb-system --create-namespace --set networkPolicy.enabled=true .

$ cat config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.49.100-192.168.49.150

$ kubectl apply -f config.yaml

$ kubectl get svc
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
kubernetes       ClusterIP      10.96.0.1        <none>           443/TCP                      129m
mywp-mariadb     ClusterIP      10.101.254.160   <none>           3306/TCP                     8m38s
mywp-wordpress   LoadBalancer   10.111.10.169    192.168.49.100   80:31351/TCP,443:31958/TCP   8m38s
```
