### ISSUE TITLE
[bitnami/fluentd] PSP and ClusterRole name mismatch

### ISSUE THREAD

**Issue by Hirostil** [bitnami/charts#14280]
### Name and Version

bitnami/fluentd 5.5.12

### What steps will reproduce the bug?

With pspEnabled parameter set to true

### Are you using any custom parameters or values?
```
forwarder:
  rbac:
    pspEnabled: true
```

### What do you see instead?

The PodSecurityPolicy is not used because in the ClusterRole the name of the PodSecurityPolicy mismatch

**Comment by javsalgar** [comment]
Hi,

Thanks for spotting the issue! Would you like to submit a PR fixing the mismatch?

**Comment by Hirostil** [comment]
PR created :)

**Comment by javsalgar** [comment]
Thank you so much! The team will take o look
