### ISSUE TITLE
Bitnami Drupal - can't install new site with drush when using AWS RDS

### ISSUE THREAD

**Issue by TenJeno** [bitnami/charts#14292]
### Name and Version

bitnami/drupal:9.4.9-debian-11-r0

### What steps will reproduce the bug?

1. Install bitnami drupal release using HELM 3 into AWS EKS Kubernetes cluster (v 1.23)
2. Use external DB hosted in AWS RDS. Database - MariaDB 10.5.17
3. Set `drupalSkipInstall` to `false`
4. Configure your external DB connection

### What is the expected behavior?

The `/opt/bitnami/scripts/drupal/setup.sh` script should truncate the database and create a new site setup 

### What do you see instead?

Instead of creating a new site, the following error pops up

```
[warning] Undefined array key "driver" SqlBase.php:112
 [warning] Undefined array key "driver" SqlBase.php:112
 [warning] Program UNKNOWN not found. Proceed if you have already created or emptied the Drupal database.

 // Do you want to continue?: yes.

 [warning] Undefined array key "driver" SqlBase.php:112
 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_settings_form

In install.core.inc line 1187:

  <ul>
  <li>To start over, you must empty your existing database and copy <em>default.settings.php</em> over <em>settings.php</em>.</li>
  <li>To upgrade an existing installation, proceed to the <a href="/update.php">update script</a>.</li>
  <li>View your <a href="http://default/">existing site</a>.</li>
  </ul>
```

### Additional information

it appears that the `/opt/bitnami/scripts/drupal/setup.sh` script doesn't read the database configuration.
If I exec into the running pod, I can see that `$databases['default']['default']` is never set in `/opt/bitnami/drupal/sites/default/settings.php`

Upon adding database config manually to the above file, I can execute `drush site:install` without any arguments, and it will work.
However, if I try executing `drush site:install` command with all arguments as in `/opt/bitnami/scripts/drupal/setup.sh` then it still doesn't work.

I initially thought that drupal pod doesn't get all the env variables, but upon checking with `env` inside the pod, I can see that all variables for DB connection are set.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/drupal#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by TenJeno** [comment]
can't reproduce. closing
