### ISSUE TITLE
[bitnami/kube-prometheus] Chart breaks with K8s Upgrade 1.24.x -> 1.25.x

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#14298]
### Name and Version

bitnami/kube-prometheus 8.3.2

### What steps will reproduce the bug?

Have the chart installed in an 1.24.x cluster
upgrade K8s
try to upgrade/change the chart

### What is the expected behavior?

The chart doesnt break

### What do you see instead?
```
Helm upgrade failed: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "prometheus-operator" namespace: "monitoring-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

### Additional information

This is caused by https://github.com/bitnami/charts/blob/c529a0a30abe1ff47c1b09beaf48011e2ea9504a/bitnami/kube-prometheus/templates/prometheus-operator/psp.yaml#L1 amd helm.
Basically helm keeps track of the PSP and wants to remove it after this evaluates to false. But K8s doesnt know anything about that resource, thus helm fails. 
The only way to prevent this is to manually prevent PSPs from being created while being on 1.24 (which is bad and most people will forget) or to automatically drop PSPs in 1.24 unless manually enabled, making sure the resource is deleted when the api still knows it

**Comment by marcosbc** [comment]
Hi @MaxRink, I'm unsure how we can fix it at this point. Maybe having increased the chart major and added it to the upgrade notes? I guess we can still add it though, although it is a bit late for changing the major. Do you have any thoughts on that?

**Comment by carrodher** [comment]
Could you please elaborate on what is your issue? Bitnami charts are tested on top of different k8s clusters with, at this moment, versions from 1.23 to 1.27 and we didn't detect any issue

**Comment by 2snEM6** [comment]
> Could you please elaborate on what is your issue? Bitnami charts are tested on top of different k8s clusters with, at this moment, versions from 1.23 to 1.27 and we didn't detect any issue

My bad Carlos, this was a mistake on my side. I had to delete deprecated Kubernetes APIs from the Helm Secret for this to work.

Disregard my previous comment.

Thank you 🙏
