### ISSUE TITLE
Any chance to have a chart for filebeat

### ISSUE THREAD

**Issue by FranAguiar** [bitnami/charts#14312]
### Name and Version

bitnami/filebeat

### What is the problem this feature will solve?

Elastic will deprecate all its helm chart for the ELK stack, bitnami already have charts for Elasticsearch, Logstash and Kibana, would be nice to also have a chart for Filebeat. Any chance team?

Actually, bitnami charts are already ahead of the officials ones in the application version
Elastic announcement: https://github.com/elastic/helm-charts/issues/1731

@jmlrt Mention in the announcement above that the community could take ownership of the charts. 🙏

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by nicklausbrown** [comment]
curious if there has been any movement here?

**Comment by javsalgar** [comment]
I'm afraid that there are no short or mid term plans to work on this solution, as there are others with higher priority to work on. As soon as there are updates, we will update this ticket.
