### ISSUE TITLE
Master node still readonly after failover

### ISSUE THREAD

**Issue by adriellcardoso** [bitnami/charts#14321]
### Name and Version

bitnami/redis 17.4.2

### What steps will reproduce the bug?

1. Install redis with sentinel enabled (values.yaml) on minikube:
`helm upgrade --install redis-ha -f values.yaml --namespace toggle --create-namespace bitnami/redis`

2. After starting successfully, delete the master node:
`kubectl -n toggle delete pod test-redis-node-0`

3. Using some cli (like [redis-bash-cli](https://github.com/caquino/redis-bash)), try to write something at the new master node:
`./redis-bash-cli -h featureflag-redis-node-1.featureflag-redis-headless.toggle.svc.cluster.local -p 6379 SET key8 External` 

### Are you using any custom parameters or values?

values.yaml:
```yaml
fullnameOverride: "test-redis"
auth:
  enabled: false
  sentinel: false
sentinel:
  enabled: true
```

### What is the expected behavior?
```
OK!
```
I would like to see confirmation about the written value.

### What do you see instead?
```
READONLY You can't write against a read only replica
```
### Additional information

I've installed the Redis with sentinel enabled, after the cluster starts, I deleted the master node (node-0) to test the failover.
After that, I installed the [redis-bash](https://github.com/caquino/redis-bash) to connect in the redis at the new master node, but when I tried to write something (external of the cluster) I got the following error:
`READONLY You can't write against a read only replica`
This is strange because I connected in the same node by the redis-cli and I wrote in a key successfully.
There is any specific setting to enable writing on the new master node externally?

**Comment by migruiz4** [comment]
Hi @adriellcardoso,

Thank you for reporting this issue. Could you please try one additional step?

If I understood correctly, the steps to reproduce the issue are the following:

1. Deploy Redis chart with sentinel enabled
2. Remove the master node.
3. From an external redis-cli pod, attempting to create a new key will raise the error `READONLY You can't write against a read-only replica`
4. When running `kubectl exec` inside the new master node, the redis-cli will succeed in creating the key.

Could you please run an additional step 5, by repeating step 3 again? 

Redis failover is not instant, and it will take some time to detect the master is down (60 seconds by default) and some additional time for the failover to be completed (3 minutes max.).
The objective of repeating this step is to discard 'timing' issues, as it is possible your Redis hadn't chosen yet the new master node by the time you perform the external cli test.

**Comment by adriellcardoso** [comment]
Hi @migruiz4,
I changed some timeout configurations and fixed the problem of the client applications.
Thanks for your support

**Comment by K3ndu** [comment]
> Hi @migruiz4, I changed some timeout configurations and fixed the problem of the client applications. Thanks for your support

That's a lot of help for future, when someone has same problem and stumbles into this ticket.
What did you configure that fixed the problem for you?

**Comment by fmulero** [comment]
Hi Kendi, you can tune sentinel failover timings with these values:
https://github.com/bitnami/charts/blob/eff20e2b8186e7b3592d65a1c8d7c28c8a3e3510/bitnami/redis/values.yaml#L1028-L1042
