### ISSUE TITLE
403 Forbidden while installing any chart

### ISSUE THREAD

**Issue by ardesai** [bitnami/charts#14335]
### Name and Version

bitnami/spark

But seemed to be happening with any charts

### I have added bitnami repo a while back and it was working as expected.
> helm repo list
NAME     	URL                               
bitnami  	https://charts.bitnami.com/bitnami
incubator	https://charts.helm.sh/incubator

### helm install my-release --namespace my-namespace bitnami/spark
**Error: INSTALLATION FAILED: failed to fetch https://charts.bitnami.com/bitnami/spark-6.3.14.tgz : 403 Forbidden**

### Are you using any custom parameters or values?

None

### What is the expected behavior?

Chart installation successful.

### What do you see instead?

**Error: INSTALLATION FAILED: failed to fetch https://charts.bitnami.com/bitnami/spark-6.3.14.tgz : 403 Forbidden**

### Additional information

This used to work for last couple of months until today, it stopped working and started getting 403 Forbidden.
I have removed and added the bitnami repo and got the same result.

**Comment by ardesai** [comment]
Issue with internal proxy in VPC.

**Comment by ThePlenkov** [comment]
Try to use
`dependencies:
  - name: spark
    repository: oci://registry-1.docker.io/bitnamicharts`
