### ISSUE TITLE
[bitnami/postgresql-ha] Postgres-HA replica nodes not starting

### ISSUE THREAD

**Issue by asifsaal** [bitnami/charts#14348]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?
```
helm install Releasename bitnami/postgresql-ha -f values.yaml
```
### Are you using any custom parameters or values?

.

### What is the expected behavior?

All the pods should come up but it goes into crashloopback.

### What do you see instead?

```
INFO: connecting to source node
DETAIL: connection string is: host=test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local port=5432 user=repmgr dbname=repmgr
DETAIL: current installation size is 123 MB
DEBUG: 1 node records returned by source node
DEBUG: connecting to: "user=repmgr password=123456 connect_timeout=30 dbname=repmgr host=test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path="
DEBUG: upstream_node_id determined as 1000
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
WARNING: data checksums are not enabled and "wal_log_hints" is "off"
DETAIL: pg_rewind requires "wal_log_hints" to be enabled
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: -F/--force provided - deleting existing data directory "/bitnami/postgresql/data"
DEBUG: replication slot "repmgr_slot_1001" exists but is inactive; reusing
NOTICE: starting backup (using pg_basebackup)...
INFO: executing:
  /opt/bitnami/postgresql/bin/pg_basebackup -l "repmgr base backup"  -D /bitnami/postgresql/data -h test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local -p 5432 -U repmgr -c fast -X stream -S repmgr_slot_1001
Logs from 1/14/2023, 12:43:48 AM
```
### Additional information

NA

**Comment by asifsaal** [comment]
#values.yaml file as below :
postgresql-repmgr 20:43:48.83 DEBUG ==> Pretending primary set to 'test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'!
postgresql-repmgr 20:43:48.83 DEBUG ==> Checking node 'test-postgresql-ha-postgresql-1.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'...
psql: error: connection to server at "test-postgresql-ha-postgresql-1.test-postgresql-ha-postgresql-headless.test.svc.cluster.local" (10.244.1.85), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
postgresql-repmgr 20:43:48.85 DEBUG ==> Skipping: failed to get primary from the node 'test-postgresql-ha-postgresql-1.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'!
postgresql-repmgr 20:43:48.85 DEBUG ==> Checking node 'test-postgresql-ha-postgresql-2.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'...
psql: error: could not translate host name "test-postgresql-ha-postgresql-2.test-postgresql-ha-postgresql-headless.test.svc.cluster.local" to address: Name or service not known
postgresql-repmgr 20:43:48.89 DEBUG ==> Skipping: failed to get primary from the node 'test-postgresql-ha-postgresql-2.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'!
postgresql-repmgr 20:43:48.89 INFO  ==> Auto-detected primary node: 'test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'
postgresql-repmgr 20:43:48.90 DEBUG ==> Primary node: 'test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'
postgresql-repmgr 20:43:48.91 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 20:43:48.92 DEBUG ==> Injecting a new postgresql.conf file...
postgresql-repmgr 20:43:48.92 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 20:43:49.07 DEBUG ==> Injecting a new pg_hba.conf file...
postgresql-repmgr 20:43:49.09 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 20:43:49.10 DEBUG ==> Node ID: '1001', Rol: 'standby', Primary Node: 'test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432'
postgresql-repmgr 20:43:49.10 INFO  ==> Initializing Repmgr...
postgresql-repmgr 20:43:49.11 INFO  ==> Waiting for primary node...
postgresql-repmgr 20:43:49.11 DEBUG ==> Wait for schema repmgr.repmgr on 'test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local:5432', will try 6 times with 10 delay seconds (TIMEOUT=60)
postgresql-repmgr 20:43:49.16 DEBUG ==> Schema repmgr.repmgr exists!
postgresql-repmgr 20:43:49.17 INFO  ==> Rejoining node...
postgresql-repmgr 20:43:49.17 INFO  ==> Cloning data from primary node...
WARNING: following problems with command line parameters detected:
  -D/--pgdata will be ignored if a repmgr configuration file is provided
NOTICE: destination directory "/bitnami/postgresql/data" provided
INFO: connecting to source node
DETAIL: connection string is: host=test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local port=5432 user=repmgr dbname=repmgr
DETAIL: current installation size is 123 MB
DEBUG: 1 node records returned by source node
DEBUG: connecting to: "user=repmgr password=123456 connect_timeout=30 dbname=repmgr host=test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path="
DEBUG: upstream_node_id determined as 1000
NOTICE: checking for available walsenders on the source node (2 required)
NOTICE: checking replication connections can be made to the source server (2 required)
WARNING: data checksums are not enabled and "wal_log_hints" is "off"
DETAIL: pg_rewind requires "wal_log_hints" to be enabled
WARNING: directory "/bitnami/postgresql/data" exists but is not empty
NOTICE: -F/--force provided - deleting existing data directory "/bitnami/postgresql/data"
DEBUG: replication slot "repmgr_slot_1001" exists but is inactive; reusing
NOTICE: starting backup (using pg_basebackup)...
INFO: executing:
  /opt/bitnami/postgresql/bin/pg_basebackup -l "repmgr base backup"  -D /bitnami/postgresql/data -h test-postgresql-ha-postgresql-0.test-postgresql-ha-postgresql-headless.test.svc.cluster.local -p 5432 -U repmgr -c fast -X stream -S repmgr_slot_1001
Logs from 1/14/2023, 12:43:48 AM

## Continuous Restarts are observed.

**Comment by asifsaal** [comment]
Please Provide some tuning parameters as the cluster is unstable
Maxconnections set to 10000 ( as we are expecting more than 1000 connections , else application doesnt work )

**Comment by javsalgar** [comment]
Hi,

Regarding the tuning parameters for the cluster, please note that we don't provide this kind of professional services. However, we will leave the ticket open in case someone from the community wants to add their own insight.

**Comment by asifsaal** [comment]
Issue has been resolved.

**Comment by zhtaihao** [comment]
> Issue has been resolved.

@asifsaal Could you kindly explain how you approached this? We are currently experiencing the same issue while trying to upgrade from chart 10.0.7 to 10.0.8 or above.

**Comment by asifsaal** [comment]
@zhtaihao Hi , In my case the issue was , if i select storageclass as nfsstorage , we were facing the issue but if chose default storage we didnt find any issue ( as replication manager is continuously synching )
