### ISSUE TITLE
[bitnami/jasperreports] existingClaim is ignored

### ISSUE THREAD

**Issue by rmk135** [bitnami/charts#14352]
### Name and Version

jasperreports/14.3.7

### What steps will reproduce the bug?

1. Deploy a chart with `existingClaim`

### Are you using any custom parameters or values?

```yaml
persistence:
  enabled: true
  existingClaim: <pvc-name>
```

### What is the expected behavior?

Deployment uses provided pvc

### What do you see instead?

Deployment uses standard pvc name

### Additional information

Looks like the issues is here: https://github.com/bitnami/charts/blob/8819180f5376a6dc9f36936aab7e1debb4dbe006/bitnami/jasperreports/templates/deployment.yaml#L200

Chart always use full name instead `existingClaim` if it's provided.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue! Would you like to submit a PR with the fix?
