### ISSUE TITLE
[MongoDB] Standalone Architecture generates TLS certificates with incorrect hostnames

### ISSUE THREAD

**Issue by meln5674** [bitnami/charts#14353]
### Name and Version

bitnami/mongodb 13.6.2

### What steps will reproduce the bug?

1. Enable TLS with the "standalone" architecture
2. Connect to the server using the FQDN (*.svc.cluster.local) for the pod
3. Observe hostname mismatch

### Are you using any custom parameters or values?

```
--set tls.enabled=true
--set useStatefulSet=true # Unsure if this is relevant, but its what I was using
```

### What is the expected behavior?

The generated TLS certificate to be valid for the hostnames the pod is reachable at.

### What do you see instead?

The TLS certificates appear to be valid for a fictitious "mongodb-headless" service which does not exist, and is not created by the chart.

### Additional information

The culprit appears to be [this line](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/standalone/dep-sts.yaml#L154) (compare with [here](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/standalone/svc.yaml#L5)). Either the service.nameOverride should be used to set the service name, or the argument the certificate generation script would be the output of the "mongodb.fullname" helper to match the service name. From looking at the replicaset StatefulSet, the same issue appears to be present, but I have not tested this.

I'm happy to open a PR if you inform me of which of these fixes is the correct one. Using the `service.nameOverride` for the service name "feels" correct, but this could result in breaking changes.

**Comment by migruiz4** [comment]
Hi @meln5674,

Thank you for reporting this issue. The headless service is only created when 'replicaset' architecture is used.
The function `mongodb.service.nameOverride` wasn't considering the standalone case, causing this issue.

I have submitted a PR (https://github.com/bitnami/charts/pull/14424) fixing this issue, adding the following SubjectAltNames to the MongoDB certificate:
```
I have no name!@test-mongodb-0:/$ openssl x509 -noout -ext subjectAltName -in /certs/mongodb.pem 
X509v3 Subject Alternative Name: 
    DNS:test-mongodb, DNS:test-mongodb-0, DNS:test-mongodb.default.svc.cluster.local, DNS:localhost, IP Address:<redacted>, IP Address:127.0.0.1 
```

The DNS names correspond to 1. Service name, 2. Pod name, 3. Long service name, 4. localhost. 
Please notice the FQDN was removed, as non-headless services do not generate the pod's FQDN.
