### ISSUE TITLE
[bitnami/mastodon] problems using tootctl after mastodon install

### ISSUE THREAD

**Issue by digitalbuddha** [bitnami/charts#14369]
### Name and Version

bitnami/mastodon

### What steps will reproduce the bug?

install the chart into k3s

### Are you using any custom parameters or values?

yes but it doesn't matter

### What is the expected behavior?

I should be able to run commands such as the below successfully
```
kubectl -n mastodon exec -it deployment/mastodon-web -- bash
tootctl accounts modify admin --reset-password
```

### What do you see instead?

I get error:

```
/opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client': fe_sendauth: no password supplied (ActiveRecord::ConnectionNotEstablished)
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_handling.rb:283:in `connection'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:553:in `load_schema!'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/attributes.rb:250:in `load_schema!'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:539:in `block in load_schema'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:536:in `synchronize'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:536:in `load_schema'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:402:in `attribute_types'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:428:in `type_for_attribute'
	from /opt/bitnami/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/type_caster/map.rb:16:in `type_for_attribute'
```

I think it is because .env.production does not exist

Documentation says to run:
RAILS_ENV=production bundle exec rake mastodon:setup but that wants me to reset env variables. 

Would appreciate a pointer on how to proceed, tootctl is used to run cleanup tasks

**Comment by digitalbuddha** [comment]
Update:
I tried to run a shell and run the above command but got a permission error as it was unable to save the .env.production file in the opt/bitnami/mastodon dir. 


As a note the official chart has a cron template for tootctl remove media. Maybe you can add similar to this chart? 

https://github.com/mastodon/chart/blob/main/templates/cronjob-media-remove.yaml

Overall it would be nice to figure out how to run tootctl but a cron job around key functionality could be a good stop gap

**Comment by digitalbuddha** [comment]
I got a permission denied.

Steps I took

kubectl exec -it mypod bash
I then run the script and get an error

bash: /opt/bitnami/scripts/mastodon-env.sh: Permission denied

ls -la /opt/bitnami/scripts/mastodon-env.sh
-rw-r--r--. 1 root root 10845 Dec 16 13:40 /opt/bitnami/scripts/mastodon-env.sh

is there a way to run as root? 
I tried to chmod but also got error
chmod: changing permissions of './opt/bitnami/scripts/mastodon-env.sh': Operation not permitted

Thank you for your help

**Comment by digitalbuddha** [comment]
for anyone else hitting this issue, here is what to run after connecting to your mastodon web pod

```
    set -o errexit
    set -o nounset
    set -o pipefail
    # Load libraries
    . /opt/bitnami/scripts/liblog.sh
    . /opt/bitnami/scripts/libos.sh
    . /opt/bitnami/scripts/libvalidations.sh
    . /opt/bitnami/scripts/libmastodon.sh
    # Load Mastodon environment variables
    . /opt/bitnami/scripts/mastodon-env.sh
```

Once you run that you will be able to run tootctl without issue

**Comment by ElanHasson** [comment]
This should not be this much work...

**Comment by huang-jy** [comment]
> This should not be this much work...

I agree, but I'll happily that a chart where I have to jump through a few hoops to get things working, over a chart that doesn't work, ever.

**Comment by robertbovens** [comment]
Well to be hones it still doesnt work. I tried for 3 days to see what the problem is.

Running tootctl still gives no password for postgres found. The beginning of the web pod states:
sed: can't read /opt/bitnami/mastodon/.env.production: No such file or directory

I have disabled all things because i had problems with running the chart, i dont see any images within the posts so started to disabled all stuff and the i saw that the env file is missing. I had elasticsearch installed but it said i needed to update the indexes, so i tried to rund also the tootctl command with again the same issue, no password found for postgres so then i started to disable all the fancy stuff, now i just have the basis running like external postgres, no s3, i thought there was a problem with s3 because i couldnt see the images in the posts, i have an other mastrodon running on other vm and it works great, no problems but version is 4.2.8

**Comment by robertbovens** [comment]
By the way if i run
    set -o errexit
    set -o nounset
    set -o pipefail
    # Load libraries
    . /opt/bitnami/scripts/liblog.sh
    . /opt/bitnami/scripts/libos.sh
    . /opt/bitnami/scripts/libvalidations.sh
    . /opt/bitnami/scripts/libmastodon.sh
    # Load Mastodon environment variables
    . /opt/bitnami/scripts/mastodon-env.sh

tootctl works, but after reboot the info is lost so it seems the problem is with the env file
