### ISSUE TITLE
[bitnami/rabbitmq] Set ssl_options.password via Secret

### ISSUE THREAD

**Issue by hgm-kklingspor** [bitnami/charts#14373]
### Name and Version

bitnami/rabbitmq 11.4.0

### What is the problem this feature will solve?

If private keys ar protected by a password, the password can only be set via `ssl_options.password` (see: [Rabbitmq Documentation /TLS Support / Providing Private Key Password](https://www.rabbitmq.com/ssl.html#private-key-passwords))

Currently the only option is to provide the password via `.Values.extraConfiguration` which results in providing a secret-Password in a possibly versioncontrolled override-values-file.

### What is the feature you are proposing to solve the problem?

Make it possible to set the `ssl_options.password` with a value from an existing secret. Set the secretName via the values.yaml.
Maybe as:

```
auth:
  tls:
    sslOptionsPasswordSecret:""
```

### What alternatives have you considered?

Injecting the password as environment-variable. But I am not sure, wether variable-expansion is possible within the rabbitmq.conf

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the suggestion. Would you like to create a PR adding support to this? Maybe it could also make sense to allow the full configuration to be set as an external secret. This could help your use case.

**Comment by hgm-kklingspor** [comment]
Hi,

I could try to contribute, but I never done this before so the process is unclear to me.

What do you mean with "full configuration". Do you mean the "TLS Upport" as own config-snippet(which then could be included, like .Values.extraConfiguration) or the whole rabbitmq.conf?

**Comment by javsalgar** [comment]
I meant that the `.Values.configuration` and `.Values.extraConfiguration` don't allow using an external secret and I think it makes sense to allow it. So yes, I meant the whole section.

**Comment by hgm-kklingspor** [comment]
I suppose that change should then be a separate Feature-Request.

I first try to contribute to this issue. Maybe we can just copy the function of ```advancedConfigurationExistingSecret```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
