### ISSUE TITLE
Please create helm chart for karma

### ISSUE THREAD

**Issue by patsevanton** [bitnami/charts#14372]
### Name and Version

https://github.com/prymitive/karma v0.111

### What is the problem this feature will solve?

Will be karma helm chart

### What is the feature you are proposing to solve the problem?

Don`t have good helm chart for karma. Thanks!

**Comment by javsalgar** [comment]
Thank you so much for the request! I will forward this for evaluation.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
