### ISSUE TITLE
Harbor field extraEnvVarsSecret not mounted on exporter

### ISSUE THREAD

**Issue by sebglon** [bitnami/charts#14379]
### Name and Version

bitnami/harbor 16.2.0

### What steps will reproduce the bug?

try to add extra secret with the field: `expoter.extraEnvVarsSecret`

### Are you using any custom parameters or values?

no custom

### What is the expected behavior?

The field expoter.extraEnvVarsSecret is not used on the deployment: https://github.com/bitnami/charts/blob/0ab760862c660fcc78cffadf8e1d8cdd70881473/bitnami/harbor/templates/exporter/exporter-dpl.yaml#L113

Values:
https://github.com/bitnami/charts/blob/b95989761f3feccc073f6739d4df62bf59ae34b7/bitnami/harbor/values.yaml#L3476

### What do you see instead?

The secret is not mounted

### Additional information

Example on the core component: https://github.com/bitnami/charts/blob/0ab760862c660fcc78cffadf8e1d8cdd70881473/bitnami/harbor/templates/core/core-dpl.yaml#L138

**Comment by carrodher** [comment]
Thanks for this issue and the associated PR, the team will review it and provide feedback
