### ISSUE TITLE
[bitnami/apache]Cant mount static conf with configmap to /app, rm: cannot remove '/opt/bitnami/apache/htdocs/index.html': Permission denied 

### ISSUE THREAD

**Issue by whall89** [bitnami/charts#1440]
**Which chart**:

bitnami/apache-7.0.1

**Description**

I am unable to load static content/custom .html file in AWS EKS kubernetes 1.13 from configmap, I receive the following error upon startup
apache_1  | apache 19:36:09.15 INFO  ==> ** Starting Apache setup **
apache_1  | apache 19:36:09.18 INFO  ==> Mounting application files from '/app'...
apache_1  | rm: cannot remove '/opt/bitnami/apache/htdocs/index.html': Permission denied

I am able to load a custom vhost config via configmap without issue

I have tried to load the index.html configmap with a custom vhost configmap and with just the htdocs configmap index.html alone. Both result in the same error:
rm: cannot remove '/opt/bitnami/apache/htdocs/index.html': Permission denied
[apache-test02-configmap.yaml.txt](https://github.com/bitnami/charts/files/3659069/apache-test02-configmap.yaml.txt)

**Steps to reproduce the issue:**
I am a cluster-admin so my user doesn't have any permission restrictions

1. I create the configmap with simple a simple index.html as the data in the default namespace
[apache-test01-configmap.yaml.txt](https://github.com/bitnami/charts/files/3659016/apache-test01-configmap.yaml.txt)

2. kubectl apply -f apache-test01-configmap.yaml
[apache-values.yaml.txt](https://github.com/bitnami/charts/files/3659053/apache-values.yaml.txt)

3. helm install --name apache-test01 bitnami/apache -f apache-values.yaml

4. Look at the logs why the pod is in a CrashLoopBackOff not starting

**Describe the results you received:**

The following logs is all that is outputted
apache_1  | apache 23:11:46.90 INFO  ==> ** Starting Apache setup **
apache_1  | apache 23:11:46.92 INFO  ==> Mounting application files from '/app'...
apache_1  | rm: cannot remove '/opt/bitnami/apache/htdocs/index.html': Permission denied

**Describe the results you expected:**
If i run the chart without specifying any htdocs options the pod starts up and starts to serve the default "IT WORKS" message in a web browser

**Version of Helm and Kubernetes**:

- Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Comment by alemorcuq** [comment]
Hi, @whall89.

Can you try using version `7.0.2` of the chart? [This issue was reported yesterday](https://github.com/bitnami/bitnami-docker-apache/issues/95) and fixed on a new release of the containers. The image `bitnami/apache:2.4.41-debian-9-r49` has the fix, and it is the default for version `7.0.2`.

Let me know how it goes.

Regards,
Alejandro

**Comment by whall89** [comment]
Great I just upgraded and now it works.

Thanks

**Comment by whall89** [comment]
closing issue
