### ISSUE TITLE
[bitnami/template] Enabling PodDisruptionBudget requires setting .Values.replicaCount > 1, even if using HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by Lance-Drane** [bitnami/charts#14407]
### Name and Version

bitnami/template

### What steps will reproduce the bug?

1. Clone repository
2. Under `template/CHART_NAME`, replace all placeholder markers (i.e. `%%COMPONENT_NAME%%`) with valid variables to enable Helm templating. You can remove things such as the subchart template in `Chart.yaml` .
3. Run `helm dependency update template/CHART_NAME`
4. Run `helm template template/CHART_NAME --set pdb.create=true --set autoscaling.enabled=true`, you can see that the PodDisruptionBudget will not be applied
5. Run `helm template template/CHART_NAME --set pdb.create=true --set autoscaling.enabled=true --set replicaCount=2` (replicaCount can have any value greater than 1), the PodDisruptionBudget template will be created.

### Are you using any custom parameters or values?

pdb.create = true
autoscaling.enabled = true
replicaCount = 2 (this should _not_ need to be set)

### What is the expected behavior?

If I set `.Values.autoscaling.enabled = true` and `.Values.pdb.create = true`, I should be able to template a PodDisruptionBudget YAML generated, without touching `.Values.replicaCount` . HorizontalPodAutoscaler users should not need to care about this value.

If `.Values.autoscaling.enabled = false`, then in order to generate the PDB YAML I should have to set _both_ `.Values.pdb.create = true` and `.Values.replicaCount = {{ some integer > 1 }}`

### What do you see instead?

No PodDisruptionBudget generated in Helm templating.

### Additional information

There are two areas `.Values.replicaCount` will be used:

1) Using logic from `template/CHART_NAME/templates/deployment.yaml` and `template/CHART_NAME/templates/statefulset.yaml`, replicas are only set if autoscaling is not enabled. This is expected behavior.

2) In `template/CHART_NAME/templates/pdb.yaml`, the logic is checking for both `.Values.pdb.create = true` and `gt .Values.replicaCount 1` . The replicaCount size check should be skipped if `.Values.autoscaling.enabled = true`

Possible fix to be applied in `pdb.yaml`:

```
{{- if and .Values.pdb.create (or (gt $replicaCount 1) .Values.autoscaling.enabled) }}
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input! Would you like to submit a PR fixing the template?

**Comment by Lance-Drane** [comment]
Sure I'd be happy to!

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
