### ISSUE TITLE
[bitnami/harbor] JobService multi-attach RWO volume or stuck with RollingUpdate with replicaCount == 1

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/charts#14416]
### Name and Version

bitnami/harbor >= 16.2.0

### What steps will reproduce the bug?

Use bitnami/harbor >= 16.2.0

### What do you see instead?

After https://github.com/bitnami/charts/pull/14128 RWO scanData volume appeared in JobService Deployment. So on replicaCount > 1 there is Volume multiAttach problem. On replica == 1 there is updateStrategy: Recreate needed which is not by default.

**Comment by Mauraza** [comment]
Hi @Antiarchitect,

I just try bitnami/harbor: 16.3.0 with `helm install harbor bitnami/harbor --set jobservice.replicaCount=2` and everything works well. 
Could you add more information to try to reproduce de issue?

**Comment by Antiarchitect** [comment]
Hi @Mauraza,
What storageClass do you have by default in your cluster? I just did:

```
helm --debug --namespace harbor-test install harbor bitnami/harbor --set jobservice.replicaCount=2 --set global.storageClass=core-rook-block --create-namespace
```

Where core-rook-block is the class for RWO Rook RBD backed by Ceph (which I think doesn't matter - It's enogh it's not ephemeral or something) and seeing this picture:

![image](https://user-images.githubusercontent.com/50209/213484808-df7c264b-62e5-419f-9300-0ec581dd4e4e.png)

```
Events:
  Type     Reason              Age    From                     Message
  ----     ------              ----   ----                     -------
  Normal   Scheduled           3m23s  default-scheduler        Successfully assigned harbor-test/harbor-jobservice-69bf6f4498-h7qvx to worker-1.prod.xxx.xxx
  Warning  FailedAttachVolume  3m23s  attachdetach-controller  Multi-Attach error for volume "pvc-b90ee82e-df36-4a18-ab35-21643ae41881" Volume is already used by pod(s) harbor-jobservice-69bf6f4498-k4glv
  Warning  FailedAttachVolume  3m23s  attachdetach-controller  Multi-Attach error for volume "pvc-b0e08ded-bbf2-4130-8cb2-fa2cb6f82d82" Volume is already used by pod(s) harbor-jobservice-69bf6f4498-k4glv
  Warning  FailedMount         80s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[jobservice-scandata job-lgs[], unattached volumes=[jobservice-scandata jobservice-config job-logs]: timed out waiting for the condition
```

**Comment by Antiarchitect** [comment]
Also I'm interested in the jobService concept?
Can/should I scale jobservice by increasing replicaCount for jobservice deployment?
If not, like in thanos/compactor case why it's a deployment and not statefulset with replicaCount == 1 anyway.
If yes and it's horizontally scalable thing what about scanData should it be RWM shared storage like NFS or it's good to have N separate RWO volumes for each instance of jobservice (and why in this case it's a deployment and not statefulset?)

**Comment by Mauraza** [comment]
Hi @Antiarchitect,

Could you add the output of `kubectl describe pvc -n harbor-test harbor-jobservice-scandata`?

> According to this chart and the official harbor chart jobservice is a a variant of singleton app pattern which is non-scalable deployment with manually created RWO PVC. Which points that updateStrategy should be Recreate by default like for https://github.com/bitnami/charts/blob/main/bitnami/thanos/values.yaml#L1683

I just check the chart of the harbor and appear this:
```
# The update strategy for deployments with persistent volumes(jobservice, registry
# and chartmuseum): "RollingUpdate" or "Recreate"
# Set it as "Recreate" when "RWM" for volumes isn't supported
updateStrategy:
  type: RollingUpdate
```
That appears in the [README.md](https://github.com/bitnami/charts/tree/main/bitnami/harbor#harbor-exporter-parameters)

**Comment by Antiarchitect** [comment]
@Mauraza,

```
Name:          harbor-jobservice-scandata
Namespace:     harbor-test
StorageClass:  core-rook-block
Status:        Bound
Volume:        pvc-3511aff4-e3a6-4f4c-ae7a-dbd743fb0061
Labels:        app.kubernetes.io/component=jobservice
               app.kubernetes.io/instance=harbor
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=harbor
               helm.sh/chart=harbor-16.3.0
Annotations:   helm.sh/resource-policy: keep
               meta.helm.sh/release-name: harbor
               meta.helm.sh/release-namespace: harbor-test
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: core-rook.rbd.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: core-rook.rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       harbor-jobservice-c8dd6f748-mfj7m
               harbor-jobservice-c8dd6f748-sxp78
Events:
  Type    Reason                 Age                From                                                                                                        Message
  ----    ------                 ----               ----                                                                                                        -------
  Normal  ExternalProvisioning   69s (x2 over 69s)  persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "core-rook.rbd.csi.ceph.com" or manually created by system administrator
  Normal  Provisioning           69s                core-rook.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6894c9ddf4-jg5qg_c5eded1f-ac42-4081-a683-9ffedfeb5fc2  External provisioner is provisioning volume for claim "harbor-test/harbor-jobservice-scandata"
  Normal  ProvisioningSucceeded  69s                core-rook.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6894c9ddf4-jg5qg_c5eded1f-ac42-4081-a683-9ffedfeb5fc2  Successfully provisioned volume pvc-3511aff4-e3a6-4f4c-ae7a-dbd743fb0061
```

**Comment by Mauraza** [comment]
Hi @Antiarchitect,

Could you check the `harbor-jobservice-config`? it seems that is another unable to attach or mount volumes

**Comment by Antiarchitect** [comment]
Hi @Mauraza What K8s object type do you mean by harbor-jobservice-config. Among PVCs related I have only `harbor-jobservice` and `harbor-jobservice-scandata`

**Comment by Mauraza** [comment]
Hi @Antiarchitect,

Sorry, it was `job-lgs`.
Did you try to increase the replicaCount to another deployment? It seems related to your persistence.
