### ISSUE TITLE
[bitnami/wordpress] Cannot change updateStrategy to Recreate

### ISSUE THREAD

**Issue by dostalradim** [bitnami/charts#14417]
### Name and Version

bitnami/wordpress 15.2.28

### What steps will reproduce the bug?

Kubernetes version 1.24. Wordpress helm chart version 15.2.28. We can not set _updateStrategy_ to _Recreate_ because the helm chart always put there rollingUpdate property and the Kubernetes return following error. The rolligUpdate property is set in default values.yaml and is always set.

### What do you see instead?

Error output:
```
$ helm upgrade -f values.yaml --create-namespace -n wordpress-hospody hospody bitnami/wordpress
Error: UPGRADE FAILED: cannot patch "wordpress-hospody" with kind Deployment: Deployment.apps "wordpress-hospody" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

With dry-run:
```
$ helm upgrade --dry-run -f values.yaml --create-namespace -n wordpress-hospody hospody bitnami/wordpress
---TRUNCATED---
  strategy:
    rollingUpdate: {}
    type: Recreate
---TRUNCATED---
```

**Comment by javsalgar** [comment]
Hi!

Could you try this comment from another ticket? https://github.com/bitnami/charts/issues/8961#issuecomment-1034866839

**Comment by dostalradim** [comment]
It is working! I am sorry, I miss that ticket. Thank you
