### ISSUE TITLE
[bitnami/elasticsearch] exporter arguments

### ISSUE THREAD

**Issue by hawksight** [bitnami/charts#1443]
**Which chart**:

bitnami/elasticsearch 6.3.7

**Description**

(sorry i opened this by mistake before completing)
After upgrading to this version of the chart, from a much older version (4.X), I was having issues with the metrics component of the chart. I looks like the arguments being passed did not match up with what the application expected.

I had two issues:
1) I needed to pass `--` instead of just `-`
1) Also the second argument apparently does not take a value, it acts as a command line flag. `-es.all=true` should be `--es.all`.

The correct args should look something like this in the deployment:

```yaml
      - args:
        - --es.uri=http://es-elasticsearch-coordinating-only:9200
        - --es.all
```

Or something like this in the template:

```yaml
args: [ "--es.uri=http://{{ template "elasticsearch.coordinating.fullname" . }}:{{ .Values.coordinating.service.port }}", "--es.all" ]
```

**Steps to reproduce the issue:**

1. Install latest version of chart (6.3.7) with metrics enabled.
2. Check logs on the metrics component once install completes.

**Describe the results you received:**

Pod wouldn't start with error message:

```
elasticsearch_exporter: error: unknown short flag '-e', try --help
```

Once I changed to use `--` on the args, I then got this:

```
elasticsearch_exporter: error: unexpected true, try --help
```

So I removed the `=true` part.

**Describe the results you expected:**

To work with the args in the manifest [here](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/metrics-deploy.yaml#L36)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:21:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.1", GitCommit:"61c30f98599ad5309185df308962054d9670bafa", GitTreeState:"clean", BuildDate:"2019-08-28T11:06:42Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Also apologies, I would submit a PR, but I couldn't see any contribution guideline.

**Comment by alemorcuq** [comment]
Hi, @hawksight.

You are completely right. I'm going to make a PR fixing this, thank you very much for your report. 

As for contributing, just make a PR with your changes. You will see a template with a checklist with some items that must be done (like increasing the Chart version or making sure new variables are documented).

Regards,
Alejandro

**Comment by ntavares** [comment]
Hi @alemorcuq the documentation still mentions to use the true/false values:
https://github.com/prometheus-community/elasticsearch_exporter#configuration

**Comment by mmosierteamvelocity** [comment]
@ntavares
Did you get this figured out? I am trying to add the other exporter flags and the pod either starts crashing or does not start.

**Comment by mmosierteamvelocity** [comment]
Was trying to add mine like this:

extraArgs: 
    ##- --es.indices
    - --es.indices_settings
    - --es.indices_mappings
    - --es.aliases
    - --es.shards
    - --es.slm
    - --es.data_stream

**Comment by mmosierteamvelocity** [comment]
The exporter is not pushing data to the grafana dashboard and I believe this is the reason.

**Comment by mmosierteamvelocity** [comment]
I can see it uses some of the flags

`args:
            {{- $protocol := (ternary "https" "http" (and .Values.security.enabled .Values.security.tls.restEncryption)) }}
            - --es.uri={{$protocol}}://{{ include "common.names.fullname" . }}:{{ include "elasticsearch.service.ports.restAPI" . }}
            - --es.all
            {{- if .Values.security.tls.restEncryption }}
            - --es.ssl-skip-verify
            {{- end }}
            {{- if .Values.metrics.extraArgs }}
            {{- include "common.tplvalues.render" (dict "value" .Values.metrics.extraArgs "context" $) | nindent 12 }}
            {{- end }}
          {{- end }}`
