### ISSUE TITLE
[bitnami/rabbitmq] Set configuration and extraConfiguration as Secret

### ISSUE THREAD

**Issue by hgm-kklingspor** [bitnami/charts#14444]
### Name and Version

bitnami/rabbitmq 11.4.0

### What is the problem this feature will solve?

Currently, `.Values.configuration` and `.Values.extraConfiguration` can only be directly set in the values.yaml
Therefore secure configuration information is currently available in possibly versionControlled values-files.

### What is the feature you are proposing to solve the problem?

Leave the user a choice of being able to preconfigure a secret, which then is loaded as configuration/extraConfiguration. Similar to `advancedConfiguration` and `advancedConfigurationExistingSecret`

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR adding the feature?
