### ISSUE TITLE
[bitnami/redis] Error: parse error at (redis/charts/common/templates/_secrets.tpl:84): function "lookup" not defined

### ISSUE THREAD

**Issue by rajivmishra-123** [bitnami/charts#14449]
### Name and Version

bitnami/redis , latest

### What steps will reproduce the bug?

helm install redis redis
kubernetes version = 1.17
helm version=3.5.2

### What is the expected behavior?

helm chart should run sucessfully as my helm version is above 3.3 .

### What do you see instead?

chart is not installing with given error
![Screenshot from 2023-01-19 16-30-24](https://user-images.githubusercontent.com/68244292/213425496-61382b55-b5f5-4f8e-8d3d-65cfe88fc1d4.png)

**Comment by javsalgar** [comment]
Hi,

Could you update your helm client to a later version? This should fix the lookup issue.
