### ISSUE TITLE
[bitnami/redis] helm chart is not installed when passing kubeconfig parameter

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#14446]
### Name and Version

bitnami/redis , latest

### What steps will reproduce the bug?

helm install redis redis --kubeconfig=path

### What is the expected behavior?

i have 2 kubeconfig files , so i want to specify my kubeconfig file path in helm installation step. and then i expect chart to be installed.

### What do you see instead?

commands run fine without any error but nothing is created nor chart is installed .

**Comment by javsalgar** [comment]
Hi,

This seems to be an issue in helm rather than the Bitnami Redis Helm chart instead. Did you check with the helm developers?
