### ISSUE TITLE
[bitnami/postgresql-ha] Connection to Postgresql Ha from Spring Boot App

### ISSUE THREAD

**Issue by mertcakmak2** [bitnami/charts#14453]
### Name and Version

bitnami/postgresql-ha

helm version: v3.9.3
chart: postgresql-ha-10.0.9
app version: 15.1.0

### What steps will reproduce the bug?

helm install my-release my-repo/postgresql-ha --set global.storageClass=standard,postgresql.replicaCount=4

I want connect to postgresql ha cluster from my spring boot app. but how to decide to database connection string?

![image](https://user-images.githubusercontent.com/21373505/213460120-c59aab49-8788-4b9e-8e72-e50501b95960.png)

My primary node is my-release-postgresql-ha-postgresql-1

![image](https://user-images.githubusercontent.com/21373505/213460323-81a074f1-e2b7-4957-8504-5fde6095d039.png)

My connection string is "jdbc:postgresql://my-release-postgresql-ha-postgresql-1.my-release-postgresql-ha-postgresql-headless:5432/postgres"

![image](https://user-images.githubusercontent.com/21373505/213460429-e0e862cd-0f9b-4b21-968b-85f3310ccff7.png)

1) Do i have to change my connection string if my primary node(my-release-postgresql-ha-postgresql-1)  is down?

2) My project is connected the my-release-postgresql-ha-postgresql-1 pod. Is PostgreSql behavior as load balancer ?

3) Do i have to connect  with pod name? Why my app doesn't write or update to db when connect with the service name?  
Like my-release-postgresql-ha-pgpool, my-release-postgresql-ha-postgresql or my-release-postgresql-ha-postgresql-headless

### Are you using any custom parameters or values?

global.storageClass=standard
postgresql.replicaCount=4

### What do you see instead?

Nothing

**Comment by javsalgar** [comment]
Hi,

For load balancing, you should use the pgpool connection instead. This component should redirect the load to the proper instance.

**Comment by mertcakmak2** [comment]
Hi, 

It is works. Thanks for solution.
