### ISSUE TITLE
bitnami/mongodb

### ISSUE THREAD

**Issue by JoemonChittilapilly** [bitnami/charts#14464]
### Name and Version

current version

### What steps will reproduce the bug?

While creating The MongoDB Helm chart there are three replica sets as given in the _values.yaml_, how will it automatically creates a persistent volume for 3 replicas automatically.
Can you point out which part of the code if is implemented

**Comment by carrodher** [comment]
The definition of the replicaset can be found at https://github.com/bitnami/charts/tree/main/bitnami/mongodb/templates/replicaset, there you can find a template for the statefulset where the number of replicas is set.

**Comment by JoemonChittilapilly** [comment]
i am asking how are you making persistent volume for each replica

**Comment by rafariossaa** [comment]
Hi,
 Not sure what are you looking for exactly. [The volumen claims are in the statefulset definition](https://github.com/bitnami/charts/blob/6df6d9bb5db42eaf45e5abf96a91ec176afe97e5/bitnami/mongodb/templates/replicaset/statefulset.yaml#L537).
