### ISSUE TITLE
[bitnami/jenkins] jenkins logs are not stored inside the container

### ISSUE THREAD

**Issue by rajivmishra-123** [bitnami/charts#14461]
### Name and Version

bitnami/jenkins, latest

### What steps will reproduce the bug?

helm install jenkins jenkins

### What is the expected behavior?

i want to persist my jenkins logs on disk . so i want my logs inside container so that i can persist them . but i could not find any option to set the logs path inside container . also could not find any logs inside container at any path.

### What do you see instead?

default directory - /opt/bitnami/jenkins/logs also does not contain any logs of jenkins.

**Comment by javsalgar** [comment]
Hi,

By default, our containers put all the logs in /dev/stdout following the 12 factor container principles. In order to fetch the logs of the pods, you can use solutions like the EFK stack or the LGTM stack.

**Comment by abhishekgupta2205** [comment]
i want to persist my logs . is there any way i can persisst them

**Comment by javsalgar** [comment]
Hi,

You may try to mount a volume in the logs folder using the `extraVolumes` and `extraVolumeMounts` sections, but I'm not sure if that would be enough. Could you detail your use case?

**Comment by abhishekgupta2205** [comment]
@javsalgar i want to know the property through which i can get my logs inside of container . as they are not present in /opt/bitname/jenkins/logs directory . so i need those logs inside container so that i can mount them

**Comment by javsalgar** [comment]
Yes, but could you explain the reasoning why you need to mount the logs and other solutions like EFK or LGTM stacks would not apply?
