### ISSUE TITLE
Use different labels 

### ISSUE THREAD

**Issue by alexppg** [bitnami/charts#1447]
**Which chart**:
Kafka. Latest.

**Description**

The helm chart sets some labels that are like `app.kubernetes.io/component` or `app.kubernetes.io/component`. All the labels begin with `app`. 

This is a problem because it collisions with the default behaviour of filebeat. By default in ES you have a `kubernetes.labels.app` label. Since this helm chart uses it, ES has a mapping problem and stops receiving logs. 

**Proposed soultion**
Change the labels from app to `app.kubernetes.io/component` to just `kubernetes.io/component`, for example.

**Comment by javsalgar** [comment]
Hi,

I'm afraid I didn't fully understand the issue. I see that, in Elasticsearch, we didn't update the labels to match the recommended kubernetes ones. We are waiting because changing labels requires a major bump in the chart version. Would the issue be solved if we changed the labels in Elasticsearch to app.kubernetes.io/component and the others?

**Comment by alexppg** [comment]
Mmm, I don't think so, let me try to be more clear.

The kafka chart has the mentioned labels, `app.kubernetes.io/*`. Filebeat reads all kubernetes's logs and the [kubernetes plugin](https://www.elastic.co/guide/en/beats/filebeat/master/add-kubernetes-metadata.html) adds some metadata to all the documents indexed in the ES read from the containers, being that pod name, namespace or labels. The way it does it is adding the a prefix `kubernetes` to all this metadata.

So we have the next created mappings in ES:
- `kubernetes.pod.name` string
- `kubernetes.app` string
- `kubernetes.pod.namespace` string

`app` is a widely used label in kubernetes, so is very probable to exist. So the problem begins when in ES there's, indeed, an existing mapping called `kubernetes.app` with the type string. When deploying kafka to k8s, filebeat will try to create a mapping called `kubernetes.app.kubernetes.io/*`, but it won't, since `kubernetes.app` will already exist. 

Your proposed solution of changing the mappings in ES does solve the issue, but I don't thing that should be done. I think the good way but use at least one of the next:
- Use more customized labels
- Don't use dictionaries to label stuff
- Make the labels customizable

I wish I explained better myself.

**Comment by javsalgar** [comment]
Hi,

My opinion is that the chart should follow the Helm and Kubernetes labelling conventions so it works. Down the line, we will unify the labels of all the charts so they follow the recommended naming. About using customized labels, that's would be something a bit complicated but doable in the future when all of our charts use the helper function `NAME_OF_THE_CHART.labels` (example: https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/_helpers.tpl#L178). That way, you could create an umbrella chart and overwrite that helper function. I'm not convinced about moving the labels to the values.yaml, as I'm not sure how common your use case is.
