### ISSUE TITLE
[bitnami/kafka] Rack Awareness for AWS multiple availability zones.

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#14495]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

Hi Team,

We have 8 node EKS Kubernates cluster with availability zones(us-east-2b 4nodes & us-east-2c 4 nodes), We have to deploy Kafka with 10 pods each availability zone with 5 pods. 

I could see below configuration in helm charts. Please let me know how to configure rackawaress for Kafka helm charts..

```
brokerRackAssignment: ""
```

Thanks

### What do you see instead?

Hi Team,

We have 8 node EKS Kubernates cluster with availability zones(us-east-2b 4nodes & us-east-2c 4 nodes), We have to deploy Kafka with 10 pods each availability zone with 5 pods. 

I could see below configuration in helm charts. Please let me know how to configure rackawaress for Kafka helm charts..

```
brokerRackAssignment: ""
```

Thanks

**Comment by javsalgar** [comment]
Hi,

The brokerRackAssignment value currently supports `aws-az`, which performs this operation

```
    {{- if eq .Values.brokerRackAssignment "aws-az" }}
    export KAFKA_CFG_BROKER_RACK=$(curl "http://169.254.169.254/latest/meta-data/placement/availability-zone-id")
    {{- end }}
```

This sets the `broker.rack` setting in kafka

https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#broker-rack

That means that each node will get its rack assigned based on the availability zone.

**Comment by bharathreddy901** [comment]
Hi @javsalgar - In which file we need to update above values and you are referring to export for IP Address. Please clarify.

export KAFKA_CFG_BROKER_RACK=$(curl "http://169.254.169.254/latest/meta-data/placement/availability-zone-id")

**Comment by javsalgar** [comment]
Hi,

This is done automatically, so you wouldn't need to do anything and the configuration files should already show the proper value.

**Comment by bharathreddy901** [comment]
Thanks @javsalgar for your inputs. Its working as expected.

**Comment by javsalgar** [comment]
Thanks for letting us know!
