### ISSUE TITLE
unable to scale jenkins pod 

### ISSUE THREAD

**Issue by rajivmishra-123** [bitnami/charts#14496]
### Name and Version

bitnami/jenkins, latest

### What steps will reproduce the bug?

`helm install jenkins jenkins`

### What is the expected behavior?

By default, it only creates 1 pod; but I want to increase no of pods so that I can achieve master-slave architecture. But can not find any way to do that.

### What do you see instead?

No options for scaling are provided

**Comment by migruiz4** [comment]
Hi @abhishekgupta2205,

We are currently working on a new major of the `bitnami/jenkins` chart (https://github.com/bitnami/charts/pull/14541), which will include new features including configuration-as-code support and Kubernetes agents.
