### ISSUE TITLE
[bitnami/apache] allow custom httpd.conf with configmap

### ISSUE THREAD

**Issue by whall89** [bitnami/charts#1449]
**Which chart**:

[bitnami/apache] 7.0.2

**Description**

Add a feature to allow the custom httpd.conf to allow a configmap with apache conf file httpd.conf to be mounted to /opt/bitnami/apache/conf/httpd.conf
This feature already exists and is working in the parent docker image
https://github.com/bitnami/bitnami-docker-apache#full-configuration

**Comment by alemorcuq** [comment]
That's actually a good idea, @whall89. Are you interested in making a PR? Nevertheless, I've created an internal task for this feature.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
We implemented this feature, @whall89. You can try it now with version`7.1.0`.

**Comment by whall89** [comment]
Great thanks, I was able to test and this works for me now.

**Comment by alemorcuq** [comment]
Glad it works, @whall89 ! Don't hesitate to open another ticket if you think some feature could improve the chart.

**Comment by cfarre** [comment]
can you tell how to pass the httpd.conf through a config map? i tried the following steps
1. create a config map from the file
kubectl create configmap httpdconfig --from-file=httpd.conf 
2. start helm chart passing the right param
helm install apache bitnami-azure/apache \
--set image.registry=marketplace.azurecr.io \
--set image.repository=bitnami/apache \
--set image.tag=2.4.41-debian-10-r53 \
--set service.type=LoadBalancer \
--set fullnameOverride=apache \
--set httpdConfConfigMap=httpdconfig

apache is throwing the below error
 Error: failed to start container "apache": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/1daa1c33-b1cd-400c-9067-29dcd8b77cf0/volume-subpaths/httpd-conf/apache/0\\\" to rootfs \\\"/var/lib/docker/overlay2/022d50e0babcf1d74607472467d2a0fddd3736e78ff6331049962d17ca7a371a/merged\\\" at \\\"/var/lib/docker/overlay2/022d50e0babcf1d74607472467d2a0fddd3736e78ff6331049962d17ca7a371a/merged/opt/bitnami/apache/conf/httpd.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by marcosbc** [comment]
@cfarre Make sure to execute the command "kubectl create configmap" from the same directory where you included the file "httpd.conf". It must have that exact file name.

Could you check if the "httpd.conf" entry appears when you run the command below?

```
kubectl describe configmap httpdconfig
```

I was able to get it working without issues. When I exec'd into the container I was able to verify that a custom line had been properly added. The outputs of the previous command on my side are:

```
Name:         httpdconfig
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
httpd.conf:
----
#
# This is the main Apache HTTP server configuration file.  It contains the
...
<IfModule mod_headers.c>
  RequestHeader unset Proxy
</IfModule>
# my custom file
```

**Comment by mlk-bit** [comment]
I get the same error as @cfarre...  I have a valid configmap.   "kubectl describe configmap httpdconfig" displays the contents correctly.   Any other ideas as to why it won't mount.

**Comment by mlk-bit** [comment]
resolved..  I realized I was passing into the configmap a different file name.  Changed the file name to "httpd.conf" and all works correctly now..
