### ISSUE TITLE
[bitnami/harbor] Repositories are not created or shown in the harbor UI while storage use shows that images were downloaded.

### ISSUE THREAD

**Issue by sio-codefresh** [bitnami/charts#14503]
### Name and Version

bitnami/harbor 16.3.1

### What steps will reproduce the bug?

* Install with Helm
* Create registry(cache proxy) and project
* Create Robot User
* Login and pull images from harbor

### What is the expected behavior?

Each time an image is pulled via harbor, a repository (or just a tag in  an existing repository) should be created and shown in the UI.

example:

![image](https://user-images.githubusercontent.com/121543020/214064362-e8b5165a-5d42-4dd7-ab02-dea1690b3fd4.png)

### What do you see instead?

no repositories created in the UI even though storage is used for the project and download of images is successful 

![image](https://user-images.githubusercontent.com/121543020/214064501-af0b2204-c500-4615-88c5-29f206c05134.png)

### Additional information

In the project quota used a pull of new images is shown as used storage:

![image](https://user-images.githubusercontent.com/121543020/214064188-bd9cfadc-8c11-4968-8da0-e83d739d7398.png)

Also, it is not clear if this is just UI bug, or if instead of pulling from harbor as a cache, in each pull harbor is actually pulling again from remote registry (quay) and only serves as a proxy, which is not what we need.

**Comment by javsalgar** [comment]
Hi,

Do you see any information in the logs that could be useful? It is not clear to me either if this is a bug in Harbor itself or in the Bitnami packaging.
