### ISSUE TITLE
[bitnami/mysql] mysql shutdown during "Server upgrade from '80027' to '80027' started"

### ISSUE THREAD

**Issue by Thangarajsubramani** [bitnami/charts#14508]
### Name and Version

bitnami/mysql:8.0.27

logs:
```
  | Jan 20, 2023 @ 21:32:32.195 | production | 2023-01-21T03:32:32.195034Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.27).

  | Jan 20, 2023 @ 21:32:32.192 | sdoe-production | [38;5;6mmysql [38;5;5m03:32:32.19 [0m[38;5;2mINFO [0m ==> Stopping mysql

  | Jan 20, 2023 @ 21:32:32.035 | production | 2023-01-21T03:32:32.035305Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.27'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.

  | Jan 20, 2023 @ 21:32:32.035 | production | 2023-01-21T03:32:32.035127Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock

  | Jan 20, 2023 @ 21:32:31.995 | production | 2023-01-21T03:32:31.994968Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.

  | Jan 20, 2023 @ 21:32:31.994 | production | 2023-01-21T03:32:31.994938Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
  | Jan 20, 2023 @ 21:32:31.994 | production | 2023-01-21T03:32:31.994158Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1.1 is enabled for channel mysql_main

  | Jan 20, 2023 @ 21:32:31.994 | production | 2023-01-21T03:32:31.994136Z 0 [Warning] [MY-013746] [Server] A deprecated TLS version TLSv1 is enabled for channel mysql_main

  | Jan 20, 2023 @ 21:32:31.816 | production | 2023-01-21T03:32:31.816712Z 4 [System] [MY-013381] [Server] Server upgrade from '80027' to '80027' completed.
```

### What steps will reproduce the bug?

in all env

### What do you see instead?

what is option to disable the mysql auto upgrade

**Comment by javsalgar** [comment]
Hi,

Could you add a values.yaml that triggers the issue? We would like to reproduce it in our side.

**Comment by javsalgar** [comment]
Thanks.

Does the issue happen with a fresh deployment? At what point does the crash occur? Should we expect a crashing just after deploying?

**Comment by Thangarajsubramani** [comment]
> Thanks.
> 
> Does the issue happen with a fresh deployment? At what point does the crash occur? Should we expect a crashing just after deploying?

no . The observation is it happens only whenever its trying upgrade.but we are not sure when its try to upgrade itself to the same version. how do we diable that if we don't needed it?

**Comment by javsalgar** [comment]
Hi,

If you want to disable the upgrade logic, you can simply override the `command` and `args` section of the pod.

**Comment by thsubramani** [comment]
> Hi,
> 
> 
> 
> If you want to disable the upgrade logic, you can simply override the `command` and `args` section of the pod.

Do you have any example --args option to avoid that? . That would be helpful and appreciated

**Comment by thsubramani** [comment]
> > Hi,
> > 
> > 
> > 
> > If you want to disable the upgrade logic, you can simply override the `command` and `args` section of the pod.
> 
> Do you have any example --args option to avoid that? . That would be helpful and appreciated 

I found the option to disable the upgrade but this is not the reason MySQL daemon is crashing. This mysqld process crashes randomly without any reason by receiving the shutdown signal from somewhere. Do we have any option to Log those stack traces something like that ? So it will help us to identify the cause of it

**Comment by javsalgar** [comment]
MySQL is using the default log levels, maybe you can try tweaking the default log levels to see if there's more information https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-application-log.html

**Comment by suhli** [comment]
how to disable upgrade at startup?
