### ISSUE TITLE
[bitnami/redis-cluster] Arguments to redis-server turns off main configuration file

### ISSUE THREAD

**Issue by aaabdallah** [bitnami/charts#14510]
### Name and Version

bitnami/redis-cluster 8.3.3

### What steps will reproduce the bug?

When I add values to the helm chart value "redis.args", the instances in the deployment come up in standalone mode. Upon further inspection, the instances are all behaving as if they did not read any configuration file.

My example for "redis.args":

```
redis:
  command:
  - redis-server
  args:
  - --maxmemory 1mb
  - --maxmemory-policy allkeys-lru
```

Some observations:

1. It is necessary to add the command field ("redis-server") if one uses the args field, otherwise there is no command passed to the bash shell used for invoking.
2. If I add /opt/bitnami/redis/etc/redis.conf as the first argument passed in to args, the pod fails, and the logs show that no such file exists. There is a default configuration file in that directory, but apparently whatever customization needs to happen to generate redis.conf does not happen when using one's own command and args fields.

My goal is simply to set maxmemory and maxmemory-policy (and perhaps other configuration parameters). In the "redis" chart (not "redis-chart"), there is a "commonConfiguration" helm chart field that allows for this type of configuration easily.

### Are you using any custom parameters or values?

Please see above.

### What is the expected behavior?

My expectation is to get custom configuration into the instances of the Redis cluster via command line arguments. If there is another way of doing this, then it seems I am not aware of it.

### What do you see instead?

The cluster members all come up in standalone mode.

### Additional information

Thank you for your time and efforts.

**Comment by javsalgar** [comment]
Hi,

Looking at the run.sh script in the redis-cluster container, we have the following

```
read -ra nodes <<< "$(tr ',;' ' ' <<< "${REDIS_NODES}")"

ARGS=("--port" "$REDIS_PORT_NUMBER")
ARGS+=("--include" "${REDIS_BASE_DIR}/etc/redis.conf")

if ! is_boolean_yes "$ALLOW_EMPTY_PASSWORD"; then
    ARGS+=("--requirepass" "$REDIS_PASSWORD")
    ARGS+=("--masterauth" "$REDIS_PASSWORD")
else
    ARGS+=("--protected-mode" "no")
fi

ARGS+=("$@")
```

In this sense, you can leave the `command` section empty and add the following as args

```
args:
  - /opt/bitnami/scripts/redis-cluster/run.sh
  - --maxmemory 1mb
  - --maxmemory-policy allkeys-lru
```

**Comment by aaabdallah** [comment]
Thank you for your quick reply.

OK, I tried as you said but the result was a CrashLoopBackoff, and the logs for the failing containers (all instances in the cluster):

```
1:C 24 Jan 2023 17:06:51.748 # Fatal error, can't open config file '/opt/bitnami/redis/etc/redis.conf': No such file or directory
```

I tried also the simpler:

```
args:
  - /opt/bitnami/scripts/redis-cluster/run.sh
```

But it gave the same result: can't open config file.

After digging about for a while...

I believe I know why: https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/redis-statefulset.yaml

There, if redis.args is defined, the default action of copying over redis-default.conf to redis.conf never happens.

There must be a way to get custom parameters into the cluster, but I am still not seeing how.

**Comment by rafariossaa** [comment]
Hi,
  Could you try this?
```
redis:
  args:
    - |
      # Backwards compatibility change
      if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
          echo COPYING FILE
          cp  /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
      fi
      {{- if .Values.cluster.init }}
      pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
      pod_index="${pod_index[-1]}"
      if [[ "$pod_index" == "0" ]]; then
        export REDIS_CLUSTER_CREATOR="yes"
        export REDIS_CLUSTER_REPLICAS="{{ .Values.cluster.replicas }}"
      fi
      {{- end }}
      /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 1mb --maxmemory-policy allkeys-lru
```

  This is what is generated when no using `redis.args`. In this case, actually the `Backwards compatibility change` section is not needed as the container image has that file as `redis.conf`. However, the missing part is setting the environment vars and calling `entrypoint.sh`.
