### ISSUE TITLE
[bitnami/postgresql] run pg_ldap_sync in cronjob if ldap is enabled

### ISSUE THREAD

**Issue by abdennour** [bitnami/charts#14511]
### Name and Version

bitnami/postgresql 12.1.9

### What is the problem this feature will solve?

Kill  the overhead of the manual configuration after integrating Postgresql with LDAP

### What is the feature you are proposing to solve the problem?

I am proposing to create a cronjob with a schedule to periodically synchronize LDAP users/groups to Postgres roles.

### What alternatives have you considered?

Manual SQL queries

**Comment by javsalgar** [comment]
Hi,

For this kind of special use cases, our recommendation is to use the `extraDeploy` section where you can add the YAML for your cron job and perform the proper operations. Did you try that?
