### ISSUE TITLE
[bitnami/keycloak] Missing upgrade docs for keycloak chart 13.x

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#14521]
### Name and Version

bitnami/keycloak 13.0.2

### What steps will reproduce the bug?

Keycloak chart as of 2023-01-24 is now version 13.0.2, but `charts/bitnami/keycloak/README.md` does not include any information on upgrading to 13.x or list breaking changes introduced with that chart major version.

### What do you see instead?

Latest update instructions in README.md are for 12.x.

**Comment by Mauraza** [comment]
Hi @brsolomon-deloitte,

If you check the [PR](https://github.com/bitnami/charts/commit/6f05162517ba2fcd0920df7ff53fe19e0f750a96) which updates to 13 is related to the upgrade of the version of [Keycloak 20](https://www.keycloak.org/2022/11/keycloak-2000-released).
