### ISSUE TITLE
[bitnami/redis] sentinel are crashing after too much tilting

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#14529]
### Name and Version

bitnami/redis , latest

### What steps will reproduce the bug?

helm install redis redis

### Are you using any custom parameters or values?

sentinel.enabled=true
no of replicas=3

### What is the expected behavior?

sentinel should work fine without tilting .

### What do you see instead?

sentinels are titling too much and pod is crashing . core dump files are created .

### Additional information

output of one of the core file.
![Screenshot from 2023-01-25 10-58-55](https://user-images.githubusercontent.com/68244292/214487550-fcfbaa4b-ff8e-47f6-8465-17063028705d.png)

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2023-01-25 11-04-47](https://user-images.githubusercontent.com/68244292/214488033-cae9a839-b731-42f7-8a71-6ef020c4e8da.png)
these many core files are created

**Comment by javsalgar** [comment]
Hi,

Could you add more details on the platform you are using for running the redis-cluster installation? Could you share the logs of the crashing pods?

**Comment by abhishekgupta2205** [comment]
![Screenshot from 2023-01-29 14-39-17](https://user-images.githubusercontent.com/68244292/215316518-03627d50-6f75-4ebf-b07b-f3505c472038.png)
this is the log output obtained when pod is crashing due to excessive tilting  .

**Comment by abhishekgupta2205** [comment]
i think this is same issue as #10547 which remained unsolved till now

**Comment by javsalgar** [comment]
Which is the Kubernetes platform you are using? Not sure if networking could be an issue here

**Comment by abhishekgupta2205** [comment]
we have on-premisies kubernetes cluster . also i have checked it on minikube , same problem occurs there

**Comment by fmulero** [comment]
Same error reported twice #14394
