### ISSUE TITLE
Spark storage issue

### ISSUE THREAD

**Issue by vjvel** [bitnami/charts#14534]
### Name and Version

spark 5.9.6

### What steps will reproduce the bug?

The Spark chart is not having any PVC on the version I used, 

Currently, it occupies the space which is under `/opt/bitnami/spark/work`. Which creates an issue on the worker node filesystem, It's using an overlay filesystem.
```
1001@prod-spark-oci-worker-0:/opt/bitnami/spark/work$   du -sh
127G    .
```

### What do you see instead?

Do we need to create PVC for this?

**Comment by jotamartos** [comment]
That folder is for the monitoring and logging information. You can get more information about it in [the Spark's documentation](https://spark.apache.org/docs/latest/spark-standalone.html#monitoring-and-logging). That data doesn't need to be persisted as it's transient information. Please review the information there to know why you have that amount of data in the work directory.
