### ISSUE TITLE
[Redis] Multiple Standalone Masters

### ISSUE THREAD

**Issue by air3ijai** [bitnami/charts#14540]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

We are switching from Redis Sentinel (3 x Redis/Sentinel) to the Redis Standalone (2 x Redis). It will simplify our architecture and will still provide a required resilience.

We will have two copies of the App with a separate Redis for each of them.

```
                 App 01 --> Redis 01 
               /
Client --> API
               \
                 App 02 --> Redis 02
```

### What is the feature you are proposing to solve the problem?

We would like to deploy 2 Standalone Masters without any replicas and access them via service from any nodes in the cluster.

Is that can be achieved by the current [Multiple masters (experimental)](https://github.com/bitnami/charts/tree/main/bitnami/redis#multiple-masters-experimental) topology?

### What alternatives have you considered?

Now we have two separate deployments, but it is more complicated to manage them in case of upgrades.

We would like to make sure that Redis 02 upgrade is started only after Redis 01 was finished and it may be handled by the Kubernetes.

**Comment by marcosbc** [comment]
Hi @air3ijai, I encourage you to have a look at https://github.com/bitnami/charts/pull/10047 where it describes this in more detail.

This could work for your scenario if you are OK with having Redis tied to a specific node. Note that you will not be able to add replicas for a master in a different node.

That said, this is experimental. It is probably best if you add a Redis chart dependency per app, as it could be simpler to manage and be less prone to errors.

**Comment by air3ijai** [comment]
@marcosbc, looks like it the about topology I have mentioned in the first comment and it is about Master per node, but it we have a kind of limitation here - App should be located on the same node with the Master?

Let's say we have Redis 100 GB RAM + App 30 GB RAM or some other constraints - how we may proceed in such a case?

**Comment by marcosbc** [comment]
@air3ijai If you can't have all your Redis pods contained into one node, you're probably better off with deploying multiple redis charts at once, by adding them as a dependency to your own chart as I mentioned previously.

The only problem with that is that, as you mentioned, you will need to take care of the maintenance of each Redis deployment individually. However, Bitnami charts do not support any automations related to the maintenance of multiple Helm deployments at once, that would also probably fall more into the "operators" area.

**Comment by air3ijai** [comment]
@marcosbc, this is the intention of the initial Feature Request - it looks like a very common and simple approach.

Just in case we need a setup with two separate masters which not stick with the specific nodes and accessible across the whole cluster.

**Comment by marcosbc** [comment]
I'm not sure that this makes sense. The scenario that you describe can be easily workaround just by deploying multiple Redis Helm chart.

I understand that it would allow users to simplify the maintenance of multiple clusters, but it would also likely involve adding a lot of complexity to the chart itself, just to support this form of "namespacing" of Redis masters.

That said, if you have any idea on how this could be implemented, feel free to send a PR implementing this feature and we will be happy to consider it.
