### ISSUE TITLE
[bitnami/postgresql-ha] Log from pods to the PersistentVolume

### ISSUE THREAD

**Issue by arturbrandysonwelo** [bitnami/charts#14545]
### Name and Version

bitnami/postgresql-ha appVersion: 11.10.0

### What is the problem this feature will solve?

Hello.
I have a question about the logging functionality.
What is the best way to get and save logs from pods of this project?
How to redirect the logs from pods (pgpool and postgresql) to PersistentVolume using functionality build in this project?

### What is the feature you are proposing to solve the problem?

If there is nothing in parameters, there should be some to log on PersistentVolume (for example: enable logging in that way, give the path for logs).

**Comment by javsalgar** [comment]
Hi,

In this kind of installations, the recommended way is to use a logging stack such as EFK or LGTM. These solutions would take the container pods and put them in a centralized system with a UI to access them.
