### ISSUE TITLE
[bitnami/MongoDb] MongoDB connection

### ISSUE THREAD

**Issue by mertcakmak2** [bitnami/charts#14544]
### Name and Version

bitnami/mongodb-13.6.4

### What steps will reproduce the bug?
```
helm install my-release my-repo/mongodb --set architecture=replicaset,replicaCount=3,global.storageClass=standard
```
![image](https://user-images.githubusercontent.com/21373505/214792383-7eaa59c3-4d48-420a-9701-0e7ffeaa0db0.png)

![image](https://user-images.githubusercontent.com/21373505/214788001-e1287bf1-9b17-4aa5-84c4-c6e482930cb6.png)

### Are you using any custom parameters or values?
```
architecture=replicaset
replicaCount=3
global.storageClass=standard
```

### What do you see instead?

Can I connect with the "my-release-mongodb-headless" service name from my app? If the answer is no, have I used pod names and service names? Like as "my-release-mongodb-0.my-release-mongodb-headless:27017", "my-release-mongodb-1.my-release-mongodb-headless:27017", "my-release-mongodb-2.my-release-mongodb-headless:27017"?

**Comment by aoterolorenzo** [comment]
Hi @mertcakmak2,

Could you explain a little more about what you are trying to do?
