### ISSUE TITLE
[Ghost] broken: Not installing deployment or statefulset

### ISSUE THREAD

**Issue by Y0ngg4n** [bitnami/charts#14564]
### Name and Version

bitnami/ghost:19.1.59-19.1.61

### What steps will reproduce the bug?

1. Add the bitnami chart repo
2. Execute `helm install ghost bitnami/ghost --set mysql.enabled=false`
3. Check for pods, deployments or statefulsets

### Are you using any custom parameters or values?

`helm install ghost bitnami/ghost --set mysql.enabled=false`

### What is the expected behavior?

Deployment of ghost pods.

### What do you see instead?

No deployment of the gost pods.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
