### ISSUE TITLE
[PostgreSQL] Enable ReadOnlyRootFS

### ISSUE THREAD

**Issue by missalt** [bitnami/charts#14578]
### Name and Version

bitnami/postgresql 12.1.11

### What is the problem this feature will solve?

Enabling ReadOnlyRootFS in Container securityContext reduces attack surface

### What is the feature you are proposing to solve the problem?

enable readOnlyRootFilesystem option in securityContext and mount volumes only on the paths that the application needs to write on (mainly /var/lib/postgresql/data/ and /var/run/postgresql/ for standard dockerhub postgres image)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by bh-tt** [comment]
Not sure about a PR, but for future reference, you need an emptyDir mount at the following locations:
 - /tmp
 - /opt/bitnami/postgresql/conf
 - /opt/bitnami/postgresql/tmp
