### ISSUE TITLE
How to configure Configure Static IP for Kafka pod

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#14597]
### Name and Version

bitnami/kafka

### What steps will reproduce the bug?

Hi Team,

How to configure  Static IP for Kafka pod in bitnami Kafka helm charts.
We want to assign the static IP for each Kafka pod, even if my Kafka pod restarts, IP should not change. Please let us know how to configure this.

Thanks,

**Comment by corico44** [comment]
Hello @bharathreddy901,
In the _values.yaml_ file itself there is a _clusterIP variable_ that it is used to configure a static clusterIP:
```
## @param metrics.kafka.service.clusterIP Static clusterIP or None for headless services
## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
##
clusterIP: ""
```
Hope this can help you.
