### ISSUE TITLE
need to fix security vulneraibilty CVV v3 with value more than 7

### ISSUE THREAD

**Issue by ankursrivastva** [bitnami/charts#14591]
### Name and Version

vault:1.12.2

### What steps will reproduce the bug?

running jfrog x ray scan will reporoduce the issue
[Docker_rmrsp-hashicorp-vault-1.12_Security_Export.csv](https://github.com/bitnami/charts/files/10530408/Docker_rmrsp-hashicorp-vault-1.12_Security_Export.csv)

### What do you see instead?

please fix the issue or let us know in which release the fix will come

**Comment by carrodher** [comment]
There is not any Bitnami image for `vault:1.12.2`, it seems this is mistake and you're using a container image from a different provider.
