### ISSUE TITLE
[bitnami/kafka] TLS enabled brokers do not return certificate chain (cert-manager + pemChainIncluded=true )

### ISSUE THREAD

**Issue by kxs-jnadeau** [bitnami/charts#14600]
### Name and Version

bitnami/kafka 20.0.5

### What steps will reproduce the bug?

1.  Deploying a 3 replicas cluster on AKS v1.23,  with cert-manager and external DNS
2. Chart deployed from helm command below.  The existing certs are generated by cert-manager with Sectigo's ACME endpoint.   Like Let'sEncrypt,  the generated secrets only contains a tls.crt (with chain) and a tls.key.    

3.  Looking at what the chart does with the pemChainIncluded flag,   I can see the certs split in the broker pods under /opt/bitnami/kafka/config/certs:

```
 -rw-r--r-- 1 1001 root 1708 Jan 27 20:22 kafka.keystore.key
-rw-r--r-- 1 1001 root 2472 Jan 27 20:22 kafka.keystore.pem
-rw-r--r-- 1 1001 root 4143 Jan 27 20:22 kafka.truststore.pem
-rw-r--r-- 1 1001 root 2472 Jan 27 20:22 xx00
-rw-r--r-- 1 1001 root 2175 Jan 27 20:22 xx01
-rw-r--r-- 1 1001 root 1968 Jan 27 20:22 xx02
```

4.  TLS validation is failing from clients (Java/Python) as shown below with openssl s_connect..   Validation goes ok if I pass the full chain to openssl s_client in a PEM file.

### Are you using any custom parameters or values?

```
helm template demo \
  --set replicaCount=3 \
  --set resources.requests.cpu=0.5 \
  --set resources.requests.memory=1024Mi \
  --set resources.limits.cpu=1 \
  --set resources.limits.memory=2024Mi \
  --set persistence.enabled=true \
  --set persistence.storageClass=managed-csi \
  --set zookeeper.persistence.storageClass=managed-csi \
  --set zookeeper.resources.requests.cpu=0.5 \
  --set zookeeper.resources.requests.memory=512Mi \
  --set zookeeper.resources.limits.cpu=1 \
  --set zookeeper.resources.limits.memory=1024Mi \
  --set auth.clientProtocol=sasl_tls \
  --set auth.externalClientProtocol=sasl_tls \
  --set auth.sasl.mechanisms=scram-sha-512 \
  --set auth.sasl.jaas.clientUsers[0]=test \
  --set auth.sasl.jaas.clientPasswords[0]="redacted" \
  --set auth.sasl.jaas.clientUsers[1]=admin \
  --set auth.sasl.jaas.clientPasswords[2]="redacted" \
  --set auth.interBrokerProtocol=sasl \
  --set auth.sasl.jaas.interBrokerUser=internal \
  --set auth.sasl.jaas.interBrokerPassword="redacted" \
  --set auth.sasl.interBrokerMechanism=scram-sha-512 \
  --set superUsers="User:admin;User:internal" \
  --set externalAccess.enabled=true \
  --set externalAccess.autoDiscovery.enabled=false \
  --set externalAccess.service.type=LoadBalancer \
  --set externalAccess.service.annotations='service.beta.kubernetes.io/azure-load-balancer-internal: "true"' \
  --set externalAccess.service.loadBalancerAnnotations[0]='external-dns.alpha.kubernetes.io/hostname: "broker-0.kafkatest.azk8scac.lab.io"' \
  --set externalAccess.service.loadBalancerAnnotations[1]='external-dns.alpha.kubernetes.io/hostname: "broker-1.kafkatest.azk8scac.lab.io"' \
  --set externalAccess.service.loadBalancerAnnotations[2]='external-dns.alpha.kubernetes.io/hostname: "broker-2.kafkatest.azk8scac.lab.io"' \
  --set externalAccess.service.loadBalancerNames[0]="broker-0.kafkatest.azk8scac.lab.io" \
  --set externalAccess.service.loadBalancerNames[1]="broker-1.kafkatest.azk8scac.lab.io" \
  --set externalAccess.service.loadBalancerNames[2]="broker-2.kafkatest.azk8scac.lab.io" \
  --set rbac.create=false \
  --set authorizerClassName=kafka.security.authorizer.AclAuthorizer \
  --set allowEveryoneIfNoAclFound=false \
  --set autoCreateTopicsEnable=false \
  --set auth.tls.type=pem \
  --set auth.tls.pemChainIncluded=true \
  --set auth.tls.existingSecrets[0]=kafka-tls-0 \
  --set auth.tls.existingSecrets[1]=kafka-tls-1 \
  --set auth.tls.existingSecrets[2]=kafka-tls-2 \
  --namespace kafkatest \
  my-repo/kafka > template.yaml
```

### What is the expected behavior?

Certificate chain is passed to the client and TLS validation is passing

### What do you see instead?

Confirmed with openssl s_connect,  the ceftificate chain is missing:

openssl s_client -showcerts -connect broker-0.kafkatest.azk8scac.lab.io:9094 -servername broker-0.kafkatest.azk8scac.lab.io

```
depth=0 C = CA, ST = Ontario, O = Redacted Inc., CN = broker-0.kafkatest.azk8scac.lab.io
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = CA, ST = Ontario, O = Redacted Inc., CN = broker-0.kafkatest.azk8scac.lab.io
verify error:num=21:unable to verify the first certificate
verify return:1
```

**Comment by kxs-jnadeau** [comment]
Digging deeper,  what get's generated in the broker servers.properties,  under the ssl.keystore.certificate.chain key,  only contains the broker certificate and not the intermediate.  I presume that's the problem.

**Comment by kxs-jnadeau** [comment]
I have made a local fix for this altering the kafka/templates/scripts-configmap.yaml that I think has the wrong logic to support intermediates.  In the end we only want the last certificate split from tls.crt to land in the trustore and all the others in the chain to be used for ssl.keystore.certificate.chain.

Does the below make sense  ? 

```
    if [[ -f "$PEM_CERT" ]] && [[ -f "$PEM_KEY" ]]; then
        CERT_DIR="/opt/bitnami/kafka/config/certs"
        PEM_CA_LOCATION="${CERT_DIR}/kafka.truststore.pem"
        PEM_CERT_LOCATION="${CERT_DIR}/kafka.keystore.pem"
            cat $PEM_CERT | csplit - -s -z '/\-*END CERTIFICATE\-*/+1' '{*}' -f ${CERT_DIR}/xx
            CERTS=($(find ${CERT_DIR} -name 'xx*' | sort -r))
            if [[ ${#CERTS[@]} < 2 ]]; then
                echo "auth.tls.pemChainIncluded was set, but PEM chain only contained 1 cert"
                exit 1
            fi
            FIND_CA_RESULT=${CERTS[0]}
            echo $FIND_CA_RESULT | sort | xargs cat >> "$PEM_CA_LOCATION"
            cat  ${CERTS[@]/$FIND_CA_RESULT} > "$PEM_CERT_LOCATION"

```

**Comment by dgomezleon** [comment]
Hi @kxs-jnadeau,

Could you please share with us the `server.properties` file that it generates in order to detect a misconfiguration there?

**Comment by sophokles73** [comment]
I ran into the same problem and have spent some time investigating the issue.

The first problem seems to be that the [setup.sh script](https://github.com/bitnami/charts/blob/7f55815b7a3e50bcf9ae90c18a72029b19da90bc/bitnami/kafka/templates/scripts-configmap.yaml#L195) from the *scripts-configmap* only includes the server's leaf certificate in the *kafka.keystore.pem* file, omitting the intermediate certs. Consequently, the kafka broker will always be configured with the leaf certificate only.

However, fixing this will not be enough because the [kafka_configure_ssl() function](https://github.com/bitnami/containers/blob/aff393200560d64c27e2b9323bdf248dd393d9d3/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L560)  from the bitnami kafka container helper library transforms the keystore PEM file to a string to be inlined into the *server.properties* in a way that is not compatible with the regular expression used by the *org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$PemParser.pemEntries()* method when starting up the broker. The regular expression only matches the *last* certificate in the chain which leads to the observed behavior.

I will create two PRs for fixing both problems here and in the *bitnami/containers* repository.

@dgomezleon would you mind re-opening this issue?

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PRs! The team will take a look

**Comment by sophokles73** [comment]
@corico44 This issue is *not* fixed by https://github.com/bitnami/containers/pull/29026 alone. It also requires https://github.com/bitnami/charts/pull/15941 to be merged ...

**Comment by ThomasRutger** [comment]
Are there any updates regarding this issue? I am currently running into the same (chart version 22.1.3).

**Comment by carrodher** [comment]
The contribution was not completed, we are happy to review any other contribution in order to solve the issue

**Comment by migruiz4** [comment]
Hi there!

We have released a new major of the bitnami/kafka chart which refactors the chart architecture and configuration.

Could you please confirm if this issue persists in the latest version?

You can find all the changes introduced in this version as well as some guidance on how to upgrade in the [Upgrading notes](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400)

One of the changes introduced in this new version is that the chart will automatically create a JKS keystore with the PEM certificates, instead of passing the PEM certificates to the container for it to configure them inline at `server.properties`.

**Comment by tbnguyen1407** [comment]
@migruiz4 Hello. It seems the refactored chart only updates server TLS portion to use JKS internally. Provisioning client with PEM certs still uses inline PEM certs in `client.properties`, which still fails this issue.

I think the provisioning job cert behavior also needs to be updated to match the server side.

**Comment by sophokles73** [comment]
@migruiz4 

My tests with the 24.x version of the chart have been successful insofar as the controller/broker now returns the full certificate chain in the TLS handshake when a client connects to it.

However, I ran into several problems trying to actually configure the controller/broker for TLS. I will create corresponding issues ...

**Comment by Jojoooo1** [comment]
@sophokles73 would you mind sharing your helm config ?

**Comment by sophokles73** [comment]
@Jojoooo1

I have created a secret `kafka-keys` containing the `kafka.key`, `kafka.crt` and `kafka-ca.crt` files.
Then I use this config when installing the chart:

```yaml
nameOverride: "kafka"
autoCreateTopicsEnable: true
deleteTopicEnable: true

controller:
  replicaCount: 3
 
listeners:
  client:
    protocol: "SASL_SSL"
  external:
    protocol: "SASL_SSL"

sasl:
  client:
    users:
    - "user1"
    passwords:
    - "pwd1"

tls:
  type: "PEM"
  pemChainIncluded: false
  existingSecret: "kafka-keys"

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  broker:
    service:
      type: "LoadBalancer"
      ports:
        external: 9094
  controller:
    service:
      type: "LoadBalancer"
      containerPorts:
        external: 9094
rbac:
  create: true
```

However, for me this has only worked after changing [scripts-configmap.yaml, line 182](https://github.com/bitnami/charts/blob/5a4ff7d8d55c2ade51de768a64d2ab8c10db4c16/bitnami/kafka/templates/scripts-configmap.yaml#L182) to

```yaml
# orig
# rm -f /certs/kafka.keystore.jks /certs/kafka.truststore.jks
# but should be
rm -f /certs/*
```

without this change, the Kafka chart fails to process the keys/certs during execution of the init container ...

**Comment by migruiz4** [comment]
@tbnguyen1407 Indeed, the provisioner job still uses the previous approach, could you please open a new issue so we can better address that specific use case?
