### ISSUE TITLE
[bitnami/cert-manager] Enable hostnetwork field for cert manager webhook

### ISSUE THREAD

**Issue by kaiyuanlim** [bitnami/charts#14698]
### Name and Version

bitnami-charts/cert-manager 0.8.9

### What steps will reproduce the bug?

1. Deploy rendered chart in our eks cluster.
2. See that webhook is not working as intended.
3. Fix was to set the hostnetwork to true for webhook

### What do you see instead?

A new values called as webhook.hostnetwork

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Would you like to submit a PR adding it?

**Comment by javsalgar** [comment]
Yes! Contributions are welcome! :D

**Comment by kaiyuanlim** [comment]
Here it is: https://github.com/bitnami/charts/pull/14776

**Comment by kaiyuanlim** [comment]
@javsalgar : Is the PR okay?

**Comment by kaiyuanlim** [comment]
Fixed in https://github.com/bitnami/charts/pull/14776
