### ISSUE TITLE
Setting for maximum tcp connection missing

### ISSUE THREAD

**Issue by mazmar** [bitnami/charts#14702]
### Name and Version

bitnami/rabbitmq

### What steps will reproduce the bug?

Install the chart with default values. There is no way to setup max number of connections to the replica

Maybe this is not the correct approach but what if I need a rabbitmq that has to run on 40k clients at the same time? Currently, I read that one instance of rabbitmq can accept 128 connections at max. This would mean 400 replica instances which are unimaginable. Is this the correct approach even?

### What do you see instead?

no value for TCP connections affecting rabbits `tcp_listen_options.backlog = 128`

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by hgm-kklingspor** [comment]
So setting `tcp_listen_options.backlog` should be sufficient to cope with greater amounts of connection-requests?
Ref.: https://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections-connection-backlog and https://www.rabbitmq.com/networking.html#socket-gen-tcp-options-common
"Maximum size of the unaccepted TCP connections queue. When this size is reached, new connections will be rejected. Set to 4096 or higher for environments with thousands of concurrent connections and possible bulk client reconnections."

I think, this should be an easy fix.
