### ISSUE TITLE
Sentinel only deployment without Replica

### ISSUE THREAD

**Issue by UgurcanAkkok** [bitnami/charts#14740]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

I don't want to deploy redis replica/master on kubernetes. I have an external redis cluster with sentinel. I want to move the sentinels to my k8s cluster.

### What is the feature you are proposing to solve the problem?

Enable only deploying sentinels without any replica container. 

### What alternatives have you considered?

Searched some other charts, but there were no charts with such option. I am considering writing a custom chart for my use-case.

**Comment by dgomezleon** [comment]
Hi @UgurcanAkkok ,

Did you read [this README section](https://github.com/bitnami/charts/blob/main/bitnami/redis/README.md#bootstrapping-with-an-external-cluster)?

Would it work for you?

Regards

**Comment by UgurcanAkkok** [comment]
Hi @dgomezleon , 
Yes, i read it but i don't want redis replicas in the kubernetes. Using that section, it deploys the sentinels beside the replicas, which i don't want.

**Comment by dgomezleon** [comment]
Hi @UgurcanAkkok,

I found [this article](https://cloudinfrastructureservices.co.uk/redis-sentinel-vs-cluster) that may help to understand the topologies that we support.

Your requirement seems very specific and tightly tied to your scenario.  It might be helpful if you elaborated a little on your purpose.

That said, we will keep this ticket open until the stale bot closes it just in case some other members of the community find this feature useful too.
