### ISSUE TITLE
[bitnami/influxdb] Customize your InfluxDB OSS URL

### ISSUE THREAD

**Issue by jasmisbvb** [bitnami/charts#14755]
### Name and Version

bitnami/influxdb:2.6.1-debian-11-r11

### What steps will reproduce the bug?

I have installed infludb using bitnami helmchart https://artifacthub.io/packages/helm/bitnami/influxdb

By defalult, the url is configured as http://localhost:8086/ in the location /binami/influxdb/configs

I’m trying to override the url as the document  https://docs.influxdata.com/influxdb/v2.6/reference/urls/using using the environment variable with following values
```
       - name: INFLUXDB_HTTP_PORT_NUMBER
         value: "8086"
       - name: INFLUXDB_HTTP_BIND_ADDRESS
         value: "influxdb"    
```
But still the the url is configured as http://localhost:8086/ in the location /binami/influxdb/configs

### Are you using any custom parameters or values?

       - name: INFLUXDB_HTTP_PORT_NUMBER
         value: "8086"
       - name: INFLUXDB_HTTP_BIND_ADDRESS
         value: "influxdb"    

### What is the expected behavior?

http://influxdb:8086/

### What do you see instead?

http://localhost:8086/

**Comment by aoterolorenzo** [comment]
Hi @jasmisbvb,

Could you cat the `influxdb.conf` file in order to see if the `INFLUXDB_HTTP_BIND_ADDRESS`  and `INFLUXDB_HTTP_PORT_NUMBER`  environment variables are being set there?
