### ISSUE TITLE
[bitnami/harbor] chart suggestion on optimization

### ISSUE THREAD

**Issue by jiaxinonly** [bitnami/charts#14757]
### Name and Version

bitnami/harbor 16.3.1

### What is the problem this feature will solve?

chart is easier to use.

### What is the feature you are proposing to solve the problem?

Offer several suggestions and hope to optimize:
1. The existingClaim option should also be available in persistence.persistentVolumeClaim.trivy
2. ingress.core.secrets and ingress.notary.secrets should only provide the name, and the certificate content should be created by users themselves. The certificate content should not be written in values.yaml. First, it is not secure, and the certificate is too long to display in values.yaml.
3. externalRedis should provide a user option. redis should not be a fixed user. redis of earlier versions does not have acl policies

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feedback! For any of the items above, would you like to create a PR to improve the chart? Suggestions are welcome and will speed up the process of polishing this chart in particular.
