### ISSUE TITLE
[bitnami/thanos] rule doesnt honor the rule file configuration

### ISSUE THREAD

**Issue by infa-pavakuma** [bitnami/charts#14753]
### Name and Version

docker.io/bitnami/thanos:0.28.0-scratch-r0

### What steps will reproduce the bug?

I am trying to set the Thanos rules config to something like this 
```          config: |-
            file_sd_configs:
            - files:
              - "/tmp/*.yaml"
              refresh_interval: 10s
            api_version: v1
```
The files are already mounted in the specified location using a config map. Doesn't seem to be working at all. 

### Are you using any custom parameters or values?

          config: |-
            file_sd_configs:
            - files:
              - "/tmp/*.yaml"
              refresh_interval: 10s
            api_version: v1

### What is the expected behavior?

See Description

### What do you see instead?

Null rules and alerts

### Additional information

It works when I manually edit the sts to just point to 
--rule-file="/tmp/*.yaml"

**Comment by javsalgar** [comment]
Hi,

Could you share an example file that is mounted in the tmp folder so we can fully reproduce the issue?

**Comment by infa-pavakuma** [comment]
Hey I am mounting it from the config map that is generated by the Prometheus operator

**Comment by javsalgar** [comment]
Are you using the bitnami/kube-prometheus chart?

**Comment by infa-pavakuma** [comment]
Nope, the community kube-prometheus helm chart

**Comment by javsalgar** [comment]
Please let us know how to exactly reproduce the issue and all the steps (if that includes installing an external chart, please add it as well).
