### ISSUE TITLE
[bitnami/airflow] newly added Dags not loading  on airflow webui

### ISSUE THREAD

**Issue by denishant** [bitnami/charts#14761]
### Name and Version

bitnami/airflow

### What steps will reproduce the bug?

I have deployed bitnami/airflow on kubernetes,also i have done git.dags.enabled as True and given our git repo in values.yaml, so that whenever new dags are pushed to git repo, it will be pulled by airflow sidecar containers (i.e git).

But whenever new dags are pushed to repo, it is pulled by sidecar containers as expected. But they didnot show on airflow webui.
Also if i go inside the airflow-scheduler pod, and run command "airflow dags list", newly added dags will appear there, but they didnot show on airflow webui.
However, if i restart the scheduler pod, newly added dags will appear on airflow webui.

Is this behavior expected ?

### What do you see instead?

newly added dags, should appear on airflow webui, without restarting airflow-scheduler pod .

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket. It is not clear to me that the issue has to do with the Bitnami packaging. Did you ask the airflow devs about this?

**Comment by denishant** [comment]
No, i hadn't asked airflow devs about this
