### ISSUE TITLE
[bitnami/rabbitmq] configuration option is broken and causes RabbitMQ to fail

### ISSUE THREAD

**Issue by Lance-Drane** [bitnami/charts#14766]
### Name and Version

bitnami/rabbitmq 11.9.0

### What steps will reproduce the bug?

1. In `values.yaml`, set `memoryHighWatermark.enabled` to `true`
2. Try to run the chart - no other values necessary

### Are you using any custom parameters or values?

memoryHighWatermark.enabled = true

### What is the expected behavior?

Rabbitmq-server should be able to start up

## Logs
```
rabbitmq 17:34:52.64 
rabbitmq 17:34:52.64 Welcome to the Bitnami rabbitmq container
rabbitmq 17:34:52.64 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 17:34:52.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 17:34:52.64 
rabbitmq 17:34:52.64 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 17:34:52.65 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 17:34:52.67 INFO  ==> Initializing RabbitMQ...
rabbitmq 17:34:52.69 INFO  ==> Starting RabbitMQ in background...
rabbitmq 17:36:40.76 ERROR ==> Couldn't start RabbitMQ in background.
```
## Logs - When turning on diagnostic mode and running `rabbitmq-server` directly

```
2023-02-06 17:49:41.874078+00:00 [error] <0.132.0> Error parsing configuration:
2023-02-06 17:49:41.884752+00:00 [error] <0.132.0>   - Syntax error in /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf after line 26 column 1, parsing incomplete
2023-02-06 17:49:41.884787+00:00 [error] <0.132.0> Are these files using the Cuttlefish format?

2023-02-06 17:49:41.886205+00:00 [error] <0.132.0> 
2023-02-06 17:49:41.886205+00:00 [error] <0.132.0> BOOT FAILED
2023-02-06 17:49:41.886205+00:00 [error] <0.132.0> ===========
2023-02-06 17:49:41.886205+00:00 [error] <0.132.0> Error during startup: {error,failed_to_parse_configuration_file}
2023-02-06 17:49:41.886205+00:00 [error] <0.132.0> 
BOOT FAILED
===========
Error during startup: {error,failed_to_parse_configuration_file}
```

## Configuration file (cat /etc/rabbitmq/rabbitmq.conf )

```
## TCP Listen Options
##
tcp_listen_options.backlog = 128
tcp_listen_options.nodelay = true
tcp_listen_options.linger.on      = 
tcp_listen_options.linger.timeout = 0
tcp_listen_options.keepalive = false
```

### Additional information

The problem is that `{{ .Values.tcpListenOptions.linger.on }}` (referenced in .Values.configuration ) will not get properly expanded out, so you'll see one of the lines in `rabbitmq.conf` get expanded out to `tcp_listen_options.linger.on     = ` . This causes rabbitmq-server to fail to parse the config file, which causes a start failure.

I'm thinking that `on` may be a reserved word in Helm chart templates, because the rest of the values are expanded out properly (including the boolean value `false`). So then the question becomes "how should the value be named" ? 

I was able to fix this problem on a custom deployment by copy-pasting the `configuration` value, and then replace `{{ .Values.tcpListenOptions.linger.on }}` with a hard-coded `true` value.

If I had a clear idea on what the value should be named, I could open an MR myself and knock this issue out. The names in the values file correspond nicely to the actual rabbitmq configuration keys.

**Comment by younessof2m** [comment]
Hello
I have the same issue on my deployment.

**Comment by Lance-Drane** [comment]
Thanks @aoterolorenzo , I went ahead and used `linteron` since it was suggested, and the base64-generated string for `rabbitmq.conf` seems to decode properly.

**Comment by elchenberg** [comment]
> I'm thinking that on may be a reserved word in Helm chart templates, because the rest of the values are expanded out properly (including the boolean value false).

I think this thread explains it: https://github.com/helm/helm/issues/5497 (tl;dr: "on" and "off" are boolean values in YAML 1.1)
