### ISSUE TITLE
[bitnami/clickhouse] Pods are not updated when more replicas are added

### ISSUE THREAD

**Issue by mohamedazouz** [bitnami/charts#14765]
### Name and Version

bitnami/clickhouse 2.3.1

### What steps will reproduce the bug?

1. Install chart with 1 replicas `replicaCount: 1` and 2 shards
2. 2 pods will be created `my-clickhouse-shard0-0 , my-clickhouse-shard1-0`
3. check pod default config `/etc/clickhouse-server/conf.d/00_default_overrides.xml`, there will be correct `remote_servers` setup as following
```xml
<remote_servers>
    <default>
      <shard>
          <replica>
              <host>my-clickhouse-shard0-0.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
      </shard>
      <shard>
          <replica>
              <host>my-clickhouse-shard1-0.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
      </shard>
    </default>
  </remote_servers>
```
4. upgrade replicas to 2 `replicaCount: 2`
5. 2 additional pods will be added `my-clickhouse-shard0-1, my-clickhouse-shard0-1`

Config On previous pods are still holding the old config But the config for the new pods is having new correct ones 
```xml
<remote_servers>
    <default>
      <shard>
          <replica>
              <host>my-clickhouse-shard0-0.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
          <replica>
              <host>my-clickhouse-shard0-1.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
      </shard>
      <shard>
          <replica>
              <host>my-clickhouse-shard1-0.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
          <replica>
              <host>my-clickhouse-shard1-1.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
      </shard>
    </default>
  </remote_servers>
```

* I had to delete the pods manually to grab the latest configMap changes.

### What is the expected behavior?

I was expected that all pods to be consistent having the same config specially for replicas/shards similar to the latest new added replicas

```xml
<remote_servers>
    <default>
      <shard>
          <replica>
              <host>my-clickhouse-shard0-0.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
          <replica>
              <host>my-clickhouse-shard0-1.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
      </shard>
      <shard>
          <replica>
              <host>my-clickhouse-shard1-0.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
          <replica>
              <host>my-clickhouse-shard1-1.my-clickhouse-headless.analytics.svc.cluster.local</host>
              <port>9000</port>
          </replica>
      </shard>
    </default>
  </remote_servers>
```

pods needs to reflect new config, so it should be restarted

### What do you see instead?

Pods are not consistent with their configuration

### Additional information

I'm not sure if this is a default behaviour or config I need to tune
Can you please help?

**Comment by javsalgar** [comment]
Hi,

It seems to me that the pods should restart on configmap updates, this is done adding the checksum as annotation. Would you like to submit a PR adding it?

**Comment by mohamedazouz** [comment]
Hey @javsalgar, I have added [PR](https://github.com/bitnami/charts/pull/14779) fixing the issue, please have a look.

**Comment by mohamedazouz** [comment]
This is fixed with the merge of this PR: https://github.com/bitnami/charts/pull/14779
