### ISSUE TITLE
[bitnami/postgresql-ha] While the master pod is down and slave becomes master but not able to write

### ISSUE THREAD

**Issue by amal-k-soman-aot** [bitnami/charts#14774]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

1. deleting the master pod

### Are you using any custom parameters or values?

no

### What is the expected behavior?

the applications should be able to write into the pod

### What do you see instead?

the transaction is become readonly transaction

**Comment by javsalgar** [comment]
Hi,

Does the application become writable at some point or it never becomes writable again?

**Comment by Tilusch** [comment]
@javsalgar Hi,

Im facing the same issue, the problem seems to be that pgpool doesn't find the new primary nodes and still sends inserts to the old primary node. 
The only way to fix this is to restart the pgpool.

When checking inside the postgres cluster with:

**Comment by javsalgar** [comment]
Hi @Tilusch did you do any change the in the values.yaml file?
