### ISSUE TITLE
[bitnami/schema-registry] HPA v2 have no valid filed named 'targetAverageUtilization'

### ISSUE THREAD

**Issue by Sakib37** [bitnami/charts#14792]
### Name and Version

schema-registry:7.3.1-debian-11-r10

### What steps will reproduce the bug?

In kubernetes version v1.23 or above, where HPA api v2 is available, if `autoscaling.targetCPU` or `autoscaling.targetMemory` is set in values.yaml file then hpa.yaml file will have the following config 

```
type: Resource
resource:
   name: cpu
   targetAverageUtilization:  $targetCPU_Value_in_values_file
```

However, kubernetes HPA V2 api will complain about invalid field `targetAverageUtilization` in the HPA

### What is the expected behavior?

Valid field for HPA should be set in the hpa.yaml templated so that kubernetes HPA v2 consider the manifest for hap.yaml as valid. 

### What do you see instead?

I see Error with the following error message:

` error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource]
`

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. It seems to me that we may need to create adaptations for the different HPA versions. I will forward this to the team. If you want to speed up the process, feel free to submit a PR.

**Comment by anuraGit19** [comment]
Hi, 
Any update on this issue? 
I faced the same issue with HPA v2.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for creating a PR! The team will take a look

**Comment by anuraGit19** [comment]
A gentle reminder, any update on the PR from the team?

**Comment by carrodher** [comment]
Please note the PR was created in your own fork and not in this bitnami/charts repo. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
