### ISSUE TITLE
[bitnami/mongodb] Add custom users with specific role

### ISSUE THREAD

**Issue by dung-tien-nguyen** [bitnami/charts#14791]
### Name and Version

bitnami/mongodb 13.6.7

### What is the problem this feature will solve?

Allow adding users with specified Mongodb built-in roles and User-Defined Roles. That will be useful when the system needs to add additional users to accompany.

### What is the feature you are proposing to solve the problem?

Add a function to create a role, a function to create a user with a role specified in the file libmongodb.sh . Then transmit ENV from helm.

**Comment by javsalgar** [comment]
Hi,

Did you try the `initScripts` feature? There you can add your custom scripts to cover your use case.

**Comment by dung-tien-nguyen** [comment]
Thank for your response, it's work.

**Comment by javsalgar** [comment]
Thanks for letting us know!
