### ISSUE TITLE
[bitnami/grafana-operator] support existing volume usage in Grafana Operator Chart template

### ISSUE THREAD

**Issue by tprakash17** [bitnami/charts#14796]
### Name and Version

bitnami/grafana-operator 2.7.17

### What is the problem this feature will solve?

currently template here https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/templates/grafana.yaml#L20-L42 doesn't support existing volume to be specified. 

**Grafana Operator now supports existing volume to be specified**. Please refer the link 👇 

https://github.com/grafana-operator/grafana-operator/blob/master/deploy/examples/persistentvolume/Grafana-existingVolume.yaml#L14

### What is the feature you are proposing to solve the problem?

It will allow users of this chart to supply existing volume to Grafana via this chart.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward this to the team. If you want to speed up the process, would you like to submit a PR?

**Comment by tprakash17** [comment]
yes i can do that. do we have a process around it? any doc @javsalgar

**Comment by javsalgar** [comment]
Hi,

Thank you so much! Here you can find the [contribution guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

**Comment by tprakash17** [comment]
@javsalgar i tried to raise PR but got permission denied.
