### ISSUE TITLE
[bitnami/clickhouse]  how change config max_concurrent_queries?

### ISSUE THREAD

**Issue by Gorniv** [bitnami/charts#14795]
### Name and Version

bitnami/clickhouse:2.2.4

### What steps will reproduce the bug?

helm install clickhouse-aso bitnami/clickhouse --namespace=clickhouse-aso --timeout=10m0s --values=aso/clickhouse/values.yaml

### Are you using any custom parameters or values?
```
# clickhouse-aso
---
global:
  storageClass: "local-storage"

persistence: 
  enabled: true
  size: "8Gi"
  storageClass: "local-storage"
image:
  tag: 22.12.3-debian-11-r0
  debug: true

### What is the expected behavior?

_No response_
```
### What do you see instead?
```
 DB::Exception: Too much simultaneous queries. Maximum: 100
 I finded https://stackoverflow.com/questions/43033077/too-many-simultaneous-queries-in-clickhouse, but I don't understand how I can change config with helm?
```

**Comment by javsalgar** [comment]
Hi,

Did you try the `overrides` section in the values.yaml? There you can add extra ClickHouse settings. Check the upstream documentation on how to change that setting

**Comment by Gorniv** [comment]
work with:
```yaml
defaultConfigurationOverrides: |
  <clickhouse>
    <max_concurrent_queries>20000</max_concurrent_queries>
  </clickhouse>
```
