### ISSUE TITLE
[bitnami/postgresql-ha] immediately starts crashing

### ISSUE THREAD

**Issue by emchristiansen** [bitnami/charts#14803]
### Name and Version

bitnami/postgresql-ha 11.1.1

### What steps will reproduce the bug?

1. Create a fresh Kubernetes cluster with 3 workers and one master.
2. Install [OpenEBS with default values using Helm](https://openebs.github.io/charts/) and make `openebs-hostpath` the default storage class.
3. Install `postgresql-ha` using default values and the instructions in `bitnami/postgresql-ha`.

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

Three `postgresql` pods and a `pgpool` pod should start and run without crashing.

### What do you see instead?

Of the 4 started pods, all crash-loop except `postgresql-ha-postgresql-0`.

### Additional information

I've attached screenshots of various log commands.
It looks like it may be a network configuration issue:

<img width="698" alt="Screenshot 2023-02-08 at 8 34 15 PM" src="https://user-images.githubusercontent.com/225668/217704196-ff8f2299-b23d-49fe-973d-f38b38a9a781.png">

<img width="2056" alt="Screenshot 2023-02-08 at 8 35 25 PM" src="https://user-images.githubusercontent.com/225668/217704235-b6e9e435-30e0-4bff-a92a-621185203aae.png">

<img width="1208" alt="Screenshot 2023-02-08 at 8 34 01 PM" src="https://user-images.githubusercontent.com/225668/217704324-057a047d-2fb7-4b97-8482-c0518e3f894c.png">

<img width="1800" alt="Screenshot 2023-02-08 at 8 34 38 PM" src="https://user-images.githubusercontent.com/225668/217704361-0442a763-c8c9-44d0-9247-f93ff1f5a73a.png">

<img width="819" alt="Screenshot 2023-02-08 at 8 34 57 PM" src="https://user-images.githubusercontent.com/225668/217704388-bc81abd0-baa1-4964-b0e9-0edfedab246d.png">

<img width="808" alt="Screenshot 2023-02-08 at 8 35 08 PM" src="https://user-images.githubusercontent.com/225668/217704416-fb3c72d9-cbb9-4439-a38b-06710518a864.png">

**Comment by javsalgar** [comment]
Hi,

Could you launch the chart with `postgresql.image.debug=true` and `pgpool.image.debug=true`? This should provide more insight on the issue.

**Comment by emchristiansen** [comment]
I'm attaching screenshots of the debug logs for the 4 pods.
Because some logs were longer than one page, in each screenshot the command I ran is the command at the _bottom_ of the screenshot.

<img width="2004" alt="Screenshot 2023-02-09 at 11 12 30 AM" src="https://user-images.githubusercontent.com/225668/217888689-4e98bbb4-5ba1-44f6-9110-3ce009c26911.png">

<img width="1621" alt="Screenshot 2023-02-09 at 11 13 05 AM" src="https://user-images.githubusercontent.com/225668/217888731-c6baf83e-e5cc-4b8e-9d69-5cad13d8f1fb.png">

<img width="1630" alt="Screenshot 2023-02-09 at 11 13 18 AM" src="https://user-images.githubusercontent.com/225668/217888754-47a966ee-70bb-4c5e-ac2e-2cd3fcc0f5d4.png">

<img width="1151" alt="Screenshot 2023-02-09 at 11 14 01 AM" src="https://user-images.githubusercontent.com/225668/217888778-050a7dce-1400-4c27-a739-10693afc3cce.png">

**Comment by emchristiansen** [comment]
FYI, I just re-created this on 3 fresh AWS Ubuntu instances (one controller and two workers).
The instances have all their ports open.

Also, I'm using [`k0s`](https://k0sproject.io/) to create the Kubernetes cluster.

**Comment by quangtamle** [comment]
hi @emchristiansen ,

I have some similar problem just like yours, so my workaround solution is disable readiness (of postgresql) or change the command of the readiness to some linux command like "ls" for example

my problem I described detail [here ](https://github.com/bitnami/charts/issues/14902)

Please try it, if it works in your case, it proves that I am on the right path :))) and it is really a flow bug (in the k8s because of readiness probe, not in legacy way)

**Comment by emchristiansen** [comment]
Thanks @quangtamle.

I think there's a decent chance what I'm seeing is caused by an error with internal Kubernetes routing in my cluster, not related to this chart.
Thus, I'm going to close this issue for now and re-open it after I've definitively ruled that out.
