### ISSUE TITLE
[bitnami/postgresql-ha] How to attach existing pvc if i set replica count more than 1

### ISSUE THREAD

**Issue by tebelyrid** [bitnami/charts#14825]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

if im setting replicacount to for example 3 and want to attach to existing PVC it cannot be done even when pvc set to readwritemany
and there is no instruction how to set primary node to certain pvc and the replica to certain pvc

### What do you see instead?

the pod keep restarting because cannot find existing PVC

**Comment by javsalgar** [comment]
Hi,

Could you show the errors you are finding and the values you are using?

**Comment by tebelyrid** [comment]
First command to create with 1 replica attach to existing PVC

helm upgrade --install pgdummy bitnami/postgresql-ha --set global.storageClass=longhorn,persistence.existingClaim=pgdummy,persistence.size=5Gi \
>     --set postgresql.password=987521 \
>     --set postgresql.repmgrPassword=987521 \
>     --set postgresql.replicaCount=1 \
>     --set postgresql.upgradeRepmgrExtension=true \
>     -n dummy-prod


![Screenshot_1](https://user-images.githubusercontent.com/122161085/218161787-ac9f17f7-93d6-4c70-bbca-8be67b080f63.png)

Then im trying to scale out to 3 nodes got error this with command

helm upgrade --install pgdummy bitnami/postgresql-ha --set global.storageClass=longhorn,persistence.size=5Gi \
>     --set postgresql.password=987521 \
>     --set postgresql.repmgrPassword=987521 \
>     --set pgpool.adminPassword=987521 \
>     --set postgresql.replicaCount=2 \
>     -n dummy-prod

![image](https://user-images.githubusercontent.com/122161085/218161987-2f2c4a05-3c7e-4fd9-935c-3818acda08b1.png)

**Comment by fmulero** [comment]
Hi @tebelyrid, sorry for my very late response.

I am trying to reproduce your issue with chart version 11 and I am not getting that error. Have you give it a try?
