### ISSUE TITLE
[bitnami/mongodb] Add network policy to deny traffic

### ISSUE THREAD

**Issue by dung-tien-nguyen** [bitnami/charts#14828]
### Name and Version

bitnami/mongodb 13.6.7

### What is the problem this feature will solve?

Add network policy to deny all traffic from out side to the namespace. That is useful when admin want to suspend Mongodb service provisioning.

### What is the feature you are proposing to solve the problem?

Add file network_policy.yaml and values in values.yaml file.

### What alternatives have you considered?

I think this feature is a basic , I wonder why it hasn't been developed yet?

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Would you like to submit a PR with it? As a workaround, you can use the `extraDeploy` array to add any extra YAML you need for your use case.
