### ISSUE TITLE
Helm Chart Support for Kafka version 3.4.0

### ISSUE THREAD

**Issue by TheDukeDK** [bitnami/charts#14829]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

A CVE affecting kafka version 3.3.2 has been identified. https://kafka.apache.org/cve-list

### What is the feature you are proposing to solve the problem?

A new version of the helm chart with app version 3.4.0 would allow us to upgrade our kafka instances and mitigate this CVE in accordance with our security policies.

### What alternatives have you considered?

Modifying existing chart with new image version. But would prefer **not** to do this.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by carrodher** [comment]
We are happy to announce that there is a new Helm chart bundling the latest Kafka version (3.4.0), see https://github.com/bitnami/charts/pull/14943
