### ISSUE TITLE
Make the chart mysql working with mysql 5.7 version

### ISSUE THREAD

**Issue by gecube** [bitnami/charts#14827]
### Name and Version

bitnami/mysql-9.4.8

### What steps will reproduce the bug?

1. Take the chart with all default values
2. change the image and repo to :

```yaml
    image:
      registry: docker.io
      repository: bitnami/mysql
      tag: 5.7.41-debian-11-r5
```

3. Find that the mysql server is not running.

```bash
mysql % kubectl logs dbserver-mysql-0  
mysql 09:19:58.04 
mysql 09:19:58.05 Welcome to the Bitnami mysql container
mysql 09:19:58.05 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 09:19:58.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 09:19:58.06 
mysql 09:19:58.06 INFO  ==> ** Starting MySQL setup **
mysql 09:19:58.08 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 09:19:58.08 INFO  ==> Initializing mysql database
mysql 09:19:58.09 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 09:19:58.09 INFO  ==> Using persisted data
mysql 09:19:58.11 INFO  ==> Running mysql_upgrade
mysql 09:19:58.12 INFO  ==> Starting mysql in background
```

### Are you using any custom parameters or values?

yes, I provided the values before.

### What is the expected behavior?

The mysql 5.7 is perfectly running as mysql of the latest version. I'd like to emphasise that there are no issues with running on top of 8.0.32-debian-11-r0 image.

The correct run on 8.0.32 looks like

```bash
mysql % kubectl logs dbserver-mysql-0 
mysql 08:45:48.52 
mysql 08:45:48.52 Welcome to the Bitnami mysql container
mysql 08:45:48.52 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 08:45:48.52 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 08:45:48.53 
mysql 08:45:48.53 INFO  ==> ** Starting MySQL setup **
mysql 08:45:48.54 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 08:45:48.55 INFO  ==> Initializing mysql database
mysql 08:45:48.56 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 08:45:48.57 INFO  ==> Installing database
mysql 08:45:54.31 INFO  ==> Starting mysql in background
mysql 08:45:56.32 INFO  ==> Configuring authentication
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 08:45:56.42 INFO  ==> Running mysql_upgrade
mysql 08:45:56.42 INFO  ==> Stopping mysql
mysql 08:45:58.44 INFO  ==> Starting mysql in background
find: '/docker-entrypoint-startdb.d/': No such file or directory
mysql 08:46:06.47 INFO  ==> Stopping mysql
mysql 08:46:09.48 INFO  ==> ** MySQL setup finished! **

mysql 08:46:09.50 INFO  ==> ** Starting MySQL **
```

### What do you see instead?

please get below.

### Additional information

I'd like to kindly ask to make the chart compatible with mysql-5.7 as 5.7 is still supported till the October of 2023. We need it to spin up test environments. So I am looking right now for any option to do it.

**Comment by carrodher** [comment]
Unfortunately, Bitnami Helm charts are tied to a specific version of the application. If there is more than one branch supported by the application, the one selected to be used in the Helm chart is the latest one according to the upstream releases.

Using a different version can or can't work, but it is not something supported out of the box since the Helm chart (as an isolated package) is built and tested using a specific version (MySQL 8.x in this case).

If you would like to contribute to this Helm chart by fixing any issue to make it compatible with both versions, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by gecube** [comment]
@carrodher Thanks, I will make further investigation.
