### ISSUE TITLE
[bitnami/cert-manager] Services are not being created unless .Values.metrics.enabled is true

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#14835]
### Name and Version

bitnami/cert-manager:0.8.12

### What steps will reproduce the bug?

It seems like you need to enable metrics before services related to cert-manager can be created.
These services are necessary to be made for the CRD of cert-manager to work.

or am I completely wrong with my assumptions?

### What do you see instead?

CRD of cert-manager should work.

**Comment by javsalgar** [comment]
Hi,

Could you explain what elements stopped working when not enabling the service? In principle cert-manager should talk to the K8s API, so I'm not sure if the service exposing is actually necessary.

**Comment by nc-ruth** [comment]
Hi @javsalgar 

When you create certificates by using the CRDs the controller needs to talk with fx. webhook service. 
But since we had disabled metrics exporter, these service resources was not created. 

Therefor the certificates could not be created, and was failing due to not being able to talk with the webhook service. 
![image](https://user-images.githubusercontent.com/41048990/218445773-2bbc4568-df6e-4e17-8e4a-80c2fa71689b.png)

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Would you like to submit a PR fixing the issue with the webhook?
