### ISSUE TITLE
[Thanos] kube-prometheus-stack open shards and thanos how to configure it?

### ISSUE THREAD

**Issue by Hello-Linux** [bitnami/charts#14842]
### Name and Version

bitnami/thanos11.6.8

### What steps will reproduce the bug?

Hello，I use kube-prometheus-stack helm chart install prometheus，and the replics is 2 and shards: 3
```
prometheus-kube-prometheus-stack-prometheus-0              
prometheus-kube-prometheus-stack-prometheus-1 
prometheus-kube-prometheus-stack-prometheus-shard-1-0
prometheus-kube-prometheus-stack-prometheus-shard-1-1 
prometheus-kube-prometheus-stack-prometheus-shard-2-0
prometheus-kube-prometheus-stack-prometheus-shard-2-1
```
the thanos sidecar service is a nodeport type, and nodeip is 192.168.0.165:30901,endpoints(192.168.26.132,192.168.25.237,192.168.26.113,192.168.25.140,192.168.26.119,192.168.25.188)
then I set 
```yaml
stores:
 - 192.168.0.165:30901
 ```
 in thanos values.yaml,There are six sidecars in total, but thanos query ui show only one sidecar(prometheus-kube-prometheus-stack-prometheus-shard-2-1) was found
![000](https://user-images.githubusercontent.com/17851645/218295018-1e198829-d683-44a7-b354-139b85837529.png)

How can I let thanos query find all sidecars after prometheus-operator shards

### What is the expected behavior?
I should find six sidecars on thanos quary ui for stores

**Comment by Hello-Linux** [comment]
who can help me @carrodher  @jiphex  @michaelklishin  @brew

**Comment by brew** [comment]
Given I last committed to this repo in 2018 (for an unrelated chart), randomly tagging me into a thread probably isn't going to get you the response you expect.

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by bmgante** [comment]
@Hello-Linux just wondering if you were able to solve this. Also, any chance of providing your lune-Prometheus-stack and thanos values.yaml? I am trying to setup it but having some issues.
Thanks a lot in advance.
