### ISSUE TITLE
bitnami/contour   passing value into boot strap config

### ISSUE THREAD

**Issue by Daxcor69** [bitnami/charts#14845]
### Name and Version

bitnami/contour helm version 10.2.0  app version 1.23.2

### What steps will reproduce the bug?

I need to pass boot strap values into the helm chart but I can find where that is possible. Here are the values

https://projectcontour.io/docs/v1.24.1/configuration/#bootstrap-config-file

this is the only place I can think of.

```yaml
## @param contour.extraArgs [array] Extra arguments passed to Contour container
##
extraArgs: []
```
Can you please advise.

### What do you see instead?
```yaml
## @param contour.bootstrap [array] Extra arguments passed to Contour boot strap container
##
bootstrap: []
```

**Comment by Daxcor69** [comment]
There is a debug port on 6060 that is used for profiling.
https://projectcontour.io/docs/v1.24.1/troubleshooting/profiling-contour/

This needs to be added as well for the contour deployment.

```
            - name: debug
              containerPort: 6060
              protocol: TCP
```

**Comment by CeliaGMqrz** [comment]
Hi @Daxcor69, sorry for the delay.

Thanks for reporting this issue. I think that you can use the initContainers param:

```.yaml
  ## @param envoy.initContainers [array] Attach additional init containers to Envoy pods
  ## For example:
 initContainers:
  - name: bootstrap-container-name
     image: your-image/bootstrap
     imagePullPolicy: Always
    

```

However, we could implement this as a new feature for our chart. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
