### ISSUE TITLE
[bitnami/keycloak] Exchange Token for clients within same Realm throws access_denied 

### ISSUE THREAD

**Issue by happy0088** [bitnami/charts#14840]
### Name and Version

bitnami/keycloak appVersion: 20.0.3

### What steps will reproduce the bug?

I am upgrading from V14 to V20 .
1. logged in user - abc@xyz.com 
   generate a token as a public client using **client1** .
2. Try to run an exchange token call with **client1** - returns proper token with
```
"aud": [
    "account",
    "client1"
  ]
```
4. When i try to run an exchange token with another **client2** - it throws error 
`error=not_allowed, reason='client is not the token holder', auth_method=token_exchange, grant_type=urn:ietf:params:oauth:grant-type:token-exchange, client_auth_method=client-secret",`

There is one observation that the public client token carries client1 entry as 
`"azp": "client1" `(since the token was generated using client1)

i have the features enabled :
```
extraEnvVars:
  - name: KC_FEATURES
    value: admin-fine-grained-authz,token-exchange,scripts

```
This functionality was working perfectly fine in V14 but started throwing error with V20.

I came across this below documentation from keycloak which talks about 
i) explicit permission setup for the target client(client2 i believe in our case ) (**not doing this for V14**) and 
ii) sending extra params in the header for the exchange calls . (**which we are already doing even in V14**)
https://www.keycloak.org/docs/latest/securing_apps/index.html#internal-token-to-internal-token-exchange

This seems little difficult in my scenario since we are creating clients on the fly from application and doing the permission registration will be very difficult 

a) is there any breaking change in V20 around this area (couldn't find one in the release docs - https://www.keycloak.org/docs/latest/release_notes/index.html )
b) If yes, then can we do this programmatically ?

### Are you using any custom parameters or values?

```
extraEnvVars:
  - name: KC_FEATURES
    value: admin-fine-grained-authz,token-exchange,scripts
```

### What is the expected behavior?

The exchange token should be generated as it was in V14 

### What do you see instead?

access_denied

**Comment by happy0088** [comment]
Just tried enabling the feature, added policy and sending the headers as well , but couldnt get it working.

**Comment by javsalgar** [comment]
Hi,

It seems to me that this question is more related to the application itself rather than the Bitnami packaging of the application. My advice would be to check first with the upstream keycloak devs and, if there's something we need to change in the packaging, then let us know so we can work on it.

**Comment by happy0088** [comment]
Thanks @javsalgar .

Linking the upstream ticket for the users 
[https://github.com/keycloak/keycloak/issues/17008](
https://github.com/keycloak/keycloak/issues/17008)
