### ISSUE TITLE
Support Labels on ServiceAccount

### ISSUE THREAD

**Issue by UXabre** [bitnami/charts#14847]
### Name and Version

bitnami/keycloak:14.0.0

### What is the problem this feature will solve?

Currently, we're using Workload Identity to federate our Service Account with Azure AD. Via a label `"azure.workload.identity/use: "true""` is communicated to the AKS binding that this serviceaccount should use `workload.identity`. Currently, only annotations are supported (which is also needed for workload identity to work, as I needed to set the ClientID)

### What is the feature you are proposing to solve the problem?

Next to annotations, support labels for the service account, I see many other projects that use serviceaccounts to also expose this.

### What alternatives have you considered?

The alternative, like I'm doing right now, is not letting the helm chart create the service account but creating it as part of a parent chart which creates this for me.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by UXabre** [comment]
Yes, i'm already working on it as it's trivial to add it i think. Will create the pr tomorrow as I want to go over the contribution doc thoroughly:-)
