### ISSUE TITLE
matomo error after restart, permissions issue

### ISSUE THREAD

**Issue by houssembaprotectline** [bitnami/charts#14853]
### Name and Version

bitnami/matomo:4.13.1-debian-11-r3

### What steps will reproduce the bug?

After the first reboot,  I had permissions issues.

```
rsync: chgrp "/bitnami/matomo/plugins/VisitorInterest" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitorInterest/Columns" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitorInterest/Reports" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitorInterest/config" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitorInterest/lang" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary/Reports" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary/Widgets" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary/config" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary/lang" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary/stylesheets" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/VisitsSummary/templates" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/WebsiteMeasurable" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/WebsiteMeasurable/Settings" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/WebsiteMeasurable/config" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/WebsiteMeasurable/lang" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/angularjs" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/angularjs/export-widget" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/angularjs/widget-preview" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/config" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/lang" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/stylesheets" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/templates" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
```

**Comment by carrodher** [comment]
Bitnami containers are non-root by default, which means any file/dir used by the application should belong to the _root_ group since the random user (_1001_ by default) is part of this _root_ group. You should adapt the permission of your local directory so the _root_ group is the owner.

You can find more info about non-root containers at
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

**Comment by houssembaprotectline** [comment]
Hi @carrodher 
Thanks for your answer, but I am using a deploy with a noroot user.
Below is my deployment:
---
# Source: matomo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  namespace: "ft-offres-matomo-dev"
  labels:
    app.kubernetes.io/name: matomo
    helm.sh/chart: matomo-0.2.18
    app.kubernetes.io/instance: matomo
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo
      app.kubernetes.io/instance: matomo
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo
        helm.sh/chart: matomo-0.2.18
        app.kubernetes.io/instance: matomo
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/port: "9117"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        runAsUser: 1001
      affinity:          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: matomo
                    app.kubernetes.io/instance: matomo
                topologyKey: kubernetes.io/hostname
              weight: 1          
      priorityClassName: ""
      hostAliases:
        - hostnames:
          - status.localhost
          ip: 127.0.0.1
      containers:
        - name: matomo
          image: 098808187153.dkr.ecr.eu-west-3.amazonaws.com/offres_matomo:4.13.3-debian-11-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
            - name: MATOMO_DATABASE_HOST
              value: "wso2-dev.ccg8em1doyst.eu-west-3.rds.amazonaws.com"
            - name: MATOMO_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MATOMO_DATABASE_NAME
              value: "matomo-dev"
            - name: MATOMO_DATABASE_USER
              value: "matomo"
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matomo-db-cred
                  key: "db-password"
            - name: MATOMO_SKIP_BOOTSTRAP
              value: "no"
            - name: MATOMO_USERNAME
              value: "admin"
            - name: MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matomo-password
                  key: matomo-password
            - name: MATOMO_EMAIL
              value: "admin.matomo@protectline.fr"
            - name: MATOMO_WEBSITE_NAME
              value: "localhost"
            - name: MATOMO_WEBSITE_HOST
              value: "https://localhost"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits: {}
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: matomo-data
              mountPath: /bitnami/matomo
        - name: metrics
          image: 098808187153.dkr.ecr.eu-west-3.amazonaws.com/offres_matomo/apache-exporter:0.11.0-debian-11-r87
          imagePullPolicy: "IfNotPresent"
          command: [ '/bin/apache_exporter', '--scrape_uri', 'http://status.localhost:8080/server-status/?auto' ]
          ports:
            - name: metrics
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources: 
            {}
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: matomo-matomo
        - name: matomo-configuration
          configMap:
            name: matomo-configuration

**Comment by houssembaprotectline** [comment]
Hello,
I use a deploiement with a persistent volume, when the pod is restarted,  with user 1001, i had a permissions issues at startup.
Please help me i'm blocked.

[38;5;6mmatomo [38;5;5m09:50:42.06 [0m[38;5;2mINFO [0m ==> Persisted Matomo installation detected
[38;5;6mmatomo [38;5;5m09:50:42.06 [0m[38;5;2mINFO [0m ==> Updating default plugins in persisted data
rsync: [generator] chgrp "/bitnami/matomo/plugins/." failed: Operation not permitted (1)
rsync: [generator] chgrp "/bitnami/matomo/plugins/API" failed: Operation not permitted (1)
.
.
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/stylesheets" failed: Operation not permitted (1)
rsync: chgrp "/bitnami/matomo/plugins/Widgetize/templates" failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
[matomo.log](https://github.com/bitnami/charts/files/10731060/matomo.log)

**Comment by migruiz4** [comment]
Hi @houssembaprotectline,

I see your deployment has the following pod SecurityContext:
```
    spec:
      securityContext:
        runAsUser: 1001
```

While the default value would be:
```
    spec:
      securityContext:
        fsGroup: 1001
```

This value is configure through the value `podSecurityContext`, is it possible you are overriding it?

Setting `fsGroup: 1001` in the pod securityContext is important, so user 1001 running the process inside the container has permissions over the mounted persistent volumes.

https://github.com/bitnami/charts/blob/9d615e705b4dd7442ae0d8a8ab857203b2904d6a/bitnami/matomo/values.yaml#L323-L330

**Comment by houssembaprotectline** [comment]
Hello @migruiz4 ,

I still have the same problem with fsGroup: 1001.
I am using an efs type persistent volume for matomo.

spec:
  storageClassName: efs-sc
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "8Gi"

On the 1st start everything is ok, but when restarting the matomo pod, cannot updating default plugins in persisted data.

**Comment by houssembaprotectline** [comment]
Hi @migruiz4,
I already tried this:

      initContainers:
        - name: volume-permissions
          image: 098808187153.dkr.ecr.eu-west-3.amazonaws.com/transverse_bitnami-shell:11-debian-11-r73
          imagePullPolicy: "IfNotPresent"
          command:
            - sh
            - -c
            - |
              mkdir -p "/bitnami/matomo"
              chown -R "1001:1001" "/bitnami/matomo"
          securityContext:
            runAsUser: 0
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: matomo-data
              mountPath: /bitnami/matomo

But i have this error:
chown: changing ownership of '/bitnami/matomo': Operation not permitted

**Comment by migruiz4** [comment]
Hi @houssembaprotectline,

The issue may not be related to the chart but to the EFS provisioner: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300

That is why even as `root` user, trying to change the ownership of the files doesn't work. The issue might be caused by the underlying NFS (EFS) user-mapping.

I'm sorry but helping with the EFS provisioner would be out of my scope, but I would recommend checking their documentation here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.5.1/docs/README.md

**Comment by houssembaprotectline** [comment]
Thanks @migruiz4 
I need to update aws efs csi driver in my cluster
Best regards

**Comment by mmelcot** [comment]
On my side I had the following:

The Helm chart was deploying Matomo DB and App with a non-root user with uid 1001.

However the NFS server that provided me the NFS on which I had my DB and app volume had no 1001 user.
So as soon as I tried to `chown` the `app` and `db` files with `chown 1001:1001 -R ...`, the ownership was automatically set to 65534 (aka 'nobody:nogroup')

However this NFS share supported the `1000:1000` user:group. 
So I `chown 1000:1000 -R app` and `chown 1000:1000 -R db`.

I can then see that it was correctly applied, if I run `ls -ln` to show the ids.

Then I put the following attributes in my helm chart:
```
# Forcing uid 1000 for 'db' container
mariadb:
  auth:
  primary:
    containerSecurityContext:
      runAsUser: 1000

# Forcing uid 1000 for 'app' container
podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
```

And it works

**Comment by santavizma** [comment]
@houssembaprotectline which efs csi driver helm chart version solved Your issue?

**Comment by lastdil** [comment]
Hello there

This is my workaround, hope this will helpful for someone

I create the special StorageClass

`resource "kubernetes_storage_class" "matomo-efs" {
  metadata {
    name = "matomo-efs"
  }
  storage_provisioner = "efs.csi.aws.com"
  reclaim_policy        = "Delete"
  volume_binding_mode   = "Immediate"
  parameters = {
    basePath = "/dynamic_provisioning"
    directoryPerms = "700"
    fileSystemId = data.terraform_remote_state.efs.outputs.efs_id
    provisioningMode = "efs-ap"
    uid = "1001"
    gid = "0"
  }
}`

Then update the chart values

`persistence:
  storageClass:  matomo-efs
  accessModes:
    - ReadWriteMany`
    
 I use aws-efs-csi-driver with version v1.7.1 (aws-efs-csi-driver-2.5.1 helm chart version) - version is very important.
 
 So it's works!

**Comment by lastdil** [comment]
@santavizma Hello
You can use gp2/3 for Mariadb PVC, so I am not facing any errors.

I only use efs for Matomo deployment.

**Comment by adepuone** [comment]
@lastdil can you plz share the link for the helm chart you were using, i am still facing the same issue.

I have tried to create the storage class as per your suggestion, the matomo

**Comment by lastdil** [comment]
@adepuone 
I'm using this one 

```hcl
module "matomo" {
  namespace  = "matomo"
  repository = "oci://registry-1.docker.io/bitnamicharts"

  app = {
    name          = "matomo"
    version       = "5.1.0"
    chart         = "matomo"
```

Unhealthy state is okay for some time during startup, after some minutes it will be healthy, just wait please

Also, you can try to remove Helm release and re-install it (don't forget remove pvc)

Plus please check the matomo logs if it fails probes

**Comment by adepuone** [comment]
kubectl get pods -n pzero | grep -i mato
matomo-57c5f4f6d5-8bf5r                         0/1     Running            8 (2m9s ago)     83m
matomo-archive-28434070-q4sh4                   0/1     Completed          0                25m
matomo-archive-28434075-smg4s                   0/1     Completed          0                17m
matomo-archive-28434085-s2kqt                   0/1     Completed          0                9m31s
matomo-archive-28434095-xg5pn                   1/1     Running            0                89s
matomo-mariadb-0                                1/1     Running            0                83m
matomo-scheduled-tasks-28434070-66nzp           0/1     Completed          0                26m
matomo-scheduled-tasks-28434075-7qsml           0/1     Completed          0                17m
matomo-scheduled-tasks-28434085-kh6f7           0/1     Completed          0                9m22s
matomo-scheduled-tasks-28434095-7f28d           1/1     Running            0                59s

kubectl describe pod matomo-57c5f4f6d5-8bf5r -n pzero | less

Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  9m28s (x767 over 84m)  kubelet  Readiness probe failed: Get "http://100.64.134.169:8080/matomo
.php": dial tcp 100.64.134.169:8080: connect: connection refused
  Warning  Unhealthy  4m32s (x193 over 37m)  kubelet  Readiness probe failed: Get "http://100.64.134.169:8080/matomo
.php": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
q

This is what i see in pod logs
![image](https://github.com/bitnami/charts/assets/157525360/344de5cb-56d4-4c61-a2fe-d96c0032123c)

**Comment by hkm15022001** [comment]
> Hello there,
> 
> This is my workaround, and I hope it will be helpful for someone.
> 
> I created a special StorageClass using Terraform:
> 
> resource "kubernetes_storage_class" "matomo-efs" {
>   metadata {
>     name = "matomo-efs"
>   }
>   storage_provisioner = "efs.csi.aws.com"
>   reclaim_policy     = "Delete"
>   volume_binding_mode = "Immediate"
>   parameters = {
>     basePath        = "/dynamic_provisioning"
>     directoryPerms  = "700"
>     fileSystemId    = data.terraform_remote_state.efs.outputs.efs_id
>     provisioningMode = "efs-ap"
>     uid             = "1001"
>     gid             = "0"
>   }
> }
> Then update the chart values:
> 
> persistence:
>   storageClass: matomo-efs
>   accessModes:
>     - ReadWriteMany
> I use aws-efs-csi-driver with version v1.7.1 (aws-efs-csi-driver-2.5.1 helm chart version) - version is very important.
> 
> So it's works!

hi, let me ask that if my storageClass has gid and uid as 1000:1000, how do I need to configure matomo helm chart to make it work? I tried setting podSecurityContext.fsGroup: 1000 and containerSecurityContext.runAsUser: 1000 but it still doesn't work
