### ISSUE TITLE
[bitnami/rabbitmq] v11.9.0 Chart version issue - Readiness probe failed

### ISSUE THREAD

**Issue by orsharab** [bitnami/charts#14875]
### Name and Version

bitnami/rabbitmq 11.9.0

### What steps will reproduce the bug?

Upgrade from chart version 10.3.9 to 11.9.0 with this command (replaced only the version flag)
`helm upgrade --install hbs-rabbitmq --version 11.9.0 --set auth.tls.failIfNoPeerCert=false,auth.tls.enabled=true,auth.tls.autoGenerated=true,auth.username=app,auth.password={MY_PASSWORD},auth.erlangCookie={MY_ERLANG_COOKIE},image.registry=hbsdevops.azurecr.io bitnami/rabbitmq -f rabbitmq-values.yaml`

### Are you using any custom parameters or values?

Below rabbitmq-values.yaml (attached as txt since yaml is not allowed) 
[rabbitmq-values.txt](https://github.com/bitnami/charts/files/10733396/rabbitmq-values.txt)

### What is the expected behavior?

Stateful set pod's in healthy state

### What do you see instead?

Upgrade was successful although the stateful set pods were failing with the following message:
![image](https://user-images.githubusercontent.com/109510961/218782221-3b81b348-7c65-4f30-a07d-1cb96500c1cc.png)

**Comment by elchenberg** [comment]
I am trying to install 11.9.1 and when I enable the debug log output I see the following error:

```
2023-02-14 18:12:36.892201+00:00 [error] <0.132.0> Error parsing configuration:
2023-02-14 18:12:36.898553+00:00 [error] <0.132.0>   - Syntax error in /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf after line 38 column 1, parsing incomplete
2023-02-14 18:12:36.898582+00:00 [error] <0.132.0> Are these files using the Cuttlefish format?
```

Line 38 is the `tcp_listen_options.linger.on` part of the newly added TCP listen options:

```
## TCP Listen Options
##
tcp_listen_options.backlog = 128
tcp_listen_options.nodelay = true
tcp_listen_options.linger.on      = 
tcp_listen_options.linger.timeout = 0
tcp_listen_options.keepalive = false
```

Maybe this is the same issue?

**Comment by elchenberg** [comment]
I do not know why Helm lets the "true" disappear for "tcp_listen_options.linger.on" when it works for "tcp_listen_options.nodelay". But when I add the "true" manually to the config secret in the namespace RabbitMQ boots without any issues.

**Comment by matteogazzadi** [comment]
> I do not know why Helm lets the "true" disappear for "tcp_listen_options.linger.on" when it works for "tcp_listen_options.nodelay". But when I add the "true" manually to the config secret in the namespace RabbitMQ boots without any issues.

https://github.com/bitnami/charts/issues/14766

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Definitely, the chart needs to change that `on` reserved keyword for another. Maybe `enabled`? Would you like to submit a PR?
