### ISSUE TITLE
[bitnami/kube-prometheus] prometheus-operator ClusterRole lacks the permission to alertmanagers/status

### ISSUE THREAD

**Issue by Jack296s** [bitnami/charts#14889]
### Name and Version

bitnami/kube-prometheus 8.3.5

### What steps will reproduce the bug?

Deploy `bitnami/kube-prometheus 8.3.5` with `charts/bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

prometheus-operator ClusterRole has the permission to alertmanagers/status

### What do you see instead?

The error log of prometheus-operator pod:
```
func=ErrorDepth msg="status \"monitoring/monitoring-kube-prometheus-alertmanager\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"monitoring-kube-prometheus-alertmanager\" is forbidden: User \"system:serviceaccount:monitoring:monitoring-kube-prometheus-operator\" cannot update resource \"alertmanagers/status\" in API group \"monitoring.coreos.com\" in the namespace \"monitoring\
```

### Additional information

should add `- alertmanagers/status` to `rules.resources` in charts/bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Jack296s** [comment]
@carrodher I upgrade my chart version to 8.3.6, but prometheus-operator log still shows error log below:
`failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"monitoring-kube-prometheus-alertmanager\" not found`

Does **charts/bitnami/kube-prometheus/crds/crd-alertmanager.yaml** need to be modified?

**Comment by marcosbc** [comment]
Hi @Jack296s, you could try and make the change locally, and see if it resolves the issue in your cluster. If so, feel free to send a PR fixing this.

**Comment by ghartm** [comment]
We do now have two versions of the prometheuses api implementation with the same apiVersion number v1.
One with status subresource and the older one without.

**Comment by migruiz4** [comment]
Hi @ghartm, 
Could you please provide more details about your issue? Any logs, command output, or steps to reproduce your issue would be helpful.

If possible, please report your issue in a separate post so we can give you better assistance.
