### ISSUE TITLE
"Get Started with Helm" link is broken at the url https://bitnami.com/stack/redis/helm

### ISSUE THREAD

**Issue by MichaelSchmidt-outbound-ai** [bitnami/charts#14900]
### Name and Version

Production web site

### What steps will reproduce the bug?

On the bitnami website at the url https://bitnami.com/stack/redis/helm

the link "Get started with Helm" is broken/ends at a 
```
----------
404
Not Found
nginx
----------
```
page

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Takes me to the expected page

### What do you see instead?
```
404
Not Found
nginx
```
### Additional information

Well I would really like to see that page so there is that

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for reporting this. 
  We are working to fix it, we will be back as soon as we have news.

**Comment by rafariossaa** [comment]
Hi, 
    That page was removed some time ago, so I have removed those dead links.
    This was also affecting other assets too.
