### ISSUE TITLE
[bitnami/kafka]Can the file size in KAFKA_VOLUME_DIR exceed the log.retention.bytes limit?

### ISSUE THREAD

**Issue by yuhuyuyu** [bitnami/charts#14904]
### Name and Version

bitnami/kafka 19.1.0

### What steps will reproduce the bug?

Deploy kafka normally, and then continue to use kafka normally.

### Are you using any custom parameters or values?

"log.retention.hours": 1

### What is the expected behavior?

I'm not quite sure what data is supposed to be stored in bitnami/kafka/data. I'm guessing it's supposed to hold some metadata about the topic and log files? 
I see that bitnama/kafka has a pv of 8Gi set in value.yaml, which I have not changed. In practice, I find that the files in bitnami/kafka/data are growing, and even some of the topic-partition folders are larger than the default 1Gi of log.retention.bytes. I wonder if there is no way for log.retention.bytes to make bitnami/ kafka/data to be deleted automatically? How should I limit the size of the files in bitnami/kafka/data to avoid a pod restart?

### What do you see instead?

As expected, the files in bitnami/kafka/data will be automatically deleted according to the settings of log.retention.hours and log.retention.bytes.But in fact, it is always growing.

**Comment by jotamartos** [comment]
Hi,

[the log.dirs parameter](https://kafka.apache.org/documentation/#brokerconfigs_log.dirs) configures a list of the directories where the log data is stored. That parameter is configured to /bitnami/kafka/data by default

https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L839

Kafka should automatically delete the content of the logs' dir [according to its documentation](https://kafka.apache.org/documentation/#brokerconfigs_log.retention.bytes). However, as the [log.segment.bytes](KAFKA_SEGMENT_BYTES) is configured with [the same size](https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml#L161), the log is never bigger than that value and it's not removed. You can configure different values according to your needs.
