### ISSUE TITLE
PostgreSQL chart should allow distinct ServiceAccounts for primary and read Pods

### ISSUE THREAD

**Issue by akloss-cibo** [bitnami/charts#14929]
### Name and Version

bitnami/postgresql 12.1.9

### What is the problem this feature will solve?

PostgreSQL primaries and read replicas have intersecting, but not equal, access requirements.  In particular, read replicas should *never* push a WAL file to the archive storage as this is indicative of a major misconfiguration which will likely render the WAL archive difficult to use in the future, as it'll have a mix of two different timelines in it.

### What is the feature you are proposing to solve the problem?

Add configuration options to allow a distinct ServiceAccount to be specified for the primary and read StatefulSets.

### What alternatives have you considered?

Rolling our own PostgreSQL chart.  We already build our own image to address https://github.com/bitnami/charts/issues/12477 and inject multiple containers into the StatefulSets to make WAL archiving and restore work correctly.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
