### ISSUE TITLE
[bitnami/postgresql-ha] Failover Deadlock in case of master node reboot

### ISSUE THREAD

**Issue by ashish1993** [bitnami/charts#14924]
### Name and Version

binami/postgres-ha

### What steps will reproduce the bug?

Deploy rke2 in HA mode with 3 master nodes
Deploy postgres-HA(3 replicas one across each master node) with pgpool(single replica)
In case of pod restart failover works fine.
In case of master node shutdown. The failover for postgres does not work and goes into deadlock. with remaining 2 in crashloopback.

### Are you using any custom parameters or values?

for env REPMGR_PRIMARY_HOST,REPMGR_NODE_NETWORK_NAME: used $(MY_POD_IP) which will be the pod IP of statefulset

### What is the expected behavior?

Expcted Behavior:  One of the standby node should accept the role of master

### What do you see instead?

Post reboot: The standby nodes retries to connect to disconnect node . however after 5 retries, the pods start election.
In election however election result: CANCELLED and enters to degraded state. 
![image](https://user-images.githubusercontent.com/5062236/219451965-f6bb2bd5-c51d-4257-bdc9-aa3130eef36a.png)

**Post degradation timeout the reelection never happens. How do we enable reelection**

Also after some time all pods go into crashloop waiting for primary(down node) to come up.
![image](https://user-images.githubusercontent.com/5062236/219452424-20c17862-8d85-4ace-b9a0-b2e23abd685c.png)

How do we recover from this. restrrting the pod quicky moves the pods to crash state

Inconclusion I have 2 queries:
**a) Is there any way to enable reelection 
b) how to recover from deadlock of postgres cluster with pods in crashloopback (trying to connect to master which is down)**

### Additional information

![image](https://user-images.githubusercontent.com/5062236/219453402-bdb323b6-131c-49d7-8381-0fdd5059d3ec.png)
Postgres version: 14.6

**Comment by dgomezleon** [comment]
Hi @ashish1993,

> for env REPMGR_PRIMARY_HOST,REPMGR_NODE_NETWORK_NAME: used $(MY_POD_IP) which will be the pod IP of statefulset

Why are you changing these values? The chart manages it in order to detect the correct IP of  REPMGR_PRIMARY_HOST and this is not supposed to be changed. 

You could place 1 pod in each node by playing with taints / toletarions or nodeAffinity.

I hope it helps

**Comment by ashish1993** [comment]
@dgomezleon Earlier it was the dns for first postgres pod(postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local) but post node reboot new master still is not elected. and the other 2 pods keeps on waiting for postgresql-ha-postgresql-0 pod

**Comment by dgomezleon** [comment]
Hi @ashish1993 ,

Could you please elaborate? 

Have you tried it without editing REPMGR_PRIMARY_HOST,REPMGR_NODE_NETWORK_NAME? What result did you obtain?
