### ISSUE TITLE
[bitnami/keycloak] - replicaCount doesn't take effect

### ISSUE THREAD

**Issue by cvallesi-kainos** [bitnami/charts#14932]
### Name and Version

bitnami/keycloak 13.0.4

### What steps will reproduce the bug?

Fresh deployment on an Azure Kubernetes Cluster, setting the `replicaCount` seems to not have any effect.

Then simply run the command `helm install -f keycloak-config.yaml keycloak bitnami/keycloak`.

Deployment happens but there is always just one replica when checking with `kubectl get pods -l app.kubernetes.io/name=keycloak -o wide` as if the parameter is not even detected:

![image](https://user-images.githubusercontent.com/97892370/219606824-fff47eeb-4cd8-4ac0-9320-0f068e9afaf9.png)

### Are you using any custom parameters or values?

Yes, the values are (password replaced):

```
{
  auth.adminPassword=xxxxxxxxxxxxxxxxxxx,
  auth.adminUser=admin-test,
  replicaCount=3,
  autoscaling.enabled=true,
  autoscaling.minReplicas=3,
  autoscaling.maxReplicas=10,
  autoscaling.targetMemory=80
}
```

### What is the expected behavior?

Multiple replicas to be deployed

### What do you see instead?

Only one instance of Keycloak is deployed and the change is not picked up

**Comment by javsalgar** [comment]
Hi,

The replicaCount parameter is not compatible with the autoScaling.enabled one.

```
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
```

I need to remember but I think that there were issues with the HPA when setting a fixed value for the replicas.

**Comment by cvallesi-kainos** [comment]
Thanks, in that case, doing something like this should work?

```
{
  autoscaling.enabled=true,
  autoscaling.minReplicas=3,
  autoscaling.maxReplicas=10,
  autoscaling.targetMemory=80
}
```

But apparently it's not :-/

**Comment by cvallesi-kainos** [comment]
@javsalgar please forgive me, I had an absolute brain fart and was completely using the wrong format for the yaml file.
