### ISSUE TITLE
[bitnami/redis-cluster] template common.names.fullname

### ISSUE THREAD

**Issue by justknife** [bitnami/charts#14941]
### Name and Version

bitmani/redis-cluster

### What steps will reproduce the bug?

when I run the chart setup with standard variables, I get an error
```
Installation error: template: redis-cluster/templates/secret.yaml:5:200: executing "redis-cluster/templates/secret.yaml at <((template "common.names.fullname" .))>: template "common.names.fullname" not defined
```
### Are you using any custom parameters or values?

None

### What do you see instead?
```
Installation error: template: redis-cluster/templates/secret.yaml:5:200: executing "redis-cluster/templates/secret.yaml at <((template "common.names.fullname" .))>: template "common.names.fullname" not defined
```

**Comment by carrodher** [comment]
What version of the Helm chart are you using? Can you also share the command you are using to deploy it? Thanks

**Comment by justknife** [comment]
sorry, i forgot install dependies
