### ISSUE TITLE
[bitnami/parse] Add configuration for enabling cloud code.

### ISSUE THREAD

**Issue by JauntyGame** [bitnami/charts#1500]
There is environment variable for enabling cloud code in **bitnami-docker-parse** image, but it is no way to do this during **bitnami/parse** chart installation.
https://github.com/bitnami/bitnami-docker-parse#how-to-deploy-your-cloud-functions-with-parse-cloud-code
Please add configuration to enable cloud code for parse server deployment via helm chart. Also would be great to have instruction on how to upload files with parse cloud code to **parse-server** pod in case of installation in kubernetes.

**Comment by juan131** [comment]
Hi @JauntyGame 

Thanks so much for your suggestions. I agree with you and we should provide an easy way to configure this in the Helm chart. I just created a task to work on this.

We'll keep you updated.

**Comment by JauntyGame** [comment]
@juan131 thanks for quick feedback. Maybe you can suggest temporal workaround to make cloud code working with parse helm chart?

**Comment by juan131** [comment]
Hi @JauntyGame 

I just created the PR to add support to this feature

**Comment by juan131** [comment]
Hi @JauntyGame

The PR was merged!!

Could you please give a try to the latest version of the chart (**10.1.0**)? In the link below you can find more information about how to add your cloud code scripts in the chart:

- https://github.com/helm/charts/blob/master/stable/parse/README.md#deploy-your-cloud-functions-with-parse-cloud-code

**Comment by alexparfianovich** [comment]
@juan131 confirmed, cloud code working in 10.1.0. Thanks for quick fix!

**Comment by juan131** [comment]
You're welcome @alexparfianovich
