### ISSUE TITLE
[bitnami/keycloak] Chart "keycloak" version "7.0.3" not found in https://charts.bitnami.com/bitnami repository

### ISSUE THREAD

**Issue by drazen-todorovic** [bitnami/charts#15053]
### Name and Version

bitnami/keycloak 7.0.3

### What steps will reproduce the bug?

Running this command:
```
helm show values keycloak --repo https://charts.bitnami.com/bitnami --version 7.0.3
```

I am getting the following error:
```
Error: chart "keycloak" version "7.0.3" not found in https://charts.bitnami.com/bitnami repository
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The expected behaviour is to see values. We are using version 7.0.3 for some of our workloads and it is really important to us to have this version of the chart.

### What do you see instead?

Error: chart "keycloak" version "7.0.3" not found in https://charts.bitnami.com/bitnami repository

**Comment by fmulero** [comment]
Hi Drazen

You can find old versions of the charts using this repo <https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami>. More information about this topic [here](https://github.com/bitnami/charts/issues/10833)

**Comment by drazen-todorovic** [comment]
Dear Fran,

Thanks that solves the issue.
