### ISSUE TITLE
[bitnami/harbor] Harbor field core.existingSecret not mounted on chartmuseum, the default secret IS

### ISSUE THREAD

**Issue by veit-r** [bitnami/charts#15062]
### Name and Version

bitnami/harbor: 16.3.6

### What steps will reproduce the bug?

Deploy the chart with an existing custom secret set as core.existingSecret.
Custom secret holds values for the following keys: "secret", "secretKey".

### Are you using any custom parameters or values?

-

### What is the expected behavior?

The field core.existingSecret is used in the chartmuseum deployment, just like it does in the core deployment:
https://github.com/bitnami/charts/blob/5d5d8d8dc1862c4960594f708d1b8f8a5fb16689/bitnami/harbor/templates/core/core-dpl.yaml#L99-L109

### What do you see instead?

The default secret is used instead, which makes the chartmuseum pod throw an error upon creation (Error: couldn't find key secret in Secret harbor/harbor-core), since I'm using the custom core.existingSecret:

Current behavior:
https://github.com/bitnami/charts/blob/5d5d8d8dc1862c4960594f708d1b8f8a5fb16689/bitnami/harbor/templates/chartmuseum/chartmuseum-dpl.yaml#L118-L121

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay. I sent a PR to fix this. Could you give it a try ?
