### ISSUE TITLE
[bitnami/postgresql-ha] postgres user not known in pgpool

### ISSUE THREAD

**Issue by PassionateDeveloper86** [bitnami/charts#15060]
### Name and Version

bitnami/postgresql-ha 11.1.3

### What steps will reproduce the bug?

1. Use Helmchart with terraform / terragrunt

```
   name       = "postgres-cluster"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "postgresql-ha"
  version    = "11.1.3"
  namespace  = var.kube_namespace

  set {
    name  = "global.postgresql.username"
    value = "one_user"
  }

  set {
    name  = "global.postgresql.password"
    value = var.postgresql_password 
  }
  
  set {
    name = "postgresql.postgresPassword"
    value = "Aaa111"
  }
  
  set {
    name = "auth.enablePostgresUser"
    value = "true"
  }
```

2. Start Helm chart / deploy

### Are you using any custom parameters or values?

see reprocude

### What is the expected behavior?

As far as I understand in the given readme, I would expect 2 users:
1) my user I created with global.postgresql.username without special rights
2) the postgres user with the given email that has super user rights

### What do you see instead?

Only my user will be created within the pgpool, both users seem to be there in the database.
I am not able to log in as postgres user within the database:

### Additional information

1) Datbasae Sceeenshot - has both users:

![grafik](https://user-images.githubusercontent.com/20551244/220063489-0f25279d-39d9-497c-b5eb-dca6c85df2c9.png)

2) When I try to login with postgres it fails:

![grafik](https://user-images.githubusercontent.com/20551244/220063569-34ece796-d8d4-4087-83f3-f720f27c16a6.png)

3) When I see in pgpool logs, there is the same error as shown in the message

4) When looking in the pool_passwd file in the pgpool only one user is there:

![grafik](https://user-images.githubusercontent.com/20551244/220063915-01e31cae-7a2e-4148-bdc3-08f1592ec507.png)

**Comment by aoterolorenzo** [comment]
Hi @PassionateDeveloper86,

How about setting `auth.postgresPassword`?

```
  set {
    name = "auth.postgresPassword"
    value = "Aaa111"
  }
```

**Comment by aoterolorenzo** [comment]
May be related to #14905

**Comment by kkarimi** [comment]
Just facing the same issue with `postgresql-ha `, @aoterolorenzo or others any idea of there was any progress on this?  thank you

**Comment by aoterolorenzo** [comment]
Hi @kkarimi,

I'm afraid the task is still in our backlog. Unfortunately we cannot provide any estimated ETA since the timing depends on the team workload and availability.
