### ISSUE TITLE
[bitnami/argocd] External redis with username and password does not connect

### ISSUE THREAD

**Issue by smolinari** [bitnami/charts#15064]
### Name and Version

bitnami/argocd@latest

### What steps will reproduce the bug?

1. Create a secret with username and password and set up a user in redis with username and password
2. Try to use `externalRedis` with just a password/ using the secret (username isn't possible to offer)
3. Install chart

### What is the expected behavior?

Expect to connect to redis

### What do you see instead?

Redis wait pods fail to connect saying password incorrect or user is disabled. 

### Additional information

I installed using the redis dependency with no issues. I'd like to, however, use my own redis instance. 

Scott

**Comment by fmulero** [comment]
Hi Scott, thanks for using Bitnami helm charts.

At the moment it seems not possible to set the `username` ([Auth command](https://redis.io/commands/auth/)). I think the configuration doesn't have the `username` becase we started working with Redis in version 5. I think this could be blocker in some installations, so I am going to open an internal task to update the charts which use Redis as subchart. Please note that we are a small team and we cannot guarantee an ETA.

**Comment by smolinari** [comment]
@fmulero - Hey Fran. No worries. I'm happy you've noticed the issue and it will be resolved at some point in the future. 

Scott
