### ISSUE TITLE
[magento 2] installed the helm chart successful , but can't reach the login page

### ISSUE THREAD

**Issue by luna1230** [bitnami/charts#1508]
I try to install the helm chart in azure aks using the following command
helm install --name magento2 --set magentoUsername=admin,magentoPassword=password,mariadb.mariadbRootPassword=secretpassword,elasticsearch.sysctlImage.enabled=true azure-marketplace/magento

helm upgrade magento2 azure-marketplace/magento --set magentoHost=137.135.78.64,magentoPassword=password,mariadb.mariadbRootPassword=VnnwmC7aKP,mariadb.db.password=iL0rNyw646

now all pods is running and I could login the admin portal . but when click "login" or "create account" in Home Page http://137.135.78.64
url turn to https://137.135.78.64/index.php/customer/account/login/referer/aHR0cDovLzEzNy4xMzUuNzguNjQvaW5kZXgucGhwLw%2C%2C/
and show can’t reach this page

**Comment by rafariossaa** [comment]
Hi @luna1230 ,
  Is this happening only after upgrading?

**Comment by marcosbc** [comment]
Hi @luna1230, just wanted to let you know that we could reproduce your issue.

The problem happens because Magento is forcing HTTPS in the frontend.

Until we determine a proper fix for existing images, you have two options:

- Use Ingress with HTTPS enabled (recommended)
- Manual fix (check below)

For the manual fix, first connect to the database:

    ROOT_PASS=$(kubectl get secret --namespace default magento2-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
    # Copy the root pass to the clipboard, we will refer to it with %ROOTPASS%

Connect to MySQL:

    mysql -h magento2-mariadb -u root -p%ROOTPASS%

And run the command below:

    UPDATE core_config_data SET value = '0' WHERE path = 'web/secure/use_in_frontend' OR path = 'web/secure/use_in_adminhtml' OR path = 'web/url/redirect_to_base';

And then flush the cache in the Magento container:

    /opt/bitnami/magento/htdocs/bin/magento cache:flush

After that it should work. I've created an internal task for fixing this issue.

**Comment by marcosbc** [comment]
Hi, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

The chart release [17.0.0](https://github.com/bitnami/charts/tree/master/bitnami/magento#1700) includes this new Docker image in case it is useful.

In particular, HTTPS is no longer enabled by default anymore so you should not find these issues anymore.
