### ISSUE TITLE
[bitnami/mariadb] Helm upgrade fails 11.5.0 root missing secret

### ISSUE THREAD

**Issue by githubcdr** [bitnami/charts#15093]
### Name and Version

mariadb 11.5.0

### What steps will reproduce the bug?

Upgrade to 11.5.0 with a rootPassword value set

### What is the expected behavior?

PASSWORDS ERROR: The secret "mariadb" does not contain the key "mariadb-password" 

### What do you see instead?

PASSWORDS ERROR: The secret "mariadb" does not contain the key "mariadb-password" 

### Additional information

secret contains key named  mariadb-root-password

**Comment by javsalgar** [comment]
Hi,

From which version are you trying to upgrade?

**Comment by githubcdr** [comment]
1.4.7 was working here.

**Comment by githubcdr** [comment]
my values

```
metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
    auth:
      rootPassword: haha
    primary:
      configuration: |-
        [mysqld]
        skip-name-resolve
        explicit_defaults_for_timestamp
        basedir=/opt/bitnami/mariadb
        plugin_dir=/opt/bitnami/mariadb/plugin
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        tmpdir=/opt/bitnami/mariadb/tmp
        max_allowed_packet=16M
        bind-address=0.0.0.0
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
        log-error=/opt/bitnami/mariadb/logs/mysqld.log
        character-set-server=UTF8
        collation-server=utf8_general_ci
        performance_schema = 0
        tmp_table_size = 64M
        max_heap_table_size = 64M
        max_allowed_packet = 64M

        query_cache_type = 0
        query_cache_limit = 256K
        query_cache_min_res_unit = 2k
        query_cache_size = 64M
        wait_timeout = 60
        table_definition_cache = 4000

        innodb_log_file_size = 32M
        table_open_cache = 512
        max_heap_table_size = 64M
        tmp_table_size = 64M
        join_buffer_size = 512K

        slow-query-log = 1
        slow-query-log-file = /opt/bitnami/mariadb/logs/mysql-slow.log
        long_query_time = 1

        [client]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        default-character-set=UTF8
        plugin_dir=/opt/bitnami/mariadb/plugin

        [manager]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid      
```

**Comment by CeliaGMqrz** [comment]
Hi @githubcdr,

Thanks for your report.

I have been able to reproduce your error. This is because you must provide your current passwords when upgrading the release. Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims. [More info](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases) 

Please, try this:
```
helm upgrade --install mariadb bitnami/mariadb --version 11.5.0 -f values.yaml  --set auth.password=<your-current-password> -n <your-namespace> --dry-run 
```

If this solves the issue, we welcome your feedback.

**Comment by sereinity** [comment]
The error also happen when we didn't want a custom user to be created, it will work nicely at installation time, create a secret without the `mariadb-password` field as expected.

In the secret.yaml file we can see that `mariadb-password` if `.Values.auth.username` isn't empty; but the template try to read it anyway, even if the value isn't used and has no interest.

We decided to put a dummy value as a password to make the upgrade pass.

**Comment by CeliaGMqrz** [comment]
Hi @sereinity, 

Good point, thanks for the detailed information. It seems that a bug has been introduced after the changes here [#14914](https://github.com/bitnami/charts/pull/14914). We are investigating it.

**Comment by v0112358** [comment]
I have the same issue.

```
STDERR:
  Error: UPGRADE FAILED: template: mariadb/templates/secrets.yaml:4:17: executing "mariadb/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "mariadb.secretName" .) "key" "mariadb-password" "providedValues" (list "auth.password") "context" $)>: error calling include: template: mariadb/charts/common/templates/_secrets.tpl:98:103: executing "common.secrets.passwords.manage" at <fail>: error calling fail:
  PASSWORDS ERROR: The secret "mariadb-infra-next" does not contain the key "mariadb-password"

COMBINED OUTPUT:
  Error: UPGRADE FAILED: template: mariadb/templates/secrets.yaml:4:17: executing "mariadb/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "mariadb.secretName" .) "key" "mariadb-password" "providedValues" (list "auth.password") "context" $)>: error calling include: template: mariadb/charts/common/templates/_secrets.tpl:98:103: executing "common.secrets.passwords.manage" at <fail>: error calling fail:
  PASSWORDS ERROR: The secret "mariadb-infra-next" does not contain the key "mariadb-password"
```

Chart version:
```
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/mariadb       	11.5.3       	10.6.12    	MariaDB is an open source, community-developed ...
```

**Comment by CeliaGMqrz** [comment]
Hi @v0112358, @sereinity, @githubcdr 

Thank you for reporting this. I have been able to reproduce the error. It could be a bug introduced in the latest changes. I have created an internal task to investigate the issue. We'll leave this issue on hold until our dev team works on the related task.

**Comment by smbonn2005** [comment]
Still having an upgrade problem with this chart due to this issue, any update on when this is going to get fixed?

**Comment by fevisera** [comment]
Hi @v0112358, @sereinity, @githubcdr, @smbonn2005,

We have deployed a new chart version (12.1.4) solving the issue informed in this thread. The chart upgrade should not fail anymore due "mariadb-password" secret problem:

```
$ helm install mariadb oci://registry-1.docker.io/bitnamicharts/mariadb -f my-values.yaml -n mariadb
$ helm status -n mariadb mariadb | grep "CHART VERSION"
CHART VERSION: 12.1.4
$ ROOT_PASSWORD=$(kubectl get secret --namespace mariadb mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
$ helm upgrade --namespace mariadb mariadb oci://registry-1.docker.io/bitnamicharts/mariadb --set auth.rootPassword=$ROOT_PASSWORD
Release "mariadb" has been upgraded. Happy Helming!
...
To upgrade this helm chart:

  1. Obtain the password as described on the 'Administrator credentials' section and set the 'auth.rootPassword' parameter as shown below:

      ROOT_PASSWORD=$(kubectl get secret --namespace mariadb mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
      helm upgrade --namespace mariadb mariadb oci://registry-1.docker.io/bitnamicharts/mariadb --set auth.rootPassword=$ROOT_PASSWORD
```

Please, let me know if the problem is solved for you too. The issue is now closed, but feel free to reopen it if you detect the issue is still failing.

Thanks you!
