### ISSUE TITLE
[bitnami/metallb] failed to list v1.Namespace: namespaces is forbidden

### ISSUE THREAD

**Issue by mmianl** [bitnami/charts#15095]
### Name and Version

bitnami/metallb 4.1.16

### What steps will reproduce the bug?

Install the helm chart in a k3s cluster with `rbac.create: true`.

### What is the expected behavior?

Metallb rbac is set-up as required by metallb.

### What do you see instead?

```
W0222 10:06:01.710162       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:metallb-system:metallb-controller" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look.

**Comment by noroutine** [comment]
Hit this too, in a recent release, they require role to have extra access to namespaces as per https://github.com/metallb/metallb/pull/1693/files#diff-bee45811bb40cfbb664509b8d6bc3df42db0197c26b51b562ffefcc741a22e81
