### ISSUE TITLE
Elasticsearch never recovers after cluster restart. Single restart fails cluster forever

### ISSUE THREAD

**Issue by virtuman** [bitnami/charts#1509]
**Which chart**: elasticsearch
all versions

**Description**
Cluster never successfully recovers after restart (data persistence enabled) with message 
`Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid E-nlXOHsSHa_Z8d1S3jDMA than local cluster uuid 4dUYLGC0RvysrkX0-nfqIQ, rejecting`

**Steps to reproduce the issue:**

1. Install helm chart bitnami/elasticsearch with values-production.yml 
2. delete all pods: kubectl delete pods --all
3. notice that some pods recover successfully, but data nodes fail to register with the above mentioned error message

**Describe the results you received:**

`kubectl logs -f elastic-elasticsearch-data-0`

```
[elastic-elasticsearch-data-0 elasticsearch] [2019-10-22T10:46:30,766][INFO ][o.e.c.c.JoinHelper       ] [elastic-elasticsearch-data-0] failed to join {elastic-elasticsearch-master-0}{cCKVF8XTTDCYX0m9FZ14pw}{XYhsq7QeSOyBDA688K8B4g}{10.42.5.237}{10.42.5.237:9300}{m} with JoinRequest{sourceNode={elastic-elasticsearch-data-0}{O1dbIj9JTBKQolnFhAIXAg}{EMV2G2adT7W1EyGVc8H94A}{10.42.5.139}{10.42.5.139:9300}{d}, optionalJoin=Optional.empty}
[elastic-elasticsearch-data-0 elasticsearch] org.elasticsearch.transport.RemoteTransportException: [elastic-elasticsearch-master-0][10.42.5.237:9300][internal:cluster/coordination/join]
[elastic-elasticsearch-data-0 elasticsearch] Caused by: java.lang.IllegalStateException: failure when sending a validation request to node
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.cluster.coordination.Coordinator$2.onFailure(Coordinator.java:513) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1120) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:243) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
[elastic-elasticsearch-data-0 elasticsearch] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
[elastic-elasticsearch-data-0 elasticsearch] 	at java.lang.Thread.run(Thread.java:834) [?:?]
[elastic-elasticsearch-data-0 elasticsearch] Caused by: org.elasticsearch.transport.RemoteTransportException: [elastic-elasticsearch-data-0][10.42.5.139:9300][internal:cluster/coordination/join/validate]
[elastic-elasticsearch-data-0 elasticsearch] Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid E-nlXOHsSHa_Z8d1S3jDMA than local cluster uuid 4dUYLGC0RvysrkX0-nfqIQ, rejecting
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$4(JoinHelper.java:148) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:264) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.4.0.jar:7.4.0]
[elastic-elasticsearch-data-0 elasticsearch] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
[elastic-elasticsearch-data-0 elasticsearch] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
[elastic-elasticsearch-data-0 elasticsearch] 	at java.lang.Thread.run(Thread.java:834) ~[?:?]
[elastic-elasticsearch-data-0 elasticsearch] [2019-10-22T10:46:30,768][INFO ][o.e.c.c.JoinHelper       ] [elastic-elasticsearch-data-0] failed to join {elastic-elasticsearch-master-0}{cCKVF8XTTDCYX0m9FZ14pw}{XYhsq7QeSOyBDA688K8B4g}{10.42.5.237}{10.42.5.237:9300}{m} with JoinRequest{sourceNode={elastic-elasticsearch-data-0}{O1dbIj9JTBKQolnFhAIXAg}{EMV2G2adT7W1EyGVc8H94A}{10.42.5.139}{10.42.5.139:9300}{d}, optionalJoin=Optional.empty}
[elastic-elasticsearch-data-0 elasticsearch] org.elasticsearch.transport.RemoteTransportException: [elastic-elasticsearch-master-0][10.42.5.237:9300][internal:cluster/coordination/join]
```

**Describe the results you expected:**

Expected cluster to successfully restart and continue normal operation

**Additional information you deem important (e.g. issue happens only occasionally):**

we use local-storage-provisioner by rancher to provision PV+PVC for local data storage on local ssds. Tried on various kubernetes versions up to current 1.15.*

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I deleted all pods and didn't get that IllegalStateException. Which is the cluster you are using? Did you put any data before doing the delete operation?

**Comment by yugansh20** [comment]
I am facing same issue.

I deleted the chart using - 
`helm delete es_chart`

Then I recovered using - 
`helm rollback es_chart 1`

This is giving error - 
`org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join validation on cluster state with a different cluster uuid`

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. We will check, but this may be related. https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-bootstrap-cluster.html#modules-discovery-bootstrap-cluster-joining

We will try checking if, with persistent storage the issue disappears. Thanks for the feedback!

**Comment by loripino21** [comment]
Hi!
I have the same issue.
I think this is due to master configuration files not being persisted at all.
From master-statefulset.yaml:
```
      volumes:
      [...]
      - name: "data"
        emptyDir: {}
```
The volume to bake "data" volume mounted in "/bitnami/elasticsearch/data" is an emptyDir!
So every time the master is restarted a new cluster configuration is created. 
Correct?

**Comment by carrodher** [comment]
Hi,
I am not able to reproduce the issue on our side, but taking a look at the error, it indicates that the data node is trying to connect to the ES cluster with a different UUID. It looks like maybe at some point during deployment bootstrap two clusters got created, each having a different UUID and the data node may have connected to one that of those.
We are not sure of the sequence of events, but to avoid such issues we released a new ES version modifying some configuration, so each master-eligible node knows the minimum number of master-eligible nodes that must be visible to form the cluster.
This avoids something known as split-brain (ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/modules-node.html#split-brain) 

Please, take into account than deleting a deployment doesn’t remove the PVC, so if your ES deployment is not holding any data, can you delete it and all associated PVC’s? Then redeploys it using the latest version.

In this commit, the option was added to the chart: https://github.com/bitnami/charts/commit/8de318653fd22f152c85f913436c7563c9fda7fd and in this one, the image revision was updated to also add those changes at image level: https://github.com/bitnami/charts/commit/c1c6e6117b622e1578811040819a5d6e5fab825a

**Comment by tzachalon** [comment]
Hi,
I was able to fix this issue.
This is probably a tiny human-error, but on the master-statefulset.yaml Line 135
https://github.com/bitnami/charts/blob/b17f0b2ab34836c459a923280e6d15eaafc6d6bb/bitnami/elasticsearch/templates/master-statefulset.yaml#L135

the word data is missing the double quotes.
When I cloned the repo and and changed data to "data", I was able to add a persistence storage to the master nodes and now the cluster can go up and down entirely without any problem at all, since the cluster uuid is being saved on the master nodes, as well as on the data nodes.

Since this is the first time I'm trying to contribute to a public repo, I'm not able to create a pull request with this fix. Can someone explain how do I open the PR?

**Comment by carrodher** [comment]
Thanks for the PR. I just added a comment trying to understand what is the reason for this change. It was solved after double quoting the name, but I am not sure about the background of that and I am not able to find other charts with the name double-quoted, let's see what others said in the PR.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
