### ISSUE TITLE
[bitnami/airflow] How to install commands to airflow-worker

### ISSUE THREAD

**Issue by calvinlu3** [bitnami/charts#15098]
### Name and Version

bitnami/airflow:latest

### What is the problem this feature will solve?

I want to use Airflow to install some helm charts, which requires the airflow-worker to have the `helm` command. 

### What is the feature you are proposing to solve the problem?

Is there currently a way to do this?

**Comment by javsalgar** [comment]
Hi,

I'm afraid that right now you would need to either:

- Override the command and args command so it downloads helm 
- Create your custom fork of the bitnami/airflow-worker image.
