### ISSUE TITLE
bitnami/postgresql image do not use ~/.pgpass file to store replication user password

### ISSUE THREAD

**Issue by amodkakade** [bitnami/charts#15135]
### Name and Version

bitnami/postgresql

### What steps will reproduce the bug?

1. Download the bitnami/postgresql chart for replication and configure the replication
2.  Use the `POSTGRESQL_REPLICATION_PASSWORD_FILE` variable to specify the replication user's password
3.  After the PostgreSQL database is set up with replication if you check `/opt/bitnami/postgresql/postgresql.conf` it contains the `primary_conninfo` parameter with the password of the replication user in clear text.
4.  The `/opt/bitnami/postgresql/postgresql.conf` is a world readable file which makes it insecure.

### What is the expected behavior?

The password of the replication user should be stored in a `.pgpass` file and PostgreSQL should use this file to receive the replication user password.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
