### ISSUE TITLE
 [bitnami/postgresql-ha] Pgpool does not discover new primary after failure

### ISSUE THREAD

**Issue by Tilusch** [bitnami/charts#15136]
### Name and Version

bitnami/postgresql-ha-11.1.3

### What steps will reproduce the bug?

- Install the chart with the values from bellow as mentioned in https://github.com/bitnami/containers/issues/16244
- delete the primary pod
- connect to a postgres pod deployed from the helmchart 
- `k exec -ti <podname> -- bash`
- create a db connection over the pgpool service
- `psql -U postgres -h <pgpool-service>`
- create a db as example
- 'create database example'

### Are you using any custom parameters or values?
```
pgpool:
  extraEnvVars:
   - name: REPMGR_FAILOVER
     value: "manual"
```
### What is the expected behavior?

- The database gets created

### What do you see instead?

- pgpool tries to create the database on the old primary host wich is now standby and cant create the DB

**Comment by Mauraza** [comment]
Hi @Tilusch,

I follow your steps but everything goes well:

```bash
$ kubectl exec -ti postgresql-ha-postgresql-0 -- psql -U postgres -h postgresql-ha-pgpool
Password for user postgres: 
psql (15.2)
Type "help" for help.

postgres=# CREATE DATABASE example;
CREATE DATABASE
postgres=# \l
                                                 List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    | ICU Locale | Locale Provider |   Access privileges   
-----------+----------+----------+-------------+-------------+------------+-----------------+-----------------------
 example   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 repmgr    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
           |          |          |             |             |            |                 | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
           |          |          |             |             |            |                 | postgres=CTc/postgres
(5 rows)
```

Did you try to check the logs?

**Comment by Tilusch** [comment]
Hi @Mauraza i tested it again and you are right. Seems like i did something quirky there..
Thanks a lot for your investigation!
