### ISSUE TITLE
Publish arm64 images to another registry eg GHCR

### ISSUE THREAD

**Issue by samip5** [bitnami/charts#15132]
### Name and Version

all

### What is the problem this feature will solve?

It would solve the issue when using multiple bitnami images, and downloading from Docker results in rate limits being hit and as result will prevent cluster boot.

### What is the feature you are proposing to solve the problem?

I would request to either move to also publish images on Quay, Github Container Registry (GHCR) or Amazon Elastic Container Registry (ECR) compared to just Docker Hub.

### What alternatives have you considered?

Maintaining a image mirror is not feasible solution.

**Comment by javsalgar** [comment]
Hi,

You can find our images in other registries like the Azure Container Registry or the ECR Public Gallery. Did you check them?

**Comment by samip5** [comment]
Huh, I must have missed them then as the only advertised one is Docker Hub that they are available on that I could find easilly.

**Comment by carrodher** [comment]
Apart from that, please note Bitnami is part of the [Docker Verified Publisher Program](https://docs.docker.com/docker-hub/publish/) so you shouldn't face any issue abut rate limits, that's why the default and recommended registry is Docker Hub.

**Comment by samip5** [comment]
> Apart from that, please note Bitnami is part of the [Docker Verified Publisher Program](https://docs.docker.com/docker-hub/publish/) so you shouldn't face any issue abut rate limits, that's why the default and recommended registry is Docker Hub.

Shouldn't maybe, but Docker Hub has a bad habit of still imposing rate limits on unauthenicated pulls.

P.S https://gallery.ecr.aws/?searchTerm=bitnami&architectures=ARM+64&page=1 shows nada.

**Comment by javsalgar** [comment]
Sorry,

I read the title incorrectly. Yes, I'm afraid that the arm64 images are only in Docker Hub at the moment.

**Comment by samip5** [comment]
Please pin it so it doesn't get closed.

**Comment by carrodher** [comment]
Unfortunately, there are no plans in the mid-term to work on pushing the ARM container images to any other registry different than DockerHub. Because of that, we will close this issue as not planned.

**Comment by samip5** [comment]
Wow, I would imagine that it would be just a few lines of code, but alright then. Bitnami images belong into the no-go category then.

**Comment by viceice** [comment]
- https://github.com/docker/hub-feedback/issues/2421
😕
