### ISSUE TITLE
arm support is broken

### ISSUE THREAD

**Issue by anubisg1** [bitnami/charts#15140]
### Name and Version

birnami/postgresql-ha 11.1.3

### What steps will reproduce the bug?

1. following the announcement https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html 

i did 

```
helm repo add postgresql-ha https://charts.bitnami.com/bitnami
helm repo update

export NAMESPACE="dev_test"
export NBDBPASSWORD="YourP@SsWoRd"
helm upgrade --install postgresql \
  --set pgpool.customUsers.usernames="netbox" \
  --set pgpool.customUsers.passwords=$NBDBPASSWORD \
  --set volumePermissions.enabled=true \
  bitnami/postgresql-ha \
  -n $NAMESPACE
  ```

the init-chmod-data container fails with

```
kubectl logs -f postgresql-postgresql-ha-postgresql-1 -c init-chmod-data -n dev_test
exec /bin/sh: exec format error
```

### What is the expected behavior?

it should work

### What do you see instead?

exec /bin/sh: exec format error

### Additional information

installed on an ARM server

**Comment by carrodher** [comment]
Please note that the announcement published some hours ago mentions Bitnami containers, in the case of Helm charts it can take longer until changes are propagated.

At this moment, the container image included in the Helm chart is
```yaml
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.2.0-debian-11-r2
```

Taking a look at DockerHub, [15.2.0-debian-11-**r2**](https://hub.docker.com/layers/bitnami/postgresql/15.2.0-debian-11-r2/images/sha256-a18fde65055e5a9571b1d28683220057f2401919189ca1fe62f934165fc980f7?context=repo) only supports AMD. The first container image supporting ARM is [15.2.0-debian-11-**r4**](https://hub.docker.com/layers/bitnami/postgresql/15.2.0-debian-11-r4/images/sha256-3c32120f060aa431ad1e72631f1e36ac7d1ef422a33b124d4143712535d1a9f7?context=repo).

### What is next once the ARM container image is already released?

There are two options:
- Wait until there is a new Helm chart release. The next release of the Helm chart will bundle the latest container images, in this case, multi-arch images. There are different factors that trigger a new Helm chart release such as a new application version, merge user contribution via PR, detected CVE, etc or a maintenance release after X days if none of the previous conditions are met.
- You can also change the images bundled in a Helm chart by modifying the _values.yaml_ or using `--set image.tag=15.2.0-debian-11-r4` when deploying the Helm chart with `helm install`.
