### ISSUE TITLE
[discourse] Backup S3 can not be use

### ISSUE THREAD

**Issue by obeyler** [bitnami/charts#15149]
### Name and Version

bitnami/discourse 10.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I try to configure S3 for Discourse backup instead of local.
I set all S3 parameters in Setting File ( s3 access key id, s3 secret access key,...)
If I change in Setting  the backup location from Local storage to S3

### What is the expected behavior?

Be able to do backup on S3

### What do you see instead?

backup tab doesn't work any more and we have :
![image](https://user-images.githubusercontent.com/23224162/221322963-372412d1-c8fc-42b8-8101-9127e49c1d17.png)

### Additional information

On container log I can see the main root cause:  

` Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.17/rubyext-ruby-3.1.3-x86_64-linux.tar.gz: no download tool found (curl or wget required)
`
So I suppose that we need to add curl or wget into docker discourse image  or provide some binary by advance

**Comment by obeyler** [comment]
I try to create a new docker image base on current
```
FROM bitnami/discourse:3.0.1-debian-11-r6
RUN apt-get update; apt install -y curl
```
it seems not enough
as now in log we have:
```
<internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require': libruby.so.3.1: cannot open shared object file: No such file or directory - /tmp/passenger-native-support-4tv219/passenger_native_support.so (LoadError)
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
