### ISSUE TITLE
[bitnami/redis] pod is continously restarting when changing cluster domain parameter

### ISSUE THREAD

**Issue by rajivmishra-123** [bitnami/charts#15153]
### Name and Version

bitnami/redis , latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install redis redis 

### Are you using any custom parameters or values?

i am changing cluster.domain paramter .

### What is the expected behavior?

pods should be created and be in running state 

### What do you see instead?

pods are in 0/2 state and continuosly restarting . no error is coming in logs also . 

### Additional information

when i tried to go inside container , conf files are not created in both conatiner . i.e /opt/bitnami/redis/etc and /opt/bitnami/redis-sentinel /etc are empty.

logs- 
![Screenshot from 2023-02-26 14-52-17](https://user-images.githubusercontent.com/68244292/221402366-bfed9f38-c5d4-4714-aa87-c47b9ffe58df.png)
values.yaml
![Screenshot from 2023-02-26 14-51-57](https://user-images.githubusercontent.com/68244292/221402380-475a9524-e967-4c54-9b0d-c015252c95e4.png)

**Comment by rajivmishra-123** [comment]
when i install the chart with cluster domain= cluster.local and upgrade it to new cluster domain, then it works fine

**Comment by dgomezleon** [comment]
Hi @rajivmishra-123 ,

Could you verify the full FQDN of the service? For example:
```
kubectl run dnsutils --image tutum/dnsutils -it --rm -- bash
```

And then execute
```
nslookup redis-master
```

Does it match with `david-redis-master.default.svc.ieil.dc499cloud`?
