### ISSUE TITLE
AKS Bitnami Wordpress and Azurefiles PVC - Could not create directory

### ISSUE THREAD

**Issue by miguelangelch** [bitnami/charts#15155]
### Name and Version

bitnami/wordpres 6.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

```
helm install wp-mywordpress bitnami/wordpress
--set wordpressUsername="test"
--set wordpressPassword="test"
--set replicaCount=1
--set service.type="LoadBalancer"
--set service.ports.http=80
--set persistence.enabled=true
--set persistence.accessModes="{ReadWriteMany}"
--set persistence.size=100Gi
--set persistence.storageClass=azurefile-premium
--set volumePermissions.enabled=true
--set volumePermissions.containerSecurityContext.runAsUser=0
```

### What is the expected behavior?

See the wordpress main page and the wp-content folder in the PVC (Azure File)

### What do you see instead?

When I am using persistence, when I try to access the blog I get this error:
![image](https://user-images.githubusercontent.com/12670461/221501981-1fd5ae69-ad23-4f36-8740-de57b69ca9c3.png)

And when I try to install a plugin or theme manually I get an error related to permissions:
![image](https://user-images.githubusercontent.com/12670461/221502030-f787b38c-4611-4dae-bf8c-567e33931880.png)

### Additional information

Accessing to the File Shares (PVC) I can see just one file but there I must see the wp-content folder:
![image](https://user-images.githubusercontent.com/12670461/221502123-3d3153e3-18de-41a9-a991-c3c308e59342.png)

The file shared and the wp-content folder have the same permissions:

```
lrwxrwxrwx 1   1001 root    32 Feb 27 07:00 wp-config.php -> /bitnami/wordpress/wp-config.php
lrwxrwxrwx 1   1001 root    29 Feb 27 07:00 wp-content -> /bitnami/wordpress/wp-content
```

I've tried with the following parameters with the same result:

```
--set securityContext.runAsUser=1001
--set securityContext.fsGroup=1001
```

**Comment by corico44** [comment]
Hello @miguelangelch,

I wasn't able to reproduce the issue. Could you show me the pods logs to get more information, please?
