### ISSUE TITLE
[bitnami/postgresql] auth.secretsKeys.adminPasswordKey is checking for key "postgres-password" instead of inserted key

### ISSUE THREAD

**Issue by mhenrike** [bitnami/charts#15156]
### Name and Version

bitnami/postgresql 12.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In k8s-aks, upgrade to chart version 12.2.1 fails because of the error:

Error: UPGRADE FAILED: execution error at (postgresql/templates/secrets.yaml:5:24): 
PASSWORDS ERROR: The secret "hed-pgsql" does not contain the key "postgres-password"

### Are you using any custom parameters or values?

I'm using a .yaml file with these settings:
```
auth:
  database: hed
  existingSecret: hed-pgsql
  secretKeys:
    adminPasswordKey: PW_HED_USER
```
### What is the expected behavior?

It should look for the key actually configured, in this case PW_HED_USER.

### What do you see instead?

Error: UPGRADE FAILED: execution error at (postgresql/templates/secrets.yaml:5:24): 
PASSWORDS ERROR: The secret "hed-pgsql" does not contain the key "postgres-password"

### Additional information

It works when I add a key with the name "postgres-password" i my secret-file, but the correct key in this case should be PW_HED_USER.

**Comment by javsalgar** [comment]
Hi,

Could you check if this PR fixed the issue? https://github.com/bitnami/charts/pull/15023

**Comment by junkiebev** [comment]
having the same issue on `12.2.2`

**Comment by javsalgar** [comment]
Hi,

This should have been fixed here:

https://github.com/bitnami/charts/pull/15023

Could you ensure that you are using the latest version of the chart?

**Comment by mhenrike** [comment]
Hi,

Thanks, can confirm it works now on `12.2.2`.

**Comment by ScionOfDesign** [comment]
This still seemed to happen to me again with the latest chart version `12.5.2`.

**Comment by fmulero** [comment]
Sorry @ScionOfDesign but I am not able to repoduce the issue in version 12.5.2 or above. Could you share more details?

**Comment by ScionOfDesign** [comment]
I will attempt to replicate the issue again.

**Comment by bruckins** [comment]
This is still the issue on version 18.2.3.
