### ISSUE TITLE
[bitnami/fluentd] Fluentd deployment to support new `persistentVolumeClaimRetentionPolicy` in StatefulSet

### ISSUE THREAD

**Issue by alen-z** [bitnami/charts#15157]
### Name and Version

bitnami/fluentd all

### What is the problem this feature will solve?

While scaling down StatefulSet Pods, PVCs will be properly deleted and not continue to induce storage costs.

### What is the feature you are proposing to solve the problem?

Allow `persistentVolumeClaimRetentionPolicy` specific feature or allow adding custom `spec` configuration to Fluentd StatefulSet deployment.

### What alternatives have you considered?

Mutating StatefulSet resources after deployment with Kyverno to include `persistentVolumeClaimRetentionPolicy`.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward this to the engineering team, but we cannot guarantee an ETA as it is not a critical feature. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by alen-z** [comment]
Thank you for quick response.

> we cannot guarantee an ETA
No worries!

> feel free to submit a PR
...if I manage to squeeze some time from the day, sure!
