### ISSUE TITLE
[bitnami/nginx-ingress-controller] Admission webhook

### ISSUE THREAD

**Issue by AlexisDucastel** [bitnami/charts#15150]
### Name and Version

bitnami/nginx-ingress-controller <9.3.31

### What is the problem this feature will solve?

Cluster users can write their Ingress rules in their own namespaces, then they can define annotations on these ingresses. This can lead to misconfiguration problem that blocks nginx-ingress-controller to be able to reload its configuration leaving controller to be "frozen in time" unable to implement new ingress changes, or event more problematic, new pods can't generate a valid config leading to broken http routing on the cluster.

### What is the feature you are proposing to solve the problem?

The upstream nginx-ingress controller implements a [validating admission webhook server](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook) that validate ingresses by checking the rendered configuration prior to accept ingress creation/modification (see https://kubernetes.github.io/ingress-nginx/how-it-works/#avoiding-outage-from-wrong-configuration). This could prevent misconfigurations and thus prevent service disruption, covering 100% of the needs of this feature request.

### What alternatives have you considered?

We can also implement checks with policy agents like OPA/Kyverno, but this is far more complex and will not cover the variety of annotations possible. For us, admission controller by ingress-controller is the way to go to ensure functionnal http routing with all nginx-ingress features.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
