### ISSUE TITLE
MongoServerError: Authentication failed.

### ISSUE THREAD

**Issue by sireeshau472** [bitnami/charts#15159]
### Name and Version

bitnami/mongodb 13.8.1

### What architecture are you using?

None

### What steps will reproduce the bug?

 Tried to connect mongodb from pod using the below steps, but facing auth fail issue.

```console
$ ./mongosh -u root -p TafoUiK8Ug 
Current Mongosh Log ID:63fc8d0f227fe394340e22cd
Connecting to:mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.7.1
MongoServerError: Authentication failed.
```
Also mongodb-arbiter-0 pod is keep on restarting and found below error log message for the pod
```
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
mongodb 10:42:04.95 ERROR ==> Node mongodb-0.mongodb-headless.mytests.svc.cluster.local did not become available
mongodb 10:42:04.96 INFO  ==> Stopping MongoDB...
```
### Are you using any custom parameters or values?
```
architecture="replicaset"
```
### What is the expected behavior?

Connection should be established from the pod

### What do you see instead?

Auth issue

**Comment by carrodher** [comment]
Did you deploy the Helm chart from scratch or was it an upgrade? In the same way, was it the first installation or did you install it previously in the same namespace?

**Comment by sireeshau472** [comment]
Hi @carrodher 

Deployed it from scratch  and facing an authentication issue . During first installation itself i m facing this issue

**Comment by sireeshau472** [comment]
I have deployed mongodb using bitnami helm charts  on microk8s, as of now it is working fine and able to connect with mongoshell from pod using auto generated rootpassword  from secrets with root user. 

Kindly someone help  me how to access mongodb externally using my public ip/dns .  In my case i m using nodeport. 

And also how to ensure write/read operations are performs correctly even though master pod is down.

**Comment by corico44** [comment]
@sireeshau472 From what you are saying, have you already managed to fix the authentication error?

**Comment by nickbrookck** [comment]
I'm coming across the same issue on GKE - authentication failure on a replicaset install. How did you fix it @sireeshau472 ?

**Comment by sireeshau472** [comment]
@nickbrookck @corico44 

I have delete all the helm chart  along with pvc and pv's which are related to those statefulset deployement, After that have reinstalled them and was able to access with new password which auto generated from secrets.

**Comment by corico44** [comment]
@sireeshau472 Thanks for posting your solution! I'm going to leave the issue open until the bot closes it in case any user needs it.

**Comment by sireeshau472** [comment]
Hi @corico44 

I m encountered with another issue while accessing  mongodb externally(in local machine), in my case I have exposed service using nodeport and traffic is coming from another haproxy server and port mapping is properly configured in haproxy using nodeport, when i m trying it access mongodb from robo 3T facing below issue.

**Comment by carrodher** [comment]
[optional/customizable] It seems it is not an issue related to the Bitnami MongoDB container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
