### ISSUE TITLE
[bitnami/kafka] versioning issue : 20.1.0 vs 21.0.1

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#15160]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

in https://github.com/bitnami/charts/pull/14943, bitnami-bot released kafka 21.0.0 (later updated to 21.0.1)
in https://github.com/bitnami/charts/pull/14938, @javsalgar downgraded the chart back to 20.1.0

note that 20.1.0 embed a major kafka upgrade, so not compatible with 20.x branch...

### What do you see instead?

--

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
