### ISSUE TITLE
[bitnami/grafana-tempo] Add the ability to disable metrics generator in Grafana Tempo

### ISSUE THREAD

**Issue by bbrysh** [bitnami/charts#15168]
### Name and Version

bintami/grafana-tempo:2.0.1

### What is the problem this feature will solve?

Currently there is no way to disable the metrics generator from being deployed in the chart. Since the metrics generator is an optional component of Tempo, we should have the ability to not install it.

### What is the feature you are proposing to solve the problem?

Add an enabled flag to the metrics generator state values that controls if the metrics generator is deployed or not.

### What alternatives have you considered?

Using the grafana tempo helm charts, but I'd rather use the bitnami ones because of the engineering done with their charts.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward this to the engineering team but, as it is not a critical issue, we cannot guarantee an ETA. If you want to speed up the process, feel free to submit a PR and we will review it
