### ISSUE TITLE
trying to upgrade from 6.2.5 to 13.1.1

### ISSUE THREAD

**Issue by vasudevbannaravuri** [bitnami/charts#15172]
### Name and Version

bitnami/keycloak:13.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to upgrade from 6.2.5 to 13.1.1, in the 6.2.5 version for keycloak service https path and management path were available but for 13.1.1 though https value is present in values.yaml file but the configuration is not picking up for my service. here I am using the service type as cluster IP. please suggest me

### What do you see instead?

only http port is available

**Comment by carrodher** [comment]
[Here](https://docs.bitnami.com/kubernetes/apps/keycloak/administration/upgrade/) you can find the upgrade notes from each major version. I recommend you to upgrade little by little instead of bumping the version in 7 major versions directly

**Comment by carrodher** [comment]
The information about how to upgrade the Helm chart can be found at https://docs.bitnami.com/kubernetes/apps/keycloak/administration/upgrade/. For information about changes in the application itself we recommend visiting the Keycloak doc site
