### ISSUE TITLE
[bitnami/mysql] Upgrade to 9.5.0 is breaking: Error: execution error at (mysql/templates/secrets.yaml:3:21)

### ISSUE THREAD

**Issue by morremeyer** [bitnami/charts#15175]
### Name and Version

bitnami/mysql 9.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install with 9.4.9 and values below
2. Upgrade to 9.5.0

### Are you using any custom parameters or values?

```yaml
image:
  repository: bitnami/mysql
  tag: 8.0.29-debian-10-r23

auth:
  forcePassword: true
  existingSecret: mysql-passwords

architecture: standalone

primary:
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi

  persistence:
    storageClass: hcloud-volumes
    size: 10Gi

  configuration: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    # Custom options
    disable_log_bin
    binlog_expire_logs_seconds=900

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid

secondary:
  replicaCount: 0

metrics:
  enabled: false
  serviceMonitor:
    enabled: true
```

The `mysql-passwords` secret contains `.spec.data` with the keys `mysql-replication-password` and `mysql-root-password` for the respective passwords.

### What is the expected behavior?

Upgrade works without any problems

### What do you see instead?

Helm exits with

```
  Error: Failed to render chart: exit status 1: Error: execution error at (mysql/templates/secrets.yaml:3:21): 
  PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                   Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                   Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
      'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MYSQL_ROOT_PASSWORD' to the command. To get the current value:
          export MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace "mysql" mysql-passwords -o jsonpath="{.data.mysql-root-password}" | base64 -d)
  Use --debug flag to render out invalid YAML
```

**Comment by carrodher** [comment]
This error is warning you that you should specify the password when upgrading, see https://github.com/bitnami/charts/tree/main/bitnami/mysql#upgrading

**Comment by morremeyer** [comment]
I understand that this is the error and what it says, but I am specifying the password through the secret already. This has not been an issue in the past.

**Comment by marcosbc** [comment]
Hi @morremeyer, it could be that your secret is missing a required field, even though it wasn't complaining before.

Could you describe the fields of your secret? E.g. `kubectl describe secret ...` - It should include the ones implemented [here](https://github.com/bitnami/charts/blob/main/bitnami/mysql/templates/secrets.yaml).

**Comment by jonkerj** [comment]
I'm running into exactly this issue (both upgrading and freshly installing). I think my existing secret contains the right fields:

```
kubectl describe secrets -n yolosaurus big-secrets
Name:         big-secrets
Namespace:    yolosaurus
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
mysql-password:              16 bytes
mysql-replication-password:  16 bytes
mysql-root-password:         16 bytes
```

**Comment by morremeyer** [comment]
Sorry for the late reply here. This issue still occurs, even in version 9.9.1. 

I initially thought it was an oversight on my side, since I did not have `mysql-password` set in the secret. However, I do have it set now:

```yaml
❯ kgsec mysql-passwords -o yaml
apiVersion: v1
data:
  mysql-password: cmVkYWN0ZWQ=
  mysql-replication-password: cmVkYWN0ZWQ=
  mysql-root-password: cmVkYWN0ZWQ=
kind: Secret
metadata:
  creationTimestamp: "2022-02-20T02:20:09Z"
  name: mysql-passwords
  namespace: mysql
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: mysql-passwords
    uid: 01ae9a20-3b35-47a4-9af6-e8900677ac7d
  resourceVersion: "96492128"
  uid: 0017d436-c10f-4717-aec6-3f77c1f9af15
type: Opaque
```

and it still happpens:

```
  Error: Failed to render chart: exit status 1: Error: execution error at (mysql/templates/secrets.yaml:3:21): 
  PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                   Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                   Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
      'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MYSQL_ROOT_PASSWORD' to the command. To get the current value:
          export MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace "mysql" mysql-passwords -o jsonpath="{.data.mysql-root-password}" | base64 -d)
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

I'll debug this more later today.

**Comment by morremeyer** [comment]
Currently looks to me like this line is not working: https://github.com/bitnami/charts/blob/d8211ca955bae990f4b1af121419545cb90309eb/bitnami/common/templates/_secrets.tpl#L93 since the error message says ` 'auth.rootPassword' must not be empty`, which is [from the `else` part](https://github.com/bitnami/charts/blob/d8211ca955bae990f4b1af121419545cb90309eb/bitnami/common/templates/_secrets.tpl#L111) of the `if $secretData` in the line after the one I linked above 🤔

**Comment by carrodher** [comment]
Thanks for reporting this issue, if you have located the issue, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by morremeyer** [comment]
I have determined that this is a duplicate of #15073. Namely, the issue ocurrs with the `diff` plugin for helm only.
