### ISSUE TITLE
Helm Chart for kubeflow (Machine Learning)

### ISSUE THREAD

**Issue by Syntax3rror404** [bitnami/charts#15177]
### Name and Version

bitnami/kubeflow 1.6.1

### What is the problem this feature will solve?

Machine learning is becoming increasingly important. The platforms to build the complex models are getting more and more complex. One of these platforms is kubeflow, which already provides kustomize deployments. The problem is with this 1000 files it is absolutely infinitely hard to set up and maintain this platform. A Helm chart would completely solve this problem.

-> GitHub Repo of kubeflow:
https://github.com/kubeflow/kubeflow
-> GitHub Repo of the manifests
https://github.com/kubeflow/manifests

It would be absolutely amazing if you had a helm chart for this.

### What is the feature you are proposing to solve the problem?

A helm chart for kubeflow

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by Syntax3rror404** [comment]
@carrodher 
sounds good thanks a lot :)

**Comment by jesperrix** [comment]
Are there any updates to adding kubeflow as a helm chart? It would be amazing 🤩

**Comment by carrodher** [comment]
Unfortunately, it is still in the queue to be analyzed in deep since it's a complex solution.

**Comment by Syntax3rror404** [comment]
ping

**Comment by thesuperzapper** [comment]
For those watching this thread, there is an existing "helm-like" option for deploying Kubeflow, it's called [__deployKF__](https://www.deploykf.org/).

It might meet your needs.

**Comment by kirkpabk** [comment]
(ping)

**Comment by Syntax3rror404** [comment]
Hello @carrodher are there any news regarding this feature? It's been a year now since I open this issue. 

Thank you again for your time :)

**Comment by carrodher** [comment]
Hi, at this moment and given other tasks the team is working on, we can't find the bandwidth to work on such as complex solution like MLFlow. We are adding different applications for the ML/AI ecosystem.
We'll have this application in mind for the future.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will be sure to reconsider it in the future.

Thanks for your suggestion!
