### ISSUE TITLE
[bitnami/kafka] network metrics fixed

### ISSUE THREAD

**Issue by ahu0605** [bitnami/charts#15185]
### Name and Version

bitnami/kafka
### What is the problem this feature will solve?

kafka network metrics is not enough! In the jmx-configmap.yaml
```
 - pattern : kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
    name: kafka_network_$1_$2_$4
    labels:
       network_processor: $3
 - pattern : kafka.network<type=(RequestMetrics), name=(RequestsPerSec), request=(.+)><>(Count)
    name: kafka_network_$1_$2_$4
        labels:
            request: $3
```
### What is the feature you are proposing to solve the problem?
```
- pattern : kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
   name: kafka_network_$1_$2_$4
   labels:
      network_processor: $3
- pattern : kafka.network<type=(RequestMetrics), name=(.+), request=(.+)><>(Count|Value)
   name: kafka_network_$1_$2_$4
   labels:
      request: $3
- pattern : kafka.network<type=(SocketServer), name=(.+)><>(Count|Value)
  name: kafka_network_$1_$2_$3
- pattern : kafka.network<type=(RequestChannel), name=(.+)><>(Count|Value)
   name: kafka_network_$1_$2_$3
```
### What alternatives have you considered?

I want to exporter all of kafka jmx_metrics

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the issue. If you think that extra sections should be added to the configmap, would you like to submit a PR with the addition?

**Comment by ahu0605** [comment]
> Hi,
> 
> Thank you so much for opening the issue. If you think that extra sections should be added to the configmap, would you like to submit a PR with the addition?

I have committed PR,please check

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
