### ISSUE TITLE
Changing persistence to disabled on the kafka chart doesn't seem to work. 

### ISSUE THREAD

**Issue by riccardolorenzon** [bitnami/charts#1525]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/kafka

**Description**
I'm trying to deploy the chart with `persistence` disabled, the pod kafka cannot start because of:
```
Warning  FailedCreate  7s (x15 over 52s)  statefulset-controller  create Pod test-kafka-0 in StatefulSet test-kafka failed error: pods "test-kafka-0" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used]
```

**Steps to reproduce the issue:**

1. Change persistence.enabled to `false` on values
2. Create the deployment.yaml file using `helm template --name test --namespace my-namespace ./kafka > deployment.yaml`   
3. Deploy the manifest created with `kubectl apply -f  deployment.yaml -n my-namespace`

**Describe the results you received:**
Pod does not start, on the pod describe i get :
```
Warning  FailedCreate  7s (x15 over 52s)  statefulset-controller  create Pod test-kafka-0 in StatefulSet test-kafka failed error: pods "test-kafka-0" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used]
```

**Describe the results you expected:**
The pod should starts as if persistence was enabled eventually without mounting any volume.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by riccardolorenzon** [comment]
This issue seems to be connected to the fact that this kind of volumes is not supported by my current k8s cluster.

**Comment by riccardolorenzon** [comment]
This issue seems to be connected to the fact that this kind of volumes is not supported by my current k8s cluster.

**Comment by alemorcuq** [comment]
Yes, @riccardolorenzon. It looks like you have some kind of Pod Security Policy that doesn't allow you to use `emptyDir` volumes. You can see your Pod Security Policies with:

```
kubectl get psp
```
