### ISSUE TITLE
Quorum queues created during deploy via loadDefinition do not adopt any followers

### ISSUE THREAD

**Issue by Millz12** [bitnami/charts#15299]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello. We're deploying RabbitMQ with 3 replicas in a cluster, and loading in a default configuration via the loadDefinitions parameter. We're creating 2 quorum queues as below:

```        "queues": [
            {
                "name": "user",
                "vhost": "/",
                "durable": true,
                "auto_delete": false,
                "type": "quorum",
                "arguments": {
                    "x-queue-type": "quorum"
                }
            },
            {
                "name": "admin",
                "vhost": "/",
                "durable": true,
                "auto_delete": false,
                "type": "quorum",
                "arguments": {
                    "x-queue-type": "quorum"
                }
            }
        ]
```

The queues are created (along with bindings, user accounts etc) without any errors, however the queues created via this method only allocate the first node without any followers. When creating additional queues manually later via the GUI then the primary node is assigned with 2 followers (which is the expected behaviour).

![image](https://user-images.githubusercontent.com/8068162/222433632-59df8b93-3d90-4fa7-8f49-60820e7cfa2d.png)

We suspect this is because the configuration is applied prior to the cluster being fully created/initialised. 

Is there a way around this without having to apply a workaround of applying the config after deployment?

Thank you

**Comment by corico44** [comment]
Hello @Millz12,

Thank you for opening this issue. It is possible that the logic that is carried out when adding the configuration by file vs manually is different. I'm going to dig deeper to see what the actual difference between the two methods is. I will notify you about this issue when I have more information.

**Comment by corico44** [comment]
Digging deeper, there doesn't seem to be such a distinct logic justifying the behavior that the queues created using loadDefinitions only allocate the first node without any followers. But when creating additional queues manually later via the GUI then the primary node is assigned with 2 followers. Therefore, I am going to create a task internally to better study this behavior.
We will notify you about this issue when we have more information. 
Thanks for reporting it.

**Comment by Millz12** [comment]
Thanks for the update @corico44 

I've found that if you wait until the cluster is fully initialised then load the same definition file from the CLI within a pod then it sets up the queues correctly.

```
$ rabbitmqctl import_definitions load.json
Importing definitions in JSON from a file at "load.json" ...
Successfully started definition import. This process is asynchronous and can take some time.
$ rabbitmq-queues quorum_status admin-events
Status of quorum queue admin-events on node rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local ...
┌─────────────────────────────────────────────────────────────────────┬────────────┬───────────┬──────────────┬────────────────┬──────┬─────────────────┐
│ Node Name                                                           │ Raft State │ Log Index │ Commit Index │ Snapshot Index │ Term │ Machine Version │
├─────────────────────────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local │ leader     │ 2         │ 2            │ undefined      │ 1    │ 3               │
├─────────────────────────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@rabbitmq-2.rabbitmq-headless.namespace.svc.cluster.local │ follower   │ 2         │ 2            │ undefined      │ 1    │ 3               │
├─────────────────────────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@rabbitmq-1.rabbitmq-headless.namespace.svc.cluster.local │ follower   │ 2         │ 2            │ undefined      │ 1    │ 3               │
└─────────────────────────────────────────────────────────────────────┴────────────┴───────────┴──────────────┴────────────────┴──────┴─────────────────┘

```

If you then remove 2 of the members from the queue so that we only have the leader..

```
$ rabbitmq-queues delete_member admin-events rabbit@rabbitmq-1.rabbitmq-headless.namespace.svc.cluster.local
$ rabbitmq-queues delete_member admin-events rabbit@rabbitmq-2.rabbitmq-headless.namespace.svc.cluster.local
```

..and reimport the definitions again...

```
$ rabbitmqctl import_definitions load_definitions.json
Importing definitions in JSON from a file at "load_definitions.json" ...
Successfully started definition import. This process is asynchronous and can take some time.
$ rabbitmq-queues quorum_status admin-events
Status of quorum queue admin-events on node rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local ...
┌─────────────────────────────────────────────────────────────────────┬────────────┬───────────┬──────────────┬────────────────┬──────┬─────────────────┐
│ Node Name                                                           │ Raft State │ Log Index │ Commit Index │ Snapshot Index │ Term │ Machine Version │
├─────────────────────────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local │ leader     │ 4         │ 4            │ undefined      │ 1    │ 3               │
└─────────────────────────────────────────────────────────────────────┴────────────┴───────────┴──────────────┴────────────────┴──────┴─────────────────┘

```

So once a quorum queue has been created, reloading the configuration doesn't do anything. 

The manual [here ](https://www.rabbitmq.com/definitions.html#import-on-boot-skip-if-unchanged) states _"By default definitions are imported by every cluster node, unconditionally. "_ 

So it looks like rabbitmq-0 pod is initialised, the config is imported with queue created with only the 1 node, then the additional pods join the cluster but additional imports of the configuration doesn't affect the quorum queue.

It may be that the logic behind load_definition needs to be changed to be post install after the cluster has initialised [(a-la older method)](https://www.rabbitmq.com/definitions.html#import-after-boot)

**Comment by corico44** [comment]
@Millz12 Thanks for the extra information. We will keep that in mind when investigating this case. I'm going to move this issue to on-hold so it won't close.

**Comment by Millz12** [comment]
Hi @corico44 

I've discovered there's a cluster_formation configuration that resolves this issue - it prevents load definitions from running until the cluster is at the target size.

Adding this line into the values.yaml resolves the problem 😃 

`cluster_formation.target_cluster_size_hint = {{ .Values.replicaCount }}`

Thanks

**Comment by corico44** [comment]
@Millz12 Thanks for the information again and for all the work done! Would you be open to contributing this change via a PR? We'd be glad to review and help with the release.
