### ISSUE TITLE
[bitnami/nginx] Example not working, expected usage unclear

### ISSUE THREAD

**Issue by MaRaSu** [bitnami/charts#1530]
**Which chart**: nginx-4.3.10

**Description**

I might be missing something totally obvious here, however I do not understand what is the intended way to use the chart (the way how it's defined to be precise, I'm reasonable familiar with nginx). I would like to add a new serverblock with a simple proxy_pass setup. Now trying to do it like in the README example "providing a customer server block" does not work because nginx.conf that Chart has included already has defined server for port 8080 so if you try to add another server for the same port you get `conflicting server name "" on 0.0.0.0:8080, ignored` from nginx when it starts. 

I could of course use another port in my serverBlock but Chart does not enable configuring nginx container port that get's linked to the service that Chart creates. I could perhaps use server name in serverBlock to prevent conflict however I do not want for my use case.

**Steps to reproduce the issue:**

1. Deploy with using the README example "providing a customer server block"

**Describe the results you received:**

2. Check logs for the conflict on redefining existing server name & port
3.  Nginx startup fails, pod is in "CrashLoopBackOff" state

**Describe the results you expected:**

I would be able to use the server I defined in custom serverBlock.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Hi, @MaRaSu.

Could you please paste the full logs of the failing Nginx container? Also, could you share detailed step by step instructions on what you did? Despite seeing the warning about conflicting ports, I'm not able to reproduce your issue as the container is working for me:

```
 12:27:44.81
 12:27:44.81 Welcome to the Bitnami nginx container
 12:27:44.81 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
 12:27:44.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
 12:27:44.82 Send us your feedback at containers@bitnami.com
 12:27:44.82
 12:27:44.82 INFO  ==> ** Starting NGINX setup **
 12:27:44.83 INFO  ==> Validating settings in NGINX_* env vars...
 12:27:44.84 INFO  ==> Initializing NGINX...
 12:27:44.84 INFO  ==> ** NGINX setup finished! **

 12:27:44.85 INFO  ==> ** Starting NGINX **
2019/10/29 12:27:44 [warn] 1#0: conflicting server name "" on 0.0.0.0:8080, ignored
nginx: [warn] conflicting server name "" on 0.0.0.0:8080, ignored
10.30.2.1 - - [29/Oct/2019:12:27:49 +0000] "GET / HTTP/1.1" 200 6 "-" "kube-probe/1.14+"
10.30.2.1 - - [29/Oct/2019:12:27:54 +0000] "GET / HTTP/1.1" 200 6 "-" "kube-probe/1.14+"
```

On the other hand, if you look to the default `nginx.conf` you will notice that the custom server blocks are included before the default server that listens on port 8080:

```
# Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
# user              www www;  ## Default: nobody

worker_processes  auto;
error_log         "/opt/bitnami/nginx/logs/error.log";
pid               "/opt/bitnami/nginx/tmp/nginx.pid";

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    log_format    main '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status  $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
    access_log    "/opt/bitnami/nginx/logs/access.log";
    add_header    X-Frame-Options SAMEORIGIN;

    client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
    proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
    fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
    scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
    uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

    sendfile           on;
    tcp_nopush         on;
    tcp_nodelay        off;
    gzip               on;
    gzip_http_version  1.0;
    gzip_comp_level    2;
    gzip_proxied       any;
    gzip_types         text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    keepalive_timeout  65;
    ssl_protocols      TLSv1 TLSv1.1 TLSv1.2;
    client_max_body_size 80M;

    include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";

    # HTTP Server
    server {
        # port to listen on. Can also be set to an IP:PORT
        listen  8080;

        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }
    }
}
```

This means that your custom server block listening on port 8080 will be the default one and will be answering all the requests to that port.

**Comment by MaRaSu** [comment]
Hi @alemorcuq,

I tried it again, created my custom values.yaml config with my custom serverBlock from scratch and interestingly enough got it working just fine. I wonder what I managed to mess up the first time I tried this. Sorry about this and thanks for your reply.

There is still perhaps an opportunity to improve README-file (or even config options) here: If you implement the README serverBlock example to the letter AND enable metrics then nginx-exporter container will crash because /status is not available anymore at localhost:8080. 

Easy to fix by adding /status to your custom serverBlock however perhaps not so obvious to someone just starting with nginx and if you need /status uri for your own use then you still need to hack the helm-files.

**Comment by carrodher** [comment]
Thanks for letting us know that the issue is solved. I agree about the docs improvements, do you want to send a PR? If not we can create an internal task to add this information

**Comment by juan131** [comment]
Hi @MaRaSu 

> I tried it again, created my custom values.yaml config with my custom serverBlock from scratch and interestingly enough got it working just fine. I wonder what I managed to mess up the first time I tried this. Sorry about this and thanks for your reply.

I'm glad you were able to solve the issue.

>  There is still perhaps an opportunity to improve README-file (or even config options) here: If you implement the README serverBlock example to the letter AND enable metrics then nginx-exporter container will crash because /status is not available anymore at localhost:8080.
> Easy to fix by adding /status to your custom serverBlock however perhaps not so obvious to someone just starting with NGINX and if you need /status uri for your own use then you still need to hack the helm-files.

Thanks so much for your feedback. You're totally right and we should implement some kind of warning. I created a PR for it.
