### ISSUE TITLE
MongoDB Compass cannot connect to mongoDB but mongosh can

### ISSUE THREAD

**Issue by TheBastosBob** [bitnami/charts#15323]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm --kubeconfig kubeconfig.yml install mongodb bitnami/mongodb  --set architecture=replicaset,replicaCount=1,auth.enabled=false,auth.rootPassword=otopilot,auth.username=otopilot,auth.password=otopilot,auth.database=otopilot,auth.existingSecret=mongodb,persistence.enabled=true,persistence.size=10Gi,persistence.storageClass=csi-cinder-high-speed,externalAccess.enabled=true,externalAccess.service.port=27017,externalAccess.autoDiscovery.enabled=true,rbac.create=true,tls.mode=allow
```

### Are you using any custom parameters or values?
```
--set architecture=replicaset,replicaCount=1,auth.enabled=false,auth.rootPassword=otopilot,auth.username=otopilot,auth.password=otopilot,auth.database=otopilot,auth.existingSecret=mongodb,persistence.enabled=true,persistence.size=10Gi,persistence.storageClass=csi-cinder-high-speed,externalAccess.enabled=true,externalAccess.service.port=27017,externalAccess.autoDiscovery.enabled=true,rbac.create=true,tls.mode=allow
```

### What do you see instead?

Server selection timed out after 30000 ms

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario. Could you try by using default values and installing the Helm chart from scratch?

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
