### ISSUE TITLE
I use the bitnami nginx  in dockerhub deploy on k8s, but can't access from browser.

### ISSUE THREAD

**Issue by andyzheung** [bitnami/charts#1532]
1、microk8s use k8s 1.16:

2、nginx:
![image](https://user-images.githubusercontent.com/22912347/67554540-345e2c80-f742-11e9-919f-7c37324a0a08.png)

3、deploy like this:
![image](https://user-images.githubusercontent.com/22912347/67554572-450ea280-f742-11e9-8daa-ef1c543614ec.png)
![image](https://user-images.githubusercontent.com/22912347/67554597-4d66dd80-f742-11e9-8910-fc45f23f6b85.png)
![image](https://user-images.githubusercontent.com/22912347/67554626-58ba0900-f742-11e9-9b69-fc7428dd841e.png)

4、pod is ok:
![image](https://user-images.githubusercontent.com/22912347/67554662-696a7f00-f742-11e9-99a4-d40dd0008314.png)
![image](https://user-images.githubusercontent.com/22912347/67554689-77b89b00-f742-11e9-9d5c-36886dee77c2.png)

5、but can't access:
I am in the node use browser:
https://localhost:30080
https://216.10.10.100:30080

**Comment by marcosbc** [comment]
Hi @andyzheung, it seems like there is a firewall blocking port 30080 as the connection times out.

If you are using a cloud image in AWS/Azure/GCE/other make sure you update the security group or firewall rules to allow connections to port 30080.

If not, check if your OS has a firewall such as [ufw](https://linuxconfig.org/how-to-enable-disable-firewall-on-ubuntu-18-04-bionic-beaver-linux) or [firewalld](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-using-firewalld-on-centos-7) and allow connections to that port.

**Comment by andyzheung** [comment]
my firewalld is stopped.@marcosbc 
![image](https://user-images.githubusercontent.com/22912347/68175103-1652c080-ffbb-11e9-96d4-2e6a7baf6afe.png)

**Comment by andyzheung** [comment]
I known the problem, nginx in docker listen 8080 but I config the deployment use 80 port. Now I have solve the problem.
![image](https://user-images.githubusercontent.com/22912347/68184042-f92cea80-ffd8-11e9-89a3-432f0ae49265.png)

![image](https://user-images.githubusercontent.com/22912347/68184067-034ee900-ffd9-11e9-834b-a696a96f2248.png)

Thank you.@marcosbc
