### ISSUE TITLE
[bitnami/fluentd] is not working after AKS(1.23.15) and Helm(5.5.16) chart upgrade

### ISSUE THREAD

**Issue by shantdevshukla** [bitnami/charts#15322]
### Name and Version

bitnami/fluentd 1.15.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Earlier it was running successfully.
2. After updation of AKS and Helm.
3. Logs are not writing to the eventhub stream.
4. throwing an error of connection refused.- err=\"dial tcp 172.18.128.66:19100: connect: connection refused\" dialID=6875534559163594919"2023-03-03 16:55:03 +0000

### Are you using any custom parameters or values?

no custom parameters only passing logs to eventhub stream

### What is the expected behavior?

Supposed to run the pod collect the aks pod logs.

### What do you see instead?

pod is running but failing to connect to the aks node.

**Comment by javsalgar** [comment]
Hi,

Something is not clear to me, did you try upgrading the chart as well? If so, from which version?
