### ISSUE TITLE
Cluster fails with Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade.

### ISSUE THREAD

**Issue by rishabhsriv** [bitnami/charts#15327]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create an azure storage account.
2. Link the storage account with a storage class.
3. Update the values.yaml file with storage class details.
4. Install the chart on your k8s cluster.

### What do you see instead?

mongodb logs
<img width="1749" alt="Screenshot 2023-03-04 at 8 09 23 PM" src="https://user-images.githubusercontent.com/35975730/222909656-8c34a1ef-acf3-4cc1-9b7f-f35c23416dee.png">

kubectl describe pvc
<img width="1748" alt="Screenshot 2023-03-04 at 8 19 48 PM" src="https://user-images.githubusercontent.com/35975730/222910957-afc271cc-faf9-426b-a2a4-299ac30923ff.png">

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MongoDB container image or Helm chart but about how the application or environment is being used/configured.

It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
