### ISSUE TITLE
Add ability to set  TCP service configurations

### ISSUE THREAD

**Issue by zenloop** [bitnami/charts#15320]
### Name and Version

bitnami/nginx-ingress-controller

### What is the problem this feature will solve?

I am trying to configure nginx tcp service timeout settings with ingress helm chart.

### What is the feature you are proposing to solve the problem?

When configuring a TCP/UDP service in ingress controller (tcp: \n   8080: "default/example-tcp-svc:9000") , add ability to configure service configurations such as proxy-connect-timeout.  If there is a way to do this already please let me know. Thanks!

### What alternatives have you considered?

Not sure if there is a way to do this already.  Please let me know.

**Comment by corico44** [comment]
Hello @zenloop,

Currently there is no possibility to set TCP service configuration for nginx-ingress-controller. Would you be open to contributing this change via a PR? We'd be glad to review and help with the release.
