### ISSUE TITLE
Support PodSecurity Admission after the PodSecurityPolicy deprecation

### ISSUE THREAD

**Issue by ooii8929** [bitnami/charts#15355]
### Name and Version

kube-state-metrics 3.3.3

### What is the problem this feature will solve?

Kubernetes deprecated the PodSecurityPolicy in version 1.25. According to [the document with kube-state-metrics](https://artifacthub.io/packages/helm/bitnami/kube-state-metrics?modal=template&template=psp.yaml), the latest version is still using PodSecurityPolicy.

### What is the feature you are proposing to solve the problem?

Migrate from PodSecurityPolicy to the Built-In PodSecurity Admission Controller

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by lombardialess** [comment]
the issue is still active and could be a blocker to upgrade k8s to 1.25

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Mauraza** [comment]
Hi @lombardialess and @ooii8929,

I just created an internal task to work on this. We update the thread when we have more information about this.

**Comment by lombardialess** [comment]
@Mauraza what do you mean when you have more information about it?
PodSecurityPolicy has been deprecated since 1.21 and removed 1.25.......should be removed soon from all Bitnami charts probably.
All major cloud providers will not support anymore 1.24 in some months. (Azure in July for example)

**Comment by lombardialess** [comment]
additional info, the issue is also on the node-exporter chart (consumed for example in my case from the prometheus operator chart)

**Comment by Starttoaster** [comment]
This is an issue in multiple Bitnami charts, including the node-exporter one. Fyi

**Comment by Mauraza** [comment]
Hi @Starttoaster,

We have a lot on our plate, but it's in our roadmap. But if you contribute we would really appreciate it.

**Comment by Starttoaster** [comment]
Should not be considered stale. Still an issue.

**Comment by rafariossaa** [comment]
As stated this is found in several assets and will be addressed.

**Comment by juan131** [comment]
Hi @ooii8929 @lombardialess @Starttoaster 

Pod Security Standards can be enforced at namespace label (see https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels) or at cluster level by configuring the built-in admission controller (see https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller).

AFAIK, there's no way to enforce a specific standard (or define exemptions) to the pods deployed by certain chart. For instance, assuming we want to apply the "baseline" standard to pods deployed by chart XXX on namespace YYY, a possible workflow would be:

1. Create namespace YYY adding the `pod-security.kubernetes.io/enforce: baseline` label.
2. Install chart XXX on namespace.

With this in mind, I don't think there's much we can do in the charts other than ensuring the deprecated PSP objects aren't created on K8s > 1.25.  Is there anything else you would expect?

**Comment by Starttoaster** [comment]
> With this in mind, I don't think there's much we can do in the charts other than ensuring the deprecated PSP objects aren't created on K8s > 1.25. Is there anything else you would expect?

@juan131 That's pretty much all I've wanted in this Issue, personally, that the charts don't try to install a deprecated and removed Kind. :+1:

**Comment by juan131** [comment]
Awesome @Starttoaster !! I'll proceed to close the issue then. Feel free to reopen it if you require further assistance.
