### ISSUE TITLE
[bitnami/mongodb] Support for labels on Mongodb PVC

### ISSUE THREAD

**Issue by sjerman** [bitnami/charts#15358]
### Name and Version

bitnami/mongodb 13.8.2

### What is the problem this feature will solve?

Some of the charts (eg mariadb-galera) support labels on PVC templates. MongoDb doesn't. Would be nice to be able to add labels.

### What is the feature you are proposing to solve the problem?

Add to 
https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/statefulset.yaml
```
        labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
          app.kubernetes.io/managed-by: {{ .Release.Service }}
          {{- if .Values.persistence.labels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.persistence.labels "context" $) | nindent 10 }}
          {{- end }}
```
Same as https://github.com/bitnami/charts/blob/main/bitnami/mariadb-galera/templates/statefulset.yaml

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR adding it?
