### ISSUE TITLE
Clickhouse-headless services gets the same annotations as clickhouse service

### ISSUE THREAD

**Issue by alexandrujieanu** [bitnami/charts#15363]
### Name and Version

bitnami/clickhouse 3.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the Helm Chart in AWS EKS
2. Define `service.type` LoadBalancer and `service.annotations` for AWS LB Controller
3. Both service and [service-headless](https://github.com/bitnami/charts/blob/main/bitnami/clickhouse/templates/service-headless.yaml#L12-L15) get the annotations. 
3. In consequence, two Load Balancers are created, one for service and another one for service-headless.

### Are you using any custom parameters or values?

```yaml
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    ....
```

### What is the expected behavior?

I expect only the service to be exposed using AWS LB.

### What do you see instead?

```console
$ kubectl -n clickhouse get svc
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)                                                                      AGE
clickhouse                      LoadBalancer   10.100.40.123    k8s-clickhou-clickhou-fe06e3fb1e-1e17YYYYYYY401a.elb.us-east-1.amazonaws.com   8123:30400/TCP,9000:31272/TCP,9004:30361/TCP,9005:30690/TCP,9009:32343/TCP   23m
clickhouse-headless             ClusterIP      None             <none>                                                                          8123/TCP,9000/TCP,9004/TCP,9005/TCP,9009/TCP                                 23m
```

`clickhouse-headless` has type `ClusterIP`, but still gets the annotations and the AWS LB Controller detects it.

```console
$ kubectl -n clickhouse get svc clickhouse-headless -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: clickhouse.xxxx.yyyy.zzz
    meta.helm.sh/release-name: clickhouse
    meta.helm.sh/release-namespace: clickhouse
```

```console
$ kubectl -n clickhouse get svc clickhouse-headless -o yaml | tail -10
  selector:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/name: clickhouse
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer:
    ingress:
    - hostname: k8s-clickhou-clickhou-006ee17ece-a7dXXXXXXX02fcb.elb.us-east-1.amazonaws.com
```
```console
$ kubectl -n clickhouse get svc clickhouse -o yaml | tail -10
  selector:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/name: clickhouse
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: k8s-clickhou-clickhou-fe06e3fb1e-1e17YYYYYYY401a.elb.us-east-1.amazonaws.com
```

### Additional information

As far as I understand the `clickhouse-headless` service is for internal use and only the `clickhouse` service should be exposed outside of the kubernetes cluster. I am also trying to understand if the AWS LB Controller should only detect services that have type `LoadBalancer`.

**Comment by migruiz4** [comment]
Hi @alexandrujieanu,

Thank you for reporting this issue! I have submitted this PR (https://github.com/bitnami/charts/pull/15425) adding the value `service.headless.annotations` and removing `service.annotations` from the headless service.

This way, it would be possible to configure the annotations for each service separately as in your use case.
