### ISSUE TITLE
[bitnami/redis-cluster] Deleted replica information cannot be removed.

### ISSUE THREAD

**Issue by sdYoo** [bitnami/charts#15361]
### Name and Version

bitnami/redis-cluster 7.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I currently have a redis-cluster consisting of 3 masters and 3 replica.
I configured the pods to float on static nodes with hostnetwork
```
master1-pod(node1)  - replica1-pod(node4)
master2-pod(node2) - replica2-pod(node5)
master3-pod(node3) - replica3-pod(node6)
```
3. Replica1-pod was deleted for testing.
4. Replica1-pod were recreated and executed normally, but were not automatically joined in Master1-pod.
(The pod is recreated on the same node-node4.)
6. Also, the deleted replica information remains in the Master1-pod > nodes.conf file.
```
test:/bitnami/redis/data$ cat nodes.conf
b28661ebe8eff7aebcc44040ec7d105d91e0195e 10.170.66.156:46379@56379 slave 638990e148d5af410f9e5f5e33e2d9e321378da1 0 1678098981613 2 connected
638990e148d5af410f9e5f5e33e2d9e321378da1 10.170.66.149:46379@56379 myself,master - 0 1678098981000 2 connected 5461-10922

**f8239cdc4c3927249273661e018eb5958a9f75e3 :0@0 slave,noaddr 638990e148d5af410f9e5f5e33e2d9e321378da1 1678084301025 1678084298015 2 disconnected**

aedbcabcb0e91842bf5178dc4a429ed94f0540be 10.170.66.155:46379@56379 slave c35319fb79c6c84a6b2670f4dd0b70b4ace4b5d0 0 1678098980000 1 connected
33dc671b5bcabbfd0b40626f169566f9e8d4c23c 10.170.66.154:46379@56379 slave e816f3f8f6aa7dacf599a0fef4da9a92170eb5f7 0 1678098980609 3 connected
e816f3f8f6aa7dacf599a0fef4da9a92170eb5f7 10.170.66.150:46379@56379 master - 0 1678098979605 3 connected 10923-16383
c35319fb79c6c84a6b2670f4dd0b70b4ace4b5d0 10.170.66.148:46379@56379 master - 0 1678098980000 1 connected 0-5460
```

### What is the expected behavior?

1. After deletion, the newly created replica1-pod should be automatically joined.
-> I would like to know what redis-cluster options are automatically joined.

2. Information of Prior replica1-pod should be deleted from nodes.conf
-> How to remove old replica information?
 It is not deleted even if you use the forget, del-node commands.
```
195e 10.170.66.156:46379@56379 slave 8da1 0 1678098981613 2 connected
8da1 10.170.66.149:46379@56379 myself,master - 0 1678098981000 2 connected 5461-10922
75e3 :0@0 slave,noaddr 8da1 1678084301025 1678084298015 2 disconnected
40be 10.170.66.155:46379@56379 slave b5d0 0 1678098980000 1 connected
c23c 10.170.66.154:46379@56379 slave b5f7 0 1678098980609 3 connected
b5f7 10.170.66.150:46379@56379 master - 0 1678098979605 3 connected 10923-16383
b5d0 10.170.66.148:46379@56379 master - 0 1678098980000 1 connected 0-5460
```

### What do you see instead?

A new replica pod was created normally on the same node, and I tried to delete the previous information, but the following error occurred.
```
I have no name!@k8s-master-1:/$ redis-cli --cluster del-node 10.0.0.0:6379 f8239cdc4c392724927366
>>> Removing node f8239cdc4c392724927366 from cluster 10.0.0.0:6379
[ERR] No such node ID f8239cdc4c392724927366
```

**Comment by sdYoo** [comment]
Hi @javsalgar 

When replica pods are deleted, new replica pods are recreated but do not automatically connect to the existing redis-cluster.
Can't I have new replica pods connect redis-cluster automatically?

* Attach log file
1. argo cd log
2. redis log

1) replica1 pod (argo cd log)
COPYING FILE
redis-cluster 04:56:03.39
redis-cluster 04:56:03.39 Welcome to the Bitnami redis-cluster container
redis-cluster 04:56:03.40 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 04:56:03.40 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 04:56:03.40 
redis-cluster 04:56:03.40 INFO  ==> ** Starting Redis setup **
redis-cluster 04:56:03.42 INFO  ==> Initializing Redis
redis-cluster 04:56:03.44 INFO  ==> Setting Redis config file
Storing map with hostnames and IPs
redis-cluster 04:56:03.71 INFO  ==> ** Redis setup finished! **

2) replica1 pod (redis log)
I have no name!@redis-replica:/tmp$ cat redis-server.log
1:C 10 Mar 2023 04:56:03.802 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 10 Mar 2023 04:56:03.802 # Redis version=7.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 10 Mar 2023 04:56:03.802 # Configuration loaded
1:M 10 Mar 2023 04:56:03.802 * monotonic clock: POSIX clock_gettime
1:M 10 Mar 2023 04:56:03.803 * No cluster configuration found, I'm 757acf841edcc6a71e37b6625114dde8b73faf77
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 7.0.7 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 46379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 10 Mar 2023 04:56:03.805 # Server initialized
1:M 10 Mar 2023 04:56:03.807 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 10 Mar 2023 04:56:03.809 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 10 Mar 2023 04:56:03.809 * Ready to accept connections

**Comment by marcosbc** [comment]
Hi @sdYoo, have you checked this? https://redis.io/commands/cluster-forget/

Note that due to how Kubernetes pods work, it is possible that Redis is not aware of a replica being deleted,.

That said, the new replica should join the Redis master node without issues. If you find issues on that aspect, could you share more information? Such as logs, etc.

**Comment by sdYoo** [comment]
Thanks kindly answer!

I guess it's a mount-path problem.
When I set the config path as below, it was recognized normally.

persistence:
  enabled: true
  path: /bitnami/redis/data
