### ISSUE TITLE
Support TLS in memcached

### ISSUE THREAD

**Issue by haizafrog** [bitnami/charts#15365]
### Name and Version

bitnami /memcached 

### What is the problem this feature will solve?

Secure Memcached and enable in-transit encryption

### What is the feature you are proposing to solve the problem?

Implement the Memcached community TLS
https://github.com/memcached/memcached/blob/master/doc/tls.txt

**Comment by carrodher** [comment]
Thanks for the suggestion! Would you like to contribute by creating a PR to add this feature? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by haizafrog** [comment]
Thank you for the response Carlos!
I will try to get the time to do it and I will be happy to contribute what I did internally to the Memcached community Dockerfile.
