### ISSUE TITLE
[bitnami/redis-cluster] When deleting the master pod, it is necessary for the replica to be converted to the master.

### ISSUE THREAD

**Issue by sdYoo** [bitnami/charts#15384]
### Name and Version

bitnami/redis-cluster 7.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I currently have a redis-cluster consisting of 3 masters and 3 replica.
I configured the pods to float on static nodes with hostnetwork
```
master1-pod(node1  10.0.0.1) - replica1-pod(node4  10.0.0.4)
master2-pod(node2 10.0.0.2) - replica2-pod(node5 10.0.0.5)
master3-pod(node3 10.0.0.3) - replica3-pod(node6 10.0.0.6)
```
2. master1-pod was deleted for testing.(kubectl delete pod~)

3. I thought replica1-pod would be promoted to master1, but it wasn't.

4. How do I get my replica to be promoted to master?

### Are you using any custom parameters or values?

none

### What is the expected behavior?

 I thought replica1-pod would be promoted to master1, but it wasn't.

1) master1 deleted
2) replica1 -> new master1

but As shown below, the master information is remain, 
and the replica is also viewing the deleted master information.

(Node ID is shortened)
```
localhost:6379> cluster nodes
4b5d0 :0@0 master,noaddr - 1678249219710 1678249214000 1 disconnected 0-5460
540be 10.0.0.4:6379@56379 myself,slave 4b5d0 0 1678257160000 1 connected
78da1  10.0.0.2:6379@56379 master - 0 1678257160000 2 connected 5461-10922
0195e  10.0.0.5:6379@56379 slave 78da1 0 1678257161827 2 connected
eb5f7   10.0.0.3:6379@56379 master - 0 1678257162829 3 connected 10923-16383
4c23c  10.0.0.6:6379@56379 slave eb5f7 0 1678257161000 3 connected
```

### What do you see instead?

An error occurs when the forget command is executed. 
```
localhost:46379> cluster forget 4b5d0
(error) ERR Can't forget my master!
```
It is converted manually with the "cluster failover takeover" command.
I want to know the setting to automatically switch from replica to master.

### Additional information

What settings do I need to set to make the replica switch to master when the master pod is deleted?

It is converted manually with the "cluster failover takeover" command.
I want to know the setting to automatically switch from replica to master.

**Comment by Mauraza** [comment]
Hi @sdYoo,

You delete the master with `kubectl delete pod...` probably the pod is being recreated and the master is active again, you can check with `kubectl get pod -w` when you are running the steps you described.

**Comment by sdYoo** [comment]
Hi @Mauraza 

Could this be caused by the master pod restarting quickly?
cluster-node-timeout was 15 seconds.
Is 5 seconds good enough?

**Comment by sdYoo** [comment]
@Mauraza 
I set cluster-node-timeout to 5 seconds, but the replica-redis does not switch to master-redis.
How can I automatically convert a replica-redis to a master-redis when deleting a master-redis?

1) befor deleted master pod logs
2) deleted master-redis pod
3) after deleted master pod logs
4) describe replica-redis log file

---- test info -----
master-redis node id: 66c2b6968f261e3615e04347ba636b467a5e6850
replica-redis node id: e6392dd3f98416cdc96ffdbf044a219a3643f75a

---- detail logs -----
1) befor deleted master pod
localhost:46379> cluster nodes
5a15318e672a876b5c233358cf52e725dbdc4441 10.170.66.148:46379@56379 master - 0 1678427479248 1 connected 0-5460
66c2b6968f261e3615e04347ba636b467a5e6850 10.170.66.150:46379@56379 master - 0 1678427478243 3 connected 10923-16383
30f11172146cdc36a208407605683ac0e2461b04 10.170.66.155:46379@56379 slave 5a15318e672a876b5c233358cf52e725dbdc4441 0 1678427478042 1 connected
62c370e156698dde4f552b2f8736b0ed610c002c 10.170.66.149:46379@56379 master - 0 1678427479750 2 connected 5461-10922
76f73eeb3e5dabcaf1eab552235f4b43b68965fe 10.170.66.156:46379@56379 slave 62c370e156698dde4f552b2f8736b0ed610c002c 0 1678427478042 2 connected
e6392dd3f98416cdc96ffdbf044a219a3643f75a 10.170.66.154:46379@56379 myself,slave 66c2b6968f261e3615e04347ba636b467a5e6850 0 1678427478000 3 connected

2) deleted master-redis pod

3) after deleted master pod
localhost:46379> cluster nodes
5a15318e672a876b5c233358cf52e725dbdc4441 10.170.66.148:46379@56379 master - 0 1678427499550 1 connected 0-5460
66c2b6968f261e3615e04347ba636b467a5e6850 :0@0 master,noaddr - 1678427498035 1678427495518 3 disconnected 10923-16383
30f11172146cdc36a208407605683ac0e2461b04 10.170.66.155:46379@56379 slave 5a15318e672a876b5c233358cf52e725dbdc4441 0 1678427499550 1 connected
62c370e156698dde4f552b2f8736b0ed610c002c 10.170.66.149:46379@56379 master - 0 1678427498338 2 connected 5461-10922
76f73eeb3e5dabcaf1eab552235f4b43b68965fe 10.170.66.156:46379@56379 slave 62c370e156698dde4f552b2f8736b0ed610c002c 0 1678427499349 2 connected
e6392dd3f98416cdc96ffdbf044a219a3643f75a 10.170.66.154:46379@56379 myself,slave 66c2b6968f261e3615e04347ba636b467a5e6850 0 1678427499000 3 connected

4) replica redis.log
1:M 10 Mar 2023 05:41:29.925 # Server initialized
1:M 10 Mar 2023 05:41:29.927 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 10 Mar 2023 05:41:29.929 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 10 Mar 2023 05:41:29.929 * Ready to accept connections
1:M 10 Mar 2023 05:41:31.078 # configEpoch set to 4 via CLUSTER SET-CONFIG-EPOCH
1:M 10 Mar 2023 05:41:32.040 # Cluster state changed: ok
1:S 10 Mar 2023 05:41:33.083 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
1:S 10 Mar 2023 05:41:33.083 * Connecting to MASTER 10.170.66.150:46379
1:S 10 Mar 2023 05:41:33.083 * MASTER <-> REPLICA sync started
1:S 10 Mar 2023 05:41:33.083 * Non blocking connect for SYNC fired the event.
1:S 10 Mar 2023 05:41:33.084 * Master replied to PING, replication can continue...
1:S 10 Mar 2023 05:41:33.084 * Trying a partial resynchronization (request 16f63cb33aec3d3cfa62464dd18efece78bc6add:1).
1:S 10 Mar 2023 05:41:33.086 * Full resync from master: 6681d1a6ac6786e86ed7d69423d9ad404ce089cd:0
1:S 10 Mar 2023 05:41:33.107 * MASTER <-> REPLICA sync: receiving 171 bytes from master to disk
1:S 10 Mar 2023 05:41:33.107 * Discarding previously cached master state.
1:S 10 Mar 2023 05:41:33.107 * MASTER <-> REPLICA sync: Flushing old data
1:S 10 Mar 2023 05:41:33.107 * MASTER <-> REPLICA sync: Loading DB in memory
1:S 10 Mar 2023 05:41:33.110 * Loading RDB produced by version 7.0.7
1:S 10 Mar 2023 05:41:33.110 * RDB age 0 seconds
1:S 10 Mar 2023 05:41:33.110 * RDB memory usage when created 1.81 Mb
1:S 10 Mar 2023 05:41:33.110 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:S 10 Mar 2023 05:41:33.110 * MASTER <-> REPLICA sync: Finished with success
1:S 10 Mar 2023 05:41:33.110 * Creating AOF incr file temp-appendonly.aof.incr on background rewrite
1:S 10 Mar 2023 05:41:33.110 * Background append only file rewriting started by pid 127
127:C 10 Mar 2023 05:41:33.112 * Successfully created the temporary AOF base file temp-rewriteaof-bg-127.aof
127:C 10 Mar 2023 05:41:33.112 * Fork CoW for AOF rewrite: current 0 MB, peak 0 MB, average 0 MB
1:S 10 Mar 2023 05:41:33.145 * Background AOF rewrite terminated with success
1:S 10 Mar 2023 05:41:33.146 * Successfully renamed the temporary AOF base file temp-rewriteaof-bg-127.aof into appendonly.aof.2.base.rdb
1:S 10 Mar 2023 05:41:33.146 * Successfully renamed the temporary AOF incr file temp-appendonly.aof.incr into appendonly.aof.2.incr.aof
1:S 10 Mar 2023 05:41:33.148 * Removing the history file appendonly.aof.1.incr.aof in the background
1:S 10 Mar 2023 05:41:33.148 * Removing the history file appendonly.aof.1.base.rdb in the background
1:S 10 Mar 2023 05:41:33.149 * Background AOF rewrite finished successfully
1:S 10 Mar 2023 05:51:35.556 # Connection with master lost.
1:S 10 Mar 2023 05:51:35.556 * Caching the disconnected master state.
1:S 10 Mar 2023 05:51:35.556 * Reconnecting to MASTER 10.170.66.150:46379
1:S 10 Mar 2023 05:51:35.556 * MASTER <-> REPLICA sync started
1:S 10 Mar 2023 05:51:35.556 # Error condition on socket for SYNC: Connection refused
1:S 10 Mar 2023 05:51:36.424 * Connecting to MASTER 10.170.66.150:46379
1:S 10 Mar 2023 05:51:36.424 * MASTER <-> REPLICA sync started
1:S 10 Mar 2023 05:51:36.424 # Error condition on socket for SYNC: Connection refused
1:S 10 Mar 2023 05:51:37.431 * Connecting to MASTER 10.170.66.150:46379
1:S 10 Mar 2023 05:51:37.431 * MASTER <-> REPLICA sync started
1:S 10 Mar 2023 05:51:37.431 # Error condition on socket for SYNC: Connection refused
1:S 10 Mar 2023 05:51:38.438 * Connecting to MASTER 10.170.66.150:46379
1:S 10 Mar 2023 05:51:38.438 * MASTER <-> REPLICA sync started
1:S 10 Mar 2023 05:51:38.439 * Non blocking connect for SYNC fired the event.
1:S 10 Mar 2023 05:51:38.440 * Master replied to PING, replication can continue...
1:S 10 Mar 2023 05:51:38.440 * Trying a partial resynchronization (request 6681d1a6ac6786e86ed7d69423d9ad404ce089cd:841).
1:S 10 Mar 2023 05:51:38.441 * Full resync from master: 0a35c7ffd53fb59be5e30516be382e97f2068ff0:0
1:S 10 Mar 2023 05:51:38.500 * MASTER <-> REPLICA sync: receiving 171 bytes from master to disk
1:S 10 Mar 2023 05:51:38.500 * Discarding previously cached master state.
1:S 10 Mar 2023 05:51:38.500 * MASTER <-> REPLICA sync: Flushing old data
1:S 10 Mar 2023 05:51:38.500 * MASTER <-> REPLICA sync: Loading DB in memory
1:S 10 Mar 2023 05:51:38.504 * Loading RDB produced by version 7.0.7
1:S 10 Mar 2023 05:51:38.504 * RDB age 0 seconds
1:S 10 Mar 2023 05:51:38.504 * RDB memory usage when created 1.60 Mb
1:S 10 Mar 2023 05:51:38.504 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:S 10 Mar 2023 05:51:38.504 * MASTER <-> REPLICA sync: Finished with success
1:S 10 Mar 2023 05:51:38.504 * Creating AOF incr file temp-appendonly.aof.incr on background rewrite
1:S 10 Mar 2023 05:51:38.505 * Background append only file rewriting started by pid 2299
2299:C 10 Mar 2023 05:51:38.507 * Successfully created the temporary AOF base file temp-rewriteaof-bg-2299.aof
2299:C 10 Mar 2023 05:51:38.507 * Fork CoW for AOF rewrite: current 0 MB, peak 0 MB, average 0 MB
1:S 10 Mar 2023 05:51:38.539 * Background AOF rewrite terminated with success
1:S 10 Mar 2023 05:51:38.539 * Successfully renamed the temporary AOF base file temp-rewriteaof-bg-2299.aof into appendonly.aof.3.base.rdb
1:S 10 Mar 2023 05:51:38.539 * Successfully renamed the temporary AOF incr file temp-appendonly.aof.incr into appendonly.aof.3.incr.aof
1:S 10 Mar 2023 05:51:38.542 * Removing the history file appendonly.aof.2.incr.aof in the background
1:S 10 Mar 2023 05:51:38.542 * Removing the history file appendonly.aof.2.base.rdb in the background
1:S 10 Mar 2023 05:51:38.544 * Background AOF rewrite finished successfully

**Comment by sdYoo** [comment]
@Mauraza 
Below is the values.yaml setting I applied.

cluster:
  init: true
  nodes: 6
  replicas: 1

service:
  ports:
    redis: 46379
  nodePorts:
    redis: "32103"

persistence:
  enabled: true
  path: /home/redis/redis-volume
  size: 40Gi
  accessModes:
    - ReadWriteOnce

# k8s hostnetwork: true
nodeips: 10.10.0.148
         10.10.0.149
         10.10.0.150
         10.10.0.154
         10.10.0.155
         10.10.0.156

customconf:
  daemonize: no
  logfile: "/tmp/redis-server.log"
  clusterNodeTimeout: 5000

**Comment by sdYoo** [comment]
@Mauraza 
My problem is that the replica does not promoted to master and keeps the below state.

localhost:46379> cluster nodes
5a15318e672a876b5c233358cf52e725dbdc4441 10.10.0.148:46379@56379 master - 0 1678427499550 1 connected 0-5460
66c2b6968f261e3615e04347ba636b467a5e6850 :0@0 master,noaddr - 1678427498035 1678427495518 3 disconnected 10923-16383
30f11172146cdc36a208407605683ac0e2461b04 10.10.0.155:46379@56379 slave 5a15318e672a876b5c233358cf52e725dbdc4441 0 1678427499550 1 connected
62c370e156698dde4f552b2f8736b0ed610c002c 10.10.0.149:46379@56379 master - 0 1678427498338 2 connected 5461-10922
76f73eeb3e5dabcaf1eab552235f4b43b68965fe 10.10.0.156:46379@56379 slave 62c370e156698dde4f552b2f8736b0ed610c002c 0 1678427499349 2 connected
e6392dd3f98416cdc96ffdbf044a219a3643f75a 10.10.0.154:46379@56379 myself,slave 66c2b6968f261e3615e04347ba636b467a5e6850 0 1678427499000 3 connected

**Comment by cveld** [comment]
I believe you should enable the sentinel feature. I watched this youtube: https://www.youtube.com/watch?v=GEg7s3i6Jak hopefully you can confirm?

**Comment by Mauraza** [comment]
Hi @sdYoo,

The promotion takes time, and the time to delete a pod a recreate is not enough. Could you tell us, why you want to check the promotion?

**Comment by sdYoo** [comment]
@Mauraza @cveld 

I am testing HA for redis-cluster.

I guess it's a mount-path problem.
When I set the config path as below, it was recognized normally.

persistence:
enabled: true
path: /bitnami/redis/data

**Comment by AbhilashKopalli** [comment]
Hi @Mauraza @cveld @sdYoo,

What is the fix for this? 

I am doing the exact same config with 1 master and 2 replicas, and when I issue the "kubectl delete command", the master pod gets deleted, but none of the replicas is promoted to the master. 

Instead new master is created and all the keys are getting lost in the process.

PS: I have set persistence to false, as we don't need persistence here.

**Comment by carrodher** [comment]
Thank you for reaching out and for your interest in our project. We'd be happy to assist you, but to do so effectively, we'll need some more details. Could you please create a separate issue filling the Issue template?

Providing this information will help us better understand your situation and assist you in a more targeted manner.

**Comment by AbhilashKopalli** [comment]
Sure @carrodher , raised a ticket for it already. 
Since, it is closely linked to this ticket, just checking if there is any possible fix for this issue already.

https://github.com/bitnami/charts/issues/26114
