### ISSUE TITLE
[bitnami/rabbitmq] Node rabbit@rabbitmq-1.rabbitmq-headless.ns.svc.cluster.local is not running or has not fully booted yet

### ISSUE THREAD

**Issue by zohebs341** [bitnami/charts#15386]
### Name and Version

bitnami/rabbitmq:3.10.8-debian-11-r4

### What architecture are you using?

None

### What steps will reproduce the bug?

We are running RabbitMQ in Azure AKS 1.24.9. Whenever we restart RabbitMQ, most of the time it is not coming up and fails with the below error.

RabbitMQ on node rabbit@rabbitmq-1.rabbitmq-headless.namespace.svc.cluster.local is not running or has not fully booted yet (check with is_booting)

Is it a bug in the version we are using? Please let us know the action needs to be taken.

bitnami/rabbitmq:3.10.8-debian-11-r4

### What is the expected behavior?

Excepted behavior is, it rabbitmq pods should come up. Even if we restart.

### What do you see instead?

If rabbitmq is not coming up, in this case. We are deleting that pod and then it's coming up.

**Comment by javsalgar** [comment]
Hi,

It seems that there is some startup process that is not being done correctly. In this sense, it is not fully clear to me that it has to do with the Bitnami packaging of the application. Did you check with the upstream RabbitMQ devs?
