### ISSUE TITLE
[bitnami/redis] Liveness probe failed: Could not connect to Redis at redis-master-0.redis-headless.system.svc.cluster.local:6379: Name or service not known

### ISSUE THREAD

**Issue by TAM360** [bitnami/charts#15385]
### Name and Version

bitnami/redis latest
kubernetes v1,21,0 (bare metal)
CentOS 7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm install redis -f values.yaml bitnami/redis -n system`

### Are you using any custom parameters or values?

Yes

```yaml
master:
  persistence:
     enabled: false

replica:
  persistence:
     enabled: false

sentinel:
  persistence:
     enabled: false
```

### What is the expected behavior?

Redis replica pod should be able to connect with master pod and start serving the traffic.

### What do you see instead?

Liveness & Readiness probes of replica pod fail
![lens-screen-shot](https://user-images.githubusercontent.com/18717997/223644672-b825cc75-72a3-4f51-bfac-50d58a5d605d.png)

```
Liveness probe failed: Could not connect to Redis at redis-master-0.redis-headless.system.svc.cluster.local:6379: Name or service not known

Readiness probe failed: Could not connect to Redis at redis-master-0.redis-headless.system.svc.cluster.local:6379: Name or service not known
```

Here are the pod's logs 
```
1:S 08 Mar 2023 07:11:04.712 * RDB is base AOF
1:S 08 Mar 2023 07:11:04.712 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:S 08 Mar 2023 07:11:04.712 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
1:S 08 Mar 2023 07:11:04.712 * DB loaded from append only file: 0.000 seconds
1:S 08 Mar 2023 07:11:04.712 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:S 08 Mar 2023 07:11:04.712 * Ready to accept connections
1:S 08 Mar 2023 07:11:04.713 * Connecting to MASTER redis-master-0.redis-headless.system.svc.cluster.local:6379
1:S 08 Mar 2023 07:11:04.716 # Unable to connect to MASTER: Invalid argument
1:S 08 Mar 2023 07:11:05.718 * Connecting to MASTER redis-master-0.redis-headless.system.svc.cluster.local:6379
1:S 08 Mar 2023 07:11:05.719 # Unable to connect to MASTER: Invalid argument
1:S 08 Mar 2023 07:11:06.721 * Connecting to MASTER redis-master-0.redis-headless.system.svc.cluster.local:6379
1:S 08 Mar 2023 07:11:06.722 # Unable to connect to MASTER: Invalid argument
```

### Additional information

I've tried the following solutions based on past comments but they aren't working in my case:
1. Disabling persistence in the chart ([link](https://github.com/bitnami/charts/issues/4830#issuecomment-753958709))
2. Verifying my CoreDNS version which v1.8.0 ([link](https://github.com/bitnami/charts/issues/4830#issuecomment-881545010))
3. Restarting CoreDNS `Deployment` ([link](https://github.com/bitnami/charts/issues/4830#issuecomment-1128355705))

**Comment by javsalgar** [comment]
Hi,

Indeed, it looks like a DNS issue. Could you check if other services in the cluster are accessible? I would try deploying the chart with `diagnosticMode.enabled=true` and check if the networking is working as expected.

**Comment by javsalgar** [comment]
Hi,

Yes, the idea behind this mode is that you can enter the pods, execute commands and check networking.

**Comment by cgqcgq123** [comment]
How to solve it? Can you give me a detailed procedure please?

**Comment by cgqcgq123** [comment]
my problem is

1:S 02 Dec 2023 08:29:06.541 * Connecting to MASTER redis-master-0.redis-headless.redis.svc.cluster.local:6379
1:S 02 Dec 2023 08:29:26.563 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 02 Dec 2023 08:29:27.571 * Connecting to MASTER redis-master-0.redis-headless.redis.svc.cluster.local:6379
1:S 02 Dec 2023 08:29:47.590 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 02 Dec 2023 08:29:48.599 * Connecting to MASTER redis-master-0.redis-headless.redis.svc.cluster.local:6379
1:signal-handler (1701505799) Received SIGTERM scheduling shutdown...
1:S 02 Dec 2023 08:30:08.615 # Unable to connect to MASTER: Resource temporarily unavailable
1:S 02 Dec 2023 08:30:08.716 * User requested shutdown...
1:S 02 Dec 2023 08:30:08.716 * Calling fsync() on the AOF file.
1:S 02 Dec 2023 08:30:08.716 # Redis is now ready to exit, bye bye...


is there any way to solve it?

**Comment by octavian2204** [comment]
Same issue here, services have non default dns name: `redis-master.redis.svc.domain.com` and `redis-replicas.redis.svc.domaincom`. So from master-0 pod:
```
 octav@MacBoook  master-0:/$ redis-cli -c -h redis-master-0.redis-headless.redis.svc.cluster.local
Could not connect to Redis at redis-master-0.redis-headless.redis.svc.cluster.local:6379: Name or service not known
not connected>
I have no name!@redis-master-0:/$ redis-cli -c -h redis-master-0.redis-headless.redis.svc.domain.com
redis-master-0.redis-headless.redis.svc.domain.com:6379> ping
PONG
```
