### ISSUE TITLE
Enable user.xml override 

### ISSUE THREAD

**Issue by moutyque** [bitnami/charts#15388]
### Name and Version

bitnami/clickhouse  latest

### What is the problem this feature will solve?

Being able to defined user settings.

### What is the feature you are proposing to solve the problem?

Provide a way to override user.xml values through the values.yaml file.  

### What alternatives have you considered?

Pass the settings through the client or the url but it is more painfull.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
