### ISSUE TITLE
[bitnami/redmine] plugins installation

### ISSUE THREAD

**Issue by skliarie** [bitnami/charts#15389]
### Name and Version

bitnami/redmine redmine-21.0.6, installs redmine 5.0.4

### What is the problem this feature will solve?

Automatic redmine plugins installation on container start

### What is the feature you are proposing to solve the problem?

Redmine has many useful plugins: checklists, agile, etc.

Requiring users to fork and build their own redmine for that is too much IMHO

### What alternatives have you considered?

cron to install the plugin on restart, but it did not work.

**Comment by skliarie** [comment]
Having list of plugins in some configmap on CLI of startup script would be nice..

**Comment by javsalgar** [comment]
Hi,

Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.

**Comment by seanbrennanzj** [comment]
> Having list of plugins in some configmap on CLI of startup script would be nice..

Did you get this resolved? This has been preventing me from using Kubernetes to run Redmine as it is almost useless without the plugin support. 
did you make a fork and get that working I can use?

**Comment by mimmus** [comment]
Any news about this?

**Comment by s0l4r** [comment]
I also would like to see this feature, the image cannot be used with custom plugins because it is out of sync with the manually installed plugins on the PVC.

**Comment by skliarie** [comment]
I ended up using redmine from docker-compose, with a script (attached, rename txt to sh
[install_plugins.txt](https://github.com/user-attachments/files/16930279/install_plugins.txt)
) to build and install plugins (tested with redmine_checklists and redmine_kanban).

Tested on
image: docker.io/bitnami/redmine:5.1.3-debian-12-r9
