### ISSUE TITLE
Controller protocol isnt set if external access enabled

### ISSUE THREAD

**Issue by burkempers** [bitnami/charts#15402]
### Name and Version

bitnami/kafka:21.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

set values for enabling externalAccess and Kraft to true

### Are you using any custom parameters or values?

set values for enabling externalAccess and Kraft to true

### What is the expected behavior?

that the env value for the KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP in the statefulset gets set correctly

### What do you see instead?

looks like lines 192 and 194 are swapped
https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/statefulset.yaml#L192-L194

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
