### ISSUE TITLE
Clair notifier log spam

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#1543]
In the harbor chart, the Clair pod is constantly spamming the logs with errors regarding the notifiers like these:

> {"Event":"found and locked a notification","Level":"info","Location":"notifier.go:143","Time":"2019-10-28 17:16:58.647841","notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2"} 
{"Event":"could not send notification via notifier","Level":"error","Location":"notifier.go:173","Time":"2019-10-28 17:16:58.653168","error":"got status 404, expected 200/201","notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2","sender name":"webhook"} 
{"Event":"waiting before retrying to send notification","Level":"info","Location":"notifier.go:163","Time":"2019-10-28 17:16:58.653217","attempts":2,"duration":1000000000,"max attempts":3,"notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2","sender name":"webhook"} 
{"Event":"could not send notification via notifier","Level":"error","Location":"notifier.go:173","Time":"2019-10-28 17:16:59.658268","error":"got status 404, expected 200/201","notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2","sender name":"webhook"} 
{"Event":"waiting before retrying to send notification","Level":"info","Location":"notifier.go:163","Time":"2019-10-28 17:16:59.658315","attempts":3,"duration":2000000000,"max attempts":3,"notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2","sender name":"webhook"} 
{"Event":"could not send notification via notifier","Level":"error","Location":"notifier.go:173","Time":"2019-10-28 17:17:01.663683","error":"got status 404, expected 200/201","notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2","sender name":"webhook"} 
{"Event":"giving up on sending notification : max attempts exceeded","Level":"info","Location":"notifier.go:157","Time":"2019-10-28 17:17:01.663731","max attempts":3,"notification name":"c1917e8f-fe05-47f3-a8d8-ef50a8612db2","sender name":"webhook"} 

Per the main chart, this is an issue with 1.8 to 1.9 compatibility (see https://github.com/goharbor/harbor/issues/9305), and is resolved by removing the notifier section from the clair configmap.

**Comment by alemorcuq** [comment]
Thanks for reporting this issue, @ajchiarello. We will fix it.
