### ISSUE TITLE
[bitnami/harbor] Embedded redis/postgres need containerSecurityContext and podSecurityContext

### ISSUE THREAD

**Issue by udf2457** [bitnami/charts#15467]
### Name and Version

bitnami/harbor 16.4.5

### What architecture are you using?

None

### What steps will reproduce the bug?

At present, `values.xml` for `bitnami/harbor` does not expose `containerSecurityContext` or `podSecurityContext` for the bundled redis and postgresql.

As a result, attempting to deploy the chart to a Restricted PSS namespace (https://kubernetes.io/docs/concepts/security/pod-security-standards/) fails:

```
W0312 08:19:45.407860   36907 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "postgresql" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "postgresql" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "postgresql" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "postgresql" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

W0312 08:19:45.407859   36907 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "redis" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "redis" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "redis" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "redis" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by carrodher** [comment]
Even if not exposed, you can use at the Harbor's values.yaml any parameter defined in the subcharts values file.
For instance, you can look at the redis parameters at https://github.com/bitnami/charts/tree/main/bitnami/redis#redis-master-configuration-parameters and then add any of those parameters under the `redis:` section of Harbor's values.yaml
