### ISSUE TITLE
[bitnami/harbor] Multi-Attach error for PVC

### ISSUE THREAD

**Issue by udf2457** [bitnami/charts#15468]
### Name and Version

bitnami/harbor 16.4.5

### What architecture are you using?

None

### What steps will reproduce the bug?

As per [the upstream docs](https://goharbor.io/docs/2.7.0/install-config/harbor-ha-helm/):

> If you have no PVCs that can be shared across nodes, you can use external object storage to store images and charts and store the job logs in database. Set the persistence.imageChartStorage.type to the value you want to use and fill the corresponding section and set jobservice.jobLogger to database.

I have done this. `imageChartStorage.type` is set to the default, `filesystem` and `jobLogger` has been modified to `database`

I have verified that all `persistence` is set to `ReadWriteOnce`.

I am using Longhorn as default store.

However, during deployment, multiple pods are stuck on `ContainerCreating` and a `describe` shows PVC attach errors:

>   Warning  FailedAttachVolume  22m                  attachdetach-controller  Multi-Attach error for volume "pvc-bad6727c-5b62-4e30-ba0a-b3b2196ecec8" Volume is already used by pod(s) harbor-registry-748f5fc7c4-c47rm
>   Warning  FailedMount         18m (x2 over 20m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-htpasswd registry-config registry-data registry-root-certificate]: timed out waiting for the condition
>   Warning  FailedMount         2m23s (x5 over 15m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-data registry-root-certificate registry-htpasswd registry-config]: timed out waiting for the condition
>   Warning  FailedMount         7s (x3 over 9m13s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-root-certificate registry-htpasswd registry-config registry-data]: timed out waiting for the condition

### Are you using any custom parameters or values?

See diff attached

### What do you see instead?

>   Warning  FailedAttachVolume  22m                  attachdetach-controller  Multi-Attach error for volume "pvc-bad6727c-5b62-4e30-ba0a-b3b2196ecec8" Volume is already used by pod(s) harbor-registry-748f5fc7c4-c47rm
>   Warning  FailedMount         18m (x2 over 20m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-htpasswd registry-config registry-data registry-root-certificate]: timed out waiting for the condition
>   Warning  FailedMount         2m23s (x5 over 15m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-data registry-root-certificate registry-htpasswd registry-config]: timed out waiting for the condition
>   Warning  FailedMount         7s (x3 over 9m13s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[registry-data], unattached volumes=[registry-root-certificate registry-htpasswd registry-config registry-data]: timed out waiting for the condition

**Comment by udf2457** [comment]
[values-diff.txt](https://github.com/bitnami/charts/files/10950616/values-diff.txt)

**Comment by CeliaGMqrz** [comment]
Hi @udf2457 

Sorry, I need more information about your deployment. Can you upload the complete values.yaml file? In the diff, it is difficult to see all the values used. 

It seems that the error is due to multiple pods trying to connect to the same PVC at the same time. Just to make sure of this:
* Are you deploying the chart for the first time, or did you do a previous install? 
* Note that if it is configured as `filesystem`, the local storage may be deleted when the pod is destroyed or moved. It is recommended to make use of a different storage provider that supports shared PVCs. 
* Can you show the output of the following command `kubectl describe pvc <your-pvc-name>` we should identify which pod is already using the PVC.

You can try deleting the PVC with the command `kubectl delete pvc <your-pvc-name>`. This will delete the PVC and any data stored in it, so be sure to back up any important data before doing this.

**Comment by angularsen** [comment]
We're seeing a similar issue pretty much every time we upgrade the Kubernetes cluster.
Helm chart `bitnami/redis` 16.5.0.


I don't have the full error message, but the last time the redis pods were failing on multi-attach and something about the volume claim already being taken by another node, I assume the old node. This is after all nodes have successfully upgraded.

The pod had this log event:
```
Unable to attach or mount volumes: unmounted volumes=[redis-data], unattached volumes=[config redis-tmp-conf tmp kube-api-access-dddsg start-scripts health redis-data]: timed out waiting for the condition
```

It seems restarting the master pod helps, but it is also possible that just waiting fixes it.
Redis is down for about 10 minutes each upgrade, is there a way to improve this?

<details>
<summary>
Example: /api/v1/namespaces/redis/persistentvolumeclaims/redis-data-redis-master-0
</summary>

```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-master-0
  namespace: redis
  uid: 8229b0ab-b0a7-4285-af23-ec7e745faa66
  resourceVersion: '55402'
  creationTimestamp: '2021-11-17T14:37:45Z'
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
    volume.kubernetes.io/selected-node: aks-agentpool-75730839-vmss000001
  finalizers:
    - kubernetes.io/pvc-protection
  managedFields:
    - manager: kube-scheduler
      operation: Update
      apiVersion: v1
      time: '2021-11-17T14:37:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:volume.kubernetes.io/selected-node: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-11-17T14:37:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
  selfLink: /api/v1/namespaces/redis/persistentvolumeclaims/redis-data-redis-master-0
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-8229b0ab-b0a7-4285-af23-ec7e745faa66
  storageClassName: default
  volumeMode: Filesystem
```
</details>
