### ISSUE TITLE
[bitnami/postgresql-ha]: Secret Key option missing from values.yaml 

### ISSUE THREAD

**Issue by udf2457** [bitnami/charts#15463]
### Name and Version

bitnami/postgresql-ha 11.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

Secret Key options appear to be missing from `values.yaml`?

For example, if you look at `bitnami/redis/values.yaml`, you have `existingSecret` and `existingSecretPasswordKey`.

But `bitnami/postgresql-ha` only seems to have `existingSecret` with no associated "Key"?

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
