### ISSUE TITLE
[bitnami/external-dns] Unreleased external-dns (v.13.3) in bitnami charts

### ISSUE THREAD

**Issue by TheKangaroo** [bitnami/charts#15472]
### Name and Version

bitnami/external-dns:0.13.3-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

It seems like you release your external-dns based on tags in the upstream external-dns repo.
Due to some complications in the release process they pushed a new tag `v0.13.3` last week but did not release this version.
This seems to have triggert the bitnami build process and created a new bitnami helm chart and docker image for external-dns v0.13.3.

### What do you see instead?

I do not think this is intended and based on the comments in https://github.com/kubernetes-sigs/external-dns/issues/3466 (I opened an issue in their repo as well) I'm not sure if 0.13.3 is even a stable release.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the ticket! I will let the team work. In the meantime, as soon as they release the newest tag, the chart will get updated as well.
