### ISSUE TITLE
[bitnami/mysql] database backup

### ISSUE THREAD

**Issue by sfeng1996** [bitnami/charts#15508]
### Name and Version

bitaami/mysql

### What is the problem this feature will solve?

the chart of mysql can backup database at regular time

### What is the feature you are proposing to solve the problem?

it can be restored by backing up data

**Comment by javsalgar** [comment]
Hi,

Could you elaborate more on the use case you want to cover? Do you want to create a CronJob for database backups? Note that you can add any extra k8s object using the `extraDeploy` array

**Comment by sfeng1996** [comment]
> Hi,
> 
> Could you elaborate more on the use case you want to cover? Do you want to create a CronJob for database backups? Note that you can add any extra k8s object using the `extraDeploy` array

yes，extraDeploy field can cover the need, tks.

**Comment by javsalgar** [comment]
Thanks for letting us know!
