### ISSUE TITLE
[bitnami/redis-cluster] On GKE cluster rebuild IP array used in cluster.externalAccess.service.loadbalancerIP changes

### ISSUE THREAD

**Issue by rajiv36** [bitnami/charts#15518]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Accessing Redis cluster outside of GKE. 

1. Deploy redis cluster chart twice once by cluster.externalAccess.enabled=true and second time when external lbs are created we input those set of ips in cluster.externalAccess.service.loadbalancerIP section of values file. And Map those ips to dns record set in terraform scripts and use dns names in redis stackexchange client lib to connect.
2. Rebuild your GKE cluster(may be due to xyz reason)
3. On restore of GKE cluster external lb ips change as they were dynamically allocated by GKE. So we need to redeploy chart with new external lb ips in cluster.externalAccess.service.loadbalancerIP section and change ip to dns mapping in our terraform script.

### Are you using any custom parameters or values?

cluster.externalAccess.enabled=true, cluster.externalAccess.service.loadbalancerIP

### What is the expected behavior?

we should somehow remove need to changing those dynamic ips in values file and redeploy chart which got changed after GKE was rebuilt.

### What do you see instead?

On restore of GKE cluster external lb ips change as they were dynamically allocated by GKE. So we need to redeploy chart with new external lb ips in cluster.externalAccess.service.loadbalancerIP section and change ip to dns mapping in our terraform script.

### Additional information

Reserving static ips for these redis cluster external lbs can be one of the solution. But is it a antipattern to have those static ips for some GKE redis lb services? Any other possible approach?

There is possibility that devops team can rebuild GKE environment due to xyz reasons which we cant avoid.

**Comment by rafariossaa** [comment]
Hi,
  I don't thinks there is an easy solution for this. Maybe with an operator that handle the current deployment this could be done more easily.
  The pods would need to be reconfigured dynamically, and for example, if the new cluster is reusing an IP from the previous cluster that could raise more issues when making the changes.
  Do you have any suggestions on how this could be tackled ? 
  PRs are welcome and we will be glad to review and merge it.

**Comment by rajiv36** [comment]
I will discuss within team and see how this can be handled in cleaner way. But reserving static ips for these lbs are one of the options which we thought about.

**Comment by rafariossaa** [comment]
Don't hesitate to come back and share your findings.

**Comment by rajiv36** [comment]
We have got 6 static ips and mapped them to 6 dns names. Now we use stackexchange redis client to read/write data. Do we need to provide all 6 lb dns names in connect method or just one is fine? as when I just pass one dns name it start writing data to redis cluster but on providing all 6 dns names in connect method it throws timeout exception. 
Connect method: https://stackexchange.github.io/StackExchange.Redis/Configuration.html
Error:
ExceptionStack = [StackExchange.Redis.RedisTimeoutException: Timeout performing EXISTS (5000ms), inst: 0, qu: 0, qs: 0, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, last-in: 4, cur-in: 0, sync-ops: 1, async-ops: 2,

**Comment by rafariossaa** [comment]
Hi,
  I would say that stackexchange is best to answer this question. I don't know how that client works.
  In any case, have you tried the connection to each one of the 6 names individually ? Maybe one of them is not working.

**Comment by rajiv36** [comment]
all of then works for read and write when I pass them individually. Sure let me post it there. Thanks

**Comment by rafariossaa** [comment]
Thanks @rajiv36, don't hesitate to comeback and share your findings.
