### ISSUE TITLE
[bitnami/cassandra] StatefulSet not specifying apiVersion and kind in volumeClaimTemplates

### ISSUE THREAD

**Issue by Nickmman** [bitnami/charts#15526]
### Name and Version

bitnami/cassandra 10.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy ArgoCD
2. Deploy cassandra chart via ArgoCD with `persistence.enabled: true`
3. Watch that the application is constantly out of sync

### Are you using any custom parameters or values?

`persistence.enabled: true`

### What is the expected behavior?

ArgoCD will not try to constantly "fix" the application to be in sync

### What do you see instead?

ArgoCD says that the VolumeClaimTemplate is missing the `kind` and `apiVersion` and tries to add it. Since this is never addressed in the actual app (ArgoCD is set to automatically "fix" itself), the issue repeats over and over.
<img width="721" alt="diff_error" src="https://user-images.githubusercontent.com/6664031/225665231-1580adf1-6c97-4a09-9d52-7615daacf353.png">

**Comment by Nickmman** [comment]
Hi Javier,

Yes, that's exactly it. Both kind and apiVersion.

**Comment by javsalgar** [comment]
Hi,

In this case I would wait for a major version of the chart, because I'm concerned of breaking the installation to the majority of users.

**Comment by Nickmman** [comment]
Javier,

I think I may have gotten it wrong, it's the other way around. Even though those fields are missing in the chart, it seems that they get added automatically.

And this is where ArgoCD comes in, since those fields are now present in the StatefulSet but are not present in the helm chart, ArgoCD tries to remove it.

I do not think that this will be a breaking change since the fields get automatically added in, from what I understand, but I could be wrong.

**Comment by javsalgar** [comment]
Hi,

Could you try performing a test upgrade using a fork of the chart that adds these fields? Just  to ensure that no breaking occurs

**Comment by Nickmman** [comment]
Hi Javier,

I will try that in my test environment and will let you know.

**Comment by Nickmman** [comment]
@javsalgar I've just finished testing with my fork and the only impact is the rolling restart due to the "version" change. I did not see any other changes. With this, ArgoCD is finally happy and does not want to constantly update anything.
