### ISSUE TITLE
/opt/bitnami/scripts/libphpbb.sh: line 179: PHPBB_SMTP_PORT: unbound variable

### ISSUE THREAD

**Issue by prashantmishraorahi** [bitnami/charts#15520]
### Name and Version

bitnami/phpbb 3.3.10-debian-11-r7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Entered values like SMTP Host, Port, User, Password etc and Installed using the helm install command.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

It should be up and running

### What do you see instead?
```
phpbb 07:18:37.72 
phpbb 07:18:37.72 Welcome to the Bitnami phpbb container
phpbb 07:18:37.72 Subscribe to project updates by watching https://github.com/bitnami/containers
phpbb 07:18:37.73 Submit issues and feature requests at https://github.com/bitnami/containers/issues
phpbb 07:18:37.73 
phpbb 07:18:37.73 INFO  ==> ** Starting phpBB setup **
realpath: /bitnami/apache/conf: No such file or directory
phpbb 07:18:37.75 INFO  ==> Configuring the HTTP port
phpbb 07:18:37.76 INFO  ==> Configuring the HTTPS port
phpbb 07:18:37.76 INFO  ==> Configuring Apache ServerTokens directive
phpbb 07:18:37.77 INFO  ==> Configuring PHP options
phpbb 07:18:37.78 INFO  ==> Setting PHP expose_php option
phpbb 07:18:37.79 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
phpbb 07:18:37.85 INFO  ==> Ensuring phpBB directories exist
phpbb 07:18:37.85 INFO  ==> Trying to connect to the database server
phpbb 07:18:37.87 INFO  ==> Creating configuration file for installation
phpbb 07:18:38.52 INFO  ==> Configuring SMTP credentials
/opt/bitnami/scripts/libphpbb.sh: line 179: PHPBB_SMTP_PORT: unbound variable
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/phpbb#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
