### ISSUE TITLE
Failed integration between Querier & Ingester

### ISSUE THREAD

**Issue by HuyDo-95g** [bitnami/charts#15521]
### Name and Version

bitnami/charts/grafana-tempo

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy the grafana-tempo chart.
2. Set datasource in grafana that point to "http://grafana-tempo-query-frontend:3200"
3. Try to run the query in the "Expose" option of grafana.

### What is the expected behavior?

The query is executed successfully.  

### What do you see instead?

Get this: 
![image](https://user-images.githubusercontent.com/74816985/225556740-9c0d9f16-1974-4e0d-8a5a-9f6bf6c3fa91.png)

Logs from Querier:
```
level=warn ts=2023-03-15T09:46:21.999206001Z caller=logging.go:86 traceID=xxxxxx msg="GET /querier/api/traces/xxxxx?mode=ingesters (500) 67.803µs Response: \"error finding ingesters in Querier.FindTraceByID: empty ring\\n\" ws: false; Accept: application/protobuf; Accept-Encoding: gzip; User-Agent: Go-http-client/1.1; X-B3-Parentspanid: xxxxx; X-B3-Sampled: 0; X-B3-Spanid: xxxxxx; X-B3-Traceid: xxxxxx; X-Envoy-Attempt-Count: 1; X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/monitoring/sa/default;Hash=xxxxxxx;Subject=\"\";URI=spiffe://cluster.local/ns/monitoring/sa/default; X-Forwarded-Proto: http; X-Request-Id:xxxxxxxx; X-Scope-Orgid: single-tenant
```

**All components are set as "tempo-gossip-member"**

**Comment by HuyDo-95g** [comment]
Hi @fmulero 
I install the bitnami/tempo as an helm chart with all the default configuration. 

This is my datasource config for my grafana
![image](https://user-images.githubusercontent.com/74816985/227832768-3a1312d6-b09f-4ab1-abd5-1c8ab9deb120.png)

**Comment by HuyDo-95g** [comment]
@fmulero 
Also the problem here is that it could not find the ingester within the "gossip ring" 
![image](https://user-images.githubusercontent.com/74816985/227836571-eacb54f5-408b-4a9f-969f-3a171b161802.png)

**Comment by fmulero** [comment]
Something looks weird to me. Default configuration exposes the `query-frontend` in port 3200 but you are using port 3100 in your grafana datasource and it seems you are getting errors about gossip ring configuration (not a timeout or bad gateway errors). Everything points that you are not using the default configuration.

Could you share the values you used and the steps you followed to install the helm chart?

**Comment by HuyDo-95g** [comment]
@fmulero 
The tempo chart is implemented with all default configuration. My value file for tempo chart is empty. 
For the datasource, I did change to 3200 but still getting the same error. And that datasource is the configuration for my grafana chart. Not the tempo
I set up my Chart. yaml like this 
![image](https://user-images.githubusercontent.com/74816985/227914728-61d52ce9-5277-4c0b-b7fc-bba33f4a96ce.png)
Empty value file 
![image](https://user-images.githubusercontent.com/74816985/227914819-902ab624-8df1-4d6c-8da3-e132d831aa8a.png)
Then run: 
`$ helm upgrade -i <chart_name> <chart_folder_path> -n <namespace>`

**Comment by fmulero** [comment]
Sorry but I cannot reproduce your issue. Could you do a little exercise?. Forget your chart, your dependencies, values, etc and try to reproduce the problem from scratch with the information provided in this issue. I you can do it, please share information about your platform

**Comment by HuyDo-95g** [comment]
In my configuration, I also inject isto-proxy as container into very pod that deployed by helm. Could that be a reason?

**Comment by fmulero** [comment]
It could. Could you share the logs from the `query-frontend` pod? Are the pods restarting?

**Comment by HuyDo-95g** [comment]
@fmulero The pods are not restarting.

**Comment by fmulero** [comment]
To be perfectly blunt I am not sure how to continue with this issue because my crystal ball is broken and I can not guess what is happening in your side.

I have this information and I can not reproduce it:
* You are using `bitnami/grafana-tempo` as dependency, and you chart is also called `grafana-tempo` (this is not in the description of the issue).
* Using default values.
* Istio seems installed but we don't have information about the configuration.
* Everything seems working but the querier is raising this error`Querier.FindTraceByID: empty ring`

Could you run the steps described [here](https://github.com/bitnami/charts/issues/15521#issuecomment-1480990066) and share the following data?
* Error appeared in grafana.
* Logs from `query-frontend`.
* Description and logs from any pod with restarts.
* Check endpoints attached to the `gossip-ring` service.
* Istio version.
