### ISSUE TITLE
Need documentation on logging

### ISSUE THREAD

**Issue by drhetianhao** [bitnami/charts#15534]
### Name and Version

all

### What is the problem this feature will solve?

I cannot find any documentation about setting up the logging using bitnami airflow helm charts. I would like to see some documentation so I can understand and troubleshoot how logging can be managed by default or with options using this helm chart.

### What is the feature you are proposing to solve the problem?

Need brief documentation on how logging are managed and how it can be defined. I cannot find anything in the values.yaml to set up documentation

**Comment by carrodher** [comment]
There is a section in the README with the different parameters used to configure and expose metrics at https://github.com/bitnami/charts/tree/main/bitnami/airflow#airflow-metrics-parameters. Is that what you are looking for?

**Comment by drhetianhao** [comment]
> There is a section in the README with the different parameters used to configure and expose metrics at https://github.com/bitnami/charts/tree/main/bitnami/airflow#airflow-metrics-parameters. Is that what you are looking for?

Hi, thanks for your reply. I was looking for the configs/values for setting up the logs for DAGs. e.g. use of PV and PVC or remote logging. 
I use the almost default setting in the microk8s K8s but got this following error msg:

*** Failed to fetch log file from worker. [Errno -3] Temporary failure in name resolution

**Comment by corico44** [comment]
Hello @drhetianhao,

As @carrodher mentions, there is a section in the README with the different parameters used to configure and expose metrics at https://github.com/bitnami/charts/tree/main/bitnami/airflow#airflow-metrics-parameters. 
There is no other specific configuration to view the logs of DAGs. But, you can always check the logs of the different kubernetes components that are created when you install the chart.
Also, have you tried checking the logs in the airflow UI itself?

**Comment by drhetianhao** [comment]
Hi @carrodher, I have checked that link but that is not for showing the logs of running the DAGs. The current documentation does not mention if the default values can display the DAG logs into the web UI or not (the default behaviour).
I think the default views do not enable the log files to be persistent from the scheduler/worker nodes with the web app.
I have managed to view the DAG logs by creating PV and PVC using the extra mount and extra volume into the global values.

**Comment by corico44** [comment]
@drhetianhao Could you please indicate how you managed to finally get the logs in case another user has the same problem in the future, please?

**Comment by drhetianhao** [comment]
"by creating PV and PVC using the extra mount and extra volume into the global values"

**Comment by kardamk** [comment]
> "by creating PV and PVC using the extra mount and extra volume into the global values"

Hello @drhetianhao ,
Could you provide a snapshot of the values.yaml containing the change for adding global volumes and volume mounts?
Thanks!

**Comment by pawgajda-drs** [comment]
> > "by creating PV and PVC using the extra mount and extra volume into the global values"
> 
> Hello [@drhetianhao](https://github.com/drhetianhao) , Could you provide a snapshot of the values.yaml containing the change for adding global volumes and volume mounts? Thanks!

There you go:

```extraEnvVars:
  - name: "AIRFLOW__LOGGING__BASE_LOG_FOLDER"
    value: "/opt/bitnami/airflow/shared-logs"

extraVolumeMounts:
  - name: airflow-logs
    mountPath: /opt/bitnami/airflow/shared-logs
    readOnly: false

extraVolumes:
  - name: airflow-logs
    persistentVolumeClaim:
      claimName: airflow-logs
```

These are global settings. I use `KubernetesExecutor` and this setup works. 
Just make sure the StorageClass of your volume supports `ReadWriteMany`.  In my case I use `azurefile`.
