### ISSUE TITLE
[bitnami/kafka] kerberos/gssapi support for bitnami kafka

### ISSUE THREAD

**Issue by sudhevan** [bitnami/charts#15536]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Hi Team,
Is there a way to enable support kerberos authentication with bitnami kafka? using SASL_PLAINTEXT or SASL_SSL options?
connecting to an external KDC server.

Thanks

### What is the feature you are proposing to solve the problem?

Allows clients to authenticate to broker with  GSSAPI using a keytab file.

**Comment by javsalgar** [comment]
Hi,

Could you let us know the upstream settings to configure kerberos? Note that you can use the KAFKA_CFG_* environment variables to map any kafka configuration field.

**Comment by maron546** [comment]
Hi.
Any news about this issue? What is the correct configuration in order to make it works?
