### ISSUE TITLE
[bitnami/elasticsearch] "headless" service is not headless

### ISSUE THREAD

**Issue by remram44** [bitnami/charts#15533]
### Name and Version

bitnami/elasticsearch 19.5.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Look at https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/master/svc-headless.yaml
2. Notice this service is called "headless"
3. Read about [headless services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services):
> you can create what are termed "headless" Services, by explicitly specifying `"None"` for the cluster IP (`.spec.clusterIP`).
4. Notice that your headless service is not headless

### What is the expected behavior?

Don't call it "headless" or make it headless

### What do you see instead?

Service is not headless, it gets a ClusterIP. This probably affects service discovery between nodes.

### Additional information

`clusterIP: "None"` was there but was removed by @mFranz82 in [`d3277448`](https://github.com/bitnami/charts/commit/d3277448ce0159b545a65de3cd1e04acf9f144d6#diff-000bd0a6b55ce7702f13769a68dc15a35ebde3d8467bf174feb867ff6e3aae62)

**Comment by rafariossaa** [comment]
Hi,
  I just merged the changes, could you give it a try ?
