### ISSUE TITLE
[bitnami/mariadb-galera] Steady increase in memory usage

### ISSUE THREAD

**Issue by renemadsen** [bitnami/charts#15532]
### Name and Version

bitnami/mariadb-galera 7.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install my-release my-repo/mariadb-galera

Spawning a normal 3 node cluster using defaults and loading 735 databases of aprox 1Mb each and 50 applications connecting to it, the memory usage keeps increasing and never drops.

### What is the expected behavior?

Steady usage of memory no major increase in a short time and not dropping down again.

### What do you see instead?

Starts out with memory usage of 1gb and then increases until the nodes limit is reached of 8gb and the pod is restarted.

### Additional information

There are no long running queries or heavy inserts/updates.

Any suggestions as to which variables we should look at to trace this down?

**Comment by javsalgar** [comment]
Hi,

Do you have a sample dataset we can use to reproduce the issue?

**Comment by renemadsen** [comment]
> Hi,
> 
> Do you have a sample dataset we can use to reproduce the issue?

Since it's containing a lot of GDPR data it's not that easy to create a sample data set. But I'll se how we can do that.
