### ISSUE TITLE
[bitnami/parse] Add support of additional env variables for advanced parse server setup.

### ISSUE THREAD

**Issue by alexparfianovich** [bitnami/charts#1554]
Parse server has a lot of possible configuration options https://github.com/parse-community/parse-server/blob/master/src/Options/Definitions.js
Please add support of passing **extraVars** to [bitnami/parse] helm chart (probably like this one https://github.com/helm/charts/blob/master/stable/neo4j/values.yaml#L75)

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. We will update this ticket when we have it.

**Comment by javsalgar** [comment]
I created this PR https://github.com/helm/charts/pull/18549

**Comment by alemorcuq** [comment]
The PR was merged, so I'm closing this.
