### ISSUE TITLE
[bitnami/redis] Sentinel master is unable to store NodePort address and keeps local address of the service/pod

### ISSUE THREAD

**Issue by sushil-clearsense** [bitnami/charts#15547]
### Name and Version

bitnami/redis 7.0.9

### What architecture are you using?

None

### What steps will reproduce the bug?

I am deploying a redis master-slave cluster in kubernetes. The cluster comes up correctly and I can access it through the cluster. However, the sentinel is storing the cluster IP of the service as master IP instead of the NodePort IP.

Therefore, when I try to connect to the redis app from an external app, the app is unable to resolve the internal IP.

How can make the sentinel store the Node IP address instead of the internal IP address of the pod/service
![image](https://user-images.githubusercontent.com/93955508/226056841-9aa9a940-d5d7-4b52-87dd-97b66c1e18fc.png)

![image](https://user-images.githubusercontent.com/93955508/226056924-2786ba2b-0b15-4724-8482-3eab1b0e5747.png)

### Are you using any custom parameters or values?

```
image:
  tag: 7.0.9-debian-11-r1
  pullPolicy: Always
  debug: true

architecture: replication

commonConfiguration: |-
  appendonly no
  save ""
  dir /bitnami/redis/data

master:
  service:
    type: NodePort
  selector:
    instancetype: redis-master
  persistence:
    enabled: true
    existingClaim: redis-data-redis-master-0-pvc

replica:
  replicaCount: 3
  service:
    type: NodePort
  persistence:
    enabled: true
    existingClaim: redis-data-redis-replica-0-pvc
  podAntiAffinityPreset: soft

sentinel:
  enabled: true
  image:
    tag: 7.0.9-debian-11-r0
    pullPolicy: Always
  service:
    type: NodePort
    #ports where redis and sentinel will be accessible
    nodePorts:
      redis: 30201
      sentinel: 30301
  configuration: |-
    sentinel announce-hostnames no
```

### What is the expected behavior?

There should be some configuration or way to access this redis cluster from an external app

### What do you see instead?

Unable to access this redis cluster from outside cluster as it is storing internal IP address

**Comment by sushil-clearsense** [comment]
Hi @Mauraza I am not using these environment variables. As the master node can change during the course, I cannot hardcode the host right? Can you please elaborate a bit more

**Comment by Mauraza** [comment]
Hi @sushil-clearsense,

You can use the service of the master node.
