### ISSUE TITLE
[bitnami/mariadb] Setting primary.persistence.labels breaks the chart

### ISSUE THREAD

**Issue by boedy** [bitnami/charts#15542]
### Name and Version

bitnami/mariadb:11.5.3

### What architecture are you using?

None

### What steps will reproduce the bug?

When setting primary.persistence.labels the spec is invalid. Then labels will be defined twice

### What is the expected behavior?

Adding the correct labels and generating valid k8s manifest

### What do you see instead?

The volumeClaimTemplates.metadata spec will contain two label keys

### Additional information

Issue at hand.

https://github.com/bitnami/charts/blob/30039195b54905be12348e950a63720fc5b318d3/bitnami/mariadb/templates/primary/statefulset.yaml#L377

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! Indeed, it should be like this

```
        labels: {{ include "common.labels.matchLabels" . | nindent 10 }}
          app.kubernetes.io/component: primary
        {{- if .Values.primary.persistence.labels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.primary.persistence.labels "context" $) | nindent 10 }}
        {{- end }}
```

As you reported it, would you like to submit a PR with the fix?
