### ISSUE TITLE
mysql Server upgrade from '80032' to '80032' takes 5 minutes

### ISSUE THREAD

**Issue by pbolle** [bitnami/charts#15550]
### Name and Version

docker.io/bitnami/mysql:8.0.32-debian-11-r0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Installing the mysql helm chart.
2. Stop debug in helm chart
3. Importing about 3 GB of data into the database
4. Kill mysql pod in kubernetes
5. look into the log of the restarted mysql pod
6. The following entry appears in the log "Server upgrade from '80032' to '80032' started"
7. after 5 minutes the following entry appears in the log "Server upgrade from '80032' to '80032' completed"
8. after 5 minutes the database is available again

This behaviour occurs every time the Pod is restarted.

### What is the expected behavior?

The expectation would be that a restart of the mysql pod does not trigger a mysql_upgrade if it is not necessary. Since in this case nothing has changed and it is obvious from the log that nothing has changed, I would expect that the application that needs the data is not down for 5 minutes.

### What do you see instead?

Applications that do not work for 5 minutes and wait for the database. Since Kubernetes often restarts a pod, this behaviour is dangerous for the stability of the application.

**Comment by marcosbc** [comment]
Hi @pbolle, this issue seems related to this line: https://github.com/bitnami/containers/blob/main/bitnami/mysql/8.0/debian-11/rootfs/opt/bitnami/scripts/libmysql.sh#L770

According to the [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/upgrading-what-is-upgraded.html):

> With [`--upgrade=FORCE`](https://dev.mysql.com/doc/refman/8.0/en/server-options.html#option_mysqld_upgrade), the server upgrades the data dictionary, the Performance Schema, and the `INFORMATION_SCHEMA`, if necessary (step 1), and forces an upgrade of everything else (step 2). **Expect server startup to take longer** with this option because the server checks all objects in all schemas.

In the past, we removed some usage for `--upgrade=FORCE` (see https://github.com/bitnami/containers/issues/22193) but it seems like we forgot to remove it from the other place as well.

Would you like to contribute a fix with the removal of the flag?

**Comment by pbolle** [comment]
Thank you for your detailed description.
I found a workaround that worked for me. I now use the bitnami mariadb chart. There was no delay when restarting.

**Comment by vholer** [comment]
As of 02/2024, this is still an issue with latest `bitnami/mysql` chart (v9.19.1).

**Comment by vholer** [comment]
I have used @pbolle's original description (thank you) and copied to a new fresh ticket #26559. Hopefully it'll get more attention.
