### ISSUE TITLE
[fluentd]: Only run aggregator part

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#1557]
**Which chart**:
fluentd

**Description**

Be able to run aggregator only.
Often folks use fluent-bit on the nodes, and hence only want to run fluentd as aggregator.

**Describe the results you received:**

Forwarder daemonset will be created - we don't want that.

**Describe the results you expected:**

Only aggregator sts.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by alemorcuq** [comment]
Hi, @davidkarlsen! I can see why an user would want this and I agree with you. I will make a PR supporting it.

**Comment by alemorcuq** [comment]
We just merged #1558, implementing this feature. Let us know if this works for you.

**Comment by davidkarlsen** [comment]
Thanks - I will!

**Comment by davidkarlsen** [comment]
Works like a charm!
