### ISSUE TITLE
Support for Nodes with ML role using Bitnami's Elastic Search Helm

### ISSUE THREAD

**Issue by udaygreddy** [bitnami/charts#15628]
### Name and Version

bitnami/charts

### What is the problem this feature will solve?

Bitnami Elastic Helm does not support creation of ML nodes. This is a feature request to support it!

### What is the feature you are proposing to solve the problem?

Support creation of ML nodes using Bitnami's Elastic Helm Chart

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by NanzhongHE** [comment]
Hi, is there any news about this issue? We have the same problem since we use the Bitnami elasticsearch helm chart. We would be grateful if we could have the ML role using the Bitnami image.
