### ISSUE TITLE
Ability to change namespace the chart uses from 'default'

### ISSUE THREAD

**Issue by se7enack** [bitnami/charts#15629]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

I would like the ability to change the namespace from default.

### What is the feature you are proposing to solve the problem?

The environment I work in doesn't allow access to 'default' ns. There should be an override that allows someone to change the namespace of the chart.

### What alternatives have you considered?

Not using this chart and manually deploying redis seems to be the only workaround.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by simonfelding** [comment]
set the namespace with helm, that works for all charts. use -n {namespace} to set namespace, --create-namespace will make helm create it if it doesn't exist.
