### ISSUE TITLE
[bitnami/argo-cd] multiple sources application is not working

### ISSUE THREAD

**Issue by hummelm** [bitnami/charts#15637]
### Name and Version

bitnami/argocd 4.4.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy argocd
2. try to create an application which is using multi-sources: ex: https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/ 
3. You cannot validate it

If you try to create the resource directly from kubectl, you will get this error:
**unknown field "spec.sources"**

I think that bitnami need to update the CRDS deployed with the chart because the one currently provided are from the version 2.3 I think, and multe sources application has been implemented in argocd 2.6.

### What is the expected behavior?

Application is created

### What do you see instead?

nothing the application is not created

### Additional information

If you try to create the resource directly from kubectl, you will get this error:
**unknown field "spec.sources"**

I think that bitnami need to update the CRDS deployed with the chart because the one currently provided are from the version 2.3.1:
https://github.com/bitnami/charts/blob/main/bitnami/argo-cd/crds/application.yaml#L1 
Multiple sources application has been implemented in argocd 2.6.

I think other CRD also need to be updated because applicationset is also not working.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Would you like to submit a PR updating the CRDs from upstream?

**Comment by Nello-Angelo** [comment]
@hummelm it works in the latest chart version try to update may be that help
