### ISSUE TITLE
External access port as a single port number instead of a one up counter

### ISSUE THREAD

**Issue by burkempers** [bitnami/charts#15654]
### Name and Version

bitnami/kafka:21.3.0

### What is the problem this feature will solve?

Istio ingress can do SNI routing for the kafka external listener.  With SNI routing the port can be the same for all of the external advertised listeners.  
To use this setup I set the `externalAccess.service.domain` to `kafka-${ID}.my.domain`, which allows the hostname to be different for each advertised listener.  https://github.com/bitnami/charts/blob/8f0f5db9ee3a0158daf3558a93688a59c7452181/bitnami/kafka/templates/scripts-configmap.yaml#L141

Then I modified the scripts-configmap to be a hard coded single port number of 30094. https://github.com/bitnami/charts/blob/8f0f5db9ee3a0158daf3558a93688a59c7452181/bitnami/kafka/templates/scripts-configmap.yaml#L142

### What is the feature you are proposing to solve the problem?

Add some logic around line 142 of the scripts configmap to allow setting a single external port value that will be the same for all kafka pods.  example:
```
{{- if .Values.externalAccess.service.ingressPort }}
export EXTERNAL_ACCESS_PORT="{{ .Values.externalAccess..service.ingressPort }}"
{{- else }}
export EXTERNAL_ACCESS_PORT="$((ID + {{ .Values.externalAccess.service.ports.external }}))"
{{- end }}
```

### What alternatives have you considered?

I am trying to remove extra ports that are allowed into my kubernetes cluster.  Using SNI routing is the only way I can accomplish removing extra ports, so I don't see another way of doing this task.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
