### ISSUE TITLE
[bitnami/keycloak] Error using authorization after 13.1.3 (java 17)

### ISSUE THREAD

**Issue by JoniJnm** [bitnami/charts#15659]
### Name and Version

bitnami/keycloak 13.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a new client with Authorization
2. This will create a default js policy 
![default-policy](https://user-images.githubusercontent.com/577282/226740753-28936cea-1d52-465a-b972-642a99b168cb.png)

After using the authorization a Java exception appears in the pod.

You can just use the Evaluate tab against the default resource: `urn:testing:resources:default` and watch the logs.

Using an HTTP request to check the authorization keycloak returns a 500 error

### What is the expected behavior?

No errors

### What do you see instead?

Using the 13.1.1 versions in the pod I see:
```
Warning: Nashorn engine is planned to be removed from a future JDK release
```

Using 13.1.3 in the pod I see:
```
java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='2e044158-e705-433f-a0b8-89e1339a078b', name='Default Policy', type='text/javascript', code='// by default, grants any permission associated with this policy
$evaluation.grant();
', description='A policy that grants access only for users within this realm'}
	at org.keycloak.scripting.DefaultScriptingProvider.getPreparedScriptEngine(DefaultScriptingProvider.java:114)
```

### Additional information

The problem appears after updating java 11 to java 17 in the container image: https://github.com/bitnami/containers/pull/25331#issuecomment-1478527560

More info about authenticator + javascript: https://www.keycloak.org/docs/latest/server_development/#deploy-the-script-engine-on-java-15-and-later

The official container has the same problem: https://github.com/keycloak/keycloak/issues/17671

The code where a default JS policy is created (so a javascript engine is needed): https://github.com/keycloak/keycloak/blob/8bc5273792e3f843d125510aa62eee353279b1ea/services/src/main/java/org/keycloak/authorization/admin/ResourceServerService.java#L178-L198

**Comment by corico44** [comment]
Hello @JoniJnm,

It seems that the error was fixed:
- https://github.com/bitnami/containers/pull/25331#issuecomment-1478527560
- https://github.com/bitnami/containers/issues/28129

Could you confirm that now the error no longer appears, please?

**Comment by valerii15298** [comment]
@corico44 I have the same problem and it does not seem to be fixed.
```
2023-04-20 17:45:24 2023-04-20 14:45:24,854 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='0a06c654-3871-4ee0-ba94-71091143f01b', name='ggg-script', type='text/javascript', code=
```

Version: `docker.io/bitnami/keycloak:21`

**Comment by JoniJnm** [comment]
Yes, tested with chart 14.2.0 and it's the same error:

```
Caused by: java.lang.IllegalStateException: Could not find ScriptEngine for script: Script{id='null', realmId='bd0467fe-18a9-4917-92e0-de64110efe9d', name='Default Policy', type='text/javascript', code='// by default, grants any permission associated with this policy
$evaluation.grant();
', description='A policy that grants access only for users within this realm'}
```


The commit https://github.com/bitnami/containers/commit/50aa7cb50329b9631ffcacd3b42fa111eaf32ef0 is not merged in the container. So, the [keycloak image](https://github.com/bitnami/containers/blob/main/bitnami/keycloak/21/debian-11/Dockerfile) still doesn't have nashorn. The official image [added it](https://github.com/keycloak/keycloak/pull/19507).

**Comment by corico44** [comment]
@JoniJnm Thank you so much for reporting this issue. I understand that the error would be fixed by applying [these changes](https://github.com/bitnami/containers/commit/50aa7cb50329b9631ffcacd3b42fa111eaf32ef0). Would you be open to contributing this change via a PR? We'd be glad to review and help with the release.

**Comment by JoniJnm** [comment]
Sorry but I'm not a Java developer. I only know with this commit my case works. But I don't know if it could have problems.

**Comment by vruum** [comment]
hey @JoniJnm , not sure exactly how I can help, but I created a new pull request, with the changes referenced above. Let's see if that fixes it.

**Comment by corico44** [comment]
Thank you @vruum, we'll review it!

**Comment by corico44** [comment]
Hello @vruum,

As @carrodher commented in #31812, it would be more recommendable that you include those changes in your local repo and build the container image from there with all the required changes to work for your use case, but not adding those changes by default for all the users.
Therefore, I proceed to close the ticket. If any other questions arise, feel free to open it again!
