### ISSUE TITLE
[bitnami/redmine]

### ISSUE THREAD

**Issue by dannyyy** [bitnami/charts#1566]
**Which chart**:

bitnami/redmine --version 12.2.12

**Description**

While starting up the pods, the containers fall into error state because of the following error:
`Error executing 'postInstallation': groupadd: failure while writing changes to /etc/gshadow`

**Steps to reproduce the issue:**

1. `helm3 install redmine bitnami/redmine --version=12.2.12 -f values.yaml`
2. Pod startup will fail

```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
Error executing 'postInstallation': groupadd: failure while writing changes to /etc/gshadow
```

Fails on default kubernetes cluster without special pod security policies

A running pod, without changing pod security policies

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.0.0-rc.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi @dannyyy ,
  I am running the chart without problems using the values.yml provided.

  Could you clean the volumes and run it again ? 
  Could  you provide the values.yml you are using?
