### ISSUE TITLE
[bitnami/memcached] to handle persistence.existingClaim

### ISSUE THREAD

**Issue by Spritekin** [bitnami/charts#15680]
### Name and Version

bitnami/memcached 6.3.13

### What is the problem this feature will solve?

Other charts like postgresql, mysql or redis allow setting a provisioned disk into the helm chart, however the memcached chart won't allow it.
I have disks provisioned and I just need to feed them to the chart same as with any the other charts mentioned above.

### What is the feature you are proposing to solve the problem?

Follow the same pattern as Redis and allow setting an existing claim as the data volume.

### What alternatives have you considered?

Search for a memcached chart that allows using a existing claim

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward this to the team but I cannot guarantee an ETA. If you want to speed up the process, would you like submit a PR replicating the existingClaim behaviour of the other charts?
