### ISSUE TITLE
[bitnami/harbor] HA setup of Harbor

### ISSUE THREAD

**Issue by rgaduput** [bitnami/charts#15708]
### Name and Version

bitnami/harbor 2.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi,
We are using Harbor on BareMetal clusters as a registry for container images. To have Production ready setup for Harbor I am trying to understand how to set up the High Availability for Harbor components. If there is some doc already can someone point me to it? If not any idea how to set up HA mode?

Thanks.

**Comment by CeliaGMqrz** [comment]
Hi @rgaduput,

Thanks for your comments!

Sorry, we don't have an official guide for it. However, you can increase the number of replicas in the harbor chart. In the `values.yaml` file you can edit the `replicaCount` parameter and set a number greater than 1 to enable node replication. 

To configure an external URL [see here](https://github.com/bitnami/charts/tree/main/bitnami/harbor#configure-the-external-url).

Note that you need to enable persistence and it is recommended to use an external database for this.

You can refer to:

* [Harbor HA Helm](https://goharbor.io/docs/1.10/install-config/harbor-ha-helm/) 
* [HA Configuration](https://goharbor.io/docs/1.10/install-config/harbor-ha-helm/#configuration)
* [Open a direct request](https://github.com/goharbor/harbor/issues) 

Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
