### ISSUE TITLE
[bitnami/sonarqube] Configuring encryption doesn't work.

### ISSUE THREAD

**Issue by ristex1** [bitnami/charts#15717]
### Name and Version

bitnami/sonarqube 2.1.1 and 2.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

https://docs.sonarqube.org/9.9/instance-administration/security/#settings-encryption

I'm deploying sonarqube via the abovementioned chart and trying to set the encryption key so I can encrypt the settings strings etc.

A deployed chart in k8s

SONARQUBE_EXTRA_PROPERTIES : sonar.secretKeyPath=/mnt/sonarqube-secretkeyfile

`sonarqube@sonarqube-xxxx-xxxxxx:/mnt/sonarqube-secretkeyfile$ ls
sonar-secret.txt`

`sonarqube@sonarqube-xxxxx-xxxxxx:/mnt/sonarqube-secretkeyfile$ cat sonar-secret.txt 
n+xxxxxxxxxxxx+xxxxxxxxxxasd=sonarqube@sonarqube-xxxxxx-xxxx:/mnt/sonarqube-secretkeyfile$`

### Are you using any custom parameters or values?

extraProperties:
  - sonar.secretKeyPath=/mnt/sonarqube-properties-secrets

Of course the extra volume and volume mounts.

### What is the expected behavior?

The expect behaviour is that sonarqube would pick up the value from the file and that I can proceed with what the guide explains to generate encrypted values so I can proceed with my DevOps connections as I don't want to store the accesskeys as plain text.

When logging in /admin/settings/encryption i'd see that encryption field

### What do you see instead?

Instead I see the option to generate a new key and the guide explaining that i should create the said file in said location and with the value of that key :)

### Additional information

I can't find anything related in the logs from the container, nor anything stored in the sonar logs either.

**Comment by javsalgar** [comment]
Hi,

Could you enter the container and check that the configuration file contains the entry you added in SONARQUBE_EXTRA_PROPERTIES?

**Comment by javsalgar** [comment]
Hi,

The thing is, if that configuration is set correcty in their properties, then it is not clear to me if this is an issue with the Bitnami packaging or in Sonarqube itself. Did you check with the upstream developers?

**Comment by ristex1** [comment]
Haven't yet, I guess I should open a ticket there, I didn't know if there's something extra that might've been configured or touched from the bitnami side regarding this setting. I guess I should open an issue there.

**Comment by ristex1** [comment]
Solved the issue by providing the name of the file as well...
