### ISSUE TITLE
[bitnami/redis] preExecCmds is string, not array

### ISSUE THREAD

**Issue by kor3k** [bitnami/charts#15728]
### Name and Version

bitnami/redis:17.9.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

documentation states `preExecCmds` is an array `[]`, while in fact it's handled as a string

`redis.master.preExecCmds: ['sleep 10']`

produces

> ./charts/redis/templates/scripts-configmap.yaml" at <4>: wrong type for value; expected string; got []interface {}

but this works

`redis.master.preExecCmds: 'sleep 10'` 

### What do you see instead?

error

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Would you like to submit a PR fixing the documentation?
