### ISSUE TITLE
[bitnami/redis] sentinel enters tilt mode and dies

### ISSUE THREAD

**Issue by rsidhaarth** [bitnami/charts#15738]
### Name and Version

bitnami/redis:6.2.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are running the redis helm chart - https://bitnami.com/stack/redis/helm with the following changes

### Are you using any custom parameters or values?

auth.enabled: false
auth.sentinel: false
sentinel.enabled: true

### What is the expected behavior?

It should not crash

### What do you see instead?

redis sentinel keeps crashing by entering the tilt mode

![image](https://user-images.githubusercontent.com/16856248/227857755-d176d335-1323-4152-9101-bce70ce74916.png)

### Additional information

We have not even started using it, just deployed it and after 12 hours  it started showing this issue

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the Kubernetes platform you are using to run the chart?

**Comment by marcosbc** [comment]
Hi @rsidhaarth, we have seen this issue in the past and the way to resolve it has been to disable the `useHostnames` option, see https://github.com/bitnami/charts/issues/9689#issuecomment-1408547888 for more info.
