### ISSUE TITLE
[bitnami/redis]  Setting downAfterMilliseconds with post-install 

### ISSUE THREAD

**Issue by vladsf** [bitnami/charts#15733]
### Name and Version

bitnami/redis 17.9.0

### What is the problem this feature will solve?

Hi,

Setting downAfterMilliseconds 10000 and below causes the cluster to be installed with Helm incorrectly. Sentinels starts faster then the all three nodes and consider master to be failing. 

Is there way to change downAfterMilliseconds automatically later on all sentinels once all master and replicas are deployed and working?

### What is the feature you are proposing to solve the problem?

downAfterMilliseconds has no affect until a Sentinel runs for 60 sec at least or other configurable time

### What alternatives have you considered?

Some post-install script to change downAfterMilliseconds after "helm install"

**Comment by vladsf** [comment]
Thank you for the tip I will try to increase initialDelaySeconds to 60.

**Comment by Mauraza** [comment]
Hi @vladsf,

Does initialDelaySeconds augmentation work?

**Comment by vladsf** [comment]
@Mauraza thank you, it worked!

**Comment by Mauraza** [comment]
Hi @vladsf,

I'm glad that works. I'm closing this out now, please don't hesitate to write us back if you have any other issues.
