### ISSUE TITLE
[bitnami/harbor] x509: certificate is valid for localhost, rancher.cattle-system, not core.harbor.domain

### ISSUE THREAD

**Issue by nishit93-hub** [bitnami/charts#15735]
### Name and Version

bitnami/harbor

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi, 

I set up the harbor using Nodeport. I can access the panel using the URL https://core.harbor.domain:31238/. However, when I try to log in from the command via the command `docker login core.harbor.domain:31238`, I get the following error

`Error response from daemon: Get "https://core.harbor.domain:31238/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

I then added an insecure registry under file `/etc/default/docker` i.e. `export DOCKER_OPTS='--insecure-registry core.harbor.domain:31238'` But it didn't work.

Moreover, I also downloaded the CA.crt from the Harbor registry and copyied to `/etc/docker/certs.d/core.harbor.domain:31238/`
after that, I am getting the following error

`Error response from daemon: Get "https://core.harbor.domain:31238/v2/": dial tcp 172.17.0.2:31238: connect: no route to host`

Please advise how I can resolve this and login to the docker registry from the command line.

### What do you see instead?

Error response from daemon: Get "https://core.harbor.domain:31238/v2/": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "harbor-ca")

**Comment by javsalgar** [comment]
Hi,

Could you share the exact values you changed from the default ones to configure the deployment?

**Comment by nishit93-hub** [comment]
Hi,

Here is the updated value file.

[harbor.txt](https://github.com/bitnami/charts/files/11077467/harbor.txt)

**Comment by nishit93-hub** [comment]
Hi,

Did you get a chance to look into the attached harbor.txt file?

**Comment by Mauraza** [comment]
Hi @nishit93-hub,

Did you try to connect with the ip and the port instead the hostname?

**Comment by nishit93-hub** [comment]
Hi @Mauraza ,

Yes, I am using the IP and port to access the harbor panel. I can access the panel but I cannot log in from CLI using IP and port.

**Comment by Mauraza** [comment]
Hi @nishit93-hub,

Did you try `docker login 172.17.0.2:31238`?  if that goes wrong you can set the ping output `ping 172.17.0.2:31238`
