### ISSUE TITLE
[bitnami/minio] Creating a bucket on deletion of bucket with name doesn't exist

### ISSUE THREAD

**Issue by EwgeniWolowik** [bitnami/charts#15743]
### Name and Version

bitnami/minio latest

### What architecture are you using?

Linux SuSe / Gitlab Linux runner + bitnami docker container

### What steps will reproduce the bug?

1. Pull newest bitnami/minio image
2. Start empty container (no buckets, nothing)
3. Send DELETE bucket REST request (via Postman) with bucket name doesn't exist
4. Receive correct error message 
    \<Code>NoSuchBucket\</Code>
    \<Message>The specified bucket does not exist\</Message>
    \<BucketName>abc42\</BucketName>
5. Check container: bucket with given name ('abc42') exists

### What is the expected behavior?

Only correct error message, no creating a bucket on deleting it

### What do you see instead?

On deletion of bucket with name doesn't exist bucket will be created with given name

### Additional information

Happens only on running docker container on Linux, on Windows everything Ok

**Comment by javsalgar** [comment]
Hi,

It seems to me that the issue you are reporting has to do with minio itself, not the Bitnami packaging of minio. Did you check with the upstream developers?

**Comment by EwgeniWolowik** [comment]
Hi.
With container created on (quay.io/)minio/minio I have no such problem...

**Comment by javsalgar** [comment]
Could you share the exact commands to reproduce? For example the curl commands so it is more straightforward

**Comment by EwgeniWolowik** [comment]
Sure.

- Start server
`docker run --name bitnami_server -p 9000:9000 -p 9001:9001 -e "MINIO_ROOT_USER=minioadmin" -e "MINIO_ROOT_PASSWORD=minioadmin" bitnami/minio:latest`

- List buckets by REST via Postman
`curl --location --request GET 'http://bitnami_server:9000/' --header 'X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' --header 'X-Amz-Date: 20230329T081305Z' --header 'Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230329/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d5b55300c9f9a6d1799b65a7e406c35c513df7ab2a76ff0f1dc6b6cf3293cbed'`

- Answer
> \<?xml version="1.0" encoding="UTF-8"?>
> \<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> &emsp;\<Owner>
> &emsp;&emsp;\<ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4\</ID>
> &emsp;&emsp;\<DisplayName>minio\</DisplayName>
> &emsp;\</Owner>
> &emsp;\<Buckets>\</Buckets>
> \</ListAllMyBucketsResult>

- Delete bucket with name doesn't exist
`curl --location --request DELETE 'http://bitnami_server:9000/abc42' --header 'X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' --header 'X-Amz-Date: 20230329T081238Z' --header 'Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230329/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=097c7083bf28df6b4a29ae642e6f191165064a7de6c38eedc7f3e709149c6ddc'`

- Answer
> \<?xml version="1.0" encoding="UTF-8"?>
> \<Error>
> &emsp;\<Code>NoSuchBucket\</Code>
> &emsp;\<Message>The specified bucket does not exist\</Message>
> &emsp;\<BucketName>abc42\</BucketName>
> &emsp;\<Resource>/abc42\</Resource>
> &emsp;\<RequestId>1750D5A88A9F9DA6\</RequestId>
> &emsp;\<HostId>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\</HostId>
> \</Error>

- List buckets again
`curl --location --request GET 'http://bitnami_server:9000/' --header 'X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' --header 'X-Amz-Date: 20230329T081305Z' --header 'Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20230329/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d5b55300c9f9a6d1799b65a7e406c35c513df7ab2a76ff0f1dc6b6cf3293cbed'`

- Answer
> \<?xml version="1.0" encoding="UTF-8"?>
> \<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> &emsp;\<Owner>
> &emsp;&emsp;\<ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4\</ID>
> &emsp;&emsp;\<DisplayName>minio\</DisplayName>
> &emsp;\</Owner>
> &emsp;\<Buckets>
> &emsp;&emsp;\<Bucket>
> &emsp;&emsp;&emsp;\<Name>abc42\</Name>
> &emsp;&emsp;&emsp;\<CreationDate>0001-01-01T00:00:00.000Z\</CreationDate>
> &emsp;&emsp;\</Bucket>
> &emsp;\</Buckets>
> \</ListAllMyBucketsResult>

- Delete bucket again works without error

**Comment by EwgeniWolowik** [comment]
I have to apologize!!!
I've tested on an minio version from 2 weeks ago and latest bitnami. Now I've pulled latest minio too and found the same error. So it must be minio itself.
Please excuse me again!
