### ISSUE TITLE
[bitnami/mongodb] pods is forbidden: User \"system:serviceaccount:dba-b2-etude:mongodbsa\" cannot list resource \"pods\" in API group \"\" at the cluster scope"

### ISSUE THREAD

**Issue by BK-STAR77** [bitnami/charts#15749]
### Name and Version

bitnami/mongodb 12.1.31

### What architecture are you using?

None

### What steps will reproduce the bug?

ENV: 1. Openshift 4.10.46
![Capture d’écran 2023-03-27 à 16 49 46](https://user-images.githubusercontent.com/26568176/227976770-d624f7bb-8bb4-4904-a324-4225d336d051.png)
![Capture d’écran 2023-03-27 à 16 50 20](https://user-images.githubusercontent.com/26568176/227976809-8a0ce95b-0f61-44a7-a0cc-3c2ffe57c1dd.png)

### Are you using any custom parameters or values?
```
helm upgrade --install mongo-db -f values.yaml bitnami/mongodb --version 12.1.31  
```
### What is the expected behavior?

Hello,

I try to deploy the MongoDB chart helm but we have an issue with the serviceaccount with the default values in the chart.

For my test, I put in a cluster admin role but with no success.

thank you in advance for your help

### What do you see instead?

![Capture d’écran 2023-03-27 à 16 49 46](https://user-images.githubusercontent.com/26568176/227977990-f8db47e8-c621-4a50-ac62-260a80d99951.png)

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by BK-STAR77** [comment]
OK I resolve my issue. I created a ClusterRole but I don't understand why it need an elevated role for just labeled a pod inside the namespace where the mongo is deployed.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MongoDB container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
