### ISSUE TITLE
[bitnami/nginx] Unable to set the Pod Disruption Budget correctly

### ISSUE THREAD

**Issue by francesco-kekko-damico** [bitnami/charts#15747]
### Name and Version

bitnami/nginx

### What architecture are you using?

Kubectl version:
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T15:54:23Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### What steps will reproduce the bug?

There are a couple of issues that are not allowing the PDB to be created correctly.

- The first issue is that the `minAvailable` and `maxUnavailable` keys cannot be both set in a single PDB. To reproduce this issue, enable the PDB and set one of the two keys in the values.yaml (https://github.com/bitnami/charts/blob/2cb65fa3c06887a4f46134daecda4495bd34a761/bitnami/nginx/values.yaml#L392). i.e.:

```yaml
  pdb:
    create: true
    maxUnavailable: 1
```
it will fail. (See output below). The _templates/pdb.yaml_ needs to be adjusted accordingly to allow only one key to be specified.
The workaround for this atm, is to delete one of the two keys from the default values, by overriding the value of the key to be null.

- The second issue is that, currently, the input validation for the `minAvailable` and `maxUnavailable` PDB values in the values.schema.json (https://github.com/bitnami/charts/blob/main/bitnami/nginx/values.schema.json) are set to validate only the integer and throwing an error if we try to set the values as a percentage (string).
This input validation is restricting us from custom our PDB values according to our needs. To reproduce this issue, enable the PDB and set the value of one of the two keys in the _values.yaml_ as a percentage. i.e.:

```yaml
  pdb:
    create: true
    maxUnavailable: 25%`
```
it will fail. (See output below).

Both points above can be checked in the doc (https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget), where it states that only one key is allowed and the values for the `minAvailable` and `maxUnavailable` can be expressed as integers or as a percentage.

Can this please be fixed?

### What is the expected behavior?

I'm expecting to:
- don't need to delete one of the two keys from the default values, by overriding the value of the key to be null.
- be able to set the values for the `minAvailable` and `maxUnavailable` to be expressed as integers or as a percentage.

### What do you see instead?

Output from the first issue:

```
UPGRADE FAILED: failed to create resource: PodDisruptionBudget.policy "redirector-nginx" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc016660f60), Selector:(*v1.LabelSelector)(0xc016660f80), MaxUnavailable:(*intstr.IntOrString)(0xc016660f40)}: minAvailable and maxUnavailable cannot be both set
```

Output from the second issue:

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
nginx:
pdb.maxUnavailable: Invalid type. Expected: integer, given: string
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by francesco-kekko-damico** [comment]
I honestly don't have time to solve these issues atm. If someone can start looking at fixing:
- the values.schema.json, to allow the PDB _minAvailable_ and _maxUnavailable_ values to expressed as integer and as a percentage (string)
-  the template/pdb.yaml, to allow to specify only one of the two _minAvailable_ key or _maxUnavailable_ key 

that would be great.

**Comment by francesco-kekko-damico** [comment]
Hi, is there any update on this fix?

**Comment by jotamartos** [comment]
Hi @francesco-kekko-damico,

Thank you for creating the ticket. As you mentioned, you can just configure one parameter in the PodDisruptionBudged as explain in [the documentation](https://kubernetes.io/docs/tasks/run-application/configure-pdb/). In your case, if you use these values in your values file 

```
  pdb:
    create: true
    maxUnavailable: 1
```

you will be only overwriting the maxUnavailable parameter, but not the minAvailable one that is set to 1 by default. If you want this to work, you need to specify both 

```
  pdb:
    create: true
    minAvailable: 0
    maxUnavailable: 1
```

Regarding the percentage issue, it's only nginx who is checking those values. You can create a simple PR to remove the information from the values.schema.json file and get credits for that. Will you do it?

**Comment by jotamartos** [comment]
In that case, the solution is to remove the information in the values.schema.json file as I mentioned above. I'm going to create a PR to remove it and allow you create a pdb that solves that case. I basically edited the chart information and installed it 

```
diff --git a/bitnami/nginx/values.schema.json b/bitnami/nginx/values.schema.json
index d2d5dde76..8b51d9550 100644
--- a/bitnami/nginx/values.schema.json
+++ b/bitnami/nginx/values.schema.json
@@ -76,20 +76,6 @@
           }
         }
       }
-    },
-    "pdb": {
-      "type": "object",
-      "properties": {
-        "create": {
-          "type": "boolean"
-        },
-        "minAvailable": {
-          "type": "integer"
-        },
-        "maxUnavailable": {
-          "type": "integer"
-        }
-      }
     }
   }
 }
diff --git a/bitnami/nginx/values.yaml b/bitnami/nginx/values.yaml
index 5cc8ecd75..2d95958a2 100644
--- a/bitnami/nginx/values.yaml
+++ b/bitnami/nginx/values.yaml
@@ -392,13 +392,13 @@ initContainers: []
 pdb:
   ## @param pdb.create Created a PodDisruptionBudget
   ##
-  create: false
+  create: true
   ## @param pdb.minAvailable Min number of pods that must still be available after the eviction
   ##
-  minAvailable: 1
+  minAvailable: 0
   ## @param pdb.maxUnavailable Max number of pods that can be unavailable after the eviction
   ##
-  maxUnavailable: 0
+  maxUnavailable: "0%"

 ## @section Custom NGINX application parameters

```

The pdb configuration allowed me set the max unavailable parameter to 0%

```
$ k get PodDisruptionBudget
NAME          MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
jota-nginx   N/A                        0%                               0                                           10s
```

**Comment by jotamartos** [comment]
PR created here: https://github.com/bitnami/charts/pull/16055

**Comment by francesco-kekko-damico** [comment]
Thank you @jotamartos for creating the PR. 

Could you please add a small comment/instruction on how to disable one of the two PDB keys in values.yaml and include in your PR? 

Other users will benefit from your comment/instruction and knowing that one of the two keys (minAvailable key or maxUnavailable) must be disable by setting the value to 0 in this Helm

**Comment by jotamartos** [comment]
Added a comment in the values.yaml file as suggested. Will close the PR once the pipeline succeeds
