### ISSUE TITLE
[bitnami/rabbitmq] Upgrade RabbitMQ from 3.8.6 in Kubernetes Using Terraform

### ISSUE THREAD

**Issue by nat-ray** [bitnami/charts#15756]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am running RabbitMQ 3.8.6 in my Kubernetes cluster which is deployed using Terraform. I need to upgrade to 3.11.10 following [the RabbitMQ upgrade path](https://www.rabbitmq.com/upgrade.html#rabbitmq-version-upgradability), which is 3.8 to 3.9, 3.9 to 3.10, and 3.10 to 3.11.

I am trying to use [ArtifactHub](https://artifacthub.io/packages/helm/bitnami/rabbitmq), but 3.9 is so old that there is no longer a Helm chart here for RabbitMQ 3.8. I tried to upgrade using chart_version = "8.21.0" and image_tag = "3.9.23-debian-11-r0" as I found that image tag [here in the version history](https://github.com/bitnami/containers/commits/main/bitnami/rabbitmq/3.9/debian-11/tags-info.yaml). Unfortunately, that fails with the error:

```
Error: chart "rabbitmq" version "8.21.0" not found in https://charts.bitnami.com/bitnami repository
```

Is there any way to go about this?

### What do you see instead?

Error: chart "rabbitmq" version "8.21.0" not found in https://charts.bitnami.com/bitnami repository

**Comment by javsalgar** [comment]
Hi,

You could try, replacing the rabbitmq image using the chart values, we have images of each branch in the bitnami/rabbitmq repository.

**Comment by nat-ray** [comment]
Thank you @javsalgar , this worked for me.
