### ISSUE TITLE
Rabbitmq - Error: unable to perform an operation on node 'rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local

### ISSUE THREAD

**Issue by zohebk8s** [bitnami/charts#15779]
### Name and Version

bitnami/3.10.8-debian-11-r4

### What architecture are you using?

None

### What steps will reproduce the bug?

I've deployed RabbitMQ in the Azure AKS cluster(Version: 1.20.9)

However, the pod is not coming up and it's throwing the below error. I've tried with & without any values for "erlangCookie". But still, I am getting the same error. Do we have any specific restrictions on passwords, I am using 14 Character password and even tried with 24 characters as well. But the same error.
```
  Warning  Unhealthy  99s (x2 over 2m9s)    kubelet  (combined from similar events): Readiness probe failed: Error: unable to perform an operation on node 'rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local'. Please see diagnostics information and suggestions below.
```
The most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to the CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/q.html to learn more
 * Consult server logs on node rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local
 * If the target node is configured to use long node names, don't forget to use --longnames with CLI tools

### DIAGNOSTICS

attempted to contact: ['rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local']

rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local:
  * connected to epmd (port 4369) on rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-917-rabbit@rabbitmq-0.rabbitmq-headless.namespace.svc.cluster.local'
 * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq
 * Erlang cookie hash: some-hash-value

### What is the expected behavior?

As I am using replicas:3, the pods should be up and running

### What do you see instead?

Pod is crashing with above errors

**Comment by zohebk8s** [comment]
@carrodher Appreciate your support on this. Am I missing something? or Do I need to use other versions of RabbitMQ? As the Azure AKS Version is 1.20.9

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info. In the same way, if you think there is something to be fixed feel free to create a PR. The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by zohebk8s** [comment]
@carrodher I haven't customized anything. No customization. It's a plain/basic helm installation specific to RabbitMQ.

That's why raised an issue in Github. From the error what you think will be the problem/issue? We cannot use this RabbitMQ chart for Azure AKS 1.20.9 versions?

**Comment by mckennajones** [comment]
@carrodher I'm observing similar behavior on a v1.25.6 AKS cluster. In my experience each of the nodes's readiness probes starts to fail shortly after any applications connect to me. 

Were you able to investigate further? I'll post any findings as I continue investigation on my side

**Comment by sirosfakhri** [comment]
any update on this?
I use windows 11 and got same error

```
rabbitmqctl version 3.12.12

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)

```

```
Error: unable to perform an operation on node 'rabbit@SiFa-Laptop'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@SiFa-Laptop
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: ['rabbit@SiFa-Laptop']

rabbit@SiFa-Laptop:
  * connected to epmd (port 4369) on SiFa-Laptop
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on SiFa-Laptop
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-1000-rabbit@SiFa-Laptop'
 * effective user's home directory: c:/Users/siros
 * Erlang cookie hash: 7k7Mf5VuC1UsjiY1e2vsNg==
```

**Comment by Sharker5854** [comment]
@sirosfakhri 
did you manage to solve this problem?

**Comment by sirosfakhri** [comment]
> @sirosfakhri did you manage to solve this problem?

Uunfortunately no. I had to use docker and Now it's works fine.

**Comment by RindraCoG** [comment]
I used Windows 10, I install with chocolatey but get the same issue where using the command line tools, but the interface on localhost:15672 works
