### ISSUE TITLE
[bitnami/rabbitmq] Support for pre-upgrade hook

### ISSUE THREAD

**Issue by shahiinn** [bitnami/charts#15784]
### Name and Version

bitnami/rabbitmq 11.12.0

### What is the problem this feature will solve?

With the New version of rabbitmq, feature flags needs to be enabled. Hence if we are upgrading an old version of rabbitmq (say 3.8.x) we need to run the below command to get the setup working.

`rabbitmqctl enable_feature_flag all`

Currently, there are no native ways by which we could do this command execution automated.

### What is the feature you are proposing to solve the problem?

Adding support for the pre-upgrade hook so that we could directly define the required commands to be executed

### What alternatives have you considered?

As the application needs to be running while the command is executed we cannot use an init container for it. Are there any other possible alternatives to achieve this?

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
