### ISSUE TITLE
[bitnami/minio] Provisioning determines whether it is a brand new instance

### ISSUE THREAD

**Issue by clcc2019** [bitnami/charts#15807]
### Name and Version

bitnami/minio:12.2.3

### What is the problem this feature will solve?

Provisioning determines whether it is a brand new instance,The query skips if there is a bucket or user

```shell
{{- if .Values.provisioning.reset }}
if ! mc ls {{ $minioAlias }}/ | grep -q '/'; then
  echo "No buckets found, creating default bucket"
else
  echo "Found at least one bucket, Skip"
  exit 0;
fi;
{{- end }}
```

### What is the feature you are proposing to solve the problem?

Avoid resetting my user information on update

**Comment by javsalgar** [comment]
Hi,

Could you explain a bit more the issue you are experiencing?

**Comment by marcosbc** [comment]
Hi @clcc2019, it could be an option to check for other ways to ensuring that the deployment has been initialized before. I would encourage you to submit any contributions in that direction, we would be glad to help with the review and release of the changes!
