### ISSUE TITLE
keycloak v21 support

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#15809]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

bitnami/keycloak chart currently supports v20 of keycloak. Would be great to have v21 support.

relates to: https://github.com/bitnami/containers/issues/25814

https://www.keycloak.org/2023/02/keycloak-2100-released.html

I know that the issue exists over at the containers repo but i feel this one might gain more visibility and upvotes to assist the internal team at bitnami to prioritize this against other feature requests

### What is the feature you are proposing to solve the problem?

Gain support for v21 of keycloak with the new features that brings.

**Comment by joancafom** [comment]
I am glad to announce that the latest version of Keycloak (21.0.2) was released some hours ago and both the [container image](https://github.com/bitnami/containers/commit/77d3ca972860f49f11dab4f975af37da24640385) and [chart](https://github.com/bitnami/charts) are currently available! 🎉

```bash
$ docker run --rm -it bitnami/keycloak kc.sh --version
...
Keycloak 21.0.2
```
