### ISSUE TITLE
[bitnami/keycloak] How to Enable Health-check API for Keycloak Bitnami 

### ISSUE THREAD

**Issue by jyotishet23123** [bitnami/charts#15805]
### Name and Version

bitnami/keycloak:20.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello,

In order to enable the Keycloak Health check I added the below environment variable in values.yaml file as mentioned in the Keycloak but the health metrics are available. 
```yaml
extraEnvVars:
  - name: KC_HEALTH_ENABLED
    value: true
```
Could you please suggest to me how to enable Keycloak Health check?

### What is the expected behavior?

Health metrics of Keycloak should be available but instead, it's not

### What do you see instead?

The metrics are not available at the below paths and its blank

- path: /health
- path: /health/live
- path: /health/ready

**Comment by javsalgar** [comment]
Hi,

If the environment variable is set and this is consumed by keycloak, it is not clear to me that the issue relies on the Bitnami packaging of Keycloak. Did you check with the keycloak devs?

**Comment by jyotishet23123** [comment]
Hi @javsalgar ,

The env variable  KC_HEALTH_ENABLED is NOT  getting set through values.yaml and throws an error... 

can you suggest me on how to enable Health metrics in Keycloak bitnami ....

**Comment by javsalgar** [comment]
Which is the error thrown?

**Comment by jyotishet23123** [comment]
Hello @javsalgar : After adding the the health-check ENV variable in the values.yaml file , i start to receive the following error 👍 


\":1001},\"serviceAccountName\":\"keycloak\",\"volumes\":null}},\"updateStrategy\":{\"rollingUpdate\":{},\"type\":\"RollingUpdate\"}}}\n]] spec:map[template:map[spec:map[affinity:map[nodeAffinity:<nil> podAffinity:<nil>] initContainers:<nil> volumes:<nil>]]]]": unrecognized type: string

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami keycloak container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
