### ISSUE TITLE
[bitnami/matomo] Can't add customCA to Matomo Chart, because of 'apt-failed' on OpenShift

### ISSUE THREAD

**Issue by m-wack** [bitnami/charts#15810]
### Name and Version

bitnami/matomo-0.2.29

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Try to use the Chart with something like:

```
  certificates:
    customCAs:
      - secret: tf-intern-cert
```
      
on OpenShift and the init container will fail because apt fails. This seems to be a permissions error. Over at the redmine chart, this was fixed recently with this PR: https://github.com/bitnami/charts/pull/15496 to this Issue: https://github.com/bitnami/charts/issues/12787

Maybe the same can be done for Matomo?

### Are you using any custom parameters or values?
```
  certificates:
    customCAs:
      - secret: tf-intern-cert
```
### What is the expected behavior?

The Init Container adds the Certificate

### What do you see instead?
```
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
apt failed, retrying
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
```

**Comment by m-wack** [comment]
To add to this Bug:

even when the init container runs through (by setting runAsUser to 0) the certificates cannot be used in the matomo main-container, because the /etc/ssl/certs folder is created by using an emptydir volume that's not mounted inside the main-container.

you either need to set 
`  extraVolumeMounts:
    - name: etc-ssl-certs
      mountPath: /etc/ssl/certs
    - name: etc-ssl-private
      mountPath: /etc/ssl/private`
      
in your values.yaml or the developers would need to ad this to the container-definition if customCAs is set:

`            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: etc-ssl-private
              mountPath: /etc/ssl/private`

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! If the same Redmine fix can be applied to Matomo, would you like to submit a PR fixing the issue?
