### ISSUE TITLE
Upgrade rabbitmq image to 3.11 (rabbitmq cluster operator)

### ISSUE THREAD

**Issue by brunocascio** [bitnami/charts#15811]
### Name and Version

bitnami/rabbitmq-cluser-operator 3.2.8

### What is the problem this feature will solve?

Support rabbitmq 3.11 in order to support superstreams feature

### What is the feature you are proposing to solve the problem?

Upgrade rabbitmq image to 3.11 (currently 3.10)

### What alternatives have you considered?

- Upgrade `rabbitmqImage:` property to 3.11 but I'm not sure if it's going to work

**Comment by carrodher** [comment]
Thanks for letting us know. I just created an internal task in order to bump the bundled RabbitMQ version. We will update this issue once there is a new release updating the RabbitMQ branch.

**Comment by carrodher** [comment]
We just released a new version of the bitnami/rabbitmq-operator Helm chart bumping the bitnami/rabbitmq container image version (see https://github.com/bitnami/charts/pull/15825). Thanks for reporting this topic!
