### ISSUE TITLE
Persistent volume not created even if persistence.enabled=true

### ISSUE THREAD

**Issue by siva3io** [bitnami/charts#15818]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

1) Install helm
2) `helm repo add bitnami https://charts.bitnami.com/bitnami`
3) `helm install kafka-release bitnami/kafka --set persistence.size=8Gi,logPersistence.size=8Gi,replicaCount=3,volumePermissions.enabled=true,persistence.enabled=true,logPersistence.enabled=true,auth.clientProtocol=plaintext,allowPlaintextListener=true,listeners=PLAINTEXT://0.0.0.0:9092,advertisedListeners=PLAINTEXT://:9092,listenerSecurityProtocolMap=PLAINTEXT:PLAINTEXT,interBrokerListenerName="PLAINTEXT",serviceAccount.create=true,rbac.create=true,image.tag=latest`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Persistent volume should have been binded with PVC.

### What do you see instead?

There are no persistent volume and hence persistent volume claim is going into pending state and therefore pod is going in pending state.

**Comment by hatharom** [comment]
You havent specified 'persistence.storageClass' which means it will use the the default provisioner on your cluster.
What is your default provisioner?

**Comment by siva3io** [comment]
1. kubernetes.io/aws-ebs
2. 
![image](https://user-images.githubusercontent.com/115470016/229309625-febd3bf7-8f50-45cb-9f8c-d238817bb4b9.png)

**Comment by migruiz4** [comment]
Hi @siva3io,

The issue does not appear to be related to the Kafka chart, but to the EBS CSI controller.

I'm sorry but it would be out of our scope to help with the EBS CSI configuration and troubleshooting.

I would recommend following the driver's configuration guides (https://docs.aws.amazon.com/eks/latest/userguide/ebs-sample-app.html) and asking in their GitHub repository for better assistance: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
