### ISSUE TITLE
[bitnami/mongodb] Unable to install dependent charts for StackStorm helm chart

### ISSUE THREAD

**Issue by acharbha** [bitnami/charts#15817]
### Name and Version

docker.io/bitnami/mongodb:4.4

### What architecture are you using?

None

### What steps will reproduce the bug?

Installed helm chart however its not success.

`helm install stackstorm-k8s-ha .\stackstorm-ha-0.110.0.tgz --namespace=myspace`

Depended pods are failing to install due these pods are non-root and hence don't have access to directories.

#### example mongodb pod status:
```
CrashLoopBackOff: back-off 5m0s restarting failed container=mongodb pod=stackstorm-k8s-ha-mongodb-0_myspace(dfd854f4-05ac-4ce7-be9e-1694f3ac7fb0)
```
#### pod logs:
```
Advertised Hostname: stackstorm-k8s-ha-mongodb-0.stackstorm-k8s-ha-mongodb-headless.myspace.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 14:55:30.95 
mongodb 14:55:31.00 Welcome to the Bitnami mongodb container
mongodb 14:55:31.00 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 14:55:31.00 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 14:55:31.01 
mongodb 14:55:31.01 INFO  ==> ** Starting MongoDB setup **
mongodb 14:55:31.03 INFO  ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb': Permission denied
```
Is anyone able to fix this issue, can someone help me with how to proceed with this and what changes are needed in the charts?

**Comment by javsalgar** [comment]
Hi,

Please note that we are not the maintainers of the stackstorm helm chart. Did you check first with the maintainers?
