### ISSUE TITLE
[bitnami/wordpress] HTTP ERROR 500

### ISSUE THREAD

**Issue by riseitup** [bitnami/charts#15831]
### Name and Version

bitnami/wordpress 6.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

my website runs on bitnami wordpress on a google cloud platform. I received HTTP ERROR 500. the issue occurred a few days ago when the WordPress core was updated to the 6.2 version which caused an issue with Themeco themes (X, Pro, and similar). I think I should downgrade the WordPress core version to 6.1.1 (the previous version), so I can update my theme before the WordPress update, would you please how I can do that?

### Are you using any custom parameters or values?

no

### What is the expected behavior?

na

### What do you see instead?

HTTP ERROR 500

### Additional information

na

**Comment by riseitup** [comment]
hello avsalgar, can you help me in this matter

**Comment by javsalgar** [comment]
Hi,

Are you using the bitnami/wordpress helm chart or the bitnami/wordpress VM?
