### ISSUE TITLE
[bitnami/elasticsearch] Environment variable ES_PATH_CONF not set. How can I locate S3 repository config directory?

### ISSUE THREAD

**Issue by sunhongmin225** [bitnami/charts#15835]
### Name and Version

bitnami/elasticsearch 8.6.2-debian-11-r10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to use AWS S3 as a repository for [Snapshot/Restore](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/modules-snapshots.html).

I've created an AWS S3 bucket for my purpose and am trying to register a snapshot repository using Kibana UI. I want to use [Kubernetes service accounts](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) for authentication.

In the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/repository-s3.html#iam-kubernetes-service-accounts), it says that I need to add a symlink to the `$AWS_WEB_IDENTITY_TOKEN_FILE` environment variable (which should be automatically set by a Kubernetes pod) in **the S3 repository config directory**, so the repository can have the read access for the service account.

This code snippet in the documentation shows how I can do this:

```console
mkdir -p "${ES_PATH_CONF}/repository-s3"
ln -s $AWS_WEB_IDENTITY_TOKEN_FILE "${ES_PATH_CONF}/repository-s3/aws-web-identity-token-file"
```

However, I found that none of the Elasticsearch nodes (i.e., elasticsearch-master, Elasticsearch-data, Elasticsearch-coordinating, elasticsearch-ingest) have set `ES_PATH_CONF` as an environment variable.

As far as I know, `ES_PATH_CONF` environment variable specifies the path to the Elasticsearch configuration directory that contains the configuration files used by Elasticsearch. And I suppose that configuration related to S3 repository is also located in the `${ES_PATH_CONF}` path.

I've installed elasticsearch via helm using bitnami repository. How can I locate **the S3 repository config directory**, or in general, the Elasticsearch configuration directory (i.e., `ES_PATH_CONF`) ?

Sorry for raising this as a bug; I was expecting that each elasticsearch node holds information about `ES_PATH_CONF`, but it didn't.

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

`echo ${ES_PATH_CONF}` shows the path to the Elasticsearch configuration directory.

### What do you see instead?

None. Environment variable `ES_PATH_CONF` is not set.

**Comment by javsalgar** [comment]
Hi,

The configuration folder in Bitnami containers is set in the `ELASTICSEARCH_CONF_DIR`, which points to `/opt/bitnami/elasticsearch/config`

**Comment by sunhongmin225** [comment]
@javsalgar

Thanks for your reply. I wonder why but when I `exec` into my `elasticsearch-master-0` node and do `echo $ELASTICSEARCH_CONF_DIR`, nothing returns. This is awkward, but anyway, I've found that in the `/opt/bitnami/elasticsearch/config` directory, configuration related files such as `elasticsearch.yml` or `log4j2.properties` exist, so I just gave it a try.

I've done the followings in two master nodes (i.e., `elasticsearch-master-0` and `elasticsearch-master-1`) as written in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/repository-s3.html#iam-kubernetes-service-accounts):

```console
mkdir -p /opt/bitnami/elasticsearch/config/repository-s3
ln -s $AWS_WEB_IDENTITY_TOKEN_FILE /opt/bitnami/elasticsearch/config/repository-s3/aws-web-identity-token-file
```

However, repository verification (done via Kibana UI) is failing with following error message:

```json
{
  "name": "ResponseError",
  "meta": {
    "body": {
      "error": {
        "root_cause": [
          {
            "type": "repository_verification_exception",
            "reason": "[my-eks-cluster-logging-snapshot-repository] path  is not accessible on master node"
          }
        ],
        "type": "repository_verification_exception",
        "reason": "[my-eks-cluster-logging-snapshot-repository] path  is not accessible on master node",
        "caused_by": {
          "type": "i_o_exception",
          "reason": "Unable to upload object [tests-<REDACTED>/master.dat] using a single upload",
          "caused_by": {
            "type": "amazon_s3_exception",
            "reason": "amazon_s3_exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: <REDACTED>; S3 Extended Request ID: <REDACTED>/<REDACTED>/<REDACTED>=; Proxy: null)"
          }
        }
      },
      "status": 500
    },
    "statusCode": 500,
    "headers": {
      "x-opaque-id": "bb3a5e7c-dea5-4b31-9b6c-<REDACTED>;kibana:application:management:",
      "x-elastic-product": "Elasticsearch",
      "content-type": "application/json;charset=utf-8",
      "content-length": "764"
    },
    "meta": {
      "context": null,
      "request": {
        "params": {
          "method": "POST",
          "path": "/_snapshot/my-eks-cluster-logging-snapshot-repository/_verify",
          "querystring": "",
          "headers": {
            "user-agent": "Kibana/8.6.2",
            "x-elastic-product-origin": "kibana",
            "x-opaque-id": "bb3a5e7c-dea5-4b31-9b6c-<REDACTED>;kibana:application:management:",
            "x-elastic-client-meta": "es=8.4.0p,js=16.18.1,t=8.2.0,hc=16.18.1",
            "accept": "application/vnd.elasticsearch+json; compatible-with=8,text/plain"
          }
        },
        "options": {
          "opaqueId": "bb3a5e7c-dea5-4b31-9b6c-<REDACTED>;kibana:application:management:",
          "headers": {
            "x-elastic-product-origin": "kibana",
            "user-agent": "Kibana/8.6.2",
            "x-opaque-id": "bb3a5e7c-dea5-4b31-9b6c-<REDACTED>",
            "x-elastic-client-meta": "es=8.4.0p,js=16.18.1,t=8.2.0,hc=16.18.1"
          }
        },
        "id": 1
      },
      "name": "elasticsearch-js",
      "connection": {
        "url": "http://elasticsearch:9200/",
        "id": "http://elasticsearch:9200/",
        "headers": {},
        "status": "alive"
      },
      "attempts": 0,
      "aborted": false
    },
    "warnings": null
  }
}
```

I've created a Kubernetes ServiceAccount with correct permissions as recommended in https://www.elastic.co/guide/en/elasticsearch/reference/8.6/repository-s3.html#repository-s3-permissions. I wonder why I get the above "Access Denied" error. Do you have any idea on why I get the following error message? Thanks.

**Comment by javsalgar** [comment]
Hi,

I don't have the expertise on the plugin, it seems to me that this goes a bit beyond the Bitnami packaging of the application and it's more related to the plugin. I will leave the ticket open in case someone from the community wants to participate, but my advice would be checking with the plugin devs for advice.

**Comment by stdmje** [comment]
@sunhongmin225 did you found a solution for that? I wonder what i have to add to the chart values in order to setup s3 backup/restore properly.

Thanks!

**Comment by sunhongmin225** [comment]
> @sunhongmin225 did you found a solution for that? I wonder what i have to add to the chart values in order to setup s3 backup/restore properly.
> 
> Thanks!

Unfortunately, I could not find a solution for this issue.

**Comment by sarathskumar** [comment]
Hi 
I am facing the same issue mentioned above. Please suggest an solution for this

**Comment by naasir-ansar** [comment]
me too having same issue.
in my case I want to store with on-prem storage

**Comment by scila1996** [comment]
Hi @sunhongmin225. I have found the way to config it. Just add this

```
  extraVolumes:
    - name: irsa-token
      projected:
        sources:
          - serviceAccountToken:
              path: aws-web-identity-token-file
              expirationSeconds: 3600
              audience: sts.amazonaws.com
  extraVolumeMounts:
    - name: irsa-token
      mountPath: /opt/bitnami/elasticsearch/config/repository-s3/aws-web-identity-token-file
      subPath: aws-web-identity-token-file
      readOnly: true
```
