### ISSUE TITLE
[bitnami/cassandra] `pod down- error-grpc: the connection is unavailable` not work

### ISSUE THREAD

**Issue by devopsdymyr** [bitnami/charts#1592]
**Which chart**:
cassandra

**Description**

Helm chart is working fine for single pod cassandra.used default values.yaml file
![image](https://user-images.githubusercontent.com/41105507/68831621-d7b4b880-06d4-11ea-8b1c-04efbae2c540.png)

https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml

then tried to deploy same helm chart with production ready values.yaml getting error.
https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values-production.yaml

**Steps to reproduce the issue:**
I have removed values.yaml from chart and moved values-production.yaml file to values.yaml
1. helm install -n cassandra . 

2. helm status cassandra
![image](https://user-images.githubusercontent.com/41105507/68831672-fe72ef00-06d4-11ea-886f-da61300d5715.png)

3. error
![image](https://user-images.githubusercontent.com/41105507/68831806-57428780-06d5-11ea-9edc-248e19f318d9.png)

**Describe the results you received:**
how i can make this helm chart to multiple node based cassandra cluster

**Comment by andresbono** [comment]
Hi @devopsdymyr, we will try to reproduce your issue and we will report back.

**Comment by andresbono** [comment]
We tried the following:

```
helm install -n cassandra -f ./values-production.yaml --set dbUser.password=SecretPassword .
```
(Note that the password should be provided), the defaults in the `values-production.yaml` are not enough).

After some time, all the pods are running:

```
$ kubectl get pods
NAME          READY   STATUS    RESTARTS   AGE
cassandra-0   1/1     Running   0          4m56s
cassandra-1   1/1     Running   0          3m19s
cassandra-2   1/1     Running   0          109s
```

Could it be related to the resources of your Kubernetes cluster? Where are you deploying the chart?

Does it happen consistently? Did you try to delete the chart and volumes and try again?

**Comment by devopsdymyr** [comment]
thanks the issue is related to resources problem

**Comment by andresbono** [comment]
Thanks for letting us know @devopsdymyr!
