### ISSUE TITLE
[bitnami/etcd] Networkpolicy uses chart version as podSelector

### ISSUE THREAD

**Issue by bh-tt** [bitnami/charts#15936]
### Name and Version

bitnami/etcd:8.8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy a deny-all networkpolicy matching all pods in a namespace
2. Deploy etcd with `networkPolicy.enabled=true`
3. do a helm upgrade to a different chart version
4. the new pod fails to become ready as the networkpolicy is now set to the new chart version. This means it cannot reach the old nodes. Simultaneously the 2 running nodes are unavailable since only our default deny-all networkpolicy applies to them.

### Are you using any custom parameters or values?
```
networkPolicy:
  enabled: true
```
### What is the expected behavior?

The networkpolicy should not select pods based on the chart version, it should instead use only annotations like app.kubernetes.io/instance, app.kubernetes.io/name which do not change between upgrades.

### What do you see instead?

The networkpolicy selects only pods on the current version of the chart, which breaks rolling upgrades.

### Additional information

It's good I tested this on a test cluster before upgrading the production etcd because this is a severe bug on an application that is normally safe to do a rolling upgrade with.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue! Would you like to submit a PR fixing it?
