### ISSUE TITLE
[bitnami/postgresql-ha] Service Account Bug Fix 

### ISSUE THREAD

**Issue by Deepanshu6dec** [bitnami/charts#15932]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Service Account Bug issue 

Issue:
1. When we want  to use custom service account name its picking a ```default``` Service account name. because of _helpers-tpl a condition is setup ( which is actually correct )
```
serviceAccount:
  create: false
  name: "Custom-Service-Account"
```

2. When we install our helm chart with dry-run to test which service is picking its using `default` Service Account 

```
helm install postgresql-ha -f psql_values.yaml bitnami/postgresql-ha --dry-run --debug

```

3.  When we used to create new service account its working fine 
4. To Fix This Issue: We have to remove that condition from Postgresql-ha stateful-sets and PG-Pool deployment manifest

```
# postgresql-ha stateful-sets

      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "postgresql-ha.serviceAccountName" . }}
      {{- end }}

# Pg-pool Service Account

     {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "postgresql-ha.serviceAccountName" . }}
      {{- end }}

```

- Template should be 

```
# postgresql-ha stateful-sets

      serviceAccountName: {{ include "postgresql-ha.serviceAccountName" . }}

# Pg-pool Service Account

      serviceAccountName: {{ include "postgresql-ha.serviceAccountName" . }}

```

- As this Condition already implement in ` _helpers.tpl`
- In my local i just remove those two conditions from template and after that it is working fine.
- Able to use my service account

```
# cat _helpers.tpl 

{{/*
 Create the name of the service account to use
 */}}
{{- define "postgresql-ha.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
    {{ default (include "common.names.fullname" .) .Values.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}

```

 

### Are you using any custom parameters or values?

no

### What is the expected behavior?

It should pick my own service Account

### What do you see instead?

Its using default

**Comment by Deepanshu6dec** [comment]
Yes Sure, Will create a PR for fixing this issue.

**Comment by javsalgar** [comment]
Thank you!!
