### ISSUE TITLE
[bitnami/rabbitmq] Join external cluster from POD always attempt to connect rabbitmq-headless.rabbitmq.svc.cluster.local

### ISSUE THREAD

**Issue by vjwilson1987** [bitnami/charts#15944]
### Name and Version

bitnami/rabbitmq 3.11.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed rabbitmq on my Kubernetes using the bitnami helm chart.

App version: 3.11.9
Chart version: 11.10.0

Then I tried to have it join an external RabbitMQ cluster running on EC2 instances with HA mode enabled. The purpose of doing it is that I am preparing a migration of RabbitMQ from EC2 to Kubernetes given [here](https://blog.palark.com/migrating-rabbitmq-to-kubernetes-without-downtime/)

The rabbitmq node name on the source ( EC2 instance ) is `rabbit@rabbitmqec2`  ( using short node name by default ) and its public IP is, lets say 1.2.3.4

Command running on the POD to join the external RabbitMQ EC2 node:
```
I have no name!@rabbitmq-0:/$ rabbitmqctl stop_app && rabbitmqctl join_cluster rabbit@rabbitmqec2 && rabbitmqctl start_app
```

But it fails and shows the following error always:
```
attempted to contact: ['rabbit@rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local']

rabbit@rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local:
  * unable to connect to epmd (port 4369) on rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local: nxdomain (non-existing domain)
```

To make the IP 1.2.3.4 known to the RabbitMQ on K8s to connect to `rabbit@rabbitmqec2` since the short node name rabbitmqec2 does not resolve globally, I tried the following methods on K8s:

1.  Pod hostAliases /etc/hosts

Using the `hostAliases` option by adding the following in the helm chart so that the POD /etc/hosts will have an entry

```
hostAliases:
- ip: "1.2.3.4"
  hostnames:
  - "rabbitmqec2"
```

2. Externalname

I tried creating an external service name ( within the same namespace rabbitmq ) with the short node name pointing to the DNS resolving long node name, say rabbitmqec2.example.com ( where the long node name points to the EC2 IP 1.2.3.4 )

```
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqec2
  namespace: rabbitmq
spec:
  type: ExternalName
  externalName: rabbitmqec2.example.com
```

3. Coredns entry

I tried the following entry in CoreDNS confirmap

```
        hosts custom.hosts rabbitmqec2 {
            1.2.3.4 rabbitmqec2
            fallthrough
        }
```

Even though I tried all the above methods, the `rabbitmqctl join_cluster rabbit@rabbitmqec2` still attempts to connect to `rabbit@rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local` which does not make sense to me.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The command `rabbitmqctl join_cluster rabbit@rabbitmqec2` should connect to the source EC2 IP 1.2.3.4 instead of trying to connect to `rabbit@rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local`

### What do you see instead?

The error I see:

```
I have no name!@rabbitmq-0:/$ rabbitmqctl stop_app && rabbitmqctl join_cluster rabbit@rabbitmqec2 && rabbitmqctl start_app

attempted to contact: ['rabbit@rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local']

rabbit@rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local:
  * unable to connect to epmd (port 4369) on rabbitmqec2.rabbitmq-headless.rabbitmq.svc.cluster.local: nxdomain (non-existing domain)
```

**Comment by javsalgar** [comment]
Hi,

I believe the issue is that it the RabbitMQ is configured for Kubernetes (with features like k8s_peer_discovery). In this situation, it is not clear to me how this integrates with connecting to external RabbitMQ clusters. My advice would be checking with the RabbitMQ devs on how to work with this use case.

**Comment by vjwilson1987** [comment]
@javsalgar If you think this is still up to RabbitMQ K8s devs, please let me know if I am supposed to open an issue [here](https://github.com/rabbitmq/rabbitmq-server)

The main reason I addressed it here is because I installed RabbitMQ on K8s using the bitnami helm chart `bitnami/rabbitmq`

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know! I believe that the RabbitMQ devs should take a look so yes, that place for opening the issue should be the one. Let's see their insights

**Comment by vjwilson1987** [comment]
Marking this as solved since the question has been answered by the RabbitMQ developers on the discussion thread https://github.com/rabbitmq/rabbitmq-server/discussions/7848
