### ISSUE TITLE
[bitnami/mariadb] Unable to use bitnami mariadb helm chart to upgrade to version above 10.6.12.

### ISSUE THREAD

**Issue by FootfallCamKitson** [bitnami/charts#15952]
### Name and Version

bitnami/mariadb 11.5.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Change image.tag to 10.10.2-debian-11-r26
2. Helm uninstall the helm chart.
3. Helm Install the chart
4. Kubernetes pod will be showing CrashLoopBackOff. ([Describe Pod Result](https://prnt.sc/VpoAiJ9k61-H))
5. When checking logs, it doesn't show any useful message. ([Pod Logs](https://prnt.sc/vZvo1nY8CoPC))
6. I had try few version above 10.6.12, all showing the same things. While I try version below 10.6.12, it was working fine for me.

### What do you see instead?

Kubernetes pod will be showing CrashLoopBackOff. ([Describe Pod Result](https://prnt.sc/VpoAiJ9k61-H)) and when checking logs, it doesn't show any useful message. ([Pod Logs](https://prnt.sc/vZvo1nY8CoPC)).

**Comment by rafariossaa** [comment]
Hi,
  When reinstalling the chart are you providing the same `auth.rootPassword` that when you deployed it for first time ?
  Could you enable `image.debug` ? Maybe that will show relevant info.
