### ISSUE TITLE
[bitnami/keycloak] Keycloak Chart version 14.0.0 is using wrong command in keycloak-config-cli job

### ISSUE THREAD

**Issue by kr4sv** [bitnami/charts#15955]
### Name and Version

bitnami/keycloak 14.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When enabling the `keycloakConfigCli`, the command of the keycloak-config-cli job is templated using `.Chart.AppVersion`.
See https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/keycloak-config-cli-job.yaml Line 66
In Chart version 14.0.0,  AppVersion is 21.0.2 --> command is trying to start  `/opt/bitnami/keycloak-config-cli/keycloak-config-cli-21.0.2.jar`
However, the config-cli container used by this chart (bitnami/keycloak-config-cli:5.6.1-debian-11-r5) is still using a 21.0.1.jar - resulting in a "command not found" error.

### Are you using any custom parameters or values?

`keycloakConfigCli:
  enabled: true`

### What is the expected behavior?

keycloak-config-cli container starting correctly

### What do you see instead?

keycloak-config-cli failing to start, as `/opt/bitnami/keycloak-config-cli/keycloak-config-cli-21.0.2.jar` is not found.

### Additional information

As a workaround, the command can be overwritten using the keycloakConfigCli.command parameter.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue, I believe that we should fix the command by not specifiyng exactly the version but maybe using major.minor and a glob. Thoughts on that?

**Comment by kr4sv** [comment]
Looking at the `keycloak-config-cli` container more closely, the default entrypoint `/opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar` is a static symlink pointing to the latest "versioned" jar.
See
![image](https://user-images.githubusercontent.com/77237232/230302696-dcc437f8-edf0-441e-9c8c-174d8e816347.png)

**Comment by javsalgar** [comment]
Hi!

Therefore, it should be a matter of changing the cmd, right? Could you try changing the YAML and ensure it works as expected, if that works we could create a PR

**Comment by kr4sv** [comment]
Hey,
just tested locally - using command `/opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar` is working as expected.
As this however is the container default command, removing the overwrite entirely unless `.Values.keycloakConfigCli.command` might be an option?

**Comment by javsalgar** [comment]
Hi!

If that works, that could be an option indeed.

**Comment by kr4sv** [comment]
remove stale plz :)
