### ISSUE TITLE
[bitnami/postgresql] password authentication failed for a user/pwd specified using values: "auth.username" and "auth.password"

### ISSUE THREAD

**Issue by cmoulliard** [bitnami/charts#15975]
### Name and Version

bitnami/postgresql 11.9.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create a kind cluster
2. Deploy the helm chart as such
```
DB_USERNAME=healthy
DB_PASSWORD=healthy

VERSION=11.9.13
helm install postgresql bitnami/postgresql \
  --version $VERSION \
  --set auth.username=$DB_USERNAME \
  --set auth.password=$DB_PASSWORD \
  --set auth.database=fruits_database \
  --create-namespace \
  -n db
```
3. Check if the pod has been well created
```
kubectl get po -n db
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Running   0          18s
```
4. Access the DB using the psql client
```
export POSTGRES_PASSWORD=$(kubectl get secret --namespace db postgresql -o jsonpath="{.data.password}" | base64 -d)
kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace db --image docker.io/bitnami/postgresql:14.5.0-debian-11-r35 --env="PGPASSWORD=$POSTGRES_PASSWORD" \
      --command -- psql --host postgresql -U healthy -d fruits_database -p 5432
psql: error: connection to server at "postgresql" (10.96.93.222), port 5432 failed: FATAL:  password authentication failed for user "healthy"
pod "postgresql-client" deleted
pod db/postgresql-client terminated (Error)
```
5. Verify the password matches what it has ben passed as helm value
```
echo $POSTGRES_PASSWORD
healthy
```

As the password encoded corresponds to what it has been passed as value to the helm chart using `auth.password`, there is certainly an issue with the init step as we cannot access the db `fruits_database` using the user `healthy` and password `healthy`

### Are you using any custom parameters or values?

  ```
--set auth.username=$DB_USERNAME \
  --set auth.password=$DB_PASSWORD \
  --set auth.database=fruits_database \
```

### What is the expected behavior?

I should be able to auth the user using the password defined as parameter

### What do you see instead?

psql: error: connection to server at "postgresql" (10.96.93.222), port 5432 failed: FATAL:  password authentication failed for user "healthy"

**Comment by javsalgar** [comment]
Hi!

Thanks for opening the ticket. Could you change the title to something more descriptive?

**Comment by cmoulliard** [comment]
The problem I raised here hs been discussed part of this blog post here: https://medium.com/@hijessicahsu/deploy-postgres-on-minikube-5cd8f9ffc9c.

It is related to the fact that if a postgres instance has been created before, data still persist within the PVC and are not cleaned. If I delete the PVC, then I can access the DB with the user/password defined
```
kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace db --image docker.io/bitnami/postgresql:14.5.0-debian-11-r35 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host postgresql -U healthy -d fruits_database -p 5432
If you don't see a command prompt, try pressing enter.

fruits_database=>
```

**Comment by javsalgar** [comment]
Hi,

Yes, the issue is that PVC from StatefulSets don't get removed by default. Therfore letfovers from previous installations should be removed.

**Comment by cmoulliard** [comment]
This is why I propose 2 changes within the documentation here: https://github.com/bitnami/charts/tree/main/bitnami/postgresql#uninstalling-the-chart

1. Rephrase

"The command removes all the Kubernetes components but PVC's associated with the chart and deletes the release." -->
"The command removes all the Kubernetes components except the PVC's associated with the chart and deletes the release."

2. Clearly warn the user

I propose to also add a note within the section to uninstall the helm chart and tell to the user that it is mandatory to delete the PVC when they will re-install the chart using a different database name, user and password !

**Comment by javsalgar** [comment]
Hi,

Thanks for the input! Would you like to submit a PR updating the README?

**Comment by osirisguitar** [comment]
> The problem I raised here hs been discussed part of this blog post here: https://medium.com/@hijessicahsu/deploy-postgres-on-minikube-5cd8f9ffc9c.
> 
> It is related to the fact that if a postgres instance has been created before, data still persist within the PVC and are not cleaned. If I delete the PVC, then I can access the DB with the user/password defined
> 
> ```
> kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace db --image docker.io/bitnami/postgresql:14.5.0-debian-11-r35 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host postgresql -U healthy -d fruits_database -p 5432
> If you don't see a command prompt, try pressing enter.
> 
> fruits_database=>
> ```

Lifesaver, I was tearing my hair out over this :-D

**Comment by jyorko** [comment]
So are you supposed to just delete the pvc and try to login again,  im not getting it,  i have had this error over and over and over again,  not just on Kuberenetes with this specific helm chart but with docker as well.  I have pruned my docker system, deleted entire namespaces and done fresh installs with fresh passwords, and still getting the error?

**Comment by cuongngungok17** [comment]
> So are you supposed to just delete the pvc and try to login again, im not getting it, i have had this error over and over and over again, not just on Kuberenetes with this specific helm chart but with docker as well. I have pruned my docker system, deleted entire namespaces and done fresh installs with fresh passwords, and still getting the error?

Hi, I am also facing with this. Did you solve this problem?

**Comment by Omkar0114** [comment]
Hi everyone,

I had the same issue, "password authentication failed." As @javsalgar mentioned earlier, uninstalling the chart does not remove the PVC attached to it by default. 

Proposed changes to docs to mention: 

- The user should delete the PVC & PV after uninstalling the `bitnami/postgresql` chart. 
- Upgrading/installing the new chart will create a new PVC for DB and create with the new DB name & password!

Thanks!)

**Comment by mhrivnak** [comment]
I hit the same issue and wasted a lot of time on it.
