### ISSUE TITLE
Harbor/harbor-portal image 1.9.1-debian-9-r12 does not exist

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#1598]
**Which chart**: Harbor v 3.0.0 

**Description**
When installing the chart, I get an image backoff on pulling docker.io/bitnami/harbor-portal:1.9.1-debian-9-r12. It looks like this image doesn't exist

**Steps to reproduce the issue:**
Install the chart via helm.

**Describe the results you received:**
Most components upgrade correctly, but the portal does not.

**Describe the results you expected:**

All components install correctly.

**Comment by miguelaeh** [comment]
Hi @ajchiarello ,
I am sorry about this issue, we had a problem with our automated updates and the tag for the harbor portal image was wrong.
We created a PR to fix it.
Thank you very much for reporting the issue!!

**Comment by miguelaeh** [comment]
Hi @ajchiarello ,
The issue was closed because the PR was merged. If you have any problem again we will be happy to help you. 
Again, thank you for reporting the issue.
