### ISSUE TITLE
[bitnami/mongodb] proposal to expose less metrics by default / drastically reduce CPU usage

### ISSUE THREAD

**Issue by horihel** [bitnami/charts#15982]
### Name and Version

bitnami/mongodb-13.9.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. have an idle mongoDB replicaset (2 mongodb, 1 arbiter, but single standalone sees the same behavioud) with a medium amount of data in it (few GBs in several collections). Enable metrics.
2. observe the primary node consume about 1700millis of CPU time in idle
3. Override args and replace `collect-all` with `--collector.diagnosticdata --collector.replicasetstatus`
4. observe mongodb CPU usage drop to about 300-400 millis of CPU time.

### Are you using any custom parameters or values?

```yaml
architecture: replicaSet
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

mongodb_exporter collects a basic amount of metrics per default and can be "extended" to collect more.

### What do you see instead?

IMHO the current default exposes an excessive amount of metrics (in my case almost 1.5MB per scrape in a modestly sized DB).

### Additional information

I'd like to know if the bitnami community is open to toning down the amount of metrics collected by default. AFAICS `diagnosticdata` + `replicasetstatus` is roughly the same amount of data as what the older mongo-exporter collected (before they switched to the new system that exposes _all_ of the backend objects). And I didn't see any difference in the grafana dashboards we're using day to day (though I'm aware that's only _my_ point of view).

The problem currently is that you're not able to tone down the default `--collect-all` without completely replacing the full command (via `metrics.args`). I'd prefer it the other way - collect only a basic amount of data and if someone likes to have "all", they can add `--collect-all` to extraArgs easily. I'm aware that this could be considered a breaking change though.

Alternatilely I can imagine having a switch for "--collect-all" that makes it easy to flick to "basic amount".

If you think that's worth considering, I could start a PR.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. I think that a non breaking option like adding a switch could work great for this case. We'll appreciate the PR contribution! :D

**Comment by horihel** [comment]
should this be re-opened as a PR is ready for it?

**Comment by javsalgar** [comment]
Reopened!
