### ISSUE TITLE
Kafka Kraft Mode upgrade

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#16011]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team - I have installed Bitnami Kafka Kraft mode with version 3.2.3 with 5 pods. I have upgraded to version 3.4.0 now.
I am getting below error after upgrade. Anyone would like to guess it? is there any option to check quorum configuration is up to date or wipe out the local state file if necessary.

![image](https://user-images.githubusercontent.com/96808632/231094838-008e1311-5beb-4e1a-bce5-2f3e9994fcdd.png)

Thanks,

### What do you see instead?

Kafka Kraft mode upgrade issue from 3.2.3 to 3.4.0

**Comment by bharathreddy901** [comment]
Hi @carrodher  - Giving more details about the issue.

1. First I have installed Bitnami Kafka Kraft mode with version 3.2.3 with 3 pods.
2. I have scaleup the pods from 3 to 5,its working fine.
3. Now the cluster consist of 5 pods.
4. Later I have upgraded the Kafka version 3.2.3 to 3.4.0,I am getting above error. 

Thanks.

**Comment by Mauraza** [comment]
Hi @bharathreddy901,

Could you add to your values `image.debug=true` to see if appears something more in the logs?

**Comment by bharathreddy901** [comment]
Hi @Mauraza - I have tried adding values image.debug=true, I am getting the same error message.

[2023-04-13 07:01:56,381] INFO [LogLoader partition=__cluster_metadata-0, dir=/bitnami/kafka/data] Producer state recovery took 13ms for snapshot load and 0ms for segment recovery from offset 11 (kafka.log.UnifiedLog$)
[2023-04-13 07:01:56,481] INFO [raft-expiration-reaper]: Starting (kafka.raft.TimingWheelExpirationService$ExpiredOperationReaper)
[2023-04-13 07:01:56,684] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.IllegalStateException: Configured voter set: [0, 1, 2, 3, 4] is different from the voter set read from the state file: [0, 1, 2]. Check if the quorum configuration is up to date, or wipe out the local state file if necessary
        at org.apache.kafka.raft.QuorumState.initialize(QuorumState.java:132)
        at org.apache.kafka.raft.KafkaRaftClient.initialize(KafkaRaftClient.java:364)
        at kafka.raft.KafkaRaftManager.buildRaftClient(RaftManager.scala:203)

**Comment by Mauraza** [comment]
Hi @bharathreddy901,

Could you share the command to upgrade? Did you pass the values with the new number of replicas?

**Comment by bharathreddy901** [comment]
Hi @Mauraza - Please find the command for upgrade.

helm upgrade kafka ./ -n kraft

I am passing number of replicas in values.yaml for replicaCount.

Thanks

**Comment by Mauraza** [comment]
Hi @bharathreddy901,

When you run the upgrade you have more replicaCount that appears in the values.yaml. Please update this value in the file and then run the command.

`helm upgrade kafka bitnami/kafka -n kraft -f values.yaml`
