### ISSUE TITLE
[bitnami/mariadb-galera] Bootstrap node ip is declared twice for pod and host

### ISSUE THREAD

**Issue by iomarcovalente** [bitnami/charts#1601]
**Which chart**:

mariadb-galera v0.5.1

**Description**

After creating a 3 nodes cluster ( will refer to them as node0,node1,node2 from here onwards) with default configuration using the chart, the galera cluster started fine and all nodes joined the cluster, but I get on node1 and node2 a connection error:

```
2019-11-14 15:07:32 0 [Note] WSREP: (3acce673, 'tcp://0.0.0.0:4567') reconnecting to 5ef0bf71 (tcp://10.119.10.189:4567), attempt 30
2019-11-14 15:08:17 0 [Note] WSREP: (3acce673, 'tcp://0.0.0.0:4567') reconnecting to 5ef0bf71 (tcp://10.119.10.189:4567), attempt 60
```

this would go on forever. 

Now, I noticed that when message relay is starting up it prints this out on both nodes  1 and 2:

```
2019-11-14 15:06:44 0 [Note] WSREP: (3acce673, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers: tcp://10.119.10.189:4567 
2019-11-14 15:06:44 0 [Note] WSREP: declaring 20c1150a at tcp://100.70.186.108:4567 stable
2019-11-14 15:06:44 0 [Note] WSREP: declaring 5ef0bf71 at tcp://10.119.10.189:4567 stable
```

Interestingly, both IPs `100.70.186.108` and `10.119.10.189` belong to node 0 the first is the `podIP` whilst the second is the `hostIP` where the pod is deployed.

On all pods I have the following variables returned:
```
+--------------------------+----------------------------------------------------------+
| Variable_name            | Value                                                    |
+--------------------------+----------------------------------------------------------+
| wsrep_incoming_addresses | 100.70.186.108:3306,100.70.74.137:3306,100.70.1.145:3306 |
+--------------------------+----------------------------------------------------------+
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 3     |
+--------------------+-------+
+-----------------------+----------------------------------------------------------------+
| Variable_name         | Value                                                          |
+-----------------------+----------------------------------------------------------------+
| wsrep_cluster_address | gcomm://ott-nft-mariadb-galera-headless.data.svc.cluster.local |
+-----------------------+----------------------------------------------------------------+
```

whilst on node0 `wsrep_cluster_address` is
```
+-----------------------+----------------------------------------------------------------+
| Variable_name         | Value                                                          |
+-----------------------+----------------------------------------------------------------+
| wsrep_cluster_address | gcomm://                                              |
+-----------------------+----------------------------------------------------------------+
```

so it seems that all is ok however, node1 and 2 still tries indefinitely to connect to that wrongly declared IP: `10.119.10.189`.

I have few questions with regards to this:
- why both podIP and hostIP where declared?
- why hostIP is declared at all since its not defined anywhere in galera configuration?
- would usign auto-eviction help in this scenario?
- what does `message relay` do and can it be disabled?

I have tried to investigate and understand when is that the 2 peers which are meant to connect to the bootstrap node gather the node data but without luck.

**Steps to reproduce the issue:**

1. Deploy helm chart with default settings

**Describe the results you received:**

Two bootstrap node IPs got declared
```
2019-11-14 15:06:44 0 [Note] WSREP: declaring 20c1150a at tcp://100.70.186.108:4567 stable
2019-11-14 15:06:44 0 [Note] WSREP: declaring 3acce673 at tcp://10.119.10.189:4567 stable
```
and as a result the paired nodes could not connect to the wrong IP `10.119.10.189`  since it was the hostIP

**Describe the results you expected:**

I expected only one IP to be declared

```
2019-11-14 15:06:44 0 [Note] WSREP: declaring 20c1150a at tcp://100.70.186.108:4567 stable
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-afa464", GitCommit:"afa464ce9760bd08a53a207f505b133b93366ea3", GitTreeState:"clean", BuildDate:"2019-10-22T21:42:57Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by iomarcovalente** [comment]
Also it seems that deleting node0's pod resulted in the other nodes to stop attempting to reconnect to node0 wrong address.

**Comment by andresbono** [comment]
Hi @iomarcovalente, thanks for the detailed information. We assumed that you just did

```
helm install bitnami/mariadb-galera
```

to deploy the chart. Is that correct?

We did that but we couldn't see the errors that you have reported in the logs. Can you tell us more about the Kubernetes cluster where you are testing this solution?

**Comment by iomarcovalente** [comment]
This issue was due to ip masquerading that we perform within our cluster. Solved

**Comment by andresbono** [comment]
Thanks for letting us know, @iomarcovalente.
