### ISSUE TITLE
[bitnami/mastodon] Mastodon's "psql wait for" fails if password has invalid characters

### ISSUE THREAD

**Issue by jilleJr** [bitnami/charts#16022]
### Name and Version

bitnami/mastodon 1.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Try deploy Bitnami's Mastodon chart: https://github.com/bitnami/charts/blob/main/bitnami/mastodon/README.md
2. Use a Postgres password with invalid characters, e.g one that includes a slash `/`

### Are you using any custom parameters or values?

Nothing out of the ordinary. I am running Postgres using the chart's dependency.

### What is the expected behavior?

The init containers start up successfully

### What do you see instead?

I was getting misleading errors. With `image.debug=true`, I saw the following messages:

```console
$ kubectl logs mastodon-streaming-6dd55646db-xh5kj wait-for-db
mastodon 16:55:03.09 INFO  ==> Waiting for PostgreSQL to be ready at mastodon-postgresql:5432/bitnami_mastodon
mastodon 16:55:03.09 DEBUG ==> psql: error: local user with ID 1001 does not exist
mastodon 16:55:08.11 DEBUG ==> psql: error: local user with ID 1001 does not exist
mastodon 16:55:13.11 DEBUG ==> psql: error: local user with ID 1001 does not exist
mastodon 16:55:18.13 DEBUG ==> psql: error: local user with ID 1001 does not exist
mastodon 16:55:23.14 DEBUG ==> psql: error: local user with ID 1001 does not exist
etc.
```

This was because it failed to parse the connection string, and then didn't have a valid user that is otherwise given by the connection string

### Additional information

This took me some digging, and eventually I figured it out. But in the process, I made this change which heavily improved the error message I got from `psql`:

```yaml
web:
  containerSecurityContext:
    runAsUser: 999 # mastodon user
```

What's missing in the script is some URL encoding, right here:

https://github.com/bitnami/charts/blob/90af4d3ec7985940143bf3b2ea805fb8872c0086/bitnami/mastodon/templates/_helpers.tpl#L554-L556

Or some note in the docs, as well as some comments in the `values.yaml`, that makes it very clear that you should not have special characters in the password.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. It seems clear that we should improve the container to perform some encoding in the connection string. I will forward this to the engineering team. However, if you want to speed up the process, would you like to submit a PR adding the feature in libmastodon.sh?

**Comment by jilleJr** [comment]
@javsalgar how would you envision that? Something like a `urlencode` function added, that is then called by this init script?

**Comment by javsalgar** [comment]
Hi!

We tried in the past escaping characters in bash but I'm not sure if we covered all the cases.
