### ISSUE TITLE
Unable to set consumer_timeout on k8s bitnami/rabbitmq

### ISSUE THREAD

**Issue by tridelt** [bitnami/charts#16025]
### Name and Version

helm/rabbitmq-11.13.0.tgz

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.helm install with rancher

### Are you using any custom parameters or values?

`helm upgrade --set rabbitmq.advancedConfiguration="consumer_timeout=100000" --namespace=cm queue bitnami/rabbitmq`

### What is the expected behavior?

Reduce the `consumer_timeout` to 100000ms.

### What do you see instead?

Instead, the `consumer_timeout` stays at the default value of 30 min.

### Additional information
There are plenty of [posts](https://stackoverflow.com/questions/53374144/rabbitmq-ack-timeout/67581599#67581599) on how to adjust it if you run rabbitmq on `localhost` or in a docker-container but I cannot configure the consumer_timeout in the bitnami/rabbitmq helm-chart deployment.

I would be super thankful to learn how to set the "consumer_timeout" correctly.
I have spent hours trying and would be very grateful for an answer.

thank you : )

**Comment by CeliaGMqrz** [comment]
Hi @tridelt, Great! 

The result should be similar. You can use the `configuration` parameter for rabbitmq's own features, instead of `extraConfiguration`, which is used to add additional configuration for other purposes. In this case, I think both options can be correct.

We will move this case as solved then, Thanks for your feedback!

**Comment by tridelt** [comment]
@CeliaGMqrz thank you! : )

**Comment by Himanshuban007** [comment]
> Hi @tridelt, Thanks for your comments! You can set this configuration through the extraConfiguration parameter in the values.yaml file.
> 
> ```miniyaml
> ## @param extraConfiguration [string] Configuration file content: extra configuration to be appended to RabbitMQ configuration
> ## Use this instead of `configuration` to add more configuration
> ## Do not use simultaneously with `extraConfigurationExistingSecret`
> ##
> extraConfiguration: |-
>   consumer_timeout = 10000
> ```
> 
> Check the configuration:
> 
> ```
> $ rabbitmqctl eval 'application:get_env(rabbit, consumer_timeout).'
> {ok,10000}
> $ cat /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf | grep 'consumer'
> consumer_timeout = 10000
> ```
> 
> We welcome your feedback :)

Where can we find the values.yaml file
