### ISSUE TITLE
[bitnami/matomo] Method for extension installation of apache php container

### ISSUE THREAD

**Issue by AH-dark** [bitnami/charts#16030]
### Name and Version

bitnami/matomo 0.2.30

### What is the problem this feature will solve?

Allow users to install PHP extensions.

### What is the feature you are proposing to solve the problem?

The Queued Tracking provided by Matomo needs to install the Redis extension. The default container does not provide the Redis extension, but Chart also has no convenient installation method.

### What alternatives have you considered?

I can modify the official container directly, but it is not conducive to subsequent maintenance.

**Comment by AH-dark** [comment]
Matomo also relies on GeoIP for user IP judgment, but the container does not provide this extension.

**Comment by javsalgar** [comment]
Hi,

In this sense, we try to be conservative of the number of extensions we add to PHP by default. If there is a use case that requires a specific extension, you may need to create your own fork.

About the geoIP case, could you show the error that Matomo returns because of the missing extension?

**Comment by dcoder2099** [comment]
Would it be possible to install additional packages using `install_packages` using an init container? What might that look like?

**Comment by javsalgar** [comment]
Hi, you could use the initContainers section to download the required extension and mount it later on in the container. You would need to use extraVolumes and extraVolumeMounts to do so.
