### ISSUE TITLE
[bitnami/grafana-loki] Add missing version, kind to volumeClaimTemplates

### ISSUE THREAD

**Issue by Yaytay** [bitnami/charts#16048]
### Name and Version

bitnami/grafana-loki

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy grafana-loki via ArgoCD, the loki-ingester and loki-querier StatefulSets remain out of synch because of the discrepancy in the definition of the volumeClaimTemplates.

### Are you using any custom parameters or values?

Can be provided if wanted, but looking at the template it doesn't provide any option for specifying the kind & version.

### What is the expected behavior?

In ArgoCD the deployed manifest should match the desired manifest.

### What do you see instead?

The live manifest contains:
```yaml
volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
```

but the desired manifest only has:
```yaml
volumeClaimTemplates:
  - metadata:
```

### Additional information

This is the equivalent of #15943, but for grafana-loki.

**Comment by Yaytay** [comment]
Let me know if you'd like a PR from this repo https://github.com/Yaytay/charts/tree/16048.
If so, please tell me what I should do with the chart version (nothing, or bump the patch version?).
Thanks.

**Comment by javsalgar** [comment]
Hi,

Thank you so much! Yes! Contributions are welcome :D In this case, it should be a patch as it is not adding a feature nor a breaking change.

**Comment by Yaytay** [comment]
Please don't close this whilst the accompanying PR is being discussed.
The last comment on that from @marcosbc leaves some hope that it might still be accepted.
If not then grafana-loki is incompatible with argocd and I won't be able to use it :(
