### ISSUE TITLE
[bitnami/mongodb-sharded] Primary Node crash in mongodb-sharded

### ISSUE THREAD

**Issue by jshcrowthe** [bitnami/charts#16054]
### Name and Version

bitnami/mongodb-sharded 6.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is the same bug that was fixed in #9387 but the fix is not available for mongodb-sharded. In the event of a primary node crash and subsequent data deletion the primary node will not check for an existing replicaset and will instead instantiate a new one.

The same fix needs to be ported to mongodb-sharded I monkeypatched a custom entrypoint using effectively the same code introduced there and it seems to be working.

### What is the expected behavior?

If the `0` crashes in a sharded setup if the PVC and pod are deleted it should instantiate as a secondary and replicate from the current primary.

### What do you see instead?

If the `0` crashes and the PVC and pod are deleted a new replicaset is created.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. As it is a matter of porting an existing fix, would you like to submit a PR?
