### ISSUE TITLE
[bitnami/phpmyadmin] 5.1.3 database export error

### ISSUE THREAD

**Issue by MFurminsky** [bitnami/charts#16056]
### Name and Version

bitnami/Redmine 5.0.0 for Windows

### What architecture are you using?

amd64

### What steps will reproduce the bug?

error on simple database export

### Are you using any custom parameters or values?

No

### What is the expected behavior?

base douwnload successful

### What do you see instead?

Failed - Network error

### Additional information

https://github.com/phpmyadmin/phpmyadmin/issues/17461

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the ticket. Do you have the steps to reproduce the issue in a clean Redmine instance?

**Comment by MFurminsky** [comment]
I can't reproduce the problem. googled this issue and updated phpMyAdmyn to latest version 5.2.1. There were no problems.

**Comment by javsalgar** [comment]
Hi!

So the way to fix the issue is simply to update to a newer phpmyadmin version, right?

**Comment by MFurminsky** [comment]
Yes. Exactly.

  
>Вторник, 18 апреля 2023, 11:17 +03:00 от Javier J. Salmerón-García ***@***.***>:
> 
> 
>Hi!
>So the way to fix the issue is simply to update to a newer phpmyadmin version, right?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <bitnami/charts/issues/16056/1512658756 @ github . com> 
 
 
С уважением,
Фурминский Михаил.
+7 (903) 66-907-99
