### ISSUE TITLE
Caching times on bitnami wordpress stack

### ISSUE THREAD

**Issue by xgaibtcgd** [bitnami/charts#16052]
### Name and Version

bitnami/wordpress

### What architecture are you using?

amd64

### What steps will reproduce the bug?

My pages seem to take some time to automatically clear the cache.  I'm bypassing my CDN (verified that) and it must be something locally configured on the server where I can't get updated pages.

This is happening outside of my wordpress site, so I know its not a plugin. Must be something in my web server config?

It seems like after 24 hours i refresh the page and everything is fine.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

When the page is refreshed i see the changes.

### What do you see instead?

The old page.  But if i do nothing, go to bed and show up the next morning and hit refresh, the prolblem seems to resolve itself.

### Additional information
These were commenteded out in httpd.conf
#Include conf/pagespeed.conf
#Include conf/pagespeed_libraries.conf

_No response_

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami WordPress container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
