### ISSUE TITLE
Cannot install enterprise edition of odoo

### ISSUE THREAD

**Issue by frshub-support** [bitnami/charts#16078]
### Name and Version

bitnami/odoo:16

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am following the official Odoo docs to install Enterprise edition as described here: https://www.odoo.com/documentation/16.0/administration/maintain/enterprise.html

I have downloaded odoo_16.0+e.latest_all.deb Enterprise installer and prepared a Dockerfile like this:

```dockerfile
FROM bitnami/odoo

ADD odoo_16.0+e.latest_all.deb .
ADD --chmod=755 run.sh /opt/bitnami/scripts/odoo/run.sh
RUN apt update \
    && apt install -y ./odoo_16.0+e.latest_all.deb
```

file `run.sh` is copied from the original image with cli argument to odoo binary added: `-i web_enterprise`, just like in the official upgrade documentation.

After attaching to the container I can see the argument is passed all right to the odoo binary:
```
root@odoo-staging-566f6476b-lrwg5:/# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
odoo         1     0  1 06:07 ?        00:00:05 /opt/bitnami/odoo/venv/bin/python /opt/bitnami/odoo/bin/odoo -i web_enterprise --config /opt/bitnami/odoo/conf/odoo.conf
```

### Are you using any custom parameters or values?

As mentioned above I use these parameters in values.yaml:

```yaml
image:
  registry: my-registry.azurecr.io
  repository: odoo
  tag: latest
```

### What is the expected behavior?

When accessing odoo GUI I expect that at the bottom of the page I see "Enterprise Edition"

### What do you see instead?

When accessing odoo GUI at the bottom of the page I see "Community Edition"

### Additional information

https://github.com/bitnami/charts/issues/1250

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
