### ISSUE TITLE
Kubernetes Operator

### ISSUE THREAD

**Issue by brogger71** [bitnami/charts#1607]
**Which chart**:

Magento in general

**Description**

Are there any plans to provide a Kubernetes Operator? According to that https://blog.openshift.com/build-kubernetes-operators-from-helm-charts-in-5-steps/ link it shouldn't be a big thing.

**Comment by carrodher** [comment]
Hi, it is something that is not in our roadmap in the short term, by the way, did you try to build this chart following the article instructions?

**Comment by brogger71** [comment]
Hi, it will not run under OpenShift as long as the Container needs to be run as root. I will try to do that as soon as the magento image is available without the need to run it as root.

**Comment by carrodher** [comment]
Yeah, that is true, OpenShift requires non-root images. At this moment some Bitnami container images need to be moved to a non-root configuration, that it's something we have in mind but there are no immediate plans to work on it.
Other web applications like WordPress or Ghost are already non-root (apart from all the infrastructure images like Nginx, Fluentd, Kafka, Zookeeper, etc), just in case you are interested on trying the operator sdk using one of those charts

**Comment by Rkbhasan1** [comment]
Thanks.
