### ISSUE TITLE
[bitnami/wordpress] Support for ReadWriteOnce access mode

### ISSUE THREAD

**Issue by bellini666** [bitnami/charts#16079]
### Name and Version

bitnami/wordpress:15.3.5

### What is the problem this feature will solve?

There are some k8s providers that doesn't support ReadWriteMany. DigitalOcean is one of them: https://docs.digitalocean.com/products/kubernetes/how-to/add-volumes/

### What is the feature you are proposing to solve the problem?

Add support for `ReadWriteOnce` so that the chart can be properly updated, even if that means we can't scale it to more than one node or even the update strategy needs to be `Recreate`

### What alternatives have you considered?

None

**Comment by javsalgar** [comment]
Hi!

If you are not scaling, you should be able to use ReadWriteOnce volumes. Did you try deploying?

**Comment by bellini666** [comment]
> Hi!
> 
> If you are not scaling, you should be able to use ReadWriteOnce volumes. Did you try deploying?

Yes, it is working fine. But I have issues when upgrading
I changed the upgrade strategy for wordpress to recreate but it still tries to attach the new pod before really finishing the previous one.

And mariadb has no option to change its upgrade strategy

**Comment by javsalgar** [comment]
Hi,

Our advice is to play with the affinity settings to ensure that the upgrading pod gets scheduled to the same node. We have some presets that should ensure it.

**Comment by bellini666** [comment]
> Hi,
> 
> Our advice is to play with the affinity settings to ensure that the upgrading pod gets scheduled to the same node. We have some presets that should ensure it.

Seems like a nice solution! Could you point me to where that preset example? I'm far from being an expert in k8s, so I really could use some examples to help me get started
