### ISSUE TITLE
Database not created with disabled authentication

### ISSUE THREAD

**Issue by marekmrowca** [bitnami/charts#1609]
**Which chart**:

influxdb 0.2.0

**Description**

When auth is disabled database is not created.

**Steps to reproduce the issue:**

1. set `authEnabled: false`
2. deploy helm chart
3. Connect to influxdb as suggested by the output message:

"To connect to your database run the following commands:
    kubectl run huge-power-influxdb-client --rm --tty -i --restart='Never' --namespace default  \
        --image docker.io/bitnami/influxdb:1.7.9-debian-9-r0 \
        --command -- influx -host huge-power-influxdb -port 8086"

**Describe the results you received:**
database is not visible:
there is only _internal db,  I need to create "my_database" manually.

**Comment by alemorcuq** [comment]
Hi, @marekmrowca.

The database is only created when the authentication is on. You can see the relevant code here https://github.com/bitnami/bitnami-docker-influxdb/blob/1de7c4088cdf42f05ba1f90f726e1c8bb2b092c5/1/debian-9/rootfs/libinfluxdb.sh#L431

You can connect to Influx and create your own database with `CREATE DATABASE mydatabase`.
