### ISSUE TITLE
[bitnami/schema-registry] kafka-avro-console-producer

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#16105]
### Name and Version

bitnami/schema-registry

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team - I have installed schema-registry newly along with Kafka. Both Kafka, zookeeper & schema-registry services are running fine. I have tried kafka-avro-console-producer to produce the messages I am getting below exception.

I am using below command.
```
kafka-avro-console-producer \
  --broker-list kafka.schema.svc.cluster.local:9092 --topic domain \
  --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
```
Error Message :
![image](https://user-images.githubusercontent.com/96808632/232710104-c3a5e75f-2faf-45a8-8225-224db94aa5f0.png)

### Are you using any custom parameters or values?

No

### What is the expected behavior?

After running Kafka-avro-console-producer, messages needs to be produced.

### What do you see instead?
```
org.apache.kafka.common.errors.SerializationException: Error deserializing json  to Avro of schema {"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}
Caused by: java.io.EOFException
```

**Comment by rafariossaa** [comment]
Hi,
  I am not an expert in kafka, but for the error message I would say that the message is not well formed for any reason. As the chart is working, I would suggest you to post this question in kafka forums, I think you would get better help there.
  Please, don't hesitate to come back and share your findings.

**Comment by MKarkowski4** [comment]
Same issue here. Do you have a solution @bharathreddy901
