### ISSUE TITLE
Skip secret.yaml creation if user defines matomoSkipInstall=true

### ISSUE THREAD

**Issue by bebosudo** [bitnami/charts#16114]
### Name and Version

bitnami/matomo:0.2.31

### What is the problem this feature will solve?

Currently defining matomoSkipInstall to true correctly skips the matomo setup, which is useful if the database has already been populated and we don't know the password/we don't want to store the password in clear text in the Helm values file.

The secret.yaml file is generated to store either the smtp password or the first password to access the bitnami dashboard, or both:
https://github.com/bitnami/charts/blob/2dc34dcde97e388167abbf199521dee1f92c2eca/bitnami/matomo/templates/secrets.yaml#L16-L18

In the case where the db is already populated and we want to skip the wizard, a password is created anyway, and helm sets it to a random value.
This causes tools like ArgoCD to see matomo as out-of-sync, because helm updates the password every time it's executed if not set, even though it's not used since we skip the wizard.

### What is the feature you are proposing to solve the problem?

I'd add a further condition on the if clause, from the current https://github.com/bitnami/charts/blob/2dc34dcde97e388167abbf199521dee1f92c2eca/bitnami/matomo/templates/secrets.yaml#L16-L18

to
```yaml
  {{- if and (not .Values.existingSecret) (not .Values.matomoSkipInstall) }}
  matomo-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "matomo-password" "providedValues" (list "matomoPassword") "context" $) }}
  {{- end }}
```

And the top condition should be changed too to:
```yaml
{{- if or (and (not .Values.existingSecret) (not .Values.matomoSkipInstall)) (and (not .Values.smtpExistingSecret) .Values.smtpPassword) }}
```

### What alternatives have you considered?

For now, I set a placeholder text in the `matomoPassword` value, and that works too, since we're skipping the wizard and the real password is now in the db.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
