### ISSUE TITLE
[bitnami/wordpress] Add php redis extension

### ISSUE THREAD

**Issue by madalinignisca** [bitnami/charts#16124]
### Name and Version

bitnami/wordpress latest

### What is the problem this feature will solve?

As a WordPress administrator, I would like to use [WP Redis](https://wordpress.org/plugins/wp-redis/) plugin as an alternative for object caching. Adding redis extension to the wordpress image will allow this popular plugin to be used, and also other plugins that use redis and not memcached.

Not everybody wants to use W3 Total Cache, and some of us consider redis to be better than memcache.

### What is the feature you are proposing to solve the problem?

Add redis extension.

**Comment by madalinignisca** [comment]
@CeliaGMqrz I do understand that and do apreciate it.

I am confused on your images as I don't know from which Dockerfile are built.

I think a lot of us could contribute to them.

Adding redis to php is something I'd tackle in a few minutes, so on my side, it's not hard to extend from your current image and add redis, but it's not that efficient and is not helping the others in the community.

**Comment by CeliaGMqrz** [comment]
Thanks @madalinignisca. We appreciate your willingness to contribute. The Dockerfile file is [here](https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/Dockerfile). You can contribute by creating a PR. The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by carrodher** [comment]
Hi, after analyzing the suggestion, unfortunately, at this moment there is no bandwidth to work on this change. If you would like to contribute by creating a PR, the Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
