### ISSUE TITLE
[bitnami/common] Should pod labels include `helm.sh/chart` label?

### ISSUE THREAD

**Issue by MikaelElkiaer** [bitnami/charts#16125]
### Name and Version

bitnami/common 2.2.4

### What is the problem this feature will solve?

I noticed when using `common.labels.standard` in both workload labels and spec labels, it will cause a re-deployment whenever the chart version is upgraded - even when the workload itself hasn't changed.
This is caused by the change of the `helm.sh/chart` label, which value will change along with the chart version.

### What is the feature you are proposing to solve the problem?

If I am misunderstanding anything, no solution is needed.

However, if the described "problem" above makes sense, I suggest creating another template `common.labels.pod`, without the `helm.sh/chart` label, to be used for pod spec labels, while the former template can still be used for workloads, services, etc.

**Comment by Mauraza** [comment]
Hi @MikaelElkiaer,

We are open to contributions! You can create a PR with that change and we will be happy to review it.

**Comment by MikaelElkiaer** [comment]
> Hi @MikaelElkiaer,
> 
> We are open to contributions! You can create a PR with that change and we will be happy to review it. 

Sure, I could contribute.

But first up is simply a question whether something should be changed.
