### ISSUE TITLE
Document or lower default  wsrep_slave_threads=4 to 1

### ISSUE THREAD

**Issue by randywatson1979** [bitnami/charts#16126]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

When deployed with `wsrep_slave_threads=4` a 3 node cluster some nodes will fail with wsrep errors in the following situation: 

OpenShift admin had set a default limit of 500 mCPU per pod if the user did not specify CPU resource request/limit in values.yaml.

### What is the feature you are proposing to solve the problem?

Set the default value of `wsrep_slave_threads` to 1 and/or clarify the relation of wsrep_slave_threads to CPU core  in README.md or as comment in values.yaml at `mariadbConfiguration`.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR adding this explanation to the README file? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
