### ISSUE TITLE
Typo in etcd chart for 'statefulset.updateStrategy'

### ISSUE THREAD

**Issue by sboschman** [bitnami/charts#1613]
The etcd statefulset template refers to `updateStratey` instead of `updateStrategy`:
https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L19

**Comment by juan131** [comment]
Hi @sboschman 

Thanks for reporting it. Closing this issue since it was fixed at https://github.com/bitnami/charts/pull/1616
