### ISSUE TITLE
can't Access supabase studio/Kong when setting Kong to ClusterIP

### ISSUE THREAD

**Issue by markbonfert** [bitnami/charts#16149]
### Name and Version

bitnami/supabase 0.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After installing the chart pods and services came up fine. But I can't access the application trough port forwarding...

### Are you using any custom parameters or values?

`helm install bitnami-supabase-hr --set kong.service.type=ClusterIP oci://registry-1.docker.io/bitnamicharts/supabase`

also tried

`helm install bitnami-supabase-hr --set kong.service.type=ClusterIP --set publicURL=127.0.0.1:8080 oci://registry-1.docker.io/bitnamicharts/supabase`

### What is the expected behavior?
```console
$ kubectl get svc
NAME                                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
bitnami-supabase-hr-auth            ClusterIP   10.3.1.161     <none>        80/TCP           16m
bitnami-supabase-hr-kong            ClusterIP   10.3.139.176   <none>        80/TCP,443/TCP   16m
bitnami-supabase-hr-meta            ClusterIP   10.3.53.11     <none>        80/TCP           16m
bitnami-supabase-hr-postgresql      ClusterIP   10.3.9.129     <none>        5432/TCP         16m
bitnami-supabase-hr-postgresql-hl   ClusterIP   None           <none>        5432/TCP         16m
bitnami-supabase-hr-realtime        ClusterIP   10.3.10.13     <none>        80/TCP           16m
bitnami-supabase-hr-rest            ClusterIP   10.3.244.54    <none>        80/TCP           16m
bitnami-supabase-hr-storage         ClusterIP   10.3.124.206   <none>        80/TCP           16m
bitnami-supabase-hr-studio          ClusterIP   10.3.188.80    <none>        80/TCP           16m

$ kubectl port-forward svc/bitnami-supabase-hr-kong 8080:80
Forwarding from 127.0.0.1:8080 -> 8000
Forwarding from [::1]:8080 -> 8000
Handling connection for 8080
Handling connection for 8080

$ kubectl port-forward svc/bitnami-supabase-hr-studio 8080:80
Forwarding from 127.0.0.1:8080 -> 3000
Forwarding from [::1]:8080 -> 3000
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080`
```
### What do you see instead?

Kong shows me "{"message":"no Route matched with those values"}". If I try to access the studio I get the /sign-in for a moment, then I get a redirect to /projects which shows me "Something went wrong
Sorry about that, please try again later or feel free to reach out to us if the problem persists."

**Comment by foogazy** [comment]
Hello @marcosbc, we actually encounter this error today as well. I tried to understand the issue but unfortunately everything seems find on the surface.

Things we have tried: 

- Separate Ingresses 
- Moving to base image "supabase/studio"
- Port forwarding 
- Setting LOG_LEVEL to debug for all pods
- checking browser console for errors

But unfortunately none of them return any error, it just simply states: "Something went wrong" and nothing else - no errors, nothing. 

I'm happy to help if anybody finds any issues that might have caused this.

**Comment by marcosbc** [comment]
@foogazy Could you clarify if you were able to get it working with any configuration? Or does it fail with everything that you have tried? Have you tried to deploy without any non-default configuration (apart from the chart defaults) to ensure that it is not the cause?

**Comment by markbonfert** [comment]
@marcosbc i did try to declare ingresses, those in the chart as well some selfdefined getting the same result. I need the `--set kong.service.type=ClusterIP` for installation tough. In contrast to foogazy i didn't do a deep dive into the logs but couldn't see an error message in the studio or kong pod logs.

Can you give me any hint what the error message might relate to? The helm notes mention that api must be reachable as well so that the studio can be accessed. What would a setup without kong look like so i might be able to exclude kong as possible error. Is it enough to just portforward too the "rest" service?

**Comment by foogazy** [comment]
Hi @markbonfert @marcosbc,  So here's a base `values.yaml` I used to deploy:  

```yaml
kong:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: "supabase.example.com"
  extraEnvVars:
    - name: LOG_LEVEL
      value: error

```
It's important to note that I used `LOG_LEVEL` error for every service. Based on my cloud deployment, if kong service is `LoadBalancer`, things seem to be fine but as soon as it's `ClusterIP`, things stop working.

Some other things I tried: 

- Using the original "supabase/studio:latest" image
  - This gets rid of the issue but shows API incompatibility issues since it just shows `supabase.example.com/rest/v1` is 404 and is stuck on "Connecting to the Database..."
- Port forwarding just the studio
  -  Didn't work at all
- Manually setting these variables to public and cluster specific endpoints but none of them resolved anything: 
```
API_EXTERNAL_URL
SUPABASE_PUBLIC_URL
SUPABASE_REST_URL
STUDIO_PG_META_URL
SUPABASE_URL
```

but, if you guys find any possible cause, I'm happy to investigate further.

**Comment by markbonfert** [comment]
@foogazy 

if you use the charts ingress you will most probably run into the issues i described in issue 16151 (see above). You can give it another shot writing your own ingress rule... didnt help me though :(

**Comment by foogazy** [comment]
@markbonfert Yes indeed, I used separate ingresses but unfortunately the issue persists. :(

**Comment by marcosbc** [comment]
I see, so if the Ingress is still failing, let's see if anything changes after https://github.com/bitnami/charts/issues/16151 is resolved. It seems like the fix is already being investigated upon, so it shouldn't be long.

**Comment by rafacouto** [comment]
The PR #16951 was merged. Could you please test the new 0.3.6 version of _bitnami/supabase_ chart and validate this issue is fixed? Thank you.

**Comment by foogazy** [comment]
> The PR #16951 was merged. Could you please test the new 0.3.6 version of _bitnami/supabase_ chart and validate this issue is fixed? Thank you.

Can confirm, thank you!
