### ISSUE TITLE
postgresql chart's `serviceBindings.enable` option generates secret with incorrect key name

### ISSUE THREAD

**Issue by p-ssanders** [bitnami/charts#16145]
### Name and Version

bitnami/postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?

1. In kubernetes
2. With `serviceBindings.enabled: true` in the values.yaml file
3. Run `helm install postgresql bitnami/postgresql -f values.yaml`
4. Observe a secret generated named `postgresql-svcbind-custom-user` of type `servicebinding.io/postgresql` with key `user`

### Are you using any custom parameters or values?

```yaml
global:
  postgresql:
    auth:
      username: my-user
      password: my-password
      database: my-database
serviceBindings:
  enabled: true
```

### What is the expected behavior?

Expected results:
1. Observe a secret generated named `postgresql-svcbind-custom-user` of type `servicebinding.io/postgresql` with key `username` per the Service Binding Specification for Kubernetes [Well-known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries)

### What do you see instead?

Actual Results:

1. Observe a secret generated named `postgresql-svcbind-custom-user` of type `servicebinding.io/postgresql` with key `user`

### Additional information

The impact is that this key cannot be consumed by service binding libraries, e.g.: spring-cloud-bindings, that expect to find the well-known secret entries. The secret must be manually modified to include a key `username`, or the library configured to consume the not-well-known key `user`.

**Comment by jotamartos** [comment]
Hi @p-ssanders,

Thank you for takin the time to report this. We are going to create a task on our side and work on updating all the charts affected by this. In the meantime, would you like to contribute by creating a PR to solve the issue in the PostgreSQL Chart? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jotamartos** [comment]
Hi @p-ssanders,

We updated the key in all the affected charts and they should be available soon. 

Thanks!
