### ISSUE TITLE
ingress for studio doesnt point to the studio svc

### ISSUE THREAD

**Issue by markbonfert** [bitnami/charts#16151]
### Name and Version

bitnami/supabase 0.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

set `studio.ingress: true` in the chart

### Are you using any custom parameters or values?

```yaml
  ingress:
    enabled: true
    pathType: ImplementationSpecific
    hostname: supabase.mydomain.com
    path: /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: k8s.mydomain.com
      external-dns.alpha.kubernetes.io/ttl: "120"
```

### What is the expected behavior?

```yaml
     - host: supabase.mydomain.com
      http:
        paths:
        - backend:
            service:
              **name: bitnami-supabase-hr-studio**
```

### What do you see instead?

```yaml
$ kubectl get ing -o yaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: k8s,mydomain.com
      external-dns.alpha.kubernetes.io/ttl: "120"
      meta.helm.sh/release-name: bitnami-supabase-hr
      meta.helm.sh/release-namespace:mynamespace
    creationTimestamp: "2023-04-20T19:49:10Z"
    generation: 4
    labels:
      app.kubernetes.io/component: studio
      app.kubernetes.io/instance: bitnami-supabase-hr
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: supabase
      app.kubernetes.io/part-of: supabase
      helm.sh/chart: supabase-0.1.5
      helm.toolkit.fluxcd.io/name: bitnami-supabase-hr
      helm.toolkit.fluxcd.io/namespace: mynamespace
    name: bitnami-supabase-hr
    namespace: mynamespace
    resourceVersion: "8041664287"
    uid: b10bc53c-0964-4836-a99d-e85b77aeac4b
  spec:
    ingressClassName: traefik-ingress
    rules:
    - host: supabase.mydomain.com
      http:
        paths:
        - backend:
            service:
              name: **bitnami-supabase-hr**
              port:
                name: http
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - supabase.mydomain.com
      secretName: supabase.mydomain.com-tls
  status:
    loadBalancer: {}
```

**Comment by dgomezleon** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by markbonfert** [comment]
> Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

i am kinda new to k8s and deploying helm charts. Writing them is kinda out of my league atm :(

**Comment by dgomezleon** [comment]
Hi @markbonfert ,

Don't worry. We have created a task to fix it :) .

**Comment by jsmueller7** [comment]
> Hi @markbonfert ,
> 
> Don't worry. We have created a task to fix it :) .

As far as I can see: You have to modify `templates/studio/ingress.yaml`. In the lines 5 and 38 replace `common.names.fullname` with `supabase.studio.fullname`.
