### ISSUE TITLE
[bitnami/mysql] why  slow_query_log=1 in  values.yaml not effect 

### ISSUE THREAD

**Issue by leon0204** [bitnami/charts#16154]
### Name and Version

bitnami/mysql  9.3.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. `helm install mysql-8 bitnami/mysql -f values.yaml`
2. `kubectl exec -it  mysql-8-primary-0 bash`
3.  all the other setting is fine but  
 ```
cat /opt/bitnami/mysql/conf /my.cnf
slow_query_log=1 is ok 

mysql> show variables like '%slow%';

| slow_query_log              | OFF                                |
```

the values.yaml change in the `/opt/bitnami/mysql/conf /my.cnf`, but no effect 

### What do you see instead?
```
mysql> show variables like '%slow%';
+-----------------------------+------------------------------------+
| Variable_name               | Value                              |
+-----------------------------+------------------------------------+
| log_slow_admin_statements   | OFF                                |
| log_slow_extra              | OFF                                |
| log_slow_replica_statements | OFF                                |
| log_slow_slave_statements   | OFF                                |
| slow_launch_time            | 2                                  |
| slow_query_log              | OFF                                |
| slow_query_log_file         | /opt/bitnami/mysql/logs/mysqld.log |
+-----------------------------+------------------------------------+
```
why 
```
| slow_query_log              | OFF                                |
```

**Comment by leon0204** [comment]
i enter the container ,the file changed ,but the mysql show variables cant effect .

**Comment by aoterolorenzo** [comment]
Hi @leon0204,

Could you provide the `values.yaml` you're using?

**Comment by leon0204** [comment]
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "csi-rbd-sc-hdd"

architecture: replication



auth:

  rootPassword: "xxxxxxx"





primary:

  name: primary

  command: []
  
  args: []

  lifecycleHooks: {}

  hostAliases: []

  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=1
    slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
    long_query_time=10.0

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid

**Comment by aoterolorenzo** [comment]
Just to be sure: Are you trying on a completely fresh install? It may be possible to be having some persistence where due an initial config parameters slow_query_log is set to 0. I know it would be pretty weird since you are accessing directly to the config file inside the pod, but I think that is a thing we would need to check

**Comment by aoterolorenzo** [comment]
Let's let the team take a deeper look to solve this. I will create an internal task for it. We will reach back here as soon we can.

**Comment by aoterolorenzo** [comment]
Hi @kfkawalec 

Seems the container has a `ENABLE_SLOW_QUERY` env var default to 0, and that mysql actually gives env vars preference so thats why using `slow_query_log=1` have not effect.
