### ISSUE TITLE
[bitnami/gitea] Gitea Load balancer installation causes SSH host keys to change, breaking SSH from clients to K3S cluster

### ISSUE THREAD

**Issue by GreNIX** [bitnami/charts#16187]
### Name and Version

bitnami/gitea 0.1.19

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Cluster info:

-  4 node Armbian arm64 cluster
- K3S version v1.25.4+k3s1
- No ingress controller installed

Steps to reproduce:
Helm install the gitea charts.  Terminate SSH connection to controlplane.  Attempt to log back in, receive error about host key having changed. The Gitea frontend is accessible, but nothing else works. Uninstalling the Gitea charts returns SSH access.

SSH is also broken to any of the worker nodes, with the same error.

### What is the expected behavior?

Gitea Helm charts not breaking SSH to K3S cluster.

### What do you see instead?

`@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:RdAbsE6tt4MoGARitTzpI+R/8qpU0AIPie2f1tv9i7I.
Please contact your system administrator.
Add correct host key in /Users/gm/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/gm/.ssh/known_hosts:34
Host key for microkube1 has changed and you have requested strict checking.
Host key verification failed.`

**Comment by corico44** [comment]
Hello @GreNIX,

Could you enable the `image.debug` parameter to see if we can get more information with the logs, please?

**Comment by mike12806** [comment]
@GreNIX did you find a solution to this? I’m seeing this behavior still unfortunately
