### ISSUE TITLE
Consider providing Cisco's Clamav HelmChart

### ISSUE THREAD

**Issue by nightswimmings** [bitnami/charts#16193]
### Name and Version

Cisco's clamav/clamav:1.0.1

### What is the problem this feature will solve?

Having a production-grade deployment of most famous opensource antivirus engine (docker clamav/clamav), useful to securize attachments and any other user input files in a web worklow

### What is the feature you are proposing to solve the problem?

Distributing a bitnami chart for clamav

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the product request. I will forward this to the team for evaluation.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
