### ISSUE TITLE
[bitnami/keycloak] chart does not set probe paths correctly if values.httpRelativePath is set

### ISSUE THREAD

**Issue by acidicX** [bitnami/charts#16197]
### Name and Version

bitnami/keycloak 14.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. in k8s 1.23, try to install the helm chart with value `httpRelativePath: /auth`
2. helm install fails because the probes fail to come up (HTTP 404)

### Are you using any custom parameters or values?

Everything as default, except values `httpRelativePath: /auth`

### What is the expected behavior?

If the value is set inside the helm chart, I would expect the probe to honor the new path as well and try to access everything behind `/auth` instead of the default path

### What do you see instead?

Probes come up with HTTP 404 because the path is wrong (`authrealms/master` instead of `/auth/authrealms/master`).

**Comment by CeliaGMqrz** [comment]
Hi @acidicX,

Thanks for your report.

It seems that there are changes after this [PR](https://github.com/bitnami/charts/pull/16183/files), could you try the latest version of the chart?

The path seems correct to me, correct me if I am wrong. I welcome your comments.

![keycloak](https://user-images.githubusercontent.com/61272496/234514671-cc96d328-b177-43a0-b45c-be5ca64b67e5.png)
