### ISSUE TITLE
[bitnami/kafka] Multus deployement for Kafka

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#16209]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi Team - Bitnami Kafka helm charts supports Multus Container Network Interface (CNI) plugin? to attach multiple network interfaces to Kafka pods.
Please share your thoughts.

I have seen Bitnami multus-cni charts not sure how to integrate this.https://github.com/bitnami/charts/tree/main/bitnami/multus-cni

https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html

Thanks.

### What do you see instead?

I could see only one IP

**Comment by javsalgar** [comment]
Hi,

Could you explain the steps you performed to deploy Kafka and Multus? Did you add any extra network interfaces?

**Comment by bharathreddy901** [comment]
Hi @javsalgar - I have created network-attachment-definitions for Kafka namespace, after that I am not sure what are the configuration changes to be made inside the values.yaml & statefulset.yaml.

![image](https://user-images.githubusercontent.com/96808632/234219055-333190bd-8b01-48ac-ba10-8c363e0fcac2.png).

![image](https://user-images.githubusercontent.com/96808632/234220663-6938849e-821b-491d-9fa5-29d27ccdc69d.png)

**Comment by javsalgar** [comment]
You would need to add annotations to the Kafka statefulset. See this example:

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.6/vmware-tanzu-kubernetes-grid-16/GUID-packages-cni-multus.html
