### ISSUE TITLE
[bitnami/moodle] Kubernetes helm chart bug, bitnami moodle not running at all

### ISSUE THREAD

**Issue by patrickk2000** [bitnami/charts#16200]
### Name and Version

bitnami/moodle

### What architecture are you using?

RKE on premises

### What steps will reproduce the bug?

1. I am using an RKE on prem cluster
2. Nothing allows bitnami moodle image to run, it keeps crashing and displaying in the logs that it is installing moodle via script with info log level and no additional error log level.
3. I tried the helm chart, it also failed at the same point.
4. Using docker compose it runs completely fine, but using RKE it does not run at all, which showcases that there is a bug from bitnami's side, we ran no custom values.yaml, we just installed the chart as it is, which is always failing, noting that we are using pgsql, which passes the connection test successfully (shows that log before moodle installation script)

### Are you using any custom parameters or values?

Nothing at all, it just runs via docker compose and not RKE, i've tried with custom deployment to run the container as root, which did not work, so i said to myself let's try bitnami moodle helm chart installation which also fails at the sake point.
The point of failure is bitnami moodle with kubernetes. Does not work at all.

### What is the expected behavior?

Fix bitnami moodle to operate with Kubernetes not alwas stuck in just 5 seconds after deployment on 6 restarts, and the number growing exponentially

### What do you see instead?

CrashLoopBackOff with no error logs, bitnami helm chart moodle with K8S

**Comment by javsalgar** [comment]
Hi,

Could you deploy the chart with `image.debug=true` to see if it provides more insight on the issue?

**Comment by patrickk2000** [comment]
Hello @javsalgar,  everything was tried, root priveleges, `debug=true` flag, nothing worked, all turnarounds were covered with no result, just try running bitnami/moodle on RKE, it will fail, as i tried on two separate RKE clusters with the same output

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by infinityonlinesolutions** [comment]
Having the same problem, the moodle pod keeps crashing and re-creating indefinitely, please help to resolve the problem.

**Comment by infinityonlinesolutions** [comment]
Here is an alternative Helm Chart which uses the Bitnami\Moodle Docker Image and it works! https://artifacthub.io/packages/helm/statcan/moodle

**Comment by carrodher** [comment]
It's weird since that chart you refer to was something that a random user pushed to ArtifactHub just copying the Bitnami one and it has not been updated for a long time, so in the end, it is just an old Bitnami chart.

**Comment by deba10106** [comment]
I keep getting the following error and moodle pod in crash loop. I've tried with both the mariadb as well as MySQLdb

`SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2026 (HY000): TLS/SSL error: self-signed certificate in certificate chain
moodle 16:58:59.57 ERROR ==> Could not connect to the database`
