### ISSUE TITLE
[bitnami/wordpress] Access all wordpress files

### ISSUE THREAD

**Issue by masoudei** [bitnami/charts#16207]
### Name and Version

bitnami/wordpress 15.3.2

### What is the problem this feature will solve?

Webmasters can not add custom files to the website's root or see error_log files and others.web site's

### What is the feature you are proposing to solve the problem?

Accessing to all files in root of web server www the the 

### What alternatives have you considered?

I think it would be a good idea to enable exposing or mapping all files in /opt/bitnami/wordpress into a persistent path: /bitnami/wordpress

**Comment by javsalgar** [comment]
Hi,

Thank you for the input! However, it is not clear to me if this is fully aligned with how containers and Kubernetes systems are expected to be used. Anyways, there is an env var called `WORDPRESS_DATA_TO_PERSIST` where you can specify the data you want to be persisted.

https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-11/rootfs/opt/bitnami/scripts/wordpress-env.sh#L118

There you could try setting it to `.` with the extraEnvVars value of the chart.

**Comment by masoudei** [comment]
Oh Great, It's working. How awesome you guys are!

Thank you so much.
So I'm gonna try to make a few issues!

Just one question. If Wordpress throws any error, the main container is not healthy anymore, We have a sidecar for filebrowser that has access to persistent volume, so users can edit files, it is exposed via an ingress. Is there any way to ignore probes for this sidecar's ingress? Or I am going the wrong way?

Also, how can we show error logs to a user in filebrowser , debug="true" ??

**Comment by javsalgar** [comment]
Hi,

You could use a separate service for the filebrowser so it is not affected by the probes.

**Comment by masoudei** [comment]
Yes , I am going to implement it as a separate service. but in the same chart . It seems sidecars not suitable for this use case.
Thank you

**Comment by masoudei** [comment]
Thanks again. it is done
