### ISSUE TITLE
[bitnami/harbor] update to harbor >= 2.8.0

### ISSUE THREAD

**Issue by florentinadolf** [bitnami/charts#16210]
### Name and Version

bitnami/harbor 16.4.8

### What is the problem this feature will solve?

https://github.com/goharbor/harbor/issues/15253

### What is the feature you are proposing to solve the problem?

Update the chart to install harbor >= 2.8.0. according to https://github.com/goharbor/harbor/issues/15253#issuecomment-1470874237 the fix is only present from this version on.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by muralib1** [comment]
Hi All,

Is this issue fixed in 2.8 version?. please confirm. currently we are at 2.6.1.
