### ISSUE TITLE
[bitnami/redis-cluster] older versions support

### ISSUE THREAD

**Issue by prawen** [bitnami/charts#16213]
### Name and Version

bitnami/redis-cluster 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello All. I'm new here. I guess, this is not a bug. I would like to use Redis 5 and Postgres 12 using Helm. But I don't see any options to do that. I tried overriding the tags, but it is not compatible with the chart version I guess. There is no releases section in this repo. And I don't see how to navigate to older releases to try out older versions of applications like Redis, postgres in my case.  Is it possible? Can someone please help? 

### What do you see instead?

Not able to view older releases.

**Comment by javsalgar** [comment]
Hi,

Which is the issue you found when overriding the tags? We don't officially support other branches in the chart but we would like to understand the issue.

**Comment by prawen** [comment]
Hello,

Sure. I tried below command. 

`helm install redis \
--set usePassword=false \
--set image.tag=5.0.14-debian-10-r172 \
oci://registry-1.docker.io/bitnamicharts/redis-cluster`

But the pods went to crashloop with below error

`redis-cluster 09:30:59.60 INFO  ==> Setting Redis config file
Changing old IP 192.168.242.126 by the new one 192.168.242.126
sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory`

**Comment by carrodher** [comment]
Modifying the bundled container images is something supported in the sense that you can do it by using `--set image.tag` as you rightly did, but it is not something tested since it is not possible to test all the combinations.
At this moment, what it's guaranteed to work and we provide support for is the specific combinations bundled in the same Helm chart as a package.

**Comment by StandardStudent** [comment]
@carrodher  i notice that tag redis-cluster/2.0.13 contains redis 5,  i tried to use that helm , but have same problem

**Comment by StandardStudent** [comment]
and also this problem
![image](https://github.com/user-attachments/assets/fcbfe058-9930-401a-a432-79e2b78c4777)
