### ISSUE TITLE
[bitnami/wordpress] WP Admin ignores K8s Ingress prefix

### ISSUE THREAD

**Issue by mountaindog** [bitnami/charts#16229]
### Name and Version

bitnani/wordpress:16.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Working in a staging environment. When accessing the Wordpress Admin area, I've noticed that the ingress rule using a Prefix, in my case, it's using "/wp(/|$)(.*)", gets dropped in the URL. This causes a 404 error on posts and links. Due to the constraints of the K8s cluster I am working with, it's necessary to use a Prefix. I understand this might be more of a Wordpress issue than Bitnani; perhaps there is a setting I am missing in the YAML file or not.  My Wordpress config does have Home and SiteURL using the prefix in the base URL. 

### Are you using any custom parameters or values?

I am using an Ingress rule with a ClusterIP. Using the standard values provided.

Ingress Rule:
`Ingress:
  annotations: {
    nginx.ingress.kubernetes.io/add-base-url: 'true',
    nginx.ingress.kubernetes.io/proxy-body-size: 25m,
    nginx.ingress.kubernetes.io/proxy-buffering: 'on',
    nginx.ingress.kubernetes.io/rewrite-target: /$2,
    nginx.ingress.kubernetes.io/use-regex: 'true'
  }
  apiVersion: ''
  enabled: true
  extraHosts: []
  extraPaths: []
  extraRules: []
  extraTls: []
  hostname: exmaple.com
  port: 80
  ingressClassName: 'nginx'
  path: /wp(/|$)(.*)
  pathType: Prefix
  secrets: []
  selfSigned: false
  tls: false
  tlsWwwPrefix: false`

### What is the expected behavior?

I expect the WP admin area to use the Ingress Prefix in its URLs.

### What do you see instead?

It drops the Ingress prefixes, which results in 404 errors. 

### Additional information

The web is full of makeshift workarounds for this issue. I would love to see a natural solution that does NOT involve hacking WP to death. I am certainly open to ideas and solutions.

**Comment by mountaindog** [comment]
Whoops. 
The web is full of makeshift workarounds for this issue. I would love to see a natural solution that does **not** involve hacking WP to death. I am certainly open to ideas and solutions.

**Comment by javsalgar** [comment]
Hi,

It seems to me that it is more of a WordPress / Ingress limitation rather than a Bitnami packaging issue. In any case, let's see if someone from the community can add their own insight for a proper solution.

**Comment by mountaindog** [comment]
To follow up on this... A working solution I came up with is the run WP in multisite mode. Certainly open to suggestions or improvements. Here are the changes listed: 

**Ingress Rules**
- Ingress Rule: Change the prefix from "/wp(/|$)(.*)" to "wp/" 
- Set reg-expression annotation to false; you can also remove it.
- Removed the rewrite annotation.

**Bitnami/Wordpress**
- Turned on multisite with subfolder option
- Set the DOMAIN_CURRENT_SITE to the host -- example.com (excluded the https://)
- Set the PATH_CURRENT_SITE to: / (default setting)
- Set the WP_SITEURL and WP_HOME to full URL with the ingress prefix: https://exmaple.com/wp
- Used this to set an htaccess file:
```
existingApacheConfigurationConfigMap:
  customPostInitScripts:
    enable-multisite.sh: |
      #!/bin/bash
      chmod +w /bitnami/wordpress/wp-config.php
      wp core multisite-install --url=example.com/wp--title="Welcome to the WordPress Multisite" --admin_user="you" --admin_password="test" --admin_email="you@example.com"
      cat /docker-entrypoint-init.d/.htaccess > /bitnami/wordpress/.htaccess
      chmod -w bitnami/wordpress/wp-config.php
    .htaccess: |
      <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteBase /wp/
      RewriteRule ^index\.php$ - [L]

      # Add a trailing slash to /wp-admin
      RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

      RewriteCond %{REQUEST_FILENAME} -f [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^ - [L]
      RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
      RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
      RewriteRule . index.php [L]
      </IfModule>
```
