### ISSUE TITLE
[bitnami/postgresql] Installing pglogical

### ISSUE THREAD

**Issue by apgapg** [bitnami/charts#16232]
### Name and Version

postgresql Helm chart

### What is the problem this feature will solve?

I am trying to host a read replicas of pg on kubernetes. My main database is on Azure Postgres. 
To enable replication we need to enable pglogical. But I am not able to find any docs to do so.

On using `postgresqlSharedPreloadLibraries: "pgaudit,pglogical"`, error occurs saying pglogical not found. 

### What is the feature you are proposing to solve the problem?

How can we install pglogical?

**Comment by javsalgar** [comment]
Hi,

I'm afraid that you may need to fork the bitnami/postgresql container and add build the plugin there. We try to be conservative with the amount of plugins we include in the image because of security concerns.

**Comment by apgapg** [comment]
OKay thanks. Is there a blog/doc regarding that, 
it would be helpful.
