### ISSUE TITLE
[bitnami/redis-cluster] Converting Helm chart to  Kube manifest and deploying is restarting the container

### ISSUE THREAD

**Issue by tapasudenia** [bitnami/charts#16230]
### Name and Version

[bitnami/redis] 7.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Convert the  helm chart to Kube manifest file using the Helm template.

`helm template bitnami/redis-cluster --values ./values.yaml > converted.yaml`
2. We have changes some labels, as per our need, that is the only change. The port numbers and other things we have kept it as it is
3. Now try and deploy this from Azure DevOps pipeline using the Kubernetes task / apply command.
4. The container continues to restarts.
5. We also tried to enable the Debug mode `BITNAMI_DEBUG` to true to see if we can get some extra information in the logs, but the logs seems clean. and I don't see any additional information with Debug set to true.
6. 
![image](https://user-images.githubusercontent.com/28840799/234379834-68798a2c-e390-45f5-80f0-6b73526b9d26.png)
7. The containers are terminating with exit Code 2
`
State:          Running
      Started:      Tue, 25 Apr 2023 12:13:17 -0700
    Last State:     Terminated
      Reason:       Error
     Exit Code:    2
`
8. There is no other useful information in the Events when I do kube pod describe
Please suggest how can we troubleshoot this.

Also, has anyone tried something like this, converting from Helm chart to Kubernetes Manifest yaml and trying to deploy?

Let me know if any other information I can share.

### Are you using any custom parameters or values?

Nope

### What is the expected behavior?

The pods should be deployed successfully and should not restart.

### What do you see instead?

Pods restarting and terminating with Exit Code 2

**Comment by tapasudenia** [comment]
This is the docker image we are using - docker.io/bitnami/redis-cluster:6.2.6-debian-10-r193, is this the stable one ?

**Comment by rafariossaa** [comment]
Hi,
  The current chart version `8.5.0` uses image: `docker.io/bitnami/redis-cluster:7.0.11-debian-11-r0`. Could you give it a try ?

**Comment by tapasudenia** [comment]
Ok I can try that
