### ISSUE TITLE
ServiceAccount reference a token that doesn't exist on k8s >= 1.24

### ISSUE THREAD

**Issue by felipeng** [bitnami/charts#16244]
### Name and Version

bitnami/rabbitmq 11.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install rabbitmq chart with default values on default namespace 
2. Run: `popeye -l error -n default`

### Are you using any custom parameters or values?

default values

### What is the expected behavior?

The SA should be created without referencing the token 

### What do you see instead?

popeye output:
```
  · infrastructure/rabbitmq...................................................................💥
    💥 [POP-304] References a secret "infrastructure/rabbitmq" which does not exist.
```
### Additional information

[On Kubernetes 1.24 there are no more Secrets (SA token) automatically created](https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0), which means the chart is creating the SA with a token reference that doesn't exist.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by felipeng** [comment]
It isn't need anymore, someon else [fixed](https://github.com/bitnami/charts/commit/6592de659b3cffad069f3a1f581cb78b3648ccdc), thanks
