### ISSUE TITLE
[bitnami/mongodb] Installing the bitnami/mongodb image through helm does not support ARM64, but the mongo official image does.

### ISSUE THREAD

**Issue by GeekDot** [bitnami/charts#16247]
### Name and Version

bitnami/mongodb:latest

### What is the problem this feature will solve?

Installing the bitnami/mongodb image through helm does not support ARM64, but the mongo official image does.

![image](https://user-images.githubusercontent.com/67632270/234747410-4b09862e-697b-4fa4-b7f9-ae1772e86ec0.png)
![image](https://user-images.githubusercontent.com/67632270/234747557-153207ee-50ab-46d1-aaef-c98da0ed79bb.png)
![image](https://user-images.githubusercontent.com/67632270/234747621-19ff2e4b-975a-42b7-bb1a-59470ec66a5d.png)

### What is the feature you are proposing to solve the problem?

Added bitnami/mongodb ARM64 image.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. We had issues adding ARM support in the past, but as soon as we have news on this we will update the ticket

**Comment by GeekDot** [comment]
> Hi!
> 
> Thank you so much for opening the ticket. We had issues adding ARM support in the past, but as soon as we have news on this we will update the ticket

Thank you so much.

**Comment by zekena2** [comment]
@javsalgar is the issues tracked somewhere? Maybe someone from the community can help fixing them.

**Comment by carrodher** [comment]
The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by dridi-walid** [comment]
Hi, any update about arm support for mongodb docker image?
