### ISSUE TITLE
Change security parameters JasperReports

### ISSUE THREAD

**Issue by giz33** [bitnami/charts#16259]
### Name and Version

bitnami/jasperreports:latest

### What is the problem this feature will solve?

I need a way to change the parameter security.validation.sql.on using the values.yaml.
How can I do this?

Tks in advance for further help.

### What is the feature you are proposing to solve the problem?

A filed inside values.yaml to change the value of security.validation.sql.on

### What alternatives have you considered?

I considered create a configmap and associate it to the deployment but the POD don't start after this.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
