### ISSUE TITLE
[bitnami/jupyterhub] Add ability to call custom runtime

### ISSUE THREAD

**Issue by johnbarney** [bitnami/charts#16327]
### Name and Version

bitnami/jupyterhub:3.1.1

### What is the problem this feature will solve?

Currently there is no way to define a runtimeClass on the singleuser container spec. This prevents me from starting the container with the nvidia container toolkit and locks me out of sharing GPU from the host to the singleuser container.

### What is the feature you are proposing to solve the problem?

Add the ability to define runtimeClass on the singleuser configuration within the chart. Based on the template it looks as though this feature has been considered as there is a commented out "runtimeClass" field in the YAML once I log into Jupyterhub and the singleuser notebook as spawned. However I cannot find how to access this feature in the Bitnami documentation or source code.

### What alternatives have you considered?

I have tried to set the nvidia runtime as default in the container toolkit however this does not work on my cluster for an yet unknown reason. Starting example containers with runtimeClass allows for GPU access. This is a bug I intend to follow up with nvidia on in the gpu-operator repository.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by johnbarney** [comment]
I've looked into this and believe Kubespawner would need to implement this feature first as I don't see it in their API documentation. For my part I've managed for force my cluster to use nvidia runtime. I'm happy to close this issue.

**Comment by carrodher** [comment]
Thanks for confirming, yes, let's close the issue

**Comment by hochbit** [comment]
For anyone with that issue:

```yaml

hub:
  configuration: |
     ...
    singleuser:
      extraPodConfig:
        runtimeClassName: nvidia
```
