### ISSUE TITLE
[bitnami/jupyterhub] Resource requests are not respected when singleuser pod is spawned

### ISSUE THREAD

**Issue by johnbarney** [bitnami/charts#16336]
### Name and Version

bitnami/jupyterhub:3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Modify singleuser.resources.* in chart.
Observe no resource change in singleuser pod when spawned

### Are you using any custom parameters or values?

      singleuser:
        resources:
          limits:
            nvidia.com/gpu: 1

### What is the expected behavior?

Based on documentation here: https://docs.bitnami.com/kubernetes/infrastructure/jupyterhub/configuration/configure-single-user-instances/

I would expect all values supplied under "singleuser:" to be properly applied to the singleuser pod when launched by hub.

### What do you see instead?

I see no resource limits/requests applied to my singleuser pods.

### Additional information

Also tried rolling back a few versions and observed the same behavior.

**Comment by johnbarney** [comment]
Digging deeper it seems this feature was considered and partially implemented but never finished. This deduction is based on reading the jupyterhub_config.py that gets shipped with the zip file Bitnami deliver to the container via a zip file in the container repo. It contains lines that parse the sections of the config file containing extra resources but never passes it along to Kubespawn. I could patch this feature in on my end by creating a custom hub container based on Bitnami's but that:

A) This solution defeats the "turnkey" advantage of a Bitnami solution 
B) The YAML fields exists to customize this value but the config file does nothing with the value supplied which makes for a frustrating troubleshooting process
C) Creates a longer work cycle when I upgrade the chart to verify the config file in my container is updated as well. 

This zip file seems to come from a blackbox source so I can't contribute to the upstream artifact. If there's somewhere to contribute to this zip file and I just missed it please let me know. For now I'll unblock myself by patching the config in a custom hub image.

**Comment by johnbarney** [comment]
Thank you for explaining that. What is the upstream repo you refer to? I’m having trouble determining where the fix needs to live since it seems the variables are handed off several times before finally ingested. I guess somewhere along this complex chain these settings are lost.

**Comment by rafariossaa** [comment]
Hi,
  [This is](https://github.com/bitnami/charts/blob/40067ec81e2f38a4f596457ccefa41bb4f2e7af0/bitnami/jupyterhub/templates/hub/configmap.yaml#L17) the upstream chart where the file is copied from.

**Comment by johnbarney** [comment]
Understood. Thanks for the info. I'll open with them.
