### ISSUE TITLE
[bitnami/wordpress]  plugin installation failed with "Installation failed: Could not create directory. /opt/bitnami/wordpress/wp-content"

### ISSUE THREAD

**Issue by bouaouda-achraf** [bitnami/charts#16332]
### Name and Version

bitnami/wordpress-nginx:6.2.0-debian-11-r15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1- deploy the helm chart https://github.com/bitnami/charts/tree/main/bitnami/wordpress with https://hub.docker.com/r/bitnami/wordpress-nginx docker image .
2- try to install a plugin 
3- plugin installation failed 

### What is the expected behavior?

the plugin installation succeded without manual intervention 

### What do you see instead?

_Installation failed: Could not create directory. /opt/bitnami/wordpress/wp-content_

### Additional information

Helm chart values yaml :  
```
wordpress:
  image:
    repository: bitnami/wordpress-nginx
    tag: 6.2.0-debian-11-r15
  persistence:
    storageClass:  azurefile-csi-premium
    accessModes:
      - ReadWriteMany
    size: 50Gi # 
  ingress:
    enabled: false
```
Chart.yaml 
```  
- name: wordpress
    repository: https://charts.bitnami.com/bitnami
    tags:
      - wordpress 
      - blog
    version: 16.0.2
```

**Comment by javsalgar** [comment]
Hi,

Could you try launching the chart with `diagnosticMode.enabled=true`, enter the container and check the permissions of the affected folders? It seems to me that there might be an issue with readOnlyRootFilesystems or similar.

**Comment by bouaouda-achraf** [comment]
Hi @javsalgar ,

Thanks for your reply .

permissions output with diagnosticMode enabled: 
`I have no name!@wp-wordpress-9f9898c7b-2c5dq:/$ ls -l **/opt/bitnami/wordpress/wp-content**
total 24
-rw-rw-r--  1 daemon root   28 Apr 27 15:15 index.php
drwxrwxr-x  2 daemon root 4096 Apr 27 17:22 languages
drwxrwxr-x 11 daemon root 4096 Apr 27 15:27 plugins
drwxrwxr-x  5 daemon root 4096 Apr 27 15:27 themes
drwxrwxr-x  2 daemon root 4096 Apr 27 17:22 upgrade
drwxrwxr-x  2 daemon root 4096 Apr 27 17:22 uploads


I have no name!@wp-wordpress-9f9898c7b-2c5dq:/$ ls -l **/opt/bitnami/wordpress**
total 240
-rw-rw-r--  1 daemon root   405 Apr 27 15:15 index.php
-rw-rw-r--  1 daemon root 19915 Apr 27 15:15 license.txt
drwxrwxr-x  2 daemon root  4096 Apr 27 15:27 licenses
-rw-rw-r--  1 daemon root  7402 Apr 27 15:15 readme.html
drwxrwxr-x  2 daemon root  4096 Apr 27 17:22 tmp
-rw-rw-r--  1 daemon root  7205 Apr 27 15:15 wp-activate.php
drwxrwxr-x  9 daemon root  4096 Apr 27 15:27 wp-admin
-rw-rw-r--  1 daemon root   351 Apr 27 15:15 wp-blog-header.php
-rw-rw-r--  1 daemon root  2338 Apr 27 15:15 wp-comments-post.php
-rw-rw-r--  1 daemon root  3013 Apr 27 15:15 wp-config-sample.php
-rw-rw-r--  1 daemon root  3013 Apr 27 17:21 wp-config.php
drwxrwxr-x  7 daemon root  4096 Apr 27 17:22 wp-content
-rw-rw-r--  1 daemon root  5536 Apr 27 15:15 wp-cron.php
drwxrwxr-x 28 daemon root 12288 Apr 27 15:27 wp-includes
-rw-rw-r--  1 daemon root  2502 Apr 27 15:15 wp-links-opml.php
-rw-rw-r--  1 daemon root  3792 Apr 27 15:15 wp-load.php
-rw-rw-r--  1 daemon root 49330 Apr 27 15:15 wp-login.php
-rw-rw-r--  1 daemon root  8541 Apr 27 15:15 wp-mail.php
-rw-rw-r--  1 daemon root 24993 Apr 27 15:15 wp-settings.php
-rw-rw-r--  1 daemon root 34350 Apr 27 15:15 wp-signup.php
-rw-rw-r--  1 daemon root  4889 Apr 27 15:15 wp-trackback.php
-rw-rw-r--  1 daemon root  3238 Apr 27 15:15 xmlrpc.php`

permissions with diagnosticMode  disabled : 
`I have no name!@wp-wordpress-64dcddd578-2gkhr:/$ ls -l  **/opt/bitnami/wordpress**
total 232
-rw-rw-r--  1 daemon root   405 Apr 27 15:15 index.php
-rw-rw-r--  1 daemon root 19915 Apr 27 15:15 license.txt
drwxrwxr-x  2 daemon root  4096 Apr 27 15:27 licenses
-rw-rw-r--  1 daemon root  7402 Apr 27 15:15 readme.html
drwxrwxr-x  2 daemon root  4096 Apr 27 17:22 tmp
-rw-rw-r--  1 daemon root  7205 Apr 27 15:15 wp-activate.php
drwxrwxr-x  9 daemon root  4096 Apr 27 15:27 wp-admin
-rw-rw-r--  1 daemon root   351 Apr 27 15:15 wp-blog-header.php
-rw-rw-r--  1 daemon root  2338 Apr 27 15:15 wp-comments-post.php
-rw-rw-r--  1 daemon root  3013 Apr 27 15:15 wp-config-sample.php
lrwxrwxrwx  1   1001 root    32 May  2 12:28 wp-config.php -> /bitnami/wordpress/wp-config.php
lrwxrwxrwx  1   1001 root    29 May  2 12:28 wp-content -> /bitnami/wordpress/wp-content
-rw-rw-r--  1 daemon root  5536 Apr 27 15:15 wp-cron.php
drwxrwxr-x 28 daemon root 12288 Apr 27 15:27 wp-includes
-rw-rw-r--  1 daemon root  2502 Apr 27 15:15 wp-links-opml.php
-rw-rw-r--  1 daemon root  3792 Apr 27 15:15 wp-load.php
-rw-rw-r--  1 daemon root 49330 Apr 27 15:15 wp-login.php
-rw-rw-r--  1 daemon root  8541 Apr 27 15:15 wp-mail.php
-rw-rw-r--  1 daemon root 24993 Apr 27 15:15 wp-settings.php
-rw-rw-r--  1 daemon root 34350 Apr 27 15:15 wp-signup.php
-rw-rw-r--  1 daemon root  4889 Apr 27 15:15 wp-trackback.php
-rw-rw-r--  1 daemon root  3238 Apr 27 15:15 xmlrpc.php



I have no name!@wp-wordpress-64dcddd578-2gkhr:/$ ls -l  **/opt/bitnami/wordpress/wp-content**
lrwxrwxrwx 1 1001 root 29 May  2 12:28 /opt/bitnami/wordpress/wp-content -> /bitnami/wordpress/wp-content
I have no name!@wp-wordpress-64dcddd578-2gkhr:/$ ls -l  /bitnami/wordpress/wp-content
ls: cannot access '/bitnami/wordpress/wp-content': No such file or directory`

**Comment by javsalgar** [comment]
Does the user that is running the container belong to the `root` group? This is a condition to make it work and I'm not sure if a policy in your cluster is preventing that.

**Comment by jotamartos** [comment]
Hi @bouaouda-achraf, 

Some minor questions to know what you tested (and what we can try to solve the issue) before working on reproducing the issue:

- Did you try using the same configuration (persistence, ingress) with the bitnami/wordpress image instead of the wordpress-nginx one?
- Did you take a look at the existing tickets in the forum that are related to this question?

https://github.com/bitnami/charts/issues?q=is%3Aissue+wordpress+permissions+storageClass

**Comment by bouaouda-achraf** [comment]
Hi @jotamartos , 

I just reproduce the bug and fix the bug  , it's related to azure file ( nfs ) storage , when switching to azure disk storage it works without any errors .

I created a PR . https://github.com/bitnami/charts/pull/16637 

Thank you

**Comment by jotamartos** [comment]
Thanks for taking the time to create the PR. The team already reviewed it. Can you take a look at the comment and update it?

Thanks

**Comment by bouaouda-achraf** [comment]
thank you @jotamartos  , PR updated .

**Comment by jotamartos** [comment]
Great! The team will review it and merge it if everything is correct. Thanks!

**Comment by bouaouda-achraf** [comment]
Hello @jleeemrge 
Can you double check on your generated  deployment yaml the value of:
readOnlyRootFilesystem: false

**Comment by jleeemrge** [comment]
Hi @bouaouda-achraf 

the securityContext section of my deployment.yaml is:

```
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
```

**Comment by lorenzo-w** [comment]
I am also experiencing this issue with Longhorn CSI RWX volume. I think this is an issue with NFS (which is used by Longhorn and other CSIs to serve RWX volumes). Possibly this is even related to a similar issue with the Nextcloud Helm Chart: https://github.com/nextcloud/helm/issues/399

**Comment by thiagomarsal** [comment]
> > I am also experiencing this issue with Longhorn CSI RWX volume. I think this is an issue with NFS (which is used by Longhorn and other CSIs to serve RWX volumes). Possibly this is even related to a similar issue with the Nextcloud Helm Chart: [nextcloud/helm#399](https://github.com/nextcloud/helm/issues/399)
> 
> A similar problem in Longhorn RWX will generate these types of errors as well. It is due to it taking a long time to fill the PVC. So it seems to interrupt before it's done. RWO is very fast in seconds to fill the PVC - and it works. RWX can take minutes - and the installation doesn't finish. You will notice a larger amount in the volume if you use RWO, this is what the actual total should be. RWX will be less because it's interrupted and doesn't complete. It can seem like there is a permissions problem, but the cause goes back to the RWX not completing.
> 
> I implemented the solution from the Nextcloud issue above as follows which now works for me. I'm not sure if this applies to this issue or how it could be resolved - maybe a comment about this in the chart values near the RWX section could help.
> 
> Bitnami WordPress values (for slow volumes such as Longhorn RWX) :
> 
> ```yaml
> livenessProbe:
>   enabled: true
>   httpGet:
>     path: /wp-admin/install.php
>     port: '{{ .Values.wordpressScheme }}'
>     scheme: '{{ .Values.wordpressScheme | upper }}'
>     httpHeaders: []
>   initialDelaySeconds: 120
>   periodSeconds: 10
>   timeoutSeconds: 5
>   failureThreshold: 50
>   successThreshold: 1
> ```

Thanks a lot for sharing this @grams777. I was also facing the same issue while using Longhorn RWX and this solved the issue.
