### ISSUE TITLE
[bitnami/redis] Split Brain

### ISSUE THREAD

**Issue by tim-hanssen** [bitnami/charts#16359]
### Name and Version

bitnami/redis:17.9.2

### What architecture are you using?

None

### What steps will reproduce the bug?

We experienced a issue where after a node goes down, one of the redis instances did not join the rest of the sentinel cluster but started it's own, running in split brain. Restarting that pod fixed the issue, but now we did not detected it before the applicatie was showing some weird responses.

After some investigation we have a full reproduction in the linked issue, the same issue is also appearing on the Redis instances we run with the Bitnami chart.

https://github.com/groundhog2k/helm-charts/issues/1231

### What do you see instead?

Split brain if one of the nodes failed.

**Comment by dgomezleon** [comment]
Hi @tim-hanssen ,

Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by rassie** [comment]
@dgomezleon This issue still exists, could you reopen this issue?

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
