### ISSUE TITLE
[bitnami/kubernetes-event-exporter] Support kubeQps and kubeBurst in kubernetes-events-exporter chart

### ISSUE THREAD

**Issue by DavidHe1127** [bitnami/charts#16371]
### Name and Version

2.3.1

### What is the problem this feature will solve?

Prevent having client throttling error when it's trying to query Kubernetes API Server for object events. The `kubernetes-events-exporter` chart bootstraps this [helm chart](https://github.com/resmoio/kubernetes-event-exporter) and that one already supports setting of [these 2 fields](https://github.com/resmoio/kubernetes-event-exporter#troubleshoot-events-discarded-warning).

### What is the feature you are proposing to solve the problem?

Add support for settings of `kubeQps` and `kubeBurst`

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the ticket. If it's just a matter of adding two values to the chart, would you like to submit a PR adding support for them?

**Comment by DavidHe1127** [comment]
@javsalgar No problem! Here you go https://github.com/bitnami/charts/pull/16376. Note, this is the first time I am making changes to a helm chart, let me know if I am missing anything in my changes. Thanks

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
