### ISSUE TITLE
[bitnami/clickhouse] add the clickhouse-backup tools

### ISSUE THREAD

**Issue by KevinLiangX** [bitnami/charts#16374]
### Name and Version

bitnami/clickhouse

### What is the problem this feature will solve?

after clickhouse helm installed , the clickhouse data need to  backup to remote server . is it possible intergrating the backup tools or other backup method to do ?  is there any solution in kubernetes ？

### What is the feature you are proposing to solve the problem?

after clickhouse helm installed , the clickhouse data need to  backup to remote server . is it possible intergrating the backup tools or other backup method to do ?  is there any solution in kubernetes ？

**Comment by javsalgar** [comment]
Hi,

It seems to me that the issue is more in the backup tool rather than clickhouse itself. Could you check with the tool developer?

**Comment by KevinLiangX** [comment]
looking forward to your reply and guidance, thanks

**Comment by javsalgar** [comment]
Hi,

In principle there are no plans to package the backup tools but it would be interesting for the backup tools dev to check why it is not working with the clickhouse container.

**Comment by KevinLiangX** [comment]
@javsalgar  hello javsalgar 
 i asked the clickhouse-backup team that intergrate the tool to our chart .
https://github.com/AlexAkulov/clickhouse-backup/issues/657 , please kindly help to check it .

is it possible to make it that backup team said ?
i don't know why he said that can not run second container in our statefulset .

**Comment by javsalgar** [comment]
Hi,

You can use the `sidecars` section to add your custom containers to the Clickhouse deployment.

**Comment by KevinLiangX** [comment]
@javsalgar  thanks, Javsalgar   I have finished the backup action in our chart by sidecar with the same data volume to make the backup.  I closed the issue now
