### ISSUE TITLE
Could I change the system timezone in zookeeper chart?

### ISSUE THREAD

**Issue by linux0x5c** [bitnami/charts#1637]
I want to change system timezone in zookeeper chart,but I can't find values to modify it,coud you help me?

**Comment by carrodher** [comment]
Hi, can you explain a bit more this use case? I mean, is it a parameter in zookeeper itself that you want to modify or are you talking about the timezone in the kubernetes node?
Is it a very specific case or a common practice?

**Comment by linux0x5c** [comment]
Hi,carrodher,this deault  timezone is UTC of zookeeper containers, like it:
[root@cce-dev-fat-uat-node-001 templates]# kubectl -ndevops exec zookeeper-0 -- date
[root@cce-dev-fat-uat-node-001 templates]# kubectl -ndevops exec zookeeper-0 -- date
Sat Nov 23 02:13:15 UTC 2019
[root@cce-dev-fat-uat-node-001 templates]# kubectl -ndevops exec zookeeper-0 -- ls -l /etc/localtime
lrwxrwxrwx 1 root root 27 Aug 12 09:45 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC

,I want to change UTC timezone to CST timezone ,can I modify it in values.yaml?

**Comment by carrodher** [comment]
In this chart is possible to use the `jvmFlags` parameter to specify the JVMFLAGS for the ZooKeeper process. I am not sure if there is any Java opt that set the timezone, googling I found [this post](https://community.cloudera.com/t5/Support-Questions/How-do-you-change-the-timezone-for-the-HDP-cluster/td-p/120424).

**Comment by linux0x5c** [comment]
OK,thanks carrodher,I will try to do it.

**Comment by linux0x5c** [comment]
Hi carrodher,when i try to update it,an error occured:
[root@cce-dev-fat-uat-node-001 zookeeper]# helm -ndevops upgrade zookeeper -f values-production.yaml . --debug
upgrade.go:79: [debug] preparing upgrade for zookeeper
upgrade.go:87: [debug] performing update for zookeeper
upgrade.go:225: [debug] creating upgraded release for zookeeper
client.go:149: [debug] checking 6 resources for changes
client.go:384: [debug] Looks like there are no changes for PodDisruptionBudget "zookeeper"
client.go:384: [debug] Looks like there are no changes for Service "zookeeper-exporter"
client.go:384: [debug] Looks like there are no changes for Service "zookeeper-headless"
client.go:384: [debug] Looks like there are no changes for Service "zookeeper"
client.go:384: [debug] Looks like there are no changes for Deployment "zookeeper-exporter"
client.go:181: [debug] error updating the resource "zookeeper":
	 cannot patch "zookeeper" with kind StatefulSet: StatefulSet.apps "zookeeper" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
upgrade.go:280: [debug] warning: Upgrade "zookeeper" failed: cannot patch "zookeeper" with kind StatefulSet: StatefulSet.apps "zookeeper" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error: UPGRADE FAILED: cannot patch "zookeeper" with kind StatefulSet: StatefulSet.apps "zookeeper" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
helm.go:76: [debug] cannot patch "zookeeper" with kind StatefulSet: StatefulSet.apps "zookeeper" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
helm.sh/helm/v3/pkg/kube.(*Client).Update
	/home/circleci/helm.sh/helm/pkg/kube/client.go:194
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:239
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:88
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:130
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
UPGRADE FAILED
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:132
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by carrodher** [comment]
What are the parameters you modified in the `values-production.yaml`? Are you able to reproduce the same issue by installing the chart from scratch using those new parameters instead of updating an old installation?

**Comment by linux0x5c** [comment]
This is different form the origin values-production.yaml:
[root@cce-dev-fat-uat-node-001 zookeeper]# diff values-production.yaml values-production.yaml.ori 
142c142
< jvmFlags: "-Duser.timezone=Asia/Shanghai"
---
> # jvmFlags:
173c173
<   storageClass: "nfs-rw"
---
>   # storageClass: "-"
176,179c176,177
<   size: 5Gi
<   annotations:
<     volume.beta.kubernetes.io/storage-class: nfs-rw
<     volume.beta.kubernetes.io/storage-provisioner: flexvolume-huawei.com/fuxinfs
---
>   size: 8Gi
>   annotations: {}

when user this params to install it,no probles occured.

[root@cce-dev-fat-uat-node-001 zookeeper]# helm install zk-test -f values-production.yaml .
NAME: zk-test
LAST DEPLOYED: Wed Nov 27 10:26:03 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

ZooKeeper can be accessed via port 2181 on the following DNS name from within your cluster:

    zk-test-zookeeper.default.svc.cluster.local

To connect to your ZooKeeper server run the following commands:

    export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=zookeeper,app.kubernetes.io/instance=zk-test,app.kubernetes.io/component=zookeeper" -o jsonpath="{.items[0].metadata.name}")
    kubectl exec -it $POD_NAME -- zkCli.sh

To connect to your ZooKeeper server from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/zk-test-zookeeper 2181:2181 &
    zkCli.sh 127.0.0.1:2181

**Comment by carrodher** [comment]
I just installed the chart using jvmFlags to set the timezone:
```
helm install bitnami/zookeeper --set jvmFlags="-Duser.timezone=Asia/Shanghai"
```
Once deployed:
```
kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
singed-spaniel-zookeeper-0           1/1     Running   0          4m38s
```
I can see if this JAVA option was passed to the `java` command that initialize ZooKeeper by running:
```bash
kubectl exec singed-spaniel-zookeeper-0 ps xufa
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001         141  0.0  0.0  36636  2788 ?        Rs   11:07   0:00 ps xufa
1001           1  1.2  0.8 3479724 64764 ?       Ssl  11:05   0:01 java -Dzookeeper.log.dir=/opt/bitnami/zookeeper/logs -Dzookeeper.log.file=zookeeper--server-singed-spaniel-zookeeper-0.log -Dzookeeper.root.logger=INFO,CONSOLE -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -cp /opt/bitnami/zookeeper/bin/../zookeeper-server/target/classes:/opt/bitnami/zookeeper/bin/../build/classes:/opt/bitnami/zookeeper/bin/../zookeeper-server/target/lib/*.jar:/opt/bitnami/zookeeper/bin/../build/lib/*.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-jute-3.5.6.jar:/opt/bitnami/zookeeper/bin/../lib/zookeeper-3.5.6.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-log4j12-1.7.25.jar:/opt/bitnami/zookeeper/bin/../lib/slf4j-api-1.7.25.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-unix-common-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-native-epoll-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-transport-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-resolver-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-handler-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-common-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-codec-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/netty-buffer-4.1.42.Final.jar:/opt/bitnami/zookeeper/bin/../lib/log4j-1.2.17.jar:/opt/bitnami/zookeeper/bin/../lib/json-simple-1.1.1.jar:/opt/bitnami/zookeeper/bin/../lib/jline-2.11.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-util-9.4.17.v20190418.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-servlet-9.4.17.v20190418.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-server-9.4.17.v20190418.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-security-9.4.17.v20190418.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-io-9.4.17.v20190418.jar:/opt/bitnami/zookeeper/bin/../lib/jetty-http-9.4.17.v20190418.jar:/opt/bitnami/zookeeper/bin/../lib/javax.servlet-api-3.1.0.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-databind-2.9.10.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-core-2.9.10.jar:/opt/bitnami/zookeeper/bin/../lib/jackson-annotations-2.9.10.jar:/opt/bitnami/zookeeper/bin/../lib/commons-cli-1.2.jar:/opt/bitnami/zookeeper/bin/../lib/audience-annotations-0.5.0.jar:/opt/bitnami/zookeeper/bin/../zookeeper-*.jar:/opt/bitnami/zookeeper/bin/../zookeeper-server/src/main/resources/lib/*.jar:/opt/bitnami/zookeeper/bin/../conf: -Xmx1000m -Duser.timezone=Asia/Shanghai -Xmx1024m -Xms1024m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
```
Although there are a lot of options in this process, at the end the timezone flag appears: `-Xmx1000m -Duser.timezone=Asia/Shanghai -Xmx1024m -Xms1024m`

**Comment by linux0x5c** [comment]
Hi carrodher,thanks so much, i had solved it with your method,as for failed upgrade,that's my cluster problem.
