### ISSUE TITLE
[bitnami/kafka] Communication through Secondary interface

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#16382]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi Team - I have deployed Kafka through Secondary interface(Multus Container Network Interface) . My requirement is Kafka pods & clients should communicate through secondary interface. Please latus know how to achieve this. 

Here net1 is the secondary interface.
![image](https://user-images.githubusercontent.com/96808632/236245273-f5609b63-8f82-49a1-b65b-28dab4b76dcd.png)

![image](https://user-images.githubusercontent.com/96808632/236245622-952fa0d5-2273-464e-a270-38bb67c4b7bc.png)

### What is the expected behavior?

Now its communication through DNS, it should point to secondary interface.

### What do you see instead?

Now its communication through DNS, it should point to secondary interface. How to achieve this?

**Comment by javsalgar** [comment]
Hi,

Did you configure any binding address to point to this second interface?

**Comment by bharathreddy901** [comment]
Hi @javsalgar - I have not configured any binding address to point to this second interface, I am not sure how to configure this.
Can you please help me here.

**Comment by marcosbc** [comment]
Hi, you can have a look at the [traffic exposure parameters](https://github.com/bitnami/charts/tree/main/bitnami/kafka#traffic-exposure-parameters). There are some parameters such as `externalAccess.service.externalIPs` that you might be interested in checking out.
