### ISSUE TITLE
[bitnami/clickhouse] how to  extender the clickhouse shard or replication

### ISSUE THREAD

**Issue by KevinLiangX** [bitnami/charts#16380]
### Name and Version

bitnami/clickouse

### What architecture are you using?

amd64

### What steps will reproduce the bug?

i used our newest version chart of clickhouse ,   it set the shard =1 and replication =1 , how can i to extender the shard or relication with  our chart . not  uninstall the helm release and deploy again with new values. 

### What do you see instead?

[root@localhost clickhouse]# kubectl get pod 
NAME                     READY   STATUS    RESTARTS   AGE
clickhouse-shard0-0      1/1     Running   4          7d3h

[root@localhost clickhouse]# helm list 
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
clickhouse	default  	1       	2023-04-28 01:55:34.622752914 +0800 CST	deployed	clickhouse-3.2.1	23.3.2

**Comment by javsalgar** [comment]
Hi,

You could try launching `helm upgrade` with the new shard and replicas

**Comment by KevinLiangX** [comment]
OK  thanks sir
