### ISSUE TITLE
Discourse on Kubernetes: Unable to get Email for Backup

### ISSUE THREAD

**Issue by ByteInSpace** [bitnami/charts#16395]
### Name and Version

bitnami/discourse 9.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Environment: Kubernetes Cluster
1. Select Backup from Settings. You will see all available backups
2. You can request sending an email with a link where to download the backup. Requested it
3. Nothing is received. No email at all. Email is properly configured as all other mails from discourse are delivered:

### Are you using any custom parameters or values?
```yaml
smtp:
  enabled: true
  host: "smtp.companyhost"
  por:_ 25
```
### What is the expected behavior?

An email with the link to the backup should arrive

### What do you see instead?

Nothing. No email at all. No entry in the error log file

### Additional information

This already occurred with the earlier 8 version, too

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/discourse#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ByteInSpace** [comment]
Do I see it right, you completely stopped your own support for Discourse, relying on Community only? OK, this renders the usage of your chart in production environment completely useless
