### ISSUE TITLE
SCRAM authentication failed - pool_passwd file does not contain an entry for "xxxx"

### ISSUE THREAD

**Issue by full1985** [bitnami/charts#16396]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1 - install postgresql-ha chart with the command `helm install postgresql-ha-0 postgresql-ha`
```
postgresql-ha-0-pgpool
postgresql-ha-0-postgresql 
```
2 - connect to "postgres" db using credentials provided by the command:
```
export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-0-postgresql -o jsonpath="{.data.password}" | base64
```
3 - create a database _database_ and user _user_
```
postgres=# CREATE USER user WITH PASSWORD 'password';
CREATE ROLE
postgres=# CREATE DATABASE database OWNER user;
CREATE DATABASE
postgres=# GRANT ALL PRIVILEGES ON DATABASE database TO user;
GRANT
```
4 - now, if you try to access database _database_ with user _user_, you will receive the following error:
```
psql: error: FATAL:  SCRAM authentication failed
DETAIL:  pool_passwd file does not contain an entry for "user"
```
The reason is that in the pgpool file /opt/bitnami/pgpool/conf/pool_passwd there is only one entry for user postgres:
```
postgres:AES......
```
If you run the following command inside the pgpool pod, you are able to add the user entry:
```
pg_enc -m -f "/opt/bitnami/pgpool/conf/pgpool.conf" -k "/opt/bitnami/pgpool/conf/.pgpoolkey" -u user password

postgres:AES...
user:AES...
```
Now you can connect to the database _database_ with user _user_ (step number 4)
The problem is that if the pgpool restarts, you will lose the entry and you will not be able to connect anymore (you should repeat again the WA manually) 

Could you please provide a fix for this?

### What do you see instead?
```
psql: error: FATAL:  SCRAM authentication failed
DETAIL:  pool_passwd file does not contain an entry for "user"
```

**Comment by migruiz4** [comment]
Hi @full1985,

The pgpool pod does not have persistence, so changes configured manually inside it would be lost during a restart.

To add additional users, you will need to upgrade the chart using the following values:
```yaml
pgpool:
  customUsers:
    usernames: "user01;user02"
    passwords: "pass01;pass02"
```

**Comment by full1985** [comment]
Hello Miguel,

I tested your solution and works perfect: it is exactly what I need
You can close this issue

Thanks for your help

**Comment by neonvignesh** [comment]
thank you

**Comment by jjangga0214** [comment]
@migruiz4 Hi! Thanks for the explanatin. Then shouldn't the pgpool deployment restarted everytime the `customUsers` changes? I think the deployment should have checksum annotation from secret.

**Comment by ton3r** [comment]
That means, a custom created role/user to postgres via sql is not possible to directly login??

like this?
 
```sql
CREATE ROLE readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;
CREATE USER prometheus_read_user with encrypted password '01H#E098448aloWWYB7!NA244cdd59E';
GRANT readaccess TO prometheus_read_user;
```

When yes, how to create complex user scenarios like this ? This example requires more than username/passwrod

**Comment by migruiz4** [comment]
Hi @ton3r,

Please notice that the `postgresql-ha` chart consists of PostgreSQL + PgPool-II.

> That means, a custom created role/user to postgres via sql is not possible to directly login??

No, that means that Pgpool-II users in `pool_password` are not persisted, therefore running the user creation commands inside the `pgpool` pod won't work, as users will be recreated at restart.

For new users to persist restarts, they need to be provided in the chart values:
```
pgpool:
  customUsers:
    usernames: "user01;user02"
    passwords: "pass01;pass02"
```

In your example, you are creating users in PostgreSQL, but notice that in a Pgpool-II scenario, the client authenticates to Pgpool-II first:

Client <-> PgPool-II <-> PostgreSQL.

I would recommend reading the PgPool-II documentation for more information: https://www.pgpool.net/docs/42/en/html/client-authentication.html

**Comment by akshay-Samara** [comment]
useful , it solve my issue = SCRAM authentication failed

**Comment by cmcxn** [comment]
> Hi [@full1985](https://github.com/full1985),
> 
> The pgpool pod does not have persistence, so changes configured manually inside it would be lost during a restart.
> 
> To add additional users, you will need to upgrade the chart using the following values:
> 
> pgpool:
>   customUsers:
>     usernames: "user01;user02"
>     passwords: "pass01;pass02"

thanks
