### ISSUE TITLE
[thanos] Handle alert.query-url parameter automatically

### ISSUE THREAD

**Issue by dragoangel** [bitnami/charts#16401]
### Name and Version

bitnamicharts/thanos 12.5.1

### What is the problem this feature will solve?

Add `--alert.query-url` automatically to `query` and `ruler` when `queryFrontend` have `.Values.ingress.enabled` and configured properly

### What is the feature you are proposing to solve the problem?

It will allow provide links in Thanos UI properly and also will generate proper alerts source label which will be send to alertmanager by `ruler`

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by dragoangel** [comment]
Hi @carrodher I will check contributing guidelines, thank you. Will try :)
