### ISSUE TITLE
[Postgres] Continuous error logs of password failed authentication in AKS

### ISSUE THREAD

**Issue by apgapg** [bitnami/charts#16405]
### Name and Version

postgresql 15.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Simply deploy the chart using helm
3. See pod logs:

![image](https://user-images.githubusercontent.com/13887407/236457350-d77d3016-d12b-4024-ac29-e6aeaebf5580.png)

Note:

1. I have removed default role `postgres` as I thought some malicious guy setup DDOS. But still error logs are coming.
2. Upon investigation I see kube-system APIs are continuously hitting the DB. (checked by adding ingress, nginx).
 Particularly these pods are continuously hitting the db pod.
 
 
![image](https://user-images.githubusercontent.com/13887407/236457874-fccef56a-3afc-4697-ab3d-609d350e13fc.png)

### What is the expected behavior?

No logs must be captured. Looks like some readiness or live probes of kuberentes isn't able to setup TCP connection with database. As database is password protected hence doesn't allow to connect.

### What do you see instead?

![image](https://user-images.githubusercontent.com/13887407/236458081-43cb2948-6e2a-4229-b3a7-1c48a4b3f3b6.png)

**Comment by apgapg** [comment]
It got solved when I created a user 
```
create user postgres with
    superuser
    createdb
    createrole
    replication
    bypassrls PASSWORD ``<the db password used in helm config>``
```

**Comment by carrodher** [comment]
Can you try reinstalling the Helm chart after removing the PV/PVC and/or installing it in a different namespace? If you install the chart several times in the same namespace and using the same name it can be some inconsistencies between the random password generated during the deployment and the one stored in the PV/PVC since `helm delete` doesn't remove the storage-related objects

**Comment by apgapg** [comment]
I tried in depth looking and found hackers attacking the exposed IP with cron jobs to enter into postgres.
THats why I was getting such logs.

I tried setting `whitelist-source-range` on ingress-nginx but seems it doesn't work on TCP ports

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami postgresql container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
