### ISSUE TITLE
[thanos] Add dashboards to helm chart

### ISSUE THREAD

**Issue by dragoangel** [bitnami/charts#16419]
### Name and Version

bitnamicharts/thanos 12.5.1

### What is the problem this feature will solve?

Deploy Thanos dashboards via configmaps taken from https://github.com/thanos-io/thanos/tree/main/examples/dashboards

### What is the feature you are proposing to solve the problem?

This will allow to get metrics details out of the box

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
