### ISSUE TITLE
[bitnami/rabbitmq] How do I determine the mapping between the bitnami/rabbitmq and the official rabbitmq version?

### ISSUE THREAD

**Issue by springmvcGitHub** [bitnami/charts#16418]
### Name and Version

3.10.7-debian-11-r11

### What architecture are you using?

None

### When bitnami/rabbitmq has 3 Pods, the retain message is on each pod,How to do it?
Scenario:
I deployed a rabbitmq cluster using bitnami/rabbitmq and enabled the mqtt plugin,3 pods. When I sent a retain message for mqtt to the cluster, all mqtt consumers would get the retain message, either for pod1/pod2/pod3. 
**But** the cluster I deployed with the official rabbitmq was also 3 Pods, only consumers connected to the pod that sent the retain message would get the retain message. 
**The doubt is:Do you make this kind of synchronization mechanism?**

### How do you determine how the version here corresponds to the official version?
There is a new feature in the 3.12-rc-management release, [mqtt offline message](https://github.com/rabbitmq/rabbitmq-server/discussions/6331). Which version of bitnami/rabbitmq will this feature appear in?
**The question is:How do you determine how the version here corresponds to the official version?**

### What do you see instead?

none.

**Comment by javsalgar** [comment]
Hi,

Note that we do not package `rc`, `beta` or `alpha` versions, we only package stable ones. You would need to check in which stable version this feature is available and look for the same version in our Bitnami repository.
