### ISSUE TITLE
public.ecr.aws registry its not being updated 

### ISSUE THREAD

**Issue by rafilkmp3** [bitnami/charts#16414]
### Name and Version

public.ecr.aws/bitnami/consul:1.15.2-debian-11-r9

### What architecture are you using?

https://gallery.ecr.aws/bitnami/consul

### What steps will reproduce the bug?

The public.ecr.aws/bitnami/consul image appears to be outdated, with the latest available image being built and pushed 13 days ago. This image is used by many public Helm charts, including those found in the bitnami/consul repository on GitHub (https://github.com/bitnami/charts/tree/main/bitnami/consul), which were last updated 4 days ago. As a result, users may encounter issues when using these charts for their applications. We request that the Bitnami team investigate this issue and take appropriate action to ensure that the image is regularly updated with the latest features and bug fixes.

Thank you for your attention to this matter.

### What do you see instead?

 Back-off pulling image "public.ecr.aws/bitnami/consul:1.15.2-debian-11-r9"

**Comment by carrodher** [comment]
Thanks for letting us know. Yes, we faced an issue that is already solved but it is required some time in order to propagate the new releases.

>  This image is used by many public Helm charts, including those found in the bitnami/consul repository on GitHub (https://github.com/bitnami/charts/tree/main/bitnami/consul)

About that, please note the public Helm charts are using images from DockerHub, no ECR so it shouldn't be any issue with that:
```yaml
image:
  registry: docker.io
  repository: bitnami/consul
  tag: 1.15.2-debian-11-r9
```

**Comment by rafilkmp3** [comment]
@carrodher Yes, I know the default registry is docker-hub, but since I used to run on AWS, I always try to use the public ecr to avoid the terrible rate limit on docker pulls from docker-hub

**Comment by rafilkmp3** [comment]
Meanwhile, I will revert to docker-hub 

@carrodher, can you update this issue when updated images get pushed to ECR?

**Comment by carrodher** [comment]
Sure, I will update this thread once fixed.

In the same way, please note Bitnami is part of the Docker Verified Publisher program so bitnami images are not affected by any rate limit

**Comment by rafilkmp3** [comment]
Thank you very much for your effort. I didn't know that images on the docker hub with Docker Verified Publisher status were exempt from pull limits

**Comment by carrodher** [comment]
BTW, pushes to https://gallery.ecr.aws were resumed on our side, see for example https://gallery.ecr.aws/bitnami/consul.

I'm closing this issue as fixed. Thanks again for reporting it
