### ISSUE TITLE
[bitnami/elasticsearch] How to install native plugins. Such as elasticsearch-analysis-ik-8.6.2.zip

### ISSUE THREAD

**Issue by thousmile** [bitnami/charts#16423]
### Name and Version

bitnami/elasticsearch 19.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use the following command to start the es cluster.

```shell
helm install es bitnami/elasticsearch -n es \
--set global.elasticsearch.service.name=k8s-es \
--set security.enabled=true \
--set security.elasticPassword=hello123456 \
--set security.tls.autoGenerated=true \
--set security.tls.restEncryption=false \
--set master.masterOnly=false \
--set master.replicaCount=1 \
--set master.persistence.size=1Gi \
--set data.replicaCount=2 \
--set data.persistence.size=2Gi \
--set coordinating.replicaCount=1 \
--set ingest.enabled=false \
--set image.repository=bitnami/elasticsearch \
--set image.tag=8.6.2-debian-11-r13
```

But I want to mount a local directory. /data/nfs/es-plugins/elasticsearch-analysis-ik-8.6.2.zip 
This plugin. How to add parameters

### Are you using any custom parameters or values?

yes

### What do you see instead?

no

**Comment by javsalgar** [comment]
Hi,

You can use the extraVolume and extraVolumeMounts section to mount extra volumes to the containers inside a pod. If you want to download the data beforehand, you can use the initContaniers section as well.
