### ISSUE TITLE
Aerospike helm chart

### ISSUE THREAD

**Issue by akshaypatidar1999** [bitnami/charts#16429]
### Name and Version

bitnami/aerospike

### What is the problem this feature will solve?

Currently there is no stable helm chart available for aerospike.

### What is the feature you are proposing to solve the problem?

This will provide a helm chart for aerospike which will allow users to provision aerospike on containers
I will be happy to contribute to this feature. I have written a basic helm chart for aerospike which I use for running aerospike on containers. With your expertise, I can improve the helm chart and maybe publish in bitnami helm repository

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; this process could take some time due to limited resources. In the meantime, we will add the 'on-hold' label to prevent the stale bot from closing this issue.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
