### ISSUE TITLE
Bitnami/kafka kraft mode not working

### ISSUE THREAD

**Issue by mak241265** [bitnami/charts#16427]
### Name and Version

bitnami/kafka 22.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have 3 nodes Kubernetes cluster. I pull kafka bitnami version 22.0.2.in cluster yaml I set the replica broker node to 3..the kraft is enabled and I generate clusterId with `cat /proc/sys/kernel/random/uuid | tr -d '-' | base64 | cut -b 1-22` as the doc said. And I set `clusterId: "ZTAxYTAzYzcyMzQ1NDM5Yj"` but when I launch the chart only one pod goes to `Ready 1/1` and the other two `0/1` as I see the logs:
```
kafka 09:28:18.81 INFO  ==> Initializing KRaft...
kafka 09:28:18.81 INFO  ==> Formatting storage directories to add metadata...
```
and after a while, even the ready pod goes down as cannot connect to the other pods.
I use nfs as a storage class and all the pv are bounded without problems. The replica count of Kafka is 3

### Are you using any custom parameters or values?
just setting my kraft values
```
kraf.clusterId : "ZTAxYTAzYzcyMzQ1NDM5Yj"
```
all pods go to running and ready states

### What do you see instead?
```
kafka 09:28:18.20 INFO  ==> ** Starting Kafka setup **
kafka 09:28:18.25 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 09:28:18.26 INFO  ==> Initializing Kafka...
kafka 09:28:18.27 INFO  ==> No injected configuration files found, creating default config files
kafka 09:28:18.79 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
kafka 09:28:18.79 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
kafka 09:28:18.79 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 09:28:18.80 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 09:28:18.81 INFO  ==> Initializing KRaft...
kafka 09:28:18.81 INFO  ==> Formatting storage directories to add metadata...
```

### Additional information
I use linux ubuntu 20.04

**Comment by migruiz4** [comment]
Hi @mak241265,

Could you please share the following information, it would help us troubleshoot your issue:

- Deploy the chart using `helm install <your_release> bitnami/kafka --set kraft.clusterId=ZTAxYTAzYzcyMzQ1NDM5Yj --set replicaCount=3 --set image.debug=true`. If possible, ensure it is a fresh install by using different PVCs or removing existing ones.
- Output of `kubectl get pods`, `kubectl describe <failing_pod>` and `kubectl logs -p <failing_pod>`.
- Does the pod stop without any error message? When 'BITNAMI_DEBUG' is enabled, the output of the `kafka-storage.sh` should be printed to the console:
    
    ```
    info "Formatting storage directories to add metadata..."
    debug_execute "$KAFKA_HOME/bin/kafka-storage.sh" format --config "$(kafka_get_conf_file)" --cluster-id "$KAFKA_KRAFT_CLUSTER_ID" --ignore-formatted
    ```
    
Additionally, It is possible that the NFS storage could be the cause of the issue, as it is a common source of errors due to the NFS users mapping on containers. 

Depending on the NFS version used and its configuration, it is usual to see errors where the root user does not have root privileges (e.g. when enabling the `volumePermissions` init-container) or user 1001 owning the files is not mapped as the same user on pod restart / recreation.

**Comment by mak241265** [comment]
In order to make sute that NFS is not a problem, i disable persistent in values.yaml..and execute the below command:
helm install -n kafka kafka ./ --set kraft.clusterId=ZTAxYTAzYzcyMzQ1NDM5Yj --set replicaCount=3 --set image.debug=true

> Hi @mak241265,
> 
> Could you please share the following information, it would help us troubleshoot your issue:
> 
> * Deploy the chart using `helm install <your_release> bitnami/kafka --set kraft.clusterId=ZTAxYTAzYzcyMzQ1NDM5Yj --set replicaCount=3 --set image.debug=true`. If possible, ensure it is a fresh install by using different PVCs or removing existing ones.
> * Output of `kubectl get pods`, `kubectl describe <failing_pod>` and `kubectl logs -p <failing_pod>`.
> * Does the pod stop without any error message? When 'BITNAMI_DEBUG' is enabled, the output of the `kafka-storage.sh` should be printed to the console:
>   ```
>   info "Formatting storage directories to add metadata..."
>   debug_execute "$KAFKA_HOME/bin/kafka-storage.sh" format --config "$(kafka_get_conf_file)" --cluster-id "$KAFKA_KRAFT_CLUSTER_ID" --ignore-formatted
>   ```
> 
> Additionally, It is possible that the NFS storage could be the cause of the issue, as it is a common source of errors due to the NFS users mapping on containers.
> 
> Depending on the NFS version used and its configuration, it is usual to see errors where the root user does not have root privileges (e.g. when enabling the `volumePermissions` init-container) or user 1001 owning the files is not mapped as the same user on pod restart / recreation.



> Hi @mak241265,
> 
> Could you please share the following information, it would help us troubleshoot your issue:
> 
> * Deploy the chart using `helm install <your_release> bitnami/kafka --set kraft.clusterId=ZTAxYTAzYzcyMzQ1NDM5Yj --set replicaCount=3 --set image.debug=true`. If possible, ensure it is a fresh install by using different PVCs or removing existing ones.
> * Output of `kubectl get pods`, `kubectl describe <failing_pod>` and `kubectl logs -p <failing_pod>`.
> * Does the pod stop without any error message? When 'BITNAMI_DEBUG' is enabled, the output of the `kafka-storage.sh` should be printed to the console:
>   ```
>   info "Formatting storage directories to add metadata..."
>   debug_execute "$KAFKA_HOME/bin/kafka-storage.sh" format --config "$(kafka_get_conf_file)" --cluster-id "$KAFKA_KRAFT_CLUSTER_ID" --ignore-formatted
>   ```
> 
> Additionally, It is possible that the NFS storage could be the cause of the issue, as it is a common source of errors due to the NFS users mapping on containers.
> 
> Depending on the NFS version used and its configuration, it is usual to see errors where the root user does not have root privileges (e.g. when enabling the `volumePermissions` init-container) or user 1001 owning the files is not mapped as the same user on pod restart / recreation.

Hello @migruiz4 

In order to make sure that problem is not about NFS storage class,i disable persistence in values.yaml. and execute the command as below:
helm install -n kafka kafka ./ --set kraft.clusterId=ZTAxYTAzYzcyMzQ1NDM5Yj --set replicaCount=3 --set image.debug=true

kubectl get pods:
root@kubeadm-01:~# kubectl get pods -n kafka
NAME      READY   STATUS    RESTARTS      AGE
kafka-0   0/1     Running   3 (59s ago)   4m31s
kafka-1   1/1     Running   3 (48s ago)   4m31s
kafka-2   0/1     Running   4 (30s ago)   4m31s

kubectl describe pod/kafka-0 -n kafka

  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  26s               default-scheduler  Successfully assigned kafka/kafka-0 to kubeadm-02.mak
  Normal   Pulled     26s               kubelet            Container image "nexus.mak:7777/bitnami/kafka:3.4.0-debian-11-r22" already present on machine
  Normal   Created    26s               kubelet            Created container kafka
  Normal   Started    26s               kubelet            Started container kafka
  Warning  Unhealthy  6s (x2 over 16s)  kubelet            Readiness probe failed: dial tcp 10.120.126.67:9092: connect: connection refused
  Warning  Unhealthy  6s (x2 over 16s)  kubelet            Liveness probe failed: dial tcp 10.120.126.67:9092: connect: connection refused

kubectl logs -f pod/kafka-0 -n kafka
root@kubeadm-01:~# kubectl logs -f pod/kafka-0 -n kafka
kafka 12:23:40.74 
kafka 12:23:40.75 Welcome to the Bitnami kafka container
kafka 12:23:40.75 Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 12:23:40.76 Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 12:23:40.76 
kafka 12:23:40.77 INFO  ==> ** Starting Kafka setup **
kafka 12:23:40.99 DEBUG ==> Validating settings in KAFKA_* env vars...
kafka 12:23:41.05 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
kafka 12:23:41.09 INFO  ==> Initializing Kafka...
kafka 12:23:41.11 INFO  ==> No injected configuration files found, creating default config files
kafka 12:23:43.07 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
kafka 12:23:43.09 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
kafka 12:23:43.10 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
kafka 12:23:43.12 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
kafka 12:23:43.14 INFO  ==> Initializing KRaft...
kafka 12:23:43.15 INFO  ==> Formatting storage directories to add metadata...
root@kubeadm-01:~# 


---------------
there is no extra logs...when the pod can not pass the readiness/liveness then it restart without any logs

**Comment by migruiz4** [comment]
@mak241265 I see that the pod is not crashing with an error, but it is being terminated by the livenessProbe timing out. 

Could you please try to increase the `livenessProbe.initialDelaySeconds=180` (default value is 10 seconds), to ensure we give the `kafka-storage.sh` plenty of time in case something is causing it to take longer than usual?

> Another problem is even if i disable kraft and enable zookeeper, pods are still trying to initializing kraft...i'm very very confused.

Thank you for reporting this issue, I will work on a fix for that as soon as possible.

**Comment by migruiz4** [comment]
Here is the PR fixing the Zookeeper issue: https://github.com/bitnami/charts/pull/16558

**Comment by mak241265** [comment]
> @mak241265 I see that the pod is not crashing with an error, but it is being terminated by the livenessProbe timing out.
> 
> Could you please try to increase the `livenessProbe.initialDelaySeconds=180` (default value is 10 seconds), to ensure we give the `kafka-storage.sh` plenty of time in case something is causing it to take longer than usual?
> 
> > Another problem is even if i disable kraft and enable zookeeper, pods are still trying to initializing kraft...i'm very very confused.
> 
> Thank you for reporting this issue, I will work on a fix for that as soon as possible.

I found something,i force the workload to be deployed on one node and everything is running now...but when the pods are distributed to multiple nodes same issue i got...what would be the problem?

**Comment by mak241265** [comment]
Problem is solved.it was related to my calico setting,,,actually i reinstall calico on kubernetes based ok default config...everything is okey now..
