### ISSUE TITLE
bitnami/postgres-ha : Use dynamic credentials without restarting PGPOOL pods

### ISSUE THREAD

**Issue by angrastuti** [bitnami/charts#16428]
### Name and Version

bitnami/postgres-ha

### What is the problem this feature will solve?

At present, the helm chart accepts the custom user/password via secret, which is further passed as an ENV variable to the container for PGPOOL during initialization.

We want to use dynamic users and passwords created via a custom application.

The above application chart requires the postgres HA chart up and running,  and the PGPOOL container requires the secret created by the application. This dependency requires us to restart the PGPOOL container to pick up the updated secrets. ( Which will not be feasible for us) . 

### What is the feature you are proposing to solve the problem?

We are having a configuration for pool_password for PGPOOL and POSTGRES username and password. ( usePasswordFile ) 
Will it be possible to update the same file using custom secrets and reload the same if the underlying secret changes? 

### What alternatives have you considered?

Other than this I am looking into modifying `PGPOOL_USER_HBA_FILE` to allow all connections for all users created dynamically but it might not be the right approach, keeping security in mind.

Thus, I will require recommendations and support for solving the use case.

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by angrastuti** [comment]
Thank you @carrodher  .  Can we request for a secret reloader image via bitnami similar to configmap reload for this ? We have [stakater/Reloader](https://github.com/stakater/Reloader) upstream for this usecase , but corresponding container image via bitnami is not present.

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; this process could take some time due to limited resources. In the meantime, we will add the 'on-hold' label to prevent the stale bot from closing this issue.

**Comment by carrodher** [comment]
> Thank you @carrodher . Can we request for a secret reloader image via bitnami similar to configmap reload for this ? We have [stakater/Reloader](https://github.com/stakater/Reloader) upstream for this usecase , but corresponding container image via bitnami is not present.

Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
