### ISSUE TITLE
[bitnami/postgresql-ha] Invalid postgresql data folder permissions after restarting the pod

### ISSUE THREAD

**Issue by ccmehk** [bitnami/charts#1649]
**Which chart**:

postgresql-ha v1.0.2

**Description**
here is the log after restarting the pod.
The permission seems invalid after restart

> postgresql 09:05:36.70 INFO  ==> Starting PostgreSQL in background...
> waiting for server to start....2019-11-22 09:05:36.731 GMT [222] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
> 2019-11-22 09:05:36.731 GMT [222] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
>  stopped waiting
> pg_ctl: could not start server
> Examine the log output.

**Steps to reproduce the issue:**

1. delete and restart the pod
2. the pod cannot be start

**Describe the results you received:**

no error occur

**Describe the results you expected:**

no error occur

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by alemorcuq** [comment]
Hi, @ccmehk.

I'm not able to reproduce your issue. I have deployed the chart like this:

```
❯ helm install -n amoreno-psql --namespace amoreno-psql bitnami/postgresql-ha
NAME:   amoreno-psql
LAST DEPLOYED: Fri Nov 22 10:38:19 2019
NAMESPACE: amoreno-psql
STATUS: DEPLOYED
[...]

❯ k get all -n amoreno-psql
NAME                                                     READY   STATUS    RESTARTS   AGE
pod/amoreno-psql-postgresql-ha-pgpool-5c46f87b75-rq5lg   1/1     Running   0          8m13s
pod/amoreno-psql-postgresql-ha-postgresql-0              1/1     Running   0          8m13s
pod/amoreno-psql-postgresql-ha-postgresql-1              1/1     Running   0          7m32s

NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/amoreno-psql-postgresql-ha-pgpool                ClusterIP   10.30.255.146   <none>        5432/TCP   8m13s
service/amoreno-psql-postgresql-ha-postgresql            ClusterIP   10.30.242.151   <none>        5432/TCP   8m13s
service/amoreno-psql-postgresql-ha-postgresql-headless   ClusterIP   None            <none>        5432/TCP   8m13s

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/amoreno-psql-postgresql-ha-pgpool   1/1     1            1           8m13s

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/amoreno-psql-postgresql-ha-pgpool-5c46f87b75   1         1         1       8m13s

NAME                                                     READY   AGE
statefulset.apps/amoreno-psql-postgresql-ha-postgresql   2/2     8m13s

❯ k delete -n amoreno-psql pod/amoreno-psql-postgresql-ha-postgresql-0
pod "amoreno-psql-postgresql-ha-postgresql-0" deleted

❯ k get all -n amoreno-psql
NAME                                                     READY   STATUS    RESTARTS   AGE
pod/amoreno-psql-postgresql-ha-pgpool-5c46f87b75-rq5lg   1/1     Running   0          10m
pod/amoreno-psql-postgresql-ha-postgresql-0              1/1     Running   0          27s
pod/amoreno-psql-postgresql-ha-postgresql-1              1/1     Running   0          10m

NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/amoreno-psql-postgresql-ha-pgpool                ClusterIP   10.30.255.146   <none>        5432/TCP   10m
service/amoreno-psql-postgresql-ha-postgresql            ClusterIP   10.30.242.151   <none>        5432/TCP   10m
service/amoreno-psql-postgresql-ha-postgresql-headless   ClusterIP   None            <none>        5432/TCP   10m

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/amoreno-psql-postgresql-ha-pgpool   1/1     1            1           10m

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/amoreno-psql-postgresql-ha-pgpool-5c46f87b75   1         1         1       10m

NAME                                                     READY   AGE
statefulset.apps/amoreno-psql-postgresql-ha-postgresql   2/2     10m
```

The pod is killed and another one respawns successfully.

Please, provide more information in order to reproduce your issue. How are you installing the chart? Which pod are you killing? What `helm` and `kubectl` version are you using?

Regards,
Alejandro

**Comment by ccmehk** [comment]
hi @alemorcuq , thanks for the reply.
I am using values-production.yaml, kubectl v1.16.3 and helm v2.16.0

Here is the step i produced the issue.
`
>helm install --name mt-postgresql-ha -f postgresql_ha2.yml --namespace=dt-prod bitnami/postgresql-ha

mt-postgresql-ha-pgpool-5cf5f89c9d-cbbbk            1/1     Running
mt-postgresql-ha-postgresql-0                       2/2     Running 
mt-postgresql-ha-postgresql-1                       2/2     Running

>In mt-postgresql-ha-postgresql-0 folder permission:
drwxrwsr-x  7 1001 1001 4096 Nov 20 01:58 ..
drwxr-sr-x  2 1001 1001 4096 Nov 25 03:02 conf
drwxrwsr-x  4 root 1001 4096 Nov 25 03:02 .
drwx------ 19 1001 1001 4096 Nov 25 03:02 data

>In mt-postgresql-ha-postgresql-1 folder permission:
drwxrwsr-x  7 1001 1001 4096 Nov 20 01:58 ..
drwxr-sr-x  2 1001 1001 4096 Nov 25 03:02 conf
drwxrwsr-x  4 1001 1001 4096 Nov 25 03:03 .
drwx--S--- 19 1001 1001 4096 Nov 25 03:03 data


>kubectl -n dt-prod delete pod mt-postgresql-ha-postgresql-1
>kubectl -n dt-prod delete pod mt-postgresql-ha-postgresql-0

postgresql 03:09:05.73 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2019-11-25 03:09:05.760 GMT [217] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2019-11-25 03:09:05.760 GMT [217] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
 stopped waiting
pg_ctl: could not start server
Examine the log output.

the folder permission after restart, 
>In mt-postgresql-ha-postgresql-0 folder permission:
drwxrwsr-x  7 1001 1001 4096 Nov 20 01:58 ..
drwxrwsr-x  2 1001 1001 4096 Nov 25 03:02 conf
drwxrwsr-x  4 root 1001 4096 Nov 25 03:02 .
drwxrws--- 19 1001 1001 4096 Nov 25 03:08 data

>In mt-postgresql-ha-postgresql-1 folder permission:
drwxrwsr-x  7 1001 1001 4096 Nov 20 01:58 ..
drwxrwsr-x  2 1001 1001 4096 Nov 25 03:02 conf
drwxrwsr-x  4 1001 1001 4096 Nov 25 03:08 .
drwx--S--- 19 1001 1001 4096 Nov 25 03:08 data
`

It seems that the data folder permission after the pod retart?

**Comment by alemorcuq** [comment]
Hi, @ccmehk.

I still can't reproduce your issue. After I install the chart, the folder permissions are the same as yours:

```
I have no name!@amoreno-postgresql-ha-postgresql-0:/$ ls -la /bitnami/postgresql/
total 32
drwxrwsr-x  5 root 1001  4096 Dec  2 11:23 .
drwxr-xr-x  3 root root  4096 Nov 14 17:32 ..
drwxr-sr-x  2 1001 1001  4096 Dec  2 11:23 conf
drwx------ 19 1001 1001  4096 Dec  2 11:23 data
drwxrws---  2 root 1001 16384 Dec  2 11:23 lost+found

I have no name!@amoreno-postgresql-ha-postgresql-1:/$ ls -la /bitnami/postgresql/
total 32
drwxrwsr-x  5 root 1001  4096 Dec  2 11:24 .
drwxr-xr-x  3 root root  4096 Nov 14 17:32 ..
drwxr-sr-x  2 1001 1001  4096 Dec  2 11:23 conf
drwx--S--- 19 1001 1001  4096 Dec  2 11:24 data
drwxrws---  2 root 1001 16384 Dec  2 11:23 lost+found
```

However, after I restart the pods, this is what I get:

```
I have no name!@amoreno-postgresql-ha-postgresql-0:/$ ls -la /bitnami/postgresql/
total 32
drwxrwsr-x  5 root 1001  4096 Dec  2 11:42 .
drwxr-xr-x  3 root root  4096 Nov 14 17:32 ..
drwxrwsr-x  2 1001 1001  4096 Dec  2 11:23 conf
drwx--S--- 19 1001 1001  4096 Dec  2 11:42 data
drwxrws---  2 root 1001 16384 Dec  2 11:23 lost+found

I have no name!@amoreno-postgresql-ha-postgresql-1:/$ ls -la /bitnami/postgresql/
total 32
drwxrwsr-x  5 root 1001  4096 Dec  2 11:39 .
drwxr-xr-x  3 root root  4096 Nov 14 17:32 ..
drwxrwsr-x  2 1001 1001  4096 Dec  2 11:23 conf
drwx--S--- 19 1001 1001  4096 Dec  2 11:41 data
drwxrws---  2 root 1001 16384 Dec  2 11:23 lost+found
```

I don't know why the `data` directory in the `postgresql-0` pod changes permissions. Are you using the default `values-production.yaml`? Is there anything about your cluster that could be changing this?

Regards,
Alejandro
