### ISSUE TITLE
[bitnami/mongodb-sharded] Custom user and database variables seem to be ignored - user and db not being created

### ISSUE THREAD

**Issue by philippfreyer** [bitnami/charts#1655]
**Which chart**:

bitnami/mongodb-sharded

**Description**

Despite a custom `mongodbDatabase`, `mongodbUsername` and `mongodbPassword` defined in the charts `values.yaml` (and the file being used when deploying the chart), no custom database or user are created. It seems like the env variables that are required to do so are not passed to the docker images. The file is being picked up, though, since I can see my custom password in the secret that the helm chart creates.

**Steps to reproduce the issue:**

1. define the following parameters in a copy of the charts `values-production.yaml` file (here: `myvalues.yaml` ):
```
## Create a non-root MongoDB user
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
## mongodbUsername: user
mongodbUsername: myuser

## non-root MongoDB user password
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
## mongodbPassword: password
mongodbPassword: myuserpass

## Create database on first run
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
# mongodbDatabase: database
mongodbDatabase: myuserdb
```
2. Deploy the helm chart using `helm install --name mongodb --namespace mytestnamespace -f /myvalues.yaml  bitnami/mongodb-sharded`
3. Wait for the cluster to be created and observe that the secrets file contains the correct password. If you try to connect to the cluster using the defined user info, the connection will fail. If you connect using the root user and list the users on the cluster, the custom user and custom db are missing.

**Describe the results you received:**

See (3) above

**Describe the results you expected:**

The user and db should have been created

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Yes, I confirm that these values are not being passed. When I developed it, I was hesitant whether to add these values or not, because in a sharded cluster I was not entirely sure how this should be implemented. I think that the best choice should be using the init scripts instead. However, let me take a look and try to implement a solution that uses these values.

**Comment by philippfreyer** [comment]
@javsalgar 
I agree that init scripts may be the way to go here - I just assumed that any configuration option offered would also already be implemented.
My workaround (which I just confirmed as working fine for me) is to add the following code to my deployment script:

```
echo "Waiting for MongoDB to start up"
kubectl rollout status --timeout=600s statefulset/mongodb-mongodb-sharded-configsvr -n ${NAMESPACE}
for i in $(seq 0 $(( SHARD_COUNT-1 )));
do
  kubectl rollout status --timeout=600s statefulset/mongodb-mongodb-sharded-shard${i}-data -n ${NAMESPACE}
  kubectl rollout status --timeout=600s statefulset/mongodb-mongodb-sharded-shard${i}-arbiter -n ${NAMESPACE}
done

sleep 60

echo "Setting oplog size"
for i in $(seq 0 $(( SHARD_COUNT-1 )));
do
    kubectl --namespace=${NAMESPACE} exec mongodb-mongodb-sharded-shard${i}-data-0 -c mongodb -- mongo -u 'root' -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval "db.adminCommand( { setFeatureCompatibilityVersion: \"4.2\" } );"
    kubectl --namespace=${NAMESPACE} exec mongodb-mongodb-sharded-shard${i}-data-0 -c mongodb -- mongo -u 'root' -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval "db.adminCommand({replSetResizeOplog: 1, size: ${OPLOG_SIZE}});"
done

echo "Creating user"
kubectl --namespace=${NAMESPACE} exec $(kubectl --namespace=${NAMESPACE} get pods -o name | grep -m1 mongodb-mongodb-sharded-mongos | cut -d'/' -f 2) -c mongos -- mongo -u "root" -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval 'db.getSiblingDB("admin").createRole({ role: "SystemRole", privileges: [{resource:{db:"admin",collection:""},actions:["killop","inprog"]}, {resource:{db:"omg",collection:""},actions:["killop","inprog"]}, {resource:{db:"celery_jobs",collection:""},actions:["killop","inprog"]}], roles: [] });'
kubectl --namespace=${NAMESPACE} exec $(kubectl --namespace=${NAMESPACE} get pods -o name | grep -m1 mongodb-mongodb-sharded-mongos | cut -d'/' -f 2) -- mongo -u "root" -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval 'db.getSiblingDB("admin").createUser({user:"'"${NEW_MONGO_USER}"'",pwd:"'"${NEW_MONGO_USER_PW}"'",roles:[{role:"readWrite",db:"'"${NEW_MONGO_DB}"'"},{role:"readWrite",db:"celery_jobs"},{role:"SystemRole",db:"admin"},"clusterManager"]});'

echo "Enabling Sharding"
kubectl --namespace=${NAMESPACE} exec $(kubectl --namespace=${NAMESPACE} get pods -o name | grep -m1 mongodb-mongodb-sharded-mongos | cut -d'/' -f 2) -c mongos -- mongo -u "root" -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval "sh.enableSharding('${NEW_MONGO_DB}');"

```

(yes, my local script is boring and calls the mongodb-deployment `mongodb` :-) )

This snippet also ensures that sharding is enabled (I was not sure whether or not that is done during startup as well seeing that I did not find the database being created before) and increases the oplog size so that replication is easier on a busy cluster (in case you want to add a config variable for that as well when writing the init scripts).

**Comment by Yaskier** [comment]
Could you at least change the README and the documentation since it does not matches the variables are not being used at all?

**Comment by javsalgar** [comment]
Hi,

@Yaskier here's the PR https://github.com/bitnami/charts/issues/1655

**Comment by Yaskier** [comment]
Thanks!!

**Comment by philippfreyer** [comment]
As happy as I am to see this closed, do you really want to close this ticket @javsalgar ? The comment of @miguelaeh sounded to me that this should be fixed in a different way and that PR #1883  should only be a temporary solution. I would second that - it would be very comfortable to not have to create the user & db manually :-)

**Comment by javsalgar** [comment]
Sorry, it got closed automatically after merging. Just re-opened

**Comment by cuzzo333** [comment]
I wanted to add a comment that this looks to be happening for me on the mongodb (non-sharded) chart as well.  [mongodb chart](https://github.com/bitnami/charts/tree/master/upstreamed/mongodb)

I would assume this is due to using the same images which aren't currently passing in the env variables.  I can open a separate PR if that's best but since this seems more to do with the image rather than the helm chart(s), I didn't want to duplicate the issue.

**Comment by cuzzo333** [comment]
After some further testing of this issue I think that the customer user, password, and database **are** being created but the database is not persisting without any documents being inserted so mongodb is dropping the database and in turn dropping the user and password.

In my values file I've defined something like below:
```
usePassword: true
# existingSecret: name-of-existing-secret
# mongodbRootPassword:
mongodbUsername: user
# mongodbPassword:
mongodbDatabase: database
```
I also have some custom init scripts being passed in by adding them to the /files/docker-entrypoint-initdb.d/ directory.  Using these scripts I'm creating a few collections and inserting documents.  With this configuration I am able to use the $MONGODB_ROOT_PASSWORD, $MONGODB_USER, and $MONGODB_PASSWORD variables with no issues.  As per the documentation $MONGODB_ROOTPASSWORD and $MONGODB_PASSWORD are generating random strings.  All of my collections and documents insert correctly and I'm able to connect to the database and it appears everything is working great.

When I test without my scripts being passed in to the container, as noted above the custom database is not present and obviously then the custom user isn't being created either.

If this behavior can be further confirmed and verified, can a default document be passed in when creating the custom database and user?  Or possibly adding documentation to the README that a requirement for passing in a custom database and user is to also add a custom script to the /files/docker-entrypoint-initdb.d/ directory that inserts at least one document into the custom database?

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the information! :) I think that this should go to a different issue, let me create it for you

**Comment by javsalgar** [comment]
We will continue the conversation in https://github.com/bitnami/bitnami-docker-mongodb/issues/201

**Comment by drcrook1** [comment]
I too appear to be having this same issue.  I set the values in a db_config.yaml which is passed on helm create.  I then exec into a pod which should have access and attempt to connect via pymongo with no success & authentication failed.

**Comment by link-webcreations** [comment]
Hello,
I'm facing the same issue with the latest version of the chart.

Despite a custom mongodbDatabase, mongodbUsername and mongodbPassword defined in the charts values.yaml (and the file being used when deploying the chart), no custom database or user are created.

Regards

**Comment by javsalgar** [comment]
Hi,

For the time being, we removed these values as it was still not implemented. However, would the initScriptsCM and initScriptsSecrev values (where you can point to confirmaps/secrets with scripts to execute during initialization) work for you? It is very flexible (note that you would need to add logic to check the kind of node, as the scripts get mounted in all the nodes).

**Comment by katboddy** [comment]
Hey I am getting the same issue (custom db, user and password not being created). Could you point me to an example how to set these with initScriptsCM or (preferably) initScriptsSecret?

**Comment by philippfreyer** [comment]
@katboddy I am afraid that I cannot tell you how to do this using an initScript, however I can tell you the kubectl commands that I am running after the database is clustered together in order to create my users - these are kubectl commands that execute commands on the Mongodb shell. Thus they should be portable into scripts as long as you manage to implement waiting for the cluster to shard properly:

```
kubectl --namespace=${NAMESPACE} exec $(kubectl --namespace=${NAMESPACE} get pods -o name | grep -m1 mongodb-mongodb-sharded-mongos | cut -d'/' -f 2) -c mongos -- mongo -u "root" -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval 'db.getSiblingDB("admin").createRole({ role: "SystemRole", privileges: [{resource:{db:"admin",collection:""},actions:["killop","inprog"]}, {resource:{db:"omg",collection:""},actions:["killop","inprog"]}, {resource:{db:"celery_jobs",collection:""},actions:["killop","inprog"]}], roles: [] });'
kubectl --namespace=${NAMESPACE} exec $(kubectl --namespace=${NAMESPACE} get pods -o name | grep -m1 mongodb-mongodb-sharded-mongos | cut -d'/' -f 2) -- mongo -u "root" -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval 'db.getSiblingDB("admin").createUser({user:"'"${NEW_MONGO_USER}"'",pwd:"'"${NEW_MONGO_USER_PW}"'",roles:[{role:"readWrite",db:"'"${NEW_MONGO_DB}"'"},{role:"readWrite",db:"celery_jobs"},{role:"SystemRole",db:"admin"},"clusterManager"]});'

echo "Enabling Sharding"
kubectl --namespace=${NAMESPACE} exec $(kubectl --namespace=${NAMESPACE} get pods -o name | grep -m1 mongodb-mongodb-sharded-mongos | cut -d'/' -f 2) -c mongos -- mongo -u "root" -p "${NEW_MONGO_ROOT_PW}" --authenticationDatabase admin --authenticationMechanism=SCRAM-SHA-256 --eval "sh.enableSharding('${NEW_MONGO_DB}');"
```

NEW_MONGO_ROOT_PW is a password that I previously generated myself:
`NEW_MONGO_ROOT_PW=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)`
 It is passed as the `mongodbRootPassword` into the helm deployment's values.yaml as well.

The main issue that you will most likely have (or not, I am not sure if initScripts may be able to wait until a cluster was sharded) is to wait until the cluster is ready to be configured. Do it too early and there will be issues with inconsistent data. My previous post https://github.com/bitnami/charts/issues/1655#issuecomment-558206352 contains all my kubectl commands to wait for the cluster to be ready, then adjust the oplog size and then create user accounts. 

I hope that at least points you into a good direction.

**Comment by katboddy** [comment]
Thank you @philippfreyer . That's definitely a good place for me to start.

**Comment by alrf** [comment]
If you need to create only one user/pw/db, my workaround is:
```
common:
  extraEnvVars:
    - name: MONGODB_USERNAME
      value: "myuser"
    - name: MONGODB_PASSWORD
      value: "mypassword"
    - name: MONGODB_DATABASE
      value: "mydb"
``` 

How to use `initScriptsCM`:
1) Create ConfigMap `kubectl -n mongodb create configmap mongodb-scripts --from-file=manage.js`
Content of the `manage.js`, for example:
```
sleep(10000); // it's required to wait primary back after initial restart
db.getSiblingDB('newdb').createUser({ user: 'newuser', pwd: 'newpassword', roles: [{role: 'readWrite', db: 'newdb'}] });
```
2) Use `mongodb-scripts` CM in `initScriptsCM` in `common` section:
```
common:
  initScriptsCM: mongodb-scripts
```

**Comment by miguelaeh** [comment]
Hi guys,
thank you very much for sharing your solutions!

**Comment by thecb4** [comment]
I have tried this solution by including the configMap as part of a helm chart. The script gets loaded as a ConfigMap but mongo never uses it. I've changed the sleep timing  to 5 min and still nothing. It's like the initScriptsCM command is ignored

**Comment by javsalgar** [comment]
Hi,

Do you see a line similar to this in the node?

```
Loading user's custom files from
```

**Comment by thecb4** [comment]
@javsalgar I think I found the issue last night. I had to include the authSource as the database I was connecting to and everything works now.

**Comment by pankaj-dahiya** [comment]
Is this thing - creating custom user and DB is that complicated that bitnami team is still unable to implement that!

**Comment by Shilagrawal** [comment]
> Is this thing - creating custom user and DB is that complicated that bitnami team is still unable to implement that!

I am also facing the same issue, This was working fine 2 months back with helm passing mongoUsername and mongoPassword for adding a new user however now that  doesnt work I also tried to install older chart versions of 4.4.12 4.4.10 no luck where as same charts worked for me 2 months back with these values did something change here how do i overcome going to each shard and then creating a user is not a viable solution !!

**Comment by carrodher** [comment]
Changes are not modified retroactively when a version is released in the Helm repository that is an immutable package. Both, in terms of Helm chart code, but also in terms of the container images.

If you're still facing any issues, please create a separate ticket providing the specific information for your use case and environment so it's easy for us to try to reproduce the issue and/or provide an answer

**Comment by Shilagrawal** [comment]
> I use initdb script to solve this problem:
> 
> ```
> my_init_script.sh: | 
>   #!/bin/bash 
>   echo "Create Database and Relative Users." 
>   #Create New Users echo 'db.createUser({user:"${dbUser}",pwd:"${dbPassword}",roles:[{role:"dbAdmin", db:"${dbName}"}]});'> /tmp/crtuser.js 
>   chmod 755 /tmp/crtuser.js 
>   mongo admin -u 'root' -p '${rootPassword}' /tmp/crtuser.js 
>   #Insert Test Data 
>   echo 'db.${dbName}.insert({test:"ok",status:"success"});'> /tmp/insinfo.js 
>   chmod 755 /tmp/insinfo.js 
>   mongo ${dbName} -u '${dbUser}' -p '${dbPassword}' /tmp/insinfo.js
> ```
> 
> I hope it useful for you.

Where do one add these lines in which file or where exactly so that each pods creates a user in a sharded deployment ?

**Comment by Shilagrawal** [comment]
> This is part of the values.yaml. Please note in order to not mix topics, the best option is to create a separate issue for your use case when you can explain what is your current situation by filling the template that appears when creating a new ticket.

#10483 created one
