### ISSUE TITLE
[bitnami/mediawiki] Buggy behavior in Mediawiki MariaDB secret logic

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#16579]
### Name and Version

bitnami/mariadb 15.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The logic in the Mediawiki chart for specifying an existing Secret for MariaDB is flawed and inflexible.

If I try to pass `mariadb.auth.existingSecret`, which is a [valid parameter of the downstream chart](https://github.com/bitnami/charts/blob/8f2277440b976d52785ba9149762ad8620a73d1f/bitnami/mariadb/values.yaml#LL139C8-L139C8), it is ignored. The reason it is ignored is because of the buggy helper function `mediawiki.databaseSecretName`.

https://github.com/bitnami/charts/blob/8f2277440b976d52785ba9149762ad8620a73d1f/bitnami/mediawiki/templates/_helpers.tpl#LL108C13-L108C41

This helper function should, but currently does not, look for `mariadb.auth.existingSecret`. It simply makes the hard assumption that the secret name will be `{{ include "mediawiki.mariadb.fullname" . }}`.

This is not in line with the rest of the charts in this repository that have database dependencies.

### What is the expected behavior?

Allow me to use `mariadb.auth.existingSecret` properly.

### What do you see instead?

The mediawiki helm chart will force the use of a Secret called `mediawiki-mariadb` (or whatever `include "mediawiki.mariadb.fullname" .` evaluates to).

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by brsolomon-deloitte** [comment]
Not stale, please reopen

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/mediawiki#community-supported-solution).

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
