### ISSUE TITLE
[minio] Passwords error on dry run with existingSecret

### ISSUE THREAD

**Issue by c4tz** [bitnami/charts#16571]
### Name and Version

bitnami/minio 12.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

0. `$ cat pw.yaml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  root-user: admin
  root-password: test-password
```
1. `$ kubectl apply -f pw.yaml`
2. `$ helm install --wait -f values.yaml minio oci://registry-1.docker.io/bitnamicharts/minio`
3. `$ helm upgrade --dry-run --wait -f values.yaml minio oci://registry-1.docker.io/bitnamicharts/minio`

### Are you using any custom parameters or values?

```yaml
auth:
  existingSecret: minio
```

### What is the expected behavior?

The command should exit with code 0 and show no diff.

### What do you see instead?

```
Pulled: registry-1.docker.io/bitnamicharts/minio:12.4.4
Digest: sha256:c850f774f276f7b1213308c86a702a6709c09ed423bf14143120798b792df75c
Error: UPGRADE FAILED: execution error at (minio/templates/NOTES.txt:88:4):
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$ROOT_PASSWORD' to the command. To get the current value:

        export ROOT_PASSWORD=$(kubectl get secret --namespace "default" minio -o jsonpath="{.data.root-password}" | base64 -d)
```

### Additional information

I'm not sure wether this was introduced in https://github.com/bitnami/charts/pull/14356 . The changes make sense to me, but someting seems to be off.

### Impact

This makes the chart unusable with `helmfile`, which uses `helm diff`, which in turn uses `helm upgrade --dry-run`.

**Comment by dcardellino** [comment]
Also experiencing the same issue with helmfile diff

**Comment by corico44** [comment]
Hello,

Have you tried to solve the error by following this guide: https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases?

**Comment by c4tz** [comment]
Yes, I had a look at that guide before. But I think it is not applicable here, because the credentials are set in the `existingSecret`, as described above.

**Comment by corico44** [comment]
@c4tz I see that you have opened a PR to correctly modify the documentation. Thank you so much. We will review it as soon as possible!
