### ISSUE TITLE
[influxdb] enabling tls for LoadBalancer services

### ISSUE THREAD

**Issue by kbakk23** [bitnami/charts#16570]
### Name and Version

bitnami/influxdb 5.5.2

### What is the problem this feature will solve?

The tls support in case of LoadBalancer service being selected and without the usage of ingress.

### What is the feature you are proposing to solve the problem?

1- Add new tls enable value and secret option 
2- The secret should contain tls.crt and tls.key
3- The secret should be mounted to be used as files in order to add them for influnxdb config to support tls
4- The configmap for influxdb.conf should be updated to update https-enabled value, tls-key and tls-cert paths

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
