### ISSUE TITLE
Kafka Helm Chart v22.1.1: KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller

### ISSUE THREAD

**Issue by anonymc207** [bitnami/charts#16593]
### Name and Version

Kafka Helm Chart 22.1.1 

### What architecture are you using?

None

### What steps will reproduce the bug?

- I wanted to update the chart from v16.2.12 to 22.1.1
-The pods could not be started because of the following error:
`KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller`
This variable should not be set manually because the script kafka_scripts will set it.

```bash
#!/bin/bash

ID="${MY_POD_NAME#"main-kafka-"}"
# If process.roles is not set at all, it is assumed to be in ZooKeeper mode.
# https://kafka.apache.org/documentation/#kraft_role

if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
    if [[ $KAFKA_CFG_PROCESS_ROLES == "" ]]; then
        export KAFKA_CFG_BROKER_ID="$(grep "broker.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
    else
        export KAFKA_CFG_NODE_ID="$(grep "node.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
    fi
else
    if [[ $KAFKA_CFG_PROCESS_ROLES == "" ]]; then
        export KAFKA_CFG_BROKER_ID="$((ID + 0))"
    else
        export KAFKA_CFG_NODE_ID="$((ID + 0))"
    fi
fi

if [[ $KAFKA_CFG_PROCESS_ROLES == *"controller"* && -z $KAFKA_CFG_CONTROLLER_QUORUM_VOTERS ]]; then
    node_id=0
    pod_id=0
    while :
    do 
        VOTERS="${VOTERS}$node_id@main-kafka-$pod_id.main-kafka-headless.main-production.svc.cluster.local:9093"
        node_id=$(( $node_id + 1 ))
        pod_id=$(( $pod_id + 1 ))
        if [[ $pod_id -ge 5 ]]; then
            break
        else
            VOTERS="$VOTERS,"
        fi
    done
    export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=$VOTERS
fi

# Configure zookeeper client
```
How could this problem occur?

### What do you see instead?

KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller.

**Comment by carrodher** [comment]
It seems you are bumping several major versions at once, it is probable you can face different issues since backward compatibility is not guaranteed when upgrading to a new major version, and in this case, there are several at once.

[Here](https://github.com/bitnami/charts/tree/main/bitnami/kafka#upgrading) you can see the considerations to be taken into account when bumping the chart version between different majors.

**Comment by n5nk** [comment]
I have upgraded from v21.4.6 to v22.1, and I see the same issue
```
[38;5;6mkafka [38;5;5m11:27:32.15 [0m
[38;5;6mkafka [38;5;5m11:27:32.15 [0m[1mWelcome to the Bitnami kafka container[0m
[38;5;6mkafka [38;5;5m11:27:32.16 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mkafka [38;5;5m11:27:32.16 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mkafka [38;5;5m11:27:32.16 [0m
[38;5;6mkafka [38;5;5m11:27:32.16 [0m[38;5;2mINFO [0m ==> ** Starting Kafka setup **
[38;5;6mkafka [38;5;5m11:27:32.22 [0m[38;5;1mERROR[0m ==> KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller
[38;5;6mkafka [38;5;5m11:27:32.23 [0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
```

Apparently, meta.properties file doesnt have node.id, and since the config scripts depends on it, and hence failing.

```
 export KAFKA_CFG_NODE_ID="$(grep "node.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
```

Current meta.properties:
```
I have no name!@kafka-1:/$ cat /bitnami/kafka/data/meta.properties 
#
#Fri May 12 10:28:26 UTC 2023
broker.id=1
version=0
cluster.id=xxxxxxx-EWgw_-tA
I have no name!@kafka-1:/$ 
```

**Comment by n5nk** [comment]
Did a work around, since we are looking for `node.id`, which isnt present in meta.properties. I ended up finding for `broker.id` and that works.

see: `grep "broker.id"`

```
 export KAFKA_CFG_NODE_ID="$(grep "broker.id" "{{ .Values.logsDirs | splitList "," | first }}/meta.properties" | awk -F '=' '{print $2}')"
`

**Comment by n5nk** [comment]
I see one more issue as part of the upgrade from v21.4.6 to v22.1. I see all the messages are lost. Do I need to set any property ?? Am I missing anything..

**Comment by anonymc207** [comment]
My workaround is deleting the meta.properties. I think, all the messages are lost, because Kafka with Kraft is not compatible with the old one.

**Comment by n5nk** [comment]
I just saw the [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-833%3A+Mark+KRaft+as+Production+Ready#KIP833:MarkKRaftasProductionReady-Kafka3.4(released):~:text=Mark%20KRaft%20as%20production%2Dready%20for%20new%20clusters) data migration from zk to KRaft is proposed for May 2023 release in v3.5.

**Comment by jnt2007** [comment]
I found a workaround, but it is not useful, because **all data lost from topics**.

Before the upgrade to Helm Chart v22.1.1 need to add `node.id` parameter into `meta.properties` on every node
```bash
echo "node.id=0" > /bitnami/kafka/data/meta.properties
```
Tried an upgrade from Helm Chart v17.1.0

**Comment by ayushsharma82** [comment]
+1 Tried installing kafka again and it still throws `ERROR ==> KRaft requires KAFKA_CFG_NODE_ID to be set for the quorum controller`

**Comment by ayushsharma82** [comment]
Trying to switch to kraft for my deployment was a big mistake. Switching back to zookeeper for now until this release has been tested by many people.

**Comment by LarsBingBong** [comment]
I totally think that it would be wonderful if someone gave this a look. Thanks. Quite important, if possible, to be able to upgrade a Kafka cluster an switch to this new of doing this with KRaft.

**Comment by carrodher** [comment]
We are doing an evaluation of the current Kraft approach used by the bitnami/kafka Helm chart, as the outcome of this evaluation, we expect to improve the documentation and the logic around this new deployment approach.

**Comment by LHozzan** [comment]
Hello.
Maybe a late, but ...
I think, that source of the problem is discussed [here](https://github.com/bitnami/containers/issues/33271). It seems, that `BROKER_ID_COMMAND` was accidentally omitted.
Hope that helps.

**Comment by LHozzan** [comment]
@carrodher or @jotamartos any news about my [PR](https://github.com/bitnami/containers/pull/34152)?

**Comment by carrodher** [comment]
The latest comment still apply:
> Sorry for the delay here @LHozzan. We are reviewing other issues with the Bitnami Kafka container and we want to come up a solution that is valid in all cases. Will update the ticket when we have more information.

We are doing some major refactors in Kafka with Kraft mode, we will update the different issues/PRs once completed

**Comment by LHozzan** [comment]
> The latest comment still apply:

Thank you, but it is possible tell your bot to let this case opened, until will be fixed? Or it is possible to hold the issue opened without placing any comments?

Thank you!

**Comment by jacek-jablonski** [comment]
Should it work now in v23.0.1? I'm still affected by this error and unable to upgrade.

values.yaml:
```
kafka:
  metrics:
    kafka:
      enabled: true

  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
      nodePorts: [30870]
      loadBalancerIPs: ["xxx"]
```

**Comment by carrodher** [comment]
We're working on a major refactor of the Kafka Helm chart and how it works in Kraft mode. Although there is not specific ETA, we will create a PR with those major changes and merge it once reviewed.

**Comment by venkatzoomcar** [comment]
Getting same issues  while updating the kafka to latest version

**Comment by LHozzan** [comment]
I hope, that problem will be [soon solved](https://github.com/bitnami/containers/issues/33271#issuecomment-1635848840).

**Comment by n5nk** [comment]
@migruiz4 Just checking, does this support data migration from zk mode to raft too? As per the [kafka v3.5 guide](https://kafka.apache.org/documentation.html#kraft_missing:~:text=ZooKeeper%20to%20KRaft%20migration%20is%20considered%20an%20Early%20Access%20feature%20and%20is%20not%20recommended%20for%20production%20clusters.) I see its still early access.

**Comment by migruiz4** [comment]
Hi @n5nk,

Yes, the new architecture in 24.x.x has been designed with two purposes in mind:
- Users should be able to deploy a cluster with dedicated nodes.
- Migrating from Zookeeper mode to KRaft mode is possible with a single deployment.

You can find our migration guide here: https://github.com/bitnami/charts/blob/main/bitnami/kafka/README.md#migrating-from-zookeeper-early-access

It is tagged as 'Early Access' because the core functionality is still in Early Access and may change in the future: https://docs.confluent.io/platform/current/installation/migrate-zk-kraft.html
