### ISSUE TITLE
[contour] missing CRDs for gateway api

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#16598]
### Name and Version

bitnami/contour 11.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Review https://projectcontour.io/resources/compatibility-matrix/
2. Note gateway API support for version of contour
3. install helm chart
4. kubectl get crd |grep networking.k8s.io
5. note missing CRDs

### Are you using any custom parameters or values?

None

### What is the expected behavior?

The Gateway CRDs for the contour gateway API should be installed

### What do you see instead?

No Gateway CRDs

### Additional information

Since this is an optional feature, it should probably be behind its own flag not just the `contour.manageCRDs` boolean.

It might make sense to have just a gateway-crds chart so other controllers can just depend on that chart for their needs and maybe avoid duplicates.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jcpunk** [comment]
I still think this would be useful
