### ISSUE TITLE
[bitnami/mysql] metrics setup is incompatible with recommended setup for mysqld_exporter

### ISSUE THREAD

**Issue by Yaytay** [bitnami/charts#16606]
### Name and Version

bitnami/mysql 9.7.1

### What is the problem this feature will solve?

The docs for mysql_exporter https://github.com/prometheus/mysqld_exporter recommend that the user for connecting to msyql have a limited set of connections, and good practice would have it with minimum required rights:
```sql
CREATE USER 'exporter'@'localhost' IDENTIFIED BY 'XXXXXXXX' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'localhost';
```
The existing templates don't provide a way to constrain the user.

### What is the feature you are proposing to solve the problem?

Modify the templates to allow the configuration of a custom metrics user, with credentials in a secret.
The user can be created in an initdbscript (will have to be a .sh picking up credentials from files) so that should not require template changes.

### What alternatives have you considered?

https://github.com/bitnami/charts/issues/16604 is related, but doesn't solve the same problem.
If that is used for getting the secret into the container then we just need a tweak to the template to allow the specification of the user.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! Would you like to submit a PR adding support for it?

**Comment by Yaytay** [comment]
I will do a PR, but it'll be dependent upon https://github.com/bitnami/charts/issues/16604 which has a pending PR already.
