### ISSUE TITLE
[minio] ERROR Unable to initialize console server's sockets: Specified port is already in use

### ISSUE THREAD

**Issue by thanhtoan1196** [bitnami/charts#16629]
### Name and Version

oci://registry-1.docker.io/bitnamicharts/minio 12.4.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install minio chart with this values:
```yaml
auth:
  rootUser: "admin"
  rootPassword: "rootPassword"

ingress:
  enabled: false

persistence:
  enabled: true
  storageClass: openebs-hostpath-retain
  size: 20Gi
```
2. See error: Unable to initialize console server's sockets: Specified port is already in use

### What do you see instead?

Logs:
```
 16:49:56.00 
 16:49:56.00 Welcome to the Bitnami minio container
 16:49:56.00 Subscribe to project updates by watching https://github.com/bitnami/containers
 16:49:56.00 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 16:49:56.01 
 16:49:56.01 INFO  ==> ** Starting MinIO setup **
minio 16:49:56.02 INFO  ==> Starting MinIO in background...
minio 16:50:01.03 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:50:01.10 INFO  ==> Stopping MinIO...
 16:50:01.19 INFO  ==> ** MinIO setup finished! **

minio 16:50:01.19 INFO  ==> ** Starting MinIO **
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.2023-05-04T21-44-30Z (go1.19.9 linux/amd64)

Status:         1 Online, 0 Offline. 
S3-API: http://localhost:9000 
Console: http://10.42.0.174:9001 http://127.0.0.1:9001   

Documentation: https://min.io/docs/minio/linux/index.html
Warning: The standard parity is set to 0. This can lead to data loss.
ERROR Unable to initialize console server's sockets: Specified port is already in use
      > Please ensure no other program uses the same address/port
Stream closed EOF for minio/minio-54c6d956bf-5lg9g (minio)
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MinIO container image or Helm chart but about how the application or environment is being used/configured:
```
ERROR Unable to initialize console server's sockets: Specified port is already in use
      > Please ensure no other program uses the same address/port
```

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by clrxbl** [comment]
I've gotten this issue in the last few weeks aswell. Rebooting the entire dedicated server (baremetal Kubernetes) resolved it once, but that's obviously not a great way of resolving it.

https://github.com/bitnami/charts/issues/7757#issuecomment-942612993 This workaround seems to do the trick for me.

**Comment by stockmind** [comment]
Backlinking this also here from #7757 :

Be careful if you have a registered a notification service like with `MINIO_NOTIFY_AMQP_ENABLE_<service>`, because if the credentials are wrong two things happen:

- Minio will NOT write any authentication errors or failures in the logs
- Minio's first process will not close properly generating the error mentioned in this issue about ports still occupied by Minio's previous process, it seems that authentication failure leads to zombie status for the first process or taking longer to close and release the ports
