### ISSUE TITLE
Postgresql Chart  is not mounting extendedConf properly

### ISSUE THREAD

**Issue by nightswimmings** [bitnami/charts#16623]
### Name and Version

bitnami/postgresql:12.5.X, bitnami/postgresql:12.4.X

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Define in chart:

```yaml
spec:
  values:
    primary:  
      extendedConfiguration: |
        max_connections = 200
```

Install, and see how the configmap postgres-extended-configuration is created and the postgres pod mounts the extended config in `/bitnami/postgresql/conf/conf.d/override.conf`. BUT, `postgresql.conf` is in `/opt/bitnami/postgresql/conf/postgresql.conf`, and has `include_dir = 'conf.d'`, but our files are in `/bitnami/...`, not in `/opt/bitnami`.
There's certainly a `/opt/bitnami/postgresql/conf/conf.d/` folder, but it's not a symlink, and the files are not copied there from the mounted volume

### What is the expected behavior?

values provided in extendedConf are well handled

### What do you see instead?

extended config files are not where expected

**Comment by nightswimmings** [comment]
By looking chart and values and templates I think it is obvious that a "cp /bitnami/postgresql/conf/conf.d/* /opt/bitnami/postgresqlconf/conf.d/" is required at some point of initialization, although I am unsure whether this is intended or not.

If it's intended, It would appreciate to know where it is the best point to add it (preferrably in documentation). I'm checking primary.command, primary.args, and initcontainers options but I am not clear on the side-effects.

Thanks a lot!

**Comment by fmulero** [comment]
I've just tested with the following commands and I don't see any relevant failure

```console
$ helm install postgresql bitnami/postgresql --set primary.extendedConfiguration="max_connections=444"
NAME: postgresql
LAST DEPLOYED: Tue May 16 16:54:10 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: postgresql
CHART VERSION: 12.4.3
APP VERSION: 15.2.0
...
To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/postgresql 5432:5432 &
    PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432

$ k exec -it postgresql-0 -- bash
I have no name!@postgresql-0:/$ PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432
psql (15.2)
Type "help" for help.
postgres=# show max_connections;
 max_connections 
-----------------
 444
(1 row)
````

Could you share the steps to reproduce it?

**Comment by fmulero** [comment]
Sorry for the delay, I think I found the reason. We are looking for the configuration files in the mounted volumen to allow users mount their own config files in the volume: https://github.com/bitnami/containers/blob/main/bitnami/postgresql/15/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L593-L596

In your case, the volume is mounted in `/data` and the configmap is mounted on `/bitnami/postgresql/conf/conf.d`, so the initialization script won't copy the config files to `/opt/bitnami/postgresql/conf/conf.d`.

I  am going to open an internal discussion about this topic. In my opinion the fix should go in one of these ways:
1. Mount the configmap over the data volume.
2. Mount the configmap in  the `/opt/bitnami/postgresql/conf/conf.d` directory.

Please feel free to open PR with any of the fixes, we will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by nightswimmings** [comment]
Thanks for the analysis!
I'd like to understand it, but I can't get where /data is related to the conf folders.
I mean now you kindly sent me the script part where this happens, but I see it copying from 
POSTGRESQL_MOUNTED_CONF_DIR to POSTGRESQL_CONF_DIR

Why is /data relevant in this context? Indeed /data is usually empty at the beginning of the pod lifecycle

I seem to understand that you mean POSTGRESQL_MOUNTED_CONF_DIR should be a subfolder of /data? Still I can't see the restriction on the section

**Comment by kapilcrest** [comment]
Any Update ? Still facing this issue.

**Comment by fmulero** [comment]
Hi @kapilcrest, thanks for using Bitnami charts.

Could you share more details or the steps to reproduce your issue? this tasks was opened 1 year ago, several changes were done from then and the original issue seems related to openshift configuration.
