### ISSUE TITLE
[bitnami/rabbitmq] Add option to set custom labels for volumeClaimTemplates

### ISSUE THREAD

**Issue by tbenatar55** [bitnami/charts#16639]
### Name and Version

bitnami/rabbitmq version: 11.15.0

### What is the problem this feature will solve?

Currently, Bitnami provides a convenient way to define volumeClaimTemplates configuration for statefulsets in RabbitMQ helm chart. However, there is no option to set custom labels for the volumeClaimTemplates, which can be limiting for users who need to organize their resources in a more specific way.
With this feature, users could set custom labels for volumeClaimTemplates, similar to how they can set labels for other Kubernetes resources. This would enhance the flexibility and organization the resources deployed on cluster.

### What is the feature you are proposing to solve the problem?

Add a new variable to set custom volumeClaim labels

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
