### ISSUE TITLE
Harbor exporter existingSecrets option

### ISSUE THREAD

**Issue by Harrys-git** [bitnami/charts#16665]
### Name and Version

bitnami/harbor:16.5.3

### What is the problem this feature will solve?

Currently you can add existing secret for most of the harbor services to keep passwords out of the config. Harbor exporter does not have this option.
The template is written so the exporter can only read the database password from harbor-core-envvars secret.

### What is the feature you are proposing to solve the problem?

Add existing secret in the exporter template to allow environment variables to be read from a custom secret.
or add existing secret for externalDatabase section of the harbor chart.

### What alternatives have you considered?

None.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Harrys-git** [comment]
Yeah I will get a PR together in the next few days.
