### ISSUE TITLE
[bitnami/clickhouse] extraOverride for clickhouse not work to grant privilledge for new user

### ISSUE THREAD

**Issue by KevinLiangX** [bitnami/charts#16671]
### Name and Version

docker.io/bitnami/clickhouse  23.4.1-debian-11-r0

### What architecture are you using?

None

### What steps will reproduce the bug?

bitnami clickhouse newest version  with 3s2r mode

default account set the new password,  and add the extraOverride configuration

![image](https://github.com/bitnami/charts/assets/40968187/5f35857b-ba45-457a-9214-67e13497d1d5)
create the user is normal, but can't grant the privilledge, command as below:
```
clickhouse-shard0-0.clickhouse-headless.default.svc.cluster.local :) CREATE USER 'newuser' IDENTIFIED BY 'password';

CREATE USER newuser IDENTIFIED WITH sha256_hash BY '55BEF6DFDDF180E4A4D61F0848F3DFBD34B179D0216A859D0F7B9C80644E8687' SALT '2A20CB10D0B2705FDF496E6D336C6F8CFB476B635AD4A2FF3EC2C3DA8CF27A0E'

Query id: a1b29cb0-50df-46e4-969d-ff2d853b9cff

Ok.

0 rows in set. Elapsed: 0.005 sec. 

clickhouse-shard0-0.clickhouse-headless.default.svc.cluster.local :) GRANT ALL ON *.* TO 'newuser';

GRANT ALL ON *.* TO newuser

Query id: 366ad4f2-eaeb-4a41-ab56-4cdcba7ef6cf


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.3.2):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, NAMED COLLECTION CONTROL, SYSTEM, dictGet, INTROSPECTION, SOURCES ON *.* WITH GRANT OPTION. (ACCESS_DENIED)


clickhouse-shard0-0.clickhouse-headless.default.svc.cluster.local :) SHOW GRANTS FOR default;

SHOW GRANTS FOR default

Query id: 1568dd71-4a51-4f52-b0cd-c2c84c358239

┌─GRANTS FOR default─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, KILL QUERY, KILL TRANSACTION, MOVE PARTITION BETWEEN SHARDS, ACCESS MANAGEMENT, SYSTEM, dictGet, INTROSPECTION, SOURCES, CLUSTER ON *.* TO default WITH GRANT OPTION │
│ GRANT ALTER NAMED COLLECTION, CREATE NAMED COLLECTION, DROP NAMED COLLECTION, SHOW NAMED COLLECTIONS ON * TO default WITH GRANT OPTION                                                                                                                     │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

what should i do for issue ?

### What do you see instead?

please see the output as above

**Comment by KevinLiangX** [comment]
updated the test result as below:

open the default user sql command with:
![image](https://github.com/bitnami/charts/assets/40968187/5d2d64ab-ba54-4f21-93a7-fce6d85360c0)
it works fine 
![image](https://github.com/bitnami/charts/assets/40968187/4d1f66b5-0635-4e9f-8894-0553a1429af8)

so what I suspect is that the updated configuration is placed in this  bitnami/etc/conf.d -> /etc/clickhouse-server/conf.d directory not in /etc/clickhouse-server/user.d directory .  Is there any other code being maintained here?

Is it possible to change such Settings ?

**Comment by KevinLiangX** [comment]
update my test ,  i changed the  statefulset yaml  as below:
{{- if or $.Values.extraOverridesConfigmap $.Values.extraOverrides }}
            - name: extra-config
              mountPath: /bitnami/clickhouse/etc/users.d/extra-configmap
conf.d ==> users.d . 
it is working now .
![image](https://github.com/bitnami/charts/assets/40968187/a4062b18-ab62-4109-b098-a3234c546270)
![image](https://github.com/bitnami/charts/assets/40968187/47841b0e-713c-4076-8956-754c8f28268b)


so  I think there are two scenarios here, update the conf in extraConfOverrides and extraUsesOverrides ，make two configmap to override the clickhouse configuration.

**Comment by KevinLiangX** [comment]
i closed the issue.  it seem that  conf.d and users.d is same. 
lack this configuration :
<show_named_collections>1</show_named_collections>
<show_named_collections_secrets>1</show_named_collections_secrets>

GRANT ALL ON *.* TO clickhouse_admin WITH GRANT OPTION;  can't work.

**Comment by EinavDanielDX** [comment]
Great, thanks!
