### ISSUE TITLE
[bitnami/wordpress] wordpress WP_HOME AND WP_SITEURL question

### ISSUE THREAD

**Issue by xyfleet** [bitnami/charts#16675]
### Name and Version

bitnami/wordpress 16.1.2

### What steps will reproduce the bug?

Based on the comment from @fmulero, I see the `wp_home` and `wp_siteurl` got updated, but cannot access the admin portal of the blog.

### What do you see instead?

we can easily access the blog through https://www.example.com/blog

**Comment by xyfleet** [comment]
@fmulero Hi Fran, thank you so much for your reply. I want to share your comment in another thread here. This works when I follow your steps to force running the initialization script. (not necessary to run helm upgrade in my case.) And my wp_home and wp_siteurl have /blog inside. 

```


ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /blog(/|$)(.*)
  pathType: Prefix


customPostInitScripts:
  wp-home-blog.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i "s|define( 'WP_HOME', 'http://' \. \$_SERVER\['HTTP_HOST'\] \. '/' );|define( 'WP_HOME', 'http://' \. \$_SERVER\['HTTP_HOST'\] . '/blog' );|g" /bitnami/wordpress/wp-config.php
    sed -i "s|define( 'WP_SITEURL', 'http://' \. \$_SERVER\['HTTP_HOST'\] \. '/' );|define( 'WP_SITEURL', 'http://' \. \$_SERVER\['HTTP_HOST'\] . '/blog' );|g" /bitnami/wordpress/wp-config.php
    wp cli cache clear
    chmod -w /bitnami/wordpress/wp-config.php
```

**Comment by xyfleet** [comment]
one more question here:

For now, I can access example.com/blog but some style files are not found. Is this related to my ingress setting? (btw, I am using alb ingress instead of nginx, which does not have URL re-write feature.)

Please see the screenshot below. 

<img width="1618" alt="image" src="https://github.com/bitnami/charts/assets/113627389/b0382ffc-ba81-42ac-b9a4-a40791d2bfe4">

**Comment by xyfleet** [comment]
Failed to access the admin portal.

I tried to access the wordpress admin portal and failed. 
I input `www.example.com/blog/admin`, the link automatically switched to `example.com/wp-admin`

<img width="756" alt="image" src="https://github.com/bitnami/charts/assets/113627389/41bfaccf-8337-4395-81c6-cd73bc3162e4">

<img width="648" alt="image" src="https://github.com/bitnami/charts/assets/113627389/1b992107-435c-4bbe-a5d8-d37dcc71af0a">

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami WordPress container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by xyfleet** [comment]
@dgomezleon Hi thanks for your update. I want to put the latest update here. Please help take a look. 
1: I updated the wp_home and wp_siteurl based on @fraFran's comment.  https://github.com/bitnami/charts/issues/16434#issuecomment-1549420868
```
wp_home: www.example.com/blog
wp_siteurl: www.example.com/blog
```
please see the code below:
```
customPostInitScripts:
  wp-home-blog.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i "s|\$_SERVER\['HTTP_HOST'\] = '127.0.0.1';|\$_SERVER\['HTTP_HOST'\] = 'www.example.com';|g" /bitnami/wordpress/wp-config.php
    sed -i "s|define( 'WP_HOME', 'http://' \. \$_SERVER\['HTTP_HOST'\] \. '/' );|define( 'WP_HOME', 'http://' \. \$_SERVER\['HTTP_HOST'\] . '/blog' );|g" /bitnami/wordpress/wp-config.php
    sed -i "s|define( 'WP_SITEURL', 'http://' \. \$_SERVER\['HTTP_HOST'\] \. '/' );|define( 'WP_SITEURL', 'http://' \. \$_SERVER\['HTTP_HOST'\] . '/blog' );|g" /bitnami/wordpress/wp-config.php
    wp cli cache clear
    chmod -w /bitnami/wordpress/wp-config.php
```

2: I also manually updated the wp_options table in DB. 
```
option_name: option_value
siteurl  --> http://www.example.com/blog
home   --> http://www.example.com/blog
```

The issue I am facking now is:
1: Some styles files cannot display correctly. 
<img width="1618" alt="image" src="https://github.com/bitnami/charts/assets/113627389/a8cde4b3-2035-4eb4-b3de-a779396985f1">


2: failed to access www.example.com/blog/admin portal and got error message:
www.example.com redirected you too many times.

<img width="437" alt="image" src="https://github.com/bitnami/charts/assets/113627389/be835a75-ce01-4dfb-b7be-019f01d4e19c">


3: In the Sample Page, I clicked "your dashboard", the page was redirected to `http://127.0.0.1/wp-admin/` 
As I mentioned at the beginning, I have replaced 127.0.0.1 with www.example.com. Why do I see this 127.0.0.1 again here?
<img width="1647" alt="image" src="https://github.com/bitnami/charts/assets/113627389/9cc4e3e1-3e88-4378-afb1-92a20657817f">

**Comment by slayerjain** [comment]
@xyfleet did you ended up solving this? I'm stuck with the exact same problem.

**Comment by lynh7** [comment]
Hi @xyfleet, I'm having the same issue the css and styles are being due to my connection is **'https'** but the wordpress itself request style to **'http'** so the browser just blocks all the requests for security reason. Might I ask you about this issue and did you solve it? Thanks

<img width="550" height="109" alt="Image" src="https://github.com/user-attachments/assets/6096a497-4d27-4144-9c73-5f377fe8a834" />
