### ISSUE TITLE
[bitnami/postgresql-ha] Add checksum annotations

### ISSUE THREAD

**Issue by bdun1013** [bitnami/charts#16680]
### Name and Version

bitnami/postgresql-ha 11.6.1

### What is the problem this feature will solve?

Currently, if a ConfigMap or Secret is updated, then the pods must be manually restarted for the changes to be picked up. 

### What is the feature you are proposing to solve the problem?

Checksum annotations should be added to automatically roll pods: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

Checksum annotations are present in a subset of the bitnami helm charts.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
