### ISSUE TITLE
[bitnami/nginx-ingress-controller] Configuration of Real visitor IP using configmap 

### ISSUE THREAD

**Issue by msnagananda** [bitnami/charts#16704]
### Name and Version

bitnami/nginx-ingress-controller 9.3.18

### What architecture are you using?

None

### What steps will reproduce the bug?

Basically here we want to track from where the users are visiting the website therefore have introduced matomo but Unfortunatly, the geolocation cannot be tracked based on IP as real ip is not passed through the matomo pod only internal IP is passed and as of now only cluster internal IP is been seen 
Since we wanted to track  the real visitor IP visiting the website the application is behind the Ingress controller in kubernetes environment 

These are the content of the config map 
```
use-proxy-protocol: "true"
  compute-full-forwarded-for: "true"
  brotli-level: "6"
  brotli-types: "text/xml image/svg+xml application/x-font-ttf image/vnd.microsoft.icon application/x-font-opentype application/json font/eot application/vnd.ms-fontobject application/javascript font/otf application/xml application/xhtml+xml text/javascript application/x-javascript text/plain application/x-font-truetype application/xml+rss image/x-icon font/opentype text/css image/x-win-bitmap"
  use-forwarded-headers: "false"
  real-ip-header: proxy_protocol
  enable-brotli: "true"
  http-snippet: "proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=static-cache:10m max_size=10g  inactive=1d use_temp_path=off;"
```

Here when i change the **real-ip-header:X-forwarded** for these changes are not reflecting in configmap 
that is where i am facing the issues

### What do you see instead?

Here when the latest values are getting updated in config map its not reflecting  instead still showing old values

**Comment by javsalgar** [comment]
Hi!

I believe that the issue is in the deployment.yaml file

```
  27   template:
  28     metadata:
  29       {{- if .Values.podAnnotations }}
  30       annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8
     }}
  31       {{- end }}
  32       labels: {{- include "common.labels.standard" . | nindent 8 }}
  33         app.kubernetes.io/component: controller
  34         {{- if .Values.podLabels }}
  35         {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
  36         {{- end }}
```

We should add something like this in the annotations section

```
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

This way, the pods would get redeployed on configmap changes via helm upgrade. Would you like to submit a PR with the changes?

**Comment by javsalgar** [comment]
Thank you!
