### ISSUE TITLE
[bitnami/airflow] Chart lacks configuration for existingSecret key names for postgresql/redis

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#16725]
### Name and Version

bitnami/airflow 14.2.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

For both the `postgresql` and `redis` subcharts, the `airflow` subchart hard-codes the key names for `existingSecrets` and does not allow the user to configure them through `redis.auth.existingSecretPasswordKey` or `postgresql.auth.secretKeys`.

The key names should be configurable. See:

- https://github.com/bitnami/charts/blob/f865b32c3c465ac7c2a2bdd177758a15c5e78595/bitnami/airflow/templates/_helpers.tpl#LL273C2-L273C2
- https://github.com/bitnami/charts/blob/f865b32c3c465ac7c2a2bdd177758a15c5e78595/bitnami/airflow/templates/_helpers.tpl#L354

### What is the expected behavior?

As a user of the `airflow` chart, I should be able to use an existing Secret for both postgresql and redis, and set `redis.auth.existingSecretPasswordKey` or `postgresql.auth.secretKeys`

### What do you see instead?

The key names are hardcoded to `password` for postgresql and `redis-password` for redis.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by brsolomon-deloitte** [comment]
Related to https://github.com/bitnami/charts/issues/16579
