### ISSUE TITLE
[bitnami/spark] Override application specific logging configuration on a Spark cluster

### ISSUE THREAD

**Issue by ardesai** [bitnami/charts#16734]
### Name and Version

bitnami/spark latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I have created a simple release using the spark chart and trying to override the log file as documented here:
https://spark.apache.org/docs/latest/running-on-yarn.html#configuration

I am aware that this is the documentation for a yarn cluster however I couldn't find anything related on the Kubernetes Spark cluster.

So following the above documentation, I am supplying the `log4j2.properties` file in the spark-submit to override for the specific application run:
```
kubectl exec -ti --namespace tenant-emsdev-core spark-abhi-em-1890-master-0 -- spark-submit \
  --files "/tmp/log4j2.properties"\
  --conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:log4j2.properties" \
  --conf "spark.executor.extraJavaOptions=-Dlog4j.configuration=file:log4j2.properties" \
  --master spark://spark-abhi-em-1890-master-svc:7077 \
  --class org.apache.spark.examples.SparkPi examples/jars/spark-examples_2.12-3.3.2.jar 5
```
I have the `log4j2.properties` file locally in `/tmp` folder.

### Are you using any custom parameters or values?

Yes, as mentioned in the command above.

### What is the expected behavior?

I am expecting `spark-submit` run to use the supplied log4j file.

### What do you see instead?

However it is not using the file and having the default logging behaviour.

### Additional information

I have tried to copy the same `log4j2.properties` at `/opt/bitnami/spark/conf` on the master pod, and it is picking this file up. So there isn't any issue with the configuration file.

**Comment by ardesai** [comment]
Hi, do you mean Spark Bitnami image?
I haven't checked.

**Comment by javsalgar** [comment]
I mean with the developers of Spark: https://issues.apache.org/jira/projects/SPARK/issues
