### ISSUE TITLE
[bitnami/elasticsearch] Parameter to update ELASTICSEARCH_NODE_ROLES in elasticsearch charts

### ISSUE THREAD

**Issue by sreenilearn** [bitnami/charts#16747]
### Name and Version

bitnami/elasticsearch:19.5.9

### What is the problem this feature will solve?

We need a suggestion or workaround for the following scenario. None of the elastic search Statefulsets has a provision to add roles. We need a "remote_cluster_client" role in either "master" or "coordination" nodes and we didn't see any provision to pass this value as variable. Environment variable ELASTICSEARCH_NODE_ROLES defaulted with "master", "data", "" respecitevly in master , data , controller Statefulsets.

Any alternative option to define the required roles in the above charts?

https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/coordinating/statefulset.yaml

### What is the feature you are proposing to solve the problem?

 for the environment variable ELASTICSEARCH_NODE_ROLES following definition {{ .Values.nodeRoles | quote }} might help

### What alternatives have you considered?

Absolutely. We would like to know any alternative way to resolve the problem

**Comment by fevisera** [comment]
Hi @sreenilearn,

Thank you for sharing this need with us! It is indeed an interesting functionality. 

PR #17003 has been created to implement this feature. If you have any other suggestions or questions about it, please feel free to share them.

Thanks!

**Comment by fevisera** [comment]
As mentioned in #17003 the issue has been resolved. So, I'm closing this issue.

**Comment by sreenilearn** [comment]
@fevisera - one clarification. I noticed that change is available only in the master and data statefulset. Would it be possible to add this to the coordination statefulset as well?

**Comment by fevisera** [comment]
Hi @sreenilearn,

Adding additional roles to the coordinating statefulset in Elasticsearch is not necessary since coordinating nodes already have a specific coordinating role. They act as intermediaries, handling search and write requests from clients and distributing them to the appropriate data nodes. Therefore, there is no need to assign additional roles to the coordinating statefulset.

Please, let me know if I'm missing something.

**Comment by sreenilearn** [comment]
@fevisera - Thank you for the details and explanation. What we are trying to achieve using coordinating statefulset is adding remote_cluster_client role. We cannot access metrics without enabling this role in coordinating node. We tried enabling remote_cluster_client role in the master and data nodes but couldn't succeed in accessing metrics and metrics UI working. Appreciate the help and support.

PS: Our team was researching alternative options, and I will probably add more details by tomorrow.

**Comment by migruiz4** [comment]
Hi @sreenilearn,

My bad, I misunderstood how [coordinating nodes](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html) work in Elasticsearch, as I initially thought only nodes without roles would act as coordinators, but it is the opposite, all nodes have implicit the coordinator role so any roles could be added without risking the node won't act as coordinator.

Although, I would like to warn to be careful with this feature, as not all nodes in the architecture are configured with persistence (e.g. coordinating and ingest) and that could be problematic if certain roles are added like `data`, `data-cold` and `data-warm`.

I have created this PR https://github.com/bitnami/charts/pull/17104 which I hope fulfills your needs.

Thanks for your suggestions!
