### ISSUE TITLE
Support memcached warm-restart

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#1685]
**Which chart**:

stable/memcached, latest version

**Description**

WDYT Adding support for https://github.com/memcached/memcached/wiki/WarmRestart ?
It could be an opt-in feature using a PVC.
This will make memcached upgrades less impacting, as the cache will survive restart.

**Steps to reproduce the issue:**

1. implement feature
2. do upgrades / restart
3. verify that cached elements are still present in mc

**Describe the results you received:**
State will be lost on upgrade

**Describe the results you expected:**
Keep state

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Version of Helm and Kubernetes**:
N/A

- Output of `helm version`:
N/A

- Output of `kubectl version`:
N/A

I've also forked the helm-project stable/mcrouter chart and I'm cleaning this up - let me know if you want it upstream.

**Comment by davidkarlsen** [comment]
Some more background: https://groups.google.com/forum/#!msg/memcached/faWH90ivfE4/QPVMGSKiBAAJ I guess this needs a bit more thinking. Ideally the volume should survive pod-recreates, but be mounted on tmpfs.

**Comment by juan131** [comment]
Hi @davidkarlsen 

Thanks so much for this great suggestion!

It's something we should consider for this chart for sure. It would be great to upgrade the Memcached chart without losing the current cache.

I just created an internal task to work on this feature and it will be added to our backlog.

**Comment by davidkarlsen** [comment]
Thanks - and WDYT about the mcrouter chart https://github.com/evryfs/helm-charts/tree/feature/mcrouter - are you interested in adopting it? It is a fork of https://github.com/helm/charts/tree/master/stable/mcrouter.
https://engineering.fb.com/web/introducing-mcrouter-a-memcached-protocol-router-for-scaling-memcached-deployments/ - adding mcrouter allows for replicating the cache - thereby having a highly-available mostly consistent cache.

**Comment by juan131** [comment]
Hi @davidkarlsen 

I think it could be a great solution. 

I don't know if the best approach would be to create an independent chart for this solution, or including it as part of this chart (similar to what we do with InfluxDB & InfluxDB Relay in the [InfluxDB chart](https://github.com/bitnami/charts/tree/master/bitnami/influxdb) or PostgreSQL & Pgpool in the [PostgreSQL HA chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha)).

Anyway, let me share your suggestion with the team.

**Comment by davidkarlsen** [comment]
I think this would mean using a statefulset (in order to do a pvc template).
Would you like a dual approach? deployment == no state, statefulset == state ?
Do you want a PR?

**Comment by juan131** [comment]
> Would you like a dual approach? deployment == no state, statefulset == state ?

That would be great. We have similar approaches in other charts (e.g. InfluxDB supports two approaches: `standalone` and `high-availability` based on the `architecture` parameter)

> Do you want a PR?

That would be great! 

We'll also need to create the corresponding container image for Mcrouter (instead of using `jphalip/mcrouter`) since we only relay on images maintained by Bitnami on our Helm charts.

**Comment by davidkarlsen** [comment]
@juan131 PTAL - Do you have any CI?

**Comment by davidkarlsen** [comment]
One more thing that is needed is to install a signal trap.

I tried using a lifecycle hook:
```
diff --git a/bitnami/memcached/templates/statefulset.yaml b/bitnami/memcached/templates/statefulset.yaml
index 19f76e0f..7af5b226 100644
--- a/bitnami/memcached/templates/statefulset.yaml
+++ b/bitnami/memcached/templates/statefulset.yaml
@@ -57,6 +57,12 @@ spec:
           ports:
             - name: memcache
               containerPort: 11211
+          {{- if .Values.persistence.enabled }}
+          lifecycle:
+            preStop:
+              exec:
+                command: ["/bin/sh", "-c", "/bin/kill", "-USR1", "1"]
+          {{- end }}
           livenessProbe:
             tcpSocket:
               port: memcache
```
But it does not seem to work. If I exec into the container and do `kill -USR1 1` it saves the state.

Maybe do this in a entrypoint/wrap memcached in a script? The handler could be installed conditionally on an env-var being set?

**Comment by juan131** [comment]
Sorry for the late response @davidkarlsen (it was a bank holiday in Spain these past days)

> Do you have any CI?

Yes, we have one but it's internal. I can trigger all the tests once the PR we consider it ready. We'd like to make the tests results public at some point.

> But it does not seem to work. If I exec into the container and do kill -USR1 1 it saves the state.

Did you try to use the same hook when using the `run.sh` script that comes with the image to start memcached?
