### ISSUE TITLE
[bitnami/mariadb-galera]  10.6.13  - Lock Issue

### ISSUE THREAD

**Issue by rsidhaarth** [bitnami/charts#16868]
### Name and Version

bitnami/mariadb-galera 10.6.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install MaraDB Galera 10.6.13 and try to deploy Magento and perform Reindex. Not only in Magento, I am seeing the same error in many other script.

### What do you see instead?

>  This version of MariaDB doesn't yet support 'GET_LOCK in cluster (WSREP_ON=ON)'

### Additional information

I am using MariaDB Galera for Magento 2 and when running the Deployment of Magento, I am getting error related to Lock. And this is not happening in older versions of Images.

**Comment by javsalgar** [comment]
Hi,

Looking at the error, it seems that this is an incompatibility issue with MariaDB Galera rather than an issue in the Bitnami packaging. My advice is to check with upstream MariaDB Galera devs.
