### ISSUE TITLE
[bitnami/postgresql] Using properties does not fully control created Service name for postgresql chart.

### ISSUE THREAD

**Issue by whitingjr** [bitnami/charts#16878]
### Name and Version

bitnamicharts/postgresql:12.5.5

### What architecture are you using?

None

### What steps will reproduce the bug?

1. `$ kubectl create namespace foo-bar`
2. `$ helm install --dry-run -n foo-bar frdemo-ds oci://registry-1.docker.io/bitnamicharts/postgresql --set-string nameOveride=frdemo-ds --set-string fullnameOveride=frdemo-ds  |grep frdemo-ds`

### Are you using any custom parameters or values?
```
nameOveride=frdemo-ds
fullnameOveride=frdemo-ds
```
### What is the expected behavior?
```yaml
name: frdemo-ds
```
### What do you see instead?
```yaml
name: frdemo-ds-postgresql
```
### Additional information

I want to control the created resource(s) name value. To exclude "-postgresql" is appended.

**Comment by corico44** [comment]
Hello @whitingjr,
The parameters are `nameOverride` and `fullnameOverride,` with two R's. So the command should be:
`helm install --dry-run -n foo-bar frdemo-ds oci://registry-1.docker.io/bitnamicharts/postgresql --set-string nameOverride=frdemo-ds --set-string fullnameOverride=frdemo-ds  | grep frdemo-ds`
