### ISSUE TITLE
[bitnami/elasticsearch] The data.heapSize parameter has no effect in version 7.12.1，please fix this

### ISSUE THREAD

**Issue by everythinggood** [bitnami/charts#16870]
### Name and Version

Bitnami/elasticsearch 7.12.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. i set the parameter into the values.yaml
![image](https://github.com/bitnami/charts/assets/7300430/92a04b98-0804-4120-937f-7dd7b299572a)
2. i watch the pod info
![image](https://github.com/bitnami/charts/assets/7300430/3cff8f45-abc3-47a3-8998-d0c568213972)
3. but the -xms and -xmx is not update,Still is 1024m
![image](https://github.com/bitnami/charts/assets/7300430/ca1c23e4-e77f-49d8-bfd4-0f803efbd722)

### Are you using any custom parameters or values?

i set the values.yaml

### What do you see instead?

still is -Xms1024m -Xmx1024m, .Values.data.heapSize is not work

### Additional information

![image](https://github.com/bitnami/charts/assets/7300430/35c59540-ff09-4dc1-a24a-8187e8f70dc6)
![image](https://github.com/bitnami/charts/assets/7300430/409db338-49b1-4cc1-bd12-4a0219a03f74)
![image](https://github.com/bitnami/charts/assets/7300430/57ace66f-6c41-4e81-b5db-dcff65192e8f)

**Comment by jotamartos** [comment]
Hi @everythinggood,

I tried to reproduce this issue but I couldn't do so. First of all, I tested the Bitnami Elasticsearch docker images and made the following changes in the docker-compose.yml file 

```
diff --git a/bitnami/elasticsearch/docker-compose.yml b/bitnami/elasticsearch/docker-compose.yml
index 6d2f1a81053..36f297a46bb 100644
--- a/bitnami/elasticsearch/docker-compose.yml
+++ b/bitnami/elasticsearch/docker-compose.yml
@@ -2,12 +2,14 @@ version: '2'

 services:
   elasticsearch:
-    image: docker.io/bitnami/elasticsearch:8
+    image: docker.io/bitnami/elasticsearch:7
     ports:
       - '9200:9200'
       - '9300:9300'
     volumes:
       - 'elasticsearch_data:/bitnami/elasticsearch/data'
+    environment:
+      - ELASTICSEARCH_HEAP_SIZE=1g
 volumes:
   elasticsearch_data:
     driver: local
```

As you can see, I set the ELASTICSEARCH_HEAP_SIZE env var and used Elasticsearch 7.x. The process was configured correctly 

```
I have no name!@927467f2f04b:/$ COLUMNS=2000 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001         1  295  4.1 5698812 1349108 ?     Ssl  11:26   0:23 /opt/bitnami/java/bin/java ... -Xms1g -Xmx1g ...
```

Then, I also tested the latest version of the Chart 

```
$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
jota-elastic    jotamartos      1               2023-06-01 11:20:47.481453345 +0000 UTC deployed        elasticsearch-19.9.5    8.8.0
```

with the following changes in the values.yaml file 

```
diff --git a/bitnami/elasticsearch/values.yaml b/bitnami/elasticsearch/values.yaml
index 40d3bc7bf..c8b298477 100644
--- a/bitnami/elasticsearch/values.yaml
+++ b/bitnami/elasticsearch/values.yaml
@@ -825,7 +825,7 @@ data:
   ## Example:
   ##   heapSize: 128m
   ##
-  heapSize: 1024m
+  heapSize: 2048m
   ## Configure Pods Security Context
   ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
   ## @param data.podSecurityContext.enabled Enabled data pods' Security Context
```

The data pod was also configured properly 

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1001         415  184 30.5 4775948 2330672 ?     Sl   11:29   0:33 /opt/bitnami/java/bin/java ... -Xms2048m -Xmx2048m ...
```

Please use an updated version of the Bitnami image and chart to avoid issues with the configuration.

**Comment by everythinggood** [comment]
你发的信我已收到，我会尽快回复的！！！

**Comment by everythinggood** [comment]
你发的信我已收到，我会尽快回复的！！！

**Comment by everythinggood** [comment]
你发的信我已收到，我会尽快回复的！！！
