### ISSUE TITLE
[bitnami/postgresql] Upgrade postgresql version from 14 to 15

### ISSUE THREAD

**Issue by nhoangduy1912** [bitnami/charts#16876]
### Name and Version

bitnami/postgresql 14

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi everyone, 

I was using an application which utilizes keycloak 16 postgresql 14 but now I need to upgrade to keycloak 19 and postgresql 15.

So the idea is to dump the data to perform an upgrade. But when I run pg_dump in postgresql pod, the following message returned

pg_dump: error: local user with ID 1001 does not exist

What is the proper way to upgrade?

### What do you see instead?

Cannot dump database

Error: pg_dump: error: local user with ID 1001 does not exist

**Comment by nhoangduy1912** [comment]
Hi @corico44,

I exec into the pod and `ran pg_dumpall -U postgres -h localhost -p 5432 > dump.sql` but it gave the error I mentioned above.

I guess it's a permission problem so I put the following into value file

```
primary:
   containerSecurityContext:
      runAsUser: 0
```

Then I was able to dump the database. What is your recommendation to do the upgrade properly?

**Comment by corico44** [comment]
This issue mentions how to upgrade correctly from one version to another: https://github.com/bitnami/charts/issues/8025. I hope it can help.
