### ISSUE TITLE
[bitnami/apache] add path and port to liveness/readiness probes

### ISSUE THREAD

**Issue by whall89** [bitnami/charts#1687]
**Which chart**:

bitnami/apache

**Description**

this chart could be improved by having alternative paths and ports for the liveness and readiness probes.
currently the path just points to "/" on port "http" this could be pointed to alternate paths on apache like server-status which is a apache mod that reports on the actual status of apache

**Additional information you deem important (e.g. issue happens only occasionally):**

I have some simple addition that can be added to the current helm chart that would allow additions to be made to the path and port while keeping the defaults the same as they currently are, but I am unable to push to a new branch to create a pull request.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: v2.14.3+g0e7f3b6
Server: v2.14.3+g0e7f3b6
```

- Output of `kubectl version`:

```
Client Version: v1.16.2
Server Version: v1.14.8-eks-b7174d
```

**Comment by alemorcuq** [comment]
Hi, @whall89. 

You can submit a PR and we will gladly review it! To do so, just _fork_ the repo and then _push_ your new branch to your fork instead of `bitnami/apache`. You should be able to create the PR from there.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Closing as #1696 was merged.
