### ISSUE TITLE
[bitnami/postgresql] service nameOverride

### ISSUE THREAD

**Issue by deimosfr** [bitnami/charts#16885]
### Name and Version

bitnami/postgresql 12.5.1

### What is the problem this feature will solve?

In the previous version, we could override the naming. All the tooling and stuffs we made in my company are based on it. It breaks compatibility. It is still present for example in the Bitnami MongoDB chart, which is great.
I can make a PR if needed.

### What is the feature you are proposing to solve the problem?

Adding nameOverride like in the Mongodb chart would avoid breaking a change from the previous versions (8.9.8 the one we were using) to this one.

### What alternatives have you considered?

Manually override the chart on our side, but we're not aligned anymore mainstream with yours, which is not convenient for upgrades

**Comment by javsalgar** [comment]
Hi,

Could you confirm in which version the chart stopped having support for the variable? Our charts have fullnameOverride or nameOverride as standards.

**Comment by deimosfr** [comment]
Hi,

Sorry I don't know, I've made a +2y jump in the chart. Moving from 8.9.8 to 12.5.1, so I don't exactly know when it has changed. A big revamp has been made on this chart since then.

**Comment by javsalgar** [comment]
Hi,

We try to be as homogeneous as possible, but when one chart gets a new feature, it takes sometime before it gets moved to the rest of the catalog. If you want to speed up the process, would you like to submit a PR?

**Comment by deimosfr** [comment]
Sure! I'll be happy to make one. I'll give you the link here once done

**Comment by javsalgar** [comment]
Thank you so much!

**Comment by shashankram** [comment]
@deimosfr are you implementing this? I am looking for a service name override as well, such that I can consistently use the same name across Helm releases.

**Comment by deimosfr** [comment]
> @deimosfr are you implementing this? I am looking for a service name override as well, such that I can consistently use the same name across Helm releases.

I should start it next week with others I've planned because of inconsistencies between charts/removed items

**Comment by vietnguyenmipro** [comment]
hi, any update on this? I am looking for this as well
