### ISSUE TITLE
Helm Charts for Matamo - Help

### ISSUE THREAD

**Issue by veerappans** [bitnami/charts#1688]
Help Wanted:

Can you please add helm chart for Matamo using MySQL.

Thanks

**Comment by carrodher** [comment]
Hi,
Thanks for the suggestion. I am sorry, but in the short term, and due to other priorities, developing the Matomo chart is not among our tasks.
Feel free to send a PR, we will be happy to review it and incorporate to the registry.

**Comment by Jeremy-Boyle** [comment]
Looks like this has been stale for a long time I would like to support this.
