### ISSUE TITLE
Repair Kafka Pod after crash - struggling in CrashLoop

### ISSUE THREAD

**Issue by bzolivereckle** [bitnami/charts#1689]
Hi, 

i am using the Bitnami Helm Chart within our kubernetes environment (Version: kafka-7.0.2 with kafka:2.3.1-debian-9-r0) and from time to time a kafka broker is crashing. So far not a problem,
but when he comes back some files seem to be corrupt on the persistent volume. So the readiness probe fails and restart the pod. How to deal with that, trying to delete the pod manually and also recreate the PVC, but its pretty ugly and the broker will get a new broker id assigned.
Any best practice how to deal with that, cause my only working solution currently is delete the helm chart, delete all the persistent volume claims and install the chart again, with is not realy an option for productive environment. Attached some logs:

[logs-from-kafka-in-kafka-0 (7).txt](https://github.com/bitnami/charts/files/3915437/logs-from-kafka-in-kafka-0.7.txt)

Kind regards
Oliver

**Comment by javsalgar** [comment]
Hi,

Which is the error that makes you think that the volume is corrupt? Maybe, what you could do to debug and fix the issue is to temporarily disable the readiness and liveness probes. This way, you can enter the node, fix the problems and then reenable the readiness/liveness probes.

**Comment by bzolivereckle** [comment]
Hi,

i am not shure that the volume is corrupt, but maybe some files which has been accessed while crashing.
Deactivate the readiness probes will result in a redeployment?

**Comment by javsalgar** [comment]
Hi,

It is highly likely that it will re-deploy.

**Comment by bzolivereckle** [comment]
@javsalgar .. redeployment is the worst option i currently have .. cause  those crashes happens quite often and i always loose the broker id, so everything reset to zero ...

**Comment by juan131** [comment]
Hi @bzolivereckle 

Sorry for the late response, we lost track of this issue.

Could you check the logs of the worker that's crashing? We might get more information about the reason why it's crashing. Please install the chart setting the `image.debug` parameter to `true` so we get more verbosity in the logs (more info at https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L33).
