### ISSUE TITLE
[bitnami/grafana] Apply template to more variables

### ISSUE THREAD

**Issue by haje01** [bitnami/charts#16891]
### Name and Version

bitnami/grafana 8.4.3

### What is the problem this feature will solve?

In many cases, especially when a chart is utilized by other charts, the name of the referenced resource will include the installation name. 

I've found this to be particularly necessary for the information described in `datasources.secretDefinition` and `dashboardsConfigMaps` in Grafana charts. 

### What is the feature you are proposing to solve the problem?

Perhaps the most elegant way to handle this is to assume the value of the variable as a template and render it when installation happens.

So, I am requesting that the `common.tplvalues.render` function be applied to those fields.

### What alternatives have you considered?

It's also possible to change it manually on each install, but it's cumbersome.

**Comment by javsalgar** [comment]
Hi! Thank you so much for the PR! The team will take a look
