### ISSUE TITLE
[bitnami/rabbitmq] - using auth.existingPasswordSecret not working - invalid credentials

### ISSUE THREAD

**Issue by igitcode** [bitnami/charts#16909]
### Name and Version

bitnami/rabbitmq:11.15.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploying rabbitmq HELM chart version 11.15.3. Fresh install not an upgrade.
2. Override the `auth.username`, set to `admin`
3. Override the `auth.existingPasswordSecret` and `auth.existingErlangSecret`
4. validate the `rabbitmq` secret in my namespace contains the keys `rabbitmq-password` and `rabbitmq-erlang-cookie`
5. Validate the ENV vars RABBITMQ_PASSWORD and RABBITMQ_ERL_COOKIE's are set
<img width="618" alt="Screenshot 2023-05-25 at 12 22 29 PM" src="https://github.com/bitnami/charts/assets/18669319/3c45c505-5e64-4050-9c38-4597f9c88dc8">
<img width="610" alt="Screenshot 2023-05-25 at 12 22 42 PM" 
src="https://github.com/bitnami/charts/assets/18669319/1461f1c5-5ba6-46ea-ac0d-1a9377362cdc">

6. The default livenessProbe fails
curl -f --user admin:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/virtual-hosts
7. The default readinessProbe fails
curl -f --user admin:$RABBITMQ_PASSWORD 127.0.0.1:15672/api/health/checks/local-alarms

### Are you using any custom parameters or values?

See above

### What is the expected behavior?

That the default livenessProbe and readinessProbe work

### What do you see instead?

it's failing due to `invalid credentials`

2023-05-25 17:28:45.138350+00:00 [warning] <0.697.0> HTTP access denied: user 'admin' - invalid credentials

### Additional information

I initially tried this with the default user `user`. After changing to `admin` I notice the `admin` user is not a valid user when I run `rabbitmqctl list_users`, I still only see `user` listed:

```
rabbitmqctl list_users
Listing users ...
user	tags
user	[administrator]
```

But dumping the `rabbitmq-config` secret shows the `default_user` is `admin`
```
## Username and password
##
default_user = admin
```

_No response_

**Comment by Mauraza** [comment]
Hi @igitcode,

Could you share the values you are using to deploy rabbitmq?

**Comment by Mauraza** [comment]
Hi @igitcode,

Did you check that rabbitmq-erlang-cookie has a length of 32 and rabbitmq-password of 16?

**Comment by igitcode** [comment]
yes, the `rabbitmq-erlang-cookie` is 32 chars and the `rabbitmq-password` is 16 chars long.

**Comment by Mauraza** [comment]
Hi @igitcode,

I don't be able to reproduce:
```
$ k get secrets rabbitmq -o yaml 
apiVersion: v1
data:
  rabbitmq-erlang-cookie: U.....
  rabbitmq-password: Q2.....
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {}
    meta.helm.sh/release-name: rabbitmq
  creationTimestamp: "2023-05-31T10:02:28Z"
  labels:
    app.kubernetes.io/instance: rabbitmq
  name: rabbitmq
  namespace: default
  resourceVersion: "223955"
  uid: b34bb094-cd07-48d8-8627-5ad8d6584b13
type: Opaque
```

The chart is wanting something similar to:
https://github.com/bitnami/charts/blob/4bab16097b8c39d27edef819af56c8227a4d1c57/bitnami/rabbitmq/templates/secrets.yaml#L7-L26
