### ISSUE TITLE
Config to set Eviction Policy for redis in standalone mode

### ISSUE THREAD

**Issue by bhanuprakash-1** [bitnami/charts#16937]
### Name and Version

bitnami/redis 17.9.x

### What is the problem this feature will solve?

Redis has eviction policy configuration which determines how to clear memory when a database reaches its memory limit. 

I don't find a configuration where I can set one of the eviction policies as mentioned here in official redis docs: https://docs.redis.com/latest/rs/databases/memory-performance/eviction-policy/.

Im using redis helm chart to create redis statelful set pod in standalone architecure in k8s.

### What is the feature you are proposing to solve the problem?

NA. I don't have a solution in mind. New to Redis!

**Comment by bhanuprakash-1** [comment]
Got it. 

Just had to set master.extraFlags:
      - "--maxmemory-policy allkeys-lru"  in values.yaml.

**Comment by nguyenquocthao** [comment]
@bhanuprakash-1 can you give the full values.yaml file?

**Comment by bhanuprakash-1** [comment]
Sure. Please find it below.

Ignore some other parameters.

`
# Default values for linkerd-charts

# Documentation for configuration here: https://github.com/bitnami/charts/tree/main/bitnami/redis#parameters

redis:

  enabled: true

  architecture: standalone
  auth:
    enabled: true
    existingSecret: rediscachepassword
    existingSecretPasswordKey: secret-value

  commonConfiguration: |-
    # Disable AOF persistence
    appendonly no
    # Disable RDB persistence
    save ""
  
  commonAnnotations:
      # This is applied to all objects. This annotations indicates reloader to rollout the object when the configmap or secret changes.
      # We need to apply this annotation to only redis-master pod but there is no way to do that.
      reloader.stakater.com/auto: "true" 

  master:
    count: 1
    
    kind: StatefulSet
    podAnnotations:
      linkerd.io/inject: enabled
    
    persistence:
      enabled: false
    
    extraFlags:
      - "--maxmemory-policy allkeys-lru"  # Eviction policy for keys when memory limit is reached

    priorityClassName: system-cluster-critical # Gives priority in scheduling and also prevents eviction

  sentinel:
    enabled: false


`
