### ISSUE TITLE
[bitnami/rabbitmq] misleading documentation on auth.enableLoopbackUser parameter

### ISSUE THREAD

**Issue by blowfishpro** [bitnami/charts#16934]
### Name and Version

bitnami/rabbitmq 11.15.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Look at [the description](https://github.com/bitnami/charts/blob/e3e59cc9908f8a9559036a4206c908014e0d4dfa/bitnami/rabbitmq/values.yaml#L145) for the `auth.enableLoopbackUser` parameter on the chart
2. Compare to RabbitMQ's [official documentation](https://www.rabbitmq.com/access-control.html#loopback-users) on what setting a user to loopback true/false means.

### What do you see instead?

The chart documentation is not consistent with the RabbitMQ's documentation.  Setting `loopback_users = none` or `loopback_users.guest = false` allows the guest user to connect from __any interface, including the loopback interface__.  Rabbitmq's default is `loopback_users.guest = true` which allows the guest user to connect from __only__ the loopback interface.  The chart defaults to `loopback_users.guest = false` which allows the guest user to connect from any interface.  The chart documentation seems to imply that changing that to `true` would be a security risk, whereas the default of`false` is actually less secure.

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for pointing this out.
  I have changed the description in the values and README.
