### ISSUE TITLE
When a sudden error occurs in GKE and the StatefulSet (STS) dies (e.g., during node updates or when the underlying engine is upgraded),

### ISSUE THREAD

**Issue by sjy-dv** [bitnami/charts#16941]
### Name and Version

bitnami/mariadb-galera:10.11.3-debian-11-r6

### What architecture are you using?

None

### What steps will reproduce the bug?

An unexpected termination can lead to the occurrence of such errors.

```
It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates. To force cluster bootstrap with this node, edit the grastate.dat file manually and set safe_to_bootstrap to 1
```
If the container keeps dying before you can modify the value of grastate.dat

Are there any potential solutions? If I set `galera.bootstrap.forceBootstrap` to true, can I avoid this error?

### What do you see instead?

And a corrupted PVC should not be restored, and all data should be completely wiped out.

**Comment by Mauraza** [comment]
We have this [issue](https://github.com/bitnami/charts/issues/2260), did you check it?
