### ISSUE TITLE
Airflow DAGs broken, when they really aren't

### ISSUE THREAD

**Issue by cccs-cat001** [bitnami/charts#1695]
**Which chart**:

Airflow latest version

**Description**

The airflow scheduler validates a DAG. The workers I have for airflow are set up differently than the scheduler, and thus have different libraries than the scheduler has. So when I go to run a DAG, airflow says it's broken because the scheduler sees the DAG has a library inside it that the scheduler doesn't have, however the worker has all the libraries the DAG needs so I know it will run just fine.

**Steps to reproduce the issue:**

1. Launch an airflow instance.
2. exec into the worker and run 
``` . /opt/bitnami/airflow/venv/bin/activate && pip3 install papermill jupyter ```
3. also copy over a test jupyter notebook to the worker. 
4. Create a dag that will run the test notebook with papermill: 
```
from airflow.operators.python_operator import PythonOperator
from airflow.operators.dummy_operator import DummyOperator
from airflow import DAG
from datetime import datetime, timedelta
import papermill

def run_papermill(inputnotebook, parameters):
    outputnotebook="/tmp/outputnotebook.ipynb"
    papermill.execute_notebook(inputnotebook,outputnotebook, parameters)

dag = DAG(dag_id="papermill_notebook", description="run a jupyter notebook with papermill", schedule_interval=timedelta(hours=2, minutes=30),
                start_date=datetime(2019, 11, 1))

po = PythonOperator(task_id="run_papermill", python_callable=run_papermill, op_kwargs={'inputnotebook':'< PATH TO COPIED NOTEBOOK >', 'parameters': {}}, dag=dag)
do = DummyOperator(task_id="start")
do >> po
```
5. Submit that dag to airflow however you choose (I have a git repo for dags)
6. Turn on the DAG.

**Describe the results you received:**

Airflow warns that the DAG you just submitted is broken. However, Follow these steps:
1. exec into the scheduler pod. run 
``` . /opt/bitnami/airflow/venv/bin/activate && pip3 install papermill ```
2. Watch as airflow doesn't complain about the broken dag anymore. 

**Describe the results you expected:**

I would expect the DAG to run, because the worker has all the libraries that the DAG needs, the scheduler does none of the executing of the DAGs, so why should it have the DAGs dependencies? 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by cccs-cat001** [comment]
Potentially completely fixed. We moved the imports that the scheduler was complaining about to inside the python functions that were using it, and now the scheduler doesn't care. I say potentially fixed because there may be some use cases where the imports cannot be put in a function, I'm just not sure what those use cases are.

**Comment by alemorcuq** [comment]
Thank you very much for reporting this, @cccs-cat001. Do you think this is an issue with our chart? Or is it Airflow's behavior?

**Comment by cccs-cat001** [comment]
I had initially thought it was with the chart, but after further investigation it seemed to be airflow itself.
