### ISSUE TITLE
[bitnami/kube-prometheus] Allow setting scrapeTimeout for prometheus 

### ISSUE THREAD

**Issue by Sakib37** [bitnami/charts#16964]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

This will allow to set a custom `scrapeTimeout` for prometheus. 

It seems like the prometheus CRD already supports `scrapeTimeout` parameter for prometheus. However, in the helm chart the prometheus.yaml file does not use the `scrapeTimeout` field. So at this moment there is no way to set the global `scrapeTimeout`  for prometheus and default value of `10s` is being used 
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

This will allow to set custom scrape timeout for prometheus via this helm chart

### What is the feature you are proposing to solve the problem?

As the CRD already have the field `scrapeTimeout`, adding this field to the prometheus object in `prometheus.yaml` file (similar to `scrapeInterval`) and having a new value `prometheus.scrapeTimeout` (similar to `prometheus.scrapeInterval`)  in the `values.yaml` file will enable this feature for this helm chart

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the team. If you want to speed up the process, would you like to submit a PR?

**Comment by Sakib37** [comment]
Thanks @javsalgar . 
For now I updated the scrapetimeout for specific job and it solved my problem. So I will wait for the fix in a future version.
