### ISSUE TITLE
[bitnami/mysql] Service cannot start after physical recovery

### ISSUE THREAD

**Issue by qybf** [bitnami/charts#16972]
### Name and Version

mysql-chart-9.9.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have two mysqls in different namespaces. I copy the/bitnami/mysql/data/directory of one mysql to the corresponding directory of the other mysql, and then start the container. The service has been unable to start, and the log is as follows:

![图片](https://github.com/bitnami/charts/assets/47775316/111b2139-b545-4005-8604-a9b94539d88e)

### Are you using any custom parameters or values?

`lower_case_table_names=1`

**Comment by qybf** [comment]
My two database versions are identical. The old database does not define lower_ Case_ Table_ Names=1

This parameter, with a new definition, now physically backs up the old database and then physically restores it to the new database. Database cannot start

**Comment by CeliaGMqrz** [comment]
Hi @qybf, 

Sorry for the delay. Thanks for your comments. 

Sorry, I can't reproduce the issue with the information provided. The screenshot does not match the described error. I will need more information. Please show the full log output with the debug enabled: `--set image.debug=true`. And show the steps you have followed in more detail. 

Make sure you are using the correct PV, you may have problems if you are using the same PV. See also the documentation [here](https://github.com/bitnami/containers/blob/main/bitnami/mysql/README.md#step-2-stop-and-backup-the-currently-running-container).
