### ISSUE TITLE
[bitnami/mongodb] Purpose property auth.existingSecret.mongodb-passwords and combine with other property in auth.*

### ISSUE THREAD

**Issue by chary1112004** [bitnami/charts#16975]
### Name and Version

bitnami/mongodb 12.1.24

### What is the problem this feature will solve?

Hi,

We are changing deployment from gitlab pipeline to argocd then instead of set parameters for passwords then it could be used in existing secret.

Follow https://artifacthub.io/packages/helm/bitnami/mongodb/12.1.24?modal=values

- **auth.rootPassword** replaced by **auth.existingSecret.mongodb-root-password**
- **auth.replicaSetKey** replaced by **auth.existingSecret.mongodb-replica-set-key**

As in the document, @param auth.existingSecret Existing secret with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, ` mongodb-replica-set-key`)

However this property **auth.existingSecret.mongodb-passwords** is not clear about its purpose, it replaces for **auth.passwords**? If yes, how it works with other properties auth.usernames, auth.databases. What format should be (Is that string or list)? 

### What is the feature you are proposing to solve the problem?

Any information would be very much appreciated.

Thank you!

**Comment by CeliaGMqrz** [comment]
Hi @chary1112004,

First, sorry for the delay. Thanks for your feature request. 

>However this property auth.existingSecret.mongodb-passwords is not clear about its purpose, it replaces for auth.passwords? If yes, how it works with other properties auth.usernames, auth.databases. What format should be (Is that string or list)?

Right, the [auth.existingSecret param](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml#L184) is used to set the mentioned keys: (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, `mongodb-replica-set-key`. This means, if you provide the secret, setting these parameters in the values.yaml is not required. If the secret is set, the values are replaced. See the [template](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/_helpers.tpl#L191). 

To use the existing secret, you need to create the secret with the mentioned keys if you don't have them yet. 

* You can create it from the command line like this, eg:

````
kubectl create secret generic name-secret-mongo --from-literal=mongodb-root-password=testing --from-literal=mongodb-replica-set-key=secret -n <yourNamespace>

helm install mongo oci://registry-1.docker.io/bitnamicharts/mongodb --set existingSecret=name-secret-mongo -n <yourNamespace>
````

Connection to the database with credentials:
```.yaml
$ mongosh --host  mongo-mongodb.mongodb.svc.cluster.local --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD
Current Mongosh Log ID:	648822c8dfe1c996a1e3a11f
Connecting to:		mongodb://mongo-mongodb.mongodb.svc.cluster.local:27017/?directConnection=true&authSource=admin&appName=mongosh+1.9.0
Using MongoDB:		6.0.6
Using Mongosh:		1.9.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

test>
```
* You can also create the secret from a yaml file, but you must make sure that all the keys are there. [See](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/)

**Comment by MaciekLeks** [comment]
Could anyone tell me what is the format of `mongodb-passwords` key in a k8s secret? As suffix suggests it works not only with one password. For one user the format is just a literal, but what about 2,3,....users?

**Comment by smsilva** [comment]
> Could anyone tell me what is the format of `mongodb-passwords` key in a k8s secret? As suffix suggests it works not only with one password. For one user the format is just a literal, but what about 2,3,....users?

You can generate a Secret like that:

```bash
kubectl create namespace mongodb

export MONGODB_ROOT_PASSWORD=$(openssl rand -base64 32)

kubectl apply \
  --namespace mongodb \
  --filename - <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
stringData:
  mongodb-root-password: ${MONGODB_ROOT_PASSWORD?}
  mongodb-replica-set-key: $(openssl rand -base64 32)
  mongodb-metrics-password: $(openssl rand -base64 32)
  mongodb-passwords: "jubarte,cisne"
EOF
```

Then you can use the Helm Chart with the user list and the Databases for each user:

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami

helm repo update bitnami

helm search repo bitnami/mongodb

helm install mongodb bitnami/mongodb \
  --create-namespace \
  --namespace mongodb \
  --wait \
  --values - <<EOF
architecture: replicaset
auth:
  enabled: true
  existingSecret: "mongodb"
  usernames:
    - silvios
    - paulos
  databases:
    - humpback
    - humpback
EOF
```

Then, you should be able to logon as the root and with the users:

```bash
export MONGODB_DATABASE_NAME="admin"
export MONGODB_ROOT_USER="root"
export MONGODB_ROOT_PASSWORD=$(kubectl get secret \
  --namespace mongodb mongodb \
  --output jsonpath="{.data.mongodb-root-password}" \
  | base64 -d)

kubectl run mongodb-client \
  --namespace mongodb \
  --rm \
  --tty \
  --stdin \
  --restart='Never' \
  --env="MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME?}" \
  --env="MONGODB_ROOT_USER=${MONGODB_ROOT_USER?}" \
  --env="MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD?}" \
  --image docker.io/bitnami/mongodb:7.0.2-debian-11-r7 \
  --command -- bash

mongosh ${MONGODB_DATABASE_NAME?} \
  --host "mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017" \
  --authenticationDatabase admin \
  --username ${MONGODB_ROOT_USER?} \
  --password ${MONGODB_ROOT_PASSWORD?}

mongosh humpback \
  --host "mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017" \
  --username silvios \
  --password jubarte
```
