### ISSUE TITLE
Can we add support for Apollo? It is still widely used

### ISSUE THREAD

**Issue by long1318737396** [bitnami/charts#16971]
### Name and Version

apollo

### What is the problem this feature will solve?

Can we add support for Apollo? It is still widely used
https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_24-kubernetes%e9%83%a8%e7%bd%b2

### What is the feature you are proposing to solve the problem?

https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_24-kubernetes%e9%83%a8%e7%bd%b2

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by long1318737396** [comment]
thank you very much!good luck

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
