### ISSUE TITLE
[bitnami/apisix] wrong environment variable reference syntax in config

### ISSUE THREAD

**Issue by lingsamuel** [bitnami/charts#16993]
### Name and Version

bitnami/apisix

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/3f5cb79454418d4e353ccc05ee3d99ce64105bda/bitnami/apisix/values.yaml#L966-L967

The syntax is not `{{ENV}}` but `${{ENV}}`, ref: https://github.com/apache/apisix/blob/6ba4f73bbbcb55d63c1a2e5ee98d782e6644f92e/conf/config.yaml#L28

This probably caused the issue commented here (I have not verified this though):
https://github.com/bitnami/charts/blob/3f5cb79454418d4e353ccc05ee3d99ce64105bda/bitnami/apisix/values.yaml#L2817-L2818

### What do you see instead?

Wrong environment variable reference syntax used.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
