### ISSUE TITLE
argocd-rbac-cm

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/charts#16998]
### Name and Version

bitnami/argocd 2.7.3

### What architecture are you using?

None

### What steps will reproduce the bug?

I have already installed Argocd and working fine. But I have not seen `argocd-rbac-cm` to config role ArgoCDAdmin with SSO keycloak although `rbac.create = true` with this [link](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/). Help me, please

### What do you see instead?

I wanna see argocb-rbac-cm

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by thanhtai9606** [comment]
> It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.
> 
> For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.
> 
> That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

Already fixed, Just create an configMap link this and it working now. Thank your help
`apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: |
    g, system:authenticated
  policy.csv: |
    g, ArgoCDAdmins, role:admin`

**Comment by Moulick** [comment]
For future reference, `argocd-rbac-cm` is part of the ArgoCD installation and not Keycloak. `argocd-rbac-cm` will not come from KeyCloak Helm Chart.

**Comment by thanhtai9606** [comment]
> For future reference, `argocd-rbac-cm` is part of the ArgoCD installation and not Keycloak. `argocd-rbac-cm` will not come from KeyCloak Helm Chart.

Oh, I know, so that the reason, I have no see config map inside argocd heml chart. But I create an other configmap argocd-rbac-cm, it works now

**Comment by Moulick** [comment]
@thanhtai9606 dunno what version of the chart you are using but https://github.com/argoproj/argo-helm/blob/2538371fecba8e3bc7a161f6484e3d752f71d1e1/charts/argo-cd/values.yaml#L263 should create the configmap
