### ISSUE TITLE
[bitnami/rabbitmq] liveness probe not working when using path_prefix

### ISSUE THREAD

**Issue by mvencl** [bitnami/charts#16995]
### Name and Version

bitnami/rabbitmq:3.11.17

### What architecture are you using?

None

### What steps will reproduce the bug?

if an instance with a different path than the default is deployed, the liveness probe refers to the default, so it does not work.
```
extraConfiguration: |-  
    management.path_prefix = /rabbitmq/
```

### What do you see instead?
```
$RABBITMQ_PASSWORD 127.0.0.1:{{ .Values.containerPorts.manager }}{{ .... path_prefix ... }}api/health/checks/virtual-hosts
```

**Comment by corico44** [comment]
Hello @mvencl,

Could you tell me what commands are you executing to recreate this error, please?

**Comment by mvencl** [comment]
> Hello @mvencl,
> 
> Could you tell me what commands are you executing to recreate this error, please?

Hello,

I just start the application but on a different path. I use the path_prefix variable for this.
Liveness probe checks the fixed management address. If path_prefix is used, the address is different and the liveness probe fails.

**Comment by corico44** [comment]
@mvencl Could you indicate if it has finally worked for you and how you have done it for future users, please?
