### ISSUE TITLE
Kafka Kraft mode 

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/charts#17008]
### Name and Version

bitnami/kafka 22.1.3

### What is the problem this feature will solve?

Allow the option to spin up a schema registry inside the same cluster. This would make the service more convenient

### What is the feature you are proposing to solve the problem?

Provide the option to spin up a bitnami schema registry container inside the cluster

### What alternatives have you considered?

Simply running the schema registry aside and connect to it. It is not the end of the world, but I think it would be an easy, but very useful addition. Thanks guys, you are awesome

**Comment by carrodher** [comment]
Thanks for this suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ETisREAL** [comment]
Sure, good idea. Will get back to you guys
