### ISSUE TITLE
[bitnami/keycloak] Support Multiple Ingress

### ISSUE THREAD

**Issue by jseiser** [bitnami/charts#17007]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Expose Keycloak API publicly, while keeping the UI private.

### What is the feature you are proposing to solve the problem?

Add the ability to configure two ingress's

### What alternatives have you considered?

Create a sep. ingress out of band.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by djjudas21** [comment]
I have the same request for the `bitnami/wordpress` chart, as I want to put the `/wp-admin` endpoint behind auth.

Unfortunately the [`bitnami/common`](https://github.com/bitnami/charts/tree/main/bitnami/common) chart doesn't support multiple ingresses. [`bjw-s/common`](https://github.com/bjw-s/helm-charts/tree/main/charts/library/common) does provide a mechanism for creating multiple named ingresses, but merging that into `bitnami/common` would also mean updating every chart that depends on it, and that's a big job :sob:

**Comment by javsalgar** [comment]
Hi!

If this is a non-breaking change we could merge it and have our automated system release new revisions of the chart.

**Comment by djjudas21** [comment]
It would be breaking, because it would change the basic Ingress syntax from:

```yaml
ingress:
  enabled: true
  host: example.com
  ...
```

to something like:

```yaml
ingress:
  main:
    enabled: true
    host: example.com
    ...
  secondary:
    enabled: true
    host: anotherexample.com
    ...
```

i.e. every existing Ingress declaration in every chart's values would need to be indented under a name such as `main`.

It's not impossible, but it is a big task and it seems like someone should approve it before work starts on changing everything.

**Comment by javsalgar** [comment]
I see. Indeed this would be a bit painful. Maybe, for certain charts, there could be a section called `ingress.secondary` that has the sections for a second ingress instance. I don't know how common this would be but for the affected apps (keycloak or wordpress) we could have it and I don't think it would be breaking.

**Comment by djjudas21** [comment]
If we're adding an optional secondary ingress, maybe it should simply duplicate the existing `ingress` block but rename it `secondaryIngress` and have them at the same level in the yaml, not connected to each other.

**Comment by javsalgar** [comment]
That could work too. Would you like to submit a PR?

**Comment by djjudas21** [comment]
I'll have a look. The `bitnami/common` chart seems pretty complex though so I'll need to get my head around the way it works :slightly_smiling_face:

**Comment by shaikzoheb-oi** [comment]
@javsalgar @carrodher In keycloak, the fix is available in specific version?

To have two ingresses, one exposed publicly and second one is for UI which is exposed internally.

Can we achieve this use case using adminIngress?
