### ISSUE TITLE
facing error in running our custom entrypoint.sh

### ISSUE THREAD

**Issue by rajivmishra-123** [bitnami/charts#17002]
### Name and Version

bitnami/redis , latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install redis redis

I want to install crontab inside my Redis container. for that, I have made a custom image using the bitnami Redis image. also, I have made changes in entrypoint.sh script to run my cron service .but now when I am using it my cron service is not running inside my container. my entrypoint changes are present inside the container also.   

### What is the expected behavior?

by using the new image, cron service should be running inside the container.

### What do you see instead?

when I install the helm chart, cron service is not up inside the container. 

### Additional information

one reason I found after debugging is that when helm chart is installed by default, cron service is not up. but when I go inside the container and manually run the entrypoint .sh present there (/opt/bitnami/scripts/redis/entrypoint.sh ), the cron service is up as commands to run the service were there. so the conclusion comes out that my entrypoint.sh is not picked when the container starts. 
so what can be the reason?

also, i tried to run my entrypoint.sh through cmd and args present in values. yaml . when I run through these, my scripts come up, but now my replica pod Redis is also become, master. 
```yaml
 command: 
   - /opt/bitnami/scripts/redis/entrypoint.sh
  args: 
    - /opt/bitnami/scripts/redis/run.sh
```
can you help me here? also, can you tell me the order in which scripts run from start to end for spawning master and replica Redis?

**Comment by rajivmishra-123** [comment]
@carrodher can you pls help here

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario/customizations.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
