### ISSUE TITLE
[bitnami/keycloak] Allow Labels on Ingress

### ISSUE THREAD

**Issue by jseiser** [bitnami/charts#17012]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Our external dns is configured to create, or not create dns entries based on the labels on an ingress.

### What is the feature you are proposing to solve the problem?

allow labels on ingress

### What alternatives have you considered?

N/A

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jseiser** [comment]
Working on this one.
