### ISSUE TITLE
feature request: document existingSecret

### ISSUE THREAD

**Issue by donifer** [bitnami/charts#1701]
This is most a documentation request.

**Which chart**:
- bitnami/mysql
- stable/mongodb (I know it's not under this repo)

**Description**
I see in `values.yaml` that you can pass an `existingSecret`, which I believe lets you give it a secret for root password, user password, etc. But I have no idea how it is supposed to be used.

Would love some more documentation or just some examples under `values.yaml`.

**Comment by juan131** [comment]
Hi @donifer 

I can see that the `existingSecret` is documented in the MongoDB's README.md (under the `#Parameters` table) and it's missing in the MySQL one.

Do you mean to create a specific section like we have for "Initialize a fresh instance" for instance?

**Comment by donifer** [comment]
Thanks for you quick reply @juan131! 

It would be ideal for me if there was a specific section such as `### Initialize a fresh instance` but I understand if this is too much.

In the MongoDB is documented as `Existing secret with MongoDB credentials` but I don’t know what it expects. I gave it a name to a secret but I am not sure what that secret should look like. What keys should I provide in those secrete. 

For example: I created a secret `mysql-credentials` then I looked at the chart and tried to figure out what keys to use, added a `mysql-root-password`. Then I set `existingSecret: mysql-credentials`. But it errores out with something like “couldn’t find a `mysql` secret”.

I am probably doing it all wrong, I just have no idea what’s the right way to do it but can’t find any documentation for it.

**Comment by juan131** [comment]
Hi @donifer 

We just updated the MySQL **README**.md and now it includes the information below about this parameter:

| Parameter                                   | Description                                                                                                                                               | Default                                                           |
| ------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| `existingSecret`  | Use existing secret for password details (`root.password`, `db.password`, `replication.password` will be ignored and picked up from this secret). The secret has to contain the keys `mysql-root-password`, `mysql-replication-password` and `mysql-password`. | `nil` |

Do you think that information is enough? Should we sth similar on MongoDB?

**Comment by donifer** [comment]
This is definitely better thank you so much! I tried that last night but I just defined a `mysql-root-password` maybe it errored out since I missed the other ones?

I'll try again and report back! I do think this should be added to mongo, and maybe other charts? Since I imagine most of them require different keys.

**Comment by alemorcuq** [comment]
Hi, @donifer.

The keys that need to be specified depend on your configuration. WIth the default `values.yaml`, the keys `mysql-root-password` and `mysql-replication-password` are needed.

I agree that we should document this in our charts, so I've created an internal task to tackle this. Meanwhile, you can use `helm install --dry-run --debug` to see what the YAMLs look like without actually installing the chart. This way you can see what the generated secret looks like.

Regards,
Alejandro

**Comment by donifer** [comment]
Hi Alejandro,

I might be doing something wrong but using the `stable/mongodb` chart with a `--dry-run` then setting the same secret keys results in a `--dry-run` with no secrets set.

As for `bitnami/mysql` seems like it's not ignoring my secret. Again, I'm pretty confident this is a user error but i'll keep trying and will report back.

**Comment by sameersbn** [comment]
you can try the following:

```bash
$ helm install --name mongodb stable/mongodb --dry-run --debug
```

In the output look for the `kind: Secret`, in my case it is:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app: mongodb
    chart: mongodb-7.5.0
    release: "mongodb"
    heritage: "Tiller"
type: Opaque
data:
  mongodb-root-password: "STA5eHhTb1pwMQ=="
```

The `data` section shows you the fields required in the default chart configuration. Kubernetes secrets are base64 encoded. To encode a string in base64 format you can use the `base64` command line tool like so `echo -n"my-secret" | base64`. The tool can also be used to decode a base64 encoded string like so `echo "STA5eHhTb1pwMQ==" | base64 --decode`.

Please note depending on the chart configuration you may need to specify additional fields. Take a look at the secrets manifest to know about all of them

**Comment by droopy4096** [comment]
as of today `README.md` for mongodb does *not* include details of `auth.existingSecret` at all.
