### ISSUE TITLE
[bitnami/harbor] harbor-notary-server-envvars secret obtains the password of the database from the values.yaml file in plain text

### ISSUE THREAD

**Issue by amgonzalezf** [bitnami/charts#17023]
### Name and Version

bitnami/harbor v16.6.6

### What is the problem this feature will solve?

In order to set a secure password for the postgresql database instead of using the default password "not-secure-database-password", I'm creating a secret called "credentials" that contains the keys 'POSTGRESQL_PASSWORD' and 'postgres-password', both of them containing the same value (the non-default password that I want to set for the database). The reason why the password is defined twice is because the 'harbor-core' pod looks for the password of the database in the key 'POSTGRESQL_PASSWORD', while the pod 'harbor-postgresql' looks for that password in the key 'postgres-password'. Then I'm setting the fields '.Values.core.existingEnvVarsSecret: credentials' and '.Values.postgresql.auth.existingSecret: credentials' to force the 'harbor-core' pod and the 'harbor-postgresql' pod to look for the database password in the 'credentials' secret respectively.

The 'harbor-notary-signer' and the 'harbor-notary-server' pods also need to get the password of the database through the secret 'harbor-notary-server-envvars'. In order for this secret to use the non-default password of the database, it's necessary to put the password in plain text in the field '.Values.postgresql.auth.postgresPassword'. This is a security concern, specially because I want to deploy Harbor with ArgoCD following GitOps principles, which means that I want to upload the values.yaml file to a git repository.

### What is the feature you are proposing to solve the problem?

1. It would be nice if it was necessary to state the non-default password of the database in a single key of a preexisting secret to avoid duplicities and to be able to change the password of the database in a single central place instead of needing to go to edit multiple keys. For example, that key could be 'POSTGRESQL_PASSWORD'. In order for this to work, the pod 'harbor-postgresql' shoudl look for its password in the key  'POSTGRESQL_PASSWORD' as well instead of looking for it in the key 'postgres-password'. 
2. It would be also cool if the 'harbor-notary-server-envvars' secret obtains the password of the database from this same key of the preexisting secret. This would also avoid the need of stating the password in plain text in the values.yaml file.

**Comment by jotamartos** [comment]
Hi @amgonzalezf,

Thank you for taking the time to provide this feedback. I just reviewed all the information you provided (sorry for the delay) and confirmed what you are saying. Would you like to contribute by creating a PR to solve the issue? You can apply the same configuration that we use in 'harbor-core' to the 'harbor-notary-signer' and 'harbor-notary-server' pods. The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
