### ISSUE TITLE
[bitnami/harbor-jobservice] config obtains the password of redis from field in plain text in the values.yaml file

### ISSUE THREAD

**Issue by amgonzalezf** [bitnami/charts#17024]
### Name and Version

bitnami/harbor v16.6.6

### What is the problem this feature will solve?

I order to set a non-default password for the 'harbor-redis-master' pod, I'm creating a secret called "credentials" that contains the key 'redis-password', whose value is the password that I want to use. Then I set the fields '.Values.auth.enabled: true' and '.Values.auth.existingSecret: credentials' to force the 'harbor-redis-master' pod to use that password.

The problem is that a secret called 'harbor-jobservice-config' is used by the 'harbor-jobservice' pod to obtain the password of redis. The only way that this password can be provided to the secret 'harbor-jobservice-config' is by pasting it in plain text in the field '.Values.redis.auth.password'. This is a security concern, specially because I want to deploy Harbor with ArgoCD following GitOps principles, which means that I want to upload the values.yaml file to a git repository.

### What is the feature you are proposing to solve the problem?

It would be better if the secret 'harbor-jobservice-config' obtains the password of redis from the key 'redis-password' of the preexisting secret. This way the password doesn't need to be provided in plain text in the values.yaml file and the password of redis can be changed from a single location instead of needing to update two objects every time we want to rotate it.

**Comment by corico44** [comment]
Hello @amgonzalezf,

Thank you so much for reporting this issue. Would you be open to contributing this change via a PR? We'd be glad to review and help with the release.
