### ISSUE TITLE
[bitnami/redis-cluster] `User requested shutdown` master nodes restarts

### ISSUE THREAD

**Issue by staboss** [bitnami/charts#17031]
### Name and Version

bitnami/redis-cluster 8.6.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Standard bitnami configuration by helm charts, without any specification (amd/arm does not matter)

### What do you see instead?

Random restarts of master nodes occur with the following log output:

```bash
1:M 02 Jun 2023 18:22:41.595 # User requested shutdown...
1:M 02 Jun 2023 18:22:41.595 * 1 of 1 replicas are in sync when shutting down.
1:M 02 Jun 2023 18:22:41.595 * Calling fsync() on the AOF file.
1:M 02 Jun 2023 18:22:41.595 * Removing the pid file.
1:M 02 Jun 2023 18:22:41.595 # Redis is now ready to exit, bye bye...
```

### Additional information

We specify only the default configuration and it does not depend on the environment, each redis node has its own node in the cluster, but the pods are still restarted

**Comment by javsalgar** [comment]
Hi,

Could you add more details of the Kubernetes cluster you are using and the time it takes to restart? We would like to reproduce it in our side.

**Comment by carrodher** [comment]
Sorry, I removed the recently created issue as a duplicate of this one (which was closed by mistake) without noticing there was some information in the new one not present here.

Although unfortunately there is no log of the removed issue, I read it and it seems a very specific use case difficult to reproduce on our side and very tied to your scenario, I'm not sure if it could be related to the Bitnami packaging itself (container and chart) or just how it is configured or how the application itself behaves.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
