### ISSUE TITLE
bitnami/redis chart in sentinel mode enters split-brain for podManagementPolicy=Parallel or after a host reboot

### ISSUE THREAD

**Issue by shadjiiski** [bitnami/charts#17047]
### Name and Version

bitnami/redis 17.11.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**Scenario 1:**
1. Prepare a 3 node k8s cluster (could work with a single node as well)
2. Install redis in sentinel-model with persistence disabled and podManagementPolicy set to **Parallel**
```
helm install --set sentinel.enabled=true,replica.persistence.enabled=false,replica.podManagementPolicy=Parallel test-redis oci://registry-1.docker.io/bitnamicharts/redis
```
3. Verify that each sentinel follows its own master:
```console
$ export REDIS_PASSWORD=$(kubectl get secret --namespace default test-redis -o jsonpath="{.data.redis-password}" | base64 -d)
$ kubectl exec -it test-redis-node-0 -c sentinel -- redis-cli -h localhost -p 26379 -a "$REDIS_PASSWORD" sentinel get-master-addr-by-name mymaster 
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "test-redis-node-0.test-redis-headless.default.svc.cluster.local"
2) "6379"
$ kubectl exec -it test-redis-node-1 -c sentinel -- redis-cli -h localhost -p 26379 -a "$REDIS_PASSWORD" sentinel get-master-addr-by-name mymaster 
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "test-redis-node-0.test-redis-headless.default.svc.cluster.local"
2) "6379"
$ kubectl exec -it test-redis-node-2 -c sentinel -- redis-cli -h localhost -p 26379 -a "$REDIS_PASSWORD" sentinel get-master-addr-by-name mymaster 
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "test-redis-node-0.test-redis-headless.default.svc.cluster.local"
2) "6379"
```
4. Verify that redis nodes themselves agree on a master:
```console
$ kubectl exec -it test-redis-node-0 -c redis -- redis-cli -h localhost -p 6379 -a "$REDIS_PASSWORD" role
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "master"
2) (integer) 50131
3) 1) 1) "test-redis-node-1.test-redis-headless.default.svc.cluster.local"
      2) "6379"
      3) "50131"
   2) 1) "test-redis-node-2.test-redis-headless.default.svc.cluster.local"
      2) "6379"
      3) "50131"
$ kubectl exec -it test-redis-node-1 -c redis -- redis-cli -h localhost -p 6379 -a "$REDIS_PASSWORD" role
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "slave"
2) "test-redis-node-0.test-redis-headless.default.svc.cluster.local"
3) (integer) 6379
4) "connected"
5) (integer) 52067
$ kubectl exec -it test-redis-node-2 -c redis -- redis-cli -h localhost -p 6379 -a "$REDIS_PASSWORD" role
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
1) "slave"
2) "test-redis-node-0.test-redis-headless.default.svc.cluster.local"
3) (integer) 6379
4) "connected"
5) (integer) 53775
```

**Scenario 2:**
1. Prepare a 3 node cluster (could work with a single node as well)
2. Install redis in sentinel-model with persistence disabled and podManagementPolicy set to **OrderedReady**
3. After spinning all pods, validate that both redis and sentinel nodes agree on a common master
4. Power cycle each k8s node. Eventually, pods will be restored but they will start more or less simultaneously (regardless of the OrderedReady policy).
5. Do same verification as in scenario 1. Senitnels have a high chance to be in split-brain situation again

### Are you using any custom parameters or values?
```
sentinel.enabled=true
replica.persistence.enabled=false
# Scenario 1
replica.podManagementPolicy=Parallel
# Scenario 2
replica.podManagementPolicy=OrderedReady
```
### What is the expected behavior?

Both sentinels and redis nodes should agree on a single redis master.

### What do you see instead?

Each sentinel follows its own master. This does not heal with time.

### Additional information

Looks like this is partially caused by the [workflow that guesses the current master](https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/scripts-configmap.yaml#L121-L183):
1. If there are any sentinels, ask them (but pods start simultaneosly, so there are none ready)
2. Otherwise, reuse master from persistence (but it is disabled)
3. Otherwise, assume master role for current node.

Redis clients are supposed to ask sentinel for the address of the current master. This issue results in wrong answer 2/3 times. As a result, the client may try to write to a read-only replica.

We are currently trying to workaround this issue by a combination of setting podManagementPolicy=OrderedReady and enabling persistence for sentinel only.

Note: this might be partially a bug in sentinel itself (not detecting conflicting configuration in sentinel.conf), see https://github.com/redis/redis/issues/12271

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Redis container image or Helm chart but about how the application or environment is being used/configured. It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

As you rightly pointed, for information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by shadjiiski** [comment]
> The scenario that you are describing would not meet those expectations, right?

* That would be scenario 2 only. Scenario 1 (podManagementPolicy: Parallel) would hit the issue in multi-az cluster as well
* I think the word **should** in that quote implies that you will not have access to your cluster if you don't comply. Not that it is expected to fail to recover without manual intervention after an outage due to different master configuration provided to the separater sentinels
* Following this guideline is not always in our control for on-prem products and is not always cheap in cloud. Do you really need to pay for multiple AZs when you are using redis as a mem cache? One could be making use of higher throughput by using local redis instance for read-only queries while still having eventual consistency of the cache as a whole.

> do you have any changes in mind to improve this chart?

Our current workaround is: disable parallel pod management, enable persistence for sentinel only. I didn't really get capacity to focus on anything better so nothing good so far. Here are some rough thoughts:
* Could be enough to amend the startup scripts to apoint node-0 to be master (instead of current node) if no other information is available. Not sure if this will play well in scenarios with enabled persistence though - might trigger failovers
* Maybe liveness probe could also fail if the node that the current sentinel believes is a master does not have a master role for some time (or does not match what other sentinels believe for some time). Not sure if this will play well with the failover mechanics or if will not slow down the probe too much
* I was thinking about some ordering in the startup scripts but that would kind of make the pod management policy useless
* Maybe the redis folks will someday detect the broken configuration and will trigger a failover

**Comment by andresbono** [comment]
It seems the issue with scenario 1 was hit out of the helm/k8s context: https://github.com/redis/redis/issues/12271#issuecomment-1615861659
