### ISSUE TITLE
[bitnami/kafka] Enabling TLS for Kafka Kraft mode

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#17041]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team - Please share the steps how to enable TLS for Kafka in Kraft mode. I have  deployed parameters which I have used for with zookeeper, which is not helping. Please find the below screen shot.

![image](https://github.com/bitnami/charts/assets/96808632/69161a4d-eb92-4b15-a795-98c9659a6260)

### Are you using any custom parameters or values?

No

### What do you see instead?

unable to deploy the with TLS in Kraft Mode.

**Comment by bharathreddy901** [comment]
Hi @carrodher - Do you have any inputs how to enable TLS for Kafka in Kraft mode, I have followed the steps which I have used to  do for with Zookeeper.

Thanks in advance.

**Comment by ThomasRutger** [comment]
I have a deployment running in Kraft mode, using TLS. But I only have one broker so not entirely the same situation. Perhaps you can share your deployment config?

**Comment by bharathreddy901** [comment]
Hi @ThomasRutger  - Please find the TLS configs for Kraft mode which I am using, But still not working.

existingSecret: "kafka-jks"
password: "bitnami"
listeners:  "CLIENT://:9092"
advertisedListeners: "CLIENT://$(MY_POD_NAME).kafka-headless.kafka.svc.cluster.local:9092"
listenerSecurityProtocolMap: "CLIENT:SSL"
interBrokerListenerName: CLIENT
clientProtocol: tls
interBrokerProtocol: tls

Thanks,
