### ISSUE TITLE
Wordpress initialise stuck at "nami INFO Initializing wordpress"

### ISSUE THREAD

**Issue by billhoph** [bitnami/charts#1704]
Issue on the following Wordpress chart:

- https://github.com/bitnami/charts/tree/master/upstreamed/wordpress

I was testing a number of helm chart on a newly created k8s cluster thru' kubeadm, while most of the chart works, but the quite simplest one "wordpress" doesn't.

While the same chart works in other clusters I build thru' Cluster API and other means, for this cluster I have rebuild the cluster for times, but issue persist. 

The PVC has created successfully and container is being started, yet the pod readiness probe keep restarting the pod as it cannot be initialized.

```console
# kubectl logs wordpress-1575473592-55dd6fcbb9-4wdwt

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress

# kubectl get pod wordpress-1575473592-55dd6fcbb9-4wdwt
NAME                                    READY   STATUS             RESTARTS   AGE
wordpress-1575473592-55dd6fcbb9-4wdwt   0/1     CrashLoopBackOff   83         8h
```

**Version of Helm and Kubernetes**:

```console
# helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @billhoph 

Could you run the commands below and share the output? That will increase the verbosity of the logs and we'll have more information to debug what's going on:

```console
$ cat > values.yaml <<'EOF'
extraEnv:
  - name: NAMI_LOG_LEVEL
    value: "trace"
EOF
$ helm install -f values.yaml my-wordpress stable/wordpress
```

**Comment by billhoph** [comment]
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre DEBUG Deleting the Varnish configuration
wordpre DEBUG Creating the Apache configuration vhost file
wordpre DEBUG Creating the Apache configuration https vhost file
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/.buildcomplete
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/.buildcomplete
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/disablePingback.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/disablePingback.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/extra-varnish
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/extra-varnish
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/index.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/index.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/license.txt
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/license.txt
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/licenses
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/licenses
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/opcache-dashboard.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/opcache-dashboard.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/readme.html
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/readme.html
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/tmp
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/tmp
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-activate.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/wp-activate.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-admin
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/wp-admin
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-blog-header.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/wp-blog-header.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-comments-post.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/wp-comments-post.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-config-sample.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/wp-config-sample.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-config.php
wordpre TRACE [configurePermissions] File to chmod: /opt/bitnami/wordpress/wp-config.php
wordpre TRACE [configurePermissions] File to chown: /opt/bitnami/wordpress/wp-content
root@k8s-01:~#
root@k8s-01:~#

it stucks like here

**Comment by juan131** [comment]
Hi @billhoph 

This is a known issue on platforms where chown/chmod operations are very slow. There's an existing issue where we're discussing this already. 

Could we move this conversation there? Please find the original issue in the link below:

- https://github.com/bitnami/charts/issues/1704

**Comment by billhoph** [comment]
Thanks alot!
I got the issue fixed by change the overlay2 docker storage driver to devicemapper

https://support.qasymphony.com/hc/en-us/articles/115004011906-Change-Docker-storage-driver-to-avoid-Overlay-issue

**Comment by juan131** [comment]
That's great @billhoph !!
I proceed to close the issue but please feel free to reopen it if you require further assistance.
