### ISSUE TITLE
[cassandra] Error in networkpolicy.yaml

### ISSUE THREAD

**Issue by qiuyuzhou** [bitnami/charts#1705]
https://github.com/bitnami/charts/blob/2786d13ae38ecb343149ed41b7cbf30e304424c5/bitnami/cassandra/templates/networkpolicy.yaml#L13-L23

`{{- if not .Values.networkPolicy.allowExternal }} ` should below the line `from:`

**Comment by juan131** [comment]
Hi @qiuyuzhou 

Thanks so much for reporting it! I just created a PR to address this issue.
