### ISSUE TITLE
[rabbitmq] Add path_prefix in rabbit management UI

### ISSUE THREAD

**Issue by SnoozeFreddo** [bitnami/charts#17067]
### Name and Version

bitnami/rabbitmq

### What is the problem this feature will solve?

Hi there,

i stumbled uppon the same problem as this guy [here](https://stackoverflow.com/questions/73872052/rabbitmq-management-plugin-there-is-no-template-when-using-rewrite-target-from).

How would i set the [management.path-prefix](https://www.rabbitmq.com/management.html#path-prefix) in bitnamis container?

I could build another docker container on top of bitnami and manually add the line to the conf, but does bitnami maybe expose more env vars that they didn't mention in their docs?

**Comment by Mauraza** [comment]
Hi @SnoozeFreddo,

You can use a custom file with the configuration you need, you can find more information in the [README.md of RabbitMQ](https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#configuration-file)
