### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] no setting for remote access to rabbitmq cluster ports

### ISSUE THREAD

**Issue by dcmeadley** [bitnami/charts#17076]
### Name and Version

Bitnami rabbitmq-cluster-operator

### What architecture are you using?

arm64

### What steps will reproduce the bug?

No paramater available to open rabbitmq cluster service to outside connections so unable to access rabbitmq management console 

### What do you see instead?

Unable to connect

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
