### ISSUE TITLE
bitnami fails to start with persistent data and initScripts

### ISSUE THREAD

**Issue by rrey** [bitnami/charts#17070]
### Name and Version

bitnami/rabbitmq 11.16.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the Helm chart with an initScripts section filled with a dummy script (see values later in this issue)
2. Wait for the pod to be ready.
3. Kill the pod with `kubectl delete pod rabbitmq-0`
4. The pod will remain in `CrashLoopBackOff`

### Are you using any custom parameters or values?

```yaml
---
replicaCount: 1
initScripts:
  init_rabbit_test.sh: |
     #!/bin/sh
     rabbitmqctl cluster_status
fullnameOverride: "rabbitmq"
```

### What is the expected behavior?

When killing the pod, it should be restarted without error. This is the case without an `initScripts` section in the values.

### What do you see instead?

```
NAME         READY   STATUS             RESTARTS      AGE
rabbitmq-0   0/1     CrashLoopBackOff   6 (43s ago)   6m19s
```

### Additional information

I investigated the issue and it seems that the scripts executed by the entrypoint is not starting rabbitmq before running the custom init scripts when it finds persistant data.

See the logs for the first startup:
```
rabbitmq 11:17:07.61
rabbitmq 11:17:07.61 Welcome to the Bitnami rabbitmq container
rabbitmq 11:17:07.61 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 11:17:07.61 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 11:17:07.61
rabbitmq 11:17:07.62 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 11:17:07.63 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 11:17:07.64 INFO  ==> Initializing RabbitMQ...
rabbitmq 11:17:07.66 INFO  ==> Starting RabbitMQ in background...
rabbitmq 11:17:12.33 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
Cluster status of node rabbit@rabbitmq-0.rabbitmq-headless.rrey.svc.cluster.local ...
[...]
```

And when it fails to restart:
```
abbitmq 11:18:40.64
rabbitmq 11:18:40.64 Welcome to the Bitnami rabbitmq container
rabbitmq 11:18:40.64 Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 11:18:40.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 11:18:40.64-
rabbitmq 11:18:40.64 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 11:18:40.65 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 11:18:40.66 INFO  ==> Initializing RabbitMQ...
rabbitmq 11:18:40.68 INFO  ==> Persisted data detected. Restoring...
rabbitmq 11:18:40.68 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
Error: unable to perform an operation on node 'rabbit@rabbitmq-0.rabbitmq-headless.rrey.svc.cluster.local'. Please see diagnostics information and suggestions below.
```

In the second case the `==> Starting RabbitMQ in background...` does not appear before the `Loading user's custom files from /docker-entrypoint-initdb.d ...` entry.
If rabbitmq is not started, any command in the init script that requires rabbitmq will fail.

**Comment by andresbono** [comment]
Does it make sense that if the init script that you are providing needs RabbitMQ to be running, you start it as part of that init script?

For example:

```
  init_rabbit_test.sh: |
    #!/bin/sh
    ! is_rabbitmq_running && rabbitmq_start_bg

    rabbitmqctl cluster_status
```

There might be other use cases where starting RabbitMQ twice (once for the init scripts, once for starting the service in foreground) is not the best approach.

**Comment by rrey** [comment]
IMO the chart/image from bitnami provide the `initScripts` feature and the scripts provided should not take care about starting rabbitmq since this is the job of the entrypoint and bitnami's implementation.

As a end user, I don't have any knowledge around the start procedure implemented by bitnami (and I think people choose bitnami to avoid having to ramp up to much or reimplement things).
I think most of people don't even know the `is_rabbitmq_running` and `rabbitmq_start_bg` even exists.

Also note that everything works with first deployments and fail after that. So it sounds like a difference in the start procedure (it is) that needs to be fixed.

**Comment by andresbono** [comment]
I guess that always starting rabbitmq in the background before running the custom init scripts shouldn't present any problem or introduce any breaking change.

Would you like to submit a PR addressing it? Our team will be happy to review it. Note that this is in fact a [bitnami/containers](https://github.com/bitnami/containers) issue.
