### ISSUE TITLE
[bitnami/keycloak] postgresql password is lost after reinstalling the chart

### ISSUE THREAD

**Issue by mariusleu** [bitnami/charts#17079]
### Name and Version

bitnami/keycloak 15.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the `bitnami/keycloak` chart with `postgresql.enabled=true`
2. Uninstall using `helm uninstall`
3. Install again on the same namespace.

### What is the expected behavior?

After reinstallation, the keycloak server should start successfully.

### What do you see instead?

After reinstallation, the keycloak server fails to start because of database authentication failure.

### Additional information

After uninstall, the persistent volumes stay in the namespace for further utilization, but the `keycloak-postgresql` secret is deleted.

On reinstallation the old persistent volume is reused but a new password secret is generated for postgresql.
However, the postgresql container is not updating the new password.

We end up in a situation where keycloak starts with the new postgresql password, which now is invalid.

I see 2 options here:
1. Add the option to keep the postgresql secret when the release is uninstalled, by adding the `helm.sh/resource-policy: keep` on the secret.
2. Fix the `bitnami/postgresql` container image to properly set the new password on the `postgresql` and `keycloak` users.

**Comment by carrodher** [comment]
Passwords are stored in the PV, if you reuse a PV from a previous deployment in subsequent deployments, you will need to log in with the credentials stored in that PV (the ones from the previous deployment) regardless of the credentials set during the subsequent deployments.

If you would like to reuse the PV you will need to pass during the new deployment the passwords from the previous ones (the ones stored in the PV) by using `--set` or directly editing the _values.yaml_ file; for instance
```
helm install my-release --set auth.adminPassword=foo oci://registry-1.docker.io/bitnamicharts/keycloak
```
where `foo` is the password stored in the PV.

When the Helm chart is installed for the first time, some installation notes are shown. In those notes, you can see some hints about how to access the different services and how to obtain the password. You can see those notes at any time by running `helm get notes RELEASE-NAME`.

**Comment by mariusleu** [comment]
I totally get that, however, from a user perspective it's quite an unexpected behaviour. While the PV stand still after the uninstallation, the password secret is gone and is regenerated on a subsequent deployment. However, on the 2nd try it won't work.

Can you confirm that's an expected behaviour across the bitnami charts and is like that by design? If so, then we can close this issue.

**Comment by RLutsch** [comment]
I have the same problem, postgres and keycloak uses the same secret, I added the `helm.sh/resource-policy: keep` annotation. 

After a while postgres changes the password (probably argocd that re-applies the chart),

The POSTGRES_POSTGRES_PASSWORD changes inside the container despite it refrencing the secret
