### ISSUE TITLE
Has there been any performance improvement for gcache?

### ISSUE THREAD

**Issue by sjy-dv** [bitnami/charts#17081]
### Name and Version

bitnami/mariadb-galera:10.11.4-debian-11-r0

### What architecture are you using?

None

### What steps will reproduce the bug?

Until recent years, there have been issues related to insufficient gcache size or the explosive growth of gcache. Fortunately, I haven't seen such issues in 2023. As far as I know, starting from Galera version 4, a feature was added to automatically adjust the gcache size. Is that correct?

### What do you see instead?

reddit

### Additional information

What I'm wondering is whether developers still need to be concerned about this aspect. If this is resolved, we can focus on infrastructure management and adhere to existing database configurations. However, if it's not resolved, it could potentially require a significant amount of time as our traffic grows.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Galera container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
