### ISSUE TITLE
[bitnami/redis-cluster] commonLabels not applied to Pods

### ISSUE THREAD

**Issue by georgelupu** [bitnami/charts#17098]
### Name and Version

bitnami/redis-cluster 8.6.2 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Add the following commonLabels to values.yaml:
```
commonLabels:
  test.label: test
```
3. and deploy redis-cluster 8.6.2 chart
4. Observe how the commonLabels is applied to all K8s resources (i.e. StatefulSets/ConfigMaps etc) except Pods.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

As it is documented, the commonLabels should be applied to all deployed objects - including Pods.

### What do you see instead?

The commonLabels are not applied to redis-cluster Pods.

### Additional information

To fix this issue, i suggest to add the following code to redis-statefulset.yaml file, after line #31 (https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/redis-statefulset.yaml#L31):

      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
      {{- end }}

**Comment by fabio-s-franco** [comment]
In addition to that, updating common labels cause the deployment to fail, because it tries to apply it to resources that do not allow it:

```shell
│ Error: cannot patch "release" with kind StatefulSet: StatefulSet.apps "example" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy'
```

Would love to PR this one @carrodher , but already late on finishin what I need to do before I get off for vacation. If in the mean time I find some time, I may take a look.

**Comment by georgelupu** [comment]
Hi @carrodher - it will be my pleasure to contribute back. 
I prepared a PR here: https://github.com/bitnami/charts/pull/17355
