### ISSUE TITLE
[bitnami/postgresql] Support for plpython3u

### ISSUE THREAD

**Issue by agapebondservant** [bitnami/charts#17106]
### Name and Version

bitnami/postgresql 12.5.6

### What is the problem this feature will solve?

Would like to see if it would be possible to support PL/Python. Is there any workaround for this?

### What is the feature you are proposing to solve the problem?

Support for plpython3u extension

**Comment by agapebondservant** [comment]
Thanks for the update! I did try creating a fork and adding it. Thus far I havent found a way to install it with this flavor of Postgres (works with the official Dockerhub Postgres image). Will keep digging, but would you happen to have any guidance on this?

**Comment by javsalgar** [comment]
Hi,

My advice would be to create a multi-stage container where in the first stage you compile the extension and in the second one you copy it to the container.
