### ISSUE TITLE
[bitnami/kafka] could not start in cluster mode

### ISSUE THREAD

**Issue by visla-xugeng** [bitnami/charts#17114]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1: installed the Sentry in k8s (https://github.com/sentry-kubernetes/charts/tree/develop/sentry)
1.1: installed Kafka cluster with 3 nodes, 1 zookeeper node.
2: manually edited the PVC volume from 8G to 20G
```
kubectl -n sentry edit pvc data-sentry-kafka-0

kubectl -n sentry edit pvc data-sentry-kafka-1

kubectl -n sentry edit pvc data-sentry-kafka-2
```
3: kafka-0 and kafka-1 works well. The kafka-2 got error:

```
[2023-06-14 04:29:49,730] ERROR [KafkaServer id=2] Fatal error during KafkaServer shutdown. (kafka.server.KafkaServer)
java.lang.IllegalStateException: Kafka server is still starting up, cannot shut down!
	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:696)
	at kafka.Kafka$.$anonfun$main$3(Kafka.scala:100)
	at kafka.utils.Exit$.$anonfun$addShutdownHook$1(Exit.scala:38)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-14 04:29:49,731] ERROR Halting Kafka. (kafka.Kafka$)
```

https://github.com/sentry-kubernetes/charts/issues/907

### What do you see instead?

failed to start the kafka cluster

**Comment by javsalgar** [comment]
Hi,

It seems to me that the issue could be related to how Kafka manages this kind of situations. Could you try checking with the upstream kafka devs to see how to avoid the issue? If there is something that we need to change in the Bitnami packaging of Kafka, we can work on it but first it would be better to confirm with upstream.
