### ISSUE TITLE
Pod remains pending and PVC stays unbound

### ISSUE THREAD

**Issue by rabbagliettiandrea** [bitnami/charts#17128]
### Name and Version

bitnami/postgresql 12.5.7

### What architecture are you using?

k3s v. v1.27.1+k3s1
amd64

### What steps will reproduce the bug?

When launching a new release of the Bitnami/PostgreSQL Helm chart using EBS CSI with a storage class configured with `WaitForConsumer`, I sometimes encounter an issue where the Pod remains pending because it cannot find the PVC (PersistentVolumeClaim). The PVC also remains pending because it doesn't have any consumer associated with it, which is expected behavior. However, after several minutes (around 6 or 7), the issue seems to resolve itself, and the PVC binds successfully, allowing the Pod to be scheduled and start working.

Steps to reproduce:

1. Deploy the Bitnami/PostgreSQL Helm chart using EBS CSI with a storage class configured with `WaitForConsumer`.
2. Observe the Pod and PVC creation process.

### Are you using any custom parameters or values?

```yaml
global:
  postgresql:
    auth:
      database: "db"
      postgresPassword: "postgresql"
primary:
  persistence:
    storageClass: ebs-gp2
    size: 10Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
```

### What is the expected behavior?

The Pod should be scheduled and start running immediately after the PVC binds successfully.

### What do you see instead?

The Pod remains pending for several minutes because it cannot find the PVC. The PVC also remains pending due to the absence of any consumer. After approximately 6 or 7 minutes, the PVC binds successfully, and the Pod is scheduled and starts running.

### Additional information

Events from `kubectl describe pod`:

```
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Warning  FailedScheduling        36m   default-scheduler        running PreFilter plugin "VolumeBinding": error getting PVC "default/postgresql-0": could not find v1.PersistentVolumeClaim "default/data-postgresql-0"
  Normal   Scheduled               32m   default-scheduler        Successfully assigned default/postgresql-0 to worker1234
  Normal   SuccessfulAttachVolume  32m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-348e7a01-c0af-4a0f-8fb9-9c9cf9a8bf45"
  Normal   Pulled                  32m   kubelet                  Container image "docker.io/bitnami/postgresql:15.3.0-debian-11-r7" already present on machine
  Normal   Created                 32m   kubelet                  Created container postgresql
  Normal   Started                 32m   kubelet                  Started container postgresql
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami PostgreSQL container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the use of the underlying technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by rabbagliettiandrea** [comment]
@carrodher thank you for your response!
It could be a race-condition on the helm chart maybe? If not, I don't get what do you mean with "we highly recommend checking forums and user guides made available by the project behind the the technology"; that is: how should I point the issue?

Thank you so much for your support, keep it up!
Have a good day,
Andrea
