### ISSUE TITLE
[bitnami/postgresql-ha] How to enable ssl/tls

### ISSUE THREAD

**Issue by wantdrink** [bitnami/charts#1712]
[bitnami/postgresql-ha] 1.10

Hi there,
I've installed postgresql 12.1 with postgresql-ha chart (NodePort). 
I read the document and didn't find how to enable SSL/TLS in pods with helm install. Is there any guidance for it?

Thanks very much.

**Comment by rafariossaa** [comment]
Hi @wantdrink ,
  I am sorry, there is not that option. 

  If you implement that, please consider to send a PR with your changes.

Best regards,

**Comment by wantdrink** [comment]
Thanks @rafariossaa

**Comment by omerfsen** [comment]
+1

**Comment by philross** [comment]
+1

**Comment by rafariossaa** [comment]
Hi, 
  I am creating a internal task to provide this feature, we will come back as soon as we have news.

**Comment by rafariossaa** [comment]
Hi,
  Now it is possible to configure TLS at pgpool and postgresql level.
  Would you like to take a look to it ?

**Comment by wantdrink** [comment]
Yep I'm glad to learn that:)  @rafariossaa
