### ISSUE TITLE
Redis-Sentinel cannot close RDB persistence

### ISSUE THREAD

**Issue by 937988621** [bitnami/charts#17131]
### Name and Version

Bitnami/redis version16.13.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I want to disable RDB and AOF data persistence in Redis Sentinel mode, so I did the following，
1.I used nfs shared storage。
2.I used custom parameters
eg:
```yaml
## @param commonConfiguration [string] Common configuration to be added into the ConfigMap
## ref: https://redis.io/topics/config
##
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  # appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
```

### What is the expected behavior?

When I close RDB in the configuration file, there should be no dump. rdb file present

### What do you see instead?
```console
$ kubectl get pod -n liulonga 
NAME                                                     READY   STATUS    RESTARTS   AGE
redis-liulonga-1685496879665-redis-sentinel6212-node-0   2/2     Running   0          16s
redis-liulonga-1685496879665-redis-sentinel6212-node-1   2/2     Running   0          12s
redis-liulonga-1685496879665-redis-sentinel6212-node-2   2/2     Running   0          7s

$ k exec -it -n liulonga redis-liulonga-1685496879665-redis-sentinel6212-node-0 bash -c redis
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-5.1$ redis-cli -p 6379 -a redis_123 
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> config get save
1) "save"
2) ""
127.0.0.1:6379> 
bash-5.1$ 
bash-5.1$ ls -l data/
total 4
-rw-r--r-- 1 1001 root 177 Jun 15 11:13 dump.rdb
```

**Comment by 937988621** [comment]
I'm very sorry, the layout of my question is very chaotic。
I want to disable RDB and AOF data persistence in Redis Sentinel mode, so I did the following，
1.I used nfs shared storage。
2.I used custom parameters
eg:
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  # appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""

kubectl get pod -n liulonga
NAME READY STATUS RESTARTS AGE
redis-liulonga-1685496879665-redis-sentinel6212-node-0 2/2 Running 0 16s
redis-liulonga-1685496879665-redis-sentinel6212-node-1 2/2 Running 0 12s
redis-liulonga-1685496879665-redis-sentinel6212-node-2 2/2 Running 0 7s

kubectl exec -it -n liulonga redis-liulonga-1685496879665-redis-sentinel6212-node-0 bash -c redis
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-5.1$ redis-cli -p 6379 -a redis_123
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> config get save
1) "save"
2) ""
127.0.0.1:6379> 
bash-5.1$ 
bash-5.1$ ls -l data/
total 4
-rw-r--r-- 1 1001 root 177 Jun 15 11:13 dump.rdb

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Redis container image or Helm chart but about how the application or environment is being used/configured.


For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by 937988621** [comment]
> It seems it is not an issue related to the Bitnami Redis container image or Helm chart but about how the application or environment is being used/configured.
> 
> For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.
> 
> That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

Thank you very much for your answer. I have tried using non containerized deployment of redis entity, but when I use the same configuration, that is, when RDB is turned off, there will not be a dump. rdb file generated. I checked the relevant startup scripts of the container and did not find any additional RDB configuration added, but the dump.rdb file does indeed exist, so I am very confused

**Comment by shlomitubul** [comment]
@937988621 this  might answer your question: https://github.com/bitnami/charts/pull/25121#issuecomment-2058882237
