### ISSUE TITLE
Kafka Uncontrolled Memory Consumption

### ISSUE THREAD

**Issue by arjun2038** [bitnami/charts#17169]
### Name and Version

bitnami/kafka 21.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed kafka in my kubernetes cluster as a three node cluster with following command.
```
helm upgrade --install kafka bitnami/kafka --version 21.4.0 --namespace ilens-infra \
  --set defaultReplicationFactor=3 \
  --set offsetsTopicReplicationFactor=3 \
  --set transactionStateLogReplicationFactor=3 \
  --set transactionStateLogMinIsr=2 \
  --set "extraEnvVars[0].name=KAFKA_CFG_MIN_INSYNC_REPLICAS" \
  --set-string "extraEnvVars[0].value=2" \
  --set replicaCount=3 \
  --set podAntiAffinityPreset=soft \
  --set nodeAffinityPreset.type=hard \
  --set nodeAffinityPreset.key=NodeAffinity \
  --set "nodeAffinityPreset.values[0]=ilens-infra" \
  --set podManagementPolicy=OrderedReady \
  --set persistence.enabled=true \
  --set persistence.size=4Gi \
  --set persistence.storageClass=managed-standardssd-retain \
  --set kraft.enabled=false \
  --set zookeeper.enabled=true \
  --set "zookeeper.fullnameOverride=zookeeper" \
  --set zookeeper.replicaCount=3 \
  --set zookeeper.podAntiAffinityPreset=soft \
  --set zookeeper.nodeAffinityPreset.type=hard \
  --set zookeeper.nodeAffinityPreset.key=NodeAffinity \
  --set "zookeeper.nodeAffinityPreset.values[0]=ilens-core" \
  --set zookeeper.podManagementPolicy=OrderedReady \
  --set zookeeper.persistence.storageClass=managed-standardssd-retain \
  --set "zookeeper.persistence.enabled=true" \
  --set "zookeeper.persistence.size=2Gi"
```
  
  
Following is the kafka resource usage when i deployed the cluster 
  
```
NAME                                          CPU(cores)   MEMORY(bytes)  
kafka-0                                           6m           361Mi
kafka-1                                           6m           358Mi
kafka-2                                           6m           360Mi
```

I pushed data to kafka cluster to a topic ilens_prod(single partition) for some time , I stopped the the producer once reach kafka lag value of 20000. Resource usage after the activity as follows

```
NAME                                          CPU(cores)   MEMORY(bytes)  
kafka-0                                            29m          522Mi
kafka-1                                            15m          465Mi
kafka-2                                            16m          470Mi
```
Kafka lag as shown the following image.(I started a consumer for some time which showing CURRENT-OFFSET value as 569.After that the consumer got removed.)
![image](https://github.com/bitnami/charts/assets/74967141/393003a8-e43a-41bf-9512-1447714de668)

Since Kafka doesn't have any consumers or producers, I noticed that memory usage was constantly rising.
For me it seems to be the memory is using for cache
As of late, usage as follows

After 15 minutes
```
NAME                                          CPU(cores)   MEMORY(bytes)  
kafka-0                                       9m                 538Mi
kafka-1                                       8m                 483Mi
kafka-2                                       9m                 492Mi
```

After 45 minutes
```
NAME                                          CPU(cores)   MEMORY(bytes)  
kafka-0                                           9m           563Mi
kafka-1                                           9m           566Mi
kafka-2                                           9m           499Mi

```
Why the memory usage is getting increased, Is there any configuration which will limit the memory(page cache) usage

### What is the expected behavior?

Since there is no producers and consumers.Memory usage should be constant or reducing

### What do you see instead?

Memory usage is continuously increasing

**Comment by carrodher** [comment]
It seems a very specific use case difficult to reproduce on our side and very tied to your scenario.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
