### ISSUE TITLE
Docker composite. yml installation, unable to logout

### ISSUE THREAD

**Issue by yzzd** [bitnami/charts#17179]
### Name and Version

image: docker.io/bitnami/suitecrm:8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Centos 8, newly installed users cannot log out by clicking on exit in the upper right corner

### What do you see instead?

Docker-composite. yml installation, unable to logout
Centos 8, newly installed users cannot log out by clicking on exit in the upper right corner

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami SuiteCRM container image or Helm chart but about how the application or environment is being used/configured.


For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
