### ISSUE TITLE
[bitnami/external-dns] Add label app.kubernetes.io/version for external-dns

### ISSUE THREAD

**Issue by psimms-r7** [bitnami/charts#17186]
### Name and Version

external-dns

### What is the problem this feature will solve?

Can we add the label app.kubernetes.io/version for the external-dns chart please this would help with tracking versions

### What is the feature you are proposing to solve the problem?

add the label app.kubernetes.io/version

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Would you like to submit a PR adding the feature?
