### ISSUE TITLE
Will etcd chart support arm64 arch?

### ISSUE THREAD

**Issue by cwocwo** [bitnami/charts#1719]
**Which chart**:

etcd

**Description**
We want to use etcd on arm64 arch.
Will etcd chart support arm64 arch?

**Comment by dani8art** [comment]
Hi @cwocwo 

I would say that it is not a problem with the chart but the docker image. Could you open an issue on https://github.com/bitnami/bitnami-docker-etcd/issues, please?

Regards.

**Comment by cwocwo** [comment]
@dani8art Thanks for your reply. I have created a new issue: https://github.com/bitnami/bitnami-docker-etcd/issues/6

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
