### ISSUE TITLE
[bitnami/apisix] apisix dashboard cracks in plugin page

### ISSUE THREAD

**Issue by karl-chanel** [bitnami/charts#17193]
### Name and Version

bitnami/apisix/2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

narmal helm install with dashboard enabled 

### What do you see instead?

bitnami/apisix/2.0.0 used apisix dashboard version 3.0.1,after helm install ,open the apisix dashboard in the boswer ,and click plugins , then the ui stuck , inspect the network in the broswer , the request  to  this /plugin/list returns 404 , BTW the offical helm chart from apisix use 3.0.0 for dashboard  in the latest helm release ,and it works fine ,and if you try to change the image version to 3.0.1,the problem appearred just like above , and i try to switch to apisx dashboard 3.0.0 in bitnami/apisix helm chart ,and it doesnt fix the problem

**Comment by karl-chanel** [comment]
https://github.com/apache/apisix-dashboard/issues/2820

**Comment by rogerogers** [comment]
Before merging, you can add plugins to the value file.

**Comment by karl-chanel** [comment]
thumbs up
