### ISSUE TITLE
[bitnami/sonarqube] chart version 2.1.6 does not include fix from PR

### ISSUE THREAD

**Issue by chrira** [bitnami/charts#17203]
### Name and Version

bitnami/sonarqube 2.1.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. use bitnami/sonarqube 2.1.6
2. set `jvmOpts`
3. they do not appear in SONARQUBE_WEB_JAVA_ADD_OPTS

### Are you using any custom parameters or values?

jvmOpts in values.yaml

### What is the expected behavior?

The fixes of the [PR](https://github.com/bitnami/charts/pull/15806) is included in v 2.1.6

Therefore a new version 2.1.7 should be created with the changes from the PR.

### What do you see instead?

It seems that the sonarqube Release 2.1.6 just contains some image tag updates but not the changes from the PR.
But the PR got merged without increasing the version again.
This should not happen. When a release is created the next PR should get a new version.

### Additional information

1. This [PR](https://github.com/bitnami/charts/pull/15806) was intended to get the version 2.1.6
2. download chart: `helm pull bitnami/sonarqube --version 2.1.6 `
3. check templates/_helpers.tpl -> the changes of the PR are not included
4. [bitnami/sonarqube] Release 2.1.6 (https://github.com/bitnami/charts/pull/15915) took the version 2.1.6
5. The [PR](https://github.com/bitnami/charts/pull/15806)  is only available on v3 with sonarqube 10

**Comment by rafariossaa** [comment]
Hi,
  The latest version is `3.2.4`, could you check that version ?

**Comment by chrira** [comment]
Yes, this version includes all changes.
But the SonarQube version for 3.2.4 is 10.
We must use SonarQube 9.9, which is only in the chart versions 2.x

As a quick fix I'm using the chart 3.2.4 and set the image tag to 9.9...
With that I have the newest chart logic and still SonarQube 9.9.

**Comment by rafariossaa** [comment]
Hi @chrira,
  That is the way to go, take the current version and using the images you need. We don't produce new releases of old major versions.

**Comment by chrira** [comment]
Thank you @rafariossaa . I was not sure how tight the app and chart versions are coupled.
I'll do it like that.

But we still have the problem that the changes of the  [PR](https://github.com/bitnami/charts/pull/15806) are not included in v 2.1.6.
I think it is a process problem that the PR has been merged without the check that the version 2.1.6 was already released in the mean time.

How can we prevent such problems in the future?

**Comment by rafariossaa** [comment]
Hi,
  I was taking a look to what had happened here.
  What happened was that there was a change from our CI/CD, that also updated the chart to `2.1.6` and the same time of you change, finally the CI/CD change was merged first and yours came a little bit later. You can see that the [merge commit of your PR](https://github.com/bitnami/charts/commit/521f7101bf1f23eca2675599c517688ad5af86b0) does not include the change for `Chart.yaml`.
  Unfortunately, the following release of this chart was a major version `3.0.0`, and this was the first release that included your changes.
  Sorry for the noise.  I handled this to our engineering team to figure out a barrier for these kind of cases.

**Comment by chrira** [comment]
Thanks for checking. I see now what happened.
For my side you can close the issue.
