### ISSUE TITLE
Ability to specify the metrics service nodeport

### ISSUE THREAD

**Issue by gilbertg** [bitnami/charts#17213]
### Name and Version

bitnami/mongodb 13.6.6

### What is the problem this feature will solve?

No problem setting up metrics with a NodePort service, but I can't specify the nodeport, neither does the chart (metrics-svc.yaml) allow it.

Auto-node port is chosen, which can change, and break my scraper. Unfortunately the scraper is outside the k8s cluster, so can't work off a serviceMonitor or internal port.

### What is the feature you are proposing to solve the problem?

Extend metrics-svc.yaml to allow a nodePort for the metrics service to be specified in values.yaml.

### What alternatives have you considered?

I can't think of another way to the expose the service outside the cluster.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
