### ISSUE TITLE
[bitnami/mongodb] Add a flag to optionally install `mongo-express`

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17241]
### Name and Version

bitnami/mongodb 13.15.2

### What is the problem this feature will solve?

When managing a mongodb instance, it can be helpful to have the https://github.com/mongo-express/mongo-express interface available to examine the database/server/instance.

### What is the feature you are proposing to solve the problem?

Add a feature flag to `bitnami/mongodb` that would load a container for https://github.com/mongo-express/mongo-express with the correct secrets/env/etc to connect to the deployed mongodb.

This would likely involve generating a container that matches the bitnami standards with this application inside of it.  Unless you just want to pull the upstream container : https://github.com/mongo-express/mongo-express#usage-docker

### What alternatives have you considered?

A small yaml file on my side to load this container.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Indeed, we would need to package the mongo-express container first in order to add support for it to the chart. That would need to be evaluated by the team. In the meantime, you can use the `sidecars` section in the chart and add the container.
