### ISSUE TITLE
[bitnami/discourse] containers can't connect to database  ( postgresql and redis ) 

### ISSUE THREAD

**Issue by Amine-741** [bitnami/charts#17254]
### Name and Version

charts/bitnami/discourse

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello 

I am encountering a "CrashLoopBackOff" error when deploying a Helm chart. ( https://github.com/bitnami/charts/tree/main/bitnami/discourse ) ; I'm working in OKD . ( Community edition of openshift ) 

### What do you see instead?

The containers is stack at this step
```
discourse 21:28:22.65
discourse 21:28:22.65 Welcome to the Bitnami discourse container
discourse 21:28:22.65 Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 21:28:22.66 Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 21:28:22.66
discourse 21:28:22.68 INFO ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 21:28:22.70 INFO ==> Trying to connect to the database server
discourse 21:28:22.77 INFO ==> Creating database bitnami_application
discourse 21:28:23.01 INFO ==> Creating Discourse configuration file
discourse 21:28:23.15 INFO ==> Ensuring Discourse directories exist
discourse 21:28:23.19 INFO ==> Trying to connect to the database server
discourse 21:28:23.25 INFO ==> Populating database
```

**Comment by javsalgar** [comment]
Hi,

Could you launch the chart with `image.debug=true` to see if there's more debug information?

**Comment by Amine-741** [comment]
Hello Javsalgar ;
Thank you for your response .
This is what i got when lanchng with image.debug=true  



discourse 09:04:31.74 INFO ==> Creating database bitnami_application
CREATE EXTENSION
CREATE EXTENSION
discourse 09:04:31.95 DEBUG ==> Validating settings in DISCOURSE_* environment variables...
discourse 09:04:31.99 INFO ==> Creating Discourse configuration file
discourse 09:04:32.00 DEBUG ==> Setting hostname to '127.0.0.1' in Discourse configuration
discourse 09:04:32.01 DEBUG ==> Setting db_host to 'discourse-postgresql' in Discourse configuration
discourse 09:04:32.03 DEBUG ==> Setting db_port to '5432' in Discourse configuration
discourse 09:04:32.04 DEBUG ==> Setting db_username to 'bn_discourse' in Discourse configuration
discourse 09:04:32.06 DEBUG ==> Setting db_password to 'postgres' in Discourse configuration
discourse 09:04:32.07 DEBUG ==> Setting db_name to 'bitnami_application' in Discourse configuration
discourse 09:04:32.09 DEBUG ==> Setting db_backup_host to 'discourse-postgresql' in Discourse configuration
discourse 09:04:32.10 DEBUG ==> Setting db_backup_port to '5432' in Discourse configuration
discourse 09:04:32.12 DEBUG ==> Setting redis_host to 'discourse-redis-master' in Discourse configuration
discourse 09:04:32.13 DEBUG ==> Setting redis_port to '6379' in Discourse configuration
discourse 09:04:32.14 DEBUG ==> Setting redis_password to 'adminadmin' in Discourse configuration
discourse 09:04:32.17 INFO ==> Ensuring Discourse directories exist
discourse 09:04:32.22 INFO ==> Trying to connect to the database server
?column?
----------
1
(1 row)
discourse 09:04:32.28 INFO ==> Populating database
chroot: cannot change root directory to '/': Operation not permitted

**Comment by dgomezleon** [comment]
Hi @Amine-741 ,

Some users reported issues with Openshift. Could you please take a look at [this previous case](https://github.com/bitnami/charts/issues/17039#issuecomment-1587004309)?

**Comment by Amine-741** [comment]
Hi @dgomezleon 

Thank you for your response. I was finally able to run my pod by adding this block to my manifest:

securityContext:
  capabilities:
    add: ["SYS_CHROOT"]

The problem now is that when I try to access the application within my browser, I see four dots charging and the application gets stuck at this step

Could you help me please

**Comment by dgomezleon** [comment]
Hi @Amine-741 ,

Did you follow the helm instructions?:

```
NAME: discourse
LAST DEPLOYED: Thu Jun 22 11:32:54 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: discourse
CHART VERSION: 10.3.2
APP VERSION: 3.0.3

** Please be patient while the chart is being deployed **Discourse can be accessed via port 80 on the following DNS name from within your cluster:

    discourse.default.svc.cluster.local

To connect to Discourse from outside the cluster, perform the following steps:

1.  Create a port-forward to the service:

    kubectl port-forward --namespace default svc/discourse 80:80 &
    echo "Discourse URL: http://127.0.0.1:80"

2. Open a browser and access Discourse using the obtained URL.

3. Get your Discourse login credentials by running:

    export DISCOURSE_PASSWORD=$(kubectl get secret --namespace "default" discourse-discourse -o jsonpath="{.data.discourse-password}" | base64 -d)
    echo User:     user
    echo Password: $DISCOURSE_PASSWORD
```

Note you need to use the same port (80). Using a different one may produce that error.

I hope it helps

**Comment by dillfrescott** [comment]
I am having this exact same issue and nothing ive tried is solving it

**Comment by dillfrescott** [comment]
In k3s

**Comment by Amine-741** [comment]
Do you have any logs ?

**Comment by dillfrescott** [comment]
I apologize it was because my k3s cluster traefik external ip was incorrect it seems

**Comment by dillfrescott** [comment]
I fixed it and its working now

**Comment by dillfrescott** [comment]
It appears that the functionality is intermittent. There’s likely a bug that needs to be addressed.

**Comment by dillfrescott** [comment]
```
NAME                         READY   STATUS             RESTARTS      AGE
discourse-postgresql-0       1/1     Running            0             90s
discourse-redis-master-0     1/1     Running            0             90s
discourse-7586755d47-lzvmx   0/2     CrashLoopBackOff   3 (29s ago)   90s
root@vps:~# kubectl logs -f discourse-7586755d47-lzvmx -c sidekiq
discourse 12:53:24.71 INFO  ==>
discourse 12:53:24.71 INFO  ==> Welcome to the Bitnami discourse container
discourse 12:53:24.71 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 12:53:24.71 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 12:53:24.71 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 12:53:24.71 INFO  ==>
discourse 12:53:44.78 WARN  ==> Hostname discourse-postgresql could not be resolved, this could lead to connection issues
discourse 12:54:04.80 WARN  ==> Hostname discourse-redis-master could not be resolved, this could lead to connection issues
discourse 12:54:04.81 INFO  ==> Creating Discourse configuration file
discourse 12:54:04.85 INFO  ==> Enabling SMTP
discourse 12:54:04.88 INFO  ==> Ensuring Sidekiq directories exist
discourse 12:54:04.89 INFO  ==> Trying to connect to the database server
```

**Comment by sfxworks** [comment]
Man, why does bitnami ship charts they don't test, but expect us to test and debug it for them 

```
 sam  kubectl logs -f user800fitforum-discourse-7bdd8d6585-9zb6j
Defaulted container "discourse" out of: discourse, sidekiq
discourse 09:07:53.45 INFO  ==> 
discourse 09:07:53.45 INFO  ==> Welcome to the Bitnami discourse container
discourse 09:07:53.46 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 09:07:53.46 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 09:07:53.46 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 09:07:53.46 INFO  ==> 
discourse 09:07:53.47 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 09:07:53.47 INFO  ==> Trying to connect to the database server
discourse 09:07:53.49 INFO  ==> Creating database bitnami_application
discourse 09:07:53.57 INFO  ==> Creating Discourse configuration file
discourse 09:07:53.61 INFO  ==> Ensuring Discourse directories exist
discourse 09:07:53.63 INFO  ==> Trying to connect to the database server
discourse 09:07:53.65 INFO  ==> Populating database
```

**Comment by theosanderson** [comment]
I got stuck in the same place "Populating database". In my case I had created an empty database with a particular name already and then given that name to the chart.

When I instead deleted the database, letting the system create it, the issue was solved.
