### ISSUE TITLE
[bitnami/airflow] Add possibility to specify schema in airflowdb externalDatabase

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#17288]
### Name and Version

bitnami/airflowdb

### What is the problem this feature will solve?

It is not possible to define a different schema for an external database. One database can have several schemas as a logical grouping. 

### What is the feature you are proposing to solve the problem?

Separate airflow tables on the schema level

**Comment by javsalgar** [comment]
Hi,

Could you show how the rendered configuration with the schema separation would look like? To see how this could be implemented.

**Comment by oktayalizada** [comment]
Hi @javsalgar, 

Parameter could look like this: 
```
[externalDatabase: 
  schema: nice_schema
```

I am not sure  what you want me to provide. But if we refer to Airflow config we can see there is an optional parameter called schema:
https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/connections/postgres.html

There is an environment variable called: AIRFLOW__DATABASE__SQL_ALCHEMY_SCHEMA

**Comment by javsalgar** [comment]
Hi!

Thank you so much! Then it would be simple to add the value and map it to the environment variable. Would you like to submit a PR adding the feature? If not we will work on it but we cannot guarantee an ETA.

**Comment by oktayalizada** [comment]
Hi @javsalgar, 
It took me some time to verify this, but this environment variable doesn't work, I will investigate this a little more and then I can, of course, create a PR for this.
