### ISSUE TITLE
[bitnami/sonarqube] Allow connect to Microsoft SQL Server (  jdbc:sqlserver:// ) 

### ISSUE THREAD

**Issue by abdennour** [bitnami/charts#17296]
### Name and Version

bitnami/sonarqube 3.2.3

### What is the problem this feature will solve?

I cannot connect to MSSQL database

### What is the feature you are proposing to solve the problem?

Either support MSSQL connection using Helm way ( values).
Or check , if `.Values.extraProperties` includes `sonar.jdbc.url` , then , ignore helm values

### What alternatives have you considered?

No Solution

**Comment by CeliaGMqrz** [comment]
Hi @abdennour,

Sorry for the delay.

Thanks for your feature request. It seems that from the [Sonarqube upstream chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube), this specific feature for MSSQL connection is not supported. However, following the [Sonarqube documentation ](https://n-saikiran.gitbook.io/sonarqube/installation-of-sonarqube/311-installation-of-sonarqube-in-sql-server) and this [point](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/jdbc-config.yaml#L13), it could be set as an experimental feature. Unfortunately, we are a small team with limited capacity to handle all the requests for the different apps in the catalog.

Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
