### ISSUE TITLE
[bitnami/wordpress] - customHTAccessCM

### ISSUE THREAD

**Issue by mountaindog** [bitnami/charts#17294]
### Name and Version

bitnami/wordpres 16.1.17

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Not necessarily a bug, but I need to figure out how to resolve this issue. According to the documentation, the preferred approach to add a RewriteRule is to use a ConfigMap. I have some basic rules; the essential value is `RewriteBase /wp/.` Including this generates an error - ``only valid in per-directory config files.`` This value is important because it matches the ingress Prefix (/wp). I had many issues with WP not respecting the Prefix and redirecting to the root URL, which breaks the site. Adding these rules seems to fix the Prefix issue. WP is running in Multisite mode. 

### Are you using any custom parameters or values?

customHTAccessCM: htaccess-config
```
      <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteBase /wp/
      RewriteRule ^index\.php$ - [L]

      # add a trailing slash to /wp-admin
      RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

      RewriteCond %{REQUEST_FILENAME} -f [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^ - [L]
      RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
      RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
      RewriteRule . index.php [L]
      </IfModule>
```

### What do you see instead?

This error is in the console.
 ``only valid in per-directory config files.`` 

### Additional information

I moved to a new K8s cluster and tried running the solution I posted [here](https://github.com/bitnami/charts/issues/16229), but it doesn't seem to work anymore. It's not the cluster, but something has changed in the installation process. Not sure. Hopefully, this is an easy setting change.

**Comment by aoterolorenzo** [comment]
Hi @mountaindog,

I would say the `RewriteBase` directive can only be used in per-directory configuration files such as .htaccess, and as you said, seems motivated more by the nginx nature than by a bug on our side. In this cases I would try to ask upstream for a specific solution or alternative.

How about to include the /wp/ prefix in the RewriteRules?

`RewriteRule ^wp/([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]`
