### ISSUE TITLE
how to use azure AD for sonarqube helm chart in the latest version

### ISSUE THREAD

**Issue by vasudevbannaravuri** [bitnami/charts#17298]
### Name and Version

bitnami/sonarqube:10.0.0-debian-11-r16

### What is the problem this feature will solve?

how to use azure AD for sonarqube helm chart in the latest version

### What is the feature you are proposing to solve the problem?

how to use azure AD for sonarqube helm chart in the latest version

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami SonarQube container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
