### ISSUE TITLE
Tomcat chart - credentials by default

### ISSUE THREAD

**Issue by black-and-white-swan** [bitnami/charts#17301]
### Name and Version

bitnami/tomcat 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When installing Tomcat chart, the password by default is always password and it's impossible to change it. It's a security problem in production.

### Are you using any custom parameters or values?

No, we don't have some parameters

### What do you see instead?

In every cases we have this default password

**Comment by carrodher** [comment]
By using the `tomcatPassword` parameter you can set any password at deployment time, this password is stored in a secret and used in the different k8s object that requires it. Aren't you able to change the password by modifying the `tomcatPassword` parameter?
