### ISSUE TITLE
[bitnami/harbor] Enabling volumePermissions does not affect the permissions

### ISSUE THREAD

**Issue by Craftoncu** [bitnami/charts#17321]
### Name and Version

harbor/16.5.3/2.8.0 (2.8.1-debian-11-r5)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Enabling the init container in helm configuration does initiate a init container:
![image](https://github.com/bitnami/charts/assets/55136417/5232a362-1081-4bde-90fa-8f4457aa231f)
![image](https://github.com/bitnami/charts/assets/55136417/11b1c655-9bd0-4544-b974-955f3afb079e)

But if I look into the storage dir, from a registry container within the same pod as the init container was, the permissions which are set are wrong:
![image](https://github.com/bitnami/charts/assets/55136417/428de080-420f-4f46-9d9b-7fbe7465b5cb)

### Are you using any custom parameters or values?

```yaml
  volumePermissions:
    containerSecurityContext:
      runAsUser: 0
    enabled: true
```

### What do you see instead?

As already described, the permissions which are set are wrong. But the container got the exit code 0 without logs. Thats kinda weird.

**Comment by Craftoncu** [comment]
Tried it with latest version today. Same issue

**Comment by Craftoncu** [comment]
Closed not on purpose

**Comment by Mauraza** [comment]
Hi @Craftoncu 

could you try to add `image.debug=true` and check if appears something in the logs?
