### ISSUE TITLE
[bitnami/postgresql] Password secret not created in postgres chart 12.5.7 and above

### ISSUE THREAD

**Issue by jasonkaedingrhino** [bitnami/charts#17334]
### Name and Version

bitnami/postgresql 12.5.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Installing postgres chart version 12.5.7 and higher will not create a secret for the password provided by `global.postgresql.auth.password`

```
$> helm install my-postgres oci://registry-1.docker.io/bitnamicharts/postgresql --version 12.5.7 --namespace my-namespace --set "architecture=standalone" --set "auth.enablePostgresUser=false" --set "global.postgresql.auth.username=myuser" --set "global.postgresql.auth.password=N0tS3cr3t"
NAME: my-postgres
LAST DEPLOYED: Fri Jun 23 13:06:55 2023
NAMESPACE: my-namespace
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: postgresql
CHART VERSION: 12.5.7
APP VERSION: 15.3.0

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS names from within your cluster:

    my-postgres-postgresql.my-namespace.svc.cluster.local - Read/Write connection

To get the password for "myuser" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace my-namespace my-postgres-postgresql -o jsonpath="{.data.password}" | base64 -d)

To connect to your database run the following command:

    kubectl run my-postgres-postgresql-client --rm --tty -i --restart='Never' --namespace my-namespace --image docker.io/bitnami/postgresql:15.3.0-debian-11-r7 --env="PGPASSWORD=$POSTGRES_PASSWORD" \
      --command -- psql --host my-postgres-postgresql -U myuser -d postgres -p 5432

    > NOTE: If you access the container using bash, make sure that you execute "/opt/bitnami/scripts/postgresql/entrypoint.sh /bin/bash" in order to avoid the error "psql: local user with ID 1001} does not exist"

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace my-namespace svc/my-postgres-postgresql 5432:5432 &
    PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U myuser -d postgres -p 5432

$> kubectl get secret --namespace my-namespace my-postgres-postgresql
Error from server (NotFound): secrets "my-postgres-postgresql" not found
```

I have also run this procedure for newest chart version 12.5.8 and it also demonstrates the same behavior.
I have also demonstrated that the secret disappears when doing `helm upgrade` from 12.5.6 -> 12.5.7 as well even when password is provided via `--set`

It seems that similar issues have been documented in #17079 and #15073

### Are you using any custom parameters or values?

```
--set "architecture=standalone" 
--set "auth.enablePostgresUser=false" 
--set "global.postgresql.auth.username=myuser" 
--set "global.postgresql.auth.password=N0tS3cr3t"
```

### What is the expected behavior?

Expected the secret to be created per the NOTES documentation, and expected this `kubectl` command to confirm the secret exists:

`kubectl get secret --namespace my-namespace my-postgres-postgresql`

### What do you see instead?

`Error from server (NotFound): secrets "my-postgres-postgresql" not found`

### Additional information

I am already aware of the risk about upgrading without providing the password via `--set`.  

If, while in this state, I choose not to provide the password, then I still get the Bitnami-generated error message suggesting to obtain the password from the secret when upgrading.  But if there is no secret, then we can't even follow the recommendation!

**Comment by CeliaGMqrz** [comment]
Hi, @jasonkaedingrhino. 

Sorry for the delay. Thanks for reporting this issue. 

I have followed your steps, however, I have checked that the secret is created correctly. 

Just to make sure, you had an old secret called `my-postgres-postgresql` ? I think you are entering the wrong name to get the secret, that's why you got the `Error from server (NotFound): secrets "my-postgres-postgresql" not found` error. Could you be sure to indicate the correct name of the secret? 

* To get the secret, you can run the following:
```
$ kubectl get secret --namespace my-namespace
NAME                                TYPE                 DATA   AGE
sh.helm.release.v1.my-postgres.v1   helm.sh/release.v1   1      85s

```
* You can check that the secret is successfully created:
```
$ kubectl get secret/sh.helm.release.v1.my-postgres.v1 -n my-namespace
 
NAME                                TYPE                 DATA   AGE
sh.helm.release.v1.my-postgres.v1   helm.sh/release.v1   1      24m
```

```
$ kubectl describe secret/sh.helm.release.v1.my-postgres.v1 -n my-namespace
Name:         sh.helm.release.v1.my-postgres.v1
Namespace:    my-namespace
Labels:       modifiedAt=1688456039
              name=my-postgres
              owner=helm
              status=deployed
              version=1
Annotations:  <none>

Type:  helm.sh/release.v1

Data
====
release:  80276 bytes
```
If the problem persists let us know. Thanks for the feedback.

**Comment by CeliaGMqrz** [comment]
Hi @jasonkaedingrhino, sorry my fault. 

I just checked it again. There is indeed an issue. Let me check with the team and I will get back with updates. 

Sorry for the inconvenience.

**Comment by jasonkaedingrhino** [comment]
The test procedure outline above does work for version `12.6.2`

**Comment by vvp1983** [comment]
13.0.0 version same error..
