### ISSUE TITLE
[bitnami/magento] volume permissions is not working

### ISSUE THREAD

**Issue by evheniyt** [bitnami/charts#17337]
### Name and Version

bitnami/magento 22.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install magento with  `volumePermissions.enabled=true`

### Are you using any custom parameters or values?

```yaml
magento:
  volumePermissions:
    enabled: true
```

### What is the expected behavior?

Volume permissions should be successfully updated

### What do you see instead?

`volume-permissions` init container is failing with this error in logs: 
```
chown: missing operand after '/bitnami/magento'                                                                                                                                                                     
Try 'chown --help' for more information. 
```

### Additional information

I think it is failing because `chown` is missing reference to a user and group
```
          args:
            - -ec
            - |
              mkdir -p "/bitnami/magento"
              chown "/bitnami/magento"
              find "/bitnami/magento" -mindepth 1 -maxdepth 1 -not -name "config" -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}
          securityContext:
```

**Comment by Mauraza** [comment]
Hi @evheniyt,

Could you share all the values are you using to try the reproduce the issue?

**Comment by Mauraza** [comment]
Hi @evheniyt,

I try with your values and everything works fine.
 It seems related to your storageClass. Where are you deploying the chart?

**Comment by evheniyt** [comment]
@Mauraza I don't think that it could be related to storage class, as I have mentioned the `chown` command is not correct
![image](https://github.com/bitnami/charts/assets/14334318/f63207bf-d814-484a-9517-69ef9b07797c)

If you will try to execute this command in the init container it will fail with the same error:
![image](https://github.com/bitnami/charts/assets/14334318/043b910a-f965-4b5e-a2d8-32fb7869d121)

I'm using a lot of other bitnami charts with this storage class and everything works fine there.

[Here is](https://github.com/bitnami/charts/blob/main/bitnami/prestashop/templates/deployment.yaml#L86) example from another bitnami chart with a correct `chown` command that works fine for me.

**Comment by Mauraza** [comment]
Hi @evheniyt,

as appears in the error of the command is missing the operand, I created a [PR](https://github.com/bitnami/charts/pull/17418) to solve the problem.
