### ISSUE TITLE
[bitnami/kafka] how do i set "loadbalancer external service type" so i can connect to kafka from outside?

### ISSUE THREAD

**Issue by encryptblockr** [bitnami/charts#1734]
How do i set "loadbalancer external service type" so i can connect to kafka from outside?
like they have it for the kubernetes kafka helm charts? https://github.com/helm/charts/tree/master/incubator/kafka#loadbalancer-external-service-type

will like a way to connect to the kafka cluster from outside the cluster and one way is by exposing using loadbalancer external service

what is settings to enable this in value.yaml file?

thanks

**Comment by juan131** [comment]
Hi @encryptblockr 

Did you try setting the `service.type` parameter to `LoadBalancer`? Check the link below:

- https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L254

That parameter will set the Kafka service type as you can check in the link below:

- https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/svc.yaml#L9
