### ISSUE TITLE
[bitnami/contour] Allow setting Policy Configuration

### ISSUE THREAD

**Issue by stumueller** [bitnami/charts#17349]
### Name and Version

bitnami/contour

### What is the problem this feature will solve?

I don't know if this is already possible. I couldn't find a way of doing it, so if there is could you let me know.

Our security team have asked us to remove the server header envoy from responses.
This is doable in envoy and projectcontour have added a global config to support this: https://github.com/projectcontour/contour/issues/4359

It looks like this global config needs to be set via a configmap https://projectcontour.io/docs/1.25/configuration/#configuration-file and https://projectcontour.io/docs/1.25/configuration/#policy-configuration (applyToIngress)

Would it be possible to allow us to set this in the helm chart? or is it already possible to add a configmap to the helm chart?

Thanks 

### What is the feature you are proposing to solve the problem?

Would it be possible to allow us to set this in the helm chart? or is it already possible to add a configmap to the helm chart?

Thanks

**Comment by javsalgar** [comment]
Hi!

Using `extraDeploy` and the `args` section, you can add a new configmap and modify the contour parameters to point to the configmap. Would that work for your case?

**Comment by stumueller** [comment]
It may do, I've also just found existingConfigMap and configInline which I guess may also work? Are there any working examples of these being used in your documentation?

Would i just do a
set {
  name = "configInline"
  value = { serverHeaderTransformation: pass_through }
}

in my terraform helm deployment?

**Comment by javsalgar** [comment]
Hi!

The use of configInLine would work, make sure that you also maintain the defaults already set.

**Comment by stumueller** [comment]
Hi, Sorry to be a pain but I'm struggling to understand how to get it to work. I've inherited this deployment and I'm still finding my way around it.

I currently have this:
resource "helm_release" "contour" {
  name             = "contour"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "contour"
  namespace        = "projectcontour"
  create_namespace = true
  version          ="12.1.1"
  timeout          = 900

  values = [jsonencode({})]

  set {
    name = "contour.nodeSelector.workload"
    value = "system"
  }

  set {
    name = "envoy.nodeSelector.workload"
    value = "system"
  }

  set {
    name = "configInline"
    value = "{serverHeaderTransformation: pass_through}"
  }
}

I've just added that final set{} but my contour pods keep crashing with
Leaving GOMAXPROCS=4: CPU quota undefined"
contour: error: failed to parse configuration: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into config.Parameters,

I've also tried 
 set {
    name = "configInline"
    value = "{applyToIngress: true}"
  }
but that gave the same error

You mentioned maintaining the defaults already set - how would I do that?

Thanks

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami contour container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
