### ISSUE TITLE
[FATAL][root] Error: listen EAFNOSUPPORT: address family not supported :::5601

### ISSUE THREAD

**Issue by meisamhasani** [bitnami/charts#17375]
### Name and Version

https://github.com/bitnami/charts/tree/main/bitnami/kibana/#installing-the-chart

### What architecture are you using?

None

### What steps will reproduce the bug?

Run

### Are you using any custom parameters or values?

helm install kibana oci://registry-1.docker.io/bitnamicharts/kibana \
  --set service.type=NodePort \
  --set global.storageClass=nfs-client \
  --set persistence.storageClass=nfs-client \
  --set service.nodePorts.http=30030 \
  --set elasticsearch.hosts[0]=elasticsearch-master \
  --set elasticsearch.port=9200

### What do you see instead?

[FATAL][root] Error: listen EAFNOSUPPORT: address family not supported :::5601

### Additional information

Hello
This error occurs after installing in Logpod

**Comment by meisamhasani** [comment]
![image](https://github.com/bitnami/charts/assets/2770416/2e2a76ed-c461-4bc6-a92d-fe04f1724a6f)

**Comment by meisamhasani** [comment]
Solved!
in Configmap.yml
kibana.yml: |
    server.host: "0.0.0.0" <-------changed to this

**Comment by aarvee11** [comment]
I had ipv6 disabled on my servers and @meisamhasani comment helped me.... makes sense, cheers  !!!
