### ISSUE TITLE
[bitnami/external-dns] New version 0.13.5 available upstream

### ISSUE THREAD

**Issue by gw0** [bitnami/charts#17382]
### Name and Version

bitnami/external-dns 6.20.4

### What is the problem this feature will solve?

There is a new upstream release of `external-dns` version 0.13.5 (https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.13.5). It includes many new features, especially filtering by IngressClassName (https://github.com/kubernetes-sigs/external-dns/pull/2054).

### What is the feature you are proposing to solve the problem?

Ingress annotations are deprecated and IngressClassName should be used instead.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it (reported in https://github.com/kubernetes-sigs/external-dns/issues/3680).

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by gw0** [comment]
Helm chart for `external-dns` still using `0.13.4`...

**Comment by FraPazGal** [comment]
Hello @gw0, our `bitnami/external-dns@0.13.5` is now available with https://github.com/bitnami/charts/pull/17692 and would be updated in our Helm repo shortly. I'll close this issue now but please reach out to us if any problem arises.

Thanks for your patience!
