### ISSUE TITLE
[postgresql/postgresql-ha] backup tooling

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17389]
### Name and Version

bitnami/postgresql 12.5.8

### What is the problem this feature will solve?

Recovery and data retention requirements for database systems.

### What is the feature you are proposing to solve the problem?

Integration with some sort of postgresql backup tool.  A scheduled pg_dump might be sufficient or perhaps something fancy like barman https://pgbarman.org/about/barman-vs-pg_dump/.

### What alternatives have you considered?

Just rolling my own solution.

**Comment by javsalgar** [comment]
Hi,

Our charts have the `extraDeploy` section where you can deploy extra objects like a cron job. This should be useful for creating your own backup policy.
