### ISSUE TITLE
[bitnami/mongodb] backup database

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17394]
### Name and Version

bitnami/mongodb 13.15.2

### What is the problem this feature will solve?

Disaster recovery

### What is the feature you are proposing to solve the problem?

Some sort of backup script/tooling integrated into the helm chart

### What alternatives have you considered?

Some sort of roll my own

**Comment by javsalgar** [comment]
Hi,

Our charts have the `extraDeploy` section where you can deploy extra objects like a cron job. This should be useful for creating your own backup policy.
