### ISSUE TITLE
consul-charts Configuration file loading order

### ISSUE THREAD

**Issue by weifan01** [bitnami/charts#1740]
Sorry, my English skills are poor.

**consul charts 1.6.1**

**data_dir configuration items in config.json are never used, was covered by the consul.json of data_dir**

Execute the following command in the consul pod, check the configration：

```
I have no name!@online-consul-0:/opt/bitnami/consul/conf$ ls
config.json  connection.json  consul.json
I have no name!@online-consul-0:/opt/bitnami/consul/conf$ cat config.json
{
"datacenter":"dc2",
"domain":"consul",
"data_dir":"/opt/bitnami/consul/data",
"pid_file":"/opt/bitnami/consul/tmp/consul.pid",
"server":true,
"ui":false,
"bootstrap_expect":3,
"addresses": {
    "http":"0.0.0.0"
},
"ports": {
    "http":8500,
    "dns":8600,
    "serf_lan":8301,
    "server":8300
},
"serf_lan":"0.0.0.0"
}
I have no name!@online-consul-0:/opt/bitnami/consul/conf$ cat consul.json
{
    "node_name": "10.101.74.55",
    "datacenter": "dc1",
    "domain": "consul",
    "data_dir": "/bitnami/consul",
    "pid_file": "/opt/bitnami/consul/tmp/consul.pid",
    "ui": true,
    "bootstrap_expect": 3,
    "performance": {
      "raft_multiplier": 1
    },
    "addresses": {
        "http": "0.0.0.0"
    },
    "retry_join": ["online-consul-0.online-consul.middle.svc"],
    "ports": {
        "http": 8500,
        "dns": 8600,
        "serf_lan": 8301,
        "server": 8300
    },
    "serf_lan": "0.0.0.0"
}
```
Both configuration files have _data_dir_ , In the configuration file loading order, data_dir configuration items in config.json are never used. refer to the [statefulset.yaml](https://github.com/bitnami/charts/blob/master/bitnami/consul/templates/statefulset.yaml), Therefore, My volume is mounted to/opt/bitnami/consul/data, but there is no any persistent data,  

```
volumeMounts:
  {{- if .Values.tlsEncryptionSecretName }}
  - name: consul-tls-certs
    mountPath: "/opt/bitnami/consul/certificates/"
    readOnly: true
  {{- end }}
  {{- if .Values.persistence.enabled }}
  - name: data
    mountPath: /bitnami/consul/data
  {{- end }}
  {{- if .Values.configmap }}
  - name: consul-config
    mountPath: /opt/bitnami/consul/conf/config.json
    subPath: config.json
  - name: consul-config
    mountPath: /opt/bitnami/consul/conf/connection.json
    subPath: connection.json
  {{- end }}

```
Whether need to change the value of the mountPath (/bitnami/consul/), or change the value of consul-config's subPath.

thank you!

**Comment by alemorcuq** [comment]
Hi, @weifan01.

Is there any reason why you want the `data_dir` to be `/opt/bitnami/consul/data` instead of `/bitnami/consul/data`? The chart expects the persistent volume to be mounted to `/bitnami/consul/data`, as you can see here: https://github.com/bitnami/charts/blob/d1d1d20465d3e5adf6e4ac6dac3870a68e234f72/bitnami/consul/templates/statefulset.yaml#L169

If you delete the `"data_dir":"/opt/bitnami/consul/data",` line from your `config.json` (or set it to `/bitnami/consul` as in the `consul.json` file) it should work. Can you try?
