### ISSUE TITLE
[bitnami/mongodb] NetworkPolicy for mongodb

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17409]
### Name and Version

bitnami/mongodb 13.15.2

### What is the problem this feature will solve?

Restricting access to mongodb

### What is the feature you are proposing to solve the problem?

If the networkpolicy logic from the postgresql chart could be ported over to this chart, that would be ideal.

### What alternatives have you considered?

Self managed policy

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
