### ISSUE TITLE
[bitnami/influxdb] extend network policy features

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17410]
### Name and Version

bitnami/influxdb 5.6.2

### What is the problem this feature will solve?

Selecting specific objects by label to permit access

### What is the feature you are proposing to solve the problem?

Copy over the pod/namespace selection bits from the postgresql template so users can have fine grained control over which services have access to influxdb

### What alternatives have you considered?

Some sort of hand generated policy.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
