### ISSUE TITLE
Not able to apply custom configuration when deploying mongodb with bitnami helm chart.

### ISSUE THREAD

**Issue by Sumitpalucc** [bitnami/charts#17415]
### Name and Version

bitnamicharts/mongodb-13.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have tried with options provided in helm values.yaml.

### Are you using any custom parameters or values?

yes, I used values.yaml

### What is the expected behavior?

I am expecting to have custom configuration like process management fork = true.

### What do you see instead?

I am able to get only default configurations.

**Comment by carrodher** [comment]
Could you please provide more info and examples about the different alternatives you tried and the result? Thanks

**Comment by Sumitpalucc** [comment]
I have tried the values.yaml file for changing the default mongodb configurations as shown below:
configuration: |
  processManagement:
    enabled: true
    fork: true
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

**Comment by Sumitpalucc** [comment]
Hi @carrodher,

Can I have an update on the above issue?

**Comment by Sumitpalucc** [comment]
Hi @carrodher,

Plz update.

**Comment by aoterolorenzo** [comment]
Hi @Sumitpalucc

So sorry for the late response, I completely miss this one. Could you attach the config file output from the generated pod?

**Comment by Sumitpalucc** [comment]
Dear @carrodher,

Thanks for your above response.

Below are the pod configurations I am getting after applying the helm chart with custom values.

**# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  #bindIp:

# replica set options
#replication:
  #replSetName: replicaset
  #enableMajorityReadConcern: true

# sharding options
#sharding:
  #clusterRole:

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: false

# security options
security:
  authorization: enabled
  #keyFile: replace_me**

It is not able to pick the configuration from the values.yaml like fork: true.

Regards
Sumit

**Comment by aoterolorenzo** [comment]
Unfortunately I'm not able to reproduce or diagnose your issue. Could you attach the pod log output and the result pod configuration file?
