### ISSUE TITLE
DETAIL: pool_passwd file does not contain an entry for "[dbUsername]"

### ISSUE THREAD

**Issue by bsakweson** [bitnami/charts#1741]
**Which chart**:
binami/postgresql-ha

**Description**
Managed to set things up on kubernetes and was able to connect to db with using the database 
admin username/secret. However, when I create a user on admin panel, pgadmin4, I am unable to login to the server using the pgpool service endpoint.

**Steps to reproduce the issue:**

1. Install chart successfully on my k8S cluster
2. Setup pgadmin4 web client
3. Use pgpool service endpoint to connect to db cluster with admin username/secret successfully
4. Create a new db user with login privileges using the pgadmin4 web console
5. Attempt to login with this new created user but was unsuccessful

**Describe the results you received:**
Instead of connection to the server successfully, I go this error:
<img width="604" alt="Screen Shot 2019-12-15 at 12 47 54 PM" src="https://user-images.githubusercontent.com/14130356/70866564-53ef2580-1f39-11ea-8d0a-e868328de7fa.png">

**Describe the results you expected:**
I got the error shown on the figure above.

**Additional information you deem important (e.g. issue happens only occasionally):**
Successful authentication to my cluster user that user.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @bsakweson 

The users you created are created in the PostgreSQL backends. However, you're not updating the **pool_passwd** on Pgpool.

For instance, in the example below:

```console
$ helm install --name postgres-ha bitnami/postgresql-ha
$ kubectl exec -it $(kubectl get pods -l app.kubernetes.io/component=pgpool,app.kubernetes.io/name=postgresql-ha -o jsonpath='{.items[0].metadata.name}') -- cat /opt/bitnami/pgpool/conf/pool_passwd
postgres:md5e1124b331ad5fbac21f764e6c64634d2
```

You'll find out that there's only one entry for the user `postgres`. You need to add the entries for your new users.

**Comment by jaipradeesh** [comment]
@juan131 Is there a way to add it as part of the chart config file than doing it manually?

**Comment by juan131** [comment]
Hi @jaipradeesh 

> Is there a way to add it as part of the chart config file than doing it manually?

At this moment, we don't provide a way to do that automatically (using configmaps or similar solutions).

> Tried doing it manually with this command ...

Could you try using the command below?

```console
$ kubectl exec -it $(kubectl get pods -l app.kubernetes.io/component=pgpool,app.kubernetes.io/name=postgresql-ha -o jsonpath='{.items[0].metadata.name}') -- pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "foo" "bar"
```

**Comment by jaipradeesh** [comment]
@juan131 

Thanks. Specifying the right config file works.

looks like pgpool is making many idle connections to the backend. How to customize pgpool.conf and upgrade the pod?

**Comment by juan131** [comment]
Hi @jaipradeesh 

At this moment we don't offer a way to specify your custom **pgpool.conf** (as we do for the **postgresql.conf** file, see https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L241).

As you can see in the link below, the image already supports this feature, so we just need to adapt the chart to add this feature:

- https://github.com/bitnami/bitnami-docker-pgpool#configuration-file

I created a PR to adapt the Helm chart. Find it in the link below:

- https://github.com/bitnami/charts/pull/1823

**Comment by tah-mas** [comment]
Changing the pool_passwd works, but have you got an eta for automating this? My concern is that if the postgres-postgresql-ha-pgpool-* is restarted the updated pool_passwd changes are lost. Thanks

**Comment by juan131** [comment]
Hi @tah-mas 

I think the simplest thing we can do is providing support to include your custom scripts (a similar solution to the one we offer for the PostgreSQL component, see https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L271) so your custom script is executed every-time the Pgpool container is started.  This way, you can include a script like the one below:

```bash
#!/bin/bash

USERS=("user1:password1" "user2:password2" "user2:password2")

for user in "${USERS[@]}"; do
    user_info=(${user//:/ })
    pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "${user_info[0]}" "${user_info[1]}"
done
```


Would that work for you?

**Comment by tah-mas** [comment]
Thanks @juan131! That would be great.

**Comment by juan131** [comment]
Hi @tah-mas 

I cannot give you any ETA, but I created an internal task to work on this specific solution I proposed. I hope we can work on it ASAP, so we can provide this feature to you.

Thanks for your understanding and patience.

**Comment by tah-mas** [comment]
Thanks for the update @juan131 . I look forward to the new feature :-)

**Comment by juan131** [comment]
Hi @tah-mas 

The PR adding support for this feature was merged! Could you please give it a try? You have 3 options to test it:
- Clone the repo and put your custom scripts under the `bitnami/postgresql-ha/files/pgpool-entrypoint-initdb.d/` directory.
- Use the `initdbScripts` parameter to pass the content of the scripts
- Create a configmap with your scripts, and use the `initdbScriptsCM` parameter to indicate the name of the configmap including your scripts.

More info at: https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L379

**Comment by hytromo** [comment]
I tried it through `pgpool.initdbScriptsCM` and it works :+1: So I think this can be closed!

One thing I noticed is that chart option is not in the README.

**Comment by tah-mas** [comment]
Sorry for the late reply. Yes this works. I use pgpool.initdbScriptsCM

**Comment by juan131** [comment]
Great @tah-mas @hytromo !! I'm glad this new parameter helped you to solve your issue!

**Comment by MrAmbiG** [comment]
What worked for me?
ssh to pgpool pod
```
kubectl -n citadel exec <PGPOOL POD> -- /bin/bash
touch /opt/bitnami/pgpool/conf/pgpool.conf
pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "USERNAME" "PASSWORD"
# extra measures
echo "host all all 0.0.0.0/0 md5"
echo "host all all 0.0.0.0/0 trust"
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing your solution.

**Comment by MrAmbiG** [comment]
> Hi @jaipradeesh
> 
> > Is there a way to add it as part of the chart config file than doing it manually?
> 
> At this moment, we don't provide a way to do that automatically (using configmaps or similar solutions).
> 
> > Tried doing it manually with this command ...
> 
> Could you try using the command below?
> 
> ```
> $ kubectl exec -it $(kubectl get pods -l app.kubernetes.io/component=pgpool,app.kubernetes.io/name=postgresql-ha -o jsonpath='{.items[0].metadata.name}') -- pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "foo" "bar"
> ```

This works but if your pgpool replicas are more than 1 then you must do it for each pod by incrementing .items[0] till .items[n-1] where n is the number of pgpool replicas. FYI it worked. I only hope that it persists. I did however try the helm chart docs which asks us to do the following.

pgpool.customUsers.passwords | Comma or semicolon separeted list of the associated passwords for the users to be added to pgpool_passwd | "pass1"
-- | -- | --

pgpool.customUsers.username | Comma or semicolon separeted list of the associated passwords for the users to be added to pgpool_passwd | "user1"
-- | -- | --
This works as documented but it doesnt if you want to add more users after the initial installation of the chart by adding more users and passwords to the above settings as per the docs then it wont work. Then you will have to go to pgpool pods to make changes as suggested here. I hope the changes persist after reboot.

**Comment by juan131** [comment]
Hi @MrAmbiG 

Did you try using the `pgpool.initdbScripts` parameter as I suggested on [this comment ](https://github.com/bitnami/charts/issues/1741#issuecomment-578637118)? You can mount a custom script such as the one below to add new users:

```bash
#!/bin/bash

USERS=("user1:password1" "user2:password2" "user3:password3")

for user in "${USERS[@]}"; do
    user_info=(${user//:/ })
    pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "${user_info[0]}" "${user_info[1]}"
done
```

**Comment by javsalgar** [comment]
Thanks for sharing!

**Comment by nauni77** [comment]
Just if someone will see this issue and have not now a solution. Now it is possible to configure:

```
pgpool:
  customUsers:
    usernames: "keycloak ciam"
    passwords: "my_keycloak*PWD my_ciam*PWD"
```
Users and passwords are separated by a space character.

**Comment by BitTheByte** [comment]
@nauni77 Could you specify the version of the chart you're using? I've having troubles with the lastest version `8.1.0`

**Comment by mogoman** [comment]
An idea:

There could be a way to dynamically generate the password file if an external secret is used.
```
pgpool.customUsersSecret: my-users
```

The idea would be to attach a RBAC account to the pod to be able to read the secret and then curl against the Kubernetes API, retrieving the secret data.

The existing env vars `PGPOOL_POSTGRES_CUSTOM_USERS` and `PGPOOL_POSTGRES_CUSTOM_PASSWORDS` could then be overwritten with the secret data (say using a crontab, or a script that sleeps for a minute in a loop) and then the `pgpool_generate_password_file` from `/opt/bitnami/scripts/libpgpool.sh` be executed to update the file.

I did some tests, pgpool does not need seem to need a restart when this file changes.

Could this be feasible? The secret can be updated externally (either by hand, API etc) and pgpool will (within a minute or two) start working with the new user without needing to restart the pod (and cutting all connections).

 I tried updating the two env vars and executing the `pgpool_generate_password_file` function, but the pool_passwd file didn't update, not sure why. I will try and do more tests when I get time.

**Comment by nauni77** [comment]
> @nauni77 Could you specify the version of the chart you're using? I'm having trouble with the latest version `8.2.1`

Hello, sorry for my late answer:

NAME         	NAMESPACE    	REVISION	UPDATED                             	STATUS  	CHART              	APP VERSION
postgresql-ha	postgresql-ha	7       	2021-12-14 22:18:25.642988 +0100 CET	deployed	postgresql-ha-8.1.2	11.14.0

**Comment by juan131** [comment]
Hi @hytromo 

> There could be a way to dynamically generate the password file if an external secret is used
> ...
> The idea would be to attach a RBAC account to the pod to be able to read the secret and then curl against the Kubernetes API, retrieving the secret data.
> ...

Thanks so much for your suggestion! IMHO, that's quite a complex solution that's out of the scope of the chart (it feels more like what you expect from an operator). Also, in terms of security, giving privileges to an init container to patch existing K8s objects is quite dangerous.

**Comment by mpolawar** [comment]
> What worked for me? ssh to pgpool pod
> 
> ```
> kubectl -n citadel exec <PGPOOL POD> -- /bin/bash
> touch /opt/bitnami/pgpool/conf/pgpool.conf
> pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "USERNAME" "PASSWORD"
> # extra measures
> echo "host all all 0.0.0.0/0 md5"
> echo "host all all 0.0.0.0/0 trust"
> ```

worked as a charm :)
