### ISSUE TITLE
[bitnami/influxdb] backup influxdb

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17419]
### Name and Version

bitnami/influxdb 5.6.2

### What is the problem this feature will solve?

Disaster recovery

### What is the feature you are proposing to solve the problem?

Some sort of backup script/tooling integrated into the helm chart.

### What alternatives have you considered?

Rolling my own.

**Comment by carrodher** [comment]
There are different parameters to configure backups, see https://github.com/bitnami/charts/tree/main/bitnami/influxdb#influxdb-backup-parameters. Did you find any issue using them?

**Comment by jcpunk** [comment]
It appears I configured them wrongly, the bug is on my side.
