### ISSUE TITLE
[bitnami/postgresql] Add read-only user for database

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17426]
### Name and Version

bitnami/postgresql 12.5.8

### What is the problem this feature will solve?

Some applications do not require write access to the database, having a seeded read-only user will permit greater hardening by only providing read access.

### What is the feature you are proposing to solve the problem?

Update the helm chart to include flags for creating a read-only user along side the read-write user.

### What alternatives have you considered?

building my own script to inject at the entry point.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
