### ISSUE TITLE
[bitnami/mongodb] Create read-only user for database

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#17427]
### Name and Version

bitnami/mongodb 13.15.2

### What is the problem this feature will solve?

Some applications only require read access to a database/collection.  By providing a read-only user the privileges are further reduced.

### What is the feature you are proposing to solve the problem?

Add some flags to the helm chart for creating read-only users for database/collections.

### What alternatives have you considered?

Some custom work at the container/database init.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Shashwatpathak05** [comment]
@jcpunk How did you resolve this requirement, I too have a similar requirement.

**Comment by jcpunk** [comment]
I've got a manual step to make the user. It is in no way automated :(
