### ISSUE TITLE
useAutoTLS results in crashing pod

### ISSUE THREAD

**Issue by tareqhs** [bitnami/charts#1743]
**Which chart**:

etcd @ master

**Description**

Setting `auth.client.secureTransport` and `auth.client.useAutoTLS` in chart values results in a pod that crashes during startup in the setup script. Console output from etcd-0 pod:
```
==> Bash debug is on
/scripts/setup.sh: line 21: ETCD_CERT_FILE: unbound variable
```
This is the section that fails
```sh
19: # Constants
20: HOSTNAME="$(hostname -s)"
21: AUTH_OPTIONS="--user root:$ETCD_ROOT_PASSWORD --cert="$ETCD_CERT_FILE" --22: key="$ETCD_KEY_FILE""
```
The environment is actually correct - `ETCD_AUTO_TLS` is set to true. Maybe in this case we should hard-code default locations for the cert files?

**Steps to reproduce the issue:**

In values.yaml set `auth.client.secureTransport` and `auth.client.useAutoTLS` to true.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Helm v2.16.1

- Output of `kubectl version`:

Kubernetes 1.15.7

**Comment by juan131** [comment]
Hi @tareqhs 

Thanks so much for reporting this issue!!! I created a PR to address this issue (despite it doesn't solve the error completely)

**Comment by juan131** [comment]
The auto-generated certificates aren't working for me to authenticate with etcd:
```
$ etcdctl $AUTH_OPTIONS member list
{"level":"warn","ts":"2019-12-18T15:09:34.752Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-b786d17d-58ef-4751-bee8-eb5838fd96d2/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 0.0.0.0, not 127.0.0.1\""}
Error: context deadline exceeded
```
