### ISSUE TITLE
[bitnami/elasticsearch] Not able to restore EBS volumes to existing pvc for Elasticsearch

### ISSUE THREAD

**Issue by saleem-unifycare** [bitnami/charts#17448]
### Name and Version

elasticsearch-19.10.2

### What is the problem this feature will solve?

I have installed elasticsearch with bitnami/elasticsearch charts on AWS EKS. PV's and PVC's are dynamically provisoned.
I have EBS volumes backed up with data in it as snapshots for data-elasticsearch-data-0,data-elasticsearch-data-1,data-elasticsearch-master-0,data-elasticsearch-master-1.
Now how can i pass my new volumes to helm command to use my new volumes as pv and then for pvc

Please guide me on this.

### What is the feature you are proposing to solve the problem?

NA

### What alternatives have you considered?

NA

**Comment by javsalgar** [comment]
Hi,

One option would be to create PVCs with the exact name as the statefulset expects to use. This way, it would not re-create the volumes.
