### ISSUE TITLE
[bitnami/kafka] Kafka Kraft Upgrade

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#17459]
### Name and Version

 [bitnami/kafka] Release 23.0.1

### What is the problem this feature will solve?

Hi All - I have installed Kafka Kraft mode with latest helm charts with Kafka version 3.5.0.
Initially I have installed Kafka with 3 pods, When I upgrade the cluster from 3 to 5 pods, Cluster is not forming.

Please find the Kafka Kraft mode cluster with 3 nodes.
![image](https://github.com/bitnami/charts/assets/96808632/c6be2837-8902-46f6-8a0b-3a6fb7361956)

After Upgrade from 3 pods to 5 pods, I am getting below error.

![image](https://github.com/bitnami/charts/assets/96808632/a89bfdaf-904c-4962-84e5-d3518cfff851)

![image](https://github.com/bitnami/charts/assets/96808632/21f3be57-dabd-40b2-a42c-c8384954fb36)

 

### What is the feature you are proposing to solve the problem?

When the cluster is added additional pods, the cluster should form. When the cluster is downgraded from 5 pods to 3 pods it should be formed.

**Comment by carrodher** [comment]
Thanks for reporting this issue. We detected some issues in Kafka when running in Kraft mode and we are working on a major refactor of the Kafka Helm chart, we will update this issue once released the new version

**Comment by bharathreddy901** [comment]
Thank you @carrodher for the update.

**Comment by fzyzcjy** [comment]
Looking forward to the fix!

**Comment by javsalgar** [comment]
This is the PR https://github.com/bitnami/charts/pull/17507
