### ISSUE TITLE
[bitnami/etcd] enable restoring from snapshot from object storage

### ISSUE THREAD

**Issue by derekperkins** [bitnami/charts#17457]
### Name and Version

bitnami/etcd 9.0.4

### What is the problem this feature will solve?

Restoring from a PVC is surprisingly difficult

### What is the feature you are proposing to solve the problem?

Enable downloading a snapshot file over http, so you can just upload the snapshot to S3/GCS

### What alternatives have you considered?

Manually using `kubectl cp` to copy the snapshot into the pod, but then no pods join the cluster after scaling / upgrading

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
