### ISSUE TITLE
[bitnami/postgresql-ha] Unable to have all metrics with postgresql-exporter

### ISSUE THREAD

**Issue by jgourmelen** [bitnami/charts#17470]
### Name and Version

bitnami/postgresql-ha 11.7.7

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. In a kubernetes environnement (EKS AWS 1.27)
4. postgres exporter is started before the postgresql container. A lot of metrics is not available. But when i start the process postgres-exporter inside the pod with a new port (same parameters), I can see all metrics.

### Are you using any custom parameters or values?

ServiceMonitor  enabled

### What do you see instead?

```bash
caller=main.go:86 level=warn msg="Error loading config" err="Error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"

caller=proc.go:250 msg="Excluded databases" databases=[]

caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="dial tcp 127.0.0.1:5432: connect: connection refused"

caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9187

caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9187

caller=server.go:74 level=info msg="Established new database connection" fingerprint=127.0.0.1:5432

caller=postgres_exporter.go:691 level=error err="Error opening connection to database 

(postgresql://myapp:PASSWORD_REMOVED@127.0.0.1:5432/myapp?sslmode=disable): dial tcp 127.0.0.1:5432: connect: connection refused"

caller=server.go:74 level=info msg="Established new database connection" fingerprint=127.0.0.1:5432

caller=postgres_exporter.go:622 level=info msg="Semantic version changed" server=127.0.0.1:5432 from=0.0.0 to=15.2.0
```

**Comment by FraPazGal** [comment]
Hello @jgourmelen,

Just to double-check and help us reproduce the issue, what metrics seem to be missing on the exporter? I run a kick test and checking the `IP:9187/metrics` endpoint returned the following:

```
$ curl 127.0.0.1:9187/metrics

# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 3.1562e-05
go_gc_duration_seconds{quantile="0.25"} 3.1562e-05
go_gc_duration_seconds{quantile="0.5"} 3.1562e-05
go_gc_duration_seconds{quantile="0.75"} 3.1562e-05
go_gc_duration_seconds{quantile="1"} 3.1562e-05
go_gc_duration_seconds_sum 3.1562e-05
go_gc_duration_seconds_count 1
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 8
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.20.5"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.455744e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 2.680912e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
```

```
$ curl 127.0.0.1:9187/metrics | wc -l
1054
```

**Comment by jgourmelen** [comment]
![image](https://github.com/bitnami/charts/assets/3177510/2c0f6005-eb9d-4319-9c6b-18b68218c996)

**Comment by jgourmelen** [comment]
I execute this command inside my container : postgres_exporter --web.listen-address=:9188

**Comment by jgourmelen** [comment]
![image](https://github.com/bitnami/charts/assets/3177510/db7eb73f-9cf6-4deb-9366-54093102b0ae)

**Comment by FraPazGal** [comment]
You were right @jgourmelen, the error was related to the error you shared. Looking in the upstream repo this error was [reported](https://github.com/prometheus-community/postgres_exporter/issues/850) but a fix hasn't been provided yet, though there is a PR open.

Once the fix is merged and a new release of the application is out, we'll automatically download it. After our CI/CD does its magic, we'll release a new chart version for `bitnami/postgresql-ha` containing the new exporter version. For now we'll mark this issue as `on-hold` and keep an eye on it, notifying you once the aforementioned process is completed.

Thanks for reporting this!
