### ISSUE TITLE
PR #17398 broke the PostgreSQL chart

### ISSUE THREAD

**Issue by psmolkin** [bitnami/charts#17472]
### Name and Version

bitnami/postgresql 12.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Plain vanila k8s
2. minimal configuration like:
  ```yml
  auth:
    postgresPassword: Hellow
  ``` 
3. helm install ...
4. get pod startup error:
![image](https://github.com/bitnami/charts/assets/24776038/dea9564f-1f67-4081-8439-d75f0c28242f)

### Are you using any custom parameters or values?

  ```yml
  auth:
    postgresPassword: Hellow
  ``` 

### What is the expected behavior?

Should just work ☺

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/24776038/6510904f-0b47-4fa2-bc4e-8afb7e29850a)

### Additional information

 12.6.0 works fine

**Comment by psmolkin** [comment]
@migruiz4 @Mauraza please note, the fix https://github.com/bitnami/charts/pull/17398 has broken the PgSQL chart

**Comment by gongomgra** [comment]
Hi @psmolkin,

Sorry for the inconveniences, it was my fault. (PR#17473) should cover your use case. It worked for me locally running the command below

```
$ helm install -n postgresql postgresql bitnami/postgresql --set auth.postgresPassword=bitnami123
```

**Comment by gongomgra** [comment]
Hi @psmolkin,

PostgreSQL 12.6.2 should fix your issue. It may take a bit to be released and available though.
