### ISSUE TITLE
[bitnami/clickhouse] login failed 

### ISSUE THREAD

**Issue by KevinLiangX** [bitnami/charts#17487]
### Name and Version

bitnami/22.8.19-debian-11-r5

### What architecture are you using?

None

### What steps will reproduce the bug?

hello sir

The previous version we used was version 23.4.2, which defined the user default and password, and added the user and password in remote_server.  It work
![image](https://github.com/bitnami/charts/assets/40968187/bcc8572b-66b4-4d0f-96c2-9aa16c80dc57)

![image](https://github.com/bitnami/charts/assets/40968187/23841910-4f6e-4b32-8577-758568161225)

But now I want to use the 22.8.19 version, because our server architecture version is low, should I use the chart file of 23.4.2? After deployment, the following error is displayed, what should I do?

![image](https://github.com/bitnami/charts/assets/40968187/08f93abc-da65-4119-a60c-ac2deb380915)

We created s3r2 and used distributed flow tags

### What do you see instead?

Na

**Comment by javsalgar** [comment]
Hi,

Just to confirm. You were using a newer version of the chart with the configuration shown above and it worked, but when using an older version this failed, right? It looks to me that it could be an upstream issue.

**Comment by KevinLiangX** [comment]
@javsalgar  cloud please help search 22.8.19-debian-11-r5 version chart file , i compare  the new chart with the  tag 8808b07,  There are some differences ,such as not setup.sh。 maybe it not work . i want to use the order version chart to try , however  can't find the old version chart file

**Comment by KevinLiangX** [comment]
@javsalgar  hello sir ,  processing ,  use the dbeaver  or other http tools can  connect the clickhouse with default and password ,   can't login by clickhouse-client,   do you have any idea?

**Comment by KevinLiangX** [comment]
@javsalgar  Hi  i closed this issue ,   login clickhouse with --password,  it works ,  or it show the error quickly . maybe this is the lower version issue of clickhouse
