### ISSUE TITLE
Why we don't have bitnami chart for nginx-php-fpm to run php application?

### ISSUE THREAD

**Issue by ninnube** [bitnami/charts#17483]
### Name and Version

bitnami/nginx-php-fpm

### What is the problem this feature will solve?

Dear,

I was looking for chart for building php apps on kubernetes platform, but couldn't find them.

Thank you.

### What is the feature you are proposing to solve the problem?

I'm looking forward to bitnami being able to build images for nginx-php-fpm  and chart to deploy on kubernetes.

Thanks

**Comment by carrodher** [comment]
Thanks for the suggestion, unfortunately, it is not something on our roadmap at this moment.
