### ISSUE TITLE
[bitnami/logstash] Can't create NodePort through logstash helm chart 

### ISSUE THREAD

**Issue by copy1dollar** [bitnami/charts#17482]
### Name and Version

bitnami/logstash 5.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Installing Logstash through Helm-Chart with `service.type=NodePort` 

### What do you see instead?

```
Error: UPGRADE FAILED: failed to create resource: Service "logstash-headless" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when type is 'ClusterIP'
```

### Additional information

duplicated issue : https://github.com/bitnami/charts/issues/15393 
but I don't know how reopen the issue.

and related : https://github.com/elastic/helm-charts/pull/839

**Comment by rafariossaa** [comment]
Hi,
  Thanks, #15393 was reopened yesterday after your comment.
  I am closing this issue, let's use the initial github issue to track this.
