### ISSUE TITLE
[bitnami/gitea]: Environment variables do not affect Gitea settings

### ISSUE THREAD

**Issue by kinger-de** [bitnami/charts#17499]
### Name and Version

bitnami/gitea:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to install the following HelmChart in a k3s environment (v1.25.5+k3s2):

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: gitea
  targetNamespace: gitea
  valuesContent: |-
    ...
    extraEnvVars:
      - name: GITEA_SMTP_ENABLED
        value: true
      - name: GITEA_service_REGISTER_EMAIL_CONFIRM
        value: true
      - name: GITEA_service_REGISTER_EMAIL_CONFIRM
        value: true
      - name: GITEA_service_DISABLE_REGISTRATION
        value: true
      - name: GITEA_service_ALLOW_ONLY_EXTERNAL_REGISTRATION
        value: true
      - name: GITEA_service_REQUIRE_SIGNIN_VIEW
        value: true
      - name: GITEA_service_DISABLE_REGISTRATION
        value: true
    ...
```

Unfortunately, the environment variables do not override the Gitea service settings. Only the environment variable 'GITEA_SMTP_ENABLED' works.

How can I configure the Gitea service via the HelmChart so that the settings are the same every time the container is started?

### What is the expected behavior?

I pass the HelmChart an extraEnvVars to control a setting of the application.

I have tried the following spellings without success:
- GITEA_DISABLE_REGISTRATION
- GITEA_SERVICE_DISABLE_REGISTRATION
- GITEA__SERVICE__DISABLE_REGISTRATION
- GITEA__service__DISABLE_REGISTRATION

### What do you see instead?

The default settings from the app.ini after the first start of the application.

**Comment by javsalgar** [comment]
Hi,

Could you share where you found these environment variables, I don't see them in the Bitnami Gitea container code.

**Comment by ZandercraftGames** [comment]
Apologies to resurrect this, but this is from https://docs.gitea.com/installation/install-with-docker-rootless/#managing-deployments-with-environment-variables. It seems that bitnami/gitea doesn't use environment variables configured this way? 
How could someone edit their gitea instance's app.ini options in another way as it seems that the helm chart does not account for a lot of options. Namely mailer.ENABLED, mailer.FROM, mailer.IS_TLS_ENABLED, server.LFS_START_SERVER, service.DISABLE_REGISTRATION, service.ENABLE_NOTIFY_MAIL and many others.

**Comment by ZandercraftGames** [comment]
Im pretty sure he got them from https://docs.gitea.com/next/installation/install-with-docker-rootless#managing-deployments-with-environment-variables. 
I do wonder how you would configure things like `START_LFS_SERVER` and other stuff though as it seems that the bitnami chart doesn't allow for this type of configuration.

**Comment by x45dev** [comment]
I have encountered the same problem. How do you configure other app.ini settings using this chart?

**Comment by x45dev** [comment]
Please reopen this issue. Without the ability to change settings via environment variables, this Helm chart implementation does not allow for reasonable customisation of the Gitea installation.

**Comment by ZandercraftGames** [comment]
> https://docs.gitea.com/administration/config-cheat-sheet?_highlight=disable_registration#service-service

These are not environment variables, but rather configurable items within the app.ini. They are categorized in the INI file and as such some terms overlap. Some of them may coincide with undocumented environment variables that Gitea checks for, but for the most part this level of granularity is exclusive to modification of the app.ini file.

Gitea provides a script that will take categorized environment variables configured in a certain format and put them into the app.ini file, however, without support for this in the bitnami package, most config items are not configurable by environment variable:
https://docs.gitea.com/next/installation/install-with-docker-rootless#managing-deployments-with-environment-variables

**Comment by x45dev** [comment]
> > https://docs.gitea.com/administration/config-cheat-sheet?_highlight=disable_registration#service-service
> 
> These are not environment variables, but rather configurable items within the app.ini. They are categorized in the INI file and as such some terms overlap. Some of them may coincide with undocumented environment variables that Gitea checks for, but for the most part this level of granularity is exclusive to modification of the app.ini file.
> 
> Gitea provides a script that will take categorized environment variables configured in a certain format and put them into the app.ini file, however, without support for this in the bitnami package, most config items are not configurable by environment variable: https://docs.gitea.com/next/installation/install-with-docker-rootless#managing-deployments-with-environment-variables
> 
> See also: https://github.com/go-gitea/gitea/tree/main/contrib/environment-to-ini

Thank you @ZandercraftGames. I agree - this is an accurate explanation of the problem. The OP's attempt at configuration is using that pattern - as implemented in the Gitea Helm chart, which uses the Gitea script configuration conversion script.

In short, Gitea takes the majority of its config from `app.ini`, so this Bitnami chart requires some means of dynamically updating it during pod startup. As I see it, the options that exist are either:
-  Replicate the Gitea helm chart pattern using a script to convert environment variables into app.ini settings; or
- Allow users to provide a supplementary `app.ini` (presumably as a ConfigMap) that is dynamically incorporated into the existing `app.ini` by an InitContainer. I am currently using this pattern with the Bitnami Helm chart using the below script:
```
#!/usr/bin/env python3
"""
merge_config.py

Usage:
    import os
    import sys

    # Insert script parent directory into PYTHONPATH to allow module import. 
    # Equivalent of `export PYTHONPATH="${PYTHONPATH}:$(pwd)"`.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, script_dir)

    from merge_config import merge_config

    filepath_primary = "app.ini"
    filepath_supplementary = "supplementary-app.ini"
    filepath_output = "merged-app.ini"
    merge_config(filepath_primary, filepath_supplementary, filepath_output)

Updated: 2023-12-05
"""

import configparser
import io


def merge_config(
    filepath_primary: str, filepath_supplementary: str, filepath_output: str
    ) -> None:
    """
    Merge two INI files while preserving the original case of keys.

    This function reads two INI files into ConfigParser objects. It updates the primary ConfigParser object
    with headers and values from the supplementary ConfigParser. If the primary config does not have a
    section present in the supplementary one, it's added. If a key exists in both, the value from the
    supplementary ConfigParser is used. The updated primary ConfigParser is then written to an output file.

    Args:
        filepath_primary (str): The path to the primary (original) INI file.
        filepath_supplementary (str): The path to the supplementary INI file.
        filepath_output (str): The path to output the merged INI file.

    Raises:
        configparser.MissingSectionHeaderError: Exception if the INI files are missing section headers. In this
        case, a temporary section header is added so that the config can be parsed correctly.
    """
    parsers = (
        configparser.ConfigParser(),
        configparser.ConfigParser(),
    )  # parsers[0]=primary parsers[1]=supplementary

    for parser, filepath in zip(parsers, (filepath_primary, filepath_supplementary)):
        # Override the optionxform property to ensure that keys remain capitalised.
        parser.optionxform = str

        # Read the files into the parser objects
        try:
            parser.read(filepath)
        except configparser.MissingSectionHeaderError:
            # ConfigParser requires section headers; so add a temporary one.
            with open(filepath, mode="r", encoding="UTF-8") as fh:
                config_str = fh.read()
            config_str = (
                f"[X-DEFAULT]\n{config_str}"  # X-DEFAULT is an arbitrary header name.
            )
            parser.read_string(config_str)

    # Update original file with supplementary headers/values.
    # If a key exists, replace value with supplementary one; else append.
    for section in parsers[1].sections():
        if not parsers[0].has_section(section):
            parsers[0].add_section(section)

        for key in parsers[1][section]:
            parsers[0][section][key] = parsers[1][section][key]

    # Write the output
    with open(filepath_output, mode="w", encoding="UTF-8") as fh:
        buf = io.StringIO()
        parsers[0].write(buf)
        output_str = buf.getvalue()

        # If a default section header was added, remove it.
        if output_str.startswith("[X-DEFAULT]"):
            lines = output_str.split("\n")
            output_str = "\n".join(lines[1:])  # Remove the first line.

        fh.write(output_str)


if __name__ == "__main__":
    filepath_primary = "app.ini"
    filepath_supplementary = "supplementary-app.ini"
    filepath_output = "merged-app.ini"

    # Call the function to merge the two INI files
    merge_config(filepath_primary, filepath_supplementary, filepath_output)

```

**Comment by Mauraza** [comment]
We are open to contributions in containers and charts, so please feel free to create a PR with your solutions.

**Comment by roadroot** [comment]
Hello,

Facing the same limitation.
Please open this issue.

**Comment by roadroot** [comment]
Hello, actually I found a solution, here is the `values.yaml` :

```yaml
gitea:
  config:
    server:
      ROOT_URL: <path:path_to_root_url | base64decode>
      DISABLE_REGISTRATION: "true"
```
