### ISSUE TITLE
[bitnami/thanos] Add support to template dnsPolicy

### ISSUE THREAD

**Issue by davidcarrera** [bitnami/charts#17517]
### Name and Version

bitnami/thanos 12.8.3

### What is the problem this feature will solve?

Thanos chart allows templating the value of dnsConfig in the deployment object, but does not allow to template the dnsPolicy field. If you need to set a specific DNS server to be used by thanos pods (useful when you use a SD based on DNS) you need to combine a dnsConfig that points to the DNS to be used + setting dnsPolicy to "None". Other charts like keycloak, redis, nginx-ingress, or rabbitmq already allow this. 

Reference of code where dnsConfig is used:
https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/query/deployment.yaml#L64

Some more info about dnsPolicy.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

### What is the feature you are proposing to solve the problem?

Add support for templating the dnsConfig field, following the same approach used in other charts.

Example in rabbitmq:
https://github.com/bitnami/charts/blob/f559fa746836bf63e86ae1fe5ddbca4d72d14b68/bitnami/rabbitmq/templates/statefulset.yaml#L88

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
