### ISSUE TITLE
[bitnami/elasticsearch] add ServiceAccount

### ISSUE THREAD

**Issue by Jay-Funk** [bitnami/charts#1752]
I have a feature request regarding the option to enable a _ServiceAccount_ for 
- _Coordinating-only_ Deployment
- _Data_ and _Master_ StatefulSet
respectively, analogously to what was proposed and implemented for the elastic/elasticsearch Helm chart (https://github.com/elastic/helm-charts/issues/61).

This is needed in order to ensure fine-granular control over the communication inside a namespace (eg via AuthorizationPolicy in istio).

**Comment by juan131** [comment]
Hi @Jay-Funk 

It would be great to add this feature to the chart. Thanks for the suggestion

Do you want to contribute by submitting a PR or would your rather us to implement it?

**Comment by Jay-Funk** [comment]
Hi @juan131 
I would be glad to contribute!
Looking at the current structure I can see that there already is a ServiceAccount for the curator.
Does it make sense to reuse it for coordinating-only, master and data or should I create a seperate ServiceAccount for them?

**Comment by sameersbn** [comment]
@Jay-Funk Thanks for the interest in contributing to improve the chart. I would suggest creating a separate service account for them
