### ISSUE TITLE
[bitnami/keycloak] What is the username and password for Keycloak

### ISSUE THREAD

**Issue by topeawolwo** [bitnami/charts#17522]
### Name and Version

bitnami/keycloak

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I am running keycloak on Kubernetes using this Helm chart from Bitnami : https://github.com/bitnami/charts/tree/main/bitnami/keycloak/#installing-the-chart

The pods and services are running 

```

kubectl get service -n default                                                                                                                     
NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
oxygen-test-keycloak             ClusterIP      10.99.9.6        <none>        8095/TCP         29h
oxygen-test-keycloak-headless    ClusterIP      None             <none>        80/TCP           29h
oxygen-test-postgresql           ClusterIP      10.108.66.109    <none>        5432/TCP         29h

➜  ~ 


 ~ kubectl get pod -n default 
NAME                                     READY   STATUS                   RESTARTS         AGE
go-grpc-greeter-server-947f6b446-rph99   1/1     Running                  14 (2d20h ago)   47d
oxygen-test-keycloak-0                   1/1     Running                  2 (91m ago)      29h
oxygen-test-postgresql-0                 1/1     Running                  0                29h


and I am exposing the service to the browser

    export HTTP_SERVICE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[?(@.name=='http')].port}" services oxygen-test-keycloak )
    

    kubectl port-forward --namespace default svc/oxygen-test-keycloak  ${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT} & echo "http://127.0.0.1:${HTTP_SERVICE_PORT}/"

```

I just cant get the correct the username and password....

### Are you using any custom parameters or values?

none

### What is the expected behavior?

login into the user interface

### What do you see instead?

<img width="752" alt="image" src="https://github.com/bitnami/charts/assets/31287837/27b65a86-e133-47ec-80b6-c98dc2793177">

**Comment by pkerwien** [comment]
If you are using bitnami/keycloak chart 15.1.6, the default admin username is: user (See auth.adminUser in the chart values). And the generated password can be extracted by running the command:

`kubectl -n <namespace> get secret keycloak -o jsonpath='{.data.admin-password}' | base64 -d && echo`

I hope this helps.

**Comment by smartlocus** [comment]
@topeawolwo  hey how did you get the credentials ? i am also stuck in the same issue. 
![image](https://github.com/bitnami/charts/assets/114703928/9743ef66-7af5-469d-b40e-741b6ad8dfd1)

i fetched the generated secret and uses the password and it is still not working

**Comment by thanhtai9606** [comment]
> @topeawolwo hey how did you get the credentials ? i am also stuck in the same issue. ![image](https://user-images.githubusercontent.com/114703928/263434143-9743ef66-7af5-469d-b40e-741b6ad8dfd1.png)
> 
> i fetched the generated secret and uses the password and it is still not working

I think you should check your username first. Or check username/pwd in your values.yml file

**Comment by stephenbjm** [comment]
The namespace (see parameter "-n") should be "keycloak" and not "default" as shown above.
So, the correct command to get the password is:
 kubectl -n keycloak get secret keycloak -o jsonpath='{.data.admin-password}' | base64 -d && echo

**Comment by h4tt3n** [comment]
I am experiencing the same issue. I have installed bitnami keycloak on an azure kubernetes cluster. 

I have extracted and decoded the autogenerated value with:

kubectl -n keycloak get secret keycloak -o jsonpath='{.data.admin-password}'
$([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("paste-encoded-secret-here")))

I keep getting this:
![image](https://github.com/bitnami/charts/assets/76813355/98b21ac6-c971-48f3-bec9-b0496581bf00)

Here is the relevant section from the values.yam file:

auth:
  ## @param auth.adminUser Keycloak administrator user
  ##
  adminUser: user
  ## @param auth.adminPassword Keycloak administrator password for the new user
  ##
  adminPassword: ""
  ## @param auth.existingSecret Existing secret containing Keycloak admin password
  ##
  existingSecret: ""
  ## @param auth.passwordSecretKey Key where the Keycloak admin password is being stored inside the existing secret.
  ##
  passwordSecretKey: ""
  ## @param auth.annotations Additional custom annotations for Keycloak auth secret object
  ##
  annotations: {}

**Comment by stephenbjm** [comment]
Hi there
Can you try extracting the password with this command:

kubectl -n keycloak get secret keycloak -o
jsonpath='{.data.admin-password}'  | base64 --decode

Then paste the resulting string into the Keycloak password field.
Best wishes
Stephen

**Comment by h4tt3n** [comment]
@stephenbjm 

Hi, I resolved the issue. It related to [this issue](https://github.com/bitnami/containers/issues/36886#issuecomment-1583325744). 
Changing the auth.adminUser and auth.adminPassword in the values file does not prompt an update of the values in an external DB. Solution was to delete and recreate the external db. This worked for me because it was empty, but might not work for others.

Is there a way around this issue?

For reference I have installed bitnami keycolak in an azure kubernetes service, and the external db is a postgresql db running in an Azure Azure Database for PostgreSQL flexible server.

Cheers, Mike

**Comment by stephenbjm** [comment]
Hi Mike
I experienced this issue if I re-installed the Bitnami Helm chart. The
secrets aren't overwritten, which I think is a common issue with Helm.
So, on a fresh install it should work, but an upgrade use case may see this
password problem.
Best wishes
Stephen
