### ISSUE TITLE
Configured ArgoCD OIDC with Keycloak not working 

### ISSUE THREAD

**Issue by topeawolwo** [bitnami/charts#17549]
### Name and Version

keycloak-15.1.6, keycloak- App version is : 21.1.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```console
$ kubectl get pod
NAME READY STATUS RESTARTS AGE
guestbook-ui-b848d5d9d-vs4qv 1/1 Running 0 7h6m
oxygen-repo-argocd-application-controller-0 1/1 Running 0 8h
oxygen-repo-argocd-applicationset-controller-6d4c9f54bd-l6kkd 1/1 Running 0 8h
oxygen-repo-argocd-dex-server-69cdb99d9b-jtz6l 1/1 Running 0 8h
oxygen-repo-argocd-notifications-controller-bdf75f5-cf6r6 1/1 Running 0 8h
oxygen-repo-argocd-redis-6dc54656bc-pgj7c 1/1 Running 0 8h
oxygen-repo-argocd-repo-server-768cbdcbc7-znfw5 1/1 Running 0 8h
oxygen-repo-argocd-server-5b966995c5-wp66p 1/1 Running 0 8h
oxygena-test-keycloak-0 1/1 Running 0 9h
oxygena-test-postgresql-0 1/1 Running 0 9h

$ kubectl get service
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
guestbook-ui ClusterIP 10.97.167.251 80/TCP 7h7m
kubernetes ClusterIP 10.96.0.1 443/TCP 2d13h
oxygen-repo-argocd-applicationset-controller ClusterIP 10.104.9.232 7000/TCP 8h
oxygen-repo-argocd-dex-server ClusterIP 10.101.255.46 5556/TCP,5557/TCP 8h
oxygen-repo-argocd-redis ClusterIP 10.102.33.22 6379/TCP 8h
oxygen-repo-argocd-repo-server ClusterIP 10.105.29.143 8081/TCP 8h
oxygen-repo-argocd-server ClusterIP 10.111.179.203 80/TCP,443/TCP 8h
oxygena-test-keycloak ClusterIP 10.96.59.25 8085/TCP 9h
oxygena-test-keycloak-headless ClusterIP None 80/TCP 9h
oxygena-test-postgresql ClusterIP 10.102.114.18 5432/TCP 9h
oxygena-test-postgresql-hl ClusterIP None 5432/TCP 9h
```
Anything else?

### What is the expected behavior?

on clicking the Argopcd login page on https://localhost:8080/ on the "Log in via keycloak button" I am supposed to be login into the ArgoCD

### What do you see instead?
```
Failed to query provider "http://localhost:8085/admin/master/": Get "http://localhost:8085/admin/master/.well-known/openid-configuration": dial tcp 127.0.0.1:8085: connect: connection refused
```

### Additional information

I have both ArgoCD and Keycloak installed in Kubernetes

Keycloak is running on http://127.0.0.1:8085/

Argopcd is running on https://localhost:8080/

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Keycloak container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
