### ISSUE TITLE
[bitnami/postgresql-ha] postgresql.extendedConf does not work as intended

### ISSUE THREAD

**Issue by baumgartnerniels** [bitnami/charts#1755]
**Which chart**: postgresql-ha:1.1.0

**Description**

Setting PostgreSQL configuration options via postgresql.extendedConf in Values does not create a ConfigMap and the postgresql pod fails to start.

**Steps to reproduce the issue:**

1. set the following values.yml:
```
---
postgresql:
  extendedConf:
    synchronous_commit: on
```
2. deploy the postgresql-ha chart
3. watch the postgresql pod fail

**Describe the results you received:**

No extendedconf configmap:
```
$ kubectl get configmaps
NAME                          DATA   AGE
values-postgresql-ha-ha-yml   1      118m
```

failing containers:
```
$ kubectl describe pods

...

  Warning  FailedMount             88s (x4 over 8m16s)  kubelet, 698e8dc5-cfdb-4b1b-9acc-c7f3a71346f3  Unable to mount volumes for pod "postgresql-ha-ha-d-d-postgresql-0_postgresql-ha-ha-d-ns(4103e56f-226a-11ea-8a2b-00505686358a)": timeout expired waiting for volumes to attach or mount for pod "postgresql-ha-ha-d-ns"/"postgresql-ha-ha-d-d-postgresql-0". list of unmounted volumes=[postgresql-extended-config]. list of unattached volumes=[data postgresql-extended-config default-token-vxqw5]

  Warning  FailedMount             3s (x13 over 10m)    kubelet, 698e8dc5-cfdb-4b1b-9acc-c7f3a71346f3  MountVolume.SetUp failed for volume "postgresql-extended-config" : configmap "postgresql-ha-ha-d-d-postgresql-extended-configuration" not found
```

**Describe the results you expected:**

The ConfigMap from templates/postgresql/extended-configmap.yaml should be created containing only the generated override.conf file.

**Additional information you deem important (e.g. issue happens only occasionally):**

The logic in templates/postgresql/extended-configmap.yaml on line 1 seems to be wrong.
instead of:
```
{{- if and (.Files.Glob "files/conf.d/*.conf") .Values.postgresql.extendedConf (not .Values.postgresql.extendedConfCM) }}
```
It should probably be something like:
```
{{- if and (or (.Files.Glob "files/conf.d/*.conf") .Values.postgresql.extendedConf) (not .Values.postgresql.extendedConfCM) }}
```

The existence (or inextistence) of additional .conf files in files/conf.d should not have an impact on postgresql.extendedConf.

**Comment by alemorcuq** [comment]
Hi, @baumgartnerniels.

Thanks for spotting this. I will send a PR fixing it.
