### ISSUE TITLE
extendedConf:  enable issue 

### ISSUE THREAD

**Issue by abhilashbs1981** [bitnami/charts#17555]
### Name and Version

bitnami/postgresql-ha 11.7.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Enable `extendedConf:` in values.yaml 

example as below
```yaml
  extendedConf: |-
    logging_collector = on
    log_destination = csvlog
    log_directory = '/var/log/postgresql'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_connections = on
    log_disconnections = on
    log_duration = on
    log_hostname = on
    log_line_prefix = '%t [%p]: [%l-1] system=postgres-k8s-%h-%c user=%u,db=%d,app=%a,client=%h '
    log_line_prefix = '%t %u %d %h'
    log_statement = 'ddl'
    log_rotation_age = 7d
    log_rotation_size = 10MB
    log_error_verbosity = verbose
    log_min_messages = WARNING
    log_lock_waits = on
```

now install helm chart by input modified values.yaml 
The pod will go to crashloop and logs are as below 
```console
$ k logs -f post-postgresql-ha-postgresql-0
postgresql-repmgr 10:01:30.21 
postgresql-repmgr 10:01:30.21 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 10:01:30.21 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 10:01:30.22 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-repmgr 10:01:30.22 
postgresql-repmgr 10:01:30.23 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 10:01:30.26 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 10:01:30.27 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 10:01:30.27 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 10:01:30.29 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 10:01:30.30 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 10:01:30.30 INFO  ==> postgresql.conf file not detected. Generating it...
**cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied**
```
if we disable the `extendedConf:`, it comes up fine . 

### Are you using any custom parameters or values?

Enable extendedConf: in values.yaml 

example as below
```yaml
  extendedConf: |-
    logging_collector = on
    log_destination = csvlog
```
### What is the expected behavior?

pod should run even after we enable the = extendedConf: in values.yaml 

example as below
```yaml
  extendedConf: |-
    logging_collector = on
    log_destination = csvlog
```

**Comment by abhilashbs1981** [comment]
Seems similar issue as https://github.com/bitnami/charts/issues/1961

**Comment by carrodher** [comment]
The extended PostgreSQL configuration (appended to main or default configuration) requires `volumePermissions.enabled`, could you try configuring this init container? See https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha#volume-permissions-parameters

**Comment by abhilashbs1981** [comment]
That Worked for the issue . But it took to a different error for the logs folder as below 

postgresql-repmgr 06:59:53.37 
postgresql-repmgr 06:59:53.37 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 06:59:53.38 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 06:59:53.38 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-repmgr 06:59:53.38 
postgresql-repmgr 06:59:53.40 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 06:59:53.43 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 06:59:53.43 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 06:59:53.44 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 06:59:53.46 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 06:59:53.47 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 06:59:53.47 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 06:59:53.58 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 06:59:53.59 INFO  ==> Initializing Repmgr...
postgresql-repmgr 06:59:53.60 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 06:59:53.61 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 06:59:53.61 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 06:59:53.64 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 06:59:53.68 INFO  ==> Configuring replication parameters
postgresql-repmgr 06:59:53.72 INFO  ==> Configuring fsync
postgresql-repmgr 06:59:53.73 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 06:59:53.77 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2023-07-12 06:59:53 GMT   LOG:  00000: pgaudit extension initialized
2023-07-12 06:59:53 GMT   LOCATION:  _PG_init, pgaudit.c:2202
**2023-07-12 06:59:53 GMT   FATAL:  58P01: could not open log file "/var/log/postgresql/postgresql-2023-07-12_065953.log": No such file or directory**
2023-07-12 06:59:53 GMT   LOCATION:  logfile_open, syslogger.c:1223
2023-07-12 06:59:53 GMT   LOG:  00000: database system is shut down
2023-07-12 06:59:53 GMT   LOCATION:  UnlinkLockFiles, miscinit.c:962
 stopped waiting
pg_ctl: could not start server
Examine the log output.

**Comment by abhilashbs1981** [comment]
have remove below and it start creating logs in default path 

    log_destination = csvlog
    log_directory = '/var/log/postgresql'
