### ISSUE TITLE
[bitnami/harbor] Wrong redis address in configmap of registry when using sentinel

### ISSUE THREAD

**Issue by adberger** [bitnami/charts#17704]
### Name and Version

bitnami/harbor 16.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When having redis in a replication setup (sentinel), the address which gets written to the configmap of the registry component has the default port of redis at the end.

Error in logs of registry container:
`redis: error connecting: dial tcp: address release-name-redis-headless:26379/mymaster:6379: too many colons in address`

### Are you using any custom parameters or values?

```
redis:
  enabled: true
  architecture: replication
  sentinel:
    enabled: true
```

### What is the expected behavior?

addr: "release-name-redis-headless:26379/mymaster"

### What do you see instead?

addr: "release-name-redis-headless:26379/mymaster:6379"

### Additional information

":" and port of redis should only be templated when sentinel is disabled.
Currently it's always templated:
`addr: "{{ template "harbor.redis.host" . }}:{{ template "harbor.redis.port" . }}"`

**Comment by andresbono** [comment]
Thank you for reporting this issue. Do you think it makes sense to create a helper function that takes into account if sentinel is used? This Helm chart already has several helpers doing something similar: [`redisFor*` helpers](https://github.com/search?q=repo%3Abitnami%2Fcharts+redisFor+path%3Abitnami%2Fharbor%2Ftemplates%2F_helpers.tpl&type=code). For example:

https://github.com/bitnami/charts/blob/8ad039e36f0a8e37ee43c46a10ff2a67a9afa765/bitnami/harbor/templates/_helpers.tpl#L255-L256

Would you like to contribute with a PR fixing this issue? Thanks!!

**Comment by andresbono** [comment]
Thank you so much for your contribution! When I first looked at this issue, I thought a new helper function would be suitable to fix it, but I might be missing some details. The PR will be reviewed soon.
