### ISSUE TITLE
moodle: Error with ClusterIP Service

### ISSUE THREAD

**Issue by AntoineFr** [bitnami/charts#17724]
### Name and Version

bitnami/moodle 16.1.5

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Use a ClusterIP service within the Moodle chart

### Are you using any custom parameters or values?
```yaml
    service:
      type: ClusterIP
```

### What do you see instead?

```
error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 23: mapping key "targetPort" already defined at line 21
```

### Additional information

When using a ClusterIP Service, the targetPort is defined twice on lines 45 and 50 :  

https://github.com/bitnami/charts/blob/b932dcfa6f1057207371b03d39a079319573391b/bitnami/moodle/templates/svc.yaml#L43-L51

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by AntoineFr** [comment]
I think reverting this PR would fix the issue : https://github.com/bitnami/charts/pull/16744

However I don't understand the problem that was fixed in this PR so it may reintroduce the bug it was meant to fix.
