### ISSUE TITLE
[bitnami/prometheus] Prometheus helm Installation unclosed action

### ISSUE THREAD

**Issue by inhyeokJeon** [bitnami/charts#17768]
### Name and Version

bitnami/prometheus 0.1.7

### What architecture are you using?

None

### What steps will reproduce the bug?

1. env
```
kubernetes: 1.19.10
helm: 3.5.3
```
2. run
```
helm install prometheus prometheus --set server.persistentVolume.storageClass=nfs-client --set server.service.type=NodePort --set alertmanager.enabled=false
```
3. result
```
Error: parse error at (prometheus/templates/tls-secret.yaml:6): unclosed action
```
### Are you using any custom parameters or values?
```
--set server.persistentVolume.storageClass=nfs-client --set server.service.type=NodePort --set alertmanager.enabled=false
```
### What is the expected behavior?

successful installation

### What do you see instead?
```
Error: parse error at (prometheus/templates/tls-secret.yaml:6): unclosed action
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
