### ISSUE TITLE
[bitnami/matomo] How to specify CA file for external mySql connection?

### ISSUE THREAD

**Issue by MichaelSL** [bitnami/charts#17766]
### Name and Version

bitnami/matomo 1.1.8

### What is the problem this feature will solve?

I'm trying to migrate my Matomo installation to k8s and use this Helm chart. While I was able to specify external database in `values.yaml`, it doesn't have a variable for mySql CA cert file. So Matomo can't connect to the db.

Here is the log:

`[18-Jul-2023 23:46:59 UTC] [45.79.63.202] Error in Matomo: Could not connect to the database: Connections using insecure transport are prohibited while --require_secure_transport=ON. This may be a temporary issue, try refreshing the page. Please contact your Matomo administrator if the problem persists.`

Matomo documentation lists following values for `config.ini.php`:

```
; Database SSL Options START
; Turn on or off SSL connection to database, possible values for enable_ssl: 1 or 0
enable_ssl = 1
; Direct path to server CA file, CA bundle supported (required for ssl connection)
ssl_ca = "/etc/mysql-certs/rds-combined-ca-bundle.pem"
; Direct path to client cert file (optional)
ssl_cert =
; Direct path to client key file (optional)
ssl_key =
; Direct path to CA cert files directory (optional)
ssl_ca_path =
; List of one or more ciphers for SSL encryption, in OpenSSL format (optional)
ssl_cipher =
; Database SSL Options END
```

### What is the feature you are proposing to solve the problem?

I propose to add a variable where base64 encoded cert can be inserted and then stored in the pvc and used for database connection.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
