### ISSUE TITLE
[bitnami/sonarqube] - Allow both extra properties as secret and as extraProperties

### ISSUE THREAD

**Issue by asafbentov** [bitnami/charts#17772]
### Name and Version

bitnami/sonarqube 3.2.5

### What is the problem this feature will solve?

I have few Sonar properties which aren't supposed to be as secrets which I want to configure through the values parameter "extraProperties" or "extraEnvVarsCM" for example:
sonar.core.serverBaseURL
And some properties which must be secret for example:
sonar.auth.oidc.clientSecret.secured

At the current state if I:
- create a secret with the secret properties at a key called SONAR_EXTRA_PROPERTIES 
- configure "extraEnvVarsSecret" to use that secret
- configure "extraProperties" with the non-secret properties
What will happen is: 
The only properties that will be writen to sonar.properties file will be the ones from "extraProperties" parameter.

And, if I use the "extraEnvVarsCM" and create a configmap with a key called SONAR_EXTRA_PROPERTIES instead of the "extraProperties" the only properties that will be written to sonar.properties are the ones from "extraEnvVarsSecret"

In the current state there is no option to add extra secret properties and extra non-secret properties at the same time.

### What is the feature you are proposing to solve the problem?

Two options that I thought about (they might not be the best solutions):
  - At the deployment template, might need to make it load extraEnvVarsSecret in a different way.
    If it contains a key called SONARQUBE_EXTRA_PROPERTIES, load it using a join to the already loaded 
    SONARQUBE_EXTRA_PROPERTIES
 - Might need to add to the sonarqube container image a new property for secret extra properties and make it load correctly at the sonar-env.sh script

### What alternatives have you considered?

I tried switching between using extraEnvVarsCM, extraEnvVarsSecret and extraProperties and all of them were overiding each over

**Comment by dgomezleon** [comment]
Hi @asafbentov ,

This is a particular scenario. An environment variable different from SONARQUBE_EXTRA_PROPERTIES should be added to the container logic. I think a good option there is to add all the parameters as extraEnvVarsSecret.

**Comment by asafbentov** [comment]
Hi @dgomezleon,
Thank you for the quick answer

In my scenario, I can't add all the parameters as extraEnvVarsSecret.
I am deploying many Sonarqube instances using Argocd, The Argocd's AppllicationSet gets the values file and the parameter
sonar.core.serverBaseURL needs to be different in each instance which I can't achieve by only using extraEnvVarsSecret.
If you think adding a new environment variable to the container logic is a possible idea then I would like to know if I need to open a new issue for that.
Another idea that came up to my mind is adding an option in the chart to set the sonar.core.serverBaseURL in the values file (if you think it is possible). But, that solution is very specific and I don't know how much this parameter is being used by other Sonarqube admins

**Comment by dgomezleon** [comment]
Hello @asafbentov ,

For both options, it would be necessary to adapt the container logic, and then update the chart if needed. Feel free to open a new issue in [containers repo](https://github.com/bitnami/containers). Explain there all the details for your use case in order to show why it is needed. You could also contribute with a PR if you consider :)
