### ISSUE TITLE
thanos image missing arm64 build

### ISSUE THREAD

**Issue by mateuszdrab** [bitnami/charts#17776]
### Name and Version

bitnami/thanos

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Latest image with tag: `0.31.0-scratch-r10` is missing an arm64 build
Last image with arm64 is tag: `0.31.0-scratch-r9`

### What do you see instead?

CrashLoopBackOff due to latest helm chart referencing the r10 image

**Comment by carrodher** [comment]
Thanks for reporting this issue, it certainly is a bug on our side due to some changes we are doing in our internal test & release pipeline. We are applying some remediations and the issue should be fixed sooner rather than later.

We will keep this thread updated once there is more news.

**Comment by carrodher** [comment]
Hi @mateuszdrab, the issue should be solved and new revisions are multiarch again, see https://hub.docker.com/layers/bitnami/thanos/0.31.0-scratch-r11/images/sha256-c33e2a8cfd83dc754330195371cf625588e873f7ea58d559bd5885de42666a49?context=explore.

When a new release of the Helm chart appears, the bundled images will be updated to the latest revisions with the issue solved. In the meantime, you can override the tag by using `--set image.tag=0.31.0-scratch-r11`.

Thanks for reporting the issue!

**Comment by mateuszdrab** [comment]
Thank you for handling it swiftly @carrodher
