### ISSUE TITLE
[bitnami/clickhouse] user sync doesn't work

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#17781]
### Name and Version

bitnami/clickhouse

### What architecture are you using?

None

### What steps will reproduce the bug?

This is my values.yaml 

after helm install I created user: user1 and database: db1. Granted full access to user1 and db1

When I try to select * from db1.table I get the following error:

### Are you using any custom parameters or values?

```yaml
image:
  tag: 23.6.2-debian-11-r0
ingress:
  enabled: true
  hostname: clickhouse.local
  pathType: Prefix
persistence:
  size: 1000Gi
extraOverrides: |
  <clickhouse>
    <users>
      <default>
        <access_management>1</access_management>
      </default>
    </users>
    <macros>
      <cluster>default</cluster>
    </macros>
  </clickhouse>
```

### What is the expected behavior?

I should get some data back

### What do you see instead?
```
DB::Exception: Received from clickhouse-shard1-0.clickhouse-headless.clickhouse.svc.cluster.local:9000. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.
```

**Comment by javsalgar** [comment]
Hi!

Could detail the steps you followed to create the user and the table?

**Comment by oktayalizada** [comment]
Database creation:

`CREATE DATABASE `db1` ON CLUSTER '{cluster}';`

User creation:

`CREATE USER  user1 ON CLUSTER '{cluster}' IDENTIFIED BY '???';`

GRANT

`GRANT ON CLUSTER '{cluster}' ALL ON db1.* TO user1;`

Table:

CREATE TABLE `db1`.`local_table1` ON CLUSTER '{cluster}'
(
    `id` UInt16,
    `id2` UInt32,
    `type_id` UInt16,
    `number` UInt32,
    `date` DateTime NULL,
    `text` String,
    `updated` DateTime64(3) DEFAULT now64(3)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
PARTITION BY toYYYYMM(updated)
ORDER BY (id, id2, type_id, number);

CREATE TABLE `db1`.`table1` ON CLUSTER '{cluster}' AS `db1`.`local_table1`
ENGINE = Distributed('{cluster}', log, local_event, murmurHash3_32(id, id2, type_id, number));

**Comment by oktayalizada** [comment]
Hi,
I have found a workaround. I knew that I will have 3 shards and 3 replicas so I changed extraOverrides to this:

```
  <clickhouse>
    <users>
      <default>
        <access_management>1</access_management>
      </default>
    </users>
    <macros>
      <cluster>default</cluster>
    </macros>
    <remote_servers>
      <default>
        <shard>
            <replica>
                <host>clickhouse-shard0-0.clickhouse-headless.clickhouse.svc.cluster.local</host>
                <port>9000</port>
                <user>default</user>
                <password>_my_password_</password>
            </replica>
            <replica>
                <host>clickhouse-shard0-1.clickhouse-headless.clickhouse.svc.cluster.local</host>
                <port>9000</port>
                <user>default</user>
                <password>_my_password_</password>
            </replica>
            <replica>
                <host>clickhouse-shard0-2.clickhouse-headless.clickhouse.svc.cluster.local</host>
                <port>9000</port>
                <user>default</user>
                <password>_my_password_</password>
            </replica>
        </shard>
        <shard>
            <replica>
                <host>clickhouse-shard1-0.clickhouse-headless.clickhouse.svc.cluster.local</host>
                <port>9000</port>
                <user>default</user>
                <password>_my_password_</password>
            </replica>
            <replica>
                <host>clickhouse-shard1-1.clickhouse-headless.clickhouse.svc.cluster.local</host>
                <port>9000</port>
                <user>default</user>
                <password>_my_password_</password>
            </replica>
            <replica>
                <host>clickhouse-shard1-2.clickhouse-headless.clickhouse.svc.cluster.local</host>
                <port>9000</port>
                <user>default</user>
                <password>_my_password_</password>
            </replica>
        </shard>
      </default>
    </remote_servers>
  </clickhouse>
```

But this will not work if I change replicaCount.

**Comment by oktayalizada** [comment]
HI @dgomezleon, 
I haven't tried it yet and I think I will not be able to try it for some time so I will close the issue. Thank you for the help
