### ISSUE TITLE
docs: links to https://kubernetes.io/docs/user-guide/...  end in 404 error

### ISSUE THREAD

**Issue by bcdady** [bitnami/charts#17782]
### Name and Version

bitnami/all

### What architecture are you using?

None

### What steps will reproduce the bug?

View a YAML files that includes a hyperlink, similar to the following:
```YAML
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
```

### What is the expected behavior?

Following a link loads the intended/expected content from kubernetes.io

### What do you see instead?

HTTP 404 error message from https://kubernetes.io/docs/ site

### Additional information

I intend to submit an MR to replace all ref links that include a link like `ref: https://kubernetes.io/docs/user-guide/` with a current/functional link

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
