### ISSUE TITLE
unable upload file size more than 1mb to solr using zookeeper after increasing max buffer size in solr helm chart

### ISSUE THREAD

**Issue by shubhranshu007** [bitnami/charts#17789]
### Name and Version

bitnami/solr:9.2.1-debian-11-r24

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. edited value.yml file for zookeeper and set max buffer size to 31457280 under zookeeper --> extraEnvvars
2. helm upgrade.
3. restart pods

### Are you using any custom parameters or values?

I edited value.yml file and added extraEnvvars under zookeeper section.
set maxbuffer size to 31457280

### What do you see instead?

unable to upload file. zookeeper connection refused.

**Comment by andresbono** [comment]
Hi, can you give us more details on how to reproduce this issue? What kind of file are you uploading and where?

**Comment by shubhranshu007** [comment]
I am uploading .bin and .txt file. The file sizes are more than 1mb.
I am not able to upload and download the files.

**Comment by andresbono** [comment]
Could you give step by step instructions to reproduce the issue? I'm not sure where are you uploading those files. Screenshots and specific error messages would also be very useful.
