### ISSUE TITLE
[bitnami/keycloak] keycloak 22 upgrade

### ISSUE THREAD

**Issue by Sevyls** [bitnami/charts#17809]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Newer version of keycloak will be available

### What is the feature you are proposing to solve the problem?

Upgrade to keycloak 22

**Comment by carrodher** [comment]
Thanks for letting us know, there is an existing issue and we will update it once it is ready, see https://github.com/bitnami/containers/issues/41059
