### ISSUE TITLE
[bitnami/grafana-operator]: ability to overwrite Grafana image

### ISSUE THREAD

**Issue by MShekow** [bitnami/charts#17807]
### Name and Version

bitnami/grafana-operator 3.0.3

### What is the problem this feature will solve?

Ability to run grafana-operator in regulated environments that do not allow the use of Docker Hub images.

### What is the feature you are proposing to solve the problem?

In the `values.yaml` of the Bitnami grafana-operator chart, one should be able to overwrite the _Grafana_ image. For this to work, the `image:` block (as shown [here](https://grafana-operator.github.io/grafana-operator/docs/examples/grafana_deployment/readme/)) needs to be added to the CR defined in [templates/grafana.yaml](https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/templates/grafana.yaml).

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
