### ISSUE TITLE
[bitnami/postgresql] postgresql 10.x.x version helm chart not found

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [bitnami/charts#17829]
### Name and Version

bitnami/postgresql 10.x.x

### What architecture are you using?

arm64

### What steps will reproduce the bug?

hi, I am using airbyte a ETL tool for data engineering part in my project, A specific version of same uses bitnami's postgresql 10.x.x version helm chart. I tried to find somewhere the same version but was unable to find. please refer me to the older repo of helm chart for same

### What do you see instead?

It provide an issue on the other version of postgresql helm chart

**Comment by carrodher** [comment]
This version is not available in the default registry due to the retention policy applied for Helm charts, see [this issue](https://github.com/bitnami/charts/issues/10833) for more information and workarounds about how to use old chart versions

**Comment by yash-ghelani-dsw** [comment]
> This version is not available in the default registry due to the retention policy applied for Helm charts, see [this issue](https://github.com/bitnami/charts/issues/10833) for more information and workarounds about how to use old chart versions

Hi,
I have added the new git url (containing helm of that specific version) in dependency chart and have successfully resolved that issue.
Thanks for your help
