### ISSUE TITLE
bitnami/grafana: Use secret storage for grafana.ini

### ISSUE THREAD

**Issue by HardNorth** [bitnami/charts#1783]
**Which chart**: bitnami/grafana 1.1.9 (latest) 

**Description**

Currently your chart offers Datasource storing as a secret object in Kubernetes. But to mount `grafana.ini` it's only possible to use a configMap object. However `grafana.ini` may contains even more sensitive data than Datasource. E.G. GitHub OAuth client ID and Secret:
Docs: https://grafana.com/docs/grafana/latest/auth/github/
Sample ini: https://github.com/grafana/grafana/blob/master/conf/sample.ini#L310

**Suggestion**
Could you please add an option to store `grafana.ini` in secrets or change it on that type of object?

Thank you, in advance.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. I believe we could add an option to include grafana ini as secret instead of configmap.

**Comment by javsalgar** [comment]
Please check https://github.com/bitnami/charts/issues/1783

**Comment by sameersbn** [comment]
That's a good point. Switching to a Secret makes sense.

**Comment by HardNorth** [comment]
Awesome! Thanks for the instant reaction!
