### ISSUE TITLE
Keycloak version upgrade

### ISSUE THREAD

**Issue by fzk273** [bitnami/charts#17832]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

A new version of keycloak is released (22.0.1). Current version in latest helm chart is 21.1.2

### What is the feature you are proposing to solve the problem?

Keycloak version update

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when packaging this new version and we need to manually fix it.

At this moment the team is working on it. We will update this thread once released the new version.

**Comment by fzk273** [comment]
> Thanks for letting us know, there is an existing issue and we will update it once it is ready, see [bitnami/containers#41059](https://github.com/bitnami/containers/issues/41059)

thanks a lot
