### ISSUE TITLE
LoadBalancer(tcp-external) vs. ExternalAccess(tcp-kafka)

### ISSUE THREAD

**Issue by YunanJeong** [bitnami/charts#17837]
### Name and Version

bitnami/kafka 23.0.5

### What is the problem this feature will solve?

I'm using a Kafka Service(type LoadBalancer) to create the endpoint for external clients.
In particular, I want to use tcp-external("service.ports.external").

However, I have doubts about some basic operations. I'd appreciate it if you could share reasons or previous issues about this.

- To enable tcp-external("service.ports.external"), Why require "externalAccess.enabled=true"? I want tcp-external only, but externalAccess services are created that I don't want.
- Also, why are externalAccess services created as many as the number of kafka replicas? This requires many IPs in a limited network env. Is it inappropriate to use Kafka Service's "service.ports.external" as endpoint instead of externalAccess service?

```template/svc.yaml
# template/svc.yaml
ports:
    (...)
    {{- if .Values.externalAccess.enabled }}
    - name: tcp-external
      port: {{ .Values.service.ports.external }}
      protocol: TCP
      targetPort: kafka-external
      {{- if (not (empty .Values.service.nodePorts.external)) }}
      nodePort: {{ .Values.service.nodePorts.external }}
      {{- end }}
    {{- end }}
    (...)
```
- Also, as shown below, the EXTERNAL advertisedListener's port follows externalAccess's one.
```template/scripts-configmap.yaml
# template/scripts-configmap.yaml
export EXTERNAL_ACCESS_PORT={{ .Values.externalAccess.service.ports.external }}
```
what did i miss? 
I am concerned that the method I want is not common or poses risks.
Thank you.

### What is the feature you are proposing to solve the problem?

If possible, I suggest that Kafka Service's external port ("service.ports.external", tcp-external) is activated independently of externalAccess Service.

**Comment by javsalgar** [comment]
Hi!

There's currently a refactor of the kafka chart, which I believe could fix the issue you mentioned https://github.com/bitnami/charts/pull/17507
