### ISSUE TITLE
[bitnami/mariadb-galera] docker bitnami/mariadb-galera 11.0.2

### ISSUE THREAD

**Issue by Bulofis** [bitnami/charts#17836]
### Name and Version

bitnami/mariadb-galera 11.0.2

### What is the problem this feature will solve?

we urgently need to add the mariadb-gallery image to docker with version at least 11.0, preferably 11.0.2

### What is the feature you are proposing to solve the problem?

create image docker.io/bitnami/mariadb-galera:10.0.2

### What alternatives have you considered?

create image docker.io/bitnami/mariadb-galera:10.0

**Comment by javsalgar** [comment]
Hi!

The team has tracked the release and will work on it. As it is a major version it may probably require changes in the container and chart, so it will take a bit longer than expected. As soon as there are news, we will update this ticket.

**Comment by jotamartos** [comment]
Hi, 

Just a quick note to let you know that the chart now includes MariaDB 11.0

https://github.com/bitnami/charts/pull/18079

Enjoy!
