### ISSUE TITLE
[bitnami/rabbitmq] OIDC / OAuth2 support for rabbitmq

### ISSUE THREAD

**Issue by SeWieland** [bitnami/charts#17846]
### Name and Version

bitnami/rabbitmq 12.0.8

### What is the problem this feature will solve?

The rabbitmq chart already provides LDAP support via the `.Values.ldap.*` values that generate an appropriate minimal rabbitmq configuration.

It would be really nice to have similar (mutually exclusive?) values for configuring basic OAuth2 support out-of-the box for rabbitmq + the managment ui + very basic docs about the required OIDC server config / settings (=> keycloak).

**The setup required for rabbitmq to integrate with e.g. keycloak is really complicated imo** and it would be really helpful for many people trying to set up a basic OIDC integration.

### What is the feature you are proposing to solve the problem?

A configuration block in the values yml similar to the existing LDAP configuration.

As everything can already be configured via the "extraConfiguration", this section should be minimalistic and provide the right hints / links for users to configure just a very basic setup correctly.

### What alternatives have you considered?

Currently I'm trying to configure everything "manually" by providing additional config via `rabbitmq.extraConfiguration`

See also: 

- https://www.rabbitmq.com/oauth2.html
- https://www.rabbitmq.com/oauth2-examples.html
- https://www.rabbitmq.com/oauth2-examples.html#access-management-ui
- https://blog.rabbitmq.com/posts/2022/07/oidc-integration/#usage

It should also be possible to set up the integration via oauth2 proxy instead of directly using KC. I don't know why this would be beneficial though.

- https://www.rabbitmq.com/oauth2-examples-proxy.html

All in all, the configuration is not straight forward - and this Chart could help to simplify the setup drastically.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! If you already have a set of values that work with extraConfiguration, would you like to submit a PR adding support for the `*.oidc` set of values?

**Comment by SeWieland** [comment]
I'll consider it, as soon as I'll finally have a working setup..

**Comment by jaison1983** [comment]
We tried doing RabbitMQ management UI login using keycloak integration 
The client is created in keycloak for rabbitmq (name RabbitMQMang)
configured the values in extra configuration

extraConfiguration: |-
  auth_mechanisms.1 = PLAIN
  auth_mechanisms.2 = EXTERNAL

  auth_backends.2 = internal
  auth_backends.3 = rabbit_auth_backend_oauth2

  management.oauth_enabled = true
  management.disable_basic_auth = true
  management.oauth_client_id = rabbitmq
  management.oauth_scopes = openid profile rabbitmq.tag:administrator
  management.oauth_provider_url = https://domainName/realms/realmName

  auth_oauth2.resource_server_id = rabbitmq
  auth_oauth2.preferred_username_claims = user_name
  auth_oauth2.additional_scopes_key = extra_scope
  auth_oauth2.jwks_url =  https://domainName/realms/realmName/protocol/openid-connect/certs

See the login page and login with username and password and get error not authorized 

In rabbitmq log I see 
HTTP access denied : User RabbitMQMang authentication failed with internal error. 

Strange that RabbitMQMang  is keycloak client name not username provided while login.

Need support
