### ISSUE TITLE
[bitnami/harbor] harbor Chartmuseum missing

### ISSUE THREAD

**Issue by johnwc** [bitnami/charts#17851]
### Name and Version

bitnami/harbor 16.6.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Install version v14.x
Update to v16.6.1

### What do you see instead?

The charts endpoint is missing. I have chartmuseum.enabled set to true, but chartmuseum seems to be missing in the UI and API endpoint.

**Comment by javsalgar** [comment]
Hi.

According to upstream, the use of chartmuseum was deprecated

https://github.com/goharbor/harbor/issues/14407

**Comment by johnwc** [comment]
What is the last version of the chart that has chartmuseum?

**Comment by javsalgar** [comment]
Hi,

My guess is that it should be the version that has appVersion < 2.4.0. It is likely that it's part of the old index, please check https://github.com/bitnami/charts/issues/10539
