### ISSUE TITLE
[bitnami/grafana-operator] Grafana image not using imagePullSecret

### ISSUE THREAD

**Issue by MShekow** [bitnami/charts#17859]
### Name and Version

bitnami/grafana-operator 3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm template my-release oci://registry-1.docker.io/bitnamicharts/grafana-operator --version=3.1.1 -f values.yaml`

### Are you using any custom parameters or values?

```yaml
global:
  imagePullSecrets:
    - something
```

### What is the expected behavior?

Generated `Grafana` CR should use the globally defined `imagePullSecret` (or the one overwritten in `values.yaml` in `grafana.image.pullSecrets`). Neither is happening.

### What do you see instead?

No image pull secret is used at all for the `Grafana` CR.

**Comment by rafariossaa** [comment]
Hi,
  The CRD we are including are [the upstream ones](https://github.com/bitnami/charts/blob/fc3f7406c0285050609de7432d71560673cb8f13/bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml#L4). I am creating an internal task to review the upstream operator's CRDs. However, right now, I could not tell if they include this feature or not.
  We will comeback as soon as we have news. Meanwhile, if you would like to send a PR we will be glad to review and merge it.

**Comment by MShekow** [comment]
The CRs of course have this feature and someone might already have fixed it (see https://github.com/bitnami/charts/commit/5019f0a6052514dbae0a56e3fa5829138a9043a2). But I am not sure whether this fix has already been _released_. Your repo / Helm charts are missing a clear indication of what is released (and when), and there also is no changelog.

**Comment by rafariossaa** [comment]
Hi,
  So would https://github.com/bitnami/charts/commit/5019f0a6052514dbae0a56e3fa5829138a9043a2 fix this issue for you ?
  Regarding the changelog I have created an internal task for our engineering team to consider.

**Comment by MShekow** [comment]
> Hi, So would [5019f0a](https://github.com/bitnami/charts/commit/5019f0a6052514dbae0a56e3fa5829138a9043a2) fix this issue for you ?

Yes, indeed. I also see that with version 3.1.3 the issue seems to be fixed.

**Comment by juan131** [comment]
Hi @MShekow 

I proceed to close the issue since the changes I introduced at #17876 addressed it. Please feel free to reopen it if you find errors again.

Thanks for reporting it.
