### ISSUE TITLE
[bitnami/postgresql-ha] postgresql HA parameter does not work

### ISSUE THREAD

**Issue by ffdtt** [bitnami/charts#17868]
### Name and Version

bitnami/postgresql-ha:11.7.6

### What architecture are you using?

None

### What steps will reproduce the bug?

I modified the configuration of value.yaml:
```
......
postgresql:
...
  tcpKeepalivesCount: ''
  tcpKeepalivesIdle: 0
  tcpKeepalivesInterval: ''
...
```
After the installation is complete, "tcp_keepalives_idle" is still 7200.

"select * from pg_settings where name like '%tcp%'" result is:
![image](https://github.com/bitnami/charts/assets/42604414/ea9bdcd7-aa03-4f42-9919-f30e101933fc)

Is there any solution that can help with this issue?

Thanks!

### Are you using any custom parameters or values?
```
  tcpKeepalivesCount: ''
  tcpKeepalivesIdle: 0
  tcpKeepalivesInterval: ''
```

### What do you see instead?

tcp_keepalives_idle	7200s	

### Additional information

Digression：
The reason why I set tcpKeepalivesIdle to 0 is that pg_dump returns an error after executing for a while:
pg_dump: error: query failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

**Comment by FraPazGal** [comment]
Hi @ffdtt, I have reproduced your case but I don't think this counts as a bug. Looking into [PSQL documentation](https://www.postgresql.org/docs/current/runtime-config-connection.html), the `tcp_keepalives_idle` is defined as:

>Specifies the amount of time with no network activity after which the operating system should send a TCP keepalive message to the client. If this value is specified without units, it is taken as seconds. A value of 0 (the default) selects the operating system's default. This parameter is supported only on systems that support TCP_KEEPIDLE or an equivalent socket option, and on Windows; on other systems, it must be zero. In sessions connected via a Unix-domain socket, this parameter is ignored and always reads as zero.

Going by this, using `postgresql.tcpKeepalivesIdle=0` is the same as using the default value (300 for debian-11). I have checked the `bitnami/postgresql-ha` chart and it does modify the config value properly:

- Default installation:
```
$ kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:15.3.0-debian-11-r72 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d postgres

If you don't see a command prompt, try pressing enter.
postgres=# SHOW tcp_keepalives_idle;
 tcp_keepalives_idle
---------------------
 300
(1 row)

-----

$ kubectl exec -it postgresql-ha-postgresql-0 -- bash
I have no name!@postgresql-ha-postgresql-0:/$ cat /opt/bitnami/postgresql/conf/postgresql.conf | grep alive
#tcp_keepalives_idle = 0		# TCP_KEEPIDLE, in seconds;
#tcp_keepalives_interval = 0		# TCP_KEEPINTVL, in seconds;
#tcp_keepalives_count = 0		# TCP_KEEPCNT;
```

- Custom installation:
```
$ helm install postgresql-ha bitnami/postgresql-ha --set postgresql.tcpKeepalivesIdle="100"
...
CHART NAME: postgresql-ha
CHART VERSION: 11.8.0
APP VERSION: 15.3.0
...
$ kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:15.3.0-debian-11-r72 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d postgres

If you don't see a command prompt, try pressing enter.
postgres=# SHOW tcp_keepalives_idle;
 tcp_keepalives_idle
---------------------
 100
(1 row)

-----

$ kubectl exec -it postgresql-ha-postgresql-0 -- bash
I have no name!@postgresql-ha-postgresql-0:/$ cat /opt/bitnami/postgresql/conf/postgresql.conf | grep alive
tcp_keepalives_idle = '100'
#tcp_keepalives_interval = 0		# TCP_KEEPINTVL, in seconds;
#tcp_keepalives_count = 0		# TCP_KEEPCNT;
```

Installing the chart with `helm install postgresql-ha bit/postgresql-ha --set postgresql.tcpKeepalivesIdle="0"` leaves the value as `300` and the config line commented. I'll say this is an implementation feature of PSQL and thus we can't do much about it.

**Comment by FraPazGal** [comment]
Hi @ffdtt,

Going only by the error msg you share I can't give you any advice. I would first try checking the pods logs and events and see if there is any pod's restarts or logs that point to an issue. That said, it seems this could be an error related to PSQL itself and not specifically to the chart. In that case I would recommend to contact [PSQL support channels](https://www.postgresql.org/community/), as they do posses a greater expertise on the PSQL workings.
