### ISSUE TITLE
[bitnami/mongodb] Not able to find mongo chart version of 10.20.0

### ISSUE THREAD

**Issue by sushmithan2** [bitnami/charts#17864]
### Name and Version

bitnami /mongodb 10.20.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm upgrade --install dev-mongodb bitnami/mongodb --version 10.20.0
<img width="929" alt="Screenshot 2023-07-25 134520" src="https://github.com/bitnami/charts/assets/137364706/38603dd0-f2c1-4272-a5b5-634c0c865d06">

### Are you using any custom parameters or values?

No

### What do you see instead?

Want a bitnami repo which has mongo chart version 0f 10.20.0

**Comment by sushmithan2** [comment]
@carrodher Can you please help me with this issue

**Comment by javsalgar** [comment]
Hi,

It seems to me that this could be part of the old index.yaml file. Could you check this? 

https://github.com/bitnami/charts/issues/10539
