### ISSUE TITLE
[bitnami/postgresql-ha] Additional users cannot be created

### ISSUE THREAD

**Issue by GruemL** [bitnami/charts#17889]
### Name and Version

bitnami/postgresql-ha-9.1.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Our goal is to create new users and a database when the postgres pods start. 

We have deployed the following step for the init scripts in the values.yaml of the helm chart:

```bash
postgresql:
    initdbScripts:
        user_setup.sql: |
            CREATE USER artifactory WITH PASSWORD 'XXX';
            CREATE DATABASE artifactory WITH OWNER=artifactory ENCODING='UTF8';
            GRANT ALL PRIVILEGES ON DATABASE artifactory TO artifactory;
            CREATE USER xray WITH PASSWORD 'XXX';
            CREATE DATABASE xraydb WITH OWNER=xray ENCODING='UTF8';
            GRANT ALL PRIVILEGES ON DATABASE xray TO xray;
``` 

This is also processed, because the script is then under:

```bash
I have no name!@postgresql-ha-postgresql-0:/docker-entrypoint-initdb.d$ ls
user_setup.sql

```

in the container. 

 However, we do not see anything in the log that this script is executed when the Postgres pods are started. The users/DBs are also not created.

Any ideas what we need to do to run the script when the Postgres Pods are started so that the users/DBs are created?

### Are you using any custom parameters or values?

described above

### What is the expected behavior?

The script is to be executed and the users and DBs are to be

### What do you see instead?

The script is not executed

**Comment by dakky** [comment]
I guess i found the problem:
the scripts defined in `initdbScripts` are only executed, on the first run (https://github.com/bitnami/containers/blob/main/bitnami/postgresql-repmgr/15/debian-11/rootfs/opt/bitnami/scripts/librepmgr.sh#L840)

So in fact this means, that `initdbScripts` is not a valid way to manage Users in a bitname postgresql-ha setup

**Comment by joancafom** [comment]
Hi @GruemL 

I was able to execute initdb scripts with no issues. Notice however that if the `debug` mode is not enable, you won't actually be able to see explicitly log entries mentioning which script is being executed and their result:

```console
$ cat user-values.yaml
postgresql:
  image:
    debug: true
  initdbScripts:
    user_setup.sql: |
              CREATE USER artifactory WITH PASSWORD 'MYPASSWORD';
              CREATE DATABASE artifactory WITH OWNER=artifactory ENCODING='UTF8';
              GRANT ALL PRIVILEGES ON DATABASE artifactory TO artifactory;
              CREATE USER xray WITH PASSWORD 'MYPASSWORD2';
              CREATE DATABASE xraydb WITH OWNER=xray ENCODING='UTF8';
              GRANT ALL PRIVILEGES ON DATABASE xray TO xray;

$ helm install postgres-ha oci://registry-1.docker.io/bitnamicharts/postgresql-ha -f user-values.yaml
$ kubectl logs postgres-ha-postgresql-ha-postgresql-0
...
postgresql-repmgr 09:08:27.00 INFO  ==> Loading custom scripts...
postgresql-repmgr 09:08:27.01 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql-repmgr 09:08:27.01 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:08:27.02 DEBUG ==> Executing /docker-entrypoint-initdb.d/..2023_08_04_09_08_19.4167745998/user_setup.sql
CREATE ROLE
CREATE DATABASE
GRANT
CREATE ROLE
CREATE DATABASE
2023-08-04 09:08:27.155 GMT [282] ERROR:  database "xray" does not exist
2023-08-04 09:08:27.155 GMT [282] STATEMENT:  GRANT ALL PRIVILEGES ON DATABASE xray TO xray;
ERROR:  database "xray" does not exist
postgresql-repmgr 09:08:27.16 INFO  ==> Configuring synchronous_replication
postgresql-repmgr 09:08:27.19 INFO  ==> Stopping PostgreSQL...
...
```

Notice as well that the SQL statements you provided are produce some errors, but the do have an effect in the PostgreSQL instance:

```console
$ kubeclt exec -it postgres-ha-postgresql-ha-postgresql-0 -- psql -U postgres
postgres=# \l
 artifactory | artifactory | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =Tc/artifactory            +
             |             |          |             |             |            |                 | artifactory=CTc/artifactory
 postgres    | postgres    | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            |
 repmgr      | postgres    | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            |
 template0   | postgres    | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres                +
             |             |          |             |             |            |                 | postgres=CTc/postgres
 template1   | postgres    | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres                +
             |             |          |             |             |            |                 | postgres=CTc/postgres
 xraydb      | xray        | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            |

```

----

As correctly pointed by @dakky, the `initdbScripts` were only conceived to be executed on the first run (when the DB is firstly initialized). If you aim to have more complex set-ups, you can always resort to sidecars containers (`postgresql.sidecars`).
