### ISSUE TITLE
v3.1.1 of grafana-operator chart pullsecrets not used.

### ISSUE THREAD

**Issue by pseymournutanix** [bitnami/charts#17880]
### Name and Version

bitnami/grafana-operator:v3.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/templates/grafana.yaml doesn't include the setup for  `pullSecrets` in the `values.yaml` file 

### Are you using any custom parameters or values?

No

### What is the expected behavior?

`pullSecrets` is used

### What do you see instead?

The values are not included in the template.

**Comment by MShekow** [comment]
Already reported that in #17859
