### ISSUE TITLE
[bitnami/mariadb-galera] README.md defines nodeAffinity, podAntiAffinity and podAffinity but values and statefulset use affinity

### ISSUE THREAD

**Issue by luizgn** [bitnami/charts#1789]
**Which chart**:

bitnami/mariadb-galera:0.6.0

**Description**

README.md defines nodeAffinity, podAntiAffinity and podAffinity on lines 118-120 but values and statefulset use affinity:

https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/templates/statefulset.yaml#L28-L29
https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/values.yaml#L344-L347

**Steps to reproduce the issue:**

It is just a documentation issue.

**Describe the results you received:**

Affinity doesn't work as defined in README.md.

**Describe the results you expected:**

Replace nodeAffinity, podAntiAffinity and podAffinity by affinity on README.md.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version of Helm and Kubernetes**:

It is just a documentation issue.

**Comment by sameersbn** [comment]
Thanks for the report
