### ISSUE TITLE
[bitnami/airflow] Airflow scheduler with pvc (rook-ceph) Crashed after pod restarted. 

### ISSUE THREAD

**Issue by deadmandrive** [bitnami/charts#17896]
### Name and Version

bitnami/airflow:1.8.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I deployed airflow using bitnami chart in K8s Cluster v.1.23.5 the node is centsOS8 and we use rook-ceph to do pvc. 
2. The PVC we use rook-cephfs with is RWX mode.
3. After deployed it functioning like 4-5 days. And the pod restarted on somehow.

### What do you see instead?

After that the airflow-scheduler pod get crashloopbackoff the logs said "failed to try resolving symlinks in path "/var/log/pods/gids-airflow_airflow-gids-dev-scheduler-7c86dbd65f-9p8gh_ad57b2db-f95c-4860-aca1-1b5e20b704f5/scheduler/282.log": lstat /var/log/pods/gids-airflow_airflow-gids-dev-scheduler-7c86dbd65f-9p8gh_ad57b2db-f95c-4860-aca1-1b5e20b704f5/scheduler/282.log: no such file or directory"

We descripbe to pod and it said.
"error while creating mount source path '/var/lib/kubelet/pods/ad57b2db-f95c-4860-aca1-1b5e20b704f5/volumes/kubernetes.io~csi/pvc-ab80e967-a429-4bb1-9eca-393c09836022/mount': mkdir /var/lib/kubelet/pods/ad57b2db-f95c-4860-aca1-1b5e20b704f5/volumes/kubernetes.io~csi/pvc-ab80e967-a429-4bb1-9eca-393c09836022/mount: file exists"

**Comment by javsalgar** [comment]
Hi,

It seems that there is a compatibility issue with rook-ceph with Airflow. Do you see this issue with other applications?

**Comment by deadmandrive** [comment]
Hi, 
We use redis cluster from bitnami with rook-ceph as well but didn't get this issue.

**Comment by javsalgar** [comment]
Hi,

Are you scaling the number of replicas of the deployments? As the PVC is readwritemany this could lead to issues if several of them are writing at the same time.

**Comment by deadmandrive** [comment]
@javsalgar No replicas is 1

**Comment by javsalgar** [comment]
It is not clear to me that this is an issue with the Bitnami packaging or with Airflow itself, did you try checking with the rook-ceph developers with this issue?
