### ISSUE TITLE
[bitnami/grafana-operator] Grafana Operator: Timeout Errors on Reconcile

### ISSUE THREAD

**Issue by pseymournutanix** [bitnami/charts#17892]
### Name and Version

bitnami/grafana-operator:v3.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Try to deploy datasources/dashboards and get things like this for all of them:-

```
1.6902926761294918e+09	INFO	GrafanaDatasourceReconciler	found matching Grafana instances for datasource	{"controller": "grafanadatasource", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaDatasource", "GrafanaDatasource": {"name":"tempo-corp","namespace":"grafana"}, "namespace": "grafana", "name": "tempo-corp", "reconcileID": "22fa1396-6836-4468-b677-4f466969077c", "count": 1}
1.6902926769751587e+09	ERROR	GrafanaDashboardReconciler	error reconciling dashboard	{"controller": "grafanadashboard", "controllerGroup": "grafana.integreatly.org", "controllerKind": "GrafanaDashboard", "GrafanaDashboard": {"name":"onprem-iaas-probes-dashboard","namespace":"grafana"}, "namespace": "grafana", "name": "onprem-iaas-probes-dashboard", "reconcileID": "cc716212-fe63-4473-9041-dae9f0e9dee5", "dashboard": "onprem-iaas-probes-dashboard", "grafana": "grafana-operator-grafana", "error": "Internal error occurred: Get \"http://grafadm:***@grafana-operator-grafana-service.grafana:3000/api/folders?limit=1000&page=1\": dial tcp 172.19.1.78:3000: i/o timeout"}
```

The service is there and matches the IP and I can port-forward and login to Grafana just fine. I set `grafadm` as the name/pw of the admin account

```
$ get svc -n grafana
NAME                               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
grafana-operator                   ClusterIP   None          <none>        8080/TCP   64m
grafana-operator-grafana-service   ClusterIP   172.19.1.78   <none>        3000/TCP   64m
```

### Are you using any custom parameters or values?

```
    security:
      admin_user: grafadm
      admin_password: grafadm
      disable_gravatar: "true"
```

### What is the expected behavior?

Datasources, and Dashboards get reconciled and imported

### What do you see instead?

`i/o timeout`

**Comment by javsalgar** [comment]
Hi,

Are you able to reproduce the issue in other Kubernetes clusters? An i/o timeout issue seems more related to me to the cluster configuration rather than the Bitnami packaging.

**Comment by pseymournutanix** [comment]
I'll try to reproduce it, there is a lot of apps on this cluster and I do lots of `kubectl -v=9` commands and nothing else exhibits this. But it's possible so I will try v4.x didn't do this on this cluster.
