### ISSUE TITLE
[bitnami/spark] PySpark SSL S3 Connection

### ISSUE THREAD

**Issue by ameuchel** [bitnami/charts#17901]
### Name and Version

bitnami/spark 7.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run `helm install spark oci://registry-1.docker.io/bitnamicharts/spark --version 7.1.0`

2. Create python file with following code where s3 endpoint begins with https://:

```
from pyspark.sql import SparkSession, Row

# Tried with and without hadoop-common (downloaded hadoop-common from maven and copied into the pod)
sc = SparkSession.builder.appName('test')\
        .master('spark://spark-master-svc:7077')\
        .config('spark.hadoop.fs.s3access.key', '<key>')\
        .config('spark.hadoop.fs.s3a.secret.key', '<secret>')\
        .config('spark.driver.cores', '3')\
        .config('spark.hadoop.fs.s3a.impl', 'org.apache.hadoop.fs.s3a.S3AFileSystem')\
        .config('spark.jars.packages', '/opt/bitnami/spark/jars/hadoop-aws:3.3.2.jar,/opt/bitnami/spark/jars/hadoop-common:3.3.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.1026.jar')\
        .getOrCreate()
        
sc._jsc.hadoopConfiguration().set('fs.s3a.endpoint', '<endpoint>')
sc._jsc.hadoopConfiguration().set('fs.s3a.connection.ssl.enabled', 'false')
sc._jsc.hadoopConfiguration().set('fs.s3a.path.style.access', 'true')

df = sc.createDataFrame([Row(a=1, b=2, Row(a=3, b=4)])

df.write.format("parquet").option("path", "s3a://bucket/path").mode("overwrite").save()
```

3. Copy python file into spark Kubernetes pod and run `spark-submit <filename>.py`.

4.  See ssl/certificate error messaging

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Dataframe is successfully written to s3

### What do you see instead?

Error logs such as: `javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certPath.SunCertPathBuilderException: unable to find valid certificatoin path to requested target`

or 

`javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

The `sun.security...` error happens when `fs.s3a.connection.ssl.enabled` is set to false while the `handshake_failure` error message happens when it is set to true

### Additional information

Writing to the s3 bucket works as expected when connected to an http endpoint rather than https. It is only when switching to an https endpoint that the error arises.

The endpoint we are trying to connect to is an on-prem storage solution accessible through a different node of the Kubernetes cluster.

We have verified that we can connect to the bucket from the spark pod through other methods (non-spark) such as sshing into the pod and running curl or python's boto3.

For instance, we can connect with boto3 via:

```
session = boto3.Session()
client = session.client(service_name='s3', aws_access_key_id='<id>, aws_secret_access_key='<secret>', endpoint_url='<endpoint>', verify=False)
```

We can also connect with boto3 by setting `verify` to the appropriate cert file.

With spark, we don't care if we do the equivalent of setting the ssl verify to False, or if we use the appropriate cert. We have tried both and neither seems to work. Disabling ssl would seem to be the easier solution.

We have tried setting numerous combinations of other pyspark config values other than what I listed in the initial example file. Here are some of those other configs:

```
fs.s3a.enablev4 -> true
spark.ssl.enabled -> true/false
spark.ssl.trustStore -> truststore file
spark.ssl.keyStore -> keystore file
spark.ssl.keyPassword -> password
spark.ssl.trustStorePassword -> password

spark.driver/executor.extraJavaOptions -> -Djavax.net.ssl.trustStore=<>,-Djavax.net.ssl.keyStore=<>,-Djavax.net.ssl.keyStore.password=<>,-Djavax.net.ssl.trustStore.password=<>,-Djavax.net.ssl.keyStorePassword=<>,-Djavax.net.ssl.trustStorePassword=<>,-Dcom.sun.net.ssl.checkRevocation=false,-Dcom.amazonaws.sdk.disableCertChecking=true
```

In the case where we set keystore/truststore values, we created some jks keystore and truststore files and added the appropriate .crt/.pem file to the stores. We've even tried changing the JAVA_HOME env variable to point to keystore/truststore files we created.

If we could simply perform the boto3 equivalent of setting `verify=False`, that would be great. Using the appropriate certificates/keystore/truststore could be a future end goal.

**Comment by javsalgar** [comment]
Hi,

Is this issue only happening with the spark code? Are you able to enter the container and check if a command like `curl` returns certificate issues?

**Comment by ameuchel** [comment]
@javsalgar Thank you for the reply. The issue is only happening with the spark code. In the "Additional information" section of the issue, I provide some details of how we ssh'd into the pod and connected with `curl` and `boto3`.

To expand on `curl` a bit, we would get an ssl error if we did not due one these three things:
1. Set the `--insecure` flag (like setting `verify=False` with boto3 
2. Set the `--cacert` flag to our .crt or .pem file 
3. Set the `SSL_CERT_FILE` env variable to our .crt or .pem file

**Comment by andresbono** [comment]
> we created some jks keystore and truststore files and added the appropriate .crt/.pem file to the stores

In which pod did you create the keystore/truststore? Maybe it is needed to have it in both the master and workers?

Let us know if you have any update on this issue.
