### ISSUE TITLE
[bitnami/redis-cluster] Add cluster DNS hostnames or fixed IPs

### ISSUE THREAD

**Issue by vladsf** [bitnami/charts#17949]
### Name and Version

bitnami/redis-cluster 8.6.7

### What is the problem this feature will solve?

Every time I re-deploy bitnami/cluster it gets random IPs for clusters nodes (cluster.externalAccess enabled).
How do I fix that or better to assign a DNS name to every nodes?

### What is the feature you are proposing to solve the problem?

Accessing redis cluster nodes by hostnames, not IPs

### What alternatives have you considered?

Not found

**Comment by javsalgar** [comment]
Hi,

There is a script inside the container logic that updates the list of IPs, could you share the logs of the pods?

**Comment by vladsf** [comment]
Not sure I understand, all 9 pods?

I did standard 'install' + 'upgrade with LoadBalancer IPs'. Yet an web App needs a way to discover those IPs. Unlike a hostname which is constant.

So the problem is not that IPs are changed on every upgrade. They are chenged after full delete & clearance.

**Comment by vladsf** [comment]
resolved with annotations and DNS labels.

**Comment by carrodher** [comment]
Glad to see you solved the issue!
