### ISSUE TITLE
postgres-ha works only with default values

### ISSUE THREAD

**Issue by Nello-Angelo** [bitnami/charts#17969]
### Name and Version

latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

postgres-ha works only with default values and any changes cant let to start cluster. I dont understand how you test this chart

### Are you using any custom parameters or values?

any changes

### What is the expected behavior?

![Screenshot_14](https://github.com/bitnami/charts/assets/82488489/72af2fa1-fa03-4477-a722-ef4666ea96f0)
![Screenshot_11](https://github.com/bitnami/charts/assets/82488489/309b5352-0a6c-4816-a1f5-675fcfcf0146)

### What do you see instead?

![Screenshot_12](https://github.com/bitnami/charts/assets/82488489/d1d03ca4-d9ec-4783-a787-78bfe1d6eab1)

**Comment by carrodher** [comment]
Could you please provide more info about how are you deploying the Helm chart and what are the values you are modifying?
