### ISSUE TITLE
Kafka helm install fails when zookeeper exporter is enabled with zookeeper.metrics.enabled=true

### ISSUE THREAD

**Issue by amtux** [bitnami/charts#1796]
**Which chart**: bitnami/kafka

**Description**
Installing helm chart with zookeeper metrics enabled fails the deployment because `Deployment.apps "kafka-zookeeper-exporter" is invalid`. Installation succeeds when zookeeper metrics are left disabled - even if jmx metrics and ServiceMonitor are enabled.

**Steps to reproduce the issue:**
1. Add repo to helm with `helm repo add bitnami https://charts.bitnami.com/bitnami`
1. Install chart with zookeeper metrics enabled: `helm install kafka --atomic --namespace storage bitnami/kafka --set zookeeper.metrics.enabled=true`

**Describe the results you received:**

```
Error: release kafka failed, and has been uninstalled due to atomic being set: Deployment.apps "kafka-zookeeper-exporter" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"kafka", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"zookeeper", "helm.sh/chart":"zookeeper-5.2.0"}: `selector` does not match template `labels`
```

**Describe the results you expected:**
Expected the installation to succeed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sameersbn** [comment]
@amtux thanks for reporting this issue. A fix for the issue has been implemented in the zookeeper chart #1797. Once it has been merged we will update the zookeeper dependency version in the kakfa chart too.
