### ISSUE TITLE
[bitnami/postgresql-ha] How to properly handle major version upgrades?

### ISSUE THREAD

**Issue by joachimnielandt** [bitnami/charts#1798]
I am currently testing out the postgresql-HA chart and was wondering how a major version upgrade of PostgreSQL would be handled properly in the default scenario? It is my understanding that the postgres version can be easily modified in the chart's values, but when the data folders are instantiated a major version change (and chart update) results in broken containers. Makes sense, as the data folders have to be updated to match the new postgres version. Will this be handled by the chart in the future, or is there a clean way of doing this manually?

**Comment by sameersbn** [comment]
@CountZukula IMO the safest way to migrate between major versions is to do a [Backup and Restore](https://www.postgresql.org/docs/9.1/backup.html).

**Comment by CountZukula** [comment]
For most databases that would suffice, but when faced with large datasets I might prefer an in-place upgrade. I understand that this would not be supported in the future of this chart?

**Comment by sameersbn** [comment]
@CountZukula You are right in that regard. Re: future support, @juan131 @javsalgar could you please chime in here.

**Comment by sameersbn** [comment]
@juan131 any ideas?

**Comment by juan131** [comment]
Hi @sameersbn 

I guess we could try to add some mechanisms to upgrade the schema in the data whenever we detect there's persisted data (using `pg_upgrade`). However, we should implement this in a way we can skip it since we don't want to play with users data automatically unless they're conscious about it.

We're doing sth similar for MariaDB (see https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.1/debian-9/rootfs/libmysql.sh#L376 and https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.1/debian-9/rootfs/libmysql.sh#L718)

**Comment by TJM** [comment]
Our procedure is roughly:

* Scale APP instances to 0 (kubectl scale sts/artifactory --replicas 0)
* Deploy new release of the latest version of the chart (change release name) in *parallel* with the old one
* Migrate data: 
```
kubectl exec -it artifactory-db-postgresql-0 -- bash -c 'export PGPASSWORD=${POSTGRES_PASSWORD}; time pg_dump -h artifactory-postgresql -U artifactory | psql -U artifactory'
```
... where we were moving from the built-in artifactory helm chart's postgresql 9.6.x to the latest 12.x. This is effectively a backup/restore, but I never had to write a file anywhere or worry about kubectl cp'ing it or whatever.,
* Update application's helm chart configuration to point to new DB, which sets the replicaCount back where it should be
* Delete old PVC

**Comment by juan131** [comment]
Thanks so much for sharing this workaround to backup/restore your existing release data!! We really appreciate it.
I am sure it'll be very helpful for other users!!
