### ISSUE TITLE
metrics: Prometheus support for SSL/TLS?

### ISSUE THREAD

**Issue by nickpapadonis** [bitnami/charts#17987]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

I do not see any options in the metrics.* section for SSL support.  Prometheus supports it.  Will it be added?

### What is the feature you are proposing to solve the problem?

Add TLS/SSL support

### What alternatives have you considered?

Insecure

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
