### ISSUE TITLE
[bitnami/mongodb] systemverbosity 5 and 1 is reporting s:"I", s:"E", s:"D*" but I need just s:"E"

### ISSUE THREAD

**Issue by rr-jino-jose** [bitnami/charts#17988]
### Name and Version

https://charts.bitnami.com/bitnami 12.1.31

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set systemVerbosity paramter to 1 or 5 

### What is the expected behavior?

I just need E logs and not I or D* logs in mongoDB pods.
I do see this env variable is set in pods MONGODB_SYSTEM_LOG_VERBOSITY: 5 but still I see 'I' and 'D*' logs
I even tried MONGODB_SYSTEM_LOG_VERBOSITY: 1

### What do you see instead?

Just see s:"E" in mongoDB pod logs - k8s

**Comment by rr-jino-jose** [comment]
Another thing which I noted is when I try to redeploy it fails with the following error

```
{"t":{"$date":"2023-07-31T14:51:50.077+00:00"},"s":"D1", "c":"NETWORK",  "id":22940,   "ctx":"initandlisten","msg":"file descriptor and connection resource limits","attr":{"hard":104857
6,"soft":1048576,"conn":838860}}
{"t":{"$date":"2023-07-31T14:51:50.078+00:00"},"s":"D1", "c":"EXECUTOR", "id":23104,   "ctx":"OCSPManagerHTTP-0","msg":"Starting thread","attr":{"threadName":"OCSPManagerHTTP-0","poolNa
me":"OCSPManagerHTTP"}}
{"t":{"$date":"2023-07-31T14:51:50.078+00:00"},"s":"D1", "c":"-",        "id":23074,   "ctx":"initandlisten","msg":"User assertion","attr":{"error":"DBPathInUse: Unable to lock the lock
 file: /bitnami/mongodb/data/db/mongod.lock (Resource temporarily unavailable). Another mongod instance is already running on the /bitnami/mongodb/data/db directory","file":"src/mongo/d
b/storage/storage_engine_init.cpp","line":214}}
{"t":{"$date":"2023-07-31T14:51:50.078+00:00"},"s":"E",  "c":"CONTROL",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"DBPathInU
se: Unable to lock the lock file: /bitnami/mongodb/data/db/mongod.lock (Resource temporarily unavailable). Another mongod instance is already running on the /bitnami/mongodb/data/db dir
ectory"}}
```

Looks like the it doesn't want to upgrade/override good old instance

**Comment by joancafom** [comment]
Hi @rr-jino-jose 

>I do see this env variable is set in pods MONGODB_SYSTEM_LOG_VERBOSITY: 5 but still I see 'I' and 'D*' logs

This is expected, as the greater the value is, the more fine-grained the log becomes.

> I just need E logs and not I or D* logs in mongoDB pods.

You can't skip _Informational_ messages tweaking the value of `systemVerbosity`, as per the [official documentation](https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-systemLog.verbosity), the lowest value is `0`, which means that only Informational messages will be shown.

You may try however the `disableSystemLog`, which will run mongodb in quiet mode and limit the amount of output. 

>Another thing which I noted is when I try to redeploy it fails with the following error

We try to keep issues single-themed. Could you please open a new one reporting the problem?

**Comment by rr-jino-jose** [comment]
Thanks @joancafom.

**Comment by rr-jino-jose** [comment]
I tried MONGODB_DISABLE_SYSTEM_LOG: yes

And I still see logs are populating

**Comment by joancafom** [comment]
I have checked and the parameter inside the configuration file for MongoDB is correctly set:

```bash
$ k exec -it mongodb-756444bdc9-khvtj -- cat /opt/bitnami/mongodb/conf/mongodb.conf | grep "systemLog" -A5
systemLog:
  destination: file
  quiet: true
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
```

So this means that the logs you see are the quieter MongoDB can go.
