### ISSUE TITLE
[bitnami/mongodb] MongoServerError: Authentication failed

### ISSUE THREAD

**Issue by ricosega** [bitnami/charts#17993]
### Name and Version

bitnami/mongodb 13.16.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Run the default values.yaml passing the arguments provided below.

### Are you using any custom parameters or values?
```yaml
architecture: replicaset
auth:
  enabled: true
  existingSecret: "mongodb-creds"
```
### What is the expected behavior?

To start properly

### What do you see instead?
From the arbiter Pod
```
mongodb 10:28:21.80 
mongodb 10:28:21.80 Welcome to the Bitnami mongodb container
mongodb 10:28:21.80 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 10:28:21.80 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 10:28:21.81 
mongodb 10:28:21.81 INFO  ==> ** Starting MongoDB setup **
mongodb 10:28:21.83 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 10:28:21.90 INFO  ==> Initializing MongoDB...
mongodb 10:28:21.95 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 10.1.110.100:27017
mongodb 10:28:23.86 INFO  ==> Creating users...
mongodb 10:28:23.86 INFO  ==> Users created
mongodb 10:28:23.87 INFO  ==> Writing keyfile for replica set authentication...
mongodb 10:28:23.89 INFO  ==> Configuring MongoDB replica set...
mongodb 10:28:23.90 INFO  ==> Stopping MongoDB...
mongodb 10:28:27.23 INFO  ==> Trying to connect to MongoDB server mongodb-0.mongodb-headless.mongodb.svc.cluster.local...
mongodb 10:28:27.24 INFO  ==> Found MongoDB server listening at mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017 !
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.
MongoServerError: Authentication failed.

```

### Additional information

Very similar but not the same to #13744
So when I add an existing secret it does not work.

**Comment by CeliaGMqrz** [comment]
Hi @ricosega,

Thanks for reporting this issue. Just to be sure, Can you please provide which Kubernetes platform you are using? We have a similar issue and an internal task to debug this. [See](https://github.com/bitnami/charts/issues/17042#issuecomment-1625662875)

**Comment by aoterolorenzo** [comment]
Thank you @ricosega , 

Let's link to #17042 and wait for the team to address it

**Comment by Dennyfentow** [comment]
thanks to the last comment @ssyrota , I thought about the possibility of it being the length of my password in the MONGODB_PASSWORD env, reducing it from 21 to 12 characters and it solved it, even though it gave the error "MongoNetworkError: connect ECONNREFUSED 10.0.1.210:2701" in my docker swarm
