### ISSUE TITLE
[bitnami/rabbitmq] Ingress existingSecret doesn't work

### ISSUE THREAD

**Issue by br05s** [bitnami/charts#18005]
### Name and Version

bitnami/rabbitmq 12.0.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Unable to use an existing secret for ingress TLS.

### Are you using any custom parameters or values?

```yaml
ingress:
  enabled: true
  hostname: ***
  tls: true
  existingSecret: my-existing-secret
```

### What is the expected behavior?

It should not give that error and use the existing secret.

### What do you see instead?

>     You enabled the TLS configuration for the default ingress hostname but
>     you did not enable any of the available mechanisms to create the TLS secret
>     to be used by the Ingress Controller.
>     Please use any of these alternatives:
>       - Use the `ingress.extraTls` and `ingress.secrets` parameters to provide your custom TLS certificates.
>       - Rely on cert-manager to create it by setting the corresponding annotations
>       - Rely on Helm to create self-signed certificates by setting `ingress.selfSigned=true`

### Additional information

In line 201 of _helpers.tpl, it does not check if `ingress.existingSecret` is set.

**Comment by migruiz4** [comment]
Hi @br05s,

Thank you for reporting this issue.

I have submitted this PR fixing this issue: https://github.com/bitnami/charts/pull/18125
