### ISSUE TITLE
[bitnami/kube-prometheus]need option to set alertmanagerConfigMatcherStrategy

### ISSUE THREAD

**Issue by YiuTerran** [bitnami/charts#18016]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

Need option to set [alertmanagerConfigMatcherStrategy](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.AlertmanagerConfigMatcherStrategy)

### What is the feature you are proposing to solve the problem?

To resolve this [issue](https://github.com/prometheus-operator/prometheus-operator/issues/3737)

### What alternatives have you considered?

externalConfig or configuration

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by nshores** [comment]
+1 - I can take this over and submit a fix.

**Comment by nshores** [comment]
Please reopen this issue
