### ISSUE TITLE
Unable to override `managed-by` label via `commonLabels`

### ISSUE THREAD

**Issue by lindhe** [bitnami/charts#18025]
### Name and Version

bitnami/apache 10.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```console
$ helm template www oci://registry-1.docker.io/bitnamicharts/apache --version 10.0.0 --set 'commonLabels.app\.kubernetes\.io/managed-by=HALLOJ' --show-only templates/svc.yaml | head -n 15
Pulled: registry-1.docker.io/bitnamicharts/apache:10.0.0
Digest: sha256:3d66e53a16eb5c444161ee463a03806737e84b72e8077d8addb101b45e402311
---
# Source: apache/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: www-apache
  namespace: "default"
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-10.0.0
    app.kubernetes.io/instance: www
    app.kubernetes.io/managed-by: Helm  # 👈 Why is this still here?
    app.kubernetes.io/managed-by: HALLOJ
spec:
  type: LoadBalancer
```

### Are you using any custom parameters or values?

`--set 'commonLabels.app\.kubernetes\.io/managed-by=HALLOJ'`

### What is the expected behavior?

I expect to be able to override labels using `commonLabels`.

### What do you see instead?

I get duplicate labels.

**Comment by carrodher** [comment]
There are some labels that are fixed and inherited from the common library chart, see https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_labels.tpl.
Using the `commonLabels` parameter, you can add more labels to those standard/default ones, but there is not any logic to override them

**Comment by lindhe** [comment]
Alright.

1. I think that should be clarified in the documentation for the `customLabels`.
2. Is that a conscious design choice, or just it happened to become that way?
3. If it just happens to be so: should we modify this Issue so that it's clear that it's about `bitnami/common` not `bitnami/apache`?

**Comment by juan131** [comment]
You're welcome @lindhe ! 

Please note that, even the PR gets approved, I need to adapt every single chart in the repo in advance so they make use of the helpers following the new format. Therefore, it can take some time for the changes to be applied.

Sorry for the inconveniences.

**Comment by lindhe** [comment]
No :(
