### ISSUE TITLE
[bitnami/discourse] Discourse hangs on compiling

### ISSUE THREAD

**Issue by sonic-sw** [bitnami/charts#18026]
### Name and Version

bitnami/discourse:10.3.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Dear community,

i have an issue starting the discourse deployment.
The pod restarts after a while with this been the last debug log output.

```
yarn run v1.22.19
$ /opt/bitnami/discourse/app/assets/javascripts/node_modules/.bin/ember build -prod
WARNING: Node v18.17.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
- Building
- Building
Environment: production
- building...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

is there anythin I can do to proceed with the installation and help to overcome the startup?

### Are you using any custom parameters or values?

Yes but the same happens on plain startup without any additional vaules been set.

### What do you see instead?

The deployment restarts after a certain time and hangs at the same place. I would expect it to start into operational mode where I can access the webinterface.

**Comment by javsalgar** [comment]
Hi,

Is this happening on a fresh install? Which is the Kubernetes cluster you are using?

**Comment by sonic-sw** [comment]
Dear Javsalgar,

correct. Plain deployment of the helm chart and the cluster version is "1.26.5-gke.1400".

Attached the final log messages before the deployment restarts
![image](https://github.com/bitnami/charts/assets/124199772/4ea05101-221e-4edf-a3b9-467718555616)

**Comment by sonic-sw** [comment]
Dear Javsalgar,

my nodes are of GKE e2-medium (2c/4r) and are to slow for building the assets before been terminated by the probes.
I have disabled all (6) probes, example given

```
  livenessProbe:
    enabled: **true**
    initialDelaySeconds: 500
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
```

```
  livenessProbe:
    enabled: **false**
    initialDelaySeconds: 500
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
```

The total startup time for me was:
**10:46:53.33** ==> Precompiling assets, this may take some time...
**10:58:56.81** ==> ** Starting Discourse **

**Comment by joancafom** [comment]
Hi @sonic-sw 

Discourse needs to pre-compile the assets on the first run, which is a process that unfortunately can take up several minutes (the exact time varies on the cluster specs and the requirements granted to the pod). 

This is however only needed on the first run, when data is persisted and the DB is initialised. Subsequent deployments may skip this operation as long as (1) persistence is enabled, (2) database is properly populated and configured, and (3) the `skipInstall` option in values.yaml is provided; which may speed things up.

As the pre-compilation time largely varies on the cluster resources, you can adapt the liveness/readiness probes with the `initialDelaySeconds` to something more according to your use-case, granting an initial extra-time for the process to finish.

**Comment by sonic-sw** [comment]
Dear @joancafom ,
first of all thnak you for the support provided!.

> (1) persistence is enabled, (2) database is properly populated and configured, and (3) the skipInstall option in values.yaml is provided; which may speed things up.

(1) is enabled as per default helm value
(2) is enabled as per default helm value
(3) I tried and it has no affect of compiling the assets on boot. It seams only to affect the database migration script.

**Comment by joancafom** [comment]
Hi again!

Yes, you're right! I took a look and the `skipInstall` option is not directly related to the precompilation of the assets. There is another variable however to control this behaviour:

```yaml
discourse:
  extraEnvVars:
    - name: DISCOURSE_PRECOMPILE_ASSETS
      value: "false"
```

This will make the pod to skip the precompilation step 😁 . Again, assets needs to be compiled on the first run, so you should NOT disable it on a fresh installation. However, performing an upgrading using it speeds thing up as mentioned:

```console
$ helm install discourse bitnami/discourse
$ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
discourse-88b4b89c5-htlph   1/2     Running   0          2m47s
discourse-postgresql-0      1/1     Running   0          2m47s
discourse-redis-master-0    1/1     Running   0          2m47s

### Wait for pre-compilation and probes to mark the pod as ready... ###
$ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
discourse-88b4b89c5-htlph   2/2     Running   0          8m30s
discourse-postgresql-0      1/1     Running   0          8m30s
discourse-redis-master-0    1/1     Running   0          8m30s

### Upgrade the chart and disable pre-compilation ###
$ cat upgrade-values.yaml
discourse:
  skipInstall: false
  extraEnvVars:
    - name: DISCOURSE_PRECOMPILE_ASSETS
      value: "false"
persistence:
  existingClaim: "discourse"

$ helm upgrade discourse bitnami/discourse -f upgrade-values.yaml

### Pod is marked as ready much faster ###
$ kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
discourse-5dd45b7465-8s4mw   2/2     Running   0          4m26s
discourse-postgresql-0       1/1     Running   0          13m
discourse-redis-master-0     1/1     Running   0          4m25s
```

**Comment by sonic-sw** [comment]
@joancafom 

this works like a charm. Combined with skipInstall: true (as I use an external DB), the boot time gone down from 18m to 6m.
Thank you so much for your valuable support!
