### ISSUE TITLE
[bitnami/supabase] externalDatabase secret password key

### ISSUE THREAD

**Issue by Industrial** [bitnami/charts#18029]
### Name and Version

bitnami/supabase 0.3.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

supabase-auth shows the event `Error: couldn't find key postgres-password in Secret default/supabase-externaldb`.

When I look at the secret only one key has been defined (with the password) and it's named `db-password`, not `postgres-password`.

### Are you using any custom parameters or values?

```
postgresql.enabled=false
externalDatabase.host=postgresql-pgpool
externalDatabase.user=postgres
externalDatabase.password=postgres
externalDatabase.existingSecretPasswordKey=postgres-password
```

I tried changing the key to `postgres-password` but it didn't work.

### What is the expected behavior?

The key to be named the same for all services.

### What do you see instead?

`db-password`. Also doesn't use the `externalDatabase.existingSecretPasswordKey` value.

**Comment by aoterolorenzo** [comment]
Hi @Industrial,

Seems supabase is checking for the postgresql password in the `postgres-password` key, in Secret `supabase-externaldb`. Could you ensure you are providing that key?
