### ISSUE TITLE
bitnami/owncloud: Installation steps in readme are missing extra settings to install properly

### ISSUE THREAD

**Issue by Nadine2016** [bitnami/charts#1802]
**Which chart**:

owncloud, all versions

**Description**

The Helm chart readme installation steps are missing a bunch of extra settings that you need to do in order for owncloud to get installed properly in a cluster in IBM Cloud. Please see details in the attached word doc. 

**Steps to reproduce the issue:**

As described in the attached word doc

**Describe the results you received:**

owncloud coluld not be installed in a Kubernetes cluster on IBM Cloud

**Describe the results you expected:**

The Helm chart readme needs detailed steps for what to do to get owncloud installed in a cluster in IBM Cloud 

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version of Helm and Kubernetes**:

All versions

- Output of `kubectl version`:

1.12

**Comment by Nadine2016** [comment]
[Guide. How create OwnCloud on IBM Cloud.docx](https://github.com/bitnami/charts/files/4026847/Guide.How.create.OwnCloud.on.IBM.Cloud.docx)

**Comment by beltran-rubo** [comment]
Hi @Nadine2016 

Thanks for reporting it. Some of the applications require to configure a specific setting with the public URL that is only created after the solution has been deployed. As you added to the document, the Bitnami Chart shows the steps in the NOTES output to upgrade the solution properly.

We will work on a solution to make this information available for the user so they can see the process to upgrade the solution and configure the application properly.

**Comment by beltran-rubo** [comment]
Hi @Nadine2016, we added the steps to update the solutions that require to specify the IP address into the [IBM get started guide](https://docs.bitnami.com/kubernetes/get-started-charts-iks/#step-2-provide-an-external-host-for-your-application). 

This section is only required for some applications that needs to be upgraded with the external IP e.g. OwnCloud. All of those solutions shows the commands to be executed in the Schematic log. Let us know if you have any questions or suggestions.

**Comment by Nadine2016** [comment]
@beltran-rubo the guide looks great. Is there a way to link to it from the owncloud Helm chart? If a user wants to deploy it on IBM Cloud, they go to the IBM Cloud catalog. The Helm chart in there is the general one. But this guide would be much more helpful for the user. 

This is how it looks like: 
![image](https://user-images.githubusercontent.com/17709352/72286445-2918ef80-3613-11ea-875c-898457c42a66.png)

**Comment by beltran-rubo** [comment]
Hi @Nadine2016,

We plan to add the link to the get started guide just below the IBM paragraph. This guide is not only useful for ownCloud users but for any users that would like to deploy any Bitnami Helm Chart in IBM like WordPress or other apps that also require to execute "helm upgrade" commands:

```
ownCloud is a file sharing server that puts the control and security of your own data back into your hands.

In IBM Cloud™ you can configure your installation from the Create tab, and then install it with a single click instead of executing the Helm installation directly. Your Helm Chart is installed by using IBM Cloud Schematics, and after the installation is complete, you can view the Chart instance, update the version, or uninstall from your Schematics workspace. If you are installing an instance for a production configuration, review the considerations for adjusting the configuration parameters.

[This tutorial](LINK) will walk you, step by step, through the process of deploying Bitnami applications on a running IBM Cloud Kubernetes Service cluster. 
```

How that looks like for you?

**Comment by beltran-rubo** [comment]
We just added the following note into the README for all our solutions: "To learn how to deploy Bitnami applications in your IBM Cloud Kubernetes Service (IKS) cluster check out this step-by-step getting started guide." 

That will be added in the next version of the Charts automatically. Let us know if you have any suggestions.

**Comment by Nadine2016** [comment]
@beltran-rubo that sounds like a great plan and will work for us. I think the higher on that page that information is, the more visible it will be for the user. That would be my only suggestion for now. Thank you so much for updating the chart and working on these items so quickly!

**Comment by beltran-rubo** [comment]
You can see it is already added for solutions that have been already released e.g. Memcached. The next version of ownCloud will also include that link.
