### ISSUE TITLE
Unable to connect to Kafka Kraft broker on single Kubernetes node by using NodePort option 

### ISSUE THREAD

**Issue by igorkatz** [bitnami/charts#18034]
### Name and Version

bitnami/kafka: 22.1.3 and 23.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install kafka with helm on single k8s node

Snippet from `/opt/bitnami/kafka/config/kraft/server.properties` configuration file in kafka broker pod:
```
listeners=INTERNAL://:9094,CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
inter.broker.listener.name=INTERNAL
advertised.listeners=INTERNAL://kafka-0.kafka-headless.mi-kafka.svc.cluster.local:9094,CLIENT://kafka-0.kafka-headless.mi-kafka.svc.cluster.local:9092,EXTERNAL://172.21.181.166:30994
controller.listener.names=CONTROLLER
listener.security.protocol.map=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
```

2. run kafka client: 
`kubectl run --image=bitnami/kafka kafka-client  --command -- sleep infinity
`

### Are you using any custom parameters or values?

Change chart configuration as below:
```yaml
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: false
    service:
      type: NodePort 
      useHostIPs: true
      domain: ""
      nodePorts:
        - 30994
```

### What is the expected behavior?

Run following command from kafka-client pod and got following output:
```
kafka-topics.sh --bootstrap-server kafka-headless.mi-kafka:9092 –list
__consumer_offsets
mytopic
```
The below command uses client port. The same behavior is expected when external access port is used   

### What do you see instead?

Run following command from kafka-client pod and got following output:
```
kafka-topics.sh --bootstrap-server 172.21.181.166:30994 –list
[2023-07-31 08:40:09,487] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/172.21.181.166:30994) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```
This command uses external access port

### Additional information

The same configuration works on K8S cluster

**Comment by carrodher** [comment]
There is currently a major refactor of the kafka chart that should most of the issues related to Kraft mode, see https://github.com/bitnami/charts/pull/17507

**Comment by igorkatz** [comment]
I am familiar with number of problems in current kafka chart and I am waiting for this major refactoring. My questions:
1.	Will this refactor include a fix for my problem? The problem is very strange because this configuration works in cluster configuration and does not work with single Kubernetes node. I've checked a lot of other variations of this configuration. All of them don't work.
2.	What is your time estimation when this major refactoring will be ready?
