### ISSUE TITLE
[bitnami/harbor] Clair unhealthy after 3.0.10 install

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#1803]
**Which chart**: Harbor v3.0.10

After upgrading to the most recent version of the Harbor chart, I found that clair reports as unhealthy and triggers an "Internal Error" when I try to interact with it. I thought it was an issue with the upgrade, and tried a fresh install, but received the same problem.

**Steps to reproduce the issue:**

1. Install Harbor chart v3.0.10.

**Describe the results you received:**

Under Interrogation Services, Clair is listed as Unhealthy, and trying to interact with brings up an "Internal Server Error"

**Describe the results you expected:**

Clair to be healthy after installation.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
v2.14.1
```

- Output of `kubectl version`:

```
v1.16.3
```

**Comment by juan131** [comment]
Hi @ajchiarello 

Thanks for reporting it! The latest Harbor version requires a new container/component: The [Harbor Scanner Adapter for Clair](https://github.com/goharbor/harbor-scanner-clair)

We're currently working on creating the corresponding container and add it to our catalog. We'll notify about our progress!

**Comment by juan131** [comment]
Hi everyones

We just want to notify you that the new version of Harbor including Clair Adapter is now available. Please feel free to provide feedback about it. Thanks in advance.
