### ISSUE TITLE
[bitnami/kafka] Fresh installation with Kraft stuck in CrashLoopBackoff (caused by ReadinessProbe)

### ISSUE THREAD

**Issue by MisterTimn** [bitnami/charts#18056]
### Name and Version

bitnami/kafka:23.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On Kubernetes 1.26, install with values file added below (kraft enabled). The chart installs but goes into CrashLoopBackOff because of the ReadinessProbe failing.

When you disable the ReadinessProbe, the chart boots up properly, after which you can enable the probes again. Upgrades then go smoothly as well. This only affects first time setup.

### Are you using any custom parameters or values?

`values.yaml`
```yaml
global:
  storageClass: "ssd"
replicaCount: 3
kraft:
  clusterId: 6674b58e-5f8a-45a8-21e
```

### What is the expected behavior?

Healthy cluster startup

### What do you see instead?

All pods in CrashLoopBackOff, logs show repeating `UnknownHostExceptions` and Kraft messages as it fails to find a leader, as all pods remain Not Ready (and thus can't be connected through DNS).

**Comment by javsalgar** [comment]
Hi!

We're currently in a major refactor of the chart, this is the PR https://github.com/bitnami/charts/pull/17507

**Comment by SergkeiM** [comment]
> Hi!
> 
> We're currently in a major refactor of the chart, this is the PR #17507

Hi @javsalgar, thank you, there is an ETA for v24 release?
