### ISSUE TITLE
[bitnami/prometheus-operator] Chart not published

### ISSUE THREAD

**Issue by code-chris** [bitnami/charts#1806]
**Which chart**:
bitnami/prometheus-operator
0.7.6 and 0.8.0

**Description**
My PRs (#1767, #1782) are merged but the Chart is not published again for days. The newest published version is 0.7.5. Can anyone trigger the publish process again?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**
The new versions are published as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
3.0.2
```

- Output of `kubectl version`:

```
any
```

**Comment by juan131** [comment]
Hi @code-chris 

There was an issue in the **requirements.lock** (they weren't synchronised with **requirements.yaml**). I already fixed and triggered the release process so they index is updated in the bitnami/charts repo.

As you can see in the commands below, your changes are now available:

```console
$ helm repo update
$ helm search bitnami/prometheus-operator
NAME                       	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/prometheus-operator	0.8.0        	0.34.0     	The Prometheus Operator for Kubernetes provides easy moni...
```

**Comment by code-chris** [comment]
Ah, ok. Thanks!
