### ISSUE TITLE
bitnami/airflow initial deployment: Could not connect to the database

### ISSUE THREAD

**Issue by FunTimeCoding** [bitnami/charts#18066]
### Name and Version

bitnami/airflow 14.3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm downloading the helm chart like this:
```
helm fetch --untar --untardir tmp --version "${CHART_VERSION}" bitnami/airflow
helm template \
  --output-dir base \
  --namespace "${NAMESPACE}" \
  --values "${TEAM_VALUES}" \
  airflow tmp/airflow
```
Then I deploy it to a Kubernetes cluster using ArgoCD and kustomization.
The `values.yaml` is untouched, so it generates normal secrets.
When observing the namespace, I see this in the worker, web and scheduler containers:
```
airflow 16:14:44.54 INFO  ==> Trying to connect to the database server
airflow 16:16:01.47 ERROR ==> Could not connect to the database
```
(more detailed log below)

The database `airflow-postgresql-0` seems to be started correctly because I can `kubectl exec` into it to run `psql`, and I also ran a separate `bitnami/postgresql` container with `kubectl run`, overriding its entrypoint with bash, and using `psql` with the credentials.
I can successfully connect to the postgres server, but the database seems empty when trying `select * from public.ab_user;`

I found this which seems related, but the solution the person chose was to go with a different chart: https://stackoverflow.com/questions/72159704/bitnami-airflow-scheduler-could-not-connect-database-while-webserve-can-connect

I'd prefer to use this bitnami/airflow chart since it appears simpler than the others.

### What is the expected behavior?

I expect the airflow deployment to start correctly so I can see all containers healthy and begin using the frontend.

### What do you see instead?

In the log of the worker, web and scheduler, I see:
```
airflow 15:42:30.89
airflow 15:42:30.90 Welcome to the Bitnami airflow container
airflow 15:42:30.90 Subscribe to project updates by watching https://github.com/bitnami/containers
airflow 15:42:30.90 Submit issues and feature requests at https://github.com/bitnami/containers/issues
airflow 15:42:30.90
airflow 15:42:30.91 INFO  ==> Enabling non-root system user with nss_wrapper
airflow 15:42:30.92 INFO  ==> ** Starting Airflow setup **
airflow 15:42:30.94 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
airflow 15:42:30.99 INFO  ==> Initializing Airflow ...
airflow 15:42:31.01 INFO  ==> No injected configuration file found. Creating default config file
airflow 15:42:32.42 INFO  ==> Configuring Airflow webserver authentication
airflow 15:42:32.46 INFO  ==> Configuring Airflow database
airflow 15:42:32.52 INFO  ==> Configuring Celery Executor
airflow 15:42:32.55 INFO  ==> Trying to connect to the database server
airflow 15:43:49.61 ERROR ==> Could not connect to the database
```

**Comment by carrodher** [comment]
Just to discard any issue related to the tools used to deploy the Helm chart, are you able to reproduce the issue by simply running the following command?
```
helm install my-airflow oci://registry-1.docker.io/bitnamicharts/airflow
```

**Comment by FunTimeCoding** [comment]
Apologies for my late reply. I did manage to use the normal helm install way now. It appears stuck on the same step, however, I also noticed a new log message in the airflow-worker container:
```
airflow-worker 09:01:23.26 INFO  ==> Waiting for Airflow Webserver to be up
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
```
I know this seems kinda obvious that something is timing out, but maybe this points at where this is coming from.

**Comment by FunTimeCoding** [comment]
I went and diffed both the stuck and the working namespace like `kubectl get all --namespace=areitzel-airflow -o yaml > areitzel-airflow.yaml` and I notice a difference besides the instance hashes and limits I introduced on the other side, see the attached images.

![postgres-postgres-password](https://github.com/bitnami/charts/assets/1647065/fc37d847-c1ee-4fce-bffe-fefc333b8484)
![airflow-database-password](https://github.com/bitnami/charts/assets/1647065/0e94c271-a4b3-464d-89ad-8a1f0d02db51)

This could be the culprit. Is this happening because in my values.yaml I have `postgresql.auth.password` left default (empty string)?

**Comment by fmulero** [comment]
Sorry @FunTimeCoding I think I missed something. According to the screenshots it seems you are not setting `postgresql.auth.enablePostgresUser` or you explicitly disabled the postgresql subchart, but you said you left the default values. I am also don't fully understand the process you followed, it seems you downloaded the chart, ran `helm template` with some values (`${TEAM_VALUES}`) and yaml files resulted are deployed using ArgCD. Please amend me if I am wrong.

Could you share the values you are setting?

NOTE: Please be careful with `helm template` some functions (like [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function)) could not have the expected result.

**Comment by FunTimeCoding** [comment]
You are right. I downloaded a clean values.yaml from version 14.3.5 again, which showed that in the diff. The values.yaml is entirely default at this point, and I recreated the deployment. Now it works, thank you for your patience.
