### ISSUE TITLE
quota-backend-bytesSettings still invalid failed to commit proposal: Active Alarm(s): NOSPACE 

### ISSUE THREAD

**Issue by jinjianming** [bitnami/charts#18073]
### Name and Version

3.5.4-debian-11-r14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

![image](https://github.com/bitnami/charts/assets/57084209/0966d15c-d8f9-4b29-b2bd-e6fedfa9efbe)

### Are you using any custom parameters or values?

etcd --quota-backend-bytes 8000000000 --max-request-bytes 10485760 --auto-compaction-retention 1m --auto-compaction-mode periodic

### What is the expected behavior?

Breaking through 2G limitations

### What do you see instead?

Breaking through 2G limitations

**Comment by carrodher** [comment]
Could you please provide more info about how are you deploying this Helm chart? It would be really useful to have the exact command you're running as well as the parameters/values you're using

**Comment by jinjianming** [comment]
After increasing the quota backup bytes, does the cluster still refuse to write?

The reason is the NO SPACE alarm. The Apply module checks every command it executes

Check if there is currently a NO SPACE alarm, and if so, refuse to write. So we also need you to send an additional cancellation notice

The command of 'etcdctl alarm disarm' is used to eliminate all alarms and ensure that the cluster is functioning normally

**Comment by jinjianming** [comment]
@carrodher hello
           Also, I would like to ask if there are any best practices for optimizing ETCD, including but not limited to，quota-backend-bytes，auto-compaction等.....
[etcd-limit](https://etcd.io/docs/v3.3/dev-guide/limit/)
[auto-compaction](https://etcd.io/docs/v3.5/op-guide/maintenance/#auto-compaction)

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
