### ISSUE TITLE
[bitnami/airflow] Clone DAGs from repo subdirectory

### ISSUE THREAD

**Issue by chgl** [bitnami/charts#1809]
**Which chart**:

bitnami/airflow 4.0.20

**Description**

**Steps to reproduce the issue:**

1. Create a git repo where the dags are stored in a subdirectory within the repo
2. Configure `airflow.cloneDagFilesFromGit`
3. Install the chart and view the airflow ui

**Describe the results you received:**

The dags do not appear in the airflow ui.

**Describe the results you expected:**

The dags appear in the airflow ui.

**Additional information you deem important (e.g. issue happens only occasionally):**

A solution may be to add a configurable sub-directory to `mountPath` (https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/deployment-web.yaml#L58-L60). I'd be interested in working on this.

**Comment by andresbono** [comment]
Hi @chgl, it sounds like an interesting feature to support.

> A solution may be to add a configurable sub-directory to mountPath (https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/deployment-web.yaml#L58-L60). I'd be interested in working on this.

Please feel free to open a PR. Contributions are more than welcome!
