### ISSUE TITLE
What is the difference between this and the operator?

### ISSUE THREAD

**Issue by jadencodes** [bitnami/charts#1810]
**Which chart**:

Etcd Latest

**Description**

We have been attempting to use the operator that handles Etcd via a kubernetes CRD from the helm stable repo [here](https://github.com/helm/charts/tree/master/stable/etcd-operator). However, there are lots of oddities that seem to happen especially when running locally. Further, the project itself hasn't had updates in months. I stumbled upon this chart and am wondering how/why people would use this vs the operator.

The operator uses deployments and local storage with the operator to handle reconciling vs this uses statefulsets with stable storage. 

Is there a reason this would be more or less stable than the operator? This seems far simpler and a statefulset seems more correct to use so given the choice I would pick the bitnami chart (and seems to have more metrics support).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
2.12
```

- Output of `kubectl version`:

```
1.14/1.15
```

**Comment by juan131** [comment]
Hi @jadencodes 

The main difference is that the obvious one: this is a simply a Helm chart. Therefore, **it doesn't aim to manage the lifecycle of the application** (etcd in this case) as an operator would do. Its main purpose is to provide a way to package/distribute/install etcd on K8s.

That said, we implemented some mechanisms on this chart (check `disasterRecovery.enabled` and `startFromSnapshot.enabled` parameters) to add some basic mechanisms to avoid losing data. These mechanisms could be considered as a way to manage the lifecycle of etcd but they're quite basic. Find more info in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/etcd#disaster-recovery

Regarding its stability, we've being improving the logic for these mechanisms, as well as providing ways to perform non-disruptive upgrades. We do our best to make it as close to production-ready as possible. We depend on you (users) to provide feedback, report issues and contribute with PRs, so we keep improving it. I'm confident that together we can have a pretty stable chart.

**Comment by jadencodes** [comment]
Thank you @juan131. That makes plenty of sense; this seems far simpler to use and manage than the operator while providing close to feature parity.
