### ISSUE TITLE
[charts/upstreamed/postgresql] unable to upgrade from 10.5 to 11.6.0

### ISSUE THREAD

**Issue by madhupnvl** [bitnami/charts#1813]
Hi Team,

We tried to upgrade to 11.6 from 10.5, but facing problem like incompatible PV.Unable to reclaim the PV of 10.5. 

The PV defined in helm charts was unable to reclaim after upgraded into 11.6
(postgresqlDataDir: /bitnami/postgresql/data, mountPath: /bitnami/postgresql are same but still).

Thank you,
Madhu

**Comment by juan131** [comment]
Hi @madhupnvl 

Could you share the exact command you used to install & upgrade your release? I'd like to reproduce the issue using the same commands. Thanks in advance.

**Comment by madhupnvl** [comment]
hi @juan131,

Please took the old 10.5 helm charts of postgresql https://github.com/bitnami/charts/tree/2efda1ee8464d9b203cd84c86b940c4d998ed8b9/upstreamed/postgresql , Create some test data in it. now down it.
commands i used, 
helm install --name my-release -f ./values-production.yaml postgresql
helm del --purge <name>


Now please take the latest Postgresql charts https://github.com/bitnami/charts/tree/master/upstreamed/postgresql 
Use the same commands.

It is unable to pair the same persistent volume. Above created test data is not available.

**Comment by juan131** [comment]
Hi @madhupnvl 

You're trying to upgrade from version `2.0.0` of the chart to version `8.1.3`. In other words, there were **6 major versions** of the chart during that period!! The chart was widely transformed during that period.

The compatibility for upgrading between versions is only guaranteed **between minor/patch versions**. We also provide instructions to upgrade between major versions in the section below:

- https://github.com/bitnami/charts/tree/master/upstreamed/postgresql#upgrade

 The only I think you can migrate your postgresql release is doing it major by major. In other words:

- Upgrade from `2.0.0` to `3.0.0` following the upgrade instructions I shared in the previous link.
- Then, upgrade from `3.0.0` to `4.0.0`.
- etc, etc.

Another alternative is to create a dump of your PostgreSQL data. Then, you can install the latest PostgreSQL chart and import your data in the new installation.

**Comment by madhupnvl** [comment]
Hi @juan131,

I refereed the steps which you given in https://github.com/bitnami/charts/tree/master/upstreamed/postgresql#200. But it is not working out.

Pod it self not starting up, due to the error "Don't have permissions to /bitnami/postgresql/data"

**Comment by juan131** [comment]
Hi @madhupnvl 

Did you try the alternative I mentioned about dumping the data?

- You just need to install a new PostgreSQL in your cluster using the latest chart version. 
- Then, you can dump the data from your old PostgreSQL, and import it in the new one.
- Once you ensure everything is working fine in the new PostgreSQL, you can remove the old one.

**Comment by madhupnvl** [comment]
Go to container shell and follow below steps
1. Take the back up from the container `pg_dumpall  -h <Container_name>-U postgres > /tmp/backup.sql`
2. Copy file to your local using `kubectl cp`
3. Stop old services and start new services
4. move the file to new container using `kubectl cp`
5. restore using `psql -U postgres < /tmp/backup.sql`
