### ISSUE TITLE
charts.bitnami.com/bitnami is failing to resolve

### ISSUE THREAD

**Issue by hari-boddapati-hpe** [bitnami/charts#18133]
### Name and Version

https://charts.bitnami.com/bitnami

### What steps will reproduce the bug?

1. RUN `helm repo add bitnami https://charts.bitnami.com/bitnami ` (In DockerFile) and tried with recent helm image as well: helm:3.12.2

### What is the expected behavior?

Repo added "bitnami"

### What do you see instead?
```
RUN helm repo add bitnami https://charts.bitnami.com/bitnami
#8 sha256:451c291c613a4e2f739dd33d3eedb167f31eae2d16c1a188bd1b501bc0ec7add
#8 0.743 Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml": tls: failed to verify certificate: x509: certificate signed by unknown authority
#8 ERROR: process "/bin/sh -c helm repo add bitnami https://charts.bitnami.com/bitnami" did not complete successfully: exit code: 1
```

**Comment by carrodher** [comment]
We received in the past a couple of comments from users with similar issues. It seems related to an issue in Helm itself, see https://github.com/helm/helm/pull/9318

Currently, the default method to fetch Bitnami charts is using the [Bitnami DockerHub OCI repository](https://hub.docker.com/u/bitnamicharts), and given that OCI is supported out of the box in [Helm 3.8.0](https://github.com/helm/helm/releases/tag/v3.8.0), could you try using OCI? [Here](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html) you can find more information about this topic

**Comment by hari-boddapati-hpe** [comment]
the above suggestion worked! Thanks @carrodher!!
