### ISSUE TITLE
Mismatch between grafana CRD specification and implementation in grafana-operator 3.0.0 chart

### ISSUE THREAD

**Issue by pcperera** [bitnami/charts#18136]
### Name and Version

bitnami/grafana-operator-3.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In the Grafana CRD implementation (1), it has `annotations` directly under `deployment`. In the Grafana CRD specification (2), it has `annotations` under `deployment/metadata`.

ArgoCD was of course not happy with (1) as it couldn't recognize and validate the fields with the CRD specification. This appeared to be the csae for `envFrom` field too.

1. https://github.com/bitnami/charts/blob/1711ba88107d9b7d540f570c5c5e6d2316e9b4e2/bitnami/grafana-operator/templates/grafana.yaml#L90-L95
2. https://github.com/bitnami/charts/blob/1711ba88107d9b7d540f570c5c5e6d2316e9b4e2/bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml#L59-L71

![image](https://github.com/bitnami/charts/assets/15628990/dbd6f6f8-4eb1-40ad-8b96-16a476d40c67)
![image](https://github.com/bitnami/charts/assets/15628990/92d5e4bb-a4e5-4802-9383-f5a637c8f3bd)

### What is the expected behavior?

Grafana CRD specification and implementation to be consistent.

### What do you see instead?

Observing a mismatch between the CRD specification and implementation.

ArgoCD is unable to recognize the corresponding fields defined.

![image](https://github.com/bitnami/charts/assets/15628990/77e08845-b56f-47a9-b5e0-a484c62c7955)

**Comment by carrodher** [comment]
Thanks for creating this issue. It was already reported by other users, see for example https://github.com/bitnami/charts/issues/17863. In that issue, there are some PRs linked addressing this topic.
I'm closing this issue as duplicated
