### ISSUE TITLE
[bitnami/apisix] did not find expected key

### ISSUE THREAD

**Issue by markeee-e** [bitnami/charts#18152]
### Name and Version

bitnami/apisix 2.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

dataplane, dashboard ingress is working
but, controlplane ingress is not working

### Are you using any custom parameters or values?

  --set controlPlane.ingress.enabled=true \
  --set controlPlane.ingress.hostname="hubble-dev-api-admin-mk.arc.hcloud.io" \
  --set controlPlane.ingress.tls=true \
  --set controlPlane.ingress.path="/" \

### What do you see instead?

Error: YAML parse error on apisix/templates/control-plane/ingress.yaml: error converting YAML to JSON: yaml: line 23: did not find expected key

Use --debug flag to render out invalid YAML

### Additional information

below is results of template --debug
`Error: YAML parse error on apisix/templates/control-plane/ingress.yaml: error converting YAML to JSON: yaml: line 23: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 23: did not find expected key
YAML parse error on apisix/templates/control-plane/ingress.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:170
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:289
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:287
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:88
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_arm64.s:1172`

**Comment by FraPazGal** [comment]
Thanks for reporting this @markeee-e! I have created https://github.com/bitnami/charts/pull/18255 to address this.
