### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Nabeel-Akhtar-Qbatch** [bitnami/charts#18150]
### Name and Version

bitnami/postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?
```
helm install postgresql bitnami/postgresql --set postgresqlPassword=postgres -n psql
```
### What do you see instead?
```
FATAL:  password authentication failed for user "postgres"
```

**Comment by Nabeel-Akhtar-Qbatch** [comment]
Hi @carrodher please help me out with it

**Comment by carrodher** [comment]
Are you deploying the Helm chart from scratch or reusing the same name and namespace from a previous deployment? This can be produced by a mismatch between the password stored in the PV/PVC from previous deployments and the password set in this one.

**Comment by Nabeel-Akhtar-Qbatch** [comment]
It is solved, my bad I was creating new PV's on the same path.
