### ISSUE TITLE
[bitnami/cassandra] for production/demo Unable to lock JVM memory

### ISSUE THREAD

**Issue by devopsdymyr** [bitnami/charts#1816]
**Which chart**:

[bitnami/cassandra]

**Description**

I have created my demo environment cassandra cluster with productiob values.yaml with modification of Core: 4 and RAm: 5Gb

https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values-production.yaml

```Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root
```

I have seen message in the pod getting 

```
jemalloc seems to be preloaded from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
WARN  [main] 2020-01-10 03:50:30,854 StartupChecks.java:169 - JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
INFO  [main] 2020-01-10 03:50:30,856 SigarLibrary.java:44 - Initializing SIGAR library
INFO  [main] 2020-01-10 03:50:30,880 SigarLibrary.java:180 - Checked OS settings and found them configured for optimal performance.
WARN  [main] 2020-01-10 03:50:30,888 StartupChecks.java:311 - Maximum number of memory map areas per process (vm.max_map_count) 262144 is too low, recommended value: 1048575, you can change it with sysctl.
 Maximum number of memory map areas per process (vm.max_map_count) 262144 is too low, recommended value: 1048575, you can change it with sysctl.
 Global buffer pool is enabled, when pool is exhausted (max is 512.000MiB) it will allocate on heap
Not submitting build tasks for views in keyspace system_traces as storage service is not initialized
```

**Steps to reproduce the issue:**

1. clone bitnami/cassandra repo in local and replace production-values.yaml to values.yml 
2. modifi core 4 and RAm 5Gb
3. install helm chart and check logs

**Describe the results you received:**

I have tested this for our demo environment but due to more load on the cluster is restarted.

30mits maximum cassandra read request will be 1 Lakh

Can you suggest me which configuration will work for this cluster.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: v2.16.1+gbbdfe5e
Server: v2.16.1+gbbdfe5e
```

- Output of `kubectl version`:

```
Client Version: v1.17.0
Server Version: v1.14.8
```

**Comment by carrodher** [comment]
Hi, I am not a Cassandra expert, but it seems that when you require more than a certain value for the RAM, the application needs the `vm.max_map_count` option *in the kernel cluster* set to a specific value. You can modify it by running as root the following command:
```
sysctl -w vm.max_map_count=1048575
```
but please, take into account that this action is performed in the kernel cluster itself, modifying this option for the whole cluster.

**Comment by devopsdymyr** [comment]
Can you give me some more details on this for kubernetes cluster

**Comment by carrodher** [comment]
It is a kernel setting that has a default value, but some applications need a higher value. According to the official doc (https://www.kernel.org/doc/Documentation/sysctl/vm.txt):

> ==============================================================
> 
> max_map_count:
> 
> This file contains the maximum number of memory map areas a process
> may have. Memory map areas are used as a side-effect of calling
> malloc, directly by mmap, mprotect, and madvise, and also when loading
> shared libraries.
> 
> While most applications need less than a thousand maps, certain
> programs, particularly malloc debuggers, may consume lots of them,
> e.g., up to one or two maps per allocation.
> 
> The default value is 65536.
> 
> =============================================================

**Comment by devopsdymyr** [comment]
Thanks for this i will try to this max_map_count
