### ISSUE TITLE
[bitnami/kafka-kraft] Need to configure min.insync.replicas 

### ISSUE THREAD

**Issue by subhadeepnemesis** [bitnami/charts#18169]
### Name and Version

bitnami/kafka 23.0.7

### What is the problem this feature will solve?

There's a way to mention min.insync.replicas for the transaction topics which we can notice here, https://github.com/bitnami/charts/blob/5c73193c9e3481ef4fc794d355348ff718e0b5dc/bitnami/kafka/values.yaml#L191C1-L192C1
Can we have a way to configure min.insync.replicas via helm values.
While configuring with Kraft-mode kafka, I have noticed that using config, we can't configure kraft mode kafka. But, if we put via helm values, then kraft-mode kafka is up & running smoothly. Now, the issue is - there's no such option to configure min.insync.replicas via helm values.

### What is the feature you are proposing to solve the problem?

Could you please consider introducing a way to configure min.insync.replicas using helm values?

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
