### ISSUE TITLE
[bitnami/supabase] GraphQL did not work 

### ISSUE THREAD

**Issue by stevefan1999-personal** [bitnami/charts#18181]
### Name and Version

bitnami/supabase:0.3.14

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy
2. Use GraphiQL in API tab

### What is the expected behavior?

Introspection query works

### What do you see instead?

Internal server error

**Comment by stevefan1999-personal** [comment]
Confirmed when both #18182 and #18183 are done could solve this

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting, I will mark this as on-hold.
