### ISSUE TITLE
[bitnami/supabase] PostgREST schema introspection did not work

### ISSUE THREAD

**Issue by stevefan1999-personal** [bitnami/charts#18183]
### Name and Version

bitnami/supabase:0.3.14

### What architecture are you using?

None

### What steps will reproduce the bug?

1.  Deploy
2.  Use GraphQL introspection

### What is the expected behavior?

It should just works. However until #18182 is solved, this would be useless for a while,

### What do you see instead?

Schema reflection is unavailable:

```json
{
    "code": "PGRST106",
    "details": null,
    "hint": null,
    "message": "The schema must be one of the following: public, storage"
}
```

### Additional information

This is because of  
https://github.com/bitnami/charts/blob/7910625e34129d7270254310c26a38d3ee245adf/bitnami/supabase/values.yaml#L1259-L1263

Instead, it should be:

```
PGRST_DB_SCHEMAS: "public,storage,graphql_public"
```

Reference: https://supabase.com/docs/guides/cli/config#api.schemas

**Comment by javsalgar** [comment]
Hi!

Thank you for opening the ticket. Marking this one as on-hold waiting for the others to be fixed
