### ISSUE TITLE
Help for airflow installation without helm on K8s cluster

### ISSUE THREAD

**Issue by anirudhkm** [bitnami/charts#1818]
Hi,

I am trying to install airflow on k8s cluster to leverage the Kubernetes executor, but I do not want to take the helm route. The reason is because our k8s clusters doesn't support helm. Can you please help us with a workaround for this.

Installing helm is going to be really challenging because our team does not have the privilege to make installations on clusters.

**Comment by alemorcuq** [comment]
Hi, @anirudhkm 

Is Helm 3 a possibility for your use case? Helm 3 doesn't rely on Tiller so you don't have to install anything on the cluster. You can read more about the changes here: https://helm.sh/docs/faq/

Another possibility would be to render the template files locally with `helm template` and then apply them with `kubectl apply`. 

Let me know if this would work for you.

**Comment by anirudhkm** [comment]
Hi @alemorcuq, thanks I think I got it to work.. Appreciate your suggestions!!

**Comment by alemorcuq** [comment]
Awesome, @anirudhkm ! Let us know if you find any issues.
