### ISSUE TITLE
[bitnami/redis] Redis sentinel mode not working with istio

### ISSUE THREAD

**Issue by haloxinyu** [bitnami/charts#18195]
### Name and Version

bitmami/redis 17.4.5

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Enable istio-injection
2. Create redis in sentinel mode with default configuration
3. All three pods are started, but each of them is configured as a master node

### What is the expected behavior?

reids started and only the first pod was configured as a master node.

### What do you see instead?

**The log of the first pod:**
```
03:33:44.83 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 200 redis-cli -h my-redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at my-redis.redis.svc.cluster.local:26379: Name or service not known
 03:33:44.84 INFO  ==> Configuring the node as master
1:C 04 Aug 2023 03:33:44.858 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Aug 2023 03:33:44.858 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 Aug 2023 03:33:44.858 # Configuration loaded
```

**The log of the second pod:**
```
03:34:07.77 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 200 redis-cli -h my-redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at my-redis.redis.svc.cluster.local:26379: Connection refused
 03:34:07.78 INFO  ==> Configuring the node as master
1:C 04 Aug 2023 03:34:07.811 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Aug 2023 03:34:07.811 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 Aug 2023 03:34:07.811 # Configuration loaded
```

**The log of the third pod**
```
03:34:33.44 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 200 redis-cli -h my-redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at my-redis.redis.svc.cluster.local:26379: Connection refused
 03:34:33.46 INFO  ==> Configuring the node as master
1:C 04 Aug 2023 03:34:33.480 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Aug 2023 03:34:33.480 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 Aug 2023 03:34:33.480 # Configuration loaded
```

### Additional information

This happens because istio-proxy sidecar container takes some seconds to be ready, but redis start-node shell and start-sentinel shell try to connect redis svc to get master addres before istio-proxy container ready which will fail and that's why we get the message "Could not connect to Redis at my-redis.redis.svc.cluster.local:26379: Connection refused" The final result is that each node cannot get the master address, so all of them will be configured as the master node.

I think it may not be complicated to solve the issue. Adding a retry mechanism to get master address with limited number and interval may work, something like
retry_while "get master address" 2 1

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket! We do not have explict support for Istio as we don't test our charts with it. However, if you mention that there is a possible workaround using `retry_while`, would you like to submit a PR fixing the issue?

**Comment by haloxinyu** [comment]
Ok, will submit a PR later
