### ISSUE TITLE
Cluster doesn't come back after node shutdown

### ISSUE THREAD

**Issue by eilmrein** [bitnami/charts#1819]
**Which chart**:
mariadb-galera 0.6.1

**Description**

I changed a few values when installing as I want to access the cluster from outside and I only have two nodes (n01 & n03 are my worker nodes) availabe:
```yaml
service:
  type: NodePort
  port: 3306
  nodePort: 32566
galera:
  name: galera01
replicaCount: 2
```
**Steps to reproduce the issue:**
Installed the cluster
1. Restored an ampache db into the cluster and created the user for ampache
2. Shut down n01 - everything ok
3. Started n01 - still ok - modified data OK too
4. Shut down n03 - still ok 
5. Started n03 - Failing

**Describe the results you received:**
```
kubectl logs galera01-mariadb-galera-1 returns
...
2020-01-10 10:16:44 0 [Note] WSREP: view(view_id(NON_PRIM,4addb30c,30) memb {
	4addb30c,0
	f4fc9eee,0
} joined {
} left {
} partitioned {
	09dac7cb,0
	0ebd8905,0
	1d2c5595,0
	35d1a1a7,0
	3809e171,0
	437230b2,0
	559b8353,0
	701c05f8,0
	825415a2,0
	9fe19afa,0
	c9e23bfd,0
	d7034442,0
})
2020-01-10 10:17:11 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	 at gcomm/src/pc.cpp:connect():158
2020-01-10 10:17:11 0 [ERROR] WSREP: gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -110 (Connection timed out)
2020-01-10 10:17:11 0 [ERROR] WSREP: gcs/src/gcs.cpp:gcs_open():1608: Failed to open channel 'galera01' at 'gcomm://galera01-mariadb-galera-headless.default.svc.cluster.local': -110 (Connection timed out)
2020-01-10 10:17:11 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2020-01-10 10:17:11 0 [ERROR] WSREP: wsrep::connect(gcomm://galera01-mariadb-galera-headless.default.svc.cluster.local) failed: 7
2020-01-10 10:17:11 0 [ERROR] Aborting
```
Pod on n03 does not start anymore with the error above

**Describe the results you expected:**
Pod on n03 should have started and rolled forward to the state of the one on n01

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
- Output of `kubectl version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
eilmrein@n00:~/k8s-ops/galera$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. It seems there's a connection timeout issue. Could you execute this command to ensure that the service is pointing to a pod?

```
kubectl get endpoints
```

Please share the output.

**Comment by eilmrein** [comment]
Miracle resolved: I had three pvs for 2 nodes and the starting node claimed the third pv not containing any data, so it wouldn't come up.
This triggers another question though: How do I scale up a galera cluster?

**Comment by javsalgar** [comment]
Hi,

Did you try with 

```
$ kubectl scale sts my-release-mariadb-galera --replicas=YOUR_DESIRED_ONES
```

**Comment by eilmrein** [comment]
Yes, I tried this,
however, this lead to permanent restarting of the new pod. I created a new
pv, so it would have a datastore.
Kind regards,
Reinhard

Am Mo., 20. Jan. 2020 um 12:56 Uhr schrieb Javier J. Salmerón-García <
notifications@github.com>:

**Comment by javsalgar** [comment]
Does it mean that you have to manually create the PVs? Didn't you have any dynamic provisioner enabled?

**Comment by eilmrein** [comment]
Hey Javier,

I'm really new to k8s, so yes, created the pv manually. I like to learn how
things work before I automate stuff. ;-)

R,R

Am Mittwoch, 22. Januar 2020 schrieb Javier J. Salmerón-García <
notifications@github.com>:
> Does it mean that you have to manually create the PVs? Didn't you have
any dynamic provisioner enabled?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/YmVwYgTlwBElBHvszNhtdaBCURAhy_hgxEmnEigWTirfKDD2ktNH2ni9ddQKdR9DRd6qWk8phm-fA0EV2IAuiVa4OAQn7N50Vk5iaX01vHOGfURV_oUmoU05NJZ5CbLRqJzb4fQTz5v2ENldaITtQn5JNwb0yJOFLAr0gOIyv4Tb95VrHq2ISvsqt8UvIoPzui6Uv6CG5Yq_qo5AD1Pm3Yb8D5Ra97rIM5Dkew0ixA=s0-d-e1-ft#https://github.com/notifications/beacon/AODU6HVMAHI6PFTUOFPJCO3Q7BKBBA5CNFSM4KFFVFCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJTX2MY.gif>

**Comment by javsalgar** [comment]
In order to allow scaling of your solution, it is essential to ensure that PVs are created as well. So, in order to scale your cluster the recommended approach is to have a volume dynamic provisioner. Otherwise you'll need to create manually all the PVs prior to scaling.
