### ISSUE TITLE
Running multiple kafka replica's fails with external advertised_listener 

### ISSUE THREAD

**Issue by michaeldebouver** [bitnami/charts#1820]
# Which chart:

name: kafka
chart: bitnami/kafka
version: 7.0.2

# Description
After installing the helm chart for kafka using 3 replicacounts, the 2nd and 3rd containers crash due to the following reason:
```
java.lang.IllegalArgumentException: requirement failed: Configured end points <external_IP>:<report> in advertised listeners are already registered by broker 1001
```
# Steps to reproduce the issue:
```
helm install -n "kf" bitnami/kafka -f helm/kf_values.yaml
```
where `kf_value.yaml`:
```yaml
---
advertisedListeners: 192.168.1.1:32500

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
  type: NodePort
  port: 32500

  ## Specify the NodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: 32500

  ## Use loadBalancerIP to request a specific static IP,
  # loadBalancerIP: 

  ## Service annotations done as key:value pairs
  annotations: {}

zookeeper:
  replicaCount: 3
replicaCount: 3
```
# Describe the results you received:

The first container starts fine.
The 2nd and 3rd container crash with the following error:
```
[2020-01-10 12:33:36,103] ERROR [KafkaServer id=1013] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.IllegalArgumentException: requirement failed: Configured end points 192.168.1.1:32500 in advertised listeners are already registered by broker 1001
at scala.Predef$.require(Predef.scala:224)
at kafka.server.KafkaServer$$anonfun$createBrokerInfo$2.apply(KafkaServer.scala:399)
at kafka.server.KafkaServer$$anonfun$createBrokerInfo$2.apply(KafkaServer.scala:397)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at kafka.server.KafkaServer.createBrokerInfo(KafkaServer.scala:397)
at kafka.server.KafkaServer.startup(KafkaServer.scala:261)
at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
at kafka.Kafka$.main(Kafka.scala:84)
at kafka.Kafka.main(Kafka.scala)
```

# Version of Helm and Kubernetes:

--

Output of helm version:
v2.10.0-rancher11

Output of kubectl version:
1.14.6

**Comment by carrodher** [comment]
In the Kafka container README, we have a section about [“Accessing Kafka with internal and external clients”](https://github.com/bitnami/bitnami-docker-kafka#accessing-kafka-with-internal-and-external-clients), the examples are oriented to docker-compose but a similar approach should be able to be applied into the chart.

In the chart there is a parameter `allowPlaintextListener` enabled using the default _values.yaml_, in the same way, there is another parameter `extraEnvVars` to add environment variables to Kafka pods. Not sure if this is the path we should follow but it is what I found in the first brief research.

We will continue investigating it and adding more info. Thanks

**Comment by Psc1234** [comment]
I have been installing kafka on k8s using bitnami kafka helm. Since I want to access kafka from external window machine, so I have set :
advertisedListeners: [INTERNAL://:9093,CLIENT://:9092,EXTERNAL://{ Public IP }:9094] in kafka values.yaml file and I started to get this issue in kafka broker pod log. 

Only one pod is running and rest are failing with error:
java.lang.IllegalArgumentException: requirement failed: Configured end points { Public IP }:9094 in advertised listeners are already registered by broker-0.

Could you please help me to resolve this issue? What exactly I need to do to resolve this issue?
