### ISSUE TITLE
[bitnami/clickhouse] upgrade broken because of immutable fields

### ISSUE THREAD

**Issue by cberge908** [bitnami/charts#18215]
### Name and Version

bitnami/clickhouse 3.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install clickhouse with an older chart version and default values (e.g. 3.1.1)
2. Upgrade to the latest chart version (3.6.1)
3. Upgrade fails due to immutable field on the statefulSet

### Are you using any custom parameters or values?

No extra values used in this example

### What is the expected behavior?

Upgrade completes without the immutable field error on the statefulSet.

### What do you see instead?

```shell
Error: UPGRADE FAILED: cannot patch "clickhouse-shard0" with kind StatefulSet: StatefulSet.apps "clickhouse-shard0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden && cannot patch "clickhouse-shard1" with kind StatefulSet: StatefulSet.apps "clickhouse-shard1" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

### Additional information

From my first analysis this might be due to the modifications of the volumeClaimTemplates section in the statefulSet. Version 3.1.1. did not include any common labels there. The most recent version seems to add the global variables into volumeClaimTemplates section and therefore causes the upgrade to fail. It would be great if this can be fixed, otherwise upgrade from older versions of Clickhouse won't be possible without doing a full re-deployment.

**Comment by cberge908** [comment]
Hey @juan131 

thanks for checking and confirming my quick analysis. I will give the statefulSet deletion a try tomorrow. In the meantime I have simply re-used the old chart version 3.1.1 and changed the clickhouse image tag to the most recent version.

Cheers,
@cberge908

**Comment by juan131** [comment]
You're welcome @cberge908 !!

Please keep us updated about your progress. I'm afraid that we can't do anything rather than providing you this workaround since removing the labels will introduce again an incompatibility.

Cheers!

**Comment by cberge908** [comment]
So deleting the statfulSets work for once - but you need to repeat it for every further upgrade again and again. Also if you start on a more recent release (e.g. 3.6.0). So I would suppose that only the label `helm.sh/chart` needs to be removed ultimately, as its value is changing. The others should be fine as they are most probably would not have any change of their value during their lifecycle.

**Comment by juan131** [comment]
@cberge908 I just created a PR to stop using dynamic labels on these fields. After we release this patch, you won't need to run the workaround for every further upgrade.
