### ISSUE TITLE
[bitnami/keycloak] node selection option for dependent postgresql

### ISSUE THREAD

**Issue by resulyrt93** [bitnami/charts#18229]
### Name and Version

[bitnami/keycloak]

### What is the problem this feature will solve?

Hello, I can set `nodeSelector` parameter for keycloak itself but i can't do it for dependency postgresql. I suppose you can pass that value from `values.yaml`.

### What is the feature you are proposing to solve the problem?

Thus we can install all our application infrastructure in same node and keep nodes isolated. afaik `nodeSelector` is a common and complusory parameter for k8s deployments.

**Comment by carrodher** [comment]
You can use any parameter for the PostgreSQL subchart just placing it under [the `postgresql:` block](https://github.com/bitnami/charts/blob/bec5471af3418c178ac487cea903768e8d8eef77/bitnami/keycloak/values.yaml#L1023) in the values.yaml or by using `--set postgresql.PARAM=VALUE`

**Comment by resulyrt93** [comment]
I added following parameter in the values.yaml but it didn't passed to specified statefulset/pod.
```yaml
postgresql:
  nodeSelector:
    role: "my-custom-node"
```
Also I've checked templates but i didn't find the part that passing these parameters to subchart.

**Comment by resulyrt93** [comment]
I tried according @javsalgar 's [this](https://github.com/bitnami/charts/issues/18285#issuecomment-1670865467) answer and it worked. So it should be
```yaml
postgresql:
  primary:
    nodeSelector:
      role: "my-custom-node"
```
