### ISSUE TITLE
[bitnami/kafka] Client connection error when testing a default Helm chart installation

### ISSUE THREAD

**Issue by opaquot** [bitnami/charts#18235]
### Name and Version

bitnami/kafka 24.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Following what is described on the [github page](https://github.com/bitnami/charts/tree/main/bitnami/kafka), I run the command
`helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka`
2. I am then presented with the next steps to test the default installation:
   - I create a _client.properties_ file to setup the SASL authentication in a client pod
   - I run the following commands to setup a test client:
      `kubectl run kafka-client --restart='Never' --image docker.io/bitnami/kafka:3.5.1-debian-11-r14 --namespace default --command -- sleep infinity`
      `kubectl cp --namespace default /path/to/client.properties kafka-client:/tmp/client.properties`
      `kubectl exec --tty -i kafka-client --namespace default -- bash`
   - Within the client, I then try to launch a producer console with the following:
      `kafka-console-producer.sh --producer.config /tmp/client.properties --broker-list kafka-beagle-controller-0.kafka-beagle-controller-headless.default.svc.cluster.local:19092,kafka-beagle-controller-1.kafka-beagle-controller-headless.default.svc.cluster.local:19092,kafka-beagle-controller-2.kafka-beagle-controller-headless.default.svc.cluster.local:19092 --topic test`
3. I get a stream of errors like the following one:
   `[2023-08-07 13:46:31,680] WARN [Producer clientId=console-producer] Connection to node -2 (kafka-controller-1.kafka-controller-headless.default.svc.cluster.local/10.42.0.64:19092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-07 13:46:31,681] WARN [Producer clientId=console-producer] Bootstrap broker kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:19092 (id: -2 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)`

I am unable to send or receive events with the test client.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

I should be able to test my Kafka cluster installation from the Helm chart by sending events through the `kafka-console-producer.sh` command.

### What do you see instead?

`[2023-08-07 13:46:31,680] WARN [Producer clientId=console-producer] Connection to node -2 (kafka-controller-1.kafka-controller-headless.default.svc.cluster.local/10.42.0.64:19092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-07 13:46:31,681] WARN [Producer clientId=console-producer] Bootstrap broker kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:19092 (id: -2 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)`

**Comment by juan131** [comment]
Hi @opaquot 

Could you please share the content of the `client.properties` file you're using? Also, could you confirm you're installing the Kafka chart with default values?

Thanks in advance

**Comment by opaquot** [comment]
Hi @juan131,

Yes here it is:
```security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="user1" \
    password="$(kubectl get secret kafka-user-passwords --namespace default -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)";```

I should add that I have also tested with a PLAINTEXT security protocol also without success.

I can confirm I'm only using default values when installing the chart.

Thanks for your help

**Comment by migruiz4** [comment]
Hi @opaquot,

I think this issue is duplicated by #18200.

I have already submitted this PR fixing this issue: https://github.com/bitnami/charts/pull/18274.

I'm sorry for the inconvenience.
