### ISSUE TITLE
[bitnami/schema-registry] Cant create schema-registry when setting kafka.enable to false

### ISSUE THREAD

**Issue by andonokar** [bitnami/charts#18237]
### Name and Version

oci://registry-1.docker.io/bitnamicharts/schema-registry

### What architecture are you using?

amd64

### What steps will reproduce the bug?

setting kafka.enable as false in the yaml values from the helm chart to only connect to an external kafka is producing this error:
```
Error: INSTALLATION FAILED: template: schema-registry/templates/statefulset.yaml:10:43: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.broker.replicaCount>: nil pointer evaluating interface {}.replicaCount
```
### Are you using any custom parameters or values?

Only altering the config to connect to my external kafka

### What is the expected behavior?

The installation should be succeding

### What do you see instead?

```
Error: INSTALLATION FAILED: template: schema-registry/templates/statefulset.yaml:10:43: executing "schema-registry/templates/statefulset.yaml" at <.Values.kafka.broker.replicaCount>: nil pointer evaluating interface {}.replicaCount
```

**Comment by andonokar** [comment]
Solved my issue by setting kafka.broker.replicaCount to 1 and kafka.kraft.enabled to false, even though the kafka.enable is false in my custom values.yaml. Both these values does not appear in the readme documention, so it's worth the look, I think.

**Comment by andonokar** [comment]
Values.yaml

kafka:
  ## @param kafka.enabled Enable/disable Kafka chart installation
  ##
  enabled: false
  broker:
    replicaCount: 1
  kraft:
    enabled: false
  ## @param kafka.controller.replicaCount Number of Kafka controller-eligible (controller+broker) nodes
  ##
  controller:
    replicaCount: 1
  ## @param kafka.listeners.client.protocol Authentication protocol for communications with clients. Allowed protocols: `PLAINTEXT`, `SASL_PLAINTEXT`, `SASL_SSL`, `SSL`
  ##
  listeners:
    client:
      protocol: "PLAINTEXT"
  ## @param kafka.service.ports.client Kafka svc port for client connections
  ##
  service:
    ports:
      client: 9092
  ## @param kafka.extraConfig Additional configuration to be appended at the end of the generated Kafka configuration file.
  ##
  extraConfig: |-
    offsets.topic.replication.factor=1
  ## @param kafka.sasl.client.users Comma-separated list of usernames for Kafka client listener when SASL is enabled
  ## @param kafka.sasl.client.passwords Comma-separated list of passwords for client listener when SASL is enabled, must match the number of client.users
  ##
  sasl:
    client:
      users:
        - user
      passwords: ""
##
## External Kafka Configuration
## All of these values are only used when kafka.enabled is set to false
##
externalKafka:
  ## @param externalKafka.brokers Array of Kafka brokers to connect to. Format: protocol://broker_hostname:port
  ##
  brokers:
    - PLAINTEXT://my-cluster-kafka-bootstrap:9092
  ## @param externalKafka.listener.protocol Kafka listener protocol. Allowed protocols: PLAINTEXT, SASL_PLAINTEXT, SASL_SSL and SSL
  ##
  listener:
    protocol: PLAINTEXT
  ## Authentication parameters
  ## @param externalKafka.sasl.user User for SASL authentication
  ## @param externalKafka.sasl.password Password for SASL authentication
  ## @param externalKafka.sasl.existingSecret Name of the existing secret containing a password for SASL authentication (under the key named "client-passwords")
  ##
  sasl:
    user: user
    password: ""
    existingSecret: ""

**Comment by andonokar** [comment]
values.yaml

kafka:
  enabled: false
  broker:
    replicaCount: 1
  kraft:
    enabled: false
  controller:
    replicaCount: 1
  listeners:
    client:
      protocol: "PLAINTEXT"
  service:
    ports:
      client: 9092
  extraConfig: |-
    offsets.topic.replication.factor=1
  sasl:
    client:
      users:
        - user
      passwords: ""
externalKafka:
  brokers:
    - PLAINTEXT://my-cluster-kafka-bootstrap:9092
  listener:
    protocol: PLAINTEXT
  sasl:
    user: user
    password: ""
    existingSecret: ""

**Comment by FraPazGal** [comment]
Hi @andonokar, thanks for reporting this! You are right, this is an issue on the template. I'll create a PR to address this shortly!
