### ISSUE TITLE
 bitnami zookeeper install isseu

### ISSUE THREAD

**Issue by bruse-peng** [bitnami/charts#18270]
### Name and Version

 bitnami/zookeeper

### What is the problem this feature will solve?

no

### What is the feature you are proposing to solve the problem?

when i install  bitnami zookeeper, if i want persistence data  i only set  persistence.storageClass?

**Comment by carrodher** [comment]
Sorry, could you please elaborate a bit more on what is your issue?
If it's about persistence, [here](https://github.com/bitnami/charts/tree/main/bitnami/zookeeper#persistence-parameters) you can find more info about the related values and [here](https://github.com/bitnami/charts/tree/main/bitnami/zookeeper#persistence) about how this chart is configured.
