### ISSUE TITLE
[bitnami/kafka] custom multi line config incorrectly rendered

### ISSUE THREAD

**Issue by ThomasRutger** [bitnami/charts#18280]
### Name and Version

bitnami/kafka 24.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using a custom config by assigning a multi line string to .Values.config does not work as it is rendered incorrectly.

To reproduce:

Assign any multiline string to .config, for example: 
```yaml
config: |
  test
  test
```

This is rendered as follows: 
```yaml
  server.properties: 
    test
    test
```

Which results in an error.

### Are you using any custom parameters or values?

```yaml
config: |
  test
  test
```

### What is the expected behavior?

Config should be rendered as multi line string yaml
```yaml
  server.properties: |
    test
    test
```

### What do you see instead?

Config rendered as single line string yaml, resulting in deployment errors.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by ThomasRutger** [comment]
I realized that you can also provide the config itself as a multiline string. eg:
`config |:
  |
  ...
  ...`

Therefore I suspect that the current behavior is probably intended and this issue can be closed (?).

**Comment by carrodher** [comment]
Yes, you're right, it can be set in that way, I'll close the issue. Thanks for using Bitnami charts
