### ISSUE TITLE
kafka-exporter's generated command uses the wrong port to talk to the kafka container.

### ISSUE THREAD

**Issue by nvp152** [bitnami/charts#18284]
### Name and Version

bitnami/kafka:24.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Turn on metrics:
`
metrics:
  kafka:
    enabled: true
`
The generated command for the metrics deployment's port points to $servicePort and 
`{{- $servicePort := int .Values.service.ports.client -}}` 
but it should be the container port (not the service port) since the headless form of the container FQDN is being used
`{{- $servicePort := int .Values.listeners.client.containerPort -}}`

### What is the expected behavior?

When using the headless form of the container FQDN, the container port should be used.

### What do you see instead?

The headless service port is being used which does not resolved if tagged to the headless form of the container FQDN.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
