### ISSUE TITLE
[bitnami/airflow] support for Airflow plugins

### ISSUE THREAD

**Issue by chgl** [bitnami/charts#1829]
>Airflow has a simple plugin manager built-in that can integrate external features to its core by simply dropping files in your `$AIRFLOW_HOME/plugins` folder.

https://airflow.apache.org/docs/stable/plugins.html

I'm interested in this feature but not quite sure what the best way to implement it as part of this chart would be.

My initial idea is similar to the `cloneDagFilesFromGit` already implemented in this chart: if `airflow.plugins.enabled` is `true`, create a new git-repo-syncer sidecar in the airflow-web pod and continuously clone plugins from a given repository url into a `git-cloned-plugin-files` volume. This volume is then mounted at `$AIRFLOW_HOME/plugins`.

I will work on a PR with this idea if there's interest in this.

**Comment by andresbono** [comment]
Hi @chgl, it sounds like an interesting feature to support! And the approach you are describing seems correct. Maybe you need to mount the plugins directory not only in the `airflow-web` pod but also in the rest of nodes (scheduler & workers).

**Comment by ekhaydarov** [comment]
whats the current support for plugins?

**Comment by chgl** [comment]
> Maybe you need to mount the plugins directory not only in the `airflow-web` pod but also in the rest of nodes (scheduler & workers).

The documentation is a bit fuzzy, but at least the scheduler seems to be necessary (*Make sure you restart the webserver and scheduler after making changes to plugins so that they take effect.* - https://airflow.apache.org/docs/stable/plugins.html). I'll probably just load it into the workers as well just to be safe.

I should find time in the next 2 weeks to work on this.

**Comment by andresbono** [comment]
Thanks @chgl. Your help is really appreciated!
