### ISSUE TITLE
mariadb-galera charts (v0.5.5 > Latest) fails to consistantly start on our k8s v1.17.0

### ISSUE THREAD

**Issue by Keithsc** [bitnami/charts#1831]
**Which chart**: 0.5.6 and newer

**Description**
I am unable to consistently get mariadb-galeria to run on our cluster. I have tried versions 0.5.5 > Latest and although the chart always installs ok the initial pod that is created doesn't always start correctly. It appears that if I delete the namespace and redeploy the chart it does work (sometimes). 

I though v0.5.5 worked but rebuilt the cluster today and the initial pod kept restarting, I remove the chart and the namespace and redeployed the chart and this time the pod started x3 and the cluster came up. I then removed the chart/namespace and tried 0.5.6 > 0.6.2 and they all failed !!!!

I then removed the 0.6.2 pod and namespace and reinstalled it again and this time it worked... so I removed the chart and the namespace again to check and it failed...

These are the logs that I have captured...

0.5.5 = Works (Most of the time)

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:16:50.72 
 11:16:50.72 Welcome to the Bitnami mariadb-galera container
 11:16:50.72 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:16:50.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:16:50.72 Send us your feedback at containers@bitnami.com
 11:16:50.72 
 11:16:50.73 INFO  ==> ** Starting MariaDB setup **
 11:16:50.78 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:16:50.99 INFO  ==> Initializing mariadb database...
 11:16:59.60 INFO  ==> Starting mariadb in background
/libmysqlgalera.sh: line 527: DB_REPLICATION_MODE: unbound variable
 11:17:02.51 INFO  ==> Stopping mariadb
 11:17:06.54 INFO  ==> ** MariaDB setup finished! **
 11:17:06.63 INFO  ==> ** Starting MariaDB **
2020-01-16 11:17:06 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.21-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")

0.5.6 (Fails)

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:13:18.92 
 11:13:18.92 Welcome to the Bitnami mariadb-galera container
 11:13:18.92 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:13:18.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:13:18.93 Send us your feedback at containers@bitnami.com
 11:13:18.93 
 11:13:18.93 INFO  ==> ** Starting MariaDB setup **
 11:13:19.00 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:13:19.20 INFO  ==> Initializing mariadb database...
 11:13:28.72 INFO  ==> Starting mariadb in background
 11:13:29.96 INFO  ==> Stopping mariadb

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:13:34.80 
 11:13:34.80 Welcome to the Bitnami mariadb-galera container
 11:13:34.80 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:13:34.80 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:13:34.80 Send us your feedback at containers@bitnami.com
 11:13:34.80 
 11:13:34.81 INFO  ==> ** Starting MariaDB setup **
 11:13:34.88 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:13:35.08 INFO  ==> Initializing mariadb database...
 11:13:35.09 INFO  ==> Persisted data detected. Restoring...
 11:13:35.10 INFO  ==> ** MariaDB setup finished! **
 11:13:35.16 INFO  ==> ** Starting MariaDB **
2020-01-16 11:13:35 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.4.11-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")

0.6.0 (Fails)

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:20:21.91 
 11:20:21.91 Welcome to the Bitnami mariadb-galera container
 11:20:21.91 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:20:21.91 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:20:21.91 Send us your feedback at containers@bitnami.com
 11:20:21.91 
 11:20:21.91 INFO  ==> ** Starting MariaDB setup **
 11:20:22.01 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:20:22.35 INFO  ==> Initializing mariadb database...
 11:20:30.33 INFO  ==> Starting mariadb in background
 11:20:31.41 INFO  ==> Stopping mariadb

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:20:35.75 
 11:20:35.75 Welcome to the Bitnami mariadb-galera container
 11:20:35.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:20:35.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:20:35.75 Send us your feedback at containers@bitnami.com
 11:20:35.75 
 11:20:35.75 INFO  ==> ** Starting MariaDB setup **
 11:20:35.82 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:20:36.07 INFO  ==> Initializing mariadb database...
 11:20:36.08 INFO  ==> Persisted data detected. Restoring...
 11:20:36.09 INFO  ==> ** MariaDB setup finished! **
 11:20:36.17 INFO  ==> ** Starting MariaDB **
2020-01-16 11:20:36 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.4.11-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")

0.6.1 (Fails)

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:22:37.82 
 11:22:37.82 Welcome to the Bitnami mariadb-galera container
 11:22:37.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:22:37.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:22:37.83 Send us your feedback at containers@bitnami.com
 11:22:37.83 
 11:22:37.83 INFO  ==> ** Starting MariaDB setup **
 11:22:37.89 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:22:38.08 INFO  ==> Initializing mariadb database...
 11:22:46.21 INFO  ==> Starting mariadb in background
 11:22:47.42 INFO  ==> Stopping mariadb

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:22:51.97 
 11:22:51.97 Welcome to the Bitnami mariadb-galera container
 11:22:51.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:22:51.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:22:51.98 Send us your feedback at containers@bitnami.com
 11:22:51.98 
 11:22:51.98 INFO  ==> ** Starting MariaDB setup **
 11:22:52.05 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:22:52.23 INFO  ==> Initializing mariadb database...
 11:22:52.26 INFO  ==> Persisted data detected. Restoring...
 11:22:52.26 INFO  ==> ** MariaDB setup finished! **
 11:22:52.32 INFO  ==> ** Starting MariaDB **
2020-01-16 11:22:52 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.4.11-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")

0.6.2 (Fails)

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:26:38.83 
 11:26:38.83 Welcome to the Bitnami mariadb-galera container
 11:26:38.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:26:38.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:26:38.83 Send us your feedback at containers@bitnami.com
 11:26:38.84 
 11:26:38.84 INFO  ==> ** Starting MariaDB setup **
 11:26:38.91 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:26:39.13 INFO  ==> Initializing mariadb database...
 11:26:46.52 INFO  ==> Starting mariadb in background
 11:26:47.80 INFO  ==> Stopping mariadb

kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:26:51.64 
 11:26:51.64 Welcome to the Bitnami mariadb-galera container
 11:26:51.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:26:51.64 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:26:51.64 Send us your feedback at containers@bitnami.com
 11:26:51.65 
 11:26:51.65 INFO  ==> ** Starting MariaDB setup **
 11:26:51.72 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:26:51.95 INFO  ==> Initializing mariadb database...
 11:26:51.96 INFO  ==> Persisted data detected. Restoring...
 11:26:51.97 INFO  ==> ** MariaDB setup finished! **
 11:26:52.04 INFO  ==> ** Starting MariaDB **
2020-01-16 11:26:52 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.4.11-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")

Next I ran...
    helm delete --purge mariadb-galera-1
    kubectl delete ns mariadb-galera-1

and it works !!!!

0.6.2 (Starts) 2nd Time round....
kubectl logs mariadb-galera-1-0 -n mariadb-galera-1 -f
 11:29:52.14 
 11:29:52.15 Welcome to the Bitnami mariadb-galera container
 11:29:52.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 11:29:52.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 11:29:52.15 Send us your feedback at containers@bitnami.com
 11:29:52.15 
 11:29:52.15 INFO  ==> ** Starting MariaDB setup **
 11:29:52.22 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 11:29:52.48 INFO  ==> Initializing mariadb database...
 11:29:59.68 INFO  ==> Starting mariadb in background
/libmysqlgalera.sh: line 527: DB_REPLICATION_MODE: unbound variable
 11:30:02.04 INFO  ==> Stopping mariadb
 11:30:05.06 INFO  ==> ** MariaDB setup finished! **

 11:30:05.15 INFO  ==> ** Starting MariaDB **
2020-01-16 11:30:05 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.4.11-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")

**Steps to reproduce the issue:**

Create a new K8S Cluster (Typhoon), install helm, rook then run the following

helm install --name mariadb-galera-1 bitnami/mariadb-galera \
  --version 0.5.5 \
  --namespace mariadb-galera-1 \
  --set persistence.enabled=true \
  --set persistence.size=20Gi 

**Version of Helm and Kubernetes**: 1.17.0

- Output of `helm version`:
Each time we run the helm command we get the usual output about connecting to databases although I just noticed the following at the top of the output ( This was while deploying 0.5.5)

E0115 13:59:37.718541   13880 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:45327->127.0.0.1:34010: write tcp4 127.0.0.1:45327->127.0.0.1:34010: write: broken pipe
LAST DEPLOYED: Wed Jan 15 13:59:37 2020
NAMESPACE: mariadb-galera-1
STATUS: DEPLOYED

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by javsalgar** [comment]
Hi,

We may need more information about the cluster. Does it have any policy to only allow immutable filesystems? Maybe the non-root user created does not belong to the root group, making it then to not work.
