### ISSUE TITLE
`helm pull` with chart url results in 403 error

### ISSUE THREAD

**Issue by vinayak-kukreja** [bitnami/charts#18339]
### Name and Version

mysql

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Run,
```
helm pull https://charts.bitnami.com/bitnami/mysql
```

### What is the expected behavior?

Chart is pulled locally. 

### What do you see instead?

Error: failed to fetch https://charts.bitnami.com/bitnami/mysql : 403 Forbidden

**Comment by carrodher** [comment]
The recommended way of pulling Bitnami Helm charts is from the DockerHub OCI registry, see https://hub.docker.com/r/bitnamicharts/mysql:
```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/common
```

If you would like to use the _index.yaml_, you need to first add the repo to your Helm client and then pull the Helm chart:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
$ helm pull bitnami/mysql
```
