### ISSUE TITLE
[bitnami/node] i get pages linking to the bitnami node chart. cant find it in the repo

### ISSUE THREAD

**Issue by wibed** [bitnami/charts#18331]
### Name and Version

bitnami/node

### What architecture are you using?

None

### What steps will reproduce the bug?

https://bitnami.com/stack/nodejs/helm

GitHub? no node

### What is the expected behavior?

to find the Helm chart on GitHub

### What do you see instead?

no helm chart

**Comment by javsalgar** [comment]
Hi,

The bitnami/node was removed approximately one year ago https://github.com/bitnami/charts/pull/13142. It seems that there are some leftover references that we need to remove. Thank you so much for reporting

**Comment by wibed** [comment]
there is no other node related helm chart is there?

**Comment by javsalgar** [comment]
Hi,

I'm afraid not. However the containers are available so you can use them in your own YAML files
