### ISSUE TITLE
[bitnami/zookeeper] Unable to use newer JVM memory settings as Xmx overrides

### ISSUE THREAD

**Issue by manojkumarbardhan** [bitnami/charts#18346]
### Name and Version

bitnami/zookeeper 11.1.6

### What is the problem this feature will solve?

The user should be able to configure JVM memory options such as - XX: MaxRAMPercentage, but it cannot be used to control the memory usage of zookeeper as Xmx overrides.

### What is the feature you are proposing to solve the problem?

Ref ticket - https://issues.apache.org/jira/browse/ZOOKEEPER-4701

### What alternatives have you considered?

Ref ticket - https://issues.apache.org/jira/browse/ZOOKEEPER-4701

**Comment by fevisera** [comment]
Hi @manojkumarbardhan,

Thank you for reaching out.

You can change the default JVM flags for the ZooKeeper process by setting `jvmFlags` in your values. That will update the JVMFLAGS environment variable. For more information, you can check the README of the Zookeeper container: https://github.com/bitnami/containers/tree/main/bitnami/zookeeper#configuration.

There is also an environment variable ZOO_HEAP_SIZE which allow you to set the size in MB for the Java Heap options (Xmx and XMs). This environment variable is ignored if Xmx and Xms are configured via JVMFLAGS. Default: 1024.

**Comment by manojkumarbardhan** [comment]
Hi @fevisera ,

Thanks for suggesting. I have already tried with jvmFlags and I am able to set the heap size. But, the issue is when I'm trying to use - XX: MaxRAMPercentage it's not working. The existing -xmx is overriding the - XX: MaxRAMPercentage. How to use this - XX: MaxRAMPercentage ?

**Comment by fevisera** [comment]
Hi @manojkumarbardhan,
Could you share how are you trying to set `- XX: MaxRAMPercentage` and detecting it is not working?

Thanks.
