### ISSUE TITLE
[bitnami/common] new macro to evaluate a checksum of configmap/secrets

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#18376]
### Name and Version

bitnami/common

### What is the problem this feature will solve?

in https://github.com/bitnami/charts/pull/17302 https://github.com/bitnami/charts/pull/17579, I patched the checksum calculation of pod annotations that are used to trigger a pod rollout.

the pattern described in [helm docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) has the issue that it will trigger a reload of the pods when the chart version change, even it the pod template and configmap data are not changed. 

This happens because the version of the chart is included in "helm.sh/chart" in metadata.labels (printf "%s-%s" .Chart.Name .Chart.Version) of the configmap and the checksum is done on the whole file.

### What is the feature you are proposing to solve the problem?

instead of copy/pasting the snippets from my PRs in other charts, I suggest a new macro to checksum only the data part of the ConfigMap/Secret, something like:

```
{{ define "common.utils.checksumData" }}
{{ omit ( include (print $.Template.BasePath .file ) . | fromYaml ) "apiVersion" "kind" "metadata" | toYaml | sha256sum }}
{{ end }}

{{ include "common.utils.checksumData" (dict "file" "/health-configmap.yaml") }}
```

this works only if there is one resource/document in the file (fromYaml does not support multiple documents).

I'll do the PR if the idea is found useful .

**Comment by CeliaGMqrz** [comment]
Hi @jouve, sorry for the late response.

Thanks for your feature request! The Bitnami team will be happy to review the PR and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by klamas1** [comment]
Sorry, but wouldn't "helm.sh/chart" in metadata.labels of deployment be changed and cause the pods to restart?

**Comment by jouve** [comment]
@klamas1  nope :)

> A Deployment's rollout is triggered if and only if the Deployment's Pod template (that is, .spec.template) is changed, for example if the labels or container images of the template are updated. Other updates, such as scaling the Deployment, do not trigger a rollout.

ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

**Comment by klamas1** [comment]
I saw the message. it does not explain how changing the deployment annotation can cause the pods rollout

**Comment by jouve** [comment]
you are allowed your opinion. :)

I though you meant the deployment.metadata originally.

indeed pod.metadata changes, I currently strip it with a --post-renderer, I should have added that to the description :)

**Comment by jouve** [comment]
also , it's going to be even easier now thanks to #18154 as we can do:
```
podLabels:
  helm.sh/chart: "{{ .Chart.Name }}"
```

**Comment by klamas1** [comment]
That's what I wrote `"helm.sh/chart" in metadata.labels of deployment`, that changed. But spec.template.metadata don't changed and pods don't rollout

What exactly changes your dictionary pod.metadata?

**Comment by klamas1** [comment]
I just can’t understand how the new macro can help and in what way
