### ISSUE TITLE
[bitnami/kafka] broker.minId has no effect on the minId of the broker

### ISSUE THREAD

**Issue by ahmedkhabkhab** [bitnami/charts#18372]
### Name and Version

bitnami/kafka 24.0.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set controller.controllerOnly to true to have separate brokers and controllers 
2. Set broker.replicaCount to 3
3. Set controller.replicaCount to 3

### What is the expected behavior?

Since the default value of broker.minId is 100 we should have 3 brokers with ids 100 101 and 102. For the controllers, since controller.minId is 0 we should have 3 controllers with ids 0 1 and 2.

### What do you see instead?

Broker ids start from 0 instead of 100 preventing the cluster from being created since we can’t have the same ids for controllers and brokers.

**Comment by migruiz4** [comment]
Hi @ahmedkhabkhab,

Is it possible you have Persistent volumes from a previous installation of the chart?

I tried to reproduce your issue in a freshly installed environment and Node ids are correctly set:

```console
$ helm install kafka bitnami/kafka --set controller.controllerOnly=true --set broker.replicaCount=3 --set controller.replicaCount=3
$ for i in {0..2}; do kubectl exec -it kafka-broker-$i -c kafka -- cat /opt/bitnami/kafka/config/server.properties | grep node.id; done
node.id=100
node.id=101
node.id=102
$ for i in {0..2}; do kubectl exec -it kafka-controller-$i -c kafka -- cat /opt/bitnami/kafka/config/server.properties | grep node.id; done
node.id=0
node.id=1
node.id=2
```

Please notice that the `minId` won't take effect when the node had been previously initialized as the previously configured `node.id` will prevail and, if migrated from Zookeeper mode, the previous `broker.id` will also be reused as the new `node.id`. In those cases, you will need to use a custom `controller.minId`/`broker.minId` that fits your use case.

```console
$ kubectl get cm kafka-scripts -o yaml
...
    # Configure node.id and/or broker.id
    if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
        if grep -q "broker.id" /bitnami/kafka/data/meta.properties; then
          ID="$(grep "broker.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')"
          kafka_conf_set "$KAFKA_CONFIG_FILE" "node.id" "$ID" # This is expected, during Zookeeper mode migration the broker.id is reused as node.id
        else
          ID="$(grep "node.id" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')"
          kafka_conf_set "$KAFKA_CONFIG_FILE" "node.id" "$ID"
        fi
    else
        ID=$((POD_ID + KAFKA_MIN_ID))
        kafka_conf_set "$KAFKA_CONFIG_FILE" "node.id" "$ID"
    fi
...
```
