### ISSUE TITLE
[bitnami/cassandra] Override namespace

### ISSUE THREAD

**Issue by iRobertas** [bitnami/charts#18380]
### Name and Version

bitnami/cassandra 10.4.5

### What is the problem this feature will solve?

Currently Cassandra chart doesn't have parameter to override namespace.

### What is the feature you are proposing to solve the problem?

Would be great to have parameter "namespaceOverride" (same as in mongodb chart).

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
