### ISSUE TITLE
[bitnami/cassandra] Unable to connect to  cqlsh 

### ISSUE THREAD

**Issue by madhupnvl** [bitnami/charts#1838]
Hi Team,

I'm facing issue to connect to cqlsh in production yaml charts.
once the charts up, 

> kubectl get pods --namespace $NAMESPACE

> kubectl exec -it $(ABOVE CASSNADRA POD NAME) bash --namespace $NAMESPACE

then 

> cqlsh -u cassandra -p cassandra 

I'm unable to connect to cqlsh, here is the error.

Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"',)})

Here is the yaml changes
> dbUser:
>  > user: cassandra
>   forcePassword: false
>   password: cassandra

After i tried with forcePassword: true also and with below client also.
>kubectl run --namespace derm derm-cassandra-client --rm --tty -i --restart="Never" --labels="cassandra-client=true"  --image docker.io/bitnami/cassandra:3.11.5-debian-9-r57 -- bash

But no luck.

i observed below warning in pod logs,

cassandra 11:09:12.28 WARN  ==> You set the environment variable CASSANDRA_PASSWORD=cassandra. This is the default value when bootstrapping Cassandra and should not be used in production environments.

**Comment by javsalgar** [comment]
Hi,

I tried this

```
helm install bitnami/cassandra --set dbUser.password=cassandra --generate-name
```

```
 130 ❯ helm ls
NAME            	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
chart-1579522830	default  	1       	2020-01-20 13:20:31.453802 +0100 CET	deployed	cassandra-4.1.14	3.11.5
```

and found no problems

```
 1 ❯ kubectl exec -ti chart-1579522830-cassandra-0 bash
I have no name!@chart-1579522830-cassandra-0:/$ cqlsh -u cassandra -p cassandra
Connected to cassandra at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.5 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh>
```

Could you confirm that you are using the latest version of the chart?

**Comment by madhupnvl** [comment]
Hi @javsalgar, 

You used development values.yaml file. rename it to values-dev.yaml and rename values-production.yaml to values.yaml. try this one.

**Comment by madhupnvl** [comment]
Hi @javsalgar,
Here is the details, what i tried.
Deleted the values.yaml file and renamed values-production.yaml to values.yaml. So my environment is production now.

> helm upgrade --install --namespace test test-cassandra cassandra

>  kubectl get pods --namespace test
> > NAME               READY   STATUS    RESTARTS   AGE
> test-cassandra-0   1/1     Running   0          2m21s
> test-cassandra-1   1/1     Running   0          1m59s
> test-cassandra-2   1/1     Running   0          96s

> kubectl exec -it test-cassandra-0 bash --namespace test
cqlsh -u cassandra -p cassandra
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"',)})

Thanks,
Madhu
