### ISSUE TITLE
arm32 (armv71) packages

### ISSUE THREAD

**Issue by Mattie112** [bitnami/charts#18387]
### Name and Version

bitnami/metrics-server

### What is the problem this feature will solve?

I am experimenting a bit with k3s on a bunch of raspberry PI boards I have doing nothing :) A combination of PI 2 (arm32) and PI 3 (arm64 supported but I installed a 32-bit OS). I was looking into metrics but all the pods are stuck on "pending" most likely due to not finding an image for the arm32 arch.

Do you plan on supporting this in any way?

I checked a couple of other bitami images but they all seem to be for 64-bit.

### What is the feature you are proposing to solve the problem?

Building the packages for arm32 (armv71)

### What alternatives have you considered?

And suggestions?

**Comment by carrodher** [comment]
Thank you for your suggestion! We truly appreciate your input but, unfortunately, at this moment it is not something on our roadmap for ARM or AMD
