### ISSUE TITLE
Rabbit is not working on aws 

### ISSUE THREAD

**Issue by Millen93** [bitnami/charts#18388]
### Name and Version

bitnami/rabbitmq:12.0.10

### What architecture are you using?

None

### What steps will reproduce the bug?

1. In Elastic k8s service I am trying to run helm chart by argocd 
2. Version of chart rabbitmq was 11.1.1, then i tried 12.0.9 and 12.0.10. All in all, i had the same trouble
3. Pod rabbitmq-0 is not working
4. Logs of pod:
```
rabbitmq 10:43:46.05 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 10:43:46.07 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 10:43:46.09 INFO  ==> Initializing RabbitMQ...
cp: cannot stat '/bitnami/rabbitmq/conf/*': No such file or directory
```
### What is the expected behavior?

working rabbitmq

**Comment by migruiz4** [comment]
Hi @Millen93,

Could you please provide more details about your use case? Apart from using ArgoCD to deploy the `bitnami/rabbitmq` chart, are you setting any custom values?

The logs you shared are the output of `kubectl logs <rabbitmq-pod-0>`? Could you please share the output of the following commands to help us troubleshoot the issue?
- `kubectl get pods` 
- `kubectl logs -p <rabbitmq-pod-0>` (logs from the previous container)
- `kubectl describe pod <rabbitmq-pod-0>`
