### ISSUE TITLE
[redis] Can't enable `sentinel.persistence.enabled` without `replica.persistence.enabled`

### ISSUE THREAD

**Issue by rassie** [bitnami/charts#18390]
### Name and Version

bitnami/redis 17.15.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Initialize Chart with `sentinel.persistence.enabled` with `replica.persistence.enabled` set to `false`. 
2. Deploy Chart
3. Observe error message `create Pod redis-node-2 in StatefulSet redis-node failed error: Pod "redis-node-2" is invalid: [spec.containers[0].volumeMounts[2].name: Not found: "sentinel-data", spec.containers[1].volumeMounts[2].name: Not found: "sentinel-data"]`

### What is the expected behavior?

`StatefulSet` should employ `volumeClaimTemplates` to create an appropriate PVC.

### What do you see instead?

There are no PVCs created.

### Additional information

The reason for missing PVCs is in the template:

https://github.com/bitnami/charts/blob/72fee9ebfb8af8d3628bfe0b3b5c00f83cfdca62/bitnami/redis/templates/sentinel/statefulset.yaml#L725-L743

Apparently, `volumeClaimTemplates` used to contain only replica's PVCs, so that the whole block has been wrapped in an if-then-else condition. When sentinel persistence has been added in https://github.com/bitnami/charts/pull/9282, only a new `volumeClaimTemplates` entry has been added without fixing the if-wrapper. If replica persistence is not enabled, no PVC is requested for the sentinel and thus everything fails.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
