### ISSUE TITLE
[bitnami/kafka] Kafka can't connect to Zookeeper (Whenever zookeeper replica count is greater than 1)

### ISSUE THREAD

**Issue by Hmr-ramzi** [bitnami/charts#1839]
**Which chart**:  Kafka / Zookeeper

**Description**

Kafka nodes can't connect to zookeeper whenever the zookeeper replica count is greater than 1.

**Describe the results you received:**

Kafka pods keep on crashlooping with timeout exception of unable to connect to Zookeeper

**Describe the results you expected:**

Kafka would connect normally to zookeeper

**Comment by javsalgar** [comment]
Hi,

I tried installing the chart like this

```
helm install bitnami/kafka --set zookeeper.replicaCount=2  --generate-name
```

and got this

```
 130 ❯ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
chart-1579522554-kafka-0       1/1     Running   2          71s
chart-1579522554-zookeeper-0   1/1     Running   0          71s
chart-1579522554-zookeeper-1   1/1     Running   0          71s
```

Could you confirm you are using the latest version of the chart?

```
❯ helm ls
NAME            	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART      	APP VERSION
chart-1579522554	default  	1       	2020-01-20 13:15:55.921077 +0100 CET	deployed	kafka-7.1.2	2.4.0
```

**Comment by Hmr-ramzi** [comment]
You are absolutely right! All good. It was an istio configuration issue on my side. Sorry for wasting your time. I appreciate your prompt reply.
