### ISSUE TITLE
[bitnami/cassandra] Unable restore the backup

### ISSUE THREAD

**Issue by madhupnvl** [bitnami/charts#1840]
Hi Team,

I'm trying to migrate from normal cassandra to bitnami/cassandra, as the process I'm referring the below page.
https://docs.bitnami.com/azure-templates/infrastructure/cassandra/administration/backup-restore/
In the above link I observed is path is not correct (/opt/bitnami/cassandra/data), so I got the new/actual path (/bitnami/cassandra/data).

I took the back up of old one & moved to the location as pointed the above page.

One of the step is to Shut down the node:
> sudo service bitnami stop
> > Error: bitnami: unrecognized service

I tried to see all the services,
> service --status-all
> >  [ ? ]  hwclock.sh
 [ - ]  procps
 [ - ]  sudo

I didn't find any thing related to it.

I skipped it and move forward, on the step Delete all .db files,
>/bitnami/cassandra/data/data/system/local-7ad54392bcdd35a684174e047860b377# sudo rm *
> > rm: cannot remove 'md-13-big-Data.db': Device or resource busy
rm: cannot remove 'md-13-big-Index.db': Device or resource busy
rm: cannot remove 'md-14-big-Data.db': Device or resource busy
rm: cannot remove 'md-14-big-Index.db': Device or resource busy

I'm unable to move forward.

The last step is to repair,
> nodetool repair test;
> > [2020-01-20 13:05:27,782] Replication factor is 1. No repair is needed for keyspace 'test'.

But no luck, Unable to restore the backup.

Thanks,
Madhu

**Comment by carrodher** [comment]
Hi,

Just to confirm. You want to move an existing non-bitnami Cassandra to the multitier Bitnami Cassandra in Azure, right? If you are trying to move your solution to kubernetes the referenced guide is not valid for this platform.

In GitHub we provide support only for docker images and charts, if you are using other Bitnami solutions like singleVMs or multitier assets in the different cloud providers or local installation this is not the place where we can help you.

We provide technical support in our [forum](https://community.bitnami.com/). Our team is actively monitoring it and will be glad to help you there, usually within a business day, and the whole community will benefit from your contribution. Could you please post your question by creating a new forum thread?

**Comment by madhupnvl** [comment]
Hi @carrodher,

We are not in Azure, we are using our local Linux environments itself.
The give https://community.bitnami.com/ is not accessible now, once is it come to online will post there.

Thank you
Madhu

**Comment by dani8art** [comment]
Hi @madhupnvl 

Are you still facing problem to post on https://community.bitnami.com/, I have checked it and it is working fine now. I hope you could post there.

Regards.

**Comment by madhupnvl** [comment]
Hi @dani8art,

No, the error in chrome is..., Your connection is not private
Attackers might be trying to steal your information from community.bitnami.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_REVOKED

In Firefox,
An error occurred during a connection to community.bitnami.com. A required TLS feature is missing. Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING 

Thanks,
Madhu Ram

**Comment by dani8art** [comment]
Hi @madhupnvl 

Which version of chrome are you using? we are using `Let's Encrypt` to generate certs and certs that are generated by this tool require `Chrome >= v67` https://community.letsencrypt.org/t/chrome-certificate-error/76345/2. Upgrade your chrome version and try again, please.

Regards.

**Comment by madhupnvl** [comment]
Hi @dani8art I'm using the latest but no luck

**Comment by dani8art** [comment]
It's something weird, it should work. Can you try to clean the cache, cookies, etc... of your browser, please?
