### ISSUE TITLE
Override externalDNS record format for Redis

### ISSUE THREAD

**Issue by Kilowhisky** [bitnami/charts#18421]
### Name and Version

bitnami/redis 17.15.2

### What is the problem this feature will solve?

The hard coded format is `<pod-name>.<release-name>.<dns-suffix>`.  This can cause issues with AWS Route53 namespaces as they won't let you easily create multi dot sub domains. It also causes issues with SSL Certs if they don't have those sub-domains defined. 

This is defined in the helpers file as https://github.com/bitnami/charts/blob/65635cedba99c5c77d4367198af46dd8582e5485/bitnami/redis/templates/_helpers.tpl#L315-L318 

### What is the feature you are proposing to solve the problem?

I would love to be able to customize this or at the very least change the format to  `<pod-name>-<release-name>.<dns-suffix>`.   Note the use of `-` instead of `.`.

### What alternatives have you considered?

Branch and override.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
