### ISSUE TITLE
[bitnami/kafka] Add a secret extraConfig in addition to the configMap one.

### ISSUE THREAD

**Issue by LuxTheDude** [bitnami/charts#18420]
### Name and Version

bitnami/kafka 24.0.10

### What is the problem this feature will solve?

Currently, the only way too add custom settings to the kafka config, is by using the extraConfig value. This is problematic as i might want to add custom settings that are secret. Since the new upgrade, the environment variables with prefix "KAFKA_CFG" are no longer working, and therefore the extraEnvVarsSecret value does not provide this functionality anymore.

I am using the chart with the sasl mechanism oauthbearer, which is relatively easy to configure, even though the chart doesn't officially support it. I have to overwrite the JAAS config, and the config will contain secrets, that i don't want to be stored in a configMap.

### What is the feature you are proposing to solve the problem?

A value called extraConfigSecret in which i can add extra configs as secrets. These would also need to not be included in the normal kafka config configMap of the template, and instead be appended to the server.properties separately from the configMap.

### What alternatives have you considered?

None. I don't see an alternative other than letting the secrets be stored in configMaps.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
