### ISSUE TITLE
[bitnami/elasticsearch] run with 1 processor 

### ISSUE THREAD

**Issue by nadavsky** [bitnami/charts#18446]
### Name and Version

bitnami/elasticsearch

### What architecture are you using?

amd64

### What steps will reproduce the bug?

go inside the container,
get default config by curl http://127.0.0.1:9200/_cluster/settings?include_defaults=true
see default.processors=1

### What is the expected behavior?

I can't find a way to change it from the chart configuration or by inject some variables.

### What do you see instead?

1 processor 

### Additional information

I suspect it depends on missing java opts -UseContainerSupport, so the container always run with one processor instead of calculate the real cores number on the host machine.

**Comment by corico44** [comment]
Hi @nadavsky, I can't find any attribute like `default.processors` in the output of that curl. Could you tell me if you are setting any value other than the default ones? What command are you using to access the container? And what result does that curl give you as output?
