### ISSUE TITLE
[bitnami/etcd] Enable ETCD_LISTEN_METRICS_URLS

### ISSUE THREAD

**Issue by svenwiltink** [bitnami/charts#18451]
### Name and Version

bitnami/etcd latest

### What is the problem this feature will solve?

When an etcd deployement is tls secured it may be desired to scrape metrics without having the need to generate/distribute certificates to prometheus. 

### What is the feature you are proposing to solve the problem?

Add the following two properties to values.yaml:

- containerPorts.metrics (int: defaulting to arbitrary port like 9090)
- metrics.useSeparateEndpoint (bool: defaulting to false)

Nothing changes when the separate endpoint is disabled. When the endpoint is enabled `ETCD_LISTEN_METRICS_URLS` is added to the statefulset with the value `http://0.0.0.0:{{ .Values.containerPorts.metrics }}`. When the separate endpoint is exposed the scrape config for prometheus should also use this port instead of the clientPort for both the portMonitor and the annotations.

**Comment by svenwiltink** [comment]
Some context: we want to monitor hundreds of etcd deployments without maintaining an equal amount of certificates for prometheus.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
