### ISSUE TITLE
mongodb-0 keeps restarting and in CrashLoopBackOff status

### ISSUE THREAD

**Issue by islet5** [bitnami/charts#18477]
### Name and Version

bitnami/mongodb:4.4.5-debian-10-r0

### What architecture are you using?

None

### What steps will reproduce the bug?

after upgraded aks cluster, mongodb-0 is in CrashLoopBackOff

<img width="616" alt="image" src="https://github.com/bitnami/charts/assets/9824473/3a5a2a4e-7073-4aba-8fe4-ef0480849dba">

### What is the expected behavior?

pod running

### What do you see instead?
```
mongodb-0                           0/2     Running     1 (4s ago)   78s
```
### Additional information
```
[xiaowei_zhou@azure-k8s ~]$ azure-sensor-k8s -n mongo-system logs -f mongodb-0  -c mongodb
Advertised Hostname: mongodb-0.mongodb-headless.mongo-system.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 04:22:53.37 
mongodb 04:22:53.37 Welcome to the Bitnami mongodb container
mongodb 04:22:53.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 04:22:53.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 04:22:53.38 
mongodb 04:22:53.38 INFO  ==> ** Starting MongoDB setup **
mongodb 04:22:53.39 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 04:22:53.41 INFO  ==> Initializing MongoDB...
mongodb 04:22:53.44 INFO  ==> Enabling authentication...
mongodb 04:22:53.45 INFO  ==> Deploying MongoDB with persisted data...
mongodb 04:22:53.45 INFO  ==> Writing keyfile for replica set authentication...
mongodb 04:22:53.48 INFO  ==> ** MongoDB setup finished! **

mongodb 04:22:53.50 INFO  ==> ** Starting MongoDB **

{"t":{"$date":"2023-08-17T04:22:53.530+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2023-08-17T04:22:53.532+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2023-08-17T04:22:53.534+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-08-17T04:22:53.535+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2023-08-17T04:22:53.535+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-08-17T04:22:53.566+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"mongodb-0"}}
{"t":{"$date":"2023-08-17T04:22:53.566+00:00"},"s":"W",  "c":"CONTROL",  "id":20720,   "ctx":"initandlisten","msg":"Available memory is less than system memory","attr":{"availableMemSizeMB":2048,"systemMemSizeMB":32113}}
{"t":{"$date":"2023-08-17T04:22:53.566+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.5","gitVersion":"ff5cb77101b052fa02da43b8538093486cf9b3f7","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2023-08-17T04:22:53.566+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.4.0-1109-azure"}}}
{"t":{"$date":"2023-08-17T04:22:53.566+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/opt/bitnami/mongodb/conf/mongodb.conf","net":{"bindIp":"*","ipv6":false,"port":27017,"unixDomainSocket":{"enabled":true,"pathPrefix":"/opt/bitnami/mongodb/tmp"}},"processManagement":{"fork":false,"pidFilePath":"/opt/bitnami/mongodb/tmp/mongodb.pid"},"replication":{"enableMajorityReadConcern":true,"replSetName":"rs0"},"security":{"authorization":"enabled","keyFile":"/opt/bitnami/mongodb/conf/keyfile"},"setParameter":{"enableLocalhostAuthBypass":"false"},"storage":{"dbPath":"/bitnami/mongodb/data/db","directoryPerDB":false,"journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"logRotate":"reopen","path":"/opt/bitnami/mongodb/logs/mongodb.log","quiet":false,"verbosity":0}}}}
{"t":{"$date":"2023-08-17T04:22:53.571+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/bitnami/mongodb/data/db","storageEngine":"wiredTiger"}}
{"t":{"$date":"2023-08-17T04:22:53.572+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
{"t":{"$date":"2023-08-17T04:22:53.572+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=512M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2023-08-17T04:22:55.208+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246175:208100][1:0x7f2dd7570140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29226 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:55.292+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246175:292798][1:0x7f2dd7570140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29227 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:55.297+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246175:297443][1:0x7f2dd7570140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29228 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:55.301+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246175:301558][1:0x7f2dd7570140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29229 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:55.301+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246175:301752][1:0x7f2dd7570140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29230 through 29552"}}

....similar info...

{"t":{"$date":"2023-08-17T04:22:56.806+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:806536][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29547 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:56.808+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:808449][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29548 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:56.811+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:811257][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29549 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:56.812+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:812872][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29550 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:56.816+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:816588][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29551 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:56.889+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:889918][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 29552 through 29552"}}
{"t":{"$date":"2023-08-17T04:22:56.947+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:947911][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (1690631426, 20164)"}}
{"t":{"$date":"2023-08-17T04:22:56.947+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692246176:947982][1:0x7f2dd7570140], file:sizeStorer.wt, txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (1690631421, 20164)"}}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"CONTROL",  "id":23377,   "ctx":"SignalHandler","msg":"Received signal","attr":{"signal":15,"error":"Terminated"}}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"CONTROL",  "id":23378,   "ctx":"SignalHandler","msg":"Signal was sent by kill(2)","attr":{"pid":0,"uid":0}}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"CONTROL",  "id":23381,   "ctx":"SignalHandler","msg":"will terminate after current cmd ends"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"SignalHandler","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"SignalHandler","msg":"Shutting down the MirrorMaestro"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"SignalHandler","msg":"Shutting down the WaitForMajorityService"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"SignalHandler","msg":"Shutdown: going to close listening sockets"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"SignalHandler","msg":"Shutting down the global connection pool"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"STORAGE",  "id":4784906, "ctx":"SignalHandler","msg":"Shutting down the FlowControlTicketholder"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"SignalHandler","msg":"Stopping further Flow Control ticket acquisitions."}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"REPL",     "id":4784907, "ctx":"SignalHandler","msg":"Shutting down the replica set node executor"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"SignalHandler","msg":"Shutting down the ReplicaSetMonitor"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"SignalHandler","msg":"Shutting down the MigrationUtilExecutor"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"CONTROL",  "id":4784925, "ctx":"SignalHandler","msg":"Shutting down free monitoring"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"STORAGE",  "id":4784927, "ctx":"SignalHandler","msg":"Shutting down the HealthLog"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"STORAGE",  "id":4784929, "ctx":"SignalHandler","msg":"Acquiring the global lock for shutdown"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"SignalHandler","msg":"Dropping the scope cache for shutdown"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"FTDC",     "id":4784926, "ctx":"SignalHandler","msg":"Shutting down full-time data capture"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"SignalHandler","msg":"Now exiting"}
{"t":{"$date":"2023-08-17T04:24:23.448+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"SignalHandler","msg":"Shutting down","attr":{"exitCode":0}}
```

**Comment by islet5** [comment]
i deleted /bitnami/mongodb/data/db/mongod.lock and run repair cmd like this:

 rm -rf ls /bitnami/mongodb/data/db/mongod.lock
mongod --repair --dbpath /bitnami/mongodb/data/db

after this:

[xiaowei_zhou@azure-k8s ~]$ azure-sensor-k8s -n mongo-system get pod
NAME                                READY   STATUS      RESTARTS     AGE
gcops-shoot-8cb774db-84gc4          1/1     Running     0            63d
mongodb-0                           0/2     Error       1 (3s ago)   45s
mongodb-arbiter-0                   1/1     Running     0            63d
mongodb-backup-job-28199970-gbv74   0/1     Completed   0            2d21h
mongodb-backup-job-28201410-wdkq4   0/1     Completed   0            45h
mongodb-backup-job-28202770-tdgst   0/1     Completed   0            22h
[xiaowei_zhou@azure-k8s ~]$ azure-sensor-k8s -n mongo-system logs -f mongodb-0 -c mongodb
Advertised Hostname: mongodb-0.mongodb-headless.mongo-system.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 04:42:20.90 
mongodb 04:42:20.90 Welcome to the Bitnami mongodb container
mongodb 04:42:20.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 04:42:20.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 04:42:20.90 
mongodb 04:42:20.91 INFO  ==> ** Starting MongoDB setup **
mongodb 04:42:20.92 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 04:42:20.93 INFO  ==> Initializing MongoDB...
mongodb 04:42:20.95 INFO  ==> Enabling authentication...
mongodb 04:42:20.96 INFO  ==> Deploying MongoDB with persisted data...
mongodb 04:42:20.96 INFO  ==> Writing keyfile for replica set authentication...
mongodb 04:42:20.99 INFO  ==> ** MongoDB setup finished! **

mongodb 04:42:21.00 INFO  ==> ** Starting MongoDB **

{"t":{"$date":"2023-08-17T04:42:21.024+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2023-08-17T04:42:21.024+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2023-08-17T04:42:21.027+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-08-17T04:42:21.027+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2023-08-17T04:42:21.027+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2023-08-17T04:42:21.059+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"mongodb-0"}}
{"t":{"$date":"2023-08-17T04:42:21.059+00:00"},"s":"W",  "c":"CONTROL",  "id":20720,   "ctx":"initandlisten","msg":"Available memory is less than system memory","attr":{"availableMemSizeMB":2048,"systemMemSizeMB":32113}}
{"t":{"$date":"2023-08-17T04:42:21.059+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.5","gitVersion":"ff5cb77101b052fa02da43b8538093486cf9b3f7","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2023-08-17T04:42:21.059+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.4.0-1109-azure"}}}
{"t":{"$date":"2023-08-17T04:42:21.059+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/opt/bitnami/mongodb/conf/mongodb.conf","net":{"bindIp":"*","ipv6":false,"port":27017,"unixDomainSocket":{"enabled":true,"pathPrefix":"/opt/bitnami/mongodb/tmp"}},"processManagement":{"fork":false,"pidFilePath":"/opt/bitnami/mongodb/tmp/mongodb.pid"},"replication":{"enableMajorityReadConcern":true,"replSetName":"rs0"},"security":{"authorization":"enabled","keyFile":"/opt/bitnami/mongodb/conf/keyfile"},"setParameter":{"enableLocalhostAuthBypass":"false"},"storage":{"dbPath":"/bitnami/mongodb/data/db","directoryPerDB":false,"journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"logRotate":"reopen","path":"/opt/bitnami/mongodb/logs/mongodb.log","quiet":false,"verbosity":0}}}}
{"t":{"$date":"2023-08-17T04:42:21.061+00:00"},"s":"F",  "c":"STORAGE",  "id":50922,   "ctx":"initandlisten","msg":"An incomplete repair has been detected! This is likely because a repair operation unexpectedly failed before completing. MongoDB will not start up again without --repair."}
{"t":{"$date":"2023-08-17T04:42:21.061+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":50922,"file":"src/mongo/db/storage/storage_engine_init.cpp","line":87}}
{"t":{"$date":"2023-08-17T04:42:21.061+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
[xiaowei_zhou@azure-k8s ~]$

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami MongoDB container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by DesireWithin** [comment]
Hello @carrodher, I have the same issue. 
The pod keeps restarting is becasue `Readiness probe failed` and `Liveness probe failed`:
```
$> kubectl describe  stackstorm/mongodb-2
...
 Events:
   Type     Reason     Age    From               Message
   ----     ------     ----   ----               -------
   Normal   Scheduled  4m6s   default-scheduler  Successfully assigned stackstorm/mongodb-2 to app-infra-k8s-node04
   Normal   Pulled     5m21s  kubelet            Container image "harbor.XXXX/infra/mongodb:4.4.15-debian-10-r8" already present on machine
   Normal   Created    5m21s  kubelet            Created container mongodb
   Normal   Started    5m21s  kubelet            Started container mongodb
   Warning  Unhealthy  3m7s   kubelet            Readiness probe failed: command "/bitnami/scripts/readiness-probe.sh" timed out
   Warning  Unhealthy  2m32s  kubelet            Liveness probe failed: command "/bitnami/scripts/ping-mongodb.sh" timed out
```
I tried to run the  bitnami script inside the pod, here is the result:
Readiness probe:
```
$> I have no name!@mongodb-2:/$ cat /bitnami/scripts/ping-mongodb.sh
#!/bin/bash
mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval "db.adminCommand('ping')"
$> I have no name!@mongodb-2:/$ bash /bitnami/scripts/ping-mongodb.sh
Current Mongosh Log ID: 64e2c012d5575ab30296362d
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
Using MongoDB:          4.4.15
Using Mongosh:          1.5.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

{ ok: 1 }     <<<sometime my terminal( Using MobaXTerm)  is stuck here,  ctrl+C and ENTER don't work.
```
Liveness probe:
```
$> I have no name!@mongodb-1:/bitnami/scripts$ cat readiness-probe.sh
#!/bin/bash
# Run the proper check depending on the version
[[ $(mongod -version | grep "db version") =~ ([0-9]+\.[0-9]+\.[0-9]+) ]] && VERSION=${BASH_REMATCH[1]}
. /opt/bitnami/scripts/libversion.sh
VERSION_MAJOR="$(get_sematic_version "$VERSION" 1)"
VERSION_MINOR="$(get_sematic_version "$VERSION" 2)"
VERSION_PATCH="$(get_sematic_version "$VERSION" 3)"
readiness_test='db.isMaster().ismaster || db.isMaster().secondary'
if [[ ( "$VERSION_MAJOR" -ge 5 ) || ( "$VERSION_MAJOR" -ge 4 && "$VERSION_MINOR" -ge 4 && "$VERSION_PATCH" -ge 2 ) ]]; then
    readiness_test='db.hello().isWritablePrimary || db.hello().secondary'
fi
mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval "${readiness_test}" | grep 'true'
$> I have no name!@mongodb-1:/bitnami/scripts$
$> I have no name!@mongodb-1:/bitnami/scripts$ bash readiness-probe.sh
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
<<< the script is stuck here. 
```
I checked pod logs, just like Author`s logs. nothing special. 
I don't know much about mongodb, just k8s, sorry about this.
Here is all information I can give:
```
K8S: v1.26.2
MongoDB Chart Version: 13.16.2
MongoDB Chart App Version: 6.0.8
MongoDB Image tag: 4.4.15-debian-10-r8 
```

**Comment by DesireWithin** [comment]
> Hello @carrodher, I have the same issue. The pod keeps restarting is becasue `Readiness probe failed` and `Liveness probe failed`:
> 
> ```
> $> kubectl describe  stackstorm/mongodb-2
> ...
>  Events:
>    Type     Reason     Age    From               Message
>    ----     ------     ----   ----               -------
>    Normal   Scheduled  4m6s   default-scheduler  Successfully assigned stackstorm/mongodb-2 to app-infra-k8s-node04
>    Normal   Pulled     5m21s  kubelet            Container image "harbor.XXXX/infra/mongodb:4.4.15-debian-10-r8" already present on machine
>    Normal   Created    5m21s  kubelet            Created container mongodb
>    Normal   Started    5m21s  kubelet            Started container mongodb
>    Warning  Unhealthy  3m7s   kubelet            Readiness probe failed: command "/bitnami/scripts/readiness-probe.sh" timed out
>    Warning  Unhealthy  2m32s  kubelet            Liveness probe failed: command "/bitnami/scripts/ping-mongodb.sh" timed out
> ```
> 
> I tried to run the bitnami script inside the pod, here is the result: Readiness probe:
> 
> ```
> $> I have no name!@mongodb-2:/$ cat /bitnami/scripts/ping-mongodb.sh
> #!/bin/bash
> mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval "db.adminCommand('ping')"
> $> I have no name!@mongodb-2:/$ bash /bitnami/scripts/ping-mongodb.sh
> Current Mongosh Log ID: 64e2c012d5575ab30296362d
> Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
> Using MongoDB:          4.4.15
> Using Mongosh:          1.5.0
> 
> For mongosh info see: https://docs.mongodb.com/mongodb-shell/
> 
> { ok: 1 }     <<<sometime my terminal( Using MobaXTerm)  is stuck here,  ctrl+C and ENTER don't work.
> ```
> 
> Liveness probe:
> 
> ```
> $> I have no name!@mongodb-1:/bitnami/scripts$ cat readiness-probe.sh
> #!/bin/bash
> # Run the proper check depending on the version
> [[ $(mongod -version | grep "db version") =~ ([0-9]+\.[0-9]+\.[0-9]+) ]] && VERSION=${BASH_REMATCH[1]}
> . /opt/bitnami/scripts/libversion.sh
> VERSION_MAJOR="$(get_sematic_version "$VERSION" 1)"
> VERSION_MINOR="$(get_sematic_version "$VERSION" 2)"
> VERSION_PATCH="$(get_sematic_version "$VERSION" 3)"
> readiness_test='db.isMaster().ismaster || db.isMaster().secondary'
> if [[ ( "$VERSION_MAJOR" -ge 5 ) || ( "$VERSION_MAJOR" -ge 4 && "$VERSION_MINOR" -ge 4 && "$VERSION_PATCH" -ge 2 ) ]]; then
>     readiness_test='db.hello().isWritablePrimary || db.hello().secondary'
> fi
> mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval "${readiness_test}" | grep 'true'
> $> I have no name!@mongodb-1:/bitnami/scripts$
> $> I have no name!@mongodb-1:/bitnami/scripts$ bash readiness-probe.sh
> Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.0
> <<< the script is stuck here. 
> ```
> 
> I checked pod logs, just like Author`s logs. nothing special. I don't know much about mongodb, just k8s, sorry about this. Here is all information I can give:
> 
> ```
> K8S: v1.26.2
> MongoDB Chart Version: 13.16.2
> MongoDB Chart App Version: 6.0.8
> MongoDB Image tag: 4.4.15-debian-10-r8 
> ```

Oh, After I upgrade MongoDB Image tag to `6.0.8-debian-11-r12`(and clean up pvc data), the issue is gone. I think the reason is the chart version is not compatible with image tag version.
