### ISSUE TITLE
[prometheus-operator] impossible to add labels to prometheus.externalLabels 

### ISSUE THREAD

**Issue by panpann** [bitnami/charts#1851]
**Which chart**: prometheus-operator:0.10.0

**Description**

Hello,
I need to add specific labels in `prometheus.externalLabels` which, after looking at the defaults, seems to be a map, I added a key / value and when rendering my chart, helm crashs with

```
Error: YAML parse error on prometheus-operator/templates/prometheus/prometheus.yaml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
helm.go:76: [debug] error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
YAML parse error on prometheus-operator/templates/prometheus/prometheus.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:129
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/install.go:455
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:214
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:214
main.newTemplateCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/template.go:63
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

**Steps to reproduce the issue:**

1. 
```
cat << EOT > /tmp/issue-prom.yaml
prometheus:
  enabled: true
  externalLabels:
    label: "test"
EOT
```
2. `helm template test bitnami/prometheus-operator --version 0.10.0 -f /tmp/issue-prom.yaml --debug`

The problem is linked to [labels rendering](https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml#L18).
I'm not familiar with go template rendering. I looked at how the `stable/prometheus-operator` chart is handling externalLabels and [they just don't try to render variables](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L35).

I've tried to only call `toYaml` on my labels and it worked

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Comment by panpann** [comment]
I dug further, just need to replace 
`{{-` by `{{` in this line https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml#L18 and

**Comment by carrodher** [comment]
Thanks for reporting the issue and also creating the PR.
