### ISSUE TITLE
Idempotent install causes Minio chart error: spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by Routhinator** [bitnami/charts#1853]
**Which chart**:

minio 3.0.1

**Description**

Running `helm upgrade --install --force` to have an idempotent CI run fails due to invalid clusterIP spec.

**Steps to reproduce the issue:**

- Create CI job to install and configure chart and other application
- Rerun job
- Failure

**Describe the results you received:**

```
129 $ helm upgrade --install --force minio-stable bitnami/minio --namespace gitlab-runner -f charts/minio/values.yaml
130 client.go:401: Replaced "minio-stable" with kind Deployment for kind Deployment
131 Error: UPGRADE FAILED: failed to replace object: Service "minio-stable" is invalid: spec.clusterIP: Invalid value: "": field is immutable
135 ERROR: Job failed: exit code 1
```

**Describe the results you expected:**

Helm detects same version is already installed or recreates the chart with the same values.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've tried running this with and without the --reuse-values flag and it fails both ways.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @Routhinator 

Thanks so much for reporting this issue!! This is related to a known issue with Helm 3 (see the link below):

- https://github.com/helm/helm/issues/6378

I'll try to put more emphasis so they reopen the issue since it's not solved in my opinion

**Comment by Routhinator** [comment]
That explains why it happens both on the `bitnami/minio` and the `stable/minio` charts - I was going to report over there and then noticed that stable is being deprecated. Figured your chart would be more updated and was surprised when it happened here too.

Guess we wait. :)

**Comment by Routhinator** [comment]
I worked around this after reading a little more carefully. I pulled out --force and instead added --atomic

This way bad deployments are rolled back so I never have a situation where --force is required and the minio chart no longer throws this error.

**Comment by carrodher** [comment]
Thank you for sharing the solution that worked for you, it will be useful for other users.
Please, don't hesitate to reopen the issue if needed.
