### ISSUE TITLE
[bitnami/zookeeper] prometheus cannot connect to zookeeper-exporter

### ISSUE THREAD

**Issue by cccs-eric** [bitnami/charts#1856]
**Which chart**:
bitnami/zookeeper-5.3.4

**Description**

My instance of prometheus (BKPR) cannot connect to zookeeper-exporter to fetch metrics.  I get a _connect: connection refused_.  The problem is that prometheus is trying to connect to the IP of the pod using the service port (9141).  I am not sure which is the best resolution for the problem:
1- Put the prometheus annotations on the pod and use container port 8080
2- Or put the annotations on the service and use port 9141
I think the annotations should go on the service and not the pod, but I'm not sure if this will work if the replicaset is greater than 1...  That's why I'm filling in a bug report and not an actual fix.

**Steps to reproduce the issue:**

1. Deploy a new instance of the bitnami/zookeeper chart using values-production.yaml (so that metrics are enabled)
2. Use an existing prometheus (BKPR or not) or standup a new one and go under the Targets tab, you should see a target with a 'DOWN' status.

**Describe the results you received:**

Prometheus reports a target with a DOWN status.

**Describe the results you expected:**

Prometheus should be able to connect successfully using a default config of the bitnami/zookeeper chart.

**Additional information you deem important (e.g. issue happens only occasionally):**

As I mentioned earlier, I was able to get it to work by changing .Values.metrics.podAnnotations.prometheus.io/port to "8080" (instead of 9141) in values-production.yaml.  I'm not sure if this is the proper fix, or if the templates should be changed to apply the annotations to the service instead of the pod...

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by marcosbc** [comment]
Hi @cccs-eric, that seems indeed to be a fix to your issue, as the ZooKeeper Exporter does use port 8080, not 9141 as can be seen in [its Dockerfile](https://github.com/bitnami/bitnami-docker-zookeeper-exporter/blob/master/0/debian-10/Dockerfile#L18)

Since you discovered this issue, it would be awesome if you could create a PR applying the mentioned change in the `values-production.yaml` (and `values.yaml` which also seems to include the line).

**Comment by cccs-eric** [comment]
Thanks for the feedback @marcosbc. I agree that Zookeeper Exporter exposes port 8080, but I have a question regarding how prometheus should behave if we change the number of replicas of pod/zookeeper-exporter.  By default, the number of replicas is set to 1 in its [deployment](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/metrics-deployment.yaml#L9).  In that scenario, prometheus will connect to port 8080 of pod/zookeeper-exporter and everything works.  

If we change the replicas value to 2, we will have 2 instances of pod/zookeeper-exporter and each one will appear in the prometheus targets.  Prometheus will fetch metrics from each instance independently.  At the same time, service/zookeeper-exporter will have 2 endpoints (one for each instance of pod/zookeeper-exporter).  What is the proper way of handling this case?  Having 2 targets in prometheus (the 2 pods), or having a single one being service/zookeeper-exporter?

**Comment by marcosbc** [comment]
@cccs-eric As far as I know, the current implementation does not support having multiple zookeeper-exporter nodes. What is your use case for this?

If it is for making sure it scales properly, note that the ZooKeeper exporter is not meant to be publicly available and should only be used by Prometheus, having only one service should be more than enough. If needed, memory settings could be configured to match the necessary value.
