### ISSUE TITLE
[bitnami/kafka] External access no longer works with controller replicas at 0. Autodiscovery is looking for wrong service

### ISSUE THREAD

**Issue by widders** [bitnami/charts#18579]
### Name and Version

bitnami/kafka 24.0.*

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy Kafka with Zookeeper and controllers replicas to 0
Set external access to true and type to Loadbalancer

Autodiscovery must be enabled because controller replicas 0 =/= controller loadbalancer ips []
Autodiscovery fails because pod name is kafka-broker-# and serivce is kafka-external-#

Kafka pods never start because of autodiscovery but cannot disable autodiscovery because of helm validations on controller that is not in use.

### What is the expected behavior?

Either autodiscovery uses correct service name or autodiscovery can be disabled

### What do you see instead?

Crashloop on autodiscovery container failing to find service 'kafka-broker-#-external"

Cannot deploy with autodiscovery disabled.

### Additional information

There's two problems here:

- autodiscovery not getting the right service name because the STS has "-broker" added to it.
- chart cannot deploy without autodiscovery if no controller replicas are in use

**Comment by widders** [comment]
This seems to effect any configuration of external access, whatever you set controller.service.type to fails to validate with replicas 0 not equal to empty array on relevant IP, Name or nodeport options thus requiring autodiscovery be enabled. Then autodiscovery fails due to the change to the statefulset name not matching the serivce.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by electrical** [comment]
Can we please re-open this as it's an active issue.

**Comment by electrical** [comment]
Still an active issue

**Comment by simonhampe** [comment]
I have the same problem using chart version 25.3.3 and Kraft mode with 3 controllers and 3 brokers. As far as I can tell, this has nothing to do with the controller configuration, but is a fault in /templates/broker/svc-external-access.yaml:

```
metadata:
  name: {{ printf "%s-%d-external" (include "common.names.fullname" $) $i | trunc 63 | trimSuffix "-" }}
```

will result in something like "chartname-0-external"

On the other hand, the autodiscovery script running for the broker is looking for a service named `"${MY_POD_NAME}-external"`, where MY_POD_NAME is populated with `metadata.name`, which in /templates/broker/statefulset.yaml is defined as 
```
metadata:
  name: {{ printf "%s-broker" (include "common.names.fullname" .) }}
```
i.e. this will result in chartname-broker and thus look for chartname-broker-0-external in the autodiscovery.

In contrast, for controllers the file /templates/controller-eligible/svc-external-access.yaml reads
```
metadata:
  name: {{ printf "%s-controller-%d-external" $fullname $i | trunc 63 | trimSuffix "-" }}
```
so it includes an explicit infix. I assume that the same should be true for the broker external access template?

**Comment by fmulero** [comment]
Hi @simonhampe

Yes you are right, it seems that the `broker/svc-external-access.yaml` template is wrong. The name should be something like:
```yaml
  name: {{ printf "%s-broker-%d-external" (include "common.names.fullname" $) $i | trunc 63 | trimSuffix "-" }}
```

I've just create #20226 to solve it, would you like to take it a glance?
