### ISSUE TITLE
[bitnami/nginx] 15.1.1 - is having crashloopback-off issue after the deployment, any suggestions or fix for it?

### ISSUE THREAD

**Issue by eravindar12** [bitnami/charts#18587]
### Name and Version

bitnami/nginx-15.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

bitnami/nginx-15.1.1 - is having crashloopback-off issue after the deployment, any suggestions or fix for it?/

### What do you see instead?

the nignx pods are crashing intermittently - noticed this behaviour with chart version of bitname/nginx-15.1.1

**Comment by javsalgar** [comment]
Hi,

Could you add some logs or information about the issue? We are unable to reproduce the issue
