### ISSUE TITLE
[bitnami/minio] Minio gets stuck while login with GUI

### ISSUE THREAD

**Issue by renewmc** [bitnami/charts#18610]
### Name and Version

bitnami/minio 12.6.12

### What architecture are you using?

None

### What steps will reproduce the bug?

Default installation with Default-params

### Are you using any custom parameters or values?

Default-params

### What is the expected behavior?

Going to minio GUI, we should see a login-screen with a animation. providing credentials to login and to see all buckets.

### What do you see instead?

Animation is not working and when i try to login, everything freezes. 

### Additional information

This only happens with this newer kind of GUI. Every bitnami/minio chart below 11.10.20 works fine.
Only Browser which worked, was on a Safari via a macbook

**Comment by javsalgar** [comment]
Hi,

Could you add more details on the Kubernetes platform you are using?

**Comment by 51yu** [comment]
I can reproduce with k8s 1.27 - minikube when port-forward, login hang with chrome

**Comment by fmulero** [comment]
The issue is in the `kubectl port-forward` command, I don't face the issue with a regular load balancer. 
```console
$ kubectl port-forward --namespace default svc/minio 9001:9001
Forwarding from 127.0.0.1:9001 -> 9001
Forwarding from [::1]:9001 -> 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
Handling connection for 9001
E0829 09:57:03.004285   83728 portforward.go:378] error copying from remote stream to local connection: readfrom tcp6 [::1]:9001->[::1]:62223: write tcp6 [::1]:9001->[::1]:62223: write: broken pipe
Handling connection for 9001
E0829 09:57:33.003493   83728 portforward.go:346] error creating error stream for port 9001 -> 9001: Timeout occurred
Handling connection for 9001
E0829 09:57:36.531340   83728 portforward.go:346] error creating error stream for port 9001 -> 9001: Timeout occurred
E0829 09:58:03.315159   83728 portforward.go:346] error creating error stream for port 9001 -> 9001: Timeout occurred
Handling connection for 9001
E0829 09:58:33.673795   83728 portforward.go:346] error creating error stream for port 9001 -> 9001: Timeout occurred
Handling connection for 9001
E0829 09:59:04.082313   83728 portforward.go:346] error creating error stream for port 9001 -> 9001: Timeout occurred
```

After the first `broken pipe` port-forwarding can not handle properly any new request and we have to restart the command to use minio. The request causing the issue in `port-forwarding` seems the video request.

Minio project has several issues open about this topic (https://github.com/minio/console/issues/2539, https://github.com/minio/console/issues/2550) and everything points to this [kubectl issue](https://github.com/kubernetes/kubectl/issues/1368).

Nothing to do in our side.
