### ISSUE TITLE
[bitnami/harbor] template inference causes registry authentication to fail

### ISSUE THREAD

**Issue by migmartri** [bitnami/charts#1862]
After deploying harbor with TLS I noticed that I was not able authenticate via `docker login` running specifically into this issue https://github.com/goharbor/harbor/issues/3114

Note `Bearer realm="http://"` instead of `https`.

```bash
curl -X GET -I https://core.harbor.mydomain.com/v2/
HTTP/2 401
server: nginx/1.17.7
date: Mon, 27 Jan 2020 22:30:42 GMT
content-type: application/json; charset=utf-8
content-length: 87
docker-distribution-api-version: registry/2.0
set-cookie: sid=28ef0df7ace4de043eba37ec9c182e1e; Path=/; HttpOnly
www-authenticate: Bearer realm="http://core.harbor.mydomain.com/service/token",service="harbor-registry"
strict-transport-security: max-age=15724800; includeSubDomains
```

The issue seems to be that the registry config map relies on the externalURL helper which hardcodes the prefix unless externalURL already defines the protocol https://github.com/bitnami/charts/blob/449f80cf4dda6fa105b3801292ad6148ae0d69b1/bitnami/harbor/templates/_helpers.tpl#L854

In order to prevent this we could either 1) check if service.tls is enabled inside the template and use https instead or 2) validate that externalURL contains the schema (https or http). 

Thanks!

**Comment by javsalgar** [comment]
Hi,

I just created this PR that fixes the issue https://github.com/bitnami/charts/pull/1866
