### ISSUE TITLE
latest version of mongodb bitnami image not available in azuremarketplace repository

### ISSUE THREAD

**Issue by pomberer** [bitnami/charts#1869]
The latest version of mongodb from https://github.com/bitnami/azure-marketplace-charts/blob/master/upstreamed/mongodb/values-production.yaml is not available in the azuremarketplace repository.

The latest images there are:
bitnami/mongodb-exporter:0.10.0-debian-9-r77
bitnami/mongodb:4.0.14-debian-9-r0

**Comment by beltran-rubo** [comment]
Hi @pomberer 

we checked the process to populate those containers in Azure Marketplace repository and they have been already delivered. It could take some time to appear there because the promotion system in place for Azure Marketplace. Could you please double check if they are available in a couple of days?

**Comment by pomberer** [comment]
Hi @beltran-rubo 

I will check in a few days, let you know and close the issue.
Thanks for your support.

**Comment by pomberer** [comment]
Hi @beltran-rubo,

The image is still not available:
`  Warning  Failed     5s (x2 over 19s)  kubelet, aks-nodepool1-22003762-vmss000001  Failed to pull image "marketplace.azurecr.io/bitnami/mongodb:4.2.3-debian-10-r10": rpc error: code = Unknown desc = Error response from daemon: manifest for marketplace.azurecr.io/bitnami/mongodb:4.2.3-debian-10-r10 not found: manifest unknown: manifest unknown`

Regards

**Comment by beltran-rubo** [comment]
Well, the previous images were available.

The new MongoDB chart was released yesterday use those latest images that have not been published in Azure yet. Those images should be available in Azure soon, usually takes ~1-2 days to be copied & published.

**Comment by beltran-rubo** [comment]
We checked it again and the image is available now. Let us know if you find any issues.

**Comment by beltran-rubo** [comment]
@pomberer the Bitnami Helm Charts are also available in Azure Marketplace https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.mongodb-chart If you subscribe to this offer you will not find those temporary issues with the containers availability. Before the Helm Chart is available in Azure Marketplace we ensure the container images are available there.

I hope it helps.
