### ISSUE TITLE
Unable to change Container Level securityContext:

### ISSUE THREAD

**Issue by ryanhyma** [bitnami/charts#1870]
There is no option in the chart to change the container level securityContext.

**Comment by juan131** [comment]
Hi @ryanhyma 

Could you please provide a little more information? 
What specific chart are you using? Please note there are ~60 charts on this repo and they can support different configuration options.

Thanks in advance.

**Comment by ryanhyma** [comment]
Wow, didn't realize. I'm referring to the MySQL chart. It doesn't include the ability to alter the container level securityContext

**Comment by juan131** [comment]
Hi @ryanhyma 

At this moment this chart supports modifying the **securityContext** at "pod" level. See:

- https://github.com/bitnami/charts/blob/master/bitnami/mysql/templates/master-statefulset.yaml#L36
- https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml#L205
- https://github.com/bitnami/charts/blob/master/bitnami/mysql/templates/slave-statefulset.yaml#L38
- https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml#L205

Why do you need to change the **securityContext** at container level?

**Comment by ryanhyma** [comment]
I'm running tools such as kube-scan, and as I'm locking down various security settings one of the problems is with NET_RAW. I'd like to be able to add something like:
securityContext:
          capabilities:
            drop:
              - NET_RAW

**Comment by juan131** [comment]
Hi @ryanhyma 

The "capabilities" is sth to be modify at container level, so extending the current `securityContext` parameter wouldn't be an option for your issue.

Maybe we could add a new parameter, such as `containerSecurityContext` where you can define advanced setting such as the "capabilities" or the "seLinuxOptions". What do you think about this option?

**Comment by ryanhyma** [comment]
Looks good to me. A similar set of parameters for the container level security would make sense.

**Comment by juan131** [comment]
Hi @ryanhyma 

Would you contribute a PR to add this feature? I'll be glad to review it and you'll have the chance to contribute with the project.

Otherwise, I can create it for you.

**Comment by ryanhyma** [comment]
Sure, it might take a few days before I have some time.

**Comment by juan131** [comment]
No rush. Thanks

**Comment by juan131** [comment]
Hi @ryanhyma 

Did you have time to take a look at this? As I mentioned before, I don't mind creating the PR for you.

**Comment by ryanhyma** [comment]
Sorry, I haven't. I like to find some time....

**Comment by ryanhyma** [comment]
If you have time and know the code, go for it.

**Comment by juan131** [comment]
I created the PR to address it
