### ISSUE TITLE
[bitnami/wordpress] mod_expires not enabled by default in wordpress bitnami image

### ISSUE THREAD

**Issue by Freundschaft** [bitnami/charts#18707]
### Name and Version

bitnami/wordpress-17.0.7

### What architecture are you using?

None

### What steps will reproduce the bug?

```
/opt/bitnami/apache2/conf$ cat httpd.conf | grep expires
```
gives me this

```
#LoadModule expires_module modules/mod_expires.so
```
also running apachectl showed that the module is not active.

indicating that mod_expires is not enabled by default, which is probably why w3 total cache expires headers arent working. is there some way to make this module enabled by default?

### What is the expected behavior?

expires headed should be added

### What do you see instead?

no headers added

**Comment by fevisera** [comment]
Hi @Freundschaft,

Sorry for the delay. I'm trying to understand the issue you are having and reproduce the error, or what you are pursuing loading that module by default. Can you please provide more context and details, especially about what you mean by "which is probably why w3 total cache expires headers arent working"?

Thank you.

**Comment by Freundschaft** [comment]
w3 total cache requires mod_expires in order to set the expires headers for browser caching.
in the bitnami wordpress image, mod_expires is disabled by default, which is why the expires headers arent set

**Comment by fevisera** [comment]
Hi @Freundschaft,

Adding the "mod_expires" module as a default could have advantages in terms of performance and bandwidth savings, but it would also add complexity to the image usage. This decision should be based on the specific needs of your website and the user experience you aim to provide.

For guidance on customizing the httpd.conf file, you can refer to the [container documentation](https://github.com/bitnami/containers/tree/main/bitnami/wordpress#customize-this-image).

Please feel free to reach out if you have any further questions or need additional assistance.

Thank you.

**Comment by Freundschaft** [comment]
ok thanks, i thought that this is such a universally needed feature itd be good to have it enabled by default, I have already customized the httpd.conf file for myself

**Comment by fevisera** [comment]
Thank you for raising this issue. As we are not planning to implement a change for this issue, I'm closing it. Feel free to contact us with any future ideas or questions. Your input is much appreciated. 

Thanks again!
