### ISSUE TITLE
[bitnami/mariadb-galera] Add support for setting pod labels

### ISSUE THREAD

**Issue by connorearl** [bitnami/charts#1873]
You can't set pod labels using values in the mariadb-galera chart. Currently it's difficult to use network policies with this chart as I can't set custom labels for multiple deployments.

**Comment by juan131** [comment]
Hi @connorearl 

As you can see in the links below, there's a parameter (`"podAnnotations"`) that you can use to set your custom pod annotations:

- https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/values.yaml#L342
- https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/templates/statefulset.yaml#L18

I guess you're looking for a similar solution for labels.

Would you consider contributing with the project by creating a PR to add this feature? I'd be glad to review it.
