### ISSUE TITLE
[bitnami/keycloak] keycloak-config-cli can't find correct jar version in image

### ISSUE THREAD

**Issue by taha-upstart** [bitnami/charts#18733]
### Name and Version

bitnami/keycloak:13.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. deploy bitnami keycloak chart with `keycloakConfigCli.enabled=True`.
2. keycloak container runs with no issues.
3. keycloak-config-cli keeps failing at start up with error: `Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.3.jar` 
4. run a local keycloak-config-cli container from the same image `docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r20` and confirmed the latest jar there is `keycloak-config-cli-20.0.1.jar`. full list of `/opt/bitnami/keycloak-config-cli` directory are: `keycloak-config-cli-17.0.1.jar  keycloak-config-cli-19.0.3.jar  keycloak-config-cli.jar keycloak-config-cli-18.0.2.jar 
keycloak-config-cli-20.0.1.jar  licenses`
5. I tried to manually override the jar and use `keycloak-config-cli.jar` but that caused different errors. it started reporting unable to connect to http://keycloak-headless:8080/ which was not the right error. I've found the correct errors when I enabled debug logging.

### What is the expected behavior?

keycloak-config-cli find the correct jar version 'keycloak-config-cli-20.0.3.jar'

### What do you see instead?

Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.3.jar

**Comment by corico44** [comment]
Hi @taha-upstart, I have found this issue #13673 which seems to be able to solve your error. Could you try the workarounds mentioned and confirm that it works, please?
