### ISSUE TITLE
[bitnam/kafka] Kafka Kraft Mode new helm charts

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#18746]
### Name and Version

bitnami/kafka version: 24.0.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team - I have deployed Kafka Kraft mode helm charts version: 24.0.14,pods are not coming up, Please find the details below.

I have enabled below properties and I am getting below error message, Please letus know where I am doing wrong.

controller.controllerOnly : true
broker.replicaCount : 3
controller.replicaCount : 3
kraft.enabled : 3

![image](https://github.com/bitnami/charts/assets/96808632/b256123d-a169-49ba-97bc-6cb0ee179216)

![image](https://github.com/bitnami/charts/assets/96808632/a5582c55-2930-4a80-8ad7-d7a899243b92)

Thanks,

### What do you see instead?

Unable to deploy Kafka Kraft mode with new version of helm charts 24.0.14

**Comment by bharathreddy901** [comment]
Hi @migruiz4 @javsalgar  - Can you please help on above error message.

Thanks.

**Comment by migruiz4** [comment]
Hi @bharathreddy901,

Could you please provide the output of `kubectl describe pod <your-kafka-pod>`?

**Comment by migruiz4** [comment]
Hi @bharathreddy901,

You forgot to mention in the issue description that you are using Kafka 3.3 (artifactory.com/mone-crdbplat-docker-dev/bitnami/kafka:3.3).

SCRAM support for Kafka KRaft has been added in Kafka 3.5, in order to run previous versions of Kafka, you need to set the value `sasl.enabledMechanisms=PLAIN`.

**Comment by bharathreddy901** [comment]
Hi @migruiz4 - Thanks for your inputs, Its working now.

How to enable the single pod to act as both Broker + Controller.

Thanks.

**Comment by migruiz4** [comment]
Hi @bharathreddy901,

'Controller' pods are, by default, controller-eligible nodes acting as controller+broker.

```yaml
controller:
  replicaCount: 1
  #controllerOnly: false
broker:
  replicaCount: 0
```

The value `controller.controllerOnly`, which defaults to `false`, controls wether controller-eligible nodes will be deployed as `Controller+Broker` or `Controller-only`.

**Comment by bharathreddy901** [comment]
@migruiz4  -  Thank for your inputs.
