### ISSUE TITLE
Consul: chart - rename of consul-key.pem - is this on purpose?

### ISSUE THREAD

**Issue by mattjenks** [bitnami/charts#1874]
https://github.com/bitnami/charts/blob/8092657d96f92ba8fa309dfb177f77be18205b2e/bitnami/consul/templates/statefulset.yaml#L223

When applying the consul-key.pem file from the secret into a volume, the file is renamed to consul.key.pem. Is this on purpose or is this a typo?

I'd prefer the name to stay the same so that the config map configuration matches the name in the secret.

**Comment by rafariossaa** [comment]
Hi @mattjenks ,
  Thanks for noticing this. This was on purpose, but there is nothing that forces to have that exact name.
  Would you like to send a PR to change this ? It will be welcome.

Thanks forehand.
