### ISSUE TITLE
[bitnami/matomo] Authentication method for SMTP

### ISSUE THREAD

**Issue by bkreynen** [bitnami/charts#18740]
### Name and Version

bitnami/matomo 2.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the helm chart providing values for smtpHost, smtpPort, smtpUser and smtpPassword
1. Open a shell in the matomo pod and execute the command `core:test-email`

### Are you using any custom parameters or values?

Smtp has been set up with values to connect to sendgrid:
```
smtpHost: smtp.sendgrid.net
smtpPort: 465
smtpProtocol: ssl
smptUser: apikey
smtpPassword: <sendgrdi_api_key>
```

### What is the expected behavior?

A test email to be send through sendgrid

### What do you see instead?

Matomo errors with: 
```
The following From address failed: noreply@defaultHostnameIfEmpty.example.org : MAIL FROM command failed,Unauthenticated senders not allowed
  ,550,SMTP server error: MAIL FROM command failed Detail: Unauthenticated senders not allowed
   SMTP code: 550
```

### Additional information

I figured out that this seems related to the Authentication method for SMTP. If you login to the matomo website and go to cog -> General settings -> Email server settings then using the provided values the box for `Authentication method for SMTP` is not set. When settings this to `Plain` emails do work. I noticed that the documentation of the docker image does provide an environment variable for this (`MATOMO_SMTP_AUTH`) and it claims the default is `Plain`, but this does not seem to be the case.

As a work around I now use the value:
```
extraEnvVars:
  - name: MATOMO_SMTP_AUTH
    value: Plain
```
I also used the same workaround to correct the from address by the way since the chart does not provide a value to change this.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue. Would you like to submit a PR adding the value? This way we would not need to use the `extraEnvVars` section

**Comment by bkreynen** [comment]
@javsalgar I added a PR adding values for the smtp auth mechanism and for the noreply mail settings.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
