### ISSUE TITLE
[bitnami/discourse] Support for subdirectory configuration

### ISSUE THREAD

**Issue by marek-memsql** [bitnami/charts#18758]
### Name and Version

latest

### What is the problem this feature will solve?

Discourse running in Docker support running a forum in a subdirectory by setting up a reverse proxy via nginx rewrites.

https://meta.discourse.org/t/serve-discourse-from-a-subfolder-path-prefix-instead-of-a-subdomain/30507

### What is the feature you are proposing to solve the problem?

The bitnami helm chart doesn't support setting the proxy up (either via the rewrites or automatically when DISCOURSE_RELATIVE_URL_ROOT is set). Would it be possible to add support to the helm chart for the subdirectory support? Thank you!

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! I will forward this to the engineering team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, feel free to submit a PR here (and probably to the container logic in the bitnami/containers repo) and we will review it.
