### ISSUE TITLE
[bitnami/redis] Support enableServiceLinks

### ISSUE THREAD

**Issue by AnisimoffNikita** [bitnami/charts#18775]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

I've noticed that large number of services in one namespace affects on health checks because of services environment variables, and default timeouts are not enough for readiness and liveness probes.

### What is the feature you are proposing to solve the problem?

I'm proposing to add `enableServiceLinks` setting with `true` value by default. `false` will prevent from injecting of this environment variables.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! Would you like to submit a PR adding support?

**Comment by AnisimoffNikita** [comment]
@javsalgar yes, I've opened #18779
