### ISSUE TITLE
Missing information for charts on the IBM report feed

### ISSUE THREAD

**Issue by gmendel** [bitnami/charts#1878]
**Which chart**:

mongodb, postgresql-ha

**Description**

On the IBM's catalog, the sync. is looking at the following URL for additional information: https://bitnami.com/library/ibm_charts_report.json in the last few weeks

There are no entries for the above charts

**Steps to reproduce the issue:**

The charts above are not in the feed

**Describe the results you received:**

**Comment by beltran-rubo** [comment]
Hi @gmendel, thanks for reporting it. We are looking into it.

**Comment by beltran-rubo** [comment]
MongoDB issue is now in the feed as well. The PostgreSQL HA solution could take a bit more time to get fixed. We will keep you in the loop.

**Comment by beltran-rubo** [comment]
Hi @gmendel, we enabled PostgreSQL HA to the feed. Please reopen it if you find any issues with any other solution.

**Comment by gmendel** [comment]
I do not seems to have permissions to re-open

**Comment by carrodher** [comment]
Hi, yes sorry, you cannot re-open your own issues if a repo collaborator closed them. But we see the comment, please, feel free to add your thoughts in a new comment and we will reopen the issue if needed.

Thanks!
