### ISSUE TITLE
[bitnami/testlink]how to add service annotation to create a internal load balancer

### ISSUE THREAD

**Issue by Yamini-TWG** [bitnami/charts#1879]
hello, 

I am trying to install test-link in kubernets cluster using bitnami charts, I am trying to understand how to add a service.annotation  to bring up the internal load balancer. I no where seen that option in values file. 

Charts: testlink

thank you

**Comment by dani8art** [comment]
Hi @Yamini-TWG 

Thank you for opening this issue. I've created a PR in the stable repository in order to add the possibility of passing annotations to the service.

Regards.

**Comment by Yamini-TWG** [comment]
well, Thank you so much. I really appreciate the quick response

**Comment by carrodher** [comment]
Thanks for reporting the issue. It should be fixed as part of https://github.com/helm/charts/pull/20531, please don't hesitate to reopen this issue if the solution doesn't work as expected.
