### ISSUE TITLE
[bitnami/postgresql-ha] Unable to get session context error when trying to create a db from a .NET app

### ISSUE THREAD

**Issue by lubishtanid** [bitnami/charts#18807]
### Name and Version

bitnami/postgresql-ha 11.8.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I deployed Postgresql HA Helm Chart by Bitnami on my Kubernetes Cluster and did the configuration based on the provided configuration fields by the Helm chart. I'm getting an error when trying to create a db from a .NET app when using PgPool II's connection string. The error says "PID XXX Unable to get session context".

### What is the expected behavior?

I should be able to create databases from the .NET app when connecting via Pg Pool's connection string into database server.

### What do you see instead?

I can't create a database from the .NET app when connecting to Pg Pool

### Additional information

My app first creates a db if it does not exist and then migrates the data. I should mention that if I manually create the db, then the app migrates the data without problem, which proves that the connection string is correct. I tried connecting directly to Postgresql server, skipping the PgPool, and the app created the db and migrated it which I believe that the app is working as expected. I used a superuser when I tried all of these things.

This is my pg_hba.conf
```
host     all            repmgr    0.0.0.0/0    trust
host     repmgr         repmgr    0.0.0.0/0    trust
host     repmgr         repmgr    ::/0    trust
host     replication      repmgr    0.0.0.0/0    trust
host     replication      repmgr    ::/0    trust
#hostssl     all             all             0.0.0.0/0               cert
#hostssl     all             all             ::/0                    cert
host     all              all       0.0.0.0/0    trust
host     all              all       ::/0         trust
local    all              all                    trust
```
This is my pool_hba.conf
```
local    all             all                            trust
host     all             repmgr       all         trust
host     all             aio       all         scram-sha-256
host     all             wide               all         trust
host     all             pop_user           all         trust
host     all             all                all         scram-sha-256
```
Is it possible that I should modify the code when connecting to a connection pooler as opposed to connecting to a postgresql server to get the session context?

**Comment by lubishtanid** [comment]
@javsalgar Hello!

My fellow developer opened an issue on dotnet/efcore, and someone there mentioned that the issue might be pgPool related. Could you give a look to this issue dotnet/efcore#31545 ?
Thanks in advance

**Comment by javsalgar** [comment]
Then I'd say that it could be an issue with pgpool itself, I would also check with the upstream pgpool devs

https://www.pgpool.net/mantisbt/login_page.php
