### ISSUE TITLE
[bitnami/rabbitmq] ServiceMonitor: <.Values.serviceMonitor.annotations>: nil pointer evaluating interface {}.annotations

### ISSUE THREAD

**Issue by kallaics** [bitnami/charts#18800]
### Name and Version

bitnami/rabbitmq     >=12.0.13 <=12.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Steps to reproduce:

Deploy the Helm chart with the following configuration:

```bash
helm install test bitnami/rabbitmq --set metrics.enabled=true --set metrics.serviceMonitor.enabled=true --dry-run
```

Error message:

```
Error: INSTALLATION FAILED: template: rabbitmq/templates/servicemonitor.yaml:14:19: executing "rabbitmq/templates/servicemonitor.yaml" at <.Values.serviceMonitor.annotations>: nil pointer evaluating interface {}.annotations
```

The issue looks like the structure changed based on the values.yaml and the servicemonitor.yaml wasn't updated.

### Are you using any custom parameters or values?

--set metrics.enabled=true 
--set metrics.serviceMonitor.enabled=true

### What is the expected behavior?

To deploy the serviceMonitor resource.

### What do you see instead?

annotation templating error

**Comment by javsalgar** [comment]
Hi! 

Thank you so much for the PR! The team will take a look
