### ISSUE TITLE
[bitnami/keycloak] External RDS connection with IAM Role instead of user and password

### ISSUE THREAD

**Issue by avnerv** [bitnami/charts#18808]
### Name and Version

bitnami/keycloak 15.1.0

### What is the problem this feature will solve?

Refrain from using a username and password for managed AWS services like RDS that support IAM role authentication

### What is the feature you are proposing to solve the problem?

Add the option to auth with external RDS with IAM role

**Comment by javsalgar** [comment]
Hi,

Which is the keycloak configuration setting that allows that? Or is it a change in the connection string?

**Comment by avnerv** [comment]
> Hi,
> 
> Which is the keycloak configuration setting that allows that? Or is it a change in the connection string?

Hi, 
I would say is a change in the connection string. https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L1046

My goal is to enable authentication using my external Postgres database (AWS RDS) through an AWS IAM role, rather than using traditional username and password credentials.

**Comment by dgomezleon** [comment]
Hi @avnerv ,

I've just opened an internal task to address it. We will keep you posted on any news.

Of course, feel free to open a PR if you want to contribute.

**Comment by dalbani** [comment]
For those interested, this is how you can configure Keycloak to use IAM authentication to connect to RDS:
```
$ ./bin/kc.sh start-dev --db=postgres --db-driver=software.amazon.jdbc.Driver --db-url 'jdbc:aws-wrapper:postgresql://keycloak-0.xxx.eu-west-1.rds.amazonaws.com:5432/keycloak\?user=keycloak\&wrapperPlugins=iam' --transaction-xa-enabled=false
```

In case you need to debug what's going on, you can prepend the following to the command:
```
KC_LOG_LEVEL=INFO,software.amazon.jdbc:FINEST
```
And put `--verbose` after `kc.sh`.

This relies on this AWS RDS JDBC driver: https://github.com/awslabs/aws-advanced-jdbc-wrapper.
So it needs to be installed in the `providers` directory.
What make it tricky is that the POM (e.g. https://repo1.maven.org/maven2/software/amazon/jdbc/aws-advanced-jdbc-wrapper/2.3.1/aws-advanced-jdbc-wrapper-2.3.1.pom) doesn't express the necessary dependencies.
So one has to look at https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/build.gradle.kts to have a guess.
From what I could test `software.amazon.awssdk:rds` was enough (for IAM authentication).

One way to fetch JARs for `software.amazon.awssdk:rds` and its (transitive) dependencies, is to use:
```
$ ./mvnw org.apache.maven.plugins:maven-dependency-plugin:3.6.1:get -Dartifact=software.amazon.awssdk:rds:2.22.3
$ cp ~/.m2/repository/software/amazon/awssdk/*/*/*.jar providers/
```

As for what changes would need to implement in the chart, I'm not so sure.
There's definitely an issue with `jdbc:postgresql:..." being hard coded in https://github.com/bitnami/containers/blob/9f6278e4abadcf4ff63eb42310739646e1ed1485/bitnami/keycloak/22/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L146.
If I find the time, I may have a try and propose an MR 😇

**Comment by avnerv** [comment]
I’m trying to configure the JDBC connection string via Helm values, but I’m unsure how to do it. The values.yaml file at [line 134](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L134) doesn’t clearly indicate how to set parameters like sslmode=require or aws_iam_auth_enabled=true.

I need to set a connection string like:

`jdbc:postgres://<RDS_ENDPOINT>:5432/<DB_NAME>?user=<DB_USER>&sslmode=require&aws_iam_auth_enabled=true`

Could someone clarify how to achieve this through the Helm chart values?
