### ISSUE TITLE
External Redis liveness check for airflow doesn't work with custom Username

### ISSUE THREAD

**Issue by hydro47** [bitnami/charts#1881]
**Which chart**:

bitnami/airflow

**Description**

If I choose to connect airflow to redis, username can't be specified

**Steps to reproduce the issue:**

1. In values.yaml:
  * set `redis.enabled` to false
  * set externalRedis to point to an existing redis server
2. helm install --name airflow-ddp -f values.yaml bitnami/airflow
3. kubectl get pods | grep scheduler  # to find the pod name
4. kubectl logs -f <pod_name>

**Describe the results you received:**

Scheduler and worker keep failing on liveness check, and restarting.
Logs contain:
```
airflow INFO  ==> Waiting for Redis host...
```

Pods looks like:

```
airflow-ddp-scheduler-8769c7bcb-gldqn          1/1     Running   9          50m
airflow-ddp-web-86c5cdc58d-92rkk               1/1     Running   0          50m
airflow-ddp-worker-0                           0/1     Running   11         50m
```

**Describe the results you expected:**

I expected to have the ability to specify username for redis, authenticate by username and password.
Scheduler and worker should connect to external redis, should not periodically restart because of connection error.
Scheduler and worker should be live and able to run DAGs via external redis.

**Additional information you deem important (e.g. issue happens only occasionally):**

--

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```

Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8", GitCommit:"0c6d31a99f81476dfc9871ba3cf3f597bec29b58", GitTreeState:"clean", BuildDate:"2019-07-08T08:46:01Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10+IKS", GitCommit:"18e8565daf60eb3a20c0ac29a7d3a93622659e4d", GitTreeState:"clean", BuildDate:"2020-01-16T04:08:27Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @hydro47 

If you take a look to the scheduler's deployment manifest (lines 137 to 146 in the link below), you'll find out that it will try to retrieve the credentials from a secret when using a external Redis.

- https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/deployment-scheduler.yaml

That secret definition can be found in the link below, and you'll find that it uses the parameter `externalRedis.password` to add the password for Redis:

- https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/secret-externalredis.yaml

Therefore, you just need to add the password to access your external Redis using the parameter `externalRedis.password`.

**Comment by hydro47** [comment]
Hi @juan131,
does this mean the username+password combination needs to be stored in the password field?
I have troubles just with specifying `username` that leads to `REDIS_USERNAME` env variable.

Thank you for the swift answer.

**Comment by juan131** [comment]
Hi @hydro47 

This chart assumes there's no "username" in the Redis authentication. Only a password is required.

**Comment by hydro47** [comment]
Hi @juan131 
Thanks for clarifying this.
What can be done to accomodate 3rd party redis services that have mandatory username?

**Comment by juan131** [comment]
Hi @hydro47 

I created a PR to provide a solution for your specific scenario.

**Comment by hydro47** [comment]
@juan131 Thank you very much for getting this done so quickly!

**Comment by juan131** [comment]
You're welcome @hydro47 

Thank you for providing feedback about the chart

**Comment by hydro47** [comment]
@juan131  is there any document with a guideline on how to contribute?

**Comment by juan131** [comment]
No guidelines so far @hydro47 

You just need to:

- Fork the repo
- Clone your fork
- Create a branch and do whatever change you want to propose
- Send a PR

Then someone from the team will review your PR and guide you through the required changes so we can merge your PR.

It would be nice if you install git-hooks once you clone the repo, since you'll find out that we have certain minimal verification tests using them:

- https://github.com/bitnami/charts/tree/master/githooks
