### ISSUE TITLE
[bitnami/mariadb-galera] Differing app versions between helm versions

### ISSUE THREAD

**Issue by andrew-landsverk-win** [bitnami/charts#1882]
**Which chart**: mariadb-galera

**Description**

This is maybe more of a question.. I routinely upgrade my helm apps in our dev cluster, typically just selecting latest and letting it go. I notice that the mariadb-galera chart versions will go back an forth between 10.3.x and 10.4.x. This causes issues because it will fail starting new nodes on an older app version. Is there a reason for releasing newer chart versions targeting older mariadb versions?

Thanks!

![image](https://user-images.githubusercontent.com/60662463/73777603-64f52f80-474f-11ea-8c3a-8ebfa6eb04e2.png)

**Comment by juan131** [comment]
Hi @andrew-landsverk-win 

We are very sorry for this error. 

There was an issue in our internal metadata system that was marking both `10.3` and `10.4` branches as the latest version to update in the chart. Therefore, it was being automatically updating the app version in a wrong way.

We fixed it and created the corresponding tests to avoid this to happen again. From now on, this chart will updated with the branch `10.4` releases.

Check new latest version: https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/Chart.yaml

It will need some hours to be updated in the chart repo index so you can download this latest version using `helm update` command.

We also check the rest of the charts of the Bitnami catalog, and this was the unique chart affected by this issue.

Thanks so much for reporting it and sorry for the inconveniences.

**Comment by andrew-landsverk-win** [comment]
@juan131 Thanks for the fast turn around time on this one! Looks like the latest is showing the right version:

![image](https://user-images.githubusercontent.com/60662463/73851464-2022d480-47f3-11ea-98d1-7d0cd4c73e88.png)

**Comment by juan131** [comment]
Great @andrew-landsverk-win ! Thank you for reporting it!! 

I proceed to close this issue as 'solved' but please do not hesitate to reopen it if you face any other weird behaviour in the chart versioning.
