### ISSUE TITLE
[bitnami/external-dns] Upgrading to 6.24.1 removes the defined podLabels from the deployment

### ISSUE THREAD

**Issue by Mahagon** [bitnami/charts#18827]
### Name and Version

bitnami/external-dns 6.24.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Define podLables
2. Deploy external-dns helm chart in version 6.23.4
3. Upgrade to 6.24.1

### Are you using any custom parameters or values?

![image](https://github.com/bitnami/charts/assets/874007/38f02234-eacb-4171-94fd-ec84760781ec)

### What is the expected behavior?

Defined podLabels should be set

### What do you see instead?

Values set in podLabels getting removed

![image](https://github.com/bitnami/charts/assets/874007/e503ac9a-6977-4c21-b58a-a13f98738706)

### Additional information

Guessing this commit caused the issue:
https://github.com/bitnami/charts/commit/a0f8f0ea81c60a0a915424184adfc031acf475f8

podLabels are missing in the deployment:

https://github.com/bitnami/charts/blob/main/bitnami/external-dns/templates/dep-ds.yaml#L15

**Comment by juan131** [comment]
Thanks @Mahagon !! I just replied you in the associated PR

**Comment by Mahagon** [comment]
It's working fine, podlabels were just removed from the deployment/daemonset
