### ISSUE TITLE
[bitnami/kafka] executing "kafka/templates/broker/svc-headless.yaml" at <.Values.worker.podLabels>: nil pointer evaluating interface {}.podLabels

### ISSUE THREAD

**Issue by ewertonhm** [bitnami/charts#18843]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka --set zookeeper.enabled=false --set replicaCount=3 --set externalZookeeper.servers=zookeeper.zookeeper.svc.cluster.local --set controller.controllerOnly=false --set controller.zookeeperMigrationMode=true --set broker.replicaCount=1

### Are you using any custom parameters or values?

--set zookeeper.enabled=false --set replicaCount=3 --set externalZookeeper.servers=zookeeper.zookeeper.svc.cluster.local --set controller.controllerOnly=false --set controller.zookeeperMigrationMode=true --set broker.replicaCount=1

### What do you see instead?

helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka --set zookeeper.enabled=false --set replicaCount=3 --set externalZookeeper.servers=zookeeper.zookeeper.svc.cluster.local --set controller.controllerOnly=false --set controller.zookeeperMigrationMode=true --set broker.replicaCount=1
Pulled: registry-1.docker.io/bitnamicharts/kafka:25.1.0
Digest: sha256:e1edd29642a85a2fef861aeb37a54580a854de05607b5137537549a0dbec07f5
Error: INSTALLATION FAILED: template: kafka/templates/broker/svc-headless.yaml:34:33: executing "kafka/templates/broker/svc-headless.yaml" at <.Values.worker.podLabels>: nil pointer evaluating interface {}.podLabels

### Additional information

Looks like its missing the worker.podLabels variable in the default values

**Comment by juan131** [comment]
Thanks for reporting it! I just created a PR to address this ASAP
