### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Bug in template: nil pointer evaluating interface {}.serviceMonitor

### ISSUE THREAD

**Issue by artazar** [bitnami/charts#18847]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Take the latest version of rabbitmq-cluster-operator chart 3.7.0
2. Try to install it with these values:
```
helm template --set clusterOperator.metrics.enabled=true --set clusterOperator.metrics.serviceMonitor.enabled=true . | kubectl apply --dry-run -f -
```
3. See the error:
```
Error: template: rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml:11:30: executing "rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml" at <.Values.metrics.serviceMonitor.labels>: nil pointer evaluating interface {}.serviceMonitor
```

### Are you using any custom parameters or values?

--set clusterOperator.metrics.enabled=true --set clusterOperator.metrics.serviceMonitor.enabled=true

### What is the expected behavior?

Chart is deployed successfully

### What do you see instead?

```
Error: template: rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml:11:30: executing "rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml" at <.Values.metrics.serviceMonitor.labels>: nil pointer evaluating interface {}.serviceMonitor
```

### Additional information

Bug in templates/cluster-operator/servicemonitor.yaml line 11:
```
  {{- $labels := merge .Values.metrics.serviceMonitor.labels .Values.commonLabels }}
```

should be:
```
  {{- $labels := merge .Values.clusterOperator.metrics.serviceMonitor.labels .Values.commonLabels }}
```

**Comment by juan131** [comment]
Thanks for reporting the issue! Reviewing the associated PR
