### ISSUE TITLE
[bitnami/grafana-loki] Add existingConfigmap NGINX option for Loki gateway

### ISSUE THREAD

**Issue by tonyjsolano** [bitnami/charts#18846]
### Name and Version

bitnami/grafana-loki 2.11.0

### What is the problem this feature will solve?

I currently have a need to adjust the following NGINX HTTP settings

- proxy_read_timeout 
- proxy_connect_timeout 
- proxy_send_timeout 
- client_max_body_size
- And possibly others

But there is no way for me to set these settings via the HELM chart and configuring the configmap that is created when this chart is deployed will overwrite the nginx.conf

### What is the feature you are proposing to solve the problem?

Have the ability to use an external Configmap similar to 
```
loki.existingConfigmap
```
Make one for the gateway
```
gateway.existingConfigmap
```
And allow the use of a custom nginx.conf

### What alternatives have you considered?

I have not considered many other alternatives since this seems to be the standard pattern for all the bitnami charts... 

Could possibly set the chart to 
```
gateway.enabled: false
```
And roll my own container with the new nginx config

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the engineering team. However, as it is not a critical feature, we cannot guarantee an ETA. However, if you want to speed up the process, would you like to submit a PR?

**Comment by tonyjsolano** [comment]
Here is the PR 

https://github.com/bitnami/charts/pull/18879 

Thank you

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
