### ISSUE TITLE
[bitnami/kafka] bundling the latest release with latest dependency release

### ISSUE THREAD

**Issue by Hmr-ramzi** [bitnami/charts#1885]
**Which chart**:

Currently, the available release available on the helm repo is 7.2.0. The latest release is 7.2.1

**Description**
Please, bundle it to the helm repo

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**
The version should be 7.2.1 was dependency of zookeeper 5.4.0

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by rafariossaa** [comment]
Hi,
  It is not very clear to me what is the issue.
  The current version of kafka chart is 7.1.2, that depends on zookeeper chart.
  If you do:
```
    helm repo add bitnami  https://charts.bitnami.com/bitnami
    helm dependency update
```
 You will get zookeeper 5.4.0 in the chart directory.
 Could you elaborate a little bit ?

Best regards,

**Comment by Hmr-ramzi** [comment]
Hi @rafariossaa 

If you reference to the helm repo. You will find that the available version for Kafka chart is 7.2.0 -> it should be 7.2.1 as per the latest release of the kafka chart. Also, the chart is bundled to the helm repo (bundled with its zookeeper dependency ). So all i am asking is that the helm repo of bitnami has kafka latest version bundled there

**Comment by Hmr-ramzi** [comment]
@juan131 Any ideas? I remember last time i contributed to the kafka chart it was automatically bundled to the newer versions on the helm repo

**Comment by Hmr-ramzi** [comment]
Thanks to @juan131 Issue has been resolved.

**Comment by rafariossaa** [comment]
Hi @Hmr-ramzi ,
  There was a problem in our internal pipeline and the updates weren't pushed to the chart repo.

  Thanks for noticing this.
