### ISSUE TITLE
[bitnami/keycloak] chart is delivered with outdated metrics spi package

### ISSUE THREAD

**Issue by ikatlinsky** [bitnami/charts#18855]
### Name and Version

bitnami/keycloak:16.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run keycloak 22 with the latest chart version
2. Try to access /realms/master/metrics endpoint
3. 500 error is displayed as a result

### What is the expected behavior?

Realms metrics should be displayed

### What do you see instead?

Instead of the metrics we receive 500 error response

### Additional information

The issue is due to the usage of https://github.com/aerogear/keycloak-metrics-spi of version 3.0.0, instead of 4.0.0

**Comment by fevisera** [comment]
Hi @ikatlinsky,

I was unable to replicate the issue you mentioned. Here are the steps I followed:
```
$ helm install my-release oci://registry-1.docker.io/bitnamicharts/keycloak
$ export HTTP_SERVICE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[?(@.name=='http')].port}" services my-release-keycloak)
$ kubectl port-forward --namespace default svc/my-release-keycloak ${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT} &
```
After that, I successfully accessed `http://localhost/realms/master/metrics`, which retrieved a variety of metrics, including:
```
...
keycloak_response_created{code="200",method="GET",resource="realms,realms/master",} 1.69401725952E9
keycloak_response_created{code="200",method="GET",resource=",welcome-content/bug.png",} 1.694017567466E9
keycloak_response_created{code="200",method="GET",resource="realms,realms/master/metrics",} 1.694017589541E9
```
Please let me know if I overlooked anything or if there is additional information you would like to provide.

Thanks.

**Comment by ikatlinsky** [comment]
@fevisera thanks, i will check it one more time on my side and get back to you

**Comment by ikatlinsky** [comment]
@fevisera hi, I checked on image 22.0.1-debian-11-r30 and it is working correctly, as delivered with spi 4.0.0, the issue is valid for 22.0.1-debian-11-r0.

we can close this issue, thank you
