### ISSUE TITLE
[bitnami/sealed-secrets] Missing period in template

### ISSUE THREAD

**Issue by SammyA** [bitnami/charts#18851]
### Name and Version

bitnami/sealed-secrets 1.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

install chart v1.5.0 with values podAnnotations set

### Are you using any custom parameters or values?

podAnnotations

### What is the expected behavior?

installs chart

### What do you see instead?

`UPGRADE FAILED: template: sealed-secrets/templates/deployment.yaml:25:32: executing "sealed-secrets/templates/deployment.yaml" at <.ValuespodAnnotations>: wrong type for value; expected map[string]interface {}; got interface {}`

### Additional information

https://github.com/bitnami/charts/blame/1db7ab9676df504d27f49b76c6df7047c84859b0/bitnami/sealed-secrets/templates/deployment.yaml#L25 is missing a period between values and podAnnotations

**Comment by juan131** [comment]
Thanks for reporting it! I just created a PR to address this ASAP
