### ISSUE TITLE
[bitnami/redis] Accidental Rollback of redis image from 7.2 to 7.0

### ISSUE THREAD

**Issue by yasmin-ravenwolfe** [bitnami/charts#18873]
### Name and Version

bitnami/redis

### What architecture are you using?

None

### What steps will reproduce the bug?

The same accidental downgrade fixed in the recent [redis-cluster](https://github.com/bitnami/charts/pull/18872) also occured in the last [redis chart release](https://github.com/bitnami/charts/commit/b2beb14fd4114585099af01b13ed91dd486c3e96).

Related to redis-cluster issue [18861](https://github.com/bitnami/charts/issues/18861) 

### What do you see instead?

```
redis-cluster 13:53:10.51 INFO  ==> ** Redis setup finished! **
1:C 25 Aug 2023 13:53:10.556 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Aug 2023 13:53:10.556 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Aug 2023 13:53:10.556 # Configuration loaded
1:M 25 Aug 2023 13:53:10.556 * monotonic clock: POSIX clock_gettime
1:M 25 Aug 2023 13:53:10.557 * Node configuration loaded, I'm 6d7e424e4a2f8f25bb5fb40d426da3f07e46f7be
```

**Comment by aoterolorenzo** [comment]
Hi @yasmin-ravenwolfe ,

I understand that this is still happening in the latest version of the chart? Have you perform a `helm repo update`before installing it? Had you deleted any persiscente (pvc's)? This is just to be sure and directly create an internal task in case you did and the problem persist.

**Comment by FraPazGal** [comment]
Hello @yasmin-ravenwolfe! Indeed this was an error in our side. The issue should now be solved though you can check https://github.com/bitnami/charts/issues/18861#issuecomment-1697753550 explaining in depth the error. Sorry for any inconvenience this may have caused!
