### ISSUE TITLE
[bitnami/redis] fail to render when commonLabels or podLabels is a string

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#18888]
### Name and Version

bitnami/redis 18.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

podLabels or commonLabels is a string (see below).

helm template -f str-pod-labels.yaml bitnami/redis

### Are you using any custom parameters or values?

``` 
master:
  podLabels: |
    toto: tutu
``` 

### What is the expected behavior?

before e3c23350ca2a96918c40265674cb53e58ff42183, commonLabels & podLabels could be strings containing go-template and would be rendered correctly.

After said commit, this is not working anymore because of various use of `merge` that only accepts dicts :
```
   {{- $podLabels := merge .Values.master.podLabels .Values.commonLabels }}
``` 

 

### What do you see instead?

fail

### Additional information

this impacts all charts upgraded to bitnami/common 2.9.0

**Comment by jouve** [comment]
@javsalgar  this issue was opened with redis as an example, but it applies to all charts in the repo ([nginx](https://github.com/bitnami/charts/blob/main/bitnami/nginx/templates/deployment.yaml#L23), [postgres](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/primary/statefulset.yaml#L25), etc)

**Comment by juan131** [comment]
Thanks for reporting the issue. Let's continue this conversation in the associated PR.
