### ISSUE TITLE
[bitnami/redis] tls.autoGenerated

### ISSUE THREAD

**Issue by Bec-k** [bitnami/charts#18905]
### Name and Version

bitnami/redis version: 17.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Generate certificate with autoGenerate option and wait until it expires :D

### Are you using any custom parameters or values?

tls.autoGenerated=true

### What is the expected behavior?

Certificate do not expire or automatically re-generated to avoid expiration.

### What do you see instead?

I see that certificate have expired and slave nodes in a cluster can't connect to master, master is saying that certificate have expired.

### Additional information

Now investigating where that certificate is generated on deployment via helm chart, to manually launch it and then put into crontab or some scheduled kubernetes task. Possibly create some much longer lifetime for a new certificate.

**Comment by Bec-k** [comment]
I have found this `genCA "redis-ca" 365`, it seems that default certificate is generated for 1 year. Something that is re-generating it after 1 year?

**Comment by Bec-k** [comment]
Where is that `genCA` utility comes from? It is used in template, i don't see it in the chart. Neither on my linux system.

**Comment by Bec-k** [comment]
Ok i have found it. You are using built-in template function of helm itself, located here:
https://helm.sh/docs/chart_template_guide/function_list/#genca

**Comment by Bec-k** [comment]
Ok, i have regenerated certs, will have to propagate them now in configs...
This is kinda unexpected. Regenerated to 10 years instead. :D

**Comment by javsalgar** [comment]
Hi,

Thanks for the informaition! Would you like to submit a PR increasing the default certificate lifetime?

**Comment by manolitto** [comment]
> Ok, i have regenerated certs, will have to propagate them now in configs... This is kinda unexpected. Regenerated to 10 years instead. :D

Having exactly the same issue. How did you achieve that regeneration for 10 years? Could you share the helm command please?
