### ISSUE TITLE
[bitnami/kafka] Unable to deploy Kafka with Latest Helm Charts 25.1.2

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#18901]
### Name and Version

bitnami/kafka version: 25.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team  - We are unable to deploy Kafka with newer version of helm charts(25.1.2), I am getting below error. Please check.

![image](https://github.com/bitnami/charts/assets/96808632/ba36b318-8ab1-4db2-aed0-14b4c72f7cdb)

### What do you see instead?

Error while deploying kafka

**Comment by javsalgar** [comment]
Hi,

Did you run helm dep build to ensure that you are using the latest version of the `common` chart?

**Comment by bharathreddy901** [comment]
Hi @javsalgar - Can you please share that command to deploy commn chart.

I am using below command to deploy Kafka,Zookeper and common chart from long time.

helm install kafka ./ -n kafka-upgrade

**Comment by javsalgar** [comment]
Inside the folder, run 

```
helm dep build
```

**Comment by bharathreddy901** [comment]
Hi @CeliaGMqrz - Please help on above error.

**Comment by bharathreddy901** [comment]
Hi @migruiz4 - Please find the out below. I am not getting same output for 'helm dep update' not sure where it is wrong.

![image](https://github.com/bitnami/charts/assets/96808632/4663cb76-3784-49d5-ba62-8f0935e19376)

[root@rr32st-master0 kafka]$ cat ./Chart.lock
dependencies:
- name: zookeeper
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.1.0
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.9.0
digest: sha256:a54db8d2946ff889eaa08317cdc9eccbfe55722b08c147ee0799925cd1b43c93
generated: "2023-08-23T10:11:09.64327+02:00"
[root@rr32st-master0 kafka]$ ls -la ./charts
total 0
drwxrwxr-x. 4 root root  37 Aug 28 11:59 .
drwxrwxr-x. 4 root root 128 Aug 28 08:23 ..
drwxrwxr-x. 3 root root  96 Aug 26 11:45 common
drwxrwxr-x. 3 root root 114 Aug 26 11:45 zookeeper
[root@rr32st-master0 kafka]$ cat ./Chart.yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: jmx-exporter
      image: docker.io/bitnami/jmx-exporter:0.19.0-debian-11-r49
    - name: kafka-exporter
      image: docker.io/bitnami/kafka-exporter:1.7.0-debian-11-r85
    - name: kafka
      image: docker.io/bitnami/kafka:3.5.1-debian-11-r25
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.25.12-debian-11-r29
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r43
apiVersion: v2
appVersion: 3.5.1
dependencies:
- condition: zookeeper.enabled
  name: zookeeper
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Kafka is a distributed streaming platform designed to build real-time pipelines and can be used as a message broker or as a replacement for a log aggregation solution for big data applications.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: kafka
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kafka
version: 25.1.1
[root@rr32st-master0 kafka]$

**Comment by bharathreddy901** [comment]
Hi @migruiz4 - For our k8s cluster we don't have internet to download the charts. I am manually downloading the charts from gitbub and moving to cluster.

**Comment by bharathreddy901** [comment]
Hi @migruiz4 - I have copied the latest versions of common & zookeeper charts. Still the same issue.

![image](https://github.com/bitnami/charts/assets/96808632/e398b328-cad4-4cb4-89b3-01468c1922f2)

**Comment by bharathreddy901** [comment]
Hi @migruiz4 - Any update on above error?

**Comment by migruiz4** [comment]
Hi @bharathreddy901,

I'm sorry but I'm unable to reproduce your error. Is it possible you have introduced any modifications or custom values?
```console
$ git clone https://github.com/bitnami/charts
Cloning into 'charts'...
remote: Enumerating objects: 262542, done.
remote: Counting objects: 100% (54956/54956), done.
remote: Compressing objects: 100% (1057/1057), done.
remote: Total 262542 (delta 54054), reused 54063 (delta 53847), pack-reused 207586
Receiving objects: 100% (262542/262542), 1.75 GiB | 19.86 MiB/s, done.
Resolving deltas: 100% (191542/191542), done.
$ cp -rf charts/bitnami/kafka /tmp/kafka
$ mkdir /tmp/kafka/charts
$ cp -rf charts/bitnami/common /tmp/kafka/charts 
$ cp -rf charts/bitnami/zookeeper /tmp/kafka/charts 
$ cd /tmp/kafka            
$ helm install my-release .
NAME: my-release
LAST DEPLOYED: Thu Aug 31 08:38:31 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: kafka
CHART VERSION: 25.1.4
APP VERSION: 3.5.1

** Please be patient while the chart is being deployed **

Kafka can be accessed by consumers via port 9092 on the following DNS name from within your cluster:

    my-release-kafka.default.svc.cluster.local

Each Kafka broker can be accessed by producers via port 9092 on the following DNS name(s) from within your cluster:

    my-release-kafka-controller-0.my-release-kafka-controller-headless.default.svc.cluster.local:9092
    my-release-kafka-controller-1.my-release-kafka-controller-headless.default.svc.cluster.local:9092
    my-release-kafka-controller-2.my-release-kafka-controller-headless.default.svc.cluster.local:9092

The CLIENT listener for Kafka client connections from within your cluster have been configured with the following security settings:
    - SASL authentication

To connect a client to your Kafka, you need to create the 'client.properties' configuration files with the content below:

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="user1" \
    password="$(kubectl get secret my-release-kafka-user-passwords --namespace default -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)";

To create a pod that you can use as a Kafka client run the following commands:

    kubectl run my-release-kafka-client --restart='Never' --image docker.io/bitnami/kafka:3.5.1-debian-11-r35 --namespace default --command -- sleep infinity
    kubectl cp --namespace default /path/to/client.properties my-release-kafka-client:/tmp/client.properties
    kubectl exec --tty -i my-release-kafka-client --namespace default -- bash

    PRODUCER:
        kafka-console-producer.sh \
            --producer.config /tmp/client.properties \
            --broker-list my-release-kafka-controller-0.my-release-kafka-controller-headless.default.svc.cluster.local:9092,my-release-kafka-controller-1.my-release-kafka-controller-headless.default.svc.cluster.local:9092,my-release-kafka-controller-2.my-release-kafka-controller-headless.default.svc.cluster.local:9092 \
            --topic test

    CONSUMER:
        kafka-console-consumer.sh \
            --consumer.config /tmp/client.properties \
            --bootstrap-server my-release-kafka.default.svc.cluster.local:9092 \
            --topic test \
            --from-beginning
```

**Comment by bharathreddy901** [comment]
Hi @migruiz4  - I have not done any modifications or custom values to the helm charts. Just I am changing the docker image name and deploying it. I am using latest image from bitnami(bitnami/kafka:3.5.1-debian-11-r35).

Not sure where it is going wrong.

Thanks for input & support.
