### ISSUE TITLE
MongoDB Upgrade Plan

### ISSUE THREAD

**Issue by emahdij** [bitnami/charts#18946]
### Name and Version

bitnami/mongodb:7.14.1

### What is the problem this feature will solve?

I'm currently using the  MongoDB Bitnami Helm chart (version 7.14.1) for my project. I'm interested in upgrading my MongoDB version from 4.4 to 6. My question is whether it's essential to update the Helm chart alongside the MongoDB upgrade.

Additionally, I'm curious if there's a method to execute this upgrade without experiencing any downtime. I have reviewed the documentation, but unfortunately, I couldn't locate any relevant information regarding these matters.

### What is the feature you are proposing to solve the problem?

Please add the update plan part to your documentation.

**Comment by carrodher** [comment]
In terms of the Helm chart, any new major version upgrades are documented in [this section](https://github.com/bitnami/charts/tree/main/bitnami/mongodb#upgrading) of the REAMDE. Apart from that, it would be nice to take into account any consideration required by MongoDB itself.
