### ISSUE TITLE
[bitnami/wordpress] HTTPS in WordPress Address and Site Address

### ISSUE THREAD

**Issue by Teeptrak** [bitnami/charts#18959]
### Name and Version

bitnami/wordpress:17.1.4

### What is the problem this feature will solve?

After checking the Bitnami WordPress Docker Image and helm values, I couldn't find a way to have [WordPress Address](https://wordpress.teeptrak.com/wp-admin/options-general.php#siteurl) and [Site Address](https://wordpress.teeptrak.com/wp-admin/options-general.php#home) to use HTTPS.

wp-config.php seems to be hardcoded with HTTP.

I tried using extraEnvVars:
```yaml
  - name: WORDPRESS_ENABLE_HTTPS
    value: 'yes'
```
And also "wordpressScheme: https" but it's not changing anything.
Either I'm doing something wrong or the feature is not available.

Thank you!

### What is the feature you are proposing to solve the problem?

Helm values or ENV that would change wp-admin.php HTTP to HTTPS.

### What alternatives have you considered?

None yet

**Comment by fevisera** [comment]
Hi @Teeptrak,

The feature you refer to appears to be already available and can be configured using the `wordpressScheme: https` setting. After setting this value, when I navigate to `https://127.0.0.1/wp-admin/options-general.php` I see the `https` is included in the URL fields:

![image](https://github.com/bitnami/charts/assets/43246350/30c129ab-b44b-4eac-9434-538d9660ba04)

If you are referring to a different feature or functionality, please provide more details, and I will be happy to assist you further.

Thank you for getting in touch with us.

**Comment by Pivert** [comment]
Having the same issue with traefik in front handling the https. The pod is http only.

`wordpressScheme: https` in helm values

But :

```
$kubectl exec -i -t pivertwp-wordpress-b949cf5db-9h2l6 -- grep '^define.*URL' /bitnami/wordpress/wp-config.php
define( 'WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/' );
```

**Comment by carrodher** [comment]
Thank you for reaching out and for your interest in our project. We'd be happy to assist you, but to do so effectively, we'll need some more details. Could you please create a separate issue filling the Issue template?

Providing this information will help us better understand your situation and assist you in a more targeted manner.

**Comment by Pivert** [comment]
Tks. Please consider my case void:
- I was cascading 2 traefik during a migration.
- After the full switch (including turning off the original traefik to prevent being banned by letsencrypt), the problem fixed by itself.
- So I suspect the headers from the origin trafik (http) to override the headers from the internet exposed traefik (https).

Still, it does not explain why the above mentioned settings did not force the WP_SITEURL to the https scheme.

Thanks,

**Comment by mrdotb** [comment]
I got the same problem of mixed content. Problem is close to https://wordpress.stackexchange.com/questions/250240/setting-serverhttps-on-prevents-access-to-wp-admin adding this variable in the wp config solved it.
```yaml
wordpressExtraConfigContent: |                                                                                                                                                        
  $_SERVER["HTTPS"] = "on";   
```
