### ISSUE TITLE
[bitnami/mongodb] Request for Compatibility Matrix: Bitnami MongoDB Helm Charts vs. Kubernetes Versions

### ISSUE THREAD

**Issue by dsavercool** [bitnami/charts#18968]
### Name and Version

Bitnami/mongodb v10+

### What is the problem this feature will solve?

I have a requirement to deploy MongoDB 4.x on Kubernetes v1.27+. However, I observed that starting with the Bitnami MongoDB Helm Chart version 10+, support for MongoDB 4.x appears to be deprecated. This poses a challenge for setups and applications that are still dependent on MongoDB 4.0, especially when they aim to run on Kubernetes v1.27.

### What is the feature you are proposing to solve the problem?

I propose to reintroduce support or provide a clear pathway to deploy MongoDB 4.0 using the Bitnami MongoDB Helm Chart on Kubernetes v1.27+. While it's understandable that maintaining older versions of MongoDB can be challenging, it would be helpful for those setups that cannot immediately upgrade to newer MongoDB versions. If there are specific technical challenges or reasons behind the deprecation, providing documentation or guidelines for users who still need MongoDB 4.0 support would be very beneficial.

Alternatively, updating the prerequisites to include a clear compatibility matrix that outlines which chart versions are best suited for specific Kubernetes releases, rather than a broad "v1.19+" notation, would streamline user decisions and reduce potential deployment ambiguities.

### What alternatives have you considered?

Alternative Helm Chart Provider: Exploring other Helm chart providers for MongoDB. However, I highly value the reliability and comprehensive nature of Bitnami's charts and would prefer to continue using them.

Custom Helm Chart: Creating a custom Helm chart based on an older version of the Bitnami MongoDB Helm Chart. This would mean maintaining it ourselves and ensuring it remains compatible with newer Kubernetes versions, which is not ideal, but workable.

Migration to Newer MongoDB Version: While this is a longer-term goal, there are immediate needs and dependencies which require the use of MongoDB 4.0, making this alternative not feasible in the short term.

**Comment by javsalgar** [comment]
Hi,

The reason for not supporting branch 4.x is because the upstream project is not providing binaries for Debian 11. In the case of MongoDB we use the upstream binaries so if they don't provide Debian 11 we cannot package it. Starting from MongoDB 5.0 they added the `mongosh` script so probably using the latest version of the chart replacing the image with the latest 4.x that we released may not work. 

In this sense, you can stick to the latest version of the chart that we provided with MongoDB 4.x (did you check if it works with the latest Kubernetes version?)  and, when ready, upgrade to latest versions of MongoDB. Another option could be creating the fork you mentioned and changing the probes to not use `mongosh`

**Comment by dsavercool** [comment]
> Hi,
> 
> The reason for not supporting branch 4.x is because the upstream project is not providing binaries for Debian 11. In the case of MongoDB we use the upstream binaries so if they don't provide Debian 11 we cannot package it. Starting from MongoDB 5.0 they added the `mongosh` script so probably using the latest version of the chart replacing the image with the latest 4.x that we released may not work.
> 
> In this sense, you can stick to the latest version of the chart that we provided with MongoDB 4.x (did you check if it works with the latest Kubernetes version?) and, when ready, upgrade to latest versions of MongoDB. Another option could be creating the fork you mentioned and changing the probes to not use `mongosh`

Addressing the liveness and readiness probes in the latest chart supporting v4.x (bitnami/mongodb v11.2.0) brought the MongoDB statefulset to life.  Thank you for your detailed response and support.

For future readers that are stuck and need to use this workaround the files containing `mongosh` are:  
templates/NOTES.txt
templates/standalone/dep-sts.yaml
templates/hidden/statefulset.yaml
templates/replicaset/scripts-configmap.yaml
templates/replicaset/statefulset.yaml

**Comment by javsalgar** [comment]
Thank you for sharing it!
