### ISSUE TITLE
[bitnami/postgresql] Impossible to set full TLS validation

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/charts#18962]
### Name and Version

bitnami/postgresql:12.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

It is impossible to set up a full chain for TLS with client verification. Since there is no way to customize the admin user name (postgres in this case), you are bound to create a certificate with the Common Name `postgres` otherwise you will get the error: '[Provided user name and authenticated user name do not match](https://serverfault.com/questions/640172/postgresql-provided-user-name-and-authenticated-user-name-do-not-match)'

### What is the expected behavior?

Either I should be able to customize the name of the default admin user, or edit the name of the service, but optimally I should be able to do both...

### What do you see instead?

However, if you set up the certificate with CN postgres, then when the client tries to connect, you will get this error:
```
'sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres-postgresql" (10.96.58.128), port 5432 failed: server certificate for "postgres" does not match host name "postgres-postgresql"
```
as the CN of the certificate doesn't match the one of the service.

### Additional information

I wanted to bring this chart to production for an important client, but it isn't feasible if there is no way to set this securely. Hopefully, I am the one missing something in the configuration. Thank you

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami PostgreSQL container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
