### ISSUE TITLE
[bitnami/moodle] certificates.customCAs is not implemented properly

### ISSUE THREAD

**Issue by kyle-rf** [bitnami/charts#18984]
### Name and Version

bitnami/moodle 17.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

specify a secret for:

```yaml
certificates:
    customCAs:
    - my-ca
```
OR
```yaml
certificates:
    customCAs:
    - secret: my-ca
```

See additional information below

### What is the expected behavior?

initContainer for certificates should mount a volume for the customCAs secrets and update the trust store 

### What do you see instead?

```
{
    "msg": "Failure when executing Helm command. Exited 1.",
    "stderr_lines": [
        "Error: UPGRADE FAILED: cannot patch \"moodle\" with kind Deployment: Deployment.apps \"moodle\" is invalid: [spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: \"etc-ssl-certs\", spec.template.spec.initContainers[0].volumeMounts[1].name: Not found: \"etc-ssl-private\", spec.template.spec.initContainers[0].volumeMounts[2].name: Not found: \"custom-ca-certificates\"]"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

### Additional information

I believe the issue is here: [certificates initContainer](https://github.com/bitnami/charts/blob/main/bitnami/moodle/templates/deployment.yaml#L90-L137)

Values file customCAs description:
```yaml
## @param certificates.customCAs Defines a list of secrets to import into the container trust store
##
customCAs:
```

The initContainer is only attempted if customCAs is not empty and that is the only reference.  There is no logic for actually creating any volumes based on secret references in `certificates.customCAs`.

[volume creation](https://github.com/bitnami/charts/blob/main/bitnami/moodle/templates/deployment.yaml#L314-L324)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kyle-rf** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

I will take a shot at this.  I was able to workaround it using initContainers, extraVolumes, and extraVolumeMounts, which has given me some ideas for implementing this feature.
