### ISSUE TITLE
MongoDB Replicaset - bitnami/mongodb:4.4.15-debian-10-r7 - "error":"ShutdownInProgress:

### ISSUE THREAD

**Issue by zohebk8s** [bitnami/charts#18995]
### Name and Version

bitnami/mongodb:4.4.15-debian-10-r7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Environment: Azure AKS

MongoDB Replicaset pods are up/running. However, continuously I see the below error message from replicaset-0.
```
# kubectl logs mongodb-rs-0 -n namespace | grep -i error
Defaulted container "mongodb" out of: mongodb, metrics, istio-proxy, istio-init (init)
{"t":{"$date":"2023-09-04T06:36:02.215+00:00"},"s":"I",  "c":"CONNPOOL", "id":22572,   "ctx":"MirrorMaestro","msg":"Dropping all pooled connections","attr":{"hostAndPort":"mongodb-rs-1.mongodb-rs-headless.namespace.svc.cluster.local:27017","error":"ShutdownInProgress: Pool for mongodb-rs-1.mongodb-rs-headless.namespace.svc.cluster.local:27017 has expired."}}
```

**Comment by carrodher** [comment]
We do not see this error when deploying the Helm chart from scratch. Could you please add more information about how are you deploying it?
