### ISSUE TITLE
ACL not working in Kcraft mode with org.apache.kafka.metadata.authorizer.StandardAuthorizer

### ISSUE THREAD

**Issue by thejass10** [bitnami/charts#18997]
### Name and Version

bitnami/kafka:23.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Using Bitnami Kafka Helm 23.0, Kafka 3.5.0

I have set `KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer`
and `KAFKA_CFG_SUPER_USERS=User:user;User:controller_user;User:ANONYMOUS`

I have added one user "test_producer" to a topic "test-acl" with "Read" permission but still am able to write to the "test-acl" topic with the test_producer user and it's also working for any user.

Any fix for this? Not seeing any error in the broker logs

### What is the expected behavior?

authorization should work

**Comment by corico44** [comment]
Hello @thejass10,

Could you enable the `image.debug` parameter to `true` so we can see more info, please?
