### ISSUE TITLE
[bitnami/kube-prometheus] podMetadata.labels does not work for prometheus and alertmanager

### ISSUE THREAD

**Issue by BernhardGruen** [bitnami/charts#18999]
### Name and Version

bitnami/kube-prometheus 8.18.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Rendering not working if either `alertmanager.podMetadata.labels` or `prometheus.podMetadata.labels` is in use.

I assume this is due to the fact that `common.tplvalues.render` is used there (instead of `common.labels.matchLabels` which is used elsewhere).

The change was introduced in this commit: https://github.com/bitnami/charts/commit/2f7fbef0d681c26a3be4a94c857c23c114b0108a to close issue #18616

### Are you using any custom parameters or values?

```yaml
alertmanager:
  podMetadata:
      labels:
        label: test
```

### What do you see instead?

There is a render error:
`Error: YAML parse error on kube-prometheus/templates/prometheus/prometheus.yaml: error converting YAML to JSON: yaml: line 120: mapping values are not allowed in this context`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by BernhardGruen** [comment]
I am normally happy to open a PR but in this case I am not even sure @juan131 did that change on purpose (i.e. it is part of the feature) or if it was a unfortunate oversight of its feature PR in #18616 .

**Comment by juan131** [comment]
Thanks for reporting it @BernhardGruen ! I just created a PR to address it.
