### ISSUE TITLE
How to track Bitnami Helm Chart Versions

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#18998]
### Name and Version

How to track Bitnami Helm Chart Versions

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team,

How to track Bitnami Helm Chart Versions, If I need to download previous versions of helm charts how to do that?
Are there any release notes, what are the fixed bugs in each version?

Thanks

### Are you using any custom parameters or values?

No

### What do you see instead?

Helm versions list.

**Comment by carrodher** [comment]
You can see the changes by looking at the git history. For instance, using etcd as an example in the following URL you can see what changed since each version has an associated PR: https://github.com/bitnami/charts/commits/main/bitnami/etcd
