### ISSUE TITLE
[bitnami/mongodb-sharded] Sharded mongodb cluster with tls.enabled (x509)

### ISSUE THREAD

**Issue by Alansyf** [bitnami/charts#19008]
### Name and Version

bitnami/mongodb-sharded-6.6.2

### What is the problem this feature will solve?

Hi, 
I see tls.enabled in mongodb helm chart [here](https://github.com/bitnami/charts/blob/51dac1ef2e068e1f357fdfa0c8e7e4142dd2d4e7/bitnami/mongodb/values.yaml#L189)  .

But i didn't find how can I enable it in the sharding mongodb values.yaml.

Is this something not supported yet? 

### What is the feature you are proposing to solve the problem?

Support x509 client authentication

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the issue. I forwarded it to the engineering team. If you want to speed up the process, feel free to submit a PR with a similar `tls` section that the `bitnami/mongodb` chart has.
