### ISSUE TITLE
Airflow LDAP connection problem

### ISSUE THREAD

**Issue by yucangit** [bitnami/charts#19000]
### Name and Version

bitnami/airflow 
chart ver :15.0.2 (app ver : 2.7.0)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When LDAP connection enabled airflow webserver pod throwing"sed: can't read /opt/bitnami/airflow/webserver_config.py: No such file or directory" error.

But when i use same values.yaml file with Airflow chart:14.3.5, it works.

**installation command:**
`helm install airflow bitnami_repo/airflow -n ns-airflow-1m --version=15.0.2 -f D:\airflow\values.yaml`

**Error( at output of airflow-web pod logs):** 
`sed: can't read /opt/bitnami/airflow/webserver_config.py: No such file or directory`

### Are you using any custom parameters or values?

**values.yaml file:**

```
ldap:
  enabled: true
  uri: "ldap://my_url:389"
  basedn: eee
  binddn: ccc
  bindpw: ddd
  rolesMapping: 'aaa'
  searchAttribute: bbb
  userRegistration: 'True'
  userRegistrationRole: "Admin"
  rolesSyncAtLogin: 'True'  
``` 

### What is the expected behavior?

←[38;5;6mairflow ←[38;5;5m14:13:09.68 ←[0m
←[38;5;6mairflow ←[38;5;5m14:13:09.68 ←[0m←[1mWelcome to the Bitnami airflow container←[0m
←[38;5;6mairflow ←[38;5;5m14:13:09.68 ←[0mSubscribe to project updates by watching ←[1mhttps://github.com/bitnami/containers←[0m
←[38;5;6mairflow ←[38;5;5m14:13:09.68 ←[0mSubmit issues and feature requests at ←[1mhttps://github.com/bitnami/containers/issues←[0m
←[38;5;6mairflow ←[38;5;5m14:13:09.68 ←[0m
←[38;5;6mairflow ←[38;5;5m14:13:09.69 ←[0m←[38;5;2mINFO ←[0m ==> Enabling non-root system user with nss_wrapper
←[38;5;6mairflow ←[38;5;5m14:13:09.69 ←[0m←[38;5;2mINFO ←[0m ==> ** Starting Airflow setup **
←[38;5;6mairflow ←[38;5;5m14:13:09.70 ←[0m←[38;5;2mINFO ←[0m ==> Validating settings in POSTGRESQL_CLIENT_* env vars
←[38;5;6mairflow ←[38;5;5m14:13:09.71 ←[0m←[38;5;2mINFO ←[0m ==> Initializing Airflow ...
←[38;5;6mairflow ←[38;5;5m14:13:09.72 ←[0m←[38;5;2mINFO ←[0m ==> No injected configuration file found. Creating default config file
←[38;5;6mairflow ←[38;5;5m14:13:10.28 ←[0m←[38;5;2mINFO ←[0m ==> Configuring Airflow webserver authentication
←[38;5;6mairflow ←[38;5;5m14:13:10.29 ←[0m←[38;5;2mINFO ←[0m ==> Enabling LDAP authentication
←[38;5;6mairflow ←[38;5;5m14:13:10.33 ←[0m←[38;5;2mINFO ←[0m ==> Configuring Airflow database
←[38;5;6mairflow ←[38;5;5m14:13:10.35 ←[0m←[38;5;2mINFO ←[0m ==> Configuring Celery Executor
←[38;5;6mairflow ←[38;5;5m14:13:10.37 ←[0m←[38;5;2mINFO ←[0m ==> Trying to connect to the database server
←[38;5;6mairflow ←[38;5;5m14:14:28.64 ←[0m←[38;5;2mINFO ←[0m ==> Populating database
←[38;5;6mairflow ←[38;5;5m14:14:30.44 ←[0m←[38;5;2mINFO ←[0m ==> Creating Airflow admin user
←[38;5;6mairflow ←[38;5;5m14:14:32.33 ←[0m←[38;5;2mINFO ←[0m ==> ** Airflow setup finished! **

### What do you see instead?

←[38;5;6mairflow ←[38;5;5m13:02:42.51 ←[0m
←[38;5;6mairflow ←[38;5;5m13:02:42.51 ←[0m←[1mWelcome to the Bitnami airflow container←[0m
←[38;5;6mairflow ←[38;5;5m13:02:42.51 ←[0mSubscribe to project updates by watching ←[1mhttps://github.com/bitnami/containers←[0m
←[38;5;6mairflow ←[38;5;5m13:02:42.51 ←[0mSubmit issues and feature requests at ←[1mhttps://github.com/bitnami/containers/issues←[0m
←[38;5;6mairflow ←[38;5;5m13:02:42.51 ←[0m
←[38;5;6mairflow ←[38;5;5m13:02:42.52 ←[0m←[38;5;2mINFO ←[0m ==> Enabling non-root system user with nss_wrapper
←[38;5;6mairflow ←[38;5;5m13:02:42.52 ←[0m←[38;5;2mINFO ←[0m ==> ** Starting Airflow setup **
←[38;5;6mairflow ←[38;5;5m13:02:42.52 ←[0m←[38;5;2mINFO ←[0m ==> Validating settings in POSTGRESQL_CLIENT_* env vars
←[38;5;6mairflow ←[38;5;5m13:02:42.54 ←[0m←[38;5;2mINFO ←[0m ==> Initializing Airflow ...
←[38;5;6mairflow ←[38;5;5m13:02:42.54 ←[0m←[38;5;2mINFO ←[0m ==> No injected configuration file found. Creating default config file
←[38;5;6mairflow ←[38;5;5m13:02:42.91 ←[0m←[38;5;2mINFO ←[0m ==> Configuring Airflow webserver authentication
←[38;5;6mairflow ←[38;5;5m13:02:42.92 ←[0m←[38;5;2mINFO ←[0m ==> Enabling LDAP authentication
sed: can't read /opt/bitnami/airflow/webserver_config.py: No such file or directory

**Comment by ITJamie** [comment]
seeing this when using the container via docker-compose too
