### ISSUE TITLE
Keycloak chart issues

### ISSUE THREAD

**Issue by gothrek22** [bitnami/charts#19016]
### Name and Version

main

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/charts/blob/3e751575aeb43afbb8ea6cc49dcf6f7c36dd9d84/bitnami/keycloak/templates/_helpers.tpl#L212C9-L212C9

it's `db-port` for port, user, database keys.

### What do you see instead?

Errors.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! 
It seems something introduced at https://github.com/bitnami/charts/pull/16378

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
