### ISSUE TITLE
[bitnami/etcd] Root password is printed to logs in clear text

### ISSUE THREAD

**Issue by turkenh** [bitnami/charts#1901]
**Which chart**: 

etcd - 4.4.11

**Description**

Root password of ETCD is printed to pod logs.

**Steps to reproduce the issue:**

1. Deploy etcd helm chart with production values (didn't check if issue happens or not with default values.yaml)
2. Check logs of any etcd pod.

`2020-02-10 12:45:54.277976 W | pkg/flags: unrecognized environment variable ETCD_ROOT_PASSWORD=fFKT5yYerv`

**Describe the results you received:**

Root password is printed to logs in clear text

**Describe the results you expected:**

Password should never printed to logs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Just a quick note to let you know that I triggered a release of a container that will fix the issue. Thank you very much for reporting.

**Comment by javsalgar** [comment]
Hi,

The new container is available. I will now update the chart https://github.com/bitnami/bitnami-docker-etcd/commit/f17ff769b3355bf6fb560eaa18079578eadb6684

**Comment by javsalgar** [comment]
Done https://github.com/bitnami/charts/commit/c4f47a05568abdf5e8fcccbacbea50b76f0b01d2

**Comment by turkenh** [comment]
Thanks, however, I just tested again with chart version 4.4.13, log is still there:

```
$ helm ls
NAME        	NAMESPACE  	REVISION	UPDATED                             	STATUS  	CHART                        	APP VERSION
etcd-cluster	etcd-system	1       	2020-02-11 13:18:55.161282 +0300 +03	deployed	etcd-4.4.13                  	3.4.3

$ kubectl get pods etcd-cluster-0 -o yaml |grep 3.4.3-debian-10
    image: docker.io/bitnami/etcd:3.4.3-debian-10-r16
    image: docker.io/bitnami/etcd:3.4.3-debian-10-r16

$ kubectl logs etcd-cluster-0 |grep ROOT_PASS
2020-02-11 10:19:28.229385 W | pkg/flags: unrecognized environment variable ETCD_ROOT_PASSWORD=qwerty123
```

Am I missing something?

**Comment by javsalgar** [comment]
Hi,

Just forgot that we override the default command in the chart. I am currently updating the scripts configmap.

**Comment by javsalgar** [comment]
Here is the PR https://github.com/bitnami/charts/pull/1909
