### ISSUE TITLE
External-DNS arm64 build

### ISSUE THREAD

**Issue by dntosas** [bitnami/charts#19014]
### Name and Version

bitnami/external-dns:latest

### What is the problem this feature will solve?

Being able to deploy external-dns in arm64 clusters

### What is the feature you are proposing to solve the problem?

Build in arm64

**Comment by carrodher** [comment]
external-dns is multi-arch, see https://hub.docker.com/r/bitnami/external-dns/tags. There you can see two different images (linux/amd64 and linux/arm64), depending on the cluster you are deploying the container image (via Helm chart) the proper architecture will be used.

**Comment by dntosas** [comment]
Oh ye, i was on previous helm chart version :)

Thnx for your response!
