### ISSUE TITLE
binami/common breaks with helm 3.5.4

### ISSUE THREAD

**Issue by alexrashed** [bitnami/charts#19011]
### Name and Version

binami/common 2.10.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The following script creates a plain helm chart (with `helm create`) and _only_ adds `bitnami/common` as dependency.
Just the import of the dependency causes the rendering of the template to fail.
```bash
#!/bin/bash
# create a tmp folder
mkdir /tmp/test
cd /tmp/test

# download helm 3.5.4
wget https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
tar -xf helm-v3.5.4-linux-amd64.tar.gz
cd linux-amd64/

# create a new test chart
./helm create incompatible-common

# add the dependency
cat <<EOT >> ./incompatible-common/Chart.yaml
dependencies:
  - name: common
    version: ^2.10.0
    repository: https://charts.bitnami.com/bitnami
EOT

# update the dependencies
./helm repo add bitnami https://charts.bitnami.com/bitnami
./helm dependency update incompatible-common

# render the plain sample template (without even using bitnami/common)
./helm template incompatible-common
# -> this command fails with `Error: parse error at (incompatible-common/charts/common/templates/_labels.tpl:14): unclosed action`
```

### Are you using any custom parameters or values?

- No

### What is the expected behavior?

I would expect `bitnami/common` to be compatible with all helm versions stated in the README (i.e. the script above should terminate without an error).

### What do you see instead?

The default chart (created with `helm create`) with only the `common` chart added cannot be rendered. 
It fails with the following error:
```
Error: parse error at (incompatible-common/charts/common/templates/_labels.tpl:14): unclosed action

Use --debug flag to render out invalid YAML
```

### Additional information

It seems like this issue has been introduced with #18154.
It was even discussed in the PR in this comment: https://github.com/bitnami/charts/pull/18154#issuecomment-1691404353
However, neither the prerequisites of the chart in the README nor the template have been changed to fix the issue.

This doesn't seem to be the biggest issue, and it seems to be fixed with Helm 3.6.0+. But we basically use the same prerequisites for our helm chart where we use `bitnami/common` as a dependency. So we would either have to bump our supported versions or pin the `bitnami/common` (at least for now) to the last release.

**Comment by juan131** [comment]
Hi @alexrashed 

This bunch of PRs I'm creating:

- https://github.com/bitnami/charts/pulls?q=is%3Apr+author%3Ajuan131+%22Use+merge+helper%22+

Along with https://github.com/bitnami/charts/pull/18889 are attempting to address this issue.

**Comment by alexrashed** [comment]
Awesome, thanks!
But just to make sure we are not mixing up things: How are these PRs fixing the issue?
#18889 has already been merged and released (should already have been contained in my tests), and the other PRs don't touch the common chart. Is there going to be a final PR doing some kind of switch?

**Comment by juan131** [comment]
Hi @alexrashed 

Sorry, you're right! I read this issue too fast, sorry for that. The PRs we've been creating fix a different issue that prevented users from using string templates on values such as `podValues` or `podAnnotations`.

However, the issue you're mentioning is still present and it's due to [this limitation](https://github.com/golang/go/issues/29770) that was fixed in `go1.16`.

**Comment by juan131** [comment]
Could you please give a try to the solution I implemented on the draft PR mentioned above and let us know if this address the issue?

**Comment by alexrashed** [comment]
Thanks for jumping on this! I can verify that your fix resolves my issue! 💯 
- I cloned out the `bitnami/charts` repo
- Used the result of `helm package bitnami/common` (from the `main` branch) in my sample, where the template cannot be rendered.
- Switched to your PR branch, created a new package, and used it in my sample, which renders correctly.

**Comment by juan131** [comment]
Thank you for double-checking!! Promoting my draft PR to review.

**Comment by mbelang** [comment]
It seams that even if this is fixed, there are still charts that depends on common that were not updated to latest. For instance, I'm installing redis v18.0.4 which still use 2.9.2

```
cat redis/charts/common/Chart.yaml 
annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.9.2
```

I see that redis has 2.x.x as a version but since I'm downloading redis chart from an other chart, I do not get latest common.

**Comment by carrodher** [comment]
Actually the latest version of Redis (18.0.4) is bundling the bitnami/common subchart version 2.10.0:
```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/redis --version 18.0.4 --untar
Pulled: registry-1.docker.io/bitnamicharts/redis:18.0.4
Digest: sha256:c22b928cf1a869df78a185a01ad30bb8339c1cd5fbcba3ef9aa94d304a2f7ac7
$ cat redis/Chart.lock
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.10.0
digest: sha256:023ded170632d04528f30332370f34fc8fb96efb2886a01d934cb3bd6e6d2e09
generated: "2023-09-05T11:35:55.621686+02:00"
```

**Comment by juan131** [comment]
It should be just a matter of time (few days) for charts to adopt the new common library with new automated releases
