### ISSUE TITLE
How to change permissions of mounted Secrets [Airflow]

### ISSUE THREAD

**Issue by otosky** [bitnami/charts#1904]
**Which chart**:

Airflow

**Description**

I'm a really green with K8s, and need a little assistance in navigating how to alter permissions on a Volume that's been mounted from a Secret.  For context, I'm trying edit permissions on several .pem SSL certificates such that group access is removed, allowing me to connect Airflow to CloudSQL via a Private IP and having SSL-enabled.

Trying to get around this:
```psycopg2.OperationalError: "[path/to/key]" private key file has group or world access; permissions should be u=rw (0600) or less```

I've been able to set a `defaultMode` for the Volume that does allow different permission settings, but doesn't result in the correct `chmod` octal value.  Can't seem to get rid of the group access.

**Steps to reproduce the issue:**

1. `kubectl create secret generic cloudsql-certs --from-file='path/to/file1' --from-file='path/to/file2'` 
2. Add to _statefulset-worker.yaml_ volumes:
```
- name: cloudsql
   secret:
     secretName: cloudsql-certs
     defaultMode: 256
```
3. Add to _statefulset-worker.yaml_ volumeMounts for container [airflow-worker]:
```
- name: cloudsql
   mountPath: /cloudsql/
```
4.  Set up connection details in Airflow UI for CloudSQL

**Describe the results you received:**

```psycopg2.OperationalError: "[path/to/key]" private key file has group or world access; permissions should be u=rw (0600) or less```

cd-ing into the directory and running `stat -L [cert-file-path]` shows access privileges of 0440 rather than 0400.  Similar situation when defaultMode is set to 384, access privileges show 0640 rather than 0600.

**Describe the results you expected:**

Expected octal privilege values to correspond to decimal input (256 --> 0400, 384 --> 0600).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.23", GitCommit:"93457f9dac45d5f95c2c609232e1ff2343c72684", GitTreeState:"clean", BuildDate:"2020-01-14T06:01:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @otosky ,
That's weird, decimal `256` is `0400` in octal it should not be mounted with `0440`, Can you confirm there is nothing overriding that?

**Comment by otosky** [comment]
The only thing I can think of is that I'm installing the chart from the value.yaml file, where the securityContext is enabled:
```
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
```

**Comment by miguelaeh** [comment]
Hi @otosky ,
The `fsGroup` will modify the group owner of the volume to `1001` but not the permissions of it. Could you share the values you are using to install the Chart so? we can try to reproduce the issue?

**Comment by otosky** [comment]
Closing the issue - got around the problem by adding an initContainer that copies the files to a new volume and alters the permissions.

**Comment by ukd1** [comment]
> Hi @otosky ,
> The `fsGroup` will modify the group owner of the volume to `1001` but not the permissions of it. Could you share the values you are using to install the Chart so? we can try to reproduce the issue?

I'm having this same issue, which goes away when removing the `securityContext`. It's not ideal, and I've no idea why it happens. It's still a thing though.

**Comment by tnimni** [comment]
> Closing the issue - got around the problem by adding an initContainer that copies the files to a new volume and alters the permissions.

hi, can you share the solution please?
