### ISSUE TITLE
Airflow deployment issue on IBM CLoud IKS

### ISSUE THREAD

**Issue by rgarg2006** [bitnami/charts#1912]
Hi, 

1.  I am facing issue deploying Airflow on IKS IBM Cloud. https://cloud.ibm.com/catalog/content/airflow

I see below error:

Error: Error applying plan: 2020/02/11 12:12:46 Terraform apply | 2020/02/11 12:12:46 Terraform apply | 1 error occurred: 2020/02/11 12:12:46 Terraform apply | * helm_release.airflow0: 1 error occurred: 2020/02/11 12:12:46 Terraform apply | * helm_release.airflow0: rpc error: code = Unknown desc = render error in "airflow/templates/secrets.yaml": template: airflow/templates/secrets.yaml:25:24: executing "airflow/templates/secrets.yaml" at <required "An Airflow Fernet Key is required!" .Values.airflow.auth.fernetKey>: error calling required: An Airflow Fernet Key is required! 2020/02/11 12:12:46 Terraform apply |

How can I generate and push Fernet key to airflow/k8 cluster on IBM Cloud Kubernetes service. 

2. How can I deploy Airflow in HA mode with cluster in 3 AZs ? 

Thanks,
Rajesh Garg

**Comment by beltran-rubo** [comment]
Hi @rgarg2006, could you tell us if you solved the issue or still exists? We are happy to help to figure out the exact problem.

**Comment by rgarg2006** [comment]
Hi,
  I am still getting issue with Airflow deployment as below:

1. template:
airflow/charts/redis/templates/redis-slave-statefulset.yaml:87:18:
executing "airflow/charts/redis/templates/redis-slave-statefulset.yaml" at
<eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible
types for comparison

2.Getting connection issue further. 172.30.118.71:8080: connect: connection
refused.

3. Also getting pvc error

Can you please suggest, how can I address same.

Also, please help me with Airflow deployment steps in IBM Cloud Multi-AZ
cluster deployment. Thanks.
Regards,
Rajesh Garg

**Comment by javsalgar** [comment]
Hi,

> <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible
types for comparison

Could you let us know the helm version? I recall seeing this issue in the past and it had to do with the helm client.

**Comment by rgarg2006** [comment]
Hi,
  I was able to deploy Airflow on IBM Kubernetes Service (IKS) cluster but
am not able to login to Airflow UI with user/bitnami credentials.
Even I tried setting username and password in parameters and applying plan
but that does not seem working.

Can you please suggest default Airflow username & password, and way to
setup/reset UI username and password on IKS setup. Thanks.
Regards,
Rajesh

**Comment by javsalgar** [comment]
Hi,

I would check two things:

   - The secret that the release creates. There you should be able to extract the password value (if I recall correctly you will see the instructions on the NOTES.txt section)
   - Does the same issue happen when deploying a fresh airflow? If it is a persisted installation then the password change will not occur.
