### ISSUE TITLE
[bitnami/etcd] Cluster does not start from etcd 

### ISSUE THREAD

**Issue by arrow2012** [bitnami/charts#19130]
### Name and Version

bitnami/etcd 3.5.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
etcd 09:46:09.91 WARN  ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
etcd 09:46:19.93 DEBUG ==> There are no enough active endpoints!
etcd 09:46:19.93 WARN  ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
etcd 09:46:39.97 DEBUG ==> There are no enough active endpoints!
etcd 09:46:39.98 WARN  ==> Cluster not healthy, not adding self to cluster for now, keeping trying...
```
### Are you using any custom parameters or values?
```
helm-sh-test upgrade --install apisix apisix/apisix --create-namespace  --namespace apisix  \
--set dashboard.enabled=true  \
--set gateway.type=NodePort  \
--set ingress-controller.enabled=true  \
--set ingress-controller.config.apisix.serviceNamespace=apisix \
--set etcd.persistence.storageClass="alicloud-nas-test-lanternai" \
--set etcd.persistence.size="20Gi" \
--set etcd.image.debug=true
```

### What do you see instead?

<img width="1152" alt="image" src="https://github.com/bitnami/charts/assets/46478986/85fd1db7-ece4-41a5-ac88-6cad7de4edf4">

**Comment by arrow2012** [comment]
k8s version  1.24.6

**Comment by arrow2012** [comment]
arrow@arrow apisix % kubectl -n apisix describe pod apisix-etcd-1                        
Name:         apisix-etcd-1
Namespace:    apisix
Priority:     0
Node:         cn-shanghai.172.16.18.150/172.16.18.150
Start Time:   Wed, 06 Sep 2023 17:45:55 +0800
Labels:       app.kubernetes.io/instance=apisix
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=etcd
              controller-revision-hash=apisix-etcd-85cf5d4445
              helm.sh/chart=etcd-8.7.7
              statefulset.kubernetes.io/pod-name=apisix-etcd-1
Annotations:  checksum/token-secret: 62191f13ed46d9970edd06de35271d2dfb1fdd158f1cd2e7b183634274b2450a
              kubernetes.io/psp: ack.privileged
Status:       Running
IP:           10.89.1.60
IPs:
  IP:           10.89.1.60
Controlled By:  StatefulSet/apisix-etcd
Containers:
  etcd:
    Container ID:   containerd://a3f9baae503f15780699cd4de25cc6112d2605697bb1f312f54aada750cae298
    Image:          docker.io/bitnami/etcd:3.5.7-debian-11-r14
    Image ID:       docker.io/bitnami/etcd@sha256:0825cafa1c5f0c97d86009f3af8c0f5a9d4279fcfdeb0a2a09b84a1eb7893a13
    Ports:          2379/TCP, 2380/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 06 Sep 2023 17:45:57 +0800
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/opt/bitnami/scripts/etcd/healthcheck.sh] delay=60s timeout=5s period=30s #success=1 #failure=5
    Readiness:      exec [/opt/bitnami/scripts/etcd/healthcheck.sh] delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:
      BITNAMI_DEBUG:                     true
      MY_POD_IP:                          (v1:status.podIP)
      MY_POD_NAME:                       apisix-etcd-1 (v1:metadata.name)
      MY_STS_NAME:                       apisix-etcd
      ETCDCTL_API:                       3
      ETCD_ON_K8S:                       yes
      ETCD_START_FROM_SNAPSHOT:          no
      ETCD_DISASTER_RECOVERY:            no
      ETCD_NAME:                         $(MY_POD_NAME)
      ETCD_DATA_DIR:                     /bitnami/etcd/data
      ETCD_LOG_LEVEL:                    debug
      ALLOW_NONE_AUTHENTICATION:         yes
      ETCD_AUTH_TOKEN:                   jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m
      ETCD_ADVERTISE_CLIENT_URLS:        http://$(MY_POD_NAME).apisix-etcd-headless.apisix.svc.cluster.local:2379,http://apisix-etcd.apisix.svc.cluster.local:2379
      ETCD_LISTEN_CLIENT_URLS:           http://0.0.0.0:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS:  http://$(MY_POD_NAME).apisix-etcd-headless.apisix.svc.cluster.local:2380
      ETCD_LISTEN_PEER_URLS:             http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN:        etcd-cluster-k8s
      ETCD_INITIAL_CLUSTER_STATE:        existing
      ETCD_INITIAL_CLUSTER:              apisix-etcd-0=http://apisix-etcd-0.apisix-etcd-headless.apisix.svc.cluster.local:2380,apisix-etcd-1=http://apisix-etcd-1.apisix-etcd-headless.apisix.svc.cluster.local:2380,apisix-etcd-2=http://apisix-etcd-2.apisix-etcd-headless.apisix.svc.cluster.local:2380
      ETCD_CLUSTER_DOMAIN:               apisix-etcd-headless.apisix.svc.cluster.local
    Mounts:
      /bitnami/etcd from data (rw)
      /opt/bitnami/etcd/certs/token/ from etcd-jwt-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-n5nkw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-apisix-etcd-1
    ReadOnly:   false
  etcd-jwt-token:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  apisix-etcd-jwt-token
    Optional:    false
  kube-api-access-n5nkw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  2m48s               default-scheduler  Successfully assigned apisix/apisix-etcd-1 to cn-shanghai.172.16.18.150
  Normal   Pulled     2m47s               kubelet            Container image "docker.io/bitnami/etcd:3.5.7-debian-11-r14" already present on machine
  Normal   Created    2m47s               kubelet            Created container etcd
  Normal   Started    2m47s               kubelet            Started container etcd
  Warning  Unhealthy  12s (x4 over 102s)  kubelet            Liveness probe failed: command "/opt/bitnami/scripts/etcd/healthcheck.sh" timed out
  Warning  Unhealthy  2s (x12 over 102s)  kubelet            Readiness probe failed: command "/opt/bitnami/scripts/etcd/healthcheck.sh" timed out

**Comment by arrow2012** [comment]
use aliyun cloud nas for   SC ,and pv was created  and mounted success, writeable

**Comment by arrow2012** [comment]
Type     Reason             Age                    From               Message
  ----     ------             ----                   ----               -------
  Warning  FailedScheduling   5m5s                   default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims. , preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.,
  Normal   Scheduled          5m4s                   default-scheduler  Successfully assigned apisix/apisix-etcd-0 to cn-shanghai.172.16.18.150
  Normal   Pulled             5m1s                   kubelet            Container image "docker.io/bitnami/etcd:3.5.7-debian-11-r14" already present on machine
  Normal   Created            5m1s                   kubelet            Created container etcd
  Normal   Started            5m1s                   kubelet            Started container etcd
  Warning  Unhealthy          116s (x5 over 3m56s)   kubelet            Liveness probe failed: command "/opt/bitnami/scripts/etcd/healthcheck.sh" timed out
  Warning  Unhealthy          116s (x15 over 3m56s)  kubelet            Readiness probe failed: command "/opt/bitnami/scripts/etcd/healthcheck.sh" timed out
  Normal   Killing            116s                   kubelet            Container etcd failed liveness probe, will be restarted
  Warning  FailedPreStopHook  116s                   kubelet            Exec lifecycle hook ([/opt/bitnami/scripts/etcd/prestop.sh]) for Container "etcd" in Pod "apisix-etcd-0_apisix(71b7ed98-84be-4996-9a83-d23f6f2581df)" failed - error: command '/opt/bitnami/scripts/etcd/prestop.sh' exited with 128: Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
, message: "Error: bad member ID arg (strconv.ParseUint: parsing \"\": invalid syntax), expecting ID in Hex\n"

**Comment by joancafom** [comment]
Hi @arrow2012 

I see that the helm chart you are using it not the {{bitnami/apisix}} one, maybe you can check that out! Regarding {{etcd}}, are you able to reproduce this issue if you deploy this chart alone (and not as a subchart)? It would also be nice if you could share the output of the following command:

```console
$ k exec -it etcd-0 -- bash /opt/bitnami/scripts/etcd/healthcheck.sh
etcd-0.etcd-headless.default.svc.cluster.local:2379 is healthy: successfully committed proposal: took = 638.833µs
```
