### ISSUE TITLE
[bitnami/external-dns] Add azure workload identity support

### ISSUE THREAD

**Issue by nbjohnson** [bitnami/charts#19141]
### Name and Version

bitnami/external-dns

### What is the problem this feature will solve?

In external-dns v0.13.6 azure workload identity support was added and the chart needs to be updated to add support

### What is the feature you are proposing to solve the problem?

To add support for workload identity, the implementation is similar to the existing `useManagedIdentityExtension` option as the ability to set `useWorkloadIdentityExtension` in the json config file needs to be available which can be seen here: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md#helm

Full instructions: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md#managed-identity-using-workload-identity

### What alternatives have you considered?

Manually patching the helm chart can work but is clunky and since the current implementation of pod/managed identity is being removed at the end of September, adding native support for this new authentication configuration is important.

**Comment by michelefa1988** [comment]
Following :)

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the engineering team. If you want to speed up the process, would you like to submit a PR adding the value?

**Comment by michelefa1988** [comment]
I have created PR https://github.com/bitnami/charts/pull/19216 for this ticket. I have tested and was able to successfully run workload identity

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
