### ISSUE TITLE
[bitnami/redis-cluster] Disable snapshotting per ENV variable

### ISSUE THREAD

**Issue by ritmas** [bitnami/charts#19140]
### Name and Version

bitnami/redis-cluster 9.0.0

### What is the problem this feature will solve?

In order to run the Redis cluster for cache purposes there is no need to have snapshotting enabled. Thus, the configuration needs adjustment:
```bash
save ""
```

Now, it doesn't work with `redis.configmap` as this is additional configuration and [appending it at the end of config file](https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/configmap.yaml#L2300-L2302) doesn't rewrite previous values:
```console
$ helm template bitnami/redis-cluster --version 9.0.0 --set redis.configmap='save ""' | egrep '^\ +save.*'
    save 900 1
    save 300 10
    save 60 10000
    save ""
```

### What is the feature you are proposing to solve the problem?

One of the options to achieve this would be implementing a similar solution as for `redis.useAOFPersistence` / `REDIS_AOF_ENABLED`. A dedicated configuration value or ENV variable would solve this.

### What alternatives have you considered?

It's possible to pass the whole Redis configuration via `redis.defaultConfigOverride`, but it doesn't feel right.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by ritmas** [comment]
@carrodher Created PR with a fix.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
