### ISSUE TITLE
[bitnami/mongodb] Backup volume in AWS

### ISSUE THREAD

**Issue by chary1112004** [bitnami/charts#19155]
### Name and Version

bitnami/mongodb 12.1.31

### What is the problem this feature will solve?

Hi,

We are trying to do backup volume EBS in AWS. The way to backup EBS by define custom tags in EBS (For example: key: value). 
However I do not see there is option in default value file that allow to do it.

### What is the feature you are proposing to solve the problem?

Any information would be very much appreciated.

Thank you!

**Comment by javsalgar** [comment]
Hi,

If I understood correctly, what you want to achieve is to add custom labels to the PVCs created in the chart?

**Comment by chary1112004** [comment]
Hi @javsalgar ,

We would like to add annotation to PVC and when PVC is updated/created then it will use annotation to add tags inside EBS.

Currently I only see the option update annotation inside storage class (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md#storageclass-tagging) then these tags are updated inside EBS.

Thanks!

**Comment by joancafom** [comment]
Hi @chary1112004 

>We would like to add annotation to PVC and when PVC is updated/created then it will use annotation to add tags inside EBS.

You can customize the annotations added to the PVCs by using the `persistence.annotations` parameter:

https://github.com/bitnami/charts/tree/main/bitnami/mongodb#persistence-parameters

Would that be enough for it to work?

**Comment by chary1112004** [comment]
Hi @joancafom,

thank you for your information. Actually this feature should belong to kubernetes to allow add tags in pvc then tags will be added inside ebs such as https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1014.

Then I would like to close this ticket. Thanks!
