### ISSUE TITLE
[bitnami/kubernetes-event-exporter] General query about this chart

### ISSUE THREAD

**Issue by jmos5156** [bitnami/charts#19171]
### Name and Version

bitnami/kubernetes-event-exporter 2.7.0

### What is the problem this feature will solve?

Sorry if this is the wrong place to ask but I have a general query about the chart itself.

The image it uses https://github.com/bitnami/charts/blob/main/bitnami/kubernetes-event-exporter/Chart.yaml based on the chart is one created by bitnami

The dockerfile https://github.com/bitnami/containers/blob/main/bitnami/kubernetes-event-exporter/1/debian-11/Dockerfile shows a bitnami download brings in a Kubernetes event exporter binary.

I wanted to confirm that this binary is based on this repository https://github.com/resmoio/kubernetes-event-exporter or a fork of it

### What is the feature you are proposing to solve the problem?

See above

### What alternatives have you considered?

See above

**Comment by javsalgar** [comment]
Hi!

I confirm that we're using this repo https://github.com/resmoio/kubernetes-event-exporter to download and compile the binaries that we provide afterwards in our containers.
