### ISSUE TITLE
[bitnami/kube-prometheus] Operator Deployment uses labels instead of podLabels as pod labels

### ISSUE THREAD

**Issue by BernhardGruen** [bitnami/charts#19199]
### Name and Version

bitnami/kube-prometheus 8.18.3
up to
bitnami/kube-prometheus 8.21.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Configuration
```yaml
operator:
  podLabels:
    label1: value1
```

### What is the expected behavior?

I expect that the operator pod gets the label `label1: value1`.

### What do you see instead?

The pod gets the labels of the deployment instead.

### Additional information

The error is in that line:
https://github.com/bitnami/charts/blob/ff8121ee686f7547142342f2b394fc97640080a8/bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml#L22

There should be a call to `kube-prometheus.operator.podLabels` instead of `kube-prometheus.operator.labels` at that point. That define was added to `_helpers.tpl` in #18616 but unfortunately the newly created named template was not used in `prometheus-operator/deployment.yaml`.

Versions before 8.18.0 were not affected by this issue because the inner function of the name template `kube-prometheus.operator.labels` was different at that point.

**Comment by BernhardGruen** [comment]
v8.18.3 is still affected by this issue. I just updated the issue accordingly.

**Comment by BernhardGruen** [comment]
@javsalgar hope this helps

**Comment by migruiz4** [comment]
Hi @BernhardGruen,

I'm sorry for the late response.

I have submitted the PR #19425 to solve this issue.

**Comment by BernhardGruen** [comment]
I just updated the original issue to reflect the affected versions. The current PR #19425 seems to just need a version bump to be ready for merge. :+1:
