### ISSUE TITLE
[bitnami/oauth2-proxy] oauth2-proxy deployment fail because oauth2-proxy can not access to redis

### ISSUE THREAD

**Issue by NicolasAuden** [bitnami/charts#19193]
### Name and Version

bitnami/oauth2-proxy 3.7.8

### What architecture are you using?

None

### What steps will reproduce the bug?

1. image: docker.io/bitnami/oauth2-proxy:7.4.0-debian-11-r272

### Are you using any custom parameters or values?
```
  --config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg
            --provider=oidc
            --set-xauthrequest=true
            --set-authorization-header=true
```
### What is the expected behavior?

oauth2-proxy should be able to access Redis

### What do you see instead?

**In aouth2-proxy pods** :
_invalid configuration:
```
2023-09-08T08:00:24.   unable to set a redis initialization key: dial tcp 10xxxxxxxxxx: connect: operation not permitted
2023-09-08T08:00:24.   unable to delete the redis initialization key: dial tcp 10xxxxxxxxxx: connect: operation not permitted_
```
**In redis pod** :
```
Warning | FailedCreate (18) | 5 mins ago | create Pod oauth2-proxy-redis-master-0 in StatefulSet oauth2-proxy-redis-master failed error: pods "oauth2-proxy-redis-master-0" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/redis]: Forbidden: seccomp may not be set]
-- | -- | -- | --
Normal | SuccessfulCreate | 16 mins ago | create Claim redis-data-oauth2-proxy-redis-master-0 Pod oauth2-proxy-redis-master-0 in StatefulSet oauth2-proxy-redis-master success
```

### Additional information

When I try to implement this release 3.7.8 and above of aouth2-proxy I get this error. Authentification is impossible.
The older releases work fine.
A difference I noticed since this release is the redis docker image version who changed from 7.0 to 7.2

**Comment by dgomezleon** [comment]
Hi @NicolasAuden ,

After a while (ouath2-proxy is restarted several times), I always reproduce the same message:

```
ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: invalid provider verifier options: missing required setting: issuer-url
```

Could you please verify you see the same behaviour

**Comment by dgomezleon** [comment]
Hi @NicolasAuden ,

Sorry for the delay. I was not able to reproduce the error. However, I think it is related to[ this PR](17237). Could you please take a look and confirm?

**Comment by NicolasAuden** [comment]
Hi @dgomezleon ,
My turn to apologize.

I tried to add the argument you have suggested, but got an error of unrecognized param.
Where am I supposed to add it ?

Here is the config of my oauth2 :

`global:
  storageClass: powerstore-nfs
ingress:
  enabled: true
  hostname: #hostname#
  path: /oauth2/
  ingressClassName: ingress-test
configuration:
  existingSecret: oauth2-proxy-test
extraArgs:
- --provider=oidc
- --set-xauthrequest=true
- --provider-display-name=coptest Login
- --login-url=https://#URLCOMPAGNY#/auth
- --redeem-url=https://#URLCOMPAGNY#/token
- --validate-url=https://#URLCOMPAGNY#/userinfo
- --set-authorization-header=true
- --skip-provider-button=true
- --reverse-proxy=true
- --redirect-url=https://#hostname#/oauth2/callback
- --skip-jwt-bearer-tokens=true
- --oidc-issuer-url=https://#URLCOMPAGNY#
- --scope=openid
- --code-challenge-method=S256
- --oidc-email-claim=sub
- --cookie-domain=.coptest.com
- --whitelist-domain=.coptest.com
- '--cookie-csrf-per-request=true'
- '--cookie-csrf-expire=60m'
- '--cookie-expire=60m'
- '--cookie-refresh=0'
replicaCount: 2
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: oauth2-proxy-test
        namespaces:
          - oauth2-proxy
        topologyKey: "topology.kubernetes.io/zone"
resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 25Mi`

**Comment by dgomezleon** [comment]
Hi @NicolasAuden 

In order to test that, you could install the chart with the option: 
```
--set redis.master.containerSecurityContext.seccompProfile.type="Unconfined"
```

or add it in a `values.yaml` file:

```
redis:
  master:
    containerSecurityContext:
      seccompProfile:
        type:  Unconfined
```

Also, I would suggest taking a look a [the previously mentioned PR](https://github.com/bitnami/charts/pull/17237/files) in order to detect the change that is producing the error.

**Comment by NicolasAuden** [comment]
Thanks, I tested it but got the same error :

_invalid configuration:
unable to set a redis initialization key: dial tcp 10.xx.xx.xxx: connect: operation not permitted
unable to delete the redis initialization key: dial tcp 10.xx.xx.xxx: connect: operation not permitted_

**Comment by NicolasAuden** [comment]
Thanks, I tested to add this option and indeed I got the same error

_invalid configuration:
unable to set a redis initialization key: dial tcp 10.xx.xxx.xxx:6379: connect: operation not permitted unable to delete the redis initialization key: dial tcp 10.xx.xxx.xxx:6379: connect: operation not permitted_

**Comment by dgomezleon** [comment]
Hi @NicolasAuden ,

Thanks a lot for all your feedback. I still suspect that your error is related to [this PR](https://github.com/bitnami/charts/pull/17237). Could you please try the following?

1. Clone charts repo.

```
$ git clone git@github.com:bitnami/charts.git
$ cd charts/bitnami/oauth2-proxy
```

2. Try the version before the changes
* Edit your `Chart.yaml` file to use Redis 17.13.2:

```
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.13.2
```

* Update deps:

```
$ helm dep update
```

You should see the following in your `charts` folder:

```
$ ls charts
common-2.13.0.tgz	redis-17.13.2.tgz
```

* Install the chart:

```
helm install redis . -f YOUR-VALUES.yaml
```

This should work for you.

3. Now, let's try the version after those changes.

* Edit your `Chart.yaml` file to use Redis 17.14.0:

```
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.14.0
```

* Execute:

```
$ helm dep update
```

You should see the following in your `charts` folder:

```
$ ls charts
common-2.13.0.tgz	redis-17.14.0.tgz
```

* Install the chart:
```
helm install redis . -f YOUR-VALUES.yaml
```

This should fail. In that case, we will make sure that your issue is related to this specific change.

**Comment by NicolasAuden** [comment]
Hi @dgomezleon ,

Thanks a gain for your help. The Redis version 17.13.2 works, while the version 17.14.0 fails.
Which seems to be related to the PR ou mentioned indeed.

Is there any workaround?

**Comment by dgomezleon** [comment]
I would suggest trying these configurations:

* Option 1: 
```
redis:
  master:
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 0
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: []
```

* Option 2 (very risky, but just to check if this may be related to a privilege issue in your cluster)
```
redis:
  master:
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 0
      runAsNonRoot: true
      allowPrivilegeEscalation: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
```

**Comment by NicolasAuden** [comment]
Hi @dgomezleon ,

I just tried both options.

Option 1 : Got this error : 
_create Pod oauth2-proxy-redis-master-0 in StatefulSet oauth2-proxy-redis-master failed error: pods "oauth2-proxy-redis-master-0" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/redis]: Forbidden: seccomp may not be set]_

Option 2 : Got this error : 
_create Pod oauth2-proxy-redis-master-0 in StatefulSet oauth2-proxy-redis-master failed error: pods "oauth2-proxy-redis-master-0" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/redis]: Forbidden: seccomp may not be set spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed]_

**Comment by dgomezleon** [comment]
Hi @NicolasAuden ,

I think it may be related to `seccomp profile` in your cluster. Could you try this?

```
redis:
  master:
    containerSecurityContext:      
      seccompProfile: {}
```

**Comment by NicolasAuden** [comment]
Hi @dgomezleon ,

Indeed the problem seems to come from the _secomp profile_ param.
I tried this way too _seccompProfile: {}_ but it doesn't work either.

The only way to make the version 3.7.8 of the application to work, seems to be to remove this parameter from the yaml once the image has been deployed.
Which is not viable in the long term, as each time you deploy a new image, the parameter comes back.

**Comment by dgomezleon** [comment]
Hi @NicolasAuden ,

Thanks for sharing it. It is likely related to how Helm is managing default values. We have just created an internal task to work on it. We will keep you updated.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by NicolasAuden** [comment]
> Hi @NicolasAuden ,
> 
> Thanks for sharing it. It is likely related to how Helm is managing default values. We have just created an internal task to work on it. We will keep you updated.

Hi @dgomezleon ,
Thanks for this update. Look forward to hearing from you.

**Comment by juan131** [comment]
Hi @dgomezleon @NicolasAuden 

Please correct me if I'm wrong but this is sth that can be solved by setting the `containerSecurityContext.seccompProfile.type` chart parameter to `null`:

```console
$ helm template oauth2-proxy oci://registry-1.docker.io/bitnamicharts/oauth2-proxy \
  --set containerSecurityContext.seccompProfile.type=null \
  -s templates/deployment.yaml
(...)
# Source: oauth2-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  (...)
spec:
  (...)
  template:
    (...)
    spec:
      (...)
      containers:
        - name: oauth2-proxy
          (...)
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile: {}
            (...)
```

As you can see above, the `deploy.spec.template.spec.containers.securityContext.seccompProfile` can be unset using this.
