### ISSUE TITLE
[bitnami/external-dns] Update clusterRole template to allow Traefik resouces.

### ISSUE THREAD

**Issue by assices** [bitnami/charts#19205]
### Name and Version

bitnami/external-dns 6.24.3

### What is the problem this feature will solve?

RBAC support for Traefik CRD resources.
Starting from 0.13.6 version, ExternalDNS supports natively [Traefik Proxy](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/traefik-proxy.md).

clusterRole created from bitnami/external-dns chart doesn't allow Traefik CRD resources.

The only workaround I found is to disable rbac and create `clusterRole` and `clusterRoleBinding` manually,

### What is the feature you are proposing to solve the problem?

Update clusterRole Template to with Traefik `apiGroup` & `resources`.

**Comment by trunet** [comment]
6 hours before you opened this, and I found now after raising my issue #19211 and a PR I submitted https://github.com/bitnami/charts/pull/19212

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
