### ISSUE TITLE
watch-namespace-selector

### ISSUE THREAD

**Issue by marinkobabic** [bitnami/charts#19204]
### Name and Version

bitnamicharts/nginx-ingress-controller

### What is the problem this feature will solve?

Please support setting watch-namespace-selector

https://github.com/joomcode/ingress-nginx/commit/d1e088e4c0955c27165b2e0d56457be621f6909e

### What is the feature you are proposing to solve the problem?

Possibility to watch multiple namespaces when scoped mode is used

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
