### ISSUE TITLE
[bitnami/solr] Expectation is to create zookeeper client to fetch collection and solr index url

### ISSUE THREAD

**Issue by shubhranshu007** [bitnami/charts#19200]
### Name and Version

bitnami/solr:9.2.1-debian-11-r7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are using pysolr libarary to create client and get SorlHost using zookeeper client.

But in kubernetes hosted solr service we are not able to get hosts 
 
with connection string shown in UI - we are getting  name resolution error.

solr image:  9.2.1-debian-11-r7
zookeeper image: 3.8.1-debian-11-r36
version: 8.1.4

### What do you see instead?

<img width="905" alt="image" src="https://github.com/bitnami/charts/assets/44315013/14e1dea1-a9a4-4599-a4d2-218fccd0a067">

**Comment by FraPazGal** [comment]
Hello @shubhranshu007, could you please detail the steps necessary to reproduce the issue? Sharing any custom parameters will also help us investigate the issue on our side. Thanks in advance!
