### ISSUE TITLE
[bitnami/supabase] Supabase storage uses deployment and readwriteonce PV

### ISSUE THREAD

**Issue by ggprod** [bitnami/charts#19219]
### Name and Version

bitnami/supbase 0.4.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy supabase storage chart
2. upgrade deployment of supbase storage chart
3. if using default value for storage.updateStrategy RollingUpdate of deployment the new pod will be stuck in pod initializing unable to mount PersistentVolume (because it is already mounted by previous pod which doesn't delete until new one is ready)

### What is the expected behavior?

should use a statefulset or else have default value for  storage.updateStrategy of Recreate

### What do you see instead?

a chart that can't be upgraded

### Additional information

The use of a deployment rather than statefulset would also be a problem if there is more than 1 replica as you can't have multiple pods connected to same persistentvolume if ReadWriteOnce

**Comment by juan131** [comment]
Hi @ggprod 

- What's your default storage class?
- Could you also please share the exact error reported by `kubectl describe pod POD_NAME` (where POD_NAME is a placeholder to be replaced with the actual name of the pod that's stuck initializing)?

It's very likely that you're using a "local storage" Persistent Volume and your new pod is being scheduled on a different cluster node where the PV can't be attached.

**Comment by ggprod** [comment]
This is for deployment to GKE (though the same thing would happen in EKS).  The default StorageClass uses persistent disks (for GKE) or EBS voume (for EKS).  These disks can only be connected to a single node at a time in read/write mode (ReadWriteOnce).  That could work for multiple pods on the same node, but I suppose in my case the RollingUpdate created the new pod on a separate node.  In general if the deployment were scaled to more than 1 replica odds are some of those replicas would be on different nodes.

I can't recall what the exact event was and it has since cleared.  It was something like:
`Unable to mount volumes for pod "podname": timeout expired waiting for volumes to attach or mount for pod "namespace"/"podname". list of unmounted volumes=[volume]. list of unattached volumes=[volume]`

Why did you not use a Statefulset for this?

**Comment by juan131** [comment]
Hi @ggprod 

Please note you can unset `storage.podAntiAffinityPreset` and set `storage.podAffinityPreset` to `hard` to ensure that storage pods are exclusively scheduled in the same K8s node:

- https://github.com/bitnami/charts/blob/main/bitnami/supabase/README.md#supabase-storage-parameters

Alternatively, you can use a storage compatible with reattaching between nodes. By the way, persistent disks on GKE should be compatible with this approach.

**Comment by ggprod** [comment]
> Alternatively, you can use a storage compatible with reattaching between nodes. By the way, persistent disks on GKE should be compatible with this approach.

GKE persistent disks must not support it (at least not using the default StorageClass and dynamic provisioning) or this problem would not have occurred.

You still haven't answered the simple question: Why did you not use a Statefulset for this?

**Comment by ggprod** [comment]
> That would depend on the property below. You can configure how rolling updates work:

Yes, but a RollingUpdate with maxSurge of 0 and maxUnavailable 1 isn't really a rolling update, it's equivalent to a Recreate (which is what we did to solve the problem but it means downtime during upgrades so again a hit to availability).

One other property of a StatefulSet is that it can create independent PVCs/PVs per pod. Rather than connecting all pods to the same PV (which makes this a sub-optimal solution)

**Comment by ggprod** [comment]
Anyway, it seems clear that this issue alone isn't going to make you reconsider using a Deployment in favour of a StatefulSet.  Personally I wouldn't recommend or use this chart for that reason (the compromised scaling and availability concerns) and perhaps this issue can be helpful to others who encounter similar problems.

**Comment by juan131** [comment]
Hi @ggprod 

We cannot use a statefulset because Supabase Storage doesn't support N different file storage backends.

Imagine you have a statefulset (using volume claim templates) with 3 replicas and a different PV per replica. Replicas aren't aware of other replicas existence (this component has no clustering support) and they just "see" the files available in their own storage bucket.

This is highly problematic since the associated K8s service distributes the requests between the replicas in a round-robin fashion. Therefore, a scenario like the one below could happen:

- You upload a file and the request is attended by replica 0. Therefore, file is stored in PV0.
- Later, you want to download the file and the request is attended by replica 1. The file doesn't exist in PV1 (the volume mounted on that replica) and it returns you a 404 error.

> Yes, but a RollingUpdate with maxSurge of 0 and maxUnavailable 1 isn't really a rolling update, it's equivalent to a Recreate (which is what we did to solve the problem but it means downtime during upgrades so again a hit to availability).

You can also use a PV with ReadWriteMany support (e.g. by using a NFS-based storage system).

**Comment by ggprod** [comment]
Yes, with a StatefulSet you couldn't just load balance requests with a service without either having logic doing replication or else partitioning the data based on key and pods forwarding read/write requests to the appropriate pod partition.  This is a common approach NoSQL/NewSQL databases take to scale

And yes, apologies, the statement about compromised scaling/availability was unfair as it didn't account for switching to using an NFS or NFS-like ReadWriteMany PV which would then allow scaling or rolling updates across nodes.

**Comment by juan131** [comment]
No need to apologize, it is always a pleasure to discuss the different approaches to address this kind of scalability / availability issues 😃
