### ISSUE TITLE
[bitnami/etcd] disaster recovery option is acually not working if replicas >1

### ISSUE THREAD

**Issue by nvtkaszpir** [bitnami/charts#1921]
**Which chart**:

bitnami/etcd version 4.4.14

**Description**

If you enable `disasterRecovery: true` and set `replicaCount: 3` then cronjob script to make snapshots will actually throw few errors:
- BITNAMI_DEBUG: unbound variable
- (and if you fix above) etcdctl snapshot actually works with only one member at a time - I believe this was caused by incorrect example in etcd docs itself (https://github.com/etcd-io/etcd/pull/11074) but unfortunately also assumes that snapshot feature was tested only with replicaCount 1.

**Steps to reproduce the issue:**
First, install nfs-server and then etcd:

```bash
helm install stable/nfs-server-provisioner

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install bitnami/etcd -f etcd-vals.yaml
```
etcd-vals.yaml
```yaml
statefulset:
  replicaCount: 3
auth:
  rbac:
    enabled: false
persistence:
  enabled: true
  size: 5Gi

disasterRecovery:
  enabled: true
  cronjob:
    schedule: "*/5 * * * *"
  pvc:
    size: 20Gi
    storageClassName: nfs

```

See what is going on with cronjobs, they are failing and it is visible if we decrease schedule even more.

**Describe the results you received:**

When cronjob starts it fails with message:

```text
BITNAMI_DEBUG: unbound variable
```
After fixing that by editing configmap there will be another message:

```text
Error: snapshot must be requested to one selected node, not multiple [http://be-etcd-0.be-etcd-headless.my-namespace.svc.cluster.local:2379 http://be-etcd-1.be-etcd-headless.my-namespace.svc.cluster.local:2379 http://be-etcd-2.be-etcd-headless.my-namespace.svc.cluster.local:2379]```
```

**Describe the results you expected:**

1. no unbound vars in script
2. properly used etcd snapshot command according to the documentation - https://github.com/etcd-io/etcd/pull/11074

**Additional information you deem important (e.g. issue happens only occasionally):**

I cna provide working fix via PR.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-gke.23", GitCommit:"a392833a56a82ab79d7e14695365b6df08f9ae38", GitTreeState:"clean", BuildDate:"2020-01-17T23:04:32Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```
This was tested on GKE.

**Comment by dani8art** [comment]
Hi @nvtkaszpir, thank you for opening the issue let's move to the PR.
Regards.
