### ISSUE TITLE
[bitnami/ghost] Unable to override the name of dependent mysql chart

### ISSUE THREAD

**Issue by aaroniscode** [bitnami/charts#19217]
### Name and Version

bitnami/ghost 19.5.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the chart with a fullnameOverride on mysql

### Are you using any custom parameters or values?

```yaml
mysql:
  fullnameOverride: foo
```

### What is the expected behavior?

Ghost should be using the correct mysql secret name of `foo` but instead it's looking for `ghost-mysql`

### What do you see instead?

The ghost Pod fails to start because the Secret name is incorrect.

Ghost should be using the correct mysql secret name of `foo` but instead it's looking for `ghost-mysql`

### Additional information

This is incorrectly set in the [bitnami/charts/tree/main/bitnami/ghost/templates/_helpers.tpl](https://github.com/bitnami/charts/blob/main/bitnami/ghost/templates/_helpers.tpl#L13) file.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
