### ISSUE TITLE
parse persistence resourcePolicy

### ISSUE THREAD

**Issue by brandan-schmitz** [bitnami/charts#19213]
### Name and Version

bitnami/parse

### What is the problem this feature will solve?

The ability to keep persistent volume claims when a helm chart is uninstalled.

### What is the feature you are proposing to solve the problem?

It would be nice to add a resourcePolicy that allows you to specify the keep option for the persistence specified in the parse server chart similar to the options in other charts such as MongoDB.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
