### ISSUE TITLE
[bitnami/redis-cluster] Error condition on socket for SYNC: Connection refused

### ISSUE THREAD

**Issue by vivet** [bitnami/charts#19225]
### Name and Version

bitnami/redis-cluster 8.6.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the chart and restart nodes.

### Are you using any custom parameters or values?

Nothing of importance.
Only some Kubernetes request and limits

### What is the expected behavior?

That the Redis pods restarts several times before everything is good.

### What do you see instead?

That they don't restart

### Additional information

Whenever nodes in the cluster restarts, due to security patching or upgrading Kubernetes.
It also happens when deploying an upgrade to the Helm chart.

This is what I see in the Redis pod logs:
```
1:S 10 Sep 2023 04:31:52.351 # Connection with master lost.
1:S 10 Sep 2023 04:31:52.351 * Caching the disconnected master state.
1:S 10 Sep 2023 04:31:52.351 * Reconnecting to MASTER 10.244.3.22:6379
1:S 10 Sep 2023 04:31:52.351 * MASTER <-> REPLICA sync started
1:S 10 Sep 2023 04:31:52.351 # Error condition on socket for SYNC: Connection refused
```
Eventually, after 5-7 restarts of some of the pods everything is up an running.
Is there a way to prevent the restarts?

I read about some similar issues where the solution should be to set the ```--commonConfiguration: |- bind 0.0.0.0```, but that parameter isn't available for the Redis-cluster chart, but on for the Redis chart.

**Comment by FraPazGal** [comment]
Hello @vivet, I have reproduced your case doing a simple `helm upgrade` and as you said the error msg appears sometime during the cluster restart. That said, the error should always be transient and the Master - Replica sync a matter of a couple retries.

The connection retries and pods restarts are part of the chart's nature to compensate the fact that a HA arch requires for additional complexity on its setup. Even so, the cluster should reach a stable state shortly after its installation.

As a side note, both the `bitnami/redis` and `bitnami/redis-cluster` charts use a configMap to add the Redis config so you could try your solution using the `redis.defaultConfigOverride` parameter. That said, it seems the `redis-cluster` chart already configures `bind` so your fix may not work in this case.

https://github.com/bitnami/charts/blob/de18b6a340bc6657fec1c89262ff482eb30b6125/bitnami/redis-cluster/templates/configmap.yaml#L107

**Comment by vivet** [comment]
Hi 
Thanks for the quick reply. 
It's reassuring that it's meant to be like that.
I don't think the "bind" will change anything, it was just an idea based on a post on the Internet.

I will close the issue.

**Comment by carrodher** [comment]
Sorry to hear that. Although this seems a completely different problem, could you please create a separate issue? Thanks

**Comment by vivet** [comment]
Okay, I didn't check the logs in detail, so I will try reproduce it next time I upgrade.
