### ISSUE TITLE
How the apisix run with skywalking

### ISSUE THREAD

**Issue by DoNotBugPlz** [bitnami/charts#19227]
### Name and Version

bitnami/apisix:2.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

perhaps Not bug，
I have installed a helm chart in kubesphere and I'm trying to use bitnami/apisix to connect with the skywalking plugin. According to the official documentation at https://apisix.apache.org/docs/apisix/plugins/skywalking/, I need to configure a conf/config.yaml file. However, I'm not sure where this configuration is located. I have added the skywalking configuration to all possible configuration items, but it doesn't seem to take effect. I have also enabled the skywalking plugin configuration in apisix. I'm confident that my skywalking is working. The screenshots below illustrate some of the issues I'm facing. I hope to get some help. Thank you!
<img width="872" alt="image" src="https://github.com/bitnami/charts/assets/42760659/438a52a4-1b8a-4e02-8c16-7c85772ed544">
<img width="1407" alt="image" src="https://github.com/bitnami/charts/assets/42760659/6c7faea6-e35f-4916-a775-b373c95b3128">
<img width="1271" alt="image" src="https://github.com/bitnami/charts/assets/42760659/849edebe-6c7a-43ef-a9ac-43ab740179ed">
<img width="1329" alt="image" src="https://github.com/bitnami/charts/assets/42760659/b5d7fc1c-60d0-4a70-a897-4d4ecfcd8b7b">
<img width="1236" alt="image" src="https://github.com/bitnami/charts/assets/42760659/9dbc21fc-ec42-4450-aac8-ed4cebafaf98">
<img width="1150" alt="image" src="https://github.com/bitnami/charts/assets/42760659/1bf8b240-1e42-4bc7-bf6d-cc702a2de3bb">

### Are you using any custom parameters or values?

that's nothing

### What is the expected behavior?

that's nothing

### What do you see instead?

that's nothing

### Additional information

that's nothing

**Comment by carrodher** [comment]
Closing this issue as duplicated of https://github.com/bitnami/charts/issues/19228
