### ISSUE TITLE
[bitnami/apisix] run with skywalking 

### ISSUE THREAD

**Issue by DoNotBugPlz** [bitnami/charts#19228]
### Name and Version

bitnami/apisix:2.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

perhaps Not bug，
I have installed a helm chart in kubesphere and I'm trying to use bitnami/apisix to connect with the skywalking plugin. According to the official documentation at https://apisix.apache.org/docs/apisix/plugins/skywalking/, I need to configure a conf/config.yaml file. However, I'm not sure where this configuration is located. I have added the skywalking configuration to all possible configuration items, but it doesn't seem to take effect. I have also enabled the skywalking plugin configuration in apisix. I'm confident that my skywalking is working. The screenshots below illustrate some of the issues I'm facing. I hope to get some help. Thank you!
<img width="872" alt="image" src="https://github.com/bitnami/charts/assets/42760659/438a52a4-1b8a-4e02-8c16-7c85772ed544">
<img width="1407" alt="image" src="https://github.com/bitnami/charts/assets/42760659/6c7faea6-e35f-4916-a775-b373c95b3128">
<img width="1271" alt="image" src="https://github.com/bitnami/charts/assets/42760659/849edebe-6c7a-43ef-a9ac-43ab740179ed">
<img width="1329" alt="image" src="https://github.com/bitnami/charts/assets/42760659/b5d7fc1c-60d0-4a70-a897-4d4ecfcd8b7b">
<img width="1236" alt="image" src="https://github.com/bitnami/charts/assets/42760659/9dbc21fc-ec42-4450-aac8-ed4cebafaf98">
<img width="1150" alt="image" src="https://github.com/bitnami/charts/assets/42760659/1bf8b240-1e42-4bc7-bf6d-cc702a2de3bb">

### Are you using any custom parameters or values?

that's nothing

### What is the expected behavior?

that's nothing

### What do you see instead?

that's nothing

**Comment by javsalgar** [comment]
Hi,

Do the logs show anything meaningful?

**Comment by DoNotBugPlz** [comment]
> Hi,
> 
> Do the logs show anything meaningful?

Hello, I have checked the logs of the four deployments in the screenshot below, but I couldn't find any information about Skywalking's tracing logs. Has anyone successfully implemented this feature here? From what I've seen, it seems that the hingress gateway can be configured with Skywalking directly to achieve gateway observability, but there doesn't seem to be such a configuration option for Bitnami's Apisix.

![Uploading image.png…]()


Based on your message, you added Skywalking configuration in the YAML file when creating Apisix, but it doesn't seem to be effective and you don't know what to do now.
![Uploading image.png…]()

**Comment by javsalgar** [comment]
Hi,

I'm not sure this has to do with the Bitnami packaging of APISIX, but in APISIX itself, as you were able to add the proper configuration options according to their documentation. Did you check with the upstream APISIX devs to see if there's any other extra setting missing?

**Comment by DoNotBugPlz** [comment]
> Hi,
> 
> I'm not sure this has to do with the Bitnami packaging of APISIX, but in APISIX itself, as you were able to add the proper configuration options according to their documentation. Did you check with the upstream APISIX devs to see if there's any other extra setting missing?

        Yes, sir, you have pointed out the key issue. Before I raised this question, I had already consulted the relevant documentation of APISIX and posted the links there. In fact, it is a configuration file modification called ./config/config.yaml. 
       After I installed Bitnami's Helm chart through Kubepsphere, I found that there were many configuration files and I was not sure which one to modify. So I made some attempts and added the relevant configuration of Skywalking to all the configuration files that I found. However, it did not take effect when I was confused. What I expected was to replace APISIX with Kubepsphere's built-in Nginx ingress, and then connect APISIX to Skywalking, so that there would be better observability. Currently, it cannot be achieved. 
       In addition, I also looked at another cloud-native gateway called Higress, and its Helm chart's value.yaml directly provides the Skywalking configuration. I was wondering if APISIX's Helm chart could also be like this, and I want to make a suggestion.
