### ISSUE TITLE
[bitnami/zookeeper] InitContainers is not properly excluded or set as an empty array

### ISSUE THREAD

**Issue by ghostsquad** [bitnami/charts#19249]
### Name and Version

zookeeper 12.1.12

### What architecture are you using?

None

### What steps will reproduce the bug?

there's conditions where you can end up with:

```
initContainers:
```
(and nothing below it) instead of

```
initContainers: []
```
(or with the field excluded).

Some software may dislike this if it's expecting `initContainers` to be an array.

https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/templates/statefulset.yaml#L77

### What do you see instead?

some software that's parsing this output I believe is complaining about `initContainers` not being valid. It should either be excluded _or_ set to an empty array.

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the issue. This should be a matter of adding an `if` statement to ensure that it does not get empty. Would you like to submit a PR with the fix?
