### ISSUE TITLE
[bitnami/airflow] Error: pg_config executable not found.

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#19242]
### Name and Version

bitnami/airflow

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Installing psycopg2 library from requirements.txt with configmap  

### What do you see instead?

```
 python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-24grtjxt/psycopg2.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
```

### Additional information

When installing psycopg2 there are additional libraries that should be installed 
libpq-dev python3-dev

Is there a way to do that?

**Comment by oktayalizada** [comment]
Hi,
Could you please tell me what you mean by building the extension internally? Do you mean creating a new dockerfile from the original bitnami docker images and adding installation of these libraries?

**Comment by javsalgar** [comment]
Yes, that could be a solution
