### ISSUE TITLE
[bitnami/harbor] Upgrade Harbor to version 2.9

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#19248]
### Name and Version

bitnami/harbor

### What is the problem this feature will solve?

Currently, the latest release of Harbor isn't supported.  Harbor 2.9 introduces some breaking changes by removing Notary.

### What is the feature you are proposing to solve the problem?

Update Harbor and remove Notary from its components.

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by Mauraza** [comment]
Hi @lusu007,

The changes are implemented in this PR https://github.com/bitnami/charts/pull/19359
