### ISSUE TITLE
Appsmith - Problem with connecting the GIT repository

### ISSUE THREAD

**Issue by k0muc** [bitnami/charts#19258]
### Name and Version

bitnami/appsmith

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1 Run Appsmith using bitnami charts
2 Create a sample application in Appsmith
3 Try connecting to a GIT repository using Appsmith's built-in interface (button on the bottom left bar)

After this, Appsmith attempts to create a local GIT repository in the /data resource. Unfortunately, the bitnami deployment does not provide such a resource, and Appsmith does not have the ability to create the directory.

In the official bitnami repository, this directory is mounted on a resource inside the appsmith-stacks directory.

### Are you using any custom parameters or values?

I used the parameters, but also tested on a pure chart straight from the bitnami repository.
I ran on localhost, on kubernetes and on openshift - the same in all cases.

### What is the expected behavior?

Correct connection to the GIT repository.

### What do you see instead?

Error about no access to /data directory.

### Additional information

I managed to get the mechanism working by mounting an additional resource as extraVolumes in the form of emptyDir, but I don't know if this is the right solution.
Maybe a PVC should be considered, or analysed to use one of the PVCs already created.

**Comment by jliedy** [comment]
If you are running this with persistent storage on the backend deployment where it gets mounted at /bitnami/appsmith, I got around this by adding the following to my appsmith values file:

```
backend:
  extraEnvVars:
    - name: APPSMITH_GIT_ROOT
      value: "/bitnami/appsmith/git-data"
```

It seems like default settings has Appsmith looking for a /data directory in the "backend" deployment, so it may be helpful to have an additional persistent volume created for that mount point

**Comment by aoterolorenzo** [comment]
Hi @k0muc, @jliedy, 

Indeed would be helpful to create an additional volume for this. I will create an internal task for the team to address this issue. We cannot provide an ETA since it depends of the team's workload, but we will reach you back here once done.

**Comment by jliedy** [comment]
@aoterolorenzo I'd say with the reasonable workarounds available, it's not that much of a priority.

**Comment by jliedy** [comment]
After looking at the templates for the chart, I could probably submit a pull request that does this, but I think I'd rather ask the maintainers if they would prefer to set the `APPSMITH_GIT_ROOT` environment variable to a subdirectory of the current PVC by default or if they would rather have an additional PVC.  I could probably add either..

**Comment by aoterolorenzo** [comment]
> After looking at the templates for the chart, I could probably submit a pull request that does this, but I think I'd rather ask the maintainers if they would prefer to set the `APPSMITH_GIT_ROOT` environment variable to a subdirectory of the current PVC by default or if they would rather have an additional PVC. I could probably add either..

Hey @jliedy,

Sorry for not having offered to contribute yourself with a PR! We will be more than glad to review it!

I cannot see any cons on using the same PVC. Feel free to give it a try, you can just add me as a reviewer of the outcome PR :)

**Comment by jliedy** [comment]
I've got a pull request at https://github.com/bitnami/charts/pull/19598 that I think covers this use case.  It's kinda touchy to do because it could bork up an existing install if it gets set.

**Comment by jliedy** [comment]
@aoterolorenzo I don't seem to have the ability (or I am missing the option to) set you as a reviewer.

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
