### ISSUE TITLE
[bitnami/airflow] Can't import module 'sklearn'

### ISSUE THREAD

**Issue by thucnd55** [bitnami/charts#19260]
### Name and Version

bitnami/airflow Package Version 14.3.6 / App Version 2.6.3 

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I installed dependences from requirements.txt by this way
Update the value in worker session:

requirements.txt 

`scikit-learn==1.3.0`

value.yaml

```
worker:
  args:
      [
        "-ec",
        "source /opt/bitnami/airflow/venv/bin/activate  && pip install -r
          /opt/bitnami/airflow/dags/git_mlops-dags/requirements.txt && deactivate
  
  
          /opt/bitnami/scripts/airflow-worker/entrypoint.sh
          /opt/bitnami/scripts/airflow-worker/run.sh\n"
      ]
```

After that i checked on pod airflow-worker-0 => container airflow-worker

`kubectl exec -it  airflow-worker-0 -n mlops bash -c airflow-worker`

`source activate`

this is result => scikit-learn is installed 

```
(venv) I have no name!@airflow-worker-0:/$ pip list | grep scikit-learn
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
scikit-learn                              1.3.0
```

But when using in DAG

`from sklearn.cluster import KMeans`

the error occur like that on Airflow UI 

```
DAG Import Errors

Broken DAG: [/opt/bitnami/airflow/dags/git_mlops-dags/b0ttle_airflow.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/git_mlops-dags/b0ttle_airflow.py", line 3, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
```

### Are you using any custom parameters or values?

worker:
  args:
      [
        "-ec",
        "source /opt/bitnami/airflow/venv/bin/activate  && pip install -r
          /opt/bitnami/airflow/dags/git_mlops-dags/requirements.txt && deactivate
  
  
          /opt/bitnami/scripts/airflow-worker/entrypoint.sh
          /opt/bitnami/scripts/airflow-worker/run.sh\n"
      ]

### What do you see instead?

```
DAG Import Errors

Broken DAG: [/opt/bitnami/airflow/dags/git_mlops-dags/b0ttle_airflow.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/git_mlops-dags/b0ttle_airflow.py", line 3, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
```

**Comment by javsalgar** [comment]
Hi,

Could you share the exact requirements.txt to see if we can reproduce the issue?

**Comment by thucnd55** [comment]
Hello @javsalgar 
This is my requirements

```
boto3==1.28.43
botocore==1.31.43
certifi==2023.7.22
charset-normalizer==3.2.0
colorama==0.4.6
cPython==0.0.6
DateTime==5.2
dnspython==2.4.2
elastic-transport==8.4.0
elasticsearch==7.13.4
et-xmlfile==1.1.0
idna==3.4
jmespath==1.0.1
joblib==1.3.2
numpy==1.25.2
openpyxl==3.1.2
pandas==2.1.0
pymongo==4.5.0
python-dateutil==2.8.2
pytz==2023.3.post1
requests==2.31.0
s3transfer==0.6.2
scikit-learn==1.3.0
scipy==1.11.2
six==1.16.0
#sklearn==0.0.post9
threadpoolctl==3.2.0
tqdm==4.66.1
tzdata==2023.3
urllib3==1.26.16
zope.interface==6.0
```
Other libs seem be ok except scikit-learn==1.3.0

**Comment by thucnd55** [comment]
Hello. I found the solution following this 
[https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#:~:text=in%20the%20callable.-,Bad%20example%3A,%2C%205)%0A%20%20%20%20%20%20%20%20print(a)%0A%20%20%20%20%20%20%20%20return%20a%0A%0A%20%20%20%20print_array(),-In%20the%20Bad](https://github.com/bitnami/charts/issues/19260#)

**Comment by javsalgar** [comment]
Thanks for sharing your solution!
