### ISSUE TITLE
[bitnami/kafka] cannot establish SSL connection to broker

### ISSUE THREAD

**Issue by ETisREAL** [bitnami/charts#19266]
### Name and Version

bitnami/kafka 25.1.10

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create certificates and the relative secret (kafka-certs) containing the root CA and kafka.crt kafka.key
2. Install the stack specifying the tls.existingSecret="kafka-certs"
3. Create client certificate and key, signing the certificate with the same CA
4. Launching the script to connect

### Are you using any custom parameters or values?

This is the python script I am using to test the connection:
```
from confluent_kafka import Producer, KafkaError
import json

def delivery_report(err, msg):
    if err is not None:
        print('Message delivery failed: {}'.format(err))
    else:
        print('Message delivered to {} [{}]'.format(msg.topic(), msg.partition()))

def main():
    conf = {
        'bootstrap.servers': 'kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092',
        'security.protocol': 'sasl_ssl',
        'sasl.mechanisms': 'PLAIN',
        'sasl.username': 'user1',
        'sasl.password': 'client',
        'ssl.ca.location': '/certs/root/kafka-ca.crt',
        'ssl.certificate.location': '/certs/cert/client.crt',
        'ssl.key.location': '/certs/key/client.key',
    }

    producer = Producer(conf)
    topic = 'your_topic'  # Replace with your desired topic name

    message = {
        'key': 'your_key',
        'value': 'your_value'
    }

    message_str = json.dumps(message)

    producer.produce(topic, key=message['key'], value=message_str, callback=delivery_report)
    producer.flush()

if __name__ == "__main__":
    main()

```

Which is running in a pod in which I mount the secrets containing its cert and key, and the root cert

### What is the expected behavior?

I should be able to establish the SASL_SSL connection but I get the below error instead :/

### What do you see instead?

%3|1694627041.133|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://kafka-controller-0.kafka-controller-headless.default]: sasl_ssl://kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092/bootstrap: SSL handshake failed: error:0A000086:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 14ms in state SSL_HANDSHAKE)

### Additional information

* The ssl.ca.location is correct, I have double, tripled checked it
* I did (install ca-certificates package) in my ubuntu pod, but it didn't make any difference. Is there some other configuration (other than simply installing this package) that am I missing? Isn't the python package supposed to handle this verification anyway?

Thanks in advance

**Comment by ETisREAL** [comment]
I'll add this, if I turn off the hostname verification the connection is established
```
conf = {
        'bootstrap.servers': 'kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092',
        'security.protocol': 'sasl_ssl',
        'sasl.mechanisms': 'PLAIN',
        'sasl.username': 'user1',
        'sasl.password': 'client',
        'ssl.endpoint.identification.algorithm': 'none',
        'ssl.ca.location': '/certs/root/kafka-ca.crt',
        'ssl.certificate.location': '/certs/cert/client.crt',
        'ssl.key.location': '/certs/key/client.key',
    }
```

However, despite correctly configuring the certificate hostname to 'k-controller-0.k-controller-headless.default.svc.cluster.local' (*note* had to fullNameOverride otherwise the CName was too long), it doesn't work :/ 

How come I get the:
```
INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /10.64.1.44 (channelId=10.64.2.81:9092-10.64.1.44:43026-19) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```
when the broker CNAME corresponds with the certificate?

Oh and also, I checked with openssl, `openssl s_client -connect k-controller-0.k-controller-headless.default.svc.cluster.local:9092 -showcerts -CAfile certs/root/kafka-ca.crt -cert certs/cert/client.crt -key certs/key/client.key' and everything went fine there

**Comment by ETisREAL** [comment]
My bad, I had a misconfiguration and was using the wrong certificates on the brokers. If you get into some trouble, remember that each broker/controller needs it OWN certificate pointing the CName to ex. k-controller-0.k-controller-headless.default.svc.cluster.local  since by default hostname verification is on. All the best my friends :)

**Comment by MuhammadJamee** [comment]
> My bad, I had a misconfiguration and was using the wrong certificates on the brokers. If you get into some trouble, remember that each broker/controller needs it OWN certificate pointing the CName to ex. k-controller-0.k-controller-headless.default.svc.cluster.local since by default hostname verification is on. All the best my friends :)

Is there any default hostname verification parameter where i can turn if off?
