### ISSUE TITLE
Additional documentation request, for adding scrape configs to prometheus-operator.

### ISSUE THREAD

**Issue by mzs114** [bitnami/charts#1927]
**Which chart**:  bitnami/prometheus-operator:0.12.2

**Description**

Please elaborate and/or provide examples on adding additional Scrape configs to prometheu-operator.

**Steps to reproduce the issue:**

The current documentation is not clear enough, do we need to generate the secret like how CoreOS documentation suggests?

**Describe the results you received:**

`additionalScrapeConfigsExternal: true` causes the release to fail.

**Describe the results you expected:**

User be able to add additional scrape configs, the instructions clear with an example to make it easy and explicit.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**: 

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @mzs114 

Did you take a look to the section below in the **README.md**?

- https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator#additional-scrape-configurations

**Comment by mzs114** [comment]
Hi @juan131, I did look at that and that is not clear enough, as the documentation of coreos/prometheus-operator mentions additional steps to configure them.

https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md

**Comment by juan131** [comment]
Hi @mzs114 

The **README.md** available in the chart assumes you already did steps **1-2-3** on [coreos/prometheus-operator guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) (create the additional configuration, make a secret and create the configmap with its content). You only need to ensure this configmap exists in the same namespace you're going to deploy Prometheus, and its name is appropriate (the chart assumes has a specific format, generated with the `prometheus-operator.prometheus.fullname` template with a `-scrape-config` suffix).

The step 4 (referencing it in the `prometheus.yaml` CRD) is not necessary, the chart will automatically do it for you when you install it using the values below:

```yaml
prometheus:
  additionalScrapeConfigsExternal: true
```

**Comment by BlackTurtle123** [comment]
> Hi @mzs114
> 
> The **README.md** available in the chart assumes you already did steps **1-2-3** on [coreos/prometheus-operator guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) (create the additional configuration, make a secret and create the configmap with its content). You only need to ensure this configmap exists in the same namespace you're going to deploy Prometheus, and its name is appropriate (the chart assumes has a specific format, generated with the `prometheus-operator.prometheus.fullname` template with a `-scrape-config` suffix).
> 
> The step 4 (referencing it in the `prometheus.yaml` CRD) is not necessary, the chart will automatically do it for you when you install it using the values below:
> 
> ```yaml
> prometheus:
>   additionalScrapeConfigsExternal: true
> ```

I have to say that the documentation is indeed very unclear. Also I didn't get from anywhere that we would need to use the steps in coreos by reading bitnami website or readme... Might be good to improve this I guess?

**Comment by juan131** [comment]
Sure! @BlackTurtle123 

Thanks for your feedback, I'll mark this issue to be reviewed by the Docs team.

**Comment by zzhao2010** [comment]
> Hi @mzs114
> 
> The **README.md** available in the chart assumes you already did steps **1-2-3** on [coreos/prometheus-operator guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) (create the additional configuration, make a secret and create the configmap with its content). You only need to ensure this configmap exists in the same namespace you're going to deploy Prometheus, and its name is appropriate (the chart assumes has a specific format, generated with the `prometheus-operator.prometheus.fullname` template with a `-scrape-config` suffix).
> 
> The step 4 (referencing it in the `prometheus.yaml` CRD) is not necessary, the chart will automatically do it for you when you install it using the values below:
> 
> ```yaml
> prometheus:
>   additionalScrapeConfigsExternal: true
> ```

@juan131 
This doc https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md is also out-dated. The command in the doc has been deprecated. Also I don't see a step to create the configmap with its content. Can you provide more detail how do you create the configmap with its content? Thanks.

**Comment by juan131** [comment]
Hi @zzhao2010 

We (Bitnami) are not maintaining the CoreOS documentation, so please create an issue on their side to update that docs.

> Can you provide more detail how do you create the configmap with its content?

You can simply create the ConfigMap definition in a YAML file and create it using the command below:

```console
$ kubectl create -f /path/to/your/configmap.yaml --namespace NAMESPACE
```

Find more information about configmaps in the K8s docs: https://kubernetes.io/docs/concepts/configuration/configmap
