### ISSUE TITLE
[bitnami/mongodb] Unable to backup with auth: {enabled false}

### ISSUE THREAD

**Issue by sfhl** [bitnami/charts#19273]
### Name and Version

bitnami/mongodb latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm install` with `backup: {enabled: true}`

### Are you using any custom parameters or values?

no

### What is the expected behavior?

backup is created

### What do you see instead?

backup fails, because of the fact that the container, created by th job wants to mount a non-existent secret `mongodb` to access `MONGODB_ROOT_PASSWORD`.
In the next step the command
```
mongodump --username=${MONGODB_ROOT_USER} --password=${MONGODB_ROOT_PASSWORD}
--host=${MONGODB_SERVICE_NAME} --port=${MONGODB_PORT_NUMBER} ${MONGODB_CLIENT_EXTRA_FLAGS}
--oplog --gzip --archive=${MONGODUMP_DIR}/mongodump-$(date '+%Y-%m-%d-%H-%M').gz
```

will fail, because authentication is disabled.

### Additional information

i have created a pull request to fix the issue:
https://github.com/bitnami/charts/pull/19272

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
