### ISSUE TITLE
[bitnami/external-dns] schema has mistakes

### ISSUE THREAD

**Issue by sstarcher** [bitnami/charts#19284]
### Name and Version

bitnami/external-dns 6.25.1

### What architecture are you using?

None

### What steps will reproduce the bug?

- aws.zonesCacheDuration: Invalid type. Expected: number, given: string in schema is a number, but the expected values are in the format of `3h`

### What do you see instead?

- aws.zonesCacheDuration: Invalid type. Expected: number, given: string

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting the issue. Would you like to submit a PR fixing the values.yaml, by which the schema is generated?

**Comment by fmulero** [comment]
Thanks a lot @sstarcher and sorry for the inconvenience. We've just reverted the changes from https://github.com/bitnami/charts/pull/19194 and in a few hours a new version will be released fixing this problem.
