### ISSUE TITLE
Modify ULIMIT default value from 65536 to 65535 due to containerd limit

### ISSUE THREAD

**Issue by bognarbalazs** [bitnami/charts#19294]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
ENV:
Kubernetes: 1.25.6 
Containerd: 1.6.15
OS: Ubuntu 20.04 LTS
Helm chart versions: 11.0.3 , 10.x 
```
### Are you using any custom parameters or values?
```
       "ulimitNofiles": {
            "type": "string",
            "description": "RabbitMQ Max File Descriptors",
            "default": "65536"
```
### What is the expected behavior?

Ulimit default values is 65536

### What do you see instead?

Containerd has a limit for ulimit: 65535 , but the default is 65536 in the helm chart. With the actual containerd version, the pod won't start. Also set for the ulimit is not permitted, which is seen in the logs .

### Additional information

Please modify the default value to 65535 , that the users who use containerd, should not set the ulimit values, because at first it won't set, and also don't need to set a "ulimitNofiles": " " value to the container be able to start.

**Comment by rafariossaa** [comment]
Hi,
  Could you point me to some documentation on this limit ?
  In theory the max number of file descriptors opened is delimited by: `sysctl fs.file-max`.
  We test the charts on AWS, GCE, Azure and we have not found issues with this. Even testing it locally on minikube I have not issues with this default value, or even if I rise it to 80000.
