### ISSUE TITLE
[Bitnami/cassandra] How to custom individual configure in cassandra.yaml

### ISSUE THREAD

**Issue by conceptjs** [bitnami/charts#19304]
### Name and Version

bitnami/cassandra 9.2.3

### What is the problem this feature will solve?

Currently Bitnami/cassandra helm chart uses _existingConfiguration_ to use a configMap to customize the configurations:

`existingConfiguration: cassandra-config`

However, _existingConfiguration_ expects the whole cassandra.yaml to be used for customization. In our case we only want to customize a single property or a few properties in cassandra.yaml file without overwrite the entire cassandra.yaml file.

The discussion in [issue #5574](https://github.com/bitnami/charts/issues/5574) suggested that we can copy cassandra.yaml from the default configure in the pod, customize the attribute(s) and use it as configMap in _existingConfiguration_.

However, this approach won't work in a cluster deployment where multiple pods are created and they have different cassandra.yaml with its own ip address configure.

### What is the feature you are proposing to solve the problem?

Bitnami/cassandra helm chart  should support individual properties with _existingConfiguration_, where we can pass only single or a few properties, for example:

`batch_size_fail_threshold_in_kb: 10000`

During the deployment only this property will be overwritten by the configMap and all other properties in cassandra.yaml file should be kept with default values.

Any comment or suggestion on alternative solutions or am I missing something here? Help is much appreciated!

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by akshayvermadtu** [comment]
Any update on this ?

I am not able to override the Cassandra config yaml in case of HA k8s deployment of Bitnami cassandra.

**Comment by seleznev** [comment]
As a workaround, individual options can be overridden via `extraEnvVars` chart value with `CASSANDRA_CFG_YAML_*` environment variables (see for details: https://github.com/bitnami/containers/pull/63358).

For example:

```yaml
extraEnvVars:
- name: CASSANDRA_CFG_YAML_MEMTABLE_ALLOCATION_TYPE
  value: offheap_objects
- name: CASSANDRA_CFG_YAML_MEMTABLE_OFFHEAP_SPACE
  value: 2GiB
```

**Comment by akshayvermadtu** [comment]
What if I want to pass unique value to each Cassandra replica ?

For example in case of restoring from snapshot, I need to pass different [initial_token](https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/configuration/configCassandra_yaml.html#configCassandra_yaml__initial_token) value to each Cassandra replica.

**Comment by jalsanishant** [comment]
I got with this same issue passing value of cassandra.yaml through custom existingconfiguration, configmap or something else? opened similar issue-
https://github.com/bitnami/charts/issues/32184
