### ISSUE TITLE
[bitnami/grafana] Allow to set loadBalancerClass in grafana chart

### ISSUE THREAD

**Issue by laozc** [bitnami/charts#19316]
### Name and Version

bitnami/grafana 9.1.2

### What is the problem this feature will solve?

`loadBalancerClass` is introduced since Kubernetes 1.24 to allow specify the LB provider.
The current grafana chart doe snot support this flag.

### What is the feature you are proposing to solve the problem?

Supports `loadBalancerClass` in grafana helm chart.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
