### ISSUE TITLE
[bitnami/matomo] values don't meet the specifications of the schema(s) in the following chart(s): smtpPort: Invalid type. Expected: string, given: integer

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#19321]
### Name and Version

bitnami/matomo 2.2.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. set `smtpPort: 465`
2. deploy chart
3. see error: `smtpPort: Invalid type. Expected: string, given: integer`

### Are you using any custom parameters or values?

```
smtpPort: 465
```

### What is the expected behavior?

shold deploy

### What do you see instead?

mentioned error caused by 
- https://github.com/bitnami/charts/pull/19194

### Additional information

related to
- #19320

**Comment by fmulero** [comment]
Thanks a lot @viceice and sorry for the inconvenience. We've just reverted the changes you mentioned and in a few hours a new version will be released fixing this problem.

**Comment by viceice** [comment]
@fmulero latest matomo releases `v2.2.3` and `v2.3.0` failed to publish, so this is still an issue

https://hub.docker.com/r/bitnamicharts/matomo/tags
