### ISSUE TITLE
[bitnami/kafka] How to use BKPR's SSL management for production-ready Kafka

### ISSUE THREAD

**Issue by octopyth** [bitnami/charts#1933]
**Which chart**:
Kafka latest

**Description**

I have installed Bitnami Kubernetes Production Runtime and I was hoping to use the SSL encryption to access the Kafka cluster externally. While this works for other charts, for Kafka I run into:
```
Error: execution error at (kafka/templates/statefulset.yaml:308:27): A secret containing the Kafka JKS certificates is required when authentication in enabled
```
BKPR is advertised as handling the SSL encryption for other charts, and it works beautifully except for Kafka. Can you guide me on how I can leverage the BKPR installation to complete the Kafka setup?

**Steps to reproduce the issue:**

1. After installing BKPR and making sure everything is working, install the Kafka chart with
```
kubectl create ns kafka
helm install bitnami/kafka \
-n kafka \
--set replicaCount=3,\
allowPlaintextListener=false,\
defaultReplicationFactor=3,\
offsetsTopicReplicationFactor=3,\
transactionStateLogReplicationFactor=3,\
transactionStateLogMinIsr=3,\
auth.enabled=true,\
metrics.kafka.enabled=true,\
metrics.jmx.enabled=true,\
zookeeper.metrics.enabled=true,\
externalAccess.enabled=true,\
externalAccess.service.type=NodePort,\
externalAccess.service.domain='kafka.my-domain.com',\
externalAccess.service.nodePort={'node-port-1','node-port-2','node-port-3'} \
--generate-name
```

**Describe the results you received:**

```
Error: execution error at (kafka/templates/statefulset.yaml:308:27): A secret containing the Kafka JKS certificates is required when authentication in enabled
```

**Describe the results you expected:**

I was hoping to take advantage of BKPR setup

**Additional information you deem important (e.g. issue happens only occasionally):**

```
kubectl get deployments -n kubeprod
```
![image](https://user-images.githubusercontent.com/640759/74611743-09d41d00-50ff-11ea-8c51-61133c979280.png)

**Version of Helm and Kubernetes**:
The Kubernetes is in Azure (AKS).

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by octopyth** [comment]
I am expecting the same experience as when I installed kubeapps: the secret is automatically created when ingress is enabled. Check https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/templates/tls-secrets.yaml

**Comment by sameersbn** [comment]
In BKPR we only configure DNS records and provision LetsEncrypt TLS certificates for web based services that use the ingress resource (routed through nginx-ingress-controller).

You should manually 
BKPR has cert-manager installed which can be used to provision TLS certificates for kafka. 

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    name: kafka
  name: kafka-tls
  namespace: kafka
spec:
  dnsNames:
  - kafka.my-domain.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: kafka-tls
```

Cert manager should provision the certificate and you should be able to configure kafka to use it appropriately.

**Comment by octopyth** [comment]
@sameersbn thanks for the feedback, I followed your advice and created Certificate resource which can be referenced through the kafka-tls secret.
```
nano kafka-cert.yaml # paste content inside
kubectl apply -f kafka-cert.yaml -n kafka
```
So far so good. Now following the instructions from https://github.com/bitnami/charts/blob/master/bitnami/kafka/README.md I try to setup kafka with
```
helm install kafka bitnami/kafka \
-n kafka \
--set replicaCount=3,\
allowPlaintextListener=false,\
defaultReplicationFactor=3,\
offsetsTopicReplicationFactor=3,\
transactionStateLogReplicationFactor=3,\
transactionStateLogMinIsr=3,\
auth.enabled=true,\
auth.certificatesSecret=kafka-tls,\
metrics.kafka.enabled=true,\
metrics.jmx.enabled=true,\
zookeeper.metrics.enabled=true,\
externalAccess.enabled=true,\
externalAccess.service.type=NodePort,\
externalAccess.service.domain=kafka.my-domain.com,\
externalAccess.service.nodePort={'node-port-1','node-port-2','node-port-3'}
```
This gives error:
`Error: must either provide a name or specify --generate-name`

When I try:
```
helm install bitnami/kafka \
-n kafka \
--set replicaCount=3,\
allowPlaintextListener=false,\
defaultReplicationFactor=3,\
offsetsTopicReplicationFactor=3,\
transactionStateLogReplicationFactor=3,\
transactionStateLogMinIsr=3,\
auth.enabled=true,\
auth.certificatesSecret=kafka-tls,\
metrics.kafka.enabled=true,\
metrics.jmx.enabled=true,\
zookeeper.metrics.enabled=true,\
externalAccess.enabled=true,\
externalAccess.service.type=NodePort,\
externalAccess.service.domain=kafka.my-domain.com,\
externalAccess.service.nodePort={'node-port-1','node-port-2','node-port-3'} --generate-name
```
I run into error:
`Error: template: kafka/templates/NOTES.txt:115:3: executing "kafka/templates/NOTES.txt" at <include "kafka.validateValues" .>: error calling include: template: kafka/templates/_helpers.tpl:275:51: executing "kafka.validateValues" at <fail>: error calling fail:
VALUES VALIDATION:
kafka: .Values.externalAccess.service.nodePort
    Number of replicas and nodePort array length must be the same.`

What am I doing wrong?

**Comment by octopyth** [comment]
What am I doing right?
