### ISSUE TITLE
[charts/bitnami/mongodb-sharded] Question: can I convert a replicaSet to sharded cluster?

### ISSUE THREAD

**Issue by BigFatDog** [bitnami/charts#1935]
I have deployed a replicaSet using helm chart `bitnami/mongodb` from ` https://charts.bitnami.com/bitnami` with `replicaSet` enabled

Is there a way for me to convert the replicaSet to a sharded cluster using `charts/bitnami/mongodb-sharded`?

**Comment by javsalgar** [comment]
Hi,

I would say that not in a straightforward way. What I would do is to deploy a sharded cluster. Then I would export and import the data from your initial instance to this new cluster. I think that would be the safest and easiest way.

**Comment by BigFatDog** [comment]
Thank You for your reply.

I'd take your advice and build a new cluster.

**Comment by javsalgar** [comment]
Please do not hesitate to open a new ticket if you find any issues.
