### ISSUE TITLE
IBM feed does not include all charts

### ISSUE THREAD

**Issue by gmendel** [bitnami/charts#1937]
**Which chart**:

phabricator , postgresql-ha, thanos 

**Description**

On the IBM's catalog, the sync. is looking at the following URL for additional information: https://bitnami.com/library/ibm_charts_report.json in the last few weeks

There are no entries for the above charts

**Steps to reproduce the issue:**

The charts above are not in the feed

**Describe the results you received:**

**Comment by beltran-rubo** [comment]
Sorry for the inconvenience. Thanos and PostgreSQL-HA are now available in the feed. We are working to make the Phabricator chart available in the JSON feed as well.

**Comment by beltran-rubo** [comment]
All of them are available in the feed now. Thanks for reporting it.
