### ISSUE TITLE
[bitnami/redis] redis 18.  Failed to install helm chart: parse error at (redis/charts/common/templates/_labels.tpl:14): unclosed action

### ISSUE THREAD

**Issue by Shad0w1990** [bitnami/charts#19384]
### Name and Version

bitnami/redis18.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

install helm chart redis on red hat openshift

### Are you using any custom parameters or values?

no

### What do you see instead?

Failed to install helm chart: parse error at (redis/charts/common/templates/_labels.tpl:14): unclosed action

**Comment by eoc-ross** [comment]
Had the same problem here. Solved by upgrading helm v3.2 to v3.10

**Comment by carrodher** [comment]
We are not able to reproduce the issue on our side using the default config, could you please provide more info about your specific use case?

**Comment by JiaLiangoooo** [comment]
You can use a low version of helm to install the chart, I also reproduced the problem.

**Comment by Kyefer** [comment]
I think this PR resolves the issue in the `common` library https://github.com/bitnami/charts/pull/19177
