### ISSUE TITLE
[bitnami/contour] I want to use CertManager without using certgen in contour.

### ISSUE THREAD

**Issue by kahirokunn** [bitnami/charts#19409]
### Name and Version

bitnami/contour 13.0.0

### What is the problem this feature will solve?

I would like to have cert manager mode if possible, as it is slow to generate and generate certgen pods and increases the number of things to monitor!

### What is the feature you are proposing to solve the problem?

If the contour.certManager flag is set, I'd like to use that.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Keep

**Comment by tsaarni** [comment]
I can work on this.

**Comment by kahirokunn** [comment]
Thx!
