### ISSUE TITLE
jasperreports: any easy way to enable disabled sources (customDataSourcesToHide)?

### ISSUE THREAD

**Issue by bbigras** [bitnami/charts#19403]
### Name and Version

bitnami/jasperreports

### Are you using any custom parameters or values?

Any easy way to enable sources in applicationContext-remote-services.xml?

**Comment by carrodher** [comment]
For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
