### ISSUE TITLE
spring-cloud-dataflow does not support sha256_password for MySQL.

### ISSUE THREAD

**Issue by hyeonggiri** [bitnami/charts#19416]
### Name and Version

bitnami/spring-cloud-dataflow Release 23.1.2

### What is the problem this feature will solve?
```
java.sql.SQLException: Client does not support authentication protocol requested by server. plugin type was = 'sha256_password'
        at org.mariadb.jdbc.plugin.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:48)
        at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:272)
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:185)
        at org.mariadb.jdbc.Driver.connect(Driver.java:70)
```

Spring Cloud Data Flow version 14.0.2 does support 'sha256_password' for MySQL, but it is not supported in later versions. I would like to update my Bitnami Spring Cloud Data Flow deployment from version 14.0.2 to version 23.1.2.

### What is the feature you are proposing to solve the problem?

I believe you only need to add 'com.mysql.cj.jdbc.Driver' to the Spring Cloud Data Flow configuration. If there is any other solution, please share it with me. Thanks in advance.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
