### ISSUE TITLE
[bitnami/prometheus] Allow to set service loadBalancerClass in prometheus chart

### ISSUE THREAD

**Issue by laozc** [bitnami/charts#19419]
### Name and Version

bitnami/prometheus 0.2.2

### What is the problem this feature will solve?

Allow to set service loadBalancerClass in `prometheus` chart

### What is the feature you are proposing to solve the problem?

Supports loadBalancerClass in `prometheus` helm chart.
See #19316 for the same for `grafana`

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
