### ISSUE TITLE
Promethues Exporter Plugin for Discourse 

### ISSUE THREAD

**Issue by SurajV121** [bitnami/charts#19424]
### Name and Version

bitnami/discourse 3.0.6-debian-11-r17

### What do you see instead?

I want to use the Prometheus Exporter Plugin for bitnami Discourse, So can you please specify if the Prometheus Exporter Plugin is supported for discourse running in the Kubernetes Cluster, (bitnami/discourse)?

**Comment by carrodher** [comment]
There is not any bundled exporter in the bitnami/discourse Helm chart but you can use the sidecars feature to add any container you want to deploy at the same time as the main container, see https://github.com/bitnami/charts/tree/main/bitnami/discourse#sidecars
