### ISSUE TITLE
airflow UI doesn't show logs if the task fails.

### ISSUE THREAD

**Issue by naveenbussari** [bitnami/charts#19433]
### Name and Version

bitnami/airflow:14.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Executor: kubernetesExecutor
2. create a dag with one task that uses BashOperator. 
3. Added a requirements section in values.yaml and mentioned the packages that need to be installed in the worker pod.
4. Mounted the 'requirements.txt' to /bitnami/python in worker. 
5. First cat a file that exists(/bitnami/python/requirements.txt) and the run sleep command for 100 seconds followed by cat a file that doesn't exist(/bitnami/python/requirements.txt). ( We just want the task that should run for some time and eventually fail)

```python
from datetime import datetime,timedelta
from textwrap import dedent
from airflow.operators.email_operator import EmailOperator

from airflow.models import Variable
import os

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.utils.dates import days_ago

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
}


with DAG(
    'sleep-dag',
    default_args=default_args,
    description='',
   
    schedule_interval= "6 10 * * *",
    start_date=datetime(2023,9,18),
   

) as dag:
    # [END instantiate_dag]
    # [START sampletask]
    sampletask = BashOperator(
        task_id='sampletask',
        bash_command='cat /bitnami/python/requirements.txt && sleep 100 && cat /bitnami/python/requirement.txt',
    )

    sampletask
```

### Are you using any custom parameters or values?

We have customized values.yaml
1. We are pull dags from a remote repository. It's working fine. The dags are reflected on the UI. running as expected.
2. custom smtp server to send email alerts on success/failure. This is also working .
3. enabled ldap to allow only the people in the organization to login to the ui.
4. added a volumeMounts in worker requirements.txt to install cutom packages using pip. This is working fine without any issues.
5. enabled ingress for UI.
6. Few other airflow configs . you can refer in the below attatched screenshot
<img width="607" alt="image" src="https://github.com/bitnami/charts/assets/88088284/9a73a60a-802b-4b18-b66c-0c2c5113542b">

### What is the expected behavior?

When the job/task fails,
1. Need to access the logs through UI if job fails. 
2. the kubernetes task pod should go to 'Error' state instead of 'Completed'

### What do you see instead?

1. Currently we get logs if the task is running or ran successully 
2. When the task fails the log section is empty.
3. Even if the task fails, the task pod status is updated to 'Completed'. 'Completed' status suggest that the job is successful. But when we check the pod logs, there is an error
<img width="1790" alt="image" src="https://github.com/bitnami/charts/assets/88088284/c25c0430-50f7-4930-b446-6f1f59fb0158">
<img width="1506" alt="image" src="https://github.com/bitnami/charts/assets/88088284/f7a992e8-2051-49db-9a7d-e3807823d0ca">

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami Airflow container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
