### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Requesting SCDF helm chart v2.11.0 release

### ISSUE THREAD

**Issue by younsl** [bitnami/charts#19446]
### Name and Version

[bitnami/spring-cloud-dataflow v2.11.0](https://github.com/bitnami/charts/tree/main/bitnami/spring-cloud-dataflow)

## Overview

Spring-cloud-dataflow `v2.11.0` has been released, the SCDF helm chart also requires a version upgrade from `v2.10.3` to `v2.11.0`.

### Request background

**Support for Spring Boot 3.x workloads**
My company's development team recently asked me for their requirements for a Spring Boot 3.x workload.
So I'm planing to upgrade SCDF from `v2.10.3` to `v2.11.0` using bitnami/spring-cloud-dataflow official chart.

These are some of the notable changes in the SCDF v2.11.0 release notes.

> **Support for Spring Boot 3.x** Workloads and support Spring Cloud Task 3.x and Spring Batch 5.x schemas. See [Spring Boot 3.x Support](https://docs.spring.io/spring-cloud-dataflow/docs/2.11.0-RC1/reference/htmlsingle/#appendix-boot3)

## References

[SCDF bitnami helm](https://bitnami.com/stack/spring-cloud-dataflow/helm)
[SCDF v2.11.0 release note](https://github.com/spring-cloud/spring-cloud-dataflow/releases/tag/v2.11.0)
[SCDF v2.11.0 docs - Getting started](https://docs.spring.io/spring-cloud-dataflow/docs/2.11.0/reference/htmlsingle/#getting-started)

### What is the feature you are proposing to solve the problem?

Request release of latest version of `spring-cloud-dataflow` Helm Chart

**Comment by javsalgar** [comment]
Hi!

Thank you so much for opening the ticket. The team is looking into it, you should expect the new version released soon.

**Comment by gayeon1025** [comment]
I am looking forward to SCDF helm chart v2.11.0 🥹

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by younsl** [comment]
Hello.
Thank you for sharing.

Instead of the bitnami/spring-cloud-dataflow image, I tried to quickly change it to the spring-cloud/spring-cloud-dataflow-server image for testing, but two errors occurred:

---

## Test environment

- **Platform** : EKS v1.24
- **SCDF**
  - **Installation method** : official helm chart provided by `bitnami/spring-cloud-dataflow`
  - **App Version** : v2.10.3

I deployed the springcloud/spring-cloud-dataflow-server image to my EKS Cluster.

```diff
  # values.yaml
  ...
  server:
   ## Bitnami Spring Cloud Dataflow Server image
   ## ref: https://hub.docker.com/r/bitnami/spring-cloud-dataflow/tags/
   ## @param server.image.registry Spring Cloud Dataflow image registry
   ## @param server.image.repository Spring Cloud Dataflow image repository
   ## @param server.image.tag Spring Cloud Dataflow image tag (immutable tags are recommended)
   ## @param server.image.digest Spring Cloud Dataflow image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
   ## @param server.image.pullPolicy Spring Cloud Dataflow image pull policy
   ## @param server.image.pullSecrets Specify docker-registry secret names as an array
   ## @param server.image.debug Enable image debug mode
   ##
   image:
     registry: docker.io
-    repository: bitnami/spring-cloud-dataflow
-    tag: 2.10.3-debian-11-r69
+    repository: springcloud/spring-cloud-dataflow-server
+    tag: 2.11.0
```

## Symptom

- Frontend issue (partially `.js` files 404 not found)
- Not found the External Database and only recognizing the In memory DB (H2)

## Conclusion

As a result, springcloud/spring-cloud-dataflow-server image does not work well.

---

**Comment by younsl** [comment]
Hello.

Recently, I checked that new SCDF v2.11.0 helm chart has been released from https://github.com/bitnami/charts/commit/b7076f80a24f4afa38fb40d5afc8658a9499e323
So I installed and operated SCDF v2.11.0 on my EKS v1.24 cluster, and it worked well.

Thanks a lot, bitnami team.

---

<details>
<summary>Hands dirty with SCDF v2.11.0</summary>

### Screenshot

Applications page for SCDF v2.11.0.

> Now I can see that `Spring Boot 3.x` has been added to the `Spring Boot version` parameter.

<img width="1700" alt="11" src="https://github.com/bitnami/charts/assets/87736192/58b8fa29-a559-4f38-8188-84fe1eef62aa">

&nbsp;

### Installation details

`spring-cloud-dataflow` helm(App version v2.11.0) deployed on EKS v1.24 cluster.

```bash
$ helm list --filter spring-cloud-dataflow
NAME                         	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                       	APP VERSION
spring-cloud-dataflow        	xxxxxxxx  	6       	2023-09-28 14:01:45.172444 +0900 KST	deployed	spring-cloud-dataflow-23.1.4	2.11.0
```

```bash
$ kubectl describe pod spring-cloud-dataflow-server-57575d5f4b-6jq7k
...
Containers:
  server:
    Container ID:   containerd://1fxxx0xx486192x67x122x5928x70xx4x60x613xxxxx3de0d12428fd63f18e54
    Image:          docker.io/bitnami/spring-cloud-dataflow:2.11.0-debian-11-r0
    ...
```

The SCDF Server pod also initializes well without any problems.

```bash
$ kubectl get pod -l app.kubernetes.io/instance=spring-cloud-dataflow
NAME                                            READY   STATUS    RESTARTS   AGE
spring-cloud-dataflow-server-57575d5f4b-6jq7k   1/1     Running   0          11h
```

When you enable flyway in your helm chart, Flyway will migrate DB schemas V6 to V9 newly.

```bash
# values.yaml
# spring-cloud-dataflow v2.11.0
...
flyway:
  enabled: true
...
```

Related flyway codes can be found [here](https://github.com/spring-cloud/spring-cloud-dataflow/tree/v2.11.0/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mysql).
</details>

---

FYI @gayeon1025

**Comment by carrodher** [comment]
Thanks for the update! As you rightly point out, the new version was released some hours ago at https://github.com/bitnami/charts/pull/19585.
