### ISSUE TITLE
[bitnami/ingress-nginx]Unable to create ingress main configmap

### ISSUE THREAD

**Issue by leecodeing** [bitnami/charts#19450]
### Name and Version

bitnami/ingress-nginx 1.8.2
CHART VERSION: 9.8.3
K8s v1.27.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Execute the command  `helm install warehouse oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller -n ingress-nginx`
Ingress main configmap was not created.
<img width="1168" alt="image" src="https://github.com/bitnami/charts/assets/54934375/cf8dd964-2879-409f-b01b-c4e516588a82">

### Are you using any custom parameters or values?

no

**Comment by jotamartos** [comment]
Hi @leecodeing,

I just tried to reproduce the issue but couldn't do so. I installed the latest version of the solution 

```
$ helm list
NAME                    	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART                         	APP VERSION
nginx-ingress-controller	default  	1       	2023-10-02 15:40:49.151201 +0200 CEST	deployed	nginx-ingress-controller-9.9.0	1.9.0
```

and the ConfigMap was properly generated 

```
$ k get cm
NAME                                       DATA   AGE
kube-root-ca.crt                           1      72d
nginx-ingress-controller-default-backend   1      4m41s

$ k get cm nginx-ingress-controller-default-backend -o yaml
apiVersion: v1
data:
  defaultBackend.conf: |-
    location /healthz {
      return 200;
    }

    location / {
      return 404;
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress-controller
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-10-02T13:40:49Z"
  labels:
    app.kubernetes.io/component: default-backend
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/version: 1.25.2
    helm.sh/chart: nginx-ingress-controller-9.9.0
  name: nginx-ingress-controller-default-backend
  namespace: default
  resourceVersion: "1051942"
  uid: 2d899829-da78-40e4-bffa-1d54383a4d54
```

Please review the permissions configuration of your cluster or try to deploy the solution in a different one.
