### ISSUE TITLE
[bitnami/cassandra] Can i deploy cassandra chart without password?

### ISSUE THREAD

**Issue by Avik1993** [bitnami/charts#1945]
**Which chart**:
bitname/cassandra

**Description**
I have created cassandra cluster using `forcePassword` as false but it stills requires password when connecting through cqlsh.
Also, I tried setting password using `dbUser.password` field but it throws `bad credentials` error with that password.

```Connection error: ('Unable to connect to any servers', {'IP': AuthenticationFailed('Failed to authenticate to IP: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"',)})```

**Describe the results you received:**
Facing Bad Credentials error

**Describe the results you expected:**
Cqlsh should be able to establish connection without password when `forcePassword` is false and with password when its true.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.0.2
```

- Output of `kubectl version`:

```
v1.14.8```

**Comment by miguelaeh** [comment]
Hi @Avik1993 ,
It is possible when you provided the password you forgot to delete the PVCs so the previous one was stored, try uninstalling the Chart, deleting the PVCs and then installing it again.

**Comment by Avik1993** [comment]
Hi @miguelaeh 
Thanks for the reply.
That indeed was the issue, doesn't uninstalling the chart takes care of deleting PVCs?

**Comment by miguelaeh** [comment]
No, when you uninstall the chart it doesn't remove the PVCs, I thought it would be implemented in Helm v3 but it seems it didn't.
