### ISSUE TITLE
[bitnami/kafka] sasl.enabledMechanisms does not overwrite metrics configuration when using the single line format but multi-line works

### ISSUE THREAD

**Issue by eli-gc** [bitnami/charts#19457]
### Name and Version

bitnami/kafka 25.1.10

### What architecture are you using?

None

### What steps will reproduce the bug?

Can run helm template with the values files described below and look at the rendered `kafka/templates/metrics/deployment.yaml ` for kafka-exporter

The multi-line configuration format will result in template.spec.containers.args section to have the correct sasl.mechanism. However, when using the single line format, sasl.mechanism will not be overwritten and still be the default `scram-sha512`

This behavior persists when using helm install and then `kubectl describe pod` or `kubectl describe replicaset`

### Are you using any custom parameters or values?

This will not overwrite the args:
```
sasl.enabledMechanisms: PLAIN
```

but this does:
```
sasl:
  enabledMechanisms: PLAIN
```

### What is the expected behavior?

Both should be valid yaml and should result in the same behavior. 

### What do you see instead?

If I specify: `sasl.enabledMechanisms: PLAIN` then I see:
```
    args:
            - -ce
            - |
              kafka_exporter \
              --kafka.server=test-release-kafka-controller-0.test-release-kafka-controller-headless.default.svc.cluster.local:9092 \
              --kafka.server=test-release-kafka-controller-1.test-release-kafka-controller-headless.default.svc.cluster.local:9092 \
              --kafka.server=test-release-kafka-controller-2.test-release-kafka-controller-headless.default.svc.cluster.local:9092 \
              --sasl.enabled \
              --sasl.username=$SASL_USERNAME \
              --sasl.password=$SASL_USER_PASSWORD \
              --sasl.mechanism=scram-sha512 \
              --web.listen-address=:9308
```

If I use the multi-line version, then I see the correct version:
```
args:
            - -ce
            - |
              kafka_exporter \
              --kafka.server=test-release-kafka-controller-0.test-release-kafka-controller-headless.default.svc.cluster.local:9092 \
              --kafka.server=test-release-kafka-controller-1.test-release-kafka-controller-headless.default.svc.cluster.local:9092 \
              --kafka.server=test-release-kafka-controller-2.test-release-kafka-controller-headless.default.svc.cluster.local:9092 \
              --sasl.enabled \
              --sasl.username=$SASL_USERNAME \
              --sasl.password=$SASL_USER_PASSWORD \
              --sasl.mechanism=plain \
              --web.listen-address=:9308

```

**Comment by jotamartos** [comment]
Hi @eli-gc,

Thank you for using our solution. If you want to edit a parameter in the chart, you need to follow the same syntax the default values.yaml file uses. In this case, you need to use these lines 

```
sasl:
  enabledMechanisms: PLAIN
```

This follows the [best practices in helm](https://helm.sh/docs/chart_best_practices/values/). 

You can also set that parameter in the command line 

```
helm template --set metrics.kafka.enabled=true --set sasl.enabledMechanisms=PLAIN kafka bitnami/kafka
```

I hope this helps

**Comment by eli-gc** [comment]
Thanks for clarifying. I thought I could use either syntax.
