### ISSUE TITLE
Outdated CRD (grafanadashboard) in bitnami/grafana-operator helm chart

### ISSUE THREAD

**Issue by lucatr** [bitnami/charts#19466]
### Name and Version

bitnami/grafana-operator 3.4.6

### What architecture are you using?

None

### What steps will reproduce the bug?

Install Grafana Operator with Bitnami Helm Chart results in outdated CRD for grafanadashboard.

### What is the expected behavior?

All values according to API documentation usable.

### What do you see instead?

CRD definition, at least for the grafanadashboard CRD, seems to be according to Grafana Operator Version 5.3: https://github.com/bitnami/charts/blame/cbabe4298f0c2a3b9e6564504b5aebd2a8a33ec6/bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml#L97

Looks like there are some updates in the meantime:
https://github.com/bitnami/charts/blob/73945fedfa2acff03fe172430fcc4b8bcf55282f/bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml#L97C2-L97C2

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
