### ISSUE TITLE
[bitnami/discourse] Upgrade of Discourse from image tag 3.0.6 to 3.1.1 is failing 

### ISSUE THREAD

**Issue by stevejr** [bitnami/charts#19461]
### Name and Version

bitnami/discourse:3.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install discourse using the Helm Chart v10.3.8 which will install image bitnami/discourse:3.0.6. Do not install any additional plugins.

Upgrade the helm release to the latest chart - v11.0.3 - which will install the image bitnami/discourse:3.1.1

The upgrade fails - the discourse container cannot perform the database migrations and is throwing an error.

### What is the expected behavior?

Discourse should upgrade from 3.0.6 to 3.1.1

### What do you see instead?

The below error is being thrown:

```
discourse 17:28:38.86 INFO  ==> Running database migrations
rake aborted!
NoMethodError: undefined method `register_bookmarkable' for Bookmark:Class
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/opt/bitnami/discourse/plugins/chat/plugin.rb:261:in `block (2 levels) in activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:1351:in `reloadable_patch'
/opt/bitnami/discourse/plugins/chat/plugin.rb:250:in `block in activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:526:in `block in notify_after_initialize'
/opt/bitnami/discourse/lib/plugin/instance.rb:524:in `each'
/opt/bitnami/discourse/lib/plugin/instance.rb:524:in `notify_after_initialize'
/opt/bitnami/discourse/config/application.rb:230:in `each'
/opt/bitnami/discourse/config/application.rb:230:in `block (2 levels) in <class:Application>'
/opt/bitnami/discourse/lib/plugin.rb:6:in `initialization_guard'
/opt/bitnami/discourse/config/application.rb:230:in `block in <class:Application>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/lazy_load_hooks.rb:75:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:32:in `run'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/application.rb:372:in `initialize!'
/opt/bitnami/discourse/config/environment.rb:7:in `<main>'
<internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/opt/bitnami/ruby/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.10/lib/zeitwerk/kernel.rb:38:in `require'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/application.rb:348:in `require_environment!'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/application.rb:506:in `block in run_tasks_blocks'
/opt/bitnami/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:25:in `load'
/opt/bitnami/ruby/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by stevejr** [comment]
Hi, just wondering if there were any initial findings?

**Comment by joancafom** [comment]
Hi @stevejr 

I was able to reproduce your issue, however this seems to me to be more related to the asset itself than to the actual `bitnami/chart` or container image. In fact, I could see there is a thread in the Discourse community over what you shared:

https://meta.discourse.org/t/upgrade-failed-nomethoderror-undefined-method-register-bookmarkable-for-bookmark-class/258761/2

I would encourage you to ask assistance there, as this seems to be on the application's logic side.

**Comment by stevejr** [comment]
Hi, is it possible to get more help from support here? 

The error I am seeing is from the Chat plugin which is now actually part of the Discourse core code base rather than being maintained as a separate plugin.

**Comment by stevejr** [comment]
Just a quick update, it seems that performing an upgrade from a pre-3.0.0 version allows the upgrade to work i.e 2.8.11 → 3.0.6 → 3.1.1

I am not sure if this is a pure accident or not but trying to upgrade from 3.0.6 straight to 3.1.1 does not work.

**Comment by joancafom** [comment]
Hi @stevejr 

I will create an internal task for review, but if this is on the application's side there is little we can do unfortunately 😢 

I reckon Discourse featured a Backup feature accesible via the UI. Another option would be to perform a backup and restore this data to a fresh, new instance (running the latest version). Hopefully that works just fine.

Could you please give this a try?

**Comment by stevejr** [comment]
Hi @joancafom, thanks for the above. I will give what you say a try and provide some feedback.

I also plan to test a standard Discourse install as per the Discourse guide with the different versions. If this upgrade flow works then we know it's not the Discourse application.

**Comment by stevejr** [comment]
Sorry, been on PTO so will test a backup and restore to latest version and see what happens.

**Comment by obeyler** [comment]
I've got the same issue.

**Comment by Cristy94** [comment]
This issue still occurs.

I am stuck on 3.0.6, if I try to update to 3.1.1 or 3.3.1 I get `uninitialized constant ChatMessageSerializer::BasicUserWithStatusSerializer ` error. I tried with the Chat plugin enabled or disabled, same error.

**Comment by Cristy94** [comment]
I fixed my upgrade problem by removing the **plugins/chat** folder before upgrading: https://softuts.com/bitnami-discourse-3-3-2-update-error/
