### ISSUE TITLE
Postgres Bitnami ImagePullSecret on Backup-CronJob

### ISSUE THREAD

**Issue by marcelmie** [bitnami/charts#19488]
### Name and Version

bitnami/postgresql 12.12.6

### What is the problem this feature will solve?

Currently it is not possible to set an ImagePullSecret for the backup cron job. If a private repository is used, it is not possible to provide the login data.

### What is the feature you are proposing to solve the problem?

Please add the option to set an ImagePullSecret. Similar to the StatefulSet

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by izphi78** [comment]
This is the same for PullPolicyPolicy.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
