### ISSUE TITLE
[bitnami/redis] Sentinel not responding with master connection

### ISSUE THREAD

**Issue by jtknights08** [bitnami/charts#19485]
### Name and Version

bitnami/redis 18.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Ubuntu LTS, microk8s --classic deployment with HostPath enabled, helm enabled add bitnami repo
2. `microk8s helm install redis -f values.yaml-n dev-system --create-namespace`
3. Ask for 'mymaster' using python redis library in a pod inside the cluster, here is the code we've used for years, Kubernetes/helm is the only thing new introduced, code was condensed for relevance and ease of reading:

```
import redis.sentinel

self.redis_password = 'password123'
self.database = 0
sentinel_host = 'redis.dev-system.svc.cluster.local'

self.sentinel = redis.sentinel.Sentinel(sentinels=[(sentinel_host, 26379)], socket_timeout=0.9)

while True:
  try:
    master = self.sentinel.master_for('mymaster', password=self.redis_password, health_check_interval=60, self.database=database)
       return master
    except Exception as e:
       print('error [{}] .. type [{}]'.format(e, type(e)))

```

### Are you using any custom parameters or values?

[values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml)  last update: #19468
```
global:
  auth:
    password: password123
sentinel:
  enabled: true
```

### What is the expected behavior?

Using python redis connector get the master connection returned.

### What do you see instead?

[2023-09-22 18:38:33,454] error [No master found for 'mymaster'] .. type [<class 'redis.sentinel.MasterNotFoundError'>]
[2023-09-22 18:38:33,458] error [No master found for 'mymaster'] .. type [<class 'redis.sentinel.MasterNotFoundError'>]
[2023-09-22 18:38:33,462] error [No master found for 'mymaster'] .. type [<class 'redis.sentinel.MasterNotFoundError'>]
[2023-09-22 18:38:33,466] error [No master found for 'mymaster'] .. type [<class 'redis.sentinel.MasterNotFoundError'>]
[2023-09-22 18:38:33,470] error [No master found for 'mymaster'] .. type [<class 'redis.sentinel.MasterNotFoundError'>]
[2023-09-22 18:38:33,474] error [No master found for 'mymaster'] .. type [<class 'redis.sentinel.MasterNotFoundError'>]

### Additional information

I modified this code and deployed master-replica, I had 0 issues connecting and using master.

I do not see logs or conf file inside the pods for redis/sentinel itself:

> I have no name!@redis-node-0:/var/log$ ls
> apt  dpkg.log
> I have no name!@redis-node-0:/var/log$ cd apt
> I have no name!@redis-node-0:/var/log/apt$ ls
> eipp.log.xz  history.log  term.log
> 
> I have no name!@redis-node-0:/bitnami/redis-sentinel$ cd conf
> I have no name!@redis-node-0:/bitnami/redis-sentinel/conf$ ls
> I have no name!@redis-node-0:/bitnami/redis-sentinel/conf$
> 
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel$ ls
> bin  etc  licenses  logs  mounted-etc  tmp
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel$ cd logs
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel/logs$ ls
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel/logs$ cd ..
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel$ cd tmp
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel/tmp$ ls
> I have no name!@redis-node-0:/opt/bitnami/redis-sentinel/tmp$

Redis Master logs (redis-0) by clicking pod/container logs in lens:

> 17:47:35.25 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 99 redis-cli -h redis.dev-system.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
> Could not connect to Redis at redis.dev-system.svc.cluster.local:26379: Connection refused
> Could not connect to Redis at redis.dev-system.svc.cluster.local:26379: Connection refused
>  17:47:37.34 INFO  ==> Configuring the node as master
> 1:C 22 Sep 2023 17:47:37.371 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 1:C 22 Sep 2023 17:47:37.371 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
> 1:C 22 Sep 2023 17:47:37.371 * Configuration loaded
> 1:M 22 Sep 2023 17:47:37.372 * monotonic clock: POSIX clock_gettime
> 1:M 22 Sep 2023 17:47:37.373 * Running mode=standalone, port=6379.
> 1:M 22 Sep 2023 17:47:37.374 * Server initialized
> 1:M 22 Sep 2023 17:47:37.377 * Creating AOF base file appendonly.aof.1.base.rdb on server start
> 1:M 22 Sep 2023 17:47:37.379 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
> 1:M 22 Sep 2023 17:47:37.379 * Ready to accept connections tcp
> 1:M 22 Sep 2023 17:48:02.717 * Replica redis-node-1.redis-headless.dev-system.svc.cluster.local:6379 asks for synchronization
> 1:M 22 Sep 2023 17:48:02.717 * Full resync requested by replica redis-node-1.redis-headless.dev-system.svc.cluster.local:6379
> 1:M 22 Sep 2023 17:48:02.717 * Replication backlog created, my new replication IDs are '87c6c766ca1691b1b4a7eaba59391bfad3124a39' and '0000000000000000000000000000000000000000'
> 1:M 22 Sep 2023 17:48:02.717 * Delay next BGSAVE for diskless SYNC
> 1:M 22 Sep 2023 17:48:07.693 * Starting BGSAVE for SYNC with target: replicas sockets
> 1:M 22 Sep 2023 17:48:07.694 * Background RDB transfer started by pid 100
> 100:C 22 Sep 2023 17:48:07.698 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
> 1:M 22 Sep 2023 17:48:07.698 * Diskless rdb transfer, done reading from pipe, 1 replicas still up.
> 1:M 22 Sep 2023 17:48:07.706 * Background RDB transfer terminated with success
> 1:M 22 Sep 2023 17:48:07.706 * Streamed RDB transfer with replica redis-node-1.redis-headless.dev-system.svc.cluster.local:6379 succeeded (socket). Waiting for REPLCONF ACK from replica to enable streaming
> 1:M 22 Sep 2023 17:48:07.706 * Synchronization with replica redis-node-1.redis-headless.dev-system.svc.cluster.local:6379 succeeded
> 1:M 22 Sep 2023 17:48:29.767 * Replica redis-node-2.redis-headless.dev-system.svc.cluster.local:6379 asks for synchronization
> 1:M 22 Sep 2023 17:48:29.767 * Full resync requested by replica redis-node-2.redis-headless.dev-system.svc.cluster.local:6379
> 1:M 22 Sep 2023 17:48:29.767 * Delay next BGSAVE for diskless SYNC
> 1:M 22 Sep 2023 17:48:34.978 * Starting BGSAVE for SYNC with target: replicas sockets
> 1:M 22 Sep 2023 17:48:34.979 * Background RDB transfer started by pid 228
> 228:C 22 Sep 2023 17:48:34.981 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
> 1:M 22 Sep 2023 17:48:34.981 * Diskless rdb transfer, done reading from pipe, 1 replicas still up.
> 1:M 22 Sep 2023 17:48:34.985 * Background RDB transfer terminated with success

Redis Sentinel logs (redis-0) by clicking pod/container logs in lens:

>  17:47:35.45 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 99 redis-cli -h redis.dev-system.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
> Could not connect to Redis at redis.dev-system.svc.cluster.local:26379: Connection refused
> Could not connect to Redis at redis.dev-system.svc.cluster.local:26379: Connection refused
> 1:X 22 Sep 2023 17:47:38.816 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 1:X 22 Sep 2023 17:47:38.816 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
> 1:X 22 Sep 2023 17:47:38.816 * Configuration loaded
> 1:X 22 Sep 2023 17:47:38.817 * monotonic clock: POSIX clock_gettime
> 1:X 22 Sep 2023 17:47:38.818 * Running mode=sentinel, port=26379.
> 1:X 22 Sep 2023 17:47:38.819 * Sentinel ID is 2a09ba7abbb41ee71e79087310d75f9809c3c815
> 1:X 22 Sep 2023 17:47:38.819 # +monitor master mymaster redis-node-0.redis-headless.dev-system.svc.cluster.local 6379 quorum 2
> 1:X 22 Sep 2023 17:48:05.069 * +sentinel sentinel 33535e4e17bf8f9f9ff9ce8f9ddf609e558ff4f2 redis-node-1.redis-headless.dev-system.svc.cluster.local 26379 @ mymaster redis-node-0.redis-headless.dev-system.svc.cluster.local 6379
> 1:X 22 Sep 2023 17:48:05.072 * Sentinel new configuration saved on disk
> 1:X 22 Sep 2023 17:48:08.923 * +slave slave redis-node-1.redis-headless.dev-system.svc.cluster.local:6379 redis-node-1.redis-headless.dev-system.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.dev-system.svc.cluster.local 6379
> 1:X 22 Sep 2023 17:48:08.927 * Sentinel new configuration saved on disk
> 1:X 22 Sep 2023 17:48:32.167 * +sentinel sentinel 9fe32540b27937ed9f341b0f610a0d8df405bb63 redis-node-2.redis-headless.dev-system.svc.cluster.local 26379 @ mymaster redis-node-0.redis-headless.dev-system.svc.cluster.local 6379
> 1:X 22 Sep 2023 17:48:32.171 * Sentinel new configuration saved on disk
> 1:X 22 Sep 2023 17:48:39.026 * +slave slave redis-node-2.redis-headless.dev-system.svc.cluster.local:6379 redis-node-2.redis-headless.dev-system.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.dev-system.svc.cluster.local 6379
> 1:X 22 Sep 2023 17:48:39.030 * Sentinel new configuration saved on disk

sentinel masters command, the 1) 1) caused weird issues so indented it once:

> I have no name!@redis-node-0:/$ redis-cli -p 26379
> 127.0.0.1:26379> auth password123
> OK
> 127.0.0.1:26379> sentinel masters
> 1)
>     1) "name"
>     2) "mymaster"
>     3) "ip"
>     4) "redis-node-0.redis-headless.dev-system.svc.cluster.local"
>     5) "port"
>     6) "6379"
>     7) "runid"
>     8) "3ebc804f48379da578ceff9a10db85272353fe40"
>     9) "flags"
>    10) "master"
>    11) "link-pending-commands"
>    12) "0"
>    13) "link-refcount"
>    14) "1"
>    15) "last-ping-sent"
>    16) "0"
>    17) "last-ok-ping-reply"
>    18) "447"
>    19) "last-ping-reply"
>    20) "446"
>    21) "down-after-milliseconds"
>    22) "60000"
>    23) "info-refresh"
>    24) "6654"
>    25) "role-reported"
>    26) "master"
>    27) "role-reported-time"
>    28) "4314425"
>    29) "config-epoch"
>    30) "0"
>    31) "num-slaves"
>    32) "2"
>    33) "num-other-sentinels"
>    34) "2"
>    35) "quorum"
>    36) "2"
>    37) "failover-timeout"
>    38) "180000"
>    39) "parallel-syncs"
>    40) "1"

Edit* Forgot to add the namespace info:

> microk8s kubectl get all --namespace dev-system

```
NAME               READY   STATUS    RESTARTS   AGE
pod/redis-node-1   2/2     Running   0          7h3m
pod/mysql-0        1/1     Running   0          3d
pod/redis-node-2   2/2     Running   0          7h3m
pod/redis-node-0   2/2     Running   0          7h4m
pod/rabbitmq-0     1/1     Running   0          3d

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
service/rabbitmq-headless   ClusterIP   None             <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   3d
service/rabbitmq            ClusterIP   10.152.183.45    <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   3d
service/mysql-headless      ClusterIP   None             <none>        3306/TCP                                3d
service/mysql               ClusterIP   10.152.183.80    <none>        3306/TCP                                3d
service/redis-headless      ClusterIP   None             <none>        6379/TCP,26379/TCP                      7h4m
service/redis               ClusterIP   10.152.183.211   <none>        6379/TCP,26379/TCP                      7h4m

NAME                          READY   AGE
statefulset.apps/rabbitmq     1/1     3d
statefulset.apps/mysql        1/1     3d
statefulset.apps/redis-node   3/3     7h4m
```

**Comment by juan131** [comment]
Hi @jtknights08 

I can confirm that installing the chart using your values in the namespace `dev-system`, Sentinel containers are properly resolving the master address, see the steps I followed:

```console
$ helm install redis oci://registry-1.docker.io/bitnamicharts/redis -f redis-sentinel.yaml -n dev-system
(...)
$ export REDIS_PASSWORD=$(kubectl get secret --namespace dev-system redis -o jsonpath="{.data.redis-password}" | base64 -d)
$ kubectl run --namespace dev-system redis-client --restart='Never' --env REDIS_PASSWORD=$REDIS_PASSWORD --image docker.io/bitnami/redis:7.2.1-debian-11-r0 --command -- sleep infinity
$ kubectl exec --namespace dev-system -it redis-client -- bash
I have no name!@redis-node-0:/$ REDISCLI_AUTH=$REDIS_PASSWORD redis-cli -h redis.dev-system.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
1) "redis-node-0.redis-headless.dev-system.svc.cluster.local"
2) "6379"
```

Could you please double-check this is properly working in the container you created for running your Python code?

**Comment by jtknights08** [comment]
@juan131 Thank you for the confirmation, with this info I figured out the redis python connection library was giving me the wrong error. In fact my issue was by default sentinel wants a password but our existing config used sentinel without a password.
