### ISSUE TITLE
Error for get chart

### ISSUE THREAD

**Issue by Test45o** [bitnami/charts#19480]
### Name and Version

bitnami/argo-cd

### What steps will reproduce the bug?

Hello

I have created a repository remote in artifactory he goes to ping this site: https://charts.bitnami.com/bitnami

![image](https://github.com/bitnami/charts/assets/129524210/07551bb5-66a1-469e-a5bb-6738e0eb92a3)

and I create a repository virtual in artifactory 
![image](https://github.com/bitnami/charts/assets/129524210/4e78e6be-8064-4d08-a7c4-e3e56faf48aa)

I added the repository remote in the virtual : 

![image](https://github.com/bitnami/charts/assets/129524210/05a8a2c4-2395-4f2d-8ad2-2f4d3d724cff)

after I have added the repository virtual in my environment helm I launch the update repo with this command:

`helm repo update` and when I install one chart with this command: `helm pull name_repo/name_chart` and I have errr

don't get the chart.

Information:
Artifactpry server 7.63.7
Version of helm: 3.9.0

Have you idea? 

Thanks in advance

### What do you see instead?

I have not found a name charted or 401 or others

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami ArgoCD Helm chart, but rather to how the application is being utilized or configured in your specific environment.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
