### ISSUE TITLE
Introduce memory limits to bitnami/cassandra

### ISSUE THREAD

**Issue by joshrosso** [bitnami/charts#1949]
**Which chart**:

`bitnami/cassandra:e85332f`

**Description**

The chart does not set [memory limits](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory). Today, the pods are deployed as [BestEffort](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-besteffort).

I'd like to propose memory limits are added to the helm chart and is exposed as a configurable parameter. This would ensure the pod is given appropriate resources based on the configuration and prevent unexpected startup and runtime failures due to inaccessible memory. For example: https://github.com/bitnami/charts/issues/1541.

Let me know if this is desirable, if so, I'll create a PR.

**Steps to reproduce the issue:**

1. Deploy the existing chart.

**Describe the results you received:**

1. No memory limit is set.

**Describe the results you expected:**

1. A memory limit to be set.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by juan131** [comment]
Hi @joshrosso 

That's desirable, but the chart already provides a way to define the requests/limits for Cassandra pods. Please take a look to the lines below:

- https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/statefulset.yaml#L63
- https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml#L64

You just need to use your custom **values.yaml** providing the values you desire for requests/limits using the `resources` parameter.

**Comment by joshrosso** [comment]
I missed this in the chart somehow. Thanks!
