### ISSUE TITLE
Document how to deploy an existing wiki using Bitnami's MediaWiki helm chart

### ISSUE THREAD

**Issue by hexmode** [bitnami/charts#19507]
### Name and Version

bitnami/mediawiki

### What is the problem this feature will solve?

I'm trying to upgrade a Bitnami MediaWiki helm chart with some minor customizations (extensions, etc) from MW 1.34 to MW 1.39.

I have a lot of experience doing this with vanilla MediaWiki, but I'm having trouble doing this with the Bitnami helm chart, even though I'm working with someone who is very experienced with k8s and helm.

### What is the feature you are proposing to solve the problem?

I'm sure this problem could easily be resolved if I could find a step-by-step guide for how to upgrade the chart.  I have a feeling that what I need already exists, but I'm not able to find it.

### What alternatives have you considered?

I've been working on this for a few weeks without success.  I'm able to deploy a new wiki using the helm chart, but upgrading from one version to the next isn't working.

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/charts/tree/main/bitnami/mediawiki#upgrading) you can find the upgrading instructions between the Helm chart major versions. For instructions about the application itself we recommend to consult the official documentation to see what changed between versions, for instance at https://www.mediawiki.org/wiki/Release_notes
