### ISSUE TITLE
[bitnami/redis-cluster] option to not set .spec.loadBalancerIP in redis-cluster/templates/svc-cluster-external-access.yaml or set via annotation

### ISSUE THREAD

**Issue by TheMeier** [bitnami/charts#19535]
### Name and Version

bitname/redis-cluster 9.0.5

### What is the problem this feature will solve?

Setting Service.spec.loadBalancerIP is deprecated (https://github.com/kubernetes/kubernetes/pull/107235). In some scenarios there are operators which target services and sets the IP for them in other scenarios the IP shall be set via an annotation (eg. `service.beta.kubernetes.io/azure-load-balancer-ipv4` or `metallb.universe.tf/loadBalancerIPs`)

### What is the feature you are proposing to solve the problem?

Remove setting .spec.loadBalancerIP and add an optional feature to inject the fixed IP using an annotation provided via helm values.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
