### ISSUE TITLE
tls-secrets.yaml will only set ca.crt for self-signed certs, value not wired in for provided certs (line 21/22)

### ISSUE THREAD

**Issue by rmwsix** [bitnami/charts#19554]
### Name and Version

bitnami/tomcat 10.1.13

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Provide tomcat.ingress.secrets.certificate and tomcat.ingress.secrets.key
2. Inspect generated secret and tls.key and tls.crt are present
3. Note there is no way to set ca.crt because the template never tries to set it on lines 21/22
4. Also note that the template does try to set it on line 42 when auto generating certs

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

tls.key, tls.crt, and ca.crt can all be specified

### What do you see instead?

ca.crt cannot be specified, only auto-generated

### Additional information

Insert this or similar at line 22:
```yaml
ca.crt: {{ .authority | b64enc }}
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
