### ISSUE TITLE
[bitnami/magento] Security settings to accessing storefront or Magento Admin

### ISSUE THREAD

**Issue by cortes-** [bitnami/charts#1955]
**Which chart**:

Magento 11.0.5

**Description**

We use the helm chart to deploy Magento to Kubernetes and need to enable the `web/secure/use_in_admin` settings so that it always defaults to `1`.
We didn't find a special parameter on the chart and when deploying Magento, the service starts with the following values:

```console
php TRACE [runProgram] Executing: /opt/bitnami/php/bin/php magento, setup: install, -v, --base-url, http://example.com/,--backend-frontname,admin,--db-host, mariadb: 3306, --db-name, bitnami_magento, --db-user, bn_magento, --db-password, <PASS>, --admin-firstname, FirstName, --admin-lastname, LastName , --admin-email, user@example.com, --admin-user, user, --admin-password, c5I0fzqVx1, --language, en_US, --currency, USD, --timezone, America / Los_Angeles, --use-secure, 1, --base-url-secure, https://example.com/,**--use-secure-admin,0**
```

**Describe the results you expected:**

It would be nice to have separate settings on the chart, allowing to adjust the parameters `web/secure/use_in_adminhtml` and `web/secure/use_in_frontend`

**Additional information you deem important (e.g. issue happens only occasionally):**

As a workaround I made a custom docker image in which a script is run from the `docker-entrypoint-init.d` directory

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by juan131** [comment]
Hi @cortes- 

This is something to be fixed in the Docker Image (https://github.com/bitnami/bitnami-docker-magento) instead of the Helm chart. Could you please create an issue at https://github.com/bitnami/bitnami-docker-magento/issues?

For your information, this is the piece of code that defines the "installation command" in the Magento Nami module (used in the image to initialize Magento):

```javascript
    const installationSettings = [
      '--base-url', appDomain,
      '--backend-frontname', $app.adminUri,
      '--db-host', `${databaseHandler.connection.host}:${databaseHandler.connection.port}`,
      '--db-name', databaseHandler.connection.name,
      '--db-user', databaseHandler.connection.user,
      '--db-password', databaseHandler.connection.password,
      '--admin-firstname', $app.firstName,
      '--admin-lastname', $app.lastName,
      '--admin-email', $app.email,
      '--admin-user', $app.username,
      '--admin-password', $app.password,
      '--language', 'en_US',
      '--currency', 'USD',
      '--timezone', 'America/Los_Angeles',
      '--use-secure', '1',
      '--base-url-secure', appSSLDomain,
      '--use-secure-admin', '0',
    ];
    $app.helpers.magentoCli('setup:install', webServerHandler, {args: installationSettings});
```

Therefore, it would be adding a parameter so the line below is not hardcode:

```
      '--use-secure-admin', '0',
```

**Comment by cortes-** [comment]
Hi @juan131 
Thanks for reply, I create an issue https://github.com/bitnami/bitnami-docker-magento/issues/129

**Comment by juan131** [comment]
Great @cortes- !!! Let's follow the conversation there!
