### ISSUE TITLE
[bitnami/minio] Minio chart needs new (secondary) metrics source

### ISSUE THREAD

**Issue by mateuszdrab** [bitnami/charts#19573]
### Name and Version

bitnami/minio

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The upstream project has been updated so that Minio exposes extra [prometheus endpoints](https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md)

The chart is currently designed to only handle the one (still valid) endpoint via a single [servicemonitor ](https://github.com/bitnami/charts/blob/main/bitnami/minio/templates/prometheusrule.yaml)which scrapes:

`/minio/v2/metrics/cluster`

The new endpoint is:

`/minio/v2/metrics/bucket`

Both need to be scraped

### What do you see instead?

Some bucket related metrics missing due to the chart not scraping the new `bucket` endpoint.

### Additional information

Happy to make the change but wanted to check how to do so from architectural point of view. 

Option one is to create a second servicemonitor
Option two is to add a second endpoint to the existing servicemonitor

Do we share servicemonitor values options for both or separate them?

**Comment by mateuszdrab** [comment]
This is still an issue with the chart.

**Comment by CeliaGMqrz** [comment]
Hi @mateuszdrab 

First, sorry for my late response. 

Thanks for reporting this issue. I see that this is a new feature. I have checked from upstream and I think the best approach here is the second option: create a second endpoint on the existing servicemonitor. 

If you would like to open a PR, the Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by mateuszdrab** [comment]
Hi @CeliaGMqrz 

Thanks for getting back to me.

The issue with adding a second endpoint is that the default endpoint looks like this `path: {{ .Values.metrics.serviceMonitor.path }}`

I am not sure at which level to separate the values for the new endpoint.

Should we have the below setup so that each endpoints can have some customization done via values?
.Values.metrics.serviceMonitor.bucket.x and .Values.metrics.serviceMonitor.cluster.x 
In the above, X is all the values options for serviceMonitor being moved under bucket and cluster.

Or, do we adopt a simpler setup with .Values.metrics.serviceMonitor.path being changed to .Values.metrics.serviceMonitor.bucketPath and .Values.metrics.serviceMonitor.clusterPath

**Comment by mateuszdrab** [comment]
This is still an issue.

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
