### ISSUE TITLE
mongodb-sharded NOTES.txt should specify a correct image for the client

### ISSUE THREAD

**Issue by jstudler** [bitnami/charts#1957]
**Which chart**: mongodb-sharded

**Description**
The kubectl run command in NOTES.txt should specify a correct image that takes global.imageRegistry into account. Similar to the way the [stable/redis chart does](https://github.com/helm/charts/blob/master/stable/redis/templates/NOTES.txt#L58).

**Steps to reproduce the issue:**

1. Install mongodb-sharded chart with custom global.imageRegistry
2. Try to install the client (Copy and paste the `kubectl run` command from the notes)
3. Pod will not run if the default docker registry is not reachable

**Describe the results you received:**

Client pod does not run

**Describe the results you expected:**

Client pod should run.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @jstudler, thanks for opening this issue. Would you like to create a PR to address it? Contributions are more than welcome!

**Comment by jstudler** [comment]
@andresbono sure: https://github.com/bitnami/charts/pull/1967

**Comment by andresbono** [comment]
Thanks again for your contribution!
