### ISSUE TITLE
Chart doesn't define the proper API Public URL

### ISSUE THREAD

**Issue by jsmueller7** [bitnami/charts#19583]
### Name and Version

bitnami/supabase 0.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The API URL isn't set properly when you don't use `kong.ingress.enabled`. The setting `global.publicURL` is ignored due to an obvious mistake in the `_helpers.tpl` file.

Here is the part in the `_helpers.tpl` that's buggy:

```
{{/*
Return the proper Supabase API Public URL
*/}}
{{- define "supabase.api.publicURL" -}}
{{- if .Values.publicURL -}}
{{- print .Values.publicURL -}}
```

Since there never is a value for `.Values.publicURL` this condition is never matched.

To fix please change from `.Values.publicURL` to `.Values.global.publicURL` 

### Are you using any custom parameters or values?

no

### What is the expected behavior?

`supabase.api.publicURL` should be set to the value of `.Values.global.publicURL` 

### What do you see instead?

> SUPABASE_PUBLIC_URL: "http://localhost:80"

### Additional information

I already provided the fix, so please get it done!

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
