### ISSUE TITLE
[bitnami/rabbitmq] per-object metrics

### ISSUE THREAD

**Issue by vanhoutenbos** [bitnami/charts#19586]
### Name and Version

bitnami/rabbitmq 12.1.7

### What is the problem this feature will solve?

Exposing the `per-object` metric endpoint to prometheus for scraping.
Currently we can only do this to change Prometheus but in my scenario I do not control Prometheus.

### What is the feature you are proposing to solve the problem?

It would be great to enable not just `/metrics` as exposed metric and scraped via `ServiceMonitor` but to also add `Per-object` scraping to that option.
More about this here; https://www.rabbitmq.com/prometheus.html#per-object-endpoint

### What alternatives have you considered?

Exposing within prometheus, but that is not an option for us.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by vanhoutenbos** [comment]
Hi!

Eventually I added an entry via the values file that also reached my goal;
`extraConfiguration: "prometheus.return_per_object_metrics = true"`

In the future it could be nice to add this as an option to the helmchart `return_per_object_metrics: boolean` but this worked for me :)
