### ISSUE TITLE
[bitnami/wordpress] Feature request: HyperDB support

### ISSUE THREAD

**Issue by cuttingsoup** [bitnami/charts#1963]
I'm trying to enable HyperDB support which requires creating two files:

- `/opt/bitnami/wordpress/db-config.php`
- `/opt/bitnami/wordpress/wp-content/db.php`

For `db-config.php` I have tried using a `ConfigMap` and mounting it but on startup the system tries to `chown` it which fails because the `ConfigMap` is mounted read only. I can create the file directly by `exec`ing into the pod, but if i use autoscaling the change won't be persisted on new pods.

`db.php` is on a ReadWriteMany PV which means it can be manually created, it would be nice to be able to do this as part of the chart installation though.

Not sure how this can be implemented, it might require changes to the bitnami docker image. I can move the request there if required.

**Comment by javsalgar** [comment]
Hi,

Our WordPress container has an init script feature that will launch any script mounted in the `/docker-entrypoint-init.d` folder.  We need to add support for it in the chart, but could you confirm that this would work for your case?

https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh

**Comment by cuttingsoup** [comment]
Almost, and it worked the first time which was confusing.

I mounted the two php files in /tmp and a script to copy them to the required locations.

The issue appears to be that since `/bitnami/wordpress/` is persistent, my script runs the first time, then runs `touch "/bitnami/$BITNAMI_APP_NAME/.user_scripts_initialized"`. Any pods that get created after the first one assume that the user scripts have already been executed and don't run them.

**Comment by javsalgar** [comment]
Hi,

I see. Maybe it makes sense to have a flag for forcing the execution of init scripts. Or to have a subset of initscripts that will always get executed.

**Comment by cuttingsoup** [comment]
Yeah I think the second option would be good and fairly easy to implement. Even a separate directory `/docker-entrypoint-init-always.d` or something along those lines for scripts that are always executed?

**Comment by javsalgar** [comment]
Great, so I will create a task for evaluating this scenario. It is not a critical feature so I cannot guarantee an ETA. However, I will update the ticket when we have more news.

**Comment by javsalgar** [comment]
Not stale

**Comment by marcosbc** [comment]
Hi, FYI we just released WordPress chart 11.0.0 with [major changes to the container image](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#1100), could you try it and let us know if it continues failing?
