### ISSUE TITLE
fix(postgresql-ha): `postgresql.database` vs `pgpool.srCheckDatabase`

### ISSUE THREAD

**Issue by jjangga0214** [bitnami/charts#19644]
### Name and Version

bitnami/postgresql-ha 11.9.8

### What is the problem this feature will solve?

Hi!

In postgresql-ha chart, there are `postgresql.database` and `pgpool.srCheckDatabase`.

The former's default value is empty while that of the latter is `"postgres"`. 

Shouldn't they be the same?
If it's that I understand wrong, please add more description so that I and others can know what's going on under the hood.

And here is my one more question.
When multiple arbitrary databases are in the same PostgreSQL instance(cluster), are they all Highly Available, which means HA is applied on the instance level, not the database level?

Thank you very much!

### What is the feature you are proposing to solve the problem?

Consistent values or more detailed description.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
