### ISSUE TITLE
fix(postgresql-ha): `persistence.resourcePolicy`

### ISSUE THREAD

**Issue by jjangga0214** [bitnami/charts#19645]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

arm64

### What steps will reproduce the bug?

The [README](https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha) is saying like this.

> Additionally, if `persistence.resourcePolicy` is set to "keep", you should manually delete the PVCs.

But it has no effect. In fact, the chart does not use the value.

Should it be removed from the docs, or does the chart support the value?

FYI, [harbor](https://github.com/goharbor/harbor-helm) uses `persistence.resourcePolicy` as well, and I like the convention by the way.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
