### ISSUE TITLE
[bitnami/moodle] Missing files after Moodle migration: Failed to open stream: No such file or directory in /bitnami/moodle/lib/filestorage/file_system.php on line 263

### ISSUE THREAD

**Issue by dominmana** [bitnami/charts#19667]
### Name and Version

bitnami/moodle 4.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Set up moodle in kubernetes for one domain (without certificate)
2. Change domain names and include a certificate
3. Restart pods
4. All the uploaded files are missing.

### What is the expected behavior?

The expected behavior is that after migration to a new domain everything works as it did on the old domain.

### What do you see instead?

On the new domain, all uploaded files are missing (file not found, 404).

### Additional information

The  only difference between the two instances is that the development version (original) did not have a Let's Encrypt certificate, while the production version (after migration) does have a Let's Encrypt certificate.

**Comment by dominmana** [comment]
I need to clarify: the first site has a Let's Encrypt Staging Certificate (https). The new site has a Let's Encrypt Production Certificate (https). Both use https.

**Comment by dominmana** [comment]
This could a problem with mount point set up, the [instructions](https://hub.docker.com/r/bitnami/moodle) for persistent volume once state that I should use 
```
--volume moodle_data:/bitnami/moodle \
```
and the all the way at the bottom, it says under "manual execution":
```
  --volume /path/to/moodle-persistence:/bitnami \
```
So if you start migrating bitnami moodle to a different domain and follow the instructions step-by-step, you might end up with all files gone and a weird folder structure.

**Comment by javsalgar** [comment]
Hi,

The instructions you are pointing are for `docker` installations, but I understood that you are using the Kubernetes helm chart. Could you clarify?

**Comment by dominmana** [comment]
Yes, kubernetes!

**Comment by javsalgar** [comment]
How did you include the certificate using the helm chart? We would like to easily reproduce in order to understand the issue.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the information. Would you like to submit a PR updating the the docs?

**Comment by dominmana** [comment]
I'm not really sure how to do that - I am not a proficient github user. I'd rather you guys handled that.

**Comment by rafariossaa** [comment]
Hi @dominmana ,
  If you check the docker-compose file, you could see there are [2 volumes being mounted](https://github.com/bitnami/containers/blob/ebc916e4094d145adaeadf9355b09a99135bc40c/bitnami/moodle/4.1/debian-11/docker-compose.yml#L30).
  In this case, I think it would be better to add to the documentation the two mounting points. What do you think ?

**Comment by dominmana** [comment]
I like this idea.

**Comment by rafariossaa** [comment]
In that case, would you like to contribute and send a PR ? We will be glad to review and merge it.

**Comment by dominmana** [comment]
> In that case, would you like to contribute and send a PR ? We will be glad to review and merge it.

As I mentioned above, I don't really know how to send PRs.

**Comment by rafariossaa** [comment]
Hi, 
 I have updated the README, I hope this helps.
