### ISSUE TITLE
Pod not running (bitnami/etcd)

### ISSUE THREAD

**Issue by nihadbakirli** [bitnami/charts#1966]
```
kubectl exec -it $POD_NAME -- etcdctl put /message Hello
{"level":"warn","ts":"2020-02-24T09:27:51.095Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-5a6c675c-327d-48a0-bb86-803d5af167e7/127.0.0.1:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
Error: etcdserver: user name is empty
command terminated with exit code 1
```
Actually from log everything seems good but pod not running just stayed 0/1

**Comment by miguelaeh** [comment]
Hi @nihadbakirli ,
That seems to not be an error, try passing the credentials to `etcdctl` :
```
etcdctl --user="youruser" --password="password" put /message Hello
```

**Comment by nihadbakirli** [comment]
> etcdctl --user="youruser" --password="password" put /message Hello

{"level":"warn","ts":"2020-02-24T10:46:26.049Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c717b6d3-9e70-4387-bb4c-ae0c67a029b8/127.0.0.1:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: authentication failed, invalid user ID or password"}
Error: etcdserver: authentication failed, invalid user ID or password
i enable rbac auth and set root pass on value.yaml and after install command etcd-0 pod not running

**Comment by nihadbakirli** [comment]
i installed last week etcd with success but today i tried again but pod not be up. Actually everythink seems good but pod not running

**Comment by miguelaeh** [comment]
Hi @nihadbakirli ,
Did you change the user and password in the command I posted to your credentials?
Also, could you share how did you deploy the Helm Chart?

**Comment by nihadbakirli** [comment]
helm install etcd bitnami/etcd

**Comment by carrodher** [comment]
Hi, as RBAC is enabled you should add the flag `--user root:$ETCD_ROOT_PASSWORD` to the `etcdctl` commands. You can obtain the password from the secret by running:
```bash
▶ export ETCD_ROOT_PASSWORD=$(kubectl get secret --namespace default etcd -o jsonpath="{.data.etcd-root-password}" | base64 --decode)
```

I just installed it using
```bash
▶ helm install etcd bitnami/etcd
```
and check if the deployment is running properly:
```bash
▶ kubectl get pods
NAME     READY   STATUS    RESTARTS   AGE
etcd-0   1/1     Running   0          4m27s
```

Executing the `etcdctl` command without the `--user` option I obtain the same issue:
```bash
▶ kubectl exec -it $POD_NAME -- etcdctl put /message Hello
{"level":"warn","ts":"2020-02-28T13:06:38.526Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-ad7285ab-d23a-48c4-9838-f2c922d1f986/127.0.0.1:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
Error: etcdserver: user name is empty
command terminated with exit code 1
```

Using the proper option for the user (root) and password (randomly generated), everything work as expected:
```bash
▶ export ETCD_ROOT_PASSWORD=$(kubectl get secret --namespace default etcd -o jsonpath="{.data.etcd-root-password}" | base64 --decode)

▶ echo $ETCD_ROOT_PASSWORD
xbPzRtYz4Z

▶ kubectl exec -it $POD_NAME -- etcdctl --user root:$ETCD_ROOT_PASSWORD put /message Hello
OK

▶ kubectl exec -it $POD_NAME -- etcdctl --user root:$ETCD_ROOT_PASSWORD get /message
/message
Hello
```

**Comment by jonasspenger** [comment]
I had the same issues (ready stays on 0/1), but it works for me when setting the chart version to 4.5.0 (and not 4.5.1).
`helm install etcd bitnami/etcd --version 4.5.0`

**Comment by carrodher** [comment]
> I had the same issues (ready stays on 0/1), but it works for me when setting the chart version to 4.5.0 (and not 4.5.1).
> `helm install etcd bitnami/etcd --version 4.5.0`

Are you able to see the same errors in the log? I mean, just to determine if the issue is the same or not, maybe the pods are not running due to a different reason

**Comment by jonasspenger** [comment]
> > I had the same issues (ready stays on 0/1), but it works for me when setting the chart version to 4.5.0 (and not 4.5.1).
> > `helm install etcd bitnami/etcd --version 4.5.0`
> 
> Are you able to see the same errors in the log? I mean, just to determine if the issue is the same or not, maybe the pods are not running due to a different reason

My mistake, it works now on both versions 4.5.0 and 4.5.1.
