### ISSUE TITLE
[bitnami/redis] Add `persistentVolumeClaimRetentionPolicy` support for Redis statefulset 

### ISSUE THREAD

**Issue by Krisztian-Molnar** [bitnami/charts#19683]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

Make use of `persistentVolumeClaimRetentionPolicy` to Delete or Retain the PVCs/PVs whenever the statefulset gets deleted or scaled down.

### What is the feature you are proposing to solve the problem?

Enable helm values to support `persistentVolumeClaimRetentionPolicy` and pass it to the templates as needed.

### What alternatives have you considered?

Similarly to Redis-cluster, we would also need this feature ([PR](https://github.com/bitnami/charts/commit/e5ac69de7323048732c47928702e8eb243eff8ef)) in regular Redis as well, not only in Redis-cluster.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Krisztian-Molnar** [comment]
Sure, created PR: #19689

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by Krisztian-Molnar** [comment]
@carrodher Pipeline fails during the _VIB Verify_ job / _Verify redis_ step, but I don't see mistakes in my code, could you please help me understand the reason?
