### ISSUE TITLE
Bitnami helm chart issue in vmware Tanzu TCA

### ISSUE THREAD

**Issue by rohit-swc** [bitnami/charts#19690]
### Name and Version

Bitnami/redis 16.13.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Vmware Tanzu

Grant validation error in TCA (orchestrator)

Logs:

"Service\cn-redis-master: Invalid port: null: must be between 1 and 65535, inclusive"
 

### Are you using any custom parameters or values?

No, using bitnami charts only for redis

### What is the expected behavior?

It should not throw this validation error.

**Comment by carrodher** [comment]
Could you please provide more info about how are you deploying this Helm chart? Are you modifying the default values (modifying the _values.yaml_ file or passing them with `--set`)?

**Comment by rohit-swc** [comment]
In helm deploynent, I am using a custom values yaml but not modifying master>service.yaml of bitnami charts. 


In this case if we ignore validation check then deployment goes well. Only problem is chart validation error in vmware TCA

**Comment by carrodher** [comment]
This seems to be a unique use case that might be challenging to replicate on our end (as it appears closely tied to your particular scenario) without the proper instructions and configuration. Could you please provide the values and the command used to deploy the Helm chart so we can try to reproduce the issue?
