### ISSUE TITLE
bitnami/cassandra How to pass config information to jmx exporter?

### ISSUE THREAD

**Issue by theirishmole** [bitnami/charts#1971]
**Which chart**:
bitnami/cassandra 5.0.2

**Description**
Within this helm script there is the option to enabled the jmx-exporter by toggling:
metrics:
  enabled: false
to:
metrics:
  enabled: true

There is no information however how configuration can be passed to the JMX exporter container as part of the helm script. 
Ie i want to use Grafana dash board and JMX exporter config outlined [here](https://github.com/oleg-glushak/cassandra-prometheus-jmx).

Can this be done through the helm script at all?
If not what is the suggested config option?
Any help appreciated.

**Comment by juan131** [comment]
Hi @theirishmole 

If you check the [statefulset manifest](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/statefulset.yaml) (lines **208-228**), you'll see that at this very moment we don't support adding any configuration option nor configuration file. 

Therfore, the [Cassandra Exporter image](https://github.com/bitnami/bitnami-docker-cassandra-exporter) is started with a default configuration file. You can find this image definition at [this link](https://github.com/bitnami/bitnami-docker-cassandra-exporter) where you'll find out the image is started using the command below:

```Dockerfile
ENTRYPOINT [ "java", "-jar", "./cassandra_exporter.jar", "./config.yml" ]
```

You can check that content of the default configuration file running:

```console
$ docker run -it --rm --entrypoint "/bin/bash" bitnami/cassandra-exporter
I have no name!@...:/opt/bitnami/cassandra-exporter$ cat config.yml
```

**Comment by theirishmole** [comment]
Hi.
I have found the Grafana dashboard i was trying to use uses JMX exporter, while the bitnami image provides Cassandra Exporter as you noted above.

I have found two other dashboards [1](https://grafana.com/grafana/dashboards/6258) [2](https://grafana.com/grafana/dashboards/10849) which do work with the default Cassandra Exporter config.

So for now I am fine with using the default config.
