### ISSUE TITLE
[bitnami/elasticsearch] enterprise search

### ISSUE THREAD

**Issue by sreenilearn** [bitnami/charts#19756]
### Name and Version

bitnami/elasticsearch:19.5.9

### What is the problem this feature will solve?

Is there any equivalent version of the following chart in bitnami? 
[docker.elastic.co/enterprise-search/enterprise-search:8.10](http://docker.elastic.co/enterprise-search/enterprise-search:8.10)

### What is the feature you are proposing to solve the problem?

elastic enterprise search chart

### What alternatives have you considered?

docker.elastic.co/enterprise-search/enterprise-search:8.10

**Comment by javsalgar** [comment]
Hi,

We cannot redistribute the commercial parts of the Elasticsearch solution, only the open-source parts.

**Comment by sreenilearn** [comment]
Got it, thank you!
