### ISSUE TITLE
How to enable ACL System?

### ISSUE THREAD

**Issue by jiangyongbing24** [bitnami/charts#1976]
**Which chart**:

consul

**Description**

I want to enable consul acl verification. How do I set it through configmap?

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by juan131** [comment]
Hi @jiangyongbing24 

You can use the `configmap` parameter (see https://github.com/bitnami/charts/blob/master/bitnami/consul/values.yaml#L105) to specify the whole configuration you want to use on Consul. This will create a configmap with your custom configuration.

Alternatively, add a piece of configuration to the default one using the `localConfig` parameter (see https://github.com/bitnami/charts/blob/master/bitnami/consul/values.yaml#L128)

**Comment by Andrioshe** [comment]
Hello @juan131,
I am actually trying to create a consul cluster with enabled acl but I am hard stuck at enabling the acl via localConfig.. can you give me en example please?

**Comment by juan131** [comment]
Hi @Andrioshe 

You can find great tutorials about how tho enable ACL rules on Consul on Hashicorp docs site:

- https://www.consul.io/docs/security/acl/acl-rules
- https://learn.hashicorp.com/tutorials/consul/access-control-setup-production?in=consul/security-networking

**Comment by dbhat6** [comment]
Hello @juan131 
I don't see much examples on how to use localConfig. Can you please point me to where I can find some of it, please?

**Comment by juan131** [comment]
Hi @dbhat6 

Do you mean how to use the `localConfig` parameter? There's an example how to use it in the **values.yaml**, see:

- https://github.com/bitnami/charts/blob/master/bitnami/consul/values.yaml#L106

**Comment by canyildiz** [comment]
> Hi @jiangyongbing24
> 
> You can use the `configmap` parameter (see https://github.com/bitnami/charts/blob/master/bitnami/consul/values.yaml#L105) to specify the whole configuration you want to use on Consul. This will create a configmap with your custom configuration.
> 
> Alternatively, add a piece of configuration to the default one using the `localConfig` parameter (see https://github.com/bitnami/charts/blob/master/bitnami/consul/values.yaml#L128)

Those links are referencing false lines now because `master` branch updated in this while. To see the correct code at the time this comment written by @juan131 please use following links instead:

`configmap`: https://github.com/bitnami/charts/blob/ae2ac1382a94a38683abd1448d93cc62f177c27e/bitnami/consul/values.yaml#L105

`localConfig`: https://github.com/bitnami/charts/blob/ae2ac1382a94a38683abd1448d93cc62f177c27e/bitnami/consul/values.yaml#L128
