### ISSUE TITLE
Add configs from secrets in redis-cluster

### ISSUE THREAD

**Issue by Exobitt** [bitnami/charts#19768]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

That you could add users with passwords from secrets, without adding them as cleartext in the field: redis.configmap

### What is the feature you are proposing to solve the problem?

That it takes one or more secrets into account, reads the secrets and adds them to the config

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
