### ISSUE TITLE
[bitnami/elasticsearch] spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

### ISSUE THREAD

**Issue by fabio-s-franco** [bitnami/charts#19763]
### Name and Version

bitnami/elasticsearch 19.13.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart (default values is sufficient)
2. Update the chart with any new value for commonAnnotations parameters. Example:
`--set commonAnnotations.app=elastic`

### What is the expected behavior?

Deployment/StatefulSet is updated with new annotations applied to all pods/services.

### What do you see instead?

> cannot patch "elastic-elasticsearch-data" with kind StatefulSet: StatefulSet.apps "elastic-elasticsearch-data" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden && cannot patch "elastic-elasticsearch-master" with kind StatefulSet: StatefulSet.apps "elastic-elasticsearch-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

### Additional information

The chart tries to update the statefulset annotations and those are not allowed by kubernetes (a new statefulset needs to be created to be able to do that).

I am not sure if there are any practical uses of annotations on statefulset resources, in addition to the pods and services, so I propose the chart gets updated to not apply annotation to statefulset / deployments, but rather only on their respective spec templates.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the suggestion. I also don't recall any specific use cases for annotations in statefulset objects (probably in some operators). However, I do not believe that is enough reason to justify removing it. To workaround the issue you are having, did you try using the specific `annotation` fields for the objects?

**Comment by fabio-s-franco** [comment]
> Hi,
> 
> Thank you so much for the suggestion. I also don't recall any specific use cases for annotations in statefulset objects (probably in some operators). However, I do not believe that is enough reason to justify removing it. To workaround the issue you are having, did you try using the specific `annotation` fields for the objects?

Yes, I had to resort to that for all node types (data, master, and coordinating nodes) separatelly

**Comment by fabio-s-franco** [comment]
I do think though, the main problem with this is not the possibility to work around the issue, but instead the disruption it may cause. Some people may have a much harder time diagnosing and understanding the issue and it can be counter-intuitive to determine what change is causing it. This is definitely more of an UX improvement rather than criticality of a bug.

**Comment by javsalgar** [comment]
Before going to a potentially breaking change, I'd love to know the thoughts of the community on the value of annotations/labels in statefulset/deployment objects. It would be weird to have a commonAnnotations with exceptions after all this time having a consistent approach (putting aside the pain that is updating statefulsets because of the forbidden fields)
