### ISSUE TITLE
[bitnami/postgresql-ha] password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#19771]
### Name and Version

bitnami/postgresql-ha:11.9.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the helm chart in a Kubernetes cluster (PVs/PVCs were deleted like was suggested on other threads)
2. Log in to any postgres node and execute "psql -U postgres" and type the password from the config

### Are you using any custom parameters or values?

```yaml
global:
  postgresql:
    password: postgres
    repmgrPassword: postgres
```

### What is the expected behavior?

Login with success

### What do you see instead?
```
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
```
### Additional information

I aim to use postgresql-ha as a data store for the Grafana HA setup.

**Comment by carrodher** [comment]
Are you deploying the Helm chart from scratch or upgrading an existing deployment? Please note reinstalling/upgrading the Helm chart without taking into account the previous password can produce a mismatch between the new password (specified in values or randomly generated) and the one already stored in the PVC from the previous deployment.

**Comment by alita1991** [comment]
I did a scratch install of the helm chart, with all PVCs deleted, I spent more time on this and found a way to make it work, with the following config:

```
global:
  postgresql:
    database: grafana
    password: postgres
    repmgrPassword: postgres
    image:
      debug: true
  pgpool:
    adminPassword: postgres
```

When I tested without setting the _pgpool.adminPassword_, I was not able to connect, could you please explain what is the role of adminPassword for pgpool? My expectation was that I should always use _postgresql.password,_ whenever I try to connect to the database (localhost when executing commands inside of the pg-0, 1 or 2 container or service pgpool)

**Comment by CeliaGMqrz** [comment]
Hi, @alita1991 

Sorry for my late response. 

I have not been able to reproduce the error.

The `adminPassword` is required if the _postgresql-ha.pgpoolSecretName_ secret does not exist, see: [notes](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/NOTES.txt#L94-L98). With default values the chart should create it. Could you make sure this? Run `kubectl get secrets`. When setting parameters manually, ensure a custom secret exists, or set the adminPassword if it doesn't.

Anyway, do you use any values in addition to those specified in the global section?
