### ISSUE TITLE
Bitnami Airflow UI username and password

### ISSUE THREAD

**Issue by rgarg2006** [bitnami/charts#1979]
1.  I was able to deploy Airflow on IBM Kubernetes Service (IKS) cluster but
am not able to login to Airflow UI with user/bitnami credentials.
Even I tried setting username and password in parameters and applying plan
but that does not seem working.

Can you please suggest default Airflow username & password, and way to
setup/reset UI username and password on IKS setup. Thanks.

2. Also can you please suggest need and architecture for Airflow multi-tenant deployment on IKS?

**Comment by beltran-rubo** [comment]
Hi,

The default user is "user" as it is specified in the parameters of the Chart. The password is randomly generated if you did not specify one. You can follow the process to get that password that is shown after the deployment. Check the IBM get started guide to know how to get that password at https://docs.bitnami.com/kubernetes/get-started-charts-iks/#step-2-provide-an-external-host-for-your-application

**Comment by beltran-rubo** [comment]
Related to multi-tenant configuration, are you looking to configure Airflow using this option? https://airflow.apache.org/docs/stable/security.html#multi-tenancy The configuration file is located at "/opt/bitnami/airflow/airflow.cfg" into the Airflow container with the option `filter_by_owner=False`. 

It is possible to create a configMap with the full configuration that you prefer for Airflow and specify that value into the "airflow.configurationConfigMap" option.
