### ISSUE TITLE
nginx-ingress-controller - 1.9.1 Docker Tag Release

### ISSUE THREAD

**Issue by surgiie** [bitnami/charts#19798]
### Name and Version

bitnami/nginx-ingress-controller 1.9.0

### What is the problem this feature will solve?

I am currently impacted by the following bug: 

https://github.com/kubernetes/ingress-nginx/issues/10462

Which has been claimed to be fixed and available in 1.9.1 release https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.9.1 if im reading this correctly. 

Im not familiar with the release cycle of the chart's docker images but when would I expect to see a bitnami tag for 1.9.1 as im currently using the default tag as specified in the chart's values.yaml: 

https://github.com/bitnami/charts/blob/main/bitnami/nginx-ingress-controller/values.yaml#L61C8-L61C26

### What is the feature you are proposing to solve the problem?

Fix for bug described here: https://github.com/kubernetes/ingress-nginx/issues/10462

### What alternatives have you considered?

Alternative chart or package for managing nginx-ingress-controller in my cluster which is undesirable.

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.
