### ISSUE TITLE
[bitnami/keycloak] Network Policy

### ISSUE THREAD

**Issue by Davidffry** [bitnami/charts#19811]
### Name and Version

bitnami/keycloak =< 17.0.0

### What is the problem this feature will solve?

Network policy.

In fact the management of network policy is focus on Ingress **but** when the we need also manage the Egress (legitimate flow) we can not do that on this network policy.

### What is the feature you are proposing to solve the problem?

Add in network policy template manage ingress and egress

### What alternatives have you considered?

Create another egress network policy manually whereas the ingress network policy already exist.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
