### ISSUE TITLE
[bitnami/keycloak] Minor documentation issue 

### ISSUE THREAD

**Issue by taladar** [bitnami/charts#19819]
### Name and Version

bitnami/keycloak 17.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Read documentation at

https://artifacthub.io/packages/helm/bitnami/keycloak

```
keycloakConfigCli.configuration | keycloak-config-cli realms configuration | {}
keycloakConfigCli.existingConfigmap | ConfigMap with keycloak-config-cli configuration. This will override keycloakConfigCli.config | ""
```

I believe the note about overriding should refer to keycloakConfigCli.configuration since keycloakConfigCli.config does not seem to exist.

### What is the expected behavior?

Documentation refers to existing parameters.

### What do you see instead?

Documentation refers to a parameter that does not seem to exist but a similarly named one exists.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for spotting the issue. Would you like to submit a PR to the bitnami/keycloak/README.md file?

**Comment by taladar** [comment]
I would prefer if someone with commit access could just add the missing "uration" bit without me having to clone the repository and making a PR just for those 7 characters if that is alright.
