### ISSUE TITLE
[bitnami/milvus] milvus-proxy always pop up error when helm re-install milvus even milvus server username & password not changed

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#19839]
### Name and Version

bitnami/milvus:3.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

1. set milvus auth in override value file
2. helm install milvus with the override value file
3. helm uninstall milvus
4. helm install milvus with the same override value file

### Are you using any custom parameters or values?

![image](https://github.com/bitnami/charts/assets/45187622/cdd0c1f0-39c3-40bb-8f11-8ddf81d03105)

### What is the expected behavior?

no issues about the milvus username & password

### What do you see instead?

1. milvus-proxy can up nornamlly, but keeps printing error log
![image](https://github.com/bitnami/charts/assets/45187622/87178b62-f525-404c-96a9-2fbb70fc6c2a)
2. milvus-init keep printing error, sometimes crashed and restart:
![image](https://github.com/bitnami/charts/assets/45187622/f9f6bc24-53e5-4c07-92da-cb5b1c96540e)
3. milvus-attu, can use old credential `root:p@ssw0rd` to login milvus ui successfully.

### Additional information

default username & password not changed, services seems can normally work, but milvus-proxy, milvus-init keep print error logs

**Comment by chenraoCR** [comment]
> Hello @chenraoCR, could you try cleaning any dangling pods and PVCs after a chart uninstallation?
> 
> ```
> $ kubectl get pods
> NAME                              READY   STATUS      RESTARTS   AGE
> milvus-minio-provisioning-84mmh   0/1     Completed   0          14m
> $ kubectl delete pod milvus-minio-provisioning-84mmh
> $ kubectl get pvc
> NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> data-milvus-etcd-0               Bound    pvc-7c240d17-e6b8-45ec-8398-734246c1d00b   8Gi        RWO            hostpath       13m
> data-milvus-etcd-1               Bound    pvc-a499404b-a9c3-458f-9f3a-3a6c5f2bf148   8Gi        RWO            hostpath       13m
> data-milvus-etcd-2               Bound    pvc-0cfd0757-c0ee-4b68-b94a-b575f536b657   8Gi        RWO            hostpath       13m
> data-milvus-kafka-controller-0   Bound    pvc-6dcf5df5-94a6-4364-8ade-40ff38b046c5   8Gi        RWO            hostpath       13m
> $ kubectl delete pvc ...
> ```
> 
> If that doesn't work, please try installing the chart in a non-default namespace. That way, you can delete de namespace once uninstalled and recreate it if you want the chart installed again.

in fact, when uninstall a chart, and then deploy a new version chart, usually we want to keep the data, data is important, so PVCs cannot be deleted,

**Comment by FraPazGal** [comment]
I think I misunderstood you @chenraoCR, I supposed you wanted a fresh installation as you were uninstalling the chart altogether before installing a new version. If you are doing the reinstall to upgrade your chart to a newer version you can just use the command `helm upgrade chartname bitnami/milvus`, which will automatically spin up the pods of the new chart version before spinning down the outdated ones.

In case you need to uninstall the chart for some other reason, be aware that once you enable milvus' auth with `milvus.auth.enabled=true` you are actually using 2 users; `root` and `user`. This second user is configured with the following params:

```
    ## @param milvus.auth.username Milvus username
    ##
    username: user
    ## @param milvus.auth.password Milvus username password
    ##
    password: ""
```

By default, the chart will generate a random password for `milvus.auth.password` if you don't specify one. If you have a chart already installed, you can check it by running:

```
$ echo Password: $(kubectl get secret --namespace default milvus -o jsonpath="{.data.password}" | base64 -d)
```

Could you try following your workflow taking this into account? You can manually set the password from the start or retrieve the randomly generated one before uninstalling and re-installing the chart (using the retrieved pass as `milvus.auth.password`).

**Comment by chenraoCR** [comment]
@FraPazGal hello, in fact, what you suggested maybe not work for my case, and i found the root cause for this:
1. first clean install milvus, in init-job.yaml
![image](https://github.com/bitnami/charts/assets/45187622/76de2dfd-12b3-4d82-a08f-56289982f0c2)
it will use default root:Milvus to connect milvus, then will update user `root` with the config milvus.auth.rootPassword
2. when re-install milvus or upgrade milvus, it still use old root:Milvus to connect milvus, but in fact, user `root` password already reset, so cannot connect milvus, then init-job will throw errors

solutions:
1. add a new filed `milvus.auth.rootOldPassword` in values.yaml
2. replace hardcoded root password `Milvus` with `milvus.auth.rootOldPassword`

so what do you think

**Comment by FraPazGal** [comment]
I understand what you mean @chenraoCR. Given the init-job logic, issues will pop-up when re-installing the chart using the same PVCs. That said, this error wouldn't appear in a `helm upgrade` as the job will only be created when:

https://github.com/bitnami/charts/blob/4184a643d0f39a63f892e84c5328870a5d1d91f0/bitnami/milvus/templates/_helpers.tpl#L1030

That said, I agree this in an issue in an install scenario using an existing PVC. Looking at your suggested solution and the job creation logic, is there actually a need to run the job in a re-install? Could we do something similar to `initJob.forceRun` and add a parameter such as `initJob.skipRun`? wydt?

**Comment by chenraoCR** [comment]
@FraPazGal agreed with what u suggested, but `initJob.forceRun` and `initJob.skip` exist at same time, sounds a little strange. And before i also wanted to skip the init-job for re-install or upgrading milvus, but there is a scenario
1.first clean install, with run init-job setting user `root` a new password different from old `Milvus`
2.one day for upgrading milvus, want to change user `root` old password after step 1, cannot
for this case, cannot handle

**Comment by FraPazGal** [comment]
Hello @chenraoCR, if we modify `initJob.forceRun` we'll need to be careful of maintaining backward compatibility so I wouldn't unless necessary.

Would you like to work on a PR for this fix? The team would be happy to review your contribution and offer any suggestions on the implementation. I can also open an internal for the development team to address this, though I couldn't give you an ETA on it.

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
