### ISSUE TITLE
[bitnami/postgresql] Add `pg_hashids`

### ISSUE THREAD

**Issue by andreaaizza** [bitnami/charts#19832]
### Name and Version

bitnami/postgresql 16.0.0

### What is the problem this feature will solve?

Missing pg_hashids extension

### What is the feature you are proposing to solve the problem?

add pg_hashids extension

### What alternatives have you considered?

create a custom image

**Comment by javsalgar** [comment]
Hi,

Adding new extensions have the risk of increasing the container size and increasing the attack surface. Unless there's a clear demand from the community, we try to be conservative with the extensions we add. Our recommendation would be to create a fork with the extension.

**Comment by andreaaizza** [comment]
Hi, clear thanks. Any doc describing how to contribute and create a custom
image safely?
Andrea

**Comment by javsalgar** [comment]
Hi,

This should help https://github.com/bitnami/charts/issues/10814#issuecomment-1162849912
