### ISSUE TITLE
Bitnami/cassandra how to connect cassandra outside the cluster?

### ISSUE THREAD

**Issue by Ashwitha01** [bitnami/charts#1983]
when trying out the command to connect the Cassandra outside the cluster, I'm getting connection error saying " Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")} . I have followed all the steps provided in the Notes section. Plz, help me.

**Comment by miguelaeh** [comment]
Hi @Ashwitha01 ,
Could you share the command you are executing?

**Comment by Ashwitha01** [comment]
To connect to your database from outside the cluster execute the following commands:

   kubectl port-forward --namespace default svc/cas-cassandra 9042:9042 &
   cqlsh -u cassandra -p $CASSANDRA_PASSWORD 127.0.0.1 9042

**Comment by javsalgar** [comment]
Hi,
I was unable to reproduce it

```
 ~                                                                                                      13:05:07  jsalmeron
❯ export CASSANDRA_PASSWORD=$(kubectl get secret --namespace default casi-cassandra -o jsonpath="{.data.cassandra-password}" | base64 --decode)
 ~                                                                                                      13:05:14  jsalmeron
❯ cqlsh -u cassandra -p $CASSANDRA_PASSWORD 127.0.0.1 9042
Connected to cassandra at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.6 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh>
cassandra@cqlsh>
cassandra@cqlsh>

```

**Comment by KarineValenca** [comment]
Hi guys, I'm using chart version 5.1.2 and app version 3.11.6. My pod starts correctely but when I pass the command `kubectl exec -ti cassandra-replica-0 cqlsh`, I received the message `Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
command terminated with exit code 1`

My values file is:

```
cassandra-replica:
    cluster:
        replicaCount: 3
        enableRPC: true
```

Does anybody knows the reason?

**Comment by KarineValenca** [comment]
I discovered that my problem was not enough memory at minikube. I scale it to 8GB and cassandra chart works properly!

**Comment by javsalgar** [comment]
Hi,

Good to know! Do not hesitate to reach if you find any other issues :)

**Comment by yobitelcom** [comment]
@javsalgar I didn't make any changes in the values.yaml file.

**Comment by Ashwitha01** [comment]
@javsalgar I din't make any changes to values.yaml file.

**Comment by Ashwitha01** [comment]
error still exists.

I have no name!@cass-cassandra-client:/$ cqlsh -u cassandra -p $CASSANDRA_PASSWORD 127.0.0.1 9042
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

**Comment by javsalgar** [comment]
Hi,

It seems that you have created a client pod but you are using 127.0.0.1 as the address. 127.0.0.1 is for the case that you are using kubectl port-forward, if you are using another pod then you should use the service name.
