### ISSUE TITLE
[bitnami/gitea] cannot use replicaCount ≠ 1 , due to mail queue

### ISSUE THREAD

**Issue by eltorio** [bitnami/charts#19834]
### Name and Version

bitnami/gitea:1.0.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

deploy helm chart to kubernetes with this values:  
```yaml
smtpHost: smtp.example.org
smtpPort: 25
replicaCount: 2
  persistence:
    size: 1Gi
    accessModes: ["ReadWriteMany"]  
extraEnvVars:
    - name: GITEA_SMTP_ENABLED
      value: "true"

```

### What is the expected behavior?

2 running pods

### What do you see instead?

1 pod is running, the other is restarting:  
```log
Back-off restarting failed container gitea-dev in pod gitea-dev-67d7758cfb-zxr4w_sandbox-gitea-dev(66e216a1-13d4-406b-bb5d-c0de3ffb5b2f)
```
the log of the restarting pod shows:  
```log
[E] Failed to create queue "mail": unable to lock level db at /opt/bitnami/gitea/data/queues/common: resource temporarily unavailable
```

### Additional information

the complete log of the restarting pod:
```log
gitea 06:41:03.05 
gitea 06:41:03.05 Welcome to the Bitnami gitea container
gitea 06:41:03.05 Subscribe to project updates by watching https://github.com/bitnami/containers>
gitea 06:41:03.05 Submit issues and feature requests at https://github.com/bitnami/containers/issues>
gitea 06:41:03.06 
gitea 06:41:03.06 INFO  ==> Configuring libnss_wrapper
gitea 06:41:03.08 INFO  ==> ** Starting Gitea setup **
gitea 06:41:03.10 INFO  ==> Waiting for database connection...
gitea 06:41:03.18 INFO  ==> Initializing Gitea...
gitea 06:41:03.28 INFO  ==> Restoring persisted Gitea installation
gitea 06:41:06.48 INFO  ==> ** Gitea setup finished! **
gitea 06:41:06.49 INFO  ==> ** Starting Gitea **
2023/10/08 06:41:06 cmd/web.go:223:runWeb() [I] Starting Gitea on PID: 1
2023/10/08 06:41:06 cmd/web.go:148:serveInstalled() [I] Gitea version: 1.20.5 built with GNU Make 4.3, go1.20.9 : bindata
2023/10/08 06:41:06 cmd/web.go:149:serveInstalled() [I] App path: /opt/bitnami/gitea/bin/gitea
2023/10/08 06:41:06 cmd/web.go:150:serveInstalled() [I] Work path: /opt/bitnami/gitea
2023/10/08 06:41:06 cmd/web.go:151:serveInstalled() [I] Custom path: /opt/bitnami/gitea/custom
2023/10/08 06:41:06 cmd/web.go:152:serveInstalled() [I] Config file: /opt/bitnami/gitea/custom/conf/app.ini
2023/10/08 06:41:06 cmd/web.go:153:serveInstalled() [I] Run mode: prod
2023/10/08 06:41:06 cmd/web.go:154:serveInstalled() [I] Prepare to run web server
2023/10/08 06:41:07 routers/init.go:112:InitWebInstalled() [I] Git version: 2.30.2, Wire Protocol Version 2 Enabled (home: /opt/bitnami/gitea/data/home)
2023/10/08 06:41:08 ...les/setting/cache.go:75:loadCacheFrom() [I] Cache Service Enabled
2023/10/08 06:41:08 ...les/setting/cache.go:90:loadCacheFrom() [I] Last Commit Cache Service Enabled
2023/10/08 06:41:08 ...s/setting/session.go:74:loadSessionFrom() [I] Session Service Enabled
2023/10/08 06:41:08 ...es/setting/mailer.go:203:loadMailerFrom() [W] connecting over insecure SMTP protocol to non-local address is not recommended
2023/10/08 06:41:08 ...es/setting/mailer.go:237:loadMailerFrom() [I] Mail Service Enabled
2023/10/08 06:41:08 ...s/storage/storage.go:176:initAttachments() [I] Initialising Attachment storage with type: local
2023/10/08 06:41:08 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /opt/bitnami/gitea/data/attachments
2023/10/08 06:41:08 ...s/storage/storage.go:166:initAvatars() [I] Initialising Avatar storage with type: local
2023/10/08 06:41:08 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /opt/bitnami/gitea/data/avatars
2023/10/08 06:41:08 ...s/storage/storage.go:192:initRepoAvatars() [I] Initialising Repository Avatar storage with type: local
2023/10/08 06:41:08 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /opt/bitnami/gitea/data/repo-avatars
2023/10/08 06:41:08 ...s/storage/storage.go:186:initLFS() [I] Initialising LFS storage with type: local
2023/10/08 06:41:08 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /opt/bitnami/gitea/data/lfs
2023/10/08 06:41:08 ...s/storage/storage.go:198:initRepoArchives() [I] Initialising Repository Archive storage with type: local
2023/10/08 06:41:08 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /opt/bitnami/gitea/data/repo-archive
2023/10/08 06:41:08 ...s/storage/storage.go:208:initPackages() [I] Initialising Packages storage with type: local
2023/10/08 06:41:08 ...les/storage/local.go:33:NewLocalStorage() [I] Creating new Local Storage at /opt/bitnami/gitea/data/packages
2023/10/08 06:41:18 ...les/queue/manager.go:108:]() [E] Failed to create queue "mail": unable to lock level db at /opt/bitnami/gitea/data/queues/common: resource temporarily unavailable
2023/10/08 06:41:18 ...ces/mailer/mailer.go:419:NewContext() [F] Unable to create mail queue
```

**Comment by joancafom** [comment]
Hi @eltorio 

Thanks for reporting the issue! I was investigating a little bit more about the problem and wondered if this does only happen when SMTP is enabled... Could you please confirm what is the result of installing the chart with a `replicaCount` > 1 (and RWX volume, of course)?

```yaml
replicaCount: 2
persistence:
  size: 1Gi
  accessModes: ["ReadWriteMany"]
```

This would be the associated `values.yaml` file. Thanks in advance

**Comment by ZandercraftGames** [comment]
I have encountered the same locking issue, but referring to the notification queue when redeploying/upgrading as well.

**Comment by eltorio** [comment]
@joancafom as @ZandercraftGames noted it is not specially linked to smtp but it is linked to all queue dependents processes.
Depending on wich process is concerned memcached or redis is mandatory. 
Redis works with all processes so I deployed a redis server and added this lines to app.ini
```toml
[queue]
TYPE = redis
CONN_STR = "redis://redis:6379/0"
```

**Comment by herokukms** [comment]
@eltorio Thanks for your help, but I cannot deploy your helm chart without removing smtp related templates.
Without smtp it works perfectly

**Comment by joancafom** [comment]
Thanks for sharing the details with the community @eltorio 

Bear in mind that Gitea itself considers HA as an experimental feature and should not be run in production (and even warns that they cannot assure that every feature/scenario works correctly). Having said that, I will create an internal task to analyse the setup with Redis as you described, and see if it would make sense to include it in our chart :)

**Comment by eltorio** [comment]
@joancafom 
Thank you, but if you don't include a queue management system you'll need to remove the parameter replicaCount since it cannot work.
I'm not sure if I'll open another issue but it might be useful to add a k8s TCPRoute option if the exposeSSH parameter is true.
In fact exposeSSH does not make sense in Kubernetes without TCPRoute since you cannot reach your service without manually tunneling or make custom exposure.

I'll simply add something like this with condition exposeSSH AND experimentalTCPRoute. 
(copied from my chart with Bitami gitea as gitea dependency). 
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata: 
    name: gitea-ssh-gateway
    namespace: {{ .Release.Namespace }}
    labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gitea.gatewayClassName }}
  listeners:
  - name: ssh
    protocol: TCP
    port: {{ .Values.gitea.service.ports.ssh }}
    allowedRoutes:
      kinds:
        - group: gateway.networking.k8s.io
          kind: TCPRoute
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: gitea-ssh-route
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gitea.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gitea-ssh-gateway
  rules:
    - backendRefs:
        - kind: Service
          name: {{ include "common.names.fullname" . }}
          port: {{ .Values.gitea.service.ports.ssh }}
```

**Comment by joancafom** [comment]
Hi @eltorio 

I have just created a PR removing the support for HA deployments in the meantime the changes are evaluated. Regarding the other issue, we usually try to keep threads single-themed. Could you please open a new issue? We will be more than happy to take a look and provide feedback there :) 

Thanks!

**Comment by herokukms** [comment]
@joancafom sad to hear that you remove the HA option. HA is the main advantage of running containerized application in a Kubernetes environment. Except if you run a Minikube for development purpose, Kubernetes is always a cluster… And why do you want to deal with a complex cluster if you don't want to use scalability nor HA ?

**Comment by herokukms** [comment]
@eltorio I use your mod successfully on our k8s cluster with 8 replicas, the only problem I have is I need to scale down to 1 before upgrade, and next scale up to 8. 
How do you deal with that ?

**Comment by joancafom** [comment]
> sad to hear that you remove the HA option

The functionality has been removed temporarily, in the meantime the required changes are evaluated by the team. Bear in mind that this has to do more with the asset itself, which does only support HA as an experimental feature, than to our product itself.
