### ISSUE TITLE
[bitnami/mediawiki] - expose deployment replicas in values file

### ISSUE THREAD

**Issue by sle78** [bitnami/charts#19842]
### Name and Version

bitnami/mediawiki v16.1.4

### What is the problem this feature will solve?

I can't set deployment **replicas** in the values file

### What is the feature you are proposing to solve the problem?

deployment replicas should be exposed unless mediawiki doesn't support it

[reference](/bitnami/charts/blob/main/bitnami/mediawiki/templates/deployment.yaml)

**Comment by juan131** [comment]
Hi @sle78 

Mediawiki does not provide any clustering or alternative mechanisms to deploy N replicas. This mean that any "write action" that you may perform while being connected to one replica won't be synchronized in the rest of replicas.

Therefore, the only way to deploy Mediawiki with multiple replicas would be using a RWX persistent volume that is shared across every replicas for storing the data (e.g. using NFS or similar persistent volume provider). Is that sth you'd be interested into?

**Comment by sle78** [comment]
Hi @juan131 thanks for your quick response on this issue. 
We can use a ReadWriteMany persistent storage shared across pods, and we may also need to enable sticky sessions on the load balance, this is something I'd be happy to experiment with and post any findings. 
May I suggest that the `replicas: 1` should be exposed with some warnings in the comment, that consistency is not guaranteed.

**Comment by juan131** [comment]
Hi @sle78 

Please take a look to the PR I just created adding support for this possibility.
