### ISSUE TITLE
Kafka Exporter - Annotations for Kubernetes Deployment

### ISSUE THREAD

**Issue by MaciekRR** [bitnami/charts#1987]
**Which chart**:

 [bitnami/kafka] Release 7.2.9 

**Description**

Is there a way to provide annotations for Deployment for Kafka-exporter ? Currently annotations in values.yaml for kafka-exporter are set only for kubernetes Service. Unfortunately to integrate with Datadog autodiscovery feature I need these annotations in Kubernetes Deployment, not Service.

**Steps to reproduce the issue:**

**Describe the results you expected:**

Annotations in Kubernetes Deployment

**Comment by sameersbn** [comment]
@MaciekRR I've implemented this option in #1990. If possible please give it a try and let me know if you find any issues

**Comment by MaciekRR** [comment]
@sameersbn Thanks for quick fix. I've tested it and correctly got annotations in the Deployment. 
Same functionality might be useful for JMX exporter (although I do not need it )

**Comment by MaciekRR** [comment]
Hi @sameersbn, when do you think we can expect this pull request will be merged ?
