### ISSUE TITLE
How to use chroot kind option, I could not find any support related to it?

### ISSUE THREAD

**Issue by ananthprasads** [bitnami/charts#1989]
How to use chroot kind option, I could not find any support related to it?

**Comment by javsalgar** [comment]
Hi,

We would need more context about what operation you want to perform. Which chart are you using? Could you provide more details?

**Comment by ananthprasads** [comment]
Hi,

Thanks for quick reply. 

I am using bitnami helm charts for both kafka and zookeeper. I want to have multiple cluster of kafka, which connects to same zookeeper. 

I could see some thing like this in zookeeper official site. Please let me know, how to enable this using bitnami helm charts 

Added in 3.2.0: An optional "chroot" suffix may also be appended to the connection string. This will run the client commands while interpreting all paths relative to this root (similar to the unix chroot command). If used the example would look like: "127.0.0.1:4545/app/a" or "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002/app/a" where the client would be rooted at "/app/a" and all paths would be relative to this root - ie getting/setting/etc... "/foo/bar" would result in operations being run on "/app/a/foo/bar" (from the server perspective). This feature is particularly useful in multi-tenant environments where each user of a particular ZooKeeper service could be rooted differently. This makes re-use much simpler as each user can code his/her application as if it were rooted at "/", while actual location (say /app/a) could be determined at deployment time.

**Comment by javsalgar** [comment]
Hi,

I am not sure if that is something to be enabled in the deployment or just directly using it in the server. Did you try setting that in your connection string when accessing kafka/zookeeper?

**Comment by ananthprasads** [comment]
I am using kafka charts only. For using chroot kind of option, we need to have path created in zookeeper and should be exposed.
And in kafka side that config should be supported.
I could see this options in confluent charts. I dont see any such option in bitnami charts.

Manually I did on one of host. Following are steps I did, I want some feature like this
1. Install a single node Kafka, three nodes zookeeper instances

     kafka1
     zookeeper1
     zookeeper2
     zookeeper3

2. Using a simple Kafka config, able to start without error in the log

     brokerid=1
     log.dir=/data/kafka
     zk.connect=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

3. Now, create a path in zookeeper1

     zkCli.sh -server zookeeper1:2181

         ls /
         [consumers, brokers, zookeeper]
         create /testkafka ''
         ls /
         [testkafka, consumers, brokers, zookeeper]

Quit & Done.

4. Verify from zookeeper2

     zkCli.sh -server zookeeper2:2181
         ls /
         [testkafka, consumers, brokers, zookeeper]

Seems ok

4. Update kafka config and restart

**Comment by javsalgar** [comment]
It seems to me that a feature like init scripts could fit your needs. You could run a set of scripts in the zookeeper and kafka nodes that would allow you to create the paths you need. Would that work for you?

Example for mongodb: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-10/rootfs/libmongodb.sh#L1208
