### ISSUE TITLE
podAnnotations not usable, wrong indent of annotations field

### ISSUE THREAD

**Issue by Xnyle** [bitnami/charts#1995]
annotations is not indented correctly under metadata. 

  {{- if .Values.podAnnotations }}
    annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
  {{- end }}

**Comment by juan131** [comment]
Hi @Xnyle 

What chart are you using? Please note this repository contains dozens of charts.

**Comment by Xnyle** [comment]
Sry, Wildfly

**Comment by dani8art** [comment]
Hi @Xnyle thank you for opening this issue, I've created a PR to fix this error.

Regards.
