### ISSUE TITLE
Dag Config Map - Need Example

### ISSUE THREAD

**Issue by stevenwarejones** [bitnami/charts#1996]
Can I get further documentation how to specify a DAG Config Map -- I'd like to have my DAGs in a separate volume that I deploy via CICD - is this possible?

**Comment by dani8art** [comment]
Hi @stevenwarejones, is your issue about `bitnami/airflow` chart, right?

**Comment by dani8art** [comment]
Hi @stevenwarejones there is any update on this? I think right now we support getting DAGs by giving a git repository and also you can use `dagsConfigMap` value to do what you are commenting above. 
- Values docs: https://github.com/bitnami/charts/tree/master/bitnami/airflow#parameters
- Load DAGs docs: https://github.com/bitnami/charts/tree/master/bitnami/airflow#load-dag-files

**Comment by dani8art** [comment]
Hi @stevenwarejones , @JWDobken any update here? did you find useful the link that I provided?
