### ISSUE TITLE
[bitnami/mariadb-galera] In a 3-node cluster, one of the nodes, ibdata1, has a very large file

### ISSUE THREAD

**Issue by hardship1** [bitnami/charts#19979]
### Name and Version

10.6.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The ibdata1 file of node 3 has 177G, but the other two nodes only have 334M, and the storage of node 3 will be occupied by ibdata1 file

### What is the expected behavior?

ibdata1 files no longer grow or increase slowly

### What do you see instead?

node1 is normal
![image](https://github.com/bitnami/charts/assets/24823238/c9632c3a-f299-421f-851a-a5fbb064ae1b)

node2 is normal
![image](https://github.com/bitnami/charts/assets/24823238/30820a0a-32bc-4040-b3b4-73b2ed722cdc)

node3 is abnormal
![image](https://github.com/bitnami/charts/assets/24823238/ce76d38a-2531-44eb-a628-2dfbbc2df3a8)

**Comment by javsalgar** [comment]
Hi,

Just to confirm, did you populate the database with a dataset of that size?

**Comment by hardship1** [comment]
Why is ibdata1 of node 3 so large and different from other nodes.
and I want ibdata1 to be smaller and not increase rapidly

**Comment by javsalgar** [comment]
Do you have a dataset that reproduces the issue?
