### ISSUE TITLE
notabug feature: Working Ingress Template for Wildfly

### ISSUE THREAD

**Issue by Xnyle** [bitnami/charts#1997]
Something like below would be nice.
~~Problem is, the template below for some reason doesn't work.~~
See below for working solution

/management path is accessible but login impossible.

Have many non k8s Wildfly instances running with the same nginx setup redirecting /management and /console to different port but somehow for this Wildfly instance that setup doesn't work. 
a POST to /management always results in 403.

I've no Idea what's going on.
If I access the service directly login is working fine ofc.

As written, this is not a Bug but a feature request in order to have a working Ingress configuration.

```apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wf-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500M
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization $http_authorization;
      proxy_set_header Origin 'http://$host';
spec:
  tls: # cert should be created
  - hosts:
    {{ range .Values.extrahosts }}
    - {{ .name }}
    {{ end }}
    secretName: {{ printf "%s-%s-cert" .Release.Name .Chart.Name | quote}} # cert-manager will store the created certificate in this secret.
  rules:
  {{ range .Values.extrahosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: /console
        backend:
          serviceName: {{ printf "%s-wildfly" .Release.Name | quote}}
          servicePort: 9990
      - path: /management
        backend:
          serviceName: {{ printf "%s-wildfly" .Release.Name | quote}}
          servicePort: 9990
      - path: /
        backend:
          serviceName: {{ printf "%s-wildfly" .Release.Name | quote}}
          servicePort: 80
  {{ end }}```

**Comment by Xnyle** [comment]
Actually login through ingress is never possible, even when I define a new host just for the admin console.

**Comment by Xnyle** [comment]
Already found out that I have to pass authorization header but that's still not enough:
```
nginx.ingress.kubernetes.io/configuration-snippet: |
    proxy_set_header Authorization $http_authorization;
```

**Comment by Xnyle** [comment]
I ended up with this at my ingress, still no luck.
I can confirm that the authorization header reaches the pod / Wildfly-Server
Would be really nice, if someone could come up with a working solution:

```
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header authorization $http_authorization;
      proxy_pass_request_headers on;
      add_header Front-End-Https on;
```

**Comment by Xnyle** [comment]
Problem is Ingress-NginX automatically adds Origin Header, it also adds CORS Headers but those are ignored, Wildfly only checks his own hostname against the Origin header if provided. 

https://github.com/wildfly/wildfly-core/blob/master/domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHttpHandler.java

if (headers.contains(Headers.ORIGIN)) {
      if(matchOrigin(exchange, allowedOrigins) != null) {

allowedOrigins is generated in Builder at bootup I presume?

Anyway, adding the following snippet to the Ingess configuration solves the issue:

```
nginx.ingress.kubernetes.io/configuration-snippet: |
  proxy_set_header Authorization $http_authorization;
  proxy_set_header Origin 'http://$host';
```
Maybe you could add this Info to the Markdown.

**Comment by dani8art** [comment]
Hi @Xnyle , this is so cool, thank you for your investigations and your solution, I would encourage you to contribute to our chart, please feel free to open a PR for adding this and give us the possibility to deploy a valid ingress configuration for wildly, you could use others examples like kibana. 
- https://github.com/bitnami/charts/blob/master/bitnami/kibana/values.yaml#L209
- https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/ingress.yaml#L1
