### ISSUE TITLE
[bitnami/redis-cluster] Can't connect to redis-cluster master slave via k8s loadbalancer service

### ISSUE THREAD

**Issue by VuKhuongDuy** [bitnami/charts#19985]
### Name and Version

redis-7.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I used chart: oci://registry-1.docker.io/bitnamicharts/redis-cluster
I want to use externalAccess, so I deployed 3 master nodes

### What do you see instead?

I used nodejs client to connect to redis-cluster via loadbalancer services IP. But it failed with an error: 
`(node:1272147) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'master' of undefined`

I also saw that 3 nodes use pod IP to connect together instead of external IP.
![Screenshot from 2023-10-10 16-12-05](https://github.com/bitnami/charts/assets/36961577/5af8f961-6b05-44ba-813e-d199d4a85cbe)
Could you help me check it? Thanks a lot

**Comment by javsalgar** [comment]
Which values did you use to deploy the chart?
