### ISSUE TITLE
[bitnami/discourse] Chat plugin is missing from Discourse when upgrading from a pre 10.0.0 Chart version which contains a pre-3.0 Image version

### ISSUE THREAD

**Issue by stevejr** [bitnami/charts#19980]
### Name and Version

bitnami/discourse 12.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install an older version of the Discourse Helm chart, for example 9.0.9 which has a pre-3.0.0 image. Check that the Chat plugin is not present.
2. Upgrade to to a version of the chart that contains a 3.0.x version of the image, for example Chart version 10.3.8. The Chat plugin is still not present even though it is now part of the Discourse core codebase.

### What is the expected behavior?

The Chat plugin should be present

### What do you see instead?

The Chat plugin is missing

### Additional information

Issue https://github.com/bitnami/charts/issues/19461 is also related to the Chat plugin and the inability to upgrade to a 3.1.n version of the Discourse image.

**Comment by dgomezleon** [comment]
Hi @stevejr,

Sorry for the delay. 

I can see that my mate @joancafom suggested [this approach](https://github.com/bitnami/charts/issues/19461#issuecomment-1757852428). Have you tried it?
