### ISSUE TITLE
[bitnami/milvus] cannot startup milvus when connect external etcd server with ssl

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#19983]
### Name and Version

bitnami/milvus:3.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

1. prepare etcd server certs(ca.pem, etcd-server.pem, etcd-server.key) and client certs(ca.pem, etcd-client.pem, etcd-client.key)
1. startup external etcd server with ssl using ca.pem, etcd-server.pem, etcd-server.key
3. generate milvus-etcd-client-tls-secret using kustomization.yaml
![image](https://github.com/bitnami/charts/assets/45187622/7dfde930-edf0-4c5e-b954-6fdcd750aa83)
4. config milvus values.yaml
![image](https://github.com/bitnami/charts/assets/45187622/cab74ef3-bd54-4ba5-b4af-c3326d34bdd3)

### What is the expected behavior?

milvus related services should startup nornamlly

### What do you see instead?

milvus releated services cannot startup, all failed when try to connect to etcd server

### Additional information

milvus helm chart, we should set enableDefaultInitContainers to true, otherwise cannot run `milvus.prepareMilvusInitContainer`, then the extraConfig cannot merge into milvus.yaml
meanwhile, also will try to run `milvus.waitForETCDInitContainer`, `milvus.waitForKafkaInitContainer`, `milvus.waitForS3InitContainer`.
But if etcd server is configured with tls, the waitForETCDInitContainer try to connect to etcd with the system public certs, not using the etcd client certs, then cannot connect to etcd server, pod will fail

**Comment by javsalgar** [comment]
Hi,

So, if I understod correctly, the issues is with the wait init container then. If we mount the certificates in case of tls and use them instead, it should work, is that correct? Did you try modifying the rendered yaml to confirm if that works? This would be helpful for the future PR

**Comment by chenraoCR** [comment]
> Hi,
> 
> So, if I understod correctly, the issues is with the wait init container then. If we mount the certificates in case of tls and use them instead, it should work, is that correct? Did you try modifying the rendered yaml to confirm if that works? This would be helpful for the future PR

yes, correct.

Also tried to modify the original helm chart file `milvus/templates/_helpers.tpl`, mounted the etcd client certs into the `milvus.waitForETCDInitContainer` and all the main containers, and in that initContainer, curl to etcd host with the mounted certs like 
`curl --max-time 5 "${etcd_host}/version" --cacert /bitnami/milvus/conf/cert/etcd/client/ca.pem --cert /bitnami/milvus/conf/cert/etcd/client/etcd-client.pem --key /bitnami/milvus/conf/cert/etcd/client/etcd-client.key `
, then startup milvus, all is okay

**Comment by chenraoCR** [comment]
in `milvus.waitForETCDInitContainer`, i just hardcoded the volumeMounts to test
![image](https://github.com/bitnami/charts/assets/45187622/9ef5e36f-4d05-4ac1-90be-273d3d66d229)

**Comment by chenraoCR** [comment]
sure, can work on it, will submit a PR with the fix

**Comment by javsalgar** [comment]
Thank you!

**Comment by chenraoCR** [comment]
@javsalgar sorry, i just pull the helm chart code, branch out a new branch, then fixed, but i have no account for your repo, so cannot commit

**Comment by chenraoCR** [comment]
@javsalgar sorry, this is my first time to submit changes on github, need to git pull my fork repo, then commit, then contribute my fork repo to bitnami/charts

**Comment by javsalgar** [comment]
NO problem!
