### ISSUE TITLE
[bitnami/airflow] could not connect to database after installing python package

### ISSUE THREAD

**Issue by Sms-Rk** [bitnami/charts#19997]
### Name and Version

bitnami/airflow:2.7.1

### What architecture are you using?

None

### What steps will reproduce the bug?

i use this dockerfile to install my python requirements package

```
FROM ***/airflow/airflow:2.7.1
USER root
COPY requirements.txt .
RUN pip3 install -r requirements.txt
```

after deploying airflow i get

could not connect to database

i also tried with requirements in /bitnami/python
but i get error about packages

### What do you see instead?
```
INFO  ==> ** Starting Airflow setup **
 airflow 11:20:56.90 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
airflow 11:20:57.27 INFO  ==> Initializing Airflow ...
airflow 11:20:57.30 INFO  ==> Configuration file found, loading configuration
airflow 11:20:57.31 INFO  ==> Trying to connect to the database server
airflow 11:22:14.52 ERROR ==> Could not connect to the database
```

**Comment by javsalgar** [comment]
Hi,

Could you set `BITNAMI_DEBUG=true` to see more information on the issue?
