### ISSUE TITLE
[bitnami/postgresql] When installing postgresql from the helm chart it goes to crashloopbackoff

### ISSUE THREAD

**Issue by Moneshs** [bitnami/charts#19999]
### Name and Version

bitnami/postgresql

### What architecture are you using?

None

### What steps will reproduce the bug?
```
helm install -n dev-resque sonar-postgresql  bitnami/postgresql --set \
global.postgresql.postgresqlUsername=sonaradmin --set \
global.postgresql.postgresqlPassword=sonaradmin123 --set \
global.postgresql.postgresqlDatabase=sonardb --set \
global.postgresql.servicePort=5432 --set \
global.storageClass=efs-resque-sc --set \
persistence.storageClass=efs-resque-sc --set \
persistence.existingClaim=efs-claim --set \
volumePermissions.enabled=true 
```

### What is the expected behavior?

using the persistence volume

### What do you see instead?

 kubectl logs sonar-postgresql-0  -c init-chmod-data -n dev-resque
chown: changing ownership of '/bitnami/postgresql': Operation not permitted

**Comment by javsalgar** [comment]
Hi,

It seems to me that the storage provider you are using is not compatible with `chmod` operations. As a way to explore the issue in more detail, you can launch the chart with `diagnosticMode.enabled=true` and try exploring what operations are allowed in the volume.

**Comment by Moneshs** [comment]
kubectl logs sonar-postgresql-0 -c init-chmod-data -n dev-resque
chown: changing ownership of '/bitnami/postgresql': Operation not permitted

its give the same output @javsalgar

**Comment by javsalgar** [comment]
And with `volumePermissions.enabled=false`?

**Comment by Moneshs** [comment]
And with volumePermissions.enabled=false

kubectl logs sonar-postgresql-0 -n dev-resque
postgresql 04:27:06.78
postgresql 04:27:06.78 Welcome to the Bitnami postgresql container
postgresql 04:27:06.78 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 04:27:06.78 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 04:27:06.78
postgresql 04:27:06.79 INFO  ==> ** Starting PostgreSQL setup **
postgresql 04:27:06.80 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 04:27:06.81 INFO  ==> Loading custom pre-init scripts...
postgresql 04:27:06.81 INFO  ==> Initializing PostgreSQL database...
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 04:27:06.83 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 04:27:06.83 WARN  ==> Lack of permissions on data directory!
postgresql 04:27:06.83 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 04:27:06.83 INFO  ==> Generating local authentication configuration

**Comment by javsalgar** [comment]
As the last operation, could you please launch it with `image.debug=true`? I want to understand in which exact part it is failing.

**Comment by Moneshs** [comment]
kubectl logs sonar-postgresql-0 -n dev-resque
postgresql 11:17:04.63
postgresql 11:17:04.63 Welcome to the Bitnami postgresql container
postgresql 11:17:04.63 Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 11:17:04.64 Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 11:17:04.64
postgresql 11:17:04.64 DEBUG ==> Configuring libnss_wrapper...
postgresql 11:17:04.65 INFO  ==> ** Starting PostgreSQL setup **
postgresql 11:17:04.66 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 11:17:04.67 INFO  ==> Loading custom pre-init scripts...
postgresql 11:17:04.67 INFO  ==> Initializing PostgreSQL database...
postgresql 11:17:04.68 DEBUG ==> Ensuring expected directories/files exist...
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 11:17:04.69 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 11:17:04.69 WARN  ==> Lack of permissions on data directory!
postgresql 11:17:04.69 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 11:17:04.69 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: could not change permissions of directory "/bitnami/postgresql/data": Operation not permitted
fixing permissions on existing directory /bitnami/postgresql/data ...

**Comment by javsalgar** [comment]
Hi,

It seems that the issue lies in the postgresql `initdb` command, which is upstream, not fruit of the Bitnami packaging. My advice would be to report this to the upstream PostgreSQL developers or use a different PVC technology.

**Comment by bodak** [comment]
@Moneshs @javsalgar Issue sits actually with AWS and the EFS CSI driver implementation.
Fix is here:
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300#issuecomment-1072860587

**Comment by rhps** [comment]
> @Moneshs @javsalgar Issue sits actually with AWS and the EFS CSI driver implementation. Fix is here: [kubernetes-sigs/aws-efs-csi-driver#300 (comment)](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300#issuecomment-1072860587)

hey this is not working anymore. Any recommendations for storageclass?
