### ISSUE TITLE
[bitnami/supabase] external database is not beeing initialized

### ISSUE THREAD

**Issue by Cbudano** [bitnami/charts#20017]
### Name and Version

bitnami/supabase 1.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

im deploying supabase on an azure aks and trying to use postgres flexible server as the external database.

### Are you using any custom parameters or values?
```
--set postgresql.enabled=false 
--set externalDatabase.host=xxxxxxxxxxx
--set externalDatabase.user=xxxxxxxxxxxx 
--set externalDatabase.password=xxxxxxxxxx
--set externalDatabase.database=xxxxxxxxxx
--set externalDatabase.port=5432
```
### What is the expected behavior?

the database should be initialized with the necesary schemas/tables.

### What do you see instead?

no objects get created on the database during the deployment, so i can see errors on the supabase components, like for storage i see:

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Migration failed. Reason: An error occurred running 'pathtoken-column'. Rolled back this migration. No further migrations were run. Reason: relation "storage.objects" does not exist

### Additional information

connection between supabase and the database is working, but i cant find any documentation regarding if when using an external databasewe need to do any previus steps, like installing extensions or running any particular scripts to create the objects.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the initialization is currently done by the supabase-postgres container (following how it is done by upstream), so when using an external database it is currently assuming that it is already initialized. As a current workaround you could try running this script in your external database

https://github.com/bitnami/containers/blob/main/bitnami/supabase-postgres/15/debian-11/rootfs/opt/bitnami/scripts/supabase-postgres/migrate.sh

As a possible improvement, we could add a job that performs this operation. Thoughts on that?
