### ISSUE TITLE
[bitnami/mysql] prometheus can't  get  data after opening merties switch

### ISSUE THREAD

**Issue by yab** [bitnami/charts#2001]
**Steps to reproduce the issue:**
1. set metrics.enabled: true
2. execute helm install my-release  -f value-production.yaml ./
3. view metries container's log:
kubectl logs -f my-release-mysql-master-0  -c metrics

`
./session-03-03-47.115.81.206.log:time="2020-03-03T00:10:14Z" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: NO)" source="exporter.go:146"
./session-03-03-47.115.81.206.log:time="2020-03-03T00:10:20Z" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: NO)" source="exporter.go:146"
./session-03-03-47.115.81.206.log:time="2020-03-03T00:10:24Z" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: NO)" source="exporter.go:146"
...
`

**Comment by juan131** [comment]
Hi @yab 

Thanks so much for reporting this issue! I just took a look to the associated PR and add you some comments.
