### ISSUE TITLE
[quesiton] bitnami/mariadb-galera - options to backup the data

### ISSUE THREAD

**Issue by eleaner** [bitnami/charts#2004]
Hello,

I am struggling to understand what are the options to backup a specific database(s) from the cluster in Kubernetes.
I can see a set of galera.mariabackup.* parameters, but I am not sure how or if I can use them

Could someone please help me?

**Comment by javsalgar** [comment]
Hi,

According to this https://github.com/bitnami/bitnami-docker-mariadb-galera#setting-up-a-multi-master-cluster, it is configuring the State Snapshot Transfer. More information here: https://galeracluster.com/library/documentation/glossary.html#term-state-snapshot-transfer

If you want regular backups my advice would be to use mysqldump or similar tools.
