### ISSUE TITLE
[bitnami/grafana-operator] Field is Immutable in Grafana Operator 

### ISSUE THREAD

**Issue by pseymournutanix** [bitnami/charts#20047]
### Name and Version

bitnami/grafana-operator:v3.4.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deployed Operator

### What is the expected behavior?

Grafana Operator deploys new instance

### What do you see instead?

```
2023-10-11T06:51:04Z	ERROR	GrafanaReconciler	reconciler error in stage	{"controller": "grafana", "controllerGroup": "grafana.integreatly.org", "controllerKind": "Grafana", "Grafana": {"name":"grafana-operator-grafana","namespace":"grafana"}, "namespace": "grafana", "name": "grafana-operator-grafana", "reconcileID": "57ff9b80-8422-40ee-a109-ceaa894c30a6", "stage": "deployment", "error": "Deployment.apps \"grafana-operator-grafana-deployment\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app\":\"grafana-operator-grafana\", \"app.kubernetes.io/component\":\"grafana\", \"app.kubernetes.io/instance\":\"grafana-operator\", \"app.kubernetes.io/name\":\"grafana-operator\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable"}
github.com/grafana-operator/grafana-operator/v5/controllers.(*GrafanaReconciler).Reconcile
	/bitnami/blacksmith-sandox/grafana-operator-5.4.1/src/github.com/grafana-operator/grafana-operator/controllers/grafana_controller.go:105
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/bitnami/blacksmith-sandox/grafana-operator-5.4.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/bitnami/blacksmith-sandox/grafana-operator-5.4.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/bitnami/blacksmith-sandox/grafana-operator-5.4.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/bitnami/blacksmith-sandox/grafana-operator-5.4.1/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/internal/controller/controller.go:227
```

**Comment by pseymournutanix** [comment]
....And they say it's not an upstream issue :)

**Comment by juan131** [comment]
@pseymournutanix could you please point us to the discussion with upstream developers?

**Comment by pseymournutanix** [comment]
https://github.com/grafana-operator/grafana-operator/issues/1268

BTW I just deleted the old instance and re-applied which was fine but not ideal.

Thanks

**Comment by juan131** [comment]
Thanks for providing the details @pseymournutanix, as you mentioned recreating the manifest would fix the issue if there's a problem with an inmutable field but it's not ideal.

A couple of extra questions:

- Were you upgrading from chart version `3.3.1` or earlier to `3.4.9`?
- Are you setting custom values at `grafana.ingress.labels`,  `grafana.labels` or `commonLabels` parameters?

**Comment by pseymournutanix** [comment]
No problem for this I was coming from 3.4.0 and I do set `commonLabels` and `grafana.labels` to the same K/V

**Comment by juan131** [comment]
Hi @pseymournutanix 

Thanks for providing the details! I tried to reproduce it by creating a **values.yaml** such as the one below:

```yaml
commonLabels:
  foo: bar
grafana:
  labels:
    foo: bar
```

Then, I installed the chart using these values and version `3.4.0`:

```bash
helm install grafana-operator oci://registry-1.docker.io/bitnamicharts/grafana-operator --values values.yaml --version 3.4.0
```

And.. I upgraded to `3.4.9` once both the Operator and Grafana pods were ready:

```bash
helm upgrade grafana-operator oci://registry-1.docker.io/bitnamicharts/grafana-operator --values values.yaml --version 3.4.9
```

However, i was unable to reproduce the issue. Could you please share the exact values you're using on these parameters?

**Comment by juan131** [comment]
Hi @pseymournutanix 

Thanks, I can reproduce the issue when upgrading from 3.3.1 -> 3.4.0. The reason for this backwards incompatibility seems to be in the changes I introduced at https://github.com/bitnami/charts/commit/ec057c1cb98158b2b8fd36a316e9d7deb633d1cb:

```diff
spec:
  client:
    timeout: 5
  service:
    spec:
      type: ClusterIP
  deployment:
    metadata:
      labels:
+       app.kubernetes.io/instance: grafana-operator
+       app.kubernetes.io/managed-by: Helm
+       app.kubernetes.io/name: grafana-operator
+       dashboards: grafana
+       helm.sh/chart: grafana-operator-3.4.0
+       app.kubernetes.io/component: grafana
    spec:
      replicas: 1
+     selector:
+       matchLabels:
+         app.kubernetes.io/instance: grafana-operator
+         app.kubernetes.io/name: grafana-operator
+         app.kubernetes.io/component: grafana
      template:
        metadata:
+         labels:
+           app.kubernetes.io/instance: grafana-operator
+           app.kubernetes.io/managed-by: Helm
+           app.kubernetes.io/name: grafana-operator
+           dashboards: grafana
+           helm.sh/chart: grafana-operator-3.4.0
+           app.kubernetes.io/component: grafana
```

The `deployment.spec.selector` field is inmutable and, therefore, the operator complains when it tries to upgrade Grafana deployment, my bad. 

The problem shouldn't affect you in the future since there are no changes affecting this field after that.

**Comment by pseymournutanix** [comment]
That's great, really appreciate you digging into this and all the hard work. I will close this.
