### ISSUE TITLE
[kubeapps] test-pods don't use global.registry

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#2007]
**Which chart**:

kubeapps, v.latest

**Description**

manifests in https://github.com/bitnami/charts/tree/master/bitnami/kubeapps/templates/tests don't use the global.registry helper like for instance: https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/templates/apprepository-deployment.yaml#L40

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

won't use global registry

**Describe the results you expected:**

use global registry here too
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by carrodher** [comment]
Hi @ davidkarlsen, thanks for reporting this issue. The kubeapps chart hosted here is just a mirror of the code present in the kubeapps repo: https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps

We will fix the issue in that repo and then the changes will appear here.

**Comment by davidkarlsen** [comment]
https://github.com/davidkarlsen/kubeapps/tree/feature/fixtestimgregistry
