### ISSUE TITLE
[bitnami/harbor] allow using existing secrets (therefore also SealedSecrets) instead of generating them based on plain text values

### ISSUE THREAD

**Issue by pfyod** [bitnami/charts#2010]
**Which chart**:

harbor

**Description**

As of now,  it's not possible to use the chart (without some major workarounds) in a GitOps pipeline - `values.yaml` has passwords / secrets in plain text. Obviously, nobody wants plain text passwords committed to version control.

If the chart was to be modified in such a way that it's possible to use values from existing secret(s) instead of the plain text parameters, it would be possible to use solutions like [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets) to securely manage passwords in a GitOps friendly and secure way.

**Describe the results you expected:**

It should be possible to use existing secrets instead of the plain text values for these parameters:

| Parameter                                                    |
| ------------------------------------------------------------ |
| **General**                                                  |
| `harborAdminPassword`                                        |
| `secretkey`                                                  |
| **Persistence**                                              |
| `persistence.imageChartStorage.azure.accountkey`             |
| `persistence.imageChartStorage.gcs.encodedkey`               |
| `persistence.imageChartStorage.s3.accesskey`                 |
| `persistence.imageChartStorage.s3.secretkey`                 |
| `persistence.imageChartStorage.swift.password`               |
| `persistence.imageChartStorage.oss.accesskeysecret`          |
| **Core**                                                     |
| `core.secret`                                                |
| **Jobservice**                                               |
| `jobservice.secret`                                          |
| **Registry**                                                 |
| `registry.secret`                                            |
| **PostgreSQL**                                               |
| `externalDatabase.password`                                  |
| **Redis**                                                    |
| `externalRedis.password`                                     |

**Additional information you deem important (e.g. issue happens only occasionally):**

There's a [PR](https://github.com/goharbor/harbor-helm/pull/199) for the `harbor-helm` repo that partially implements this functionality.

**Comment by miguelaeh** [comment]
Hi @pfyod ,
Thank you very much for the suggestion.
Would you like to create a PR for this feature?
