### ISSUE TITLE
Zookeeper how to configure existingClaim for multi replica deployment

### ISSUE THREAD

**Issue by olga-density** [bitnami/charts#20111]
### Name and Version

bitnami/zookeeper

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I have a zookeeper with three replicas. All replicas are running in east-1a. I'd like to redeploy the helm chart with three replicas to deploy across three AZs. And I need to restore/migrate the existing PVCs. I was thinking of configuring existingClaim using dataSource (VolumeSnapshot or existing PVC), but there are no options in the helm chart.
Kindly ask for any advice/suggestions on how to proceed with migration. 

### What do you see instead?

There are no available config in values

**Comment by carrodher** [comment]
This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
