### ISSUE TITLE
Outdated CRD in contour

### ISSUE THREAD

**Issue by ruzmuh** [bitnami/charts#20112]
### Name and Version

bitnami/contour 13.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. deploy contour with  `manageCRDs: true` (it's true by default)
2. try to create an http proxy with a regex route condition, e.g.: 
```yaml
spec:
  routes:
  - conditions:
    - regex: /list/.*
    ...
```

### What is the expected behavior?

httpproxy.projectcontour.io/example created

### What do you see instead?

 HTTPProxy in version "v1" cannot be handled as a HTTPProxy: strict decoding error: unknown field "spec.routes[0].conditions[0].regex"

### Additional information

bitnami/contour uses AppVersion=1.26.0.
HTTPProxy's CRD was updated in 1.26.0 release (see https://github.com/projectcontour/contour/releases/tag/v1.26.0#minor-changes)
For instance, this block was added: https://github.com/projectcontour/contour/blob/ef24ff216c1c799957fed921c89d7c75f358db38/examples/contour/01-crds.yaml#L5145

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
