### ISSUE TITLE
elasticsearch chart, no xpaxk......pitiful

### ISSUE THREAD

**Issue by junneyang** [bitnami/charts#2015]

**Comment by carrodher** [comment]
Hi, please, can you elaborate a bit more on your issue? Thanks!

**Comment by carrodher** [comment]
Hi, I just discovered another issue about the same topic in the container image repository (this repository is for charts). I will close this one and provide an answer in https://github.com/bitnami/bitnami-docker-elasticsearch/issues/70.

Thanks!
