### ISSUE TITLE
[bitnami/mongodb] Helm upgrade password sync issue

### ISSUE THREAD

**Issue by boopathykpm** [bitnami/charts#2016]
**Which chart**:
      **Chart**: MongoDB
      **Version**: 7.8.7
      **Chart URL**: https://github.com/bitnami/charts/tree/master/upstreamed/mongodb

**Description**

MongoDB is not updating the password change that occurred while upgrading the helm chart.  

**Steps to reproduce the issue:**

1. Install the MongoDB helm chart 
2. Upgrade the helm chart after changing the values on values.yaml that needs to be updated. 
3. The password on the secret that got updated once the helm upgrade is done. 

**Describe the results you received:**

The password of MongoDB is getting updated inside the secret, which got created while installing the helm chart for the first time. 

**Describe the results you expected:**

The password for the database is referring to the password that generated while installing the helm chart, it's not picking up the password which got updated after helm upgrade.  

While doing the helm upgrade, there should be a listener component that should keep looking for any password change had happened, if so it needs to update MongoDB cluster password. 

Now, in this case, the connection to the database is getting failed as the new password is not getting updated to the cluster. It should get updated so that the failure of the database will be fixed.

**Comment by miguelaeh** [comment]
Hi @boopathykpm ,
In the helm upgrade command, you should pass the old passwords. The password is not being updated because it is stored into a volume, so, when you perform the helm upgrade the stored password remains the first one, not the generated in the upgrade. To solve the issue it should be enough passing the old password in the helm upgrade command.

**Comment by boopathykpm** [comment]
Hi @miguelaeh  
Thanks for updating. I will try that out. Can you let me know the best practice to rotate the password for admin?

**Comment by miguelaeh** [comment]
Hi @boopathykpm ,
I am afraid there is not a "trivial" way to that. You can do something similar to this, to modify the MongoDB password manually: https://docs.bitnami.com/azure-templates/infrastructure/mongodb/administration/change-reset-password/
Or you could export the database data, install the chart again and import the data.

**Comment by boopathykpm** [comment]
Thanks, @miguelaeh it makes sense !!!

**Comment by drcrook1** [comment]
Can you specify how you change the password via the helm chart version?  I'm running into this problem and I would like to rotate my secrets in my Azure Key Vault linked to an update keys script which runs headlessly without an admin intervening.

**Comment by miguelaeh** [comment]
Hi @drcrook1 ,
Could you open a different issue for your use case?
Also, I am not sure do you mean with `change the password via the helm chart version`, could you clarify that?
