### ISSUE TITLE
Add loadBalancerClass and allocateLoadBalancerNodePorts to postgres chart

### ISSUE THREAD

**Issue by timcole** [bitnami/charts#20214]
### Name and Version

postgresql 13.1.5

### What is the problem this feature will solve?

[loadBalancerClass](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) and [allocateLoadBalancerNodePorts](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation) are not configurable in `postgres` chart.

_Similar to #19421 and #19316 added for other charts_

### What is the feature you are proposing to solve the problem?

Please add support for these two spec options. I don't have the ability to PR this myself at the moment but would greatly appreciate the addition. Thank you!

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by timcole** [comment]
Hello, this should definitely remain open for someone who has the bandwidth to tackle it.

I've undergone surgery recently so can't get this done myself at the moment.
