### ISSUE TITLE
[bitnami/matomo] Configmap for config.ini.php in Matomo

### ISSUE THREAD

**Issue by rdagerfall** [bitnami/charts#20228]
### Name and Version

bitnami/matomo 2.2.2

### What is the problem this feature will solve?

I want to be able to override configuration: "/bitnami/matomo/config/config.ini.php" in the container using the Helm chart.

I want to configure it to work with a reverse proxy: https://matomo.org/faq/how-to-install/faq_98/ and for this I need to add a few lines to the config.ini.php

How can I achieve this using the helm template?

Should I just go ahead and mount the config "config.ini.php" manually as a configmap and include the whole configuration?

### What is the feature you are proposing to solve the problem?

Configmap for config.ini.php

### What alternatives have you considered?

N/A

**Comment by rdagerfall** [comment]
Thanks! The configmap is created but for some reason the script is not executed when I restart the container.

I can see that configmap  `matomo-postinit` is mounted and I can run the script manually and it works fine.

```
1001@matomo-ccb8fbb8c-gd79s:/$ ls docker-entrypoint-init.d/
custom-post-init.sh

1001@matomo-ccb8fbb8c-gd79s:/$ sh /docker-entrypoint-init.d/custom-post-init.sh 
Run custom-post-init.sh
```


Script:

```
customPostInitScripts:
  custom-post-init.sh: |
    #!/bin/bash
    echo "Run custom-post-init.sh"

    CONFIG_FILE="/bitnami/matomo/config/config.ini.php"
    FORCE_SSL="force_ssl = 1\n"
    ASSUME_SECURE_PROTOCOL="assume_secure_protocol = 1\n"
    PROXY_CLIENT_HEADERS="proxy_client_headers[] = HTTP_X_FORWARDED_FOR\n"
    PROXY_HOST_HEADERS="proxy_host_headers[] = HTTP_X_FORWARDED_HOST"

    sed -i "/\[General\]/a\\$FORCE_SSL$ASSUME_SECURE_PROTOCOL$PROXY_CLIENT_HEADERS$PROXY_HOST_HEADERS" "$CONFIG_FILE"
```

Logs:

```
matomo 11:31:50.08 INFO ==> Configuring the HTTP port
matomo 11:31:50.09 INFO ==> Configuring the HTTPS port
matomo 11:31:50.09 INFO ==> Configuring Apache ServerTokens directive
matomo 11:31:50.11 INFO ==> Configuring PHP options
matomo 11:31:50.11 INFO ==> Setting PHP expose_php option
matomo 11:31:50.12 INFO ==> Setting PHP output_buffering option
matomo 11:31:50.14 INFO ==> Validating settings in MYSQL_CLIENT_* env vars
matomo 11:31:50.16 WARN ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo 11:31:50.23 INFO ==> Persisted Matomo installation detected
matomo 11:31:50.23 INFO ==> Updating Matomo files in persisted data
matomo 11:31:53.62 INFO ==> Restoring Matomo installation
matomo 11:31:53.97 INFO ==> Trying to connect to the database server
matomo 11:31:54.00 INFO ==> Launching schema update
Everything is already up to date.
Done. To check if this worked please open the system report or run `./console diagnostics:run` and look out for the private directories check. If it doesn't work you may need to execute this command using a user that has write permissions or maybe you are not using Apache or IIS web server. Please note you may need to execut this command every time you update Matomo to a newer version.
matomo 11:31:57.30 WARN ==> Skipping cron configuration for Matomo because of running as a non-root user
matomo 11:31:57.30 INFO ==> ** Matomo setup finished! **
matomo 11:31:57.31 WARN ==> Cron will not be started because of running as a non-root user
matomo 11:31:57.32 INFO ==> ** Starting Apache **
[Mon Oct 16 11:31:57.411098 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Mon Oct 16 11:31:57.411189 2023] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

**Comment by javsalgar** [comment]
Hi,

I'm afraid the init script needs to work on a clean installation if I'm not mistaken.

**Comment by rdagerfall** [comment]
I did a workaround and I'm running the script with a init container instead. This solution fixed so correct visitor external IP-address is showing.

If someone else have this issue, I did like this:

```
initContainers:
  - name: custom-post-init-script
    image: bitnami/matomo
    command:
      - /bin/sh
      - docker-entrypoint-init.d/custom-post-init.sh
    volumeMounts:
      - name: matomo-data
        mountPath: /bitnami/matomo
      - name: custom-postinit
        mountPath: /docker-entrypoint-init.d
customPostInitScripts:
  custom-post-init.sh: |
    #!/bin/bash

    # Config
    CONFIG_FILE="/bitnami/matomo/config/config.ini.php"

    # Variables
    SCRIPT_START="#Generated by custom-post-init.sh\n"
    FORCE_SSL="force_ssl = 1\n"
    ASSUME_SECURE_PROTOCOL="assume_secure_protocol = 1\n"
    PROXY_CLIENT_HEADERS="proxy_client_headers[] = HTTP_X_FORWARDED_FOR\n"
    PROXY_HOST_HEADERS="proxy_host_headers[] = HTTP_X_FORWARDED_HOST\n"
    SCRIPT_END="#End of custom-post-init.sh"

    if ! grep -q "#Generated by custom-post-init.sh" "$CONFIG_FILE"; then
       echo "Executing custom-post-init.sh"
       sed -i "s/\[General\]/[General]\n$SCRIPT_START$FORCE_SSL$ASSUME_SECURE_PROTOCOL$PROXY_CLIENT_HEADERS$PROXY_HOST_HEADERS$SCRIPT_END/" "$CONFIG_FILE"
    else
       echo "Not executing custom-post-init.sh since already executed"
    fi
```
Configuration for [General] will then look like this:

```
[General]
#Generated by custom-post-init.sh
force_ssl = 1
assume_secure_protocol = 1
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_host_headers[] = HTTP_X_FORWARDED_HOST
#End of custom-post-init.sh
```

**Comment by JoshuaSmeda** [comment]
This feature request seems like a pretty sane request. There are plenty of users who have custom plugins, that are configured through config.ini.php, besides the usually custom config.

Specifically catering for all edge cases through env vars is a fool's errand. 

What is the possibility of driving the config.ini.php through a ConfigMap as a alternative solution?

**Comment by javsalgar** [comment]
Hi,

It could be possible to add support for custom config.ini files. However, as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR with the value?

**Comment by arslanbekov** [comment]
Why this task was closed needs to be clarified; it would have been beneficial.

Matomo can read settings `config.php.ini` from environment variables - https://plugins.matomo.org/EnvironmentVariables

However, the docker container Bitnami Matomo does not support this, and changing `config.php.ini` through definition env does not work for me.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kyotin** [comment]
Thanks so much [rdagerfall](https://github.com/rdagerfall)
