### ISSUE TITLE
[bitnami/wordpress] loadBalancer external IP stuck in pending state

### ISSUE THREAD

**Issue by arkabase** [bitnami/charts#20232]
### Name and Version

bitnami/wordpress 18.0.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. install Helm Chart in kubernetes using the command provided in official doc : 
`$ helm install my-release oci://registry-1.docker.io/bitnamicharts/wordpress`

2. check installed service as asked in the install process :
`$ kubectl get svc --namespace default -w my-release`

### What is the expected behavior?

the service should provide an external IP for accessing the app from outside the cluster

### What do you see instead?

External IP is stuck to <pending> state and the `status.loadBalancer` path in the service template is empty : 

```console
$ kubectl get svc --namespace default my-release -o yaml
apiVersion: v1
kind: Service
...
status:
  loadBalancer: {}
```

### Additional information

Debian 12 + Kubernetes 1.28.2 + Helm 3.12.3

**Comment by javsalgar** [comment]
Hi,

This seems to be an issue in the Kubernetes cluster rather than a problem in the Bitnami packaging of WordPress. Which is the Kubernetes platform you are using? If you are using minikube, this is expected.
