### ISSUE TITLE
Add 'shareProcessNamespace` to the bitnami chart for external-dns

### ISSUE THREAD

**Issue by Nexarian** [bitnami/charts#20239]
### Name and Version

bitnami/external-dns 6.56.5

### What architecture are you using?

None

### What steps will reproduce the bug?

In this commit over a year ago the `shareProcessNamespace` flag was introduced into the `externalDns` helm chart: https://github.com/kubernetes-sigs/external-dns/pull/2715

Go into this directory: https://github.com/bitnami/charts/tree/main/bitnami/external-dns and grep for `shareProcessNamespace` and you'll find nothing.

This blocks the ability to use the workaround described here: https://github.com/kubernetes-sigs/external-dns/issues/3713

### Are you using any custom parameters or values?

Yes, I want to use `shareProcessNamespace` but the bitnami chart doesn't provide it.

### What is the expected behavior?

For the bitnami chart to pass through the `shareProcessNamespace` parameter like it does all others to the external-dns chart.

### What do you see instead?

Nothing. The parameter isn't passed.

### Additional information

This is important because users of externalDNS who use Vault for IAM authentication with the AWS_SHARED_CREDENTIAL_FILE method are blocked on an elegant way to keep their external-dns pods functional.

Without this, a custom restarter cron has to be implemented for users of this chart.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
