### ISSUE TITLE
[bitnami/keycloak]  How to setup keycloak to use TLS while send outgoing email

### ISSUE THREAD

**Issue by WestFarmer** [bitnami/charts#20244]
### Name and Version

bitnami/keycloak 16.0.2

### What is the problem this feature will solve?

I have self-hosted email(using poste.io) which using Let's encrypt certs.

and In my kubernetes' I have secret containing same certs.

this secret contain only these two keys:
```
tls.crt
tls.key
```

how to config this chart to using such certs to send email with STARTTLS ?

I have saw those TLS config parameters, but don't know how to set values.

Please share a example....

please note I want keycloak expose HTTP only, as there was reverse proxying handleing HTTPS

### What is the feature you are proposing to solve the problem?

please help

**Comment by javsalgar** [comment]
Hi,

You may need to configure the keystore: https://www.keycloak.org/server/keycloak-truststore

In order to achieve that, you could use the custom init scripts section of the chart.

**Comment by WestFarmer** [comment]
using certs like those from let's encrypt. truststore is not necessary. because jre has built-in trust for them.

thanks for help, case closed.
