### ISSUE TITLE
GF_INSTALL_PLUGINS is being mis-interpreted

### ISSUE THREAD

**Issue by nhti** [bitnami/charts#20242]
### Name and Version

bitnami/grafana-operator

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the grafana-operator chart
2. Leave configurations to be default
3. Add a GrafanaDatasource type resource with plugins spec similar to
```yaml
  plugins:
    - name: camptocamp-prometheus-alertmanager-datasource
      version: 1.0.0
```
4. Deploy out the grafana-operator helm chart
5. Observe the grafana-deployment created by the operator
It has the following environment variable
```yaml
       - name: GF_INSTALL_PLUGINS
          value: camptocamp-prometheus-alertmanager-datasource 1.0.0
```
6. Observe the grafana-deployment logs
It has the following logs message
```
grafana 04:10:21.48 
grafana 04:10:21.48 Welcome to the Bitnami grafana container
grafana 04:10:21.48 Subscribe to project updates by watching https://github.com/bitnami/containers
grafana 04:10:21.48 Submit issues and feature requests at https://github.com/bitnami/containers/issues
grafana 04:10:21.48 
grafana 04:10:21.49 INFO  ==> Ensuring /etc/grafana/grafana.ini points to /opt/bitnami/grafana/conf/grafana.ini
grafana 04:10:21.49 INFO  ==> Ensuring /var/lib/grafana points to /opt/bitnami/grafana/data
grafana 04:10:21.50 INFO  ==> Ensuring /var/log/grafana points to /opt/bitnami/grafana/logs
grafana 04:10:21.51 INFO  ==> Installing plugin camptocamp-prometheus-alertmanager-datasource
Deprecation warning: The standalone 'grafana-cli' program is deprecated and will be removed in the future. Please update all uses of 'grafana-cli' to 'grafana cli'
✔ Downloaded and extracted camptocamp-prometheus-alertmanager-datasource v1.2.1 zip successfully to /opt/bitnami/grafana/data/plugins/camptocamp-prometheus-alertmanager-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.

grafana 04:10:21.80 INFO  ==> Installing plugin 1.0.0
Deprecation warning: The standalone 'grafana-cli' program is deprecated and will be removed in the future. Please update all uses of 'grafana-cli' to 'grafana cli'
Error: ✗ 404: Plugin not found (Grafana v10.1.4 linux-amd64)
```

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

The expected behaviour is for grafana to install the camptocamp-prometheus-alertmanager-datasource plugin of version 1.0.0

### What do you see instead?

Grafana is installing the camptocamp-prometheus-alertmanager-datasource plugin of version 1.2.1 (latest) and a "1.0.0" plugin

### Additional information

I have tried manually setting the GF_INSTALL_PLUGINS value as camptocamp-prometheus-alertmanager-datasource:1.0.0 instead, and it would execute the expected behaviour

**Comment by fevisera** [comment]
Hi @nhti,

It seems another user implemented https://github.com/bitnami/containers/pull/51889 mentioning it would solve your issue. Could you please confirm that is related to your issue? If so, does it make sense to you to wait for that PR review resolution to check if your issue is solved?

Thanks.

**Comment by fevisera** [comment]
Hi @nhti,

Thanks a lot for confirming both things! I will leave this issue open. Once that PR is successfully resolved, it should automatically close this issue.
