### ISSUE TITLE
[bitnami/mongodb] arbiter's configuration file cannot be customised 

### ISSUE THREAD

**Issue by tripplemac** [bitnami/charts#20255]
### Name and Version

bitnami/mongodb 14.0.10

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Customise the param `arbiter.configuration` in `values.yaml`.
2. Run helm install: `$ helm --dry-run --debug install my-mongodb oci://registry-1.docker.io/bitnamicharts/mongodb`

### Are you using any custom parameters or values?

```
arbiter:
  configuration: |-
    storage:
      dbPath: /my/data/db
```

### What is the expected behavior?

It should generate `arbiter/configmap.yaml` with provided configuration.

### What do you see instead?

Installation ends with following error:
```
Error: INSTALLATION FAILED: YAML parse error on mongodb/templates/arbiter/configmap.yaml: error converting YAML to JSON: yaml: line 4: found character that cannot start any token
helm.go:84: [debug] error converting YAML to JSON: yaml: line 4: found character that cannot start any token
YAML parse error on mongodb/templates/arbiter/configmap.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:304
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:306
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:152
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_arm64.s:1197
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_arm64.s:1197
```

### Additional information

The issue is inside the `bitnami/mongodb/templates/arbiter/configmap.yaml` template file, where you should use `printf` instaed of `print`, see here:
https://github.com/bitnami/charts/blob/9b732c6d900c75cc0ff1f942766418df4f9935f4/bitnami/mongodb/templates/arbiter/configmap.yaml#L10

BTW: the same issue is present in the `bitnami/mongodb-sharded` chart

**Comment by rafariossaa** [comment]
Hi @tripplemac,
  I am sorry, but our mongodb image does not support ARM architecture, you can [check it here](https://hub.docker.com/search?q=bitnami%2Fmongodb), so I think the cause of the error is this.
  We are currently looking into supporting this architecture for mongodb. We will come back as soon as we have news.

**Comment by rafariossaa** [comment]
Reviewing this, currently MongoDB does not support ARM with debian images.

**Comment by tripplemac** [comment]
Hi @rafariossaa, thanks for looking at this issue.
I'm running the MongoDB on AMD64, so that should be fine. The ARM64 architecture in my bug report refers to the computer where I'm running `$ helm install ...`. 

This is not about the runtime, but rather about a bug in the yaml template, that fails to generate correct `configmap.yaml` for the arbiter node. 
This line in the `mongodb/templates/arbiter/configmap.yaml` file is wrong:
```yaml
{{ print "%s-arbiter" (include "mongodb.fullname" .) }}
```
You must use `printf` instead of `print`:
```yaml
{{ printf "%s-arbiter" (include "mongodb.fullname" .) }}
```

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay.
  As you figured it out. Would you like to contribute and send a PR ? We will be glad to review and merge it.

**Comment by tripplemac** [comment]
Sure, will do so.
