### ISSUE TITLE
How to change logging levels in log4j.properties

### ISSUE THREAD

**Issue by LorrieS** [bitnami/charts#2027]
**Which chart**:

| **Component** | **Helm Source** | **Helm Chart** | **Helm Chart Version** | **Application Version** |
|---------------|-----------------|----------------|------------------------|-------------------------|
| Kafka | Helm - GitHub | bitnami/kafka | 7.0.3 | 2.3.1 |

## 
**Description**

I am trying to figure out how to change logging level for a few classes in Kakfa.
The logging levels are currently set in /opt/bitnami/kafka/conf/log4j.properties.
Is there a way to change them on the fly, or a chart value I can set so new logging level will be applied when I install this chart?  

**Version of Helm and Kubernetes**:

Helm version:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

```

Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi @LorrieS ,
  I am sorry, there is not parameter to change the log4j.properties on the fly. 
  If you make the changes and want to share it, I will be glad to review and merge them.
