### ISSUE TITLE
[bitnami/supabase 2.0.1] Add kong.service.annotations

### ISSUE THREAD

**Issue by cccs-jamalhabash** [bitnami/charts#20288]
### Name and Version

bitnami/supabase 2.0.1

### What is the problem this feature will solve?

I want to deploy the Supabase helm chart on AKS with an [internal load balancer](https://learn.microsoft.com/en-us/azure/aks/internal-lb?tabs=set-service-annotations). 

To use the internal load balancer, you need to add the annotation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` to the desired service. In this case, I would like to add this annotation to the Kong service.

### What is the feature you are proposing to solve the problem?

Please add the option `kong.service.annotations`. 

This is similar to the options `auth.service.annotations`, `meta.service.annotations`, `realtime.sevice.annotations`, `rest.service.annotations`, `storage.service.annotations`, `studio.service.annotations`, which are included in the supabase chart already.

Similar changes have been made in other charts: https://github.com/bitnami/charts/issues/4205

### What alternatives have you considered?

Not using the Bitnami Supabase chart.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by cccs-jamalhabash** [comment]
Closing the issue, as feature already exists. 

Kong is a sub-chart of the Supabase chart. The [kong chart](https://github.com/bitnami/charts/tree/main/bitnami/kong#traffic-exposure-parameters) has the parameter service.annotations.
