### ISSUE TITLE
can only call getservlethandlers on a running metricsystem

### ISSUE THREAD

**Issue by nevo11** [bitnami/charts#20282]
### Name and Version

bitnami/airflow/

### What architecture are you using?

None

### What steps will reproduce the bug?

-- disconnected environment -- can't get logs out
we are are running on  openshift 4.8 
spark cluster running well
at airflow: creating spark session:
`spark = SparkSession.builder.appName...`

error at airflow log:
```
py4j.protocol.Py4JavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.IllegalArgumentException: requierment failed: can Only call getServletHandlers on a runing MetricSsytem
```
at spark master:
```
Error while invoking RpcHandler#receive() for one-way message.
Java.io.InvalidClassException: org.apache.spark.deploy.ApplicationDescription; local class incompatible: stream classdesc ...
```
the spark in use: bitnami/spark

we could not find a solution out there and we would like to understand what is going on there

thank you

**Comment by carrodher** [comment]
It appears that the issue may not be directly related to the Bitnami Airflow container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

This seems to be a unique use case that might be challenging to replicate on our end, as it appears closely tied to your particular scenario.

For inquiries about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend referring to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
