### ISSUE TITLE
[question] Label injection best practices

### ISSUE THREAD

**Issue by windmark** [bitnami/charts#2029]
**Which chart**:
Applies to all charts

**Description**
I'm developing applications with helm charts from here as subcharts and deploying them to Openshift. Openshift has a special feature that groups resources into visual applications using the `app.kubernetes.io/part-of`, but this requires the subcharts to have the label set on the highest metadata level on the resources.

Now to my question, what are the best practices for developers of helm charts regarding allowing injection of custom labels via values? I find certain inconsistencies and it would be interesting for me to know if general support of label injection would be a feature you consider.

Or is there another way using helm that I have missed?

**Comment by miguelaeh** [comment]
Hi @windmark ,
Thank you very much for open this thread.
I think you are requesting something like the `podLabels` that already exists in some Charts but the general deployment, statefulset, etc., right?
For example, you can check it in `bitnami/wildfly/values.yaml`

**Comment by windmark** [comment]
Hey @miguelaeh, exactly I mean adding the option of injection labels on all templates like deployment, pvc, secrets, svc etc to allow the implementer to be flexible in how it's used.

If we were to agree that this is something we want and decide on a naming pattern, I could create a PR to do it for all the charts in this repo. It's not that much work and easy to confirm that it's not breaking anything.

**Comment by miguelaeh** [comment]
Hi @windmark ,
First, thank you very much for offering you to contribute with that, our team really appreciates that.
Just to be sure, you want to add the labels for example here, right?:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "external-dns.fullname" . }}
  labels: {{ include "external-dns.labels" . | nindent 4 }}
    <HERE>
```

Looking to the `external-dns.labels` function, I can see the pod labels will be placed there too. I guess you want to add the labels **only** where I put the `<HERE>` but not in the pods, is this correct?
If that is what you are trying to achieve, I would say to create a new template to render the labels and add it just where I put the `<HERE>`. Do you agree with that?
Also @javsalgar what do you think?

**Comment by javsalgar** [comment]
Thanks for contributing! So, what I understand is the following. 

- You would like to add a set of labels to all of the resources regardless of the type. I'm not sure if it makes sense to have some sort of `commonLabels` value that would add the same labels to all of components. I'm hesitant to add it as a `global` value so it is included in all the subcharts.
- If not, you would like to have a labels section per component type, something like `secretLabels`, `pvcLabels`... etc. 

Currently we are in the process of standardizing the charts so I will cc @dani8art for consideration

**Comment by javsalgar** [comment]
I think that `commonLabels` and `commonAnnotations` could be an interesting feature.

**Comment by windmark** [comment]
Thank you for your quick responses! I think that `commonLabels` and `commonAnnotations ` would be a great addition to have in `values.yaml`. It's up to you if we then take it to the next step and also standardize so that `secretLabels` etc are added as well, but maybe that wouldn't hurt?

It sounds great that you are working with standardizing the charts 👍

**Comment by miguelaeh** [comment]
From me, it is fine to have both if they are useful. Nevertheless, I am not totally sure about if add labels per component add too much value, do you think it is a frequent scenario to need that?

**Comment by windmark** [comment]
> From me, it is fine to have both if they are useful. Nevertheless, I am not totally sure about if add labels per component add too much value, do you think it is a frequent scenario to need that?

I'm not sure, but if we regardless add the support for `commonLabels` maybe it's unnecessary to limit in case someone has the use case for it?

**Comment by miguelaeh** [comment]
It is just for maintain the charts as simple as possible

**Comment by miguelaeh** [comment]
Hi @windmark ,
I want to let you know that we are having this into account in our standarisation process.
Regards.

**Comment by windmark** [comment]
> Hi @windmark ,
> I want to let you know that we are having this into account in our standarisation process.
> Regards.

I'm glad to hear, thank you! Keep me in the loop if there is anything more I can contribute to.

**Comment by dani8art** [comment]
@windmark we started we #2044 as it has just one component, I guess we would only need `commonLabels` regarding this conversation.
