### ISSUE TITLE
[bitnami/kube-prometheus] Configure Prometheus Rules from a file

### ISSUE THREAD

**Issue by mohitmaheshwari31** [bitnami/charts#20310]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

I am trying to mount a folder which consist of Prometheus rules files . I tried various approach like creating the configmap and mounting it , but it is not showing up in df -h inside the container. 

There is a option to configure additionalPrometheusRules , but if there are 100s of rules, that it would impossible to manage values.yaml file. 

 
 

### What is the feature you are proposing to solve the problem?

the way we can configure the additional promethues.yaml , we should also have the way to configure prometheus Rules file not just the rules

**Comment by mohitmaheshwari31** [comment]
Please suggest if there is any workaround as well

**Comment by aoterolorenzo** [comment]
Hi @mohitmaheshwari31 ,

At the moment the only way to get it done would by using `additionalPrometheusRules`. As the amount of rules could become noisy doesn't seem to be a very common scenario, and we have no expectations of adding a feature allowing other options. Nevertheless, we are open to accept any community contributions so if you want to contribute yourself with a PR, the team will be glad to review it.
