### ISSUE TITLE
[bitnami/kube-prometheus] How to add prometheus rules file in prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0

### ISSUE THREAD

**Issue by mohitmaheshwari31** [bitnami/charts#20316]
### Name and Version

bitnami/kube-prometheus:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Can someone please guide me how we can update the prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0 with our cutomize rules path  ?

### What do you see instead?

Can we delete the crd/configmap and recreate  it after applying the helm ?
Because if i create the configmap before helm , it is not allowing to deploy prometheus server

**Comment by javsalgar** [comment]
Hi,

It seems to me that this is not related with the Bitnami packaging of kube-prometheus, rather it is more focused on the usage of kube-prometheus itself. Did you check with the upstream developers? https://github.com/prometheus-operator/prometheus-operator

**Comment by mohitmaheshwari31** [comment]
No yet. I will check with them if they can help. Thank you .
