### ISSUE TITLE
[bitnami/consul] Gossip encryption is not activated when specifying custom encryption key

### ISSUE THREAD

**Issue by daanknoope** [bitnami/charts#20327]
### Name and Version

bitnami/consul 10.13.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Generate a new gossip encryption key using `consul keygen` (`docker run -it bitnami/consul:1.16.2 consul keygen`)
2. Put this encryption key in your consul values.yaml file at `gossipKey: ""`
3. Helm install the chart
4. Inspect the beginning of the log of one of the consul pods. 

### Are you using any custom parameters or values?

`gossipKey: "DVoLa/k99hfBEdIfCLkzSpWg4obElLYVIFDsutKCL/w="`

### What is the expected behavior?

The expected behaviour would be for Consul to start up and show it is using Gossip Encryption.

### What do you see instead?

Consul will start without enabling gossip encryption. It says `Gossip Encryption: false` in the logging:

```
consul 16:53:14.62
consul 16:53:14.62 Welcome to the Bitnami consul container
consul 16:53:14.62 Subscribe to project updates by watching https://github.com/bitnami/containers
consul 16:53:14.62 Submit issues and feature requests at https://github.com/bitnami/containers/issues
consul 16:53:14.62
consul 16:53:14.62 INFO  ==> ** Starting Consul setup **
consul 16:53:14.63 INFO  ==> Validating settings in CONSUL_* env vars..
consul 16:53:14.64 INFO  ==> Initializing Consul...
consul 16:53:14.64 INFO  ==> Deploying consul with persisted data...
consul 16:53:14.64 INFO  ==> No injected configuration files found. Creating default config files...
find: '/docker-entrypoint-initdb.d/': No such file or directory
consul 16:53:14.64 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
consul 16:53:14.64 INFO  ==> ** Consul setup finished! **

consul 16:53:14.65 INFO  ==> ** Starting Consul **
==> Starting Consul agent...
               Version: '1.16.2'
            Build Date: '2023-09-19 19:29:18 +0000 UTC'
               Node ID: 'ea2d2de0-8108-d2e6-3b75-8f56850933db'
             Node name: 'consul-pr-0'
            Datacenter: 'dc1' (Segment: '<all>')
                Server: true (Bootstrap: false)
           Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, gRPC-TLS: 8503, DNS: 8600)
          Cluster Addr: 10.1.0.40 (LAN: 8301, WAN: 8302)
     Gossip Encryption: false
      Auto-Encrypt-TLS: false
           ACL Enabled: false
     Reporting Enabled: false
    ACL Default Policy: allow
             HTTPS TLS: Verify Incoming: false, Verify Outgoing: false, Min Version: TLSv1_2
              gRPC TLS: Verify Incoming: false, Min Version: TLSv1_2
      Internal RPC TLS: Verify Incoming: false, Verify Outgoing: false (Verify Hostname: false), Min Version: TLSv1_2
```

### Additional information

This is caused by a missing `CONSUL_GOSSIP_ENCRYPTION="yes"` environment variable. I'm preparing a PR.

When the PR is merged, the chart will still fail until https://github.com/bitnami/containers/issues/51959 is resolved by merging https://github.com/bitnami/containers/pull/51982

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
