### ISSUE TITLE
[postgres-ha] unable to recover when primary pod is other than 0

### ISSUE THREAD

**Issue by svilensabev** [bitnami/charts#2033]
**Which chart**:

name: postgresql-ha
version: 1.4.8

**Description**

I found an interesting scenario where `postgres-ha` is unable to start/recover after update of helm chart with modified `replicaCount`.

It happens to me during failover tests of latest chart version. First I delete manually primary pod so that `repmgr` promote another replica to be the primary pod like `postgresql-ha-postgresql-1`.

:thinking: :thought_balloon: Thinking that we may need another replica that serves as a witness in such conditions,

OR being able to promote itself as primary if no other postgres pods are running.

This issue https://github.com/bitnami/charts/issues/1934 seems same behavior to me but it was fixed by bumping pg-pool image version.

Thanks for all the effort here. This chart could be splendid!

**Steps to reproduce the issue:**

1. Start `postgres-ha` chart with `2 replicas` using following `values.yaml`

```
---
  postgresql:
    username: postgres
    password: superuserpass
    database: app
    repmgrUsername: repmgr
    repmgrPassword: repmgrpass
    replicaCount: 2
  postgresqlImage:
    debug: true

  pgpool:
    adminPassword: pgpoolpass
    replicaCount: 2
```

2. Wait for pods to started

```
kubectl rollout status sts --namespace=postgresql-ha postgresql-ha-postgresql
```

3. Manually delete `postgresql-ha-postgresql-0` which has the primary role

```
kubectl delete po --namespace=postgresql-ha postgresql-ha-postgresql-0
```

4. Wait for deleted pod to be recreated

```
kubectl rollout status sts --namespace=postgresql-ha postgresql-ha-postgresql
```

5. Check which pod has the primary role using `repmgr`. I login to `postgresql-ha-postgresql-0` as user `postgres` which I manually created in order to run `repmgr` commands inside this non-root container.

```
postgres@postgresql-ha-postgresql-0:/$ repmgr cluster show -f /opt/bitnami/repmgr/conf/repmgr.conf --compact
 ID   | Name                       | Role    | Status    | Upstream                   | Location | Prio. | TLI
------+----------------------------+---------+-----------+----------------------------+----------+-------+-----
 1000 | postgresql-ha-postgresql-0 | standby |   running | postgresql-ha-postgresql-1 | default  | 100   | 2
 1001 | postgresql-ha-postgresql-1 | primary | * running |                            | default  | 100   | 2
```

6. Update helm chart to use `1 replica only`. Kubernetes first delete pod with index 1, then delete pod with index 0, and when it starts the new pod with index 0 it fails to recover forever with following message

```
[2020-03-11 12:06:18] [DETAIL] attempted to connect using:
user=repmgr password=repmgrpass connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.postgresql-ha.svc.cluster.local port=5432 fallback_application_name=repmgr
[2020-03-11 12:06:18] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2020-03-11 12:06:18] [HINT] upstream node must be running before repmgrd can start
```

At this moment, I think that repmgr on pod-0 is looking for pod-1 which was the last promoted primary, but since pod-1 does not exist, there is a missing logic for pod-0 to promote itself as primary.

**Describe the results you received:**

After scale out, the postgresql pod is continuously restarting without opportunity to promote itself as primary. Server is unreachable and I was unable to recover even using `existingClaim` or `pdb: true`

**Describe the results you expected:**

The postgresql server to remain in working condition with pod-0 as primary role.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Helm 2 using Rancher v2.3.5
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by svilensabev** [comment]
Ok, the trick so far for me was to set `postgresql.updateStrategyType: OnDelete`. This way pod-0 is not manually deleted during helm upgrade.

Also, a good workaround is to scale down to only 1 postgresql pod using `kubectl scale` before any helm upgrade tasks. By doing that, the pod-0 will be promoted to primary. It might be good to be part of chart documentation if its a rule.

**Comment by dani8art** [comment]
Hi @svilensabev, thank you for this feedback we really appreciate it. It seems you found a workaround for this specific scenario and I've checked that it is working fine for me too. I also confirmed that doesn't matter how many replicas you have in the beginning it happens always I've tried the following:

```bash
## Install cluster from scratch
$ helm install pg \
  --set postgresql.replicaCount=4 \
  --set pgpool.replicaCount=2 \
  bitnami/postgresql-ha

## Force primary node rotation
$ kubectl delete po  pg-postgresql-ha-postgresql-0

## Wait until is finished
$ kubectl rollout status sts pg-postgresql-ha-postgresql

## Get deployment info
$ export PGPOOL_PASSWORD=$(kubectl get secret pg-postgresql-ha-pgpool -o jsonpath="{.data.admin-password}" | base64 --decode)
$ export POSTGRES_PASSWORD=$(kubectl get secret pg-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ export REPMGR_PASSWORD=$(kubectl get secret pg-postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

## Upgrade the cluster size
$ helm upgrade pg \
  --set postgresql.replicaCount=1 \
  --set postgresql.password="$POSTGRES_PASSWORD" \
  --set postgresql.repmgrPassword="$REPMGR_PASSWORD" \
  --set pgpool.replicaCount=2 \
  --set pgpool.adminPassword="$PGPOOL_PASSWORD" \
  bitnami/postgresql-ha
```

I think it is caused when the primary node is not the last to be removed so I would say a primary node is not being gracefully removed and the cluster doesn't know how to work. Do you think it could be that?

**Comment by svilensabev** [comment]
@dani8art Thanks for confirmation that you reproduced this issue.

> I think it is caused when the primary node is not the last to be removed so I would say a primary node is not being gracefully removed and the cluster doesn't know how to work.

Yes, exactly.

**Comment by stv0g** [comment]
I ran into the same issue. I assume this could be solved by running `repmgr -f /etc/repmgr.conf standby promote` inside the primary pod to regain its primary status

**Comment by stv0g** [comment]
But I'm lacking the knowledege to run this insude the shortlived pod before it gets killed :(

**Comment by dani8art** [comment]
@stv0g but what we actually want to make the primary node left its primary status before it gets killed, don't we?

**Comment by svilensabev** [comment]
@dani8art That's a good point.

Perhaps we could introduce `preStop` event as described here.

> Kubernetes sends the preStop event immediately before the Container is terminated. Kubernetes’ management of the Container blocks until the preStop handler completes, unless the Pod’s grace period expires.

https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by stv0g** [comment]
> @stv0g but what we actually want to make the primary node left its primary status before it gets killed, don't we?

In my case the primary node died before it could pass its role to a seconday..

**Comment by dani8art** [comment]
So I'm looking for a command in `repmgr` that fit our requirements it seems to there be one that could help us. 
 - `repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf primary unregister`

I will try doing `unregister` command, however, if you know a better way of doing that, please don't hesitate to tell me.

**Comment by stv0g** [comment]
@dani8art What happens if the primary node dies before it can unregister?

In my case I lost the PV of the primary node..

**Comment by marcosbc** [comment]
@stv0g You can check the `readinessProbe` and `livenessProbe` options, to disable (or increase) the health check.
