### ISSUE TITLE
[redis] Long startup and readiness probe

### ISSUE THREAD

**Issue by ggtools** [bitnami/charts#2034]
**Which chart**:

redis-10.5.7

**Description**

On a redis instance with 20+GiB the initial AOF file loading can be quite long especially if the AOF file hasn't been rewritten for a while. As a consequence, the readinessprobe fails, the server is killed and we enter in an endless loop. One solution is to increase the initial delay to something *high enough* but this introduce another issue as the service won't be available before the end of the initial delay even if Redis is actually accepting the connections.

**Steps to reproduce the issue:**

Crash loop:
1. Load a Redis instance (single server, no slave, no sentinel) with 20Gib+ of data
2. Kill the pod

Service not available
0. Start a fresh redis instance (no AOF data needed)
1. Extend the initial delay to something quite high
2. Update the helm release

**Describe the results you received:**

If the server takes more than 30 seconds to restart, the readiness probe will fail and trigger a server restart.

With extended initialDelay, the Redis server will be ready to listen but it won't be accessible using the service.

**Describe the results you expected:**

No crash and redis available through the service as soon as it is ready to listen.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dani8art** [comment]
Hi @ggtools, I don't know if you already did but you can also try to play with `failureThreshold` to increase the number of attempts before restarting the pods 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes

**Comment by ggtools** [comment]
I'm going to try something with:

- periodSeconds: 20
- failureThreshold: 200

Looks a bit weird to me to allow that many failures but should do the trick.

**Comment by tsutsu** [comment]
Can this issue now be solved "the right way" by adding a `startupProbe`?

**Comment by juan131** [comment]
Correct @tsutsu !

We have an opened task to include startup probes parameters on every chart, but we didn't have the chance to work on that yet. I expect that Redis (and the rest of the chart in the catalog) will include them in the next few weeks.

**Comment by qdumouli** [comment]
Hello, 

@juan131 has this been looked at to include the startupProbe ? It would be really helpful to have it !

Thanks

**Comment by juan131** [comment]
Hi @qdumouli 

Sorry we didn't have time to work on that yet. 

Please feel free to submit a PR adding it to Redis if it's blocking you. You can use MongoDB as a reference, since it already has support for this parameter:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb
