### ISSUE TITLE
[bitnami/sftpgo] Add helm chart

### ISSUE THREAD

**Issue by willzhang** [bitnami/charts#20346]
### Name and Version

bitnami/sftpgo v2.5.4

### What is the problem this feature will solve?

Add sftpgo helm chart

https://github.com/drakkan/sftpgo/blob/main/docker/README.md

### What is the feature you are proposing to solve the problem?

sftpgo no official helm chart

### What alternatives have you considered?

This sftpgo helm chart not support persistent: https://github.com/sagikazarmark/helm-charts/tree/master/charts/sftpgo

**Comment by javsalgar** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources that could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
