### ISSUE TITLE
[bitnami/gitea] need SSH_DOMAIN

### ISSUE THREAD

**Issue by willzhang** [bitnami/charts#20349]
### Name and Version

bitnami/gitea 1.0.6

### What is the problem this feature will solve?

when exposed with _nodeport_, there is `root_url`, but no `ssh_domain`
```
--set ROOT_URL=http://<node-ip>:<node-port> \
--set SSH_DOMAIN= ?
```

### What is the feature you are proposing to solve the problem?

when exposed with _nodeport_,  can not cloud with ssh

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
