### ISSUE TITLE
Want a tool to generate helm application templates with one click

### ISSUE THREAD

**Issue by hamishliu** [bitnami/charts#20350]
### Name and Version

https://github.com/bitnami/charts/tree/main/template/CHART_NAME

### What is the problem this feature will solve?

Hi

I like bitnami’s helm charts template specification very much. I also noticed that bitnami officially provides a general helm charts template. Any application charts package can be created based on this template.

I carefully read the template https://github.com/bitnami/charts/tree/main/template/CHART_NAME. There are many placeholders in it that need to be replaced based on customized application information. Is there any tool that can be used based on this? This template and specific parameters generate helm charts with one click. How do you implement it internally? Shouldn't the replacement be written manually?

thanks

### What is the feature you are proposing to solve the problem?

Provide tool scripts to quickly generate your own application charts

**Comment by carrodher** [comment]
Hi, Thank you for bringing this issue to our attention. Unfortunately, we don't have such a tool and have no plans to develop it in the short term. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. 
The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by hamishliu** [comment]
ok

**Comment by stepanselyuk** [comment]
These scripts can be used:

prepare-placeholders-config.sh
```
#!/usr/bin/env bash

echo 'placeholders:' | tee placeholders.yaml

grep -RPo '%%[^%]+%%' . \
 | awk -F: '{print $2}' \
 | sort \
 | uniq \
 | xargs -I{} bash -c 'grep -Rn "{}" . | while read -r tpl; do echo "    # $tpl"; done; echo -e "  - tpl: \047{}\047\n    value: \047{}\047"; echo' \
 | tee -a placeholders.yaml
```

replace-placeholders.sh:
```
#!/usr/bin/env bash

# Check if yq is installed (yq is used for parsing YAML)
if ! command -v yq &> /dev/null
then
    echo "yq could not be found. Please install yq."
    exit
fi

# Directory containing files to process
TARGET_DIR="."

# Read and replace placeholders
while IFS= read -r line
do

    # echo "line: $line"
    # Extract template and value
    TEMPLATE=$(awk 'BEGIN { FS=":::" } {print $1}' <<<"$line")
    VALUE=$(awk 'BEGIN { FS=":::" } {print $2}' <<<"$line")

    #echo "tpl: $TEMPLATE"
    #echo "value: $VALUE"
    #continue

    if [[ "$TEMPLATE" == "$VALUE" ]]
    then
        # echo "Skipping $TEMPLATE as it has the same value."
        continue
    fi

    # Use find to recursively locate files and sed to replace the placeholder
    find "$TARGET_DIR" -type f ! -name 'placeholders.yaml' -exec sed -i "s|${TEMPLATE}|${VALUE}|g" {} +

    echo "Replaced '$TEMPLATE' with '$VALUE'."

done < <(yq e '.placeholders[] | [.tpl, .value] | .[]' "placeholders.yaml" | sed 'N;s/\n/:::/')

echo "Replacement complete."
```

cc @carrodher 
I can create a PR.
