### ISSUE TITLE
[kafka] add annotations for Pod Template in kubernetes Deployment

### ISSUE THREAD

**Issue by MaciekRR** [bitnami/charts#2036]
**Which chart**:
Kafka
**Description**
It turned out that to use DataDog auto-discovery feature (https://docs.datadoghq.com/agent/autodiscovery/), there must be annotations added to "Pod Template" section in kubernetes deployment.yaml. This will cause all pods created will have these annotations added.
Currently `metrics.kafka.annotations` adds only annotations on top level of deployment.yaml.

**What you expect to happen**
Pods created (kafka exporter) have annotations added

**Comment by dani8art** [comment]
Hi @MaciekRR, if I understand well you would like to have annotations for every `kafka-exporter` pod, right? a field like `metrics.kafka.podAnnotations` could be fine then, right?

**Comment by MaciekRR** [comment]
yes, right, every pod created needs to have these annotations. "metrics.kafka.podAnnotations" would be perfect here.

**Comment by dani8art** [comment]
Hi @MaciekRR I've created a PR adding this new field, feel free to take a look and add your thought there. Thank you.

**Comment by MaciekRR** [comment]
Thank you for resolving this issue so fast :)
