### ISSUE TITLE
[bitnami/keycloak] is external infinispan cache configuration supported?

### ISSUE THREAD

**Issue by thetoolsmith** [bitnami/charts#20368]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

We are looking to externalize the infinispan cache. Is there any preconfigured hooks for doing this with Bitnami/keycloak?

### What is the feature you are proposing to solve the problem?

making an initial inquiry only

### What alternatives have you considered?

none yet

**Comment by javsalgar** [comment]
I'm afraid there's currently no option to do it out of the box. You could try using the extraVolumes and extraVolumeMounts section to mount a volume for the cache. Would that work for your use case?

**Comment by jwklijnsma** [comment]
i will like to add this helmchart we have it working for version 23
