### ISSUE TITLE
[bitnami/kafka] Unable to disable controller based external access

### ISSUE THREAD

**Issue by HassanHashemi** [bitnami/charts#20364]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

run following command:
```
helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka  --set externalAccess.enabled=true --set externalAccess.service.type=NodePort --set externalAccess.broker.service.externalIPs[0]='192.168.1.2' --set externalAccess.broker.service.externalIPs[1]='192.168.1.3' --set externalAccess.broker.service.externalIPs[2]='192.168.1.3' --set broker.readinessProbe.initialDelaySeconds=30 --set zookeeper.enabled=true --set kraft.enabled=false --set broker.replicaCount=3 --set controller.replicaCount=0
```
### What do you see instead?
```
kafka: externalAccess.controller.service.loadBalancerNames or externalAccess.controller.service.loadBalancerIPs
    By specifying "externalAccess.enabled=true", "externalAccess.autoDiscovery.enabled=false" and
    "externalAccess.controller.service.type=LoadBalancer" at least one of externalAccess.controller.service.loadBalancerNames
    or externalAccess.controller.service.loadBalancerIPs  must be set and the length of those arrays must be equal
    to the number of replicas.
```

**Comment by carrodher** [comment]
Could you follow the instructions in the error message?
> By specifying `externalAccess.enabled=true`, `externalAccess.autoDiscovery.enabled=false` and
`externalAccess.controller.service.type=LoadBalancer` at least one of `externalAccess.controller.service.loadBalancerNames` or `externalAccess.controller.service.loadBalancerIPs` must be set and the length of those arrays must be equal to the number of replicas.

Does the issue persist once configured as suggested?
