### ISSUE TITLE
[bitnami/milvus]milvus cannot startup when deployed in the same namespace with external minio

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#20396]
### Name and Version

bitnami/milvus:3.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

1. deploy bitnami/etcd helm chart in namespace ns-ext
2. deploy bitnami/minio helm chart in namespace ns-ext
3. deploy bitnami/milvus helm chart in namespace ns-ext with connecting the external etcd & minio in same namespace
4. milvus cannot startup

### Are you using any custom parameters or values?

![image](https://github.com/bitnami/charts/assets/45187622/4f536572-4be0-4774-b449-4ec73dfcedc5)

### What is the expected behavior?

no matter milvus deployed in same or different namespace with etcd & minio, milvus should startup

### What do you see instead?

1. if milvus deployed in the same namespace with etcd & minio, milvus cannot startup
![image](https://github.com/bitnami/charts/assets/45187622/2e3d71e5-dba3-4de6-b0df-868faf557ee2)
![image](https://github.com/bitnami/charts/assets/45187622/a2f750f0-3d7d-4779-bb85-4510b4b6bec4)

2. if imilvus deployed in a different namespace from etcd & minio, milvus can startup

### Additional information

when disable serviceLinks in all the deployment.yaml, then milvus can deployed in the same/different namespace with etcd & minio
![image](https://github.com/bitnami/charts/assets/45187622/5a32d773-7fb5-44ad-9375-cfd362f960f8)
so can add a field "enableServiceLinks" in the main value.yaml then apply it to all the deployment.yaml files

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by chenraoCR** [comment]
sure, can create a PR
