### ISSUE TITLE
[bitnami/nginx] Allow to completely replace the Nginx configuration

### ISSUE THREAD

**Issue by KIVagant** [bitnami/charts#2039]
**Which chart**:

bitnami/nginx

**Description**

It would be nice to be able to completely replace the default nginx configuration with a fully customized config (which would work well together with https://github.com/bitnami/charts/issues/1591).

**Comment by miguelaeh** [comment]
Hi @KIVagant ,
Thank you very much for your feedback.
Would you like to create a PR for that purpose?

**Comment by KIVagant** [comment]
Yes, why not. I already patched your great Helm chart to support a volume with http basic secret, so I will try to find time to add this feature as well and prepare a PR. But if I disappear, disgrace me.

**Comment by miguelaeh** [comment]
Thank you very much!!!!
We really apreciate the contributions to our repositories.
