### ISSUE TITLE
[bitnami/milvus]waitForS3InitContainer miss s3 port when connect external s3

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#20398]
### Name and Version

bitnami/milvus:3.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

1. deploy external minio with default port 9000
2. deploy milvus to connect external minio

### Are you using any custom parameters or values?

![image](https://github.com/bitnami/charts/assets/45187622/8ec4d01b-4471-4194-ae0a-a071ade10cb9)

### What is the expected behavior?

milvus could connect minio and startup normally

### What do you see instead?

milvus waitForS3InitContainer cannot connect minio, failed
![image](https://github.com/bitnami/charts/assets/45187622/fbe769cc-dd61-425f-b2cc-4815fc800e4f)

### Additional information

in waitForS3InitContainer, the minio address, just has host, not contains the port, so cannot connect external minio
![image](https://github.com/bitnami/charts/assets/45187622/fb7f120d-c952-458a-8259-dfc29aaee8e5)
![image](https://github.com/bitnami/charts/assets/45187622/6b5925db-d93a-4dc6-9eda-14b7a19916f9)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
