### ISSUE TITLE
Support for customPlugin

### ISSUE THREAD

**Issue by raji032** [bitnami/charts#20414]
### Name and Version

bitnami/apisix

### What is the problem this feature will solve?

Parameters missing in the values.yaml for adding customPlugins

### What is the feature you are proposing to solve the problem?

Ability to add custom built plugins to apisix

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by raji032** [comment]
Can you let me know if the option is available in Production version. Thanks.

**Comment by carrodher** [comment]
There are some plugins added to the default configuration, see https://github.com/bitnami/charts/blob/main/bitnami/apisix/values.yaml#L1592
