### ISSUE TITLE
Question: What tool does Bitnami use to generate documentation for its charts? Is this tool available to the community?

### ISSUE THREAD

**Issue by evsasha** [bitnami/charts#20415]
### Name and Version

bitnami/wordpres 1.2.3

### What is the problem this feature will solve?

I can't find in the documentation what tool is used to generate the README for Bitnami charts. Is this tool available to the community?

I need to make slight modifications to the Bitnami chart for my own purposes and I want to keep the documentation for the chart up to date.

Currently, I have to either update the documentation manually or use alternative tools.

### What is the feature you are proposing to solve the problem?

Make the tool for generating documentation for Bitnami charts available to the community.

### What alternatives have you considered?

[terr](https://github.com/norwoodj/helm-docs)

**Comment by carrodher** [comment]
The table with the different values is automatically generated by using https://github.com/bitnami-labs/readme-generator-for-helm, other content in the README files is not automated.

**Comment by evsasha** [comment]
@carrodher Thank you, that's exactly what I needed. My question is resolved.
