### ISSUE TITLE
[bitnami/external-dns] your releasing system seems to be failing

### ISSUE THREAD

**Issue by julian3xl** [bitnami/charts#2041]
**Which chart**:

bitnami/external-dns (2.20.4)

**Description**

Yesterday you merged my PR fixing one problem with the new 0.7.0 external-dns version and it was bumped to 2.20.4. That release doesn't reflect the changes I fixed with my PR, but they already are at HEAD.

**Steps to reproduce the issue:**

1. helm pull bitnami/external-dns
2. tar xvfz external-dns-2.20.4.tgz
3. cat external-dns/templates/clusterrole.yaml
4. Compare it with https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/clusterrole.yaml

You should see this change https://github.com/bitnami/charts/commit/97af92a390de3742199153841ad1764125bb1bce

**Comment by julian3xl** [comment]
@miguelaeh please, if you could check this that will be awesome, thanks in advance!

**Comment by miguelaeh** [comment]
Hi @julian3xl ,
Have in mind the chart needs to go through our internal pipeline before the release. It is needed wait some time for the repository to be updated. I already launched the jobs manually and they are in progress..

**Comment by julian3xl** [comment]
then why 2.20.4 is available?

**Comment by miguelaeh** [comment]
Hi @julian3xl ,
It seems in the history that just before merging your changes there was a release for the 2.20.4 version. Now the version 2.20.5 has been released and your changes appeared.
What I don't understand is why it didn't give a conflict. Le me continue checking it

**Comment by julian3xl** [comment]
Ah!!!, that makes sense! Thanks so much @miguelaeh
