### ISSUE TITLE
type error when setting servicemonitor endpoint port

### ISSUE THREAD

**Issue by Ognian** [bitnami/charts#20418]
### Name and Version

bitnami/keycloak 17.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

setting the port value of a service monitor endpoint results in a helm error:
```
Error: UPGRADE FAILED: cannot patch "keycloak" with kind ServiceMonitor: ServiceMonitor.monitoring.coreos.com "keycloak" is invalid: spec.endpoints[0].port: Invalid value: "integer": spec.endpoints[0].port in body must be of type string: "integer"
```
due to: https://github.com/bitnami/charts/blob/1056ea2f48bb0165b01df4550205ed5c7092c0c0/bitnami/keycloak/templates/servicemonitor.yaml#L27
change the above line from:
`    - port: {{ $endpoint.port }}`
to:
`    - port: {{ $endpoint.port | quote }}`

Thanks, Ognian

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
