### ISSUE TITLE
[rabbitmq] not applying username and password

### ISSUE THREAD

**Issue by varspare** [bitnami/charts#2043]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Which chart**:

Rabbitmq version: 6.18.9 

**Description**

Override username and password apply to the configuration file but do not take effect in the rabbitmq-server when it runs

**Steps to reproduce the issue:**
1. helm repo add bitnami https://charts.bitnami.com/bitnami

2. helm install rabbitmq bitnami/rabbitmq --set rabbitmq.username=admin,RABBITMQ_USER=admin,rabbitmq.password=secretpassword,rabbitmq.erlangCookie=secretcookie

3. kubectl exec -it rabbitmq-0 /bin/bash

4. rabbitmq@rabbitmq-0:/$ head -n3 /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
##username and password
default_user=admin
default_pass=secretpassword

5. rabbitmq@rabbitmq-0:/$ rabbitmqctl authenticate_user admin secretpassword
Authenticating user "admin" ...
Error:
Error: failed to authenticate user "admin"
user 'admin' - invalid credentials

6. rabbitmq@rabbitmq-0:/$ rabbitmqctl list_users
Listing users ...
user	tags
mquser	[administrator]

7. rabbitmq@rabbitmq-0:/$ rabbitmqctl authenticate_user mquser secretpassword
Authenticating user "mquser" ...
Error:
Error: failed to authenticate user "mquser"
user 'mquser' - invalid credentials
 

**Describe the results you received:**

Unable to authenticate with the username/password set via the helm install command
Steps 4-7 above

**Describe the results you expected:**

Expect to be able to authenticate with the username and password set via the helm install command

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by embcla** [comment]
I've seen this when I decided to change the password and I upgraded the helm release.

But when I removed and reinstalled it did work, but I used a value files. Have you tried that?

**Comment by varspare** [comment]
No I've only tried via the set command

**Comment by rafariossaa** [comment]
Hi,
  Could it by a typo in the step 2 you indicate ?
  It should be something like:
```helm install my-release \
  --set rabbitmq.username=admin,rabbitmq.password=secretpassword,rabbitmq.erlangCookie=secretcookie \
    bitnami/rabbitmq```

**Comment by varspare** [comment]
> Hi,
> Could it by a typo in the step 2 you indicate ?
> It should be something like:
> 
> ```
>   --set rabbitmq.username=admin,rabbitmq.password=secretpassword,rabbitmq.erlangCookie=secretcookie \
>     bitnami/rabbitmq```
> ```

I don't think so, since I can see them making it inside the running container and appearing in the configuration file. All those commands in the report have been copy and pasted.

**Comment by rafariossaa** [comment]
Hi, 
  Could you delete the installed chart and the pvc created and try it again ?
  I can't reproduce it running on a amazon kubernetes cluster:

```I have no name!@rabbitmq-0:/$  head -n3 /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
##username and password
default_user=admin
default_pass=secretpassword
I have no name!@rabbitmq-0:/$ rabbitmqctl authenticate_user admin secretpassword
Authenticating user "admin" ...
Success
```
  Which kubernetes cluster are you using ?

**Comment by varspare** [comment]
> Hi,
> Could you delete the installed chart and the pvc created and try it again ?
> I can't reproduce it running on a amazon kubernetes cluster:
> 
> ```
> I have no name!@rabbitmq-0:/$  head -n3 /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf
> ##username and password
> default_user=admin
> default_pass=secretpassword
> 
> I have no name!@rabbitmq-0:/$ rabbitmqctl authenticate_user admin secretpassword
> Authenticating user "admin" ...
> Success
> ```
> 
> Which kubernetes cluster are you using ?

I'm running against Azure Kubernetes (AKS) 

But I think you've found it I haven't previously deleted the pvc, after doing so it worked. I'll keep testing to make sure and confirm here.

**Comment by varspare** [comment]
@rafariossaa 
Thank you, it was the pre-existing PVC which was preventing the new credentials applying, I've added a step to delete the PVC as part of deployments when credentials change- not ideal but I'm guessing there is very little we can do to change that.

**Comment by lindhe** [comment]
Which version of the rabbitmq chart will this fix be in? I'm running 6.23.0 and experiencing the same issue.

**Comment by embcla** [comment]
@lindhe have you deleted the PVC before (re) installing the chart? That fixes the issue

**Comment by lindhe** [comment]
Oh, right. No I did not – I had misunderstood the solution.

If I recall correctly, Helm 3 has no way to delete PVC on uninstall. Does this mean that there will *always* be a manual step after uninstallation? That's not terribly neat...
