### ISSUE TITLE
[postgresql] Add kube deployment to chart.

### ISSUE THREAD

**Issue by atzawada** [bitnami/charts#2045]
Is there any way we can get a Kubernetes deployment file created for this chart repo? I am trying to create a pg deployment where I can scale down to 0 instances when necessary.

**Comment by miguelaeh** [comment]
Hi @atzawada ,
I am not sure about what do you need, are you looking for a YAML file containing only the deployment? In that case, you can obtain something similar using the `helm template` command, but you will need to modify that deployment to be valid. 
If that is not what you are looking for plsease provide us more information.
