### ISSUE TITLE
[wordpress] reinitialize database

### ISSUE THREAD

**Issue by polRk** [bitnami/charts#2047]
```
mysql-c TRACE [execute] Result: {"code":1,"stdout":"","stderr":"ERROR 1062 (23000) at line 1: Duplicate entry 'mail_from' for key 'option_name'\n"}
Error executing 'postInstallation': MySQL command failed to run. Error:
 ERROR 1062 (23000) at line 1: Duplicate entry 'mail_from' for key 'option_name'

nami    TRACE Error: Error executing 'postInstallation': MySQL command failed to run. Error:
 ERROR 1062 (23000) at line 1: Duplicate entry 'mail_from' for key 'option_name'
```

**Comment by juan131** [comment]
Hi @polRk 

Could you please provide a little more context about this issue? How can I reproduce it?

**Comment by polRk** [comment]
Yes, if something went wrong, kubernetes starts restarting the module (or deployment), but the database was already initialized at the previous launch. You should not cause an error if the database was initialized or contains data. 
!IMPORTANT
I create helm release with **skipInstall = false**!
Your script initialized database, insert data. But if something goes wrong in the next steps, kubernetes restart the deployment, and i see an error 
```Duplicate entry 'mail_from' for key 'option_name'```

**Comment by juan131** [comment]
Hi @polRk 

The current logic assumes that, at least, during the 1st boot everything works. I mean, WordPress is initialised successfully. Once the 1st boot works, the WP container creates a flag in the "persisted directory" that allows WP to know that it doesn't need to configure WP from scratch, but reuse the persisted data instead.

**Comment by polRk** [comment]
Then why did I get this error ? Anyway, I'm running a script that checks for database availability before running the helm chart and set right flags

**Comment by juan131** [comment]
Because stth went wrong during the 1st boot, and WP didn't create the flag. Therefore, it assumes it needs to install WP again. However, the database was already populated with some data and, therefore, the conflict.
