### ISSUE TITLE
[bitnami/rabbitmq] RabbitMQ chart is ignoring RABBITMQ_PASSWORD value, taking default_password instead

### ISSUE THREAD

**Issue by thedusansky** [bitnami/charts#20477]
### Name and Version

bitnami/rabbitmq 12.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi team, 

I'm trying to deploy the RMQ helm chart onto the Cluster. I left the auth.password value to some dummy value. 

We are using a mechanism to fetch the sensitive passwords from AWS SSM, by creating SecretProviderClass and secret which is mounting into the pod. Hence I changed the StatefulSet definition a bit:

            - name: RABBITMQ_PASSWORD
              {{- if .Values.mountSecretFromSecretManager }}
              valueFrom:
                secretKeyRef:
                  name: cbpm-rabbitmq
                  key: rabbitmq-password              
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rabbitmq.secretPasswordName" . }}
                  key: rabbitmq-password
              {{- end }}

At the end, this env has indeed the value it's supposed to, I've checked it also while I was on the pod. However, I've noticed that liveness/readiness fails - 

_HTTP access denied: user 'myuser' - invalid credentials_

For me the probe definition looks fine:

- curl -f --user {{ .Values.auth.username }}:$RABBITMQ_PASSWORD 127.0.0.1:{{ .Values.containerPorts.manager }}/api/health/checks/virtual-hosts

However when I wanted to trigger the probe manually from the pod, I've noticed that indeed it's not working but working with default_password value! 
For me, it's quite confusing. I thought that RABBITMQ_PASSWORD is indeed the password, hence all those efforts to protect it. Now I've found out that actually the default_password in configurations block, is taking priority over it and I cannot find any simple mechanism for how to protect it too. 
I want the RMQ to have the password value that I've set, not any random (secure.password). Is there any way to achieve this without putting a password into the code?

Many thank
Dusan

### Are you using any custom parameters or values?

Important ones are mentioned

### What do you see instead?

RMQ chart is failing since it's only use default_password value instead of RABBITMQ_PASSWORD

**Comment by javsalgar** [comment]
Hi,

If I understood correctly, you deployed with an initial value but then changed the password to a new one taken from a secret, is that correct? I'm afraid that passwords are currently set at first boot, so probably the new password was not taken.

**Comment by thedusansky** [comment]
Hi @javsalgar , 

Thank you for the prompt response. 
I've managed to fix the issue in the meantime. I've put some dummy value like "Changeme1234" for the auth.password. 
I thought this value is irrelevant since I inject the value for RABBITMQ_PASSWORD in a different way. 
I have know other concern - 
We use NFS for persistent storage (AWS EFS). It works just fine, everything is bounded. Even if I delete the whole RMQ instance (including PVC & PV), and deploy the chart again, it persist all the queues etc that I've created before. 
However, once I want to change the password, the same issue as above appears. It looks like RMQ somehow stores this credentials config on the persistent storage and can't update it afterward? 
My question would be, is there a way to change the initial password when we use persistence? 

Many thanks! 
Dusan

**Comment by rafariossaa** [comment]
Hi,
  This worked for me, could you give it a try ?

```bash
# Deploy the chart with an initial password
$ helm install myrabbit bitnami/rabbitmq --set auth.password=test

# Once deployed I got into the pod and changed the password
$ kubectl exec -it myrabbit-rabbitmq-0  -- bash

I have no name!@myrabbit-rabbitmq-0:/$ rabbitmqctl change_password user testnew
Changing password for user "user" ...
I have no name!@myrabbit-rabbitmq-0:/$


# Get the erlang cookie
$ echo "ErLang Cookie : $(kubectl get secret --namespace default myrabbit-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 -d)"
ErLang Cookie : S4w5BmATpHLUxXoF7g97GHjuO3KO7df5

# Delete the deployment (the PVC will persist and won't be deleted)
$ helm delete myrabbit 
release "myrabbit" uninstalled


# Redeploy with the same name, you would need to indicate the previous values for the password and cookie
$ helm install myrabbit bitnami/rabbitmq --set auth.password=testnew --set auth.erlangCookie=S4w5BmATpHLUxXoF7g97GHjuO3KO7df5

# Get into the pod again and check the authentication
$ kubectl exec -it myrabbit-rabbitmq-0  -- bash

I have no name!@myrabbit-rabbitmq-0:/$ rabbitmqctl authenticate_user user testnew
Authenticating user "user" ...
Success
```

**Comment by abhchand** [comment]
@rafariossaa - this will work, but is there a way to avoid having to enter the container to set this manually?

In your own example, you set `auth.password=test` and later modify it to `testnew`. Is there a way to just set it to `test` from the start? Feels like `auth.password` is not a useful option if you have to manually update it.

Thanks!

**Comment by rafariossaa** [comment]
Hi @thedusansky, did you have the chance to try what I indicated ?
