### ISSUE TITLE
[bitnami/redis-cluster] how to use Azure Disk for AKS having version 1.27

### ISSUE THREAD

**Issue by sumanthkumarc22** [bitnami/charts#20488]
### Name and Version

bitnami/redis-cluster 7.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

In dev environment , deployed the redis cluster.
i am getting "  Warning  FailedAttachVolume  10s (x2 over 2m11s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-***************" : timed out waiting for external-attacher of disk.csi.azure.com CSI driver to attach volume resourceID.

present i am using the AKS cluster with version 1.27.3
while referring to the Kubernetes document "https://kubernetes.io/docs/concepts/storage/persistent-volumes/", came to know that [azureDisk](https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk) - Azure Disk (not available in v1.27)

could you please help me on this.

### What do you see instead?

i am getting "  Warning  FailedAttachVolume  10s (x2 over 2m11s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-***************" : timed out waiting for external-attacher of disk.csi.azure.com CSI driver to attach volume resourceID.

**Comment by javsalgar** [comment]
Hi,

It seems to me that this is not related to the Bitnami packaging of redis-cluster but with AKS itself. Did you check with the Azure team on the issue?
