### ISSUE TITLE
Add option to disable Load Balancer Node Port Allocation 

### ISSUE THREAD

**Issue by belps96** [bitnami/charts#20495]
### Name and Version

bitnami/rabbitmq 12.3.0

### What is the problem this feature will solve?

When using the LoadBalancer service type with the RabbitMQ helm chart, NodePorts are assigned for each service port. 

Being able to set `spec.allocateLoadBalancerNodePorts` to `false `would address this.

### What is the feature you are proposing to solve the problem?

`service.allocateLoadBalancerNodePorts: false`

### What alternatives have you considered?

Creating a loadbalancer manually

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
