### ISSUE TITLE
[wordpress] Do not prepareDataToPersist

### ISSUE THREAD

**Issue by polRk** [bitnami/charts#2050]
How can i disable function, which clone wp-content folder ? 
```
wordpre TRACE [prepareDataToPersist] Preparing /opt/bitnami/wordpress/wp-content to persist in /bitnami/wordpress/wp-content
``` 

I use this command  in CI/CD for cloning my wp-content from git.
```
        echo "Clean wp-content"
        kubectl exec -i ${POD} -n highseason -c wordpress -- bash -c "cd /bitnami/wordpress/wp-content; ls | grep -v uploads | xargs rm -rf"
        echo "Copy wp-content to ${NS}/${RELEASE}."
        cd wordpress
        kubectl cp wp-content ${POD}:/bitnami/wordpress -c wordpress -n ${NS}
```

**Comment by polRk** [comment]
REF https://github.com/bitnami/bitnami-docker-wordpress/issues/225

**Comment by miguelaeh** [comment]
Hi @polRk ,
I would like to understand the issue better. You are overriding the content of the `wp-content` folder with your GitHub content. So, why is it needed to disable that? I mean, as you are executing that command from local, once the pod is created, it should override the content of that folder, so the old content will disappear.

**Comment by polRk** [comment]
For example, I run your helm chart and want the wp-content content to be the same as in the **short-lived feature branch**. I **don't** need a permanent wordpress deployment, I want to upload modified theme or plugin files and only see my changed files. I want to quickly launch helm chart without initializing wp-content. I want only to initialize wp-config.php

**Comment by polRk** [comment]
It would be good to add support for init containers and disable the wp-content initialization (add default themes and bitnami predefined plugins)

**Comment by juan131** [comment]
Hi @polRk 

Did you try using the parameter `wordpressSkipInstall` parameter? It allows you to skip the WP wizard installation.

**Comment by polRk** [comment]
> Hi @polRk
> 
> Did you try using the parameter `wordpressSkipInstall` parameter? It allows you to skip the WP wizard installation.

I have tried. If my pvc has empty /bitnami/wordpress dir, it doesn't help.

**Comment by juan131** [comment]
Hi @polRk 

Another alternative would be adding your custom scritps at `/docker-entrypoint-init.d`, see:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh
- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/app-entrypoint.sh#L13

We would need to adapt the chart to allow users mount their scripts at that path. Then, you can add in your scripts anything you'd like and that would be executed just after WP is initialized (add plugins, themes, etc.)
