### ISSUE TITLE
container sudo password

### ISSUE THREAD

**Issue by secoldPrivate** [bitnami/charts#2053]
currently using the latest bitnami/wordpress.

I need to go in and modify the file upload sizes, but I can't install vim because I don't know the password for the root user in the container!

**Comment by rafariossaa** [comment]
Hi @secoldPrivate ,
  We currently have a internal task to make possible to set serveral PHP parameters in all the charts that use PHP.
  Right now there is no ETA for this, but we will come back as soon as it is implemented.
