### ISSUE TITLE
postgresql: cronjob backup not working with tls

### ISSUE THREAD

**Issue by mrlhansen** [bitnami/charts#20546]
### Name and Version

bitnami/postgresql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the following Helm command.

```console
$ helm install mypostgres bitnami/postgresql -f values.yaml
Error: INSTALLATION FAILED: YAML parse error on postgresql/templates/backup/cronjob.yaml: error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context
```

### Are you using any custom parameters or values?

Values file `values.yaml`. This is the simplest version to reproduce the error.

```yaml
tls:
  enabled: true
  autoGenerated: true
backup:
  enabled: true
```

### What is the expected behavior?

I expect the deployment to be installed.

### What do you see instead?

I see the above error message.
```
Error: INSTALLATION FAILED: YAML parse error on postgresql/templates/backup/cronjob.yaml: error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context
```

### Additional information

I also tried by manually setting a TLS certificate via a Kubernetes secret, but that also fails.

I also tried different versions of the chart, but they all seem to have the same problem.

**Comment by FraPazGal** [comment]
Thanks for reporting this bug @mrlhansen! It seems this errors stems from a templating issue in `cronjob.yaml`, would you be interested on contribute with a fix for this? We'll be happy to review your PR and add it to our `bitnami/postgresl` chart.

**Comment by AdolfoVillalobos** [comment]
Hi!  I would be happy to submit a PR if no one is working on this.  I've been using bitnami's charts for a while now, and would love to give back.  I am also in need of a solution for this issue as well.

**Comment by FraPazGal** [comment]
Thanks for the offer and using our products @AdolfoVillalobos! Our team will review your contribution and help you on it happily, please feel free to reach out if you have any questions or need assistance.
