### ISSUE TITLE
[bitnami/kafka] minReadySeconds support in the Kafka chart

### ISSUE THREAD

**Issue by dhduvall** [bitnami/charts#20540]
### Name and Version

bitnami/kafka 25.3.0

### What is the problem this feature will solve?

When the Kafka StatefulSet is restarted, each pod is taken down immediately after the previous one is marked ready. This seems to put clients into an unhappy state. While I'm sure that clients could be written more robustly, the problem does seem to disappear with an appropriate setting of `minReadySeconds`, and I'd like for the Kafka chart to support that.

### What is the feature you are proposing to solve the problem?

Similar to what was implemented for redis (#13596, #13783, #15417), add `minReadySeconds` support to the chart. I'll start putting this together myself, but I've no doubt it'd be faster for someone who's already contributed to do so.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for suggestion. Would you like to submit a PR adding the same support as the others you mentioned?
