### ISSUE TITLE
Add ability to NOT generate service account for external DNS

### ISSUE THREAD

**Issue by derrickburns** [bitnami/charts#2056]
When using Amazon IAM for Service Accounts, we create service accounts that need IAM identities outside of the helm chart.  We need the ability to NOT create the service account in the helm chart.

**Comment by miguelaeh** [comment]
Hi @derrickburns ,
Thank you very much for your suggestions, I guess you are requesting the service acoount to be optional, would you like to create a PR for that purpose?

**Comment by derrickburns** [comment]
Done:

https://github.com/bitnami/charts/pull/2104

**Comment by miguelaeh** [comment]
Thank you very much @derrickburns , a colleague is already in charge of your PR.
