### ISSUE TITLE
[bitnami/matomo] CronJobs fail due to ReadWriteOnce PVC access mode

### ISSUE THREAD

**Issue by chrisaiello** [bitnami/charts#20568]
### Name and Version

bitnami/matomo 3.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Running in GKE
- Using default values, specifically, persistence and cronjobs enabled.

### What is the expected behavior?

CronJobs `matomo-archive` and `matomo-scheduled-tasks` should execute successfully. 

### What do you see instead?

If the cronjobs are scheduled on a different node than the `matomo` deployment, they will fail to run as they cannot mount the `persistentVolumeClaim` with access mode `ReadWriteOnce` as the PVC is already bound to the deployment.

### Additional information

on GKE, at least, you can't just change the `accessMode` to `ReadWriteMany` without complex and costly workarounds: https://medium.com/@Sushil_Kumar/readwritemany-persistent-volumes-in-google-kubernetes-engine-a0b93e203180

I was able to mitigate this issue by adding `podAffinity` to the deployment and cronjob specs to ensure all pods are scheduled on the same node. I'm not confident enough to say if this is a good long-term solution.

**Comment by ashwin027** [comment]
Im having the exact same issue with EKS where gp-2 PVs only allow RWO.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Taronyuu** [comment]
@carrodher I've ran into the same issue and have fixed it by modifying the values file (pretty much add a label to the web container and add pod affinities to the cronjobs). Can I just add these fixes as a PR or should this be done in a different way?

**Comment by carrodher** [comment]
Sure, your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
