### ISSUE TITLE
[bitnami/contour] Update CRDs and Contour rbac

### ISSUE THREAD

**Issue by claytonig** [bitnami/charts#20561]
### Name and Version

bitnami/contour 

### What is the problem this feature will solve?

This in preparation of the new version of [contour 1.27](https://github.com/projectcontour/contour/releases/tag/v1.27.0) to use endpoint slices. 
Also the CRD's are out of date.

### What is the feature you are proposing to solve the problem?

- Update CRDs as. these are out of date 
- Update contour rbac to allow reading of endpoint slices.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
