### ISSUE TITLE
[bitnami/postgresql] Postgres Backup cronjob

### ISSUE THREAD

**Issue by parzival0741** [bitnami/charts#20578]
### Name and Version

Bitnami/postgres:13.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the chart with custom tls and backups enabled.

### Are you using any custom parameters or values?

We are also trying to use vault injection but the error blocked the ability to test that.

### What is the expected behavior?

The cronjob starting and backing up Postgres.

### What do you see instead?

Line 52 errors on the cronjob file which before rendering ends up being line 80. If you run helm template the value:/tmp/certs/ is missing a space and causes the error.

Removing the tack from the front set of braces fixed the issue. 

### Additional information

Something is also wrong with the annotations section it fails to run if you have any in your inputs.
IE. Vault injection is failing to work on the cronjob as well.

Note: I understand that this is not ideal but I can’t share screenshots or data directly on this thread. I will see if I can recreate the issues on my own time to demonstrate it.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by mrlhansen** [comment]
This sounds like the same issue I reported here #20546
