### ISSUE TITLE
Incorrect variable name in Bitnami/mysql

### ISSUE THREAD

**Issue by Hramoff** [bitnami/charts#20574]
### Name and Version

bitnami/mysql 9.14.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The `defaultAuthenticationPlugin` variable is entered into values.yaml to indicate the authentication plugin.
[defaultAuthenticationPlugin](https://github.com/bitnami/charts/blob/79261efe92efeed696bc103c5cfe7b905debb1b9/bitnami/mysql/values.yaml#L156)

But the configuration settings indicate `.Values.auth.defaultAuthPlugin`
[configuration](https://github.com/bitnami/charts/blob/79261efe92efeed696bc103c5cfe7b905debb1b9/bitnami/mysql/values.yaml#L205)

### What is the expected behavior?

my.cnf
```
[mysqld]
default_authentication_plugin=caching_sha2_password
...
...
```

### What do you see instead?

my.cnf
```
[mysqld]
default_authentication_plugin=mysql_native_password
...
...
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
