### ISSUE TITLE
postgresql-ha replication between multiple clusters

### ISSUE THREAD

**Issue by mirkub** [bitnami/charts#20587]
### Name and Version

bitnami/postgresql-ha

### What is the problem this feature will solve?

I have a running postgresql cluster (A). In the cluster, there is 1 pgpool and 3 ha-postgresql replicas. One of the replicas is primary and has write permission.
Now I'd like to start a new kubernetes cluster (B) which should be used just for replication in case the cluster (A) is destroyed. For communication between the clusters I'd start a load balancer service on cluster (A) and let the postgresql-ha pod on cluster (B) connect to the service. The load balancer has some external IP and port different to 5432 (30111).

I was trying to make it work but there are multiple problems with this. For example the hostname of the primary POD is transferred from site(A) to site(B) and on site (B) the hostname is unknown and the port is also different to 5432 to access.

Is there any concept of how such functionality can be achieved?

### What is the feature you are proposing to solve the problem?

Allow configuration for such deployment.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by chandresh87** [comment]
@mirkub  were you able to solve this? I am trying to do something similar.

**Comment by davidy718** [comment]
same here, trying to do something similar

**Comment by mirkub** [comment]
We have abandoned bitnami and used zalando/patroni instead.
