### ISSUE TITLE
[bitnami/prestashop] Fatal error: Uncaught TypeError: array_key_exists() on upgrade

### ISSUE THREAD

**Issue by ChrisLovering** [bitnami/charts#20591]
### Name and Version

bitnami/prestashop 19.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Have a prestashop instance running from version 13.1.21
2. Run `helm upgrade prestashop bitnami/prestashop --version 19.1.0 -f values.yaml --set prestashopPassword=foo,mariadb.auth.password=foo,mariadb.auth.rootPassword=foo,smtpPassword=foo --wait`
3. Load prestashop page

### Are you using any custom parameters or values?

```yaml
prestashopHost: merch.example.com

prestashopUsername: merch@example.com
prestashopPassword:
prestashopEmail: merch@example.com
prestashopFirstName: example
prestashopLastName: example

allowEmptyPassword: false

smtpHost: smtp.mailgun.org
smtpPort: 587
smtpUser: merch@example.com
smtpProtocol: tls

podAnnotations:
  prometheus.io/scrape: "false"

mariadb:
  primary:
    persistence:
      enabled: true
      storageClass: linode-block-storage-retain
      size: 10Gi

containerPorts:
  http: 8080
  https: 8443

updateStrategy:
  type: Recreate

service:
  type: ClusterIP

ingress:
  enabled: false

persistence:
  enabled: true
  storageClass: "linode-block-storage-retain"

  size: 10Gi

metrics:
  enabled: false

  podAnnotations:
    prometheus.io/scrape: "false"

```

### What is the expected behavior?

Prestashop works as intended, with no major issues expected during upgrade

### What do you see instead?

4 separate log outputs, the last being the fatal error

```
Deprecated: AppKernel implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /bitnami/prestashop/app/AppKernel.php on line 33

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /bitnami/prestashop/config/bootstrap.php on line 89

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /bitnami/prestashop/config/bootstrap.php on line 89

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, Shop given in /bitnami/prestashop/src/Adapter/EntityMapper.php:99 Stack trace: #0 /bitnami/prestashop/src/Adapter/EntityMapper.php(99): array_key_exists() #1 /bitnami/prestashop/classes/ObjectModel.php(264): PrestaShop\PrestaShop\Adapter\EntityMapper->load() #2 /bitnami/prestashop/classes/shop/Shop.php(128): ObjectModelCore->__construct() #3 /bitnami/prestashop/classes/shop/Shop.php(411): ShopCore->__construct() #4 /bitnami/prestashop/config/config.inc.php(118): ShopCore::initialize() #5 /bitnami/prestashop/administration/index.php(40): require('...') #6 {main} thrown in /bitnami/prestashop/src/Adapter/EntityMapper.php on line 99
```

### Additional information

Prestashop instance has been running on 13.1.21 (1.7.7-6 app version) since Aug 2021. Decided to update it today with the command above and got the error above.

My googling around for this error all pointed towards running a too new version of php, but I don't see any way to control which version of php is running inside the container via configuration.

**Comment by FraPazGal** [comment]
Hello @ChrisLovering, be aware you are trying to upgrade from a chart 6 majors behind which have translated into several breaking changes. Besides the changes to the chart itself, the upgrade from Prestashop 1.7 to 8.0 doesn't seem to be seamless and could be the culprit behind the reported PHP errors.

The changes pertaining to the chart itself could be bridged with some work, but I doubt the upgrade to the new Prestashop version would be as easy.

I would recommend following the [migration documentation](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/migration/) so you can move you existing data to a fresh Prestashop 8 instance used by our latest `bitnami/prestashop` chart version.

**Comment by ChrisLovering** [comment]
Ah right, I was following [the upgrade documentaiton](https://github.com/bitnami/charts/tree/main/bitnami/prestashop#upgrading) which indicated no major issues were to be expected during the upgrade at each step, so assumed that it would be fine.

I'll follow the migration documentation provided, thanks for your help.
