### ISSUE TITLE
Multus-cni and Whereabouts use .Release.Namespace for the ServiceAccount instead of common.names.namespace

### ISSUE THREAD

**Issue by antevens** [bitnami/charts#20597]
### Name and Version

whereabouts 0.5.6 / multus-cni 1.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy charts using Namespace Override

This is a common use-case since both Multus and Whereabouts would typically be deployed into kube-system.

### Are you using any custom parameters or values?

`--set namespaceOveride=kube-system`

### What is the expected behavior?

Default service account would be created -n kube-system namespace and ClusterRole/Rolebinding would point to it.

### What do you see instead?

Service Account is created in the namespace used by the Helm install, Daemonset will fail to start because of missing Service Account.

### Additional information
```
namespace: {{ .Release.Namespace | quote }}
namespace: {{ include "common.names.namespace" . | quote }}
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
