### ISSUE TITLE
[bitnami/postgresql] BUG: sed error when using 'exisingSecret' and replication enabled.

### ISSUE THREAD

**Issue by joe-sonrichard** [bitnami/charts#2060]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
**Which chart**:
postgresql v8.6.4

**Description**
If you use an existing secret for the db passwords with replication enabled the slaves will die during init due to a `sed` error. We tried removing special characters from the replication password (it had two slashes) but it still fails. 

**Steps to reproduce the issue:**

1. Write a file postgresql-values.yaml with the following:
```yaml
replication:
  enabled: true
  slaveReplicas: 2
  synchronousCommit: "on"
  numSynchronousReplicas: 1
  applicationName: artifactory

existingSecret: postgresql-admin-user-creds

postgresqlDatabase: artifactory

persistence:
  size: 100Gi

metrics:
  enabled: true
```
2. Create postgresql-admin-user-creds secret:
```
kubectl create secret generic postgresql-admin-user-creds \
        --from-literal=postgresql-password="$(openssl rand -base64 50)" \
        --from-literal=postgresql-replication-password="$(openssl rand -base64 50)" \
        --from-literal=postgresql-ldap-password="$(openssl rand -base64 50)"
```
3. Use helm to install using this values file: `helm install artifactory -f postgresql-values.yaml bitnami/postgresql`
4. Inspect the pods as they're created (I used k9s) (observe failure in slave pod)

5. Observing the error, try editing the secret key `postgresql-replication-password` to remove all special characters, uninstall and reinstall via helm. Note it still breaks.

**Describe the results you received:**

The replication slave dies:
![image](https://user-images.githubusercontent.com/49208786/76775693-1b4f2a00-677c-11ea-8692-fcc7f43beb04.png)

Due to a sed error:
![image](https://user-images.githubusercontent.com/49208786/76775765-391c8f00-677c-11ea-8380-7ae5ed6ebcc9.png)

Here's the secrets after removing a few slashes from `postgresql-replication-password`
![image](https://user-images.githubusercontent.com/49208786/76776221-d8da1d00-677c-11ea-87ac-913b68b4cefe.png)
(Yes I know I'm pasting my passwords publicly - I've already deleted them from my cluster)

**Describe the results you expected:**

The master and slave nodes would turn on and run all auto-magically, in particular, they would authenticate successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue does not occur if you disable replication or enable replication and do not use the `existingSecret` field.

You may note that "artifactory" shows up here and there but as yet no artifactory resources exist in my cluster so it should not be a factor in debugging.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```json
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```json
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
  It seems that is an issue when the pwd contains `/` , we are woring in fixing it. 
  Meanwhile, as workaround, could you set a password that not contains that character ?

**Comment by joe-sonrichard** [comment]
I did, it seemed that that didn't help since I still had the error after removing the slashes from the password. However, I think the issue probably remained because it was still using the old password per issue #2061.

**Comment by dani8art** [comment]
Hi, Could you try to do it having a password without special characters, I mean just `[a-z][A-Z][0-9]`

**Comment by joe-sonrichard** [comment]
@dani8art, at this point I've long since bypassed postgres altogether. I did try changing it to a password without special characters but it appears postgres keeps a local copy of the creds which are not updated when the secret is updated. As a result, (and since reinstalling doesn't wipe the password either) I could never replace the complicated password with the simple alpha-numeric one. That's covered in #2061 which relates to [another known issue](https://github.com/helm/charts/issues/16251).

**Comment by dani8art** [comment]
Sure, you can not replace only in the secret since it is store in postgres itself, you need to redeploy from scratch with the new password and you must delete the persistence volumes.

**Comment by finaldzn** [comment]
Hello, Ive encountered this bug after installing postgres locally (windows) I then could not connect to the postgres container using the secret's password.

**Comment by rafariossaa** [comment]
Hi @finaldzn ,
  Could you open a new issue so we can do a proper tracking of it ? This issue was relate to the password the user was generating and as you are using postgres container in windows maybe it is a different case.

Thanks forehand.
