### ISSUE TITLE
Add TLS support for the web front end

### ISSUE THREAD

**Issue by scottrix** [bitnami/charts#20610]
### Name and Version

bitnami/jasperreports

### What is the problem this feature will solve?

It is always good to have encrypted connections, adding this improve system security.

### What is the feature you are proposing to solve the problem?

TLS to jasper reports frontend

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
