### ISSUE TITLE
[bitnami/airflow] Is global.storageClass in Airflow Helm Chart being used?

### ISSUE THREAD

**Issue by snowsky** [bitnami/charts#20628]
### Name and Version

Airflow

### What architecture are you using?

None

### What steps will reproduce the bug?

I set `global.storageClass` in Airflow's Chart, but it didn't take effect and I didn't find any place in Airflow's chart refers to the `global.storageClass`.

### What do you see instead?

N/A

**Comment by snowsky** [comment]
Got it, thanks for the helpful hint 👍 Do you think it is ok to add a comment? Will refer to this issue for your credit.

**Comment by snowsky** [comment]
Got it, will do a quick search :)

**Comment by snowsky** [comment]
After searching the whole repo, I found `107` charts using the same global variables. I feel it is helpful for people to know about it.

Do you think it is ok to add the below line right after the line https://github.com/bitnami/charts/blob/main/bitnami/airflow/README.md#global-parameters?
```
*These parameters will be passed to all the dependent sub-charts defined in `Chart.yaml`*
```

**Comment by dgomezleon** [comment]
Hi @snowsky ,

We provide documentation to explain the characteristics of our charts. However, it may be more related to general aspects of Helm, as you can see in the link below:

 https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by snowsky** [comment]
Thanks for the info. I think we don't need a PR to address this issue. Closing 🙂
