### ISSUE TITLE
Wordpress Helm Chart Apache exporter SecurityContext

### ISSUE THREAD

**Issue by pomland-94** [bitnami/charts#20622]
### Name and Version

bitnami/wordpress:latest

### What architecture are you using?

arm64

### What steps will reproduce the bug?

It's not possible to set the SecurityContext for the Apache exporter inside the WordPress Helm Chart.

### What do you see instead?

In hardened clusters, the Apache exporter does not come up.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
