### ISSUE TITLE
Redis sentinel Error: waitpid() returned a pid we can't find in our scripts execution queue!

### ISSUE THREAD

**Issue by koenigfa1** [bitnami/charts#20638]
### Name and Version

bitnami/redis/18.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using an Image with the following Dockerfile:

```dockerfile
FROM redis:7.0-alpine3.18

RUN apk add --no-cache bash
RUN apk add openssl
```

I am using the following YAML to deploy the Redis Sentinel with the above shown Image in the StatefulSet.

[YAML.zip](https://github.com/bitnami/charts/files/13267723/YAML.zip)

### Are you using any custom parameters or values?

Complete Resources and Setup are shown in the YAML.zip above.

### What is the expected behavior?

Run without the error messages 

### What do you see instead?

[1.log](https://github.com/bitnami/charts/files/13267736/1.log)
[2.log](https://github.com/bitnami/charts/files/13267737/2.log)
[3.log](https://github.com/bitnami/charts/files/13267738/3.log)

### Additional information

To make it clear I am NOT using the official Bitnami Image shown in the Helm Chart docker.io/bitnami/redis:7.2.1-debian-11-r0 / docker.io/bitnami/redis-sentinel:7.2.1-debian-11-r0 because those critical CVEs in the images are not allowed in my environment. See above which Image I used, I copied the Dockerfile!

**Comment by carrodher** [comment]
Unfortunately, that is something not supported out of the box by the Helm chart. If you're replacing the container images with non-Bitnami images, it couldn't work.

I understand your concern regarding security vulnerabilities. While we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by koenigfa1** [comment]
Alright. But i dont have access to the golden Images. My task is to find a way to use a custom own Image without any critical CVEs. I actually dont use the helm chart anymore as you can see. I picked each YAML file and apply them by myself. I mean the Pods and the redis container are running. I dont know may the Log from sentinel "waitpid() returned a pid we can't find in our scripts execution queue!" be just an info or warning? How can i check everything is working properly?

**Comment by koenigfa1** [comment]
```
│ sentinel 1:X 07 Nov 2023 14:28:18.174 # waitpid() returned a pid (144) we can't find in our scripts execution queue!                                            │
│ sentinel 1:X 07 Nov 2023 14:28:22.757 * +sentinel sentinel 817333fc9cfeb5cf8d7595ba084eac43e846dd09 10.248.64.245 26379 @ mymaster xx-yy-redis-n │
│ sentinel 1:X 07 Nov 2023 14:28:22.769 * Sentinel new configuration saved on disk                                                                                │
│ sentinel 1:X 07 Nov 2023 14:28:23.109 # waitpid() returned a pid (152) we can't find in our scripts execution queue!                                            │
│ sentinel 1:X 07 Nov 2023 14:28:28.123 # waitpid() returned a pid (169) we can't find in our scripts execution queue!
```

I see sentinel doing stuff correctly isnt it? Is the Log Message not an error just an information? If so what is the impact of the message?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
