### ISSUE TITLE
[bitnami/mongodb] Persistent Failures in Readiness and Liveness Probes for Containers in Kubernetes Cluster

### ISSUE THREAD

**Issue by yashdevops01** [bitnami/charts#20649]
### Name and Version

bitnami/mongodb-14.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. In our dev and prod environment, we installed the **bitnami/mongodb** helm chart in the **AWS EKS cluster** and we used **t3a.large** size **three instance node group**.
2. It's working properly but sometimes the pod shows 0/1 running status
3. I describe the mongodb-o pod and return warring message

![Screenshot from 2023-11-07 11-04-15](https://github.com/bitnami/charts/assets/150107897/5794fa88-a0d7-4dbe-aae8-686a367df9b6)

### Are you using any custom parameters or values?

I used custom values.yaml file. I was customized [ mongodb replicaset with loadbalancer ] (#https://docs.bitnami.com/kubernetes/infrastructure/mongodb/configuration/configure-external-access-replicaset/#use-loadbalancer-services)

### What do you see instead?

What we expect to see instead is that the containers pass the readiness and liveness probes within the specified time frames. We expect the scripts readiness-probe.sh and ping-mongodb.sh to execute successfully without timing out. The containers should be ready to serve traffic and running as expected.

**Comment by carrodher** [comment]
Readiness and Liveness Probes have default values that are used to work in most environments, although under certain circumstances it could be needed to fine-tune them to meet the requirements of your environment

**Comment by yashdevops01** [comment]
@carrodher Thanks for the reply, Here we only used default Readiness and Liveness Probes values in our all environments. we do not have any requirements for our environment. we have already used the default value in our stage environment here we have not seen this issue. okay, anything other solution for this error?

**Comment by carrodher** [comment]
Weirdly, other charts work and this one works in a similar environment. You can use the `image.debug` parameter to increase the verbosity of the container logs, just in case there are some hints.

**Comment by yashbabariya** [comment]
@carrodher I was debugging mongodb pod container logs and I got some connection-related errors every second. this happens in every environment. 
![Screenshot 2023-11-21 at 10 01 34 AM](https://github.com/bitnami/charts/assets/67451545/60e1577c-b0e4-4803-8e01-1fb643b4b59b)

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by f-w** [comment]
The readiness state of my MongoDB statefulset pods is so unstable to the point such that 3 pods rarely are ready at same time. Increasing `readinessProbe.timeoutSeconds` from default 5 to 10 solves my problem. My pod cpu limits is 250 milli-core, which could be the cause of slowness.
