### ISSUE TITLE
Getting error while launching Jenkins SaaS service in IBM Cloud

### ISSUE THREAD

**Issue by ankurgarg21** [bitnami/charts#2065]
Hi Team,

I am facing below error when launching Jenkins SaaS service offered by IBM in Catalog.

https://cloud.ibm.com/catalog/content/jenkins-Qml0bmFtaS1qZW5raW5z-global

Please if you can check on same. 

 2020/03/16 02:26:13 Terraform apply | Debug : Nap for 5 sec for Tiller installation to finish.
 2020/03/16 02:26:13 Terraform apply | Error : issue with tiller installation.. exiting 
 2020/03/16 02:26:13 Terraform apply | Error : No response received from tiller in 60 sec
 2020/03/16 02:26:13 Terraform apply | Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
 2020/03/16 02:26:13 Terraform apply | Error: could not find a ready tiller pod
 2020/03/16 02:26:13 Terraform apply | 
 2020/03/16 02:26:13 Terraform apply | 
 2020/03/16 02:26:13 Terraform apply | 
 2020/03/16 02:26:13 Terraform apply | 
 2020/03/16 02:26:13 Terraform apply | Terraform does not automatically rollback in the face of errors.
 2020/03/16 02:26:13 Terraform apply | Instead, your Terraform state file has been partially updated with
 2020/03/16 02:26:13 Terraform apply | any resources that successfully completed. Please address the error
 2020/03/16 02:26:13 Terraform apply | above and apply again to incrementally change your infrastructure.
 2020/03/16 02:26:13 Terraform apply | 
 2020/03/16 02:26:13 Terraform apply | 
 2020/03/16 02:26:13 Terraform APPLY error: Terraform APPLY errorexit status 1

Thanks,
Ankur

**Comment by beltran-rubo** [comment]
Hi @ankurgarg21 It seems there was an issue installing Helm Tiller in your K8s cluster. It is failing before installing the Jenkins Helm Chart. @gmendel is that something you can help with?

**Comment by gmendel** [comment]
This look like a Schematics issue with the tiller version, open a ticket on the IBM cloud

**Comment by ankurgarg21** [comment]
HI @gmendel 

> This look like a Schematics issue with the tiller version, open a ticket on the IBM cloud

Hi @gmendel Before open a case here I checked already with IBM on this and they reply below.

As they answered, support for third-party services is provided directly by the service provider.
For this Jenkins offer, support is provided by Bitnami, as you can read at the end of the Readme page (https://cloud.ibm.com/catalog/content/jenkins-Qml0bmFtaS1qZW5raW5z-global#about) of the Catalog offer.

Can you give me more insight on this issue so that I can open case again with IBM.

Thanks in advance.

**Comment by ankurgarg21** [comment]
> HI @gmendel
> 
> > This look like a Schematics issue with the tiller version, open a ticket on the IBM cloud
> 
> Hi @gmendel Before open a case here I checked already with IBM on this and they reply below.
> 
> As they answered, support for third-party services is provided directly by the service provider.
> For this Jenkins offer, support is provided by Bitnami, as you can read at the end of the Readme page (https://cloud.ibm.com/catalog/content/jenkins-Qml0bmFtaS1qZW5raW5z-global#about) of the Catalog offer.
> 
> Can you give me more insight on this issue so that I can open case again with IBM.
> 
> Thanks in advance.

Also I found tiller is not installed in Kube cluster which means issue is with Kube cluster not Jenkins service. I am checking with IBM support on this. 

Please find the output below:

Admins-MacBook-Pro:~ admin$ helm status
Error: could not find tiller
Admins-MacBook-Pro:~ admin$ kubectl -n kube-system get po
NAME                                                  READY   STATUS    RESTARTS   AGE
calico-kube-controllers-77d9744958-cj44g              1/1     Running   0          47m
calico-node-4w8n4                                     1/1     Running   0          25m
calico-node-7mbcm                                     1/1     Running   0          31m
calico-node-d66lc                                     1/1     Running   0          25m
coredns-6cc6b4ddb6-f2khz                              1/1     Running   0          30m
coredns-6cc6b4ddb6-l8ln5                              1/1     Running   0          30m
coredns-6cc6b4ddb6-zddbn                              1/1     Running   0          47m
coredns-autoscaler-688d995d7c-b7krs                   1/1     Running   0          47m
dashboard-metrics-scraper-69468c6b44-k5bbj            1/1     Running   0          45m
ibm-master-proxy-static-10.244.0.61                   2/2     Running   0          31m
ibm-master-proxy-static-10.244.128.94                 2/2     Running   0          25m
ibm-master-proxy-static-10.244.64.76                  2/2     Running   0          24m
ibm-vpc-block-csi-controller-0                        3/3     Running   0          45m
ibm-vpc-block-csi-node-dn4tg                          2/2     Running   0          31m
ibm-vpc-block-csi-node-rgjlx                          2/2     Running   0          24m
ibm-vpc-block-csi-node-tcrmg                          2/2     Running   0          25m
kubernetes-dashboard-bbcc67fc-z999p                   1/1     Running   0          45m
metrics-server-55d6dbc947-rdcfp                       2/2     Running   0          29m
public-crbponpqat0lol57crqjhg-alb1-7fccb74ddc-p4m9c   4/4     Running   0          39m
public-crbponpqat0lol57crqjhg-alb1-7fccb74ddc-stt4l   0/4     Pending   0          39m
public-crbponpqat0lol57crqjhg-alb2-58ffd4487b-9kcv7   4/4     Running   2          39m
public-crbponpqat0lol57crqjhg-alb2-58ffd4487b-zn56s   0/4     Pending   0          39m
public-crbponpqat0lol57crqjhg-alb3-fff7675bd-8zh7n    0/4     Pending   0          39m
public-crbponpqat0lol57crqjhg-alb3-fff7675bd-d6f2v    4/4     Running   0          39m
vpn-b5cd9dc8b-8tp2v                                   1/1     Running   0          45m
Admins-MacBook-Pro:~ admin$

**Comment by beltran-rubo** [comment]
As @gmendel mentioned, this is probably an issue in IBM schematics. That is the responsible of installing Tiller to be able to deploy Helm Charts. Please report this issue to IBM support as it should be fixed in Schematics.

From Bitnami, we will be happy to help you with any issues with the Helm Chart deployment & configuration.

**Comment by ankurgarg21** [comment]
> As @gmendel mentioned, this is probably an issue in IBM schematics. That is the responsible of installing Tiller to be able to deploy Helm Charts. Please report this issue to IBM support as it should be fixed in Schematics.
> 
> From Bitnami, we will be happy to help you with any issues with the Helm Chart deployment & configuration.

Thanks @beltran-rubo  I am checking with IBM and will get back to you if needed. Thanks for your support.

**Comment by beltran-rubo** [comment]
Thanks, please keep us in the loop with the solution and let us know if there is anything we can help you with.

**Comment by ankurgarg21** [comment]
> Thanks, please keep us in the loop with the solution and let us know if there is anything we can help you with.

I almost resolved this issue now ending up another issue where I need to overwrite value for nodeSelector, can you give me an example to overwrite same:

nodeSelector: {{- include "jenkins.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}

how to fill above value with node name.

thanks

**Comment by beltran-rubo** [comment]
the "nodeSelector" option is available via parameter. Check the "Set the deployment values" and you are able to configure that option.

<img width="930" alt="Screen Shot 2020-03-31 at 14 51 38" src="https://user-images.githubusercontent.com/3718440/78028427-5007d780-735f-11ea-8ca8-9aeb79531aec.png">

**Comment by ankurgarg21** [comment]
> the "nodeSelector" option is available via parameter. Check the "Set the deployment values" and you are able to configure that option.
> 
> <img alt="Screen Shot 2020-03-31 at 14 51 38" width="930" src="https://user-images.githubusercontent.com/3718440/78028427-5007d780-735f-11ea-8ca8-9aeb79531aec.png">

yes I know therefore I am asking for right syntax to fill the right value because I tried below didn't work:
{ip-address}

**Comment by ankurgarg21** [comment]
I found it myself, its working fine thanks.

{ ibm-cloud.kubernetes.io/internal-ip: 1.2.3.4 }
