### ISSUE TITLE
[sealed-secrets] crd out of sync with upstream project

### ISSUE THREAD

**Issue by HaveFun83** [bitnami/charts#20667]
### Name and Version

bitnami/sealed-secrets

### What architecture are you using?

None

### What steps will reproduce the bug?

The provided chart [crds](https://github.com/bitnami/charts/tree/main/bitnami/sealed-secrets/crds) ist out-of-sync with the upstream project [crds](https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets/crds) 

The provide sealedsecrets.bitnami.com crd missing the following change: https://github.com/bitnami-labs/sealed-secrets/pull/1217

### What is the expected behavior?

crds are synced with upstream projects

### What do you see instead?

The status  column is missing

Upstream
```
NAME                 STATUS   SYNCED   AGE
example-secret                True     272d
```
bitnami/charts
```
NAME                 AGE
example-secret       446d
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by HaveFun83** [comment]
unfortunately there is no simple solution for this.  i thought about this ideas
* using an github action to sync the crd file / folder from the upstream repo (should also work via PR)
  * https://github.com/marketplace/actions/repo-file-sync-action
* Ask the upstream project if they add the crd into an separate crd helmchart witch than can be used as dependency
* deprecated the bitnami/sealed-secrets chart and point only to upstream  bitnami-labs/saled-secrets as you are in the same company i think

@carrodher what do you think?

**Comment by carrodher** [comment]
Thanks! Yes, we have an internal task to automatically import the CRDs from upstream projects when needed. In this case, I was suggesting just creating a PR updating the CRDs to solve the issue at this moment. I agree the long-term solution requires more effort and that's why we have a task in our backlog that we hope to be able to do soon

**Comment by HaveFun83** [comment]
Great. than i will create an PR for the crd. 
Thanks a lot
