### ISSUE TITLE
[bitnami/postgresql] Add eneable pg_stat_statements extension in values file

### ISSUE THREAD

**Issue by javsalgar** [bitnami/charts#2067]
Copying conversation from https://github.com/helm/charts/issues/21486

> Need to add extension.pg_stat_statements : bool with default false to values file and add support this extension. In the future, by the same principle, you can add the inclusion of other extensions. What needs to do for implementing this feature?

By @heckad

**Comment by javsalgar** [comment]
Hi,

Just so I understand. Wouldn't including your extended configuration file work in this case? 

https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L177

README: https://github.com/bitnami/charts/tree/master/bitnami/postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf

**Comment by Cellebyte** [comment]
@javsalgar the configuration for postgres looks like the following to enable pg_stats_statements.

```conf
# - Shared Library Preloading -

shared_preload_libraries = 'pg_stat_statements' # (change requires restart)
pg_stat_statements.max = 10000
pg_stat_statements.track = all

```

**Comment by javsalgar** [comment]
Hi,

Good to know. If the extended configuration works then please confirm that we can close this issue.

**Comment by Cellebyte** [comment]
> Hi,
> 
> Good to know. If the extended configuration works then please confirm that we can close this issue.
I don't know it because I am currently not running postgresql inside a container.

**Comment by javsalgar** [comment]
Hi,

Then, if I understand correctly, you are not currently using our Bitnami PostgreSQL Container? Are you using our Virtual Machines or Cloud Instances?

**Comment by Cellebyte** [comment]
@javsalgar no. I am only using postgres as it is and it is possible to configure this value over the current `values.yaml`

**Comment by javsalgar** [comment]
Hi, 

Then you are using our helm chart, which uses our PostgreSQL container, right? Just to properly clarify

**Comment by Cellebyte** [comment]
no as a default debian installation without any k8s in mind.

**Comment by javsalgar** [comment]
Hi,

Sorry, I think that I got lost then. If you are not using Kubernetes, I don't fully understand how you could use the chart values.yaml file. Could you please clarify?

**Comment by Cellebyte** [comment]
@javsalgar I only want to say that this option can be set in this scope for postgres and  will be applied. Their is no extra configuration needed beside that.

**Comment by carrodher** [comment]
Not stale, @javsalgar we lost this ticket

**Comment by javsalgar** [comment]
Hi,

If I understood correctly, the extended configuration was sufficient for enabling that value. Not sure if we had to implement something else.

**Comment by javsalgar** [comment]
Closing this for now. Please reopen if necessary.

**Comment by gredwhite** [comment]
Guys, there are al lot of messages at this thread but NO example is provided how to enable pg_stat_statements extension via values.yaml

**Comment by danielorbach** [comment]
> Guys, there are al lot of messages at this thread but NO example is provided how to enable pg_stat_statements extension via values.yaml

Posting here the answer from [StackOverflow](https://stackoverflow.com/questions/74024514/how-to-add-extension-pg-stat-extension-to-postgres-bitnami-helm-chart):
```helm
postgresql
  metrics
    primary:
      extendedConfiguration: |
        shared_preload_libraries = 'pg_stat_statements' # (change requires restart)
        pg_stat_statements.max = 10000
        pg_stat_statements.track = all
```

For future readers see the README: [postgresql.conf / pg_hba.conf files as configMap
](https://github.com/bitnami/charts/tree/cfbfe86992eb83aa39118222bb9b13c14febced9/bitnami/postgresql#postgresqlconf--pg_hbaconf-files-as-configmap)
