### ISSUE TITLE
The MongoDB slave node does not start properly after it is restarted

### ISSUE THREAD

**Issue by Cairry** [bitnami/charts#20678]
### Name and Version

10.26.2

### What architecture are you using?

None

### What steps will reproduce the bug?

<img width="543" alt="image" src="https://github.com/bitnami/charts/assets/115769353/7c68cb53-4d2d-4fad-a179-c247baa0fd6d">
<img width="1438" alt="image" src="https://github.com/bitnami/charts/assets/115769353/be8b7657-cb06-4268-8c46-6312b29eade4">
<img width="969" alt="image" src="https://github.com/bitnami/charts/assets/115769353/45943114-0480-423c-87fe-fc7b11ed8441">

### What do you see instead?

After the slave node is automatically pulled up, it cannot run normally.

**Comment by Cairry** [comment]
<img width="1436" alt="image" src="https://github.com/bitnami/charts/assets/115769353/2db259c5-a2e9-4c6d-8a2f-1cb597ead7ec">
I found that the logs of the new container after the restart contain the IP address of the old container, is this the cause? Why do I find the IP of the old container?

**Comment by carrodher** [comment]
Could you please elaborate a bit more on how are you deploying the Helm chart and what are the values you're using?
