### ISSUE TITLE
[bitnami/wordpress] BUG persistence volumes with file.csi.azure.com provider

### ISSUE THREAD

**Issue by chris8205** [bitnami/charts#20676]
### Name and Version

bitnami/wordpress 6.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In Azure AKS if the deployment use azurefile (file.csi.azure.com) [is must "use" for ReadWriteMany]
the deployment of the Wordpress 6.3.2 stucks when the Wordpress-Installer tries to move the files to the persistence storage (mount point) 
when file wp-config.php is moved the system tries to modify the file permission with setfacl but setfacl runs into permission issues.
the script stops and 'wp-content' folder isn't moved 
wordpress is now in a inconsistent state.

please can you provide a workaround or fix this issue

### Are you using any custom parameters or values?
```
  persistence:
    enabled: true
    storageClass: "azurefile"
    accessModes:
      - ReadWriteMany
    size: 10Gi
```
### What is the expected behavior?

wordpress not running properly because the wp-content files are missing

### What do you see instead?

/bitnami/wordpress/ folder only contains wp-config.php file

no other content is in there

### Additional information

my test with a busybox and same pvc mounted shows that a chown is running sucessfully (but without changing the permissions / owner) but results in state "0"
so it seems, that busybox is handling azurefile pvc otherway as the debian based os used for the wordpress.

**Comment by migruiz4** [comment]
Hi @chris8205,

Thank you for reporting this issue. Could you please share the logs from the failing pod?

The function `persist_app` is shared by many of the applications in the catalog, but we haven't been reported any issues related to `file.csi.azure.com`.

**Comment by dakr0013** [comment]
i have the same problem. here is the log of the failing container:
```
wordpress 16:43:49.40 INFO  ==> 
wordpress 16:43:49.40 INFO  ==> Welcome to the Bitnami wordpress container
wordpress 16:43:49.40 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
wordpress 16:43:49.40 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
wordpress 16:43:49.40 INFO  ==> 
wordpress 16:43:49.41 INFO  ==> ** Starting WordPress setup **
wordpress 16:43:49.43 INFO  ==> Generating sample certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
.....++++
............++++
e is 65537 (0x010001)
Signature ok
subject=CN = example.com
Getting Private key
realpath: /bitnami/apache/conf: No such file or directory
wordpress 16:43:49.57 INFO  ==> Configuring the HTTP port
wordpress 16:43:49.58 INFO  ==> Configuring the HTTPS port
wordpress 16:43:49.58 INFO  ==> Configuring Apache ServerTokens directive
wordpress 16:43:49.61 INFO  ==> Configuring PHP options
wordpress 16:43:49.61 INFO  ==> Setting PHP expose_php option
wordpress 16:43:49.62 INFO  ==> Setting PHP output_buffering option
wordpress 16:43:49.64 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 16:43:49.84 INFO  ==> Ensuring WordPress directories exist
wordpress 16:43:49.84 INFO  ==> Trying to connect to the database server
wordpress 16:43:49.88 INFO  ==> Configuring WordPress with settings provided via environment variables
wordpress 16:43:50.93 INFO  ==> Installing WordPress
wordpress 16:43:58.51 INFO  ==> Persisting WordPress installation
setfacl: wp-config.php: Operation not permitted
```

**Comment by chris8205** [comment]
@migruiz4 --> same log like @dakr0013 
thank you @dakr0013  for the log...

from my point of view there can be a mismatch from group vs user @filepermissions.... (1001 vs daemon vs root)
if i deploy the chart with "root" and "allowroot", also with elevated permissions... the deployment runs fine.
from "fsgroup" i've forced it to daemon so mount of the csi was done with root:daemon instead of root:1001

i'm not sure wich point of view seems to be the right one...
the view from the setfacl or if its only a false "mount" from UID and / or GID view...

one thing is sure, setfacl fails and then script stops.  ;)

**Comment by migruiz4** [comment]
In version 18.1.0 we introduced some changes to the chart securityContext (https://github.com/bitnami/charts/pull/20559)

Could you please confirm if the issue also exists in the previous version 18.0.12?

**Comment by guidoffm** [comment]
Please re-open this issue.

I found the cause of this issue:

They run a `setfacl` command in one shell script, I guess this here: 

https://github.com/bitnami/containers/blob/ca9fcb84f97abf085ce55b7f72fdb8f7b528bb80/bitnami/wordpress/6/debian-11/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L60

But `setfacl` is not supported on every type of filesystem. For me I use NFS and NFS does not support 'setfacl`.

This causes the container to die.

**Comment by chris8205** [comment]
Yes, but it seems that there is  it the same error handling or result on different distributions… 
Busybox seems to ignore if setacl can’t change permissions on nfs, if you’re trying the same on a Debian you’ll get a error message that it isn’t allowed/no permission to do the change.

but I’ve in mind that with elevated privileges from deployment site that is was running fine, or of the permissions are forced to the final group / users 
Setacl need nothing to do, so the error is not thrown.

**Comment by guidoffm** [comment]
One way to workaround this issue is tu disable persistence completely. 
for this you can set

```yaml
        persistence:
          enabled: false
```

But I do not know if persistence is required.

**Comment by chris8205** [comment]
It depends on your environment…
Theoretically only the database persistence is needed… but if you’re using custom themes or specific plugins,… you’ve to pre-load them …

but the persistence is much easier to do with the integrated chart / image … but it’s setacl-bugged

**Comment by nfacha** [comment]
Also facing this issue

**Comment by helders** [comment]
@lemonprogis i had the same issue, after creating the StorageClass with the parameters you proposed it worked fine again.

Thanks a lot!

**Comment by lemonprogis** [comment]
You are welcome @helders! Something else I ran into is Premium_LRS does work better than Standard_LRS, BUT NetApps File actually works the best from a latency perspective. The pattern above works, but need to define a different StorageClass. 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-netapp-files
provisioner: csi.trident.netapp.io
parameters:
  backendType: "azure-netapp-files"
  fsType: "nfs"
reclaimPolicy: Retain
allowVolumeExpansion: true
```
