### ISSUE TITLE
Make instances of supabase storage configurable

### ISSUE THREAD

**Issue by jsmueller7** [bitnami/charts#20776]
### Name and Version

bitnami/supabase 2.1.1

### What is the problem this feature will solve?

The configs of supabase storage are written in a file `ecosystem.config.js` that's executed as arg on launch of the container:

```
module.exports = {
  apps: [
    {
      instances: 'max',
      env: {
        NODE_ENV: 'production',
      },
      script: 'dist/server.js',
    },
  ],
}
```
`instances: 'max'` leads to a massive waste of RAM in a large cluster. By now the config file must be overmounted; having a direct way to control the number of instances through the helm chart is more desirable.

### What is the feature you are proposing to solve the problem?

Waste of memory.

### What alternatives have you considered?

This is the best alternative.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
