### ISSUE TITLE
[bitnami/grafana] Secret name in NOTES.txt not updated

### ISSUE THREAD

**Issue by yi-jiayu** [bitnami/charts#2081]
**Which chart**:

bitnami/grafana@1.3.3

**Description**

The notes for bitnami/grafana include a command to print out the Grafana admin password. However, the secret name it uses was recently changed so the command no longer works.

In `NOTES.txt` the secret is called `grafana-secret`:

https://github.com/bitnami/charts/blob/301bb18b0f8455d6f64c26aedd50ee9d7c74c221/bitnami/grafana/templates/NOTES.txt#L28

In `secret.yaml` it has been changed to `grafana-admin` in a [recent commit](https://github.com/bitnami/charts/commit/b68f39fe8c4fc1e50b835776aa43663d936a608a#diff-9ceb7dc7b056dde66dda2f5553152c2dR5):

https://github.com/bitnami/charts/blob/301bb18b0f8455d6f64c26aedd50ee9d7c74c221/bitnami/grafana/templates/secret.yaml#L5

**Steps to reproduce the issue:**

1. Install/upgrade bitnami/grafana to 1.3.3
2. Try to print the admin password using the command given

**Describe the results you received:**

```
$ kubectl get secret grafana-secret --namespace metrics -o jsonpath="{.data.GF_SECURITY_ADMIN_PASSWORD}" | base64 --decode
Error from server (NotFound): secrets "grafana-secret" not found
```

**Describe the results you expected:**

```
$ kubectl get secret grafana-secret --namespace metrics -o jsonpath="{.data.GF_SECURITY_ADMIN_PASSWORD}" | base64 --decode
password
```

**Comment by carrodher** [comment]
Thanks for creating this issue. I just created a PR to solve it!
