### ISSUE TITLE
include a postgresql version for cloudnative-pg

### ISSUE THREAD

**Issue by wibed** [bitnami/charts#20822]
### Name and Version

bitnami/cloudnative-pg

### What is the problem this feature will solve?

the project page
- https://github.com/cloudnative-pg/cloudnative-pg

a working implementation of a chart
- https://github.com/itay-grudev/cloudnative-pg-charts

having 2 separate helm charts that diverge

### What is the feature you are proposing to solve the problem?

postgres has quite a few settings,  and the repo has 2 successful implementation of such.
it would be great if that experience could carry over to the cloudnative-pg project aswell.

### What alternatives have you considered?

reinvent the wheel on another repo

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
