### ISSUE TITLE
[harbor] remove scandata on jobservice

### ISSUE THREAD

**Issue by sebglon** [bitnami/charts#20862]
### Name and Version

bitnami/harbor: 19.0.5

### What architecture are you using?

None

### What steps will reproduce the bug?

Related to the issue https://github.com/goharbor/harbor-helm/issues/1320
### What is the expected behavior?

Remove the scandata volume on jobservice like here: https://github.com/goharbor/harbor-helm/pull/1378/files

### What do you see instead?

Impossible to scale jobservice

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by sebglon** [comment]
@carrodher a PR is created. Thanks for your help to merge it.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
