### ISSUE TITLE
[rabbitmq-ha] epmd error for host rabbitmq-ha-0.rabbitmq-ha-discovery

### ISSUE THREAD

**Issue by arianf** [bitnami/charts#2086]
**Which chart**:
Name: `rabbitmq-ha`
Version: `3.8.0`

**Description**

rabbitmq-ha-0 is getting into a crash loop..

```
$ k get pods/rabbitmq-ha-0 
NAME            READY   STATUS             RESTARTS   AGE
rabbitmq-ha-0   0/1     CrashLoopBackOff   4          6m9s
```

```
$ k get svc -o wide
NAME                          TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)                       AGE     SELECTOR
rabbitmq-ha                   ClusterIP   192.168.232.97    <none>        15672/TCP,5672/TCP,4369/TCP   9m59s   app=rabbitmq-ha,release=sentry-db
rabbitmq-ha-discovery         ClusterIP   None              <none>        15672/TCP,5672/TCP,4369/TCP   9m59s   app=rabbitmq-ha,release=sentry-db
```

When I try to check the logs, I get:
```
k logs rabbitmq-ha-0     
ERROR: epmd error for host rabbitmq-ha-0.rabbitmq-ha-discovery.sentry-production.svc.cluster.local: nxdomain (non-existing domain)
```

**Steps to reproduce the issue:**

1. `helm install sentry-db .`
2. problem happens

**Describe the results you received:**

Unsuccessful deploy

**Describe the results you expected:**

Succesful deploy

**Additional information you deem important (e.g. issue happens only occasionally):**

My clusters ingress and egress is set to deny all by default

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @arianf 

There's no `rabbitmq-ha` chart in this repository, but a `rabbitmq` chart instead.

Are you using the [one at the stable repository](https://github.com/helm/charts/tree/master/stable/rabbitmq-ha)? Please note we're not the maintainers of that chart.
