### ISSUE TITLE
MLflow --no-serve-artifacts

### ISSUE THREAD

**Issue by juftin** [bitnami/charts#20892]
### Name and Version

bitnami/mlflow:0.2.3

### What is the problem this feature will solve?

The MLflow template chart currently uses the [--serve-artifacts](https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-server-serve-artifacts) feature on the server. On the [MLflow documentation](https://mlflow.org/docs/latest/tracking.html) this is described as [Scenario 5](https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access):
> MLflow Tracking Server enabled with proxied artifact storage access

<details><summary>Scenario 5</summary>
<p>

> MLflow’s Tracking Server supports utilizing the host as a proxy server for operations involving artifacts. Once configured with the appropriate access requirements, an administrator can start the tracking server to enable assumed-role operations involving the saving, loading, or listing of model artifacts, images, documents, and files. This eliminates the need to allow end users to have direct path access to a remote object store (e.g., s3, adls, gcs, hdfs) for artifact handling and eliminates the need for an end-user to provide access credentials to interact with an underlying object store.

![image](https://github.com/bitnami/charts/assets/49741340/b34c08ab-b952-4b08-a7fd-bc766f8dab51)

</p>
</details> 

This means that client doesn't require permissions to access the Artifact storage (like the S3 backend) - and instead those objects are served over HTTP. 

Unfortunately this deployment method doesn't support our use case, we are more interested in [Scenario 4](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores):
> MLflow with remote Tracking Server, backend and artifact stores

<details><summary>Scenario 4</summary>
<p>

> MLflow also supports distributed architectures, where the tracking server, backend store, and artifact store reside on remote hosts. This example scenario depicts an architecture with a remote MLflow Tracking Server, a Postgres database for backend entity storage, and an S3 bucket for artifact storage.

![image](https://github.com/bitnami/charts/assets/49741340/32b64f0e-1b97-441c-a988-5405ab40de08)

</p>
</details>

In scenario 4 the MLflow tracking server informs the client where the artifacts are located on the S3 remote host and the client itself fetches the artifacts directly from S3. This is nice for a couple of reasons:

1. Performance - we are working with extremely large artifacts - these artifacts are large enough that the tracking server can struggle to handle the serving over HTTP. Relying on the client to handle this improves performance and allows us to only allocate limited resources to the tracking server.
2. Security - relying on both the Client and server to have permissions to the S3 backend resolves some concerns of our security team. 

### What is the feature you are proposing to solve the problem?

The feature I'm suggesting is a feature-flag on the `values.yaml` that would make the `--serve-artifacts` argument optional on the underlying template https://github.com/bitnami/charts/blob/b65f50c0d3853f784c620b629d268ef783f2b33c/bitnami/mlflow/templates/tracking/deployment.yaml#L141-L147

Using (an optional) `--no-serve-artifacts` alongside [--default-artifact-root](https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-server-default-artifact-root) would make this Chart compatible with both scenarios listed above.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by bhack** [comment]
There is a connected PR @carrodher probably we could improve the github-actions conf/policy.
