### ISSUE TITLE
SCRAM authentication failed - backend response with kind 'E' when expecting 'R' && pool_passwd file does not contain an entry for "xxxx"

### ISSUE THREAD

**Issue by xtianus79** [bitnami/charts#20899]
### Name and Version

[bitnami/postgresql-ha]

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This isn't a bug but it is hella confusion for Postgres HA with PGPools. The TLDR is that you need the same user and password in the PGPool as you do in the database user you want to have access to the DB via a client. At first I couldn't figure out what the hell was going on so hopefully this just helps someone. 

Thankfully, I tied both of these posts together to give me clues as to what was going on. Unfortunately, they don't really come out and say what is happening with obviousness to make it apparent. The OP's fix their issue but the real explanation is not really realized so I hope to do it here. [Clue 1](https://github.com/bitnami/charts/issues/16396) [Clue 2](https://github.com/bitnami/charts/issues/16408) [Clue 3 The PG POOL DOCS](https://www.pgpool.net/docs/42/en/html/client-authentication.html) Like I said, along the way I got both errors. 

Ok, So basically (And even ChatGPT was confused as hell at figuring this out; ahem) the main point here is that PGPool is your client interface to your databases. Client <--> PGPool <--> PostgreSQL Servers ||FULL STOP|| Thanks @migruiz4 !!! 

What this tells you is that while a user is obviously needed in your Postgres DB instruction you need the exact same user and password in your client. 

> Since Pgpool-II is a middleware that works between PostgreSQL servers and a PostgreSQL database client, so when a client application connects to the Pgpool-II, Pgpool-II in turn connects to the PostgreSQL servers using the same credentials to serve the incoming client connection. **Thus, all the access privileges and restrictions defined for the user in PostgreSQL gets automatically applied to all Pgpool-II clients, with an exceptions of the authentications on PostgreSQL side that depends on the client's IP addresses or host names.** Reason being the connections to the PostgreSQL server are made by Pgpool-II on behalf of the connecting clients and PostgreSQL server can only see the IP address of the Pgpool-II server and not that of the actual client. Therefore, for the client host based authentications Pgpool-II has the pool_hba mechanism similar to the pg_hba mechanism for authenticating the incoming client connections.

There is a lot to unpack here. What this sentence "with an exceptions of the authentications on PostgreSQL side that depends on the client's IP addresses or host names." is saying is that basically while you can go directly into the server and effectively enter the main postgres pod/node (we're talking about K8's here) and localhost this command ` psql -U somenew_user -h localhost -d postgres` if the user was created in a normal postgres way (forget about pgpool for a second) it will log in to your DB with that user just fine. In short, if you go through the server directly and log in to that user it's fine; otherwise, from a client connection you're screwed. This was a big confusion/miss here. It works in localhost but not my client. 

So, this error: `FATAL: SCRAM authentication failed
  Detail: pool_passwd file does not contain an entry for "somenew_user` arises from trying to connect to the client with a user you may have created from a client in an SQL script. Related to `Clue 1`

// Sidenote: 
GPT was making the argument that they were 2 different abstractions. LOL, I just wanted to share the pain of the argument I was having with GPT basically fighting against the real principle. Adding hours to debugging instead of me just doing a Google search and finding the git issues. 

> You
what is a difference of pgpool user and a regular postgresql user. keep it short

> ChatGPT
A Pgpool user typically refers to a user account that is specifically for connecting to the Pgpool service, which may have administrative privileges within Pgpool and be used for managing Pgpool features and settings.

> A regular PostgreSQL user is an account that is used to connect directly to the PostgreSQL database to perform database operations like queries, updates, or schema changes.

> The key difference lies in their scope of use:
Pgpool User: Manages and interacts with the Pgpool connection pooler and load balancer.
PostgreSQL User: Interacts directly with the PostgreSQL database.

> You
that's odd. why would I want to add users to the pgpool. how can I test the user names and passwords I just created in dbeaver

As you see, round and round we went with no understanding of what the issue really was. I digress. 

Then also, from the clients perspective, I thought well let me try to use a user I had created with an `existingSecret` setting in the values.yaml for PGPool. I got this error: `ERROR: backend authentication failed
  Detail: backend response with kind 'E' when expecting 'R'
ERROR: backend authentication failed
  Detail: backend response with kind 'E' when expecting 'R'`. This also, emmits from the PGPool backend localhost call to postgreSQL through `psql`

This is related to `Clue 2`

Now, if I go back into my master postgreSQL node and try to (for some stupid reason I thought it would work) access one of the PGPool users. 

This error emits:
```bash
I have no name!@somepod-postgresql-ha-postgresql-2:/$ psql -U newUser_two -h localhost -d postgres
Password for user newUser_two:
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "newUser_two"
```
In this way, if postgreSQL server doesn't have the user and or wrong password it will emit that error message.

Needless to say, by tieing all things together it dawned on me that I need to go through the process of creating the exact same user on a postgreSQL DB as I do in the PGPool and you can't connect a client directly to a PostgreSQL server you have to go through PGPool. GPT you're wrong humans are still smarter ;) 

I hope this helps someone in the future.  Some clear documentation should make this much more clear. I'm sure this can be automated through scripts and jobs but setting it up and trying to figure what was going on was a PITA. 

### What is the expected behavior?

The expected behavior would be to have clear documentation so that the understanding is clear of how one should approach setting up a client with HA PGPool configuration. 

### What do you see instead?

Lot's of time debugging unnecessarily. It makes a lot more sense when you know what PGPool's involvement really is for in the process.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by VGerris** [comment]
Didn't anyone wonder what the meaning of E and R were in the error ? What a poor error message.
I get this when I disable pga_hba auth and allow clear text auth ( to test a way to work around double user creation ) but I get the error for both existing users in the file and the ones only in the database. The chart seems to have a solution that is to add the user, I will implement something similar I suppose.

**Comment by daemondev** [comment]
I avoid this error creating user in database, the user must be exists in the database
