### ISSUE TITLE
Chart Version 2.1.3 breaks Studio

### ISSUE THREAD

**Issue by jsmueller7** [bitnami/charts#20914]
### Name and Version

bitnami/supabase 2.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart
2. Navigate to studio
3. You'll get an "client side" error in your browser (tested with Chrome and Firefox)

### Are you using any custom parameters or values?

Many, but non that I can imagine to cause this problem.

### What is the expected behavior?

Studio is accessible

### What do you see instead?

The error.

### Additional information

Problem doesn't exist with chart version 2.1.2

**Comment by andresbono** [comment]
Hi thank you for reporting this issue. Could you please share more details about the "client side" error you mention? What is the specific error that you are facing?

**Comment by jsmueller7** [comment]
Hi @andresbono 
when I open studio after the upgrade i just see it for less than a second. Then the browser shows `Application error: a client-side exception has occurred (see the browser console for more information).`

In my browser console I can see these logs

```
_app-86f71816465632ed.js:38 [Warning] Please install/enable Redux devtools extension
ew @ _app-86f71816465632ed.js:38
framework-989c9c8f728099b7.js:25 TypeError: Cannot read properties of undefined (reading 'length')
    at y (603-358c181f050cef22.js:1:3608)
    at lk (framework-989c9c8f728099b7.js:25:60903)
    at i (framework-989c9c8f728099b7.js:25:119424)
    at uD (framework-989c9c8f728099b7.js:25:99077)
    at framework-989c9c8f728099b7.js:25:98944
    at uI (framework-989c9c8f728099b7.js:25:98951)
    at uE (framework-989c9c8f728099b7.js:25:95703)
    at uT (framework-989c9c8f728099b7.js:25:96092)
    at r6 (framework-989c9c8f728099b7.js:25:44813)
    at framework-989c9c8f728099b7.js:25:93603
l9 @ framework-989c9c8f728099b7.js:25
main-3c777cdbc22097e7.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at y (603-358c181f050cef22.js:1:3608)
    at lk (framework-989c9c8f728099b7.js:25:60903)
    at i (framework-989c9c8f728099b7.js:25:119424)
    at uD (framework-989c9c8f728099b7.js:25:99077)
    at framework-989c9c8f728099b7.js:25:98944
    at uI (framework-989c9c8f728099b7.js:25:98951)
    at uE (framework-989c9c8f728099b7.js:25:95703)
    at uT (framework-989c9c8f728099b7.js:25:96092)
    at r6 (framework-989c9c8f728099b7.js:25:44813)
    at framework-989c9c8f728099b7.js:25:93603
ec @ main-3c777cdbc22097e7.js:1
main-3c777cdbc22097e7.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ec @ main-3c777cdbc22097e7.js:1
projects:1 Uncaught (in promise) Objectmsg: "operation is manually canceled"type: "cancelation"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
```

As said, the error goes away when I downgrade back to chart version `2.1.2.`.

**Comment by andresbono** [comment]
It looks like the problematic path is `/projects`, right? Does the error appear for other paths like `/project/default`?

**Comment by jsmueller7** [comment]
I've just checked. Indeed I can access `/project/default` without problems.

**Comment by jsmueller7** [comment]
There are less errors in the console though.

**Comment by andresbono** [comment]
Thank you, @jsmueller7. We will investigate the issue and will update this issue. In the same way, please, let us know if you have any new findings.

**Comment by jsmueller7** [comment]
The fix itself works, but in your changes you've made adjustmens to the service of supabae studio that aren't working.
See my comments in this: 

https://github.com/bitnami/charts/commit/42f8da77f87b33c653d40974d8914b4e3d1da535#r137854538

https://github.com/bitnami/charts/commit/42f8da77f87b33c653d40974d8914b4e3d1da535#r137854596

Could you please revert these changes?

**Comment by dominik-horb-umg** [comment]
We are seeing problems with the studio ingress in `v2.8.0` due to a mismatch of the port name of the service:

https://github.com/bitnami/charts/blob/a5b06d44246f88e19f14e54c36c8bcf230a795f4/bitnami/supabase/templates/studio/service.yaml#L39

And the one referenced in the ingress manifest in these two places:

- https://github.com/bitnami/charts/blob/a5b06d44246f88e19f14e54c36c8bcf230a795f4/bitnami/supabase/templates/studio/ingress.yaml#L45
- https://github.com/bitnami/charts/blob/a5b06d44246f88e19f14e54c36c8bcf230a795f4/bitnami/supabase/templates/studio/ingress.yaml#L35
