### ISSUE TITLE
i have deployed bitnami testlink on azure unable to install bugzilla 

### ISSUE THREAD

**Issue by llsrinull** [bitnami/charts#2092]
any body have document to help installation and integration please

**Which chart**:

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by rafariossaa** [comment]
Hi,
  Could you elaborate on what you have tried so far, errors you get, etc ?
