### ISSUE TITLE
[bitnami/zookeeper] logs show prometheus metric 

### ISSUE THREAD

**Issue by bruse-peng** [bitnami/charts#20944]
### Name and Version

 bitnami/zookeeper

### What architecture are you using?

amd64

### What steps will reproduce the bug?

no

### Are you using any custom parameters or values?

i meet the issue how  can solve the issue
2023-11-14 22:38:02,364 [myid:] - WARN  [RequestThrottler:o.a.z.s.RateLogger@57] - [13342092 times] Message: Prometheus metrics reporting task queue size exceeded the max Last value:1000000

### What is the expected behavior?

no

### What do you see instead?

<img width="1435" alt="image" src="https://github.com/bitnami/charts/assets/47881861/fb15c700-6af8-4107-8172-dd45610cbca5">

### Additional information

no

**Comment by javsalgar** [comment]
Hi,

It looks to me that this is something more related to the upstream configuration settings rather than the Bitnami packaging of Zookeeper. Did you check with the Zookeeper devs to see how that parameter can be increased?
