### ISSUE TITLE
Template Bitnami/Wildfly for Ingress

### ISSUE THREAD

**Issue by twtakao** [bitnami/charts#20951]
### Name and Version

bitnami/wildfly

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi, in https://github.com/bitnami/charts/blob/main/bitnami/wildfly/templates/ingress.yaml there is a wrong value used.

Search for `.Values.persistence.annotations` should be `.Values.ingress.annotations`

Commit
https://github.com/bitnami/charts/commit/d56dec30d3704775e3d8914667c8185e857e34f5

Example:
`helm install teste bitnami/wildfly --dry-run  --set ingress.enabled=true --set "ingress.annotations.nginx\.ingress\.kubernetes\.io/whitelist-source-range=111.111.111.111"`

### Are you using any custom parameters or values?

` --set "ingress.annotations.nginx\.ingress\.kubernetes\.io/whitelist-source-range=111.111.111.111"`

### What is the expected behavior?
```yaml
annotations:
ingress.annotations.nginx.ingress.kubernetes.io/whitelist-source-range=111.111.111.111
```
### What do you see instead?
```yaml
annotations:
{}
```
### Additional information

Chart used 17.1.2 after updating repo

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
