### ISSUE TITLE
bitnami/mlflow helm chart issue with upgrade db during init.

### ISSUE THREAD

**Issue by lambertsbennett** [bitnami/charts#20963]
### Name and Version

bitnami/mlflow 0.2.3

### What architecture are you using?

None

### What steps will reproduce the bug?
```
helm install mlflow bitnami/mlflow
helm uninstall mlflow
helm install mlflow bitnami/mlflow
```
### Are you using any custom parameters or values?

Nothing altered.

### What is the expected behavior?

mlflow should start up and respect the runUpgradeDB value.

### What do you see instead?

upon startup the second time the mlflow-tracking container hits a crashloopbackoff where the error is "Back-off restarting failed container upgrade-db-auth in pod ..."

**Comment by bhack** [comment]
I confirm this issue

**Comment by bhack** [comment]
@fevisera I have already https://github.com/bitnami/charts/pull/21217

But why does this happen also on upgrade?

**Comment by fevisera** [comment]
Hi @bhack,

Sorry for the delay. Could you please provide additional details, parameters, logs, and the specific commands you are executing for the upgrade?

Thank you.

**Comment by bhack** [comment]
I don't have a clean setup now to install and upgrade again but just try on you setup to to:
`helm install mlflow bitnami/mlflow` with the previous version

and then 

`helm upgrade mlflow bitnami/mlflow` with the latest one.

**Comment by fevisera** [comment]
Hi @bhack,

I was unable to reproduce the error you mentioned. When you have a moment, could you kindly share the logs you are receiving? From which version are you attempting to upgrade?

Here are the steps I took:
```
$ helm install mlflow bitnami/mlflow --create-namespace --version 0.2.8
...
CHART NAME: mlflow
CHART VERSION: 0.2.8
APP VERSION: 2.8.1
...
$ kubectl get po
NAME                               READY   STATUS      RESTARTS   AGE
mlflow-minio-6466d7f4b6-7sbbg      1/1     Running     0          102s
mlflow-minio-provisioning-lcfhl    0/1     Completed   0          101s
mlflow-postgresql-0                1/1     Running     0          102s
mlflow-run-84fdd59d6c-6jths        1/1     Running     0          102s
mlflow-tracking-5ddc5d57b5-2q4qh   1/1     Running     0          102s
$ helm upgrade mlflow bitnami/mlflow
...
CHART NAME: mlflow
CHART VERSION: 0.3.0
APP VERSION: 2.8.1
...
$ kubectl get po
NAME                               READY   STATUS      RESTARTS   AGE
mlflow-minio-b6c4ccc55-gdv2j       1/1     Running     0          63s
mlflow-minio-provisioning-wz8l4    0/1     Completed   0          65s
mlflow-postgresql-0                1/1     Running     0          3m40s
mlflow-run-57d6c8bdcb-h7x97        1/1     Running     0          65s
mlflow-tracking-6fd6f6977d-h7g4q   1/1     Running     0          65s
```

Thanks.

**Comment by bhack** [comment]
I don't see the helm upgrade in your command

**Comment by bhack** [comment]
@fevisera I've uninstalled the helm and remove all pv/pvc and just installing the last version I have bot run and tracking pods stuck in init.
The log is:
```
Defaulted container "mlflow" out of: mlflow, wait-for-database (init), get-default-auth-conf (init), render-auth-conf (init), upgrade-db-auth (init)
```

**Comment by bhack** [comment]
Ok nevermind it was a perrmission issue.

We could still check what we want to do at:
https://github.com/bitnami/charts/pull/21217

**Comment by lambertsbennett** [comment]
OK seeing as how this is more of a feature than a bug, I will close this issue.
