### ISSUE TITLE
[bitnami/grafana-operator]: `namespaceScope=true` restricts grafana to the local namespace, but is needed to restrict to an allowlist of namespaces

### ISSUE THREAD

**Issue by dazoakley** [bitnami/charts#20960]
### Name and Version

bitnami/grafana-operator 3.5.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We're running multiple deployments of the operator in the same cluster so we need to restrict the namespaces each deployment watches.

Deploy a basic operator with the configuration below, then it won't be able to observe any other namespaces.

I can submit a PR with the simple fix, but I'm not sure if there are tests or anything that needs to be updated...

### Are you using any custom parameters or values?

```yaml
nameOverride: sandbox

operator:
    namespaceScope: true
    watchNamespace: grafana-sandbox,monitoring-sandbox
```

### What is the expected behavior?

We'd expect the operator to watch the defined namespaces.

### What do you see instead?

The following RBAC permissions errors:

```
E1115 08:31:43.935838       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1beta1.Grafana: failed to list *v1beta1.Grafana: grafanas.grafana.integreatly.org is forbidden: User "system:serviceaccount:grafana-sandbox:grafana-sandbox" cannot list resource "grafanas" in API group "grafana.integreatly.org" in the namespace "monitoring-sandbox"
```

### Additional information

This is due to the fact that `operator.namespaceScope=true` is needed for the `operator.watchNamespace` setting to be applied in the deployment template here: https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/templates/deployment.yaml#L123

But if you define `operator.namespaceScope=true` then it disables the cluster scope here: https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/templates/rbac-clustescope.yaml#L6 and enables a namespaced scoped rolebinding here: https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/templates/rbac-namespace.yaml#L6

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
