### ISSUE TITLE
Mongodb: metrics exporter cannot connect to mongodb if root password contains @

### ISSUE THREAD

**Issue by lff0305** [bitnami/charts#2096]
We use strong passwords and it contains @ 
However we found that after mongo chart is deployed , metric export container cannot connect to mongodb.

After investigating, we found that because there is a @ in the root password, metrics exporter will run as
`/bin/mongodb_exporter --mongodb.uri mongodb://root:aaaa@bbbb@localhost:27017/admin`. 
Since first @ is used to split the fields, 
user: root
password: aaaa
hostname: bbbb@localhost
of course the hostname is not correct.

To resolve:
update the metric container template to
```
command: [ 'sh', '-c', '/bin/mongodb_exporter --mongodb.uri mongodb://root:`echo $MONGODB_ROOT_PASSWORD | sed -r "s/@/%40/g"`@localhost:{{ .Values.service.port }}/admin {{ .Values.metrics.extraArgs }}' ]
```

**Comment by andresbono** [comment]
Thanks for reporting this issue, @lff0305.

Would you like to open a PR addressing the issue? Your solution sounds good!

**Comment by lff0305** [comment]
PR submitted : https://github.com/bitnami/charts/pull/2099
Please review.

**Comment by andresbono** [comment]
#2099 is now merged, thanks for your contribution!
