### ISSUE TITLE
[bitnami/kafka] ACL rules

### ISSUE THREAD

**Issue by ozahavi** [bitnami/charts#20974]
### Name and Version

bitnami/kafka 26.3.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I have configured my Kafka cluster with two topics and two users, but I cannot understand from the docs where I should configure the actual ACL and assign each user permissions to a topic (ACL rules).

### Are you using any custom parameters or values?

```
(
      {
        service = {
          headless = {
            publishNotReadyAddresses = true
          }
        }

        extraConfig = [
          {
            authorizerClassName="kafka.security.auth.SimpleAclAuthorizer"
          }
        ]

        kraft = {
          enabled = true
        }

        provisioning = {
          enabled           = true
          numPartitions     = 2
          replicationFactor = 3
          topics            = ["topic1","topic2"]
        }

        controller = {
          replicaCount = 2
        }

        broker = {
          replicaCount = 2
        }

        sasl = {
          client = {
            users     = ["user1", "user2"]
            passwords = ["pass1", "pass2"]
          }
        }
    })
```

**Comment by javsalgar** [comment]
Hi,

Did you try the `provisioning.extraProvisioningCommands` value? There you could configure extra settings for the topic

**Comment by ozahavi** [comment]
> Hi,
> 
> Did you try the `provisioning.extraProvisioningCommands` value? There you could configure extra settings for the topic

Nope, I was thinking of configuring it via `extraConfig` similar to the way I configured `authorizerClassName`. 
The question is, what are the needed keys and the structure that need to be added in?

**Comment by javsalgar** [comment]
Hi,

It seems that this question is more related to the usage of Minio itself rather than the Bitnami packaging of the application. Did you check the MinIO documentation or their support page?

**Comment by ozahavi** [comment]
> Hi,
> 
> It seems that this question is more related to the usage of Minio itself rather than the Bitnami packaging of the application. Did you check the MinIO documentation or their support page?

This is for Kafka not Minio

**Comment by FraPazGal** [comment]
Hello @ozahavi, could it be you are parsing the `extraConfig` param as an array? It expects a single string so it should be something like this:
```
$ helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka --set extraConfig="authorizerClassName=kafka.security.auth.StandardAuthorizer",...
```

**Comment by ozahavi** [comment]
@FraPazGal @javsalgar any suggestions?

**Comment by FraPazGal** [comment]
I think this comes from a syntax error. Going by [Kafka's documentation](https://docs.confluent.io/platform/current/kafka/authorization.html#kraft-based-ak-clusters), you should be using the following syntax:

```
authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer

#### Using it our chart ####
$ helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka --set extraConfig="authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer",...
```

It's possible you got confused by our README, as `authorizerClassName` was a custom parameter we used that was later on parsed for Kafka (see that https://github.com/bitnami/charts/blob/main/bitnami/kafka/README.md?plain=1#L1125-L1152 refers to deprecated settings of our chart).

Could you try using the official syntax? If the issue persist please share with an updated values info to help us reproduce the error on our side.
