### ISSUE TITLE
There is no possibility to add annotations only for specific daemonset/deployment/statefulset.

### ISSUE THREAD

**Issue by agrevtsev** [bitnami/charts#20983]
### Name and Version

bitnami/template

### What is the problem this feature will solve?

There is no possibility to add annotations only for specific daemonset/deployment/statefulset.
My proposal is introduce such entities as deploymentAnnotations, statefulsetAnnotations and daemonsetAnnotations, as for now we can only apply annotations to daemonset/deployment/statefulset globally, by the means of .Values.commonAnnotations.
For example: when one wants to use [stakater/Reloader](https://github.com/stakater/Reloader) to reload daemonset/deployment/statefulset on secret/configmap change, one must add specific annotation to the entity one wants to manage as such.

### What is the feature you are proposing to solve the problem?

My idea is to transform templates for daemonset/deployment/statefulset as such (e.g. for deployment):
```
  {{- if or .Values.%%MAIN_OBJECT_BLOCK%%.deploymentAnnotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.%%MAIN_OBJECT_BLOCK%%.deploymentAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.%%MAIN_OBJECT_BLOCK%%.deploymentAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
```
IDK if such changes could be considered following "best practice", and ready to provide PR if so.

Cheers!

**Comment by javsalgar** [comment]
Hi!

I think that in other charts, what we have is `annotations`, but it's true that it can be a bit confusing. Would you like to submit a PR adding that feature to the template?

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
