### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] - Backup Rabbitmq cluster via Kanister blueprint

### ISSUE THREAD

**Issue by brandtwinchell** [bitnami/charts#21021]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.10.3

### What is the problem this feature will solve?

I cannot find any specific documentation on how to correctly quiesce a RabbitMQ cluster to perform any type of backup.  When attempting to restore a cluster currently (using Kasten K10), the process fails while trying to terminate the existing pods as the 'prestophook' fails and then all Rabbitmq pods remain in this state.  The K10 restore eventually fails with:
``` message: Failed to delete associated PVCs ```

``` kubectl describe ```
```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        18m                default-scheduler        0/9 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/9 nodes are available: 9 No preemption victims found for incoming pod..
  Normal   Scheduled               18m                default-scheduler        Successfully assigned compass-staging/rabbitmq-cluster01-ra-server-0 to k8-clst39-wkr02
  Normal   SuccessfulAttachVolume  18m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8ad62826-070a-4370-9c5a-hgfhgfhgfhfhh"
  Normal   Pulling                 18m                kubelet                  Pulling image "docker.io/bitnami/rabbitmq:3.10.14-debian-11-r1"
  Normal   Pulled                  18m                kubelet                  Successfully pulled image "docker.io/bitnami/rabbitmq:3.10.14-debian-11-r1" in 436.917297ms (818.779836ms including waiting)
  Normal   Created                 18m                kubelet                  Created container setup-container
  Normal   Started                 18m                kubelet                  Started container setup-container
  Normal   Pulling                 17m                kubelet                  Pulling image "docker.io/bitnami/rabbitmq:3.10.14-debian-11-r1"
  Normal   Pulled                  17m                kubelet                  Successfully pulled image "docker.io/bitnami/rabbitmq:3.10.14-debian-11-r1" in 309.088673ms (309.452316ms including waiting)
  Normal   Created                 17m                kubelet                  Created container rabbitmq
  Normal   Started                 17m                kubelet                  Started container rabbitmq
  Normal   Killing                 17m                kubelet                  Stopping container rabbitmq
  Warning  FailedPreStopHook       17m                kubelet                  PreStopHook failed
  Warning  Unhealthy               16m (x9 over 17m)  kubelet                  Readiness probe failed: dial tcp X.X.X.X:5672: connect: connection refused
```

**Environment:**
kubeadm v1.26.5
kasten v6.0.11
rabbitmq-cluster-operator v3.10.3

### What is the feature you are proposing to solve the problem?

open to suggestions.  I do not know if any type of stun/quiesce feature is already available or not

### What alternatives have you considered?

I am not sure if reducing the replica count down to 1 pod, perform the backup/restore, and then increase the replica count will work.  I have not successfully been able to accomplish this via Kanister blueprints

**Comment by brandtwinchell** [comment]
So looks like RabbitMQ Operator does not support scaledown operations.
```
"msg":"Cluster Scale down not supported; tried to scale cluster from 3 nodes to 1 nodes","controller":"rabbitmqcluster","controllerGroup":"rabbitmq.com","controllerKind":"RabbitmqCluster","RabbitmqCluster":{"name":"rabbitmq-cluster100-ra"
```

**Comment by brandtwinchell** [comment]
Finally found the backup/restore docs on [VMware](https://docs.vmware.com/en/VMware-RabbitMQ-for-Kubernetes/1/rmq/backup.html).
Seems there is no way to really backup a cluster with quorum queues?

**Comment by brandtwinchell** [comment]
So now the issue is using K10 to restore the Rabbitmq cluster;

- K10 tries to scale down the cluster to replace the PV & pods
- this process fails as the operator does not support scale down

So what is the recommended way to actually restore a Rabbit cluster?

**Comment by javsalgar** [comment]
Hi,

It seems to me that the question is not releated with the Bitnami packaging of rabbitmq-cluster-operator. Instead, it seems to be related with the operator itself.  Could you check with the upstrream devs? https://github.com/rabbitmq/cluster-operator
