### ISSUE TITLE
Can't scale replicas, even when using external data source

### ISSUE THREAD

**Issue by vivet** [bitnami/charts#21027]
### Name and Version

bitnami/grafana:9.5.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Just set replica to 2.

### Are you using any custom parameters or values?

I am setting the ExtraEnvVars for MySQL data source.
```
--set grafana.extraEnvVars[0].name=GF_DATABASE_TYPE
--set grafana.extraEnvVars[0].value="mysql"
--set grafana.extraEnvVars[1].name=GF_DATABASE_HOST
--set grafana.extraEnvVars[1].value=$env:MYSQL_HOST
--set grafana.extraEnvVars[2].name=GF_DATABASE_USER
--set grafana.extraEnvVars[2].value=$env:MYSQL_ADMIN_USER
--set grafana.extraEnvVars[3].name=GF_DATABASE_PASSWORD
--set grafana.extraEnvVars[3].value=$env:MYSQL_ADMIN_PASSWORD
--set grafana.extraEnvVars[4].name=GF_DATABASE_SSL_MODE
--set grafana.extraEnvVars[4].value="skip-verify"
--set grafana.extraEnvVars[5].name=GF_DATABASE_CA_CERT_PATH
--set grafana.extraEnvVars[5].value="/etc/mysql/certs/DigiCertGlobalRootCA.crt.pem"
--set grafana.extraEnvVars[6].name=GF_DATABASE_SERVER_CERT_NAME
--set grafana.extraEnvVars[6].value=$env:MYSQL_HOST
--set grafana.extraVolumes[0].name="mysql-ssl-volume"
--set grafana.extraVolumes[0].secret.secretName="grafana-mysql-cert"
--set grafana.extraVolumeMounts[0].name="mysql-ssl-volume"
--set grafana.extraVolumeMounts[0].mountPath="/etc/mysql/certs"
--set grafana.extraVolumeMounts[0].readOnly="true"
```
### What is the expected behavior?

That I can scale the number of replicas when using an external data source.

### What do you see instead?

The pod stays in Container creating, with an event warning.

```
Warning  FailedMount  14s (x511 over 19h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data], failed to process volumes=[]: timed out waiting for the condition
```

### Additional information

Is there a parameter to use for letting the chart know that I am using a MySQL external data source?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
