### ISSUE TITLE
[bitnami/kibana] Kibana web interface authorization

### ISSUE THREAD

**Issue by xriser** [bitnami/charts#2103]
Is there some way to setup authorization in the Kibana web interface?

**Comment by dani8art** [comment]
Hi @xriser, thank you for opening this issue, Kibana and Elasticsearch use X-pack to implement security, you can find the instructions here:
- https://www.elastic.co/guide/en/elasticsearch/reference/7.6/configuring-security.html
- https://www.elastic.co/guide/en/kibana/7.6/using-kibana-with-security.html

We package the open-source version of kibana and elasticsearh, unfortunately, this version of the stack doesn't have access to the authentication feature see https://www.elastic.co/subscriptions

However, you can try other approaches like https://aboullaite.me/secure-kibana-keycloak/ using our images https://github.com/bitnami/bitnami-docker-keycloak-gatekeeper
