### ISSUE TITLE
Schema Registry Prometheus Monitoring

### ISSUE THREAD

**Issue by kisermichael** [bitnami/charts#21034]
### Name and Version

bitnami/schema-registry

### What is the problem this feature will solve?

Would like to monitor the Schema Registry with Prometheus

### What is the feature you are proposing to solve the problem?

Updating of the values file to include the jmx and prometheus variables as well as adding the appropriate jmx config maps.     This can be seen in the confluent helm charts (https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-schema-registry)

### What alternatives have you considered?

Currently not monitoring

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kemalgoklensadapay** [comment]
Any plans to introduce this one?

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
