### ISSUE TITLE
Redis (in Sentinel mode) via Helm chart starts really slowly

### ISSUE THREAD

**Issue by phlegx** [bitnami/charts#21036]
### Name and Version

bitnami/redis:7.0.11

### What is the problem this feature will solve?

I'm currently running a 3 node Redis sentinel cluster. It seems that on the initial setup starting the first Redis instance takes quite a while 3-4 minutes. I'm not exactly sure why though.

Also I have a cluster with a single node for testing purposes only.  On this I only run a single instance of Redis. Here the slow start/restart when deleting the pod is always an issue then.

 Is this a normal behavior or can this be influenced via some settings?
 
 What is see in the logs during that time is the following:
 
```
 sentinel  14:21:45.90 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 220 redis-cli -h auth-redis-cache.auth-databases.svc.cluster.local -p 26379 sentinel get-master-addr-by-name auth-redis-cache-master
redis  14:21:45.71 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 220 redis-cli -h auth-redis-cache.auth-databases.svc.cluster.local -p 26379 sentinel get-master-addr-by-name auth-redis-cache-master
Stream closed EOF for auth-databases/auth-redis-cache-node-0 (redis)
```

Log after successfully "restarting" (single instance on test cluster)

```
 │ sentinel  14:21:45.90 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 220 redis-cli -h auth-redis-cache.au │
│ sentinel 1:X 17 Nov 2023 14:25:25.979 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo                                                │
│ sentinel 1:X 17 Nov 2023 14:25:25.979 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started              │
│ sentinel 1:X 17 Nov 2023 14:25:25.979 # Configuration loaded                                                                         │
│ sentinel 1:X 17 Nov 2023 14:25:25.980 * monotonic clock: POSIX clock_gettime                                                         │
│ sentinel 1:X 17 Nov 2023 14:25:25.982 * Running mode=sentinel, port=26379.                                                           │
│ sentinel 1:X 17 Nov 2023 14:25:25.983 # Sentinel ID is 776d550f63296a466a48dbb75dbe4a7f9eda51a1                                      │
│ sentinel 1:X 17 Nov 2023 14:25:25.983 # +monitor master auth-redis-cache-master auth-redis-cache-node-0.auth-redis-cache-headless.au │
│ Stream closed EOF for auth-databases/auth-redis-cache-node-0 (sentinel)                                                              │
│ redis  14:21:45.71 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD timeout 220 redis-cli -h auth-redis-cache.auth- │
│ redis  14:25:25.72 INFO  ==> Configuring the node as master                                                                          │
│ redis 1:C 17 Nov 2023 14:25:25.762 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo                                                   │
│ redis 1:C 17 Nov 2023 14:25:25.762 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started                 │
│ redis 1:C 17 Nov 2023 14:25:25.762 # Configuration loaded                                                                            │
│ redis 1:M 17 Nov 2023 14:25:25.763 * monotonic clock: POSIX clock_gettime                                                            │
│ redis 1:M 17 Nov 2023 14:25:25.764 * Running mode=standalone, port=6379.                                                             │
│ redis 1:M 17 Nov 2023 14:25:25.764 # Server initialized                                                                              │
│ redis 1:M 17 Nov 2023 14:25:25.767 * Creating AOF base file appendonly.aof.1.base.rdb on server start                                │
│ redis 1:M 17 Nov 2023 14:25:25.768 * Creating AOF incr file appendonly.aof.1.incr.aof on server start                                │
│ redis 1:M 17 Nov 2023 14:25:25.768 * Ready to accept connections                                                                     │
│ Stream closed EOF for auth-databases/auth-redis-cache-node-0 (redis) 
```

**EDIT:** it seems that this `timeout 220` is pretty much close to the exact time this starting process takes.

 thanks a lot in advance

### What is the feature you are proposing to solve the problem?

Depends, if there is a setting that influences the behavior already, then please provide this. Otherwise please implement a fix.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
