### ISSUE TITLE
[bitnami/postgresql] password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by netblack** [bitnami/charts#21049]
### Name and Version

bitnami/postgresql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the helm chart in a Kubernetes cluster 
2. Retrieve the password from the secret
3. Log in to the postgres node and execute "psql -U postgres" and type the password from the config

### Are you using any custom parameters or values?

Not specifying custom variables.

### What do you see instead?

$ psql -U postgres
Password for user postgres:
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: fe_sendauth: no password supplied

### Additional information

In the usage documentation of the image, employ POSTGRESQL_PASSWORD as the default password for the administrator account. However, in bitnami/postgresql/templates/primary/statefulset.yaml, the environmental variable used is named POSTGRES_PASSWORD. It is imperative that these two variables align for consistency."

**Comment by javsalgar** [comment]
Hi,

It seems there is an issue with the terminal, as it says that no password was supplied. Could you try using `PGPASSWORD` before launching the command?

**Comment by netblack** [comment]
Thanks for you reply.

**Comment by Mauraza** [comment]
Hi @netblack,

If you check https://github.com/bitnami/containers/blob/main/bitnami/postgresql/16/debian-11/rootfs/opt/bitnami/scripts/postgresql-env.sh, it appears both variables POSTGRESQL_PASSWORD and  POSTGRES_PASSWORD.
