### ISSUE TITLE
[bitnami/mongodb] TLS Configuration Issue Without mTLS

### ISSUE THREAD

**Issue by emahdij** [bitnami/charts#21052]
### Name and Version

bitnami/mongodb:14.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello Bitnami Charts Team,

I am referencing a previously reported issue #13317, where deploying MongoDB with TLS enabled without requiring mTLS was not possible due to the --tlsCAFile flag being set by default.

I am experiencing a similar problem with the latest version of the MongoDB chart (14.2.5). When attempting to deploy MongoDB with TLS, the system defaults to requiring mTLS. This behavior is contrary to my requirements, where I need to establish TLS connections without enforcing client certificate verification.

Could you provide a resolution or a workaround that allows the use of TLS without mTLS? 

Thank you for your assistance.

### What do you see instead?

Applications connect to MongoDB without SSL requirements.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Tuurkevg** [comment]
Is there an solution? I got the exact same problem. It just wont start and don't give me any usefull errors.
