### ISSUE TITLE
[bitnami/cassandra] Is there a plan to create a Helm chart for Cassandra version 5.0?

### ISSUE THREAD

**Issue by Tingfing6** [bitnami/charts#21054]
### Name and Version

Cassandra/5.0

### What is the problem this feature will solve?

Currently, the latest version of the Cassandra Helm chart is 4.1.3. However, I would like to experiment with Cassandra version 5.0.

### What is the feature you are proposing to solve the problem?

Currently, the latest version of the Cassandra Helm chart is 4.1.3. However, I would like to experiment with Cassandra version 5.0.

### What alternatives have you considered?

Currently, the latest version of the Cassandra Helm chart is 4.1.3. However, I would like to experiment with Cassandra version 5.0.

**Comment by javsalgar** [comment]
Hi!

Looking at the tags here https://github.com/apache/cassandra/tags, it seems that Cassandra 5.0 is still in alpha stage. As soon as it becomes stable, we will package the container and, at some point, the chart will be updated as well.

**Comment by Tingfing6** [comment]
> Hi!
> 
> Looking at the tags here https://github.com/apache/cassandra/tags, it seems that Cassandra 5.0 is still in alpha stage. As soon as it becomes stable, we will package the container and, at some point, the chart will be updated as well.

Thank you for your response.
