### ISSUE TITLE
[bitnami/spark]  with revrse proxy and ssl 

### ISSUE THREAD

**Issue by nevo11** [bitnami/charts#21062]
### Name and Version

bitnami/spark/

### What architecture are you using?

None

### What steps will reproduce the bug?

I configured the spark master to be a reverse proxy and it worked, then i configured spark to work in ssl configuration , but the following error occured when i try to use the functionality of the reverse proxy:
500 java.lang.nullpointerexception missing sslcontextfactory

### Are you using any custom parameters or values?

no

### What is the expected behavior?

to work in master reverse proxy configuration with ssl

### What do you see instead?

whene i try to go in worker trougth spark master i get error 500 java.lang.nullpointerexception missing sslcontextfactory

**Comment by javsalgar** [comment]
Hi,

Could you share the exact configuration so we can reproduce the issue?

**Comment by nevo11** [comment]
ok,
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=https://spark.your-domain.com
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=https://spark.your-domain.com


ssl.enabled=true

**Comment by Mauraza** [comment]
Hi @nevo11,

Could you share the logs? Did you try to use `image.debug=true` to have more information?

**Comment by nevo11** [comment]
error in ui of worker in revers proxy master:
          http ERROR 500 java.NullPointerException: Missing SslContextFactory
          URL:         /proxy/<worker id>
          STATUS: 500
          MESSEGE: java.NullPointerException: Missing SslContextFactory
          SERVLET: org.apache.spark.ui.jettyUtils...
          CAUSED BY: java.NullPointerException: Missing SslContextFactory
error in master 
           java.NullPointerException: Missing SslContextFactory
 in the workers there are no logs of that

**Comment by Mauraza** [comment]
Hi @nevo11,

Are you using the ingress too? 
```
ingress:
  enabled: true
  hostname: spark.your-domain.com
```

**Comment by nevo11** [comment]
yes i try to use ingress but the problem accer even inside the cluster 
i allways can get to the master ui but wehen i try to get /proxy/<workerid> heven using curl inside the cluster i get
 500 java.NullPointerException: Missing SslContextFactory

**Comment by Mauraza** [comment]
Hi @nevo11,

Which version of Spark and the container are you using? 
Could you try with the last one (Chart: 8.1.6)?

**Comment by nevo11** [comment]
I using chart version 7.1.2 this is a known error in that version?

**Comment by nevo11** [comment]
with spark 3.4.1

**Comment by Mauraza** [comment]
I tested with the last version, and all works. Could you check with the last version?

**Comment by nevo11** [comment]
i just try and get the same problem
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>\n<title>Error 500 java.lang.NullPointerException: Missing SslContextFactory</title>\n</head>\n<body><h2>HTTP ERROR 500 java.lang.NullPointerException: Missing SslContextFactory</h2>\n<table>\n<tr><th>URI:</th><td>/proxy/worker-20231205094009-10.1.0.28-42511</td></tr>\n<tr><th>STATUS:</th><td>500</td></tr>\n<tr><th>MESSAGE:</th><td>java.lang.NullPointerException: Missing SslContextFactory</td></tr>\n<tr><th>SERVLET:</th><td>org.apache.spark.ui.JettyUtils$$anon$3-58936275</td></tr>\n<tr><th>CAUSED BY:</th><td>java.lang.NullPointerException: Missing SslContextFactory</td></tr>\n</table>\n<h3>Caused by:</h3><pre>java.lang.NullPointerException: Missing SslContextFactory\n\tat java.base/java.util.Objects.requireNonNull(Objects.java:235)\n\tat org.sparkproject.jetty.io.ssl.SslClientConnectionFactory.&lt;init&gt;(SslClientConnectionFactory.java:57)\n\tat org.sparkproject.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1273)\n\tat org.sparkproject.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1279)\n\tat org.sparkproject.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:209)\n\tat org.sparkproject.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:215)\n\tat org.sparkproject.jetty.client.HttpDestination.&lt;init&gt;(HttpDestination.java:100)\n\tat org.sparkproject.jetty.client.PoolingHttpDestination.&lt;init&gt;(PoolingHttpDestination.java:25)\n\tat org.sparkproject.jetty.client.http.HttpDestinationOverHTTP.&lt;init&gt;(HttpDestinationOverHTTP.java:32)\n\tat org.sparkproject.jetty.client.http.HttpClientTransportOverHTTP.newHttpDestination(HttpClientTransportOverHTTP.java:54)\n\tat org.sparkproject.jetty.client.HttpClient.lambda$resolveDestination$0(HttpClient.java:597)\n\tat java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)\n\tat org.sparkproject.jetty.client.HttpClient.resolveDestination(HttpClient.java:593)\n\tat org.sparkproject.jetty.client.HttpClient.resolveDestination(HttpClient.java:571)\n\tat org.sparkproject.jetty.client.HttpClient.send(HttpClient.java:626)\n\tat org.sparkproject.jetty.client.HttpRequest.sendAsync(HttpRequest.java:780)\n\tat org.sparkproject.jetty.client.HttpRequest.send(HttpRequest.java:767)\n\tat org.sparkproject.jetty.proxy.AbstractProxyServlet.sendProxyRequest(AbstractProxyServlet.java:618)\n\tat org.sparkproject.jetty.proxy.ProxyServlet.service(ProxyServlet.java:114)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:590)\n\tat org.sparkproject.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)\n\tat org.sparkproject.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)\n\tat org.apache.spark.ui.HttpSecurityFilter.doFilter(HttpSecurityFilter.scala:95)\n\tat org.sparkproject.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)\n\tat org.sparkproject.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)\n\tat org.sparkproject.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)\n\tat org.sparkproject.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.sparkproject.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)\n\tat org.sparkproject.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.sparkproject.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)\n\tat org.sparkproject.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.sparkproject.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)\n\tat org.sparkproject.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.sparkproject.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)\n\tat org.sparkproject.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)\n\tat org.sparkproject.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.sparkproject.jetty.server.Server.handle(Server.java:516)\n\tat org.sparkproject.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)\n\tat org.sparkproject.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)\n\tat org.sparkproject.jetty.server.HttpChannel.handle(HttpChannel.java:479)\n\tat org.sparkproject.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)\n\tat org.sparkproject.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.sparkproject.jetty.io.FillInterest.fillable(FillInterest.java:105)\n\tat org.sparkproject.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)\n\tat org.sparkproject.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)\n\tat org.sparkproject.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)\n\tat org.sparkproject.jetty.io.FillInterest.fillable(FillInterest.java:105)\n\tat org.sparkproject.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)\n\tat org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)\n\tat org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)\n\tat org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)\n\tat org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)\n\tat org.sparkproject.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)\n\tat org.sparkproject.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)\n\tat org.sparkproject.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n</pre>\n<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.52.v20230823</a><hr/>\n\n</body>\n</html>\n

**Comment by Mauraza** [comment]
Hi @nevo11,

I tested with these values:

```yaml
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=https://spark.your-domain.com
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=https://spark.your-domain.com
ingress:
  enabled: true
  hostname: spark.your-domain.com
```

I couldn't reproduce the issue; could you tell me if you are using other values?  
Where are you deploying this chart?
You can add the value `image.debug=true` to see if the logs show more information.

**Comment by yankees5963** [comment]
I am getting the same issue on the newest chart 8.9.1
