### ISSUE TITLE
[bitnami/postgresql] Postgress Chart generates an error with attempting install

### ISSUE THREAD

**Issue by grateitservices** [bitnami/charts#21090]
### Name and Version

Postgres Latest

### What architecture are you using?

None

### What steps will reproduce the bug?

In k8s

Running 
```
$ helm install postgres oci://registry-1.docker.io/bitnamicharts/postgresql
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/bob/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/bob/.kube/config
Pulled: registry-1.docker.io/bitnamicharts/postgresql:13.2.14
Digest: sha256:855dadf100abbe600d6d0322b086a5e53778416249c1b8e1f4f85f6ea04f3331

Error

Error: INSTALLATION FAILED: create: failed to create: Post "https://10.68.4.21:6443/api/v1/namespaces/postgres/secrets": unexpected EOF
$ kubectl get all
No resources found in postgres namespace.
$ kubectl get pvc
No resources found in postgres namespace.
```

### Are you using any custom parameters or values?

I have tried with and without custom values and get the same error

### What is the expected behavior?

Should deploy postgress with default alues

### What do you see instead?

Error from helm chart

**Comment by javsalgar** [comment]
Hi,

It seems to me that the issue lies in the Kubernetes cluster API, as it is returning an EOF. Could you check that the issue does not happen in other clusters?

**Comment by grateitservices** [comment]
Thank you , I was able to deploy via a DockerDesktop K8s cluster.  I will troubleshoot our K8s environment
