### ISSUE TITLE
bitnami/mastodon tootctlMediaManagement/cronjob.yaml has hardcoded volume name that causes job container to fail creation

### ISSUE THREAD

**Issue by joelparker** [bitnami/charts#21110]
### Name and Version

bitnami/mastodon 3.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy bitnami/mastodon chart with --set tootctlMediaManagement.enabled=true
When the tootctlMediaManagement cronjob schedules a job it willl fail  when it tries to initialize the container because it won't be able to mount the media-management volume.  This is because the configmap with the tootctl media script will have a different name and fail to mount to the container in the pod.  

This has been broken since https://github.com/joelparker/charts/commit/10711912ed2c3ab5840f1c8196de1ea413deeccd when the feature was introduced by me.  

### Are you using any custom parameters or values?

--set tootctlMediaManagement.enabled=true

### What is the expected behavior?

The Job is run and the container shows. a completed state

```
<helm_install_name>-tootctl-media-<random_chars>                       0/1     Completed   0             14h
```

### What do you see instead?

The Pod never gets pas init container

### Additional information

I have a PR to fix the issue and will be pushing it soon.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
