### ISSUE TITLE
[bitnami/postgresql-ha] pgpool's liveness probe is broken. 

### ISSUE THREAD

**Issue by liyuntao** [bitnami/charts#2113]
**Which chart**:

postgresql-ha  1.4.11 (current version)

**Description**

It seems the `healthcheck.sh` file has been moved in the latest pgpool docker image. In previous version it's located in root path `/healthcheck.sh`, but now it's in `/opt/bitnami/scripts/pgpool/healthcheck.sh` thus broke the [liveness probe](https://github.com/bitnami/charts/blob/b0dad808a863a966067244fa5c815fa6959516ff/bitnami/postgresql-ha/templates/pgpool/deployment.yaml#L128) and the pod is restarting forever.

**Steps to reproduce the issue:**

```bash
# attach to old container
docker run -it --rm bitnami/pgpool:4.1.1-debian-10-r16 /bin/sh
# inside container
find / -name "health*.sh"
> /healthcheck.sh


# attach to new container
docker run -it --rm bitnami/pgpool:4.1.1-debian-10-r29 /bin/sh
# inside container
find / -name "health*.sh"
> /opt/bitnami/scripts/pgpool/healthcheck.sh
```

**Comment by juan131** [comment]
Thanks for the fix @liyuntao !!
I just created a PR to address it
