### ISSUE TITLE
[bitnami/postgres] no loadBalancerSourceRanges in svc-read

### ISSUE THREAD

**Issue by alexz75** [bitnami/charts#2114]
Reproduction:
1. Deploy bitnami/postgresql version. 8.6.8 with the following settings:
```
service:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.1.1.1/32
```
2. Current result: Getting regular service with the loadBalancerSourceRanges, but read-only service is opened to all of the world.
3. Expected: read-only service should have the same loadBalancerSourceRanges or possibility to configure own one
See: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/svc.yaml and compare with https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/svc-read.yaml

Should add the following section:
```
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}

```

**Comment by juan131** [comment]
Hi @alexz75 

Thanks so much for reporting this issue! I could reproduce it and I created a PR to address it.
