### ISSUE TITLE
[bitnami/harbor] Harbor registry HA functionality is not working as expected.

### ISSUE THREAD

**Issue by sabiges** [bitnami/charts#21215]
### Name and Version

bitnami/harbor

### What architecture are you using?

None

### What steps will reproduce the bug?

In any K8s cluster that dynamic PV provisioning, deploy the harbor chart with registry replica count with 2 . 
Expected O/P:
2 harbor-registry pods should come up in different node. 
Actual o/p:
2 harbor-registry pods are coming up in same node  since the pvc is binded into one node.
In this case, if some node failure happens, both the pods will go to terminating state and HA functionality will not be acheived.

### Are you using any custom parameters or values?

Incrementing replicaCount: 1 of harbor-registry using seperate value.syaml
https://github.com/bitnami/charts/blob/2575818836eeff7d53aa30ec6c6457543e43a526/bitnami/harbor/values.yaml#L1870C3-L1870C18

### What is the expected behavior?

Expected O/P:
2 harbor-registry pods should come up in different node. 

### What do you see instead?

Actual o/p:
2 harbor-registry pods are coming up in same node  since the pvc is binded into one node.
In this case, if some node failure happens, both the pods will go to terminating state and HA functionality will not be acheived.

### Additional information

Could you please provide the solution to make the Harbor-registry with HA support. Current deployment service is not working as expected. I am curious to know why this service is not statefulset since it requires to store the DATA permanently .

**Comment by jotamartos** [comment]
Hi @sabiges,

Just a quick note to let you know that we received this issue. I'll take a look at the configuration and will update the ticket once I have more information.

**Comment by sabiges** [comment]
@jotamartos : Thanks for the update. If you have any updates regarding temporary Workaround , please let me know. I will use it and test it.

**Comment by jotamartos** [comment]
hi @sabiges,

Sorry for the delay. I just confirmed that this chart has the [podAntiAffinity parameter](https://github.com/bitnami/charts/blob/main/bitnami/harbor/templates/registry/registry-dpl.yaml#L53) already configured. Have you tried setting the `registry.podAntiAffinityPreset` parameter to `hard`? 

```
helm install jota-h bitnami/harbor --set registry.replicaCount=2 --set registry.podAntiAffinityPreset=hard
```

I just confirmed that the registry pods were scheduled in different nodes 

```
$ kubectl get pods -o wide
NAME                                        READY   STATUS              RESTARTS   AGE   IP            NODE                                                  NOMINATED NODE   READINESS GATES
...
jota-h-harbor-registry-54544b8469-2rn6x     0/2     ContainerCreating   0          13s   <none>        gke-environment-bzbb-nodepool-workers-1ceaebb2-mlt7   <none>           <none>
jota-h-harbor-registry-54544b8469-db68k     0/2     ContainerCreating   0          12s   <none>        gke-environment-bzbb-nodepool-workers-1ceaebb2-q229   <none>           <none>
```

**Comment by sabiges** [comment]
@jotamartos : Sure, I will try with this change and update you. Thanks for the update.

**Comment by jotamartos** [comment]
Sorry @sabiges, 

I didn't see that error because I didn't allow the deployment finish, I simply verified that the pods were assigned to different nodes. Let me take a look at the error and will update this ticket as soon as I have more information.

**Comment by jotamartos** [comment]
Hi @sabiges,

I just checked that the default access mode of the created persistent volumes is ReadWriteOnce. You need to change it to ReadWriteMany as you will be using different nodes to deploy the pods

```
helm install harbor bitnami/harbor --set registry.replicaCount=2 --set registry.podAntiAffinityPreset=hard --set persistence.persistentVolumeClaim.registry.accessModes={ReadWriteMany}
```

Remember that your cluster must support this access mode. For example, GKE clusters do not support that. Once you deploy the solution, I confirmed that the pods were running in different nodes 

```
harbor-registry-899cf74cc-lk8tm      2/2     Running            0             3m55s   10.244.0.3   minikube       <none>           <none>
harbor-registry-899cf74cc-zwnnb      2/2     Running            0             3m55s   10.244.1.3   minikube-m02   <none>           <none>
```

I hope this helps
