### ISSUE TITLE
Authentication failed when using "custom" cassandra.yaml mounted with extraConfigurations.

### ISSUE THREAD

**Issue by sharkannon** [bitnami/charts#21218]
### Name and Version

bitnami/cassandra 10.6.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy a chart with (Using 3.0.27 image)

```
helm upgrade --install --create-namespace --namespace cassandra cassandra2 oci://registry-1.docker.io/bitnamicharts/cassandra
```
Copy the cassandra.yaml and put it into a configmap, then add that configmap to the extraConfigurations to override the default.

If I spin up 2 parallel statefulsets, one with the "custom" _cassandra.yaml_ and one w/out the custom _cassandra.yaml_, they both come up with the exact same JVM args and the exact same cassandra.yaml (different host name), but when I try to connect to the pod using the credentials (same credentials), the one with the "custom" _cassandra.yaml_ fails to connect.

I'm assuming there's something in one of the sh customization scripts that isn't running on the password change, but I don't know what it is.  Right now, I'm looking for ideas vs a full bug log.

### What is the expected behavior?

```
cqlsh -u cassandra -p PASSWORD x.x.x.x
```

to connect to the host with custom _cassandra.yaml_

### What do you see instead?
```
Connection error: ('Unable to connect to any servers', {'x.x.x.x': AuthenticationFailed('Failed to authenticate to x.x.x.x: Error from server: code=0100 [Bad credentials] message="Username and/or password are incorrect"',)})
```

**Comment by rafariossaa** [comment]
Hi,
  There is no `extraConfigurations` parameters in the `values.yaml`. Are you meaning `existingConfiguration`  ?

**Comment by sharkannon** [comment]
existingConfiguration, yes, sorry

I’ll grab the logs later today.
