### ISSUE TITLE
MLFLOW - LDAP auth 

### ISSUE THREAD

**Issue by Mihai-CMM** [bitnami/charts#21228]
### Name and Version

bitnami/mlflow

### What is the problem this feature will solve?

Will be easier to set groups of data scientists that have access to mlflow based on their LDAP accounts

### What is the feature you are proposing to solve the problem?

n/a

### What alternatives have you considered?

n/a

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
