### ISSUE TITLE
[mariadb-galeria] Unable to amend startup CLI

### ISSUE THREAD

**Issue by gwvandesteeg** [bitnami/charts#2122]
**Which chart**:

chart: mariadb-galera
version: 0.8.5

**Description**

Needing to specify additional command line arguments to the MariaDB startup and the only section of the statefulset chart missing the command section is the mariadb container.  A nice simple way of adding adding extra command args would be usefull.

**Steps to reproduce the issue:**

1. Configure the chart to take pass in additional CLI args to the mariadb container...
2. You can't

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Irrelevant it's the chart that's incomplete

- Output of `kubectl version`:

Irrelevant it's the chart that's incomplete

**Comment by marcosbc** [comment]
Hi @gwvandesteeg, you should be able to achieve that with the environment variable `MARIADB_EXTRA_FLAGS`, which can be set via the [`extraFlags` option in the chart](https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/values.yaml#L327).

**Comment by gwvandesteeg** [comment]
Yeah, found it after digging through the Dockerfile and the chart when i wasn't in a rush.  Wasn't very clear.
