### ISSUE TITLE
[bitnami/kube-prometheus] `prometheus.additionalArgs` not working

### ISSUE THREAD

**Issue by anyoloten** [bitnami/charts#21227]
### Name and Version

bitnami/kube-prometheus 8.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`prometheus.additionalArgs` not working

### Are you using any custom parameters or values?

```
prometheus:   
  additionalArgs: 
    - name: --xxxx
```

### What is the expected behavior?

successed

### What do you see instead?

```
helm -n monitoring upgrade -i prometheus bitnami/kube-prometheus -f .yaml --version 8.4.0
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "additionalArgs" in com.coreos.monitoring.v1.Prometheus.spec
```

**Comment by WVenus** [comment]
Hi @anyoloten 
You can check the parameter writing method

![image](https://github.com/bitnami/charts/assets/39941928/7a457d27-80a1-41bd-837a-3ab00ad59a95)

**Comment by anyoloten** [comment]
@WVenus 

```
prometheus:   
  additionalArgs: 
    - name: xxx 
       value: xxx
```

not working 

but 
![image](https://github.com/bitnami/charts/assets/64666574/fe1217bf-943d-4ea2-8f1c-0c7565dd3a8b)

**Comment by anyoloten** [comment]
In prometheus-operator the problem also exists and I solved this problem by other way
