### ISSUE TITLE
AMQPLAIN login refused with invalid credentials

### ISSUE THREAD

**Issue by shrey-ld-schrodinger** [bitnami/charts#21229]
### Name and Version

rabbitmq, version: 8.31.3

### What architecture are you using?

None

### What steps will reproduce the bug?

- We have a jenkins build which creates a new kubernetes cluster and starts up RMQ in it (along with other services)
- Sometimes (rarely) it happens that RMQ does not accept the credentials for login
- Error message is like : `AMQPLAIN login refused: user 'someuser' - invalid credentials`

### Are you using any custom parameters or values?

- I have already increased `rabbitmq.readinessProbe.initialDelaySeconds` to 120 seconds
- We set the custom authentication using `rabbitmq.auth.username` and `rabbitmq.auth.password`

### What is the expected behavior?

Password set above is accepted

### What do you see instead?

Sometimes password is not accepted

### Additional information

Jenkins builds themselves run on workers which run on GCE instances managed by a GKE cluster

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
