### ISSUE TITLE
at <index $root.Values.externalAccess.service.nodePort $i>: error calling index: index of untyped nil

### ISSUE THREAD

**Issue by panypopo** [bitnami/charts#2123]
https://github.com/bitnami/charts/blob/1c9f3ce80c30acc8e487c52191d097485b9e83e9/bitnami/kafka/templates/svc-external-access.yaml#L42

here might be `targetPort: {{ index $root.Values.externalAccess.service.nodePorts $i }} `

**Comment by juan131** [comment]
Thanks for reporting it @panypopo !!! You're 100% right. I just created a PR to fix it.
