### ISSUE TITLE
[bitnami/wordpress] Support for CronJobs in the Bitnami WordPress Helm Chart

### ISSUE THREAD

**Issue by lotyp** [bitnami/charts#21246]
### Name and Version

bitnami/wordpress

### What is the problem this feature will solve?

The Bitnami WordPress Helm chart currently lacks out-of-the-box support for CronJobs. This is particularly relevant for managing tasks like wp-cron.php. The [Bitnami WordPress documentation](https://docs.bitnami.com/aws/apps/wordpress/configuration/disable-wordpress-cron/) suggests disabling the default wp-cron behavior, but does not provide an alternative solution within the Helm chart context.

### What is the feature you are proposing to solve the problem?

I propose enhancing the Bitnami WordPress Helm chart to include built-in support for CronJobs. This feature would facilitate scheduled tasks management directly via the Helm chart.

### What alternatives have you considered?

While other Bitnami Helm charts, such as [Matomo](https://github.com/bitnami/charts/blob/main/bitnami/matomo/templates/cronjob.yaml), include CronJob functionality, the WordPress chart does not. Currently, users have to manually configure CronJobs outside the Helm chart, which is not ideal for a seamless deployment experience.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by brandan-schmitz** [comment]
Any chance this can be reopened as it was never completed but is still a useful thing to get added?

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
