### ISSUE TITLE
[bitnami/keycloak] Upgrade keycloak to 23.0.0

### ISSUE THREAD

**Issue by thanhtoan1196** [bitnami/charts#21261]
### Name and Version

bitnami/keycloak 17.3.4

### What is the problem this feature will solve?

Keycloak has version 23.0.0
https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-23-0-0

### What is the feature you are proposing to solve the problem?

Upgrade keycloak to 23.0.0

**Comment by thanhtoan1196** [comment]
I hope chart has a new version with keycloak 23.0.0

**Comment by viceice** [comment]
if the new version is already available as docker image then you can manually override the tag via helm values.

**Comment by thanhtoan1196** [comment]
> if the new version is already available as docker image then you can manually override the tag via helm values.

I think 23.0.0 is major so it may not be compatible with the old config.

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. We will provide updates on this thread as soon as the new version is successfully released.

**Comment by CyanoFresh** [comment]
really need this, any updates?

**Comment by gabornyerges** [comment]
Hello, any update on this pls?

**Comment by javsalgar** [comment]
Hi!

I'm afraid we are still working on it. As soon as there are news, we will notify the community

**Comment by tanadeau** [comment]
FYI: The `keycloak-config-cli` project used in this chart has support for Keycloak 23 as of this morning.

**Comment by dalbani** [comment]
For the record, there's also an issue open in the `containers` repository: https://github.com/bitnami/containers/issues/53268.

**Comment by carrodher** [comment]
The new version has been already released, see the changes
- in the container image: https://github.com/bitnami/containers/pull/54244
- in the Helm chart: https://github.com/bitnami/charts/pull/21762

Thanks for your patience, feel free ping us if you find any issue
