### ISSUE TITLE
Backup cron job for mongodb chart doesn't work with podSecurityContext enabled

### ISSUE THREAD

**Issue by mkoziel-pfl** [bitnami/charts#21278]
### Name and Version

bitnami/mongodb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set the `podSecurityContext.enabled: true` in the values file for mongodb helm chart
2. Set the `backup.enabled: true` in the values file for mongodb helm chart
3. Try to install the helm chart

### Are you using any custom parameters or values?

No...just the standard _values.yaml_ file with podSecurityContext and backup feature turned on.

### What is the expected behavior?

Helm chart succeeds to install and a backup Cron job is registered with K8S

### What do you see instead?

An error stating that securityContext is not part of the batch/v1 JobSpec specification.

### Additional information

In the CronJob.yaml template file for the helm chart, securityContext is getting written out if `podSecurityContext.enabled: true`

The specification definitely doesn't allow for this attribute to exist from ConJob definition (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobspec-v1-batch)

Removing this attribute from the template file is probably the simplest fix for this issue since we already have the ability to control, at the container level, applying security context.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
