### ISSUE TITLE
Allow modify default PVC name 

### ISSUE THREAD

**Issue by PiotrKlimek** [bitnami/charts#21270]
### Name and Version

bitnami/postgresql 13.2.18

### What is the problem this feature will solve?

Currently it's impossible to change name of the PVC.

### What is the feature you are proposing to solve the problem?

It would be nice to have it templated so user could be able to change default name which now is `data`:
https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/primary/statefulset.yaml#L638C12-L638C12

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
