### ISSUE TITLE
[bitnami/grafana-operator] Namespace scope to current namespace bugged

### ISSUE THREAD

**Issue by shubhamranjan** [bitnami/charts#21288]
### Name and Version

bitnami/grafana-operator 3.5.6+

### What architecture are you using?

None

### What steps will reproduce the bug?

- Try installing helm chart to scope to current namespace.

In version 3.5.5, by setting `operator.namespaceScope=true`, we could scope the chart to **just** the current namespace or custom namespace using the field `operator. watchNamespace` values.

But with the change introduced in #20962 , it uses the same variable `operator. watchNamespace` to check whether the namespace has to be restricted and as an input to which namespaces needs to be watched, which mandates specifying a namespace if we want to restrict it. For users who want to restrict it to just the current namespace, its no longer possible.

### What is the expected behavior?

We should be able to watch just the current namespace where the operator is being deployed.

### What do you see instead?

We are not able to watch just the current namespace and can only specify statically defined namespaces or all namespaces.

### Additional information

Can be fixed by simply reverting the PR.

**Comment by rafariossaa** [comment]
Hi,
  @dazoakley, could you take a look to this ? I would like to find a common solution for this issue and your issue .

**Comment by dazoakley** [comment]
Hi @rafariossaa,

I've pushed up a fix in https://github.com/bitnami/charts/pull/21404 - apologies for missing that edge case.

**Comment by rafariossaa** [comment]
Thanks @dazoakley !.
@shubhamranjan  Let's wait until it gets reviewed and merged.
