### ISSUE TITLE
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1"

### ISSUE THREAD

**Issue by epneo-banuprakash** [bitnami/charts#21284]
### Name and Version

 bitnami/grafana-operator --version 3.5.8 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi all,
I am trying to upgrade bitnami/grafana-operator version from **2.9.3 to 3.5.8** , which is the latest version but I couldn't able to succeeded, it's throwing the error
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1"
```

we are using Aks version 1.25 and Helm 3.+, trying to update through the terraform script.

### What do you see instead?
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1"
```

**Comment by rafariossaa** [comment]
Have you tried to upgrade in smaller steps ? From 2.9.3 to 3.0.0 and then moving upwards ?

**Comment by epneo-banuprakash** [comment]
yes, when I tried to update from 2.9.3 to 3.0.0, I got this error: **UPGRADE FAILED: YAML parse error on grafana-operator/templates/grafana.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key**

So if I try to update to 3.0.0 above version I got the Error: **UPGRADE FAILED: unable to recognize "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1"**

**Comment by rafariossaa** [comment]
did you take into account [this notice](https://github.com/bitnami/charts/tree/main/bitnami/grafana-operator#user-content-to-300) ?

**Comment by epneo-banuprakash** [comment]
How can I migrate API version  integreatly.org/v1alpha1 -> grafana.integreatly.org/v1beta1, above doc isn't cleared about that migration, Is there any command to do it or any process ,pls provide the link if any,, This  grafana.integreatly.org/v1beta1 will work on 2.9.3?? Is there any alter solution to upgrade.

**Comment by rafariossaa** [comment]
Hi,
  For that question I would suggest you to ask in grafana forums, I think they could provide a better answer on how to perform that migration.

**Comment by epneo-banuprakash** [comment]
Hi i posted the issue in grafana forums but u can see the replay from them 
<img width="684" alt="image" src="https://github.com/bitnami/charts/assets/89842780/913878fb-7cff-4228-a0f8-6f5bcf0327a3">
How can i upgrade ??

**Comment by rafariossaa** [comment]
How to transform `integreatly.org/v1alpha1 -> grafana.integreatly.org/v1beta1` is explained in this [link](https://grafana.github.io/grafana-operator/blog/2023/05/27/v4-to-v5-migration/). You will need to edit and change the manifests.
