### ISSUE TITLE
[Kafka][Cassandra]HPA for Kafka and Cassandra

### ISSUE THREAD

**Issue by Raksha-CPU** [bitnami/charts#21285]
### Name and Version

kafka & cassandra latest version

### What is the problem this feature will solve?

Hello, I'm interested in implementing Horizontal Pod Autoscaling (HPA) for Kafka and Cassandra, but I couldn't find any options for this in the Helm charts. Is there a specific reason why it's not implemented in these charts?

### What is the feature you are proposing to solve the problem?

I'm looking to enable Horizontal Pod Autoscaling (HPA) for both Kafka and Cassandra Helm charts.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Raksha-CPU** [comment]
Hi Team,

I am customizing the Helm chart to implement Horizontal Pod Autoscaling (HPA) for Kafka. Below is the template for the HPA.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-hpa
  namespace: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: kafka
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
     resource:
       name: memory
       target:
         type: Utilization
         averageUtilization: 30
        
        
<img width="556" alt="image" src="https://github.com/bitnami/charts/assets/85828578/4d5e16f7-2e23-4c16-9110-64cc84f6a02e">

<img width="861" alt="image" src="https://github.com/bitnami/charts/assets/85828578/4348c57b-c920-43de-a262-5e19c6803f13">


During autoscaling, Kafka pods are getting terminated without showing any errors. Can you please tell us why this is happening, and does Kafka (and Cassandra) support autoscaling?
