### ISSUE TITLE
[bitnami/nginx-ingress-controller] Error with DaemonSet 

### ISSUE THREAD

**Issue by naoyayamamoto** [bitnami/charts#21306]
### Name and Version

bitnami/nginx-ingress-controller 9.9.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Use with `kind: DaemonSet` will result in an error due to lack of geoip

### Are you using any custom parameters or values?

kind: DaemonSet

### What is the expected behavior?

Starts normally.

### What do you see instead?

An error occurs and the container does not start up properly.

### Additional information

The controller-deployment.yaml was fixed when fixing #21196 , but controller-daemonset.yaml was not.
We believe a similar fix is needed.

**Comment by opencmit2** [comment]
Hi @javsalgar 
I can help modify it

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
