### ISSUE TITLE
opensearch-dashboard chart does not support initcontainers

### ISSUE THREAD

**Issue by scheffold** [bitnami/charts#21300]
### Name and Version

bitnami/opensearch:0.4.2

### What is the problem this feature will solve?

the helm file    ``/opensearch/dahsboards/deployment.yaml`` only supports injection of sidecar containers  - not initContainers

- [ ] 

### What is the feature you are proposing to solve the problem?

initContainers should be able to configure for dashboard deployment

### What alternatives have you considered?

prehook lifecycle post start - but does not always working  appropriately due to not guaranteed execution order.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
