### ISSUE TITLE
run JMX to Prometheus exporter for Kafka as java agent rather than side-car

### ISSUE THREAD

**Issue by janvanbesien-ngdata** [bitnami/charts#21309]
### Name and Version

bitnami/kafka 18.0.3

### What is the problem this feature will solve?

Expose JVM process metrics (memory and CPU usage, e.g. `jvm_memory_bytes_used`) to Prometheus.

### What is the feature you are proposing to solve the problem?

Kafka JMX metrics are currently exported via a side-car in the Kafka Chart: see container `jmx-exporter` in `bitnami/kafka/templates/statefulset.yaml`, enabled when `.Values.metrics.jmx.enabled` is true. As indicated in the README of the Prometheus JMX exporter project (https://github.com/prometheus/jmx_exporter), it is actually recommended to run it as a JVM agent rather than a separate process. One very concrete advantage is that it then also exposes process metrics (memory and CPU usage, e.g. `jvm_memory_bytes_used`).

### What alternatives have you considered?

What is available as `jvm_memory_bytes_used` can also be obtained from `java_lang_memory_heapmemoryusage_used` (that's the Prometheus metric name that corresponds to an attribute of the java.lang:type=Memory MBean), but having the process metrics available directly is more in-line with how it typically works for other Java processes.

The current situation makes system monitoring for Kafka inconsistent with other Java processes, such as for example bitnami/zookeeper. 

I ran a quick test with a customized bitnami/kafka docker image (added the prometheus agent jar file) to confirm this will just work fine. I can work on a proper PR where I replace the side-car with an agent-based implementation, if you agree this would be an improvement.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by juan131** [comment]
As stated at https://github.com/bitnami/containers/pull/53817#issuecomment-1859812522, I'm afraid we cannot accept contribution including the JMX exporter as a JAVA agent.
