### ISSUE TITLE
[bitnami/redis-cluster] Redis-cluster: IP is not updated from nodes.conf when restarting

### ISSUE THREAD

**Issue by mojixcoder** [bitnami/charts#21301]
### Name and Version

bitnami/redis-cluster:9.1.3

### What architecture are you using?

None

### What steps will reproduce the bug?

We have a redis-cluster with 6 nodes.

We asked our cloud team to change the worker node of one of the pods due to CPU throttling.
After this, our nodes updated the IP address of the restarted node except the restarted node itself.  
It still had its old IP address but other cluster nodes had its updated address.

It caused some requests to fail.  

P.S. When I manually restart pods it is ok, when the pod is drained by the cloud team this happens.

### What do you see instead?

CLUSTER NODES on other cluster nodes:
```
e65fabcc823f2da67a9cc66f32f21c6d6f2f0dc4 10.132.229.222:6379@16379 master - 0 1701248880000 7 connected 10923-16383
a83817f26b662a4d6faea5c00950c31f5d60839b 10.132.233.170:6379@16379 master - 0 1701248880944 2 connected 5461-10922
9bdbdb2f01eae7e182a6dde38b4228edf4c5633e 10.132.34.102:6379@16379 myself,master - 0 1701248880000 1 connected 0-5460
6031374ed55177c7d538ea31c4700540327140b3 10.133.4.210:6379@16379 slave e65fabcc823f2da67a9cc66f32f21c6d6f2f0dc4 0 1701248880830 7 connected
4956310a97f1645fc9ae23c714d5ee9e73f01868 10.132.78.148:6379@16379 slave 9bdbdb2f01eae7e182a6dde38b4228edf4c5633e 0 1701248881979 1 connected
92a23425002e50609ed31fe9fca8c2ea9b92c188 10.132.61.108:6379@16379 slave a83817f26b662a4d6faea5c00950c31f5d60839b 0 1701248881000 2 connected
```

CLUSTER NODES on restarted node:
```
e65fabcc823f2da67a9cc66f32f21c6d6f2f0dc4 10.132.229.222:6379@16379 master - 0 1701248880000 7 connected 10923-16383
a83817f26b662a4d6faea5c00950c31f5d60839b 10.132.233.170:6379@16379 master - 0 1701248880944 2 connected 5461-10922
9bdbdb2f01eae7e182a6dde38b4228edf4c5633e 10.132.34.102:6379@16379master - 0 1701248880000 1 connected 0-5460
6031374ed55177c7d538ea31c4700540327140b3 wrong_ip:6379@16379 myself,slave e65fabcc823f2da67a9cc66f32f21c6d6f2f0dc4 0 1701248880830 7 connected
4956310a97f1645fc9ae23c714d5ee9e73f01868 10.132.78.148:6379@16379 slave 9bdbdb2f01eae7e182a6dde38b4228edf4c5633e 0 1701248881979 1 connected
92a23425002e50609ed31fe9fca8c2ea9b92c188 10.132.61.108:6379@16379 slave a83817f26b662a4d6faea5c00950c31f5d60839b 0 1701248881000 2 connected
```

**Comment by mojixcoder** [comment]
Can we have an option to create a service for each pod?  
And make cluster to use this service instead of pod IPs. 
I think it fixes the problem of invalid IPs.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by mojixcoder** [comment]
Do you think using services instead of pod IPs is a good solution?

since pod IPs are not static in kubernetes and we have to handle so many edge cases in order to have updated IP addrs.

using service names would fix the issue.

Or did we have any specific reason not to that at the first place? I want to make sure I’m not missing anything.

**Comment by mojixcoder** [comment]
I found out what the issue is, the `nodes.conf` is stored inside the volume directory and it has the cluster nodes IP addresses (including `myself` node).  
When a pod get restarted, it updates it new IP address with other nodes but it doesn't update its own IP in `nodes.conf` for itself.
Therefore, other nodes have its new IP address but the pod itself has its old IP address.  

We should update pod's IP address in `nodes.conf` in `initContainers` before the Redis container gets ready.

If you think that's ok, I can work on it.

**Comment by mojixcoder** [comment]
Thank you @CeliaGMqrz .
Yeah I can provide this information later.

I only have a question. Did you run `cluster nodes` on the restarted pod or on other pods?
Because other pods get the updated IP address.

**Comment by mojixcoder** [comment]
I think I can add an `initContainers` to my example and fix the issue.

**Comment by mojixcoder** [comment]
Hey guys,
Do we have any updates on this?

**Comment by dilipk8** [comment]
I'm seeing the exact same issue. 

I have setup the bitnami redis-stack-server on an EKS cluster in cluster mode with 3 masters, 3 replicas.
Deleted master-0 pod manually.
Any updates and way to solve this issue ? Would be great.

**Comment by mojixcoder** [comment]
> I'm seeing the exact same issue.
> 
> I have setup the bitnami redis-stack-server on an EKS cluster in cluster mode with 3 masters, 3 replicas. Deleted master-0 pod manually. Any updates and way to solve this issue ? Would be great.

We ended up writing our own charts.
We are going to use bitnami charts after this fix.

We fixed the issue with an initContainer to fix outdated IPs.

https://github.com/mojixcoder/redis-cluster/blob/main/templates/statefulset.yaml#L20

here is the link to the initContainer that we used in our redis cluster charts.

**Comment by CeliaGMqrz** [comment]
Hi @mojixcoder 

Thanks for the information. However, I just tried to reproduce the issue and couldn't do so. I followed these steps:

* Install the chart using the default values.
* Select a pod and get the IP and cluster nodes info (Using `redis-cli` or  `cat /bitnami/redis/data/nodes.conf`):

```
$ cat /bitnami/redis/data/nodes.conf
7758b7f489c104e85c60eed8b866433cc9601587 10.244.0.10:6379@16379,,tls-port=0,shard-id=76ffd36171263aa70d5e3381cde1051bde07cb60 slave 4c2fc9d8289df385f3055059d45d3c4422dda0c7 0 1701690387375 1 connected
04afe916562d2ba1f20c8f52f89f4938f113a237 10.244.0.13:6379@16379,,tls-port=0,shard-id=b6d2194b765e733998348e72bd02209ed6d2e9ed slave f16df35cb40ffa8bc8cf212d44398d3811bd2a14 0 1701690387373 2 connected
4c2fc9d8289df385f3055059d45d3c4422dda0c7 10.244.0.14:6379@16379,,tls-port=0,shard-id=76ffd36171263aa70d5e3381cde1051bde07cb60 master - 0 1701690387375 1 connected 0-5460
4dcd1991f0980063eb7cb7b752dfeeb7f627db9b 10.244.0.11:6379@16379,,tls-port=0,shard-id=ee7a2f9d2136a58ba8d1d70c5128a0739302acee slave b1e9d4547e1826687423a5f8ed394ee5fbd1994e 0 1701690387375 3 connected
f16df35cb40ffa8bc8cf212d44398d3811bd2a14 10.244.0.12:6379@16379,,tls-port=0,shard-id=b6d2194b765e733998348e72bd02209ed6d2e9ed myself,master - 0 1701690387370 2 connected 5461-10922
b1e9d4547e1826687423a5f8ed394ee5fbd1994e 10.244.0.9:6379@16379,,tls-port=0,shard-id=ee7a2f9d2136a58ba8d1d70c5128a0739302acee master - 0 1701690387375 3 connected 10923-16383
vars currentEpoch 6 lastVoteEpoch 0
```

* Delete the pod manually and get the info again in the same pod. We can see that the IP has changed and the node is now connected to the cluster

```
I have no name!@redis-redis-cluster-1:/$ redis-cli
127.0.0.1:6379> cluster nodes
4dcd1991f0980063eb7cb7b752dfeeb7f627db9b 10.244.0.11:6379@16379 slave b1e9d4547e1826687423a5f8ed394ee5fbd1994e 0 1701691970000 3 connected
4c2fc9d8289df385f3055059d45d3c4422dda0c7 10.244.0.14:6379@16379 master - 0 1701691970476 1 connected 0-5460
f16df35cb40ffa8bc8cf212d44398d3811bd2a14 10.244.0.15:6379@16379 myself,slave 04afe916562d2ba1f20c8f52f89f4938f113a237 0 1701691969000 7 connected
04afe916562d2ba1f20c8f52f89f4938f113a237 10.244.0.13:6379@16379 master - 0 1701691972514 7 connected 5461-10922
7758b7f489c104e85c60eed8b866433cc9601587 10.244.0.10:6379@16379 slave 4c2fc9d8289df385f3055059d45d3c4422dda0c7 0 1701691971500 1 connected
b1e9d4547e1826687423a5f8ed394ee5fbd1994e 10.244.0.9:6379@16379 master - 0 1701691970000 3 connected 10923-16383
```

The IP address has been changed from `10.244.0.12` to `10.244.0.15`.

It's possible that the issue is related to the volume path. Currently, you are using `/redis/data` instead of the expected `/bitnami/redis/data`. This could be causing issues with the file where the information is saved. Can you please try changing the path to `/bitnami/redis/data` and see if that resolves the issue?

It's possible too that this issue is related to the Kubernetes platform you are using. To confirm, have you experienced this problem on other clusters? This will help us determine if it's an EKS-specific issue.

**Comment by mojixcoder** [comment]
I have tested this on my local `minikube` and our self-hosted k8s cluster.  

@dilipk8 did you also change the volume path?

**Comment by Ilya-bmx** [comment]
@CeliaGMqrz Hello can u say, which file should i delete , so nodes.conf will be reinitialized, or how does it work?
if I just delete nodes.conf it contains **826a407c44b42e07378d86db620fd03c310e507d :0@0 myself,master - 0 0 0 connected**
after recreating chart

**Comment by mojixcoder** [comment]
> @CeliaGMqrz Hello can u say, which file should i delete , so nodes.conf will be reinitialized, or how does it work? if I just delete nodes.conf it contains **826a407c44b42e07378d86db620fd03c310e507d :0@0 myself,master - 0 0 0 connected** after recreating chart

Hello,
I ended up writing my own helm charts, you can take a look at it and get some ideas.
[repo](https://github.com/mojixcoder/redis-cluster)
