### ISSUE TITLE
[bitnami/kafka] Allowing for customize dnsPolicy and dnsConfig for Kafka & ZK

### ISSUE THREAD

**Issue by siyuan0322** [bitnami/charts#21319]
### Name and Version

bitnami/kafka 20.4.3

### What is the problem this feature will solve?

In the intranet K8S cluster, we have a server ip dedicated for DNS resolution, so we need to modify the dnsPolicy and dnsConfig to make the dns resolution work.

I would like to submit a patch for kafka and zookeeper.

### What is the feature you are proposing to solve the problem?

Like the config example in [this post](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config)

I have a patch for my own repo, and I wonder if this could be officially supported. https://github.com/siyuan0322/GraphScope/commit/f23b92f4573c407abc78e4073cac1cf90b16924d

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
