### ISSUE TITLE
[bitnami/kafka] No support for segment.ms

### ISSUE THREAD

**Issue by btxbtx** [bitnami/charts#21315]
### Name and Version

bitnami/kafka 26.4.3

### What architecture are you using?

None

### What steps will reproduce the bug?

You can try setting variations of the `segment.ms` environment variable, i.e. `KAFKA_CFG_SEGMENT_MS`, and none of them will take effect.  I couldnt find any reference to `segment.ms` in the docs for bitnami kafka.

### Are you using any custom parameters or values?

I am trying to set it via `extraEnvVars`

### What is the expected behavior?

The `segment.ms` config of kafka is updated.

### What do you see instead?

Nothing.  I don't even see a segment.ms in `/opt/bitnami/kafka/config/*` in the pod.

**Comment by fouadsemaan** [comment]
Have you tried setting it in values.yaml extraConfig? Something like this:

extraConfig: |
  key=value

**Comment by fouadsemaan** [comment]
I have tried for other values and it did work.

It must follow the key=value convention so in your case:

segment.ms=400000000

**Comment by joancafom** [comment]
Hi @btxbtx 

As shared by @fouadsemaan, the expected way to specify extra custom configuration is by using the `extraConfig` parameter. Since version `24.0.0`, the chart has added compatibility with `securityContext.readOnlyRootFs=true`
 (see [notes](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400)), which makes your approach incompatible.

**Comment by joancafom** [comment]
@btxbtx 

The example you provided should work as per my tests:

```console
$ cat values.yaml
controller:
  extraConfig: |-
    segment.ms=400000000
$ helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka -f values.yaml
$ kubectl exec -it kafka-controller-0 -- tail /opt/bitnami/kafka/config/server.properties
...
# End of SASL JAAS configuration

segment.ms=400000000
```
