### ISSUE TITLE
[bitnami/discourse] Plugins install according to log but are not existing at runtime

### ISSUE THREAD

**Issue by psych0d0g** [bitnami/charts#21320]
### Name and Version

bitnami/discourse 12.0.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

deploy discourse chart
add plugins to discourse.plugins list:
```yaml
      plugins: 
        - https://github.com/davidtaylorhq/discourse-telegram-notifications
        - https://github.com/discourse/discourse-category-icons
        - https://github.com/discourse/discourse-kanban-theme
        - https://github.com/paviliondev/discourse-tickets
        - https://github.com/discourse/discourse-assign
        - https://github.com/discourse/discourse-solved
```
upgrade chart deployment

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

plugins get put into file system location where they can be loaded by discourse

### What do you see instead?

```console
$ kube logs discourse-7dc9bb9fcf-dmpmg | head
Defaulted container "discourse" out of: discourse, sidekiq
Cloning into '/opt/bitnami/discourse/plugins/discourse-telegram-notifications'...
Cloning into '/opt/bitnami/discourse/plugins/discourse-category-icons'...
Cloning into '/opt/bitnami/discourse/plugins/discourse-kanban-theme'...
Cloning into '/opt/bitnami/discourse/plugins/discourse-tickets'...
Cloning into '/opt/bitnami/discourse/plugins/discourse-assign'...
Cloning into '/opt/bitnami/discourse/plugins/discourse-solved'...
discourse 09:33:31.06 INFO  ==> 
discourse 09:33:31.06 INFO  ==> Welcome to the Bitnami discourse container
discourse 09:33:31.06 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 09:33:31.06 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
```

```console
$ ls /opt/bitnami/discourse/plugins/
drwxrwxr-x 10 discourse root 4096 Nov 28 18:55 .
drwxrwxr-x  4 discourse root 4096 Nov 28 18:55 ..
drwxrwxr-x 10 discourse root 4096 Nov 28 18:55 chat
drwxrwxr-x  6 discourse root 4096 Nov 28 18:55 discourse-details
drwxrwxr-x  8 discourse root 4096 Nov 28 18:55 discourse-lazy-videos
drwxrwxr-x  7 discourse root 4096 Nov 28 18:55 discourse-local-dates
drwxrwxr-x  9 discourse root 4096 Nov 28 18:55 discourse-narrative-bot
drwxrwxr-x  6 discourse root 4096 Nov 28 18:55 discourse-presence
drwxrwxr-x 10 discourse root 4096 Nov 28 18:55 poll
drwxrwxr-x  8 discourse root 4096 Nov 28 18:55 styleguide
```

```console
$ ls /opt/bitnami/discourse/plugins -la
lrwxrwxrwx 1 root root 26 Nov 30 09:33 /opt/bitnami/discourse/plugins -> /bitnami/discourse/plugins
root@discourse-7dc9bb9fcf-dmpmg:/# 
```

**Comment by juan131** [comment]
Hi @psych0d0g 

Is this sth that you can reproduce exclusively while upgrading an existing Discourse installation or are you able to also reproduce it on a "clean environment" installing the chart for the 1st time?

**Comment by psych0d0g** [comment]
I would have to check, let me verify and get back to you on the new installation reproducibility :)

**Comment by psych0d0g** [comment]
well, i didnt expect that tbh, especially with the git checkout's being logged on every container start i would've expected the container to actually use the git checkout data, and not check them out into nirvana.

**Comment by juan131** [comment]
Hi @psych0d0g 

You're right and it doesn't make much sense to run the `rake plugin:install` commands on every container restart since, with the current implementation, they'll be ignored. Indeed, I'd recommend to unset the `discourse.plugins` chart parameter during helm upgrades. I'm talking about the commands below:

- https://github.com/bitnami/charts/blob/main/bitnami/discourse/templates/deployment.yaml#L114-L120

A possible workaround for avoiding plugins to be persisted, so they're installed/updated on every container restart, would be overwriting the default value for the `DISCOURSE_DATA_TO_PERSIST` env. variables removing the `plugins` folder, see:

- https://github.com/bitnami/containers/blob/main/bitnami/discourse/3/debian-11/rootfs/opt/bitnami/scripts/discourse-env.sh#L105

For instance, installing the chart using a values such as the ones below:

```yaml
extraEnvVars:
  - name: DISCOURSE_DATA_TO_PERSIST
    value: "public/backups public/uploads"
```

**Comment by psych0d0g** [comment]
okay, that workaround might be an idea, but that still leaves the use-case of plugin code-updates to be solved.
so if, for example, i have a plugin installed via the chart, and at one point the plugins git repo gets updated, which happens quite a bit ;), the updated plugin will never be installed in the discourse container running, it will potentially be checked out (probably into the right location but there will be a symlink created after the checkout to point to a diffrent location, leaving the files and folders underneeth inaccessible) but never actually used by the discourse instance.

so it will run outdated plugins with the user not directly aware (since container startup logs plugin git checkouts)

**Comment by juan131** [comment]
Hi @psych0d0g 

Yes, we should definitely document it, please take a look to the PR I just submitted.
