### ISSUE TITLE
OPENCART_ENABLE_HTTPS is not working

### ISSUE THREAD

**Issue by iliyan-velichkov** [bitnami/charts#21322]
### Name and Version

docker.io/bitnami/opencart:4.0.2-3-debian-11-r21

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I'm installing `bitnami/opencart` version `16.1.2` on a k8s cluster but when I try to access the application I receive the following error:
![image](https://github.com/bitnami/containers/assets/5058839/59b859ea-53ef-4f30-be38-0e7baa149026)

The chart was installed with the following configurations:
```
helm pull bitnami/opencart -d "$CHART_FOLDER" --version $CHART_VERSION

helm install $CHART_NAME ./opencart --set opencartHost=$OPEN_CART_HOST,opencartUsername=$OPEN_CART_APP_USER,opencartPassword=$OPEN_CART_APP_PASSWORD,mariadb.auth.rootPassword=$OPEN_CART_DATABASE_ROOT_PASSWORD,mariadb.auth.password=$OPEN_CART_DATABASE_PASSWORD,opencartEnableHttps=true,service.type=ClusterIP,ingress.enabled=false 
```

I checked the opencart pod and OPENCART_ENABLE_HTTPS was set to true.
![image](https://github.com/bitnami/containers/assets/5058839/efed64cf-4260-4d71-90b7-cb98c2f87d20)

Here is an example of the `/bitnami/opencart/config.php`
![image](https://github.com/bitnami/containers/assets/5058839/6518555c-c688-41c0-a09a-7378c0ab9210)

### What is the expected behavior?

to server static resources from the HTTPS

### What do you see instead?

OpenCart tries to load static resources through HTTP

**Comment by iliyan-velichkov** [comment]
The workaround actually works only for the home page.
If you open the admin page https://example.com/administration you get the same error:
![image](https://github.com/bitnami/charts/assets/5058839/13ea602e-79b1-41bf-a4ae-6e703f5fa7f8)

**Comment by FraPazGal** [comment]
Hello @iliyan-velichkov! Thanks for the report and providing a workaround. I have reproduced the issue and it seems adding the `HTTPS_SERVER` params to the config is not enough. To fix this we'll need to modify the container's [initialisation logic](https://github.com/bitnami/containers/blob/e0d89a9a722f669f2e4fafe80039dece0cf39564/bitnami/opencart/4/debian-11/rootfs/opt/bitnami/scripts/libopencart.sh#L318) so it uses `https` everywhere.

Would you be interested in contributing in our `bitnami/containers` repo with a fix? The team will be happy to review the PR and help you if need!

**Comment by iliyan-velichkov** [comment]
@FraPazGal did you get a change to check the PR?

**Comment by iliyan-velichkov** [comment]
any updates about the PR?

**Comment by FraPazGal** [comment]
Hello @iliyan-velichkov, it seems my colleague in charge of the PR review hasn't gotten back to you. I'll sync with him and he'll reach out as soon as possible.

**Comment by iliyan-velichkov** [comment]
the [PR](https://github.com/bitnami/containers/pull/53359) was merged
