### ISSUE TITLE
cassandra bitnmami chart enable G1GC garbade collection instead of default CMS

### ISSUE THREAD

**Issue by jalsanishant** [bitnami/charts#21332]
### Name and Version

bitnami/cassandra 10.6.6

### What is the problem this feature will solve?

improves the efficiency of ram management, clears unused space, enables faster processing of tables

### What is the feature you are proposing to solve the problem?

need an option for enabling G1GC on all replicas of Cassandra pods inside values of helm chart - https://github.com/bitnami/charts/blob/main/bitnami/cassandra/values.yaml
instead of manually changing config at /opt/bitnami/cassandra/conf/jvm11-server.options file on a pod which is not ideal

### What alternatives have you considered?

manual change requires commenting of CMS settings & uncommenting G1GC settings inside jvm11-server.options file:
```
#################
# GC SETTINGS #
#################


### CMS Settings
-XX:+UseConcMarkSweepGC
-XX:+CMSParallelRemarkEnabled
-XX:SurvivorRatio=8
-XX:MaxTenuringThreshold=1
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:CMSWaitDuration=10000
-XX:+CMSParallelInitialMarkEnabled
-XX:+CMSEdenChunksRecordAlways
## some JVMs will fill up their heap when accessed via JMX, see CASSANDRA-6541
-XX:+CMSClassUnloadingEnabled


### G1 Settings
## Use the Hotspot garbage-first collector.
#-XX:+UseG1GC
#-XX:+ParallelRefProcEnabled

#
## Have the JVM do less remembered set work during STW, instead
## preferring concurrent GC. Reduces p99.9 latency.
#-XX:G1RSetUpdatingPauseTimePercent=5
#
## Main G1GC tunable: lowering the pause target will lower throughput and vise versa.
## 200ms is the JVM default and lowest viable setting
## 1000ms increases throughput. Keep it smaller than the timeouts in cassandra.yaml.
#-XX:MaxGCPauseMillis=500

## Optional G1 Settings
# Save CPU time on large (>= 16GB) heaps by delaying region scanning
# until the heap is 70% full. The default in Hotspot 8u40 is 40%.
#-XX:InitiatingHeapOccupancyPercent=70

# For systems with > 8 cores, the default ParallelGCThreads is 5/8 the number of logical cores.
# Otherwise equal to the number of cores when 8 or less.
# Machines with > 10 cores should try setting these to <= full cores.
#-XX:ParallelGCThreads=16
# By default, ConcGCThreads is 1/4 of ParallelGCThreads.
# Setting both to the same value can reduce STW durations.
#-XX:ConcGCThreads=16
```
--> checkout https://github.com/k8ssandra/k8ssandra/blob/140cf8d5960e6fd2b4265817e5a7fdb177a7559d/charts/k8ssandra/values.yaml#L228

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
