### ISSUE TITLE
Prometheus chart creates ClusterRoleBinding even with rbac disbaled

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#21347]
### Name and Version

bitnami/promethes 0.4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set `server.rbac.create=false`
2. Observe that the ClusterRole is not generated, but ClusterRoleBinding is

### Are you using any custom parameters or values?

```yaml
server:
  rbac:
    create: false
```

### What is the expected behavior?

Neither ClusterRole nor ClusterRoleBinding are generated

### What do you see instead?

ClusterRoleBinding is generated

### Additional information

A quick look through other charts, looks like most of them check if rbac enabled before creating ClusterRoleBinding.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
