### ISSUE TITLE
[prometheus-operator] upgrade failed / remoteWrite error validating data

### ISSUE THREAD

**Issue by ssh2n** [bitnami/charts#2135]
**Which chart**: prometheus-operator:0.13.6

**Description**
Wanted to upgrade, but it failed, may you help?

**Steps to reproduce the issue:**

1. [First Step]
put this to values.yaml
  remoteWrite:
    - url: http://url.com
      queue_config:
        max_samples_per_send: 10000
        max_shards: 30
      basic_auth:
        username: xxx
        password: xxx
2. [Second Step]
helm upgrade my-release bitnami/prometheus-operator -f values.yaml
3. [and so on...]

**Describe the results you received:**

helm upgrade prom bitnami/prometheus-operator \         
--namespace monitoring \
-f ./values/prom.yaml 
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "basic_auth" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite, ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "queue_config" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite]

**Describe the results you expected:**

upgraded...
-->

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by miguelaeh** [comment]
Hi @ssh2n ,
Have you tried to not specify those two parameters that do  not have a value?
Try changing:
```diff
remoteWrite:
    url: http://url.com
-    queue_config:
    max_samples_per_send: 10000
    max_shards: 30
-    basic_auth:
    username: xxx
    password: xxx
```

**Comment by ssh2n** [comment]
Not by now, as I have to redeploy the cloluster anyway.
But is the correct formate to have - url: or schould i leave it away ?

**Comment by ssh2n** [comment]
+ btw if i manually add erporters, schould/can i add them to the values.yaml ? 
Likke:
exporters:
  node-exporter:
    enabled: true
  kube-state-metrics:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true

kubeProxy:
  service:
    port: 10249
    targetPort: 10249
    selector:
      k8s-app: kube-proxy
  serviceMonitor:
    interval: "10s"
    https: false

kubeScheduler:
  service:
    port: 10251
    targetPort: 10251
    selector:
      component: kube-scheduler
  serviceMonitor:
    interval: "10s"
    https: false

kubeControllerManager:
  service:
    port: 10252
    targetPort: 10252
  serviceMonitor:
    interval: "10s"
    https: false

node-exporter:
  service:
    labels:
      jobLabel: node-exporter
  serviceMonitor:
    enabled: true
    jobLabel: jobLabel
  extraArgs:
    collector.filesystem.ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
    collector.filesystem.ignored-fs-types: "^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$"

kube-state-metrics:
  replicaCount: 2
  serviceMonitor:
    enabled: true
    interval: "10s"

kubeApiServer:
  enabled: true
  serviceMonitor:
    interval: "10s"
    metricRelabelings: []
    relabelings: []

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true
    interval: "10s"
    metricRelabelings: []
    relabelings: []
    cAdvisorMetricRelabelings: []
    cAdvisorRelabelings: []

exporters:
  node-exporter:
    enabled: true
  kube-state-metrics:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true

kubeProxy:
  service:
    port: 10249
    targetPort: 10249
    selector:
      k8s-app: kube-proxy
  serviceMonitor:
    interval: "10s"
    https: false

kubeScheduler:
  service:
    port: 10251
    targetPort: 10251
    selector:
      component: kube-scheduler
  serviceMonitor:
    interval: "10s"
    https: false

kubeControllerManager:
  service:
    port: 10252
    targetPort: 10252
  serviceMonitor:
    interval: "10s"
    https: false

node-exporter:
  service:
    labels:
      jobLabel: node-exporter
  serviceMonitor:
    enabled: true
    jobLabel: jobLabel
  extraArgs:
    collector.filesystem.ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
    collector.filesystem.ignored-fs-types: "^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$"

kube-state-metrics:
  replicaCount: 2
  serviceMonitor:
    enabled: true
    interval: "10s"

kubeApiServer:
  enabled: true
  serviceMonitor:
    interval: "10s"
    metricRelabelings: []
    relabelings: []

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true
    interval: "10s"
    metricRelabelings: []
    relabelings: []
    cAdvisorMetricRelabelings: []
    cAdvisorRelabelings: []

**Comment by miguelaeh** [comment]
Hi @ssh2n ,
You can add to your custom values.yaml only the parameters that are defined [here](https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/values.yaml). If you add more they will not take any effect as the chart will not use them in its templates.

**Comment by ssh2n** [comment]
And about the format of remotewrite with basic_auth and queue_config values?
Is a feature request needed?

**Comment by miguelaeh** [comment]
Hi @ssh2n ,
Could you share the error after deleting those properties? I guess it should not be the same as you are not providing them.
