### ISSUE TITLE
[bitnami/rabbitmq] Request for Modification in RabbitMQ Helm Chart to Support HashiCorp Vault Integration

### ISSUE THREAD

**Issue by sobrito** [bitnami/charts#21359]
### Name and Version

bitnami/rabbitmq 12.5.5

### What is the problem this feature will solve?

The current issue is the incompatibility between Bitnami's RabbitMQ Helm chart and HashiCorp's Vault Secrets service. The key for the RabbitMQ password needs to be rabbitmq-password, but Vault Secrets does not accept hyphens (-) in secret names, limiting the integration between these two services.

### What is the feature you are proposing to solve the problem?

I am proposing two potential solutions:

- Change the default key from rabbitmq-password to rabbitmq_password, allowing direct integration with Vault, which accepts underscores (_) in names.
- Add an option in values.yaml to set a custom name for the secret key, providing flexibility to adapt to different secret management systems.

### What alternatives have you considered?

The alternatives I have considered include:

- Not using HCPVaultSecretsApp and looking for other password management solutions that are compatible with the current structure of the RabbitMQ Helm chart.
- Manually entering the password in the chart, which would reduce the security and automation of the process.

**Comment by javsalgar** [comment]
Hi!

In other charts we add support for `existingSecretKey`, which I believe could fix the issue you are facing. Would you like to submit a PR adding support for this?

**Comment by maxvisser** [comment]
Should be completely fixed after https://github.com/bitnami/charts/pull/22016 is merged
