### ISSUE TITLE
[rabbitmq] ERROR: epmd error for host xxx: nxdomain (non-existing domain)

### ISSUE THREAD

**Issue by xunchangguo** [bitnami/charts#2136]
**Which chart**:

rabbitmq
version：6.9.12

**Description**

ERROR: epmd error for host rabbitmq-0.rabbitmq-headless.db.svc.cluster.local: nxdomain (non-existing domain)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @xunchangguo,

Could you try adding this annotation:
```
annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
```

`helm install my-release --set-string service.annotations."service\.alpha\.kubernetes\.io/tolerate-unready-endpoints"=true bitnami/rabbitmq`

**Comment by xunchangguo** [comment]
Hi @Mauraza,

Thank u very much!
add this anotations it's work, but not add on the rabbitmq Service, add on rabbitmq-**headless** Service

**Comment by ashexpertVersion2** [comment]
Hi i have the same problem even after adding that annotation...
i even tried adding:
`  publishNotReadyAddresses: true`
but still no luck ...

**Comment by Mauraza** [comment]
Hi @ashexpertVersion2,

To add this annotation in the service it's the same `helm install my-release --set-string service.annotations."publishNotReadyAddresses"=true  bitnami/rabbitmq`.

**Comment by ashexpertVersion2** [comment]
hi @Mauraza 
i also tried that solution... even i execute your command again (exactly that command) but still getting nxdomain...

**Comment by Mauraza** [comment]
Hi @ashexpertVersion2 ,

I think you need to do it in `rabbitmq-headless`. Cloud you try that?

**Comment by ashexpertVersion2** [comment]
yes i tried both annotation and publishNotReadyAddresses field on both headless and normal svc.

**Comment by Mauraza** [comment]
Hi @ashexpertVersion2,

I think this it's another issue, could you please open another issue with the information of your cluster, the version of kubectl and helm are you using?

**Comment by ashexpertVersion2** [comment]
one solution is to set rabbitmq.clustering.address type to something other than hostname, but i think this is not the way...

**Comment by ashexpertVersion2** [comment]
ok.

**Comment by ashexpertVersion2** [comment]
rookie mistake....
haven't set proper k8s_domain. :((((
thanks @Mauraza and sorry for wasting your time.
