### ISSUE TITLE
[bitnami/kube-prometheus] Throwing "patch" errors in kube-apiserver logs

### ISSUE THREAD

**Issue by dtu-ruth** [bitnami/charts#21361]
### Name and Version

bitnami/kube-prometheus 8.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Rollout Prometheus
2. Check logs of kube-apiserver

### What is the expected behavior?

No errors in the kube-apiserver logs

### What do you see instead?

`E1204 02:51:17.635535       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:\"failed to create typed patch object (monitoring\/prometheus-default-prometheus; monitoring.coreos.com\/v1, Kind=Prometheus): errors:\\n  .status.conditions[type=\\\"Available\\\"].observedGeneration: field not declared in schema\\n  .status.conditions[type=\\\"Reconciled\\\"].observedGeneration: field not declared in schema\"}: failed to create typed patch object (monitoring\/prometheus-default-prometheus; monitoring.coreos.com\/v1, Kind=Prometheus): errors:\n`

**Comment by javsalgar** [comment]
Hi,

Could you check that the CRDs are updated to the latest version?

**Comment by dtu-ruth** [comment]
Hi @javsalgar, updating to the latest CRD's seemed to have solved the issue.
I will be closing the issue.

Thank you for your advice! (:
