### ISSUE TITLE
Bitnami Application Catalog Based on Debian 12, Coming Soon

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#21362]
We're excited to share that during January 2024, the current Debian 11 “bullseye” used as the base image of Bitnami containers -and therefore Helm charts- will be replaced with Debian 12 "bookworm".

This is a significant change in our containers and Helm charts that helps to keep system packages more updated and reduce the number of unfixed/unpatched vulnerabilities reported by vulnerability scanners. Currently, although we regularly update our images with the latest system packages, certain CVEs may persist until they are patched in either the OS or the application so changing to a newer distro will allow us to speed up the updates on our catalog. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

Besides the Bitnami Application Catalog built on Debian 12 (community version), users have the possibility to build their applications on the base OS of their choice through the enterprise version of the Bitnami Application Catalog: [VMware Tanzu Application Catalog](https://app-catalog.vmware.com/catalog). Tanzu Application Catalog offers various base images such as Debian 10, 11 & 12, PhotonOS 3 & 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images to choose from.

### What changes are expected?
- **Container image tags**
  - As per the Bitnami [rolling tags policy](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/), some tags will change to reflect the new distro version i.e. `6-debian-11` will be `6-debian-12`.
  - Other rolling tags will point to the new Debian 12-based containers without an explicit mention in their name, i.e. `latest`.
  - The immutable tag will also change to show the new distro version, resetting the revision number, i.e. `6.4.1-debian-11-r4` will be `6.4.1-debian-12-r0`.
  - There would not be any deletion of any image. All the Debian 11 images will persist in the registry.

- **bitnami/containers GitHub repository**
  - In terms of the source code, the [GitHub repository](https://github.com/bitnami/containers) will change its directory structure from `bitnami/ASSET/BRANCH/debian-11` to `bitnami/ASSET/BRANCH/debian-12`.
  - Please note both directories (`debian-11` and `debian-12`) could coexist for some time.

- **Helm charts**
  - Since backward compatibility won't be affected by a change in the distro version used by the containers, a major version bump of the Helm chart version is not expected.
  - A new version of every Helm chart will be released updating the bundled containers pointing to Debian 12-based images, i.e
```diff
  repository: bitnami/mariadb
-  tag: 11.1.3-debian-11-r0
+  tag: 11.1.3-debian-12-r0
 
    repository: bitnami/os-shell
-    tag: 11-debian-11-r91
+    tag: 12-debian-12-r0
```

If you have any further questions, feel free to ask.

**Comment by ira-gordin-sap** [comment]
Is it relevant for [bitnami/redis]?

**Comment by carrodher** [comment]
> Is it relevant for [bitnami/redis]?

Yes, all the images will receive an update in the underlying distro, although no breaking changes are expected.

**Comment by mveitas** [comment]
Is there an update for this issue?

**Comment by carrodher** [comment]
> Is there an update for this issue?

Yes, in fact, all the containers and Helm charts are now available in Debian 12.
