### ISSUE TITLE
[bitnami/keycloak] allow existingConfigmapAsSecret in addition to existingConfigmap

### ISSUE THREAD

**Issue by joaocc** [bitnami/charts#21384]
### Name and Version

bitnami/keycloak 17.3.4

### What is the problem this feature will solve?

Currently, configuration can be added via ConfigMap.
However, this doesn't allow a useful pattern (in gitops scenarios) of using ExternalSecrets template v2 to dynamically generate complex configs as secrets.

### What is the feature you are proposing to solve the problem?

Add a variable existingConfigmapAsSecret that would behavi similarly to existingConfigmap, but instead of sourcing the configuration from a ConfigMap, it would do it from a Secret.

### What alternatives have you considered?

Using valuesFrom in helmreleases (flux2/gitops) but it isn't as flexible as that

**Comment by javsalgar** [comment]
Hi! Thank you so much for the feature request. Would you like to submit a PR adding the value?
