### ISSUE TITLE
[bitnami/mysql] [bitnami/mariadb] Allow deployment without specifying a rootPassword explicitly

### ISSUE THREAD

**Issue by MurzNN** [bitnami/charts#21410]
### Name and Version

bitnami/mysql 9.14.4

### What is the problem this feature will solve?

I just want to deploy mysql or mariadb without specifying a `rootPassword` explicitly in `values.yaml` file or anywhere else!

But seems it is not possible?

Here is the comment for the `auth.rootPassword` value:
> Password for the root user. Ignored if existing secret is provided

So I can put the `auth.existingSecret` value, instead of it, great!

But not so much! Again, I should create the secret resource manually with specifying the password manually.

So, most of the users just put the `rootPassword` to the `values.yaml` as plaintext, which is very insecure, and then - some of them also upload the `values.yaml` to shared git repos, reducing the security to zero.

I know that we can use helm-secrets with SOPS, age, or any other secret backends, and I personally already use them. But it is a too hard step for many other users, so most of them still store passwords as plaintext in YAML files.

### What is the feature you are proposing to solve the problem?

To resolve this issue, will be good to integrate a password generator into the helm chart, which will generate a random secure password and put it into the secret resource automatically.

Maybe via a separate option like `auth.generateInitialrootPassword`.

And the same - for the `auth.password` and `auth.replicationPassword` too.

This small feature will simplify deploying significantly, with increasing security!

Also, will be good to share this approach with all other Bitnami helm charts.

### What alternatives have you considered?

No alternatives come to my mind yet.

**Comment by javsalgar** [comment]
Hi,

AFAIK, if you don't specify a password the chart should generate a random one for you. Did you try it? Did you see any error?
