### ISSUE TITLE
Add support for using the bitnami/openresty image in the nginx helm chart

### ISSUE THREAD

**Issue by eldada** [bitnami/charts#21416]
### Name and Version

bitnami/nginx

### What is the problem this feature will solve?

The ability to have a helm deployment of the official [bitnami openresty container image](https://hub.docker.com/r/bitnami/openresty) using the current bitnami nginx Helm chart.

### What is the feature you are proposing to solve the problem?

The two images are similar, and when I just replace the `image.repository` to `bitnami/openresty` and set `image.tag` to `latest`, it works (I didn't do a deep test of features).
But - mapping of custom configuration like adding a `serverBlock` does not get mounted to the right location.

In the nginx image, it goes to `/opt/bitnami/nginx/conf/server_blocks`
In the openresty image, it needs to go to `/opt/bitnami/openresty/nginx/conf/server_blocks`

There are probably other areas of configuration that need adjustments.

I'm proposing one of the options
- Adjusting the images to use a more similar file system structure (and maybe keeping compatibility with some links)
- Adjusting the nginx helm chart to detect what image it's using and correct the paths as needed

### What alternatives have you considered?

Creating a new `openresty` helm chart, but it feels like this is a waste of effort as part of the solution is already in the nginx chart.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by eldada** [comment]
I'll try to get around to it. Anyone else seeing this is more than welcome to try and I'll be happy to review.
