### ISSUE TITLE
[bitnami-spring-cloud-dataflow] Logging output in JSON format

### ISSUE THREAD

**Issue by dhpizza** [bitnami/charts#21414]
### Name and Version

bitnami/spring-cloud-dataflow 25.0.0

### What is the problem this feature will solve?

More and more cloud native users request JSON-format structured logging which is easier to aggregate and parse by log collectors. Enabling JSON logging in the spring-cloud-dataflow helm chart today will require users to build their own custom Docker image with some additional JAR libs and a custom logback configuration file, which adds a burden on every single user. Thus adding this to the container project seems like a good fit.

### What is the feature you are proposing to solve the problem?

I'd like it to be easy to enable `JSON` logging in bitnami/spring-cloud-dataflow and bitnami/spring-cloud-skipper docker image. Ideally by simply adding SCDF_LOG_FORMAT=JSON. The default should still be normal text logging.

The needed changes to will include

* Add a logback.xml to the repo, with configuration for JSON logging (appender / encoder)

* Introduce a new env.var e.g. SCDF_LOG_FORMAT=json to enable the feature.

### What alternatives have you considered?

Tried to add a logback-spring.xml config via ConfigMap and place the config in
`/opt/bitnami/spring-cloud-skipper/conf/` and `/opt/bitnami/spring-cloud-dataflow/conf/` but these dirs are read-only

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
