### ISSUE TITLE
etcd database is getting filled up so quickly or throwing error connection timeout

### ISSUE THREAD

**Issue by abhayycs** [bitnami/charts#21429]
### Name and Version

bitnami/etcd-3.5.8

### What architecture are you using?

None

### What steps will reproduce the bug?

I have an application which stores a lot of it's data in etcd(persistence=enabled), and keeps updating the database all the time. Due to this my etcd db is getting full. Even if I have enable the compaction 'periodically'. I'm afraid if I decrease the compaction interval then my etcd will become more slower. 
I was wondering if there is any way to tell etcd to maintain only one single 'revision' of data in the database and avoid compaction. Could you please help me with this, if it is possible?

### What do you see instead?

My etcd db gets filled up so quickly, or it becomes really slow and starts throwing 'connection timeout' error .

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by abhayycs** [comment]
Hi @carrodher, 
I just have a query. 
Using bitnami-etcd-helm-charts or in it's configuration, do we have any option to make etcd to maintain only a single 'revision' of data in the database and avoid compaction?
