### ISSUE TITLE
[postgresql-ha] v0.4 PostGIS isn't being installed when deployed to cloud

### ISSUE THREAD

**Issue by ZephSibley** [bitnami/charts#2142]
**Which chart**:
postgresql-ha v0.4

**Describe the bug**
I've deployed the database but when my API goes to make migrations it falls over, saying that the type geometry isn't recognised, and that postgis probably isn't installed.

I had this issue before on my minikube cluster deployment **before** I downgraded to v0.4. The issue is fixed on my minikube cluster, but the Linode deployment is giving me the same issue despite using virtually same config and version, the only difference is that on the cloud I've configured it to use a loadbalancer. I have redeployed many times now.

**To Reproduce**
1. Deploy postgresql-ha v0.4 (maybe on Linode)
2. Try to use PostGIS stuff

**Expected behavior**
PostGIS should already be installed on the database.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  I tried both versions of the chart, v2.0.1 and 0.4.0 and both reported that postgis is installed.
  This is what I did:
```
$ helm install my-pgha bitnami/postgresql-ha --version 0.4.0

(wait until the deployment is completed)

$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-pgha-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ kubectl run my-pgha-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql:10 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h my-pgha-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION

postgres=# SELECT PostGIS_Version();
            postgis_version            
---------------------------------------
 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)

```
```
$ helm3 install my-pgha bitnami/postgresql-ha

(wait until the deployment is completed)

$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-pgha-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ kubectl run my-pgha-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql:11 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
         --command -- psql -h my-pgha-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION

postgres=# SELECT PostGIS_Version();
            postgis_version            
---------------------------------------
 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)

```
  Could you give it a try ?

**Comment by ZephSibley** [comment]
I upgraded to the latest version using kubeapps and ran the commands:
`kubectl run prod-db-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql:11 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
         --command -- psql -h prod-db-postgresql-ha-pgpool -p 5432 -U postgres -d postgres
If you don't see a command prompt, try pressing enter.

postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION
postgres=# SELECT PostGIS_Version();
            postgis_version
---------------------------------------
 2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
`

Unfortunately I'm still getting the same result when my API runs migrations. Could it be because I'm running it with a loadbalancer?

**Comment by ZephSibley** [comment]
Apologies, I ran the CREATE EXTENSION command on the default database instead of the one I specified in the config.

I must have done all this on my Minikube cluster and completely forgotten about it.

Thanks for the help.
