### ISSUE TITLE
Enabling metrics in postgres-ha causes double metrics collection

### ISSUE THREAD

**Issue by danielgoepp** [bitnami/charts#21448]
### Name and Version

postgresql-ha-12.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Boot a clean cluster with metrics enabled in helm chart using all default settings

### Are you using any custom parameters or values?

No

### What is the expected behavior?

By default I would think that the annotations for prometheus would just get added to the pods by default, not a service created too. If a user prefers to use a service, great, have an option that says "use service" or "use pods" for metrics collection. But, defaulting to enabling both methods seems redundant.

### What do you see instead?

Currently the chart will add the necessary annotations to the pods so that prometheus will automatically start scraping:

```
prometheus.io/port: 9187
prometheus.io/scrape: true
```

However, it will also add a new service:
```
service/postgres-postgresql-ha-postgresql-metrics    ClusterIP   10.43.99.125    <none>        9187/TCP   2s
```

This service has the same annotations as above, and includes all the existing pods.

This causes all the same metrics to get collected twice, once directly from the pods, and once from the service pointing to the pods.

### Additional information

My work around for now is to just simple kill the metrics service. But, it comes back every run of the chart to update.

Here is an example query showing the double entries:
postgres_exporter_build_info {namespace="pgtest"}

```
postgres_exporter_build_info{app_kubernetes_io_component="postgresql", app_kubernetes_io_instance="postgres", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="postgresql-ha", app_kubernetes_io_version="16.1.0", branch="HEAD", controller_revision_hash="postgres-postgresql-ha-postgresql-79f645f879", goarch="amd64", goos="linux", goversion="go1.20.11", helm_sh_chart="postgresql-ha-12.3.2", instance="192.168.73.18:9187", job="kubernetes-pods", namespace="pgtest", node="k3s-prod-02", pod="postgres-postgresql-ha-postgresql-0", revision="68c176b8833b7580bf847cecf60f8e0ad5923f9a", role="data", statefulset_kubernetes_io_pod_name="postgres-postgresql-ha-postgresql-0", tags="unknown", version="0.15.0"} | 1
postgres_exporter_build_info{app_kubernetes_io_component="postgresql", app_kubernetes_io_instance="postgres", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="postgresql-ha", app_kubernetes_io_version="16.1.0", branch="HEAD", controller_revision_hash="postgres-postgresql-ha-postgresql-79f645f879", goarch="amd64", goos="linux", goversion="go1.20.12", helm_sh_chart="postgresql-ha-12.3.2", instance="192.168.79.53:9187", job="kubernetes-pods", namespace="pgtest", node="k3s-prod-01", pod="postgres-postgresql-ha-postgresql-1", revision="68c176b8833b7580bf847cecf60f8e0ad5923f9a", role="data", statefulset_kubernetes_io_pod_name="postgres-postgresql-ha-postgresql-1", tags="unknown", version="0.15.0"} | 1
postgres_exporter_build_info{app_kubernetes_io_component="postgresql", app_kubernetes_io_instance="postgres", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="postgresql-ha", app_kubernetes_io_version="16.1.0", branch="HEAD", controller_revision_hash="postgres-postgresql-ha-postgresql-79f645f879", goarch="amd64", goos="linux", goversion="go1.20.12", helm_sh_chart="postgresql-ha-12.3.2", instance="192.168.86.220:9187", job="kubernetes-pods", namespace="pgtest", node="k3s-prod-03", pod="postgres-postgresql-ha-postgresql-2", revision="68c176b8833b7580bf847cecf60f8e0ad5923f9a", role="data", statefulset_kubernetes_io_pod_name="postgres-postgresql-ha-postgresql-2", tags="unknown", version="0.15.0"} | 1
postgres_exporter_build_info{app_kubernetes_io_component="postgresql", app_kubernetes_io_instance="postgres", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="postgresql-ha", app_kubernetes_io_version="16.1.0", branch="HEAD", goarch="amd64", goos="linux", goversion="go1.20.11", helm_sh_chart="postgresql-ha-12.3.2", instance="192.168.73.18:9187", job="kubernetes-service-endpoints", namespace="pgtest", node="k3s-prod-02", prometheus="kube-prometheus", revision="68c176b8833b7580bf847cecf60f8e0ad5923f9a", service="postgres-postgresql-ha-postgresql-metrics", tags="unknown", version="0.15.0"} | 1
postgres_exporter_build_info{app_kubernetes_io_component="postgresql", app_kubernetes_io_instance="postgres", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="postgresql-ha", app_kubernetes_io_version="16.1.0", branch="HEAD", goarch="amd64", goos="linux", goversion="go1.20.12", helm_sh_chart="postgresql-ha-12.3.2", instance="192.168.79.53:9187", job="kubernetes-service-endpoints", namespace="pgtest", node="k3s-prod-01", prometheus="kube-prometheus", revision="68c176b8833b7580bf847cecf60f8e0ad5923f9a", service="postgres-postgresql-ha-postgresql-metrics", tags="unknown", version="0.15.0"} | 1
postgres_exporter_build_info{app_kubernetes_io_component="postgresql", app_kubernetes_io_instance="postgres", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="postgresql-ha", app_kubernetes_io_version="16.1.0", branch="HEAD", goarch="amd64", goos="linux", goversion="go1.20.12", helm_sh_chart="postgresql-ha-12.3.2", instance="192.168.86.220:9187", job="kubernetes-service-endpoints", namespace="pgtest", node="k3s-prod-03", prometheus="kube-prometheus", revision="68c176b8833b7580bf847cecf60f8e0ad5923f9a", service="postgres-postgresql-ha-postgresql-metrics", tags="unknown", version="0.15.0"}
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by danielgoepp** [comment]
Thanks @carrodher - I wish I could, but I'm not familiar enough with this chart right now to help. Perhaps if I get a little time I can dig into it. I'm hoping someone more familiar with it could take a quick look and perhaps at least provide a work around? As I mentioned, even if a fancy automatic solution is not possible, perhaps just a flag that lets you disable or set the preferred method. I dunno.

**Comment by seang96** [comment]
Which one would it be preferred to stay on? This looks like it would be an easy change.

**Comment by danielgoepp** [comment]
Personally I think that having metrics collected directly from the pods makes the most sense. Just my two cents.

**Comment by danielgoepp** [comment]
Thanks @seang96! I just checked back in on this. I see you have implemented a solution, I will test it out. Appreciate the help.
