### ISSUE TITLE
[bitnami/contour] Add supports for contour and envoy PodDisruptionBudgets

### ISSUE THREAD

**Issue by PSanetra** [bitnami/charts#21457]
### Name and Version

bitnami/contour 15.0.1

### What is the problem this feature will solve?

Currently contour and envoy Deployments may experience downtime during node maintenance.

### What is the feature you are proposing to solve the problem?

It would be nice if PodDisruptionBudgets could be enabled for these deployments to avoid downtime. This is already supported on the default-backend.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
