### ISSUE TITLE
external-dns 2.20.8 serviceAccountName does not create service account

### ISSUE THREAD

**Issue by haghabozorgi** [bitnami/charts#2147]
**Which chart**: 
external-dns

**Describe the bug**
using tf to deploy helm charts. The service account does not get created, causing the helm chart install to time out on the deployment since the serviceaccount referenced does not exist.
From what I can tell the 'not' in this statement is causing the account not to be created
https://github.com/bitnami/charts/commit/11ee48ee38160447ec5616116d93b8f339eecf7c#diff-4bfe3d6e75164b7d166575aaa807b761R1

But i could be wrong. additionally, I am not certain there should be duplicate `if` line in L37-38 of deployment.yaml  https://github.com/bitnami/charts/commit/11ee48ee38160447ec5616116d93b8f339eecf7c#diff-2de4b1675ddca29c3d48da6f3a4e95fdR38

**To Reproduce**
install 2.20.8 chart on kube cluster with this snippet below
```
rbac:
  create: true
  serviceAccountName: "testaccount"
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${testaccount_iam_role}"
```
happens on update from 2.20.7 as well.

**Expected behavior**
the service account should be created so the deployment does not time out looking for a serviceaccount that does not exist.

**Version of Helm and Kubernetes**:
eks 1.15
helm 3.1.1

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
we have tested against 2.20.7 and 2.20.4 and both work as expected.

**Comment by juan131** [comment]
Hi @haghabozorgi 

Thanks for reporting this issue! I just create to address it ASAP. See https://github.com/bitnami/charts/pull/2151
