### ISSUE TITLE
README Typo for Galera Cluster Helm Chart

### ISSUE THREAD

**Issue by advra** [bitnami/charts#21470]
### Name and Version

bitnami/mariadb-galera

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The README states:
```
helm install my-release \
  --set rootUser.password=secretpassword,
  --set db.user=app_database \
    oci://REGISTRY_NAME/REPOSITORY_NAME/mariadb-galera
```

Instead it should read the following where comma `,` should instead be `\`:
```
helm install my-release \
  --set rootUser.password=secretpassword \
  --set db.user=app_database \
    oci://REGISTRY_NAME/REPOSITORY_NAME/mariadb-galera
```

### What do you see instead?

```
[test@test sbns]$ helm install my-release \
>   --set rootUser.password=secretpassword,
   bitnami/mariadb-galeraError: INSTALLATION FAILED: must either provide a name or specify --generate-name
[test@test sbns]$   --set db.user=app_database \
>     bitnami/mariadb-galera
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
