### ISSUE TITLE
[bitnami/thanos] Allow configuration of minReadySeconds for Thanos Receive

### ISSUE THREAD

**Issue by luqic** [bitnami/charts#21480]
### Name and Version

bitnami/thanos 12.15.0

### What is the problem this feature will solve?

There's currently an issue with "Out of bounds" errors when the Thanos Receive cluster restarts, and one of the working solutions is to set `spec/minReadySeconds: 120`.

Ref: https://github.com/thanos-io/thanos/issues/4831#issuecomment-1503754747

### What is the feature you are proposing to solve the problem?

Allow configuration of `minReadySeconds` for Thanos Receive.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by luqic** [comment]
Sure! I'll give it a shot.

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
