### ISSUE TITLE
[bitnami/postgresql-ha] PGPool II using mTLS and custom configuration cannot be used together as it breaks with pgHbaConfiguration: - It's also unknow how it works by default

### ISSUE THREAD

**Issue by xtianus79** [bitnami/charts#21493]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

None

### What steps will reproduce the bug?

Writing any custom pg_hba.conf on the postgres servers using `pgHbaConfiguration: ""` breaks the installation. 

When setting up the helm chart it seems like a logical thing you could setup as custom for how the backend should react to incoming certificates. When reading documentation it is clear that the hostssl should be set to all all cert and the password would not be used thereafter. 
What I was attempting to-do but it failed. 
```bash
host     all            repmgr    0.0.0.0/0    md5
    host     repmgr         repmgr    0.0.0.0/0    md5
 ...
    hostssl  all            all       0.0.0.0/0    cert
    hostssl  all            all       ::/0         cert
    #host     all            all       0.0.0.0/0    md5
    #host     all            all       ::/0         md5
 ....
```
What's weird is that when trying to set this up it took a couple days of wondering why this wasn't working and even seeing if there was just somewhere else to define the HBA. 

Then I thought, ok let me just try to login with postgress and rever the changes when the changes in PG server's pg_hba.conf cleary has the host uncommented and the hostssl commented out. 

To my surprise I saw that it did work. But how? All pg documentation leads you to think you have to properly setup the hba conf. 

I am using CA verify-full and it works but how? I am confused as to why this would work when the visible hba doesn't seem to be setup correctly. 

Is there another pg_hba.conf somewhere? or is it the client ca cert command and the way pgpool works. Again, pgpool has the correct setup. 

If I wanted to change the hba in this situation where an how should I change either a values file and or use a script? 

I believe this is related to the closed issue here. 

https://github.com/bitnami/charts/issues/14190

### Are you using any custom parameters or values?

This but had to remove. 

``pgHbaConfiguration: ""``

### What is the expected behavior?

To create a custom pg server hba conf without fail. 

### What do you see instead?

A failing build

### Additional information

Perhaps if I understood how it is working better from the pgpool to the pgserver it may be sufficient enough to only worry about the PGPool here. 

Any help would be appreciated.

**Comment by FraPazGal** [comment]
Hi @xtianus79, it seems this could be an old issue from our chart. Could you share any custom TLS configuration and how you defined the value at `pgHbaConfiguration`? That would help us better reproduce this issue and create an internal task if necessary.
