### ISSUE TITLE
[bitnami/elasticsearch] Anonymous User access enabling.

### ISSUE THREAD

**Issue by naasir-ansar** [bitnami/charts#21495]
### Name and Version

bitnami/elasticsearch

### What is the problem this feature will solve?

https://www.elastic.co/guide/en/elasticsearch/reference/current/anonymous-access.html

Elasticsearch natively supports with anonymous access with minimal configurations on their elasticsearch.yml & kibana.yml configurations.
This give a lot flexibility towards customers to use it.
It would be very effective this can we configured through helm chart itself.

### What is the feature you are proposing to solve the problem?

Anonymous user configuration through helm chart.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by naasir-ansar** [comment]
Hi @carrodher,
Can you please confirm that anonymous user access is not supported through available chart ?
Or If we have any other way to implement it.
please let me know.

**Comment by jotamartos** [comment]
Hi @naasir-ansar,

Sorry for the delay in getting back to you. As the documentation describes, this feature is not enabled by default 

>By default, anonymous requests are rejected and an authentication error is returned (status code 401).

Allowing anonymous access will require to update the container configuration and set the "xpack.security.authc" parameter as explained in the documentation. It will require to create a new env var (ELASTICSEARCH_ENABLE_ANONYMOUS_ACCESS for example) that adds the required configuration in the conf file. For example, you can see an example of how to modify the configuration [here](https://github.com/bitnami/containers/blob/main/bitnami/elasticsearch/8/debian-11/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L736). Once you create the PR, the team will be more than happy to review it. 

Thanks
