### ISSUE TITLE
init-chmod-data initContainer does not create directories

### ISSUE THREAD

**Issue by sergevs** [bitnami/charts#2150]
**Which chart**:
influxdb 0.4.3

**Describe the bug**
init-chmod-data initContainer does not create required directories and therefore can't set permissions

**To Reproduce**
1. set  volumePermissions.enabled: true
2. inspect persistent volume and find that  {data,meta,wal} directory is created instead of 3 separate directories data , meta and wal
3. container does not start because there is no write permissions for influxdb

**Expected behavior**
Required directories with correct permissions created

**Additional context**
sh does not have curly braces bash expansion. the issue can be fixed in the following ways:
- use bash interpreter for initContainer
or
- provide all 3 full path directories to mkdir command

**Comment by Mauraza** [comment]
Hello @sergevs,

I run `helm install my-release bitnami/influxdb --set-string volumePermissions.enabled=true` and the pod started perfectly and the persistent volume look:
```
drwxrwxrwx 6 root     root 4096 Mar 27 14:22 .
drwxr-xr-x 3 root     root 4096 Mar 19 09:59 ..
drwxr-xr-x 3 influxdb root 4096 Mar 27 14:22 data
drwxr-xr-x 2 influxdb root 4096 Mar 27 14:22 meta
drwx------ 3 influxdb root 4096 Mar 27 14:22 wal
drwxr-xr-x 2 influxdb 1001 4096 Mar 27 14:21 {data,meta,wal}
```
Set the value to a true or false or any reserved word , you need to use `--set-string` instead only `--set `.

I hope that helps you.

**Comment by sergevs** [comment]
notice {data,meta,wal} directory and it's permissions which is created by initContainer.
your setup works  because actually  data, meta & wal directories got already assigned  permissions - not by initContainer and actually in your setup it will work fine without 
volumePermissions.enabled option

**Comment by Mauraza** [comment]
Could you tell me your setup and I try to help you with that? or if my setup It's valid to you, please close the issue

**Comment by sergevs** [comment]
Volume permissions management depends on kubernetes setup.
If you wish - you can setup rancher kubernetes cluster (https://rancher.com/) on bare bones servers and use local storage volume provisioning.
Alternatively I would suggest to read the code at  https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/influxdb/deployment-standalone.yaml
```
 65:      command:
 66:          - sh
 67:           - -c
 68:           - |
 69:             mkdir -p /bitnami/influxdb/{data,meta,wal}
```
Do you think that _mkdir_ command at line 69 is correct ?
Also please see *Additional context* in the ticket description.

**Comment by Mauraza** [comment]
Hi @sergevs, 

We're going to make some changes to fix this. I'll update this thread when you're done.

**Comment by Mauraza** [comment]
Hi @sergevs,

we just update the chart of Influxdb (`version of chart 0.4.4`), please check if the problem it's fixed
