### ISSUE TITLE
nodePort: null -> Incorrect type. Expected "integer".

### ISSUE THREAD

**Issue by ThePlenkov** [bitnami/charts#21501]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi!

We're building application.yaml using `helm template rabbitmq`

In the generated file I see that `nodePort: null` is not a valid value according to the schema kubernetes://schema/io.k8s.api.core.v1.serviceport 

Ideally, I prefer that the generated yaml file should be a valid one. Maybe this is an issue not related to the schema itself.  Luckily it doesn't impact the runtime behavior anyhow. But the point is - when I remove `nodePort: null` from the file - the service keeps working identically. Is it needed?

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/6381507/691a910d-82d1-4935-800f-bc698c79a9f5)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by carrodher** [comment]
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
