### ISSUE TITLE
[etcd] Allow Configuration of ServiceAccount for CronJob Pods

### ISSUE THREAD

**Issue by hndoss** [bitnami/charts#21509]
### Name and Version

etcd/9.6.2

### What is the problem this feature will solve?

There is no direct configuration option to specify the serviceAccountName for the pods created by the CronJob when disaster recovery is enabled. This limitation hinders users from customizing the ServiceAccount associated with the pods, limiting their ability to control permissions and access for the CronJob.

### What is the feature you are proposing to solve the problem?

A key addition, a parameter, for example, disasterRecovery.cronjob.serviceAccountName, within the Helm chart's values

### What alternatives have you considered?

-

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
