### ISSUE TITLE
[bitnami/grafana-operator] resource mapping not found for name: "grafana-grafana-operator-grafana" namespace: "monitoring" from "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1" │ ensure CRDs are installed first

### ISSUE THREAD

**Issue by epneo-banuprakash** [bitnami/charts#21521]
### Name and Version

bitnami/grafana-opreator

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to update bitnami/grafana-operator from version 2.9.3 to 3.0.1 through the terraform script, but I got the error `resource mapping not found for name: "grafana-grafana-operator-grafana" namespace: "monitoring" from "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1"
│ ensure CRDs are installed first`

I tried a lower version i.e. 3.0.0 still facing this `Error: YAML parse error on grafana-operator/templates/grafana.yaml: error converting YAML to JSON: yaml: line 54: did not find expected key`

And also tried migration of api, but I didn't successful, anyone in the universe tell me how to upgrade this..??

### Are you using any custom parameters or values?

customized 

### What is the expected behavior?

Upgrade successful

### What do you see instead?
```
resource mapping not found for name: "grafana-grafana-operator-grafana" namespace: "monitoring" from "": no matches for kind "Grafana" in version "grafana.integreatly.org/v1beta1"
│ ensure CRDs are installed first
```
### Additional information

Platform: Azure k8s version 1.25.3
Current version: bitnami/grafana-operator version-2.9.3
Facing issue: migration failed to 3.0.0

**Comment by javsalgar** [comment]
Hi,

I'm not sure how the terraform provider for helm is working, but the chart is including the CRDs and via helm install it will deploy them first and then the rest of the objects. Did you try running it with regular helm install? Maybe it's something to be reported to the upstream terraform provider devs.

**Comment by epneo-banuprakash** [comment]
<img width="972" alt="image" src="https://github.com/bitnami/charts/assets/89842780/c770c411-cba7-4797-8f8e-a5800f4c2e1d">
Yes I tried to update manually but same error, in both scenarios ,

<img width="867" alt="image" src="https://github.com/bitnami/charts/assets/89842780/88e19168-c240-4d41-bd41-7f92cb01ff37">

**Comment by javsalgar** [comment]
Did you try manually deploying the CRDs of the new version? Note that helm does not update the CRDs automatically (this is by design) and need to be manually updated.

**Comment by epneo-banuprakash** [comment]
Please let me know how can I update the CRDs manually for this particular chart bitnami/grafana-operator for version 2.9.3.
Thanks in advance..

**Comment by javsalgar** [comment]
Hi,

You will need to run kubectl apply with the crds YAML files in this path https://github.com/bitnami/charts/tree/main/bitnami/grafana-operator/crds

**Comment by epneo-banuprakash** [comment]
Hi,

I tried to apply as u mentioned above but i am getting this error now,
<img width="956" alt="image" src="https://github.com/bitnami/charts/assets/89842780/50cb04a4-1ee5-4255-a5e9-09b46cf661b5">

Below CRDs are installed one year ago 
<img width="492" alt="image" src="https://github.com/bitnami/charts/assets/89842780/e6aaf1ac-2f5f-4430-86e9-fdc5089e3f07">


what should I do now??

**Comment by javsalgar** [comment]
Hi, The issue is that you are using the incorrect URL, as that one includes GIthub HTML. You would need to get the Raw file (there's a button that you can click in the Github UI)

**Comment by epneo-banuprakash** [comment]
Hi,
Thanks for the above clarification , I have done installation of CRDs manually and then tried to upgrade but now getting the below errors,

["Error: UPGRADE FAILED: failed to create resource: Grafana.grafana.integreatly.org "grafana-grafana-operator-grafana" is invalid: [spec.config.smtp.enabled: Invalid value: "boolean": spec.config.smtp.enabled in body must be of type string: "boolean", spec.config.alerting.enabled: Invalid value: "boolean": spec.config.alerting.enabled in body must be of type string: "boolean", spec.config.analytics.check_for_updates: Invalid value: "boolean": spec.config.analytics.check_for_updates in body must be of type string: "boolean", spec.config.analytics.reporting_enabled: Invalid value: "boolean": spec.config.analytics.reporting_enabled in body must be of type string: "boolean", spec.config.security.disable_gravatar: Invalid value: "boolean": spec.config.security.disable_gravatar in body must be of type string: "boolean"]"]

So I have looked into it "https://github.com/bitnami/charts/issues/17554" is everything updated in CRDs, now??,why this is still not working.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
