### ISSUE TITLE
[bitnami/rabbitmq] Add community plugin download via init-container

### ISSUE THREAD

**Issue by bjoernw** [bitnami/charts#2154]
**Which chart**:
rabbitmq

I would like to be able to specify the location of community plugins I want to use, have an init container download them, and drop them in the right directory. Happy to help add this if this is something you're interested in.

**Comment by carrodher** [comment]
Hi,

currently, you can use the `extraPlugins` parameter to enable already bundled plugins. To download 3rd-party plugins there is needed to implement a solution like the one you're proposing.

In fact, we already have this feature implemented in other charts like Kibana. We're happy to accept contributions and review your PR if you think it is something you can contribute.

I will point you to some Kibana references that I think can be useful:
- https://github.com/bitnami/charts/tree/master/bitnami/kibana#installing-plugins
- https://github.com/bitnami/charts/blob/e07d9d96e8c6677051841ea169c72c044c3c2d67/bitnami/kibana/values.yaml#L58
- https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/plugins-configmap.yml
- https://github.com/bitnami/charts/blob/e07d9d96e8c6677051841ea169c72c044c3c2d67/bitnami/kibana/templates/deployment.yaml#L107
- https://github.com/bitnami/charts/blob/e07d9d96e8c6677051841ea169c72c044c3c2d67/bitnami/kibana/templates/deployment.yaml#L150
