### ISSUE TITLE
[bitnami/prometheus-operator] Kafka service monitor and JMX exporters not showing as active targets

### ISSUE THREAD

**Issue by victoryNap** [bitnami/charts#2155]
**Charts**:
Prometheus-operator:0.13.8
Kafka:9.0.0

I'm running into the same issues that the guys on this issue:
https://github.com/bitnami/charts/issues/1197
Its closed, so I'll open a new one for tracking.

Running on GKE, I've installed kafka with the following configuration:
```
metrics:
  jmx:
    enabled: true
  kafka:
    enabled: true
  serviceMonitor:
    enabled: true
```
And prometheus with the default configuration, in the monitoring namespace.

I can get to the jmx (for each kafka instance) and serviceMonitor output on 5556 and 9308.

While the services appear in prometheus, they dont appear as active targets, which means no stats come through :(

<img width="391" alt="Screen Shot 2020-03-28 at 5 55 31 PM" src="https://user-images.githubusercontent.com/1377320/77835707-54dd4900-711d-11ea-89d4-e8c98524106a.png">

The nodes are showing up as 'discovered lables' as well:
<img width="555" alt="Screen Shot 2020-03-28 at 6 26 57 PM" src="https://user-images.githubusercontent.com/1377320/77836168-e9e24100-7121-11ea-9bbe-d63865e76061.png">

Is there any way to manually add them through a config map?

**Expected behavior**
I'd expect the export nodes to show up as active targets.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by juan131** [comment]
Hi @victoryNap 

This should have been fixed at https://github.com/bitnami/charts/pull/2145
Please check latest version and let us know if that PR solved the issue for you

**Comment by victoryNap** [comment]
Yea...you were 100% correct. I was using 9.0.0, and it was added to the 9.0.3 release.

Sorry for the noise!
