### ISSUE TITLE
Helm - PostgreSQL | How to enable pgrouting extension?

### ISSUE THREAD

**Issue by darren-rose** [bitnami/charts#21554]
### Name and Version

bitnamicharts/postgresql

### What is the problem this feature will solve?

adding pgrouting

### What is the feature you are proposing to solve the problem?

adding pgrouting

### What alternatives have you considered?

volume mounts

**Comment by Mauraza** [comment]
Hi @darren-rose,

This is not included by default in the bitnami/chart. If you want to be included, you can create a script or something similar following the instruction of pgrouting.
