### ISSUE TITLE
[bitnami/thanos] Make it possible for runbook_url to be overriden

### ISSUE THREAD

**Issue by kaiohenricunha** [bitnami/charts#21568]
### Name and Version

12.6.1

### What is the problem this feature will solve?

Current runbooks don't provide valuable instructions on how to mitigate alerts. Plus, they cannot be changed because they are hard-coded:

https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/alert-rule/receive.yml#L33

### What is the feature you are proposing to solve the problem?

Make it possible for URLs to be overriden or something like the kube-prometheus-stack does:

```yaml
  ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
  runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward it to the engineering team. If you want to speed up the process, would you like to submit a PR?

**Comment by kaiohenricunha** [comment]
> Hi!
> 
> Thank you so much for the feature request! I will forward it to the engineering team. If you want to speed up the process, would you like to submit a PR?

We're in a bit of a hurry, but I'll try.
