### ISSUE TITLE
bitnami/kafka  sed: -e expression #1, char 190: unterminated `s' command

### ISSUE THREAD

**Issue by Sunshine-JamesHu** [bitnami/charts#2157]
**Which chart**:
bitnami/kafka 9.0.4

**Describe the bug**
This error log in kafka pod
INFO ==> ** Starting Kafka setup **
WARN ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
INFO ==> Initializing Kafka...
INFO ==> No injected configuration files found, creating default config files
sed: -e expression #1, char 190: unterminated `s' command

**To Reproduce**
use default values.yaml and change

externalAccess.enabled=true
externalAccess.service.type=NodePort
externalAccess.autoDiscovery.enabled=true
serviceAccount.create=true
rbac.create=true

after start app.

**Comment by juan131** [comment]
Hi @Sunshine-JamesHu 

I was unable to reproduce that issue:

```console
$ cat > values.yaml << 'EOF'
externalAccess:
  enabled: true
externalAccess:
  service:
    type: NodePort
  autoDiscovery:
    enabled: true
serviceAccount:
  create: true
rbac:
  create: true
$ helm install -f values.yaml kafka bitnami/kafka
(...)
$ kubectl get pods
NAME                READY   STATUS    RESTARTS   AGE
kafka-0             1/1     Running   0          4m11s
kafka-zookeeper-0   1/1     Running   0          4m11s
```

Did you change any other parameter? That error looks like sth wrong while setting some Kafka parameter. See:

- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L25
- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/prebuildfs/opt/bitnami/scripts/libfile.sh#L17

**Comment by kebyn** [comment]
I encountered the same problem.
```
$ helm get values kafka -n kafka
USER-SUPPLIED VALUES:
externalAccess:
  autoDiscovery:
    enabled: true
  enabled: true
  service:
    type: NodePort
persistence:
  enabled: false
rbac:
  create: true
replicaCount: 3
serviceAccount:
  create: true
zookeeper:
  persistence:
    enabled: false
```
```
$ kubectl logs  -n kafka pod/kafka-0
 11:21:46.30
 11:21:46.31 Welcome to the Bitnami kafka container
 11:21:46.31 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 11:21:46.32 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 11:21:46.32 Send us your feedback at containers@bitnami.com
 11:21:46.32
 11:21:46.32 INFO  ==> ** Starting Kafka setup **
 11:21:46.36 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
 11:21:46.37 INFO  ==> Initializing Kafka...
 11:21:46.37 INFO  ==> No injected configuration files found, creating default config files
sed: -e expression #1, char 178: unterminated `s' command
```

**Comment by juan131** [comment]
Hi everyone,

I was able to reproduce the issue using `externalAccess.service.type=NodePort`.

I also created a PR to address this issue.

**Comment by JavadHosseini** [comment]
I have the same problem. My image version  is bitnami/kafka:3.3.1-debian-11-r22. I install helm chart version 20.0.1.

**Comment by badihi** [comment]
After almost 4 years, having the same issue with bitnami/kafka:3.6.1-debian-12-r12!
