### ISSUE TITLE
Redis Helm chart runAsUser parameter cannot be changed/removed

### ISSUE THREAD

**Issue by egenillo** [bitnami/charts#21572]
### Name and Version

bitnami/redis 18.5.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Helmchart is adding `runAsUser: 1001` when containerSecurityContext is enabled. This is a problem because there is no way to remove that value due the following bug in helm: https://github.com/helm/helm/issues/12637. This has been an ongoing problem in helm for several years.
 
Problem with runAsUser having a value is that this make the chart not compatible between k8s & Openshift with the default values.

### What do you see instead?

Errors on Redis pods deployed in OCP  like ..."it would violate PodSecurity "

**Comment by opencmit2** [comment]
Hi @egenillo 
I hope you can provide more useful information. Can't delete runAsUser: 1001? I tested that it can be deleted.
![image](https://github.com/bitnami/charts/assets/112474703/7e298998-0b92-42f7-8a9c-84b9c4663c3a)

**Comment by egenillo** [comment]
If you set --set redis.master.containerSecurityContext.runAsUser=null  the parameter runAsUser is not included in helm chart
Closing
