### ISSUE TITLE
[bitnami/redis] Allow to set service loadBalancerClass in redis chart

### ISSUE THREAD

**Issue by outductor** [bitnami/charts#21584]
### Name and Version

bitnami/redis 18.5.0

### What is the problem this feature will solve?

Allow to set service loadBalancerClass in redis chart

### What is the feature you are proposing to solve the problem?

Allow to set service loadBalancerClass in `redis` chart
See https://github.com/bitnami/charts/issues/19421 for the same for `kube-prometheus`

**Comment by opencmit2** [comment]
Hi @javsalgar 
I can give it a try.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
