### ISSUE TITLE
[bitnami/kafka] kafka-manager can't read information regarding of JMX 

### ISSUE THREAD

**Issue by tom1005** [bitnami/charts#2160]
Hi.

I'm using kafka via bitnami helm chart.
In addtional, I'm using kafka-manager.(not bitnami chart)

But, kafka-manager can't read information regarding of JMX.
I thinks that JXM PORT didn't expose service.

```
> kubectl get service 
test-kafka                              ClusterIP      172.21.113.222   <none>          9092/TCP
test-kafka-headless                     ClusterIP      None             <none>          9092/TCP
````

I wanna kafka-manager can read information regarding of JMX in kafka via bitnami helm chart.

Please let me know this question.

Thanks.

**Comment by juan131** [comment]
Hi @tom1005 

Did you enable the JMX metrics exporter? Please note that you need to 

```yaml
metrics:
  jmx:
    enabled: true
```

Check https://github.com/bitnami/charts/tree/master/bitnami/kafka#metrics-parameters for more information.

**Comment by tom1005** [comment]
Hi @juan131

thanks for help :)

It work well.
