### ISSUE TITLE
binami Odoo Image and multi company domains with single database

### ISSUE THREAD

**Issue by etomProductions** [bitnami/charts#21603]
### Name and Version

bitnami/odoo

### What is the problem this feature will solve?

I have one data base of Odoo 16 with multi-company.
each company has its own domain www.domain-1.com and www.domain-2.com.

Both domains when I try to reach foreword to www.domain-1.com 

### What is the feature you are proposing to solve the problem?

I need to know how to set the virtual host to match Odoo requirements.
Each company domain must point to the website inside odoo. I had it in the version before the current one in bitnami also

### What alternatives have you considered?

I tried to add vertuail host for each domain.
I checked every single documents in both Odoo and bitnami :( but no luck

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
