### ISSUE TITLE
postgresql-ha deleting primary node causes two nodes to become primary

### ISSUE THREAD

**Issue by danielgoepp** [bitnami/charts#21614]
### Name and Version

bitnami/postgresql-ha-12.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Boot a new cluster using default settings, 3 replicas
2. Delete primary node

### Are you using any custom parameters or values?

Not really. I set timezone, a password and pullPolicy, but nothing that I could think would affect this behavior.

### What is the expected behavior?

I would expect that when `-0` is deleted, `-1` takes over as primary (which it does seem to). Then when `-0` comes back online, it come back as a standby, as there has already been a node promoted to primary (`-1`). If there is logic / control to get it back in sync and re-promote it, great, but not until that has happened. Also when it does happen it needs to do it in a way that `-1` and Pgpool are able to handle.

### What do you see instead?

`-1` becomes primary, then when `-0` comes back online, it also thinks it is primary still.

```
 ID | Name                                        | Role    | Status               | Upstream                              | repmgrd | PID | Paused? | Upstream last seen
----+---------------------------------------------+---------+----------------------+---------------------------------------+---------+-----+---------+--------------------
 1000 | postgres-postgresql-ha-postgresql-0         | primary | * running            |                                       | running | 1   | no      | n/a
 1001 | postgres-postgresql-ha-postgresql-1         | standby | ! running as primary |                                       | running | 1   | no      | n/a
 1002 | postgres-postgresql-ha-postgresql-2         | standby |   running            | ! postgres-postgresql-ha-postgresql-1 | running | 1   | no      | 0 second(s) ago
```

### Additional information

This is a follow up to https://github.com/bitnami/charts/issues/10821

There was a request there to create a new bug since that issue was getting long and appeared to be about two different things. I can't confirm the Pgpool behavior yet, until I can get the nodes themselves to behave correctly.

**Comment by juan131** [comment]
Hi @danielgoepp 

I think the issue described in the link below describes exactly the same "split brain" problem:

- https://github.com/bitnami/charts/issues/20998

Please take a look and close the issue in favor of that one if you consider it's the same topic.

> My apologizes for asking you to create this issue (given the original one was initially related to Istio) 🙏🏼

**Comment by danielgoepp** [comment]
@juan131 I can see that issue might or might not have the same root cause, not sure. They could be completely different problems, manifesting a very similar behavior. That issue is far more raw and tons of details. I think this example is super clean and easy to reproduce. Also, that is bitnami/postgresql-repmgr where as this one is bitnami/postgresql-ha. I mean, if you want to close this, sure. But honestly I can't even tell what is happening in that other issue. Do you know if anyone has even tried to reproduce this by simply booting a clean cluster and restarting the primary? I'm happy to help provide any further details too if it helps.

**Comment by danielgoepp** [comment]
Sure, I will close this out then and watch that other one. If you think they are the same, you know better than me :) Thanks.
