### ISSUE TITLE
phpmyadmin needs initialDelaySeconds for livenessProbe

### ISSUE THREAD

**Issue by puckpuck** [bitnami/charts#2161]
**Which chart**:
phpmyadmin

**Describe the bug**
CrashLoopBackOff from main deployment, caused by the livenessProbe failing on default settings.  The pod takes about 45-50s before it is ready to serve in my environment (node is a beefy VM on a PowerEdge R420).

**To Reproduce**
Deploy the phpmyadmin chart on slower hardware

**Expected behavior**
It works properly on slower hardware.

**Additional context**
I manually added
`initialDelaySeconds: 60`
to the livenessProbe on the deployment and everything was fine.  I'm not sure if this should be a hard coded setting or set in values.

**Comment by juan131** [comment]
Hi @puckpuck 

You're totally right. We should have parameters to modify the liveness probes (as we have for most charts). I created a PR so you can in the future use the `livenessProbe` and `readinessProbe` parameters to customize the probes.
