### ISSUE TITLE
[bitnami/rabbitmq] Incorrect log level in Google Logs Explorer

### ISSUE THREAD

**Issue by vparmeland** [bitnami/charts#21620]
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using this helm -> https://artifacthub.io/packages/helm/bitnami/rabbitmq/ 
All the k8s container execution logs are send to gcp, but there is an issue while interpreting logs

### Are you using any custom parameters or values?

https://artifacthub.io/packages/helm/bitnami/rabbitmq/ 
HELM values 

```yaml
rabbitmq:
  auth:
    .......
  extraConfiguration: |-
    load_definitions = /app/load_definition.json
    log.file.formatter = json
    log.console.formatter = json
    log.syslog.formatter = json
```

### What do you see instead?

Log are flagged as "ERROR" 
<img width="1222" alt="image" src="https://github.com/bitnami/charts/assets/17825769/14c78d54-4348-44b2-b8fc-9403e80258a7">
It works as expected when i check the logs on kuctl
<img width="1135" alt="image" src="https://github.com/bitnami/charts/assets/17825769/6e1d5792-e49a-402a-ba62-9397b0446e19">

```
ERROR 2023-12-18T09:04:21.352817583Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.35 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ setup **
ERROR 2023-12-18T09:04:21.373167390Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.37 [0m[38;5;2mINFO [0m ==> Validating settings in RABBITMQ_* env vars..
ERROR 2023-12-18T09:04:21.458813468Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.45 [0m[38;5;3mWARN [0m ==> A definition file with "users" was found. The RABBITMQ_SECURE_PASSWORD environment variables will be ignored.
ERROR 2023-12-18T09:04:21.470737073Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.47 [0m[38;5;2mINFO [0m ==> Initializing RabbitMQ...
ERROR 2023-12-18T09:04:21.655714550Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.65 [0m[38;5;2mINFO [0m ==> Persisted data detected. Restoring...
ERROR 2023-12-18T09:04:21.662306660Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.66 [0m[38;5;2mINFO [0m ==> No custom scripts in /docker-entrypoint-initdb.d
ERROR 2023-12-18T09:04:21.666089163Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.66 [0m[38;5;2mINFO [0m ==> ** RabbitMQ setup finished! **
ERROR 2023-12-18T09:04:21.758713066Z [resource.labels.containerName: rabbitmq] [38;5;6mrabbitmq [38;5;5m09:04:21.75 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ **

```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
