### ISSUE TITLE
[bitnami/mysql]Can't access to mysql nodeport

### ISSUE THREAD

**Issue by lijian12345** [bitnami/charts#21647]
### Name and Version

bitnami/mysql 9.15.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm deploy mysql
```bash
helm install mysql bitnami/mysql --version 9.15.0 \
--set auth.rootPassword=root \
--set primary.service.type=NodePort \
--set primary.service.nodePorts.mysql=32000
```
2. connect to mysql
```bash
mysql -hlocalhost -P32000 -uroot -p
```
3. then the mysql client stucks, with no response 

### What do you see instead?

the mysql client stucks, with no response

**Comment by carrodher** [comment]
Can you check the installation notes with [`helm get notes`](https://helm.sh/docs/helm/helm_get_notes/)? Are you able to connect to the database using those instructions?

**Comment by lijian12345** [comment]
> Can you check the installation notes with [`helm get notes`](https://helm.sh/docs/helm/helm_get_notes/)? Are you able to connect to the database using those instructions?

After `helm get notes mysql`, I got this response:
```
NOTES:
CHART NAME: mysql
CHART VERSION: 9.15.0
APP VERSION: 8.0.35

** Please be patient while the chart is being deployed **

Tip:

  Watch the deployment status using the command: kubectl get pods -w --namespace default

Services:

  echo Primary: mysql.default.svc.cluster.local:3306

Execute the following to get the administrator credentials:

  echo Username: root
  MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace default mysql -o jsonpath="{.data.mysql-root-password}" | base64 -d)

To connect to your database:

  1. Run a pod that you can use as a client:

      kubectl run mysql-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mysql:8.0.35-debian-11-r0 --namespace default --env MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD --command -- bash

  2. To connect to primary service (read/write):

      mysql -h mysql.default.svc.cluster.local -uroot -p"$MYSQL_ROOT_PASSWORD"
```

Yeah, it looks like the commands used in k8s cluster. But when I set it as a NodePort, shouldn't I have direct access to it in Windows Host?

**Comment by carrodher** [comment]
If set to a different service type, the instructions should be different and rendered in that way
