### ISSUE TITLE
[external-dns] 'pihole' is now a supported provider as of 0.13.2, but lacks a configuration section in helm chart

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#21658]
### Name and Version

bitnami/external-dns:6.28.6

### What architecture are you using?

None

### What steps will reproduce the bug?

Unable to configure pihole server, pihole looks to be missing from the helm chart:
```
  provider: pihole
  pihole-server: http://pihole-web.pihole.svc.cluster.local
```

'pihole' has been a supported provider as of 0.13.2, see release notes:
https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.13.2

### Are you using any custom parameters or values?

Instructions how to deploy with raw yaml:
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md

### What is the expected behavior?

Configure with pihole via helm chart

### What do you see instead?

Unable to because there's no place to specify the pihole server

### Additional information

![image](https://github.com/bitnami/charts/assets/92187614/07af0e4c-3234-43e1-b8fd-89e6d875949d)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
