### ISSUE TITLE
Add new chart: Casdoor

### ISSUE THREAD

**Issue by sp71** [bitnami/charts#21660]
### Name and Version

Casdoor latest

### What is the problem this feature will solve?

**Feature Request**
- Add support for Casdoor [Helm Chart](https://github.com/casdoor/casdoor-helm)

### What is the feature you are proposing to solve the problem?

[Casdoor](https://casdoor.org/docs/overview/) is a UI-first [Identity Access Management (IAM)](https://en.wikipedia.org/wiki/Identity_management) / [Single-Sign-On (SSO)](https://en.wikipedia.org/wiki/Single_sign-on) platform based on OAuth 2.0, OIDC, SAML, and CAS.

**Comment by carrodher** [comment]
Thanks for your suggestion!

We will check it internally and evaluate the feasibility of adding this new product to the catalog; due to limited resources, this process could take some time. In the meantime and to prevent the stale bot from closing this issue, we will add the 'on-hold' label.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
