### ISSUE TITLE
[bitnami/contour] multiple envoy LoadBalancer services for multi-AZ deployments

### ISSUE THREAD

**Issue by 3deep5me** [bitnami/charts#21684]
### Name and Version

15.0.1

### What is the problem this feature will solve?

Some cloud-proivder does not support region-wide LoadBalancers only zone-wide LoadBalancers. 
Which lead to unavailable services if the zone with the LoadBalancer is not available. 

In the case you do only have a zone-wide LoadBalancer and want an HA deployment of the ingress-controller you have to deploy a LoadBalancer for every zone. Like [here (scaleway/nginx)](https://www.scaleway.com/en/docs/tutorials/k8s-kapsule-multi-az/#nginx-ingress-controller-as-a-stateless-multi-az-application) described.

In common you have to deploy a additional LoadBalancer-Services for every zone with an annotation like `load-balancer.hetzner.cloud/location: hel1` or `service.beta.kubernetes.io/scw-loadbalancer-zone: fr-par-1`. 

Then failover between the LoadBalancers (and so zones) is done over DNS-checking. 

Right now the solution would be the extraDeploy filed - i think.

### What is the feature you are proposing to solve the problem?

I am not that much aware about the internal structure of the Chart. But i could imagine a new field under `enovy.service` which name something like `replicas` and a list `replicas.separateAnnotations`.
Other suggestions are welcome.

### What alternatives have you considered?

using the extraDeploy field

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
