### ISSUE TITLE
[bitnami/mongo] updateStrategy deployment configuration

### ISSUE THREAD

**Issue by 4nte** [bitnami/charts#2169]
**Which chart**:
MongoDB chart

**Is your feature request related to a problem? Please describe.**
When upgrading a MongoDB chart, a rolling update is performed by default.
Rolling update fails if deployment is using a PVC that can be attached to only one pod at a time.
Because of this, the rolling update will hang forever since the new pod will never be able to attach to the PVC.

**Describe the solution you'd like**
Expose `updateStrategy` in chart values.

**Describe alternatives you've considered**
Deleting the helm release and installing it again.

**Additional context**
I've seen this solution has been chosen for some other charts in the Bitnami repo too.

**Comment by 4nte** [comment]
I'm happy to open a PR if you agree.

**Comment by beltran-rubo** [comment]
Thanks! That would be great, any contribution will be welcome.
