### ISSUE TITLE
[bitnami/kube-prometheus] Add priorityClassName to node-exporter 

### ISSUE THREAD

**Issue by felipewnp** [bitnami/charts#21701]
### Name and Version

bitnami/kube-prometheus 8.22.8

### What is the problem this feature will solve?

bitnami/kube-prometheus does not have priorityClassName parameter available for the node-exporter and has to be added manually inside the cluster, after the chart installation is complete.

### What is the feature you are proposing to solve the problem?

Adding a priorityClassName to node-exporter will eliminate the need to remember to manually change/add priorityClassName in the node-exporter daemonset. 

### What alternatives have you considered?

Adding manually priorityClassName to node-exporter daemonset.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by felipewnp** [comment]
@carrodher 

I discovered that the parameters of the bitnami/node-exporter chart work in the bitnami/kube-Prometheus chart if put inside/under `node-exporter: {}`

So I think the best way to deal with this is:
* In the `docs` and the `values.yaml` of the `bitnami/kube-prometheus` chart, mention that the parameters of the `node-exporter: {}` section are the same and available in the `bitnami/node-exporter` chart documentation.

What do you think?

**Comment by carrodher** [comment]
That's something inherited from Helm and works in that way for all Helm charts, not something specific for this Helm chart so it should be something documented in Helm itself since it is not related to this Helm chart at all. See https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
