### ISSUE TITLE
[HAProxy] add terminationGracePeriodSeconds on deployment

### ISSUE THREAD

**Issue by sebglon** [bitnami/charts#21702]
### Name and Version

bitnami/haproxy:0.5.5

### What is the problem this feature will solve?

We need to prevent long connection lost during gracefull shutdown.

### What is the feature you are proposing to solve the problem?

add terminationGracePeriodSeconds on helm values

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
