### ISSUE TITLE
[bitnami/minio] Configuration value metrics.serviceMonitor.namespace has no effect in 12.12.0

### ISSUE THREAD

**Issue by paulusasol** [bitnami/charts#21718]
### Name and Version

bitnami/minio 12.12.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the MinIO chart in Kubernetes with `metrics.serviceMonitor.enabled` set to `true`, `metrics.serviceMonitor.namespace` set to a namespace different from the one Kubernetes MinIO is running in and `metrics.prometheusOperator.namespace` unset.

Then the Service Monitor is created in the namespace MinIO is running in.

### Are you using any custom parameters or values?

```YAML
metrics:
      serviceMonitor:
        enabled: true
        namespace: "monitoring"
```
(and some more, not related to Metrics.

### What is the expected behavior?

The service monitor is created in the namespace specified using the configuration value `metrics.serviceMonitor.namespace`, as in older versions.

### What do you see instead?

The service monitor is created in the namespace MinIO is running in or the one configured by the `metrics.prometheusRule.namespace`.

### Additional information

https://github.com/bitnami/charts/blob/f449a44a1f3997829bf2e3d3105dec729a3f038f/bitnami/minio/templates/servicemonitor.yaml#L7 uses `metrics.prometheusRule.namespace`, whereas older versions used `metrics.serviceMonitor.namespace`, as per https://github.com/bitnami/charts/blob/94ed4f3e702aabb4cd30a9a83916900a4964c163/bitnami/minio/templates/servicemonitor.yaml#L11

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
