### ISSUE TITLE
[postgresql] Permission's error installing chart 8.6.3 and warning

### ISSUE THREAD

**Issue by mkanakis** [bitnami/charts#2171]
I am coping this over from [helm stable Charts](https://github.com/helm/charts/issues/21689).

Describe the bug
I have been using version 8.4.3 for a while now. Today I attempted to install 8.6.3 which led to a **chmod** permissions error.

After removing the chart and re-installing it with:

`volumePermissions: enabled: "true"`

It deployed successfully with an init Container as well but also gave the following warning:

```
postgresql 14:44:14.25 WARN ==> Data directory is set with a legacy value, adapting POSTGRESQL_DATA_DIR...
postgresql 14:44:14.25 WARN ==> POSTGRESQL_DATA_DIR set to "/var/lib/bitnami/postgresql/data"!!
```

I don't mind having an init container running, however I am worried to upgrade the rest of the containers due to this warning. Should I be worried upgrading from 8.4.3 to 8.6.3? Will this affect existing data somehow?

Version of Helm and Kubernetes:
Helm Version -> v2.14.3-rancher1
Kubernetes Version -> 1.17.4

Thanks.

Edit: fix styling

**Comment by Mauraza** [comment]
Hi @mkanakis.

only the path where PostgreSQL saves the data has been changed, anyway it is always advisable to make a copy of the data. Please check [https://github.com/bitnami/charts/tree/master/bitnami/postgresql#persistence]
(https://github.com/bitnami/charts/tree/master/bitnami/postgresql#persistence)

**Comment by mkanakis** [comment]
Thanks for the quick reply @Mauraza, 

Of course I will make a copy but I would prefer avoiding the hassle in the first place. 
In any case, existing data in the old path will remain there, I guess.

About the chmod error, do you know what changed and I have to spawn an initContainer now?

Best,
Marios.

**Comment by Mauraza** [comment]
Could you copy the error of chmod? please I need to know when it's happened and which is the folder.
