### ISSUE TITLE
[bitnami/spring-cloud-dataflow] MariaDB JDBC shouldn't have `useMysqlMetadata=true`

### ISSUE THREAD

**Issue by corneil** [bitnami/charts#21722]
### Name and Version

bitnami/spring-cloud-dataflow 26.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Default deployment with Rabbit and MariaDB.
Execute the following using SCDF Shell:

```
app register --uri docker:springcloudtask/timestamp-task:3.0.0 --name timestamp3 --bootVersion 3 --type task --force
task create --name ts-task3 --definition "timestamp3"
task launch --name ts-task3 --properties app.*.logging.level.root=debug
```

Dataflow will attempt to use a BOOT3_TASK_SEQ as a sequence table instead of a sequence.
Batch 5 tables is using sequences for MariaDB.

### Are you using any custom parameters or values?

Remove `useMysqlMetadata=true` from MariaDB JDBC URL for both Skipper and Dataflow.

### What is the expected behavior?

The task should launch and complete.

### What do you see instead?

Could not increment ID for BOOT3_TASK_SEQ sequence table; nested exception is java.sql.SQLSyntaxErrorException: (conn=20) Unknown column 'ID' in 'field list'

### Additional information

[Database JDBC URL Exmaples](https://docs.spring.io/spring-cloud-dataflow/docs/2.11.1/reference/htmlsingle/#configuration-local-rdbms)

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
