### ISSUE TITLE
[bitnami/postgresql-ha] backup

### ISSUE THREAD

**Issue by camaeel** [bitnami/charts#21741]
### Name and Version

bitnami/postgresql-ha

### What is the problem this feature will solve?

Lack of backup in chart

### What is the feature you are proposing to solve the problem?

Would be nice if this chart would also get backup feature, just as non-ha version did.

### What alternatives have you considered?

Postgresql operators, but seems an overkill if you have 1 or 2 db instances in a cluster.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by camaeel** [comment]
Seems it was implemented here: https://github.com/bitnami/charts/pull/20563
