### ISSUE TITLE
[bitnami/jupyterhub]cannot disable the xsrf check with configuration

### ISSUE THREAD

**Issue by zhhkof** [bitnami/charts#21764]
### Name and Version

bitnami/jupyterhub 5.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have installed bitnami/jupyterhub 5.0.0 by helm in my rancher cluster.  I'm try to embed the jupyterhub‘s page into my web by using iframe. The xsrf check Forbidden the login api，because of 'XSRF cookie does not match POST argument'.
I want to disable the xsrf check and have search the options from jupyterhub‘s document、other website, but it doesn't work.
so, I have to inquire about the correct configuration method here by creating a issue.

### Are you using any custom parameters or values?

I add some config in jupyterhub/templates/hub/configmap.yaml as following:
```yaml
data:
  jupyterhub_config.py: |
.........
    # csrf test config
    c.JupyterHub.disable_xsrf = True
    c.JupyterHub.disable_check_xsrf = True
    c.JupyterHub.tornado_settings = {'headers': { 'Content-Security-Policy': "frame-ancestors * 'self'} }
    c.JupyterHub.allow_origin = '*'
    c.JupyterHub.allow_remote_access = True

    c.LabApp.disable_check_xsrf = True
    c.NotebookApp.disable_xsrf = True
    c.NotebookApp.disable_check_xsrf = True
    c.NotebookApp.tornado_settings = {'headers': { 'Content-Security-Policy': "frame-ancestors * 'self'"} }
    c.NotebookApp.allow_origin = '*'
    c.NotebookApp.allow_remote_access = True

    c.ServerApp.disable_xsrf = True
    c.ServerApp.disable_check_xsrf = True
    c.ServerApp.tornado_settings = {'headers': { 'Content-Security-Policy': "frame-ancestors * 'self'" } }
    c.ServerApp.allow_origin = '*'
    c.ServerApp.allow_remote_access = True

    c.ConfigurableHTTPProxy.disable_xsrf = True
    c.ConfigurableHTTPProxy.disable_check_xsrf = True
    c.ConfigurableHTTPProxy.tornado_settings = {'headers': { 'Content-Security-Policy': "frame-ancestors * 'self'" } }
    c.ConfigurableHTTPProxy.allow_origin = '*'
    c.ConfigurableHTTPProxy.allow_remote_access = True
.....
```
### What is the expected behavior?

login successfully, and I can work with it.

### What do you see instead?

403 : Forbidden
XSRF cookie does not match POST argument

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by secrettoad** [comment]
Hi. This is actually a valid issue. There is no documented way to disable xsrf via jupyterhub config, even though it can be a super problematic feature. Can you please advise at the least as to whether or not an undocumented switch currently exists? If not, this is a valid and necessary feature request.

My use case for context: Using juypyterhub singleuser servers as remote development machines behind several other layers of secure proxy (making jupyter's security features unneccessary and so only using dummy auth)

**Comment by mfrancke** [comment]
@zhhkof I'm struggling with this too: did you ever solve you issue?

**Comment by zhhkof** [comment]
@mfrancke no.  but I deployed an nginx server with a reverse proxy configured.

**Comment by kevinevelasco** [comment]
> [@mfrancke](https://github.com/mfrancke) no. but I deployed an nginx server with a reverse proxy configured.

Do you have a sample code of this? I’m stuck here with this problem…:(
