### ISSUE TITLE
[bitnami/mariadb] Unable to upgrade without passing the rootPassword to values.yaml

### ISSUE THREAD

**Issue by MurzNN** [bitnami/charts#21765]
### Name and Version

bitnami/mariadb 14.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run `helm install mariadb oci://registry-1.docker.io/bitnamicharts/mariadb`
See that the chart is installed successfully, without specifying any passwords manually.
2. Run `helm upgrade mariadb oci://registry-1.docker.io/bitnamicharts/mariadb`
See an error:

> Error: UPGRADE FAILED: execution error at (mariadb/templates/NOTES.txt:73:6): 
> PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
>                  Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
>                  Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
> 
>     'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:
> 
>         export MARIADB_ROOT_PASSWORD=$(kubectl get secret mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)

### What is the expected behavior?

Upgrade should be applied without any errors

### What do you see instead?

I see the error that I should specify the root password. But this password is already specified in the Secret resource, and available for the chart and any pods inside it!

So, why the chart can't just get it from there to make the upgrade, to not ask to fill it explicitly?

### Additional information

And the same problem is with mysql and maybe other charts.

**Comment by carrodher** [comment]
That's expected. Since the password from the first deployment is stored in the volume and volumes are not recreated during upgrades, you need to follow those instructions to use the already set password.

**Comment by MurzNN** [comment]
But the password is already stored in the secret, why do I need to specify it as a plaintext in the `values.yaml` again? Why the chart can't just get it from the secret directly?

**Comment by juan131** [comment]
Hi @MurzNN 

We already have mechanisms in place to detect there's an existing secret and reuse its data thanks to the use of the `common.secrets.passwords.manage` helper, see:

- https://github.com/bitnami/charts/blob/main/bitnami/mariadb/templates/secrets.yaml#L8

You can reproduce it following these steps:

- Install the chart setting a custom password for `auth.rootPassword`:

```bash
helm install mariadb oci://registry-1.docker.io/bitnamicharts/mariadb \
  --set auth.rootPassword=some-secret-password \
  --version 14.1.4 
```

- Ensure the password has been properly set:

```console
$ kubectl get secret mariadb -o jsonpath='{.data.mariadb-root-password}' | base64 --decode
some-secret-password
```

- Upgrade the release without providing any password and double-check the secret data didn't change:

```console
$ helm upgrade mariadb oci://registry-1.docker.io/bitnamicharts/mariadb --version 14.1.4
Pulled: registry-1.docker.io/bitnamicharts/mariadb:14.1.4
Digest: sha256:e8997dd398073d025d5ab076b89ca16e3f2eb08ad4c13d5ddd49ad795fc74c32
Release "mariadb" has been upgraded. Happy Helming!
NAME: mariadb
(...)
$ kubectl get secret mariadb -o jsonpath='{.data.mariadb-root-password}' | base64 --decode
some-secret-password
```

**Comment by MurzNN** [comment]
Yeah, all works well, sorry for bothering! The problem was that the secret file was created after the helm upgrade happened, because of this it was not detected and asked to specify the rootPassword.
After fixing the pipeline - all starts working well!
