### ISSUE TITLE
[bitnami/gitea] add cache handling with redis

### ISSUE THREAD

**Issue by s83** [bitnami/charts#21779]
### Name and Version

bitnami/gitea 1.2.9

### What is the problem this feature will solve?

Add cache handling support to the chart 

### What is the feature you are proposing to solve the problem?

- cache handling can be done via redis-cluster or redis chart 
- disabled by default
- support external redis host, port, username, password etc..

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
