### ISSUE TITLE
[bitnami/nginx] HTML Structure Folde 

### ISSUE THREAD

**Issue by Mohamedmahrous995** [bitnami/charts#21776]
### Name and Version

nginx:2.13.3

### What is the problem this feature will solve?

I Have created this Path under templates
```
templates/pages/oidc/index.html
templates/pages/edp_ldap/index.html 
```
I need to create configmap  with two indexs.html files

### What is the feature you are proposing to solve the problem?
```yaml
index-oidc.html: |-
    {{ .Files.Get "templates/pages/oidc/index.html" | nindent 4 }}
  index-edp-ldap.html: |-
    {{ .Files.Get "templates/pages/edp_ldap/index.html" | nindent 4 }}
```
### What alternatives have you considered?

It doesn't work and gives me this error 
```
Error: INSTALLATION FAILED: YAML parse error on nginx/templates/pages/edp_ldap/index.html: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by OneCricketeer** [comment]
According to the Helm documentation, Files.Get cannot access files within the templates path

That folder is reserved for Kubernetes manifests anyway, not HTML files. Try with just a pages directory instead. Otherwise, create and mount a volume, rather than use a Configmap with Helm
