### ISSUE TITLE
Deploy Redis Cluster with redis-stack modules

### ISSUE THREAD

**Issue by krebznet** [bitnami/charts#21786]
### Name and Version

bitnami/redis--cluster/7.2.3

### What is the problem this feature will solve?

Hi I am sorry upfront if I am misunderstanding this, my use case is i have deployed redis-stack and redis-stack-server that load a set of modules including time series and other features, running a redis-stack helm chart i cannot cluster it and i am trying to figure out if its possible to deploy this redis-cluster helm chart with the modules that come with redis-stack

### What is the feature you are proposing to solve the problem?

Possibly update the redist-cluster helm chart to allow optional modules like time series to be installed on each cluster node. 

### What alternatives have you considered?

installing redis-cluster outside of kubernetes, breaking my large data set into multiple instances of redis-stack-server but these are not ideal. I am inserting around 300,000 key/values a second and on a single node it break.s.

**Comment by rafariossaa** [comment]
Hi,
  What we have packaged as container and chart is redis, not the redis-stack. I am not sure which `redis-stack` helm  chart are you using, could you provide a link ?

**Comment by svabra** [comment]
Please reopen. It is clearly the lightweight redis-stack-server image that should be used. https://hub.docker.com/r/redis/redis-stack-server

It does NOT include RedisInsight, which is the right choice when using it as a base for the bitnami deployment. However, using a Redis Custer without modules like Redis TimeSeries, Redis Search, RedisJSON makes little sense to me. At some point Devs want to use these features and then they are stuck with the limited Redis version. Please reopen the issue.

**Comment by rafariossaa** [comment]
Hi,
  I have registered the request in our internal system to by analyzed. However, this is not guaranteed that this would be implemented.
  Take into account that the redis-stack licensing is one of the point that have to be considered.
  We will come back if we have news.

**Comment by svabra** [comment]
Hi Rafa, I checked that before. No worries in this case. These are the 2 actions you are not allowed to perform according to the RSALv2 license.

```
- Commercialize the software or provide it to others as a managed service
- Remove or obscure any licensing, copyright, or other notices
```

 As long as you don't have it run as a service for others, that is fine. Wrapping it with a Operator is fine. Here is the link to the [RSALv2](https://redis.com/legal/licenses/?_gl=1*1id8cvj*_ga*MTYwMzYyOTc1Ni4xNzA0NjQ1ODUy*_ga_8BKGRQKRPV*MTcwNzMzNDA0Ny4xMS4wLjE3MDczMzQwNDkuNTguMC4w*_gcl_au*NDg5NTgzMzU3LjE3MDQ2NDU4NTI.&_ga=2.49185126.1140139326.1707334048-1603629756.1704645852)

**Comment by rafariossaa** [comment]
Thanks for coming back and sharing your findings.
