### ISSUE TITLE
[bitnami/mongodb] external-dns annotations for loadbalancer service replicas

### ISSUE THREAD

**Issue by jdurzi** [bitnami/charts#21789]
### Name and Version

bitnami/mongodb 14.4.9

### What is the problem this feature will solve?

When using [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) to automatically populate DNS records on a service of type LoadBalancer, it should be possible to have separate annotation values for each replica.

Since all replicas are generated from a loop in the same template file, perhaps it should be possible to template a hostname as well, with numbers or so, with support for external DNS.

### What is the feature you are proposing to solve the problem?

If using a service type LoadBalancer and multiple replicas, then multiple load balancers are created at different hostnames. If you want to use ExternalDNS to reference these, you need to use annotations to do so, for example: 

`external-dns.alpha.kubernetes.io/hostname: example.com`

It would be helpful if a base hostname could be used and then iterated upon since we can't use one hostname in route 53 for multiple loadbalancer hostnames. They need to be different, and annotations in plaintext do not support this - so they need some kind of templating.

### What alternatives have you considered?

Writing a Kyverno policy to discover and automatically annotate the existing services, but this feels a bit separated from the release itself.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
