### ISSUE TITLE
[question] pinniped-concierge, when run within vcluster, does not generate pinniped-concierge-concierge-kube-cert-agent deployment

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#21810]
### Name and Version

bitnami/pinniped:1.4.5

### What architecture are you using?

kubernetes v1.28.2
vcluster, latest helm chart: v0.18.1

### What steps will reproduce the bug?

1. deploy vcluster via loft helm chart
2. deploy pinniped-concierge using default values.yaml

### Are you using any custom parameters or values?

none

### What is the expected behavior?

normal pinniped deployment

### What do you see instead?

```console
$ k -n pinniped-concierge get all
NAME                                                READY   STATUS    RESTARTS   AGE
pod/pinniped-concierge-concierge-76d479b5c8-gqszb   1/1     Running   0          121m

NAME                                                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/pinniped-concierge-concierge-pinniped-concierge-api   ClusterIP   10.111.230.49   <none>        443/TCP   121m
service/pinniped-concierge-concierge                          ClusterIP   10.108.3.251    <none>        443/TCP   121m

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pinniped-concierge-concierge   1/1     1            1           121m

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/pinniped-concierge-concierge-76d479b5c8   1         1         1       121m
```

### Question
1. Where does the 'pinniped-concierge-concierge-kube-cert-agent' deployment come from?  (I don't see it in templates)
2. What is pinniped looking for that causes the 'pinniped-concierge-concierge-kube-cert-agent' deployment to appear?  (so that I can ensure those requirements are being met in the vcluster environment).

**Comment by joancafom** [comment]
Hi @lknite 

> Where does the 'pinniped-concierge-concierge-kube-cert-agent' deployment come from? (I don't see it in templates)

That deployment is not something explicitly provided by the chart (and as you rightly said, there is no template for it in the repository). Instead, the resource is created by the application itself. There are some details that can be configured though, and you can see we are specifying the name and the image to use in the same values.yaml file:

https://github.com/bitnami/charts/blob/308e0efeca7effff3b3441242f3ec06700d3ded1/bitnami/pinniped/values.yaml#L144-L146

You can also see the application creating the associated deployment if you inspect the logs of the `concierge` pod:

```console
$ k logs pinniped-concierge-785df44f89-tnwzz | grep "pinniped-concierge-kube-cert-agent"
{"level":"info","timestamp":"2024-01-09T12:45:03.491077Z","logger":"kube-cert-agent-controller","caller":"go.pinniped.dev/internal/controller/kubecertagent/kubecertagent.go:404$kubecertagent.(*agentController).createOrUpdateDeployment","message":"creating new deployment","deployment":{"name":"pinniped-concierge-kube-cert-agent","namespace":"default"},"templatePod":{"name":"kube-controller-manager-minikube","namespace":"kube-system"}}
...
```

> What is pinniped looking for that causes the 'pinniped-concierge-concierge-kube-cert-agent' deployment to appear? (so that I can ensure those requirements are being met in the vcluster environment).

Everything related to concierge configuration is under the `concierge` entry in the values.yaml section. I guess that if the deployment is not being created you should be able to obtain more details obtaining cluster events `kubectl get events` or inspecting the concierge pod logs (which is the one that creates this deployment).

**Comment by lknite** [comment]
Thank you, I'll dig in more with this information.
