### ISSUE TITLE
Very difficult to use

### ISSUE THREAD

**Issue by oomgomgxx** [bitnami/charts#21813]
### Name and Version

Very difficult to use

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Very difficult to use

### Are you using any custom parameters or values?

Very difficult to use

### What is the expected behavior?

Very difficult to use

### What do you see instead?

Very difficult to use

### Additional information

Very difficult to use

**Comment by carrodher** [comment]
Could you please provide more information about the specific Helm chart you're using and what are the issues you're facing?
