### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Update helm chart to add rabbitmq.erlangInetConfig: |

### ISSUE THREAD

**Issue by Vinaum8** [bitnami/charts#21823]
### Name and Version

rabbitmq-cluster-operator 3.10.7

### What is the problem this feature will solve?

I would like to request the operator's update to install another Rabbitmq Cluster Spec.

I installed via this link:
`KUBECTL APPLY -F "https://github.com/rabbitmq/cluster-opector/releases/last/download/clusion-opector.yml"`

And Custom Resource is changed:
`CustomResourcedefinition.apiextensions.k8s.io/rabbitmqclusters.rabbitmq.com`

When executing the command: `kubectl explain rmq.spec.rabbitmq`

We can observe the features:
```
Erlanginetconfig <string>
     ERLANG INET CONFIGURATION TO APPLY TO THE ERLANG VM RUNNING RABBIT. SEE
     Also: https://www.erlang.org/doc/apps/erts/inet_cfg.html
```

As I am using Helm Chart via Argocd, it soon removes this feature that was installed manually and ends up returning the following error:
```
STRECT DECODING ERROR: Unknown Field "Spec.rabbitmq.erlanginetconfig"
```
### What is the feature you are proposing to solve the problem?

We can observe the features: 
```
Erlanginetconfig <string>
     ERLANG INET CONFIGURATION TO APPLY TO THE ERLANG VM RUNNING RABBIT. SEE
     Also: https://www.erlang.org/doc/apps/erts/inet_cfg.html
```
### What alternatives have you considered?

install the custom resource via manifest and do not use helm chat.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Vinaum8** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

This would be my first opensource contribution and I still don't know where to start hahahahahah but I'll read the documentation and at least try :D

**Comment by Vinaum8** [comment]
Hi Folks!!

I create a fork of this repository and observe who: the @migruiz4 already create this feature! 😃 
in this PR: #22379 

and update from version 3.10.7 to 3.13.0 worked for me.

![image](https://github.com/bitnami/charts/assets/13757018/8e9ee7ab-dae3-471f-bafe-a225288a55b7)

Thanks @migruiz4 !!!
