### ISSUE TITLE
Option to integrate custom configurations when using 'coreNames' value to create custom cores

### ISSUE THREAD

**Issue by OriMeyuhas** [bitnami/charts#21832]
### Name and Version

bitnami/solr:8.3.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Set up the Bitnami Solr Helm chart with specific core names using the `coreNames` value.
2. Attempt to associate these custom cores with a set of custom configurations during the Helm chart deployment.

### Are you using any custom parameters or values?

```yaml
solr:
  auth:
    enabled: false
  replicaCount: 1

  zookeeper: 
    replicaCount: 1
  
  cloudEnabled: false

  cloudBootstrap: false
  collectionShards: 0
  collectionReplicas: 0
  
  coreNames:
    - "dev"
```

### What is the expected behavior?

The expected behavior is that when using the `coreNames` value to create custom cores with the Helm chart, there should be an option to seamlessly apply a complete set of custom configurations to these cores. Upon core creation, these configurations should be automatically and correctly associated with their respective cores, enabling each core to function with its unique settings. This feature would facilitate a more efficient and automated setup process for Solr cores, accommodating a wide range of custom configuration needs without the necessity for manual post-deployment adjustments

### What do you see instead?

In the current setup, when creating cores using the `coreNames` value, I am unable to directly associate these cores with a full set of custom configurations. Instead, the cores are initialized with default settings, requiring manual intervention to apply custom configurations post-deployment. This approach is time-consuming and less efficient, especially when dealing with multiple cores or frequent deployments. The lack of an integrated method for applying custom configurations during the initial core creation process limits the automation and flexibility of the setup.

### Additional information

I attempted to resolve the issue by creating a custom Docker image with an additional layer to copy the desired configuration files. However, this approach was unsuccessful. It seems that something within the Helm chart overrides and prevents these custom configurations from being applied as intended during the core creation process.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by OriMeyuhas** [comment]
Thank you for the invitation to contribute. Currently, I'm more in need of a solution or guidance for this issue. If there are any known workarounds or suggestions , that would be greatly appreciated. Thank you for your support.
@carrodher
