### ISSUE TITLE
[bitnami/airflow] Service type as LoadBalancer is not working for airflow chart

### ISSUE THREAD

**Issue by vinayakbhadage** [bitnami/charts#2183]
**Which chart**:
airflow chart

**Describe the bug**
Below command fails on AKS while using service.type as loadbalancer
 helm upgrade airflow azure-marketplace/airflow --set service.type=LoadBalancer,airflow.baseUrl=http://$APP_HOST:$APP_PORT,airflow.auth.password=$APP_PASSWORD,postgresql.postgresqlPassword=$APP_DATABASE_PASSWORD,redis.password=$APP_REDIS_PASSWORD --namespace bitnami

Error: UPGRADE FAILED: template: airflow/templates/NOTES.txt:62:12: executing "airflow/templates/NOTES.txt" at <eq .Values.servicePort "nodePort">: error calling eq: invalid type for comparison

**To Reproduce**
1. helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
2. helm install azure-marketplace/airflow
3. helm install airflow azure-marketplace/airflow --set service.type=LoadBalancer --namespace bitnami
4. export APP_HOST=$(kubectl get svc --namespace airflowns airflow --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
export APP_PORT=80
export APP_PASSWORD=$(kubectl get secret --namespace airflowns airflow -o jsonpath="{.data.airflow-password}" | base64 --decode)
export APP_DATABASE_PASSWORD=$(kubectl get secret --namespace airflowns airflow-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
export APP_REDIS_PASSWORD=$(kubectl get secret --namespace airflowns airflow-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
5. helm upgrade airflow azure-marketplace/airflow \
    --set service.type=LoadBalancer,airflow.baseUrl=http://$APP_HOST:$APP_PORT,airflow.auth.password=$APP_PASSWORD,postgresql.postgresqlPassword=$APP_DATABASE_PASSWORD,redis.password=$APP_REDIS_PASSWORD --namespace bitnami
**Expected behavior**
helm chart for airflow must be deployed
**Version of Helm and Kubernetes**:
Cluster version: 1.15.10

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by dani8art** [comment]
Hi @vinayakbhadage thank you for opening this issue, we found some errors in the `NOTE.txt` I will open a PR soon to fix them, in the meantime, you could use this workaround

```bash
helm upgrade airflow azure-marketplace/airflow  \
  --set servicePort="",service.type=LoadBalancer,airflow.baseUrl=http://$APP_HOST:$APP_PORT,airflow.auth.password=$APP_PASSWORD,postgresql.postgresqlPassword=$APP_DATABASE_PASSWORD,redis.password=$APP_REDIS_PASSWOR \
  --namespace bitnami
```

**Comment by vinayakbhadage** [comment]
thanks... this error is fixed but airflow not deployed successfully  giving postgress password mismatch error: 

>  FATAL:  password authentication failed for user "bn_airflow"
    Password does not match for user "bn_airflow".

**Comment by dani8art** [comment]
did you remove the PVC? helm doesn't remove it automatically. Also, you can try adding `""` to the values.

```
helm upgrade airflow azure-marketplace/airflow  \
  --set servicePort="",service.type=LoadBalancer,airflow.baseUrl=http://$APP_HOST:$APP_PORT,airflow.auth.password="$APP_PASSWORD",postgresql.postgresqlPassword="$APP_DATABASE_PASSWORD",redis.password="$APP_REDIS_PASSWORD" \
  --namespace bitnami
```
