### ISSUE TITLE
Solr pod not starting in IPv6 environment

### ISSUE THREAD

**Issue by mhenson1** [bitnami/charts#21844]
### Name and Version

bitnami/solr 8.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have an AWS EKS cluster setup to use IPv6 and I'm trying to install the Solr chart on it. If I use any of the Debian 12 or newer images for Solr then the Solr pod won't start. The log has this error and keeps restarting

Failed to connect to the zookeeper node at solr-zookeeper:2181

The Zookeeper pod starts fine. I've also noticed that if I install the chart using a Debian 11 image so the install is successful and then do a helm upgrade but switch to a Debian 12 image the upgrade will be successful and it won't complain about not being able to find zookeeper.

The rest of my pods for other applications install correctly and Solr also works if I make an EKS cluster with IPv4, it's just the IPv6 environment where it is an issue.

### Are you using any custom parameters or values?
```
helm install solr bitnami/solr -n default --wait --timeout 20m --set global.storageClass=nfs --set global.imageRegistry=<my AWS registry> --set replicaCount=1 --set collectionReplicas=1 --set collectionShards=1 --set zookeeper.replicaCount=1 --set resources.requests.memory=2Gi --set zookeeper.resources.requests.memory=2Gi --set auth.adminUsername=admin --set auth.adminPassword=Abcdef1!
```
### What is the expected behavior?

Solr and Zookeeper pods to both start and Helm install to complete when using an IPv6 network.

### What do you see instead?

The log from the Solr pod
```
solr 21:26:26.61
solr 21:26:26.61 Welcome to the Bitnami solr container
solr 21:26:26.61 Subscribe to project updates by watching https://github.com/bitnami/containers
solr 21:26:26.61 Submit issues and feature requests at https://github.com/bitnami/containers/issues
solr 21:26:26.62
solr 21:26:26.62 INFO  ==> ** Starting solr setup **
solr 21:26:26.63 INFO  ==> Validating settings in SOLR_* env vars...
solr 21:26:26.63 INFO  ==> Initializing Solr ...
solr 21:26:26.64 INFO  ==> Configuring file permissions for Solr
solr 21:26:26.64 INFO  ==> Deploying Solr Cloud from scratch
solr 21:26:26.64 INFO  ==> Waiting for Zookeeper to be up
solr 21:26:51.66 ERROR ==> Failed to connect to the zookeeper node at solr-zookeeper:2181
solr 21:26:51.66 ERROR ==> Zookeeper not detected
```
### Additional information

If I added this parameter to the chart, the install would complete
```
--set image.tag=9.3.0-debian-11-r69
```
If I added this one it would fail
```
--set image.tag=9.3.0-debian-12-r0
```

**Comment by carrodher** [comment]
The Bitnami Application Catalog (OpenSource) is built on Debian 11. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 10, 11 & 12, PhotonOS 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

There are plans to move the Bitnami Application Catalog to Debian 12, but it's not yet available, see https://github.com/bitnami/charts/issues/21362.
If you have any further questions, feel free to ask.
