### ISSUE TITLE
[bitnami/zookeeper] support persistence.existingClaim

### ISSUE THREAD

**Issue by horihel** [bitnami/charts#2185]
**Which chart**:
zookeeper 5.7.2

**Is your feature request related to a problem? Please describe.**
The kafka chart supports persistence.existingClaim as an option, but without zookeeper supporting the same option, it can't be deployed the same way. 

**Describe the solution you'd like**
Zookeeper could add the same mechanism (use an existing PersistentStorageClaim) with 'persistence.existingClaim') as the kafka chart does.

**Describe alternatives you've considered**
On a system that can't provide a StorageClass, zookeeper can only run with emptyDir storage (by setting persistence.enabled=false).

**Comment by miguelaeh** [comment]
Hi @horihel ,
Thank you very much for the suggestion, would you like to create a PR adding that feature? We will be very pleased to review it.

**Comment by horihel** [comment]
I did a bit of testing myself and at least for me it seems to work fine with 
- persistence.enabled=false
- persistence.enabled=true with default storageclass and 
- persistence.existingClaim

**Comment by miguelaeh** [comment]
Hi @horihel ,
thank you for the PR, let's continue the thread there, I have requested some changes.
