### ISSUE TITLE
[bitnami/external-dns] DNS Records persist after deleting services pods

### ISSUE THREAD

**Issue by srak** [bitnami/charts#21856]
### Name and Version

bitnami/external-dns 6.28.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm deploying external_DNS in an AWS EKS cluster to manage the application's DNS resolution.
1. I deploy game-2048 test application with the following annotation: 
```yaml
  annotations:
    external-dns.alpha.kubernetes.io/hostname: game-2048.sandbox3.example.com
```

2. The external_dns service creates the DNS records as expected
```
cname-game-2048.sandbox3.example.com | TXT | Simple | - | No | "heritage=external-dns,external-dns/owner=default,external-dns/resource=service/game-2048/service-2048" | 300 | - | - | -
game-2048.sandbox3.example.com | A | Simple | - | Yes | k8s-game2048-service2-1471255641-3e1f6jff17954z48.elb.us-west-2.amazonaws.com. | - | - | Yes | -
game-2048.sandbox3.example.com | TXT | Simple | - | No | "heritage=external-dns,external-dns/owner=default,external-dns/resource=service/game-2048/service-2048" | 300 | - | - | -
```

3. Delete the application in this case
```
kubectl delete -f game-2048.yaml
```

4. Check the resources in Route53; the three above resources are there.

5. if you redeploy the application, the k8x-game2048-service2.... is updated with the new resource.

6. Is this the expected behavior? Are the DNS Records expected to be preserved when the applications are removed, or did I miss some configuration somewhere?

### Are you using any custom parameters or values?

The configuration for external-DNS is managed with terraform.
```
resource "helm_release" "external_dns" {
  repository = "oci://registry-1.docker.io/bitnamicharts"
  name       = "external-dns"
  chart      = "external-dns"
  version    = "6.28.6"
  namespace  = "kube-system"

  set {
    name  = "provider"
    value = "aws"
  }

  set {
    name  = "aws.zoneType"
    value = "public"
  }

  set {
    name  = "aws.region"
    value = local.region
  }

  set {
    name  = "aws.roleArn"
    value = var.irsa.external-dns
  }

  set {
    name  = "serviceAccount.name"
    value = "external-dns"
  }

  set {
    name  = "aws.zonesCacheDuration"
    value = "600s"
  }

  set {
    name  = "logLevel"
    value = "debug"
  }

  set_list {
    name  = "domainFilters"
    value = ["${var.name}.example.com"]
  }
  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = var.irsa.external-dns
  }
```

### What is the expected behavior?

I would expect the DNS Records to be removed when the pods are removed but I can see reasons not to do so and manage that by hand.

### What do you see instead?

I see the DNS Records created by external-DNS staying in Route53 after removing the application.

**Comment by javsalgar** [comment]
Hi,

It seems to me that the issue is not in the Bitnami packaging of external-dns but in upstream external-dns itself. DId you check with the upstream devs?

https://github.com/kubernetes-sigs/external-dns
