### ISSUE TITLE
Support extraVolumeClaimTemplates in Clickhouse server pod definitions

### ISSUE THREAD

**Issue by nickmarden** [bitnami/charts#21878]
### Name and Version

bitnami/clickhouse 4.1.16

### What is the problem this feature will solve?

When a Clickhouse server container restarts, UDF definitions or implementations (in the form of local binaries) can be lost.

### What is the feature you are proposing to solve the problem?

I propose to add `extraVolumeClaimTemplates` so that sufficiently-determined developers can mount non-data PVs into the Clickhouse server container as part of the Clickhouse StatefulSet definition. If UDF definition files and/or implementation binaries are installed on such a PV, they will be present at restart time for use by the Clickhouse server without the need to re-install them.

### What alternatives have you considered?

Converting our high-performance UDF binaries to pure SQL. This seemed impractical, given that some of the UDFs depend on Go libraries that are not easily implemented or converted to SQL.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
