### ISSUE TITLE
[bitnami/kube-prometheus] Latest version (8.23.0) is not listed on artifacthub.io

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#21875]
### Name and Version

bitnami/kube-prometheus @ 8.23.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

No steps are needed for reproduction.

### What do you see instead?

Version 8.23.0 is not listed on ArtifactHub but is released.

**Comment by carrodher** [comment]
Thanks for letting us know. ArtifactHub ingests data from the Bitnami charts index.yaml and it seems the new version is not present there, see
```console
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo bitnami/kube-prom
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/kube-prometheus	8.22.8       	0.70.0     	Prometheus Operator provides easy monitoring de...
```
but, that version is present in the OCI registry (which is the recommended way of consuming Bitnami charts), see [DockerHub](https://hub.docker.com/layers/bitnamicharts/kube-prometheus/8.23.0/images/sha256-43262dc77850541cd67a797cb8a08583d0faa45d37a4c5560a29cbb738179bdb?context=explore).

The index.yaml, and therefore ArtifactHub, are updated by using GH Actions, it seems the the execution for this new version failed at https://github.com/bitnami/charts/actions/runs/7262227519. I just retried it, if the issue persists we will probably need to cut a new release to retrigger the process.
