### ISSUE TITLE
[bitnami/mariadb] Binlog cleanup configuration is missing

### ISSUE THREAD

**Issue by Munsio** [bitnami/charts#21886]
### Name and Version

bitnami/mariadb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Run the pod a few months

### What do you see instead?

Binlog files are accumulating without getting cleared taking half the space of the whole DB

### Additional information

MySQL is using a default for `binlog_expire_logs_seconds` of 30 days while MariaDB seems to throw that value over board https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#binlog_expire_logs_seconds

When checking the `mariadb-galera` chart I found that there is `expire_logs_days` set to 14 days.

MySQL is dropping the `expire_logs_days` so I would suggest to also switch to `binlog_expire_logs_seconds` and set it to at least 14 days, like in mariadb-galera, in the next mariadb chart release.

**Comment by Munsio** [comment]
Hi,

Actually it would not require a environment variable. 
I should have linked to the already existing configuration of the `mariadb-galera` config - https://github.com/bitnami/charts/blob/main/bitnami/mariadb-galera/values.yaml#L417

So by modifying the [mariadb/values.yml](https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml#L212) to something like this it should already work.

```
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    long_query_time=10.0
    
    ## Binary Logging
    ##
    binlog_expire_logs_seconds=2592000

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
```

In my example I use the default value from MySQL which equals 30 days (30*24*60*60 seconds)

**Comment by javsalgar** [comment]
Hi,

So then it should be a matter of updating the values.yaml with the value, right?

**Comment by Munsio** [comment]
yes

**Comment by javsalgar** [comment]
Awesome. Would you like to submit a PR updating the values?
