### ISSUE TITLE
[bitnami/oauth2-proxy] Support for SSL connections to externalRedis

### ISSUE THREAD

**Issue by HontoNoRoger** [bitnami/charts#21883]
### Name and Version

bitnami/oauth2-proxy

### What is the problem this feature will solve?

Securing connections to the external Redis, so that no non-encrypted traffic is happening between the oauth2-proxy and an external Redis.

### What is the feature you are proposing to solve the problem?

Add another parameter `ssl: true` or `tls: true` to the `externalRedis` helm chart, so that an SSL connection is established to the given host and port.

### What alternatives have you considered?

Trying to patch OAUTH2_PROXY_REDIS_CONNECTION_URL to use a "rediss://" schema (note the second s) with an ArgoCD deployed helm chart, seems quite impossible though.

**Comment by joancafom** [comment]
Hi @HontoNoRoger 

Having communications secured by the usage of TLS is an interesting feature to have, both in the `externalRedis` and the built-in `redis` chart configurations. For that to happen, it is first needed to make sure Oauth2 Proxy itself is provided with the proper certificates for the connection to happen.

Though I think it should be currently possible to do that using environment variables and using the extraVolumes options available in the chart, it would be nice to have this feature included and add the relevant properties directly in the `values.yaml` file. Would you like to contribute with a PR implementing it? The team will be more than happy to review it 😁
