### ISSUE TITLE
[FEATURE] Allow all cassandra config options to be given as env vars (similar to bitnami/kafka chart)

### ISSUE THREAD

**Issue by matthewadams** [bitnami/charts#2190]
**Which chart**:
bitnami/cassandra:5.2.0

**Is your feature request related to a problem? Please describe.**
Problem:  can only configure a small number of cassandra settings via environment variables.

**Describe the solution you'd like**
Make changes in this chart to take advantage of https://github.com/bitnami/bitnami-docker-cassandra/issues/67, similar to the bitnami/kafka chart.

**Describe alternatives you've considered**
The only alternative is to create a `ConfigMap` to mount as the `cassandra.yaml` file.

**Additional context**
This feature already has a precedent in the bitnami/kafka chart & corresponding image.  https://github.com/bitnami/bitnami-docker-kafka/blob/master/README.md#configuration says:
```
Additionally, any environment variable beginning with KAFKA_CFG_ will be mapped to its corresponding Kafka key. For example, use KAFKA_CFG_BACKGROUND_THREADS in order to set background.threads or KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE in order to configure auto.create.topics.enable.
```

**Comment by rafariossaa** [comment]
Hi @matthewadams ,
  Thanks for suggesting this. I am creating an internal task to address this feature.
  We will come back to you as soon as we have news.

**Comment by matthewadams** [comment]
Not stale

**Comment by rafariossaa** [comment]
Hi,.
  This task is in our backlog, unfortunately I don't have a ETA for this task.

**Comment by matthewadams** [comment]
not stale

**Comment by rafariossaa** [comment]
Hi,
  Sorry, we don't still have an ETA for this task.

**Comment by matthewadams** [comment]
not stale
