### ISSUE TITLE
[bitnami/sealed-secrets] sealed-secrets generates a self-signed tls secret if expected secret is not present, it needs to wait for the secret though

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#21927]
### Name and Version

bitnami/sealed-secrets:1.6.3

### What is the problem this feature will solve?

My secret appears after a few seconds as it is pulled from a vault.

This needs to be used but the sealed-secrets controller just creates its own self-signed secret.

### What is the feature you are proposing to solve the problem?

Please add the ability to add an initContainer, which I can use to wait for the secret.

Or add a parameter to the sealed secrets controller to avoid creating a self-signed cert if the expected secret is not present, instead failing and restarting in a loop until the secret is detected.

### What alternatives have you considered?

I could pull the helm chart and wrap it with my own to allow an initContainer but seems I can't be the only one who might come looking for this.

### Use case

This issue will come up for folks working with running sealed-secrets on multiple clusters and who chose to use the same tls certs on all.

**Comment by javsalgar** [comment]
Hi!

The chart has this value, which should work for your use case

```
## @param initContainers [object] Add additional init containers to the Sealed Secret pod(s)
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'echo "hello world"']
##
initContainers: []

```

**Comment by lknite** [comment]
Sure enough, not sure how I missed that.  Thought I even searched for the string 'init'...

In any case, thank you.  That's what I needed.
