### ISSUE TITLE
[bitnami/kafka] emptydir gets defined but is unused when persistance.enabled=false

### ISSUE THREAD

**Issue by horihel** [bitnami/charts#2194]
**Which chart**:
kafka 9.0.4

**Describe the bug**
If persistence.enabled=false then the StatefuleSet template will
- Define an emptydir with name "data" in volumes but will not mount it to the main container in volumeMounts.

This is because the data->/bitnami/kafka mount is disabled explicitely when persistence.enabled is off, so it's not using the emptydir that was defined for this case.

This causes kafka to lose data when the pod restarts. If emptydir is used properly, data should only be lost if the pod gets deleted and redeployed.

This causes inconsistency between kafka and zookeeper, because zookeeper chart doesn't have the bug.

**To Reproduce**
set persistence.enabled to false
see pod defines an emptydir volume "data" but doesn't mount it to the main container.

**Expected behavior**
kafka uses the data volume.

**Version of Helm and Kubernetes**:
helm 3.1.2, kubernetes 1.17.2 on RKE

**Additional context**
AFAICS removing the conditionals around the data volume in VolumeMounts should fix the problem without any side effects.

**Comment by juan131** [comment]
Hi @horihel 

Thanks so much for reporting this issue! I just created a PR to address it
