### ISSUE TITLE
[bitnami/fluent-bit] Error encountered while enabling HPA using Helm

### ISSUE THREAD

**Issue by younessof2m** [bitnami/charts#21952]
### Name and Version

bitnami/fluent-bit 0.6.5

### What architecture are you using?

None

### What steps will reproduce the bug?

When trying to enable HPA the error occured

### What do you see instead?
```
fluent-bit/templates/hpa.yaml:7:15: executing "fluent-bit/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" .>: error calling include: template: fluent-bit/charts/common/templates/_capabilities.tpl:149:7: executing "common.capabilities.hpa.apiVersion" at <semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .context)>: error calling semverCompare: Invalid Semantic Version
```
### Additional information

I think the error is similar like that https://github.com/bitnami/charts/pull/10334

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
