### ISSUE TITLE
[bitnami/grafana-operator] "502 Bad Gateway" at logout

### ISSUE THREAD

**Issue by swapzero** [bitnami/charts#21955]
### Name and Version

bitnami/grafana-operator > 3.5.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- deploy grafana-operator with bitnami/grafana-operator chart version > 3.5.11
- login to grafana (I am using LDAP)
- logout 

### What is the expected behavior?

to see grafana login screen

### What do you see instead?

502 Bad Gateway

### Additional information

grafana deployed with grafana-operator  chart v3.5.11 doesn't have this issue.

**Comment by bruceoutdoors** [comment]
I have this issue as well. I'm also using LDAP

**Comment by bruceoutdoors** [comment]
Issue is coming from grafana >=10.2.3: https://github.com/grafana/grafana/issues/79753

You can resolve it by downgrading grafana to version 10.2.2

**Comment by bruceoutdoors** [comment]
yes it is LDAP related. I’m using jumpcloud.

Also I’m not using grafana operator (I didn’t read where I was earlier haha) - but just thought I mention issue is from upstream.

**Comment by joancafom** [comment]
Thanks so much for bringing up the context @bruceoutdoors ! I missed your link to the upstream project when I first saw your comment 😅 .
