### ISSUE TITLE
[bitnami/mongodb] Inaccurate Checks in Bitnami Readiness and Startup Probes

### ISSUE THREAD

**Issue by eli-hasson** [bitnami/charts#21957]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

I found that the current readiness and startup probes  , which utilizes the bitnami scripts `/bitnami/scripts/readiness-probe.sh` and `/bitnami/scripts/startup-probe.sh` (stored within the docker image `docker.io/bitnami/mongodb:5.0.23-debian-11-r3` ) , returns an unexpected exit code (0) even when encountering an error. Here’s a snippet of the issue:
```
I have no name!@common-mongodb-2:/$ mongosh $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep 'true'
Connecting to: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.1
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017

I have no name!@common-mongodb-2:/$ echo $?
0
```
The issue arises from the fact that the pattern `directConnection=true` matches the grep `true` filter, resulting in an incorrect exit code (0). This misleading exit code makes it seem like the health check is passing.
When we used our custom probes leveraging the mongo shell instead of mongosh, the output was different and did not contain the word ‘true’:
```
I have no name!@common-mongodb-2:/$ mongo --eval 'db.hello().isWritablePrimary || db.hello().secondary'                 
MongoDB shell version v5.0.23
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("8b83775b-9e40-47b2-9293-23387ee36fd1") }
MongoDB server version: 5.0.23
true
```

A swift solution is to add the `--quiet` argument to silence the output during the connection process, ensuring only the accurate MongoDB status is returned:
```
mongosh $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --quiet --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'
```
By incorporating `--quiet`, we eliminate unwanted output and guarantee a reliable status from MongoDB.

### What do you see instead?

readiness and startup checks succeeded even when mongodb pod has not reached `SECONDAY` or `PRIMARY` state.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
