### ISSUE TITLE
[bitnami/rabbitmq] Wrong documentation and measure in rabbitmq memory watermark

### ISSUE THREAD

**Issue by dvarrazzo** [bitnami/charts#21981]
### Name and Version

bitnami/rabbitmq 12.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

IEC memory units are supported by k8s but not by rabbitmq. When an IEC value  is passed to `resources.limits.memory` (e.g. `768Mi`), the same value is also used in `rabbitmq.conf` as `vm_memory_high_watermark.absolute = 768Mi`. The value is accepted by the config parser but not hadled correctly afterwards.

### Are you using any custom parameters or values?

Straight [from the documentation](https://github.com/bitnami/charts/blob/97d62fa3f76634178ca2837c8473d32834104aea/bitnami/rabbitmq/README.md?plain=1#L477-L480):

```
memoryHighWatermark.enabled="true"
memoryHighWatermark.type="relative"
memoryHighWatermark.value="0.4"
resources.limits.memory="2Gi"
```

### What is the expected behavior?

Commands such as `rabbitmqctl status` and `rabbitmqctl report` don't work because of the problem.

To reproduce:
```
$ kubectl exec rabbitmq-0 -- rabbitmqctl status
```

### What do you see instead?

```
Reporting server status of node rabbit@rabbitmq-0.rabbitmq-headless.dev.svc.cluster.local ...
Stack trace: 

** (FunctionClauseError) no function clause matching in RabbitMQ.CLI.InformationUnit.convert/2
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/information_unit.ex:33: RabbitMQ.CLI.InformationUnit.convert({:error, :parse_error}, "gb")
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/ctl/commands/status_command.ex:152: RabbitMQ.CLI.Ctl.Commands.StatusCommand.output/2
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/ctl/commands/report_command.ex:113: RabbitMQ.CLI.Ctl.Commands.ReportCommand.run_command/3
    (rabbitmqctl 3.12.1) lib/rabbitmq/cli/ctl/commands/report_command.ex:57: RabbitMQ.CLI.Ctl.Commands.ReportCommand.run/2
    (rabbitmqctl 3.12.1) lib/rabbitmqctl.ex:174: RabbitMQCtl.maybe_run_command/3
    (rabbitmqctl 3.12.1) lib/rabbitmqctl.ex:142: anonymous fn/5 in RabbitMQCtl.do_exec_parsed_command/5
    (rabbitmqctl 3.12.1) lib/rabbitmqctl.ex:642: RabbitMQCtl.maybe_with_distribution/3
    (rabbitmqctl 3.12.1) lib/rabbitmqctl.ex:107: RabbitMQCtl.exec_command/2

Error:
:function_clause

command terminated with exit code 70
```

### Additional information

See https://github.com/rabbitmq/rabbitmq-server/discussions/10308 for the report upstream.

**Comment by dvarrazzo** [comment]
Actually, sorry, it seems that the problem is not with `resources.limits.memory` but with `memoryHighWatermark.value`. More complete values:

```
memoryHighWatermark:
  enabled: true
  type: absolute
  value: 768Mi

resources:
  limits:
    memory: 1024Mi
  requests:
    memory: 1024Mi
```

The resources.limits.memory is converted to bytes, the hwm stays in IEC:

```
total_memory_available_override_value = 1073741824
vm_memory_high_watermark.absolute = 768Mi
## TCP Listen Options
```

The documentation does use MB as example:

```
memoryHighWatermark.value="512MB"
```

but maybe a warning note would be useful there?

**Comment by rafariossaa** [comment]
Hi,
  Thanks for noticing this.
  I have created a PR to fix this.

**Comment by bmaehr** [comment]
Just because I have been searching for a while after upgrading the chart: Earlier (e.g. chart 12.4.2) a value 512MB of for memoryHighWatermark was working but now it needs to be 512Mi. According to [rabbitmq documentation](https://www.rabbitmq.com/docs/memory#absolute-limit) 512MB would still be correct, but now the conversation in the chart fails. 

Result are the messages 
```
 memory resource limit alarm set on node 'rabbit@rabbit-rabbitmq-1.rabbit-rabbitmq-headless.management.svc.cluster.local'.
 **********************************************************
 *** Publishers will be blocked until this alarm clears ***
 **********************************************************

```
and
```
Memory high watermark set to 0 MiB (0 bytes) of 2048 MiB (2147483648 bytes) total
vm_memory_high_watermark set. Memory used:139517952 allowed:0
```
after restart.
