### ISSUE TITLE
[bitnami/rabbitmq] Incomplete documentation for `clustering.name`

### ISSUE THREAD

**Issue by dvarrazzo** [bitnami/charts#21987]
### Name and Version

bitnami/rabbitmq 12.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The chart default with clustering = true but no cluster name set causes confusion. A cluster is created, but, for some aspects a cluster is presented with two different names, defaulting to the node name. For example, with using the command `rabbitmqctl cluster_status` on the pod `rabbitmq-0`, the following is returned

```console
$ rabbitmqctl cluster_status
Cluster status of node rabbit@rabbitmq-0.rabbitmq-headless.dev.svc.cluster.local ...
Basics

Cluster name: rabbit@rabbitmq-0.rabbitmq-headless.dev.svc.cluster.local
Total CPU cores available cluster-wide: 4

Disk Nodes

rabbit@rabbitmq-0.rabbitmq-headless.dev.svc.cluster.local
rabbit@rabbitmq-1.rabbitmq-headless.dev.svc.cluster.local
...
```

and, on `rabbitmq-1`, there would be a report of `Cluster name: rabbit@rabbitmq-1.rabbitmq-headless.dev.svc.cluster.local`. On the grafana dashboard instead of seeing a cluster, there are two clusters named as the nodes.

![image](https://github.com/bitnami/charts/assets/199429/03f471ca-d43a-4b16-87f6-695f0bbc6a88)

The cluster might or might not work well (the resources created in the cluster are duplicated on both the nodes; we were having failover problems but I'm not sure if this is related).

My suggestion is to not allow an empty string for `clustering.name`, if `clustering.enabled` is true, and to use `{{ include "common.names.fullname" . }}` as default for the name.

### Are you using any custom parameters or values?

`--set replicaCount=2` is enough to reproduce the issue, leaving `clustering` with the default values.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input! Would you like to submit a PR with the cluster name?

**Comment by dvarrazzo** [comment]
> Thank you so much for the input! Would you like to submit a PR with the cluster name?

No problem, on its way.

**Comment by FraPazGal** [comment]
Hello @dvarrazzo, the readme-generator will only take the first line (the one that uses `@param`). I agree we could move L257 to L256 to avoid confusion.
