### ISSUE TITLE
[bitnami/kafka] Unable to produce or consume messages on Kafka cluster with External

### ISSUE THREAD

**Issue by MikeOltmanFox** [bitnami/charts#22003]
### Name and Version

bitnami/kafka 26.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

the goal of this is to run a local Kafka environment in a k8s cluster with external access to locally debug event-driven services
I am looking to have both ability to run in cluster or debug
everything is running localhost for dev purposes
- k8s cluster is a kind cluster
- os is MacOs (latest version, Apple chip)

1. start with standard install of helm chart
2. apply the following within values.yaml to set comms to PLAINTEXT and expose EXTERNAL (replicaCount: 3 I redundant with default but left in values.yaml so I can test various replicas.)
3. port forward 31000, 31001, 31002 to 9095
4. running a test within the cluster successfully produces and consumers messages (topic hello is auto created in my in-cluster process)
5. running `kafka-console-producer --topic hello --bootstrap-server localhost:31002` or `kafka-console-producer --topic hello --bootstrap-server localhost:31000,localhost:31001,localhost:31002` both produce the following error:
```WARN [Producer clientId=console-producer] Received invalid metadata error in produce request on partition hello-0 due to org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)```
6. running `kafka-console-consumer --topic hello --bootstrap-server localhost:31000,localhost:31001,localhost:31002 --group localgroup` produces no console error but consumes no messages. localgroup is unique to console only. the following is seen in the broker logs:
```
INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group localgroup in Stable state. Created a new member id console-consumer-b9694855-bc45-407a-a0ef-d9c1b51bbe53 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Preparing to rebalance group localgroup in state PreparingRebalance with old generation 11 (__consumer_offsets-30) (reason: Adding new member console-consumer-b9694855-bc45-407a-a0ef-d9c1b51bbe53 with group instance id None; client reason: rebalance failed due to MemberIdRequiredException) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Stabilized group localgroup generation 12 (__consumer_offsets-30) with 2 members (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Assignment received from leader console-consumer-0f3fbce5-19e3-4737-b5da-480656b4568b for group localgroup for generation 12. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
```

### Are you using any custom parameters or values?

```
kafka:
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
      name: CLIENT
      sslClientAuth: ""
    controller:
      name: CONTROLLER
      containerPort: 9093
      protocol: PLAINTEXT
      sslClientAuth: ""
    interbroker:
      containerPort: 9094
      protocol: PLAINTEXT
      name: INTERNAL
      sslClientAuth: ""
    external:
      containerPort: 9095
      protocol: PLAINTEXT
      name: EXTERNAL
      sslClientAuth: ""
  controller:
    replicaCount: 3

  externalAccess:
    enabled: true
    controller:
      service:
        domain: localhost
        type: NodePort
        nodePorts: ['31000','31001','31002']
 ```

### What is the expected behavior?

I expect both localhost process and simple console consumer and producers to connect and produce/consume messages. I'm not clear if this is a bug or a gap in documented configuration or just something I missed.

### What do you see instead?

errors as provided in main text

### Additional information

I plan on testing with replica set to 1 as well, but I feel since this is a "default plus minor comms configuration" it should work without reducing replicas

**Comment by MikeOltmanFox** [comment]
one more note. the in-k8s-cluster process connects using the k8s addresses directly
`event-bus-kafka-controller-2.event-bus-kafka-controller-headless.default.svc.cluster.local:9092`

also tried this on the console to no avail
`kafka-console-consumer --topic hello --bootstrap-server localhost:31001 --group localgroup`

**Comment by joancafom** [comment]
Hi @MikeOltmanFox 

I am having trouble to fully understand your use case, so I will try to explain what I understood and go over the steps I followed based on that. 

> the goal of this is to run a local Kafka environment in a k8s cluster with external access to locally debug event-driven services
I am looking to have both ability to run in cluster or debug
everything is running localhost for dev purposes
k8s cluster is a kind cluster
os is MacOs (latest version, Apple chip)

You are running a local K8s cluster in your macOS machine with an ARM chip using _Kind_ as the solution to deploy it. You want to deploy the `bitnami/kafka` chart on it and want to interact with it not only from within the cluster, but also from outside it, so you enabled the external access feature. Everything works well (producing and consuming msg) from within the cluster, but outside of it you seem to face some strange problems.

First of all, let me tell you that I am not familiar with _Kind_ so I don't really know the internals of how it works. I will use Minikube on a local macOS machine with an ARM though, so it will be pretty similar. Just to set the context, let me mention that local K8s solutions for macOS machines usually (not all) work by running a virtual machine Linux OS under the hood where K8s is actually installed and then connections are forwarded to this host. This is the case of Minikube (but don't really know about _Kind_).

1. Deploy the `bitnami/kafka` chart with values based on yours and check everything is running as expected:

```console
$ cat params.yaml
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
controller:
  replicaCount: 3

externalAccess:
  enabled: true
  controller:
    service:
      domain: "my-cluster"
      type: NodePort
      nodePorts: ['31000','31001','31002']

$ helm install kafka bitnami/kafka -f params.yaml
$ k get pods
NAME                 READY   STATUS    RESTARTS   AGE
kafka-client         1/1     Running   0          53m
kafka-controller-0   1/1     Running   0          55m
kafka-controller-1   1/1     Running   0          55m
kafka-controller-2   1/1     Running   0          55m
```

Notice however how the top-level `kafka` entry was not provided (maybe you are deploying the chart somewhat differently?, if not, please make sure to delete it). Also notice that I have changed the `domain` entry to `my-cluster`. The rest is the same (the omitted entries have the same default value).

2. Connect to the Kafka cluster from within the K8s cluster as described by the NOTES, create a new topic and produce/consume messages:

```console
$ kubectl run kafka-client --restart='Never' --image docker.io/bitnami/kafka:3.6.1-debian-11-r0 --namespace default --command -- sleep infinity
$ kubectl exec --tty -i kafka-client --namespace default -- bash
> kafka-console-producer.sh \
            --broker-list kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.default.svc.cluster.local:9092 \
            --topic candy
>>lollipop
>>marshmallow

> kafka-console-consumer.sh \
        --bootstrap-server kafka.default.svc.cluster.local:9092 \
        --topic candy \
        --from-beginning
lollipop
marshmallow
^CProcessed a total of 2 messages
```

3. Connect to the Kafka cluster from outside. For this, bear in mind that in my case (**and maybe yours as well**), our K8s cluster is not running directly in our machine, and thus connecting to the loopback interface (127.0.0.1) will not directly work unless specifically configured. 

3.1. As we are using a NodePort, we will identify which is the IP of the node running our application and, together with the port we have specified, we have a socket to connect to:

   ```console
   $ k get nodes
    NAME       STATUS   ROLES           AGE    VERSION
    minikube   Ready    control-plane   220d   v1.26.3

   $ k describe node/minikube | grep IP
     InternalIP:  192.168.49.2
   ```

3.2. Create an entry in my `/etc/hosts` file to make the host `my-cluster` (the domain we have configured) point to `192.168.49.2` 

```
$ echo "192.168.49.2 my-cluster" >> /etc/hosts
```

3.3 As I don't have any of the Kafka binaries available in my local system, I will use a docker image containing them and share the host network:

```console
$ docker run --network host --rm -it bitnami/kafka bash
> $ kafka-console-consumer.sh \
            --bootstrap-server my-cluster:31002 \
            --topic candy \
            --from-beginning
lollipop
marshmallow
^CProcessed a total of 2 messages

> $ kafka-console-producer.sh \
   --broker-list my-cluster:31000,my-cluster:31001,my-cluster:31002 \
   --topic candy
>>gum
>>jellyfish

> $ kafka-console-consumer.sh --bootstrap-server my-cluster:31002 --topic candy --from-beginning
lollipop
marshmallow
gum
jellyfish
^CProcessed a total of 4 messages
```

Maybe I am missing something, but as you can seem, everything seems to be working like a charm! Hence, I think this has something to do with your networking 🤔 

Hope it helps!

**Comment by MikeOltmanFox** [comment]
further testing, I created a topic using `kafka-topics --create --topic hello.test --partitions 5 --replication-factor 3 --bootstrap-server localhost:31001`
continue to view the following error in the producer logs:
```
[16] Not Coordinator For Group: the broker returns this error code if it receives an offset fetch or commit request for a group that it is not a coordinator for
```
controller/broker logs:
```
Closing connection due to error during produce request with correlation id 2 from client id  with ack=0
Topic and partition to exceptions: hello.test-0 -> org.apache.kafka.common.errors.NotLeaderOrFollowerException (kafka.server.KafkaApis)
```

this only happens in producers and consumer outside the k8s cluster. so its clear the processes are connecting but something is incorrect with the configuration

**Comment by MikeOltmanFox** [comment]
@joancafom thank you for the detailed breakdown of how you made it work. I will run through this and see if that works for me.

I believe kind work similar to minikube but if I cannot make it work with kind I will also test with minikube to verify if that is the problem.

I do see some of the differences and will reconfigure and test accordingly. the biggest is the localhost and loopback call. I wondered if that could be a problem, but as I was able to manage some sort of connection I wasn't sure.

I will let you know the results as soon as I test.

**Comment by MikeOltmanFox** [comment]
following your process above I end up with the same result, but testing further (including using Minikube instead of Kind) I believe it is a networking issue with the IP address of the k8s cluster. I cannot access that IP. by default, the IP was the same as yours. but regardless of attempts to access, I cannot directly access. I tried starting up the cluster with a static IP of 172.16.0.2 and the same result. I cannot access that cluster IP. this appears to be consistent with many public issues around accessing Minikube services.

I then tested various port-forward configurations with partial success.

question for you: do you have any custom routing or tunneling to your cluster? do you have any port forwards?

**Comment by MikeOltmanFox** [comment]
so I have been able to access it successfully. definitely no bugs in the helm chart, but perhaps something to note in the docs or maybe this thread will suffice.

the issue appears to be the internal networking in MacOS and access to Minikube or Kind even when setting the NodePorts. the reason appears to be two-fold:
1. the IP address of the cluster is  inaccessible. so even using /etc/hosts will have no effect since it just does not route to the IP. even though my cluster knows it is exposing the NodePorts on that address (my utility confirms these links: `172.16.0.2:31000,172.16.0.2:31001,172.16.0.2:31002`) my environment cannot access
2. the NodePorts are exposes as a service and not on the pods. my previous port forwarding was set on the pods. so running this command correctly forwards the services. although I do find it interesting that the NodePort is 9094 and not 9095. I don't understand that, but it works:
```
kubectl port-forward svc/event-bus-kafka-controller-0-external 31000:9094 & \
kubectl port-forward svc/event-bus-kafka-controller-1-external 31001:9094 & \
kubectl port-forward svc/event-bus-kafka-controller-2-external 31002:9094 &
```
**output**
```
Forwarding from 127.0.0.1:31001 -> 9095
Forwarding from 127.0.0.1:31000 -> 9095
Forwarding from 127.0.0.1:31002 -> 9095
Forwarding from [::1]:31001 -> 9095
Forwarding from [::1]:31000 -> 9095
Forwarding from [::1]:31002 -> 9095
```

I do not know if this is MacOS specific, M2 chip specific, or perhaps my version of Docker or Minikube. I also tested in Kind and exact same results and solution.

I do wonder if it works for you because running within Docker allows the communication from container to container/cluster vs terminal to cluster.

I will try to run a few more options and see if I can discern anything else.

**Comment by MikeOltmanFox** [comment]
One last finding and then open to how you want to handle this ticket.

if I just port forward the cluster, it still does not work. Any other combination of ports, forwarding, external access does not appear to work. I tried pod forwarding, cluster forwarding, and ip tunneling to no success (the last I may have done wrong). I also tried custom IP addresses for both Minikube and Kind. my only success is if both of the following are true:
- kafka values.yaml has this:
```
  externalAccess:
    ## @param externalAccess.enabled Enable Kubernetes external cluster access to Kafka brokers
    ##
    enabled: true
    controller:
      service:
        domain: "localhost"
        type: NodePort
        nodePorts: ['31000','31001','31002']
```
- the specific NodePort services are forwarded:
```
kubectl port-forward svc/event-bus-kafka-controller-0-external 31000:9094 & \
kubectl port-forward svc/event-bus-kafka-controller-1-external 31001:9094 & \
kubectl port-forward svc/event-bus-kafka-controller-2-external 31002:9094 &
```

**Comment by joancafom** [comment]
> question for you: do you have any custom routing or tunneling to your cluster? do you have any port forwards?

No, but I have noticed that minikube changed the default implementation and now runs using docker-based images instead of a Linux VM. In any case, I don't recall performing any configuration changes regarding networking.

> so I have been able to access it successfully. definitely no bugs in the helm chart, but perhaps something to note in the docs or maybe this thread will suffice.

Glad to see this is not related to the chart 😁  I think this thread is enough, as this has much more to do with the specific functioning of a cluster implementation than to our asset itself.

> kubectl port-forward svc/event-bus-kafka-controller-0-external 31000:9094 & \
kubectl port-forward svc/event-bus-kafka-controller-1-external 31001:9094 & \
kubectl port-forward svc/event-bus-kafka-controller-2-external 31002:9094 &

Beware that the port-forward mapping from the K8s cluster to your local machine SHOULD BE unique. That is, you should NOT assign the same local port to more than one remote endpoint.

Having said that, I think this issue revolves around the internal of how Minikube/Kind works on Apple ecosystem and you should therefore reach out to their community to obtain a precise answer about their internals. Thanks!

**Comment by newerton** [comment]
@joancafom Thanks for the example, I upgraded my Kafka to Kraft mode, and I spent almost the whole day trying to connect through ports 9092~9095, using LoadBalancer, NodePort and ClusterIP, all with port-forward and I was unsuccessful.

Your example helped me find my problem.
First with 1 replica it was not working, with 3 replicas I was able to use kafka-console-producer.sh and kafka-console-consumer.sh, then I did the test using the "domain" and it also worked.

I'm using KafkaJS, and everything is fine now.

The only problem is that the first time the topic is created, it returns an error.

**This server does not host this topic-partition**

When the pod restarts, the connection is established.

My chart dependencies:
```yaml
dependencies:
  - name: kafka
    version: "26.8.0"
    repository: "https://charts.bitnami.com/bitnami"
```
My values-develop:
```yaml
extraConfig: "autoCreateTopicsEnable=true;deleteTopicEnable=true"
externalAccess:
  enabled: true
  controller:
    service:
      domain: "kafka.microservice.local"
      type: NodePort
      nodePorts: [31000, 31001, 31002]
serviceAccount:
  create: true
rbac:
  create: true
controller:
  replicaCount: 3
kraft:
  enabled: true
  clusterId: "q1Sh-9_ISia_zwGINzRvyQ"
metrics:
  jmx:
    enabled: true
    kafkaJmxPort: 9997
  kafka:
    enabled: false
  serviceMonitor:
    enabled: false
    labels:
      release: prometheus
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
```

C:\Windows\System32\drivers\etc\hosts (Windows 11)
```
127.0.0.1       kafka.microservice.local
```

**Comment by joancafom** [comment]
Hi @newerton 

Glad to see the thread helped 😁. As per your your new issue, we try to keep threads single-themed. Could you please check if there is another similar issue already created? If it is not the case, feel free to open a new one and one of our team members will take care 🚀
