### ISSUE TITLE
[bitnami/supabase] Cannot access postgresql db as superuser

### ISSUE THREAD

**Issue by wdoppenberg** [bitnami/charts#22079]
### Name and Version

bitnami/supabase 2.2.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Deploy bitnami to k8s with default values, port-forward db, then attempt to push a project's supabase configuration (migrations) to deployed db using `supabase db push --db-url postgresql://postgres:<pw>@localhost:5432`. `<pw>` is in your db-secret. `postgres` user is not superuser, and trying to access using the `supabase_admin` user (which does have superuser) with the aforementioned password doesn't work either. 

Furthermore, very often during initialization of all the containers, the logs of the postgresql container contain the following lines (repeated often):

```
│ 2024-01-13 14:20:06.191 GMT [2113] FATAL:  password authentication failed for user "supabase_admin"
```

This is often paired with other services that are part of the chart not initializing, leading me to believe that there is something wrong with the secret configuration or something else.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

I'd like to be able to push a project such as [this one](https://github.com/mckaywrigley/chatbot-ui) to the db. 

### What do you see instead?

No authorization when a call like the following is done when logged in using `psql postgresql://postgres:<pw>@localhost:5432`:

```
create extension http;
ERROR:  permission denied to create extension "http"
HINT:  Must be superuser to create this extension.
```

**Comment by javsalgar** [comment]
Hi,

Could you confirm that you don't have PVC leftovers from previous supabase installations?

**Comment by wdoppenberg** [comment]
> Hi,
> 
> Could you confirm that you don't have PVC leftovers from previous supabase installations?

Hi, I've indeed come to the realization that if the PVC leftovers are deleted, the other services can communicate. However, I still have the issue of not being able to login in as superuser (`supabase_admin`) to the database using a port forward mapping and `psql`.

**Comment by joancafom** [comment]
Hi @wdoppenberg 

> Hi, I've indeed come to the realization that if the PVC leftovers are deleted, the other services can communicate.

Thanks for the confirmation, and glad it helped.

> However, I still have the issue of not being able to login in as superuser (supabase_admin) to the database using a port forward mapping and psql.

I have tried to reproduce your issue, but I can log in and operate fine using the `supabase_admin` user. Here are the steps I've followed:

1. List the secrets and obtain the generated password:

```console
$ kubectl get secrets | grep postgres
supabase-postgresql              Opaque                                1      10m

$ kubectl describe secret/supabase-postgresql
Name:         supabase-postgresql
Namespace:    test
Labels:       app.kubernetes.io/instance=supabase
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=postgresql
              app.kubernetes.io/version=16.1.0
              helm.sh/chart=postgresql-13.2.30
Annotations:  meta.helm.sh/release-name: supabase
              meta.helm.sh/release-namespace: test

Type:  Opaque

Data
====
postgres-password:  10 bytes

$ kubectl get secret/supabase-postgresql -o jsonpath='{.data.postgres-password}' | base64 -d
fm7otocADU
```

2. Connect to the DB using `psql`. As I do not have `psql` binaries locally, I will create a temporary pod with the `bitnami/postgresql` image as a base:

```console
$ kubectl run psql-client --rm -it --image=bitnami/postgresql --env="PGPASSWORD=fm7otocADU" --command -- psql --host supabase-postgresql -U supabase_admin -d postgres -p 5432

postgres=# \c
psql (16.1, server 15.5)
You are now connected to database "postgres" as user "supabase_admin".
postgres=# create extension http;
CREATE EXTENSION

postgres=# \du
                                      List of roles
         Role name          |                         Attributes
----------------------------+------------------------------------------------------------
(...)
 supabase_admin             | Superuser, Create role, Create DB, Replication, Bypass RLS
```

Could you please check if that is the case for you as well?

**Comment by wdoppenberg** [comment]
> Hi @wdoppenberg
> 
> > Hi, I've indeed come to the realization that if the PVC leftovers are deleted, the other services can communicate.
> 
> Thanks for the confirmation, and glad it helped.
> 
> > However, I still have the issue of not being able to login in as superuser (supabase_admin) to the database using a port forward mapping and psql.
> 
> I have tried to reproduce your issue, but I can log in and operate fine using the `supabase_admin` user. Here are the steps I've followed:
> 
>     1. List the secrets and obtain the generated password:
> 
> 
> ```
> $ kubectl get secrets | grep postgres
> supabase-postgresql              Opaque                                1      10m
> 
> $ kubectl describe secret/supabase-postgresql
> Name:         supabase-postgresql
> Namespace:    test
> Labels:       app.kubernetes.io/instance=supabase
>               app.kubernetes.io/managed-by=Helm
>               app.kubernetes.io/name=postgresql
>               app.kubernetes.io/version=16.1.0
>               helm.sh/chart=postgresql-13.2.30
> Annotations:  meta.helm.sh/release-name: supabase
>               meta.helm.sh/release-namespace: test
> 
> Type:  Opaque
> 
> Data
> ====
> postgres-password:  10 bytes
> 
> $ kubectl get secret/supabase-postgresql -o jsonpath='{.data.postgres-password}' | base64 -d
> fm7otocADU
> ```
> 
>     2. Connect to the DB using `psql`. As I do not have `psql` binaries locally, I will create a temporary pod with the `bitnami/postgresql` image as a base:
> 
> 
> ```
> $ kubectl run psql-client --rm -it --image=bitnami/postgresql --env="PGPASSWORD=fm7otocADU" --command -- psql --host supabase-postgresql -U supabase_admin -d postgres -p 5432
> 
> postgres=# \c
> psql (16.1, server 15.5)
> You are now connected to database "postgres" as user "supabase_admin".
> postgres=# create extension http;
> CREATE EXTENSION
> 
> postgres=# \du
>                                       List of roles
>          Role name          |                         Attributes
> ----------------------------+------------------------------------------------------------
> (...)
>  supabase_admin             | Superuser, Create role, Create DB, Replication, Bypass RLS
> ```
> 
> Could you please check if that is the case for you as well?

This worked! Thanks a lot :)
