### ISSUE TITLE
Airflow Postgres externalDatabase with SSL

### ISSUE THREAD

**Issue by anirao** [bitnami/charts#22075]
### Name and Version

bitnami/airflow 16.1.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create an external postgresql database in azure and enable Enforce SSL connection. Update the values.yaml and populate the externalDatabase information and apply the configuration.
You will notice that the pods keep restarting with this in the logs
airflow 17:55:30.46 INFO  ==> Trying to connect to the database server
airflow 17:56:56.20 ERROR ==> Could not connect to the database

I can however exec into one of the airflow pods and connect to the database  
psql "host=mydb.postgres.database.usgovcloudapi.net port=5432 dbname=airflow_db user=airflow_user@mydb password=airflow_pass sslmode=require" and connect to the database successfully.

I have setup the postgres database as specified below:
CREATE DATABASE airflow_db;
CREATE USER airflow_user WITH PASSWORD 'airflow_pass';
GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow_user;
-- PostgreSQL 15 requires additional privileges:
USE airflow_db;
GRANT ALL ON SCHEMA public TO airflow_user;

My psql connection details
psql (16.1, server 11.18)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compression: off)

### Are you using any custom parameters or values?

    externalDatabase:  #TODO - fake info
      host: mydb.postgres.database.usgovcloudapi.net
      port: 5432
      user: airflow_user
      database: airflow_db
      password: "airflow_pass" 
      existingSecret: ""
      existingSecretPasswordKey: ""

### What is the expected behavior?

Connect without any issues and get to the UI.

### What do you see instead?

airflow-scheduler-6f785b9f76-xks7s   0/1     CrashLoopBackOff   10 (24s ago)   42m
airflow-web-6d8497cd9-wgngg          0/1     CrashLoopBackOff   10 (25s ago)   42m

You will notice that the pods keep restarting with this in the logs
airflow 17:55:30.46 INFO  ==> Trying to connect to the database server
airflow 17:56:56.20 ERROR ==> Could not connect to the database

### Additional information

I did try adding AIRFLOW_DATABASE_USE_SSL extraEnvVars based on what i read in https://github.com/bitnami/charts/issues/5226. This did not help.

**Comment by anirao** [comment]
Turns out this had nothing to do with SSL. Turns out it was to do with the externalDatabase.user which needs to be in the username@hostname format. Would be good to update the README.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for letting us know. Would you like to submit a PR updating the README?

**Comment by anirao** [comment]
Link to the PR - https://github.com/bitnami/charts/pull/22207
