### ISSUE TITLE
Fail to install new postgresql when the namespace used is other than default

### ISSUE THREAD

**Issue by cvgaviao** [bitnami/charts#22080]
### Name and Version

bitnamicharts/postgresql 13.2.29

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. using microk8s 1.28.5
2. microk8s helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql -n postgresql --create-namespace

### What is the expected behavior?

I was expecting that the postgresql was installed in a custom namespace other than the default one.

### What do you see instead?

The created pod stays in a pending state with the following warning message: MountVolume.SetUp failed for volume "kube-api-access-z6gkp" : configmap "kube-root-ca.crt" not found

**Comment by FraPazGal** [comment]
Hello @cvgaviao, going by warning message the error may be related to `microk8s`. I have tried reproducing the without success and by default our CIs tests our charts in non-default namespaces.

I suggest you to try using another Kubernetes cluster be it locally, Docker Kubernetes or Minikube, or in the cloud using the services of a cloud provider.
