### ISSUE TITLE
[bitnami/supabase] `supabase-realtime` Segmentation fault during startup

### ISSUE THREAD

**Issue by wdoppenberg** [bitnami/charts#22085]
### Name and Version

bitnami/supabase 2.2.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Attempted to install the chart on `minikube` instance on MacOS (ARM). 

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Correct initialization

### What do you see instead?

`supabase-realtime` container will fail to initialize and exits with the following error:

```bash
/bin/bash: line 1:    12 Segmentation fault      realtime eval Realtime.Release.migrate
```

**Comment by carrodher** [comment]
Unfortunately, Supabase is not supported in ARM at this moment. We have an internal task to review it; we'll update this ticket accordingly after that review.

**Comment by wdoppenberg** [comment]
> Unfortunately, Supabase is not supported in ARM at this moment. We have an internal task to review it; we'll update this ticket accordingly after that review.

Thank you for the quick reply, I look forward to the review's outcome.

**Comment by vanakema** [comment]
@carrodher is there an update? Unfortunately supabase is our only docker image dependency that is not compatible with arm64

**Comment by carrodher** [comment]
Yes, all the Bitnami supabase images are now multiarch, you shouldn't face any issue deploying them in ARM
