### ISSUE TITLE
[bitnami/matomo] smtp settings are not taking effect

### ISSUE THREAD

**Issue by ashwin027** [bitnami/charts#22084]
### Name and Version

bitnami/matomo 4.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set the SMTP settings through the values.yaml
2. Invite a user from the Matomo UI - Error in pod logs - usr/sbin/sendmail function not found.
3. Add the SMTP settings manually from the matomo UI - Settings --> System --> General settings --> Email server settings. Emails work fine. 

### Are you using any custom parameters or values?
```
smtpAuth: "Login"
smtpHost: "redacted"
smtpPort: "587"
smtpUser: "user"
smtpProtocol: "tls"
noreplyName: "redacted"
noreplyAddress: "redacted" 
smtpExistingSecret: "secret containing key smtp-password"
```
### What is the expected behavior?

Adding the SMTP settings through the values.yaml should take effect. The Matomo UI should also reflect the settings set through the values.yaml file.

### What do you see instead?

The SMTP settings specified in the values.yaml file does not take effect.

**Comment by migruiz4** [comment]
Hi @ashwin027,

Could you please confirm that your use case was a fresh install?

I tried to reproduce your issue but when login into Matomo I can see the SMTP settings have been configured:
![image](https://github.com/bitnami/charts/assets/37381070/289fc50d-cad6-407c-a32b-4c71326c4113)

Please note that SMTP settings will only take effect during the server's first boot.
