### ISSUE TITLE
Clickhouse connection via clickhouse client

### ISSUE THREAD

**Issue by amandpay** [bitnami/charts#22090]
### Name and Version

bitnamicharts/clickhouse 23.12.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the helm charts
2. Create a ingress
3. Try to connect from clickhouse client via ingress host.

### What do you see instead?

I have installed clickhouse via helm charts, and created an ingress like clickhouse.xyz.com, I am able to connect from grafana plugin at port 443 but when I use 
```
./clickhouse client -h clickhouse.xyz.com--port 443 -u username--password passs
```
this is not responding.

**Comment by juan131** [comment]
Hi @amandpay 

Could you please the **values.yaml** (or equivalent parameters passed via `--set ` flag) you used while installing the chart? Thanks in advance.
