### ISSUE TITLE
Minio Root User Disabled

### ISSUE THREAD

**Issue by sass1997** [bitnami/charts#22095]
### Name and Version

docker.io/bitnami/minio:2023.5.4-debian-11-r1

### What architecture are you using?

None

### What steps will reproduce the bug?

How can I unlock the root user? Unfortunately, I've changed the password without enabling the FLAG `MINIO_FORCE_NEW_KEYS`. I want to reenable the user right now

### What do you see instead?
```
mc: <ERROR> Unable to initialize new alias from the provided credentials. Your account is disabled; please contact your administrator.
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
