### ISSUE TITLE
[SSL] [Cassandra] SSL Setup issues with cassandra

### ISSUE THREAD

**Issue by vaibhavkhurana2018** [bitnami/charts#2215]
I am trying to setup client SSL on the cassandra cluster which i have deployed on k8s. The helm chart documentation, says i have to create a secret with proper keystore and truststore. The problem that i have here is, for generation keystores i have to generate certs via ips/dns of the nodes(pods in this case), but the ip's will keep on changing with the pod and pod dns will be local to that cluster (My clients can be outside of the k8s cluster hosting cassandra, so can't use this).

I don't want to use hostNet for this as then i will be bound by the cloud machines, and the flexibility k8s gives will be lost.

Please suggest. Also if someone can point out to some valid solutions/discussions/articles for this. Is it possible to do this thing in some other way, will love to have some examples.

**Comment by marcosbc** [comment]
@vaibhavkhurana2018 AFAIK, the chart currently uses the list of nodes in "CASSANDRA_SEEDS", which refer to headless hostnames (i.e. "cassandra-0.cassandra-headless.default.svc.cluster.local"). If you use those values, you should be able to create a domain.

Usually the best way for doing this if you don't know the hostnames beforehand, consists in deploying the Helm chart without SSL and obtaining the node names afterwards. Once obtained, you can update the deployment with SSL configured.

It is worth mentionig that we have had similar issues in Kafka before, see: https://github.com/bitnami/charts/issues/1279#issuecomment-511465933.
You should also look into the OpenSSL configuration posted in the thread, as it will be needed if you want to create certificates with Subject Alternative Names (SANs).
