### ISSUE TITLE
[bitnami/prometheus-operator] not clear how to dynamically add Targets in an existing running deployment

### ISSUE THREAD

**Issue by strus38** [bitnami/charts#2217]
bitnami/prometheus-operator - latest version

From the doc I cannot find a way to add a new Target in scrape_configs.

I basically deployed the helm chart:
`helm update prometheus-operator \
  --set operator.service.type=ClusterIP \
  --set prometheus.service.type=ClusterIP \
  --set alertmanager.service.type=ClusterIP \
  --set prometheus.externalLabels.cluster="data-producer-0" \
  bitnami/prometheus-operator
`
This is working fine and I can monitor my kubernetes cluster, but now I want to add an external VM which has a node-exporter setup.

I would expect somewhere in the documentation to find the way to add more targets without redeploying the helm chart or adding the `--set prometheus.additionalScrapeConfigsExternal=true` parameter.

I tried to edit the existing config map:
`kubectl edit configmap prometheus-prometheus-operator-prometheus-rulefiles-0`
but I don't see where and if I can add a scrape_configs section into it.

Any hints please?

Follow-up: I just did:
` $ kubectl create configmap prometheus-prometheus-operator-prometheus-scrape-config --from-file additional-scrape-configs.yaml
`
`
$ cat additional-scrape-configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: default
data:
  additional-scrape-configs.yaml: |-
    scrape_configs:
      - job_name: centos8
        static_configs:
          - targets: ['10.0.2.15:9100']
`
`
$helm upgrade prometheus-operator \
  --set prometheus.thanos.create=false \
  --set operator.service.type=ClusterIP \
  --set prometheus.service.type=ClusterIP \
  --set alertmanager.service.type=ClusterIP \
  --set prometheus.additionalScrapeConfigsExternal=true \
  --set prometheus.externalLabels.cluster="data-producer-0" \
  bitnami/prometheus-operator
`
But something is wrong since I don't see my additional host in prometheus/targets

Any hints?

Thanks

**Comment by javsalgar** [comment]
Hi,

Wouldn't the Prometheus Operator CRDs do the job? For example the ServiceMonitor object? 

https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor

**Comment by strus38** [comment]
Ok for targets which are running within the k8s cluster, but what about
targets which are running outside, but reachable (network wise) outside of
it?
Thanks

**Comment by javsalgar** [comment]
Hi,

In this sense, you could create a Kubernetes service that points to that external target

https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/.
