### ISSUE TITLE
[bitnami/logstash] Is there any way to override settings in logstash.yml?

### ISSUE THREAD

**Issue by natimellino** [bitnami/charts#22211]
### Name and Version

bitnami/logstash

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Set `configFileName` to the name of the mounted configuration file for logstash.yml.
2. Create configmap with logstash.yml configuration and create the volumeMounts.
3. Install the chart.

### What is the expected behavior?

See file /opt/bitnami/logstash/config/logstash.yml overwritten with the configmap I created.

### What do you see instead?

/opt/bitnami/logstash/config/logstash.yml file content is not overwritten with my default settings.

### Additional information

I've benn trying for a couple of days to put my own configuration in logstash.yml in order to configure persistent queues and other stuff. But I had no luck. I've tried to directly mount my own config file in the same location where the default logstash.yml is located but it throws an error. I also used the `configFileName` parameter from the chart but I believe that it is not what I need. Is there actually a way to put my own settings in logstash.yml? Thanks in advance.

**Comment by migruiz4** [comment]
Hi @natimellino,

The value `configFileName` corresponds to the name of the file containing the Logstash pipeline configuration when `enableMultiplePipelines=false`.

At the moment, the `bitnami/logstash` chart and image do not provide a method to customize the `logstash.yml` file other than mounting it.
It would be possible to mount `logstash.yml` as a volume using the `extraVolumes` and `extraVolumeMounts` values or creating your own Configmap including both logstash.conf and logstash.yml and provide it using the `existingConfiguration`value.

Although, I implemented a new feature in the `bitnami/logstash` chart that may help you. By using the new value `extraConfigurationFiles` you can provide any additional file you would like to include at `/opt/bitnami/logstash/config`.
See https://github.com/bitnami/charts/pull/22512

The example I added in the values.yaml can be used to extend the `logstash.yml` file.

**Comment by natimellino** [comment]
Hi @migruiz4, thank you for your response! I gave a look at the feature and I think this would work for me, I will give it a try and see if it works, thanks for your time :)
