### ISSUE TITLE
[bitnami/external-dns] Azure Private DNS : use secrets for sensitive env variable

### ISSUE THREAD

**Issue by Tetradeus** [bitnami/charts#2221]
**Which chart**:
bitnami/external-dns

**Is your feature request related to a problem? Please describe.**
Provider Azure private dns : sensitive data are being passed directly to deployment definition instead of via secrets

**Describe the solution you'd like**
It would be way better to use env from secrets 

**Describe alternatives you've considered**
NONE...

**Additional context**
Use secrets for following values in https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/deployment.yaml :
```
            {{- if eq .Values.provider "azure-private-dns" }}
            # Azure Private DNS variables
            {{- if .Values.azure.tenantId }}
            - name: AZURE_TENANT_ID
              value: {{ .Values.azure.tenantId }}
            {{- end }}
            {{- if .Values.azure.aadClientId }}
            - name: AZURE_CLIENT_ID
              value: {{ .Values.azure.aadClientId }}
            {{- end }}
            {{- if .Values.azure.aadClientSecret }}
            - name: AZURE_CLIENT_SECRET
              value: {{ .Values.azure.aadClientSecret }}
            {{- end }}
            {{- end }}
```

**Comment by rafariossaa** [comment]
Hi @Tetradeus 
  Thanks for noticing this, I am opening a internal task to handle this issue.
  We will come back as soon as we have news.

  Meanwhile feel free to make a PR, I will be glad to review it.

Thanks
