### ISSUE TITLE
[bitnami/rabbitmq] least privileges deployment

### ISSUE THREAD

**Issue by aleksf** [bitnami/charts#2227]
**Which chart**:
[bitnami/rabbitmq] - All versions

**Is your feature request related to a problem? Please describe.**
My current problem is that rabbitmq chart deployment requires clusteradmin role binding as it depends on RBAC config it creates. **rbacEnabled** option is rather confusing - when false is specified, Pod keeps crashing as it requires endpoint-reader  for peer discovery to form cluster:
```
2020-04-05 08:07:42.425 [info] <0.280.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
2020-04-05 08:07:42.425 [info] <0.280.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
2020-04-05 08:07:42.425 [info] <0.280.0> Peer discovery backend does not support locking, falling back to randomized delay
2020-04-05 08:07:42.426 [info] <0.280.0> Peer discovery backend rabbit_peer_discovery_k8s supports registration.
2020-04-05 08:07:42.426 [info] <0.280.0> Will wait for 893 milliseconds before proceeding with registration...
2020-04-05 08:07:43.351 [error] <0.280.0> Failed to fetch a list of nodes from Kubernetes API: 403
2020-04-05 08:07:43.354 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 0 neighbours exited with reason: no case clause matching {error,"403"} in rabbit_mnesia:init_from_config/0 line 140 in application_master:init/4 line 138
2020-04-05 08:07:43.354 [info] <0.44.0> Application rabbit exited with reason: no case clause matching {error,"403"} in rabbit_mnesia:init_from_config/0 line 140
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"403\"}},[{rabbit_mnesia,init_from_config,0,[{file,\"src/rabbit_mnesia.erl\"},{line,140}]},{rabbit_mnesia,init_with_lock,3,[{file,\"src/rabbit_mnesia.erl\"},{line,120}]},{rabbit_mnesia,init,0,[{file,\"src/rabbit_mnesia.erl\"},{line,87}]},{rabbit_boot_steps,'-run_step/2-lc$^0/1-0-',2,[{file,\"src/rabbit_boot_steps.erl\"},{line,50}]},{rabbit_boot_steps,run_step,2,[{file,\"src/rabbit_boot_steps.erl\"},{line,55}]},{rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,28}]},{rabbit_boot_steps,run_boot_steps,1,[{file,\"src/rabbit_boot_steps.erl\"},{line,29}]},{rabbit,start,2,[{file,\"src/rabbit.erl\"},{line,1011}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,"403"}},[{rabbit_mnesia,init_from_config,0,[{file
Crash dump is being written to: /opt/bitnami/rabbitmq/var/log/rabbitmq/erl_crash.dump...done
```
 In my case I only need one instance of RabbitMQ. Developers should be able to control deployment via CI/CD. RabbitMQ is the only chart in my deployment pipeline that requires namespace admin to be deployed. All other charts I am using deploy without requiring clusteradmin. 

**Describe the solution you'd like**
Allow rabbitmq chart deployment without rbac for single-node development instances. 

**Describe alternatives you've considered**
An official Helm repo chart suffers same problem - https://github.com/helm/charts/tree/master/stable/rabbitmq

**Additional context**
N/A

**Comment by miguelaeh** [comment]
Hi @aleksf ,
RBAC is needed for RabbitMQ to be able to query the Kubernetes API from inside the cluster for the peer discovery feature. That feature is optional.
If you want to use a single instance, and because of that you don't want the peer discovery I would give a try to override the `rabbitmq.plugins` of the Chart that is by default `rabbitmq_management rabbitmq_peer_discovery_k8s` and delete the `rabbitmq_peer_discovery_k8s` so it doesn't need to use RBAC.

**Comment by mrybas** [comment]
Hi @miguelaeh, 
your solution does not working for me
My values.yaml

```
rabbitmq:
  erlangCookie: "RABBITMQ_ERLANG_COOKIE"
  username: "RABBITMQ_USER"
  password: "RABBITMQ_PASS"
  rbacEnabled: false
  plugins: "rabbitmq_management"
  persistence:
    enabled: true
    storageClass: cephrbd
    accessModes: ["ReadWriteOnce"]
    size: 25G
```
but helm ignores this changes
`helm2 template rabbitmq`

```
# Source: charts/rabbitmq/templates/configuration.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-rabbitmq-config
  namespace: default
  labels:
    app: rabbitmq
    chart: rabbitmq-6.25.4
    release: "release-name"
    heritage: "Tiller"
data:
  enabled_plugins: |-
    [rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap].
  rabbitmq.conf: |-
    ##username and password
    default_user=user
    default_pass=CHANGEME
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    # queue master locator
    queue_master_locator=min-masters
    # enable guest user
    loopback_users.guest = false
    #disk_free_limit.absolute = 50MB
    #management.load_definitions = /app/load_definition.json
```

**Comment by miguelaeh** [comment]
Hi @mrybas ,
Are you passing your `values.yaml` to th helm template command? 
I tried to reproduce your issue with no luck:
```
helm2 template bitnami/rabbitmq --set rabbitmq.rbacEnabled=false,rabbitmq.plugins=nonexistent
```
And this is the output:
```
# Source: rabbitmq/templates/configuration.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-rabbitmq-config
  namespace: macabrera
  labels:
    app: rabbitmq
    chart: rabbitmq-6.25.5
    release: "release-name"
    heritage: "Tiller"
data:
  enabled_plugins: |-
    [nonexistent, rabbitmq_auth_backend_ldap].
```
As you can see it is the plugin I set plus the `rabbitmq_auth_backend_ldap`, but there is not `rabbitmq_peer_discovery_k8s`

**Comment by mrybas** [comment]
yes, my fault is the wrong configuration, thanks

**Comment by miguelaeh** [comment]
So, is it working now?

**Comment by mrybas** [comment]
Yes, now everything works for me.  Thanks

**Comment by aleksf** [comment]
@miguelaeh, It appears problem is k8s peer discovery cm content is not updated when **rabbitmq_peer_discovery_k8s** plugin is removed/not specified, as a result proposed overrides alone don't have an effect as cm still refers to rabbit_peer_discovery_k8s as cluster formation protocol:

**Chart install steps:**
```
 $ helm fetch bitnami/rabbitmq --untar
 $ cd rabbitmq
 $ helm install bitnamirabbit --set rbacEnabled=false,rabbitmq.plugins=rabbitmq_management .
```

**CM values post-override:**
```
apiVersion: v1
data:
  enabled_plugins: '[rabbitmq_management, rabbitmq_auth_backend_ldap].'
  rabbitmq.conf: |-
    ##username and password
    default_user=user
    default_pass=CHANGEME
    ## Clustering
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
...
```
**Pod logs:**
```
 BOOT FAILED
===========

Config file generation failed:
05:42:32.609 [error] You've tried to set cluster_formation.k8s.host, but there is no setting with that name.
05:42:32.609 [error]   Did you mean one of these?
05:42:32.660 [error]     cluster_formation.dns.hostname
05:42:32.660 [error]     cluster_formation.node_type
05:42:32.660 [error]     cluster_partition_handling
05:42:32.660 [error] You've tried to set cluster_formation.node_cleanup.interval, but there is no setting with that name.
05:42:32.660 [error]   Did you mean one of these?
05:42:32.733 [error]     cluster_formation.node_type
05:42:32.733 [error]     cluster_formation.dns.hostname
05:42:32.733 [error]     cluster_keepalive_interval
05:42:32.733 [error] You've tried to set cluster_formation.node_cleanup.only_log_warning, but there is no setting with that name.
05:42:32.733 [error]   Did you mean one of these?
05:42:32.822 [error]     cluster_formation.node_type
05:42:32.822 [error]     cluster_formation.dns.hostname
05:42:32.822 [error]     cluster_formation.peer_discovery_backend
05:42:32.826 [error] Error generating configuration in phase transform_datatypes
05:42:32.826 [error] Conf file attempted to set unknown variable: cluster_formation.node_cleanup.only_log_warning
05:42:32.826 [error] Conf file attempted to set unknown variable: cluster_formation.node_cleanup.interval
05:42:32.826 [error] Conf file attempted to set unknown variable: cluster_formation.k8s.host
In case the setting comes from a plugin, make sure that the plugin is enabled.
Alternatively remove the setting from the config.
```

It works after commenting rabbitmq.configuration, commenting following lines specifically:
```
    #cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    #cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    #cluster_formation.node_cleanup.interval = 10
    #cluster_formation.node_cleanup.only_log_warning = true
    #cluster_partition_handling = autoheal
```

**Comment by mrybas** [comment]
@aleksf try to redefine the section `configuration `.
```  
rabbitmq:
    configuration: |-
```
because the cluster is declared in standard values.yaml
or add --set rabbitmq.configuration=
```
helm2 template . --set rbacEnabled=false,rabbitmq.plugins=rabbitmq_management,rabbitmq.configuration= | less

**Comment by miguelaeh** [comment]
Hi, 
> It appears problem is k8s peer discovery cm content is not updated when rabbitmq_peer_discovery_k8s plugin is removed/not specified

Maybe your use case is not the same? If you need to create a cluster and you need the peer discovery you should not disable that plugin. Maybe I didn't catch your point. 
In your first comment you said you only need one node so why do you need the peer discovery?
>In my case I only need one instance of RabbitMQ.

Could you explain a bit more your scenario?

**Comment by imurvai** [comment]
Hi,
I have the same issue as the original one, after installing the bitnami/rabbitmq chart I'm getting the followings in our K8S cluster:

2020-12-16 12:39:10.409 [info] <0.269.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
2020-12-16 12:39:10.425 [info] <0.269.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
2020-12-16 12:39:10.425 [info] <0.269.0> Peer discovery backend does not support locking, falling back to randomized delay
2020-12-16 12:39:10.425 [info] <0.269.0> Peer discovery backend rabbit_peer_discovery_k8s supports registration.
2020-12-16 12:39:10.425 [info] <0.269.0> Will wait for 1193 milliseconds before proceeding with registration...
2020-12-16 12:39:11.643 [error] <0.269.0> Failed to fetch a list of nodes from Kubernetes API: 403
2020-12-16 12:39:11.645 [error] <0.269.0> Peer discovery returned an error: "403". Will retry after a delay of 500 ms, 9 retries left...

even though I've added this in my values.yaml file:

plugins: "rabbitmq_management"

So that the peer discovery should be turned off.
I also checked the pod's yaml in Rancher and found this:

    - name: RABBITMQ_PLUGINS
      value: rabbitmq_management, rabbitmq_auth_backend_ldap

It suggests me that the peer discovery is really not enabled but at startup rabbitmq still tries to discover peers.
Is there anything I'm doing wrong?

**Comment by miguelaeh** [comment]
Hi @imurvai ,

It seems that issue is the configuration section. Even deleting the plugin form the list it is being used in the configuration:
```
configuration: |-
  ## Username and password
  default_user = {{ .Values.auth.username }}
  default_pass = CHANGEME
  ## Clustering
  cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
  cluster_formation.k8s.host = kubernetes.default.svc.{{ .Values.clusterDomain }}
  cluster_formation.node_cleanup.interval = 10
  cluster_formation.node_cleanup.only_log_warning = true
  cluster_partition_handling = autoheal
```

Could you try to remove those lines and try again?

**Comment by imurvai** [comment]
Hi @miguelaeh ,
I copied the configuration section form the original values.yaml into my values.yaml file without the clustering settings and now it's working.
Thanks for your help.

**Comment by miguelaeh** [comment]
I am glad it finally worked! Thanks for the answer!

**Comment by FurkanSalih** [comment]
Values of `plugin` and `cluster_formation.peer_discovery_backend` are different. One of them is `rabbitmq_peer_discovery_k8s ` and the other is `rabbit_peer_discovery_k8s`. Is this bug or something?

**Comment by miguelaeh** [comment]
Hi @FurkanSalih ,
I just checked it and it seems to be correct. the pluggin name seems to be different from the `discovery_backend`.
https://www.rabbitmq.com/cluster-formation.html -> check here the `rabbit_peer_discovery_k8s`
https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s -> check here the plugin name

**Comment by manisha-tanwar** [comment]
Hi, I'm also facing the same issue and removing clustering from configuration fixed it for me.
But I would like to setup cluster with `replica:3`,  is it possible to configure it without roles access on K8 API?

**Comment by miguelaeh** [comment]
Hi @manisha-tanwar ,
I think you are talking about deploying RabbitMQ in cluster mode without RBAC. RabbitMQ needs RBAC for peer discovery so it is not possible unless you find another way to discover peers. You can check this comment https://github.com/bitnami/charts/issues/2227#issuecomment-609686661

**Comment by manisha-tanwar** [comment]
Thanks @miguelaeh 
Get serviceaccount created with attached rolebinding. & It worked fine without any configuration changes. This is what I've now:
```
  rbac:
    create: false
  serviceAccount:
    create: false
    name: rabbitmq-ha
    automountServiceAccountToken: true
 ```
 
 Thanks again for the help!

**Comment by miguelaeh** [comment]
You're welcome!

**Comment by pmorch** [comment]
Like the OP,
> In my case I only need one instance of RabbitMQ

When looking at the chart's default values.yaml file, I saw that the problematic parts of the configuration can be disabled by:
`clustering.enabled=false`, so an absolute minimal RabbitMQ installation that doesn't require any extra privileges can be done with:

```
helm install my-release --set auth.username=admin,auth.password=admin,rbac.create=false,clustering.enabled=false bitnami/rabbitmq
```

Since the configuation no longer references the problematic plugin, my testing hasn't shown a need to disable it.

If then later we need to expand to multiple RabbitMQ nodes, we can get an admin to create the service account for us, and then reference it like @manisha-tanwar does in https://github.com/bitnami/charts/issues/2227#issuecomment-784047894

**Comment by miguelaeh** [comment]
Hi @pmorch ,
Thank you very much for sharing your approach!
