### ISSUE TITLE
[bitnami/minio] Install fails if Prometheus is not installed and ServiceMonitor is enabled

### ISSUE THREAD

**Issue by cmontemuino** [bitnami/charts#22365]
### Name and Version

bitnami/minio 13.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create a brand new Kubernetes cluster
2. `helm install my-release oci://registry-1.docker.io/bitnamicharts/minio --version 13.1.1 --set metrics.serviceMonitor.enabled=true`

### What is the expected behavior?

The ServiceMonitor resource should be skipped. Prometheus CRD is not avaialble.

### What do you see instead?

Helm install fails because `monitoring.coreos.com/v1` is not available.

### Additional information

This could be solved by checking prometheus's apiVersion is available with `.Capabilities.APIVersions.Has` function.
```

**Comment by cmontemuino** [comment]
I can contribute with a PR if that helps.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
