### ISSUE TITLE
[bitnami/mongodb] override namespace through values.yaml

### ISSUE THREAD

**Issue by benjamin-wright** [bitnami/charts#2243]
**Which chart**:
mongodb

**Is your feature request related to a problem? Please describe.**
We are trying to put together a chart for shared infrastructure running in each of our environment clusters, it would be great to be able to deploy dependency charts into their own namespaces, so that a single chart could deploy multiple components.

**Describe the solution you'd like**
Ideally, I could add configuration such as:

```yaml
mongodb:
  namespaceOverride: mongo
```

to the `values.yaml` in my umbrella chart, to direct the `mongodb` dependency to install into its own namespace. This is a similar approach to the one taken in the `jenkins` and `prometheus` charts in stable:

https://github.com/helm/charts/pull/18986
https://github.com/helm/charts/pull/15202

**Describe alternatives you've considered**
Without the proposed change, the only alternative I can think of is to install the individual components separately, through some kind of custom script or additional tooling. This would work, of course, but you either lose the description of your environment in a single declarative format, or pay the cost of the additional complexity in purchasing, acquiring or developing and maintaining the extra tooling. It's not much, but if helm can do it already then why bother?

**Comment by benjamin-wright** [comment]
I have a fork where I've implemented what I think is needed, will raise a PR shortly!

**Comment by miguelaeh** [comment]
Hi @benjamin-wright ,
Thank you very much for the suggestion, we really appreciate that kind of improvement.
We will wait for your PR!! Thank you very much!!
