### ISSUE TITLE
[bitnami/postgresql] slave pod authentication fails when replica field is update to true. 

### ISSUE THREAD

**Issue by gane5hvarma** [bitnami/charts#2244]
**Which chart**:
The name (and version) of the affected chart
name: postgresql
version: 7.7.2
**Describe the bug**
slave pod authentication fails after we do helm upgrade with replica set to true. works fine if replica is set true at first release. but if we install a fresh release with replica set to false, dump some data to pg and then upgrade the release with replica set to true

**To Reproduce**
1. install this  postgresql chart with replication.enabled false
2. dump some data to pg
3. update the release by setting replication.enable true
4. then by seeing logs of slave pod, error - pg_basebackup: could not connect to server: FATAL:  password authentication failed for user "repl_user"

Doubt: what if master db has some data, after enabling replication will the data will automatically flow into slave or we should manually migragte it ?

**Comment by juan131** [comment]
Hi @gane5hvarma 

Did you explicitly set the PostgreSQL password when installing/upgrading the chart? As it's explained in the README.md (see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#upgrade) it's necessary to do so to avoid secrets to be populated with randomly created passwords that are not sync with the original ones.

**Comment by gane5hvarma** [comment]
Hi @juan131 I have explicitly set the password when installing, upgrading. I have found a workaround. After updating the chart i have manually added slave replica user to master db. seems like the initdb scripts are not checking for new users if the user data is already present in the disks. I need help to add slave replica user to master db automatically.

**Comment by juan131** [comment]
Hi @gane5hvarma 

> After updating the chart i have manually added slave replica user to master db

Why did you manually added a new replica user? Why not relying on the user automatically created when installing the chart with replication enabled?
Could you please provide more information about this?

> Seems like the initdb scripts are not checking for new users if the user data is already present in the disks

Initdb scripts should only be executed in the "master" nodes, since these are the nodes with "write" permissions.

**Comment by gane5hvarma** [comment]
Hi @juan131, what i mean to say is i have installed the chart without enabling replication. and then i have loaded some data to postgres. and then i have updated the release with enabling replication. also i want master to use above pvc which.

**Comment by juan131** [comment]
Hi @gane5hvarma 

I am afraid it is not possible to install the chart without replication, and then upgrade the release enabling replication. The chart does not support this approach.

To enable replication, you need to install a new release enabling it from the very beginning. Then, you can try to migrate the PostgreSQL database that you are interested on keeping using backup/restore features (see https://docs.bitnami.com/general/infrastructure/postgresql/administration/backup-restore-postgresql for more information).

**Comment by gane5hvarma** [comment]
Hi @juan131 

but I was able to do replication after updating the chart with replication enabled and by manually adding replica user to master DB with role replication. Doing this lets you sync slave DB with master DB.

**Comment by juan131** [comment]
Hi @gane5hvarma 

Yes, you can sync slave pods with master using a custom replica user. However, when you install a release without replication, and then you upgrade it enabling replication, there will be other inconsistencies (like labels for instance). That's why we DO NOT recommend to follow this approach.

As I said, we do not support upgrading the chart this way, and we highly recommend to migrate the data when you want to add replication to an exiting release without replication.

**Comment by gane5hvarma** [comment]
Hi @juan131 
i have handled the inconsistencies by changing labels in the deployment file to make sure it works end to end.

**Comment by juan131** [comment]
Great @gane5hvarma ! 

Please do not hesitate to let us know if you require further help with this chart.
