### ISSUE TITLE
[Cassandra Chart] storage_port and seeds can't be overridden in helm chart

### ISSUE THREAD

**Issue by yury-kozlov** [bitnami/charts#2245]
**Which chart**:
cassandra, 5.2.0

**Is your feature request related to a problem? Please describe.**
I'm looking for a solution to deploy Cassandra multi-node cluster, where nodes are not hosted on the same kubernetes cluster, and thus require access via public IP and custom transport port (other than default 7000).
I see that bitnami-cassandra docker image provides such variables: CASSANDRA_SEEDS and CASSANDRA_TRANSPORT_PORT_NUMBER, but there's no way to override them in the helm chart.

**Describe the solution you'd like**
It would be great if I can provide my own list of seed IP addresses and a custom storage_port instead of 7000.

**Describe alternatives you've considered**
I'm new to helm and k8s, and I would appreciate if you advise alternative solutions, As of now I'm thinking of adjusting your chart to my needs manually.

**Comment by miguelaeh** [comment]
Hi @yury-kozlov ,
Thank you for the feedback. 
To add that feature it is needed to add the env vars to the Statefulset and the parameters to the values.yaml, also add them to the README.md and bump the minor version.
Would you like to create a PR for that purpose? We will be happy to review it.
