### ISSUE TITLE
[bitnami/airflow] Unable to Access Python Virtual Environment After Git Sync / Airflow

### ISSUE THREAD

**Issue by Katoo2706** [bitnami/charts#22476]
### Name and Version

bitnami/airflow

### What architecture are you using?

None

### Hi everyone,

I'm encountering an issue with accessing the Python virtual environment after using Git Sync to deploy Airflow. The problem arises when attempting to access the container and the Python virtual environment, resulting in the following error:

`bash: /opt/bitnami/airflow/venv/bin/activate: No such file or directory`

Upon further investigation, I discovered that the dags folder is located in the root folder of the container, which is synced from the Git repository. The expected location of the dags folder after mounting is: /opt/bitnami/airflow/dags/git_data-warehouse/.

### What do you see instead?

`bash: /opt/bitnami/airflow/venv/bin/activate: No such file or directory`

**Comment by javsalgar** [comment]
Hi!

Do you have some sample values that trigger the issue?
