### ISSUE TITLE
enableS3 value missing from values.yaml & README

### ISSUE THREAD

**Issue by christian-nickerson-faculty** [bitnami/charts#22514]
### Name and Version

bitnami/milvus:5.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

when deploying with an external s3, the following parameters fail (in documentation):
```yaml
minio.enabled=false
externalS3.host=myexternalhost
exterernalS3.accessKeyID=accesskey
externalS3.accessKeySecret=secret
```

however, the chart is expecting in externals3-secret.yaml to be able to take the access credentials and create a secret from them when no existingSecret is present:
```yaml
{{- if and (not .Values.minio.enabled) (not .Values.externalS3.existingSecret) .Values.enableS3 }}
```

### Are you using any custom parameters or values?

```terraform
  set {
    name  = "externalS3.host"
    value = "https://${aws_s3_bucket.milvus_bucket.id}.s3.${var.region}.amazonaws.com"
  }
  set {
    name  = "externalS3.accessKeyID"
    value = aws_iam_access_key.milvus_s3_key.id
  }
  set {
    name  = "externalS3.accessKeySecret"
    value = aws_iam_access_key.milvus_s3_key.secret
  }
```

### What is the expected behavior?

the s3 secret credentials should be auto created

### What do you see instead?

the s3 secret credentials should be auto created

### Additional information

we got around this by passing the existing secret instead, however, this should be made clear in documentation / in values.yaml

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
