### ISSUE TITLE
[bitnami/nginx] Duplicate .spec.automountServiceAccountToken field in Pod template of NGINX deployment

### ISSUE THREAD

**Issue by DonaldKellett** [bitnami/charts#22517]
### Name and Version

bitnami/wordpress 15.9.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm pull bitnami/nginx --version 15.9.0 --untar
cd nginx/
helm template nginx . --show-only templates/deployment.yaml | \
    yq '.spec.template.spec' | \
    grep automountServiceAccountToken
```

### Are you using any custom parameters or values?

No, this bug is reproducible with the default Helm chart values.

### What is the expected behavior?

At most 1 line of output, e.g.

```yaml
automountServiceAccountToken: false
```

### What do you see instead?

2 lines of output, indicating a duplicate field:

```yaml
automountServiceAccountToken: false
automountServiceAccountToken: false
```

### Additional information

This is causing Flux v2 reconciliation failures with the NGINX Helm chart in our production Rancher RKE2 cluster.

![Screenshot from 2024-01-19 21-50-51](https://github.com/bitnami/charts/assets/7777884/328ff347-6471-4f22-8853-93bea25ec7f6)

**Comment by DonaldKellett** [comment]
Root cause: https://github.com/bitnami/charts/commit/2413d64624fa17ba0a13d737fd5fb6b432d8c5dd#diff-db03758781f6e1a8151dbbf46755d6339840b0ac71090576fe7e4e1941ebd5ffR41-R44

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by dominikkaminski** [comment]
@carrodher Added the same change as @DonaldKellett plus the removal of the `automountServiceAccountToken` in values (and README).

Now Pipeline is green and would be very nice if you could approve either @DonaldKellett or mine PR soon :)

Cheers :wave:

**Comment by uqix** [comment]
We need to downgrade to 15.8.1 before new release.
