### ISSUE TITLE
[bitnami/postgresql] fails to start with openshift 

### ISSUE THREAD

**Issue by gratinierer** [bitnami/charts#22511]
### Name and Version

bitnami/postgresql 13.3.1

### What architecture are you using?

None

### What steps will reproduce the bug?

on openshift deployment fails, when using 
```seLinuxOptions: {}``` 

### What is the expected behavior?

deployment succeeds.

### What do you see instead?

```
Forbidden: not usable by user or serviceaccount, provider restricted: .containers[0].seLinuxOptions.level: Invalid value: ""
```

### Additional information

setting ```seLinuxOptions: null``` fixes the issue.

**Comment by javsalgar** [comment]
Never mind, I'm creating PRs for all the catalog. Thanks for reporting
