### ISSUE TITLE
Clickhouse not starting when overriding namespace

### ISSUE THREAD

**Issue by shrenikgala** [bitnami/charts#22526]
### Name and Version

bitnamicharts/clickhouse

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm running following helm version on intel based mac.
```
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}
```

i've overriden the namespace parameter to be `clickhouse` and executed the following command, which runs into an error
```
helm install clickhouse-deployment --set replicaCount=2 --set shards=2 --set namespaceOverride=clickhouse  oci://registry-1.docker.io/bitnamicharts/clickhouse
```

```
Pulled: registry-1.docker.io/bitnamicharts/clickhouse:4.3.1
Digest: sha256:d0bc26c849e854e74fde31e0ae388c87b5aa91801b226f8d99d3a12ce200865d
Error: INSTALLATION FAILED: namespaces "clickhouse" not found
```
Couple of observations:
1) I also ran the same command in dry-run mode and templates are generating fine with the caveat that i see the yamls using namespace as `"clickhouse"` in quotes. Not sure if that's causing an issue
```
helm install clickhouse-deployment --set replicaCount=2 --set shards=2 --set namespaceOverride=clickhouse  oci://registry-1.docker.io/bitnamicharts/clickhouse --dry-run
```

2) Running the same helm command without `namespaceOverride` works fine and creates the deployment in `default` namespace

### Are you using any custom parameters or values?

```
helm install clickhouse-deployment --set replicaCount=2 --set shards=2 --set namespaceOverride=clickhouse  oci://registry-1.docker.io/bitnamicharts/clickhouse
```

### What is the expected behavior?

It should install clickhouse with the new namespace value provided

### What do you see instead?

```
Pulled: registry-1.docker.io/bitnamicharts/clickhouse:4.3.1
Digest: sha256:d0bc26c849e854e74fde31e0ae388c87b5aa91801b226f8d99d3a12ce200865d
Error: INSTALLATION FAILED: namespaces "clickhouse" not found
```

**Comment by shrenikgala** [comment]
Looks like it might be an issue of helm2 vs helm3 functionality ?

**Comment by carrodher** [comment]
Starting from Helm >= 3.2, you need to use `--create-namespace` in addition to `--namespace <namespace>`
