### ISSUE TITLE
[bitnami/clickhouse] cluster id not found

### ISSUE THREAD

**Issue by oomgomgxx** [bitnami/charts#22532]
### Name and Version

bitnami/clickhouse

### What architecture are you using?

None

### What steps will reproduce the bug?

helm install signoz: https://artifacthub.io/packages/helm/signoz/signoz

### What do you see instead?

Hello, please tell me how to set the id of the cluster. I am using this Chart to deploy a Clickhouse cluster and as external storage for SigNoz, but found that the cluster id is "default" (SigNoz Helm Chart requires the id to be "cluster"), and the property modification cannot be found.

<img width="527" alt="image" src="https://github.com/bitnami/charts/assets/58796445/5b8ed8f0-fd74-481e-907a-29958043b309">

**Comment by javsalgar** [comment]
Hi,

Did changing the `defaultConfigurationOverrides` as you showed in the image work?

**Comment by oomgomgxx** [comment]
> Hi,
> 
> Did changing the `defaultConfigurationOverrides` as you showed in the image work?

Manually modifying the label can achieve the purpose, but Chart does not provide the corresponding configuration property options. I hope that subsequent versions will provide

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input. I will forward this to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding the value? Something like `clusterName` and then it is used in the `defaultConfig` template
