### ISSUE TITLE
Why not use `docker.io/bitnamicharts` for OCI chart

### ISSUE THREAD

**Issue by dungdm93** [bitnami/charts#22530]
I just tested out:

```bash
$ helm template foobar oci://docker.io/bitnamicharts/mysql --version 9.18.0
Pulled: docker.io/bitnamicharts/mysql:9.18.0
Digest: sha256:464bb1d8027b7650472d363c234df2af9210410961c64b18753200367c794e5e
...
```

and
```bash
$ helm template foobar oci://registry-1.docker.io/bitnamicharts/mysql --version 9.18.0
Pulled: registry-1.docker.io/bitnamicharts/mysql:9.18.0
Digest: sha256:464bb1d8027b7650472d363c234df2af9210410961c64b18753200367c794e5e
...
```

both produce the same output.

So why don't we use `docker.io` instead of `registry-1.docker.io`. I think it's shorter and look much nicer.

**Comment by carrodher** [comment]
Hi, thanks for your question.
When we implemented Helm charts in DockerHub as OCI packages it was the very beginning of OCI support in DockerHub and the documentation we received was pointing to `registry-1.docker.io`, for instance, the blog post they published announcing OCI support is referring everywhere to `registry-1.docker.io`, see https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/.

In the same way, that's the command suggested by DockerHub to pull the Helm charts, see https://hub.docker.com/r/bitnamicharts/mysql
<img width="1418" alt="Screenshot 2024-01-20 at 18 53 34" src="https://github.com/bitnami/charts/assets/13216600/69bc26bc-b816-4899-b6e5-3710f631662b">

**Comment by dungdm93** [comment]
@carrodher Thanks for your info.
So I think we should work with Docker Hub first.
