### ISSUE TITLE
（bitnami/fluent-bit）Does "daemonset.hostPaths" support multiple paths? Because now I find that logs only mounts one path "/var/log", but I think it is also necessary to collect other paths at the same time. How should the request be configured?

### ISSUE THREAD

**Issue by oomgomgxx** [bitnami/charts#22533]
### Name and Version

bitnami/fluent-bit

### What architecture are you using?

None

### What steps will reproduce the bug?

Found that logs only mounts one path "/var/log"

### What do you see instead?

Does "daemonset.hostPaths" support multiple paths? Because now I find that logs only mounts one path "/var/log", but I think it is also necessary to collect other paths at the same time. How should the request be configured?

**Comment by opencmit2** [comment]
Hi @oomgomgxx 
Refer to the documentation below.
https://github.com/bitnami/charts/blob/main/bitnami/fluent-bit/values.yaml#L248
https://github.com/bitnami/charts/blob/main/bitnami/fluent-bit/values.yaml#L433
