### ISSUE TITLE
[bitnami/redis] Use sentinel client side

### ISSUE THREAD

**Issue by Hackatosh** [bitnami/charts#22539]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

In the Redis documentation, it is possible to use sentinel "client side" (https://redis.io/docs/management/sentinel/ => Example 3: Sentinel in the client boxes). This means that it is not mandatory to use a full Redis Instance along side each sentinel, which consumes less resources.

![image](https://github.com/bitnami/charts/assets/37976573/aa3e9533-8520-4472-926e-fcc964201bb3)

### What is the feature you are proposing to solve the problem?

Allow the use of "client side sentinel" with the chart. I don't think it's possible at the moment

**Comment by andresbono** [comment]
Hi, thank you for opening this issue. I'm not sure if configuring the sentinels in a "client side" way would make sense for this generic chart. We don't have control over the wide variety of use-cases our users can have...

Having said that, for the sake of resource optimization, a user suggested if it would be possible to split master/replica and sentinels in different pod configurations so they could be scaled independently as well as setting different resource constraints to each of them: https://github.com/bitnami/charts/issues/17038. The suggestion is still being evaluated but just sharing it with you in case.
