### ISSUE TITLE
[bitnami/redis-cluster]: Allow templating on existingSecret param

### ISSUE THREAD

**Issue by joelact** [bitnami/charts#22549]
### Name and Version

bitnami/redis-cluster 9.3.0

### What is the problem this feature will solve?

At this time, templating is not allowed on existingSecret parameter, which is not very flexible.

### What is the feature you are proposing to solve the problem?

add tpl function to the helpers file

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input. Would you like to submit a PR adding support for templating the variable?

**Comment by joelact** [comment]
Hey!
Sure, thanks for your feedback.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
