### ISSUE TITLE
[bitnami/postgresql] Please add serviceaccount field to pgdump backup cronjob template

### ISSUE THREAD

**Issue by szpeter80** [bitnami/charts#22564]
### Name and Version

bitnami/postgresql 13.4.0

### What is the problem this feature will solve?

The backup job has no option to specify which serviceaccount to use, so it will use the default. On Openshift, the default settings are too restrictive for postgres and pgdump to start. While the server has a field to set serviceAccountName, the backup job currently missing this feature.

### What is the feature you are proposing to solve the problem?

Please add a serviceAccountName field to backup cron job template and a corresponding entry in the backup section in values-default.yaml. The default value for this key, as i understand, is "default" in Kubernetes.

### What alternatives have you considered?

There is no alternative. If you want the backup job to run under Openshift, either you have to disable securtiy controls or disable the backup section of the chart and you add a cronjob resource outside the chart deployment workflow. Maintining this "dangling" resource is error prone, eg. continously check for image version changes in chart and update its pod spec accordingly

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by alexey-ban** [comment]
This request is also interesting in connection with working with azure file csi driver via workload identity

**Comment by carrodher** [comment]
Thanks for the follow-up. As mentioned, if you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines

Feel free to reach out if you have any questions or need assistance.
