### ISSUE TITLE
[Prestashop] Parameterize liveness and readiness probe path

### ISSUE THREAD

**Issue by juanpmarin** [bitnami/charts#2261]
**Which chart**:
prestashop  9.1.12

**Is your feature request related to a problem? Please describe.**
The path of the probes should be parameterizable because the /login path does not exist on another prestashop supported languages, for example in spanish it is /iniciar-sesion

**Describe the solution you'd like**
Create a parameter for liveness probe path and readiness probe path

**Comment by carrodher** [comment]
I just created this PR implementing this feature. Thanks for using our chart!
