### ISSUE TITLE
deepCopy not defined

### ISSUE THREAD

**Issue by hatharom** [bitnami/charts#2266]
**Which chart**:
postgresql

**Describe the bug**
Wait helm template failed: Error: parse error in "mychart/charts/postgresql/templates/svc.yaml": template: mychart/charts/postgresql/templates/svc.yaml:1: function "deepCopy" not defined : exit status 1

**To Reproduce**
Pushed to repo and refreshed rancher catalog and redeployed

**Version of Helm and Kubernetes**:

- Output of `helm version`:
2.14.3-rancher1

- Output of `kubectl version`:
Client 1.16,  Server 1.17

**Context**
On my local machinbe using minikube (helm:2.16 , kubectl client 1.15, server 1.18) it works fine.

Versions are just fine imo, because chart requirement states: 
```
Prerequisites
    Kubernetes 1.12+
    Helm 2.11+ or Helm 3.0-beta3+
    PV provisioner support in the underlying infrastructure
```

Where does this 'deepCopy' comes from? It was added 2 days ago into the postgresql chart.

**Comment by juan131** [comment]
Hi @hatharom 

You're using a pretty old version of Helm, `deepCopy` is a function that was introduced in Helm 2.16. However, as you mentioned the prerequisites were not properly updated when we introduced the use of this function.

That said, regardless I strongly encourage to upgrade to `Helm 3` (or `Helm 2.16+` if Helm3 is not a possibility for you), I opened a PR to use an alternative to this function. The code is cleaner using `deepCopy`, but at least it's compatible with `Helm 2.11+`.
