### ISSUE TITLE
Procedure missing to enable TLS in bitnami ElasticSearch Helm chart 7.6.2 

### ISSUE THREAD

**Issue by Abu0108** [bitnami/charts#2268]
Elasticsearch - Secure Connections (SSL/HTTPS)

We are using bitnami ElasticSearch helmChart 7.6.2 from helm hub, but we are unable to enable TLS as we dont find any clear documentation. Can you please provide these details. 

We want to integrate with bitnami Kibana TLS.

**Comment by rafariossaa** [comment]
Hi @Abu0108 ,
   I am sorry, currently that feature is not supported, the reason is that to enable it  x-pack extension needs to be integrated in the container.

**Comment by Abu0108** [comment]
@rafariossaa Thank you for the confirmation. Any update on when it shall be made available.

**Comment by rafariossaa** [comment]
@Abu0108  Sorry, not by now.

**Comment by rafariossaa** [comment]
Hi, if there is not more comments on this, I will be closing the issue.
