### ISSUE TITLE
Bitnami Kafka helm chart configuration to override compression.type topic level setting

### ISSUE THREAD

**Issue by nimeshpsharma** [bitnami/charts#22691]
### Name and Version

bitnami/kafka-21.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install kafka helm chart with the configuration defined in value.yaml file 
2. contents of values.yaml with configuration defined as `compression.type` to override existing topic configuration
```yaml
kafka:
  compression.type: "gzip"
  numPartitions: 5
  deleteTopicEnable: true
```
3. Create a new topic in kafka container
4. Check the configuration for `compression.type` on a created topic

### What is the expected behavior?

Topic should be created with `compression.type` as gzip

### What do you see instead?

Topic configuration is not showing `compression.type` and it's set as default with producer setting as NONE

### Additional information

Is there any separate configuration to override the ' compression.type` setting on a topic?

**Comment by migruiz4** [comment]
Hi @nimeshpsharma,

Please note that `compression.type` is a Kafka setting, while you are setting a Chart setting.
If you would like to set additional Kafka settings through the chart settings, you may need to use the `extraEnvVars` value to set the environment variable `KAFKA_CFG_COMPRESSION_TYPE`.

Additionally, please note that version 21.x.x of the bitnami/kafka chart was last released 9 months ago, and the next releases include major changes affecting Kafka configuration settings values such as `kafka.deleteTopicEnable`.
