### ISSUE TITLE
[bitnami/redis-cluster] external ip in load balancer is always pending

### ISSUE THREAD

**Issue by lijian12345** [bitnami/charts#22697]
### Name and Version

bitnami/redis-cluster 9.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In k8s within docker desktop for windows, when setting cluster.externalAccess.enabled=true, then the chart will create 6 load balancers, and creating external ip for them. 
2. But the truth is only 1 load balance can create a external ip called "localhost", the other 5 are always pending, as we can see in this pic:
![image](https://github.com/bitnami/charts/assets/26590220/e54af269-f419-4084-b6d3-f37eadeeedee)

### Are you using any custom parameters or values?

cluster.externalAccess.enabled=true

### What is the expected behavior?

external ip can be successfully created

### What do you see instead?

external ip is always pending

**Comment by javsalgar** [comment]
Hi,

It seems that your cluster does not have support for creating external LoadBalancer IPs. You would need to move to a k8s cluster that has support for it.

**Comment by lijian12345** [comment]
> Hi,
> 
> It seems that your cluster does not have support for creating external LoadBalancer IPs. You would need to move to a k8s cluster that has support for it.

Thx for ur reply! It seems that k8s within the docker desktop has some issues, maybe I should change to minikube to have a experiment.

**Comment by lijian12345** [comment]
> Hi,
> 
> It seems that your cluster does not have support for creating external LoadBalancer IPs. You would need to move to a k8s cluster that has support for it.

Today I had some new discoveries. I deployed istio and bookinfo example apps, found that it can be accessed through istio ingress gateway(LoadBalancer type). That means in fact it has support for LoadBalancer type, as seen in the pic:
![image](https://github.com/bitnami/charts/assets/26590220/a4a13e19-24a5-4746-acc5-ea9fbaa602a6)
So the problem may occur in somewhere else.

**Comment by javsalgar** [comment]
From what I see in the first picture, it seems to only support one load balancer IP (localhost), I would check with Docker Desktop to see how this can be done.

**Comment by lijian12345** [comment]
> From what I see in the first picture, it seems to only support one load balancer IP (localhost), I would check with Docker Desktop to see how this can be done.

very thx!
