### ISSUE TITLE
[bitnami/mlflow]: automountServiceAccountToken has been moved

### ISSUE THREAD

**Issue by angegar** [bitnami/charts#22694]
### Name and Version

bitnami/mlflow:0.6.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy the chart version 0.3.0
Upgrade the chart to version 0.6.0
Deployment fails

### What do you see instead?

Service account permission issues

### Additional information

The root cause is that the automountServiceAccountToken has been moved out of the serviceAccountSection to be place in :** {{ .Values.tracking.automountServiceAccountToken }}**

The chart version has been incremented with a minor whereas I think it should be a major because the user interface changed.

**Comment by javsalgar** [comment]
Hi!

Could you explain the use case? Are you using mlflow with some sort of Kubernetes integration?

**Comment by angegar** [comment]
Yes sorry,

I am using mlfow helm chart, and the configuration field automountServiceAccountToken  has been moved from the tracking.serviceAccount section to the tracking one. Thus, I guess it is a breaking change.

**Comment by javsalgar** [comment]
Hi, 

We did not update the minor version because in the original chart we were not mounting the service account token. However, could you let us know why you require the SA token to be in the pod? We can revert the change and then bump the major version again. If you want to speed up the process, you can submit a PR and we will review it.

**Comment by angegar** [comment]
It is because I spin up infrastructure such as a PostGreSQL. The infrastructure is managed with GCP config connector so that I need to be able request the object status in an init container before starting mlflow.
