### ISSUE TITLE
[bitnami/kafka ] Auto Scaling 

### ISSUE THREAD

**Issue by moinologics** [bitnami/charts#22733]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Auto Scaling as per load

### What is the feature you are proposing to solve the problem?

Horizontal Pod Autoscaler

I need information/examples on how to properly deploy auto Scaling using hpa, if this can be achieved already

**Comment by carrodher** [comment]
Unfortunately, there is not an option to set HorizontalPodAutoscaler in the Kafka Helm chart.

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
