### ISSUE TITLE
DAG Git not working 

### ISSUE THREAD

**Issue by asaklex** [bitnami/charts#2273]
**Which chart**:
bitnami/airflow 1.10.9

**Describe the bug**
I'm getting this error:
`error: a container name must be specified for pod megaflow-airflow-worker-0, choose one of: [git-repo-syncer airflow-worker] or one of the init containers: [git-clone-repository]`

This error occurs if  airflow.cloneDagFilesFromGit.enabled  = true with a dag repository.

**To Reproduce**
1. create values config with airflow.cloneDagFilesFromGit.enabled = true + repository + branch
2. `helm install megaflow -f values.yml  bitnami/airflow`
3. Inspect logs of the airflow worker pod `kubectl logs pod/worker-podname`

**Expected behavior**
airflow should work with git enabled for Dags

**Version of Helm and Kubernetes**: 1.17

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-27T12:32:23Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Issue can be observed with web / scheduler / worker

PS: I m using  private repository with token

**Comment by asaklex** [comment]
Issue is related to kubernetes pod  with multiple containers . 
By providing the container name , the issue is fixed, and we are able to read the logs of the container 
`kubectl logs pod/megaflow-airflow-web-6dfcf4b547-p6r65 -c airflow-web -n airflow
`

**Comment by rafariossaa** [comment]
Hi @asaklex ,
  Thanks for reporting your findings. 

Best regards

**Comment by ecda909** [comment]
How did you all provide the container name?
