### ISSUE TITLE
apache_exporter failed to start

### ISSUE THREAD

**Issue by yeouchien** [bitnami/charts#2274]
**Which chart**:
wordpress 9.1.3

**Describe the bug**
`apache_exporter` failed to start with error
`apache_exporter: error: unknown short flag '-s', try --help`

**To Reproduce**
`helm install my-release bitnami/wordpress` with values
```
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.8.0-debian-10-r3
```

**Expected behavior**
`apache_exporter` run without error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
According to the README in https://github.com/Lusitaniae/apache_exporter , the correct way to use apache_exporter is `--scrape` but in https://github.com/bitnami/charts/blob/8f3b7cea39cd7994156a5f251f0dce1c0bb3e51e/bitnami/wordpress/templates/deployment.yaml#L185-L188
it's using `-scrape`

**Comment by Mauraza** [comment]
Hi @yeouchien,

I've been able to reproduce it, let's work on it. We'll update this thread when it's fixed. 

Thank you for reporting it.
