### ISSUE TITLE
Memcached HA always out of sync in ArgoCD

### ISSUE THREAD

**Issue by figaw** [bitnami/charts#22743]
### Name and Version

bitnami/memcached 6.9.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Statefulset template renders `replicas` when autoscaling is enabled.

A helm template which uses a horizontalPodAutoscaler shouldn't define "replicas" in a `deployment` or `statefulset`.

The other half of #8390 

ArgoCD explains it here: https://argo-cd.readthedocs.io/en/stable/user-guide/best_practices/#leaving-room-for-imperativeness

### Are you using any custom parameters or values?

```yaml
architecture: high-availability
autoscaling:
  enabled: true
```

### What is the expected behavior?

Statefulset doesn't define a set number of replicas, so the HPA will manage it instead.

### What do you see instead?

Statefulset defines a set number of replicas, incidentally making ArgoCD constantly terminate the pods that the HPA scales up.

### Additional information

Firstly: like with #8390 the issue only strictly arises when we combine the chart with ArgoCD (or perhaps some other gitops client..), but if you create a new helm-chart, the `replicas` in the `deployment.yaml` is also guarded:

```yaml
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
```

So it's good practice not to include it.

Secondly: I didn't make changes to the `deployment.yaml` in the chart templates, since we create the HPA if and only if architecture is also set to `high-availability`; we could never have a conflict between the Deployment and the HPA.

**Comment by figaw** [comment]
I'm working on a PR for this.

**Comment by figaw** [comment]
^apologies for the noise, I was having "fun" with getting the commit signed.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
