### ISSUE TITLE
postgresql-ha pgpool attempts to authenticate using SCRAM and fails when authentication method md5 is set

### ISSUE THREAD

**Issue by DorBreger** [bitnami/charts#22740]
### Name and Version

postgresql-ha 12.8.1

### What architecture are you using?

None

### What steps will reproduce the bug?

install the helm chart with `pgpool.authenticationMethod: 'md5'` and the pgpool would not be able to authenticate to the backend, causing it to fail the readinessProbe, restart, and fail again.

### Are you using any custom parameters or values?

`pgpool.authenticationMethod : md5`

### What is the expected behavior?

I would expect the pgpool to authenticate to be able to authenticate to the backend and my application to be able to authenticate to the pgpool using md5

### What do you see instead?
```
2024-01-26 10:39:14.777: child pid 152: ERRORL failed to authenticate to backend using SCRAM
2024-01-26 10:39:14.777: DETAIL:valid password not found
```

**Comment by FraPazGal** [comment]
Hello @DorBreger, I understand you are trying to use a postgresql-repmgr prior to version `<14` right? PSQL changed its default auth method to `scram` from `md5` in `v14` to improve security.

Although not recommended, you should be able to use `md5` by changing the default auth method both in pgpool (as you are already doing) and psql-rempgr by modifying its config file. I successfully installed the latest chart version `13.1.1` with the following params, could you try them?

```
## values.yaml

postgresql:
  ## This will replace the default config file
  ## We'll need to add `password_encryption` to the default config
  configuration: |-
    listen_addresses = '*'
    port = '5432'
    wal_level = 'replica'
    fsync = 'on'
    max_wal_size = '400MB'
    archive_mode = 'on'
    archive_command = '/bin/true'
    max_wal_senders = '16'
    max_replication_slots = '10'
    wal_keep_size = '128MB'
    hot_standby = 'on'
    logging_collector = 'on'
    log_directory = '/opt/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = 'false'
    log_disconnections = 'false'
    log_hostname = 'true'
    client_min_messages = 'error'
    shared_preload_libraries = 'repmgr, pgaudit, repmgr'
    include_dir = 'conf.d'
    pgaudit.log_catalog = 'off'
    password_encryption = md5
pgpool:
  authenticationMethod: md5
```
