### ISSUE TITLE
[bitnami/fluentd] extra gems extensions

### ISSUE THREAD

**Issue by gulecroc** [bitnami/charts#22758]
### Name and Version

bitnami/fluentd:5.14.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Some plugins/gems build extensions under `/opt/bitnami/fluentd/extensions`, as geoip : https://github.com/bitnami/containers/issues/55364

Currently the extraGems init container only copy gems and specifications directories.

This issue is to copy extensions directory as well

### What is the expected behavior?

install-extra-gems init container build extra plugin and copy all plugin resources (gems, specficiations and extensions)

### What do you see instead?

install-extra-gems init container does not copy extensions directory

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
