### ISSUE TITLE
Add alpha configuration parameter for oauth2-proxy

### ISSUE THREAD

**Issue by albert0815** [bitnami/charts#22756]
### Name and Version

bitnami/oauth2-proxy:6.23.1

### What is the problem this feature will solve?

Currently it is not possible to provide the "alpha configuration" (preferable as a secret).

### What is the feature you are proposing to solve the problem?

Add a parameter which allows adding the alpha configuration in a secret. Basically similar to configuration.existingConfigmap but as a secret because OIDC secrets are included.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
