### ISSUE TITLE
[bitnami/thanos] receive.service.additionalHeadless=true produce metrics twice

### ISSUE THREAD

**Issue by jkroepke** [bitnami/charts#22754]
### Name and Version

bitnami/thanos 12.21.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy prometheus-operator
2. Deploy thanos with `receive.service.additionalHeadless=true`
3. The ServiceMonitor for receive matches both services (headless and non-headless)

### Are you using any custom parameters or values?

`receive.service.additionalHeadless=true`

### What is the expected behavior?

the ServiceMonitor should not match the additional headless service

### What do you see instead?

the ServiceMonitor should match the additional headless service

### Additional information

The issues exist with the ruler and storegateway, too.

**Comment by jkroepke** [comment]
unstale

**Comment by aoterolorenzo** [comment]
I think this is due a conceptual change raised after addressing #16967. Mor info on [this comment](https://github.com/bitnami/charts/issues/16967#issuecomment-1588852479):

**Comment by jkroepke** [comment]
unstale

**Comment by fmulero** [comment]
Hi @jkroepke, I think you can workaround this issue setting the value `metrics.serviceMonitor.selector`. Could you give it a try?

**Comment by jkroepke** [comment]
The problem is that the clusterip service and the headless service having the same labels. In any case, both services match.

A solution would be a combination of `metrics.serviceMonitor.selector` and distinct labels for clusterip and headless service.

For example, each clusterip service gets the label `headless=false` and each headless service gets `headless=true`.

Then `metrics.serviceMonitor.selector` can additionally set to `headless=false`

**Comment by fmulero** [comment]
Yes, you are completely right. If we want to avoid scrapping the metrics twice when we have set `<component>.service.additionalHeadless=true` we'll need to set these values:
* `<component>.service.labels` with a custom label like `headless=false`
*  `metrics.serviceMonitor.selector` with the same label as above, in the example `headless=false`

This problem was fixed sometime ago and reappeared after #7685. To be perfectly blunt I don't see right now any benefit on that change and I think we could revert it.

**Comment by jkroepke** [comment]
In that case, offer a dedicated Service Monitoring. I cant see a use case to have all thanos metrics twice.

**Comment by jkroepke** [comment]
Still an issue

**Comment by jkroepke** [comment]
@fmulero Could you re-open this issue?

**Comment by fmulero** [comment]
Hi @jkroepke, we've just reverted the change #17685 to fix this issue.  These changes were released on version 15.1.1
