### ISSUE TITLE
configAsCode.extraConfigFiles is declared in values.yaml but never used in templates

### ISSUE THREAD

**Issue by majikman111** [bitnami/charts#22763]
### Name and Version

bitnami/jenkins 12.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set configAsCode.extraConfigFiles.enabled to true
2. Set configAsCode.extraConfigFiles
3. Deploy helm chart, where configAsCode.extraConfigFiles is never referenced

### Are you using any custom parameters or values?

configAsCode.extraConfigFiles.enabled
configAsCode.extraConfigFiles

### What is the expected behavior?

Additional files should be added to configmap `jenkins-casc`

### What do you see instead?

No additional files should be added to configmap `jenkins-casc`

### Additional information

Values entry:
https://github.com/bitnami/charts/blob/main/bitnami/jenkins/values.yaml#L251

Should be included in this template
https://github.com/bitnami/charts/blob/main/bitnami/jenkins/templates/casc-cm.yaml

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
