### ISSUE TITLE
[bitnami/argo-cd] ArgoCD container does ship with argocd-k8s-auth

### ISSUE THREAD

**Issue by donovanrost** [bitnami/charts#22769]
### Name and Version

bitnami/argocd/5.4.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`docker pull bitnami/argo-cd:2.9.5-debian-11-r0`
`docker run -it  bitnami/argo-cd:2.9.5-debian-11-r0 bash`
`which argocd-k8s-auth`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

ArgoCD uses `argocd-k8s-auth` to authenticate with external clusters. This binary should be on the filesystem. 

### What do you see instead?

Nothing, the binary is not on the filesystem

**Comment by donovanrost** [comment]
In retrospect, I realize this issue is better suited for the bitnami/containers repo, and have opened an issue here https://github.com/bitnami/containers/issues/55502

**Comment by javsalgar** [comment]
Hi! Thank you so much for opening the ticket. Closing this one then.
