### ISSUE TITLE
add SSL Mode support for PostgreSql and Redis 

### ISSUE THREAD

**Issue by ThomasUllrich666** [bitnami/charts#2277]
**Which chart**:
airflow current Version

**Is your feature request related to a problem? Please describe.**
I use external databases which require a secure ssl connection. If I want to connect to this database I need to set the SSLMode parameter in the PostgreSql connection. 

**Describe the solution you'd like**
Can you please add 2 new parameter:
//support for Postgresql SSL Mode: https://www.postgresql.org/docs/9.1/libpq-ssl.html
externalDatabase.sslMode=disable
// trusted certificate authorities
externalDatabase.rootCertSecret=nil

**Describe alternatives you've considered**
no alternatives fount

**Additional context**
https://www.postgresql.org/docs/9.1/libpq-ssl.html
https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-connection-strings

**Comment by rafariossaa** [comment]
Hi @ThomasUllrich666,
  Sorry for the delay, 
  Thanks for the request, I am creating an internal task to add this feature.
  We will come back to you as soon as we have news.
