### ISSUE TITLE
[bitnami/thanos] Error when upgrading to 0.34

### ISSUE THREAD

**Issue by tommiz1989** [bitnami/charts#22823]
### Name and Version

0.34

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Installation of the bug using storegateway sharding will produce the bug.

### Are you using any custom parameters or values?

Using the sharding functionality for Storegateway

### What is the expected behavior?

Helm upgrade success

### What do you see instead?

Failure when executing Helm command. Exited 1.
stderr: Error: Failed to render chart: exit status 1: Error: template: thanos/templates/storegateway/statefulset-sharded.yaml:35:34: executing \"thanos/templates/storegateway/statefulset-sharded.yaml\" at <.Values.storegateway.revisionHistoryLimit>: can't evaluate field Values in type int\n\nUse --debug flag to render out invalid YAML

### Additional information

I think you might be lacking a $ before the template variable here:
https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/storegateway/statefulset-sharded.yaml#L35

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Would you like to submit a PR with the fix?

**Comment by tommiz1989** [comment]
Seems like a fixed was pushed to the repo, waiting for the fix to be released.
