### ISSUE TITLE
Can not change the data dir of mysql

### ISSUE THREAD

**Issue by 27149chen** [bitnami/charts#22821]
### Name and Version

bitnami/mysql 9.18.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. set existingClaim to reuse exsiting data
2. set datadir in config file or in extraFlags
3. install the chart
4. mysql failed to start

### Are you using any custom parameters or values?

primary.persistence.existingClaim = "xxx"
primary.configuration = "...  datadir=xxx   ..."
primary.extraFlags = "--datadir=xxx"

### What is the expected behavior?

mysql started

### What do you see instead?

mysql failed to start

### Additional information

Set the value in configuration does not work because in setup.sh and run.sh "--datadir=${DB_DATA_DIR}" will be used.
So I try to pass a new --datadir, it works in run.sh, but still failed in setup.sh because function mysql_initialize will also use env DB_DATA_DIR
The only way is changing the env DB_DATA_DIR, but it is defined in mysql-env.sh, I can find a way to override it

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
