### ISSUE TITLE
[bitnami/postgresql] [bitnami/common] Helm upgrade with --dry-run option and "existing secret" produces "credentials error" 

### ISSUE THREAD

**Issue by percenuage** [bitnami/charts#22834]
### Name and Version

bitnami/postgresql 13.4.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Environment

``` yaml
# Kubernetes (GKE)
Client Version: v1.27.2
Server Version: v1.25.10-gke.2700
# Helm
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}
```
using this chart: https://artifacthub.io/packages/helm/bitnami/postgresql/13.4.3

2. Config

Postgresql chart are installed as a dependencies chart:
```yml
# Chart.yaml
apiVersion: v2
name: app
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 13.2.29
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
---
# values.yaml
[...]
postgresql:
  enabled: true
  fullnameOverride: postgresql

  auth:
    database: ops
    username: ops
    existingSecret: postgresql

  image:
    tag: 16.1.0-debian-11-r19

  primary:
    persistence:
      size: 1Gi
```

3. Commands

Before, I created `postgresql` secret with this command: `k create secret generic postgresql --from-literal=password="abcde0123" --from-literal=postgres-password="azerty9874"`

Then I installed the chart using: `helm upgrade --install -n default --install thanos app` --> GOOD ✅ 
Retry again without "dry-run": `helm upgrade --install -n default --install thanos app` --> GOOD ✅ 
Retry again with "dry-run": `helm upgrade --install -n default --install thanos app --dry-run` --> FAIL ❌ 

The chart shows an error as if I didn't use "existing secret":
```
Error: UPGRADE FAILED: execution error at (app/charts/postgresql/templates/secrets.yaml:23:16):
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.postgresql.auth.password' must not be empty, please add '--set global.postgresql.auth.password=$PASSWORD' to the command. To get the current value:

        export PASSWORD=$(kubectl get secret --namespace "main" postgresql -o jsonpath="{.data.password}" | base64 -d)
```

### What is the expected behavior?

The upgrade command with "dry-run" should be successful.

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/6691104/76e35f57-b9a3-43c7-9618-4b4c26228e93)

### Additional information

I think this issue comes from **bitnami/common** since we talk about "existing secret". I haven't try another chart.

**Comment by thai-op** [comment]
I'm seeing the same problem but with the "mariadb" chart. I'm trying to patch an configuration via Kustomization and this error just blocks everything.

> │ Error: error running dry run for a diff: execution error at (matomo/charts/mariadb/templates/secrets.yaml:8:21):
│ PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
│                  Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
│                  Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
│
│     'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:
│
│         export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "analytics" matomo-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
│
│
│   with module.matomo_optiversal.helm_release.matomo,
│   on ../../analytics/matomo/main.tf line 2, in resource "helm_release" "matomo":
│    2: resource "helm_release" "matomo" {

**Comment by rafariossaa** [comment]
Hi,
  Could you try this ?
```
helm upgrade --install -n default --install test app --dry-run=server
```
  The issue here is that if you do not indicate `server` it tries to validate the manifest on the client side, and it can not find the already created secrets.

**Comment by percenuage** [comment]
> Hi, Could you try this ?
> 
> ```
> helm upgrade --install -n default --install test app --dry-run=server
> ```
> 
> The issue here is that if you do not indicate `server` it tries to validate the manifest on the client side, and it can not find the already created secrets.

@rafariossaa Sorry but `--dry-run` accepts only boolean value.
```
Error: invalid argument "server" for "--dry-run" flag: strconv.ParseBool: parsing "server": invalid syntax
```

**Comment by rafariossaa** [comment]
Could you upgrade the helm tool ? this option was added in [helm 3.13.0](https://github.com/helm/helm/releases/tag/v3.13.0) in September.

**Comment by percenuage** [comment]
@rafariossaa Yes it works with the new version of Helm and the option --dry-run=server. Thx a lot !

**Comment by rafariossaa** [comment]
You are welcome, I am glad you were able to solve the issue.
