### ISSUE TITLE
[bitnami/elasticsearch] mounting /bitbami/elasticsearch/data 

### ISSUE THREAD

**Issue by omeruth** [bitnami/charts#22839]
### Name and Version

bitnami/elasticsearch

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to mount  /bitbami/elasticsearch/data to a local host folder /home/username/data. I am extraVolumes and extraVolumeMounts. But it doesn't let me create. Perhaps I am doing something wrong. How can I achieve this objective. I don't want to use PVC and PV.

### What do you see instead?

na

**Comment by javsalgar** [comment]
Hi,

Could you share the values you are using?

**Comment by omeruth** [comment]
here are the values. 
          
- name: elasticsearch
    chart: oci://registry-1.docker.io/bitnamicharts/elasticsearch
    namespace: db
    version: 19.6.0
    values:
      - extraEnvs:
        - name: discovery.type
          value: single-node
        # - name: cluster.initial_master_nodes
        #   value: ""
        - name: network.host
          value: 0.0.0.0
        - name: transport.host
          value: 127.0.0.1
      - extraConfig: 
          discovery:
            type: single-node
            seed_hosts: []
          cluster:
            initial_master_nodes: ""
      - master:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
          masterOnly: false
          replicaCount: 1
          persistence:
            enabled: false
      - data:
          replicaCount: 0
      - coordinating:
          replicaCount: 0
      - ingest:
          replicaCount: 0
      - security:
          enabled: true
          elasticPassword: "pasword"
          tls:
            autoGenerated: true
            restEncryption: true
      - resources:
          limits:
            cpu: "300m"
            memory: "3200Mi"
          requests:
            cpu: "200m"
            memory: "3000Mi"
      - extraEnvs:
        - name: "discovery.type"
          value: "single-node"
      - volumePermissions:
          enabled: true
      - extraVolumes:
        - name: esdata
          hostPath:
            path: /data/efs/es/esdata
            type: DirectoryOrCreate
        - name: esconfig
          hostPath:
            path: /data/efs/es/esconfig
            type: DirectoryOrCreate
      - extraVolumeMounts:
        - name: esdata
          mountPath: /bitnami/elasticsearch/
        - name: esconfig
          mountPath: /opt/bitnami/elasticsearch/config
      - global:
          kibanaEnabled: true
      - extraInitContainers:
          - name: init-chmod
            image: busybox
            command: ['sh', '-c', 'chmod -R go+w /opt/bitnami/elasticsearch/config']
            volumeMounts:
              - name: esconfig
                mountPath: /opt/bitnami/elasticsearch/config
      - extraInitContainers:
          - name: init-chmod2
            image: busybox
            command: ['sh', '-c', 'chmod -R go+rw /bitnami/elasticsearch/']
            
Also for esdata if I chose  mountPath: /bitnami/elasticsearch/data pod will fail with warning as invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/bitnami/elasticsearch/data": must be unique
so i changed the mountPath to "/bitnami/elasticsearch/

**Comment by rafariossaa** [comment]
Hi,
  May I ask why you don't want to use PV ? I would like to know more about your use case.
  If persistence is disable a `emptyDir` volume is used for the data directory. If you want to use a specific directory on the host you could create a PV for that directory and then use `master.persistence.existingVolume`.

**Comment by omeruth** [comment]
Thank you existingVolume worked for me!

**Comment by rafariossaa** [comment]
I am glad you could solve your issue.
