### ISSUE TITLE
bitnami/postgresql-ha - chart default setup not working on azure

### ISSUE THREAD

**Issue by dapus123** [bitnami/charts#2285]
Hi Guys,

I'm trying to install latest postgresql-ha in a kubernetes cluster setup on Azure, using default _values.yaml_ or _values-production.yaml_ from github source:
```
helm install postgresql -f values-production.yaml --set postgresql.password=123test --set postgresql.repmgrPassword=text123 --set postgresql.repmgrLogLevel=DEBUG .
```

https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values-production.yaml
https://hub.helm.sh/charts/bitnami/postgresql-ha/2.0.4

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

I simply cannot make it work and I cannot troubleshoot container as it stops, tried to tweak around with the _values-production.yaml_ but no luck.

pgpool log sample:
```
own"
2020-04-09 05:31:08: pid 1: ERROR: failed to make persistent db connection
2020-04-09 05:31:08: pid 1: DETAIL: connection to host:"postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless.default.svc.cluster.local:5432" failed
2020-04-09 05:31:08: pid 1: LOG: find_primary_node: make_persistent_db_connection_noerror failed on node 1
```
postgresql log sample:
```
postgresql-repmgr 05:37:41.07 INFO ==> ** Starting PostgreSQL with Replication Manager setup **
repmgr 05:37:41.13 INFO ==> Validating settings in REPMGR_* env vars...
postgresql 05:37:41.13 INFO ==> Validating settings in POSTGRESQL_* env vars..
repmgr 05:37:41.13 INFO ==> Querying all partner nodes for common upstream node...
repmgr 05:37:41.17 INFO ==> There are no nodes with primary role. Assuming the primary role...
repmgr 05:37:41.17 INFO ==> Preparing PostgreSQL configuration...
postgresql 05:37:41.18 INFO ==> postgresql.conf file not detected. Generating it...
repmgr 05:37:41.23 INFO ==> Preparing repmgr configuration...
repmgr 05:37:41.23 INFO ==> Initializing Repmgr...
postgresql 05:37:41.23 INFO ==> Initializing PostgreSQL database...
postgresql 05:37:41.24 INFO ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 05:37:41.24 INFO ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql 05:37:41.24 INFO ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 05:37:41.26 INFO ==> Deploying PostgreSQL with persisted data...
postgresql 05:37:41.27 INFO ==> Stopping PostgreSQL...
postgresql-repmgr 05:37:41.28 INFO ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql 05:37:41.34 INFO ==> Starting PostgreSQL in background...
postgresql-repmgr 05:37:41.56 INFO ==> ** Starting repmgrd **
[2020-04-09 05:37:41] [NOTICE] repmgrd (repmgrd 5.0.0) starting up
[2020-04-09 05:37:41] [INFO] connecting to database "user=repmgr password=test123 host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2020-04-09 05:37:41] [DEBUG] connecting to: "user=repmgr password=123test connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr"
[2020-04-09 05:37:41] [ERROR] connection to database failed
[2020-04-09 05:37:41] [DETAIL]
**received invalid response to SSL negotiation:**
```
Does anyone know if this chart should work on azure kubernetes cluster?
Thank you!

**Comment by elliottminns** [comment]
Same issue on DigitalOcean Kubernetes cluster

**Comment by carrodher** [comment]
Hi,

this chart is tested on top of AKS so the platform/cluster shouldn't be the problem in that case.

According to the log
```
[2020-04-09 05:37:41] [INFO] connecting to database "user=repmgr password=test123 host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2020-04-09 05:37:41] [DEBUG] connecting to: "user=repmgr password=123test connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr"
[2020-04-09 05:37:41] [ERROR] connection to database failed
```
it seems an issue related to the authentication, did you installed it previously?

Take into account that if you don't set any password it generates a random one that is stored in the PVC:
```
▶ kubectl get pvc | grep postgresql
data-postgresql-postgresql-ha-postgresql-0    Bound    pvc-b392935d-8a72-4274-a124-8ebf91578fd3   8Gi        RWO            standard       3m37s
data-postgresql-postgresql-ha-postgresql-1    Bound    pvc-a2b7e40b-f3a8-4c3a-96c4-23c3b17b98ea   8Gi        RWO            standard       2m46s
```
and that PVC is not removed with `helm delete`, so if you install again the chart with the same name (`postgresql` in your case) but using a different password (explicitly or the random one), the deployment is going to fail because in the PVC the password is still the previous one.

I was able to reproduce the issue following this approach:
- Installing it from scratch with the following command works fine
```
$ helm install postgresql -f values-production.yaml --set postgresql.password=password1 --set postgresql.repmgrPassword=password1 --set postgresql.repmgrLogLevel=DEBUG .
```
- Then remove the deployment:
```
$ helm delete postgresql
```
- Now install it again with the same name but different password:
```
$ helm install postgresql -f values-production.yaml --set postgresql.password=newPassword --set postgresql.repmgrPassword=newPassword --set postgresql.repmgrLogLevel=DEBUG .
```
- In this case the deployment failed:
```
$ kubectl logs -f postgresql-postgresql-ha-postgresql-0 postgresql
...
[2020-04-13 12:17:01] [DEBUG] connecting to: "user=repmgr password=newpass connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr"
[2020-04-13 12:17:01] [ERROR] connection to database failed
[2020-04-13 12:17:01] [DETAIL]
FATAL:  password authentication failed for user "repmgr"
```

If that is your case, you need to remove the PVC when deploying it from scratch using the same name but different password:
```
$ helm delete postgresql
$ kubectl delete pvc data-postgresql-postgresql-ha-postgresql-0 data-postgresql-postgresql-ha-postgresql-1
persistentvolumeclaim "data-postgresql-postgresql-ha-postgresql-0" deleted
persistentvolumeclaim "data-postgresql-postgresql-ha-postgresql-1" deleted
```

**Comment by dapus123** [comment]
Hi There,

Thanks a lot for reply. 

Besides Azure we have deployed kyma project if that will make any difference, I really don't know at this point.
[ kyma-project.io](url)

I wish it was simpler as you explained, but apparently it doesn't work for me :) - just tried it from scratch (no pvc, no pods, nothing).
I remember I tried it by using persistence: true/false, completely deleting it from scratch several times, trying to override repmgr.conf and postgresql.conf, putting ssl=off to postgresql or conninfo including sslmode=disable but no success.

`k describe pod postgresql-ha-postgresql-0
...
Events:
  Type     Reason                  Age                     From                                        Message
  ----     ------                  ----                    ----                                        -------
  Warning  FailedScheduling        10m (x2 over 10m)       default-scheduler                           pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled               10m                     default-scheduler                           Successfully assigned default/postgresql-ha-postgresql-0 to aks-nodepool1-34569519-vmss000000
  Normal   SuccessfulAttachVolume  10m                     attachdetach-controller                     AttachVolume.Attach succeeded for volume "pvc-9edf5319-7d8f-11ea-ba6a-26b1715ec831"
  Warning  FailedMount             8m42s                   kubelet, aks-nodepool1-34569519-vmss000000  Unable to mount volumes for pod "postgresql-ha-postgresql-0_default(9f184184-7d8f-11ea-ba6a-26b1715ec831)": timeout expired waiting for volumes to attach or mount for pod "default"/"postgresql-ha-postgresql-0". list of unmounted volumes=[data]. list of unattached volumes=[data default-token-wgkzt istio-envoy istio-certs]
  Normal   Pulled                  8m27s                   kubelet, aks-nodepool1-34569519-vmss000000  Container image "docker.io/istio/proxyv2:1.4.3" already present on machine
  Normal   Created                 8m27s                   kubelet, aks-nodepool1-34569519-vmss000000  Created container istio-init
  Normal   Started                 8m27s                   kubelet, aks-nodepool1-34569519-vmss000000  Started container istio-init
  Normal   Pulled                  8m25s                   kubelet, aks-nodepool1-34569519-vmss000000  Container image "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r72" already present on machine
  Normal   Created                 8m24s                   kubelet, aks-nodepool1-34569519-vmss000000  Created container istio-proxy
  Normal   Pulled                  8m24s                   kubelet, aks-nodepool1-34569519-vmss000000  Container image "docker.io/istio/proxyv2:1.4.3" already present on machine
  Normal   Started                 8m24s                   kubelet, aks-nodepool1-34569519-vmss000000  Started container istio-proxy
  Normal   Created                 8m24s                   kubelet, aks-nodepool1-34569519-vmss000000  Created container metrics
  Normal   Started                 8m24s                   kubelet, aks-nodepool1-34569519-vmss000000  Started container metrics
  Warning  Unhealthy               8m22s                   kubelet, aks-nodepool1-34569519-vmss000000  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy               8m20s                   kubelet, aks-nodepool1-34569519-vmss000000  Readiness probe failed: psql: FATAL:  the database system is shutting down
  Normal   Started                 8m (x3 over 8m25s)      kubelet, aks-nodepool1-34569519-vmss000000  Started container postgresql
  Normal   Created                 8m (x3 over 8m25s)      kubelet, aks-nodepool1-34569519-vmss000000  Created container postgresql
  Normal   Pulled                  8m (x3 over 8m25s)      kubelet, aks-nodepool1-34569519-vmss000000  Container image "docker.io/bitnami/postgresql-repmgr:11.7.0-debian-10-r76" already present on machine
  Warning  BackOff                 3m36s (x25 over 8m14s)  kubelet, aks-nodepool1-34569519-vmss000000  Back-off restarting failed container
'

`
helm install postgresql-ha -f values-production.yaml --set postgresql.password=BOrhanci83! --set postgresql.repmgrPassword=PIsica83! --set postgresql.repmgrLogLevel=DEBUG .

k get pods
postgresql-ha-pgpool-66769d7945-d9ghb   1/2     CrashLoopBackOff   7          14m
postgresql-ha-postgresql-0              2/3     CrashLoopBackOff   7          14m

k logs -f postgresql-ha-postgresql-0 postgresql

postgresql-repmgr 14:08:13.11
postgresql-repmgr 14:08:13.11 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 14:08:13.12 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 14:08:13.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 14:08:13.12 Send us your feedback at containers@bitnami.com
postgresql-repmgr 14:08:13.12
postgresql-repmgr 14:08:13.14 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
repmgr 14:08:13.20 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql 14:08:13.21 INFO  ==> Validating settings in POSTGRESQL_* env vars..
repmgr 14:08:13.21 INFO  ==> Querying all partner nodes for common upstream node...
repmgr 14:08:13.25 INFO  ==> There are no nodes with primary role. Assuming the primary role...
repmgr 14:08:13.26 INFO  ==> Preparing PostgreSQL configuration...
postgresql 14:08:13.26 INFO  ==> postgresql.conf file not detected. Generating it...
repmgr 14:08:13.31 INFO  ==> Preparing repmgr configuration...
repmgr 14:08:13.32 INFO  ==> Initializing Repmgr...
postgresql 14:08:13.32 INFO  ==> Initializing PostgreSQL database...
postgresql 14:08:13.32 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 14:08:13.33 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql 14:08:13.33 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 14:08:13.35 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 14:08:13.36 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 14:08:13.37 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql 14:08:13.44 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 14:08:13.67 INFO  ==> ** Starting repmgrd **
[2020-04-13 14:08:13] [NOTICE] repmgrd (repmgrd 5.0.0) starting up
[2020-04-13 14:08:13] [INFO] connecting to database "user=repmgr password=PIsica83! host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2020-04-13 14:08:13] [DEBUG] connecting to: "user=repmgr password=PIsica83! connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr"
[2020-04-13 14:08:13] [ERROR] connection to database failed
[2020-04-13 14:08:13] [DETAIL]
received invalid response to SSL negotiation:

[2020-04-13 14:08:13] [DETAIL] attempted to connect using:
  user=repmgr password=PIsica83! connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgdpops-MacBook-Pro:postgresql-ha dpop$ vc.cluster.local port=5432 fallback_application_name=repmgr
`

I also got a notification via email regarding the same issue on DO k8 cluster:
`Elliott Minns <notifications@github.com>
To:
bitnami/charts
Cc:
dapus123
,
Author
Unsubscribe

Sat, Apr 11 at 6:11 PM

Same issue on DigitalOcean Kubernetes cluster`

Please advice!

Thank you,
Dani

**Comment by carrodher** [comment]
I am trying to reproduce the issue on my side, as I am not able to reproduce it with the default parameters, did you modify the _values-production.yaml_ or are you using the default one? If yes, can you share the changes you implemented in order to try to reproduce the same environment? Thanks

**Comment by dapus123** [comment]
Hi,

Unfortunately I ran it again clean/fresh git clone and I didn't modify anything, just default values-production.yaml.
```helm install postgresql-ha -f values-production.yaml --set postgresql.password=BOrhanci83! --set postgresql.repmgrPassword=PIsica83! --set postgresql.repmgrLogLevel=DEBUG .```
Please note that we have[ kyma-project.io](url) installed on top of our k8 cluster

Thank you,
Dani

**Comment by dapus123** [comment]
ssl is off by default in postgresql, but what about repmgr? if default doesn't touch the ssl, then it could but I don't know yet to relate with kyma installation.

**Comment by carrodher** [comment]
Hi,

AFAIK Azure enables SSL by default in the cluster, but in the postgresql-ha chart, TLS is not implemented at this moment. We are working on standardizing some parameters in all the bitnami charts, hopefully we will add TLS support to this one sooner rather than later.

**Comment by dapus123** [comment]
thanks you
