### ISSUE TITLE
[bitnami/elasticsearch] SingleNode healthcheck failing on IPv6 environments

### ISSUE THREAD

**Issue by mtenrero** [bitnami/charts#22880]
### Name and Version

bitnami/elasticsearch:8.12.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configure deployment with masterOnly set to true
2. Disable data, ingest and coordinating roles deployment
3. Deploy chart on pure IPv6 cluster
4. Healthceck of readiness probe will fail

### What is the expected behavior?

Healthcheck works correctly on pure IPv6 envs and deployment is succcesfully deployed without restart 

### What do you see instead?

Pods gets restarted due to readiness probe issue

### Additional information

I've seen the issue is because in the helm chart is define when masterOnly is set to true param ELASTICSEARCH_ADVERTISED_HOSTNAME is not passed and therefore, internal pod IP address is used instead.

https://github.com/bitnami/charts/blob/c997bdfc2f43aedc79f6cf949bbb611d007adf96/bitnami/elasticsearch/templates/master/statefulset.yaml#L183

With this approach, the call made to the server will be without square brackets and the request will fail in consequence.

https://github.com/bitnami/containers/blob/16154319849aa21949ff0a6af528f6d8ef8062a7/bitnami/elasticsearch/8/debian-11/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L450

The proposal for fixing it would be adding alwayes the env var or fix the script for appending [] when it's an IPv6, maybe in the networking lib. 

What do you think?

**Comment by andresbono** [comment]
Hi @mtenrero, thank you for opening this issue. Did you test that just by passing the `ELASTICSEARCH_ADVERTISED_HOSTNAME` env-var the issue is resolved? You can try with `master.extraEnvVars`.

Please feel free to open a PR with your proposed change and a member of the team will review it. Thank you!!

**Comment by mtenrero** [comment]
Adding extraEnvVars works fine, but IMHO I guess it's better to have this login inside the chart, as the users may not know how to properly configure this param in certain topologies.

**Comment by andresbono** [comment]
Of course, adding extraEnvVars is just a workaround that I wanted to confirm it worked in your scenario. But it is not a proper solution.

If the `get_machine_ip` function is not working as you would expect with IPv6, we will be more than welcome to review a PR improving or fixing the functionality!

https://github.com/bitnami/containers/blob/16154319849aa21949ff0a6af528f6d8ef8062a7/bitnami/elasticsearch/8/debian-11/prebuildfs/opt/bitnami/scripts/libnet.sh#L53-L72
