### ISSUE TITLE
Sync with IBM public cloud failes with: redis-cluster 5.0.7

### ISSUE THREAD

**Issue by gmendel** [bitnami/charts#2292]
**Which chart**:
redis-cluster 5.0.7

**Describe the bug**
Failed to pull image "docker.io/bitnami/redis-cluster:5.0.8-debian-10-r0": rpc error: code = Unknown desc = failed to resolve image "docker.io/bitnami/redis-cluster:5.0.8-debian-10-r0": docker.io/bitnami/redis-cluster:5.0.8-debian-10-r0 not found

**To Reproduce**
Could not deploy on IKS

**Comment by beltran-rubo** [comment]
Hi Gili,

We apologize for the inconvenience. This Chart was a new one and it was released on Friday. At the moment you checked the images were not available yet, the images are available now. We will also make sure it appears in the IBM JSON feed.
