### ISSUE TITLE
[bitnami/redis] Changed `networkPolicy.enabled` default breaks my install

### ISSUE THREAD

**Issue by joekrill** [bitnami/charts#22934]
### Name and Version

bitnami/redis 18.11.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy redis via latest helm chart version
2. Note that a network policy is now created by default

### What is the expected behavior?

A breaking change like this shouldn't be included in a minor release bump. 

### What do you see instead?

For me, it completely broke my redis instance. Since I'm using istio, it prevents the istio-proxy sidecar from reaching the istiod service. 

### Additional information

This should have cause a major version increment because this is a breaking change.

**Comment by javsalgar** [comment]
Hi! Thank you so much for reporting the issue. That was a good catch about Istio. Let me prepare fixes to avoid problems on this.

**Comment by javsalgar** [comment]
@joekrill could you confirm if the fix above works for your installation? If so, we will apply it to the rest of the charts

**Comment by joekrill** [comment]
> @joekrill could you confirm if the fix above works for your installation? If so, we will apply it to the rest of the charts

Once the chart is deployed I can check it. But it still seems like this should require a major version bump, no? It's hard to understand the implications of this and it could still be a breaking change for some folks, I would think.

**Comment by javsalgar** [comment]
In order to be on the safe side, we will create a new PR disabling the network policy and then creating a major bump enabling it and setting externalEgress=false. This way we will avoid any more disrupting changes. Once again we're sorry for any inconvenience caused.

**Comment by joekrill** [comment]
@javsalgar This did indeed fix my issue with Istio. Thanks so much!
