### ISSUE TITLE
Support for ARM64 architecture in Bitnami container images on Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by MauroSoli** [bitnami/charts#22932]
### Name and Version

bitnami/redis 7.2.4

### What is the problem this feature will solve?

As done in [this Issue](https://github.com/bitnami/charts/issues/7305#issuecomment-1544667772), I would like to be able to pull Redis Bitnami images from Amazon ECR Public Gallery.

### What is the feature you are proposing to solve the problem?

Add multi-arch support in [Amazon ECR Public Gallery](https://gallery.ecr.aws/bitnami/redis).

**Comment by carrodher** [comment]
Unfortunately, there are no plans in the mid-term to work on pushing the ARM container images to any other registry different than DockerHub. Because of that, we will close this issue as not planned.
