### ISSUE TITLE
I want to establish a connection between my Airflow instance and an external MySQL database to store metadata.

### ISSUE THREAD

**Issue by arjun-guptha** [bitnami/charts#22946]
### Name and Version

bitnami/airflow:2.7

### What is the problem this feature will solve?

I've implemented Airflow using the Bitnami Helm chart. I'm curious to know if the Bitnami Helm chart supports connecting Airflow to an external MySQL database for storing metadata. If it does, could you please provide me with the configuration details? Currently, I've only been able to see the details for connection to an external PostgreSQL configuration.

### What is the feature you are proposing to solve the problem?

I want to establish a connection between my Airflow instance and an external MySQL database to store metadata.

**Comment by arjun-guptha** [comment]
> [Here](https://github.com/bitnami/charts/tree/main/bitnami/airflow#airflow-database-parameters) you can find the different parameters required to configure an external database.

Hi @carrodher So we can establish a connection to MySQL also as an external database, correct?

**Comment by carrodher** [comment]
No sorry, only PostgreSQL is available

**Comment by wangko27** [comment]
it work for me
https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html#setting-up-a-mysql-database
- 1 update you  airflow values.yaml add extraEnvVars
`## @param extraEnvVars Add extra environment variables for all the Airflow pods
##
extraEnvVars:
  - name: AIRFLOW__API__AUTH_BACKENDS
    value: 'airflow.api.auth.backend.basic_auth'
  - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
    value: 'True'
  - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
    value: 'mysql+mysqldb://admin:vAitrE27F2@mysql-primary:3306/airflow_db'`

- 2 Setting up a MySQL Database
`CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'airflow_user' IDENTIFIED BY 'airflow_pass';
GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user';`
- 3 reinstall airflow
`
helm -n demo del airflow 
helm -n demo install airflow .
`
