### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Metrics service name exceed 63 characters

### ISSUE THREAD

**Issue by Sirz3chs** [bitnami/charts#22957]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.10.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the helm chart with a long release name like `rabbitmq-cluster-operator` and enable metrics service

### Are you using any custom parameters or values?

```yaml
---
msgTopologyOperator:
  metrics:
    service:
      enabled: true
```

### What is the expected behavior?

Be able to deploy the metrics service.

### What do you see instead?

The metrics-service.yml resource uses the `fullname` which is indeed truncated at 63 characters but it is suffixed by `-metrics` and cause the name to exceed this limit.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
