### ISSUE TITLE
[bitnami/minio] Server is not starting with custom security context

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#22989]
### Name and Version

bitnami/minio:12.10.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set ReadOnlyRootFilesystem = true for container security context
2. Read-only filesystem error on `/opt/bitnami/minio/tmp`
3. Set uid and gid to 10001
4. Permission-denied filesystem error on `/opt/bitnami/minio/tmp`

### Are you using any custom parameters or values?

I set custom uid/gid + ReadOnlyRootFilesystem = true

### What is the expected behavior?

ReadOnlyRootFilesystem and custom uid/gid should be possible. 

### What do you see instead?

Read-only filesystem error + Permission-denied filesystem error on `/opt/bitnami/minio/tmp.`

### Additional information

Even mounting a simple emptyDir is generating the following message "Adding local Minio host to 'mc' configuration..." in an infinite loop.

This was discovered while trying to address the issues reported by kube-score / kube-linter

- [CRITICAL] Container Security Context ReadOnlyRootFilesystem
- [CRITICAL] Container Security Context User Group ID

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
