### ISSUE TITLE
Fix http metrics by upgrading to the latest keycloak-metrics-spi version

### ISSUE THREAD

**Issue by v0lk3r** [bitnami/charts#22986]
### Name and Version

bitnami/keycloak 18.3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy helm chart with metrics enabled
2. Check metrics endpoint - the `keycloak_request_duration` metrics are missing (located at `<base url>/auth/realms/<realm>/metrics` 

### Are you using any custom parameters or values?
```yaml
metrics:
  enabled: true
```
### What is the expected behavior?

HTTP response time metrics are exported

### What do you see instead?

Other than the "docstring" the specific metrics are missing, e.g.

```
# HELP keycloak_request_duration Request duration
# TYPE keycloak_request_duration histogram
...
```

### Additional information

See also issue https://github.com/aerogear/keycloak-metrics-spi/issues/182 in the metrics spi. There's a new version that is supposed to fix that issue.

**Comment by dgomezleon** [comment]
Updated in this [PR](https://github.com/bitnami/charts/pull/23169).

**Comment by v0lk3r** [comment]
Awesome, thanks @dgomezleon for getting that fixed/updated so quickly!
