### ISSUE TITLE
[wordpress/http requests] Mixed Content: The page at <URL> was loaded over HTTPS, but requested an insecure element <URL>

### ISSUE THREAD

**Issue by VanderSant-ShawAndPartners** [bitnami/charts#22988]
### Name and Version

bitnami/wordpress:19.2.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deployment
2. Add Gateway, VirtualService and DestinationRule
3. When I access my WordPress DNS "wordpress.dev.shawandpartners.com" the page is not able to perform all requests correctly

### Are you using any custom parameters or values?
```
wordpressUsername: admin
wordpressPassword: admin
service.type: LoadBalancer
auth.database: sp_wordpress
auth.username: shawandpartners_wordpress
auth.persistence.size: 10Gi
```

### What is the expected behavior?

![image](https://github.com/bitnami/charts/assets/142842036/25ef968f-516c-45a9-988c-e0b714567171)

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/142842036/74a84f9f-eda8-4e41-98c6-11e716c699fd)

### Additional information

I am using Helm Istio with my Kubernetes to perform the deployment. When I use the load balance IP or execute the application in localhost I do not have this type of problem, but when I try to execute WordPress with a domain name, that has an SSL certificate, I have a lot of problems with a mix of types of requests. I would like to know what I can do to fix this problem

I have already tried to use several types of WordPress extensions, but nothing worked

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
