### ISSUE TITLE
Jupyterhub the act of overriding PostgreSQL enable flag breaks common image in init container

### ISSUE THREAD

**Issue by DreamingRaven** [bitnami/charts#22983]
### Name and Version

bitnami/jupyterhub 5.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm repo add bitnami repo
2.  ``helm template jupyterhub bitnami/jupyterhub --set postgresql.enabled=false``
Results in:
```
Error: template: jupyterhub/templates/hub/deployment.yaml:82:20: executing "jupyterhub/templates/hub/deployment.yaml" at <include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global)>: error calling include: template: jupyterhub/charts/common/templates/_images.tpl:12:31: executing "common.images.image" at <.imageRoot.registry>: nil pointer evaluating interface {}.registry

Use --debug flag to render out invalid YAML
```
Internal db use is unaffected as it is the default, and overriding with true continues to work.

### Are you using any custom parameters or values?

```yaml
postgresql:
  enabled: false
```

### What is the expected behavior?

Template render would successfully find the common image to use for db connection testing and configuration.

### What do you see instead?

```bash
Error: template: jupyterhub/templates/hub/deployment.yaml:82:20: executing "jupyterhub/templates/hub/deployment.yaml" at <include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global)>: error calling include: template: jupyterhub/charts/common/templates/_images.tpl:12:31: executing "common.images.image" at <.imageRoot.registry>: nil pointer evaluating interface {}.registry

Use --debug flag to render out invalid YAML
```
```bash
> helm template jupyterhub bitnami/jupyterhub --set postgresql.enabled=false --debug
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /home/archer/.cache/helm/repository/jupyterhub-5.6.3.tgz


Error: template: jupyterhub/templates/hub/deployment.yaml:82:20: executing "jupyterhub/templates/hub/deployment.yaml" at <include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global)>: error calling include: template: jupyterhub/charts/common/templates/_images.tpl:12:31: executing "common.images.image" at <.imageRoot.registry>: nil pointer evaluating interface {}.registry
helm.go:84: [debug] template: jupyterhub/templates/hub/deployment.yaml:82:20: executing "jupyterhub/templates/hub/deployment.yaml" at <include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global)>: error calling include: template: jupyterhub/charts/common/templates/_images.tpl:12:31: executing "common.images.image" at <.imageRoot.registry>: nil pointer evaluating interface {}.registry
```

### Additional information

Stems from the following image template included from common:
https://github.com/bitnami/charts/blob/cdb5a9a797b557d0590292c87aefb9c56a3db7ef/bitnami/jupyterhub/templates/hub/deployment.yaml#L77-L82
If the charts yaml defaults to false for postgresql.enabled this issue is not incurred. It is only incurred when overriden externally like a consumer using the chart and wants an external db.

Relates to: https://github.com/bitnami/charts/pull/22735 which fixes the ability of the chart to support external db connections, but does not touch / fix this issue with the template not resolving an image to use for the init container, and was only later discovered after separately testing rather than including postgresql-ha as a subchart for in-chart testing.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
