### ISSUE TITLE
[bitnami/postgresql-ha] PodDisruptionBudget is missing on postgresql statefulset

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#22991]
### Name and Version

bitnami/postgresql-ha:12.3.4

### What is the problem this feature will solve?
```
[CRITICAL] StatefulSet has PodDisruptionBudget
        · No matching PodDisruptionBudget was found
            It's recommended to define a PodDisruptionBudget to avoid
            unexpected downtime during Kubernetes maintenance operations, such
            as when draining a node.
```
### What is the feature you are proposing to solve the problem?

Create a new PodDisruptionBudget resource in the helm chart

**Comment by carrodher** [comment]
Could you please provide more information about how are you deploying the Helm chart, what is the environment and the values used? Thanks
