### ISSUE TITLE
ARM64 Support for Postgresql

### ISSUE THREAD

**Issue by olsenpabu** [bitnami/charts#22996]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

I just want to confirm if ARM64 is supported by the Postgresql Charts

### What is the feature you are proposing to solve the problem?

Able to support arm64 architecture

**Comment by carrodher** [comment]
PostgreSQL container image and therefore the Helm chart is multi-arch. If you deploy it in an ARM host, it should pick the ARM image.

**Comment by olsenpabu** [comment]
Thank you! Will try this
