### ISSUE TITLE
cassandra deployment failing with poddisruptionbudgets.policy error

### ISSUE THREAD

**Issue by govindkailas** [bitnami/charts#2300]
**Which chart**:
Cassandra chart v 5.2.0.

**Describe the bug**
Filed the details here, 
https://github.com/kubeapps/kubeapps/issues/1656

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @govindkailas ,
I would say you have any Kind of RBAC in your cluster enabled and the rules are not allowing that role to access the PDB.
Have in mind RBAC rules are purely additive so I would give a try to give access to the PDB resource.

**Comment by govindkailas** [comment]
Cluster admins gave only restricted access to each serviceaccount, we have seen that for most of the application that are enough. Why is PDB needed and what are we trying to achieve by getting access to PDB?

**Comment by miguelaeh** [comment]
Hi @govindkailas ,
The PDB is something that will ensure that a minimum number of Pods are running, in any case, it should be necessary for production environments but not for development.
So, let me create a PR to allow disable it.
Thank you for reporting.
