### ISSUE TITLE
[bitnami/nginx] Add optional mounts

### ISSUE THREAD

**Issue by addshore** [bitnami/charts#2301]
**Which chart**: nginx

**Is your feature request related to a problem? Please describe.**
I want to add a mount to the chart to serve some static file.

**Describe the solution you'd like**
Ability to define mounts in values for the chart.

**Describe alternatives you've considered**
Not using the bitnami nginx image
(I understanding if bitnami don't want to add this)

**Comment by juan131** [comment]
Hi @addshore 

Thanks for reporting this! I also consider this a basic feature to support. I just created a PR to provide different mechanisms to solve this.

**Comment by juan131** [comment]
Hi @addshore 

Could you please give a try to new chart version (**5.2.0**)? In the section below of the README.md you have more information about the different mechanisms we implemented for you to deploy your custom static site:

- https://github.com/bitnami/charts/tree/master/bitnami/nginx#deploying-your-custom-web-application
