### ISSUE TITLE
Chart `rabbitmq-cluster-operator` missing OperatorPolicy CRD

### ISSUE THREAD

**Issue by RichiCoder1** [bitnami/charts#23027]
### Name and Version

rabbitmq-cluster-operator 3.14.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* Install rabbitmq-cluster-operator 3.14.1
* Note that `rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator` doesn't go healthy due to missing OperatorPolicy CRD

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

Service boots

### What do you see instead?

CRD present

### Additional information

N/A

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by DrFaust92** [comment]
PR incoming

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by mruoss** [comment]
It's not just the CRD that's missing. RBAC needs to be defined as well. See my [comment in the PR](https://github.com/bitnami/charts/pull/23037#issuecomment-1926479774)
