### ISSUE TITLE
[bitnami/rabbitmq] Azure marketplace Failed to pull image Not Found

### ISSUE THREAD

**Issue by daniemarquesorigo** [bitnami/charts#23026]
### Name and Version

azure-marketplace/rabbitmq 11.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. In Azure Kubernetes Service
2. With Default Config
3. helm install rabbitcore -f values-qa.yml azure-marketplace/rabbitmq --set auth.password="..." --set auth.erlangCookie="..."

### Are you using any custom parameters or values?

Custom values.yml:
```yaml
extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_shovel_management"
replicaCount: 1

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  mountPath: /bitnami/rabbitmq/mnesia
  size: 1Gi
  ```

### What do you see instead?
```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  35m                  default-scheduler  Successfully assigned hml/rabbitcore-rabbitmq-0 to aks-hml-18662355-vmss00004x
  Normal   Pulling    34m (x4 over 35m)    kubelet            Pulling image "marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0"
  Warning  Failed     34m (x4 over 35m)    kubelet            Failed to pull image "marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0": rpc error: code = NotFound desc = failed to pull and unpack image "marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0": failed to resolve reference "marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0": marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0: not found
  Warning  Failed     34m (x4 over 35m)    kubelet            Error: ErrImagePull
  Warning  Failed     33m (x6 over 35m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    45s (x153 over 35m)  kubelet            Back-off pulling image "marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0"
```

**Comment by dookse** [comment]
@javsalgar 
Try replacing all occurrences of 'marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0' with 'bitnami/rabbitmq:3.11.2-debian-11-r0' in your configuration. 
I was actually using version 'rabbitmq:3.10.5-debian-11-r5', but I managed to resolve it.

**Comment by javsalgar** [comment]
Hi!

Did you follow these instructions? https://docs.bitnami.com/azure/get-started-cnab/

**Comment by Crossbow78** [comment]
I've been using rabbitmq in my local Docker Kubernetes cluster, and can no longer pull the image from the original marketplace url.

> (HTTP code 404) unexpected - manifest for marketplace.azurecr.io/bitnami/rabbitmq:3.11.2-debian-11-r0 not found: manifest unknown: manifest tagged by "3.11.2-debian-11-r0" is not found

What's worse, after the Kubernetes upgrade on our production AKS cluster, our pods referencing this image could no longer start up. A week earlier this still worked fine on our test AKS cluster.

> Failed to pull image "[marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0](http://marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0)": rpc error: code = NotFound desc = failed to pull and unpack image "[marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0](http://marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0)": failed to resolve reference "[marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0](http://marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0)": [marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0](http://marketplace.azurecr.io/bitnami/rabbitmq:3.9.18-debian-10-r0): not found

What has changed in the past week?

> Did you follow these instructions? https://docs.bitnami.com/azure/get-started-cnab/

I cannot make sense of any of this, nor do I see how it would apply to - for example - a local 'helm install'...

**Comment by Miseq** [comment]
Yup, it actually happend in my dev enviroment, no way of accessing this image. Sooner or later someone's production application will restart and try to pull image no longer available.

**Comment by Eddie0065** [comment]
Can confirm, 30 minutes ago one of the pods didn't succeed with pulling the image, the same problem. 
I'm afraid it can happen with the prod env in any moment.

**Comment by daniemarquesorigo** [comment]
My understaging is that the bitnami images are no loger available at the registry marketplace.azurecr.io. I solved it by using the helm chart from the repo https://charts.bitnami.com/bitnami.

> Hi!
> 
> Did you follow these instructions? https://docs.bitnami.com/azure/get-started-cnab/

I did as a workaround but is very cumbersome and a manual process which is not feasable in production for us.

**Comment by daniemarquesorigo** [comment]
> Can confirm, 30 minutes ago one of the pods didn't succeed with pulling the image, the same problem. I'm afraid it can happen with the prod env in any moment.

Yes, it did happened to us when a pool scaled up. I had to recreate the cluster using the oficial bitnami repo https://charts.bitnami.com/bitnami

**Comment by daniemarquesorigo** [comment]
The only solution is migrating the chart to use the official bitnami chart and upgrade the deploy as follows:

`helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

helm upgrade <youredis> bitnami/redis
`

This will resolve the problem without loss of configuration.
