### ISSUE TITLE
prometheus federeration broken with latest images.

### ISSUE THREAD

**Issue by binayaj** [bitnami/charts#23028]
### Name and Version

bitnami/prometheus 2.49.1-debian-11-r3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We are running two instances of Prometheus and one Prometheus is pulling metrics of the other using federation. With the old image, that we are currently using (v2.28.1-debian-10-r22), federation works fine. But as soon as we update the Prometheus image to 2.49.1-debian-11-r3, Prometheus works locally, but federated doesn't work at all. It cannot scrape metrics and gives the following error:
```
Error:
Get "https://federatedprometheus.domain.net:443/federate": unexpected EOF"
```
### Are you using any custom parameters or values?

no

### What is the expected behavior?

the main Prometheus is supposed to pull metrics from the federated Prometheus instance.

### What do you see instead?
```
Error:
Get "https://federatedprometheus.domain.net:443/federate": unexpected EOF"
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment. Please note there is a jump of several different versions between both images.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
