### ISSUE TITLE
[bitnami/postgresql-ha] Repmgr Data resync Issue

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [bitnami/charts#23034]
### Name and Version

bitnami/postgresql-ha 12.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using the bitnami PostgreSQL HA with Kubernetes as helm chart. I have the 3 master nodes and 2 worker nodes.
When the pod get restarts , the data itself fully removed and start syncing the data from beginning.
Is the above process working actually by nature ?
                  (or)
Is there any other option to clear this Issue?

### Are you using any custom parameters or values?

```
postgresql:
  postgresPassword: admin@123
  password: admin@123
  database: kubeapp
  repmgrPassword: admin@123
  repmgrConnectTimeout: 2
  repmgrReconnectAttempts: 1
  repmgrReconnectInterval: 2
  repmgrChildNodesCheckInterval: 2
  repmgrChildNodesDisconnectTimeout: 5
  replicaCount: 3
  image:
    debug: true

service:
  type: NodePort

volumePermissions:
  enabled: true

pgpool:
  adminPassword: admin@123
  replicaCount: 2
  customUsers:
     usernames: postgres
     passwords: admin@123

persistence:
  storageClass: "nfs-client"
  size: 50Gi``
```

### What is the expected behavior?

No need to data gets remove and resync the data from beginning , when pod restarts

### What do you see instead?

the data gets removed and resync the data from beginning , when pod restarts

**Comment by javsalgar** [comment]
Hi,

At the moment this is the solution by default. We have an experimental feature to use pg_rewind 

```
postgresql:
  ## EXPERMENTAL: Use pg_rewind for standby failover
  ## @param postgresql.usePgRewind Use pg_rewind for standby failover (experimental)
  ##
  usePgRewind: false
```

In case this does not work, it wtill fallback to removing the data.

**Comment by Sardonyxtechsupport** [comment]
Hi, 
      You mentioning "This is an Experimental Feature".
      Can I have some other solutions for fix this Issue ?

**Comment by javsalgar** [comment]
I'm afraid there no other options at the moment.

**Comment by Sardonyxtechsupport** [comment]
anyone could you give me the solution as soon as possible

**Comment by cjreyn** [comment]
We're also seeing this issue. Are there any plans to address it?
