### ISSUE TITLE
[bitnami/ingress-nginx-controller] tcp service unreachable after upgrade

### ISSUE THREAD

**Issue by wvengen** [bitnami/charts#23049]
### Name and Version

bitnami/ingress-nginx-controller 10.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

After an upgrade of 9.11.0 to 10.3.0 the [tcp services](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/) stopped being reachable. http/https traffic had no issues.

In our chart values, we use:
```yaml
tcp:
  9876: namespace/database-service:5432
```

so that a database can be reached from the outside. This used to work with 9.11.0, but not after the upgrade to 10.3.0.

### What is the expected behavior?

```sh
psql -h x.x.x.x -p 9876
```
```
Password for user <user>:
```

### What do you see instead?

```sh
psql -h x.x.x.x -p 9876
```
```
psql: error: connection to server at "x.x.x.x", port 9876 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

### Additional information

After some debugging, it turns out that disabling the newly introduced network policy (I suppose that would be https://github.com/bitnami/charts/pull/22874) makes the external tcp service reachable again

```yaml
networkPolicy:
  enabled: false
```

It looks like it would be helpful to add the external services to the network policy.

**Comment by javsalgar** [comment]
Hi,

This is strange because the controller by default is having an open egress (precisely because we could not predict what services would be connected). 

```
k describe netpol

Spec:
  PodSelector:     app.kubernetes.io/component=default-backend,app.kubernetes.io/instance=nginx-ingress-controller,app.kubernetes.io/name=nginx-ingress-controller        
  Allowing ingress traffic:
    To Port: 8080/TCP
    From: <any> (traffic not restricted by source)
  Allowing egress traffic:
    To Port: <any> (traffic allowed to all ports)
    To: <any> (traffic not restricted by destination)
  Policy Types: Ingress, Egress
```

Could you let us know which cluster you are using? Also, could you confirm that adding the port in the extraEgress section works?

```
networkPolicy:
  extraEgress:
    - port: 9876
```

**Comment by wvengen** [comment]
Thank you for your reply!

`kubectl describe netpol` shows for the ingress controller
```
PodSelector:     app.kubernetes.io/component=controller,app.kubernetes.io/instance=system,app.kubernetes.io/name=ingress-nginx
Allowing ingress traffic:
  To Port: 8080/TCP
  To Port: 8443/TCP
  To Port: 10254/TCP
  From: <any> (traffic not restricted by source)
Allowing egress traffic:
  <none> (Selected pods are isolated for egress connectivity)
Policy Types: Ingress, Egress
```

Thank you for putting me on the egress track. The network policy seems to need two additions:
1. Add 9876 as an ingress port
2. Add 5432 as an egress port

That can be achived by setting the following options in the values file:

```yaml
networkPolicy:
    allowExternalEgress: false
    extraEgress:
      - ports:
        - port: 5432
          protocol: TCP
    extraIngress:
      - ports:
        - port: 9876
          protocol: TCP
```

I'm using a Kubernetes v1.26.6 cluster on OpenStack (with [Gardener](https://gardener.cloud/) for the Kubernetes cluster), with a LoadBalancer for the ingress controller.

**Comment by wvengen** [comment]
It seems to me that perhaps when `allowExternalEgress` is `true` (the default), the network policy's `policyTypes` should exclude `Egress` (instead of just having a default egress policy).

**Comment by javsalgar** [comment]
Do you happen to know which network plugin does your k8s installation use? 

According to the Kubernetes documentation, this should allow all egress traffic:

https://kubernetes.io/docs/concepts/services-networking/network-policies/#allow-all-egress-traffic

```
egress:
  - {}
```

You can see it in other non-bitnami projects like upstream kube-prometheus

https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/alertmanager-networkPolicy.yaml

So I wonder if it is some issue with a given CNI plugin

**Comment by wvengen** [comment]
The networking config for Gardener is:

```yaml
  networking:
    type: calico
    providerConfig:
      overlay:
        enabled: true
    pods: 100.a.a.a/16
    nodes: 10.b.b.b/16
    services: 100.c.c.c/13
    ipFamilies:
      - IPv4
```

I suppose that would use [Calico CNI](https://github.com/projectcalico/calico/tree/master/cni-plugin) ([network policy docs](https://docs.tigera.io/calico/latest/network-policy/)). The Gardener version is v1.84.2.

[The k8s netpol docs](https://kubernetes.io/docs/concepts/services-networking/network-policies/#allow-all-egress-traffic) mention that indeed the `egress: [ {} ]` config would allow all egress traffic.

**Comment by wvengen** [comment]
Looking through calico's changelog, I found https://github.com/projectcalico/calico/pull/7148, which I don't fully grasp but do get that something with updating policies didn't function correctly. When removing the policy that has the extra ingress port added but an egress policy of `[ {} ]`, and recreating it, it works as expected.

So yes, this is likely to be a bug in calico's cni-plugin. I think the issue can be closed then (and I'll reopen if it turns out to be something else). Thanks for pointing in the right direction!

**Comment by wvengen** [comment]
Perhaps what remains is then: perhaps extra tcp (and udp) services would need to be added to the ingress network policy?

**Comment by javsalgar** [comment]
Hi,

Could you let us know which default nginx-ingress-controller ports we're missing to configure?

**Comment by wvengen** [comment]
The default controller network policy has ingress ports 8080 (for http), 8443 (for https) and 10254 (for metrics).
When exposing [tcp services](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/) using the chart, these were not added to the ingress network policy. The result is that exposed tcp services are not accessible. (This is probably true for udp services as well.)

In the case described in this issue, port 9876 was missing from the ingress network policy for the ingress controller.

**Comment by javsalgar** [comment]
Could you check if the PR above fixes the issue?

**Comment by javsalgar** [comment]
Thanks for confirming!
