### ISSUE TITLE
MongoDB replicaset service

### ISSUE THREAD

**Issue by rodrigodlima** [bitnami/charts#2304]
Hi, 

This is a doubt about the bitnami/mongodb chart. When I exec the chart with replicaset=true, the chart create two services: 

my-release-mongodb
my-release-mongodb-headless

On the first service (my-release-mongodb) there is only one endpoint to mongodb-primary pod. The second service (my-release-mongodb-headless) there are 3 endpoints (1 pod arbiter, 1 pod slave and 1 primary pod).

I want to expose this service from outside the cluster, if I expose the first service, the only pod that will receive connection is the "mongodb-primary".  If I expose the second service, all the pod will receive connections, including arbiter pod. It's correct?

There is a way to create a service only with the primary's and secondary's pods, without arbiters?

**Comment by juan131** [comment]
Hi @rodrigodlima 

The headless service cannot be exposed to the outside and it's only intended for internal use. It' used to provide unique network identifiers per pod.

At this moment, you can only access the primary nodes from the outside since, as you mentioned, no dedicated service is created for secondary nodes. Secondary nodes just replicate the data available in the primary node, unless this node is unavailable. When the primary node is unavailable, a secondary node will take the primary role. Mor information in the link below:

- https://docs.mongodb.com/manual/replication/#replication-in-mongodb

Write operations are only allowed in the primary node. This chart asumes all read operations are also done through the primary node, since there could be inconsistencies in secondary nodes when using asynchronous replication. Check the link below for more information:

- https://docs.mongodb.com/manual/replication/#read-operations

**Comment by rodrigodlima** [comment]
Hi Juan, thank you for explaining. There is an option on MongoDB that permit read operations in secondary nodes, but really, it's may return data that does not reflect the state of the data on the primary.
But, in this case, where read and write operations are allowed only on primary node and there is only one service, whats the correct connection string to use? mongodb://user:password@mongo.svc.local:27017/?replicaSet=rs0 or a standlone string: mongodb://user:password@mongo.svc.local:27017/db ?

**Comment by juan131** [comment]
Hi @rodrigodlima 

It depends on whether you're accessing your MongoDB setup from outside, or inside the K8s cluster. If you run the command below, you'll obtain sth like this:

```console
$ helm status my-release
MongoDB can be accessed via port 27017 on the following DNS name from within your cluster:

    mongodb.default.svc.cluster.local

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.2.5-debian-10-r44 --command -- mongo admin --host mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/mongodb 27017:27017 &
    mongo --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD
```

There you'll find the instructions to connect both from outsider or inside the cluster ⏫

**Comment by alankwon** [comment]
Hi, I was wondering about the same thing... I'd appreciate if you could clarify few things for me.

So, if the primary-0 goes down and secondary-0 takes over the primary role, but my-release-mongodb service is tied to primary-0, how does the secondary-0 receive the write/read requests from the application? Wouldn't all requests be on hold until primary-0 comes back? Also, does primary-0 take back the primary role as soon as it comes back?

If the secondary-0 doesn't process any write/read request while primary-0 is up and it's not reachable even when it takes the primary role, what exactly is secondary-0 is used for?

BTW, if secondary-0 really takes over the primary role, the current naming convention is very confusing.

**Comment by emrahcetiner** [comment]
in readme file:

> Some characteristics of this chart are:
> 
> - Each of the participants in the replication has a fixed stateful set so you always know where to find the primary, secondary or arbiter nodes.

when disaster scenario occurred, chart's characteristics crashes.
I am not sure that the usage is correct with a fixed stateful set.

**Comment by Mauraza** [comment]
I just create a PR for if the secondary takes the primary role the cluster, the cluster continue working.

**Comment by emrahcetiner** [comment]
> BTW, since secondary-0 takes over the primary role when primary-0 goes down, the current naming convention is very confusing.

primary-0 takes back immediately the primary role after goes up. In a disaster scenario, the naming convention is confusing. I agree but it doesn't take a long time.
