### ISSUE TITLE
Rabbitmq pod pending indefinitely on chart install

### ISSUE THREAD

**Issue by nicole-brewer** [bitnami/charts#2306]
**Which chart**:
name: bitnami/rabbitmq 
chart version: 6.25.2
app version: 3.8.3

**Describe the bug**       
I've tried to install rabbitmq on my single node kubernetes cluster, but the pod stays pending indefinitely.

**To Reproduce**
1. Used `kubeadm` to initialize an untained single node cluster with weavenet networking. All good there.
1.`helm repo add bitnami https://charts.bitnami.com/bitnami`
2. `helm install rabbitmq -f rabbitmq.yaml bitnami/rabbitmq` in the same directory as my yaml file, which is a replica of the example containing a secret definitions file
3. `kubectl get pods` gave me
```
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
default       rabbitmq-0                                0/1     Pending   0          9m7s
```
4.  Tried without my config to make sure that wasn't the problem, `helm install rabbitmq bitnami/rabbitmq` but got the same result.

**Version of Helm and Kubernetes**:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @nicole-brewer ,
In this case, it would be helpful if you can share the output of the following command:
```console
kubectl describe pod <pod-name>
```
Also, provide the `describe` of the deployment too.

This kind of issue is normally caused by volumes not being attached. Did you configure the dynamic volume provisioning in your cluster?

**Comment by nicole-brewer** [comment]
I didn't have any kind of persistent storage set up, so I couldn't use dynamic volume provisioning. Thanks for response!
