### ISSUE TITLE
[bitnami/mongodb] clusterDomain values forces to use only FQDN

### ISSUE THREAD

**Issue by antonioberben** [bitnami/charts#2312]
**Which chart**:
mongodb (7.10.10)

**Is your feature request related to a problem? Please describe.**
There is a value: `clusterDomain` which is used in:
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/statefulset-arbiter-rs.yaml#L111
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/statefulset-primary-rs.yaml#L126
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/statefulset-secondary-rs.yaml#L129

The implementation always uses the FQDN to resolve the DNS. i.e:
- `mongo-headless.svc.cluster.local`
or
- `mongo-headless.svc.[CUSTOM_DOMAIN]` [THIS IS MY CASE]

This makes to not use the default kubernetes options for resolving dns:
1. `svc_name` 
2. `svc_name.namespace` 
3. `svc_name.namespace.svc.cluster_domain` [THIS IS THE ONLY POSSIBILITY]

This makes the chart to loose versatility. 

**Describe the solution you'd like**
In my personal case, due to cluster setup, it would be handier if this chart offers options `1.` and `2.`
So that I could not be forced to set a value for `clusterDomain` always. Option `1.` (resolution by service name) would be enough.

**Describe alternatives you've considered**
Instead of adding a default value in [clusterDomain value](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L122), just leave it empty.
Then in the template, something like:
```
{{- if .Values.replicaSet.clusterDomain }}
  - name: MONGODB_ADVERTISED_HOSTNAME
    value: "$(MONGODB_POD_NAME).{{ template "mongodb.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
{{- else }}
  - name: MONGODB_ADVERTISED_HOSTNAME
    value: "$(MONGODB_POD_NAME).{{ template "mongodb.fullname" . }}-headless.{{ .Release.Namespace }}"
{{- end }}
```

**Comment by dani8art** [comment]
Hi @antonioberben, headless service is just for the mongo instances to communicate between themself inside the cluster, you should be able to connect with the [primary service](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/svc-primary-rs.yaml#L5) just using the default kubernetes options for resolving dns.

why do you need to connect to the headless service?

I think it would be good if you have the chance you could open a PR and we could discuss this on it, what do you think?

**Comment by antonioberben** [comment]
Hi @dani8art. Sure, I will open a PR to discuss.
The reason to use the headless service is that, in the case of having a cluster (i.e. 1 primary + 3 secondary + 1 arbiter) and the primary goes down, the remaining members of replicaset vote to select a new primary. 

Thus, a secondary becomes a primary. **But only at replicaset-topology-level.** Because at kubernetes level, `primary service` still points to the pod from `primary statefulset` ([here why](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/svc-primary-rs.yaml#L43) ) which is now down.

Then, the primary pod is back online, tries to re-join the replicaset, replication of data happens, and the new voting gets him the status of primary online when it is ready with all replicated data, which consumes certain period of time.

Until then, if our app points to primary service, it returns an error since pod is not ready yet. 

In the other hand, if our app points to the full set of IPs using the headless service, it always survives and resolve to connect to a one secondary pod (elected as primary in mongo topology).

Bit confusing :)
