### ISSUE TITLE
[bitnami/mongodb] Installation failed when metrics enabled

### ISSUE THREAD

**Issue by semihbkgr** [bitnami/charts#23172]
### Name and Version

bitnami/mongodb 14.8.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

```bash
$ helm install mongo oci://registry-1.docker.io/bitnamicharts/mongodb --set="metrics.enabled=true"
Error: INSTALLATION FAILED: template: mongodb/templates/networkpolicy.yaml:52:26: executing "mongodb/templates/networkpolicy.yaml" at <.Values.metrics.containerPorts.metrics>: nil pointer evaluating interface {}.metrics
```

### Are you using any custom parameters or values?

--set="metrics.enabled=true"

### What is the expected behavior?

Install mongodb with exporter sidecar container

### What do you see instead?

Error: INSTALLATION FAILED: template: mongodb/templates/networkpolicy.yaml:52:26: executing "mongodb/templates/networkpolicy.yaml" at <.Values.metrics.containerPorts.metrics>: nil pointer evaluating interface {}.metrics

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by evilprince** [comment]
is this fixed ?
having same issue

**Comment by semihbkgr** [comment]
@evilprince no, the fix PR has not been merged yet.

**Comment by javsalgar** [comment]
I enabled auto-merge so it's merged once the verification passes.
