### ISSUE TITLE
[bitnami/haproxy] Automatic pod reload when using existingConfigmap and chart as a subchart

### ISSUE THREAD

**Issue by malkops** [bitnami/charts#23176]
### Name and Version

bitnami/haproxy 0.13

### What is the problem this feature will solve?

Automatic pod reload when using existingConfigmap 
We want to use configmap templating for dynamic generation, but if we specify the existingConfigmap parameter, no annotation is added

### What is the feature you are proposing to solve the problem?
 
I don't have any idea actually

**Comment by javsalgar** [comment]
Hi,

Maybe you could try adding configmap-reload as a sidecar. We have a bitnami container for this solution https://github.com/bitnami/containers/tree/main/bitnami/configmap-reload

**Comment by malkops** [comment]
Hi, can you give a hint, use how to set up the sidecar correctly, the link https://docs.bitnami.com/kubernetes/apps/haproxy/configuration/configure-sidecar-init-containers/ returns 404

**Comment by carrodher** [comment]
Sorry, this kind of documentation were moved to the chart README, you can find it now at https://github.com/bitnami/charts/tree/main/bitnami/haproxy#use-sidecars-and-init-containers

**Comment by malkops** [comment]
According to the documentation https://github.com/jimmidyson/configmap-reload/blob/main/README.md, configmap-reload sidecar won't help as it only sends the signal via http. Maybe your image can send restart signal in some other way?

**Comment by carrodher** [comment]
The Bitnami ConfigMap Reload image can be found at https://github.com/bitnami/containers/tree/main/bitnami/configmap-reload. It seems you're using a different one. Not sure if bitnami/configmap-reload fits better for your use case.

**Comment by malkops** [comment]
You are right and according to the documentation item https://github.com/bitnami/containers/tree/main/bitnami/configmap-reload#configuration, the configuration is described here https://github.com/jimmidyson/configmap-reload/blob/master/README.md as I pointed out above

Based on the documentation, ConfigMap Reload is not suitable as a solution when using helm chart as subchart

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
