### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Network policy blocks call to admission webhook

### ISSUE THREAD

**Issue by mruoss** [bitnami/charts#23181]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.15.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install the chart with network policies enabled (default)
2. Try to add a VHost using the messaging topology operator
3. Check the logs of the messaging topology operator pods to see that the webhook calls fail

### What is the expected behavior?

I expect the default settings for network policy to allow ingress for admission webhook calls

### What do you see instead?

In the logs I see this:
```
"error":"failed to Update object with controller reference: Internal error occurred: failed calling webhook \"vpermission.kb.io\": failed to call webhook: Post \"https://rabbitmq-system-rabbitmq-messaging-topology-operator-webhook.rabbitmq-system.svc:443/validate-rabbitmq-com-v1beta1-permission?timeout=10s\": EOF"
```

### Additional information

All works fine if I disable network policies.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I created this PR to fix the issue https://github.com/bitnami/charts/pull/23200

Depending on the Kubernetes installation, it seems that the apiserver -> pod communication needs to be modelled in the network policy. We enable this ingress rule by default and that should help us to avoid issues.

**Comment by mruoss** [comment]
Hi @javsalgar 
Could you make sure this is deployed? Apparently the CD pipeline failed: https://github.com/bitnami/charts/actions/runs/7828503998

**Comment by javsalgar** [comment]
Hi!

I triggered a new release of the chart to ensure that the feature is there.
