### ISSUE TITLE
Openshift support for dokuwiki

### ISSUE THREAD

**Issue by chokdee** [bitnami/charts#2318]
**Which chart**:
Dokuwiki charts

**Is your feature request related to a problem? Please describe.**
I have tried to install the dokuwiki helm charts to our openshift infrastructure. But it failed because apache cannot run as root and lower ports are not supported. So I have tried to change the Dockerimage file. But still struggeling.

**Describe the solution you'd like**
Please make the Dokuwiki runnable on Openshift.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by beltran-rubo** [comment]
Hi @chokdee, OpenShift is not a platform supported for Dokuwiki. As you mention the container is configured as "root" by default and that requires changes to fully support this platform.

**Comment by chokdee** [comment]
Hi @beltran-rubo 
Openshift is kubernetes. But some of the security constraints (at least running as root) are not allowed in Openshift.

**Comment by beltran-rubo** [comment]
Yes we are familiar with that. Most of our catalog, infrastructure solutions mainly, are already non-root containers but we need to allocate time and effort to do changes for other apps like Dokuwiki.
