### ISSUE TITLE
[bitnami/cassandra] helm chart is creating 2 services when i install it using helm? Which service my client container should connect to?

### ISSUE THREAD

**Issue by madhugarimilla** [bitnami/charts#23194]
### Name and Version

bitnami/cassandra-10.8.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In GKE environment with Kubernetes 1.25 and helm 3.10.2, I am trying to install a 3 node cassandra using the below command 

helm install cassandra oci://registry-1.docker.io/bitnamicharts/cassandra --set replicaCount=3

When i list the services using 'kubectl get svc', it displays 2 services. one is with the name cassandra and the other is with the name cassandra-headless . 

I would like to know which service that i should use to connect java client which is running in a different container in the same namespace? What is the purpose of each of these services?

### Are you using any custom parameters or values?

--set replicaCount=3

### What is the expected behavior?

I would like to understand how to use the cassandra helm chart in k8s environment and purpose of having multiple services and which service to use by the client programs.

### What do you see instead?

When i list the services using 'kubectl get svc', it displays 2 services. one is with the name cassandra and the other is with the name cassandra-headless . 
```
-bash-4.2# kubectl get svc
NAME                 TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)                               AGE
cassandra            ClusterIP   240.128.140.118   <none>        9042/TCP,8080/TCP                     38m
cassandra-headless   ClusterIP   None              <none>        7000/TCP,7001/TCP,7199/TCP,9042/TCP   38m
```

**Comment by javsalgar** [comment]
Hi,

The headless service is for internal communication, you should use the regular `cassandra` one.
