### ISSUE TITLE
(Rancher + Wordpress)  Access denied for user 'bn_wordpress'@'conainer_ip' (using password: YES)

### ISSUE THREAD

**Issue by DavidM-772424** [bitnami/charts#23207]
### Name and Version

bitnami/wordpress-19.2.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install Rancher with RKE + helm and kubectl.
2. add hetzner node driver, to manage clusters on hetzner cloud.
3. do
```
helm repo add wordpress https://charts.bitnami.com/bitnami
helm pull wordpress/wordpress
```

4. Adjust setting `Loadbalancer` to a `clusterip` and add password bellow username in mysql config parameters on the values.yaml

5. deploy and check container logs. 
6. You should see. 
```
ERROR 1045 (28000): Access denied for user 'bn_wordpress'@'10.42.1.99' (using password: YES)
2024-02-06T14:56:40.777966602Z wordpress 14:56:40.77 DEBUG ==> Executing SQL command:
SELECT 1
2024-02-06T14:56:40.787638376Z /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 1045 (28000): Access denied for user 'bn_wordpress'@'10.42.1.99' (using password: YES)
wordpress 14:56:45.80 ERROR ==> Could not connect to the database
```

### Are you using any custom parameters or values?

Adjust setting in values.yaml `Loadbalancer` to a `clusterip` and add password bellow username in mysql config parameters on the values.yaml

### What is the expected behavior?

The expected behavior is that the container start on rancher with rke managed by with hetzner node drive.
My main goal is to deploy 100-200 wordpress website on the rancher cluster fleed. with 5 workers and 3 etc, 1 controlplane.

### What do you see instead?

ERROR 1045 (28000): Access denied for user 'bn_wordpress'@'10.42.1.99' (using password: YES)
wordpress 14:56:45.80 ERROR ==> Could not connect to the database

### Additional information

If some one has an ideia or know a fix for this it will be appreciated.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
