### ISSUE TITLE
[bitnami/harbor] Unable to pull Harbor chart

### ISSUE THREAD

**Issue by vtrenton** [bitnami/charts#23217]
### Name and Version

bitnami/harbor

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I cannot seem to be able to pull the helm chart using the instructions in the repo:
https://github.com/bitnami/charts/tree/main/bitnami/harbor/#tldr

```
$ helm install my-release oci://registry-1.docker.io/bitnamicharts/harbor
Error: INSTALLATION FAILED: GET "https://registry-1.docker.io/v2/bitnamicharts/harbor/tags/list": unable to retrieve credentials
```

Do I need to auth to this registry? I don't see anything in the README? Thanks!

### What is the expected behavior?

installation of Harbor

### What do you see instead?

Error: INSTALLATION FAILED: GET "https://registry-1.docker.io/v2/bitnamicharts/harbor/tags/list": unable to retrieve credentials

**Comment by javsalgar** [comment]
Hi! Could you check the solution here? https://github.com/bitnami/charts/issues/20314

**Comment by adamency** [comment]
> https://github.com/helm/helm/issues/12423

@javsalgar Again, this is NOT the same issue.

The error here is:

```
unable to retrieve credentials
```

While the error in the upstream issue is:

```
401 Unauthorized
```

These are not the same errors.

**Comment by vtrenton** [comment]
For full disclosure - I do not own a Mac - This issue was 100% Linux focused.

**Comment by adamency** [comment]
@vtrenton Yes, this has nothing to do with your original problem. But this is the only existing issue here which contains this specific error text. So I didn't want to make a new issue when I already had found the solutions. I was simply giving the solution to others who will surely wander here when encountering this major issue of a docker bug in mac, which impacts `helm` and many other tools which rely on `docker`.
