### ISSUE TITLE
Bitnami/kafka won't install with custom maxMessageBytes

### ISSUE THREAD

**Issue by edemen** [bitnami/charts#2321]
**Which chart**:

bitnami/kafka

**Describe the bug**
Installation fails with unclear error message.

**To Reproduce**
Run `helm install kafka bitnami/kafka --set maxMessageBytes=20971520`

Error message:
```
Error: template: kafka/templates/statefulset.yaml:244:62: executing "kafka/templates/statefulset.yaml" at <"">: wrong type for value; expected string; got float64
```

**Expected behavior**
I would expect the installation to finish or an appropriate error to be shown.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @edemen 

Could you try adding an underscore (`_`) before the number as it's set in the default values.yaml (see https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L154)?

```console
$ helm install kafka bitnami/kafka --set maxMessageBytes=_20971520
```

**Comment by edemen** [comment]
Yes this works, thank you
