### ISSUE TITLE
Sonarqube - LDAP Existing Secret

### ISSUE THREAD

**Issue by vicgb** [bitnami/charts#23212]
### Name and Version

bitnami/sonarqube

### What is the problem this feature will solve?

LDAP Password by Kubernetes Secret. Is there any reason why the LDAP password has to be inserted in plain text?

### What is the feature you are proposing to solve the problem?

The idea is to do something similar to what is done for SMTP authentication, for LDAP. 

I think it would be safest to pick up that value from a kubernetes secret.

### What alternatives have you considered?

Modify by hand the deployment.yaml , _helpers.tpl and values.yaml files

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
