### ISSUE TITLE
Prometheus Chart.yaml updated with invalid images

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#23262]
### Name and Version

bitnami/prometheus 0.9.3

### What architecture are you using?

None

### What steps will reproduce the bug?

A recent automated commit that was released as Prometheus chart 0.9.3 changed the `images` value inside `Chart.yaml` with bad values:

https://github.com/bitnami/charts/pull/23258/files#diff-111c23447e2001b03f6ed4da8fb85fa676fbeab3bf659f29b99a6cd8c0c46dd7

**Comment by bpfoster** [comment]
Not limited to just Prometheus.  A quick sampling:

https://github.com/bitnami/charts/commit/0e510528a0507c249e6edb8c4be65744ae3b126e#diff-2e2b0c8d347c6cd68d28b03042255abe54a7671a6b025ad3d9b3d23c6d195d02
https://github.com/bitnami/charts/commit/e0deb389f59c360654b01d8e40154553db7f000b#diff-8a52c8c87702a451aab5a58cd712558a85606591c5eab81dcbbbdefcd93c445a
https://github.com/bitnami/charts/commit/1885589b2fe4d79e2eee1533c190487868cf7a34#diff-baa74b9171bae4a29e4edb9df324b5941099231d2d58dec52929c65048f52c8d

**Comment by antgamdia** [comment]
Hi @bpfoster, @steache, thanks for reporting this issue. It was a bug we introduced in a recent change today. We have already fixed it and re-triggered an update for those affected charts ([example](https://github.com/bitnami/charts/commit/c430615da13bdde4dcd93de6ee8bb8f7b3fbbc76)).
In the next hours everything will get back to normal.

Sorry for the inconvenience!

**Comment by rgl** [comment]
does this mean that none of these charts are actually tested before being merged?

**Comment by antgamdia** [comment]
No, all the charts are being functionally tested as usual. This bug solely affected to some of our `image` annotations we introduced just some months ago, but the overall quality of the released asset wasn't affected.
For instance, see [this output](https://github.com/bitnami/charts/actions/runs/7813951916/job/21314192492) depicts how the tests were passing before merging the PR. 
That said, apologies for the inconvenience 😅

**Comment by antgamdia** [comment]
👋 I have checked every chart is now back to normal. Thanks again for reporting the issue and sorry for the noise!
Closing issue.
