### ISSUE TITLE
Sync with IBM public cloud failes with: redis-cluster 5.0.8

### ISSUE THREAD

**Issue by gmendel** [bitnami/charts#2329]
**Which chart**:
redis-cluster 5.0.8

**Describe the bug**
Still problem provisioning with defaults (started with https://github.com/bitnami/charts/issues/2292)

Pods are not coming up:

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/4655019/79345707-74d38180-7eff-11ea-9fae-717698af7986.png">

All PVs are bound:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/4655019/79345783-8c126f00-7eff-11ea-9231-0035ba6117c3.png">

Have you tried this on IKS?

**Comment by beltran-rubo** [comment]
Hi Gili, thanks for reporting it. All our Charts are tested in IKS through the pipeline. We are using the new IKS VPC infrastructure that it creates the default Volumes faster. 

It seems the issue is the time since the PVC is created until it is mounted into the pod. We will modify the Chart to use "storageClass: ibmc-block-gold" by default as it is configured for other Charts.

**Comment by gmendel** [comment]
yes.... time can vary from many reasons (location, time of day, ....) we need to extend the timeouts

**Comment by beltran-rubo** [comment]
Right, tested the new version with the "gold" storageClass, Redis Cluster takes ~7 min to be fully ready. You could see there are pods restarting until it is fully deployed.

$ helm install rc3 ibm/redis-cluster --wait --timeout=600s

```
rc3-redis-cluster-0                      1/1     Running                      3          6m37s
rc3-redis-cluster-1                      1/1     Running                      4          6m37s
rc3-redis-cluster-2                      1/1     Running                      3          6m37s
rc3-redis-cluster-3                      1/1     Running                      2          6m37s
rc3-redis-cluster-4                      1/1     Running                      2          6m37s
rc3-redis-cluster-5                      1/1     Running                      0          6m37s
rc3-redis-cluster-cluster-create-gjchp   0/1     Completed                    0          14s
```
