### ISSUE TITLE
[bitnami/supabase] Add imgproxy service + S3 object-storage

### ISSUE THREAD

**Issue by colin-chadwick** [bitnami/charts#23300]
### Name and Version

bitnami/supabase 0.23.11

### What is the problem this feature will solve?

The Supabase Helm Chart is missing the imgproxy and an option to configure an external S3 object-storage, see [ENV variables in Docker file of Supabase](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L230-L237). This feature is quite important, not everyone wants to persist storage data on their own server. Additionally, image resizing won't work without the imgproxy.

### What is the feature you are proposing to solve the problem?

Add option to configure external object-storage + the imgproxy service.

**Comment by dgomezleon** [comment]
Hi @colin-chadwick,

Thanks for reporting it. I have created an internal task to review the issue.
