### ISSUE TITLE
[bitnami/redis-cluster]-AOF Functionality Issue: Keys are getting stored in the Aof file from only one node not from the entire redis-cluster.

### ISSUE THREAD

**Issue by Harish27012002** [bitnami/charts#23327]
### Name and Version

bitnami/redis-cluster:7.2.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1)Deploy a Bitnami Redis Cluster version 7.2.3 using the image tag: 7.2.3-debian-11-r1. Set it up with 6 nodes and 1 replica.
2)Navigate to the Values.yaml file and update the value for  "useAOFPersistence" to "yes".
3)Open the configmap.yaml file in the template folder. Search for the appendonly configuration and set its value to "yes".
4)Execute some SET commands to interact with the deployed Redis cluster.

### What is the expected behavior?

Expectations:
When exiting the Redis CLI in the Redis cluster, all keys should be stored from across the entire cluster to  AoF file.

### What do you see instead?

However, I've observed that only keys from one node are being stored, rather than collecting keys from all nodes in the cluster.

**Comment by joancafom** [comment]
Hi @Harish27012002 

> When exiting the Redis CLI in the Redis cluster, all keys should be stored from across the entire cluster to AoF file.

>However, I've observed that only keys from one node are being stored, rather than collecting keys from all nodes in the cluster.

I believe this is certainly a question related to the asset instead to our chart packaging. I can see that when AOF feature is enabled, `redis` definitely persists the data in files across the cluster, but not in every single node. This might be the desired behaviour, as maybe it is inefficient to have a complete replication of the data in every node. From my tests, I can see the data is replicated in 2 out of 6 nodes in the cluster, which does not seem like a bad approach to me.

In any case, I am not an expert in Redis, so I'd say that if you have further concerns you should reach out to the official Redis community forum.

>1)Deploy a Bitnami Redis Cluster version 7.2.3 using the image tag: 7.2.3-debian-11-r1. Set it up with 6 nodes and 1 replica.
2)Navigate to the Values.yaml file and update the value for "useAOFPersistence" to "yes".
3)Open the configmap.yaml file in the template folder. Search for the appendonly configuration and set its value to "yes".
4)Execute some SET commands to interact with the deployed Redis cluster.

One side node in your steps: you don't need to perform step 3, the chart will automatically change the value for you on runtime!

Hope it helps!

**Comment by Harish27012002** [comment]
Hi @joancafom Thanks for your reply.
