### ISSUE TITLE
rgcluster

### ISSUE THREAD

**Issue by Harish27012002** [bitnami/charts#23325]
### Name and Version

rgcluster:latest

### What is the problem this feature will solve?

Need a helm chart for the rgcluster so that aof and snapshot problem will be solved .

### What is the feature you are proposing to solve the problem?

I have tried the rgcluster image for the aof it was working as expected.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
