### ISSUE TITLE
NGINX | checksum/server-block-configuration is not applied when no podAnnotation is set

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#2333]
**Which chart**:
nginx

**Describe the bug**
If the `podAnnoation` is not set, the `checksum/server-block-configuration` annoation is not printed.

**To Reproduce**
1. deploy helm chart with `serverBlock`
2. change server block
3. deploy again
4. the pods are not destroyed, due to the missing `checksum/server-block-configuration`

**Expected behavior**
The `checksum/server-block-configuration` should always be set if the `serverBlock` is used

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by juan131** [comment]
Thanks for reporting this @aeimer !! I just created a PR to address it
