### ISSUE TITLE
external-dns v6.32.0 missing from OCI registry

### ISSUE THREAD

**Issue by peikk0** [bitnami/charts#23356]
### Name and Version

registry-1.docker.io/bitnamicharts/external-dns 6.32.0

### What architecture are you using?

None

### What steps will reproduce the bug?

```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 6.32.0
```

### What is the expected behavior?

`helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 6.32.0` fetches `external-dns-6.32.0.tgz`

### What do you see instead?

```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 6.32.0
Error: registry-1.docker.io/bitnamicharts/external-dns:6.32.0: not found
$ helm show chart oci://registry-1.docker.io/bitnamicharts/external-dns
Pulled: registry-1.docker.io/bitnamicharts/external-dns:6.31.5
...
```

**Comment by carrodher** [comment]
Thanks for reporting it. We had an issue with the synchronization we have in place to publish the charts in DockerHub. I forced a new release (6.32.1) at https://github.com/bitnami/charts/pull/23362 which produced this new version to be already published in DockerHub, see [bitnamicharts/external-dns:6.32.1](https://hub.docker.com/layers/bitnamicharts/external-dns/6.32.1/images/sha256-d3c368daadf3a4c0f16a2c640274164419caba4ee58d6512dd3a5f6d4c8f9e3f?context=explore)
