### ISSUE TITLE
[bitnami/joomla] Add serviceMonitor if metrics is enabled

### ISSUE THREAD

**Issue by xxkel-sd** [bitnami/charts#23363]
### Name and Version

bitnami/joomla 18.2.3

### What is the problem this feature will solve?

When enabling metrics the chart doesn't automatically setup a ServiceMonitor. So even if the metrics endpoint is available no metrics are collected

### What is the feature you are proposing to solve the problem?

Add a ServiceMonitor template to the chart like the one you will find in MariaDB Helm Chart (https://github.com/bitnami/charts/blob/main/bitnami/mariadb/templates/servicemonitor.yaml)

### What alternatives have you considered?

none

**Comment by javsalgar** [comment]
Hi,

If the ServiceMonitor CRD is not enabled then the deployment would fail, that's why it's set as optional so users can enable metrics without the operator.
