### ISSUE TITLE
Support for two way SSL authentication in Kafka Charts

### ISSUE THREAD

**Issue by etavene** [bitnami/charts#2338]
Hi 

**Which chart:**
Kafka Current Chart

**Is your feature request related to a problem? Please describe.**

Does Kafka Charts supports two way SSL authentication ? 

The below information from statefulset yaml shows that one-way SSL is supported. Is my assumption correct ? 

   _{{- else if and .Values.auth.ssl (not .Values.auth.enabled) }}
              value: "SSL://$(MY_POD_NAME).{{ template "kafka.fullname" . }}-headless.}_

If so, how to enable client authentication also?

**Comment by Mauraza** [comment]
Hi @etavene,

Yes, Kafka support SSL. You can find all the information in this section [Enable security for Kafka and Zookeeper](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper) in the README.md

**Comment by etavene** [comment]
@Mauraza 
Thanks for your reply. I had already gone through the document, but I don't see any explicit mention of two-way SSL authentication support in Kafka charts. I want to authenticate the clients also, what configuration changes i need to perform to enable that.

**Comment by Mauraza** [comment]
Hi @etavene,

So far we have only worked on what is published.  We will surely work on it in the future
