### ISSUE TITLE
[bitnami/fluentd] Unable to mount extra volumes

### ISSUE THREAD

**Issue by irizzant** [bitnami/charts#2339]
**Which chart**:
[bitnami/fluentd]

**Describe the bug**
The chart is currently missing the possibility to mount extra volumes inside Fluentd forwarders.
This is needed for example when you need to monitor `systemd' modules and the system store logs outside `/var/log/` path (e.g CentOS, Debian).

**Expected behavior**
Ability to specify extra options in `values` and `values-production` files to mount extra volumes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by rafariossaa** [comment]
Hi @irizzant,
  Could you elaborate a bit on your use case ?
  Dealing with logs is a typically done in the [forwarder](https://docs.fluentd.org/deployment/high-availability).
  Anyway, Pull requests are welcome, so feel free to send them. We will be glad of reviewing them.

**Comment by irizzant** [comment]
@rafariossaa you're right, I updated the Issue text, I wrote 

> The chart is currently missing the possibility to mount extra volumes inside Fluentd aggregators.

but I meant
> The chart is currently missing the possibility to mount extra volumes inside Fluentd **forwarders**.

**Comment by rafariossaa** [comment]
@irizzant I am creating an internal task to add this feature.
We will come back as soon as we have news.

**Comment by irizzant** [comment]
Activity!

**Comment by rafariossaa** [comment]
Hi,
  This task still in our backlog. We will come back as soon as we have news.

**Comment by irizzant** [comment]
@rafariossaa I added a PR for this

**Comment by rafariossaa** [comment]
Hi @irizzant,
  Thank you very much for your PR.
  We are going to review it, you will have news soon.
