### ISSUE TITLE
[bitnami/redis] Redis Sentinel Calling Other Namespaces

### ISSUE THREAD

**Issue by BenHesketh21** [bitnami/charts#23401]
### Name and Version

bitnami/redis 18.0.4 and others

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy the redis chart with sentinel enabled and multiple replicas to 2 different namespaces.

### Are you using any custom parameters or values?

sentinel.enabled=true

### What is the expected behavior?

The two redis instances should coexist without interacting with each other.

### What do you see instead?

They start competing with each other and become 1 redis cluster.

### Additional information

Duplicate of #21855 as it is still an issue

**Comment by BenHesketh21** [comment]
I think it may be to do with the emptyDir volume for sentinel data but I'm not sure

**Comment by milosjanda** [comment]
I also managed to get into this situation, but it's hard to reproduce. I reproduced it by restarting both statefulsets several times. My suspicion is that this happens the moment one of the Redis clusters gets an IP address that was used sometime earlier in the other Redis cluster. But I can't verify this.

**Comment by BenHesketh21** [comment]
Could it be anything to do with the sentinel data volume? Maybe when master nodes start up on the same node or something?

**Comment by CeliaGMqrz** [comment]
Hi @BenHesketh21, @milosjanda 

Sorry for the delay.

I have not been able to reproduce this issue. It is strange, as typically, they wouldn't start on the same node. The volume could be a contributing factor. However, to get to the heart of the matter, could you kindly walk me through the steps you took to encounter this issue? Additionally, any log output related to the error would be immensely helpful. 

Thanks for your feedback.

**Comment by bbrala** [comment]
Grmbl... Im getting the same error, for some reason 2 instances started finding eachother.

```
│  16:58:59.63 INFO  ==> Found previous master redis-node-1.redis-headless.ntvg-cache.svc.cluster.local in /opt/bitnami/redis-sentinel/etc/sentinel.conf                                                                      │
│  16:58:59.63 INFO  ==> about to run the command: timeout 90 redis-cli -h redis.cvte-cache.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster                                                              │
│  16:58:59.64 INFO  ==> printing REDIS_SENTINEL_INFO=(redis-node-1.redis-headless.ntvg-cache.svc.cluster.local,6379)
```

Now after restart the conf already has both instances, so on boot it just takes the existing (bad) set and rolls with it.
