### ISSUE TITLE
[bitnami/argo-cd] ArgoCD marks kafka out of sync on clusterID and passwords

### ISSUE THREAD

**Issue by ingmars1709** [bitnami/charts#23407]
### Name and Version

bitnami/kafka v26.8.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In a Kubernetes environment v1.26.3 using default values for the bitnami Kafka chart, when I update a `replicaCount `of a totally different container (service-XYZ) then consequently ArgoCD detects also changes in the `kafka-kraft-cluster-id` and in `controller-password` and in` interbroker-password`. And as a consequence the kafka controller pod is restarted as well by ArgoCD.

The container (service-XYZ) for which I change the replicaCount is a Kafka consumer/producer.

### Are you using any custom parameters or values?

None

### What is the expected behavior?

That the kafka controller pod is not restarted, because I would expect changing a `replicaCount `of an unrelated container does not trigger changes in Kafka properties.

### What do you see instead?

A restart of the kafka controller pod in Kubernetes triggered by ArgoCD because of the following detected diffs:
```
/Secret fat/kafka-kraft-cluster-id
kraft-cluster-id: ++++++++++++
kraft-cluster-id: ++++++++

/Secret fat/kafka-user-passwords
controller-password: ++++++++++++
inter-broker-password: ++++++++++++

controller-password: ++++++++
inter-broker-password: ++++++++

apps/Deployment fat/service-XYZ
replicas: 1
replicas: 2

apps/StatefulSet fat/kafka-controller
checksum/passwords-secret: 57e719cf52a666876960767777b9cfe8c0f1d955cb546d3c1b960723d021b583
checksum/passwords-secret: a466d6c18da86e041c73d11ebb5b55164ab905b08d3bcaf59c35aeb9fd9ae6cc
```

**Comment by javsalgar** [comment]
Hi!

How is this unrelated container deployed? Are you using the extraDeploy section of the chart? Is Kafka a subchart?

**Comment by ingmars1709** [comment]
Hi,

Thanks for the quick response. 

We use an Chart.yaml which contains a kafka chart of our own. And that chart on its turn contains the real dependency on the bitnami kafka chart. So in that sense it's a subchart.

Also, the Chart.yaml contains the service-XYZ chart. However, we don't use the extraDeploy section.

I fixed it eventually with setting the `existingSecret `and `existingClusterIdSecret` properties to let ArgoCD **not** manage the secrets. 

But the root cause is not clear to me yet if you let ArgoCD

**Comment by javsalgar** [comment]
It seems to me that this should be something to check with the upstream Argo CD devs.
