### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Network policy blocks calls to RabbitMQ for setting up VHost

### ISSUE THREAD

**Issue by MikeFear** [bitnami/charts#23403]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.15.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart with network policies enabled (default)
2. Try to add a VHost using the messaging topology operator
3. Check the events of the VHost where you see that the creation fails.

### What is the expected behavior?

I expect the default settings for network policy to allow ingress for the RabbitMQ port for setting up vhosts, users etc.

### What do you see instead?

There is a FailedDeclare event on the VHost and the vhost has a FailedCreateOrUpdate condition with the following message: 
`Put "http://main.e2e.svc:15672/api/vhosts/e2e-10059": dial tcp 10.0.101.252:15672: i/o timeout`

### Additional information

All works fine if I disable network policies.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. The issue is not in the ingress but in the egress section. We found that also these changes caused issues with istio. The PR above should fix both issues
