### ISSUE TITLE
  Failed to pull image "docker.io/bitnami/bitnami-shell:11-debian-11-r114": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/bitnami/bitnami-shell:11-debian-11-r114": failed to resolve reference "docker.io/bitnami/bitnami-shell:11-debian-11-r114": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by utkarshatembhurkar** [bitnami/charts#23406]
### Name and Version

docker.io/bitnami/rabbitmq:3.11.15-debian-11-r3

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using this configuration with Kustomize to deploy to GKE and getting the error:
Failed to pull image "[docker.io/bitnami/bitnami-shell:11-debian-11-r114](http://docker.io/bitnami/bitnami-shell:11-debian-11-r114)": rpc error: code = Unknown desc = failed to pull and unpack image "[docker.io/bitnami/bitnami-shell:11-debian-11-r114](http://docker.io/bitnami/bitnami-shell:11-debian-11-r114)": failed to resolve reference "[docker.io/bitnami/bitnami-shell:11-debian-11-r114](http://docker.io/bitnami/bitnami-shell:11-debian-11-r114)": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: server
  serviceName: rabbitmq-discovery

  replicas: 1
  updateStrategy:
      # https://www.rabbitmq.com/upgrade.html
      # https://cloud.google.com/kubernetes-engine/docs/how-to/updating-apps
      type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/component: server
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-requests-cpu: 5m
        vault.hashicorp.com/agent-requests-mem: 16Mi
        vault.hashicorp.com/agent-limits-cpu: 10m
        vault.hashicorp.com/agent-limits-mem: 32Mi
    spec:
      serviceAccountName: rabbitmq-sa
      terminationGracePeriodSeconds: 180
      securityContext:
        fsGroup: 1001
      # This init container copies the config files from read-only ConfigMap to writable location.
      initContainers:
      - name: volume-permissions
        image: docker.io/bitnami/bitnami-shell:11-debian-11-r114
        imagePullPolicy: "IfNotPresent"
        command:
          - /bin/bash
        args:
          - -euc
          - |
            # first source the variables to have the RABBITMQ_ERL_COOKIE
            source <(cat /vault/secrets/*.env)
            mkdir -p "/bitnami/rabbitmq/mnesia"
            chown "1001:1001" "/bitnami/rabbitmq/mnesia"
            find "/bitnami/rabbitmq/mnesia" -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
            xargs -r chown -R "1001:1001"

            # Copy the mounted configuration to both places.
            cp /rabbitmqconfig/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
            # Change permission to allow to add more configurations via variables
            chown 1001:1001 /etc/rabbitmq/rabbitmq.conf
            chmod 660 /etc/rabbitmq/rabbitmq.conf
            cp /rabbitmqconfig/enabled_plugins /etc/rabbitmq/enabled_plugins
        securityContext:
          runAsUser: 0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /bitnami/rabbitmq/mnesia
        - name: configmap
          mountPath: /rabbitmqconfig
        - name: config
          mountPath: /etc/rabbitmq

      containers:
      - name: rabbitmq
        image: docker.io/bitnami/rabbitmq:3.11.15-debian-11-r3
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsUser: 1001 
          privileged: false
          allowPrivilegeEscalation: false
        command: ['/bin/bash']
        args:
          - -c
          - |
            source <(cat /vault/secrets/*.env)
            /opt/bitnami/scripts/rabbitmq/entrypoint.sh
            /opt/bitnami/scripts/rabbitmq/run.sh
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
        lifecycle:
        
          # postStart:
          #   exec:
          #     command:
          #     - /bin/bash
          #     - -ec
          #     - |
          #       # Wait for the RabbitMQ to be ready.
          #       until rabbitmq-diagnostics -q check_running; do
          #         sleep 5
          #       done

          #       # By default, RabbitMQ does not have Highly Available policies enabled,
          #       # using the following command to enable it.
          #       rabbitmqctl set_policy ha-all "." '{"ha-mode":"all", "ha-sync-mode":"automatic"}' --apply-to all --priority 0
          preStop:
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  if [[ -f /opt/bitnami/scripts/rabbitmq/nodeshutdown.sh ]]; then
                      /opt/bitnami/scripts/rabbitmq/nodeshutdown.sh -t "180" -d "false"
                  else
                      rabbitmqctl stop_app
                  fi
        env:
        - name: JAVA_OPTS
          value: >-
                -Dlog4j2.formatMsgNoLookups=true
                -Dlog4j2.disable.jmx=true
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_SERVICE_NAME
          value: 'gted-archive-system-rabbitmq-discovery'
        - name: RABBITMQ_USE_LONGNAME
          value: 'true'
        - name: RABBITMQ_FORCE_BOOT
          value: "no"
        - name: RABBITMQ_NODENAME
          value: 'rabbit@$(MY_POD_NAME).gted-archive-system-rabbitmq-discovery.$(DISCOVERY_NAMESPACE).svc.cluster.local'
        - name: K8S_HOSTNAME_SUFFIX
          value: '.gted-archive-system-rabbitmq-discovery.$(DISCOVERY_NAMESPACE).svc.cluster.local'
        - name: RABBITMQ_MNESIA_DIR
          value: "/bitnami/rabbitmq/mnesia/$(RABBITMQ_NODENAME)"
        - name: RABBITMQ_LOGS
          value: "-"
        - name: RABBITMQ_ULIMIT_NOFILES
          value: "65536"
        - name: RABBITMQ_LOAD_DEFINITIONS
          value: "no"
        - name: RABBITMQ_DEFINITIONS_FILE
          value: "/app/load_definition.json"
        ports:
        - name: clustering
          containerPort: 25672
        - name: amqp
          containerPort: 5672
        - name: amqp-ssl
          containerPort: 5671
        - name: prometheus
          containerPort: 15692
        - name: http
          containerPort: 15672
        volumeMounts:
        - name: config
          mountPath: /etc/rabbitmq
        - name: data
          mountPath: /bitnami/rabbitmq/mnesia
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - ping
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - status
          initialDelaySeconds: 20
          timeoutSeconds: 30
          periodSeconds: 60

      volumes:
      - name: configmap
        configMap:
          name: rabbitmq-config
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
      - name: config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/component: server
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard-rwo
      resources:
        requests:
          storage: 8Gi

### What do you see instead?

Failed to pull image "[docker.io/bitnami/bitnami-shell:11-debian-11-r114](http://docker.io/bitnami/bitnami-shell:11-debian-11-r114)": rpc error: code = Unknown desc = failed to pull and unpack image "[docker.io/bitnami/bitnami-shell:11-debian-11-r114](http://docker.io/bitnami/bitnami-shell:11-debian-11-r114)": failed to resolve reference "[docker.io/bitnami/bitnami-shell:11-debian-11-r114](http://docker.io/bitnami/bitnami-shell:11-debian-11-r114)": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by avinal** [comment]
I am having the same error with `bitnami/postgresql` from around 5 hrs ago. The bitnami/bitnami-shell repo is gone from the docker hub and I can't find a breaking change/deprecation notice anywhere.

**Comment by utkarshatembhurkar** [comment]
using os-shell helped me.
Thank you

**Comment by davejhahn** [comment]
This is a pretty big breaking change--we are running into this after doing some other upgrades where the pods migrated and couldn't start up.  Unless you are on one of the two most recent chart versions, you will run into this.

**Comment by carrodher** [comment]
The `bitnami/bitnami-shell` image was deprecated a long time ago in favor of `bitnami/os-shell`. That change was announced with a deprecation notice in the DockerHub README. After 7 months since that moment and following the retention policy defined at [README.md#retention-policy](https://github.com/bitnami/containers/blob/main/README.md#retention-policy), the `bitnami/bitnami-shell` repo was removed in favor of [`bitnami/bitnami-shell-archived`](https://hub.docker.com/r/bitnami/bitnami-shell-archived).

This process is followed in that way to not keep unmaintained images in DockerHub without receiving updates for a long time and users not noticing it. With the relocation of the images to a different repo, users are aware that they are using an unmaintained image. The only change to continue using it is to replace `bitnami/bitnami-shell` with `bitnami/bitnami-shell-archived` in their _values.yaml_. Or the preferred options, use a newer version of the Helm chart bundling this image or, at least, replace the image by the maintained `bitnami/os-shell`

**Comment by avinal** [comment]
Hey @carrodher I am using the configuration below, it uses initContainer to generate and copy certificate, and that needs bitnami/bitnami-shell to work.

```yaml
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.7
    helm:
      releaseName: postgres
      parameters:
        - name: image.tag
          value: 13.10.0
        - name: tls.enabled
          value: "true"
        - name: tls.autoGenerated
          value: "true"
 ```
 
Are the newer images updated to use bitnami/os-shell?

**Comment by carrodher** [comment]
`bitnami-shell` and `os-shell` are equivalent images, just a rename was performed to deliver this image not only as part of the opensource catalog (Bitnami Application Catalog) but also in the enterprise catalog ([VMware Tanzu Application Catalog]([VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog))).

If `os-shell` doesn't work for your use case, feel free to open a separate issue so we can investigate what happened. In any case, using `bitnami-shell-deprecated` where previously `bitnami-shell` was used should work fine since both images are the same, even with the same tags.

**Comment by carrodher** [comment]
> Just checking, the `bitnami/bitnami-shell-deprecated` that you mention doesn't seem to work https://hub.docker.com/r/bitnami/bitnami-shell-deprecated

Sorry @jack1902, unfortunately, that was a typo on my latest comment (I just edited it). The proper repo name is `-archived` instead of `-deprecated`, see https://hub.docker.com/r/bitnami/bitnami-shell-deprecated

**Comment by carrodher** [comment]
Hello everyone,

Following your valuable feedback, we have made adjustments to our retention policy to better serve the Bitnami Helm charts community:
* For regular images, the time window in which both repositories (`bitnami/foo` and `bitnami/foo-archived`) coexist has been extended from 3 to 6 months. After that period, `bitnami/foo` will be fully removed.
* Special images, like `bitnami/bitnami-shell`, which are extensively used in Helm charts, will now have an extended coexistence period of 1 year.

*In the case of [bitnami/bitnami-shell](https://hub.docker.com/r/bitnami/bitnami-shell), it has been recovered and will be removed on July 2024, precisely 1 year after the initial deprecation date.*

We strongly encourage everyone to update their deployments to a recent Helm chart version or consider using `bitnami/os-shell` whenever possible to ensure continued access to updates.
