### ISSUE TITLE
[bitnami/cassandra] Installation failed when serviceMonitor enabled

### ISSUE THREAD

**Issue by leonchik1976** [bitnami/charts#23408]
### Name and Version

bitnami/cassandra 10.9.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm install cassandra oci://registry-1.docker.io/bitnamicharts/cassandra --set metrics.enabled=true --set metrics.serviceMonitor.enabled=true`

### Are you using any custom parameters or values?

`--set metrics.enabled=true --set metrics.serviceMonitor.enabled=true`

### What is the expected behavior?

Install Cassandra with service monitor

### What do you see instead?
```
Error: INSTALLATION FAILED: template: cassandra/templates/servicemonitor.yaml:11:24: executing "cassandra/templates/servicemonitor.yaml" at <include>: wrong number of args for include: want 2 got 0
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by leonchik1976** [comment]
Issue still exists

**Comment by emouawad** [comment]
Issue still exists

**Comment by fmulero** [comment]
Thanks for using Bitnami charts and reporting this issue.

Version 11.1.1 has been released and fixes this issue.
