### ISSUE TITLE
bitnami-shell image replaced by os-shell?

### ISSUE THREAD

**Issue by Mark90** [bitnami/charts#23411]
### Name and Version

bitnami/postgresql 12.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

We are using version 12.1.5 of the `postgres` chart. Up until yesterday this this chart installed fine. Today it doesn't as the `bitnami-shell` image seems to not be on Docker hub anymore. Has this image been removed in favor of `os-shell`?

### What do you see instead?

> Failed to pull image "docker.io/bitnami/bitnami-shell:11-debian-11-r62": failed to pull and unpack image "docker.io/bitnami/bitnami-shell:11-debian-11-r62": failed to resolve reference "docker.io/bitnami/bitnami-shell:11-debian-11-r62": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by Mark90** [comment]
After trying out 14.0.5 of the `postgres` chart I see that it is indeed pulling the `docker.io/bitnami/os-shell:11-debian-11-r96` image.

So this means that all old charts using `bitnami-shell` have indirectly been removed?

**Comment by carrodher** [comment]
Please note there is an already existing issue for this topic (https://github.com/bitnami/charts/issues/23406).
Crossposting here some notable comments:
* First notable comment:
> The `bitnami/bitnami-shell` image was deprecated some months ago in favor of `bitnami/os-shell` (see https://github.com/bitnami/containers/pull/41421). That change was announced with a deprecation notice in the DockerHub README.
> After 7 months and following the retention policy defined at [README.md#retention-policy](https://github.com/bitnami/containers/blob/main/README.md#retention-policy), the `bitnami/bitnami-shell` repo was removed in favor of [`bitnami/bitnami-shell-archived`](https://hub.docker.com/r/bitnami/bitnami-shell-archived) where all the existing images tags are present.
>
> This process is followed in that way to not keep unmaintained and insecure images not receiving updates for a long time in DockerHub. With the relocation of the images to a different repo, users are aware that they are using a deprecated image. If they want to continue using it, the only required change is the replacement of `bitnami/bitnami-shell` with `bitnami/bitnami-shell-archived` in their _values.yaml_. Although the preferred options are 1) using a newer version of the Helm chart bundling this image or, 2) at least, replacing the image with the maintained `bitnami/os-shell`.

* Second notable comment:
> Hello everyone,
>
> Following your valuable feedback, we have made adjustments to our retention policy to better serve the Bitnami Helm charts community:
> * For regular images, the time window in which both repositories (`bitnami/foo` and `bitnami/foo-archived`) coexist has been extended from 3 to 6 months. After that period, `bitnami/foo` will be fully removed.
> * Special images, like `bitnami/bitnami-shell`, which are extensively used in Helm charts, will now have an extended coexistence period of 1 year.
>
> **In the case of [bitnami/bitnami-shell](https://hub.docker.com/r/bitnami/bitnami-shell), it has been recovered and will be removed on July 2024, precisely 1 year after the initial deprecation date.**
>
> We strongly encourage everyone to update their deployments to a recent Helm chart version or consider using `bitnami/os-shell` whenever possible to ensure continued access to updates.

**Comment by Mark90** [comment]
Thanks for the quick reply and explanation! Sorry I missed that other issue, I'll close this and leave any further comments in there.
