### ISSUE TITLE
Tags in keycloak chart are outdated

### ISSUE THREAD

**Issue by Ansible-man** [bitnami/charts#23419]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Pull images and inspect
Images are:
- bitnami/keycloak:23.0.6-debian-11-r0
- bitnami/keycloak-config-cli:5.10.0-debian-11-r4
- bitnami/postgresql:16.1.0-debian-11-r25
- bitnami/os-shell:11-debian-11-r95
- bitnami/postgres-exporter:0.15.0-debian-11-r7
- bitnami/nginx:1.16.1-debian-10-r63

Tags are outdated

### What do you see instead?

Old images

**Comment by carrodher** [comment]
Please note containers and Helm charts have a different release cadence. Helm charts are updated when a new version of the upstream application is released or when there is a new revision of the container addressing a CVE. There could be other causes producing a new container revision without triggering the Helm chart release.
