### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] nil pointer evaluating interface {}.metrics when network policies are enabled

### ISSUE THREAD

**Issue by aschleifer** [bitnami/charts#23427]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.15.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

try to deploy the mentioned chart in the mentioned version with `msgTopologyOperator.metrics.enabled = true` and `msgTopologyOperator.metrics.serviceMonitor.enabled` but no other metrics setting

### Are you using any custom parameters or values?

```
msgTopologyOperator.metrics.enabled = true
msgTopologyOperator.metrics.serviceMonitor.enabled = true
```

### What is the expected behavior?

It should deploy without issues and enable metrics

### What do you see instead?

```
std out err: %!(EXTRA *errors.errorString=Error: template: rabbitmq-cluster-operator/templates/messaging-topology-operator/networkpolicy.yaml:62:26: executing "rabbitmq-cluster-operator/templates/messaging-topology-operator/networkpolicy.yaml" at <.Values.msgTopologyOperator.metrics.containerPorts.metrics>: nil pointer evaluating interface {}.metrics
```

### Additional information

The used configuration as worked in version `3.13.0`.

It seems the issue was introduced with https://github.com/bitnami/charts/pull/22739 in version `3.15.0`, as this PR adds the network policies file by using the value `.Values.msgTopologyOperator.metrics.containerPorts.metrics` which is neither added with default values to https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml to avoid breaking changes in a new feature, nor in the https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/README.md of the chart.

This issue breaks semantic versioning of the chart as now you either need to enable the feature or set the needed value which both should not be needed for a minor/feature version change of the chart.

**Comment by aschleifer** [comment]
Reading the parameters in the README again `msgTopologyOperator.containerPorts.metrics` exists and is set (https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml#L877-L880) but not used in the networkpolicy template.

**Comment by aschleifer** [comment]
A similar issue exiswts in the cluster-operator networkpolicy template with a usage of the non existing `.Values.clusterOperator.metrics.containerPorts.http` value.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
