### ISSUE TITLE
[bitnami/mariadb] master not picking up the loadbalancer annotation 

### ISSUE THREAD

**Issue by govindkailas** [bitnami/charts#2342]
[maria-dev.txt](https://github.com/bitnami/charts/files/4487835/maria-dev.txt)
**Which chart**:
mariadb v7.3.17

**Describe the bug**
I tried giving the service type as loadbalancer in the values.yaml, looks like only slave is picking up the configuration. 

**To Reproduce**
1. Select the maria db chart v7.3.17 from KubeApp
2. Provide the attached values.yaml
3. We will see master is pending for external loadbalancer ip
4. Slave already got the external IP as shows as type loadbalacner.

**Expected behavior**
I am not sure this behaviour is expected, but what I would want is both master and slave should fetch the loadbalancer annotation mentioned in the values.yaml and create external lips. Right now, only slave is getting the external IP and master keeps waiting for external ip.

**Version of Helm and Kubernetes**: 

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4+vmware.1", GitCommit:"0f866081ec4345725d7a74fdd5d353b5637d387a", GitTreeState:"clean", BuildDate:"2019-12-11T22:11:30Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
[maria-dev.txt](https://github.com/bitnami/charts/files/4487821/maria-dev.txt)

```

**Additional context**

**Comment by marcosbc** [comment]
@govindkailas Unfortunately we could not reproduce your issue.

In our case we used a GKE cluster with the changes below to the values.yaml file:

```
diff --git a/bitnami/mariadb/values.yaml b/bitnami/mariadb/values.yaml
index 4c54ac3b..8f5690c6 100644
--- a/bitnami/mariadb/values.yaml
+++ b/bitnami/mariadb/values.yaml
@@ -65,7 +65,7 @@ volumePermissions:

 service:
   ## Kubernetes service type, ClusterIP and NodePort are supported at present
-  type: ClusterIP
+  type: LoadBalancer
   # clusterIp:
   #   master: xx.xx.xx.xx
   #   slave: xx.xx.xx.xx
@@ -322,7 +322,8 @@ master:
   service:
     ## Add custom annotations to the service
     ##
-    annotations: {}
+    annotations:
+      cloud.google.com/load-balancer-type: internal
       # external-dns.alpha.kubernetes.io/hostname: db.example.com

 slave:
@@ -453,7 +454,8 @@ slave:
   service:
     ## Add custom annotations to the service
     ##
-    annotations: {}
+    annotations:
+      cloud.google.com/load-balancer-type: internal
       # external-dns.alpha.kubernetes.io/hostname: rodb.example.com

 metrics:
```
We see it is working properly via `kubectl get svc` as both master and slave are showing a proper public IP in the "EXTERNAL-IP" section.

One thing we noticed in your configuration is that you set an annotation for the master service, but not for the slave. Could the issue be there by any chance?

**Comment by govindkailas** [comment]
I shall retry and let you know @marcosbc
