### ISSUE TITLE
[bitnami/magento] Module Code changes dont take effect until VM reboot.

### ISSUE THREAD

**Issue by mSIESTE** [bitnami/charts#23422]
### Name and Version

bitnami-magento-2-2.4.6-r21-debian-11-amd64

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Start Container
2. Install or create a Module with Events/Observer
3. Make changes to that Module (Observer Class) [I added a new log output]
4. Test the Module

### What is the expected behavior?

I would except that the new Log Output was written.

### What do you see instead?

I dont see the new Output in my Logfile

### Additional information

My changes that dowsnt work until VM reboot:

Old Output(Works !):
 $this->logger->info("test1");
I added this Line:
 $this->logger->info("test2");

Given Output:
[2024-02-14T08:32:32.193660+00:00] main.INFO: test1 [] []

Expected:
[2024-02-14T08:32:32.193660+00:00] main.INFO: test1 [] []
[2024-02-14T08:32:32.193660+00:00] main.INFO: test2 [] []

I´m in Dev Mode.
I tried many Commands like:
sudo php bin/magento setup:upgrade;sudo php bin/magento setup:di:compile;sudo php bin/magento setup:static-content:deploy -f;sudo chmod -R 0777 var/ pub/ generated/;sudo php bin/magento cache:flush;

sudo rm -rf pub/static/frontend/ var/cache/;sudo php bin/magento s:up;sudo php bin/magento s:di:c;sudo php bin/magento setup:static-content:deploy -f;sudo php bin/magento indexer:reindex;sudo php bin/magento c:f;sudo chmod -R 777 generated/ var/cache/ pub/static var/

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
