### ISSUE TITLE
[bitnami/postgresql] insecure permissions on password file

### ISSUE THREAD

**Issue by marccampbell** [bitnami/charts#2345]
**Which chart**:
postgresql 8.7.4

**Describe the bug**
When enabling the password file option in values.yaml, insecure permissions are set on the mounted file, which results in commands such as pg_dump failing to work.

**To Reproduce**
Deploy the chart with
--set usePasswordFile=true

Postgres starts. Now exec into the postgresql-postgresql-0 container that it's created, and attempt to run pg_dump:
```
PGPASSFILE=/opt/bitnami/postgresql/secrets/postgresql-password pg_dump -U myusername -d mydb -h 127.0.0.1
WARNING: password file "/opt/bitnami/postgresql/secrets/postgresql-password" has group or world access; permissions should be u=rw (0600) or less
 ```

This warning causes pg_dump to reject the password file

**Expected behavior**
This should set the permissions to 0600 or less on the mounted file.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}```
```
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi @marccampbell ,
  Thanks for reporting this. 
  I am testing it and looking for a fix.
  I will come back as soon as I have news.

**Comment by rafariossaa** [comment]
Hi @marccampbell ,
  The usePasswordFile setting is not generating a file `.pgpass` file like [these](https://www.postgresql.org/docs/10/libpq-pgpass.html) , it is a file with just the password.
  However, you can use `PGPASSWORD` instead of `PGPASSFILE` like this:

`PGPASSWORD=$(cat /opt/bitnami/postgresql/tmp/postgresql-password) pg_dump -U postgres `

  Could you give it a try ?

**Comment by marccampbell** [comment]
@rafariossaa i ended up coming up with the same solution as a workaround here. Should the chart create the file using secure permissions though, so we don't need to work around?

**Comment by marccampbell** [comment]
Also, I forked and tried to fix this, but there's a bug in K8s that makes `defaultMode` on a volume mounted from a secret not be applied when there's also a `fsGroup` set. So a true fix here would probably require an init container to set this permission, which feels like a bigger solution

**Comment by rafariossaa** [comment]
Hi @marccampbell ,
  That is not a work around, it that PGPASSFILE is for other use case.
  The PGPASSFILE needs a specific format, and that is not generated by the initialization.
   You can specify the permissions when mounting a volumen as detailed [here](https://kubernetes.io/docs/concepts/configuration/secret/).
   Anyway, feel free to send any PR you consider, we will be glad to review and merge them.
