### ISSUE TITLE
Onboard Spring Cloud Data Flow helm chart

### ISSUE THREAD

**Issue by sabbyanandan** [bitnami/charts#2346]
As part of the continuing efforts to present Spring products for Kubernetes community and to make them more accessible, we would like to partake in Bitnami's container image generation process, and likewise contribute the Helm chart to go along with it. 

We have had the [Spring Cloud Data Flow](https://hub.helm.sh/charts/stable/spring-cloud-data-flow)'s Helm chart in the public repository for a while now — we would like to onboard `bitnami/spring-cloud-data-flow` into Bitnami's helm repository. 

**Core components:**
- [Spring Cloud Data Flow](https://github.com/spring-cloud/spring-cloud-dataflow)
- [Spring Cloud Skipper](https://github.com/spring-cloud/spring-cloud-skipper)

Today, we use the Fabric8 plugin to generate the Docker images (see: [example](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server/pom.xml#L117)). Both are Java projects and we use Maven to build them. 

**Dependencies:**
See: [spring-cloud-data-flow/requirements.yaml](https://github.com/helm/charts/blob/master/stable/spring-cloud-data-flow/requirements.yaml)

**Comment by beltran-rubo** [comment]
Hi @sabbyanandan,

Thanks for opening this issue. We will work on checking the integration of the Spring Cloud images and the Chart.

**Comment by sabbyanandan** [comment]
Hi, @beltran-rubo! Any thoughts on when we will have access to the Bitnami images?

**Comment by beltran-rubo** [comment]
Hi @sabbyanandan 

We have been testing the existing solution and checking there is not any red flags to add this solution as part of the catalog. We plan to work on the containers & Charts in a next iteration, probably mid-May.

**Comment by sabbyanandan** [comment]
Thank you for the update!

**Comment by beltran-rubo** [comment]
Just to let you know we continue working on that, we will let you know when the container images are available first and then the Chart so you can test them before making them publicly available.

**Comment by sabbyanandan** [comment]
Hi, @beltran-rubo. I wanted to follow-up if you have any updates for us.

**Comment by beltran-rubo** [comment]
Yes, we are pretty close to release the container images and you can see the PR for the Helm Chart at https://github.com/bitnami/charts/pull/2747. I will contact you once this first version is fully functional with the Bitnami container images.

**Comment by beltran-rubo** [comment]
Hi @sabbyanandan 

The container images are now available in Docker Hub and in GitHub at https://github.com/bitnami/bitnami-docker-spring-cloud-dataflow and https://github.com/bitnami/bitnami-docker-spring-cloud-skipper. The PR #2747 already uses those images. We continue working on building the Prometheus Rsocket Proxy image and adding some other functionalities into the Helm Chart but any feedback will be welcome.

**Comment by sabbyanandan** [comment]
Nicely done! @chrisjs: Feel free to take it for a spin and share any feedback that you may have.

**Comment by chrisjs** [comment]
lots of good stuff in that PR!

**Comment by sabbyanandan** [comment]
@beltran-rubo @juan131: Impressive work! Thank you for pushing it to promote a cleaner and a pluggable design. Looking forward to giving it a go when the PR merged.

**Comment by juan131** [comment]
@sabbyanandan @chrisjs I just wanted to let you know that Spring Cloud Dataflow chart is now published! Please take a look when you have a chance.

**Comment by donbeave** [comment]
Hello!

Is it possible to use external RabbitMQ or Kafka? I can see configuration for external database or skipper, but can not find a way to configure external messaging system here: https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/values.yaml

**Comment by juan131** [comment]
Sure, it would be a great idea to provide support for using an external messaging service. I'll take a look to your PR as soon as possible, thanks so much!

**Comment by donbeave** [comment]
@juan131 ok, good, I'll add support external messing service today a little bit later.
