### ISSUE TITLE
Web server keeps having import errors

### ISSUE THREAD

**Issue by lusiahli** [bitnami/charts#2350]
**Which chart**:
[airflow] version 4.4.3

**Describe the bug**
Web UI displays broken dag errors while airflow list_dags runs without any problem.
No dagbag.py errors found in the airflow-webserver.log either.

**To Reproduce**
deploy helm chart

**Expected behavior**
Web UI displays the dags properly

**Comment by rafariossaa** [comment]
Hi @lusiahli ,
  Could you provide instructions on how to reproduce this issue ?.

**Comment by lusiahli** [comment]
@rafariossaa Every time we deploy it, the web UI keep displays Broken Dag error we had before. We installed related oracle package and some folders in our own image based on bitnami's airflow image, the errors displayed should be gone now. There is no error in airflow-webserver.log, airflow list_dags runs fine. 

I guess my question is, where do the errors in the table import_error come from? The UI obviously is pulling the error from the table. Not sure which function of bitnami airflow is still feeding the errors into it...

**Comment by rafariossaa** [comment]
Hi @lusiahli ,
  Could you try the latest version of the chart ?

**Comment by lusiahli** [comment]
@rafariossaa Thank you for the suggestion. We have switched to the latest version of the chart and have figured out that the errors in the table import_error were coming from the scheduler. Now everything is good.  One more thing while you're here, is it possible for a dag file in a sub folder to work? eg. the dag file is cloned under /dags/git/myfolder instead of /dags/git .  Thanks!

**Comment by lusiahli** [comment]
@rafariossaa Never mind. Did a test. It seems that all dag files in the sub folder of /dags will be imported by airflow.

**Comment by rafariossaa** [comment]
@lusiahli , Thanks for coming back and sharing your findings.
I am closing this issue now.
Please, If you find an issue , don't hesitate to open it.
