### ISSUE TITLE
Fallback to Chart AppVersion for termination in "common.images.image"

### ISSUE THREAD

**Issue by Ergaac** [bitnami/charts#23536]
### Name and Version

bitnami/common 2.15.3

### What is the problem this feature will solve?

Some best practices say for the image tag to match the Chart AppVersion. This is already the fallback for `"common.images.version"`, but is not implemented in `"common.images.image"`
https://jfrog.com/blog/helm-charts-best-practices/
```
image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
```

### What is the feature you are proposing to solve the problem?

Implement a fallback of $termination to use Chart AppVersion if `imageRoot.tag` is not supplied.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Ergaac** [comment]
Amazing!
