### ISSUE TITLE
[bitnami/thanos]: change ObjectStore configMap into secret

### ISSUE THREAD

**Issue by nbenaglia** [bitnami/charts#2353]
**Which chart**: bitnami/thanos

**Is your feature request related to a problem?**
ObjectStore is defined in a file [objstore-configmap.yaml](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/objstore-configmap.yaml), representing a Kubernetes ConfigMap resource.
The same ObjectStore should be passed to thanos-sidecar while configuring prometheus-operator as specified [here](https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator/) where the tag `prometheus.thanos.objectStorageConfig.secretName` is a Kubernetes Secret resource (not a ConfigMap).
This is a conflicting definition (configMap vs secret) that makes hard to reuse the same information in more places.

**Describe the solution you'd like**
Considering that ObjectStore may contain access and secret key (to access a bucket), it should be a secret.
In Thanos chart it should be considered the idea of transforming all references to configMap into references to a secret and make ObjectStore a secret.

**Comment by juan131** [comment]
Hi @nbenaglia 

Thanks so much for reporting this issue! I agree with you, we should be using a Secret to pass this Objstore configuration. I'll take a look to the PR created by @Whyeasy
