### ISSUE TITLE
[bitnami/postgresql-ha] Container has the same readiness and liveness probe

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#23537]
### Name and Version

bitnami/postgresql-ha:12.3.4

### What is the problem this feature will solve?

```
[CRITICAL] Pod Probes
        · Container has the same readiness and liveness probe
            Using the same probe for liveness and readiness is very likely
            dangerous. Generally it's better to avoid the livenessProbe than
            re-using the readinessProbe.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
```

### What is the feature you are proposing to solve the problem?

Proper container probes for postgres container as default values in the helm chart.

### What alternatives have you considered?

Values that can address the problem I'm trying to solve

**Comment by javsalgar** [comment]
Hi! Thank you so much for reporting. I will forward this to the team for evaluation. If you want to speed up the process, feel free to submit a PR and we will review it
