### ISSUE TITLE
[bitnami/minio] Service account automountServiceAccountToken should be set to false

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#23542]
### Name and Version

bitnami/minio:12.10.10

### What is the problem this feature will solve?

Disabling automatic token mounting with automountServiceAccountToken set to false enhances security and control in Kubernetes by reducing attack surface, providing explicit control over token usage, avoiding unnecessary access, and meeting compliance and security requirements.

### What is the feature you are proposing to solve the problem?

Set the automountServiceAccountToken flag to false in the helm chart

### What alternatives have you considered?

Any explanation of why is not possible.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
