### ISSUE TITLE
[bitnami/postgresql] Read-replica networkpolicy is always created

### ISSUE THREAD

**Issue by ghost** [bitnami/charts#23545]
### Name and Version

bitnami/postgresql 14.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm template postgresql bitnami/postgresql` without values

### What is the expected behavior?

It should not create the networkpolicy for read replicas if it is deployed in standalone architecture.

### What do you see instead?

A wrong networkpolicy is created.

### Additional information

The networkpolicy is missing a check for the architecture, e.g. `eq .Values.architecture "replication"`
https://github.com/bitnami/charts/blob/87a61011766e471156e8d6363dad563791ce0e1b/bitnami/postgresql/templates/read/networkpolicy.yaml#L6

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
