### ISSUE TITLE
Issue while trying to deploy helm w/terraform

### ISSUE THREAD

**Issue by truekoi** [bitnami/charts#23557]
### Name and Version

bitnami/rabbitmq-cluster-operator:3.17.0

### What architecture are you using?

None

### What steps will reproduce the bug?

deploy the following code via terraform

`resource "helm_release" "rabbitmq-cluster-operator" {
  name       = "rabbitmq-cluster-operator"
  namespace  = one(kubernetes_namespace.ns.metadata).name
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "rabbitmq-cluster-operator"
  version    = "3.17.0"
}`

### What do you see instead?

`
 When expanding the plan for
│ module.rabbitmq.helm_release.rabbitmq-cluster-operator to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/helm" produced an invalid new value for
│ .manifest: 
then ~50k symbols long string 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵`

### Additional information

start trying few days before and was waiting maybe new version solve my issue - unfortunately it isn't
manually deployed well. 
I mean this by manually : 
`helm install rabbitmq-cluster-operator bitnami/rabbitmq-cluster-operator -n rabbitmq-system`

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by truekoi** [comment]
>The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Maybe , thats why I came here to find an answear - I can even think that there might be not so many users w/terraform etc. 

At the same time it'll be good to figure  out what happend bc terraform it's a widle use instrument and I really think it worth to spend time on resolution (or prepare a proper solution how to use it , e.g. env specifications etc.)

Thanks in advance!

**Comment by truekoi** [comment]
for anyone who run into the same issue - in my case it solved w/configuring helm provider 

e.g. w/o commented out lines work like a charm

provider "helm" {
  #experiments {
  #  manifest = true
  #}
