### ISSUE TITLE
[bitnami/etcd] Failed to liveness check on gke: eaccess caused: unknown

### ISSUE THREAD

**Issue by HoangViet144** [bitnami/charts#23571]
### Name and Version

bitnami/etcd 9.11.52

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Create a new etcd cluster using the default chart

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Liveness and readiness check will be okay

### What do you see instead?
```
Readiness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "34483793ea6a2424fccd7f53fc350ff5571a634749a2d41f01c0231120d26243": OCI runtime exec failed: exec failed: container_linux.go:390: starting container process caused: setns_init_linux.go:98: eaccess caused:: unknown
```
### Additional information

Node image: Ubuntu 22.04.3 LTS
Container runtime: containerd://1.6.18
Kubelet version: v1.26.13-gke.1189000

**Comment by HoangViet144** [comment]
It seems that etcd is using distroless image now, which makes liveness and healthness check

**Comment by carrodher** [comment]
We're not able to reproduce the issue installing the chart with default parameters. Could you please provide the exact command and values you're using to deploy it?

**Comment by HoangViet144** [comment]
I use `helm install etcd-test etcd bitnami/etcd --version=9.11.52`. After investigation, we found that the issue is because GKE node (version 1.26.13-gke.118900) cannot open shell/ execute script. GKE node version 1.26.10-gke.1101000 works well. It is likely a GKE issue. Thus I will close this problem
