### ISSUE TITLE
[bitnami/grafana] Version 9.8.4 - 9.8.6 not available through OCI registry

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#23576]
### Name and Version

bitnami/grafana 9.8.4-9.8.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Try downloading the Grafana Chart using Bitnami's OCI registry (oci://registry-1.docker.io/bitnamicharts)
2. Fails with the following error `Error: could not download oci://registry-1.docker.io/bitnamicharts/grafana: registry-1.docker.io/bitnamicharts/grafana:9.8.4: not found`

### Are you using any custom parameters or values?

Not relevant for this issue

### What do you see instead?

The latest versions of the chart can't be used via the OCI registry. But they are available through HTTP. But all version are listed on https://artifacthub.io/packages/helm/bitnami/grafana

**Comment by lusu007** [comment]
Now Renovate suggested updating to 9.8.18. But that version isn't available in this 3 and not listed on Artifathub as well. 

Something seems to be broken in the release process.

**Comment by meyfa** [comment]
We just received notice that 18.14.1 of the redis chart is available via the registry, but in the Git history, the last update bumps the version to 18.14.0 only? Where is the additional patch bump coming from?

**Comment by lusu007** [comment]
As far as I can tell this issue is fixed and #23582, #23576, 23599 and #23619 as well.
