### ISSUE TITLE
Should not bitnami/ejbca be deployed as a StatefulSet instead of Deployment kind?

### ISSUE THREAD

**Issue by zentavr** [bitnami/charts#23579]
### Name and Version

bitnami/ejbca 11.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

EJBCA internally has kinda Services (like a periodic tasks, crons) which could be used for the different purposes. In our organization we use these to update CRLs for our CAs (a lot of VPN CAs). Before the migration into K8S we used EJBCA as a docker container with the pre-defined host name. When you define a Service task - you can specify which hostname should be considered to run the task. Now this is not possible to fulfill, because the hostname of the pod is unique all the time.

<img width="1706" alt="000" src="https://github.com/bitnami/charts/assets/595334/55b5754d-d2a8-4d55-ae5e-1ab5cf3e8628">

### What is the expected behavior?

I would like to be able to use the services

### What do you see instead?

The services are not being executed periodically

**Comment by zentavr** [comment]
As a workaround could be done in this way:
<img width="927" alt="001" src="https://github.com/bitnami/charts/assets/595334/caf1e16b-a9d1-4c17-82a2-b1f39751f6b3">

and the audit log:
<img width="1254" alt="002" src="https://github.com/bitnami/charts/assets/595334/a701b43b-4dfa-4137-96eb-87196753f4f3">

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
