### ISSUE TITLE
[bitnami/nginx] At least 1 pod annotation needed in values to so checksum/server-block-configuration is generated

### ISSUE THREAD

**Issue by addshore** [bitnami/charts#2358]
**Which chart**:
nginx

**Describe the bug**
When the value is as below:

```
podAnnotations: {}
```

No checksum/server-block-configuration is added.

I went to add my own checksum

```
podAnnotations:
  serverBlockHash: {{ readFile "nginx.conf" | sha256sum }}
```

And then saw in my diff that one should already have been provided by the chart:

```
+       annotations:
+         serverBlockHash: 20a995cdc1eaf985bb68c97edc530027812914367b7ecc9317e0a215f86c9d43
+
+         checksum/server-block-configuration: 7e5f4c01e5917f1a4c4f14faba330b4d675b20fc04c5be49a6ffbf776000f8ad
```

**Expected behavior**
checksum/server-block-configuration is added as an annotation event when no other custom annotations are added

**Comment by juan131** [comment]
Thanks for reporting the issue!!

What version of the NGINX chart are you using @addshore ? This issue was addressed 4 days ago in the PR below:

- https://github.com/bitnami/charts/pull/2336

**Comment by addshore** [comment]
o/ I'm on 5.2.0 after https://github.com/bitnami/charts/issues/2301#issuecomment-613850915 was fixed for me a few days ago.
I guess there is already a next version I should be on! :)
Where is the canonical list of chart releases for bitnami?

**Comment by juan131** [comment]
Hi @addshore 

It's quite simple to obtain, see:

```consolse
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm search repo -l bitnami/nginx
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/nginx                   	5.2.2        	1.17.10    	Chart for the nginx server
bitnami/nginx                   	5.2.1        	1.17.10    	Chart for the nginx server
bitnami/nginx                   	5.2.0        	1.17.10    	Chart for the nginx server
bitnami/nginx                   	5.1.15       	1.17.10    	Chart for the nginx server
bitnami/nginx                   	5.1.14       	1.17.9     	Chart for the nginx server
...
```

**Comment by addshore** [comment]
Thanks!
Closing as this is obviously already resolved.

Is there any sort of written change log or web page? (rather than just the helm output).
Totally okay if there isn't, I just want to make sure I'm not missing something!

**Comment by juan131** [comment]
I'm afraid there's no changelog. We add some notes when we bump the major version including breaking changes though: 

- https://github.com/bitnami/charts/tree/master/bitnami/nginx#upgrading
