### ISSUE TITLE
[bitnami/redis] bitnamicharts/redis has tag to `18.14.2` but charts highest version is `18.14.0`

### ISSUE THREAD

**Issue by DerRockWolf** [bitnami/charts#23582]
### Name and Version

bitnami/redis 18.14.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I'm using renovatebot to bump the chart versions, that's how I've noticed it.

Renovate currently tries to bump the chart version to `18.14.2` which is an existing tag in the [docker registry](https://hub.docker.com/r/bitnamicharts/redis/tags).
The latest version of the `Chart.yaml` however points to [`18.14.0`](https://github.com/bitnami/charts/blob/cf413a8a118a0dd1288b72b6ae9936f655221e9b/bitnami/redis/Chart.yaml#L37).

### What is the expected behavior?

I would expect the tags in the docker registry to correlate with the versions specified in the `Chart.yaml` files.

### What do you see instead?

See above.

**Comment by rouke-broersma** [comment]
We see the same for external-dns. The only chart version for 6.33 on docker hub is 6.33.3, however the chart version in the repo is 6.33.0: https://hub.docker.com/r/bitnamicharts/external-dns/tags?page=1&name=6.33 

We also cache the images so we noticed that external-dns 6.33.3 uses image `registry-1.docker.io/bitnami/external-dns:0.14.0-debian-11-r26` while the chart specifies `docker.io/bitnami/external-dns:0.14.0-debian-11-r9`.

**Comment by carrodher** [comment]
Thanks for reporting. Yes, it is an issue in our release process. Helm charts are being built, tested and released as usual but with the wrong version number.
Charts are functional, tested and secure as usual, but there has been some confusion in some versions (the number itself) no the Helm chart as a package.

**Comment by viceice** [comment]
is the registry change expected? `docker.io` => `registry-1.docker.io`

**Comment by DerRockWolf** [comment]
Has this been solved @carrodher?

**Comment by carrodher** [comment]
Yes, the latest version is the same in
- GitHub: https://github.com/bitnami/charts/blob/53aca51120f86086e6780dc0453b93fbf49766b4/bitnami/redis/Chart.yaml#L39
- DockerHub: https://hub.docker.com/layers/bitnamicharts/redis/18.19.2/images/sha256-d681d7e587c6b623d596e0b02727465ad0e7b974a405e766cca03443038ebdc2?context=explore
