### ISSUE TITLE
[bitnami/kafka] Installation fails when serviceBingings.enabled set to true

### ISSUE THREAD

**Issue by spzm** [bitnami/charts#23603]
### Name and Version

bitnami/kafka 24.0.0-26.10.0

### What architecture are you using?

Amd64

### What steps will reproduce the bug?

1. Add multiple users in the config and enable serviceBindings
```yaml
sasl:
  client:
    users:
      - "admin"
      - "user"
serviceBindings: 
  enabled: true
```

2. Run template/install/upgrade

### Are you using any custom parameters or values?

Yes, but reproduced when only these values are set and all others are default.

### What is the expected behavior?

Installation begins.

### What do you see instead?

Error: template: kafka/templates/controller-eligible/statefulset.yaml:42:38: executing "kafka/templates/controller-eligible/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: kafka/templates/secrets.yaml:69:88: executing "kafka/templates/secrets.yaml" at <.Values.service.ports.client>: can't evaluate field Values in type int

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
