### ISSUE TITLE
[bitnami/rabbitmq] Error rendering template - nil pointer

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#23607]
### Name and Version

bitnami/rabbitmq 12.12.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Attempt to install latest rabbitmq chart with no vales set for resources.
2. Observe error.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Chart installs

### What do you see instead?

```
Error: template: foo/charts/rabbitmq/templates/validation.yaml:6:4: executing "foo/charts/rabbitmq/templates/validation.yaml" at <include "rabbitmq.validateValues" .>: error calling include: template: foo/charts/rabbitmq/templates/_helpers.tpl:188:35: executing "rabbitmq.validateValues" at <include "rabbitmq.validateValues.memoryHighWatermark" .>: error calling include: template: foo/charts/rabbitmq/templates/_helpers.tpl:227:64: executing "rabbitmq.validateValues.memoryHighWatermark" at <.Values.resources.limits.memory>: nil pointer evaluating interface {}.memory Use --debug flag to render out invalid YAML
```

### Additional information

In this commit:
https://github.com/bitnami/charts/commit/b9339c73fbff437da149410a2a50209b69b507ec#diff-4196e2902de7c60cf9b84763119ec51216bf72ff7ec6917e94e3feaadb1b7dd3L803

The empty dict was removed for `resources.limits` and `resources.requests`.

`_helpers.tpl` [attempts to dereference](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/_helpers.tpl#L227) `resources.limits.memory` without checking if `resources.limits` is non-nil.

Note that while `memoryHighWatermark.enabled` = `false`, older versions of helm (<3.10) will evaluate all conditions in `and`/`or`.  This behavior [changed in go 1.18](https://tip.golang.org/doc/go1.18#htmltemplatepkghtmltemplate).

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
