### ISSUE TITLE
[bitnami/wildfly]

### ISSUE THREAD

**Issue by baldodavi** [bitnami/charts#2365]
**Which chart**:
name: wildfly
version: 3.5.12

**Describe the bug**
Calling 
`export SERVICE_IP=$(kubectl get svc --namespace default singed-gorilla-wildfly --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")`

 as reported after wildfly install this error is obtained: 
`error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil
`

**To Reproduce**
helm install ./wildfly
`export SERVICE_IP=$(kubectl get svc --namespace default singed-gorilla-wildfly --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")`

**Expected behavior**
Not to have error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
HElm: Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by Mauraza** [comment]
Hi @baldodavi, 

Do you have an external Ip associated with the service of `wildfly`?  you can see that running the next command `kubectl get svc`. if the service has an IP or the status are `pending`

**Comment by baldodavi** [comment]
Status is pending.

**Comment by Mauraza** [comment]
@baldodavi, you need to have a public IP to do that. f you don't have a public IP you can't get a LoadBalancer.

**Comment by baldodavi** [comment]
Thanks for help
