### ISSUE TITLE
[bitnami/redis-cluster] Error when installing with production values

### ISSUE THREAD

**Issue by rechandler12** [bitnami/charts#2367]
**Which chart**:
redis-cluster:2.0.3

**Describe the bug**
When install chart I've got error:
Error: YAML parse error on redis-cluster/templates/metrics-svc.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

**To Reproduce**
1. Install chart with helm install -f https://raw.githubusercontent.com/bitnami/charts/master/bitnami/redis-cluster/values-production.yaml redis bitnami/redis-cluster
2. See error

**Expected behavior**
No error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @rechandler12, 

I just create a PR fixed the error, please check if it's working when the merge will be complete.

**Comment by glimberg** [comment]
Was having the same issue with chart version 2.0.5.

Tried out the pull request and it fixed the issue.
