### ISSUE TITLE
Ability to setup custom resources for cronjobs

### ISSUE THREAD

**Issue by headyj** [bitnami/charts#23690]
### Name and Version

bitnami/matomo 

### What is the problem this feature will solve?

Currently the resources assigned to cronjobs are the same as the one of the main pod, without the possibility to do override it: https://github.com/bitnami/charts/blob/main/bitnami/matomo/templates/cronjob.yaml#L113

There is a problem running these cronjobs when you are using RWO volumes, like mentioned on [this issue](https://github.com/bitnami/charts/issues/20568). A workaround is to setup a `podAffinity` but it is not bullet proof as it will not work if the node on which the main matomo pod is running is already full. Removing the resources assigned to the cronjobs would then ensure they got executed. Not an ideal solution to have cronjobs without assigned resources, but at least it would work

### What is the feature you are proposing to solve the problem?

Default behavior would still be to inherit default resources assigned to matomo, but with the possibility to override it

**Comment by reiSh6phoo9o** [comment]
Having the same issue, would need that . If helpful,  can provide a PR

**Comment by reiSh6phoo9o** [comment]
Hi, anything else I can do here?
