### ISSUE TITLE
[bitnami/mongodb-sharded] {Feature request} allow setting sessionAffinity on mongos-service

### ISSUE THREAD

**Issue by oldluke92** [bitnami/charts#2369]
**Which chart**:
bitnami/mongodb-sharded, version 1.1.4

**Is your feature request related to a problem? Please describe.**
Problem:
Running mongodb queries and iterating over cursors frequently gives `MongoError; Cursor not found, cursor id: xxxxxxxxxxxx` Errors using the mongodb native driver in nodejs with the sharded DB. This mostly happens if the cusor contains more than 10k elements, each of the documents ~2kb in size. The affected DB is not fragmented over multiple shards.
We had the same issue before with mongo 3.6, and setting the sessionAffinity of the mongos service to "ClientIP" solved it permanently. 
I also tried that on the service of the bitnami-mongodb-sharded deployment - and afterwards it worked like a charm.

I cannot find anything specifically about it, but I assume that the mongos routers actually hold the temporary query cursors. If so, this could lead to a scenario like this:
* query gets executed, mongos returns the cursor
* the service fetches the first batch of documents, does some processing and sends it to my applications client
* The application tries to fetch another batch of documents out of the same cursor, but it's request goes to another mongos instance which does not hold that cursor

Tried to find someting in the official docs [here](https://docs.mongodb.com/manual/core/sharded-cluster-query-router/#routing-and-results-process) but these descriptions are pretty unspecific.

**Describe the solution you'd like**
Adding a field to the values.yaml (like mongos.service.sessionAffinity) and a templated line for sessionAffinity to the mongos service so that one can be configured (but defaults to "None" to maintain backwards compatibility) would solve this.

```yaml
spec:
  sessionAffinity: {{default "None" .Values.mongos.service.sessionAffinity}}
```

**Describe alternatives you've considered**
I guess there is always a possibility that i'm just doing something wrong, but there is nothing I found researching the given error.

Can provide a PR if you'd like.

**Comment by juan131** [comment]
Hi @oldluke92 

We have seen similar issues on other applications (e.g. web application users whose cache was invalidated when a different pod attends their requests).

Supporting a way to manage the **sessionAffinity** looks like a good alternative for me. Here I add more context about this feature for those interested on it:

```console
$ kubectl explain service.spec.sessionAffinity
KIND:     Service
VERSION:  v1

FIELD:    sessionAffinity <string>

DESCRIPTION:
     Supports "ClientIP" and "None". Used to maintain session affinity. Enable
     client IP based session affinity. Must be ClientIP or None. Defaults to
     None. More info:
     https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies 
```

> Can provide a PR if you'd like.

Yes please! Submit a PR and I'll be glad to review it.

**Comment by juan131** [comment]
This issue was solved at https://github.com/bitnami/charts/pull/2375
