### ISSUE TITLE
better handling of rabbitmq secret

### ISSUE THREAD

**Issue by tibers** [bitnami/charts#2371]
**Which chart**:
rabbitmq latest

**Is your feature request related to a problem? Please describe.**
Rather than use `existingBlahSecret`, simply don't derp around with the secret at all if we are in an upgrade situation. 

**Describe the solution you'd like**
Don't mess with the secret during an upgrade, even if the secret isn't specified with `--set` or in `values`.

**Describe alternatives you've considered**
hardcode the secret. Yuk!

**Additional context**

**Comment by miguelaeh** [comment]
Hi @tibers ,
thank you very much for the PR, let's discuss about this there, to avoid duplicated threads

**Comment by miguelaeh** [comment]
I am going to close this thread as we are already taking care of this in the PR.
