### ISSUE TITLE
[bitnami/kafka] externalAccess with port other than 19092 fails

### ISSUE THREAD

**Issue by kyle-winkelman** [bitnami/charts#2373]
**Which chart**:
Kafka: 10.2.3

**Describe the bug**
When the externalAccess.service.port is set to something other than 19092 the kafka-X-external service points to port 19092 even though the script in scripts-configmap.yaml would reconfigure the port that is actually exposed to be the configured value.

Some changes could be made to take this number into consideration but there is a secondary problem, if a port like 443 is used the container fails to start because port 443 is not allowed unless the container is run as root.

**To Reproduce**
helm install kafka bitnami/kafka \
  --set externalAccess.enabled=true \
  --set externalAccess.service.loadBalancerIPs[0]=10.10.10.10 \
  --set externalAccess.service.type=LoadBalancer \
  --set externalAccess.service.port=443

**Expected behavior**
Allow any port, including 443, to appear in externalAccess.service.port.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
3.1
```

- Output of `kubectl version`:

```
1.15
```

**Additional context**

I'd be willing to make a PR, but I feel like it would be a pretty large change as I would probably be removing a lot of the EXTERNAL/INTERNAL listeners in favor of a single listener that is used for both and alter the scripts-configmap.yaml to not change the `KAFKA_CFG_LISTENERS`, only the `KAFKA_CFG_ADVERTISED_LISTENERS` after it has gotten the appropriate IP from the loadBalancerIPs list or SHARED_FILE.

**Comment by Mauraza** [comment]
Hi @kyle-winkelman, 

Exactly you need to be root to be able to use port 443 as it is a protected port. You can't do it with a non-root container.

**Comment by kyle-winkelman** [comment]
The main problem is the [kafka-external port](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L288-L291) is hard coded to 19092, so the [kafka-external service](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/svc-external-access.yaml#L37-L39) will always point to port 19092 even if you start the externalAccess.service.port on something different.

**Comment by kyle-winkelman** [comment]
The secondary problem is the port 443 issue. I believe there shouldn't be an INTERNAL and an EXTERNAL listener (i.e. [remove this](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L142-L155)). There should be one port opened at service.port and then the kafka-external service should just direct traffic from externalAccess.service.port to service.port.

**Comment by Mauraza** [comment]
The issue will be closed when the PR is closed
