### ISSUE TITLE
Generation of log files only works if –set postgresqlImage.debug=true is set to true

### ISSUE THREAD

**Issue by jebru2** [bitnami/charts#2382]
**Which chart**:
The name (and version) of the affected chart
bitnami/postgresql-ha (default)

**Describe the bug**
postgres logs are not accessable from kubectl logs postgres-postgresql-ha-postgresql-0, unless the –set postgresqlImage.debug flag is set to true. 

**To Reproduce**
Run the following

1. run helm install $deployname bitnami/postgresql-ha --set postgresql.configurationCM=postgres --set postgresqlImage.debug=false
2. generate some log entries fx.. select this does not exits..
3. run kubectl logs postgres-postgresql-ha-postgresql-0
4. observe that there is no log output from the node. (limited log output exists few lines are coming out)
5. now set postgresqlImage.debug=true and observe the difference.

**Expected behavior**
I would expect to see the same amount of postgresql log as when the postgersqlimage.debug is set to true. I would need full postgresql log. being able to have access to the postgresql log is essential for any operation. 

**Version of Helm and Kubernetes**:
helm: v3.1.2
Kubernetes: v1.14.10-gke.27

**Comment by Mauraza** [comment]
Hi @jebru2,

I believe that the information that appears in the logs should be a variable, which can be modified according to the user's preferences or the case. In the end, if you want more information just put debug=true.
