### ISSUE TITLE
[bitnami/mariadb-galera] How to install additional plugin such as columnstore

### ISSUE THREAD

**Issue by fzhan** [bitnami/charts#23867]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

Enable additional plugin to be installed. At the moment there's no option to allow image to run 
```
apt install libjemalloc2 mariadb-backup libmariadb3 mariadb-plugin-columnstore
```

### What is the feature you are proposing to solve the problem?

Bring ability to install additional plugins for mariadb.

**Comment by javsalgar** [comment]
Hi!

For this case, you may need to create a fork of the container where you build and install the additional plugins for MariaDB.
