### ISSUE TITLE
[bitnami/kibana] Kibana should listen in "::" for IPv6 compatability

### ISSUE THREAD

**Issue by stv0g** [bitnami/charts#2386]
**Which chart**: kibana

**Describe the bug**

Connections to the kibana frontend are not possible on a IPv6 only cluster.

**To Reproduce**

Deploy a kibana chart with default values.

**Expected behavior**

Kibana should listen on "::"

We just need to change the following line:

https://github.com/bitnami/charts/blob/master/bitnami/kibana/templates/configmap.yml#L10

Listening on "::" will also listen on IPv4.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @stv0g, thanks for opening this issue. I don't see any cons on your proposal. Would you like to open a PR to address the changes? Let us know what you think!

**Comment by stv0g** [comment]
Hi @andresbono ,

I created a PR #2401
