### ISSUE TITLE
Error: parse error at (redis/charts/common/templates/_resources.tpl:15): unclosed action

### ISSUE THREAD

**Issue by rrigoni** [bitnami/charts#23884]
### Name and Version

bitnami/redis

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Any redis installation attempt on a k8s or kind kubernetes cluster fails with the  following error: 
`Error: parse error at (redis/charts/common/templates/_resources.tpl:15): unclosed action`

Installation commands:
`helm repo add bitnami https://charts.bitnami.com/bitnami`
`helm repo update`
`helm install redis bitnami/redis`

Helm version:
`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

### Are you using any custom parameters or values?

No, no custom values were set. 

### What is the expected behavior?

That the installation works without failures. 

### What do you see instead?

```
Error: parse error at (redis/charts/common/templates/_resources.tpl:15): unclosed action
```

### Additional information

This worked until last week, yesterday it started failing. 
I created an Ubuntu VM to test this out and it also fails in Ubuntu.

**Comment by rrigoni** [comment]
Removing and reinstalling helm solved the issue.

**Comment by bmgante** [comment]
Hi all,

I am facing this issue and helm-playground reports the same error:

https://helm-playground.com/#t=N7D0CoCgGEHsAcCeAnAlgcwBYBcAEA1AWQHcBDZAUwBpcBJAOwGMA6SAZQAUARADQFoAMqkYV6AZwp9aAE1HZUAM1QVkALlwBBDhugAJAKJ8ATMwAMkcKAC%2BVyJBARcAN1QBbdRLxKANhWyJ4CgBeVwBXMWxSRkwKdUsbOwcoACU-UOR6XFJcSjFYdJEcigBHUIoI0G83VDxYACMAKwpGPDrSCWlcWEzs9FQnUVx4XL9WABUYiSGR7DEsylwFWGRcNrFhXGxy%2BXp0LPpO%2Blg8VwpSejxsWFWKXHCKTtRM4dhpUJbUbvtgXCfGb1CslwACJGLBXK5usxcvlkCIxMxhuU-MDcAAKaTCPDA-yBVHA%2BjnWDAgCUuD4CXithAfFwsiU9FuoPBkPo0PKsPhiJmqIp1LA4FwE1uVVcNTm5Fu2BiRVK2zmf0o7Qeq0QuAArKYAKToigADxE8DwFHgMVOyFI3j4EWWpHQFBJVO%2BtIAJEjPHNVEE6VjILgQYSjqiMVjcH7-RHgZQ5RExMHMS0QYx4KF8QBGUymVz406Q5CIdNGAAchFQ%2BJNZpUlutVwt9vxmtLpPDEZBovF8dDoJT6c12ZBueWBZBaYAnEYmyCKxRzdWbXWKOnTEYACxNkktjf%2B4FixjIYnohN4FuR6NlWOdxPd1Mgox9nMzof4u8ANknwOns6t87ti5BjbLLdWzbapZkvbFkxvYEAGYAHZ1X7HdH3zfFoKLNcyynU0Zyrb9a1-JdV3XTdw2BMRXEtbxwLDYCQTPeVqOvBtM0QwcUP-NMJ0wj9sK-GtbXrf9TGI2jgXbMDDy7SD8XgrMHzzYdgVgl8S24z9cP4hdCIw5sIyApDMVCfsQ0TE9t3oi9JKvaShLkgdkMUjMiLU3iNJ-QTgQA3TgLE0C4ysiCexBWTWIc3toLfFzKwtPCBL-YEnJ0oDcH07xyEEkzj1EiyJMypMgoSsx5KfW9TBXVTy1cmLNIIoSRJ88T-LypiR2YdVivYmDTFgrjKuiud8I8xL6pS0i9TS5AMqPGifJyprppa4ETFMDrFJXUxR0ivqcOq9z4q85LI0axibJgor7IU-EXzTFcdKw-rYq0kdlySkjtyMcb0r-PKzLokpz1yhbTpXc6kMukEizHXr7p2ga4uYkajr8k6CpfUG2McoxiwqmG%2BL27SRq3BIaV%2BBRcEwdoAGkKDVN0ZjmZhcVuPlnV%2BA59VwOnkVmXBGYCW4AB9NlgABNUhXG8clieAWkKG8KYWZJ4YnmwMngX0ZJkgAeWSdQOBmXAAGsadwAByLUxFNtmnEtVBpGYTRvG8WBiBVG2AXKeZbgt1E%2BcCdEGlgJ4QSoYNjcQOYuY9EkySFhRSFQSXFZl3BRE6ZPZYOKWrCAA&v=LQhQEsBcFMFsGcBcACA2gIgGbgE70ugDTLrzQDGA9gHYAm6AuqEA

**Comment by jnissan1** [comment]
Upgrading helm executable helped me.
from here - https://github.com/bitnami/charts/issues/14449
