### ISSUE TITLE
How to enable logfile to be created and read from /var/log/ folder? 

### ISSUE THREAD

**Issue by abindlish** [bitnami/charts#23885]
### Name and Version

redis 17.11.8

### What architecture are you using?

AKS Linux VMs(amd64)

### What steps will reproduce the bug?

We are trying to add logfile at /var/log/redis-server.log by enabling the config in the configmap. But there is permission denied error.
We need this as out promtail scrapes it by default from this location.

### Are you using any custom parameters or values?

logfile 'var/log/redis.log'

### What do you see instead?

Permission denied on POD restart

**Comment by carrodher** [comment]
Could you please provide the configmap and the exact error? Thanks

**Comment by abindlish** [comment]
Error is 

*** FATAL CONFIG FILE ERROR (Redis 7.0.12) ***
Can't open the log file: Permission denied

Configmap:
data:
  master.conf: |-
    dir /data
    # User-supplied master configuration:
    rename-command FLUSHDB ""
    # End of master configuration
  redis.conf: |-
    # User-supplied common configuration:
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    logfile '/var/log/redis.log'
    # End of common configuration
  replica.conf: |-
    dir /data
    # User-supplied replica configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of replica configuration




We are just pulling the charts and deploying, no modifications are done.

**Comment by abindlish** [comment]
is there any update on this?

**Comment by abindlish** [comment]
Can someone please provide some inputs on this issue, this is really affecting the dev teams as they cant view redis logs

**Comment by abindlish** [comment]
Thanks for the revert. We will try the options suggested. But do you have a link to the documentation that states this option of changing the config runasroot=true?
I don't think I came across it.

**Comment by FraPazGal** [comment]
Hello @abindlish, although it not a strictly documentation, you can see the list of parameters our `bitnami/redis` supports [here](https://github.com/bitnami/charts/tree/main/bitnami/redis#parameters). You can also check similar information in the `values.yaml` file. 

Besides that, you can check a brief explanation on nonRoot usage in our [Best Practices guide](https://docs.bitnami.com/tutorials/production-ready-charts/#use-non-root-containers). I hope it is helpful!
