### ISSUE TITLE
[bitnami/fluentd] Remaining Helm / GoLang template fragments in README

### ISSUE THREAD

**Issue by stv0g** [bitnami/charts#2389]
**Which chart**: fluentd

**Describe the bug**

There are some Go template pieces copied into an ConfigMap example in the README which will not be processed by the template engine:

https://github.com/bitnami/charts/tree/f5f5a1c03abe26d8242f6ac97f8e74c9dd30943d/bitnami/fluentd#forwarding-the-logs-to-another-service

**Comment by andresbono** [comment]
Hi @stv0g, it seems the following line is breaking the template:

https://github.com/bitnami/charts/blame/f5f5a1c03abe26d8242f6ac97f8e74c9dd30943d/bitnami/fluentd/README.md#L235
```
{{- end }}
```

Can you confirm that removing it solves the issue?

**Comment by stv0g** [comment]
There's also:

```
<source>
      @type prometheus
      port {{ .Values.metrics.service.port }}
    </source>
```

and

```
    <source>
      @type forward
      bind 0.0.0.0
      port {{ .Values.aggregator.port }}
    </source>
```

**Comment by stv0g** [comment]
Hi @andresbono,

I created a PR for removing the template fragments: #2400

**Comment by andresbono** [comment]
Thanks, we will review it shortly.
