### ISSUE TITLE
[bitnami/mysql] Automatically Add Any `extraPorts` to `NetworkPolicy` Ingress

### ISSUE THREAD

**Issue by BHSDuncan** [bitnami/charts#23893]
### Name and Version

bitnami/mysql 9.21.2

### What is the problem this feature will solve?

There may be a good reason why this isn't done, but I thought I'd suggest it anyway in order to save people a few hours of hunting around. (If I've missed something, please feel free to let me know and close this request.)

Currently, if any `extraPorts` are added (e.g. exposing 33060 for `mysqlx` and the X plugin), the relevant service still can't be reached unless `networkPolicy.extraIngress` is added with the corresponding port(s).

I'd assume (perhaps incorrectly) that if people are using `extraPorts` to expose new ports, then they are probably looking to access the pods/services from outside the MySQL pod/container itself.

### What is the feature you are proposing to solve the problem?

One of two things:

- Automatically add or map `extraPorts` to an additional `ingress` block in the `NetworkPolicy`; or,
- Update the `extraPorts` docs to indicate that people should probably add those same ports to the `networkPolicy.extraIngress` setting if they want to be able to access those ports externally.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I believe it makes sense. Would you like to submit a PR adding it?

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
