### ISSUE TITLE
[bitnami/harbor] Error pulling image no such host but portal works fine

### ISSUE THREAD

**Issue by nirupbbnk** [bitnami/charts#23901]
### Name and Version

bitnami/harbor latest version

### What architecture are you using?

None

### What steps will reproduce the bug?

exposing using nginx ingress with ssl 

### What is the expected behavior?

should be able to pull image using docker pull 

### What do you see instead?

Error response from daemon: Get "https://harbor.nutrikorr.com/v2/": dial tcp: lookup harbor.nutrikorr.com on 172.19.192.1:53: no such host

### Additional information
I am able to access the portal using https://harbor.nutrikorr.com , works fine , but image pull is not happening , I am following https://medium.com/@elementtech.dev/kubernetes-image-proxy-cache-from-minutes-to-milliseconds-fd14173e831f
_No response_

**Comment by javsalgar** [comment]
Hi,

The `no host error` seems to be an issue with the DNS, not related to the Bitnami Harbor chart. I tried accessing https://harbor.nutrikorr.com/v2/ and found no issues. Could you check the DNS configuration of the docker daemon?

**Comment by nirupbbnk** [comment]
ya it was issue with my dns , closing
