### ISSUE TITLE
[bitnami/mongodb] Empty-Dir volume is missing in the default arbiter node configuration

### ISSUE THREAD

**Issue by SeWieland** [bitnami/charts#23905]
### Name and Version

bitnami/mongodb 14.12.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the chart with default values and replicaset architecture with arbiter node.

In version 14.12.0, the arbiter node declares mounts of the "empty-dir" volume.
However, the empty-dir volume only gets created conditionally using:

`{{- if or .Values.arbiter.configuration .Values.arbiter.existingConfigmap .Values.arbiter.extraVolumes .Values.tls.enabled }}`

### What is the expected behavior?

The empty-dir volume should be created unconditionally

### What do you see instead?

The arbiter pod cannot be created:

`create Pod mongodb-arbiter-0 in StatefulSet mongodb-arbiter failed error: Pod "mongodb-arbiter-0" is invalid: [spec.containers[1].volumeMounts[0].name: Not found: "empty-dir", spec.containers[1].volumeMounts[1].name: Not found: "empty-dir", spec.containers[1].volumeMounts[2].name: Not found: "empty-dir", spec.containers[1].volumeMounts[3].name: Not found: "empty-dir"]`

### Additional information

https://github.com/bitnami/charts/commit/550fbdc01cd0be150d049bfebccd5ad4b8f81f7f#diff-612eca9dddc4865c19f9f215f63fdd2c6089626c7a7d2102c2d713abd196aed7

**Comment by SeWieland** [comment]
As a workaround I simply added 

```yaml
arbiter:
  # Workaround for https://github.com/bitnami/charts/issues/23905
  extraVolumes:
  - name: dummy-dir
    emptyDir: {}
```

To my values yaml until this issue gets resolved

**Comment by javsalgar** [comment]
Hi! Thank you so much for reporting. I created the PR above to fix the issue.
