### ISSUE TITLE
Request for Citus data prod ready docker image

### ISSUE THREAD

**Issue by abhi7788** [bitnami/charts#2391]
**Which chart**:
Request for a new chart/docker image

**Is your feature request related to a problem? Please describe.**
Are there any plans for your team to look into creating production ready citus cluster on Kubernetes. From my own experience i found citus a really Powerful database solution however due to absence of production ready citus docker image pose a great challenge

**Describe the solution you'd like**
Create a production ready docker and helm chart for citus data

**Describe alternatives you've considered**
Currently looking into MariadB columnar store engine and Postgres database

**Additional context**
Let me know if you need detail about the issues with current citus data docker image which restricts its adoption as a solution

**Comment by carrodher** [comment]
Hi,

Thanks for your suggestions, Citus is not in our roadmap at this moment, we are working on provide a solution based on PostgreSQL with Patroni which can fit into similar use cases.
Regarding Citus, we will consider it for the future as it is on our radar, but as I mention, it is not in our roadmap right now.

Best regards,

**Comment by abhi7788** [comment]
Thanks @carrodher for the update. I am looking forward for the Postgres solution you have mentioned especially if it can provide distributed capabilities.

**Comment by abhi7788** [comment]
@carrodher before closing this issue, any eta on the solution that you have mentioned above.

**Comment by carrodher** [comment]
We have a task included in our backlog and we already did some advances, but it also depends on other priorities, so I am sorry but, at this moment, I can't provide an ETA for this new asset.

**Comment by abhi7788** [comment]
No problem @carrodher . Thanks alot for the information and all the awesome work you guys are doing!!!

**Comment by prakash7396** [comment]
Hi abhi,you have citusdata helm charts..if there means please share us

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
