### ISSUE TITLE
Add a Helm chart for RedisInsight

### ISSUE THREAD

**Issue by lusu007** [bitnami/charts#23926]
### Name and Version

None

### What is the problem this feature will solve?

Adds a UI component to manage Redis instances. This could also be added as an optional component to the existing Redis Helm charts.

### What is the feature you are proposing to solve the problem?

RedisInsight just released the 2.0 version as a Docker image, which contains major improvements over 1.0. I think Bitnami should add this to their repository to complete the management of Redis.

see: https://github.com/RedisInsight/RedisInsight/issues/519#issuecomment-1919562231

### What alternatives have you considered?

None

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. To ensure that your idea receives the attention it deserves, we will apply the 'on-hold' label. This will prevent our automated system from prematurely closing the issue.

We will keep you updated on any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.

**Comment by lusu007** [comment]
Hey @carrodher is it possible to prevent stale markings?

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
