### ISSUE TITLE
[bitnami/grafana-loki] Promtail pods should not be created with label 'loki-gossip-member: "true"'

### ISSUE THREAD

**Issue by rprin** [bitnami/charts#23939]
### Name and Version

bitnami/grafana-loki 2.18.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the chart with promtail enabled

### What is the expected behavior?

Promtail pods do not expose the gossip ring port (7946) so they should not be created with label `loki-gossip-member: "true"`.
This label is used as a pod selector by the `gossip-ring-headless-service`, so the service can try to forward traffic to the pods (instead of loki pods).

### What do you see instead?

Promtail pods are created with label 'loki-gossip-member: "true"'

### Additional information

I deployed the chart on two clusters, I had no problem for the first cluster, but for the second the distributor pod could not start, with the following errors.

`ts=2024-02-27T09:08:58.491267125Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with:  10.42.223.168:7946"
ts=2024-02-27T09:08:58.49340105Z caller=memberlist_logger.go:74 level=debug msg="Failed to join 10.42.132.255:7946: dial tcp 10.42.132.255:7946: connect: connection refused"
ts=2024-02-27T09:09:08.494447563Z caller=memberlist_logger.go:74 level=debug msg="Failed to join 10.42.63.172:7946: dial tcp 10.42.63.172:7946: i/o timeout"`

After manually removed the label from the promtail daemonset manifest and restarted the promtail pods, the distributor pod was able to start successfully.

This bug cannot be always reproduced, I think it depends on how the service choose the pod it forwards traffic to.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Would you like to submit a PR fixing the issue?

**Comment by rprin** [comment]
Yes I will
