### ISSUE TITLE
[bitnami/spring-cloud-dataflow] enable metrics error in networkpolicy.yaml http is not a method 

### ISSUE THREAD

**Issue by anuragpathak21** [bitnami/charts#23932]
### Name and Version

bitnami/spring-cloud-dataflow 26.8.0

### What architecture are you using?

None

### What steps will reproduce the bug?

`helm dependency update`
`helm lint --set metrics.enabled=true`

### Are you using any custom parameters or values?

--set metrics.enabled=true

### What is the expected behavior?

The lint should passed

### What do you see instead?

[ERROR] templates/: template: spring-cloud-dataflow/templates/server/networkpolicy.yaml:87:26: executing "spring-cloud-dataflow/templates/server/networkpolicy.yaml" at <.Values.metrics.service.ports.http>: http is not a method but has arguments

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I created the PR above to fix it.
