### ISSUE TITLE
[bitnami/kafka] Plaintext listener enabled when it shouldn't be

### ISSUE THREAD

**Issue by CharlieC3** [bitnami/charts#2393]
**Which chart**:
bitnami/kafka, version 10.2.6

**Describe the bug**
The `ALLOW_PLAINTEXT_LISTENER` env var is being set to `yes` despite configuring the property in `values.yaml` to false and while the `auth` property is enabled. This behavior is not expected.
This causes the following log to appear in the startup sequence:
```
 19:42:57.66 INFO  ==> ** Starting Kafka setup **
 19:42:57.70 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
```

**To Reproduce**
1. `helm install my-release \
  --set allowPlaintextListener=false \
  --set auth.enabled=true \
  bitnami/kafka`

**Expected behavior**
I would expect the `ALLOW_PLAINTEXT_LISTENER` env var to follow the value given from the `allowPlaintextListener` property, and not inference it from whether `auth` is enabled or not. Or at the very least, inverse the logic so if auth is enabled the `ALLOW_PLAINTEXT_LISTENER` is set to `no`, because currently it tries to enable the plaintext listener if auth is enable (which seems strange).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
https://github.com/bitnami/charts/blob/c8e9aa002c60e4b67a9822278115dcf585ff60a2/bitnami/kafka/templates/statefulset.yaml#L226-L227

**Comment by Mauraza** [comment]
Hi @CharlieC3, 

This is because of the `auth.enable` requires `allowPlaintextListener` to be set to `true`, which can be found in the [Kafka documentation](http://kafka.apache.org/090/documentation.html#security)

**Comment by CharlieC3** [comment]
@Mauraza ,
Thanks, I think I found the text here:
> The security implementation lets you configure different protocols for both broker-client and broker-broker communication. These must be enabled in separate bounces. A PLAINTEXT port must be left open throughout so brokers and/or clients can continue to communicate.

http://kafka.apache.org/090/documentation.html#security_rolling_upgrade

Is this specifically what you're referring to? It seems like a strange requirement on Kafka's behalf. Someone who would enable SSL probably wouldn't want traffic still coming through in plaintext (like me).

I will close this ticket.
