### ISSUE TITLE
[bitnami/clickhouse] Add support for sizing up an existing PV claim

### ISSUE THREAD

**Issue by kopax** [bitnami/charts#23943]
### Name and Version

bitnami/clickhouse 5.0.2

### What is the problem this feature will solve?

Increase the PV size from the chart, will solve manual PV size increase being unsyncede with the chart in argocd

When I play with `persistence.size`, I get the following error :

```
Failed sync attempt to 1b911c092db4327ce16aec779b659c2972c8e751: one or more objects failed to apply, reason: StatefulSet.apps "clickhouse-shard0" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
````

If I edit the pvc manually, I get a bigger pvc, but then argocd show clickhouse being unsync.

### What is the feature you are proposing to solve the problem?

Add a way to edit directly the PVC from the chart

### What alternatives have you considered?

NA

**Comment by javsalgar** [comment]
Hi,

Accoding to the message, it seems that the `size` of a PVC is considered an immutable field. This is done by design in Kubernetes so there's not much we can do in the chart.

**Comment by kopax-polyconseil** [comment]
Do you have a recommendation on how to do that properly ?

**Comment by javsalgar** [comment]
What I would do is to create a backup of the clickhouse data, then create a new fresh installation with the proper PVC size and then dump the backup data. However, let's see if someone from the community has experience with any PVC resizer.
