### ISSUE TITLE
[bitnami/airflow] kubernetes executer support

### ISSUE THREAD

**Issue by ishioni** [bitnami/charts#2394]
**Which chart**:
bitnami/airflow-6.1.7

Since airflow-1.10.0 the kubernetes executor is officially supported. Any change we can use it instead of celery, including the necessary RBAC templates and airflow.cfg generation? I'll be trying to modify the chart on my own to add these features, but I'm very fresh to airflow itself, so I'd appreciate this feature being there to use. I'll be using [this chart](https://github.com/BrechtDeVlieger/airflow-kube-helm) as reference

**Comment by javsalgar** [comment]
Hi,

Sure! Feel free to contribute with a PR. If you can't, we will add a task in our backlog but, as it is not a critical feature, we would not able to guarantee an ETA.

**Comment by sacuja** [comment]
Hello,
Do we have kubernetes executer supported in Bitnami Airflow helm charts ?

**Comment by javsalgar** [comment]
Hi! It is currently in our backlog. As soon as we have more news, we will update the ticket
