### ISSUE TITLE
[bitnami/airflow] ssh git credentials support in git-repo-syncer

### ISSUE THREAD

**Issue by ishioni** [bitnami/charts#2395]
**Which chart**:
bitnami/airflow-6.1.7

There is no support to embed a ssh key into git-repo-syncer. Seeing as one could use a deploy key just for airflow, instead of exposing user/pass via https cloning, it would be a much safer option

**Comment by javsalgar** [comment]
Hi,

In some charts we have the extraVolumeMounts and extraVolumes section that allow you to include extra elements to the containers. Would that work for your case? Maybe also allowing to customize the syncer command could cover your use case?

**Comment by austinbv** [comment]
This would be great to support

**Comment by javsalgar** [comment]
Hi,

I think this PR should cover the use case https://github.com/bitnami/charts/pull/2595

**Comment by kad-bijste** [comment]
Did anybody manage to clone a git repo with dags using ssh git credentials recently (release 10.3.x)?
