### ISSUE TITLE
[bitnami/minio] Changing `containerPorts.api` causes the pods to fail health probes on startup

### ISSUE THREAD

**Issue by pvallone** [bitnami/charts#23953]
### Name and Version

bitnami/minio 13.6.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set `containerPorts.api` to `9020` and deploy the chart to Minikube or another k8s cluster.
2. Notice that the health probes fail with "connection refused" errors when trying to communicate with MinIO over the modified port. They fail even if one sets `service.ports.api` to `9020` too.

### What is the expected behavior?

The pods should start up, and the health probes should successfully communicate with MinIO over port `9020`.

### What do you see instead?

The pods fail to start up, with the health probs failing due to "connection refused" errors when trying to use port `9020`.

**Comment by migruiz4** [comment]
Hi @pvallone,

Thank you for reporting this issue and I'm sorry for the late response.

I have submitted this PR fixing this issue: https://github.com/bitnami/charts/pull/24591
