### ISSUE TITLE
[bitnami/fluentd] NetworkPolicy of aggregator should include aggregator port

### ISSUE THREAD

**Issue by fgleixner** [bitnami/charts#24008]
### Name and Version

bitnami/fluentd 5.18.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy chart with default values. It will create a forwarder Daemonset and a aggregator StatefulSet. And it will create Network Policies for these that include ingress rules for 9880 and 24231. But the forwarder Pods cannot ship logs to the aggregator which listens on the port 24224 by default.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

The Helm chart should create a ingress rule for the aggregator that includes the value of aggregator.port

### What do you see instead?

Forwarders cannot connect to aggregator.

### Additional information

Workaround is setting of
```yaml
aggregator:
  networkPolicy:
    extraIngress:
      - ports:
          - port: 24224
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
