### ISSUE TITLE
[bitnami/grafana-operator] Issue with Service account overwriting

### ISSUE THREAD

**Issue by arvindpalani** [bitnami/charts#24024]
### Name and Version

Grafana 10.1.4 image version, Grafana operator 5.4.1 version 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

While I am upgrading the grafana version from 4.10.1 to 5.4.1, there is new deployment creating which have new service account and service account name assigned to it. But I tried to overwrite the new service account with the exisiting account name in values.yaml. But I can only do it for grafana operator, but not for grafana. I want help in the correct tag and how to overwrite it. I tried with many tag, but it is not working.

### What do you see instead?

I can't overwrite the new serviceaccount name

**Comment by javsalgar** [comment]
Hi,

In the grafana object there is this section

```
  {{- if .Values.grafana.serviceAccount }}
  serviceAccount:
    {{- include "common.tplvalues.render" ( dict "value" .Values.grafana.serviceAccount "context" $ ) | nindent 4 }}
  {{- end }}

``` 

Did you try setting the definition for this field?

**Comment by BJKupka** [comment]
I came across this issue whilst migrating to the bitnami helm chart. I structured my service account configuration based on the comment found [here](https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/values.yaml#L542-L544).

I simply replaced with my actual service account key/value (key/value scrubbed below):

```
   serviceAccount:
     annotations:
      {my_service_account_key_here}: "{my_service_account_value_here}"
```

It blew up with the following:

```
Error from server (BadRequest): error when creating "grafana-operator.yaml": Grafana in version "v1beta1" cannot be handled as a Grafana: strict decoding error: unknown field "spec.serviceAccount.annotations"
```

I ended up looking back and adopting our previously configured grafana deployment's service account configuration, which ended up working:

```
   serviceAccount:
     metadata:
        annotations:
         my_service_account_key_here}: "{my_service_account_value_here}"
``` 

The grafana template for `serviceAccount` is just defined as an object, so not exactly sure why the former failed and the latter worked tbh.
