### ISSUE TITLE
[bitnami/elasticsearch] metrics deployment uses incorrect URL if kibana is enabled

### ISSUE THREAD

**Issue by BadLiveware** [bitnami/charts#24038]
### Name and Version

bitnami/elasticsearch 19.19.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Enable kibana and override elasticsearch service name

The service name is defined by this template:
https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/_helpers.tpl#L49-L60

The metric exporter deployment uses different logic for the service name:
https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/metrics/deployment.yaml#L94

### What do you see instead?

The metric deployment cannot connect to elasticsearch

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
