### ISSUE TITLE
[bitnami/grafana] Grafana crashes when using dashboard provider

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#24042]
### Name and Version

bitnami/grafana 9.11.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the latest chart, configuring to use dashboard provider
2. Witness crash on startup

### Are you using any custom parameters or values?
Install the chart, enabling dashboardsProvider:
`helm install my-release oci://registry-1.docker.io/bitnamicharts/grafana --set dashboardsProvider.enabled=true`

### What is the expected behavior?

Pods startup successfully

### What do you see instead?

```
grafana 15:13:28.85 INFO  ==> 
grafana 15:13:28.86 INFO  ==> Welcome to the Bitnami grafana container
grafana 15:13:28.86 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
grafana 15:13:28.86 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
grafana 15:13:28.86 INFO  ==> 
cp: cannot create directory '/opt/bitnami/grafana/conf/./provisioning/access-control': Permission denied
cp: cannot create directory '/opt/bitnami/grafana/conf/./provisioning/notifiers': Permission denied
cp: cannot create directory '/opt/bitnami/grafana/conf/./provisioning/alerting': Permission denied
cp: cannot create directory '/opt/bitnami/grafana/conf/./provisioning/plugins': Permission denied
cp: cannot create regular file '/opt/bitnami/grafana/conf/./provisioning/dashboards/sample.yaml': Read-only file system
cp: cannot create directory '/opt/bitnami/grafana/conf/./provisioning/datasources': Permission denied
```

### Additional information

This began happening after upgrading the chart from v9.10.2 to v9.11.0

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! I created the PR above to fix the issue https://github.com/bitnami/charts/pull/24055
