### ISSUE TITLE
[bitnami/mongodb] Allow secondary use different storageclass

### ISSUE THREAD

**Issue by caiohasouza** [bitnami/charts#2405]
**Which chart**:
mongodb 7.13.x

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to be possible configure a differente storageclass to secondary, this approach allow i run primary/secondary/arbiter in differente AWS zones.

**Describe alternatives you've considered**
Add a persistent option to a secondary.

**Additional context**
this has already been discussed in PR https://github.com/bitnami/charts/pull/2398

**Comment by dani8art** [comment]
Hi @caiohasouza, Thank you for opening this issue, I see you created a PR too, let's move there the conversation.
