### ISSUE TITLE
[bitnami/redis-cluster] metrics-svc.yaml: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by glimberg** [bitnami/charts#2408]
**Which chart**:
bitnami/redis-cluster v2.0.7

**Describe the bug**

line 23 of the template should use nindent rather than indent.  Pull request shortly

As it is currently, the following error occurs:

Error: YAML parse error on redis-cluster/templates/metrics-svc.yaml: error converting YAML to JSON: yaml: line 17: mapping values are not allowed in this context

**To Reproduce**
`helm install test . -f ./values-production.yaml --dry-run`

**Expected behavior**
There should be no error using the default production values

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
 ```

**Additional context**

**Comment by carrodher** [comment]
Thanks for reporting the issue and creating a PR. As I mention in the PR, our CI/CD system is in progress.

**Comment by carrodher** [comment]
By the way, I think this issue is related to this one #2367. Just for the records
