### ISSUE TITLE
[Kafka] Chart fails to start - zookeeper is in pending state

### ISSUE THREAD

**Issue by hatharom** [bitnami/charts#2410]
**Which chart**:
Kafka 10.2.6

**Describe the bug**
Zookeeper pod is in pending state.

**To Reproduce**
I have followed the very first command in the readme 

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/kafka
```
It works.
But once I have an other resourse running- elasticsearch in this case - kafka fails to startup.

Kafkapod  is crashing because of missing ZK connection. ZK is in pending state.

```
kubectl descripe pods jazzy-bronco-zookeeper-0
says Insufficient cpu
```
So what now? How to debug this? My cpu is running only with a 10% load
Other Kafka charts or hand made kafka k8s resource work well.

**Expected behavior**
To start up. Or at least show some error message

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Ran with minikube.

**Comment by carrodher** [comment]
Minikube is launching a VM in your local machine, so the machine running out of CPU is the VM. Did you check the CPU of the local or the virtual machine?

You can modify some parameters before starting minikube:
```
minikube start --help
...
      --memory='2000mb': Amount of RAM allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or
g).
      --cpus=2: Number of CPUs allocated to the minikube VM.
```
