### ISSUE TITLE
mysql charts should use different nodePort config for master and slave when service type is NodePort

### ISSUE THREAD

**Issue by gawainguo** [bitnami/charts#2414]
**Which chart**:
mysql:8.0.19

**Describe the bug**
mysql-master and mysql-slave services use same nodePort when service type is NodePort and cause port conflicting.

**To Reproduce**
1. Set service.type: NodePort
2. Set service.port: 30XXX
3. Helm instal failed and give the port already in used error:
```
Error: Service "demo-db-mysql" is invalid: spec.ports[0].nodePort: Invalid value: 30036: provided port is already allocated
```
which is allocated by slave service

**Expected behavior**
mysql-master and mysql-slave should use different nodePort config to avoid conflict.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting. This is an issue that it is fixed in the mariadb chart but did not solve yet in the mysql chart. I will open a task for fixing it and let you know when the fix is available.

**Comment by cdmikechen** [comment]
It still need to be fixed, I have a same problem.

**Comment by javsalgar** [comment]
I created this PR https://github.com/bitnami/charts/pull/2579
