### ISSUE TITLE
[bitnami/kube-prometheus] seLinuxOptions defaults are not valid

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#24159]
### Name and Version

bitnami/kube-prometheus 8.29.1

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/charts/commit/57a916f142666b5ca6c43a22f46761ad051ffa3b, https://github.com/bitnami/charts/commit/b91a628df5fb47a5e7e03f23a468f2a5d91da7bd and others have set seLinuxOptions to 'null' which is not valid on non openshift clusters from an apiserver perspective
This comes up as an error from flux as flux uses serverside-apply for drift correction.
However, the root cause is sending an invalid object to the apiserver, using server-side apply. 

```
    Message:               Could not determine release state: unable to determine cluster state: Alertmanager/monitoring-system/alertmanager-alertmanager dry-run failed (Invalid): Alertmanager.monitoring.coreos.com "alertmanager-alertmanager" is invalid: [spec.containers[0].securityContext.seLinuxOptions: Invalid value: "null": spec.containers[0].securityContext.seLinuxOptions in body must be of type object: "null", spec.containers[1].securityContext.seLinuxOptions: Invalid value: "null": spec.containers[1].securityContext.seLinuxOptions in body must be of type object: "null"]
```

The clean fix is not even spitting out fields that are set to null in the templating process, the quick fix is the old behavior of just having an empty object

### What is the expected behavior?

Having valid defaults that the apiserver can actually diff

### What do you see instead?

a broken helmRelease as the apiserver can't diff old and new states anymore

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. If that's the case, then I would do the following:

- Revert the default seLinuxOptions to an empty object
- Update the `common.compatibility.renderSecurityContext` helper (which is done to perform adaptations to openshift in securityContexts) and make it omit the seLinuxOptions value if it is an empty object.

**Comment by javsalgar** [comment]
I created this PR to allow returning the seLinuxOptions to empty object https://github.com/bitnami/charts/pull/24268

**Comment by javsalgar** [comment]
Reopening the issue until it is fixed in kube-prometheus.

**Comment by Zebradil** [comment]
We experience the same issue with the grafana-operator chart. Could the same solution (changing from `null` to `{}`) applied there too?

**Comment by javsalgar** [comment]
It's here https://github.com/bitnami/charts/pull/24647
