### ISSUE TITLE
[bitnami/redis]

### ISSUE THREAD

**Issue by Juancarlosmartin10** [bitnami/charts#2415]
Hi team, 

It is possible to add a line onn redis.conf?¿ I need to activate Event Notification on Sentinel Redis Kubernetes. The line to add on redis.conf is the following:

notify-keyspace-events Ex

**Comment by rafariossaa** [comment]
Hi @Juancarlosmartin10 ,
  You can set you own redis.conf in the value.yml.
  Could you take a look to [this](https://github.com/bitnami/charts/blob/e9ae77b89be07c1fd00ea7e9d181542eb4dedb90/bitnami/redis/values.yaml#L85) ?

**Comment by Juancarlosmartin10** [comment]
Hi @rafariossaa , 
This configmap is for sentinel container, but not for redis, if I Put there this line, It will be applied for Redis container too?

**Comment by rafariossaa** [comment]
I am sorry, I indicated the wrong line number.
You can set the configuration for the master and slaves, [here](https://github.com/bitnami/charts/blob/e9ae77b89be07c1fd00ea7e9d181542eb4dedb90/bitnami/redis/values.yaml#L235) and [here](https://github.com/bitnami/charts/blob/e9ae77b89be07c1fd00ea7e9d181542eb4dedb90/bitnami/redis/values.yaml#L412).

**Comment by Juancarlosmartin10** [comment]
Many thanks, solved
