### ISSUE TITLE
[bitnami/grafana-tempo] Grafana Tempo chart sets deprecated configuration

### ISSUE THREAD

**Issue by bpfoster** [bitnami/charts#24164]
### Name and Version

bitnami/grafana-tempo 2.11.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Installing the chart out of the box leads to warnings printed to the logs.

In Tempo v2.4, cache configuration was refactored and the old configuration methods have been deprecated.

https://grafana.com/docs/tempo/latest/release-notes/v2-4/#cache-configuration-refactored

### Are you using any custom parameters or values?

None

### What do you see instead?

```
level=warn ts=2024-03-05T14:06:15.05609389Z caller=main.go:130 msg="-- CONFIGURATION WARNINGS --"
level=warn ts=2024-03-05T14:06:15.05616032Z caller=main.go:136 msg="c.StorageConfig.Trace.Cache is deprecated and will be removed in a future release." explain="Please migrate to the top level cache settings config."
level=info ts=2024-03-05T14:06:15.056186335Z caller=main.go:225 msg="initialising OpenTracing tracer"
level=info ts=2024-03-05T14:06:15.069045124Z caller=main.go:118 msg="Starting Tempo" version="(version=2.4.0, branch=HEAD, revision=b1c4d3fbf)"
level=warn ts=2024-03-05T14:06:15.134927419Z caller=tempodb.go:623 msg="legacy cache configured with the following roles. Please migrate to the new top level cache configuration." roles="unsupported value type"
level=info ts=2024-03-05T14:06:15.134996091Z caller=cache.go:54 msg="caches available to storage backend" footer=false bloom=true offset_idx=false column_idx=false trace_id_idx=true page=false
```

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
