### ISSUE TITLE
kafka-exporter stops working when a kafka-controller in the cluster becomes unavailable

### ISSUE THREAD

**Issue by ingmars1709** [bitnami/charts#24179]
### Name and Version

bitnami/kafka v26.8.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy a kafka cluster with a `replicaCount` of 3 (kafka exporter runs OK)
2. Have 1 controller go offline for a long time
3. kafka-exporter is reporting errors and will start to crash the loop

### Are you using any custom parameters or values?

```yaml
kafka:
   controller:
       replicaCount: 3
   persistence:
       size: 8Gi
   extraConfig: |
       offsets.topic.replication.factor=2
       default.replication.factor=3
       auto.create.topics.enable=false
       min.insync.replicas=2
       unclean.leader.election.enable=false
       offsets.retention.minutes=43200
       log.retention.hours=720
   provisioning:
      replicationFactor: 3
```

### What is the expected behavior?

I expect the kafka-exporter to keep reporting metrics of the other two kafka-controllers that are still running.

### What do you see instead?
```
I0306 08:41:13.749929       1 kafka_exporter.go:800] Starting kafka_exporter (version=1.7.0, branch=non-git, revision=non-git)
I0306 08:41:14.534696       1 kafka_exporter.go:971] Listening on HTTP :9308
E0306 08:41:23.867204       1 kafka_exporter.go:421] Cannot get leader of topic __consumer_offsets partition 0: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
E0306 08:41:26.148119       1 kafka_exporter.go:430] Cannot get current offset of topic __consumer_offsets partition 0: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
E0306 08:41:28.431311       1 kafka_exporter.go:442] Cannot get oldest offset of topic __consumer_offsets partition 0: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
