### ISSUE TITLE
PR 23428 broke cloneHtdocsFromGit.extraVolumeMounts

### ISSUE THREAD

**Issue by berlincount** [bitnami/charts#24177]
### Name and Version

bitnami/apache HEAD

### What steps will reproduce the bug?

When using `cloneHtdocsFromGit.enabled`, two mismatched `else if` statements break the use of `volumeMounts`.

### What do you see instead?

Shadowed `volumeMounts` are not mounted, making e.g. the use of SSH keys as security credentials impossible.

### Additional information

https://github.com/bitnami/charts/pull/23428/files/f9b9e758506d334fed151a36af4ece05d0ebe8d9#r1500714983 and
https://github.com/bitnami/charts/pull/23428/files/f9b9e758506d334fed151a36af4ece05d0ebe8d9#r1500715136 show the broken conditionals causing the issues, @javsalgar has not reacted yet, but might not have been pinged.

Templated testing with diffs linked into PR might help uncover this kind of issue during the review.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by berlincount** [comment]
Was fixed in #24196
