### ISSUE TITLE
Rabbitmq Unable to add podAnnotations

### ISSUE THREAD

**Issue by kferrone** [bitnami/charts#2418]
**Describe the bug**
I am unable to add any podAnnotations to the RabbitMQ chart. 

**Version of Helm and Kubernetes**:
helm: 3.2.0
k8s: 1.15 eks

**Which chart**:
rabbitmq

**What happened**:

Here is the error I get when I add any kind of annotations to the pods:

> Error: YAML parse error on rabbitmq/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context

**What you expected to happen**:

Add the pod annotations with no fuss

**How to reproduce it** (as minimally and precisely as possible):

A simple example of what I tried in myValues.yaml:
```yaml
podAnnotations:
  foo: bar
```
This was the only value I used. I deleted all the rest of them until I discovered this was the failing value. 

**Anything else we need to know**:

Annotations in other parts of the chart did work. e.g. the ingress annotations

**Comment by juan131** [comment]
Hi @kferrone 

What version of the RabbitMQ chart are you using? I was unable to reproduce the issue using the latest version `6.25.5`:

```console
$ helm search repo bitnami/rabbitmq
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/rabbitmq	6.25.5       	3.8.3      	Open source message broker software that implem...
$ cat > values.yaml << 'EOF'
podAnnotations:
  foo: bar
EOF
$ helm template -f values.yaml rabbitmq bitnami/rabbitmq -s templates/statefulset.yaml
(...)
    metadata:
      (...)
      annotations:
        checksum/secret: cd5b9bdb9e576de4f45573bd41ea6d199433715e92856742f947da8053464f34
        foo: bar
    spec:
(...)
```

**Comment by kferrone** [comment]
Oh so I discovered a bit more about the issues. Its not just when the podAnnotations are set, it's when I have podAnnotations and metrics in the values like below. This is actually my entire values file. . . 

```yaml
podAnnotations:
  foo: bar
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

Here is my output:
```
 helm template -f values.yaml rabbitmq bitnami/rabbitmq
Error: YAML parse error on rabbitmq/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```
I also tried with `--debug` but It was quite long. However it did show me the actual failing line, look at the podAnnotation below and you will see the issue:

```yaml
annotations:
  checksum/secret: biglongsecret
  foo: barprometheus.io/port: '9419'
  prometheus.io/scrape: "true
```

While looking through the template I have found the offender:
```go
{{/*
Return podAnnotations
*/}}
{{- define "rabbitmq.podAnnotations" -}}
{{- if .Values.podAnnotations }}
{{- toYaml .Values.podAnnotations }}
{{- end }}
{{- if .Values.metrics.enabled }}
{{- include "rabbitmq.tplValue" ( dict "value" .Values.metrics.podAnnotations "context" $) }}
{{- end }}
{{- end -}}
```

I believe the `include` in the metrics enabled if block does not need the dash in front, i.e.
```go
{{ include "rabbitmq.tplValue" ( dict "value" .Values.metrics.podAnnotations "context" $) }}
```
This way the metrics annotations won't be pushed one line up.

**Comment by juan131** [comment]
Hi @kferrone 

Now I was able to reproduce it! Thanks so much for reporting this issue. I just created a PR to address it.
