### ISSUE TITLE
Nginx server block config deletes default https server config

### ISSUE THREAD

**Issue by simon-b64** [bitnami/charts#24180]
### Name and Version

bitnami/nginx 15.10.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Startup the image and set the serverBlock helmchart value.
Now the default https server-block won't be applied and the readinessprobes will fail.

### Are you using any custom parameters or values?

yes the serverBlock. e.g:
```yaml
serverBlock: |-
      server {
        listen  8080;

        include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
      
        location / {
          root html;
          index index.html index.htm;
        }
      
        location /file {
          autoindex on;
          autoindex_exact_size off;
          autoindex_localtime on;
        }
      }
```
### What is the expected behavior?

The default https server block will still be applied and the custom serverblock will just be added as stated in the default values comments.

### What do you see instead?

Readinessprobes fail and the helm chart won't deploy without disabling them

### Additional information

Current workaround:
Add a second serverblock to the serverblock config which is the default ssl serverblock

**Comment by juan131** [comment]
Hi @simon-b64 

As it's explained in the chart and the associated container tutorial below, this mechanism allows adding custom server blocks adding a custom `server-block.conf` file under the `/opt/bitnami/nginx/conf/server_blocks` directory:

- https://github.com/bitnami/containers/tree/main/bitnami/nginx#adding-custom-server-blocks

The default `nginx.conf` included in this container image use the `include` directive to add these server blocks in to the NGINX configuration, see:

- https://github.com/bitnami/containers/blob/main/bitnami/nginx/1.25/debian-12/rootfs/opt/bitnami/nginx/conf/nginx.conf#L44

You mentioned a https server block but there's no such a server block defined by default. The chart configure NGINX to expose the server in the "8080" port by default (http).
