### ISSUE TITLE
postgresql-ha 

### ISSUE THREAD

**Issue by cloud-arrow** [bitnami/charts#2419]
postgresql-ha 3.1.0

psql: could not translate host name "postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local" to address: Name or service not known
repmgr 19:21:10.63 DEBUG ==> Host 'postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local:5432' is not accessible

**Comment by rafariossaa** [comment]
Hi @cloud-arrow ,
  Could you describe what you where trying and the steps to reproduce this issue ?

Thanks forehand.

**Comment by alQlagin** [comment]
Hi! I have the same issue

Just run with helm and values-production.yaml from repo and got error with host resolve

![image](https://user-images.githubusercontent.com/3256488/82127718-33204a00-97cf-11ea-88af-42cdc75158d7.png)

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by AtomicNibble** [comment]
I had the same issue turns out `db-postgresql-ha-postgresql-1` was unable to connect to repmgr due to NetworkPolicy:

```yaml
networkPolicy:
  enabled: true
```

**Comment by rafariossaa** [comment]
Hi,
  I did:
```
  helm install my-pg -f values-production.yaml .
```
  and I got my pods running:
```
$ kubectl logs my-pg-postgresql-ha-postgresql-0 postgresql 
postgresql-repmgr 06:36:21.09 
postgresql-repmgr 06:36:21.10 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 06:36:21.10 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 06:36:21.10 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 06:36:21.10 
postgresql-repmgr 06:36:21.14 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
repmgr 06:36:21.23 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql 06:36:21.24 INFO  ==> Validating settings in POSTGRESQL_* env vars..
repmgr 06:36:21.24 INFO  ==> Querying all partner nodes for common upstream node...
repmgr 06:36:21.36 INFO  ==> There are no nodes with primary role. Assuming the primary role...
repmgr 06:36:21.37 INFO  ==> Preparing PostgreSQL configuration...
postgresql 06:36:21.37 INFO  ==> postgresql.conf file not detected. Generating it...
repmgr 06:36:21.46 INFO  ==> Preparing repmgr configuration...
repmgr 06:36:21.47 INFO  ==> Initializing Repmgr...
postgresql 06:36:21.48 INFO  ==> Initializing PostgreSQL database...
postgresql 06:36:21.49 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql 06:36:21.49 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 06:36:23.11 INFO  ==> Starting PostgreSQL in background...
postgresql 06:36:23.24 INFO  ==> Changing password of postgres
postgresql 06:36:23.27 INFO  ==> Starting PostgreSQL in background...
repmgr 06:36:23.27 INFO  ==> Creating repmgr user: repmgr
repmgr 06:36:23.31 INFO  ==> Creating repmgr database: repmgr
postgresql 06:36:23.55 INFO  ==> Stopping PostgreSQL...
postgresql 06:36:24.56 INFO  ==> Starting PostgreSQL in background...
repmgr 06:36:24.68 INFO  ==> Registering Primary...
postgresql 06:36:24.90 INFO  ==> Loading custom scripts...
postgresql 06:36:24.90 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 06:36:25.91 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql 06:36:26.00 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 06:36:26.23 INFO  ==> ** Starting repmgrd **
[2020-05-19 06:36:26] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2020-05-19 06:36:26] [NOTICE] starting monitoring of node "my-pg-postgresql-ha-postgresql-0" (ID: 1000)
[2020-05-19 06:36:26] [NOTICE] monitoring cluster primary "my-pg-postgresql-ha-postgresql-0" (ID: 1000)
```

  In which k8s cluster are you running the chart ?.

**Comment by alQlagin** [comment]
@AtomicNibble thanks) It runs as expected when i disabled networkPolicy

**Comment by rafariossaa** [comment]
hi @alQlagin ,
  In which k8s cluster are you running the chart ?

**Comment by AtomicNibble** [comment]
Well I suspect it is one where NetworkPolicy is enforced.

**Comment by rafariossaa** [comment]
We test our charts in Amazon, Google  and Azure in our CD/CI, that the reason I asking in which one. Maybe we need to adapt something or document this usage.

**Comment by AtomicNibble** [comment]
The cluster where I had the issue was using https://github.com/cilium/cilium for NetworkPolicy enforcement.

**Comment by rafariossaa** [comment]
@AtomicNibble, does it work for you if as @alQlagin stated you disable the neworkpolicy ?

**Comment by AtomicNibble** [comment]
Huh? I mentioned I had had same issue and solved it by disabling networkpolicy in this comment https://github.com/bitnami/charts/issues/2419#issuecomment-630469005

I was just following up to try help a fix end up in the chart.

**Comment by alQlagin** [comment]
> hi @alQlagin ,
> In which k8s cluster are you running the chart ?

Rancher installed with rke (hypercube under the hood)

**Comment by rafariossaa** [comment]
ok, thanks
