### ISSUE TITLE
Add support for hostPath data dir for rabbitmq

### ISSUE THREAD

**Issue by kolyadin** [bitnami/charts#24217]
### Name and Version

bitnami/rabbitmq:12.15.0

### What is the problem this feature will solve?

Bare metal installation support where pv/pvc is not supportted

### What is the feature you are proposing to solve the problem?

When persistence is set to true chart config must provide option for set up hostPath directory on host machine

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
