### ISSUE TITLE
Mismatch in default templating values used for rabbitmq-operator networkpolicy

### ISSUE THREAD

**Issue by randori-jgross** [bitnami/charts#24223]
### Name and Version

bitnami/rabbitmq-cluster-operator 3.20.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The helm templated values called for in the networkpolicy for both the cluster-operator and messaging-topography-operator don't match the defaults in values.yaml.

[Cluster Operator network networkpolicy](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/templates/cluster-operator/networkpolicy.yaml#L63)
Rendering value: `.Values.clusterOperator.metrics.enabled`
values.yaml value: `.Values.clusterOperator.metrics.service.enabled`
From: [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml#L483-L489)

[Message Topography Operator networkpolicy](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/networkpolicy.yaml#L69)
Rendering value: `.Values.msgTopologyOperator.metrics.enabled`
values.yaml value: `.Values.msgTopologyOperator.metrics.service.enabled`
From: [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml#L1081-L1087)

### What is the expected behavior?

Templated values match the defaults in values.yaml.  Either add `metrics.enabled: false` to the 2 sections in values.yaml, or use the value for `metrics.service.enabled` for networkpolicy logic.

### What do you see instead?

Ingress networkpolicy is not rendered due to a missing `.Values.clusterOperator.metrics.enabled` and  `.Values.msgTopologyOperator.metrics.enabled` not called out in the default `values.yaml` file.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by andresbono** [comment]
> Yes, I'm happy to make a PR for the project. Which solution would the maintainers prefer?
> 
> * add `metrics.enabled: false` to the 2 sections in values.yaml
> * use the value for `metrics.service.enabled` for the networkpolicy logic

Please, let's stick to the second one: `metrics.service.enabled`. Thank you very much for willing to contribute to the project!
