### ISSUE TITLE
[bitnami/kafka] Expose Kafka on minikube to enable outside connection

### ISSUE THREAD

**Issue by dino-chiio** [bitnami/charts#24238]
### Name and Version

bitnami/kafka:27.0.1 and kafka: 3.7.0; helm version: 3.14.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to create Apache Kafka on Kubernetes using minikube. I run the command with some parameters as follows: 

_`helm install my-release -n kafka-cluster bitnami/kafka --set controller.replicaCount=1 --set broker.replicaCount=0  --set externalAccess.enabled=true --set externalAccess.service.broker.type=LoadBalancer --set externalAccess.service.controller.type=LoadBalancer --set externalAccess.service.broker.port=9094 --set externalAccess.service.controller.containerPorts.external=9094 --set externalAccess.autoDiscovery.enabled=true --set serviceAccount.create=true --set rbac.create=true --set controller.automountServiceAccountToken=true --set broker.automountServiceAccountToken=true --set persistence.enabled=true --set persistence.existingClaim=kafka-pv`_

### What is the expected behavior?

Successfully install Kafka on Kubernetes cluster and clients outside can connect to read and write data

### What do you see instead?

`Back-off restarting failed container auto-discovery in pod my-release-kafka-controller-0_kafka-cluster`

`Error from server (BadRequest): container "kafka" in pod "my-release-kafka-controller-0" is waiting to start: PodInitializing`

**Comment by javsalgar** [comment]
Hi!

If you want to use externalAccess in minikube you may need to enable addons like `metallb`, as minikube does not provide external IPs by default.
