### ISSUE TITLE
[bitnami/external-dns] Allowing for customize dnsPolicy and dnsConfig for external-dns deployment

### ISSUE THREAD

**Issue by chaijunkin** [bitnami/charts#24245]
### Name and Version

bitnami/external-dns 6.36.1

### What is the problem this feature will solve?

external-dns usually called external DNS outside from the cluster, which may caused NXDOMAIN "error" in CoreDNS. This feature allowed users to customize the workload DNS resolution.

### What is the feature you are proposing to solve the problem?

There was no way to set dnsConfig or dnsPolicy for kubernetes workload, thus making it impossible to set custom nameserver and custom nameserver config for the pod.

Similar feature to this PRs [Kafka DNSPolicy and DNSConfig](https://github.com/bitnami/charts/issues/21319) or [kubernetes-sigs/external-dns PR](https://github.com/kubernetes-sigs/external-dns/pull/4265).

I'm planning to contribute.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
