### ISSUE TITLE
[bitnami/kafka] External access via NodePort - Incorrect targetPort

### ISSUE THREAD

**Issue by domderen** [bitnami/charts#2427]
**Which chart**:
bitnami/kafka v10.0.0 app version 2.4.1

**Describe the bug**
I'm running a kafka chart with the following settings:

```
externalAccess.enabled: true
externalAccess.autoDiscovery.enabled: true
externalAccess.service.type: NodePort
```

This creates an Service in Kubernetes called `kafka-0-external` with settings:

```
kind: Service
apiVersion: v1
metadata:
  name: kafka-0-external
  namespace: infra
  selfLink: /api/v1/namespaces/infra/services/kafka-0-external
  uid: a73cf9cb-87af-11ea-87b2-06ba93eb5002
  resourceVersion: '12834415'
  creationTimestamp: '2020-04-26T11:18:28Z'
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-10.0.0
    pod: kafka-0
spec:
  ports:
    - name: tcp-kafka
      protocol: TCP
      port: 9092
      targetPort: 30292
      nodePort: 30292
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
    statefulset.kubernetes.io/pod-name: kafka-0
  clusterIP: 10.100.24.173
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
```

I'm surprised to see that the `targetPort` is set to the same value as the `nodePort`. As far as I understand Kubernetes docs here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#serviceport-v1-core the `targetPort` should be set to the pod's port, which in my case in 9092.

With this configuration I'm not able to connect to any of the kafka nodes. I'm trying with:

```
bin/kafka-topics.sh --list --bootstrap-server <NODE_VPC_INTERNAL_IP>:32705
bin/kafka-topics.sh --list --bootstrap-server <NODE_EXTERNAL_IP>:32705
```

and get this error every time:

```
Error while executing topic command : org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1587902114716) timed out at 1587902114763 after 1 attempt(s)
[2020-04-26 11:55:14,770] ERROR java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1587902114716) timed out at 1587902114763 after 1 attempt(s)
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at kafka.admin.TopicCommand$AdminClientTopicService.getTopics(TopicCommand.scala:333)
	at kafka.admin.TopicCommand$AdminClientTopicService.listTopics(TopicCommand.scala:252)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:66)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1587902114716) timed out at 1587902114763 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
 (kafka.admin.TopicCommand$)
```

As far as I saw, this is happening because of this line: https://github.com/bitnami/charts/blob/8f4744ec76601cadffab1dbce6e6e4755267b166/bitnami/kafka/templates/scripts-configmap.yaml#L57

Is this an expected and correct behaviour?

**To Reproduce**
```
helm install kafka bitnami/kafka --set externalAccess.enabled=true --set externalAccess.autoDiscovery.enabled=true --set externalAccess.service.type=true
```

**Expected behavior**
I expect Kafka service to be accessible via the external node IP & nodePort.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by marcosbc** [comment]
@domderen I would say that is because the external IP address was not properly set, or you are not able to access the specific port due to a firewall configuration.

You can see the IP address that Kafka was configured with by running the commands in the NOTES after deploying the chart (change DEPLOYMENT_NAME and KAFKA_POD with appropriate values):

    Kafka brokers domain: You can get the external node IP from the Kafka configuration file with the following commands (Check the EXTERNAL listener)

        1. Obtain the pod name:

        kubectl get pods --namespace default -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=DEPLOYMENT_NAME,app.kubernetes.io/component=kafka"

        2. Obtain pod configuration:

        kubectl exec -it KAFKA_POD -- cat /opt/bitnami/kafka/config/server.properties | grep advertised.listeners
```

If you do something such as "curl IP_ADDRESS:PORT" and it times out, that is indicating a firewall is blocking the request. You should check if the IP address makes sense, and if you have access to that port in the firewall settings.

**Comment by domderen** [comment]
Hey @marcosbc thank you for your quick response. You are right, it looks like a firewall error on my end. I configured the AWS Security-Group to allow access on those ports, and it worked. What surprised me, is that I wasn't able to use VPC internal IPs to access the cluster, until my Security Group allowed explicit access from a specific IP address inside that VPC on that port. 

Maybe you might have an idea what might be the cause of this... I have an EC2 machine (let's call it `kafka-operator`) in the same VPC as my Kubernetes cluster. I'm trying to access kafka cluster, that is hosted inside my kube cluster, from this machine. 

I configured my Kubernetes Cluster Hosts Security Group to allow access on All protocols and All ports from the security group attached to `kafka-operator` ec2 instance. But with this setting, I was not able to access my kafka cluster, either via internal or external IPs of the Kubernetes cluster hosts.

Only after re-configuring the Kubernetes Cluster Hosts Security Group to allow access to port 32705 (and two other) from the public IP address assigned to my `kafka-operator` ec2 instance, I was able to ping my Kafka cluster.

Do you have any idea what might be the reason for it? I expected the cluster internal ip address to work even without those ports being exposed explicitly for `kafka-operator`'s IP address.

**Comment by marcosbc** [comment]
My understanding is that you would need to access the service via the NodePort, since you enabled that mode.

When you access the public IP via NodePort, the address will not be in the IP route table so it will send it to the default route, and with the public IP address of `kafka-operator`.

**Comment by domderen** [comment]
Hey @marcosbc thanks for checking this one out. I think in the end the problem was AWS related. I think there is some problem in security group access control between machines in public subnets. 

I'll close this issue.

**Comment by GounGG** [comment]
I understand that the nodeport mode is still only accessed on the same intranet machine as kafka, rather than across different intranet segments, using the public network to access.
