### ISSUE TITLE
Adopt Charts to be inflated with `helm template` instead of helm install for ArgoCD GitOps to get reliable outcome. 

### ISSUE THREAD

**Issue by qdrddr** [bitnami/charts#24306]
### Name and Version

bitnami/all

### What is the problem this feature will solve?

Some of the bitnami charts rely on the `helm install`. At the same time, GitOps tools like [ArgoCD deliberately do not use the helm install approach; instead, they inflate charts with the helm template](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/). This keeps Argo CD neutral to all manifest generators while simultaneously having bitnami charts potentially being deployed incorrectly with ArgoCD.

### What is the feature you are proposing to solve the problem?

ArgoCD is a popular GitOps tool. GitOps is a reliable and reproducible approach to deploying resources into k8s adopted by more and more people, providing easier application maintenance and support. Please consider bitnami charts to check the `helm template` inflate charts with expected outcomes. Please do not rely on `helm install` to be used neutrally to all manifest generators, replicated, and in a GitOps-friendly manner. 

### What alternatives have you considered?

The current workaround is to use kustomization to fix the issues.

**Comment by carrodher** [comment]
Thanks for the detailed information, could you please provide more information about the exact issues you're facing using a specific Helm chart as an example?

Bitnami charts have some logic in the _NOTES.txt_ that’s not compatible with `helm templates`, for instance, to check existing secrets for credentials. But AFAIK it’s ignored when using `helm` only to generate manifests.
