### ISSUE TITLE
[bitnami/external-dns] secret management enhancement?

### ISSUE THREAD

**Issue by cyrilcros** [bitnami/charts#2430]
**Which chart**:
External-dns version: 2.21.2 appVersion: 0.7.1.

**Is your feature request related to a problem? Please describe.**
There are many DNS providers in the chart with different ways to secure credentials (env var, secret file, string in values.yaml). I don't want to add credentials from the `values.yaml` into version controls.

**Describe the solution you'd like**
The templates in the chart already create a Kubernetes Secret for credentials, I would rather be able to provide my own secret as a `values.yaml` option in a format following your template.
You can even skip validation of this Secret in your code, by telling users to first generate a helm manifest with their unencrypted credentials, extract the generated Secret, and then rerun the Chart with the Secret passed as a value. 

**Describe alternatives you've considered**
You can also use Helm template and then manually extract the generated Secret, but I would rather do that once rather than every time the Chart changes.

**Comment by miguelaeh** [comment]
Hi @cyrilcros ,
To avoid write your credentials in the values.yaml you can pass them ussing `--set` parameter to the helm install command.
Also, the chart supports the use of an existing secret, you just have to create your own secret and put it, for example, at the `aws.secretName` in the case of AWS. https://github.com/bitnami/charts/blob/8f4744ec76601cadffab1dbce6e6e4755267b166/bitnami/external-dns/values.yaml#L83

**Comment by cyrilcros** [comment]
Well, AWS/ Azure / Cloudflare/ GCP already support this type of feature. I am asking whether ALL the other providers could use something like this for their own secrets.

You hint it is possible, but I am not sure how.  In the templates, this doesn't look like this is always applied. What secret should I use for PowerDNS for example?

All providers have a `set via arguments/env. variables` comment, only some have a `secretName` value available. 

There are also some discrepancies between the Cloudflare values file (see [code](https://github.com/bitnami/charts/blob/8f4744ec76601cadffab1dbce6e6e4755267b166/bitnami/external-dns/values.yaml#L152)  with commented values), the Read.me values where it is not mentioned, and the template files where it is used [here](https://github.com/bitnami/charts/blob/8f4744ec76601cadffab1dbce6e6e4755267b166/bitnami/external-dns/templates/_helpers.tpl#L123).

**Comment by miguelaeh** [comment]
Hi @cyrilcros ,
Now I got your point, that PR implements the `secretName` feature for PowerDNS too.

**Comment by cyrilcros** [comment]
@miguelaeh kindly submitted a PR, will close if/when merged.

**Comment by miguelaeh** [comment]
Hi @cyrilcros ,
Sorry for the late we missed the notification, I already pinge another member of the team to review the PR.
Regards.
