### ISSUE TITLE
we need new keycloak tag of  version( 24.0.1)

### ISSUE THREAD

**Issue by Scumwong** [bitnami/charts#24321]
### Name and Version

keycloak

### What architecture are you using?

None

### What steps will reproduce the bug?

we need a new keycloak tag of version (24.0.1)

### What do you see instead?

bitnami/keycloak:24.0.1

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible. 

There is an already existing issue for this topic in the containers repository, see https://github.com/bitnami/containers/issues/63545. We will provide updates on that thread as soon as the new version is successfully released.
