### ISSUE TITLE
[bitnami/influxdb] resources, aws cli cache and service account for the backup part in the helm chart

### ISSUE THREAD

**Issue by jeb1jeb2** [bitnami/charts#24324]
### Name and Version

bitnami/influxdb 5.18.1

### What is the problem this feature will solve?

In the backup part of the helm chart, there are multiple Problems when deploying to a restricted OpenShift namespace.

1. You do not have the possibility to set resources in any of the backup containers.
1. Also the aws cli needs an `.aws` folder as its cache.
1. The last Problem is the service account. It is currently not possible to use an other service Account than the default for the name space.

### What is the feature you are proposing to solve the problem?

1. Set up a resources in the chronjob-backup.yaml that are configurable in the values.yaml
2. Add an other empty dir sub-dir for the `.aws` cache
3. Add the influx service account to the backup if it is created or setup a backup service account

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I see that you are creating a fork adding the feature. Is that the case? We would really appreciate your contribution :D

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
