### ISSUE TITLE
Upgrade redis to 5.0.9

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [bitnami/charts#2434]
**Which chart**:
redis 10.6.10

**Describe the solution you'd like**
There is a new redis release 5.0.9 which includes some important performance improvements (https://github.com/antirez/redis/issues/7071), it'd be great if we could get the chart updated to support it.

Based on:

https://github.com/bitnami/charts/blob/8f4744ec76601cadffab1dbce6e6e4755267b166/bitnami/redis/Chart.yaml#L4

It looks like the current redis version supported by the chart is 5.0.8.

Though it also looks like this may also require an updated redis build in [`bitnami/bitnami-docker-redis`](https://github.com/bitnami/bitnami-docker-redis).

**Comment by beltran-rubo** [comment]
Wow nice performance improvement, thanks for letting us know. Redis 5.0.9 has not been officially released yet https://redis.io/download but we will make sure that once it is released the Helm Chart is updated as soon as possible.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
The tag as well as the packaged binary (`http://download.redis.io/releases/redis-5.0.9.tar.gz`) are already available, so my guess is that this is an oversight.

See also: https://github.com/antirez/redis/issues/7115.

**Comment by carrodher** [comment]
Hi, we are going to change the tracking point from https://redis.io/download to http://download.redis.io/releases/. Then our system should automatically trigger the new release for this version and avoid this kind of issue in the future.

**Comment by carrodher** [comment]
Hi, everything worked as expected and the bitnami/redis chart using the new Redis version (`5.0.9`) was tested and released.

[This is the commit](https://github.com/bitnami/charts/commit/00efc573d9c4cbf2839b8fecce7d87a14616cecb) updating the version and the container images. In the same way you can find this new version of the bitnami/redis chart in the charts repository: 

```
▶ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈

▶ helm search repo bitnami/redis
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/redis        	10.6.11      	5.0.9      	Open source, advanced key-value store. It is of...
bitnami/redis-cluster	2.0.10       	5.0.9      	Open source, advanced key-value store. It is of...
```

Thanks again for reporting the issue and, please, don't hesitate to reopen the issue if something doesn't work as expected.
