### ISSUE TITLE
[Magento] allow setting 'StrategyType'

### ISSUE THREAD

**Issue by stijnbrouwers** [bitnami/charts#2435]
**Which chart**:
Magento

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to set the strategy type for my chart to 'Recreate'. 

**Additional context**
I am using Azure Disk for persistent storage and using 'RollingUpdate' sometimes keeps the pod in pending state because it schedules the new pod on a new VM which fails on mounting the disk due that it's already mounted to another VM.

**Comment by carrodher** [comment]
Thanks for adding this new feature, we are going to review the PR and test it in our internal CI/CD pipeline
