### ISSUE TITLE
Redis  - Sentinel unable to finish a failover

### ISSUE THREAD

**Issue by albertocsm** [bitnami/charts#2436]
**Which chart**:
Redis

**Describe the bug**
https://github.com/bitnami/charts/issues/1682#issuecomment-618965902

**To Reproduce**
see https://github.com/bitnami/charts/issues/1682#issuecomment-618965902

**Expected behavior**
see https://github.com/bitnami/charts/issues/1682#issuecomment-618965902

**Version of Helm and Kubernetes**:
1.15

- Output of `helm version`:
3.2.0
```
(paste your output here)
```

- Output of `kubectl version`:
1.18
```

**Comment by albertocsm** [comment]
not sure i follow @miguelaeh 
are you referring to `sentinel failover-timeout`? i currently have 15s for that configuration.

im prolly missing something basic here but eventually, after some tries where everything goes fine, i eventually get into a state where the fail-over process never completes with success. it keeps retrying forever with no success.

next, an example where i got the `failover-abort-no-good-slave` error. im not sure why.
ie.:
```
slv1 (8e200acecaa7f766b4dbb69a1dd69ba5d965ab7b)
1:X 24 Apr 2020 16:28:16.235 # +new-epoch 50
1:X 24 Apr 2020 16:28:16.235 # +try-failover master redis 10.145.159.156 6379
1:X 24 Apr 2020 16:28:16.236 # +vote-for-leader 8e200acecaa7f766b4dbb69a1dd69ba5d965ab7b 50
1:X 24 Apr 2020 16:28:16.239 # 365bdb267e550a2d9ad330663f4d42ba88d037fa voted for 8e200acecaa7f766b4dbb69a1dd69ba5d965ab7b 50
1:X 24 Apr 2020 16:28:16.239 # d256623d2f8ab42a3105022724536edff6060b03 voted for 8e200acecaa7f766b4dbb69a1dd69ba5d965ab7b 50
1:X 24 Apr 2020 16:28:16.288 # +elected-leader master redis 10.145.159.156 6379
1:X 24 Apr 2020 16:28:16.288 # +failover-state-select-slave master redis 10.145.159.156 6379
1:X 24 Apr 2020 16:28:16.346 # -failover-abort-no-good-slave master redis 10.145.159.156 6379
1:X 24 Apr 2020 16:28:16.422 # Next failover delay: I will not start a failover before Fri Apr 24 16:28:47 2020


slv0 (d256623d2f8ab42a3105022724536edff6060b03)
1:X 24 Apr 2020 16:28:16.238 # +new-epoch 50
1:X 24 Apr 2020 16:28:16.239 # +vote-for-leader 8e200acecaa7f766b4dbb69a1dd69ba5d965ab7b 50
1:X 24 Apr 2020 16:28:16.737 # +odown master redis 10.145.159.156 6379 #quorum 2/2
1:X 24 Apr 2020 16:28:16.737 # Next failover delay: I will not start a failover before Fri Apr 24 16:28:47 2020


m0 (365bdb267e550a2d9ad330663f4d42ba88d037fa)
1:X 24 Apr 2020 16:28:16.238 # +new-epoch 50
1:X 24 Apr 2020 16:28:16.239 # +vote-for-leader 8e200acecaa7f766b4dbb69a1dd69ba5d965ab7b 50
1:X 24 Apr 2020 16:28:16.840 # +odown master redis 10.145.159.156 6379 #quorum 2/2
1:X 24 Apr 2020 16:28:16.840 # Next failover delay: I will not start a failover before Fri Apr 24 16:28:46 2020
```

**Comment by dani8art** [comment]
Hi @albertocsm , It seems to be a problem related to the wrong exit of the master pod from the cluster. We should try to find a way where master pod graceful exits from the cluster, maybe we could try a preStop hook or sth as we are trying [here](https://github.com/bitnami/charts/pull/2406) for another similar error. Would you suggest any way to do it better for redis?

**Comment by albertocsm** [comment]
im inclined to think a preStop life-cycle event would not be effective for 100% of the situations.
```
Kubernetes sends the preStop event immediately before the Container is terminated. Kubernetes’ management of the Container blocks until the preStop handler completes, unless the Pod’s grace period expires.
```
https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#discussion

what is the "action" that a Redis+Sentinel pod receiving an abrupt SIGTERM would not do and cause the issue?

**Comment by albertocsm** [comment]
im experimenting with a custom Redis setup that relies on both static ServiceIPs and SetinelIDs.  with this setup, until this moment, i was not able to reproduce the problem of getting into a "failover deadlock".

what leads you to believe that the issue i raised is caused by a `wrong exit of the master pod` @dani8art ?

**Comment by javsalgar** [comment]
Hi,

If this setup works, it may be worth adding it as a feature in the chart. In our redis-cluster solution we allow static LoadBalancer ips for example, so it may make sense to allow static IPs and IDs.

**Comment by gopal229** [comment]
It will be great if it's supported by the Redis chart itself. Today when we upgrade the chart the IP addresses of the PODs gets updated and that is causing our client ( java lettuce client ) application to fail as it is expecting the master/slave IP's to be fixed. Ref: https://github.com/lettuce-io/lettuce-core/issues/1147

**Comment by dani8art** [comment]
Hi, 

As @javsalgar it may be worth adding it as a feature in the chart so we have opened an internal task to evaluate and handle it, unfortunately, we are not able to give you an ETA. However, we are open to community contributions and PR, if you guys have a chance and you think can open a PR with the approach that you suggested, we would be happy to discuss and handle it. 

Thank you so much for your feedback.

**Comment by albertocsm** [comment]
👍

**Comment by alexgaganashvili** [comment]
I'm having the same problem as described by @albertocsm. I eventually have to intervene and restart the pods.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
