### ISSUE TITLE
[bitnami/airflow] Access Airflow Web UI using a context path

### ISSUE THREAD

**Issue by cjay2067** [bitnami/charts#24382]
### Name and Version

bitnami/airflow

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have installed the bitnami airflow helm chart in AWS EKS, here I cannot access the Airflow Web UI by using a context path, I was able to access the UI by doing port fording. 
Then I reinstalled the chart by changing baseUrl to `baseUrl: "/airflow"`, here my web service, scheduler, and worker pods were not up due to a db connectivity error. 
Do we have a proper way to handle this?  

### Are you using any custom parameters or values?

 `baseUrl: "/airflow"`

### What is the expected behavior?

accessing the Airflow web UI using a context path

### What do you see instead?

I'm getting webserver not found error

**Comment by carrodher** [comment]
Could you please share with us the error logs? In the same way, setting `web.image.debug` to true will add more verbosity to the initialization logs

**Comment by cjay2067** [comment]
Hi @carrodher , here I attached the output of kubectl describe pod (web-server pod) for your reference. Please assist me to resolve this issue. 
Thanks. 
[pod_description.txt](https://github.com/bitnami/charts/files/14651216/pod_description.txt)

**Comment by javsalgar** [comment]
Hi,

We would need the output of `kubectl logs` to better understand the issue.
