### ISSUE TITLE
[bitnami/keycloak] External RDS connection with multiple hosts instead of one

### ISSUE THREAD

**Issue by mh013370** [bitnami/charts#24392]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Postgres can be deployed in an HA (multi-host) fashion, but the chart only allows for a single host to be configured. Can it be possible to supply our own connection string alternatively to all of the current static settings here: https://github.com/bitnami/containers/blob/9f6278e4abadcf4ff63eb42310739646e1ed1485/bitnami/keycloak/22/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L146

### What is the feature you are proposing to solve the problem?

We have a postgres deployed in an HA fashion where one is primary and others are standby read-only. We can only configure one host in the chart, so we can't take advantage of the HA deployment.

### What alternatives have you considered?

I can't find a way to configure multiple hosts, but would be happy to be shown how!

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
