### ISSUE TITLE
[bitnami/grafana-operator] New release is broken (new CRDs)

### ISSUE THREAD

**Issue by rivoalrivoal** [bitnami/charts#24406]
### Name and Version

bitnami/grafana-operator 3.12.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install the chart grafana-operator with default value

### What do you see instead?

Error when grafana-operator pod starting : 
```
2024-03-13T19:44:14Z	ERROR	controller-runtime.source.EventHandler	if kind is a CRD, it should be installed before calling Start	{"kind": "GrafanaAlertRuleGroup.grafana.integreatly.org", "error": "no matches for kind \"GrafanaAlertRuleGroup\" in version \"grafana.integreatly.org/v1beta1\""}
```

### Additional information

There are a new CRDs
https://github.com/grafana/grafana-operator/blob/master/deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanaalertrulegroups.yaml

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by rivoalrivoal** [comment]
Fixed with https://github.com/bitnami/charts/pull/24400
