### ISSUE TITLE
[bitnami/nats] enable system_account

### ISSUE THREAD

**Issue by ro0NL** [bitnami/charts#24443]
### Name and Version

bitnami/nats 7.18

### What is the problem this feature will solve?

Nats has the concept of a system account: https://docs.nats.io/running-a-nats-service/configuration/sys_accounts#local-configuration

AFAIK we cannot make use of it when using bitnami charts, unless we override the full config, which defeats the chart ;)

This currently blocks monitoring:

```console
$ nats server report jetstream
nats: error: server request failed, ensure the account used has system privileges and appropriate permissions
```

### What is the feature you are proposing to solve the problem?

Allow specifying a system account

**Comment by FraPazGal** [comment]
Hello @ro0NL, I agree adding account's support would be a nice feature so no cons on my side. Checking our current chart's config, we'll need to add a couple of new account-related parameters and update the `configuration` one.

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by ro0NL** [comment]
Sorry, i dont have real time for that :)

It's not a real blocker for us currently, but would be nice-to-have.

**Comment by kmsunitrends** [comment]
This was marked as completed, but I can't find a chart parameter that provides this functionality.

Could some provide an example or point me in the right direction? I may have overlooked it!

**Comment by ro0NL** [comment]
use official chart, be done
