### ISSUE TITLE
[bitnami/influxdb] no imagePullSecrets in backup cronjob

### ISSUE THREAD

**Issue by jeb1jeb2** [bitnami/charts#24449]
### Name and Version

bitnami/influxdb 6.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Using OpenShift
2. Having a private docker repository for the influx-image
3. Set the right imagePullSecrets in the global section

### What is the expected behavior?

The CronJob should be able to pull the influx image as the main container can.

### What do you see instead?

The Main Container can use the imagePullSecrets set in global of the values.yaml. The backup CronJob can't, because there are no imagePullSecrets

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
