### ISSUE TITLE
[bitnami/external-dns] Add support for OCI IAM Instance Principall and OCI IAM Workload Identity

### ISSUE THREAD

**Issue by cloudoutloud** [bitnami/charts#24459]
### Name and Version

bitnami/external-dns 6.37.0

### What is the problem this feature will solve?

The Oracle provider for external DNS supports alternative authentication methods.

https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/oracle.md#oci-iam-instance-principal
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/oracle.md#oci-iam-workload-identity

These don't require creating an OCI user with a long-lived key and secret.

It seems this chart does not support these methods as it always tries to create a secret and mount. https://github.com/bitnami/charts/blob/main/bitnami/external-dns/templates/dep-ds.yaml#L836
https://github.com/bitnami/charts/blob/main/bitnami/external-dns/templates/dep-ds.yaml#L769

it was also reported in this https://github.com/bitnami/charts/pull/9334

### What is the feature you are proposing to solve the problem?

Update https://github.com/bitnami/charts/blob/main/bitnami/external-dns/templates/dep-ds.yaml#L769 to include else statements to skip if alternative authentication methods are used.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by cloudoutloud** [comment]
Started to work on this https://github.com/bitnami/charts/pull/24708

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
