### ISSUE TITLE
Wordpress: wrong example for securityContext -> runAsUser and fsGroup

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [bitnami/charts#2446]
**Which chart**:
[`wordpress` v5.4.0, chart v9.2.0](https://hub.helm.sh/charts/bitnami/wordpress)

**Describe the bug**
At the [page of the helm chart](https://hub.helm.sh/charts/bitnami/wordpress), down to the section "Upgrading", in the notes for 9.0.0, there is a paragraph:

> The Bitnami WordPress image was migrated to a "non-root" user approach. Previously the container ran as the root user and the Apache daemon was started as the daemon user. From now on, both the container and the Apache daemon run as user 1001. **You can revert this behavior by setting the parameters `securityContext.runAsUser`, and `securityContext.fsGroup` to `root`.** Chart labels and Ingress configuration were also adapted to follow the Helm charts best practices.

I marked the point of interest in **bold**. The fields `securityContext.runAsUser` and `securityContext.fsGroup` are in fact integers, and `root` should be `0`.

**To Reproduce**

1. Release a helm chart with `values: {securityContext: { fsGroup: 0, runAsUser: 0}}`
2. We have a Flux CI/CD operator for helm so let's open its logs :b
3. See this error:

*A readable version:*

* `invalid type for io.k8s.api.core.v1.PodSecurityContext.fsGroup: got "string", expected "integer"`;
* `invalid type for io.k8s.api.core.v1.PodSecurityContext.runAsUser: got "string", expected "integer"`.

*Full error message:*

`ts=2020-04-27T22:10:07.830988596Z caller=release.go:186 component=release release=kammiac-site targetNamespace=kammiac-site resource=kammiac-site:helmrelease/kammiac-site helmVersion=v3 error="failed to determine if the release should be synced" err="failed to upgrade chart for release [kammiac-site]: error validating \"\": error validating data: [ValidationError(Deployment.spec.template.spec.securityContext.fsGroup): invalid type for io.k8s.api.core.v1.PodSecurityContext.fsGroup: got \"string\", expected \"integer\", ValidationError(Deployment.spec.template.spec.securityContext.runAsUser): invalid type for io.k8s.api.core.v1.PodSecurityContext.runAsUser: got \"string\", expected \"integer\"]"`

**Expected behavior**
Either the docs should be fixed, or the chart should support human-readable usernames for PodSecurityContext settings.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @CosmoMyzrailGorynych ,
The security context expects an integer, set it to `root` means set it to the UID `0` that is the `root` UID. In any case, please feel free to send a PR updating the `README.md` if you think it is confusing.

**Comment by CosmoMyzrailGorynych** [comment]
FYI Helm is a high-level abstraction that should not require intricate knowledge of Kubernetes or Linux. "Set it to `root` means to set it to `0`" is called mind-reading.
