### ISSUE TITLE
[bitnami/spring-cloud-dataflow] externalRabbit requires `rabbit.auth` to be entered

### ISSUE THREAD

**Issue by dmfrey** [bitnami/charts#24475]
### Name and Version

bitnami/spring-cloud-dataflow 26.11.0

### What is the problem this feature will solve?

When External Rabbit is configured and `rabbit.enabled: false`, you are still required to enter:
```
rabbit:
    auth:
        password:
        erlangCookie:
```

Both of these items are available in secrets. The Rabbit Operator, when provisioning a rabbit instance, will create separate secrets containing connection information with user and password, as well as a separate secret containing the erlangCookie. It would be helpful to be able load these from secrets much like the external database can be configured from an external secret.

### What is the feature you are proposing to solve the problem?

Provide consistency across external configuration for externally provisioned services.

### What alternatives have you considered?

Override environment variables. Hardcode values in values.yaml.

**Comment by juan131** [comment]
Thanks for this feature request! It's been implemented and the new `26.12.0` chart version will include it.
