### ISSUE TITLE
[bitnami/keycloak] Keycloak helm chart uses incompatible keycloak-config-cli

### ISSUE THREAD

**Issue by joaocc** [bitnami/charts#24480]
### Name and Version

bitnami/keycloak 19.3.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy helm chart

### What do you see instead?
```
2024-03-15 13:45:37.867  WARN 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Local keycloak-config-cli (5.11.1-24.0.1) and remote Keycloak (23.0.7) may not compatible.
2024-03-15 13:45:38.114 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Cannot create realm 'client-0': HTTP 500 Internal Server Error{"error":"unknown_error"}
2024-03-15 13:45:38.115  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:01.386.
```

### Additional information

In standard keycloak images, keycloak-config-cli allows specifying tag that includes a reference to a compatible keycloak version.
In the case of bitnami/keycloak helm chart v19.3.3, it is using `bitnami/keycloak` docker `v23.0.7-debian-12-r3`, while `bitnami/keycloak-config-cli`  v5.11.1-debian-12-r0, which seems to be compatible with keycloak v24+

**Comment by Selveris** [comment]
I've got the same issue too, managed to resolve it by downgrading keycloak-config-cli to version 5.10.0

Would be great if there was a table in the README showing the compatibility between the config-cli and keycloak versions

**Comment by joaocc** [comment]
in the upstream docker images (non-bitnami) they have a set of tags equivalent to "latest compatible with keycloak version x.y.z" which is well thought out, but requires a way of tagging things which doesn't match bitnami common scheme.

**Comment by tanadeau** [comment]
This is still an issue.

**Comment by joaocc** [comment]
Hi. Any updates on this? Thx

**Comment by joaocc** [comment]
Would like to keep this open, as this issue is bound to affect future releases where versions for keycloak and keycloak-cli are not compatible at some point in time

**Comment by juan131** [comment]
Hi everyone,

We have automations in place that update the containers and the chart with the latest releases from branch `5.x` for keycloak-config-cli (tracking https://github.com/adorsys/keycloak-config-cli/releases) and branch `24.x` for keycloak (tracking https://github.com/keycloak/keycloak/releases).

This automation is currently incapable of detecting incompatibilities, so please we encourage you to report any issue you may find.

**Comment by joaocc** [comment]
Not sure if that is enough, as the error message seems at collision with the changelog statement (23.0.7 and 5.11.x).
If this is an one off case where they are removing compat, maybe it's enough upgrading the versions.

[5.11.0](https://github.com/adorsys/keycloak-config-cli/compare/v5.10.0...v5.11.0) - 2024-03-12
* Updated CI to use Keycloak 24.0.1
* Updated CI to use Keycloak 23.0.7
* Changed briefRepresentation from false to true (mistakenly considered full: https://github.com/keycloak/keycloak/issues/25096)
  * Removes compatibility of Versions 23.0.0, 23.0.1, 23.0.2 and 23.0.3
* Using getGroupByPath again after being fixed (https://github.com/keycloak/keycloak/issues/25111)
