### ISSUE TITLE
[bitnami/keycloak] is external infinispan cache configuration supported?

### ISSUE THREAD

**Issue by jwklijnsma** [bitnami/charts#24495]
### Name and Version

bitnamie/keycloak

### What is the problem this feature will solve?

We are looking to externalize the infinispan cache. Is there any preconfigured hooks for doing this with Bitnami/keycloak?

### What is the feature you are proposing to solve the problem?

making an initial inquiry only

### What alternatives have you considered?

none yet

**Comment by jwklijnsma** [comment]
i will like to add this helmchart we have it working for version 23

**Comment by carrodher** [comment]
You can take a look at https://github.com/bitnami/charts/tree/main/bitnami/keycloak#keycloak-cache-parameters and https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L1275

**Comment by jwklijnsma** [comment]
> You can take a look at https://github.com/bitnami/charts/tree/main/bitnami/keycloak#keycloak-cache-parameters and https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L1275

we have already like the with extravalue but it will be nice to have in main chart
