### ISSUE TITLE
The script with empty input

### ISSUE THREAD

**Issue by MR-Os1** [bitnami/charts#24519]
### Name and Version

bitnami/kibana 20.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. create a Elasticsearch with Kibana enabled and enable all of SSL and security passwords.
2. update configuration for adding ingress for kibana.

### What do you see instead?

 the initContainer "copy-default-plugins" in kibana is having a problem with: /opt/bitnami/scripts/libfs.sh: line 61: 1: missing directory.

### Additional information

idk but it's either something with `$SERVER_DEFAULT_PLUGINS_DIR` variable that has no value or the script that is used (libfs.sh)
should have default folders if it needs to run without params
https://github.com/bitnami/charts/blob/cdc06795ba3b1e1b9a9899e9aefb8085c9bbd662/bitnami/kibana/templates/deployment.yaml#L100-L127

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by MR-Os1** [comment]
@carrodher
Thanks for responding.
I found out the version of kibana.image has a release which fixed my issue

**Comment by carrodher** [comment]
I'm glad to hear that!
