### ISSUE TITLE
[bitnami/thanos] thanos distributor pods goes in crashloopback state. 

### ISSUE THREAD

**Issue by sakeebshaikh74** [bitnami/charts#24513]
### Name and Version

thanos /13.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Steps to reproduce.
Installed the helm chart with receive in dual-mode
Added the following endpoint in prometheus.
```yaml
remoteWrite:
    - url: http://thanos-receive:19291/api/v1/receive
```
in standalone mode, i see the receive is up in querier

![image](https://github.com/bitnami/charts/assets/163878399/91af11d1-bba7-4479-af5a-2ae71e326723)

but in dual mode

pods are crashloopback and 

![image](https://github.com/bitnami/charts/assets/163878399/7c3e5d9e-8fa9-4ed9-a9ff-c98e0b096469)

nothing in the distrubitor logs
```console
$ k logs thanos-receive-distributor-74cd546d77-8sskb -n observability
ts=2024-03-18T15:03:17.817194671Z caller=receive.go:136 level=info component=receive mode=RouterOnly msg="running receive"
ts=2024-03-18T15:03:17.817235415Z caller=options.go:26 level=info component=receive protocol=HTTP msg="disabled TLS, key and cert must be set to enable"
ts=2024-03-18T15:03:17.817300467Z caller=receive.go:743 level=info component=receive msg="no existing storage found, no data migration attempted"
ts=2024-03-18T15:03:17.817639243Z caller=options.go:26 level=info component=receive protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
ts=2024-03-18T15:03:17.817984673Z caller=receive.go:446 level=info component=receive msg="starting receiver"
ts=2024-03-18T15:03:17.818053177Z caller=intrumentation.go:75 level=info component=receive msg="changing probe status" status=healthy
ts=2024-03-18T15:03:17.818049743Z caller=handler.go:376 level=info component=receive component=receive-handler msg="Start listening for connections" address=0.0.0.0:19291
ts=2024-03-18T15:03:17.818081424Z caller=http.go:73 level=info component=receive service=http/server component=receive msg="listening for requests and metrics" address=0.0.0.0:10902
ts=2024-03-18T15:03:17.818175048Z caller=receive.go:373 level=info component=receive msg="listening for StoreAPI and WritableStoreAPI gRPC" address=0.0.0.0:10901
ts=2024-03-18T15:03:17.818203649Z caller=intrumentation.go:75 level=info component=receive msg="changing probe status" status=healthy
ts=2024-03-18T15:03:17.818202586Z caller=receive.go:537 level=info component=receive msg="Set up hashring for the given hashring config."
ts=2024-03-18T15:03:17.818217607Z caller=intrumentation.go:56 level=info component=receive msg="changing probe status" status=ready
ts=2024-03-18T15:03:17.818262614Z caller=handler.go:403 level=info component=receive component=receive-handler msg="Serving plain HTTP" address=0.0.0.0:19291
ts=2024-03-18T15:03:17.818265692Z caller=grpc.go:131 level=info component=receive service=gRPC/server component=receive msg="listening for serving gRPC" address=0.0.0.0:10901
ts=2024-03-18T15:03:17.818287432Z caller=tls_config.go:274 level=info component=receive service=http/server component=receive msg="Listening on" address=[::]:10902
ts=2024-03-18T15:03:17.818316731Z caller=tls_config.go:277 level=info component=receive service=http/server component=receive msg="TLS is disabled." http2=false address=[::]:10902
```

### Are you using any custom parameters or values?

no

### What is the expected behavior?

the distributor should work fine and the receiver should write data to the storegateway

### What do you see instead?

I see the errors in p8s
```
ts=2024-03-18T15:02:48.266Z caller=dedupe.go:112 component=remote level=warn remote_name=9c8e3b url=http://thanos-receive:19291/api/v1/receive msg="Failed to send batch, retrying" err="Post \"http://thanos-receive:19291/api/v1/receive\": dial tcp 10.100.239.216:19291: connect: connection refused"
ts=2024-03-18T15:03:22.377Z caller=dedupe.go:112 component=remote level=warn remote_name=9c8e3b url=http://thanos-receive:19291/api/v1/receive msg="Failed to send batch, retrying" err="Post \"http://thanos-receive:19291/api/v1/receive\": EOF"
ts=2024-03-18T15:03:52.388Z caller=dedupe.go:112 component=remote level=warn remote_name=9c8e3b url=http://thanos-receive:19291/api/v1/receive msg="Failed to send batch, retrying" err="Post \"http://thanos-receive:19291/api/v1/receive\": dial tcp 10.100.239.216:19291: connect: connection refused"
ts=2024-03-18T15:04:53.977Z caller=dedupe.go:112 component=remote level=warn remote_name=9c8e3b url=http://thanos-receive:19291/api/v1/receive msg="Failed to send batch, retrying" err="Post \"http://thanos-receive:19291/api/v1/receive\": dial tcp 10.100.239.216:19291: connect: connection refused"
ts=2024-03-18T15:05:05.913Z caller=dedupe.go:112 component=remote level=warn remote_name=9c8e3b url=http://thanos-receive:19291/api/v1/receive msg="Failed to send batch, retrying" err="Post \"http://thanos-receive:19291/api/v1/receive\": EOF"
```

**Comment by sakeebshaikh74** [comment]
we enabled the headless service for the receive component and added the endpoints
config:
<     - endpoints:
<         - "thanos-receive-0.thanos-receive-headless.observability.svc.cluster.local:10901"
<         - "thanos-receive-1.thanos-receive-headless.observability.svc.cluster.local:10901"

is this correct to create the hashring configuration or do we have some standard solution to create the hashring configuration

**Comment by sakeebshaikh74** [comment]
If this configuration was missing why is there no error in the receive or distributor component to identify the issue

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
