### ISSUE TITLE
[bitnami/oauth2-proxy] subchart redis.replica.replicaCount isn't working 

### ISSUE THREAD

**Issue by qdrddr** [bitnami/charts#24520]
### Name and Version

bitnami/oauth2-proxy

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When setting values `redis.replica.replicaCount` it doesn't have any effect: only master created and no replicas created.

`helm install oauth2-proxy oci://registry-1.docker.io/bitnamicharts/oauth2-proxy -f oauth2-proxy.bitmani.values.yaml`

### Are you using any custom parameters or values?

values.yaml file content
```yaml
redis:
  enabled: true
  architecture: standalone
  replica:
    replicaCount: 3
```

### What is the expected behavior?

Redis replica pods should be created

### What do you see instead?

Redis subchart creates master, but no replica pods are created in k8s.

### Additional information

CHART VERSION: 4.10.3
K8s: v1.27.10

**Comment by javsalgar** [comment]
Hi,

Could you set `redis.architecture=replication`? This should fix the issue

**Comment by qdrddr** [comment]
Thanks, it worked, @javsalgar!

**Comment by qdrddr** [comment]
redis.architecture=replication
