### ISSUE TITLE
Wrong selector in Networkpolicy for Argo Workflows 

### ISSUE THREAD

**Issue by SammyA** [bitnami/charts#24534]
### Name and Version

bitnami/argo-workflows-7.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Install chart v7.0.0

### What is the expected behavior?

NetworkPolicies should restrict ingress to certain ports, and allow all egress.

### What do you see instead?

When there are no other matching networkpolicies, all ingress (and egress) is allowed. If there are other matching networkpolicies, argo-worklflows breaks, unless ingress and egress required to function is also allowed by these other policies.

### Additional information

The networkpolicies select pods using a label that does not exist on the pods:

https://github.com/bitnami/charts/blob/8f8b3417e80625ad588f9991326de408036b7399/bitnami/argo-workflows/templates/controller/networkpolicy.yaml#L24

https://github.com/bitnami/charts/blob/8f8b3417e80625ad588f9991326de408036b7399/bitnami/argo-workflows/templates/server/networkpolicy.yaml#L24

Therefore these policies have no effect.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
