### ISSUE TITLE
[bitnami/schema-registry] Change default file mode to 0600 so that container crash can be recovered

### ISSUE THREAD

**Issue by hertfelder** [bitnami/charts#24545]
### Name and Version

bitnami/schema-registry 17.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When connecting to Kafka via SASL_SSL, `schema-registry.truststore.jks` and `schema-registry-X.keystore.jks` are copied to `/opt/bitnami/schema-registry/certs` from `/certs` (which is a projected volume, the jks are pulled in from secrets) when the container starts. Due to [this line](https://github.com/bitnami/charts/blob/9ee0e0505c76b6b82d389792abce0a6951210ba0/bitnami/schema-registry/templates/statefulset.yaml#L293), the files are created with mode `0400`. If the container crashes (not the Pod!), any subsequent restart will fail with
> cp: cannot create regular file '/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks': Permission denied

since the file is not writable by the owner.

### What is the expected behavior?

Crash of the container should be recoverable. Why not set the `defaultMode` to `0600`?

### What do you see instead?

> cp: cannot create regular file '/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks': Permission denied

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Would you like to submit a PR setting that `defaultMode`?
