### ISSUE TITLE
[bitnami/airflow] nil pointer evaluating interface {}.global

### ISSUE THREAD

**Issue by kmdlcp** [bitnami/charts#24568]
### Name and Version

bitnami/airflow 17.2.4

### What architecture are you using?

None

### What steps will reproduce the bug?

Installing the chart with following values:

```yaml
dags:
  existingConfigmap: "dags"
```

### What is the expected behavior?

Airflow being installed without errors

### What do you see instead?
```
Error: template: airflow/templates/worker/statefulset.yaml:110:12: executing "airflow/templates/worker/statefulset.yaml" at <include "airflow.loadDAGsInitContainer" (dict "component" "worker" "context" .)>: error calling include: template: airflow/templates/_helpers.tpl:207:23: executing "airflow.loadDAGsInitContainer" at <include "common.compatibility.renderSecurityContext" (dict "secContext" $compDefinition.containerSecurityContext "context" $)>: error calling include: template: airflow/charts/common/templates/_compatibility.tpl:26:15: executing "common.compatibility.renderSecurityContext" at <.context.Values.global.compatibility>: nil pointer evaluating interface {}.global
```
### Additional information
This seems to be similar to issue #24283, with the same problem, just in a different part of the helm chart.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
