### ISSUE TITLE
Bug: Nginx server block causing the charts to fail

### ISSUE THREAD

**Issue by JayGhiya** [bitnami/charts#24567]
### Name and Version

bitnami/nginx: 15.14.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

when i add server block config 
```yaml
serverBlock: |-
  upstream api_server {
      server api-server-service:80 fail_timeout=0;
  }

  upstream web_server {
      server web-server-service:80 fail_timeout=0;
  }
  
  include  "/opt/bitnami/nginx/conf/bitnami/*.conf";

  server {
      listen 80;
      server_name $$DOMAIN;

      client_max_body_size 5G;    # Maximum upload size

      location ~ ^/api(.*)$ {
          rewrite ^/api(/.*)$ $1 break;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_redirect off;
          proxy_pass http://api_server;
      }

      location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_redirect off;
          proxy_pass http://web_server;
      }
  }

```
the pod crashes citing there is no nginx conf available. I do understand nginx conf is part of the container and this just goes there and sits in but why it is not being available? looks like something v specific to the config I have.

### What is the expected behavior?

shud work.

### What do you see instead?

pod crash

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by JayGhiya** [comment]
Sure I could share values yaml then it should help us get down to real issue

**Comment by JayGhiya** [comment]
Yea this was solved my bad in terms of minor config mistake.
