### ISSUE TITLE
bitnami/spring-cloud-dataflow NPE on Skipper Configmap

### ISSUE THREAD

**Issue by rakrvptl** [bitnami/charts#24575]
### Name and Version

bitnami/spring-cloud-dataflow

### What architecture are you using?

None

### What steps will reproduce the bug?

Took the latest version of values yaml and configured values for my local setup for minikube.

On executing the custom values yaml getting this error. 
```
Error: INSTALLATION FAILED: template: spring-cloud-dataflow/templates/skipper/deployment.yaml:33:35: executing "spring-cloud-dataflow/templates/skipper/deployment.yaml" at <include (print $.Template.BasePath "/skipper/configmap.yaml") .>: error calling include: template: spring-cloud-dataflow/templates/skipper/configmap.yaml:77:27: executing "spring-cloud-dataflow/templates/skipper/configmap.yaml" at <$environmentVariables>: undefined variable: $environmentVariables
```
Maybe this line needs a fix similar to one at line 58
https://github.com/bitnami/charts/blob/main/bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml#L77

### What is the expected behavior?

Generate k8s deployment or scripts during dry-run option

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
