### ISSUE TITLE
No way to correctly upgrade to Mariadb 10.11

### ISSUE THREAD

**Issue by jordanefillatre** [bitnami/charts#24581]
### Name and Version

bitnami/mariadb-galera: 8.2.9 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am looking to upgrade a mariadb-galera cluster in 10.6.5 deployed with the bitnami chart version 7.4.11.
I want to move to mariadb-galera 10.11.7 with  8.2.9 chart version and following [editor recommendations](https://mariadb.com/kb/en/upgrading-from-mariadb-10-6-to-mariadb-10-11-with-galeracluster/)

### What is the expected behavior?

The required mysql_upgrade `mysql_upgrade --skip-write-binlog` with `wsrep off` is  run at 10.11 pod startup

### What do you see instead?

The required mysql_upgrade `mysql_upgrade --skip-write-binlog` with `wsrep off` is not run at 10.11 pod startup

I didn't see any script to do that and I didn't see how it could be done with only manual operations as a workaround. I think that chart must use a docker image that checks if the upgrade is required at startup

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/charts/tree/main/bitnami/mariadb-galera#upgrading) you can see some notes about upgrading the chart from one major to another major, but mainly it's needed to see the upstream recommendations.

**Comment by jordanefillatre** [comment]
Hello, I agreed with the need of review upstream recommendations, but the situation that I point is that the neither the helm upgrade or manual operations will allow to correctly follow them. I don't see a to restart each pod with wsrep off and run the mysql_upgrade. In my mind a an helm upgrade must allow to do this basic upgrade operation.

**Comment by jotamartos** [comment]
Hi @jordanefillatre,

According to the documentation, "this can cause issues if you restart a non-upgraded node in a cluster where the rest of the nodes have been upgraded.". Old nodes are not expected to be restarted during the upgrade process, they will be removed and new ones will appear so this shouldn't be an issue when upgrading the Bitnami MariaDB Galera chart. Did you run into any issue when can replicate? 

If you need all pods to be recreate at the same time, you can change the upgrade strategy to recreate all pods at once 

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

You can contribute to this repo by following the [contributor guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) and the team will take care of checking the changes.

**Comment by jordanefillatre** [comment]
Hi @jotamartos 
I don't think that the galera protocol version last documentation note is related to  the  need  of run mysql_upgrade with wsrep off .
I don't run into  replication issue but error are logged at pod restart in new mariadb version due to unappropriate startup sequence in case of upgrade. The mysql_upgrade is not run before re enable the replication: 

`2024-03-19  9:01:13 46 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
2024-03-19  9:01:13 46 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
`

**Comment by jotamartos** [comment]
I just reproduced the issue when upgrading from Bitnami MariaDB Galera Chart version 7.5.5 to 8.0.0. I'll investigate if this also happens with the latest version of the chart or if it's a problem that only happens with old version of the solution. 

Thanks

**Comment by jotamartos** [comment]
Hi @jordanefillatre,

As I mentioned, I could reproduce the issue when migrating from Bitnami MariaDB Galera Chart version 7.5.5 to 8.0.0 (from MariaDB 10.6 to 10.11). However, the upgrade doesn't throw that error when migrating from Chart version 8.0.0 (fresh install) to 9.0.0 (MariaDB versions 10.11 to 11.0). 

As we can't update the chart that includes MariaDB 10.11 anymore, you will need to finish the upgrade manually by running the `mysql_upgrade --user=root --password=PASSWORD` command in each of the nodes. That command solves the issue and the error is no longer shown in the logs.

**Comment by jotamartos** [comment]
>Upgrading manually doesn't really solve the issue as statefulset start each mariadb cluster node with wsrep ON.

Once you run the mysql_upgrade command in each node, you shouldn't get those errors anymore as the database information will be updated. 

>If entrypoint scripts in the container image used to deploy mariadb-galera 10.11 are not maintained, the issue still impact also next 11.0 upgrades

As I mentioned above, I upgraded from 10.11 to 11.0 and I did not get the error so this seems to be a specific upgrade instruction from 10.6. However, you can always [contribute](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) and improve the upgrade process if problem persists

https://github.com/bitnami/containers/blob/main/bitnami/mariadb-galera/11.0/debian-12/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L1140
