### ISSUE TITLE
[bitnami/postgresql] imagePullSecrets helper expects a list of strings instead of a list of maps

### ISSUE THREAD

**Issue by bjayanth** [bitnami/charts#2458]
**Which chart**:
bitnami/postgresql:8.9.3

**Describe the bug**
Having this in a parent chart that pulls in postgresql as a dependency causes the postgresql workload template to have a misformed imagePullSecrets field.
Parent values.yaml:
```
global:
  imagePullSecrets:
    - name: regcred
```
postgresql StatefulSet yaml:
```
imagePullSecrets:
  - name: map[name:regcred]
```

**To Reproduce**
Un-comment the global.imagePullSecrets line in the values.yaml file
```
global:
  postgresql: {}
#   imageRegistry: myRegistryName
  imagePullSecrets:
    - name: myRegistryKeySecretName
```
Run `helm install postgresql bitnami/postgresql/ --dry-run`

**Expected behavior**
Expect the postgresql Helm chart to accept global.imagePullSecrets as list of maps.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
For reference, `helm create` creates a chart with:
values.yaml:
```
imagePullSecrets: []
```
deployment.yaml:
```
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```

**Comment by juan131** [comment]
Hi @bjayanth 

I wasn't able to reproduce the issue. I followed these steps:

```console
$ cat > values.yaml << 'EOF'
global:
  postgresql: {}
  imagePullSecrets:
    - NEW_PULL_SECRETS
EOF
$ helm template -f values.yaml postgresql bitnami/postgresql -s templates/statefulset.yaml
---
# Source: postgresql/templates/statefulset.yaml
(...)
   spec:
      imagePullSecrets:
        - name: NEW_PULL_SECRETS
(...)
```

Offtopic: please upgrade your Helm client (Helm 3.1.2 is affected by a known vulnerability, see https://github.com/helm/helm/security/advisories/GHSA-q8q8-93cv-v6h8)

**Comment by bjayanth** [comment]
Hey @juan131, thank you for looking into this.

If you try adding this in the values.yaml is when it'll fail:
```
global:
  imagePullSecrets:
    - name: NEW_PULL_SECRETS
```
Note the `name: NEW_PULL_SECRETS` and not just `NEW_PULL_SECRETS`

The problem is I have the parent chart following the templates `helm create` creates as much as possible (to standardize Helm charts) and that has 
```
{{- with .Values.imagePullSecrets }} # in my case: {{- with .Values.global.imagePullSecrets | default .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
```
in the deployment.yaml. And this makes it expect `imagePullSecrets` to be of the form `- name: secret`.

**Comment by javsalgar** [comment]
Hi,

Could you let us know which is the parent chart you are using? Is it one you created or is it another one from Bitnami? I would expect that all of our charts follow the same standard but I'm not sure if we can guarantee 0 collissions with other charts that use the global parameter.

**Comment by bjayanth** [comment]
A parent chart I created. So yeah, to solve it, I could change it (and all other subcharts) to follow Bitnami's standard. And just to be clear, having `- name: map[name:regcred]` doesn't break anything while deploying because I don't need a secret to pull the default image.

I just saw that all charts under Bitnami have the same helper.

I guess the question is why is Bitnami following a different standard from what Helm suggests (I'm assuming `helm create` follows their best practices)?

**Comment by juan131** [comment]
Hi @bjayanth 

The "standard" usually changes along the time.

For instance, there was a time where the "standard" labels were `app`, `chart`, `release` and `heritage`. Then, Helm switched them to adopt K8s recommended labels, see:

- https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

The problem when Helm changes the standard is that we cannot adopt it without including backwards incompatibilities in the charts. That's the reason why we have charts, like PostgreSQL, using the "old" standard (see https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml#L5) while we have recent charts added to the catalog, like Thanos, using the "new" one (see https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/_helpers.tpl#L48).

**Comment by bjayanth** [comment]
Hey @juan131. Thank you for the explanation. That makes sense.
I realize there's no easy way to keep updating the charts, especially if it affects the common structure. And since this doesn't make the k8s deployment fail, I will close the issue.

**Comment by juan131** [comment]
You're welcome @bjayanth 
Please do not hesitate to reach if you require further help in the future with this or any other chart.

**Comment by lmsurpre** [comment]
i just hit this same thing on the bitnami redis chart (version 16.x).
the fact the docs just say "Global Docker registry secret names as an array" is quite unhelpful.

complicating matters, googling "bitnami imagePullSecret" pulls up the [bitnami drupal chart doc](https://docs.bitnami.com/kubernetes/apps/drupal/configuration/configure-image-registry/) which uses a list of maps instead of a list of strings
