### ISSUE TITLE
[bitnami/opensearch] Broken links to OpenSearch documentation

### ISSUE THREAD

**Issue by lindhe** [bitnami/charts#24585]
### Name and Version

bitnami/opensearch

### What architecture are you using?

None

### What steps will reproduce the bug?

These links are broken:

https://github.com/bitnami/charts/blob/2fd560d5c7730d37a0f51503dcc57098d4f60c30/bitnami/opensearch/README.md?plain=1#L67-L68

Seems to be https://opensearch.org/ nowadays.

### What do you see instead?

Maybe this is a good link? https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/#important-settings

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by lindhe** [comment]
Normally I'd love to contribute, but since I don't know where you intend the links to lead it's hard for me to create a useful PR on this particular issue. :)

**Comment by lindhe** [comment]
Fixed in #29548
