### ISSUE TITLE
Pods keep crashing when specified communityPlugins options

### ISSUE THREAD

**Issue by pidge-raman** [bitnami/charts#24592]
### Name and Version

bitnami/rabbitmq 13.0.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Setting up community Plugin leads to server to bootstrap
Issue is due to directory `/opt/bitnami/rabbitmq/plugins` is read-only

- Add a community plugins

```
communityPlugins: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez"
```

### What is the expected behavior?

Rabbitmq server should start with the provided plugin

### What do you see instead?

```
rabbitmq 07:29:11.12 INFO  ==>
rabbitmq 07:29:11.12 INFO  ==> Welcome to the Bitnami rabbitmq container
rabbitmq 07:29:11.12 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 07:29:11.12 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 07:29:11.12 INFO  ==>
rabbitmq 07:29:11.13 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 07:29:11.14 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 07:29:11.22 INFO  ==> Initializing RabbitMQ...
```

After this step it crashes

**Comment by mentlak0** [comment]
Hi, 

Just had a similar issue with helm chart version 13.0.0. The below may help?

It looks like some default values have been added to the statefulset and when deployed it was crashing one of my nodes. 

This is what has changed:

![image](https://github.com/bitnami/charts/assets/93769720/af509773-9546-4af2-9ceb-400873039a31)


I added this to my values (which it was previously) and it has fixed it:
```
containerSecurityContext:
  readOnlyRootFilesystem: false
  runAsGroup: 0
```

**Comment by pidge-raman** [comment]
Thanks, This fixes the issue.
Reason we are using 13.0.0 release is the security improvements we got, this might defeat the purpose.

**Comment by mentlak0** [comment]
Yeah I agree. We have automated chart upgrades for our external charts. So we upgrade to latest version once every week. 

I can see this possibly 'defeating' the purpose. But it fixes for now to maintain uptime. Going to look into the changes soon.

**Comment by FraPazGal** [comment]
Hello @pidge-raman, this is indeed an issue introduced in the new major which I could reproduce locally:

```
$ kubectl logs rabbitmq-0
...
rabbitmq 16:35:09.70 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 16:35:09.71 INFO  ==> Initializing RabbitMQ...
rabbitmq 16:35:09.71 DEBUG ==> Downloading custom plugins...
```

Thanks for the proposed workaround @mentlak0, we appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by semakBetterMe** [comment]
The same issue after some digging:
`/opt/bitnami/rabbitmq` is under root:root permission even `volumePermissions.enable = true not change it`
so when we specify `communityPlugins` rabbitmq try download and put plugin into this directory and don't have permission with `exitCode: 23`

**Comment by juan131** [comment]
Hi everyone! I just created a PR to address this issues so it's possible to install custom plugins without reverting security defaults.
