### ISSUE TITLE
[bitnami/apisix] Unable to disable tls on control-plane

### ISSUE THREAD

**Issue by jorgenll** [bitnami/charts#24594]
### Name and Version

bitnami/apisix 3.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set the parameter `controlPlane.tls.enabled=false`
2. Generate the template

### Are you using any custom parameters or values?

-- set controlPlane.tls.enabled=false

### What is the expected behavior?

If we disable the tls on the controlPlane, the Secret **apisix-control-plane-tls** isn't generated

### What do you see instead?

The Secret **apisix-control-plane-tls** is generated. If additionally the parameters `controlPlane.tls.autoGenerated` is set to false, the secret is generated without data

### Additional information

Reviewing the template [tls-secret.yaml](https://github.com/bitnami/charts/blob/main/bitnami/apisix/templates/tls-secret.yaml) file, exists a difference between the configuration for the data-plane and the control-plane. 
The following [if sentence](https://github.com/bitnami/charts/blob/main/bitnami/apisix/templates/tls-secret.yaml#L7) miss the check `.Values.controlPlane.tls.enabled`. 
The current if: 
```yaml
{{- if and .Values.controlPlane.enabled (not .Values.controlPlane.tls.existingSecret) }}
```
The expected if: 
```yaml
{{- if and .Values.controlPlane.enabled .Values.controlPlane.tls.enabled (not .Values.controlPlane.tls.existingSecret) }}
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by jorgenll** [comment]
Great, I'll create the pull request with the fix. 
Additionally, I've see a similar issue trying to disable the tls on the ingress-controller. I'll include both fixes on the PR

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
