### ISSUE TITLE
[bitnami/wordpress] Upgrade wordpress helm package 20.1.3 to 21.0.3 and having a file permission denied issue

### ISSUE THREAD

**Issue by tk2023** [bitnami/charts#24590]
### Name and Version

bitnami/wordpress 21.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. upgrade wordpress helm package from 20.1.3 to 21.0.3 and pod cannot start
2. using external database and external pvc
3. when starting the container, it said:
```
wordpress 17:55:48.06 INFO  ==> ** Starting WordPress setup **
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/00_status-vhost.conf': Permission denied
```

### What do you see instead?

when I do: `kubectl logs wordpress-768fdc8967-rsd4r` 

it said:
```
wordpress 17:55:48.06 INFO  ==> ** Starting WordPress setup **
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/00_status-vhost.conf': Permission denied
```

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by tk2023** [comment]
so, is there a document about how to fix the container in order to upgrade to version 21.0.0?

**Comment by javsalgar** [comment]
Could you confirm is setting runAsGroup=0 and readOnlyRootFilesystem=false fixes the issue for the time being? Then we can check what could be happening in the installation.

**Comment by tk2023** [comment]
Just upgrade to 21.0.7 and still not working.

**Comment by javsalgar** [comment]
Did you check this? https://github.com/bitnami/charts/issues/24590#issuecomment-2017589090

**Comment by mchobbel** [comment]
Same problem for me for 21.0.10.  Image:  docker.io/bitnami/wordpress:6.4.3-debian-12-r31 
With these settings it is still the same:
```
containerSecurityContext:
  runAsGroup: 0
  readOnlyRootFilesystem: false
```

**Comment by javsalgar** [comment]
Apart from that, did you change any other setting from values.yaml? We want to reproduce the issue

**Comment by mchobbel** [comment]
My own "clean" reproduction goes like this:
 - create a new PVC  2G - referenced by persistence.existingClaim
 - create an empty MariaDb
 - fill the helm-values-template accordingly
 - run helm install -f YAML_FILE BASENAME  bitnami/wordpress

Then I get 
```
wordpress 11:25:06.70 INFO  ==> ** Starting WordPress setup **
wordpress 11:25:06.74 WARN  ==> The Apache configuration file '/opt/bitnami/apache/conf/httpd.conf' is not writable. Configurations based on environment variables will not be applied.
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/00_status-vhost.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/wordpress-https-vhost.conf': Permission denied
cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/wordpress-vhost.conf': Permission denied
```
And when I inspect the PVC I can see the (empty) wordpress directory was created:
```
/ # ls -l mnt/pvc/
total 20
drwx------    2 root     root         16384 Apr  3 11:24 lost+found
drwxr-xr-x    2 1001     1001          4096 Apr  3 11:24 wordpress
```

**Comment by javsalgar** [comment]
Could you share with us the configmaps you are using for htaccess and apache? I believe that's where the issue is

**Comment by benedikt-bartscher** [comment]
We have the same issue. Current configmap:
```yaml
  wordpress-htaccess.conf: |-
    LoadModule remoteip_module modules/mod_remoteip.so
    RemoteIPHeader X-Forwarded-For

    LoadModule cache_module modules/mod_cache.so
    LoadModule cache_disk_module modules/mod_cache_disk.so
    LoadModule expires_module modules/mod_expires.so
    # Cache all
    CacheEnable disk "/"
    # Directory on the disk to contain cached files
    CacheRoot "/var/cache/httpd/proxy"
    # Enable cache and set 15-minute caching as the default
    ExpiresActive On
    ExpiresDefault "access plus 15 minutes"
    # Force no caching for PHP files
    <FilesMatch "\.(php)$">
        ExpiresActive Off
    </FilesMatch>
```

**Comment by mchobbel** [comment]
My configmaps are
[htaccess.txt](https://github.com/bitnami/charts/files/14859223/htaccess.txt)
[httpd-conf.txt](https://github.com/bitnami/charts/files/14859224/httpd-conf.txt)

**Comment by javsalgar** [comment]
I'm about 99% sure that the issue triggers with custom htaccess/configmaps, I will check it and work on a fix

**Comment by javsalgar** [comment]
Hi! 

Could you check if the PR above fixes the issue? :arrow_up: I tried with a custom htaccess and it worked.

**Comment by mchobbel** [comment]
Hi javsalgar,  thanks a lot. It works fine now.
