### ISSUE TITLE
Add external configuration steps in Keycloak chart

### ISSUE THREAD

**Issue by rcbandit111** [bitnami/charts#24620]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Into which file do I have to add configuration for the external database and how it should be formatted in yaml syntax?

### What do you see instead?

Missing description

**Comment by carrodher** [comment]
It is documented in the README, see https://github.com/bitnami/charts/tree/main/bitnami/keycloak#use-an-external-database.
The configuration parameters are available in the values.yaml, see https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L1245
