### ISSUE TITLE
Allow customizing primary persistence volume/claim

### ISSUE THREAD

**Issue by UnsolvedCypher** [bitnami/charts#24624]
### Name and Version

bitnami/postgresql 15.1.2

### What is the problem this feature will solve?

The name of the primary persistence volume (and created claim) is hardcoded to "data". Some users want to customize this name

### What is the feature you are proposing to solve the problem?

Add the ability to customize the primary persistence volume/claim.

### What alternatives have you considered?

Not customizing the name

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
