### ISSUE TITLE
[bitnami/fluentd]

### ISSUE THREAD

**Issue by irizzant** [bitnami/charts#2462]
**Which chart**:
[bitnami/fluentd] 1.0.4

**Describe the bug**
The chart as is it's not compatible with Istio [requirements](https://istio.io/docs/ops/deployment/requirements/).
* `app` label is missing
* Service [port names](https://github.com/bitnami/charts/blob/32e9c184bc4c3cfdd1f50054bfc1d77fe1ac6ed6/bitnami/fluentd/templates/metrics-svc.yaml#L14) are incorrect 
* Service's are overlapping, e.g https://github.com/bitnami/charts/blob/master/bitnami/fluentd/templates/aggregator-svc.yaml and https://github.com/bitnami/charts/blob/master/bitnami/fluentd/templates/svc-headless.yaml both map to the same Pod (the aggregators).

**Expected behavior**
The chart should be compatible with Istio

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by carrodher** [comment]
Thanks for creating the issue and contributing through the PR, we are going to review it and test in our CI/CD system.

**Comment by irizzant** [comment]
Ok looking forward for your reply
