### ISSUE TITLE
Zookeeper Start Error

### ISSUE THREAD

**Issue by liyongxian** [bitnami/charts#24639]
### Name and Version

bitnami/zookeeper

### What architecture are you using?

None

### What steps will reproduce the bug?

1、helm pull bitnami/zookeeper
2、helm install zookeeper -n daas-system ./ --set global.storageClass=local-path
3、kubectl get po -n daas-system
![image](https://github.com/bitnami/charts/assets/18571576/34570719-dc89-4fcd-87f7-ae1f19ccba5f)
4、 Pod logs
![image](https://github.com/bitnami/charts/assets/18571576/aae9d844-43c4-4d18-99ef-4aadb93031cb)

### Are you using any custom parameters or values?

--set global.storageClass=local-path

### What is the expected behavior?

Zookeeper Pod Running.

### What do you see instead?
```
/opt/bitnami/java/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
[0.079s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
```

**Comment by juan131** [comment]
Hi @liyongxian 

It seems like Zookeeper is unable to allocate the required resources to start. Do you have enough RAM memory in your cluster?

**Comment by wlrm-dlisovsky** [comment]
We faced the same issue on the k8s cluster. 

```
[0.199s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
```
And we have enough CPU/RAM in the cluster.
We've already tried to update nproc/kernel.threads-max/vm.max_map_count to bigger sizes but no success. 
resources are not so big to request:
```
    Limits:
      cpu:     100m
      memory:  512Mi
    Requests:
      cpu:      20m
      memory:   128Mi
```
also we tried to decrease Xss/Xmx - doesn't help.
where else we could look?

**Comment by javsalgar** [comment]
I would try increasing the resources to see if that fixes the issue

**Comment by ChrWeis** [comment]
We're currently running into the same issue.
But it is yet, not clear to me how this can be resolved.

`[0.002s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.`

To eliminate possibly limiting factors, we've set high resource limits:

```yaml
  resources:
    # increased resources to eliminate a possibly limiting factor 
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 4Gi
      cpu: 2
```

Reducing the heapsize to 512, did also not help with the issue. However, CLI output lists `-Xmx` twice.
`-Dzookeeper.log.dir=/opt/bitnami/zookeeper/logs -Dzookeeper.log.file=/opt/bitnami/zookeeper/logs/zookeeper.out  -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -Xmx1000m -Xmx512m -Xms512m -Dzookeeper.electionPortBindRetry=0 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false org.apache.zookeeper.server.quorum.QuorumPeerMain `

**Comment by juan131** [comment]
@ChrWeis what steps did you follow to decrease the heapsize?

**Comment by ChrWeis** [comment]
@juan131 , I set the paramter to `heapSize:512` referenced in [zookeeper-chart-parameters](https://github.com/bitnami/charts/tree/b2d0ffc22544d9bedb52253cb91607a1ff58a09c/bitnami/zookeeper#zookeeper-chart-parameters).

**Comment by juan131** [comment]
Thanks for the details @ChrWeis 

Regarding the issue with the `-Xmx` flag being set twice, please not `java` starts processing arguments from left to right hence the last occurrence takes precedence which is `-Xmx512m` in your case.

Could you please connect to your ZooKeeper container (using `kubectl exec -it ...`) and share the output of running the command: `ulimit -a`?

**Comment by ChrWeis** [comment]
I was unable to connect to the Zookeeper container without changing anything on the current deployment, as it was stuck in a crash loop.

However, we've figured out that the issue actually wasn't memory related.  Instead it was a permission issue.
We modified the container security context to `containerSecurityContext.seccompProfile.type: Unconfined`. This got the containers started successfully.
