### ISSUE TITLE
OpenSearch re-creates certificates when deployed through ArgoCD

### ISSUE THREAD

**Issue by NandoTheessen** [bitnami/charts#24643]
### Name and Version

bitnami/opensearch:0.9.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy OpenSearch through ArgoCD with autoGenerated certificates

### Are you using any custom parameters or values?

`security.tls.autoGenerated: true`

### What is the expected behavior?

The deployment should be stable, certificates should not change

### What do you see instead?

On every commit to the repository housing GitOps configuration, new certificates are generated which triggers a re-deployment of all pods.

This also happens on commits that are entirely unrelated to the configuration of OpenSearch.

**Comment by migruiz4** [comment]
Hi @NandoTheessen,

The `bitnami/opensearch` chart already includes a feature to reuse existing secrets called `common.secrets.lookup`:

https://github.com/bitnami/charts/blob/57adc1632d3e3638d44c1a7806a6e2245756be22/bitnami/opensearch/templates/tls-secret.yaml#L34-L50

The `common.secrets.lookup` is a lib function from our `bitnami/common` chart that relies on Helm's [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) function to reuse existing secrets when deploying.

https://github.com/bitnami/charts/blob/57adc1632d3e3638d44c1a7806a6e2245756be22/bitnami/common/templates/_secrets.tpl#L144-L165

If the `lookup` function fails, it will then recreate a new value.

The issue in this case is not related to the chart itself, but to ArgoCD not supporting Helm's lookup function: https://github.com/argoproj/argo-cd/issues/5202

I'm sorry but there is not much we can do to fix this issue on our side.

**Comment by NandoTheessen** [comment]
Thanks, then this can be closed!
