### ISSUE TITLE
[bitnami/rabbitmq] Password secret changes with every Helm upgrade but actual password remains the same

### ISSUE THREAD

**Issue by OvervCW** [bitnami/charts#2465]
**Which chart**:
bitnami/rabbitmq 6.25.5

**Describe the bug**
Doing a Helm upgrade resets the password secret every time without updating the actual RabbitMQ password:

```
$ helm upgrade -i my-release bitnami/rabbitmq --wait
```

This is confusing in general *and* breaks the liveness/readiness probes.

**To Reproduce**
1. Run `helm upgrade -i my-release bitnami/rabbitmq --wait`
2. Log in with the username `user` and password in the `my-release-rabbitmq` secret and find that it works fine.
3. Upgrade the release by running `helm upgrade -i my-release bitnami/rabbitmq --wait` again.
4. Observe that the password in `my-release-rabbitmq` has changed, but when logging in rabbitmq still only accepts the old password.

**Expected behavior**
RabbitMQ should either assume the new password, or the existing password secret should stay in place once it has been generated.

**Version of Helm and Kubernetes**: 

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"126eb499523e5fffc0138e8e2e031787e5ab1943", GitTreeState:"clean", BuildDate:"2020-04-03T17:45:13Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

N/A

**Comment by rafariossaa** [comment]
Hi, 
  I am unable to reproduce the issue, the command works for me.
  Could you try again previously deleting the installed chart and the pvc ?
  Could you attach the pod logs ?

Thanks

**Comment by OvervCW** [comment]
@rafariossaa You're right, I pinpointed the problem more specifically just now.

**Comment by carrodher** [comment]
Please note it's mandatory to indicate the password and erlangCookie that was set the first time the chart was installed to upgrade the chart. Otherwise, new pods won't be able to join the cluster

```
rabbitmq.password="RABBITMQ_PASSWORD"
rabbitmq.erlangCookie="RABBITMQ_ERLANG_COOKIE"
```

Please note that `RABBITMQ_PASSWORD` and `RABBITMQ_ERLANG_COOKIE` are placeholders that you should modify. In order to obtain both values you can execute the following commands:
```
echo "Password: $(kubectl get secret --namespace {{ .Release.Namespace }} {{ template "rabbitmq.fullname" . }} -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
echo "ErLang Cookie: $(kubectl get secret --namespace {{ .Release.Namespace }} {{ template "rabbitmq.fullname" . }} -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"
```

**Comment by OvervCW** [comment]
@carrodher Does the same apply for many of the other databases in this repo? E.g. redis?

**Comment by carrodher** [comment]
Yes, the password is stored in secrets and the secrets are regenerated when you install or upgrade the chart, so it is needed to pass the password (or the secret) to use the previous one.

I was taking a look at the READMEs and it seems that it is not explained properly so I just created a task in order to create a section explaining this behavior.

**Comment by OvervCW** [comment]
Alright, thank you. In that case I consider this issue resolved.
