### ISSUE TITLE
[bitnami/elasticsearch] Unable to perform rolling update while using recommended elastic client

### ISSUE THREAD

**Issue by LucyJohnson-lua4life** [bitnami/charts#24666]
### Name and Version

bitnami/elastic 19.21.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install Elasticsearch Cluster on Kubernetes (3 master nodes, 2 coordinator, 2 ingest)
2. Query Cluster with recommended elasticsearch client (either https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html or https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html). Pass the elastic client the addresses to the 2 coordinator nodes (coordinator-0 and coordinator-1). Try to query the cluster in a loop during a rolling update.
3. Perform a rolling Update on the cluster OR simulate it by doing:
`kubectl rollout restart statefulset ingest` 
`kubectl rollout restart statefulset master` 
`kubectl rollout restart statefulset coordinator` 

### What is the expected behavior?

I would expect the elasticsearch client to keep returning results once the coordinator-0 is getting restarted. (Since the client should switch to coordinator-1 then)

### What do you see instead?

The client returns a UnknownHostException since the DNS lookup doesnt work anymore for the coordinator-0 that is going down and the elastic client can't handle that.

### Additional information

Maybe this is less of a Bug-Report as more of a question of how a rolling update is generally performed with this chart. I couldn't find any reports on this issue so far, even though I think that my use case is a rather common one. 
The goal really is just to be able to continue querying the elasticsearch during a rolling update.

**Comment by LucyJohnson-lua4life** [comment]
Additonally: The reason for the "UnknownHostException" most likely lies in the way Kubernetes stateful sets work. Since they don't make a proper DNS lookup anymore once coordinator-0 is down. However the elastic-client requires a so called "RetryableException" to than try query the next passed node (coordinator-1) https://github.com/elastic/elasticsearch/blob/main/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L306  Is that still in the scrope of the bitnami chart? Or should I rather implement a own retry-mechanism in my Java-Application itself?

**Comment by magro** [comment]
@LucyJohnson-lua4life I just stumbled over this issue here, wondering how to connect a java/rest client to a bitnami es setup... Because you closed this issue, what was your conclusion?
