### ISSUE TITLE
Rplication factors are too large for the number of replicas

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#24660]
### Name and Version

bitnami/kafka 27.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Install the helm chart with a replicaCount less than 3

### Are you using any custom parameters or values?

Yes, but the problem is that either the values created by the chart or incorrect for low replica counts, or they need to be overriden for those replica counts.

### What is the expected behavior?

The replication factors should be no higher than the number of replica pods. For instance, the config values for...

transaction.state.log.replication.factor
offsets.topic.replication.factor

are set at 3 as a default. When the replicaCount is less than 3 this only serves to break the instances. I don't know if the chart is creating the default values, or not overriding the default values for replica counts of 1 or 2, but it probably should, just so the chart is not causing errors.

### What do you see instead?

Default replications factors higher than the replica count.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
