### ISSUE TITLE
[bitnami/kubernetes-event-exporter] Using podAnnotations to inject vault annotations does not work

### ISSUE THREAD

**Issue by epwickey** [bitnami/charts#24676]
### Name and Version

bitnami/kubernetes-event-exporter

### What architecture are you using?

None

### What steps will reproduce the bug?

Add podAnnotations in values.yaml. No matter how I try to escape the curlybraces ( using backticks {{ "{{" }} notation ) I always get the error function "secret" not defined

### Are you using any custom parameters or values?
```
podAnnotations:
    vault.hashicorp.com/role: "kubernetes-apps"
    vault.hashicorp.com/log-level: "Info"
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-password: "kubernetes-secrets/data/tooling/es-node/k8s_events_exporter"
    vault.hashicorp.com/agent-inject-template-password: |
        {{`{{- with secret "kubernetes-secrets/data/tooling/es-node/k8s_events_exporter" -}}
          export ES_USERNAME="k8s_events_exporter"
          export ES_PASSWORD="{{ .Data.data.k8s_events_exporter }}"
          {{- end }}`}}
```
### What is the expected behavior?

pod annotations added to the deployment and init container for vault created

### What do you see instead?

error function "secret" not defined.

**Comment by epwickey** [comment]
This might be hapenning at this step
`          {{- $podAnnotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.podAnnotations .Values.commonAnnotations ) "context" . ) }}          {{- include "common.tplvalues.render" ( dict "value" $podAnnotations "context" $ ) | nindent 8 }}`

**Comment by epwickey** [comment]
changing the include part in annotations to below works ( Include separately )

          {{- if .Values.podAnnotations }}
          {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
          {{- end }}
          {{- if .Values.commonAnnotations }}
          {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 8 }}
          {{- end }}

**Comment by javsalgar** [comment]
Hi!

Thank you for the PR! The team will take a look

**Comment by juan131** [comment]
Try using:
```yaml
podAnnotations:
  vault.hashicorp.com/agent-inject-template-password: |
    {{ printf "{{`{{- with secret \"kubernetes-secrets/data/tooling/es-node/k8s_events_exporter\" }}\n  export ES_USERNAME=\"k8s_events_exporter\"\n  export ES_PASSWORD=\"{{ .Data.data.k8s_events_exporter }}\"\n  {{- end }}" }}`}}" }}
```
Result:
```console
$ helm template -f values.yaml kubernetes-event-exporter oci://registry-1.docker.io/bitnamicharts/kubernetes-event-exporter -s templates/deployment.yaml
(...)
spec:
  (...)
  template:
    metadata:
      annotations:
        checksum/config: 7b57284294d98c65a2318b1d9d462ea267680054ae0e13210c8686912896836d
        vault.hashicorp.com/agent-inject-template-password: |-
          {{- with secret "kubernetes-secrets/data/tooling/es-node/k8s_events_exporter" }}
          export ES_USERNAME="k8s_events_exporter"
          export ES_PASSWORD="{{ .Data.data.k8s_events_exporter }}"
          {{- end }}" }}
```

**Comment by epwickey** [comment]
Works
