### ISSUE TITLE
The init containers should set resources, otherwise it's no possible to use a ResourceQuota for the Namespace

### ISSUE THREAD

**Issue by jfreese** [bitnami/charts#24673]
### Name and Version

bitbanit/fluentd 6.1.0

### What is the problem this feature will solve?

The init containers of the Fluentd StatefulSet or DaemonSet don't  define resources. But reosurces are required, when a ResourceQuota is defined.

### What is the feature you are proposing to solve the problem?

Add `resources: {{- toYaml .Values.init.resources | nindent 12 }}` to the init container and 
```yaml
init:
  resources: {}
```
to the values.yaml.

So we can overwrite the properties in ore custom values.yaml and define the resources.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
