### ISSUE TITLE
[bitnami/keycloak] secret value for external database does not get updated in kubernetes secret object

### ISSUE THREAD

**Issue by sebschlue** [bitnami/charts#24689]
### Name and Version

bitnami/keycloak 19.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. set database password via helm chart values and install keycloak.
2. update database password via helm chart values and upgrade keycloak.

### Are you using any custom parameters or values?

As far as I can see, this ticket is only about helm chart value externalDatabase.password

### What is the expected behavior?

I expect that the following value actually changes after an upgrade deployment with changed helm chart value externalDatabase.password:

```
kubectl get secret keycloak-externaldb -o jsonpath='{.data.db-password}' | base64 -d | xargs 
```

### What do you see instead?

The value does not change.

### Additional information

When running "helmfile apply" or "helmfile sync", I can even see the changed password in server-side helm chart values via

```
helm get values keycloak | grep password
```

But the actual value in kubernetes secret does not change.

There are two workarounds:

a) I can delete the kubernetes secret object and then perform the helm upgrade. secret object will be re-created with correct (changed) value.

b) I can perform "helmfile template | kubectl apply -f -" and this will update secret value in-place even without prior deletion.

But neither "helmfile apply" not "helmfile sync" nor "helm upgrade" will result in secret value inside kubernetes secret object keycloak-externaldb being changed. No options seem to help here, I have tried "--force" and "--reset-values" and some others with no success.

**Comment by FraPazGal** [comment]
Hello @sebschlue! I have been able to reproduce the issue and the root use is the `common.secrets.passwords.manage` helper that manages the secret's key. Checking [its template](https://github.com/bitnami/charts/blob/47242dbde5d9cab7e8061041835ff67ea2f35aea/bitnami/common/templates/_secrets.tpl#L101-L103), the logic checks whether the secret (and key) exists but it doesn't check if the existing key's value is the same as the one provided in the `values.yaml`.

Thank you for bringing this issue to our attention. If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by trourance** [comment]
I'm currently facing the same issue. Has it been fixed in a recent version ?
