### ISSUE TITLE
[kube-prometheus] needs new rbac permissions

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#24680]
### Name and Version

bitnami/kube-prometheus 8.30.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy chart
2. check console log of prometheus operator pod

### What is the expected behavior?

Don't see those warnings

### What do you see instead?

```
level=warn ts=2024-03-26T13:52:49.22290741Z caller=main.go:260 msg="missing permission to emit events" reason="missing \"create\" permission on resource \"events\" (group: \"\") for all namespaces"
level=warn ts=2024-03-26T13:52:49.222947711Z caller=main.go:260 msg="missing permission to emit events" reason="missing \"patch\" permission on resource \"events\" (group: \"\") for all namespaces"
```

### Additional information

This is probably cause by 
- https://github.com/prometheus-operator/prometheus-operator/pull/6179

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
