### ISSUE TITLE
Double hyphen in jaeger agent deployment/service name

### ISSUE THREAD

**Issue by pbolduc** [bitnami/charts#24699]
### Name and Version

bitnami/jaeger 1.11.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy jaeger `helm install jaeger oci://registry-1.docker.io/bitnamicharts/jaeger --set fullnameOverride=jaeger`
2. Observe the generated name for agent deployment and service

```
kubectl get svc -l app.kubernetes.io/component=agent

NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                         AGE
jaeger--agent   ClusterIP   10.98.107.90   <none>        6831/TCP,6832/TCP,5778/TCP,5775/TCP,14271/TCP   72s
```

```
kubectl get deployment -l app.kubernetes.io/component=agent
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
jaeger--agent   0/2     2            0           106s
```

The double hyphen is set in the [_helpers.tpl](https://github.com/bitnami/charts/blob/5e4910e8bc2b7624e34f91950cd378bca420000b/bitnami/jaeger/templates/_helpers.tpl#L138) on line 138.

### Are you using any custom parameters or values?

Just defaults, example above uses `--set fullnameOverride=jaeger` but this shouldn't make a difference.

### What is the expected behavior?

There should only be a single hyphen in the agent service and deployment names

### What do you see instead?

```
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                         AGE
jaeger--agent   ClusterIP   10.98.107.90   <none>        6831/TCP,6832/TCP,5778/TCP,5775/TCP,14271/TCP   72s
```

```
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
jaeger--agent   0/2     2            0           106s
```

### Additional information

I'll see if I can find time to submit a PR today or tomorrow.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
