### ISSUE TITLE
[bitnami/keycloak] provide chart for keycloak 24.0.2

### ISSUE THREAD

**Issue by antikalk** [bitnami/charts#24711]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Providing a chart for keycloak 24.0.2

The automated release job failed and requires manual intervention: https://github.com/bitnami/charts/pull/24677 

### What is the feature you are proposing to solve the problem?

Providing a chart for keycloak 24.0.2

**Comment by javsalgar** [comment]
Hi!

The team is looking into it. As soon as there are updates, we will notify the community.

**Comment by psleep** [comment]
As per Keycloak documentation, the --proxy option will be depreciated. Can this change please be reflected in the helm chart?

https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option

Thanks for all the work!

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
