### ISSUE TITLE
[wordpress & mariadb]

### ISSUE THREAD

**Issue by johnsiciliano** [bitnami/charts#2471]
So after doing an upgrade deployment with the new version of wordpress chart I'm getting a fatal error.
This is the second time this has happened, I notice it happens after the chart has been updated.

I've upgraded before with the same chart version as before, and no issues arose.

I used the same values file as the one i used 3 weeks go.

Errors and description posted below

If there's something I can do to safely upgrade please let me know

`xxxxx-mariadb-0                    0/1     CrashLoopBackOff   6          10m`

logs output is giving me this

```
mariadb 04:00:11.60 
mariadb 04:00:11.61 Welcome to the Bitnami mariadb container
mariadb 04:00:11.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 04:00:11.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 04:00:11.61 Send us your feedback at containers@bitnami.com
mariadb 04:00:11.61 
mariadb 04:00:11.61 INFO  ==> ** Starting MariaDB setup **
mariadb 04:00:11.69 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 04:00:11.70 INFO  ==> Initializing mariadb database
mariadb 04:00:11.73 INFO  ==> Using persisted data
mariadb 04:00:11.76 INFO  ==> Running mysql_upgrade
mariadb 04:00:11.76 INFO  ==> Starting mariadb in background
mariadb 04:00:12.84 INFO  ==> Stopping mariadb`
```

instance output is as follows

```
Name:         xxxxx-mariadb-0
Namespace:    default
Priority:     0
Node:         pool-zmt6vkhg6-dgrq/10.138.17.147
Start Time:   Wed, 29 Apr 2020 20:48:34 -0700
Labels:       app=mariadb
              chart=mariadb-7.3.21
              component=master
              controller-revision-hash=xxxxx-mariadb-6974f69889
              release=xxxxx
              statefulset.kubernetes.io/pod-name=xxxxx-mariadb-0
Annotations:  <none>
Status:       Running
IP:           10.244.0.105
IPs:
  IP:           10.244.0.105
Controlled By:  StatefulSet/xxxxx-mariadb
Containers:
  mariadb:
    Container ID:   docker://0370ef7e715d0351442b30bd0ab68349ecd1ff63b6e1750849ddf4d88b503406
    Image:          docker.io/bitnami/mariadb:10.3.22-debian-10-r92
    Image ID:       docker-pullable://bitnami/mariadb@sha256:6d502d77a21812fa3a38021f48b968000cd6b13a5572e331e2261931dfad73c4
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 29 Apr 2020 21:00:11 -0700
      Finished:     Wed, 29 Apr 2020 21:00:14 -0700
    Ready:          False
    Restart Count:  7
    Liveness:       exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'xxxxx-mariadb'>  Optional: false
      MARIADB_USER:           bn_wordpress
      MARIADB_PASSWORD:       <set to the key 'mariadb-password' in secret 'xxxxx-mariadb'>  Optional: false
      MARIADB_DATABASE:       bitnami_wordpress
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fp42v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-xxxxx-mariadb-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      xxxxx-mariadb
    Optional:  false
  default-token-fp42v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fp42v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From                          Message
  ----     ------                  ----                 ----                          -------
  Normal   Scheduled               <unknown>            default-scheduler             Successfully assigned default/xxxxx-mariadb-0 to pool-zmt6vkhg6-dgrq
  Warning  FailedAttachVolume      13m                  attachdetach-controller       Multi-Attach error for volume "pvc-92912110-980b-4955-8ceb-abdbe9717f11" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulAttachVolume  13m                  attachdetach-controller       AttachVolume.Attach succeeded for volume "pvc-92912110-980b-4955-8ceb-abdbe9717f11"
  Normal   Pulling                 13m                  kubelet, pool-zmt6vkhg6-dgrq  Pulling image "docker.io/bitnami/mariadb:10.3.22-debian-10-r92"
  Normal   Pulled                  13m                  kubelet, pool-zmt6vkhg6-dgrq  Successfully pulled image "docker.io/bitnami/mariadb:10.3.22-debian-10-r92"
  Normal   Created                 11m (x5 over 13m)    kubelet, pool-zmt6vkhg6-dgrq  Created container mariadb
  Normal   Started                 11m (x5 over 13m)    kubelet, pool-zmt6vkhg6-dgrq  Started container mariadb
  Normal   Pulled                  11m (x4 over 12m)    kubelet, pool-zmt6vkhg6-dgrq  Container image "docker.io/bitnami/mariadb:10.3.22-debian-10-r92" already present on machine
  Warning  BackOff                 3m2s (x49 over 12m)  kubelet, pool-zmt6vkhg6-dgrq  Back-off restarting failed container
```

**Comment by andresbono** [comment]
Hi @johnsiciliano, thanks for opening this issue. Can you tell us the specific versions of the chart that you are using to do the upgrade (from and to)? With that information, we will try to reproduce your issue.

**Comment by tancou** [comment]
Hi,
I have the exact same problem.
If I want to upgrade one value of the config, the mariadb doesn't start again.

I'm deploying it on rancher, I use the bitnami catalog.
For example, when I deploy thoses values :
```---
  allowOverrideNone: "true"
  ingress: 
    enabled: "true"
    hostname: "wp.k8s.example.fr"
  mariadb: 
    db: 
      password: "dbpassword"
    master: 
      persistence: 
        storageClass: "longhorn"
    rootUser: 
      password: "roopassword"
  persistence: 
    accessMode: "ReadWriteMany"
    storageClass: "nfs"
  replicaCount: "3"
  service: 
    externalTrafficPolicy: "Local"
  wordpressEmail: "email@example.com"
  wordpressPassword: "wppassword"
  wordpressScheme: "http"
  wordpressUsername: "user"
```
Everything works fine.
Then, I upgrade anything, for instance `replicaCount: "5"`, I get stuck with
```
mariadb 19:36:01.08 
mariadb 19:36:01.08 Welcome to the Bitnami mariadb container
mariadb 19:36:01.08 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 19:36:01.08 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 19:36:01.08 Send us your feedback at containers@bitnami.com
mariadb 19:36:01.08 
mariadb 19:36:01.09 INFO  ==> ** Starting MariaDB setup **
mariadb 19:36:01.12 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 19:36:01.12 INFO  ==> Initializing mariadb database
mariadb 19:36:01.13 INFO  ==> Using persisted data
mariadb 19:36:01.14 INFO  ==> Running mysql_upgrade
mariadb 19:36:01.14 INFO  ==> Starting mariadb in background
mariadb 19:36:02.17 INFO  ==> Stopping mariadb
```

I tried with a separated mariadb (the one in this catalog).
I set up a mariadb master + slave, then the wordpress, using "an external database".

First try : works perfectly.

Then upgrade something on the mariadb. Could not start again :
Master log spammed with :
`[Warning] Access denied for user 'wordpress'@'10.42.3.242' (using password: YES)`
Slave stuck with
```
mariadb 19:47:20.43 Welcome to the Bitnami mariadb container
mariadb 19:47:20.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 19:47:20.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 19:47:20.43 Send us your feedback at containers@bitnami.com
mariadb 19:47:20.44 
mariadb 19:47:20.44 INFO  ==> ** Starting MariaDB setup **
mariadb 19:47:20.49 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 19:47:20.50 INFO  ==> Initializing mariadb database
mariadb 19:47:20.51 INFO  ==> Using persisted data
mariadb 19:47:20.52 INFO  ==> Running mysql_upgrade
mariadb 19:47:20.53 INFO  ==> Starting mariadb in background
mariadb 19:47:21.56 INFO  ==> Stopping mariadb
```

**Comment by javsalgar** [comment]
Hi,

Please note that when you upgrade the chart, you need to re-specify the passwords again or they will get automatically re-generated, causing issues with the persistence. This has been a problem from some time and I definitely think we should add a validation to all of our charts so an upgrade without re-setting the password is not allowed.

**Comment by tancou** [comment]
I understand the behaviour, but I specify my current password when I upgrade, and my password still get randomized.

**Comment by johnsiciliano** [comment]
Hi, the version of the chart I'm using is 9.2.2. 
I believe this is the issue, it generated a new root password as soon as it updated mariadb.
This creates such a headache because it clobbers my installations.
Could there be a feature to set the root mariadb password using init-script if a certain value in the chart is defined?

**Comment by andresbono** [comment]
Hi @tancou, @johnsiciliano, thanks for your feedback.

We are going to work on improving the user experience during the upgrade, but for now, the passwords need to be specified on every update.

**Comment by andresbono** [comment]
Can you share how are you specifying the password values, @tancou? Please, do not share the real value of the secrets.

**Comment by tancou** [comment]
Hi @andresbono 

I am using Rancher to deploy the helm. Here a screen of my actual configuration :

![image](https://user-images.githubusercontent.com/919768/81473452-f072d680-91fe-11ea-8602-d265f3081e9f.png)

I sent a message to the Rancher team because I'm not sure but the problem could be related to their form parser, causing the password randomised when I upgrade.

**Comment by andresbono** [comment]
Thanks, @tancou, please, let us know about any news you may have.

**Comment by vinayagg** [comment]
I am facing same issue. Here are my bash logs.
In short
- first deployment works (I passed in password)
- I check password, it does not match supplied password
- I uninstall and reinstall, pods do not come up
- I uninstall, delete PVCs and reinstall, pods do come up

I am not able to find a way to reattaching existing PVCs
------------------------------------------------------------------------------
$ COUNT=3

$ kubectl create ns $COUNT
namespace/3 created

#let's deploy it and pass in a password
$ helm install --namespace $COUNT --set mariadb.db.password=password mdb$COUNT .
NAME: mdb3
LAST DEPLOYED: Mon May 25 23:05:39 2020
NAMESPACE: 3
STATUS: deployed
...

$ kubectl --namespace $COUNT get pods
NAME                    READY   STATUS    RESTARTS   AGE
mdb3-mariadb-master-0   1/1     Running   0          101s
mdb3-mariadb-slave-0    1/1     Running   0          101s

$ kubectl get secret --namespace 3 mdb3-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode
CUuALpcUr3
# This does not match our passed in password

$ helm uninstall --namespace $COUNT mdb$COUNT
release "mdb3" uninstalled

$ kubectl --namespace $COUNT get pvc
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-mdb3-mariadb-master-0   Bound    pvc-0e0fe601-263b-4bb1-952d-05e89177d560   8Gi        RWO            standard       4m22s
data-mdb3-mariadb-slave-0    Bound    pvc-1b25f6b3-89dc-408c-9379-6fe0cb96cfaf   8Gi        RWO            standard       4m22s

$ kubectl --namespace $COUNT get pods
No resources found in 3 namespace.

# let's deploy again with same password and keeping PVCs. pods do not come up
$ helm install --namespace $COUNT --set mariadb.db.password=password mdb$COUNT .
NAME: mdb3
LAST DEPLOYED: Mon May 25 23:10:33 2020
NAMESPACE: 3
STATUS: deployed
...

$ kubectl --namespace $COUNT get pods -w
NAME                    READY   STATUS              RESTARTS   AGE
mdb3-mariadb-master-0   0/1     ContainerCreating   0          6s
mdb3-mariadb-slave-0    0/1     ContainerCreating   0          6s
mdb3-mariadb-slave-0    0/1     Running             0          10s
mdb3-mariadb-slave-0    0/1     Error               0          13s
mdb3-mariadb-slave-0    0/1     Running             1          14s
mdb3-mariadb-slave-0    0/1     Error               1          16s
mdb3-mariadb-master-0   0/1     Running             0          18s

$ helm uninstall --namespace $COUNT mdb$COUNT
release "mdb3" uninstalled

# now lets delete the PVCs and deploy again, pods will come up
$ kubectl --namespace $COUNT delete pvc data-mdb$COUNT-mariadb-master-0 &
[1] 683
$ persistentvolumeclaim "data-mdb3-mariadb-master-0" deleted
kubectl --namespace $COUNT delete pvc data-mdb$COUNT-mariadb-slave-0 &
[2] 730
[1]   Done                    kubectl --namespace $COUNT delete pvc data-mdb$COUNT-mariadb-master-0
$ persistentvolumeclaim "data-mdb3-mariadb-slave-0" deleted

[2]+  Done                    kubectl --namespace $COUNT delete pvc data-mdb$COUNT-mariadb-slave-0
$ kubectl --namespace $COUNT get pvc
No resources found in 3 namespace.
$ kubectl --namespace $COUNT get pods
No resources found in 3 namespace.

$ helm install --namespace $COUNT --set mariadb.db.password=password mdb$COUNT .
NAME: mdb3
LAST DEPLOYED: Mon May 25 23:12:06 2020
NAMESPACE: 3
STATUS: deployed

$ kubectl --namespace $COUNT get pods -w
NAME                    READY   STATUS              RESTARTS   AGE
mdb3-mariadb-master-0   0/1     ContainerCreating   0          6s
mdb3-mariadb-slave-0    0/1     ContainerCreating   0          6s
mdb3-mariadb-master-0   0/1     Running             0          24s
mdb3-mariadb-slave-0    0/1     Running             0          24s
mdb3-mariadb-master-0   1/1     Running             0          55s
mdb3-mariadb-slave-0    1/1     Running             0          74s
$
