### ISSUE TITLE
Kafka provisioning fails due to hard-coded wait-for-port timeout being too short.

### ISSUE THREAD

**Issue by emily2005** [bitnami/charts#24724]
### Name and Version

bitnami/kafka/templates/provisioning/job.yaml

### What is the problem this feature will solve?

Currently, Kafka is not able to install properly due to the timeout being hard-coded in the chart to 120 seconds here:
https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/provisioning/job.yaml#L67

We have kafka configured in a 3 node replicaset and we are running a gke autopilot cluster. The main issue is that autopilot does not provision node capacity until a workload is created and it takes longer than 2 minutes to provision a node. Being able to increase this value beyond 120 seconds would solve this issue for us. 

### What is the feature you are proposing to solve the problem?

Ideally, the timeout should be a variable that can be passed from the values if it needs to be longer than 120 seconds. 

### What alternatives have you considered?

Here is a link to our code where we worked around the issue:

https://gitlab.com/dsri-org/infra/gcp/dyff/dyff-kafka/-/blob/main/main.tf?ref_type=heads#L124

**Comment by FraPazGal** [comment]
I agree with your proposal @emily2005 and thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
