### ISSUE TITLE
Access denied for user 'root'@'localhost' Error while installing a master-slave MySQL cluster

### ISSUE THREAD

**Issue by StevenModin** [bitnami/charts#24727]
### Name and Version

bitnami/mysql 10.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. run cmd `helm install mysql-cluster -f values.yaml bitnami/mysql`
then mysql-cluster-secondary-1 in a loop of initailization
2. run `kubectl describe po/mysql-cluster-secondary-1` but nothing is wrong
3. run `kubectl describe po/mysql-cluster-secondary-0` and see error `mysqladmin: connect to server at 'localhost' failed error: 'Access denied for user 'root'@'localhost' (using password: YES)'`
4. use `kubectl logs` to see mysql-cluster-secondary-0, find there are all warings but no error
use `kubectl logs` to see mysql-cluster-secondary-1, show message: `Error from server (BadRequest): container "mysql" in pod "mysql-cluster-secondary-1" is waiting to start: PodInitializing`

I guess it's secondary-0's error that make secondary-1 fall in the initailization loop, what can I try to locate error?

### Are you using any custom parameters or values?

values.yaml
``` yaml
auth:
  rootPassword: "123456"

primary:
  persistence:
    size: 4Gi
    enabled: true

secondary:
  replicaCount: 2
  persistence:
    size: 4Gi
    enabled: true
    
architecture: replication
```

### What do you see instead?

p.s. the process of `kubectl get po --watch`
```console
$ kubectl get po --watch
NAME                        READY   STATUS    RESTARTS   AGE
mysql-cluster-primary-0     0/1     Running   0          18s
mysql-cluster-secondary-0   0/1     Running   0          18s
mysql-cluster-primary-0     0/1     Running   0          25s
mysql-cluster-primary-0     1/1     Running   0          25s
mysql-cluster-secondary-0   0/1     Running   0          35s
mysql-cluster-secondary-0   1/1     Running   0          35s
mysql-cluster-secondary-1   0/1     Pending   0          0s
mysql-cluster-secondary-1   0/1     Pending   0          4s
mysql-cluster-secondary-1   0/1     Init:0/1   0          4s
```
### Additional information
```console
$ kubectl version
Client Version: v1.28.7+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7+k3s1
```

**Comment by carrodher** [comment]
It seems the issue is produced by a mismatch between the password used in the values and the one provided in a previous deployment. Did you deploy the Helm chart previously in the same namespace using the same name? That could produce the mentioned mismatch between a new password used in the values and the one stored in the PV/PVC.

**Comment by StevenModin** [comment]
> It seems the issue is produced by a mismatch between the password used in the values and the one provided in a previous deployment. Did you deploy the Helm chart previously in the same namespace using the same name? That could produce the mentioned mismatch between a new password used in the values and the one stored in the PV/PVC.

I tried to install again by deleting all PVs, PVCs and namespaces, and choose a new password, but the matter still exists.

**Comment by carrodher** [comment]
Unfortunately I am not able to reproduce the issue, see below the steps I followed to deploy the Helm chart from scratch:
```console
$ cat values.yaml
auth:
  rootPassword: "123456"

primary:
  persistence:
    size: 4Gi
    enabled: true

secondary:
  replicaCount: 2
  persistence:
    size: 4Gi
    enabled: true

architecture: replication

$ helm install mysql-cluster -f values.yaml bitnami/mysql
$ kubectl get secret --namespace default mysql-cluster -o jsonpath="{.data.mysql-root-password}" | base64 -d
123456
$ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
mysql-cluster-primary-0     1/1     Running   0          3m39s
mysql-cluster-secondary-0   1/1     Running   0          3m39s
mysql-cluster-secondary-1   1/1     Running   0          2m27s
```

**Comment by StevenModin** [comment]
> Unfortunately I am not able to reproduce the issue, see below the steps I followed to deploy the Helm chart from scratch:
> 
> ```
> $ cat values.yaml
> auth:
>   rootPassword: "123456"
> 
> primary:
>   persistence:
>     size: 4Gi
>     enabled: true
> 
> secondary:
>   replicaCount: 2
>   persistence:
>     size: 4Gi
>     enabled: true
> 
> architecture: replication
> 
> $ helm install mysql-cluster -f values.yaml bitnami/mysql
> 
> $ kubectl get secret --namespace default mysql-cluster -o jsonpath="{.data.mysql-root-password}" | base64 -d
> 123456
> 
> $ kubectl get pods
> NAME                        READY   STATUS    RESTARTS   AGE
> mysql-cluster-primary-0     1/1     Running   0          3m39s
> mysql-cluster-secondary-0   1/1     Running   0          3m39s
> mysql-cluster-secondary-1   1/1     Running   0          2m27s
> ```

You are right, I tried every thing as far as I know and finally choose to create a new cluster for test. It worked out in the end. So the matter cause by the cluster but the charts. The cluster is behaving normally, but it's not. So I'll try to fix my previous cluster then. Sorry to bother you and wish you a happy day!

**Comment by Jonny023** [comment]
```yaml
secondary:
  startupProbe:
    enabled: false
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
```
