### ISSUE TITLE
How to upgrade bitnami kafka from 20.0.0 to 27.1.2

### ISSUE THREAD

**Issue by shifeichen** [bitnami/charts#24725]
### Name and Version

bitnami/kafka 20.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install bitnami/kafka 20.0.0

2. fetch bitnami/kafka 27.1.2 and unarchive it 

3. change  templates/broker/statefulset.yaml
         name: {{ printf "%s-broker" (include "common.names.fullname" .) }} => name: {{ printf "%s" (include "common.names.fullname" .) }}

4. change values.yaml
   broker.replicaCount=3
   zookeeper.enabled=true
   zookeeper.replicaCount=3

5. upgrade kafka

6. errors
```
**helm -n kafka-test upgrade kafka .**

Error: UPGRADE FAILED: execution error at (kafka/templates/broker/statefulset.yaml:42:38): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'sasl.interbroker.password' must not be empty, please add '--set sasl.interbroker.password=$INTER_BROKER_PASSWORD' to the command. To get the current value:

        export INTER_BROKER_PASSWORD=$(kubectl get secret --namespace "kafka-test" kafka-user-passwords -o jsonpath="{.data.inter-broker-password}" | base64 -d)
```

### Are you using any custom parameters or values?
```
   broker.replicaCount=3
   zookeeper.enabled=true
   zookeeper.replicaCount=3
```
### What is the expected behavior?

upgrade succeed

### What do you see instead?
```
Error: UPGRADE FAILED: execution error at (kafka/templates/broker/statefulset.yaml:42:38): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'sasl.interbroker.password' must not be empty, please add '--set sasl.interbroker.password=$INTER_BROKER_PASSWORD' to the command. To get the current value:

        export INTER_BROKER_PASSWORD=$(kubectl get secret --namespace "kafka-test" kafka-user-passwords -o jsonpath="{.data.inter-broker-password}" | base64 -d)
```

**Comment by shifeichen** [comment]
I haven't set password for 20.0.0.

**Comment by carrodher** [comment]
[Here](https://github.com/bitnami/charts/tree/main/bitnami/kafka#upgrading) you can find the instructions and notable changes for the different major versions.
In any case, you need to follow the steps that appears in the console to upgrade from one version to another in order to retrieve the random password set during the first deployment and then use it during the upgrade.

**Comment by dVerhees** [comment]
@carrodher I'm running into the same issue as @shifeichen In my deployment of Kafka the connection was set to use `PLAINTEXT` protocol, and was never set to `SASL` in past upgrades, therefore the secret containing username/password doesn't exist. 
As far as I can read, the `PLAINTEXT` protocol is still supported, but if it's not, where can I find a guide to migrate from `PLAINTEXT` to `SASL` ?

**Comment by carrodher** [comment]
It depends on the version you are upgrading from. Since version 24.0.0 all listeners are configured with protocol `SASL_PLAINTEXT` by default, but `PLAINTEXT` is still supported.

In versions [24.0.0](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400) and [28.0.0](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2800) there were some big changes, you need to take into account the upgrade notes when upgrading to those versions.

**Comment by dVerhees** [comment]
I understand your comment about needing to check for major changes when upgrading and taking those into account, however when you say `PLAINTEXT` is still supported, I wouldn't expect the error about `sasl.interbroker.password` to be raised when the protocol is set to `PLAINTEXT` but only when the protocol contains `SASL_*`

**Comment by andresbono** [comment]
We will need more information in order to get a better understanding of the specific upgrading issue: Original and upgraded version, values passed for each of the versions...

**Comment by arik-pillar** [comment]
I have the same issue. I'm deploying kafka within a k8s cluster with `PLAINTEXT` and I didn't set any password.
I don't require any authentication for my cluster. Is there any workaround?
