### ISSUE TITLE
[bitnami/wordpress] Mount a config map as wp-config.php

### ISSUE THREAD

**Issue by lwj5** [bitnami/charts#2473]
**Which chart**:
wordpress

**Is your feature request related to a problem? Please describe.**
Any changes to wordpress helm chart values do not get reflected in **wp-config.php**, this leads to a false perception where one might think that the values are updated but are actually out of sync.

In actual fact, updates to wp-config.php must be done manually by editing the file directly on the filesystem and this will ultimately lead to (once again) the helm chart values to be out of sync with **wp-config.php**.

**Describe the solution you'd like**
We generate a config map using a .yaml template defining a **wp-config.php** key with the value containing the actual configs. And mount this config map key in /bitnami/worpress/wp-config.php.

We will use the values from the existing values:
wordpressTablePrefix
wordpress.databaseHost
wordpress.databasePort
wordpress.databaseName
wordpress.databaseUser
.etc to populate the config map

Two additional helm chart variable will be provided 
configDefine - to populate define( 'key', 'value' );
`configDefine.AUTOMATIC_UPDATER_DISABLED = true` will insert `define( 'AUTOMATIC_UPDATER_DISABLED', true ) `

configBlock - to populate wp-config with a chunk of text

**Describe alternatives you've considered**
Nil

I'm looking for comments on this method. If there is enough support, I can create a PR.

**Comment by carrodher** [comment]
Thanks for this idea, I think is a good feature to add to the WordPress chart, we are happy to help you if you want to create a PR. As you can see in the [contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) it should be easy to start collaborating with this repository.

Please, don't hesitate to ask any questions.

**Comment by lwj5** [comment]
@carrodher I've added the PR, however, the bitnami wordpress image requires chmod to complete which prevents this from working. See https://github.com/bitnami/bitnami-docker-wordpress/issues/240

**Comment by carrodher** [comment]
Thanks for the PR and the detailed information regarding the issue with the image and the permissions.
We'll review both (issue and PR), usually within a business day, so we can work together to have it working.

**Comment by lwj5** [comment]
Refer to #2491
