### ISSUE TITLE
[ Thanos] ObjstoreConfig type FILESYSTEM not working with 14.0.2 release

### ISSUE THREAD

**Issue by RishabhKumarGupta** [bitnami/charts#24733]
### Name and Version

bitnami/thanos 14.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Use the newest thanos helm chart version 14.0.1
Configure objstoreConfig

### Are you using any custom parameters or values?

```
  objstoreConfig: |-
    type: FILESYSTEM
    config:
      directory: "/local-persistance/"
```

### What is the expected behavior?

objstoreConfig needs to work here as given in the offical documentation and was working before 14.0.1 release : https://thanos.io/tip/thanos/storage.md/#:~:text=type%3A%20FILESYSTEM%0Aconfig%3A%0A%20%20directory%3A%20%22%22%0Aprefix%3A%20%22%22

### What do you see instead?

Error: template: lightops-obs-metrics/charts/thanos/templates/storegateway/statefulset-sharded.yaml:54:44: executing "lightops-obs-metrics/charts/thanos/templates/storegateway/statefulset-sharded.yaml" at <include "thanos.objstoreConfig" .>: error calling include: template: lightops-obs-metrics/charts/thanos/templates/_helpers.tpl:126:18: executing "thanos.objstoreConfig" at <.Values.objstoreConfig>: can't evaluate field Values in type int

**Comment by dragoangel** [comment]
Just to note issue not in content of `objstoreConfig`, it's in the scope.

**Comment by dragoangel** [comment]
Will create PR that fixes this things with config annotations, thare is a lot of places where they done in different manners... Will align them all

**Comment by dragoangel** [comment]
Created PR, @RishabhKumarGupta you can form my repo to test. I could reproduce your issue, and tested locally, my fix should solve your issue.
