### ISSUE TITLE
Missing '/' causes failure of readiness probe

### ISSUE THREAD

**Issue by ricardo-noyolalozano** [bitnami/charts#24742]
### Name and Version

bitnami/keycloak 19.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Change the `httpRelativePath` in the values file and the readiness probe will fail

### Are you using any custom parameters or values?

Just change `.Values.httpRelativePath` to anything else and it will fail

### What is the expected behavior?

That the readiness probe not fail

### What do you see instead?

Readiness probe failure

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
