### ISSUE TITLE
Can't initial MySQL by using helm  

### ISSUE THREAD

**Issue by wuxiaoxin730** [bitnami/charts#24752]
### Name and Version

bitnami/mysql:10.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. K8S env, 3 nodes
2. exec command: helm install <mysql-name> bitnami/mysql

### What is the expected behavior?

MySQL pod runs well

### What do you see instead?

1. Pod running is not successful, whose status is "CrashLoopBackOff"
2. There is a warning in k8s logs: "The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file"
3. pv and pvc were  created and works well, configmap has my.cnf file

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
