### ISSUE TITLE
Wrong database collation in Redmine Chart

### ISSUE THREAD

**Issue by ad-si** [bitnami/charts#2475]
**Which chart**:
Redmine  4.1.1 

**Describe the bug**
Does not allow importing issues with Unicode characters as the database is probably set up with the wrong UTF-8 collation. More information: https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**To Reproduce**
1. `helm install redmine`
2. Try to create an issue which contains a 4 byte Unicode character.

**Expected behavior**
It should be possible to use all Unicode characters.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
You are right. Currently we are not enabling utf8mb4 by default on any of our containers, but we have an internal task for changing that. However it could take some time until that is achieved.

In the meantime it should be possible to do it manually. However, we tried converting the database to utf8mb4 and it did not work, so we will look into this and come back once we have more information on what could be happening.

**Comment by marcosbc** [comment]
@ad-si We are working on improving the Bitnami MySQL and MariaDB environment variables to support setting collations and character sets.

Once implemented, you would set the below environment variables in Docker Compose installations:

      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_CHARACTER_SET=utf8mb4

After released we will look into implementing a compatible change for the MariaDB and MySQL charts to support those options, so you can use them in your Helm chart.

**Comment by wimtiaz14** [comment]
help to correct my code on update picture @wimtiaz14

**Comment by dani8art** [comment]
Also, now that it was implemented in the containers, you could take the advantages of `extraEnvVars` in `bitnami/mariadb` chart and modify the collations. Please try to add this to your helm deployments.

```console
  --set mariadb.extraEnvVars[0].name=MARIADB_COLLATE,mariadb.extraEnvVars[0].value=utf8mb4_unicode_ci
  --set mariadb.extraEnvVars[1].name=MARIADB_CHARACTER_SET,mariadb.extraEnvVars[1].value=utf8mb4
```

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
