### ISSUE TITLE
[bitnami/redis-cluster] Metrics won't start if usePasswordFile = true

### ISSUE THREAD

**Issue by rechandler12** [bitnami/charts#2476]
**Which chart**:
 redis-cluster:2.0.13

**Describe the bug**
Metrics container after deployed has error:
```
/bin/bash: /opt/bitnami/redis/secrets/redis-password: No such file or directory
```

In file `redis-statefulset.yaml` lines 219-223 is:
```
          volumeMounts:
            {{- if .Values.usePasswordFile }}
            - name: redis-password
              mountPath: /secrets/
            {{- end }}
```

I think this should be:
```
          volumeMounts:
            {{- if .Values.usePasswordFile }}
            - name: redis-password
              mountPath: /opt/bitnami/redis/secrets/
            {{- end }}
```

**To Reproduce**
1. Create values.yaml with content:
```
password: xxx
usePasswordFile: true
```
2. Install chart with helm install -f https://raw.githubusercontent.com/bitnami/charts/master/bitnami/redis-cluster/values-production.yaml -f values.yaml redis bitnami/redis-cluster
3.  See metrics container log

**Expected behavior**
No error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, thanks for creating this issue reporting the described bug, as you have a possible solution, would you like to create a PR solving it? If not we will do it on our side, but just asking as you already provide the workaround.
