### ISSUE TITLE
[bitnami/redis] Issue with Slave persistence with Azure file PV

### ISSUE THREAD

**Issue by gopal229** [bitnami/charts#2478]
**Which chart**:
Redis, version 10.5.7

**Describe the bug**
I m trying to deploy the Redis chart with Sentinel enabled in AKS with Azure files as PV. The chart deployment was fine, but i see issue with Slave persistence, the rewriteaof process seems to be crashing.

**To Reproduce**
1. Create Storage class 
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
```
2. Update the storage class in `values-production.yaml`
3. Install Helm chart
4. Check the logs in slave PODs of redis-service container,  the slave persistence doesn't seem to work properly. 
```
1:S 01 May 2020 05:49:51.161 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
1:S 01 May 2020 05:49:51.181 # Error trying to rename the temporary AOF file temp-rewriteaof-bg-373.aof into appendonly.aof: Permission denied
1:S 01 May 2020 05:49:51.293 * Background append only file rewriting started by pid 374
1:S 01 May 2020 05:49:51.345 * AOF rewrite child asks to stop sending diffs.
374:C 01 May 2020 05:49:51.345 * Parent agreed to stop sending diffs. Finalizing AOF...
374:C 01 May 2020 05:49:51.345 * Concatenating 0.00 MB of AOF diff received from parent.
374:C 01 May 2020 05:49:51.364 * SYNC append only file rewrite performed
374:C 01 May 2020 05:49:51.365 * AOF rewrite: 0 MB of memory used by copy-on-write
1:S 01 May 2020 05:49:51.393 * Background AOF rewrite terminated with success
1:S 01 May 2020 05:49:51.398 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
1:S 01 May 2020 05:49:51.413 # Error trying to rename the temporary AOF file temp-rewriteaof-bg-374.aof into appendonly.aof: Permission denied
1:S 01 May 2020 05:49:51.524 * Background append only file rewriting started by pid 384
1:S 01 May 2020 05:49:51.592 * AOF rewrite child asks to stop sending diffs.
384:C 01 May 2020 05:49:51.592 * Parent agreed to stop sending diffs. Finalizing AOF...
384:C 01 May 2020 05:49:51.592 * Concatenating 0.00 MB of AOF diff received from parent.
384:C 01 May 2020 05:49:51.653 * SYNC append only file rewrite performed
384:C 01 May 2020 05:49:51.654 * AOF rewrite: 0 MB of memory used by copy-on-write
1:S 01 May 2020 05:49:51.724 * Background AOF rewrite terminated with success
1:S 01 May 2020 05:49:51.729 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
1:S 01 May 2020 05:49:51.754 # Error trying to rename the temporary AOF file temp-rewriteaof-bg-384.aof into appendonly.aof: Permission denied
1:S 01 May 2020 05:49:51.865 * Background append only file rewriting started by pid 385
1:S 01 May 2020 05:49:51.928 * AOF rewrite child asks to stop sending diffs.
385:C 01 May 2020 05:49:51.928 * Parent agreed to stop sending diffs. Finalizing AOF...
385:C 01 May 2020 05:49:51.928 * Concatenating 0.00 MB of AOF diff received from parent.
385:C 01 May 2020 05:49:51.951 * SYNC append only file rewrite performed
385:C 01 May 2020 05:49:51.952 * AOF rewrite: 0 MB of memory used by copy-on-write
1:S 01 May 2020 05:49:51.965 * Background AOF rewrite terminated with success
1:S 01 May 2020 05:49:51.970 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
1:S 01 May 2020 05:49:51.986 # Error trying to rename the temporary AOF file temp-rewriteaof-bg-385.aof into appendonly.aof: Permission denied
1:S 01 May 2020 05:49:52.096 * Background append only file rewriting started by pid 386
1:S 01 May 2020 05:49:52.148 * AOF rewrite child asks to stop sending diffs.
386:C 01 May 2020 05:49:52.148 * Parent agreed to stop sending diffs. Finalizing AOF...
386:C 01 May 2020 05:49:52.148 * Concatenating 0.00 MB of AOF diff received from parent.
386:C 01 May 2020 05:49:52.211 * SYNC append only file rewrite performed
386:C 01 May 2020 05:49:52.212 * AOF rewrite: 0 MB of memory used by copy-on-write
```
**Expected behavior**
No errors in slave redis-service container logs.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"1fc58d90cc4bc569394d9a882522adcb99fbaa57", GitTreeState:"clean", BuildDate:"2020-04-03T15:20:08Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional context**

The issue is happening only with Azure file, i dont see any issue when Azure Disk is used

**Comment by javsalgar** [comment]
Hi,

Could you try deploying the chart with this value enabled?

```
volumePermissions:
  enabled: true
```

This would force some chmod operations that may solve the issue.

**Comment by gopal229** [comment]
@javsalgar Tried it, still same error in slave logs. I don't see these errors in master POD.

**Comment by andresbono** [comment]
Hi @gopal229, did you try to exec into the pods (master and slaves) to see if there are differences in the permissions and ownership of the `/data` directory? It is strange that the issue only happens in slave pods.

**Comment by gopal229** [comment]
Hi @andresbono , I have checked the permissions of /data directory. The permission of directory are same across master and slave PODS

 kubectl exec -it redis-service-master-0 -- bash
Defaulting container name to redis-service.
Use 'kubectl describe pod/redis-service-master-0 -n gg-redis-test' to see all of the containers in this pod.
I have no name!@redis-service-master-0:/$ ls -lrt /data/
total 1
-rwxrwxrwx 1 root 1001   0 May  2 05:21 appendonly.aof
-rwxrwxrwx 1 root 1001 176 May  2 05:22 dump.rdb
I have no name!@redis-service-master-0:/$ exit
exit

 kubectl exec -it redis-service-slave-0 -- bash
Defaulting container name to redis-service.
Use 'kubectl describe pod/redis-service-slave-0 -n gg-redis-test' to see all of the containers in this pod.
I have no name!@redis-service-slave-0:/$ ls -lrt /data
total 1
-rwxrwxrwx 0 root 1001   0 May  2 05:21 appendonly.aof
-rwxrwxrwx 1 root 1001 175 May  2 05:21 dump.rdb
I have no name!@redis-service-slave-0:/$ exit
exit

kubectl exec -it redis-service-slave-1 -- bash
Defaulting container name to redis-service.
Use 'kubectl describe pod/redis-service-slave-1 -n gg-redis-test' to see all of the containers in this pod.
I have no name!@redis-service-slave-1:/$ ls -lrt /data/
total 1
-rwxrwxrwx 0 root 1001   0 May  2 05:22 appendonly.aof
-rwxrwxrwx 1 root 1001 176 May  2 05:22 dump.rdb
-rwxrwxrwx 1 root 1001  92 May  8 06:33 temp-rewriteaof-113466.aof
I have no name!@redis-service-slave-1:/$

**Comment by rafariossaa** [comment]
Hi,
  Could it be that that kind of storage does not support renaming? 
  Could you try to do it manually in the pod ? or to `touch` the file ? Just to check which operations (Read, write) are allowed on the file.

**Comment by gopal229** [comment]
Thanks @rafariossaa . It looks like Azure files don't support rename/move operations.

I have no name!@redis-service-slave-0:/data$ mv temp-rewriteaof-bg-5250.aof appendonly.aof
mv: cannot move 'temp-rewriteaof-bg-5250.aof' to 'appendonly.aof': Permission denied

**Comment by gopal229** [comment]
The reason for choosing Azure files is, the Azure managed disk doesn't support zone redundancy.
In the case of AZ failure, the Redis persistent disk will be lost and the data can't be recovered

**Comment by andresbono** [comment]
> Thanks @rafariossaa . It looks like Azure files don't support rename/move operations.
> 
> I have no name!@redis-service-slave-0:/data$ mv temp-rewriteaof-bg-5250.aof appendonly.aof
> mv: cannot move 'temp-rewriteaof-bg-5250.aof' to 'appendonly.aof': Permission denied

Thanks for confirming it, @gopal229. Is it the same with the master pod, right? As you mentioned that you weren't seeing errors in master nodes.

**Comment by gopal229** [comment]
@andresbono  I haven't tried rename operation on master POD. But as I said earlier, I didn't see any errors in the master POD logs.

**Comment by rafariossaa** [comment]
HI @gopal229,
  Thanks for sharing. 
  The problem here seems to be how redis work, It renames files and that is not compatible with Azure files.
