### ISSUE TITLE
[bitnami/airflow] User specified in auth section of values is not created

### ISSUE THREAD

**Issue by Nickmman** [bitnami/charts#24781]
### Name and Version

bitnami/airflow 18.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

* Deploy helm chart with `auth.existingSecret` set to a secret containing all the credentials required
* Try to access web UI with the credentials (defaults to `admin` username)
* Obtain invalid credentials page

### What is the expected behavior?

Airflow can be accessed with user credentials

### What do you see instead?

No user is being created, even checking the database yields that no user exists.

### Additional information

I'm creating this issue with the assumption that the chart deployment will create a user given that the `auth` section exists in the chart.

**Comment by javsalgar** [comment]
Hi!

Could you confirm that you do not have leftover PVCs from previous installations?

**Comment by Nickmman** [comment]
Hi @javsalgar, I can confirm that the PVC is freshly created upon deploying the helm chart. I just now redeployed it, deleted the PVC and found this line in the airflow-web logs on startup:
` {override.py:868} WARNING - No user yet created, use flask fab command to do it.`

**Comment by Nickmman** [comment]
Checking the database manually, it seems that effectively no user is created:
```
bitnami_airflow=> select * from ab_user;
 id | first_name | last_name | username | password | active | email | last_login | login_count | fail_login_count | created_on | changed_on | created_by_fk | changed_by_fk
----+------------+-----------+----------+----------+--------+-------+------------+-------------+------------------+------------+------------+---------------+---------------
(0 rows)
```

**Comment by FraPazGal** [comment]
Hello @Nickmman, I've been able to reproduce your issue on my side. As detailed in the secret template, both the fernet and secret key need to be base64-encoded and be of a minimum length (32-length keys worked for me):

```
$ kubectl create secret generic test-secret --from-literal=airflow-password="test_air_pass" --from-literal=airflow-fernet-key="WkFHU2ppOXhVNWtnMDJocFpCN01lSVZkdHd3Q205NzM=" --from-literal=airflow-secret-key="UzNPUXFKMDlQQ1VtZDhzNVo0RGpnSndPUjBDMzJmMXA="
```

Could you retry taking the above into account?

**Comment by Nickmman** [comment]
Hi @FraPazGal, I did a fresh redeploy (removing the postgresql PVC so that the database is created from scratch), using 32-length for the secret keys you mentioned and the user is still not being created. The same log output from the web container about no user created is also still present.

**Comment by FraPazGal** [comment]
Hi @Nickmman, not sure where your issue lays. I have deployed the chart latest version with the following commands without issue:

```
$ kubectl create secret generic test-secret --from-literal=airflow-password="test_air_pass" --from-literal=airflow-fernet-key="WkFHU2ppOXhVNWtnMDJocFpCN01lSVZkdHd3Q205NzM=" --from-literal=airflow-secret-key="UzNPUXFKMDlQQ1VtZDhzNVo0RGpnSndPUjBDMzJmMXA="
$ helm install airflow bitnami/airflow --set auth.existingSecret=test-secret
```

Could you try using the exact same commands? If the problem persist, please check whether the airflow-web deployment is really using the created secret.

**Comment by Nickmman** [comment]
@FraPazGal I got it working, I misunderstood you when you said to create base64 secrets, I didn't realize you meant the actual value to be encoded. It's all working now, thank you!
