### ISSUE TITLE
[bitnami/kafka] Can't install kafka/consul with skaffold+helm.

### ISSUE THREAD

**Issue by Cloud956** [bitnami/charts#24814]
### Name and Version

bitnami/kafka 21.0.0, bitnami/consul 10.9.8

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Initialize minikube (v1.32.0)
2. Create a skaffold.yaml with the following:

<pre>
profiles:
  - name: pre
    patches:
      - op: remove
        path: /build
    portForward:
      - resourceType: service
        resourceName: consul-headless
        port: 8500
        localPort: 30085
      - resourceType: service
        resourceName: kafka-0-external
        port: 9094
        localPort: 30094
    deploy:
      helm:
        releases:
          - name: kafka
            remoteChart: bitnami/kafka
            version: 21.0.0
            createNamespace: true
            namespace: hospital
            wait: true
            setValueTemplates:
              persistence.enabled: false
              zookeeper.persistence.enabled: false
              externalAccess.enabled: true
              externalAccess.service.type: NodePort
              externalAccess.service.domain: localhost
              externalAccess.service.nodePorts[0]: 30094
              serviceAccount.create: true
              autoCreateTopicsEnable: true
              deleteTopicEnable: true
          - name: consul
            remoteChart: bitnami/consul
            version: 10.9.8
            namespace: hospital
            createNamespace: true
            setValueTemplates:
              gossipKey: InMUqtEp8HWXySVIvF1K1vDq
              replicaCount: 1
              persistence.enabled: "false"
              metrics.enabled: "false"
            wait: true
</pre>

4. Run `skaffold deploy -p pre`

### Are you using any custom parameters or values?

Not that I know of, except the ones I mentioned above.

### What is the expected behavior?

Kafka and consul should deploy.

### What do you see instead?

![Screenshot 2024-03-25 at 14 47 20](https://github.com/bitnami/charts/assets/24865274/2f48b9c7-ccbc-4411-addf-4b9d6b94a223)

Upon investigating the minikube service the pods fail with the following:

![Screenshot 2024-04-02 at 14 29 18](https://github.com/bitnami/charts/assets/24865274/4cec1070-d469-4157-b81d-074fff37df48)

The pods keep restarting and crashing forever.

### Additional information

This deployment used to work before (22.03.2024) and when ran on 25.03.2024 stopped working with the above-mentioned errors. Upgrading the versions, for example kafka to 22.0.0, makes the deployment work but I need v21 to work. I have already attempted reinstalling everything + factory resetting my device.

**Comment by javsalgar** [comment]
Hi!

What do you exactly need from version v21 that is not present in v22?

**Comment by Cloud956** [comment]
Hello,

It is just that a lot of the already existing compoments are using v21 and
it is working on other devices/pipelines. Upgrading everything might be a
bigger task than a fix for my problem (hopefully).

**Comment by javsalgar** [comment]
I see that we're already in kafka version 28 😅 , so this goes a bit beyond the support we can offer. An exec format error normally is related to architecture issues, like running arm64 containers in a amd64 machine (or vice versa). Could you check if something like this could be happening?

**Comment by Cloud956** [comment]
I know that my device is arm64. How could I check if the container is a different machine? Is that not handled automatically by docker/minikube?

**Comment by Cloud956** [comment]
I have resolved the issue. Newer versions of docker (25.0.0+) can no longer deploy older charts. This issue affects more than just kafka and consul charts, but most definitely versions of bitnami/kafka before 22 and consul 10.9.8. Downgrading docker to <25 solves the deployment issues.
