### ISSUE TITLE
sealed-secrets: missing port for metrics

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#24837]
### Name and Version

bitnami/sealed-secrets: 2.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. The metrics are provided on port 8081 - but this misses a service-entry and then the service-monitor should be changed accordingly.

### What is the expected behavior?

servicemonitor should make prometheus scrape metrics

### What do you see instead?

No metrics are scraped

**Comment by carrodher** [comment]
Thanks for letting us know, there is already a PR under review that should fix this issue, see https://github.com/bitnami/charts/pull/24653
