### ISSUE TITLE
[bitnami/wordpress] Appears that "global.storageClass" overrides more specific storageClass settings

### ISSUE THREAD

**Issue by aragilar** [bitnami/charts#24845]
### Name and Version

wordpress:21.0.10 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Setting `global.storageClass` to a dummy fallback value (e.g. "test-storage-class") overrides the storageClass used in more specific places (e.g. for wordpress, `mariadb.primary.persistence.storageClass` and `persistence.storageClass`). I would expect global to act as a fallback, rather than override the values. 

### What is the expected behavior?

I would expect to be able to use a fallback value in global, so as to be able to catch any cases where the default storage class is being used, and direct them to a more appropriate class. 

### What do you see instead?

My settings of `mariadb.primary.persistence.storageClass` and `persistence.storageClass` are ignored, and `global.storageClass` is used instead.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. The logic is set here: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_storage.tpl#L16

Would you like to submit a PR changing the default behavior?

**Comment by aragilar** [comment]
https://github.com/bitnami/charts/pull/24863 created with the smallest change I think will fix this.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
