### ISSUE TITLE
[bitnami/metallb] CRD for BGPPeer refers to webhook-service for conversions, but chart installs metallb-webhook-service

### ISSUE THREAD

**Issue by asagi4** [bitnami/charts#24846]
### Name and Version

bitnami/metallb 5.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Observe the webhook service:
```
# oc get service -n metallb-system
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
metallb-webhook-service   ClusterIP   172.30.191.52   <none>        443/TCP   530d
```

And the CRD has this: https://github.com/bitnami/charts/blob/a2a6eabda632d12ded2b2d0959c44aca2b73fab8/bitnami/metallb/templates/crds/crds.yaml#L264

### Are you using any custom parameters or values?

```
controller:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
```

### What is the expected behavior?

The webhook should refer to the correct service.

### What do you see instead?

I see constant spam like this in kube-apiserver logs:
```
E0403 08:38:29.207764      16 cacher.go:469] cacher (bgppeers.metallb.io): unexpected ListAndWatch error: failed to list metallb.io/v1beta1, Kind=BGPPeer: conversion webhook for metallb.io/v1beta2, Kind=BGPPeer failed: Post "https://webhook-service.metallb-system.svc:443/convert?timeout=30s": service "webhook-service" not found; reinitializing...
```

### Additional information

Upstream seems to use just "webhook-service". Perhaps this was a mistake when syncing templates from upstream?

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. So it should be a matter of changing the reference from webhook-service to metallb-webhook-service. Would you like to submit a PR with the change?

**Comment by javsalgar** [comment]
Hi! I created this PR to fix the CRD https://github.com/bitnami/charts/pull/24930
