### ISSUE TITLE
[bitnami/rabbitmq] stateful set bug

### ISSUE THREAD

**Issue by bjoernw** [bitnami/charts#2485]
**Which chart**:
Latest Rabbitmq

**Describe the bug**
`Error: UPGRADE FAILED: YAML parse error on rabbitmq/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 58: block sequence entries are not allowed in this context`

**To Reproduce**
Install the chart

**Version of Helm and Kubernetes**:
helm 3, k8s 1.14

**Comment by bjoernw** [comment]
version "6.25.5" does not have this issue so it must have been introduced in yesterday's commit.

**Comment by juan131** [comment]
Hi @bjoernw 

I was not able to reproduce the issue using the default values. Check:

```console
$ helm install rabbitmq bitnami/rabbitmq --version 6.25.5
$ helm upgrade rabbitmq bitnami/rabbitmq
$ helm history rabbitmq
REVISION	UPDATED                 	STATUS    	CHART          	APP VERSION	DESCRIPTION
1       	Tue May  5 08:21:05 2020	superseded	rabbitmq-6.25.5	3.8.3      	Install complete
2       	Tue May  5 08:21:59 2020	deployed  	rabbitmq-6.25.7	3.8.3      	Upgrade complete
```

Could you please share what values.yaml are you using? Thanks in advance.

**Comment by mboutet** [comment]
Hi, the problem arises when resources are set for the volume permissions init container like so:
```
  volumePermissions:
    enabled: true
    resources:
      requests:
        memory: 64Mi
        cpu: 5m
      limits:
        memory: 64Mi
        cpu: 50m
```

**Comment by juan131** [comment]
Hi @bjoernw 

That's a known issue when you deploy the chart on K8s clusters that don't have full support for SecurityContext(s).

By default, the PVCs should respect the security context and adapt the volumes that are mounted in the container based on the `fsGroup` property. However, some K8s distributions don't use that information and, therefore, we need to use the "volumePermissions" init container to adapt them.
