### ISSUE TITLE
[bitnami/common] Duplicate code to return apiVersion for ingress resources

### ISSUE THREAD

**Issue by Shiftmaj** [bitnami/charts#24864]
### Name and Version

bitnami/common 1.3.2+

### What architecture are you using?

None

### What steps will reproduce the bug?

In [this file](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_capabilities.tpl), [lines 96 to 102](https://github.com/bitnami/charts/blob/e7e570a89e70501de5c26acf49e1037862a6422d/bitnami/common/templates/_capabilities.tpl#L96) seems to be duplicate of [lines 103 to 109](https://github.com/bitnami/charts/blob/e7e570a89e70501de5c26acf49e1037862a6422d/bitnami/common/templates/_capabilities.tpl#L103):

```
{{/*
Return the appropriate apiVersion for ingress.
*/}}
{{- define "common.capabilities.ingress.apiVersion" -}}
{{- if .Values.ingress -}}
{{- if .Values.ingress.apiVersion -}}
{{- .Values.ingress.apiVersion -}}
{{- else if semverCompare "<1.14-0" (include "common.capabilities.kubeVersion" .) -}}
{{- print "extensions/v1beta1" -}}
{{- else if semverCompare "<1.19-0" (include "common.capabilities.kubeVersion" .) -}}
{{- print "networking.k8s.io/v1beta1" -}}
{{- else -}}
{{- print "networking.k8s.io/v1" -}}
{{- end }}
{{- else if semverCompare "<1.14-0" (include "common.capabilities.kubeVersion" .) -}}
{{- print "extensions/v1beta1" -}}
{{- else if semverCompare "<1.19-0" (include "common.capabilities.kubeVersion" .) -}}
{{- print "networking.k8s.io/v1beta1" -}}
{{- else -}}
{{- print "networking.k8s.io/v1" -}}
{{- end -}}
{{- end -}}
```

### What do you see instead?

Remove duplicate code

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
