### ISSUE TITLE
[Nginx/nginx ingress] :Unable to access my subdirectory hosted content

### ISSUE THREAD

**Issue by abhi7788** [bitnami/charts#2488]
**Which chart**:
Nginx/Nginx Ingress Controller

**Describe the bug**
I am using nginx bitnami image to host site. We are using following kind of structure 

/app/html/commonfolder/folder1/index.html
/app/html/commonfolder/folder2/index.html
/app/html/commonfolder/folder3/index.html

When i exposed this setup with a nodeport service (lets call it service2) and i am able to access my content with following link

<Podip>:<port>/commonfolder/folder1/index.html
<Podip>:<port>/commonfolder/folder2/index.html
<Podip>:<port>/commonfolder/folder3/index.html

After this configuration i tied with a existing ingress controller which is already routing ankther existing app service i.e. service 1 and used following config

Host : mysite.com
  Path:/
  Service: service1
  Path:/commonfolder/
  Seevice: service2

Now when try to test this with following url

Mysite.com/commonfolder/folder1/index.html
Mysite.com/commonfolder/folder2/index.html
Mysite.com/commonfolder/folder3/index.html

It keep on redirecting me to the nginx welcome home page i.e. /app/html/index.html

I went through some threads but not able to figure out if i am missing any config or some other setting

**Expected behavior**

Mysite.com/commonfolder/folder1/index.html will route me to the content hosted in folder1
While Mysite.com/commonfolder/folder2/index.html
Will route me to content hosted in folder2

**Comment by abhi7788** [comment]
I was able to find the resolution for this issue. The fix was simple; in the ingress configuration i was using following variable
nginx.ingress.kubernetes.io/rewrite-target:/
Which was redirecting all my traffic to root. Simply removing this config helped me to fix the issue. It seems like post 0.22 version we have to define explicit Capture group for the substring in url. You can more details here : 
https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

Closing this issue now

**Comment by miguelaeh** [comment]
Thank you very for sharing your solution @abhi7788!!
