### ISSUE TITLE
bitnami/kube-prometheus unable to configure prometheus, alertmanager, sidecar in tls mode

### ISSUE THREAD

**Issue by sakeebshaikh74** [bitnami/charts#24894]
### Name and Version

name: kube-prometheus sources: - https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus version: 8.28.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Can you please suggest how to enable TLS for each component? 

### Are you using any custom parameters or values?

no

### What is the expected behavior?

prometheus, alertmanager, sidecar should be in TLS 

### What do you see instead?

I do not see the components in TLS mode

**Comment by rafariossaa** [comment]
Hi,
  Have you tried enabling TLS with ingress (`XXXXXXX.ingress.tls`) ?

**Comment by sakeebshaikh74** [comment]
Hi @rafariossaa ,

Yes I have tried this flags but unable to enable TLS.

certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.prometheus.ingress.hostname }}
    ## You can use the prometheus.ingress.secrets parameter to create this TLS secret or relay on cert-manager to create it
    ##
    tls: true
    ## @param prometheus.ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
    ##
    selfSigned: true

**Comment by sakeebshaikh74** [comment]
@rafariossaa can you please help here

**Comment by rafariossaa** [comment]
Sorry for the delay, I am taking a look.

**Comment by rafariossaa** [comment]
Did you enable ingress too ?
You should see the secrets created and ingress components should be using them.

**Comment by sakeebshaikh74** [comment]
yes i enabled the ingress and see the secrets but not working in tls mode

**Comment by rafariossaa** [comment]
could you provide the settings you are using ? I would like to reproduce it on my side.
