### ISSUE TITLE
Airflow cannot perform initial repositories clone

### ISSUE THREAD

**Issue by MarijnMB** [bitnami/charts#24935]
### Name and Version

bitnami/airflow 18.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Same as https://github.com/bitnami/charts/issues/17543

### Are you using any custom parameters or values?

git repo for dags, same as https://github.com/bitnami/charts/issues/17543

### What do you see instead?

Nothing at all: clone-repositories container immediately errors without ever showing an error message in the logs.

### Additional information

If I change the git.clone.args to `args: [ "-ec", "sleep 500000" ]` (to keep it running) and enter a shell in the container, the user as which I'm logged in is "I have no name!" and the `./opt/bitnami/scripts/libfs.sh` command (first line of the default entrypoint) gives a permissions error. `whoami` shows the user has UID 1001, which doesn't exist in the git container.

**Comment by dunn** [comment]
I've recently (in the past 3 or 4 days?) begun seeing this in the `git-clone-repository` container for the nginx chart as well.

**Comment by dunn** [comment]
Rolling back the Nginx chart to 15.12.2 fixes the issue, so it arose sometime in between then and now (16.0.2).

**Comment by MarijnMB** [comment]
My guess would be this:

```
- image: docker.io/bitnami/git:2.43.2-debian-12-r2
+ image: docker.io/bitnami/git:2.44.0-debian-12-r2
```

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

During the past weeks, we have been performing some changes to improve the security of our container and Helm charts, see https://github.com/bitnami/charts/issues/24251. For instance, in the case of Airflow it's detailed at the releases notes for the new major: https://github.com/bitnami/charts/tree/main/bitnami/airflow#to-1800 (same for NGINX but with version 16.0.0)

**Comment by MarijnMB** [comment]
@carrodher I fully understand the benefits of running as non-root, but that doesn't help me here. The issue is not the permissions on the local directory (since there is none, this is a clean installation), but the non-existent user in the git containers.

**Comment by jotamartos** [comment]
Hi, 

We reproduced the issue and we are working on a fix. This issue is caused by the latest security updates we introduced in the chart. 

Sorry for the inconvenience.

**Comment by jotamartos** [comment]
PR is created here. You can test the changes if you want to 😄

**Comment by jamesmedice** [comment]
once git tries to clone error :
fatal: could not read Username for 'https://source.developers.google.com': No such device or address
