### ISSUE TITLE
[bitnami/elasticsearch] how change default data path "/bitnami/elasticsearch/data"

### ISSUE THREAD

**Issue by StefanSa** [bitnami/charts#2495]
**Which chart**:
elasticsearch

Hi there,
thanks for the helpful and good charts. We have three bare metal hosts.
Here a volume has already been mounted from the SAN storage in the local file system.
My question about the default data path:
How do i change the default data path according to e.g.
`/data-san/k8s/bitnami/elasticsearch/data`

thx

**Comment by miguelaeh** [comment]
Hi @StefanSa ,
If I understood your question correctly, you want to modify the data path inside the pod.
To do that you will need to modify a bit the Helm Chart and add the environment variable `ELASTICSEARCH_DATADIR` to the ES pod, then you can provide your custom path into that variable.
You can see that variable in the image code: https://github.com/bitnami/bitnami-docker-elasticsearch/blob/3168424a7b445077ceda2235f4161eb55e62ad7b/7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L152

**Comment by StefanSa** [comment]
Hi @miguelaeh 
Thanks the answer was helpful

**Comment by fcstring31** [comment]
@miguelaeh do you have a more specific example of how to do this? I provided a custom value for `ELASTICSEARCH_DATADIR` during the helm chart install, and the pods took that value for the variable, but the data path is still `/bitnami/elasticsearch/data` in the pods' config file.

**Comment by miguelaeh** [comment]
Hi @fcstring31 ,
The env var has been changed in a refactorization of the image and it is now called `ELASTICSEARCH_DATA_DIR`. You can find it here: https://github.com/bitnami/bitnami-docker-elasticsearch/blob/a89bbd64fd2c2a35e1d559a89935a36d74ed4e44/7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L155

**Comment by fcstring31** [comment]
Thanks for getting back so quickly @miguelaeh ! And thanks for pointing that out.
Still no luck getting the path set. I'm providing a supplemental file in the chart install that contains this:
```
extraEnvVars:
- name: ELASTICSEARCH_DATA_DIR
  value: /mnt/azure/elasticsearch
```
Is that the right way to pass in a value for that env var?

**Comment by miguelaeh** [comment]
Hi @fcstring31 ,
Yes, it should be passed in that way. I think you probably would need to change the mount points in the helm chart.
https://github.com/bitnami/charts/blob/4f0976fdbd80be747818174e8dc0ceabc67dfaa8/bitnami/elasticsearch/templates/data-statefulset.yaml#L82

**Comment by fcstring31** [comment]
@miguelaeh I haven't... 
I'm using Azure Files, so I'm passing that into `extraVolumes` and `extraVolumeMounts`. And then I set `ELASTICSEARCH_DATA_DIR` to the mount path as I showed before.

I was thinking by setting the data path, that `data` volume would just go unused. Do I also need to to override that? And so my Azure Files volume becomes the `data` volume instead of an "extra" volume?

**Comment by joancafom** [comment]
Hi @fcstring31,

If you are using the `extraVolumes` and `extraVolumeMounts` properties, you should set the mountpath in them so as to match the value of the `ELASTICSEARCH_DATA_DIR` property. I think that should be enough in order for it to work. If it still doesn't, can you please provide me with the values you are using to try to bound the issue?

Another option (I don't know if it [works for you](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv)) would be using the property `existingClaim`. This way, you can avoid changing the default path 😁.

Thanks!
