### ISSUE TITLE
[bitnami/minio] Permission denied at startup with multiple drives per node

### ISSUE THREAD

**Issue by Aegdesil** [bitnami/charts#24998]
### Name and Version

bitnami/minio 14.1.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploying minio in distributed mode, with 4 disks per node.

### Are you using any custom parameters or values?

Using multiple drives per node:

```
  statefulset:
    drivesPerNode: 4
```

### What is the expected behavior?

The pods should start without errors.

### What do you see instead?

The pods crash at startup with this log:
```
/opt/bitnami/scripts/libminio.sh: line 364: /bitnami/minio/data/.root_user: Permission denied
```

### Additional information

I see that the /bitnami/minio/data folder does not exist, since I am using multiple disks, this is the content of /bitnami/minio:
```
I have no name!@minio-1:/opt/bitnami/minio-client$ ls -la /bitnami/minio/     
total 24
drwxr-xr-x 6 root root 4096 Apr  3 00:42 .
drwxr-xr-x 3 root root 4096 Apr  3 00:42 ..
drwxrwsr-x 8 root 1001 4096 Apr  3 00:42 data-0
drwxrwsr-x 8 root 1001 4096 Apr  3 00:42 data-1
drwxrwsr-x 8 root 1001 4096 Apr  3 00:42 data-2
drwxrwsr-x 8 root 1001 4096 Apr  3 00:42 data-3
```

The script is trying to create a new folder in /bitnami/minio, but since this folder belongs to the root user it does not have the correct permissions.
Setting volumePermissions.enabled to true does not solve the issue as it only changes the permissions of the data-* folders, not the parent.

I think the environment variable MINIO_DATA_DIR is set to `persistence.mountPath` by mistake, it should be `persistence.mountPath-0` when using multiple disks.
The script that is causing the error uses this environment variable to determinate where the files should be written [here](https://github.com/bitnami/containers/blob/main/bitnami/minio/2024/debian-12/rootfs/opt/bitnami/scripts/libminio.sh#L364).

**Comment by fadjar340** [comment]
I have same issue..
It's occurred since I want to use version 14.1.x, upgraded from 13.8.x.

Assistance will be appreciate...

Regards,
Fadjar

**Comment by andresbono** [comment]
Thank you for raising this issue, PR #25301 should fix the permission denied. Feel free to review it.
