### ISSUE TITLE
ServicePort does not update correctly for ingress

### ISSUE THREAD

**Issue by Matthew-Hicks-CrowdAI** [bitnami/charts#25015]
### Name and Version

bitnami/minio:14.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

try and update the `ingress.servicePort` and it will not change

### Are you using any custom parameters or values?

Yes, I'm setting the servicePort to minio-api

### What is the expected behavior?

the ingress will point to minio-api port

### What do you see instead?

it stays pointed to minio-console

**Comment by Matthew-Hicks-CrowdAI** [comment]
i was able to easily fix it by changing out the "minio console" on line 33 of templates/ingress.yaml to ( .Values.ingress.servicePort )

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
