### ISSUE TITLE
[bitnami/redis-cluster] Readme inconsistency over parameter name to use

### ISSUE THREAD

**Issue by iomarcovalente** [bitnami/charts#2503]
**Which chart**:
redis-cluster:latest

**Describe the bug**
The readme states:
`Similarly, you can add extra init containers using the initContainers parameter.`

Although from the Values file and the template I can only see referenced `.Values.extraInitContainers`.

Find inconsistent line here: https://github.com/bitnami/charts/blame/master/bitnami/redis-cluster/README.md#L377

**To Reproduce**
N/A

This needs to be updated accordingly with the correct value: `extraInitContainers`

**Comment by iomarcovalente** [comment]
Also I am quite confused as how the block below works - if it works at all, as I tried to plug that into my chart and doesn't work.
```
        {{- if .Values.extraInitContainers }}
        {{- range $key, $value := .Values.extraInitContainers }}
        - name: "{{ $key }}"
        {{- toYaml $value | nindent 12 }}
        {{- end }}
        {{- end }}
```
I found the syntax below more straightforward - and it works
```
      {{- if .Values.extraInitContainers }}
{{ tpl (toYaml .Values.extraInitContainers) . | indent 6 }}
      {{- end }}
```

**Comment by marcosbc** [comment]
@iomarcovalente You're right about the `initContainers` typo, and the other change looks good as well. Would you mind sending a PR fixing those issues? We would be happy to review it!
