### ISSUE TITLE
[opencart] OPENCART_ENABLE_HTTPS is not working for the administration pages

### ISSUE THREAD

**Issue by kirilovvv** [bitnami/charts#25038]
### Name and Version

bitnami/opencart 18.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm installing bitnami/opencart version 18.0.0 on a k8s cluster but when I try to access the admin interface I receive the following errors:
![Screenshot 2024-04-08 at 15 46 26](https://github.com/bitnami/charts/assets/103365560/9e324fbc-d1cb-4d2e-a462-dcc8e1075fb6)
Due to the following errors the page is not fully loaded, also the **login** fails with wrong credentials

Steps to reproduce:
1. Install the chart with the provided configuration
2. Open https://<host>/administration

### Are you using any custom parameters or values?

values.yaml:
```yaml
opencartHost: "<host>"
opencartEnableHttps: true
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: <host>
  annotations: { cert-manager.io/issuer: "<issuer>" }
  tls: true
```

### What is the expected behavior?

To successfully load the administration pages and be able to login.

### What do you see instead?

Partial Login page (all the static content cannot be fetched) and the Login itself fails.

### Additional information

Currently, the administration config file (`/bitnami/opencart/administration/config.php`) looks like this:
```php
<?php
// APPLICATION
define('APPLICATION', 'Admin');

// HTTP
define('HTTP_SERVER', 'http://<host>/administration/');
define('HTTP_CATALOG', 'http://<host>/');
// DIR
define('DIR_OPENCART', '/opt/bitnami/opencart/');
define('DIR_APPLICATION', DIR_OPENCART . 'administration/');
define('DIR_SYSTEM', DIR_OPENCART . 'system/');
define('DIR_EXTENSION', DIR_OPENCART . 'extension/');
define('DIR_IMAGE', DIR_OPENCART . 'image/');
define('DIR_STORAGE', '/bitnami/opencart_storage/');
define('DIR_CATALOG', DIR_OPENCART . 'catalog/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');

// DB
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', '<db_host>');
define('DB_USERNAME', 'bn_opencart');
define('DB_PASSWORD', '<db_password>');
define('DB_DATABASE', 'bitnami_opencart');
define('DB_PREFIX', 'oc_');
define('DB_PORT', '3306');

// OpenCart API
define('OPENCART_SERVER', 'https://www.opencart.com/');
define('HTTPS_SERVER', 'https://<host>/administration/');
define('HTTPS_CATALOG', 'https://<host>/');
```

After modifying `HTTP_SERVER` and `HTTP_CATALOG` configurations to point to HTTPS the page successfully loaded and I was able to login.
Modifications:
```
define('HTTP_SERVER', 'https://<host>/administration/');
define('HTTP_CATALOG', 'https://<host>/');
```

**Comment by kirilovvv** [comment]
Also I found that the HTTP_SERVER configuration for the client area (in /bitnami/opencart/config.php) is set to use **https** instead of http. That was fixed with bitnami/containers#53359

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kirilovvv** [comment]
bitnami/containers#64995 is merged so I am closing this issue
