### ISSUE TITLE
[bitnami/redis | bitnami/minio] Problems with "common.labels.standard" updating redis from 17.2 to 19.0

### ISSUE THREAD

**Issue by VPoshelyuk** [bitnami/charts#25049]
### Name and Version

bitnami/redis 19.0.2, bitnami/minio 4.1.11

### What architecture are you using?

None

### What steps will reproduce the bug?

1.- Updating redis package from 17.2.0 to 19.0.2
2.- Running helm
3.- Generates an error that didn't appear in previously used version:
> Error: template: x/charts/redis/templates/master/serviceaccount.yaml:13:14: executing "x/charts/redis/templates/master/serviceaccount.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: x/charts/minio/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: x/charts/minio/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:100: [debug] template: x/charts/redis/templates/master/serviceaccount.yaml:13:14: executing "x/charts/redis/templates/master/serviceaccount.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: x/charts/minio/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: x/charts/minio/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Same output as before updating the version(no errors)

### What do you see instead?

> Error: template: x/charts/redis/templates/master/serviceaccount.yaml:13:14: executing "x/charts/redis/templates/master/serviceaccount.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: x/charts/minio/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: x/charts/minio/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name

### Additional information

I'm pretty much sure the root cause is the same as for this issue: https://github.com/bitnami/charts/issues/18933 since I had to change the repo I'm exporting from with the recent changes to bitnami structure but in my case minio have to stay pinned, was wondering if there is any other way around it other than bumping minio?

**Comment by juan131** [comment]
Hi @VPoshelyuk 

Please help me understand your problem. Your chart is using both Redis & MinIO as sub-charts but one of them is pointing to a version that uses an old version `bitnami/common` library, is that right?

- Could you share your `Chart.lock` if that's the case?
- Why MinIO has to stay pinned in your case?

**Comment by VPoshelyuk** [comment]
Yes, that's right 
Here is what we have in Chart.lock:
```
  - name: minio
    version: "4.1.11"
    repository: https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami
    condition: minio.enabled
  - name: redis
    version: "19.0.2"
    repository: https://charts.bitnami.com/bitnami
```  
And minio have to stay pinned since they changed their licensing at some point, so going up a major version will be an issue for us because of that (we went away from using minio in the future versions of our app, but still have to support this old one that has it)

**Comment by juan131** [comment]
Hi @VPoshelyuk 

You can still use the latest Bitnami chart version and use and older image version which license suits your needs. For instance, using a **values.yaml** such as the one below and replacing `XXX` with a version that works for you:

```yaml
minio:
  image:
    registry: docker.io
    repository: bitnami/minio
    tag: XXX
```

That said, the chart version you're using is very old `4.x.x` vs `14.x.x` (actual one) so it's very likely that the image you're using isn't compatible with the new chart.

Another alternative would be installing separately MinIO using the Bitnami chart and de-associate it as a dependency of your chart. You'll have to enable parameters to indicate your app how to connect to the MinIO instance that would be "external" to the chart now. Similar to what we do in charts such as the ones below:

- https://github.com/bitnami/charts/blob/main/bitnami/spring-cloud-dataflow/values.yaml#L2014-L2046

**Comment by VPoshelyuk** [comment]
We've tried the first option already, unfortunately, yes, the 10 major version gap played the role and it's incompatible with the latest chart.   

Going to give the second option a go. 
Thanks a lot for your help, @juan131
