### ISSUE TITLE
[bitnami/redis-cluster]appendonly is true in redis-cluster

### ISSUE THREAD

**Issue by zhaoanliu** [bitnami/charts#2505]
**Which chart**:
redis-cluster:latest

**Describe the bug**
After deploy the chart, I found appendonly is true for all nodes in redis-cluster, even though it is set to no in the config map bitnami/redis-cluster/templates/configmap.yaml

**To Reproduce**
1. Deploy redis-cluster
2. Check file /opt/bitnami/redis/etc/redis.conf
3. The appendonly is true in file redis.conf. 
4. Also confirmed /bitnami/redis/data/appendonly.aof is growing

**Expected behavior**
AOF should be disabled by default, or at least been able to set in the chart values file.

**Comment by zhaoanliu** [comment]
I double checked, and the redis cluster nodes are running without the config files:
"The server is running without a config file"

**Comment by andresbono** [comment]
Thanks for creating this issue, @zhaoanliu. We are going to check what are the possibilities to implement a way to make AOF configurable.

Related: https://github.com/bitnami/bitnami-docker-redis/issues/159

**Comment by zhaoanliu** [comment]
I found the problem and created the following pull request: https://github.com/bitnami/bitnami-docker-redis-cluster/pull/1

It is just to comment out the following line in startup setting script libredis.sh:

# redis_conf_set appendonly yes

**Comment by andresbono** [comment]
Thanks, @zhaoanliu, we saw your PR, we left a comment:

> We have some changes planned to be applied and may conflict with your change.
