### ISSUE TITLE
[bitnami/nginx] Changed the default type from LoadBalancer to ClusterIP

### ISSUE THREAD

**Issue by kometen** [bitnami/charts#25085]
### Name and Version

bitnami/nginx

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the helm chart.

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

Default to ClusterIP.

### What do you see instead?

Default to LoadBalancer.

### Additional information

Please review this PR to change the default type to ClusterIP. https://github.com/bitnami/charts/pull/25084

**Comment by javsalgar** [comment]
Hi!

Thanks for the PR! I'll let the conversation continue in the PR
