### ISSUE TITLE
[bitnami/mongodb] How can I run oldest version of MongoDB? Like 4.X.X all old images totally broken

### ISSUE THREAD

**Issue by nowost** [bitnami/charts#25100]
### Name and Version

bitnami/mongodb

### What architecture are you using?

None

### What steps will reproduce the bug?

Try to install any old image, tag 4.x.x I got tonn errors (Authentification error, mongo.conf not fount error and others), but fresh images installation is good. how i can run MongoDB 4.x.x and have not broken startup scripts?

### What do you see instead?

errors

**Comment by javsalgar** [comment]
Hi!

We're currently supporting MongoDB version 7.x.x, so I'm afraid that very old images such as 4.x.x are not supported with the newest version of our charts. My advice would be to go to mongodb chart branch 10.x.x, which used Mongodb branch 4.x.x and give it a try. Note that this is not supported by the team. 

https://github.com/bitnami/charts/commit/ed25600c2b16f06a9287be65326412fd10afd607
