### ISSUE TITLE
redis-cluster with redis-go has a empty ip node

### ISSUE THREAD

**Issue by AlecBruns** [bitnami/charts#25107]
### Name and Version

bitnami/redis-cluster:10.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Using `redis-go v9.4.0`, I am unable to stay connected to the cluster within minikube. Puts and Scans fail eventually do to an empty ip node.

I created the chart by using the following command 
```
helm upgrade --install redis redis/redis-cluster --set "usePassword=false"
```

After logging outputs from the Redis commands and failures in my go app, I was able to see one of the Nodes being used was labeled as: `Redis<:0 db:0` as opposed to a Node with an actual ip/port: `Redis<10.244.5.110:6379 db:0>`.

When trying to connect to that empty node, a connection refused error is thrown. Is there a workaround?

I have tried passing the cluster service name as well as each individual pod via the headless service.

### Are you using any custom parameters or values?

--set "usePassword=false"

### What is the expected behavior?

A stable connection to the Redis Cluster

### What do you see instead?

```
2024/04/10 14:00:41.387272 Scanning on master: Redis<10.244.5.110:6379 db:0>
2024/04/10 14:00:41.387295 Scanning on master: Redis<:0 db:0>
2024/04/10 14:00:41.387536 ERROR: Redis Key Scan Failed: dial tcp :0: connect: connection refused
```

**Comment by carrodher** [comment]
It seems you are using a non-bitnami Helm chart (redis/redis-cluster), please open an issue in the project in charge of that solution.

**Comment by AlecBruns** [comment]
@carrodher Sorry, it is a bitnami helm chart. I add the repo via `helm repo add redis https://charts.bitnami.com/bitnami

**Comment by AlecBruns** [comment]
Didn't realize this would be reopened, already made a new ticket with more info? https://github.com/bitnami/charts/issues/25119
