### ISSUE TITLE
[bitnami/mariadb-galera] mariadb-galera on OpenShift 

### ISSUE THREAD

**Issue by Rockbob89** [bitnami/charts#25111]
### Name and Version

bitnami/mariadb-galera 11.3.2

### What architecture are you using?

None

### What steps will reproduce the bug?

The installation fails on OpenShift 4.13 (error should be happening on any OpenShift version because the charts initContainer is forcing a non-viable securityContext. Even when using the forced securityContext adaption via `global.compatibility.openshift.adaptSecurityContext: force`.

The Pod and Container securityContext are getting set correctly (and should be working on OpenShift) but sadly the initContainers securityContext settings aren't touched by the aforementioned adaptSecurityContext trigger.

Therefore there's just one step to reproduce:

`helm upgrade --install mariadb-galera bitnami/mariadb-galera -f values.yaml`

### Are you using any custom parameters or values?
values.yaml
```yaml
global:
  compatibility:
    openshift: 
      adaptSecurityContext: force	
fullnameOverride: mariadb-galera
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
podManagementPolicy: OrderedReady
replicaCount: 3
```

### What is the expected behavior?

The expected behaviour is that the pods are getting spawned/scheduled.

### What do you see instead?

```console
$ kubectl -n dev-maria-db get statefulsets.apps 
NAME             READY   AGE
mariadb-galera   0/3     12m


$ kubectl -n dev-maria-db get pods
No resources found in dev-maria-db namespace.

$ kubectl -n dev-maria-db describe statefulsets.apps mariadb-galera
Name:               mariadb-galera
Namespace:          dev-maria-db
CreationTimestamp:  Wed, 10 Apr 2024 16:43:20 +0200
[...]
Events:
  Type     Reason        Age                   From                    Message
  ----     ------        ----                  ----                    -------
  Warning  FailedCreate  7m54s (x18 over 13m)  statefulset-controller  create Pod mariadb-galera-0 in StatefulSet mariadb-galera failed error: pods "mariadb-galera-0" is forbidden: unable to validate against any security context constraint: [provider anyuid: .initContainers[0].seLinuxOptions.level: Invalid value: "": must be s0:c26,c15, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/preserve-logs-symlinks]: Forbidden: seccomp may not be set, pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/mariadb-galera]: Forbidden: seccomp may not be set, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 1001: must be in the ranges: [1000680000, 1000689999], provider restricted-v2: .initContainers[0].seLinuxOptions.level: Invalid value: "": must be s0:c26,c15, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

### Additional information

As said, the securityContext on a Pod & Container level are getting set correctly:

(extract from `[...] get statefulsets.app mariadb-galera -o yaml`)
```yaml
[...]
container:
  [...]
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
         - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
       type: RuntimeDefault
```

**Comment by javsalgar** [comment]
Hi!

Did you try with the latest version of the chart. I believe that the seLinuxOptions issue is fixed.

**Comment by Rockbob89** [comment]
Hey!

Sorry for the late reply, I was working on another project.

I just ran a test with the newest version `CHART VERSION: 13.0.0` & `APP VERSION: 11.3.2`, once without any custom values and another time setting `global.compatibility.openshift.adaptSecurityContext: force`

Sadly both tries resulted in the same error as before. No Pod's beeing scheduled because of securityContext problems.

**Comment by migruiz4** [comment]
Hi @Rockbob89,

Thank you for reporting this issue! 

I have submitted this PR (https://github.com/bitnami/charts/pull/25578) which I think should fix this issue.

Looks like the `preserve-logs-symlinks` initContainer was not considering the value `global.compatibility.openshift.adaptSecurityContext: force`, therefore causing this issue.

**Comment by migruiz4** [comment]
Hi @Rockbob89,

Could you please try using the latest version 13.0.1 and let us know if the issue persists?
