### ISSUE TITLE
[bitnami/redis-cluster] Redis Cluster with redis-go gets connection errors

### ISSUE THREAD

**Issue by AlecBruns** [bitnami/charts#25119]
### Name and Version

bitnami/redis-cluster:10.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Using redis-go v9.4.0, I am unable to stay connected to the cluster within minikube. Puts and Scans fail eventually do to an empty ip node.

I created the chart by using the following command

```
helm repo add redis https://charts.bitnami.com/bitnami

helm upgrade --install redis redis/redis-cluster --set "usePassword=false"
```
The connection host/port used is `redis-redis-cluster:6397` which matches the service name:

```
redis-redis-cluster            ClusterIP   10.101.65.40     <none>        6379/TCP                        8m17s
redis-redis-cluster-headless   ClusterIP   None             <none>        6379/TCP,16379/TCP              8m17s
```

After logging outputs from the Redis commands and failures in my go app, I was able to see one of the Nodes being used was labeled as: `Redis<:0 db:0` as opposed to a Node with an actual ip/port: `Redis<10.244.5.110:6379 db:0>`.

When trying to connect to that empty node, a connection refused error is thrown. Is there a workaround?

I have tried passing the cluster service name as well as each individual pod via the headless service.

### Are you using any custom parameters or values?

--set "usePassword=false"

### What is the expected behavior?

A stable connection to the Redis Cluster

### What do you see instead?

```
2024/04/10 14:00:41.387272 Scanning on master: Redis<10.244.5.110:6379 db:0>
2024/04/10 14:00:41.387295 Scanning on master: Redis<:0 db:0>
2024/04/10 14:00:41.387536 ERROR: Redis Key Scan Failed: dial tcp :0: connect: connection refused
```

**Comment by javsalgar** [comment]
Hi!

Do you have a sample container that we can use to reproduce the issue?

**Comment by AlecBruns** [comment]
Let m e make a sample one.

**Comment by AlecBruns** [comment]
I don't have an image to share but I can share a code example and dockerfile config:

```
package main

import (
	"log"
	"time"

	"github.com/redis/go-redis/v9"
)

func redis_connect() {
	rdb = redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:    []string{"redis-redis-cluster:6379"},
		Password: "", // no password set
	})

	status := rdb.Set(appContext, "test", "5", 6*time.Second)
	status2 := rdb.Set(appContext, "test2", "5", 6*time.Second)

	if status.Val() != "OK" {
		log.Fatalf("ERROR: Redis Key Set Failed: %s", status)
	}

	if status2.Val() != "OK" {
		log.Fatalf("ERROR: Redis Key Set Failed: %s", status)
	}
}

```

```
FROM golang:1.20 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .


# Build the command inside the container.
RUN CGO_ENABLED=0 GOOS=linux go build -v -o go-app
```

container can be run with `/go-app`

**Comment by AlecBruns** [comment]
I've tried multiple different configurations: 
Using the normal client connection to a single node via the headless service as well as passing just the master nodes and then all the nodes to the cluster config. 

No matter what, it will work for a few commands then fail when it gets to a node without any ip or port: 

```
 Redis Key Set Failed: ex 6: dial tcp :0: connect: connection refused
 ```

**Comment by AlecBruns** [comment]
I've also tried the standard redis chart, but get `ERR This instance has cluster support disabled` when trying to connect to the cluster

**Comment by javsalgar** [comment]
Is the client being used inside the cluster or outside the cluster?

**Comment by AlecBruns** [comment]
Inside the minikube cluster

**Comment by andresbono** [comment]
Did you try running the equivalent commands via the redis-client CLI directly? As explained in the Helm notes, you can run the client like this:

```console
$ helm install redis oci://registry-1.docker.io/bitnamicharts/redis-cluster --version 10.0.2 --set "usePassword=false"
$ helm get notes redis
$ kubectl run redis-redis-cluster-client --rm -it --restart='Never' --image docker.io/bitnami/redis-cluster:7.2.4-debian-12-r12 -- bash
$$ redis-cli -c -h redis-redis-cluster
```

And then enter some commands:

```
10.244.0.117:6379> ping
PONG
10.244.0.117:6379> SET test '5' EX 6
OK
10.244.0.117:6379> SET test2 '5' EX 6
OK
10.244.0.117:6379> GET test
"5"
10.244.0.117:6379> GET test2
"5"

# wait some time to let the keys expire...
10.244.0.117:6379> GET test
(nil)
10.244.0.117:6379> GET test2
(nil)
```

Those commands work consistently for me without any "connection refused" errors. Could it be a bug in your code or any specific problem in your k8s cluster?

**Comment by recodyx** [comment]
same issue here. go lang application and bitnami cluster are deployed in same namespace.

I can connect to redis (port forward), so it works and alive. But the go application getting:

> read: connection reset by peer
