### ISSUE TITLE
Grafana Mimir - /path missing for servicemonitors in mimir chart

### ISSUE THREAD

**Issue by priyaGokul** [bitnami/charts#25116]
### Name and Version

bitnami/mimir 1.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I deployed Grafana Mimir in K8 clusters using Bitnami Helm chart
2.  All the pods, STS, service seem to be running as expected with s3 backend
3. On configure service monitors, I don't seem to configure path: /metrics under https://artifacthub.io/packages/helm/bitnami/grafana-mimir?modal=template&template=ingester/servicemonitor.yaml

### Are you using any custom parameters or values?

I use values.yaml for customization. Not lot of changes except for label and annotation and s3 backend

### What is the expected behavior?

configure and deploy servicemonitors using chart.

### What do you see instead?

I don't see /metrics endpoint exposed and couldn't find a way to configure path under metrics section in chart.

ref: https://artifacthub.io/packages/helm/bitnami/grafana-mimir

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by priyaGokul** [comment]
A follow up questions, Does mimir expose metrics endpoint in services?

**Comment by carrodher** [comment]
Metrics are disabled by default, [here](https://github.com/bitnami/charts/tree/main/bitnami/grafana-mimir#other-parameters) you can check how they can be enabled and the different parameters to customize it.

**Comment by priyaGokul** [comment]
@carrodher , Sure , I will check it out, Does enabling metrics and service monitor create prometheus operator + service monitors? I have a prometheus operator installed in namespace and would like to configure chart to use only service monitor.

Your response is greatly appreciated.

**Comment by javsalgar** [comment]
Hi,

The chart will not deploy prometheus operator, you can use your existing installation.
