### ISSUE TITLE
[bitnami/gitea] Wrong chart category: Analytics -> DeveloperTools

### ISSUE THREAD

**Issue by cshen-dev** [bitnami/charts#25125]
### Name and Version

bitnami/gitea 2.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Nav to bitnami/gitea/Chart.yaml
2. Check the line 5

### What is the expected behavior?

line 5: category: DeveloperTools

### What do you see instead?

line 5: category: Analytics

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
