### ISSUE TITLE
[bitnami/zookeeper] serviceMonitor has wrong port name

### ISSUE THREAD

**Issue by horihel** [bitnami/charts#2512]
**Which chart**:
bitnami/zookeeper-5.14.2

**Describe the bug**
If you enable ServiceMonitor, the chart will create a ServiceMonitor, pointing to a port named "metrics" - which doesn't exist on the metrics-service.
Instead, metrics service exports a port named "tcp-metrics"

**To Reproduce**
1. install zookeeper with metrics.enabled=true and metrics.serviceMonitor.enabled=true
2. Find that prometheus-operator doesn't scrape zookeeper
3. Find that the ServiceMonitor says "metrics" but the endpoint's port name is "tcp-metrics"

-- 

if you manually edit the serviceMonitor after installation (to 'tcp-metrics') scraping starts working.

**Expected behavior**
ServiceMonitor points to the correct port-name

**Version of Helm and Kubernetes**:
helm v2.16.5
kubernetes v1.17

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
simply changing port: to "tcp-metrics" in templates/serviceMonitor.yaml fixes the issue.

**Comment by miguelaeh** [comment]
Hi @horihel ,
Thank you very much for reporting the issue, that happened probably when we made the Chart Istio compatible, that need the protocol in the name.
