### ISSUE TITLE
[bitnami/postgresql] Execution order of initdb scripts

### ISSUE THREAD

**Issue by arches-richard** [bitnami/charts#25139]
### Name and Version

bitnami/postgresql 15.2.5, bitnami/mariadb 18.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Question: what is the execution order of the initdb scripts, if there is one that is guaranteed? Is it just chronological order?

### What do you see instead?

N/A

### Additional information

Would be really helpful if this repository enabled discussions so that users can read and answer each other's questions.

**Comment by javsalgar** [comment]
Hi, 

If I recall correctly, it should be alphabetical order.
