### ISSUE TITLE
Placeholders are incorrectly replaced in KAFKA_CLIENT_PASSWORDS for configuration with >10 users

### ISSUE THREAD

**Issue by nfsvtrifork** [bitnami/charts#25132]
### Name and Version

bitnami/kafka 28.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Add more than 10 users to `sasl.client.users`
2. Inspect `/opt/bitnami/kafka/config/server.properties` inside controller kontainer
3. See that the passwords for user at index 10-19 are all set to the password of user at index 1 with the second character of the index as the postfix.
    - For instance, if user[1] has password _PASS_, the password for user[10] will be _PASS0_, the password for user[11] will be _PASS1_, and so on

### Are you using any custom parameters or values?

A list of users with more than 10 elements

### What is the expected behavior?

The passwords should correspond with the passwords in the secret `kafka-user-passwords` at key `client-passwords`

### What do you see instead?

Given that user[1] has password _PASS_, the password for user[10] is _PASS0_, the password for user[11] is _PASS1_, and so on, instead of their respective passwords

### Additional information

The error seems to be in [bitnami/kafka/templates/scripts-configmap.yaml](https://github.com/bitnami/charts/blob/3614ed59f79b15912f5ec2382588cb6c2453f2de/bitnami/kafka/templates/scripts-configmap.yaml#L308-L310) (line 308 - 310), where `i = 1` will replace:
- `password-placeholder-1` with the right password (eg. `PASS`)
- `password-placeholder-10` with the same password but `0` as a postfix (eg. `PASS0`)
- `password-placeholder-11` with the same password but `1` as a postfix (eg. `PASS1`)
- and so on

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
