### ISSUE TITLE
[bitnami/prometheus-operator] Setting prometheus.persistence.storageClass produces invalid YAML

### ISSUE THREAD

**Issue by AdrianoKF** [bitnami/charts#2514]
**Which chart**:
Chart: `bitnami/prometheus-operator`
Version: `0.15.4`

**Describe the bug**
Enabling persistence for Prometheus and setting `prometheus.persistence.storageClass` to a non-empty value leads to an error when rendering the template.

```
$ helm template prometheus-operator --set prometheus.persistence.enabled=true --set prometheus.persistence.storageClass='pure-file' 
Error: YAML parse error on prometheus-operator/templates/prometheus/prometheus.yaml: error converting YAML to JSON: yaml: line 44: did not find expected key
```

Upon further investigation, it seems that the template chomps the line break preceding the `storageClassName` key in [bitnami/prometheus-operator/templates/prometheus/prometheus.yaml, line 117](https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml#L117):

```
{{- include "prometheus-operator.prometheus.storageClass" . }}
```

This leads to the following invalid output in the generated YAML (obtained using `helm template --debug`):

```yaml
    volumeClaimTemplate:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"storageClassName: pure-file
```
I believe eliminating the chomping of whitespace before the `include` call should fix the problem:

```diff
- {{- include "prometheus-operator.prometheus.storageClass" . }}
+ {{ include "prometheus-operator.prometheus.storageClass" . }}
```

**To Reproduce**

```shell
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm pull bitnami/prometheus-operator --untar
$ helm template prometheus-operator --set prometheus.persistence.enabled=true --set prometheus.persistence.storageClass='pure-file'
```

**Expected behavior**
Valid YAML output should be generated that includes the defined `storageClassName` attribute.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.14.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by AdrianoKF** [comment]
I'm not sure about the preferred process - if needed, I can prepare a PR with the fix proposed in the issue :)

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting the issue! If you could create a PR we would be very grateful :)

**Comment by AdrianoKF** [comment]
> Hi,
> 
> Thank you very much for reporting the issue! If you could create a PR we would be very grateful :)

Great, thanks for your fast reply! I have opened a PR containing the fix, see above :)

**Comment by javsalgar** [comment]
Thank you very much!!
