### ISSUE TITLE
[bitnami/gitea] Make log level configurable

### ISSUE THREAD

**Issue by fvogl** [bitnami/charts#25149]
### Name and Version

bitnami/gitea 2.0.3

### What is the problem this feature will solve?

able to control the log level of the app

### What is the feature you are proposing to solve the problem?

make log level configurable as ENV which will make it into the custom app.ini

### What alternatives have you considered?

unfortunately i could not find an alternative approach

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR?
