### ISSUE TITLE
Airflow baseURL issue with reverse proxy node port 

### ISSUE THREAD

**Issue by ImaDigitalTeam** [bitnami/charts#25154]
### Name and Version

bitnami/airflow 18.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When i try to upgrade the helm chart with the base url config i cannot reach the gui. I received this error:
Apache Airflow is not at this location.

Checking the env variable of the web pod i see:
<img width="594" alt="Screenshot 2024-04-12 at 11 38 07" src="https://github.com/bitnami/charts/assets/74365254/4163ab61-9d43-42c8-bf22-a583eef231a5">

AIRFLOW_BASE_URL : http://10.19.1.103:32735/airflow:8080

### Are you using any custom parameters or values?

 baseUrl: "http://10.19.1.103:32735/airflow"

### What is the expected behavior?

AIRFLOW_BASE_URL : http://10.19.1.103:32735/airflow

without the 8080 port

### What do you see instead?

AIRFLOW_BASE_URL : http://10.19.1.103:32735/airflow:8080

**Comment by javsalgar** [comment]
Hi,

I imagine that using a prefix was not considered in the container. Could you try doing the following to ensure that using prefixes work?

```
web:
  extraEnvVars:
    - name: AIRFLOW_BASE_URL
      value: http://10.19.1.103:32735/airflow
```

This should overwrite the other `AIRFLOW_BASE_URL` env var.
