### ISSUE TITLE
Ghost 10.0.0 Ingress annotations

### ISSUE THREAD

**Issue by rodolfo-picoreti** [bitnami/charts#2515]
**Which chart**:
ghost 10.0.0

**Describe the bug**
I think #2044 introduced a bug. The ingress annotations are being set using ```.Values.service.annotations```. Is that the intended behaviour?

**To Reproduce**
https://github.com/bitnami/charts/blame/master/bitnami/ghost/templates/ingress.yaml#L9

**Expected behavior**
To set ingress annotations using ```ingress.annotations``` not ```service.annotations```

**Comment by rafariossaa** [comment]
Hi @rodolfo-picoreti, 
  Thank you very much for noticing this, this is a bug.
  Do you want to contribute by submitting a PR or would your rather us to implement it?

**Comment by rodolfo-picoreti** [comment]
Hi @rafariossaa, its a very quick fix IMO so if you don't mind you can implement it. But if you want i can submit a PR.

**Comment by rafariossaa** [comment]
Hi @rodolfo-picoreti ,
  It would be great if you can do it.

Thanks forehand

**Comment by rodolfo-picoreti** [comment]
Ok! Please check #2655 .

**Comment by rafariossaa** [comment]
Hi @rodolfo-picoreti ,
  Thanks you very much for the PR.
  I have seen that @marcosbc is taking care of it.
