### ISSUE TITLE
[bitnami/mongodb] prevent mongodb/mongosh from phoning home on every *ness-probe

### ISSUE THREAD

**Issue by horihel** [bitnami/charts#25157]
### Name and Version

bitnami/mongodb-15.1.4

### What is the problem this feature will solve?

The mongodb chart invokes mongosh for every startup/liveness/readyness probe. By default, mongosh will send telemetry data back to HQ whenever it connects. We suspect this to be the cause of problems on some of our deployments, resulting in pods not becoming ready if outside DNS is slow or unavailable.

And from a privacy-point of view, this behaviour is undesired - especially when it is not communicated clearly like in this case (it is mentioned in the mongodb documentation, but you have to explicitely search for it to be even aware that it happens).

### What is the feature you are proposing to solve the problem?

as [documented](https://www.mongodb.com/docs/mongodb-shell/telemetry/#toggle-telemetry-collection), add "disableTelemetry()" to the invoking command, or drop a config file by default that prevents mongosh from trying.

### What alternatives have you considered?

it's probably possible for the user to mount an appropriate configmap containing a mongosh configfile using extraVolumeMount - i haven't explored that possibility yet. From my point of view, I'd like the default to be _not_ phoning home, but I can accept if the bitnami team opts to take whatever defaults upstream decides are reasonable.

**Comment by jotamartos** [comment]
Hi @horihel,

Thank you for your suggestion. Would you like to contribute to this project and suggest a change? You can follow [our guideline](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) to do so 😄 

Regarding what to change, you can find the script that the readiness and liveness probes use 

https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/common-scripts-cm.yaml#L18

Our team will be more than happy to review your changes and update the solution with them.

**Comment by horihel** [comment]
happy to do so - with the newly adopted readOnlyRootFilesystems, it might be feasible to mount a configmap with the mongosh config. 
I'll look into it, but it'll take a while until I can pick this up.

**Comment by horihel** [comment]
just wanted to ping back - this is not abandoned yet, just not high prio enough that we can tackle it immediately

**Comment by LittleHoopoe** [comment]
Maybe useful for someone and maybe someone can help me further :D 
I'm using this here =>

`  initdbScripts:
    disable-telemetry.js: |
      mongosh --nodb --eval "disableTelemetry()"
  # these lines are only temporary and well be gone as soon all instances are updated to chart version 2.0.44
  lifecycleHooks:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            mongosh --nodb --eval "disableTelemetry()"`

This is good for the first pod of a replica but doesn't apply to the rest. I'm out of ideas.
