### ISSUE TITLE
Support SMTP_AUTHENTICATION

### ISSUE THREAD

**Issue by dotKuro** [bitnami/charts#2516]
**Which chart**:
redmine

**Is your feature request related to a problem? Please describe.**
I tried to configure the redmine with the given chart to use the google smtp relay as described here: https://support.google.com/a/answer/2956491. The relay has the option to not use smtp authentication but to rather whitelist ip adresses. To use this feature I need to be able to set the SMTP_AUTHENTICATION docker env variable as described here: https://github.com/bitnami/bitnami-docker-redmine#smtp-configuration. For this chart this option does not exist.

**Describe the solution you'd like**
A good solution would be to add a parameter to the chart like the existing smtpHost, smtpPort, and so on parameters.

**Describe alternatives you've considered**
I tried to use the extraVars parameter, but I couldn't find what the syntax for that one is, because just setting key-value pairs like "key=value" probably conflicts with the syntax of the other parameters.

**Additional context**
/

**Comment by miguelaeh** [comment]
Hi @dotKuro ,
Sorry for the late response, we missed this issue and it just appeared today in our board thanks to the stale bot.
I checked an it seems that that env var is not currently available in the [SMTP section](https://github.com/bitnami/charts/blob/e17eeb4ed644deff5139ba6100d6f3761d12e2e8/bitnami/redmine/values.yaml#L59). 
Would you like to create a PR adding that env var to the Chart?
