### ISSUE TITLE
[bitnami/redis] redis-server requirepass appears in process table

### ISSUE THREAD

**Issue by freedge** [bitnami/charts#25163]
### Name and Version

bitnami/redis main

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. use it

### What is the expected behavior?

no secret given on the command line

### What do you see instead?

```--requirepass``` argument shows up in the process table, it is also recorded by auditing tools.

stackrox finds
```
redis-server --port 6379 --include /opt/bitnami/redis/etc/redis.conf --requirepass vz... --masterauth vz...
```

### Additional information

https://github.com/bitnami/charts/blob/94ce52ab08a89a7881e8d443f153e284a3f65229/bitnami/redis/templates/scripts-configmap.yaml#L241

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. It seems to me that the issue is not related to the Bitnami packaging of Redis but with how redis manages the its process table entry. Did you report it upstream?

**Comment by freedge** [comment]
hi, redis provides a way to give parameters either on the command line or through a config file. Bitnami packaging choose to give the password on the command line so it's really an issue here, and not upstream.
