### ISSUE TITLE
[bitnami/wordpress] Customizing the SMTP sender email address and sender name

### ISSUE THREAD

**Issue by mrclrchtr** [bitnami/charts#25174]
### Name and Version

bitnami/wordpress 22.1.7

### What is the problem this feature will solve?

Currently, it is only possible to set the parameter `wordpressEmail`. This is used both as the SMTP login and as the sending address. So, it's not possible to use a different login than the sender address.

### What is the feature you are proposing to solve the problem?

 I would be very happy if this could be separated.

**Comment by javsalgar** [comment]
Hi,

This may require a change in the bitnami/wordpress container and adding a new env var. 

https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-12/rootfs/opt/bitnami/scripts/libwordpress.sh#L656

I will forward it to the team but, as it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding this separation?

**Comment by mrclrchtr** [comment]
Ah ok, yes, that doesn't look too complicated. I'll see if I can find the time to do it in the near future. Thank you very much.

**Comment by mrclrchtr** [comment]
I would also like to adjust the `from_name` in the process. Does it make sense to include a "if `$WORDPRESS_SMTP_FROM_EMAIL` is not set, then use `${WORDPRESS_FIRST_NAME} ${WORDPRESS_LAST_NAME}`" in this script?

Exactly the same for `$WORDPRESS_SMTP_FROM_EMAIL`?

Otherwise it would be a breaking change, wouldn't it?

**Comment by javsalgar** [comment]
I agree, let's avoid potentially breaking changes

**Comment by mrclrchtr** [comment]
I haven't had time to do this yet, but I still intend to create a PR.

**Comment by mrclrchtr** [comment]
I created https://github.com/bitnami/containers/pull/67399

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look

**Comment by mrclrchtr** [comment]
I will create another PR, to be able to set these new environment variables with the chart.

**Comment by mrclrchtr** [comment]
I also created https://github.com/bitnami/charts/pull/28648
