### ISSUE TITLE
[bitnami/wordpress] Adjusting the cluster domain should be possible to fix memcached

### ISSUE THREAD

**Issue by mrclrchtr** [bitnami/charts#25176]
### Name and Version

bitnami/wordpress 22.1.7

### What is the problem this feature will solve?

![image](https://github.com/bitnami/charts/assets/16151098/36fa0ad0-387a-43f7-b1f9-39105ad1bbc0)

We have a custom cluster domain that is not "cluster.local".
This leads to the issue that memcached cannot be reached.

### What is the feature you are proposing to solve the problem?

Adjusting that should be possible.

**Comment by javsalgar** [comment]
Did you try changing the value `clusterDomain`?
