### ISSUE TITLE
[bitnami/redmine] CAP_CHMOD doesn't exist

### ISSUE THREAD

**Issue by morganbasset** [bitnami/charts#25181]
### Name and Version

bitnami/redmine:28.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install Chart in version 28.0.1
2. Cannot install it because CAP_CHMOD doesn't exist

### What do you see instead?

Remove "chmod" from the capabilities list in values.yaml

### Additional information

https://man7.org/linux/man-pages/man7/capabilities.7.html

**Comment by javsalgar** [comment]
Hi, this error is fixed here: https://github.com/bitnami/charts/pull/24933
