### ISSUE TITLE
kubeapps Postgresql Resource Settings are being ignored and stay default with HELM Chart Version 15.0.2

### ISSUE THREAD

**Issue by ILZ1105** [bitnami/charts#25183]
### Name and Version

bitnami/kubeapps 15.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Use either a resourcepreset or dial in your required resources in the part for postgres
2. Deploy the chart (done via kubeapps in my case)
3. Check the resources of the pod or the respective statefulset
The values are still the defaults:
resources:
limits:
cpu: 150m
ephemeral-storage: 1Gi
memory: 192Mi
requests:
cpu: 100m
ephemeral-storage: 50Mi
memory: 128Mi

### Are you using any custom parameters or values?

I've used resourcePreset: medium, nothing changed
I've dialed in the specific resources, nothing changed

   resources:
     requests:
       cpu: 2
       memory: 512Mi
     limits:
       cpu: 3
       memory: 1024Mi

### What is the expected behavior?

The resources are accordingly set to the statefulset and the respective pod.

### What do you see instead?

I see the default values used, regardles of what I define in the values.yaml:

limits:
cpu: 150m
ephemeral-storage: 1Gi
memory: 192Mi
requests:
cpu: 100m
ephemeral-storage: 50Mi
memory: 128Mi

### Additional information

Causes issues when kubeapps tries to sync the bitnami repo and potentially other repos. The DB can even crash multiple times and not accept any more requests because it's in recovery mode. It's constantly at the limit of 150m for CPU when it's synching Bitnami.

**Comment by javsalgar** [comment]
Hi,

Looking at the values.yaml there is an error. It shouldn't be postgresql.resources / postgresql.resourcesPreset but postgresql.primary.resources and postgresql.primary.resourcesPreset
