### ISSUE TITLE
[bitnami/contour] Missing ConfigMap and BackendTLSPolicy permissions in clusterrole when adding gatewayRef

### ISSUE THREAD

**Issue by bumarcell** [bitnami/charts#25203]
### Name and Version

bitnami/contour 17.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Add gateway.gatewayRef in contour configmap
2. Restart contour
3. On startup it it logs the following errors:

```
level=error msg="pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User \"system:serviceaccount:contour:contour-contour\" cannot list resource \"configmaps\" in API group \"\" at the cluster scope" caller="reflector.go:147" context=kubernetes error="<nil>"

level=error msg="pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1alpha2.BackendTLSPolicy: failed to list *v1alpha2.BackendTLSPolicy: backendtlspolicies.gateway.networking.k8s.io is forbidden: User \"system:serviceaccount:contour:contour-contour\" cannot list resource \"backendtlspolicies\" in API group \"gateway.networking.k8s.io\" at the cluster scope" caller="reflector.go:147" context=kubernetes error="<nil>"
```

### What is the expected behavior?

The chart should add all relevant permissions in rbacs, including those for CRDs.

### What do you see instead?

The clusterrole doesn't define permissions for all GatewayAPI crds, namely backendpolicies isn't added.
The list and watch permissions on configmaps were also missing, which only throws an error after adding gatewayRef.

**Comment by jotamartos** [comment]
> The clusterrole doesn't define permissions for all GatewayAPI crds, namely backendpolicies isn't added.
> The list and watch permissions on configmaps were also missing, which only throws an error after adding gatewayRef.

Hi, 

Thank you for reporting the issue. As you have identified the issue, would you like to contribute? You can contribute by following [our contributing guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) and it will benefit the community.

Thanks

**Comment by bumarcell** [comment]
Looks like it's been added in chart v17.0.7 
Many thanks ❤️
