### ISSUE TITLE
[bitnami/magento] Any way to get root access in magento pod?

### ISSUE THREAD

**Issue by pavlokudrynskyi** [bitnami/charts#25202]
### Name and Version

bitnami/magento

### What architecture are you using?

None

### What steps will reproduce the bug?

Use the official helm chart with the default podSecurityContext and containerSecurityContext
When I'm trying to change runAsUser to `0` instead of the default (`1001`) container constantly restarts during the initialization.

By just executing `sudo su` I'm getting `sudo not found` error. 

I'm trying to install additional packages on Magento pod and execute some commands, but cannot find a way to do that. Is there any other options?

### Are you using any custom parameters or values?

I've use the default one, but also the configuration below
```podSecurityContext:
  enabled: true
  fsGroup: 0

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  capabilities: {}
  seccompProfile: {}
  runAsNonRoot: false
  privileged: true
  allowPrivilegeEscalation: true```

### What is the expected behavior?

are able to install toold and execute commands under root user.

### What do you see instead?

Permission denied error or sudo not found error.

### Additional information

_No response_

**Comment by javsalgar** [comment]
Hi,

I'm afraid that root configuration is not something we are actively testing or supporting. If you need to extend the image you could try creating your own forked image by extending with 'FROM bitnami/magento`
