### ISSUE TITLE
[bitnami/keycloak] Same ports in deployment spec

### ISSUE THREAD

**Issue by Usaldudo** [bitnami/charts#25218]
### Name and Version

bitnamu/keycloak 21.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy latest keycloak
```
helm template my-release oci://registry-1.docker.io/bitnamicharts/keycloak --version 21.0.2
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Helm install should succeed.

### What do you see instead?

Error from server:
```
Error from server: failed to create typed patch object (default/my-release-keycloak; apps/v1, Kind=StatefulSet): .spec.template.spec.containers[name="keycloak"].ports: duplicate entries for key [containerPort=7800,protocol="TCP"]
```

### Additional information

I think this is because of new port from #25110

**Comment by javsalgar** [comment]
Hi! Thank you so much for reporting. I created this PR to fix it https://github.com/bitnami/charts/pull/25222
