### ISSUE TITLE
[bitnami/redis] Liveness Probes Failing on AKS 1.29.2

### ISSUE THREAD

**Issue by noxwuan** [bitnami/charts#25217]
### Name and Version

bitnami/redis

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We've recently upgraded our test environment on Azure Kubernetes Service (AKS) to version 1.29.2 and started encountering an intermittent issue with liveness probes on our Redis setup (standard bitnami chart with no customization).

- Cluster Configuration: Our deployment consists of one master and two replicas.
- Previous Version: Prior to the AKS upgrade, the same configuration on AKS/K8S 1.26.3 worked flawlessly (and still works, we have a parallel system that still runs the same chart under heavy load)

### Are you using any custom parameters or values?

- Setup --> exec [sh -c /health/ping_liveness_local.sh 5] delay=20s timeout=6s period=5s #success=1 #failure=5

### What is the expected behavior?

For probes to work 100% - (at least if there is no load on the nodes)

### What do you see instead?

- Error Message: Sporadically, the liveness probes fail with the following error:Liveness probe failed: command "sh -c /health/ping_liveness_local_and_master.sh 5" timed out
- Frequency: The failure happens randomly every 10-15 minutes and doesn't follow any discernible pattern.

### Additional information

We attempted to replicate the problem by running redis-cli ping directly in a loop on all three pods/containers. However, there were no signs of latency or peaks in response times - we also ran Redis intrinsic tests (generating heavy load on all nodes) - but that did result in consistently stable values and the same random liveness probe issues.

Has anyone else encountered this post-upgrade? We're trying to root out the cause as there's no apparent system load or network latency that would be disrupting the liveness checks (or maybe there is a brief drop for 1 call, but we were not able to reproduce it by doing the same checks in parallel in the shell)

**Comment by Alwinius** [comment]
I have a similar issue with timeouts in the liveness/readiness probes. I can see that the containers cpu usage is considerably higher than in other clusters that are not affected. This leads to throtteling by Kubernetes with the default resource limits.

However, for me the difference between the two clusters is the other way around: EKS 1.29.2 works fine, but when installed one day later on the production system with EKS 1.28.7, the issue appears. Both use very simple configuration without persistence

**Comment by javsalgar** [comment]
Hi! I think that the issue may be related to properly configured resource limits/requests for your use case. Could you confirm that these are configured and it is not using the ones set by default in `resourcesPreset`? These are not meant for production and are configured to the minimum value working in our test suite

**Comment by Alwinius** [comment]
Thanks for reply @javsalgar. We are using indeed the default values:
resources:
            limits:
              cpu: 150m
              ephemeral-storage: 1Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi

But in one system the actual CPU usage is 0.02 (20% of request) and in the other it's 0.15 (150% of request and equal to the limit) where both instances are basically idle and contain maybe 10 keys.

**Comment by javsalgar** [comment]
Could you try increasing the CPU limits to see if that solves the issue? At least to pinpoint where the problem could be

**Comment by Alwinius** [comment]
Yes, this seems like a workaround. Initially the CPU usage is around 0.32 and then drops to 0.17. The instance contained 0 keys at that point.

**Comment by javsalgar** [comment]
It probably is related to how the database performs a first initialization.  This is not happening in our tests with major k8s distributions (including AKS) but each deployment should adapt the `resources` section to their use case.

**Comment by Alwinius** [comment]
We updated the cluster with high CPU usage to EKS 1.29 now and the issue seems to be gone. 

But I would still say that this is a bug if an empty redis consumes 10x the CPU than in another cluster.

**Comment by javsalgar** [comment]
Hi,

It could be, but probably it seems more of an upstream issue rather than an issue in the Bitnami packaging. Maybe it's worth reporting it upstream.
