### ISSUE TITLE
Kafka panic: kafka: client has run out of available brokers to talk to

### ISSUE THREAD

**Issue by cedricve** [bitnami/charts#2522]
**Which chart**:
Kafka 10.3.2

**Describe the bug**

I'm using the values-production.yaml file, and when creating the chart, it can not start the exporter.

    C02XL1E5JHD3:kafka i353408$ kubectl logs kafka-exporter-574df9dfc7-62d79
    time="2020-05-05T20:07:23Z" level=info msg="Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=830660212e6c109e69dcb1cb58f5159fe3b38903)" source="kafka_exporter.go:474"
    time="2020-05-05T20:07:23Z" level=info msg="Build context (go=go1.10.3, user=root@981cde178ac4, date=20180707-14:34:48)" source="kafka_exporter.go:475"
    time="2020-05-05T20:07:28Z" level=error msg="Error Init Kafka Client" source="kafka_exporter.go:210"
    panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

    goroutine 1 [running]:
    main.NewExporter(0xc42005db70, 0x1, 0x1, 0x100, 0x8f22f8, 0x0, 0x8f22f8, 0x0, 0x0, 0x8f22f8, ...)
    	/go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:211 +0x847
    main.main()
    	/go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:481 +0x215b

**Comment by rafariossaa** [comment]
Hi @cedricve ,
  Could you provide more background ? For example, which kubernetes cluster are you trying to deploy in, if you are setting any parameters, etc .
  Could you check if the other pods are running ?
