### ISSUE TITLE
[bitnami/redis] Ability to rename redis service port name

### ISSUE THREAD

**Issue by arianf** [bitnami/charts#25228]
### Name and Version

bitnami/redis latest

### What is the problem this feature will solve?

Our internal kube cluster has an odd requirement, it requires all service `ports.name` to match the `ports.targetPort`, I've filed something internally to hopefully get this constraint fixed (but due to the complexity of fixing it, it may take a lot of time, or never be resolved).

```yaml
name: tcp-redis
targetPort: redis
```

https://github.com/bitnami/charts/blob/7359f94e1c61801f043b4515f697575830f814e1/bitnami/redis/templates/master/service.yaml#L47-L58

### What is the feature you are proposing to solve the problem?

It would be awesome, if `ports.name` or `ports.targetPort` name could also be configurable

### What alternatives have you considered?

I've tried using `.Values.master.service.extraPorts` to add a port with matching name

```yaml
service:
  extraPorts:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
```

but that results with a duplicate key since the default config and the extraPorts config are using the same ports

```
spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", AppProtocol:(*string)(nil), Port:6379, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting the issue. Would you like to submit a PR adding a value for the service name?
