### ISSUE TITLE
Why number of MariaDB primary replicas is harcoded to 1 in template

### ISSUE THREAD

**Issue by faizan-syed** [bitnami/charts#25220]
### Name and Version

bitnami/mariadb

### What architecture are you using?

None

### What steps will reproduce the bug?

There is no option in values file to change mariaDB primary replica count (stateful set). Is there any reason for this it is set static to 1 and cannot be changed? What could be the issue if I increase number of primary replica.
It also has PDB count set to 1 by default not sure if I can increase that in this case ?

### What do you see instead?

<img width="812" alt="Screenshot 2024-04-18 at 13 47 04" src="https://github.com/bitnami/charts/assets/84979480/6ce04171-de7e-4adb-9215-48140e28cacb">

**Comment by javsalgar** [comment]
Hi!

MariaDB primary replica count is set to 1 because multi-master is not supported in this chart. In order to have a multi-master mariadb you can use the MariaDB Galera chart.
