### ISSUE TITLE
[bitnami/postgresql-ha] Implement HPA for Read Replica

### ISSUE THREAD

**Issue by paretl** [bitnami/charts#25239]
### Name and Version

bitnami/postgresql-ha

### What is the problem this feature will solve?

It will permit to adjust the number of replica pods based on a metric (CPU usage for example)
It optimizes resource usage and so, reduce the cost of the cluster

### What is the feature you are proposing to solve the problem?

Add the possibility to setup the HPA on the number of replica of PostgresQL
I saw that this feature was mentionned in this issue https://github.com/bitnami/charts/issues/2931 but it was closed due to inactivity

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR?
