### ISSUE TITLE
[bitnami/keycloak] Unable to use Ingress rule without a host defined

### ISSUE THREAD

**Issue by wkbrd** [bitnami/charts#25233]
### Name and Version

bitnami/keycloak 21.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Attempting to deploy Keycloak helm chart with ingress.enabled=true should not require a hostname to be defined.  An ingress does not require the host to be filled in.

### Are you using any custom parameters or values?

ingress.enabled=true

### What is the expected behavior?

Ingress run should be created without the "host: ..." line, though the rest of the rule is defined and traffic flows properly.

### What do you see instead?

Helm chart does not deploy and gives an error message

**Comment by javsalgar** [comment]
Hi!

Could you try using the `extraHosts` section? There you can use an empty `host` value, which may work for your use case

**Comment by wkbrd** [comment]
That ended up working.  Thank you!
