### ISSUE TITLE
Using S3 or Google Cloud for image hosting

### ISSUE THREAD

**Issue by alexkasemir** [bitnami/charts#2523]
**Which chart**:
/bitnami/ghost

**Is your feature request related to a problem? Please describe.**
Persistent Storage can be finicky when redeploying, and my kubes cluster has dynamic node scaling but not ReadWriteMany when it comes to Storage Classes. I was hoping to use AWS S3 or Google Cloud Storage to store my images for a safer deployment strategy (one where its harder to lose images).

**Describe the solution you'd like**
A simple way to integrate solutions like this: https://ghost.org/integrations/amazon-s3/ or https://ghost.org/integrations/google-cloud-storage/ using the helm chart.

**Describe alternatives you've considered**
Persistent Storage for Images and 🤞 I don't lose my images. Figuring out how to extend this helm chart to allow for custom storage adapters.

**Comment by miguelaeh** [comment]
Hi @alexkasemir ,
I am not totally sure I understand the issue. You can configure Ghost to use `ReadWriteMany` using the following parameter: https://github.com/bitnami/charts/blob/9f6e477fb626ef2e4d2e695e84f01e3961a1e64c/bitnami/ghost/values.yaml#L247

**Comment by alexkasemir** [comment]
Ah sorry for the confusion @miguelaeh. 

So we use the Google Cloud Kubernetes Engine, which does not support ReadWriteMany. Therefore, we were hoping to be able to store our Ghost Images in Amazon s3 or Google Cloud Storage instead of in PersistenceStorage. Ghost has a few integrations for [this](https://ghost.org/integrations/amazon-s3/) but I was wondering it was possible to do this using this helm chart?

**Comment by miguelaeh** [comment]
Hi @alexkasemir ,
Sorry for the confusion, the helm chart does not support those env vars, but I think you could configure them after the installation using the configuration file: https://github.com/colinmeinke/ghost-storage-adapter-s3#configuration

**Comment by alexkasemir** [comment]
Thanks for the response. After some further research, we ended up using a [nfs-server-provisioner](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) to get ReadWriteMany support on our Google Cloud Cluster. I think it might be worthwhile for this chart to investigate supporting other image-hosting options, but for right now I think this will be alright for us! 

Thanks for your help.
