### ISSUE TITLE
[bitnami/cassandra] Cannot login to cassandra using cqlsh (Authentication Issue)

### ISSUE THREAD

**Issue by amirhallaji** [bitnami/charts#25278]
### Name and Version

bitnami/cassandra 11.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploying the chart using the following command in the ```cassandra``` directory.

```bash
helm upgrade cassandra . -i --values values.yaml
```

After the deployment, I try to log in to Cassandra in the terminal using ```cqlsh -u cassandra -p cassandra```. But I get this error.
```
Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Failed to authenticate to 127.0.0.1:9042: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"')})
```
Also, I should mention that this problem occurred when I first did a ```helm uninstall cassandra```, and after installing it again, I couldn't log in to Cassandra anymore.

I have checked the password in the secrets and it had been already set to ```cassandra```. 
Also, I have left the password empty to be generated randomly and used that random password. This didn't work out either.

### Are you using any custom parameters or values?

```bash
dbUser:
   password: "cassandra"
```

### What is the expected behavior?

I would have logged in with this simple ```cqlsh -u cassandra -p cassandra```. But now I can't.

### What do you see instead?

I get this error.
```bash
Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Failed to authenticate to 127.0.0.1:9042: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"')})
```

**Comment by amirhallaji** [comment]
Hi,
I did not delete pvc since I didn't want to lose data. 
As I know, the deletion of PVC results in losing data if no backup is provided. 
Should I have done something else?

**Comment by javsalgar** [comment]
When there is a PVC, the installation will re-use the password from the volume. Could you confirm what the previous password was?

**Comment by amirhallaji** [comment]
I got it.
Yes, the previous password was ```cassandra``` which I used to log in. But, after installing it again, this password didn't work anymore.

**Comment by dgomezleon** [comment]
Hi @amirhallaji 

I was not able to reproduce the issue. I tried the following.

1. Install the chart with default values only using `dbUser.password="cassandra"`
2. Access with the following commands
```
   kubectl port-forward --namespace test svc/cassandra 9042:9042 &
   cqlsh -u cassandra -p cassandra 127.0.0.1 9042
```
4. Unisntall it and keep PVC.
5. Install again
6. Access with the previous commands.

I would suggest using these commands in case it helps:

```
$ export CASSANDRA_PASSWORD=$(kubectl get secret --namespace "test" cassandra -o jsonpath="{.data.cassandra-password}" | base64 -d)
$   kubectl port-forward --namespace test svc/cassandra 9042:9042 &
$  cqlsh -u cassandra -p $CASSANDRA_PASSWORD 127.0.0.1 9042

**Comment by amirhallaji** [comment]
Hi @dgomezleon 

Thank you for your suggestion. Actually, I had done these steps multiple times before creating this issue, but unfortunately, they didn't work for me. I think the only solution may be to delete PVC. Am I right?

I also should mention that the first time I uninstalled the chart, it was due to the lack of resources in that namespace that made me do that. I don't know whether it's helpful or not. But I add it to this issue.

**Comment by dgomezleon** [comment]
Hi @amirhallaji 

You could try the following to apply [this docs](https://docs.bitnami.com/general/infrastructure/cassandra/administration/change-reset-password/):

1. Copy the original configuration:
```
$ kubectl cp cassandra-0:/opt/bitnami/cassandra/conf/cassandra.yaml /tmp/cassandra.yaml
```
2. Edit it as follows
```
...
# - AllowAllAuthenticator performs no checks - set it to disable authentication.
# - PasswordAuthenticator relies on username/password pairs to authenticate
#   users. It keeps usernames and hashed passwords in system_auth.roles table.
#   Please increase system_auth keyspace replication factor if you use this authenticator.
#   If using PasswordAuthenticator, CassandraRoleManager must also be used (see below)
authenticator: 'AllowAllAuthenticator'

# Authorization backend, implementing IAuthorizer; used to limit access/provide permissions
# Out of the box, Cassandra provides org.apache.cassandra.auth.{AllowAllAuthorizer,
# CassandraAuthorizer}.
#
# - AllowAllAuthorizer allows any action to any user - set it to disable authorization.
# - CassandraAuthorizer stores permissions in system_auth.role_permissions table. Please
#   increase system_auth keyspace replication factor if you use this authorizer.
authorizer: 'AllowAllAuthorizer'
...
``` 
3. Create a CM
```
$ kubectl create cm cassandra-conf --from-file=/tmp/cassandra.yaml
```
4. Uninstall the chart and install it as follows
```
helm install cassandra . --set existingConfiguration=cassandra-con
```
5. Access with `cqlsh` (with empty password) and set it to `cassandra`:
```
$ cqlsh -u cassandra 127.0.0.1 9042
  cqlsh> UPDATE system_auth.roles SET salted_hash = '$2a$10$1gMPBy9zSkDzKxdbU2v/gOslcMRPDcXVqmwQYBmi8MVgYvNdRZw/.' WHERE role = 'cassandra';
  cqlsh> exit 
```
6. Uninstall and install the chart as usual.

You should be able to access it with `cassandra` password.

**Comment by amirhallaji** [comment]
Hi dear @dgomezleon 

Thank you very much. It worked for me.

**Comment by singer0503** [comment]
nice bro @dgomezleon 
this is good solution.
