### ISSUE TITLE
Dont hard code the namespace in ZOO_SERVERS value

### ISSUE THREAD

**Issue by red8888** [bitnami/charts#25277]
### Name and Version

bitnami/zookeeper 13.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy the chart and see this:

```
ZOO_SERVERS: prerequisites-zookeeper-0.prerequisites-zookeeper-headless.MY_NAMESPACE.svc.cluster.local:2888:3888::1
````

### What is the expected behavior?

The namespace should not be hard coded into the svc reference.

### What do you see instead?

Does the namespace need to be included here? Why is it included? This is a problem because it makes the config less portable.

I just ran into an issue where I did a velero restore to a new namespace and this hard coded value I now have to change.

It should just point to the service name without namespace specifier.

**Comment by juan131** [comment]
Hi @red8888

Please note the environment variable `ZOO_SERVERS` is auto-populated by the chart using the piece of code below:

- https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/templates/statefulset.yaml#L242-L250

As you can see, the namespace is set using the helper "zookeeper.namespace" which is defined below:

- https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/templates/_helpers.tpl#L37-L46

You can use the `namespaceOverride` parameter to set any custom namespace you want.
