### ISSUE TITLE
clickhouse extradb

### ISSUE THREAD

**Issue by nowost** [bitnami/charts#25292]
### Name and Version

bitnami/clickhouse v24.3.2

### What is the problem this feature will solve?

I can add extra databases via values.yaml 

### What is the feature you are proposing to solve the problem?

I think  need values to extend clickhouse provisioning like
```yaml
databases:
 - mydb
```
```yaml
or
extradbs:
 - mydb: db
    user: user
```

### What alternatives have you considered?

I tried extraOverridesConfigmap: "some-configs", but got no luck.

**Comment by carrodher** [comment]
At this moment, the only "database" support in ClickHouse is Zookeeper, see https://github.com/bitnami/charts/tree/main/bitnami/clickhouse#external-zookeeper-support.

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
