### ISSUE TITLE
[Bitnami/Spark] Worker stuck because of error invalid null input:name when execute command

### ISSUE THREAD

**Issue by anhlevfx** [bitnami/charts#25314]
### Name and Version

bitnami/spark:9.0.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I installed spark cluster with `helm install my-release oci://registry-1.docker.io/bitnamicharts/spark` and used Minikube.

Run spark-submit to the master pod and check worker pod logs. Found that the log is stuck in the `Execute command....` I tried copying the command below and run it directly in the worker pod terminal.

The command: `/opt/bitnami/spark$ /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1024M -Dspark.driver.port=41119 -Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@python-spark-submit-pod:41119 --executor-id 0 --hostname 10.244.0.26 --cores 1 --app-id app-20240422180134-0054 --worker-url spark://Worker@10.244.0.26:35823 --resourceProfileId 0`

Terminal show error

```
Exception in thread "main" org.apache.hadoop.security.KerberosAuthException: failure to login: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
.....
Caused by: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
......
```

### What do you see instead?

Spark workers stuck and master recreate new workers after a periodic time.

**Comment by fmulero** [comment]
Hi @anhlevfx thanks for using Bitnami charts!

I am little bit confused with the information you provided. If I am not wrong, that error is related to the application itself, the application you are trying to run, not the cluster. Anyway please check if you are facing any kind of connectivity error, we include recently NetworkPolicies to block undesired traffic. To test if those rules are blocking your traffic you can disabled them setting `worker.networkPolicy.enabled=false`

**Comment by anhlevfx** [comment]
Hello @fmulero ,
I tried upgrade helm with the config you suggested. But, the issue still exist.
I created a pod with the image same as spark cluster. I mounted a volume in the pod to load my python script. From that pod, I executed spark-submit and got the error log as I mentioned.

Addition information, I ran example code after install successfully and it works like a charm.

I think some people facing same problem like me:
https://stackoverflow.com/questions/72897413/spark-submit-fails-on-kubernetes-using-spark-bitnami-docker-image-getting-java

I have no idea to fix this. Take me many days!.

**Comment by fmulero** [comment]
Could you share a simple scenario to reproduce the initial failure? I think you are facing 2 different issues:
* Run spark-submit to the master pod and check worker pod logs. Found that the log is stuck in the `Execute command....`Spark workers stuck and master recreate new workers after a periodic time. <-- I am worried about this.
* `java.lang.NullPointerException: invalid null input: name` I think this is a red herring, and it is related about how you are trying to diagnose the issue and not the issue itself. Please amend me if I am wrong

**Comment by OmarElHrr** [comment]
Hi  @anhlevfx 
Did you resolve the problem?

**Comment by anhlevfx** [comment]
> Could you share a simple scenario to reproduce the initial failure? I think you are facing 2 different issues:
> 
> * Run spark-submit to the master pod and check worker pod logs. Found that the log is stuck in the `Execute command....`Spark workers stuck and master recreate new workers after a periodic time. <-- I am worried about this.
> * `java.lang.NullPointerException: invalid null input: name` I think this is a red herring, and it is related about how you are trying to diagnose the issue and not the issue itself. Please amend me if I am wrong

Sorry about lately reply!

You are right!. I got error log `java.lang.NullPointerException: invalid null input: name` by run the command, which is latest log in spark worker pod. Of course, I ran the command in the same worker pod.

**Comment by OmarElHrr** [comment]
Hi @anhlevfx 
Yes, it works for me with the spark-operator in Minikube, but in the K8S cluster, it gives the same problem.

**Comment by anhlevfx** [comment]
> Hi @anhlevfx Yes, it works for me with the spark-operator in Minikube, but in the K8S cluster, it gives the same problem.

I tried spark-operator with minikube multi nodes with no issue. Maybe, I will try K8S cluster of a cloud service in next week and let you know if have issues. Anyway, I think you should submit the issue to spark-operator repo and we will discuss later.

**Comment by OmarElHrr** [comment]
@anhlevfx 
This is my Dockerfile. Could you check if the problem is with the user settings or in the Dockerfile itself?
*****************************************************************
FROM bitnami/spark:3.3.2-debian-11-r157

#WORKDIR /opt/spark/app
WORKDIR /opt/bitnami/spark

USER root

RUN mkdir -p /opt/bitnami/spark/test


COPY ./target/ingestion-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/bitnami/spark/test

RUN mkdir -p /opt/bitnami/spark/.ivy2 && \
    chmod -R 777 /opt/bitnami/spark/.ivy2

USER 1001

ENTRYPOINT [ "/opt/bitnami/scripts/spark/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/spark/run.sh" ]
*****************************************************************************************

**Comment by anhlevfx** [comment]
@OmarElHrr O
When use spark-operator, my docker file was built base on 'ghcr.io/apache/spark-docker/spark:3.5.0-python3'. You can try. Just for clear understand, spark-operator is another repo, not bitnami chart.

**Comment by fmulero** [comment]
I am trying to find the root cause of the issue. Could you share following details?:
* `values.yaml` file and/or instructions to deploy the spark cluster to try to reproduce a similar scenario.
* Logs from your worker nodes just before the crash. If you can get the events or describe the failing pod that could be great to diagnose the issue better.
* Do you have prometheus or information from metrics server? Maybe the problem is related to the resources. You can increase them easily setting `worker.resourcesPreset` https://github.com/bitnami/charts/blob/081ffe9dd70c8fccd308552d3b6335cc25c98909/bitnami/spark/values.yaml#L665-L685

**Comment by anhlevfx** [comment]
Hi @fmulero , please reproduce by steps below.

1. Start spark cluster: run only `helm install my-release oci://registry-1.docker.io/bitnamicharts/spark` and will have 3 pod (1 master and 2 worker)
<img width="1443" alt="Screenshot 2024-05-10 at 14 25 32" src="https://github.com/bitnami/charts/assets/31474164/1c04d30a-ee68-40d8-b6c8-f9f796e77d58">

2. Create a spark-app-submit pod in k8s to run `spark-submit`. Mount to host folder, which has `spark-main.py` file
```
apiVersion: v1
kind: Pod
metadata:
  name: spark-app-submit
  labels:
    app: spark
spec:
  containers:
  - name: spark-app-submit
    image: docker.io/bitnami/spark:3.5.1-debian-12-r2
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    hostPath:
      path: /home/data
      type: DirectoryOrCreate
```

```
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Convert Array to RDD") \
    .getOrCreate()

data_array = [1, 2, 3, 4, 5]

data_rdd = spark.sparkContext.parallelize(data_array)

print("RDD from array:", data_rdd.collect())

spark.stop()
```

3. Exec to spark-app-submit pod and run command `spark-submit --master spark://my-release-spark-master-svc:7077 /data/spark-main.py`

4. Check log spark-worker pod
<img width="2262" alt="Screenshot 2024-05-10 at 14 30 10" src="https://github.com/bitnami/charts/assets/31474164/6cfbbe0e-2436-436f-982f-0260c5cd2920">

5. Check log spark-master pod
<img width="1152" alt="Screenshot 2024-05-10 at 14 30 29" src="https://github.com/bitnami/charts/assets/31474164/84b37560-2ca7-4e5b-8b51-e02cd43d069e">

6. Run command stuck in the log of worker on a worker pod.
`/opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1024M -Dspark.driver.port=46801 -Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@spark-app-submit:46801 --executor-id 369 --hostname 10.244.0.7 --cores 1 --app-id app-20240510072155-0000 --worker-url spark://Worker@10.244.0.7:43481 --resourceProfileId 0`
<img width="2294" alt="Screenshot 2024-05-10 at 14 33 21" src="https://github.com/bitnami/charts/assets/31474164/32ea375d-0bea-443a-b4f8-6e3a0c30edcb">

**Comment by fmulero** [comment]
Point 6 in my opinion is a red herring. Not related with the original issue. 

I could reproduce the issue and this is what I can see in error output for each task execution:
```console
$ kubectl exec -it  my-release-spark-worker-0 -- find /opt/bitnami/spark/work/ -name stderr -exec cat {} \;
...
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
24/05/13 07:53:52 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 197@my-release-spark-worker-0
24/05/13 07:53:52 INFO SignalUtils: Registering signal handler for TERM
24/05/13 07:53:52 INFO SignalUtils: Registering signal handler for HUP
24/05/13 07:53:52 INFO SignalUtils: Registering signal handler for INT
24/05/13 07:53:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/05/13 07:53:53 INFO SecurityManager: Changing view acls to: spark
24/05/13 07:53:53 INFO SecurityManager: Changing modify acls to: spark
24/05/13 07:53:53 INFO SecurityManager: Changing view acls groups to: 
24/05/13 07:53:53 INFO SecurityManager: Changing modify acls groups to: 
24/05/13 07:53:53 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark; groups with view permissions: EMPTY; users with modify permissions: spark; groups with modify permissions: EMPTY
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:429)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:418)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:449)
        at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
        at scala.collection.immutable.Range.foreach(Range.scala:158)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:447)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
        at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:439)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        ... 4 more
Caused by: java.io.IOException: Failed to connect to spark-app-submit/<unresolved>:42385
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
        at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.net.UnknownHostException: spark-app-submit
...
```

Workers are trying to return the output of your application to  `spark-app-submit` hostname, but that name can not be resolved. To solve that problem you have different options:
* Configure/publish your app to use the pod IP instead of the hostname. Please refer to Spark documentation.
* Configure a kubernetes service with `spark-app-submit` name, selecting your pod. Please refer kubernetes documentation.
* Configure a different service for your pod and set `setHostnameAsFQDN `. Please refer kubernetes documentation.
* Add a record for `spark-app-submit`to your DNS server

**Comment by anhlevfx** [comment]
Thank you @fmulero . I will try your suggestion. The issue can close.
