### ISSUE TITLE
bitnami/nats - unable to override configs due to which metrics(nats-exporter) container is not created

### ISSUE THREAD

**Issue by satyanand0045** [bitnami/charts#25312]
### Name and Version

bitnami/nats 8.0.1

### What is the problem this feature will solve?

Hi Team,

I tried to override configs in bitnami nats values.yaml as per the requirement but post deployment I see the values are not picked. I tried giving "" to the variable values, still I don't see the config reflecting.
 I'm unable to enable metrics container (side car container) and disable auth and unable to override other configs too.

https://github.com/bitnami/charts/blob/main/bitnami/nats/values.yaml

Request you to help.

### What is the feature you are proposing to solve the problem?

Please help how to fix the issue.

**Comment by carrodher** [comment]
Could you please share how are you modifying the default values and how are you deploying the Helm chart?

**Comment by satyanand0045** [comment]
Hi Team, Issue is fixed. Thank you.
