### ISSUE TITLE
[bitnami/thanos] Add support for `endpoint-group` in store gateway

### ISSUE THREAD

**Issue by verejoel** [bitnami/charts#25317]
### Name and Version

bitnami/thanos 15.1.0

### What is the problem this feature will solve?

HA Store replicas are references using the `endpoint` rather than the `endpoint-group` flag. This means fanout is used, rather than round-robin.

### What is the feature you are proposing to solve the problem?

Highly available store API components should be referenced using the `endpoint-group` flag, instead of `endpoint`. This uses round-robing rather than fan-out to distribute requests.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
