### ISSUE TITLE
[bitnami/kafka] Migrate data from Confluent Kafka to Bitnami Kafka

### ISSUE THREAD

**Issue by opatil-vibrent** [bitnami/charts#25332]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

We have a very old version of Confluent Kafka running on our kubernetes cluster, cp-kafka:5.4.1 and we are now moving to the bitnami kafka latest version. How can I migrate all my data from my old Kafka installation to the new one? I tried running mirror maker in a docker container on the same cluster but the mirror maker does not copy the data nor it shows any logs. I am using Mirror Maker from Kafka 2.8.1. When I try to run Mirror Maker to copy data from one confluent kafka installation to another it works but does not work with Bitnami Kafka.

Is it possible to migrate data from Confluent Kafka to Bitnami Kafka using Mirror Maker? If not, what is the correct way to do it?

### What is the feature you are proposing to solve the problem?

If the mirror-maker is not the way to copy data from confluent Kafka to Bitnami Kafka can someone please let me know the correct way to do it?

**Comment by rafariossaa** [comment]
Hi, I am not a kafka expert, but for this use case I would suggest to ask in kafka forums as this might be very tied to confluent kaftka. The procedure should not be dissimilar to any other kafka to kafka migration.
