### ISSUE TITLE
[bitnami/minio] Versioning cannot be enabled in standalone mode

### ISSUE THREAD

**Issue by austince** [bitnami/charts#25341]
### Name and Version

bitnami/minio 14.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy the chart in standalone mode with a provisioned bucket, versioning enabled
2. Open the minio console and view the bucket config
3. See the versioning is not enabled

### Are you using any custom parameters or values?

```yaml
mode: standalone

provisioning:
  enabled: true
  buckets:
   - name: test
     versioning: true
```

### What is the expected behavior?

The provisioning job enables versioning on the bucket. 

### What do you see instead?

The provisioning job excludes the versioning in standalone mode. 

### Additional information

It seems as of https://github.com/bitnami/charts/pull/9301#issue-1159940460, versioning was not supported in standalone mode. This is not mentioned in [the current docs](https://min.io/docs/minio/kubernetes/upstream/administration/object-management/object-versioning.html), and it is possible to configure buckets in standalone mode to be versioned manually.

**Comment by austince** [comment]
Validated in a local chart change: 

```
Defaulted container "minio" out of: minio, wait-for-available-minio (init)
Start Minio provisioning
Added `provisioning` successfully.
Restart command successfully sent to `provisioning`. Type Ctrl-C to quit or wait to follow the status of the restart process.
┌────────────────┬────────┐
│ HOST           │ STATUS │
├────────────────┼────────┤
│ 127.0.0.1:9000 │ ✔      │
└────────────────┴────────┘

Restarted `provisioning` successfully in 564 milliseconds
Bucket created successfully `provisioning/test`.
provisioning/test versioning is enabled
End Minio provisioning
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
