### ISSUE TITLE
Typo: "NetworkPolice" vs "NetworkPolicy" (across many charts)

### ISSUE THREAD

**Issue by SeanKilleen** [bitnami/charts#25347]
### Name and Version

multiple charts, multiple versions (docs only)

### What architecture are you using?

None

### What steps will reproduce the bug?

This is a documentation-only bug.

I noticed that while browsing through that many items say `Add extra ingress rules to the NetworkPolice`, but right next to it shows `Add extra egress rules to the NetworkPolicy` and the text is often on a property that includes `networkPolicy`. 

I figure I'll do a small PR to cleanup the docs, since I happened to come across it while reading.

https://github.com/search?q=repo%3Abitnami%2Fcharts%20NetworkPolice&type=code

### What do you see instead?

`NetworkPolice` when the text means `NetworkPolicy`

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
