### ISSUE TITLE
Whether to support minio cluster expansion

### ISSUE THREAD

**Issue by kubecto** [bitnami/charts#25357]
### Name and Version

bitnami/minio

### What is the problem this feature will solve?

Supports minio cluster expansion

### What is the feature you are proposing to solve the problem?

When the minio cluster resources are insufficient, you can add a new minio cluster to expand the minio capacity

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kubecto** [comment]
Personally feel statefulset, not very good implementation, because minio is based on the ordered host name to component cluster, when the second cluster is created, the host name statefulset name starts from 0, it seems to re-implement a cr controller to achieve

**Comment by mhkarimi1383** [comment]
@carrodher 
There is no way to expand the cluster right now?
