### ISSUE TITLE
ArgoCD Notifications Enable

### ISSUE THREAD

**Issue by troyanskiy** [bitnami/charts#25373]
### Name and Version

bitnami/argocd 6.0.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install argocd from helm with notification.enabled=true

### What is the expected behavior?

Expect notifications pod to start

### What do you see instead?

Notifications Pod not started
Logs:
```
16:32:31.53 INFO  ==> 
 16:32:31.53 INFO  ==> Welcome to the Bitnami argo-cd container
 16:32:31.53 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 16:32:31.53 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 16:32:31.54 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
 16:32:31.54 INFO  ==> 
 16:32:31.54 INFO  ==> Configuring libnss_wrapper

time="2024-04-24T16:32:32Z" level=fatal msg="invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"
```

**Comment by dgomezleon** [comment]
Hi @troyanskiy 

It does not seems to be related to the charts. You can take a look [at this answer](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1234#issuecomment-787936210) or [this](https://stackoverflow.com/questions/61903086/error-no-configuration-has-been-provided-try-setting-kubernetes-master-environ).

I hope it helps

**Comment by troyanskiy** [comment]
Hi @dgomezleon 

That did not help, or I was doing something wrong.

I have k3s installation v1.29.3+k3s1

And using lens I've installed from helm charts argo-cd.
Just enabling `notifications.enabled=true` I have in the logs message above.

It seems in the notifications container it tries to use api server, but it does not have k8s config file.
I have on the host config file in `/etc/rancher/k3s/k3s.yaml` which I've added on host to `.bashrc`

Do I need to take the config file and mount it into the pod (deployment)?

**Comment by dgomezleon** [comment]
Sorry to hear that. I could not reproduce the issue on AKS, EKS, or GKE, so it does not seem related to the chart itself. Unfortunately, I'm unfamiliar with k3s, but I will keep it open in case someone with more knowledge can help. 

I also could see a similar issue on [this post](https://medium.com/@k.sahanshah/deploy-a-two-node-k3s-cluster-in-oracle-d57351c7ca4#:~:text=error%3A%20no%20configuration%20has%20been%20provided%2C%20try%20setting%20KUBERNETES_MASTER%20environment%20variable) in case it helps.

**Comment by troyanskiy** [comment]
@dgomezleon I've tried that as well and it did not help.

I will dig a bit later and post a solution here for future.

Thanks @dgomezleon for your help.

**Comment by ktzsolt** [comment]
I am hitting the exact same error in the notifications container log for the 6.0.10 version of the chart. With 5.2.1 it was working fine I have "bisect"ed that it is working in 5.4.5 chart version and breaks in 5.5.0 version with the error message OP provided:
  
    level=fatal msg="invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"

**Comment by ktzsolt** [comment]
This is the commit that made the regression: https://github.com/bitnami/charts/commit/0e6b8edaf2a48d36a717bf90292b302917ac08e4

Setting back `notifications.serviceAccount.automountServiceAccountToken` to true in values, as it was in 5.4.5, "fixes" this:

        notifications:
          enabled: true
          serviceAccount:
            automountServiceAccountToken: true

This is just a workaround, any idea about what should be the right setup?

**Comment by troyanskiy** [comment]
Hi @ktzsolt 

Thank you for the investigation!

I confirm with your workaround I have working notifications controller and I've received notification.

ArgoCD Chart Version: 6.0.14
On K3S Version: v1.29.3+k3s1

**Comment by dgomezleon** [comment]
Thanks @ktzsolt ,

I introduced a typo when testing it so I could not reproduce it. After reproducing it I created a [PR](https://github.com/bitnami/charts/pull/25561) to solve the issue.
