### ISSUE TITLE
cloudflare-dns-records-per-page for external-dns

### ISSUE THREAD

**Issue by devcube9** [bitnami/charts#25370]
### Name and Version

bitnami/external-dns 0.14.1

### What is the problem this feature will solve?

There's no way to pass --cloudflare-dns-records-per-page to external-dns

### What is the feature you are proposing to solve the problem?

add cloudflare.dnsRecordsPerPage to values.yaml and modify dep-ds.yaml to use that value

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
