### ISSUE TITLE
[bitnami/influxdb] Flux support

### ISSUE THREAD

**Issue by lelithium** [bitnami/charts#2537]
**Which chart**:
`bitnami/influxdb:0.4.7`

**Describe the bug**
The chart doesn't support having Flux support enabled (https://docs.influxdata.com/influxdb/v1.8/administration/config/#flux-enabled-false)

**To Reproduce**

Minimal values file to trigger the bug:
```yaml
influxdb:
        extraEnvVars:
                - name: INFLUXDB_HTTP_FLUX_ENABLED
                  value: "true"
```

```bash
helm install fluxbug bitnami/influxdb --values values.yaml
```

**Expected behavior**
I expected the chart to support Flux and not error out.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
---
Here's some more info:
1. Using this values file to install the chart:
```yaml
influxdb:
        extraEnvVars:
                - name: INFLUXDB_HTTP_FLUX_ENABLED
                  value: "true"
image:
        debug: true
```
I can get the debug output of Influx when it crashes.
```
influxdb 14:42:18.28 
influxdb 14:42:18.28 Welcome to the Bitnami influxdb container
influxdb 14:42:18.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-influxdb
influxdb 14:42:18.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-influxdb/issues
influxdb 14:42:18.29 Send us your feedback at containers@bitnami.com
influxdb 14:42:18.29 
influxdb 14:42:18.29 INFO  ==> ** Starting InfluxDB setup **
influxdb 14:42:18.31 DEBUG ==> Validating settings in INFLUXDB_* env vars...
influxdb 14:42:18.32 INFO  ==> Initializing InfluxDB...
influxdb 14:42:18.32 INFO  ==> No injected configuration files found. Creating default config files...
influxdb 14:42:18.32 INFO  ==> Deploying InfluxDB from scratch
influxdb 14:42:18.32 INFO  ==> Starting InfluxDB in background...
ts=2020-05-06T14:42:18.345907Z lvl=info msg="InfluxDB starting" log_id=0MbbqQQG000 version=1.8.0 branch=1.8 commit=781490de48220d7695a05c29e5a36f550a4568f5
ts=2020-05-06T14:42:18.345928Z lvl=info msg="Go runtime" log_id=0MbbqQQG000 version=go1.13.8 maxprocs=2
[tcp] 2020/05/06 14:42:18 tcp.Mux: cannot read header byte: EOF
influxdb 14:42:18.84 INFO  ==> Creating users and databases...
influxdb 14:42:18.84 DEBUG ==> Creating admin user...
Failed to connect to http://127.0.0.1:8086: Get http://127.0.0.1:8086/ping: dial tcp 127.0.0.1:8086: connect: connection refused
Please check your connection settings and ensure 'influxd' is running.
influxdb 14:42:18.87 INFO  ==> Stopping InfluxDB...
Terminated
```
I think the culprit is this line
```
[tcp] 2020/05/06 14:42:18 tcp.Mux: cannot read header byte: EOF
```
But I haven't had time to look into why this is occuring

2. The bug also occurs with the `high-availability` architecture

**Comment by miguelaeh** [comment]
Hi @lelithium ,
Thank you very much for reporting the issue.
I would say the error could reside on the image, we will take a look in deeper to this issue. Nevertheless, as we have limited resources I cannot provide you with an estimated date.

**Comment by lelithium** [comment]
Hi @miguelaeh,

Thanks for your quick answer. I was able to reproduce the issue using the raw docker image. I'll open an issue in the right repo, and link to this one.

**Comment by miguelaeh** [comment]
Thanks @lelithium ,
I already created a task on our side to check this.
Regards

**Comment by lelithium** [comment]
The underlying issue has been fixed (see https://github.com/bitnami/bitnami-docker-influxdb/pull/2), which has solved the issue on my end **when manually specifying the image*

values_current.yaml
```yaml
influxdb:
        extraEnvVars:
                - name: INFLUXDB_HTTP_FLUX_ENABLED
                  value: "true"
```

values_fixed.yaml
```yaml
influxdb:
        extraEnvVars:
                - name: INFLUXDB_HTTP_FLUX_ENABLED
                  value: "true"
image:
        tag: 1.8.0-debian-10-r60
```

```bash
helm3 install current bitnami/influxdb --values values_current.yaml
# yields the same error as in initial issue
helm3 install fixed bitnami/influxdb --values values_fixed.yaml
# works without issue
```

I'm not sure how the CI updates tags on this chart, but I think it's safe to use this new tag unto the chart (`r60` is the latest as of writing)

**Comment by miguelaeh** [comment]
Hi @lelithium ,
thanks for the information. The tags are updated in every PR to the `bitnami/chart` repo by our CI. That's why we tell the users to wait until the tags are updated before merge the PRs.

**Comment by lelithium** [comment]
Hi @miguelaeh, that makes sense. Are there any steps I should take to have this new image tag incorporated unto a new version ? Or is the ball on bitnami's side to use the CI to upgrade ? I'm 100% OK with opening a PR myself on this repo if that's what's needed

**Comment by miguelaeh** [comment]
Hi @lelithium ,
I forced a new release on our side to update the tags. Now they are using the latest ones: https://github.com/bitnami/charts/commit/6ef7bcde81395854bf408d04f065ce93931d8cd8#diff-ee387abc9aa8a623b2074e83d06f6bf2

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
