### ISSUE TITLE
[bitnami/apache-apisix] Issue deploying the chart

### ISSUE THREAD

**Issue by Asakaigg** [bitnami/charts#25385]
Hi
I hope you are doing well 
I am using Apache Apisix and when I installed the apisix but the pods were not running for four replicas 
I hope you help me with this 
![image](https://github.com/bitnami/charts/assets/165806253/0487f231-0da9-44eb-bafe-ef050663d62b)

**Comment by Asakaigg** [comment]
HI 
I hope you are doing well 
I am using apache apisix and when I installed the apisix but the pods are not running for four replicas 
I hope you help me on this 
![image](https://github.com/bitnami/charts/assets/165806253/0487f231-0da9-44eb-bafe-ef050663d62b)

**Comment by carrodher** [comment]
Could you please provide more info about how the Helm chart is being deployed and the values you're using?
