### ISSUE TITLE
kube_namespace_labels metrics missing

### ISSUE THREAD

**Issue by Mapmo** [bitnami/charts#25380]
### Name and Version

bitnami/kube-metrics 4.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On Kubernetes cluster with rke2 v1.29.0, the Prometheus metrics kube_namespace_labels disappeared after upgrading to the latest kube-prometheus version. Other Kube metrics are still getting collected as before. The namespace labels were not changed and are still there.

### Are you using any custom parameters or values?

Not updating anything related to kube-metrics when deploying the helm chart

### What is the expected behavior?

Seeing metrics for kube_namespace_labels

### What do you see instead?

Not seeing them

**Comment by jotamartos** [comment]
Hi @Mapmo,

Thank you for using Bitnami. It seems that's expected from version 2.10.x

https://github.com/kubernetes/kube-state-metrics/issues/2297

Please configure the required parameters using the extraArgs field

```
diff --git a/bitnami/kube-state-metrics/values.yaml b/bitnami/kube-state-metrics/values.yaml
index 7ca8c8bcf3..0a83cd1ec3 100644
--- a/bitnami/kube-state-metrics/values.yaml
+++ b/bitnami/kube-state-metrics/values.yaml
@@ -129,7 +129,8 @@ image:
 ## Example:
 ## extraArgs:
 ##    metric-labels-allowlist: pods=[*]
-extraArgs: {}
+extraArgs:
+  metric-labels-allowlist: namespaces=[*]
 ## @param command Override default container command (useful when using custom images)
 ##
 command: []
```

![Screenshot 2024-05-07 at 11 20 23](https://github.com/bitnami/charts/assets/8791635/498605a7-38c2-442b-ac47-968aae4aa7f1)

**Comment by Mapmo** [comment]
Thank you @jotamartos . So this is an intended functionality that makes newer version non-backward compatible with older versions?

**Comment by jotamartos** [comment]
It seems they change the way the application works. You can create an issue in their repos to get more information about the change.

**Comment by Mapmo** [comment]
Okay, thank you very much
