### ISSUE TITLE
[bitnami/rabbitmq] RBAC Rules for RabbitMQ

### ISSUE THREAD

**Issue by ChristianRaoulis** [bitnami/charts#25387]
### Name and Version

bitnami/rabbitmq 14.0.2

### What is the problem this feature will solve?

i'm using Cyberark Conjur in my K8s Plattform and need to bind an extra role to the service account which allows the account to read the k8s secret.

I've done something similar to my keycloak chart using the [rbac.rules](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L897) option.

### What is the feature you are proposing to solve the problem?

Adding the `rbac.rules` option to the rabbitmq chart

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! Would you like to submit a PR adding the value? If not, we will work on it, but as it is not a critical feature, we cannot guarantee an ETA.
