### ISSUE TITLE
[bitnami/redis] Supported versions of Redis are not documented

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#25395]
### Name and Version

bitnami/redis, bitnami/redis-cluster

### What is the problem this feature will solve?

I'm trying to understand what versions of Redis the current Helm Chart supports for install / upgrade. Right now the Helm Chart define a default version of Redis, but nothing about the supported  versions or about a possible upgrade path that can be followed just by changing the version in the values.yaml.

### What is the feature you are proposing to solve the problem?

Compatibility matrix with the supported versions of Redis that can be used with the current Helm Chart for Install / Upgrade.

### What alternatives have you considered?

A simple answer will help me move forward, and in the future, will be nice to have this documented somewhere (this apply for both redis + redis-cluster)

**Comment by javsalgar** [comment]
Hi!

In general, we provide images for the branches supported in the upstream project. Right now 6.2.x, 7.0.x and 7.2.x. However, we have only tested and verified the helm chart with the image set in the values.yaml file. Technically, it is possible to switch images from those supported branches but this is not something we have verified. 

Regarding upgrade paths, normally helm upgrade should do the trick when working with patch and minor versions. About major versions, in the README.md you should find notes about what to expect from this major and if there is a special upgrade path different from helm upgrade. 

When working major changes of the application itself (one thing is the chart version and another the app version, but a major app version bump always implies a chart version bump), we usually recommend the instructions from upstream.
