### ISSUE TITLE
[bitnami/mediawiki] Unable to use $wgAllowImageTag in LocalSettings.php

### ISSUE THREAD

**Issue by iain-ilearner** [bitnami/charts#25394]
### Name and Version

bitnami/mediawiki 20.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install minimal chart release 
```
helm install my-release oci://registry-1.docker.io/bitnamicharts/mediawiki \
    --set mediawikiHost=wiki.example.org \
    --set service.type=ClusterIP
```
2. Observe that the pods start successfully and become ready.
3. Scale MediaWiki deploy down and back up again
```
kubectl scale deploy/my-release-mediawiki --replicas 0
kubectl scale deploy/my-release-mediawiki --replicas 1
```
4. Observe that a new pod starts successfully and becomes ready.
5. Inject the bad config.
```
kubectl exec -it deploy/my-release-mediawiki -- /bin/bash -c 'echo "\$wgAllowImageTag = true;" >> /bitnami/mediawiki/LocalSettings.php'
```
6. Cycle the pods again
```
kubectl scale deploy/my-release-mediawiki --replicas 0
kubectl scale deploy/my-release-mediawiki --replicas 1
```
7. Observe that the new pod never starts successfully nor becomes ready.

### What do you see instead?

After the following lines in the logs, the container enters a crash loop, never becoming ready.
```
    mediawiki 15:29:12.53 INFO  ==> Restoring persisted MediaWiki installation
    mediawiki 15:29:12.85 INFO  ==> Trying to connect to the database server
```
I'd already narrowed the problem down to that PHP variable, and suspected it was probably related to the PHP Notice that gets emitted.
My suspicions were confirmed when I enabled `BITNAMI_DEBUG` to report this issue.
```
    mediawiki 15:29:12.53 INFO  ==> Restoring persisted MediaWiki installation
    mediawiki 15:29:12.85 INFO  ==> Trying to connect to the database server
    mediawiki 15:29:12.89 DEBUG ==> Getting $wgDBserver from MediaWiki configuration
    mediawiki 15:29:12.92 DEBUG ==> ^\s*(//\s*)?\$wgDBserver\s*=([^;]+);
    mediawiki 15:29:13.01 DEBUG ==> Getting $wgDBname from MediaWiki configuration
    mediawiki 15:29:13.04 DEBUG ==> ^\s*(//\s*)?\$wgDBname\s*=([^;]+);
    mediawiki 15:29:13.10 DEBUG ==> Getting $wgDBuser from MediaWiki configuration
    mediawiki 15:29:13.10 DEBUG ==> ^\s*(//\s*)?\$wgDBuser\s*=([^;]+);
    mediawiki 15:29:13.11 DEBUG ==> Getting $wgDBpassword from MediaWiki configuration
    mediawiki 15:29:13.29 DEBUG ==> ^\s*(//\s*)?\$wgDBpassword\s*=([^;]+);
    mediawiki 15:29:13.30 DEBUG ==> Executing SQL command:
    SELECT 1
    /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
    1
    Some of your configuration settings caused a warning:
    
    * AllowImageTag is deprecated: since 1.35; register an extension tag named
      <img> instead.
    
    Please correct the issue before running update.php again.
    If you know what you are doing, you can bypass this check
    using --skip-config-validation.
```

### Additional information

The `$wgAllowImageTag` setting has been deprecated by MediaWiki, but it shouldn't stop the pod from starting. I suggest `--skip-config-validation` is probably desired during pod start-up, or at least raise the error at a higher log level.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by carrodher** [comment]
Thanks for the detailed information. To unify efforts we'll close this ticket in favor of the one created in the containers repo. Let's continue there.
