### ISSUE TITLE
fluentd initContainers lack resources configuration

### ISSUE THREAD

**Issue by dr4Ke** [bitnami/charts#25390]
### Name and Version

bitnami/fluentd 6.1.1

### What is the problem this feature will solve?

In the case of a resourceQuota is set on the namespace, the pod cannot start because of this lack of resource definition.

### What is the feature you are proposing to solve the problem?

Add default resource definitions for mandatory initContainers. And/or add a setting in values.yaml.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
