### ISSUE TITLE
[bitnami/elasticsearch] Istio showing Passthrough traffic among Elastic Pods

### ISSUE THREAD

**Issue by irizzant** [bitnami/charts#2539]
**Which chart**:
Elasticsearch version 12.0.1

**Describe the bug**
Kiali dashboard shows that there is Passthrough traffic on port 9200 and 9300 anong Elastic Pods, which should be instead monitored by Istio and reported as part of the service mesh.

**To Reproduce**
1. Deploy Istio 1.5.2
1. Enable auto sidecar injection in the namespace
1. Deploy the chart with values production
1. Open Kiali and check the mesh graph, it shows Passthrough traffic among Elastic nodes

**Expected behavior**
No Passthrough traffic should happen among nodes

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR! We will continue the discussion there :)
