### ISSUE TITLE
[bitnami/opencart]  ERROR: You did not provide an external host in your 'helm install' call 

### ISSUE THREAD

**Issue by marangiop** [bitnami/charts#2541]
**Which chart**:
opencart (version 7.0.15)

**Describe the bug**
Trying to install the chart on Kubernetes cluster. I get error above (see screenshots error part 1 and 2). I follow suggestions. I export APP_DATABASE_PASSWORD and APP_PASSWORD to variables, but export of APP_HOST gives me error (see error part 3 screenshot). I then successfully upgrade by putting FQDN of desired Opencart service as localhost, but I get more problems: mariadb and opencart pods have both "pending" status, and number of available opencart pods is 0. ( see successful upgrade but more problems screenshot)

**To Reproduce**
See attached screenshots in the following order 
error_part1
error_part2
error_part3
successful upgrade but more problems

**Expected behavior**
Smooth installation, 1 opencart pod available after installation, OpenCart deployed at my desired Host

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

![error_part1](https://user-images.githubusercontent.com/29339953/81212421-2af92b00-8fd5-11ea-983a-55bc4d0ad7ec.PNG)
![error_part2](https://user-images.githubusercontent.com/29339953/81212424-2b91c180-8fd5-11ea-86a4-b5e40fce099f.PNG)
![error_part3](https://user-images.githubusercontent.com/29339953/81213106-30a34080-8fd6-11ea-87d0-da91f6594e98.PNG)
![successful upgrade but more problems](https://user-images.githubusercontent.com/29339953/81213569-d787dc80-8fd6-11ea-9388-2fde153c9640.PNG)

**Comment by marcosbc** [comment]
The LoadBalancer IP may take a few minutes to appear. If still it does not work, it could be possible your cluster does not have a LoadBalancer provider (i.e. Minikube), or it is not configured properly (i.e. missing annotations). Could you check if that is the case?

You can also consider enabling Ingress, which usually gives less problems.

**Comment by marangiop** [comment]
Hi @marcosbc , thank you for your reply. I am not sure how to check if my cluster has LoadBalancer enabled or its configuration, but I can tellyou  that all my services on my cluster are either ClusterIP or NodePort type. There are no LoadBalancer type of services so I can infer that probably LoadBalancer is not configured and NodePort is probably what I need...

Anyhow, I have changed the type of service of "my-release-opencart" container to NodePort and it still was not working. So I am now looking into setting up an Ingress to this service as you suggested. 

Below is an ingress I have created. Does this look sensible?
![image](https://user-images.githubusercontent.com/29339953/81556822-3fe60d80-938b-11ea-9a1f-bf54446a9be9.png)

I have run this ingress, but I am not sure whether address is correct. Any ideas as to how to move forward?
![image](https://user-images.githubusercontent.com/29339953/81556899-60ae6300-938b-11ea-8988-e12d9ba2d19b.png)

This is the output when I curl the host:
![image](https://user-images.githubusercontent.com/29339953/81557011-90f60180-938b-11ea-8cec-158d912544f8.png)

**Comment by marcosbc** [comment]
AFAIK you don't need to create a specific Ingress resource, the chart already does that for you with `--set ingress.enabled=true`. You can check extra configurations in the "ingress:" section of "values.yaml".

Check the following tutorial which shows you how to configure the Joomla chart with Ingress: https://docs.bitnami.com/tutorials/secure-kubernetes-services-with-ingress-tls-letsencrypt/. The process is almost identical for OpenCart. It also covers how to configure NGINX Ingress Controller so it works with your cluster, in case you don't have any Ingress Controller enabled yet.
