### ISSUE TITLE
[bitnami/redis] From the parameters .Values.sentinel.service.loadBalancerIP is applied to two services, therefore one is in waiting status

### ISSUE THREAD

**Issue by ehuzii** [bitnami/charts#25419]
### Name and Version

bitnami/redis 19.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

If I use LoadBalancer for the Sentinel service, and set my own IP address for LoadBalancer, the chart creates two services:
service
service-master

and uses .Values.sentinel.service.loadBalancerIP for each:
https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/sentinel/service.yaml#L35C22-L35C61
https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/sentinel/service.yaml#L123

### Are you using any custom parameters or values?

sentinel:
  service:
    type: LoadBalancer
    loadBalancerIP: "10.1.1.1"

### What is the expected behavior?

it would be great to add the ability to define a separate loadbalacerIP for sentinel.service.createMaster, and ideally define the service type for sentinel.service and sentinel.service.createMaster separately.
since in our case the loadbalancer is needed only for the master.

### What do you see instead?

currently I see two services, one of which hangs in waiting status, as the ip address is busy

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I will forward this to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR separating the values?
