### ISSUE TITLE
[bitnami/nginx] deployment fail because of OpenShift restricted-v2

### ISSUE THREAD

**Issue by antoinetran** [bitnami/charts#25425]
### Name and Version

bitnami/nginx 16.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.  `helm upgrade --install my-nginx bitnami/nginx --set global.compatibility.openshift.adaptSecurityContext=true --version 16.0.3`

### Are you using any custom parameters or values?

Yes see beyond "What steps will reproduce the bug?"

### What is the expected behavior?

Deployment OK

### What do you see instead?

Deployment KO with nginx pods saying:
```
is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 1001: must be in the ranges:
```

### Additional information

Analysis:
This is because the renderSecurityContext is missing for the initContainer only: see https://github.com/bitnami/charts/blob/main/bitnami/nginx/templates/deployment.yaml#L83
What is currently in code:
```
securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
```
What should be in code:
```
securityContext:  {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.podSecurityContext "context" $) | nindent 12 }}
```

**Comment by antoinetran** [comment]
Workaround: set values.yaml like this, and it works
```
global:
  compatibility:
    openshift:
      adaptSecurityContext: "force"
containerSecurityContext:
  runAsUser: null
  runAsGroup: null
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by antoinetran** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Ok, I tried with this pull request :)

**Comment by darren-bell-optiva** [comment]
Hi. This same problem exists for the nginx-ingress-controller https://github.com/bitnami/charts/blob/43ccdb2e902638fb493ace373c0756f336472c69/bitnami/nginx-ingress-controller/templates/controller-deployment.yaml#L81 and also the daemonset

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by antoinetran** [comment]
> Hi. This same problem exists for the nginx-ingress-controller
> 
> https://github.com/bitnami/charts/blob/43ccdb2e902638fb493ace373c0756f336472c69/bitnami/nginx-ingress-controller/templates/controller-deployment.yaml#L81
> and also the daemonset

I don't mind, I added the fix in my branch too for nginx-ingress-controller.
