### ISSUE TITLE
[bitnami/etcd] chart should include PodDisruptionBudget

### ISSUE THREAD

**Issue by dbaumgarten** [bitnami/charts#2542]
**Which chart**:
The etcd chart

**Is your feature request related to a problem? Please describe.**
Pod evictions (for example because of a node-drain) can make etcd unavailable.

**Describe the solution you'd like**
Add a PodDisruptionBudget for the etcd-pods that ensures that a majority of pods is available.

**Describe alternatives you've considered**
Every user of the chart could add the PodDisruptionBudget by himself.

**Comment by carrodher** [comment]
Thanks for the suggestions, I just created the above PR implementing it, once reviewed and released the issue will be closed automatically.
