### ISSUE TITLE
[bitnami/minio] Possibility to create default accessKeys

### ISSUE THREAD

**Issue by ammirator-administrator** [bitnami/charts#25433]
### Name and Version

bitnami/minio 14.3.0

### What is the problem this feature will solve?

There is no way to add a default accessKey, I think in the original chart from minio there was such possibility
At the moment we have to create these manually, but when doing local development it is common to kill a cluster and restart it for example if using minikube etc etc, so it becomes annoying every time to create these manually

At the moment in the provisioning job there is a possibility to create default buckets and default users, but no option to creat default accessKeys

### What is the feature you are proposing to solve the problem?

Add some field at the provisioning level like:
```
accessKeys:
  - accessKeyId: <...>
    accessKeySecret: <...>
```

### What alternatives have you considered?

No alternatives at the moment, just creating manually which is not a enjoying thing

**Comment by javsalgar** [comment]
Hi!

In the provisioning job, there is an extraCommands section
```

              {{- if .Values.provisioning.extraCommands }}
              {{ join ";" .Values.provisioning.extraCommands | nindent 14 }};
              {{- end }}

```

Would this help to create these access keys?

**Comment by ammirator-administrator** [comment]
@javsalgar 
Thanks

Yes I used this alongside the `mc` command from minio 
In case someone needs that , here is a example
```
  extraCommands:
    # Delete key if exists ( || true, so that the command doesn't fail if is first run and key doesn't exists)
    - |
      mc admin user svcacct rm provisioning $S3_MINIO_ON_PREM_ACCESS_KEY_ID || true
    # Re-create with new values if these changed
    - |
      mc admin user svcacct add --access-key $S3_MINIO_ACCESS_KEY_ID --secret-key $S3_MINIO_ACCESS_SECRET provisioning $S3_MINIO_ADMIN_USERNAME

```

**Comment by ndrslmpk** [comment]
Can you elaborate on where to add this?
