### ISSUE TITLE
[bitnami/minio] When minio adds the buckets created, it sets the public read permission for buckets, hope add in the provisioning-job.yaml

### ISSUE THREAD

**Issue by liuxin638507** [bitnami/charts#25437]
### Name and Version

bitnami/minio

### What is the problem this feature will solve?

When minio adds the buckets created, it sets the public read permission for buckets

### What is the feature you are proposing to solve the problem?

When minio adds the buckets created, it sets the public read permission for buckets
this is my job
```yaml
            - "/bin/bash"
            - "-c"
            - |
              set -e
              ############################################
              # MinIO 
              MINIO_HOST="http://minio:9000"
              MINIO_ACCESS_KEY={{ .Values.auth.rootUser }}
              MINIO_SECRET_KEY={{ .Values.auth.rootPassword }}

              # BUCKET_LIST
              BUCKET_LIST=("test1" "test2" "test3")
              ############################################

              while true; do
                if curl --output /dev/null --silent --head --fail $MINIO_HOST/minio/health/live; then
                  echo "$MINIO_HOST 检测成功"
                  break
                  else
                    echo "$MINIO_HOST 检测失败"
                    sleep 5
                  fi
                done
              mc config host add myminio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

              for bucket in ${BUCKET_LIST[@]}; do
                if ! mc ls myminio/$bucket >/dev/null 2>&1; then
                  mc mb myminio/$bucket
                  echo "Bucket $bucket created."
                  mc anonymous set download myminio/$bucket
                else
                  echo "Bucket $bucket already exists."
                  if mc anonymous get myminio/$bucket | grep 'download' >/dev/null 2>&1; then
                    echo Access permission for $bucket is set true
                  else
                    mc anonymous set download myminio/$bucket
                  fi
                fi
              done
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by liuxin638507** [comment]
> 感谢您提请我们注意此问题。感谢您的参与！如果您有兴趣提供解决方案，我们欢迎您创建拉取请求。Bitnami 团队很高兴审查您的提交并提供反馈。您可以[在此处](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md)找到贡献指南。
> 
> 您的贡献将极大地造福社区。如果您有任何问题或需要帮助，请随时与我们联系。

think you  ，I added a new line in provisioning-job.yaml to set permissions, which can also be set as variables
vim templates/provisioning-job.yaml
183               mc mb {{ $target }} --ignore-existing {{ $region }} {{ $withLock }};
184               mc anonymous set download {{ $target }};
