### ISSUE TITLE
[bitnami/etcd] chart should include settings for auto-compation

### ISSUE THREAD

**Issue by dbaumgarten** [bitnami/charts#2543]
**Which chart**:
Th etcd-chart

**Is your feature request related to a problem? Please describe.**
Without enabled auto-compaction the storage required by etcd grows over time until it hits a limit of etcd and crashes the server. This happens especially fast with write-heavy workloads.

**Describe the solution you'd like**
Etcd has an auto-compaction feature which can be enabled via env vars or flags. Add settings to the helm chart that allow the user to enable auto-compaction.

**Describe alternatives you've considered**
Users could modify the helm chart themselves to include the necessary env vars. But they would have to re-do this changes whenever they update the chart.

**Comment by andresbono** [comment]
Hi @dbaumgarten, the feature that you are suggesting seems logic. Would you like to open a PR implementing it? Contributions are more than welcome!

**Comment by dbaumgarten** [comment]
I would really like to do so, but I first have to clarify with my employer if and how I am allowed to contribute to open-source-projects on my work time.
I am pretty sure this will be possible, but it could take a while to get the official permission.

**Comment by mboutet** [comment]
@dbaumgarten, I would also like to have this feature. What did you have in mind in term of implementation?

**Comment by dbaumgarten** [comment]
I think the easiest way (and completely enough) would be to add two new settings to the chart that map directly (when set) to the etcd-parameters: --auto-compaction-mode and --auto-compaction-retention.
Setting these values by default would probably be nice (because sooner or later this will concern every single user), but this could possibly cause backwards compatibility issues.
Also, finding good default values would probably be hard.

**Comment by andresbono** [comment]
Keeping those flags disabled by default, but configurable, seems reasonable. At least for the first version of the implementation.

**Comment by maninderCiena** [comment]
Was facing same issue , will make changes and submit a PR.

**Comment by juan131** [comment]
https://github.com/bitnami/charts/pull/5755 was closed in favor of https://github.com/bitnami/charts/pull/5756
