### ISSUE TITLE
[bitnami/postgresql] Not able to deploy Bitnami Postgresql helm chart in Openshift

### ISSUE THREAD

**Issue by umamahiswari22** [bitnami/charts#25441]
### Name and Version

bitnami/postgresql:15.6.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Trying to deploy Bitnami Postgresql helm chart in Openshift cluster.
OCP version: 4.12

https://github.com/bitnami/charts/tree/main/bitnami/postgresql

Using Persistant volume.

Have modified the values.yaml, with the recommended values for openshift from the readme. i.e.

    For OpenShift 4.11 and higher, let set OpenShift the runAsUser and fsGroup automatically. Configure the pod and container security context to restrictive defaults and disable the volume permissions setup: primary. podSecurityContext.fsGroup=null,primary.podSecurityContext.seccompProfile.type=RuntimeDefault,primary.containerSecurityContext.runAsUser=null,primary.containerSecurityContext.allowPrivilegeEscalation=false,primary.containerSecurityContext.runAsNonRoot=true,primary.containerSecurityContext.seccompProfile.type=RuntimeDefault,primary.containerSecurityContext.capabilities.drop=['ALL'],volumePermissions.enabled=false,shmVolume.enabled=false

But after installing the helm chart, i get the below error

postgresql git:(sonarqube) ✗ oc logs pod/sonarqube-postgresql-0 exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error

Could someone please assist me in identifying what I might be overlooking? I'm encountering an issue while deploying the Bitnami PostgreSQL Helm chart in my OpenShift cluster. Specifically, I'm getting an error when trying to execute the entrypoint script (entrypoint.sh). The error message, "exec format error," suggests that there could be an issue with the script's format or execution or permission issues.

### Are you using any custom parameters or values?

yes

pushed the bitnami image to my private registry
custom secret to store postgre password 
storage class name 
and below values according to readme provided

   For OpenShift 4.11 and higher, let set OpenShift the runAsUser and fsGroup automatically. Configure the pod and container security context to restrictive defaults and disable the volume permissions setup: primary. podSecurityContext.fsGroup=null,primary.podSecurityContext.seccompProfile.type=RuntimeDefault,primary.containerSecurityContext.runAsUser=null,primary.containerSecurityContext.allowPrivilegeEscalation=false,primary.containerSecurityContext.runAsNonRoot=true,primary.containerSecurityContext.seccompProfile.type=RuntimeDefault,primary.containerSecurityContext.capabilities.drop=['ALL'],volumePermissions.enabled=false,shmVolume.enabled=false

### What is the expected behavior?

To be able to successfully deploy the hem chart in openshift cluster and for the DB pod  and service to be up and running.

### What do you see instead?

DB pod keeps crashing with the below error

postgresql git:(sonarqube) ✗ oc logs pod/sonarqube-postgresql-0 

exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error

**Comment by javsalgar** [comment]
Hi,

Which version of the helm chart are you deploying? Right now by default it will automatically remove all `fsGroup` and `runAsUser`/'runAsGroup` sections when deploying in Openshift. Could you confirm which version of the chart you are using?
