### ISSUE TITLE
[bitnami/harbor] Clair notifier 404 in logs

### ISSUE THREAD

**Issue by schnatterer** [bitnami/charts#2546]
**Which chart**:
Harbor

**Describe the bug**
Our Harbor Core log is flooded (one statement per second) with log statements such as this: 

```
2020/05/07 14:01:37.539 [D] [server.go:2807]  |     10.40.0.39| 404 |   2.173623ms| nomatch| POST     /service/notifications/clair
```

**To Reproduce**
1. Deploy chart
2. Check `kubectl logs ` on `harbor-core` pod

**Expected behavior**
No recurring 404 log statements

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Could that be cause by [this](https://github.com/bitnami/charts/blob/8dce093c90ad398fa2a76a911a4ce95af3d4e5c0/bitnami/harbor/conf/clair.yaml#L21) setting? 

It's not present in the [official chart](https://github.com/goharbor/harbor-helm/blob/af22cb82a02c3153210adbc94e80be7d5742cd85/conf/clair.yaml).

Or did you put it there for a specific reason, @marcostvz?

I tried removing it from the chart - the error is gone. But does this destroy some clair-related functionality?

**Comment by juan131** [comment]
Hi @schnatterer 

Could you please share the **values.yaml** you're using to deploy the Harbor chart?

@javsalgar could you please take a look to this too?

**Comment by schnatterer** [comment]
Hi @juan131, Thanks for getting back to me.

This occurs in production with managed databases and all. 
I'm still trying to reproduce it on a local cluster. On our local development version Clair has been deactivated until now.

**Comment by marcostvz** [comment]
@schnatterer I see they removed that section from the official chart in this commit: https://github.com/goharbor/harbor-helm/commit/0e721f02196456f2803bff4268c3cd3c2a772ea9

I suggest doing the same.

**Comment by javsalgar** [comment]
Hi,

In this PR I added that change. Thanks for reporting

https://github.com/bitnami/charts/pull/2544

**Comment by schnatterer** [comment]
Hi @marcostvz & @javsalgar, thanks for your efforts!

**Comment by juan131** [comment]
Removing "stale" label since the PR wasn't merged yet. We're working on Harbor 2.0 and it will be merged when releasing it.

**Comment by juan131** [comment]
Hi everyone,

Could you please give a try to the new major version (`6.0.0`) that includes the new major version of Harbor `2.0.0`? This issue was addressed on that major version.
