### ISSUE TITLE
Documentation update to backup/restore redis replication + sentinel

### ISSUE THREAD

**Issue by alita1991** [bitnami/charts#25469]
### Name and Version

bitnami/redis:7.2.4

### What is the problem this feature will solve?

Missing backup/restore procedure for replication + sentinel

### What is the feature you are proposing to solve the problem?

Procedure to backup/restore for replication + sentinel

### What alternatives have you considered?

A simple comment with the steps required or a link that maps with the default Helm Chart config

**Comment by carrodher** [comment]
Did you check https://github.com/bitnami/charts/tree/main/bitnami/redis#backup-and-restore?
