### ISSUE TITLE
[bitnami/kafka] how to enable the replicationfactor in new chart bitnami kafka 28.1.1 

### ISSUE THREAD

**Issue by Akashs12345** [bitnami/charts#25470]
### Name and Version

bitnami/kafka 28.1.1

### What is the problem this feature will solve?

we have downloaded the new helm chart Kafka for our env we are trying to give replication factor in values.yaml but we don't see any section saying replication factor please help us how can we configure 

### What is the feature you are proposing to solve the problem?

in our env we have 3 brokers and 3 controllers we have to configure the replication factor in the new chart to replicate all topics in all other brokers or controller

**Comment by Akashs12345** [comment]
please helm @bitnami-bot  @tompizmor

**Comment by Akashs12345** [comment]
@javsalgar please help

**Comment by carrodher** [comment]
There is a `provisioning.replicationFactor` parameter, see https://github.com/bitnami/charts/tree/main/bitnami/kafka#kafka-provisioning-parameters

**Comment by Akashs12345** [comment]
hi @carrodher, do you mean we have to set the provisioning to true and mention the replication factor inside it.
we have tried that our values.yaml looks like this 

provisioning:
  ## @param provisioning.enabled Enable kafka provisioning Job
  ##
  enabled: true
  ## @param provisioning.automountServiceAccountToken Mount Service Account token in pod
  ##
  automountServiceAccountToken: false
  ## @param provisioning.numPartitions Default number of partitions for topics when unspecified
  ##
  numPartitions: 2
  ## @param provisioning.replicationFactor Default replication factor for topics when unspecified
  ##
  replicationFactor: 3
  
  
  after this we are getting one pod for  provisioning after sometimes its disappearing

**Comment by Akashs12345** [comment]
any comments on that ? @carrodher

**Comment by Akashs12345** [comment]
@carrodher any suggestion?

**Comment by alemorcuq** [comment]
Hi, @Akashs12345.

To configure the replication factor, you need to set it in the Kafka configuration file. As stated [here](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400), starting on version `24.0.0`, you need to add your custom configurations to the `extraConfig` parameter. Any Kafka configuration settings added to the `extraConfig` parameter will be appended to the Kafka configuration file.

**Comment by amit-poddar3** [comment]
Hi @alemorcuq ,
We followed similar approach to setup replicationFactor and numPartition under extraConfig but however we trying list topics under extraConfig with replicationFactor and  numPartition values for each topic which is not working for us. We tried using provisioning block where we mentioned topic list and values but it didn't reflect, can you share how can we specify  numPartition and replicationFactor for each topic separately using values.yaml file of kafka helm chart 3.7 with Kraft
