### ISSUE TITLE
[bitnami/matomo] ArgoCD / Secrets Constantly Recreating

### ISSUE THREAD

**Issue by cculver** [bitnami/charts#25471]
### Name and Version

bitnami/matomo 7.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I set up a very basic version of this chart using the chart's version of MariaDB. I am using ArgoCD. I didn't specify my own passwords for the matomo console or for mariadb. 

### Are you using any custom parameters or values?

Nothing special - set basic info, persistence, ingress, and enabled mariadb.

### What is the expected behavior?

I expect one secret for matomo and one secret for mariadb to be created upon starting the chart, and I expect those secrets to remain the same unless I change them.

### What do you see instead?

I'm finding that since ArgoCD continuously regenerates configuration, it is continuously replacing two autogenerated secrets - one for matomo and one for mariadb. The secrets each alternate between two values - it goes from one value to another, and then back to the first, and then back to the second, and so on. 

### Additional information

I'm happy to specify my own password for Matomo in a sealed secret, but there's no guidance for the mariadb side. I'm not even sure if providing my own secret for the Matomo side will fix this problem. Can anyone tell me what I'm missing here?

**Comment by rafariossaa** [comment]
Not sure what could be happening with argoCD but that continuos secret recreation doesn't look normal to me. 
If you install the chart with helm you get two secrets, one for matomo and other for mariadb. 

```
$ helm install mymtm bitnami/matomo

$ kubectl get secrets
NAME                          TYPE                 DATA   AGE
mymtm-mariadb                 Opaque               2      3m14s
mymtm-matomo                  Opaque               1      3m14s
sh.helm.release.v1.mymtm.v1   helm.sh/release.v1   1      3m14s
```

**Comment by cculver** [comment]
Right, and it continues to regenerate with a different value because it is seeded with randomness. Is there any way to specify a password for MariaDB or will it always create a secret?

**Comment by cculver** [comment]
Anyone have any ideas here? Still cannot get a running instance under argocd.

**Comment by rafariossaa** [comment]
You could set the database password by using the [mariadb parameters](https://github.com/bitnami/charts/blob/a644ce06c12cc478ad21eae2893145430ceeb3ee/bitnami/matomo/values.yaml#L632) in `values.yaml`

**Comment by jdagostino9188** [comment]
Hi we just dealt with this and found a solution.  We create a secret w random values in Terraform (could be anything just has to exist before deploying the app) and then point to it with .Values.mariadb.auth.existingSecret which you can find in the bitnami/mariadb chart.

Hope that helps!
