### ISSUE TITLE
keycloak loginAction is missing the port

### ISSUE THREAD

**Issue by vishrantgupta** [bitnami/charts#25489]
### Name and Version

bitnami/keycloak 19.4.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using bitnmai/keycloak helm chart version 19.4.1, the `loginAction` in the keycloak login screen is missing the port number

```
<form class="login clr-form" onsubmit="login.disabled = true; return true;" action="${url.loginAction}" method="post">
```

![image](https://github.com/bitnami/charts/assets/1741243/d383ac51-043a-4988-9d46-ec2518153b28)

The keycloak is behind Istio and Nginx, and in Nginx I have already tried setting `proxy_set_header Host $host:$server_port;`, but, the port number is coming out to be empty.

### What do you see instead?

Missing port number

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
