### ISSUE TITLE
[bitnami/redis-cluster] Avoid scheduling redis-cluster primary and replicas on the same node

### ISSUE THREAD

**Issue by donch** [bitnami/charts#25505]
### Name and Version

bitnami/redis-cluster 8.6.2

### What is the problem this feature will solve?

In case we have less than 6 nodes, we need to be able to schedule primary and replica (for a same shard) on different nodes.
This can also works with any node labels (AZ etc). (Almost the same than #17712)

### What is the feature you are proposing to solve the problem?

We need a mechanism to not schedule replicas and primary on the same node (or any labels). This maybe done at the cluster bootstrap ? 

### What alternatives have you considered?

Add more nodes than the minimum pods required by redis-cluster or another technology.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
