### ISSUE TITLE
[bitnami/kafka] sed expression in init container of broker has default delimiter, that lead to errors using passwords with '/'

### ISSUE THREAD

**Issue by palark-team-lynx** [bitnami/charts#25500]
### Name and Version

bitnami/kafka 28.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

If you set password for sasl with '/' symbol in it, so sed will exit with error, because it is used default delimiter in init script
For example you have such sasl config in values.yaml
```
sasl:
  client:
    users:
      - user
    passwords:
      - passw/ord
```
The problem is on line 140 of scripts-configmap.yaml
https://github.com/bitnami/charts/blob/bb1ece6f1cb4110af1a35ea23bb16e03a76c7595/bitnami/kafka/templates/scripts-configmap.yaml#L140

### What is the expected behavior?

There is no error in sed, so we can use password without escaping special characters in it
 

### What do you see instead?

sed gets error

### Additional information

Use non-printable delimiter like this in scripts-configmap.yaml on line 113
https://github.com/bitnami/charts/blob/bb1ece6f1cb4110af1a35ea23bb16e03a76c7595/bitnami/kafka/templates/scripts-configmap.yaml#L113C9-L113C29

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Would you like to submit updating the sed script?

**Comment by palark-team-lynx** [comment]
Yeah, sure! I would like to make a PR. Return in some time)

**Comment by vyaradaikin** [comment]
@javsalgar I have made PR https://github.com/bitnami/charts/pull/25856

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
