### ISSUE TITLE
[zookeeper] No matches for kind "PodDisruptionBudget" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by piby180** [bitnami/charts#25511]
### Name and Version

bitnami/zookeeper

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am using Zookeeper as part of Apache Pinot Helm chart here
https://github.com/apache/pinot/blob/master/helm/pinot/requirements.yaml
https://github.com/apache/pinot/blob/master/helm/pinot-0.2.8.tgz

We have recently upgraded our k8s cluster to v1.27.12-eks-adc7111 and since then we started getting this error

```
error: resource mapping not found for name: "pinot-zookeeper" namespace: "pinot-dev" from "STDIN": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
ensure CRDs are installed first
```

### What is the expected behavior?

Pdb should use apiVersion policy/v1

**Comment by andresbono** [comment]
Hi, thank you for opening this issue.

In the `pdb.yaml` template, bitnami/zookeeper uses a function from the common library to set the proper `apiVersion` for different Kubernetes versions:

https://github.com/bitnami/charts/blob/52f2d9a0c192ab156f08cdb9620f71e59034d223/bitnami/zookeeper/templates/pdb.yaml#L8

https://github.com/bitnami/charts/blob/52f2d9a0c192ab156f08cdb9620f71e59034d223/bitnami/common/templates/_capabilities.tpl#L15-L24

Maybe you are using an old version of the chart?

**Comment by piby180** [comment]
Hi @andresbono 
You are right. I have posted it in Pinot community and they are now working on upgrading the chart. Closing the issue now.
