### ISSUE TITLE
[bitnami/mariadb, bitnami/wordpress] K8S 1.30 no longer supports PVC auto-allocation with an empty storage class name

### ISSUE THREAD

**Issue by juye-ops** [bitnami/charts#25513]
### Name and Version

bitnami/mariadb, bitnami/wordpress

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I just deploy a default template of `mariadb `and `wordpress` at K8S 1.30(released 17, April).

And, the [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md#bug-or-regression) specifies below. 
> The PersistentVolume controller no longer automatically assigns a default StorageClass to Persistent Volume Claims (PVCs) with an empty `storageClassName`.

### Are you using any custom parameters or values?
```
$ helm install custom-maria bitnami/mariadb --set volumePermissions.enabled=true
```
### What is the expected behavior?

If you deploy your own PV, then your maria works.

```console
$ kubectl get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY  ...
maria-pv-1   10Gi       RWO            Retain  ...

$ kubectl get pvc
NAME                          STATUS   VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
data-custom-maria-mariadb-0   Bound    maria-pv-1   10Gi       RWO                           <unset>                 12m

$ kubectl get pods
NAME                     READY   STATUS    RESTARTS      AGE
custom-maria-mariadb-0   0/1     Running   1 (42s ago)   6m14s
```

### What do you see instead?

```console
$ helm install custom-maria bitnami/mariadb --set volumePermissions.enabled=true
$ kubectl get pv
No resources found
$ kubectl get pvc
NAME                          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
data-custom-maria-mariadb-0   Pending                                                     <unset>                 27s
```

From now on, we should use custom PV such as below.
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-pv-1
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/emptydir"
```

### Additional information

Make sure that version of K8S is 1.30(released 17, April)

**Comment by dgomezleon** [comment]
Thanks for reporting. We plan to handle it at #24863
