### ISSUE TITLE
[bitnami/grafana-operator] Add CRD for GrafanaContactPoints to fix issues with operator version 5.9.0

### ISSUE THREAD

**Issue by BernhardGruen** [bitnami/charts#25514]
### Name and Version

bitnami/grafana-operator 4.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy Version 4.1.1 of the bitnami/grafana-operator chart
2. Grafana-Operator crashes regularly

### Are you using any custom parameters or values?

not relevant - empty values.yaml file crashes too

### What is the expected behavior?

I expect a running grafana-operator instance that does not crash

### What do you see instead?

The grafana-operator crashes after some uptime (like every 1 or 2 minutes)

### Additional information

It seems the issue is related to a newly added CRD GrafanaContactPoints. That CRD was added via the following PR to Grafana-Operator 5.9.0: https://github.com/grafana/grafana-operator/pull/1474/files#diff-f5475eafb228ed01aad2937a7d77862ca47eae2c07c2901505ab88b5ef72c8b8

Link to Grafana-Operator 5.9.0 Release: https://github.com/grafana/grafana-operator/releases/tag/v5.9.0

The CRD is not yet found in bitnami/grafana-operator as of version 4.1.1 (see PR https://github.com/bitnami/charts/pull/25483)

**Comment by tomberget** [comment]
Please note that once the CRD is added, the service account role also needs to be updated to allow for list and watch of GrafanaContactPoints.

**Comment by BernhardGruen** [comment]
@tomberget thank you for your annotation. I forgot to mention or even check that.

**Comment by tomberget** [comment]
@BernhardGruen I wrote it before I checked the original PR link. As long as this is fixed according to the original PR, it will be taken care of :)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by tomberget** [comment]
@BernhardGruen @carrodher 
I can have a go at it, got some time on my hands :)

**Comment by BernhardGruen** [comment]
@tomberget Sure, give it a try. Many thanks in advance. :+1:

**Comment by tomberget** [comment]
For some odd reason i suddenly pulled a lot of changes into the original PR so I had to recreate it (I though that GPG signing was sufficient, was not :) ).

Now there should be a proper working PR #25517 👍

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
