### ISSUE TITLE
Redis - TLS Certificate not including useExternalDNS suffix.

### ISSUE THREAD

**Issue by janakg** [bitnami/charts#25512]
### Name and Version

bitnami/redis 19.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When we enabled useExternalDNS and provided a suffix. Expecting it to add to the TLS certificate altNames

tls-secret.yaml

```yaml
{{- $altNames := list (
printf "*.%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) (

printf "%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (

printf "*.%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (

printf "*.%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) (

printf "%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) "127.0.0.1" "localhost" $fullname }}
```

### Are you using any custom parameters or values?
```
 useExternalDNS:{
            enabled: true,
            suffix: "example.com",
        },
```
### What is the expected behavior?

Expecting the suffix to get added to altNames of TLS

### What do you see instead?

`useExternalDNS.suffix` to be part of TLS certificate with e.g:: DNS:*.example.com

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
