### ISSUE TITLE
[bitnami/oauth2-proxy] Add support for external redis database index

### ISSUE THREAD

**Issue by zoc** [bitnami/charts#25529]
### Name and Version

bitnami/oauth2-proxy latest

### What is the problem this feature will solve?

A redis instance can support up to 16 databases (numbered from 0 to 15). The database to be used can be specified in the connection url, as defined below:
```
redis :// [[username :] password@] host [:port][/**database**]
          [?[timeout=timeout[d|h|m|s|ms|us|ns]] [&clientName=clientName]
          [&libraryName=libraryName] [&libraryVersion=libraryVersion] ]
```
This feature is explicitly supported by oauth2 proxy according to the [documentation](https://oauth2-proxy.github.io/oauth2-proxy/configuration/session_storage#usage).

The chart does not currently supports setting the redis database index. It might not be an issue when deploying a redis instance dedicated to the oaut2 proxy deployed by the chart. However it is annoying when using an external redis instance.

### What is the feature you are proposing to solve the problem?

Add a databaseIndex property to externalRedis value, defaulting to 0:
```
externalRedis:
  host: <redis host>
  port: <redis port>
  databaseIndex: <database> <-- add support for this
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
