### ISSUE TITLE
Logstash chart doesn't take config Input/Ouput/Filter from values.yaml

### ISSUE THREAD

**Issue by nhtua** [bitnami/charts#2553]
**Which chart**:
Logstash (v0.2.18)

**Describe the bug**
Helm doesn't take config from input/output/filter sections in `values.yaml`. It just ignores any values you put in these sections. 

The problem is in file `templates/sts.yaml` which scans and loads files from directory `files/conf/*` if existed. Somehow, there is a file `README.md` stays there and makes the condition always TRUE - always loads config from `files/conf/*`.

```
#logstash/templates/sts.yaml:72
volumeMounts:
{{- if or (.Files.Glob "files/conf/*") .Values.input .Values.filter .Values.output .Values.existingConfiguration }}
    - name: configurations
      mountPath: /bitnami/logstash/config
{{- end }}
```

**To Reproduce**
1. update config values in sections input/output/filter from `values.yaml`
2. heml install -f values.yaml logstash .
3. kubectl describe configmap logstash
4. See error, there is only file REAME.md, no `logstash.conf`

**Expected behavior**
Helm chart has to compile the logstash.conf file from vars input/output/filter in `values.yaml` and put it to configmap.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"********", GitCommit:"*******", GitTreeState:"clean", BuildDate:"********", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Thanks @nhtua 

I just reviewed your PR! Thanks so much for identifying this issue
