### ISSUE TITLE
[bitnami/discourse] Install new plugins in Discourse

### ISSUE THREAD

**Issue by Finallf** [bitnami/charts#25533]
### Name and Version

bitname/discourse latest

### What is the problem this feature will solve?

I would like to include new plugins but I'm using Docker and Docker Compose, could someone give me the steps to follow.

I saw the steps in this topic, but is it for k8s, correct?
[https://github.com/bitnami/charts/issues/17455](https://github.com/bitnami/charts/issues/17455)

### What is the feature you are proposing to solve the problem?

Include new plugins using docker and/or docker compose.

### What alternatives have you considered?

The alternative would be to use k8s, but I wouldn't want to use it, as all my infrastructure is based on pure Docker.

Thanks

**Comment by javsalgar** [comment]
Hi!

Yes, the instructions are for the discourse chart, which adds an init container that downloads the plugins. For docker-compose you may need to mimic that behavior by launching `bundle exec rake plugin:install` inside the container

**Comment by Finallf** [comment]
> Hi!
> 
> Yes, the instructions are for the discourse chart, which adds an init container that downloads the plugins. For docker-compose you may need to mimic that behavior by launching `bundle exec rake plugin:install` inside the container

When I try to activate a plugin with the above command, it gives me this error:
`Could not locate Gemfile or .bundle/ directory`

**Comment by javsalgar** [comment]
In which directory are you running that command?
