### ISSUE TITLE
[bitnami/influxdb] Incorrect file name for custom config

### ISSUE THREAD

**Issue by cpotteck** [bitnami/charts#25532]
### Name and Version

bitnami/influxdb 6.0.9

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy the helm chart on kubernetes (for me, its on GKE): `kubectl create ns test-influxdb && helm install test-influxdb .`
2. With the custom configuration below
3. Show pod logs `kubectl logs svc/test-influxdb`, they are not in json format
4. Show the server configuration, `reporting-disabled` still shows `false`. In my case, I port-forwarded (`kubectl port-forward svc/test-influxdb 8086`), logged in as 'admin', and checked http://localhost:8086/api/v2/config

### Are you using any custom parameters or values?

Only changes vs the default values is a custom influxdb configuration:

```
influxdb:
  configuration: |
      reporting-disabled = true
```

### What is the expected behavior?

Influxdb picks up the custom configuration, and `reporting-disabled` shows as `true` in the server config.

### What do you see instead?

The config file is detected by the startup script:

```
influxdb 21:50:46.63 INFO  ==> ** Starting InfluxDB setup **
influxdb 21:50:46.74 INFO  ==> Custom configuration /opt/bitnami/influxdb/etc/influxdb.conf detected!
influxdb 21:50:46.83 WARN  ==> The 'INFLUXDB_' environment variables override the equivalent options in the configuration file.
influxdb 21:50:46.83 WARN  ==> If a configuration option is not specified in either the configuration file or in an environment variable, InfluxDB uses its internal default configuration
influxdb 21:50:46.83 INFO  ==> Starting InfluxDB in background...
influxdb 21:50:48.43 INFO  ==> Deploying InfluxDB from scratch
influxdb 21:50:48.43 INFO  ==> Creating primary setup...
User	Organization	Bucket
admin	primary		primary
influxdb 21:50:49.43 INFO  ==> Stopping InfluxDB...
Terminated
influxdb 21:50:49.53 INFO  ==> ** InfluxDB setup finished! **
```

However, the configuration is not actually being taken in by influxdb:

* Logging in and showing http://localhost:8086/api/v2/config, `reporting-disabled` is still `false`: 

```json
{
  "config": {
    "assets-path": "",
    "bolt-path": "/bitnami/influxdb/influxd.bolt",
    "e2e-testing": false,
    "engine-path": "/bitnami/influxdb",
    "feature-flags": null,
    "flux-log-enabled": false,
    "hardening-enabled": false,
    "http-bind-address": "0.0.0.0:8086",
    "http-idle-timeout": 180000000000,
    "http-read-header-timeout": 10000000000,
    "http-read-timeout": 0,
    "http-write-timeout": 0,
    "influxql-max-select-buckets": 0,
    "influxql-max-select-point": 0,
    "influxql-max-select-series": 0,
    "instance-id": "",
    "log-level": "info",
    "metrics-disabled": false,
    "nats-max-payload-bytes": 0,
    "nats-port": 0,
    "no-tasks": false,
    "pprof-disabled": false,
    "query-concurrency": 1024,
    "query-initial-memory-bytes": 0,
    "query-max-memory-bytes": 0,
    "query-memory-bytes": 0,
    "query-queue-size": 1024,
    "reporting-disabled": false,
    "secret-store": "bolt",
    "session-length": 60,
    "session-renew-disabled": false,
    "sqlite-path": "/bitnami/influxdb/influxd.sqlite",
    "storage-cache-max-memory-size": 1073741824,
    "storage-cache-snapshot-memory-size": 26214400,
    "storage-cache-snapshot-write-cold-duration": "10m0s",
    "storage-compact-full-write-cold-duration": "4h0m0s",
    "storage-compact-throughput-burst": 50331648,
    "storage-max-concurrent-compactions": 0,
    "storage-max-index-log-file-size": 1048576,
    "storage-no-validate-field-size": false,
    "storage-retention-check-interval": "30m0s",
    "storage-series-file-max-concurrent-snapshot-compactions": 0,
    "storage-series-id-set-cache-size": 0,
    "storage-shard-precreator-advance-period": "30m0s",
    "storage-shard-precreator-check-interval": "10m0s",
    "storage-tsm-use-madv-willneed": false,
    "storage-validate-keys": false,
    "storage-wal-fsync-delay": "0s",
    "storage-wal-max-concurrent-writes": 0,
    "storage-wal-max-write-delay": 600000000000,
    "storage-write-timeout": 10000000000,
    "store": "disk",
    "strong-passwords": false,
    "testing-always-allow-setup": false,
    "tls-cert": "",
    "tls-key": "",
    "tls-min-version": "1.2",
    "tls-strict-ciphers": false,
    "tracing-type": "",
    "ui-disabled": false,
    "vault-addr": "",
    "vault-cacert": "",
    "vault-capath": "",
    "vault-client-cert": "",
    "vault-client-key": "",
    "vault-client-timeout": 0,
    "vault-max-retries": 0,
    "vault-skip-verify": false,
    "vault-tls-server-name": "",
    "vault-token": ""
  }
}
```

### Additional information

After some research, it seems like the chart creates the custom config under `/opt/bitnami/influxdb/etc/influxdb.conf`, which is not a filename supported by influxdb v2. According to influxdb docs [1], the file name in v2 should be `config.*` and the value of `INFLUXD_CONFIG_PATH` is expected to be set to a path containing this file. `influxdb.conf` was the expected file name for v1 [2]

I tried working around this issue in the chart by instead creating a configmap defining a file named `config.toml` (with the same contents as the ones listed under "Are you using any custom parameters or values?"), and setting `existingConfiguration` instead. I also defined an `extraEnvVars` setting `INFLUXD_CONFIG_PATH` to `/opt/bitnami/influxdb/etc`.

However, doing this, the startup fails with:

```
influxdb 21:03:28.53 INFO  ==> ** Starting InfluxDB setup **
influxdb 21:03:28.54 DEBUG ==> Validating settings in INFLUXDB_* env vars...
influxdb 21:03:28.55 INFO  ==> No injected configuration files found. Creating default config files...
touch: cannot touch '/opt/bitnami/influxdb/etc/influxdb.conf': Read-only file system
influxdb 21:03:28.56 INFO  ==> Stopping InfluxDB...
```
Note that it still tries to create `influxdb.conf`.

Looking further into the image code, `INFLUXD_CONFIG_PATH` is set to "${INFLUXDB_CONF_DIR}/influxdb.conf" which matches with `/opt/bitnami/influxdb/etc/influxdb.conf` [3]. So as far as I can see there is no way to overwrite this value with the order of preference specified at the top of that file, and there is no way to work around this in the current version of the chart.

[1] https://docs.influxdata.com/influxdb/v2/reference/config-options/#influxdb-configuration-file
[2] https://docs.influxdata.com/influxdb/v1/administration/config/#using-the-configuration-file
[3] https://github.com/bitnami/containers/blob/2a80b1d55e02375a56fc8f312ddb52fe211e9c6d/bitnami/influxdb/2/debian-12/rootfs/opt/bitnami/scripts/influxdb-env.sh#L84

**Comment by cpotteck** [comment]
I was wrong about the log format being configurable to JSON in 2.x, that option seems to have been present in 1.x but remove since (ref: [influxdb 2.x docs](https://docs.influxdata.com/influxdb/v2/admin/logs/#log-formats), related issue: https://github.com/influxdata/influxdb/issues/22826). I edited the issue report to remove mentions of log formatting.

Also, I have seen that most (if not all) configuration options which can be set in the config file can also be set with environment variables, so I was mistaken when I stated "there is no way to work around this in the current version of the chart". 

We would definitely prefer using a config file for readability though, so curious to know if the current implementation is working in the expected way.

**Comment by jotamartos** [comment]
Hi @cpotteck,

You can try using `reporting-disabled: true` to disable it or include `--reporting-disabled` in the args that the command runs. 

https://docs.influxdata.com/influxdb/v2/reference/config-options/#reporting-disabled

I hope this helps.

**Comment by cpotteck** [comment]
@jotamartos Thanks for the suggestion. I went ahead ahead and used the environment variable `INFLUXD_REPORTING_DISABLED=true`, but yes `--reporting-disabled` also works.

Regarding `reporting-disabled: true`, that would depend on being able to set the influxdb config file in a file and format which influxdb 2.x recognizes which I have not been able to do with the bitnami image and chart. 

Using the environment variable or arg flags is a workable solution for me, but I would still be curious to know if setting the influxdb config via the helm chart's `configuration:` field ([see in values file](https://github.com/bitnami/charts/blob/main/bitnami/influxdb/values.yaml#L182)) is expected to work for 2.x. If it is not compatible, a note could be added to specify this (I would be happy to open a PR).

**Comment by jotamartos** [comment]
Hi @cpotteck,

I just detected an issue in the solution that is preventing this custom configuration to work properly. There are 2 problems, the deployment is creating a "influxdb.conf" file when v2 only supports .yaml, .toml or .json config files. The second one is related to the INFLUXD_CONFIG_PATH env var that is not properly set in the container. 

Please keep using the --reporting-disabled parameter or the env var to disable this feature. We will let you know when the issue is fixed and you can use the influxdb.configuration parameter in the chart.

**Comment by jotamartos** [comment]
Version 6.0.11 of the chart will include the changes to fix this issue. 

https://github.com/bitnami/charts/pull/25640

You can use this config from that moment on

```
influxdb:
  configuration: |-
      reporting-disabled: true
```
