### ISSUE TITLE
RabbitMQ `auth.password` is required when `auth.existingPasswordSecret` is defined

### ISSUE THREAD

**Issue by ChristianRaoulis** [bitnami/charts#25557]
### Name and Version

bitnami/rabbitmq 14.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create a Secret with `rabbitmq-password` and a value
2. Set the `auth.existingPasswordSecret` value to the name of your secret
3. Try to deploy it

### What is the expected behavior?

The Chart should use the existing secret values from `auth.existingPasswordSecret` and don't require the auth.password` value.

### What do you see instead?

The Chart shows an error when the `auth.password` value is empty.

```
error: template: rabbitmq/templates/secrets.yaml:9:17: executing "rabbitmq/templates/secrets.yaml" at <include "rabbitmq.password" .>: error calling include: template: rabbitmq/templates/_helpers.tpl:69:12: executing "rabbitmq.password" at <include "getValueFromSecret" (dict "Namespace" (include "common.names.namespace" .) "Name" (include "rabbitmq.secretPasswordName" .) "Length" 16 "Key" (include "rabbitmq.secretPasswordKey" .))>: error calling include: template: rabbitmq/templates/_helpers.tpl:293:38: executing "getValueFromSecret" at <"\"">: invalid value; expected string
```

**Comment by migruiz4** [comment]
Hi @ChristianRaoulis,

I'm sorry but I wasn't able to reproduce your issue:
```
$ kubectl create secret generic rabbitmq-test --from-literal=rabbitmq-password=my-pass
$ cat values.yaml
auth:
  existingPasswordSecret: rabbitmq-test
$ helm install rabbitmq bitnami/rabbitmq -f values.yaml
...
```

Could you please provide more details about your case? What method are you using to deploy the chart? Are you using any additional values?

**Comment by ChristianRaoulis** [comment]
Sorry, I forgot to close the issue.

I changed my password, now everything works just fine. It looks like there was a weird interaction between pulumi (which i use to deploy the chart), Conjur and Helm.

**Comment by migruiz4** [comment]
No problem, thank you for your feedback!
