### ISSUE TITLE
Cannot execute elasticsearch-keystore, elasticsearch-plugin etc

### ISSUE THREAD

**Issue by superkjp** [bitnami/charts#2555]
**Which chart**:
The name (and version) of the affected chart
elasticsearch tag:7.6.2-debian-10-r30
**Describe the bug**
Cannot execute elasticsearch-related command, like:elasticsearch-keystore,elasticsearch-plugin etc.
**To Reproduce**
1. Go to '/opt/bitnami/elasticsearch/bin'
2. Type: 'elasticsearch-keystore add s3.client.default.access_key'
3. See error
could not find java in bundled jdk at /opt/bitnami/elasticsearch/jdk/bin/java

**Expected behavior**
'Enter value for s3.client.default.access_key: '

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I was expecting to use the minio with s3 to do the backup with:
PUT /_snapshot/my_minio_repository
{
   "type": "s3",
   "settings": {
      "bucket": "ece-backup",
      "access_key": "...",
      "secret_key": "...",
      "endpoint": "http://minio.velero.svc.cluster.local:9000",
      "protocol": "http"
   }
}

And I got the error message:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Setting [access_key] is insecure, but property [allow_insecure_settings] is not set"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Setting [access_key] is insecure, but property [allow_insecure_settings] is not set"
  },
  "status" : 400
}

**Comment by carrodher** [comment]
Hi,

Thanks for reporting the issue, the source of the error is that the `JAVA_HOME` environment variable is not set in the container. I just created an internal task to fix this issue in the container image.

In the meantime, you can add the `JAVA_HOME` env. variable when running the `elasticsearch-keystore` command, in fact, this command is in the PATH so you don't need to specify the whole path. As a summary, the following command should work:
```
$ JAVA_HOME=/opt/bitnami/java elasticsearch-keystore add s3.client.default.access_key
Enter value for s3.client.default.access_key:
```

Once fixed the issue, the `JAVA_HOME=/opt/bitnami/java` can be omitted.

**Comment by superkjp** [comment]
Thanks a lot, it works. Appreciated
