### ISSUE TITLE
[bitnami/minio] $totalDrives in _helpers.tpl doesn't take number of zones into account

### ISSUE THREAD

**Issue by Johannesm299** [bitnami/charts#25553]
### Name and Version

bitnami/minio 14.3.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Try to template the chart with values for running in distributed mode: 

- `helm template myminio bitnami/minio --version 14.3.3 -f .\distributed-values.yaml`

### Are you using any custom parameters or values?

distributed-values.yaml:
```
mode: distributed
statefulset:
 replicaCount: 2
 zones: 2
 drivesPerNode: 1
```

### What is the expected behavior?

Since replicaCount is set to two and also zones is set to two, there will be 4 pods, each with one drive, meaning in total there will be four drives.

### What do you see instead?

```
Error: execution error at (minio/templates/NOTES.txt:76:4): 
VALUES VALIDATION:
minio: total drives
    The total number of drives should be greater than 4 to guarantee erasure coding!
    Please set a combination of nodes, and drives per node that match this condition.
    For instance (--set statefulset.replicaCount=2 --set statefulset.drivesPerNode=2)

Use --debug flag to render out invalid YAML
```

### Additional information

This seems to be, because [$totalDrives](https://github.com/bitnami/charts/blob/6b4b33c503ebd5b00287334578803e9d9459e606/bitnami/minio/templates/_helpers.tpl#L187) does not take the zones into consideration when calculating the total drives.

Or is it meant to check if there are 4 drives per zone? In that case I would suggest renaming the variable to `totalDrivesPerZone` and changing the error message accordingly.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting the issue. Would you like to submit a PR improving this check?

**Comment by Johannesm299** [comment]
Hi, yes I'm happy to do so. But I'm not sure if the calculation is wrong, or if there should be 4 drives per zone.

**Comment by alemorcuq** [comment]
Sorry for the late reply @Johannesm299. I think you are right and zones should be counted in the calculation. At least that's what I understand from this [calculator](https://min.io/product/erasure-code-calculator?ref=docs).

**Comment by jani888** [comment]
I don't think this change is correct, if I understand correctly. In the bitnami/minio chart zones are the equivalent of pools in minio terminology. Therefore, referring to this [documentation](https://min.io/docs/minio/linux/operations/install-deploy-manage/expand-minio-deployment.html#minimum-drives-for-erasure-code-parity), each pool should have a minimum drive count of 4. So I think the original calculation was correct, and the new one is wrong. What do you think @Johannesm299 , @alemorcuq ?
