### ISSUE TITLE
[bitnami/redis-cluster] Improve local usage

### ISSUE THREAD

**Issue by ammirator-administrator** [bitnami/charts#25563]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

It works fine) but locally to spin up a cluster is a pain when it comes to connect to the cluster fromoutside
Let's imagine locally you use a Minikube instance just one node
Now you start a cluster with 3 pods and make it externally available

What it is gonna do is create a service per redis instance and separate load balancers for each
Now the problem is that in Minikube when you run tunnel to have the services exposed to outside it just gives to all load balancers same IP 127.0.0.1

And since all pods use same port the connect is not gonna work)

To resolve such problem it would be nice that beside the loadBalancerIPS array to have a new field ports, so that we can declare separate ports for every instance so these can still use same IP but be mounted on separate ports

This will make the local development better and developers happier (At least me :))

So in the end we can connect to this 127.0.0.1:6739, 127.0.0.1:6780, 127.0.0.1:6781 etc etc

Using the default service it is not possible from outside I saw there is a default service but if we make only this a LoadBalancer and not the cluster.externalAccess then to connect to default service is still not possible and I'm sure no one connects to it because redis responds with a MOVED command and clients can't execute that because only the default service is accesible from outside not other pods and redis instances

I don't even understand why default service exists) sure no one uses this because is unusable, maybe just with ClusterIP and only inside the cluster but definitelly not as LoadBalancer

### What is the feature you are proposing to solve the problem?

The feature is to add posibility to declare different ports for every instance by default if you declare port 6379 then this will be used on all pods and this is not friendly with local development when making the cluster accesible from outside

The proposed solution is to add this possibility ONLY when external access is TRUE, so that for every service we can declare separate ports so that we can use same IP for them

I guess a lot of peoples may want that who uses minikube, and do not want to spin up external load balancers etc etc and configire additional things to get uniq IP

### What alternatives have you considered?

no alternatives

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward it to the team but as it not a critical feature and a use-case meant for local testing, we cannot guarantee an ETA. However, if you want to speed up the process, would you like to submit a PR?
