### ISSUE TITLE
[bitnami/wordpress] Helm Chart doesn't support PDF-Thumbnail-Gen

### ISSUE THREAD

**Issue by madejackson** [bitnami/charts#25562]
### Name and Version

bitnami/wordpress:6.4.3-debian-12-r20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Upload a PDF to Wordpres or Install Plugin: https://de.wordpress.org/plugins/pdf-thumbnails-support-test/

### What is the expected behavior?

Either add an env-var to enable Imagemagick+Ghostscript with PDF-Thumbnail-Support (also depends on specific settings in Imagemagick+Ghostscript) or enable those per default.

### What do you see instead?

![grafik](https://github.com/bitnami/charts/assets/24832654/3aa96789-30f1-40f8-834d-efba94b4c59b)

**Comment by jotamartos** [comment]
Hi @madejackson,

Thank you for reporting this. You can generate a [new image including imagemagick and ghostscript](https://github.com/bitnami/containers/blob/main/bitnami/wordpress/6/debian-12/Dockerfile) and confirm that everything works as expected. Once you test it, you can contribute to the containers repo by following our [contributing guidelines](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) and the whole community will benefit from that. You can also suggest any other change related to the configuration if necessary.

Thanks
