### ISSUE TITLE
[bitnami/haproxy] Add ExternalIPs to Service

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/charts#25564]
### Name and Version

bitnami/haproxy 2.9.7

### What is the problem this feature will solve?

We need to expose haproxy to external applications. For internals reasons, we have to use [ExternalIPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips).

But the Haproxy chart do not allow setting ExternalIPs.

### What is the feature you are proposing to solve the problem?

We need a option to set ExternalIPs, like this:

| Name                                    | Description                                                                                                                      | Value                    |
| --------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- | ------------------------ |
| `service.externalIPs`             | External IPs                                                                                                             | `[]`           |

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
