### ISSUE TITLE
[bitnami/mysql] Mysql 5.7: [ERROR] unknown variable 'mysqlx=0'

### ISSUE THREAD

**Issue by shawkitajima** [bitnami/charts#25568]
### Name and Version

bitnamicharts/mysql:10.2.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Using docker-desktop as the Kubernetes provider
2. Using any namespace
3. run: `helm install mysql-5 oci://registry-1.docker.io/bitnamicharts/mysql --set image.tag=5.7`

### Are you using any custom parameters or values?

--set image.tag=5.7

### What is the expected behavior?

Mysql 5.7 should run without issue

### What do you see instead?

```
mysql 17:37:59.12 Welcome to the Bitnami mysql container
mysql 17:37:59.13 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 17:37:59.13 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 17:37:59.13 
mysql 17:37:59.13 INFO  ==> ** Starting MySQL setup **
mysql 17:37:59.14 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 17:37:59.14 INFO  ==> Initializing mysql database
mysql 17:37:59.15 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 17:37:59.16 INFO  ==> Installing database
2024-05-06T17:37:59.435877Z 0 [Warning] InnoDB: New log files created, LSN=45790
2024-05-06T17:37:59.466189Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2024-05-06T17:37:59.469444Z 0 [ERROR] unknown variable 'mysqlx=0'
2024-05-06T17:37:59.469457Z 0 [ERROR] Aborting
```

**Comment by javsalgar** [comment]
Hi,

Please note that you are using a mysql branch that has been deprecated on our side https://github.com/bitnami/containers/tree/main/bitnami/mysql

In this sense, the changes in our charts cannot guarantee support for these deprecated branches. However, for this specific case, you can edit the configuration in the values.yaml file and remove the mysqlx references
