### ISSUE TITLE
 Latest Wordpress very slow when fresh deployment and importing an instance that was previously running with wordpress official image WordPress

### ISSUE THREAD

**Issue by titansmc** [bitnami/charts#2556]
**Which chart**:
Latest Wordpress

**Describe the bug**
The website takes from 10s to 20s to load (sometimes it goes up to 40s), and the first query takes like 5s(or even more) until I see something coming to the logs. Until it finally crashes.
```
10.133.83.221 - - [08/May/2020:07:20:49 +0000] "GET /wp-content/bitnami/wordpress/wp-content/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src/assets/lib/font-awesome-v5.2.0/css/all.min.css?ver=0.6.8 HTTP/1.1" 404 84332
[Fri May 08 07:21:32.447573 2020] [mpm_prefork:notice] [pid 71] AH00169: caught SIGTERM, shutting down
```

**To Reproduce**

Deploy fresh wordpress , import mysql dump into mariadb, and copy wp-content.

**Expected behavior**
Wordpress running smooth 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
the website was previously running the official Wordpress image and mysql server 5.7

**Comment by titansmc** [comment]
1min37s this time:
![image](https://user-images.githubusercontent.com/8192096/81389598-62bdbb00-911a-11ea-9ed7-bd8189ad7308.png)

**Comment by titansmc** [comment]
Resources shouldn't be an issue, since I have defined 1.5G and 1 cpu:
```
[ mysqldump-s3]# kubectl top pod -n web web-wordpress-cb97cd75c-hz8wc 
NAME                                   CPU(cores)   MEMORY(bytes)   
web-wordpress-cb97cd75c-hz8wc   597m         290Mi    
```

**Comment by andresbono** [comment]
Hi @titansmc, from our experience, these kind of performance issues are related to plugins or themes that you may have installed on your WordPress. Can you try to disable some of them temporarily to see if the performance improves? This test might lead us to the source of the issue.

**Comment by titansmc** [comment]
Gracias Andres. So for now I had to switch to official wordpress image because I am not managing this WP instance and cannot play that much with it, but thanks for letting me know and I will try to find a solution for that. But I can confirm that the website is a bit messy , so it makes total sense what you are saying.
Although is weird why it keeps working (in a way) with the official WP image.

Thanks.

**Comment by andresbono** [comment]
Thanks for letting us know, @titansmc.
