### ISSUE TITLE
Spark Connect Support

### ISSUE THREAD

**Issue by Veiasai** [bitnami/charts#25570]
### Name and Version

bitnami/spark 9.0.1

### What is the problem this feature will solve?

Operational benefit: users can submit spark jobs from everywhere without running a driver.

### What is the feature you are proposing to solve the problem?

https://spark.apache.org/docs/latest/spark-connect-overview.html

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Veiasai** [comment]
hey, I took a look at this. 
it seems like I just need to change the start command for spark master.

However, I jumped into the spark docker image and couldn't find ./sbin/start-connect-server.sh

```
I have no name!@774832a2ed86:/opt/bitnami/spark$ ls /opt/bitnami/spark/sbin/
decommission-slave.sh   spark-daemon.sh          start-master.sh                 start-slaves.sh        stop-all.sh               stop-mesos-shuffle-service.sh  stop-worker.sh
decommission-worker.sh  spark-daemons.sh         start-mesos-dispatcher.sh       start-thriftserver.sh  stop-history-server.sh    stop-slave.sh                  stop-workers.sh
slaves.sh               start-all.sh             start-mesos-shuffle-service.sh  start-worker.sh        stop-master.sh            stop-slaves.sh                 workers.sh
spark-config.sh         start-history-server.sh  start-slave.sh                  start-workers.sh       stop-mesos-dispatcher.sh  stop-thriftserver.sh
```

https://github.com/bitnami/containers/blob/main/bitnami/spark/3.5/debian-12/Dockerfile

and this dockerfile shows the spark release is from https://downloads.bitnami.com/files/stacksmith/${COMPONENT}.tar.gz


do you know how that work?

I can find `start-connect-server.sh` in https://www.apache.org/dyn/closer.lua/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
