### ISSUE TITLE
[bitnami/gitea] Custom Config Value "ENABLE_OPENID_SIGNIN"

### ISSUE THREAD

**Issue by ikamii** [bitnami/charts#25572]
### Name and Version

bitnami/gitea

### What is the problem this feature will solve?

Hello, I am trying to deploy Gitea Helm chart with a custom config "ENABLE_OPENID_SIGNIN=true".

I have added 
```yaml
extraEnvVars:
  - name: ENABLE_OPENID_SIGNIN
    value: "true"
```
but it doesn't work. I couldn't find how to change it.

### What is the feature you are proposing to solve the problem?

Could you maybe add this feature to change this config value. I've seen that it's not in app.ini.template.

### What alternatives have you considered?

I also have tried to change the `deployment.yaml` but it didn't work as well. 

Thank you in advance!

**Comment by javsalgar** [comment]
Hi,

This may require a change in the gitea initialization logic. https://github.com/bitnami/containers/blob/main/bitnami/gitea/1/debian-12/rootfs/opt/bitnami/scripts/libgitea.sh#L189

Adding this variable and then modify the gitea configuration file. I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR in bitnami/containers adding the feature?

**Comment by ikamii** [comment]
Hi again,

Thank you for your answer. 

I would like to try to modify the gitea configuration file as well as the helm chart. If I manage to achieve it, I'll create a PR in bitnami/containers and also in bitnami/charts. Otherwise I would comment here.

Thanks!

**Comment by ikamii** [comment]
https://github.com/bitnami/containers/pull/66480

I have created a PR. I am going to update the helm chart as well.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look

**Comment by ikamii** [comment]
I have commented on PR after I've found an error and couldn't find any solution. You might have an idea to solve this.

After setting the values to true the container starts with the right values.

I get in `app.ini`

```ini
[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true
```
after fully gitea initialization, both turns to false (gitea auto assigns the values to `false).

And after I restart the container it turns to the values which I set again.

**Comment by javsalgar** [comment]
Maybe these values should be set after passing the gitea wizard

**Comment by ikamii** [comment]
The assignee of PR is also looking what is causing this issue. 

I'll try what you said today 👍🏼

**Comment by ikamii** [comment]
Hi again,

I have tried setting the values after passing the gitea wizard and it works. I will commit the changes.

**Comment by ikamii** [comment]
I am also done with the helm chart changes. It works as good as the container. I am waiting the approval of the PR in containers. Afterwards, I'll commit the chart changes and create a PR here and close this issue.

Thanks for everything!

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
