### ISSUE TITLE
Readiness probe failed: mysqladmin: connect to server at 'localhost' failed

### ISSUE THREAD

**Issue by osaffer** [bitnami/charts#2558]
Hi,

I am facing a problem as showed into the subject.
My Cluster Kubernetes is behind a corporate proxy.
The installation has been done with helm : 
stable/mariadb          7.4.1           10.3.22

The same installation has been done also on my laptop without any problem.

But with the server behind proxy, I cant.

In kube_proxy, of course I have the variable no_proxy set 

 - name: https_proxy
          value: http://$HOST:$PORT
        - name: http_proxy
          value: http://$HOST:$PORT
        - name: no_proxy
          value: localhost,127.0.0.1,127.0.0.0,127.0.1.1,0.0.0.0,knode0,knode1,knode2,knode3,172.20.0.0/16,172.26.0.0/16
 kubectl logs -f mariadb-0
mariadb 11:18:44.82
mariadb 11:18:44.82 Welcome to the Bitnami mariadb container
mariadb 11:18:44.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 11:18:44.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 11:18:44.82
mariadb 11:18:44.83 INFO  ==> ** Starting MariaDB setup **
mariadb 11:18:44.89 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 11:18:44.89 INFO  ==> Initializing mariadb database
mariadb 11:18:44.91 INFO  ==> Installing database

Description of pod

 Normal   Created    2m26s (x2 over 5m24s)  kubelet, knode3  Created container mariadb
  Normal   Started    2m26s (x2 over 5m24s)  kubelet,  knode3  Started container mariadb
  Warning  Unhealthy  24s (x25 over 4m54s)   kubelet, knode3  Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists!

Thanks a lot for your support,

**Comment by miguelaeh** [comment]
Hi @osaffer ,
There is something not clear to me here regarding the proxy. Your k8s cluster is behind a proxy but the error you are showing is from the Pod's logs, so I don't see the relation between them. Maybe I am missing something, could you clarify that?

**Comment by osaffer** [comment]
> Hi @osaffer ,
> There is something not clear to me here regarding the proxy. Your k8s cluster is behind a proxy but the error you are showing is from the Pod's logs, so I don't see the relation between them. Maybe I am missing something, could you clarify that?

Hi,

It is just for information that I inform the kubernetes is behind a proxy.

I dont have this constraint with my laptop ;-)

**Comment by miguelaeh** [comment]
Hi @osaffer ,
From my point, this does not seem related to the proxy. Maybe I am something here, but the readiness probe is performed from the pod to itself, so the proxy should not be implicated here. From your MySQL logs, it seems that the Readiness probe failed because Mysql has not finished the starting process. Can you confirm that mysql is actually running?

**Comment by osaffer** [comment]
> Hi @osaffer ,
> From my point, this does not seem related to the proxy. Maybe I am something here, but the readiness probe is performed from the pod to itself, so the proxy should not be implicated here. From your MySQL logs, it seems that the Readiness probe failed because Mysql has not finished the starting process. Can you confirm that mysql is actually running?

Hi,

Indeed, it is not related with the proxy. 
I performed a test successfully by disabling the persistence volume, and the deployment was ok.
There is a problem, when I enable persistence volume.
I use NFS as persistence Volume, my NFS server is configured on Cluster (Corosync+Pacemaker+DRBD)
When starting the helm installation, the directory is well created /mnt/nfs/default-data-mariadb-0-pvc-e08722be-9343-49ac-b9e4-2b39e4f5df50/data# ls -lrct
total 4
-rw-rw---- 1 1003 root  0 May 11 11:25 ibdata1
-rw-rw---- 1 1003 root 52 May 11 11:25 aria_log_control

But only two files are created.

volumePermissions:
  enabled: true

securityContext:
  enabled: true
  fsGroup: 1004
  runAsUser: 1003


On my laptop, the deployment is good, with NFS Server, but without any cluster, so just single node.

**Comment by osaffer** [comment]
Problem solved :-D

There was the following message in syslog on nfs server side.
Lockd: cannot monitor

I just restarted rpc.statd
systemctl start rpc-statd

Regards,

**Comment by miguelaeh** [comment]
Hi @osaffer ,
I am glad you get a solution for it.
Thank you very much for sharing it with the rest of the users!!!
Please don't hesitate to contact us if you find any issue with our charts in the future.
Regards.
