### ISSUE TITLE
[bitnami/vault] Support for DynamoDB storage 

### ISSUE THREAD

**Issue by Shravankumark** [bitnami/charts#25639]
### Name and Version

bitnami/vault

### What is the problem this feature will solve?

I am planning to use the Bitnami helm chart for the Vault with DynamoDB as backend storage. Want to find out if Dynamo is supported backend?

**Comment by javsalgar** [comment]
Hi!

The chart exposes the full configuration via its `configuration` section, so it in principle it could be modified to connect to a DynamoDB instance

**Comment by Shravankumark** [comment]
Got it.Thanks.
Do we have an auto unseal option with bitnami chart?

**Comment by javsalgar** [comment]
I'm afraid that's not something we're currently supporting as it is discouraged by upstream devs.
