### ISSUE TITLE
[bitnami/kafka] Migration to Kafka 3.5 dropped support for rack awareness

### ISSUE THREAD

**Issue by rubenvw-ngdata** [bitnami/charts#25645]
### Name and Version

bitnami/kafka 28.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Support for kafka rack awareness was added in https://github.com/bitnami/charts/pull/13308, but dropped in https://github.com/bitnami/charts/pull/17507. I believe this was unintentional since I cannot find anything mentioning this in the commit message.

The property `broker.rack` is not a property that can simply be filled via `extraConfig` because it requires a dynamic value setting, that depends on the availability zone where the pod is scheduled.

### What is the expected behavior?

Can you add support for this unintentional removal of functionality.

The previous bitnami/kafka chart version that we used supporting this functionality was 22.0.1

### What do you see instead?

No support via any of the chart parameters.

**Comment by janvanbesien-ngdata** [comment]
As @rubenvw-ngdata says, this was dropped in https://github.com/bitnami/charts/pull/17507. To be even more specific, here: https://github.com/bitnami/charts/pull/17507/files#r1594006644
