### ISSUE TITLE
Keycloak: using httpRelativePath with no trailing slash causes readiness probe to fail

### ISSUE THREAD

**Issue by peeveen** [bitnami/charts#25641]
### Name and Version

bitnami/keycloak 21.0.3

### What architecture are you using?

None

### What steps will reproduce the bug?

Set `httpRelativePath` to a value with no trailing slash, e.g. `/blah`

Observe that the readiness probe fails, as it expects the trailing slash:

```
Readiness probe failed: Get "http://10.244.0.150:8080/blahrealms/master"
```

### What is the expected behavior?

Readiness probe (eventually) succeeds.

### What do you see instead?

```
Readiness probe failed: Get "http://10.244.0.150:8080/blahrealms/master"
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
