### ISSUE TITLE
[bitnami/postgresql] The database is not shut down cleanly and pods start with automatic recovery

### ISSUE THREAD

**Issue by em-** [bitnami/charts#25663]
### Name and Version

bitnami/postgresql 15.2.9

### What architecture are you using?

None

### What steps will reproduce the bug?

1. deploy the postgresql chart
2. initiate a pod rollout
3. check the logs of the new pod
4. find out that it recovered from a unclean shutdown

### Are you using any custom parameters or values?

None relevant

### What is the expected behavior?

The database should be shut down cleanly.

### What do you see instead?

```
2024-05-06 21:57:04.197 GMT [96] LOG:  database system was interrupted; last known up at 2024-05-06 21:52:59 GMT
2024-05-06 21:57:04.387 GMT [96] LOG:  database system was not properly shut down; automatic recovery in progress
```

### Additional information

The `bitnami/postgresql-ha` chart already sets a [preStop hooks](https://github.com/bitnami/charts/blob/234e9a7f195b7469343d921bbad14895eee9d180/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L161) to initiate the clean shutdown of the database. Ideally the `bitnami/postgresql` chart should do the same, since relying only on [SIGTERM is suboptimal](https://stackoverflow.com/a/75829325/65624) as it does not terminate existing client connections.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by em-** [comment]
Err, can this be reopened by someone with enough permissions?
