### ISSUE TITLE
[bitnami/wordpress-nginx] Config Waiter is timing out.

### ISSUE THREAD

**Issue by AllenWhittaker** [bitnami/charts#25674]
### Name and Version

wordpress-with-nginx

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploying on any zone within GCP. 

### Are you using any custom parameters or values?

All Defaults are being used. 

### What is the expected behavior?

That wordpress with NGIX and SSL will deploy successfully. 

### What do you see instead?

Software config.waiter is timing out after 31 minutes. 

### Additional information

I have tried different projects as well as different regions and it still fails after 31 minutes.

**Comment by javsalgar** [comment]
Hi,

Are you using any of our charts? We only have a bitnami/wordpress helm chart but currently it only supports the variant with apache.
