### ISSUE TITLE
[bitnami/external-dns] - Traefik 3.x.x - support resource 'traefik.io' only

### ISSUE THREAD

**Issue by assices** [bitnami/charts#25677]
### Name and Version

bitnami/external-dns 7.3.0

### What is the problem this feature will solve?

Traefik CRDs `containo.us` are deprecated in favor of `traefik.io`.

[Traefik 3.x.x](https://github.com/traefik/traefik-helm-chart?tab=readme-ov-file#crds-support-of-traefik-proxy) will install `traefik.io` CRDs only.

Enabling `traefik-proxy` as `sources` with Traefik 3.x.x installed from scratch (not upgraded) external-dns fails with error message `failed to sync traefik.containo.us/v1alpha1, Resource=ingressroutes: context deadline exceeded` because CDRs and API group `traefik.containo.us` misses.

In case of Traefik upgrade to version 3.x.x, `containo.us` and `traefik.io` are both present in the cluster, so the issue doesn't occur.

### What is the feature you are proposing to solve the problem?
It seams flag `traefik-disable-legacy` can solve the issue. It there a way to configure it?

### What alternatives have you considered?

Maybe installing CRDs `containo.us` [manually](https://github.com/traefik/traefik-helm-chart?tab=readme-ov-file#upgrade-up-to-27x)

**Comment by assices** [comment]
Solved.

I fonud a way to enable the flag to Disable listeners on Resources under traefik.containo.us

```
extraArgs:
  traefik-disable-legacy:
```

**Comment by kamikaze** [comment]
sorry, but it doesn't work. I don't see this in container arguments

**Comment by assices** [comment]
> sorry, but it doesn't work. I don't see this in container arguments

Strange, on my side `extraArgs.traefik-disable-legacy` defines `--traefik-disable-legacy` argument in the container.

![image](https://github.com/bitnami/charts/assets/48159985/59815854-db9c-4983-8313-98b9a881a994)

**Comment by kamikaze** [comment]
> > sorry, but it doesn't work. I don't see this in container arguments
> 
> Strange, on my side `extraArgs.traefik-disable-legacy` defines `--traefik-disable-legacy` argument in the container.
> 
> ![image](https://private-user-images.githubusercontent.com/48159985/345324702-59815854-db9c-4983-8313-98b9a881a994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTU3MDYsIm5iZiI6MTcyMDA5NTQwNiwicGF0aCI6Ii80ODE1OTk4NS8zNDUzMjQ3MDItNTk4MTU4NTQtZGI5Yy00OTgzLTgzMTMtOThiOWE4ODFhOTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEyMTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWZlZWUwOGFkNmI0MDIwYmE3ZTdhZGI4NDVmNjdjMGU4ZTIzYzZlOWJiOTMzNTY5YjU2YzgyMDJhN2Q1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcSSn6P8tM3yQEed9pb3jKVl-F4cNO6c26xomK-LgUw)

which version of helm chart do you use? mine is 8.0.1 and still nothing:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      version: "8.x"
  values:
    logLevel: debug
    extraArgs:
      traefik-disable-legacy:
    txtOwnerId: "host-id"
    txtSuffix: "-prod"
    domainFilters:
      - host.com
      - .host.com
```

```
Arguments
--metrics-address=:7979 --log-level=debug --log-format=text --domain-filter=host.com --domain-filter=.host.com --policy=upsert-only --provider=cloudflare --registry=txt --interval=10m --txt-owner-id=host-id --txt-suffix=-prod --source=service --source=ingress --source=traefik-proxy --cloudflare-dns-records-per-page=100
```

**Comment by assices** [comment]
8.0.0, but I upgraded to 8.0.1 in my lab and it works. The chart is deployed with ArgoCD.

Template code that handles the argument is this:

```
            {{- range $key, $value := .Values.extraArgs }}
             # Extra arguments
              {{- if $value }}
            - --{{ $key }}={{ $value }}
              {{- else }}
            - --{{ $key }}
              {{- end }}
            {{- end }}
          {{- end }}
```

Did you try a manual Helm installation (not using Flux) o using Flux with a values override file?
