### ISSUE TITLE
postgresql-ha INSERT statement hanging, despite CREATE TABLE success

### ISSUE THREAD

**Issue by deed02392** [bitnami/charts#2568]
**Which chart**:
bitnami/postgresql-ha 3.2.3

**Describe the bug**
When attempting to perform an INSERT to a newly created table as the Postgres user, the instruction hangs indefinitely.

**To Reproduce**
1. Deploy the chart
2. Auth as postgres and CREATE TABLE
3. Attempt to select * from table - result is empty table
4. Attempt to insert. Execution hangs.

**Expected behavior**
INSERT should succeed and data be visible on subsequent SELECT statements.

**Version of Helm and Kubernetes**:
Helm v3
K8s 1.15

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Using the psql connection method outlined by the Helm install output. Interesting that CREATE TABLE succeeds when INSERT does not.

**Comment by deed02392** [comment]
Seems to be an application level deadlock issue. Closing.

**Comment by deed02392** [comment]
I was unable to resolve this in the application. The app us using MagicStack's asyncpg with connection pooling. 

I have switched to using bitnami/postgresql now and, without changing any app logic, everything is working. So it is probably some interoperability issue between asyncpg and pgpool or whatever is being used to make it 'HA'.

**Comment by joancafom** [comment]
Thanks for your comment @deed02392 !

I think you are right and it must be something at application interoperability level. I have tried to reproduce the steps you described and could effectively retrieve some results after an INSERT statement:
```
postgres=# SELECT * FROM alpha;

id | name
---+-----
 1   test

(1 row)
```

I am glad to see you eventually got your app to work! Do not hesitate to contact us again in case you face any further problems 😄. Thanks!

**Comment by deed02392** [comment]
Thanks @joancafom :) so you got it working using MagicStack/asyncpg with connection pool and postgresql-ha? I wonder if you can reproduce it by attempting to make two concurrent INSERT statements using two async functions?

**Comment by joancafom** [comment]
@deed02392 no sorry, I meant I could reproduce the [steps](https://github.com/bitnami/charts/issues/2568#issue-615496283) you firstly described in this issue with success, but have not tried MagicStack/asyncpg as it seems to be specific to that application. In that case, you could try to ask MagicStack.

Anyways, should you further investigate in the matter you could post your solution here if you like to, so as to contribute with the rest of the community. Thanks again!

**Comment by mecampbellsoup** [comment]
@deed02392 what did you end up doing to work around this? In our case we had to use `aiopg` backend (I assume you are also using `encode/databases` library).

I think we will likely switch our postgres HA deployment from `bitnami/postgresql-ha` to Crunchy Data's Kubernetes offering and use pgBouncer for connection pooling.

https://github.com/CrunchyData/postgres-operator#connection-pooling

**Comment by deed02392** [comment]
hi @mecampbellsoup , I ended up just using hundreds of native connections with the `postgres` chart. I am now in the process of setting up pgbouncer with a dedicated DB node instead because my performance needs have increased a lot since I first raised this issue.

**Comment by mecampbellsoup** [comment]
> hi @mecampbellsoup , I ended up just using hundreds of native connections with the `postgres` chart. I am now in the process of setting up pgbouncer with a dedicated DB node instead because my performance needs have increased a lot since I first raised this issue.

Interesting, so you setup/teardown each of those native connections (instead of using any sort of pooling) basically?

**Comment by deed02392** [comment]
Yeah basically just not using any pooling whatsoever.

Thanks for the tip! Didn't try aiopg, I'm not sure if it's a drop-in replacement for asyncpg or whether I'd need to modify a bunch of application code though (it might be the reason I never tried it).
