### ISSUE TITLE
[bitnami/odoo] Ability to extend python packages without custom image build

### ISSUE THREAD

**Issue by tbscode** [bitnami/charts#25687]
### Name and Version

bitnami/odoo

### What is the problem this feature will solve?

There is no good way to add extra add-ons that require additional python packages.
Add-ons in `/bitnami/odoo/addons` can persist and it can be utilized to install custom add-ons without modifying the base image.

And I can install python requirement to the running container using `source /opt/bitnami/odoo/venv/bin/activate && pip3 install -r /requirements.txt`

**But** the helm chart utilizes the venv at `/opt/bitnami/odoo/venv/` this is not part of any volume claim, therefore re-sets on every container start-up.

### What is the feature you are proposing to solve the problem?

A good-way to use the odoo helm chart with custom modules that require additional python packages.

I could Imagine having a separate virtual environment inside the odoo data volume claim that is linked to the `/opt/bitnami/odoo/venv/` e.g.: `/bitnami/odoo/venv` that users can install extra pip packages in.

### What alternatives have you considered?

Installing them every time at start-up using the `initContainer`.

> Please correct me if there already is another way to achieve this? 🙏🏻

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feedback! I agree that the UX could be improved with, for example, allowing via values.yaml to introduce a set of python packages and have the chart render the init container that installs the plugin. I have my concerns on persisting the full packages section of the virtual environment as it could potentially break security upgrades. However, auto-generating the pip instal init container could be a good first step. Thoughts?

**Comment by tbscode** [comment]
I like the idea, sounds like it would be a valid solution.

Personally not entirely sure how such a setup would look-like, do you do something similar in other charts.

**Comment by JacqueGM** [comment]
@tbscode @javsalgar  did you manage to find a workable solution for this? the init container approach I tried but I ran into race problem between the init and main container, also strangely enough when installing with pip instal -r requirements.txt it only installs the dist folder of the packages in requirements.txt....
