### ISSUE TITLE
[bitnami/minio] Volumes are removed on helm uninstall

### ISSUE THREAD

**Issue by ammirator-administrator** [bitnami/charts#25709]
### Name and Version

bitnami/minio 14.3.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Install minio standalone using the bitnami helm chart
Then check the created PV and see that there is a PV
The run Helm uninstall
What you'll after is that helm uninstall will remove the PV also even tho it should not which is the case with all helm charts 
But with this minio chart the volume is deleted for some reason which cause data lost and is not clear to me why that happens
Maybe is there a option to prevent that??

### Are you using any custom parameters or values?

default params, only thing that mode is standalone

### What is the expected behavior?

PV should no be deleted on helm uninstall

### What do you see instead?

PV are deleted and data is lost, this is a critical thing please investigate

**Comment by ammirator-administrator** [comment]
even if persistence.enabled:true it still removes the volumes on uninstall I guess this may be the issue that this flag is not respected, can someone check that, is a big deal if someone lose data because of this

**Comment by javsalgar** [comment]
Hi,

By default helm will delete the PVC objects created for objects like Deployments. The ones that are not deleted by default are those PVCs part of `volumeClaimTemplates` in a StatefulSet. If you want to maintain the PVC in the MInio standalone deployment, you need to add the following annotation in values.yaml:

```
persistence:
  annotations:
    helm.sh/resource-policy: keep
```

**Comment by ammirator-administrator** [comment]
Hey @javsalgar 
Thanks for answer
