### ISSUE TITLE
[bitnami/postgresql] unable to generate local authentication configuration

### ISSUE THREAD

**Issue by mecampbellsoup** [bitnami/charts#25700]
### Name and Version

bitnami/postgresql:16.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Use the `bitnami/postgresql` Helm chart, version `15.2.9`, which installs PG 16.2.0.

### What is the expected behavior?

Postgres container should initialize.

### What do you see instead?

ERROR:

```
cloud-console-postgresql-0 postgresql postgresql 18:55:19.41 DEBUG ==> Ensuring expected directories/files exist...
cloud-console-postgresql-0 postgresql postgresql 18:55:19.52 INFO  ==> pg_hba.conf file not detected. Generating it...
cloud-console-postgresql-0 postgresql postgresql 18:55:19.60 INFO  ==> Generating local authentication configuration
cloud-console-postgresql-0 postgresql popen failure: Cannot allocate memory
cloud-console-postgresql-0 postgresql initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/opt/bitnami/postgresql/bin/initdb"
- cloud-console-postgresql-0 › postgresql
```

### Additional information

Possibly related to:

* https://github.com/bitnami/containers/issues/59772

**Comment by totothekiller** [comment]
Same issue here, any update ?

**Comment by ithesadson** [comment]
Same issue here, 
$helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql -f postgres-values.yml
```
`$ cat postgres-values.yml 
image:
  debug: true

primary:
  persistence:
    storageClass: "nfs"
    size: 4Gi

volumePermissions:
  enabled: true

```
![image](https://github.com/bitnami/charts/assets/56589824/6a631c22-b2bf-428f-bbbc-7fa50281d080)

**Comment by ithesadson** [comment]
Same issue here,
$helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql -f postgres-values.yml 
```
cat postgres-values.yml 
image:
  debug: true

primary:
  persistence:
    storageClass: "nfs"
    size: 4Gi

volumePermissions:
  enabled: true
```
![image](https://github.com/bitnami/charts/assets/56589824/4c034ea0-afa7-49ba-a744-4f11c3c0fa9f)

**Comment by ithesadson** [comment]
`$  helm install postgresql bitnami/postgresql -f postgres-values.yml`
(Error with latest version)

Versiyonu 14.0.2 olarak ayarladım ve hatasız şekilde postgresql kuruldu.
`$  helm upgrade --install postgresql bitnami/postgresql -f postgres-values.yml --version 14.0.2 `

**Comment by ithesadson** [comment]
> Same issue here, $helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql -f postgres-values.yml
> 
> ```
> cat postgres-values.yml 
> image:
>   debug: true
> 
> primary:
>   persistence:
>     storageClass: "nfs"
>     size: 4Gi
> 
> volumePermissions:
>   enabled: true
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/56589824/331477223-05638452-b4e0-4143-9576-97b7eedd5cc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzczNDAsIm5iZiI6MTcxNTkzNzA0MCwicGF0aCI6Ii81NjU4OTgyNC8zMzE0NzcyMjMtMDU2Mzg0NTItYjRlMC00MTQzLTk1NzYtOTdiN2VlZGQ1Y2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA5MTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZDdiOTdjZWY0MmFlNTk4ZGZiMDBmMWVmYTRiMmIzNWJkY2E1MTVkODQ3YzQyYzYwZGUyNjg2MmM1ZDM1ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g9Kt7GbfXTEEpsn4vAVAIiT3ia0q0v2gp6LlN3P7BTE)

`$ helm install postgresql bitnami/postgresql -f postgres-values.yml
`(Error with latest version)

I set the version to 14.0.2 and installed postgresql without errors.
`$ helm upgrade --install postgresql bitnami/postgresql -f postgres-values.yml --version 14.0.2 
`

**Comment by jotamartos** [comment]
Hi @mecampbellsoup,

I just tested a fresh deployment with a subset of your changes
```
diff --git a/bitnami/postgresql/values.yaml b/bitnami/postgresql/values.yaml
index 4776bec68b..13cb3835e5 100644
--- a/bitnami/postgresql/values.yaml
+++ b/bitnami/postgresql/values.yaml
@@ -122,7 +122,7 @@ image:
   pullSecrets: []
   ## Set to true if you would like to see extra information on logs
   ##
-  debug: false
+  debug: true
 ## Authentication parameters
 ## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#setting-the-root-password-on-first-run
 ## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#creating-a-database-on-first-run
@@ -1396,7 +1396,7 @@ backup:
 volumePermissions:
   ## @param volumePermissions.enabled Enable init container that changes the owner and group of the persistent volume
   ##
-  enabled: false
+  enabled: true
   ## @param volumePermissions.image.registry [default: REGISTRY_NAME] Init container volume-permissions image registry
   ## @param volumePermissions.image.repository [default: REPOSITORY_NAME/os-shell] Init container volume-permissions image repository
   ## @skip volumePermissions.image.tag Init container volume-permissions image tag (immutable tags are recommended)
```

 and everything worked as expected


```
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Running   0          90s
```

Please review the configuration of the storage class you created and confirm that that's the issue with the deployment. I also suggest you take a look at the changes we introduced in version 15.0.0 of the Chart 

https://github.com/bitnami/charts/tree/main/bitnami/postgresql#to-1500

**Comment by mecampbellsoup** [comment]
I'm starting to wonder if these permissions are somehow inconsistent...

```
(⎈|default:cloud-console)mcampbell-1➜  ~/github/coreweave/k8s-services/dev : mc/cloud-console/enable-pg-volume-permissions ✘ :✚✭ ᐅ  helm get values --all cloud-console | grep runAsUser
        runAsUser: 5050
        runAsUser: 1001
      runAsUser: 1001
      runAsUser: 1001
      runAsUser: 1001
      runAsUser: 0
(⎈|default:cloud-console)mcampbell-1➜  ~/github/coreweave/k8s-services/dev : mc/cloud-console/enable-pg-volume-permissions ✘ :✚✭ ᐅ  helm get values --all cloud-console | grep runAsGroup
        runAsGroup: 5050
        runAsGroup: 0
      runAsGroup: 0
      runAsGroup: 0
      runAsGroup: 0
      runAsGroup: 0
(⎈|default:cloud-console)mcampbell-1➜  ~/github/coreweave/k8s-services/dev : mc/cloud-console/enable-pg-volume-permissions ✘ :✚✭ ᐅ  helm get values --all cloud-console | grep runAsNonRoot
        runAsNonRoot: true
      runAsNonRoot: true
      runAsNonRoot: true
      runAsNonRoot: true
      runAsNonRoot: false
```

**Comment by mecampbellsoup** [comment]
> Please review the configuration of the storage class you created and confirm that that's the issue with the deployment. I also suggest you take a look at the changes we introduced in version 15.0.0 of the Chart
> 
> [`main`/bitnami/postgresql#to-1500](https://github.com/bitnami/charts/tree/main/bitnami/postgresql?rgh-link-date=2024-05-17T14%3A41%3A13Z#to-1500)

I don't think this is related as chart versions 14.x.x suffer the same issue.

**Comment by mecampbellsoup** [comment]
Yea, in the end, I think this was something specific to our k8s cluster (and probably the storage class) implementation... I am no longer able to reproduce this issue w/ the original versions of the Helm chart.

**Comment by mecampbellsoup** [comment]
Seems like the issue might be realted to k8s apiserver version - see https://github.com/bitnami/charts/issues/27833.

**Comment by nh4ttruong** [comment]
It seems to relate to issue #34674 and docker-library/golang#467. So, we need to specify `libseccomp` to `Unconfined` and set `containerSecurityContext` to allow `allowPrivilegeEscalation=true` and `privileged=true`

This is fixed by setting on `values.yaml`:
```yaml
  containerSecurityContext:
    enabled: true
    privileged: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: true
    seccompProfile:
      type: "Unconfined"
```
