### ISSUE TITLE
[bitnami/redis-cluster] Scale up redis-cluster only add nodes, not resharding

### ISSUE THREAD

**Issue by zhaoanliu** [bitnami/charts#2573]
**Which chart**:
[bitnami/redis-cluster]

**Describe the bug**
I run "helm upgrade" to scale up the existing redis-cluster from 6 nodes to 12 nodes. The upgrade succeeded, and all the new nodes are up. But the slots are not resharded, so basically still 3 masters are working instead of 6.

**To Reproduce**
1. Helm install redis-cluster with default settings
2. Helm upgrade with the following settings:
"password=${REDIS_PASSWORD},cluster.init=false,cluster.nodes=12,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=6"

**Expected behavior**
3 more masters and 3 more slaves added to the cluster, and the slots are rebalanced from the 3 old masters to all 6 masters.

**Comment by zhaoanliu** [comment]
Note below, after the upgrade, cluster_known_nodes is 12 but cluster_size is 3.

redis-cluster:6379> CLUSTER INFO
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:12
cluster_size:3
cluster_current_epoch:16
cluster_my_epoch:7
cluster_stats_messages_ping_sent:254576
cluster_stats_messages_pong_sent:250836
cluster_stats_messages_meet_sent:6
cluster_stats_messages_fail_sent:22
cluster_stats_messages_sent:505440
cluster_stats_messages_ping_received:250831
cluster_stats_messages_pong_received:254248
cluster_stats_messages_meet_received:5
cluster_stats_messages_fail_received:9
cluster_stats_messages_auth-req_received:5
cluster_stats_messages_received:505098

**Comment by rafariossaa** [comment]
Hi @zhaoanliu ,
  This kind of operations are not currently handled automatically by the chart, you will need to reshard it manually. 
  For reference: https://redis.io/topics/cluster-tutorial#resharding-the-cluster.

**Comment by ganeshjaju** [comment]
> Hi @zhaoanliu ,
> This kind of operations are not currently handled automatically by the chart, you will need to reshard it manually.
> For reference: https://redis.io/topics/cluster-tutorial#resharding-the-cluster.

Hi,
As I can see, the cluster upgrade still does not auto reshard the slots when persistence is enabled.
Is this supported? If not, any plans for this in the near future?

**Comment by juan131** [comment]
@rafariossaa @miguelaeh do you know if we created an internal task to support this in the chart?

**Comment by rafariossaa** [comment]
@juan131 , we don't have a task for this.

**Comment by rafariossaa** [comment]
I have just created the task to study the what can be done regarding resharding in this chart.

**Comment by juan131** [comment]
Thanks @rafariossaa

**Comment by miguelaeh** [comment]
Thank you very much @rafariossaa , sorry guys I missed this thread.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
