### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] metrics-endpoint serviceMonitor references missing port

### ISSUE THREAD

**Issue by tolleiv** [bitnami/charts#25743]
### Name and Version

bitnami/rabbitmq-cluster-operator 4.2.8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Release the chart with it's default values and monitoring enabled.

`helm template rabbitmq-cluster-operator "oci://registry-1.docker.io/bitnamicharts/rabbitmq-cluster-operator" --version 4.2.8 --set clusterOperator.metrics.serviceMonitor.enabled=true --set clusterOperator.metrics.service.enabled=true --namespace=demo`

The rendered resources include a ServiceMonitor with two endpoints:

```
---
# Source: rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-cluster-operator
    ...
spec:
  ...
  endpoints:
    - port: http
    - port: metrics
---
```

where the related Deployment only has a single port:

```
---
# Source: rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  ...
spec:
    ...
    spec:
      ...
      containers:
        - name: rabbitmq-cluster-operator
          ...
          ports:
            - name: http
              containerPort: 9782
              protocol: TCP
---
```

### Are you using any custom parameters or values?

clusterOperator.metrics.serviceMonitor.enabled=true
clusterOperator.metrics.service.enabled=true

### What is the expected behavior?

The ServiceMonitor should only reference existing ports.

### What do you see instead?

The `metrics` Port is part of the ServiceMonitor without being present on the Deployment.

### Additional information

The second port was introduce in https://github.com/bitnami/charts/commit/dceeb500a15f7b9580f39a519ccbbba8a787c683 - maybe a feature flag should be added or some more documentation.

**Comment by tolleiv** [comment]
Maybe also the author @basit9958 of the change [dceeb50](https://github.com/bitnami/charts/commit/dceeb500a15f7b9580f39a519ccbbba8a787c683) could add their two cents on this one.

**Comment by tolleiv** [comment]
Before this get's stale, I'll try to come up with a pull request in the next days. Would be great to get input on this one beforehand.

**Comment by javsalgar** [comment]
Hi,

I believe that the metrics endpoint references the RabbitMQ instances created by the operator. It's not clear to me whether the selector actually matches the created instances.

**Comment by tolleiv** [comment]
> Hi,
> 
> I believe that the metrics endpoint references the RabbitMQ instances created by the operator. It's not clear to me whether the selector actually matches the created instances.

The RabbitMQ instances do not have `metrics` endpoints either, those are named `prometheus` -> https://github.com/rabbitmq/cluster-operator/blob/HEAD/internal/resource/service.go#L240 - not sure what the initial idea behind the change was.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
