### ISSUE TITLE
[bitnami/keycloak] Enabling metrics for Keycloak

### ISSUE THREAD

**Issue by zohebk8s** [bitnami/charts#25847]
### Name and Version

bitnami/keycloak:18.0.0-debian-10-r6

### What architecture are you using?

None

### What steps will reproduce the bug?

Keycloak is slow and wanted to have metrics enabled for Keycloak. So that it can be visualised in Grafana.

### Are you using any custom parameters or values?

No

### What do you see instead?

Performance improvements and metric’s enablement for Keycloak.

do we need to add any custom parameter for metrics enablement? Like KC_OTEL etc

**Comment by zohebk8s** [comment]
I’ve gone through bitnami Keycloak & official Keycloak documentation. Unfortunately couldn’t find the steps or process to figure out this problem.

Appreciate your feedback on this?

**Comment by rafariossaa** [comment]
Hi @zohebk8s ,
  Sorry for the delay.
  Not sure what is this issue about. There is a parameter in the values to enable the metrics in keycloak. Could you elaborate on what you have tried so far and the issues you have found ?
