### ISSUE TITLE
[bitnami/haproxy] allow  to set enableServiceLinks

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/charts#25851]
### Name and Version

bitnami/haproxy 1.1.2

### What is the problem this feature will solve?

I need to set `enableServiceLinks: false` because I have too much environment variables, the chart does not allow to set it.

### What is the feature you are proposing to solve the problem?

I propose to add a chart value `enableServiceLinks`, true by default.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
