### ISSUE TITLE
[bitnami/redis] Missing support for kubernetes 1.16

### ISSUE THREAD

**Issue by javsalgar** [bitnami/charts#2585]
**Description**
When installing bitnami/redis 10.6.3 you receive the following error:

```bash
no matches for kind "Deployment" in version "extensions/v1beta1"
```
This is due to the `Deployment` kind being moved top the `apps/v1` api resource.

**Steps to reproduce the issue:**

1. Install Kubernetes 1.16+ (Now the default in Docker Desktop)
2. `helm repo add bitnami https://charts.bitnami.com/bitnami`
3. `helm install bitnami/redis --version 10.6.13`

The error above is received.

**Describe the results you expected:**

The redis chart installs as expected

**Version**

|Kind | Version|
|---|---|
|OS|Mac 10.15.3|
|Docker Installation|Docker Desktop 2.3.0.2|
|Docker|19.03.8|
|Kubernetes|1.16+|

Original: https://github.com/bitnami/bitnami-docker-redis/issues/170

**Comment by javsalgar** [comment]
Hi @ericp96

This is very strange, the chart does not have any Deployment. I was unable to reproduce it 

``
 1 ❯ helm install redis  bitnami/redis --version 10.6.13
NAME: redis
LAST DEPLOYED: Thu May 14 10:11:37 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **
Redis can be accessed via port 6379 on the following DNS names from within your cluster:

redis-master.default.svc.cluster.local for read/write operations
redis-slave.default.svc.cluster.local for read-only operations


To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis server:

1. Run a Redis pod that you can use as a client:

   kubectl run --namespace default redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:6.0.1-debian-10-r1 -- bash

2. Connect using the Redis CLI:
   redis-cli -h redis-master -a $REDIS_PASSWORD
   redis-cli -h redis-slave -a $REDIS_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/redis-master 6379:6379 &
```

Are you using the latest helm version? Did you execute helm repo update?

**Comment by ericp96** [comment]
Hi @javsalgar - thanks for taking a look! I must not have updated the repo to the latest because it appears the issue is fixed (as you pointed out).  My apologies.

**Comment by javsalgar** [comment]
Hi, 

Good to know! do not hesitate to open a new ticket if you find more issues
