### ISSUE TITLE
[bitnami/mastodon] Mastodon shows a blank page when the ingress otpion is enabled in the values file with traefik ingress controler

### ISSUE THREAD

**Issue by shuma-g0rath** [bitnami/charts#25868]
### Name and Version

bitnami/mastodon 4.2.8-debian-12-r6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am on a 3 nodes kubernetes v1.28.9 cluster using traefik v3.0.0 installed using the official helm chart. Metallb is also used as load balancer for some applications.
When deploying a new instance of mastodon using the bitnami helm chart I can succesfully  (for testing purpose only) login using the ip address assigned to the mastodon-apache service by metallb, so it seems everything is working correctly.
When I try to access mastodon using the public domain name through the ingress created by the helm chart I get a blank page after having provided my admin user credentials

### Are you using any custom parameters or values?

--set apache.enabled=true
-- set apache.ingress.enabled=true
--set apache.ingress.hostname=mastodon.example.com

### What is the expected behavior?

the mastodon homepage should appear after a succesful login when using the public domain name referenced by the ingress.

### What do you see instead?

The browser shows a blank page.

### Additional information

I don't see any information in the traefik logs or the different mastodon pods logs that could explain this behavior. I also tried to completely disable the apache deployment in the values file and replace it by an nginx deployment using a custon serverblock instead and point an ingress or ingressroute to this pod's service. I also tried to setup traefik ingressroutes directly pointing to the mastodon-web and mastodon-streaming services using different sets of rules based on pathprefix. The result is the same.

**Comment by jotamartos** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by huang-jy** [comment]
FWIW, I hit this problem also. If you port forward to the installation and use localhost, everything is fine, but if you map an ingress to it, with SSL (I used Nginx), you get a blank page on login, so I think something in the Apache subchart is not configuring right
