### ISSUE TITLE
Back-off restarting failed container kafka-init in pod

### ISSUE THREAD

**Issue by KarthikShantharam** [bitnami/charts#25877]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

In a Dev environment with tls enabled with the below values.yaml (actual will be injected through terraform tf file), with tls certificate generated with ca.crt, tls.key, tls.crt, keystore.jks and truststore.jks in "kakfka-tls-secret" the PODs fails with below exception
```
Back-off restarting failed container kafka-init in pod ba19133-dev-stream-eks-deploy-kafka-controller-0_ba19133-dev-stream(78ef18a9-6be2-4591-8379-5f80c8580045)
```

### What is the expected behavior?

The PODs spin up and get clustered, similar configuration works fine in openshift cluster and facing issues in AWS EKS cluster

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
