### ISSUE TITLE
[bitnami/keycloak] Keycloak parameters missing documentation for tag value

### ISSUE THREAD

**Issue by Dmarcotrigiano** [bitnami/charts#25870]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The tag value works and is not documented.
![image](https://github.com/bitnami/charts/assets/79153083/6d7136d7-0635-4436-ae79-cc88a82aeb8e)

### What do you see instead?

This is a doc report

**Comment by carrodher** [comment]
Hi, thanks for letting us know, tags are removed on purpose from the table, see https://github.com/bitnami/charts/pull/19841
