### ISSUE TITLE
Broken WordPress Links

### ISSUE THREAD

**Issue by vivekmistry** [bitnami/charts#2587]
**Which chart**:
Wordpress, Nginx-Ingress-Controller, Nginx

**Describe the bug**:

Have installed Wordpress + Nginx on Wordpress on GKE. Using Ingress Controller, have routed my website to Wordpress Service.
From connection wise, everything is working as properly but while accessing the site using the domain name, the website is not properly loaded and there are broken links.
Below is the snippet of nginx.conf file. Please advise, whether it is correct or need amendment?

data:
nginx.conf: |-
server {
listen 80;
index index.php index.html;
server_name example.com; ## will replace will actual dns name
error_log /var/log/nginx/error.log;
access_log /var/log/nginx/access.log;
root /var/www/html;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass {{ template "wordpress.fullname" . }}:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

The following are logs from Wordpress Pod:

wordpre INFO
nami    INFO  wordpress successfully initialized
INFO  ==> Starting gosu...
[Thu May 14 13:13:50.682725 2020] [ssl:warn] [pid 74] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu May 14 13:13:50.683776 2020] [ssl:warn] [pid 74] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu May 14 13:13:50.759196 2020] [ssl:warn] [pid 74] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu May 14 13:13:50.759910 2020] [ssl:warn] [pid 74] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Thu May 14 13:13:51.234311 2020] [mpm_prefork:notice] [pid 74] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.5 configured -- resuming normal operations
[Thu May 14 13:13:51.234630 2020] [core:notice] [pid 74] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
10.4.2.1 - - [14/May/2020:13:13:52 +0000] "GET /wp-login.php HTTP/1.1" 200 1833
10.4.2.1 - - [14/May/2020:13:14:01 +0000] "GET /wp-login.php HTTP/1.1" 200 4788
10.4.2.1 - - [14/May/2020:13:14:02 +0000] "GET /wp-login.php HTTP/1.1" 200 1833
10.128.0.27 - - [14/May/2020:13:14:10 +0000] "GET /wp-login.php HTTP/1.1" 200 4788
10.4.2.1 - - [14/May/2020:13:14:10 +0000] "GET /wp-login.php HTTP/1.1" 200 4788
10.4.0.66 - - [14/May/2020:13:14:10 +0000] "HEAD / HTTP/1.1" 200 -
10.4.2.1 - - [14/May/2020:13:14:12 +0000] "GET /wp-login.php HTTP/1.1" 200 1833
10.128.0.26 - - [14/May/2020:13:14:17 +0000] "GET /wp-login.php HTTP/1.1" 200 4788
10.4.2.1 - - [14/May/2020:13:14:22 +0000] "GET /wp-login.php HTTP/1.1" 200 1833
--More--(2%)

**To Reproduce**

**Expected behavior**
Please whether the nginx-conf is in right order?
**Version of Helm and Kubernetes**:

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}

- Output of `kubectl version`:

Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
vivekmistry163@cloudshell:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by joancafom** [comment]
Hello @vivekmistry !

From what I have understood, you are using an Ingress Controller, a NGINX Chart and a Wordpress Chart. The connection you are describing should look something like this:

`Ingress Controller <-> NGINX <-> Wordpress`

Bitnami's Wordpress Chart includes an Apache Server that will take care of rendering the request, so you don't need to configure an external NGINX Server 😁. Hence, you can directly route your Ingress Controller to the Wordpress' own Service:

`Ingress Controller <-> Wordpress`

I think that by removing NGINX, not only will your links work, but you will avoid a redundant stage. In order to enable Wordpress ingress integration you may take a look at the [docs](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#ingress). 

Could that work for you? Thanks!
