### ISSUE TITLE
[bitnami/mlflow] MLFlow separate settings for Auth database

### ISSUE THREAD

**Issue by truealex81** [bitnami/charts#25945]
### Name and Version

bitnami/mlflow 1.0.6

### What is the problem this feature will solve?

Right now it is not possible to place auth database in the same postgresql database, but in different schema. For example in Azure CosmosDB for PostgreSQL is not possible to create more than one standard database on the server instance. So the only way to separate MLFlow databases is to create different schemas (for different users) and use them as a separate database. 

### What is the feature you are proposing to solve the problem?

Introduce separate additional parameters for auth database configuration:
```
externalAuthDatabase:
  host: 
  port: 
  database: 
  user: 
  password: 
```
### What alternatives have you considered?

Right now the only alternative in my current situation is to create whole new separate Azure CosmosDB for PostgreSQL instance which is not cost efficient.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Would you like to submit a PR adding this support?

**Comment by frittentheke** [comment]
This is quite a reasonable request. Please kindly leave open.
