### ISSUE TITLE
[bitnami/mariadb] chart doesn't has connection encryption options

### ISSUE THREAD

**Issue by trustdark** [bitnami/charts#2594]
**Which chart**:
MariaDB version: 7.3.10

**Is your feature request related to a problem? Please describe.**
Just found out that that enabling encryption from value.yaml is impossible as it done mariadb-galera

**Describe the solution you'd like**
I would like to see option enable.tls=true inside values.yaml with possibility to add certificates as secret

**Describe alternatives you've considered**
Using mariadb-galera or enabling encryption via config files

**Comment by dani8art** [comment]
Hi @trustdark, thank you very much for your proposal, I would like to know a bit more. When you say encryption, do you mean connection encryption like [Data-in-Transit Encryption](https://mariadb.com/kb/en/secure-connections-overview/) or tablespace encryption like [Data-at-Rest Encryption](https://mariadb.com/kb/en/data-at-rest-encryption-overview/)?

**Comment by trustdark** [comment]
Hi, @dani8art, sorry for my poor English. I meant connection encryption like Data-in-Transit Encryption. 
Unfortunately project was started with mariadb. Right now its still possible to migrate on mariadb-galera but it looks strange that such important feature is not present in chart but also available in similar chart. 
Just curious, why do you support 2 charts - mariadb and mariadb-galera?

**Comment by dani8art** [comment]
> Just curious, why do you support 2 charts - mariadb and mariadb-galera?

The main difference between them if the topology.

- `bitnami/mariadb` implements a standalone deployment and master-slave cluster type.
- `bitnami/mariadb-galera` implements a master-master topology.

**Comment by trustdark** [comment]
Sounds challenging! In 2 weeks ill have day off and try to prepare PR similar to mariadb-galera.
