### ISSUE TITLE
[bitnami/mongodb] Allow templating for initdbScriptsConfigMap 

### ISSUE THREAD

**Issue by AzHicham** [bitnami/charts#25966]
### Name and Version

bitnami/mongodb 15.4.3

### What is the problem this feature will solve?

Right now it's not possible to do the following: 
```
mongodb:
  initdbScriptsConfigMap: '{{ include "common.names.fullname" $ }}-configmap'
```
Because according to this [code](https://github.com/bitnami/charts/blob/c289f0e8815089f52b77d8977fe8e1793bf19ff5/bitnami/mongodb/templates/_helpers.tpl#L225) no templating is allowed. 

Without this possibility the configmap name must be hardcoded.

### What is the feature you are proposing to solve the problem?

A simple solution is to change in the code the following line : 
`{{- printf "%s" .Values.initdbScriptsConfigMap -}}`
by this one 
`{{- printf "%s" (tpl .Values.initdbScriptsConfigMap $) -}}`

tpl is often used in bitnami charts (postgresql, even in mongodb chart) in order to allow this kind of templating

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team, but as it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding this feature?

**Comment by AzHicham** [comment]
Hello, 
I'll try to create a PR asap :)

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
