### ISSUE TITLE
Failing to helm repo update

### ISSUE THREAD

**Issue by achar007** [bitnami/charts#25960]
### Name and Version

bitnami/mariadb

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```console
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "bitnami" chart repository (https://charts.bitnami.com/bitnami):
	Get "https://charts.bitnami.com/bitnami/index.yaml": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Update Complete. ⎈Happy Helming!⎈
```

### Are you using any custom parameters or values?

no

**Comment by achar007** [comment]
![image](https://github.com/bitnami/charts/assets/41984491/f73f244b-5d27-4dd6-adc2-9d2cb25d1d96)

**Comment by carrodher** [comment]
We are not able to reproduce the issue:
```console
$ helm repo ls
NAME   	URL
bitnami	https://charts.bitnami.com/bitnami

$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
```
Maybe it was a transient issue or something related to your connection.

In the same way, please note the recommended way of consuming Bitnami Helm charts is using OCI in [DockerHub](https://hub.docker.com/u/bitnamicharts).

**Comment by achar007** [comment]
Finally issue got resolve, not sure what's the resolution.

helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

**Comment by simonreddy2001** [comment]
We are facing similar issue 
![image](https://github.com/bitnami/charts/assets/77497059/0951e81b-ed8e-428d-af7a-60a122abc80f)
Any solution to solve this ?

**Comment by carrodher** [comment]
Hi, we don't have any record of malfunction on our logs, could you please check if it could be an issue related to a firewall rule, ISP or something like that?
