### ISSUE TITLE
[bitnami/thanos] receiveDistributor is not set up to work properly in the chart

### ISSUE THREAD

**Issue by AlexDCraig** [bitnami/charts#25991]
### Name and Version

bitnami/thanos 15.4.6

### What is the problem this feature will solve?

It's a good idea to run Thanos receive in "dual" mode in this chart, where there is a fleet of distributors and a fleet of ingesters. Unfortunately, the chart isn't set up right for this though, because it doesn't allow for a service or ingress under ``receiveDistributor``.

I'm assuming that when you're using the ``receiveDistributor``, your Prometheus remote write instances should be pointed at an ingress that routes traffic to ``receiveDistributor``. Therefore, I think these two components are necessary.

### What is the feature you are proposing to solve the problem?

Add a service that's on by default. Add an ingress that you can turn on.

### What alternatives have you considered?

You can always create services and ingresses out of band of the chart.

**Comment by AlexDCraig** [comment]
Looking at this more, I'm pretty confused how this is supposed to work. Maybe I am misunderstanding? Following this: https://thanos.io/tip/proposals-accepted/202012-receive-split.md/

The ``receiveDistributor`` in this chart has no ingress, service, or hashring configured, but the ``receive`` does. Isn't that opposite? Quoting the article:

> This allows setting optional deployment model were only routing receivers are using hashring files and does the routing and replication. That allows ingesting receivers to not handle any routing or hashring, only receiving multi tenant writes.

In this case, isn't ``receive`` the ingester, and ``receiveDistributor`` the routing receiver? It doesn't seem like the chart is set up this way.

**Comment by AlexDCraig** [comment]
Looking at this more, I'm puzzled how ``receiveDistributor`` is supposed to work here... How does it form a hash ring with other members of its deployment?

**Comment by srekkas** [comment]
As i understand with this config two services is created
thanos-receive     -     
thanos-receive-distributor pods
thanos-receive-headless     - thanos-receive pods

then you use like this "thanos-receive.observability.svc.cluster.local" for prometheus remote write.

receive:
  ## @param receive.enabled Enable/disable Thanos Receive component
  ##
  enabled: true
  logLevel: info
  mode: "dual-mode"
  tsdbRetention: 15d
  replicationFactor: 3
  replicaCount: 3
  service:
    additionalHeadless: true

receiveDistributor:
  ## @param receiveDistributor.enabled Enable/disable Thanos Receive Distributor component
  ##
  enabled: true
  replicaCount: 3
  replicationFactor: 3

**Comment by AlexDCraig** [comment]
I understand now that the chart does work properly, it's just confusing because the service and ingress of receive flip to point at receiveDistributor when you've enabled dual mode.

Still, I would appreciate a separate service for the ingesters in this case, because as-is you can't monitor the ingesters in the chart, because there's only one service and it points at receiveDistributor.

**Comment by rgarcia6520** [comment]
Had a single standalone thanos running fine for several weeks. 

Attempted to turn on autoscaling with the above values to ensure the `receiveDistributor` is enabled and `receive.mode="dual-mode"` and only received errors in prometheus writing and no data in thanos or graphs with no errors in the latter. 

Ensured that hashring for hard-set 3 thanos-receive replicas looked like the following:
```
  hashrings.json: |-
    [
      {
        "hashring": "default",
        "tenants": [],
        "endpoints":["thanos-receive-0.thanos-receive-headless.thanos.svc:19091","thanos-receive-1.thanos-receive-headless.thanos.svc:10901","thanos-receive-2.thanos-receive-headless.thanos.svc:10901"]
      }
    ]
```

All pods in thanos NS were Running and happy but prometheus pods configured for remoteWrite only showed the following:

```
msg="Failed to send batch, retrying" err="server returned HTTP status 503 Service Unavailable: 3 errors: backing off forward request for endpoint {thanos-receive-0.thanos-receive-headless.thanos.svc:19091 0}: target not available; forwarding request to endpoint thanos-receive-1.thanos-receive-headless.thanos.svc:10901: rpc error: code = AlreadyExists desc = add 674 samples: out of bounds; forwarding request to endpoint thanos-receive-2.thanos-receive-headless.thanos.svc:10901: rpc error: code = AlreadyExists desc = add 669 samples: out of bounds\n" 

&&

target not available; backing off forward request for endpoint {thanos-receive-2.thanos-receive-headless.thanos.svc:10901 0}: target not available; forwarding request to endpoint thanos-receive-1.thanos-receive-headless.thanos.svc:10901: rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: read tcp 10.42.7.242:46964->10.42.2.142:10901: read: connection reset by peer\"
```

When port-forwarding to the individual pods, HTTP/GET requests were successful and returned information. No networkpolicies were in place in thanos NS.

**Comment by rajbaratht** [comment]
@rgarcia6520 I'm getting the same error. Did you find a solution for this ?

```
ts=2024-12-09T21:05:25.854Z caller=dedupe.go:112 component=remote level=warn remote_name=thanos-receiver url=http://thanos-receive.local:19291/api/v1/receive msg="Failed to send batch, retrying" err="server returned HTTP status 503 Service Unavailable: 4 errors: backing off forward request for endpoint {thanos-receive-1.thanos-receive-headless.thanos.svc.cluster.local:10901 0}: target not available; backing off forward request for endpoint {thanos-receive-2.thanos-receive-headless.thanos.svc.cluster.local:10901 0}: target not available; forwarding request to endpoint thanos-receive-0.thanos-receive-headless.thanos.svc.cluster.local:10901: rpc error: code = Unavailable desc = name resolver error: produced zero addresses; forwarding request to endpoint thanos-receive-3.thanos-receive-headless.thanos.svc.cluster.local:10901: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
```

**Comment by rgarcia6520** [comment]
@rajbaratht No, I added a comment here https://github.com/thanos-io/thanos/issues/5407#issuecomment-2501371688 which appears to still be open upstream. I migrated back to just a single receive pod with large resources which seems to be working smoothly for my environments.

**Comment by rgarcia6520** [comment]
Appreciate the response and glad to hear it, unfortunately I had confirmed my endpoints in the hashring were all correct and were receiving responses just fine but messages were not getting past the receive-distributor and only getting that error even after a couple hours of sending messages in. Going back to single receive pod/endpoint messages were flowing steady again.

**Comment by bshelton** [comment]
@rgarcia6520 I just ran into this exact issue in my environment. It turns out my headless service was missing the correct selector labels. It wasn't until I got some traffic and it activated the HPA did I find this out. Check if your headless service has any endpoints. That's what was causing the dns resolving issues for me.
