### ISSUE TITLE
Can Cassandra have the loadbalancer in front ? 

### ISSUE THREAD

**Issue by Jenishk56** [bitnami/charts#2600]
**Which chart**:
Cassandra

**Describe the bug**
Not a bug but a query on implementation. Best of my understanding, Cassandra is not good to have the load balancer in front. But as the Cassandra helm chart got this functionality as per the documentation:- 

`service.loadBalancerIP | LoadBalancerIP if service type is LoadBalancer | nil
`
This suggests We can have the loadbalancer. Also, the headless service suggests more or less similar by randomly picking up the Cassandra nodes from the cluster. 

Am I missing something in here? I am trying to figure out this badly and trying to implement it to have the separate Passthrough for separate Cassandra pods considering we can't have the Loadbalancer.

Best,
Jenish

**Comment by rafariossaa** [comment]
Hi,
  If you install the chart you will get some information on how to connect from a client. Maybe this will cast some light for you.
  The headless service is use to interconnect nodes, have into account that you can span and kill node dynamically and the cluster have to be able to handle this situations.

**Comment by Jenishk56** [comment]
Thanks for getting back @rafariossaa

I tried it already. While trying through the Load balancer way, It asks me to connect at the LoadbalancerIP which is a single point (LoadbalancerIP:9042). The document doesn't provide much information about it.

Headless, again comes to the same funda where it says for '
e.g. CQL: cassandra.default.svc.cluster.local:9042

This means, cassandra.default.svc.cluster.local behaves like a load balancer entry point and can randomly pick any of the pod through it.

**Comment by rafariossaa** [comment]
Hi, 
  Usually,the LB is used to connect from clients, meanwhile the headless svc is use to a node to connec to the rest of the cluster. In kuberentes you don't really know the name of the nodes as they are dinamically created, so if you start a cluster with nodes: node-0, node-1, node-2, later it could be 3,4,5, and you need to pass the list of nodes to a node become part of the cluster. By using the headless you can point new nodes to the svc and become part of the cluster as other nodes are yet under that svc.
