### ISSUE TITLE
i did  install  phpmyadmin 

### ISSUE THREAD

**Issue by stevenbill** [bitnami/charts#2603]
i did  install  phpmyadmin by  helm  but  i dont know  how  can i  get  user and  pass

**Comment by javsalgar** [comment]
Hi,

The user and password should be the one of the database you are trying to connect. Do you have the credentials of your database?

**Comment by stevenbill** [comment]
i did  install it by helm 
from this  link  
https://github.com/bitnami/charts

**Comment by stevenbill** [comment]
i did  install it by helm 
from this  link  
https://github.com/bitnami/charts

**Comment by stevenbill** [comment]
i did  install it by helm 
from this  link  
https://github.com/bitnami/charts

**Comment by stevenbill** [comment]
its  show to  me  this error  
 Cannot log in to the MySQL server

mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by javsalgar** [comment]
Hi,

Could you show the output of this command? We need to ensure that the database was initialized

```
kubectl get pods
```

Then, were you able to obtain the database credentials?
