### ISSUE TITLE
[bitnami/Ghost] ghost/charts/common/templates/_secrets.tpl:43: function "get" not defined

### ISSUE THREAD

**Issue by jonneolie** [bitnami/charts#2604]
Hi,

When i try to deploy the Ghost template, i get the following message. 

Wait helm template failed. Error: parse error in "ghost/charts/common/templates/_secrets.tpl": template: ghost/charts/common/templates/_secrets.tpl:43: function "get" not defined : exit status 1

Is there something i can do to fix this, or is this an issue with the Ghost helm chart?

If you need more information, please let me know.

**Comment by marcosbc** [comment]
Hi @jonneolie, how are you installing the Ghost chart?

Note that if you run the command in the cloned bitnami/charts directory, you will need to enter the "bitnami/ghost" directory and run the below command:

    helm dep update

If that is not the case, let us know the specifics so we can try to reproduce this issue on our side.
