### ISSUE TITLE
ServiceMonitor for kublet and cadvisor not working in Azure

### ISSUE THREAD

**Issue by james-knott** [bitnami/charts#2607]
**Which chart**:
bitnami/prometheus-operator

**Describe the bug**
When deploying helm chart I had to change https to http in order to allow the servicemonitor to work. I see that you can change the servicemonitor to use http in the values.yaml but I would like to get https to work. Is this possible with the helm chart?

**To Reproduce**
```
helm3 install prometheus-operator --namespace monitoring \
  --set prometheus.thanos.create=true \
  --set operator.service.type=ClusterIP \
  --set prometheus.service.type=ClusterIP \
  --set alertmanager.service.type=ClusterIP \
  --set prometheus.thanos.service.type=NodePort \
  --set prometheus.externalLabels.cluster="Development" \
  -f prod-values.yaml \
  bitnami/prometheus-operator
```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:  

```
3.21
```

- Output of `kubectl version`:

```
1.15.10
```

**Comment by miguelaeh** [comment]
Hi @james-knott ,
Just to confirm, do you have `kubelet.serviceMonitor.https` to `true`? It seems that `true` is the default value if it is not working maybe this could be a bug.
Could you share your `prod-values.yaml` ?

**Comment by james-knott** [comment]
Yes I will Thank you

**Comment by miguelaeh** [comment]
Hi @james-knott ,
I installed the Helm Chart with your same parameters except the `serviceMonitor.https=false` and I am not getting any error, could you share wich is the error you are getting?

**Comment by james-knott** [comment]
server returned HTTP status 401 Unauthorized

**Comment by miguelaeh** [comment]
Hi @james-knott ,
I am still not able to reproduce your issue, could you be more specific? Where are you getting that `401` error?
Also, have in mind that it is an `Unauthorized` error that should not be related to `https`

**Comment by james-knott** [comment]
The Target is giving the error on the prometheus dashboard
