### ISSUE TITLE
[bitnami/mariadb] 18.0.6 upgrading fails with lost connection

### ISSUE THREAD

**Issue by anotherglitchinthematrix** [bitnami/charts#26105]
### Name and Version

bitnami/mariadb:18.0.6

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I just simply updated the helm version from `bitnami/mariadb:16.3.2` to `bitnami/mariadb:18.0.6`, but during `mysql-upgrade` and `mysql-check` the error below thrown and the whole `mysql-upgrade` and the `mysql-check` steps repeated indefinetly and I had to stop release to downgrade the chart eventually, I enabled the `image.debug=true` before downgrade but nothing useful thrown but the error below, I suspect some timeout or some packet size limit caused this, but even after I maxed all of the timeout and packet limits it's just keep crashing and restarting the upgrade process, for information, the pod never restarted only the upgrade processes. 

If it helps, the mariadb server I'm trying to upgrade has over 300 databases and is about 13 GB, do you think the size is causing the issue and do you have any advice on upgrading the server with such a load?

> Lost connection to server during query when executing 'CHECK TABLE ... FOR UPGRADE'

### Are you using any custom parameters or values?

```yaml
mariadb:
  fullnameOverride: mariadb
  global:
    storageClass: oci-bv
  auth:
    database: application
    rootPassword: secret
    username: user
    password: secret
  image:
    debug: true
    persistence:
      size: 64Gi
    configuration: |
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      datadir=/bitnami/mariadb/data
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=1073741824
      connect_timeout=31536000
      max_connections=100000
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8MB4
      collation-server=utf8mb4_unicode_ci
      slow_query_log=0
      long_query_time=10.0
      innodb_log_file_size=268435456
      innodb_buffer_pool_size=268435456
      innodb_io_capacity=1000
      join_buffer_size=512000
      sort_buffer_size=512000
      preload_buffer_size=64000
      net_read_timeout=3600
      net_read_timeout=3600
      wait_timeout=31536000
      sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      optimizer_switch=condition_pushdown_for_derived=on,condition_pushdown_for_subquery=on,condition_pushdown_from_having=on,derived_merge=on,derived_with_keys=on,exists_to_in=on,extended_keys=on,firstmatch=on,hash_join_cardinality=off,in_to_exists=on,index_condition_pushdown=on,index_merge_intersection=on,index_merge_sort_intersection=off,index_merge_sort_union=on,index_merge_union=on,index_merge=on,join_cache_bka=on,join_cache_hashed=on,join_cache_incremental=on,loosescan=on,materialization=on,mrr_cost_based=off,mrr_sort_keys=off,mrr=off,not_null_range_scan=off,optimize_join_buffer_size=on,orderby_uses_equalities=on,outer_join_with_cache=on,partial_match_rowid_merge=on,partial_match_table_scan=on,rowid_filter=on,semijoin_with_cache=on,semijoin=on,split_materialized=off,subquery_cache=on,table_elimination=on

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
```

### What is the expected behavior?

Upgrading successfully like upgrading from older versions.

### What do you see instead?

Crashing on mysql-upgrade and mysql-check steps when upgrading the helm chart version.

**Comment by anotherglitchinthematrix** [comment]
There is something suspicious, when I tried to downgrade the error below raised and I had to remove the stateful set to recover. 

```bash
opt/bitnami/scripts/libos.sh: line 346:    48 Killed                  "$@"
```

**Comment by javsalgar** [comment]
Hi,

Are you setting resources in the chart? This "Killed" error looks to me related to out of memory errors?

**Comment by javsalgar** [comment]
By default the chart configures a set of minimal resources that work in our test environments, but definitely not suitable for production. Could you try setting the resources section? I believe this issue has to do with not enough memory set for your use case.
