### ISSUE TITLE
[postgres] Add option to disable default metrics

### ISSUE THREAD

**Issue by mcritchlow** [bitnami/charts#2611]
**Which chart**:
Postgres (and presumably HA), latest.

**Is your feature request related to a problem? Please describe.**
My use case is to use the Postgres helm chart in our application and expose metrics for Prometheus/Grafana. Our DBA has no interest in the default metrics, or at least wants enough disabled that I'd prefer to build up what we want via `customMetrics`. 

The exporter image supports disabling the default metrics [as a flag](https://github.com/wrouesnel/postgres_exporter#flags) via `disable-settings-metrics` or [an environment variable](https://github.com/wrouesnel/postgres_exporter#environment-variables) via `PG_EXPORTER_DISABLE_DEFAULT_METRICS`, however this option does not appear to be made available via the Helm chart. 

**Describe the solution you'd like**
What would be great, is a chart option along the lines of `metrics.defaultMetrics.enabled`, presumably with a default value of `true`.

**Describe alternatives you've considered**
Not having this isn't the end of the world :) I won't include these defaults in our Grafana dashboard, and we can definitely make due.

Also, if I'm just missing a way to leverage this with the chart as-is, I apologize!

**Additional context**
N/A

**Comment by juan131** [comment]
Hi @mcritchlow 

Thanks for your feedback!

I agree with you, we should support a parameter to set that flag or, as a generic alternative, support a way to add any extra flag or environment variable to the PostgreSQL Prometheus exporter container.

Please feel free to submit a PR implementing one of these alternatives, and we'll be glad to review it and add it to the PostgreSQL chart.

**Comment by mcritchlow** [comment]
Hi @juan131 , thanks! Ok sounds good. I'll see what my employer is up for. 

> a parameter to set that flag

This does sound like a quick win, and I could probably get a PR up for that quickly, but, as you noted:

> as a generic alternative, support a way to add any extra flag or environment variable to the PostgreSQL Prometheus exporter container

This seems more desirable, particularly going the environment variable route, because it takes the work off of you all to maintain individual flags. 

That said, I'll see what kind of time I can spend and try to propose something soon.

**Comment by mcritchlow** [comment]
@juan131 - I took a pass using the `extraEnvVars` pattern: https://github.com/bitnami/charts/pull/2620 and it seems to be working for me. Let me know what you think, thanks!

**Comment by juan131** [comment]
Checking your PR, thanks so much for implementing this!
