### ISSUE TITLE
[bitnami/milvus] configure externalKafka tls settings

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#26110]
### Name and Version

bitnami/milvus 7.0.5

### What is the problem this feature will solve?

now the image docker.io/bitnami/milvus:2.4.2-debian-12-r1 that the helm chart bitnami/milvus:7.0.5 used supports to config kafka tls client certs to connect kafka server running with tls
https://github.com/milvus-io/milvus/blob/c6e2dd05fc89bbb4a6d9a851eddc9ceea7494abf/configs/milvus.yaml#L141
![image](https://github.com/bitnami/charts/assets/45187622/a1a2eae7-4470-4582-b543-b1fe8d3a6bfd)
but now the bitnami/milvus helm chart cannot config externalKafka with tls certs
https://github.com/bitnami/charts/blob/bf03e1d210f3a2a2a13586014a5afd6756cc4b0a/bitnami/milvus/values.yaml#L5295

### What is the feature you are proposing to solve the problem?
enabled to config externalKafka tls certs
would like to commit a PR to solve this problem just like
https://github.com/bitnami/charts/pull/20498

### What alternatives have you considered?

we should enable milvus to connect externa kafka server running with tls with kafka client certs

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
