### ISSUE TITLE
[bitnami/milvus] configure externalS3 tls settings

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#26111]
### Name and Version

bitnami/milvus 7.0.5

### What is the problem this feature will solve?

now the image docker.io/bitnami/milvus:2.4.2-debian-12-r1 that the helm chart bitnami/milvus:7.0.5 used supports to config mino tls client certs to connect minio server running with tls
https://github.com/milvus-io/milvus/blob/c6e2dd05fc89bbb4a6d9a851eddc9ceea7494abf/configs/milvus.yaml#L81
![image](https://github.com/bitnami/charts/assets/45187622/7e1f1713-b1c7-428d-9ec4-acac3d7cbcd5)
but now the bitnami/milvus helm chart cannot config externalS3 with tls certs
https://github.com/bitnami/charts/blob/bf03e1d210f3a2a2a13586014a5afd6756cc4b0a/bitnami/milvus/values.yaml#L5279C1-L5279C11

### What is the feature you are proposing to solve the problem?

enbaled to config externalS3 tls certs
would like to commit a PR to solve this problem just like config etcd client tls certs
https://github.com/bitnami/charts/pull/20498

### What alternatives have you considered?

we should enable milvus to connect external minio server running with tls with minio client certs

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team, but as it is not a critical feature, we cannot guarantee an ETA. If you would like to contribute to a PR the team will review it, speeding up the process.

**Comment by chenraoCR** [comment]
> Hi!
> 
> Thank you so much for the feature request. I will forward it to the team, but as it is not a critical feature, we cannot guarantee an ETA. If you would like to contribute to a PR the team will review it, speeding up the process.

as the PR #26118 just merged, now will work on this feature

**Comment by chenraoCR** [comment]
@javsalgar Hi, i just commit a PR for this feature, so could you reopen it

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look

**Comment by chenraoCR** [comment]
> Hi!
> 
> Thank you so much for the PR! The team will take a look

hello, i have committed the PR https://github.com/bitnami/charts/pull/27068 for quite a long time, so how about the result?
