### ISSUE TITLE
Typo in wordpress deployment.yaml

### ISSUE THREAD

**Issue by detscorn** [bitnami/charts#26133]
### Name and Version

bitnami/wordpress 22.2.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

There is a typo in deployment.yaml line 326.  "apcahe-tmp-dir"

### What do you see instead?

typo

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
