### ISSUE TITLE
[harbor] Support Harbor 2.0

### ISSUE THREAD

**Issue by Djiit** [bitnami/charts#2614]
**Which chart**: 
bitnami/harbor

**Is your feature request related to a problem? Please describe.**
Nah. Just want to track the support of Harbor 2.0 in this helm chart.

**Describe the solution you'd like**
Harbor 2.0 is out, and eventually this chart should support it (blog post : https://goharbor.io/blog/harbor-2.0/).

**Describe alternatives you've considered**

**Additional context**
Tracked here in the official Helm chart : https://github.com/goharbor/harbor-helm/issues/584

**Comment by andresbono** [comment]
Thanks for showing interests, @Djiit! We will post a message here when we have any news.

**Comment by andresbono** [comment]
Hi @Djiit, we have released a new version of the chart: `6.0.1` that is using Harbor 2: https://github.com/bitnami/charts/tree/master/bitnami/harbor. Hope you find it useful!
