### ISSUE TITLE
[wordpress] allow for custom serviceName and servicePort

### ISSUE THREAD

**Issue by katsika** [bitnami/charts#2619]
**Which chart**:
bitnami/wordpress

**Is your feature request related to a problem? Please describe.**
Both `serviceName` and `servicePort` are hardcoded in [ingress.yaml](https://github.com/bitnami/charts/blob/c7751eb5764e468e1854b58a1b8491d2b13e0a4a/bitnami/wordpress/templates/ingress.yaml#L25-L33). It makes it impossible to create more sophisticated rules, for example for AWS ALB. 

**Describe the solution you'd like**
Provide additional parameters to override default values:
`ingress.extraHosts[0].serviceName` and `ingress.extraHosts[0].servicePort`
```diff
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
-             serviceName: {{ template "wordpress.fullname" $ }}
+             serviceName: {{ if .serviceName }}{{ .serviceName }}{{ else }}{{ template "wordpress.fullname" $ }}{{ end }}
-             servicePort: {{ default "http" .servicePort }}
+             servicePort: http
    {{- end }}
```

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback! That should be easy to implement. As it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, feel free to submit a PR and we will review it. 

Also, could you provide more details about the ALB use case? It would be quite helpful for us

**Comment by katsika** [comment]
@javsalgar thanks, I'll see if I can get a PR together.

One use case (which also requires reordering `paths`, complicating things further) is [ssl redirect](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/).

Perhaps hardcoded `- path: /` path should become configurable too.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback! Let us know when you have the PR :)

**Comment by javsalgar** [comment]
Hi @katsika were you able to work on this?
