### ISSUE TITLE
[NATS] -  Websocket support

### ISSUE THREAD

**Issue by Sofka-XT** [bitnami/charts#2624]
**Which chart**:
bitnami/nats

**Is your feature request related to a problem? Please describe.**
I am interested in websocket support  for browsers

**Comment by rafariossaa** [comment]
Hi @Sofka-XT,
  Could you provide more context/background for that use case ?

**Comment by Sofka-XT** [comment]
NATS has websocket support, you should have an option to enable this feature.

**Comment by beltran-rubo** [comment]
Hi @Sofka-XT did you already try the current configuration? Not sure if you are looking for the 'client' side for connecting to NATS https://github.com/isobit/websocket-nats Could you post if you got any error?
