### ISSUE TITLE
broken pr links in changelog

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#26329]
### Name and Version

All

### What architecture are you using?

None

### What steps will reproduce the bug?

1. see https://github.com/bitnami/charts/blob/e37834c831892cc130160cedbf4826a892b31292/bitnami/prometheus/CHANGELOG.md?plain=1#L5
2. open the pr link

### Are you using any custom parameters or values?

unrelated

### What is the expected behavior?

have working pr links

### What do you see instead?

wrong link, `pulls` vs `pull`

<https://github.com/bitnami/charts/pulls/25902> needs to be <https://github.com/bitnami/charts/pull/25902>

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. The PR above should fix the issue.
