### ISSUE TITLE
Grafana chart can't set a DB as repository

### ISSUE THREAD

**Issue by Stephane-Thales** [bitnami/charts#2635]
**Which chart**: grafana

**Describe the bug**

while trying to set a postgres DB as repository i tried to create a secret (or a configmap) for custom.ini file
--set config.useCustomIniFile=true
--set config.customIniSecret=my-grafana-config-secret
(alternatively --set config.customIniConfigMap=my-grafana-config)
The file is mounted but as a directory and is not applied
==> that's my main issue

after that I tried other options but the lack of documentation did not help :
- replacing the grafana.ini using config.useGrafanaIniFile and config.grafanaIniSecret or config.grafanaIniConfigMap => error trying to mount a folder as a file (as the file already exist and the mount is trying to create a folder as above)
- using Env variableusing --set extraEnvVars here it's not explained if we need to pass host env variable names or the container new env name and values, and in which format that need to be writen as --set => any exemple please ?

**To Reproduce**

1. create the secret

`cat > my-grafana-config.ini`

with

```
[database]
type=postgres
host=mypostgres-stolon-proxy:5432
user=yourmaster
password=Xxx
```

create the secret

`kubectl create secret generic -n tuto07 my-grafana-config-secret --from-file=my-grafana-config.ini`

2. create the helm

```
helm install --namespace tuto07 \
--set persistence.enabled=false \
--set replicaCount= \
--set config.useCustomIniFile=true \
--set config.customIniSecret=my-grafana-config-secret \
--set plugins="vertamedia-clickhouse-datasource\,grafana-kubernetes-app" \
mygrafana bitnami/grafana
```

3. check 

```
kubectl exec -n tuto07 mygrafana-7b4bcdfccc-z52gd -it  --  /bin/sh
cd /opt/bitnami/grafana/conf
cat custom.ini

```
result
`cat: custom.ini: Is a directory`
and it's empty

**Expected behavior**

the custom.ini is a file, and grafana is connected to the postgres server and created the grafana database

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Alternate issue**

Can't set the env variables.
What is the syntax ?
I tried multiple variation of the following with { or [ and-or " , = or : 
none worked

`--set extraEnvVars={GF_DATABASE_TYPE:postgres\,GF_DATABASE_HOST:mypostgres-stolon-proxy\:5432\,GF_DATABASE_USER:yourmaster\,GF_DATABASE_PASSWORD:Xxx} \`

**Comment by joancafom** [comment]
Hi @Stephane-Thales ,

When mounting a custom file, the [name](https://github.com/bitnami/charts/tree/master/bitnami/grafana#using-custom-configuration) specified in the documentation should be preserved so as to make the pod correctly retrieve from the secret/configmap. In your case, `my-grafana-config.ini` should be renamed to `custom.ini`.

Let me guide you through your specific case:
```console
$ cat custom.ini                                                                                                                                                      
[database]
type=postgres
host=mypostgres-stolon-proxy:5432
user=yourmaster
password=Xxx
```

```console
$ kubectl create secret generic my-grafana-config-secret --from-file=custom.ini
secret/my-grafana-config-secret created

$ kubectl describe secret my-grafana-config-secret                                                                                                                    
Name:         my-grafana-config-secret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
custom.ini:  88 bytes
```

Install and check:

```console
$ helm install --set config.useCustomIniFile=true --set config.customIniSecret=my-grafana-config-secret mygrafana bitnami/grafana

$ kubectl exec mygrafana-6fcd44d5f6-647sx -- cat conf/custom.ini                                                                                                    
[database]
type=postgres
host=mypostgres-stolon-proxy:5432
user=yourmaster
password=Xxx
```
Regarding your question on the `extraEnvVars`, I think the most convenient way of modifying properties on a deployment (not only for this specific parameter) is to directly change the `values.yml` to suit your needs. Would that work for you?

Thanks!

**Comment by Stephane-Thales** [comment]
Thanks, that help.
for the extraEnvVars, indeed it look like it will be easier with a value.xml than with a --set.

**Comment by joancafom** [comment]
Glad to help! Thanks 😁

**Comment by QuanTran91** [comment]
Hi @Stephane-Thales 
Might I know did you set the db as repository via extraEnvVars?
Thank you.

**Comment by Stephane-Thales** [comment]
> Hi @Stephane-Thales Might I know did you set the db as repository via extraEnvVars? Thank you.

Hi it was a long time ago, If I remember correctly I was not able to do it using helm, and used only the kubectl and yml.

**Comment by QuanTran91** [comment]
Nevermind, I figure out
  grafana:
    extraEnvVars:
    - name: GF_DATABASE_TYPE
      value: postgres
    - name: GF_DATABASE_HOST
      value: <database endpoint>
    - name: GF_DATABASE_NAME
      value: grafana
    - name: GF_DATABASE_USER
      value: grafanauser
    - name: GF_DATABASE_PASSWORD
      value: <password>
    - name: GF_DATABASE_SSL_MODE
      value: disable
