### ISSUE TITLE
[prometheus-operator] Add Provision for Alertmanager Templates

### ISSUE THREAD

**Issue by Nuru** [bitnami/charts#2636]
**Which chart**:
bitnami/prometheus-operator chart version 0.17.1

**Is your feature request related to a problem? Please describe.**

The [stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) chart provides a way to supply Alertmanager templates and have them [included in the Alertmanager secret](https://github.com/helm/charts/blob/d6973a495463725d1a2ac67d56f0f834753e0eb6/stable/prometheus-operator/templates/alertmanager/secret.yaml#L20-L22) as decribed [here](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#alerting). The bitnami chart does not, and without that, there is no convenient way to supply Alertmanager templates. 

**Describe the solution you'd like**

Provide feature parity with stable/prometheus-operator

<details><summary>Possible patch</summary>

```diff
diff --git a/bitnami/prometheus-operator/templates/alertmanager/secrets.yaml b/bitnami/prometheus-operator/templates/alertmanager/secrets.yaml
index 8ccdb1e3..fcd685aa 100644
--- a/bitnami/prometheus-operator/templates/alertmanager/secrets.yaml
+++ b/bitnami/prometheus-operator/templates/alertmanager/secrets.yaml
@@ -6,4 +6,7 @@ metadata:
   labels: {{- include "prometheus-operator.alertmanager.labels" . | nindent 4 }}
 data:
   alertmanager.yaml: {{ toYaml .Values.alertmanager.config | b64enc | quote }}
+{{- range $key, $val := .Values.alertmanager.templateFiles }}
+  {{ $key }}: {{ $val | b64enc | quote }}
+{{- end }}
 {{- end }}
```
</details>

**Describe alternatives you've considered**

I considered using `alertmanager.configMaps` but there is no example or description of how to use it (is it just a list of names of configMaps? where do they get mounted?) and I do not want to have to separately create a configMap.

**Comment by javsalgar** [comment]
Hi,

From https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md:

> ConfigMaps is a list of ConfigMaps in the same namespace as the Alertmanager object, which shall be mounted into the Alertmanager Pods. The ConfigMaps are mounted into /etc/alertmanager/configmaps/.


Would that work for your case?
