### ISSUE TITLE
[bitnami/kube-prometheus] Support for keepDroppedTargets in kube-prometheus helm-chart

### ISSUE THREAD

**Issue by p53** [bitnami/charts#26365]
### Name and Version

bitnami/kube-prometheus:9.2.1

### What is the problem this feature will solve?

need to be able to set prometheus global options

### What is the feature you are proposing to solve the problem?

either add additional global parameter keepDroppedTargets or add possibility to add any additional global configuration

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the team but as it is not a critical feature I cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.

**Comment by p53** [comment]
Not stale
