### ISSUE TITLE
[prometheus-operator] Allow setting externalUrl

### ISSUE THREAD

**Issue by Nuru** [bitnami/charts#2637]
**Which chart**:
bitnami/prometheus-operator chart version 0.17.1

**Is your feature request related to a problem? Please describe.**

Prometheus and Alertmanager [must be configured](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/exposing-prometheus-and-alertmanager.md#kubernetes-api) with the full URL at which they will be exposed.
The [stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) chart provides a way to set `externalUrl` for [Prometheus](https://github.com/helm/charts/blob/d6973a495463725d1a2ac67d56f0f834753e0eb6/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L52-L58) and [Alertmanager](https://github.com/helm/charts/blob/d6973a495463725d1a2ac67d56f0f834753e0eb6/stable/prometheus-operator/templates/alertmanager/alertmanager.yaml#L18-L24). The bitnami chart does not, and without that, there is no way to deploy Prometheus and Alertmanager behind a custom Ingress. 

**Describe the solution you'd like**

Provide feature parity with stable/prometheus-operator

<details><summary>Possible patch</summary>

```diff
diff --git a/bitnami/prometheus-operator/templates/alertmanager/alertmanager.yaml b/bitnami/prometheus-operator/templates/alertmanager/alertmanager.yaml
index 7cd13b19..13350eea 100644
--- a/bitnami/prometheus-operator/templates/alertmanager/alertmanager.yaml
+++ b/bitnami/prometheus-operator/templates/alertmanager/alertmanager.yaml
@@ -11,7 +11,9 @@ spec:
   image: {{ template "prometheus-operator.alertmanager.image" . }}
   {{- end }}
   listenLocal: {{ .Values.alertmanager.listenLocal }}
-  {{- if and .Values.alertmanager.ingress.enabled .Values.alertmanager.ingress.hosts }}
+  {{- if .Values.alertmanager.externalUrl }}
+  externalUrl: "{{ .Values.alertmanager.externalUrl }}"
+  {{- else if and .Values.alertmanager.ingress.enabled .Values.alertmanager.ingress.hosts }}
   externalUrl: {{ if .Values.alertmanager.ingress.tls }}https{{else}}http{{ end }}://{{ (index .Values.alertmanager.ingress.hosts 0).name }}/
   {{- else }}
   externalUrl: http://{{ template "prometheus-operator.alertmanager.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.alertmanager.service.port }}
diff --git a/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml b/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml
index 1afc5885..5bd68ec4 100644
--- a/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml
+++ b/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml
@@ -40,7 +40,9 @@ spec:
   {{- else if .Values.prometheus.replicaExternalLabelName }}
   replicaExternalLabelName: "{{ .Values.prometheus.replicaExternalLabelName }}"
   {{- end }}
-  {{- if and .Values.prometheus.ingress.enabled .Values.prometheus.ingress.hosts }}
+  {{- if .Values.prometheus.externalUrl }}
+  externalUrl: "{{ .Values.prometheus.externalUrl }}"
+  {{- else if and .Values.prometheus.ingress.enabled .Values.prometheus.ingress.hosts }}
   externalUrl: {{ if .Values.prometheus.ingress.tls }}https{{else}}http{{ end }}://{{ (index .Values.prometheus.ingress.hosts 0).name }}/
   {{- else }}
   externalUrl: http://{{ template "prometheus-operator.prometheus.fullname" . }}.{{ .Release.Namespace }}:9090
```
</details>

**Comment by juan131** [comment]
Hi @Nuru , 

This comes from the [stable/prometheus-operator](https://github.com/helm/charts/blob/402a220fe1ef7ff83a80e84005e2edf0dcf8f73c/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L52)

```
{{- if .Values.prometheus.prometheusSpec.externalUrl }}
  externalUrl: "{{ .Values.prometheus.prometheusSpec.externalUrl }}"
{{- else if and .Values.prometheus.ingress.enabled .Values.prometheus.ingress.hosts }}
  externalUrl: "http://{{ index .Values.prometheus.ingress.hosts 0 }}{{ .Values.prometheus.prometheusSpec.routePrefix }}"
{{- else }}
  externalUrl: http://{{ template "prometheus-operator.fullname" . }}-prometheus.{{ $.Release.Namespace }}:{{ .Values.prometheus.service.port }}
{{- end }}
```

This is the equivalent part in the Bitnami chart:

```
  {{- if and .Values.prometheus.ingress.enabled .Values.prometheus.ingress.hosts }}
  externalUrl: {{ if .Values.prometheus.ingress.tls }}https{{else}}http{{ end }}://{{ (index .Values.prometheus.ingress.hosts 0).name }}/
  {{- else }}
  externalUrl: http://{{ template "prometheus-operator.prometheus.fullname" . }}.{{ .Release.Namespace }}:9090
  {{- end }}
```

As you said, we don't have any equivalent to the `prometheus.prometheusSpec.externalUrl` parameter. 

That said, you should be able to expose Prometheus behind an Ingress using `prometheus.ingress.XXX` parameters. Could you please detail the use case where that's not enough?

**Comment by Nuru** [comment]
@juan131 Use case is making Prometheus available on the public internet but protected by an authenticating proxy that is not Kubernetes aware and therefore does not, itself, implement Ingress. So `prometheus.ingress.enabled: false` but `externalUrl: https://prometheus.example.com`

I will have a PR for you soon that takes care of this, #2636, and some other stuff.

**Comment by Nuru** [comment]
@juan131 See #2650 for implementation

**Comment by juan131** [comment]
Thanks! I just took a 1st look to your PR
