### ISSUE TITLE
[bitnami/valkey] global.valkey.password does not override auth.password

### ISSUE THREAD

**Issue by mkyc** [bitnami/charts#26372]
### Name and Version

bitnami/valkey:0.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

install using values file and test CM content

### Are you using any custom parameters or values?

```
global:
  valkey:
    password: "password"

architecture: standalone

master:
  resources:
    requests:
      cpu: 300m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 50Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

image:
  debug: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

I'd expect that `$VALKEY_PASSWORD` is `password`. 

### What do you see instead?

random string. 

### Additional information

If you make it: 

```
global:
  valkey:
    password: "password"

architecture: standalone

auth:
  password: "password"

master:
  resources:
    requests:
      cpu: 300m
      memory: 50Mi
    limits:
      cpu: 300m
      memory: 50Mi
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

image:
  debug: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

value is `password` as expected.

**Comment by juan131** [comment]
Thanks for reporting the issue @mkyc !! I just created a PR to address it.
