### ISSUE TITLE
[bitnami/solr] Increase the expiration of self-signed certificate generated

### ISSUE THREAD

**Issue by eroji** [bitnami/charts#26390]
### Name and Version

bitnami/solr

### What is the problem this feature will solve?

The default duration of the CA and server cert generated by Solr chart when `tls.enabled` is set to true is 365 days. This is awfully short and could be a ticking time bomb. Is it possible for you to override this value without changing the template file altogether?

### What is the feature you are proposing to solve the problem?

Perhaps allow the duration of the cert be a override argument.

### What alternatives have you considered?

The alternative would be to provide your own certs

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. In principle, the autogenerated certs are not recommended for production workloads. but I will forward this to the engineering team. As this is not a critical feature, we cannot guarantee an ETA, however, you can speed up the process by submitting a PR adding a value for the number of days
