### ISSUE TITLE
[bitnami/argo-cd] argo-cd-notifications liveness problem

### ISSUE THREAD

**Issue by ktzsolt** [bitnami/charts#26405]
### Name and Version

bitnami/argo-cd 6.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
$ helm upgrade --install argocd oci://registry-1.docker.io/bitnamicharts/argo-cd --version 6.3.2 --set notifications.enabled=true

```

with 6.3.1 there is no such problem.
The commit that introduced the bug: https://github.com/bitnami/charts/pull/26367/commits/49bbe1c61a49930ad8d3a666b91e39bdabc122d8

### Are you using any custom parameters or values?

--set notifications.enabled=true

### What is the expected behavior?

helm install succeeds with notifications enabled

### What do you see instead?

```
Pulled: registry-1.docker.io/bitnamicharts/argo-cd:6.3.2
Digest: sha256:582f84b7c8df0d06eb59f1375381bb7f11ed201fe1b1ca470b668268be9596d4
W0524 13:05:27.567182   38296 warnings.go:70] unknown field "spec.template.spec.containers[0].livenessProbe.tcpSocket.path"
Error: UPGRADE FAILED: failed to create resource: Deployment.apps "argocd-argo-cd-notifications" is invalid: spec.template.spec.containers[0].livenessProbe.tcpSocket.port: Invalid value: 0: must be between 1 and 65535, inclusive
```

**Comment by dgomezleon** [comment]
Thanks for notifying me. I've just sent a PR fixing the issue.
