### ISSUE TITLE
[new chart - cilium CNI] add new chart for cilium

### ISSUE THREAD

**Issue by w0aw** [bitnami/charts#26443]
### Name and Version

new chart - cilium

### What is the problem this feature will solve?

it will add an cilium helm chart.

### What is the feature you are proposing to solve the problem?

bitnami already have cilium based container images. 

thank you

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our team is actively working on this at the moment. We will provide updates on this thread as soon as the new version is successfully released.
