### ISSUE TITLE
[bitnami/mongodb] Configmap common-scripts broken

### ISSUE THREAD

**Issue by rrileyca** [bitnami/charts#26464]
### Name and Version

bitnami/mongodb 15.4.4

### What architecture are you using?

None

### What steps will reproduce the bug?

The common-scripts ConfigMap is broken by this commit:  https://github.com/bitnami/charts/commit/8d26cb1c0b9c5d8e08bcd9bd53a0dc142536e00f#diff-8e7a2940c656b0df7a24e56520021ed30861800305043065f521076e8f8b6e45

Notice on line 22, a space was removed. Now it reads:
```shell
TLS_OPTIONS='--tls {{ if .Values.tls.mTLS.enabled }}--tlsCertificateKeyFile=/certs/mongodb.pem {{ end }}--tlsCAFile=/certs/mongodb-ca-cert--tlsAllowInvalidHostnames'
```

which is missing a space between `tlsCAFile=/certs/mongodb-ca-cert` and `--tlsAllowInvalidHostnames`

### What do you see instead?

The error:

```
Error: ENOENT: no such file or directory, open '/certs/mongodb-ca-cert--tlsAllowInvalidHostnames'
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! As you spotted the issue, would you like to submit a PR fixing the space?
