### ISSUE TITLE
[bitnami/ghost] In latest version of ghost, it can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock

### ISSUE THREAD

**Issue by chary1112004** [bitnami/charts#26468]
### Name and Version

bitnami/ghost 21.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,

We are trying to deploy ghost and ghost is using mysql as database however mysql pod could not be up

Command to install ghost latest version
```
helm install my-ghost bitnami/ghost --version 21.0.1
```

this error shows when I describe pod
```
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!
```

And if I go inside container then there is no such this file
```
$ kubectl exec -it --namespace=cms-ghost ghost-mysql-0 -- bash
Defaulted container "mysql" out of: mysql, preserve-logs-symlinks (init)
I have no name!@ghost-mysql-0:/$ ls -la /opt/bitnami/mysql/tmp/mysql.sock
ls: cannot access '/opt/bitnami/mysql/tmp/mysql.sock': No such file or directory
```

I have tried to follow suggestion to increase startup probe however it does not work.

Any suggestion to resolve this issue would be very much appreciated!

Thanks!

### What do you see instead?

It is in reproduce step

**Comment by javsalgar** [comment]
Hi!

This could be a transient error. Could you check if both pods are shown as ready when running kubectl get pods?

**Comment by chary1112004** [comment]
Hi @javsalgar ,

The mysql pod could not be up and it is keeping restart. Mysql pod will disappear after amount of time.

$ helm install my-ghost bitnami/ghost --version 21.0.1
Error: release ghost failed, and has been uninstalled due to atomic being set: client rate limiter Wait returned an error: context deadline exceeded

**Comment by javsalgar** [comment]
Could you run kubectl describe pod to see what is causing the restart?

**Comment by JimTim** [comment]
Ok,
at first I found a workaround, add this to your helm chart custom values:
```yaml
#...
mysql:
  enabled: true
#...
  auth:
#...
    authenticationPolicy: "mysql_native_password"
  primary:
    configuration: |-
        [mysqld]
        authentication_policy='{{- .Values.auth.authenticationPolicy | default "* ,," }}'
        mysql_native_password=ON
        skip-name-resolve
        explicit_defaults_for_timestamp
        basedir=/opt/bitnami/mysql
        plugin_dir=/opt/bitnami/mysql/lib/plugin
        port={{ .Values.primary.containerPorts.mysql }}
        mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
        mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
        socket=/opt/bitnami/mysql/tmp/mysql.sock
        datadir=/bitnami/mysql/data
        tmpdir=/opt/bitnami/mysql/tmp
        max_allowed_packet=16M
        bind-address=*
        pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
        log-error=/opt/bitnami/mysql/logs/mysqld.log
        character-set-server=UTF8
        slow_query_log=0
        long_query_time=10.0

        [client]
        port={{ .Values.primary.containerPorts.mysql }}
        socket=/opt/bitnami/mysql/tmp/mysql.sock
        default-character-set=UTF8
        plugin_dir=/opt/bitnami/mysql/lib/plugin

        [manager]
        port={{ .Values.primary.containerPorts.mysql }}
        socket=/opt/bitnami/mysql/tmp/mysql.sock
        pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    persistence:
#...
```

**What does that do?**
It resets the authentication_policy back to `mysql_native_password`. To do this, we must then set an additional option in mysql.conf, `mysql_native_password=ON`. Therefore, the default config was overwritten with all its default options and this value was added.

**Why did this happen?**
The latest Ghost Helm version also uses a new MySQL chart version from Bitnami, where a breaking change regarding authentication has been introduced. Or rather, a long announced deprecation was removed. 

[Source](https://artifacthub.io/packages/helm/bitnami/mysql#to-11-0-0)

> This major bump uses mysql 8.4 image, that includes several  configuration settings, for example the parameter auth.defaultAuthenticationPlugin has been removed in favor of auth.authenticationPolicy. This could potentially break your deployment and you would need to adjust the config settings accordingly.

Related notes in the deprecation removal in mysql: https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html#mysqld-8-4-0-deprecation-removal

---
**And what happens now?**

With the above options, the mysql pod will start again and so will Ghost. At this point you should make a backup of your posts at the latest. From this point onwards, you can upgrade to the new authentication method. Follow this guide: https://dnsmichi.at/2024/05/11/docker-compose-ghost-msql-8-4-msql-native-password-startup-errors-mitigation-solution/#how-to-migrate-to-cachingsha2password

I am currently trying this out and will then update this comment with the specific commands.

**Comment by javsalgar** [comment]
Thank you so much for the information. The community will benefit from this! Would you like to add this information to the README.md file?

**Comment by chary1112004** [comment]
@JimTim thank you for the information. I had to do another work around by deploying external database and point to the external database.
