### ISSUE TITLE
[bitnami/mlflow] raises image warning without changing image

### ISSUE THREAD

**Issue by dhrp** [bitnami/charts#26471]
### Name and Version

bitnami/mlflow 1.2.0

### What architecture are you using?

amd64

## Install the mlflow helm chart
1. get the dependencies: `helm dependency build`
2. install the chart `helm upgrade --install mlflow -f values.yaml .`
3. Notice the Notes give the following warning:
    > ⚠ SECURITY WARNING: Original containers have been substituted. This Helm chart was designed, tested, and validated on multiple platforms using a specific set of Bitnami and Tanzu Application Catalog containers. Substituting other containers is likely to cause degraded security and performance, broken chart features, and missing environment variables.
   >
   > Substituted images detected:
   > `- %!s(<nil>)/:%!s(<nil>) `

### Are you using any custom parameters or values?

nope

### What is the expected behavior?

the warning is not raised

### What do you see instead?

this warning:
```
⚠ SECURITY WARNING: Original containers have been substituted. This Helm chart was designed, tested, and validated on
multiple platforms using a specific set of Bitnami and Tanzu Application Catalog containers. Substituting other containers is 
likely to cause degraded security and performance, broken chart features, and missing environment variables.

Substituted images detected:
- %!s(<nil>)/:%!s(<nil>)
```

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
