### ISSUE TITLE
[nginx-ingress-controller] can't access nginx 404 default backend.

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#2648]
**Which chart**:
nginx-ingress-controller-5.3.19

**Describe the bug**
nginx-ingress-controller service external IP remains pending. I cannot reach the nginx default 404 backend.

**To Reproduce**
1. Create a values file for helm chart installation.
```
controller:
  nodeSelector:
    kubernetes.io/hostname: nlwymmd
  hostNetwork: True
  dnsPolicy: ClusterFirstWithHostNet
```
2. I install the helm chart
`helm install nginx-ingress-controller bitnami/nginx-ingress-controller -f nginx-ingress-values.yaml`

3. I check the running services. I find that the external ip is pending.
```
raphaelc@nlwymmd:~/orpheus_site_atlas/releases/external_charts$ kubectl get service
NAME                                       TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
kubernetes                                 ClusterIP      10.96.0.1        <none>        443/TCP                                 3d14h
nginx-ingress-controller                   LoadBalancer   10.97.29.12      <pending>     80:31334/TCP,443:30155/TCP              4m12s
nginx-ingress-controller-default-backend   ClusterIP      10.106.206.72    <none>        80/TCP                                  4m12s
```
4. I am VPN'd into my cluster subnet. I try to access the nginx default webpage, but my browser is unable to connect. I have tried both the DNS name and the IP address.

**Expected behavior**
I expected that when I try to visit my ip address or my dns name, I will see the 404 backend. Instead, I see that it's unable to connect.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I recently installed a new kubernetes cluster with the Calico CNI.

**Comment by andresbono** [comment]
Hi @raphaelcervantes, is you cluster able to create services of type `LoadBalancer`? In general, only major clouds can do so. For testing purposes, you can try to change the service type to `NodePort` or even `ClusterIP` (as you are setting `hostNetwork: True`). Add the following to your custom values:

```
service:
  type: NodePort
```

**Comment by raphaelcervantes** [comment]
@andresbono Thank you for the reply. I have a bare-metal setup, so my cluster probably can't create services of type LoadBalancer.

 I have added both 
```
service:
  type: NodePort 
```
and
```
service:
  type: ClusterIP
```

to my custom values, but I still can't access the 404 by visiting the cluster DNS. I am still learning how this works, so I will look up what NodePorts and ClusterIPs are, and I will try to see if I can access the 404 backend through a port-forward. But otherwise, I feel stuck.

Thank you.

**Comment by andresbono** [comment]
Hi @raphaelcervantes, if you use service.type `NodePort`, you will be able to access the service in the port specified in the service description:

```
$ kubectl get svc
NAME                                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kubernetes                                      ClusterIP   10.96.0.1       <none>        443/TCP                      12m
nic1-nginx-ingress-controller                   NodePort    10.96.200.219   <none>        80:32763/TCP,443:30980/TCP   9m
nic1-nginx-ingress-controller-default-backend   ClusterIP   10.96.159.21    <none>        80/TCP                       9m
```

In the example above, you will see `80:32763/TCP,443:30980/TCP`. This means that port `80` of nginx-ingress-controller is exposed in port `32763` in the node and port `443` in `30980`.

If you are not behind a firewall, you should be able to access them. If not, you can test it by ssh'ing to the node and doing:

```
curl 127.0.0.1:32763
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

---

I saw that you are trying to set `hostNetwork: True`. Please keep in mind that you need to set as a root element not under `controller`:

```
nodeSelector:
  kubernetes.io/hostname: nlwymmd

hostNetwork: True
dnsPolicy: ClusterFirstWithHostNet

service:
  type: NodePort
```

**Comment by raphaelcervantes** [comment]
> I saw that you are trying to set hostNetwork: True. Please keep in mind that you need to set as a root element not under controller:

This was actually my problem the entire time! I was adapting the custom values from another nginx-ingress-controller helm chart and didn't realize that controller shouldn't have been there. 

Thank you. It works for me with or without specifying `service.type = Nodeport.`

**Comment by andresbono** [comment]
Great! Thanks for confirming!
