### ISSUE TITLE
[bitnami/grafana-operator] Wrong content of grafanacontactpoints.integreatly.org.yaml

### ISSUE THREAD

**Issue by daleckystepan** [bitnami/charts#26499]
### Name and Version

grafana-operator:4.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just install it.

### Are you using any custom parameters or values?

yes, but does not matter

### What is the expected behavior?

Grafana operator does not crash regularly.

### What do you see instead?

Grafana operator does crash regularly.

```
2024-05-28T14:40:10.796711976Z 2024-05-28T14:40:10Z	ERROR	setup	problem running manager	{"error": "failed to wait for grafanacontactpoint caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.GrafanaContactPoint"}

```

### Additional information

https://github.com/bitnami/charts/blob/main/bitnami/grafana-operator/crds/grafanacontactpoints.integreatly.org.yaml has wrong content. It contains different resource GrafanaAlertRuleGroup instead of grafanacontactpoints.

**Comment by github-ashishkumar** [comment]
Also, the alertmanager specific json available from Grafana Alert export feature is showing up multiple fields, however, those are not available in the codebase causing error. I removed it to fix my pipeline but the question is more on if a specific panel
ID is using the alert then how it will sync up after running the grafana operator.

![Alert_Export](https://github.com/bitnami/charts/assets/170959011/a63ae14d-5d52-4691-b8ef-6187ab477f22)

**Comment by ashmere** [comment]
PR https://github.com/bitnami/charts/pull/25517 originally fixed this issue but PR https://github.com/bitnami/charts/pull/26440 looks to have overwritten them, causing the current issue

**Comment by jotamartos** [comment]
Thanks for taking the time to report this issue. I just send a PR to update this and will merge it once tests pass
