### ISSUE TITLE
Thanos Sharding Cache Issue

### ISSUE THREAD

**Issue by Lukiido** [bitnami/charts#26503]
### Name and Version

bitnami/thanos 15.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

If you enable sharding and have an indexcacheconfig or bucketcacheconfig set the storegateway shards do not come up, they crashloop with an error saying the file cannot be found. Wondering if the sts yaml for the shards needs to be updated possibly? 

### Are you using any custom parameters or values?

```yaml
indexCacheConfig: |
type: IN-MEMORY
config:
max_size: 512MB
max_item_size: 125MB
```

### What is the expected behavior?

The sharded storegateway is to come up. 

### What do you see instead?

This error:

```
{"caller":"main.go:145","err":"open /conf/cache/index-cache.yml: no such file or directory
loading file /conf/cache/index-cache.yml for index-cache.config-file\http:/
github.com/efficientgo/tools/extkingpin.(*PathOrContent).Content
    /bitnami/blacksmith-sandox/thanos-0.35.0/pkg/mod/github.com/efficientgo/tools/extkingpin@v0.0.0-20220817170617-6c25e3b627dd/pathorcontent.go:79
main.runStore
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/store.go:341
main.registerStore.func1
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/store.go:250
main.main
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/main.go:143
runtime.main
    /opt/bitnami/go/src/runtime/proc.go:267
runtime.goexit
    /opt/bitnami/go/src/runtime/asm_amd64.s:1650
get content of index cache configuration
main.runStore
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/store.go:343
main.registerStore.func1
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/store.go:250
main.main
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/main.go:143
runtime.main
    /opt/bitnami/go/src/runtime/proc.go:267
runtime.goexit
    /opt/bitnami/go/src/runtime/asm_amd64.s:1650
preparing store command failed
main.main
    /bitnami/blacksmith-sandox/thanos-0.35.0/src/github.com/thanos-io/thanos/cmd/thanos/main.go:145
runtime.main
    /opt/bitnami/go/src/runtime/proc.go:267
runtime.goexit
    /opt/bitnami/go/src/runtime/asm_amd64.s:1650","level":"error","ts":"2024-05-24T14:22:52.795611102Z"}
```

**Comment by fmulero** [comment]
Hi @Lukiido, thanks for using Bitnami charts.

I am trying to reproduce your issue but I didn't have luck. Are you sure that you are using the right indentation?:

```yaml
indexCacheConfig: |
  type: IN-MEMORY
  config:
  max_size: 512MB
  max_item_size: 125MB
```

Could you share concrete steps to reproduce it? Please include the whole `values.yaml` file?

**Comment by Lukiido** [comment]
Hey sure thing!

Basically this issue only occurs when using this values.yaml file and sharding is enabled. If we disable sharding then the storegateway will come up without issue. 

`thanos:
  indexCacheConfig: |
    type: IN-MEMORY
    config:
      max_size: 512MB
      max_item_size: 125MB
  bucketCacheConfig: |
    type: MEMCACHED
    config:
      addresses:[1.1.1.1]
      timeout: 500ms
      max_idle_connections: 100
      dns_provider_update_interval: 10m

  serviceAccount:
    create: false
    name: "stage-prometheus"

  compactor:
    enabled: true
    logLevel: error
    consistencyDelay: 30m
    extraFlags:
      - --delete-delay=1h
      - --bucket-web-label=replica
      - |
        --selector.relabel-config=
          - action: keep
            source_labels: ["replica"]
            regex: ".*stage.*"
    resources:
      requests:
        cpu: 2000m
        memory: 16Gi
      limits:
        memory: 16Gi
    persistence:
      enabled: true
      storageClass: "thanos-storage"
      size: 120Gi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  query:
    enabled: true
    replicaCount: 3
    pdb:
      create: true
      minAvailable: 1
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        memory: 2Gi
    extraFlags:
      - --query.timeout=5m
      - --query.auto-downsampling
      - --no-query.partial-response
      - --endpoint.info-timeout=60s
      - --store.unhealthy-timeout=5m
      - --store.response-timeout=5m
    replicaLabel:
      - prometheus_replica

  storegateway:
    enabled: true
    resources:
      requests:
        cpu: 4000m
        memory: 16Gi
      limits:
        memory: 16Gi
    persistence:
      storageClass: "storage"
      size:  64Gi
    logLevel: error
    extraFlags:
      - --ignore-deletion-marks-delay=6h
      - --chunk-pool-size=2GB

    sharded:
      enabled: true
      hashPartitioning:
        shards: "3"
      timePartitioning:
        - min: -30d
          store.grpc.series-sample-limit: "50000000"
        - min: -90d
          max: -30d
          store.grpc.series-sample-limit: "50000000"
        - max: -90d
          store.grpc.series-sample-limit: "50000000"`

**Comment by sgreben** [comment]
@Lukiido This looks a lot like the issue addressed by my two PRs here (#26490 (buggy fix) and #27101 (fixing the buggy fix)). When v15.7.6 is released this should just work again..

**Comment by sgreben** [comment]
oh right, note that you'll need to use `storegateway.config` instead of the toplevel `indexCacheConfig` key to configure the index cache. Otherwise it tries to set the config files from both keys as the index cache config and the pods fail to start.

**Comment by Lukiido** [comment]
> oh right, note that you'll need to use `storegateway.config` instead of the toplevel `indexCacheConfig` key to configure the index cache. Otherwise it tries to set the config files from both keys as the index cache config and the pods fail to start.

Oh thank you! do you happen to have a link to the doc or an example, I must have missed it when I was digging through the chart.

**Comment by sgreben** [comment]
It's really just

```
storegateway:
  config: |
    type: IN-MEMORY
    config:
    max_size: 512MB
    max_item_size: 125MB
```

I don't think I saw this in the docs at all. Here's where I found out about this: <https://github.com/bitnami/charts/issues/24678#issuecomment-2042559131>

**Comment by sgreben** [comment]
The chart could really use another follow-up PR to deconflict indexCacheConfig and storegateway.config somehow. Tbh I'm really not sure what the point of additionally having `storegateway.config` is, given that it's passed to the index-cache config thanos CLI flag..

**Comment by Lukiido** [comment]
Thanks! How do I ensure that both bucket and index cache are loaded this way? Right now with sharding enabled and even just an index or bucket cache config called out I get the same error, can I place both under that storegateway.config? 

Ex:

`  indexCacheConfig: |
    type: IN-MEMORY
    config:
      max_size: 512MB
      max_item_size: 125MB
  bucketCacheConfig: |
    type: MEMCACHED
    config:
      addresses:[1.1.1.1]
      timeout: 500ms
      max_idle_connections: 100
      dns_provider_update_interval: 10m`
      
`storegateway:
  config: |
    type: IN-MEMORY
    config:
    max_size: 512MB
    max_item_size: 125MB
    type: MEMCACHED
    config:
      addresses:[1.1.1.1]
      timeout: 500ms
      max_idle_connections: 100
      dns_provider_update_interval: 10m  `

**Comment by Lukiido** [comment]
Hey, I removed my last comment after finding this issue [here](https://github.com/bitnami/charts/issues/25240) off of the link provided above. This seems to work to get the sharded gateways up! Thanks for the help!

I think one improvement would be to no need to do this and just define them earlier in the values like we would if it isnt sharded, or to add this to the documentation some place.

Thanks again!

**Comment by Lukiido** [comment]
Sorry, I did get these confused it does look like the issue I linked doesnt fix it for sharding it only fixes the statefulset.yaml. If I am wanting to define a bucketcache and indexcache for the shards how do I do that under the config spec using the example you provided @sgreben ?

Thanks again!

**Comment by Lukiido** [comment]
Hey, Just wanted to touch back on this issue to see if anyone is able to provide me with example config or some docs on how to set index and bucket cache within the storage-gateway shareded setting? Currently when trying to set both it indicates I have duplicate options and crashloops.

**Comment by nextrevision** [comment]
This is a little perplexing to me as well. I'm seeing the error `flag 'index-cache.config-file' cannot be repeated` when defining `indexCacheConfig` and `bucketCacheConfig` as top-level keys and using the sharded store gateway. I've had these settings since version `12.23.0` of the chart.

If I'm reading this correctly in [statefulset-sharded.yaml](https://github.com/bitnami/charts/blob/e6d16b4256f027adbb3610b4e66ee2c05039618f/bitnami/thanos/templates/storegateway/statefulset-sharded.yaml#L149):
```
            {{- if $.Values.indexCacheConfig }}
            - --index-cache.config-file=/conf/cache/index-cache.yml
            {{- end }}
            {{- if $.Values.bucketCacheConfig }}
            - --store.caching-bucket.config-file=/conf/cache/bucket-cache.yml
            {{- end }}
            {{- if or (include "thanos.storegateway.createConfigmap" $) $.Values.storegateway.existingConfigmap }}
            - --index-cache.config-file=/conf/cache/config.yml
            {{- end }}
```

[statefulset-sharded.yaml](https://github.com/bitnami/charts/blob/8384d96ba8b92128a2d262499f8b54f4541db2a4/bitnami/thanos/templates/_helpers.tpl#L321)
```
{{/*
Return true if a configmap object should be created
*/}}
{{- define "thanos.storegateway.createConfigmap" -}}
{{- if and (or .Values.storegateway.config .Values.indexCacheConfig .Values.bucketCacheConfig) (not .Values.storegateway.existingConfigmap) }}
    {{- true -}}
{{- else -}}
{{- end -}}
{{- end -}}

...

{{/*
Return the storegateway config
*/}}
{{- define "thanos.storegatewayConfigMap" -}}
{{- if .Values.storegateway.config }}
config.yml: |-
  {{- include "common.tplvalues.render" (dict "value" .Values.storegateway.config "context" $) | nindent 2 }}
{{- end }}
{{- if .Values.indexCacheConfig }}
index-cache.yml: |-
  {{- include "common.tplvalues.render" (dict "value" .Values.indexCacheConfig "context" $) | nindent 2 }}
{{- end }}
{{- if .Values.bucketCacheConfig }}
bucket-cache.yml: |-
  {{- include "common.tplvalues.render" (dict "value" .Values.bucketCacheConfig "context" $) | nindent 2 }}
{{- end }}
{{- end -}}
```

It seems impossible to set this correctly. Setting `.Values.indexCacheConfig` is required when setting `storegateway.config`, but it will always lead to the flag being set twice. Why does this need to be done twice and why do the cache configurations need to be tied to the existence of the `storegateway.config` setting? It seems to me that config, indexCacheConfig and bucketCacheConfig each need to exist as separate files. Why can't we manage them as separate configmaps with separate mount points? It looks like we need to choose one direction or the other unless I'm missing something obvious.

**Comment by nextrevision** [comment]
Using the chart as is, it looks like the fix is to move the contents of `indexCacheConfig` to `storegateway.config` and remove the `indexCacheConfig` key entirely. I can make a PR to add it to the upgrade notes for 15.x, but I'm not sure if I'm entirely confident in my understanding of the intent behind the `storegateway.config` key. At the bare minimum, I think the description should be updated if it is indeed only applicable to the index cache. If that is true, then I do think it should be renamed.
