### ISSUE TITLE
cp: cannot stat '/opt/bitnami/keycloak/lib/quarkus/*': No such file or directory

### ISSUE THREAD

**Issue by rajshivaram** [bitnami/charts#26520]
### Name and Version

bitnami/keycloak

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```Dockerfile
FROM quay.io/keycloak/keycloak:latest as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/
```

### What do you see instead?

Getting the following error while deploying custom image
```
cp: cannot stat '/opt/bitnami/keycloak/lib/quarkus/*': No such file or directory
```
### Additional information

Please help fix this, as I am unable to find any solution for this on the internet as well

**Comment by carrodher** [comment]
It seems you're not using the Bitnami Keycloak container image

**Comment by rajshivaram** [comment]
As per the documentation i am using the below container image

FROM quay.io/keycloak/keycloak:latest as builder

https://www.keycloak.org/server/containers

**Comment by carrodher** [comment]
That image is not from Bitnami, please post the question in the Keycloak forum.
