### ISSUE TITLE
[multus-cni] Add support for the thick plugin

### ISSUE THREAD

**Issue by luis-guimaraes-exoawk** [bitnami/charts#26543]
### Name and Version

bitnami/multus-cni

### What is the problem this feature will solve?

Currently the Helm chart for Multus CNI doesn't allow a simple deployment of the thick configuration of Multus CNI.
Since the thick configuration is now the one recommended, it should be supported by the chart.

### What is the feature you are proposing to solve the problem?

Adding a top level value `plugin` that can be set to `thin` or `thick`, being `thin` by default for backwards compatibility.

### What alternatives have you considered?

Using the official container image for Multus and re-writing the entire config for the thick version, but it's extremely time consuming

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
