### ISSUE TITLE
Many users reporting "error 400, request header too large"

### ISSUE THREAD

**Issue by MateoStr** [bitnami/charts#26554]
### Name and Version

bitnami wordpress 5.6.1-1

### What architecture are you using?

None

### What steps will reproduce the bug?

Some users visiting my wordpress site are greeted with a "Bad Request" error page, reading "Your browser sent a request that this server could not understand. Size of a request header field exceeds the server limit."

### Are you using any custom parameters or values?

not to my knowledge

### What is the expected behavior?

access to the wordpress site without issue

### What do you see instead?

for some users (typically but not limited to  users who have been around for a long time and have visited the site on a number of occasions), they are barred access due to this error

### Additional information

I have customized the file /opt/bitnami/apache2/include/httpd.h file

line 193: changed DEFAULT_LIMIT_REQUEST_LINE to 32768
line 197: changed DEFAULT_LIMIT_REQUEST_FIELDSIZE to 32768
line 201: changed DEFAULT_LIMIT_REQUEST_FIELDS to 200

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by MateoStr** [comment]
Is there a way I can validate or troubleshoot this on the server side? Such as a log of 400 errors?
