### ISSUE TITLE
No support for passwords in secrets

### ISSUE THREAD

**Issue by cculver** [bitnami/charts#26594]
### Name and Version

bitnami/matomo 7.3.0

### What is the problem this feature will solve?

I have reviewed the helm chart template for matomo and mariadb (embedded chart). It seems this chart was made only with those users that call 'helm install' in mind. I, on the other hand, am committing my chart values to a git repository and using argocd to manage my cluster's state. Unlike many other charts, there is no way to set the application password or the mariadb password through a secret (from this chart, not the bitnami mariadb chart, which ironically has a way to do this). I do not want, nor would it be best practice, to set a password in values.yaml files that would be clearly readable from source control.

### What is the feature you are proposing to solve the problem?

In an ideal chart, I would create a sealed secret with the application password and the mariadb password (or separately), commit that/those to source control, and the cluster would decrypt it/them, create the secret(s), and the chart would read passwords from that/those secret(s). Alternatively, one could create a secret on the cluster directly and have the chart read from it.

**Comment by fmulero** [comment]
Hi @cculver, thanks for using bitnami/charts.

I am trying to understand where is your issue but I don't have a clear idea. I tried to deploy the matomo chart without using helm install and storing the passwords in different secrets. These are the steps I followed:

```console
$ kubectl create secret generic test-mariadb --from-literal mariadb-password=salami --from-literal mariadb-root-password=sausage
secret/test-mariadb created
$ kubectl create secret generic test-matomo --from-literal matomo-password=salchichon
secret/test-matomo created
$ helm template test bitnami/matomo --set existingSecretest-matomo --set mariadb.auth.existingSecret=test-mariadb | kubectl apply -f -
networkpolicy.networking.k8s.io/test-mariadb created
networkpolicy.networking.k8s.io/test-matomo created
poddisruptionbudget.policy/test-matomo created
serviceaccount/test-mariadb created
configmap/test-mariadb created
persistentvolumeclaim/test-matomo-matomo created
service/test-mariadb created
service/test-matomo created
deployment.apps/test-matomo created
statefulset.apps/test-mariadb created
cronjob.batch/test-matomo-archive created
cronjob.batch/test-matomo-scheduled-tasks created
```

The pods started without issues and I could log into the web console with the credential stored in the `test-matomo` secret.  Could you share more details about your use case?

**Comment by cculver** [comment]
The issue is that I'm trying to do this within only the parent chart, matomo, which includes mariadb. It may not be documented that we can use secrets, or it may not be possible at all. But in the matomo chart, the only reference that I can see in the documentation or in the chart to a secret is for SMTP. Am I missing something? Thank you!

**Comment by cculver** [comment]
Thanks, I had multiple things going on including misconfiguration from a previous installation that made me think things weren't working. I wiped everything clean and started the deployment from scratch, erasing the PVC contents etc. Closing this issue.

**Comment by payxn** [comment]
Hello,

Sorry to reopen this, but when specifying `mariadb.auth.existingSecret=test-mariadb`, it doesn't update the volume secret in Matomo's deployment — see here](https://github.com/bitnami/charts/blob/b4719488b3fcd5037216469b249aaab9ca05d386/bitnami/matomo/templates/deployment.yaml#L307)..

This means the secret name must match the default expected by the chart, regardless of the existingSecret value. Is this the intended behavior?
