### ISSUE TITLE
I can't start pod RabbmitMQ in K8s

### ISSUE THREAD

**Issue by Thai-bug** [bitnami/charts#26591]
### Name and Version

bitnami/rabbitmq 14.3.2

### What architecture are you using?

None

### What steps will reproduce the bug?

On the logging screen, pod is stuck in the introduce screen

### What do you see instead?

I use hot path pvc for data storage
![image](https://github.com/bitnami/charts/assets/38286872/c2e2b60f-7aa9-4f91-917b-a34a9b793c3e)

**Comment by Thai-bug** [comment]
[values.txt](https://github.com/user-attachments/files/15521788/values.txt)

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
