### ISSUE TITLE
[bitnami/janusgraph] Improvement of documentation: Dockerimage/HelmChart How to create a Gremlin remote console

### ISSUE THREAD

**Issue by tnet-ag** [bitnami/charts#26590]
### Name and Version

bitnami/janusgraph HelmChart + Dockerimage

### What is the problem this feature will solve?

Will make it easier to start.
Otherwise the users have to reverse engeneer the Dockerimage / Helm chart to find out on how to start the gremlin console for the running janusgraph server with all credentials and the right config. 

### What is the feature you are proposing to solve the problem?

Example command for creating a remote gremlin connection in Readme on github and on docker hub .

After searching for a long time I found the an example command in the Helm Notes.txt, the text what you get when the chart is installed or you do helm status janusgraph.
The problem is that not everybody will see that text.
I forexample use Flux GitOps, so i never see these messages.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the input. Would it make sense to add the example to the README.md file as well? Would you like to submit a PR improving the README?
