### ISSUE TITLE
[bitnami/mongodb] - unknown field "spec.template.spec.initContainers[0].automountServiceAccountToken"

### ISSUE THREAD

**Issue by StarwingRC** [bitnami/charts#26596]
### Name and Version

bitnami/mongodb 15.6.1, 15.6.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

EKS: 1.28

While trying to render a chart using the params described below, I get a strange error mentioned in the title: 

```
 helm template --release-name mongodb-chart-update .  --debug > out_mongodb_chart_update.yaml

kubectl apply -f out_mongodb_chart_update.yaml -n sandbox --dry-run=server

Error from server (BadRequest): error when creating "mongodb_chart_update.yaml": StatefulSet in version "v1" cannot be handled as a StatefulSet: strict decoding error: unknown field "spec.template.spec.initContainers[0].automountServiceAccountToken"
```

### Are you using any custom parameters or values?

the following params are enabled:

externalAccess.enabled: true
externalAccess.autoDiscovery.enabled: true
automountServiceAccountToken: true

### What is the expected behavior?

Chart renders without any errors

### What do you see instead?

StatefulSet in version "v1" cannot be handled as a StatefulSet: strict decoding error: unknown field "spec.template.spec.initContainers[0].automountServiceAccountToken"

### Additional information

What I would be interested is finding out if you can also replicate the issue or is some misconfiguration on my side.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting . The issue is in the _helpers.tpl file

```
{{/*
Init container definition to get external IP addresses.
*/}}
{{- define "mongodb.initContainers.autoDiscovery" -}}
- name: auto-discovery
  image: {{ include "mongodb.externalAccess.autoDiscovery.image" . }}
  imagePullPolicy: {{ .Values.externalAccess.autoDiscovery.image.pullPolicy | quote }}
  # We need the service account token for contacting the k8s API
  automountServiceAccountToken: true

```

We should remove the automountServiceAccountToken line, as this should go to in the pod definition, not in the init container definition. As you discovered the issue, would you like to submit a PR removing it?
