### ISSUE TITLE
[bitnami/nginx] Allowing for customize dnsPolicy and dnsConfig for nginx

### ISSUE THREAD

**Issue by sepauli** [bitnami/charts#26612]
### Name and Version

bitnami/nginx 17.3.2

### What is the problem this feature will solve?

In the intranet K8S cluster, we have a server IP dedicated to DNS resolution, so we need to modify the dnsPolicy and dnsConfig to make the DNS resolution work.

### What is the feature you are proposing to solve the problem?

I would like to submit a patch for nginx like the patch for Kafka #21402
I have already a patch in my own repo https://github.com/sepauli/bitnami-charts/tree/dns-service

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
