### ISSUE TITLE
[bitnami/kafka] kafka user passwords

### ISSUE THREAD

**Issue by Umaaz** [bitnami/charts#26610]
### Name and Version

bitnami/kafka 28.0.4

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. deploy the chart with 2 users
2. change the password of one of the users
3. The password doesn't update 

### Are you using any custom parameters or values?

I am setting the `sasl.client.users` and `sasl.client.passwords`.

### What is the expected behavior?

The users/passwords should update to the new values.

### What do you see instead?

The usernames update but the passwords remain as the old values.

### Additional information

Looking into the issue, it seems that there is code https://github.com/bitnami/charts/blob/kafka/28.0.4/bitnami/kafka/templates/secrets.yaml#L20 that only updates the password value if the length of the old and new list has changed. This would explain the issue, as this is the scenario I had, I replaced an old user with a new user, so the list length did not change. Since then I have been getting auth issues as the passwords used by the apps are not the same as the passwords in the kafka service.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that currently, the users and passwords are only set on first boot. We would like to improve our charts to allow this kind of changes but currently this is not possible unless you deploy a custom job that performs the update operation.

**Comment by Umaaz** [comment]
I have been using the helm chart with terraform and although it restarts the cluster on a change (which is not ideal) it does work. I can add and remove users without an issue. Unless that is if I add and remove a user at the same time and the list doesn't change.

I have now added a 'dummy' user to my user list that I can remove or add as needed to ensure the list length changes.

From what I can see the issue I am getting is due to this:
```
{{- if or (empty $secretValue) (not (eq (len .Values.sasl.client.users) (len (splitList "," (b64dec $secretValue))))) }}
```
If I understand it correctly, if is checking that the new and old lists are the same length. If changed to check the string values are the same the issue should be resolved. Although I am unsure why a comparison is needed, can the value not just be updated to the new value?

**Comment by migruiz4** [comment]
Hi @Umaaz,

Thank you for reporting this issue. I have submitted this PR (#27097) which should fix this.
