### ISSUE TITLE
[minio] Cluster doesn't start when using distributed installation with NetworkPolicies enforced

### ISSUE THREAD

**Issue by vmwiz** [bitnami/charts#2667]
**Which chart**:
bitnami/minio 3.4.1

**Describe the bug**
When spinning up a distributed minio installation with `networkPolicy.enabled: true` and `networkPolicy.allowExternal: true` the following appear in pod logs
```
2020-05-26T09:55:47.715668832Z Waiting for a minimum of 2 disks to come online (elapsed 1s)
2020-05-26T09:55:47.715738309Z 
2020-05-26T09:55:48.214276401Z Waiting for a minimum of 2 disks to come online (elapsed 1s)
2020-05-26T09:55:48.214333417Z 
2020-05-26T09:55:48.71547668Z Waiting for a minimum of 2 disks to come online (elapsed 2s)
2020-05-26T09:55:48.715529077Z 
2020-05-26T09:55:49.214914187Z Waiting for a minimum of 2 disks to come online (elapsed 2s)
```
And the service keeps being unavailable

**To Reproduce**
1. Deploy the chart using the `values-production.yaml` and enable WebUI
```
helm install --name minio bitnami/minio -f values-production.yaml --set disableWebUI=false
```
2. Try to access the WebUI (through ingress or port-forward)
-> Unavailable
3. Grab logs from pods
```
kubectl logs pod/minio-0
kubectl logs pod/minio-1
kubectl logs pod/minio-2
kubectl logs pod/minio-3
```

**Expected behavior**
Minio distributed pods must be able to connect to each others.
You could add a second ingress policy with a label `minio-server` and tag the statefulset pods with it.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by vmwiz** [comment]
Issue still exists with latest release

**Comment by rafariossaa** [comment]
Hi @vmwiz ,
  Sorry for the long delay, it seems our support system missed this issue.

  Could you indicate in which kubernetes cluster are you running this chart ?.

**Comment by vmwiz** [comment]
Hi @rafariossaa,

I'm running it on a bare-metal (CentOS 7) kubespray cluster with 1.16.9

**Comment by rafariossaa** [comment]
Hi,
  I could run it by:
- Deleting the previous PVCs
- Deploy with following command, using provided `values-production.yaml`: 
```
helm install  myminio -f values-production.yaml --set networkPolicy.allowExternal=true --set disableWebUI=false .
```

Could you give it a try ?

**Comment by vmwiz** [comment]
Sorry for the late answer... Just had the chance to test your command and I can't reproduce the problem, my bad :confused:
As I haven't my original value file somewhere close to me to retest with my own values lets close this issue, thank you Rafael!
