### ISSUE TITLE
[bitnami/mysql] breaks with read only root filesystem

### ISSUE THREAD

**Issue by mjpitz** [bitnami/charts#2673]
**Which chart**:
```
chart:
    repository: https://charts.bitnami.com/bitnami
    name: mysql
    version: 6.13.2 
```

**Describe the bug**
When attempting to use the MySQL chart on a cluster with strict pod security policies, I encounter issues during startup with the `libmysql.sh` script. The complete output of my container is as follows:

```
$ kubectl logs -f -n depscloud mysql-slave-0
/opt/bitnami/scripts/libmysql.sh: line 60: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 114: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 126: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 133: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 145: cannot create temp file for here-document: Read-only file system
 19:06:26.10 
 19:06:26.11 Welcome to the Bitnami mysql container
 19:06:26.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
 19:06:26.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
 19:06:26.11 
 19:06:26.11 INFO  ==> ** Starting MySQL setup **
/opt/bitnami/scripts/libmysql.sh: line 60: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 114: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 126: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 133: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libmysql.sh: line 145: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/mysql/setup.sh: line 19: DB_TMP_DIR: unbound variable
```

**To Reproduce**
1. Set up strict pod security policies on a kubernetes cluster
2. Attempt to deploy the chart as is
3. Wait for the chart to try and start pods
4. Pods using the strict PSP will fail with output similar to above.

**Expected behavior**
The chart simply runs as it would on a cluster without strict PSP's.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I'm pretty sure the issue here is with the `/tmp` directory. With strict pod security policies, this directory becomes read only. The output seems to hint at here-documents needing the ability to create tmp files in `/tmp` in order to support the inline `cat <<"EOF"` syntax.

Adding an `emptyDir: {}` mount for `/tmp` should fix this problem.

**Comment by mjpitz** [comment]
I was able to verify adding the two `/tmp` mounts was able to get the chart to initialize properly, but mysql seems to crash with no information at the "==> Installing database" section.

```
$ kubectl logs -n depscloud mysql-master-0 mysql
mysql 19:40:22.61 
mysql 19:40:22.61 Welcome to the Bitnami mysql container
mysql 19:40:22.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 19:40:22.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 19:40:22.61 
mysql 19:40:22.62 INFO  ==> ** Starting MySQL setup **
mysql 19:40:22.67 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 19:40:22.68 INFO  ==> Initializing mysql database
mysql 19:40:22.69 INFO  ==> Installing database
```

**Comment by marcosbc** [comment]
Hi @mjpitz, currently the MySQL container does not support read-only file systems. But in any case, like you mention, by mounting some tmp volumes it may work (mainly for the logs and temporary directory -i.e. where the socket and PID files are stored-).

Could you try to enable the environment variable BITNAMI_DEBUG=yes on the failing node to get more information on the failure?

Also, to give you some heads up, we're planning major changes to the MySQL container to be released during this week (probably tomorrow), which could make the container easier to deploy with RO file systems (except for the log, pid and socket files as mentioned above).

**Comment by mjpitz** [comment]
@marcosbc Sure thing. Is there a branch for the refactor that I can try out? I'd love to give the new version a try.

**Comment by mjpitz** [comment]
Ah, very useful:

```
mysql 14:40:45.40 
mysql 14:40:45.40 Welcome to the Bitnami mysql container
mysql 14:40:45.41 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 14:40:45.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 14:40:45.41 
mysql 14:40:45.41 INFO  ==> ** Starting MySQL setup **
mysql 14:40:45.46 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 14:40:45.46 INFO  ==> Initializing mysql database
mysql 14:40:45.47 DEBUG ==> Custom configuration my.cnf detected
mysql 14:40:45.47 DEBUG ==> Ensuring expected directories/files exist
mysql 14:40:45.48 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 14:40:45.48 INFO  ==> Installing database
2020-05-27T14:40:45.500278Z 0 [System] [MY-013169] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.20) initializing of server in progress as process 150
2020-05-27T14:40:45.501358Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2020-05-27T14:40:45.501365Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2020-05-27T14:40:45.512126Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2020-05-27T14:40:45.518036Z 1 [ERROR] [MY-012576] [InnoDB] Unable to create temporary file; errno: 30
2020-05-27T14:40:45.518110Z 1 [ERROR] [MY-012929] [InnoDB] InnoDB Database creation was aborted with error Generic error. You may need to delete the ibdata1 file before trying to start up again.
2020-05-27T14:40:45.518294Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2020-05-27T14:40:45.518375Z 0 [ERROR] [MY-013236] [Server] The designated data directory /bitnami/mysql/data/ is unusable. You can remove all files that the server added to it.
2020-05-27T14:40:45.518471Z 0 [ERROR] [MY-010119] [Server] Aborting
2020-05-27T14:40:45.518814Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.20)  Source distribution.
```

I bet this is where the volume permissions init container comes in, which violates the run as non-root container in our PSP.

**Comment by marcosbc** [comment]
Unfortunately we don't have any public branch yet, but we are working towards having it published later today or tomorrow. We'll keep you posted with any update.

>I bet this is where the volume permissions init container comes in, which violates the run as non-root container in our PSP.

That would make sense, yes. But then, how would the init container for fixing permissions be able to do it, if it's not allowed to run as root?

**Comment by marcosbc** [comment]
Hi, we have already released the improvements to the MySQL container image. Version `6.14.2` of the chart should already include it, but you can also use the container tag `8.0.20-debian-10-r37` if you want to avoid upgrading the chart, for now.

**Comment by orlandothoeny** [comment]
I got the same error.

The container crashing after `==> Installing database`.
However, the issue in my case was an invalid custom config.

Checked it with https://dev.mysql.com/doc/refman/8.0/en/server-configuration-validation.html

Worked after fixing the config.
