### ISSUE TITLE
Changing ghostProtocol to https blocks service becoming online.

### ISSUE THREAD

**Issue by argestes** [bitnami/charts#2674]
**Which chart**:
ghost-10.0.6

**Describe the bug**
Changing ghostProtocol to https blocks service becoming online.

**To Reproduce**
1. Download https://github.com/bitnami/charts/blob/master/bitnami/ghost/values.yaml
2. Edit `ghostProtocol` to `https`
3. Change `service.type` to `ClusterIP`
4. Add `ghostHost` blog.example.com (leave ghostPort: 80 commented out)
5. Install the chart with changed values
6. Blog never comes online.

**Expected behavior**
Blog becoming online.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Tried to understand this for 5 hours possibly.

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. There are any errors in the logs `kubectl logs -f POD_NAME` ?

For the Ghost application function correctly, you should specify the `ghostHost` parameter to specify the FQDN (recommended) or the public IP address of the Ghost service.

Optionally, you can specify the `ghostLoadBalancerIP` parameter to assign a reserved IP address to the Ghost service of the chart. However please note that this feature is only available on a few cloud providers (f.e. GKE).

To reserve a public IP address on GKE:
```
$ gcloud compute addresses create ghost-public-ip
```
The reserved IP address can be assigned to the Ghost service by specifying it as the value of the `ghostLoadBalancerIP` parameter while installing the chart.

**Comment by argestes** [comment]
Hi, thanks for responding.
I'm prodiving FQDN for ghostHost. Its something like 'blog.mydomain.com'

I'm using the service as ClusterIP since I'm not allowing chart to write the ingress values for me. I'm running the chart on a Baremetal Load Balancer with Nginx Ingress controller for remote proxy.

I'm deciding to write my own ingress configuration is because If I let the chart to wrote those then when I uninstall the chart, ingress values and related certificates are also deleted.

When I change ghostProtocol to http the service starts, only problem I'm having is I cannot use the preview of the site since it tries to render a http version of the url and browser is blocking it.

There is no errors on log. Container thinks everyting is normal.

**Comment by argestes** [comment]
Maybe ghost thinks if ghostProtocol is https then it should listen to 443?

**Comment by carrodher** [comment]
Yes, you are right, we are setting this env. variable in the [deployment](https://github.com/bitnami/charts/blob/master/bitnami/ghost/templates/deployment.yaml#L70):
```yaml
- name: GHOST_PROTOCOL
  value: {{ .Values.ghostProtocol | quote }}
```
then this env. variable is used by the container to configure the url.

Also it's set in the readiness and liveness probes:
```yaml
{{- if eq .Values.ghostProtocol "https" }}
- name: X-Forwarded-Proto
  value: https
{{- end }}
```

**Comment by argestes** [comment]
Hey thanks for putting time and checking this issue!
Can you guide me to a workaround on this chart please?

**Comment by carrodher** [comment]
I think you need to also change the port:
```yaml
- name: GHOST_PORT_NUMBER
  value: {{ default .Values.service.port .Values.ghostPort | quote }}
```
this variable is going to use the port specified in the values.yaml or the one in the `ghostPort` parameter, you need to modify one of those parameters to reflect the change.

**Comment by argestes** [comment]
Do you consider this a bug or is this intented behavior?

**Comment by carrodher** [comment]
I think both environment variables should be set according to the desired scenario, if you want to use a protocol via `GHOST_PROTOCOL` that is served in a different port, you also need to set the `GHOST_PORT_NUMBER` variable.

If setting both parameters with the appropriate value, it doesn't work, then it's a real bug that we need to solve. In the other case, maybe we can add more documentation to clarify that, but IMHO it is not a bug.

**Comment by jalberto** [comment]
is there a way to make ghost uses whatever protocol is in the endpoint?

I add SSL in a different layer, but if I set Ghost to use http, every generated url uses it, while if I set to https it expects to manage SSL in its side

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
