### ISSUE TITLE
[bitnami/nats] add a servicemonitor

### ISSUE THREAD

**Issue by calvinbui** [bitnami/charts#2677]
**Which chart**:
nats-4.3.13
https://github.com/bitnami/charts/tree/master/bitnami/nats

**Describe the solution you'd like**
A `servicemonitor` template to be added to the NATS Helm Chart. Metrics can exported at the moment using `metrics.enabled: true`.

Other charts provided by Bitnami like:

- https://github.com/bitnami/charts/blob/16bd948d6d72bde3708b69231aecfcacd9d5c368/bitnami/rabbitmq/templates/servicemonitor.yaml
- https://github.com/bitnami/charts/blob/2548751a548177f513a7a19dbce59d92fd214aac/bitnami/postgresql-ha/templates/postgresql/servicemonitor.yaml
- https://github.com/bitnami/charts/blob/a0e44f7d6a10b8b5643186130ea420887cb72c7c/bitnami/wordpress/templates/servicemonitor.yaml

**Additional context**

**Comment by miguelaeh** [comment]
Hi @calvinbui ,
Thank you very much for your suggestion. We have limited resources so we don't cannot provide an estimated date for this change. Would you like to create a PR to make this process faster? We will review the PR in 24 hours.
