### ISSUE TITLE
[bitnami/harbor] service account for harbor resources

### ISSUE THREAD

**Issue by w0aw** [bitnami/charts#26870]
### Name and Version

bitnami/harbor:latest

### What is the problem this feature will solve?

current harbor helm chart doesn't create "serviceAccount" for any of harbor pods (excluding postgres & redis dependencies).
i guess relying of namespace default serviceAccount is not an good idea.

### What is the feature you are proposing to solve the problem?

a serviceAccount resource should be added in current chart. maybe one account for all pods. or maybe one for each component

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting the issue. Indeed, we should create a service account per component. I will forward it to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.
