### ISSUE TITLE
Add `mariadb.primary.persistence.selector` and `mariadb.primary.persistence.annotations`

### ISSUE THREAD

**Issue by Amphaal** [bitnami/charts#26879]
### Name and Version

bitnami/matomo 7.3.2

### What is the problem this feature will solve?

So we do not have to create a PVC manually specifically for DB, since this is not needed otherwise for matomo app files.

### What is the feature you are proposing to solve the problem?

Mimics `persistence.selector` and `persistence.annotations`, for consistency sake.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
