### ISSUE TITLE
[bitnami/rabbitmq] Downscale to 0 / shutdown the cluster with an attribute

### ISSUE THREAD

**Issue by paretl** [bitnami/charts#26872]
### Name and Version

bitnami/rabbitmq-cluster-operator 4.3.1

### What is the problem this feature will solve?

Today, I didn't find a solution to entirely stop/shutdown my RabbitMQ cluster. This is to reduce costs in an development kubernetes cluster
By changing the `replicas` to `0`, it does not remove the pods. I have to scale down my statefulset to remove my pods

If someone have solve this problem, I'm open to the solution

### What is the feature you are proposing to solve the problem?

Have an attribute like `shutdown: true` to automatically reduce the number of replicas to 0 on the Rabbitmq Cluster resource and on the statefulset
It could help to automate that with a CronJob that changes this parameter

### What alternatives have you considered?

Doing a custom Cronjob that will change the `replicas` and also modify the statefulset
But this is a hack

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
