### ISSUE TITLE
[ bitnami/harbor] trivy env var NO_PROXY misconfigured

### ISSUE THREAD

**Issue by w0aw** [bitnami/charts#26913]
### Name and Version

bitnami/harbor:21.4.2

### What architecture are you using?

arm64

### What steps will reproduce the bug?

using
```yaml
exposureType: ingress
```
I am not sure but maybe because of this env variable harbor shows trivy scanner as unhealthy. for more [details](https://github.com/goharbor/harbor-helm/pull/599)

### What is the expected behavior?

harbor-trivy env variable
```
NO_PROXY = "harbor-core,harbor-jobservice,harbor-database,harbor-registry,harbor-portal,harbor-trivy,127.0.0.1,localhost,.local,.internal"
```
### What do you see instead?

harbor-trivy env variable
```
NO_PROXY = "harbor-core,harbor-jobservice,harbor-database,harbor-registry,harbor-portal,harbor-trivy,127.0.0.1,localhost,.local,.internal,%!s(MISSING),%!s(MISSING),%!s(MISSING),%!s(MISSING)"
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
