### ISSUE TITLE
[redis] No route to host when after delete/reinstall

### ISSUE THREAD

**Issue by patrickgardella** [bitnami/charts#2697]
**Which chart**:
`redis-10.6.15`

**Describe the bug**
When starting with 'cluster.enabled=true' set (which is supposed to be the default), it starts one slave pod (out of the two in the statefulset), which then returns the error:
```
Warning  Unhealthy  3m8s (x5 over 4m36s)  kubelet, aks-default-26368278-vmss000000  Liveness probe failed: 
Could not connect to Redis at redis-master-0.redis-headless.chatbot.svc.cluster.local:6379: No route to host
Warning  Unhealthy  9s (x25 over 5m1s)  kubelet, aks-default-26368278-vmss000000  Readiness probe failed: 
Could not connect to Redis at redis-master-0.redis-headless.chatbot.svc.cluster.local:6379: No route to host
```

**To Reproduce**
1. Run `helm install -n chatbot redis bitnami/redis --set cluster.enabled=true`

__Note__ I had previously done a `helm -n chatbot uninstall redis` to try to remove redis and allow for a new installation. _It's almost acting like something was left over and not uninstalled._

**Expected behavior**
My expectation is that the slave stateful set would start and connect to the master.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
`kubectl -n chatbot logs redis-slave-0`:

> 18:32:46.96 INFO  ==> ** Starting Redis **
> 1:C 28 May 2020 18:32:46.970 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 1:C 28 May 2020 18:32:46.970 # Redis version=6.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
> 1:C 28 May 2020 18:32:46.970 # Configuration loaded
> 1:S 28 May 2020 18:32:46.972 * Running mode=standalone, port=6379.
> 1:S 28 May 2020 18:32:46.972 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> 1:S 28 May 2020 18:32:46.972 # Server initialized
> 1:S 28 May 2020 18:32:46.972 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> 1:S 28 May 2020 18:32:46.972 * Reading RDB preamble from AOF file...
> 1:S 28 May 2020 18:32:46.972 * Loading RDB produced by version 6.0.3
> 1:S 28 May 2020 18:32:46.972 * RDB age 5772 seconds
> 1:S 28 May 2020 18:32:46.972 * RDB memory usage when created 1.79 Mb
> 1:S 28 May 2020 18:32:46.972 * RDB has an AOF tail
> 1:S 28 May 2020 18:32:46.972 * Reading the remaining AOF tail...
> 1:S 28 May 2020 18:32:46.972 * DB loaded from append only file: 0.000 seconds
> 1:S 28 May 2020 18:32:46.972 * Ready to accept connections
> 1:S 28 May 2020 18:32:46.974 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:32:46.975 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:32:48.428 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:32:48.981 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:32:48.982 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:32:52.044 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:32:53.001 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:32:53.002 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:32:56.076 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:32:57.014 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:32:57.016 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:00.076 # Error condition on socket for SYNC: Resource temporarily unavailable
> 1:S 28 May 2020 18:33:01.034 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:01.035 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:03.149 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:04.043 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:04.045 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:06.220 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:07.059 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:07.060 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:09.292 # Error condition on socket for SYNC: Resource temporarily unavailable
> 1:S 28 May 2020 18:33:10.069 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:10.070 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:12.364 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:13.078 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:13.079 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:15.436 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:16.087 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:16.088 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:18.508 # Error condition on socket for SYNC: Resource temporarily unavailable
> 1:S 28 May 2020 18:33:19.098 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:19.099 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:21.580 # Error condition on socket for SYNC: Resource temporarily unavailable
> 1:S 28 May 2020 18:33:22.108 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:22.109 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:24.652 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:25.117 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:25.118 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:27.724 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:28.126 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:28.127 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:30.796 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:31.136 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:31.136 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:36.940 # Error condition on socket for SYNC: Operation now in progress
> 1:S 28 May 2020 18:33:37.157 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:37.157 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:40.012 # Error condition on socket for SYNC: Resource temporarily unavailable
> 1:S 28 May 2020 18:33:40.165 * Connecting to MASTER redis-master-0.redis-headless.chatbot.svc.cluster.local:6379
> 1:S 28 May 2020 18:33:40.166 * MASTER <-> REPLICA sync started
> 1:S 28 May 2020 18:33:43.084 # Error condition on socket for SYNC: Resource temporarily unavailable

**Comment by patrickgardella** [comment]
Further testing shows that this error occurs even when I do not pass the `--set cluster.enabled=true` in the install command. So it probably has to do with deleting and reinstalling...

**Comment by iMoses** [comment]
I'm experiencing the same issue under the same conditions.. still seems like an issue that should remain open

**Comment by rafariossaa** [comment]
Hi @iMoses , 
  Could you provide more context ? I would like to know which kubernetes cluster are you using, or if is has any special configuration.
Thanks forehand.

**Comment by phlegx** [comment]
Having the same problem on my cluster. ATM running bitnami `redis` with `sentinel` (1 master two slaves) on one single host (I know that should not be in production) for testing purposes. Had to restart my server and redis didn't came up. Had to restart the two slave pods then it was able to recover.

**Comment by iMoses** [comment]
> Hi @iMoses ,
> Could you provide more context ? I would like to know which kubernetes cluster are you using, or if is has any special configuration.
> Thanks forehand.

No special configuration, running on Azure AKS on version 1.16.9

**Comment by rafariossaa** [comment]
Hi,
  This was originally reported with chart version 10.6.15, current version is 10.7.11. 
  Could you indicate which chart version are you using ?

**Comment by phlegx** [comment]
I'm on version `10.5.7`. Will upgrade. Thanks!
