### ISSUE TITLE
rabbitmq-ha support

### ISSUE THREAD

**Issue by rajivml** [bitnami/charts#2698]
**Which chart**:
rabbitmq

HI,

The rabbitmq chart that is hosted here, does it supports HA as well with mirroring of queues, I don't see any parameters through which mirroring of queues can be enabled here, 

https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values-production.yaml

I had a look at this chart , but I read somewhere that these charts are gonna deprecated by end of this year, so don't want to take dependency on something which is going to get deprecated soon
https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/statefulset.yaml

**Comment by miguelaeh** [comment]
Hi @rajivml ,
Yes it is. You can just change the `replicas` parameter and the cluster will be created.

The official `helm/chart` repository is deprecated, so we moved all of our charts from there to the `bitnami/chart` repository.

**Comment by rajivml** [comment]
Thanks @miguelaeh for the confirmation, you can close this

**Comment by miguelaeh** [comment]
You're welcome
