### ISSUE TITLE
Recognize existingConfigmap change

### ISSUE THREAD

**Issue by xXluki98Xx** [bitnami/charts#27031]
### Name and Version

bitname/oauth2-proxy 5.3.3

### What is the problem this feature will solve?

I am mounting a custom ConfigMap, which i am templating in a umbrella chart, but the Oauth2Proxy Container are not restarted, if the Config content is changed.

I am currently manually killing the container.

### What is the feature you are proposing to solve the problem?

It would be nice if we could use the checksum function in the same way as for the "configuration.content" option.

I am not sure if it's possible to get a checksum of a ConfigMap that is not deployed by the helm chart.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by xXluki98Xx** [comment]
I also discovered now, that a update of the config, changed the default redis-password secret, but does not trigger the oauth2Proxy app to restart, which means it cannot connect to redis until a restart
