### ISSUE TITLE
[bitnami/thanos] Release 15.7.2 did not release helm chart to server

### ISSUE THREAD

**Issue by Hadlock** [bitnami/charts#27043]
### Name and Version

bitnami/thanos 15.7.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

terraform:

```hcl
resource "helm_release" "thanos-query" {
  # this is the service that queries the prometheus data stored on S3 sent there from the thanos-prometheus sidecar(s)
  name       = "thanos-query"
  repository = "oci://registry-1.docker.io/bitnamicharts/"
  chart      = "thanos"
  version    = "15.7.2"
  namespace  = "thanos"
  create_namespace = true
```

### Are you using any custom parameters or values?

version    = "15.7.1"

### What is the expected behavior?

should install

### What do you see instead?
```
helm_release.thanos-query: Creating...
╷
│ Error: could not download chart: registry-1.docker.io/bitnamicharts/thanos:15.7.2: not found
│
│   with helm_release.thanos-query,
│   on thanos.tf line 28, in resource "helm_release" "thanos-query":
│   28: resource "helm_release" "thanos-query" {
│
╵
```
### Additional information

I'm using terraform, but fails on the regular `helm` command line as well

**Comment by Hadlock** [comment]
To clarify, the chart was not sent to the chart server ,for whatever reason. Please note the errors in this PR https://github.com/bitnami/charts/pull/27020

thanks

**Comment by carrodher** [comment]
Thanks for letting us know. That version should be already available, see https://hub.docker.com/layers/bitnamicharts/thanos/15.7.2/images/sha256-23cf07632dd11665eb9c152152fa8486e00ea5859b5e7cedfbe5e9c9359e1861?context=explore
