### ISSUE TITLE
[bitnami/rabbitmq] change the statefulset.spec.podManagementPolicy from OrderedReady to Parallel

### ISSUE THREAD

**Issue by trevorboydsmith** [bitnami/charts#27042]
### Name and Version

bitnami/rabbitmq:14.x

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm install bitnami/rabbitmq
2. with replicas set to 3
3. wait for all pods to come online
4. you can get into one of three states: a. clustering works and all 3 pods are clustered b. deadlock c. you get two clusters one with 2 rabbits and one with 1 rabbit

### Are you using any custom parameters or values?

replica count set to 3 

### What is the expected behavior?

all 3 pods cluster together and report 3 out of 3 in the cluster when you do `rabbitmqctl cluster_status`

### What do you see instead?

you get two clusters: one with 2 rabbits and one with 1 rabbit

### Additional information

proposed solution:

* to avoid deadlock or cluster with less than 3 replicas follow official documentation https://www.rabbitmq.com/docs/cluster-formation#peer-discovery-k8s --> which says to use statefulset.spec.podManagementPolicy set to `Parallel` instead of `OrderedReady`

quote from official docs page:

```
Use Parallel podManagementPolicy

podManagementPolicy: "Parallel" is the recommended option for RabbitMQ clusters.

Because of [how nodes rejoin their cluster](https://www.rabbitmq.com/docs/clustering#restarting), podManagementPolicy set to OrderedReady can lead to a deployment deadlock with certain readiness probes:

-     Kubernetes will expect the first node to pass a readiness probe
-     The readiness probe may require a fully booted node
-     The node will fully boot after it detects that its peers have come online
-     Kubernetes will not start any more pods until the first one boots
-     The deployment therefore is deadlocked
- 

podManagementPolicy: "Parallel" avoids this problem, and the Kubernetes peer discovery plugin then deals with the [natural race condition present during parallel cluster formation](https://www.rabbitmq.com/docs/cluster-formation#initial-formation-race-condition).
```

when doing helm upgrade: you can kubectl delete statefulset THEN do helm upgrade to get the new `Parallel`

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the request. Indeed, this is something that was requested in other tickets but we could not prioritize it. If you want to speed up the process, would you like to submit a PR changing the default value?

**Comment by trevorboydsmith** [comment]
for helm install the first time, i found from my testing that changing from OrderedReady to Parallel causes the rabbitmq cluster to not form correctly more often. 

RE testing: for the example setting replica count set to N=3 then doing helm install, would get you 3 clusters each with cluster has one rabbitmq node instead of the expected one cluster with 3 rabbitmq nodes... and then i would have to manually delete rabbitmq-1, rabbitmq-2 pods and they would join into the cluster.

given my testing, i think the old OrderedReady config is better... so i'm marking this as "closed/"won't fix". 

(at the very least this would require more testing before committing this change.)

p.s. i apologize for causing any undue extra work for anyone.

**Comment by trevorboydsmith** [comment]
for helm install the first time, i found from my testing that changing from OrderedReady to Parallel causes the rabbitmq cluster to not form correctly more often. 

RE testing: for the example setting replica count set to N=3 then doing helm install, would get you 3 clusters each with cluster has one rabbitmq node instead of the expected one cluster with 3 rabbitmq nodes... and then i would have to manually delete rabbitmq-1, rabbitmq-2 pods and they would join into the cluster.

given my testing, i think the old OrderedReady config is better... so i'm marking this as "closed/"won't fix". 

(at the very least this would require more testing before committing this change.)

p.s. i apologize for causing any undue extra work for anyone.

**Comment by trevorboydsmith** [comment]
for helm install the first time, i found from my testing that changing from OrderedReady to Parallel causes the rabbitmq cluster to not form correctly more often. 

RE testing: for the example setting replica count set to N=3 then doing helm install, would get you 3 clusters each with cluster has one rabbitmq node instead of the expected one cluster with 3 rabbitmq nodes... and then i would have to manually delete rabbitmq-1, rabbitmq-2 pods and they would join into the cluster.

given my testing, i think the old OrderedReady config is better... so i'm marking this as "closed/"won't fix". 

(at the very least this would require more testing before committing this change.)

p.s. i apologize for causing any undue extra work for anyone.

**Comment by mpmatti** [comment]
@trevorboydsmith So is it the best practice to use OrderedReady when first deploying a RabbitMQ cluster for the cluster formation work correctly, and then later changing to Parallel for better tolerance of cluster restarts?
