### ISSUE TITLE
external-dns chart fails with "apiKey is not a method but has arguments" for powerdns provider

### ISSUE THREAD

**Issue by nserev** [bitnami/charts#2706]
**Which chart**:
external-dns
**Describe the bug**
When used with apiKey value I get the following error
Error: template: external-dns/templates/secret.yaml:51:26: executing "external-dns/templates/secret.yaml" at <.Values.pdns.apiKey>: apiKey is not a method but has arguments

**To Reproduce**
1. Create values.yaml similar to this one:
----
provider: "pdns"
pdns:
  apiUrl: "http://pdns.local"
  apiPort: 8081
  apiKey: APIKEY
txtOwnerId: "external-dns"
domainFilters:
  - "example.local"
logLevel: "debug"
interval: "10s"
rbac:
  create: "true"
-----
2. Try to install external-dns
3. See error

**Expected behavior**
Helm chart instaled with no errors.

**Version of Helm and Kubernetes**:
helm version: v3.1.2
kube version: v1.16.8-eks-e16311

**Additional context**
Works fine with secret for apikey

**Comment by miguelaeh** [comment]
Hi @nserev ,
it seems to be an issue in the Chart, we are taking care of that PR.
Thanks for reporting it!!
