### ISSUE TITLE
[bitnami/matomo] Wait for initial installation of matomo's components to complete before firing matomo's pod `Ready` state

### ISSUE THREAD

**Issue by Amphaal** [bitnami/charts#27064]
### Name and Version

bitnami/matomo 7.3.2

### What is the problem this feature will solve?

Kinda related to https://github.com/bitnami/charts/issues/15793; matomo app pod goes in `Ready` state before initial installation of matomo components in PersistentVolume is achieved. This is undesired if you need for instance to update `config/config.ini.php` right after pod installation, which does not exist yet at this stage; one might expect, using Ansible, that `Ready` state means that is completely up and ready, which is not really the case.

What happened in my case was that Ansible `community.general.ini_file` invoked right after `config/config.ini.php` silently created the path (directory + file) instead of editing it since it did not exist yet, thus generating ownership of said folder and file with root:root, which matomo's user 1001:1001 wont be able to update afterward.

### What is the feature you are proposing to solve the problem?

Update `readinessProbe` behavior to expect both apache server to be up and serving, AND ALSO, in case of initial installation, wait for it to finish. As a workaround, i now wait for `config/config.ini.php` before applying any modifications to it.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Would you like to submit a PR updating the readinessProbe to something more reliable?
