### ISSUE TITLE
[bitnami/matomo] Config (PVC) loss after stop ArgoCD Deployment - use Statefulset instead of Deployment

### ISSUE THREAD

**Issue by tgruenert** [bitnami/charts#27072]
### Name and Version

bitnami/matomo

### What is the problem this feature will solve?

* Installed helm chart via ArgoCD (personally i think, install via helm cause same effect)
* setup Matomo with the nice GUI
* remove ArgoCD App for Matomo - this also removes the PVC
* as a result the config is lost

Using a StatefulSet instead Deployment will not remove Volume after deleting Application. 

### What is the feature you are proposing to solve the problem?

Some other helms implement a StatefulSet and Deployment as a configurable alternative.

### What alternatives have you considered?

Alternatively you can set a hostPath as Volume. hostPath is deprecated.

**Comment by javsalgar** [comment]
Hi!

You can add the following annotation in persistence.annotations: `helm.sh/resource-policy: "keep"` 

https://github.com/helm/helm/issues/6261
