### ISSUE TITLE
[bitnami/jaeger] jaeger-cassandra-ready-check timed out

### ISSUE THREAD

**Issue by Sebastian-Materna** [bitnami/charts#27071]
### Name and Version

bitnami jaeger 2.3.4 and bitnami/cassandra 11.x

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using the jaeger chart in my AKS cluster with a single STS of cassandra. From scratch everything works fine but after some time, jaeger can't connect to cassandra anymore (this occurs on jaeger-agent, jaeger-collector and jaeger-query):

```
jaeger-cassandra-ready-check  13:38:06.62 INFO  ==> Connecting to the Cassandra instance jaeger-cassandra:9042
jaeger-cassandra-ready-check <stdin>:1:ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out - received only 0 responses." info={'consistency': 'ONE', 'required_responses': 1, 'received_responses': 0}
```

On the cassandra logs:
```
WARN  [Native-Transport-Requests-2] 2024-06-10 13:41:30,278 SelectStatement.java:462 - Aggregation query used without partition key
WARN  [Native-Transport-Requests-2] 2024-06-10 13:41:30,278 NoSpamLogger.java:108 - Aggregation query used without partition key on table bitnami_jaeger.traces, aggregation type: AGGREGATE_EVERYTHING
WARN  [Native-Transport-Requests-12] 2024-06-10 13:41:34,143 SelectStatement.java:462 - Aggregation query used without partition key
WARN  [Native-Transport-Requests-6] 2024-06-10 13:41:35,086 SelectStatement.java:462 - Aggregation query used without partition key
INFO  [Native-Transport-Requests-2] 2024-06-10 13:41:40,280 NoSpamLogger.java:105 - "Operation timed out - received only 0 responses." while executing SELECT * FROM bitnami_jaeger.traces WHERE token(trace_id) >= token(0x038c38b53cb94b41ca98aadcb452845b) LIMIT 100 ALLOW FILTERING
```

I'm running cassandra in a small environment with 1 CPU and 2GB memory. After wiping all data, it works for some time. Currently the data is 400MB, which IMHO is not much.

For a test, I have updated the cassandra node to 7 cores and 10GB memory without success. 
Also I have noticed the log:
```
INFO  [ReadStage-9] 2024-06-10 13:36:33,130 NoSpamLogger.java:105 - Maximum memory usage reached (512.000MiB) for chunk-cache buffer pool, cannot allocate chunk of 8.000MiB
```
on cassandra, since this is an INFO it should not prevent cassandra from operation, right? 

### Are you using any custom parameters or values?

```yaml
cassandra:
  persistence:
    size: 8Gi
  resources:
    requests:
      cpu: 1
      memory: 2048Mi
```

### What is the expected behavior?

Jaeger is running and can execute queries against cassandra backend

### What do you see instead?

See information about reproduce.

**Comment by Sebastian-Materna** [comment]
The query from `jaeger-cassandra-ready-check` `SELECT COUNT(*) FROM bitnami_jaeger.traces` is very expensive for cassandra. Maybe we need to update this query to be performant.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the drill down. Now that you have a better approach, would you like contribute sending a PR ? We will be glad to review and merge it.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
