### ISSUE TITLE
[bitnami/argo-cd] Argocd-repo-server pod getting restarted with OOMKilled

### ISSUE THREAD

**Issue by Pavanipogula** [bitnami/charts#27091]
### Name and Version

bitnami/argocd 4.7.18

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. We have enabled the resources limit and requests to argocd-repo-server. 
`resources:
          limits:
            cpu: 1500m
            memory: 500Mi
          requests:
            cpu: 30m
            memory: 75Mi`
 2. Post this change whenever we trigger multiple applications deployment at once with helm chart as source repo the pod is getting restarted with OOMKilled status.
 3. Logs obtained in the container are
 `{"error":"helm pull --destination /tmp/151cb75d-9882-4a0d-bb74-cdcda80aae8c --version 1.0.56903+33e65bd7 --repo https://charts.xxx.com test-app failed signal: killed","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2024-06-11T07:47:01Z","grpc.time_ms":20298.629,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2024-06-11T07:47:21Z"}`

### What is the expected behavior?

The pod shouldn't restart.

### What do you see instead?

The pods are getting restarted with OOMKilled error

**Comment by javsalgar** [comment]
Hi,

Thank you so much for opening the ticket. The OOMKilled error has to do with the pod running out of memory. Did you try increasing the memory values? If your question is about why it consumes that amount of memory, this has to do with the application itself, and then my advice would be to check with the upstream argo-cd devs.

**Comment by Pavanipogula** [comment]
Hi @javsalgar 

We have incresed the resource limits for the pod and it solved the issue. Thanks.
