### ISSUE TITLE
[bitnami/odoo] Enable high performance setup for replicaCount > 1

### ISSUE THREAD

**Issue by fzhan** [bitnami/charts#27105]
### Name and Version

bitnami/odoo:26.2.4

### What is the problem this feature will solve?

Repeated Serialization Errors("could not serialize access due to concurrent update") in Postgres Database when deployed with replicaCount > 1.

Upgrade the database to allow repeatable read:
ALTER DATABASE db_name SET DEFAULT_TRANSACTION_ISOLATION TO 'repeatable read';

Error reporting db deadlock.

### What is the feature you are proposing to solve the problem?

Apply db config for postgresql to allow replicaCount > 1

**Comment by javsalgar** [comment]
Hi!

The PostgreSQL subchart allows setting init scripts to modify the database

```
postgresql:
  primary:
    initdb:
      scripts:
        enable_performance.sql: | 
          ALTER DATABASE bitnami_odoo SET DEFAULT_TRANSACTION_ISOLATION TO 'repeatable read';
```

Did you try that?

**Comment by fzhan** [comment]
@javsalgar I will give this ago. I'm using external postgresql at the moment so I managed to altered the db separately.

Just wondering if the team has tested it with multi pod / concurrent setup, that's all. There seems to be levels of configuration for Odoo to be able to operate with more than one concurrent pods.

**Comment by fzhan** [comment]
Can I use ```postgresql:
  primary:
    initdb:
      scripts:``` to install additional python packages? Such as pdfminer?

**Comment by jotamartos** [comment]
>Just wondering if the team has tested it with multi pod / concurrent setup, that's all. There seems to be levels of configuration for Odoo to be able to operate with more than one concurrent pods.

We test the solution using some [custom values](https://github.com/bitnami/charts/blob/main/.vib/odoo/runtime-parameters.yaml). We test that the UI works as expected as well as some commands and files inside the pod/container. Everything is described in the [TESTING page](https://github.com/bitnami/charts/blob/main/TESTING.md).

>Can I use postgresql: primary: initdb: scripts: to install additional python packages? Such as pdfminer?

You can use an initContainer to install anything you need before deploying the application 

```
## @param initContainers Add additional init containers to the Odoo pods
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'copy addons from git and push to /bitnami/odoo/addons. Should work with extraVolumeMounts and extraVolumes']
##
initContainers: []
```

**Comment by fzhan** [comment]
@jotamartos Thank you! I will give these a go.

**Comment by fzhan** [comment]
@jotamartos this doesn't help install additional python package such as pandas, since the venv is in the original image. The 'AccessShareLock' is caused by the init script, and 'ALTER DATABASE db_name SET DEFAULT_TRANSACTION_ISOLATION TO 'repeatable read';' needs to be run everytime a new pod restarts, somehow the init script reset the db transaction isolation.

**Comment by fzhan** [comment]
> @jotamartos this doesn't help install additional python package such as pandas, since the venv is in the original image. The 'AccessShareLock' is caused by the init script, and 'ALTER DATABASE db_name SET DEFAULT_TRANSACTION_ISOLATION TO 'repeatable read';' needs to be run everytime a new pod restarts, somehow the init script reset the db transaction isolation.
> 
> Does that mean I need to place the script in customPostInitScripts and set odooSkipInstall to off?
> 
> Also just to follow up, for anyone who's out there trying to set this using Bitnami Helm, you can't just simply set replicaCount to 3, it's a known Odoo limitation on the postgresql: https://www.odoo.com/sl_SI/forum/pomoc-1/repeated-serialization-errors-could-not-serialize-access-due-to-concurrent-update-in-postgres-database-148511
> 
> I'm still trying to figure out how to pass the value so it can kick start with replicaCount = 3.

Apparently that's a replacement of existing post-init.sh, anythiing I place in customPostInitScript took away the original /docker-entrypoint-init.d and reported missing conf file [in /opt/bitnami/odoo/conf](grep: /opt/bitnami/odoo/conf/odoo.conf: No such file or directory)

**Comment by fzhan** [comment]
All init script fixed. But i'm still struggling to start fresh using replicaCount = 3. Perhaps a consideration for the next helm upgrade?

Forgot to mention that I'm using external postgresql.

**Comment by fzhan** [comment]
> All init script fixed. But i'm still struggling to start fresh using replicaCount = 3. Perhaps a consideration for the next helm upgrade?
> 
> Forgot to mention that I'm using external postgresql.

customPostInitScript doesn't work, the module required a python library, every time the deployment restarts, it skips the installation, why does it only install once?

**Comment by fzhan** [comment]
> > Just wondering if the team has tested it with multi pod / concurrent setup, that's all. There seems to be levels of configuration for Odoo to be able to operate with more than one concurrent pods.
> 
> We test the solution using some [custom values](https://github.com/bitnami/charts/blob/main/.vib/odoo/runtime-parameters.yaml). We test that the UI works as expected as well as some commands and files inside the pod/container. Everything is described in the [TESTING page](https://github.com/bitnami/charts/blob/main/TESTING.md).
> 
> > Can I use postgresql: primary: initdb: scripts: to install additional python packages? Such as pdfminer?
> 
> You can use an initContainer to install anything you need before deploying the application
> 
> ```
> ## @param initContainers Add additional init containers to the Odoo pods
> ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
> ## e.g:
> ## initContainers:
> ##  - name: your-image-name
> ##    image: your-image
> ##    imagePullPolicy: Always
> ##    command: ['sh', '-c', 'copy addons from git and push to /bitnami/odoo/addons. Should work with extraVolumeMounts and extraVolumes']
> ##
> initContainers: []
> ```

hi @jotamartos , initContainers does not take effect on npm / python related library installation such as npm less or pandas. Is there any other ways for 'packages' to be installed to the system path within docker image?

**Comment by fzhan** [comment]
@javsalgar after spent month debugging, I found that the reason odoo bitnami chart doesn't support replicaCount >1 is that it runs setup every time, https://github.com/bitnami/containers/blob/d0b0771fdb5178cf98be6ee507565a2ed9d8736c/bitnami/odoo/17/debian-12/rootfs/opt/bitnami/scripts/odoo/entrypoint.sh#L23

Is there any way these setup can be avoid or is it by design that odoo deployment can only run with one instance?

**Comment by javsalgar** [comment]
In principle, if it's possible, we have no restrictions in setting it, though it is true that this setup has not actively tested. At least for testing, you could override the `command` and `args` section with a check that ensures that the setup is only run the first time (for example by checking the persistence)

**Comment by fzhan** [comment]
@javsalgar thanks for the suggestion. In short, I've turned on skip bootstrap. Will see what else can be improved over the next couple of months.
```
  - name: ODOO_SKIP_BOOTSTRAP
    value: "true"
```
