### ISSUE TITLE
[bitnami/etcd] bug: readinessProbe will fail when run etcd with tls

### ISSUE THREAD

**Issue by chenraoCR** [bitnami/charts#27109]
### Name and Version

bitnami/etcd:10.2.2

### What architecture are you using?

None

### What steps will reproduce the bug?

1. config bitnami/etcd values.yaml using self-signed certs
![image](https://github.com/bitnami/charts/assets/45187622/8688ac6d-9d76-44ae-999d-1e6d90d18b04)
2. helm install etcd

### Are you using any custom parameters or values?

values.yaml
![image](https://github.com/bitnami/charts/assets/45187622/8688ac6d-9d76-44ae-999d-1e6d90d18b04)

### What is the expected behavior?

etcd should run normally

### What do you see instead?

etcd pod readinessProbe fails

### Additional information

1. if set auth.client.caFileName, then ectd will startup with two-way tls authentication, but livenessProbe will fail
![image](https://github.com/bitnami/charts/assets/45187622/ab7bdbff-ba92-44e2-b7dd-4b37dd80f92f)
as it uses httpGet, only support one-way tls authentication
https://github.com/bitnami/charts/blob/ea7b2f5847c1cc7b2693e471e2b13712c1979752/bitnami/etcd/templates/statefulset.yaml#L290
2. if not set auth.client.caFileName, means leave it empty, then ectd will startup with one-way tls authentication, but readinessProbe will fail
![image](https://github.com/bitnami/charts/assets/45187622/fbf73c20-9024-4986-8c31-73cfb11cb5a3)
as it uses script /opt/bitnami/scripts/etcd/healthcheck.sh, 
https://github.com/bitnami/charts/blob/ea7b2f5847c1cc7b2693e471e2b13712c1979752/bitnami/etcd/templates/statefulset.yaml#L304

`healthcheck.sh`
![image](https://github.com/bitnami/charts/assets/45187622/c6a7af64-1431-4781-8c3d-a311d57849c2)
`libetcd.sh`
![image](https://github.com/bitnami/charts/assets/45187622/93627d0a-575a-4dc9-9bb5-5c15794a072d)
then  _etcdctl endpoint health_ will fail as it needs the CA to verify the serve certs, but caCert not set in the values.yaml
![image](https://github.com/bitnami/charts/assets/45187622/5ec1b989-7cd7-4dca-8dc1-4df1413896b7)
3. solutions
3.1 just allow etcd startup in one-way tls
remove auth.client/peer.caFilename, and set readinessProbe&startupProbe using httpGet just like livinessProbe
3.2 allow etcd startup in one-way & two-way tls
need to change `libetcd.sh`,  when not supply CA file but etcd startup with tls, then add `--insecure-transport=false --insecure-skip-tls-verify=true`  to the `etcdctl_auth_flags`
![image](https://github.com/bitnami/charts/assets/45187622/4c1649db-7519-48ab-8b7b-69aec59aca84)

**Comment by chenraoCR** [comment]
what's the progress on this issue

**Comment by juan131** [comment]
Hi @chenraoCR 

Thanks so much for reporting the issue and providing so much context. I think what makes sense is to add the flags `--insecure-tranrt=false --insecure-skip-tls-verify=true` to the `etcdctl_auth_flags` when mutual TLS is enabled.

Would you like to contribute with a PR amending this? You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md). Your contribution will greatly benefit the community.

**Comment by chenraoCR** [comment]
Hi @juan131 
Sorry but i think maybe cannot commit the PR for this issue, this issue is about the bitnami/etcd docker image, donot know how to commit a PR to change the etcd docker image, this needs to modify the file "libetcd.sh" in the docker image, think i have no the right to do such thing

**Comment by chenraoCR** [comment]
ah, i found where to modify the docker image files

**Comment by juan131** [comment]
Thanks so much for the PR! The team will review it
