### ISSUE TITLE
[bitnami/argo-cd] ArgoCD repo-server NetworkPolicy uses ApplicationSet values

### ISSUE THREAD

**Issue by tmarback** [bitnami/charts#27108]
### Name and Version

bitnami/argo-cd 6.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the chart with `repoServer.networkPolicy.enabled: true`

### Are you using any custom parameters or values?

`repoServer.networkPolicy.enabled: true`

### What is the expected behavior?

The `NetworkPolicy` resource generated for the repo-server component should have the values specified in the `repoServer.networkPolicy` section.

### What do you see instead?

It has the values from the `applicationSet.networkPolicy` section instead.

### Additional information

See [templates/repo-server/networkpolicy.yaml in the current latest commit](https://github.com/bitnami/charts/blob/dd705237d4f14d7005b707075995185272fb4882/bitnami/argo-cd/templates/repo-server/networkpolicy.yaml) - all the templates use `.Values.applicationSet` instead of `.Values.repoServer`.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! As you spotted the issue, would you like to submit a PR setting the correct references?

**Comment by Jeremy-Boyle** [comment]
Ill do a PR for this, i have some changes that need to be addressed as well.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
