### ISSUE TITLE
[postgresql-ha] How to recovery data manually by mounted files?

### ISSUE THREAD

**Issue by liyuntao** [bitnami/charts#2711]
If I ran into a situation when the pg-ha lose PVC,
or I cannot make any pod in running state. But mounted data files are still on my disk.

How should I do to make a re-deployment without losing old data?

Backgroud1:
https://github.com/bitnami/charts/issues/2033
The cluster kept crash. And primary is on pod1. 
After downscale to replica=0, the pod0 cannot successfully start forever.

Backgroud2:
(The worst situation) lose everything but mounted files on machine.

**Comment by liyuntao** [comment]
Just found out how to connect mounted volumes using single pg with a docker-compose file. (Manual copy generated postgresql.conf/pg_hba.conf to  original `/data` folder) Then pg can start normally. Thus I can dump the data and re-create whole cluster manually. (Backgroud2 case)

I hope to know is there any solution to recover cluster when I met situation like case backgroud1, with pvc/pv/mounted volume files left.

**Comment by joancafom** [comment]
Hi @liyuntao !

>  But mounted data files are still on my disk.

Just to figure out the correct scenario, do you mean that you lost every asset of your release (including PVCs), but you keep a copy of mounted data in your hard drive? So, you want to create a brand new release that uses that data in order to recover the previous state, am I right?
Also, if you think a step-by-step use case would help be better understand your problem, that would be nice 😀

Thanks!

**Comment by liyuntao** [comment]
Hi, @joancafom  Thanks for your quick reply.

Yeah, that's right. The backgroud2 is just my hypothetical scenario if someday somebody does some misoperation(delete helm release, delete all PVCs), how could I re-create a release without losing data.

The steps I found out and working currently is:
0. Assume my previous production data(local PV's hostPath) is left on physical Node, which is `/data/pg_prod_data`.
1. Start a simple Postgres instance by docker-compose(details below), with two volume mounted.
2. Copy default first-time generated files, `postgresql.conf` and `pg_hba.conf` to mounted data folder `/data/pg_prod_data`,  from `my_local_folder_for_get_confs` in YAML.
3. docker exec -it into Postgres instance, execute pg_dump manually, get all databases dump to volume path two, which is `/backup` in the container,  also `my_local_folder_for_backup` on physical Node.
4. deploy a brand new release using `bitnami/postgres-ha` chart.
5. Start a pg-client pod in Kubernetes, with hostPath volume to `my_local_folder_for_backup`. Manually connect to the container IP of current primary pg-ha instance(in the brand new release), then exec pg_restore to recover all data.

```yaml
version: '3.1'

services:
 db:
  image: postgres:11
  restart: always
  environment:
   POSTGRES_PASSWORD: xxxx
  volumes:
    - ./my_local_folder_for_get_confs/data:/var/lib/postgresql/data
   - ./my_local_folder_for_backup:/backup
  ports:
    - 5432:5432
```

The recovery steps seem silly and slow. Although it can solve my problem, at least no data loss, I wonder if someday I met an emergency in production, the recovering time and long service stop time may be a big problem.

Is there a more efficient recovery plan/steps that exist(if I can re-deploy the release and using old volume files directly)?  If the dataset is huge, the `dump-deploy-reImport` way may be time-consuming.

**Comment by joancafom** [comment]
Hey @liyuntao 

Thanks for your explanation! There are two main ideas that comes to my mind for what you want to do. I will try to explain them and you can tell me if they are a valid option to you 😁. 

There are two concepts in Kubernetes called [_Jobs_](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) and [_CronJob_](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/). If you are not familiar with them, the main idea is to create some pods that carry out some task to completion. A _CronJob_ in addition will perform the duty periodically.

On the one hand, you can create a simple _CronJob_ that runs from time to time (maybe once every two days) and performs a dump of your Postgres. Once the dump is performed, you can use an external uploading provider (like Azure, Amazon, Google, ...) to keep your latest record.  You make take a look at this [example](https://github.com/bitnami/charts/blob/47162eea9388033b62096cdae468415b48e9278b/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml) from influxdb.

On the other, you could have a _Job_ that you may run on the unlikely event of failure and that takes care of setting up a new PVC with the restored data. By using the property `persistence.existingClaim` you can indicate `postgres-ha` to use a pre-existing PVC in a given release.

Would that make sense? Thanks!
