### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] RabbitMQ Messaging Topology Operator: TopicPermission WebhookConfiguration not present

### ISSUE THREAD

**Issue by DanielePalaia** [bitnami/charts#27143]
### Name and Version

bitnami/rabbitmq-cluster-operator:4.3.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. helm install my-release oci://registry-1.docker.io/bitnamicharts/rabbitmq-cluster-operator 
2. kubectl edit ValidatingWebhookConfiguration my-release-rabbitmq-messaging-topology-operator-webhook-default

The Webhook configuration for this specific controller is missing.
I also noticed it missing here:

https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml

### What is the expected behavior?

The relative controller TopicPermission doesn't work correctly on update/delete as the Webhook Configuration is not present

### What do you see instead?

The relative controller should work on update field ecc...

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Indeed, it seems that some configuration from upstream is missing. Would you like to submit a PR updating the missing configuration? If not we will work on it.

**Comment by DanielePalaia** [comment]
@javsalgar Yes, actually I already did the implementation and now it is working. I didn't do the PR because I wasn't sure if this file https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml was edited by some of your automation
