### ISSUE TITLE
[bitnami/keycloak] Allow multiple `extraEnvVarsCM` and `extraEnvVarsSecret` values

### ISSUE THREAD

**Issue by rassie** [bitnami/charts#27156]
### Name and Version

bitnami/keycloak:21.4.1

### What is the problem this feature will solve?

Keycloak is a service that's usually deployed centrally for multiple independent teams to use. When a need arises in these teams to create an SPI, these SPIs might need to get configured via environment variables. However, while the application team is in charge of these variables, someone else is managing the Keycloak instance, so that this team might decide to provide people in charge of the Keycloak instance a known `ConfigMap` or a `Secret` name which it's in charge of and which would contain all the variables the team needs. Variables from this `ConfigMap` or `Secret` could be added to Keycloak via `extraEnvVarsCM` or `extraEnvVarsSecret` values.

However, this currently only works for one team since there is only one extension point, i.e. `extraEnvVarsCM` and `extraEnvVarsSecret` both accept only one value each. If extended to arrays, these values could allow scaling to multiple teams delivering their configuration and SPIs to the central Keycloak instance.

### What is the feature you are proposing to solve the problem?

Make `extraEnvVarsCM` and `extraEnvVarsSecret` accept arrays of values.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Would you like to submit a PR adding support for these values as arrays? It would be important to allow backwards compatibility to not force a major bump in the chart.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
