### ISSUE TITLE
[bitnami/kube-prometheus] support for prometheus agent resource KIND

### ISSUE THREAD

**Issue by w0aw** [bitnami/charts#27189]
### Name and Version

[ bitnami/kube-prometheus:9.2.1 ]

### What is the problem this feature will solve?

just wanted to know, what if i have remote storage for prometheus and i just want to run only few agents with shards.
related issue in [community chart](https://github.com/prometheus-community/helm-charts/issues/1519)
### What is the feature you are proposing to solve the problem?

i know currently we can run "prometheus" kind with remote write, but it consumes a lot of memory.

### What alternatives have you considered?

i guess there should be an option for like "prometeus.useAgentMode" if its true then we can switch resource kind to prometheusAgent or we can have whole new resource sets with prometheusAgent disabled by default.
addition info [here](https://github.com/prometheus-community/helm-charts/pull/3520/files) AND [here](https://github.com/prometheus-community/helm-charts/pull/3628/files)

sorry but please let me know if its already supported

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process you can submit a PR and the team will review it.
