### ISSUE TITLE
[bitnami/harbor] - trivy persistence using existing PVC

### ISSUE THREAD

**Issue by cwrx777** [bitnami/charts#27184]
### Name and Version

bitnami/harbor 21-4.3

### What is the problem this feature will solve?

Question:
any reason why [trivy ](https://github.com/bitnami/charts/blob/harbor/21.4.3/bitnami/harbor/templates/trivy/trivy-sts.yaml)does not support existing claim persistence, unlike [registry](https://github.com/bitnami/charts/blob/harbor/21.4.3/bitnami/harbor/templates/registry/registry-pvc.yaml#L7)? 

reference: 
[harbor-helm](https://github.com/goharbor/harbor-helm/blob/v1.14.2/templates/trivy/trivy-sts.yaml#L180)

### What is the feature you are proposing to solve the problem?

To let trivy to use existing PVC.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
