### ISSUE TITLE
[bitnami/harbor] - allow using existing secret for ingress

### ISSUE THREAD

**Issue by cwrx777** [bitnami/charts#27187]
### Name and Version

bitnami/harbor 21.4.3

### What is the problem this feature will solve?

there is no option if we already have exising secret for tls. 

### What is the feature you are proposing to solve the problem?

using exiting secret for  `.Values.ingress.core.hostname`

### What alternatives have you considered?

`.Values.ingress.core.extraTls`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
