### ISSUE TITLE
[bitnami/harbor] - add  SCANNER_TRIVY_SKIP_JAVA_DB_UPDATE in trivy CM Environment variables

### ISSUE THREAD

**Issue by cwrx777** [bitnami/charts#27190]
### Name and Version

bitnami/harbor 21.4.3

### What is the problem this feature will solve?

Currently we need to use extra envVars to configure SCANNER_TRIVY_SKIP_JAVA_DB_UPDATE. 

### What is the feature you are proposing to solve the problem?

allow SCANNER_TRIVY_SKIP_JAVA_DB_UPDATE to be configurable using values.yaml. 
[reference](https://github.com/goharbor/harbor-helm/blob/v1.14.2/templates/trivy/trivy-sts.yaml#L96)
also also refer to other environment variables [here](https://github.com/goharbor/harbor-helm/blob/v1.14.2/templates/trivy/trivy-sts.yaml#L64)

### What alternatives have you considered?

using extra envVars

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.
