### ISSUE TITLE
helm charts kafka doc without param auth.ssl

### ISSUE THREAD

**Issue by ThePolarNight** [bitnami/charts#2724]
**Which chart**:
The name (and version) of the affected chart
3.1.0
**Describe the bug**
helm charts kafka readme.md file (branch master)without param auth.ssl, but template file svc.yaml use this param.

**Comment by javsalgar** [comment]
Hi,

Currently, we are doing a major refactor of the authentication, so now new parameters will be used. Feel free to take a look here: https://github.com/bitnami/charts/pull/2708/files

Thank you very much for the feedback :)
