### ISSUE TITLE
[bitnami/kafka] externalAccess (LoadBalancer) with custom port doesn't work

### ISSUE THREAD

**Issue by jkralik** [bitnami/charts#2726]
**Which chart**:
kafka-10.3.3

**Describe the bug**
When you set external access with LoadBalancer with custom port, then client cannot connect.

**To Reproduce**
1. Run `helm install my-release bitnami/kafka --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer --set externalAccess.service.port=19093 --set 'externalAccess.service.loadBalancerIPs[0]=LOAD_BALANCER_IP'`

But if you use default port then it works:
 `helm install my-release bitnami/kafka --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer --set externalAccess.service.port=19092 --set 'externalAccess.service.loadBalancerIPs[0]=LOAD_BALANCER_IP'`

**Expected behavior**
Client can connect to customized port.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by dani8art** [comment]
Hi @jkralik, we have just release a major version of this chart, could you test with the latest version and see if it works? `helm repo update` and try with the latest one `11.0.0`.
Thanks!

**Comment by jkralik** [comment]
@dani8art Yes it is working with `11.0.0`. What I need to do If I want to change `externalAccess.service.port` to `9092` ? I found that I need to change `service.port`, `service.internalPort` , because listeners cannot listen on same port.

**Comment by jkralik** [comment]
With this cfg it's not working:
```
allowPlaintextListener: false
service:
  port: 19092
  internalPort: 19093

externalAccess:
  enabled: true
  service:
    port: 9092
```
and Kafka produces error:
`[2020-06-03 11:35:25,994] WARN [Controller id=0, targetBrokerId=0] Connection to node 0 (kafka-0.kafka-headless.streaming.svc.cluster.local/172.17.0.20:19093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)`

**Comment by juan131** [comment]
Hi @jkralik 

Probably related to the hardcoded port in the listeners (despite the advertised listeners are correctly configured).

- Could you please share the whole values.yaml you're using?
- Could you also share the output of running the command below?

```console
kubectl get sts kafka -o yaml --namespace streaming
```

**Comment by jkralik** [comment]
@juan131 Sure:

[values.yaml](https://github.com/bitnami/charts/files/4729513/values.yaml.txt)
[cmd.output](https://github.com/bitnami/charts/files/4729533/cmd.output.txt)
Kafka logs:
[kafka-0.log](https://github.com/bitnami/charts/files/4729536/kafka-0.log.txt)
