### ISSUE TITLE
[bitnami/mongodb-sharded] PVC are not deleted on chart uninstallation

### ISSUE THREAD

**Issue by tschneider-aneo** [bitnami/charts#27306]
### Name and Version

bitnami/mongodb-sharded 8.2.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm install my-mongodb-sharded oci://registry-1.docker.io/bitnamicharts/mongodb-sharded --version=8.2.3`
2. `helm uninstall my-mongodb-sharded`
3. `kubectl get pvc`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

As described in the chart documentation, the option `shardsvr.persistence.resourcePolicy` is set to `""` by default and the following description is provided: ([doc](https://artifacthub.io/packages/helm/bitnami/mongodb-sharded#shard-configuration-persistence-parameters))

> "Setting it to "keep" to avoid removing PVCs during a helm delete operation. Leaving it empty will delete PVCs after the chart deleted"

Thus, the persistent volume claims created by the Helm chart should be destroyed on chart uninstallation.

### What do you see instead?

The persistent volume claims are still there.

**Comment by juan131** [comment]
Hi @tschneider-aneo 

Thanks so much for reporting this issue!! I think this is a copy-paste error to be honest. This workaround works for avoiding PVCs to be removed when their associated manifest is explicitly included as part or the chart, for instance in the example below:

- https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/standalone/pvc.yaml#L16

However, when the PVC is created as a result of using "volumeClaimTemplates" in a statefulset, Helm is unable to recognize that PVC is part of the Helm release. This is a known limitation in Helm, see:

- https://github.com/helm/helm/issues/5156

Therefore, unless I'm missing sth, we should remove every reference in the catalog to this workaround if they're applied to "volumeClaimTemplates".

**Comment by tschneider-aneo** [comment]
Thank you for you answer @juan131 !

You mentionned the way the "classical" mongodb chart overcomes this Helm limitation when the architecture is a standalone and the PVC is created with its own YAML manifest.

However, I've already deployed MongoDB with this chart, even with a replica set architecture and I had no problems deleting PVC's on chart uninstallation thanks to the `persistentVolumeClaimRetentionPolicy.enabled` and `persistentVolumeClaimRetentionPolicy.whenDeleted` options.

So I just checkoud the StatefulSet template and eventhough the PVC's are created as a result of using "volumeClaimTemplates" within a StatefulSet manifest, the chart also defines a `persistentVolumeClaimRetentionPolicy` in the StatefulSet spec, making PVC's deletion on chart uninstallation work :
https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/statefulset.yaml#L530

So implementing this in the shardsvr's StatefulSet should fix this issue I think.

**Comment by juan131** [comment]
You're completely right! I just created a PR to address this

**Comment by tschneider-aneo** [comment]
That's great, thank you for your quickness in addressing this issue ! I'm looking forward to using this feature !
