### ISSUE TITLE
Document metrics.sentinel parameters

### ISSUE THREAD

**Issue by georgelupu** [bitnami/charts#27305]
### Name and Version

bitnami/redis 19.5.0

### What is the problem this feature will solve?

Currently, in the README file we can find one line stating that:
in chart version 14.0.0, _`sentinel.metrics.*` parameters are deprecated in favor of metrics.sentinel.* ones._, but no documentation is provided on the `metrics.sentinel.*` parameters that an end user could use.

### What is the feature you are proposing to solve the problem?

Document the use of `metrics.sentinel.*` parameters.

### What alternatives have you considered?

None

**Comment by carrodher** [comment]
In the latest versions metrics for sentinel were removed, that's why there is not any mention to them in the README

**Comment by georgelupu** [comment]
Thank you @carrodher for the prompt reply.
I will close this issue.
