### ISSUE TITLE
[bitnami/vault] Allow to disable auth delegator

### ISSUE THREAD

**Issue by ChristianRaoulis** [bitnami/charts#27310]
### Name and Version

bitnami/vault 1.4.7

### What is the problem this feature will solve?

I am not allowed to create cluster roles on the cluster:

```
Unable to continue with install: could not get information about the resource ClusterRoleBinding "vault-dfba03cf-core-services-server" in namespace "": clusterrolebindings.rbac.authorization.k8s.io "vault-dfba03cf-core-services-server" is forbidden: User "u-tr4u7rcbue" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

and since only the auth delegator requires that feature it would be nice if someone could add an option to disable it.

### What is the feature you are proposing to solve the problem?

Adding an options to the values to disable the auth delegator resources

### What alternatives have you considered?

disabling rbac and creating the role bindings myself.

Note: I got no clue about how helm charts work internally. It would be nice if someone else could provide this feature

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by ChristianRaoulis** [comment]
> The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

Offering a way to disable the auth delegator (and all related resources) when it is unused or unwanted still seems to be a nice to have feature for the vault helm chart in my opinion.

Hashicorp offers this functionallity in their [helm chart](https://github.com/hashicorp/vault-helm/tree/main) since almost 2 years.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Charismara** [comment]
*bump*
This feature would still be a nice improvement and it would be great if someone could take on the implementation.

**Comment by Charismara** [comment]
Adding a comment doesn't count as activity?
