### ISSUE TITLE
[bitnami/keycloak] KC_HOSTNAME_ADMIN_URL seems incorrect in proxy=edge

### ISSUE THREAD

**Issue by singhbaljit** [bitnami/charts#27315]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy Keycloak chart with proxy mode `edge`.
2. Enable ingress (and TLS termination) with nginx (could be any ingress controller)
3. Go to admin page, and click on the `Administration Console`
4. Get an error that the `redirect_uri` is incorrect.

### Are you using any custom parameters or values?

```
proxy: edge

ingress.enabled: true
ingress.ingressClassName: ngnix
ingress.hostname: "auth.something.com"

adminIngress.enabled: true
adminIngress.ingressClassName: ngnix
adminIngress.hostname: "admin.something.com"
```

### What is the expected behavior?

It should take you to the login page correctly. However, it does not because the `KC_HOSTNAME_ADMIN_URL` value uses `http`, where as the redirect_uri (correctly) has the `https`.

### What do you see instead?

Error that the redirect_uri is incorrect for admin console.

### Additional information

The issue is [here](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/statefulset.yaml#L216C21-L216C26): 

```yaml
            - name: KC_HOSTNAME_ADMIN_URL
              value: "http{{ if .Values.adminIngress.tls }}s{{ end }}://{{ include "common.tplvalues.render" (dict "value" .Values.adminIngress.hostname "context" $) }}"
```

It switches to HTTPS only when the TLS is enabled. It should also be HTTPS in `edge` proxy mode.

There are some related issues that may impact this issue as well, namely #25963 and #26175.

**Comment by singhbaljit** [comment]
I just realized this was recently added in #25386.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by singhbaljit** [comment]
@carrodher please have a look at #27436.
