### ISSUE TITLE
[bitnami/apisix] JSONSchema too strict for extraEnvVars

### ISSUE THREAD

**Issue by james-mchugh** [bitnami/charts#27319]
### Name and Version

bitnami/apisix:3.1.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set `.Values.dataPlane.extraEnvVars` to a string (containing Helm templating, for example)
2. Run `helm template .`
3. Observe error due to JSON schema validation

### Are you using any custom parameters or values?

```yaml
dataPlane:
  extraEnvVars: |-
      {{- include "my-chart.apisix.authEnvs" . }}
```

### What is the expected behavior?

`dataPlane.extraEnvVars` allows for strings as the value is passed to the `common.tplvalues.render` template function prior to being added to the deployment/daemonset.

### What do you see instead?

```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
apisix:
- dataPlane.extraEnvVars: Invalid type. Expected: array, given: string
```

### Additional information

There may be additional fields with similar issues.

I took a look at the Bitnami Postgresql chart, which omits `extraEnvVars` fields from the JSON schema. Other charts may handle this differently though.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by james-mchugh** [comment]
Sure thing. I can put a PR together for this.

**Comment by james-mchugh** [comment]
PR opened!

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by james-mchugh** [comment]
Hello @carrodher . Sorry to bug you about this, but do you have a timeline for when the PR might be reviewed by? I'm more than happy to reduce the changes if that will help with the review. I'm just hoping to not have to continue forking the chart for too long to get around a simple JSON schema validation issue.

**Comment by carrodher** [comment]
Hi @james-mchugh, thank you for your contribution! We truly appreciate your effort and interest in improving the _bitnami/apisix_ chart.

Our team currently has a high volume of Issues and Pull Requests to review. Please be assured that we are doing our best to get to yours as soon as possible. We appreciate your patience and understanding.
