### ISSUE TITLE
[bitnami/vault] RBAC Rules for Vault

### ISSUE THREAD

**Issue by ChristianRaoulis** [bitnami/charts#27314]
### Name and Version

bitnami/vault 1.4.7

### What is the problem this feature will solve?

I'm using Cyberark Conjur in my K8s Plattform and need to bind an extra role to the service account which allows the account to read the k8s secret.

### What is the feature you are proposing to solve the problem?

Adding the `server.rbac.rules` option to the chart

**Comment by Charismara** [comment]
*bump*
This feature would still be a nice improvement and it would be great if someone could take on the implementation.

**Comment by Charismara** [comment]
Adding a comment doesn't count as activity?
