### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] INSTALLATION FAILED: "rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator" already exists

### ISSUE THREAD

**Issue by mrlioncub** [bitnami/charts#27322]
### Name and Version

bitnam/rabbitmq-cluster-operator 4.3.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install with watchAllNamespaces=false:
```
helm install rabbitmq-cluster-operator bitnami/rabbitmq-cluster-operator --set clusterOperator.watchAllNamespaces=false --set clusterOperator.watchNamespaces={rabbitmq}  --set msgTopologyOperator.watchAllNamespaces=false --set msgTopologyOperator.watchNamespaces={rabbitmq}
```

### Are you using any custom parameters or values?

```
--set clusterOperator.watchAllNamespaces=false --set clusterOperator.watchNamespaces={rabbitmq} \
--set msgTopologyOperator.watchAllNamespaces=false --set msgTopologyOperator.watchNamespaces={rabbitmq}
```

### What do you see instead?

Error: INSTALLATION FAILED: 1 error occurred:
        * rolebindings.rbac.authorization.k8s.io "rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator" already exists

**Comment by fmulero** [comment]
Hi @mrlioncub, thanks for using bitnami/charts and sharing this issue.

I've just reproduced the problem and it is related with the size of the names for the role bindings here:
https://github.com/bitnami/charts/blob/d78148f0fa81232fe7cb847b8bfe3d3a500a79e0/bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrolebinding.yaml#L30-L34

The template `include "rmqco.msgTopologyOperator.fullname" $` return in your example the name `rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator` which already have 63 characters. As workaround you could use a shorter name for your release, something like `rmqco` could fit

**Comment by mrlioncub** [comment]
Thanks. A shorter name works!
