### ISSUE TITLE
multus broken

### ISSUE THREAD

**Issue by kfox1111** [bitnami/charts#27320]
### Name and Version

bitnami/multus-cni 2.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

install it. delete a multus-cni daemonset pod, look at `00-multus.conf` on its host

You get nested type:multus sections in delegates, and things break.

### What is the expected behavior?

calico config is delegated into multus config without extra multus delegates.

### What do you see instead?

extra multus delegates that break things.

**Comment by kfox1111** [comment]
I would love to help, but I have no idea how the binaries are produced. Could you please point me at their source and build scripts so I can debug further?

**Comment by carrodher** [comment]
That would be nice. The container image script and logic are placed at https://github.com/bitnami/containers/tree/main/bitnami/multus-cni

**Comment by kfox1111** [comment]
I don't follow.
https://github.com/bitnami/containers/blob/main/bitnami/multus-cni/4/debian-12/Dockerfile#L35  just points to what looks like are prebuilt images. 

How are they built? Where does the source come from?

I straced the binaries and I don't see them following the code from the multus-cni released tarballs. The binaries are different from the multus-cni project's builds. So, not sure how to debug further.

**Comment by carrodher** [comment]
Those intermediate packages are the result of downloading the upstream source code (in this case from https://github.com/k8snetworkplumbingwg/multus-cni/releases) and compiling it, in that sense, the upstream source code is not modified.

Then, that intermediate package is included in the _Dockerfile_ to build the container image and later the Helm chart.

What are the differences you're finding between binaries?

**Comment by kfox1111** [comment]
I hit this issue with the chart:
https://github.com/k8snetworkplumbingwg/multus-cni/issues/353

Was trying to dig through the code to understand why the strace doesn't seem to follow the behavior of the binary doesnt seem to match the code. Then wasn't finding the exact code that the containers were using.

I just found this:
https://github.com/k8snetworkplumbingwg/multus-cni/commit/633985d82fd700a7f6ebdbb6dd1f529307ed4260

which doesn't look like it is in the 4.0.2 release?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by kfox1111** [comment]
Its not directly related to the chart, no. But it is also a major problem for the chart, as its broken when you helm install it.

It looks like at the moment the thin plugin upstream is broken in their released version. Switching to support the thick plugin may help fix the chart.

**Comment by kfox1111** [comment]
still a problem, not solved.

**Comment by kfox1111** [comment]
Could someone bump up the version to the newest release? It should have some fixes for this.

**Comment by javsalgar** [comment]
Hi,

There is an automated PR that is currently failing, we are checking it https://github.com/bitnami/charts/pull/28775
