### ISSUE TITLE
[bitnami/mariadb] Add support for setting pod labels

### ISSUE THREAD

**Issue by GCHQDeveloper926** [bitnami/charts#2735]
**Which chart**:
MariaDB

**Is your feature request related to a problem? Please describe.**
I am trying to set pod labels so I can run KubeMonkey in my cluster

**Describe the solution you'd like**
Similar to https://github.com/bitnami/charts/issues/1873 I'd like to add support for setting podLabels in a similar way to how annotations are done. 

**Describe alternatives you've considered**
Labelling deployments after they are deployed to my cluster but that is a bit of a pain, would be easier to support this in the chart, similar to how some of the other charts are doing this.

**Additional context**
I'm happy to raise a PR for this if you'd be happy for that to happen!
@juan131 I know you commented on the issue I've tagged above, would you be happy for this to happen on the MariaDB as well?

**Comment by marcosbc** [comment]
Hi @GCHQDeveloper926! You're right, currently the MariaDB chart is missing that. We would really appreciate if you contribute and send the PR, we'll be happy to review it. Thanks!

**Comment by GCHQDeveloper926** [comment]
Great, I'll get started on this!
