### ISSUE TITLE
[Bitnami/redis-cluster] Add PodDisruptionBudget to template

### ISSUE THREAD

**Issue by QwertyQaz414** [bitnami/charts#2741]
Hi,

I can't seem to find a PDB field option for redis-cluster. Am I missing something? It would be very useful to have one!

**Comment by joancafom** [comment]
Hi @QwertyQaz414 

That would be a nice feature to have for sure. We will consider your request into account so as to enhance our Chart, but I can't give you an exact ETA at the moment. However, if you would like to contribute, you can send us a PR with the changes and we will be more than happy to review and include them!

Thanks!
