### ISSUE TITLE
[bitnami/mongodb-sharded] Capacity to create non-root users on chart installation

### ISSUE THREAD

**Issue by tschneider-aneo** [bitnami/charts#27422]
### Name and Version

bitnami/mongodb-sharded 8.2.3

### What is the problem this feature will solve?

Capacity to query MongoDB in a more secure way

### What is the feature you are proposing to solve the problem?

Add an option that would create classical, non-root user(s) for MongoDB.

### What alternatives have you considered?

Add a init or post-init script that would create non-root user(s), but I don't think that should be done this way when using Helm chart as it is already an available feature with the classical non-sharded MongoDB Helm chart

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
