### ISSUE TITLE
[bitnami/postgresql] k8s 1.27.0 problem with tolerate-unready-endpoints

### ISSUE THREAD

**Issue by M-A-X-I-M** [bitnami/charts#27435]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

As we upgraded our k8s to version 1.27.0, we got this error:
![grafik](https://github.com/bitnami/charts/assets/84561681/cff0342a-7475-4465-8a1b-8518e1ee72e9)

### What is the feature you are proposing to solve the problem?

The unready-endpoints annotations need to be removed to solve this in this file:
https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/primary/svc-headless.yaml
because the matrix-synapse is using this helm chart as depedencie

**Comment by rafariossaa** [comment]
Which k8s version were you using previously ?
Are you upgrading the chart too ? if so, indicate the version from and to used.
BTW, I noticed that k8s 1.27 is close to [EOL (2024-06-28)](https://kubernetes.io/releases/).

**Comment by M-A-X-I-M** [comment]
> Which k8s version were you using previously ? Are you upgrading the chart too ? if so, indicate the version from and to used. BTW, I noticed that k8s 1.27 is close to [EOL (2024-06-28)](https://kubernetes.io/releases/).
we are using CCE in open telekom cloud this is why our k8s version is always lower
