### ISSUE TITLE
Missing liblog.sh file in rabbitmq initContainers

### ISSUE THREAD

**Issue by pierrefoyard** [bitnami/charts#27443]
### Name and Version

bitnami/rabbitmq:14.3.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Start a pod based on bitnami/rabbitmq:14.3.2 chart and rabbitmq:3.13.3 docker image.
It leads to an error message at initContainers stage:
`"/bin/bash: line 3: /opt/bitnami/scripts/liblog.sh: No such file or directory" `

If I use same image with a chart version older than this commit https://github.com/bitnami/charts/commit/a3c7c6e5bc685b2587a6302770e20c6890ebd72d I can then start my pod and connecting in it I observe that liblog.sh is not existing in my container

### What do you see instead?

"/bin/bash: line 3: /opt/bitnami/scripts/liblog.sh: No such file or directory"

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
