### ISSUE TITLE
[bitnami/apisix] Apisix ETCD going into Crash loop back off

### ISSUE THREAD

**Issue by Lakshmi2k1** [bitnami/charts#27444]
### Name and Version

bitnami/etcd 10.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello,
I have deployed apisix 2.7.0 Helm chart and out of three etcd pods, two are going into crash loop back off error which affects the ingress created for other deployments.

![image](https://github.com/bitnami/charts/assets/59364250/de31a0b4-2234-4911-90bc-515ad6e3f3a9)
The logs show the following details,

Master (etcd pod in running state)
```
"msg":"rejected stream from remote peer because it was removed","local-member-id"
```

Other pods (etcd pods in crash loop back off state)
```
"failed to publish local member to cluster through raft","local-member-id":"2c16fb63879f0d98","local-member-attributes":"{Name:apisix-etcd-1 ClientURLs:[http://apisix-etcd-1.apisix-etcd-headless.apisix.svc.cluster.local:2379/ http://apisix-etcd.apisix.svc.cluster.local:2379]}","request-path":"/0/members/2c16fb63879f0d98/attributes","publish-timeout":"7s","error":"etcdserver: request cancelled"
```
Currently stuck in this, let me know if anyone has faced this and has any fix for this

### What do you see instead?

The pod keeps restarting

**Comment by javsalgar** [comment]
Hi,

Did you check if there were PVCs from previous deployments?
