### ISSUE TITLE
charts.bitnami.com provider DNSSEC configuration invalid

### ISSUE THREAD

**Issue by nethershaw** [bitnami/charts#27452]
### What steps will reproduce the bug?

1. Attempt `helm repo add bitnami https://charts.bitnami.com/bitnami` on a machine using a DNSSEC-enabled resolver.
2. Unreachable: DNS resolution failure.

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

`"bitnami" has been added to your repositories`

### What do you see instead?

```
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://repo.broadcom.com/bitnami-files/index.yaml": dial tcp: lookup repo.broadcom.com on 127.0.0.1:53: server misbehaving
```

### Additional information

The Helm repository charts.bitnami.com dereferences to repo.broadcom.com, but the entire broadcom.com domain is configured incorrectly: its DNSSEC implementation uses the SHA-1 hash algorithm, which is no longer allowed, and which strictly prevents any DNSSEC-enabled resolvers accessing the site. This is common in enterprise environments, and is unnecessarily complicating a deployment in mine.

Evidence: https://dnsviz.net/d/repo.broadcom.com/dnssec/

The repository maintainers here must contact the repository service provider (Broadcom) and instruct them to migrate their DNSSEC implementation to the use of a modern hash algorithm.

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. We will redirect this issue internally and keep this thread updated with any news.
