### ISSUE TITLE
[bitnami/grafana-loki] promtail secret should not be created if existingSecret is specified

### ISSUE THREAD

**Issue by ib-ak** [bitnami/charts#27464]
### Name and Version

bitnami/grafana-loki 4.6.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Provide existing secret name in .`Values.promtail.existingSecret`

### What is the expected behavior?

A new secret should not be created

### What do you see instead?

New secret is created

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
