### ISSUE TITLE
[bitnami/mongodb] Missing backup retention option

### ISSUE THREAD

**Issue by jani888** [bitnami/charts#27461]
### Name and Version

bitnami/mongodb 15.0.2

### What is the problem this feature will solve?

There is a feature in the `bitnami/mongodb` chart for creating regular backups using a cronjob. This works well, except there is no option to set the retention limit (in days of storage size). Because of this, the PVC will get full eventually. 

### What is the feature you are proposing to solve the problem?

There should be some kind of retention attribute for setting the backup retention

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
