### ISSUE TITLE
[bitnami/airflow] Support alternative broker to Redis 

### ISSUE THREAD

**Issue by ChristianRaoulis** [bitnami/charts#27473]
### Name and Version

bitnami/airflow 18.3.4

### What is the problem this feature will solve?

I'm currently using RabbitMQ and Redis Sentinel in my Tech Stack which could both be used as broker for celery (or airflow) but the helm chart only allows me to use redis due to how the config get's created in `libairflow.sh` (see [here](https://github.com/bitnami/containers/blob/main/bitnami/airflow-worker/2/debian-12/rootfs/opt/bitnami/scripts/libairflow.sh#L404)). I would need to create a custom config which would complicate the deployment or let the chart set up another redis which would waste compute resources.

### What is the feature you are proposing to solve the problem?

It would be very nice if the helm chart would support different broker types (Redis, Redis Sentinel, RabbitMQ)

### What alternatives have you considered?

Creating a custom deployment instead of using the helm chart

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by ChristianRaoulis** [comment]
*bump*
This feature would still be a nice improvement and it would be great if someone could take on the implementation.
