### ISSUE TITLE
The index file has over 15MB again

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#27470]
The index file at https://repo.broadcom.com/bitnami-files/index.yaml has over 15MB again, and we're getting 
```
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://repo.broadcom.com/bitnami-files/index.yaml": EOF
```

Is the size expected or is there some problem with the pruning of the index? 

Thank you

_Originally posted by @Moglum in https://github.com/bitnami/charts/issues/10539#issuecomment-2180143363_

**Comment by Moglum** [comment]
The EOF error was caused by our firewall blocking `repo.broadcom.com` - has the location of the repo index file changed recently? We haven't seen this problem before as we had a rule allowing `charts.bitnami.com`
 
We are now able to pull charts from the repo, but index size is still a bit concerning.

**Comment by carrodher** [comment]
We are not currently trimming the _index.yaml_ file as there have been no recent issues related to its size. However, the policy has been announced, and users should be aware that if any issues arise, we will trim the file accordingly.

Please note that the recommended way to consume Bitnami charts is from the [DockerHub OCI registry](https://hub.docker.com/u/bitnamicharts).

As you rightly pointed out, this should not be the cause of the error. We recently changed the location from which the _index.yaml_ is served. The new location is `https://repo.broadcom.com/bitnami-files/index.yaml`.

**Comment by Moglum** [comment]
I will look into switching to the OCI registry instead.


I believe we can close this one, as there are no outstanding problems or questions on my end. Thanks
