### ISSUE TITLE
Jenkins chart has incompatible configuration-as-code plugin 

### ISSUE THREAD

**Issue by mike12806** [bitnami/charts#27487]
### Name and Version

bitnami/jenkins 5.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install chart
2. Init pod fails to start with the following error:
```
Git plugin 4.3.0 requires configuration-as-code configuration-as-code:1810.v9b_c30a_249a_4c but found configuration-as-code:1569.vb_72405b_80249
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The chart includes compatible plugin values 

### What do you see instead?

Plugins are not on compatible values

**Comment by migruiz4** [comment]
Hi @mike12806,

I'm sorry but '5.3.0' is not a correct version for the `bitnami/jenkins` chart.

Could you please provide a correct version so we can try to reproduce the issue? I tried using the latest version (`13.4.8`) and wasn't able to reproduce the issue.

Additionally, freshly installed bitnami/jenkins chart, without previously existing PVCs and no custom value should not install any plugins.

**Comment by mike12806** [comment]
My bad - I was previously pulling the bitnami jenkins chart but the current chart i'm using is apparently from Jenkins directly. I will close this and apologize for the inconvenience.
