### ISSUE TITLE
Missing customization of annotations in pod template section for Kafka Exporter

### ISSUE THREAD

**Issue by ishfid4** [bitnami/charts#2748]
**Which chart**:
Kafka chart.

**Describe the bug**
Kafka exporter deployment changed, therefore there is no possibility to add custom pod annotations in section _spec.template.metadata.annotations_ . I've noticed that in versions 9.0.0+. Previously this possibility was present since version 7.4.0
In order to use DataDog auto-discovery feature (https://docs.datadoghq.com/agent/autodiscovery/), there must be annotations added to "Pod Template" section in kubernetes deployment.yaml. This will cause all pods created will have these annotations added. #2062 and #2036 
Previously,  when it was working, to add such annotations I could specify parameters in values file for deployment. I.e.:
```
metrics:
  kafka:
    enabled: true
    podAnnotations:
      ad.datadoghq.com/kafka-exporter.check_names: '["openmetrics"]'
      ad.datadoghq.com/kafka-exporter.init_configs: '[{}]'
      ad.datadoghq.com/kafka-exporter.instances: |
        [{
             "prometheus_url": "http://%%host%%:9308/metrics",
             "namespace": "MyApplication",
             "metrics": ["*"]
        }]
```

**Expected behavior**
After specifying in parameters file, section about annotation in pod template metadata, deployed kafka exporter will have set those annotations. I assume that changes regarding this should be done in _**kafka-metrics-deployment.yaml**_ file, between line 21 and 22.

**Comment by rafariossaa** [comment]
Hi,
  If you want add annotations to the metrics pods, as the example you gave, you need to enable the metrics and provide the annotations values.
  Could you try using version 10 of the chart and the following diff ?
```diff
610c610
<     enabled: false
---
>     enabled: true
680a681,688
>         ad.datadoghq.com/kafka-exporter.check_names: '["openmetrics"]'
>         ad.datadoghq.com/kafka-exporter.init_configs: '[{}]'
>         ad.datadoghq.com/kafka-exporter.instances: |
>           [{
>              "prometheus_url": "http://%%host%%:9308/metrics",
>              "namespace": "MyApplication",
>              "metrics": ["*"]
>           }]
```
The I can see it is generated in the resulting yaml.
```
$ helm template -f values.yaml_modified  . | grep datadog
    ad.datadoghq.com/kafka-exporter.check_names: '["openmetrics"]'
    ad.datadoghq.com/kafka-exporter.init_configs: '[{}]'
    ad.datadoghq.com/kafka-exporter.instances: |
```
