### ISSUE TITLE
[bitnami/redis] Redis pod going into "Succeeded" state after some time 

### ISSUE THREAD

**Issue by tomas-stary-work** [bitnami/charts#27486]
### Name and Version

bitnami/redis 19.5.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.) Update Redis helm chart from 17.1.2 (7.0.4) to 19.5.0 (7.2.5)
2.) Pods will run for some time then go into succeeded state
3.) Delete pods in succeeded state and cluster returns to normal

### Are you using any custom parameters or values?

YES

### What is the expected behavior?

The pod should never enter the successful state and should continue running

### What do you see instead?

After some time, the pod switches to successful status.

### Additional information

- Kubernetes versions 1.28.3
- It's definitely related to the load on redis. However, redis only took up 1GB of RAM and was set to more than 20GB, so it won't be memory. I'm not sure if some connections are missing. Unfortunately, this happened to me on the PRODUCTION cluster and I can't reproduce the problem on the test cluster. I had to do a rollback of the redis helm chart version on the production cluster.
- Same behavior as in issue which is closed [here](https://github.com/bitnami/charts/issues/23405).

**Comment by javsalgar** [comment]
Hi!

Could you share the logs of the pods that are running into Succeeded? Could you perform the upgrade with image.debug=true?

**Comment by tomas-stary-work** [comment]
There was nothing unusual about the logs. In addition, I tried turning on debug, which changed the value of the env variable BITNAMI_DEBUG=true in the pod, but I did not record any additional information in the logs.

**Comment by javsalgar** [comment]
Please let me know if you are able to reproduce so we can reproduce too
