### ISSUE TITLE
[bitnami/redis] Call failover while gracefull shutdown of master

### ISSUE THREAD

**Issue by dm3ch** [bitnami/charts#2749]
**Which chart**:
bitnami/redis 10.6.18

**Is your feature request related to a problem? Please describe.**
When you are gracefull killing redis pod that is current master, election of new master starts only after configured timeout.

**Describe the solution you'd like**
I think it would be a good idea to add preStop hook for all sentinel containers. It should check if pod is actual master and trigger failover via `sentinel failover` command and wait until new master would be elected. Script should exit only after new master election (and maybe syncing needed amount of replicas) to provide flowless experience when k8s nodes is drained for maintanance.

**Describe alternatives you've considered**

**Additional context**

**Comment by WarheadsSE** [comment]
This was bumped into while exploring turning on native `bitnami/redis` dependency with Sentinels @ https://gitlab.com/gitlab-org/charts/gitlab/-/issues/2132#note_353985755

**Comment by miguelaeh** [comment]
Hi @dm3ch ,
Thank you very much for your suggestion,
would you like to open a PR for that feature? We will be pleased to review it.

**Comment by dm3ch** [comment]
I'll try to create PR with adding such logic

**Comment by miguelaeh** [comment]
Thank you very much!

**Comment by dm3ch** [comment]
reopen
