### ISSUE TITLE
[bitnami/apisix] missing ingressClass resource KIND 

### ISSUE THREAD

**Issue by w0aw** [bitnami/charts#27502]
### Name and Version

bitnami/apisix:3.2.5

### What is the problem this feature will solve?

current chart doesn't create ingressClass for ingressController.

i am not sure weather i have to manually enable it. but i haven't find any key in default values file.

### What is the feature you are proposing to solve the problem?

having ingress controller without ingressClass doesn't make sense. please correct me if i am wrong

### What alternatives have you considered?

possible solution, [here](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/templates/ingress-class.yaml)

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. In our testing we were able to verify apisix without the ingress class, but it makes sense to follow the upstream behavior and deploy an ingress class. As you discovered the issue, would you like to submit a PR including the ingress class?

**Comment by w0aw** [comment]
@javsalgar thanks for asking but i am not confident with helm chart variable sharing and inter file connection.

**Comment by juan131** [comment]
@w0aw thanks for reporting this issue! I just created a PR to address it
