### ISSUE TITLE
[external-dns] Automatic creation of secret for Cloudflare is broken

### ISSUE THREAD

**Issue by ggillies** [bitnami/charts#2751]
**Which chart**:
external-dns chart version 3.1.1

**Describe the bug**
When you attempt to use the cloudflare provider, and pass `cloudflare.email` and `cloudflare.apiKey` through use of helm values, you get a secret created by the chart, but the deployment doesn't use it.

**To Reproduce**

* Create a values file with the following
```yaml
provider: cloudflare
cloudflare:
  email: someone@something.com
  apiKey: someApiKey
```
* Use helm diff to see what will get created
```
helm diff upgrade --allow-unreleased external-dns bitnami/external-dns -f values.yaml
```

* Observe that the diff output shows your `someApiKey` being set as an environment variable on the deployment (leaking it), and the deployment is not using the secret object created by the chart. Also note that the chart does create a secret object (although not used)

**Expected behavior**
That the deployment object would reference the secret object that the chart creates, and the deployment output does not have `someApiKey` in plain text

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

Looks like regression was introduced in https://github.com/bitnami/charts/pull/2572/

**Comment by joancafom** [comment]
Hi @ggillies 

I have been able to reproduce your issue and successfully checked that both `apiKey` and `apiToken` were susceptible to plaintext printing in the resulting output. I will implement changes to change this behaviour and use the secret that is already created. 

Thanks for your reporting!
