### ISSUE TITLE
[bitnami/mongodb]   when  start mongodb livenessProbe hang

### ISSUE THREAD

**Issue by zxcasongs** [bitnami/charts#27538]
### Name and Version

bitnami/mongodb 5.0.8

### What is the problem this feature will solve?

Yesterday, I disabled the public network on the server and found that the pod could not start normally. When I entered the server and executed the livenessProbe script /bitnami/scripts/ping-mongodb.sh, I discovered it was hanging. Then, I performed packet capture on the server and found requests to api.segment.io and ec2-35-166-226-67.us-west-2.compute.amazonaws.com. After allowing access to these two addresses, the livenessProbe script worked normally. I would like to ask why these two addresses need to be requested.
![企业微信截图_41020422-2402-41c4-b74d-9d8684adaa92](https://github.com/bitnami/charts/assets/35259607/be97da1f-31d0-49d2-85df-e9e18d7217be)
![企业微信截图_4318613f-13e0-46c9-88bf-0857032111b0](https://github.com/bitnami/charts/assets/35259607/0a8b7146-e5a0-433c-b04a-71bfd8495eb9)
![企业微信截图_17392b12-0b3b-489e-8654-cd2262b3534e](https://github.com/bitnami/charts/assets/35259607/5dda407e-66aa-4a84-8c5a-dc6d22ff914c)

### What is the feature you are proposing to solve the problem?

To run MongoDB on an internal network

**Comment by horihel** [comment]
that's mongosh phoning home - see #25157

**Comment by zxcasongs** [comment]
Thank you, I understand now. You are my hero, but it looks like there isn't a solution.

**Comment by zxcasongs** [comment]
> that's mongosh phoning home - see #25157

Thank you, I understand now. You are my hero, but it looks like there isn't a solution.

**Comment by javsalgar** [comment]
Thank you for adding the solution! I believe that's something to be reported to the mongosh devs.
