### ISSUE TITLE
[bitnami/kafka] jmx-metrics servicemonitor has wrong path

### ISSUE THREAD

**Issue by horihel** [bitnami/charts#27546]
### Name and Version

bitnami/kafka-29.3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install kafka with `metrics.jmx.enabled=true` and `metrics.serviceMonitor.enabled=true`
2. prometheus-operator will pick up the new service
3. target reports as _DOWN_ in prometheus with error `expected a valid start token, got "<" ("INVALID") while parsing: "<"`

### Are you using any custom parameters or values?

`--set metrics.jmx.enabled=true --set metrics.serviceMonitor.enabled=true`

### What is the expected behavior?

prometheus being able to scrape metrics

### What do you see instead?

`expected a valid start token, got "<" ("INVALID") while parsing: "<"`

### Additional information

It looks like the recent upgrade to jmx-metrics 1.0 changed the path which metrics are exposed. jmx-exporter no longer exposes metrics on the root path, instead, they are exposed on `/metrics`

I think this can be easily solved by changing the path in the [serviceMonitor](https://github.com/bitnami/charts/blob/80fcadce0160f2ee7df08d7523f7a886beeab64c/bitnami/kafka/templates/metrics/jmx-servicemonitor.yaml#L30) to `/metrics` instead of `/`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by horihel** [comment]
PR is ready for review.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
