### ISSUE TITLE
[bitnami/mysql]: How to perform mysql backup

### ISSUE THREAD

**Issue by cwrx777** [bitnami/charts#27555]
### Name and Version

bitnami/mysql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is not a but a question on how to perform sqlbackup for db deployed using this chart. 
I intend to use [percona xtrabackup](https://www.percona.com/mysql/software/percona-xtrabackup).
I would imagine that the percona xtrabackup is run in another pod in the same namespace.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
