### ISSUE TITLE
[bitnami/kafka] Unable to set sasl scram-sha-512 username and password

### ISSUE THREAD

**Issue by ashwanthkumar** [bitnami/charts#27566]
### Name and Version

bitnami/kafka 29.3.4

### What architecture are you using?

None

### What steps will reproduce the bug?

The file as part of https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/_helpers.tpl#L605-L612 only seems to support adding the client.users and their password only for PLAIN types and not for SCRAM types. I know from #41415 that the controller doesn't support SCRAM but only PLAIN types but seems like the code applies that for client types as well.

### What is the expected behavior?

The user and password placeholder should be applied even for scram login modules.

### What do you see instead?

```
# Listeners SASL JAAS configuration
listener.name.client.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required user_user=\"password-placeholder-0\";
listener.name.client.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
listener.name.client.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
listener.name.internal.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"inter_broker_user\" password=\"interbroker-password-placeholder\" user_inter_broker_user=\"interbroker-password-placeholder\" user_user=\"password-placeholder-0\";
listener.name.internal.scram-sha-256.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=\"inter_broker_user\" password=\"interbroker-password-placeholder\";
listener.name.internal.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=\"inter_broker_user\" password=\"interbroker-password-placeholder\";
# End of SASL JAAS configuration"
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
