### ISSUE TITLE
[bitnami/elasticsearch] How do I disable overwriting the custom image plugins directory

### ISSUE THREAD

**Issue by liuxin638507** [bitnami/charts#27582]
### Name and Version

bitnami/elasticsearch:8.14.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

My custom image has been into `/opt/bitnami/elasticsearch/plugins`, but I helm after install, into the container `/opt/bitnami/elasticsearch/plugins` directory into an empty directory, I want to use my custom plugins, could you tell me how to disable `/opt/bitnami/elasticsearch/plugins` are covered

### What do you see instead?

I can't comment values.yaml line, the container plugins are still empty

**Comment by carrodher** [comment]
Can you take a look at the [plugins section](https://github.com/bitnami/containers/tree/main/bitnami/elasticsearch#plugins) in the container doc?

**Comment by liuxin638507** [comment]
> Can you take a look at the [plugins section](https://github.com/bitnami/containers/tree/main/bitnami/elasticsearch#plugins) in the container doc?

I have looked at it and customized a new image for the required plugins. The name of the plugins is entered in values. yaml, but I couldn't find the option to disable plugins or not to overwrite my customized plugins

**Comment by jotamartos** [comment]
Hi @liuxin638507,

If you are creating a custom image with your plugins, you need to include them in the "DB_DEFAULT_PLUGINS_DIR" folder. That folder is /opt/bitnami/elasticsearch/plugins.default and it's later copied to the plugins volume

https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/master/statefulset.yaml#L151

Could you please try that and let us know if that resolves the issue? 

Thanks

**Comment by liuxin638507** [comment]
> Hi @liuxin638507,
> 
> If you are creating a custom image with your plugins, you need to include them in the "DB_DEFAULT_PLUGINS_DIR" folder. That folder is /opt/bitnami/elasticsearch/plugins.default and it's later copied to the plugins volume
> 
> https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/master/statefulset.yaml#L151
> 
> Could you please try that and let us know if that resolves the issue?
> 
> Thanks

Placed in/opt/bitnami/elasticsearch/plugins. The default directory is ok, thank you very much, although when es start copy to plugins volume directory, feeling a bit low efficiency, if the custom plug-in, is relatively slow

**Comment by jotamartos** [comment]
>although when es start copy to plugins volume directory

That's done due to security reasons. You can learn more about it in this PR 

https://github.com/bitnami/charts/pull/23779

**Comment by liuxin638507** [comment]
> > 虽然当 es 开始复制到插件卷目录时
> 
> 这样做是出于安全原因。您可以在此 PR 中了解更多信息
> 
> #23779

Ok, thank you very much!
