### ISSUE TITLE
Kafka Exporter Deployment requires $NAME-jaas secret even when auth is disabled

### ISSUE THREAD

**Issue by st0ckface** [bitnami/charts#2758]
**Which chart**:
bitnami/kafka

**Describe the bug**
The kafka-exporter-deployment template doesnt have any ability to remove a requirement on the $NAME-jass secret for the `SASL_USER_PASSWORD` environment variable, even when auth is not being used.

**To Reproduce**
`helm install kafka bitnami/kafka  --set metrics.kafka.enabled=true`
Notice that the pod created for the kafka metrics exporter is status `CreateContainerConfigError` with an event: `Error: secret "kafka-jaas" not found`

**Expected behavior**
A way to remove the dependency on the secret from the chart.

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
I thanks for filling this issue, I will take a look and update this thread in a couple of days

**Comment by carrodher** [comment]
Hi @st0ckface, the issue should be fixed with the above PR (thanks @juan131 for the changes). We are waiting for our internal tests and release pipeline. Once released, the PR will be merged and this issue closed automatically, but please, don't hesitate to reopen it if needed.
