### ISSUE TITLE
bitnami/kafka KAFKA-UI feature support

### ISSUE THREAD

**Issue by KorenP1** [bitnami/charts#27599]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

kafka-ui support inside the helm chart of kafka + connecting with the kafka and using the jmx metrics

### What is the feature you are proposing to solve the problem?

Needed kafka-ui support

### What alternatives have you considered?

i have used another helm chart and combined the values

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
