### ISSUE TITLE
Example how to set up GRPC+HTTP at the same domain for argo-cd with ALB ingress controller

### ISSUE THREAD

**Issue by zentavr** [bitnami/charts#27594]
### Name and Version

bitnami/argo-cd 6.4.8

### What is the problem this feature will solve?

The chart provides 2 ingress setting in the values for ArgoCD server:
- server.ingress
- server.ingressGrpc

Is there any example how to set up this with ALB controller using annotations at the same domain and ALB?
[ArgoCD Manual](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode) proposes to have another service for that.

### What is the feature you are proposing to solve the problem?

Help users to set up argoCD in AWS

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! At this moment there is not such documentation about that specific use case. If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by zentavr** [comment]
Right now I’m using the single ALB and argoncd cli works with the warning.

**Comment by zentavr** [comment]
Actually the issue is not solved and solution is not provided.
