### ISSUE TITLE
APISIX doesn't see environment variables

### ISSUE THREAD

**Issue by ahmsay** [bitnami/charts#27593]
### Name and Version

bitnami/apisix:3.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In AWS EKS, I am trying to use bitnami apache apisix helm chart. The dataplane doesn't see the environment variables. The environment variables exist when i look inside the container but it behaves like they don't exist and says it cannot find it.

### Are you using any custom parameters or values?

My helm chart:  https://github.com/ahmsay/Solidvessel/blob/master/.kubernetes/environments/prod/apisix/apisix.yaml

My apisix config file: https://github.com/ahmsay/Solidvessel/blob/master/.kubernetes/environments/prod/apisix/apisix-configmap.yaml

The secret containing the environment variable i am trying to inject: https://github.com/ahmsay/Solidvessel/blob/master/.kubernetes/argocd/mainapps/templates/secrets/apisix-secret.yaml

The secret is successfully decrypted and a kubernetes secret is created. And its value is injected inside the dataplane container.

### What is the expected behavior?

A working authentication flow.

### What do you see instead?

I get this error:

```
2024/06/29 06:22:02 [error] 8#8: init_worker_by_lua error: /usr/local/apisix/apisix/plugin.lua:300: failed to load the configuration file: failed to handle configuration: can't find environment variable CLIENT_SECRET
stack traceback:
	[C]: in function 'error'
	/usr/local/apisix/apisix/plugin.lua:300: in function 'get_plugin_names'
	/usr/local/apisix/apisix/plugin.lua:786: in function 'init_worker'
	/usr/local/apisix/apisix/init.lua:145: in function 'http_init_worker'
	init_worker_by_lua:2: in main chunk
```

### Additional information

When i tried the same configuration in my local environment with the official docker image, it works.
I also tried different environment variables or using extraEnvVars instead of extraEnvVarsSecrets but the result is the same.

**Comment by ahmsay** [comment]
Hello @jotamartos,

What step are you referring to?

I am following this page: https://artifacthub.io/packages/helm/bitnami/apisix#additional-environment-variables

Neither extraEnvVars nor extraEnvVarsSecret are working as expected. This time i tried on my local device. I can see the environment variables inside the container when i type ``env``. And I have an environment variable called CLIENT_SECRET that is meant to be injected in my apisix.yaml file. But i have an error and it says that the environment variable is not found (as mentioned above).

Please note that I don't have an error when i use the official image with the same configuration.

**Comment by jotamartos** [comment]
Hi @ahmsay 

>What step are you referring to?

I did a quick test to include a new parameter in the configuration based on the env var and everything worked as expected. I made these changes in the dataPlane object

```
diff --git a/bitnami/apisix/values.yaml b/bitnami/apisix/values.yaml
index 6918ae517b..0fb56c4e65 100644
--- a/bitnami/apisix/values.yaml
+++ b/bitnami/apisix/values.yaml
@@ -343,6 +343,8 @@ dataPlane:
           token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
 
         default_weight: 50 # weight assigned to each discovered endpoint. default 50, minimum 0
+    # Testing line
+    # new-parameter: "{{ print "{{NEW_APISIX_ENV_VAR}}" }}"
   ## @param dataPlane.extraConfig [object] extra configuration parameters to add to the config.yaml file in APISIX Data plane
   ##
   extraConfig: {}
@@ -468,7 +470,9 @@ dataPlane:
   ##   - name: FOO
   ##     value: "bar"
   ##
-  extraEnvVars: []
+  extraEnvVars:
+    - name: NEW_APISIX_ENV_VAR
+      value: "new-value"
   ## @param dataPlane.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for APISIX nodes
   ##
   extraEnvVarsCM: ""
```

and deployed the chart. Once all pods were running, I confirmed that the new parameter was added to the configuration and it used the env var value I configured

```
➜  apisix git:(main) k exec -it apisix-data-plane-79d784b689-cbxz5 -- env | grep -i new                      
Defaulted container "apisix" out of: apisix, wait-for-control-plane (init), prepare-apisix (init)
NEW_APISIX_ENV_VAR=new-value
➜  apisix git:(main) k exec -it apisix-data-plane-79d784b689-cbxz5 -- tail /usr/local/apisix/conf/config.yaml
Defaulted container "apisix" out of: apisix, wait-for-control-plane (init), prepare-apisix (init)
      # apiserver host, options [ipv4, ipv6, domain, environment variable]
      host: ${KUBERNETES_SERVICE_HOST} #default ${KUBERNETES_SERVICE_HOST}
      # apiserver port, options [port number, environment variable]
      port: ${KUBERNETES_SERVICE_PORT} #default ${KUBERNETES_SERVICE_PORT}
    client:
      # serviceaccount token or token_file
      token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    default_weight: 50 # weight assigned to each discovered endpoint. default 50, minimum 0
# Testing line
# new-parameter: "new-value"
```

As you can see, I modified the configuration using the dataPlane.defaultConfig parameter, but you can also mount your own config map and  the prepare-apisix init container will take care of evaluating the configuration and creating the necessary files in the system.

**Comment by ahmsay** [comment]
Hello @jotamartos ,

In your example you modified the config.yaml file. I am trying to modify apisix.yaml file.  Can you try that file as well? Because it doesn't work in my case. Please note that the same configuration works when i use Apisix with single docker container with the official image.

**Comment by ahmsay** [comment]
Hello @jotamartos ,

In your example you modified the config.yaml file. I am trying to modify the apisix.yaml file. I also noticed that after I run ``apisix reload`` command inside the container the error is gone. 

Is there a way to automate this in the helm chart definition, like a post-start lifecycle hook?

**Comment by jotamartos** [comment]
You can mount your apisix.yaml file and make any necessary change in a new initContainer, similar to the changes that I mentioned above. That way, once the container is running, the configuration is the one you expect and do not need to run that extra command. Would that work for you?

As you mention, you can also try setting a lifecycle hook 

https://github.com/bitnami/charts/blob/main/bitnami/apisix/templates/control-plane/dep-ds.yaml#L170

**Comment by ahmsay** [comment]
A lifecycle hook would work for me. Thanks for the clarification.
