### ISSUE TITLE
[bitnami/kafka] Missing jmx exporter probes

### ISSUE THREAD

**Issue by KorenP1** [bitnami/charts#27606]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

While using jmx exporter there is no probes like readiness or liveness in the jmx exporter sidecar container

### What is the feature you are proposing to solve the problem?

Jmx exporter probes

### What alternatives have you considered?

Not that emergency so i am using it without probes

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
