### ISSUE TITLE
bitnami/postgresql pgadmin feature support

### ISSUE THREAD

**Issue by KorenP1** [bitnami/charts#27600]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

adding pgadmin to the helm chart and connecting it to the postgres

### What is the feature you are proposing to solve the problem?

web UI to the postgres

### What alternatives have you considered?

I have used another pgadmin helm chart of non bitnami

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
