### ISSUE TITLE
[bitnami/mongodb] Error parsing YAML config: duplicate key: security.javascriptEnabled

### ISSUE THREAD

**Issue by lasseoe** [bitnami/charts#27604]
### Name and Version

bitnami/mongodb 15.6.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy chart with "disableJavascript: true" then issue `kill 1` within the container (to simulate the process dying or otherwise getting killed).

### Are you using any custom parameters or values?

```yaml
persistence:
  size: 2Gi
disableJavascript: true
```

### What is the expected behavior?

MongoDB should restart without issue.

### What do you see instead?

MongoDB fails to to start and the pod ends in CrashLoopBackOff.
Deleting the pod resolves the issue, in a production system this is however not ideal though.

```
mongodb 14:47:33.41 INFO  ==> ** Starting MongoDB setup **
mongodb 14:47:33.44 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 14:47:33.64 INFO  ==> Initializing MongoDB...
mongodb 14:47:33.89 INFO  ==> Deploying MongoDB with persisted data...
mongodb 14:47:33.91 INFO  ==> ** MongoDB setup finished! **

mongodb 14:47:33.94 INFO  ==> ** Starting MongoDB **
Error parsing YAML config: duplicate key: security.javascriptEnabled
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
Stream closed EOF for mongo-test/mongodb-786d58c747-g9pcq (mongodb)
```

### Additional information

This also happens with a replicaset.

**Comment by lasseoe** [comment]
Not stale, still an issue

**Comment by lasseoe** [comment]
This is still an issue.

**Comment by fmulero** [comment]
Hi @lasseoe Sorry for our late response.

This problem have been fixed on this PR https://github.com/bitnami/containers/pull/70617. In a few hours the chart will be updated with that container image. Could you give it a try?

**Comment by lasseoe** [comment]
Hi Fran,

No worries, we're all busy and have to prioritize.
Thanks a ton for fixing this - I've just tested it, and it appears to work as expected :-)
