### ISSUE TITLE
bitnami/mongodb (mongo-express, or another GUI) feature support

### ISSUE THREAD

**Issue by KorenP1** [bitnami/charts#27601]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

web UI to the mongodb helm chart

### What is the feature you are proposing to solve the problem?

WEB GUI MONGODB

### What alternatives have you considered?

using another helm chart of non bitnami images and helm

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
