### ISSUE TITLE
failed to sync traefik.containo.us/v1alpha1

### ISSUE THREAD

**Issue by kamikaze** [bitnami/charts#27622]
### Name and Version

bitnami/external-dns-8.0.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

This one is not fixed/working:

https://github.com/bitnami/charts/issues/25677

### What do you see instead?
```
time="2024-07-01T19:46:41Z" level=fatal msg="failed to sync traefik.containo.us/v1alpha1, Resource=ingressrouteudps: context deadline exceeded"
```

**Comment by kamikaze** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

done :)

https://github.com/bitnami/charts/pull/27766

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
