### ISSUE TITLE
wp-content cannot be found in destined persistent volume folder but in docker/overlay2

### ISSUE THREAD

**Issue by genughaben** [bitnami/charts#2762]
Sorry if that's not a bug, but a feature... I'd appreciate an explanation nonetheless! Thank you for your help!

**Which chart**:
wordpress App version 9.0.3 used in rancher 2.4.4

**Describe the bug**
When I choose to save data in a persistent volume and persistent volume claim (created local-path-provisioner) the files are not saved in the destined folder, here:

```shell
 /opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress
```

 but in 

```shell
/var/lib/docker/overlay2/5273d32ad25deab85b820da048193e1f94425c6d43ebc901112b87c7398ee75b/merged/opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress/wordpress/wp-content
```

and multiple diff folders.

I want to be sure that the data is not lost, should the cluster / the app/deployment fail. If that is the case, is the above folder a save option to backup using borg for complete recreation, provided I saved the mariadb contents separately.

I am especially puzzled as this persistent volume / persistent volume claim issues does only affect the wordpress-data not the mariadb contents.

```shell
user@node_machine:/opt/local-path-provisioner/pvc-7e090e17-297a-45b4-83d0-54d84f96ab8a_genughaben_data-genughaben-mariadb-0$ ls
data
user@node_machine:/opt/local-path-provisioner/pvc-7e090e17-297a-45b4-83d0-54d84f96ab8a_genughaben_data-genughaben-mariadb-0$ ls data/
aria_log.00000001  aria_log_control  ib_buffer_pool  ibdata1  ib_logfile0  ib_logfile1  ibtmp1  multi-master.info  mysql  mysql_upgrade_info  performance_schema  tc.log  test  wordpress
user@node_machine:/opt/local-path-provisioner/pvc-7e090e17-297a-45b4-83d0-54d84f96ab8a_genughaben_data-genughaben-mariadb-0$ 
```

Any suggestions?
Thank you!

**To Reproduce**
Prerequisites: a ks8 cluster created/managed by rancher 2.4.4 cluster
1. Installed wordpress using app using the local-path-provider for mariadb and wordpress with Chart Version version 7.3.8 or 9.0.3 adding necessary runAsUser: 0 and fsGroup: 0 options (modification by hand in deployments.yaml)
2. Adding SSL by adding cert-manager and annotations: cert-manager.io/cluster-issuer=letsencrypt-staging and kubernetes.io/tls-acme="true" and field.cattle.io/ingressState={} and adding passage:

```yaml
   tls:
  - hosts:
    - domain.com
    secretName: domain-com
```

to the ingress.yaml.

3. When I now ssh into my clusters node, where the folder is located, it is empty:

```shell
user@node_machine:/opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress$ ls
user@node_machine:/opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress$ 
```

while contents can be found in:

```shell
root@v220191262921103386:/var/lib/docker/overlay2/5273d32ad25deab85b820da048193e1f94425c6d43ebc901112b87c7398ee75b/merged/opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress# ls
wordpress
root@v220191262921103386:/var/lib/docker/overlay2/5273d32ad25deab85b820da048193e1f94425c6d43ebc901112b87c7398ee75b/merged/opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress# ls wordpress/
wp-config.php  wp-content
root@v220191262921103386:/var/lib/docker/overlay2/5273d32ad25deab85b820da048193e1f94425c6d43ebc901112b87c7398ee75b/merged/opt/local-path-provisioner/pvc-12b3a621-86fa-4392-93f1-cd29dea477f4_genughaben_genughaben-wordpress# 

```

only accessible by root.

**Expected behavior**
The files should (also) be available in the folder of the persistent volume.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```shell
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```shell
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

Thank you for your help / suggestions!

**Comment by miguelaeh** [comment]
Hi @genughaben ,
I think that is more related to the Kubernetes cluster than the Helm Chart. In that way, it should not be a problem in order to persist the data.
If you want to use a specific full path in the host, I think you would need to config the PVC to use `hostpath` paths.

**Comment by hrvatskibogmars** [comment]
I have the same issue. Wordpress files are just not persisted in the right location on the disk, but MariaDB works fine. I am using the latest docker version, latest WordPress chart version, and latest local-path-provisioner.

I didn't have these issues before.

**Comment by hrvatskibogmars** [comment]
@genughaben Did you manage to fix the problem?

**Comment by miguelaeh** [comment]
Hi @hrvatskibogmars ,
Are you also using rancher? Do you know which is the latest version that works in your case?

**Comment by hrvatskibogmars** [comment]
> Hi @hrvatskibogmars ,
> Are you using rancher too? Do you know which is the latest version that works in your case?

Docker
`
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
`
Rancher v2.4.4
Kubernetes v1.17.4
Rancher/local-path-provisioner:v0.0.14

I can try and revert it back and see on what version of 8.x chart this worked for me. 
--

**Comment by miguelaeh** [comment]
Hi @hrvatskibogmars ,
I wanted to say which version of the Helm Chart
