### ISSUE TITLE
executing "redis-cluster/templates/update-cluster.yaml" at <.Values.cluster.update.addNodes>: can't evaluate field update in type interface {}

### ISSUE THREAD

**Issue by 0xkevin** [bitnami/charts#27735]
### Name and Version

bitnami/redis-cluster 7.6.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm fetch bitnami/redis-cluster --version 7.6.4 --untar`
2. `helm template -n redis-cluster redis-cluster charts/redis-cluster --output-dir yaml/ctjsoft-test/redis-cluster/redis-cluster/ --set-string global.storageClass=rook-ceph-block`
3. `Error: template: redis-cluster/templates/update-cluster.yaml:1:18: executing "redis-cluster/templates/update-cluster.yaml" at <.Values.cluster.update.addNodes>: can't evaluate field update in type interface {}`

### What do you see instead?
```
Error: template: redis-cluster/templates/update-cluster.yaml:1:18: executing "redis-cluster/templates/update-cluster.yaml" at <.Values.cluster.update.addNodes>: can't evaluate field update in type interface {}
```

**Comment by 0xkevin** [comment]
Really appreciate the help.

**Comment by andresbono** [comment]
I'm not sure what is wrong there, to be honest. What is your `helm version`?
