### ISSUE TITLE
[bitnami/vault] Describe how to create initial keys and run in HA with raft backend

### ISSUE THREAD

**Issue by pat-s** [bitnami/charts#27738]
### Name and Version

bitnami/vault 1.4.9

### What is the problem this feature will solve?

The chart README does not mention that running in HA is not working OOB even though a HA-enabled storage backend is being used.

Yes, it refers to the Vault documentation but in a very generic way, making it hard to get started and frustrated.

### What is the feature you are proposing to solve the problem?

Add a section to the README that describes how to 

1. Init Vault and create initial keys
2. Run in HA using the (default) raft backend

## Description

1. Run `vault operator init` and `vault operator unseal` in a pod of your choice
2. In the additional replica, run `vault operator raft join http://<fullname>-server.<namespace>:8200` to let the other replica join the existing raft cluster
5. (optional) configure [Auto-unseal](https://developer.hashicorp.com/vault/tutorials/auto-unseal)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
