### ISSUE TITLE
Could not connect to Redis: No route to host

### ISSUE THREAD

**Issue by iMoses** [bitnami/charts#2776]
**Which chart**:
redis 10.6.18

**Describe the bug**
slave can't connect to master with this error
```
Could not connect to Redis at redis-master-0.redis-headless.stage0.svc.cluster.local:6379: No route to host
```
it seems that the address is wrong because i can connect only using `redis-master-0.stage0.svc.cluster.local:6379`
i think that `.redis-headless` appearing in the dns is the bug

**To Reproduce**
no idea.. happened after helm uninstall then install.

**Expected behavior**
dns should be correct

seems to me that `redis/templates/redis-slave-statefulset.yaml` line 128 should be replaced
```
currently -
value: {{ template "redis.fullname" . }}-master-0.{{ template "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}

working for me -
value: {{ template "redis.fullname" . }}-master-0.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}

```

**Comment by iMoses** [comment]
further investigation proved that it was a dns refresh issue

**Comment by leisurelyclouds** [comment]
delete pods in coredns can solve problem
