### ISSUE TITLE
Diversity: Allow Keycloak admin realm to be changed/configurable

### ISSUE THREAD

**Issue by wkbrd** [bitnami/charts#27816]
### Name and Version

bitnami/keycloak 21.4.5

### What is the problem this feature will solve?

The admin realm of Keycloak is fixed in this chart to 'master'.  In an interest to allow users of this chart to not use this term, if the chart allowed for changing the admin realm name as a built-in, this would make supporting this easier.

### What is the feature you are proposing to solve the problem?

Allow specifying a value that is the admin realm.

It would then use the use of admin realm varaible in the following places:

- in the statefulset.yaml in the readinessProbe.httpGet.path (or in customReadinessProbe.httpGet.path of values.yaml)
- metrics.serviceMonitor.endpoints[1].path (in values.yaml)

And would specify the realm name via the KC_SPI_ADMIN_REALM environment variable

### What alternatives have you considered?

For now, I have implemented the applicable changes detailed above, though having this supported as a built-in would improve maintainability of this chart going forward.

**Comment by wkbrd** [comment]
As mentioned, I have been able to support this change without changing the chart, though changes to the chart would be appreciated.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by wkbrd** [comment]
PR was merged. Thanks, all!
