### ISSUE TITLE
bitnami/postgresql: CrashLoopBackOff when trying to start the pod

### ISSUE THREAD

**Issue by jouvin** [bitnami/charts#27833]
### Name and Version

bitnami/postgres 15.5.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Kubernetes 1.24 cluster (instantiated through OpenStack Magnum Antelope version)
2. A storage class defined to provision storage from OpenStack Cinder (storage service)
3. Run helm install postgres bitnami/postgresql -f values-postgres-test.yaml
4. Pod is going to status CrashLoopBackOff

### Are you using any custom parameters or values?

values-postgres-test.yaml:
```yaml
image:
    debug: true
```

### What is the expected behavior?

I expect the pod to run successfully! I don't understand why it worked before (at that time with `bitnami/postgres` 14.2.4 in a K8s 1.23 cluster). We upgraded our OpenStack version to be able to instanciate 1.24 K8s clusters that seem to work fine with other applications but since then postgresql has been failing every time I tried to create a pod. It seems to fail also with a 1.23 cluster.

I got this error Cannot allocate memory after adding image: debug: true in the YAML file. Else there was absolutely no error message anywhere... Maybe this kind of error should be logged even if debug: false... But it doesn't give me much information about the reason for the problem and I don't understand if the initdb error after this first error is the cause of the problem (but I did nothing to the container as the logs show) or the consequence... I doubled the memory allocated to minions (and masters), without any impact.

Help would be very much appreciated. I'm completely stuck with this problem. According to what I saw, K8s 1.23 is still the minimum required version so it should work.

### What do you see instead?

Running kubectl describe pod pod/postgres-postgresql-0:

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15m                default-scheduler  Successfully assigned default/postgres-postgresql-0 to test-mj-1-24-lb-m2n3-syhrkg32hov2-node-2
  Normal   Pulled     14m (x4 over 15m)  kubelet            Container image "docker.io/bitnami/postgresql:latest" already present on machine
  Normal   Created    14m (x4 over 15m)  kubelet            Created container postgresql
  Normal   Started    14m (x4 over 15m)  kubelet            Started container postgresql
  Warning  BackOff    3s (x83 over 15m)  kubelet            Back-off restarting failed container
```

Running kubectl logs pod/postgres-postgresql-0:

```
postgresql 08:05:00.16 INFO  ==>
postgresql 08:05:00.16 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 08:05:00.17 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 08:05:00.17 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 08:05:00.17 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql 08:05:00.17 INFO  ==>
postgresql 08:05:00.17 DEBUG ==> Configuring libnss_wrapper...
postgresql 08:05:00.18 DEBUG ==> Copying files from /opt/bitnami/postgresql/conf.default to /opt/bitnami/postgresql/conf
postgresql 08:05:00.19 INFO  ==> ** Starting PostgreSQL setup **
postgresql 08:05:00.20 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 08:05:00.21 INFO  ==> Loading custom pre-init scripts...
postgresql 08:05:00.21 INFO  ==> Initializing PostgreSQL database...
postgresql 08:05:00.21 DEBUG ==> Ensuring expected directories/files exist...
postgresql 08:05:00.22 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 08:05:00.22 INFO  ==> Generating local authentication configuration
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/opt/bitnami/postgresql/bin/initdb"
```

### Additional information

I didn't find how to reopen an issue. This one is a new occurence of #24050, with a more recent environment. It's a long time I have not tested this, so I cannot way when it started to occur, unfortunately.

K8S cluster resources:

```
[ jouvin @ OS_LAL ] [ jouvin @ OS_LAL ] (openstack) bash-4.2$   kubectl top nodes
NAME                                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
test-mj-1-24-lb-m2n3-syhrkg32hov2-master-0   122m         1%     2015Mi          12%
test-mj-1-24-lb-m2n3-syhrkg32hov2-master-1   192m         2%     1879Mi          12%
test-mj-1-24-lb-m2n3-syhrkg32hov2-node-2     75m          0%     1239Mi          7%
```

**Comment by jouvin** [comment]
I was able to move forward in the support of more recent versions of K8s. I just tried with a 1.28 cluster and it works. So it seems the problem is related to old versions of K8s.

**Comment by rafariossaa** [comment]
Sorry for the delay.
I am glad you were able to solve it. I am closing this.
BTW, in the case you want to reopen an issue, just add a comment to it.

**Comment by mecampbellsoup** [comment]
I also experienced this in k8s clusters w/ server API version of 1.20.15.

In clusters 1.24+ however this error did not occur and I wasn't able to reproduce it.

I'm not sure at what point the behavior changed exactly between 1.20 ~ 1.24 but, I can +1 the statement "it seems the problem is related to old versions of K8s" from @jouvin.
