### ISSUE TITLE
[prometheus-operator] Fails to set required labels on pods

### ISSUE THREAD

**Issue by Nuru** [bitnami/charts#2784]
**Which chart**:
prometheus-operator 0.19.1

**Describe the bug**
Labels are not set on Prometheus pods, causing podAntiAffinity to have no effect.

The podAntiAffinity rules require `prometheus-operator.prometheus.matchLabels` to be set:
https://github.com/bitnami/charts/blob/4ea05704cd211f4dd0357ab4ed45c4312f1e1574/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml#L139-L143

but they are not set:
https://github.com/bitnami/charts/blob/4ea05704cd211f4dd0357ab4ed45c4312f1e1574/bitnami/prometheus-operator/templates/prometheus/prometheus.yaml#L120-L122

**To Reproduce**

Deploy Prometheus with podAntiAffinity and note that the deployed pods do not have the labels specified in the podAntiAffinity labelSelector

**Expected behavior**
podAntiAffinity is set with labels that match the deployed Prometheus pods.

**Additional Note**
Same problem exists with Alertmanager

**Comment by miguelaeh** [comment]
Hi @Nuru ,
Do you mean that the `podMetadata` section is empty? It is intended to be used by the user adding their labels: https://github.com/bitnami/charts/blob/4ea05704cd211f4dd0357ab4ed45c4312f1e1574/bitnami/prometheus-operator/values.yaml#L523

**Comment by Nuru** [comment]
@miguelaeh I mean the chart's podAntiAffinity settings do not work because they select labels that are not applied to the pods.

**Comment by miguelaeh** [comment]
Hi @Nuru ,
You are right, I copied the wrong labels. Now I saw what you mean. Please take a look to the PR I created, it solves the issue. #2803

**Comment by Nuru** [comment]
@miguelaeh Thanks. I haven't tested it, but #2803 looks good to me.
