### ISSUE TITLE
[bitnami/elasticsearch] Support persistentVolumeClaimRetentionPolicy

### ISSUE THREAD

**Issue by mike12806** [bitnami/charts#27846]
### Name and Version

elasticsearch:21.2.8

### What is the problem this feature will solve?

Would enable the ability to clean up volumes automatically as Elasticsearch scales up and down (statefulset) 

### What is the feature you are proposing to solve the problem?

https://github.com/giuliocalzolari/charts/blob/ef4e7d40f0dfd22d6b3672a3514eb3a21c1c27e8/bitnami/rabbitmq/values.yaml#L970C1-L970C37 - persistentVolumeClaimRetentionPolicy - this would solve it and is enabled in several other bitnami charts (https://github.com/search?q=org%3Abitnami+persistentVolumeClaimRetentionPolicy&type=code)

This should probably just be commonly enabled across all Bitnami charts, to be honest... 

### What alternatives have you considered?

None - persistentVolumeClaimRetentionPolicy should be the solution here as it's a K8s native solution - https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I wil forward it to thet team, bu as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding the retention policy?

**Comment by mike12806** [comment]
> Hi!
> 
> Thank you so much for the feature request. I wil forward it to thet team, bu as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding the retention policy?

Yep yep - I should be able to model how this was implemented in other bitnami charts and put up a PR. 

Just to clarify here - https://github.com/bitnami/charts/blob/b205f7a39c528e0fe365568f955c25c460649c4f/CONTRIBUTING.md - will the CI process run all neccesary tests or am I required to run locally and attest in the PR?

**Comment by mike12806** [comment]
> > Hi!
> > Thank you so much for the feature request. I wil forward it to thet team, bu as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding the retention policy?
> 
> Yep yep - I should be able to model how this was implemented in other bitnami charts and put up a PR.
> 
> Just to clarify here - https://github.com/bitnami/charts/blob/b205f7a39c528e0fe365568f955c25c460649c4f/CONTRIBUTING.md - will the CI process run all neccesary tests or am I required to run locally and attest in the PR?

Submitted PR - Thanks @javsalgar

**Comment by mike12806** [comment]
Submitted PR @javsalgar - https://github.com/bitnami/charts/pull/27866 - Thanks!

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
