### ISSUE TITLE
[bitnami/postgresql] on OpenShift 4.13 "chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted"

### ISSUE THREAD

**Issue by rockyhopper** [bitnami/charts#27860]
### Name and Version

bitnami/postgresql 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy helm postgresql chart (latest= 15.5.15 with appVersion: 16.3.0) on Openshift 4.13 with custom values defined in 'values.yml' 

### Are you using any custom parameters or values?

```
global:
  postgresql:
    auth:
      database: "postgres"
      password: "myadmpass"
      username: "postgres"
      postgresPassword: "myreallysecretpassword"
    service.ports.postgresql: "5432"

image:
  tag: 16.3.0-debian-12-r19
    
primary:
  persistence:
    size: 3Gi
  podSecurityContext:
    fsGroup: null
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsUser: null
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]

volumePermissions:
  enabled: false
shmVolume:
  enabled: false

image:
  debug: true
```

### What is the expected behavior?

Postgresql should be deployed successfully.

### What do you see instead?

Pod fails to start 

```

[postgresql-0](https://********************/pods/postgresql-0)
Back-off restarting failed container postgresql in pod postgresql-0_my-namespace(acbc3c57-2cd6-45fd-96c8-edbbd5e0c8fc)
```

with logs

```
[38;5;6mpostgresql [38;5;5m16:34:02.79 [0m[38;5;2mINFO [0m ==> 
[38;5;6mpostgresql [38;5;5m16:34:02.88 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami postgresql container[0m
[38;5;6mpostgresql [38;5;5m16:34:02.88 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mpostgresql [38;5;5m16:34:02.88 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mpostgresql [38;5;5m16:34:02.88 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[38;5;6mpostgresql [38;5;5m16:34:02.89 [0m[38;5;2mINFO [0m ==> 
[38;5;6mpostgresql [38;5;5m16:34:02.98 [0m[38;5;5mDEBUG[0m ==> Copying files from /opt/bitnami/postgresql/conf.default to /opt/bitnami/postgresql/conf
[38;5;6mpostgresql [38;5;5m16:34:02.98 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL setup **
[38;5;6mpostgresql [38;5;5m16:34:03.09 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql [38;5;5m16:34:03.19 [0m[38;5;2mINFO [0m ==> Loading custom pre-init scripts...
[38;5;6mpostgresql [38;5;5m16:34:03.20 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m16:34:03.20 [0m[38;5;5mDEBUG[0m ==> Ensuring expected directories/files exist...
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
[38;5;6mpostgresql [38;5;5m16:34:03.38 [0m[38;5;3mWARN [0m ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
[38;5;6mpostgresql [38;5;5m16:34:03.38 [0m[38;5;3mWARN [0m ==> Lack of permissions on data directory!
[38;5;6mpostgresql [38;5;5m16:34:03.38 [0m[38;5;2mINFO [0m ==> pg_hba.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m16:34:03.39 [0m[38;5;2mINFO [0m ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "1001640000".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /bitnami/postgresql/data ... initdb: error: could not change permissions of directory "/bitnami/postgresql/data": Operation not permitted`

```

### Additional information

Regarding custom values I've following recommendations for deployment on Openshift >= 4.11.

**Comment by javsalgar** [comment]
Hi,

This is strange, as the data volume should already have the proper permissions for the random user. Could you launch the chart wtih diagnosticMode.enabled=true, enter the container and check the permissions of the data volume?

**Comment by rockyhopper** [comment]
Hi,

Here are the results:

```
$ ls -lia /bitnami/postgresql/data
total 0
 9223442405598953472 drwxrwxrwx. 2 root 1001640000 0 Jul 10 15:24 .
12298227009095979647 drwxrwxrwx. 2 root 1001640000 0 Jul 10 15:24 ..
$ whoami
1001640000
$ 
```

I was able to create an empty folder in /bitnami/postgresql/data.
But trying to "chown" is resulting in same "Operation not permitted"...

```
$ chown 1001640000:1001640000 /bitnami/postgresql/data
chown: changing ownership of '/bitnami/postgresql/data': Operation not permitted
$ 
```

Does it mean that changing ownership was not required but attempted?

Thanks for your help.

**Comment by javsalgar** [comment]
It seems that the PostgreSQL initdb script is trying to perform that chown but it is not necessary.

**Comment by rockyhopper** [comment]
According to "https://hub.docker.com/_/postgres" (official postgres image):

> "The main caveat to note is that postgres doesn't care what UID it runs as (as long as the owner of /var/lib/postgresql/data matches), but initdb does care (and needs the user to exist in /etc/passwd) [...]"

Then, I understand that UID (here 1001640000) should be owner of the '/var/lib/postgresql/data' and not only have accesses.
It might explain why it tries to chown (replacing file owner with "my" UID value).

Not sure about bitnami/postgresql used here, I only found:

> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001

**Comment by dgomezleon** [comment]
Hi @rockyhopper ,

I was not able to reproduce the issue on Openshift 4.13 with version 15.5.15 and 15.5.16. This is the output I obtained:

```
$ ls -lia /bitnami/postgresql/
total 24
       2 drwxrwsr-x.  4 root       1000720000  4096 Jul 15 10:20 .
65016428 drwxr-xr-x.  3 root       root          24 Jul  5 12:16 ..
      12 drwx------. 19 1000720000 1000720000  4096 Jul 15 10:21 data
      11 drwxrws---.  2 root       1000720000 16384 Jul 15 10:20 lost+found
```

**Comment by rockyhopper** [comment]
Hi @dgomezleon ,

Thank you for your feedback.

I don't know if it can be somehow related to some cluster settings, as I have limited access to it, I would need to ask administrators.

Whatever I will retry on Monday with the same versions you tried. Also I will check if I can test on another OpenShift cluster.

Best regards.

**Comment by rockyhopper** [comment]
Hi @dgomezleon,

As mentioned above, I retried today with both 15.5.15 and 15.5.16 on same OpenShift cluster as before, and issue is encountered for both versions.

- 15.5.15


`
$ ls -lia /bitnami/postgresql
total 0
3406689585411903082 drwxrwxrwx. 2 root 1001640000  0 Jul 22 14:38 .
          618791791 drwxr-xr-x. 3 root root       24 Jul  5 12:16 ..
9223442405598953472 drwxrwxrwx. 2 root 1001640000  0 Jul 22 14:38 data
$ 

`

-  15.5.16 

`
$ ls -lia /bitnami/postgresql 
total 0
2695660707847181481 drwxrwxrwx. 2 root 1001640000  0 Jul 22 14:40 .
          249567039 drwxr-xr-x. 3 root root       24 Jul  5 12:16 ..
9223442405598953472 drwxrwxrwx. 2 root 1001640000  0 Jul 22 14:40 data
$

`

But I also tried on another (free redhat) instance which is OpenShift 4.15.14 (I found no option to test on 4.13.x), and it works.

`
$ ls -lia /bitnami/postgresql
total 24
        2 drwxrwsr-x.  4 root       1012720000  4096 Jul 22 14:58 .
702672293 drwxr-xr-x.  3 root       root          24 Jul  5 12:16 ..
       12 drwx------. 19 1012720000 1012720000  4096 Jul 22 14:58 data
       11 drwxrws---.  2 root       1012720000 16384 Jul 22 14:57 lost+found

`

As you cannot reproduce with OpenShift 4.13 and issue is not occuring on OpenShift 4.15 on my side, I guess the issue is with my OpenShift 4.13 cluster configuration.

I will reach administrators for them to investigate: I guess you can no more help me, then closing the ticket.

I apologize for any time lost.

Best regards.
