### ISSUE TITLE
clickhouse defaultConfigurationOverrides pretty display

### ISSUE THREAD

**Issue by funcx27** [bitnami/charts#27868]
### Name and Version

clickhouse/6.2.10

### What is the problem this feature will solve?

helm template result configmap data 00_default_overrides.xml has white space before \n, kubectl get cm not pretty display.
![image](https://github.com/bitnami/charts/assets/15167195/413542cb-c8a1-43dc-ab8f-75038eb1bf9f)

### What is the feature you are proposing to solve the problem?

delete blank line in defaultConfigurationOverrides

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
