### ISSUE TITLE
[bitnami/matomo] customCAs parameter seems doesn't work properly 

### ISSUE THREAD

**Issue by RaimundasR** [bitnami/charts#27879]
### Name and Version

bitnami/matomo:7.3.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Just add certs in the secret named `truststore-secret` 

then add in the ` customCAs` list with name `truststore-secret`

```
certificates:
    customCAs: 
        - secret: truststore-secret
           
```

after trying to install i'm  getting the  error 👇 

```
"error":"YAML parse error on matomo/templates/deployment.yaml: error converting YAML to JSON: yaml: line 71: did not find expected alphabetic or numeric character","errorVerbose"
```

which is in the deployment.yaml template --> https://github.com/bitnami/charts/blob/main/bitnami/matomo/templates/deployment.yaml   `initContainers:`, but Im not even using some `initContainers` except default value `initContainers: []`

### What is the expected behavior?

Im expecting as document says

```
  ## @param certificates.customCAs Defines a list of secrets to import into the container trust store
  ##
  customCAs: []
  ```

### What do you see instead?

explained at `What steps will reproduce the bug?`

### Additional information

any ideas, what Im doing wrong, or what I should do to resolve this issue :/ Thank you!!

**Comment by RaimundasR** [comment]
Any update on this? I just modified deployment.yaml to ingore this iniContainer 71 line, as I'm not using it, and then it still failing in other values 😢 
```
      {{- if .Values.initContainers }}
      initContainers:
        {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 6 }}
      {{- end }}
      {{- include "matomo.initContainers" . | nindent 2 }}
```

Not sure how to fix it....

**Comment by dgomezleon** [comment]
Hi @RaimundasR 
Thanks for reporting it. I have sent a PR to fix the issue.

**Comment by RaimundasR** [comment]
> Hi @RaimundasR Thanks for reporting it. I have sent a PR to fix the issue.

But after fix it still fails, just in another place...

```
{"level":"info","ts":"2024-07-16T06:02:59.034Z","logger":"runtime","msg":"unknown field \"spec.template.spec.initContainers[0].imagePullSecrets\""}
```
