### ISSUE TITLE
[bitnami/gitea] Allow setting external db params via secret

### ISSUE THREAD

**Issue by aqeelat** [bitnami/charts#27871]
### Name and Version

bitnami/gitea 2.3.11

### What is the problem this feature will solve?

Gitea uses a postgres database. Currently, we have to set the database connection details manually in the values file, and the password is the only one that can be set via a secret.
We have a lot of charts and it would be a huge hassle to go and maintain them manually.

Currently, we have a secret with our db connection detail. It has:

It would be great if we can use this secret for gitea as well.

### What is the feature you are proposing to solve the problem?

Allow setting more params via secret.

POSTGRES_HOST
PORTGRES_PORT
POSTGRES_USER
POSTGRES_PASSWORD

Similar to how it is done in bitnami/keycloak

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward this to the team but as it is not a critical issue we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR?
