### ISSUE TITLE
[bitnami/harbor] Harbor admin password not working after a while 

### ISSUE THREAD

**Issue by HamzaZoubair** [bitnami/charts#27896]
### Name and Version

bitnami/harbor 21.1.5

### What architecture are you using?

None

### What steps will reproduce the bug?

Installing Harbor bitnami helm chart with ArgoCD

### What do you see instead?

Core, JobService and Registry restart after a while from installation 
After that login is failing with admin default password.
When I reset the password on postgres Pod, the login works again
`update harbor_user set salt='', password='' where user_id = 1;`

**Comment by jdaln** [comment]
Could this be somehwat linked to https://github.com/bitnami/charts/issues/27483#issuecomment-2233755228 ?

**Comment by andresbono** [comment]
Hi @HamzaZoubair, is your issue happening only when deploying with ArgoCD? Please, share the values you are providing so we can reproduce the issue.

**Comment by HamzaZoubair** [comment]
@andresbono @jdaln 
Thanks for you response, when I set the postgresql password it is fixed.
I have another problem oidc authentication is faling after a while also and I have this log 

[ERROR] [/core/controllers/oidc.go:118]: Failed to exchange token, error: oauth2: "invalid_client" "Invalid client credentials."
[DEBUG] [/lib/http/error.go:62]: {"errors":[{"code":"BAD_REQUEST","message":"oauth2: \"invalid_client\" \"Invalid client credentials.\""}]}

Thank you.

**Comment by andresbono** [comment]
Do you think that error is somehow related to the way we package the helm chart? Please, share any suggestions for improvements that you may have.
