### ISSUE TITLE
New chart for dotnet-core application

### ISSUE THREAD

**Issue by shankarmohannamakkal** [bitnami/charts#2789]
**Which chart**:
New chart required to deploy asp.net core applications (web/api)

**Is your feature request related to a problem? Please describe.**
Currently there is no chart in bitnami for deploy the asp.net core application projects using kestrel server

**Describe the solution you'd like**
We can create a new chart with the following templates for deploy the asp.net core applications
- Config map
- Deployment
- Services
- Ingress

**Additional context**
Please let us know about this idea of creating a new chart for deploying asp.net core applications (web/api) in kubernetes. So that based on any suggestion here i can go ahead and create a new chart.

**Comment by juan131** [comment]
Hi @shankarmohannamakkal 

Thanks so much for this great initiative. We'll be glad to accept your contribution and add this helm chart to the repository.

Please take a look to our [Contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md), specially put special emphasis in the section [Adding a new chart to the repository](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository). Do not hesitate to let us know if you have any doubt about the process.

Once you create the PR adding the new chart, our team will review it and help you through the process until it's finally accepted and added to the catalog.

**Comment by shankarmohannamakkal** [comment]
New chart created as dotnet-core-kestrel.

PR - https://github.com/bitnami/charts/pull/2859

**Comment by shankarmohannamakkal** [comment]
bitnami aspnet-core chart is done - [https://github.com/bitnami/charts/tree/master/bitnami/aspnet-core](https://github.com/bitnami/charts/tree/master/bitnami/aspnet-core)
Good to close this issue.
