### ISSUE TITLE
[bitnami/redis-cluster] Add HorizontalPodAutoscaler to chart Redis-Cluster

### ISSUE THREAD

**Issue by Praveen-98cs** [bitnami/charts#27897]
### Name and Version

bitnami/redi-cluster

### What is the problem this feature will solve?

don't have to add the HPA manually to the redis-cluster deployment.

### What is the feature you are proposing to solve the problem?

I saw that a HPA has been added to the redis chart. just wanted to know, if it is possible to add a HPA to redis-cluster chart as well? 

### What alternatives have you considered?

Cause currently I am using  a HPA created by me but it would be idea if this can be added to the chart it self.

**Comment by javsalgar** [comment]
Hi!

It is not clear to me that the automations would work as expected by adding-removing nodes automatically. Currently there is a job that perform this kind of update operations. Did you try adding a HPA and see what happens?

**Comment by Praveen-98cs** [comment]
Hi!
Yes, I tried that out and the autoscaling up and down worked when doing a redis benchmark and putting a bit of a load. The only issue was the pvc's that are getting created don't get deleted when auto scaling down, not sure about the data loss as well. just wanted to know if there are any alternative method rather than plugging a HPA as you mentioned that

> Currently there is a job that perform this kind of update operations.
can you explain a bit more?

Thank you!

**Comment by javsalgar** [comment]
Hi!

You can see the cluster update logic in this script. 

https://github.com/bitnami/charts/blob/f716e12ccc46a838fee203a137e15ab5a1791b32/bitnami/redis-cluster/templates/update-cluster.yaml#L80

As you can see it performs redis cluster rebalance operations. And that would be missed with the HPA

**Comment by javsalgar** [comment]
Something that comes to mind would be triggering a bash script on a certain prometheus metrics (in case you have a prometheus instance connected). https://stackoverflow.com/questions/71419928/trigger-an-action-based-on-prometheus-metrics

**Comment by Praveen-98cs** [comment]
Thank you will look into this.

**Comment by jayqwal** [comment]
@Praveen-98cs , would you mind sharing your working solution here? Did you add some logic in your HPA to trigger script?

**Comment by jayqwal** [comment]
@javsalgar ,

> triggering a bash script on a certain prometheus metrics

So would you suggest a new separate pod/process that monitors the metrics and call the `helm upgrade ...` command as suggested in the [README](triggering a bash script on a certain prometheus metrics)?

**Comment by Praveen-98cs** [comment]
@jayqwal for now we are going with the approach of using the helm upgrade and adding a node, but still there is an issue as we are using flux so we can't pass any commands with the helm upgrade, will update if we have found a solution.

**Comment by jayqwal** [comment]
@Praveen-98cs thanks for the updates!
@javsalgar so this feature request is still valid as autoscaling is a very useful feature for many peoples. Can we re-open this ticket?
