### ISSUE TITLE
mc: <ERROR> Unable to initialize service restart UI: could not open a new TTY: open /dev/tty: no such device or address.

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#27898]
### Name and Version

bitnami/minio:14.6.20

### What architecture are you using?

amd64

### What steps will reproduce the bug?

tried using helm command

```
helm install minio-default     \
--namespace velero     \
--create-namespace     \
--set resources.requests.memory=1Gi     \
--set persistence.size=32Gi \
--set auth.rootUser=minio \
--set auth.rootPassword=minio123  \
--set service.type=NodePort  \
--set service.nodePorts.api=30100  \
--set service.nodePorts.console=30200  \
--set provisioning.enabled=true \
--set provisioning.buckets[0].name=velero    \
--set provisioning.buckets[0].policy=public \
--set provisioning.buckets[0].purge=true  \
oci://registry-1.docker.io/bitnamicharts/minio
```

### Are you using any custom parameters or values?

Yes, mentioned above with auto provisioning

### What is the expected behavior?

in previous version, auto provisioning was able to create buckets , but its creating problem now

### What do you see instead?

```
root@devops99:~# k -n velero logs -f minio-velero-provisioning-7wppl
Defaulted container "minio" out of: minio, wait-for-available-minio (init)
Start Minio provisioning
Added `provisioning` successfully.
mc: <ERROR> Unable to initialize service restart UI: could not open a new TTY: open /dev/tty: no such device or address.

```

**Comment by zltyfsh** [comment]
We are investigating the same issue. Downgrading the helm-chart version to previous release (14.6.18) solved the problem for us, so this is a regression in the last release.

**Comment by busyboy77** [comment]
Thank you acknowledging this. I'll now close this thread.

**Comment by zltyfsh** [comment]
@busyboy77 I think it was a premature close of the issue, because there is a regression/bug in the current version. The downgrade is just a work-a-round. Can you re-open the issue?

**Comment by busyboy77** [comment]
Re-opening as require by Sir @zltyfsh . Thank your for concern.

**Comment by ukclivecox** [comment]
Seems last work minio/mc is RELEASE.2024-06-24T19-40-33Z-cpuv1

**Comment by zltyfsh** [comment]
There has been done some improvements for the "admin service restart" UI in https://github.com/minio/mc/pull/4979., and I wouldn't be surprised if that's causing the problems.
