### ISSUE TITLE
[mariadb-galera] allow templated extraVolumes configMap name and existingSecret

### ISSUE THREAD

**Issue by rajeevnaikte** [bitnami/charts#27914]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

To avoid conflicts with multiple release installs, we would prefix all resources with release name. To mariadb-galera chart if we pass templated configMap name, e.g. `{{ .Release.Name }}-some-sh-file`, in `extraVolumes` and templated `existingSecret`, e.g. `{{ .Release.Name }}-my-db-secret`, then bitnami chart will not resolve it with the dynamic release name, which requires passing these values separately for every release install.

### What is the feature you are proposing to solve the problem?

Resolve the values of `extraVolumes` and `existingSecret` with `tpl` function

### What alternatives have you considered?

passing these values separately for every release install.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
