### ISSUE TITLE
[bitnami/spark] Update the "Define custom configuration" section in readme

### ISSUE THREAD

**Issue by ricsi046** [bitnami/charts#27956]
### Name and Version

bitnami/spark 9.2.5

### What is the problem this feature will solve?

The readme won't mislead users in the future.

### What is the feature you are proposing to solve the problem?

Replace configurationConfigMap with existingConfigmap in the mentioned section of the readme, since that parameter was renamed a while ago.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for spotting the documentation issue. Would you like to submit a PR updating the README?
