### ISSUE TITLE
[bitnami/postgresql] Set the number of backups to keep

### ISSUE THREAD

**Issue by joaopedrocg27** [bitnami/charts#27954]
### Name and Version

bitnami/postgresql 15.5.14

### What is the problem this feature will solve?

This would save a lot of disk space.

### What is the feature you are proposing to solve the problem?

I would like to set the maximum number of backups using the backup feature so I do not keep an infinite number of pgdump files.

### What alternatives have you considered?

I have tried this and it works great but it would be great if it was integrated in the chart:

```
      command:
      - /bin/sh
      - -c
      - |
        BACKUP_DIR=${PGDUMP_DIR}
        BACKUPS_TO_KEEP=5
        
        echo "Current backups in ${BACKUP_DIR}:"
        ls -lh ${BACKUP_DIR}/pg_dumpall-*.pgdump
        
        pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers --no-password --file=${BACKUP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump
        
        if [ $? -eq 0 ]; then
          echo "Backup created successfully."
          
          BACKUPS_TO_DELETE=$(ls -1t $BACKUP_DIR/pg_dumpall-*.pgdump | tail -n +$((BACKUPS_TO_KEEP+1)))
          
          if [ -n "$BACKUPS_TO_DELETE" ]; then
            echo "Deleting old backups:"
            echo "$BACKUPS_TO_DELETE"
            
            echo "$BACKUPS_TO_DELETE" | xargs -I {} rm -- {}
          else
            echo "No backups to delete."
          fi
        else
          echo "Backup creation failed. Old backups will not be deleted."
        fi
```
Before and After
<img width="370" alt="image" src="https://github.com/user-attachments/assets/5480d048-b374-4b5b-b4a0-748a8f688681">

<img width="360" alt="image" src="https://github.com/user-attachments/assets/4b1d3ca5-34d8-46ce-a907-3d7f677811e7">

Logs (other deployment):

<img width="757" alt="image" src="https://github.com/user-attachments/assets/87a8a81b-e468-44af-8892-3d8d3c0226ec">

**Comment by javsalgar** [comment]
Hi!

Thanks for the feature request. I imagine this could be implemented as some sort of job that accesses the database. Would you like to propose a PR?

**Comment by joaopedrocg27** [comment]
> Hi!
> 
> 
> 
> Thanks for the feature request. I imagine this could be implemented as some sort of job that accesses the database. Would you like to propose a PR? 

Could this just replace the current default for the backup command that runs as a cron job? I opened this fr because I thought that nobody faced this yet.


I'll open a PR when I find some free time. Thank you
