### ISSUE TITLE
How to use offical elasticsearch 7.4 from bitnami charts?

### ISSUE THREAD

**Issue by yaodwwy** [bitnami/charts#27961]
### Name and Version

bitnami/elasticsearch 7.4

### What is the problem this feature will solve?

In fact, the server does not need to upgrade the main version frequently, only patches and maintainable items need to be upgraded.

### What is the feature you are proposing to solve the problem?

Update charts of different versions to be consistent with the list in official maintenance.

**Comment by carrodher** [comment]
Each Helm chart functions as a package tested with a specific combination of source code (Helm chart templates) and container images. Deviating from this tested combination may lead to unpredictable results, which we cannot guarantee.

Replacing the container images to use a different version is not recommended as it has not been tested, it could or could not work, but it is not something we provide support for.
