### ISSUE TITLE
[bitnami/mlflow] can't use external minio.

### ISSUE THREAD

**Issue by nakyo7** [bitnami/charts#27967]
### Name and Version

bitnami/mlflow 1.0.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I want use already installed minio instead install minio. 
However, due to this conditional statement(https://github.com/bitnami/charts/pull/25294), external minio is not available. 
Is there a reason why this conditional statement was made?

### What do you see instead?

Log is occurred in tracking server.
'The AWS Access Key Id and you provided does not exist in our recored.'

**Comment by jotamartos** [comment]
Sorry for the late reply. As explained in the PR you linked, that was disabled to avoid errors when not using the MinIO subchart. If you are using an external server, you can set the MLFLOW_S3_ENDPOINT_URL env var as extraEnvVar parameter. Does that work for you? 

If you think there are better ways to solve this, you can always contribute to the project by following the [contributing guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md). The team will be more than happy to review the changes and the whole community will benefit from them. 

Thanks
