### ISSUE TITLE
[bitnami/valkey-cluster] Error: UPGRADE FAILED: YAML parse error on common/charts/valkey-cluster/templates/metrics-svc.yaml: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by sunyeongchoi** [bitnami/charts#27970]
### Name and Version

bitnami/valkey-cluster-0.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

```yaml
metrics:
  enabled: true
```

metric 활성화 후 helm install시 에러가 발생합니다.

### What do you see instead?
```
Error: UPGRADE FAILED: YAML parse error on common/charts/valkey-cluster/templates/metrics-svc.yaml: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
