### ISSUE TITLE
[bitnami/grafana][bitnami/prometheus-operator] automatically provision prometheus dashboards

### ISSUE THREAD

**Issue by raphaelcervantes** [bitnami/charts#2797]
**Which chart**:
grafana-1.5.2 and prometheus-operator-0.15.4

**Is your feature request related to a problem? Please describe.**
I am transitioning away from the charts in the stable repository because they are becoming deprecated. Their version of prometheus-operator has grafana incorporated with provisioned prometheus-dashboards that make cluster monitoring a joy. The provisioned dashboards are here: https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates/grafana/dashboards

**Describe the solution you'd like**
If possible, I would like prometheus dashboards to be automatically provisioned into grafana, as is done in stable helm chart. If this is impractical, I would like suggestions on how I can automatically provision these prometheus dashboards. I think doing it by hand would be tedious (but I can be wrong).

**Describe alternatives you've considered**
I have tried finding another dashboard in Grafana. For example: https://grafana.com/grafana/dashboards/3662
I haven't found one that works well and I didn't find one that has been updated recently.

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you very much for using Bitnami. I think this is a good feature to have. We will evaluate it and update the ticket when we have more information. As this is not a critical feature, we cannot guarantee an ETA. However, as soon as I have news, I will let you know.

**Comment by connec** [comment]
I've also been investigating some way of using the bitnami/grafana chart as a dependency and provisioning Grafana dashboards from an external source of truth (e.g. rather than having to keep them all in-tree as config maps).

I've created a PR (#3077) that adds support for arbitrary extra volumes in the Grafana pod/container, which I intend to use with a `curl`-based sidecar that will pull dashboards and write them to the `/opt/bitnami/grafana/dashboards` folder. This is similar to the approach used in the stable/grafana repo (e.g. https://github.com/helm/charts/blob/master/stable/grafana/templates/_pod.tpl#L32-L59).

**Comment by javsalgar** [comment]
Hi

Thank you very much! We will review it very soon :)

**Comment by dbrennand** [comment]
Hey everyone 😄 
I am also very interested in these dashboards being added! 👍

**Comment by connec** [comment]
Something I came across and hoped to see in the Bitnami charts is grafana operator: https://github.com/integr8ly/grafana-operator

In a high automated cluster with prometheus operator and other elements in the BKPR, something like Grafana Operator would make a lot of sense to me.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input! I will forward it evaluation. Other users contributed with a helm chart PR (Contour, Discourse, MetalLB, ASP.Net Core) which did speed up the process of packaging. Feel free to contribute if you want us to maintain a Grafana Operator chart :)

**Comment by raphaelcervantes** [comment]
I'm looking into this again and I'm confused how grafana-operator addresses the issue of provisioning dashboards for k8 cluster monitoring.

**Comment by javsalgar** [comment]
Hi @raphaelcervantes , feel free to open a new ticket regarding grafana-operator and the way it provisions dashboards. I think this ticket, now that the operator is available, can be closed.
