### ISSUE TITLE
[bitnami/discourse] Validating settings in POSTGRESQL_CLIENT_* env vars

### ISSUE THREAD

**Issue by peteryang1756** [bitnami/charts#27978]
### Name and Version

bitnami/discourse:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I try to host discourse on Render but I got 
```
Validating settings in POSTGRESQL_CLIENT_* env vars
```
How to fix it

### What do you see instead?

```
Welcome to the Bitnami discourse container
discourse 12:50:34.34 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
discourse 12:50:34.34 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
discourse 12:50:34.34 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
discourse 12:50:34.34 INFO  ==> 
discourse 12:50:34.35 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
discourse 12:50:34.42 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
discourse 12:50:34.43 INFO  ==> Creating Discourse configuration file
discourse 12:50:34.46 INFO  ==> Ensuring Discourse directories exist
discourse 12:50:34.47 INFO  ==> Trying to connect to the database server
discourse 12:50:36.15 INFO  ==> Populating database
Application exited with code 1. This usually indicates an application failure. Check that the command used to launch your application is correct.
Instance stopped
```

**Comment by peteryang1756** [comment]
Hello, I saw a issues on github
And it say
```
Could you launch the chart with image.debug=true to see if there's more debug information?
```
How to do it because I try to add it in env but I got :must be a valid environment variable name

**Comment by javsalgar** [comment]
Hi!

Could you provide the values you used for deploying? Could you try deploying with `image.debug=true`?

**Comment by peteryang1756** [comment]
> Hi!
> 
> Could you provide the values you used for deploying? Could you try deploying with `image.debug=true`?

Hi, thanks it looks like a redis configuration error, but I am using an external redis but there is no redis user env in readme.md, what is the env for redis user?

**Comment by javsalgar** [comment]
Hi,

Looking at https://github.com/discourse/discourse/blob/main/config/discourse_defaults.conf, it seems that there is no redis_user section. I would check with upstream discourse to see if a redis authentication is supported.

**Comment by tp1050** [comment]
i got the same issues
