### ISSUE TITLE
[bitnami/keycloak] Slow response time witth ingress.hostname=keycloak.local

### ISSUE THREAD

**Issue by metin-durmaz** [bitnami/charts#27988]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Ingress.hostname value is specified as "keycloak.local" in the default values.yaml file. Since ".local" is used exclusively in MacOS, it takes 5-6 seconds to resolve this domain at first.

https://serverfault.com/questions/1055086/webpage-always-takes-5-seconds-to-load-the-first-time-using-nginx

### What is the feature you are proposing to solve the problem?

This domain can be updated with a different value.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request but this would require a change in all of our charts for consistency. As this is a very specific use case where you are testing the chart from a Mac OS environment, it is hard for me to justify a batch change in all charts for this.
