### ISSUE TITLE
[bitnami/etcd] Network policy ingress rules are overriden by metrics rule

### ISSUE THREAD

**Issue by vipulagarwal** [bitnami/charts#27981]
### Name and Version

bitnami/etcd-10.2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set `metrics` enabled to `true`

Change the following values under `networkPolicy`:
- set `allowExternal` to `false`
- set `ingressNSMatchLabels` to a namespace label

### Are you using any custom parameters or values?

```
networkPolicy:
  allowExternal: false
  ingressNSMatchLabels:
    mylabel: true

metrics:
  enabled: true
```

### What is the expected behavior?

Only namespace with `mylabel=true` are allowed to connect to etcd port 2379

### What do you see instead?

All namespaces can connect to etcd when `metrics` are enabled within the helm chart.

This happens because of the following template code: https://github.com/bitnami/charts/blob/etcd/10.2.6/bitnami/etcd/templates/networkpolicy.yaml#L76-L80

### Additional information

I appreciate the intention to automate network policy when prometheus metrics are enabled and promote metrics scrapping. However, this logic is overriding the network policy restrictions intended by [`ingressNSMatchLabels`](https://github.com/bitnami/charts/blob/etcd/10.2.6/bitnami/etcd/values.yaml#L762)

**Comment by vipulagarwal** [comment]
A rendered template for the above example:
```# Source: etcd/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: release-name-etcd
  namespace: "sysdig-deploy"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    app.kubernetes.io/version: 3.5.14
    helm.sh/chart: etcd-10.2.6
    app.kubernetes.io/component: etcd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: etcd
      app.kubernetes.io/component: etcd
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    # Allow inbound connections
    - ports:
        - port: 2379
        - port: 2380
      from:
        - podSelector:
            matchLabels:
              release-name-etcd-client: "true"
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: etcd
              app.kubernetes.io/component: etcd
        - namespaceSelector:
            matchLabels:
              "mylabel": "true"
    # Allow prometheus scrapes for metrics
    - ports:
        - port: 2379
```

The last three lines adds an ingress rule that overrides the rule above it.

**Comment by vipulagarwal** [comment]
A rendered template for the above example:
```# Source: etcd/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: release-name-etcd
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    app.kubernetes.io/version: 3.5.14
    helm.sh/chart: etcd-10.2.6
    app.kubernetes.io/component: etcd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: etcd
      app.kubernetes.io/component: etcd
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    # Allow inbound connections
    - ports:
        - port: 2379
        - port: 2380
      from:
        - podSelector:
            matchLabels:
              release-name-etcd-client: "true"
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: release-name
              app.kubernetes.io/name: etcd
              app.kubernetes.io/component: etcd
        - namespaceSelector:
            matchLabels:
              "mylabel": "true"
    # Allow prometheus scrapes for metrics
    - ports:
        - port: 2379
```

The last three lines adds an ingress rule that overrides the rule above it.

**Comment by rafariossaa** [comment]
Hi,
  In this case, I would suggest you to disable `networkPolicy` and use `extraDeploy` to use your custom networkPolicy.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your offering. Let see if more issues are open on this topic and take a decision then. I think this case of things are very dependent on the environment, how and where you have deployed prometheous (and others), so in each case the needs for the network policies are going to be different. I think there is not silver bullet for this, hence other mechanism to do what it is needed is provided.
