### ISSUE TITLE
[bitnami/elasticsearch] Enable bundled Kibana

### ISSUE THREAD

**Issue by YuXiaoCoder** [bitnami/charts#2806]
**Which chart**:
bitnami/elasticsearch 12.0.0

**Is your feature request related to a problem? Please describe.**
How to specify the image version of Kibana when the bundled Kibana is enabled by ES

**Describe the solution you'd like**
specify the image version of Kibana when the bundled Kibana is enabled by ES

**Comment by javsalgar** [comment]
Hi,

You could set it using `kibana.image.tag`
