### ISSUE TITLE
[bitnami/grafana-loki] Querys in grafana, dont show all log. Only about 2h.

### ISSUE THREAD

**Issue by nowost** [bitnami/charts#28116]
### Name and Version

bitnami/grafana-loki 4.6.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install standard helm chart 4.6.0
2. Add in Grafana Loki source (loki-gateway)
3. In Grafana explorer query logs, i see only last 2h (no older logs)

### Are you using any custom parameters or values?

i use persistence storage class, all other config is default.

### What is the expected behavior?

i must see all logs.

### What do you see instead?

i see logs only for last 2h.
![image](https://github.com/user-attachments/assets/cb9ae379-6fe7-475b-b1c3-c51789a67c96)

**Comment by javsalgar** [comment]
Hi,

It is not clear to me that the issue has to do with the Bitnami packaging of Grafana Loki, but with the configuration of Loki itself. Did you check with the upstream Grafana devs to see if there's a setting that must be changed?

**Comment by nowost** [comment]
For some reason i cant see old log in grafana explorer when make query to Loki. Maybe it's about Loki settings.

**Comment by nowost** [comment]
Solution:  **"This chart does not function fully when using local filesystem as a persistence store. When using a local filesystem as a persistence store, querying will not be possible (or limited to the ingesters' in-memory caches). For a fully functional deployment of this helm chart, an object storage backend is required."**

**Comment by nowost** [comment]
resolved
