### ISSUE TITLE
[bitnami/postgresql] How to enable ssl and external access through ingress

### ISSUE THREAD

**Issue by hussainsaify** [bitnami/charts#2812]
Hi Team,

I was enabling ssl/tls on postgresql but pod is failing to come up with failure related to password authentication.

I have copied certificates to postgresql data directory and added ssl=on in postgresql.conf

Following is the error on pod startup.
```
postgresql 08:46:05.95 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 08:46:05.96 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2020-06-11 08:46:05.986 GMT [136] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-06-11 08:46:05.986 GMT [136] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2020-06-11 08:46:05.986 GMT [136] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2020-06-11 08:46:05.990 GMT [136] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-06-11 08:46:06.002 GMT [137] LOG:  database system was shut down at 2020-06-11 08:46:03 GMT
2020-06-11 08:46:06.007 GMT [136] LOG:  database system is ready to accept connections
 done
server started
2020-06-11 08:46:06.076 GMT [145] FATAL:  password authentication failed for user "postgres"
2020-06-11 08:46:06.076 GMT [145] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
2020-06-11 08:46:06.076 GMT [145] LOG:  could not send data to client: Broken pipe
postgresql 08:46:06.08 DEBUG ==> Executing /docker-entrypoint-initdb.d/security_ddl.sql
2020-06-11 08:46:06.092 GMT [151] FATAL:  password authentication failed for user "postgres"
2020-06-11 08:46:06.092 GMT [151] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2020-06-11 08:46:06.094 GMT [152] FATAL:  password authentication failed for user "postgres"
2020-06-11 08:46:06.094 GMT [152] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
psql: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"
postgresql 08:46:06.09 INFO  ==> Stopping PostgreSQL...
2020-06-11 08:46:06.100 GMT [136] LOG:  received smart shutdown request
2020-06-11 08:46:06.104 GMT [136] LOG:  background worker "logical replication launcher" (PID 143) exited with exit code 1
2020-06-11 08:46:06.104 GMT [138] LOG:  shutting down
2020-06-11 08:46:06.123 GMT [136] LOG:  database system is shut down
```
Thanks in advance!

**Comment by carrodher** [comment]
Hi, in order to reproduce the issue on our side, can you provide more information about how are you installing the chart? It's useful for us to know the changes in the values.yaml or the parameters used via `--set`.

Is it the first installation or did you install it previously? In that case, please take into account you need to remove the PV/PVCs between installation because the randomly generated password is stored in the PV and used in the second installation that is expecting a new random password.

**Comment by hussainsaify** [comment]
Thanks @carrodher for responding. After setting password and user through the chart, pods got started successfully but when installing a fresh chart, pods starts failing due to not being able to initialize postgres data directory. Through init container, I am copying server certificate and  keys inside postgreql data directory and that is the likely cause of pod not getting restarted.

I am attaching my values file. Please let me know in case you need more information
[bitnami-postgresql-values.txt](https://github.com/bitnami/charts/files/4779595/bitnami-postgresql-values.txt)

**Comment by carrodher** [comment]
Installing a fresh chart without removing the PV/PVCs and without setting the password via parameters is going to fail because the new installation is generating a new random password that is different from the one stored in the PV.

So you need to: 1) delete the PV/PVC in order to the new installation using the new random password or 2) set as parameter the password present in the PV

**Comment by hussainsaify** [comment]
Yes, that fixed the issue. But, now I am getting a new issue, if I try to copy SSL keys before data directory initialization then pod fails. For now, I am installing chart without SSL and once it is installed, I am upgrading with SSL enabled and it's working fine.

Do we have a better way of installing chart with SSL other than installing without ssl and then upgrading with SSL?

Thanks,
Hussain

**Comment by carrodher** [comment]
Just to be clear, if you enable SSL in the values.yaml with
```yaml
postgresqlExtendedConf:
  ssl: on
```
and also use an init container to copy the SSL keys with
```yaml
master:
  extraInitContainers:
    - name: move-ca-crts
      image: busybox:1.30.0
      securityContext:
        runAsUser: 0
      command: ['sh', '-c', 'cp /etc/dev-tls-certs/ca.crt /postgresql/data/root.crt && cp /etc/dev-tls-certs/tls.crt /postgresql/data/server.crt && cp /etc/dev-tls-certs/tls.key /postgresql/data/server.key && chmod 600 /postgresql/data/*.crt && chmod 600 /postgresql/data/*.key && chown  1001:1001 /postgresql/data/*.crt  && chown  1001:1001 /postgresql/data/*.key']
      volumeMounts:
        - mountPath: /postgresql
          name: data
        - mountPath: /etc/dev-tls-certs
          name: dev-tls-secret
```
the pod fails. Then your workaround is to set `ssl: off` in the first installation and then upgrade setting this parameter to `on`. Is this the approach you're following? Can you share with us what is the error when you enable everything in the first deployment?

**Comment by hussainsaify** [comment]
@carrodher Yes, you are right I have to first turn SSL off and remove the init container for moving certificates on installation and once installed, turn SSL on and add init container for moving certificates to data directory and upgrade the chart. Below are the error logs if I enable SSL at the time of 1st chart installation.

Logs during pod startup-

postgresql 07:26:17.75 
postgresql 07:26:17.75 Welcome to the Bitnami postgresql container
postgresql 07:26:17.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 07:26:17.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 07:26:17.75 Send us your feedback at containers@bitnami.com
postgresql 07:26:17.76 
postgresql 07:26:17.76 DEBUG ==> Configuring libnss_wrapper...
postgresql 07:26:17.77 INFO  ==> ** Starting PostgreSQL setup **
postgresql 07:26:17.81 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 07:26:17.81 INFO  ==> Loading custom pre-init scripts...
postgresql 07:26:17.82 INFO  ==> Initializing PostgreSQL database...
postgresql 07:26:17.82 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgresql 07:26:17.82 DEBUG ==> Ensuring expected directories/files exist...
postgresql 07:26:17.84 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 07:26:17.84 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 07:26:17.84 INFO  ==> Generating local authentication configuration
postgresql 07:26:17.85 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 07:26:17.85 INFO  ==> Configuring replication parameters
postgresql 07:26:17.87 INFO  ==> Configuring fsync
postgresql 07:26:17.88 INFO  ==> Loading custom scripts...
postgresql 07:26:17.88 INFO  ==> Enabling remote connections
postgresql 07:26:17.89 INFO  ==> Stopping PostgreSQL...
postgresql 07:26:17.89 INFO  ==> ** PostgreSQL setup finished! **

postgresql 07:26:17.93 INFO  ==> ** Starting PostgreSQL **
2020-06-16 07:26:17.949 GMT [1] LOG:  skipping missing configuration file "/postgresql/data/postgresql.auto.conf"
2020-06-16 07:26:17.949 GMT [1] FATAL:  "/postgresql/data" is not a valid data directory
2020-06-16 07:26:17.949 GMT [1] DETAIL:  File "/postgresql/data/PG_VERSION" is missing.

**Comment by carrodher** [comment]
Hi, it seems the `postgresqlDataDir` is not containing the proper data. You are setting it to `postgresqlDataDir: /postgresql/data` and that shouldn't be an issue, for example, I launched a new deployment using this value and the chart is properly initialized and the files are present in the proper folder:
```console
$ ls -la /postgresql/data
total 96
drwx------ 19 1001 1001 4096 Jun 17 06:41 .
drwxrwsr-x  4 root 1001 4096 Jun 17 06:41 ..
drwx------  5 1001 root 4096 Jun 17 06:41 base
drwx------  2 1001 root 4096 Jun 17 06:42 global
drwx------  2 1001 root 4096 Jun 17 06:41 pg_commit_ts
drwx------  2 1001 root 4096 Jun 17 06:41 pg_dynshmem
-rw-------  1 1001 root 1636 Jun 17 06:41 pg_ident.conf
drwx------  4 1001 root 4096 Jun 17 06:46 pg_logical
drwx------  4 1001 root 4096 Jun 17 06:41 pg_multixact
drwx------  2 1001 root 4096 Jun 17 06:41 pg_notify
drwx------  2 1001 root 4096 Jun 17 06:41 pg_replslot
drwx------  2 1001 root 4096 Jun 17 06:41 pg_serial
drwx------  2 1001 root 4096 Jun 17 06:41 pg_snapshots
drwx------  2 1001 root 4096 Jun 17 06:41 pg_stat
drwx------  2 1001 root 4096 Jun 17 06:47 pg_stat_tmp
drwx------  2 1001 root 4096 Jun 17 06:41 pg_subtrans
drwx------  2 1001 root 4096 Jun 17 06:41 pg_tblspc
drwx------  2 1001 root 4096 Jun 17 06:41 pg_twophase
-rw-------  1 1001 root    3 Jun 17 06:41 PG_VERSION
drwx------  3 1001 root 4096 Jun 17 06:41 pg_wal
drwx------  2 1001 root 4096 Jun 17 06:41 pg_xact
-rw-------  1 1001 root   88 Jun 17 06:41 postgresql.auto.conf
-rw-------  1 1001 root  241 Jun 17 06:41 postmaster.opts
-rw-------  1 1001 root   71 Jun 17 06:41 postmaster.pid
```

Can you check if when you're using the init container (and the volume mount at `/postgresql`) the content of this folder is following the above structure? It seems PostgreSQL (as an application) is trying to find some configuration files in that dir that are not present, maybe because the init container volume is overriding it or something.

**Comment by hussainsaify** [comment]
@carrodher The Issue is because of init container, I am copying certificates inside PostgreSQL data directory and during fresh installation Postgres expect the data directory to be empty. That's why when I install without SSL it works, and after that when I upgrade with SSL there are no issues as data directory is already in initialized state.

So, it's a two-step process, first install chart without SSL and then upgrade with SSL enabled. If there was a way to copy the certificate at an alternative path then this issue wouldn't arise.

**Comment by carrodher** [comment]
Hi, yes, at this moment it is not the best approach. We are working on adding SSL support directly to the container image used in this chart, so this issue should be solved soon. With the new approach, it will be possible to handle SSL directly using the default image and some parameters in the chart, as we are already doing in other Bitnami charts. Those changes are going to be applied to the PostgreSQL and PostgreSQL HA charts. We will update this thread once releases, stay tuned.

In the meantime, it seems there is a `PGSSLROOTCERT` env. variable to change the root dir of the certificates, maybe you can mount the certificates in a different place and use this variable. It is something I didn't test, just checked the official docs:
- https://www.postgresql.org/docs/9.3/libpq-envars.html
- https://www.postgresql.org/docs/9.3/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT
But in the end, this is another workaround like the one you used to make it works with a 2-steps process; so I think the definitive solution is going to be part of the new release I previously mentioned.
