### ISSUE TITLE
Invalid redis tag

### ISSUE THREAD

**Issue by jascsch** [bitnami/charts#28134]
### Name and Version

bitnamit/redis 19.6.2

### What architecture are you using?

None

### What steps will reproduce the bug?
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = `helm pull --destination /tmp/98495daa-40dc-43a8-80ca-33a8500bd52c --version 19.6.2 --repo https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami redis` failed exit status 1: Error: invalid_reference: invalid tag

### What is the expected behavior?

The issue does not exist with version 19.6.1

### What do you see instead?

invalid tag version

### Additional information

The redis helm chart with version tag 19.6.2 cannot be pulled. can you please check if something went wrong and tag the version again?

**Comment by carrodher** [comment]
Thanks for reporting the issue, it seems there is something wrong with the index; we'll check it.
Having said that, please note the proper way of consuming Bitnami Helm charts is by using OCI packages from DockerHub:
```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/redis --version 19.6.2
Pulled: registry-1.docker.io/bitnamicharts/redis:19.6.2
Digest: sha256:1f996c79bf42e3dd69abdac6dccbf6d2a6a96aeef89e0e17ee6b28aa20922b6d
```
