### ISSUE TITLE
[bitnami/postgresql-ha] Not able to access postgres externally using ingress

### ISSUE THREAD

**Issue by hussainsaify** [bitnami/charts#2813]
Hi Team,

I have installed postgresql-ha helm chart but not able to access db externally using nginx-ingress.

Client- pgadmin3
Kubernetes- 1.14 (AWS EKS)
Ingress Controller - nginx-ingress
url- postgresql-ha-test.********.com
port- 80

Error-
9:02:01: Error: Error connecting to the server: received invalid response to SSL negotiation: H

Do we need to do anything extra to get it work?

Thanks,
Hussain

**Comment by andresbono** [comment]
Hi @hussainsaify, did you set the `ingress.enabled` flag? Can you share with us the command or values.yaml that you are using to deploy the chart? That would help us reproducing the issue. Please make sure no sensitive information is shared.

**Comment by hussainsaify** [comment]
[postgres-values.txt](https://github.com/bitnami/charts/files/4778973/postgres-values.txt)

Thanks, @andresbono  for responding. I have attached my values file.

Yes, I do have ingress.enabled flag set to true and ingress is getting created. When I try to connect through ingress URL it gives me SSL negotiation error on the ingress controller.

Please let me know if you need more details.

Thanks,
Hussain

**Comment by hussainsaify** [comment]
Also,  following is the command I am using to connect

kubectl run postgresql-ha-test-client --rm --tty -i --restart='Never' --namespace test --image bitnami/postgresql:11 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-test-client=true" \
        --command -- psql -h postgresql-ha-test.**********.com -p 80 -U postgres -d postgres

**Comment by hussainsaify** [comment]
@andresbono Did you get a chance to look into it?

**Comment by andresbono** [comment]
Hi @hussainsaify, we have been checking this issue more in depth and, in principle, with an nginx-ingress, you can't use the ingress rule that the helm chart creates out-of-the-box.

The ingress rule is using the http protocol but postgresql is plain tcp. Both protocols are not compatible. Future versions of this chart will update the templates and documentation to avoid confusion.

Possible solutions for you to expose the service might be using a service of type `LoadBalancer` or exposing TCP ports in the nginx ingress: https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/ (you will need to make sure your ingress controller is running with `--tcp-services-configmap` set)

Let us know if you need more clarifications

**Comment by hussainsaify** [comment]
Thanks @AndreaBeggiato 

Currently, we are using configmap only for forwarding the requests but it gets ugly when you are hosting about 40 databases and forward request to them using different ports. Also, creating a service loadbalancer is too costly as it requires to create a load balancer for each of them.

Is there a better solution to access externally?

**Comment by andresbono** [comment]
Maybe you can launch a single postgresql-ha deployment with multiple databases and credentials, that way, you will need to expose a single port only and you can manage all the databases in a unified way.
