### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Adding annotations to stream deployment

### ISSUE THREAD

**Issue by dadacom379** [bitnami/charts#28155]
### Name and Version

bitnami/spring-cloud-dataflow 30.0.0

### What is the problem this feature will solve?

At the moment it is not possible to add annotations to a deployment. In my example trying to put in place a Kubernetes reloader when a configMap or secret is changing 

### What is the feature you are proposing to solve the problem?

Is it possible to add a feature like the existing one?

deployer.*.kubernetes.job-annotations=reloader.stakater.com/auto:"true"
deployer.*.kubernetes.pod-annotations=reloader.stakater.com/auto:"true"
deployer.*.kubernetes.service-annotations=reloader.stakater.com/auto:"true"
Like a configuration that could be deployer.*.kubernetes.deployment-annotations=reloader.stakater.com/auto:"true"

Then when a injected configMap or secret change the deployment restart

![image](https://github.com/user-attachments/assets/dc5c6e4f-c2b3-4a3b-9e81-4e683289e743)

?

### What alternatives have you considered?

At this time the alternative was to execute a Kubectl command

- kubectl annotate deployment --all reloader.stakater.com/auto="true" -n my-namespace

**Comment by javsalgar** [comment]
Hi!

In other charts we have the deploymentAnnotations or statefulsetAnnotations value depending on the application. Would you like to submit a PR adding support for this value?

**Comment by dadacom379** [comment]
Im on holiday ass hold
