### ISSUE TITLE
[bitnami/keycloak] Proxy Headers ENV breaks installs

### ISSUE THREAD

**Issue by adryan30** [bitnami/charts#28154]
### Name and Version

bitnami/keycloak

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install chart at version 21.7.0

### Are you using any custom parameters or values?

Via values.yaml:
```yaml
proxy: edge
proxyHeaders: #Leave empty
```

### What is the expected behavior?

The chart should work normally

### What do you see instead?

The pod displays an error:
`ERROR ==> The value of KEYCLOAK_PROXY_HEADERS should be either empty, 'forwarded' or 'xforwarded'`

### Additional information

I believe this error is caused by this PR #27890, more specifically on file `bitnami/keycloak/templates/configmap-env-vars.yaml`, the default for env `KEYCLOAK_PROXY_HEADERS` seems to break the install.

**Comment by adryan30** [comment]
Temporary fix can be achieved by setting `proxyHeaders` in `values.yaml`

**Comment by andresbono** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by spirosagr** [comment]
Has there been any progress concerning this or any other workarounds? Our issue is that although with xforwarded keycloak seems to work, because our keycloak is behind a load balancer with SSL termination we can't access the administrator UI anymore.

**Comment by andresbono** [comment]
Does it makes sense that you open a new GitHub issue where you detail your particularities? Not sure if your case is 100% related to this issue.

In any case, please, check if your problems persist with the latest version of the chart, there has been some recent updates that may be related: https://github.com/bitnami/charts/commits/main/bitnami/keycloak.

**Comment by gregth** [comment]
I'm also facing this issue.

**Comment by andresbono** [comment]
@gregth, can you share more details? What is the version of the chart you are using? What are the values.yaml you are passing?
