### ISSUE TITLE
[bitnami/odoo] Set external database for Odoo Charts, after install module hangs and not start anymore

### ISSUE THREAD

**Issue by mrfzy00** [bitnami/charts#28150]
### Name and Version

bitnami/odoo:17.0.20240605

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. re-deploy the charts
2. delete deployments
3. change the database connection, even 4 - 5 times
4. back to step 1 again

### Are you using any custom parameters or values?

no.

### What is the expected behavior?

While pooling form externalDB, the database connection not dropping or get some warning logs:

`WARNING tools_odoo odoo.service.server: Thread <Thread(odoo.service.http.request.132344904144576, started 132344904144576)> virtual real time limit (185/150s) reached` 

We're expecting on process instalation of module we don't have any issues on virtual real time limit. Or while restarting we don't have to wait pooling connection to external database.

### What do you see instead?

```
WARNING tools_odoo odoo.service.server: Thread <Thread(odoo.service.http.request.132344904144576, started 132344904144576)> virtual real time limit (185/150s) reached
```

### Additional information

Since we're already testing to use a postgresqlpooler in sidecar container setup, it seems the Database still shown a warning above, do we have some misconfiguration or not? or do you have any alternative to implement?

**Comment by mrfzy00** [comment]
hi, sorry for late reply

i'm trying to load the debug mode from the charts, and it seems why the load from odoo keeps failing.

causes from the liveness probe and readiness probe taking below than 5 minutes, but odoo still initializing modules from the DB. so in case of that i increase the rate of probe period to take time for the odoo initialize the modules.

i can't say its solved, but for now its the best solution i get right now.

**Comment by javsalgar** [comment]
Hi,

The question would be why it is taking that long to initialize that externaldb. Does it happen with other applications that access the db? In this sense, if the bundled db does not have that issue, I'd check with the maintainers of the external db

**Comment by mrfzy00** [comment]
Thanks for the reply

We host the External DB on GCP, using CloudSQL (PostgreSQL). In other apps
it doesn't have behaviour like Odoo, connect as expected. But while it was
at Odoo it took times.
