### ISSUE TITLE
[bitnami/postgresql] Please Add Service Type for metrics in bitnami/postgres

### ISSUE THREAD

**Issue by AnkitDwivedi74** [bitnami/charts#28160]
### bitnami/postgresql and latest

latest

### What is the problem this feature will solve?

currently, we can not use db metrics outside the cluster by default as bitnami/postgres-ha has. bitnami/postgres only have ClusterIP

### What is the feature you are proposing to solve the problem?

like I have a Prometheus in VM and I want to make a dashboard on that time, but I can not consume metrics directly from the cluster because of cluster IP  so here I need port forwarding 

### What alternatives have you considered?

by using service type NodePort or Loadbalacer can consume metrics directly. add feature for service type in values file

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. It should be a matter of exposing something like metrics.service.type. Would you like to submit a PR adding support for it? If not I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA.
