### ISSUE TITLE
[bitnami/postgresql-ha]: improper password sanitation in pgpool

### ISSUE THREAD

**Issue by Karitham** [bitnami/charts#28179]
### Name and Version

bitnami/pgpool (tested from 4.4.5 to latest)

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set admin password for pgpool in postgreslql-ha to `(z=3U+<zGb2K5y9C4vA$@%FrKquU35X=yBC@%+;<`, see it exit without any error. (I don't have the time to reproduce the exact password, see below for other possible options of which password is the actual culprit; sorry)

### Are you using any custom parameters or values?

I'm using postgresql-ha as a dependency to another chart so I can't exactly share the full configuration; but I only set these values `postgresql-ha.pgpool.adminPassword` `postgresql-ha.postgresql.password` `postgresql-ha.postgresql.postgresPassword` `postgresql-ha.postgresql.repmgrPassword`

Optionally, here are the default values by the helm chart I'm using too. <https://gitea.com/gitea/helm-chart/src/branch/main/values.yaml#L533-L551>

### What is the expected behavior?

don't exit 0 or 1 (depending on pgpool image version)

### What do you see instead?

depending on the pgpool version I see either *nothing* or some random error about the password file not existing

### Additional information

The process of fixing the bug for me was rotating all my passwords related to postgresql-ha in any way to passwords that don't contain any special characters.

**Comment by rafariossaa** [comment]
Could you enable debug and share the logs ?

**Comment by Karitham** [comment]
I'm not going to be available enough to help debug this, and with it being not reported before I can only assume it was a misconfiguration on my end. Eg my secret conveniently turned out empty due to some typo in yaml. It would explain the vague warning about the password file not existing I guess.
