### ISSUE TITLE
Broken link in Osclass readme

### ISSUE THREAD

**Issue by bsvihovec** [bitnami/charts#2817]
**Which chart**:
Osclass - 7.0.17

**Describe the bug**
The following link in the readme - https://osclass.org/ - does not load correctly.

**To Reproduce**
1. Go to https://github.com/bitnami/charts/blob/master/bitnami/osclass/README.md
2. Click on Osclass (first word of the readme)
3. See error

**Expected behavior**
The link to load correctly.

**Comment by joancafom** [comment]
Hi @bsvihovec 

The URL is correct and I fear that this is actually related to the official web itself, which seems to be inactive 🤔

Thanks for reporting!
