### ISSUE TITLE
Keydb Container Image and Helm Chart

### ISSUE THREAD

**Issue by viju2008** [bitnami/charts#28184]
### Name and Version

NEW Chart request

### What is the problem this feature will solve?

Keydb is a fork of redis and its growing in popularity

Bitnami can add a container image or helm chart of keydb so that the bitnami hardended container image could be used 

### What is the feature you are proposing to solve the problem?

Keydb is a fork of redis and its growing in popularity

Bitnami can add a container image or helm chart of keydb so that the bitnami hardended container image could be used 

### What alternatives have you considered?

There is no alternative on bitnami

**Comment by carrodher** [comment]
Thank you for your suggestion!

We truly appreciate your input. Our team will now conduct an internal review to assess the viability of integrating this new open-source product into our catalog. As we have limited resources, please understand that this evaluation process might take some time. To ensure that your idea receives the attention it deserves, we will apply the 'on-hold' label. This will prevent our automated system from prematurely closing the issue.

We will keep you updated on any developments regarding the addition of this product. Your patience and understanding are greatly appreciated.

**Comment by prashant1ingle** [comment]
The container image and helm of keydb will be helpful for us

**Comment by bmartin13** [comment]
Looks like latest stable version is: v6.3.4

Officially referenced Helm chart: https://artifacthub.io/packages/helm/enapter/keydb

**Comment by SergkeiM** [comment]
@bmartin13 

There is a [thread](https://github.com/Snapchat/KeyDB/issues/669) on KeyDB that Author doesn't have time to maintain this chart. And is not Archived, KeyDB Team doesn't have bandwidth to maintain there own chart: https://github.com/Snapchat/KeyDB/issues/669#issuecomment-1714319925

**Comment by carrodher** [comment]
Thanks, there are plans to add it to the catalog. Although I can't provide an exact ETA, it could be available during September.

**Comment by SergkeiM** [comment]
Hi @carrodher Great news, thank you.

**Comment by viju2008** [comment]
It will be very helpful to have this image in bitnami

**Comment by viju2008** [comment]
Hello,, Team any update . We are eagerly waiting for its release in september

**Comment by juan131** [comment]
The container is now available, see:

- https://github.com/bitnami/containers/commit/a45a7a5040f6399852e796b19a25d34429eb1e68
- https://hub.docker.com/layers/bitnami/keydb/6.3.4-debian-12-r0/images/sha256-48bb5e01493820ccd5e13114c059c53324870746e82230c34b8e67de86cf98f6?context=explore

We're working on the chart release now.

**Comment by juan131** [comment]
The KeyDB chart is now available in the catalog.
