### ISSUE TITLE
[bitnami/cassandra] How to setup and configure multiple users

### ISSUE THREAD

**Issue by alexbrand** [bitnami/charts#2818]
**Which chart**:
Cassandra v5.4.2

**Is your feature request related to a problem? Please describe.**
I need to configure multiple user credentials in my Cassandra database.

**Describe the solution you'd like**
Currently, it is only possible to set the admin user/password of the database. 

While it is possible to provide custom cql scripts that run when the container starts up via `initDBConfigMap`, this functionality only supports ConfigMaps and not Kubernetes Secrets. For this reason, I cannot use this feature to provide a cql script that sets up users/passwords.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feature request. Indeed, I believe that we should allow both configmaps and secrets (just like we do in other charts). I will open a task for adding the feature. While we cannot guarantee an ETA, I will update this ticket as soon as I have more news. If you want to speed up the process, feel free to send a PR.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that I created a PR that fixes it. Feel free to take a look: https://github.com/bitnami/charts/pull/2900
