### ISSUE TITLE
[MySQL] Default documentation contains bash script, but executes it via `sh`

### ISSUE THREAD

**Issue by florian-besser** [bitnami/charts#28195]
### Name and Version

oci://registry-1.docker.io/bitnamicharts/mysql:11.1.4

### What architecture are you using?

ARM64

### What steps will reproduce the bug?

1. Follow https://github.com/bitnami/charts/blob/main/bitnami/mysql/README.md
2. Specifically use the following scriptlet in your helm chart:
```yaml
initdbScripts:
  my_init_script.sh: |
    #!/bin/sh
    if [[ $(hostname) == *master* ]]; then
      echo "Master node"
      mysql -P 3306 -uroot -prandompassword -e "create database new_database";
    else
      echo "No master node"
    fi
```
(This is an exact copy from the docs)

### What is the expected behavior?

The script should work without any error, and create `new_database` on the master node.

### What do you see instead?

Since the script is executed by `/bin/sh` it prints 
```
/bin/sh: 2: [[: not found
```

This is correct as per my understanding the POSIX shell does not know `[[`, it only knows `[`

### Additional information

I believe today `bash` is widely adopted, as such instead of rewriting the script to be POSIX compliant it might be easier to just execute it using `/usr/bin/bash`

Additionally, I would make the following two and a half changes to the script:
1. The script uses `-uroot -prandompassword`, would suggest changing to `-uroot -p"$MYSQL_ROOT_PASSWORD"` as that variable is available.
2. An even better alternative than `MYSQL_ROOT_PASSWORD` would be to use:
```bash
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
                  fi
```
3. Replace `master` in the script with `primary` as the default name for the `primary` host is now "primary", and no longer "master"

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by florian-besser** [comment]
I have contributed on https://github.com/bitnami/charts/pull/27877 but still waiting for review - after that has been given some attention I'd consider opening another one.

**Comment by florian-besser** [comment]
Raised PR as requested.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
