### ISSUE TITLE
[bitnami/mariadb-galera] Bootstrap controller pod

### ISSUE THREAD

**Issue by pozniakas** [bitnami/charts#28198]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

A need for manual intervention to recover the database after a failure.

### What is the feature you are proposing to solve the problem?

A bootstrap controller pod which is responsible for automating these manual processes described in the documentation (Checking safe_to_boostrap, Only one node with safe_to_bootstrap: 1, All the nodes with safe_to_bootstrap: 0):
https://github.com/bitnami/charts/blob/main/bitnami/mariadb-galera/README.md#checking-safe_to_boostrap

This would allow us to restore the database without any manual intervention and ensure its latest state. Of course, a pod like this should be optional and only enabled through Helm Chart values.

I believe I could do it myself and contribute to the MariaDB Galera community, but firstly I would like to discuss if this is needed and what risks it could bring. :)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by pozniakas** [comment]
But I would also like to get input from your side. If you see this as a needed solution or what risks do you see here? Maybe there is something I should know before trying to implement

**Comment by rafariossaa** [comment]
Hi @pozniakas,
  Something like that would be great, but as you indicated there would be risks in an automated recovering. Some automation should be possible in a controller, but we didn't want to create an operator due its complexity.
  As with all database assets, the main risk is data loss. Handling the recovery is a delicate with many things that can go wrong process.
  I am interested in what would be the approach and the user experience. Could you elaborate a bit on these aspects ?
