### ISSUE TITLE
[bitnami/kube-prometheus] chart's operator.kubeletService doesn't create a service for kubelet

### ISSUE THREAD

**Issue by ahmadidev** [bitnami/charts#28205]
### Name and Version

bitnami/kube-prometheus 9.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?
```
helm install bitnami/kube-prometheus -f values.yaml --dry-run
```
### Are you using any custom parameters or values?
```
operator:
  kubeletService: true
```
### What is the expected behavior?

Should create a Service as the document pointed out.
https://github.com/bitnami/charts/blob/159035583e70a5ded7d1b7aea22978e022c79660/bitnami/kube-prometheus/values.yaml#L526-L530

### What do you see instead?

It only sets `--kubelet-service` argument to the operator container args.
https://github.com/bitnami/charts/blob/159035583e70a5ded7d1b7aea22978e022c79660/bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml#L83-L85

**Comment by javsalgar** [comment]
Hi,

This is because it is the prometheus-operator the one that creates the service, not the helm chart itself. So you should expect the operator, once deployed, to create the service.

**Comment by ahmadidev** [comment]
Thanks for the clarification.
