### ISSUE TITLE
[bitnami/haproxy] missing deploymentAnnotations

### ISSUE THREAD

**Issue by tommyjcarpenter** [bitnami/charts#28225]
### Name and Version

bitnami/haproxy 2.0.13

### What architecture are you using?

None

### What steps will reproduce the bug?

see https://github.com/bitnami/charts/tree/main/bitnami/haproxy

there is service.annotations, common, ingress, and pod. but if you want to add an annotation ONLY onto the deployment, there seems no way to do that. our use case is `reloader.stakater`. see https://github.com/stakater/Reloader?tab=readme-ov-file#secret

We are abusing `common` but it adds this annotation onto EVERYTHING which isnt what we want. 

### What is the expected behavior?

somewhere to put deployment.Annotations

### What do you see instead?

nowhere to put deployment.Annotations

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by tommyjcarpenter** [comment]
@carrodher PR is up :)

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
