### ISSUE TITLE
[bitnami/etcd] readiness probe failed then rbac is disabled on AKS cluster

### ISSUE THREAD

**Issue by braghettos** [bitnami/charts#28228]
### Name and Version

bitnami/etcd 10.2.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm install etcd-test krateo/etcd -n krateo-system --set auth.rbac.create=false`

### Are you using any custom parameters or values?

`--set auth.rbac.create=false`

### What is the expected behavior?

Etcd is running and readiness probe is satisfied.

### What do you see instead?

When I describe etcd pod:
```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  2m22s (x1613 over 4h)  kubelet  (combined from similar events): Readiness probe failed: {"level":"warn","ts":"2024-07-23T19:49:17.497755Z","logger":"client","caller":"v3@v3.5.14/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004fc000/etcd-test-0.etcd-test-headless.krateo-system.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
etcd-test-0.etcd-test-headless.krateo-system.svc.cluster.local:2379 is unhealthy: failed to commit proposal: etcdserver: user name is empty
Error: unhealthy cluster
^[[38;5;6metcd ^[[38;5;5m19:49:17.49 ^[[0m^[[38;5;1mERROR^[[0m ==> Unhealthy endpoint!
```
### Additional information

This issue is not happening in kind. I found this issue on an AKS cluster.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by braghettos** [comment]
@carrodher I think it is related to the Helm chart, in particular to the readiness script, because it is trying to make a commit with a username that does not exist because the RBAC is disabled (as made possible via the same Helm chart). I will check the script's content and give you feedback.
