### ISSUE TITLE
[bitnami/mongodb-sharded] Support for external mongos

### ISSUE THREAD

**Issue by taylorsmithgg** [bitnami/charts#2827]
**Which chart**:
bitnami/mongodb-sharded

**Describe the bug**
I am currently having issues finding a working configuration for connecting the mongos templates to an external Mongo cluster.

**To Reproduce**
Deploy mongos with an external configuration.

**Expected behavior**
Mongos should connect to external mongo cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am currently trying to authenticate using a keyfile.
I have mapped my config servers and when passing the keyfile, I receive a message:
```
exception: connect failed
```

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. I didn't think about just deploying a set of mongos. That's something that we could add it in the chart.  I'm not sure about the cause of the error above, don't you have any other log or message that could provide more clues about the issue?

**Comment by javsalgar** [comment]
Hi.

I created a PR for your case. Feel free to take a look https://github.com/bitnami/charts/pull/2901
