### ISSUE TITLE
Use existing volume claim for elastic master/data

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#2833]
I'd like to be able to use an existing volume claim, or at least specify the PV to be bound for elasticsearch master and data. Is there currently away to do either of these?

**Comment by miguelaeh** [comment]
Hi @zenbones ,
It seems that currently, we are not supporting it.
Please feel free to send a PR and we will be pleased to review it.

**Comment by zenbones** [comment]
pr merged
