### ISSUE TITLE
[bitnami/grafana] document setting up SMTP for Grafana chart

### ISSUE THREAD

**Issue by andrei-dascalu** [bitnami/charts#2834]
**Which chart**:
bitnami/grafana

**Describe the bug**
SMTP user/pass can be set either through dedicated variables or through an existing secret with configurable keys, the SMTP can be enabled/disabled via a flag. However, I can't find how to provide the SMTP server address.

**To Reproduce**
1. Go to https://github.com/bitnami/charts/blob/master/bitnami/grafana/values.yaml
2. Doesn't seem to be a value for providing SMTP server address

**Expected behavior**
Have a parameter to provide smtp server address

** Additional information **

I've tried configuring SMTP in 2 ways: 

1. using the exposed values
2. using a custom.ini config
REgarding the custom.ini config, I've created a Secret rather than a configmap and used the following:

```
 --set config.useCustomIniFile=true \
 --set config.customIniSecret=grafana-custom-ini \
```

The custom.ini appears with the correct content at `/opt/bitnami/grafana/conf/custom.ini` but it seems to be ignored, as the section of smtp looks like:

```
[smtp]
enabled = true
host = smtp.eu.mailgun.org:587
user = postmaster@mailgun.<whatever>.com
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = <whatever>
;cert_file =
;key_file =
;skip_verify = false
from_address = noreply-grafana@<whatever>.com
from_name = Grafana
# EHLO identity in SMTP dialog (defaults to instance_name)
ehlo_identity = grafana.<whatever>.com
```

all the configuration items are tested and working, using the same custom.ini and mounting in the official Grafana docker container works as expected. I am not sue whether it's something with the helm chart or the bitnami Grafana docker image.

**Comment by dani8art** [comment]
Hi @andrei-dascalu thank you for opening the issue.

There is another way to pass configuration properties to grafana, you can use envvars with the following pattern `GF_<section>_<property>` and the chart have the `extraEnvVars` feature. So I think you could try:

```console
--set smtp.enabled=true
--set smtp.user=user
--set smtp.password=pass
--set extraEnvVars[0].name=GF_SMTP_HOST,extraEnvVars[0].value=yourhost.com
```
