### ISSUE TITLE
[bitnami/postgresql-ha] Is there a way to sync credentials between pgpool and postgresql (without LDAP)?

### ISSUE THREAD

**Issue by ttinkr** [bitnami/charts#2836]
**Which chart**:
bitnami/postgresql-ha 3.2.10

**Is your feature request related to a problem? Please describe.**
Maybe there is already a way or maybe I am just not understanding how things work correctly. But when I deploy postgresql with pgpool I need the same sets of credentials for the database on both systems. It seems like there is no way to include a secret or something that acts as a common set of credentials for database access. There is the option to use the "existingSecret", but this only pre-populates the files as I understand. But after deployment, how can I create an account and make it persistent on both systems, especially on pgpool? As soon as I restart, all the accounts are gone because there is no secret or PVC where this is saved. How can I run this in production when it looses all the accounts every time the Pod gets recreated?

**Describe the solution you'd like**
A PVC or even better a secret that gets shared between postgresql and pgpool instances that updates the user accounts on both systems. Not just a one-time configuration, but a steady sync between secret and i.e. pgpool_passwd file.

**Describe alternatives you've considered**
I am open for any recommendation how to solve this without having to create a startup script that creates the users every time pgpool starts up.

Thanks for making great charts! I really think that your charts are some of the best ones out there!
Thomas

**Comment by juan131** [comment]
Hi @ttinkr 

I noticed you also commented in this issue https://github.com/bitnami/charts/issues/1631. Let's move the conversation there to avoid duplications.
