### ISSUE TITLE
Schema registry authentication 

### ISSUE THREAD

**Issue by stefannmih** [bitnami/charts#28431]
### Name and Version

bitnami/schema-registry:7.3/debian-12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello,

I am trying to follow the confluent documentation to enable the [HTTP basic authentication](https://docs.confluent.io/platform/current/schema-registry/security/index.html#configuring-the-rest-api-for-basic-http-authentication). As presented here, I need to configure the following settings:
```
authentication.method=BASIC
authentication.roles=<user-role1>,<user-role2>,...
authentication.realm=<section-in-jaas_config.conf>
```

Following also this [documentation](https://docs.confluent.io/platform/current/installation/docker/config-reference.html#sr-long-configuration), should let me add the above settings as:
```yaml
extraEnvVars:
  - name: SCHEMA_REGISTRY_AUTHENTICATION_ROLES
    value: <value>
  - name: SCHEMA_REGISTRY_AUTHENTICATION_METHOD
    value: 'BASIC'
  - name: SCHEMA_REGISTRY_AUTHENTICATION_REALM
    value: <value>
```
The thing that I noticed is that the bitnami helm chart for the Confluent Schema registry does not add these parameters with my values in the schema-registry.properties. Going further I found that the image for the schema registry uses this [script](https://github.com/bitnami/containers/blob/main/bitnami/schema-registry/7.3/debian-12/rootfs/opt/bitnami/scripts/schema-registry-env.sh) to write the environment variables. 

It seems like the docker image does not know what to do with other environment variables than the ones in the schema-registry-env.sh

My questions are:
1. Am I doing something wrong in setting the basic auth to the schema registry?
2. Is there any other way to set up basic auth for the schema registry? I was able to set the authentication using: 
```yaml
 configuration: |-
   authentication.method = BASIC
   authentication.realm = KafkaClient
   authentication.roles = admin
   ...
```
However, this is not the best approach due to the fact that I am also using SASL and the credentials for the schema registry to authenticate to kafka will be visible

### What is the expected behavior?

Set up basic HTTP authentication with users taken from a secret

### What do you see instead?

The extra environment variables declared by me appear in the pod configuration, however,  they have no impact.

**Comment by carrodher** [comment]
Did you take a look at those parameters to configure Kafka auth in Schema Registry? https://github.com/bitnami/charts/tree/main/bitnami/schema-registry#enable-authentication-for-kafka

**Comment by stefannmih** [comment]
Yes. That describes the authentication from schema registry to kafka. I'm looking for a way to authenticate from client to schema registry.

**Comment by stefannmih** [comment]
Did you get the chance to look into it?

**Comment by dgomezleon** [comment]
Hi @stefannmih ,

Sorry for the delay, we have a lot of cases to check these days. I will provide you with an answer today.
