### ISSUE TITLE
Moodle site restore can't log in

### ISSUE THREAD

**Issue by samgabrail** [bitnami/charts#2846]
**Which chart**:
Moodle chart moodle-7.2.14, APP Version 3.8.3

**Describe the bug**
Can't log in to moodle after a site restore of the mariadb and the moodledata folder.

**To Reproduce**
I'm trying to restore my Moodle site. I used phpmyadmin to import a mariadb database that I had backed up using mysqldump command:
```
mysqldump -u bn_moodle --password=xxxx -C -Q -e --create-options bitnami_moodle > /tmp/backup.sql
```

I also restored the moodledata folder which I had backed up. The following error is seen in the logs when I attempt to login with my username and password. I expected to be able to log in.

```
Warning: require_once(/bitnami/moodle/user/profile/field/afaqr/field.class.php): failed to open stream: No such file or directory in /bitnami/moodle/user/profile/lib.php on line 571

Fatal error: require_once(): Failed opening required '/bitnami/moodle/user/profile/field/afaqr/field.class.php' (include_path='/bitnami/moodle/lib/pear:.:/opt/bitnami/php/lib/php') in /bitnami/moodle/user/profile/lib.php on line 571
```

**Expected behavior**
To log in to the site

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @samgabrail 

Could you please provide information about what steps you performed to restore the moodledata folder?

**Comment by samgabrail** [comment]
Hi @juan131 

I tested logging into the site before and after restoring the moodledata folder and got the same result. I also tested everything using docker-compose and got the same error.

Here are the steps I took to backup and restore the moodledata folder:
## Backup Script

```shell
#!/bin/bash
DATE=`date +%Y-%m-%d-%T`
POD=$(/usr/local/bin/kubectl -n courses-tekanaid get pod -l app=courses-tekanaid-moodle -o jsonpath="{.items[0].metadata.name}")
/usr/local/bin/kubectl cp courses-tekanaid/$POD:/bitnami/moodle/moodledata /tmp/moodledata
zip -r /tmp/moodledata-$DATE.zip /tmp/moodledata
/usr/local/bin/aws s3 cp /tmp/moodledata-$DATE.zip s3://tekanaid-moodle-backup/
rm /tmp/moodledata-$DATE.zip
```

## Moodle data files Restore

```shell
POD=$(/usr/local/bin/kubectl -n courses-tekanaid get pod -l app=courses-tekanaid-moodle -o jsonpath="{.items[0].metadata.name}")
kubectl cp /Users/sam/Deployments/Personal/backups/moodledata-2020-04-18-22_15_01.zip $POD:/bitnami/moodle
kubectl exec -it $POD bash
apt update
apt install unzip vim -y
unzip moodledata-2020-04-18-22_15_01.zip
mv /bitnami/moodle/moodledata /bitnami/moodle/moodledata-old
mv /bitnami/moodle/tmp/moodledata /bitnami/moodle/
```

**Comment by samgabrail** [comment]
Ok, I found the issue. It turned out to be an issue with an afaqr field which has to do with the a2fa authentication plugin. I had to go into the database with PHPMyAdmin and delete that row in the mdl_user_info_field table.

**Comment by juan131** [comment]
Great @samgabrail !! I'm very glad you were able to identify and solve the issue!

**Comment by leandrobocon** [comment]
> Ok, I found the issue. It turned out to be an issue with an afaqr field which has to do with the a2fa authentication plugin. I had to go into the database with PHPMyAdmin and delete that row in the mdl_user_info_field table.

Thanks. Today I had the same problem and applied what you said. Solved!
