### ISSUE TITLE
Issue with Co-locating Arbiter Pods in MongoDB Sharded Chart

### ISSUE THREAD

**Issue by Chriskuiper1** [bitnami/charts#28506]
### Name and Version

bitnami/mongodb-sharded

### What architecture are you using?

amd64

### What steps will reproduce the bug?

**Issue Summary:**
We are experiencing difficulties in deploying Arbiter pods on the same nodes as their corresponding shard data pods in our Kubernetes cluster, using the Bitnami MongoDB Sharded Helm chart. Our intended node structure requires each shard and its associated Arbiter to reside on the same node.

**Current Setup:**

Node Labeling: We have labeled our nodes to identify which shard should run on them, using the following convention: pool: shardX, where X is the shard number.

Node Selector for Shards: The following nodeSelector is used to assign shard data pods to the appropriate nodes:

```yaml
nodeSelector: {
  pool: "shard{{ .dataNodeLoopId }}"
}
```

This method successfully places data pods on the correct nodes as per the shard labels.

**Problem Description:**
However, we encounter issues when trying to place the Arbiter pods on the same nodes as their corresponding shard data pods. 

### What is the expected behavior?

**Expected Result:**
We expect the Arbiter pods to be co-located with their corresponding shard data pods, resulting in the following deployment pattern:

**Node 1:**
data0-shard0
data1-shard0
arbiter0-shard0

**Node 2:**
data0-shard1
data1-shard1
arbiter0-shard1

**Request:**
We need a solution to dynamically and correctly match Arbiter pods with their corresponding shard data pods on the appropriate nodes. This should maintain the intended shard-specific node structure, ensuring that each Arbiter runs on the same node as its shard.

### What do you see instead?

We tried two approaches:

**Method 1: Using dataNodeLoopId**

```yaml
nodeSelector: {
  pool: "shard{{ .dataNodeLoopId }}"
}
```

Issue: This method results in an incorrect label "pool: shard", indicating that dataNodeLoopId is not accessible or not being interpolated correctly in the Arbiter context.

**Method 2: Using arbiterLoopId**

```yaml
nodeSelector: {
  pool: "shard{{ .arbiterLoopId }}"
}
```

Issue: This configuration places all Arbiter pods on nodes labeled with "pool: shard0", which means that all Arbiter pods are assigned to the node designated for shard0, regardless of their corresponding shard data pods.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
