### ISSUE TITLE
[bitnami/thanos] Add integration for Thanos Ruler with PrometheusRule via ruleSelector

### ISSUE THREAD

**Issue by kaiohenricunha** [bitnami/charts#28525]
### Name and Version

bitnami/thanos latest

### What is the problem this feature will solve?

The current configuration only allows Ruler to interact with recordings and alertings via configmap, a big no if a project is already running hundreds of records of PrometheusRules to manage Prometheus records and alerts.

### What is the feature you are proposing to solve the problem?

Just like in the kube-prometheus-stack, using [rulerSelector](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L4467) for discovering rules will make the overall experience much more easier to automate.

### What alternatives have you considered?

Using the kube-prometheus-stack just to deploy the Thanos Ruler, which wouldn’t be the best option…

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by kaiohenricunha** [comment]
> Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).
> 
> Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Isn't there any workaround for this?

**Comment by tchatzig** [comment]
any news with this?
Is this planned as a future improvement?

**Comment by mrBlackhat** [comment]
i also am curious,i have prometheus rules managed by prometheus-operator, how to make thanos ruler aware of them if ruleSelector is not implemented?
