### ISSUE TITLE
[bitnami/redis] Add RedisJSON module to Redis / Redis-Cluster

### ISSUE THREAD

**Issue by Praveen-98cs** [bitnami/charts#28528]
### Name and Version

bitnami/redi-cluster:latest

### What is the problem this feature will solve?

modules such as RedisJSON, RedisSearch are not available in bitnami redis-cluster deployments and you can't load them because of this.  Because of this you can't add JSON type data to redis. 

### What is the feature you are proposing to solve the problem?

I am proposing to add these modules to work with the redis-cluster deployments and be able to load the modules.

### What alternatives have you considered?

I have tried this way by following this [stackoverflow solution](https://stackoverflow.com/questions/65087705/is-it-possible-to-load-a-redis-module-redisbloom-onto-a-redis-helm-chart-bitn). 

I made this custom image

```Dockerfile
FROM redis/redis-stack:latest AS builder

FROM bitnami/redis-cluster:latest
COPY --from=builder /opt/redis-stack/lib/rejson.so /usr/lib/redis/modules/rejson.so

CMD ["/run.sh", "--loadmodule", "/usr/lib/redis/modules/rejson.so"]
```

and pushed this image to the dockerHub and then i used that image when installing the helm chart of bitnami redis-cluster chart and added these changes in the values.yaml

1. change the image data
2. Add these configs

```yaml
  configmap: |
    enable-module-command yes
    loadmodule /usr/lib/redis/modules/rejson.so
```
Then the RedisJSON module got added. But I don't know whether this method is allowed depending on the licensing, But I only got the jsonmodule. 

is this possible?

**Comment by javsalgar** [comment]
Hi,

This is something that we evaluated in the past, and we found that we could not package these modules for license reasons.

**Comment by Praveen-98cs** [comment]
Hi,

So, is there any solutions you have come up with? maybe using a different way to add JSON data? any alternatives?

Thank you.

**Comment by Praveen-98cs** [comment]
Seems like using this way for internal purposes would be fine but to provide as a service it will be a license issue. Anyways HASH can be used to store JSON like way to enter data so that way seems okay for now.
