### ISSUE TITLE
[bitnami/keycloak] Mariadb Support

### ISSUE THREAD

**Issue by yeplaa** [bitnami/charts#28529]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

I would use Mariadb stack as Database backend of Keycloack Chart. Currently, mariadb is not recommended as external database (https://github.com/bitnami/charts/tree/main/bitnami/keycloak#use-an-external-database). Moreover, it's supported by Keycloak (https://www.keycloak.org/server/db)

### What is the feature you are proposing to solve the problem?

Is it possible that mariadb be supported with Helm chart externaldatabase feature?

**Comment by yeplaa** [comment]
Do you think it's possible @javsalgar?

Thanks

**Comment by carrodher** [comment]
Thanks for your suggestion, at this moment, and given other priorities in the team, there are no immediate plans to work on this feature.

**Comment by RGRDigit** [comment]
Hello,
Same issue here :(
I wanted to add keycloak to an existing project where MariaDB is already deployed.
So I was hopping that I will be able to capitalize on our knowledge and pipelines to deploy a new instance of Maria.

I there really no plans to work on this feature in your roadmap ?
Do you thing that as a user I can plug your chart helm and a Maria in a different way ?

Thanks by advance for your help.

**Comment by javsalgar** [comment]
Hi!

The first thing to check would be the bitnami container, so it allows using an external database for MariaDB. Probably it would require changes here. https://github.com/bitnami/containers/blob/main/bitnami/keycloak/25/debian-12/rootfs/opt/bitnami/scripts/libkeycloak.sh

If this is implemented, then the chart could be changed to allow an external MariaDB database. As my colleague mentioned, I'm afraid we do not have short term plans to work on it, but contributions are welcome. If someone from the community wants to explore this and submit a PR, we will review it, speeding up the whole process.
