### ISSUE TITLE
bitnami/prometheus - server configmap gets even when server.existingConfigmap is set.

### ISSUE THREAD

**Issue by ib-ak** [bitnami/charts#28531]
### Name and Version

bitnami/prometheus 1.3.14

### What architecture are you using?

amd64

### What steps will reproduce the bug?

set  `server.existingConfigmap` to an existing server config cm.

### What is the expected behavior?

server configmap should not be created

### What do you see instead?

A new server configmap gets created

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
