### ISSUE TITLE
[bitnami/wordpress] customPostInitScripts doesn't run as root 

### ISSUE THREAD

**Issue by noatudor** [bitnami/charts#28534]
### Name and Version

bitnami/wordpress 23.0.11

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Deploy Helm Chart with Custom Values Below

### Are you using any custom parameters or values?

```yaml
containerSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false

volumePermissions:
  enabled: true
  containerSecurityContext:
    seLinuxOptions: {}
    runAsUser: 0
```

### What is the expected behavior?

`whoami` should output root so I can execute root commands

### What do you see instead?
```
│ wordpress 12:36:15.06 INFO  ==> ** Starting WordPress setup **                                                                                                                                                            
│ wordpress 12:36:15.11 WARN  ==> The Apache configuration file '/opt/bitnami/apache/conf/httpd.conf' is not writable. Configurations based on environment variables will not be applied.                                     │
│ wordpress 12:36:15.13 INFO  ==> Generating sample certificates                                                                                                                                                            
│ Certificate request self-signature ok                                                                                                                                                                                     
│ subject=CN = example.com                                                                                                                                                                                                  
│ realpath: /bitnami/apache/conf: No such file or directory                                                                                                                                                                 
│ wordpress 12:36:17.34 INFO  ==> Configuring the HTTP port                                                                                                                                                                 
│ wordpress 12:36:17.41 INFO  ==> Configuring the HTTPS port                                                                                                                                                                
│ wordpress 12:36:17.41 INFO  ==> Configuring Apache ServerTokens directive                                                                                                                                                
│ chown: changing ownership of '/opt/bitnami/php/var/run': Operation not permitted                                                                                                                                          ```

### Additional information

Exact Images from the describe
```
Image ID: docker.io/bitnami/wordpress@sha256:de085a75467e253af6c08dad311ed418731ae04eb03cf11a4641a4d843a1aa12
```

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
