### ISSUE TITLE
[bitnami/kafka] basic getting started with  not working for kafka chart in docker-desktop in windows

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [bitnami/charts#28533]
### Name and Version

bitnami/kafka:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to use kakfa char to deploy a kafka cluster. I intented to deploy a basic cluster with an external endpoint so it can be accessed from localhost. So I installed like
```
helm install my-release oci://REGISTRY_NAME/REPOSITORY_NAME/kafka
```
using `REGISTRY_NAME=registry-1.docker.io` and `REPOSITORY_NAME=bitnamicharts`.
then I use the Option A for Accessing Kafka brokers from outside the cluster
https://github.com/bitnami/charts/tree/main/bitnami/kafka#using-loadbalancer-services
updating the values.yaml fields:

```
externalAccess.enabled=true
externalAccess.service.broker.type=LoadBalancer
externalAccess.service.controller.type=LoadBalancer
externalAccess.service.broker.ports.external=9094
externalAccess.service.controller.containerPorts.external=9094
externalAccess.autoDiscovery.enabled=true
serviceAccount.create=true
rbac.create=true
```
Up to here, I can remark that some fields are not the same as the ones found on values.yaml for example
`externalAccess.service.controller.containerPorts`, so an update of the documentation not work.

Besides my initial steps, the system also forced me to change another part of the configuration by returning me the message:
```
kafka: controller-automountServiceAccountToken
    By specifying "externalAccess.enabled=true" and "externalAccess.autoDiscovery.enabled=true"
    an initContainer will be used to auto-detect the external IPs/ports by querying the
    K8s API. Please note this initContainer requires the service account token. Please set controller.automountServiceAccountToken=true
    and broker.automountServiceAccountToken=true.
```
So I did.

After that, I tried to connect as a publisher and I get 

```
{"level":"ERROR","timestamp":"2024-07-25T20:54:12.607Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Failed to connect: Port should be >= 0 and < 65536. Received type number (NaN).","retryCount":4,"retryTime":7966}
console.js:15
{"level":"ERROR","timestamp":"2024-07-25T20:54:20.587Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Failed to connect: Port should be >= 0 and < 65536. Received type number (NaN).","retryCount":5,"retryTime":17164}
console.js:15
KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Failed to connect: Port should be >= 0 and < 65536. Received type number (NaN).
    at c:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\network\connection.js:254:11
    at new Promise (<anonymous>)
    at Connection.connect (c:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\network\connection.js:167:12)
    at ConnectionPool.getConnection (c:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\network\connectionPool.js:56:24)
    at Broker.connect (c:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\broker\index.js:86:52)
    at async C:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\cluster\brokerPool.js:93:9
    at async C:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\cluster\index.js:107:14
    at async Cluster.connect (c:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\cluster\index.js:146:5)
    at async Object.connect (c:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\node_modules\kafkajs\src\producer\index.js:219:7)
    at async main (C:\Users\israel\Documents\codes\dev\cryptween\architecture\cliente\index.js:34:5) {name: 'KafkaJSNumberOfRetriesExceeded', retriable: false, helpUrl: undefined, retryCount: 5, retryTime: 17164, …}
```

Also over one night the controller restarted more than a hundred times.

### Are you using any custom parameters or values?

I am using Kubernetes from docker-desktop in Windows

### What is the expected behavior?

to create a stable cluster and be able to connect via localhost

### What do you see instead?

a lot of restarting of the pods and also I am not able to connect to the cluster

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by israel-gonzalezmedina** [comment]
Thanks for the response @carrodher . However it does is a problem  directly related to the Bitnami container image/Helm chart. As specified, it is a Bitnami container image/Helm chart documentation problem. My enviroment is clean. My Kubernetes on Docker Desktop was reset for every test. 
I miss to add that the basic installation 
`helm install my-release oci://REGISTRY_NAME/REPOSITORY_NAME/kafka`
indeed works fine. 
The problem was when try to expose Kafka brokers to outside the cluster and I followed  the dcumentation steps for it. So it is a Bitnami container image/Helm chart.

**Comment by javsalgar** [comment]
When you mention that it works fine with the basic installation, you mean that you are able to connect your application inside the cluster? Or did you perform a port-forward
