### ISSUE TITLE
[bitnami/argo-cd] applicationset cluster-role-binding missing namespace on subject

### ISSUE THREAD

**Issue by eastwood-c** [bitnami/charts#28539]
### Name and Version

bitnami/argo-cd 6.6.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```bash
helm repo update
helm upgrade --install argo-cd \
  bitnami/argo-cd \
  --set applicationSet.enabled=true \
  --set applicationSet.clusterAdminAccess=true
```

### What is the expected behavior?

successful deployment

### What do you see instead?
```
Error: UPGRADE FAILED: failed to create resource: ClusterRoleBinding.rbac.authorization.k8s.io "argo-cd-applicationset-controller" is invalid: subjects[0].namespace: Required value
```
### Additional information

[templates/applicationset/clusterrolebinding.yaml#L16](https://github.com/bitnami/charts/blob/60cabb07dac432a58d79a5ffcb756079a32c70fa/bitnami/argo-cd/templates/applicationset/clusterrolebinding.yaml#L16) namespace declaration is missing from the subject fragment.

[templates/application-controller/clusterrolebinding.yaml#L22](https://github.com/bitnami/charts/blob/60cabb07dac432a58d79a5ffcb756079a32c70fa/bitnami/argo-cd/templates/application-controller/clusterrolebinding.yaml#L22) showing the correct usage in the application-controller template.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
