### ISSUE TITLE
TLS/SSL error: SSL is required

### ISSUE THREAD

**Issue by claudiobat** [bitnami/charts#28554]
### Name and Version

bitnami/wordpress 6.6.1-debian-12-r1 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi,
I have a Helm chart that uses bitnami/wordpress.
After migrating from bitnami/wordpress 6.6.1-debian-12-r1 to 6.6.0-debian-12-r0 I have this error:

```
[38;5;6mwordpress [38;5;5m09:42:26.06 [0m[38;5;5mDEBUG[0m ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
[38;5;6mwordpress [38;5;5m09:42:31.18 [0m[38;5;5mDEBUG[0m ==> Executing SQL command:
```

The Mysql server is not under my control so in these days I can't add SLL support.
So, is there a way a method with this chart to avoid using SSL for the database queries?

Thank you

### What is the expected behavior?

In the previous versions the queries didn't use SSL.

### What do you see instead?

The SELECT 1 check fails because the Mysql Server doesn't support SSL.

**Comment by claudiobat** [comment]
Excuse me, the new helm chart is bitnami/wordpress 23.0.11, the previos bitnami/wordpress 23.0.4

**Comment by p4block** [comment]
The actual underlying cause is that the 6.6.1 wordpress container introduced a newer mysql client that doesn't like the x509 v1 certificate in mysql/mariadb https://jira.mariadb.org/browse/MDEV-33592

I downgraded the container to 6.6.0  (23.0.9 chart) in the meantile while Bitnami figures it out. An update to mysql/mariadb is needed, I think, and the client in Wordpress is doing it right.

**Comment by juan131** [comment]
This is currently discussed at https://github.com/bitnami/containers/issues/70392, let's continue the conversation there.

**Comment by gongomgra** [comment]
@claudiobat @p4block  we have just released a new revision of our WordPress image including the fix for this issue. 

```
docker pull bitnami/wordpress:6.6.1-debian-12-r3
```

You can check the changes included in this new image at https://github.com/bitnami/containers/commit/0a7377b834dcd2c3fd0cb562c37966a33c6e7708

**Comment by claudiobat** [comment]
The version 6.6.1-debian-12-r3 solves my problem too, Thank you.

Claudio B.
