### ISSUE TITLE
ability to increase the size of file uploads

### ISSUE THREAD

**Issue by samgabrail** [bitnami/charts#2855]
**Which chart**:
moodle-7.2.14

**Is your feature request related to a problem? Please describe.**
I'd like to have the ability to increase the size of file uploads. Right now the default is at 40 MB.

**Describe the solution you'd like**
This is done by following the instructions in the link below
https://docs.bitnami.com/aws/apps/moodle/administration/increase-upload-limit-php/

However, the issue is that the /opt/bitnami/php/etc/php.ini file is not stored on a persistent volume. So if you make the change in the container, it doesn't persist.

I'd like this file to be added to the persistent volume and an option added to change the value of the upload size in the chart's values file. 

post_max_size = 40M
upload_max_filesize = 40M

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input. I think it makes sense to allow our containers to modify several critical php parameters or even allowing you to mount your custom php configuration. I will open a task so we can evaluate adding these features. We cannot guarantee an ETA, but I will update this ticket when we have more information.

**Comment by javsalgar** [comment]
Hi,

In the chart, you can set the following environment variables:

```
extraEnvVars:
  - name: PHP_UPLOAD_MAX_FILESIZE
    value: 40M
  - name: PHP_POST_MAX_SIZE
    value: 40M
```

Could you check if it works for you?

**Comment by karl18** [comment]
Hi @javsalgar 

I'd the same issue, tried the proposed solution and worked fine! 
Thanks a lot !

**Comment by javsalgar** [comment]
Thank for letting us know!

**Comment by hamzakhalem** [comment]
any solution guys ?
