### ISSUE TITLE
[bitnami/harbor] Trivy scanner is unhealthy

### ISSUE THREAD

**Issue by HamzaZoubair** [bitnami/charts#28558]
### Name and Version

bitnami/harbor 22.0.8

### What architecture are you using?

None

### What steps will reproduce the bug?

When we upgraded the chart version from 21.1.5 to 22.0.8 the trivy scanner was unhealthy and we could not scan artifacts. 
On Trivy pod logs we don't have any information. 
Can you please provide support? 

### What is the expected behavior?

Trivy scanner healthy

### What do you see instead?

Trivy scanner status in unhealthy

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
