### ISSUE TITLE
[Bitnami/Jenkins] Fails copying scripts in ca-central-1 (works in us-east-1)

### ISSUE THREAD

**Issue by pobtastic** [bitnami/charts#28562]
### Name and Version

bitnami/jenkins 13.4.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Quicklaunch in AWS for Kubernetes, in ca-central-1
2. Stack mostly comes up, but fails with a connection issue (timeout) copying scripts over into the generated bucket

### Are you using any custom parameters or values?

None

### What is the expected behavior?

Scripts would be copied into bucket and CloudFormation should complete successfully.

### What do you see instead?

Via Cloudformation event stream - Rollback on Custom::CopyZips, CloudTrail suggests timeout - expectation, given that deploying on us-east-1 worked, issues with cross-region code?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by pobtastic** [comment]
No no, maybe I can be clearer - I'm using [Bitnami Helm Chart for Jenkins](https://aws.amazon.com/marketplace/pp/prodview-nwz3ql5idxcva) and then I'm using "Launch on a new EKS cluster with QuickLaunch" so I'm making zero changes to it - other than choosing a t3a.small instance.  Everything else is on defaults.

When you go to launch, it automatically sends you to, e.g.: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/quickcreate?templateURL=https://s3.amazonaws.com/awsmp-fulfillment-cf-templates-prod/4cfaa163-b863-4bda-aa8a-bc4ff4f26cc8/dc6e37d4-2c67-4261-b1ea-9ba4f4c0a37d/aa8f0e02-bac3-4d46-9c44-8a5e02283fc3.template

But obviously at this point, you can change it to ... https://ca-central-1.console.aws.amazon.com/cloudformation/home?region=ca-central-1#/stacks/quickcreate...etc etc...

There is no specific niche thing I'm doing for this - I'm just changing the region and the Custom::CopyZips part then doesn't work cross-region.
