### ISSUE TITLE
[valkey] master.updateStrategy documentation missing

### ISSUE THREAD

**Issue by dchandekstark** [bitnami/charts#28560]
### Name and Version

bitnami/valkey 0.3.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When setting `master.kind` to "Deployment", the key `master.updateStrategy` is used by the template `master/application.yaml` to set `spec.strategy`.  

This information is not reflected in the documentation.

### What do you see instead?

Missing documentation

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
