### ISSUE TITLE
[bitnami/kafka] /scripts/kafka-init.sh: Permission denied error

### ISSUE THREAD

**Issue by sudhim076** [bitnami/charts#28579]
### Name and Version

bitnami/kafka:3.7.1-debian-12-r1

### What architecture are you using?

None

### What steps will reproduce the bug?

Issue currently exists,. We are getting the below error when running the kafka container in Kubernetes cluster.
**/bin/bash: line 1: /scripts/kafka-init.sh: Permission denied error in kubernetes init container**

### What is the expected behavior?

container should run without any issue.

### What do you see instead?

kafka-init container is failing to start with error message:

**/bin/bash: line 1: /scripts/kafka-init.sh: Permission denied error in kubernetes init container**

**Comment by jotamartos** [comment]
Hi, 

I can see that you are using custom configuration when deploying the chart. For example, you are using a custom storageClass that may be introducing the issue 

```
  persistence:
    enabled: true
    storageClass: manged-premium-retain-csi
```

Could you please try deploying the chart with the default parameters to confirm that it works as expected? You will later need to debug the issue by introducing the changes in the values.txt file you shared.
