### ISSUE TITLE
[binamit/keycloak] Helm chart using deprecated hostname v1 env variable

### ISSUE THREAD

**Issue by chrisdrobison** [bitnami/charts#28586]
### Name and Version

bitnami/keycloak 22.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy helm chart

### What is the expected behavior?

Helm chart updated to use the new hostname v2 parameters.

### What do you see instead?

Keycloak 25 has changed the way hostnames work. They've released documentation on hostnames v2 and have deprecated hostname v1 parameters. This helm chart uses hostname v1 parameters as signified by the warning on startup:

```
2024-07-30 02:31:40,081 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used run time options are UNAVAILABLE and will be ignored during build time:
 	- hostname-url: Available only when hostname:v1 feature is enabled.
```

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by singhbaljit** [comment]
I think we need to update the container scripts first, see https://github.com/bitnami/containers/issues/70461.
