### ISSUE TITLE
[bitnami/gitea] OAuth2 Provider Configuration

### ISSUE THREAD

**Issue by ikamii** [bitnami/charts#28584]
### Name and Version

bitnami/gitea

### What is the problem this feature will solve?

I am not sure if it's already possible to configure an OAuth2 provider via values.yaml while deploying this chart, like in gitea/gitea chart. If there is a feature for this, please explain me. Thank you in advance!

example:

```yaml
oauth:
    []
    # - name: 'OAuth 1'
    #   provider:
    #   key:
    #   secret:
    #   existingSecret:
    #   autoDiscoverUrl:
    #   useCustomUrls:
    #   customAuthUrl:
    #   customTokenUrl:
    #   customProfileUrl:
    #   customEmailUrl:
```

### What is the feature you are proposing to solve the problem?

It enables to configure OAuth2 authentication Provider while deploying Gitea helm chart.

**Comment by ikamii** [comment]
Hi sorry for late reply,

Firstly thank you for your response.

When I copy &  paste what you have provided in `values.yaml`, it doesn't work but it was expected. I might have to test a bit more I think.

If it won't work, I will try to find a solution and implement something in next days.

**Comment by kosumic** [comment]
> Hi sorry for late reply,
> 
> Firstly thank you for your response.
> 
> When I copy & paste what you have provided in `values.yaml`, it doesn't work but it was expected. I might have to test a bit more I think.
> 
> If it won't work, I will try to find a solution and implement something in next days.

Did you find a solution? Did you fork it?

**Comment by ikamii** [comment]
Hi there,

I have found a solution but not with the init contaniers. 

After deploying the gitea, ai use the gitea cli in the pod to configure the OAuth2. 

I am unfortunately away from my computer but I can send the cli command here tomorrow.

**Comment by kosumic** [comment]
> Hi there,
> 
> I have found a solution but not with the init contaniers. 
> 
> After deploying the gitea, ai use a gitea cli in the pod to configure the OAuth2. 
> 
> I am unfortunately away from my computer but I can send the cli command here tomorrow. 

Maybe you should try the official gitea chart instead.

**Comment by ikamii** [comment]
While I was using the gitea, official gitea chart had some other problems which bitnami one did not have. 

I might check it out in the future.
