### ISSUE TITLE
Guidance on setting configuration values for the postgresql subchart

### ISSUE THREAD

**Issue by BenManifold** [bitnami/charts#28594]
### Name and Version

bitnami/postgresql 10.9.4

### What is the problem this feature will solve?

Very difficult to override only certain configuration options, such as max_wal_size, without blowing away all other necessary configurations.

If the chart template isn't going to be written in a way to support only overriding what we intend to override, then we need the default values to be present in values.yaml where we can actually see them.

### What is the feature you are proposing to solve the problem?

The values file should contain the effective configuration, including such items as max_wal_size and everything it shares a map with.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
