### ISSUE TITLE
bitnami keyclaok facing issue after login Cookie not found. Please make sure cookies are enabled in your browser. 

### ISSUE THREAD

**Issue by Meet-S0ni** [bitnami/charts#28593]
### Name and Version

bitnami/keycloak:24.0.5-debian-12-r8

### What architecture are you using?

amd64

### What steps will reproduce the bug?

create Kubernetes deployment and service yaml using the above image 
try to access the service via loadbalancer IP 

it is working with port-forward but when I access via loadbalancer it shows this, 
this is not a browser issue I have tried in multiple browsers and multiple machines 

![image](https://github.com/user-attachments/assets/802c8c15-2e2b-4c6b-be7c-47ad76558908)

### Are you using any custom parameters or values?

I have just passed parameters for Postgres connection and user and password 

### What do you see instead?

not sure

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
