### ISSUE TITLE
[bitnami/kibana] kibanaPassword random generation missing

### ISSUE THREAD

**Issue by davidecelano** [bitnami/charts#28615]
### Name and Version

bitnami/kibana 8.14.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The documentation states

> elasticsearch.security.auth.kibanaPassword has to provide the password for the kibana_system user, otherwise random password will be generated.

but if a kibanaPassword isn't provided then the helm install fails
`Error: execution error at (kibana/templates/secret.yaml:19:22): A Kibana password is required!`

The template doesn't seem to provide a way to generate a random password for kibana_system

### What is the expected behavior?

A random password should be created if the
elasticsearch.security.auth.kibanaPassword
isn't provided

### What do you see instead?

`Error: execution error at (kibana/templates/secret.yaml:19:22): A Kibana password is required!`

**Comment by javsalgar** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
