### ISSUE TITLE
[bitnami/kafka] /scripts/kafka-init.sh fails on IMDSv2-enforced cluster

### ISSUE THREAD

**Issue by DieterDP-ng** [bitnami/charts#28617]
### Name and Version

bitnami/kafka 29.2.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In an AWS environment where [IMDSv1 has been disabled](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html#iam-condition-keys-and-imds), deploy the kafka chart with `brokerRackAssignment: "aws-az"` present in the values.

### Are you using any custom parameters or values?

brokerRackAssignment: "aws-az"

### What do you see instead?

```
/scripts/kafka-init.sh: line 50: 3: missing value
```

### Additional information

The issue is caused by this snippet from `kafka-init.sh` (lines 49 and 50):

```
export BROKER_RACK=$(curl "http://169.254.169.254/latest/meta-data/placement/availability-zone-id")
kafka_conf_set "$KAFKA_CONFIG_FILE" "broker.rack" "$BROKER_RACK"
```

In an environment where IMDSv2 is enforced, the curl request will get a `401 Unauthorized` error, resulting in a missing `$BROKER_RACK`.

As described on [this page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html#instance-metadata-options-order-of-precedence), ISMDv2 requests will work on environments with or without enforcement of IMDSv2. So the solution is to [perform a ISMDv2 request](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) instead:

```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone-id
```

**Comment by javsalgar** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by DieterDP-ng** [comment]
For future readers: this was fixed by https://github.com/bitnami/charts/pull/27921
