### ISSUE TITLE
[bitnami/mysql] MYSQL: Service Binding Secret Does Not Include database

### ISSUE THREAD

**Issue by ryanjbaxter** [bitnami/charts#28627]
### Name and Version

bitname/mysql

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Using Tilt I am running 
```
load('ext://helm_resource', 'helm_resource', 'helm_repo')
helm_repo('bitnami', 'https://charts.bitnami.com/bitnami')
helm_resource('mysql', 'bitnami/mysql', resource_deps=['bitnami'], flags=['--set=serviceBindings.enabled=true', '--set=auth.database=frustration_free'])
```

### Are you using any custom parameters or values?

--set=serviceBindings.enabled=true --set=auth.database=frustration_free

### What is the expected behavior?

The secret that gets created contains a `database` attribute

### What do you see instead?

No `database` attribute is present

### Additional information

The logic to include the `database` attribute is only present if a custom user is provided

https://github.com/bitnami/charts/blob/18810c2e600761d58950c97e509191b7630a19bc/bitnami/mysql/templates/secrets.yaml#L28-L73

**Comment by ryanjbaxter** [comment]
Yes the database does get created even when not specifying a non-root user also be created

**Comment by javsalgar** [comment]
If that's the case, then it would make sense to add the database value if set to the other service binding. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. However, if you want to speed up the process, you can submit a PR and the team will take a look

**Comment by javsalgar** [comment]
Thank you so much!

**Comment by ryanjbaxter** [comment]
Thanks!  When will this be available in the public bitnami repo?

**Comment by carrodher** [comment]
The new version (11.1.15) is already published in the OCI registry, see https://hub.docker.com/r/bitnamicharts/mysql/tags

**Comment by ryanjbaxter** [comment]
Thanks!
