### ISSUE TITLE
[bitnami/matomo] config/config.ini.php not writeable unable to install plugins

### ISSUE THREAD

**Issue by fabianboerner** [bitnami/charts#28628]
### Name and Version

bitnami/matomo 8.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

default setup for matomo helm chart.

1. Go to market place
2. install plugin
3. activate plugin
4. message config/config.ini.php not writeable changes are not stored.

### Are you using any custom parameters or values?

i have tried:

  customPostInitScripts:
    custom-post-init.sh: |
      #!/bin/bash
      chmod 777 /bitnami/matomo/config/config.ini.php

All other settings are for password and smtp.

### What is the expected behavior?

Plugin is installed.

### What do you see instead?

![image](https://github.com/user-attachments/assets/f5c485a0-0156-477f-8d58-873f2aeec579)

**Comment by fabianboerner** [comment]
When i deploy everything it works the moment i changed it the first time and it seems something redeploys it stops working again.

**Comment by dgomezleon** [comment]
Hi @fabianboerner ,

I couldn't reproduce the issue on GKE with the default values. I installed and activate `Queued tracking`.

![Screenshot 2024-08-06 at 13 30 42](https://github.com/user-attachments/assets/4953e4f0-6a9b-407d-ac54-cba1d41acb96)

Did you try a different plugin?

You could also try changing the `containerSecurityContext`:

```
containerSecurityContext:
  readOnlyRootFilesystem: false
  runAsGroup: 0
```

I hope it helps

**Comment by fabianboerner** [comment]
It seems it was the storage class from digital ocean when first installed it was readable. 

After i deployed changes the error occured and the only thing that was not changed was the pvc on the digital ocean storage class. 

I implemented an nfs controller with a new storage class and that has solved the problem.

https://www.digitalocean.com/community/tutorials/how-to-set-up-readwritemany-rwx-persistent-volumes-with-nfs-on-digitalocean-kubernetes-de

**Comment by dgomezleon** [comment]
Thanks for sharing your solution here.
