### ISSUE TITLE
[bitnami/thanos] When using Thanos Store for hash sharding, it supports adding custom relabel configurations.

### ISSUE THREAD

**Issue by iyacontrol** [bitnami/charts#28633]
### Name and Version

bitnami/thanos master

### What is the problem this feature will solve?

template:  https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/storegateway/statefulset-sharded.yaml

For thanos storegateway, if i enable hashPartitioning, this template will use --selector.relabel-config. This means that if I enable hash sharding, I will not be able to use selector.relabel-config to implement additional filtering functions, such as filtering by tenant or region. Therefore, it is necessary to support appending user-defined relabel settings while sharding.

```
    - |
      --selector.relabel-config=
        - action: hashmod
          source_labels: ["__block_id"]
          target_label: shard
          modulus: 10
        - action: keep
          source_labels: ["shard"]
          regex: 6
```

for example:

```
    - |
      --selector.relabel-config=
        - action: hashmod
          source_labels: ["__block_id"]
          target_label: shard
          modulus: 10
        - action: keep
          source_labels: ["shard"]
          regex: 6
        - action: keep
          source_labels: ["tenant"]
          regex: abc
```

### What is the feature you are proposing to solve the problem?

implement additional filtering functions, such as filtering by tenant or region.

**Comment by javsalgar** [comment]
Hi! Thank you so much for the feature request. I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will check it.
