### ISSUE TITLE
.gitmodules references https://github.com/bitnami/charts-docs which does not appear to exist

### ISSUE THREAD

**Issue by mwoodpatrick** [bitnami/charts#28649]
### Name and Version

none

### What architecture are you using?

amd64

### What steps will reproduce the bug?

git submodule update  --recursive

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Pulls any existing submodules

### What do you see instead?
```
remote: Repository not found.
fatal: repository 'https://github.com/bitnami/charts-docs/' not found
fatal: clone of 'https://github.com/bitnami/charts-docs' into submodule path '/mnt/wsl/projects/git/westie-dev-pnpm/kube/bitnami/charts/docs' failed
Failed to clone 'docs' a second time, aborting
fatal: Failed to recurse into submodule path 'kube/bitnami/charts'
```

**Comment by carrodher** [comment]
That submodule was removed a long time ago, are you able to reproduce the issue by using the latest commit in the main branch?
```console
$ git submodule update --recursive
$ echo $?
0
```

**Comment by mwoodpatrick** [comment]
I resolved the issue at my end (out of date submodule), many thanks for the response
