### ISSUE TITLE
[bitnami/external-dns] External dns rfc2136 zone cannot supply more than 2 zones.

### ISSUE THREAD

**Issue by Jeremy-Boyle** [bitnami/charts#28645]
### Name and Version

bitnami/external-dns 8.3.3

### What is the problem this feature will solve?

Currently the helm template only allows for a single zone, however external-dns can support more than one zone by adding extra argument variables similar to how the domain filter works. 

Currently the only way to add another zone is to add it with 
```yaml
extraArgs:
  rfc2136-zone: extra-zone.com
```

However since this is a map and not a array it would only be able to support one additional zone.

This will support more than one zone, however, due to the limitations there might be additional providers that allow multiple arguments that cannot be set due to how extraArgs works. Need feedback if this should be changed to how most other bitnami charts do it via. My recommendation is that this should be changed from a map to a array to be inline with other charts to reduce a dependency when arguments are added that support multiple flags. 

```yaml
extraArgs: []
```

This fix will change the value 

```yaml
rfc2136:
  zone: ""
```

to

```yaml
rfc2136:
  zones: []
```

### What is the feature you are proposing to solve the problem?

This will change the default values file to support more than two zones.

And discuss if changing to `extraArgs: []` makes sense

### What alternatives have you considered?

The following can work for another zone, another option is manually editing the template and maintaining yourself.
```yaml
extraArgs:
  rfc2136-zone: extra-zone.com
```

**Comment by javsalgar** [comment]
Hi,

I agree that using an array would make more sense to allow this kind of scenarios. I will forward it to the team but I cannot guarantee an ETA. Would you like to submit a PR adding support for extraArgs as an array? (without breaking backwards compatibility)

**Comment by dieselr** [comment]
Hi,

With the addition of support for multiple zones in the rfc2136 provider, I believe it's important to also provide support for multiple TSIG keys. Currently, only one key can be assigned, which may be problematic if separate zones require different security keys.

**Comment by javsalgar** [comment]
Thank you so much for the PR!

**Comment by TomyLobo** [comment]
I also have this issue.
