### ISSUE TITLE
Pre-installed plugins and themes via YAML ? - Wordpress

### ISSUE THREAD

**Issue by manitycloud** [bitnami/charts#2865]
Dears,

I'm new to the Kubernetes mechanism, so please don't judge me :)
I try to implement what I need with this technology, this is for the moment a learning approach rather than a production approach.
In your YAML you mention that we can specify extra plugins and themes for wordpress.
However, I don't really understand how this command is actually working:

```
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'copy themes and plugins from git and push to /bitnami/wordpress/wp-content. Should work with extraVolumeMounts and extraVolumes']
##
```
Could you please give me a concrete example by adding for example wordpress-seo plugin, woocommerce plugin and storefront theme via this command?

(fyi:
https://downloads.wordpress.org/plugin/woocommerce.4.2.0.zip
https://downloads.wordpress.org/plugin/wordpress-seo.14.3.zip
https://downloads.wordpress.org/theme/storefront.2.5.7.zip)

Thank you a lot

**Comment by rafariossaa** [comment]
Hi,  
  Could you take a look to this other approach ?
  https://github.com/bitnami/charts/issues/2796

**Comment by manitycloud** [comment]
Thank you for your reply.
So if I'm right, I simply should do this:
```
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'wp plugin install woocommerce --activate --allow-root && wp plugin install wordpress-seo --activate --allow-root && wp theme install storefront --activate --allow-root']
##
```
Am I correct?

**Comment by manitycloud** [comment]
Or maybe is there an easier way to do that simply with the helm command via a parameter?

**Comment by sssarali** [comment]
Hello, 

I am also having trouble using the `initContainer`. I am trying to pull a custom image from harbor. And I have this for the `initContainer`. I'm not using any commands yet as to test whether the initContainer will even work:
```
 initContainers:
  - name: <harbor-image>
  - image: <image> 
  - imagePullPolicy: IfNotPresent
```
However, the initContainer keeps failing. Any ideas why? Thanks!

**Comment by rafariossaa** [comment]
> Thank you for your reply.
> So if I'm right, I simply should do this:
> 
> ```
> ## initContainers:
> ##  - name: your-image-name
> ##    image: your-image
> ##    imagePullPolicy: Always
> ##    command: ['sh', '-c', 'wp plugin install woocommerce --activate --allow-root && wp plugin install wordpress-seo --activate --allow-root && wp theme install storefront --activate --allow-root']
> ##
> ```
> 
> Am I correct?

No, I am sorry.
In that example he is not using the initcontainer, but a shell script that run the plugins installation commands. This script should be located on /docker-entrypoint-init.d.

**Comment by rafariossaa** [comment]
> Hello,
> 
> I am also having trouble using the `initContainer`. I am trying to pull a custom image from harbor. And I have this for the `initContainer`. I'm not using any commands yet as to test whether the initContainer will even work:
> 
> ```
>  initContainers:
>   - name: <harbor-image>
>      image: <image> 
>      imagePullPolicy: IfNotPresent
>      pullSecrets: <harbor-pass>
>      volumeMounts:
>          - mountPath: /bitnami
>            name: tracker-data
> ```
> 
> However, the initContainer keeps failing. Any ideas why? Thanks!

Hi,
  You issue seem to be different, do you mind to open a new issue so we can make a better tracking of it ?.

Thanks forehand.
