### ISSUE TITLE
[bitnami/cassandra] Make TLS secret configuration more versatile to allow interaction with cert-manager/trust-manager

### ISSUE THREAD

**Issue by tbalzer** [bitnami/charts#28687]
### Name and Version

bitnami/cassandra 11.3.12

### What is the problem this feature will solve?

We are trying to use the `bitnami/cassandra` chart to deploy a cassandra cluster with TLS enabled, using certificates/keystores created via [cert-manager](https://cert-manager.io/) and truststores created by trust-manager (part of the same project), which leads to issues due to the differing formats of the secrets created by cert-manager/trust-manager vs the secret expected by the chart.

The main differences are:

* chart expects a single secret for truststore and keystore, which doesn't allow usage of trust-manager which creates a separate secret for the truststore
* chart expects the keys `keystore` and `truststore`, but cert-manager and trust-manager create the keys `keystore.jks`/`keystore.p12` and `truststore.jks`/`truststore.p12` respectively (not configurable on either side)
* chart expects the keys `keystore-password` and `truststore-password` in the same secret, with non-configurable keys (this is configurable on cert-manager and trust-manager side though, so not a deal-breaker but still not flexible)

### What is the feature you are proposing to solve the problem?

Introduce the following values:

* `tls.secretKeys.truststorePassword` with default `truststore-password`
* `tls.secretKeys.keystorePassword` with default `keystore-password`
* `tls.secretKeys.keystore` with default `keystore`
* `tls.secretKeys.truststore` with default `truststore`
* `tls.existingTrustSecret` with default of empty string (signaling "none", meaning to use `tls.existingSecret` for both)

Then instead of hardcoded values for the secret keys, the respective values could be used while ensuring backwards compatibility. Special care has to be taken in case of `keystore` and `truststore` which are also used as filenames in init-containers and environment variables as the tls secret is mounted to `/certs` which could be replaced with a projected volume built from just the expected/required files from one or multiple secrets as configured.

### What alternatives have you considered?

Another alternative would be (at least for some users not requiring trust-manager) to request changes just in cert-manager to make those keys configurable. I personally think though that this is the more appropriate place.

Another alternative would be to build some kind of workaround that generates the expected secrets from the existing secrets generated by cert-manager before deploying the helm chart. This is however quite inconvenient.

**Comment by tbalzer** [comment]
@javsalgar PR is attached

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
