### ISSUE TITLE
[Postgres-ha] mountPath & extendedConf conflict and prevent pod start

### ISSUE THREAD

**Issue by elordahl** [bitnami/charts#2869]
**Which chart:**
[bitnami/postgresql-ha]

**Is your feature request related to a problem?** Yes
When using the `persistence.enabled` AND `postgresql.extendedConf` values, the ConfigMap is mounted in `/bitnami/postgresql/conf/conf.d/` which is inside the default mountPoint `/bitnami/postgresql/`.  While troubleshooting, I noticed some inconsistencies with mount points and wanted to check on the following before submitting a PR:

https://github.com/bitnami/charts/blob/d75d9893cf02241b0b4e5b43fb986e87551c0f9b/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L221-L224

Is there a scenario where this should NOT be mounted?  I think it should be mounted, even with `persistence.enabled=false`, since the volume still exists as an `emptyDir`.

1.  PVC: ✅ 
1.  PVC with existing claim: ✅ 
1.  No persistence, emptyDir: ✅

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Yes, you are right. I believe that the volumeMount should be there always, as it is using an emptyDir when persistence is set to false. Feel free to submit a PR :)

**Comment by javsalgar** [comment]
Not stale. Creating a PR
