### ISSUE TITLE
[bitnami/elasticsearch] Include compatibility matrix between helm charts and Elastic version

### ISSUE THREAD

**Issue by tabiStein** [bitnami/charts#28701]
### Name and Version

19.1.1

### What is the problem this feature will solve?

This is as much a question as it is a request. I want to upgrade my elasticsearch chart version to a version that uses commons 2.x.x, without breaking integration with Elastic version 7.10. 

### What is the feature you are proposing to solve the problem?

If you already have this documented somewhere, I am having trouble finding it. Could you share it with me and consider linking it in your Readme?
If this doesn't exist, could you please create it?

### What alternatives have you considered?

Upgrading to version 19.21.2 and praying integration with Elastic 7.10 doesn't break.

**Comment by javsalgar** [comment]
Hi,

Just to understand, do you want to know which exact elasticsearch versions each chart provides? Would the appVersion section in the Chart.yaml work? I believe that helm repo search can provide this information too.

**Comment by tabiStein** [comment]
> Hi,
> 
> Just to understand, do you want to know which exact elasticsearch versions each chart provides? Would the appVersion section in the Chart.yaml work? I believe that helm repo search can provide this information too.

Hi, not quite. We are currently using the Helm chart version 19.1.1 with 7.10 and it works, despite 19.1.1's appVersion being higher (8.3.2-debian-11-r1). I would like to upgrade the Helm chart to a higher version while still being compatible with 7.10, but I don't see that information anywhere.

**Comment by javsalgar** [comment]
I'm afraid that, while the two branches essentially share the same container logic, we are only performing chart verification and validation with the version shown in appVersion. In terms of resources, it would be difficult (in terms of automation) and expensive (in terms of testing resources), to perform all the chart validations in all supported branches in our whole catalog.

For Elasticsearch 7.x.x, we are currently performing container-level validation.
