### ISSUE TITLE
[Bitnami/RabbitMQ] Credentials are not working

### ISSUE THREAD

**Issue by pmorelli92** [bitnami/charts#2870]
**Which chart**:
RabbitMQ - Version 7.0.0.

**Describe the bug**

Pod wont get ready since the liveness check is failing.

```
2020-06-18 07:54:41.989 [warning] <0.861.0> HTTP access denied: user 'someUsernameIsHere' - invalid credentials
```

**To Reproduce**

```
helm repo add bitnami https://charts.bitnami.com/bitnami

helm install rabbitmq \
  --set auth.username=someUsernameIsHere,auth.password=secretpassword,auth.erlangCookie=secretcookie \
    bitnami/rabbitmq
```

**Expected behavior**

Pod gets ready.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I managed to make it work only using `user` or `admin` as usernames. Anything else I try fails.

**Comment by juan131** [comment]
Thanks so much for reporting this issue! This regression was introduced by me when I did a major refactoring of the chart.

I just created a PR to address it.

**Comment by juan131** [comment]
Hi @pmorelli92 

We just released a new version of the chart (7.0.2) addressing this issue, could you give it a try?

**Comment by lyptt** [comment]
@juan131 I get the same issue on the latest version, and the version you've mentioned. I can see that the environment variables are specified as `RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD` on the pod. Which version was working before your changes?

**Comment by juan131** [comment]
Hi @lyptt 

Could you please share what steps did you follow so I can reproduce the issue on my side ?
Did you install RabbitMQ on a clean environment? I mean, without existing PVCs from previous deployments.

**Comment by pmorelli92** [comment]
Hi @juan131 sorry for the delay, for me it worked using 7.0.2 and also 7.1.2. Thanks for the fix

**Comment by juan131** [comment]
I'm glad to hear that @pmorelli92 
Thank you for reporting it!!!

**Comment by pavars** [comment]
Issue is still present in helm chart 7.6.7, doesn't matter how it's installed (as a dependency or standalone)
```helm install rp-rabbitmq --set auth.username=rabbitmq,auth.password=rabbitmq,rabbitmq.rabbitmq.username=rabbitmq,rabbitmq.rabbitmq.password=rabbitmq,replicaCount=1 bitnami/rabbitmq```

Password works that is set up using rabbitmq.rabbitmq.password but username is still user even though it shows rabbitmq in the kubectl info

**Comment by juan131** [comment]
Hi @pavars 

I installed the chart using the command you shared:

```console
$ helm install rp-rabbitmq --set auth.username=rabbitmq,auth.password=rabbitmq bitnami/rabbitmq
NAME: rp-rabbitmq
LAST DEPLOYED: Mon Sep 28 10:51:47 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Credentials:

    echo "Username      : rabbitmq"
    echo "Password      : $(kubectl get secret --namespace default rp-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
    echo "ErLang Cookie : $(kubectl get secret --namespace default rp-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"

RabbitMQ can be accessed within the cluster on port  at rp-rabbitmq.default.svc.

To access for outside the cluster, perform the following steps:

To Access the RabbitMQ AMQP port:

    echo "URL : amqp://127.0.0.1:5672/"
    kubectl port-forward --namespace default svc/rp-rabbitmq 5672:5672

To Access the RabbitMQ Management interface:

    echo "URL : http://127.0.0.1:15672/"
    kubectl port-forward --namespace default svc/rp-rabbitmq 15672:15672
```

Then, I accessed the RabbitMQ Management interface using the `kubectl port-forward` command suggested in the NOTES.txt, and I used the credentials `username: rabbitmq`, `password: rabbitmq`, and I could login without issues:

![Screenshot 2020-09-28 at 10 53 57](https://user-images.githubusercontent.com/6740773/94411568-0450b200-0179-11eb-8a81-b4aa883c3cbf.png)
![Screenshot 2020-09-28 at 10 54 53](https://user-images.githubusercontent.com/6740773/94411603-0dda1a00-0179-11eb-94a6-60644002099c.png)



> Note: You don't need to use these parameters: `rabbitmq.rabbitmq.password` and `rabbitmq.rabbitmq.password`. They are deprecated. It should be enough using `auth.username` and `auth.password` parameters.

**Comment by TabakM4n** [comment]
Hello @juan131 

your example is working as expected but when I run install it with namespace it stops working.

`helm upgrade rabbitmq --install --namespace mynamespace --set auth.username=rabbitmq,auth.password=rabbitmq bitnami/rabbitmq`

**Comment by miguelaeh** [comment]
Hi @TabakM4n ,
Which is the error you are getting when installing into a namespace?

**Comment by TabakM4n** [comment]
@miguelaeh I just can't login and the UI shows me `Login failed`

**Comment by miguelaeh** [comment]
Did you deploy it previously? Could you try to deploy it with a different release name or in case you are in a development environment deleting the PVCs previously?

**Comment by TabakM4n** [comment]
Thanks! This was the issue - I deleted the PVCs and it started working with namespace.

**Comment by miguelaeh** [comment]
You're welcome!

**Comment by evgmoskalenko** [comment]
Hello, How I can fixed it, if I login after updating my chart with existing PVCs?

**Comment by asanglard** [comment]
Hi,

I have the same with this chart version : rabbitmq-8.9.2

After deleting the PVC as suggested above, the issue was fixed. Would it be possible to avoid this manual PVC deletion ?

The experience is quite painful to deploy rabbitmq with this defect. (find that it is known issue, delete manually the PVC, etc...)

**Comment by juan131** [comment]
Hi @asanglard 

As it's explained in the [troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues), there others alternatives such as doing helm rollbacks when you face this issue.

Please also note that we included in recent version of the chart some validations to avoid this error to happen during upgrades. See the command sequence below:

```console
$ helm search repo bitnami/rabbitmq
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/rabbitmq	8.9.2        	3.8.11     	Open source message broker software that implem...
$ helm install rabbitmq bitnami/rabbitmq
...
(installation notes are displayed)
....
$ helm upgrade rabbitmq bitnami/rabbitmq
Error: UPGRADE FAILED: template: rabbitmq/templates/NOTES.txt:138:4: executing "rabbitmq/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredRabbitmqPasswordErrors) "context" $)>: error calling include: template: rabbitmq/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.password' must not be empty, please add '--set auth.password=$RABBITMQ_PASSWORD' to the command. To get the current value:

        export RABBITMQ_PASSWORD=$(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)

    'auth.erlangCookie' must not be empty, please add '--set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE' to the command. To get the current value:

        export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
```

As you can see, the upgrade process fails providing me the instructions to properly upgrade the chart without facing issues with passwords.

**Comment by Korrozia** [comment]
> Hello @juan131
> 
> your example is working as expected but when I run install it with namespace it stops working.
> 
> `helm upgrade rabbitmq --install --namespace mynamespace --set auth.username=rabbitmq,auth.password=rabbitmq bitnami/rabbitmq`

The same situation, when installed in custom namespace cannot login, when installed to default namespace can login.

**Comment by javsalgar** [comment]
Hi,

Could it be that in that namespace you had leftover pvcs from another release?

**Comment by arisdavid** [comment]
I was facing the same issue. It worked after deleting the PVC as suggested above. Uninstalled and reinstalled rabbitmq, working fine. 

Get the name of your pvc e.g. use kubectl. 

then delete it: 
`kubectl delete pvc <YOUR_PVC> --namespace=<YOUR_NAMESPACE>`

**Comment by exipnus** [comment]
Hello,

@juan131  As of 17/11/2022 this is still an issue. I deleted PVC/PV  and trying to use existingPasswordSecret

![image](https://user-images.githubusercontent.com/85255193/202418642-d53d9679-5439-4fd2-b324-f41ff14980f6.png)


then in the logs I get 

![image](https://user-images.githubusercontent.com/85255193/202418781-42b597d2-bfbb-4a56-a0bf-0b428c2cd75b.png)

I have created the secret:

![image](https://user-images.githubusercontent.com/85255193/202419138-9794f437-7f0c-48d7-b657-375208e012f0.png)


Am I doing something wrong?

Thanks

**Comment by Lieutenant-Fortis** [comment]
> Hello,
> 
> @juan131 As of 17/11/2022 this is still an issue. I deleted PVC/PV and trying to use existingPasswordSecret
> 
> ![image](https://user-images.githubusercontent.com/85255193/202422045-e261a600-68f9-462c-9bf0-33cc30aef6b6.png)
> 
> then in the logs I get
> 
> ![image](https://user-images.githubusercontent.com/85255193/202418781-42b597d2-bfbb-4a56-a0bf-0b428c2cd75b.png)
> 
> I have created the secret:
> 
> ![image](https://user-images.githubusercontent.com/85255193/202419138-9794f437-7f0c-48d7-b657-375208e012f0.png)
> 
> Am I doing something wrong?
> 
> Thanks

Have the same issue... Looking for solution.

**Comment by ppostnov** [comment]
> > Hello,
> > @juan131 As of 17/11/2022 this is still an issue. I deleted PVC/PV and trying to use existingPasswordSecret
> > ![image](https://user-images.githubusercontent.com/85255193/202422045-e261a600-68f9-462c-9bf0-33cc30aef6b6.png)
> > then in the logs I get
> > ![image](https://user-images.githubusercontent.com/85255193/202418781-42b597d2-bfbb-4a56-a0bf-0b428c2cd75b.png)
> > I have created the secret:
> > ![image](https://user-images.githubusercontent.com/85255193/202419138-9794f437-7f0c-48d7-b657-375208e012f0.png)
> > Am I doing something wrong?
> > Thanks
> 
> Have the same issue... Looking for solution.

I am too and will be appreciate for help !

**Comment by FranAguiar** [comment]
Same issue here, I trying older versions but the issue seems to be there too (I'm deleting the PVC)

**Comment by FranAguiar** [comment]
@ppostnov @Lieutenant-Fortis @exipnus 
Hello guys, I created a new issue, I hope we can get some attention. If you want to add your thoughts do not hesitate to post here: https://github.com/bitnami/charts/issues/13758

**Comment by sunnynehar56** [comment]
I had the same issue, I resolved it by having the correct valid JSON definition file.
Scaled-down sts to 0, deleted the PVCs, changed definitions secret, scaled up everything working fine.

below logs are missing earlier

```
2023-01-10 11:32:58.771713+00:00 [info] <0.502.0> Applying definitions from file at '/app/definitions.json'

2023-01-10 11:32:58.771764+00:00 [info] <0.502.0> Asked to import definitions. Acting user: rmq-internal

2023-01-10 11:32:58.771848+00:00 [info] <0.502.0> Importing concurrently 2 users...

2023-01-10 11:32:58.774668+00:00 [info] <0.497.0> Successfully changed password for user 'user'

2023-01-10 11:32:58.774670+00:00 [info] <0.496.0> Successfully changed password for user 'management'

2023-01-10 11:32:58.774749+00:00 [info] <0.497.0> Successfully set user tags for user 'system' to [administrator]

2023-01-10 11:32:58.774761+00:00 [info] <0.496.0> Successfully set user tags for user 'management' to [management]

2023-01-10 11:32:58.774874+00:00 [info] <0.502.0> Importing concurrently 1 vhosts...

2023-01-10 11:32:58.777266+00:00 [info] <0.502.0> Importing concurrently 1 permissions...

2023-01-10 11:32:58.779990+00:00 [info] <0.496.0> Successfully set permissions for 'system' in virtual host '/' to '.*', '.*', '.*'

2023-01-10 11:32:58.782283+00:00 [info] <0.502.0> Importing sequentially 1 policies...
```
