### ISSUE TITLE
Deploy kafka 3.7.0 using helm

### ISSUE THREAD

**Issue by vnktsai** [bitnami/charts#28722]
### Name and Version

bitnami/kafka 3.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm running k8s 1.30 and would like to deploy kafka3.7.0 using helm. Which tag/release supports this?

**Comment by tbotnz** [comment]
@vnktsai you want to use version 29.3.2

see https://github.com/bitnami/charts/tree/82f0e6c052c92a7e92460effe5efe3f88c3222cf/bitnami/kafka

**Comment by vnktsai** [comment]
@tbotnz  Could you please assist me in finding information about which Helm chart versions support specific versions of PostgreSQL and Redis? I'm looking for a README or documentation that provides this compatibility information, as it will be helpful for my deployment. Thank you!
