### ISSUE TITLE
[bitnami/kafka] Allow podSelector from any namespaceSelector

### ISSUE THREAD

**Issue by tbotnz** [bitnami/charts#28720]
### Name and Version

bitnami/kafka 30.0.1

### What is the problem this feature will solve?

We would like an ingress netpol to allow a podSelector label from any namespace. Using podSelector alone means the client pod must be in the same namespace, so we need to use "namespaceSelector and podSelector". We want to bring the bitnami/kafka netpol behavior inline with the bitnami/redis as per #12607

### What is the feature you are proposing to solve the problem?

Update networkpolicy.yaml template to allow ingressNSMatchLabels={} and podSelector=whatever:labels

### What alternatives have you considered?

Alternative / workaround: Manual update of netpol.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by tbotnz** [comment]
Thanks for merging the PR, in the docker registry https://hub.docker.com/r/bitnamicharts/kafka/tags its still only showing the old version, is anything else needed to get 30.0.2 in there?
