### ISSUE TITLE
[bitnami/redis]  Can't initialize Background Jobs. Error message: Operation not permitted

### ISSUE THREAD

**Issue by QQandWX** [bitnami/charts#28743]
### Name and Version

bitnami/redis

### What architecture are you using?

None

### What steps will reproduce the bug?

I use latest bitnami/redis chart and image:   bitnami/redis:7.0.5-debian-11-r6

master1, slave1.
and I get error in both pods:
```
1:C 07 Aug 2024 10:37:03.799 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 07 Aug 2024 10:37:03.799 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Aug 2024 10:37:03.799 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Aug 2024 10:37:03.799 * Configuration loaded
1:M 07 Aug 2024 10:37:03.800 * monotonic clock: POSIX clock_gettime
1:M 07 Aug 2024 10:37:03.802 * Running mode=standalone, port=6379.
1:M 07 Aug 2024 10:37:03.803 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 07 Aug 2024 10:37:03.803 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted
```

**Comment by QQandWX** [comment]
is redis:7.2.5-debian-12-r4

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by QQandWX** [comment]
My Docker version: 20.10.8
My linux:  ubuntu:18.04          kernel : 4.15.0-76-generic

I had a test again
Here are my testing steps：
1、helm repo add bitnami https://charts.bitnami.com/bitnami
2、helm pull bitnami/redis
3、tar vxf redis-19.6.4.tgz 
4、vim values.yml 
global:
  storageClass: "rook-cephfs"
architecture: standalone
5、I didn't do anything else afterwards，  i run： helm install redis ./ -n redis
i got:
NAME             READY   STATUS             RESTARTS   AGE
redis-master-0   0/1     CrashLoopBackOff   5          5m54s

logs:
1:C 08 Aug 2024 07:57:14.009 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 08 Aug 2024 07:57:14.009 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 08 Aug 2024 07:57:14.009 * Configuration loaded
1:M 08 Aug 2024 07:57:14.094 * monotonic clock: POSIX clock_gettime
1:M 08 Aug 2024 07:57:14.096 * Running mode=standalone, port=6379.
1:M 08 Aug 2024 07:57:14.096 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 08 Aug 2024 07:57:14.096 # Fatal: Can't initialize Background Jobs. Error message: Operation not permitted

**Comment by misslxs** [comment]
I also encountered this error when starting the Redis image while using Helm to create the Harbor repository

k8s version :v1.22.5
os : Ubuntu 20.04.6 LTS
redis image version :7.2.5-debian-12-r4

**Comment by javsalgar** [comment]
Looking at the logs, this is done by Redis itself, not the Bitnami logic. So, my advice is to check with the upstream Redis developers.

**Comment by QQandWX** [comment]
I set container privileged=true , the pod can run

  containerSecurityContext:
    enabled: true
    privileged: true
    allowPrivilegeEscalation: true
