### ISSUE TITLE
[bitnami/kafka] Unable to deploy Kafka 3.7.0 cluster

### ISSUE THREAD

**Issue by vnktsai** [bitnami/charts#28740]
### Name and Version

bitnami/kafka 3.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I installed using the below command
    `helm install   kafka-test bitnami/kafka -f values.yaml --version 29.3.2`
2. All 3 Pods are going into crashloopbackoff state.
3. I also tried this #24817 but the still had the same issue.

### Are you using any custom parameters or values?

```yaml
image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.7

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 2

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 2

zookeeper:
  enabled: false

kraft:
  enabled: true
  clusterId: "" # Ensure this is set
  controllerQuorumVoters: "0@kafka-test-controller-0.kafka-test-controller-headless.default.svc.cluster.local:9093,1@kafka-test-controller-1.kafka-test-controller-headless.default.svc.cluster.local:9093,2@kafka-test-controller-2.kafka-test-controller-headless.default.svc.cluster.local:9093"

listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""
networkPolicy:
  enabled: false
```

### What is the expected behavior?

I would expect the Kafka 3 node cluster to be healthy

### What do you see instead?

```
INFO [BrokerServer id=2] Transition from STARTING to STARTED (kafka.server.BrokerServer)
[2024-08-07 07:47:08,829] ERROR [BrokerServer id=2] Fatal error during broker startup. Prepare to shutdown (kafka.server.BrokerServer)
java.lang.RuntimeException: Received a fatal error while waiting for the controller to acknowledge that we are caught up
        at org.apache.kafka.server.util.FutureUtils.waitWithLogging(FutureUtils.java:68)
        at kafka.server.BrokerServer.startup(BrokerServer.scala:500)
        at kafka.server.KafkaRaftServer.$anonfun$startup$2(KafkaRaftServer.scala:99)
        at kafka.server.KafkaRaftServer.$anonfun$startup$2$adapted(KafkaRaftServer.scala:99)
        at scala.Option.foreach(Option.scala:407)
        at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:99)
        at kafka.Kafka$.main(Kafka.scala:112)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.util.concurrent.CancellationException
        at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
        at kafka.server.BrokerLifecycleManager$ShutdownEvent.run(BrokerLifecycleManager.scala:586)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:186)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Additional information

Using Kubernetes version 1.30
Calico 3.28.0

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by PAzter1101** [comment]
I also encountered this problem :(
`networkPolicy.enabled: false` does not help

**Comment by yaoquanxin** [comment]
bitnami kafka default chart have so many probelm ,- -
