### ISSUE TITLE
[bitnami/mongodb] new empty-dir volume should have configurable sizelimt

### ISSUE THREAD

**Issue by monotek** [bitnami/charts#28742]
### Name and Version

bitnami/mongodb @15.6.16

### What is the problem this feature will solve?

The new empty-dir volume has no configurable sizelimt.
This is forbidden by a policy in our case.

### What is the feature you are proposing to solve the problem?

The empty-dir volume should have a configurable sizelimt.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by monotek** [comment]
done: https://github.com/bitnami/charts/pull/28771

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look

**Comment by monotek** [comment]
@bitnami-bot reopen
