### ISSUE TITLE
Most bitnami charts missing from ArtifactHUB.

### ISSUE THREAD

**Issue by orendain** [bitnami/charts#28765]
### Name and Version

bitnami/keycloak 22.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Navigate to any one of the following:
- https://artifacthub.io/packages/helm/bitnami/keycloak: `Sorry, the package you requested was not found.`
- https://artifacthub.io/packages/helm/bitnami/postgresql: `Sorry, the package you requested was not found.`
- (list all Bitnami charts) https://artifacthub.io/packages/search?org=bitnami&sort=relevance&page=1: 3 results.

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

All bitnami charts are published/picked up by ArtifactHub.

### What do you see instead?

Vast majority of bitnami charts missing.

### Additional information

Unsure if a publisher (bitnami) issuer or an ArtifactHUB one. Have cross-posted just in case and have not confirmed the issue's source.

**Comment by hongbo-miao** [comment]
Seems all gone such as

- https://artifacthub.io/packages/helm/bitnami/kafka
- https://artifacthub.io/packages/helm/bitnami/spark
- https://artifacthub.io/packages/helm/bitnami/schema-registry

**Comment by carrodher** [comment]
I am not aware of any change on our side, we are publishing our charts as usual. Let's see what's the conclusion of the issue created in the ArtifactHub repo

**Comment by orendain** [comment]
Closing as addressed by https://github.com/artifacthub/hub/issues/3973.
