### ISSUE TITLE
Why can't I enable zookeeper SSL?

### ISSUE THREAD

**Issue by skyrise-l** [bitnami/charts#28778]
### Name and Version

bitnami/zookeeper

### What architecture are you using?

None

### What steps will reproduce the bug?

I modified the configuration file zoo.cfg and set environment variables, and I am sure that the environment variables and configuration file are effective. The specific settings are as follows. I am also sure that my certificate exists and is OK, but when I use something like Kafka to connect, I can still connect directly without authentication. May I ask what else I need to set to configure Zookeeper's SSL?

### Are you using any custom parameters or values?

```bash
    # ZooKeeper configuration entries for TLS
    echo >> /opt/bitnami/zookeeper/conf/zoo.cfg  
    export ZOO_TLS_CLIENT_ENABLE=true
    echo "tls.client.enabled=true" >> /opt/bitnami/zookeeper/conf/zoo.cfg
    export ZOO_TLS_CLIENT_AUTH=need
    echo "tls.client.auth=need" >> /opt/bitnami/zookeeper/conf/zoo.cfg
    export ZOO_TLS_CLIENT_KEYSTORE_FILE=$PEM_CERT_LOCATION
    echo "tls.client.keystorePath=${PEM_CERT_LOCATION}" >> /opt/bitnami/zookeeper/conf/zoo.cfg
    export ZOO_TLS_CLIENT_TRUSTSTORE_FILE=$PEM_CA_LOCATION
    echo "tls.client.truststorePath=${PEM_CA_LOCATION}" >> /opt/bitnami/zookeeper/conf/zoo.cfg
    export ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=""
    echo "tls.client.keystorePassword=" >> /opt/bitnami/zookeeper/conf/zoo.cfg
    export ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=""
    echo "tls.client.truststorePassword=" >> /opt/bitnami/zookeeper/conf/zoo.cfg
    
    export ZOO_ENABLE_AUTH=yes
    export ALLOW_ANONYMOUS_LOGIN=no
```

### What do you see instead?

connect directly without authentication.

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
