### ISSUE TITLE
[bitnami/rabbitmq] extraEnvVars example incorrect

### ISSUE THREAD

**Issue by connorearl** [bitnami/charts#2877]
**Which chart**:
rabbitmq 7.0.0

**Describe the bug**
The example in values-production shows the extraEnvVars format as below
```
extraEnvVars:
   - name: FOO
     value: BAR
```
When it should actually be:
```
extraEnvVars:
  FOO: BAR
```

**Comment by joancafom** [comment]
Hi @connorearl ,

Thanks for reporting! This issue was already fixed in a recent PR #2867 and has already been released, so updating the Chart will make it work with the format you find in both `values` and `values-production`. 

Thanks!
