### ISSUE TITLE
[Bitnami/elasticsearch]: Init container `copy-tls-certificates` image name hardcoded and does not respect global imageRegistry value.

### ISSUE THREAD

**Issue by majikman111** [bitnami/charts#28787]
### Name and Version

bitnami/elasticsearch 21.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In all ElasticSearch stateful sets, when security is enabled a init container named `copy-tls-certificates` is declared with the hardcoded image
          `image: bitnami/os-shell:12-debian-12-r22`
This hardcoded image does not respect the global imageRegistry value and so security cannot be enabled in an air-gapped environment and/or when using a custom docker registry.

See [here ](https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/templates/master/statefulset.yaml#L110) for an example.

This image specification should use a helper template and include that here like all the other init containers in the chart do.

### Are you using any custom parameters or values?

```yaml
global:
  imageRegistry: "custom-registry.net"
security:
  enabled: true
```

### What is the expected behavior?

The stateful set pods should successfully pull all container images from the global imageRegistry.

### What do you see instead?

The `copy-tls-certificates` container fails to pull an image from the global imageRegistry and instead tries to use docker.io

**Comment by majikman111** [comment]
This issue is still present

**Comment by fmulero** [comment]
Thanks a lot @majikman111 for bring this issue to our attention.

I've just created #29083 to solve it. I appreciate your review

**Comment by majikman111** [comment]
Looks good to me
