### ISSUE TITLE
[bitnami/rabbitmq] Custom username cannot set password

### ISSUE THREAD

**Issue by connorearl** [bitnami/charts#2878]
**Which chart**:
rabbitmq 7.0.0

**Describe the bug**
When a custom user and existing secret is set for the password, the pod will fail to start with error 
`Couldn't change password for user 'user'`

**To Reproduce**
1. Set username using `auth.username`
2. Set password using `auth.existingPasswordSecret`

**Expected behavior**
The pod to start successfully with the user I requested

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
To work around it you can add the env var as below:
```
extraEnvVars:
  RABBITMQ_USERNAME: customUserName
```

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. Just did this

```
kubectl create secret generic rabbittest --from-literal=rabbitmq-password=test1234
helm install rab bitnami/rabbitmq --set auth.username=test --set auth.existingPasswordSecret=rabbittest

...

 1 ❯ kubectl get pods  -w
NAME             READY   STATUS    RESTARTS   AGE
rab-rabbitmq-0   1/1     Running   0          2m42s
```

Could you try with the latest release of the chart? I see that 7.0.3 is available
