### ISSUE TITLE
[bitnami/redis-cluster] Replace default Secret by Secret Provider Class

### ISSUE THREAD

**Issue by Praveen-98cs** [bitnami/charts#28788]
### Name and Version

bitnami/redis-cluster latest

### What is the problem this feature will solve?

I wanted to store the redis-cluster password as a secret in hashicorp and retrieve from there. I created a secret-provider-class for that but the problem is the default, secret.yaml secret is getting created which I don't want when i do the helm install. 
 
Is there a way I can use only the secret that is getting created from  secret-provider-class and a way i can omit secret.yaml to stop deploying without editing the default templates? maybe add a part to the secret-provider-class or add something in the values.yaml file?

### What is the feature you are proposing to solve the problem?

I saw that using flux-helm-release you can omit secret from getting created but my problem is, then it will stop creating the secret from the secret-provider-class cause I have given the same name. which is redis-cluster.

**Comment by javsalgar** [comment]
Hi!

Would the `existingSecret` value work for your use case? 

```
## @param existingSecret Name of existing secret object (for password authentication)
##
existingSecret: ""
```
