### ISSUE TITLE
[bitnami/redis-cluster] Unable to deploy redis-cluster 7.2.5

### ISSUE THREAD

**Issue by vnktsai** [bitnami/charts#28789]
### Name and Version

bitnami/redis-cluster 7.2.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I installed using the below command
   helm install   new-redis oci://registry-1.docker.io/bitnamicharts/redis-cluster  -f values.yaml
2. All 6 Pods are going into crashloopbackoff state.
  new-redis-redis-cluster-0   0/1     CrashLoopBackOff   6 (110s ago)     7m33s
new-redis-redis-cluster-1   0/1     CrashLoopBackOff   6 (109s ago)     7m33s
new-redis-redis-cluster-2   0/1     CrashLoopBackOff   6 (101s ago)     7m33s
new-redis-redis-cluster-3   0/1     CrashLoopBackOff   6 (104s ago)     7m33s
new-redis-redis-cluster-4   0/1     CrashLoopBackOff   6 (114s ago)     7m33s
new-redis-redis-cluster-5   0/1     CrashLoopBackOff   1 (5s ago)       7s
3. I also gone through this #7868 issue. But didn't find any solution

### What is the expected behavior?

I would expect the redis-cluster  node to be healthy

### What do you see instead?

/bin/bash: line 12: /opt/bitnami/scripts/redis-cluster/entrypoint.sh: No such file or directory

### Additional information

Using Kubernetes version 1.30
Calico 3.28.0

**Comment by javsalgar** [comment]
Hi! Could you share the logs? Did you try with image.debug=true?

**Comment by waqas543** [comment]
I have got the same issue. 


`Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  16s   default-scheduler  Successfully assigned test/redis-cluster-0 to pageloaderc1
  Normal   Pulled     12s   kubelet            Container image "docker.io/bitnami/redis-cluster:7.2.5-debian-12-r2" already present on machine
  Normal   Created    12s   kubelet            Created container redis-cluster
  Normal   Started    11s   kubelet            Started container redis-cluster
  Normal   Pulled     11s   kubelet            Container image "docker.io/bitnami/redis-exporter:1.61.0-debian-12-r2" already present on machine
  Normal   Created    11s   kubelet            Created container metrics
  Normal   Started    11s   kubelet            Started container metrics
  Warning  Unhealthy  4s    kubelet            Liveness probe failed: Could not connect to Redis at localhost:6379: Connection refused
  Warning  Unhealthy  4s    kubelet            Readiness probe failed: Could not connect to Redis at localhost:6379: Connection refused`
