### ISSUE TITLE
[bitnami/flux] Use Helm Lookup for CRDs

### ISSUE THREAD

**Issue by jl-beast** [bitnami/charts#28812]
### Name and Version

bitnami/flux 2.3.14

### What is the problem this feature will solve?

If there is already an existing Custom Resource Definition on the Cluster when installing Flux, I am unable to install it with a chart. 

I desire to port a helm chart with Flux as a dependency so that I can safely template the HelmRepository/OCIRepository/HelmChart/HelmRelease CRDs. The reason I want to do this is that I have to provide a helm chart as a final product, but the growing complexity of the chart demands extra-layers of preprocessing and flexible deployment, whilst I am limited on what tools I can use, though operators are fair game.

This, however, becomes an issue when I have multiple deployments of the same chart onto the same cluster. Whilst the controllers should conduct a leader-election and prevent any operator issues, the chart itself is fighting me.

### What is the feature you are proposing to solve the problem?

I propose adding a flag or some template that can be added to the values.yaml that when installing the CRDs will do a lookup for those CRDs already existing. This should allow for deployments.

### What alternatives have you considered?

I have considered just controlling this via InstallCRDs when installing or copying the chart and making a custom version.

The first makes installation harder and makes automation more complex, whereas having a custom version makes future updates more annoying.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward this to the team but as it is not a critical feature we cannot guarantee an ETA. However, if you want to speed up the process, you can submit a PR adding support for the `lookup` option (making sure this does not break `helm template` based installations) and the team will take a look
