### ISSUE TITLE
[bitnami/wordpress] Better custom image/CI-CD instructions

### ISSUE THREAD

**Issue by ZeldOcarina** [bitnami/charts#28835]
### Name and Version

bitnami/wordpress 23.1.1

### What is the problem this feature will solve?

I have been working for about a month with this Helm Chart and I am not seeing a path to get a proper CI/CD workflow when I update a Wordpress theme to publish changes automatically in the Cluster.

### What is the feature you are proposing to solve the problem?

What I would do is having better docs on how to publish your own image starting from Bitnami's Wordpress (I've tried what is already written but it's super minimal and confusing imo) and how to connect a CI/CD pipeline.

### What alternatives have you considered?

I've tried debugging this myself but I've fallen back to using a migration plugin on any code changes.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the documentation improvement request. I am afraid that, as it is not a critical feature, we cannot guarantee an ETA on this. However, in order to benefit the community, could you let us know the issues you found?

**Comment by ZeldOcarina** [comment]
Closing issues for inactivity automatically is dumb, if a real issue arises nobody would notice..

**Comment by ZeldOcarina** [comment]
The issue anyways is there's no clear path to automatically spin up a Wordpress instance already with a theme and uploads plus an existing database. It probably can be done but I could not figure out how, let alone use a CI/CD pipeline for it!
