### ISSUE TITLE
[bitnami/apache] cloneHtdocsFromGit causes CrashLoopBackOff in git-repo-syncer 

### ISSUE THREAD

**Issue by russau** [bitnami/charts#28845]
### Name and Version

bitnami/apache 11.2.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Attempting to use the cloneHtdocsFromGit feature of the `bitnami/apache ` chart

```
helm install my-apache bitnami/apache  \
  --set-string cloneHtdocsFromGit.repository=https://github.com/russau/static-site.git \
  --set-string cloneHtdocsFromGit.enabled=true \
  --set-string cloneHtdocsFromGit.branch=main
```

You will see a `Back-off restarting failed container git-repo-syncer` in the created pod

### What is the expected behavior?

Expecting to see the github repo getting cloned and displayed by apache.

### What do you see instead?

Seeing a failure in the `git-repo-syncer` container.

### Additional information

I did some debugging and I think I can see this line in the `entrypoint.sh` is failing when it attempts to create a ssh key on the readonly file system.

https://github.com/bitnami/containers/blob/main/bitnami/git/2/debian-12/rootfs/opt/bitnami/scripts/git/entrypoint.sh#L35

I can see the nginx chart mounts a writable `/etc/ssh` into the container:
https://github.com/bitnami/charts/blob/nginx/18.1.7/bitnami/nginx/templates/deployment.yaml#L189-L200

Whereas the apache chart doesn't: https://github.com/bitnami/charts/blob/apache/11.2.13/bitnami/apache/templates/deployment.yaml#L151-L156

**Comment by javsalgar** [comment]
Hi,

Thank you so much for spotting the issue! Probably, in this chart we may also require mounting that etc folder. Would you like to submit a PR adding it, just like the nginx chart?

**Comment by russau** [comment]
This makes sense to me now! The issue goes away when I use `--set containerSecurityContext.enabled=false`.  Looks like it was introduced with this commit: https://github.com/bitnami/charts/commit/6b0889197e33f20b93f84fee9e6917634f358efc

I'll test a pull request tomorrow.

**Comment by javsalgar** [comment]
Thank you so much for the PR!
