### ISSUE TITLE
[bitnami/keycloak] remove proxy parameter (breaking)

### ISSUE THREAD

**Issue by singhbaljit** [bitnami/charts#28840]
### Name and Version

bitnami/keycloak: 22

### What is the problem this feature will solve?

Keycloak has moved to start using `proxyHeaders`, and `proxy` flag has been deprecated. The container was updated, and it only supports `KEYCLOAK_PROXY_HEADERS` environment variable. However, the chart still supports `proxy`, which it emulates by just passing the `KEYCLOAK_PROXY_HEADERS` value. We should simplify the chart, and just remove the `proxy` parameter.

### What is the feature you are proposing to solve the problem?

Simplifies certain conditional logic in the chart since currently both `proxy` and `proxyHeaders` are supported.

**Comment by javsalgar** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
