### ISSUE TITLE
[bitnami/discourse] Plugins are not installed when added in the helm-release 

### ISSUE THREAD

**Issue by Giiltham** [bitnami/charts#28871]
### Name and Version

bitnami/discourse 13.2.15

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Add discourse-solved in the helm-release
```
  discourse:
    plugins:
      - https://github.com/discourse/discourse-solved
```
2. Check the logs at startup, the plugin is cloned

```
Cloning into '/opt/bitnami/discourse/plugins/discourse-solved'...
{
  "discourse-solved": "1bbdfd8f"
}
checking out compatible discourse-solved version: 526a44644a7b3f0c2a3ba4fc16e72f364e9fce6d
HEAD is now at 526a446 FIX: Nest combobox within LI element (#280)
[38;5;6mdiscourse [38;5;5m09:46:14.63 [0m[38;5;2mINFO [0m ==> 
[38;5;6mdiscourse [38;5;5m09:46:14.63 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami discourse container[0m
[38;5;6mdiscourse [38;5;5m09:46:14.63 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[38;5;6mdiscourse [38;5;5m09:46:14.63 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[38;5;6mdiscourse [38;5;5m09:46:14.63 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[38;5;6mdiscourse [38;5;5m09:46:14.63 [0m[38;5;2mINFO [0m ==> 
[38;5;6mdiscourse [38;5;5m09:46:14.64 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_CLIENT_* env vars
[38;5;6mdiscourse [38;5;5m09:46:14.65 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
[38;5;6mdiscourse [38;5;5m09:46:14.67 [0m[38;5;2mINFO [0m ==> Creating database bitnami_application
[38;5;6mdiscourse [38;5;5m09:46:14.83 [0m[38;5;2mINFO [0m ==> Creating Discourse configuration file
[38;5;6mdiscourse [38;5;5m09:46:14.91 [0m[38;5;2mINFO [0m ==> Restoring persisted Discourse installation
[38;5;6mdiscourse [38;5;5m09:46:15.06 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
[38;5;6mdiscourse [38;5;5m09:46:15.08 [0m[38;5;2mINFO [0m ==> Running database migrations
[38;5;6mdiscourse [38;5;5m09:46:32.85 [0m[38;5;2mINFO [0m ==> Precompiling assets, this may take some time...

[38;5;6mdiscourse [38;5;5m09:49:59.15 [0m[38;5;2mINFO [0m ==> ** Discourse setup finished! **
[38;5;6mdiscourse [38;5;5m09:49:59.18 [0m[38;5;2mINFO [0m ==> ** Starting Discourse **
=============== Phusion Passenger(R) Standalone web server started ===============
PID file: /opt/bitnami/discourse/passenger.8080.pid
Log file: /opt/bitnami/discourse/log/passenger.8080.log
Environment: production
Accessible via: http://0.0.0.0:8080/

You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
```

3. The plugin can't be found in /opt/bitnami/discourse/plugins/ or in the application itself (administration -> plugins)

### What do you see instead?

The plugin can't be found in /opt/bitnami/discourse/plugins/ or in the application itself (administration -> plugins)

### Additional information

I can bash in the pod and execute : 
`RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/discourse/discourse-solved`
which does work

**Comment by jotamartos** [comment]
I just tried to reproduce the issue but the plugin was included in the plugins folder after the deployment finished. I edited the values.yaml file 

```
diff --git a/bitnami/discourse/values.yaml b/bitnami/discourse/values.yaml
index 1e451805ae..b5746ad53b 100644
--- a/bitnami/discourse/values.yaml
+++ b/bitnami/discourse/values.yaml
@@ -290,7 +290,8 @@ discourse:
   ## plugins:
   ##   - https://github.com/discourse/discourse-oauth2-basic
   ##
-  plugins: []
+  plugins:
+      - https://github.com/discourse/discourse-solved
   ## @param discourse.persistPlugins Persist plugins across container restarts
   ##
   persistPlugins: true

```

and confirmed that the folder existed 

```
➜  discourse git:(main) k exec -it discouse-discourse-76b694fb5-xr6gn -- ls /opt/bitnami/discourse/plugins/
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
Defaulted container "discourse" out of: discourse, sidekiq
chat               discourse-lazy-videos    discourse-presence  poll
checklist          discourse-local-dates    discourse-solved    spoiler-alert
discourse-details  discourse-narrative-bot  footnote            styleguide
```

**Comment by hxtmdev** [comment]
@Giiltham try to reproduce this with a fresh deployment (especially fresh PVC) with `persistPlugins: false` from the start. This helped with plugin changes in my case.
If that solves your problem you might have to transition to `persistPlugins: false` somehow if you can't reinstall fresh, no idea if manual changes are necessary to keep the PVC but not "persist" the plugins, might be as some plugins might already be "persisted".

**Comment by Giiltham** [comment]
> @Giiltham try to reproduce this with a fresh deployment (especially fresh PVC) with `persistPlugins: false` from the start. This helped with plugin changes in my case. If that solves your problem you might have to transition to `persistPlugins: false` somehow if you can't reinstall fresh, no idea if manual changes are necessary to keep the PVC but not "persist" the plugins, might be as some plugins might already be "persisted".

It worked thanks.

**Comment by Giiltham** [comment]
Shouldn't it be specified to try using "persistPlugins: false" in the discourse chart readme if plugins don't work by default ? I've found several topics on internet talking about this afterwards.

**Comment by hxtmdev** [comment]
I think [this](https://github.com/bitnami/charts/blob/6cf09bebecb993ed045ab7f4147254ea2bebe72f/bitnami/discourse/README.md?plain=1#L114) covers it.

**Comment by Giiltham** [comment]
Yes, but i think it could be a little more explicit on the subject, it's not only that we can't upgrade them but also that we can add new ones. 
I understand that the message covers it but that's not always straightforward at a first glance, while i think it is a behavior we would expect by default on any other discourse instance

**Comment by hxtmdev** [comment]
I myself only read the comment in the `values.yaml` when I started out, so adding it there and explicitly stating "no additions" would probably be an improvement, yes 👍🏻

**Comment by jotamartos** [comment]
I'm glad to hear you manage to solve the issue with the plugin. As I mentioned, it worked without problems in a fresh deployment. If you think the documentation can be improved, please follow [the contribution guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) to help the users in the future when running into this issue.
