### ISSUE TITLE
[bitnami/discourse] Allow configuration of POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS for specific plugins

### ISSUE THREAD

**Issue by AMontagu** [bitnami/charts#28870]
### Name and Version

bitnami/discourse 13.2.15

### What is the problem this feature will solve?

Some discource plugins as [discourse-ai](https://github.com/discourse/discourse-ai) need Postgres extension as "vector". 

But it seem the CM value used to declare extensions are not configurable: https://github.com/bitnami/charts/blob/bdd9234fed458a0a4fd14ee481fb33bf1c598806/bitnami/discourse/templates/configmaps.yaml#L50

### What is the feature you are proposing to solve the problem?

Is it possible to use a values with default value for that need ?

### What alternatives have you considered?

It's possible to deploy our own database with correct extension but it add deployment complexity.
It's also possible to dynamically change the config maps before recreating the database but it add a manual action.
Connect directly to the SQL pods and install the extension manually

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. Indeed, it makes sense to make that section configurable with a value. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding that value (having `hstore, pg_trgm` as default) and we will check it.
