### ISSUE TITLE
Spark executors are getting exited with status1 & error code1

### ISSUE THREAD

**Issue by ankit302** [bitnami/charts#2888]
HI @javsalgar ,

I'm also facing the same issue, I'm running spark in cluster mode, 1 master & 1 worker in AKS -kubernetes environment.

Worker node logs :
20/06/18 16:46:05 INFO Worker: Asked to launch executor app-20200618164330-0000/67 for Spark shell 20/06/18 16:46:05 INFO SecurityManager: Changing view acls to: root 20/06/18 16:46:05 INFO SecurityManager: Changing modify acls to: root 20/06/18 16:46:05 INFO SecurityManager: Changing view acls groups to: 20/06/18 16:46:05 INFO SecurityManager: Changing modify acls groups to: 20/06/18 16:46:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); groups with view permissions: Set(); users with modify permissions: Set(root); groups with modify permissions: Set() 20/06/18 16:46:05 INFO ExecutorRunner: Launch command: "/usr/lib/jvm/java-1.8-openjdk/jre/bin/java" "-cp" "///conf:/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=32813" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@spark-master-854c767679-wxl4h:32813" "--executor-id" "67" "--hostname" "10.24.0.43" "--cores" "1" "--app-id" "app-20200618164330-0000" "--worker-url" "spark://Worker@10.24.0.43:34573" 20/06/18 16:46:08 INFO Worker: Executor app-20200618164330-0000/67 finished with state EXITED message Command exited with code 1 exitStatus 1 20/06/18 16:46:08 INFO ExternalShuffleBlockResolver: Clean up non-shuffle files associated with the finished executor 67 20/06/18 16:46:08 INFO ExternalShuffleBlockResolver: Executor is not registered (appId=app-20200618164330-0000, execId=67) 20/06/18 16:46:08 INFO Worker: Asked to launch executor app-20200618164330-0000/68 for Spark shell 20/06/18 16:46:08 INFO SecurityManager: Changing view acls to: root 20/06/18 16:46:08 INFO SecurityManager: Changing modify acls to: root 20/06/18 16:46:08 INFO SecurityManager: Changing view acls groups to: 20/06/18 16:46:08 INFO SecurityManager: Changing modify acls groups to: 20/06/18 16:46:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); groups with view permissions: Set(); users with modify permissions: Set(root); groups with modify permissions: Set() 20/06/18 16:46:08 INFO ExecutorRunner: Launch command: "/usr/lib/jvm/java-1.8-openjdk/jre/bin/java" "-cp" "///conf:/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=32813" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@spark-master-854c767679-wxl4h:32813" "--executor-id" "68" "--hostname" "10.24.0.43" "--cores" "1" "--app-id" "app-20200618164330-0000" "--worker-url" "spark://Worker@10.24.0.43:34573" 20/06/18 16:46:10 INFO Worker: Asked to kill executor app-20200618164330-0000/68 20/06/18 16:46:10 INFO ExecutorRunner: Runner thread for executor app-20200618164330-0000/68 interrupted 20/06/18 16:46:10 INFO ExecutorRunner: Killing process! 20/06/18 16:46:10 INFO Worker: Executor app-20200618164330-0000/68 finished with state KILLED exitStatus 1 20/06/18 16:46:10 INFO ExternalShuffleBlockResolver: Clean up non-shuffle files associated with the finished executor 68 20/06/18 16:46:10 INFO ExternalShuffleBlockResolver: Executor is not registered (appId=app-20200618164330-0000, execId=68)

Master node logs:-

20/06/18 16:45:26 INFO Master: Removing executor app-20200618164330-0000/49 because it is EXITED 20/06/18 16:45:26 INFO Master: Launching executor app-20200618164330-0000/50 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:29 INFO Master: Removing executor app-20200618164330-0000/50 because it is EXITED 20/06/18 16:45:29 INFO Master: Launching executor app-20200618164330-0000/51 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:31 INFO Master: Removing executor app-20200618164330-0000/51 because it is EXITED 20/06/18 16:45:31 INFO Master: Launching executor app-20200618164330-0000/52 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:33 INFO Master: Removing executor app-20200618164330-0000/52 because it is EXITED 20/06/18 16:45:33 INFO Master: Launching executor app-20200618164330-0000/53 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:35 INFO Master: Removing executor app-20200618164330-0000/53 because it is EXITED 20/06/18 16:45:35 INFO Master: Launching executor app-20200618164330-0000/54 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:38 INFO Master: Removing executor app-20200618164330-0000/54 because it is EXITED 20/06/18 16:45:38 INFO Master: Launching executor app-20200618164330-0000/55 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:40 INFO Master: Removing executor app-20200618164330-0000/55 because it is EXITED 20/06/18 16:45:40 INFO Master: Launching executor app-20200618164330-0000/56 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:42 INFO Master: Removing executor app-20200618164330-0000/56 because it is EXITED 20/06/18 16:45:42 INFO Master: Launching executor app-20200618164330-0000/57 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:45 INFO Master: Removing executor app-20200618164330-0000/57 because it is EXITED 20/06/18 16:45:45 INFO Master: Launching executor app-20200618164330-0000/58 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:47 INFO Master: Removing executor app-20200618164330-0000/58 because it is EXITED 20/06/18 16:45:47 INFO Master: Launching executor app-20200618164330-0000/59 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:49 INFO Master: Removing executor app-20200618164330-0000/59 because it is EXITED 20/06/18 16:45:49 INFO Master: Launching executor app-20200618164330-0000/60 on worker worker-20200618162718-10.24.0.43-34573 20/06/18 16:45:52 INFO Master: Removing executor app-20200618164330-0000/60 because it is EXITED 20/06/18 16:45:52 INFO Master: Launching executor app-20200618164330-0000/61 on worker worker-20200618162718-10.24.0.43-34573

Master Deployment file:-

apiVersion: apps/v1 kind: Deployment metadata: name: spark-master namespace: XXXXXXXXX labels: app: spark-master spec: selector: matchLabels: app: spark-master template: metadata: labels: app: spark-master spec: imagePullSecrets: - name: regcred containers: - name: spark-master image: registry.apps.aXXXXXXXXXX/spark-master:2.4.4-hadoop2.7 imagePullPolicy: Always ports: - containerPort: 8080 - containerPort: 7077 - containerPort: 6066

Worker Deployment configuration file:-

apiVersion: apps/v1 kind: Deployment metadata: name: spark-worker namespace: XXXXXXXX labels: app: spark-worker spec: selector: matchLabels: name: spark-worker template: metadata: labels: name: spark-worker spec: imagePullSecrets: - name: regcred containers: - env: - name: SPARK_MASTER value: spark://spark-master-hadoop:7077 name: spark-worker image: registry.apps.XXXXXX/spark-worker:2.4.4-hadoop2.7 imagePullPolicy: Always ports: - containerPort: 8081

service configuration for master :-

`apiVersion: v1
kind: Service
metadata:
name: spark-master-hadoop
namespace: XXXXXXXXXXXXX
spec:
type: ClusterIP
selector:
app: spark-master
ports:

name: web-ui
protocol: TCP
port: 8080
targetPort: 8080
name: master
protocol: TCP
port: 7077
targetPort: 7077
name: master-rest
protocol: TCP
port: 6066
targetPort: 6066

**Comment by dani8art** [comment]
Hi @ankit302 thank you for opening this issue, I was testing the example command and it seems to be working fine for me:

```bash
$ kubectl exec -ti --namespace default sp-spark-worker-0 -- spark-submit --master spark://10.51.255.229:7077     --class org.apache.spark.examples.SparkPi     $EXAMPLE_JAR 5
20/06/22 07:38:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/06/22 07:38:15 INFO SparkContext: Running Spark version 2.4.6
20/06/22 07:38:15 INFO SparkContext: Submitted application: Spark Pi
20/06/22 07:38:15 INFO SecurityManager: Changing view acls to: spark
20/06/22 07:38:15 INFO SecurityManager: Changing modify acls to: spark
20/06/22 07:38:15 INFO SecurityManager: Changing view acls groups to: 
20/06/22 07:38:15 INFO SecurityManager: Changing modify acls groups to: 
20/06/22 07:38:15 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
20/06/22 07:38:16 INFO Utils: Successfully started service 'sparkDriver' on port 39849.
20/06/22 07:38:16 INFO SparkEnv: Registering MapOutputTracker
20/06/22 07:38:16 INFO SparkEnv: Registering BlockManagerMaster
20/06/22 07:38:16 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/06/22 07:38:16 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/06/22 07:38:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f5f12a72-e305-423f-a392-dae63256a80e
20/06/22 07:38:16 INFO MemoryStore: MemoryStore started with capacity 413.9 MB
20/06/22 07:38:16 INFO SparkEnv: Registering OutputCommitCoordinator
20/06/22 07:38:16 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/06/22 07:38:16 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local:4040
20/06/22 07:38:16 INFO SparkContext: Added JAR file:/opt/bitnami/spark/examples/jars/spark-examples_2.11-2.4.6.jar at spark://sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local:39849/jars/spark-examples_2.11-2.4.6.jar with timestamp 1592811496854
20/06/22 07:38:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://10.51.255.229:7077...
20/06/22 07:38:17 INFO TransportClientFactory: Successfully created connection to /10.51.255.229:7077 after 67 ms (0 ms spent in bootstraps)
20/06/22 07:38:17 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20200622073817-0002
20/06/22 07:38:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20200622073817-0002/0 on worker-20200622073407-10.48.3.45-36155 (10.48.3.45:36155) with 1 core(s)
20/06/22 07:38:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20200622073817-0002/0 on hostPort 10.48.3.45:36155 with 1 core(s), 1024.0 MB RAM
20/06/22 07:38:17 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41997.
20/06/22 07:38:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20200622073817-0002/1 on worker-20200622073516-10.48.2.11-43149 (10.48.2.11:43149) with 1 core(s)
20/06/22 07:38:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20200622073817-0002/1 on hostPort 10.48.2.11:43149 with 1 core(s), 1024.0 MB RAM
20/06/22 07:38:17 INFO NettyBlockTransferService: Server created on sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local:41997
20/06/22 07:38:17 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/06/22 07:38:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20200622073817-0002/1 is now RUNNING
20/06/22 07:38:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20200622073817-0002/0 is now RUNNING
20/06/22 07:38:17 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local, 41997, None)
20/06/22 07:38:17 INFO BlockManagerMasterEndpoint: Registering block manager sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local:41997 with 413.9 MB RAM, BlockManagerId(driver, sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local, 41997, None)
20/06/22 07:38:17 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local, 41997, None)
20/06/22 07:38:17 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local, 41997, None)
20/06/22 07:38:18 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
20/06/22 07:38:19 INFO SparkContext: Starting job: reduce at SparkPi.scala:38
20/06/22 07:38:19 INFO DAGScheduler: Got job 0 (reduce at SparkPi.scala:38) with 5 output partitions
20/06/22 07:38:19 INFO DAGScheduler: Final stage: ResultStage 0 (reduce at SparkPi.scala:38)
20/06/22 07:38:19 INFO DAGScheduler: Parents of final stage: List()
20/06/22 07:38:19 INFO DAGScheduler: Missing parents: List()
20/06/22 07:38:19 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at map at SparkPi.scala:34), which has no missing parents
20/06/22 07:38:19 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 2.0 KB, free 413.9 MB)
20/06/22 07:38:19 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1381.0 B, free 413.9 MB)
20/06/22 07:38:19 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local:41997 (size: 1381.0 B, free: 413.9 MB)
20/06/22 07:38:19 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1163
20/06/22 07:38:19 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (10.48.2.11:33572) with ID 1
20/06/22 07:38:19 INFO DAGScheduler: Submitting 5 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at map at SparkPi.scala:34) (first 15 tasks are for partitions Vector(0, 1, 2, 3, 4))
20/06/22 07:38:19 INFO TaskSchedulerImpl: Adding task set 0.0 with 5 tasks
20/06/22 07:38:20 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, 10.48.2.11, executor 1, partition 0, PROCESS_LOCAL, 7870 bytes)
20/06/22 07:38:20 INFO BlockManagerMasterEndpoint: Registering block manager 10.48.2.11:44327 with 413.9 MB RAM, BlockManagerId(1, 10.48.2.11, 44327, None)
20/06/22 07:38:20 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.48.2.11:44327 (size: 1381.0 B, free: 413.9 MB)
20/06/22 07:38:20 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, 10.48.2.11, executor 1, partition 1, PROCESS_LOCAL, 7870 bytes)
20/06/22 07:38:21 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1031 ms on 10.48.2.11 (executor 1) (1/5)
20/06/22 07:38:21 INFO TaskSetManager: Starting task 2.0 in stage 0.0 (TID 2, 10.48.2.11, executor 1, partition 2, PROCESS_LOCAL, 7870 bytes)
20/06/22 07:38:21 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 122 ms on 10.48.2.11 (executor 1) (2/5)
20/06/22 07:38:21 INFO TaskSetManager: Starting task 3.0 in stage 0.0 (TID 3, 10.48.2.11, executor 1, partition 3, PROCESS_LOCAL, 7870 bytes)
20/06/22 07:38:21 INFO TaskSetManager: Finished task 2.0 in stage 0.0 (TID 2) in 55 ms on 10.48.2.11 (executor 1) (3/5)
20/06/22 07:38:21 INFO TaskSetManager: Starting task 4.0 in stage 0.0 (TID 4, 10.48.2.11, executor 1, partition 4, PROCESS_LOCAL, 7870 bytes)
20/06/22 07:38:21 INFO TaskSetManager: Finished task 3.0 in stage 0.0 (TID 3) in 51 ms on 10.48.2.11 (executor 1) (4/5)
20/06/22 07:38:21 INFO TaskSetManager: Finished task 4.0 in stage 0.0 (TID 4) in 37 ms on 10.48.2.11 (executor 1) (5/5)
20/06/22 07:38:21 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
20/06/22 07:38:21 INFO DAGScheduler: ResultStage 0 (reduce at SparkPi.scala:38) finished in 1.856 s
20/06/22 07:38:21 INFO DAGScheduler: Job 0 finished: reduce at SparkPi.scala:38, took 2.126785 s
Pi is roughly 3.1374222748445497
20/06/22 07:38:21 INFO SparkUI: Stopped Spark web UI at http://sp-spark-worker-0.sp-spark-headless.default.svc.cluster.local:4040
20/06/22 07:38:21 INFO StandaloneSchedulerBackend: Shutting down all executors
20/06/22 07:38:21 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
20/06/22 07:38:21 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/06/22 07:38:21 INFO MemoryStore: MemoryStore cleared
20/06/22 07:38:21 INFO BlockManager: BlockManager stopped
20/06/22 07:38:21 INFO BlockManagerMaster: BlockManagerMaster stopped
20/06/22 07:38:21 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/06/22 07:38:21 INFO SparkContext: Successfully stopped SparkContext
20/06/22 07:38:21 INFO ShutdownHookManager: Shutdown hook called
20/06/22 07:38:21 INFO ShutdownHookManager: Deleting directory /tmp/spark-b99058b1-e1fe-44f7-8928-4f230ac4a3dc
20/06/22 07:38:21 INFO ShutdownHookManager: Deleting directory /tmp/spark-c2f48cac-1c0e-4a59-acc3-076d733af103
```

we can see in the logs the result of the job launched:

```bash
20/06/22 07:38:21 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
20/06/22 07:38:21 INFO DAGScheduler: ResultStage 0 (reduce at SparkPi.scala:38) finished in 1.856 s
20/06/22 07:38:21 INFO DAGScheduler: Job 0 finished: reduce at SparkPi.scala:38, took 2.126785 s
Pi is roughly 3.1374222748445497
```

Is that happening for you as well?

**Comment by beltran-rubo** [comment]
@ankit302 please try to use "java" only as the command to execute and the job will pick it from the path. The path you specified does not exist: "/usr/lib/jvm/java-1.8-openjdk/jre/bin/java"

**Comment by ankit302** [comment]
@dani8art Can you share your github repo ??
are you running this in K8s...

still getting same error;

20/06/22 07:43:40 INFO ExternalShuffleBlockResolver: Clean up non-shuffle files associated with the finished executor 28
20/06/22 07:43:40 INFO ExternalShuffleBlockResolver: Executor is not registered (appId=app-20200622074237-0000, execId=28)
20/06/22 07:43:40 INFO Worker: Asked to launch executor app-20200622074237-0000/29 for Spark shell
20/06/22 07:43:40 INFO SecurityManager: Changing view acls to: spark
20/06/22 07:43:40 INFO SecurityManager: Changing modify acls to: spark
20/06/22 07:43:40 INFO SecurityManager: Changing view acls groups to:
20/06/22 07:43:40 INFO SecurityManager: Changing modify acls groups to:
20/06/22 07:43:40 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
20/06/22 07:43:40 INFO ExecutorRunner: Launch command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=43425" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@spark-master-6859865f8c-c4rpc:43425" "--executor-id" "29" "--hostname" "10.24.0.45" "--cores" "1" "--app-id" "app-20200622074237-0000" "--worker-url" "spark://Worker@10.24.0.45:33451"
20/06/22 07:43:42 INFO Worker: Executor app-20200622074237-0000/29 finished with state EXITED message Command exited with code 1 exitStatus 1
20/06/22 07:43:42 INFO ExternalShuffleBlockResolver: Clean up non-shuffle files associated with the finished executor 29
20/06/22 07:43:42 INFO ExternalShuffleBlockResolver: Executor is not registered (appId=app-20200622074237-0000, execId=29)
20/06/22 07:43:42 INFO Worker: Asked to launch executor app-20200622074237-0000/30 for Spark shell
20/06/22 07:43:42 INFO SecurityManager: Changing view acls to: spark
20/06/22 07:43:42 INFO SecurityManager: Changing modify acls to: spark
20/06/22 07:43:42 INFO SecurityManager: Changing view acls groups to:
20/06/22 07:43:42 INFO SecurityManager: Changing modify acls groups to:
20/06/22 07:43:42 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
20/06/22 07:43:42 INFO ExecutorRunner: Launch command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=43425" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@spark-master-6859865f8c-c4rpc:43425" "--executor-id" "30" "--hostname" "10.24.0.45" "--cores" "1" "--app-id" "app-20200622074237-0000" "--worker-url" "spark://Worker@10.24.0.45:33451"
20/06/22 07:43:44 INFO Worker: Executor app-20200622074237-0000/30 finished with state EXITED message Command exited with code 1 exitStatus 1

**Comment by dani8art** [comment]
Hi @ankit302 I've noticed you are using other different images than the `bitnami` ones, is it right? I can see in the logs `image: registry.apps.aXXXXXXXXXX/spark-master:2.4.4-hadoop2.7 `. Our Chart `bitnami/spark` is ready to be launched with `bitnami/spark` image only, we can not guarantee that it would work with other non-bitnami images. 

If you really want to try our chart I would recommend you to follow the steps:
- docs https://github.com/bitnami/charts/tree/master/bitnami/spark
- tutorials https://docs.bitnami.com/kubernetes/infrastructure/spark/

**Comment by samsonarita** [comment]
For "spark.driver.host", you need to use the pod IP in your request rather than the hostname. spark seems not to be working well with the hostname. This worked for me:

e.g.

`'spark.driver.host', '10.244.0.131'`
