### ISSUE TITLE
[bitnami/postgresql] Adhere to Helm label best practices

### ISSUE THREAD

**Issue by denniseffing** [bitnami/charts#2889]
**Which chart**: postgresql (chart version 8.10.6)

**Is your feature request related to a problem? Please describe.**
We use the service mesh Istio in combination with a Kiali deployment to visualize our mesh. 
Kiali utilizes labels to group deployed resources into "apps". By default, the label `app=` is used for this. Istio v1.5 and Kiali v1.15 changed the default app label from `app=` to `app.kubernetes.io/name=`, following the [Helm label best practices](https://helm.sh/docs/chart_best_practices/labels/). We therefore replaced every `app=` label with a corresponding `app.kubernetes.io/name=` label. 

The Bitnami postgresql chart does not provide a way to add an additional label to all generated resources (only master and slave pods & statefulsets) which is why we are not able to migrate our postgresql deployments to the new app labeling scheme. 

This results in an inconsistent service mesh visualization because postgres deployments are not grouped into their corresponding apps.

**Describe the solution you'd like**
Change the labels `app=`, `chart=`, `release=` and `heritage=` to their new counterparts according to the [Helm label best practices](https://helm.sh/docs/chart_best_practices/labels/).

**Describe alternatives you've considered**
Add configuration options so that we are able to add labels to _all_ resources generated by the chart simultaneously.

**Comment by joancafom** [comment]
Hey @denniseffing 

Thanks for your issue, it does sound completely reasonable to me! I can try to implement the changes in a PR or, if you are up to it, you can create a PR with the changes and our team will be more than happy to review it !

What do you think? Thanks again!

**Comment by denniseffing** [comment]
Hi @joancafom 

thank you for your feedback! I will try to open up a PR sometime this week, the week after that at the latest.

**Comment by joancafom** [comment]
That is wonderful! Do not forget to link back this issue in the PR.

Thanks!

**Comment by denniseffing** [comment]
Hi @joancafom, I opened up a PR that replaces the labels.

**Comment by joancafom** [comment]
Thanks so much for your contribution! One of our team of engineers will review it soon and provide with feedback 🚀
