### ISSUE TITLE
[bitnami/redis] openssl not found in redis chart

### ISSUE THREAD

**Issue by figpom-solutions** [bitnami/charts#28901]
### Name and Version

bitnami/redis 20.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install the chart with sentinel enabled
2.  error occured in sentinel pod: /opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 57: openssl: command not found
3. the pod fails (crashloopbackoff)

### Are you using any custom parameters or values?
```
sentinel.enabled: true
persistence.enabled: false
persistentVolumeClaimRetentionPolicy.enabled: false
```
### What is the expected behavior?

the chart should work and pods deploying without errors.

### What do you see instead?

error occured in sentinel pod: /opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 57: openssl: command not found

### Additional information

in fact, when I launch the sentinel container manually, openssl binary is not present.

**Comment by juan131** [comment]
Hi @figpom-solutions 

We just released a new container version that should fix this issue, see:

- https://github.com/bitnami/containers/pull/71069

Could you please give it a try using the `7.2.5-debian-12-r5` container image tag?
