### ISSUE TITLE
[bitnami/postgresql] Add support for setting custom podantiaffinity (or alternative)

### ISSUE THREAD

**Issue by dpkirchner** [bitnami/charts#28916]
### Name and Version

bitnami/postgresql 15.5.17

### What is the problem this feature will solve?

This would allow sysadmins to configure k8s to schedule primary and read replicas on different nodes. Currently, primaries and read replicas may be scheduled on the same node because the antiaffinity directives are too specific.

### What is the feature you are proposing to solve the problem?

I think the easiest solution would be to remove `"component" "primary"` from https://github.com/bitnami/charts/blob/ea7247a9eae7026f6385e6ad4ac4609cef72ec1a/bitnami/postgresql/templates/primary/statefulset.yaml#L61 and `"component" "read"` from https://github.com/bitnami/charts/blob/ea7247a9eae7026f6385e6ad4ac4609cef72ec1a/bitnami/postgresql/templates/read/statefulset.yaml#L59. Alternatively or additionally, allowing admins to specify their own rules could be helpful.

### What alternatives have you considered?

I'm not sure there are any good alternatives given the `component` label use is hardcoded. I did consider using `podLabels` to set custom labels, however they appear to be overridden in `_affinities.tpl`; custom labels are added to the template before "fixed" labels, including `component`.

**Comment by javsalgar** [comment]
Hi!

Did you try using the `affinity` value? This allows you to set fully custom affinity settings.

**Comment by dpkirchner** [comment]
Huh. That was the first thing I tried but it didn't work, so I dug in and found the preset stuff. I just tried `affinity` again and it works fine. Thx!
