### ISSUE TITLE
tls.extraDnsNames is wrongly documented in values.yaml

### ISSUE THREAD

**Issue by busyboy77** [bitnami/charts#28933]
### Name and Version

bitnami/mongodb:15.6.19

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In mongoDB helm charts AFAIK from historical point, the below given information is incorrect and should be updated to represent correct format.

```YAML
tls:
  ## e.g:
  ## extraDnsNames
  ##   "DNS.6": "$my_host"
  ##   "DNS.7": "$test"
  ##
  extraDnsNames: []
```

Adding `extraDnsNames` as suggested in the comments results in an invalid `openssl.conf` file

```YAML
  ## e.g:
  ## extraDnsNames
  ##   "DNS.6": "$my_host"
  ##   "DNS.7": "$test"
  ##
  extraDnsNames: 
       "DNS.6" : "mongo"
       "DNS.7": "performance.problem.my.cluster.local"

```

Added `cat -n /certs/openssl.cnf` at line number 99 to view the contents of the `openssl.conf` file in `templates/common-scripts-cm.yaml`

this results in something like below 

```
root@devops218:~/mongodb# helm upgrade --install --namespace er --create-namespace --values ./values.yaml mongo .
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
Release "mongo" does not exist. Installing it now.
Error: template: mongodb/templates/standalone/dep-sts.yaml:130:31: executing "mongodb/templates/standalone/dep-sts.yaml" at <concat .Values.tls.extraDnsNames .Values.externalAccess.service.publicNames>: error calling concat: Cannot concat type map as list
root@devops218:~/mongodb#
```

However this works when we change it something like below:

```YAML
tls:
  ## e.g:
  ## extraDnsNames
  ##   "DNS.6": "$my_host"
  ##   "DNS.7": "$test"
  ##
  extraDnsNames:
         - "mongo.mongo"
         - "performance.problem.my.cluster.local"

```

Please update the docs to include 
* add @param tls.extraDnsNames tag to be supported by helm readme generator.
* correct format for the tag itself. 
** Incorrect 
```YAML
  ## extraDnsNames
  ##   "DNS.6": "$my_host"
  ##   "DNS.7": "$test"
  ##
```
* Correct format is 
```YAML
  ## extraDnsNames:
  ##   - "custom-name-1"
  ##   - "custom-name-2"
```

* add the proper tag 
```YAML
## @param tls.extraDnsNames [defaut: Empty] Add Extra names to auto-genarated TLS Certs. ( Only when auto-generated is set to true )
```

### What do you see instead?

Updated

**Comment by busyboy77** [comment]
This results in `openssl.conf` like below

```
root@devops218:~/mongodb# k -n er logs -f mongo-mongodb-0 -c generate-tls-certs
     1  [req]
     2  req_extensions = v3_req
     3  distinguished_name = req_distinguished_name
     4  [req_distinguished_name]
     5  [ v3_req ]
     6  basicConstraints = CA:FALSE
     7  keyUsage = nonRepudiation, digitalSignature, keyEncipherment
     8  subjectAltName = @alt_names
     9  [alt_names]
    10  DNS.1 = mongo-mongodb
    11  DNS.2 = mongo-mongodb-0
    12  DNS.3 = mongo-mongodb.er.svc.cluster.local
    13  DNS.5 = mongo.mongo
    14  DNS.6 = performance.problem.my.cluster.local
Certificate request self-signature ok
subject=C = US, O = My Organisations, OU = IT, CN = mongo-mongodb-0
root@devops218:~/mongodb#

```

Although another bug is appeared now , the DNS.4 is not present , because the loops starts from DNS.5 .

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
