### ISSUE TITLE
[bitnami/etcd] Etcd cronjob etcd-snapshotter is invalid

### ISSUE THREAD

**Issue by grootTwig** [bitnami/charts#28949]
### Name and Version

bitnami/etcd:10.2.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm  install etcd bitnami/etcd   --set persistence.enabled=true --set disasterRecovery.enabled=true --set metrics.enabled=true --set replicaCount=3 --set volumePermissions.enabled=true

### What is the expected behavior?

installed successfully

### What do you see instead?

error:
Error: INSTALLATION FAILED: 1 error occurred:
	* CronJob.batch "etcd-snapshotter" is invalid: spec.jobTemplate.spec.template.spec.initContainers[0].volumeMounts[1].name: Not found: "tmp-dir"

### Additional information

I've noticed that the chart gets no definition of volume named tmp-dir but empty-dir instead
![image](https://github.com/user-attachments/assets/63b2d867-4f0f-4a01-908d-521c09c56e47)

![image](https://github.com/user-attachments/assets/149e37f1-a3d3-494d-917b-4c32a0d33dfe)

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. As you spotted the issue, would you like to submit a PR fixing the volume name?
