### ISSUE TITLE
[bitnami/airflow] load dags initcontainer does not have resources section

### ISSUE THREAD

**Issue by bbakker2** [bitnami/charts#28952]
### Name and Version

bitnami/airflow 19.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. for a cluster that mandates all containers have resources declared
2. deploy bitnami/airflow with dags.existingConfigmap defined
3. the cluster rejects the deployment of scheduler, web and worker because initContainer 'load-dags' does not declare resources

### Are you using any custom parameters or values?

dags.existingConfigmap=xxx

### What is the expected behavior?

succesfull deployment

### What do you see instead?

Getting error
``` 
Error from server (Forbidden): error when creating "xxxxx": admission webhook "validation.gatekeeper.sh" denied the request: [container-must-have-limits-and-requests] container <load-dags> does not have <{"cpu", "memory"}> limits defined
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
