### ISSUE TITLE
[bitnami/redis-cluster] Allow to do Helm Upgrade without the  `--set password=$REDIS_PASSWORD`

### ISSUE THREAD

**Issue by Praveen-98cs** [bitnami/charts#28963]
### Name and Version

bitnami/redi-cluster latest

### What is the problem this feature will solve?

Allow redis-cluster chart to do helm upgrade without requiring the `--set password=$REDIS_PASSWORD` parameter.

### What is the feature you are proposing to solve the problem?

If there is an flux built in system to reconcile and upgrade helm chart of redis-cluster, this `--set password=$REDIS_PASSWORD` parameter is a blocker as it is not possible to provide this parameter. 

Will it be possible to allow to do helm upgrade without requiring the `$REDIS_PASSWORD`?

**Comment by javsalgar** [comment]
Hi!

Thank you for reporting! It could be done using a similar logic to the one in clickhouse https://github.com/bitnami/charts/blob/d7a6e363b0919f2bfa4c073a9cfc349b529de1a9/bitnami/clickhouse/templates/secret.yaml#L19

Using the `common.secrets.password.manage` helper could work for this. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. However, if you want to speed up the process, you can submit a PR and the team will check it .

**Comment by Praveen-98cs** [comment]
Thank you! will look into this!
