### ISSUE TITLE
[bitnami/mlflow] Allow setting resources for default init containers

### ISSUE THREAD

**Issue by ander-db** [bitnami/charts#28978]
### Name and Version

bitnami/mlflow 1.4.22

### What architecture are you using?

None

### What steps will reproduce the bug?

**Description**:
In Kubernetes clusters with resource quotas enabled (requiring CPU and RAM specifications for all containers), the default init containers in the MLflow Helm chart fail to deploy. This is because these containers do not have resource specifications, which are required in such environments.

**Steps to reproduce**:
1. Set up a Kubernetes cluster with resource quotas enabled.
2. Attempt to deploy MLflow using the Bitnami Helm chart with default settings.
3. Observe that the deployment fails due to resource specification requirements for init containers.

**Current behavior**:
The deployment fails because the default init containers do not have CPU and RAM specifications, which are required by the cluster's resource quota policy.

**Workaround**:
The only workaround I've found is to:

1. Attempt the deployment and let it fail.
2. Inspect the failed configuration to identify all default init containers.
3. Set enableDefaultInitContainers: false in the Helm values.
4. Manually redefine all init containers with appropriate resource specifications.

### What is the expected behavior?

The chart should include a 'resources' section for default init containers in Helm values, similar to other containers in the chart, allowing customization without disabling them.

### What do you see instead?

When attempting to deploy the MLflow chart in a cluster with resource quotas:

- The deployment fails with error messages similar to:
`Error creating: pods "mlflow-tracking-xxxxxxxxx-xxxx" is forbidden: failed quota: kf-resource-quota: must specify cpu for: copy-certs,get-default-auth-conf,render-auth-conf,upgrade-db-auth,wait-for-database,wait-for-s3; memory for: copy-certs,get-default-auth-conf,render-auth-conf,upgrade-db-auth,wait-for-database,wait-for-s3
`

### Additional information
Is there a plan to address this issue in future releases of the chart? Perhaps by allowing resource specifications for default init containers without requiring them to be completely redefined?

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I will forward it to the team but we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding support for these resources and the team will check it.
