### ISSUE TITLE
[MongoDB] Unable to set replicas max count

### ISSUE THREAD

**Issue by rg2609** [bitnami/charts#2898]
**Which chart**:
bitnami/mongodb

**Describe the bug**
I am trying to set the replica set true and setting the `replicaSet.pdb.maxUnavailable.secondary` and `replicaSet.pdb.maxUnavailable.arbiter` but unable to start the chart. And when I am using the `values-production.yaml` same error I am getting.

**Error Output**
```bash
Error: PodDisruptionBudget.policy "mongodb-arbiter" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc0095309e0), Selector:(*v1.LabelSelector)(0xc009530a00), MaxUnavailable:(*intstr.IntOrString)(0xc0095309c0)}: minAvailable and maxUnavailable cannot be both set
```
I am don't know, that I am missing something or what. I just wanted the MongoDB should work with horizontal scaling. Is this chat has HPA?

**Comment by joancafom** [comment]
Hi @rg2609 

Are you setting those values by editing `values-production.yaml` ? If so, you must ensure to comment out the lines referring to `minAvailable`. According to he official Kubernetes [documentation](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget), only one of `maxUnavailable` or `minAvailable` can be specified in a single PDB:

> You can specify only one of maxUnavailable and minAvailable in a single PodDisruptionBudget. maxUnavailable can only be used to control the eviction of pods that have an associated controller managing them...

Regarding support for HPA the answer is that this Chart does not come along with this feature by default, but you can implement it (and contribute with a PR if you like).

Hope it helps, thanks!

**Comment by rg2609** [comment]
Thank you @joancafom,
Appreciate for your help :+1: , I thought that it should have min and max both. I will try to create HPA feature and create PR for the same

**Comment by joancafom** [comment]
That is awesome! Do not hesitate to create any other issues and contact us back!
