### ISSUE TITLE
Using sprig functions in templates

### ISSUE THREAD

**Issue by technosophos** [bitnami/charts#29]
I am super excited to see this repository!

Have you guys looked at the [Sprig](https://github.com/Masterminds/sprig) functions that are exposed to the template engine? I was looking at the RedMine chart, and thinking it might make sense to do something like `{{ default 22 .smtpPort}}` or things like that.

I think Helm might be a version or so back from the Sprig head. But most of the functions are the same between versions.

Thanks!

**Comment by prydonius** [comment]
Hey @technosophos :smiley: 

Awesome - didn't realise those functions were available in Helm. Do you think it would be better to put defaults in [redmine/tpl/values.toml](https://github.com/bitnami/charts/blob/master/redmine/tpl/values.toml), as this is where someone would change the default values?

Another idea we were discussing was if we could grab environment variables using `{{ env "SMTP_PORT" }}` to provide a similar interface as the container, though interpolating environment vars from your machine might be strange.

**Comment by sameersbn** [comment]
@technosophos @prydonius  we started out along the same lines, i.e. `{{ default 587 .smtpPort}}`. Later we decided that it makes sense that the underlying container picks the default values when not specified. That way if the defaults are changed in [bitnami/redmine](https://github.com/bitnami/bitnami-docker-redmine/) image, we won't have to update anything here. Documentation wise, the user should be able to cross reference the docker image and chart docs and find no ambiguity

We should use the `quote` sprig function though.

**Comment by prydonius** [comment]
@sameersbn oh, you're right.

We should maybe consider rethinking that. I'm actually not too worried about having to update the charts if defaults change, since I don't imagine that happening very often. By having the defaults in the charts, it'll be easier for people to find out what they are.

I know we decided to remove the possible options and their defaults from the README and point to the image documentation instead, but it might make sense to add them to the template or values.

**Comment by sameersbn** [comment]
In that case IMO `values.toml` may be the apt location to specify the default values cause it will have more hits from users.

**Comment by technosophos** [comment]
Good points. I've also done the {{env}} thing here and there, but it feels a little scary sometimes because it requires the user to set things that are outside of the scope of the template.

For the most part, I think @sameersbn's reasoning is sound: the `values.toml` file makes the most sense as the location for defaults. I always go back and forth about whether values ought to be as "required" as possible (values must be set in the TOML file) or as "optional" as possible (there are defaults for everything). My tendency is to lean toward optional, but perhaps leaning the other way actually makes for the most consistent user experience.

Thanks again!

**Comment by prydonius** [comment]
Thanks again for your feedback @technosophos, this has been implemented with #30 and #33 :smile:
