### ISSUE TITLE
[bitnami/mariadb] Readiness probe failed: mysqladmin: Deprecated program name

### ISSUE THREAD

**Issue by Infinoid** [bitnami/charts#29016]
### Name and Version

mariadb-19.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy current version of helm release
2. wait for it to come up
3. check `kubectl get events` or `kubectl describe pod/mariadb-0`
4. see unhealthy readiness probe messages

### Are you using any custom parameters or values?

* initdbScriptsConfigMap = "mariadb-initscripts" (this contains 2 .sql files)
* global.defaultStorageClass = "rbd"

### What is the expected behavior?

Readiness probe succeeds.

### What do you see instead?

```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Created                 15m                kubelet                  Created container mariadb
  Normal   Started                 15m                kubelet                  Started container mariadb
  Warning  Unhealthy               13m (x9 over 14m)  kubelet                  Readiness probe failed: mysqladmin: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mariadb/bin/mariadb-admin' instead
```

### Additional information

Similar messages appear in #19215 and #18642, as warnings alongside another error.  Those issues solved the other errors but ignored the warning.

The most recent comment in #19215 provides some syntax to disable the probes entirely.  But I think it would be better to fix the probes, rather than disabling them.

**Comment by Infinoid** [comment]
Note that my mariadb seems to be working.  I am able to `exec` into the container and connect using the `mariadb` CLI and `$MARIADB_ROOT_PASSWORD`.  The issue is simply that the readiness probe uses a deprecated program name.

This will eventually break, and in the meantime, it looks ugly in the logs, and gets in the way of other errors when they occur.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I will forward it to the team, but as it is not a critical feature (yet) we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR replacing mysqladmin with mariadb-admin?
