### ISSUE TITLE
[bitnami/rabbitmq] RabbitMq (non cluster-operator) is not starting on Rancher

### ISSUE THREAD

**Issue by adaumann** [bitnami/charts#29019]
### Name and Version

bitnami/rabbitmq 14.6.7

### What architecture are you using?

None

### What steps will reproduce the bug?

Environment: Rancher installation V2.8.3

Description: I using the bitnami/rabbitmq charts (NON clustered) to deploy to Rancher Kubernetes, The pod gives not valuable log information, and after a few minutes I receive:
```
rabbitmq 07:16:10.01 ERROR ==> Couldn't start RabbitMQ in background.
```
I tried to set the loglevel to "debug", but no other information. On MicroKubernetes the same configuration works. 

I tried to disable persistency, no effect. I added the replicas, no effect.
```
rabbitmq 07:57:33.43 INFO  ==> 
2024-08-26T07:57:33.440101577Z rabbitmq 07:57:33.43 INFO  ==> Welcome to the Bitnami rabbitmq container
rabbitmq 07:57:33.44 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 07:57:33.44 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
2024-08-26T07:57:33.457940356Z rabbitmq 07:57:33.45 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
rabbitmq 07:57:33.45 INFO  ==> 
2024-08-26T07:57:33.516922120Z rabbitmq 07:57:33.51 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 07:57:33.61 INFO  ==> Validating settings in RABBITMQ_* env vars..
2024-08-26T07:57:33.710261983Z rabbitmq 07:57:33.70 INFO  ==> Initializing RabbitMQ...
rabbitmq 07:57:33.83 INFO  ==> Starting RabbitMQ in background...
rabbitmq RROR ==> Couldn't start RabbitMQ in background.
```
The configuration has been set to default, no effect

### Are you using any custom parameters or values?
```yaml
rabbitmq:
  persistence:
    enabled: false
```
### What is the expected behavior?

The server should start normally

### What do you see instead?
```
rabbitmq 07:16:10.01 ERROR ==> Couldn't start RabbitMQ in the background.
```
No debug information

### Additional information

Tried to activate Debug output, but no additional info:
```yaml
  logs: false
  extraConfiguration: |
    log.default.level = debug
    log.file = false
    log.console = true
    log.console.level = debug
    log.console.formatter = json      
```

**Comment by javsalgar** [comment]
Hi,

I see a "Killed" error, which is normally related to memory consumption. Could you try increasing the memory limits in the values.yaml file?

**Comment by adaumann** [comment]
I can confirm that this was a memory problem, by setting the following:

memoryHighWatermark.enabled="true"
memoryHighWatermark.type="relative"
memoryHighWatermark.value="0.4"
resources.limits.memory="2Gi"

it works. Please close the issue

**Comment by adaumann** [comment]
Closed
