### ISSUE TITLE
[bitnami/zookeeper] ENV for seperate dataLogDir

### ISSUE THREAD

**Issue by jonathan-m-foley** [bitnami/charts#2902]
**Which chart**:
bitnami/zookeeper (5.17.0)

**Is your feature request related to a problem? Please describe.**
Zookeeper's Administrator Guide recommends storing the data and transaction logs on separate storage devices for performance. This is accomplished by specifying the dataDir and dataLogDir properties, respectively, in the zoo.conf file. Unfortunately, I do not see any support for changing these values directly via the bitnami helm chart. The only apparent recourse is to replace the configuration file by specifying the entire configuration in .Values.config. 

In addition to configuring the properties, the StatefulSet's VolumeClaimTemplates do not permit arbitrary volume claims to be specified which prevents setting up a separate dataLogDir device via the helm chart.

**Describe the solution you'd like**
It would be very helpful if there were variables that could be set via Values.yaml corresponding directly to zoo.conf's dataDir and dataLogDir.  Also, adding a conditionally rendered block into the StatefulSet's VolumeClaimTemplates section to match the dataLogDir would be a welcome addition so that the user has the option to set up a cluster per Zookeeper's recommendations without additional tooling or forking the helm chart and potentially the bitnami docker image for zookeeper as well.

**Describe alternatives you've considered**
I have used kustomize to patch in an additional PVC in the VolumeClaimTemplates section of the StatefulSet matching my dataLogDir. I then used the Values.extraVolumeMounts to mount it at the dataLogDir location.

I have also copied the zoo.conf file out of /opt/bitnami/zookeeper/conf from a running, working bitnami/zookeeper container. I then copied the content of the zoo.conf into the values.yaml under the .Values.config key. The only change I made to the contents was to add the dataLogDir=/path/to/my/extra/mount k,v pair to the conf. Unfortunately, this caused the following exception to show up dozens of times per second in my zookoeeper logs ad infinitum:

```
2020-06-22 21:34:17,460 [myid:1] - WARN  [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /10.1.0.1:38974, session = 0x0
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-22 21:34:17,829 [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /10.1.0.1:38978, session = 0x0
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I suspect this has to do with the way the docker image's shell scripts mutate the configuration on startup as it is quite tricky to follow but I don't know for sure yet. 

**Additional context**
N/A

**Comment by jonathan-m-foley** [comment]
Regarding my comments in the "Describe alternatives you've considered section", I believe the problem I ran into there is owing to the fact that the the zookeeper_generate_conf() function in libzookeeper.sh only runs if no user configuration file is specified, effectively requiring the chart user to set the server.x properties statically in their supplied Values.config.

**Comment by juan131** [comment]
Hi @jonathan-m-foley 

Thanks so much for this great feedback!! I agree with you, we should explore a way to use two separate volumes as recommended for production environments: one for data, another one for logs.

I just opened an internal task to work on this feature. We will keep you updated about our progress.

**Comment by jonathan-m-foley** [comment]
Great, thank you!

**Comment by jonathan-m-foley** [comment]
Due to crunchtime on my end, my company has just given me the greenlight to fork & attempt a fix myself.  I should be able to post a PR within 2 weeks. This would involve small PRs both for the chart and the associated docker image.

Implementation Plan:
- Add value to zookeeper chart’s values.yaml corresponding to the zoo.conf’s dataLogDir property.
- Inject the new value as an ENV into the docker container.
- Add logic to set the value of dataLogDir to the zookeeper_generate_conf() function in libzookeeper.sh within the zookeeper image.

**Comment by jonathan-m-foley** [comment]
^I neglected to note that the above planis a partial fix - I had already worked around the StatefulSet's VolumeClaimTemplates not being configurable (i.e. I used kustomize to patch in additional volumee claim templates). Time permitting I would also like to update the chart to allow passing down arbitrary VolumeClaimTemplates via Values.yaml in this PR.

**Comment by juan131** [comment]
Hi @jonathan-m-foley 

Every contribution is welcomed, so please feel free to create a PR adding this feature and we'll be glad to review it. As you said both the container and the chart would need changes since we need to add the chart a way to create custom PVCs, and we need to provide a way to configure Zookeeper so it uses different directories for data & logs.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
