### ISSUE TITLE
[bitnami/redis] Automatic labelling to slave pod using redis sentinel @Kubernetes

### ISSUE THREAD

**Issue by BernardBerenes** [bitnami/charts#29039]
### Name and Version

bitnami/redis:7.4.0

### What is the problem this feature will solve?

Addressing confusion in Kubernetes service traffic routing to pod.

### What is the feature you are proposing to solve the problem?

In this case, Master (set only), Slave (get only)

We can apply a service specifically for the slaves, so the service does not need to access the Redis master pod, which would otherwise increase the load on the Redis master pod. Therefore, is there a feature that can automatically label the Redis slave pods, allowing us to create a separate service for those Redis slaves?

### What alternatives have you considered?

An alternative is using a Job, but if we use a Job that runs continuously, it will make our server heavy.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
