### ISSUE TITLE
[bitnami/grafana-mimir] Tempo Ingesters register to mimir ring and make the whole stack crash

### ISSUE THREAD

**Issue by thechaak** [bitnami/charts#29071]
### Name and Version

bitnami/grafana-mimir:latest

### What architecture are you using?

None

### What steps will reproduce the bug?

Unsure of how to reproduce this issue as it has never happened in our current deployment before.

### Are you using any custom parameters or values?

mimir.yaml
```
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: mimir
    namespace: mimir
    chart: bitnami/grafana-mimir
    values:
      - alertmanager:
          enabled: false
          persistence:
            enabled: false
          blockStorage:
            backend: s3
            config:
              access_key_id: {{ requiredEnv "MIMIR_S3_ACCESS_KEY_ID" }}
              bucket_name: {{ requiredEnv "MIMIR_S3_BUCKET" }}
              endpoint: 'kao-ecs-01-dtn.dstcorp.net:9020'
              insecure: true
              secret_access_key: {{ requiredEnv "MIMIR_RULER_S3_SECRET_ACCESS_KEY" }}
      - compactor:
          resources:
            requests:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 200Mi
            limits:
              memory: 10Gi
              cpu: 4
              ephemeral-storage: 10Gi
          persistence:
            enabled: false
          extraArgs:
            - -compactor.compaction-concurrency=4
            - -compactor.compactor-tenant-shard-size=2
          replicaCount: 5
      - distributor:
          replicaCount: 15
          resources:
            requests:
              memory: 1.5Gi
              cpu: 150m
              ephemeral-storage: 500Mi
            limits:
              memory: 2.5Gi
              cpu: 450m
              ephemeral-storage: 1Gi
          readinessProbe:
            timeoutSeconds: 50
      - querier:
          resources:
            requests:
              memory: 100Mi
              cpu: 150m
              ephemeral-storage: 200Mi
            limits:
              memory: 1.5Gi
              cpu: 150m
              ephemeral-storage: 1Gi
          replicaCount: 3
      - queryFrontend:
          resources:
            requests:
              memory: 100Mi
              cpu: 150m
              ephemeral-storage: 200Mi
            limits:
              memory: 192Mi
              cpu: 150m
              ephemeral-storage: 1Gi
          replicaCount: 3
      - queryScheduler:
          resources:
            requests:
              memory: 100Mi
              cpu: 150m
              ephemeral-storage: 200Mi
            limits:
              memory: 1.5Gi
              cpu: 150m
              ephemeral-storage: 1Gi
          enabled: true
          replicaCount: 3
      - ruler:
          enabled: true
          persistence:
            enabled: false

          extraArgs:
            - -ruler.alertmanager-url=http://alertmanager.alertmanager.svc.cluster.local:9093/
            - -ruler.rule-path=/bitnami/grafana-mimir/ruler
            - -ruler.enable-api=true
          blockStorage:
            backend: s3
            config:
              access_key_id: {{ requiredEnv "MIMIR_RULER_S3_ACCESS_KEY_ID" }}
              bucket_name: {{ requiredEnv "MIMIR_RULER_S3_BUCKET" }}
              endpoint: 'xxx.xxx.net:9020'
              insecure: true
              secret_access_key: {{ requiredEnv "MIMIR_RULER_S3_SECRET_ACCESS_KEY" }}
      - storeGateway:
          resources:
            requests:
              memory: 100Mi
              cpu: 150m
              ephemeral-storage: 1Gi
            limits:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 32Gi
          persistence:
            enabled: false
          replicaCount: 5
      - ingester:
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 200Mi
            limits:
              memory: 8Gi
              cpu: 2
              ephemeral-storage: 1Gi
          readinessProbe:
            timeoutSeconds: 50
          replicaCount: 8
          persistence:
            enabled: true
            storageClass: longhorn
            accessModes: ["ReadWriteMany"]
            size: 8Gi
      - minio:
          enabled: false
      - gateway:
          resources:
            requests:
              memory: 100Mi
              cpu: 150m
              ephemeral-storage: 200Mi
            limits:
              memory: 192Mi
              cpu: 150m
              ephemeral-storage: 1Gi
          replicaCount: 8
          service:
            type: NodePort
            nodePorts:
              http: 30080
      - metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
            labels:
              release: k8smon
      - mimir:
          blockStorage:
            backend: s3
            config:
              access_key_id: {{ requiredEnv "MIMIR_S3_ACCESS_KEY_ID" }}
              bucket_name: {{ requiredEnv "MIMIR_S3_BUCKET" }}
              endpoint: 'xxx.xxx.net:9020'
              insecure: true
              secret_access_key: {{ requiredEnv "MIMIR_S3_SECRET_ACCESS_KEY" }}
          overrideConfiguration:
            frontend:
              max_outstanding_per_tenant: 1000
            limits:
              max_global_series_per_user: 5000000
              max_cache_freshness: 10m
              max_query_parallelism: 240
              max_total_query_length: 12000h
              creation_grace_period: 90m
              ingestion_rate: 100000
              ingestion_burst_size: 1000000
              ruler_max_rules_per_rule_group: 100
            usage_stats:
              enabled: false

Tempo.yaml:

---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: tempo
    namespace: tempo
    chart: bitnami/grafana-tempo
    values:
      - tempo:
          overrideConfiguration:
            multitenancy_enabled: true
            server:
              http_listen_port: 8080
            storage:
              trace:
                backend: s3
              s3:
                endpoint: "xxx.xxx.net:9021"
                insecure: false
                bucket: {{ requiredEnv "TEMPO_S3_BUCKET" }}
                access_key: {{ requiredEnv "TEMPO_S3_ACCESS_KEY_ID" }}
                secret_key: {{ requiredEnv "TEMPO_S3_SECRET_ACCESS_KEY" }}
            metrics_generator:
              processor:
                service_graphs:
                  
          traces:
            otlp:
              http: true
              grpc: true
            zipkin: true
            jaeger:
              thriftHttp: true
      - compactor:
          enabled: true
      - ingester:
          replicaCount: 0
          persistence:
            enabled: false
      - querier:
          replicaCount: 0
      - distributor:
          service:
            type: NodePort
            nodePorts:
              http: '30003'
              grpc: '30004'
      - metricsGenerator:
          remoteWrite:
            - url: http://mimir-grafana-mimir-gateway.mimir/api/v1/push
```

### What is the expected behavior?

tempo ingesters should register to tempo and mimir ingesters should register to mimir.

### What do you see instead?

Tempo Ingesters registerd to mimir ingester ring which caused the stack to go down and stop returning logs.

### Additional information

There is a same issue in loki-distributed: https://github.com/grafana/tempo/issues/2766
for which the solution is using cluster_labels

But for bitnami charts, the cluster_labels property is not there.
How to solve this issue?

**Comment by javsalgar** [comment]
Hi,

Does the field `loki.overrideConfiguration` work for this case?

**Comment by thechaak** [comment]
Hi @javsalgar 
I have been waiting for your reply.
Yes, I have already tried overrideConfiguration, its saying the cluster_label value is unknown.

**Comment by javsalgar** [comment]
Hi,

That seems to be an issue in the Loki configuration itself, could you share the generated config map in the upstream ticket above? They may let you know where exactly the cluster_label value should look like

**Comment by thechaak** [comment]
This is mimir.yaml configmap

activity_tracker:
  filepath: /bitnami/grafana-mimir/activity.log
alertmanager_storage:
  backend: s3
  s3:
    access_key_id: nonprodmimir-admin
    bucket_name: nonprodmimir
    endpoint: kao-ecs-01-dtn.dstcorp.net:9020
    insecure: true
    secret_access_key: bnpurOSmwb6AKzGOZvllvn4XNNvpRy0H2btQyyWG
api:
  alertmanager_http_prefix: /alertmanager
  prometheus_http_prefix: /prometheus
blocks_storage:
  backend: s3
  bucket_store:
    chunks_cache:
      backend: memcached
      memcached:
        addresses: mimir-memcachedchunks:11211
        timeout: 450ms
    index_cache:
      backend: memcached
      memcached:
        addresses: mimir-memcachedindex:11211
        timeout: 450ms
    metadata_cache:
      backend: memcached
      memcached:
        addresses: mimir-memcachedmetadata:11211
        timeout: 450ms
    sync_dir: /bitnami/grafana-mimir/tsdb-sync
  s3:
    access_key_id: nonprodmimir-admin
    bucket_name: nonprodmimir
    endpoint: kao-ecs-01-dtn.dstcorp.net:9020
    insecure: true
    secret_access_key: X6QCoFLSWhvpaDHCCyNYTlbrJmRbh+QmcubqFsIe
  tsdb:
    dir: /bitnami/grafana-mimir/tsdb
compactor:
  data_dir: /bitnami/grafana-mimir/compactor
frontend:
  cache_results: true
  max_outstanding_per_tenant: 1000
  parallelize_shardable_queries: true
  results_cache:
    backend: memcached
    memcached:
      addresses: mimir-memcachedfrontend:11211
      timeout: 500ms
  scheduler_address: mimir-grafana-mimir-query-scheduler-headless.mimir.svc:9095
frontend_worker:
  grpc_client_config:
    max_send_msg_size: 419430400
  scheduler_address: mimir-grafana-mimir-query-scheduler-headless.mimir.svc:9095
ingester:
  ring:
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /bitnami/grafana-mimir/tokens
    unregister_on_shutdown: false
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
limits:
  creation_grace_period: 90m
  ingestion_burst_size: 1000000
  ingestion_rate: 100000
  max_cache_freshness: 10m
  max_global_series_per_user: 5000000
  max_query_parallelism: 240
  max_total_query_length: 12000h
  ruler_max_rules_per_rule_group: 100
memberlist:
  abort_if_cluster_join_fails: false
  advertise_port: 7946
  bind_port: 7946
  compression_enabled: false
  join_members:
  - dns+mimir-grafana-mimir-gossip-ring.mimir.svc.cluster.local:7946
multitenancy_enabled: true
querier:
  max_concurrent: 16
query_scheduler:
  max_outstanding_requests_per_tenant: 800
ruler:
  alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-grafana-mimir-alertmanager-headless.mimir.svc.cluster.local/alertmanager
  enable_api: true
  rule_path: /bitnami/grafana-mimir/ruler
ruler_storage:
  backend: s3
  s3:
    access_key_id: chin-hsu@nonprodmruler@gids-emea
    bucket_name: nonprodmruler
    endpoint: kao-ecs-01-dtn.dstcorp.net:9020
    insecure: true
    secret_access_key: bnpurOSmwb6AKzGOZvllvn4XNNvpRy0H2btQyyWG
server:
  grpc_listen_port: 9095
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_connection_age: 2m
  grpc_server_max_connection_age_grace: 5m
  grpc_server_max_connection_idle: 1m
  http_listen_port: 8080
store_gateway:
  sharding_ring:
    tokens_file_path: /bitnami/grafana-mimir/tokens
    wait_stability_min_duration: 1m
tenant_federation:
  enabled: true
usage_stats:
  enabled: false
  installation_mode: helm
  
  
  And this is tempo.yaml configmap:
  multitenancy_enabled: false
cache:
  caches:
    - memcached:
        host: tempo-memcached
        service: memcache
        timeout: 500ms
        consistent_hash: true
      roles:
        - bloom
        - trace-id-index
compactor:
  compaction:
    block_retention: 48h
  ring:
    kvstore:
      store: memberlist
distributor:
  ring:
    kvstore:
      store: memberlist
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
    zipkin:
      endpoint: 0.0.0.0:9411
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
querier:
  frontend_worker:
    frontend_address: tempo-grafana-tempo-query-frontend-headless:9095
ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    tokens_file_path: /bitnami/grafana-tempo/data/tokens.json
metrics_generator:
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /bitnami/grafana-tempo/data/wal
    remote_write: 
      - url: http://mimir-grafana-mimir-gateway.mimir/api/v1/push
memberlist:
  bind_port: 7946
  abort_if_cluster_join_fails: false
  join_members:
    - tempo-grafana-tempo-gossip-ring:7946
overrides:
  per_tenant_override_config: /bitnami/grafana-tempo/conf/overrides.yaml
server:
  http_listen_port: 3200
  grpc_listen_port: 9095
storage:
  trace:
    backend: local
    blocklist_poll: 5m
    local:
      path: /bitnami/grafana-tempo/data/traces
    wal:
      path: /bitnami/grafana-tempo/data/wal
     
    And also have overrides.yaml in tempo which is empty like this:
    
    overrides: {}
    
    Does it needs to be updated?
    if yes, how to update this as I could'nt find any documentation for this.

**Comment by javsalgar** [comment]
Using the lokiOverrides configuration should do the trick, but we would need to know where exactly the `cluster_labels` section should go inside the loki configuration, this is something that needs to be specified by the upstream devs.

**Comment by thechaak** [comment]
Can you tell me where I need to specify the cluster_labels in loki for tempo and mimir.

this is my loki.yaml 

---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: loki
    namespace: loki
    chart: bitnami/grafana-loki
    values:
      - metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: monitoring
            labels:
              release: k8smon
      - loki:
          overrideConfiguration:
            chunk_store_config:
              chunk_cache_config:
                background:
                  writeback_buffer: 5000000
                  writeback_size_limit: 1000MB
                memcached:
                  batch_size: 100
                  parallelism: 100
                memcached_client:
                  addresses: dns+loki-memcachedchunks:11211
                  consistent_hash: true
            limits_config:
              max_global_streams_per_user: 100000
              max_streams_per_user: 100000000
              per_stream_rate_limit: 1024M
              per_stream_rate_limit_burst: 2048M
              ingestion_burst_size_mb: 2000
              ingestion_rate_mb: 20000
              allow_structured_metadata: false
              max_cache_freshness_per_query: 10m
              reject_old_samples: true
              reject_old_samples_max_age: 168h
              retention_period: 336h
              split_queries_by_interval: 15m
            schema_config:
              configs:
                - from: "2020-10-24"
                  index:
                    period: 24h
                    prefix: index_
                  object_store: aws
                  schema: v11
                  store: boltdb-shipper
            server:
              http_listen_port: 3100
            storage_config:
              aws:
                endpoint: "https://xxx.net:9021"
                insecure: false
                s3forcepathstyle: true
                bucketnames: {{ requiredEnv "LOKI_S3_BUCKET" }}
                access_key_id: {{ requiredEnv "LOKI_S3_ACCESS_KEY_ID" }}
                secret_access_key: {{ requiredEnv "LOKI_S3_SECRET_ACCESS_KEY" }}
              # index_gateway_client:
              #     server_address: dns:///loki-distributed-index-gateway:9095
              boltdb_shipper:
                active_index_directory: /bitnami/grafana-loki/loki/index
                cache_location: /bitnami/grafana-loki/loki/cache
                # index_gateway_client:
                #   server_address: dns:///loki-distributed-index-gateway:9095
              #  shared_store: aws
                
      - compactor:
          enabled: true
          persistence:
            enabled: false
      - gateway:
          enabled: true
          replicaCount: 3
      - indexGateway:
          replicaCount: 3
          service:
            nodePorts:
              http: 31000
              grpc: 31002
      - distributor:
          replicaCount: 3
          service:
            type: NodePort
            nodePorts:
              http: 30000
              grpc: 30001
      - ingester:
          replicaCount: 7
          persistence:
            enabled: false
          extraArgs:
            - -ingester.autoforget-unhealthy=true
          resources:
            requests:
               memory: 512Mi
               cpu: 500m
               ephemeral-storage: 200Mi
            limits:
               memory: 1Gi
               cpu: 2
               ephemeral-storage: 1Gi
      - querier:
          replicaCount: 3
          persistence:
            enabled: false
          resources:
            requests:
               memory: 256Mi
               cpu: 250m
               ephemeral-storage: 200Mi
            limits:
               memory: 512Mi
               cpu: 500m
               ephemeral-storage: 1Gi
      - queryFrontend:
          replicaCount: 1
          resources:
            requests:
               memory: 256Mi
               cpu: 250m
               ephemeral-storage: 200Mi
            limits:
               memory: 512Mi
               cpu: 500m
               ephemeral-storage: 1Gi
      - queryScheduler:
          replicaCount: 3
      - ruler:
          enabled: true
          persistence:
            enabled: false
            storageClass: longhorn
            accessModes: ["ReadWriteMany"]
            size: 8Gi
          replicaCount: 0
          extraArgs:
            - -ruler.alertmanager-url=http://alertmanager.alertmanager.svc.cluster.local:9093/
        #    - -ruler.rule-path=/bitnami/grafana-loki/ruler
            - -ruler.enable-api=true
      - tableManager:
          replicaCount: 3
      - promtail:
          enabled: false
          
 Any help would be grateful

**Comment by javsalgar** [comment]
In the `overrideConfiguration` section, you would set

```
overrideConfiguration:
  memberlist:
    cluster_label: YOUR_VALUE_HERE
```
