### ISSUE TITLE
helm install error

### ISSUE THREAD

**Issue by Patientrookie** [bitnami/charts#29076]
### Name and Version

bitnami/mariadb

### What architecture are you using?

None

### What steps will reproduce the bug?
```
helm install mariadb --set auth.rootPassword=secretpassword,auth.database=baetyl_cloud bitnami/mariadb
```
then
```
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: the server could not find the requested resource
```

### What do you see instead?

![probem](https://github.com/user-attachments/assets/93524ca9-3341-42fd-9d9c-3db4e2724c8f)

**Comment by Patientrookie** [comment]
macos cannot execute the exe program

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
