### ISSUE TITLE
Mysql Error in SELECT 1, using Azure Mysql

### ISSUE THREAD

**Issue by ivmos** [bitnami/charts#29087]
### Name and Version

bitnami/wordpress 23.1.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm trying to update from chart 22.4.20 to chart version 23.1.9. No values/config changed.

I'm having crash loop in POD with the error:
```
wordpress 13:06:23.39 DEBUG ==> Executing SQL command:
SELECT 1
/opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
ERROR 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.
wordpress 13:07:18.88 ERROR ==> Could not connect to the database
```

Thanks in advance

### Are you using any custom parameters or values?
```yaml
  wordpressExtraConfigContent: |
    define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
```
Using external database config (Azure).

(No change from the previous working version)

### What is the expected behavior?

The startup works so WordPress pod can run

### What do you see instead?

Crashloop as SELECT 1 fails, the setup of WordPress in the POD fails.

**Comment by migruiz4** [comment]
Hi @ivmos,

The error message displayed shows that your databases is configured to enforce SSL connection for all clients (https://dev.mysql.com/doc/mysql-security-excerpt/8.0/en/using-encrypted-connections.html#mandatory-encrypted-connections):

```
ERROR 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.
```

Could you please let me know if adding the following value to your deployment fixes the issue?

```yaml
extraEnvVars: 
  - name: "MYSQL_CLIENT_ENABLE_SSL"
    value: true
```

That value will add the `--ssl-mode=REQUIRED` flag to your mysql client connections.

You can also use variables `MYSQL_CLIENT_SSL_CA_FILE`, `MYSQL_CLIENT_SSL_KEY_FILE` and `MYSQL_CLIENT_SSL_CERT_FILE` to provide the file path to your PEM certificates if required.

**Comment by ivmos** [comment]
Right, using MYSQL_CLIENT_ENABLE_SSL env var does the trick. I do not need to provide the other vars.

Thanks!
