### ISSUE TITLE
[bitnami/etcd] enable tls, livenessProbe is Unhealthy: remote error: tls: certificate required

### ISSUE THREAD

**Issue by kevinadmin** [bitnami/charts#29096]
### Name and Version

bitnami/etcd 10.2.13

### What architecture are you using?

None

### What steps will reproduce the bug?

1. kubernetes 1.26+
2. config with 
extraEnvVars:
  - name: "ETCDCTL_INSECURE_SKIP_TLS_VERIFY"
    value: "true"
3. run with
```
helm install bk-etcd bitnami/etcd \
  --namespace bk-test \
  --set replicaCount=3 \
  --set auth.rbac.create=false \
  --set auth.client.secureTransport=true \
  --set auth.client.enableAuthentication=false \
  --set auth.client.existingSecret=bk-etcd-certs \
  --set auth.client.certFilename=tls.crt  \
  --set auth.client.certKeyFilename=tls.key \
  --set auth.client.caFilename=ca.crt \
  --set persistence.enabled=true \
  --set persistence.size=12Gi \
  --set auth.peer.secureTransport=true \
  --set auth.peer.useAutoTLS=true \
  -f values.yaml 
```
5. error with
kubernetes describe:
Warning  Unhealthy          18m (x161 over 3h52m)   kubelet  Liveness probe failed: Get "https://9.165.224.119:2379/livez": remote error: tls: certificate required 
Warning  Unhealthy          3m37s (x27 over 3h7m)   kubelet  (combined from similar events): Liveness probe failed: Get "https://9.165.224.119:2379/livez": write tcp 9.165.224.97:53675->9.165.224.119:2379: write: connection reset by peer  

with log:
{"level":"warn","ts":"2024-08-29T03:02:35.750697Z","caller":"embed/config_logging.go:170","msg":"rejected connection on client endpoint","remote-addr":"9.165.224.97:57780","server-name":"","error":"tls: client didn't provide a certificate"}  

### What do you see instead?

pod staus is CrashLoopBackOff and running , always restart

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, would you like to submit a PR adding a `livenessProbe.httpHeaders` value?

**Comment by Kai-Zhang** [comment]
I encountered the same issue. I tried the solution mentioned in https://github.com/bitnami/charts/issues/27872#issuecomment-2225063036, and it worked well for me. It needs more settings but is still straightforward.
