### ISSUE TITLE
[bitnami/zookeeper] Custom Config issue when no snapshot exists.

### ISSUE THREAD

**Issue by tomerleib** [bitnami/charts#2910]
**Which chart**:
name: zookeeper
version: 5.17.0
appVersion: 3.6.1

**Describe the bug**
Unable to upgrade the chart when no snapshot created. Related to https://issues.apache.org/jira/browse/ZOOKEEPER-3056

According to the bug solution, I need to do add `snapshot.trust.empty=true` to zoo.cfg

The problem with this approch is that in order to add it to my zoo.cfg, I need to add it under the config section, adding only this part will create zoo.cfg with only oneline and ignores all the other parameters that are passed such as `tickTime` and more and eventually will cause Zookeeper to crush since I did not add parameters such as `dataDir` to the config section. More than that, other parameters that aren't exposed to the values and populated automatically such as `Metrics Providers` and `server.1...` must be provided manually to the custom configuration file and specifically for the connectionstring of `server.1...` it cannot be hardcoded because it depends on the number of zk servers and the namespace where I install ZK.

Example of a dynamically created config:
```
# The number of milliseconds of each tick
tickTime=2000
# The number of ticks that the initial
# synchronization phase can take
initLimit=10
# The number of ticks that can pass between
# sending a request and getting an acknowledgement
syncLimit=5
# the directory where the snapshot is stored.
# do not use /tmp for storage, /tmp here is just
# example sakes.
dataDir=/bitnami/zookeeper/data
# the port at which the clients will connect
clientPort=2181
# the maximum number of client connections.
# increase this if you need to handle more clients
maxClientCnxns=60
#
# Be sure to read the maintenance section of the
# administrator guide before turning on autopurge.
#
# http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance
#
# The number of snapshots to retain in dataDir
autopurge.snapRetainCount=3
# Purge task interval in hours
# Set to "0" to disable auto purge feature
autopurge.purgeInterval=0

## Metrics Providers
#
# https://prometheus.io Metrics Exporter
metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
metricsProvider.httpPort=9141
metricsProvider.exportJvmInfo=true
maxCnxns=0
reconfigEnabled=false
quorumListenOnAllIPs=false
4lw.commands.whitelist=srvr, mntr
maxSessionTimeout=40000
server.1=test-zookeeper-0.test-zookeeper-headless.test.svc.cluster.local:2888:3888;2181
server.2=test-zookeeper-1.test-zookeeper-headless.test.svc.cluster.local:2888:3888;2181
server.3=test-zookeeper-2.test-zookeeper-headless.test.svc.cluster.local:2888:3888;2181
```

**Expected behavior**
I would expect to add any custom flags to the config and it should be appended to the existing configuration instead of creating a new one, by doing it the config can still be dynamically generated instead of creating a new config file.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: v2.14.3+g0e7f3b6
Server: v2.14.3+g0e7f3b6
```

- Output of `kubectl version`:

```
Client Version: v1.15.3
Server Version: v1.15.3
```

**Comment by rafariossaa** [comment]
Hi, 
  Could you indicate from which version are you trying to upgrade ?

**Comment by tomerleib** [comment]
Sure, it's quite an outdated version.
Chart version 1.2.3
App version 3.4.13

**Comment by rafariossaa** [comment]
Hi, 
  You could try creating a fake snapshot by entering the container and run:
```
touch /opt/bitnami/zookeeper/data/version-2/snapshot.0
```
  please adjust the path if needed.
  As a general rule, make always a backup before the upgrade. And as this is quite outdated, do the upgrades step by step and not try to jump to the very latest version in one shot.

**Comment by tomerleib** [comment]
About jumping from old version to a (much ) newer version, you're correct, however, I cannot go this path now so I have to jump.

I have tried this method, simply creating the snapshot and performing the upgrade caused the pods to crush with the error of `No snapshot found, but there are log entries. Something is broken!`

So it seems that I still need to go with the custom config file.

**Comment by rafariossaa** [comment]
Hi,
  Maybe other way of doing this is to backup the data and import later the data in a new cluster.
  I have found this tool: https://github.com/rgs1/zk_shell .  
  Could you give it a try ?.
