### ISSUE TITLE
VOLSYNC HELM CHART 

### ISSUE THREAD

**Issue by viju2008** [bitnami/charts#29128]
### Name and Version

bitnami/volsync

### What is the problem this feature will solve?

Volsync helm chart will make it easy to deploy and configure volsync in source and destination cluster and setup Persistent volume replication

https://artifacthub.io/packages/helm/backube-helm-charts/volsync

### What is the feature you are proposing to solve the problem?

Volsync helm chart from bitnami

**Comment by carrodher** [comment]
Removing it as duplicated of https://github.com/bitnami/containers/issues/71492
