### ISSUE TITLE
[mongodb-sharded] Disabling persistence is impossible

### ISSUE THREAD

**Issue by tschneider-aneo** [bitnami/charts#29127]
### Name and Version

bitnami/mongodb-sharded 8.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm install my-mongodb-sharded oci://registry-1.docker.io/bitnamicharts/mongodb-sharded --version=8.2.3 --set shardsvr.persistence.enabled=false`

or

1. `helm install my-mongodb-sharded oci://registry-1.docker.io/bitnamicharts/mongodb-sharded --version=8.2.3 --set configsvr.persistence.enabled=false`

### Are you using any custom parameters or values?

`--set shardsvr.persistence.enabled=false` or `--set configsvr.persistence.enabled=false`

### What is the expected behavior?

My release gets deployed without producing any PV or PVC for the associated MongoDB entity.

### What do you see instead?

`Error: INSTALLATION FAILED: YAML parse error on mongodb-sharded/templates/shard/shard-data-statefulset.yaml: error converting YAML to JSON: yaml: line 184: did not find expected key`

or

`Error: INSTALLATION FAILED: YAML parse error on mongodb-sharded/templates/config-server/config-server-statefulset.yaml: error converting YAML to JSON: yaml: line 187: did not find expected key`

### Additional information

Providing `"false"` as a string produces the same error.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
