### ISSUE TITLE
[bitnami/owncloud] Mount secret as volume to container

### ISSUE THREAD

**Issue by mikeyGlitz** [bitnami/charts#2913]
**Which chart**:

bitnami/owncloud

**Is your feature request related to a problem? Please describe.**

I want to connect my Owncloud deployment to a LDAP server for user authentication. Currently LDAP queries are being rejected because the Owncloud server is not configured to send a CA certificate with the LDAP request.

**Describe the solution you'd like**

I'd like a new variable in the Helm chart that I can use to provide a secret name and a secret key in order for the secret to be mounted onto the container to the path `/etc/ssl/certs`

**Describe alternatives you've considered**

The only alternative I can think of is using the `kubectl edit` command and manually adding the values to create a mount from an existing secret

**Comment by joancafom** [comment]
Hi @mikeyGlitz,

Thanks for your issue, it is an interesting issue to have for sure! Just to fully understand the request, how are you configuring LDAP requests right now? Are you using the web interface? Also, I do understand this has to do with LDAP**S** and that LDAP itself works fine, am I right?

Thanks!

**Comment by mikeyGlitz** [comment]
As it stands, I can establish an LDAP connection without TLS. As soon as I enable TLS, the LDAP request is denied.
OwnCloud has an LDAP plugin which can be downloaded from the marketplace which is what I'm using to set up LDAP.
As for the certificates, they're generated using [cert-manager](https://cert-manager.io/docs/installation/kubernetes/).

**Comment by joancafom** [comment]
Hi @mikeyGlitz,

I see, so it may be the case that OwnCloud fails to complete LDAPS requests because it does not trust the CA. I have been reviewing this recent PR on redmine #2774 and currently thinking of implementing something similar for OwnCloud. That way, in addition to adding the specified certificates under `/etc/ssl/certs` and `update-certificates-ca` command is also triggered so as to correctly update `ca-certificates.cert`.

What do you think of it? Thanks!

**Comment by mikeyGlitz** [comment]
That sounds like what I'm trying to do. The certificate secret needs to be mounted onto the pod/container as a volume. The CA certificate then needs to be trusted in able to make the requests using TLS.

**Comment by joancafom** [comment]
Hi @mikeyGlitz 

Glad to see this can solve your issue regarding LDAPS. To keep you updated about the matter, I am currently implementing the [changes](https://github.com/bitnami/charts/compare/master...joancafom:owncloud-root-ca) and plan to make a PR soon.

Thanks!
