### ISSUE TITLE
[mongodb-sharded] Increasing the usability of the overrideNamespace value

### ISSUE THREAD

**Issue by hyun98** [bitnami/charts#29142]
### Name and Version

bitnami/mongodb-sharded 8.3.6

### What is the problem this feature will solve?

It would be nice that install a mongodb-sharded cluster by simply setting the `namespaceOverride` value without passing the namespace argument.

Despite setting the `namespaceOverride` value, the primaryHost value of `configsvr` is currently fixed to the `Release.Namespace` value.
Because of this, it is very difficult to insert a mongodb-sharded chart as a subchart of another chart.

### What is the feature you are proposing to solve the problem?

I think it will be a more flexible code if you modify it to check the `namespaceOverride` value in the part where you set the `primaryHost` in the `_helper.tpl` file.

related code : https://github.com/bitnami/charts/blob/7134ec1db9fa5b1e9dcf04a131c09f17f1f21f1c/bitnami/mongodb-sharded/templates/_helpers.tpl#L36

### What alternatives have you considered?

Use `common.names.namespace` instead of `Release.Namespace`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
