### ISSUE TITLE
[bitnami/mlflow] values.yaml contain bash with environment variable reference

### ISSUE THREAD

**Issue by Archimonde666** [bitnami/charts#29150]
### Name and Version

bitnami/mlflow:1.4.25

### What steps will reproduce the bug?

Install bitnami/mlflow with default values.yaml using envsubst

### What is the expected behavior?

Postgres starts normally

### What do you see instead?

=> container postgres fail to initialize with this stack : 
```
postgresql 08:07:38.76 INFO  ==> 
postgresql 08:07:38.84 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 08:07:38.84 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 08:07:38.86 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql 08:07:38.87 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql 08:07:38.94 INFO  ==> 
postgresql 08:07:39.17 INFO  ==> ** Starting PostgreSQL setup **
postgresql 08:07:39.36 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 08:07:39.46 INFO  ==> Loading custom pre-init scripts...
postgresql 08:07:39.56 INFO  ==> Initializing PostgreSQL database...
postgresql 08:07:39.86 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 08:07:39.87 INFO  ==> Generating local authentication configuration
postgresql 08:07:40.17 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 08:07:40.37 INFO  ==> Configuring replication parameters
postgresql 08:07:41.38 INFO  ==> Configuring fsync
postgresql 08:07:41.56 INFO  ==> Configuring synchronous_replication
postgresql 08:07:42.14 INFO  ==> Loading custom scripts...
postgresql 08:07:42.16 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 08:07:42.17 INFO  ==> Starting PostgreSQL in background...
Password for user postgres: 
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
postgresql 08:07:43.96 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
```

### Additional information

i have tried to install bitnami/postgresql which turned to be working fine in the cluster along with dozen of services which makes me tell the problem shouldn't be cluster related.

I have also tried using existing secret which turned with the same issue 
And also overriding most of the directly related stuff from bitnami/postgres template which were also unneffective

**Comment by javsalgar** [comment]
Hi,

It seems to me that there may be leftovers from a previous PostgreSQL installation PVC. Could you ensure that the subchart did not have any leftover PVCs? A way to double check that would be to deploy in a different namespace or with a different release name.

**Comment by Archimonde666** [comment]
Hello, i'm sure that no previous data from a leftover pvc impacted this : 
- i installed indeed in a brand new namespace 
- i have the same issue with persistance disabled

**Comment by javsalgar** [comment]
Could you share the generated YAML of the PosgreSQL statefulset?

**Comment by Archimonde666** [comment]
I also anticipate the next question, the automatically generated secret is as such :

**Comment by Archimonde666** [comment]
Ok i think i have it. 
=> the init script stored in the secret is the values template is the problem 
https://github.com/bitnami/charts/blob/b4dd573fb5c00290db0552b8b1c034584a89d827/bitnami/mlflow/values.yaml#L1330

=> i use environment variable in the values.yaml template (as it should be) and then i replace it with envsubst in my CICD.

=> the envsubst replace $POSTGRES_POSTGRES_PASSWORD from my CICD which isn't nor defined nor expected to be defined here

=> i'll test manually restoring the configmap but i believe it wil fix.


=> i recommend you find another way of defining this init script

**Comment by Archimonde666** [comment]
Problem confirmed.
I found a workaround, you can give env value explicitely before using envsubst : just give it back the value it need : 
`POSTGRES_POSTGRES_PASSWORD='$POSTGRES_POSTGRES_PASSWORD' envsubst values.yaml`
