### ISSUE TITLE
[bitnami/influxdb] Users permission and db creation 

### ISSUE THREAD

**Issue by and-dzh3** [bitnami/charts#2915]
**Which chart**:
[bitnami/influxdb] version: 0.5.1

**Is your feature request related to a problem? Please describe.**
I want to be able to create ha influxDB cluster with few databases and few users but
If services exposed via load balancer(AWS) I can't  create users and databases, not via CLI and not  via chronograph because it randomly redirects to different pods (and data not synchronized between them .)

**Describe the solution you'd like**
Create users and databases with permission via CLI or UI 

**Describe alternatives you've considered**
I know the init scrips and addition config maps and custom values are supported, but what happens if i need to create a new database on the fly?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. So, if I understand correctly, the issue is that you cannot access the influxdb database from outside the cluster. We've seen similar cases for other charts like Kafka or Redis Cluster. Maybe it makes sense in this case to allow exposing all pods externally, so you don't find any issue with the redirections. Would that make sense?

**Comment by and-dzh3** [comment]
@javsalgar no, I can access , read database via the load balancer  and inject data via a relay load balancer, but if i want to manage permission and create databases its always send me to different pods ( so I need to create databases and users on each pod  and there is no replication mechanism )

**Comment by javsalgar** [comment]
Hi,

From what I see, this seems to be a limitation in how influxdb-relay works. I'm not sure if there's an easy option for this. The only thing that comes to mind would be allowing to modify the custom scripts so they get executed everytime the container gets restarted. In that script you could check if a given user exists and if not, create it. The same with the database. 

So, if you need to create a database on the fly you would change the init script configmap and restart the pods. Would that make sense?

**Comment by and-dzh3** [comment]
@javsalgar tnq for answers, done with init dB scripts .
