### ISSUE TITLE
[postgresql] when specifying a custom user metrics can't be collected anymore

### ISSUE THREAD

**Issue by tbalzer** [bitnami/charts#29156]
### Name and Version

bitnami/postgresql 15.5.12

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Set `auth.username` to `myuser`
2. Set `metrics.enabled` to `true`
3. Install chart and observe logs of metrics container

### Are you using any custom parameters or values?

`--set auth.username=myuser --set metrics.enabled=true`

### What is the expected behavior?

Metrics should be collected from all databases regardless of whether a custom user is specified or not.

### What do you see instead?

Once a custom user is specified this user is used to collect metrics and has insufficient permissions.

### Additional information

This breaks for us in 15.5.12 as since that version all databases are monitored instead of only the database the custom user has access to.

In my opinion the `postgres` administrative user should be used to collect metrics. This also solves other related issues like #20247 I believe.

If you agree I'm happy to provide a PR for this.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Stevenpc3** [comment]
This doesn't solve for "custom" user or in postgresql-ha
