### ISSUE TITLE
[bitnami/harbor] Unable to login with admin user

### ISSUE THREAD

**Issue by shaikzoheb-oi** [bitnami/charts#29163]
### Name and Version

bitnami/harbor 2.11.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Deployed harbor locally using kind cluster.

All pods are running fine.

Even I am able to access harbor portal as well, but when trying to login using admin credentials. It's saying invalid user or password. Even though the user and password is correct

![image](https://github.com/user-attachments/assets/2e6c6b97-f981-4811-bf3b-1040a07b1407)

Same admin password I am trying to login:

![image](https://github.com/user-attachments/assets/2e1a5b65-d365-403c-bf02-cd1ec283463c)

### Are you using any custom parameters or values?

NO

### What is the expected behavior?

I should be able to login with admin user and the password

### What do you see instead?

Invalid user name or password

![image](https://github.com/user-attachments/assets/86b38319-a0e9-4358-a13b-cc0d643febd9)

### Additional information

It's a bitnami helm chart - harbor-23.0.1

App Version: 2.11.1

**Comment by shaikzoheb-oi** [comment]
@javsalgar Please let me know if you need more details. Usually it should work out of the box, I am not sure why it's failing.

**Comment by shaikzoheb-oi** [comment]
Even I've tried in this way as well, but it didn't worked.

helm install harbor --set adminPassword=Z0een_342342 oci://registry-1.docker.io/bitnamicharts/harbor -n harbor-local

![image](https://github.com/user-attachments/assets/54ffae93-d6da-4643-bcb9-a7c76a4c7a68)

**Comment by javsalgar** [comment]
Hi!

Could you ensure that you do not have leftover PVCs from previous Harbor installations?

**Comment by shaikzoheb-oi** [comment]
Before installing harbor with this flag "--set adminPassword", I've uninstalled and deleted existing harbor PVCs and reinstalled with below command. But it didn't worked as I've posted error above.

![image](https://github.com/user-attachments/assets/b466b860-4f2d-412f-97f2-bf3513443b84)

**Comment by shaikzoheb-oi** [comment]
@javsalgar Looks like something is wrong. Even I've deployed the same harbor in a fresh cluster, but still the same invalid user or password. I've cleared the browser cache as well

I am not sure whether the issue is only for me or for other users as well

**Comment by shaikzoheb-oi** [comment]
@javsalgar Any suggestions on this?

**Comment by shaikzoheb-oi** [comment]
If you want me to try with other versions of helm, I can try immediately and validate. Even with version 22.0.12, I am getting the same error "Invalid user or password"

**Comment by shaikzoheb-oi** [comment]
It is not allowing to create new user as well.

![image](https://github.com/user-attachments/assets/77c73131-3b3c-492c-97f4-f964f7a80119)

**Comment by shaikzoheb-oi** [comment]
@juan131 Thanks a lot. It was my browser cache issue.

Truely appreciate your response

**Comment by Bloodday** [comment]
I know this is closed, but he same is happening to me with harbor helm template v24.1.2

**Comment by pptfz** [comment]
I know this is closed, but he same is happening to me with harbor helm template v27.0.3

**Comment by pptfz** [comment]
> I know this is closed, but he same is happening to me with harbor helm template v24.1.2我知道这是关闭的，但是我对我的港口舵模板v24.1.2发生了同样的事情。

I also encountered the same problem and was unable to log in to Harbor.
