### ISSUE TITLE
[bitnami/thanos] Constant volumeClaimTemplates diff in ArgoCD

### ISSUE THREAD

**Issue by pentago** [bitnami/charts#29178]
### Name and Version

bitnami/thanos 15.7.23

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deployed chart with ArgoCD

### Are you using any custom parameters or values?

Just enabled persistence:

```
  persistence:
    enabled: true
```

..and enabled almost all components (query,frotnend,compactor,storagegateway,ruler,receive)

### What is the expected behavior?

ArgoCD application gets synced and not showing any diff

### What do you see instead?

ArgoCD app showing constant diffs for `volumeClaimTemplates`

![image](https://github.com/user-attachments/assets/2ad8d7ee-39af-4556-a24e-3b3f33a0d1ad)

### Additional information

values.yaml I use: https://gist.githubusercontent.com/pentago/777503aef4454125536bff90751ddfb9/raw/ec840374e7c78a44032097bab269c6e25614c54e/values.yaml

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. It seems that argo-cd expects to have the apiVersion and kind sections set. Would you like to submit a PR adding these two fields?

**Comment by pentago** [comment]
Sure, no probs!

**Comment by javsalgar** [comment]
Thank you so much for the PR!
