### ISSUE TITLE
seaweedfs does not support an external mariadb database

### ISSUE THREAD

**Issue by wkbrd** [bitnami/charts#29196]
### Name and Version

bitnami/seaweedfs 1.0.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using seaweedfs and providing the externalDatabase options, the required environment variables defining the mariadb configuration (WEED_MYSQL_*) are not defined.

### Are you using any custom parameters or values?

Yes.

mariadb.enabled=false
externalDatabase.enabled=true
externalDatabase.host
externalDatabase.user
externalDatabase.password
externalDatabase.port
externalDatabase.database

### What is the expected behavior?

seaweedfs starts properly and uses mariadb/mysql as its filer persistence storage

### What do you see instead?

Fails to start since the required environment variables are not set.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by wkbrd** [comment]
This was implemented via #29216.
