### ISSUE TITLE
[bitnami/elasticsearch:21.3.11]: copy-tls-certificates initcontainer does not use containersecuritycontext

### ISSUE THREAD

**Issue by kvandenhoute** [bitnami/charts#29192]
### Name and Version

bitnami/elasticsearch:21.3.11

### What architecture are you using?

None

### What steps will reproduce the bug?

It's not really a bug, it just doesn't use the given containersecuritycontext, which it actually should use

### What is the expected behavior?

Use the given containersecuritycontext (it does not need anything special)

### What do you see instead?

It doesn't use it

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
