### ISSUE TITLE
[postgresql] bug : password authentication failed after installing postgres on windows (not in container)

### ISSUE THREAD

**Issue by finaldzn** [bitnami/charts#2920]
**Which chart**:
The name (and version) of the affected chart
postgresql-8.7.2
**Describe the bug**
When installing postgres locally (ie not in a container) on windows, pg passwords are not recognized anymore by the pg container in kubernetes despite them being correct.
**To Reproduce**
1. Install the postgresql chart on kubernetes
2. Connect with the specified password
3. Install postgresql on windows
4. Try to connect to the postgresql on kubernetes with the specified password and it should not work (postgres user authentification failed, passwords did not match)

**Expected behavior**

I expected to be able to connect to the windows postgresql with the windows password and I expected to be able to connect to the postgresql container with the container password 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Uninstalling postgres locally (windows) and then resetting my clustyer fixed the problem.

**Comment by andresbono** [comment]
Hi @finaldzn, when you install the chart, you get some information on how to connect to postgresql.

> kubectl port-forward --namespace default svc/postgresql 5432:5432 &
> PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432

You can get that information again by executing:

```
helm get notes <RELEASE NAME>
```

Do the commands work for you? How are you trying to connect to the cluster?

**Comment by finaldzn** [comment]
Hello, I'm trying to connect to postgres from inside the cluster directly

Le jeu. 25 juin 2020 à 10:44 AM, Andrés Bono <notifications@github.com> a
écrit :

**Comment by andresbono** [comment]
Hi @finaldzn, if you are connecting from inside the cluster, there is nothing to worry about your local postgresql installation in Windows.

Did you try the commands from my previous comment? Please, give us more information about the commands that you are executing to connect to your postgresql deployment if you need further help.

**Comment by misterstrickland** [comment]
Not sure if my issue is related, but I'm installing the chart on a Fedora 29 and the authentication never works. I followed all the steps to extract the password, tried overriding the user name and password (with and without `global.postgresql`), copy/pasting the command to run the client container, and nothing works.  I always get `psql: FATAL:  password authentication failed for user "postgres"` (or the other user I set)

**Comment by andresbono** [comment]
Hi @misterstrickland, can you share the specific version of the chart and the values that you are using to install the chart?

**Comment by finaldzn** [comment]
> Hi @finaldzn, if you are connecting from inside the cluster, there is nothing to worry about your local postgresql installation in Windows.
> 
> Did you try the commands from my previous comment? Please, give us more information about the commands that you are executing to connect to your postgresql deployment if you need further help.

I tried to connect to the postgres server through an application in the same cluster. But the password was not right and I had a `password authentication failed for user "postgres"` . 

But removing my local postgres on windows (not in a container) and resetting my cluster fixed the problem.

**Comment by misterstrickland** [comment]
> Hi @misterstrickland, can you share the specific version of the chart and the values that you are using to install the chart?

Running this:
```
helm install fl-psql bitnami/postgresql --set service.nodePort=32432 --set service.type=NodePort
```

Installed helm/k8s:
```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @misterstrickland, it is possible that you need to start from a totally clean deployment. In order to preserve the data of PostgreSQL, some persistent volumes are kept even if you do `helm delete`. Maybe you are keeping volumes from a previous deployment and then the password is out of sync.

You can list the persistent volumes claims with `kubectl get pvc`. If you are sure there is no relevant data in the deployments, you can do:

```
helm delete fl-psql
kubectl delete pvc <YOUR_PVC>
```

**Comment by misterstrickland** [comment]
> Hi @misterstrickland, it is possible that you need to start from a totally clean deployment. In order to preserve the data of PostgreSQL, some persistent volumes are kept even if you do `helm delete`. Maybe you are keeping volumes from a previous deployment and then the password is out of sync.
> 
> You can list the persistent volumes claims with `kubectl get pvc`. If you are sure there is no relevant data in the deployments, you can do:
> 
> ```
> helm delete fl-psql
> kubectl delete pvc <YOUR_PVC>
> ```

That did the trick, thanks!

**Comment by andresbono** [comment]
Cool! Thanks to you for confirming it!
