### ISSUE TITLE
[bitnami/minio]: `metrics.prometheusRule` also requires `metrics.enabled` which doesn't exist.

### ISSUE THREAD

**Issue by Karitham** [bitnami/charts#29218]
### Name and Version

bitnami/minio 14.6.7

### What steps will reproduce the bug?

the docs for `metrics.prometheusRule` mention `metrics.enabled` but `metrics.enabled` isn't documented in `values.yaml`. Weirdly, `metrics.serviceMonitor` doesn't require `metrics.enabled`.

**Comment by Karitham** [comment]
Also I just found that adding labels is named differently in both `serviceMonitor` and `prometheusRule`. `metrics.serviceMonitor.labels` and `metrics.prometheusRule.additionalLabels`

The latter has documentation problems as well.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by Karitham** [comment]
I've looked into contributing, and it appears the consistency is poor.
```
❯ rg metrics.prometheusRule.additionalLabels ./bitnami/*/values.yaml --count | wc -l
22
❯ rg metrics.prometheusRule.labels ./bitnami/*/values.yaml --count | wc -l
6

❯ rg metrics.serviceMonitor.additionalLabels ./bitnami/*/values.yaml --count | wc -l
9
❯ rg metrics.serviceMonitor.labels ./bitnami/*/values.yaml --count | wc -l
59
```
I've seen a few lines saying `additionalLabels` was deprecated here and there (eg, the grafana chart), but nothing concrete. Are there any guidelines about this? Is the status quo fine and nobody cares?

Other than that, most seems to have a `metrics.enabled` as well as a per-kind `serviceMonitor` and `prometheusRule` so I'll PR that.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
