### ISSUE TITLE
bitnami/seaweedfs Support for postgresql external database

### ISSUE THREAD

**Issue by wkbrd** [bitnami/charts#29215]
### Name and Version

bitnami/seaweedfs 1.0.9

### What is the problem this feature will solve?

Allows for using an external postgres database with seaweedfs

### What is the feature you are proposing to solve the problem?

Add support for specifying environment variables and password secret for a postgres database to be used with seaweedfs.

### What alternatives have you considered?

Mariadb could be used, though using postgres would enable an additional option and may be desirable for organizations that are using postgres and not mariadb as their database-of-choice.

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by wkbrd** [comment]
Capability was implemented via #29216.
