### ISSUE TITLE
bitnami/airflow: Add KubernetesExecutor to Airflow

### ISSUE THREAD

**Issue by bhavaniravi** [bitnami/charts#2921]
**Which chart**:
airflow 

**Is your feature request related to a problem? Please describe.**
Airflow has an option to use KubernetesExecutor instead of CeleryExecutor, from what I saw the executor is hardcoded i[n scheduler deployment config](https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/deployment-scheduler.yaml#L214). This makes impossible to use this helm chart for people using `kubernetesExecutor`

**Describe the solution you'd like**
Moving the executor selection and its associated configs to the values file.

**Comment by rafariossaa** [comment]
Hi,
  I am opening an internal task to study this request and the changes needed.
  We will come back as soon as we have news.

Thanks.

**Comment by juan131** [comment]
This feature was added at https://github.com/bitnami/charts/pull/4069
