### ISSUE TITLE
Zookeeper StatefulSet is always out of sync in argocd

### ISSUE THREAD

**Issue by aqeelat** [bitnami/charts#29288]
### Name and Version

bitnami/zookeeper 13.4.9

### What architecture are you using?

None

### What steps will reproduce the bug?

Just a regular kafka deployment

### What is the expected behavior?

For the templates to have apiVersion and kind.

### What do you see instead?

<img width="1151" alt="Screenshot 2024-09-06 at 10 59 51 PM" src="https://github.com/user-attachments/assets/11aa0ef1-8095-4c9d-af35-839294eb86e7">

### Additional information

After searching in the repo, almost all volumeClaimTemplates are correct, except for zookeeper and a few other deployments/satetefulSets.
I will open a PR to fix this.

**Comment by aqeelat** [comment]
I take it back.

Out of the 73 files that have volumeClaimTemplates, 44 files are missing the apiVersion and kind, including the template.
I don't mind opening the PR but this would mean that I'll be bumping the versions of a lot of charts, and get stuck in a versioning loop until the PR is merged.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by aqeelat** [comment]
@carrodher what's the process for releasing a new version of kafka? Do I just run `helm dependency build` and open a pr with the updated lock file?
