### ISSUE TITLE
[bitnami/matomo] Connect Matomo to Azure Flexible server with encrypted connections (SSL)

### ISSUE THREAD

**Issue by florentvaldelievre** [bitnami/charts#29287]
### Name and Version

bitnami/matomo 8.0.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Matomo is failing to configure database (step 3) in the wizard when SSL is enabled on flexible server side

```
matomo 19:35:39.65 INFO  ==>
matomo 19:35:39.65 INFO  ==> Welcome to the Bitnami matomo container
matomo 19:35:39.65 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
matomo 19:35:39.65 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
matomo 19:35:39.65 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
matomo 19:35:39.65 INFO  ==>
matomo 19:35:39.65 INFO  ==> ** Starting Matomo setup **
matomo 19:35:39.69 DEBUG ==> Validating settings in APACHE_* environment variables
matomo 19:35:39.70 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
matomo 19:35:39.70 INFO  ==> Generating sample certificates
Certificate request self-signature ok
subject=CN = example.com
realpath: /bitnami/apache/conf: No such file or directory
matomo 19:35:42.71 INFO  ==> Configuring the HTTP port
matomo 19:35:42.71 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/httpd.conf
matomo 19:35:42.71 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/bitnami/bitnami.conf
matomo 19:35:42.72 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/vhosts/00_status-vhost.conf
matomo 19:35:42.72 INFO  ==> Configuring the HTTPS port
matomo 19:35:42.72 DEBUG ==> Configuring port 8443 on file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
matomo 19:35:42.72 INFO  ==> Configuring Apache ServerTokens directive
matomo 19:35:42.72 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
matomo 19:35:42.80 INFO  ==> Configuring PHP options
matomo 19:35:42.80 INFO  ==> Setting PHP expose_php option
matomo 19:35:42.81 INFO  ==> Setting PHP output_buffering option
matomo 19:35:42.82 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo 19:35:42.92 DEBUG ==> Validating settings in MATOMO_* environment variables...
matomo 19:35:43.01 INFO  ==> Ensuring Matomo directories exist
matomo 19:35:43.02 INFO  ==> Trying to connect to the database server
matomo 19:35:43.02 DEBUG ==> Executing SQL command:
SELECT 1
1
matomo 19:35:43.12 INFO  ==> Starting apache in background
matomo 19:35:48.30 INFO  ==> apache started
matomo 19:35:48.30 INFO  ==> Passing Matomo installation wizard
....
A lot of HTML is returned, but I think the actual error message is this one:

    <h2>Database Setup</h2>
            <div class="alert alert-danger">
            Could not connect to the database server:
            Connections using insecure transport are prohibited while --require_secure_transport=ON.
```

From what I understand, the following curl is failing: https://github.com/bitnami/containers/blob/3ae4eb18f2c9b056b66283157ea07c45dfc34e99/bitnami/matomo/5/debian-12/rootfs/opt/bitnami/scripts/libmatomo.sh#L363-L372

I am a bit worried when I see this parameter set statically in the php code
            'enable_ssl'    => false

https://github.com/matomo-org/matomo/blob/750fdced131a8d2fd3ed30ba06b19506651f4258/plugins/Installation/FormDatabaseSetup.php#L163C10-L163C18

**Steps to reproduce**

https://learn.microsoft.com/en-us/azure/mysql/flexible-server/how-to-connect-tls-ssl

- Deploy a Flexible server on Azure with SSL enabled. Create a database for Matomo
- Deploy Matomo helm chart on AKS and connect it to Azure MySQL Flexible Server.

Use the following Extra environment variables to the chart

```yaml
 extraEnvVars:
  - name: MYSQL_CLIENT_ENABLE_SSL
    value: "yes"
  - name: MYSQL_CLIENT_SSL_CA_FILE
    value: "/etc/ssl/certs/DigiCert_Global_Root_CA.pem"
  - name: MYSQL_CLIENT_ENABLE_SSL_WRAPPER
    value: "yes"
  - name: MATOMO_ENABLE_DATABASE_SSL
    value: "yes"
  - name: MATOMO_ENABLE_FORCE_SSL
    value: "yes"
  - name: MATOMO_DATABASE_SSL_CA_FILE
    value: "/etc/ssl/certs/DigiCert_Global_Root_CA.pem"
```

Any idea? Connection with SSL is not supported?

### What do you see instead?

See above

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by florentvaldelievre** [comment]
Thank you but can you confirm if the wizard supports SSL connexion?

**Comment by tduniec** [comment]
hello @florentvaldelievre 

I am having exactly the same issue using AWS EKS (where matomo chart is deployed) and RDS MySQL db. 
Seems like setting up this suggested config is not applied to connections check. 

I have also tried using the certificates intiContainer but not succeeded. 

Can we ask you to fix this @bitnami_team
