### ISSUE TITLE
[bitnami/mariadb-galera] optional 'node-name'/'node-number' parameter? (feature or support request)

### ISSUE THREAD

**Issue by Trogie** [bitnami/charts#29292]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

Hello,
I am searching to have my binlogs on a seperate (NFS) share. One application has a small database but one with lots of writes/deletes so my binlogs get very big very fast. I want to keep the database data on the 'default' persistence storage.

I thought on mounting the NFS share on /bitnami/mariadb/data/binlogs and write the binlogs into that directory. The problem is that all nodes will overwrite each others binlogs. Hence the logs should be written in /bitnami/mariadb/data/binlogs/<pod-number> or <pod-name> in order to not overwrite them.

### What is the feature you are proposing to solve the problem?

Is there a way to add a 'hostname' variable into the helm charts for that? Willing to develop it myself with some coaching.

### What alternatives have you considered?

None for the moment

**Comment by javsalgar** [comment]
Hi!

Would something like having a binlog PVC per node (using the NFS storage) work? We could allow adding extra `volumeClaimTemplates` sections, which could work for your use case

**Comment by Trogie** [comment]
Aaah yeah! I was thinking at 1 (NFS) share that all nodes use, but having the binlogs in a per-node share would also be OK.

**Comment by javsalgar** [comment]
Great! I will forward it to the team, but as it is not a critical feature I cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding support for `extraVolumeClaimTemplates`. You can see an example here https://github.com/bitnami/charts/blob/eef283596e54e26b9b7a3e1fa05e6d62654c7c87/bitnami/airflow/templates/worker/statefulset.yaml#L291
