### ISSUE TITLE
[bitnami/apisix] Ability to disable Kubernetes discovery

### ISSUE THREAD

**Issue by james-mchugh** [bitnami/charts#29312]
### Name and Version

bitnami/apisix:3.3.9

### What is the problem this feature will solve?

Currently, Kubernetes discovery is enabled by default. This can be problematic when running Apisix in standalone mode with the routes manually configured. When I deploy Apisix, I disable RBAC creation as I do not want Apisix to have cluster-level permissions, this causes Apisix to repeatedly log the following error

```
2024/09/09 16:28:30 [error] 22#22: *472764 [lua] informer_factory.lua:295: list failed, kind: Endpoints, reason: Forbidden, message : {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints is forbidden: User \"system:serviceaccount:default:apisix-data-plane\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"endpoints"},"code":403}
```

This doesn't cause any real issues, as Kubernetes discovery isn't needed for my usecase. However, the error message can be  misleading when trying to debug other errors. 

### What is the feature you are proposing to solve the problem?

Add a `dataPlane.discovery.enabled` field to control whether discovery is enabled or not. 

### What alternatives have you considered?

In the nearterm, I'm going to override the entire `dataPlane.defaultConfig` field from the values.yaml to remove the discovery section.

I have also tried disabling it by setting `apisix.extraConfig.discovery: {}` in the values.yaml, but that caused issues in the prepare-apisix init container: 

```
/opt/bitnami/apisix/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init
invalid discovery kubernetes configuration: object matches none of the required
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding support for that value and the team will check it.
