### ISSUE TITLE
[bitnami/mariadb-galera] warning: setting timezone 'Etc/UTC' fails on server.

### ISSUE THREAD

**Issue by sepek** [bitnami/charts#29313]
### Name and Version

bitnami/mariadb-galera 14.0.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Creating a cluster
2. Connecting via Sequelize with mariadb node connector 2.5.6 as regular user
3. Check the logs of the mariadb container

### Are you using any custom parameters or values?

values diff against the git version from the corresponding `git tag`
```
diff --git a/values/mariadb-galera.yaml b/values/mariadb-galera.yaml
index 0ee1ae6..3a113a2 100644
--- a/values/mariadb-galera.yaml
+++ b/values/mariadb-galera.yaml
@@ -325,7 +327,7 @@ containerSecurityContext:
 rootUser:
   ## @param rootUser.user Username for the admin user.
   ##
-  user: root
+  user: root_2024
   ## @param rootUser.password Password for the admin user. Ignored if existing secret is provided.
   ## Password is ignored if existingSecret is specified.
   ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mariadb-galera#setting-the-root-password-on-first-run
@@ -338,7 +340,7 @@ rootUser:
 ## @param existingSecret Use existing secret for password details (`rootUser.password`, `db.password`, `galera.mariabackup.password` will be ignored and picked up from this secret)
 ## The secret has to contain the keys mariadb-root-password, mariadb-galera-mariabackup-password and mariadb-password.
 ##
-existingSecret: ""
+existingSecret: mariadb-galera-users
 ## @param usePasswordFiles Mount credentials as a files instead of using an environment variable.
 ##
 usePasswordFiles: false
@@ -356,14 +358,14 @@ db:
   ## @param db.user Username of new user to create
   ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mariadb-galera#creating-a-database-user-on-first-run
   ##
-  user: ""
+  user: foobar_2024
   ## @param db.password Password for the new user. Ignored if existing secret is provided.
   ##
   password: ""
   ## @param db.name Name for new database to create
   ## ref: https://github.com/bitnami/containers/tree/main/bitnami/mariadb-galera#creating-a-database-on-first-run
   ##
-  name: my_database
+  name: foobar
```

### What is the expected behavior?

No warnings in the logs from the SQL connection

### What do you see instead?

Get spammed regularly by:
```
warning: setting timezone 'Etc/UTC' fails on server.
 look at https://mariadb.com/kb/en/mysql_tzinfo_to_sql/ to load IANA timezone.
Setting timezone can be disabled with option `skipSetTimezone`
```

### Additional information

- This does **not happen** with `root_2024`
- Importing the timezone information as suggested by the link does not help
- Trying to explicitly set the timezone to a different one or using `+00:00` via `TZ` env and/or `default-time-zone` does not help
- Explicitly setting the TZ in Sequelize (as string and `+00:00`) or changeing `useUTC` does not help
- Enabling debug in Sequelize if there are any special requests send - which are not
- Creating a local mariadb Docker container (tag `lts`), with a read-only setup and the same config - minus Bitnami specific paths and minus Galera does not reproduce the problem
- Connecting from the dev setup directly via port forwarding which can reproduce the problem
- Comparing the GRANTS with a setup which does not show that problem, only difference is a IP restriction

Note: obviously that's not necessarily a Bitnami chart issue, however that's so far the only option to trigger that problem for me so I decided to start here

**Comment by javsalgar** [comment]
Hi,

Thank you for the detailed information. Does the issue happen when using the regular `mysql` client instead of sequelize?

**Comment by sepek** [comment]
Thanks for reviewing the issue. First it does not appear if I use `mysql` and execute `SET time_zone='Etc/UTC'` like the node library does.

However I seem to have found the source of the problem:
```
@@ -473,9 +473,9 @@ mariadbConfiguration: |-
 
   ## Character set
   ##
-  collation_server=utf8_unicode_ci
-  init_connect='SET NAMES utf8'
-  character_set_server=utf8
+  collation_server=utf8mb4_unicode_520_ci
+  init_connect='SET NAMES utf8mb4'
+  character_set_server=utf8mb4
 
   ## MyISAM
   ##
```
After that change it does not happen anymore. As the default collation for the mariadb node library `UTF8MB4_UNICODE_CI`. Due to that it breaks the command it doesn't work anymore.
So this is clearly a layer 8 issue sorry for the noise!
However I have no idea why we did not see any functional issue nor why it does not appear as `root`  …

As the source was layer 8 I consider this problem solved and close it.  If you think I should go with that to the Sequlize or mariadb node library team, please tell me.
