### ISSUE TITLE
[bitnami/redis] why do wee need publishNotReadyAddresses=true in headless service

### ISSUE THREAD

**Issue by yvzsrt** [bitnami/charts#29323]
### Name and Version

bitnami/redis:15.5.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have a problem about redis-headless service 
All cluster nodes are UP and in Ready status:
```
NAME       STATUS   ROLES                  AGE    VERSION
ha-node1   Ready    control-plane,master   234d   v1.23.17
ha-node2   Ready    control-plane,master   234d   v1.23.17
ha-node3   Ready    control-plane,master   234d   v1.23.17
```
All end points are OK
```
sepon@ha-node1:~$ kubectl -n voltha-1 describe ep redis-1-headless redis-1 | grep Address
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
```
When one node becomes NotReady:
```
NAME       STATUS     ROLES                  AGE    VERSION
ha-node1   Ready      control-plane,master   234d   v1.23.17
ha-node2   NotReady   control-plane,master   234d   v1.23.17
ha-node3   Ready      control-plane,master   234d   v1.23.17
```
Endpoints of Redis servis is OK but end points of redis-headless is not updated:
```
sepon@ha-node1:~$ kubectl -n voltha-1 describe ep redis-1-headless redis-1 | grep Address
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
  Addresses:          172.16.14.228,172.16.44.217
  NotReadyAddresses:  172.16.109.214
```
As you see pod 172.16.109.214 is in NotReady status but it is still in headless end point list

I asked this situation to Kubernetes github and found that there is the "publishNotReadyAddresses: true" parameter in headless service, parameter not exists in redis service.

when we shutdown a node our application tries to go redis pod that is in terminating status as IP of that pod is still in end point list. Why do you use this parameter? For applications that use redis should we not use headless service?

### What do you see instead?

```
sepon@ha-node1:~$ kubectl -n voltha-1 describe ep redis-1-headless redis-1 | grep Address
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
  Addresses:          172.16.14.228,172.16.44.217
  NotReadyAddresses:  172.16.109.214
```

**Comment by javsalgar** [comment]
Hi,

The reasoning for using the headless service is because the nodes require their own endpoint (in the form of ephemeral IP in this case) for their internal cluster creation. About the `publishNotReadyAccess=true`, if I remember correctly, it had to do with the necessity of the nodes to be accessible during cluster creation time, but maybe this has changed and it's not necessary. Could you try deploying disabling the publishNotReadyAccess value and see if the cluster starts?  At least we could set it as a parameter, as it may cause problems with different CNI plugins.
