### ISSUE TITLE
Postgressql. existingClaim should be for master and slave

### ISSUE THREAD

**Issue by serg-bs** [bitnami/charts#2932]
**Which chart**:
postgresql

**Describe the bug**
Deploy to bare metal kubernetes I need to set up persistence.existingClaim
persistence.existingClaim should be different for master and slave
like in mysql helmchart
```
{{- else if and .Values.slave.persistence.enabled .Values.slave.persistence.existingClaim }}
        - name: "data"
          persistentVolumeClaim:
            claimName: {{ .Values.slave.persistence.existingClaim }}
{{- else if and .Values.slave.persistence.enabled (not .Values.slave.persistence.existingClaim) }}
  volumeClaimTemplates:
```

**Comment by andresbono** [comment]
Hi @serg-bs, it makes sense to add this feature. Would you like to open a PR addressing the changes? Contributions are more than welcome!
