### ISSUE TITLE
[bitnami/external-dns] Add targetLabels to the ServiceMonitor for external-dns

### ISSUE THREAD

**Issue by mrrsm** [bitnami/charts#29332]
### Name and Version

bitnami/external-dns

### What is the problem this feature will solve?

The service monitor does not let you specify `targetLabels` to include extra labels

### What is the feature you are proposing to solve the problem?

Add `targetLabels`, similar to the rabbitmq chart, to the service monitor

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look
