### ISSUE TITLE
Right way to specify podAffinity/nodeSelector for kibana sub-chart from Elasticsearch chart

### ISSUE THREAD

**Issue by nikhilno1** [bitnami/charts#2933]
I have just started using Bitnami Elasticssearch chart to deploy my cluster on AWS EKS. I have been able to deploy it successfully using the _values-production.yaml_ file. Thank you for this wonderful chart. 

I have one issue though. I see that the _templates/metrics-deploy.yaml_ doesn't handle both, node selector or pod affinity. I want my metrics container to run on one of the Elasticsearch master nodes. Does that mean I have to modify the _metrics-deploy.yaml_ file? Is it possible to change only the _values-production.yaml_ file?

Thanks.

**Comment by rafariossaa** [comment]
Hi @nikhilno1 ,
  Yes, currently it can not handle both. 
  Would you like to make a PR ? We will be glad to review and merge it.
