### ISSUE TITLE
[bitnami/mlflow] MLFlow Tracking manifest

### ISSUE THREAD

**Issue by NeelArle** [bitnami/charts#29351]
### Name and Version

bitnami/mlflow:1.5.0

### What is the problem this feature will solve?

Currently, the MLFlow server's tracking object has been defined as Deployment at the K8S manifest "yaml" file. However, having associated PVs there are issues when upgrading the tracking object running "helm upgrade" commands, as a RollingUpdate strategy is applied by default (this could be solved by setting the ‘Recreate’ strategy). 

Furthermore, in the documentation, the property ‘tracking.updateStrategy.type’ is described as ‘mlflow statefulset strategy type’, but currently the object is of type Deployment and not StatefulSet.

### What is the feature you are proposing to solve the problem?

My suggestion is therefore to change the manifest ‘tracking/deployment.yaml’ to tracking/statefulset.yaml' so that it becomes a StatefulSet object, which is more appropriate when volumes are assigned to the object.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
