### ISSUE TITLE
[bitnami/postgres-ha] extendedConf causing permissions error

### ISSUE THREAD

**Issue by elizabeth-dev** [bitnami/charts#29365]
### Name and Version

bitnami/postgres-ha 14.2.27

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Deploy an instance of the postgresql-ha chart specifying a custom `postgresql.extendedConf` value
2. The PostgreSQL pod fails with error:

```
postgresql-repmgr 10:26:03.49 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 10:26:03.50 INFO  ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied
```

### Are you using any custom parameters or values?

```
postgresql:
  extendedConf: |-
    hba_file /tmp/pg_hba.conf
```

### What is the expected behavior?

The pod starts with the custom configuration applied

### What do you see instead?

The initContainer that sets the permissions in the `/opt/bitnami/postgresql/conf` folder isn't setting them properly, causing the PostgreSQL initialization to fail when trying to write to its conf dir

### Additional information

I see the following error when installing the chart that might be related:
```
W0911 10:26:00.865333      68 warnings.go:70] unknown field "spec.template.spec.initContainers[0].securityContext.enabled"
```

**Comment by cyberm4g3** [comment]
I just ran into this as well. As a work around, I set the `volumePermissions.image.tag` helm value to `11-debian-11-r94` as I know that version is working correctly. Of note, I'm using version `12.8.0` of the helm chart.

**Comment by jotamartos** [comment]
Hi all, 

We reproduced the issue and are reviewing the configuration. This is probably caused by the security and permissions related configuration changes we applied in the past. I'll update this thread when having more information.

**Comment by jotamartos** [comment]
I just found the issue with the extendedConf parameter. If you make use of it, you also need to enable the volumePermissions.enabled parameter so this block is executed and the permissions are configured properly

https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L118

I hope this info helps

**Comment by elizabeth-dev** [comment]
> I just found the issue with the extendedConf parameter. If you make use of it, you also need to enable the `volumePermissions.enabled` parameter so this block is executed and the permissions are configured properly
> 
> https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L118
> 
> I also created a PR to update the documentation
> 
> #29497
> 
> I hope this info helps

had a chance to try this and it works!! thanks a lot ✨
