### ISSUE TITLE
[bitnami/elasticsearch] Changing elastic password cause readiness probe to fail

### ISSUE THREAD

**Issue by mayac-philips** [bitnami/charts#29366]
### Name and Version

bitnmai/elasticsearch 8.10.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Changine elastic username password
2. replace secret in secret k8s object
3. restart elasticsearch

### Are you using any custom parameters or values?

running on master pod.
mounting secret as elasticsearch-password

### What is the expected behavior?

Probe readiness and liveness should work with the new password

### What do you see instead?

I get a log showing:  [elasticsearch-master-0] Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]

### Additional information

If I cancel security to disable elasticsearch is running. When enabled it showed running with 1/0. I entered the pod and verified the new password is in env. I tried followed similar situation when upgrading without providing password but that didn't help.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that changing the secret object does not cause the password to change inside the container. In the Bitnami containers, the password is set at first boot, so if you want to change the password, you will need to enter the container and perform the password change as well.

**Comment by mayac-philips** [comment]
> Hi,
> 
> I'm afraid that changing the secret object does not cause the password to change inside the container. In the Bitnami containers, the password is set at first boot, so if you want to change the password, you will need to enter the container and perform the password change as well.

How do I do that? I tried go to bin/elasticsearch-reset-password but that didn't work. We changed the password through kibana ui. I was able to connect with port-forwarding to elasticsearch.  In the end I did something like this and it worked:
