### ISSUE TITLE
[bitnami/airflow] Task with Branch Operator is following both branch 

### ISSUE THREAD

**Issue by ramjeeanna** [bitnami/charts#29382]
### Name and Version

github/airflow-8.9.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. create Airflow DAG with Task Branch operator like below
pre_check = BranchPythonOperator(task_id='pre_validlate',
                                     python_callable=pre_validate_fn). 
graph is below:
init_report >> pre_check >> data_extraction >> end
pre_check >> remove_table

2. The function of branch operator, pre_validate_fn will decide which branch to follow, the code is below:
 follow_branch = 'data_extraction'
    if not kwargs['param']['delta']:
        follow_branch = ['data_extraction', 'remove_table']
    print(follow_branch)
    return follow_branch
  In we dont set detla, then it will remove as well as go for extraction
 In our case, if our input parameter is passed wit 'delta' as True even in that case, the condition is followed.
3. When such malfunctioned execution happens, the task remove_table is shown success in UI and table also deleted in logic.  But the respective task_id=remove_table logs folder is not created under the relevant run_id folder.

### What is the expected behavior?

1. if task is running, its log folder should have been created.
2.  param is given with values, it should not losing its data when parallel run is happening.

### What do you see instead?

1. task folder not created
2. kwargs params are not read properly

### Additional information

NA

**Comment by javsalgar** [comment]
Hi,

It is not clear to me if this is an issue in the Bitnami packaging of Airflow, but on the Airflow application itself. Did you report it upstream? Are you able to reproduce with the upstream airflow chart?
