### ISSUE TITLE
Harbor Chart - CSRF Key invalid

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#2939]
Harbor, v6.x

After installing the chart, I cannot log into harbor due a CSRF_Key invalid error. Looking in the core-envvars, I see that the string for the CSRF_KEY has been distorted. Replacing it with the string I had defined in the install resolves the issue. In the template for this secret, I see that it is not base64 encoding the value of the CSRF_KEY value, which I believe to be the issue.

1. Install the chart
2. Try to log into harbor

**Expected behavior**
The CSRF_KEY to be stored correctly.

**Comment by joancafom** [comment]
Hi @ajchiarello,

Thank you for your issue, I have created a PR #2954 that is intended to properly encode the Key again and solve the problem.

Thanks!
