### ISSUE TITLE
kafka on k8s

### ISSUE THREAD

**Issue by smuthugala** [bitnami/charts#29403]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

kafka k8s brokers (3pod) need to access via one external DNS with one port 

### What is the feature you are proposing to solve the problem?

Hi team,

I want to access kafkabrokers from outside the k8s cluster. how can I do it? because I need one DNS name to access my cluster outside.

as an example, bootstrap-server like "kafka-dev.kafka.abc.com" once I gave "kafka-dev.kafka.abc.com " URL its need to connect to my k8s running brokers (3 brokers pod running).

in this use case, what kind of config needs to be done in kafka server.properties and ingress?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
