### ISSUE TITLE
[bitnami/fluentd] Plugin installation

### ISSUE THREAD

**Issue by stevehipwell** [bitnami/charts#2941]
**Which chart**:
`fluentd` v1.2.5

**Is your feature request related to a problem? Please describe.**
Maintaining a separate _Docker_ image to enable custom plugins is painful and could be fixed withing this chart by allowing plugin installation as in `stable/fluentd`.

**Describe the solution you'd like**
Allow plugin configuration as part of this chart.

**Describe alternatives you've considered**
I've tested other charts with their own and other images and I can't get a working solution that doesn't require a custom _Docker_ image.

**Additional context**
I'm happy to create a PR for this.

**Comment by marcosbc** [comment]
Hi @stevehipwell, feel free to send the PR! We would be glad to review it.

I can see that the current stable/fluentd sets up a configmap with a script to install the plugins with `fluent-gem`, overwriting the `command`, and the end calls the `/run.sh` script for running the service.

In our case, the initialization logic is included in the `rootfs` of the container, so it would probably make more sense to add an environment variable for supporting plugins and executing `fluent-gem` in [`setup.sh`](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/setup.sh).

> I've tested other charts with their own and other images and I can't get a working solution that doesn't require a custom Docker image.

I guess you mean that you must execute the following command for the plugins to be installable, right?

    chmod -R g+rwX /opt/bitnami/fluentd/extensions

It should be feasible to add that logic to [`postunpack.sh`](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/postunpack.sh).

**Comment by mooncser** [comment]
Hi @marcosbc, 
Is there any update for the issue? It is not convenient to maintain another image when users install custom plugins.

**Comment by marcosbc** [comment]
Hi @mooncser, unfortunately not. Would you be up for contributing this feature to the chart? If not let us know and we'll create an internal task for tackling this (unfortunately I'm unable to provide any ETA for when we'd start looking into this).
