### ISSUE TITLE
grafana-loki: component=distributor path=write msg="write operation failed" - pod_template_hash=\"c6874b4ff\"}' has 16 label names; limit 15" org_id=fake

### ISSUE THREAD

**Issue by shaikzoheb-oi** [bitnami/charts#29446]
### Name and Version

bitnami/grafana-loki 3.1.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Deployed in AWS EKS and all the pods are running.

grafana-loki chart version - grafana-loki-4.6.16
app version - 3.1.1

EKS version: v1.29.3

Two challenges:

1. Log retention is not working
2. Write operation is failing with below error

Error:
```
level=error ts=2024-09-16T12:16:01.354075979Z caller=manager.go:49 component=distributor path=write msg="write operation failed" details="entry for stream '{app_kubernetes_io_component=\"distributor\", app_kubernetes_io_instance=\"loki\", app_kubernetes_io_managed_by=\"Helm\", app_kubernetes_io_name=\"grafana-loki\", app_kubernetes_io_part_of=\"grafana-loki\", app_kubernetes_io_version=\"3.1.1\", container_hash=\"docker.io/bitnami/grafana-loki@sha256:2ec59ce96a1d97ed43fef4285c2fdbfa55b7538d2e6aaa37534302fcd72e2172\", container_image=\"docker.io/bitnami/grafana-loki:3.1.1-debian-12-r4\", container_name=\"grafana-loki-distributor\", helm_sh_chart=\"grafana-loki-4.6.16\", host=\"ip-10-11-46-68.ec2.internal\", job=\"fluent-bit\", loki_gossip_member=\"true\", namespace_name=\"loki\", pod_name=\"loki-grafana-loki-distributor-c6874b4ff-26vhq\", pod_template_hash=\"c6874b4ff\"}' has 16 label names; limit 15" org_id=fake
```
### Are you using any custom parameters or values?

NO

### What is the expected behavior?

There shouldn't be any errors and the retention should work

**Comment by shaikzoheb-oi** [comment]
below is the configmap being used. It has retention enabled
`apiVersion: v1
data:
  loki.yaml: |-
    auth_enabled: false
    chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          addresses: dns+loki-memcachedchunks:11211
          consistent_hash: true
    common:
      compactor_address: http://loki-grafana-loki-compactor:3100
    compactor:
      compaction_interval: 10m
      delete_request_store: filesystem
      retention_delete_delay: 168h
      retention_delete_worker_count: 150
      retention_enabled: true
      working_directory: /bitnami/grafana-loki/loki/retention
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://loki-grafana-loki-querier:3100
    frontend_worker:
      frontend_address: loki-grafana-loki-query-frontend:9095
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      wal:
        dir: /bitnami/grafana-loki/wal
    limits_config:
      allow_structured_metadata: true
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 336h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-grafana-loki-gossip-ring
    querier:
      max_concurrent: 16
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          memcached_client:
            addresses: dns+loki-memcachedfrontend:11211
            consistent_hash: true
            max_idle_conns: 16
            timeout: 500ms
            update_interval: 1m
    query_scheduler:
      max_outstanding_requests_per_tenant: 32768
    ruler:
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /bitnami/grafana-loki/conf/rules
        type: local
    schema_config:
      configs:
      - from: "2020-10-24"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
      - from: "2024-03-12"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v12
        store: tsdb
      - from: "2024-04-23"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /bitnami/grafana-loki/loki/index
        cache_location: /bitnami/grafana-loki/loki/cache
        cache_ttl: 168h
      filesystem:
        directory: /bitnami/grafana-loki/chunks
      index_queries_cache_config: null
      tsdb_shipper:
        active_index_directory: /bitnami/grafana-loki/loki/tsdb-index
        cache_location: /bitnami/grafana-loki/loki/tsdb-cache
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s`

**Comment by shaikzoheb-oi** [comment]
@carrodher In order to increase the max number of labels in loki, is there any specific parameter do I need to use?

As in distributor logs, I see the same error repeatedly. Write operation failed, as it has exceeded the limit "15"

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by shaikzoheb-oi** [comment]
@carrodher From application point of view, I am sure that we are using nearly 20-25 labels. But loki is by default accepting 15 labels. That's why trying to increase that limit from "15" to "30"

In grafana doc, I've found an url which talks about same issue. As I am using bitnami/grafana-loki, that's why thought of raising it here.

https://grafana.com/docs/loki/latest/setup/upgrade/#changes-to-default-configuration-values-in-30

![image](https://github.com/user-attachments/assets/0802b340-73c9-4c7e-adbe-55fe482a0878)
![image](https://github.com/user-attachments/assets/52f55143-eb50-47b9-890c-4651aef78487)

Question here is, how can I increase the limits for labels in loki. Default value is "15", and I am trying to increase it to "30". If you can comment on this, it would be of great help.

validation.max-label-names-per-series

**Comment by shaikzoheb-oi** [comment]
@carrodher https://github.com/grafana/loki/blob/main/pkg/validation/limits.go

f.IntVar(&l.MaxLabelNamesPerSeries, "validation.max-label-names-per-series", 15, "Maximum number of label names per series.")

**Comment by shaikzoheb-oi** [comment]
Regarding retention, it looks like it's a limitation if we use local filesystem storage.

![image](https://github.com/user-attachments/assets/77c37a2e-877e-413f-8883-ececc1f2cd83)


https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki/#limitation

**Comment by shaikzoheb-oi** [comment]
@carrodher I've fixed that labels related error by increasing the max labels.

 limits_config:
      max_label_names_per_series: 30

Can you please comment on retention part? Like it won't support local filesystem storage?

https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki/#limitation
