### ISSUE TITLE
[bitnami/redis-cluster] Reason for using velero over the redis-cluster inbuilt backup system

### ISSUE THREAD

**Issue by Praveen-98cs** [bitnami/charts#29443]
### Name and Version

bitnami/redi-cluster latest

### What is the problem this feature will solve?

A way to backup and restore redis-cluster without using any 3rd party softwares.

### What is the feature you are proposing to solve the problem?

In the documentation of the redis-cluster, you have recommended using `velero` for backing up and why can't we use the redis-cluster in built `snapshot` and maybe make a way to restore it when we need? I understand since this is redis-cluster and we have multiple nodes with persistent volumes to be backed up and restoring process will be a bit tedious. but is there a way you can suggest to make this possible just by relying with redis-cluster backing up method? 

### What alternatives have you considered?

Can we try using `RIOT` for this purpose?
https://github.com/redis/riot

**Comment by javsalgar** [comment]
Hi!

We recommend Velero because it is part of our Tanzu ecosystem. Indeed, it is potentially possible to use other methods, so feel free to try `riot` or other methods.

**Comment by Praveen-98cs** [comment]
> Hi!
> 
> We recommend Velero because it is part of our Tanzu ecosystem. Indeed, it is potentially possible to use other methods, so feel free to try `riot` or other methods.

Thanks will have a look at it!
