### ISSUE TITLE
[bitnami/spark] Issue running spark client tasks

### ISSUE THREAD

**Issue by gnunns** [bitnami/charts#2946]
Hi,

After deploying spark, 1 master 5 workers using the bitnami docker image and helm charts on a kubernetes cluster I am having issues running jobs successfully.  Kicking off a task either with spark submit or from a python spark context will connect to the master and start the executors on all workers, the executor apps then exit with code 1 exitStatus 1.

Spark Helm version: 1.2.28
Spark appVersion: 2.4.4

Steps to reproduce

1) Launch job

`kubectl run --namespace fuzzyland spark-client --rm --tty -i --restart='Never'     --image docker.io/bitnami/spark     -- spark-submit --master spark://10.244.5.71:30391     --class org.apache.spark.examples.SparkPi     --deploy-mode client     examples/jars/spark-examples_2.11-2.4.4.jar 1000`

2) Tail logs on spark workers.  The spark workers will continue to start, exit and restart the app indefinitely with very little error information.

spark-worker-0 spark-worker 20/06/26 21:47:58 INFO Worker: Asked to launch executor app-20200626214720-0000/91 for Pi
spark-worker-0 spark-worker 20/06/26 21:47:58 INFO SecurityManager: Changing view acls to: spark
spark-worker-0 spark-worker 20/06/26 21:47:58 INFO SecurityManager: Changing modify acls to: spark
spark-worker-0 spark-worker 20/06/26 21:47:58 INFO SecurityManager: Changing view acls groups to: 
spark-worker-0 spark-worker 20/06/26 21:47:58 INFO SecurityManager: Changing modify acls groups to: 
spark-worker-0 spark-worker 20/06/26 21:47:58 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark); groups with view permissions: Set(); users  with modify permissions: Set(spark); groups with modify permissions: Set()
spark-worker-0 spark-worker 20/06/26 21:47:58 INFO ExecutorRunner: Launch command: "/opt/bitnami/java/bin/java" "-cp" "/opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=34857" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@jupyter-gnunns:34857" "--executor-id" "91" "--hostname" "192.168.7.24" "--cores" "2" "--app-id" "app-20200626214720-0000" "--worker-url" "spark://Worker@192.168.7.24:34896"
spark-worker-0 spark-worker 20/06/26 21:47:59 INFO Worker: Executor app-20200626214720-0000/91 finished with state EXITED message Command exited with code 1 exitStatus 1

Any assistance is greatly appricated.

Thanks

Gavin

**Comment by dani8art** [comment]
It seems to be due to `--deploy-mode client`, I've tried without this and it works, could you give a try with the following

```bash
$ kubectl run --namespace fuzzyland spark-client --rm --tty -i --restart='Never' --image docker.io/bitnami/spark -- spark-submit --master spark://10.244.5.71:30391 --class org.apache.spark.examples.SparkPi --deploy-mode cluster examples/jars/spark-examples_2.11-2.4.4.jar 1000
```

**Comment by gnunns** [comment]
I was able to resolve this issue by setting the following in the spark conf. Because I was kicking the job from a jhub notebook it was running as --deploy-mode client. If its possible to run the driver on the cluster and get the results back to the notebook I would love to know that trick.

The problem seemed to be the driver was running on my notebook in client mode and the spark workers were not able to resolve the address back to that pod.  By setting the spark.driver.host to the pod that was submitting the task the job was able to complete and return a result to the notebook.

```
conf = pyspark.SparkConf()
conf.setMaster("spark://<ip-addr>:<port>")
conf.set("spark.driver.host", host_ip)
```

Thanks

Gavin

**Comment by dani8art** [comment]
Hi @gnunns thank you so much for the contribution, we will take a look to it and try to add it to our chart.

**Comment by jaken551** [comment]
@gnunns, which image are you running in jhub while using this helm chart? I tried your fix but end up with 
`Exception: Python in worker has different version 3.6 than that in driver 3.8, PySpark cannot run with different minor versions.Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.`

**Comment by dani8art** [comment]
Hi @gnunns currently this chart is only prepare to be run with bitnami images, you could get some errors and it could not work fine when using other images. 

Thanks!

**Comment by jpellman** [comment]
There seem to be several redundant issues related to this problem (https://github.com/bitnami/charts/issues/7001, https://github.com/bitnami/charts/issues/1626, https://github.com/bitnami/charts/issues/1775, https://github.com/bitnami/charts/issues/2946

From my research, I believe that one issue here is that the block manager port needs to be set to a specific port for communication between the driver that runs in a notebook and the executors/workers (see https://github.com/bitnami/charts/issues/1626#issuecomment-946723115).

**Comment by Mauraza** [comment]
Hi @jpellman,

Did you check these comments https://github.com/bitnami/charts/issues/2883#issuecomment-703327091 https://github.com/bitnami/charts/issues/2883#issuecomment-703352163?

**Comment by lamyalfred** [comment]
Hello,

I take the liberty of reopening this ticket because I am also having difficulties connecting to my Spark cluster from Jupyter.

I really thought I had found the solution with what jpellman suggested, but now I get the following error message:

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [1], in <module>
     10 def mod(x):
     11     return x % 2
---> 12 rdd = sc.parallelize(range(1000)).map(mod).take(10)

File /opt/conda/lib/python3.9/site-packages/pyspark/rdd.py:1568, in RDD.take(self, num)
   1565         taken += 1
   1567 p = range(partsScanned, min(partsScanned + numPartsToTry, totalParts))
-> 1568 res = self.context.runJob(self, takeUpToNumLeft, p)
   1570 items += res
   1571 partsScanned += numPartsToTry

File /opt/conda/lib/python3.9/site-packages/pyspark/context.py:1227, in SparkContext.runJob(self, rdd, partitionFunc, partitions, allowLocal)
   1223 # Implementation note: This is implemented as a mapPartitions followed
   1224 # by runJob() in order to avoid having to pass a Python lambda into
   1225 # SparkContext#runJob.
   1226 mappedRDD = rdd.mapPartitions(partitionFunc)
-> 1227 sock_info = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
   1228 return list(_load_from_socket(sock_info, mappedRDD._jrdd_deserializer))

File /opt/conda/lib/python3.9/site-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /opt/conda/lib/python3.9/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (10.244.0.84 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2403)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2352)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2351)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2351)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1109)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1109)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1109)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2591)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2533)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2522)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:898)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2214)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2235)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2254)
	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Maybe I misinterpreted the explanations.

I'm using the HELM map provided [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html). I added the expected configuration in my config.yaml:
![image](https://user-images.githubusercontent.com/99251037/152963020-d5ba2d5c-0665-40a6-9777-34af47095e75.png)

During the installation, I install the HELM chart then I create the headless service resource:
![image](https://user-images.githubusercontent.com/99251037/152963083-106d8ee1-0369-43cd-b3ef-7d85c3cf0728.png)

Here is the headless-svc-jupyter.yaml file :
![image](https://user-images.githubusercontent.com/99251037/152963254-b559275f-7b28-473f-9b26-b8188ccb5093.png)

I run this command from Jupyter, and get the error message given below :
![image](https://user-images.githubusercontent.com/99251037/152963645-3e2d4d43-6030-4ac9-b6bf-d5cfbe16348c.png)

Can someone explain to me what I'm doing wrong?

**Comment by MainRo** [comment]
@jpellman how did you modify the extra_pod_config option? Did you:

- Override the whole configuration with the "hub.existingConfigmap" variable
- Used the "hub.configuration" variable (I do not understand how to use it)
- something else?
