### ISSUE TITLE
[bitnami/keydb]  Add support for cluster mode for keydb

### ISSUE THREAD

**Issue by Onewaysidewalks** [bitnami/charts#29481]
### Name and Version

bitnami/keydb all

### What is the problem this feature will solve?

The current Bitnami KeyDB Helm chart does not provide built-in support for "Cluster" mode (partitioned masters). Users who wish to use this mode have to manually configure it, which complicates the setup and maintenance. Without native support, it's harder to deploy, upgrade, and scale the KeyDB cluster in Kubernetes environments, limiting high availability and fault tolerance. It is a. common setup most redis clients in production run, when configured to do so.

### What is the feature you are proposing to solve the problem?

I propose adding support for cluster mode in the KeyDB Helm chart. This feature should include configuration options for enabling and managing master partitioning across nodes. Documentation on how to set up, scale, and monitor this replication mode should also be provided to ensure users can take full advantage of KeyDB’s high-availability capabilities, which can be found [here](https://docs.keydb.dev/docs/cluster-tutorial/).

### What alternatives have you considered?

The only alternatives right now is to use the "worse-performing" redis helm chart, as it supports the cluster mode correctly.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by yaman** [comment]
Hey there. I am also interested in cluster support(active-active, multi-master). I will be modifying bitnami/keydb helm chart in the coming days(most probably starting today). I will share my progress here.

**Comment by Skaronator** [comment]
I'm also interested in this

**Comment by Onewaysidewalks** [comment]
@yaman did you end up implementing this? (would love to see the resulting chart etc.)
