### ISSUE TITLE
Also, now that it was implemented in the containers, you could take the advantages of `extraEnvVars` in `bitnami/mariadb` chart and modify the collations. Please try to add this to your helm deployments.

### ISSUE THREAD

**Issue by jorgeantoniosandoval1** [bitnami/charts#2953]
Also, now that it was implemented in the containers, you could take the advantages of `extraEnvVars` in `bitnami/mariadb` chart and modify the collations. Please try to add this to your helm deployments.

```console
  --set mariadb.master.extraEnvVars[0].name=MARIADB_COLLATE,mariadb.master.extraEnvVars[0].value=utf8mb4_unicode_ci
  --set mariadb.master.extraEnvVars[1].name=MARIADB_CHARACTER_SET,mariadb.master.extraEnvVars[1].value=utf8mb4
```

_Originally posted by @dani8art in https://github.com/bitnami/charts/issues/2475#issuecomment-640549055_

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure what do you mean with this ?
  The feature is implemented in the chart https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml#L262, so you can use what @dani8art indicated.
