### ISSUE TITLE
[harbor] Trivy response very slow in resourcesPreset: nano

### ISSUE THREAD

**Issue by owanio1992** [bitnami/charts#29546]
### Name and Version

bitnami/harbor:23.0.3

### What architecture are you using?

arm64

### What steps will reproduce the bug?

relate issue 
https://github.com/bitnami/containers/issues/72534

trivy should give nano option

### What do you see instead?

trivy response slow

```
I have no name!@harbor-core-7b859fc658-ql85j:/tmp$ ./curl http://harbor-trivy:8080/api/v1/metadata
real    0m7.151s
user    0m0.000s
sys     0m0.004s
```

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
