### ISSUE TITLE
[bitnami/opensearch]: Replace open.co links with opensearch.org

### ISSUE THREAD

**Issue by lindhe** [bitnami/charts#29547]
### Name and Version

bitnami/opensearch 1.3.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Click the links in the README that lead to open.co and see that the site is broken.

### What is the expected behavior?

I expect to end up with the official documentation for OpenSearch.

### What do you see instead?

A broken site. I presume it's an old site for OpenSearch.

### Additional information

If I can figure out the corresponding pages on the real site, I'll make a PR to fix this.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
