### ISSUE TITLE
Data is stored for a maximum of 2 hours

### ISSUE THREAD

**Issue by SerheoReutty** [bitnami/charts#29558]
### Name and Version

bitnami/grafana-loki

### What architecture are you using?

amd64

### What steps will reproduce the bug?

default installation

### Are you using any custom parameters or values?

default

### What is the expected behavior?

Long-term storage of logs

### What do you see instead?

Data is stored for a maximum of 2 hours

### Additional information

Hello. I installed bitnami-grafana-loki without any additional parameters. 
The logs are saved for the last 2 hours. Then it's like a cleanup happens. I don't understand why. Persistance is enabled. Only 200 megabytes of the available 8 gigabytes are used on PV. 
What could be the problem, maybe I'm missing something?

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a specific scenario that is not easy to reproduce on our side.

If you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by ricard0javier** [comment]
Hi @carrodher, I'm facing the same issue. I found that the default configuration of the chart does not persist logs when using the filesystem as storage. The behaviour is described in the [documentation ](https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki/#persistence) 

> This chart does not function fully when using local filesystem as a persistence store. When using a local filesystem as a persistence store, querying will not be possible (or limited to the ingesters' in-memory caches). For a fully functional deployment of this helm chart, an object storage backend is required.

The logs we are observing are fetched from the cache. I'm with this chart I will be pushed to use something like S3 to use more than the cache to store the logs.

**Comment by juan131** [comment]
Hi everyone! As @ricard0javier mentioned that's a known limitation of the chart

A real object storage system (such as S3 or GCS) can be configured by adapting the `storage_config` in Loki configuration:

- https://github.com/bitnami/charts/blob/main/bitnami/grafana-loki/values.yaml#L166-L193

Find more info at:

- https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/
