### ISSUE TITLE
[bitnami/kafka] Enable configuration for StatefulSet revisionHistoryLimit 

### ISSUE THREAD

**Issue by josephrodriguez** [bitnami/charts#29569]
### Name and Version

bitnami/kafka 30.1.4

### What is the problem this feature will solve?

For all StatefulSet in the chart there is not way to configure the revisionHistoryLimit specification property. 

### What is the feature you are proposing to solve the problem?

Include a revisionHistoryLimit parameter in values.yaml with a default value that can be redefined on chart value override. This value is going to be use to set the property on the specific StatefulSet for controllers and brokers

### What alternatives have you considered?

Actually the workaround it's a combination with Kustomization creating patches operations to set the value for all StatefulSet , kafka-brokers and kafka-controllers.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR adding the value and the team will check it.

**Comment by josephrodriguez** [comment]
Hi @javsalgar ,

Sure, I'll prepare a pull request for this feature request and let know here.
