### ISSUE TITLE
[bitnami/redis-cluster] Unable to set resources using Helm's --set

### ISSUE THREAD

**Issue by michael-bouvy** [bitnami/charts#2956]
**Which chart**:

`bitnami/redis-cluster 3.1.1`

**Describe the bug**

When setting Redis resources using `--set` CLI param, the value is not rendered in the templates.

**To Reproduce**

1. `helm template --set redis.resources.requests.memory=1024Mi redis-cluser bitnami/redis-cluster`
2. Check output:

```
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
```

Setting values within `values.yaml` works fine.

**Expected behavior**

Being able to set resources values using `--set`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.1.2
```

- Output of `kubectl version`:

```
Client: v1.18.3
Server: v1.16.6-aliyun.1
```

**Comment by miguelaeh** [comment]
Hi @michael-bouvy ,
Thank you very much for your comment, try executing `helm dependencies update` to bring the latest common chart we use for common functions.

**Comment by michael-bouvy** [comment]
Hi @miguelaeh, sorry for late reply ; I think running the dependencies update command is not applicable in this context, as I am using the remote chart with a standalone helm command, without any chart config.

**Comment by javsalgar** [comment]
Hi,

This is a warning due to the resources value not being set as `{}` by default. In this PR I set the value https://github.com/bitnami/charts/pull/3149
