### ISSUE TITLE
[bitnami/postgresql] How to enable FIPS on postgresql bitnami chart?

### ISSUE THREAD

**Issue by srinivasgowda097** [bitnami/charts#29585]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

we have built a custom bitnami image (using UBI9 with FIPS enabled) , now we would like to use this custom image with latest bitnami chart , need to change md5 to scram-sha-256 in pg_hba.conf file

### What is the feature you are proposing to solve the problem?

Can you please help us with easy way to change md5 to scram-sha-256 in pg_hba.conf file ,(Is there any extra environment that we can set in the bitnami containers ?)

**Comment by carrodher** [comment]
The Bitnami Application Catalog (OpenSource) is built on Debian 12. As part of VMware, Bitnami also provides a custom catalog of containers and Helm Charts based on various base images, including Debian 11 & 12, PhotonOS 5, Ubuntu 22.04 & 24.04, and Red Hat UBI 8 & 9. You can explore these options via the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

Beyond the variety of distributions, the VMware Tanzu Application Catalog offers enterprise-grade features such as FIPS, VEX, SBOM, and SLSA3. If you have any further questions, feel free to reach out.
