### ISSUE TITLE
[bitnami/contour] Contour chart should support deploying with an AWS NLB

### ISSUE THREAD

**Issue by geota** [bitnami/charts#2960]
**Which chart**:
bitnami/countour 1.0.0 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

The chart should support deploying with an NLB:
https://projectcontour.io/guides/deploy-aws-nlb/
https://github.com/projectcontour/contour/tree/master/examples/contour#deploying-with-host-networking-enabled-for-envoy

**Describe alternatives you've considered**
I considered not using NLB.

**Additional context**
n/a

**Comment by javsalgar** [comment]
Hi! Thank you very much for your feedback! We will take a look to the PR and provide feedback very soon :)
