### ISSUE TITLE
[bitnami/etcd] Add etcd-defrag CronJob for Etcd Maintenance

### ISSUE THREAD

**Issue by mikyll** [bitnami/charts#29619]
### Name and Version

bitnami/etcd

### What is the problem this feature will solve?

Over time, as DB keys are added, updated, and deleted, the etcd database becomes **fragmented**. This fragmentation can result in inefficient use of disk space, with consequent degraded performance. In our case scenario (etcd deployed with apisix) this eventually caused the etcd nodes to crash.

According to the [v3.5 docs](https://etcd.io/docs/v3.5/op-guide/maintenance/), etcd needs **periodic maintenance**.

### What is the feature you are proposing to solve the problem?

To solve the fragmentation issue, etcd provides the `etcdctl defrag` command, which blocks the system from reading and writing data if the etcd member is running.

**Feature request**: add a chart template to include a **CronJob** which performs **automatic periodic etcd defragmentation**, possibly configurable via parameters.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request! I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.
