### ISSUE TITLE
[bitnami/wordpress] Allow using nginx instead of apache

### ISSUE THREAD

**Issue by xorinzor** [bitnami/charts#29615]
### Name and Version

bitnami/wordpress

### What is the problem this feature will solve?

Apache performs significantly slower then Nginx. Bitnami already offers a `wordpress-nginx` container, but from my testing this does not appear to be as simple as changing `image.repository` to `bitnami/wordpress-nginx` (with the appropriate `image.tag`).

### What is the feature you are proposing to solve the problem?

Improved performance by using nginx

**Comment by javsalgar** [comment]
Hi,

Probably you may be able to make it work if you set:

```
containerSecurityContext:
  runAsGroup: 0
  readOnlyRootFilesystem: false
```
