### ISSUE TITLE
[bitnami/postgresql-ha] Postgres HA loosing data after restart

### ISSUE THREAD

**Issue by antikilahdjs** [bitnami/charts#29623]
### Name and Version

bitnami/postgres-ha

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the charts as default 
2. Add persistence as true
3. Using the docker.io/bitnami/postgresql-repmgr:14.7.0-debian-11-r5
### Are you using any custom parameters or values?
```
extendedConf: |-
    shared_buffers = 8GB
    effective_cache_size = 24GB
    maintenance_work_mem = 2GB
    work_mem = 4MB
    checkpoint_completion_target = 0.9
    wal_buffers = 64MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    huge_pages = try
    min_wal_size = 2GB
    max_wal_size = 8GB
    max_worker_processes = 30
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 30
    max_parallel_maintenance_workers = 4
    max_replication_slots = 10
    max_wal_senders = 20
```
### What is the expected behavior?

When the postgres restart the data needs to be persists or am wrong ? 

### What do you see instead?

I have a large database with 3 instances as HA so when the instance needs to be restarted all data in the path /bitnami/postgresql/data is gone

### Additional information

I am sorry but am not found anything related about it and of course am using the persistence as well

**Comment by javsalgar** [comment]
Hi!

Are you able to reproduce the issue with a small database? We would like to reproduce it on our side.
