### ISSUE TITLE
[bitnami/mysql]  How to resync mysql-secondary data from the mysql-primary ?

### ISSUE THREAD

**Issue by dellnoantechnp** [bitnami/charts#29642]
### Name and Version

bitnami/mysql 9.23.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

How to recreate `mysql-secondary` master slave synchronization? 

When my `mysql-secondary` slave synchronization failed, I deleted its pvc data, because it was a long time ago, and then planned to use a slave node with empty data to fully synchronize data from the `mysql-primary` node. 

I expected that bitnami/mysql had considered this part of the demand and implementation, but I actually found that this was not in line with my expectations. 

The root password of the `mysql-secondary` instance was also unknown. 
Although the new slave node could be seen using the `show slave hosts` command on the master, there were only increasing `mysql-relay-bin.000002` logs in the secondary data directory, and the binlog was not updated.

```shell
>_ mysql -uroot -p******
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

How to do that ?

### What do you see instead?

mysql-secondary  couldn't  to use.

### Additional information

Is my usage incorrect ？？？

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
