### ISSUE TITLE
JasperReports

### ISSUE THREAD

**Issue by huang-tianwen** [bitnami/charts#29648]
### Name and Version

bitnami/jasperreports

### What is the problem this feature will solve?

Hi, I thought there was a charts for jasperreports. Where i can find the old charts?

### What is the feature you are proposing to solve the problem?

If deprecated, maybe move it to another repo?

### What alternatives have you considered?

move deprecated charts to other repo so user can still using the charts

**Comment by carrodher** [comment]
The bitnami/jasperreports Helm chart was deprecated back in February. You can see all the previous versions at https://hub.docker.com/r/bitnamicharts/jasperreports, but there won't be new releases.
