### ISSUE TITLE
Contour chart has no report/category entry for onboarding with the IBM catalog

### ISSUE THREAD

**Issue by gmendel** [bitnami/charts#2965]
**Which chart**:
contour 1.5.1

**Describe the bug**
This chart is not in the Bitnami report: https://bitnami.com/library/ibm_charts_report.json -> lacking category to be onboarded with.

**To Reproduce**

**Comment by rafariossaa** [comment]
Hi,
  We fixed a issue on this.
   Could you check it again ?

**Comment by gmendel** [comment]
looks good

**Comment by rafariossaa** [comment]
Hi, 
 Thanks, in that case I am not reopening this issue.
