### ISSUE TITLE
Include additional labels in common.labels.matchLabels

### ISSUE THREAD

**Issue by alexwhiteoval** [bitnami/charts#29662]
### Name and Version

bitnami/common 2.x.x

### What is the problem this feature will solve?

Currently the _common.labels.matchLabels_ helper only allows the inclusion of the following labels:

- app.kubernetes.io/instance
- app.kubernetes.io/name

No additional labels can be added.

When applying external network policies to custom podLabels, the podLabels are not included in the service _spec.selector_ config as the _matchLabels_ excludes them, this breaks the network policy and blocks access.

### What is the feature you are proposing to solve the problem?

Including other labels passed into the customValues property would increase the ability to use custom labels for network policies.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
