### ISSUE TITLE
[bitnami/elasticsearch] OOM on data/master

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#2967]
This is not a bug, so apologies, but I'm getting repeated OOM shutdowns on master and data containers. This is very shortly after startup and there's almost no usage of elasticsearch, even when the cluster is in operation. It's not like I'm providing a huge amount of memory, but 512M for the master and 1.5G for data, and there should be nearly no data. Any suggestions? Too little memory? Is there some config on elasticsearch I need to add so it doesn't open up consuming so much memory?

Thanks for any help.

**Comment by dani8art** [comment]
Hi @zenbones , 512M might be an insufficient amount of memory for elasticsearch since we have this https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables `ELASTICSEARCH_HEAP_SIZE=1024m` by default. Maybe you can try to adjust this value to fit your requirements.

**Comment by zenbones** [comment]
I did adjust the value, and checked that it gets to the container as the proper env value, and checked that the java process is using that value for xms and xmx, and it's all correct. And then the containers OOM. Maybe this is an elastic search thing where it just needs a larger minimum heap, but it does seem like a lot for a little.

**Comment by dani8art** [comment]
> Maybe this is an elastic search thing where it just needs a larger minimum heap

Regarding that elasticsearch is built in java, I would bet on this phrase. You only have to see that default value is `1024m`. Here they wrote a very good explanation on how to set production environment heap size and physical memory https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

**Comment by zenbones** [comment]
Thanks for the reference. It's a bit harsh, btw, to blame this on the JVM. There's overhead for working under the virtual machine, but on a server application where there's a single JVM in a relatively unconstrained environment, the cost is not particularly relevant. What is relevant is the way elasticsearch works, which is going to chew RAM no matter what it's written in. That speed is sitting on the indexing scheme, and the cost trade-off there is memory for speed. This is why I usually stay way, but then we'd have to talk FluentD/FluentBit and logging in kubernetes environments... it is what it is.

**Comment by andresbono** [comment]
Hi @zenbones, this issue has been stale for a while. Is there anything that requires our attention or anything we can help you with? Was the reference we shared useful for you?

**Comment by zenbones** [comment]
Yes, it was. Just needed to increase the allowed memory. Thanks.
