### ISSUE TITLE
[bitnami/thanos] PR #29673 is a breaking change for existing deployments

### ISSUE THREAD

**Issue by bootc** [bitnami/charts#29749]
### Name and Version

bitnami/thanos 15.7.26

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Deploy a previous version of the chart, e.g. 15.7.25, with `--set storagegateway.enabled=true` or equivalent
2. Upgrade to 15.7.26

### Are you using any custom parameters or values?

`storagegateway.enabled=true` is the relevant setting which enables the thanos-storegateway StatefulSet. 

### What is the expected behavior?

The upgrade should succeed without manual intervention.

### What do you see instead?

```
cannot patch "thanos-storegateway" with kind StatefulSet: StatefulSet.apps "thanos-storegateway" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

**Comment by bootc** [comment]
This is the PR from the issue title: #29673

**Comment by dgomezleon** [comment]
Hi @bootc 

Thanks for the heads up. We will revert the change.
