### ISSUE TITLE
[bitnami/postgresql-ha 11.9.7] psql version mismatch with server version

### ISSUE THREAD

**Issue by juniperlorelei12** [bitnami/charts#29750]
### Name and Version

bitnami/postgresql-ha 11.9.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Checkout postgresql-ha version 11.9.7 chart
2. Install the chart
3. Wait for pods to spin up
4. Exec into pgpool pod using `kubectl exec -it <pgpool-pod-name> -- psql --host <app-name>-postgresql-ha-pgpool -U postgres -d postgres`
5. Immediately be greeted by the warning: 
```
psql (14.9, server 15.4)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
```
6. type \z
7. Get the following error:
```
ERROR:  operator is not unique: unknown || "char"
LINE 16:            E' (' || polcmd || E'):'
                          ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```

### Are you using any custom parameters or values?

The only change I made to values.yaml is more than likely irrelevant to the issue. Regardless, I made lines 1070-1072 the following:
```yaml
  customUsers:
    usernames: "jiradbuser"
    passwords: "jiradbpassword"
```
because my client wants to use Postgres with Jira. This is also why I'm using a specific version of the chart. As far as I can tell, 11.9.7 was the last version of these Helm charts to use Postgres 15, which is a prerequisite for Jira.

### What is the expected behavior?

I expect not to be greeted by a warning that explicitly says "some features might not work" on a fresh install.
I also expect to see a list of all user permissions in response to \z, instead of an error.

### What do you see instead?

I'll repeat myself, as required.
When logging into Postgres, I see the warning:
```
psql (14.9, server 15.4)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work
```
When I run the command `\z`, I see the following error INSTEAD of a list of user permissions:
```
ERROR:  operator is not unique: unknown || "char"
LINE 16:            E' (' || polcmd || E'):'
                          ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```
I'm not certain, but I suspect that this issue is causing me cascading issues with my Jira setup.
As mentioned, I'm trying to stand up Postgres to connect to Jira, and after the "Database setup" page during the Jira setup wizard, I start to get HTTP 500 errors

### Additional information

I've tried researching this issue and all of the solutions say to either uninstall and reinstall Postgres, or just point to a different version of psql that's already installed. Obviously, I do not control the version of psql that comes with this helm chart
I've also tried downgrading Postgresql to version 14, which does get rid of the warning. However, this is not a solution because Jira doesn't support Postgresql version 14, only 15.

How do I upgrade psql to version 15? (If that is the best solution, that is)

**Comment by jotamartos** [comment]
Thanks for taking the time to report this. We are going to work on updating the client version included in the pgpool image. Sorry for the inconvenience.

**Comment by jotamartos** [comment]
This PR updates the pgpool image in the chart to include a newer version 

```
root@a0f801fdcd41:/# psql --version
psql (PostgreSQL) 17.0
root@a0f801fdcd41:/# 
```

**Comment by juniperlorelei12** [comment]
Awesome, thank you so much! I don't suppose there's a way to modify pgpool to include a _specific_ version of psql? I have a requirement to run Postgresql v15. Previously psql was running at v14 and this new PR bumps it all the way to v17. Ideally, I'd like to have Postgresql v15 and psql v15

**Comment by jotamartos** [comment]
>I don't suppose there's a way to modify pgpool to include a specific version of psql?

No, sorry. pgpool includes a fixed version of the client binary.

>Ideally, I'd like to have Postgresql v15 and psql v15

We updated the client library to the latest branch. According to the documentation, any new major version should work with the previous ones. Take a look at the notes section here: https://www.postgresql.org/docs/17/app-psql.html

**Comment by juniperlorelei12** [comment]
> > Ideally, I'd like to have Postgresql v15 and psql v15
> 
> We updated the client library to the latest branch. According to the documentation, any new major version should work with the previous ones. Take a look at the notes section here: https://www.postgresql.org/docs/17/app-psql.html

So you're telling me to use the newest version of the charts to get psql version 17, then edit postgresql.image.tag to downgrade to Postgres 15? Is that all I have to do or are there other considerations when downgrading Postgres for this chart?

**Comment by jotamartos** [comment]
I suggest you use the latest version of the chart that includes PostgreSQL 16.x. If that's not possible, you can update your deployment to use the latest tag of the bitnami/pgpool image (4.5.4-debian-12-r2) so you get the PostgreSQL 17.x client.
