### ISSUE TITLE
MARIADB GALERA HELM CHART FOR MARIADB IMAGE VERSION 10.6.19

### ISSUE THREAD

**Issue by viju2008** [bitnami/charts#29772]
### Name and Version

bitnami/mariadb:10.6.19

### What is the problem this feature will solve?

Dear Sir,

Request to provide MARIADB GALERA HELM CHART FOR MARIADB IMAGE VERSION 10.6.19

It is the latest stable version in 10.6.x series of MARIADB 

Regards

### What is the feature you are proposing to solve the problem?

UPDATED HELM CHART

**Comment by carrodher** [comment]
Helm charts only support a single major version, in this case, the latest LTS version which is 11.4.

In containers, you can find all the branches supported by the upstream project, see https://github.com/bitnami/containers/tree/main/bitnami/mariadb-galera. There you can see the latest version for branch 10.6 is 10.6.19 (https://github.com/bitnami/containers/pull/71906).

You can try using that branch with the Helm chart by overriding [the `image.tag` parameter](https://github.com/bitnami/charts/blob/main/bitnami/mariadb-galera/values.yaml#L91). However, please note that this configuration hasn’t been tested by our automated test and release pipeline, so we cannot guarantee it will work or provide support for any issues that may arise.

**Comment by viju2008** [comment]
As MARIADB still supports 10.6.X version and is providing Long Term Support for the same. Request to please provide a chart of MARIADB 10.6.19 LTS VERSION

![image](https://github.com/user-attachments/assets/caccb188-75f8-4187-bb94-368880dfb364)

Please find link from MARIADB WESBITE

https://mariadb.com/kb/en/mariadb-10-6-19-release-notes/

**Comment by viju2008** [comment]
Dear Sir,

Request to please provide the helm chart for mariadb 10.6.19

**Comment by javsalgar** [comment]
As my colleague mentioned

> You can try using that branch with the Helm chart by overriding [the image.tag parameter](https://github.com/bitnami/charts/blob/main/bitnami/mariadb-galera/values.yaml#L91). However, please note that this configuration hasn’t been tested by our automated test and release pipeline, so we cannot guarantee it will work or provide support for any issues that may arise.
