### ISSUE TITLE
[bitnami/mongodb] support MongoDB 8.0

### ISSUE THREAD

**Issue by SIMULATAN** [bitnami/charts#29788]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

Being unsure about the compatibility with the newest MongoDB release. Having to manually override the image version.

### What is the feature you are proposing to solve the problem?

Bump the appVersion to 8.0.0.
There's already a Bitnami image for it since https://github.com/bitnami/containers/commit/2586ee8444b4fdb1d3e0e5415c080502315e9c50

Relevant patch notes:
- https://www.mongodb.com/docs/manual/release-notes/8.0-compatibility/
- https://www.mongodb.com/docs/manual/release-notes/8.0/

### What alternatives have you considered?

Simply "yolo"-ing the upgrade - MongoDB is known to be relatively lenient when it comes to upgrades, no dump-and-restore style upgrade as with PostgreSQL is required.

**Comment by gongomgra** [comment]
Hi @SIMULATAN,

Thanks for using Bitnami. We are still working on a fully working solution for the MongoDB 8.0 container. After that, we will continue working on updating the Helm chart and its other related assets. We will keep you posted.

**Comment by gongomgra** [comment]
Hi @SIMULATAN,

We have released a new image solving some initialization issues. You can find more details on the implemented changes at https://github.com/bitnami/containers/pull/73130

We will continue working on updating the Helm chart for both MongoDB and the other assets using it as a dependency.

**Comment by gongomgra** [comment]
Hi @SIMULATAN,

Just a quick note to let you know we have just released a new major version of our MongoDB Helm chart (version 16.0.0) including MongoDB image 8.0.0

https://github.com/bitnami/charts/pull/29801
