### ISSUE TITLE
[bitnami/keycloak] Initialize Helm Deployment With Client Credentials Grant For Config CLI

### ISSUE THREAD

**Issue by a-priestley** [bitnami/charts#29784]
### Name and Version

bitnami/keycloak 23.0.0

### What is the problem this feature will solve?

The problem I am trying to solve is the fact that we cannot activate OTP MFA for the admin Keycloak account without breaking the config CLI functionality.
By default, the CLI authenticates using password grant, but when multifactor authentication is added on top of it, the service can no longer authenticate.

### What is the feature you are proposing to solve the problem?

In the CLI documentation, there is mention of using client credentials as opposed to password, but for this, a client secret and service account needs to be created for the admin_cli client. This can be done in the admin console of course, but is it possible to initialize the helm chart with it already in place?
It's a "chicken and the egg" problem. We can configure our .yaml with a `keycloakConfigCli.configuration` block, defining the admin_cli client with the necessary attributes, but a basic password grant is required for this to work initially. After the first run, we then need to rewrite the .yaml to specify that the CLI will be authenticating using client credentials from then on. Preferably, we want to be able to create the desired state in one shot.

### What alternatives have you considered?

If it isn't possible to configure the bitnami/keycloak chart in this way, is there any advice for creating the desired state using init containers, or other methods?

Thanks!

**Comment by dgomezleon** [comment]
Hi @a-priestley 

The chart does not support MFA automatically.  

If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
