### ISSUE TITLE
Kube-Prometheus: envFrom: Invalid value: "null": spec.containers[0].envFrom in body must be of type array

### ISSUE THREAD

**Issue by Poil** [bitnami/charts#29799]
### Name and Version

bitnami/kube-prometheus 9.6.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Upgrade stack 9.5.* to 9.6.3

### What do you see instead?

one or more objects failed to apply, reason: 
```
Prometheus.monitoring.coreos.com "kubeprometheus-kube-promet-prometheus" is invalid: [spec.containers[0].envFrom: Invalid value: "null": spec.containers[0].envFrom in body must be of type array: "null", spec.containers[0].env: Invalid value: "null": spec.containers[0].env in body must be of type array: "null"]
```
### Additional information

https://github.com/bitnami/charts/pull/29022/files#diff-88e5abdbe6412745a97bdea4ae5c917597dc4d29a513b8049e3ac488c5dadf43

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
