### ISSUE TITLE
Cert-gen runs even if envoy.tlsExistingSecret and contour.tlsExistingSecret are specified

### ISSUE THREAD

**Issue by jamesggraf-m1** [bitnami/charts#29809]
### Name and Version

bitnami/contour 19.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

- Generate the envoy and contour SSL certificates
- Create the envoycert and contourcert k8s secrets using them
- Deploy the helm chart, specifying only the `envoy.tlsExistingCert=envoycert` and `contour.tlsExistingCert=contourcert` but NOT the root `tlsExistingCert` value

### Are you using any custom parameters or values?

- envoy.tlsExistingCert
- contour.tlsExistingCert

### What is the expected behavior?

Maybe I'm missing something, but this particular configuration causes cert-gen to run and hang, probably because `envoycert` and `contourcert` already exist and it can't overwrite them. In this circumstance, I would expect cert-gen not to run, or there be a flag to explicitly disable it

### What do you see instead?

Cert-gen runs and hangs. The docs don't make it especially clear what the root `tlsExistingSecret` value is intended for

**Comment by jamesggraf-m1** [comment]
I suspect this is the line that's to blame: https://github.com/bitnami/charts/blob/main/bitnami/contour/templates/_helpers.tpl#L45

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by jamesggraf-m1** [comment]
This may be an issue on my end because I had a bad indentation in the envoy configuration (It was indented one level too deep). I'm less certain this is an issue.
