### ISSUE TITLE
Redis: Non-SSL and SSL Port

### ISSUE THREAD

**Issue by jeremybeeman** [bitnami/charts#29834]
### Name and Version

bitnami/redis 20.1.7

### What is the problem this feature will solve?

We've been running into an issue when using SSL with redis where the SSL connection sometimes hangs. In order to mitigate this, I was going to try turning off SSL within our k8s cluster and still leaving SSL for external connections. Not sure if this is the approach (open to suggestions) but when trying to pursue it, it looked like I couldn't configure multiple ports for the redis pod.

### What is the feature you are proposing to solve the problem?

The feature would be to allow for multiple ports for redis, allowing SSL and non-SSL ports for redis. Another component of this would be to allow for switching the liveness/readiness probes from SSL-based to use the non-SSL port since that traffic stays within the host.

### What alternatives have you considered?

We are currently working to handle other components that may be overloading our redis instance. We're also trying to determine why this one client is now having SSL problems now instead of earlier on their app itself.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
