### ISSUE TITLE
[bitnami/jaeger] update cqlsh image

### ISSUE THREAD

**Issue by rorynickolls-skyral** [bitnami/charts#29836]
### Name and Version

bitnami/jaeger 3.0.3

### What is the problem this feature will solve?

The tag for `cqlshImage` is out-of-date in the default values: https://github.com/bitnami/charts/blob/b445bd37a6c255363ba790ea37cc380a55f6c49b/bitnami/jaeger/values.yaml#L1520

The latest version of Cassandra and the one deployed by the chart is 5.0.1 so this is a whole major version behind. 

### What is the feature you are proposing to solve the problem?

Ideally this version should be kept up-to-date, at least with the major version of Cassandra that the chart deploys.

### What alternatives have you considered?

We will have to override this value ourselves for now.

**Comment by carrodher** [comment]
Thanks for letting us know, yes, you're right, we will cut a new release updating the Cassandra major version

**Comment by carrodher** [comment]
A new version was released bumping the Cassandra major version, see https://github.com/bitnami/charts/pull/29860/files#diff-e8bd31b38026903403bcf0c15f57c9871e9e641ee74b9e1c0cd5e03db505a435L1520-R1520.

Thanks for letting us know!
