### ISSUE TITLE
[bitnami/thanos] data-dir should be configurable

### ISSUE THREAD

**Issue by gdlx** [bitnami/charts#29835]
### Name and Version

bitnami/thanos 15.7.27

### What is the problem this feature will solve?

I'm using Thanos compactor on an AWS EFS volume, shared between multiple k8s clusters and accounts.
That means I need to have a directory for each cluster, but the EFS controller doesn't allow to automatically create this directory, so I can't directly mount it on the compactor pod.

Mounting `/data` on the EFS root and setting `data-dir` to a subdirectory correctly creates a directory for each cluster, but the current chart value for `data-dir` is hard coded to `/data`, and setting it in `extraFlags` causes an error because the parameter can only be set once.

### What is the feature you are proposing to solve the problem?

The `data-dir` setting should be configurable, with `/data` as a default value.

### What alternatives have you considered?

I'm currently overriding the whole `args` list just to customize `data-dir`.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
