### ISSUE TITLE
[bitnami/keycloak] 26.0.0 Infinispan error

### ISSUE THREAD

**Issue by VonNao** [bitnami/charts#29840]
### Name and Version

bitnami/keycloak 26.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I upgrade the keycloak helm chart to version 24.0.0. During the startup from keycloak 26.0.0 the following error in regards to infinispan is show and the container dosen't start.
```
java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity$External
```

We arent't using any special parameters and infinispan isn't external

Environment: Kubernetes RKE2 1.30.3
Database: Postgres 16

### What is the expected behavior?

Normal Keycloak Startup 

### What do you see instead?

The Following Error in the logs.
```
java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity$External
```

**Comment by Bykow** [comment]
I'm also seeing a similar error after update the helm chart from `23.0.0` to `24.0.0` .

[error.log](https://github.com/user-attachments/files/17351372/error.log)

**Comment by javsalgar** [comment]
Hi,

As you are upgrading between major versions, it may be required to perform some manual steps. Did you check the upgrading guide? https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-26-0-0

To help debugging the issue, you may want to set `diagnosticMode.enabled=true` value

**Comment by Jojoooo1** [comment]
Upgrade between major release is not possible when you have multiple replica.
