### ISSUE TITLE
vault cannot form a cluster all replicas run as leaders

### ISSUE THREAD

**Issue by Aadarsh-Verma** [bitnami/charts#29866]
### Name and Version

bitnami/vault 

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install with the below custom-values

### Are you using any custom parameters or values?

```yaml
server:
  replicaCount: 3

  persistence:
    enabled: true
    selector:
      app: vault
    size: 10Gi
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    privileged: true
    allowPrivilegeEscalation: true

  config: |
    disable_mlock = true
    ui = true
    listener "tcp" {
      tls_disable = 1
      address = "[::]:{{ .Values.server.containerPorts.http }}"
      cluster_address = "[::]:{{ .Values.server.containerPorts.internal }}"
      {{- if .Values.server.metrics.enabled }}
      # Enable unauthenticated metrics access (necessary for Prometheus Operator)
      telemetry {
        unauthenticated_metrics_access = "true"
      }
      {{- end }}
    }
    storage "raft" {
      path = "{{ .Values.server.persistence.mountPath }}"
      retry_join {
          leader_api_addr = "http://vault-server-0.vault-server-headless:8200"
      }
     retry_join {
          leader_api_addr = "http://vault-server-1.vault-server-headless:8200"
      }
     retry_join {
          leader_api_addr = "http://vault-server-2.vault-server-headless:8200"
      }
    }

    service_registration "kubernetes" {}
injector:
  enabled: false

volumePermissions:
  enabled: true
```

### What do you see instead?

all vault nodes run as leaders, whereas there should only be a single leader and the rest need to be followers,

I can form a cluster on the official Hashicorp helm chart using the same config

**Comment by jotamartos** [comment]
Sorry for the delay in getting back to you. This is just a quick note to let you know that we received the issue and will come back to you as soon as we have more information.

**Comment by Aadarsh-Verma** [comment]
I was able to configure the cluster setup on configuring the config.hcl file 
I am closing this ticket as well

**Comment by jotamartos** [comment]
I'm glad to hear that you managed to solve the issue. Could you please provide more information about what was wrong with the config so other users can benefit from that? 

Thanks
