### ISSUE TITLE
Connect argocd to local kube-apiserver

### ISSUE THREAD

**Issue by Amithpn** [bitnami/charts#29894]
### Name and Version

bitnami/argocd-2.12.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

K8s 1.29.3
bitnami/argocd-2-12.3
kube-apiserver:1.29.3

I want to connect to local kube-apiserver running in my namespace instead of k8s cluster

### Are you using any custom parameters or values?

no

### What is the expected behavior?

I want to know how to provide the Kubernetes service URL to the argocd

### What do you see instead?

Unable to connect to local k8s service

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
