### ISSUE TITLE
Kafka helm installation error | chart version: 30.1.5

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#29904]
### Name and Version

bitnami/kafka 30.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team - I am installing Bitnami Kafka helm charts with kraft mode, I am getting the below error while installing helm charts.
Any parameters I need to change in Kafka values.yaml file?
```
Error: template: kafka/templates/secrets.yaml:131:23: executing "kafka/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (printf "%s-kraft-cluster-id" (include "common.names.fullname" .)) "key" "kraft-cluster-id" "providedValues" (list "kraft.clusterId") "length" 22 "context" $)>: error calling include: template: kafka/charts/common/templates/_secrets.tpl:117:16: executing "common.secrets.passwords.manage" at <eq .failOnNew false>: error calling eq: incompatible types for comparison
```
![image](https://github.com/user-attachments/assets/110fad36-de79-437b-9144-4cbc9c74c390)

### What do you see instead?

unable to install Kafka.

**Comment by bharathreddy901** [comment]
Please find the Kafka values.yaml file,which I am using.

**Comment by bharathreddy901** [comment]
@migruiz4  - Can you please help on above error?

**Comment by bharathreddy901** [comment]
Hi @migruiz4 @carrodher  - Can you please help on above error.

**Comment by migruiz4** [comment]
Hi @bharathreddy901, I'm sorry for the late response.

I see that you are installing the chart directly from the repository, have you modified the chart files?

We recommend installing the stable version of the chart from our repository:
- `helm install my-release oci://registry-1.docker.io/bitnamicharts/kafka` 

If you would like to install from the repository for development purposes, make sure to update the subcharts to the latest tested version using the command `helm dep build`.

It would be helpful if you could also provide the following details:

- What command did you use to install the chart? 
- Are you using any custom values? 
- When installing the chart, did you have any volumes from a previous install?
