### ISSUE TITLE
[bitnami/wordpress] Plugin installation failed

### ISSUE THREAD

**Issue by MedElevus** [bitnami/charts#29905]
### Name and Version

bitnami/wordpress

### What architecture are you using?

None

### What steps will reproduce the bug?

I don't know how to fix

### What do you see instead?

Installation failed: Could not create directory. /opt/bitnami/wordpress/wp-content/upgrade/f20890c5-classic-editor.1.6.5

**Comment by javsalgar** [comment]
Hi!

Could you add more details on the Kubernetes platform and the chart version you are using?
