### ISSUE TITLE
[bitnami/harbor] Harbor v2.0.0 GC not working 

### ISSUE THREAD

**Issue by nagyclaudiu83** [bitnami/charts#2992]
**Which chart**:
Harbor version 6.0.6 
- will affect all Bitnami chart versions that deploy Harbor v2.0.0+ 

**Describe the bug**
Clicking the "GC Now" button in Harbor will trigger a GC job that will always end with status "Error"

**To Reproduce**
1. Go to 'Administration/Garbage Collection'
2. Click on 'GC Now'
3. Click on History tab
4. Wait for the job to finish
5. Status will be "Error"

**Expected behavior**
GC should complete successfully. 

**Version of Helm and Kubernetes**:
Kubernetes: Rancher deployed 1.17.6
Helm: internal rancher application store

**Additional context**
The most relevant log message was found in the registryctl container log:
`[ERROR] [/registryctl/api/registry.go:49]: Fail to execute GC: exit status 127, command err: /bin/bash: registry_DO_NOT_USE_GC: command not found`

It looks like the rename of registry to registry_DO_NOT_USE_GC was done in the registryctl API function "func StartGC", but the binaries in bitnami containers were never renamed. 

This leads me to believe that the changes in Harbor v2.0.0+ as described in https://github.com/goharbor/harbor/issues/11606 have not been fully implemented in the bitnami build.

**Comment by dani8art** [comment]
Hi @nagyclaudiu83 we were able to reproduce it and we are working on fixing it, thank you so much for the feedback we will keep you updated.

**Comment by beltran-rubo** [comment]
There were several new versions of Harbor Chart since you reported the issue, could you please check if you can still reproduce it with the latest version 6.0.10 ?

**Comment by dani8art** [comment]
Hi @nagyclaudiu83, sorry for my late response. We did the changes and created a symbolic link between registry_DO_NOT_USE_GC and registry, so that you should be able to run it from the UI.

You can check it by executing:

```
docker run —rm -ti bitnami/harbor-registry ls -la /opt/bitnami/harbor-registry/bin
```
Hopefully it fixes your problems. Please do not hesitate to contact us if you find any other problem.

**Comment by nagyclaudiu83** [comment]
Thank you for the fix.

**Comment by mousambhagat** [comment]
Hi @dani8art Can you please share the command to create the link. I am facing same issue in my setup.
-rwxr-xr-x 1 harbor harbor  20M 2020-05-11 10:45 registry_DO_NOT_USE_GC
I tried to create the link but 
harbor [ /bin ]$ ln -s registry_DO_NOT_USE_GC registry
ln: cannot create symbolic link from 'registry_DO_NOT_USE_GC' to 'registry': Permission denied

**Comment by carrodher** [comment]
Are you using the latest version of the container? This fix should be part of the image itself.

About the error you're facing please take into account the container is non-root by default, so the user running in the container won't be able to perform this kind of operation.
If you want to do this kind of change by yourself you need to run the container as `root` or perform the modifications in the _Dockerfile_ (before the `USER 1001` directive) and build your own image
