### ISSUE TITLE
[bitnami/rabbitmq] Allow Configuration for RabbitMQ log level

### ISSUE THREAD

**Issue by andrei-dascalu** [bitnami/charts#29933]
### Name and Version

bitnami/rabbitmq 15.0.3

### What is the problem this feature will solve?

Currently there seems to be no exposed setting for configuring the very verbose default log level of "info". This means that the verbosity of the logs cannot be controlled.

### What is the feature you are proposing to solve the problem?

A helm chart value like "logLevel" that could be set to supported values as per https://www.rabbitmq.com/docs/logging

### What alternatives have you considered?

Currently the solution is to map custom configuration file and overriding various chart settings in the process.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team but, as it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.
