### ISSUE TITLE
[bitnami/mysql] Add support for TLS/SSL in mysql chart

### ISSUE THREAD

**Issue by borys-bilkevych** [bitnami/charts#29943]
### Name and Version

bitnami/mysql-11.1.19

### What is the problem this feature will solve?

- data encryption
- authentication
- compliance
- secure connections

### What is the feature you are proposing to solve the problem?

Add support for SSL/TLS for mysql (as you have been do it for another charts, like redis, psql, etc)

### What alternatives have you considered?

This feature will help to avoid using custom modifications with initContainers, volumeMounts and so on.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I forward it to the team for evaluation. We cannot guarantee an ETA, but as soon is it is available we will update this ticket.

**Comment by borys-bilkevych** [comment]
It can be easily done, by using the next option in mysql conf: `require_secure_transport=OFF/ON`

You can just move it as values in chart, like in redis/psql, or just close it. Thanks

**Comment by javsalgar** [comment]
Just a note to let you know that we created a PR to add TLS support for MySQL like we have in other charts

https://github.com/bitnami/charts/pull/30640
