### ISSUE TITLE
[bitnami/redis] schema breaks templating

### ISSUE THREAD

**Issue by Stevenpc3** [bitnami/charts#29952]
### Name and Version

bitnami/redis 20.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

In any environment, set a master.podAnnotations to a template value and see this error.

![{32BC5C28-BEF5-48B3-8E37-364B14C5E6E5}](https://github.com/user-attachments/assets/36e408a9-3fec-4309-8401-9a6cf68cf204)

### Are you using any custom parameters or values?

```
redis:
  master:
    podAnnotations: '{{- include "mysite.com/common/annotations" . }}'
```

### What is the expected behavior?

deploys normally and templates the annotations as it used to do.

### What do you see instead?

error from schema that says "string" is not valid and only accepts objects.

### Additional information

This has been the way we have done it forever.  In order to fix this I would have to pass keys and only render the values.  We return a large set of key/value pairs and this breaks our functionality.

**Comment by Stevenpc3** [comment]
simply updating https://github.com/bitnami/charts/blob/main/bitnami/redis/values.schema.json#L590C18-L590C32 and https://github.com/bitnami/charts/blob/main/bitnami/redis/values.schema.json#L1309 (I think are the two places) to allow 'string' or 'object' should be enough.

**Comment by Stevenpc3** [comment]
I also assume many other places will have this issue like 'podLabels', 'affinity', 'nodeSelectors'... a whole bunch.  Essentially, any item in values.yaml that is templatable, but the schema limits to objects or boolean or array or anything not a string.

**Comment by Stevenpc3** [comment]
Is there a way to make helm check the schema AFTER render?  I would expect it to work that way which would resolve this issue...

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I believe there were other PRs in the past changing the schema to allow both types of values. Would you like to submit a PR updating the schema?

**Comment by Stevenpc3** [comment]
What happened to those other PRs?

I can submit for the items that effect me now, but I don't have the time to go through all the other possible values that can be templates at this time.

**Comment by Stevenpc3** [comment]
Bump to self
