### ISSUE TITLE
Server ConfigMap does not set ImagePullPolicy

### ISSUE THREAD

**Issue by dmfrey** [bitnami/charts#29965]
### Name and Version

bitnami/spring-cloud-dataflow 32.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

In `values.yaml` set `deployer.imagePullPolicy` to any acceptable value.

Server ConfigMap template never uses this value, so ImagePullPolicy never gets set.

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

ImagePullPolicy get set in the Server ConfigMap

### What do you see instead?

Property is never set

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
