### ISSUE TITLE
can not add chart repo  https://charts.bitnami.com/bitnami

### ISSUE THREAD

**Issue by bufapiqi** [bitnami/charts#29979]
### Name and Version

bitnami

### What architecture are you using?

None

### What steps will reproduce the bug?

run helm repo add bitnami https://charts.bitnami.com/bitnami

### Are you using any custom parameters or values?

no

### What do you see instead?

Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://repo.broadcom.com/bitnami-files/index.yaml": unexpected EOF

### Additional information

If you visit the URL you get an access denied error.

**Comment by carrodher** [comment]
I'm not able to reproduce the issue, please check there is not any other connectivity issue on your side:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
```

Apart from that, please note the recommended way for consuming Bitnami Helm charts is using the [DockerHub OCI packages](https://hub.docker.com/u/bitnamicharts), i.e `helm install redis oci://registry-1.docker.io/bitnamicharts/redis`

**Comment by Wiikiiki** [comment]
Hi I encountered the exact same problem, trying changing your network may help. After I changed my IP, the bitnami repo was successfully added.
