### ISSUE TITLE
[bitnami/postgresql-ha] pgpool's readinessProbe doesn't working when using `PGPOOL_POSTGRES_PASSWORD_FILE`

### ISSUE THREAD

**Issue by yukha-dw** [bitnami/charts#29980]
### Name and Version

bitnami/postgresql-ha

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set `pgpool.usePasswordFile=true`
2. Set `pgpool.readinessProbe.enabled=true`
3. Use default readinessProbe

k8s will deploy pgpool with this problematic readinessProbe
```
Readiness:            exec [bash -ec PGPASSWORD=${PGPOOL_POSTGRES_PASSWORD} psql -U "kong" -d "kong" -h /opt/bitnami/pgpool/tmp -tA -c "SELECT 1" >/dev/null] delay=5s timeout=5s period=5s #success=1 #failure=5
```

### Are you using any custom parameters or values?

```YAML
pgpool:
  usePasswordFile: true
  readinessProbe:
    enabled: true
```

### What is the expected behavior?

readinessProbe fetch password from `PGPOOL_POSTGRES_PASSWORD_FILE`

### What do you see instead?

```
  Warning  Unhealthy  119s (x190 over 16m)  kubelet            Readiness probe failed: Password for user [CUSTOM_USER]:
psql: error: connection to server on socket "/opt/bitnami/pgpool/tmp/.s.PGSQL.5432" failed: fe_sendauth: no password supplied
```

### Additional information

Related lines:
https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/pgpool/deployment.yaml#L325-L334

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
