### ISSUE TITLE
Milvus datanode networkpolicy for egress is not working

### ISSUE THREAD

**Issue by rakesh-upadhyay1** [bitnami/charts#29981]
### Name and Version

bitnami/milvus 9.0.7

### What architecture are you using?

None

### What steps will reproduce the bug?

1. In OpenShift environment, deploy milvus 9.0.7
2. datanode pod goes in crashloopbackoff always waiting for the wait-for-etcd to validate etcd pod
3. and the wait-for-etcd init container is not able to resolve etcd service url

### Are you using any custom parameters or values?

no using the default values

### What is the expected behavior?

network policy for datanode to have egress allow all applied

### What do you see instead?

network policy for datanode to have egress

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
