### ISSUE TITLE
[bitnami/supabase] Does Bitnami officially stop supporting the Supabase Helm chart from October 2024?

### ISSUE THREAD

**Issue by namdoel1412** [bitnami/charts#30006]
### Name and Version

bitnami/supabase:5.2.2

### What is the problem this feature will solve?

Does Bitnami officially stop supporting the Supabase Helm chart from October 2024?

### What is the feature you are proposing to solve the problem?

Does Bitnami officially stop supporting the Supabase Helm chart from October 2024?

### What alternatives have you considered?

Does Bitnami officially stop supporting the Supabase Helm chart from October 2024?

**Comment by javsalgar** [comment]
Hi,

Yes, the Bitnami Supabase chart has been deprecated and therefore all support has been stopeed.

**Comment by magick93** [comment]
Just curious, why has the supabase chart been deprecated? What was the reasoning?
