### ISSUE TITLE
[bitnami/milvus] Support standalone mode

### ISSUE THREAD

**Issue by clcc2019** [bitnami/charts#30005]
### Name and Version

bitname/milvus:9.0.8

### What is the problem this feature will solve?

Lighte deployment requirements, fewer resources

### What is the feature you are proposing to solve the problem?

Single-machine deployment

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. As a workaround, you can try disabling all of the nodes but one, and override the `args` section so it is launched as standalone. You may need to edit the `milvus.defaultConfig` section too. I'm afraid it goes beyond my expertise but let's see if someone from the community can share their experience too.
