### ISSUE TITLE
[bitnami/airflow] Startup fails when `nameOverride` or `fullnameOverride` is specified for internal Redis

### ISSUE THREAD

**Issue by LucasRakotomalala** [bitnami/charts#30000]
### Name and Version

bitnami/airflow at least since 18.x.x

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Setting either `redis.nameOverride` or `redis.fullnameOverride` to any custom **non empty** value
2. Try deploying Bitnami Airflow
3. See that Airflow is not running since it can not find Redis&reg; master instance

### Are you using any custom parameters or values?

```yaml
# values.yaml
redis:
  enabled: true
  nameOverride: airflow-redis
```
Or:

```console
--set=redis.enabled=true --set=redis.nameOverride=airflow-redis
```

### What is the expected behavior?

The `airflow.redis.fullname` helper should search correctly in `redis` subchart: the `chartName` **should be** `redis` instead of `redis-master`.

### What do you see instead?

By having `redis-master` in `chartName`, it results to have wrong `REDIS_HOST`environment variable for all statefulsets when using internal Redis: https://github.com/bitnami/charts/blob/main/bitnami/airflow/templates/_helpers.tpl#L363-L364

Currently, we have `REDIS_HOST` rendered as `{{ .Release.Name }}-airflow-redis` instead of `{{ .Release.Name }}-airflow-redis-master`.

_Note: `{{ .Release.Name }}` is correctly templated._

### Additional information

Line impacted: https://github.com/bitnami/charts/blob/main/bitnami/airflow/templates/_helpers.tpl#L129

To me, it should use a `printf` to add `-master` at the end.
Examples:
- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/_helpers.tpl#L158
- https://github.com/bitnami/charts/blob/main/bitnami/appsmith/templates/_helpers.tpl#L124-L141

**Comment by fmulero** [comment]
Thanks a lot @LucasRakotomalala! I appreciate a lot this detailed explanation, you almost fix the issue.

The key here is the name of the main service exposed by the redis chart. As you spotted, redis clients should use the host `{{.Release.name}}-master`.

I've just created the PR https://github.com/bitnami/charts/pull/30117 to fix the issue. Please take it a glance.

**Comment by LucasRakotomalala** [comment]
Hello @fmulero,
Thank you for your PR #30117, it looks good to me.

___

What I did in the PR #30081 is also fixing issue #30087.
Also, I introduced a new helper `airflow.redis.host`, to be able to reuse `airflow.redis.fullname` if needed later on.
I also made a fix for PostgreSQL host. Do I need to create a ticket for that?

**Comment by fmulero** [comment]
Oh! I didn't see it, my failure. I'll close my PR in favor of yours
