### ISSUE TITLE
Inclusive selector in deployment creates conflict with image-renderer when using port-forward

### ISSUE THREAD

**Issue by xkbarkar** [bitnami/charts#3000]
**Which chart**:
grafana-2.1.2

**Describe the bug**
After helm installation the instructions specify  
```
kubectl port-forward svc/grafana 8080:3000 & 
```
To open  the dashboard, running this command will result in error 
```bash
error: Pod 'grafana-image-renderer-******' does not have a named port 'dashboard'   
```
since the selector in the grafana service 
```yaml
selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
```
Will return both grafana and grafana-image-renderer pods 

**To Reproduce**
Install grafana using helm , follow the port-forward instructions in the terminal 

**Expected behavior**
Grafana exposed on localhost port 8080

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
As a very lazy workaround ran the following post deployment to create a distinct result for the service selector
```bash
 kubectl patch svc grafana  -p '{"spec": { "selector": { "app.kubernetes.io/service": "grafana" }}}'
 kubectl patch deployment grafana  -p '{"spec": { "template": { "metadata" : { "labels": { "app.kubernetes.io/service": "grafana" }}}}}'```

**Comment by rafariossaa** [comment]
Hi,
  Could you try with chart version 3.1.2 ?
