### ISSUE TITLE
Issue with creating a default user for Keycloak using environment variables

### ISSUE THREAD

**Issue by itsstefanpopov** [bitnami/charts#30012]
### Name and Version

bitnami/keycloak:24.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using terraform to deploy keycloak's latest version using the bitnami chart. Everything seems okay, up to the point when i access my public dns url for keycloak and I get prompted with this:
![image](https://github.com/user-attachments/assets/33f5af11-252b-4bf6-89a6-0719a538a4aa)
Now what i did with terraform, according to the [bitnami documentation](https://artifacthub.io/packages/helm/bitnami/keycloak#add-extra-environment-variables), like so
![image](https://github.com/user-attachments/assets/b612e539-6920-4015-85a2-7ca2b7650c36)
I have these environment variabels in the pod 
![image](https://github.com/user-attachments/assets/bc45e259-3402-43f4-bec8-a25d84a91cca)
But i am still getting prompted with the same message in keycloak.

### What do you see instead?

In the keycloak UI, i am seeing this message:
To create the temporary administrative user open https://localhost/, or set the environment variables KC_BOOTSTRAP_ADMIN_USERNAME and KC_BOOTSTRAP_ADMIN_PASSWORD when starting the server.

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
