### ISSUE TITLE
[bitnami/flux] RBAC - leases.coordination.k8s.io permissions assigned to Role instead of ClusterRole?

### ISSUE THREAD

**Issue by TiepiNL** [bitnami/charts#30027]
### Name and Version

bitnami/flux 2.3.20

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Pre-render the helm chart with `helm template fluxcd bitnami/flux --someargs <args> > deployment.yaml`
2. `kubectl apply deployment.yaml`
3. `kubectl apply some-syncs.yaml`

(This is how I bootstrap Flux via GHA)

### What is the expected behavior?

The syncs/Kustomizations work fine.

### What do you see instead?

`kubectl get kustomizations -n flux-system` show "Source artifact not found" failures, and `flux logs --all-namespaces --level=error` shows "leases.coordination.k8s.io is forbidden" errors.

### Additional information

The "leases" permissions are assigned to a Role in https://github.com/bitnami/charts/blob/main/bitnami/flux/templates/source-controller/roles.yaml. In the flux repository, this is a ClusterRole: https://github.com/fluxcd/flux2/blob/main/manifests/rbac/controller.yaml (also see https://fluxcd.io/flux/security/#controller-permissions).

If I add the ClusterRole manually with the same permissions for "coordination.k8s.io" as the created Role, Flux does start syncing and the errors are gone.

**Comment by javsalgar** [comment]
Hi,

By the time we created the chart, that was set to Role. Maybe, in recent versions, this was set to ClusterRole. As you discovered the issue, would you like to submit a PR updating the object to ClusterRole?

**Comment by migruiz4** [comment]
Hi @TiepiNL,

I'm sorry but I see that the upstream repository still defines the same as our chart.
Please take a look at:
- https://github.com/fluxcd/source-controller/blob/v1.4.1/config/rbac/role.yaml
- https://github.com/fluxcd/source-controller/blob/v1.4.1/config/rbac/leader_election_role.yaml

You referenced flux v2, but our chart still uses `v1.4.1`.

I will discuss this with the team, but I think that for the time being I may need to dismiss your PR, since this may require a major release on our side and maybe updating flux from v1 to v2.

I'm sorry for the inconvenience.

**Comment by TiepiNL** [comment]
> Hi @TiepiNL,
> 
> I'm sorry but I see that the upstream repository still defines the same as our chart. Please take a look at:
> 
> * https://github.com/fluxcd/source-controller/blob/v1.4.1/config/rbac/role.yaml
> * https://github.com/fluxcd/source-controller/blob/v1.4.1/config/rbac/leader_election_role.yaml
> 
> You referenced flux v2, but our chart still uses `v1.4.1`.
> 
> I will discuss this with the team, but I think that for the time being I may need to dismiss your PR, since this may require a major release on our side and maybe updating flux from v1 to v2.
> 
> I'm sorry for the inconvenience.

I'm quite new to Flux (and to Kubernetes in general tbh) and a bit lost now. Afaik "Flux v2" is the name of the ecosystem, and is e.g. the source-controller one of the [components](https://github.com/fluxcd/flux2/tree/main?tab=readme-ov-file#components). The [description of the components](https://fluxcd.io/flux/components/source/) on the flux website link to the Github repo you referenced. `v1.4.1.` seems to be the component version.

Based on the v2 description in the [FAQ](https://fluxcd.io/flux/migration/faq-migration/#what-are-significant-new-differences-between-flux-v1-and-flux-v2), I dare to say that the bitnami chart is Flux v2.

That being said, the resource files that you pointed to clearly have Roles and not ClusterRoles, in contradiction to the manifest in the v2 repo. Even tho it fixes my issue, I agree that simply moving the permissions from Role to ClusterRole might be not the correct solution. A broader RBAC comparison might be the way to go? I checked the Flux community helm chart and it has a `crd-controller` ClusterRole with the leases permission: [crd-controller-clusterrole.yaml](https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/templates/crd-controller-clusterrole.yaml).

I'm happy to continue using my ClusterRole "patch", and to let you guys dive deeper into the v2 rbac.
