### ISSUE TITLE
[bitnami/kafka] Support multiple root CA on external access

### ISSUE THREAD

**Issue by shiinro** [bitnami/charts#30020]
### Name and Version

bitnami/kafka 30.1.6

### What is the problem this feature will solve?

Now, Kafka accept only 1 root CA from secret.
```
# Create JKS truststore from CA cert
keytool -keystore /certs/kafka.truststore.jks -alias CARoot -import -file /certs/ca.crt -storepass "${KAFKA_TLS_TRUSTSTORE_PASSWORD}" -noprompt
```
 `ca.crt` key from secret is a list of all acceptable client certificate CAs

### What is the feature you are proposing to solve the problem?

Split /certs/ca.crt file into multiples files then import them into truststore

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. I will forward it to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look.
