### ISSUE TITLE
[bitnami/rabbitmq] Rabbitmq helm chart can't accept TLS connection via management plugin.

### ISSUE THREAD

**Issue by stgns** [bitnami/charts#30035]
### Name and Version

bitnami/rabbitmq 15.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I try to use either autogenerated TLS certs or custom defined ones, rabbitmq can't initiate management console on HTTPS port 15671.

### Are you using any custom parameters or values?

No. Only the ones recommended via values.yaml

### What is the expected behavior?

I should access management web ui via TLS.

### What do you see instead?

Secure Connection Failed

An error occurred during a connection to localhost:15672. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by stgns** [comment]
There is a similar issue here:

https://github.com/rabbitmq/rabbitmq-server/discussions/7363

It might be resolved with the same configuration settings.

**Comment by jotamartos** [comment]
Thanks for posting the solution here, it'll be useful for others running into the same issue.
