### ISSUE TITLE
intermittent dns issue in new versions of keycloak 

### ISSUE THREAD

**Issue by johnoloughlin** [bitnami/charts#30058]
### Name and Version

bitnami/keycloak 24.0.1  also seen in 22.2.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This has nothing to do with the key cloak binary.  although it does effect it and causes a java dump whenever it hits the issue.
I have been able to use curl within the keycloak pod to reproduce. (to simplify the debug)
steps to reproduce: 
run `while true; do curl -k -v postgresql.database.svc.cluster.local; sleep 5; done` within the container.
After a period of time, and successful lookups the dns lookup will fail intermittently
```curl: (6) Could not resolve host: postgresql.database.svc.cluster.local
* Could not resolve host: postgresql.database.svc.cluster.local
* Closing connection 0
```
We have taken a number of steps to try narrow the issue.
The issue seems to be a combination of the chart and the image.

Can't reproduce the issue with:
`kubectl run -n platform-system  platform-keycloak-1 -it --image=docker.io/bitnami/keycloak:26.0.1-debian-12-r0 -- bash` 

Can't reproduce the issue with:
`kubectl debug -n platform-system  platform-keycloak-0 -it --image=nicolaka/netshoot`

**Can reproduce the issue with**
`kubectl debug -n platform-system  platform-keycloak-0 -it --image=docker.io/bitnami/keycloak:26.0.1-debian-12-r0 -- bash`

**Can reproduce the issue by editing the entry command of the keycloak pod to sleep**

Can't reproduce by changing the keycloak pod image to ubuntu:jammy

This issue doesn't appear in the older version of the keycloak chart `15.1.3`

### What do you see instead?

dns issue above

**Comment by johnoloughlin** [comment]
After a lot of deployments I believe I have narrowed down the issue to
`
---
# Source: keycloak/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: my-release-keycloak
  namespace: "maestro-database"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.0.1
    helm.sh/chart: keycloak-24.0.1
    app.kubernetes.io/component: keycloak
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: keycloak
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 7800
        - port: 8080
---

`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
