### ISSUE TITLE
[bitnami/keycloak] Keycloak passwords not updating when Passwords are injected through Vault.

### ISSUE THREAD

**Issue by hamza-haider00** [bitnami/charts#30051]
### Name and Version

keycloak-10.1.4

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Create a secret and save Keycloak password in vault. let's say this password is (keycloak123)
2. Create ServiceProviderClass to provide secrets to CSI driver.
3. Add newly generated secret into Keycloak helm chart and map password keys. (This will generate a secret <keycloak-secret> when Keycloak is deployed)
4. Deploy fresh Keycloak.
5. Login to Keycloak with the password that was stored in vault.
Everything works fine till here.
6. Patch password in vault secret. let's say new password is (admin123)
7. Delete the secret <keycloak-secret>.
8. Restart the keycloak pod.
9. Exec into keycloak password
10. Echo $admin-password variable to check the value of password set. It should be reflecting the updated password (admin123)
11. Access keycloak webpage and try log in using new password (admin123)

Issue arise here as Keycloak would not allow login with admin123 password but keycloak123.

### What is the expected behavior?

Keycloak should be accepting new password which is admin123 instead of old-password.

### What do you see instead?

I encounter login error for incorrect password when attempting login with new password. I have tried upgrading the deployment using `helm upgrade` command as well, but it still accepts the old password.

### Additional information

In addition, password hashes are stored in Postgresql database within the cluster.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that currently the passwords are set on first boot, so if you change the secret you may need to perform operations on keycloak manually.

**Comment by hamza-haider00** [comment]
@javsalgar , by manually you mean from keycloak web interface, right?
I have tried updating password from web interface and password updates successfully. but issue arises only when injecting updated password from vault.

**Comment by javsalgar** [comment]
Hi,

Yes, I believe it should be done from the web interface.
