### ISSUE TITLE
SCDF Prometheus RSocket Proxy deployment template does not mount emptyDir to /tmp

### ISSUE THREAD

**Issue by dmfrey** [bitnami/charts#30063]
### Name and Version

bitnami/spring-cloud-dataflow 32.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Enable Metrics in values

```yaml
metrics:
    enabled: true
```

Prometheus RSocket Proxy starts up, but fails to extract the `snappy-java` native library to `/tmp` since the filesystem is not writable.  The Prometheus RSocket Proxy server is unusable at this point as the `/metrics/connected` endpoint never returns a 200 OK.

### What is the expected behavior?

`/tmp` gets mounted to the declared `emptyDir` volume

### What do you see instead?

The issues described above

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.
