### ISSUE TITLE
[bitnami/keycloak] Please share the compatibility of bitnami/keycloak and bitnami/keycloak-config-cli versions which helps us to upgrade our applications

### ISSUE THREAD

**Issue by MadanReddyK** [bitnami/charts#30065]
### Name and Version

bitnami/keycloak-config-cli

### What architecture are you using?

None

### What steps will reproduce the bug?

Working with below versions:
Keycloak: 23.0.6 chart: 18.0.1 keycloak-config-cli: 5.10.0-debian-11-r0

Not working after upgrade
Keycloak: 24.0.5-debian-12-r8 chart: 21.8.0 
keycloak-config-cli: 
6.0
5.12.0-debian-12-r2
5.12.0-debian-12-r5
5.12.0-debian-12-r4
5.11.0-debian-12-r0
5.11.1-debian-12-r0
6.1.0-24.0.5
5.10.0-debian-11-r0

used all versions of cli, deployment stucks at Keycloak-config-cli job  

### Are you using any custom parameters or values?

NO

### What is the expected behavior?

Works as older version

### What do you see instead?

log: "Error creating: admission webhook "vault.hashicorp.com" denied the request: error creating new agent sidecar: failed to find service account volume mount"

**Comment by javsalgar** [comment]
Hi,

It seems that the error is not related with keycloak but with a problem with a vault webhook. Could you double check it?
