### ISSUE TITLE
[bitnami/mlflow] imagePullPolicy of mlflow container is not set according to docstring

### ISSUE THREAD

**Issue by hahahannes** [bitnami/charts#30061]
### Name and Version

bitnami/mlflow:2.0.2

### What architecture are you using?

None

### What steps will reproduce the bug?

```
helm template --values=values.yaml --set image.tag=latest bitnami/mlflow > foo.bar
```

### Are you using any custom parameters or values?

image.tag=latest

### What is the expected behavior?

`imagePullPolicy` of the mlflow contaienr should be `Always`

### What do you see instead?

`imagePullPolicy` of the mlflow contaienr should be `IfNotPresent`

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
