### ISSUE TITLE
[bitnami/drupal] Can i use any drupal container image with bitnami/drupal helm chart

### ISSUE THREAD

**Issue by L0rD59** [bitnami/charts#30076]
### Name and Version

bitnami/drupal 20.0.10

### What is the problem this feature will solve?

Hi !

Can I use a drupal image other than official bitnami/drupal or bitnami based with this helm chart ?

In this context, I'm currently facing a problem linked with deployment - initContainers - prepare-base-dir , command/args that requires /opt/bitnami/scripts in the drupal image, and there isn't any conditional statement to avoid this

Is this an issue or the normal behavior ?

Thanks

### What is the feature you are proposing to solve the problem?

Adding condition statement in prepare-base-dir initContainer

https://github.com/bitnami/charts/blob/a781e775554f74ae029d2e2bb3a3758a5871ad33/bitnami/drupal/templates/deployment.yaml#L68-L88

**Comment by L0rD59** [comment]
as workaround i use kustomize to remove this part of chart, but i would like to know if i can use other drupal container image with the chart

**Comment by javsalgar** [comment]
Hi,

The sections that you removed were meant to ensure the maximum security settings (such as readOnlyRootFilesystem). In this sense, while it is possible to change the image to a non-bitnami one, that's not something we test or actively support.
