### ISSUE TITLE
[bitnami/mysql] support mysql 8.0.40

### ISSUE THREAD

**Issue by paochiang** [bitnami/charts#30078]
### Name and Version

bitnami/mysql

### What is the problem this feature will solve?

MySQL 8.0.40 (2024-10-15, General Availability)
The version I use now is：
```
version: 6.14.11
appVersion: 8.0.22
```
I want to upgrade mysql to 8.0.40，but I found that the latest version is 8.0.37：
![image](https://github.com/user-attachments/assets/189f58ae-2260-444e-99cb-9ffccdc0e2c3)

Is there a plan to support mysql 8.0.40?

### What is the feature you are proposing to solve the problem?

I want to know if there is a plan to support mysql 8.0.40, and the time plan

**Comment by javsalgar** [comment]
Hi,

The image for 8.0.40 is available in our repositories. You can try switching the image, but we did not perform any verification at chart-level.

**Comment by paochiang** [comment]
> Hi,
> 
> The image for 8.0.40 is available in our repositories. You can try switching the image, but we did not perform any verification at chart-level.

Thank you, I have upgraded to MySQL 8.4.3. 
```
version: 11.1.19
appVersion: 8.4.3
```
