### ISSUE TITLE
RabbitMq cannot login with username and password

### ISSUE THREAD

**Issue by standup-jb** [bitnami/charts#3008]
**Which chart**:

bitnami/rabbitmq

**Describe the bug**

Login http://10.20.112.202:15672/ use username and password. but login failed. there api response http code 401 . 

**To Reproduce**

1. My chart values.yaml 

```
## RabbitMQ Authentication parameters
##
auth:
 
  username: admin


  password: admin
```

2. After I install chart successed.

```
[root@test-a6-docker-60-236 helm-package]# echo "Username      : admin"
Username      : admin
[root@test-a6-docker-60-236 helm-package]#     echo "Password      : $(kubectl get secret --namespace default rabbitmq-1 -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
Password      : admin
[root@test-a6-docker-60-236 helm-package]#
```

3. I use the browser open the admin page

![image](https://user-images.githubusercontent.com/18265949/86357712-d6a2bc80-bca0-11ea-9874-3ff8b585eff1.png)

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
[root@test-
```

**Comment by juan131** [comment]
Hi @standup-jb 

Did the issue appear after installing the chart from scratch? Or was it after upgrading an existing release? Please note it's mandatory to set the the `auth.username`, `auth.password` and `auth.erlangCookie` parameters when upgrading too.

- https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#upgrading

Please also ensure you don't have PVCs from previous releases, since they're not removed and they could cause a conflict if different credentials were set.

**Comment by standup-jb** [comment]
> Hi @standup-jb
> 
> Did the issue appear after installing the chart from scratch? Or was it after upgrading an existing release? Please note it's mandatory to set the the `auth.username`, `auth.password` and `auth.erlangCookie` parameters when upgrading too.
> 
> * https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#upgrading
> 
> Please also ensure you don't have PVCs from previous releases, since they're not removed and they could cause a conflict if different credentials were set.


I solved this problem. Thank you very much . I will close this issues.

**Comment by standup-jb** [comment]
In fact , Use github issues solve problems isn't effective way . Is there have some IM method to connect your . Such as facebook . messager or email .

**Comment by juan131** [comment]
Hi @standup-jb 

We attend issues related with Bitnami charts or Bitnami containers through GitHub. We don't provide support through mail or IM systems.

We also have a Community forum, where we attend generic issues related with Bitnami products (regardless they're related to containers/charts or other Bitnami products such as native installers or single VMs):

- https://community.bitnami.com/

**Comment by tsterker** [comment]
For anyone having the same issue (also #3074), but a fresh install (with PVC removed) did not help:

I provided my own `configuration`, such as

```yml
# values.yaml
rabbitmq:
    configuration: |-
        log.console.level = warning
```

Removing this (and/or moving it to `extraConfiguration`) solved the problem for me after another fresh install.

**Comment by juan131** [comment]
Hi @tsterker 

Thanks for sharing your workaround!! That said, it really surprises me that you couldn't solve the issue by removing the PVC(s) and performing a fresh install.

Setting the parameters `auth.username`, `auth.password` and `auth.erlangCookie` should work on a fresh install.
