### ISSUE TITLE
[bitnami/airflow] Redis port is not taken from values

### ISSUE THREAD

**Issue by LucasRakotomalala** [bitnami/charts#30087]
### Name and Version

bitnami/airflow at least since 18.x.x

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Setting `redis.master.service.ports.redis` to any int that is not `6379` (e.g. `6380`)
2. Try deploying Bitnami Airflow
3. See that Airflow is not running since the port of Redis&reg; is not `6379`

### Are you using any custom parameters or values?

```yaml
# values.yaml
redis:
  enabled: true
  master:
    service:
      ports:
        redis: 6380
```
Or:

```console
--set=redis.enabled=true --set=redis.master.service.ports=6380
```

### What is the expected behavior?

The `REDIS_PORT_NUMBER` environment variable should be rendered as follow:

```yaml
            - name: REDIS_PORT_NUMBER
              value: "6380"
```

### What do you see instead?

The `REDIS_PORT_NUMBER` environment variable is rendered as follow:

```yaml
            - name: REDIS_PORT_NUMBER
              value: "6379"
```

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look
