### ISSUE TITLE
IBM Cloud - Prometheus Operator basic authentication

### ISSUE THREAD

**Issue by martingerman81** [bitnami/charts#3009]
**Which chart**:
Prometheus Operator - 0.3.9 IBM cloud
Prometheus-operator-0.20.4

**Describe the bug**
We set a secret to the ingress configuration for basic authentication in order to login using user and password to get access to Prometheus API. We set the prometheus.ingress.annotations with 
{"kubernetes.io/ingress.class": "nginx", "nginx.ingress.kubernetes.io/auth-type": "basic", "nginx.ingress.kubernetes.io/auth-secret": "prometheus-basic-auth", "nginx.ingress.kubernetes.io/auth-realm": "Authentication Required"} 
As you can see we have included the "nginx.ingress.kubernetes.io/auth-secret": "prometheus-basic-auth", but when we access the URL prometheus.xxx.com/graph we not need user and password, sound like the ingress controller created via catalog in the IBM cloud is not using the prometheus-basic-auth secret.

**To Reproduce**
1. Go to https://cloud.ibm.com/catalog/content/prometheus-operator-Qml0bmFtaS1wcm9tZXRoZXVzLW9wZXJhdG9y-global
2. Configure prometheus operator.
**prometheus.ingress.hosts =** [{"name":"blablabla","path":"/"}]
**prometheus.ingress.annotations=** {"kubernetes.io/ingress.class": "nginx", "nginx.ingress.kubernetes.io/auth-type": "basic", "nginx.ingress.kubernetes.io/auth-secret": "prometheus-basic-auth", "nginx.ingress.kubernetes.io/auth-realm": "Authentication Required"}
**prometheus.ingress.enabled=**true
**prometheus.secrets =**["prometheus-basic-auth"]
3. Install button

**Expected behavior**
Before access to the prometheus.xxx.com/graph we expect username and password request.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11+IKS", GitCommit:"c33b093e937d1f9eee340f9bddfa14e1e54ad1a4", GitTreeState:"clean", BuildDate:"2020-06-17T21:37:54Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by marcosbc** [comment]
Hi @martingerman81, note that the IBM Ingress controller does not use the following annotation format:

```
nginx.ingress.kubernetes.io/auth-secret
```

Instead, it looks like it must have a format like this:

```
ingress.bluemix.net/mutual-auth: "secretName=<mysecret> port=<port> serviceName=<servicename1>,<servicename2>"
```

Refer to https://cloud.ibm.com/docs/containers?topic=containers-ingress_annotation for more information.
