### ISSUE TITLE
Transitioning Bitnami Helm charts to OCI for enhanced security, efficiency, and compatibility

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#30110]
In January 2022, we announced the general availability of Helm charts in OCI registries, coinciding with [the release of Helm version 3.8.0](https://github.com/helm/helm/releases/tag/v3.8.0). In January 2023, Bitnami began populating and distributing the largest and most up-to-date Open-Source catalog of [Helm charts in OCI format in Docker Hub](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html).

Since then, the adoption of the Bitnami Helm charts in OCI format has proliferated. Because charts stored in container registries follow OCI standards, developers can use many of the same tools for Helm charts that they use with container images. This makes integrating Helm into automated pipelines easier and uses modern infrastructure-as-code and deployment techniques like GitOps.

We would like to go further and help the Helm community to continue adopting the OCI distribution format. Starting November the 18th, 2024, Bitnami Helm charts will default to OCI. All the charts will remain Open Source and publicly available at https://hub.docker.com/u/bitnamicharts.

### What will happen to the current `index.yaml` stored at charts.bitnami.com?

To guarantee a smoother transition, the `index.yaml` will continue to exist as an OCI artifact in Docker Hub. To maintain backward compatibility, users who still use the helm repo add command can continue using this approach. The Helm tooling manages this transparently.

The `index.yaml` will change the “URL” option to point to the new OCI versions of Helm charts:
```diff
  urls:
-    - https://charts.bitnami.com/bitnami/airflow-18.3.2.tgz
+    - oci://registry-1.docker.io/bitnamicharts/airflow:18.3.2
```

Users should not see any change when deploying Helm charts. They must use a Helm CLI greater than 3.8.0 to deploy them.

### What will happen to the Bitnami Helm charts in tgz format?
The Bitnami Helm charts in tgz format will no longer be updated. Previous versions since 2023 are available at Docker Hub and it is easy to get the tgz format via Helm command:

```
$ helm pull oci://registry-1.docker.io/bitnamicharts/airflow –version 18.3.2
```

Older versions will remain available at the same URL for 6 months to ensure a smooth transition. Do not hesitate to contact us for any questions or suggestions at https://github.com/bitnami/charts/issues

---

For more information on this topic, check out our latest blog post: [Bitnami Helm Charts Moving to OCI](https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html).

**Comment by viceice** [comment]
please publish to `public.ecr.aws` too

- https://github.com/docker/hub-feedback/issues/2421
😕

**Comment by alexsorkin** [comment]
Revert the registry index back, guys...

`$ helm show values redacted-private/thanos Error: failed to fetch https://redacted-private-registry/registry-context/api/helm/redacted-private/oci://registry-1.docker.io/bitnamicharts/thanos:15.9.2 : 404 `

You have ruined 100.000s proxy registry around the world.

HTTP registry should point to HTTP URLs.

**Comment by vnea** [comment]
Hello.

I'm currently using [Nova](https://github.com/FairwindsOps/nova) to scan my helm Charts and check for new updates.

I have this current configuration for Nova:

```yaml
---
containers: false
helm: true

poll-artifacthub: false
include-all: true
format: table

url:
  - https://charts.bitnami.com/bitnami
```

Under the hood, Nova will access to https://charts.bitnami.com/bitnami/index.yaml and check if there are new updates.

But now, I'm using getting the charts from Bitnami via `OCI` and not `HTTP`.

I was wondering myself: is https://charts.bitnami.com/bitnami/index.yaml maintained for the OCI charts?

I'm not sure how it works exactly so I prefer to ask.
