### ISSUE TITLE
[bitnami/postgresql] metrics.collectors ignored for read replica

### ISSUE THREAD

**Issue by dklenke** [bitnami/charts#30125]
### Name and Version

bitnami/postgresql 16.0.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy bitnami postgres with `architecture: replication` and at least 1 custom metrics collector enabled. For example like this: `helm install --set architecture=replication,metrics.enabled=true,metrics.collectors.postmaster=true my-release oci://registry-1.docker.io/bitnamicharts/postgresql`
2. observe that the metrics container for the primary postgres container starts with the startup arguments correctly set to `--collector.postmaster` while the metrics container for the read replica is missing this flag

### Are you using any custom parameters or values?
```
architecture: replication
metrics.enabled: true
metrics.collectors.postmaster: true
```
### What is the expected behavior?

Both the StatefulSet for the postgresql primary as well as the StatefulSet for the postgresql read replica should start their metrics containers with the extra arguments for the enabled or disabled collectors from the helm values.

### What do you see instead?

Only the StatefulSet of the postgresql primary uses settings defined at `metrics.collectors`.

### Additional information

The responsible line in the template for the primary StatefulSet is [here](https://github.com/bitnami/charts/blob/0868c633cc6b2f16efcbbd86e0dce126ac0fdcd1/bitnami/postgresql/templates/primary/statefulset.yaml#L530). Any equivalent is missing for the read replica StatefulSet [here](https://github.com/bitnami/charts/blob/0868c633cc6b2f16efcbbd86e0dce126ac0fdcd1/bitnami/postgresql/templates/read/statefulset.yaml#L432).

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will take a look

**Comment by dklenke** [comment]
That you for the response! I will provide a pull request

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
