### ISSUE TITLE
[bitnami/keycloak] Support Multiple Ingress - Public/Private

### ISSUE THREAD

**Issue by shaikzoheb-oi** [bitnami/charts#30134]
### Name and Version

bitnami/keycloak - 25.0.4-debian-12-r1

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy bitnami keycloak

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

We should be able to expose "/admin" api only for internal/private users

### What do you see instead?

Eventhough If we deploy seperate ingress, it's not working

**Comment by shaikzoheb-oi** [comment]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme-clusterissuer
    external-dns.alpha.kubernetes.io/hostname: abc.com
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    whitelistSourceRange: “private ops"
  name: keycloak-internal
  namespace: keycloak
spec:
  ingressClassName: nginx
  rules:
  - host: abc.com
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              name: http
        path: /admin/
        pathType: Prefix
  tls:
  - hosts:
    - abc.com
    secretName: abc.com-tls

**Comment by shaikzoheb-oi** [comment]
@javsalgar Appreciate your inputs/suggestions on this use-case?

**Comment by javsalgar** [comment]
Hi,

What issue do you see when using the separate ingress?

**Comment by shaikzoheb-oi** [comment]
@javsalgar I am referring to this yaml - https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml

I've enabled adminIngress along with Ingress.

Host/Domain: https://abc.com

Ingress rule is "/". (https://abc.com) ---> Public one or should be accessed externally

adminIngress rule is "/admin" and "/realms/master" (https://abc.com/admin & https://abc.com/realms/master---> This is only for internal user/private within dedicated network and it's working fine within the network.

The challenge is, the actual endpoint "https://abc.com" is not working over internet/public and giving "403".

**Comment by shaikzoheb-oi** [comment]
@javsalgar This is what I am trying to convey.

![image](https://github.com/user-attachments/assets/9bce4fc1-b4a9-4c9b-b9df-683be1afbbd1)

**Comment by shaikzoheb-oi** [comment]
@javsalgar Is there any alternative solution for this? 

One more thing is, once we enable adminIngress - In configmap It will add KEYCLOAK_HOSTNAME_ADMIN: https://abc.com/admin (https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/configmap-env-vars.yaml)

With this keycloak url won't work, why because already the KEYCLOAK_HOSTNAME: https://abc.com/

So once we access https://abc.com/ ---> Its' redirecting to https://abc.com/admin/admin and the error "An internal server error has occurred". As a workaround, I have to remove that "admin" from KEYCLOAK_HOSTNAME_ADMIN and restart keycloak pod.

If the root url of the keycloak point to some other context path like "/adminconsole" rather than "/admin" then i think we can apply private/internal ingress rule to "/admin"

**Comment by florianrusch** [comment]
Please note that setting `hostname` and `hostname-admin` does not prevent keycloak from accepting and responding to requests to the Admin API via the `hostname` url.

![image](https://github.com/user-attachments/assets/3c5c93fc-6f87-4f9d-b477-904798924598)

https://www.keycloak.org/server/hostname#_exposing_the_administration_console_on_a_separate_hostname
