### ISSUE TITLE
app.kubernetes.io/version should pick the image tag in values.yaml instead of .Chart.AppVersion

### ISSUE THREAD

**Issue by reegnz** [bitnami/charts#30151]
### Name and Version

bitnami/external-dns 8.3.5

### What is the problem this feature will solve?

When rendering charts, the `app.kubernete.io/version` is populated with the `appVersion` declared in `Chart.yaml`, instead of using the `.image.tag` passed as a value.

### What is the feature you are proposing to solve the problem?

When someone overrides the image tag, that should be used in the labels instead of the `appVersion`, otherwise it is incorrect metadata.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
