### ISSUE TITLE
[bitnami/thanos] Allow providing an existing service account for all componenets

### ISSUE THREAD

**Issue by Alexx-G** [bitnami/charts#3015]
**Which chart**:
bitnami/thanos v0.13.0

**Is your feature request related to a problem? Please describe.**
I'm using IAM roles for service accounts in AWS EKS to give access to the S3 bucket for Thanos componenets. While this work quite nicely when there's a single service account, it's a bit of a problem when you can't control service account name.
Currently when creating the assume policy for the IAM role, I have to consider that there are 4 service accounts I need to give access to and add corresponding rules. Also it implies that I have to set the same annotation to 4 different service accounts when installing the helm chart.

**Describe the solution you'd like**
Normally helm charts allow providing name of an existing service account via something like `*.serviceAccount.name` and when this property it's set, the helm chart doesn't create its service account. 

**Describe alternatives you've considered**
Providing the role via annotation for each service account and tweaking the assume policy, so it accepts several service accounts, however it seems kinda error prone. Creating a single service account and providing it for all components would allow reducing boilerplate.

**Comment by dani8art** [comment]
Hi @Alexx-G , I've just created a PR adding the feature requested, please let's move the conversation there. Thank you!
