### ISSUE TITLE
[bitnami/keycloak] KEYCLOAK_HOSTNAME present even if KEYCLOAK_PROXY_HEADERS is set

### ISSUE THREAD

**Issue by RDemarneffe** [bitnami/charts#30182]
### Name and Version

bitnami/keycloak:24.0.4

### What architecture are you using?

None

### What steps will reproduce the bug?

Into the Helm chart of Keycloak, the configuration variable `KEYCLOAK_HOSTNAME` is always set once the ingress is enabled.

However, as stated into the Keycloak startup log, when this variable is set, the content of the variable `KEYCLOAK_PROXY_HEADERS` is never taken into account.

### What is the expected behavior?

When the helm `proxyHeaders` variable is set, the `KEYCLOAK_HOSTNAME` into the config map should not be set.

### What do you see instead?

The `KEYCLOAK_HOSTNAME` is always set when ingress is enabled.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will check it.
