### ISSUE TITLE
airflow-exporter providing limited metrics.

### ISSUE THREAD

**Issue by surendar-argtech** [bitnami/charts#30185]
### Name and Version
```
helm install my-release oci://registry-1.docker.io/bitnamicharts/airflow
```

### What steps will reproduce the bug?

airflow exporter is getting limited metrics from airflow.

### What do you see instead?

I don't know how to do this resolve.

### Additional information

Please provide the exact reason for not getting all the metrics of airflow through the airflow-exporter.

**Comment by dgomezleon** [comment]
Hi @surendar-argtech 

What metrics are you missing? Do you mean [statsd](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/metrics.html#setup-statsd)?

**Comment by dgomezleon** [comment]
Hi @surendar-argtech 

Could you please be more specific about the metrics you are missing? Maybe sharing an example with your tested values, actual results and expected results could help.

**Comment by juan131** [comment]
@surendar-argtech StatsD metrics will be supported on version `22.0.0`, see contribution above
