### ISSUE TITLE
[bitnami/wordpress] Wordpress maintenance mode returns 503 health check fails

### ISSUE THREAD

**Issue by lwj5** [bitnami/charts#3019]
**Which chart**:
wordpress

**Describe the bug**
When updating WordPress plugins or themes. WordPress is automatically put into maintenance mode.
wp-login.php will return 503, thus health check will fail.

**To Reproduce**
1. Go to 'WordPress updates'
2. Click on 'update all'
4. See pod die

**Expected behavior**
The pod is not supposed to be killed, the health check URL should return 200 even in maintenance mode.

**Version of Helm and Kubernetes**:
Does not matter

**Comment by javsalgar** [comment]
Hi,

I think that, in the case of a long upgrade, it may make sense to change the liveness/readiness probe of the container. In other charts we are allowing a customLivenessProbe and customReadinessProbe section that deals with this kind of situations. In this chart it is not implemented yet, so while you perform this maintenance operation I would advise you to disable the liveness/readiness probes and then reenable them. Would it make sense for your case?

**Comment by lwj5** [comment]
I see okay, thanks for the reply. I'll try to find something for a long term solution.

**Comment by lwj5** [comment]
@javsalgar wp-admin/install.php might be a good health check path. It doesn't get affected by maintenance mode and fails when DB connection fails. You could consider the path change.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input! Feel free to create a PR with the change. If not, we will add it to our backlog (which would take a bit longer because of priorities)

**Comment by lwj5** [comment]
PR added.

**Comment by javsalgar** [comment]
Thank you so much! We will review it very soon :)
