### ISSUE TITLE
[bitnami/elasticsearch] Update ELASTICSEARCH README.md "Elasticsearch rest Encryption" section

### ISSUE THREAD

**Issue by vmaglietta** [bitnami/charts#30199]
### Name and Version

bitnami/elasticsearch 21.3.22

### What architecture are you using?

None

### What steps will reproduce the bug?

Since elasticsearch.security.auth.kibanaUsername has been removed starting from kibana chart ver. 10.0, please update your readme.md Enable bundled Kibana - Elasticsearch rest Encryption section accordingly.

Many thanks

### Are you using any custom parameters or values?

no

### What do you see instead?

security_exception: unable to authenticate user [kibana_system] for REST request

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the request! I will forward it to the team, but as it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR removing these values and the team will check it.
