### ISSUE TITLE
How to config pod time zone

### ISSUE THREAD

**Issue by standup-jb** [bitnami/charts#3020]
I use the rabbitmq charts deploy in k8s . but the time zone is UTC 
`
I have no name!@rabbitmq-24-0:/etc$ date
Fri 03 Jul 2020 10:32:43 AM UTC
`
I am in ShangHai China  . I want to set the time zone is Asia/shanghai . So Is there any way to change the time zone .

**Comment by juan131** [comment]
Hi @standup-jb 

Try setting the `TZ` environment variable:

```console
$ docker run --rm -it bitnami/rabbitmq -- bash
I have no name!@c4e4e3cddbcb:/$ date
Mon 06 Jul 2020 08:03:30 AM UTC
TZ=Asia/Shanghai date
Mon 06 Jul 2020 04:03:16 PM CST
```

**Comment by standup-jb** [comment]
> Hi @standup-jb
> 
> Try setting the `TZ` environment variable:
> 
> ```
> $ docker run --rm -it bitnami/rabbitmq -- bash
> I have no name!@c4e4e3cddbcb:/$ date
> Mon 06 Jul 2020 08:03:30 AM UTC
> I have no name!@c4e4e3cddbcb:/$ TZ=Asia/Shanghai date
> Mon 06 Jul 2020 04:03:16 PM CST
> ```

I modified the rabbitmq chart statefulset.yaml . add env TZ as below and resolved this issue . I think it is  enhancement . Chart show provided a variable config timezone in values.yaml . Default is UTC .but usually use local time when developer deploy in their country. 
`
          env:
            - name: TZ
              value: Asia/Shanghai
`
