### ISSUE TITLE
airflow chart upgrade fails

### ISSUE THREAD

**Issue by ebizboy** [bitnami/charts#30210]
### Name and Version

bitnami/airflow 21.1.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

bitnami airflow version from 20.0.2 -> 21.1.1

### Are you using any custom parameters or values?

dags:
  enabled: true

### What is the expected behavior?

chart upgrade succeed

### What do you see instead?

Received response status [FAILED] from custom resource. Message returned: Error: b'Error: UPGRADE FAILED: template: airflow/templates/web/deployment.yaml:30:31: executing "airflow/templates/web/deployment.yaml" at <include (print $.Template.BasePath "/config/configmap.yaml") .>: error calling include: template: airflow/templates/config/configmap.yaml:116:12: executing "airflow/templates/config/configmap.yaml" at <include "airflow.defaultInitContainers.loadDAGsPlugins" .>: error calling include: template: no template "airflow.defaultInitContainers.loadDAGsPlugins" associated with template "gotpl"\n'

**Comment by juan131** [comment]
Hi @ebizboy 

Thanks so much for reporting this issue! I'm the one who's adding a series of new features in Airflow chart in the last days. 

I was able to identify the issue and I'll send a PR to address it right after https://github.com/bitnami/charts/pull/30211 gets merged.

**Comment by juan131** [comment]
@ebizboy I just merged the PR addressing the bug you reported, please give a try to the chart version `21.2.1` and let us know if you still face upgrading issues. Also, given you're upgrading from `20.y.z`, please ensure you read the upgrade notes at:

- https://github.com/bitnami/charts/tree/main/bitnami/airflow#to-2100

**Comment by ebizboy** [comment]
@juan131 The chart upgrade has been successfully completed. However, I’m experiencing an issue where the Airflow tasks are failing immediately upon starting. I will investigate to see if this is on my end, and if it turns out to be a bug, I’ll create a new issue for it. Thank you
