### ISSUE TITLE
[bitnami/nats] Expose Statefulset Pod Management Policy

### ISSUE THREAD

**Issue by rblaine95** [bitnami/charts#30217]
### Name and Version

bitnami/nats 8.4.5

### What is the problem this feature will solve?

Currently the NATS Statefulset Pod Management Policy isn't exposed, which means it's essentially hardcoded to `OrderedReady`.

### What is the feature you are proposing to solve the problem?

Expose the `podManagementPolicy` in the NATS StatefulSet

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
