### ISSUE TITLE
[bitnami/thanos] Support different resources for sharded Storegateway

### ISSUE THREAD

**Issue by utkudarilmaz** [bitnami/charts#30219]
### Name and Version

bitnami/thanos 15.8.0

### What is the problem this feature will solve?

Each sharded Thanos Store needs different resources to operate correctly. For example, we can define different time ranges for each store but larger ranges require higher memory.

### What is the feature you are proposing to solve the problem?

```
storegateway:
  resources: ## Default resources for shards which haven't custom resources
    requests:
      cpu: 1
      memory: 2Gi
  sharded:
    enabled: true
    timePartitioning:
      - min: "-7d"
        max: ""
        resources: ## Override resources for this shard.
          requests:
            cpu: 2
            memory: 4Gi
      - min: "-14d"
        max: "-7d"
        resources: {}

### What alternatives have you considered?

_No response_

**Comment by javsalgar** [comment]
Hi! Thank you so much for the feature request. I will forward it to the team but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and the team will check it.
