### ISSUE TITLE
OpenSearch Security plugin installed but disabled. This can expose your configuration (including passwords) to the public

### ISSUE THREAD

**Issue by yanone1** [bitnami/charts#30242]
### Name and Version

bitnami/opensearch-1.2.6

### What architecture are you using?

None

### What steps will reproduce the bug?

1. in a google cloud environment -gke  1.30.5-gke.1014001 
2. helm install.
3. using gce-internal ingress -this is not a related issue.

### What is the expected behavior?

I need to have the security plugin enabled using the provided certificate files.
at the dashboard under management to see the security plugin UI.
login to the dashboard with username and password. 

### What do you see instead?

no login prompt for the dashboard.
no security plugin enabled.

**Comment by carrodher** [comment]
Could you please describe how are you installing the plugins? Please note there is a `plugins` parameter you can use to specify the plugins to be installed, see https://github.com/bitnami/charts/tree/main/bitnami/opensearch#opensearch-cluster-parameters
