### ISSUE TITLE
[bitnami/airflow-exporter] Exporter is providing few metrics of bitnami airflow, not all metrics, i want all metrics of bitnami airflow.

### ISSUE THREAD

**Issue by surendar-argtech** [bitnami/charts#30274]
### Name and Version

bitnami/airflow-exporter:0.20220314.0-debian-12-r51

### What architecture are you using?

None

### What steps will reproduce the bug?

limited metrics exposed by airflow exporter, this is the issue, i want all the metrics of bitnami airflow.

### What do you see instead?

![image](https://github.com/user-attachments/assets/109d47b5-078c-4718-a652-2a67abc5c20d)

**Comment by surendar-argtech** [comment]
![image](https://github.com/user-attachments/assets/bfee3527-2618-4efc-ad9f-7a48d42d319b)
except these metrics, airflow exporter is not scraping other metrics of bitnami airflow.

**Comment by javsalgar** [comment]
Hi,

Thank you for bringing up the issue. It is not clear to me that the issue is with the Bitnami packaging of Airflow Exporter but in Airflow Exporter itself. Did you try reporting to the upstream Airflow Exporter devs? https://github.com/PBWebMedia/airflow-prometheus-exporter
