### ISSUE TITLE
Issues with deployments on GKE after Cluster update

### ISSUE THREAD

**Issue by bananbyran** [bitnami/charts#3028]
**Which chart**:
The name (and version) of the affected chart
Wordpress
Mariadb

**Describe the bug**
Probably not a bug, rather a failure from my way. 

Google upgraded the node pool (or gke version) automatically and since then all deployments fail, especially mariadb. 
I use a slightly customized wordpress image with a default bitnami mariadb. The mariadb deployment fails to start since the upgrade from Google. 

The wordpress deployments seems to start but fails at trying to connect to mariadb obviously.
I tried updating the deployment with a fresher image but that also fails. My own conclusion is that it fails to connect to it's previously created PVC because of permission issues, which is kinda strange cause nothing has really changed. Except for the previously stated cluster version. I also don't really know if there is a way to get an update log from the cluster, the logs I can see is filled to the brim with other information.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.15", GitCommit:"8ce551a0c972a9f113e326df0537aa3f1798d93e", GitTreeState:"clean", BuildDate:"2020-05-05T18:38:03Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
Describe from one of the failing mariadb pods.
```
Name:           envikensbostader-mariadb-0
Namespace:      envikensbostader
Priority:       0
Node:           gke-customer-medium-1-default-pool-1a16eb67-apab/10.164.15.208
Start Time:     Mon, 06 Jul 2020 00:15:24 +0200
Labels:         app=mariadb
                chart=mariadb-7.3.16
                component=master
                controller-revision-hash=envikensbostader-mariadb-54d695b6db
                release=envikensbostader
                statefulset.kubernetes.io/pod-name=envikensbostader-mariadb-0
Annotations:    <none>
Status:         Running
IP:             10.52.4.13
IPs:            <none>
Controlled By:  StatefulSet/envikensbostader-mariadb
Containers:
  mariadb:
    Container ID:   docker://beffb0674e64f4a02a6bcdd55317eeb6578f86790d3e5bbecb45f61733859be7
    Image:          docker.io/bitnami/mariadb:10.3.23-debian-10-r38
    Image ID:       docker-pullable://bitnami/mariadb@sha256:749e6240d95aaab5fa52b6c0cd696738ae6db3bc42e3953c77d871665f5e4059
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 06 Jul 2020 11:18:03 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Mon, 06 Jul 2020 11:15:12 +0200
      Finished:     Mon, 06 Jul 2020 11:18:03 +0200
    Ready:          False
    Restart Count:  144
    Liveness:       exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'envikensbostader-mariadb'>  Optional: false
      MARIADB_USER:           bn_wordpress
      MARIADB_PASSWORD:       <set to the key 'mariadb-password' in secret 'envikensbostader-mariadb'>  Optional: false
      MARIADB_DATABASE:       bitnami_wordpress
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tngr9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-envikensbostader-mariadb-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      envikensbostader-mariadb
    Optional:  false
  default-token-tngr9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tngr9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                                                       Message
  ----     ------     ----               ----                                                       -------
  Normal   Pulled     52m (x3 over 53m)  kubelet, gke-customer-medium-1-default-pool-1a16eb67-apab  Container image "docker.io/bitnami/mariadb:10.3.23-debian-10-r38" already present on machine
  Warning  Unhealthy  17m (x7 over 23m)  kubelet, gke-customer-medium-1-default-pool-1a16eb67-apab  Liveness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists!
  Warning  BackOff    7m30s (x2995 over 11h)  kubelet, gke-customer-medium-1-default-pool-1a16eb67-apab  Back-off restarting failed container
  Warning  Unhealthy  2m28s (x86 over 24m)    kubelet, gke-customer-medium-1-default-pool-1a16eb67-apab  Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/opt/bitnami/mariadb/tmp/mysql.sock' exists!
```
Logs from GCP.
```
E 2020-07-06T09:07:13.898981658Z [38;5;6mmariadb [38;5;5m09:07:13.89 [0m[38;5;2mINFO [0m ==> ** Starting MariaDB setup **
 
E 2020-07-06T09:07:13.913874595Z [38;5;6mmariadb [38;5;5m09:07:13.91 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_*/MARIADB_* env vars
 
E 2020-07-06T09:07:13.918451075Z [38;5;6mmariadb [38;5;5m09:07:13.91 [0m[38;5;2mINFO [0m ==> Initializing mariadb database
 
E 2020-07-06T09:07:13.930711336Z [38;5;6mmariadb [38;5;5m09:07:13.93 [0m[38;5;3mWARN [0m ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
 
E 2020-07-06T09:07:13.932363934Z [38;5;6mmariadb [38;5;5m09:07:13.93 [0m[38;5;2mINFO [0m ==> Using persisted data
 
E 2020-07-06T09:07:13.956212076Z [38;5;6mmariadb [38;5;5m09:07:13.95 [0m[38;5;2mINFO [0m ==> Running mysql_upgrade
 
E 2020-07-06T09:07:13.965960495Z [38;5;6mmariadb [38;5;5m09:07:13.96 [0m[38;5;2mINFO [0m ==> Starting mariadb in background
 
```

**Comment by juan131** [comment]
Hi @bananbyran 

It's very likely to be related with your previous PVC. What kind of PV were you using? Is it a Local PV? If it's a local PV, it means it's a disk mounted on a specific node (see https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#what-is-a-local-persistent-volume) and that can be problematic if the node pool was upgraded.

Do you have any backup of your WP site?

> I tried updating the deployment with a fresher image but that also fails

Did you try also to create a different release of WP+MariaDB (installing the chart with a different release name) to ensure that WP can indeed start without issues when starting from scratch?

**Comment by bananbyran** [comment]
Pretty sure they are local yeah. Is there a way to fix them. Also I have moved a bit further in my own findings. I enabled the debug feature for the mariadb image and got this.
```
2020-07-07  6:52:42 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.23-MariaDB) starting as process 53 ...
2020-07-07  6:52:42 0 [Note] InnoDB: Using Linux native AIO
2020-07-07  6:52:42 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-07-07  6:52:42 0 [Note] InnoDB: Uses event mutexes
2020-07-07  6:52:42 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-07-07  6:52:42 0 [Note] InnoDB: Number of pools: 1
2020-07-07  6:52:42 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-07-07  6:52:42 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-07-07  6:52:42 0 [Note] InnoDB: Completed initialization of buffer pool
2020-07-07  6:52:42 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-07-07  6:52:42 0 [ERROR] InnoDB: Unsupported redo log format. The redo log was created with MariaDB 10.5.4.
2020-07-07  6:52:42 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2020-07-07  6:52:43 0 [Note] InnoDB: Starting shutdown...
2020-07-07  6:52:43 0 [ERROR] Plugin 'InnoDB' init function returned error.
2020-07-07  6:52:43 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2020-07-07  6:52:43 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-07-07  6:52:43 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2020-07-07  6:52:43 0 [ERROR] Aborting
```

Some googling later a suggestion was to rename the ib_logfile0, which I did, with the help of a recover pod.
Which resulted in this log

```
2020-07-07  7:24:13 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.23-MariaDB) starting as process 53 ...
2020-07-07  7:24:13 0 [Note] InnoDB: Using Linux native AIO
2020-07-07  7:24:13 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-07-07  7:24:13 0 [Note] InnoDB: Uses event mutexes
2020-07-07  7:24:13 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-07-07  7:24:13 0 [Note] InnoDB: Number of pools: 1
2020-07-07  7:24:13 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-07-07  7:24:13 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-07-07  7:24:13 0 [Note] InnoDB: Completed initialization of buffer pool
2020-07-07  7:24:13 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-07-07  7:24:13 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-07-07  7:24:13 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-07-07  7:24:13 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-07-07  7:24:13 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-07-07  7:24:13 0 [Note] InnoDB: Waiting for purge to start
2020-07-07  7:24:13 0 [Note] InnoDB: 10.3.23 started; log sequence number 1361791060; transaction id 967096
2020-07-07  7:24:13 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2020-07-07  7:24:13 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-07-07  7:24:13 0 [Note] Server socket created on IP: '127.0.0.1'.
2020-07-07  7:24:13 0 [Warning] 'proxies_priv' entry '@% root@lantlivinredning-mariadb-0' ignored in --skip-name-resolve mode.
2020-07-07  7:24:13 0 [Note] Reading of all Master_info entries succeeded
2020-07-07  7:24:13 0 [Note] Added new Master_info '' to hash table
2020-07-07  7:24:13 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.3.23-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2020-07-07  7:24:13 0 [Note] InnoDB: Buffer pool(s) load completed at 200707  7:24:13
2020-07-07  7:24:14 8 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
FATAL ERROR: Upgrade failed
mariadb 07:24:14.58 INFO  ==> Stopping mariadb
2020-07-07  7:24:14 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
2020-07-07  7:24:14 0 [Note] InnoDB: FTS optimize thread exiting.
2020-07-07  7:24:14 0 [Note] Event Scheduler: Purging the queue. 0 events
2020-07-07  7:24:14 0 [Note] InnoDB: Starting shutdown...
2020-07-07  7:24:14 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
2020-07-07  7:24:14 0 [Note] InnoDB: Instance 0, restricted to 2048 pages due to innodb_buf_pool_dump_pct=25
2020-07-07  7:24:14 0 [Note] InnoDB: Buffer pool(s) dump completed at 200707  7:24:14
2020-07-07  7:24:15 0 [Note] InnoDB: Shutdown completed; log sequence number 1361791069; transaction id 967097
2020-07-07  7:24:15 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-07-07  7:24:15 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
```

So now I have the issue of a faulty root password I guess. Shouldn't the image get the password from the configuration secret? Or did the pods get recreated with new passwords when the node pool upgraded.

> Did you try also to create a different release of WP+MariaDB (installing the chart with a different release name) to ensure that WP can indeed start without issues when starting from scratch?

I do have a deployment running successfully. It was the latest deployment I created just last week. So that survived, which also leads me to think it might be some compatibility issues.

**Comment by bananbyran** [comment]
Also found a slightly related issue #2634 though I'm sure I didn't redeploy them without the reference to the old secrets. 
Is there a way to reset the password on the PVC data? Feels like that would be my solution but everything I try ends up not working. 

Last thing I tried was to install mysql on a recover-pod that mounts the data, but changing the datadir in mysql to the mounted data wont work. Mysql don't start on the recover-pod then.

**Comment by juan131** [comment]
> So now I have the issue of a faulty root password I guess. Shouldn't the image get the password from the configuration secret? Or did the pods get recreated with new passwords when the node pool upgraded.

Yes, they should take from the secret but the secret could have changed from the original values if you upgraded the chart without indicating the original password (that's explained in this section https://github.com/bitnami/charts/tree/master/bitnami/mariadb#upgrading)

That said, you can still reset the root password by mounting the volume on a Bitnami MariaDB container and rewriting the default command so it does sth like "sleep infinity" (to avoid MariaDB to start during the initialisation and fail). Then, you can connect to the container opening a Bash shell and follow these steps:

- Create a file in **/tmp/mysql-init** with the content shown below (replace **NEW_PASSWORD** with the password you wish to use).

```
UPDATE mysql.user SET Password=PASSWORD('NEW_PASSWORD') WHERE User='root';
FLUSH PRIVILEGES;
```

- Start MariaDB with the following command:

```console
$ . /opt/bitnami/scripts/libmariadb.sh
$ . /opt/bitnami/scripts/mariadb-env.sh
$ /opt/bitnami/mariadb/bin/mysqld_safe --defaults-file=${DB_CONF_DIR}/my.cnf --basedir=${DB_BASE_DIR} --datadir=${DB_DATA_DIR} --socket=${DB_SOCKET_FILE} --init-file=/tmp/mysql-init 2> /dev/null &
```

- Remove the **/tmp/mysql-init** file and stop MariaDB:

```console
$ rm /tmp/mysql-init
$ mysql_stop
```

Now you can remove the pod, and mount again the volume in your original MariaDB pods.

**Comment by bananbyran** [comment]
Thanks, managed to resolve it with the help of the above, though the mysql-init way didn't work for some reason. Instead I altered the start command to.
`/opt/bitnami/mariadb/bin/mysqld_safe --defaults-file=${DB_CONF_DIR}/my.cnf --basedir=${DB_BASE_DIR} --datadir=${DB_DATA_DIR} --socket=${DB_SOCKET_FILE} --skip-grant-tables 2> /dev/null &`

Which starts mysql without the need to login. I then did the normal way of altering the password:
```
$ mysql
mysql> use mysql;
mysql> update user set password=PASSWORD("NEW-ROOT-PASSWORD") where User='root';
mysql> flush privileges;
mysql> quit
```

**Comment by juan131** [comment]
Great @bananbyran !!! I'm very glad you were able to restore your database!! Were you able to also recover your WP site?

**Comment by evtimmy** [comment]
Just hit this issue as well after upgrading AKS cluster with Bitnami WordPress deployment.  For some reason when mariadb restarted, the original passwords became invalid. Note that there have been no new deployments or upgrade. I have also checked and this is not due to not passing original secrets - the password in the secret resource never changed.

I wonder if the default mariadb configuration in the chart has some sort of password expiration period that kicks-in after restart?

**Comment by juan131** [comment]
Hi @evtimmy 

> I wonder if the default mariadb configuration in the chart has some sort of password expiration period that kicks-in after restart? 

No, AFAIK.

> the password in the secret resource never changed

Are you positive about that? Did you try to do a rollback of the chart release as it's explained in the [Troubleshooting Guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#solve-issue)

**Comment by evtimmy** [comment]
@juan131
Yup, positive that the secret did not change.  I followed your advise and I just performed a few rollbacks to make sure that the secrets did not change and that's right - both the secrets and the reference to the secrets did not change throughout the releases for the past 6 months (there were only a couple). We do use custom secrets template that preserves secrets on upgrades and auto-generates secrets on installs.  

In our case, the only thing we did was upgrade the cluster from 1.20 to 1.21 - that just added extra nodes and drained the existing nodes, pods got moved, then remove the extra nodes. We did no releases in-between, so basically this is how events unfolded:
1. Working wordpress deployment (has not been restarted for months)
2. Upgrade cluster 1.20 -> 1.21, we needed some updates to the CSI Driver and those worked well, some unrelated failing deployments got fixed with the updated driver as they got the proper file permissions for the pvc.
3. When testing the cluster upgrade the only deployments that started failing were the Bitnami WordPress deployment. Upon examination we saw that the root password did not work anymore. Used work-around describe here to reset it to the original value in the secret. After that the mariadb pod started ok, but the wordpress pod could not connect - we had to reset the wordpress db user password to original value (from secret) as well. Happened for both our stage and production deployments.

I wonder if either not restarting for months may have played a role, or updating the CSI Driver somehow affected some files in a way that caused auth data to be reset.

**Comment by juan131** [comment]
Hi @evtimmy 

Thanks so much for providing such a detailed description of your environment and how the issue was reproduced. Honestly, at this very moment, I'm as surprised as you because I don't see any reason for the MariaDB root password (+ the one used to identify the "bn_wordpress" user) to change.

A couple of questions:

- After restoring the passwords with the workaround provided by @bananbyran , did you miss anything else in the database? Did you lose info about your blog posts, users or any other kind of data that's stored in the database?
- What kind of PVs are you using for MariaDB?

**Comment by evtimmy** [comment]
Yeah, agreed this is so strange. I wish we could figure out a reliable way to reproduce, maybe that should be the next step in this investigation.

It seems that the database was all intact after the restore, all posts were there, including all statistics from the analytics plugins we have. 

Here's the PV:
```apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  creationTimestamp: "2021-03-14T07:21:55Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/disk-csi-azure-com
  name: pvc-xxxxxxxxxxxxxxxxxxx
  resourceVersion: "2604328"
  uid: xxxxxxxxxxxxxxxxxxx
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-prod-mariadb-0
    namespace: blog
    resourceVersion: "2604271"
    uid: xxxxxxxxxxxxxxxxxxx
  csi:
    driver: disk.csi.azure.com
    fsType: ext4
    volumeAttributes:
      skuname: StandardSSD_LRS
      storage.kubernetes.io/csiProvisionerIdentity: xxxxxxxxxx-disk.csi.azure.com
    volumeHandle: xxxxxxxxxxxxxxxxx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - xxxxxxxx
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
status:
  phase: Bound
```

**Comment by juan131** [comment]
Hi @evtimmy 

It seems you're using an Azure disk.. So we can discard any issue related with the K8s node filesystem (we can find them when using local volumes). And.. you said the database was intact.. So they only think I can think of is that the secrets changed and they don't have the same keys used when you installed the chart for the 1s time.

However, you said you're positive the secrets haven't changed so I run out of ideas, honestly.

**Comment by evtimmy** [comment]
Hi @juan131 

Unable to repro so far. We think this may have been due to a custom database backup & restore script that has somehow messed up the authentication. I'll try to get hold of that and try to repro when I find the time, but for now let's keep this issue closed. If I am able to get a concrete repro steps I'll open a new issue.

**Comment by juan131** [comment]
sure! Thanks so much @evtimmy 

Please keep us update if you discover anything new.
