### ISSUE TITLE
[bitnami/kube-prometheus] CRDs are not automatically updated

### ISSUE THREAD

**Issue by SpeedGriffon** [bitnami/charts#30366]
### Name and Version

bitnami/kube-prometheus 10.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Moving the CRDs to a subchart in #30142 caused them to not be picked up by the Update CRDs CI job.

### What do you see instead?

The CRDs are not automatically updated with each appVersion bump.

### Additional information

There are typos in both lines a6731f1 changed in `update_crds.sh`, but it doesn't seem the script is used.
https://github.com/bitnami/charts/blob/0a32af11c9ba26cc295a818ef696148c48beb006/bitnami/kube-prometheus/hack/update_crds.sh#L35-L37

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. As you discovered the typos, would you like to submit a PR?
