### ISSUE TITLE
[bitnami/keycloak] Issue with metrics into ServiceMonitor

### ISSUE THREAD

**Issue by RDemarneffe** [bitnami/charts#30369]
### Name and Version

bitnami/keycloak 24.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy the helm chart with default values.

### What is the expected behavior?

ServiceMonitor correctly configure prometheus for scrapping

### What do you see instead?

ServiceMonitor correctly configure prometheus for the instance metrics but incorrectly configure it for realm metrics.
This problem is that the port for instance metrics is 9000 and for realm metrics is 8080.

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
