### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] RabbitMQ Cluster Operator Creates A PodDisruptionBudget For Disabled Message Topology Operator

### ISSUE THREAD

**Issue by dorilahav** [bitnami/charts#30364]
### Name and Version

bitnami/rabbitmq-cluster-operator 4.3.24

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. I created an argocd application using the rabbitmq-cluster-operator helm
2. I disabled the message topology operator using the value below
3. I watched the operator go live but the health check is at degraded
4. RabbitMQ is working fine, but just the health check is degraded and a PodDisruptionBudget is failed

### Are you using any custom parameters or values?

msgTopologyOperator.enabled: false

### What is the expected behavior?

When msgTopologyOperator.enabled is set to false in values.yaml, it should not create a PodDisruptionBudget

### What do you see instead?

A PodDisruptionBudget is created and argocd application is in Degraded state because the pod count is 0

### Additional information

I looked at the last version (currently 4.3.27) and it doesn't look like it's fixed

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting, indeed, in the messaging-topology-operator/pdb.yaml file, instead of:

```
{{- if .Values.msgTopologyOperator.pdb.create }}
```


It should be:

```
{{- if and .Values.msgTopologyOperator.enabled .Values.msgTopologyOperator.pdb.create }}
```

As you discovered the issue, would you like to submit a PR?

**Comment by dorilahav** [comment]
I would love to
