### ISSUE TITLE
[bitnami/nats] Expose `publishNotReadyAddresses` in Headless Service

### ISSUE THREAD

**Issue by rblaine95** [bitnami/charts#30392]
### Name and Version

bitami/nats 8.4.8

### What is the problem this feature will solve?

We deploy NATS in AWS EKS and we use a Network Load Balancer for the `nats` service.

We use the AWS Load Balancer Controller with Readiness Gates enabled so we can do controlled rolling updates of the NATS cluster.

The Readiness Gates make it so that K8s will use the Load Balancer's target group health status before shutting down an old pod.

The problem is that, by default, NATS uses the `nats` (load balancer) service for clustering. With the readiness gates and scaling from zero, we see the health checks never pass which prevents the cluster from forming.

Our solution was to change it so NATS uses the `nats-headless` service instead and manually adding `publishNotReadyAddresses` on the headless service so that DNS works and the NATS cluster can form.

### What is the feature you are proposing to solve the problem?

Expose the `publishNotReadyAddresses` config in the Headless Service.
Maintain the existing default of `publishNotReadyAddresses: false` so operators have to explicitly set it to `true`

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
