### ISSUE TITLE
[bitnami/airflow] load custom dags on airflow

### ISSUE THREAD

**Issue by surendar-argtech** [bitnami/charts#30401]
### Name and Version

helm install my-release oci://registry-1.docker.io/bitnamicharts/airflow

### What architecture are you using?

None

### What steps will reproduce the bug?

i am not able to load cutom dags on airflow

### What do you see instead?

what should i do

**Comment by javsalgar** [comment]
Hi,

Could you share more information on the values you used and the DAG repository you tried to load? We would like to reproduce the issue on our side.
