### ISSUE TITLE
[bitnami/redis-cluster] Request to Increase Default terminationGracePeriodSeconds for Redis StatefulSet in Helm Chart

### ISSUE THREAD

**Issue by sajad-sadra** [bitnami/charts#30412]
### Name and Version

bitnami/redis-cluster 11.0.8

### What is the problem this feature will solve?

The redis-cluster Bitnami Helm chart does not set a terminationGracePeriodSeconds value for StatefulSet pods, which means the default Kubernetes value of 30 seconds is used. This may not provide sufficient time for Redis instances to complete data-saving operations (e.g., RDB snapshots or AOF writes) before being terminated during rolling updates or scaling down. Insufficient time for graceful shutdowns could lead to potential data loss or corruption.

### What is the feature you are proposing to solve the problem?

I propose setting a default terminationGracePeriodSeconds value in the redis-cluster Helm chart to a more suitable duration, such as 120 or 300 seconds. This would ensure that Redis pods have adequate time to complete data persistence operations safely before termination. Additionally, including a note in the chart's documentation to guide users on adjusting this value based on their data size and workload would be beneficial.

### What alternatives have you considered?

- **Manual Configuration**: Users can manually set terminationGracePeriodSeconds in their values.yaml file. However, many may not be aware of the potential risks of using the default 30-second value.
- **Documentation Update Only**: Adding documentation guidance without changing the chart default could help users understand the need for customization but doesn't proactively mitigate the risk for users who overlook this setting.
- **No Change**: Leaving the current behavior unchanged continues to pose a risk for users with Redis clusters that rely on data persistence and may lead to unexpected data loss or corruption.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feedback. I will forward it to the team, but as it is not a critical feature we cannot guarantee en ETA. If you want to speed up the process you can submit a PR adding support for a `terminationGracePeriodSeconds` value that gets rendered in the StatefulSet definition. I'm not sure if that value is immutable so we may want to set it to the default to avoid bumping a major.

**Comment by sajad-sadra** [comment]
Thanks for the response. I will submit a PR for this matter.

**Comment by javsalgar** [comment]
Thank you so much!

**Comment by fmulero** [comment]
Changes in #30470 have been merged.
