### ISSUE TITLE
index.yaml 403 Forbidden

### ISSUE THREAD

**Issue by kashtan404** [bitnami/charts#30438]
### Name and Version

all

### What architecture are you using?

amd64

### What steps will reproduce the bug?
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
```

### What is the expected behavior?

Successful repo update

### What do you see instead?
```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "bitnami" chart repository (https://charts.bitnami.com/bitnami):
	failed to fetch https://charts.bitnami.com/bitnami/index.yaml : 403 Forbidden
```

**Comment by carrodher** [comment]
Not sure if there was any kind of transient error, we are not able to reproduce the issue
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
```

BTW, please note the recommended way of consuming Bitnami Helm charts is by using the [OCI packages stored in DockerHub](https://hub.docker.com/u/bitnamicharts).

**Comment by pmokeev** [comment]
@carrodher 
I can reproduce it by just using curl:
```bash
➜  ~ curl  https://charts.bitnami.com/bitnami
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2QREJBV3WMBCK5KD</RequestId><HostId>Ge0EP/zQK4MDF2tmt6RxRX784RWQrLN7CwLAvsMQsIDIuBRh0qZLZECtAcsNgxfrw8GL5QyvEAM=</HostId></Error>
```

**Comment by carrodher** [comment]
This URL is **not** designed to be used with `curl` or web browsers, it only works when adding it to the Helm client:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
```

The only browsable URL is https://charts.bitnami.com/ which redirects you to a static page with some instructions about how to add the repository to the Helm client.

With `curl` you can fetch the _index.yaml_, but that's all
```console
$ curl https://charts.bitnami.com/bitnami/index.yaml
...
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 3.8.0
    created: "2022-06-02T01:56:22.118314024Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Apache ZooKeeper provides a reliable, centralized register of configuration
      data and services for distributed applications.
    digest: sha256:f57fe57cfe2280fe4ca87ffd546b64625cf650c02cdb5b849ee0ddad06302a9b
    home: https://github.com/bitnami/charts/tree/master/bitnami/zookeeper
    icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
    keywords:
    - zookeeper
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: zookeeper
    sources:
    - https://github.com/bitnami/bitnami-docker-zookeeper
    - https://zookeeper.apache.org/
    urls:
    - https://charts.bitnami.com/bitnami/zookeeper-9.2.1.tgz
    version: 9.2.1
generated: "2023-01-09T18:56:51.100542554Z"
```

**Comment by 4erdenko** [comment]
Same problem.
```yaml
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: failed to fetch https://charts.bitnami.com/bitnami/index.yaml : 403 Forbidden
Cleaning up file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by carrodher** [comment]
I've reviewed our setup, and there haven't been any changes on our side, so it’s unclear what's causing this issue. However, here are a couple of important points to consider:
* First, please note that the recommended way to consume Bitnami Helm charts is through OCI packages hosted on DockerHub. You can find them [here](https://hub.docker.com/u/bitnamicharts).
* If you still prefer using an _index.yaml_ file (although not recommended), we also maintain a copy hosted on GitHub: https://raw.githubusercontent.com/bitnami/charts/refs/heads/archive-full-index/bitnami/index.yaml.

**Comment by vvp1983** [comment]
`...Unable to get an update from the "kc" chart repository (https://charts.bitnami.com/bitnami):
        failed to fetch https://charts.bitnami.com/bitnami/index.yaml : 403 Forbidden`

**Comment by ShapovalovIgor** [comment]
The problem persists. It works through a VPN, though. It seems like a range of addresses is blocked.

**Comment by carrodher** [comment]
> The problem persists. It works through a VPN, though. It seems like a range of addresses is blocked.

Probably related to the ongoing issue with CloudFlare, see https://www.cloudflarestatus.com/. There were no changes on our side.

**Comment by aliaksander-samuseu** [comment]
The issue is happening again, for me (I'm from Eastern Europe). My colleagues from other parts of the world report it works for them. It was working for me a week or so ago, now I see that very error mentioned in the original report. It's been like that for a couple days already.

**Comment by teja463** [comment]
Bitnami chart repo URL changed to https://repo.broadcom.com/bitnami-files/
