### ISSUE TITLE
Harbor v2.12.0

### ISSUE THREAD

**Issue by adberger** [bitnami/charts#30449]
### Name and Version

bitnami/harbor

### What is the problem this feature will solve?

Harbor [v2.12.0](https://github.com/goharbor/harbor/releases/tag/v2.12.0) was released a week ago.  
How is the bitnami helm chart updated?
Is there a trigger or manual work involved?

**Comment by carrodher** [comment]
The Helm chart is in the oven right now. For instance, the container for this new version was released some days ago at https://github.com/bitnami/containers/pull/74376. But the Helm chart is composed of several containers, we have some tests in place to ensure all those containers use the same version. At this moment, we are facing some issues to release Harbor Adapter Trivy, once those issues are fixed, the Helm chart should be released.

**Comment by carrodher** [comment]
A new Harbor version was released, see https://github.com/bitnami/charts/pull/30461 now
