### ISSUE TITLE
Unable to connect HTTPS repository: error testing repository connectivity: failed to get index: 403 Forbidden

### ISSUE THREAD

**Issue by Nello-Angelo** [bitnami/charts#30447]
### What architecture are you using?

amd64

### What steps will reproduce the bug?

connect to bitnami in argocd from Russia

Unable to connect HTTPS repository: error testing repository connectivity: failed to get index: 403 Forbidden

**Comment by carrodher** [comment]
There is a similar issue at https://github.com/bitnami/charts/issues/30438, to funnel the communication in a single place, let's close this one in favor of the existing one.

**Comment by 4erdenko** [comment]
So is this a mistake with access to https://charts.bitnami.com/bitnami/index.yaml from Russia or not?

**Comment by Nello-Angelo** [comment]
yes @4erdenko

**Comment by ShapovalovIgor** [comment]
The problem persists. It works through a VPN, though. It seems like a range of addresses is blocked.

**Comment by carrodher** [comment]
> The problem persists. It works through a VPN, though. It seems like a range of addresses is blocked.

Probably related to the ongoing issue with CloudFlare, see https://www.cloudflarestatus.com/. There were no changes on our side.
