### ISSUE TITLE
Support passing POSTGRES_INITSCRIPTS_PASSWORD from k8s secret

### ISSUE THREAD

**Issue by james64** [bitnami/charts#30469]
### Name and Version

bitnami/postgres:latest

### What is the problem this feature will solve?

This is the list of environment variables passed to the primary statefulset which contains passwords:
- `POSTGRES_PASSWORD`
- `POSTGRES_POSTGRES_PASSWORD`
- `POSTGRES_REPLICATION_PASSWORD`
- `POSTGRES_INITSCRIPTS_PASSWORD`
- `POSTGRES_LDAP_BIND_PASSWORD`

All of these have the value passed in via `valueFrom.secretKeyRef` as it should be. All of them except `POSTGRES_INITSCRIPTS_PASSWORD` which is passed by value directly in sts yaml definition.

### What is the feature you are proposing to solve the problem?

Add support for passing passwords directly or as a pre-existing secret. When passed directly add it to some secret and reference it in sts yaml using `valueFrom.secretKeyRef`. Standard stuff which already works for the rest of pg_pswd env vars.

### What alternatives have you considered?

It is possible to pass the password as part of `primary.extraEnvVarsSecret`. But that still means that `primary.initdb.password` should be updated as suggested above or removed as not useful.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
