### ISSUE TITLE
Grafana dashboard for rabbitmq

### ISSUE THREAD

**Issue by standup-jb** [bitnami/charts#3047]
Sorry. I meet a problems . I use the prometheus scrape the metric data from rabbitmq . I download the rabbitmq dashboard template in the Grafana website. But the metrics name is not fit in promethues collected. 

So is there any provided grafana dashboard template is match the rabbitmq metrics data .

**Comment by juan131** [comment]
Hi @standup-jb 

This chart uses the [rabbitmq_prometheus plugin](https://github.com/rabbitmq/rabbitmq-prometheus) (see https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L674) to expose RabbitMQ metrics. Therefore, you need to look for a Grafana dashboard compatible with its metrics.

**Comment by standup-jb** [comment]
> Hi @standup-jb
> 
> This chart uses the [rabbitmq_prometheus plugin](https://github.com/rabbitmq/rabbitmq-prometheus) (see https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L674) to expose RabbitMQ metrics. Therefore, you need to look for a Grafana dashboard compatible with its metrics.

At finally . I use this Grafana dashboard (https://grafana.com/grafana/dashboards/10991) is right . Thanks for you help .

**Comment by juan131** [comment]
Great! I'm glad you could fine a dashboard that meets your requirements.
