### ISSUE TITLE
[bitnami/etcd]: Support persistentVolumeClaimRetentionPolicy for the snapshotter volume

### ISSUE THREAD

**Issue by gozer** [bitnami/charts#30481]
### Name and Version

bitnami/etcd

### What is the problem this feature will solve?

Currently, it's possible to specify `.Values.persistentVolumeClaimRetentionPolicy` but it only affects the PVs behind the StatefulSet.

### What is the feature you are proposing to solve the problem?

It would be sensible to also support a similar setting (or reuse the same) for the PVC created for the snapshotter job.

### What alternatives have you considered?

Post-installation fixups and post-rendering, but this is impractical with [ArgoCD](https://github.com/argoproj/argo-cd/issues/3698)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
