### ISSUE TITLE
Unable to override namespace in external DNS chart

### ISSUE THREAD

**Issue by warroyo** [bitnami/charts#30497]
### Name and Version

external-dns/8.5.1

### What steps will reproduce the bug?

attempt to use the `namespaceOverride` value in the helm values

### Are you using any custom parameters or values?

`namespaceOverride`

### What is the expected behavior?

The namespace will be overridden for all objects created

### What do you see instead?

namespace is overridden for only certain objects.

### Additional information

It looks like the `namespaceOverride` value is only used in a few of the chart templates, this means it's not possible to override the ns.

**Comment by juan131** [comment]
Thanks so much @warroyo !! I just created a PR to address the issue
