### ISSUE TITLE
[bitnami/mysql] Helm installation failing 

### ISSUE THREAD

**Issue by scoutjohn** [bitnami/charts#30517]
### Name and Version

bitnami/mysql

### What architecture are you using?

minikube cluster

### What steps will reproduce the bug?

I am trying to install mysql in my minikube based on 

https://volsync.readthedocs.io/en/stable/usage/rsync-tls/mysql-migration.html#deploy-mysql

```
helm install --namespace ns-one --set auth.rootPassword=mypassword --set primary.podSecurityContext.enabled=false   --set primary.containerSecurityContext.enabled=false --set primary.persistence.storageClass=csi-hostpath-sc mysql bitnami/mysql
```

I have tried giving `--set auth.rootPassword=mypassword123` and not setting the parameter as well

I am using a namespace I already have.

**it is throwing** 

```
Error: INSTALLATION FAILED: template: mysql/templates/secrets.yaml:9:17: executing "mysql/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "mysql.secretName" .) "key" "mysql-password" "length" 10 "providedValues" (list "auth.password") "honorProvidedValues" true "context" $)>: error calling include: template: mysql/charts/common/templates/_secrets.tpl:124:16: executing "common.secrets.passwords.manage" at <eq .failOnNew false>: error calling eq: incompatible types for comparison
```

### Are you using any custom parameters or values?
```
 --set auth.rootPassword=mypassword --set primary.podSecurityContext.enabled=false --set primary.containerSecurityContext.enabled=false --set primary.persistence.storageClass=csi-hostpath-sc 
```

**Comment by scoutjohn** [comment]
the same command for mariadb seams to be working 

helm install --namespace ns-one   --set auth.rootPassword=mypassword123  --set volumePermissions.enabled=true  --set primary.service.type=LoadBalancer --set primary.containerSecurityContext.enabled=false   --set primary.persistence.storageClass=csi-hostpath-sc   mari
adb bitnami/mariadb
NAME: mariadb
LAST DEPLOYED: Tue Nov 19 18:20:40 2024
NAMESPACE: ns-one
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: mariadb
CHART VERSION: 20.0.0
APP VERSION: 11.4.4


mariadb-0         1/1     Running                 0             60s

**Comment by carrodher** [comment]
I'm not able to reproduce the error. Using the same command everything works:
```console
$ helm install --namespace ns-one --set auth.rootPassword=mypassword --set primary.podSecurityContext.enabled=false   --set primary.containerSecurityContext.enabled=false --set primary.persistence.storageClass=csi-hostpath-sc mysql bitnami/mysql --create-namespace
NAME: mysql
LAST DEPLOYED: Tue Nov 19 19:24:03 2024
NAMESPACE: ns-one
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: mysql
CHART VERSION: 12.0.0
APP VERSION: 8.4.3

** Please be patient while the chart is being deployed **

Tip:

  Watch the deployment status using the command: kubectl get pods -w --namespace ns-one

Services:

  echo Primary: mysql.ns-one.svc.cluster.local:3306

Execute the following to get the administrator credentials:

  echo Username: root
  MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace ns-one mysql -o jsonpath="{.data.mysql-root-password}" | base64 -d)

To connect to your database:
  1. Run a pod that you can use as a client:
      kubectl run mysql-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mysql:8.4.3-debian-12-r0 --namespace ns-one --env MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD --command -- bash

  2. To connect to primary service (read/write):
      mysql -h mysql.ns-one.svc.cluster.local -uroot -p"$MYSQL_ROOT_PASSWORD"

WARNING: There are "resources" sections in the chart not set. Using "resourcesPreset" is not recommended for production. For production installations, please set the following values according to your workload needs:
  - primary.resources
  - secondary.resources
+info https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
```

**Comment by scoutjohn** [comment]
hi @carrodher , Thanks for replying , I am still getting this error 

$ helm install --namespace ns-one --set auth.rootPassword=mypassword --set primary.podSecurityContext.enabled=false   --set primary.containerSecurityContext.enabled=false --set primary.persistence.storageClass=csi-hostpath-sc mysql bitnami/mysql
Error: INSTALLATION FAILED: template: mysql/templates/secrets.yaml:9:17: executing "mysql/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "mysql.secretName" .) "key" "mysql-password" "length" 10 "providedValues" (list "auth.password") "honorProvidedValues" true "context" $)>: error calling include: template: mysql/charts/common/templates/_secrets.tpl:124:16: executing "common.secrets.passwords.manage" at <eq .failOnNew false>: error calling eq: incompatible types for comparison


![image](https://github.com/user-attachments/assets/e23e162d-2d17-4d7f-9904-2d0a1c570a72)

I have just setup the helm repo. I think I am using the latest image

**Comment by scoutjohn** [comment]
@carrodher : I was having an older version of helm, I updated it to the latest and now it is running 
$ h version
version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"clean", GoVersion:"go1.22.7"}

<img width="879" alt="image" src="https://github.com/user-attachments/assets/1a1a9784-27a6-4852-8c20-3ef5e772769e">

apologies for the confusion.
