### ISSUE TITLE
password authentication failed for user "bn_keycloak"

### ISSUE THREAD

**Issue by mhazan01** [bitnami/charts#30516]
### Name and Version

bitnami/keycloak latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

 helm upgrade -i keycloak oci://registry-1.docker.io/bitnamicharts/keycloak --create-namespace -n keycloak -f values.yaml

### Are you using any custom parameters or values?

configured domain name and tls

### What is the expected behavior?

working pgsql backend

### What do you see instead?

FATAL:  password authentication failed for user "bn_keycloak"

### Additional information

no matter what, the password doesn't work in the pgsql container, including trying to connect to it from the container itself with psql

**Comment by BohdanBohatov** [comment]
This is because of "upgrade" it creates new password and places it inside container, but db still used old one. You will not fix it, just create new chart and set postgresql password in values file.
If you have old password you may place it in values.yaml, if you don't have - create new ns with db password.

```
postgresql:
  auth:
    password: "9t3tggid47"
```

**Comment by mhazan01** [comment]
Thanks, i've tried as suggest but still getting the same error. i have also tried with install instead of upgrade, same  results.

**Comment by mhazan01** [comment]
got the db to work, i was setting up a too short password in the "password:" field ? anyway it's not being used. now it works with the keycloak-postgresql : password secret which is different. but now i'm stuck with another bug from here : https://github.com/bitnami/charts/issues/30215. :(
