### ISSUE TITLE
[bitnami/keycloak] I have an ldap realm configured, how can i grant those users access to keycloak itself as an admin?

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#30514]
### Name and Version

bitnami/keycloak:latest

### What is the problem this feature will solve?

'admin' is set by default, but I'd like to be able to log in with my usual ldap user account

### What is the feature you are proposing to solve the problem?

I want to specify a ldapgroup via the helm chart whose members will be granted admin access.

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by lknite** [comment]
Helm charts for other apps such as argocd & harbor allow you to provide an oidc configuration, allowing for user login immediately after deployment.

However, given that keycloak provides the oidc being used, maybe it makes sense that it would not be possible to similarly configure it.
