### ISSUE TITLE
[bitnami/harbor] externalDatabase password mandatory

### ISSUE THREAD

**Issue by gulecroc** [bitnami/charts#30527]
### Name and Version

bitnami/harbor 24.0.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When trying to install the chart with an external database, the password is mandatory in the chart `externalDatabase.password`.

The check: https://github.com/bitnami/charts/blob/d7b125b8b6d6da047e76598d72449e71330d1ffb/bitnami/harbor/templates/_helpers.tpl#L429

I would like to only give the password with the harbor core existing envvars (`core.existingEnvVarsSecret`)

### What do you see instead?

```
Error: UPGRADE FAILED: execution error at (harbor/templates/NOTES.txt:49:3): 
VALUES VALIDATION:
harbor: External PostgreSQL password
    An external database password is required!.
    Please set a password (--set externalDatabase.password="xxxx")
```

**Comment by jotamartos** [comment]
Hi, 

Thank you for using Bitnami. That's a specific use case, as you can see the parameter is used when generating the secret

https://github.com/bitnami/charts/blob/main/bitnami/harbor/templates/core/core-secret-envvars.yaml#L39

As an alternative, you could modify the chart and [submit the contribution](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) to support a new parameter externalDatabase.existingSecret [as we have for others](https://github.com/search?q=repo%3Abitnami%2Fcharts%20externalDatabase.existingSecret&type=code).
