### ISSUE TITLE
worker report celery bug

### ISSUE THREAD

**Issue by fzhan** [bitnami/charts#30536]
### Name and Version

bitnami/airflow-22.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Install the helm package with default value
Worker responded with error: 
'''
airflow command error: argument GROUP_OR_COMMAND: invalid choice: 'celery' (choose from 'cheat-sheet', 'config', 'connections', 'dag-processor', 'dags', 'db', 'info', 'jobs', 'kerberos', 'plugins', 'pools', 'providers', 'roles', 'rotate-fernet-key', 'scheduler', 'standalone', 'sync-perm', 'tasks', 'triggerer', 'users', 'variables', 'version', 'webserver'), see help above.
'''

### Are you using any custom parameters or values?

everything default to package value

### What is the expected behavior?

worker loading as expected, no error

### What do you see instead?

airflow command error: argument GROUP_OR_COMMAND: invalid choice: 'celery' (choose from 'cheat-sheet', 'config', 'connections', 'dag-processor', 'dags', 'db', 'info', 'jobs', 'kerberos', 'plugins', 'pools', 'providers', 'roles', 'rotate-fernet-key', 'scheduler', 'standalone', 'sync-perm', 'tasks', 'triggerer', 'users', 'variables', 'version', 'webserver'), see help above.

**Comment by kirby0025** [comment]
Hello,
I'm having the same issue with the 22.4.5 version.
There is no information regarding how you fixed this, can you provide some ?

Thank you
