### ISSUE TITLE
external-dns issue with headless service and oci dns

### ISSUE THREAD

**Issue by abdelrahman-salama** [bitnami/charts#30540]
### Name and Version

bitnami/external-dns 8.5.0

### What architecture are you using?

None

### What steps will reproduce the bug?

I am trying to use external-dns in OKE to update DNS zone in OCI it's working fine, but when using it with the headless service,

The headless service tries to create an A record for the service itself that points to all the pod IPs, and external-dns returns the following error:
```
time="2024-11-17T07:44:41Z"
level=error
msg=
"Failed to do run once: soft error
Error returned by Dns Service. Http Status Code: 400. Error Code: InvalidParameter. Opc request id: 7d8e4f505de41824f26287ba25da94c1/54AB11EAE9B756D81AEA3EAFED7170E8/53346593790954C5B674BE99356FBB1A. Message: Record (xxx.example.com, A) contained invalid rdata (1.1.1.1 2.2.2.2 )
Operation Name: PatchZoneRecords
Timestamp: 2024-11-17 07:44:41 +0000 GMT
Client Version: Oracle-GoSDK/65.71.1
Request Endpoint: PATCH https://dns.me-jeddah-1.oci.oraclecloud.com/20180115/zones/ocid1.dns-zone.oc1..xxxxxxxxxx/records?compartmentId=ocid1.compartment.oc1..xxxxxxxxxxxxnTroubleshooting Tips: See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_invalidparameter for more information about resolving this error.
Also see https://docs.oracle.com/iaas/api/#/en/dns/20180115/Records/PatchZoneRecords for details on this operation's requirements.
To get more info on the failing request, you can set OCI_GO_SDK_DEBUG env var to info or higher level to log the request/response details.
If you are unable to resolve this Dns issue, please contact Oracle support and provide them this full error message."
```

### What is the expected behavior?

Create the record successfully

### What do you see instead?

contained invalid rdata

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by abdelrahman-salama** [comment]
Thanks for your response, and to be clear, I am not doing any custom or specific configuration in my environment.

It's a basic work, the default behavior for external-dns with headless service is to create an A for each pod and create A record for the main domain pointing to all pods ips, and this setup is working fine with aws route53 but not with oracle cloud zone.
