### ISSUE TITLE
Infoxblox no more supported in in-tree App Version 0.15.0

### ISSUE THREAD

**Issue by Lolelinus13** [bitnami/charts#30557]
### Name and Version

bitnami/external-dns

### What architecture are you using?

None

### What steps will reproduce the bug?

In the https://github.com/kubernetes-sigs/external-dns/pull/4516/ (change for app version 0.15.0) the Infoblox got removed from the in-tree. Therefore you can't use the Infoblox values anymore.  

### What is the expected behavior?

Could you rewrite the helm chart so that it also works with the new WebHook approach for Infoblox.

### What do you see instead?

When you run the helm chart version 8.5.1 with the App Version 0.15.0 with the Infoblox values it fails with the error grid.Host env is not supported.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
