### ISSUE TITLE
Problem with deployment using helm chart bitnami/contour 19.3.1 in k8s

### ISSUE THREAD

**Issue by vldanch** [bitnami/charts#30556]
### Name and Version

bitnami/contour 19.3.1

### What architecture are you using?

None

### What steps will reproduce the bug?

```
kube_context="k8s-dev" ; \
kube_namespace="ingress-internal" ; \
helm_chartname="contour" ; \
helm upgrade \
    --kube-context ${kube_context} \
    --namespace ${kube_namespace} --create-namespace \
    --install ${kube_namespace}-${helm_chartname} ./19.3.1 \
    --values ./19.3.1/values-dev.yaml
```

### What do you see instead?

Logs(ingress-internal/ingress-internal-contour-contour-86dbf945-stnjv:contour)
```
time="2024-11-21T09:08:10Z" level=info msg="maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS"                                                                                                       
time="2024-11-21T09:08:10Z" level=info msg="args: [serve --incluster --xds-address=0.0.0.0 --xds-port=8001 --http-port=8000 --envoy-service-http-port=8080 --envoy-service-https-port=8443 --contour-cafile=/certs/ca
time="2024-11-21T09:08:10Z" level=fatal msg="failed to create informer" error="no matches for kind \"ExtensionService\" in version \"projectcontour.io/v1alpha1\"" resource=extensionservices   
```
Logs(ingress-internal/ingress-internal-contour-envoy-cht7v:envoy)
```
[2024-11-21 09:13:18.664][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:214] StreamClusters gRPC config stream to contour closed since 277s ago: 14, upstream connect error or disc
onnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: Connection refused                                                                            
[2024-11-21 09:13:26.660][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:214] StreamRuntime gRPC config stream to contour closed since 300s ago: 14, upstream connect error or disco
nnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: Connection refused                                                                             
[2024-11-21 09:13:32.776][1][warning][config] [./source/extensions/config_subscription/grpc/grpc_stream.h:214] StreamRuntime gRPC config stream to contour closed since 306s ago: 14, upstream connect error or disco
nnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: Connection refused
```

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
