### ISSUE TITLE
[bitnami/elasticsearch] 21.3.25 Chart.lock specifies mismatched version of Kibana

### ISSUE THREAD

**Issue by jcox10** [bitnami/charts#30567]
### Name and Version

bitnami/elasticsearch 21.3.25

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy with helm chart elasticsearch version 21.3.25
2. Enable Kibana
3. Check the versions.

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

The versions should match. The [ES documentation](https://github.com/elastic/kibana?tab=readme-ov-file#version-compatibility-with-elasticsearch) says the versions should match, else a warning is logged.

### What do you see instead?

Versions not matched.  Elasticsearch = 8.16.0 and kibana = 8.15.3. Warning is logged in Kibana.

### Additional information

The chart.lock file needs to be updated so it is pointing to kibana chart version 11.3.1

**Comment by javsalgar** [comment]
Hi!

Thanks for reporting. This was fixed in this PR https://github.com/bitnami/charts/issues/30594. Please update to 21.3.26
