### ISSUE TITLE
fluentd metrics endpoints return connection refused

### ISSUE THREAD

**Issue by davejhahn** [bitnami/charts#3056]
**Which chart**:
fluentd-1.2.7

**Describe the bug**
Installation with metrics.enabled= true, metrics.serviceMonitor.enabled=true, and metrics.serviceMonitor.namespace set (to monitoring in my case) creates Service Monitor and fluentd-metrics service but there are no metrics endpoints accessible.

**To Reproduce**
1. Install Prometheus-Operator
2. Install bitnami fluentd helm chart, with --set metrics.enabled=true,metrics.serviceMonitor.enabled=true,metrics.serviceMonitor.namespace=<namespace>
3. Visit prometheus and Targets
4. Metric endpoints reporting as Down, with all targets show Get "http://10.244.0.119:24231/metrics": dial tcp 10.244.0.119:24231: connect: connection refused for equivalent IP

**Expected behavior**
Endpoints reporting UP

**Version of Helm and Kubernetes**:
1.16.9 AKS

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Not sure where the metrics are supposed to be served from, there is no additional pods or sidecars created, unless it's built into Fluentd.

**Comment by Dexolite** [comment]
@davejhahn What was the issue in your case ? Enabled metrics, from within the pod:

```
root@fluentd-8h5pn:/opt/bitnami/fluentd# curl 127.0.0.1:24231/metrics
curl: (7) Failed to connect to 127.0.0.1 port 24231: Connection refused
```

**Comment by davejhahn** [comment]
@Dexolite it's been a while since I worked on this, to be honest I don't remember what specifically I did to get it working.  Looking at my deployment, it wasn't anything different than what I had above.

In case it helps, below are the parameters I am passing to the helm chart:

--set aggregator.configMap=elasticsearch-output --set forwarder.configMap=container-parser --set aggregator.extraEnv[0].name=ELASTICSEARCH_HOST --set aggregator.extraEnv[0].value=elasticsearch-elasticsearch-coordinating-only.logging.svc.cluster.local --set aggregator.extraEnv[1].name=ELASTICSEARCH_PORT --set-string aggregator.extraEnv[1].value=9200 --set metrics.enabled=true --set metrics.serviceMonitor.enabled=true --set metrics.serviceMonitor.namespace=monitoring

I did create a custom image (using the Bitnami image as the base), not because of Prometheus issues, but to add a couple of plugins unrelated, so image.repository, image.registry, and image.tag are also set but is not listed above.  That had nothing to do with solving it though, I added that after the fact.

It doesn't create an additional container or sidecar, it serves it out of each of the containers, so with default settings, 4 pods should appear in Prometheus.

Not sure this helps or not, but maybe you can compare it against what you have and see if anything jumps out as different.

**Comment by Dexolite** [comment]
After some reading, I needed to Expose Metrics by Prometheus Input Plugin via HTTP. 
Basically this: https://docs.fluentd.org/monitoring-fluentd/monitoring-prometheus

Not as easy as just enabling metrics :) Glad you resolved is @davejhahn, take care !

**Comment by davejhahn** [comment]
@Dexolite yep, that was it.  When i read your update it reminded me of doing that.  I had added to my conifg as well.  Glad you got it working, sorry my brain stopped functioning lol.
