### ISSUE TITLE
wordpress Version 24.0.6 at ArtifactHUB (helm)

### ISSUE THREAD

**Issue by titver968** [bitnami/charts#30561]
### Name and Version

bitnami/wordpress 24.0.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The command: 
`helm pull --destination /tmp --version 24.0.6 --repo https://charts.bitnami.com/bitnami wordpress` ends with error:
```
Error: invalid_reference: invalid tag
```

**Comment by titver968** [comment]
The Version 24.0.4 can be installed.

**Comment by carrodher** [comment]
Please note the recommended way of consuming Bitnami Helm charts is using the OCI package hosted in DockerHub:
```
helm pull oci://registry-1.docker.io/bitnamicharts/wordpress --version 24.0.6
```

However, if you're using the Bitnami index.yaml, please note you need to add it to the Helm CLI and keep it up to date:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
 search repo bitnami/wordpress
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo bitnami/wordpress
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/wordpress      	24.0.6       	6.7.0      	WordPress is the world's most popular blogging ...

$ helm pull --version 24.0.6 bitnami/wordpress
$ ls -la
...
-rw-r--r--   1 carlosrh  staff   152K Nov 21 17:26 wordpress-24.0.6.tgz
```

Any other way of consuming Bitnami charts could not be supported.

**Comment by titver968** [comment]
THX, I've changed to oci and it's works. You can close the ticket.
