### ISSUE TITLE
[bitnami/elasticsearch] `invalid tag` with version `21.3.26`

### ISSUE THREAD

**Issue by drehelis** [bitnami/charts#30617]
### Name and Version

bitnami/elasticsearch 21.3.26

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
helm pull --destination /tmp/ --version 21.3.26 --repo https://charts.bitnami.com/bitnami elasticsearch --debug
```

### What do you see instead?

```
Error: invalid_reference: invalid tag
helm.go:84: [debug] invalid_reference: invalid tag
```

### Additional information

Version 21.3.25 works.

**Comment by chintai-paul** [comment]
Same issue with `postgresql` chart version `16.2.2`. Version `16.2.1` works.
```
# Failing:
helm --kube-context pohlhauser install postgresql postgresql --namespace default --repo https://charts.bitnami.com/bitnami --create-namespace
# Working:
helm --kube-context pohlhauser install postgresql --version 16.2.1 postgresql --namespace default --repo https://charts.bitnami.com/bitnami --create-namespace
# Also working:
helm repo add bitnami https://charts.bitnami.com/bitnami
helm upgrade --install postgresql bitnami/postgresql --namespace default
```

**Comment by carrodher** [comment]
As reported in https://github.com/helm/helm/issues/13466, this problem stems from how the `helm ... --repo ...` command handles an _index.yaml_ file containing OCI URLs.

### Why is this issue appearing now?
Historically, Bitnami Helm charts were accessed by adding the Bitnami repository to the Helm CLI:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```
or by directly installing/pulling a specific Helm chart using the `--repo` flag:
```
$ helm pull --repo https://charts.bitnami.com/bitnami foo
```

In April 2023, [Bitnami introduced support for the OCI format](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html), recommending OCI-based installation as the primary method going forward. For example:
```
helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 8.6.0
```

As detailed in our [recent announcement](https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html) and https://github.com/bitnami/charts/issues/30110, the traditional method is now being deprecated. Consequently, the _index.yaml_ served at `https://charts.bitnami.com/bitnami` now uses OCI URLs, exposing the above mentioned issue in the Helm CLI's handling of these URLs.

**Comment by drehelis** [comment]
Changing `https://charts.bitnami.com/bitnami` to `registry-1.docker.io/bitnamicharts` in my ArgoCD app did the trick, I only needed to add an OCI registry in Argo first.
