### ISSUE TITLE
Multi-disk support for Clickhouse

### ISSUE THREAD

**Issue by NBMSacha** [bitnami/charts#30620]
### Name and Version

bitnami/clickhouse

### What is the problem this feature will solve?

Currently, it is only possible to mount one volume via the bitnami clickhouse helm chart. Would be great to be able to mount multiple volumes, as some clickhouse config enable different storage classes.

### What is the feature you are proposing to solve the problem?

Changing the persistentStorage spec to an array.

### What alternatives have you considered?

Moving out of the helm chart or forking it

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
