### ISSUE TITLE
Question: correct Redis connection string

### ISSUE THREAD

**Issue by joesimon0102** [bitnami/charts#3064]
Hi All,

I have deployed Redis into K8s but I'm not able to connect to it from a backend API which is already inside K8s in the same namespace.
I tried a lot of different connection string to connect to Redis but I couldn't succeed.

My question how can I find out what Redis connection string should I use inside my backend API?
Can I query it from somehow with help of kubectl?

I'm using this: https://github.com/bitnami/charts/tree/master/bitnami/redis chart.

**Comment by rafariossaa** [comment]
Hi,
  When you run helm install you will get some instructions on how to connect to. 
E.g.:
```
$ helm install my-release bitnami/redis
NAME: my-release
LAST DEPLOYED: Thu Jul  9 08:53:19 2020
NAMESPACE: rafael
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **
Redis can be accessed via port 6379 on the following DNS names from within your cluster:

my-release-redis-master.rafael.svc.cluster.local for read/write operations
my-release-redis-slave.rafael.svc.cluster.local for read-only operations


To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace rafael my-release-redis -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis server:

1. Run a Redis pod that you can use as a client:
   kubectl run --namespace rafael my-release-redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:6.0.5-debian-10-r23 -- bash

2. Connect using the Redis CLI:
   redis-cli -h my-release-redis-master -a $REDIS_PASSWORD
   redis-cli -h my-release-redis-slave -a $REDIS_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace rafael svc/my-release-redis-master 6379:6379 &
    redis-cli -h 127.0.0.1 -p 6379 -a $REDIS_PASSWORD
```
  To get this information from your current running chart, you can do:
```
$ helm get notes my-release
```
  where `my-release` is the name you gave to the chart.
  You can get your running charts with:
```
$ helm list
```

**Comment by joesimon0102** [comment]
Thanks I'll try this out.

**Comment by rafariossaa** [comment]
You are welcome.
 Please don't hesitate to share your findings.

**Comment by joesimon0102** [comment]
Thanks for you help, it works.

**Comment by deepakkrmodi** [comment]
@rafariossaa I was trying to use the instruction, and once i run this command : kubectl run --namespace rafael my-release-redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:6.0.5-debian-10-r23 -- bash

and then i tried running next command : redis-cli -h my-release-redis-master -a $REDIS_PASSWORD

It says redis-client : command not found. but my redis-client pod is running.

Is there any mistake i am making? Please help me. TIA :)

**Comment by rafariossaa** [comment]
Hi,
  Have into account you need to adjust the namespace to the namespace you are using.
  In any case, this issue is closed and yours seem to be another problem. 
  Do you mind to open a new issue and add the commands you run and the log you got ? This way we are not mixing issue and we can help better.

Thanks forehand.
