### ISSUE TITLE
When Prometheus and Thanos sidecar are launched simultaneously, should the Thanos sidecar launch configuration tsdb.path point to the Prometheus storage.tsdb.path-defined TSDB database data directory?

### ISSUE THREAD

**Issue by vitaaaaa1** [bitnami/charts#30655]
### Name and Version

bitnami/thanos-15.8.1

### What architecture are you using?

None

### What steps will reproduce the bug?

I am using Bitnami's Helm Chart to install Prometheus + Thanos sidecar, but I found that the default Prometheus uses the tsdb data directory path of `--storage.tsdb.path=/bitnami/prometheus/data`, while the Thanos sidecar points to the Prometheus tsdb data directory of `--tsdb.path=/prometheus/`. It's strange that the sidecar can work normally and upload tsbd data blocks to Minio, which is confusing. Am I misunderstanding the meaning of the tsdb.path parameter, or does the sidecar not need to access the Prometheus tsdb data directory to upload data blocks?

### What is the expected behavior?

![image](https://github.com/user-attachments/assets/ff08578b-50cd-4e50-b323-ced1e04a9bf3)
![image](https://github.com/user-attachments/assets/30d5cc0d-e0f2-487e-8b6c-5155023cd822)

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
