### ISSUE TITLE
Unable to download ELK chart information

### ISSUE THREAD

**Issue by hw2822** [bitnami/charts#30653]
### Name and Version

bitnami/logstash

### What architecture are you using?

None

### What steps will reproduce the bug?

I can't download the chart information by running `helm show all bitnami/logstash` but other charts like kafka and jenkins are fine

### What do you see instead?
```
Error: failed to download "bitnami/logstash"
```

**Comment by hw2822** [comment]
I am using lens on windows. Seems lens is always fecthing the latest version 

when I run `helm pull bitnami/logstash` I got 
`cannot rename d:\Users\local_xxxxx\Temp\logstash:6.3.9-.tgz099912535 to logstash:6.3.9-.tgz: rename d:\Users\local_hwxxxx\Temp\logstash:6.3.9-.tgz099912535 logstash
:6.3.9-.tgz: The parameter is incorrect.` 

But when I try version 6.3.8 it was successful.

**Comment by carrodher** [comment]
Historically, Bitnami Helm charts were accessed by adding the Bitnami repository to the Helm CLI:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```
or by directly installing/pulling a specific Helm chart using the `--repo` flag:
```
$ helm pull --repo https://charts.bitnami.com/bitnami foo
```

In April 2023, [Bitnami introduced support for the OCI format](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html), recommending OCI-based installation as the primary method going forward. For example:
```
helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 8.6.0
```

As detailed in our [recent announcement](https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html) and https://github.com/bitnami/charts/issues/30110, the traditional method is now being deprecated. Consequently, the _index.yaml_ served at `https://charts.bitnami.com/bitnami` now uses OCI URLs, probably it is an issue in [_lens_](https://github.com/lensapp/lens) about how it handles OCI URLs, you should open an issue there looking for a solution in that tool.
