### ISSUE TITLE
[bitnaim/kafka] Apache Kafka Tiered Storage 

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#30657]
### Name and Version

Bitnami/Kafka 3.9.0

### What is the problem this feature will solve?

In Bitnami Kafka helm charts tiered storage is enabled. If not can you please help us how to enable it?

**Comment by javsalgar** [comment]
Hi,

I don't think we enable this feature by default. However, the chart allows you to use the `extraConfig` section where you can include additional settings. There you can set the necessary values to enable tiered storage. I didn't find the official documentation but in this link you can see example values that you can set in the extraConfig section https://developers.redhat.com/articles/2023/11/22/getting-started-tiered-storage-apache-kafka#set_up_an_s3_bucket_and_iam_credentials_in_aws

**Comment by bharathreddy901** [comment]
Thanks you @javsalgar for info.
