### ISSUE TITLE
An error occurred while fetching the catalog: Unable to get the available package detail for the package "bitnami/mysql" using the plugin "helm.packages": internal: Unable to retrieve chart files: sql: no rows in result set.

### ISSUE THREAD

**Issue by fea359** [bitnami/charts#30668]
### Name and Version

bitnami/mysql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When I searched for mysql, tomcat, and redis using kubeapps, I was able to find these applications, but when I deployed them, it prompted: "An error occurred while fetching the catalog: Unable to get the available package detail for the package "bitnami/mysql" using the plugin "helm.packages": internal: Unable to retrieve chart files: sql: no rows in result set."
But helm search was able to search and install them.
I found the mysql record in the database files, and indeed did not find the record of 12.1.0, but I found the record of 12.0.0, and then I changed 12.0.0 to 12.1.0 and it succeeded. There are many similar situations, such as redis-cluster.
The root cause is that the records in the files table in PostgreSQL have not been updated in a timely manner.

### Are you using any custom parameters or values?

no

### What do you see instead?

![image](https://github.com/user-attachments/assets/0119cb4b-fe11-4999-927e-bcf694727da2)
![image](https://github.com/user-attachments/assets/137a8cd4-ebef-4e50-9fbe-c922650acc32)
![image](https://github.com/user-attachments/assets/5747a51b-72b0-460c-b997-904ba43d94a8)
![image](https://github.com/user-attachments/assets/68b5a3de-e593-4806-a848-e357ad0ce940)
![image](https://github.com/user-attachments/assets/3956d556-0e5c-4638-b348-e27dbc9aaa48)
![image](https://github.com/user-attachments/assets/bfa3b214-4417-4712-be60-94908aa5ea98)
![image](https://github.com/user-attachments/assets/5f28c137-00b0-4c60-ac77-f49df1c078a9)
![image](https://github.com/user-attachments/assets/a92bd93d-7635-4d93-8869-2f61f0d37973)

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side. Probably the best place to look for support is at https://github.com/vmware-tanzu/kubeapps.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.
