### ISSUE TITLE
[bitnami/mongodb] Invalid port name for mongo services

### ISSUE THREAD

**Issue by chris922** [bitnami/charts#3067]
_Originally posted in https://github.com/bitnami/charts/pull/2918_

Hey @juan131 , we just installed mongo using version 8.0.7 of the mongodb chart and noticed that we aren't able to connect to the deployed mongo using this connection string: `mongodb+srv://mongodb-headless.persistence.svc.cluster.local`

I found out that the reason is, that the port within the `mongodb-headless` service is named `tcp-mongodb` instead of `mongodb` and then I found this change here.

Could you please have a look again at your changes and ensure that connecting to mongo via `srv` still works?
This also affects the other service definitions that you created during your refactorings.

More information about this: 
* https://www.mongodb.com/blog/post/mongodb-3-6-here-to-SRV-you-with-easier-replica-set-connections -> mongo prepends `_mongodb._tcp` to the hostname 
* https://kubernetes.io/docs/concepts/services-networking/service/#dns: k8s is using the port name + protocol in the SRV DNS entry as a prefix

**Comment by chris922** [comment]
@juan131 I just changed all port names (to keep them in sync even if it is maybe not required for the non-headless services) and raised a PR. Hopefully I haven't missed something.

**Comment by juan131** [comment]
Hi @chris922 

Did you try adapting your connection string to `tcp-mongodb+srv://mongodb-headless.persistence.svc.cluster.local`?

The reason behind using `tcp-mongodb` as port name is to be compatible with [Istio](https://istio.io), since it requires the ports to be prefixed with the protocol name.

**Comment by chris922** [comment]
Just tried the connection string and unfortunately it is not working, the Java mongo driver fails:

> The connection string is invalid. Connection strings must start with either 'mongodb://' or 'mongodb+srv://

Regarding Istio: You are probably referring to this page here?
-> https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

As it defines a `mongo` protocol the port name should then be `mongo-mongodb`. 

Nevertheless with K8s 1.18+ the `appProtocol` field will be supported. Maybe it's better to use this one (in case K8s 1.18+ will be used) and stick to the mongo convention and keep the port named `mongodb`?

Even better: If the type could not be defined Istio will treat it as TCP so it might not be that important at all.

> If the protocol cannot automatically be determined, traffic will be treated as plain TCP traffic.

**Comment by dani8art** [comment]
hi @chris922 , does it fit yours requirements?

```bash
$ export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongo-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

$ kubectl run --namespace default mongo-mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.2.8-debian-10-r7 --command -- mongo "mongodb://mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local,mongo-mongodb-1.mongo-mongodb-headless.default.svc.cluster.local" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```

I'm able to connect using this.

**Comment by chris922** [comment]
Thanks @dani8art , this works, but we would like to use the SRV DNS entry to connect so that we don't need to define all available pods in our applications. They should just connect to one static name (the SRV entry) and resolve the nodes automatically.

Using your method we would need to update the connection strings in all our applications everytime we scale up/down our mongo nodes.

**Comment by juan131** [comment]
Hi @chris922

If you're configuring MongoDB as a replicaset and you want to access it from outside the K8s cluster, then you'll have to update the connection strings with the list of external services (one per MongoDB node) to use. Check the section "Replicaset: Accessing MongoDB nodes from outside the cluster" in the **README.md**.

This is sth typical in MongoDB. You application should know the whole list of nodes available, and auto-discover which node has the "primary" role (checking the rs status). It makes no sense to access MongoDB through a service which is pointing both to "primary" and "secondary" nodes, because it can eventually redirect you to a secondary node which doesn't accept write operations.

**Comment by chris922** [comment]
Thanks @juan131 , I just had a look at the mentioned chapter, but we don't need to access the mongo from outside our k8s cluster.

Since MongoDB 3.6 it is possible to use a DNS SRV record, see https://www.mongodb.com/blog/post/mongodb-3-6-here-to-SRV-you-with-easier-replica-set-connections

Using this the client doesn't need to know the nodes of the replica set and instead just need to know the DNS SRV entry. It will then get the list of nodes by resolving this DNS entry.

We would like to use this type of connection, but therefore the mongo port has to be named `mongodb` instead of `tcp-mongodb`. Right now as a workaround we create an additional headless service with the correct port name to solve this. But it should be much easier if this chart will use the required port name for its headless service.

**Comment by juan131** [comment]
I see @chris922 ... Thanks for providing the whole context.

Let's move back to `mongodb` name.. Do you see any cons @javsalgar @dani8art? I did some testing and there's no issue while upgrading existing releases. That said, users will have to adapt (again) their apps configuration.

**Comment by javsalgar** [comment]
If the port name has this kind of consequences in the applications, maybe it makes sense to allow setting the name as a value. Wouldn't that work for most of the users with different apps configurations?

**Comment by dani8art** [comment]
I agree with @javsalgar , we could make it configurable in the `values.yaml` so people that want to use istio will still able to do it and people that want to use DNS SRV too. I see two way of doing so:

```yaml
istio:
  enabled: false
```

or 

```yaml
...
   service:
     portName: tcp-mongodb
...
```

**Comment by juan131** [comment]
I'd rather use the second approach. The reason to use a specific port name can be related with Istio but also with other reasons.

**Comment by chris922** [comment]
As I already mentioned in one of my previous comments I think even for Istio the `tcp-` prefix is not required, because Istio will treat it by default as tcp. We are also using Istio that still works naming the port just `mongodb` (but it's maybe related to the Istio config).

> If the protocol cannot automatically be determined, traffic will be treated as plain TCP traffic.

_(see https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)_

And if you want to improve something here when using Istio the protocol name would be `mongo` and thus the port name should be `mongo-mongodb`.

Or multiple services could be created, one for DNS SRV and one for Istio.
