### ISSUE TITLE
[bitnami/etcd] snapshot PVCs deleted after uninstall

### ISSUE THREAD

**Issue by felpasl** [bitnami/charts#30672]
### Name and Version

bitnami/etcd

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. After installing etcd with `disasterRecovery.enabled=true`, the snapshot PVCs are created as expected to store scheduled backups.
2. However, after uninstalling etcd from the cluster, the snapshot PVCs are deleted.
3. The expected behavior is to maintain the snapshots for maintenance, migration, or recovery actions.

### Are you using any custom parameters or values?

disasterRecovery:
  enabled: true

### What is the expected behavior?

after uninstalling etcd from the cluster, the snapshot PVCs are deleted, The expected behavior is to maintain the snapshots for maintenance, migration, or recovery actions.

### What do you see instead?

the snapshot PVCs are deleted

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Indeed, it makes total sense that the snapshot PVC should be kept when uninstalling the release. The PVC object (snapshot-pvc.yaml) would be missing this annotation. 

```
    helm.sh/resource-policy: keep
```

As you discovered the issue, would you like to submit a PR?
