### ISSUE TITLE
[bitnami/template] HPA wrong context and yaml path assumed

### ISSUE THREAD

**Issue by sinux-l5d** [bitnami/charts#30713]
### Name and Version

bitnami/template 0.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

The context passed to "`common.capabilities.hpa.apiVersion` in the template to create charts seems invalid.
Currently ,we have: https://github.com/bitnami/charts/blob/35ab5363741e7548f4076f04da6e62d10153c60c/template/CHART_NAME/templates/hpa.yaml#L7

Which could produce "Invalid Semantic Version" error when HPA is enabled.

Moreover, the path to the autoscaling block is assumed to be in `.Values.worker` in two places : 
https://github.com/bitnami/charts/blob/35ab5363741e7548f4076f04da6e62d10153c60c/template/CHART_NAME/templates/hpa.yaml#L34
https://github.com/bitnami/charts/blob/35ab5363741e7548f4076f04da6e62d10153c60c/template/CHART_NAME/templates/hpa.yaml#L46

### What do you see instead?

As mentioned in https://github.com/bitnami/charts/pull/17444#pullrequestreview-1537055133, the contexted passed should be, for example, like this:  
https://github.com/bitnami/charts/blob/35ab5363741e7548f4076f04da6e62d10153c60c/bitnami/nginx/templates/hpa.yaml#L7

The YAML path to the autoscaling block should be `.Values.%%MAIN_OBJECT_BLOCK%%.autoscaling` just like in the rest of the file.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
