### ISSUE TITLE
Request for apache NiFi chart

### ISSUE THREAD

**Issue by yahavHalfon** [bitnami/charts#30710]
### Name and Version

apache-nifi

### What is the problem this feature will solve?

NiFi 2.0 has recently been released, introducing several significant enhancements. We would like to have a Bitnami Helm chart that supports deploying an Apache NiFi high-availability cluster. This would enable the efficient and reliable use of NiFi in a production-grade environment, ensuring scalability and fault tolerance.

### What is the feature you are proposing to solve the problem?

A Bitnami Helm chart for Apache NiFi that supports:

High availability: The ability to deploy a highly available NiFi cluster with multiple nodes.
Simplified configuration: Helm values for setting the number of cluster nodes, enabling secure communication (SSL/TLS) .
Persistence: Persistent storage options for maintaining flow state and other critical data across restarts.
Scalability: Easy scaling of NiFi nodes.
Monitoring integration: Metrics support for Prometheus and Grafana, to monitor cluster health and performance.
Security: Options for enabling authentication, role-based access control (RBAC), and secure communication.

### What alternatives have you considered?

Manually configuring NiFi clusters using the Apache-provided deployment methods. However, these are complex, prone to human error, and not as user-friendly as the Bitnami Helm chart ecosystem.

**Comment by carrodher** [comment]
Thanks for the suggestion, unfortunately, this asset was evaluated and discarded at https://github.com/bitnami/charts/issues/5208.
If at some point it's re-evaluated, we'll update this ticket.
