### ISSUE TITLE
redis slave not being promoted to master

### ISSUE THREAD

**Issue by horacimacias** [bitnami/charts#30729]
### Name and Version

bitnami/redis-cluster:11.1.0

### What architecture are you using?

None

### What steps will reproduce the bug?

Install chart
```bash
helm install redis-service -n redis-cluster oci://registry-1.docker.io/bitnamicharts/redis-cluster --set fullnameOverride=redis-service,usePassword=false,persistence.enabled=true --create-namespace
```

Everything works ok and master-slaves are "paired" correctly (no node has both master and slave).

```bash
redis-cli cluster nodesc7ac23aa260f304d30634c1807e81cfe6a19e81a 10.32.2.174:6379@16379 slave 6ca70683b1f09042fb2469659e7c88df8a002550 0 1733225257389 2 connected
94956623a32ff207e0581b954465ad1bb0d20631 10.32.0.195:6379@16379 slave 58abc2ad85f48a434c7d15544272b5d868372412 0 1733225257000 3 connected
6ca70683b1f09042fb2469659e7c88df8a002550 10.32.1.74:6379@16379 master - 0 1733225255000 2 connected 5461-10922
f920fc9ba78c4758a0e1e8dbd34bd22877e08cd0 10.32.1.186:6379@16379 slave 2f992a8a7677731aae5d16cbd75679dced5a8862 0 1733225257000 1 connected
2f992a8a7677731aae5d16cbd75679dced5a8862 10.32.0.33:6379@16379 myself,master - 0 0 1 connected 0-54605
8abc2ad85f48a434c7d15544272b5d868372412 10.32.2.206:6379@16379 master - 0 1733225256379 3 connected 10923-16383
```

shutdown node 0, where master 10.32.0.33 and slave 10.32.0.195 are running.
The slave of the failed master is promoted. The cluster is still ok.

```bash
redis-cli cluster nodes
f920fc9ba78c4758a0e1e8dbd34bd22877e08cd0 10.32.1.186:6379@16379 master - 0 1733225730832 7 connected 0-5460
58abc2ad85f48a434c7d15544272b5d868372412 10.32.2.206:6379@16379 master - 0 1733225732847 3 connected 10923-163839
4956623a32ff207e0581b954465ad1bb0d20631 10.32.0.195:6379@16379 slave,fail 58abc2ad85f48a434c7d15544272b5d868372412 1733225603752 1733225597000 3 connected
2f992a8a7677731aae5d16cbd75679dced5a8862 10.32.0.33:6379@16379 master,fail - 1733225602745 1733225598000 1 connected
6ca70683b1f09042fb2469659e7c88df8a002550 10.32.1.74:6379@16379 myself,master - 0 0 2 connected 5461-10922
c7ac23aa260f304d30634c1807e81cfe6a19e81a 10.32.2.174:6379@16379 slave 6ca70683b1f09042fb2469659e7c88df8a002550 0 1733225731933 2 connected
```

start node 0 again. The two pods on this node are now slaves.

```bash
redis-cli cluster nodes
f920fc9ba78c4758a0e1e8dbd34bd22877e08cd0 10.32.1.186:6379@16379 master - 0 1733226021539 7 connected 0-5460
58abc2ad85f48a434c7d15544272b5d868372412 10.32.2.206:6379@16379 master - 0 1733226020000 3 connected 10923-16383
94956623a32ff207e0581b954465ad1bb0d20631 10.32.0.166:6379@16379 slave 58abc2ad85f48a434c7d15544272b5d868372412 0 1733226021000 3 connected
2f992a8a7677731aae5d16cbd75679dced5a8862 10.32.0.77:6379@16379 slave f920fc9ba78c4758a0e1e8dbd34bd22877e08cd0 0 1733226020000 7 connected
6ca70683b1f09042fb2469659e7c88df8a002550 10.32.1.74:6379@16379 myself,master - 0 0 2 connected 5461-10922
c7ac23aa260f304d30634c1807e81cfe6a19e81a 10.32.2.174:6379@16379 slave 6ca70683b1f09042fb2469659e7c88df8a002550 0 1733226019361 2 connected

```

At this point, node 1 has two masters, 10.32.1.186 and 10.32.1.74

```bash
redis-cli cluster nodes
94956623a32ff207e0581b954465ad1bb0d20631 10.32.0.166:6379@16379 slave 58abc2ad85f48a434c7d15544272b5d868372412 0 1733227175766 3 connected
c7ac23aa260f304d30634c1807e81cfe6a19e81a 10.32.2.174:6379@16379 slave 6ca70683b1f09042fb2469659e7c88df8a002550 0 1733227175000 2 connected
58abc2ad85f48a434c7d15544272b5d868372412 10.32.2.206:6379@16379 master - 0 1733227174708 3 connected 10923-163832
f992a8a7677731aae5d16cbd75679dced5a8862 10.32.0.77:6379@16379 myself,slave f920fc9ba78c4758a0e1e8dbd34bd22877e08cd0 0 0 7 connected
6ca70683b1f09042fb2469659e7c88df8a002550 10.32.1.74:6379@16379 master,fail? - 1733227010499 1733227004000 2 connected 5461-10922
f920fc9ba78c4758a0e1e8dbd34bd22877e08cd0 10.32.1.186:6379@16379 master,fail? - 1733227006471 1733227002378 7 connected 0-5460

```

the two masters on the failed node (10.32.1.74 and 10.32.1.186) continue to show "fail?". 
Their associated slaves (10.32.2.174 and 10.32.0.77) are not promoted to masters ever.
With only one master, the cluster is not working.

### Are you using any custom parameters or values?
```
--set fullnameOverride=redis-service,usePassword=false,persistence.enabled=true
```
### What is the expected behavior?

The slaves should be promoted to masters when/if their respective master fails.

### What do you see instead?

Slaves are not promoted to masters.

**Comment by carrodher** [comment]
Hi, the issue may not be directly related to the Bitnami container image/Helm chart, but rather to how the application is being utilized, configured in your specific environment, or tied to a particular scenario that is not easy to reproduce on our side.

If you think that's not the case and want to contribute a solution, we'd like to invite you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Please feel free to contact us if you have any questions or need assistance.

Suppose you have any questions about the application, customizing its content, or technology and infrastructure usage. In that case, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by hmacias-avaya** [comment]
thanks. I thought this chart would somehow "remember" or enforce which pod replicas are a master, which are a slave, and how masters and slaves are paired.
After doing some more tests I believe this is not the case; the chart only treats the first replica as the "cluster creator" and everybody else the same. So, my expectation that a slave promoted to master due to master failure would be demoted back to slave once the master was back up, is incorrect.

If there is any documentation or anybody has any pointers to relevant source code that controls who becomes a master, who becomes a slave and how masters and slaves are paired together, please let me know.
