### ISSUE TITLE
[bitnami/redis-cluster] redis-cluster puts master and slave on the same kubernetes node

### ISSUE THREAD

**Issue by horacimacias** [bitnami/charts#30728]
### Name and Version

bitnami/redis-cluster:11.1.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install chart:

```bash
helm install redis-service -n redis-cluster oci://registry-1.docker.io/bitnamicharts/redis-cluster --set fullnameOverride=redis-service,usePassword=false,persistence.enabled=true --create-namespace
```

Retrieve redis cluster information:

```
528c541ee1faca8dd78fcf3dae5e0462d06f2c9c 10.32.2.11:6379@16379 master - 0 1733224728000 3 connected 10923-16383
2369086fd52031dafa0bc7877f6778c14059d3c8 10.32.0.210:6379@16379 myself,master - 0 0 1 connected 0-5460
9a2127df228dc7bf5fc25ba119427d28ba823cd1 10.32.1.194:6379@16379 slave 2369086fd52031dafa0bc7877f6778c14059d3c8 0 1733224728830 1 connected
4ab2836dc8976b592abc89bdfc97e1253f8bd41e 10.32.0.139:6379@16379 slave 449daf6eece43b16da10f8b2d06f73ba38020d5d 0 1733224726000 2 connected
9d6a713381584122b89be8666821a78b35840a0d 10.32.2.145:6379@16379 slave 528c541ee1faca8dd78fcf3dae5e0462d06f2c9c 0 1733224725000 3 connected
449daf6eece43b16da10f8b2d06f73ba38020d5d 10.32.1.216:6379@16379 master - 0 1733224727819 2 connected 5461-10922
```

I'm deploying this on an environment with 3 nodes. 
The third node was scheduled the redis-services replicas 2(10.32.2.11) and 3(10.32.2.145), out of replicas 0..5.

I was expecting each node to get 1 master and 1 slave but not have the master and his slave on the same node.
**Is this expectation correct?**

### Are you using any custom parameters or values?

--set fullnameOverride=redis-service,usePassword=false,persistence.enabled=true 

### What is the expected behavior?

Masters and their associated slave must not be running on the same node.

### What do you see instead?

Sometimes, the same node gets a master and a slave. 
When this happens, the cluster still works but failure of that node would lead to the cluster not working anymore.

**Comment by javsalgar** [comment]
Hi,

If I'm not mistaken, in principle it is the `redis` command the one that is deciding which is master and slave. I'm not sure if that is intelligent enough to know that there are two processes on the same node. This could be worth investigating but the script may require more actions on the Kubernetes side such as knowing in which exact node, at runtime, it has been scheduled.

**Comment by liufenix** [comment]
> redis-cluster puts master and slave on the same kubernetes node

Have you solved this problem

**Comment by horacimacias** [comment]
for now I'm just manually checking where masters/slaves have been scheduled by kubernetes. 
Eventually, the same check I'm triggering manually will be done by a pod in kubernetes, and rearrange shards or master/slave pairs (e.g. using `CLUSTER FAILOVER` on replicas) to make sure masters are scheduled where they should be.
