### ISSUE TITLE
[bitnami/discourse] feat: allow specifying credentials from secret

### ISSUE THREAD

**Issue by acelinkio** [bitnami/charts#30721]
### Name and Version

discourse:15.0.5

### What is the problem this feature will solve?

Allow username and password to be specified via Kubernetes secret.  Many Kubernetes operators generate credentials (username and password) and store them inside of a Kubernetes secret.  Those operators (like Bitnami's RabbitMQ topology operator) do not allow you to specify username and expect it to be generated.

For Discourse that means manually aligning the Postgres username inside of the values.yaml.  Instead both username and password should read from keys when an existing secret is leveraged. 

### What is the feature you are proposing to solve the problem?

Introduce a existingSecretUsernameKey and existingSecretPostgresUsernameKey.

```yaml
## @param externalDatabase.existingSecret Name of an existing secret resource containing the database credentials
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the database credentials
## @param externalDatabase.existingSecretPostgresPasswordKey Name of an existing secret key containing the database admin user credentials
``` 

### What alternatives have you considered?

Adding a manual step to align username in values.yaml

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the feature request. I will forward it to the team but as it is not a critical fix we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR and team will take a look
