### ISSUE TITLE
VolumeClaim selector for mariadb-galera 

### ISSUE THREAD

**Issue by rsokolovs** [bitnami/charts#3072]
**Which chart**:
mariadb-galera 

**Is your feature request related to a problem? Please describe.**
It will be very nice to have a VolumeClaim selector for mariadb-galera chart.

**Describe the solution you'd like**
It should be something like rabbitmq chart - https://github.com/bitnami/charts/blob/fbb761d4b64c0fa07721b002edffa05df5e3bf8d/bitnami/rabbitmq/templates/statefulset.yaml#L325-L327
or redis chart - https://github.com/bitnami/charts/blob/fbb761d4b64c0fa07721b002edffa05df5e3bf8d/bitnami/redis/templates/redis-master-statefulset.yaml#L488-L491

**Additional context**
It's very important to have those lables if you have prepared PV's for multiple charts and if you deploy those charts in the same time.

**Comment by marcosbc** [comment]
Hi @rsokolovs, do you want to contribute the change to the Helm chart? It does not look complex, so feel free to send a PR, we would be glad to check it!
