### ISSUE TITLE
Invalid tag version 20.4.0 [bitnami/redis]

### ISSUE THREAD

**Issue by jascsch** [bitnami/charts#30727]
### Name and Version

bitnami/redis 20.4.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Try to fetch the latest tag version for redis helm chart version 20.4.0 --> Error: invalid_reference: invalid tag
please note that version 20.3.0 works perfectly fine

### What is the expected behavior?

version tag 20.4.0 should work

### What do you see instead?

Error: invalid_reference: invalid tag
please note that version 20.3.0 works perfectly fine

### Additional information

![image](https://github.com/user-attachments/assets/cdce5b05-48dc-4268-8026-e39a8b0eec5c)

**Comment by carrodher** [comment]
As reported in https://github.com/helm/helm/issues/13466, this problem stems from how the `helm ... --repo ...` command handles an _index.yaml_ file containing OCI URLs.

### Why is this issue appearing now?
Historically, Bitnami Helm charts were accessed by adding the Bitnami repository to the Helm CLI:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```
or by directly installing/pulling a specific Helm chart using the `--repo` flag:
```
$ helm pull --repo https://charts.bitnami.com/bitnami foo
```

In April 2023, [Bitnami introduced support for the OCI format](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html), recommending OCI-based installation as the primary method going forward. For example:
```
helm pull oci://registry-1.docker.io/bitnamicharts/external-dns --version 8.6.0
```

As detailed in our [recent announcement](https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html) and https://github.com/bitnami/charts/issues/30110, the traditional method is now being deprecated. Consequently, the _index.yaml_ served at `https://charts.bitnami.com/bitnami` now uses OCI URLs, exposing the above mentioned issue in the Helm CLI's handling of these URLs.

**Comment by jascsch** [comment]
thx a lot. I have changed the repo url to registry-1.docker.io/bitnamicharts which worked fine.
