### ISSUE TITLE
[bitnami/contour] release name should also be applied to certgen

### ISSUE THREAD

**Issue by erikschul** [bitnami/charts#30752]
### Name and Version

bitnami/contour 19.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

They must also use different certificates when deploying multiple releases in the same namespace.
Currently, it generates "envoycert" and "contourcert", but should include the release name as a prefix or suffix in the secret name.
This also applies to the places where the certificates are used.

### What do you see instead?

I solved this by manually creating a Certificate using cert-manager and using tlsExistingSecret.
This also solves automatic renewal, which is nice.
But everything else in the chart seems to support release-name, so it might be nice to add this.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by erikschul** [comment]
Related: https://github.com/bitnami/charts/pull/29416

**Comment by erikschul** [comment]
My own conclusion is that using cert-manager is better because of certificate renewal.

**Comment by erikschul** [comment]
Closing in favor of using certmanager.
Renaming certgen certificates could potentially break something.
