### ISSUE TITLE
Bitnami/phpmyadmin allow setting additional environment variables

### ISSUE THREAD

**Issue by violuke** [bitnami/charts#3078]
**Which chart**:
bitnami/phpmyadmin v6.2.2 (and all versions)

**Is your feature request related to a problem? Please describe.**
The upstream [bitnami-docker-phpmyadmin](https://github.com/bitnami/bitnami-docker-phpmyadmin) docker image allows for additional env vars which I need to set to allow larger file imports - such as `PHP_UPLOAD_MAX_FILESIZE`, `PHP_POST_MAX_SIZE` and `PHP_MEMORY_LIMIT`

**Describe the solution you'd like**
I'd like to be able to set these vars in this helm chart.

**Describe alternatives you've considered**
Override the image completely with a different one, but for obvious reasons this is a lot more hassle than it needs to be.

**Comment by joancafom** [comment]
Hey @violuke,

I have created a PR implementing the possibility to provide with extra environment variables, that should fix the problem.

Thanks for your issue!

**Comment by violuke** [comment]
Thanks @joancafom that's really helpful of you 👍 Looking forward to it being merged
