### ISSUE TITLE
Set max_clustering_key_restrictions_per_query in scylladb

### ISSUE THREAD

**Issue by satyajeet96** [bitnami/charts#30803]
### Name and Version

bitnami/scylladb

### What architecture are you using?

None

### What steps will reproduce the bug?

I have installed bitnami scylladb helmchart in kubernetes cluster. I want to set `max_clustering_key_restrictions_per_query: 10000`.
I have set in values.yaml file at `existingConfiguration: scylla-custom-config`. I have created a configmap scylla.yaml with this value.
When I exec into a pod at the path /bitnami/scylladb/etc. I can see file scylla.yaml with value
```
max_clustering_key_restrictions_per_query: 10000
write_request_timeout_in_ms: 60000
```
But when I run my normal query in cli I get error of limit 100.
So is the value set or not. If not then from where can I set.

**Comment by dgomezleon** [comment]
Hi @satyajeet96 

Thanks for reporting it. I was able to reproduce the issue and created a task to solve it.
