### ISSUE TITLE
Allow Templating of Host for livenessProbe and readinessProbe in nginx chart

### ISSUE THREAD

**Issue by hofq** [bitnami/charts#30818]
### Name and Version

bitnami/nginx 18.2.5

### What is the problem this feature will solve?

my nginx can only return the right status code on a specific host, as this is the current setup

### What is the feature you are proposing to solve the problem?

I can set the host and keep livenessProbe and readinessProbe enabled

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
