### ISSUE TITLE
[bitnami/thanos] thanos query support distributed mode

### ISSUE THREAD

**Issue by bluesky6529** [bitnami/charts#30819]
### Name and Version

bitnami/thanos 

## Description
Add support for Thanos Query distributed mode execution in the Bitnami Helm chart. This feature was introduced in Thanos to improve query performance.

## Reference
- [Thanos Distributed Query Execution Design](https://thanos.io/tip/proposals-done/202301-distributed-query-execution.md/)

### What is the feature you are proposing to solve the problem?

Similar to how `receiveDistributor` is implemented in the chart, I think:

1. Create a new component `queryDistributor` that will:
   - Act as the entry point for all queries
   - Distribute queries across query instances
   - Only operate in distributed mode (as per Thanos design)

2. Required changes:
   - Create `queryDistributor`
   - If created, Thanos queryfrontend need to change to queryDistributor endpoint

### What alternatives have you considered?

N/A

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
