### ISSUE TITLE
Kubernetes Pod application connection issues to external database

### ISSUE THREAD

**Issue by amin224** [bitnami/charts#3083]
I have deployment an application on a Kubernetes Pod in a cluster, but I need to connect the application to an external database Postgresql. I am receiving connection exceptions from the application due to connection issues. I am working on local host. I am trying to connect my spring boot API application inside a Pod to an external database (a separate machine within my local network). According to my research, I assume I should make a service file of type Cluster-IP or Node-Port for my application to connect to my external database. Unfortunately connection exception is still on my application due to incapability of connecting to my external database. I have also changed my application jdbc connection string to postgresql as mentioned in other forums. In addition, I also did a kubeadm reset and made sure the pod-network-cidr={IP would be compatible within my subnet} but it did not resolve my problem. After doing some research I assumed a helm chart would resolve my issue but I am getting a timeout error when trying to install my chart.

```
$ helm install --name dictionary ./mychart --set service.type=NodePort
Error: Get "https://ip:443/version?timeout=32s": dial tcp ip:443: i/o timeout
```

```
Cluster information:
Kubernetes version: v1.18.5
VM-Host: Ubuntu 18.04
two virtual machines for worker node and master node
```

service.yml:

```
apiVersion: v1
kind: Service
metadata:
   name: identity-service
   labels:
     app: net
spec:
  selector:
      app: identity
  type: NodePort 
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
```

endpoint.yml:

```
apiVersion: v1
kind: Endpoints
metadata:
   name: identity-service
   labels:
     app: net
subsets:
 - addresses:
     - ip: {database ip}
   ports:
     - port: 5432
```

deployment.yml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
   name: application
   labels:
     app: net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
       hostNetwork: true
       containers:
       - name: applicationapi
         image: {image name}
         ports:
         - containerPort: 80
```

Logs from application Pod before using a service:

```
Unhandled Exception: Npgsql.NpgsqlException: Exception while connecting ---> System.TimeoutException: Timeout during connection attempt
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   --- End of inner exception stack trace ---
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
```

Logs after applying service and endpoint:

```
Unhandled Exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
```

Below are the Pod IPs
When I ping the pods from my worker node VM these are the results:

> workernode@workernode:~$ ping 192.168.190.198
> PING 192.168.190.198 (192.168.190.198) 56(84) bytes of data.
> 64 bytes from 192.168.190.198: icmp_seq=1 ttl=64 time=0.074 ms
> 64 bytes from 192.168.190.198: icmp_seq=2 ttl=64 time=0.077 ms
> 64 bytes from 192.168.190.198: icmp_seq=3 ttl=64 time=0.082 ms
> ^C
> --- 192.168.190.198 ping statistics ---
> 3 packets transmitted, 3 received, 0% packet loss, time 2030ms
> rtt min/avg/max/mdev = 0.074/0.077/0.082/0.010 ms
> workernode@workernode:~$ ping 192.168.190.199
> PING 192.168.190.199 (192.168.190.199) 56(84) bytes of data.
> 64 bytes from 192.168.190.199: icmp_seq=1 ttl=64 time=0.083 ms
> 64 bytes from 192.168.190.199: icmp_seq=2 ttl=64 time=0.210 ms
> 64 bytes from 192.168.190.199: icmp_seq=3 ttl=64 time=0.147 ms
> ^C
> --- 192.168.190.199 ping statistics ---
> 3 packets transmitted, 3 received, 0% packet loss, time 2026ms
> rtt min/avg/max/mdev = 0.083/0.146/0.210/0.053 ms

But when I ping the Pods from my master node there is no response:

> root@ubuntu:~/Kubernetes yml files# ping 192.168.190.198
> PING 192.168.190.198 (192.168.190.198) 56(84) bytes of data.
> ^C
> --- 192.168.190.198 ping statistics ---
> 3 packets transmitted, 0 received, 100% packet loss, time 2028ms
> root@ubuntu:~/Kubernetes yml files# ping 192.168.190.199
> PING 192.168.190.199 (192.168.190.199) 56(84) bytes of data.
> ^C
> --- 192.168.190.199 ping statistics ---
> 3 packets transmitted, 0 received, 100% packet loss, time 2046ms

I noticed my kubernetes cluster IP is not in the subnet, so is this why there is no connection to outside cluster?
But the kubernetes endpoint is the same IP as the virtual machine for master node.

    root@ubuntu:~/Kubernetes yml files# kubectl get services
    NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
    kubernetes   ClusterIP   10.190.0.1       <none>        443/TCP    18h

When i ping my database on both virtual machines there is connection.

**Comment by andresbono** [comment]
Hi @amin224, you should check the network visibility and reachability of the external database from the pod inside the cluster. It will depend on the particularities of the network configuration of your cluster. Maybe you can execute a pod for debugging purposes and start troubleshooting from there. For example:

```
kubectl run --image=bitnami/minideb debug --command sleep infinity
kubectl exec -it debug -- install_packages curl net-tools dnsutils iputils-ping
kubectl exec -it debug -- bash
```

If you can't get it to work, you can use `hostNetwork` spec in the pod, but it is not very recommended to do that in production, due to security reasons. https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces

**Comment by amin224** [comment]
Hello @andresbono , Thank you for your response I appreciate your support as I have been stuck with this issue for three consecutive days. I am researching for a solution to this problem and I have came across everything at this point. I did use the sleep infinity command in my deployment file to keep my Pods running unfortunately that will not help as the API request to database is not working. I have two questions I hope you can answer them to make sure I am understanding the scenario.

**Question 1**
`In order to connect to an external database (outside the cluster) to my Pod in the cluster I can use the service and endpoint files for my deployment, Do i have to change the **jdbc connection string IP address to postgresql** as I have stated in the service file `metadata.name: postgresql` ?`

**Question 2**
`When I created the service and endpoint files I have noticed that the endpoint is exactly the IP and port of my database but the clusterIP is 10.111. which is not even in the subnet of my IP addresses. Do i have to change the service clusterIP?`

**Question 3**
`If i wanted to post an API request of my Pod do I have to enter the service IP and port? If that is the case then my cluster-IP IP address should be changed. How can I do that as I tried to change it from the calico-kubeconfig file but it isnt changing.`

I will read about hostNetwork as you mentioned and try my luck . Cheers

**Comment by amin224** [comment]
Dear @andresbono , Good news! I have used the hostNetwork spec in the pod and as I can see the Pod is running with no crashes, in addtion, while checking the logs of the Pod everything seems good. Meanwhile sending an API request using postman there seems to be a Error: socket hang up. I used the clusters IP and port of my service is this the correct way to use my Pod?

**kubectl describe service identity-service**
```
Name:                     identity-service
Namespace:                default
Labels:                   app=net
Annotations:              Selector:  app=identity
Type:                     NodePort
IP:                       10.110.11.45
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31000/TCP
Endpoints:                {database ip}:5432
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**Comment by amin224** [comment]
Dear @andresbono , Thank you so much, including hostNetwork in my deployment file helped me connect to the database when sending an API request.  Hopefully in the future I will include my database in the cluster and not face network issues.

**Comment by andresbono** [comment]
> **Question 1**
> In order to connect to an external database (outside the cluster) to my Pod in the cluster I can use the service and endpoint files for my deployment, Do i have to change the **jdbc connection string IP address to postgresql** as I have stated in the service file metadata.name: postgresql ?

In theory, both IP address and service name can be used. If you have defined a service/endpoint, it's better if you use them, so that you can update the information about your external database in the service/endpoint files, for example, changing the IP address.

> **Question 2**
> When I created the service and endpoint files I have noticed that the endpoint is exactly the IP and port of my database but the clusterIP is 10.111. which is not even in the subnet of my IP addresses. Do i have to change the service clusterIP?

It is expected that the network space address are different because they are different networks, internal to the cluster and external. By default, the service is type clusterIP.

> **Question 3**
> If i wanted to post an API request of my Pod do I have to enter the service IP and port? If that is the case then my cluster-IP IP address should be changed. How can I do that as I tried to change it from the calico-kubeconfig file but it isnt changing.

For the pod inside the cluster, you should always use the service name and port and let Kubernetes (and calico) manage that for you.

---


> Dear @andresbono , Thank you so much, including hostNetwork in my deployment file helped me connect to the database when sending an API request. Hopefully in the future I will include my database in the cluster and not face network issues.

That's great news! Let us know if you need more help or we can close the issue.
