### ISSUE TITLE
🔊 Notice about LTS branches and pull rates in Docker Hub

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#30853]
Starting December 10th, 2024, only the latest stable branch of applications deployed by Bitnami Helm charts will receive updates in the free Bitnami catalog. Previous versions already released will not be deleted. They are still available to pull from DockerHub.
For example, for PostgreSQL, only branch 17 (the latest stable version) will be maintained in the free catalog. Other upstream-supported branches, such as 13, 14, 15, and 16, will be exclusively available through Bitnami Premium.

Also on that date, all free Bitnami Helm charts and containers will be subject to standard pull-rate limits and pull caps in Docker Hub.

To continue accessing up-to-date releases of all the upstream-supported branches and to pull without any limitations, you can upgrade to Bitnami Premium. Please check the Bitnami Premium page in our partner Arrow's marketplace. See [https://www.arrow.com/globalecs/na/vendors/bitnami](https://www.arrow.com/globalecs/na/vendors/bitnami?utm_source=GitHub&utm_medium=charts) for more information.

**Comment by schnatterer** [comment]
@carrodher @bradmbock I noticed most Bitnami Charts are no longer listed on ArtifactHub. I cannot find anything about this in the Bitnami premium announcements.

Is this by design? Is it related to this issue?

**Comment by carrodher** [comment]
@schnatterer, it is not related to this topic.
It already happened in the past, and there was an open issue at https://github.com/artifacthub/hub/issues/3973 which was updated today because of this incident as well.

**Comment by schnatterer** [comment]
@carrodher Thanks for clarifying this. I'm very much relieved.

**Comment by tegioz** [comment]
Related to the AH issue mentioned above, please see https://github.com/artifacthub/hub/issues/3973#issuecomment-2587089079 @schnatterer @carrodher.
