### ISSUE TITLE
[azure-marketplace-charts/bitnami/elasticsearch] howto: enable authentication to elastic and kibana

### ISSUE THREAD

**Issue by ericfaure007** [bitnami/charts#3092]
**Which chart**:
[azure-marketplace-charts/bitnami/elasticsearch]

**Describe the bug**
There is no clear documentation on how to enable authentication for elastic and kibana
I tried to add some variables in values.yaml file
extraEnvVars:
- name: ELASTICSEARCH_USERNAME
    value: elastic
  - name: ELASTICSEARCH_PASSWORD
    value: elasticpass
  - name: xpack.security.enabled
    value: true

helm install elastic-test -f values.yaml bitnami-azure/elasticsearch
but it's not working.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.3+2.el8", GitCommit:"4edcae3c96edf7fa6a3bcf93de6d85763aed1284", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
 oc version
Client Version: 4.4.6
Server Version: 4.3.27
Kubernetes Version: v1.16.2+d6d3cff

```

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, our container does not include xpack because of its license.
