### ISSUE TITLE
[odoo] longpolling support

### ISSUE THREAD

**Issue by ayushin** [bitnami/charts#3097]
Hi,

Just giving a thought about moving our odoo setup to kubertnettes however I can't find wether this chart supports longpolling?

I'd expect to have a separate service and perhaps even a  dedicated ingress with long timeouts?

**Comment by andresbono** [comment]
Hi @ayushin, we haven't explored that option. To better understand what you are proposing, can you share an example of chart that is doing that already? How the traffic would be split for the different services and ingress?

**Comment by ayushin** [comment]
@andresbono well, i haven't explored that option either, but we do use livechat which takes a connection to port 8072 (or whatever the longpolling port is configured to be) and a very long time out (600s) for proxy and workers. I don't see it anywhere in the chart templates, so I assumed the im_chat would not be working?

It took us a very long time to get it working by tweaking nginx and odoo settings in a docker setup, so I guess we would have to experiment quite a bit with nginx-ingress annotation, creating a separate ingress path /longpolling and a dedicated service and end-point for 8072

so could you confirm you don't have the im_chat working with your helm chart as it is? (i am not new to odoo, but perhaps i am missing something?)

**Comment by andresbono** [comment]
Hi @ayushin, thanks for the details. We deploy Odoo with basic configuration but we haven't explored or checked the `im_chat` feature, so we can't tell you if it will work or not. Please, if you finally get it working, it would be great if you can open a PR so we continue improving the chart. We will be more than happy to review it!
