### ISSUE TITLE
[MariaDb] Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock'

### ISSUE THREAD

**Issue by trung-hiro** [bitnami/charts#3098]
**Which chart**:
MariaDB - version 10.3.23

**Describe the bug**
After i deploy my project to vitualmachines (Azure server).
So my project connect to mariadb about 20minute. And after then my server is restarted. so i login to my server and can restart mariadb. My log i recived :

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (111)

Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.078Z - info: Performing service start operation for apache
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.078Z - verbose: Running export start for apache
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.291Z - debug: Injecting the folling environment: {"PATH":"/opt/bitnami/apache/bin:/opt/bitnami/apache2/bin:/opt/bitnami/common/bin:/opt/bitnami/git/bin:/opt/bitnami/goni
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: apache 02:17:42.32 INFO  ==> apache is already running
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.330Z - info: Performing service start operation for postgresql
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.330Z - verbose: Running export start for postgresql
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.524Z - debug: Injecting the folling environment: {"PATH":"/opt/bitnami/apache/bin:/opt/bitnami/apache2/bin:/opt/bitnami/common/bin:/opt/bitnami/git/bin:/opt/bitnami/goni
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: postgresql 02:17:42.58 INFO  ==> postgresql is already running
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.590Z - info: Performing service start operation for mariadb
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.590Z - verbose: Running export start for mariadb
Jul 13 02:17:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:17:42.759Z - debug: Injecting the folling environment: {"PATH":"/opt/bitnami/apache/bin:/opt/bitnami/apache2/bin:/opt/bitnami/common/bin:/opt/bitnami/git/bin:/opt/bitnami/goni
Jul 13 02:17:54 SEMPlan-JP-Live dhclient[469]: XMT: Solicit on eth0, interval 113590ms.
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: mariadb 02:18:42.86 ERROR ==> mariadb did not start
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: 2020-07-13T02:18:42.879Z - error: Unable to perform start operation Export start for mariadb failed with exit code 1
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: ## 2020-07-13 02:18:42+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/010_detect_new_account...
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: ## 2020-07-13 02:18:42+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/020_bitnami_agent_extra...
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: ## 2020-07-13 02:18:42+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/030_bitnami_agent...
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: ## 2020-07-13 02:18:42+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/040_update_welcome_file...
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: ## 2020-07-13 02:18:42+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/050_bitnami_credentials_file...
Jul 13 02:18:42 SEMPlan-JP-Live bitnami[42875]: ## 2020-07-13 02:18:42+00:00 ## INFO ## Running /opt/bitnami/var/init/post-start/060_clean_metadata...
Jul 13 02:18:42 SEMPlan-JP-Live systemd[1]: bitnami.service: Control process exited, code=exited, status=1/FAILURE

**Comment by rafariossaa** [comment]
Hi,
  Could you provide more information about your deployment ? Chart version, settings in values.xml used, chart logs, etc.
