### ISSUE TITLE
[bitnami/minio] loadBalancerSourceRanges list rendering is broken

### ISSUE THREAD

**Issue by YaKalmar0** [bitnami/charts#31018]
### Name and Version

bitnami/minio 14.9.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

This is the same as #14834 but in the minio chart. The entire description of the mentioned issue is relevant to this one.

### What do you see instead?
```
Invalid value: "1.2.3.4/24 5.6.7.8/24 9.10.11.12/24": must be a valid CIDR value, (e.g. 10.9.8.0/24 or 2001:db8::/64)
```

**Comment by carrodher** [comment]
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!
