### ISSUE TITLE
[Request] etcd dashboard for multiple etcd cluster metriccs

### ISSUE THREAD

**Issue by SrinivReddy** [bitnami/charts#3103]
Hi Team,

I have configures a etcd cluster using bitnami helm charts and enabled metrics to promethues.

I have a two etcd clusters in my eks cluster, how can we get metrics per cluster in grafana dashboard ?

**Comment by juan131** [comment]
Hi @SrinivReddy 

You can play with the labels to distinguish between the metrics coming from one etcd cluster or another. Or obtain the ones coming from both clusters.

For instance, if I install two etcd cluster called "foo" and "bar":

```
$ helm install foo bitnami/etcd
$ helm install bar bitnami/etcd
```

Then, you'll find that there are labels both solutions share (e.g. `app.kubernetes.io/name=etcd`) but there are other that are different (e.g. `app.kubernetes.io/instance=foo` vs `app.kubernetes.io/instance=bar`)

```
$ kubectl get pods --show-labels
NAME                READY   STATUS    RESTARTS   AGE   LABELS
bar-etcd-0          0/1     Running   0          35s   app.kubernetes.io/instance=bar,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=etcd,controller-revision-hash=bar-etcd-6db775c7f,helm.sh/chart=etcd-4.8.10,statefulset.kubernetes.io/pod-name=bar-etcd-0
foo-etcd-0          0/1     Running   0          40s   app.kubernetes.io/instance=foo,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=etcd,controller-revision-hash=foo-etcd-554f8fc7b6,helm.sh/chart=etcd-4.8.10,statefulset.kubernetes.io/pod-name=foo-etcd-0
```

Find more information at https://prometheus.io/docs/prometheus/latest/querying/basics/

**Comment by SrinivReddy** [comment]
@juan131 , Got it Thanks!
