### ISSUE TITLE
[Bitnami] Webiste https://charts.bitnami.com/bitnami is not accessible

### ISSUE THREAD

**Issue by mallick-asad** [bitnami/charts#31053]
### Describe your issue as much as you can

I am trying to access https://charts.bitnami.com/bitnami directly, but it is not accessible. I am attempting to create an EKS cluster that downloads charts from Bitnami, which throws an error.

Error: could not download chart: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp: lookup charts.bitnami.com: no such host

**Comment by jotamartos** [comment]
DNS records were updated and information is being propagated now. We will keep monitoring this to confirm everything works as expected, this may take some time but you shouldn't run into any issue from that time on. Sorry for the inconvenience.

**Comment by benediktblank** [comment]
Our pipelines are working again it seems

**Comment by mallick-asad** [comment]
> DNS records were updated and information is being propagated now. We will keep monitoring this to confirm everything works as expected, this may take some time but you shouldn't run into any issue from that time on. Sorry for the inconvenience.

Thank you @jotamartos
