### ISSUE TITLE
Permission denied in k8s keycloak.conf

### ISSUE THREAD

**Issue by Fargus3222** [bitnami/charts#31073]
### Name and Version

bitnami/keycloak:latest

### What architecture are you using?

Kubernetes in autoscaling cluster on Selectel

### What steps will reproduce the bug?

I want to run keycloak in Kubernetes and receive `/opt/bitnami/scripts/libkeycloak.sh: line 117: /opt/bitnami/keycloak/conf/keycloak.conf: Permission denied` but in docker on my local server everything in okay.

### What do you see instead?

```
keycloak 13:53:17.12 INFO  ==>
keycloak 13:53:17.12 INFO  ==> Welcome to the Bitnami keycloak container
keycloak 13:53:17.12 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
keycloak 13:53:17.12 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
keycloak 13:53:17.13 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
keycloak 13:53:17.13 INFO  ==>
keycloak 13:53:17.13 INFO  ==> ** Starting keycloak setup **
keycloak 13:53:17.15 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 13:53:17.16 INFO  ==> Trying to connect to PostgreSQL server postgres.postgres.svc...
keycloak 13:53:17.17 INFO  ==> Found PostgreSQL server listening at postgres.postgres.svc:5432
keycloak 13:53:17.17 INFO  ==> Configuring database settings
/opt/bitnami/scripts/libkeycloak.sh: line 117: /opt/bitnami/keycloak/conf/keycloak.conf: Permission denied
```

### Additional information

I deploy in Deployment without statefulset

**Comment by carrodher** [comment]
Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.

For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
* [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
* [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
* [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
* [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)

These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by Fargus3222** [comment]
My Deployment run with out forwarding /opt/bitnami/keycloak/conf/keycloak.conf both in cybernetes and docker

> Bitnami containers are designed to operate as non-root by default. Consequently, any files or directories used by the application should be owned by the _root_ group, as the random user (_1001_ by default) is a member of this _root_ group. To ensure proper permissions, you'll need to adjust the ownership of your local directory accordingly.
> 
> For more comprehensive information about non-root containers and their significance for security, you can explore the following resources:
> 
>     * [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
> 
>     * [Use Non-Root Containers](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/)
> 
>     * [Work With Non-Root Containers for Bitnami Applications](https://docs.bitnami.com/tutorials/work-with-non-root-containers)
> 
>     * [Running non-root containers on Openshift](https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift)
> 
> 
> These references provide valuable insights into the best practices and considerations when working with non-root containers in Bitnami applications.

**Comment by Fargus3222** [comment]
My Deployment run with out forwarding /opt/bitnami/keycloak/conf/keycloak.conf both in cybernetes and docker
