### ISSUE TITLE
[bitnami/drupal] pod-startup error with minikube

### ISSUE THREAD

**Issue by sumeshsquare** [bitnami/charts#3108]
### Chart: drupal

I am using GCP VM for this setup with minikube (driver as docker), using helm chart to install drupal without changing any default config with command: `helm install drupal .`

Drupal pod error below:
```
INFO  ==> Starting drupal... 
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

Version of Helm and Kubernetes:  Helm Version: v3.2.4 & minikube version: v1.12.0 

Help: @andresbono

**Comment by dani8art** [comment]
Hi @sumeshsquare could you share with us the chart version?

I'm using `version: 7.0.3` and Im not able to reproduce it.

Thanks!

**Comment by sumeshsquare** [comment]
> Hi @sumeshsquare could you share with us the chart version?
> 
> I'm using `version: 7.0.3` and Im not able to reproduce it.
> 
> Thanks!

I am using the latest one:

apiVersion: v1
name: drupal
version: 8.0.1
appVersion: 9.0.2

**Comment by andresbono** [comment]
Hi @sumeshsquare, sorry for the inconvenience. Could you stick to the previous major until we fix the issue? `7.0.3`. As soon as we release a new version of the container, the issue should be gone.

**Comment by sumeshsquare** [comment]
Hi @dani8art, Thank you for the info.
I am a newbie, could you please let me know how to get the older version 7.0.3, please

**Comment by andresbono** [comment]
Hi @sumeshsquare, please follow the steps specified here: https://github.com/bitnami/charts#user-content-tldr

Note that in the chart repository, the stable version is `7.0.3`:

```
$ helm search repo bitnami/drupal
NAME          	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/drupal	7.0.3        	9.0.2      	One of the most versatile open source content m..
```

**Comment by sumeshsquare** [comment]
Hi @andresbono, Thank you so much, it worked :)
one final question, how can I get the source code of version 7.0.3, in git repo, I could able to see latest one only.

**Comment by andresbono** [comment]
You can use this link: https://github.com/bitnami/charts/tree/e6db6bfa55c09418e53aa33a6cf7f56d422e64ea/bitnami/drupal. It does a checkout to e6db6bfa55c09418e53aa33a6cf7f56d422e64ea, the commit of the `7.0.3` release.

**Comment by sumeshsquare** [comment]
> You can use this link: https://github.com/bitnami/charts/tree/e6db6bfa55c09418e53aa33a6cf7f56d422e64ea/bitnami/drupal. It does a checkout to [e6db6bf](https://github.com/bitnami/charts/commit/e6db6bfa55c09418e53aa33a6cf7f56d422e64ea), the commit of the `7.0.3` release.

Awesome, Thanks @andresbono and @dani8art

**Comment by andresbono** [comment]
Hi @sumeshsquare, the latest version of Drupal chart is now released:

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈

$ helm search repo bitnami/drupal
NAME          	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/drupal	8.0.3        	9.0.2      	One of the most versatile open source content m...
```

**Comment by sumeshsquare** [comment]
Hi @andresbono ,
Great release, I like the common chats separation!

With latest update, the Permission issue was fixed, but the pod startup is in hang state, logs below:

```

drupal 05:45:33.26 
drupal 05:45:33.27 Welcome to the Bitnami drupal container
drupal 05:45:33.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
drupal 05:45:33.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues
drupal 05:45:33.28 
drupal 05:45:33.28 INFO  ==> ** Starting Drupal setup **
drupal 05:45:33.32 INFO  ==> Configuring PHP options
drupal 05:45:33.33 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 05:45:33.37 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
drupal 05:45:33.39 INFO  ==> Trying to connect to the database server
drupal 05:45:33.41 INFO  ==> Configuring file permissions for Drupal
drupal 05:45:33.41 INFO  ==> Installing Drupal site
```

**Comment by andresbono** [comment]
Hi @sumeshsquare, can you deploy the chart with debug enabled?

```bash
helm install drupal-test bitnami/drupal --set image.debug=true
```

This is what we get:

```
...
drupal 08:48:55.16 INFO  ==> Configuring file permissions for Drupal
drupal 08:48:55.16 INFO  ==> Installing Drupal site

 You are about to:
 * DROP all tables in your 'bitnami_drupal' database.

 // Do you want to continue?: yes.

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_settings_form
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [notice] Performed install task: install_profile_modules
 [notice] Performed install task: install_profile_themes
 [notice] Performed install task: install_install_profile
 [notice] Performed install task: install_configure_form
 [notice] Cron run completed.
 [notice] Performed install task: install_finished
 [success] Installation complete.
drupal 08:49:21.74 INFO  ==> Flushing Drupal cache
 [success] Cache rebuild complete.
drupal 08:49:24.92 INFO  ==> Persisting Drupal installation
drupal 08:49:25.01 INFO  ==> ** Drupal setup finished! **

drupal 08:49:25.02 INFO  ==> ** Starting Apache **
...
```

How many resources does minikube have assigned?

**Comment by sumeshsquare** [comment]
Hi @andresbono, thanks for that debug tip !

The error was with the MySQL instance which I am trying to connect with is 5.6, 

``` debug log
The database server version 5.6  
  .49</em> is less than the minimum required version   
  5.7.8</em>.
```

Thanks Again...

**Comment by andresbono** [comment]
We are glad to have helped! 👍
