### ISSUE TITLE
[bitnami/redis] Can't open the append-only file: Permission denied

### ISSUE THREAD

**Issue by bartversluijs** [bitnami/charts#3110]
**Which chart**:
[bitnami/redis - v10.7.11](https://github.com/bitnami/charts/tree/master/bitnami/redis)

**Describe the bug**
When I start the bitnami/redis chart on a microk8s cluster, the master as well as the slave keeps crashing with the following logs:
```
 10:08:55.69 INFO  ==> ** Starting Redis **
1:C 14 Jul 2020 10:08:55.711 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 14 Jul 2020 10:08:55.711 # Redis version=6.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 14 Jul 2020 10:08:55.711 # Configuration loaded
1:M 14 Jul 2020 10:08:55.713 # Can't open the append-only file: Permission denied
```

I've tried it on a managed Kubernetes cluster, where it works out of the box.

**To Reproduce**
1. Create a microk8s cluster via snap
2. Install the bitnami/redis chart
3. See logs

**Expected behavior**
It should start all the Redis pods without any issues.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I've tried the following using the `values.yaml`:
```yaml
volumePermissions:
  enabled: true
```

and

```yaml
securityContext:
  enabled: true
  fsGroup: 2000
  runAsUser: 0
```

But both didn't work. Used them separate from each other and combined.

(btw, I have `storage` enabled on microk8s. Other apps with pvc's work)

**Comment by joancafom** [comment]
Hi @bartversluijs ,

Thanks for your issue! Could you please try with the following values altogether and tell me if they worked for you?

```yaml
volumePermissions:
  enabled: true

securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
```

Thanks!

**Comment by bartversluijs** [comment]
Hi @joancafom,

Thanks! I thought I've tried that before, settings `fsGroup` and `runAsUser` to 1001. But it seems like it did the trick, thanks!
