### ISSUE TITLE
[bitnami/postgres-ha] Could not resize shared memory segment; To little space on `/dev/shm`

### ISSUE THREAD

**Issue by ltsbkuster** [bitnami/charts#3111]
**Which chart**:
postgresql-ha-3.2.10

**Is your feature request related to a problem? Please describe.**
I have a database with two connected tables. 
 - table sensor: 1 million rows
 - table sensor_stats: 10 million rows (10 rows per sensor)

Executing a query like this
```
select id, count(*) from sensor
inner join sensor_stats on sensor.uid = sensor_stats.sensor_uid
group by id
limit 1000
```

causes following Error
```
ERROR:  could not resize shared memory segment "/PostgreSQL.497503474" to 16777216 bytes: No space left on device
CONTEXT:  parallel worker
SQL state: 53100
```

After a bit of googling it statet out that postgres uses `/dev/shm` to exchange data between workers.
Especially [this issue](https://github.com/kubernetes/kubernetes/issues/28272) is about this topic, even mentioning the problem beeing very specific to postgresql and kubernetes.
In a default kubernetes setup (e.g. minikube or also Azure AKS) `/dev/shm` is somehow mounted as 64Mb big folder:

```
shm              64M   12K   64M   1% /dev/shm`
```
During the query I can see how this 64M get filled up and then when it reaches 64M, the error occurs. I already tried to increment `shared_buffers` in `postgresql.extendedConf` but this has no effect, since the size of `/dev/shm` is anyway not controllable from within the container.

**Describe the solution you'd like**
Include a config-value where the size of /dev/shm can be configured. If specified, the /dev/shm should be overmounted like this in the postgresql container:
```
# postgresql/statefulset.yaml
...
volumeMounts:
     - name: dshm
      mountPath: /dev/shm
...
volumes:
    - name: dshm
       emptyDir:
            medium: Memory
            sizeLimit: 256Mi
...
```
I tested this solution and my query now returns a result.

**Describe alternatives you've considered**
Additional Volumes to the Postgresql container could also fix the problem, however the user is in charge to apply this volume by hand.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback! This is very valuable for us :) In other charts we have the values for extraVolume and extraVolumeMounts which allow you to add different types of volumes. I think that it would also make sense to allow an extraVolumeClaimTemplates section that will also create volumes for the statefulset. From what I read, you are proposing to add a value called `shmMount` (or something similar) where you can specify the properties of a volume that would override `shm`. 

Right now we are in the process of standardizing the charts as much as we can, so I'm not sure about adding the `shm` section or simply adding a section in the documentation explaining how to use the `extraVolumeMounts` and `extraVolumeClaimTemplates` sections (that we will add to the chart) covering the use case you mention here. I think that the chart would be more maintainable like this. For the time being I will ensure that the chart has the three extra volume sections and this section documented. But if more users from the community find more valuable to have an specific shm section, we could consider adding the value.

**Comment by ltsbkuster** [comment]
I think it would be totally fine to add extraVolumes to the Postgresql Statefulset to stay as close as possible to the other charts.

**Comment by javsalgar** [comment]
Thank you very much! Stay tuned as I'll notify here when the PR is available :)

**Comment by niksubramanian** [comment]
@javsalgar, just checking in to see if there's an update on this issue? We're currently facing the same problem and, if possible, would like to avoid forking from the main repository.

Thanks for the chart by the way - it's been super useful!

**Comment by niksubramanian** [comment]
Just in case anyone else is confronted with this issue, our temporary workaround:

```
kubectl edit statefulsets -n $MY_NAMESPACE postgresql-ha-postgresql
# Please note: the name of the statefulset can change, depending on how you installed the release
```

And in the statefulset:
```
# ...
  volumeMounts:
  # ...
  - mountPath: /dev/shm
    name: dshm
# ...
volumes:
# ...
- emptyDir:
  medium: Memory
  sizeLimit: 512Mi
  name: dshm
```

Be aware that if you `helm upgrade` the release, this risks overwriting this change, and you'll need to reapply it.

**Comment by javsalgar** [comment]
Hi,

I am afraid it is still in our backlog. However, I contacted the team for re-prioritization. Thank you very much for the workaround!

**Comment by dominik-bln** [comment]
As a sidenote, the `bitnami/postgresql` chart contains a volume like this already:

https://github.com/bitnami/charts/blob/840d880e5cd52599b73831348172fd187be1f263/bitnami/postgresql/templates/statefulset.yaml#L546

**Comment by niksubramanian** [comment]
Would it be worthwhile to post a pull request for this issue? I can easily add either the `shmVolume` approach or the `extraVolumeMounts` approach, if there's a good chance that the pull request will be accepted ;)

Let me know, happy to contribute.

**Comment by javsalgar** [comment]
Hi,

I created a PR that adds a bunch of standard values in this chart. This includes extraVolumes and extraVolumeMounts. Please take a look https://github.com/bitnami/charts/pull/3797

**Comment by dare-mr** [comment]
Did this get merged into the main chart for postgresql-ha?

I still don't see this shmVolume option in the statefulset. It seems that this was added only to the standalone PG.

https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml

**Comment by javsalgar** [comment]
Hi,

I don't recall the context of only adding it to the standalone, would you like to create a PR to add it?

**Comment by ltsbkuster** [comment]
Hi together,

You can define a dshm extra volume in values.yaml for postgresql-ha which if i remeber correctly was the fix for this issue.
https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha#use-a-volume-for-devshm

**Comment by dare-mr** [comment]
Thanks guys. I got confused because the fix was made directly into the chart for the standalone PG but not to the PG-HA. 

I will try using the extra volume in values.yaml.

This can be closed.
