### ISSUE TITLE
[bitnami/etcd] snapshotter error when one replica

### ISSUE THREAD

**Issue by fefi42** [bitnami/charts#3112]
**Which chart**:
etcd 4.8.2

**Describe the bug**
When only one replica exists the snapshotter job fails. With the following error:

```
==> Bash debug is on
+ AUTH_OPTIONS=
+ ETCDCTL_ENDPOINTS=http://etcd-0.etcd-headless.my-chart.svc.cluster.local:2379,
+ export ETCDCTL_ENDPOINTS=http://etcd-0.etcd-headless.my-chart.svc.cluster.local:2379
+ ETCDCTL_ENDPOINTS=http://etcd-0.etcd-headless.my-chart.svc.cluster.local:2379
+ mkdir -p /snapshots
+ read -d, ETCDCTL_ENDPOINTS
Error - all etcd endpoints are unhealthy!
+ echo 'Error - all etcd endpoints are unhealthy!'
+ exit 1
``` 

The script tries to read the endpoints with a comma as a delimiter. However when only one replica is present it will never read anything since there is no comma present. 

**To Reproduce**
1. Deploy the chart with one replica and snapshotting activated. 
2. Wait until the snapshotter starts.

You can also test it using a script like this:
```
#!/bin/bash
export ETCDCTL_ENDPOINTS=http://etcd-0.etcd-headless.my-chart.svc.cluster.local:2379
while read -d, ETCDCTL_ENDPOINTS; do
    echo "Using endpoint ${ETCDCTL_ENDPOINTS}" 1>&3 2>&4
    echo we should be seeing this
done <<< "$ETCDCTL_ENDPOINTS"
echo we should not be seeing this
```
Adding a trailing comma to `ETCDCTL_ENDPOINTS` will make this run.

**Expected behavior**
Expected would be that the snapshotting also works with only one replica if the replica is healthy. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.10-gke.8", GitCommit:"fd29f95f189cb16dd8fe0bd5dc8b485dfd049d2c", GitTreeState:"clean", BuildDate:"2020-06-23T23:44:30Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @fefi42 

Thanks for reporting the issue! This piece of code should make it:

```bash
export ETCDCTL_ENDPOINTS=http://etcd-0.etcd-headless.my-chart.svc.cluster.local:2379
read -r -a endpoints <<< "$(tr ',;' ' ' <<< "$ETCDCTL_ENDPOINTS")"
for endp in "${endpoints[@]}"; do
    echo "Using endpoint $endp"
    ...
done
```

I just created a PR to fix this.
