### ISSUE TITLE
[bitnami/redis-cluster] cp: cannot stat '/opt/bitnami/redis/etc/redis-default.conf': No such file or directory

### ISSUE THREAD

**Issue by duvallj** [bitnami/charts#3113]
**Which chart**:
bitnami/redis-cluster version 3.1.5

**Describe the bug**
When attempting to install the helm chart, all the go into a crash loop with the same behavior: `cp: cannot stat '/opt/bitnami/redis/etc/redis-default.conf': No such file or directory`

**To Reproduce**
1. `helm install my-release bitnami/redis-cluster`
2. Run `kubectl get pods` to see that the my-release-redis-cluster-X pods are in a `CrashLoopBackOff` state

**Expected behavior**
bitnami/redis-cluster installs successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Full output from testing:
```
[user@centos7 ~]$ helm install h-redis bitnami/redis-cluster
^C
[user@centos7 ~]$ kubectl get pods
NAME                                                READY   STATUS        RESTARTS   AGE
h-redis-redis-cluster-cluster-create-kxgvc          1/1     Running       0          13s
h-redis-redis-cluster-5                             0/1     Error         0          13s
h-redis-redis-cluster-4                             0/1     Error         0          13s
h-redis-redis-cluster-0                             0/1     Error         1          13s
h-redis-redis-cluster-1                             0/1     Error         1          13s
h-redis-redis-cluster-3                             0/1     Error         1          13s
h-redis-redis-cluster-2                             0/1     Error         0          13s
[user@centos7 ~]$ helm status h-redis
NAME: h-redis
LAST DEPLOYED: Tue Jul 14 06:35:48 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **


To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace default h-redis-redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)

You have deployed a Redis Cluster accessible only from within you Kubernetes Cluster.INFO: The Job to create the cluster will be created.To connect to your Redis cluster:

1. Run a Redis pod that you can use as a client:
kubectl run --namespace default h-redis-redis-cluster-client --rm --tty -i --restart='Never' \
 --env REDIS_PASSWORD=$REDIS_PASSWORD \
--image docker.io/bitnami/redis-cluster:6.0.5-debian-10-r27 -- bash

2. Connect using the Redis CLI:

redis-cli -c -h h-redis-redis-cluster -a $REDIS_PASSWORD
[user@centos7 ~]$ kubectl get pods
NAME                                                READY   STATUS             RESTARTS   AGE
h-redis-redis-cluster-cluster-create-kxgvc          1/1     Running            0          39s
h-redis-redis-cluster-3                             0/1     CrashLoopBackOff   2          39s
h-redis-redis-cluster-5                             0/1     CrashLoopBackOff   2          39s
h-redis-redis-cluster-0                             0/1     CrashLoopBackOff   2          39s
h-redis-redis-cluster-2                             0/1     CrashLoopBackOff   2          39s
h-redis-redis-cluster-4                             0/1     CrashLoopBackOff   2          39s
h-redis-redis-cluster-1                             0/1     CrashLoopBackOff   2          39s
[user@centos7 ~]$ kubectl logs h-redis-redis-cluster-3 h-redis-redis-cluster
 13:36:29.72
 13:36:29.73 Welcome to the Bitnami redis-cluster container
 13:36:29.73 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
 13:36:29.73 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
 13:36:29.74
 13:36:29.74 INFO  ==> ** Starting Redis setup **
 13:36:29.78 INFO  ==> Initializing Redis...
cp: cannot stat '/opt/bitnami/redis/etc/redis-default.conf': No such file or directory
```
---
I find this error slightly strange because bitnami/redis still works.

**Comment by andresbono** [comment]
Hi @duvallj, thanks for opening this issue. We couldn't reproduce it, we are using `3.1.5` as well.

- Are you modifying any of the default values for the chart?
- What is the image that you are using?

```
kubectl get pod h-redis-redis-cluster-0 -o jsonpath='{.spec.containers[0].image}'
```

- Are you installing the deployment from scratch? Do you have PVCs from previous retries?
- Is the configmap for that file being created?

```
kubectl get configmap h-redis-redis-cluster-default
```

**Comment by duvallj** [comment]
Hi @andresbono , thank you for the follow-up! To answer your questions:
* No, I am not modifying any default values
* The output of the command to get the image shows `docker.io/bitnami/redis-cluster:6.0.5-debian-10-r27`, which is the same image you said you were using
* I did not manually configure any PVCs, but I did run `helm uninstall h-redis` before retrying each time. Is this something I should look harder at?
* The output of the command to see if the configmap exists is:
```
[user@centos7 ~]$ kubectl get configmap h-redis-redis-cluster-default
NAME                            DATA   AGE
h-redis-redis-cluster-default   1      4m36s
```
(the time shows up as fairly new because I re-installed `redis-cluster` to respond, it is still failing)
---
Something else that might be an issue: I am in a corporate environment where any non-proxied requests to the outside internet will fail. I have the proxy variables set up for my local session (so helm doesn't seem to have any problems) and for kubernetes' CRI backend so it can pull images, but might the processes inside the container also be trying to do something with the internet?

**Comment by andresbono** [comment]
> * I did not manually configure any PVCs, but I did run `helm uninstall h-redis` before retrying each time. Is this something I should look harder at?

You might try to remove the PVCs created for the deployment in addition to the `helm uninstall`. Make sure you don't mind removing them. That way, you will start from a totally new, clean deployment.

It is a very weird issue indeed. 

---

> Something else that might be an issue: I am in a corporate environment where any non-proxied requests to the outside internet will fail. I have the proxy variables set up for my local session (so helm doesn't seem to have any problems) and for kubernetes' CRI backend so it can pull images, but might the processes inside the container also be trying to do something with the internet?

There shouldn't be any issues with restricted networks to global internet.
