### ISSUE TITLE
[bitnami/etcd] Restore Issues on Kubernetes

### ISSUE THREAD

**Issue by dk-do** [bitnami/charts#3114]
**Which chart**:
Tested with etcd-4.8.9 and etcd-4.4.3

**Describe the bug**
We have some issues regarding etcd-backup restores on Kubernetes:
The etcd-snapshotter is running every hour. Once a day we copy the data from the etcd-snapshot directory to a backup folder in filesystem to perform a tape backup.

Time by time we are struggeling with restoring data.

**To Reproduce**
1. Copy the db file to /tmp/ to all etcd-0, etcd-1, etcd-2 pods.

2. Run the restore-snapshot command in all pods.
`kubectl exec -it etcd-0 -- etcdctl snapshot restore /tmp/db --name etcd-0 --initial-cluster etcd-0=http://etcd-0.etcd-headless.default.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-headless.default.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-headless.default.svc.cluster.local:2380 --initial-cluster-token etcd-cluster-k8s --initial-advertise-peer-urls http://etcd-0.etcd-headless.default.svc.cluster.local:2380`

3. COPY the restored data from /opt/bitnami/etcd/etcd-0.etcd/member/snap/db to the default data directory: /bitnami/etcd/data/member/snap/

4. Unfortunately it is not possible to change the data dir to the original restore location, because it contains the pod-id in the path: /opt/bitnami/etcd/**etcd-0.etcd**/member/snap/db

5. This is why we copy the restored data to the original path.

6. Scale the statefulset down and up again.

Sometimes the restore is working. Sometimes we get these errors:

+ etcd-0 › etcd
etcd-0 etcd ==> Bash debug is off
etcd-0 etcd ==> Detected data from previous deployments...
+ etcd-2 › etcd
etcd-2 etcd ==> Bash debug is off
etcd-2 etcd ==> Detected data from previous deployments...
+ etcd-1 › etcd
etcd-1 etcd ==> Bash debug is off
etcd-1 etcd ==> Detected data from previous deployments...
etcd-2 etcd ==> Cluster not responding!!
etcd-2 etcd ==> There was no snapshot to perform data recovery!!
etcd-1 etcd ==> Cluster not responding!!
etcd-1 etcd ==> There was no snapshot to perform data recovery!!
etcd-0 etcd ==> Cluster not responding!!
etcd-0 etcd ==> There was no snapshot to perform data recovery!!

**Expected behavior**
Always a successful backup restore.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
  I can see this is already being tracked here https://github.com/bitnami/bitnami-docker-etcd/issues/7
  To not duplicate issues, I am closing this one.
