### ISSUE TITLE
[bitnami/jenkins] initHookScriptsSecret in values.yaml throws an error if not set to empty.

### ISSUE THREAD

**Issue by starci183** [bitnami/charts#31167]
### Name and Version

bitnami/jenkins

### What architecture are you using?

None

### What steps will reproduce the bug?

I created a secret named `example` that contains several Groovy init hook scripts (for example `example1.groovy`, `example2.groovy`). 
An error occurred after setting `initHookScriptsSecret: example` in the `values.yaml` file. 

The error message is (I use Terraform): 
```
"Deployment.apps "jenkins" is invalid: [spec.template.spec.volumes[2].projected.sources[1].secret.name: Required value, spec.template.spec.containers[0].volumeMounts[5].name: Not found: "jenkins-init-hook-scripts"]."
```

After doing some research, I found the following line in the ([`templates/deployment.yaml`](https://github.com/bitnami/charts/blob/main/bitnami/jenkins/templates/deployment.yaml))

```yaml
- secret:
   secretName: {{ print (tpl .Values.initScriptsSecret .) }}
   defaultMode: 0755
```
The error suggests that the `secret.name` is not specified, which seems to be the cause. I'm wondering if the recent Kubernetes version has changed `secretName` to `name`, or if I missed something in the configuration.

### Are you using any custom parameters or values?

`initHookScriptsSecret: example`

### What is the expected behavior?

The Helm chart has been installed, and the init hook scripts are working correctly.

**Comment by dgomezleon** [comment]
Hi @starci183 ,

Thanks for reporting it. I have just sent a fix.

**Comment by starci183** [comment]
> Hi @starci183 ,
> 
> Thanks for reporting it. I have just sent a fix.
