### ISSUE TITLE
We detected a DOS attack from WordPress pod to these IPs

### ISSUE THREAD

**Issue by tnakajo** [bitnami/charts#3118]
**Which chart**:
WordPress 
https://cloud.ibm.com/catalog/content/wordpress-Qml0bmFtaS13b3JkcHJlc3M=-global#about

**Describe the bug**
IBM Cloud Abuse team and Trust & Safety Analyst team detected a DOS attack from the IBM Cloud IKS worker node (10.85.50.61 / 158.177.229.162) to the owner(s) of these IPs (Outside of IBM Cloud network).

The customer of the IKS cluster running the bitami WordPress, doesn't know why/how their IKS system is attacking those IPs. We need to assist to find out how to resolve this.

**To Reproduce**
We don't know but it keeps attacking.

**Expected behavior**
IKS cluster/workers/pods should not access to the external IPs frequently.

**Version of Helm and Kubernetes**:
N/A

- Output of `kubectl version`:
N/A

**Additional context**

The owner(s) of these IPs are sending us complaints of the IKS worker node IP (10.85.50.61 / 158.177.229.162) attacking their IP space without authorization.

The IP has been attacking the following:
```
cpanel6.vhosting-it.com - 185.229.236.37
cpanel2.vhosting-it.com - 31.14.137.219
cpanel3.vhosting-it.com - 185.25.206.144
ssd2-cpanel.vhosting-it.com - 78.47.158.89
```

The owner(s) of these IPs detected a DOS attack from the IBM Cloud Network.
Below is the logs:
```
158.177.229.162 - - [06/Jul/2020:14:04:16 +0200] "GET /wp-login.php HTTP/1.1" 200 5699 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:04:17 +0200] "POST /wp-login.php HTTP/1.1" 200 6115 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:04:18 +0200] "POST /xmlrpc.php HTTP/1.1" 404 27422 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:24 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:24 +0200] "POST /wp-login.php HTTP/1.1" 200 3460 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:24 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:24 +0200] "POST /wp-login.php HTTP/1.1" 200 3441 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:24 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:24 +0200] "POST /wp-login.php HTTP/1.1" 200 3442 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "POST /wp-login.php HTTP/1.1" 200 3444 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "POST /wp-login.php HTTP/1.1" 200 3445 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "POST /wp-login.php HTTP/1.1" 200 3446 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:23:37:25 +0200] "GET /wp-login.php HTTP/1.1" 200 3068 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:18:53 +0200] "GET /wp-login.php HTTP/1.1" 200 7983 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:18:54 +0200] "POST /wp-login.php HTTP/1.1" 401 3595 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:18:55 +0200] "GET /wp-login.php HTTP/1.1" 200 7983 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:18:56 +0200] "POST /wp-login.php HTTP/1.1" 401 3594 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:18:57 +0200] "POST /xmlrpc.php HTTP/1.1" 301 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
158.177.229.162 - - [06/Jul/2020:14:18:57 +0200] "GET /xmlrpc.php HTTP/1.1" 404 18101 "http://www.orestegaspari.com/xmlrpc.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefo
```

*IBM Cloud Support investigated from IKS perspective*
I see the IKS cluster has the following 2 workers running at this moment and I'd like to find out which pod (application) is causing the issue via the worker node (10.85.50.61 / 158.177.229.162).

```
kube-bqnvqhbf0banu8mjret0-incituclust-pool2to-00000844 fra02 iks.ibm 10.85.50.5 / 158.177.229.171
kube-bqnvqhbf0banu8mjret0-incituclust-pool2to-00000939 fra02 iks.ibm 10.85.50.61 / 158.177.229.162
```

I suspect the following pod causing the issue.  
```  
NAMESPACE NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES  
reklameapp1 reklameapp1-wordpress-678846bf96-dzrt8 1/1 Running 0 18h 172.30.250.249 10.85.50.61 <none> <none>  
```  
As I verified by the following commands.
``` 
$ kubectl describe pod/reklameapp1-wordpress-678846bf96-dzrt8 -n reklameapp1 >pod.describe.txt  
$ kubectl logs reklameapp1-wordpress-678846bf96-dzrt8 -n reklameapp1 >logs.reklameapp1.txt  
```  

I see lots of the following logging every minute in the pod. (logs.reklameapp1.txt)

```
172.30.250.249 - - [13/Jul/2020:11:55:32 +0000] "POST /wp-cron.php?doing_wp_cron=1594641332.9818029403686523437500 HTTP/1.1" 200 -  
10.85.50.61 - - [13/Jul/2020:11:55:32 +0000] "GET /wp-login.php HTTP/1.1" 200 1911  
172.30.250.249 - - [13/Jul/2020:11:56:33 +0000] "POST /wp-cron.php?doing_wp_cron=1594641392.9964718818664550781250 HTTP/1.1" 200 -  
10.85.50.61 - - [13/Jul/2020:11:56:32 +0000] "GET /wp-login.php HTTP/1.1" 200 1911  
10.85.50.61 - - [13/Jul/2020:11:56:36 +0000] "GET /wp-login.php HTTP/1.1" 200 1911
```

It seems the WordPress application pod causes the issue to abuse the external IPs. 
Could you investigate the issue of why the pod access the IPs like a DoS attack?

**Comment by tnakajo** [comment]
[pod.describe.txt](https://github.com/bitnami/charts/files/4923181/pod.describe.txt)
[get_services_-o_wide.txt](https://github.com/bitnami/charts/files/4923182/get_services_-o_wide.txt)
[get_pods_-o_wide.txt](https://github.com/bitnami/charts/files/4923183/get_pods_-o_wide.txt)
[pod.describe.txt](https://github.com/bitnami/charts/files/4923184/pod.describe.txt)

**Comment by beltran-rubo** [comment]
Hi @tnakajo 

A possible to this issue is the customer migrated his own WordPress site (previously hosted in vhosting-it.com) to the IKS Bitnami WordPress deployment. That migration requires to configure properly WordPress to point to the new IP or domain and it is possible the customer did not change it.

The K8s health checks are running every 10 secs by default and it is trying to get the "/wp-login.php" page to check it is active. That request could also imply to get redirected to the previous domain (vhosting-it) for that 'wp-login.php' but also for other static files probably (js, css, png,...).

Could you please confirm with the customer if that could be the case? check with the customer to configure WordPress domain properly from the admin panel or to update the domain IP address to point to the new installation? 

Another suggestion would be to increase the time for the k8s liveness & readiness checks with `kubectl edit reklameapp1-wordpress` and replace "periodSeconds=10" with "periodSeconds=60", that should also decrease the external queries.

Let us know if that helps.

**Comment by tnakajo** [comment]
Thank you. I invited the customer here to respond.

**Comment by Photic** [comment]
Hello, I am the person currently working on the talked about cluster.

The wordpress.txt files is the yaml file used to spin up reklameapp1 to start with. The configuration changed is only the readiness and liveliness probes.

At the moment there is only 2 wordpress instances running, but we had, at some point, 6 running, all spun up using the same yaml file, which would explain the amount of traffic hitting vhosting at the same time. It does not explain why we are hitting them to start with. 

The customer in question says they did not know about the website vhosting prioer to the attacks. 

[wordpress.txt](https://github.com/bitnami/charts/files/4924565/wordpress.txt)

**Comment by beltran-rubo** [comment]
Did they customize WordPress somehow? installing plugins (e.g. a CDN plugin for static assets) or restoring a previous WordPress installation could make to do requests to other sites.

If you run `wget http://(IP or Domain)/wp-login.php`, could you check if you see those IPs or Domains inside the html page?

**Comment by Photic** [comment]
All the ip addresses using the command wget yields the correct ingress ip for the cluster. 

They do have wordpress plugins installed, just dont see how those plugins could have anything to do with the probing of vhosting in such a specific manner. Only way to find out is to kill the wordpress pods, and see if the attacks continue I guess.

**Comment by beltran-rubo** [comment]
You can try but if the code for connecting to those servers is into the wordpress plugins/uploads folder (inside 'wp-content' folder) it will continue happening as this folder is in a persistent volume.
