### ISSUE TITLE
Can we have VPA with Postgres

### ISSUE THREAD

**Issue by rg2609** [bitnami/charts#3120]
**Which chart**:
Postgres

I am trying to add the [Vertical Pod autoscaling (VPA)](https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler) in Postgres chart, and my questions are

- Can we add VPA with Postgres 

-  if we can, then how to do it

Any help on this VPA topic will be appreciated.
Thank you.

**Comment by marcosbc** [comment]
Hi @rg2609, it's not something the chart currently supports, but you could always contribute it via a PR. We would be glad to review it!

**Comment by rg2609** [comment]
Thank you @marcosbc for a reply, can you give us any guidelines about it

**Comment by marcosbc** [comment]
Sure!

If you want to enable VPA, you would need to define a resource affecting the Helm chart. To do that, create a file such as `vertical-pod-autoscaler.yaml` inside the `bitnami/postgresql/templates` directory in this repository.

The file would have a structure similar to what is defined here: https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling#getting_resource_recommendations

In this case, PostgreSQL uses a StatefulSet, so you would need to update the target not to be referring to a Deployment. You should also target slave nodes.

In https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling#opt_out_specific_containers they describe how to opt out specific containers, so this does not affect sidecar containers. Keep that in mind.

Finally, note that you would also need to add some options to enable/disable VPA (should be disabled by default) in `values.yaml` and document this in the README.md file.

**Comment by rg2609** [comment]
@marcosbc, Thank you for your reply
I got your point on how to add VPA in Postgres. VPA evacuate the pod and restart it, is there any harm or chance of any data loss.

**Comment by marcosbc** [comment]
Note that PostgreSQL data is persisted with PVCs, so you should not worry about data loss. And since the amount of nodes doesn't change, you should not see new volumes being created or other volumes being deleted either.
