### ISSUE TITLE
`postgresql-postgres-password` doesn't work with `global.postgresqlUsername` and without `postgresqlPostgresPassword`

### ISSUE THREAD

**Issue by tschale** [bitnami/charts#3130]
**Which chart**: postgresql 9.1.1

**Describe the bug**
Including `postgresql-postgres-password` in the `existingSecret` only works when `postgresqlUsername` and `postgresqlPostgresPassword` are set. It doesn't work when `global.postgresqlUsername` is set instead or when the password is only included as `postgresql-postgres-password` in the secret without a value for `postgresqlPostgresPassword` in the values. There's an explicit check for both of those in `charts/bitnami/postgresql/templates/statefulset.yaml`:
```
{{- if and .Values.postgresqlPostgresPassword (not (eq .Values.postgresqlUsername "postgres")) }}
```
Not sure whether actually a bug or expected behavior. If it's expected behavior it might be better documented.

**To Reproduce**
1. set `global.postgresqlUsername` and include `postgresql-postgres-password` in `existingSecret`
2. don't set `postgresqlUsername` and/or `postgresqlPostgresPassword`
3. install chart
4. see that `POSTGRES_POSTGRES_PASSWORD` is missing in the pods `env` definition

**Expected behavior**
- that it doesn't matter whether `global.postgresqlUsername` or `postgresqlUsername` is used
- that `postgresqlPostgresPassword` doesn't need to be set in values but it's value only needs to be included as `postgresql-postgres-password` in the `existingSecret`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0+k3s.1", GitCommit:"0f644650f5d8e9f091629f860b342f221c46f6d7", GitTreeState:"clean", BuildDate:"2020-01-06T23:22:38Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for noticing this. 
   I have created an internal task to fix this because the changes needed can have lateral effects in other charts that use this one.
  We will come back as soon as we have news.
  In any case, PR will be welcome and we will be glad to review it.

**Comment by tschale** [comment]
Thank you! I'll keep it in mind, but I don't think I'll be able to work on a PR in the short term...
