### ISSUE TITLE
bitnami/elasticsearch/  service  type is not   headless 

### ISSUE THREAD

**Issue by yangvipguang** [bitnami/charts#3131]
**Which chart**:
The name (and version) of the affected chart
elasticsearch-12.5.1	
**Describe the bug**
I want to know why   isn't the  data and master  statefulset's service type None (aka  headless)。

![图片](https://user-images.githubusercontent.com/11416887/87618730-237c9d80-c74d-11ea-86e1-68df7bce0310.png)

**Comment by javsalgar** [comment]
Hi,

The context of not making it headless was for Istio compatibility. You can find more info in this issue: https://github.com/bitnami/charts/issues/2199
