### ISSUE TITLE
Excessive cpu usage from mediawiki probes

### ISSUE THREAD

**Issue by mnorrsken** [bitnami/charts#3138]
**Which chart**:
Mediawiki 10.0.1

**Describe the bug**
The probing to api.php causes excessive cpu usage because api.php renders the "help" page

**To Reproduce**
1. Check cpu usage for idle container

**Expected behavior**
Not that much cpu usage from idle container

To fix, change probe to:
 /api.php?action=query&meta=siteinfo&format=none

**Comment by andresbono** [comment]
Thank you very much for the suggestion, @mnorrsken!! Would you like to open a PR addressing the changes? Contributions are more than welcome 👍

**Comment by mnorrsken** [comment]
Not done anything like that before but ill try. I also think i have to test it with different security settings.

**Comment by marcosbc** [comment]
I've created #3349 for fixing this issue. Thanks for the suggestion!
