### ISSUE TITLE
[bitnami/mongodb] when metrics disabled, metrics-svc.yaml should not be created

### ISSUE THREAD

**Issue by ianhlee** [bitnami/charts#3151]
**Which chart**:
mongodb

**Describe the bug**
when metrics.enabled: false, metrics-svc.yaml content should be generated

**To Reproduce**
1. Go to values.yaml file
2. Change metrics.enabled from true to false
3. Run helm install or helm template to see metrics-svc.yaml content is generated

**Expected behavior**
metrics-svc.yaml content should **NOT** be generated so that it is not deployed to Kubernetes

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
```

**Additional context**
I think there should be if statement to check for metrics.enabled then it generates the content only if it is true

**Comment by beltran-rubo** [comment]
Hi @ianhlee, thanks for reporting it, it seems a specific use case we need to improve. In order to speed up the process to get fixed we encourage users to submit PRs that way we can review & test the changes faster.

Thanks,

**Comment by marcosbc** [comment]
Fixing in #3346
