### ISSUE TITLE
Not able to access running kafka using port forward from outside the cluster

### ISSUE THREAD

**Issue by gittadesushil** [bitnami/charts#3154]
**Which chart**:
helm install my-release bitnami/kafka

**Describe the bug**
Fort forward is not allowing me to access running kafka service. 

Command I run to install helm charts:
```
helm install my-release bitnami/kafka --set externalAccess.enabled=true,externalAccess.service.type=NodePort,externalAccess.autoDiscovery.enabled=true,serviceAccount.create=true,rbac.create=true,persistence.size=1Gi
```

**To Reproduce**
my-release-kafka-0-external is successfully running on my cluster
NAME                                      TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                
my-release-kafka-0-external   NodePort   x.x.x.x              <none>            9094:30080/TCP 

Run below command:
 kubectl port-forward services/my-release-kafka-0-external 8080:9094

**Expected behavior**
I should be able to access the kafka broker.

**Actul behavior**
The broker localhost:8080 is reachable but kafka can't connect. 
Ensure you have access to the *advertised listeners* of the cluster and the proper authorizations.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I want to access Kafka brokers from outside the cluster. Using NodePort services I followed below Option
A) Use random node ports using an initContainer that discover them automatically.
I can't use loadbalencer becuase some IP and ports are blocked in my organization. I need to use kafka outside cluster to execute my tests.

**Comment by joancafom** [comment]
Hi @gittadesushil !

Thanks for posting your issue. There is a step I don't really understand, but maybe you can provide me with a little bit more context:

> Run below command:
> kubectl port-forward services/my-release-kafka-0-external 8080:9094

I guess you are trying to forward traffic from your localhost:8080 to cluster's 9094 but I think there is no need to (and that in fact, would not be considered external traffic). Since you are using NodePort, you may find more convenient to directly access using the IP assigned to that service. If you are using minikube, this can be easily done as so:

```console
$ minikube service my-release-kafka-0-external --url                                                                                                                                                                             
http://192.168.99.101:30761
```

Having said that, the main issue here might be that the external access is not configured properly. By default when using NodePort, if no IP or domain is explicitly specified, the external/public IP of the machine running the cluster will be used. E.g:

```console
$ helm install my-release-one bitnami/kafka --set externalAccess.enabled=true,externalAccess.service.type=NodePort,externalAccess.autoDiscovery.enabled=true,serviceAccount.create=true,rbac.create=true,persistence.size=1Gi
$ k exec -it my-release-one-kafka-0  -- cat /opt/bitnami/kafka/config/server.properties | grep advertised.listeners                                                                   
advertised.listeners=INTERNAL://my-release-one-kafka-0.my-release-one-kafka-headless.default.svc.cluster.local:9093,CLIENT://my-release-one-kafka-0.my-release-one-kafka-headless.default.svc.cluster.local:9092,
EXTERNAL://MY_PUBLIC_IP:30761
```

It is more than likely that access through this address is not configured properly (from what I have understood from your context), and using it will end up in a timeout or other error. However, you can specify the domain or external ip used to configure Kafka external listener when service type is NodePort using the parameter `externalAccess.service.domain`. 

```console
$ helm install my-release-two bitnami/kafka --set \ 
externalAccess.enabled=true, \
externalAccess.service.type=NodePort, \ 
externalAccess.autoDiscovery.enabled=true, \
serviceAccount.create=true, \
rbac.create=true, \
persistence.size=1Gi, \
externalAccess.service.domain=192.168.99.101
```

Now, I can successfully connect and use both a producer and a consumer:

```console
$ kafka-console-producer.sh --broker-list 192.168.99.101:30761 --topic test
> test
> bitnami

$ kafka-console-consumer.sh --bootstrap-server 192.168.99.101:31463 --topic test --from-beginning
test
bitnami
^C
Processed a total of 2 messages
```

Hope it can help, thanks!

**Comment by gittadesushil** [comment]
@joancafom Thank you for your time and help.
**Update:** I am not using minikube. I am using a cluster which is deployed on Azure. 

When I deploy my-release-two I see you have assigned the ip address to externalAccess.service.domain property. My question is how can I get available IP address that I have to assign?

**Now I have executed the 2nd command for deplyoing  my-release-two**

> Still I am confused, I am not able to access the IP of Node. I am not able to ping the IP itself.


Now I tried use port forwarding with assigned port 31608 but I will get error on my console. I am not able to connect to broker.

`E0722 13:58:36.737159   40536 portforward.go:400] an error occurred forwarding 8080 -> 31608: error forwarding port 31608 to pod f53cc320b75879d3cf3aa101da3fe9bbebd05e65a5281fa2d13874b807869bff, uid : exit status 1: 2020/07/22 11:58:36 socat[92969] E connect(5, AF=2 127.0.0.1:31608, 16): Connection refused`

I am stuck and No clue what to do? I should be able to access this using port-forward but still I think something is wrong with Advertised host.

**Comment by viggys** [comment]
Hey @joancafom , I have the externalAccess configured as you have mentioned with domain and nodePort.
But i'm still facing the issues connecting to kafka externally.

Chart version: **kafka-11.5.1**

**Note**: I'm not facing this issue when using **kafka-10.3.3**. Works perfectly, except for kafka-exporter (when auth is enabled).

I'm trying to upgrade the chart from **_10.3.3_** to the **_latest_** version, as **_10.3.3_** has no authentication support for kafka-exporter.

**Comment by gittadesushil** [comment]
> Hey @joancafom , I have the externalAccess configured as you have mentioned with domain and nodePort.
> But i'm still facing the issues connecting to kafka externally.
> 
> Chart version: **kafka-11.5.1**
> 
> **Note**: I'm not facing this issue when using **kafka-10.3.3**. Works perfectly, except for kafka-exporter (when auth is enabled).
> 
> I'm trying to upgrade the chart from **_10.3.3_** to the **_latest_** version, as **_10.3.3_** has no authentication support for kafka-exporter.

@viggys Are you running it on kubernetes cluster or locally? Can you give an example that How you are accessing using Node port externally? I also get NodeIp but still I am not able to connect. Is that becuase of different range of IPs?

**Comment by viggys** [comment]
@joancafom , I see the [README](https://github.com/bitnami/charts/tree/master/bitnami/kafka#to-1100) mentions there has been some refactoring around the configuration of listeners during the chart version upgrade from 10.x to 11.x.

I have below observation related to why the external access may not be working with v11,

Listeners Configuration generated for broker server.properties
**v10** --> ```listeners=INTERNAL://:9092,EXTERNAL://:61021```
**v11** --> ```listeners=INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094```

I understand that the client and inter-broker communications are using different ports in v11 (allowing for different protocols).  Important thing is that the port configured for EXTERNAL listener is **NodePort** (61021) in **v10**, but it is **container port** (9094) in case of **v11**, which i believe is causing the connectivity issue.

Can you please verify this observation?
In case the above configuration is intended, please share any missing configuration details.

**Comment by viggys** [comment]
> @viggys Are you running it on kubernetes cluster or locally? Can you give an example that How you are accessing using Node port externally? I also get NodeIp but still I am not able to connect. Is that becuase of different range of IPs?

@gittadesushil 
I'm running this on a k8s cluster with multiple replicas of kafka and zookeeper.
Try using the v10.3.3 chart and follow the steps as mentioned (here)[https://github.com/bitnami/charts/tree/master/bitnami/kafka#using-nodeport-services] for external access using NodePort.

**Comment by juan131** [comment]
Thanks for opening the PR! Moving discussion there

**Comment by esafzay** [comment]
@gittadesushil I am facing the same issue. Were you able to connect to Kafka from your local system?
