### ISSUE TITLE
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored' on a fresh insta;;

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [bitnami/charts#3157]
**Which chart**:
wordpress:9.3.20

**Describe the bug**
I am trying to install wordpress inside a custom kubernetes cluster (not AKS) inside Azure. I am deploying with 3 replicas and as mentioned in the docs, I am setting `persistence.accessMode: ReadWriteMany`. For Azure, AzureFiles is the only storage mechanism which supports `ReadWriteMany` and it is registered as a storage class in the cluster. So, I am also setting `persistence.storageClass: files`.

Now, when I install the chart, I find that it takes a lot of time to copy the files over to the volume, like upwards of 5 minutes. I can see that the plugins and themes do get copied. When it tries to work on the `.initialised` file, it crashes. On restarting, it crashes again while trying to work on the `.restored` file.

I tried reinstalling with a single replica and the `storageClass` set to Azure Disk and the copy completed pretty fast so this doesn't seem to be a user permission issue as in https://github.com/bitnami/bitnami-docker-wordpress/issues/218. I am pretty stumped at this. Any ideas what could be causing this?

**To Reproduce**
1. Install the wordpress helm chart with the production specs and the `storageClass` set to Azure Files
2. See slow copy and ultimately error `Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/wordpress/.restored'`

**Expected behavior**
The chart is supposed to get installed perfectly while using Azure Files

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"2b13e288f94dd2577d4ff7261f9eb76b1d5692a1", GitTreeState:"clean", BuildDate:"2020-06-01T21:55:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I must note that I am using the bitnami wordpress chart as a dependency in my chart since I need to deploy some custom resources like Istio Gateway. But I tried installing the bitnami chart by itself and faced the same issue.

**EDIT**
I tried to deploy in an AKS cluster too and it is failing. There seems to be some issue with Azure Files itself.

---
**EDIT 2**
I did some more digging, by using Azure files and by using Azure disks. In the default setup, using Azure Disks work and the files are created as such
```
I have no name!@wordpress-blog-56968f7cdc-r22qj:/bitnami$ ls -la
total 68
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 .
drwxr-xr-x. 1 root root 4096 Jul 19 11:22 ..
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 apache
drwxrwxr-x. 2 root root 4096 Jul 15 05:42 gosu
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 libphp
drwxrwxr-x. 1 root root 4096 Jul 15 05:41 php
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 tini
drwxrwsr-x. 3 root 1001 4096 Jul 19 11:23 wordpress
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 wp-cli
I have no name!@wordpress-blog-56968f7cdc-r22qj:/bitnami/wordpress$ ls -la
total 24
drwxrwsr-x. 3 root 1001 4096 Jul 19 11:23 .
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 ..
-rw-r--r--. 1 1001 1001    0 Jul 19 11:23 .initialized
-r--r-----. 1 1001 1001 4297 Jul 19 11:23 wp-config.php
drwxr-sr-x. 4 1001 1001 4096 Jul 19 11:23 wp-content
```
When using Azure Files, the same directories look like
```
I have no name!@wordpress-blog-56968f7cdc-vwnwl:/bitnami$ ls -la
total 64
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 .
drwxr-xr-x. 1 root root 4096 Jul 19 12:13 ..
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 apache
drwxrwxr-x. 2 root root 4096 Jul 15 05:42 gosu
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 libphp
drwxrwxr-x. 1 root root 4096 Jul 15 05:41 php
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 tini
drwxrwxrwx. 2 root 1001    0 Jul 19 12:03 wordpress
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 wp-cli
I have no name!@wordpress-blog-56968f7cdc-vwnwl:/bitnami/wordpress$ ls -la
total 8
drwxrwxrwx. 2 root 1001    0 Jul 19 12:03 .
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 ..
drwxrwxrwx. 2 root 1001    0 Jul 19 12:03 wp-content
```
Note: I cannot show the full contents of `/bitnami/wordpress` as the container crashes

So, I created another storage class but with setting my own `mountOptions`
```
mountOptions:
- uid=1001
- gid=1001
```
Using this storage class works although the performance is still orders slower than Azure disk. The files look like this using this storage class:
```
I have no name!@wordpress-blog-56968f7cdc-29wzk:/bitnami$ ls -la
total 64
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 .
drwxr-xr-x. 1 root root 4096 Jul 19 12:19 ..
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 apache
drwxrwxr-x. 2 root root 4096 Jul 15 05:42 gosu
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 libphp
drwxrwxr-x. 1 root root 4096 Jul 15 05:41 php
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 tini
drwxrwxrwx. 2 1001 1001    0 Jul 19 12:19 wordpress
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 wp-cli
I have no name!@wordpress-blog-56968f7cdc-29wzk:/bitnami/wordpress$ ls -la
total 8
drwxrwxrwx. 2 1001 1001    0 Jul 19 12:19 .
drwxrwxr-x. 1 root root 4096 Jul 15 05:42 ..
drwxrwxrwx. 2 1001 1001    0 Jul 19 12:19 wp-content
```

The conclusion I can draw is that when the contents of the `wordpress` folder are owned by 1001/1001, things work fine. In Azure disks case, the `wordpress` folder has `drwxrwsr-x` which gives its contents the correct perms. Creating my own Azure file storage class forces the contents of `wordpress` folder to be 1001/1001 by making the `wordpress1 folder owned by 1001/1001.

I understand the root cause but I have no idea how to fix it. Creating the custom storage class seems like a hack. Any ideas how this can be solved?

**Comment by andresbono** [comment]
Hi @SayakMukhopadhyay, thank you very much for the analysis on the performance issues with Azure files. There is not so much we can think about to solve the issue. You might try by changing the security context options for the WordPress pods. That way, it is possible that you don't need to tweak the mount options of the storage class: https://github.com/bitnami/charts/blob/8d0240ec3b35587a4b78e5730719f567cf3a503c/bitnami/wordpress/values.yaml#L197-L200

However, we recommend enabling the security context with a non-privileged user for security reasons.

We will keep this issue open in case someone else has any suggestions on the topic.

**Comment by SayakMukhopadhyay** [comment]
Hi @andresbono , thanks for the response. Right now, I am using the production spec provided with the chart which uses the above values already
```
securityContext: 
   enabled: true 
   fsGroup: 1001 
   runAsUser: 1001 
```
I realise that the performance issue is not within your control but the fact that the same `securityContext` values creates difference file/folder perms for Azure Disk and Azure File is weird and I was hoping if you would have some insight into it. I was also hoping that getting to the bottom of the perms issue might resolve the performance issue too.

**Comment by andresbono** [comment]
I'd say that in Azure Files the permissions and ownership are given by the mount options that you specify in the storage class and those can't be changed ([ref](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv#mount-options)), hence the difference between both storage services (Azure Disk and Azure Files).
