### ISSUE TITLE
[mongodb] Unable to deploy replicaset due to bug in portName

### ISSUE THREAD

**Issue by kev24uk** [bitnami/charts#3161]
**Which chart**:
mongodb

**Describe the bug**
Attempting to deploy a mongodb replicaset gives the following error:

```Error: template: mongodb/templates/replicaset/external-access-svc.yaml:31:22: executing "mongodb/templates/replicaset/external-access-svc.yaml" at <.Values.service.portName>: can't evaluate field Values in type int```

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
At a quick glance, it seems to have come from a recent commit and the offending yaml file looks like it is missing a $root in front of the .Values.service.portName

Dropping back to version 8.0.9 of the chart works fine.

**Comment by juan131** [comment]
Thanks so much for reporting it @kev24uk !! I just created a PR to address it
