### ISSUE TITLE
Unable to deploy chart using terraform: 403 forbidden on index.yaml

### ISSUE THREAD

**Issue by yghern** [bitnami/charts#3166]
Hello.
I am using terraform to deploy one of your helm modules (external-dns). Since yesterday my terraform started getting 403 error when trying to access https://charts.bitnami.com/index.yaml (I tried to access it using Terraform itself, browser and wget@linux). The same code run successfully for several weeks now without any change from my side, so I narrowed it down to change in your configuration.

Terraform output
Error: failed to resolve "external-dns", Looks like "https://charts.bitnami.com" is not a valid chart repository or cannot be reached: Failed to fetch https://charts.bitnami.com/index.yaml : 403 Forbidden

The domain charts.bitnami.com is visible and can be reached without an issue.

Let me know if I can be any more helpful.
Regards,
Artur Chamier

**Comment by iamwithnail** [comment]
I had this this morning.  The address you have is an older one that isn't being forwarded anymore - if you replace the repository url with `https://charts.bitnami.com/bitnami` it'll go back to working.

**Comment by yghern** [comment]
Yup I can now confirm that updating repo URL fixes the problem

**Comment by rafariossaa** [comment]
Hi,
  I am glad you were able to fix the issue.
  Thanks for sharing.

**Comment by dinbtechit** [comment]
I still see 403 Forbidden

I can't access the URL directly  https://charts.bitnami.com/bitnami/posgresql

![image](https://user-images.githubusercontent.com/17984781/199481154-34512e6d-7d8a-465d-a390-87dea0da294a.png)


```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "https://charts.bitnami.com/bitnami/postgresql" chart repository:
        failed to fetch https://charts.bitnami.com/bitnami/postgresql/index.yaml : 403 Forbidden
...Unable to get an update from the "https://charts.bitnami.com/bitnami/mongodb" chart repository:
        failed to fetch https://charts.bitnami.com/bitnami/mongodb/index.yaml : 403 Forbidden
```

**Comment by zdhamasha** [comment]
same issue here 

https://charts.bitnami.com/bitnami/minio

`"https://charts.bitnami.com" is not a valid chart repository or cannot be reached: failed to fetch https://charts.bitnami.com/index.yaml : 403 Forbidden`

**Comment by ThePlenkov** [comment]
what is the right way to access charts?

**Comment by carrodher** [comment]
The preferred way to consume Bitnami Helm charts is as OCI packages hosted in DockerHub:
```
helm install my-release oci://registry-1.docker.io/bitnamicharts/<chart>
```
