### ISSUE TITLE
[bitnami/discourse] Administrator account is not set

### ISSUE THREAD

**Issue by LucaPrete** [bitnami/charts#3169]
**Which chart**:
Discourse 0.1.7

**Describe the bug**
The first time I start Discourse and I navigate to the home page I get the following message:

```
Unfortunately, no administrator emails were defined during setup, so finalizing the configuration may be difficult. Please add a developer email in the configuration file or create an administrator account from console.
```

**First issue: ** the email has been provided through the *DISCOURSE_EMAIL* env variable (see the configmap file of the chart). Why the GUI still asks to create an account?

**Second issue: ** Clicking on the link "create an administrator account from console" the docs mention to create the admin account using the command "rake admin:create". Although it's not optimal I exec into the discourse container and I try to run the command in /opt/bitnami/discourse, but I get the message below:

```
root@discourse-56f75df579-c9f4k:/opt/bitnami/discourse# rake admin:create
rake aborted!
Gem::LoadError: You have already activated rake 12.3.3, but your Gemfile requires rake 13.0.1. Prepending `bundle exec` to your command may solve this.
/opt/bitnami/discourse/config/boot.rb:13:in `<top (required)>'
/opt/bitnami/discourse/config/application.rb:16:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/ruby/bin/ruby_executable_hooks:24:in `eval'
/opt/bitnami/ruby/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```

cc @dani8art @joancafom - I've also reproduced this with the 0.1.8 chart (coming with #3036 )

**Comment by marcosbc** [comment]
Hi, we're looking into the issue with the e-mail. We could not reproduce it in the container image with a docker-compose so it is related to the chart deployment.

As for the second error, you should be running the following command instead:

    bundle exec rake admin:create

We'll let you know once we find any related information on the warning.

**Comment by LucaPrete** [comment]
Marcos, thanks for the feedback.

Could it be that this is related to the parameter "DISCOURSE_SKIP_INSTALL"
set to yes in the helm-chart?

-Luca


Il giorno mer 22 lug 2020 alle ore 19:35 Marcos Bjoerkelund <
notifications@github.com> ha scritto:

**Comment by LucaPrete** [comment]
You can see btw the configmap and related default values in these two files:

https://github.com/bitnami/charts/blob/master/bitnami/discourse/templates/configmaps.yaml
https://github.com/bitnami/charts/blob/master/bitnami/discourse/values.yaml

Il giorno mer 22 lug 2020 alle ore 21:01 Luca Prete <preteluca@gmail.com>
ha scritto:

**Comment by marcosbc** [comment]
I see. Yes, that is certainly the issue here if you enabled that option. `DISCOURSE_SKIP_INSTALL` is meant for existing Discourse databases, or new installations meant to be fully configured by users. With that option, the wizard won't be passed and no site settings changes will be performed (Admin e-mail, site name, logos...).

**Comment by marcosbc** [comment]
Note that, since the configuration file is not persisted by default, it will still be configured via the env vars. However, those environment variable will not affect settings that Discourse store in the database, when `DISCOURSE_SKIP_INSTALL` is enabled.

**Comment by LucaPrete** [comment]
Marcos, FYI I've also submitted this
https://github.com/bitnami/charts/pull/3200.

-Luca

Il giorno mer 22 lug 2020 alle ore 23:55 Marcos Bjoerkelund <
notifications@github.com> ha scritto:

**Comment by LucaPrete** [comment]
Marcos, last but not least, I'm trying the command you've proposed (bundle
exec rake admin:create)

From what directory should I execute it from?

When I try to execute it from /opt/bitnami/discourse I get:

```
discourse-674554cfb4-7nltd:/opt/bitnami/discourse# bundle exec rake
admin:create
rake aborted!
LoadError: cannot load such file -- rb-inotify
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in
`require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in
`block in require_with_bootsnap_lfi'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in
`register'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in
`require_with_bootsnap_lfi'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in
`rescue in require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in
`require'
/opt/bitnami/discourse/config/application.rb:65:in `<top (required)>'
/opt/bitnami/discourse/Rakefile:7:in `require'
/opt/bitnami/discourse/Rakefile:7:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in
`<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan:

(See full trace by running task with --trace)
```

-Luca

Il giorno gio 23 lug 2020 alle ore 14:00 Luca Prete <preteluca@gmail.com>
ha scritto:

**Comment by marcosbc** [comment]
That is most likely because `rb-inotify` is listed as a development gem, and CLI commands are executed by default with `RAILS_ENV=development`.

To workaround it:

```console
$ export RAILS_ENV=production
$ bundle exec rake admin:create
```

**Comment by sonic-sw** [comment]
Email the admin username in the values.yaml is all lower case and min 10 chars long.
