### ISSUE TITLE
Postgres-HA: LoadBalancing not working between the pod

### ISSUE THREAD

**Issue by rg2609** [bitnami/charts#3176]
**Which chart**:
Postgres-HA

**Describe the bug**
I created the helm chart with 2 replicas of pods and trying to test the load performance of the chart. [Sample DB](https://github.com/pthom/northwind_psql) and running following a query from multiple terminals
```
DO $$
DECLARE
    r record;
    c varchar(50);
BEGIN
   FOR counter IN 1..5 LOOP
      RAISE NOTICE 'Counter: %', counter;
      FOR r IN
          SELECT count(*) as c from orders a CROSS JOIN orders as b CROSS JOIN orders as d
      LOOP
          RAISE NOTICE 'Rows Returned: %', r.c;
      END LOOP;
   END LOOP;
END; $$;
```
Above query ran on multiple terminals to check if it managing the load on both the pod, but it is using only one pod for execution. not the other one.
Following images show the result of ```show pool_nodes```
![image](https://user-images.githubusercontent.com/20682661/88052619-20801380-cb78-11ea-9a56-046dd0d798cb.png)
one of the nodes is set ```false``` for ```load_balance_node```

**Comment by juan131** [comment]
Hi @rg2609 

Could you please share the exact command (or values.yaml) you used to install the Postgres HA chart? I mean, every parameter that you set with a different value rather than the default one.

**Comment by rg2609** [comment]
I used the following parameter:
```
service.type: LoadBalancer
postgresql.password
```

**Comment by juan131** [comment]
Hi @rg2609 

As you can see in the `show pool_nodes` command you shared, in the `select_cnt` column both nodes have received the a similar amount of "select" requests. I couldn't find much documentation about what the `load_balancer_node` specifically means, but it doesn't affect the requests being balanced between the nodes.

Please also note that write operations will always be redirected the primary node.

**Comment by rg2609** [comment]
Hi @juan131,
> Please also note that write operations will always be redirected the primary node.
Yes, the write operations will always be redirected to the primary nodes

> SELECT count(*) as c from orders a CROSS JOIN orders as b CROSS JOIN orders as d
But I am not doing write operation, I am executing the ```SELECT``` operation

**Comment by juan131** [comment]
Hi @rg2609 

> But I am not doing write operation, I am executing the SELECT operation

Correct, as you can see 535 of these "select" operations were managed by the **node 0**, while 542 of them were managed by the **node 1**. Please check the `select_cnt` column obtained in the `show pool_nodes` command.
