### ISSUE TITLE
postgres pgpool and  slaves/replicas are not deployed during postgres-ha helm chart

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#3182]
**Which chart**:
postgresql-ha helm chart  and version : 3.4.6

**Describe the bug**

 postgres pgpool and  slaves/replicas are not deployed during postgres-ha helm chart deployment . Detailed steps are given below.

**To Reproduce**

**Step 1** : git clone https://github.com/bitnami/charts.git

**Step 2** : cd charts/bitnami/postgresql-ha/

**Step 3** : Updated following properties in "values-production.yaml" 

	volumePermissions:
  	  enabled: true
	metrics:
  	  enabled: false
	postgresql:
	  replicaCount: 3

**Step 4** : Deploy the postgres-ha helm chart using below command.

[root@masternode1 postgresql-ha]# helm install --name postgres-ha bitnami/postgresql -f values-production.yaml --set postgresqlPassword=AmHbj5KKhvDLnay --set postgresql.repmgrPassword=password
NAME:   postgres-ha
LAST DEPLOYED: Tue Jul 21 23:17:03 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/NetworkPolicy
NAME                    AGE
postgres-ha-postgresql  0s

==> v1/Pod(related)
NAME                      AGE
postgres-ha-postgresql-0  0s

==> v1/Secret
NAME                    AGE
postgres-ha-postgresql  0s

==> v1/Service
NAME                             AGE
postgres-ha-postgresql           0s
postgres-ha-postgresql-headless  0s

==> v1/StatefulSet
NAME                    AGE
postgres-ha-postgresql  0s

NOTES:
** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS name from within your cluster:

    postgres-ha-postgresql.default.svc.cluster.local - Read/Write connection

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgres-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run postgres-ha-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.8.0-debian-10-r33 --env="PGPASSWORD=$POSTGRES_PASSWORD"
   --labels="postgres-ha-postgresql-client=true" --command -- psql --host postgres-ha-postgresql -U postgres -d postgres -p 5432

Note: Since NetworkPolicy is enabled, only pods with label postgres-ha-postgresql-client=true" will be able to connect to this PostgreSQL cluster.

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/postgres-ha-postgresql 5432:5432 &
    PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432

[root@masternode1 postgresql-ha]#

**Step 5** : Please look at the output of kubectl get pods command,pgpool,replicas/slaves are not deployed.

[root@masternode1 postgresql-ha]# kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
postgres-ha-postgresql-0   1/1     Running   0          22s

**Step 6 :** 

[root@masternode1 postgresql-ha]# kubectl get pvc
NAME                            STATUS   VOLUME                                        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-postgres-ha-postgresql-0   Bound    data-postgres-ha-postgresql-ha-postgresql-0   8Gi        RWO                           26s

**Expected behavior**

            postgres-ha should have deployed pgpool ,master and replicas/slaves.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

[root@masternode1 postgresql-ha]# **helm version**
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
[root@masternode1 postgresql-ha]#

- Output of `kubectl version`:

[root@masternode1 postgresql-ha]# **kubectl version**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

Please let me know if you need any additional information.

**Comment by rafariossaa** [comment]
Hi,
  As commented in #2987 , we are currently running our CI/CD to make a new release, I think it will also fix this.
  I will let you know when it is out, so you can check.

**Comment by parvaths1118** [comment]
Thanks @rafariossaa ,please let me know once release is done.

**Comment by parvaths1118** [comment]
@rafariossaa ,Please can you let me know if the release is done and i can take the  latest helm chart?

**Comment by parvaths1118** [comment]
@rafariossaa Please can you let me know if the release is done already ? I have downloaded the latest helm chart but we are still having the same issues.

Should i use any specific version of containers for deployment of postgres-ha?

**Comment by rafariossaa** [comment]
Hi,
   We have just released a new version of the chart. Could you try version 3.4.9 ?

**Comment by parvaths1118** [comment]
Thank you @rafariossaa ,with the latest help chart,All pods are deployed.Thank you for the release.

**Comment by rafariossaa** [comment]
Hi,
  Your are welcome.
  I am glad that this is working well for you now.
