### ISSUE TITLE
[rabbitmq] management.load_definitions usage

### ISSUE THREAD

**Issue by nodesocket** [bitnami/charts#3191]
**Which chart**:
RabbitMQ

**Describe the bug**
When using loadDefinitions from an existing secret:

```
    loadDefinition:
      enabled: true
      secretName: rabbitmq-load-definition
```

Is:

```
extraConfiguration: |-
  management.load_definitions = /app/load_definition.json
```

Required? I don't understand the relationship of the `management.load_definitions` file path here. The load definitions exist in a secret as raw JSON, where is `/app/load_definition.json` coming from?

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
  Yes, it is that way.
  You can check that the secret is added as a volume in line 300 and then mounted on /app in line 265 of `templates/statefulset.yaml`.

**Comment by nodesocket** [comment]
@rafariossaa so `management.load_definitions` path must be `/app/load_definition.json`. Will changing it to:

```
management.load_definitions = /opt/bitnami/rabbitmq/load_definition.json
```

Work as well?

**Comment by rafariossaa** [comment]
Hi,
  No, it won't work, the secret is mounted on `/app/load_definition.json`. You can see a example [here](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#user-content-load-definitions).

**Comment by nodesocket** [comment]
@rafariossaa ok thanks. I just updated to `/app/load_definition.json`. Just curious is using `/app` a standard convention of mounting directories in Kubernetes?

**Comment by andresbono** [comment]
Hi @nodesocket, it is now working as expected, right?

The `/app` mount directory is not necessarily specific to Kubernetes, it's more about containers, that tend to mount volumes in the root directory.

**Comment by nodesocket** [comment]
> Hi @nodesocket, it is now working as expected, right?
> 
> The `/app` mount directory is not necessarily specific to Kubernetes, it's more about containers, that tend to mount volumes in the root directory.

Thanks, it should be. Have not fully tested yet. Thanks for all the help.

**Comment by nodesocket** [comment]
@AndreaBeggiato sorry to open this back up, but I just discovered if I specify a custom `load_definition.json` then the default user specified in the Helm values `rabbitmq.username` and `rabbitmq.existingPasswordSecret` are not created.

How can I keep the default behavior of having the Chart setup the default user, but then run a custom `load_definition.json`?

Essentially only looking to add the following `load_defintion.json`

```
    {
      "permissions": [
        {
          "configure": ".*",
          "read": ".*",
          "user": "mycustomuser",
          "vhost": "mittimus",
          "write": ".*"
        }
      ],
      "vhosts": [
        {
          "limits": [],
          "metadata": {
            "description": "",
            "tags": []
          },
          "name": "mittimus"
        }
      ]
    }
```
