### ISSUE TITLE
[bitnami/discourse] DISCOURSE_SKIP_INSTALL should be set to no if .Values.discourse.skipInstall is nil or false

### ISSUE THREAD

**Issue by LucaPrete** [bitnami/charts#3199]
Related to discourse 0.1.7

In https://github.com/bitnami/charts/blob/master/bitnami/discourse/templates/configmaps.yaml `DISCOURSE_SKIP_INSTALL` is set to `yes` if `.Values.discourse.skipInstall` is `true`, but it's not set to `no` if `.Values.discourse.skipInstall` is set to `false`. We need to add an else over there...

I'll send a PR

cc @joancafom @dani8art @marcosbc

**Comment by andresbono** [comment]
Hi @LucaPrete, thanks for opening this issue!

Is it really needed? Did you find issues with it? Note that the default value is set to no:

https://github.com/bitnami/bitnami-docker-discourse/blob/8333dae9f89cea1b5acccdd94dac52c9c063f75b/2/debian-10/Dockerfile#L37
```Dockerfile
    DISCOURSE_SKIP_INSTALL="no" \
```

---

An alternative to the `if / else` would be to use the ternary operator:

```
DISCOURSE_SKIP_INSTALL: {{ ternary "yes" "no" .Values.discourse.skipInstall | quote }}
```

**Comment by LucaPrete** [comment]
Ahhh...I haven't seen the Dockerfile. You're right.

Anyway, I'd propose to add it anyway for clarity and completeness.

-Luca

Il giorno ven 24 lug 2020 alle ore 16:09 Andrés Bono <
notifications@github.com> ha scritto:

**Comment by andresbono** [comment]
Yeah, that's fine! Please open a PR and we will be glad to review it!

**Comment by LucaPrete** [comment]
Hello guys. We can close it, as it's been done through
https://github.com/bitnami/charts/pull/3200

-Luca

Il giorno mer 12 ago 2020 alle ore 09:28 stale[bot] <
notifications@github.com> ha scritto:

**Comment by marcosbc** [comment]
Thanks! Closing this.
