### ISSUE TITLE
[bitnami/redis] After failover+recover, there will be two masters (with simple reproducible experiments)

### ISSUE THREAD

**Issue by fzyzcjy** [bitnami/charts#3202]
**Which chart**:
redis:latest

**Describe the bug**

**NOTE:** I can try my best to help fix the issue.

1. Say we use Bitnami helm chart to set up 1 Redis master (say, redis A) and 1 or 2 slave (say, redis B and C) (and 3 sentinels).
2. Then, let the master pod be dead (e.g. in redis-cli run `DEBUG SLEEP 100`). The `redis sentinel` should elect one slave to become the new master. (More details: redis B is new master, redis A is dead.)
3. Next, k8s StatefulSet notices the dead master pod. Thus it re-creates a new master pod (say redis A').
4. Now comes the problem. When re-creating the new master pod, all the configs are *master* configs instead of *slave* ones (e.g. there will be no `slaveof`). Thus the new master pod will behave like a master. However, the sentinels have already elect the slave-B to become the master. Thus there are two masters (redis A' and redis B) now! Redis will become quite unhappy :(

P.S. Thanks for the chart, and I learn a lot from it!

**To Reproduce**
See above :)

**Expected behavior**
See above :)

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
latest
```

- Output of `kubectl version`:

```
latest
```

**Additional context**
N/A

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I was unable to reproduce the issue. I launched the cluster, scaled the master to 0, then rescaled it to 1 and could see that the original master pod is now slave of another pod

```
127.0.0.1:6379> info replication
# Replication
role:slave
master_host:172.17.0.10
master_port:6379
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0

---

redo-redis-slave-0                         2/2     Running     3          22m     172.17.0.10   minikube   <none>           <none>
```

However, it is true that the pod naming is incorrect after that. We want to change this so instead of master-slave pods we have simply redis-0, redis-1, redis-2 pods.

**Comment by fzyzcjy** [comment]
Yes later I find that redis is smart enough to solve that issue. Thus I closed the issue after several hours. Thanks for reply!

**Comment by fzyzcjy** [comment]
Hi I do successfully reproduced the problem now. Steps:

1. Install the helm chart. Now we will see master pod (pod A) and slave pod (pod B).
2. **Kill** (i.e. delete) the master pod (call it pod A). Kubernetes will auto recreate another master pod (call it pod A2).
3. Verify that pod A2 has **different ip** compared with pod A. (This should be the usual case since k8s never guarantee static ip)
4. Then **both A2 and B think they are masters!** (Verify by, for example: run `INFO replication` and see the roles. Or `SET k v` on both instances, and observe that they do not replicate. Or look at `SENTINEL REPLICAS mymaster`, and see sentinels do not even know the existence of pod A2.) 

Guess of why this happens:

When pod A2 is created, it is configured as a master by the bitnami startup scripts / pod spec. Moreover, it has a brand new ip. Thus, it is as if **this pod A2 is a separate unrelated brand-new redis instance** which has completely **no** relationship with the original pod A/B/sentinels. Thus, it is not recognized, and of course it is not a slave of pod B.

Thanks

**Comment by javsalgar** [comment]
cc @rafariossaa

**Comment by rafariossaa** [comment]
Hi,
  Thanks for providing information on how to reproduce the issue.
  I am adding this information to our current internal task in this issue.
  We will come back as soon as we have news.

**Comment by fzyzcjy** [comment]
@rafariossaa Thanks for the reply!

**Comment by fzyzcjy** [comment]
By the way there may exist another issue: The persistent volume.

Notice that bitnami uses **emptyDir** to store config for both redis node and redis sentinel. However, [sentinel documentation](https://redis.io/topics/sentinel) says:

> This file will be used by the system in order to save the current state that will be reloaded in case of restarts

Thus, IMHO we should use a `PersistentVolume` instead of `emptyDir` to save the conf file.

As for whether `emptyDir` or `PersistentVolume` for the main node I am not sure. But you know, `emptyDir` means, when the pod/container is restarted on the **same** node, data are kept; but when on different node, data get lost. So this will lead to **different** behavior when the redis pod is scheduled onto the same or different node.

**Comment by rafariossaa** [comment]
Hi,
  That is a good point. Thanks ! 
  I am adding this to our internal task to take it into account.

**Comment by rafariossaa** [comment]
Hi,
  A new version of the chart was released.
  Could you give it a try and check if this fixed the issue for you ?

**Comment by fzyzcjy** [comment]
@rafariossaa Hi I have created my own helm chart two weeks ago (since I did not know when will the bugfix be released, and I needed the bug to be fixed immediately). The code looks good to me, but I do not have a cluster to test on hand.

**Comment by andresbono** [comment]
Thanks for letting us know, @fzyzcjy!
