### ISSUE TITLE
[bitnami/grafana] custom.ini file is not loaded by grafana-server

### ISSUE THREAD

**Issue by xakraz** [bitnami/charts#3204]
**Which chart**:
The name (and version) of the affected chart

```
Chart: grafana-3.1.2
App version: 7.1.0      

```

**Describe the bug**

Grafana server does not use the `custom.ini` file

**To Reproduce**
1. Create a `configMap` or `Secret` as stated in the doc to create the `custom.ini` file: https://github.com/bitnami/charts/blob/master/bitnami/grafana/README.md#using-custom-configuration
2. Add the needed values for the release
  * `config.useCustomIniFile=true`
  * `config.customIniSecret=your_secret_name`
3. Release

The file is populated as expected :tada: 
```
kubectl exec -it -n prometheus grafana-68dbc7fccc-tl4hs /bin/bash
$ cat config/custom.ini
```

But in the log we can only see : 
```
grafana-58dfc5745c-226vv grafana t=2020-07-23T13:24:50+0000 lvl=info msg="Config loaded from" logger=settings file=/opt/bitnami/grafana/conf/defaults.ini
grafana-58dfc5745c-226vv grafana t=2020-07-23T13:24:50+0000 lvl=info msg="Config loaded from" logger=settings file=/opt/bitnami/grafana/conf/grafana.ini
```

And no mention to `custom.ini`

**Expected behavior**

According to the doc:
- https://grafana.com/docs/grafana/latest/administration/configuration/

>  Depending on your OS, make all configuration changes in either `custom.ini` or `grafana.ini`.

Suggestions:
* Either remove the `custom.ini` support if everything is supposed to go in `grafana.ini`
* Either override the container command to specify the `custom.ini` file thanks to `--config` flag

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by marcosbc** [comment]
Hi @xakraz, you are right, mentions of "custom.ini" should be removed.

Note that it should be possible to change this functionality by overriding the value of the `GF_CUSTOM_PATHS` environment variable, i.e. by setting it to custom.ini. See: [chart](https://github.com/bitnami/charts/blob/master/bitnami/grafana/templates/configmap.yaml#L25) and [run.sh](https://github.com/bitnami/bitnami-docker-grafana/blob/master/7/debian-10/rootfs/run.sh#L3).

Do you want to contribute the required changes to the Helm chart?

**Comment by xakraz** [comment]
Hi @marcosbc ,

AFAIAC, I think the mentions and management of `custom.ini` should be simply removed. I is simpler that way :smile:

**Comment by dsrao2101** [comment]
Hi
I want to make changes to grafana.ini . How can I achieve this?
