### ISSUE TITLE
[bitnami/redis] The so-called "master" is slave and "slave" is master after a failover && A proposal to merge the two StatefulSets 

### ISSUE THREAD

**Issue by fzyzcjy** [bitnami/charts#3206]
**Which chart**:
redis:latest

**Describe the bug**
After a failover (e.g. [in the tutorial](https://docs.bitnami.com/tutorials/deploy-redis-sentinel-production-cluster/)), the `redis-master-0` pod (and the `redis-master` StatefulSet) will actually become a slave. At the same time, the `redis-slave-0` (or 1 or 2) will become a master. Of course, the other `redis-slave-1/2` will still be slave.

The problem is: The name is "master", but actually it is acting as a slave! The name is "slave", but actually one pod is acting as master and another two are acting as a slave... This may be misleading and confusing...

**My proposal**: Can we merge the two StatefulSets into one? In that case, the problem above will disappear. In addition, the `yaml` files will also be shorter, because currently the are lots of duplications between the master and slave setup.

p.s. Thanks very much for the charts, and I have learnt a lot from them!

**To Reproduce**
1. Start master + slave
2. failover
3. then see it

**Expected behavior**
See above

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
latest
```

- Output of `kubectl version`:

```
latest
```

**Additional context**
N/A

**Comment by andresbono** [comment]
Hi @fzyzcjy, that's a known issue. Thanks for suggesting alternatives! As said in https://github.com/bitnami/charts/issues/3202#issuecomment-663415796, we want to improve this behavior. What do you think about this proposed solution? Note that two statefulsets might be necessary because the initial configuration is different.

> it is true that the pod naming is incorrect after that. We want to change this so instead of master-slave pods we have simply redis-0, redis-1, redis-2 pods.

**Comment by fzyzcjy** [comment]
Oh actually I have solved this by creating a customized version based on Bitnami. Let me upload it and link it here, maybe it will be helpful :)

My idea: Yes just to let `statefulset-pod-0` be the initial master. About the different config, actually the [official k8s tutorial](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#statefulset) talks about this and uses a trick to detect the index:

```
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate mysql server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          echo [mysqld] > /mnt/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/master.cnf /mnt/conf.d/
          else
            cp /mnt/config-map/slave.cnf /mnt/conf.d/
          fi
```

**Comment by fzyzcjy** [comment]
My charts are here: https://github.com/fzyzcjy/redis-sentinel-kubernetes

**Comment by andresbono** [comment]
Nice! Thanks for letting us know. We will close this issue then as you are using your own one. But stay tuned for the improvements that we do in `bitnami/redis`!

**Comment by fzyzcjy** [comment]
You are welcome! :)
