### ISSUE TITLE
[Thanos] Allow extraFlags for boolean flags and multiple times the same flag

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#3218]
**Which chart**:
Thanos - 1.4.1

**Describe the bug**
Some of the flags that can be set on Thanos are boolean flags 
`--query.auto-downsampling`, `--query.partial-response`
or they can be repeated multiple times `(repeatable)`
https://thanos.io/components/query.md/#the-same-output-will-be-present-for-this-example-with-multiple-replica-labels

**To Reproduce**
```
$ cat > thanos.yaml <<PROPS
querier:
  extraFlags:
    query.partial-response: ""
    query.replica-label: "cluster"
    query.replica-label: "environment"
PROPS
```
```
$ helm dep build bitnami/thanos
$ helm template -f thanos.yaml bitnami/thanos 
```

**Expected behavior**
Boolean flags are rendered correctly but it's very ugly.
For the `query.replica-label` flags only 2 are rendered the one defined through `querier.replicaLabel` and the last one on the `querier.extraFlag` map

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Only one `replicaLabel` is not good enough since we aggregate metrics from different clusters and environments into a single S3 bucket

**Comment by marcosbc** [comment]
Hi @carlosjgp, you're right. It does not feel very natural, and multiflags are not supported. I've created #3245 to fix this issue.
