### ISSUE TITLE
[bitnami/rabbitmq] Ingress is not working as defined

### ISSUE THREAD

**Issue by rnkhouse** [bitnami/charts#3224]
**Which chart**:
Rabbitmq

**Describe the bug**
I am trying to setup ingress hostname but, it;s not working and showing as default name: `rabbitmq.local`. Using below values:

    ingress:
      enabled: true
      hostName: rabbitmq.example.com
      path: /
      tls: true
      existingSecret: tls-name
      annotations:
        kubernetes.io/ingress.class: nginx-internal

**To Reproduce**
Create helm chart using above helm values. I am using AKS cluster

**Expected behavior**
It should config valid ingress name.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, can you execute your `helm install` with the `--dry-run` flag and also filtering the word `host`? In my case, everything is set using the new hostname:
```console
$ helm install rabbitmq --dry-run bitnami/rabbitmq -f values.yaml | grep 'host'
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
              value: hostname
    - host: newhost.com
1. Get the RabbitMQ Management URL and associate its hostname to your cluster external IP:
   echo "RabbitMQ Management: http://newhost.com/"
   echo "$CLUSTER_IP  newhost.com" | sudo tee -a /etc/hosts
```
are you able to obtain the same result?

**Comment by rnkhouse** [comment]
Hi, thanks for your reply. I found that it was type in the hostname. I changed it from `hostName` to `hostname`.
