### ISSUE TITLE
[bitnami/wordpress] Correct way to upgrade an installation

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [bitnami/charts#3228]
**Which chart**:
wordpress:9.3.22

**Describe the bug**
Documentation in https://docs.bitnami.com/kubernetes/get-started-aks/#keep-your-wordpress-installation-up-to-date not in line with normal k8s procedures. The docs at the link says that we can use the WP dashboard to upgrade the installation but if a pod goes down after the upgrade, it will start up the older version right? Is there something going on to mitigate this? What is the actual recommended practice to upgrade a wordpress deployment when installing via a Helm chart.

**Comment by marcosbc** [comment]
Hi @SayakMukhopadhyay, thanks for reporting! You're totally right, the documentation is wrong as the only persisted files across WP container installs are `wp-content` and `wp-config.php`.

What we usually recommend is to use [tools such as VaultPress or All-in-One WP Migration](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#to-900).

However, for more simple upgrades that don't involve chart changes, you'd only need to change the container tag/version used in your deployment. I.e. `5.4.0-debian-10-r1 -> 5.4.2-debian-10-r36` (would upgrade from 5.4.0 to 5.4.2).

**Comment by marcosbc** [comment]
FYI: I've created an internal task for fixing the documentation, it should be fixed in a week or two.

**Comment by marcosbc** [comment]
This was fixed, so I'm closing this issue.

**Comment by ahmadidev** [comment]
This document is still pointing to the wrong upgrade procedure: https://docs.bitnami.com/aws/apps/wordpress/administration/upgrade/

**Comment by carrodher** [comment]
Please note that documentation is about the AWS cloud image, not the Helm chart
