### ISSUE TITLE
Q: Test update from Rabbitmq version 5.7.x to version 5.8.x.

### ISSUE THREAD

**Issue by torsten-liermann** [bitnami/charts#3230]
Hi,

I would like to test an update from Rabbitmq version 5.7.x to version 5.8.x and use the current helm chart and change the image version from 3.8.5-debian-10-r38 into 3.7.19 (latest bitnami version of 5.7.x) . Something must have changed in the configuration so that RABBITMQ_USER / RABBITMQ_PASSWORD do not work. I don't quite understand it, because bitnami Docker Image 5.7.19 works without helm.

Is there a Helm3 chart for the last 5.7.x version?

Thx

In the meantime I found an older version of the helm chart with rabbitmq 3.7.18-debian-9-r. But the chart has already been changed so that a helm upgrade is no longer possible. Disappointing.

**Comment by torsten-liermann** [comment]
In the meantime I found an older version of the helm chart with rabbitmq 3.7.18-debian-9-r. But the chart has already been changed so that a helm upgrade is no longer possible. Disappointing.

**Comment by andresbono** [comment]
Hi @torsten-liermann, the chart versions that you mention are using the same version of the container image: `3.7.15`.

```
$ helm search repo bitnami/rabbitmq --versions --version '^5.7'
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/rabbitmq	5.9.1        	3.7.15     	Open source message broker software that implem...
bitnami/rabbitmq	5.9.0        	3.7.15     	Open source message broker software that implem...
bitnami/rabbitmq	5.8.2        	3.7.15     	Open source message broker software that implem...
bitnami/rabbitmq	5.8.1        	3.7.15     	Open source message broker software that implem...
bitnami/rabbitmq	5.8.0        	3.7.15     	Open source message broker software that implem...
bitnami/rabbitmq	5.7.0        	3.7.15     	Open source message broker software that implem...
```

You can find the full list by executing `helm search repo bitnami/rabbitmq --versions`. I hope you find this useful.
