### ISSUE TITLE
[bitnami/prometheus-operator] Relation to stable/prometheus-operator

### ISSUE THREAD

**Issue by Annegies** [bitnami/charts#3242]
Hi, 

We've been using the helm chart from stable for a while now. I was wondering if this chart was a separate one, or if you're going to deprecate the stable one and continue developing in the bitnami charts repository? 

And if you're deprecating the chart in the stable repository, how come the versioning is completely different?

**Comment by javsalgar** [comment]
Hi,

Please note that we're not maintainers of the stable/prometheus-operator chart. The bitnami/prometheus-operator is a different chart and that explains the different versioning.  I imagine that the team behind it will have plans about what to do when the stable repository is deprecated. I would advise you to ask them directly. 

If you want to give our chart a try, don't hesitate to let us know any feedback :)

**Comment by Annegies** [comment]
Alright, thanks for the info! We'll take a look at your chart!
