### ISSUE TITLE
[bitnami/grafana] custom grafana-admin secret and helper command

### ISSUE THREAD

**Issue by notdodo** [bitnami/charts#3247]
**Which chart**:
bitnami/grafana

**Describe the bug**
When using the flag `-admin.existingSecret=grafana-secret` the pod is searching for the key `password` while the default secret creates the key `GF_SECURITY_ADMIN_PASSWORD`.

**To Reproduce**

```bash
kubectl delete secrets -n monitoring grafana-admin
kubectl apply -f grafana-secret.yaml
helm install --namespace=monitoring grafana bitnami/grafana --set=admin.existingSecret=grafana-secret --wait
```

**Expected behavior**
The secrets should be using the same key and/or when using the custom secret the output of the Helm command should print:

```bash
echo "User: admin"
echo "Password: $(kubectl get secret grafana-admin --namespace monitoring -o jsonpath="{.data.password}" | base64 --decode)"
```
not:

```bash
echo "User: admin"
echo "Password: $(kubectl get secret grafana-admin --namespace monitoring -o jsonpath="{.data.GF_SECURITY_ADMIN_PASSWORD}" | base64 --decode)"
```

**Comment by marcosbc** [comment]
Thanks for reporting! You're right, the current instructions are wrong and have pushed a fix.

In any case, the expected behavior would be to get the secret "grafana-secret", not "grafana-admin". Note we've taken that into account in the PR.
