### ISSUE TITLE
[bitnami/mariadb-galera] how to choose the best po to safe_to_bootstrap when all the pod died in an extreme scenario?

### ISSUE THREAD

**Issue by lcfang** [bitnami/charts#3248]
**Which chart**:
mariadb-galera, 4.0.0 

**Describe the bug**
[https://github.com/bitnami/charts/pull/3214#issuecomment-664168270](https://github.com/bitnami/charts/pull/3214#issuecomment-664168270)

**To Reproduce**
1. Deploy a new mariadb-galera cluster with the default of 3 nodes and podAntiAffinity in a k8s with 3masters( and the masters are also slave nodes), and I use extra nfs storage.
2. shutdown all the nodes of k8s
3. see the file grastate.dat, some times, all the seqno still be -1, some times, the seqno is positive integer and -1.

**Expected behavior**
in this scenario,I am not sure which pod I should choose to set safe_to_bootstrap=1 manully, Or if there some auto ways to select a oldest one?
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
# helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by lcfang** [comment]
@andresbono More info: The problem described above with the pr [https://github.com/bitnami/charts/pull/3214](https://github.com/bitnami/charts/pull/3214)  cherry-picked in my chart. 
I observed that if the nodes of k8s are shutdown one by one, all the seqno is  positive integer, and safe_to_bootstrap  in grastate.dat of the last  one being shutdown will be set to 1 automatically.

**Comment by carrodher** [comment]
Hi, thanks for reporting we are going to take a look at the issue to provide the proper answer

**Comment by carrodher** [comment]
Hi, I think it is difficult to provide a solution to the problem you're describing, in theory, you need to locate the last node and try to launch the cluster from this one.

But if all the nodes were killed in an abrupt way, it is not easy to know if one of the nodes is going to have `seqno > 0` nor `safe_to_bootstrap = 1`. If you are able to determine what was the last node, you can use this one, or you can try to check one by one, randomly, or something like that

**Comment by zacharystokes** [comment]
This is not in kubernetes context, but rather on bare metal.  **But** this exact scenario happened to me this last weekend when our on-prem datacenter abruptly went dark.  Even in a three-node Galera cluster, only one of the nodes would accept safe_to_bootstrap = 1 and start, allowing for other nodes to start and wsrep to sync across the cluster.

**Comment by lcfang** [comment]
@carrodher Thanks for your reply. I also think its difficult to know which was the last one. My policy is that setting safe_to_bootstrap of mariadb-galera-0 to 1 if all the seqno=-1, or setting the safe_to_bootstrap=1 for the mariadb-galera-x whose seqno is max when some seqno are positive integer and some are -1. Do you think if this is a good way?

> This is not in kubernetes context, but rather on bare metal

@zacharystokes  the node of k8s can be bare metal or vm, I use mariadb-galra-cluster in k8s with vm as node, so I think this exact scenario also may happen in k8s.

**Comment by carrodher** [comment]
Yes, I think this kind of solution is the best approach to try to minimize the effect of those undesired cases although maybe there are some corner cases it's probably a good method.

**Comment by lcfang** [comment]
close
