### ISSUE TITLE
[bitnami/wordpress] Tutorial to use helm to push wordpress production environment with custom WP containers won't work

### ISSUE THREAD

**Issue by theclue** [bitnami/charts#3253]
**Which chart**:
Wordpress

**Describe the bug**
Trying to following the [official tutorial](https://docs.bitnami.com/tutorials/deploy-custom-wordpress-production-helm/) on pushing a production-ready Wordpress stack using helm doesn't seems to work. Maybe it is outdated?

In particular, I'm trying to deploy a custom-build wordpress image as explained [here](https://docs.bitnami.com/tutorials/deploy-locally-custom-wordpress/). In dev environment (docker-composer) it works perfectly with a persistent volume for the wp-content

I'm going to describe the inconsistencies here:

**Error in symlinking wp-content**

The tutorial says to add the download-extra.sh files in Dockerfile, just after `COPY rootfs /` but this will make the `app-entrypoint.sh`  to fail as wp-content will exist already when the application logic will try to create/symlink it.

**Password: su: Authentication failure**

When delaying the call to download-extra.sh _inside_ the app-entrypoint.sh itself, I get the error above.

For your references, here's the `download-extra.sh` file:

```
curl -o /tmp/all-in-one-wp-security-and-firewall.zip https://downloads.wordpress.org/plugin/all-in-one-wp-security-and-firewall.zip
curl -o /tmp/all-in-one-wp-migration.7.25.zip https://downloads.wordpress.org/plugin/all-in-one-wp-migration.7.25.zip

unzip /tmp/all-in-one-wp-security-and-firewall.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip /tmp/all-in-one-wp-migration.7.25.zip -d /opt/bitnami/wordpress/wp-content/plugins
```

and this is the `app-entrypoint.sh` file:

```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "httpd" ]]; then
    . /apache-init.sh
    . /wordpress-init.sh
    nami_initialize apache php mysql-client wordpress
	
	su daemon -s /bin/bash -c '/download-extra.sh'

	su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-wp-security-and-firewall'
	su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-wp-migration'

	info "Starting wordpress... "
    . /post-init.sh
fi

exec tini -- "$@"

```

**Comment by andresbono** [comment]
Thanks for reporting these issues, @theclue. We will review and update the tutorial addressing any required changes.

**Comment by theclue** [comment]
Fyi I've encountered the same errors also using base wordpress image as a starting point, ie this simple (yet effective) Dockerfile:

```
FROM bitnami/wordpress:5.4.2

USER root

COPY src/plugins /opt/bitnami/wordpress/wp-content/plugins
COPY src/themes /opt/bitnami/wordpress/wp-content/themes

COPY download-extra.sh /download-extra.sh
RUN bash download-extra.sh
```

I've an error during the init stage that wp-content cannoy be symlinked since it already exists.

**Comment by andresbono** [comment]
Hi @theclue, we have been reviewing the documentation and all the steps seem to work as expected for us, we could't reproduce your issues. After checking again the snippets from your first comment, it seems you are executing the `download-extra.sh` in the `app-entrypoint.sh`. However, in the [guide](https://docs.bitnami.com/tutorials/deploy-locally-custom-wordpress/), that script is intended to be executed in the Dockerfile.

In the `app-entrypoint.sh` you just need to add these two lines after the `nami_initialize` line:
```
    su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-wp-security-and-firewall'
    su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate all-in-one-wp-migration'
```

Could you please try that way?

**Comment by theclue** [comment]
Hi, 

I've tried both.

In the first case (Dockerfile, following the guide) I've an error about symlinking

Trying to delay the copy AFTER the initialization (in app-entrypoint) I've the second issue reported about permissions

Pls bear in mind that I've no issues when provisioning using docker-composer, but I've when manually building the image for using in kubernetes. I think this is because in the latter I don't have mounted volumes.

You can easily reproduce using my latter Dockerfile, which is much more simple:

```
FROM bitnami/wordpress:5.4.2

USER root

COPY src/plugins /opt/bitnami/wordpress/wp-content/plugins
COPY src/themes /opt/bitnami/wordpress/wp-content/themes

COPY download-extra.sh /download-extra.sh
RUN bash download-extra.sh
```

**Comment by dani8art** [comment]
Hi @theclue you are facing now errors about permissions only? or you still getting errors about symlinks?

**Comment by theclue** [comment]
Hi @dani8art, sorry for the late reply (I was out on vacation with no access to the Internet)

the problem (following the tutorial) is about symlinking. This is because I'm trying to copy my custom plugins + themes content from the Dockerfile.

But when I do so, the deploy of the helm chart will fail, because /opt/bitnami/wordpress/wp-content/ exists already so the init script cannot symlink to it

This probably means that the COPY statements in the Dockerfile are pushing into the wrong path, but which is the right one then?

**Comment by andresbono** [comment]
Hi @theclue, we could finally reproduce the issue.

```
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/wordpress/wp-content' -> '/opt/bitnami/wordpress/wp-content'
```

The key was that the Dockerfile that you were using in https://github.com/bitnami/charts/issues/3253#issuecomment-667191541, was defining the user as `root`. The docker-compose doesn't change the default user of the image, so the container was running as root as well. It didn't fail because of that.

However, in the helm chart, there are securityContext settings that restricts the privileges of the  pods `runAsUser` defaults to `1001`:
https://github.com/bitnami/charts/blob/3910de7325317b752e1c2e46456fbdaa765cb50b/bitnami/wordpress/templates/deployment.yaml#L49-L53

This is the script that we have been using to prepare the environment to build the image:

```bash
mkdir -p src/plugins src/themes

curl https://downloads.wordpress.org/plugin/bbpress.2.6.4.zip -o src/plugins/bbpress.2.6.4.zip
unzip src/plugins/bbpress.2.6.4.zip -d src/plugins
curl https://downloads.wordpress.org/theme/gambit.1.6.5.zip -o src/themes/gambit.1.6.5.zip
unzip src/themes/gambit.1.6.5.zip -d src/themes

cat <<EOF >Dockerfile
FROM bitnami/wordpress:5.4.2

USER root

COPY src/plugins /opt/bitnami/wordpress/wp-content/plugins
COPY src/themes /opt/bitnami/wordpress/wp-content/themes
EOF
```

In order to solve the issue, you have two options:

a) If you want to run the container image as root in the helm chart deployment (not recommended for security reasons), set the `securityContext.fsGroup=0` and `securityContext.runAsUser=0` values.

b) Modify the Dockerfile to adjust the permissions. At the end of your Dockerfile, set `g+w` to the `wp-content` directory and restore the unprivileged user:

```
RUN chmod -R g+w /opt/bitnami/wordpress/wp-content
USER 1001
```

Let us know if this works for you.

Related:

- https://github.com/bitnami/bitnami-docker-wordpress/issues/260
- https://github.com/bitnami/bitnami-docker-wordpress/issues/251

**Comment by theclue** [comment]
Hi @andresbono, tnx for your support.

Your solution almost works when I do the first deploy, but I'm facing some issues in my CI pipeline when doing successive commits which alter the content on the wp-content subtree (ie. updating my custom plugins and themes).

I see that no changes are reflected on the /opt/bitnami/wordpress/wp-content tree. This is because I use a persistent storage I guess.

Thus, I changed strategy with some that should solve the issue and being a bit more versatile for future developments at the same time: copy my custom content from a busybox machine within an InitContainer and not using a custom-made bitnami/wordpress image anymore.

In my values.yml:

```
initContainers:
  - name: init-wp-content
    image: <my private registry>/bitnami-wp-busybox:latest
    command: ['sh', '-c', 'cp -RT /opt/mrm/wordpress/wp-content/ /bitnami/wordpress/wp-content']
    volumeMounts:
    - name: wordpress-data
      mountPath: /bitnami/wordpress
```

Where bitnami-wp-busybox image is built this way:

```
FROM grrywlsn/alpine-coreutils-curl:latest

USER root

COPY src/plugins /opt/mrm/wordpress/wp-content/plugins
COPY src/themes /opt/mrm/wordpress/wp-content/themes

COPY download-extra.sh /download-extra.sh

RUN sh /download-extra.sh

RUN chmod -R g+w /opt/mrm/wordpress/wp-content
```

I've no errors during the deploy, but no content is added. In facts:

```
I have no name!@wordpress-68f6d48c48-vjzhm:/$ ls /opt/bitnami/wordpress/wp-content/plugins
akismet              all-in-one-wp-migration  google-analytics-for-wordpress  index.php  licenses     w3-total-cache         wp-mail-smtp
all-in-one-seo-pack  amp                      hello.php                       jetpack    simple-tags  wp-cloud-mgmt-console
```

any idea?

**Comment by andresbono** [comment]
Hi @theclue, is the init container being executed? Maybe you added it wasn't executed yet.

**Comment by theclue** [comment]
> Hi @theclue, is the init container being executed? Maybe you added it wasn't executed yet.

Yes, it is:

![image](https://user-images.githubusercontent.com/1724406/92403877-aceb9300-f132-11ea-8456-9c4b09639952.png)

I'm really puzzled I must admit...

**Comment by andresbono** [comment]
Hi @theclue, we have been investigating it and it seems there is a missing property (`subPath`) in the volumeMount of the init container. Please try with the following `values.yaml` and let us know if it works:

```yaml
initContainers:
  - name: init-wp-content
    image: <my private registry>/bitnami-wp-busybox:latest
    command: ['sh', '-c', 'cp -RT /opt/mrm/wordpress/wp-content/ /bitnami/wordpress/wp-content']
    volumeMounts:
    - name: wordpress-data
      mountPath: /bitnami/wordpress
      subPath: wordpress
```

**Comment by theclue** [comment]
>       subPath: wordpress

works like a charm!

**Comment by andresbono** [comment]
Great! Thanks for confirming i 🎉
