### ISSUE TITLE
[bitnami/minio] Add schedulerName

### ISSUE THREAD

**Issue by jbagot** [bitnami/charts#3255]
**Which chart**:
bitnami/minio version 3.4.21

**Is your feature request related to a problem? Please describe.**
I need to use a different scheduler, stork, and this chart doesn't allow to change it.

**Describe the solution you'd like**
I want the option to change the scheduler used by the chart.

**Comment by javsalgar** [comment]
Thank you very much for using Bitnami. We will review the PR. Thanks for contributing :)
