### ISSUE TITLE
Fail to attach PVC to pods after installation of Kafka

### ISSUE THREAD

**Issue by devsentient** [bitnami/charts#3269]
**Which chart**:
bitnami Kafka chart

**Describe the bug**
Installation on a Kops cluster completes but the pods remain in `ContainerCreating` status because the PVC fails to attach to the pod.

Logs from the kube-controller-manager:
```
E0729 15:47:29.627876       1 attacher.go:86] Error attaching volume "aws://us-east-1c/vol-0ede9157ef4b7626c" to node "ip-172-20-45-68.ec2.internal": error attaching EBS volume "vol-0ede9157ef4b7626c" │
│  to instance "i-0243673feb8b10624": "InternalError: An internal error has occurred\n\tstatus code: 500, request id: d76412e0-86ae-48ad-934e-ad13556a6231"                                                │
│ I0729 15:47:29.628212       1 actual_state_of_world.go:322] Volume "kubernetes.io/aws-ebs/aws://us-east-1c/vol-0ede9157ef4b7626c" is already added to attachedVolume list to node "ip-172-20-45-68.ec2.i │
│ nternal", update device path ""
```
Error message from the pod description:
```
Warning  FailedAttachVolume  106s                  attachdetach-controller                (combined from similar events): AttachVolume.Attach failed for volume "pvc-a6baeec3-ec86-4701-a58e-7dc46c3d3 │
│ 8c1" : error attaching EBS volume "vol-0effe62963a355a25" to instance "i-0f6aac973169fd4aa": "InternalError: An internal error has occurred\n\tstatus code: 500, request id: cbda5152-73af-4730-88e0-84b │
│ ad2e11f7f" 
```

**Comment by juan131** [comment]
Hi @devsentient 

Could you please share the values that you modified when installing the chart? For instance, if your chart release is named "my-release" and you installed it in the namespace "my-namespace", share the output of running the command below:

```console
$ helm get values my-release -n my-namespace
```

**Comment by devsentient** [comment]
Hi,
I tried both the following commands with the same outcome:
`helm install --generate-name bitnami/kafka --set nodeSelector="kops.k8s.io/instancegroup: nodes2" -n kafka`
and
`helm install --generate-name bitnami/kafka -n kafka`

**Comment by carrodher** [comment]
Can you try removing the existing PV/PVCs related to kafka? You can list them by running
```
kubectl get pvc -n kafka
kubectl get pv -n kafka
```
or in the default namespace if needed (removing the `-n kafka`)
