### ISSUE TITLE
[bitnami/postgresql-ha]Restoring the postgresql full backup not working

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#3273]
**Which chart**:
postgresql-ha helm chart ,3.4.9

**Describe the bug**

we have standard postgresql running in docker then  we are migrating the data that was created from postgres database standard docker container to kubernetes environment using bitnami postgres-ha helm chart.

bitnami postgres-ha helm chart deployed successfully and running fine.

As part of migration we have created the postresql full backup using pg_dumpall command from the standard postgresql running in docker and then trying to import in to kubernetes postgres environment but it is failing. 

Please note that I am able to restore it in to another  standard postgresql container running in docker and  i think the issue is happening only when i try to restore in bitnami postgresql container db.

**To Reproduce**

**Step 1 :**  Create the database backup from the postgres DB running in docker.

**Step 2 :**  Restore following the below command
[root@masternode1 tmp]# gunzip  -c iam_202007291800.sql.gz | psql -h 10.174.4.21 -U postgres
Password for user postgres:
SET
SET
SET
ERROR:  database "iam" does not exist
ERROR:  role "iamdb_readonly" does not exist
ERROR:  role "iamdcosbeta" does not exist
ERROR:  current user cannot be dropped
ERROR:  role "rds_iam" does not exist
ERROR:  role "rds_password" does not exist
ERROR:  role "rds_replication" does not exist
ERROR:  role "rds_superuser" does not exist
ERROR:  role "rdsadmin" does not exist
ERROR:  role "rdsrepladmin" does not exist
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
ERROR:  role "postgres" already exists
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
CREATE ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
ALTER ROLE
GRANT ROLE
GRANT ROLE
GRANT ROLE
GRANT ROLE
GRANT ROLE
CREATE DATABASE
GRANT
REVOKE
GRANT
\connect: ERROR:  unable to read message kind
DETAIL:  kind does not match between master(53) slot[1] (45)
[root@masternode1 tmp]#

**Expected behavior**

postgres backup should be restored successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

[root@masternode1 tmp]# helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
[root@masternode1 tmp]#

- Output of `kubectl version`:

[root@masternode1 tmp]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
[root@masternode1 tmp]#

**Additional context**

**Comment by dani8art** [comment]
Hi @parvaths1118, could you try it using https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#initialize-a-fresh-instance?

Please, take a look at this issue too https://github.com/helm/charts/issues/19898#issuecomment-572967126

**Comment by parvaths1118** [comment]
Hello @dani8art  ,

After the helm chart deployed, here is the status of pods **"pgpool-2 replicas and posgresql-5 replicas"**

[root@masternode1 tmp]# kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
postgres-ha-postgresql-ha-pgpool-6c94d7b7d5-25xjw   1/1     Running   0          47m
postgres-ha-postgresql-ha-pgpool-6c94d7b7d5-d62v5   1/1     Running   0          45m
postgres-ha-postgresql-ha-postgresql-0              2/2     Running   1          40m
postgres-ha-postgresql-ha-postgresql-1              2/2     Running   0          81m
postgres-ha-postgresql-ha-postgresql-2              2/2     Running   1          80m
postgres-ha-postgresql-ha-postgresql-3              2/2     Running   1          79m
postgres-ha-postgresql-ha-postgresql-4              2/2     Running   1          78m
[root@masternode1 tmp]#

Restoring of the database worked fine but I had to reboot the master pod for making it work after helm chart is deployed, if you look at the below output “**postgres-ha-postgresql-ha-postgresql-1”** acts as primary instance currently but **“postgres-ha-postgresql-ha-postgresql-0”** was the primary instance when the helm chart was deployed , after rebooting  **postgres-ha-postgresql-ha-postgresql-0**  pod then  **postgres-ha-postgresql-ha-postgresql-1** has become the primary. I am not sure why reboot of master pod fixed the problem of restoring the database. Please can you explain ? Is there any known issue around this ?

Intially I have rebooted the pgpool pods but that did not help ,restore worked fine only after rebooting the master pod.When I say rebooting the pod means “I have deleted the pod and replica set recreated the same pod again”

postgres=# show pool_nodes;
node_id |                                                    hostname                                                    | port | status | lb_weight |  role
   | select_cnt | load_balance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------------------------------+------+--------+-----------+------
---+------------+-------------------+-------------------+-------------------+------------------------+---------------------
0       | postgres-ha-postgresql-ha-postgresql-0.postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | stand
by | 13         | false             | 14516358205       |                   |                        | 2020-08-05 10:15:09
1       | postgres-ha-postgresql-ha-postgresql-1.postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | prima
ry | 463        | true              | 0                 |                   |                        | 2020-08-05 10:14:53
2       | postgres-ha-postgresql-ha-postgresql-2.postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | stand
by | 11         | false             | 14482803773       |                   |                        | 2020-08-05 10:15:39
3       | postgres-ha-postgresql-ha-postgresql-3.postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | stand
by | 10         | false             | 14432471029       |                   |                        | 2020-08-05 10:15:49
4       | postgres-ha-postgresql-ha-postgresql-4.postgres-ha-postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | stand
by | 13         | false             | 14432471029       |                   |                        | 2020-08-05 10:15:49
(5 rows)

Below is the command used for restoring the database:

gunzip  -c iam_202007291800.sql.gz | psql -h 10.174.4.21 -U postgres -p 5432

**Comment by dani8art** [comment]
Hi @parvaths1118,

The state of the cluster in postgresql repmgr is store in a database so when you try to restore it, the state of the cluster will be also restored. At the same time, our containers and helm chart will try to set the cluster up so both configurations are conflicting until you force kubernetes to make the cluster goes to the same state as the restored one.

You can try to only backup and restore your own databases instead of the entire postgresql data.

**Comment by parvaths1118** [comment]
Thank you so much for your clarification @dani8art  .Please close the case.
