### ISSUE TITLE
[bitnami/elasticsearch] Add nodeSelector and tolerations for Elasticsearch metrics

### ISSUE THREAD

**Issue by harry-cai** [bitnami/charts#3276]
Hello,

Could you help to add 'nodeSelector' and 'tolerations' attributes for the metrics service?
Thanks!

Best regards,
Harry

**Comment by juan131** [comment]
Hi @harry-cai 

Thanks so much for the feedback! I agree with you, we should support them for the Curator too.

Would you like to create a PR or do you prefer us to implement it? I'll be glad to review the PR if you decide to go ahead and create a PR

**Comment by harry-cai** [comment]
Hello @juan131 ,

Sorry for my mistake!  
I've updated the title to Elasticsearch 'metric' service. The Curator has node attributes in the template.

I have created a pull request([3316](https://github.com/bitnami/charts/pull/3316)), please help to review it. Thanks!

Best regards,
Harry
