### ISSUE TITLE
Mongodb replicaset members host is set to IP instead of fully qualified domain name

### ISSUE THREAD

**Issue by davide-talesco** [bitnami/charts#3281]
**Which chart**:
charts/bitnami/mongodb/

**Describe the bug**
When creating a default replicaset release the locally stored replicaset config file reference each member via IP instead of FQDN.

This is a problem when one of the members fails and restart. Once it restarts it will possibly get a differnet IP and will not be able to join the replicaset 

I thought replicaSetHostnames should do the trick but it is true by default and it seems it doesn't make any difference.

I also noticed a Warning message in the mongo logs:

mongodb 07:27:29.94 WARN  ==> In order to use hostnames instead of IPs your should set MONGODB_ADVERTISED_HOSTNAME

so I tried to use the extraEnvVars to set above Env variable but the problem persists.

extraEnvVars:
  - name: MONGODB_ADVERTISED_HOSTNAME
    value: enabled

**To Reproduce**
1. create value.yaml as below 
```yaml
architecture: replicaset
```
2. helm install mongo -f value.yaml bitnami/mongodb
3. kubectl exec -it mongo-mongodb-0 -- /bin/bash
4. mongo
5. rs.conf()

```json
"members" : [
                {
                        "_id" : 0,
                        "host" : "10.131.17.103:27017",
                        "arbiterOnly" : false,
                        "buildIndexes" : true,
                        "hidden" : false,
                        "priority" : 5,
                        "tags" : {

                        },
                        "slaveDelay" : NumberLong(0),
                        "votes" : 1
                },
                ...
        ],
```

You can see the members[x].host is the IP and not the hostname of the member.

6. kubectl delete pod mongo-mongodb-0
7. wait for the new pod to be created
8. exec into the new pod and connect to mongo
9. run rs.status() and see the new instance cannot join the replica set with InvalidReplicaSetConfig codeName. The reason is the conf reference the old member by IP.

```json
rs0:OTHER> rs.status()
{
        "operationTime" : Timestamp(1596120812, 1),
        "ok" : 0,
        "errmsg" : "Our replica set config is invalid or we are not a member of it",
        "code" : 93,
        "codeName" : "InvalidReplicaSetConfig",
        "$clusterTime" : {
                "clusterTime" : Timestamp(1596120812, 1),
                "signature" : {
                        "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
                        "keyId" : NumberLong(0)
                }
        }
}
rs0:OTHER> 
```
10. To fix just manually update the replicaset config replacing the old IP with the new hostname

cfg = rs.conf()
cfg.members[0].host = 'pod fully qualified name'
rs.reconfig(cfg, {force: true})

**Expected behavior**
The replicaset config when initially created should reference all the members via their fully qualified domain name

**Version of Helm and Kubernetes**:

- Output of `helm version`:

version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by miguelaeh** [comment]
Hi @davide-talesco ,

> so I tried to use the extraEnvVars to set above Env variable but the problem persists.

extraEnvVars:

    name: MONGODB_ADVERTISED_HOSTNAME
    value: enabled


I think you just need to set `replicaSetHostnames=true` but have in mind it will not take effect when `architecture` is `standalone`.
So I would give a try with:
```
architecture: replicaset
replicaSetHostnames: true
```

**Comment by davide-talesco** [comment]
@miguelaeh 

as stated above I already tried to set the replicaSetHostnames key but the problem persists.
Of course the architecture must be replicaset.

Any other ideas?
Am I missing something?

**Comment by miguelaeh** [comment]
Hi @davide-talesco ,
I have been trying to replicate the issue but with no luck.
Could you install it using the following command and paste the logs?
```
helm install mongodb bitnami/mongodb --set architecture=replicaset,replicaSetHostnames=true
```

Also, wich version of the Helm Chart are you using?

**Comment by davide-talesco** [comment]
I installed the chart as you suggested but I get the same result.

As you can see the logs of mongodb-0 still shows the warning message

![image](https://user-images.githubusercontent.com/17530954/89072316-38be1280-d370-11ea-8707-130563b14089.png)

and if I connect to mongodb-0 and check the replicaset configuration I can see both members.host is the containers IP rather than the FQDN.

![image](https://user-images.githubusercontent.com/17530954/89072587-c3067680-d370-11ea-9a03-9f5329db2040.png)

I am using 
bitnami/mongodb                   	8.0.1        	4.2.8

how does the log looks like in your case?

**Comment by miguelaeh** [comment]
Hi @davide-talesco ,
Could you try using the lastest version of the Helm Chart?
Execute:
```
helm repo update
```

and then install it again.
I am using the version `8.2.1` which is the latest one and that is not shown:

![image](https://user-images.githubusercontent.com/36923089/89175528-37ffc900-d588-11ea-870c-628857d7b626.png)
