### ISSUE TITLE
[bitnami/zookeeper] The production's configuration can not work for me

### ISSUE THREAD

**Issue by pengmingming** [bitnami/charts#3283]
**Which chart**:
bitbnami/zookeeper  zookeeper-5.21.0.tgz

**Describe the bug**
[ERROR] templates/: template: zookeeper/templates/statefulset.yaml:135:31: executing "zookeeper/templates/statefulset.yaml" at <.Values.autopurge.purgeInterval>: nil pointer evaluating interface {}.purgeInterval

Error: 1 chart(s) linted, 1 chart(s) failed

**To Reproduce**
1. helm pull bitbnami/zookeeper
2. tar -xvxf zookeeper-5.21.0.tgz
3. cd zookeeper
// I'd like to overwrite the `values.yaml`  use the `values-production.yaml`
4. cp values-production.yaml values.yaml
5.Use the command  with `helm lint .` in order to check the charts

**Expected behavior**
[ERROR] templates/: template: zookeeper/templates/statefulset.yaml:135:31: executing "zookeeper/templates/statefulset.yaml" at <.Values.autopurge.purgeInterval>: nil pointer evaluating interface {}.purgeInterval

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by pengmingming** [comment]
hello! I use values-production.yaml instead of the values.yaml. but it cannot work well!

**Comment by joancafom** [comment]
Hi @pengmingming 

Thanks for your issue! I was able to reproduce the problem locally and am preparing a PR in order to fix it. I will link back to this issue in order to let you know 😃

**Comment by pengmingming** [comment]
@joancafom Alright, thanks for your quick replay.
