### ISSUE TITLE
[bitnami/mongodb] mongodb 4.4 is out, any plans to support it?

### ISSUE THREAD

**Issue by botzill** [bitnami/charts#3290]
Hi.

Do you have plans to support 4.4 ?

Thx.

**Comment by carrodher** [comment]
Hi, thanks for letting us know.

First, we need to work on releasing the bitnami/mongodb Docker image:
- https://github.com/bitnami/bitnami-docker-mongodb (code)
- https://hub.docker.com/repository/docker/bitnami/mongodb (image)

Once released the new image version, you will be able to use it in the chart by modifying the values, for example installing the chart with the following parameter: `helm install ... --set image.tag=4.4` or just `helm install` if the new version is the one set by default in the values.yaml

**Comment by botzill** [comment]
Hi @carrodher. 

OK great, looking forward to 4.4, they seem to add some interesting features that we may need.

**Comment by carrodher** [comment]
We are going to work on this during this iteration, please stay tuned to [DockerHub](https://github.com/bitnami/bitnami-docker-mongodb) or [GitHub](https://github.com/bitnami/bitnami-docker-mongodb) to see the new branch.

Once released you should be able to use it in the chart by setting `--set image.tag=4.4` or modifying the _values.yaml_, we are going to wait sometime before doing this version the default one in the chart.

**Comment by carrodher** [comment]
The new version was released yesterday: https://github.com/bitnami/charts/commit/99c83cf16905bc0849e7f569264a450cc6425edf
