### ISSUE TITLE
[bitnami/fluentd] Aggregator pods don't use created & declared ServiceAccount

### ISSUE THREAD

**Issue by chadlwilson** [bitnami/charts#3292]
**Which chart**:
Fluentd chart, in aggregator configuration

**Describe the bug**
Even with the default top-level `values.yaml` configuration of
```yaml
serviceAccount:
  create: true
```

The aggregator `StatefulSet` definition does not use the created `ServiceAccount` in its pod spec, and instead uses the `default` service account. Given this is a top level configuration in the chart, this is a bit confusion. It feels like you should be able to use

```yaml
aggregator:
  enabled: true
forwarder:
  enabled: false
serviceAccount:
  create: true
rbac:
  create: false
```
(since I don't think the aggregator has a use case for the RBAC permissions being created by the chart?)

**To Reproduce**
- Install the default chart with `aggregator.enabled=true`
- Look at the `serviceAccount` the aggregator pods are running with

**Expected behavior**
The aggregator pods should be running with the service account created when `serviceAccount.create=true`

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dani8art** [comment]
Hi @chadlwilson thanks you for opening this issue and working in the PR, let's move the conversation there.
