### ISSUE TITLE
[bitnami/redis] PDB selector doesn't use the release

### ISSUE THREAD

**Issue by swiatekm** [bitnami/charts#3294]
**Which chart**:
[bitnami/redis], all releases since PDB was introduced - `10.7.4+`.

**Describe the bug**
The PDB selects all redis pods in the namespace, which makes it behave incorrectly when running multiple releases in a single namespace.

**To Reproduce**
Install two Redis releases in a single namespace with pdb enabled. Both pdbs with select all the Redis pods in the namespace, rather than just the ones belonging to their release.

**Expected behavior**
A PDB should only select Pods that belong to the release it belongs to.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.14.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-14f01f", GitCommit:"14f01fe8f04411d5e187b220034ca2117d79f7de", GitTreeState:"clean", BuildDate:"2020-05-23T21:32:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
I'd already fixed this in a fork, but wanted to submit an issue first in case there was something I was missing. I'll submit a PR once the issue is acknowledged.

**Comment by marcosbc** [comment]
Hi @swiatekm, it looks like you're right, it's missing references to the release/instance name. Could you send the PR? Thanks!
