### ISSUE TITLE
Q: MariaDB, long running mysql_upgrade and upgrade accross two versions

### ISSUE THREAD

**Issue by torsten-liermann** [bitnami/charts#3295]
Hi,

Requirement: A single MariaDB instance in version X.Y with a larger database must be upgraded to version X.Y + 2.

I am thinking that a longer running mysql_upgrade should run without using the database in parallel. However, this would mean that the upgrade does not run in the normal MariaDB pod, but in its own container. If the MariaDB upgrade runs in the normal pod, there would be problems with the readiness probe.

Furthermore, I unfortunately need two steps of the DB upgrade: first for the upgrade from version X.Y to X.Y + 1 and then the upgrade from version X.Y + 1 to X.Y + 2

Aren't initContainers a good solution for the two upgrade steps? For this I imagine a small change to the Docker image, which ensures that the MariaDB container closes after a mysql_upgrade.

I know rolling update is also supported, but at the moment it's about an existing, simple installation.
Am I thinking right so far, or are there other solutions?

Thanks
Torsten

**Comment by miguelaeh** [comment]
Hi @torsten-liermann ,
Would it be possible for you to increase the `readinessProbe` period temporally? In that way, I think you should be able increase it, perfomr the upgrade and then return it to your current value.

**Comment by torsten-liermann** [comment]
I asked for a feature request: "run mysql upgrade in an init container, shutdown the daemon and exit. "

If that's not a good idea, then it doesn't matter.

Thanks.
