### ISSUE TITLE
[bitnami/discourse] sidekiq missing pid | discourse

### ISSUE THREAD

**Issue by gkarthiks** [bitnami/charts#3296]
**Which chart**:
bitnami/discourse: 0.1.7

**Describe the bug**
Using the *bitnami/discourse* chart from https://charts.bitnami.com/bitnami, after installation in the kubernetes(ocp) cluster, the postgresql and redis are running fine. But the following error message is thrown in the sidekiq container
```error
nami    ERROR Unable to start com.bitnami.discourse-sidekiq: Cannot find pid file '/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid
```

The second issue is, if I run the discourse without sidekiq (ofcourse i will loose lot of background functionality, but) when the discourse pod (with just the discourse container without sidekiq) is getting evicted and recreated again, the newly created pod (discourse container) couldn't come backup online. This throws an error stated below.
```error
  Error executing 'postInstallation': ERROR:  duplicate key value violates unique constraint "index_site_settings_on_name"
  DETAIL:  Key (name)=(site_contact_username) already exists.
```

**To Reproduce**
##### Problem Scenario 1
1. Install the bitnami/discourse in OCP/Kubernetes Cluster
2. Examine the sidekiq container logs (almost after 7 minutes)

##### Problem Scenario 2
1. Install the bitnami/discourse in OCP/Kubernetes Cluster without sidekiq container
2. Delete the discourse pod after successful deployment from the above step.
3. Examine the discourse container logs

**Expected behavior**
* Sidekiq should run without error in OCP/K8s cluster
* Discourse should run without issue after restarts

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-14T00:24:11Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

My deployments uses a service account that is configured in `scc` for `RunAsAny` privilege. So there shouldn't be any difference with a normal k8s cluster and my ocp for this scenario.

### Error logs from sidekiq container
```bash
Welcome to the Bitnami discourse container
 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
  
 nami    INFO  Initializing discourse-sidekiq
 postgre INFO  Trying to connect to PostgreSQL server
 postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
 postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
 discour INFO  Configuring the Discourse database files...
 discour INFO  Configuring Redis...
 discour INFO  Setting up SMTP in Sidekiq...
 discour INFO  Waiting for Discourse service to be ready...
 nami    INFO  discourse-sidekiq successfully initialized
 Starting discourse-sidekiq...
 nami    ERROR Unable to start com.bitnami.discourse-sidekiq: Cannot find pid file '/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid'.
```

### Error logs when restarted with only discourse container
```bash

Welcome to the Bitnami discourse container

 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues
   
 nami    INFO  Initializing postgresql-client
 nami    INFO  postgresql-client successfully initialized
 nami    INFO  Initializing discourse
 discour INFO  Patching Discourse...
 postgre INFO  Trying to connect to PostgreSQL server
 postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432
 postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432
 discour INFO  Preparing Discourse environment...
 discour INFO  Configuring the Discourse database files...
 discour INFO  Configuring Redis...
 discour INFO  Setting up SMTP in Discourse...
 discour INFO  Configuring Discourse database...
 discour INFO  Enabling PostgreSQL plugins for Discourse...
 discour INFO  Migrating database...
 discour INFO  Creating the Discourse admin user...
 discour INFO  Configuring your Discourse installation...
 Error executing 'postInstallation': ERROR:  duplicate key value violates unique constraint "index_site_settings_on_name"
 DETAIL:  Key (name)=(site_contact_username) already exists.
```

**Comment by dani8art** [comment]
Hi @gkarthiks thanks for opening the issue could you add `--set image.debug` so that we can see more info about the containers configurations, I suspect is about a write permission error when it tries to create `/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid`

BTW, are you using persistence? 

> Error logs when restarted with only discourse container

When it is running after a first initialization it shouldn't execute `Creating the Discourse admin user...` either `Configuring your Discourse installation...`. It also could be related to the write permissions since it couldn't write the file that says the initialization was done before.

**Comment by gkarthiks** [comment]
Actually its like a magic. The error is gone and working fine. But yeah I do use a PV and the permissions are set right.

**Comment by dani8art** [comment]
Hi @gkarthiks I cannot see any errors in the logs? could you explain it a bit more?

Could it be the `redirection`?
