### ISSUE TITLE
[bitnami/prometheus-operator] Missing CRDs for Synthetic Probes

### ISSUE THREAD

**Issue by laevilgenius** [bitnami/charts#3297]
**Which chart**: bitnami/prometheus-operator: 0.27.1

**Describe the bug**
Prometheus pod doesn't start.

**Additional context**
Prometheus operator v0.41.0 has added [Synthetic Probes](https://github.com/coreos/prometheus-operator/pull/2832) support which requires CRDs update.

**Comment by joancafom** [comment]
Hi @laevilgenius 

I have tried to reproduce the issue with the latest version of bitnami/prometheus-operato and it seems to work for me:

```console
$ helm list                                                                                                                                                                      
NAME 	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART                     	APP VERSION
lambda	default  	1       	2020-08-05 10:07:40.851158 +0200 CEST	deployed	prometheus-operator-0.28.0	0.41.0
```

```console
$ kubectl get pods
NAME                                                    READY   STATUS    RESTARTS   AGE
alertmanager-lambda-prometheus-operator-alertmanager-0   2/2     Running   0          7m8s
lambda-kube-state-metrics-59444c77c7-8k946               1/1     Running   0          7m13s
lambda-node-exporter-fkq8r                               1/1     Running   0          7m13s
lambda-node-exporter-r7457                               1/1     Running   0          7m13s
lambda-node-exporter-xfrff                               1/1     Running   0          7m13s
lambda-prometheus-operator-operator-85f45bcb66-66vg6     1/1     Running   0          7m13s
```

Regarding new Synthetic Probes, I will try to open a new PR adding support for the new CRDs.

Thanks!

**Comment by laevilgenius** [comment]
@joancafom There's still prometheus pod missing in your install, and operator should have a lot of logs like this: `cannot list resource "probes" in API group "monitoring.coreos.com" at the cluster scope`. With your PR it all should be working again, thanks!

**Comment by joancafom** [comment]
You are right! I was able to log the messages. Thanks for your issue, I will proceed with the merge once internal CI/CD tests have passed.

Thanks for your issue!
