### ISSUE TITLE
[redis] Incorrect docs of livenessProbe and readinessProbe values

### ISSUE THREAD

**Issue by wi1dcard** [bitnami/charts#3298]
**Which chart**:
The name (and version) of the affected chart
Chart: `redis`
Version: latest

**Describe the bug**

The default values of `master.livenessProbe` and `master.readinessProbe` are likely incorrect:

|                                          | in README.md | in values.yaml |   |   |
|------------------------------------------|--------------|----------------|---|---|
| master.livenessProbe.initialDelaySeconds | 30           | 5              |   |   |
| master.livenessProbe.periodSeconds       | 30           | 5              |   |   |
| master.readinessProbe.periodSeconds      | 10           | 5              |   |   |

See:

<https://github.com/bitnami/charts/blob/34459a915efb9af6bc062587027fffe6d77a5806/bitnami/redis/values.yaml#L297-L310>

**To Reproduce**

None

**Expected behavior**

The default values are identical in both README.md and values.yaml.

**Version of Helm and Kubernetes**:

Unrelated

**Additional context**

I'm not sure if we should fix the docs, or the value in the doc is correct and we should update values.yaml. So I decided to submit an issue first. How do you think?

**Comment by marcosbc** [comment]
Hi @wi1dcard, thanks for reporting this! It looks like the README is the one with wrong properties. I've created a PR at #3308 fixing this issue.
