### ISSUE TITLE
[bitnami/odoo] Update Ingress to kubernetes 1.18 

### ISSUE THREAD

**Issue by ruddy32** [bitnami/charts#3302]
bitnami/odoo 14.0.10

Ingress API extensions/v1beta1 is deprecated

Use following apiVersion: networking.k8s.io/v1beta1

**Comment by miguelaeh** [comment]
Hi @ruddy32 ,
We are aware of this issue. Nevertheless, that change will break the backward compatibility, because of that, we are waiting for the next new major version of the Helm Chart to perform that change.
