### ISSUE TITLE
[bitnami/wordpress] Kubernetes configuration specified for minikube does not work

### ISSUE THREAD

**Issue by milles9393** [bitnami/charts#3307]
**Which chart**:
Wordpress version latest and 8.1.0

**Describe the bug**
Trying to deploy a helm chart on minikube. According to docs the service type should be set to "NodePort" from type "LoadBalancer". See below, copied from "helm show values bitnami/wordpress". 

> ## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP
> 
> service:
>   type: LoadBalancer 

The output i get from installing it with overwritten values is 
```
Error: template: wordpress/templates/svc.yaml:9:19: executing "wordpress/templates/svc.yaml" at <.Values.service.annotations>: nil pointer evaluating interface {}.annotations
```

i've tried adding the 

I am overriding it using my own values file with the following command: 
$helm install wordpress bitnami/wordpress --values=wordpress-values.yaml

wordpress-values.yaml below: 
```
service:
  type: NodePort
```

I've also tried to add the "annotations: test" but the same error occurs. 

The install works with just default values. But "NodePort" should be used instead of "LoadBalancer" as the service type.   

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, I am sorry but I am not able to reproduce the issue, I just installed the latest WordPress version in minikube by running
```console
$ helm install wordpress bitnami/wordpress --set service.type=NodePort
NAME: wordpress
LAST DEPLOYED: Mon Aug  3 18:28:22 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
** Please be patient while the chart is being deployed **

Your WordPress site can be accessed through the following DNS name from within your cluster:

    wordpress.default.svc.cluster.local (port 80)

To access your WordPress site from outside the cluster follow the steps below:

1. Get the WordPress URL by running these commands:

   export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services wordpress)
   export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
   echo "WordPress URL: http://$NODE_IP:$NODE_PORT/"
   echo "WordPress Admin URL: http://$NODE_IP:$NODE_PORT/admin"

2. Open a browser and access WordPress using the obtained URL.

3. Login with the following credentials below to see your blog:

  echo Username: user
  echo Password: $(kubectl get secret --namespace default wordpress -o jsonpath="{.data.wordpress-password}" | base64 --decode)
```

Everything is up and running:
```console
$ helm ls
NAME     	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART          	APP VERSION
wordpress	default  	1       	2020-08-03 18:28:22.074441 +0200 CEST	deployed	wordpress-9.4.0	5.4.2

$ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
wordpress-64b547c44-mrx72   1/1     Running   0          3m51s
wordpress-mariadb-0         1/1     Running   0          3m51s
```

In order to access to the UI, I followed the steps in showed in the notes:
```console
$ export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services wordpress)
$ export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
$ echo "WordPress URL: http://$NODE_IP:$NODE_PORT/"
WordPress URL: http://192.168.64.8:31629/
```

![Screenshot 2020-08-03 at 18 33 57](https://user-images.githubusercontent.com/13216600/89205377-ee2ed700-d5b7-11ea-9a5f-d389b8059db6.png)

Are you able to do the same steps with the latest version (`helm repo update`)?

**Comment by milles9393** [comment]
@carrodher The way you did it works for me as well. What I tried to do which does not work is to override the default values with my own values file: 

1, create my own values dir
2, create my own wordpress-values.yaml 
3, Populate wordpress-values.yaml with new values (service: type: NodePort)
4, Install it $ helm install wordpress bitnami/wordpress --values=wordpress-values.yaml 

Overriding other default values like wordpressUsername or wordpressPassword does however work with my own values file .

**Comment by carrodher** [comment]
Hi, I am sorry but still not able to reproduce it.

I just created a `my-values.yaml` with the following content:
```yaml
 service:
   type: NodePort
 wordpressUsername: newUser
```
and deployed the chart by running:
```console
$ helm install wordpress bitnami/wordpress --values=my-values.yaml
NAME: wordpress
LAST DEPLOYED: Tue Aug  4 10:53:30 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
** Please be patient while the chart is being deployed **

Your WordPress site can be accessed through the following DNS name from within your cluster:

    wordpress.default.svc.cluster.local (port 80)

To access your WordPress site from outside the cluster follow the steps below:

1. Get the WordPress URL by running these commands:

   export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services wordpress)
   export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
   echo "WordPress URL: http://$NODE_IP:$NODE_PORT/"
   echo "WordPress Admin URL: http://$NODE_IP:$NODE_PORT/admin"

2. Open a browser and access WordPress using the obtained URL.

3. Login with the following credentials below to see your blog:

  echo Username: newUser
  echo Password: $(kubectl get secret --namespace default wordpress -o jsonpath="{.data.wordpress-password}" | base64 --decode)
```
from the above notes, the parameters set in `my-values.yaml` are being taken into account because the `echo Username` line is using the new username provided in that file, and also the instructions are the ones related to NodePort: ` export NODE_PORT ...`

Can you review your values.yaml file just in case there is any typo? Can you share it with us to try to reproduce it on our side?

**Comment by milles9393** [comment]
@carrodher 

I guess its some typo or some parameter that should not be in there. Because yours works for me as well.

my-values.yaml below.

```
wordpressUsername: helm-user
wordpressPassword: my-pass
wordpressEmail: helm-user@example.com
wordpressFirstName: Helm_is
wordpressLastName: Fun
wordpressBlogName: Learn Helm!
service:
  type: NodePort
```

**Comment by carrodher** [comment]
I am glad to see you are able to solve the issue, I just tried with the above values and everything is working as expected.
