### ISSUE TITLE
[bitnami/discourse] Can't specify pgsql admin user for external PostgreSQL server

### ISSUE THREAD

**Issue by glimberg** [bitnami/charts#3311]
**Which chart**:
bitnami/discorurse 0.1.7 (latest as of this writing)

**Is your feature request related to a problem? Please describe.**
When deploying in GCE/GKE along with a CloudSQL PostgreSQL server, users don't have access to the main `postgres` account within PostgreSQL.  You can create admin accounts, but cannot access that account.

**Describe the solution you'd like**
The ability to specify an admin account other than `postgres` to do the database setup for Discourse

**Describe alternatives you've considered**
There aren't any as far as I can see

**Comment by marcosbc** [comment]
Hi @glimberg, it looks like you should be using `externalDatabase`, which would allow to use an external database different than the PostgreSQL chart.

Note you must also specify `--set postgresql.enabled=false` in the `helm install` call.

**Comment by glimberg** [comment]
externalDatabase.postgresqlPostgresPassword | Password for the root "postgres" user (used in the installation stage)
-- | --
^^ this is the field I'm talking about

**Comment by glimberg** [comment]
We don't have access to the postgres user

**Comment by marcosbc** [comment]
I see. Currently we're only exposing `postgresqlPostgresPassword` for `POSTGRESQL_ROOT_PASSWORD`, and there is a missing value for `POSTGRESQL_ROOT_USER`. I've created a PR at #3325 to fix this.

**Comment by marcosbc** [comment]
I've just merged #3325, note that the chart version 0.3.0 may take some time before it is released, but hopefully it should be available tomorrow.

Note that if you deploy it from the local `charts` repository (i.e. `helm install myrelease /path/to/charts/bitnami/discourse`), it should work now. Let us know if you find any issues.
