### ISSUE TITLE
trying to implement bitnami/kong in to GCP GKE cluster

### ISSUE THREAD

**Issue by kevinchu85** [bitnami/charts#3314]
Hello, I am new to kong and trying to implement bitnami/kong in our GCP Kubernetes cluster. Had a few questions revolving around the deployment and the security of the proxy and admin ports. 

1. Currently I can see the postgres deployment only has a 8Gig PV and I can't find a parameter that I can use to set it as a bigger PV size let's say like 20GB. Secondly can the size of PV be extended after the postgress and kong have been deployed to the GKE.

2. Currently I deployed kong with service.type as LoadBalancer which exposes the IP to the internet. Is there a way to control who can access the kong proxy and admin ports. What I mean is if someone is to come through external internet is there a way I can configure that only specific external IPs could get to kong and to specific ports of kong?

Really hope someone can help me out with this thank you.

**Comment by dani8art** [comment]
Hi @kevinchu85 thanks for opening the issue.

Regarding [1], you can use the subchart parameter, please find them [here](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#parameters), you can set them like `--set postgresql.persistence.size=20Gi`. On the other hand, it depends on the `storageClass` you are going to use the PV can be extended or not, more docs [here](https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource), and you can select the proper one from [google docs](https://cloud.google.com/kubernetes-engine/docs/concepts/storage-overview)

Regarding [2], you can try using [this](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-ilb) and the [service annotations](https://github.com/bitnami/charts/blob/master/bitnami/kong/values.yaml#L337)

**Comment by kevinchu85** [comment]
Hello @dani8art Thanks for your reply. Will try out the parameter you mentioned for the size of disk. Can this later be expanded as well if I run Helm upgrade with that parameter?

Will look in to the ingress topic you high lighted, does this mean we will leave the service.type as default which is ClusterIP?

**Comment by dani8art** [comment]
> Can this later be expanded as well if I run Helm upgrade with that parameter?

It depends on the storageclass you have used to create your PVC.

> can set the storageclass as well using a parameter?

Yes you could use it as `postgresql.persistence.storageClass`

>  and the deployment only creates 1 container of postgres, which I think we have to manually scale as the stateful does not have the option to auto scale is that correct?

Please use https://github.com/bitnami/charts/tree/master/bitnami/postgresql#production-configuration-and-horizontal-scaling

>  And will we need to enable the ingress controller?

Please could you share with us the entire command you used? so that we can try to reproduce it and help you.

**Comment by kevinchu85** [comment]
Hey @dani8art, thanks for being so helpful.

I used the following command to install bitnami/kong without looking in to expanding the PV size at that time.

helm install kong-test --set autoscaling.enabled=true --set autoscaling.maxReplicas=5 --set service.exposeAdmin=true --set ingress.enabled=true bitnami/kong

From what I understand I think the server.type will need to be set to NodePort rather than leaving it default at ClusterIP. Please do correct me if I am wrong. Once the ingress is enabled that would mean we will be connecting to the admin console through the ingress service rather? and in case if my doubts are right about the node port will that mean I will need to create multiple ingress services based on the number of kong replicas there will be and use them as backend to an http(s) load balancer for traffic from outside?

**Comment by kevinchu85** [comment]
I did try adding --set service.type=NodePort but it timed out and the pods have the following error on them.

containers with unready status: [kong kong-ingress-controller]

**Comment by dani8art** [comment]
> will need to be set to NodePort rather than leaving it default at ClusterIP

Yes, you are right it should be `NodePort` or `LoadBalancer`, I would use `NodePort`

Regarding exposing admin `--set service.exposeAdmin=true`, this is to expose admin inside the cluster through a kubernetes service. As you can see `$ kubectl get service kong-test -o yaml` `http-proxy` and `http-admin` are exposed in `NodePort`s but checking the ingress entry  `$ kubectl get ingress kong-test -o yaml` the only exposed port is `http-proxy`

> Error: failed post-install: timed out waiting for the condition

This error is caused because of your persistence data is conflicting with the new one you have to completely remove your PVC from your previous deployments, please execute this

```console
$ kubectl delete pvc data-kong-test-postgresql-0
```

**Comment by kevinchu85** [comment]
so how can I have both admin and the proxy exposed through the ingress rules? do I need to enable a different parameter to allow the admin to be exposed? As I do not want to want to have both directly exposed to the internet, I would like to have them exposed internally where traffic would be sent to and from kong out to the internet and internal through a loadbalancer as that way I will be able to allow traffic from specific IPs to reach kong rather than from anywhere.

in terms of removing the pvc to get it working, does this also mean each time I run helm upgrade to set certain parameters I will need to delete the pvc? if that is the case won't I loose all the configurations that I made in Kong? Like if I tried to scale the postgres container and that caused the same issue where to pop up on the pods. "containers with unready status: [kong kong-ingress-controller]"

**Comment by kevinchu85** [comment]
I tried the following kong install 

helm install kong-test --set service.exposeAdmin=true --set ingress.enabled=true --set service.type=NodePort bitnami/kong

and it seems the ingress ends up giving this error " Some backend services are in UNHEALTHY state"

**Comment by kevinchu85** [comment]
@dani8art , as an alternative I deployed Kong with service.type=NodePort and kept ingress.enabled as the default value of false.

I tried to then expose the service by manually creating an ingress rule on the GKE cluster but even in that scenario the ingress fails with the same error that I previously was encountering "backend services are in UNHEALTHY state"

**Comment by dani8art** [comment]
> in terms of removing the pvc to get it working, does this also mean each time I run helm upgrade to set certain parameters I will need to delete the pvc

No, you can upgrade your kong instance but you have to take into account that there are some values that you always have to pass because there are some values that are persisted such as `postgresql.postgresqlPassword`. If you don't pass it, it will be autogenerated again and you will have inconsistent data in your deployment, the one persisted and the other one just autogenerated.

> so how can I have both admin and the proxy exposed through the ingress rules?

you can try to set `ingress.hostname=""` and use 

```yaml
  extraHosts:
    - name: kong.local
       path: /admin
    - name: kong.local
       path: /api1
```

> "backend services are in UNHEALTHY state"

Yes, it seems to be related to the fact that when we deploy kong we don't have any backend service behind it so the health check is always done against `/` and it is returning the following. It should be healthy when a backend service is ready.

```console
$ curl -ik localhost:8080
HTTP/1.1 404 Not Found
Date: Tue, 11 Aug 2020 10:34:46 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 48
X-Kong-Response-Latency: 0
Server: kong/2.0.5

{"message":"no Route matched with those values"}
```

**Comment by kevinchu85** [comment]
Hello @dani8art do you mean something like ingress.hosts[0].name=kong.local, ingress.hosts[0].paths=/admin and ingress.hosts[1].name=kong.local,ingress.hosts[1].paths=/api ?

**Comment by dani8art** [comment]
You can find `ingress.hostname` at https://github.com/bitnami/charts/blob/master/bitnami/kong/values.yaml#L360 it will create the default host because of that we need to override it.

> Hello @dani8art do you mean something like ingress.hosts[0].name=kong.local, ingress.hosts[0].paths=/admin and ingress.hosts[1].name=kong.local,ingress.hosts[1].paths=/api ? I do not see ingress.hostname="" in the parameter list provided in the Helm Charts.

yes, could you try 

```
--set ingress.hosts[0].name=kong.local,ingress.hosts[0].paths=/admin,ingress.hosts[1].name=kong.local,ingress.hosts[1].paths=/api,ingress.hostname=""
```

Regarding,

```
Error: UPGRADE FAILED: cannot patch "kong-bitnami-test-postgresql" with kind StatefulSet: StatefulSet.apps "kong-bitnami-test-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

it is because we are using `volumeClaimTemplates` inside this StatefulSet, however you can use `postgresql.persistence.existingClaim=you-pvc` and handle it outside of helm deployment

**Comment by kevinchu85** [comment]
Hey @dani8art this would mean I should deploy kong using the values.yaml rather than helm?

I tried the following command:
helm install kong-bitnami-test --set ingress.hosts[0].name=kong.local --set ingress.hosts[0].paths=/admin --set ingress.hosts[1].name=kong.local --set ingress.hosts[1].paths=/api --set ingress.hostname="kong_test" --set postgresql.postgresqlPassword=bitnami --set service.type=NodePort --set service.exposeAdmin=true --set ingress.enabled=true bitnami/kong

And it failed with this error
Error: template: kong/templates/NOTES.txt:9:12: executing "kong/templates/NOTES.txt" at <.paths>: range can't iterate over /admin

**Comment by kevinchu85** [comment]
@dani8art I was able to work on an alternative to exposing the kong proxy the internet. I kept the services exposed to an internal IP by using service.type as NodePort and just used an external loadbalancer to point to the kong proxy. This resolved my issue of exposing it directly to the internet and I can add ssl certificates on the LoadBalancer to ensure only 443 traffic is allowed.

I would still though like to know where I was going wrong with the ingress rules as from your last post it seems like instead of using Helm I should use the values.yaml file to deploy kong. Please let me know if I am going in the right direction? Furthermore, I was looking at values.yaml file and I could not figure out how the postgres sql db was being deployed or it needs to be deployed separately using a different config file?

**Comment by kevinchu85** [comment]
An update on the issue, it was working on friday when I tried to use the external load balancer to point to kong but I am not sure what changed today when I got back to it I can't reach it anymore...

**Comment by dani8art** [comment]
> Error: template: kong/templates/NOTES.txt:9:12: executing "kong/templates/NOTES.txt" at <.paths>: range can't iterate over /admin

I did a mistake on the comment above, please try with:

```console
--set ingress.extraHosts[0].name=kong.local,ingress.extraHosts[0].path=/admin,ingress.hostname="",ingress.enabled=true
```

> Furthermore, is there a way to connect the kong install with cloud sql postgres? 

yes, it could be used `postgresql.external` to configure external postgresql

**Comment by kevinchu85** [comment]
@dani8art I went with an alternative to exposing the admin API. I used the GKE port forwarding to get access to the admin API console and configure Kong. This way the API port can only be accessed from my local and the admin port is not exposed to the internet. This way at least I think we can secure the admin port.

for the postgressql.external I actually did try using that parameter but it fails, I am guessing I need to have the kong DB schema first on the cloud sql? As I only created a DB instance and a db by the name of Kong. Are there any other parameters that we need to specify? As I am only specifying the host, username and password to the cloud sql.

**Comment by kevinchu85** [comment]
@dani8art I think the reason why the ingress is having issues with the setup is because in the kong deployment the healthcheck is not exposed to port 80. When we create an ingress it by default creates a healthcheck for the backend which is pointing to the node port rather than port 80.

**Comment by dani8art** [comment]
>  I am guessing I need to have the kong DB schema first on the cloud sql? 

No, Kong will create for you.

> Are there any other parameters that we need to specify?

```
    --set postgresql.enabled=false \
    --set postgresql.external.host=_HOST_OF_YOUR_POSTGRESQL_INSTALLATION_ \
    --set postgresql.external.password=_PASSWORD_OF_YOUR_POSTGRESQL_INSTALLATION_ \
    --set postgresql.external.user=_USER_OF_YOUR_POSTGRESQL_INSTALLATION_
```

>  I can remove the kong.local/ from the ingress?

Yes, you have to do both.
-  `--set ingress.hostname="kevin-gcplearning.com"`
-  point your cloud DNS to the load balancer IP

> Keep getting this error on the ingress even without exposing the admin console 

You will continue to see this error until you set up an API behind the proxy because the proxy itself returns an error when there is no API registered. 

```
$ curl -ik localhost:8080
HTTP/1.1 404 Not Found
```

**Comment by kevinchu85** [comment]
@dani8art what about the healthcheck that is failing on the load balancer that gets created using when ingress.enabled is set to true? I can see there are two different ports and two different health checks on that load balancer out of which the one on port 31402 health check fails.
I tried adding a sample route and it does not redirect to that sample "http://35.241.31.241/hello", when I hit that link I get the error "default error 404" but when I go to that link by itself it works without any issues.

http://hellothere-sck2sgpaua-ts.a.run.app

And can I add my SSL certificate to the loadbalancer through the load balancer manually? I assume I should be able to since it is an http(s) external load balancer

**Comment by dani8art** [comment]
> what about the healthcheck that is failing on the load balancer that gets created using when ingress.enabled is set to true?

Hi, I was checking deeper your use case and I think you can avoid using Ingress for exposing the proxy to internet, instead of you can follow the next steps. 

**Deploy kong**

I've added `--set ingressController.enabled=false` because you don't need it by now, right? if you would need it just remove the parameter. 

```console
$ helm install kong \
  --set postgresql.postgresqlPassword=8nIGPjGAZD \
  --set service.type=LoadBalancer \
  --set ingressController.enabled=false \
  bitnami/kong
```

**Get your IP**

You can use the IP directly, set an entry on your DNS or if you just want to try, add an entry in `/etc/hosts`. It may take a few minutes for the LoadBalancer IP to be available. You can watch the status of by running `kubectl get --namespace default svc -w kong`

```console
$ kubectl get svc --namespace default kong -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
```

**Configure your route**

```console
$ k port-forward kong-87bd98c88-2pfkr 8001:8001
```

Create a service

```console
$ curl --location --request POST 'http://localhost:8001/services' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "test",
    "url": "https://hellothere-sck2sgpaua-ts.a.run.app"
}'
```

Create a route

```
$ curl --location --request POST 'http://localhost:8001/services/test/routes' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "test",
    "protocols": ["http", "https"],
    "paths": ["/"]
}'
```

**Go to your IP**

```
curl -ik http://you_ip
```

> And can I add my SSL certificate to the loadbalancer through the load balancer manually? I assume I should be able to since it is an http(s) external load balancer

Yes, https://cloud.google.com/load-balancing/docs/https

**Comment by kevinchu85** [comment]
@dani8art I was initially using that way of exposing the proxy where I set the service.type as LoadBalancer but that creates a TCP loadbalancer which is a layer 4 LB and I want to use a layer 7 loadbalancer which gets deployed when we enable ingress.enabled=true. Once that LB gets created is when I would add my SSL certificate to the 443 port on that http(s) LB. The reason behind that is a lot of our traffic will be coming through http/https and yes I did remove the ingresscontroller.enabled parameter because I have a feeling we will need to use it in the near future. So just wondering how we can get that http(s) Lb working when I use ingress.enabled=true

**Comment by dani8art** [comment]
I used this command successfully to deploy kong as well, and the rest of the steps but you need to set an entry on your DNS or if you just want to try, add an entry in /etc/hosts for `kong.local`.

```console
$ helm install kong \
  --set postgresql.postgresqlPassword=8nIGPjGAZD \
  --set service.type=NodePort \
  --set ingress.enabled=true \
  --set ingressController.enabled=false
  bitnami/kong
```

**Comment by kevinchu85** [comment]
@dani8art, please have a look at the screenshot I shared. I tried the exact command you mentioned but the ingress does not work. I added kong.local to my local but there are errors on the ingress and because of that I get the error **404 try again after 30 seconds**

```
$ helm install kong \
  --set postgresql.postgresqlPassword=bitnami\
  --set service.type=NodePort \
  --set ingress.enabled=true \
  --set ingressController.enabled=false
  bitnami/kong
```

The only thing I changed was the postgresql password from the command you shared.

**Comment by kevinchu85** [comment]
@dani8art I actually just noticed that we can place SSL certs within Kong itself so I guess will use the type loadbalancer as it is and just add the SSL cert to the kong application through the admin console.

Big thanks for the help @dani8art

**Comment by dani8art** [comment]
> please have a look at the screenshot I shared. I tried the exact command you mentioned but the ingress does not work.

I followed this [step](https://github.com/bitnami/charts/issues/3314#issuecomment-677637777) but using this [command](https://github.com/bitnami/charts/issues/3314#issuecomment-677684963) to install kong and it worked for me. Please, make sure you are adding the route since it does not exist in kong then the ingress will return an error to you.

**Comment by kevinchu85** [comment]
@dani8art it's very strange... but I will give that another go. Currently I think I found a few work arounds for it and it's working ok. As an example I am using firewalls to control which IPs can access the Kong proxy and as for SSL I will try out adding it to the Kong API gateway itself.
I will though try out the steps you mentioned with that command and see how it goes. Will update you once I test it out.
Thanks Again!
