### ISSUE TITLE
[bitnami/rabbitmq] Unable to login to the rabbitmq management console

### ISSUE THREAD

**Issue by eran-davidi-optibus** [bitnami/charts#3317]
**Which chart**:
rabbitmq version 7.5.7

**Describe the bug**
Unable to login to the rabbitmq management console

**To Reproduce**
1. Install the chart with ```helm install --name rabbitmq bitnami/rabbitmq```
2. Try to login to the management console
3. See the yellow message error "Login failed"

**Expected behavior**
Login to the management console

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @eran-davidi-optibus ,
I am not able to reproduce your issue. I can login into the console correctly using a port-forward of the port `15672`, default user `user` and executing 
```
echo $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)
```
 to get the password

**Comment by eran-davidi-optibus** [comment]
It is working on eks 1.17 but not on eks 1.14

**Comment by miguelaeh** [comment]
Hi @eran-davidi-optibus ,
Can you see any error on your logs? Could you share the logs?

**Comment by eran-davidi-optibus** [comment]
This is the command I ran:
```helm install --name rabbitmq bitnami/rabbitmq --set auth.username=guest --set auth.password=guest```

trying to login the console and getting "Login failed" message.
Rabbit log attached
[rabbitmq.log](https://github.com/bitnami/charts/files/5028329/rabbitmq.log)

**Comment by emcay** [comment]
Id suggest checking the following in the values.yaml I wasn't able to login without setting the below

`loopback_users.guest = true`

**Comment by miguelaeh** [comment]
Hi,
I have tested it again using the command @eran-davidi-optibus provided and it worked for me.
If you have installed it before with different credentials try using a different name or deleting the PVCs and it should work.

**Comment by one70six** [comment]
Running into the same issue on chart: 7.5.8. Deleting the PVC solved it but that is a bit scary considering what is stored there for RMQ.

**Comment by rafariossaa** [comment]
Hi,
  Could it be that you first run the helm install without providing the user and password and then you run it again setting them ? In this case the PVC are created in the first run (without the settings) and later reused when the user and password are set.

**Comment by jarnix** [comment]
Somehow I cannot login too. I have to set the password for "user" using rabbitmqctl...
I tried setting a password in values in auth.password, the secret is set, but the rabbit doesn't seem to use it.
I'm on GKE 1.16.13-gke.1

**Comment by miguelaeh** [comment]
Hi @jarnix ,
If you installed it previously you will need to delete the PVC or to modify the previously stored password using the CLI.
If not the password that is being configured is the one from your previous release
Regards.

**Comment by jarnix** [comment]
thx I found the answer in other issues, sorry I did not find my comment again so I could not update it. Thanks !

**Comment by tlefevre** [comment]
@jarnix I am having this issue as well - where did you find an answer?

**Comment by miguelaeh** [comment]
Hi @tlefevre ,
This is how to solve it: https://github.com/bitnami/charts/issues/3317#issuecomment-702590391

**Comment by jarnix** [comment]
yes @tlefevre you would need to remove the PVC that is created with the chart deployment but not removed after its deletion.

**Comment by tlefevre** [comment]
Ah ok, I was afraid that was the solution. I already tried this with no luck, even no go with rabbitmqctl change_password.
