### ISSUE TITLE
[bitnami/wordpress] The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable

### ISSUE THREAD

**Issue by aleksey005** [bitnami/charts#3320]
Install from helm-chart
Kubernetes 1.18
Docker 19.3.6
PVC Longhorn 1.0.1

Error after restart workload in DB MariaDB (internal)
```
mariadb 08:32:41.16 
mariadb 08:32:41.17 Welcome to the Bitnami mariadb container
mariadb 08:32:41.17 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 08:32:41.17 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 08:32:41.17 
mariadb 08:32:41.17 INFO  ==> ** Starting MariaDB setup **
mariadb 08:32:41.19 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 08:32:41.20 INFO  ==> Initializing mariadb database
mariadb 08:32:41.21 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 08:32:41.21 INFO  ==> Using persisted data
mariadb 08:32:41.26 INFO  ==> Running mysql_upgrade
mariadb 08:32:41.28 INFO  ==> Starting mariadb in background
mariadb 08:32:43.36 INFO  ==> Stopping mariadb
```

**Comment by carrodher** [comment]
If I have not understood, you are able to deploy the chart using the above values.yaml with something like `helm install wordpress bitnami/wordpress -f my-values.yaml`; then you are trying to upgrade by running `helm upgrade wordpress -f my-values.yaml`, right?

What is the starting version from which you want to upgrade? Can you check the permission in the PVC? Please, take into account that both images (WordPress and MariaDB) are non-root images

**Comment by aleksey005** [comment]
> If I have not understood, you are able to deploy the chart using the above values.yaml with something like `helm install wordpress bitnami/wordpress -f my-values.yaml`; then you are trying to upgrade by running `helm upgrade wordpress -f my-values.yaml`, right?
yes

> What is the starting version from which you want to upgrade?
9.3.21 --> 9.3.24
and after reinstall 9.3.24
9.3.24 --> 9.4.0
update process with use internal DB installation from helm-chart not work!

> Can you check the permission in the PVC?
i use Longhorn 1.0.1 default storage classs

> Please, take into account that both images (WordPress and MariaDB) are non-root images
Longhorn not delete data - only add

**Comment by carrodher** [comment]
Thanks for the information, that is what I did trying to reproduce the issue:

- Installed bitnami/wordpress 9.3.21
```console
$ helm install wordpress bitnami/wordpress --version 9.3.21

$ helm ls
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
wordpress	default  	1       	2020-08-05 07:56:51.697128045 +0000 UTC	deployed	wordpress-9.3.21	5.4.2

$ kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
wordpress-76756cdd7b-dsfr2   1/1     Running   0          28m
wordpress-mariadb-0          1/1     Running   0          28m
```

- As 9.3.24 doesn't exist in the registry, I updated the deployment to the 9.3.22
```console
$ helm search repo bitnami/wordpress -l
NAME             	CHART VERSION	APP VERSION   	DESCRIPTION
bitnami/wordpress	9.4.0        	5.4.2         	Web publishing platform for building blogs and ...
bitnami/wordpress	9.3.22       	5.4.2         	Web publishing platform for building blogs and ...
bitnami/wordpress	9.3.21       	5.4.2         	Web publishing platform for building blogs and ...

$ helm upgrade wordpress --version 9.3.22 bitnami/wordpress --set mariadb.rootUser.password=HD64U4sDqp --set mariadb.db.password=RrDz02VNJX --set wordpressPassword=ddZVy1Pa6Z

$ helm ls
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
wordpress	default  	2       	2020-08-05 08:26:41.589347589 +0000 UTC	deployed	wordpress-9.3.22	5.4.2

$ kubectl get pods
NAME                         READY   STATUS        RESTARTS   AGE
wordpress-76756cdd7b-dsfr2   0/1     Terminating   1          31m
wordpress-7ff8b95bb9-tzhb6   1/1     Running       0          81s
wordpress-mariadb-0          1/1     Running       0          69s
```

- Now, I executed the same upgrade command but with the 9.4.0 version
```console
$ helm upgrade wordpress --version 9.4.0 bitnami/wordpress --set mariadb.rootUser.password=HD64U4sDqp --set mariadb.db.password=RrDz02VNJX --set wordpressPassword=ddZVy1Pa6Z

$ helm ls
NAME     	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
wordpress	default  	3       	2020-08-05 08:30:35.013251616 +0000 UTC	deployed	wordpress-9.4.0	5.4.2

$ kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
wordpress-58d4655786-nv25j   1/1     Running   0          9m27s
wordpress-mariadb-0          1/1     Running   0          13m
```

That is the same upgrade workflow but using the default values. What is different? Please note that the passwords are randomly generated and stored in a secret unless you set the password in the values.yaml (or with `--set`). Those passwords are randomly generated after installing/upgrading the chart, which means that during the upgrade, we need to use the existing password to avoid the deployment generating a new random one that doesn't match with the one stored from the first installation. That is only needed if you don't set any password.

In my `helm upgrade` commands, I am setting the passwords for mariadb root user, mariadb database and wordpress:
```
helm upgrade ... \
--set mariadb.rootUser.password=HD64U4sDqp \
--set mariadb.db.password=RrDz02VNJX \
--set wordpressPassword=ddZVy1Pa6Z
```
according to your values, you are setting the WordPress one (`wordpressPassword: testing`) so it is not needed to set this one as it is already in the values; but I don't see any values for the MariaDB passwords, so in this case, you need to pass them during the upgrade.

You can obtain those random passwords by running
```console
$ kubectl get secret --namespace default wordpress-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode
RrDz02VNJX

$ kubectl get secret --namespace default wordpress-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode
HD64U4sDqp
```

**Comment by aleksey005** [comment]
@carrodher the problem was precisely that. I set all passwords so that they would not be generated randomly and performed the update process from - as a result, the update was completed successfully. thank you for participating in solving my update problem! now my blog is working!

**Comment by carrodher** [comment]
I am glad that it worked for you. We are working on adding more verbosity about this kind of error when upgrading without setting the existing passwords.
