### ISSUE TITLE
[bitnami/harbor] Issue with custom TLS secret

### ISSUE THREAD

**Issue by ninjaslothx** [bitnami/charts#3330]
**Which chart**:
bitnami/harbor  6.0.11

**Describe the bug**
Job service fails to start when using custom `service.tls.existingSecret`
Due to unknown CA

```
Failed on load rest config err:Get https://harbor-core:443/api/internal/configurations: x509: certificate signed by unknown authority, url:https://harbor-core:443/api/internal/configurations
```

My values file is based on the values-production.yaml with the only params changed as follows:
```
service.type: Ingress
service.tls.existingSecret: "my-certificate"
service.tls.commonName: ""

ingress.hosts.core: harbor.mydomain.com
ingress.hosts.notary: notary.mydomain.com
externalURL: https://harbor.mydomain.com
```

Certificate used includes tls.crt tls.key and ca.crt.  

My understanding is service.tls.existingSecret would be for external access only via the ingress. 
However if I set service.tls.existingSecret defaults (empty string) and set back the commonName it works as expected. 

Is it using the certificate from service.tls.existingSecret to respond internally to the cluster as well via https://harbor-core:443?

I do see the generated certs here and they are issued by the `harbor-internal-ca`
```
harbor-chartmuseum-crt         kubernetes.io/tls                     3      19m
harbor-chartmuseum-secret      Opaque                                1      19m
harbor-clair                   Opaque                                3      19m
harbor-clair-crt               kubernetes.io/tls                     3      19m
harbor-core                    Opaque                                4      19m
harbor-core-crt                kubernetes.io/tls                     3      19m
harbor-core-envvars            Opaque                                8      19m
harbor-jobservice              Opaque                                1      19m
harbor-jobservice-crt          kubernetes.io/tls                     3      19m
harbor-jobservice-envvars      Opaque                                1      19m
harbor-notary-server           Opaque                                5      19m
harbor-portal-crt              kubernetes.io/tls                     3      19m
harbor-postgresql              Opaque                                2      19m
harbor-registry                Opaque                                3      19m
harbor-registry-crt            kubernetes.io/tls                     3      19m
harbor-trivy-crt               kubernetes.io/tls                     3      19m
harbor-trivy-envvars           Opaque                                3      19m
```

I feel I may be missing something here...any help would be appreciated.

**Comment by dani8art** [comment]
Hi @ninjaslothx, thanks for opening the issue

How are you creating the `service.tls.existingSecret`?

**Comment by ninjaslothx** [comment]
The certificate is created like so
`kubectl create secret generic my-certificate --from-file=tls.crt=mycert.crt --from-file=tls.key=mykey.key --from-file=ca.crt=myca.crt -n harbor`

The cert itself is generated from an internal Windows CA and is wildcard certificate for the domain. 
Happy to try using a cert with the fqdn in the subject/san if you think this could be related.

**Comment by ninjaslothx** [comment]
After some further testing, the issue seems completely unrelated to the custom cert.
It's actually caused by `internalTLS.enabled: true`

Apologies but I must have modified this without noting during my previous tests. 
When setting this to `false` there is no issues with deployment using my custom cert. 
When set to true the following 3 components fail to start.

```
NAME                                    READY   STATUS             RESTARTS   AGE
harbor-chartmuseum-676fc7bcdf-cmfpj     0/1     CrashLoopBackOff   4          2m19s
harbor-jobservice-54fd988786-xh4zk      0/1     Running            1          2m19s
harbor-portal-6cf67f9c6b-ww757          0/1     Running            1          2m19s
```
 
This is true using the default values-production.yaml with internalTLS enabled as well on chart version 6.0.11

**Comment by dani8art** [comment]
Hi @ninjaslothx ,

Could you try setting these values too?

```
core.tls.existingSecret=my-certificate
chartmuseum.tls.existingSecret=my-certificate
clair.tls.existingSecret=my-certificate
jobservice.tls.existingSecret=my-certificate
portal.tls.existingSecret=my-certificate
registry.tls.existingSecret=my-certificate
trivy.tls.existingSecret=my-certificate
```

**Comment by ninjaslothx** [comment]
If I supply custom certs for the values above it works without issues!
It woudl seem only when left for self generation I encounter issues.

**Comment by dani8art** [comment]
As I can understand you would like to use custom one for `service.tls.existingSecret` but this value in combination with `internalTLS.enabled=true` goes to an error, right?

**Comment by ninjaslothx** [comment]
Yes exactly. The use of the tls cert should be unrelated to the internalTLS. 
In saying that we would be updating the component internalTLS secrets in production (as you suggested above), so the issue is not breaking in that aspect.

**Comment by dani8art** [comment]
Hi @ninjaslothx, 

We have opened an internal task in order to evaluate and fix the issue, unfortunately, we can't give you an ETA. However, if it is important for you and you feel you can handle it and you have a chance to create a PR we would be happy to handle it.
