### ISSUE TITLE
moodle update

### ISSUE THREAD

**Issue by zdhamasha** [bitnami/charts#3337]
**Which chart**:
The name (and version) of the affected chart

 bitnami/moodle  version 8.0.1

**Describe the bug**
we have upgraded our moodle from version 3.7 to 3.9 and the upgrade went very well, after upgrading when we open the site 
notification it is ask for upgrade and the version not changed  

![image](https://user-images.githubusercontent.com/63958325/89426053-65907200-d742-11ea-91c4-ea67835a6b6c.png)

**Comment by miguelaeh** [comment]
Hi @zdhamasha ,
How did you the upgrade? If you just changed the image it will not upgrade the application since we are persisting the full application directory because of symlinks issues. It is necessary to upgrade it manually.

**Comment by zdhamasha** [comment]
@miguelaeh  

I upgraded it by helm upgrade command with updating the chart version --version 8.0.1

**Comment by miguelaeh** [comment]
Hi @zdhamasha ,
I am afraid that will not upgrade the Magento application since it is persisted into the volumes. You will need to perform the upgrades manually either connecting to the pods or using the UI.
Regards.

**Comment by zdhamasha** [comment]
Sorry for late reply 

What do you mean by the Magento application !

**Comment by rafariossaa** [comment]
Hi,
  I think he meant moodle instead of magento.

**Comment by zdhamasha** [comment]
I followed the following link to fix the issue 

https://docs.bitnami.com/oci/apps/moodle/administration/upgrade/#:~:text=Approach%20A%3A%20Bitnami%20installations%20using%20system%20packages,-Move%20your%20current&text=Navigate%20to%20the%20application%20from,refer%20to%20the%20migration%20steps.
