### ISSUE TITLE
[Bitnami/Harbor] Chart Version 7.0.1 does not have all the images updated to Harbor 2.0.2

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#3351]
**Which chart**:
Harbor 7.0.1

**Describe the bug**
In the default values for the chart, only some of the container images have been updated to the harbor 2.0.2 versions found in the bitnami docker hub repositories.

**Expected behavior**
All the images to be for the same harbor version.

**Comment by marcosbc** [comment]
Hi @ajchiarello, thanks for reporting this. Harbor 7.0.2 was just released with the updated versions, so it should be correct now.

**Comment by ajchiarello** [comment]
Thanks!
