### ISSUE TITLE
Unable to delete svc/loadbalancer on prometheus operator

### ISSUE THREAD

**Issue by matty1979** [bitnami/charts#3353]
`kubectl delete -n monitoring service prometheus-operator-prometheus-thanos `

Running this results in the following happening
`service "prometheus-operator-prometheus-thanos" deleted
error: An error occurred while waiting for the object to be deleted: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 5; INTERNAL_ERROR") has prevented the request from succeeding`

I'm unable to delete the namespace installed in as it won't remove the service. 

`kubectl get namespace "stucked-namespace" -o json \
            | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/" \
            | kubectl replace --raw /api/v1/namespaces/stucked-namespace/finalize -f -`

Results with

`"kind":"Namespace","apiVersion":"v1","metadata":{"name":"monitoring","selfLink":"/api/v1/namespaces/monitoring/finalize","uid":"a3ca2714-acf5-4f00-b6f6-d9b77ea087aa","resourceVersion":"481025","creationTimestamp":"2020-08-06T15:37:36Z","deletionTimestamp":"2020-08-06T17:42:45Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2020-08-06T17:42:51Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2020-08-06T17:42:51Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"False","lastTransitionTime":"2020-08-06T17:42:51Z","reason":"ContentDeleted","message":"All content successfully deleted, may be waiting on finalization"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2020-08-06T17:42:51Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: services. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2020-08-06T17:42:51Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: service.kubernetes.io/load-balancer-cleanup in 1 resource instances"}]}}`

I'm unable to delete the namspace since I'm unable to remove the load balancer.

**Comment by miguelaeh** [comment]
Hi @matty1979 ,
This doesn't seems to be an error with the Helm Chart but with the kubernetes cluster. Please refer to https://github.com/kubernetes/kubernetes/issues/69147

**Comment by matty1979** [comment]
Correct, /close please. Issue fixed on my end.
