### ISSUE TITLE
[bitnami/rabbitmq] auth.password or default_pass?

### ISSUE THREAD

**Issue by emcay** [bitnami/charts#3354]
**Which chart**:
rabbitmq-7.5.7

**Describe the bug**
auth.password or default_pass both exist in the values.yaml generating confusion

**Expected behavior**
Clear notes on which/what should be done with either or both of them, or eliminate one of them

Im not sure why this is here, it does look like CHANGEME makes its way into the rabbitmq.conf, how does this differ than the auth.password parameter?

**Comment by dani8art** [comment]
Hi @emcay thanks for opening the issue.

You should use `auth.password` always, if not the chart will generate a random password. `default_pass` will be always overridden but we need to keep it there.

**Comment by emcay** [comment]
Thanks for the response. I went through the scripts and understand how it works now.
