### ISSUE TITLE
bitnami/postgresql

### ISSUE THREAD

**Issue by pavlin117** [bitnami/charts#3361]
**Which chart**:
bitnami/postgresql

**Describe the bug**
Trouble to install chart and staying in pending state. after doing "kubectl describe pod <podname> it gives me an event:

  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "postgresql-postgresql-0": pod has unbound immediate PersistentVolumeClaims

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by dani8art** [comment]
Hi @pavlin117 thanks for opening the issue,

Could you share with us the entire command you executed and the values you set, please?

BTW, does the cluster have PV enable?
