### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Add Prometheus + Grafana to the template

### ISSUE THREAD

**Issue by sabbyanandan** [bitnami/charts#3363]
**Which chart**:
`bitnami/spring-cloud-dataflow`

**Is your feature request related to a problem? Please describe.**
When we ported the SCDF's [OSS Helm chart](https://hub.helm.sh/charts/stable/spring-cloud-data-flow) and its feature set, it appears we have missed transitioning the Prometheus + Grafana along with it. I do see the Prometheus RSocker Proxy component; however, without the basic Prometheus/Grafana combination running automatically, the set up (via: `metrics.enabled=true`) is useless for monitoring. The single command provisioning SCDF with monitoring, in particular, it doesn't give that great getting started experience. 

**Describe the solution you'd like**
It'd be great to provision SCDF along with Prometheus, Prometheus RSocket Proxy and Grafana when the Bitnami chart is used with the following command:

> helm install my-scdf-release bitnami/spring-cloud-dataflow --set metrics.enabled=true

This is similar to the following command in the OSS Helm chart that is available today:

> helm install my-scdf-release stable/spring-cloud-data-flow --set features.monitoring.enabled=true

**Comment by beltran-rubo** [comment]
Thanks Sabby, we will work on making it simple to integrate with the other Helm Charts of Prometheus & Grafana.

**Comment by CalvinTMurray** [comment]
Hi, is this still under development, as i can't see any reference to documentation or current open issues on this

**Comment by marcosbc** [comment]
@calvinbui I guess what you're looking for is [this](https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/values.yaml#L93) and/or [this](https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/values.yaml#L811), right?

**Comment by CalvinTMurray** [comment]
Sorry, what i'm looking for is this.  This old OSS stable helm chart provided the following feature toggle for grafana and prometheus: https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow#feature-toggles.

https://github.com/helm/charts/blob/master/stable/spring-cloud-data-flow/requirements.yaml, i see there was also discussion in https://github.com/spring-cloud/spring-cloud-dataflow/issues/4063#issuecomment-670596389 with regards to the missing functionality

**Comment by marcosbc** [comment]
After some more investigation about the context for this issue, I see that we decided not to add loging/monitoring tools as dependencies for any of our charts, instead we aim to make them compatible with existing logging/monitoring tools that are already installed in the cluster. In summary, we decided not to implement this feature.

If you want to see how to integrate SCDF chart with logging/monitoring solutions, you can check out this example script (which takes care of deploying a Prometheus+Grafana and configuring them into SCDF): https://github.com/sabbyanandan/SpringOne2020/blob/master/scripts/deploy-scdf.sh

**Comment by CalvinTMurray** [comment]
@marcosbc That's perfect thanks!
