### ISSUE TITLE
go client fails to connect to Sentinel and AUTH is enabled

### ISSUE THREAD

**Issue by alaindazzi** [bitnami/charts#3366]
**Which chart**:
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/redis        	10.7.16      	6.0.6      	Open source, advanced key-value store. It is of...
bitnami/redis-cluster	3.1.11       	6.0.6      	Open source, advanced key-value store. It is of...

**Describe the bug**
i am connecting to a redis/sentinel set-up with go-redis client.

I have usePassword set to True in the redis chart both globally and within the sentinel block.

i can connect to redis only when a password is provided and i was expecting the same behavior via sentinel.

I get the following error ...

redis: 2020/08/07 23:57:58 sentinel.go:396: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required.

but i am providing a password. if i change the target url to the redis master it connects with the same password.

**To Reproduce**
```
Steps to reproduce the behavior:
1. deploy redis chart with helm
in values.yaml (override) make sure ...

## Use redis sentinel in the redis pod. This will disable the master and slave services and
## create one redis service with ports to the sentinel and the redis instances
sentinel:
  enabled: true
  ## Require password authentication on the sentinel itself
  ## ref: https://redis.io/topics/sentinel
  usePassword: true

## Use password authentication
usePassword: true

## Redis password (both master and slave)
## Defaults to a random 10-character alphanumeric string if not set and usePassword is true
## ref: https://github.com/bitnami/bitnami-docker-redis#setting-the-server-password-on-first-run
##
password: "foobar"

2.set-up go client 
redisSentinelClient := redis.NewFailoverClient(&redis.FailoverOptions{
					MasterName:    "mymaster",
					SentinelAddrs: []string{fmt.Sprintf("%s:%d", settings.RedisSentinelURL, settings.RedisSentinelPort)},
					PoolSize:      100,
					MaxRetries:    3,
					Password:      settings.RedisPassword,
					DB:            0,
				})
3. kubernetes svc log shows

jwt-service-v1-549bbd8fb5-wnv5m jwt-service redis: 2020/08/07 23:57:58 sentinel.go:396: sentinel: GetMasterAddrByName master="mymaster" failed: NOAUTH Authentication required.
```

**Expected behavior**
it should accept a password

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
C02TW0THHTDG:fid adazzi$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

i logged on the sentinel pod and dumped the config ... to confirm that the redis master password was set
```
$ k exec -it  redis-slave-0 -n redis -c sentinel sh
$ cat /opt/bitnami/redis-sentinel/etc/sentinel.conf
dir "/tmp"
bind 0.0.0.0
port 26379
sentinel myid 6958c8c9f249e07165e8254c1afb95094d2336ba
sentinel deny-scripts-reconfig yes
sentinel monitor mymaster 10.128.42.241 6379 2
sentinel down-after-milliseconds mymaster 60000
sentinel failover-timeout mymaster 18000
requirepass MJMS0giHBB
# Generated by CONFIG REWRITE
protected-mode no
user default on #a1960b49fe8baeab1d453fa072ab9b01010e0e9ec3ca299e2ebf89e24d81c8f9 ~* +@all
sentinel auth-pass mymaster MJMS0giHBB
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel known-replica mymaster 10.128.42.62 6379
sentinel known-replica mymaster 10.128.41.192 6379
sentinel known-sentinel mymaster 10.128.41.192 26379 0ada758feb23a9d01e7b7681012cf6e2a1258c84
sentinel known-sentinel mymaster 10.128.42.241 26379 1b075f4c00047d656a9ba01d462f9ff06f332b86
sentinel current-epoch 0
```

```
 k get svc -n redis
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
redis            ClusterIP   172.20.67.6     <none>        6379/TCP,26379/TCP   2d1h
redis-headless   ClusterIP   None            <none>        6379/TCP,26379/TCP   2d1h
redis-metrics    ClusterIP   172.20.249.48   <none>        9121/TCP             2d1h
```

i set my sentinel url to REDIS_SENTINEL_URL: "redis.redis.svc.cluster.local" and port 26379

Is this correct?or do i have to specify the 3 sentinel ip address:port pairs in the array?

**Comment by alaindazzi** [comment]
well i am passed this point now. the missing parameter was SentinelPassword in the go client.

```
redisSentinelClient := redis.NewFailoverClient(&redis.FailoverOptions{
					MasterName:       "mymaster",
					SentinelAddrs:    []string{fmt.Sprintf("%s:%d", settings.RedisSentinelURL, settings.RedisSentinelPort)},
					PoolSize:         100,
					MaxRetries:       3,
					Password:         settings.RedisPassword,
					SentinelPassword: settings.RedisPassword,
					// SentinelUsername: "mymaster",
					DB: 0,
				})
```
but now i am getting ... connection reset by peer!!!

jwt-service-v1-5c79675448-mjwxk jwt-service redis: 2020/08/08 01:13:06 sentinel.go:470: sentinel: discovered new sentinel="0ada758feb23a9d01e7b7681012cf6e2a1258c84" for master="mymaster"
jwt-service-v1-5c79675448-mjwxk jwt-service redis: 2020/08/08 01:13:06 sentinel.go:470: sentinel: discovered new sentinel="1b075f4c00047d656a9ba01d462f9ff06f332b86" for master="mymaster"
jwt-service-v1-5c79675448-mjwxk jwt-service redis: 2020/08/08 01:13:06 sentinel.go:438: sentinel: new master="mymaster" addr="10.128.42.241:6379"
jwt-service-v1-5c79675448-mjwxk jwt-service {"level":"error","ts":1596849196.432947,"caller":"redis/redis.go:97","msg":"Redis Connection Failed","error":"read tcp 10.128.41.40:45148->10.128.42.241:6379: read: connection reset by peer"

**Comment by joancafom** [comment]
Hi @alaindazzi 

Could you verify you can access the redis instance using the `redis-cli` command? I have tried deploying a Chart using your configuration and it all seems to be working:

```console
$ helm install tauro bitnami/redis
NAME: tauro
LAST DEPLOYED: Mon Aug 10 12:22:12 2020
NAMESPACE: default
STATUS: deployed
...

$ export REDIS_PASSWORD=$(kubectl get secret --namespace default tauro-redis -o jsonpath="{.data.redis-password}" | base64 --decode)

$kubectl run --namespace default tauro-redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:6.0.6-debian-10-r10 -- bash

$ redis-cli -h tauro-redis -p 6379 -a $REDIS_PASSWORD
$ tauro-redis:6379> ping
PONG

$ redis-cli -h tauro-redis -p 26379 -a $REDIS_PASSWORD
$ tauro-redis:26379> ping
PONG
```

I am afraid this could be an issue related to the `go client`. Could you verify this? Thanks

**Comment by alaindazzi** [comment]
redis works using the cli. sentinel also works form the cli. the redis-go client works great on my mac with an external redis/sentinel set-up. the same config on kubernetes is completely unstable.

**Comment by joancafom** [comment]
Hi @alaindazzi ,

It may be the case that if `redis-cli` works with no issues but `redis-go` client fails, this it due to the latter. I am afraid I cannot provide direct assistance with the `redis-go` client as I am not very familiar with. Nevertheless, we can try to bound the issue on the Redis side so you can get a better idea of what is happening 😄

1. Are you trying to connect from within the cluster or from outside it? 
2. What cluster are you using?
3. I saw you have provide with the errors shown from the client side, but can you provide with the logs that the pods show when the client performs a connection? (`kubectl logs <my-pod>`).

Thanks!

**Comment by steven-varga** [comment]
Experienced similar problems and following thought the above conversation helped to  solve my problems. Many thanks!
```
opts := redis.FailoverOptions{
	MasterName: name, SentinelAddrs: sentinels, DB: opt.DB,
	Username: opt.Username, Password: opt.Password,
// in my case  the following line was missing:
	SentinelUsername: opt.Username, SentinelPassword: opt.Password,
	...
}
```
