### ISSUE TITLE
Consider renaming thanos-querier to thanos-query

### ISSUE THREAD

**Issue by SerialVelocity** [bitnami/charts#3368]
**Which chart**:
The name (and version) of the affected chart.
Thanos 2.0.0

**Is your feature request related to a problem? Please describe.**
When trying to use the thanos dashboards (like https://github.com/thanos-io/thanos/raw/9b578afb476374b68dd5ac5bfe50bcef70690760/examples/dashboards/overview.json), they all key on `thanos-query`. This means that the dashboards do not work by default (stateless Prometheus clusters are painful because of this)

**Describe the solution you'd like**
Rename thanos-querier to thanos-query

**Comment by rafariossaa** [comment]
Hi,
  Could you provide a little bit more of detail ? I would like to know if this issue raises because you are learning/trying Thanos or because you have a current prometheus and thanos deployment and something went wrong.
  Have into account that those dashboards are tailor-made for the deployment that it is done by thanos-io's script `scripts/quickstart.sh`, so it will depend on the prometheus  job's names. You can check it on https://github.com/thanos-io/thanos/blob/master/scripts/quickstart.sh#L120 .
  In this case you will need to do some changes to those dashboards because not the same scenario that the one the script `quickstart.sh` starts.

**Comment by SerialVelocity** [comment]
I have a current prometheus/thanos deployment. I recently switched over from having a standard deployments/stateful sets to your chart and I am having the issue that the existing dashboards/alerts, they are all keyed on `thanos-query.*` but since your chart uses `thanos-querier`, it doesn't match.

I actually import my dashboards using https://github.com/integr8ly/grafana-operator which makes it difficult since it means I have to fork the dashboard repos. The same happens for alerts since all alerts I have found use `thanos-query.*` too.

This is just a small ticket about a pain point I felt. Feel free to close if you don't agree :)

**Comment by rafariossaa** [comment]
Hi, 
  We have currently a similar issue related to the use of thanos examples with our charts. #3373 .
  We are studying these issues.

**Comment by rafariossaa** [comment]
Hi, 
  The PR was merged, did it solved the issue for you ?

**Comment by SerialVelocity** [comment]
@rafariossaa Can you point me to the PR that you think fixed this?

**Comment by rafariossaa** [comment]
Hi, 
  I referred to PR 3116, that is linked in issue 3373. Maybe that can also work for you.

**Comment by SerialVelocity** [comment]
Hi @rafariossaa, that doesn't seem to fix anything. It isn't to do with the ports of the sidecar, it's to do with the name `thanos-query`.

**Comment by rafariossaa** [comment]
Hi,
  I am creating a internal task to made the changes needed. I can't give you an ETA.
  Meanwhile maybe you would like to make a PR, we will be glad to review and merge it.

**Comment by ahmednasir91** [comment]
@SerialVelocity you can use the mixins to generate the dashboards with updated query for the thanos querier. I had similar issue and ended up doing it in my fork and playing with mixins. So if you use the following config in mixins you can generate json dashboards

```jsonnet
(thanos {

   dashboard+:: {
     prefix: 'Mixin / Thanos / ',
     tags: ['thanos', 'infrastucture'],
     namespaceMetric: 'thanos_status:component_count',
     namespaceLabel: 'kubernetes_namespace',
   },

   query+:: {
     jobPrefix: 'thanos-querier',
     selector: 'kubernetes_pod_name=~"%s.*"' % self.jobPrefix,
     title: '%(prefix)sQuery' % $.dashboard.prefix,
     namespaceLabel: $.dashboard.namespaceLabel,
   },
   store+:: {
     jobPrefix: 'thanos-store',
     selector: 'kubernetes_pod_name=~"%s.*"' % self.jobPrefix,
     title: '%(prefix)sStore' % $.dashboard.prefix,
     namespaceLabel: $.dashboard.namespaceLabel,
   },
   rule+:: {
     jobPrefix: 'thanos-ruler',
     selector: 'kubernetes_pod_name=~"%s.*"' % self.jobPrefix,
     title: '%(prefix)sRule' % $.dashboard.prefix,
     namespaceLabel: $.dashboard.namespaceLabel,
   },
   sidecar+:: {
     jobPrefix: 'prometheus-server',  // The pod name for sidecar is prometheus.
     selector: 'kubernetes_pod_name=~"%s.*"' % self.jobPrefix,
     title: '%(prefix)sSidecar' % $.dashboard.prefix,
     namespaceLabel: $.dashboard.namespaceLabel,
   }
)
...
```

**Comment by SerialVelocity** [comment]
@ahmednasir91 Yes, the issue here is that all dashboards/monitoring that currently exists ready to use (without me having to fork and then keep up to date) are using `thanos-query.*`. Another option would be to file a PR on thanos to update the default jobPrefix to `thanos-quer` but since the pod is called `thanos-query` everywhere else, it would probably be better to adhere to that convention instead.

**Comment by ahmednasir91** [comment]
@SerialVelocity even without forking you can add this project as a library as mentioned in the README
1. install jsonnet bundler
2. follow https://github.com/thanos-io/thanos/tree/master/mixin#use-as-a-library to install as library
3. add a new `config.libsonnet` file as mentioned in my last comment
4. generate the dashboard and rule example files

**Comment by SerialVelocity** [comment]
@ahmednasir91 The point of this issue is to make it easier to use pre-generated dashboards. Yes, there are workarounds but they require you to keep your generated code up to date instead of relying on stuff that already exists. Whether it is using a fork or pulling in the project using jsonnet bundler (especially if you aren't using it currently) doesn't matter.

**Comment by mhulscher** [comment]
I drafted a PR @ https://github.com/bitnami/charts/pull/4307

**Comment by javsalgar** [comment]
Thanks! We will take a look and provide feedback :D, though I'm not sure if it will require extra changes in our side.
