### ISSUE TITLE
[bitnami/prometheus-operator] thanos-sidecar monitoring

### ISSUE THREAD

**Issue by ahmgeek** [bitnami/charts#3373]
**Which chart**:
[bitnami/prometheus-operator]

**Is your feature request related to a problem? Please describe.**
Is there a way to scrape the sidecar metrics?

**Describe the solution you'd like**
a service monitor for thanos-sidecar

**Comment by rafariossaa** [comment]
Hi,
  Could you elaborate a bit more in your scenario and needs ?

Thanks forehand.

**Comment by ahmgeek** [comment]
This dashboard: https://github.com/thanos-io/thanos/blob/master/examples/dashboards/sidecar.json
from the official thanos Repo, expects the sidecar/thanos-sidecar to expose metrics. 
This is not the case unfortunately, the `job="thanos-sidecar"` doesn't exist and the target doesn't exist in Prometheus.

Thanks a lot guys, you are the best.

**Comment by rafariossaa** [comment]
Hi, 
  We have currently a similar issue related to the use of thanos examples with our charts. #3368 .
  We are studying these issues.

**Comment by hwoarang** [comment]
@rafariossaa The sidecar metrics can be exposed by defining an additional port as explained here https://github.com/bitnami/charts/pull/3116

**Comment by rafariossaa** [comment]
Hi @hwoarang ,
  Thanks for linking to the PR.

**Comment by ahmgeek** [comment]
we need a service monitor for that, correct?

**Comment by hwoarang** [comment]
@ahmgeek depends. If you use thanos with prometheus-operator from Bitnami then the service monitor [1] already scrapes the thanos service[2] as it has the correct labels

[1] https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/templates/prometheus/servicemonitor.yaml
[2] https://github.com/bitnami/charts/blob/master/bitnami/prometheus-operator/templates/prometheus/thanos-service.yaml

**Comment by rafariossaa** [comment]
Hi, 
  The PR was merged, did it solved the issue for y ou ?

**Comment by ahmgeek** [comment]
@rafariossaa it did. I've closed the issue, thanks all.
