### ISSUE TITLE
CI broken?

### ISSUE THREAD

**Issue by aogier** [bitnami/charts#3382]
Hi, despite #3370 and the new minor 8.2.5 chart appeared in your repo, code is w/o the changes you've merged. Don't know if it's a correct expectation from me to find changes indeed merged in 8.2.5 version tho.

Can you help me? Thank you, regards

**Comment by rafariossaa** [comment]
Hi,
  Yes, another PR got first and used the 8.2.5, you have to rebase, and bump the chart version again.

**Comment by aogier** [comment]
Hi, thank you for your response. I'm unsure on how to proceed because if I look on master, I can see my changes. Could a simple bump w/o modifications do the trick?

**Comment by rafariossaa** [comment]
Hi,
 If your changes are already merge there is not action needed.

**Comment by aogier** [comment]
Rafario, I've literally told you that on first message :D 

kthxbye Rafario
