### ISSUE TITLE
[Thanos] Add memcached index and bucket blocks to chart as you do with `objstore`

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#3384]
**Which chart**:
Thanos 2.1.1

**Is your feature request related to a problem? Please describe.**
I would like to add the configuration for the Memcached stores utilised by the Thanos Store gateway since 0.12.0 for index (GA) and bucket (beta)
https://thanos.io/components/store.md/#memcached-index-cache

but providing the configuration on the Helm chart `extraFlags` 
```
storegateway:
  enabled: true
  extraFlags:
    - |-
      --store.caching-bucket.config=type: MEMCACHED
      config:
        addresses:
        - dns+thanos-memcached:11211
```
returns an error
```
Error: YAML parse error on thanos/templates/storegateway/statefulset.yaml: error converting YAML to JSON: yaml: line 57: mapping values are not allowed in this context
```

**Describe the solution you'd like**
Add files to `{{ include "thanos.fullname" . }}-objstore-secret` secret created on the chart

using a conditional when the key is defined

```
data:
  objstore.yml: |-
    {{- include "thanos.tplValue" (dict "value" .Values.objstoreConfig "context" $) | b64enc | nindent 4 }}
```
similarly
```
data:
  objstore.yml: |-
    {{- include "thanos.tplValue" (dict "value" .Values.objstoreConfig "context" $) | b64enc | nindent 4 }}
{{- if .Values.indexCacheConfig }}
  index-cache.yml: |-
    {{- include "thanos.tplValue" (dict "value" .Values.indexCacheConfig "context" $) | b64enc | nindent 4 }}
{{- end }}
{{- if .Values.bucketCacheConfig }}
  bucket-cache.yml: |-
    {{- include "thanos.tplValue" (dict "value" .Values.bucketCacheConfig "context" $) | b64enc | nindent 4 }}
{{- end }}
```

**Describe alternatives you've considered**
Use Helm and `extraFlags` but since the value of the flag is YAML there are validation errors when this is rendered
I'm pretty sure there is a workaround for this but it wouldn't be as clean as the proposed approach, IMO

**Additional context**
-

**Comment by carrodher** [comment]
Thanks for creating the issue and the associated PR, we're going to review and test the PR and this issue is going to be closed automatically once merged the PR. Thanks again
