### ISSUE TITLE
[bitnami/owncloud] owncloudPassword has an undocumented validation

### ISSUE THREAD

**Issue by samueldmq** [bitnami/charts#3394]
**Which chart**:
Latest owncloud.

**Describe the bug**
The value owncloudPassword has an unkown validation. For example, it can be "adminadm" but cannot be "admin123" nor simply "admin". Running the chart with an invalid value results in an unclear error message:

Welcome to the Bitnami owncloud container
[...]
nami    INFO  Initializing owncloud
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at drive-mariadb:3306
mysql-c INFO  MySQL server listening and working at drive-mariadb:3306
Error executing 'postInstallation':

  The "--admin-pass" option requires a value.

maintenance:install [--database DATABASE] [--database-connection-string DATABASE-CONNECTION-STRING] [--data
base-name DATABASE-NAME] [--database-host DATABASE-HOST] [--database-user DATABASE-USER] [--database-pass [
DATABASE-PASS]] [--database-table-prefix [DATABASE-TABLE-PREFIX]] [--admin-user ADMIN-USER] [--admin-pass A
DMIN-PASS] [--data-dir DATA-DIR]

**To Reproduce**
1. Set owncloudPassword to 'admin'
2. Run the chart

**Expected behavior**
The restrictions in the owncloudPassword values should be described in the README.

**Additional context**
I cannot share the versions of Helm and Kubernetes at this moment as ArgoCD is what is interacting with the cluster. I hope these info are not relevant to this specific report and you are able to reproduce it.

**Comment by dani8art** [comment]
Hi @samueldmq, thanks for opening the issue

I've followed the step to reproduce the issue but was unable to do it. Could you add `image.debug=true` and paste the more detailed logs, please?

BTW, could you also try to start a fresh instance? please, remove your current deployment and PVCs that have been created and execute the following

```console
$ helm repo upgrade
$ helm install owncloud bitnami/owncloud --set owncloudPassword=admin
$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
owncloud-9c8cd68db-xnmzp   1/1     Running   0          91m
owncloud-mariadb-0         1/1     Running   0          91m
```
