### ISSUE TITLE
403 Forbidden with staticSiteConfigmap

### ISSUE THREAD

**Issue by kursattokpinar** [bitnami/charts#3402]
**Which chart**:
nginx:6.0.5

**Describe the bug**
I have a ConfigMap named my-configmap with a single key: members.json, and some json content set as value.
Here is my answers to deploy the chart:
` service.type: NodePort`
` staticSiteConfigmap: my-configmap`

Deployment became completed successfully. Once I try to access to the service via NodePort, it raises 403 Forbidden error.

**To Reproduce**
1. Define a ConfigMap with a single data. For instance, myfile.json: {"somekey": "somevalue"}
2. Deploy the chart with the answers given below:
`service.type: NodePort`
`staticSiteConfigmap: my-configmap`
2. Once the Deployment is done successfully, try to access the Deployment via newly created NodePort service: http://{ip-address-of-the-worker-node}:{3xxxx}/

**Expected behavior**
myfile.json file with the content '{"somekey": "somevalue"}'

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am using RKE cluster and Rancher Server. I have validated that the myfile.json is mounted under /app folder in the container.

**Comment by joancafom** [comment]
Hi @kursattokpinar 

Thanks for your issue. I have been trying to replicate the problem and I think this is because indeed you are not providing any index page nginx can deliver when accessing `/`. Could please try accessing `/myfile.json` instead? It worked for me 😁.

```console
$ echo "NGINX URL: http://$NODE_IP:$NODE_PORT/"
NGINX URL: http://192.168.99.101:30001/

$ curl http://192.168.99.101:30001/member.json                                                                                                                                                  
{"somekey": "somevalue"}
```

Thanks!
