### ISSUE TITLE
[bitmani/mongodb-sharded] Support of mongodb 4.4.x

### ISSUE THREAD

**Issue by achupryn** [bitnami/charts#3406]
**Which chart**:
bitmani/mongodb-sharded

**Describe the solution you'd like**
Add support of Mongodb v4.4

**Comment by carrodher** [comment]
Hi, thanks for letting us know.

First, we need to work on releasing the bitnami/mongodb-sharded Docker image:

- https://github.com/bitnami/bitnami-docker-mongodb-sharded (code)
- https://hub.docker.com/repository/docker/bitnami/mongodb-sharded (image)

Once released the new image version, you will be able to use it in the chart by modifying the values, for example installing the chart with the following parameter: `helm install ... --set image.tag=4.4` or editing the values.yaml. 
When a new major version appears, we are used to waiting sometime before doing this version the default one in the chart, but you can use the new image via the already mentioned workarounds.

**Comment by carrodher** [comment]
The new version was released a couple of days ago, see https://github.com/bitnami/charts/blob/master/bitnami/mongodb-sharded/Chart.yaml#L4. I am closing this issue. Thanks
