### ISSUE TITLE
default install fails with Helm 2.6.0 (function "nindent" not defined)

### ISSUE THREAD

**Issue by toby-1-kenobi** [bitnami/charts#3413]
**Which chart**:
bitnami/redis 10.7.16

**Describe the bug**
Following the TL;DR part of the [README](https://github.com/bitnami/charts/tree/master/bitnami/redis) gave an error on the second command

**To Reproduce**

`$ helm install --name redis bitnami/redis`

> Error: parse error in "redis/templates/redis-with-sentinel-svc.yaml": template: redis/templates/redis-with-sentinel-svc.yaml:11: function "nindent" not defined

**Expected behavior**

installing Redis into my GKE cluster

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:19:25Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by joancafom** [comment]
Hi @toby-1-kenobi 

Thanks for your issue! It seems like you are using a legacy version of Helm that is not compatible with this chart. Please upgrade your version to meet the [prerequisites](https://github.com/bitnami/charts/tree/master/bitnami/redis#prerequisites) 😄.

Thanks!

**Comment by toby-1-kenobi** [comment]
Sorry, my mistake for not reading the prerequisites. I upgraded helm and it works fine.
