### ISSUE TITLE
Enable authentication to elastic and kibana

### ISSUE THREAD

**Issue by adrianovieira** [bitnami/charts#3416]
**Which chart**:
The name (and version) of the affected chart.

`bitnami/elasticsearch (12.6.1 / 7.8.1)`

**Is your feature request related to a problem? Please describe.**
<A clear and concise description of what the problem is. Ex. I am always frustrated when>

I'm trying to deploy both with autentication and TLS/SSL enabled

**Describe the solution you'd like** 

` xpack.security*`

**Describe alternatives you've considered**

none

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by carrodher** [comment]
Hi, thanks for creating this issue but this topic was already discussed in other threads, can you take a look for example at this one https://github.com/bitnami/charts/issues/3208#issuecomment-664158321?
