### ISSUE TITLE
postgresql

### ISSUE THREAD

**Issue by paxinos** [bitnami/charts#3423]
**Which chart**:
postgresql

**Describe the bug**
postgresql 20:07:55.33 
postgresql 20:07:55.33 Welcome to the Bitnami postgresql container
postgresql 20:07:55.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 20:07:55.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 20:07:55.34 
postgresql 20:07:55.34 DEBUG ==> Configuring libnss_wrapper...
postgresql 20:07:55.35 INFO  ==> ** Starting PostgreSQL setup **
postgresql 20:07:55.37 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 20:07:55.38 INFO  ==> Loading custom pre-init scripts...
postgresql 20:07:55.38 INFO  ==> Initializing PostgreSQL database...
postgresql 20:07:55.38 DEBUG ==> Ensuring expected directories/files exist...
postgresql 20:07:55.40 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 20:07:55.40 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
Bus error (core dumped)
child process exited with exit code 135
initdb: removing contents of data directory "/bitnami/postgresql/data"
postgresql 20:07:59.18 INFO  ==> Stopping PostgreSQL...
running bootstrap script ...

**To Reproduce**
helm install --name postgresql bitnami/postgresql -f ./values.yaml 

**Expected behavior**
ahh... running postgresql...

**Version of Helm and Kubernetes**:

Kubernetes 1.17.5 with Rancher

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
- Output of `kubectl version`:

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

Digging into it it seems to be a problem with 'hugetlb', but haven't found a solution.

**Comment by rafariossaa** [comment]
Hi,
  Can you indicate in witch k8s cluster are you running this chart ? Could you provide the parameters used run run the chart ?
  What does make you suspect on `hugetlb`?

**Comment by paxinos** [comment]
Running in an on-prem cluster.   5 worker nodes running ubuntu 18.04.  have 16 cores.  96GB RAM.   And is very lightly loaded at present - just a few small pods.   We do have MySQL running without problem.

Default parameters - nothing changed.    Not setting any cpu/memory limits.

Suspect hugetlb from googling this startup problem.  But have not found any solution that works.   So, just a suspicion.   Open to try any suggestions you may have.

**Comment by rafariossaa** [comment]
Hi,
  The default values in postgresql for `huge_pages` is `try`, maybe you can try providing a config file an setting it to `off`.
  Did you hit this issue with other charts ?

**Comment by paxinos** [comment]
Do you have a pointer how to easily make that change to the PostgreSQL config file?

Haven't run into this before...  happily...

**Comment by rafariossaa** [comment]
Hi,
  Could you take a look to this [link](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#postgresqlconf--pg_hbaconf-files-as-configmap) ?
