### ISSUE TITLE
[bitnami/mariadb] How to use my local gluster-heketi storage class

### ISSUE THREAD

**Issue by huangyingw** [bitnami/charts#3426]
**Which chart**:
mariadb

**Describe the bug**
by default, it is creating pvc: data-mariadb-master-0, data-mariadb-slave-0, which would bound fail. 
How could I configure it to use my STORAGECLASS: gluster-heketi, like another pvc: gluster-pvc did ?
````
➜  setup git:(master) ✗ kubectl get PersistentVolumeClaim
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
data-mariadb-master-0   Pending                                                                                         10h
data-mariadb-slave-0    Pending                                                                                         10h
gluster-pvc             Bound     pvc-1ea05ef2-f7e6-4953-a9e5-c992fc3ab8e3   1Gi        RWX            gluster-heketi   10h
````

**Comment by dani8art** [comment]
Hi @huangyingw thanks for opening the issue, could you try this?

```
--set master.persistence.storageClass=gluster-heketi,slave.persistence.storageClass=gluster-heketi
```

**Comment by huangyingw** [comment]
> Hi @huangyingw thanks for opening the issue, could you try this?
> 
> ```
> --set master.persistence.storageClass=gluster-heketi,slave.persistence.storageClass=gluster-heketi
> ```

cools, it really works, is this the best way to specify my custom setting ? 
if I want to customize through values.yaml, how to make the similar change ?

**Comment by dani8art** [comment]
> is this the best way to specify my custom setting ?

It depends on your requirements, some times the command line is the best option to pass them others you would need to pass them by `values.yaml`, e.g a password would be a good example to be passed by command line and you can use environment variables

```
$ export MY_PASSWORD=my-pass
$ helm install mariadb bitnami/mariadb --set db.password=$MY_PASSWORD
```

> if I want to customize through values.yaml, how to make the similar change ?

Normally, when they are values that have not security risks they could be also passed by `custom-values.yaml` and this will override only the specified values and will use the default values for the rest.

**./custom-values.yaml**
```yaml
db:
  user: my_user
  name: my_database
master:
  persistence:
    storageClass: gluster-heketi
slave:
  persistence:
    storageClass: gluster-heketi
```

```
$ export MY_PASSWORD=my-pass
$ helm install mariadb bitnami/mariadb --values ./custom-values.yaml --set db.password=$MY_PASSWORD
```

**Comment by huangyingw** [comment]
@dani8art thanks so much for such info, it may take me some time to verify your suggestion, for my glusterfs is down now...

**Comment by juan131** [comment]
Hi @huangyingw 

No worries, take your time and do not hesitate to come back to us if you require further help.

**Comment by huangyingw** [comment]
great thanks for this help.  
I have another question about bitnami/wordpress, I want to have a stateful app running.
bellow is my command to run from folder ./bitnami/wordpress/
````
helm dependency update ./
helm install wordpress ./ --values ./custom-values.yaml
````
here is my custom-values.yaml:
````
global:
  storageClass: gluster-heketi
````

after I run 
````
kubectl get svc --namespace default -w wordpress
````

````
I got EXTERNAL-IP pending.
````

so my question is how to specify the external-ip ? 
FYI, I install the Kubernetes in my local ubuntu machine, it is a single-machine Kubernetes cluster for development. I want to use that machine's lan IP, say 192.168.31.91, to used as external-ip. 
how to do this ?

**Comment by juan131** [comment]
Hi @huangyingw 

By default the "service type" used for WordPress is "LoadBalancer", but that type is only supported on certain K8s distros (mainly the ones provided by cloud providers such as Google, Amazon or AKS). This is the reason why it's stuck at "EXTERNAL-IP pending". Find more information in the link below:

- https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

For more information about how to expose externally your WP site, check these links:

- https://github.com/bitnami/charts/tree/master/bitnami/wordpress#wordpress-parameters
- https://github.com/bitnami/charts/tree/master/bitnami/wordpress#ingress

**Comment by huangyingw** [comment]
haha, so far, in order to run the WP chart, I have installed and configured gluster cluster on 3 VM hosted on my local bare-metal server.

In order to expose my WP site, looks like I need to install/configure traefik on my local bare-metal server.
then use the traefik as LoadBalancer, and configure Ingress for WP.

**Comment by juan131** [comment]
Hi @huangyingw 

Our charts are prepared to work with any Ingress Controller such as NGINX, Traefik or Contour. Indeed, we have helm charts to install in your cluster some of them:

- Contour: https://github.com/bitnami/charts/tree/master/bitnami/contour
- Kong: https://github.com/bitnami/charts/tree/master/bitnami/kong (includes the kong-ingress-controller container for managing Ingress resources using Kong)
- NGINX Ingress Controller: https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller

**Comment by huangyingw** [comment]
thanks very much, I will try those, if I have question about Ingress Controller, will open issue separately
