### ISSUE TITLE
[bitnami/mongodb] Mongodb Arbiter pod CrashLoopBackOff and mongodb-0 node did not become available on AWS EKS EC2 instance

### ISSUE THREAD

**Issue by hanif-everycity** [bitnami/charts#3428]
**Description**

Mongodb Arbiter pod CrashLoopBackOff and logs show mongodb-0 node `did not become available` on AWS EKS EC2 instance.

- App Version: 4.2.8
- Chart version: mongodb-8.3.0

**Steps to reproduce the issue:**

```console
$ helm install --namespace="${MONGO_NAMESPACE}" mongo bitnami/mongodb \
  --set architecture=replicaset \
  --set replicaCount=3 \
  --set externalAccess.enabled=true \
  --set externalAccess.service.type=NodePort \
  --set rbac.create=true \
  --set externalAccess.autoDiscovery.enabled=true \
  --set externalAccess.service.nodePorts[0]=30030 \
  --set externalAccess.service.nodePorts[1]=30031 \
  --set externalAccess.service.nodePorts[2]=30032
```

**Describe the results you received:**

After installing MongoDB cluster, **mongo-mongodb-arbiter-0** is restarting frequently and the pod is showing CrashLoopBackOff. The 3 MongoDB pods are running.

**Describe the results you expected:**

**mongo-mongodb-arbiter-0** to be in running state.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here are the results from `kubectl logs`:

```console
mongodb 19:04:31.98
mongodb 19:04:31.98 Welcome to the Bitnami mongodb container
mongodb 19:04:31.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 19:04:31.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 19:04:31.98 
mongodb 19:04:31.99 INFO  ==> ** Starting MongoDB setup **
mongodb 19:04:32.00 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:04:32.01 INFO  ==> Initializing MongoDB...
mongodb 19:04:32.02 INFO  ==> Deploying MongoDB from scratch...
mongodb 19:04:32.70 INFO  ==> Creating users...
mongodb 19:04:32.70 INFO  ==> Users created
mongodb 19:04:32.71 INFO  ==> Writing keyfile for replica set authentication...
mongodb 19:04:32.72 INFO  ==> Configuring MongoDB replica set...
mongodb 19:04:32.73 INFO  ==> Stopping MongoDB...
mongodb 19:04:34.84 INFO  ==> Trying to connect to MongoDB server mongo-mongodb-0.mongo-mongodb-headless.mymongo-db.svc.cluster.local...
mongodb 19:04:34.85 INFO  ==> Found MongoDB server listening at mongo-mongodb-0.mongo-mongodb-headless.mymongo-db.svc.cluster.local:27017 !
**mongodb 19:07:33.34 ERROR ==> Node mongo-mongodb-0.mongo-mongodb-headless.mymongo-db.svc.cluster.local did not become available**
mongodb 19:07:33.34 INFO  ==> Stopping MongoDB..
```

Results from `kubectl describe pod/mongo-mongodb-arbiter-0`:

```console
Warning  Unhealthy  20m (x9 over 5h16m)     kubelet, ip-192-168-48-108.eu-west-1.compute.internal  **Liveness probe failed: dial tcp 192.168.35.125:27017: connect: connection refused**
Warning  Unhealthy  12m (x9 over 5h29m)     kubelet, ip-192-168-48-108.eu-west-1.compute.internal  **Readiness probe failed: dial tcp 192.168.35.125:27017: connect: connection refused**
Warning  BackOff    3m5s (x927 over 5h26m)  kubelet, ip-192-168-48-108.eu-west-1.compute.internal  **Back-off restarting failed container**
```

Here's the statefulset:

```
Name:               mongo-mongodb-arbiter
Namespace:          mymongo-db
CreationTimestamp:  Sat, 15 Aug 2020 14:46:58 +0100
Selector:           app.kubernetes.io/component=arbiter,app.kubernetes.io/instance=mongo,app.kubernetes.io/name=mongodb
Labels:             app.kubernetes.io/component=arbiter
                    app.kubernetes.io/instance=mongo
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=mongodb
                    helm.sh/chart=mongodb-8.3.0
Annotations:        meta.helm.sh/release-name: mongo
                    meta.helm.sh/release-namespace: mymongo-db
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
  Partition:        824640648284
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/component=arbiter
                    app.kubernetes.io/instance=mongo
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=mongodb
                    helm.sh/chart=mongodb-8.3.0
  Service Account:  mongo-mongodb
  Containers:
   mongodb-arbiter:
    Image:      docker.io/bitnami/mongodb:4.2.8-debian-10-r47
    Port:       27017/TCP
    Host Port:  0/TCP
    Liveness:   tcp-socket :mongodb delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  tcp-socket :mongodb delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                          false
      MY_POD_NAME:                             (v1:metadata.name)
      MY_POD_NAMESPACE:                        (v1:metadata.namespace)
      K8S_SERVICE_NAME:                       mongo-mongodb-arbiter-headless
      MONGODB_REPLICA_SET_MODE:               arbiter
      MONGODB_INITIAL_PRIMARY_HOST:           mongo-mongodb-0.mongo-mongodb-headless.$(MY_POD_NAMESPACE).svc.cluster.local
      MONGODB_REPLICA_SET_NAME:               rs0
      MONGODB_ADVERTISED_HOSTNAME:            $(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD:  <set to the key 'mongodb-root-password' in secret 'mongo-mongodb'>    Optional: false
      MONGODB_REPLICA_SET_KEY:                <set to the key 'mongodb-replica-set-key' in secret 'mongo-mongodb'>  Optional: false
      ALLOW_EMPTY_PASSWORD:                   no
    Mounts:                                   <none>
  Volumes:                                    <none>
Volume Claims:                                <none>
Events:                                       <none>`
```

**Comment by juan131** [comment]
Hi @hanif-everycity 

Are the rest of pods up and running? I wasn't able to reproduce it using the same command you used...

```console
$ kubectl get pods -n "${MONGO_NAMESPACE}"
NAME                      READY   STATUS    RESTARTS   AGE
mongo-mongodb-0           1/1     Running   0          3m11s
mongo-mongodb-1           1/1     Running   0          2m31s
mongo-mongodb-2           1/1     Running   0          2m2s
mongo-mongodb-arbiter-0   1/1     Running   0          3m11s
$ kubectl get svc -n mongodb
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
mongo-mongodb-0-external         NodePort    10.35.245.15    <none>        27017:30030/TCP   4m37s
mongo-mongodb-1-external         NodePort    10.35.240.7     <none>        27017:30031/TCP   4m37s
mongo-mongodb-2-external         NodePort    10.35.247.224   <none>        27017:30032/TCP   4m37s
mongo-mongodb-arbiter-headless   ClusterIP   None            <none>        27017/TCP         4m37s
mongo-mongodb-headless           ClusterIP   None            <none>        27017/TCP         4m37s
```

Did you perform any upgrade or did you change the password?

**Comment by hanif-everycity** [comment]
Hi @juan131,

Yes, the other pods are running apart from mongo-mongodb-arbiter-0 constantly going from Running to CrashLoopBackOff .

This is a new install on AWS EKS backed EC2 node.

What does `Readiness probe failed: dial tcp 192.168.35.125:27017: connect: connection refused` mean? Could this be a firewall or security group issue?

I am due to attempt a deployment again and will update this thread.

**Comment by InsOpDe** [comment]
Might be related to #3424
I'm facing the same issue on-premise with these values:
```yaml
fullnameOverride: status-service-db
auth:
  enabled: true
  username: status-service
  database: status-service
  existingSecret: status-service-db-secret
labels:
  service: status-service
architecture: replicaset
replicaSetName: statusservicers
replicaCount: 1
resources:
  limits: {}
  requests: {}

serviceAccount:
  create: false
```
and:
appVersion: 4.2.8
chart-version: 8.2.1

**Comment by juan131** [comment]
Hi @InsOpDe @hanif-everycity 

Does this happens exclusively when using "NodePort"  as "externalAccess.service.type", or are you able to reproduce the issue also when using "LoadBalancer"?

**Comment by InsOpDe** [comment]
Hi @juan131 
Im using the default values except for the snippet above. i.e. `externalAccess.service.type` is `LoadBalancer`.
Maybe I should open an extra issue, since i am not utilizing `externalAccess` at all.

Just updated to Chart version: mongodb-8.3.0 and no remedy.

**Comment by juan131** [comment]
Please open a different issue @InsOpDe 
I'm unable to reproduce the issue, and it seems the original issue reported by @hanif-everycity is related to the external access configuration.

**Comment by kyrylonazarenko** [comment]
The same issue.
App Version: 4.4.1 
Chart version: mongodb-9.2.1

**Comment by kyrylonazarenko** [comment]
> The same issue.
> App Version: 4.4.1
> Chart version: mongodb-9.2.1

As a trick, I was able to deploy first without external access enable = true and without rbac enable true, after replica started successfully I have enabled external access and rbac and upgrade chart

**Comment by rafariossaa** [comment]
Hi,
  Are you using the very same command and using the same kubernetes cluster ?

**Comment by sampouch** [comment]
The same issue.
**App Version: 4.4.1
Chart version: mongodb-9.2.4
Kubernetes: 1.18.8**

Same behavior when deployed on Microsoft Azure and local Docker desktop

**Is it scheduled to fix this bug in the next MongoDb release ?**

**Error :**
**INFO  ==> Found MongoDB server listening at vic-mongo-mongodb-0.vic-mongo-mongodb-headless.mongodb.svc.cluster.local:27017 !
2020-11-10T18:15:49.086589141Z mongodb 18:15:49.08 ERROR ==> Node vic-mongo-mongodb-0.vic-mongo-mongodb-headless.mongodb.svc.cluster.local did not become available
2020-11-10T18:15:49.090644792Z mongodb 18:15:49.08 INFO  ==> Stopping MongoDB...**

values.yaml
```
 architecture: replicaset
 replicaSetName: rs0
 replicaSetHostnames: true
 replicaCount: 3

  # Exposure parameters
  ## External Access to MongoDB nodes configuration
  externalAccess:
    enabled: true
    service:
      type: NodePort
      nodePorts:
        - 30000
        - 30001
        - 30002
    autoDiscovery:
      enabled: false   **Note: has been also tested with this param set to true**
  ##
  ## MongoDB Arbiter parameters.
  ##
  arbiter:
    enabled: true
```

**Comment by juan131** [comment]
Hi everyone!!

Please let's continue the conkerstaion on this issue: https://github.com/bitnami/charts/issues/4073
We're currently tracking the issue with external access and nodeports there.

**Comment by shaileshgaikwad2001** [comment]
Hi Everyone,  

I also faced the same issue and noted that for each deployment, you’ll get a new root password in the corresponding secret. However, the value of this secret gets updated every time you redeploy your ReplicaSet, but the change won’t take effect. This is because ReplicaSets are based on Kubernetes StatefulSets, and if the PVC’s Reclaim Policy is “Delete”, it won’t get deleted by default after you delete your deployment with tools like Helm. This means your “admin” DB and the storedKey (root-password) within it will remain the same as it was during the first deployment.  

To make the changes take effect, you’ll need to manually clean up the PVC resource (and possibly the PV and the physical storage as well). After doing this, my arbiter pod became stable and stopped restarting, as the arbiter pod was trying to connect to the MongoDB pod using the root password, and the new password was mismatching with the old stored password in the key-store of the PVC.
