### ISSUE TITLE
Not able to connect my Domain to static IP address on Google Cloud Platform.

### ISSUE THREAD

**Issue by pMehta1609** [bitnami/charts#3429]
I have deployed "WordPress Certified by Bitnami and Automattic" and have created a DNS record in GCP(Google Cloud Platform) and updated my NameServer to my domain service provider. Still, I am not able to connect my Domain to default static IP URL: http://34.105.78.123/. Please help me.

**Comment by marcosbc** [comment]
Hi @pMehta1609, this doesn't look related to Bitnami Helm charts for Kubernetes, but Bitnami cloud images. Could you post this question in the [Bitnami Community](https://community.bitnami.com)? We'll be glad to help you there!
