### ISSUE TITLE
[bitnami/mongodb-sharded] ServiceAccount can't be set via values.yaml

### ISSUE THREAD

**Issue by krzysztof-miemiec** [bitnami/charts#3432]
**Which chart**:
`bitnami/mongodb-sharded: 1.6.3`

**Is your feature request related to a problem? Please describe.**
I'm using Consul Connect to enable communication between different Data Centers. It requires defining a `serviceAccountName` on pods that are connected with Consul Connect sidecar.

**Describe the solution you'd like**
I'd like to be able to define `serviceAccountName` in the following ways:
- globally (for all pods)
- for `mongos` (this is the most important, as `mongos` is effectively accepting all connections to databases
- for `shardsvr`
- for `configsvr`

**Describe alternatives you've considered**
I managed to overcome this issue for some time, by mounting service account token to `/var/run/secrets/kubernetes.io/serviceaccount`, but it looks like Consul began to check something more than just JWT. It's just simpler to set `serviceAccountName` and let it mount itself automatically.

**Additional context**
N/A

**Comment by marcosbc** [comment]
Hi @krzysztof-miemiec, thanks for reporting this! It looks like a specific use case we need to improve. However, we have a small team and many of us are still on vacations at this moment. In order to speed up the process to get this fixed, we encourage users to submit PRs, would you be up for that?

**Comment by krzysztof-miemiec** [comment]
@marcosbc that was my initial intention, yet I had to find some time (and motivation) to do that 😉
Thanks for encouragement, I hope everything works fine and gets released soon!

BTW: Is there any automation in this repo that can help me validate my work?

**Comment by marcosbc** [comment]
@krzysztof-miemiec For simple changes we rely on linting + installing the chart via GitHub Actions to ensure the chart is properly installed. The linting is added via Git hooks (before pushing to a remote branch), and you can find the available hooks in the `githooks` subdirectory.

If the changes were more complex and affected more parts of the chart, we would also launch an automated testing job in our internal CI, and get back to you in case we find any blockers.
