### ISSUE TITLE
[bitnami/dokuwiki] Upgrading from 8.0.3 to 9.01 fails with internal PHP errors

### ISSUE THREAD

**Issue by Be-El** [bitnami/charts#3433]
**Which chart**:
bitname dokuwiki 9.0.1

**Describe the bug**
I tried to upgrade a running installation based on the bitnami/dokuwiki chart version 8.0.3 to version 9.0.1, which also includes a major dokuwiki upgrade. Extra helm configuration only contains settings for ingress and storage, no extra dokuwiki configuration. Plugins, data and configuration files generated by dokuwiki itself are stored on a volume that is also used in the upgrade container.

The apache server within the deployment started, but run into PHP errors upon requests:
[Thu Aug 13 09:50:10.703067 2020] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
[Thu Aug 13 09:50:41.247783 2020] [php7:error] [pid 90] [client X.X.X.X:54820] PHP Fatal error: Uncaught Error: Class 'dokuwiki\plugin\config\core\Setting\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61
X.X.X.X - - [13/Aug/2020:09:50:41 +0000] "GET /doku.php HTTP/1.1" 500 -
[Thu Aug 13 09:50:51.118657 2020] [php7:error] [pid 91] [client X.X.X.X:54902] PHP Fatal error: Uncaught Error: Class 'dokuwiki\plugin\config\core\Setting\Setting' not found in /opt/bitnami/dokuwiki/inc/deprecated.php:61\nStack trace:\n#0 /opt/bitnami/dokuwiki/inc/load.php(38): require_once()\n#1 /opt/bitnami/dokuwiki/inc/init.php(200): require_once('/opt/bitnami/do...')\n#2 /opt/bitnami/dokuwiki/doku.php(36): require_once('/opt/bitnami/do...')\n#3 {main}\n thrown in /opt/bitnami/dokuwiki/inc/deprecated.php on line 61
X.X.X.X - - [13/Aug/2020:09:50:51 +0000] "GET /doku.php HTTP/1.1" 500 -

Reverting back to 8.0.3 works and the service was accessible again.

**To Reproduce**
1. Install dokuwiki with chart version 8.0.3
2. Verify that dokuwiki is working
3. Upgrade the installation to 9.0.1
4. Access dokuwiki

**Expected behavior**
A working web interface

**Version of Helm and Kubernetes**:
Kubernetes 1.18.3 via Rancher 2.4.5, integrated helm, deployment via rancher web ui and bitnami helm catalog

**Additional context**

The issue is also reported as splitbrain/dokuwiki#3229

**Comment by Be-El** [comment]
Hi,

with some feedback from the dokuwiki developers, I was able to get dokuwiki up and running.

The problem itself is already known for some time: splitbrain/dokuwiki#791

The plugin directory contains both locally installed plugins and plugins bundled with the application itself. Since it is usually located in an extra volume, the bundled plugins are not updated correctly if the docker container itself is updated and replaced with a container running a newer dokuwiki release.

The proposed solution is splitting the plugin directory into a part with the bundled plugins (taken from the dokuwiki release), and the user defined plugins from a volume. Not sure how much work is needed for this, I'm not a php developer.

**Comment by marcosbc** [comment]
Hi @Be-El, I'm not sure that we should rename the plugin files and then create symlinks, since it points to an actual upstream issue in DokuWiki (bundling plugins at build time that are unsupported between different updates), which you linked above (https://github.com/splitbrain/dokuwiki/issues/791).

In any case, the Bitnami DokuWiki container is prepared to handle such scenarios if you do the following on your side in your Dockerfile:

* Rename `plugins` to `plugins.bundled`
* Create `plugins` folder and add symlinks from folders in `plugins.bundled` to the `plugins` directory (make sure to be using absolute paths)

Alternatively, you could always avoid persisting plugins by setting the environment variable `DOKUWIKI_DATA_TO_PERSIST` to the same value as before except the plugins directory.
