### ISSUE TITLE
[bitnami/kafka] Incorrect loadBalancerSourceRanges is set to external service

### ISSUE THREAD

**Issue by yoichiwo7** [bitnami/charts#3434]
**Which chart**:
The name (and version) of the affected chart

```
name: kafka
version: 11.8.0
appVersion: 2.6.0
```

**Describe the bug**

externalAccess uses service's `loadBalancerSourceRanges` instead of its own `loadBalancerSourceRanges`.
Because of this, incorrect `loadBalancerSourceRanges` is set to external service.

https://github.com/bitnami/charts/blob/1bab26ecff639528cbcead8e9fcea46e906ad5c8/bitnami/kafka/templates/svc-external-access.yaml#L34-L35

**To Reproduce**

1. Set `externalAccess.enabled: true`
2. Set service's `loadBalancerSourceRanges` to empty value.
3. Set externalAccess's `loadBalancerSourceRanges` to non-empty value.
4. Install the chart

After installation, the external service has no `loadBalancerSourceRanges` set.

**Expected behavior**

External service must set its `loadBalancerSourceRanges` based on externalAccess's `loadBalancerSourceRanges`.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

none

**Comment by dani8art** [comment]
Hi @yoichiwo7 thanks for opening the issue, I recently opened a PR that fixes this. Please, let's move the conversation there.
