### ISSUE TITLE
extraHosts issue in ingress in aspnet core

### ISSUE THREAD

**Issue by BaskaranSelvaraj** [bitnami/charts#3436]
**Which chart**:
aspnet-core

**Describe the bug**

when i provide the below mentioned value in the values.yaml file:

```yaml
Ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /health/status
  extraHosts:
    - name: testing
       path: test
```

exception details :
```
Error: template: aspnet-core/templates/health-ingress.yaml:37:30: 
executing "aspnet-core/templates/health-ingress.yaml" at <include "aspnet-core.fullname" .>: 
error calling include: template: aspnet-core/templates/_helpers.tpl:8:4: 
executing "aspnet-core.fullname" at <include "common.names.fullname" .>: 
error calling include: template: aspnet-core/charts/common/templates/_names.tpl:22:14: 
executing "common.names.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```

**Expected behavior**

chart should allow to add the extraHosts in the ingress 

**Version of Helm and Kubernetes**:
helm3 
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4"}
```
**Additional context**
Getting the exception using the "helm template"
Note: change the "range" to "if" in the line 31 is working fine but its not a correct solution.

**Comment by juan131** [comment]
Thanks so much for reporting the issue! I just created a PR to address it
