### ISSUE TITLE
[bitnami/postgres-ha] Support for WAL archiving

### ISSUE THREAD

**Issue by lpaarup** [bitnami/charts#3437]
**Which chart**:
bitnami/postgres-ha version 3.4.9

**Is your feature request related to a problem? Please describe.**
I'm looking for a postgresql helm chart that has both HA and easy Backup and Restore procedures. I found this one really good at the first point but I'm having some problems to understand if it is possible to do Point in Time Recovery.

I know how to perform base backups at periodic intervals using postgresql libaries such as pgbasebackup, but if I get a crash in between backups, I don't know how to get from the latest backup to the crash timestamp. WAL files would help in that process, but I don't see a way to persist them outside the containers in case they restart.

**Describe the solution you'd like**
Having a storageClass or PVC value where the master would write the WAL files. In the end, what I would like is to have the WAL files written to a persistent storage so that I can recover from them in case the data segment and the pods crash.

**Describe alternatives you've considered**
I've seen that the bitnami/postgresql chart provides the ability to define extraVolumes and extraVolumeMounts from the values. In that way I could mount a directory inside the container to a PV and define that directory as the WAL archiving destination. Then, I would always have the latest WAL entries even after a failure.

I don't know if there is a reason why this is not implemented in this chart or if there is any reason why WAL archiving is not supported out of the box.

**Additional context**

**Comment by marcosbc** [comment]
Hi @lpaarup, note that the Bitnami PostgreSQL HA chart already persists any data stored in the PostgreSQL data directory (`/bitnami/postgresql/data`), and WAL data is stored in the `pg_wal` subdirectory (`/bitnami/postgresql/data/pg_wal`). In case of a failure, the data would be obtainable from that volume like any other file in that volume.

In any case, it wouldn't hurt to use a separate volume for WAL-specific data. For such changes we encourage users to contribute to Bitnami charts, we'll always be glad to review any external contributions. That would also allow this change to be implemented a lot quicker than by conventional means.

**Comment by lpaarup** [comment]
Thank you @marcosbc. Yes, I understand that in case of a pod restart, the WAL files will still be persisted in pg_wal directory in the data segment (in a Persistent Volume). However, my concern is in case I lose the data in the Persistent Volume. In that case I'm losing everything (including the pg_wal directory).

In that case, I would need to repopulate the data PV using a backup. Imagine that backup is from 3pm and the data loss occurs at 5pm. The pg_wal directory will contain the WAL files until 3pm and everything up to 5pm will be unrecoverable.

If I had a way to mount another volume, I could store the WAL files in another location (in real-time, not during the backup). If I then have a backup from 3pm and a data loss at 5pm, I could recover the data segment from 3pm and use the WAL files (which are in another volume and I assume they are not lost) to recover until 5pm.

I could happily contribute with the extraVolumes and extraVolumeMounts, but I just wanted to know if it is something in progress by someone else (as mentioned in #2363).

**Comment by marcosbc** [comment]
Thanks for the detailed explanation, we understand your use case now and it makes a lot of sense.

Unfortunately we have not started working on the issue mentioned in #2363, so if you could contribute the feature it would be great!

**Comment by arush-sal** [comment]
I suppose this simple can be achieved by adding the following your values.yaml:

```yaml
postgresqlConfiguration:
  archive_mode: 'on'
  wal_level: <level>
  archive_command: <your_command>
  archive_timeout: <a sane interval>
```
