### ISSUE TITLE
fatal unsupported certificate: unable to connect to redis via redis-cli when tls and authclient are both enabled.

### ISSUE THREAD

**Issue by gopaljayanthi** [bitnami/charts#3440]
**Which chart**:
bitnami/redis 10.7.16
**Describe the bug**
Unable to connect to tls enabled authclient enabled redis with redis-cli
opnssl s_client gives this error

No client certificate CA names sent
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
SSL handshake has read 2835 bytes and written 2876 bytes
Verification: OK
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
read from 0x5631cabb84f0 [0x5631cabc2fb3] (5 bytes => 5 (0x5))
0000 - 17 03 03 00 13 .....
read from 0x5631cabb84f0 [0x5631cabc2fb8] (19 bytes => 19 (0x13))
0000 - 48 b3 ef 66 b7 a1 80 7d-a3 d1 3d e6 19 0e 83 4b H..f...}..=....K
0010 - 00 1e 6b ..k
**SSL3 alert read:fatal:unsupported certificate**
139629142873216:error:14094413:SSL routines:ssl3_read_bytes:sslv3 alert unsupported certificate:../ssl/record/rec_layer_s3.c:1544:SSL alert number 43
read from 0x5631cabb84f0 [0x5631cabad3d0] (8192 bytes => -1 (0xFFFFFFFFFFFFFFFF))

and on the server side I am seeing this error

**Error accepting a client connection: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed**

When i use openssl s_server , then i am able to connect using openssl s_client with the same certs
openssl verify -CAfile ca.crt server.crt returns OK.
 

**To Reproduce**
1. kubectl create secret generic redis-tls --from-file ca.crt --from-file clouddriver.key --from-file clouddriver.crt
2.  edit values.yml to set tls true (values.yml is attached as redistls-values.txt , also note TLSv1_3 is enabled)
[redistls-values.txt](https://github.com/bitnami/charts/files/5084941/redistls-values.txt)

3. helm install redis bitnami/redis -f values.yml
4. create a redis-cli client from instructions after helm install completes. EXEC into the redis-client pod and run 

5.  redis-cli -h red5-redis-master.red.svc.cluster.local -p 6379 -a RBsr0TaNMt  --tls --cert /tmp/clouddriver.crt  --key /tmp/clouddriver.key  --cacert /tmp/ca.crt
enter ping when prompted and the server disconnects.
6. openssl s_client -connect red5-redis-master.red.svc.cluster.local -port 6379 -key /tmp/clouddriver.key -cert /tmp/clouddriver.crt -CAfile /tmp/ca.crt
ssl session is not established

**Expected behavior**
redis-cli -h red5-redis-master.red.svc.cluster.local -p 6379 -a XXXXXX  --tls --cert /tmp/clouddriver.crt  --key /tmp/clouddriver.key  --cacert /tmp/ca.crt
gives a redis command prompt, when you type ping , PONG should be the output

openssl s_client -connect red5-redis-master.red.svc.cluster.local -port 6379 -key /tmp/clouddriver.key -cert /tmp/clouddriver.crt -CAfile /tmp/ca.crt
an ssl session will be established.

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
 helm version
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

```
- Output of `kubectl version`:

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-14f01f", GitCommit:"14f01fe8f04411d5e187b220034ca2117d79f7de", GitTreeState:"clean", BuildDate:"2020-05-23T21:32:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Trying to connect to redis  using rediss protocol from spinnaker
the certificates were created using the following commands

openssl req -new -newkey rsa:2048 -nodes -keyout rootprivkey.pem -out rootreq.pem -config ca.cnf
touch index
echo 01 > serial.txt
openssl ca -out rootcrt.pem -days 2652 -keyfile rootprivkey.pem -selfsign -config ca.cnf -extensions ca_ext -in rootreq.pem -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1
openssl x509 -in rootcrt.pem -text -noout
openssl req -new -newkey rsa:2048 -keyout serverprivkey.pem -out serverreq.pem -config server.cnf -nodes
openssl ca -in serverreq.pem -days 1200 -cert rootcrt.pem -keyfile rootprivkey.pem -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out servercrt.pem -config ca.cnf

cp rootcrt.pem ca.crt
cp serverprivkey.pem clouddriver.key
cp servercrt.pem clouddriver.crt

kubectl create secret generic redis-tls --from-file ca.crt --from-file clouddriver.key --from-file clouddriver.crt

the CA cert has CA=true enabled and the other have CA=false.  X509 extensions are also set fro keyusage, extendedkeyusage and subjectalternate names
The ca.cnf and server.cnf are also attached.
[ca.txt](https://github.com/bitnami/charts/files/5084912/ca.txt)
[server.txt](https://github.com/bitnami/charts/files/5084913/server.txt)

**Comment by andresbono** [comment]
Hi @gopaljayanthi, in the steps to reproduce the issue, I noticed that you are using `stable/redis`. Please note the previous chart is no longer under maintenance. Last commit is from 5 months ago: https://github.com/helm/charts/pull/21333. You should instead use `bitnami/redis`: https://github.com/bitnami/charts#tldr

Please, let us know if you still find the issue with the latest version of the chart.

**Comment by gopaljayanthi** [comment]
Hi Andres
We areusing bitnami/redis not stable/redis
I corrected the issue in github.

Thanks
Gopal

**Comment by gopaljayanthi** [comment]
Please reopen issue, I mistyped stable/redis instead of bitnami/redis

**Comment by andresbono** [comment]
Hi again @gopaljayanthi, thanks for confirming it.

I have tried to reproduce your issue with some convenient sample tls certs that you can find here: [OpenVPN/openvpn - sample-keys](https://github.com/OpenVPN/openvpn/tree/master/sample/sample-keys). I'd say that the main issue you are facing is that you are not using public/private certificates but only the private part (server). When using the redis-client, the public part of the certificates is expected instead of the private one. See the following commands for reference:

```
curl -sLO https://raw.githubusercontent.com/OpenVPN/openvpn/master/sample/sample-keys/ca.crt
curl -sLO https://raw.githubusercontent.com/OpenVPN/openvpn/master/sample/sample-keys/server.crt
curl -sLO https://raw.githubusercontent.com/OpenVPN/openvpn/master/sample/sample-keys/server.key
curl -sLO https://raw.githubusercontent.com/OpenVPN/openvpn/master/sample/sample-keys/client.crt
curl -sLO https://raw.githubusercontent.com/OpenVPN/openvpn/master/sample/sample-keys/client.key

kubectl create secret generic redis-tls --from-file ca.crt --from-file server.key --from-file server.crt

cat <<EOF >values.yaml
cluster:
  enabled: false

tls:
  enabled: true
  authClients: true
  certificatesSecret: redis-tls
  certFilename: server.crt
  certKeyFilename: server.key
  certCAFilename: ca.crt

master:
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
EOF

helm install redis bitnami/redis -f values.yaml

export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)
kubectl run redis-client --restart='Never' --env REDIS_PASSWORD=$REDIS_PASSWORD --image docker.io/bitnami/redis:6.0.6-debian-10-r10 --command -- sleep infinity
kubectl cp --namespace default client.crt redis-client:/tmp/client.crt
kubectl cp --namespace default client.key redis-client:/tmp/client.key
kubectl cp --namespace default ca.crt redis-client:/tmp/ca.crt

kubectl exec -ti redis-client -- redis-cli -h redis-master -a $REDIS_PASSWORD --tls --cert /tmp/client.crt --key /tmp/client.key --cacert /tmp/ca.crt
```

Could you please generate the public part of the certs to use it with the client?

Also note that in the `values.yaml`, I have disabled the readiness and liveness probes to avoid the master pod being restarted when enabling client authentication. We will be checking if there is something we can do to improve this behavior.

**Comment by gopaljayanthi** [comment]
THis worked great. Now I am able to connect using redis-cli. THanks for the help, I am now connecting to the redis using a java application. ( part of spinnaker). I updated the truststore to contain the ca.crt and the keystore to contain client.p12.  I am unable to connect with the server showing these errors
Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=8)

If needed I can create a new issue.

**Comment by andresbono** [comment]
Hi @gopaljayanthi, it's great that it worked for you! Please make sure that you generate your own certificates and keys, the ones downloaded in my snippet are only intended to be used for testing purposes.

Do you think your new issue is related to the way you are creating the certificates? If so, I'm not sure if we will be able to help you on that. You might want to check the script that generates the sample certificates: https://github.com/OpenVPN/openvpn/blob/master/sample/sample-keys/gen-sample-keys.sh There you can see the openssl commands used to create all the files.
