### ISSUE TITLE
After Installation of Bitnami wordpress, the initial password is not working

### ISSUE THREAD

**Issue by kdutta76** [bitnami/charts#3443]
HI ,

After Installation of Bitnami WordPress, the initial password is not working.
I have tried multiple times..
Site address
http://34.105.11.80/ 
Admin URL
http://34.105.11.80//wp-admin/ 
Instance- mydigitalstore1-vm
Ione- us-west1-b

**Comment by beltran-rubo** [comment]
Hi,

That is not a Helm Chart, that looks a Bitnami VM launched from Google Marketplace. Those images create a random password at boot time and you can get from the Google dashboard. Please check this guide and see if the password you get from the Google Console works properly https://docs.bitnami.com/google/faq/get-started/find-credentials/

**Comment by kdutta76** [comment]
HI,

Yes I have used the same path and used admin id as user and password as
mentioned in the Admin password( temporary)

**Comment by beltran-rubo** [comment]
It looks like there are to slashes in the URL, could you please check at http://34.105.11.80/wp-admin/

**Comment by kdutta76** [comment]
Great... it worked..
I also did not notice..
