### ISSUE TITLE
Does latest mongodb helm chart support Mongodb 3.6.x ?

### ISSUE THREAD

**Issue by lexual** [bitnami/charts#3446]
Hi,

Not clear from the documentation is Mongodb 3.6.x is still supported by the latest helm chart.

Can I just change the image.tag to a mongodb 3.6.x one and it will work?

thanks,

;)

**Comment by marcosbc** [comment]
Hi @lexual, we don't test MongoDB 3.6 internally with the current chart, but it should work without many problemsa as the inputs for the container (environment variables) are the same. Let us know if you find any issues.

**Comment by lexual** [comment]
Hi,

Have tried by setting image.tag to `3.6.19-debian-9-r9`

Whether in architecture set to standalone or replicaset, it comes up, but the pods continually restart.
Couldn't see anything obvious in the logs that showed up.

Any tips on how to debug this further?

[logs-csv.txt](https://github.com/bitnami/charts/files/5090065/logs-csv.txt)

**Comment by lexual** [comment]
Turns out the liveness probess rely upon pgrep which is part of procps debian packages.

These aren't available in the debian9 based 3.6 images currently, so the liveness probes fail, and the pods get continually restarted. Will raise PR on docker iamge to add procps ;)
