### ISSUE TITLE
[bitnami/postgresql] Failed to update with helm3 due to immutable value clusterIP

### ISSUE THREAD

**Issue by dev-kpyc** [bitnami/charts#3447]
Updating the postgresql chart fails due to attempting to change an immutable value

Steps to reproduce:

* `svc-headless.yaml` specifies `service.clusterIP: None`
* On first deploy, k8s automatically assigns `service.clusterIP` to some IP
* On upgrade, the chart attempts to replace this value gain with `None`

Error: `spec.clusterIP: Invalid value: "": field is immutable`

See: https://github.com/helm/helm/issues/6378

**Comment by mkmrah** [comment]
Yes.. I have also noticed the same and was about to raise ticket then noticed this issue.

1. helm install parse-chart /Users/mkm/Developer/bitnami/helm/parse-10.3.0.tgz 
2. The pods will be up and running
3. Later when you tried to upgrade the chart version to latest
```
helm upgrade parse-chart /Users/mkm/Developer/bitnami/helm/parse-11.0.4.tgz
```

The following error noticed

```
Error: UPGRADE FAILED: cannot patch "node-chart-mongodb" with kind Deployment: Deployment.apps "node-chart-mongodb" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"mongodb", "app.kubernetes.io/instance":"node-chart", "app.kubernetes.io/name":"mongodb"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

```

Similar Upgrade error noticed for these charts as well
* postgresql
* harbor
* grafana
* ghost

Refer this comment https://github.com/helm/helm/issues/6378#issuecomment-557746499 and as per this changes required in chart template to make it work for helm3.

Also there is open ticket with helm https://github.com/helm/helm/issues/7956

**Comment by andresbono** [comment]
Hi @dev-kpyc, @mkmrah, thanks for reporting this issue. Are you experiencing the problem when performing upgrades between major versions of the charts only? For example in the steps to reproduce the issue with parse, the version is upgraded from `10.3.0` to `11.0.4`. If you check the [notable changes](https://github.com/bitnami/charts/tree/master/bitnami/parse#to-1100):

> Backwards compatibility is not guaranteed since breaking changes were included in MongoDB subchart.

**Comment by dev-kpyc** [comment]
I think it applies to any update

**Comment by mkmrah** [comment]
@andresbono thanks for looking into this. I noticed this issue while upgrading from 10.3.0 to 11.0.4. you can also try with other version upgrade using the steps mentioned above.

**Comment by andresbono** [comment]
@dev-kpyc, we can't reproduce the with PostgreSQL. We tried the following:

```
$ helm install test bitnami/postgresql --version 9.1.1

$ kubectl get svc/test-postgresql-headless
NAME                       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
test-postgresql-headless   ClusterIP   None         <none>        5432/TCP   32s

$ helm upgrade test bitnami/postgresql --version 9.2.1 --set postgresqlPassword=$POSTGRESQL_PASSWORD
```

As you can see, there is no IP assigned to the _ClusterIP_ service. When you set `.spec.clusterIP: None` the service is considered headless and, by definition, a cluster IP is not allocated: [docs](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services). How is it possible that this happens?:

> Steps to reproduce:
> 
> * `svc-headless.yaml` specifies `service.clusterIP: None`
> * On first deploy, k8s automatically assigns `service.clusterIP` to some IP

I can only think that the failing service is not the headless one but `svc.yaml`. Could you confirm that? Can you also let us know what are the input parameters (values) that you are using to deploy and upgrade the chart?

**Comment by andresbono** [comment]
@mkmrah, we double checked all the applications that you reported in your previous comment. All of then went well when upgrading version between the same major. To check all the versions you can execute:

```
$ helm search repo bitnami/parse --versions
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/parse	11.0.4       	4.3.0      	Parse is a platform that enables users to add a...
bitnami/parse	11.0.3       	4.3.0      	Parse is a platform that enables users to add a...
bitnami/parse	11.0.2       	4.3.0      	Parse is a platform that enables users to add a...
bitnami/parse	11.0.1       	4.2.0      	Parse is a platform that enables users to add a...
bitnami/parse	10.3.19      	4.2.0      	Parse is a platform that enables users to add a...
bitnami/parse	10.3.18      	4.2.0      	Parse is a platform that enables users to add a...
...
```

| chart | major version | initial version | upgraded version | results | 
| --- | --- | --- | --- | --- |
| bitnami/parse | 11 | 11.0.1 | 11.0.4 | OK |
| bitnami/postgresql | 9 | 9.1.1 | 9.2.1 | OK |
| bitnami/harbor | 7 | 7.0.0 | 7.1.0 | OK |
| bitnami/grafana | 3 | 3.0.1 | 3.4.0 | OK |
| bitnami/ghost | 10 | 10.0.0 | 10.1.0 | OK |

What we did was executing the `helm install` and `helm upgrade` in a similar way that in https://github.com/bitnami/charts/issues/3447#issuecomment-676367548.

In addition to this manual check that we have done, our CI/CD systems test that the upgrade is successful for Helm 2 and Helm 3.

**Comment by mkmrah** [comment]
> @mkmrah, we double checked all the applications that you reported in your previous comment. All of then went well when upgrading version between the same major. To check all the versions you can execute:
> 
> ```
> $ helm search repo bitnami/parse --versions
> NAME         	CHART VERSION	APP VERSION	DESCRIPTION
> bitnami/parse	11.0.4       	4.3.0      	Parse is a platform that enables users to add a...
> bitnami/parse	11.0.3       	4.3.0      	Parse is a platform that enables users to add a...
> bitnami/parse	11.0.2       	4.3.0      	Parse is a platform that enables users to add a...
> bitnami/parse	11.0.1       	4.2.0      	Parse is a platform that enables users to add a...
> bitnami/parse	10.3.19      	4.2.0      	Parse is a platform that enables users to add a...
> bitnami/parse	10.3.18      	4.2.0      	Parse is a platform that enables users to add a...
> ...
> ```
> 
> chart	major version	initial version	upgraded version	results
> bitnami/parse	11	11.0.1	11.0.4	OK
> bitnami/postgresql	9	9.1.1	9.2.1	OK
> bitnami/harbor	7	7.0.0	7.1.0	OK
> bitnami/grafana	3	3.0.1	3.4.0	OK
> bitnami/ghost	10	10.0.0	10.1.0	OK
> What we did was executing the `helm install` and `helm upgrade` in a similar way that in [#3447 (comment)](https://github.com/bitnami/charts/issues/3447#issuecomment-676367548).
> 
> In addition to this manual check that we have done, our CI/CD systems test that the upgrade is successful for Helm 2 and Helm 3.

@andresbono Can you please try upgrade parse chart from 10.3.0 to 11.0.4 and see you also get similar error what we reported here?

**Comment by dev-kpyc** [comment]
I didn't attempt updating again since a couple days ago. We're using skaffold with postgres as a dependency, so I moved postgres to a separate chart (not a dependency) and added `remote: true` to the configuration so that skaffold doesn't try to redeploy postgres. That fixed the issue for me. If I get some time I'll try again

**Comment by andresbono** [comment]
@mkmrah, in that case, yes, the error message is exactly the same for us. The error is caused by the MongoDB chart, a chart dependency of Parse:

- `bitnami/parse 10.3.0` requires `bitnami/mongodb  7.4.5`
- `bitnami/parse 11.0.4` requires `bitnami/mongodb  8.2.3`

The key here is that those versions are not intended to be upgraded automatically (`helm upgrade`) because they introduce incompatible changes with the previous versions, hence we bumped the version of the charts as major (bitnami/parse `10.x.x` -> `11.x.x`, bitnami/mongodb `7.x.x` -> `8.x.x`). We treat our versions following semantic versioning conventions: https://semver.org/#summary.

When major changes are required, we add a note in the readme, to offer some guidance to upgrade when is needed:

- [bitnami/parse: To 11.0.0](https://github.com/bitnami/charts/tree/master/bitnami/parse#to-1100)
- [bitnami/mongodb: To 8.0.0](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#to-800)

Here you can find a similar issue: https://github.com/bitnami/charts/issues/3201

I hope this information helps.

**Comment by mkmrah** [comment]
@andresbono Thanks for sharing the details. I have done some extensive testing with some of the charts and here is my findings

1. I was able to install the parse-3.9.0 chart with helm3 and then was able to upgrade till 4.1.0 (3.9.0 --> 3.10.0 --> 4.1.0).
2. But from  parse-4.1.0 -->4.2.0 version upgrade failed with below error

````
 2020/08/17 16:12:25 Terraform apply | Error: cannot patch "parse34-51e2-45-mongodb" with kind Deployment: Deployment.apps "parse34-51e2-45-mongodb" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"mongodb", "app.kubernetes.io/instance":"parse34-51e2-45", "app.kubernetes.io/name":"mongodb"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
````

3. Grafana below chart versions upgrade failed

```
1.3.3. --> 3.4.0.
1.6.1 --> -3.4.0.
1.2.4. --> 3.4.0.
1.1.4 --> 3.4.0
```
with this error message

```
cannot patch "grafanae2-24b6-41" with kind Deployment: Deployment.apps "grafanae2-24b6-41" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"grafana", "app.kubernetes.io/instance":"grafanae2-24b6-41", "app.kubernetes.io/name":"grafana"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
4. postgresql below chart versions upgrade failed 

```
7.1.0. --> 9.1.4
8.3.3 --> 9.1.4
8.9.6 --> 9.1.4
```
error message

```
cannot patch "postgresql49-5975-49-postgresql" with kind StatefulSet: StatefulSet.apps "postgresql49-5975-49-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

Can you please confirm all these failures also due MongoDB chart version?

**Comment by mkmrah** [comment]
@andresbono 
4.2.0 maps to parse-11.0.2.tgz and 4.3.0 maps to parse-11.0.3.tgz

Please keep this ticket open till we complete our testing.

**Comment by andresbono** [comment]
Yes, we will keep this issue open. Please let us know if the command `kubectl delete statefulsets.apps --cascade=false postgresql-postgresql` was of any help.

**Comment by andresbono** [comment]
Hi @mkmrah, any updates on the issue?
