### ISSUE TITLE
Airflow Chart - How to integrate Google OAuth

### ISSUE THREAD

**Issue by pankajkoti** [bitnami/charts#3456]
How can we have the chart use Google OAuth for authentication of users?

**Comment by andresbono** [comment]
Hi @pankajkoti, we haven't explored that option, you can find documentation about it in the Apache Airflow Documentation:

https://airflow.apache.org/docs/stable/security.html#google-authentication

**Comment by pankajkoti** [comment]
hi, okay, how to pass this variables to the helm chart and especially how I can safely pass the client_secret?

**Comment by andresbono** [comment]
Hi @pankajkoti, you can find convenient the `airflow.webserverConfigMap` parameter: 

> Config map name for ~/airflow/webserver_config.py

See the README for more details on the different options that the chart support: https://github.com/bitnami/charts/tree/master/bitnami/airflow#parameters

**Comment by pankajkoti** [comment]
> Hi @pankajkoti , were you successful in integrating Google OAuth in to Airflow 2.0? I have a ConfigMap with contents from a customized `webserver_config.py` that is mounted on my web server pod, but the pod continuously enters in to CrashLoopBackOff and the logs do not even indicate what might be going wrong.

Hi @dontspamterry No, I could not. What we did is put Airflow behind Nginx Ingress and integrated Nginx ingress with Google OAuth.

**Comment by dontspamterry** [comment]
Ah, ok, @pankajkoti . Thanks for responding! So you disabled all auth in Airflow completely since your nginx ingress now handles the authentication?

**Comment by pankajkoti** [comment]
> Ah, ok, @pankajkoti . Thanks for responding! So you disabled all auth in Airflow completely since your nginx ingress now handles the authentication?

Yes correct, the Airflow is inside VPC and is not exposed directly to the public.

**Comment by dontspamterry** [comment]
> > Ah, ok, @pankajkoti . Thanks for responding! So you disabled all auth in Airflow completely since your nginx ingress now handles the authentication?
> 
> Yes correct, the Airflow is inside VPC and is not exposed directly to the public.

awesome. Thank you for confirming!!
