### ISSUE TITLE
Airflow Chart -  Request to support custom templates

### ISSUE THREAD

**Issue by pankajkoti** [bitnami/charts#3457]
Hi Team, we use SOPS for secrets. We would like to decrypt secrets from our sops file and need a custom template for this. I tried adding this template by creating a templates/ directory but looks like it's not accepted. Can this be supported?

**Comment by rafariossaa** [comment]
Hi,
  We don't use SOPS for the secrets, but as as far as I can see, it seems you need to decrypt the secrets before launching the chart.
  Could you elaborate a bit more on how this is used and which changes you have tried and what is needed ? 
  I am not sure but, maybe something can be done.

**Comment by pankajkoti** [comment]
Okay, so we have a secrets file based on SOPS. And I would like to add a templates file to evaluate this sops file and deploy secrets to the cluster.
The template would be something like this:
{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
  name: {{ include "airflow.fullname" . }}
  
  labels:
    app: {{ template "airflow.name" . }}
    component: web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc}}
{{- end }}
{{- end }}




How can I add this template?

**Comment by pankajkoti** [comment]
Okay, so it worked, please ignore and close this issue
