### ISSUE TITLE
[bitnami/rabbitmq] Adding Federated Resources does not work

### ISSUE THREAD

**Issue by kemra102** [bitnami/charts#3459]
**Which chart**:
rabbitmq 7.6.0

**Describe the bug**
I have defined my RabbitMQ resources to be loaded into RabbitMQ using the provided `loadDefinition`/`existingConfiguration` setup. On the whole this works fine until I add resources (`parameters` & `policies`) that have a component/definition of `federation-upstream`. This cause the container to error out with an error like this:

```
2020-08-18 11:05:54.766 [error] <0.865.0> exit:{error,<<"Validation failed\n\ncomponent federation-upstream not found\n (MOVIDA/federation-upstream/cm-movida-events)">>}
exit:{error,<<"Validation failed\n\ncomponent federation-upstream not found\n (MOVIDA/federation-upstream/cm-movida-events)">>}
```

On a "standard" RabbitMQ install this would simply mean that the Federation plugins haven't been enabled (& `rabbitmq-server` restarted). I added the `rabbitmq_federation` & `rabbitmq_federation_management` plugins via `extraPlugins` but I still get the exact same error as above.

**To Reproduce**
1. Create a deployment that adds in RabbitMQ resources at startup that include Federated resources.
2. Try to create the deployment.

**Expected behavior**
RabbitMQ should start up and all resources (including federated ones) should have been created.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-fd1ea7", GitCommit:"fd1ea7c64d0e3ccbf04b124431c659f65330562a", GitTreeState:"clean", BuildDate:"2020-05-28T19:06:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I don't think it's relevant but our rollout of this Helm chart is being managed by Terraform:
```
Terraform v0.12.24
```

**Comment by javsalgar** [comment]
Hi,

Do you have an example configuration that triggers the error? It would be very helpful for us to reproduce.

**Comment by kemra102** [comment]
The error is complaining about this `parameter` (we have others like it):

```
"parameters": [
        {
            "vhost": "MOVIDA",
            "name": "product-movida-events",
            "component": "federation-upstream",
            "value": {
                "uri": "amqp://movida:${rabbitmq_federation_product_movida_pass}@mq.${env}.product.example.com/MOVIDA",
                "exchange": "movida-event"
            }
        },
]
```

**Comment by javsalgar** [comment]
Hi,

I'm trying to reproduce but I would need the full definition file. Could you provide it? (if there's sensitive data just put random values as what we want is to reproduce the validation error).

**Comment by kemra102** [comment]
I have created a copy of the resources I'm using with some names switched around etc here: https://gist.github.com/kemra102/0bd10d98c0580ec1b316c229dd74a80b

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that I was able to reproduce the issue. Could you confirm that you didn't find the issue with the same configuration in other RabbitMQ instance that you have? Could it be that it doesn't work like that in newer versions of RabbitMQ? In any case, we will need to investigate in our side as well. Thanks for reporting.

**Comment by javsalgar** [comment]
Thanks for the hint. I'll add it to the information for the engineering team.

**Comment by maxisam** [comment]
workaround: https://github.com/bitnami/charts/blob/e598474a61bdce563d9508ccf5eda90be260e10b/bitnami/rabbitmq/values.yaml#L237

uncommon this line. 

It is actually in the readme. However, I think loadDefinition should handle it all the way through 

Just add something like should do the trick.

```yml
 {{- if .Values.loadDefinition.enabled }}
load_definitions = /app/load_definition.json
 {{- end }}
```

**Comment by kemra102** [comment]
> workaround:
> 
> https://github.com/bitnami/charts/blob/e598474a61bdce563d9508ccf5eda90be260e10b/bitnami/rabbitmq/values.yaml#L237
> 
> uncommon this line.
> 
> It is actually in the readme. However, I think loadDefinition should handle it all the way through
> 
> Just add something like should do the trick.
> 
> ```yaml
>  {{- if .Values.loadDefinition.enabled }}
> load_definitions = /app/load_definition.json
>  {{- end }}
> ```

This doesn't seem to work for me, I still get the error shown in my initial post. Have you understood the issue? I don't have any problem passing in a load definition in general, we have that working no problem. It is only an issue when trying to configure federation. The error is consistent with trying to add federation resources without the `rabitmq_federation` plugin enabled.

**Comment by maxisam** [comment]
@kemra102 ah I see, I thought you have a problem to load definition. Just curious, how did you make it work without this workaround?

**Comment by kemra102** [comment]
@maxisam We override parts of the values.yaml with our own, and in our overriding values.yaml we have a snippet that looks something like this:

```
loadDefinition:
  enabled: true
  existingSecret: rabbitmq-load-definition
```

We load in the load definition file specified above as a Kubernetes Secret and the above config can then pick it up and mount it inside the container. We use Terraform so we can set an explicit dependency for the Helm Deployment on the K8s secret being created first so that when it deploys it's guaranteed to be there and available.

The second example here is basically what we're doing: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions

**Comment by joshw123** [comment]
@maxisam Did we ever find a solution to this problem? 

Thank You

**Comment by maxisam** [comment]
@joshw123 I don't have this issue nor this use case, so I can't answer this

**Comment by joshw123** [comment]
> @joshw123 I don't have this issue nor this use case, so I can't answer this

Ah apologies, it seemed like you had a solution.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
