### ISSUE TITLE
[bitnami/postgresql-ha]postgresql standby instances are not connected to master if one of the workernode hosting the replicas are permanently down

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#3465]
**Which chart**:
[bitnami/postgresql-ha] version : 3.4.9

**Describe the bug**

Postgresql standby instances are not connected to master if one of the workernode hosting the replicas are permanently down. Attached values-production.yaml.

**To Reproduce**

Please find the step by step detailed explaination.

**Step 1 :** Deploy the helm chart. Please download the values-production.yaml attached. I have configured 5 postgresql replicas and 2 pgpool replicas with persistence volume enabled.

[root@masternode1 postgresql-ha]# helm install --name postgresql-ha bitnami/postgresql-ha -f values-production.yaml
NAME:   postgresql-ha
LAST DEPLOYED: Tue Aug 18 23:27:06 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                    AGE
postgresql-ha-postgresql-hooks-scripts  0s

==> v1/Deployment
NAME                  AGE
postgresql-ha-pgpool  0s

==> v1/NetworkPolicy
NAME           AGE
postgresql-ha  0s

==> v1/Pod(related)
NAME                                   AGE
postgresql-ha-pgpool-8546b7b876-c4n6s  0s
postgresql-ha-pgpool-8546b7b876-zc8lg  0s
postgresql-ha-postgresql-0             0s

==> v1/Secret
NAME                      AGE
postgresql-ha-pgpool      0s
postgresql-ha-postgresql  0s

==> v1/Service
NAME                               AGE
postgresql-ha-pgpool               0s
postgresql-ha-postgresql           0s
postgresql-ha-postgresql-headless  0s
postgresql-ha-postgresql-metrics   0s

==> v1/StatefulSet
NAME                      AGE
postgresql-ha-postgresql  0s

NOTES:

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed through Pgpool via port 5432 on the following DNS name from within your cluster:

    postgresql-ha-pgpool.default.svc.cluster.local

Pgpool acts as a load balancer for PostgreSQL and forward read/write connections to the primary node while read-only connections are forwarded to standby nodes.

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To get the password for "repmgr" run:

    export REPMGR_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.13.0-debian-10-r55 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" \
        --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb

Note: Since NetworkPolicy is enabled, only pods with label "postgresql-ha-client=true" will be able to connect to this PostgreSQL cluster.

To connect to your database from outside the cluster execute the following commands:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w postgresql-ha-pgpool

    export SERVICE_IP=$(kubectl get svc --namespace default postgresql-ha-pgpool --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h $SERVICE_IP -p 5432  -U postgres -d testdb

[root@masternode1 postgresql-ha]#

**Step 2 :** Please check the status of pods. "kubectl get pods" . This looks good and working as expected.

[root@masternode1 postgresql-ha]# kubectl get pods -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP               NODE                                 NOMINATED NODE   READINESS GATES
postgresql-ha-pgpool-8546b7b876-mnzht   1/1     Running   0          7m36s   10.233.78.191    workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-pgpool-8546b7b876-ngjnh   1/1     Running   0          7m36s   10.233.103.225   workernode2.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-0              2/2     Running   0          7m36s   10.233.103.226   workernode2.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-1              2/2     Running   0          7m10s   10.233.78.192    workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-2              2/2     Running   0          6m50s   10.233.70.184    workernode3.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-3              2/2     Running   0          6m22s   10.233.103.227   workernode2.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-4              2/2     Running   0          5m57s   10.233.78.193    workernode1.test.nimblestorage.com   <none>           <none>
[root@masternode1 postgresql-ha]#

**Step 3 :** I am connecting to database and check the pgpool_nodes status ,one primary instance and 4 standby instances which is working fine.

[root@masternode1 postgresql-ha]# export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
[root@masternode1 postgresql-ha]# kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.13.0-debian-10-r55 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb
If you don't see a command prompt, try pressing enter.

testdb=# show pool_nodes;
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | primary | 13         | false
            | 0                 |                   |                        | 2020-08-19 03:27:38
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 4          | false
            | 0                 |                   |                        | 2020-08-19 03:28:03
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 7          | false
            | 0                 |                   |                        | 2020-08-19 03:28:18
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 1          | true
            | 0                 |                   |                        | 2020-08-19 03:28:48
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 2          | false
            | 0                 |                   |                        | 2020-08-19 03:29:08
(5 rows)

testdb=#

**Step 4 :** Checking the status pg_stat_replication ,which seems to be good all the 4 standby instances are streaming.

testdb=# select * from pg_stat_replication;
 pid | usesysid | usename | application_name |  client_addr   | client_hostname | client_port |         backend_start         | backend_xmin |   state   | se
nt_lsn  | write_lsn | flush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+----------------+-----------------+-------------+-------------------------------+--------------+-----------+---
--------+-----------+-----------+------------+-----------+-----------+------------+---------------+------------
 330 |    16385 | repmgr  | walreceiver      | 10.233.70.181  |                 |       48928 | 2020-08-19 03:27:48.589534+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
 528 |    16385 | repmgr  | walreceiver      | 10.233.103.219 |                 |       51502 | 2020-08-19 03:28:31.165317+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
 411 |    16385 | repmgr  | walreceiver      | 10.233.78.186  |                 |       56824 | 2020-08-19 03:28:04.908165+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
 633 |    16385 | repmgr  | walreceiver      | 10.233.78.187  |                 |       52288 | 2020-08-19 03:28:50.417312+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
(4 rows)

testdb=#

**Step 5 :** In workernode2.test.nimblestorage.com ,we had two postgresql replicas   and one pgpool instance was running(Please check kubectl get pods output in the begining), workernode2.test.nimblestorage.com OS is crashed and is permanently down.

**After the workernode2 is down ,Please check pods status**  I think this is expected because since worker node is down kubelet can't approve the state.

[root@masternode1 ~]# kubectl get pods -o wide
NAME                                    READY   STATUS        RESTARTS   AGE   IP               NODE                                 NOMINATED NODE   READINESS GATES
postgresql-ha-pgpool-8546b7b876-kz768   1/1     Running       0          27m   10.233.70.186    workernode3.test.nimblestorage.com   <none>           <none>
postgresql-ha-pgpool-8546b7b876-mnzht   1/1     Running       1          45m   10.233.78.191    workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-pgpool-8546b7b876-ngjnh   1/1     Terminating   0          45m   10.233.103.225   workernode2.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-0              2/2     Terminating   0          45m   10.233.103.226   workernode2.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-1              2/2     Running       0          45m   10.233.78.192    workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-2              2/2     Running       1          45m   10.233.70.184    workernode3.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-3              2/2     Terminating   0          44m   10.233.103.227   workernode2.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-4              2/2     Running       1          44m   10.233.78.193    workernode1.test.nimblestorage.com   <none>           <none>
[root@masternode1 ~]#

If you look at the show pool_nodes status ,we could see two instances are in DOWN status which is exepcted but all the standby nodes are disconnected from master (Please check the status of pg_stat_replication query  response down)

testdb=# show pool_nodes;
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | **down**   | 0.200000  | standby | 0          | false
            | 0                 |                   |                        | 2020-08-19 04:12:42
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | primary | 48         | false
            | 0                 |                   |                        | 2020-08-19 04:12:21
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 7          | false
            | 5776              |                   |                        | 2020-08-19 04:14:11
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | **down**   | 0.200000  | standby | 0          | false
            | 0                 |                   |                        | 2020-08-19 04:12:42
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 0          | true
            | 16782992          |                   |                        | 2020-08-19 04:14:01
(5 rows)

testdb=# **select * from pg_stat_replication;**
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_lsn | write_lsn | fl
ush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+----------+-----------+---
--------+------------+-----------+-----------+------------+---------------+------------
**(0 rows)**

**Expected behavior**

I dont know if i am correct....But I am expecting remaining standby instances should be connected to master so that replication would happen to another standby instances.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

[root@masternode1 ~]# helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
[root@masternode1 ~]#

- Output of `kubectl version`:

[root@masternode1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
[root@masternode1 ~]#

**Additional context**

**Comment by parvaths1118** [comment]
[values-production.txt](https://github.com/bitnami/charts/files/5094081/values-production.txt)

**Comment by parvaths1118** [comment]
Please find the some other information,

As the workernode is completely down,we have forcibly deleted the pods so that they would be redeployed in another worker node. Please check the status of the pods after the "Terminating" state pods are deleted forcibly.

Pods are started fine but the standby instances are still not connected to master ,so replication cannot happen. Please help me about this issue.

[root@masternode1 ~]# **kubectl get pods -o wide**
NAME                                    READY   STATUS    RESTARTS   AGE   IP              NODE                                 NOMINATED NODE   READINESS GATES
postgresql-ha-pgpool-8546b7b876-kz768   1/1     Running   0          59m   10.233.70.186   workernode3.test.nimblestorage.com   <none>           <none>
postgresql-ha-pgpool-8546b7b876-mnzht   1/1     Running   1          77m   10.233.78.191   workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-0              2/2     Running   1          12m   10.233.70.187   workernode3.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-1              2/2     Running   0          77m   10.233.78.192   workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-2              2/2     Running   1          76m   10.233.70.184   workernode3.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-3              2/2     Running   0          12m   10.233.78.194   workernode1.test.nimblestorage.com   <none>           <none>
postgresql-ha-postgresql-4              2/2     Running   1          75m   10.233.78.193   workernode1.test.nimblestorage.com   <none>           <none>
[root@masternode1 ~]#

testdb=# **show pool_nodes;**
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 3          | false
            | 33566640          |                   |                        | 2020-08-19 05:04:43
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | primary | 402        | false
            | 0                 |                   |                        | 2020-08-19 04:17:18
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 183        | false
            | 100675504         |                   |                        | 2020-08-19 04:17:18
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 1          | true
            | 12208             |                   |                        | 2020-08-19 05:05:13
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 0          | false
            | 117452720         |                   |                        | 2020-08-19 04:17:18
(5 rows)


testdb=# **select * from pg_stat_replication;**
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_lsn | write_lsn | fl
ush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+----------+-----------+---
--------+------------+-----------+-----------+------------+---------------+------------
(0 rows)

**Comment by juan131** [comment]
This is a known issue and we're already tracking it at https://github.com/bitnami/charts/issues/3127
Let's follow the conversation there
