### ISSUE TITLE
bitnami/wordpress - wp-config.php read only extension

### ISSUE THREAD

**Issue by deantheiceman** [bitnami/charts#3466]
Now that wp-config.php is marked as read only how do I add these rules like:

```
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' == $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {
    $_SERVER['HTTPS'] = 'on';
}
```

Or enabling wp-rocket when it requires changes to be added to wp-config.php

**Comment by miguelaeh** [comment]
Hi @deantheiceman ,
thank you very much for reporting it. I have added a new parameter that will allow you to add extra content to the wp-config file.
There is an example in the PR above about how to use it.
Please, let us know if that solves your issue.
Regards.

**Comment by deantheiceman** [comment]
This doesn't seem to work, do I need to upgrade the image or something?

**Comment by miguelaeh** [comment]
Hi @deantheiceman ,
You need to execute:
```
helm repo update
```

To update your Helm repositories. Then you can pass that parameter like the following:
```
helm install wordpress . --set wordpressExtraConfigContent="if ( isset( \$_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' ==\$_SERVER['HTTP_X_FORWARDED_PROTO'] ) {
    \$_SERVER['HTTPS'] = 'on';
}"
```

**Comment by deantheiceman** [comment]
I'm running the latest version, I'm using a yaml file for my values, is this the correct way?

```
wordpressExtraConfigContent: "if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' == $_SERVER['HTTP_X_FORWARDED_PROTO'] ) { $_SERVER['HTTPS'] = 'on'; } \n define('WP_CACHE', true); "
```

**Comment by miguelaeh** [comment]
Hi @deantheiceman ,
I test it using a yaml file and the lines are added to the configuration file, but in a wrong format as you can see:
```
            unset($headers["X-Pingback"]);
            return $headers;
           });
// disable pingbacks
add_filter( "xmlrpc_methods", function( $methods ) {
             unset( $methods["pingback.ping"] );
             return $methods;
           });
}

if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' == $_SERVER['HTTP_X_FORWARDED_PROTO'] ) { $_SERVER['HTTPS'] = 'on'; }
 define('WP_CACHE', true);
```

It is just not properly formated.

**Comment by deantheiceman** [comment]
Hi @miguelaeh seems the issue is here https://github.com/bitnami/bitnami-docker-wordpress/issues/264 since it's not modified on the second run. What are our options now?

**Comment by miguelaeh** [comment]
Hi @deantheiceman ,
In that case, I think we could try to mount the configuration file using a configMap directly to `/opt/bitnami/wordpress/wp-config.php` but it will require some changes in the Chart.
Would you like to create a PR?
