### ISSUE TITLE
How to use bitnami thanos querier.dnsDiscovery.sidecarsService param for multiple sidecar services?

### ISSUE THREAD

**Issue by hrisant** [bitnami/charts#3467]
**Which chart**:
bitnami/thanos

**Is your feature request related to a problem? Please describe.**
This is more a documentation request:

My setup is the folowing:

if I have 3 prometheus shards, deployed with prometheus operator, with 3 thanos-sidecars and 3 services for these sidecars of the form:
Name                         Type
sidecar-edge-peers  LoadBalancer
sidecar-kube-peers  LoadBalancer
sidecar-infr-peers     LoadBalancer

Is there a way I can use the querier chart param "querier.dnsDiscovery.sidecarsService" for all three?
In this doc (https://docs.bitnami.com/tutorials/create-multi-cluster-monitoring-dashboard-thanos-grafana-prometheus/) I found this form:

querier:
stores:
- SIDECAR-SERVICE-IP-ADDRESS-1:10901
- SIDECAR-SERVICE-IP-ADDRESS-2:10901

But I would rather not depend on IPs as we sometimes redeploy our prometheus for various reasons monitoring.

**Describe the solution you'd like**
Have an example of how to use querier.dnsDiscovery.sidecarsService for multiple sidecar services, if that is possible.

**Describe alternatives you've considered**
provide stores params for each sidecar service.

**Comment by javsalgar** [comment]
Hi,

I'm not an expert, but the first thing that I would check is to manually create a service that maps to all sidecars using labels. Did you try that and it worked? In other charts we have an extraDeploy parameter that allows you to deploy any other yaml you like. Could you describe more the use case and why you would like to unify the services?

**Comment by hrisant** [comment]
Hi @javsalgar ,

Thanks for the response! 
To be honest I did not think of unifying under one service the three sidecars. I tried it and in the querier stores tab only one sidecar appeared, not sure if I did something bad, but I don't think querier likes different sidecars on the same service(mine was LB), maybe I am wrong. 
It wen well though with the querier.stores param (mentioned above) using the service full name:
querier:
  stores:
    - sidecar-infr-peers.monitoring.svc:10901
    - sidecar-edge-peers.monitoring.svc:10901
    - sidecar-kube-peers.monitoring.svc:10901

So I found a good solution for my usecase (mapping multiple sidecars in querier in a redeploy-resistent manner).
I don't know if "querier.dnsDiscovery.sidecarsService" could do the same; I'm on a tight schedule now so I'll use what I have working now and maybe return to investigating it later. The thing is it is eyecatchy, having sidecar in the name and all. It would be nice to work with a list or a templating of some sort (maybe it does, just did not have time to investigate)

All the best,
Andrei

**Comment by javsalgar** [comment]
Hi,

Then I may have misunderstood the use case, I thought you wanted to unify the services. I'm glad that you found a solution to your use case :) Do not hesitate to come with more information that could be helpful for creating a new feature, we'll gladly help. 

Best
