### ISSUE TITLE
cannot log into rabbitmq management console installed with bitnami/rabbitmq chart

### ISSUE THREAD

**Issue by altfatterz** [bitnami/charts#3468]
**Which chart**:
rabbitmq

**Describe the bug**
Cannot log into http://localhost:15672/ 
I tried with **guest/guest** or the credentials provided with:

```bash
 echo "Username      : user"
 echo "Password      : $(kubectl get secret --namespace default eb-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
```

**To Reproduce**
1. 
```bash
helm install eb-rabbitmq bitnami/rabbitmq
```
2. 
Run in separate terminals
```bash
kubectl port-forward --namespace default svc/eb-rabbitmq 5672:5672
kubectl port-forward --namespace default svc/eb-rabbitmq 15672:15672
```
3. Access: http://localhost:15672/
4. Cannot login

**Expected behavior**
The user is logged into management console.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```bash
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

- Output of `kubectl version`:
```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @altfatterz, we couldn't reproduce the issue. We executed the same you did:

```
$ helm install eb-rabbitmq bitnami/rabbitmq
$ kubectl get secret --namespace default eb-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode
$ kubectl port-forward --namespace default svc/eb-rabbitmq 15672:15672
```

Could it be that you are reusing old PVs from a previous deployment?

**Comment by altfatterz** [comment]
Hi @andresbono, yes it works now after `helm repo update`. I will close the ticket. Thanks.

**Comment by altfatterz** [comment]
the issue is happening again, after 

```bash
$ helm install eb-rabbitmq bitnami/rabbitmq
```

I cannot login again with `user` and the generated password. I have update to the latest `rabbitmq` chart `7.6.3`.
Could this be this change which broke it? https://github.com/bitnami/charts/commit/8d0be4f3cdd1b7ddaeefabbad8d4ff5f2a21f7ae

I tried to verify it hit this issue: https://github.com/bitnami/charts/issues/3497

Could you help?

**Comment by altfatterz** [comment]
ok, figured it out. I needed to delete the `pvc` created and reinstall the chart and then I could login to the management console again.

**Comment by andresbono** [comment]
Hi @altfatterz, that's what I suspected it was happening! https://github.com/bitnami/charts/issues/3468#issuecomment-677530175
> Could it be that you are reusing old PVs from a previous deployment?

Please note that we have improved this behavior in the latest versions of the charts. It now shows a warning message when you try to upgrade the chart without specifying the credentials:

> PASSWORDS ERROR: you must provide your current passwords when upgrade the release
>    'auth.password' must not be empty, please add '--set auth.password=$RABBITMQ_PASSWORD' to the command.
