### ISSUE TITLE
[bitnami/moodle] apache_exporter does not depend on APACHE_HTTP_PORT_NUMBER from moodle container

### ISSUE THREAD

**Issue by gastonsilva** [bitnami/charts#3484]
Port should be the same as APACHE_HTTP_PORT_NUMBER from moodle container (now defaults 8080):

https://github.com/bitnami/charts/blob/da4b1e51dc8135ed86d9ce9703d197a9ea82e0ca/bitnami/moodle/templates/deployment.yaml#L189

**Comment by miguelaeh** [comment]
Hi @gastonsilva ,
Thank you very much for reporting this. I think you are right, the previous PR should fix your issue.
Regards.
