### ISSUE TITLE
Support WTF_CSRF_ENABLED config in bitnami/airflow

### ISSUE THREAD

**Issue by BigFatDog** [bitnami/charts#3485]
**Which chart**:
bitnami/airflow

**Is your feature request related to a problem? Please describe.**
When using the rest api plugin that is [introduced in the chart](https://github.com/bitnami/charts/tree/master/bitnami/airflow#loading-plugins)

The plugins gets loaded and works well. But I got `CSRF token missing` error when using post rest requests。
According to the solution from [this plugin's doc](https://github.com/teamclairvoyant/airflow-rest-api-plugin): 
I need to configure airflow
```
WTF_CSRF_ENABLED=false
```

I tried but it has no effect. I double checked `bitnami/airflow-docker-image` and found that it doesn't support this configuration

**Describe the solution you'd like**
I can configure `WTF_CSRF_ENABLED` in the chart

**Describe alternatives you've considered**
Other solutions are totally fine as long as the post rest apis would work.

**Additional context**
N/A

**Comment by javsalgar** [comment]
Hi,

Did you try using the `airflow.webserverConfigMap` value? There you could add the setting you are missing. From the doc:

```
We need to replace the CSRF_ENABLED attribute with WTF_CSRF_ENABLED. This change is required to support the POST method when RBAC is enabled with JWT. Please add the following property in the {AIRFLOW_HOME}/webserver_config.py file.

 # Flask-WTF flag for CSRF
 WTF_CSRF_ENABLED = False
```

**Comment by BigFatDog** [comment]
I just tried the following config:
```
airflow:
  auth:
    forcePassword: xxx
    username: xxx
    password: xxx
    fernetKey: "xxx"
  webserverConfigMap:
    WTF_CSRF_ENABLED: false
```

Then got error: 
```
MountVolume.SetUp failed for volume "custom-webserver-configuration-file" : configmap "map[WTF_CSRF_ENABLED:false]" not found
```

**Comment by javsalgar** [comment]
Hi,

Sorry if I didn't explain myself correctly. What you need to put there is the name of a ConfigMap that contains the `webserver_config.py` with the settings you want to enable.

**Comment by BigFatDog** [comment]
Hi,
No. That's my fault, I should have read doc more thoroughly. 


I created a configmap:
```
kubectl describe configmap airflow-webserver-config -n xxx
Name:         airflow-webserver-config
........
Data
====
WTF_CSRF_ENABLED:
----
false
/ #
```

Then use the configmap in airflow chart:
```
airflow:
  webserverConfigMap: airflow-webserver-config
```

I got error:
```
Error executing 'postInstallation': Traceback (most recent call last):

File "/opt/bitnami/airflow/venv/bin/airflow", line 25, in

from airflow.configuration import conf

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/__init__.py", line 31, in

from airflow.utils.log.logging_mixin import LoggingMixin

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/__init__.py", line 24, in

from .decorators import apply_defaults as _apply_defaults

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/decorators.py", line 36, in

from airflow import settings

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/settings.py", line 37, in

from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG # NOQA F401

File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/configuration.py", line 695, in

with open(WEBSERVER_CONFIG, 'w') as file:

IsADirectoryError: [Errno 21] Is a directory: '/opt/bitnami/airflow/webserver_config.py'
```

**Comment by javsalgar** [comment]
Hi,

It would be a bit different, you need to put the contents of the whole file in an entry called webserver_config.py.

However, I just saw that the flag is already enabled in the default webserver_config.py 

```
# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = True
```

Could you check it by entering the container using the default values?

**Comment by BigFatDog** [comment]
Thank you for your patience. I change my `ConfigMap` to:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: airflow-webserver-config
  labels:
    app: airflow-webserver-config
data:
  webserver_config.py: |
    - WTF_CSRF_ENABLED : false
```
and it works

**Comment by javsalgar** [comment]
Thanks for letting us know!
