### ISSUE TITLE
[bitnami/harbor] add support for cabundlesecretname to match upstream harbor chart

### ISSUE THREAD

**Issue by paulczar** [bitnami/charts#3486]
The upstream harbor chart has a [value](https://github.com/goharbor/harbor-helm/commit/782a05418a79d4bc997f03224d0948a462f6b7e4) `caBundleSecretName` that enables you to provide a custom ca bundle, this allows you to use endpoints for auth and other things that are TLS, but self signed.

I am using internally hosted keycloak to provide auth, and I want to be able to use self signed TLS certs, porting this value and feature from the upstream chart would allow this.

**Comment by andresbono** [comment]
Hi @paulczar, thanks for opening this issue. Is this what you are looking for?

https://github.com/bitnami/charts/tree/master/bitnami/harbor#persistence-parameters

| Parameter                                                     | Description                                                                                                                                                                                                                                                                                                                                     | Default         |
|---------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------|
| `persistence.imageChartStorage.caBundleSecretName`            | Specify the `caBundleSecretName` if the storage service uses a self-signed certificate. The secret must contain keys named `ca.crt` which will be injected into the trust store  of registry's and chartmuseum's containers.                                                                                                                    |                 |

**Comment by paulczar** [comment]
No, this is a harbor wide root setting, not one specific to chart storage.  See the link I posted in the original issue (or here - https://github.com/goharbor/harbor-helm/commit/782a05418a79d4bc997f03224d0948a462f6b7e4 ) for the commit in which it was implemented upstream.

**Comment by mkuendig** [comment]
Same here. Would love to get that parameter. We use mTLS everyhwere and quering LDAP needs that internal CA cert. I have set persistence.imageChartStorage.caBundleSecretName and I still get the LDAP TLS verification error.

**Comment by andresbono** [comment]
Thanks for the clarification @paulczar! So yes, it seems a nice feature to support.

Would you be interested on contributing with a PR to add the new feature @paulczar, @mkuendig?

**Comment by paulczar** [comment]
Oh its actually much worse.  I just put together the PR, and in testing it still doesn't work.  

After some investigations ... It appears that the upstream harbor components have a script [/harbor/install_cert.sh](https://github.com/goharbor/harbor/blob/0846425b8a4b262550520bea06d47f6f69dc53e9/make/photon/common/install_cert.sh)  that's called in the [entrypoint.sh](https://github.com/goharbor/harbor/blob/0846425b8a4b262550520bea06d47f6f69dc53e9/make/photon/core/entrypoint.sh#L5) which installs any ca certs found in `/harbor_cust_cert`.   I cannot find this script in the bitnami docker images / build process, not is it called in the bitnami entrypoint.sh.   

This would need to be fixed in each of the images in order for this to work.

**Comment by paulczar** [comment]
From what I can see this also means the existing `persistence.imageChartStorage.caBundleSecretName` will not work as it also puts a root ca cert in the /harbor_cust_cert path, so not only are we missing functionality, we have a bug.  

see https://github.com/bitnami/charts/blob/master/bitnami/harbor/templates/registry/registry-dpl.yaml#L189-L193

**Comment by andresbono** [comment]
Thanks for identifying it, @paulczar. We are going to fix the harbor container images addressing this issues. Then we can come back here to modify the chart.

**Comment by andresbono** [comment]
Hi @paulczar, as we said in https://github.com/bitnami/charts/pull/3536#issuecomment-694872372, we have implemented the changes in the images and we have released a new version of the `bitnami/harbor` chart:
`[bitnami/harbor] Release 7.2.2 updating components versions` https://github.com/bitnami/charts/commit/f7d7cad8108618ae86e4ccdcb6587fc65c6159cd

The changes already done in the container images plus your PR #3536 should solve this issue.

**Comment by mkuendig** [comment]
@andresbono @paulczar I'm still very much interested in this. Would be great to get this fixed.

**Comment by andresbono** [comment]
Hi @mkuendig, thanks for showing interests on this. We have just rebased #3536. Could you please use that PR to test if the new feature works for you?

**Comment by mkuendig** [comment]
we have tested it and it works well. Thanks!

**Comment by juan131** [comment]
We were still waiting for @paulczar (the user who created the PR) to update the PR, but I decided to a step forward and update it for him and merge it! The changes will be available by default on version **8.1.0**.
