### ISSUE TITLE
[bitnami/wordpress] ReplicaSet has timed out progressing.; Deployment does not have minimum availability.

### ISSUE THREAD

**Issue by Med-All** [bitnami/charts#3487]
**Which chart**:
Wordpress 9.03

**Describe the bug**
I'm not able to deploy Wordpress Helm Chart using Rancher Catalog. MariaDB pod runs fine but wordpress pod errors out as 

`ReplicaSet "wordpress-557fcb8469" has timed out progressing.; Deployment does not have minimum availability.`

Also from the wordpress pod logs:

`Error executing 'postInstallation': Failed to connect to wordpress-mariadb:3306 after 36 tries`

and from the wordpress pod shell:

```
I have no name!@wordpress-557fcb8469-gj585:/$ mysql -h wordpress-mariadb -u root -p
Enter password: 
ERROR 2005 (HY000): Unknown MySQL server host 'wordpress-mariadb' (-3)
```

but

```
I have no name!@wordpress-557fcb8469-gj585:/$ mysql -h 10.42.0.8 -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 16597
Server version: 10.3.22-MariaDB Source distribution
```

**Expected behavior**
Able to connect to wordpress-mariadb from wordpress pod

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @Med-All ,
Could you give a try to connect using a service address like the following:
```
my-svc.my-namespace.svc.cluster-domain.example
```
?
Where `my-svc` should be the name of the MariaDB service, and probably the `cluster-domain.example` should be changed by `cluster.local`, so you should use something like:
```
mysql -h  wordpress-mariadb.<YOUR-NAMESPACE>.svc.cluster.local -u root -p
```

**Comment by Med-All** [comment]
Thanks for the response @miguelaeh

I have tried to verify connections following your recommendations.

On the MariaDB pod:
```
I have no name!@wordpress-mariadb-0:/$ cat /etc/hosts                                                      
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.42.0.14      wordpress-mariadb-0.wordpress-mariadb.wordpress.svc.cluster.local       wordpress-mariadb-0
```

No clue why `-0` was added to the host name but

```
I have no name!@wordpress-mariadb-0:/$ mysql -h wordpress-mariadb-0.wordpress-mariadb.wordpress.svc.cluster.local -u root -p                   
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 48253
Server version: 10.3.22-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```

works fine from the MariaDB pod.

Than on the Wordpress pod:

```
I have no name!@wordpress-6647794f9b-4mmxd:/$ mysql -h wordpress-mariadb-0.wordpress-mariadb.wordpress.svc.cluster.local -u root -p
Enter password: 
ERROR 2005 (HY000): Unknown MySQL server host 'wordpress-mariadb-0.wordpress-mariadb.wordpress.svc.cluster.local' (-3)
```

for some reason hostname is not registered for that namespace.

Any clue?

**Comment by miguelaeh** [comment]
Hi @Med-All ,
> No clue why -0 was added to the hostname but

You are using the MariaDB pod name. You should be using the service name. Execute the following:
```
kubectl get services
```

Get the MariaDB service name, that should be `<release-name>-mariadb`, and use it as the MariaDB host instead of the pod name.

**Comment by Med-All** [comment]
@miguelaeh 

Here is the output for that namespace:

```
> kubectl get services --namespace=wordpress
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
wordpress           LoadBalancer   10.43.91.13     <pending>     80:30158/TCP,443:30453/TCP   4d16h
wordpress-mariadb   ClusterIP      10.43.178.123   <none>        3306/TCP                     4d16h
```

as I have stated in the OP I'm not able to connect to the DB using service name.

**Comment by miguelaeh** [comment]
Hi @Med-All ,
Please check the [comment above](https://github.com/bitnami/charts/issues/3487#issuecomment-678961205). That is to use the full-service name, but in you reply you were using the pod name that is not reachable from other pods. (that is why you had a `-0`, because you set the pod name not the service name).
I would like you to check if it works using the full service name.
I mean, with:
> Get the MariaDB service name, that should be <release-name>-mariadb, and use it as the MariaDB host instead of the pod name.

I wanted to say that you need to use that name with the following:
```
<SERVICE_NAME>.<NAMESPACE>.svc.cluster-domain.example
```
That, in your case it will be:
```
wordpress-mariadb.<NAMESPACE>.svc.cluster.local
```

You checked this:
```
wordpress-mariadb-0.wordpress-mariadb.wordpress.svc.cluster.local
```
That is not correct since it is the pod name.

**Comment by Med-All** [comment]
Well, I have used 

```
wordpress-mariadb-0.wordpress-mariadb.wordpress.svc.cluster.local
```

because that was registered as a hostname in the MariaDB pod.

Running connection to the service is not working as I have stated in the OP:

```
I have no name!@wordpress-84765d6f9-mbdcc:/$ mysql -h wordpress-mariadb.wordpress.svc.cluster.local -u root -p
Enter password: 
ERROR 2005 (HY000): Unknown MySQL server host 'wordpress-mariadb.wordpress.svc.cluster.local' (-3)
```

**Comment by Med-All** [comment]
Ok, I have made some progress on that. It came up one of nodes has problems with CoreDNS. My question in that case is better to scrap that node or reinstall it via RKE?

On another hand I was able to install Wordpress on another node but can't get access to it and it shows waiting for external IP

```
> kubectl get services -n wordpress 
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
wordpress           LoadBalancer   10.43.137.240   <pending>     80:31672/TCP,443:31400/TCP   18m
wordpress-mariadb   ClusterIP      10.43.7.73      <none>        3306/TCP                     18m
```

What I should to look at in that case?

**Comment by miguelaeh** [comment]
Hi @Med-All ,
I am afraid we are not experts in RKE, it seems your issues are due to a wrong cluster configuration so I recommend you to ask to the Rancher team.

> On another hand I was able to install Wordpress on another node but can't get access to it and it shows waiting for external IP

Regarding that, I think this link will be useful https://rancher.com/docs/rancher/v1.2/en/cattle/adding-load-balancers/

**Comment by Med-All** [comment]
Well, I thought it is part of the Wordpress Helm Chart as I see that L4 Load Balancer was created for the `wordpress` service but is in the `pending` state and no clue why as I don't see any errors there.

**Comment by miguelaeh** [comment]
It could be in a pending state because the cluster has not provided the external IP yet. The provision of the external IP should be done by the k8s cluster, not by the chart.

**Comment by Med-All** [comment]
Yeah, for some reason is not able to get assigned external IP neither to resolve any external host names.

**Comment by miguelaeh** [comment]
I would recommend you to ask the Rancher team since they will be able to help you configuring your cluster properly.

**Comment by Med-All** [comment]
I did some progress. At least ingress was able to provide WP site, bu I'm not able to get `/wp-admin` to work.

On another hand L4 Balancer created by the chart is still in _pending_ status for some reason.

```
> kubectl get svc -n wordpress -o wide
NAME                                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE     SELECTOR
ingress-d5bf098ee05c3bbaa0a93a2ceedd8d1a   ClusterIP      10.43.51.5      <none>        80/TCP                       15m     workloadID_ingress-d5bf098ee05c3bbaa0a93a2ceedd8d1a=true
wordpress                                  LoadBalancer   10.43.137.240   <pending>     80:31672/TCP,443:31400/TCP   5d22h   app.kubernetes.io/instance=wordpress,app.kubernetes.io/name=wordpress
wordpress-mariadb                          ClusterIP      10.43.7.73      <none>        3306/TCP                     5d22h   app=mariadb,component=master,release=wordpress
```

**Comment by miguelaeh** [comment]
Hi, you can take a look to our MetalLB Helm Chart here: https://github.com/bitnami/charts/tree/master/bitnami/metallb

**Comment by Med-All** [comment]
Yes, I was looking at that option. My question here is do I need to have both - L7 Ingress and L4 Balancer for that Wordpress deployment? As I have understand L7 Ingress (server by NGINX) can be set as a load balancer too or not?

**Comment by miguelaeh** [comment]
it is not needed to have both. Either the Ingress and the LoadBalancer will allow you to access the cluster by a single connection point. Both of them will balance the load, the difference will be that you can have one ingress for more than one deployment but if you use a loadbalancer service you need to have one public IP per deployment (and those IPS needs to be paid)

**Comment by Med-All** [comment]
OK, I understand that part.

I assume that for the web apps like WP L7 Ingress is enough

**Comment by miguelaeh** [comment]
Hi,
I am sorry but I am not familiar with that "box". Could you elaborate what is it?

**Comment by Med-All** [comment]
Sorry for generalizing it - I had on my mind dedicated VM or put on the same VM where I have running Docker with the Rancher.

**Comment by miguelaeh** [comment]
The MetalLB Chart would need to be deployed in your K8s cluster as another chart release. You can find more information here: https://metallb.universe.tf/

**Comment by Med-All** [comment]
OK, so I think conclusion is that it will be great that Wordpress Helm Chart can have option to pick up where it is deployed so it will set service under desired type. Other way, for someone new to Helm Charts like me, it is getting confused that L4 Balancer is required when is not when is deployed to the bare metal. Even if someone will deploy to the cloud may required to have L4 Ingress in case of multiple services provided on the same external IP. 

IMO is better to have both, and disable one of them, rather than have only one which creates confusion for rookies ;)

**Comment by miguelaeh** [comment]
Hi,
> OK, so I think conclusion is that it will be great that Wordpress Helm Chart can have option to pick up where it is deployed so it will set service under desired type.

The Helm Chart has not the logic to select the type of service that should be used. It the chart's user who must set the service type depending on his specific use case. See: https://github.com/bitnami/charts/blob/8bfacfaa23af65ed2cbcfeba870c9b15f70aeb4e/bitnami/wordpress/values.yaml#L270

> Other way, for someone new to Helm Charts like me, it is getting confused that L4 Balancer is required when is not when is deployed to the bare metal. Even if someone will deploy to the cloud may required to have L4 Ingress in case of multiple services provided on the same external IP.

I am sorry but I don't fully understand what you mean

**Comment by Med-All** [comment]
> The Helm Chart has not the logic to select the type of service that should be used. It the chart's user who must set the service type depending on his specific use case. See:
> 
> https://github.com/bitnami/charts/blob/8bfacfaa23af65ed2cbcfeba870c9b15f70aeb4e/bitnami/wordpress/values.yaml#L270
>

I know that Helm Chart has not the logic because it can be edited and used directly on K8s, but I have used it through the Rancher Catalog connected to Helm repo and just used UI to deploy it w/o any edits for that section. Here are coming to play Rancher Charts enhancements and questions section which may to resolve that problem of the "logic" (https://rancher.com/docs/rancher/v2.x/en/catalog/creating-apps/#rancher-charts)
 
> > Other way, for someone new to Helm Charts like me, it is getting confused that L4 Balancer is required when is not when is deployed to the bare metal. Even if someone will deploy to the cloud may required to have L4 Ingress in case of multiple services provided on the same external IP.
> 
> I am sorry but I don't fully understand what you mean

Sorry with the confusion here. I think what I have described above should to explain my doubt.

Thanks again for your help!

**Comment by miguelaeh** [comment]
Hi @Med-All ,
Now I understand what you mean. So, if I am not wrong you are requesting us to add the questions files so it is easier to deploy our chart in rancher, right?

**Comment by Med-All** [comment]
That's correct, if possible. Sorry for confusion and putting all (Helm Chart and custom yaml for the Rancher) into one bucket.

I think we can close that ticket as it went towards Helm Chart enhancements for the Rancher and it is up to Bitnami team if that can be done.

**Comment by miguelaeh** [comment]
Hi again,
I discussed the addition of the questions file to the charts with the team. Since it is something specific from Rancher we don't think we should add them. We already have `values.schema.json` files that are officially supported and describe the structure of the `values.yaml` file. More information here: https://helm.sh/docs/topics/charts/#the-chart-file-structure
Sorry for the inconvenience.
Regards.
