### ISSUE TITLE
[bitnami/harbor] Several containers fail to start when internalTLS is enabled

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#3489]
**Which chart**:
Harbor v7.1.0

**Describe the bug**
When enabling internalTLS, several containers fail to start.

The chartmuseum container enters a crashloop with this error: FATAL	open /bitnami/certs/server.crt: no such file or directory
The secret being mounted for ChartMuseum is created, but has no server.crt key.

The jobservice container enters a crashloop with this error: Failed on load rest config err:Get https://harbor-core:443/api/internal/configurations: x509: certificate signed by unknown authority, url:https://harbor-core:443/api/internal/configurations
It does not trust the automatically generated certificate that the core is using.

The harbor-portal container enters a crashloop, hanging at ** Starting NGINX **

The trivy container never starts, hanging at: {"addr":":8443","certificate":"/bitnami/certs/tls.crt","clientCAs":"/bitnami/certs/ca.crt","key":"/bitnami/certs/tls.key","level":"debug","msg":"Starting API server with TLS","time":"2020-08-22T10:32:53Z"}

**To Reproduce**
1. Install harbor with internalTLS enabled.

**Expected behavior**
All containers will start normally when using internalTLS

**Comment by rafariossaa** [comment]
Hi,
  Thanks for reporting this issue.
  I was able to reproduce it, I am opening an internal task to look deeper into it and find a fix.
  This could take a while, meanwhile any PR is welcomed and we will be glad of reviewing it.
