### ISSUE TITLE
[prometheus-operator] is bitnami/prometheus-operator similar to stable/prometheus-operator?

### ISSUE THREAD

**Issue by scottrigby** [bitnami/charts#3490]
**Which chart**:
prometheus-operator

**Is your feature request related to a problem? Please describe.**
The similarly named `stable/prometheus-operator` chart has always been a misnomer, according to: https://github.com/prometheus-community/community/issues/28#issuecomment-670406329

Question: is bitnami/prometheus-operator similar to stable/prometheus-operator in that way?

**Describe the solution you'd like**
If it is similar, `stable/prometheus-operator` is moving to the `prometheus-community` org – but renamed `kube-prometheus` to more accurately explain the project it installs: https://github.com/prometheus-operator/kube-prometheus

In this case, would you want to either rename this chart as well, or merge efforts in the new prometheus-community helm charts repo?

**Describe alternatives you've considered**
N/A

**Additional context**
See:
- https://github.com/scottrigby/prometheus-helm-charts/pull/1
- https://github.com/prometheus-community/community/issues/28

PS, I haven't had time to dig into this chart, I only saw it on Helm Hub and Artifact Hub, so want to make you aware of the above changes and reasoning. Thanks!

**Comment by miguelaeh** [comment]
Hi @scottrigby ,
Thank you very much for informing us about this. We will evaluate how the renaming will affect our internal tools and we will perform the necessary changes.
Best regards.

**Comment by juan131** [comment]
I plan to bump the major version of the chart at this PR (https://github.com/bitnami/charts/pull/3498), check the PR to learn more about the reasons. If we're going to rename the chart, then we should include the corresponding changes on that PR

**Comment by jjangga0214** [comment]
@juan131 
Should this issue be closed?

**Comment by marcosbc** [comment]
@jjangga0214 You're right, thanks for checking that! Closing now.
