### ISSUE TITLE
MongoDB could not be configured as multi-region

### ISSUE THREAD

**Issue by techsaau** [bitnami/charts#3496]
**Which chart**:
MongoDB version 8.1.5

**Describe the bug**
Current setup of MongoDB can not use Azure FileShare which only supports ReadWriteMany feature. But every single mongodb pod needs a separate storage otherwise it will fail to create a pod and will get lock file error.
In multi-region architecture, we need shared storage which can be used by two or more regions. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"e3808385c7b3a3b86db714d67bdd266dc2b6ab62", GitTreeState:"clean", BuildDate:"2020-07-15T20:50:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by carrodher** [comment]
Hi, what values are you using for the `persistence` section? Please take into account this section can be customizable although I am not sure if it will cover your exact use case, in that case, do you have any workaround we can implement? Feel free to create a PR if that's the case

**Comment by techsaau** [comment]
@carrodher  Persistance is enabled. It is working perfectly fine in one kubernetes cluster.
If we use using two kubernetes cluster but want to sync the data for Higher Availability\Redundancy. Then I do not know how to replicate data between two different mongodb deployments. If there is something your can help.

**Comment by carrodher** [comment]
I am sorry but as far as I know, this feature is not currently supported in the chart; we are open to receive PRs adding new features apart from the ones that are in our roadmap but unfortunately this is not something we are going to work on in the short time due to other priorities. We are happy to guide/help contributors to collaborate adding features to the charts, just in case you are interested on implement a solution for your use case.
