### ISSUE TITLE
Somehow this seems to cause some issues on my end:

### ISSUE THREAD

**Issue by jsbrain** [bitnami/charts#3501]
It seems like the changes of #3335 cause an issue while upgrading to 10.1.x.

I'm running rancher and want to upgrade to the latest version. When I select any of the charts of 10.1.x, I immediately get the error as seen below.

```
Wait helm template failed. Error: parse error in "ghost/templates/NOTES.txt": template: ghost/templates/NOTES.txt:79: illegal number syntax: "-" : exit status 1
```

According to the error it has to do with this line here:
https://github.com/bitnami/charts/blob/73c8873f1ae98c7105f09fa7443043c49704e98e/bitnami/ghost/templates/NOTES.txt#L79

**Comment by javsalgar** [comment]
Hi,

I've been unable to reproduce the issue. Something tells me it could be related to the helm version you are using. Which helm version are you using in your rancher interface? Also, from which version of the chart you are trying to upgrade?

**Comment by jsbrain** [comment]
Hey, thanks to your question I realized that I'm still using helm2 but can use helm3 instead. Seems as if helm3 doesn't have that issue so I'll try to migrate my deployments later. I'm going to close this issue. :)

**Comment by javsalgar** [comment]
Thank you very much for confirming! Do not hesitate to open a new ticket in case you find other issues :)
