### ISSUE TITLE
[redis-cluster]

### ISSUE THREAD

**Issue by vitobotta** [bitnami/charts#3502]
**Which chart**:
redis-cluster, latest

**Describe the bug**
I am trying to set up a cluster with 3 masters and no replicas. So I set the nodes count to 3 and replicas to 0. The installation works fine with no errors, but the cluster is not configured properly. In the logs I see "No cluster configuration found" and the file /bitnami/redis/data/nodes.conf only contains one node. 

**Expected behavior**
I would expect the masters to be linked to each other in a cluster.

**Version of Helm and Kubernetes**:
Helm v3.3.0+g8a4aeec
Kubernetes v1.18.6

Thanks in advance for any help!

**Comment by juan131** [comment]
Hi @vitobotta 

The number or nodes in the cluster shouldn't be less than 6. I mean, the one you set at `cluster.nodes` parameter. That said, since you have 3 master and no replicas, you're not reaching that number...

Could you check the logs of the K8s job used to create the cluster?
