### ISSUE TITLE
[bitnami/harbor] Harbor 2.0.2 requires postgres max_connections increase to 1024

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#3505]
**Which chart**:
Harbor v7.1.0

**Describe the bug**
Per the main harbor project, in version 2 the postgresql max_connections should be increased to 1024. They implemented this change in Harbor v2.0.2 in order to resolve multiple issues, but it is not showing up when installing the Harbor chart v7.1.0. See: https://github.com/goharbor/harbor/issues/12644

**To Reproduce**
1. Install harbor chart v7.1.0
2. Connect to the postgres registry database at commandline
3. run 'show max_connections;'

**Expected behavior**
The max_connections should be upgraded per the software requirements.

**Additional Context**
The low max_connections directly prevents certain operations, such as a large replication.

**Comment by andresbono** [comment]
Thanks for reporting this issue, @ajchiarello. We are going to release a new version of the chart configuring the proper value for max_connections. In the meantime, could you please deploy the chart adding the following values yaml?

```yaml
postgresql:
  postgresqlExtendedConf:
    maxConnections: 1024
```

You can execute the following commands to test it:

```bash
cat <<EOF >custom-values.yaml
postgresql:
  postgresqlExtendedConf:
    maxConnections: 1024
EOF

helm install harbor bitnami/harbor --values custom-values.yaml

export POSTGRESQL_PASSWORD=$(kubectl get secret harbor-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl exec harbor-postgresql-0 -- bash -c "PGPASSWORD=$POSTGRESQL_PASSWORD psql -U postgres -c 'show max_connections;'"
```

It should show:

```
 max_connections
-----------------
 1024
(1 row)
```

Let us know if it works for you.

**Comment by ajchiarello** [comment]
Hi @andresbono - yes, adding that option to the helm chart resolved the issue - thanks!

**Comment by andresbono** [comment]
Thanks for confirming it, @ajchiarello. We are going to add those recommended values by default in the chart: https://github.com/bitnami/charts/pull/3509.
