### ISSUE TITLE
Harbor-Trivy is not root-less

### ISSUE THREAD

**Issue by mkuendig** [bitnami/charts#3506]
https://github.com/bitnami/charts/blob/a21e38daaee248201425e2b85cea271d4a43ce8d/bitnami/harbor/templates/trivy/trivy-sts.yaml#L68-L69

It lists security context user 0 and that doesn't work with our psp-restricted. Please change to non-root.

**Comment by rafariossaa** [comment]
Hi,
  That is only rendered if you have `volumePermissions.enabled` and `persistence.enabled`, if you use the default values.yml, that part is not generated.
  You can check it with: 
```
$ helm template myharbor -f values.yaml . | grep runAsUser
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
            runAsUser: 1001
```
  Would this work for you ?

**Comment by mkuendig** [comment]
Thanks Raffael. Maybe I misunderstand the persistence.enabled parameter. For our setup we do need persistence as we have settings that are stored on the containers and of course we want a persistence setup for all the containers, etc.

**Comment by rafariossaa** [comment]
Hi,
    `volumePermissions.enabled` is used in the cases where you need to set the permissions for the volume before the harbor container starts. From the REAMDE:
```

volumePermissions.enabled | Enable init container that changes volume permissions in the data directory (for cases where the default k8s runAsUser and fsUser values do not work)
```
  Persistence is enabled by default, so in you case I think the default values should work for you.

  Could you give it a try ?

**Comment by rafariossaa** [comment]
Hi,
  Did you tried ?
