### ISSUE TITLE
[bitnami/mongodb] Arbiter unhealthy after pod restart

### ISSUE THREAD

**Issue by ajila-fmeyer** [bitnami/charts#3519]
**Which chart**:
Name: bitnami/mongodb
Helm chart version: 9.0.0
App version: 4.4.0

**Describe the bug**
If MongoDB Arbiter is used and the pod is restarted due to a node crash, the MongoDB master can no longer be found and Arbiter becomes unhealthy.
![Screenshot 2020-08-26 at 09 02 27](https://user-images.githubusercontent.com/57093260/91272187-a39a1800-e77b-11ea-9095-05c7fadf6c07.png)

**To Reproduce**
1. helm install mongodb -f values.yaml bitnami/mongodb --namespace helm-mongodb

**Expected behavior**
I expect after a pod restart of Arbiter that the MongoDB cluster can be found and Arbiter can take over its function again.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
It seems to me that the variable $(MY_POD_NAMESPACE) in the check URL is not correct or cannot be resolved correctly.
At the first start of Arbiter, this variable will be replaced directly by the namespace, after that not anymore.

**Comment by andresbono** [comment]
Hi @ajila-fmeyer, thanks for reporting this issue. Could you please share the specific values that you are using? We would like to reproduce it.

**Comment by ajila-fmeyer** [comment]
> Hi @ajila-fmeyer, thanks for reporting this issue. Could you please share the specific values that you are using? We would like to reproduce it.

Hi @andresbono,
I'm using the [values-production.yaml](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values-production.yaml) with some additional values.

Additional values
`initdbScriptsConfigMap: init-mongo`
`extraEnvVarsSecret: mongodb-service-init-mongo-secrets`
`replicaCount: 2`

**Comment by ajila-fmeyer** [comment]
Hi @andresbono 
Were you able to reproduce the problem in your environment?
I have the same problem with the [values-production.yaml](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values-production.yaml) file without adjustments.

**Comment by andresbono** [comment]
Hi @ajila-fmeyer, thanks. We tried to reproduce it, but we couldn't exactly get the same error. This is what we tried:

- Deploy a kubernetes cluster with 2 workers:

```
$ kubectl get nodes
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   8h    v1.18.2
kind-worker          Ready    <none>   8h    v1.18.2
kind-worker2         Ready    <none>   8h    v1.18.2

- Install the chart and see the distributions of the pods in the nodes:

$ helm install mongo9 bitnami/mongodb --version 9.0.0 --values ./bitnami/mongodb/values-production.yaml

$ kubectl get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE     IP            NODE           NOMINATED NODE   READINESS GATES
mongo9-mongodb-0           2/2     Running   0          6m50s   10.244.2.13   kind-worker2   <none>           <none>
mongo9-mongodb-1           2/2     Running   0          6m27s   10.244.1.17   kind-worker    <none>           <none>
mongo9-mongodb-2           2/2     Running   0          6m9s    10.244.1.19   kind-worker    <none>           <none>
mongo9-mongodb-3           2/2     Running   0          5m55s   10.244.2.15   kind-worker2   <none>           <none>
mongo9-mongodb-arbiter-0   1/1     Running   0          4m45s   10.244.1.20   kind-worker    <none>           <none>
```

- Stop the node where mongodb-0 is scheduled:

```
$ docker stop kind-worker2
```

- After some time, (~5 minutes, depending on the toleration settings):

```
$ k get pods -o wide
NAME                       READY   STATUS        RESTARTS   AGE     IP            NODE           NOMINATED NODE   READINESS GATES
mongo9-mongodb-0           2/2     Terminating   0          16m     10.244.2.13   kind-worker2   <none>           <none>
mongo9-mongodb-1           2/2     Running       0          15m     10.244.1.17   kind-worker    <none>           <none>
mongo9-mongodb-2           2/2     Running       0          15m     10.244.1.19   kind-worker    <none>           <none>
mongo9-mongodb-3           2/2     Terminating   0          15m     10.244.2.15   kind-worker2   <none>           <none>
mongo9-mongodb-arbiter-0   1/1     Running       0          3m53s   10.244.1.21   kind-worker    <none>           <none>
```

- Restart the arbiter pod:

```
$ kubectl delete pod mongo9-mongodb-arbiter-0
$ kubectl logs mongo9-mongodb-arbiter-0
...
mongodb 15:10:35.75 INFO  ==> Trying to connect to MongoDB server mongo9-mongodb-0.mongo9-mongodb-headless.default.svc.cluster.local...
timeout reached before the port went into state "inuse"
```

Is this somehow similar to what you are getting?

---

> It seems to me that the variable $(MY_POD_NAMESPACE) in the check URL is not correct or cannot be resolved correctly.
> At the first start of Arbiter, this variable will be replaced directly by the namespace, after that not anymore.

It shouldn't be the case... You can check the values by exec'ing into the arbiter pods:

```
$ kubectl exec -it mongo9-mongodb-arbiter-0 -- bash -c 'echo $MONGODB_INITIAL_PRIMARY_HOST; echo $MY_POD_NAMESPACE'
mongo9-mongodb-0.mongo9-mongodb-headless.default.svc.cluster.local
default
```

https://github.com/bitnami/charts/blob/ed275c5f8748e233dfe85b9e1bcea2723a638cd9/bitnami/mongodb/templates/arbiter/statefulset.yaml#L86-L89

**Comment by ajila-fmeyer** [comment]
Hi @andresbono 
Thanks for your feedback.

Now I cannot reproduce my problem on our AKS infrastructure. 
It may well be that there was a problem with AKS and Kubernetes 1.16.10. With K8s 1.17.9 it looks good.

Sorry for the circumstances 😀

**Comment by andresbono** [comment]
Great! We are glad that you were able to solve the issue!

**Comment by ajila-fmeyer** [comment]
Hi @andresbono 

Problem came up on a newly AKS Cluster 👎 
Other users who use the Helm chart have reported the same issue on the Kubernetes Slack channel.

**Comment by andresbono** [comment]
But @ajila-fmeyer, why is that environment variable not substituted? Note that it is documented for Kubernetes:

https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

Can you try the `print-greeting` manifest from the link above in your cluster? Does it substitute the variables and print the correct message?

```
Warm greetings to The Most Honorable Kubernetes
```

**Comment by ajila-fmeyer** [comment]
Hello @andresbono 
Yes the example `print-greeting` works.

Now I have seen that the variables are not only not resolved on the arbiter but also on the MongoDB pods 👎 
Do you have any idea what else I could try?

**Comment by andresbono** [comment]
Hi @ajila-fmeyer, I can't think of any reason why the `print-greeting` example works perfectly and the substitutions are done but not in the case of mongodb-arbiter.

You might want to try `arbiter.extraEnvVars` like this:

```yaml
   extraEnvVars:
     - name: MONGODB_INITIAL_PRIMARY_HOST
       value: mongo9-mongodb-0.mongo9-mongodb-headless.default.svc.cluster.local 
```

And that should override the other unsubstituted environment variables. You may need to do this for other variables as well. Note that this is just a workaround, not a proper solution. Any additional information about the issue would be good to know.
