### ISSUE TITLE
[memcached] POD and Service are annotated to be scraped by Prometheus

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#3521]
**Which chart**:
Memcached - 4.2.21

**Describe the bug**
Metrics are scraped twice by Prometheus making Dashboards, Alerts and PromQL queries not reliable (unless you know this)

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy Prometheus from "Helm Stable"
2. Deploy Bitnami Memcached with these values
```
replicas: 3
persistence:
  enabled: false
metrics:
  enabled: true
```
3. Open Prometheus UI
4. Search for `sum(memcached_commands_total) by (job)` 

you will see that Prometheus is scraping Memcache through both SD, Kubernetes Endpoints (`memcached-metrics`) and Kubernetes POD

this makes my PromQL queries tricky because I normally rely on not having duplicated metrics on Prometheus

**Expected behaviour**
Metrics are scraped only once using Prometheus or Prometheus Operator

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
I noticed because this Grafana dashboard was showing some funny percentages
https://grafana.com/grafana/dashboards/11527

**Comment by miguelaeh** [comment]
Hi @carlosjgp ,
I think to avoid Kuberentesw to scrape from the pod you must remove the following annotations from your values: https://github.com/bitnami/charts/blob/82e614cd531638323d72ecd7b7e491073156fbb6/bitnami/memcached/values.yaml#L185
You can see the section `Scraping Pod Metrics via Annotations` at https://hub.helm.sh/charts/stable/prometheus

**Comment by carlosjgp** [comment]
> Hi @carlosjgp ,
> I think to avoid Kuberentesw to scrape from the pod you must remove the following annotations from your values: https://github.com/bitnami/charts/blob/82e614cd531638323d72ecd7b7e491073156fbb6/bitnami/memcached/values.yaml#L185
> You can see the section `Scraping Pod Metrics via Annotations` at https://hub.helm.sh/charts/stable/prometheus

Thanks for your answer @miguelaeh ,

I've put a workaround in place already but depending on the Helm version and Prometheus configuration might or might not work for other people

My approach has been very simple. I want to keep the metrics coming from the pods instead of the service so I'm doing...
```yaml
matrics:
  service:
    annotations:
      prometheus.io/scrape: "false"
```

By default Prometheus looks at that annotation value and only keeps metrics where it's `"true"`

But it's strange that this particular chart annotates the service and the pod automatically when you enable the metrics.

Is the first time I see this on a chart to be honest it would be better to default one or the other but not both IMO

**Comment by miguelaeh** [comment]
Hi @carlosjgp ,
Thank you very much for sharing your solution!

> Is the first time I see this on a chart to be honest it would be better to default one or the other but not both IMO

We try to configure the default options for what we think are the most common cases, but we are always open to change them in case we receive feedback requesting it. The only concern about changing default values is that it could modify users' deployments unexpectedly in an upgrade. So we usually wait for major versions.
