### ISSUE TITLE
[memcached] Documentation is outdated. replicas ==> replicaCount

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#3522]
**Which chart**:
Memcached - 4.2.21

**Describe the bug**
I'm running only 1 replica!

**To Reproduce**
Go to Helm hub
https://hub.helm.sh/charts/bitnami/memcached

use the values indicated on the documentation

Steps to reproduce the behaviour:
1. Deploy Bitnami Memcached with these values
```
replicas: 3
persistence:
  enabled: false
metrics:
  enabled: true
```
2. `kubectl get po --all-namespaces` shows only 1 replica

**Expected behaviour**
Setting the values indicated on the documentation I have the expected amount of replicas

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
I just realised while writing this other issue #3521 

Have you considered automating the generation of the chart documentation using something like [`helm-docs`](https://github.com/norwoodj/helm-docs)?

**Comment by carlosjgp** [comment]
another property not documented
`architecture`
https://github.com/bitnami/charts/blob/master/bitnami/memcached/values.yaml#L54

Once I've increased the replica count from 1 to 3 I now have an error saying that the property `architecture` has to be `high-availability`

```
<include "memcached.validateValues" .>: error calling include: template: memcached/templates/_helpers.tpl:180:51: executing "memcached.validateValues" at <fail>: error calling fail: VALUES VALIDATION: memcached: replicaCount The standalone architecture doesn't allow to run more than 1 replica. Please set a valid number of replicas (--set memcached.replicaCount=1) or use the "high-availability" architecture (--set architecture="high-availability"
```

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the report. Indeed, it seems that our documentation is outdated with the latest changes of the chart. I haven't taken a look at helm-docs, but it may be worth taking a look. In the meantime, we will fix the documentation. If you want to speed up the process feel free to send a PR and we will merge it.

**Comment by javsalgar** [comment]
Hi,

I've taken a look and it seems that the values are correctly documented now.

```
| `replicaCount`                           | Number of containers                                                                                   | `1`                                                          |
```

```
| `architecture`                           | Memcahed architecture. Allowed values: standalone or high-availability                                 | `standalone`                                                 |
```

These are extracts from the readme. Could you confirm if things are ok now?

**Comment by carlosjgp** [comment]
Yeah, it looks like those properties are now documented in the readme and values file 🚀
