### ISSUE TITLE
[postgresql-ha]how to enable pgpool logs by parameters?

### ISSUE THREAD

**Issue by hey-hoho** [bitnami/charts#3526]
I want to enable pgpool logs in pgpool.conf, I set the [pgpool.configuration] to 
```
log_destination = 'stderr,syslog'
log_line_prefix = '%t: pid %p: '
log_connections = on
log_hostname = on
log_statement = on
log_per_node_statement = on
log_client_messages = on
```
but get a error.
What should I do？
Thanks!

**Comment by juan131** [comment]
Hi @hey-hoho 

Could you provide a little more context about how you're testing this? I guess you created your own **values.yaml** with the parameter below, am I right?

```yaml
pgpool:
  configuration: |-
    log_destination = 'stderr,syslog'
    log_line_prefix = '%t: pid %p: '
    log_connections = on
    log_hostname = on
    log_statement = on
    log_per_node_statement = on
    log_client_messages = on
```

Please note that, when you use this parameter, you'll have to include the whole configuration file (not only the log settings).

When you install the chart without this parameter, this configuration file is created based on the default one and adapted automatically based on the settings passed via env. vars. However, when you use this parameter, the logic that creates/adapts it is skipped and the configuration you passed is used.

**Comment by hey-hoho** [comment]
I install this chart On Ranher AppStore, use a answer key to set  [pgpool.configuration] .

I'm also tried use the whole configuration file, but I got follow errors:

pgpool 06:49:19.35 
pgpool 06:49:19.35 Welcome to the Bitnami pgpool container
pgpool 06:49:19.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 06:49:19.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 06:49:19.35 Send us your feedback at containers@bitnami.com
pgpool 06:49:19.36 
pgpool 06:49:19.36 INFO  ==> ** Starting Pgpool-II setup **
pgpool 06:49:19.37 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 06:49:19.46 INFO  ==> Initializing Pgpool-II...
pgpool 06:49:19.49 INFO  ==> Custom configuration /opt/bitnami/pgpool/conf/pgpool.conf detected!
pgpool 06:49:19.50 INFO  ==> ** Pgpool-II setup finished! **
pgpool 06:49:19.52 INFO  ==> ** Starting Pgpool-II **
2020-08-27 06:49:19: pid 1: LOG:  could not open configuration file "/opt/bitnami/pgpool/conf/pool_hba.conf": No such file or directory
2020-08-27 06:49:19: pid 1: FATAL:  initializing pool password, failed to open file:"/opt/bitnami/pgpool/conf/pool_passwd"
2020-08-27 06:49:19: pid 1: DETAIL:  file open failed with error:"Read-only file system"

**Comment by juan131** [comment]
Hi @hey-hoho 

I am able to reproduce the issue.. It's a problem in the initalization logic of Pgpool's container that doesn't take into account there's a ConfigMap mounted in the configuration directory. 

I just opened an internal task to fix this issue. Thanks so much for reporting it.

**Comment by hey-hoho** [comment]
Expecting...

By the way ,Can I use items instand of the whole configuration file?😁

**Comment by juan131** [comment]
Hi @hey-hoho 

It should be easy to provide a way to append a piece of configuration to the default auto-generated configuration file. That said, it would be harder to ensure that it replaces original settings when passing configuration options that are also available in the default one.

**Comment by dani8art** [comment]
Hi @hey-hoho could you try to use the latest version of the chart? it seems the issue was fixed and the latest version works fine.

```console
$ helm repo update
```

```console
$ helm install pg bitnami/postgresql-ha -f values.yaml
```

```console
$ kubectl logs pg-postgresql-ha-pgpool-6665878777-484dl
pgpool 15:08:45.22 
pgpool 15:08:45.22 Welcome to the Bitnami pgpool container
pgpool 15:08:45.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 15:08:45.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 15:08:45.23 
pgpool 15:08:45.23 INFO  ==> ** Starting Pgpool-II setup **
pgpool 15:08:45.26 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 15:08:45.36 INFO  ==> Initializing Pgpool-II...
pgpool 15:08:45.43 INFO  ==> Generating pg_hba.conf file...
pgpool 15:08:45.44 INFO  ==> Generating pgpool.conf file...
pgpool 15:08:45.73 INFO  ==> Custom configuration '/opt/bitnami/pgpool/user_config/pgpool.conf' detected!. Adding it to the configuration file.
pgpool 15:08:45.74 INFO  ==> Generating password file for local authentication...
pgpool 15:08:45.81 INFO  ==> Generating password file for pgpool admin user...
pgpool 15:08:45.84 INFO  ==> ** Pgpool-II setup finished! **

pgpool 15:08:45.86 INFO  ==> ** Starting Pgpool-II **
2020-09-09 15:08:45: pid 1: LOG:  Backend status file /opt/bitnami/pgpool/logs/pgpool_status does not exist
2020-09-09 15:08:45: pid 1: LOG:  memory cache initialized
2020-09-09 15:08:45: pid 1: DETAIL:  memcache blocks :64
```
