### ISSUE TITLE
[bitnami/airflow] What would be the steps to create a local release of the chart to test

### ISSUE THREAD

**Issue by pankajkoti** [bitnami/charts#3531]
Hi Team,
I am using the following command from the charts directory to build and use a chart locally to test: 
tar -czvf airflow-6.4.0.tgz airflow

But, it doesn't seem to build it correctly. Can you please guide on what would be the way

**Comment by juan131** [comment]
Hi @pankajkoti 

Try with `helm fetch` command to retrieve the tarball of a specific chart version. E.g.:

```console
$  helm fetch bitnami/airflow --version 6.4.0
```

Find more information in the link below:

- https://v2.helm.sh/docs/helm/#helm-fetch

**Comment by pankajkoti** [comment]
Thank you for the information
