### ISSUE TITLE
Kafka broker consuming Full system memory 

### ISSUE THREAD

**Issue by skyfirst93** [bitnami/charts#3532]
The name (and version) of the affected chart
Kafka
name: kafka
version: 6.0.1
appVersion: 2.3.0

**Describe the bug**
The issues is kafka pod where there are multiple java process (kafka jar files) are getting started. There are eating up the system memory. In One day the system memory used up was around 10gb. 
This is a single instance of kafka running in the k8s cluster. There is no resource limit also set on the statefulset

**To Reproduce**
1. Deployed Kafka with single 1 instance
2. after some time memory was getting used up 
3. inside Kafka pod we see the below output 
```
ps aux
1001    1  0.3  2.9 4768852 898148 ?      Ssl  Aug25   3:44 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     10600  0.3  2.9 4768852 898148 ?      Ssl  Aug25   3:44 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     10898  0.2  2.9 4768852 907136 ?      Ssl  Aug25   3:43 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     11197  0.2  2.3 4768852 732016 ?      Ssl  Aug25   3:37 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     11495  0.2  2.4 4768852 746004 ?      Ssl  Aug25   3:33 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     11793  0.3  3.3 4768852 1042916 ?     Ssl  Aug25   4:00 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     12091  0.2  2.3 4768852 724388 ?      Ssl  Aug25   3:33 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     12390  0.5  4.4 4768852 1375948 ?     Ssl  Aug25   6:16 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     12688  0.3  2.7 4768852 836968 ?      Ssl  Aug25   3:49 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     12986  0.3  2.8 4768852 864532 ?      Ssl  Aug25   3:48 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     13284  0.5  4.4 4768852 1370164 ?     Ssl  Aug25   6:17 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
1001     13582  0.2  2.5 4768852 773580 ?      Ssl  Aug25   3:39 java -Xmx2048m -Xms2048m -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:Init
```

**Expected behavior**
I want to understand what could be the reason why kafka pod is creation these extra processes.
**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

(paste your output here)
```

- Output of `kubectl version`:

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeSt ate:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeSt ate:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Could you provide more information about the load it is receiving? I would like to reproduce the issue on my side. Do the process get spawned immediately or after some time?

**Comment by skyfirst93** [comment]
Hi @javsalgar ,
It is receiving logs of around 20 microservices continuously on individual topics. 
The process are getting spawned over a period of time. 
The number is increasing as the memory usage is increasing 

Heap size set currently is 2Gb. 

Thanks,
Akash

**Comment by javsalgar** [comment]
Hi,

It looks to me that this behaviour is part of how Kafka works. Probably it needs to have some performance tuning settings to have more CPU and memory control. My advice would be to first contact the Kafka developers so they can provide more feedback on the best configuration for your requirements.

https://kafka.apache.org/contact

Please let us know what they say, in case we need to change something on our side.

**Comment by skyfirst93** [comment]
The issue was with my configuration. Hence, closing. Thanks for the help

**Comment by javsalgar** [comment]
Hi!

Thanks for letting us know! We would be very grateful if you could share which setting were the ones causing issues.

**Comment by skyfirst93** [comment]
Hi 
The issues was that the extra processes where kafka-consumers consuming on different topics.They were started by a different application inside the kafka pod and were not getting killed. 
Them Continues running was eating up the memory. After killing them the issue was not seen

**Comment by javsalgar** [comment]
Thanks for sharing!
