### ISSUE TITLE
[bitnami/airflow] How to install packages from a private repository?

### ISSUE THREAD

**Issue by ElriesV** [bitnami/charts#3533]
Hi there,

I'm trying to figure out a proper way to install a package from a private Gitlab repository in the bitnami/airflow helm chart. I have been able to sync a `requirements.txt` to my airflow instance and it seems to work properly (e.g. numpy). However, I have no clue how to add a package from a private repo in there.

I've tried adding `git+git://user:token@gitlab.com/<user>/<repository>.git#egg=<package_name>` to the requirements.txt, but this doesn't seem to work. I still get a 'module not found' error on my DAGs.

Although this seems like an issue many organizations face, I can't find anything in the documentation around adding private packages to the helm deployment. 

Can someone point me in the right direction here? Much appreciated!

**Comment by juan131** [comment]
Hi @ElriesV 

Did you give a try to cloning the DAGs from a repository? Please take a look to the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/airflow#option-3-get-your-dag-files-from-a-git-repository

**Comment by ElriesV** [comment]
Hi @juan131,

Yes, cloning DAGs works like a charm! It is the dependencies that I'm requiring in these DAGs that are causing me headaches. For example, I am using a DAG-file that imports a python package that is not available on PIP. It is my own, private package hosted on Gitlab. Obviously, the package has to be installed for me to be able to import and use it in my DAG file. 

I can't find a way to install the package from my private repository, however. Publicly available packages, such as numpy and pandas, are working fine using the `requirements.txt `file.

**Comment by juan131** [comment]
I understand @ElriesV 

I am afraid that it's not possible to do automatically at this very moment, since we don't provide a way to mount your SSH credentials so you can install python packages from private repositories.

I created a task and added it to our backlog to add this feature.

**Comment by ElriesV** [comment]
hmm that's unfortunate.

Do you have an idea how this can normally be handled in the standalone docker container? Or will I be facing the same issue then?

BR,
Elroy

**Comment by juan131** [comment]
Hi @ElriesV 

I'm afraid that you will face very similar issues since there's no "easy" way to pass your SSH credentials to the standalone container either.

**Comment by ashishmgofficial** [comment]
@juan131 I have mounted the requirements.txt and it seems to install the dependencies in the scheduler container but the workers complain that the module is not found. Any help ?

**Comment by juan131** [comment]
Hi @ashishmgofficial 

Could you please share how you're mounting  this `requirements.txt` in the workers? Are you using the `worker.extraVolumes` and `worker.extraVolumeMounts` parameters of the chart?

**Comment by ashishmgofficial** [comment]
@juan131 

Yes I have mounted using ```worker.extraVolumes``` and ```worker.extraVolumeMounts``` as below :  

```
  extraVolumeMounts:
    - name: airflow-pip-requirements
      mountPath: /bitnami/python    
  extraVolumes:        
    - name: airflow-pip-requirements
      persistentVolumeClaim:
         claimName: airflow-pip-requirements-claim
```

**Comment by juan131** [comment]
Hi @ashishmgofficial 

Did you modify the default command/args used on worker nodes so `pip install ...` is executed before starting the worker? Sth like:

```yaml
worker: 
  command:
    - /bin/bash
  args:
    - -ec
    - |
      pip install -r /bitnami/python/requirements.txt
      /app-entrypoint.sh /run.sh
```

**Comment by NicolasRisi** [comment]
hi @juan131 ,

I have the same problem. My worker pods doesn't install python packages from requirements.txt

We can't overwrite the command of the worker container in a pod (kubernetesExecutor) because of [this template](https://github.com/bitnami/charts/blob/0f29afcb16e74d5b9ad87c23bfaad3efadea1f5d/bitnami/airflow/templates/config/configmap.yaml)

As the kubernetes documentation state :
![image](https://user-images.githubusercontent.com/11333761/109887875-da993b00-7c82-11eb-80cf-47d08dccfdd9.png)

I think the args overwrite the CMD of the worker dockerfile.

![image](https://user-images.githubusercontent.com/11333761/109888086-349a0080-7c83-11eb-9b53-051325cca571.png)

So we don't have the [[ "$1" == "/run.sh" ]] condition in [this file](https://github.com/bitnami/bitnami-docker-airflow-worker/blob/2.0.1-debian-10-r3/2/debian-10/rootfs/app-entrypoint.sh) and we don't launch the pip install requirements.

**Comment by juan131** [comment]
You're right @NicolasRisi 

If you're using the `kubernetesExecutor` executor, it'll use the **pod_template.yaml** you pointed to, and there's no way to extend/customize the command/args used in the worker.

It's extensible though, when using the `CeleryExecutor`, see:

- https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/worker/statefulset.yaml#L85

Would you like to contribute with a PR adding sth similar to the solution shown above to the **pod_template.yaml**?

**Comment by NicolasRisi** [comment]
I tested this approach but unfortunately it doesn't work ....
When we override the command with :
![image](https://user-images.githubusercontent.com/11333761/110003341-90fa3000-7d16-11eb-8109-786b6219e9bc.png)

We have problems with tini.
![image](https://user-images.githubusercontent.com/11333761/110003429-a7a08700-7d16-11eb-84da-1f57241449d2.png)

It doesn't work neither with "/app-entrypoint.sh /run.sh".

I think this is because the bash context of the command ... "bash -ec ..."

But i think the problem can be solved by modifying [this file](https://github.com/bitnami/bitnami-docker-airflow-worker/blob/master/2/debian-10/rootfs/app-entrypoint.sh) in the worker repository.

Can we just move the python packages installation out of the condition "if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]" (care with the indentation ...)

I'm not sure about the impact.

**Comment by juan131** [comment]
Hi @NicolasRisi 

Could you try with sth like this?

```yaml
worker: 
  command:
    - /bin/bash
  args:
    - -ec
    - |
      (PUT YOUR CUSTOM ACTIONS HERE)
      /app-entrypoint.sh /run.sh
```

**Comment by NicolasRisi** [comment]
Yes i already tried but the args are overwritten with "airflow tasks ...."

**Comment by juan131** [comment]
Hi @NicolasRisi 

Could you share the modifications you did in the ConfigMap (**pod_template.yaml** section)? I must be missing something here since I don't fully get why the arguments are overwritten.

**Comment by NicolasRisi** [comment]
![image](https://user-images.githubusercontent.com/11333761/110305294-e7a88800-7ffc-11eb-91a4-669b06fb1357.png)

We are in KubernetesExecutor so, 1 task will pop 1 worker pod which execute the task. So the args are overwritten with the command "airflow tasks run ..." which execute the task. It's dynamic depending of the task. If we set ourself the args (and let's imagine they are not overwritten), when the worker will pop, it will execute nothing.

We don't have a Redis in pubsub to read the dynamic args like in celery executor.

**Comment by juan131** [comment]
Hi @NicolasRisi 

I see what you mean. The argumenta are dynamically changed by the scheduler when creating the new worker pods.

Assuming it only modifies the `args`, respecting the `command` defined in the **pod_template.yaml**, you could do sth like this:

```yaml
worker: 
  command:
    - /bin/bash
    - -ec
    - |
      if [ ! $EUID -eq 0 ] && [ -e "$LIBNSS_WRAPPER_PATH" ]; then
          echo "airflow:x:$(id -u):$(id -g):Airflow:$AIRFLOW_HOME:/bin/false" > "$NSS_WRAPPER_PASSWD"
          echo "airflow:x:$(id -g):" > "$NSS_WRAPPER_GROUP"
          export LD_PRELOAD="$LIBNSS_WRAPPER_PATH"
      fi
      if [[ -f "/bitnami/python/requirements.txt" ]]; then
          source /opt/bitnami/airflow/venv/bin/activate
          pip install -r /bitnami/python/requirements.txt
          deactivate
      fi
      nami_initialize airflow-worker
      exec tini -- /run.sh "$@"
```

**Comment by NicolasRisi** [comment]
Hi @juan131
Thanks, i'll try this command this week or next week. I'll make the PR if it works :)

**Comment by juan131** [comment]
Great @NicolasRisi ! Please keep us updated about your progress

**Comment by RaedShabbir** [comment]
What would be considered the best workaround for this atm? 
Just extending the three images for web, scheduler and worker? 
Thanks

**Comment by juan131** [comment]
Hi @RaedShabbir 

There are two issues discussed here:

- Problems to include a custom **requirements.txt** on worker nodes when using the "kubernetesExecutor"
- The chart doesn't provide a way to mount your SSH credentials so you can install python packages from private repositories.

What is actually your problem?

**Comment by RaedShabbir** [comment]
Hello, 

My issue is the second 

> The chart doesn't provide a way to mount your SSH credentials so you can install python packages from private repositories.

**Comment by RaedShabbir** [comment]
It seems like extending the docker images worked, but is there something faster? 
Which containers actually require dag specific libraries to be installed? I extended the web, scheduler and worker images and installed the relevant packages. 

Would I be able to run something like the following from inside the relevant containers? 
`pip install <path_to_sync'd_dags_repo>`

**Comment by juan131** [comment]
Hi @RaedShabbir 

> It seems like extending the docker images worked, but is there something faster?

Currently I don't think there's another option to install python packages from private repos. We have a task to support this feature, but we didn't have the chance to work on it yet.

---

You might get it working by using the `XXX.extraVolumes` and `XXX.extraVolumeMounts` parameters. Using these parameters you can mount any custom volume/configmap/secret in any path of the container. So, I guess you could potentially mount your SSH keys in the containers.

**Comment by RaedShabbir** [comment]
Hello @juan131 thanks for the info, went with the docker route, though I'm having some issues loading the dag into the web UI, they work fine from the command line, but the UI displays` BrokenDag` & strange Import Errors  Do you know if I have to extend the bitnami/git images as well? Which images in specific would I have to install my private packages on?

**Comment by juan131** [comment]
> went with the docker route

Do you mean that you're mounting the SSH keys in the container by building your custom one?

> Do you know if I have to extend the bitnami/git images as well?

It depends.. If you're already bundling them in the container, you don't need to do so. In case you're cloning the DAGS from a repo as explained in [this guide](https://github.com/bitnami/charts/tree/master/bitnami/airflow#option-2-get-your-dag-files-from-a-git-repository) you'll have to add them in case the repository requires SSH.

> Which images in specific would I have to install my private packages on?

`bitnami/airflow`, `bitnami/airflow-scheduler` and `bitnami/airflow-worker`

**Comment by RaedShabbir** [comment]
> Do you mean that you're mounting the SSH keys in the container by building your custom one?

Not quite, I am extending the relevant images by installing the private packages directly onto them. So no SSH keys involved. 
I access the Dags through the git sync approach and keep them on a separate repository. 

>It depends.. If you're already bundling them in the container, you don't need to do so. In case you're cloning the DAGS from a repo as explained in this guide you'll have to add them in case the repository requires SSH.

I ended up not needing ssh using the method described here to access the private dags repo https://github.com/bitnami/charts/issues/5645. Then the base image already had my packages installed. 

Ideally it'd awesome to run a 
pip install <path to private repo>, but don't have time to setup/test right now  with the keys

**Comment by juan131** [comment]
Hi @RaedShabbir 

> I ended up not needing ssh using the method described here to access the private dags repo #5645. Then the base image already had my packages installed.

That makes total sense.

Indeed, that would be the best scenario for production environments since you don't need to download/install python packages while initializing Airflow. This improves the boot time and it's suitable for K8s with no access to internet.

The reason why we provide a mechanisms to do it dynamically is to avoid users having to build their own images extending Bitnami ones.

**Comment by sleepo-chin** [comment]
Hello, @juan131 I have 2 questions.

1. I've already added cmd&args in values.yaml but when I upgrade helm. Pod airflow worker status is CrashLoopBackOff
2. from problem 1 .so I tried to exec in container airflow-worker for manually install python package. but I got an error that
 
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/.local'
Check the permissions.
```
I think problem 1 related to 2 or not? what should I do in args pip install for permission in containner?

**Comment by juan131** [comment]
Hi @sleepo-chin 

Some questions:

- Are you using the workaround I mentioned on [this response](https://github.com/bitnami/charts/issues/3533#issuecomment-793625324)?
- What executor are you using: `CeleryExecutor ` or `kubernetesExecutor`?
- Where are you trying to install the Python packages (what directory)? Please note that the worker is running with an unprivileged user by default

**Comment by sleepo-chin** [comment]
> Are you using the workaround I mentioned on this response?
I modified values.yaml with that
```
worker: 
  command:
    - /bin/bash
  args:
    - -ec
    - |
      pip install -r /bitnami/python/requirements.txt
      /app-entrypoint.sh /run.sh
```
but pod can't start with status crashloopbackoff. I will try to your mentioned.

> What executor are you using: CeleryExecutor or kubernetesExecutor?

Now, I used CeleryExecutor in a demo. In the next step, I will use Kubernetesexecutor.

>  Where are you trying to install the Python packages (what directory)? Please note that the worker is running with an unprivileged user by default

I think the pod in the first answer can't start.so I used the default values.yaml and exec in the worker and try to install the package in bitnami/python/requirements.txt to find root cause in the first answer.

**Comment by marcosbc** [comment]
Hi @sleepo-chin, note that the entrypoint should already take care of installing dependencies, see run.sh: https://github.com/bitnami/bitnami-docker-airflow/blob/cafc8eab1efddb5efda5a00cc861ef10f35f1d49/1/debian-10/rootfs/run.sh#L14

Also, you seem to be using an old release of the Airflow chart. Note that we introduced major changes to the container install logic in [`1.10.15-debian-10-r17` and `2.0.1-debian-10-r50`](https://github.com/bitnami/bitnami-docker-airflow#11015-debian-10-r17-and-201-debian-10-r50).

As for your issue, note that the proper way to install packages would be to load the virtual env environment, if not, Pip will try to install packages for the entire system, for which non-root users lack privileges.

**Comment by tomandevcc** [comment]
**sorry, How I can install packages in KubernetesExecutor?**

Now I have git-sync (for load dags) and setting (KubernetesExecutor) but I don't know how to set values.yaml for install package and pod-template.yaml

I add extraVolumeMount and extraVolume by readme

```
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
  ## Add extra volumes
  ##
  extraVolumes:
    - name: requirements
      configMap:
        name: requirements

```
**What should I do next?**

**Comment by marcosbc** [comment]
@tomandevcc Refer to these instructions in the README https://github.com/bitnami/charts/tree/master/bitnami/airflow#install-extra-python-packages

In summary you need to mount the file `/bitnami/python/requirements.txt`. To do that you would create the volume `/bitnami/python` and the volume mount `requirements.txt` inside there. Check this WordPress example:

```yaml
extraVolumeMounts:
  - name: wordpress-config
    mountPath: /opt/bitnami/wordpress/wp-config.php
extraVolumes:
  - name: wordpress-config
    configMap:
      name: MYCONFIGMAP
      items:
        - key: wp-config.php
          path: wp-config.php
```

**Comment by sagisd** [comment]
> Hi @RaedShabbir
> 
> > It seems like extending the docker images worked, but is there something faster?
> 
> Currently I don't think there's another option to install python packages from private repos. We have a task to support this feature, but we didn't have the chance to work on it yet.
> 
> You might get it working by using the `XXX.extraVolumes` and `XXX.extraVolumeMounts` parameters. Using these parameters you can mount any custom volume/configmap/secret in any path of the container. So, I guess you could potentially mount your SSH keys in the containers.

Hi @juan131, 
I want to clone the dags from local git so I've mount the ssh key (pem) but unable to clone the repo.
I changed the git clone in ./templates/_git_helpers.tpl (for testing only..)
`GIT_SSH_COMMAND=' ssh -F /dev/null -i <PATH_TO_PEM_FILE>' git clone USER@HOST:PATH_TO_GIT_REPO /dags_{{ include "airflow.git.repository.name" . }} || true`

I'm getting the error:
```
Cloning into '/dags_main'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

GIT_PATH_TO_REPO is located on the same machine when I'm using Helm

**Comment by juan131** [comment]
Hi @sagisd 

> I changed the git clone in ./templates/_git_helpers.tpl (for testing only..)

Could you share the changes you did? I'm not very sure about the exact changes you introduced.

> GIT_PATH_TO_REPO is located on the same machine when I'm using Helm

I guess you mean `PATH_TO_GIT_REPO`, right?
Also, is the GIT server accessible from the K8s cluster where you are installing the chart? Please note that it doesn't matter if the machine you're using to run the "helm install" command has connectivity to clone the repo, it must be accessible from inside the K8s cluster so the init container can access it.

**Comment by sagisd** [comment]
@juan131 thanks for you reply, 

>Could you share the changes you did? I'm not very sure about the exact changes you introduced.

I changed the file: ./templates/_git_helpers.tpl

```
-      is_mounted_dir_empty "/dags_{{ include "airflow.git.repository.name" . }}" && git clone {{ .repository }} --branch {{ .branch }} /dags_{{ include "airflow.git.repository.name" . }} || true
+      is_mounted_dir_empty "/dags_{{ include "airflow.git.repository.name" . }}" && GIT_SSH_COMMAND=' ssh -i /bitnami/certs/ed25519.pem'; git clone sagisd@example.com:/mnt/git/myrepo /dags_{{ include "airflow.git.repository.name" . }} || true
```
/bitnami/certs/ed25519.pem is mounted on the pod
example.com is the same machine that running the minikube

I have removed the {{.repository}} and {{.branch}} values - just to test the command, I will rewrite it once it's working.
>Also, is the GIT server accessible from the K8s cluster where you are installing the chart? Please note that it doesn't matter if the machine you're using to run the "helm install" command has connectivity to clone the repo, it must be accessible from inside the K8s cluster so the init container can access it.

Could you tell me how to do that? I can't use ssh\ping on the pod

I'm using minikube for testing, the production cluster is composed of a master and two nodes (3 machines)

**Comment by sagisd** [comment]
@juan131 thanks!
you're right
```console
sagisd@example.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
Actually I found a workaround - I've created nginx host that let me clone like github so no need for any pem file
`git clone git.example.com`

Now I'm facing with an issue regarding the ingress but it's not related to this issue :P
Thanks for your help!

**Comment by juan131** [comment]
Great @sagisd !!

I'm very glad you were able to workaround the issue and clone the repos including the DAGs.

**Comment by gowthamprabhu** [comment]
> https://github.com/bitnami/charts/tree/master/bitnami/airflow#install-extra-python-packages

Hello, I'm little new to Kube, How do I map the requirements.txt using Helm to mounts ?

**Comment by rafariossaa** [comment]
hi @gowthamprabhu ,
  Could you take a look to [this](https://github.com/bitnami/charts/issues/6190) ? 
  In any case my advise is to take a look to kubernetes documentation first to get familiar with this topic.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by jamesmedice** [comment]
having this worked fine the installation, but on web and scheduler i got error on airflow FE interface.
this is for worker:
          image: bitnami/airflow-worker:2.2.3-debian-10-r40
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-ce"
            - |              
                echo "[AIRFLOW WORKER STARTING]"
                source /opt/bitnami/airflow/venv/bin/activate
                pip install --no-cache-dir -r /bitnami/python/requirements.txt 
                echo "[AIRFLOW WORKER CUSTOM LIBS INSTALLED]"
                . /opt/bitnami/scripts/airflow-worker-env.sh
                . /opt/bitnami/scripts/libairflowworker.sh
                airflow_generate_config # Generate the config file
                cp /opt/bitnami/airflow/airflow.cfg /opt/bitnami/airflow/k8s-executor-config/airflow.cfg
		  volumeMounts:
            - name: k8s-executor-config
              mountPath: /opt/bitnami/airflow/k8s-executor-config
            - name: requirements
              mountPath: /bitnami/python/requirements.txt              
              subPath: requirements.txt
      volumes:
        - name: k8s-executor-config
          emptyDir: {}
        - name: requirements
          configMap:
            name: airflow-requirements


this is for web and scheduler

      containers:
         - name: airflow-scheduler
          image: bitnami/airflow-scheduler:2.2.3-debian-10-r40
          imagePullPolicy: "IfNotPresent"
          env: 
          volumeMounts: 
            - name: requirements
              mountPath: /bitnami/python/requirements.txt              
              subPath: requirements.txt 
      volumes: 
        - name: requirements
          configMap:
            name: airflow-requirements

on the airflow logs i see : 
[2023-12-18, 09:20:45 UTC] {taskinstance.py:1700} ERROR - Task failed with exception
    from sas7bdat import SAS7BDAT
ModuleNotFoundError: No module named 'sas7bdat'
