### ISSUE TITLE
[bitnami/postgresql-ha] /opt/bitnami/pgpool/conf/pool_passwd is not manageable/persistent

### ISSUE THREAD

**Issue by sylver** [bitnami/charts#3538]
**Which chart**:
postgresql-ha 3.2.3 (didn't try last one yet)

**Describe the bug**
Maybe I misunderstand the provisioning and management of users' permissions, but it seems we can manage users credentials only during initScripts at the first install, any subsequent new user or password (added manually in postgres and editing the `pgpool_passwd` file) change won't be taken into account by pgpool.  
Also restarting the service clear the `pgpool_passwd` file, denying access afterward.

**To Reproduce**
- after a successful deployment of the chart
- create a new postgresql user and add its password in `/opt/bitnami/pgpool/conf/pool_passwd` in order to login
- simulate a restart/failure of the only pod of the service `pgpool`
- any new login attempt with the user fails, also other users can't login either.

**Expected behavior**
Persistence of credentials with pgpool, maybe with a configmap/volume mount
Also maybe I just didn't get the right way to do it, so that would be more of a question than a bug then.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-fd1ea7", GitCommit:"fd1ea7c64d0e3ccbf04b124431c659f65330562a", GitTreeState:"clean", BuildDate:"2020-05-28T19:06:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @sylver ,
If I understood it correctly you want to provide to pgpool the postgresql users and passwords, so I think you are looking for something like: `PGPOOL_POSTGRES_CUSTOM_PASSWORDS` `PGPOOL_POSTGRES_CUSTOM_USERS`. Those container are supported in the Chart under `pgpool.customUsers` and `pgpool.customUsers.passwords`. See https://github.com/bitnami/charts/blob/d0045d9f223ec6b81145e9901a170f281cb9e0e9/bitnami/postgresql-ha/values.yaml#L325
Regards.

**Comment by sylver** [comment]
Hi @miguelaeh,

Thanks for you answer.

I'm looking for a way to actually manage users outside of the chart initial provisioning.
We use a complex multi-projects IaC and users/dbs for the database are defined and managed in another project than the one provisioning the database server itself with a dedicated postgresql provider linked to our apps deployment.

`pgpool.customUsers` is still something to use during chart/server deployment and I can't change it later on.
But looking at your documentation, there's `pgpool.customUsersSecret` that would maybe fit my need and I could manipulate in our users provider, what do you think ?
That would also require a restart of the pgpool service if modified I guess though ?

What's the expected format of this secret ? Is it strictly the content of the `pgpool_passwd` file ? Do I need to provide also the `postgres` admin user credentials or is it still handled outside of the secret ?

Thanks !

**Comment by sylver** [comment]
> 
> What's the expected format of this secret ? Is it strictly the content of the `pgpool_passwd` file ? Do I need to provide also the `postgres` admin user credentials or is it still handled outside of the secret ?

nvm, I had a peek into your templates code and found out what I needed to know to test this custom secret : 

https://github.com/bitnami/charts/blob/f8d79eacbefae13f60e93fe7fe85741c03fb9d69/bitnami/postgresql-ha/templates/pgpool/deployment.yaml#L66-L77

**Comment by miguelaeh** [comment]
Hi @sylver ,
I am glad you found the proper format.

> That would also require a restart of the pgpool service if modified I guess though ?

Regarding that, yes, you will need to restart the container to apply the changes to the users file.

**Comment by sylver** [comment]
Hi @miguelaeh,

Sorry for the delay on coming back to you.

I can confirm that using `pgpool.customUsersSecret` resolves my issue. That way I'm able to update the `pgpool_passwd` file with persistence, the only requirement is to restart the service afterward to take effect.

Thanks again for your help.
