### ISSUE TITLE
PLAINTEXT for Internal and SSL for external clients

### ISSUE THREAD

**Issue by etavene** [bitnami/charts#3539]
**Which chart**:
kafka charts 

**Describe the bug**

I want to configure internal kafka consumers  with PLAINTEXT and External consumers with SSL. Is this supported in current kafka charts ?  

listener.security.protocol.map=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:SSL

I am able to configure both either SSL or PLAINTEXT

**Comment by javsalgar** [comment]
Hi,

I think that the chart value `listenerSecurityProtocolMap` should do the trick. Please let us know if this works for you

**Comment by etavene** [comment]
@javsalgar Thanks for your reply. The said option didnt work. 

If I mention auth.clientProtocol as PLAINTEXT,  all the information related to  ssl.keystore  ssl.truststore missing in 
/opt/bitnami/kafka/config/server.properties file. 

So, I changed the settings as shown below

auth:
  clientProtocol: tls
  interBrokerProtocol: plaintext
  jksSecret: kafka-jks2
listeners: []
advertisedListeners: []
listenerSecurityProtocolMap: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:SSL" 

The kafka log shows " Configuring Kafka for client communications with PLAINTEXT authentication"
So the server.properties doesn't have any entries related to truststore and keystore. 

The libkafka.sh file shows, only if protocol is SSL, then only ssl related information is available in server.properites

 if [[ "$protocol" = "SASL_SSL" ]] || [[ "$protocol" = "SSL" ]]; then
            kafka_configure_ssl

kafka_configure_ssl() 
    kafka_server_conf_set ssl.keystore.location "$KAFKA_CONF_DIR"/certs/kafka.keystore.jks

so the libkafka.sh is only considering $client_protocol as either SSL or PLAINTEXT, it is not considering external client protocol.

**Comment by javsalgar** [comment]
Thank you very much for the input. One last thing, did you try injecting your custom configuration file? If the configuration is injected then all the auto-configuration steps would be skipped.

**Comment by etavene** [comment]
Yes, I injected configuration, as you told all auto-configuration steps were skipped and i was able to acheive what I wanted.  But if we skip auto-configuration, parameters such as KAFKA_CFG_ADVERTISED_LISTENER and KAFKA_CFG_BROKER_ID  are hard to manage per instance in a statefulset configuration.

**Comment by javsalgar** [comment]
Hi,

I agree that we could improve the user experience when working with this kind of configuration. I will open a task for allowing the configuration of the `EXTERNAL` section of the listener map. I cannot guarantee an ETA, but we will update the ticket as soon as we have more news.

**Comment by etavene** [comment]
@javsalgar  Thanks for you help. 
One more clarification is required. For both "tls" and "mtls" options, the server.properties had ssl.client.auth=required field. I expected this option doesn't require to be added in server.properites when auth.clientProtocol is "tls"

**Comment by YuryHrytsuk** [comment]
@javsalgar, any updates?

**Comment by javsalgar** [comment]
Hi, I am afraid it is still in our backlog. However, I recall that we did several improvements in the kafka authentication mechanisms. However, I believe that this specific issue is still not fixed.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
