### ISSUE TITLE
[bitnami/postgresql-ha] no privileges were granted for "public",can not receive request

### ISSUE THREAD

**Issue by zffocussss** [bitnami/charts#3546]
**Which chart**:
postgresql-ha

**Describe the bug**

kubectl get pods

- pgsql-ha-postgresql-ha-pgpool-bc856c47c-lrzfv   1/1     Running   0          6h18m
- pgsql-ha-postgresql-ha-postgresql-0             2/2     Running   0          6h18m
- pgsql-ha-postgresql-ha-postgresql-1             2/2     Running   0          6h17m

2020-08-28 10:38:08.704 GMT [13035] WARNING:  no privileges were granted for "public"
2020-08-28 10:38:08.704 GMT [13035] CONTEXT:  SQL statement "GRANT ALL ON SCHEMA "public" TO CURRENT_USER"

postgresql is not runing well.

**To Reproduce**

helm install --name pgsql-ha ./postgresql-ha \
--namespace kong \
--set postgresqlImage.tag=12-debian-10 \
--set postgresqlImage.debug=true \
--set global.postgresql.database=xxx \
--set global.postgresql.username=xxx \
--set global.postgresql.password=xxx \
--set persistence.enabled=true \
--set volumePermissions.enabled=true \
--set postgresql.syncReplication=true \
--set metrics.enabled=true \
--set networkPolicy.enabled=false \
-f ./postgresql-ha/values-production.yaml

**Expected behavior**
it should be running well,and it can accept request

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
logs in pg-pool
the loop of error messages

2020-08-28 10:13:27: pid 1095: DETAIL:  EOF encountered with frontend
2020-08-28 10:13:27: pid 693: ERROR:  unable to read data from frontend
2020-08-28 10:13:27: pid 693: DETAIL:  EOF encountered with frontend
2020-08-28 10:13:29: pid 1497: ERROR:  unable to read data from frontend
2020-08-28 10:13:29: pid 1497: DETAIL:  EOF encountered with frontend
2020-08-28 10:13:29: pid 1090: ERROR:  unable to read data from frontend
2020-08-28 10:13:29: pid 1090: DETAIL:  EOF encountered with frontend
2020-08-28 10:13:30: pid 1015: ERROR:  unable to read data from frontend
2020-08-28 10:13:30: pid 1015: DETAIL:  EOF encountered with frontend
2020-08-28 10:13:30: pid 1084: ERROR:  unable to read data from frontend

**Comment by andresbono** [comment]
Hi @zffocussss, we could isolate and reproduce the issue with the following options:

```
$ helm install postgres-fail ./postgresql-ha --set postgresqlImage.tag=12-debian-10 --set postgresql.syncReplication=true

$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgres-fail-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ kubectl run postgres-fail-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:12-debian-10 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql -h postgres-fail-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

postgres=# CREATE DATABASE test;
# It hangs forever
^C
Cancel request sent
WARNING:  canceling wait for synchronous replication due to user request
DETAIL:  The transaction has already committed locally, but might not have been replicated to the standby.
CREATE DATABASE
```

So it seems the issue is related to the synchronous replication.

It is interesting that with PostgreSQL 11, the error is not appearing:

```
$ helm install postgres-ok ./postgresql-ha --set postgresqlImage.tag=11-debian-10 --set postgresql.syncReplication=true

$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgres-ok-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ kubectl run postgres-ok-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:11-debian-10 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql -h postgres-ok-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

postgres=# CREATE DATABASE test;
CREATE DATABASE
```

Can you try by using PostgreSQL 11 or not enabling `syncReplication` to confirm the source of the issue?
