### ISSUE TITLE
[bitnami/kibana] doesn't emit podAnnotations

### ISSUE THREAD

**Issue by craigminihan** [bitnami/charts#3549]
**Which chart**:
bitnami/kibana-7.9.0

**Describe the bug**
When `podAnnotations` is specified via --set/--set-string it isn't emitted in the markup.

**Expected behavior**
The kibana pods should have annotations, none are present.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
There are no references to annotations in the chart source.

**Comment by juan131** [comment]
Hi @craigminihan 

Could you please specify the exact command you're using to set the annotations via `--set`? That said, I highly discourage to use `--set` to manage objects on a `helm install` command. Instead, I'd use:

```command
$ cat > custom-values.yaml << 'EOF'
podAnnotations:
  foo: bar
  baz: quiz
EOF
$ helm install -f custom-values.yaml bitnami/kibana
```

**Comment by craigminihan** [comment]
@juan131 thanks for the input. An ammended version of your example shows the problem:

```sh
$ cat > custom-values.yaml << 'EOF'
elasticsearch:
  hosts:
  - test
  port: 1234
podAnnotations:
  foo: bar
  baz: quiz
EOF
$ helm template -f custom-values.yaml --version 5.3.10 TEST bitnami/kibana
```

The deployment output does not contain `foo` or `baz`. My use-case was to exclude `fluent-bit` on the pod via:

```yaml
  annotations:
    fluentbit.io/exclude: "true"
```
I'd PR normally but I just don't have the time at the moment. I've switched to the `elastic/kibana` chart now so happy to close if not important.

**Comment by juan131** [comment]
Oh!! You're right, I just identify the issue!! 
I created a PR to address this, thanks for reporting it!
