### ISSUE TITLE
Chart.yaml for metrics-server should include a link to this repository

### ISSUE THREAD

**Issue by philomory** [bitnami/charts#3551]
**Which chart**:
I'm particularly interested in the metrics-server chart, but _every_ chart would probably benefit from this

**Is your feature request related to a problem? Please describe.**
It's hard to find this github repository from the chart's listing on Helm Hub.

**Describe the solution you'd like**
This `Chart.yaml` file for the metrics-server chart should list https://github.com/bitnami/charts/tree/masterbitnami/metrics-server as either the `home` url or as a `source` url.

**Comment by miguelaeh** [comment]
Hi @philomory ,
Sorry I am not sure to understand what are you requesting. The metrics-server's `Chart.yaml` has as home the metrics-server repo as you can see here: https://github.com/bitnami/charts/blob/c7f5c590d73122bba29d2bc59f1c8a59ff7372d8/bitnami/metrics-server/Chart.yaml#L10

**Comment by philomory** [comment]
Sorry, the URL I shared had a typo, but, it's a URL within _this_ repository, the repository where the chart _comes from_. It should have said https://github.com/bitnami/charts/tree/master/bitnami/metrics-server .

**Comment by miguelaeh** [comment]
I think you are looking for something like the above PR, could you take a look?

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!

**Comment by philomory** [comment]
@miguelaeh Yes, that is exactly the kind of thing I was looking for, thanks!
