### ISSUE TITLE
[bitnami/postgresql-ha] Cannot run repmgr CLI successfully

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/charts#3558]
**Which chart**:
bitnami/postgresql-ha 3.5.9

**Describe the bug**
When I'm trying to use repmgr CLI via exec + command or exec -it and running repmgr --help I got an error:

```
kubectl -n production-app-sentry exec pg-ha-postgresql-0 -- repmgr --help
could not get current user name: Success
command terminated with exit code 1
```

**Expected behavior**
repmgr CLI works normally

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
NONE

**Comment by miguelaeh** [comment]
Hi @Antiarchitect ,
The problem here seems to be that executing a command directly does not load the `nss_wrapper` configuratino. try with the following command that will load the `nss_wrapper` configuration:

```
kubectl exec -it <pod-name> /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr --help
```

**Comment by Antiarchitect** [comment]
That works as expected! Thank you @miguelaeh

**Comment by st-ram** [comment]
Works with docker as well
