### ISSUE TITLE
[bitnami/postgresql-ha] Regular or irregular liveness probe failure for pgpool pod

### ISSUE THREAD

**Issue by Jaesang** [bitnami/charts#3576]
**Which chart**:
Postgresql-HA 3.4.3

**Describe the bug**
When I deployed 1 pgpool pod and 1 or 2 postgresql pod, pgpool pod fails liveness probe every hour or hour and a half.
This is describes about pgpool pod.
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Warning  Unhealthy  25h   kubelet, suy-aw05  Liveness probe failed: pgpool 06:57:44.87 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  25h  kubelet, suy-aw05  Liveness probe failed: pgpool 06:57:59.96 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  25h  kubelet, suy-aw05  Liveness probe failed: pgpool 06:58:15.06 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  25h  kubelet, suy-aw05  Liveness probe failed: pgpool 06:58:30.16 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  25h  kubelet, suy-aw05  Liveness probe failed: pgpool 06:58:45.27 INFO  ==> Checking pgpool health...
psql: timeout expired
```
When I disabled liveness probe, and monitoring manual sql query to pgpool every seconds, at some point, it hangs without a response to the query.

This is a graph for number of restart for pgpool pod. It ran fine some hours, but endless liveness probe fail was occured every hour or hour and a half after suddenly restart once.
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/885169/91825461-491b2300-ec77-11ea-8360-3e05203e51ee.png">

Is there any experience about this? What can I do investigate for this issue? This issue may be due to my environment, but I don't know why  it doesn't always fail and the error comes after some time has passed.
 
**To Reproduce**
1. Delete Postgresql-HA helm chart
2. Re-deploy Postgresql-HA helm chart

**Expected behavior**
Success liveness probe.

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by andresbono** [comment]
Hi @Jaesang, thanks for opening this issue. Do the nodes have enough resources to handle the deployment? Do the node assigned to pgpool have some kind of cron tasks that may saturate the resource consumption periodically? Are you deploying with custom values or default ones?

Does the problem only occur with pgpool pods? Can you try to deploy more than one replica to see if all the pods are affected by this issue?

```
helm install postgresql-ha bitnami/postgresql-ha --set pgpool.replicaCount=2
```

You can check to which node the pods are assigned with:

```
kubectl get pods -o wide
```

That way you can verify if it depends on the k8s node that schedules the ndoe or it could be something else.

**Comment by Jaesang** [comment]
Thank @andresbono, I'll check upgrade replicaCount by your advise.
Before check, I can answer your some questions.
1. Do the nodes have enough resources to handle the deployment? : Yes, There isn't special load and node has enough capacity.
2.  Do the node assigned to pgpool have some kind of cron tasks that may saturate the resource consumption periodically?
: No, There isn't special cron tasks.
3. Are you deploying with custom values or default ones?: For md5 authentication, I only added init scripts for add user to pool_passwd
```
pgpool:
  initdbScripts:
    db_init_script.sh: |
            #!/bin/bash

            USERS=("test:test" "test2:test2")

            for user in "${USERS[@]}"; do
              user_info=(${user//:/ })
              pg_md5 -m --config-file="/opt/bitnami/pgpool/conf/pgpool.conf" -u "${user_info[0]}" "${user_info[1]}"
            done
```

**Comment by andresbono** [comment]
Thanks for the additional information, @Jaesang.

**Comment by kkorada** [comment]
same here.

pgpool pod restarting indefinitely with Liveness probe failed message.

**Comment by kkorada** [comment]
I tried creating 2 replicas for pgpool.

For pod commhub-db-pgpool-8db676b85-dkhpj
`
Events:
  Type     Reason     Age   From                                                      Message
  ----     ------     ----  ----                                                      -------
  Normal   Scheduled  50m   default-scheduler                                         Successfully assigned default/commhub-db-pgpool-8db676b85-dkhpj to ip-192-168-4-43.ap-southeast-1.compute.internal
  Normal   Pulling    50m   kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Pulling image "docker.io/bitnami/pgpool:4.1.3-debian-10-r7"
  Normal   Pulled     50m   kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Successfully pulled image "docker.io/bitnami/pgpool:4.1.3-debian-10-r7"
  Warning  Unhealthy  49m   kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:42:05.64 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  49m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:42:20.76 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  48m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:42:35.89 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  48m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:42:51.04 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  48m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:43:06.16 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Normal   Started    47m (x2 over 50m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Started container pgpool
  Warning  Unhealthy  47m                kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:44:25.64 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  46m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 14:44:40.76 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  46m (x3 over 46m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  (combined from similar events): Liveness probe failed: pgpool 14:45:25.12 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Normal   Created    45m (x3 over 50m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Created container pgpool
  Warning  Unhealthy  45m (x2 over 47m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Readiness probe failed: cannot exec in a stopped state: unknown
  Normal   Pulled     45m (x2 over 47m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Container image "docker.io/bitnami/pgpool:4.1.3-debian-10-r7" already present on machine
  Warning  Unhealthy  45m (x2 over 47m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Readiness probe failed:
  Warning  Unhealthy  20m                kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:11:25.64 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  19m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:11:40.76 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  19m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:11:55.88 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  19m  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:12:11.00 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Normal   Killing    19m (x3 over 48m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Container pgpool failed liveness probe, will be restarted
  Warning  Unhealthy  19m                kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:12:26.12 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
  Is the server running on host "localhost" (::1) and accepting
  TCP/IP connections on port 5432?
`

For pod commhub-db-pgpool-8db676b85-prpjt
`  
Type    Reason     Age   From                                                      Message
  ----    ------     ----  ----                                                      -------
  Normal  Scheduled  39m   default-scheduler                                         Successfully assigned default/commhub-db-pgpool-8db676b85-prpjt to ip-192-168-3-35.ap-southeast-1.compute.internal
  Normal  Pulled     39m   kubelet, ip-192-168-3-35.ap-southeast-1.compute.internal  Container image "docker.io/bitnami/pgpool:4.1.3-debian-10-r7" already present on machine
  Normal  Created    39m   kubelet, ip-192-168-3-35.ap-southeast-1.compute.internal  Created container pgpool
  Normal  Started    39m   kubelet, ip-192-168-3-35.ap-southeast-1.compute.internal  Started container pgpool`

**Comment by kkorada** [comment]
Any update on this ?

**Comment by andresbono** [comment]
Hi @kkorada, do the logs show any relevant message before the pods crash?

**Comment by Jaesang** [comment]
@kkorada status is exactly same with my case.

**Comment by kkorada** [comment]
same here, no logs before pods crash.

**Comment by andresbono** [comment]
Hi @Jaesang, @kkorada, we are going to keep a deployment running for some time, in case we are able to reproduce the issue.

**Comment by kkorada** [comment]
Hi, any update on what happened to your deployment ? Was is the same ?

**Comment by andresbono** [comment]
Hi, no issues so far:

```
$ kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-58c6f47565-h8ktg   1/1     Running   0          24h
postgresql-ha-pgpool-58c6f47565-t64n9   1/1     Running   0          24h
postgresql-ha-postgresql-0              1/1     Running   0          24h
postgresql-ha-postgresql-1              1/1     Running   0          24h
```

I deployed with `helm install postgresql-ha bitnami/postgresql-ha --set pgpool.replicaCount=2`.

**Comment by kkorada** [comment]
Yes it is not going into CrashLoopBackoff and no restarts for me with the same chart. But the thing is there were no connections to the pool. May be this is happening when there are connections. Could u try putting some load onto that pool.

**Comment by kkorada** [comment]
I just tried with below values with 4 microservices connecting to it. Each service opens a pool (hikari pool) of ~10 connections.
values:
```
  postgresql:
    password: 123123
    repmgrPassword: 123123
    initdbScripts:
      init_script.sql: |
        create database xyzDb;
  pgpool:
    replicaCount: 2
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
```

events:
```
Events:
  Type     Reason     Age                From                                                       Message
  ----     ------     ----               ----                                                       -------
  Normal   Scheduled  12m                default-scheduler                                          Successfully assigned default/commhub-dbha-pgpool-6dd746969-hvj6m to ip-192-168-3-194.ap-southeast-1.compute.internal
  Normal   Pulled     12m                kubelet, ip-192-168-3-194.ap-southeast-1.compute.internal  Container image "docker.io/bitnami/pgpool:4.1.3-debian-10-r7" already present on machine
  Normal   Created    12m                kubelet, ip-192-168-3-194.ap-southeast-1.compute.internal  Created container pgpool
  Normal   Started    12m                kubelet, ip-192-168-3-194.ap-southeast-1.compute.internal  Started container pgpool
  Warning  Unhealthy  12m (x5 over 12m)  kubelet, ip-192-168-3-194.ap-southeast-1.compute.internal  Readiness probe failed: psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off
```

```
Events:
  Type     Reason     Age                From                                                      Message
  ----     ------     ----               ----                                                      -------
  Normal   Scheduled  13m                default-scheduler                                         Successfully assigned default/commhub-dbha-pgpool-6dd746969-lvvwc to ip-192-168-4-43.ap-southeast-1.compute.internal
  Warning  Unhealthy  13m (x5 over 13m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Readiness probe failed: psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off
  Warning  Unhealthy  8m44s  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:45:07.58 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  8m29s  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:45:22.72 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  8m14s  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:45:37.82 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  7m59s  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:45:52.93 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Normal   Killing    7m43s  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Container pgpool failed liveness probe, will be restarted
  Warning  Unhealthy  7m43s  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Liveness probe failed: pgpool 15:46:08.03 INFO  ==> Checking pgpool health...
psql: timeout expired
could not connect to server: Cannot assign requested address
           Is the server running on host "localhost" (::1) and accepting
           TCP/IP connections on port 5432?
  Normal   Created    7m13s (x2 over 13m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Created container pgpool
  Normal   Pulled     7m13s (x2 over 13m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Container image "docker.io/bitnami/pgpool:4.1.3-debian-10-r7" already present on machine
  Normal   Started    7m13s (x2 over 13m)  kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Started container pgpool
  Warning  Unhealthy  7m13s                kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Readiness probe failed:
  Warning  Unhealthy  7m13s                kubelet, ip-192-168-4-43.ap-southeast-1.compute.internal  Readiness probe failed: cannot exec in a stopped state: unknown
```

**Comment by andresbono** [comment]
That makes sense, @kkorada. I launched the following deployment (10 replicas) to query PostgreSQL:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql-ha-client
  name: postgresql-ha-client
spec:
  replicas: 10
  selector:
    matchLabels:
      app: postgresql-ha-client
  template:
    metadata:
      labels:
        app: postgresql-ha-client
    spec:
      containers:
      - image: docker.io/bitnami/postgresql-repmgr:11.9.0-debian-10-r10
        name: postgresql-repmgr
        command: ['bash', '-c', 'while true; do export PGPASSWORD=KK49m7h99X; psql -h postgresql-ha-pgpool -p 5432 -U postgres -d postgres -c "show pool_processes;" >/dev/null; done']
```

**Comment by andresbono** [comment]
```
$ kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-client-55584f577f-5lbtd   1/1     Running   0          19h
postgresql-ha-client-55584f577f-7kjzb   1/1     Running   0          19h
postgresql-ha-client-55584f577f-c2zqk   1/1     Running   0          19h
postgresql-ha-client-55584f577f-cfbj8   1/1     Running   0          19h
postgresql-ha-client-55584f577f-ddf6r   1/1     Running   0          19h
postgresql-ha-client-55584f577f-f5tb7   1/1     Running   0          19h
postgresql-ha-client-55584f577f-h6hp6   1/1     Running   0          19h
postgresql-ha-client-55584f577f-qm6vx   1/1     Running   0          19h
postgresql-ha-client-55584f577f-wssjf   1/1     Running   0          19h
postgresql-ha-client-55584f577f-zs2vd   1/1     Running   0          19h
postgresql-ha-pgpool-58c6f47565-h8ktg   1/1     Running   0          5d23h
postgresql-ha-pgpool-58c6f47565-t64n9   1/1     Running   0          5d23h
postgresql-ha-postgresql-0              1/1     Running   0          5d23h
postgresql-ha-postgresql-1              1/1     Running   0          5d23h
```

No issues so far on our side. This is getting very difficult to debug.

**Comment by eremcan** [comment]
I'm having a similar issue. After I  get backup with psql, It throws psql: timeout expired. 
Is there any solution for it?

**Comment by juan131** [comment]
Hi @eremcan 

Does your backup modifies the password of the `postgres` user?
Please note that these probes (readiness/liveness probes) use the password you set when installing the chart to access the database. So, if this is no longer a valid password, the probes will fail.

**Comment by eremcan** [comment]
Hello @juan131 
No my backup script doesn't make any modification for postgres user.

**Comment by juan131** [comment]
Hi @eremcan 

Thanks! Could you try the following approach?

- Install (or upgrade) the chart disabling the probes.
- Restore your backup in the database.
- Check the CPU/RAM of the PostgreSQL pods (`kubectl top pod POD_NAME`) and share the results.
- Try to access manually to the database after restoring the database and share the results.

**Comment by vishrantgupta** [comment]
It could be happening because of this issue https://github.com/bitnami/charts/issues/6094#issuecomment-962693603
