### ISSUE TITLE
[bitnami/zookeeper] No possibility to override serviceAccount.name

### ISSUE THREAD

**Issue by rrymaszewski** [bitnami/charts#3581]
**Which chart**:
zookeeper

**Describe the bug**
there is no option to use existing serviceAccount.name. 

when you don't set serviceAccount.create = true then there is no value serviceAccountName defined in statefulset resource

when you set serviceAccount.create than serviceAccountName is defined but additionally new resource for ServiceAccount is created. 

**To Reproduce**

Set in values.yaml 

serviceAccount.name = abc
serviceAccount.create = false

**Expected behavior**
we should have possibility to override value

serviceAccount.name

without setting value 

serviceAccount.create = true

**Version of Helm and Kubernetes**:

**Comment by joancafom** [comment]
Hi @rrymaszewski 

Thanks for reporting the issue! I have created a PR with some changes #3587 that is intended to solve this.
