### ISSUE TITLE
[bitnami/joomla] template: joomla/templates/NOTES.txt:78: illegal number syntax

### ISSUE THREAD

**Issue by dnauck** [bitnami/charts#3583]
**Which chart**:
bitnami/joomla version 8.1.2

**Describe the bug**

i get the following error message while i try to deploy the bitnami/joomla version 8.1.2 chart on an azure AKS cluster 1.7.9 deployed by Rancher 2.4:

```
wait helm template failed. Error: parse error in \"joomla/templates/NOTES.txt\": template: joomla/templates/NOTES.txt:78: illegal number syntax: \"-\"\n: exit status 1
```

Using the following values:

```
image:
  registry: docker.io
  repository: bitnami/joomla
  pullPolicy: IfNotPresent
  debug: false

joomlaUsername: "myuser"
joomlaPassword: "mypassword"
joomlaEmail: "mail@domain.com"
allowEmptyPassword: "no"

updateStrategy:
  type: RollingUpdate

mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: "bitnami_joomla"
    user: "bn_joomla"
    password: "mypassword"
  rootUser:
    password: "mypassword"

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      storageClass: "my-class"
      accessModes:
        - ReadWriteOnce
      size: 1Gi

service:
  type: ClusterIP
  #port: 80
  #httpsPort: 443
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster

ingress:
  enabled: true
  certManager: true
  hostname: www.domain.com

  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 40m  

  hosts:
  - name: domain.com
    path: /

  tls:
  - hosts:
      - www.domain.com
      - domain.com
    secretName: www-domain-com-cert

persistence:
  enabled: true
  storageClass: "my-class"
  accessMode: ReadWriteMany
  size: 2Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 128Mi
    cpu: 100m

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 6
  successThreshold: 1
```

i don't see what value is wrong and cause the error. maybe someone can help.

Thanks!

**Comment by juan131** [comment]
Hi @dnauck 

I'm unable to reproduce the issue using the exact **values.yaml** you shared and the command below:

```console
$ helm template joomla bitnami/joomla -f values-joomla.yaml
```

What version of Helm are you using?

**Comment by dnauck** [comment]
I'm using the Rancher 2.4.5 UI to deploy a Helm3 version of the chart.

**Comment by dnauck** [comment]
Tested again with default values, same error message.

**Comment by juan131** [comment]
So.. You're using Helm2 and Tiller, that could explain it. I mean, there are some feature/functions that we can use in the templates included in Helm3 that are not available in Helm2. It's very likely your Tiller server doesn't know how to render our Joomla! chart.

Our catalog is built, tested and intended for Helm3 since Helm2 is deprecated, see:

- https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan

**Comment by dnauck** [comment]
Hi @juan131,

this was wrong from my side. The tiller message from the rancher logs was from another chart on Helm v2 base.
The bitnami repository was added as Helm v3 (and no tiller message at all in the logs during install of the bitnami joomla chart)

**Comment by juan131** [comment]
Great!! Glad to hear that @dnauck 
I proceed to close the issue as "solved", please do not hesitate to reopen it if you require further help

**Comment by dnauck** [comment]
@juan131 Sadly no ;)

I just wanted to say that helm v2 is not used by Rancher for this chart. The issue is still there.

**Comment by juan131** [comment]
Oh sorry! I misunderstood you...
Could you share the exact helm version used by Rancher? I'd like to reproduce the issue on my side to see what is the specific template that's incompatible with it.
