### ISSUE TITLE
[bitnami/postgresql-ha] pgpool waiting after noderestart

### ISSUE THREAD

**Issue by BenchmarkingBuffalo** [bitnami/charts#3591]
**Which chart**:
I am using the chart bitnami/postgresql-ha in version 3.5.6

**Describe the bug**
I have deployed a cluster with two postgres-pods and two pgpool-pods on a baremetal kubernetes cluster with two worker nodes. When I reboot one of the nodes, after a timespan between 5 and 30 seconds, connections to pgpool are possible again. This is a long amount of time in my opinion. 
I created a configmap for configuring pgpool as described below.

**To Reproduce**
1. Create a configmap containing 
```
health_check_max_retries='0'
health_check_period='1'
health_check_timeout='1'
```
2. Import the configmap
```
kubectl create configmap testconfig --from-file=pgpool.conf
```
3. Install the helm chart
```
helm install --name mypg --version 3.5.6 --set pgpool.configurationCM=testconfig --set postgresql.repmgrConnectTimeout=1 --set postgresql.repmgrReconnectAttempts=1 --set postgres.repmgrReconnectInterval=2 --set postgresql.password=password --set postgresql.repmgrPassword=password --set pgpool.replicaCount=2 --set persistence.enabled=false --set service.type=LoadBalancer --set service.loadBalancerIP=192.168.10.5 bitnami/postgresql-ha
```
4. Connect to the cluster using psql
```
psql -h 192.168.10.5 -U postgres -d postgres
```
5. Check schemas
```
\dn
```
6. Reboot one of the worker nodes (The one, where the active pgpool-pod is running on)
7. Try step 5 again.

**Expected behavior**
I dont know, wether this is a bug or wether I am missing a configuration option. 
I would expect the second pgpool to realize, the first one is down and take over control.
As far as I can see, as soon as the node reboots, the loadbalancer-IP is anounced from the other node.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
````

**Comment by juan131** [comment]
Hi @BenchmarkingBuffalo 

Are you PostgreSQL node also split into different worker nodes? Please note that you can play with the `postgresql.affinity` and `pgpool.affinity` parameters to ensure the pods are scheduled on different nodes to reduce the downtime:

- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

**Comment by rafariossaa** [comment]
Hi @BenchmarkingBuffalo,
  Maybe the initial configuration for pgpool could be lowered so you don't experiment a high delay, but if you lowered them too much, if there is a small network glitch it will be considered as a node failed when it is not.
 You can tune them with the procedure you have indicated, and find which values work best in you case.
