### ISSUE TITLE
Bitnami/grafana - I cannot host grafana on a path - url routing

### ISSUE THREAD

**Issue by Romiko** [bitnami/charts#3595]
Hi,

In K8, I want to host grafana on a path e.g. http://myhost.com/grafana. It works perfectly if I use stable/prometheus-operator with the built in grafana charts.

Please advise.

Using the latest chart

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: sre-slo-nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: "slo{{ requiredEnv "REGION" }}.{{ .Environment.Name }}.me.com"
      paths: ["/grafana/?.*"]

service:
  port: 80

**Comment by miguelaeh** [comment]
Hi @Romiko ,
Give a try to:
```
ingress:
  enabled: true
    - name: myhost.com
      paths: ["/grafana"]
```

Then to test it you will need to edit your `/etc/hosts` file and add a record for `myhost.com` pointing to the Ingress IP.
