### ISSUE TITLE
[bitnami/postgresql-ha] add pgBackRest support

### ISSUE THREAD

**Issue by sw34** [bitnami/charts#3600]
**Which chart**:
postgresql-ha

**Is your feature request related to a problem? Please describe.**
Looking for a way to take backups of postgres in the cluster.

**Describe the solution you'd like**
Looking for a way to backup the cluster using pgBackRest.  Because pgBackRest needs to know who the primary is the config files on both the postgres database server pods and the pgBackRest pod need to be updated when the primary is down and a secondary is promoted or a new secondary is brought online.

**Describe alternatives you've considered**
not sure what other options would work, ```pg_dump``` is not an option for me

**Comment by andresbono** [comment]
Hi @sw34, thanks for opening this issue. If changing the configuration file is needed, maybe pgBackRest is not suitable for this chart. We haven't explored pgBackRest solution though. Just curious, why pg_dump is not valid for you?

**Comment by sw34** [comment]
pg_dump is not capable of differential or incremental backups, however I I have found that I can use the WAL files for this so I will try to find a solution like using a combination of WAL file archive and pg_dump that will serve my needs.

**Comment by andresbono** [comment]
Thanks for letting us know, @sw34. It would be great if you can share the conclusions of your findings!

**Comment by thangamani-arun** [comment]
@sw34 Did you find a way to enabled PGBackRest with your postgresql-ha deployment ?
@andresbono don't we like to have more options for end users?

**Comment by exfly** [comment]
Any suggestions?
