### ISSUE TITLE
[bitnami/wordpress] Mounting the wordpress volume inside an initContainer

### ISSUE THREAD

**Issue by grizzo-fsm** [bitnami/charts#3604]
**Which chart**:
Wordpress 9.5.4

**Describe the bug**
If I define an initContainer inside a separate values.yaml, to push some files into the wordpress persistent storage, the mariadb container won't start with the following log output.

```
mariadb 06:59:33.88 INFO  ==> ** Starting MariaDB setup **
mariadb 06:59:33.91 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 06:59:33.92 INFO  ==> Initializing mariadb database
mariadb 06:59:33.94 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 06:59:33.94 INFO  ==> Using persisted data
mariadb 06:59:33.97 INFO  ==> Running mysql_upgrade
mariadb 06:59:33.99 INFO  ==> Starting mariadb in background
mariadb 06:59:36.15 INFO  ==> Stopping mariadb
```

**To Reproduce**
1. Setup a values.yaml with following content:
```yaml
initContainers:
  - name: init-container
    image: gmrizzo/init-container
    imagePullPolicy: Always
    command: ['sh', '-c', 'mount']
    volumeMounts:
      - mountPath: /bitnami/wordpress
        name: wordpress-data
        subPath: wordpress
```
2. Run `helm install -f stoma-wp/values.yaml sample-deployment-name bitnami/wordpress`

**Expected behavior**
The mariadb pod should start normally.

**Version of Helm and Kubernetes**: v3.3.1

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I want to provision the storage with a custom plugin or theme. As stated in the values-production.yaml it could be accomplished through this configuration: 
```
## Add init containers to the pod.
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## Example:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'copy themes and plugins from git and push to /bitnami/wordpress/wp-conntent. Should work with extraVolumeMounts and extraVolumes']
##
```
Is there a way of doing this? Another possible solution would be to create a new chart that has the wordpress chart as a requirement.

**Comment by javsalgar** [comment]
Hi,

It is not clear to me how adding an init container in WordPress would trigger an error in the MariaDB container. Could you check if if not setting the initContainers does not cause the error?

**Comment by grizzo-fsm** [comment]
Hi, 

I think you're right. The initContainer has nothing todo with this behavior. I found that if I don't delete the PVC from mariadb after uninstalling the wordpress chart, a new deployment of the mariadb pod will fail with the output of the initial post. 

Is there a "correct" way of uninstalling and reinstalling the wordpress chart without deleting the mariadb pvc? Setting the wordpressSkipInstall value to false also didn't help.

Currently I'm struggling a lot with this chart because it seems overcomplicated pushing custom plugins, themes and especially database dumps into the deployment. 

Is there a way of leveraging the available wp-cli to install plugins and themes that were pushed inside the volume?

Thanks in advance.

**Comment by javsalgar** [comment]
Hi,

I think the easiest choice would be to use the init scripts support feature that the Bitnami WordPress container has. 

https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh

The idea would be mounting a set of scripts in the `/docker-entrypoint-init.d` folder. I advise you to first try it using docker-compose. When you achieve what you are looking for, then you can use the `extraVolumes` and `extraVolumeMounts` values to mount a configmap with the scripts. Would that work for you?
