### ISSUE TITLE
[bitnami/cassandra]: wrong reference to configMap

### ISSUE THREAD

**Issue by nbenaglia** [bitnami/charts#3605]
In Values there's a section for:

```
## Secret with cql script (with sensitive data). Useful for creating a keyspace
## and pre-populating data
##
## initDBSecret:
```

But secret is not mounted, like show here:
https://github.com/bitnami/charts/blob/374e903fce2e28fcf6a89ab61e3867e415a3d1e7/bitnami/cassandra/templates/statefulset.yaml#L259

Configmap is wrong in L259.

**Comment by juan131** [comment]
You're totally right! I just approved/merged you PR! Thanks so much for the fix.
