### ISSUE TITLE
[bitnami/mariadb] VolumeClaim selector for mariadb

### ISSUE THREAD

**Issue by poksiala** [bitnami/charts#3607]
**Which chart**:
mariadb

**Is your feature request related to a problem? Please describe.**
It will be very nice to have a VolumeClaim selector for mariadb chart.

**Describe the solution you'd like**
For mariadb-galera this has been already implemented:
- Issue: https://github.com/bitnami/charts/issues/3072
- PR: https://github.com/bitnami/charts/pull/3237

**Additional context**
I can create a PR if you are willing to consider this feature.

**Comment by andresbono** [comment]
Hi @poksiala, yes, of course! PRs are more than welcome. I don't see any cons on adding persistence selectors to this chart.
