### ISSUE TITLE
Example of nginx chart with php ?

### ISSUE THREAD

**Issue by GreyXor** [bitnami/charts#3608]
Hello everyone, I'd like to make a nginx php mariadb and redis stack for a PHP application. To do this I would like to use these 3 chart helms

https://bitnami.com/stack/nginx/helm
https://bitnami.com/stack/mariadb/helm
https://bitnami.com/stack/redis/helm

And for PHP I can't find a helm chart so maybe i will use the official docker php php image.

I would like to know if it is possible to group these 3 charts in one (maybe via a requirements.yaml?) to share my php app files in a RWX nfs volume and thus make my application easily scalable and production ready? So how can I add a PHP in all this? (scalable too).
This way is good ? Do you know some helm chart production/scalable ready for this ? Or how to make a PHP service with the bitnami/nginx chart? (in a scalable way)
Thanks !

**Comment by miguelaeh** [comment]
Hi @GreyXor ,
If you add them to the `requirements.yaml` file, they will be installed all at once, and also you can pass the parameters using the specific section in your custom `values.yaml`.

I recommend you to take a look to our Nginx stack at https://bitnami.com/stack/nginx, it does not have Redis but maybe you can deploy itas an external service.

> And for PHP I can't find a helm chart so maybe i will use the official docker php php image.
Regarding this, we also have a PHP docker image at https://github.com/bitnami/bitnami-docker-php-fpm
