### ISSUE TITLE
[bitnami/postgresql] postgresqlExtendedConf does not support string type value

### ISSUE THREAD

**Issue by skyrain** [bitnami/charts#3610]
**Which chart**:
bitnami/postgresql

Version:9.4.0

**Is your feature request related to a problem? Please describe.**

postgresqlExtendedConf does not support string type value.

If I set something like,

```
postgresqlExtendedConf:
    listenAddresses: '*'
```

In the final generated postgresql.conf file, the entry will be:

```
listenAddresses = *
```

instead of
```
listenAddresses = '*'
```
The quote is required for some of the properties in postgresql.conf, we need to have a way to deal with this.

**Describe the solution you'd like**
Add the ability to setup string type value config variables.

**Describe alternatives you've considered**

**Additional context**

**Comment by joancafom** [comment]
Hi @skyrain 

Thanks for your issue! By double-quoting the values I think this should work. E.g:

```yaml
postgresqlExtendedConf:
  listenAddresses: "'*'"
```

```console
$  helm template alpha bitnami/postgresql -s templates/extended-config-configmap.yaml
---
# Source: postgresql/templates/extended-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpha-postgresql-extended-configuration
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.4.0
    app.kubernetes.io/instance: alpha
    app.kubernetes.io/managed-by: Helm
data:

  override.conf: |
    listen_addresses='*'
```

Hope it helps, thanks!

**Comment by skyrain** [comment]
> Hi @skyrain
> 
> Thanks for your issue! By double-quoting the values I think this should work. E.g:
> 
> ```yaml
> postgresqlExtendedConf:
>   listenAddresses: "'*'"
> ```
> 
> ```
> $  helm template alpha bitnami/postgresql -s templates/extended-config-configmap.yaml
> ---
> # Source: postgresql/templates/extended-config-configmap.yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: alpha-postgresql-extended-configuration
>   labels:
>     app.kubernetes.io/name: postgresql
>     helm.sh/chart: postgresql-9.4.0
>     app.kubernetes.io/instance: alpha
>     app.kubernetes.io/managed-by: Helm
> data:
> 
>   override.conf: |
>     listen_addresses='*'
> ```
> 
> Hope it helps, thanks!

great, it works.
