### ISSUE TITLE
bitnami/airflow  ingress  annotations is error

### ISSUE THREAD

**Issue by superbeer** [bitnami/charts#3611]
**Which chart**:

> apiVersion: v1
> name: airflow
> version: 6.4.0
> appVersion: 1.10.12

**Describe the bug**

uncomment  ingress  annotations is  error
```
annotations:
    kubernetes.io/ingress.class: nginx
```
> error

`coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>`

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting. I believe this warning (note that it shouldn't affect the deployment) is because we have this as a default value

```
annotations:
```

I think it should be fixed by setting as a default:

```
annotations: {}
```

**Comment by superbeer** [comment]
i think error from helm templates.

**Comment by javsalgar** [comment]
Does the deployment work? Do you see the final ingress rule with the annotations?
