### ISSUE TITLE
[bitnami/rabbitmq] Error when specifying service.extraPorts

### ISSUE THREAD

**Issue by Gazza7205** [bitnami/charts#3621]
**Which chart**:
RabbitMQ - latest version (and previous versions)

**Describe the bug**
Install warning when defining service.extraPorts. This doesn't result in any failures, additional ports are published as expected.
```
coalesce.go:196: warning: cannot overwrite table with non table for extraPorts (map[])
coalesce.go:196: warning: cannot overwrite table with non table for extraPorts (map[])
coalesce.go:196: warning: cannot overwrite table with non table for extraPorts (map[])
```

**To Reproduce**
1. Create a ```my-values.yaml``` file with the following

```
service:
  extraPorts:
  - name: mqtt
    port: 1883
    targetPort: mqtt
extraContainerPorts:
- name: mqtt
  containerPort: 1883
```

2. Install the Chart

```
$ helm install my-release bitnami/rabbitmq -f my-values.yaml
```

**Expected behavior**

The following warning appears

```
coalesce.go:196: warning: cannot overwrite table with non table for extraPorts (map[])
```

The Chart then installs successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Running this on a Macbook, I've seen the same issue on Ubuntu and Windows. It may be Helm itself?

**Comment by javsalgar** [comment]
Hi,

The issue is because of the default value for extraPorts

```
  extraPorts: {}
```

It should be the following to avoid this warning.

```
  extraPorts: []
```

We will fix it in later versions. If you want to speed up the process feel free to create a PR. Thank you so much for reporting!

**Comment by Gazza7205** [comment]
> Hi,
> 
> The issue is because of the default value for extraPorts
> 
> ```
>   extraPorts: {}
> ```
> 
> It should be the following to avoid this warning.
> 
> ```
>   extraPorts: []
> ```
> 
> We will fix it in later versions. If you want to speed up the process feel free to create a PR. Thank you so much for reporting!

Thanks for the quick response @javsalgar - I've created a PR with the update.
