### ISSUE TITLE
Cluster fails to form after deleting consul-0 pod from statefulset

### ISSUE THREAD

**Issue by BobBeeke** [bitnami/charts#3626]
**Which chart**: 
bitnami/consul:latest

**Describe the bug**
Default install: Consul statefulset with 3 replica's.
When for some reason one deletes the consul-0 pod (and let consul-1 and consul-2 live) consul will not form a cluster after consul-0 spins up again. The consul-0 pod forms its own cluster (split brain) and needs to be manually joined to the other nodes. 

This works only for pod consul-0. The other pods can be deleted with no issue.

**To Reproduce**
1. Install default consul helm chart (latest)
2. Verify cluster has formed with 3 memnbers with something like: 

```
kubectl exec -it consul-0 -- consul members
```

3. Delete pod consul-0: 

```
kubectl delete pod consul-0
```

4. Verify that consul-0 doesn't join the cluster automatically:

```
kubectl exec -it consul-0 -- consul members
kubectl exec -it consul-1 -- consul members
```

5. Repeat above steps and delete pod consul-1 and verify that the cluster forms correctly.

**Expected behavior**
Cluster forms without manual action after deleting pod consul-0

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Our problem is solved by using the short service name for CONSUL_RETRY_JOIN in the consul statefulset.yaml:

Change:

```
            - name: CONSUL_RETRY_JOIN
              value: {{ printf "%s-0.%s.%s.svc.%s" $consulFullName $consulHeadlessSvcName .Release.Namespace $clusterDomain | quote }}
```

To:

```
            - name: CONSUL_RETRY_JOIN
              value: value: {{ printf "%s" $consulFullName | quote }}
```

I'm not entirely sure if this is solid for every possible scenario but at least it works for normal cases.

**Comment by dani8art** [comment]
Hi @BobBeeke I've just created a PR that fixes this issue, please, let's move the conversation there. 

Thank you so much for reporting it!
