### ISSUE TITLE
[bitnami/etcd] add loadBalancerSourceRanges (feature request)

### ISSUE THREAD

**Issue by rico-bincentive** [bitnami/charts#3629]
**Which chart**:
etcd

**Is your feature request related to a problem? Please describe.**
Must of charts already support `loadBalancerSourceRanges`.
In my scenario, etcd is our configuration management service. It does not allow all of the traffic to access.

**Describe the solution you'd like**
Add `loadBalancerSourceRanges` setting for etcd chart.

**Describe alternatives you've considered**
Would consider trying `service.beta.kubernetes.io/aws-load-balancer-extra-security-groups` annotation on ELB.

**Additional context**
I can help this feature. 👋

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input! We will work on that but we cannot guarantee an ETA. However, if you want to speed up the process feel free to create a PR and we will review it.
