### ISSUE TITLE
"Remote host terminated the handshake" even when ssl is not enabled

### ISSUE THREAD

**Issue by manoadamro** [bitnami/charts#3634]
**Which chart**:
spark 3.0.0

**Describe the bug**
according to the docs, `security.ssl.enabled` is false by default, but even when explicitly set to false, I am getting:

```
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
```

**To Reproduce**
helm install to kubernetes cluster
submit a task

**Expected behavior**
not to get ssl errors when ssl is explicitly disabled

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @manoadamro ,
Could you share the exact values you are setting to be able to reproduce the issue?

**Comment by manoadamro** [comment]
I''m not using values, Im using the defaults on the helm chart.
I have also tried running `helm install` with `--set "security.ssl.enabled=false"`
