### ISSUE TITLE
[kafka] kafka chart is not working with default vaules-production.yaml in aks

### ISSUE THREAD

**Issue by gowrisankar22** [bitnami/charts#3636]
**Which chart**:

helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
helm install test azure-marketplace/kafka -f values-production.yaml

**Describe the bug**
Installing the Kafka chart is not working in AKS out of the box. 

```
Unable to mount volumes for pod "kafka-aks-bitnami-zookeeper-0_default(a49ba80b-1847-4fbb-bd40-5db790a157e3)": timeout expired waiting for volumes to attach or mount for pod "default"/"kafka-aks-bitnami-zookeeper-0". list of unmounted volumes=[data]. list of unattached volumes=[data default-token-hshhk]
```

**To Reproduce**
1. Go to AKS cluster
2. helm install test azure-marketplace/kafka -f values-production.yaml

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`: 3

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

```
- Output of `kubectl version`:

```
1.15
```

Can you please let me know, should we change any values specifically for aks ??
btw, I am using  default storageclass.

**Comment by joancafom** [comment]
Hi @gowrisankar22 

I have tried to replicate your issue but did not face any problems in AKS:

```console
$ helm install test azure-marketplace/kafka -f values-production.yaml
NAME: test
LAST DEPLOYED: Wed Sep  9 17:26:35 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
...

$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
test-kafka-0                           2/2     Running   0          2m1s
test-kafka-1                           2/2     Running   0          2m1s
test-kafka-2                           2/2     Running   0          2m1s
test-kafka-exporter-7558cdd845-v4d9m   1/1     Running   4          2m1s
test-zookeeper-0                       1/1     Running   0          2m1s
```
I am also using `default` as my storageclass. Are you using a custom `values-production.yaml` file? Could you please try again just in case it was due to a transitory error?

Thanks!

**Comment by gowrisankar22** [comment]
@joancafom subchart zookeeper basically works fine only with vaules.yaml file not with values-production.yaml.  If you do 
```
helm install test azure-marketplace/kafka -f values-production.yaml
```
this will take the values.yml for the subchart not the values-production.yaml. I moved the values-production.yaml and values.yml and tried it is failing.

**Comment by joancafom** [comment]
Hi @gowrisankar22 

I still can't replicate your issue. I have tried downloading the chart tarball and deploying it using the `values-production.yaml` but everything seems to be working fine:

```console
$ helm pull azure-marketplace/kafka
$ tar -xf kafka-11.8.3.tgz && cd kafka
$ helm install test azure-marketplace/kafka -f values-production.yaml
NAME: test
LAST DEPLOYED: Thu Sep 10 11:40:14 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
...

$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
test-kafka-0                           2/2     Running   0          118s
test-kafka-1                           2/2     Running   0          118s
test-kafka-2                           2/2     Running   0          118s
test-kafka-exporter-8474cc579f-qvc89   1/1     Running   4          118s
test-zookeeper-0                       1/1     Running   0          118s
```

Could you please provide me with your steps so as to try to reproduce the problem? Thanks!

**Comment by gowrisankar22** [comment]
sure. @joancafom 

Please find the steps to reproduce:

```
1. helm pull azure-marketplace/kafka
2. cd charts/zookeeper
3. mv values-production.yaml to values.yaml
4. helm template ../kafka/ -f values-production.yaml --name-template kafka-bitnami --namespace default > manifest.yml
5. kubectl apply -f manifest.yml
```

**Comment by dani8art** [comment]
Hi @gowrisankar22, 

I think you don't need to pull either override the `values.yaml` you can override it just using `kafka/values-production.yaml`

**Kafka values-production.yaml**
```yaml
...
zookeeper:
  <zookeeper_values_here>

...
```

As we are not able to reproduce the issue, could you add `image.debug=true` to every image and share the logs of your failing container with us so that we can try to help you, please?
