### ISSUE TITLE
[kube-prometheus] unexpected publicly exposed services on hostIP

### ISSUE THREAD

**Issue by mgcrea** [bitnami/charts#3638]
**Which chart**:

kube-prometheus@1.1.0

**Describe the bug**

ClusterIP services that are supposed to be internal somehow end up being exposed publicly

**To Reproduce**

1. Install chart without any specific options
2. Access http://xx.yy.150.105:9100/metrics (where xx.yy.150.105 is the public k8s host IP) that should be internal

**Expected behavior**

ClusterIP services are supposed to accessible only from the cluster, and so far all services used to work that way. But trying [kube-prometheus](https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus), I end up with a few ClusterIP services that somehow highjack the host IP and are publicly exposed. Did not think it was possible without any Ingress/NodePort/etc.

Here is the actual service:

```
kind: Service
apiVersion: v1
metadata:
  name: kube-prometheus-node-exporter
  namespace: kube-prometheus
  selfLink: /api/v1/namespaces/kube-prometheus/services/kube-prometheus-node-exporter
  uid: 0c4cd5a1-4849-4635-a656-238a5c3b4b78
  resourceVersion: '20388'
  creationTimestamp: '2020-09-08T18:08:17Z'
  labels:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 1.0.1
    helm.sh/chart: node-exporter-1.1.0
    jobLabel: node-exporter
  annotations:
    meta.helm.sh/release-name: kube-prometheus
    meta.helm.sh/release-namespace: kube-prometheus
    prometheus.io/scrape: 'true'
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2020-09-08T18:08:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:meta.helm.sh/release-name': {}
            'f:meta.helm.sh/release-namespace': {}
            'f:prometheus.io/scrape': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/version': {}
            'f:helm.sh/chart': {}
            'f:jobLabel': {}
        'f:spec':
          'f:ports':
            .: {}
            'k:{"port":9100,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/name: node-exporter
  clusterIP: 10.107.104.65
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
```

Nothing stands out as to why this one would end up public (eg. can access using host IP like: http://xx.yy.150.105:9100/metrics).

Any idea what I could be missing?

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @mgcrea 

That's the service created for the node exporter (which is a subchart as you can check in the [equirements.yaml](https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/requirements.yaml#L7)). As you can see in the link below, the service definition is a "normal" one, I mean it should be as any other ClusterIP service running in your cluster.

- https://github.com/bitnami/charts/blob/master/bitnami/node-exporter/templates/service.yaml

That said, node exporter uses a daemonset, see [daemonset.yaml](https://github.com/bitnami/charts/blob/master/bitnami/node-exporter/templates/daemonset.yaml). And, by default, it uses the host networks, see:

- https://github.com/bitnami/charts/blob/master/bitnami/node-exporter/templates/daemonset.yaml#L76

If you take a look to this [chart's parameters](https://github.com/bitnami/charts/tree/master/bitnami/node-exporter#parameters), there's a `hostNetwork` parameter that you can set to "false" to avoid it. Please note that you will edit this parameter in the section below in the [kube-prometheus values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/values.yaml):

```yaml
## Exporters
exporters:
  node-exporter:
    ## Enable node-exporter
    enabled: true
```

**Comment by mgcrea** [comment]
@juan131 Thanks for the thorough explanation! Learned something new today. Any reason this defaults to `true`?

**Comment by juan131** [comment]
You're welcome @mgcrea 

Node Exporter is designed to monitor the host's system (each node in the cluster in this case). I'm not an expert on this particular container, but I guess that it requires to access the host network to retrieve some metrics. Therefore, it's very likely some metrics won't be exposed when it's not using the host network. 

By the way, installing Node Exporter as part of the kube-prometheus release is totally optional. I mean, you can set the parameter `exporters.node-exporter.enabled` to `false` to do so.

**Comment by albanm** [comment]
Does anybody know if it is possible to access the host network for monitoring but only expose the 9100 port internally ?
