### ISSUE TITLE
changing Bitnami GKE kong default parameter values

### ISSUE THREAD

**Issue by kevinchu85** [bitnami/charts#3639]
Hello,

trying to figure out if there is a way to change certain parameters on the GKE version on bitnami kong, specifically keep alive time. We have a few routes configured in Kong and when they are called we get a response timed out. From looking around it seems like it has something to do with the upstream directives maybe?

I can see on the Admin API 

nginx_http_upstream_directives  keepalive_timeout is set to 60seconds and the keepalive_requests are set to 100 by default.

I was wondering if these can be changed? I was able to ssh in to the GKE pod running Kong and could see there is a config file 
**/opt/bitnami/kong/server/nginx-kong.conf**. That file has the configs for timeouts for Kong but could those manually be changed or it needs to go through a rolling upgrade through HELM to have those changed?

The Specific error we get is
`"message":"The upstream server is timing out"`

Have also attached a screenshot of the error we can see on our browser.
![Screen Shot 2020-09-09 at 7 04 36 pm](https://user-images.githubusercontent.com/67666903/92578859-cf66e300-f2cf-11ea-91f9-b3a84994d49a.png)

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. I don't think those parameters are configurable in the chart, you shouldn't set any special configuration in the files.

Kong is usually placed in front of one or several APIs (named _Services_ in Kong). When you configure a _Service_, you can also set the timeout for the connection with the Upstream API. See https://docs.konghq.com/2.1.x/proxy/#3-proxying--upstream-timeouts or https://docs.konghq.com/getting-started-guide/2.1.x/expose-services/#add-a-service

**Comment by kevinchu85** [comment]
@carrodher Thanks for confirming that. I did see that option while creating the service and route but at that time I thought it would be over written by the default values in `ngnix-kong.conf` file. Thanks for clearing that doubt for me.
