### ISSUE TITLE
MongoDB Sharded - Metrics Export on arbiters

### ISSUE THREAD

**Issue by hightoxicity** [bitnami/charts#3641]
**Which chart**:

mongodb-sharded

**Describe the bug**
The metric exporter can not do ops near local mongodb

```
time="2020-09-09T04:30:55Z" level=error msg="Failed to get replSetGetConfig: (Unauthorized) not authorized on admin to execute command { replSetGetConfig: 1, lsid: { id: UUID(\"12622f44-019f-4fb5-9e2c-946ef3f9b4f4\") }, $db: \"admin\", $readPreference: { mode: \"primaryPreferred\" } }." source="replset_conf.go:115"
time="2020-09-09T04:30:55Z" level=error msg="Failed to get oplog collection status: (Unauthorized) not authorized on local to execute command { collStats: \"oplog.rs\", lsid: { id: UUID(\"12622f44-019f-4fb5-9e2c-946ef3f9b4f4\") }, $db: \"local\", $readPreference: { mode: \"primaryPreferred\" } }" source="oplog_status.go:144"
time="2020-09-09T04:30:55Z" level=error msg="Failed to get oplog timestamps status: (Unauthorized) not authorized on local to execute command { find: \"oplog.rs\", comment: \"/home/nurlan/go/src/github.com/percona/mongodb_exporter/collector/mongod/oplog_status.go:85\", filter: {}, limit: 1, singleBatch: true, sort: { $natural: -1 }, lsid: { id: UUID(\"12622f44-019f-4fb5-9e2c-946ef3f9b4f4\") }, $db: \"local\", $readPreference: { mode: \"nearest\" } }" source="oplog_status.go:149"
```
An arbiter does have neither sync of admin db nor sync of data
But in the chart, the root password is used to try to connect to the local arbiter on the metric container and as expected it fails

https://github.com/bitnami/charts/blob/master/bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml#L227

An arbiter run with local exception :
https://docs.mongodb.com/manual/core/security-users/#localhost-exception

**To Reproduce**
1. Create a mongodb-sharded cluster with 2 shards, 2 replicaset + 1 arbiter per shard
2. kubectl logs -f -n mongodb pio-mongodb-sharded-shard0-arbiter-0 -c metrics
3. You should see errors

**Expected behavior**
In current state, the mongo_exporter should not run on arbiter nodes but maybe I missed something trying to understand how mongo works

Thanks

**Comment by miguelaeh** [comment]
Hi @hightoxicity ,
Could you share with us the command you are using to install the Chart to be able to reproduce the issue?
