### ISSUE TITLE
[bitnami/postgresql-ha]Information request on postgresql-ha for production deployment.

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#3644]
**Which chart**:
postgresql-ha/3.5

**Describe the bug**

we are evaluating bitnami/postgresql-ha for our production deployment and are in final stage of validating the bitnami solution.

I was asked to clarify few things .Please can you help responding them.

1. This particular solution is using pgpool and repmgr, however, the pgpool-II documentation states explicitly that this is not supported. https://www.pgpool.net/mediawiki/index.php/FAQ#Can_I_use_repmgr_with_Pgpool-II.3F . From the link please check the question "Can I use repmgr with Pgpool-II?"

2. We are already using a JDBC Connection Pool manager (Hikari) in our application layer. Pgpool-II also manages a Connection Pool. Is it advisable to connect 1 connection pool to another one ? Please can you advice how to handle this ?

3.Was there any  performance tests been done to pgpool ,we are planning to do performance with our application but just wanted to check  from your experience if you had noticed any performance issues ?

Thanks in advance for clarifying the above questions, This would help us for our production deployment.

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by parvaths1118** [comment]
Hi @rafariossaa , kindly can you check and help answering the questions?

**Comment by rafariossaa** [comment]
Hi,

> 1. This particular solution is using pgpool and repmgr, however, the pgpool-II documentation states explicitly that this is not supported. https://www.pgpool.net/mediawiki/index.php/FAQ#Can_I_use_repmgr_with_Pgpool-II.3F . From the link please check the question "Can I use repmgr with Pgpool-II?"

In chart, pgpool is used to handle the pooling and connections but not to handle the promotion that it is done by repmgr. We are not using postgres as part of our IT, hence we haven't hit the issues commented there. Please let us know if you find any related issue so we can fix it and improve our chats/containers.

> 2. We are already using a JDBC Connection Pool manager (Hikari) in our application layer. Pgpool-II also manages a Connection Pool. Is it advisable to connect 1 connection pool to another one ? Please can you advice how to handle this ?

I can not see any problems on this. The application handle its connections to pgpool and pgpool handle its connections to postgres nodes. Pooling is a mechanism to no need to open a new connection each time it is needed, to speed up connections. In this case you will have a couple of layers.

> 3.Was there any performance tests been done to pgpool ,we are planning to do performance with our application but just wanted to check from your experience if you had noticed any performance issues ?

We have not done performance tests. Performance tests are tricky to do, and to have usable results them will require to have a very controlled environment, so you have the same server with the same load, same disks with same I/O, etc. In a cloud environment, this is very variable and it is very difficult to have consistent results when repeating the same tests.
Also, in general with performance and benchmarks, you should peek a test that is similar to how you application behave. You have to consider percentage of reads, inserts, and updates, if they are on the same tables others etc. 
As you can see, checking performance on databases is quite tricky.

I'd suggest you to ask question 2 and 3 on pgpools forums, I am sure they can provide a better answer.

**Comment by parvaths1118** [comment]
Thank you @rafariossaa for the information.

I would check with postgresql support on points 2 and 3.

Please can you clarify when we upgrade helm chart by changing postgresql docker image version gor example version 10 to 12 ,what happens on data migration ?? Should I dump and restore into latest version of postgresql ??

I have few SQL scripts which I want to execute once my helm chart is ready,I have tried with initdb scripts configuring  SQL queries in values.yaml but I have few SQL files to be executed,I Saw an option related to configmap but I did not find any examples on configuration part.please can you share with some example on how to configure SQL scripts to be executed for creating our application DB once helm chart is deployed.

**Comment by rafariossaa** [comment]
Hi,

> I would check with postgresql support on points 2 and 3.

I'd would suggest to ask the pgpools question in pgpool's forums instead in postgresql's ones

> Please can you clarify when we upgrade helm chart by changing postgresql docker image version gor example version 10 to 12 ,what happens on data migration ?? Should I dump and restore into latest version of postgresql ??

You can't not simply change the docker image, postgresql 12 will complain if you start it with data files form version 10.
The chart doesn't upgrade the data, so you will need to dump and restore.

> I have few SQL scripts which I want to execute once my helm chart is ready,I have tried with initdb scripts configuring SQL queries in values.yaml but I have few SQL files to be executed,I Saw an option related to configmap but I did not find any examples on configuration part.please can you share with some example on how to configure SQL scripts to be executed for creating our application DB once helm chart is deployed.

I think this is the easiest way. 
If you clone the chart report, you will find this directory `postgresql-ha/files/docker-entrypoint-initdb.d `, where you can copy your custom `.sh`, `.sql` or `.sql.gz` file so they are executed during the first boot of the image.
So, if you install it with `helm install mypostgresql -f values.yaml .` it will deploy the chart and run the scripts you have put there.
