### ISSUE TITLE
[bitnami/redis-cluster] Redis Cluster Pods stuck in status Waiting: CrashLoopBack

### ISSUE THREAD

**Issue by swdee** [bitnami/charts#3653]
**Which chart**:
bitnami/redis-cluster v3.2.4

**Describe the bug**
Pods enter CrashLoopBack state and Redis Cluster never starts up.

Viewing a Pods log gives cause of error;

```
redis-cluster 03:02:01.25 
redis-cluster 03:02:01.25 Welcome to the Bitnami redis-cluster container
redis-cluster 03:02:01.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 03:02:01.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 03:02:01.26 
redis-cluster 03:02:01.26 INFO  ==> ** Starting Redis setup **
redis-cluster 03:02:01.27 INFO  ==> Initializing Redis
redis-cluster 03:02:01.29 INFO  ==> Setting Redis config file
Changing old IP 10.244.0.113 by the new one 10.244.0.238
sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory
```

**To Reproduce**

Using digitalocean.com kubernetes environment deploy using helm chart
```
helm install bitnami/redis-cluster --name redis --namespace redis
```

**Expected behavior**
Cluster to successfully start up without error.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

A similar Issue #2937 was reported but went unresolved as the issue could not be reproduced.  As discussed in that issue we 
 can successfully start up the cluster using;

```
helm install bitnami/redis-cluster --name redis --namespace redis --set persistence.path=/data
```

It was suggested that the issue might be cloud-provider specific, we have opened this ticket as we are experiencing this issue on DigitalOcean k8s environment so you maybe able to reproduce the problem with them.

**Comment by andresbono** [comment]
Hi @swedee, thanks for opening this issue. Have you tried the `volumePermissions` family of parameters? In case it is related.

**Comment by swdee** [comment]
@andresbono 

Thanks for your thoughts, I overlooked the `volumePermissions` section of Issue #2937 

I have managed to resolve the issue, it comes down to the default block storage `do-block-storage` at Digital Ocean setting the StorageClass parameter `volumeBindingMode: Immediate`, which according to the [k8s documentation](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode) is the default setting.

I created a new StorageClass consisting of the following;

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

Then deployed redis-cluster with helm using;

```
helm install bitnami/redis-cluster --name redis --namespace redis --set persistence.storageClass=redis-storage
```

I further note the that setting `persistence.path=/data` is NOT needed when the StorageClass `volumeBindingMode` is set to `WaitForFirstConsumer`.

As a storage classes default is `volumeBindingMode: Immediate` is there a way the Helm chart can check for this on deployment to avoid running into this issue?

**Comment by SweDee** [comment]
Hi, sorry but you have replied to the wrong person. Looks like the one you
wanted to mention was @swdee, not @SweDee. You've probably figured that out
already but wanted to let you know.

Kind regards,
David (SweDee)

Den fre 11 sep. 2020 kl 13:48 skrev swdee <notifications@github.com>:

**Comment by swdee** [comment]
That was my thought to about querying the K8s API, however depending on the environment that would introduce other problems related to permissions that one would want to avoid.  

I have submitted a PR #3667 which simply updates the installation instructions, which should address this issue for other new users of this chart.

**Comment by andresbono** [comment]
Thanks for opening the PR, @swdee. We will review it shortly.

**Comment by swdee** [comment]
As testing in Minikube worked with `volumeBindingMode: Immediate` we have withdrawn the PR and just leave the solution to this problem in this Issue for others to refer to if they get stuck.

**Comment by andresbono** [comment]
Thank you, @swdee.
