### ISSUE TITLE
[bitnami/cassandra] Backup/Restore/Snapshot

### ISSUE THREAD

**Issue by mquilling** [bitnami/charts#3660]
**Which chart**:
Cassandra 5.4.0

**Is your feature request related to a problem? Please describe.**
We are migrating to bitnami cassandra in Kubernetes and I would like to restore from the snapshot files.  We currently have a 5 node cluster and I have run `nodetool snapshot` on each to generate the snapshot files.

[This](https://docs.bitnami.com/google-templates/infrastructure/cassandra/administration/backup-restore/) does not seem to be relevant and since the containers does not run as root I cannot copy over the snapshots (permission denied).  Even if I could I am not sure how to properly stop cassandra on each node.

**Describe the solution you'd like**
I would like to know the recommended approach and if it's possible using the helm chart.

What's the proper way to do this?  The more details the better - assume I am going from a 5 node cluster to another 5 node cluster.

**Describe alternatives you've considered**
Not using bitnami if backup/restore is not supported.

**Comment by marcosbc** [comment]
Hi @mquilling, note that the previous guide is used for Bitnami single VMs and multi-tier images. Also, we've just discovered some issues in the guide anyways which we're in process of fixing ASAP.

In the case of Helm charts, the Cassandra data directory is located at `/bitnami/cassandra/data` (and not `/opt/bitnami/cassandra/data`). You cannot run "sudo" either (non-root container) nor restart services in the container (a pod recreation is required). The rest of steps are the same though:

* Deploy the new Cassandra pod. The DB schema must already be setup beforehand (i.e. keyspaces and tables). You can automate this via [initDB scripts](https://github.com/bitnami/charts/tree/master/bitnami/cassandra#initializing-the-database). 
* Copy the snapshot to the pod and extract (i.e. via `kubectl cp` + `tar xzf`).
* Run `nodetool drain`
* Clear commitlog directory: `rm /bitnami/cassandra/data/commitlog/*` 
* Delete .db files: `find /bitnami/cassandra/data/data/system/local-UUID/ -name '*.db' -type f -delete` (NOTE: remember to replace `UUID`)
* Copy the snapshot files:

    ```
    $ cp -r /path/to/KEYSPACE/TABLENAME-UUID/snapshots/SNAPSHOTNAME/. /bitnami/cassandra/data/data/KEYSPACE/TABLENAME-UUID/
    ```

    For instance:

    ```
    $ cp -r /tmp/backup/mykeyspace/mytable-885718e0f69911eaaf4b878e2fd960e3/snapshots/1600095035403/. /bitnami/cassandra/data/data/mykeyspace/mytable-885718e0f69911eaaf4b878e2fd960e3/
    ```

* Run `nodetool status mykeyspace`
* Run `nodetool repair mykeyspace`
* Delete the pod to restart and for the changes to take effect: `kubectl delete pod mycassandra-0`

Hope it helps!

**Comment by mquilling** [comment]
Thanks @marcosbc - I have started to go through this process and the one thing I noted was I needed to be root
```
securityContext:
  enabled: true
  fsGroup: 0
  runAsUser: 0
```
In order to copy files, so my plan is to migrate as root, then flip back to the default user.  Since this is a brand new cluster with no data or load I think I can skip the first few steps and just copy over the snapshots.
