### ISSUE TITLE
[bitnami/nginx-ingress-controller] Default backend probe paths should be configurable

### ISSUE THREAD

**Issue by longwa** [bitnami/charts#3662]
**Which chart**:
bitnami/nginx-ingress-controller

**Describe the bug**
Chart does not allow override of the path for default backend health checks and thus can't work with some other custom defaults such as `quay.io/kubernetes-ingress-controller/custom-error-pages-amd64` which serve health at the `/healthz` endpoint. 

Note that this was changed in a PR not too long ago from from `/healthz` to just `/` (which seems wrong to me). 

The best option is default to `/` and allow it to be configured in the`values.yaml`

**Comment by longwa** [comment]
Simple PR submitted to fix: https://github.com/bitnami/charts/pull/3663

**Comment by andresbono** [comment]
Hi @longwa, thanks for opening both the issue and the PR. The change that you are proposing makes sense. We will review and merge #3663 shortly!
