### ISSUE TITLE
Can't fully modify application securityContext

### ISSUE THREAD

**Issue by djcass44** [bitnami/charts#3669]
**Which chart**:
mongodb - 9.1.2
postgresql - 9.4.1
postgresql-ha - 3.6.1
Likely others

**Describe the bug**
Charts do not offer a way of properly configuring an applications security context. E.g. the `allowPrivilegeEscalation` flag cannot be set to false. This is a problem with non-mutating policy engines such as OPA GateKeeper which will reject containers which do not set this flag to false.

**To Reproduce**
1. Install OPA GateKeeper with the allow-privilege-escalation PSP (https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy)
2. Deploy any of the listed charts using standard values
3. `kubectl get events`
4. See that the pod creation failed

**Expected behavior**

The charts should drop privileges that they don't require, or they should be configurable enough for a user to do so.
A rough example:
```yaml
{{- if .Values.securityContext.enabled }}
      securityContext: {{ toYaml .values.securityContext }}
{{- end }}
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I'm happy to fix this for some of the charts, I'm not certain of the best way forward in terms of retaining backwards compatibility.

**Comment by marcosbc** [comment]
Hi @djcass44, you're right. We recently implemented something similar for Fluentd, see: https://github.com/bitnami/charts/pull/3615. I'm going to open an internal task for handling these changes to all related charts.

Unfortunately I cannot give an ETA for when this work would be started. If you are in a hurry to get this working for specific assets, feel free to send a PR applying changes similar to the one I mentioned before, we'd be happy to review it.

**Comment by djcass44** [comment]
Thanks, @marcosbc. I've opened a PR for PostgreSQL (#3687) which I'll use as a canary for the best implementation. When that goes through I'll do some of the other charts. Cheers

**Comment by marcosbc** [comment]
That's great! Thanks for the update.

**Comment by chrismilson** [comment]
Is there any progress on this? 

If not, and the changes would be similar to the changes in the other charts, I would be happy to do a PR for this.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
