### ISSUE TITLE
[bitnami/mariadb-galera]  Document how to update my.cnf settings in a running cluster

### ISSUE THREAD

**Issue by lpghartz** [bitnami/charts#3671]
**Which chart**:
mariadb-galera-4.3.3

**Is your feature request related to a problem? Please describe.**
In a running system, its sometimes necessary to tweak my.cnf settings (for example, to establish/break replication settings). There's no obvious way to with this chart. I'm assuming its something that is possible, but not spelled out in the documentation.

**Describe the solution you'd like**
Documentation for how to update the settings in a running cluster. Deleting the chart isn't acceptable because of the downtime involved (and is worse because the scaling down to zero leaves the cluster in an unknown state and has to be recovered via bootstrapping). 

**Describe alternatives you've considered**
- Editing the files manually, but this requires starting a pod with access to the persistant storage claim, which isn't possible with engines that are ReadWriteOnce (such as Azure's managed-premium storage class)
- Editing the ConfigMap the chart inserts, but that appears to only be evaluated when first configuring the nodes?
- Yelling profanities at my monitor. No response.

This is such a basic need for any database system, I feel like there's got to be something obvious I'm missing (and, presumably others would miss) in the documentation. Or if its not possible, it really needs to be. Half the point of having a multimaster cluster gets lost if you can't do rolling updates.

**Comment by miguelaeh** [comment]
Hi @lpghartz ,
The `my.cnf` file is created from the values as you can see at https://github.com/bitnami/charts/blob/8398ae65dbed054f0bc28bbdda600a65f9c9a812/bitnami/mariadb-galera/values.yaml#L245

I think it should be enough with a `helm upgrade` setting the configuration in your `values.yaml`, the pods should be recreated in order as it is specified here https://github.com/bitnami/charts/blob/8398ae65dbed054f0bc28bbdda600a65f9c9a812/bitnami/mariadb-galera/values.yaml#L55

**Comment by lpghartz** [comment]
Augh, I forgot I tried that at one point, and it corrupted the cluster so I never tried it again. In retrospect, I think the cluster may not have had enough resources to scale the pods, and the attempt caused Kubernetes to evict all of them, which hit the "scaled everything to zero" bug that leaves the galera state dirty, so nothing would restart even after it had freed up resources to do so. 

I've since enabled auto-scaling on that test cluster, so that may be a "safe" option now. I'll give it a shot. I was hoping there was a "cleaner" supported way of doing it. Most of our other services we run have ConfigMaps mounted in the pods and configuration changes are picked up when they happen, rather than going through an expensive delete/recreate cycle on the pods. 

Given this is a fairly uncommon scenario (for us) of needing to update it, it probably doesn't matter in this case. I'll follow-up after testing with the results. If it does, in fact, behave properly, I'd suggest a paragraph about it in the documentation would be good.

Thanks!

**Comment by miguelaeh** [comment]
Hi @lpghartz ,
I agree in that the ConfigMaps should be reloaded automatically. We are already doing it in other charts, so I will check if it is possible here and I will create a PR for that.
Regards.

**Comment by lpghartz** [comment]
That would really be a great enhancement. Doing the upgrade did work, but it was definitely heavier-weight than I like. The process seems to have terminated the pod before re-allocating (so the total number never went higher than the allocated count), which is good, but still less efficient than a simple restart of the server itself.

Should I just close this report, or do you want me to leave it open to associate to the PR?

**Comment by miguelaeh** [comment]
We will associate the PR and it will be closed automatically once the PR is merged.
Regards.

**Comment by miguelaeh** [comment]
Hi @lpghartz ,
I was taking a look to this issue again, I was thinking in adding what is explained here: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments but the upgrade will be needed anyway since it is necessary to upgrade the deployment to re-create the pods. So I think it will not add too much value, and the upgrade seems to be the best way to do this.
Have you considered any other way?

**Comment by miguelaeh** [comment]
If you want to update the ConfigMap directly you will need to deal with the deployment and modify it too to be able to make the pods be recreated and load the new ConfigMap.
If you don't want to perform the upgrade you can modify the ConfigMap manually and add an extra annotation to the deployment that you would need to edit manually too. It would be the same that the link I posted above was explaining but without the need to know all the parameters that were used to deploy the chart.

**Comment by m33li5** [comment]
> Hi @lpghartz ,
> I was taking a look to this issue again, I was thinking in adding what is explained here: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments but the upgrade will be needed anyway since it is necessary to upgrade the deployment to re-create the pods. So I think it will not add too much value, and the upgrade seems to be the best way to do this.
> Have you considered any other way?

@miguelaeh Would you re-consider opening the issue and implementing the mentioned configmap checksum annotations?
For me atleast, making changes to `.Values.mariadbConfiguration` and doing `helm upgrade` only applies the changes to the configMap and doesn't replace any of the running Pods. It would be great if configmap changes triggered pod re-creation.

**Comment by m33li5** [comment]
> Hi @m33li5 ,
> Try using `--recreate-pods` in the upgrade command

The `--recreate-pods` flag has been deprecated https://github.com/helm/helm/pull/6463

**Comment by miguelaeh** [comment]
Hi @m33li5 ,
I was not aware of that, let me create a PR so you can check if it solves your case

**Comment by m33li5** [comment]
> Hi @m33li5 ,
> I was not aware of that, let me create a PR so you can check if it solves your case

This is perfect, solved!
