### ISSUE TITLE
[kafka] jksSecret is not read via helm template

### ISSUE THREAD

**Issue by gowrisankar22** [bitnami/charts#3673]
**Which chart:**
kafka charts

**Describe the bug**
I have created secrets out of the certificate for ssl. I want to configure Kafka with jksSecret & jksPassword and but this value is not read somehow.
 
https://github.com/bitnami/charts/blob/553783f6a3437719e2b17a3f485047ad0ab73a3b/bitnami/kafka/values.yaml#L269

```
 jksSecret: kafka-jks

  ## Password to access the JKS files when they are password-protected.
  ##
 jksPassword: abcd1234

```

```
helm template ../kafka/ -f values.yaml  --set auth.jksSecret=kafka-jks --name-template kafka --namespace default > manifest.yml 
```

BRs, Gowrisankar

**Comment by javsalgar** [comment]
Hi,

According to the templates, it is read in the statefulset.yaml file

```
            {{- if .Values.auth.jksPassword }}
            - name: KAFKA_CERTIFICATE_PASSWORD
              value: {{ .Values.auth.jksPassword | quote }}
            {{- end }}
```

Could you double check that you are setting the value as `auth.jksPassword`?

**Comment by gowrisankar22** [comment]
yes i am setting as `auth.jksPassword ` and `auth.jksSecret` only but it is not thereafter template rendered

**Comment by javsalgar** [comment]
Hi,

I think I saw what is missing , did you set any of the `auth.clientProtocol` or `auth.interBrokerProtocol` values?

```
{{/*
Return true if encryption via TLS should be configured
*/}}
{{- define "kafka.tlsEncryption" -}}
{{- $tlsProtocols := list "tls" "mtls" "sasl_tls" -}}
{{- if or (has .Values.auth.clientProtocol $tlsProtocols) (has .Values.auth.interBrokerProtocol $tlsProtocols) -}}
    {{- true -}}
{{- end -}}
{{- end -}}
```

Otherwise that part will not be rendered.
