### ISSUE TITLE
[bitnami/fluentd] millisecond timestamp log but fluentd drops subsecond

### ISSUE THREAD

**Issue by serg-bs** [bitnami/charts#3680]
**Which chart**:
fluentd 
version: 1.3.0
Docker Image
  repository: bitnami/fluentd
  tag: 1.11.2-debian-10-r0
**Describe the bug**
I have millisecond timestamp log but fluentd drops subsecond.

**To Reproduce**
https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/

enable only aggregator:
https://github.com/serg-bs/efk

```fluentd:
  aggregator:
    enabled: true
    configMap: elasticsearch-output
    service:
      type: NodePort
    extraEnv:
    - name: ELASTICSEARCH_HOST
      value: "efk-elasticsearch-coordinating-only"
    - name: ELASTICSEARCH_PORT
      value: "9200"
  forwarder:
    enabled: false
```
Part of fluentd.conf
```    # Send the logs to the standard output
    <match **>
      @type elasticsearch
      include_tag_key true
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      logstash_format true
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
```

I send log directly from my python and java apps.
But I had trouble with @timestamp field, I dont see millisecond. Milisecond is always 000

https://docs.fluentd.org/v/0.12/quickstart/faq#i-have-millisecond-timestamp-log-but-fluentd-drops-subsecond-why
Looks like bitnami docker image have some trouble with millisecond? 

**Expected behavior**
See millisecond in kibana

**Comment by dani8art** [comment]
Hi @serg-bs thanks for opening the issue

I was researching a bit and I found that in the tutorial case the `000` is correct since the logs from apache are the following.

```
10.48.3.1 - - [17/Sep/2020:11:21:29 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 516
10.48.3.1 - - [17/Sep/2020:11:21:31 +0000] "GET /wp-login.php HTTP/1.1" 200 2122
10.48.3.1 - - [17/Sep/2020:11:21:39 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 516
10.48.3.1 - - [17/Sep/2020:11:21:41 +0000] "GET /wp-login.php HTTP/1.1" 200 2122
```

Could you share with us how you are sending and the format of your logs, please? This case makes me think the error could be in the sense of formating.

**Comment by serg-bs** [comment]
Example with python 
https://github.com/serg-bs/django-hello-world

**Comment by dani8art** [comment]
Your application logs have not milliseconds

```
[18/Sep/2020 10:20:36] "GET /healthz HTTP/1.1" 301 0
[18/Sep/2020 10:20:36] "GET /healthz/ HTTP/1.1" 200 2
[18/Sep/2020 10:20:46] "GET /healthz HTTP/1.1" 301 0
[18/Sep/2020 10:20:46] "GET /healthz/ HTTP/1.1" 200 2
```

**Comment by serg-bs** [comment]
Thanks. I will tune up my project. 
By the way.  Do you enable log output in fluentd for trace purpose? If yes, could I do it with helm chart?

**Comment by dani8art** [comment]
Hi @serg-bs what do you exactly mean with "log output"? logs for the fluentd process it self?

**Comment by serg-bs** [comment]
I mean my app log you show  in previos comment.
I beleave you take it from fluentd.

**Comment by dani8art** [comment]
No, I got it from the app logs. The ones that are collected by fluentd. As they didn't have milliseconds fluentd is not able to get them. 

BTW, you can enable fluentd logging by configuring as https://docs.fluentd.org/configuration/plugin-common-parameters#log_level

**Comment by serg-bs** [comment]
Thanks
