### ISSUE TITLE
[external-dns] Doesn't update entries with new ingress controller load balancer

### ISSUE THREAD

**Issue by bugok** [bitnami/charts#3683]
Disclaimer: I'm not totally sure where this issue is. Whether it's in nginx ingress controller, its chart or in external-dns or its chart. I think the external-dns chart is what makes the most sense to me - but I may be wrong.

**Which chart**:
external-dns, version 3.2.5.

**Describe the bug**
After updating the nginx ingress controller chart (which forced a new load balancer), the dns entries still contained a CNAME to the old load balancer (which doesn't exist)

**To Reproduce**
0. Get an EKS cluster
1. Install nginx ingress controller which will create a classic load balancer. 
2. Install external dns
3. Install an ingress with an external dns annotation. 
4. See that a route53 entry is created (I'm creating CNAMEs)
5. Update the nginx ingress controller to another version (or some other action which will force the creation of a new load balancer)
6. See that the route53 entries don't change, and are pointing to the old classic load balancer (which doesn't exist anymore)

**Expected behavior**
I'd expect that when a new ingress controller is installed, then the route53 entries will be updated to the new load balancer. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.3", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I'm running an EKS cluster on AWS, where I'm using external-dns to create route53 entries.

I'd be happy to supply more information if needed.
Maybe I'm missing something and this is an expected behavior - but I'd like to get confirmation for this.

Thank you!

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Looking at the error, I think this is something that should be reported to the upstream external-dns developers, as it seems to be an issue in the external-dns code itself, not the chart. Could you let them know? https://github.com/kubernetes-sigs/external-dns/issues

If there's anything that we need to work on our side (the chart itself), please let us know.

**Comment by bugok** [comment]
Done: https://github.com/kubernetes-sigs/external-dns/issues/1785
