### ISSUE TITLE
ClusterRoleBinding and ClusterRole using deprecated api versions?

### ISSUE THREAD

**Issue by SeanWally** [bitnami/charts#3692]
**Which chart**:
external-dns, 3.4.0

**Describe the bug**
I'm using `helmfile lint` in my CI pipeline to validate the contents of chart for deployments in my kubernetes clusters. 
 The external-dns chart returns deprecated syntax errors for `rbac.authorization.k8s.io/v1beta1 ClusterRole` and `rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding` using deprecated api versions.

```STDERR:
  Error: 1 chart(s) linted, 1 chart(s) failed
COMBINED OUTPUT:
  ==> Linting /tmp/026977652/default/external-dns/bitnami/external-dns/2.21.1/external-dns
  [ERROR] templates/clusterrole.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRole" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRole"
  [ERROR] templates/clusterrolebinding.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
  Error: 1 chart(s) linted, 1 chart(s) failed
```

**To Reproduce**
1. Update to the latest version of helmfile.
2. Create a helmfile.yaml file that references bitname/externaldns @ v3.4.0
2. Run `helmfile lint` on the helmfile.yaml

**Expected behavior**
The `external-dns` chart should cleanly pass `helmfile` linting.

**Version of Helm and Kubernetes**:
Kubernetes: 1.15
Helm: 3.3.1
Helmfile: 0.128.0

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-658790", GitCommit:"6587900c2b7bd83f0937204894202c93a1ecfb5f", GitTreeState:"clean", BuildDate:"2020-07-16T01:29:42Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Agreed, we should update the RBAC API version because it will be deprecated in 1.20. I will open a task for this, if you want to speed up the process, don't hesitate to open a PR and we will review it.

**Comment by pmalek-sumo** [comment]
This is not an issue anymore in `5.3.4` 👍🏻

**Comment by javsalgar** [comment]
Thanks for confirming! I will proceed to close the ticket. Do not hesitate to reopen in case there's anything we're missing.
