### ISSUE TITLE
[bitnami/grafana] Grafana chart ignores secret for Admin password

### ISSUE THREAD

**Issue by jonfairbanks** [bitnami/charts#3693]
**Which chart**:

- Chart: grafana-3.4.1
- Version: 7.1.4

**Describe the bug**

Grafana does not use the admin password value that is stored in the `grafana-admin` kubernetes secret. This occurs whether the admin password is auto-generated by the chart, or pre-configured during setup of the Helm chart.

**To Reproduce**

I am using Terraform, so my examples are as follows but this also occurs with a basic Helm install --

Allow Grafana to generate its own password:
```
resource "helm_release" "grafana" {
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "grafana"
  name       = "grafana"
  namespace  = "grafana"
  set {
    name  = "ingress.enabled"
    value = "true"
  }
  set {
    name  = "ingress.hosts[0].name"
    value = cloudflare_record.grafana.hostname
  }
}
```

OR

Set a predefined Admin password via config:
```
resource "helm_release" "grafana" {
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "grafana"
  name       = "grafana"
  namespace  = "grafana"
  set {
    name  = "ingress.enabled"
    value = "true"
  }
  set {
    name  = "ingress.hosts[0].name"
    value = cloudflare_record.grafana.hostname
  }
  set_sensitive {
    name  = "admin.password"
    value = "MyAdminPassword"
  }
}
```

**Steps to reproduce the behavior**:

1. Install the Grafana chart either with no admin password set or set one yourself
2. Confirm the admin password that was set in the kubernetes secret (`kubectl get secrets/grafana-admin --template={{.data.GF_SECURITY_ADMIN_PASSWORD}} -n grafana | base64 -d`)
3. Navigate to the Grafana UI and login with the admin user and the password found in step 2.
4. See "Invalid Username or Password" error and HTTP 401 in console

**Expected behavior**

Access to the Grafana UI is allowed with the password defined in the grafana-admin secret

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-26T20:32:49Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The only way to access Grafana UI is to use `grafana-cli` within the pod to reset the admin password:
```
kubectl exec -n grafana grafana-7968bbd4b7-tdklb -- bin/grafana-cli admin reset-admin-password MyAdminPassword
```

After running this step, only now are you able to access Grafana via the UI with the admin user account.

If you dump the contents of the `grafana-admin` secret one last time, you see that it has not changed and still does not reflect the new value.

**Comment by juan131** [comment]
Hi @jonfairbanks 

I'm unable to reproduce the issue.

I installed the Grafana chart using the commands below:

```console
$ helm install grafana bitnami/grafana --set admin.password=MyAdminPassword
$ echo "Password: $(kubectl get secret grafana-admin --namespace default -o jsonpath="{.data.GF_SECURITY_ADMIN_PASSWORD}" | base64 --decode)"
Password: MyAdminPassword
```

Then, I opened a tunnel and access Grafana through http://127.0.0.1:8080 

```console
$ kubectl port-forward svc/grafana 8080:3000
```

Using the credentials below, I logged in without issues:

- User: admin
- Password: MyAdminPassword

**Comment by jonfairbanks** [comment]
Hmm, let me give this another test. Thank you for checking.

**Comment by juan131** [comment]
Sure @jonfairbanks !! Please let us know if you still run into issues with it.

**Comment by jonfairbanks** [comment]
I think this related to some stale references lying around from a prior install attempt. Closing for now. 😸
