### ISSUE TITLE
dnspolicy option need to enable for mongo db statefulset

### ISSUE THREAD

**Issue by vnvbadri** [bitnami/charts#3694]
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values-production.yaml
by default it is using dnspolicy:clusterfirst it need option for dnspolicy: none and dnsconfig name server
**Which chart**:
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marcosbc** [comment]
Hi @vnvbadri, we encourage users to contribute to the [bitnami/charts](https://github.com/bitnami/charts) repo by submitting PRs. To contribute, have a look to the [Contributing Guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md).
