### ISSUE TITLE
[bitnami/mongodb-sharded] missing annotations in service

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#3695]
**Which chart**:

[bitnami/mongodb-sharded]

**Describe the bug**
There is no annotations here
https://github.com/bitnami/charts/blob/master/bitnami/mongodb-sharded/templates/mongos/mongos-service.yaml

so this setting doesn't work
https://github.com/bitnami/charts/blob/033787e25299036444eaaeaad39115f88b6feb00/bitnami/mongodb-sharded/values.yaml#L773

Probably need something like this?
```yml
  {{- if .Values.service.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}  
```

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. The service annotations are used in the _headless-service_
https://github.com/bitnami/charts/blob/033787e25299036444eaaeaad39115f88b6feb00/bitnami/mongodb-sharded/templates/headless-service.yaml#L6

But I agree on the _mongos-service_ should also have the annotations. Would you like to send a PR adding it? Thank you

**Comment by maxisam** [comment]
@carrodher Do you think the fix I proposed is good enough?

**Comment by carrodher** [comment]
Yes, I think you can duplicate the same approach used in _templates/headless-service.yaml_, thanks for your collaboration!

**Comment by maxisam** [comment]
The chart version number was outdated by the time it got merged. It should be 2.1.3.

**Comment by carrodher** [comment]
That's the reason why those changes are present in the code repo (GitHub) but not in the chart registry.
Bumping the chart version, our automated pipeline should detect, test, and release the new version. Thanks
