### ISSUE TITLE
open edx platform user activation

### ISSUE THREAD

**Issue by simsah** [bitnami/charts#3701]
I have successfully installed the open edx platform and created user accounts. When I create an user. I immediately have access to the demo project. When I log out, there I could not found a way to login again. The problem is that I do not get an activation mail to confirm the account.  I have tried with gmail smtp and smtp2go mail servers. I would be grateful for any suggestion.
Thank you

**Comment by carrodher** [comment]
Hi, via GitHub issues Bitnami provides support for Docker images and Helm charts, in this case, I think you are using a virtual machine, cloud installation, or a local installer, in those cases the support is provided in the [Bitnami Community forum](https://community.bitnami.com/), can you create the post in that forum? Thanks!

**Comment by simsah** [comment]
Uups, thank you.. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [bitnami/charts] open edx platform user activation (#3701)From: Carlos Rodríguez Hernández To: bitnami/charts CC: simsah ,Author 
Hi, via GitHub issues Bitnami provides support for Docker images and Helm charts, in this case, I think you are using a virtual machine, cloud installation, or a local installer, in those cases the support is provided in the Bitnami Community forum, can you create the post in that forum? Thanks!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bitnami/charts/issues/3701#issuecomment-694797744",
"url": "https://github.com/bitnami/charts/issues/3701#issuecomment-694797744",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
