### ISSUE TITLE
[bitnami/rabbitmq] ability to not expose default ports

### ISSUE THREAD

**Issue by radunicolae** [bitnami/charts#3704]
**Which chart**:
bitnami/rabbitmq

**Is your feature request related to a problem? Please describe.**
I am attempting, an failing, to comment out ports: 5672, 4369 and 25672
I have no issue with the container exposing the ports I just don't want the service (AWS ELB in our case) to expose to ports to the outside

**Describe the solution you'd like**
And extra set of parameters

**Describe alternatives you've considered**

**Additional context**
I have tried editing the svc.yaml file but helm seems to ignore any modification.

**Comment by andresbono** [comment]
Hi @radunicolae, I'm afraid that the `svc.yaml` template doesn't allow to enable/disable those ports:

https://github.com/bitnami/charts/blob/8bfacfaa23af65ed2cbcfeba870c9b15f70aeb4e/bitnami/rabbitmq/templates/svc.yaml#L27-L60

Maybe what you can do is keeping that service as ClusterIP and then after launching the Helm Chart you create an additional service of type `LoadBalancer` that suit your needs. You might find useful the following command to get the current manifest of your service:

```console
$ kubectl get svc YOUR_SERVICE -o yaml
```

**Comment by radunicolae** [comment]
Hello @andresbono I ended up editing the svc.yaml:

> ports:
>     {{- if .Values.ampq.enabled }}
>     - name: amqp
>       port: {{ .Values.service.port }}
>       targetPort: amqp
>       {{- if (eq .Values.service.type "ClusterIP") }}
>       nodePort: null
>       {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
>       nodePort: {{ .Values.service.nodePort }}
>       {{- end }}
>     {{- end }}
>     {{- if .Values.auth.tls.enabled }}
>     - name: amqp-ssl
>       port: {{ .Values.service.tlsPort }}
>       targetPort: amqp-ssl
>       {{- if (eq .Values.service.type "ClusterIP") }}
>       nodePort: null
>       {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.tlsNodePort)) }}
>       nodePort: {{ .Values.service.tlsNodePort }}
>       {{- end }}
>     {{- end }}
>     {{- if .Values.empd.enabled }}
>     - name: epmd
>       port: 4369
>       targetPort: epmd
>       {{- if (eq .Values.service.type "ClusterIP") }}
>       nodePort: null
>       {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.epmdNodePort))) }}
>       nodePort: {{ .Values.service.epmdNodePort }}
>       {{- end }}
>     {{- end }}
>     {{- if .Values.dist.enabled }}
>     - name: dist
>       port: {{ .Values.service.distPort }}
>       targetPort: dist
>       {{- if eq .Values.service.type "ClusterIP" }}
>       nodePort: null
>       {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.distNodePort))) }}
>       nodePort: {{ .Values.service.distNodePort }}
>       {{- end }}
>     {{- end }}
>     - name: http-stats
>       port: {{ .Values.service.managerPort }}
>       targetPort: stats
>       {{- if eq .Values.service.type "ClusterIP" }}
>       nodePort: null
>       {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.managerNodePort))) }}
>       nodePort: {{ .Values.service.managerNodePort }}
>       {{- end }}
>     {{- if .Values.metrics.enabled }}
>     - name: metrics
>       port: {{ .Values.service.metricsPort }}
>       targetPort: metrics
>       {{- if eq .Values.service.type "ClusterIP" }}
>       nodePort: null
>       {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.metricsNodePort))) }}
>       nodePort: {{ .Values.service.metricsNodePort }}
>       {{- end }}
>     {{- end }}
>     {{- if .Values.service.extraPorts }}
>     {{- include "common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
>     {{- end }}

and adding an option to enable / disable the ports then added the corresponding lines in values.yaml


## Disable unnecessary ports
ampq:
  enabled: false
empd:
  enabled: false
dist:
  enabled: false

**Comment by andresbono** [comment]
That works as well, thanks for letting us know. But note that you may have issues if you do `helm upgrade` for future versions of the chart.
