### ISSUE TITLE
[redis] In version 11.0.0 you cannot just install master, without slave

### ISSUE THREAD

**Issue by zackijack** [bitnami/charts#3707]
**Which chart**:
redis
version: 11.0.0

**Describe the bug**
In [this commit](https://github.com/bitnami/charts/commit/782f4bfbf070f9f0c66612c9b234efc4212fd460#diff-66583f0ecdcb594f25a53f3b240317cdR1) there is one condition that causes not able to install only the master, without the slave

**To Reproduce**
install with `cluster.enabled=false`
```bash
$ helm install redis bitnami/redis --set cluster.enabled=false
```

**Expected behavior**
Sometimes we just need a single instance of redis (a master), no cluster or sentinel.

**Comment by Klohto** [comment]
Workaround discussed on https://github.com/bitnami/charts/pull/3658

Still no word from Bitnami if cluster=false and sentinel=false are actually supported.

**Comment by florent-tails** [comment]
Ran into the same issue – a workaround for now is to just leave it as enabled and set `cluster.slaveCount` to 0. 🤷

**Comment by FraPazGal** [comment]
Hello all,

It does seems that we introduced a typo in PR #3658 that is provoking that no master instance is installed unless `cluster.enabled=false`, sorry for the inconvenience. I will make a couple more of tests and create a new PR to fix this issue. 

In the meantime, please use the workaround provided by @florent-tails of setting the number of slaves in the cluster to 0. Thanks for helping out!!
