### ISSUE TITLE
[bitnami/prestashop] Add a section in the documentation to explain how to activate SSL in Prestashop, the chart configuration itself is not enough

### ISSUE THREAD

**Issue by sylver** [bitnami/charts#3714]
**Which chart**:
prestashop 9.2.12

**Describe the bug**

I have provisioned the chart behind my own ingress (Kong), the relevant values used are : 
```
  service.type: 'NodePort',
  prestashopHost: 'my.final.host.domain.tld',
  ingress.enabled: false,
  mariadb.enabled: true,
```

Everything is deployed properly and my ingress (with `external-dns` and `cert-manager`) is properly updated to route to the prestashop service.

I can trace the routing to the prestashop pod when I call `my.final.host.domain.tld` (as configured in the ingress and in the `prestashopHost` value of the chart), as expected, but that triggers an infinite 302 redirection loop from prestashop.

```
...
#REDACTED# - - [18/Sep/2020:16:35:08 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:10 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:10 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:10 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:11 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:11 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:11 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:12 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:12 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:12 +0000] "GET / HTTP/1.1" 302 -
#REDACTED# - - [18/Sep/2020:16:35:13 +0000] "GET / HTTP/1.1" 302 -
...
```

I don't see what's wrong in my configuration and how I could avoid prestashop to do this infinite redirect (to itself...)

**EDIT**: The infinite redirection issue does not happen when calling the `/administration` route (but still one `302` redirection is sent, it just doesn't loop indefinitely on this one route, which is the expected behavior I suppose).

**Expected behavior**

Remove the weird redirect or at least have a way to disable it if that has any use in some cases.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sylver** [comment]
I investigated further, the loop problem was caused by a Kong plugin I have, forcing https connection with a 302, while your Apache server returns a 302 to http (?!) 

<img width="346" alt="Screen Shot 2020-09-20 at 2 00 29 AM" src="https://user-images.githubusercontent.com/3833987/93691660-a244dc80-fae8-11ea-9f4a-56ba5f54c190.png">

I then tried with your own Ingress (without the https redirect plugin), and still https connections are getting a 302 to http from Apache (as expected): 

<img width="273" alt="Screen Shot 2020-09-20 at 2 16 26 AM" src="https://user-images.githubusercontent.com/3833987/93691661-abce4480-fae8-11ea-9682-05eeb3b37dd7.png">

Why would you force redirect to a non-secure connection ?

**Comment by sylver** [comment]
Ok, finally found the problem. Turns out one needs to manually activate SSL in the prestashop administration panel, else it forces a non-secure connection...

Maybe you could turn that on automatically if the SSL is configure in the chart ? One can't guess that by himself, I've spend days trying to figure that out while the problem was totally unrelated to the chart. At least put a troubleshooting section in the documentation.

**Comment by carrodher** [comment]
Thanks for the detailed information! If it is something that needs to be activated in the admin panel via Prestashop UI I think it is not going to be easy to activate it automatically from the chart according to the values selected by the user.

In that case, I agree to have a section in the README documenting this use case. Would you like to collaborate by creating a PR adding this section? We would be happy to review the PR and include that section in the README

**Comment by sylver** [comment]
Sure, here it is @carrodher 

I didn't bump the chart version since that's just documentation (thus the failing test), let me know if that's ok.

**Comment by carrodher** [comment]
Thanks for your contribution! I'll review the PR and merge if everything looks fine
