### ISSUE TITLE
Redis-cli require password while usePassword is false 

### ISSUE THREAD

**Issue by halradaideh** [bitnami/charts#3717]
Redis chart - redis-10.6.0

when i try to connect to redis using cli is keep asking for password, but i deployed it with usepassword = false

![image](https://user-images.githubusercontent.com/43438708/93665337-49d8f500-fa7e-11ea-86ef-c467bccef94a.png)

kubernetes version
v1.14.10-gke.36

helm version
2.16

**Comment by sundowndev** [comment]
I have the same issue, any advice ?

**Comment by halradaideh** [comment]
i was using the chart as requirement helm chart, and forget to indent it under redis:

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know! @sundowndev is your case similar to @halradaideh ?

**Comment by sundowndev** [comment]
@javsalgar Thanks for asking, I think that was an issue on my end, I finally chose to use a password anyway.

**Comment by javsalgar** [comment]
Ok, do not hesitate to open a new ticket if you find any other issue.
