### ISSUE TITLE
[bitnami/prestashop] Included mariadb deployment does not have any affinity configuration

### ISSUE THREAD

**Issue by sylver** [bitnami/charts#3721]
**Which chart**:

prestashop 9.2.12

**Is your feature request related to a problem? Please describe.**

The chart includes the possibility to provision by itself the database as a mariadb pod. Unfortunately the `affinity` value parameter does not seem to be used by this pod and it deploys on the first node it finds available. I didn't find any way with the chart to define where this pod should be deployed.

**Describe the solution you'd like**

Have an option to define the mariadb pod affinity, or at least use the same `affinity` values as for the prestashop pod.

**Describe alternatives you've considered**

You can try to patch the pod afterward but that's not practical in an automated CD

**Comment by FraPazGal** [comment]
Hi @sylver,

You can indeed use the `affinity` parameter for mariadb. This chart uses the [bitnami/mariadb](https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml) one as a subchart, so you can use and configure every property already present in that chart. In this case, you would need to define the `Values.mariadb.affinity` value.

**Comment by sylver** [comment]
Hi @FraPazGal,

Thanks for the tip, didn't know we could do that ! (The exact parameter was `Values.mariadb.master.affinity`)
 
I can indeed update the pod affinity this way, unfortunately now I get an affinity conflict with the associated volume that was provisioned before. Even a fresh new install does not target the affinity node for the `pv`. 

It does not seem I can configure that in the `mariadb` chart, could you confirm that ? I would probably need to provide my own `pv` with the right `nodeAffinity` instead then ?

**Comment by FraPazGal** [comment]
Hi @sylver,

It is as you say, I'm afraid that you can't configure the persistent volume `nodeAffinity` from the `mariadb` chart. So if a fresh install doesn't configure correctly the affinity for the `pv`, you would need to release your own `pv`.

**Comment by sylver** [comment]
That's what I thought, thanks for your help @FraPazGal !
