### ISSUE TITLE
existingSecret: Wrong or unclear readme

### ISSUE THREAD

**Issue by alex-jesper** [bitnami/charts#3722]
**Which chart**:

Latest postgresql chart

**Is your feature request related to a problem? Please describe.**

The README.md is incorrect or wrong.

**Describe the solution you'd like**
Change the readme.

**The problem**

The readme under existing secret states:

> The secret has to contain the keys postgresql-postgres-password which is the password for postgresqlUsername when it is different of postgres, postgresql-password which will override postgresqlPassword

But `postgresql-postgres-password` is the admin password, and not the password of the optionally-created-non-admin-user of `postgresqlUsername`. I think the password-keys should be swapped so it should instead be:

> The secret has to contain the keys postgresql-password which is the password for postgresqlUsername when it is different of postgres, postgresql-postgres-password which will override postgresqlPassword`

I would like someone to verify that I am correct and then I can do a pull request.

/Jesper

**Comment by juan131** [comment]
Hi @alex-jesper 

You're 100% right! Thanks for the correction. Please submit a PR and I'll be glad to review it.

**Comment by alex-jesper** [comment]
Hi @juan131,

It seems I do not have permission to create a new branch, is that something you can fix?

**Comment by juan131** [comment]
You don't need to create a new branch in this repo. Instead, please fork the repo, upload your changes to some branch in you fork, and submit the PR. Find more information in the link below:

- https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#how-to-contribute

**Comment by alex-jesper** [comment]
@juan131 I created the PR for you.

**Comment by juan131** [comment]
Your PR was approved and landed. Thanks so much for the fix!
