### ISSUE TITLE
[Bitnami/kube-prometheus] Lack of exporters for: kube-controller-manager, kube-scheduler and coredns

### ISSUE THREAD

**Issue by miko-epam** [bitnami/charts#3724]
The current set of exporters includes:
- kube-apiserver
- kube-proxy
- kubelet

It would be helpful to have ServiceMonitor for the following components, as these are important part of Kubernetes:
- kube-controller-manager
- kube-scheduler
- coredns

There components are currently included into helm stable/prometheus-operator

**Comment by carrodher** [comment]
Thanks for creating the issue and the associated PR, we are going to review the PR and provide feedback (if needed). Thanks!
