### ISSUE TITLE
Can Someone please help me to get the postgresql helm charts of version 8.10.14.

### ISSUE THREAD

**Issue by yerriswamykonanki** [bitnami/charts#3726]
Could someone shares with me the download link of Postgresql helm charts of version 8.10.14.

**Comment by killerzwelch** [comment]
Hi, I don't know what you want to achieve. But here is the link
https://charts.bitnami.com/bitnami/postgresql-8.10.14.tgz

You can find this out when downloading the repo yaml (the path where you make the add repo and add index.yaml at the end) so in that case https://charts.bitnami.com/bitnami/index.yaml 
There you can find the chart including the URLs.

**Comment by yerriswamykonanki** [comment]
Thank you So much @killerzwelch. I have a reqquirment to maintain our own helm chart repository. For that I am collecting all the rerquired helm charts.

Can you share me the Redis helm charts of version 10.9.0.

**Comment by killerzwelch** [comment]
hi @yerriswamykonanki,
you're welcome, please look it up on your own. The just browse the yaml for your helm chart that you're searching.
kind regards

**Comment by miguelaeh** [comment]
Hi,
You can download the required version using the following:
```
helm fetch bitnami/<chart-name> --version <version>
```

Note you must have the bitnami repository enabled previously:
```
 helm repo add bitnami https://charts.bitnami.com/bitnami
```

In your specific case, to download redis:
```
helm fetch bitnami/redis --version 10.9.0
```
