### ISSUE TITLE
[redis]: post-upgrade-hook runs before chart dependency is ready

### ISSUE THREAD

**Issue by damienwebdev** [bitnami/charts#3732]
**Which chart**:
`bitnami/redis:11.0.0`

**Describe the bug**
I utilize redis:11.0.0 as a dependency of a larger chart. When installing my parent chart, the `post-upgrade-hook` for the parent chart fires before this chart is ready.

**To Reproduce**
Use redis as a dependent chart, run an upgrade for the parent chart which modifies `redis`. Redis will not be ready when parent chart's hook runs. 

**Expected behavior**
A flawless upgrade process.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by FraPazGal** [comment]
Hi @damienwebdev,

Have you tried to upgrade your chart using `helm upgrade --wait`? By default, the upgrade is considered as successful when all the resources have been released. Using `--wait`, it would only be considered a completed upgrade once all the resources are released and the minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are ready, so it shouldn't start the post-upgrade-hook until then.

**Comment by damienwebdev** [comment]
Yep. My mistake.
