### ISSUE TITLE
[redis] cluster.enabled=false failed to deploy

### ISSUE THREAD

**Issue by vilyansky** [bitnami/charts#3737]
**Which chart**:
bitnami/redis-11.0.1

**Describe the bug**
redis is not deployed with cluster.enabled=false

**To Reproduce**
1. Set
```yaml
cluster:
  enabled: false
```
in values.yaml

2. 
```bash
$ helm install redis -f values.yaml  bitnami/redis
```
3.
```bash
$ helm ls
NAME 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION  
redis	default  	1       	2020-09-21 19:19:58.704537179 +0300 MSK	deployed	redis-11.0.1	6.0.8      
```
4.
```bash
$ kubectl get pods  
No resources found in default namespace.
```

**Expected behavior**
```bash
$ kubectl get pods
NAME             READY   STATUS    RESTARTS   AGE
redis-master-0   0/1     Running   0          5s
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
It also happens with 11.0.0 chart version. With 10.8.x is everything ok.

**Comment by vilyansky** [comment]
O_o, great!

**Comment by carrodher** [comment]
Thanks for reporting the issue, it was a typo introduced in a recent PR; once fully tested and merged the PR our internal CI/CD pipeline is going to release a new chart version that is going to be available in the chart repository after `helm repo update`

**Comment by mihaisee** [comment]
Hello, I might be missing something here (sorry if that's the case). But I have an issue with this: 
I can see the new version `11.0.3` (as specified in #3738 Chart.yaml) after `helm repo update`.
I run `helm dep up` on my chart and it successfully pulls the new chart version in the `charts` directory. 
All good up to this point.
The issue I am encountering is that the chart is missing all the changes in the #3738 and I still can't deploy the chart without cluster enabled.
Same thing if I run `helm --namespace=default install test-redis-no-cluster bitnami/redis --version 11.0.3 --set cluster.enabled=false`. No statefulsets are created.

Thanks

**Comment by miguelaeh** [comment]
Hi, 
Thank you for notifying this.
It seems that two PRs were merged simultaneously for Redis, we have forced a new release and now it is on the index.
Regards.
