### ISSUE TITLE
[bitnami/kube-prometheus] Published chart is outdated

### ISSUE THREAD

**Issue by hwoarang** [bitnami/charts#3741]
**Which chart**:
bitnami/kube-prometheus

**Describe the bug**
helm repo update && helm search repo bitnami/kube-prometheus returns

```
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                       
bitnami/kube-prometheus	1.1.0        	0.41.1     	kube-prometheus collects Kubernetes manifests t...
```
However, the chart has been bumped to 2.0.0 about 2 weeks ago.

https://github.com/bitnami/charts/commit/75da3d6252c6d772d12b51575a0b9541e6197fe1

Just wanted to check if everything is OK with publishing updates for this chart. If there is a better place to ask these questions instead of creating an issue please let me know :)

**Comment by FraPazGal** [comment]
Hello @hwoarang, 

Don't worry, this is exactly the place for asking this! 

There is indeed a problem with this chart newest version in our internal CI/CD tool. It is a known issue that we are working on fixing. It should be solved for the end of the week and thus updated in our helm repo.
