### ISSUE TITLE
[Bitnami/Thanos] Feature request of Query Frontend

### ISSUE THREAD

**Issue by ioannissavvaidis** [bitnami/charts#3747]
**Which chart**:
Bitnami/Thanos [latest]

**Is your feature request related to a problem? Please describe.**
After metrics observation for our Thanos installation, we noticed latency in Thanos Querier.
This latency comes from long-range queries, during streaming series from Prometheus.

**Describe the solution you'd like**
Add the option in Thanos Chart to install [Query Frontend](https://thanos.io/v0.15/components/query-frontend/#query-frontend) component.

Thank you!

**Comment by ioannissavvaidis** [comment]
Closing issue, I will prepare a PR.

**Comment by miguelaeh** [comment]
Hi @ioannissavvaidis ,
Thank you very much for requesting the feature.
I will create an internal task and we will update this thread once we have news.
Regards.

**Comment by ioannissavvaidis** [comment]
Thank you @miguelaeh !

**Comment by ioannissavvaidis** [comment]
Hello @miguelaeh,

Do you have any update on this issue?

Thank you!

**Comment by ioannissavvaidis** [comment]
Its ok, the latest version of Thanos with this component is at [pre-release state](https://github.com/thanos-io/thanos/releases/tag/v0.16.0-rc.0).

**Comment by carrodher** [comment]
Hi, at this moment the task is included in our backlog, as we are a small team we need to balance our bandwidth between fixing issues and adding new features. In this case, I hope the task is added to our sprints in the future, but I can't provide you an exact ETA to be fully done. Thanks

**Comment by ioannissavvaidis** [comment]
Thanks for you reply @carrodher , I totally understand!
