### ISSUE TITLE
[bitnami/rabbitmq] Add config checksum to pod annotations

### ISSUE THREAD

**Issue by WolfspiritM** [bitnami/charts#3749]
**Which chart**:
rabbitmq 7.6.7

**Is your feature request related to a problem? Please describe.**
Changing for example verify_peer to verify_none doesn't trigger an update of the pods and requires a manual change of the statefulset to become active

**Describe the solution you'd like**
Adding a checksum to the annotation will cause the pods to be rescheduled

**Comment by javsalgar** [comment]
Hi,

Yes, you are right. We do not have a checksum for the configmap. I will open a task to implement it. As it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, do not hesitate to open a PR and we will review it.

**Comment by javsalgar** [comment]
Checking this again, it seems that's already done https://github.com/bitnami/charts/issues/4402
