### ISSUE TITLE
Bitnami mongodb cluster can't access from mongo3t client kubernetes

### ISSUE THREAD

**Issue by SHUFIL** [bitnami/charts#3751]
I have installed bitnami mongodb cluster with `helm install my-release bitnami/mongodb -f values-production.yaml . , architecture: replicaset , and replicaCount: 2` in aws server,

`helm version version.BuildInfo{Version:"v3.2.4",CHART mongodb-8.2.1, APP VERSION 4.2.8,  kubectl version GitVersion:"v1.16.8"`
Its installed successfully one statefulset along with three pods and one svc , I have put port forward, to get access mongodb from Robo3T client as a localhost with using user name and password , But its getting Error , it is `Authorization failed on admin database as root`

I have tryed with portforword to svc , pod, and statefulset all are getting same error .

`kubectl port-forward  --namespace default svc/my-release-mongodb-headless 27017:27017`
I dont need mongodb access though with puplic ip , so used `type : NoodePort `
Is it I done any wrong or anything extra i need to mension in values-production.yaml file ?

**Comment by muhaarif** [comment]
I got same issues

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I installed the chart with these parameters

```
helm install mymongo . -f values-production.yaml --set architecture=replicaset --set replicaCount=2
```

Then I got the password

```
kubectl get secret --namespace default mymongo-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode
```

Then I was able to connect without issues

![image](https://user-images.githubusercontent.com/1133777/93986942-3d5ae200-fd87-11ea-9c69-87b46d585781.png)

**Comment by SHUFIL** [comment]
whitch host-name you used , did you used port-forward ?

**Comment by SHUFIL** [comment]
can u plz share me the host name which one used in mongo3T and  portforward command ? , i need to know to where you portforward , becoase its not happening from myside

**Comment by javsalgar** [comment]
Hi,

Yes, I used the same kubectl port-forward command you specified in the post

```
kubectl port-forward --namespace default svc/my-release-mongodb-headless 27017:27017
```

The hostname I used is `localhost`
