### ISSUE TITLE
[bitnami/Guacamole] Can’t create users through CLI

### ISSUE THREAD

**Issue by AStrangerInAStrangeLand** [bitnami/charts#3756]
Hi. 

I am trying to automate the creation of my users in Guacamole on AWS by using an SSH script and having all the details configured in the CLI. 

The only issue is there is no clear way for me to create USERS and / or ￼ AMEND the details for them like the URL mapping them to a specific instance. 

I am sure there is a way, but there is nothing I have found as of yet in the docs or online and I am having to do it through the GUI at the moment. Thanks.

**Comment by carrodher** [comment]
Hi, Bitnami provides support for Docker images and Helm charts via GitHub issues, in this case, I think you are using a virtual machine, cloud installation, or a local installer, in those cases the support is provided in the [Bitnami Community forum](https://community.bitnami.com/), can you create the post in that forum? Thanks!
