### ISSUE TITLE
[bitnami/wordpress] Cannot use custom php.ini

### ISSUE THREAD

**Issue by theclue** [bitnami/charts#3757]
I'm working with the latest wordpress helm chart and I was wondering if I can use a custom `php.ini` file. This is because these overrides don't have effect (perhaps for [this](https://wordpress.stackexchange.com/questions/256261/which-one-does-wordpress-prioritize-when-it-comes-to-php-ini-wp-config-and-hta))

```
wordpressExtraConfigContent: |
  @ini_set( 'upload_max_filesize' , '192M' );
  @ini_set( 'post_max_size', '192M');
  @ini_set( 'max_execution_time', '600');
```

Changing the default php.ini file seems tricky, as /bitnami/php path is not into the PV (which would allow me to use an initContainer to put data into).

I'm NOT using e derived WP docker image.

Any idea on how to do that without creating a custom Docker image?

**Comment by javsalgar** [comment]
Hi,

Right now, the way that comes to mind is by using the `extraVolumes` and `extraVolumeMounts`. With that, you could mount an existing configmap with thp php.ini settings. However, I believe we should make it easier for the php settings to be modified.
