### ISSUE TITLE
[chart\postgres]Error: execution error at (postgresql/templates/statefulset.yaml:436:29)

### ISSUE THREAD

**Issue by rjeka** [bitnami/charts#3758]
**Which chart**:
name: postgresql
version: 9.7.0

**Describe the bug**
Hello!
When I try to deploy Postgres with production values I get an error
```
Error: execution error at (postgresql/templates/statefulset.yaml:436:29): In order to enable metrics you need to specify a database (.Values.postgresqlDatabase or .Values.global.postgresql.postgresqlDatabase)
```

**To Reproduce**
1. helm fetch bitnami/postgresql --untar
2. cd postgresql 
3. helm install postgres -f values-production.yaml ./ 
4. Error: execution error at (postgresql/templates/statefulset.yaml:436:29): In order to enable metrics you need to specify a database (.Values.postgresqlDatabase or .Values.global.postgresql.postgresqlDatabase)

**Expected behavior**
If I try to install without production values file chart is installed without error
```
helm install postgres ./ --dry-run
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by juan131** [comment]
Hi @rjeka 

The **values-production.yaml** requires some "extra" values to be passed. Please try with:

```console
$ helm install postgres . \
    -f values-production.yaml \
  --set postgresqlDatabase=SomeDatabase \
  --set postgresqlPassword=SomePassword
