### ISSUE TITLE
I don't reach how to inject apache rewrite conditions on production values by bitnami/wordpress

### ISSUE THREAD

**Issue by floresfactor** [bitnami/charts#3760]
I installed bitnami's wordpress stack via Helm, everything works very well, I just want to apply the redirection from http to https but I don't see a clear example to add apache rewrite conditions in the production values of the chart, could you give me an example of how add them.

¡Saludos Bitnami! desde México

**Comment by carrodher** [comment]
Hi, this is something usually done by using an Ingress Controller. As this is an advance configuration we documented it in the following guide: https://docs.bitnami.com/tutorials/secure-wordpress-kubernetes-managed-database-ssl-upgrades/#secure-traffic-with-tls-and-lets-encrypt-ssl-certificates
