### ISSUE TITLE
[mariadb] pvc does not be deleted after uninstall

### ISSUE THREAD

**Issue by Hokwang** [bitnami/charts#3761]
**Which chart**:
bitnami/mariadb

**Describe the bug**
```
helm install mariadb-test -f myvalues.yaml bitnami/mariadb
helm uninstall mariadb-test 
kubectl get pvc
NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
data-mariadb-master-0   Bound    pvc-fd682b3f-2470-4e36-8a22-2c2a63b8bb08   8Gi        RWO            sc-stage   14h
data-mariadb-slave-0    Bound    pvc-337aff87-4328-4cae-83a6-0d305940b72b   8Gi        RWO            sc-stage   14h
data-mariadb-slave-1    Bound    pvc-05ad634e-159f-457b-b6b8-3bb599aa7ebd   8Gi        RWO            sc-stage   14h
```
In myvalues.yaml, I am using storageClass.

**Expected behavior**
remove pvc also

**Version of Helm and Kubernetes**:
helm 3 and kubernetes 1.17.11

**Comment by miguelaeh** [comment]
Hi @Hokwang ,
This is not an issue related to the chart but something related to Helm itself. The PVCs are not deleted after uninstalling a release. I think that is something that has been discussed several times in the Helm repository.

**Comment by Hokwang** [comment]
@miguelaeh Thanks for your comment, I didn't know that. I will close this case.
