### ISSUE TITLE
[bitnami/mongodb] LoadBalancer services not created with externalAccess enabled

### ISSUE THREAD

**Issue by mnmami** [bitnami/charts#3764]
**Which chart**:
Bitnami/MongoDB Chart version 9.1.2, App version 4.4.1

**Describe the bug**
LoadBalancer services not created with externalAccess enabled

**To Reproduce**
1. create the following custom values:
```yaml
architecture: replicaset
replicaCount: 2
externalAccess.enabled: true
externalAccess.service.type: LoadBalancer
externalAccess.service.port: 27017
externalAccess.autoDiscovery.enabled: true
externalAccess.service.loadBalancerIPs[0]: a.b.c.d
externalAccess.service.loadBalancerIPs[1]: w.x.y.z.
```
Also without  `externalAccess.service.loadBalancerIP`.

2. Install the chart:
```bash
helm install mongodb bitnami/mongodb -f externalAccess.yaml
```
3. Run `kubectl get svc`. 
```bash
kubernetes                           ClusterIP   10.98.0.1    <none>        443/TCP     21d
mongodb-arbiter-headless             ClusterIP   None         <none>        27017/TCP   43m
mongodb-headless                     ClusterIP   None         <none>        27017/TCP   43m
```

**Expected behavior**
Get the LoadBalancer services along the external IP addresses to allow remote access e.g. from a mongo shell.

Something like:
```bash
mongodb-0-external         LoadBalancer    a.b.c.d    <none>        27017:30030/TCP   4m37s
mongodb-1-external         LoadBalancer    w.x.y.z     <none>        27017:30031/TCP   4m37s
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by marcosbc** [comment]
Hi @mnmami, this certainly looks like a bug. We're looking into this and will get back to you, but if you find the issue before that, feel free to send a PR.

**Comment by romainehinds17** [comment]
If this is a bare metal cluster, do you have an external LB installed within the cluster?

**Comment by mnmami** [comment]
Mieanwhile, @marcosbc could you point to a version where the external access should work and reliably?

**Comment by mnmami** [comment]
@romainehinds17, I'm running that on GCP.

**Comment by marcosbc** [comment]
Hi @mnmami, that was implemented in the chart version 8.0.0, so if it fails, it's probably due to some environment configuration issues on your side.

Note that the service you are referring to is NOT the external-access service. It should be shown like this:

```
NAME                                      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                 AGE
mymongodb01-0-external                    LoadBalancer   11.22.33.44     22.33.44.55     27017:30358/TCP                         4m41s
mymongodb01-1-external                    LoadBalancer   33.44.55.66     77.88.99.11     27017:32717/TCP                         4m41s
mymongodb01-arbiter-headless              ClusterIP      None            <none>          27017/TCP                               4m41s
mymongodb01-headless                      ClusterIP      None            <none>          27017/TCP                               4m41s
```

If they do not show, it's probable that they're not being deployed. Please make sure that this is happening by executing `helm template ...` instead of `helm install ...` (using same arguments), you should see this being output:

```
...
---
# Source: mongodb/templates/replicaset/external-access-svc.yaml
---
apiVersion: v1
kind: Service
metadata:
```

If that is not the case, then you are not deploying with the proper options. 

If that file does appear, however, but the service gets removed, make sure you don't have any kind of internal service that removes `type: Service` objects exposed to the public and that don't contain a proper annotation. In our case, when we deploy to GKE, we have to specify the following extra option for it to work:

```
--set 'externalAccess.service.annotations.cloud\.google\.com/load-balancer-type=internal'
```

**Comment by mnmami** [comment]
Hi @marcosbc,

Using `helm template` did return the services, but with _ClusterIP_ as service type, exactly like what I get as a result. 

I, however, got to create the LoadBalance services by passing all the options via the `--set` args to the `helm install` command.

```bash
helm install mongodb bitnami/mongodb --set architecture=replicaset,replicaCount=2,externalAccess.enabled=true,externalAccess.service.type=LoadBalancer,externalAccess.service.port=27017,externalAccess.autoDiscovery.enabled=true,exte
rnalAccess.service.loadBalancerIPs[0]=a.b.c.d,externalAccess.service.loadBalancerIPs[1]=w.x.y.z,rbac.create=true -n namespace
```

Strange that the same options added to a file (as I listed above) and passed via the `-f` arg didn't work and at the same time didn't show any error message. Any explanation?

**Comment by dani8art** [comment]
Hi when using different cloud providers to install charts we need to adapt them to their specific requirements, in this case, it seems like GKE require a different way to expose services for external access, as we can see [here](https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#step_2b_using_an_ingress)

You can use a regional IP-Address or global one.

- if you decide to use regional, then you can use `LoadBalancer` setting the IPs
- if you decide to use global you need to use `NodePort` service type and create an `Ingress` per each mongodb service to expose externally

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-access-mongo-XX
  annotations:
    kubernetes.io/ingress.global-static-ip-name: YOUR_STATIC_IP_HERE
  labels:
    app.kubernetes.io/instance: my-mongo
spec:
  backend:
    serviceName: my_release_name-mongodb-XX-external
    servicePort: 8080
```

Where you must replace `XX` by the pod number `0`, `1`, etc, `YOUR_STATIC_IP_HERE` by the corresponding static IP and `my_release_name` by the name of the helm release.

**Comment by mnmami** [comment]
Thank a lot @dani8art for the information and guide. I'll go with the dynamically assigned IPs for now, and when needed, I created the Ingress for the static ones as you outlined.

**Comment by madmansn0w** [comment]
> Hi @marcosbc,
> 
> Using `helm template` did return the services, but with _ClusterIP_ as service type, exactly like what I get as a result.
> 
> I, however, got to create the LoadBalance services by passing all the options via the `--set` args to the `helm install` command.
> 
> ```shell
> helm install mongodb bitnami/mongodb --set architecture=replicaset,replicaCount=2,externalAccess.enabled=true,externalAccess.service.type=LoadBalancer,externalAccess.service.port=27017,externalAccess.autoDiscovery.enabled=true,exte
> rnalAccess.service.loadBalancerIPs[0]=a.b.c.d,externalAccess.service.loadBalancerIPs[1]=w.x.y.z,rbac.create=true -n namespace
> ```
> 
> Strange that the same options added to a file (as I listed above) and passed via the `-f` arg didn't work and at the same time didn't show any error message. Any explanation?
> 
> Now in the 2-node repicaset, one starts and one goes into `Init:CrashLoopBackOff` loop with very little hints from the logs/describe.
> 
> `kubectl logs`:
> 
> ```shell
> container "mongodb" in pod "raptor-database-mongodb-0" is waiting to start: PodInitializing
> ```
> 
> `kubectl describe pod`:
> 
> ```shell
> Back-off restarting failed container
> ```
> 
> However, I think this should go to a separate issue.
> 
> **Update:** Problem solved by removing IP address assignment and allowing the chart creating them.
> 
> ```shell
> helm install mongodb bitnami/mongodb --set architecture=replicaset,replicaCount=2,externalAccess.enabled=true,externalAccess.service.type=LoadBalancer,externalAccess.service.port=27017,rbac.create=true -n namespace
> ```
> 
> Now everything works, but I'll eventually need to be able to set the static IP addresses (previously reserved from GCP).

I'm having the same issue with the PodInitializing state for the second of two replicasets. If I increase replicaset to 3, the additional load balancers are never initialized. 

```
> kubectl get svc -o wide
mongodb-0-external         LoadBalancer   10.97.167.63     <pending>     27017:31032/TCP               55s   app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=mongodb,app.kubernetes.io/name=mongodb,statefulset.kubernetes.io/pod-name=mongodb-0
mongodb-1-external         LoadBalancer   10.101.22.245    localhost     27017:32325/TCP               55s   app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=mongodb,app.kubernetes.io/name=mongodb,statefulset.kubernetes.io/pod-name=mongodb-1
mongodb-2-external         LoadBalancer   10.103.24.23     <pending>     27017:31393/TCP               55s   app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=mongodb,app.kubernetes.io/name=mongodb,statefulset.kubernetes.io/pod-name=mongodb-2
```

Any hints on how I can solve this?
