### ISSUE TITLE
[bitnami/contour] Use certs in secret rather that using `contour cert` job

### ISSUE THREAD

**Issue by GrandChaman** [bitnami/charts#3766]
**Which chart**:
The `contour` chart, version `2.1.1`

**Is your feature request related to a problem? Please describe.**
The `contour cert` job doesn't allow for automatic certificate renewal. Allowing to use custom secrets would allow the chart users to use tools like [cert-manager](https://cert-manager.io/) to handle the `mTLS` between `contour` and `envoy`

**Describe the solution you'd like**
Add a field in `values.yml` allowing the chart users to use a secret instead of the `contour cert` job for the `contour` and `envoy` TLS credentials.

**Describe alternatives you've considered**
An alternative would be to mount the secrets as additional volumes and find a way to tell `contour` and `envoy` to use them instead.

**Additional context**
N/A

**Comment by dani8art** [comment]
Hi @GrandChaman thank you so much for the suggestion, I've just created a PR, please, let's move the conversation there.
