### ISSUE TITLE
[bitnami/kube-prometheus] and [bitnami/prometheus-operator:0.15.4] not deploying Prometheus

### ISSUE THREAD

**Issue by skulos** [bitnami/charts#3775]
**Which chart**:
name: kube-prometheus
version: 2.1.1

**Describe the bug**
Not installing.

**To Reproduce**
1. Add repo (added it before)
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```
2. Install
```
$ helm install my-release bitnami/kube-prometheus
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "probeNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "probeSelector" in com.coreos.monitoring.v1.Prometheus.spec]
```

**Expected behavior**
Have the chart deploy the following components to my Kubernetes cluster:

- Prometheus Operator
- Prometheus
- Alertmanager

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.3", GitCommit:"", GitTreeState:"", GoVersion:"go1.15"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.7", GitCommit:"bfb38f707bc4a8edfcd73472ec3d96b500b8b781", GitTreeState:"archive", BuildDate:"2020-09-12T13:44:53Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I deleted my Prometheus release this morning. Wanted to add Scylla scrape endpoints but couldn't get the helm upgrade command to take in the ConfigMap (used an older version of the helm charts that still need ConfigMap before Secrets become the way to add the additional scrapes.) Redeployed my old chart and everything but Prometheus is running. Prometheus seems to not pull and deploy. I expect 3 replicas, of which none are currently in the cluster.

**Comment by marcosbc** [comment]
We recently updated the CRD rules in #3597, and it looks like it could have affected this. In order to fix it, please remove the previous rules like this:

```
$ kubectl delete crd prometheuses.monitoring.coreos.com prometheusrules.monitoring.coreos.com
```

Then re-deploy the chart and it should complete successfully

**Comment by skulos** [comment]
Thank you. Sorry for the late reply.

The config was correct one morning when I checked. Think the chart just needed some time to update. (Or at least, that is my running theory.)

**Comment by Ornias1993** [comment]
@marcosbc I did have the same error though, although my install did continue:
`skipping unknown hook: "crd-install"`

No previous install on said system.

**Comment by javsalgar** [comment]
Hi,

This warning can be safely ignored as it is from the helm2 CRD. If you are using Helm 3, you should see the CRDs in the system. What do you see when executing `kubectl get crds`?

**Comment by Ornias1993** [comment]
@javsalgar I've no issue running or deploying... Just wanted to note the error isn't related to previous installs like previously suggested.
