### ISSUE TITLE
Bitnami Container Solution for InfluxDB (TM) is not working on Azure 

### ISSUE THREAD

**Issue by abarqawi** [bitnami/charts#3776]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**
trying to enable this template on Azure and its failing with **unknown error**
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.influxdb-container

**To Reproduce**
Creating this always fail with unknown error
https://ms.portal.azure.com/#create/bitnami.influxdb-container

![image](https://user-images.githubusercontent.com/16225699/94261713-fc0b3380-ff3a-11ea-9c58-a0003d2d7b7f.png)

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by beltran-rubo** [comment]
Hi @abarqawi 

We were not able to reproduce it, we could subscribe to the container image and see in the repository. Could you please open a ticket in Azure support to check if there is any issue with any quota or limitation?

<img width="511" alt="Screenshot 2020-09-28 at 14 00 07" src="https://user-images.githubusercontent.com/3718440/94430016-88b02e80-0193-11eb-9f19-f908361b89a4.png">
<img width="514" alt="Screenshot 2020-09-28 at 14 01 15" src="https://user-images.githubusercontent.com/3718440/94430023-8a79f200-0193-11eb-916a-eeffe5d82e14.png">

**Comment by abarqawi** [comment]
![image](https://user-images.githubusercontent.com/16225699/94779170-2cd1e980-03cf-11eb-9f8e-160e0e12a4ff.png)
Unfortunately it’s still not running for me.

**Comment by andresbono** [comment]
Hi @abarqawi, did you open the ticket in Azure support? They might have more information about the issue.

Does the error only appear for the _Bitnami Container Solution for InfluxDB (TM)_? To discard if this is specific to Bitnami, did you try with containers from other publishers?

**Comment by abarqawi** [comment]
Hi @andresbono i am from Azure CSS but the problem i dont have insight about failure can you connect me with someone who developed the app or responsible for it

**Comment by andresbono** [comment]
Hi @abarqawi, I'm part of the team who developed that container. The publishing process from the Partner Center seems correct for this container. Do you suggest that we check anything else on our side?

**Comment by abarqawi** [comment]
@andresbono i did repro it seems there is error related to subscription for mine , can you show this error to end user as is ?
because its showing unknown 

![image](https://user-images.githubusercontent.com/16225699/95673213-6fee4280-0baf-11eb-9eb5-1887ddd34fec.png)

**Comment by beltran-rubo** [comment]
Sorry @abarqawi but do not think we can help you with that. Could you please open an Azure request to report that issue? As publisher, we could not reproduce it on our side and we follow the official process from Azure to publish the containers.

**Comment by abarqawi** [comment]
thanks @beltran-rubo i am from Azure support , the idea is to show to customer meaningful error code not unknown 
not sure if this can be handled in the marketplace app definition or not 

as you can see there is error shown in javascript for "subscription is not registered to use microsoft.containerRegistry"

but in azure portal its showing error unknown !

**Comment by beltran-rubo** [comment]
Hi @abarqawi 

As publishers, we do not have control over that error. We only make sure the offer is active in the Marketplace and the container is successfully available for users. 

This specific step is totally owned by the Azure Marketplace so do not think there is anything we can do on our side as the offer is successfully published and we can not reproduce it. Could you please check with the Azure Marketplace team?
