### ISSUE TITLE
[bitnami/airflow] Add creation or existing of using service account in airflow chart

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#3779]
**Which chart**:
airflow (all versions)

**Is your feature request related to a problem? Please describe.**
We want to use kubernetes pod operator in airflow which will require us to attach a service account to airflow with proper roles/role binding.

**Describe the solution you'd like**
A service account name to be provided, if provided use the service account else have a flag createServiceAccount: true will create the service account and add to all deployment/statefulset manifests.

We can manage roles and role binding separately or that also can be included in this chart.

**Describe alternatives you've considered**
Alternative I use today, is to attach the role to default service account that is being used by airflow but I feel it is not secure.

**Comment by FraPazGal** [comment]
Hi @iamsudip,

Thanks for your input, I agree it would be a good addition to our chart. Would you like to contribute with a PR implementing this? We would be happy to review it and add it to our repo. 

As a reference, there is a similar feature in our [nginx-ingress-controller](https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller) chart, just in case you want to take on with the PR.

**Comment by iamsudip** [comment]
Comment to remove stale label.
