### ISSUE TITLE
setup.sh not execute correctly when set the "config:"

### ISSUE THREAD

**Issue by shifeichen** [bitnami/charts#3780]
**Which chart**:
11.2.2

**Describe the bug**

The **values.yaml** has a parameter "config" which can be mount to **/bitnami/kafka/config/server.properties**,
and cover the default config, the content:

```
    controlled.shutdown.enable=true
    listeners=INTERNAL://:9093,CLIENT://:9092
    listener.security.protocol.map=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
    log.dirs=/bitnami/kafka/data
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.flush.interval.messages=10000
    log.flush.interval.ms=1000
    log.retention.hours=168
    log.retention.bytes=1073741824
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connect=kafka-p-fl4fh-zookeeper
    zookeeper.connection.timeout.ms=6000
    group.initial.rebalance.delay.ms=0
    auto.create.topics.enable=true
    default.replication.factor=1
    delete.topic.enable=true
    inter.broker.listener.name=INTERNAL
    log.retention.check.intervals.ms=300000
    message.max.bytes=1000012
```

and the `pod-0` is up, but `pod-1`, `pod-2` can not register to the cluster, but is up too.
i enter to the pod, found the KAFKA_CFG_BROKER_ID=-1, the setup.sh is not executed correctly.
i don't know why.

how can i set extra config to the kafka.  

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by juan131** [comment]
@shifeichen could you please try using the latest version of the chat (**11.8.5**)? I am unable to reproduce the issue with that version.

You just need to update your helm repo running the command below:

```console
$ helm repo update
```
