### ISSUE TITLE
[bitnami/thanos] sd querier configmap is erroneously mounted as a folder

### ISSUE THREAD

**Issue by grassiale** [bitnami/charts#3781]
**Which chart**:
thanos 2.4.1
**Describe the bug**
The service discovery configmap is erroneously mounted as a folder hence causing thanos querier to throw the error:

```
{"caller":"file.go:323","err":"read /conf/servicediscovery.yml: is a directory","level":"error","msg":"Error reading file","path":"/conf/servicediscovery.yml","ts":"2020-09-25T16:02:39.226686213Z"}
```

Adding the line `subPath: servicediscovery.yml` in the volume mounts deployment spec, like this:

```
volumeMounts:
        - mountPath: /conf/servicediscovery.yml
          name: sd-config
          subPath: servicediscovery.yml
```

solves the issue by correctly mounting as file.

**To Reproduce**

Install helm chart and specify some values in sdConfig in the form of 

```
sdConfig: |
  - targets: [something:10901]
```

**Expected behavior**

The configmap should be mounted as a file.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @grassiale 

Thanks so much for opening this issue!! I can confirm that it's mounted as a directory and, therefore, the Querier complains about it. 

Would you open a PR addressing this with the solution you shared, or would you rather us to open it instead?

**Comment by grassiale** [comment]
Hi @juan131 , done : https://github.com/bitnami/charts/pull/3789
