### ISSUE TITLE
[bitnami/mariadb] Warning while writing on /opt/bitnami/mariadb/conf/my.cnf

### ISSUE THREAD

**Issue by sagaraspl** [bitnami/charts#3784]
**Which chart**:
bitnami/mariadb chart and version is 7.10.2

**Describe the bug**
While the container becomes up we are getting following warning in kubernets.
mariadb 12:07:40.70 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.

We are running container as non-root user and security context,
runAsUser: 1001
fsGroup: 1001
runAsGroup: 0

So the 1001 user belongs to group root 0.

Now the permission of file: /opt/bitnami/mariadb/conf/my.cnf is 644, so the permission of file should be 664 instead then only group have write permission.

**Expected behavior**
The container when goes up should be able to write to file /opt/bitnami/mariadb/conf/my.cnf.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.7", GitCommit:"bfb38f707bc4a8edfcd73472ec3d96b500b8b781", GitTreeState:"clean", BuildDate:"2020-08-12T20:27:48Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Running Kubernets on DigitalOcean

**Comment by miguelaeh** [comment]
Hi @sagaraspl ,
I would say that is because the configuration file is mounted as a ConfigMap that is not writable.
The ConfigMap is created using the configuration from the values.yaml. You can see it at https://github.com/bitnami/charts/blob/840d880e5cd52599b73831348172fd187be1f263/bitnami/mariadb/values.yaml#L302

**Comment by sagaraspl** [comment]
Hi @miguelaeh 

Thanks for update. Yes but I don't see a place where I can change the permission of mounted ConfigMap. There is security context but it doesn't helping either.

**Comment by miguelaeh** [comment]
Hi @sagaraspl ,
The ConfigMap cannot be written even if you change the permissions. To modify that configuration you will need to update your values.yaml and perform a Helm upgrade
