### ISSUE TITLE
[bitnami/kafka] Mismatch between values.yaml and the README for pdb.create

### ISSUE THREAD

**Issue by mehta-ankit** [bitnami/charts#3791]
**Which chart**:
Kafka chart, version: 11.8.4

**Describe the bug**
README mentions default value for `pdb.create` is false, but in the values.yaml file it is set to true.
Its not a big deal but it threw me off for a second.

**To Reproduce**
1. Install the chart with default values
2. run `kubectl get pdb` and you'll see Kafka PDB created even though README says it should not be because `pdb.create` is false according to it.
![image](https://user-images.githubusercontent.com/22157398/94427921-dc078a00-015d-11eb-8355-0c5265b5ed3b.png)

**Expected behavior**
I am not 100% sure if we want default to true to create the PDB. So either values.yaml file should change back to false for pdb.create and whoever wants one can overwrite the value. 
Or
README should be updated to say `pdb.create` is `true` by default.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Thanks so much for reporting it @mehta-ankit ! I just created a PR to address this issue
As you said, PDB shouldn't be enabled by default in the **values.yaml**
