### ISSUE TITLE
[bitnami/influxdb] cluster replication

### ISSUE THREAD

**Issue by and-dzh3** [bitnami/charts#3793]
**Which chart**:
bitnami/influxdb

**Describe the bug**
Whats happened in of replica pods is down 

**To Reproduce**
1. If one pod from 3 replicas down (example one node of the cluster was spot and spot gone)
2. relay will send the messages only to available pods 
3. after the third replica pod will be recreated again, data for this period of time when pod was offline will be missed?

**Expected behavior**
Any replication between the pods, If no what is the meaning of production cluster ??

**Comment by andresbono** [comment]
Hi @and-dzh3, when you use the `values-production.yaml`, a series of high-availability features are enabled in addition to the basic features of the `values.yaml`. Read more on this here: https://github.com/bitnami/charts/tree/master/bitnami/influxdb#production-configuration-and-horizontal-scaling.

To have some level of high availability, [InfluxDB Relay (TM)](https://github.com/influxdata/influxdb-relay) is used. The documentation of the service has a section on [Recovery](https://github.com/influxdata/influxdb-relay#recovery) that you may find useful.

**Comment by and-dzh3** [comment]
@andresbono thanks for your answer
