### ISSUE TITLE
[bitnami/mariadb] existingSecret value is ignored

### ISSUE THREAD

**Issue by hamid-elaosta** [bitnami/charts#3794]
**Which chart**:
bitnami/mariadb 7.10.1

**Describe the bug**
If existingSecret is set, the chart is aware that it needs to use an existing secret, but it fails deployment unless the secret name is "mariadb".

**To Reproduce**
1. set `existingSecret` to a value other than "mariadb", e.g. "mariadb-secrets"
2. Deploy chart
3. NOTES.txt shows "mariadb-secrets" under Administrative Credentials
4. Pods fail to deploy because secret named "mariadb" does not exist.

**Expected behavior**
Pods should use the name provided to `existingSecret` as shown and templated into NOTES.txt and not be hardcoded to use "mariadb".

**Version of Helm and Kubernetes**:
Helm v3.3.4
Kubernetes v1.18.8

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
If I create my secret with the name "mariadb" the chart deploys as expected.

**Comment by miguelaeh** [comment]
Hi @hamid-elaosta ,
Thank you very much for reporting this issue.
The above PR should fix it, please take a look when you have the chance.
Regards.

**Comment by hamid-elaosta** [comment]
Hi @miguelaeh Thanks for looking at that so quickly. I have applied the patch locally and confirmed that it is working.

**Comment by miguelaeh** [comment]
Thanks for the confirmation @hamid-elaosta !!
