### ISSUE TITLE
[bitnami/influxdb] metrics and monitoring 

### ISSUE THREAD

**Issue by and-dzh3** [bitnami/charts#3795]
**Which chart**:
[bitnami/influxdb]

**Is your feature request related to a problem? Please describe.**
In each pod of influxdb exists  _internal db with metrics but ,
if I want to visualize them in grafana the data will be showing only from a specific pod  (in each grafana page refresh data will be changed depends on what pod it's connected via ingress).

and also metrics and service monitor enabled  but the data is not informative (Standart Prometheus metrics )
```
...
process_virtual_memory_max_bytes -1
promhttp_metric_handler_requests_in_flight 1
promhttp_metric_handler_requests_total{code="200"} 48935
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
....
```
**Describe the solution you'd like**
Can someone share how to collect, monitor, and visualize the metrics
or  maybe grafana dashboard json

**Comment by dani8art** [comment]
Hi @and-dzh3 thanks for opening this issue.

- How are you installing this chart? can you share the steps/commands you followed?

- How are you installing Prometheus/Grafana? are you using prometheus-operator or just prometheus?

**Comment by dani8art** [comment]
We have tried to reproduce using `bitnami/kube-prometheus` chart and seems to be working fine:

```console
$ helm install --wait -n monitoring prom bitnami/kube-prometheus
```

```console
$ helm upgrade --install influxdb bitnami/influxdb \
  --set architecture=high-availability \
  --set influxdb.replicaCount=3 \
  --set adminUser.pwd=my-pass \
  --set metrics.enabled=true \
  --set metrics.serviceMonitor.enabled=true
```

```console
$ kubectl port-forward -n monitoring svc/prom-kube-prometheus-prometheus 9090:9090
```
![Screenshot 2020-09-29 at 11 49 58](https://user-images.githubusercontent.com/4376304/94543145-f5860000-0249-11eb-9b29-4c19ed5f7db9.png)

**Comment by and-dzh3** [comment]
@dani8art 
I have the same setup with prom operator and I have these metrics, 
But only these metrics are available (status code ) ?

**Comment by dani8art** [comment]
You can query like `{job="influxdb"}` to see all the metrics or also 

```console
$ k port-forward influxdb-0 8086:8086
```

and go to http://127.0.0.1:8086/metrics

**Comment by and-dzh3** [comment]
@dani8art  tnq , maybe you have some dashboard JSON  for grafana ?

**Comment by dani8art** [comment]
You can try to find some useful dashboard in their official web page https://grafana.com/grafana/dashboards?search=influxdb%20internal

**Comment by and-dzh3** [comment]
Thanks, additionally, I found some other solution...
in each pod of influx you have _internal db with metrics.
so I connected each pod from the replica as the data store to grafana and build a dashboard based on internal influx metrics
