### ISSUE TITLE
[wordpress] MariaDB is not work as high availability

### ISSUE THREAD

**Issue by emreberber** [bitnami/charts#3796]
**Which chart**:
Chart : Wordpress

**Describe the bug**
I install wordpress helm chart with values-production.yaml. It's create MariaDB, one master and two slave pod. But if i shutting down the master pod, wordpress is fail. Database not pass to slave pods and the application give 502. This case is not available for production environment beacuse not high availabity. Does anyone have any suggestions for solution

Thanks.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by FraPazGal** [comment]
Hi @emreberber, 

Installing the chart with `values-production.yaml` will create 3 wordpress pods and a single mariadb pod. If I understood correctly, you are also enabling `mariadb.replication=true`, which will also create a mariadb-slave pod right? 

Although it's true that it creates a replication cluster, it only has 1 master, so if you remove the `mariadb-master` pod, you will indeed not be able to access your database. The database that we include in this chart is a simple one and we understand that users may need a more secure database for production environment, that is why you can attach an external database. You can find more information in the chart's [README.md](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#using-an-external-database)

**Comment by emreberber** [comment]
Thanks for your feedback and advice. @FraPazGal
