### ISSUE TITLE
[bitnami/postgresql] version 9.7.3 is not published in index.yaml

### ISSUE THREAD

**Issue by techknowlogick** [bitnami/charts#3801]
**Which chart**:
bitnami/postgresql version 9.7.3

**Describe the bug**
When referencing bitnami/postgresql v9.7.3 as a helm dep it will fail to import.

**To Reproduce**
Set bitnami/postgresql chart as a dependency of a chart and use version 9.7.3, when running `helm dependency update` the command will fail because `Error: could not find : chart postgresql not found in https://charts.bitnami.com/bitnami`. This is due to version 9.7.3 not being found in the index.yaml

you can verify this by running:
```
curl https://charts.bitnami.com/bitnami/index.yaml | grep -A5 postgresql | grep 9.7
```
and you will see 9.7.2, but 9.7.3 is missing.

**Expected behavior**
Dependency is  referenced.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
``

**Comment by marcosbc** [comment]
Hi @techknowlogick, version 9.7.3 has not been published yet and it's in process of being released in our pipeline, however we're finding some issues. We've just sent #3808 to ensure it will appear in our pipeline shortly.

In the meantime, you should be able to use 9.7.2 without any problems.

**Comment by techknowlogick** [comment]
Thanks :) Will close this now.
