### ISSUE TITLE
cephfs mount can not read write 

### ISSUE THREAD

**Issue by reckless-huang** [bitnami/charts#3814]
**Which chart**:
redis-cluster-3.2.5

**Describe the bug**
cephfs as pv in pod , it doesn`t work ,logs /opt/bitnami/scripts/librediscluster.sh: line 189: /bitnami/redis/data/nodes.sh: Permission denied on evert pod 

**To Reproduce**

**Expected behavior**
i want install a redis cluster on my k8s ,when  i start it by helm ,everythiing look good , but only one minute every pod go to error and logs  /opt/bitnami/scripts/librediscluster.sh: line 189: /bitnami/redis/data/nodes.sh: Permission denied on evert pod .
mount pv with admin and not readonly ,i  just  requesy help and thanks a lot , Look forward to your favourable reply
**Version of Helm and Kubernetes**:

- Output of `helm version`:
v2.16.11

- Output of `kubectl version`:
1.19.2
**Additional context**

**Comment by reckless-huang** [comment]
Look forward to your favourable reply

**Comment by andresbono** [comment]
Hi @reckless-huang, you say that the pod is up for some time, are you able to check the permissions and ownership of the volume directory? You can exec into the pod and execute `ls -la /bitnami/redis/data` before the pod is restarted.

There are cases in which the permissions of the volume need to be adjusted. You may want to try the `volumePermissions.enabled=true` parameter. See https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#common-parameters

**Comment by reckless-huang** [comment]
> Hi @reckless-huang, you say that the pod is up for some time, are you able to check the permissions and ownership of the volume directory? You can exec into the pod and execute `ls -la /bitnami/redis/data` before the pod is restarted.
> 
> There are cases in which the permissions of the volume need to be adjusted. You may want to try the `volumePermissions.enabled=true` parameter. See https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#common-parameters

Thanks alot  ，its fix my problem
