### ISSUE TITLE
annotation is injectable in node-exporter

### ISSUE THREAD

**Issue by aldrineeinsteen** [bitnami/charts#3815]
**Which chart**:
helm.sh/chart=node-exporter-1.1.2

**Describe the bug**
When setting annotations for prometheus.io\port below is the error reported:
_Error: UPGRADE FAILED: YAML parse error on node-exporter/templates/service.yaml: error converting YAML to JSON: yaml: line 6: did not find expected key_

**To Reproduce**
1. install node-exporter using helm install (regular progress)
2. update the node-exporter using --set 
```
helm upgrade node-exporter bitnami/node-exporter --namespace ns \
   --set service.annotations."prometheus\.io/port"=9100 \
   --dry-run
```
3. See error

**Expected behavior**
The added annotation should be added onto the service accordingly

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
a
```

**Additional context**

![image](https://user-images.githubusercontent.com/4903148/94588588-b8e5f300-02a1-11eb-8f16-fea503893dce.png)

**Comment by miguelaeh** [comment]
Hi @aldrineeinsteen ,
The above PR should fix the issue. Could you give a try?

**Comment by aldrineeinsteen** [comment]
@miguelaeh got hospitalised due to a major accident... Sorry couldn't reach out on time. I just tried out the setup. It works 👍

**Comment by miguelaeh** [comment]
Thanks for the confirmation!
Regards.
