### ISSUE TITLE
[bitnami/postgresql] How to set namespace for the postgres pods?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [bitnami/charts#3818]
Is there any configuration possible to set the namespace of the postgres pods?
I couldn't find anything in the docs, except the network policy (which is probably not exactly what I'm referring to)?

If this is not implemented, could you implement it somehow?

**Comment by juan131** [comment]
Hi @h0jeZvgoxFepBQ2C 

I am not sure if this is what you're looking for, but you can simply use the `--namespace` flag when installing the PostgreSQL chart to choose the namespace where to deploy PostgreSQL pods. For instance, to install them on the namespace 'FOO':

```console
helm install my-release bitnami/postgresql --namespace FOO
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Sorry, I should have been more clear: 

We are using postgresql as a dependency for our own helm chart, so there is no explicit called command line call, where I can set the namespace.
We would like to generate the namespace name dynamically, so that each postgres server is hosted in the desired namespace? (hope I'm not writing nonsense, we are absolute beginners on kubernetes :))

**Comment by juan131** [comment]
Hi @h0jeZvgoxFepBQ2C 

If you are using it as dependency of your own chart, it works exactly the same way. I meant the `--namespace` flag will affect the PostgreSQL manifests in the same way.

So.. if you have a chart called "foo" (using `bitnami/postgresql` as dependency) and you want to install it in the namespace "bar":

```console
$ kubectl create namespace bar
$ helm install my-release foo --namespace bar
```
