### ISSUE TITLE
[bitnami/wordpress] Whenever wordpress deployment restarts due to an error, it reverts back to original version

### ISSUE THREAD

**Issue by Msarnaot** [bitnami/charts#3821]
**Which chart**:
Wordpress

**Describe the bug**
Periodically, we have to upgrade wordpress to the latest release. However we noticed that whenever the pod restarts for whatever reason, our wordpress deployment reverts back to the version with which we deployed. We first deployed wordpress about a year ago. So it reverts back to the version of wordpress from back then. Can you please recommend how to persist this setting?

**Comment by andresbono** [comment]
Hi @Msarnaot, thanks for opening this issue. Could you tell us what is the process that you follow to upgrade WordPress?
