### ISSUE TITLE
[bitnami/mariadb-galera] existingSecret is not honoured  

### ISSUE THREAD

**Issue by hamid-elaosta** [bitnami/charts#3825]
**Which chart**:
bitnami/mariadb-galera 4.4.1

**Describe the bug**
If `existingSecret` is set, the deployment fails at the value validation because the passwords have not been set directly.
```
helm install mariadb -f values-production.yaml bitnami/mariadb-galera
Error: template: mariadb-galera/templates/NOTES.txt:62:3: executing "mariadb-galera/templates/NOTES.txt" at <include "mariadb-galera.validateValues" .>: error calling include: template: mariadb-galera/templates/_helpers.tpl:187:51: executing "mariadb-galera.validateValues" at <fail>: error calling fail: 
VALUES VALIDATION:
mariadb-galera: rootUser.password
    A MariaDB Database Root Password is required ("rootUser.forcePassword=true" is set)
    Please set a password (--set rootUser.password="xxxx")
mariadb-galera: db.password
    A MariaDB Database Password is required ("db.forcePassword=true" is set)
    Please set a password (--set db.password="xxxx")
mariadb-galera: galera.mariabackup.password
    A MariaBackup Password is required ("galera.mariabackup.forcePassword=true" is set)
    Please set a password (--set galera.mariabackup.password="xxxx")

```
Additionally, the README.md does not document the data values to be used in the `existingSecret`, while the `bitnami/mariadb` README.md does next to `existingSecret`.

I believe these values to be `mariadb-root-password`, `mariadb-galera-mariabackup-password` and `mariadb-password.

**To Reproduce**
1. Start with `values-production.yaml` uncomment `existingSecret`
2. Set a value for `existingSecret` e.g. mariadbgalerasecrets
3. Create a secret with the data values listed above, and name it the same as the value set for `existingSecret`
4. Do NOT set password values in `values-production.yaml`
4. Deploy bitnami/mariadb-galera using modified the `values-production.yaml`
5. Validation error occurs

**Expected behavior**
Chart should deploy using secrets from `existingSecret`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by dani8art** [comment]
Hi @hamid-elaosta thank you for the feedback!!

You can workaround this issue by adding:

```console
--set rootUser.forcePassword=false,db.forcePassword=false,galera.mariabackup.forcePassword=false
```

However, I think you are completely right and if `existingSecret` is set, theses validations should not be taken into account. I've just opened a PR (#3844) to fix that and add the required data in the `existingSecret` to the README.md, please let's move the conversation there.
