### ISSUE TITLE
[bitnami/mongodb-sharded] existingSecret

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#3826]
**Which chart**:
mongodb-sharded latest

**Describe the bug**
existingSecret doesn't work

**To Reproduce**
https://github.com/bitnami/charts/blob/e34db5356eece19e957c7d6b3de4c2c26a559e08/bitnami/mongodb-sharded/templates/_helpers.tpl#L99-L105

I think it should be like this according to other chart
```
 {{- printf "%s" .Values.existingSecret -}}
```

**Comment by maxisam** [comment]
ah... I just typed exactly the same command you typed. It doesn't work. 

It generated another set of secret.


![image](https://user-images.githubusercontent.com/456807/94831907-e41c2f80-03d2-11eb-9b37-d09166e3c362.png)


I did helm repo update before I tried.

![image](https://user-images.githubusercontent.com/456807/94832096-1b8adc00-03d3-11eb-9d67-eab9c7199611.png)

**Comment by FraPazGal** [comment]
Hi @maxisam,

Yes, the `mongo-mongodb-sharded` secret is expected to be created but if its been successfully deployed with `existingSecret=secret-mongo`, the chart should be taking the passwords from our custom secret. 

If it isn't using our new secret you should be able to access mongo with the default password. Using my third command, can you connect using the `$MONGODB_ROOT_PASSWORD` variable like this:

```
kubectl port-forward --namespace default svc/mongo-mongodb-sharded 27017:27017 & mongo --host 127.0.0.1 -u root -p $MONGODB_ROOT_PASSWORD
```

**Comment by maxisam** [comment]
![image](https://user-images.githubusercontent.com/456807/94937637-74bb4400-0495-11eb-8e84-7336dabbc6c3.png)

It doesn't work.

**Comment by FraPazGal** [comment]
Hi @maxisam,

From what I see in your screenshot, your mongodb-sharded chart should be using your new password, could you try my command `Connect to database` in one of my previous replays?

Maybe the confusion stems from the fact that the secret `mongo-mongodb-sharded` is created regardless of whether is used or not, and the same happens with the message in the notes to obtain the password. That message always tells you to obtain `$MONGODB_ROOT_PASSWORD` using the `mongo-mongodb-sharded` secret, even when the password is obtained from an existing secret.

Now that I think about it, we should at least change the notes's message for it to use the new created secret to avoid confusion.

**Comment by maxisam** [comment]
I see. It does work. What a big misunderstanding. thx!

**Comment by dani8art** [comment]
Hi @maxisam, thank you so much for your feedback, I've recently created a PR that will avoid creating unnecessary secrets. Please, let's move the conversation there.
