### ISSUE TITLE
Can't get services to start

### ISSUE THREAD

**Issue by FTWJAY** [bitnami/charts#3827]
**Which chart**:
The name (and version) of the affected chart
all
**Describe the bug**
I can't get services to start. ruby on rals on windows 10 machine. I click on start services and a window blinks on but that's it., no services start and nothing works.
**To Reproduce**

**Expected behavior**
A window to open to control the services
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Please note that this is for Bitnami charts. For our Windows installers please open a ticket in community.bitnami.com.
