### ISSUE TITLE
[bitnami/nginx] cloneStaticSiteFromGit no template found

### ISSUE THREAD

**Issue by Daxcor69** [bitnami/charts#3829]
**Which chart**:
Nginx 7.1.1

**Describe the bug**
Dry run errors out when specifying cloneStaticSiteFromGit: functionality.  The Helm chart works just fine with out this being enabled.

**To Reproduce**
`helm install test-nginx -f /home/brad/foundry-v2/website/website/values.yaml bitnami/nginx --dry-run --debug`

**Expected behavior**
Wanting the nginx helm to pull form the existing repo and install website content.

**Version of Helm and Kubernetes**:

Kube
Client Version: v1.18.8
Server Version: v1.18.8

Helm
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

**Additional context**

- Output of 
`helm install test-nginx -f /home/brad/foundry-v2/website/website/values.yaml bitnami/nginx --dry-run --debug`

```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/brad/.cache/helm/repository/nginx-7.1.1.tgz

Error: template: nginx/templates/deployment.yaml:69:20: executing "nginx/templates/deployment.yaml" at <include "cloneStaticSiteFromGit.image" .>: error calling include: template: no template "cloneStaticSiteFromGit.image" associated with template "gotpl"
helm.go:94: [debug] template: nginx/templates/deployment.yaml:69:20: executing "nginx/templates/deployment.yaml" at <include "cloneStaticSiteFromGit.image" .>: error calling include: template: no template "cloneStaticSiteFromGit.image" associated with template "gotpl"
```

Relevant section of values.yaml.

```
cloneStaticSiteFromGit:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.28.0-debian-10-r57
    pullPolicy: IfNotPresent
  repository: https://gitlab.com/bradley8/website-v2.git
  branch: master
  interval: 60
```

**Comment by marcosbc** [comment]
Hi @Daxcor69, thanks for reporting. I could reproduce it and found the issue to be this:

```lang=diff
diff --git a/bitnami/nginx/templates/deployment.yaml b/bitnami/nginx/templates/deployment.yaml
index a2ae4a316..65c1e0cbc 100644
--- a/bitnami/nginx/templates/deployment.yaml
+++ b/bitnami/nginx/templates/deployment.yaml
@@ -66,7 +66,7 @@ spec:
               mountPath: /app
       containers:
         - name: git-repo-syncer
-          image: {{ include "cloneStaticSiteFromGit.image" . }}
+          image: {{ include "nginx.cloneStaticSiteFromGit.image" . }}
           imagePullPolicy: {{ .Values.cloneStaticSiteFromGit.image.pullPolicy | quote }}
           command:
             - /bin/bash
```

I've sent a PR (#3854) and expect to have it merged today. After that, our pipeline will automatically trigger a release of the NGINX chart so expect it to be available later today or early tomorrow (if everything goes correctly).
