### ISSUE TITLE
[bitnami/metrics-server] Support configuring service labels

### ISSUE THREAD

**Issue by michelzanini** [bitnami/charts#3840]
**Which chart**:
bitnami/metrics-server = 4.3.2

**Is your feature request related to a problem? Please describe.**
The stable chart allows changing the the labels of a service with `service.labels` but the Bitnami does not, making the transition harder.

**Describe the solution you'd like**
To allow `service.labels` to be configured via `values.yaml`.

**Comment by andresbono** [comment]
Hi @michelzanini, we are open to add this feature. In fact, other charts already support it. Would you like to open a PR addressing the changes? Contributions are more than welcome!

You can follow the same approach than in `bitnami/nginx-ingress-controller`:

https://github.com/bitnami/charts/blob/e33e65a275f53681405d098c332f1b31e3432c30/bitnami/nginx-ingress-controller/templates/controller-service.yaml#L8-L10

**Comment by michelzanini** [comment]
I friend of mine created the PR there for this. Thanks!

**Comment by andresbono** [comment]
The PR is now merged. Thanks for the contribution!
