### ISSUE TITLE
Dynamically fetching Redis Password using CSI driver 

### ISSUE THREAD

**Issue by Dinesh558** [bitnami/charts#3855]
**Which chart**:
The name (and version) of the affected chart.
Redis

**Is your feature request related to a problem? Please describe.**
Currently we need to pass the redis password via parameters or file, is it possible to integrate with Azure key vault or HashiCorp Vault using CSI driver

https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes#install-helm-and-the-secrets-store-csi-driver

**Comment by FraPazGal** [comment]
Hi @Dinesh558,

Reading the azure documentation, I understand that this solution mounts the secrets stored in the vault as a folder inside the pod, is that right? If that is the case, wouldn't it be possible to retrieve the password from that mounted folder?

If it is of help, our redis chart also support passing the redis password using a secret with the options `existingSecret` and `existingSecretPasswordKey`.

**Comment by akshayinamdarbjp** [comment]
Hi FraPazGal, 

Currently we use AWS secrets manager, is there any way to integrate that? Even if we want to store it in secrets manager, this chart encodes and stores it in K8s secrets and retrieved whenever new pod is scheduled. We thought of providing password during deployment and delete the K8s secret later one. But it affects the deployment of new pods when one is killed.

**Comment by FraPazGal** [comment]
Hi @akshayinamdarbjp!

This a known limitation of mongodb, as explained in their [documentation](https://docs.mongodb.com/manual/core/replica-set-rollbacks/#rollback-elapsed-time-limitations). You would need to pass the flag `rollbackTimeLimitSecs` to the image to increase the default time limit. You can set new flags using the chart's `extraFlags` parameter.

**Comment by FraPazGal** [comment]
Hi @akshayinamdarbjp!

Unfortunately, there is no ready-to-go parameters for implementing AWS secrets manager in this chart. Should you need it, please open a new issue to discuss the necessary changes or additions needed in the chart for it to work with AWS secrets manager.
