### ISSUE TITLE
Can´t install redis chart in numeric namespace

### ISSUE THREAD

**Issue by rmtedi** [bitnami/charts#3856]
**Which chart**:
The name (and version) of the affected chart
Redis 
**Describe the bug**
I get error when try install redis in namespace with name is numeric
**To Reproduce**
helm install rmt-redis bitnami/redis -n '9991103'
**Expected behavior**
Redis installed
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```
helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}

- Output of `kubectl version`:

```
(paste your output here)
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
Output error:
Error: unable to build kubernetes objects from release manifest: [unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103},"t|..., bigger context ...|redis"},"name":"backendcanais-redis","namespace":9991103},"type":"Opaque"}|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103}}|..., bigger context ...|"name":"backendcanais-redis-scripts","namespace":9991103}}|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103}}|..., bigger context ...|redis"},"name":"backendcanais-redis","namespace":9991103}}|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103}}|..., bigger context ...|,"name":"backendcanais-redis-health","namespace":9991103}}|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103},"s|..., bigger context ...|name":"backendcanais-redis-headless","namespace":9991103},"spec":{"clusterIP":"None","ports":[{"name|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103},"s|..., bigger context ...|,"name":"backendcanais-redis-master","namespace":9991103},"spec":{"ports":[{"name":"redis","port":63|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103},"s|..., bigger context ...|},"name":"backendcanais-redis-slave","namespace":9991103},"spec":{"ports":[{"name":"redis","port":63|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103},"s|..., bigger context ...|,"name":"backendcanais-redis-master","namespace":9991103},"spec":{"selector":{"matchLabels":{"app":"|..., unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":9991103},"s|..., bigger context ...|},"name":"backendcanais-redis-slave","namespace":9991103},"spec":{"replicas":2,"selector":{"matchLab|...]

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. I believe the issue would be solved by changing:

```
  namespace: {{ .Release.Namespace }}

```

With 

```
  namespace: {{ .Release.Namespace | quote }}
```

We will work on that, but as it is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, feel free to open a PR and we will review it.

**Comment by javsalgar** [comment]
Hi,

I created this PR for fixing it. Please take a look https://github.com/bitnami/charts/pull/4094
