### ISSUE TITLE
Issues in running harbor with restricted psp

### ISSUE THREAD

**Issue by tvvignesh** [bitnami/charts#3857]
**Which chart**:
harbor

**Describe the bug**
Unable to run the chart with restricted psp: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml

If I set volumepermissions to false and run it, permission to create /bitnami is denied in the postgres and if I set the volumepermission to true then init containers try to run with id 0 which is not permitted as per the restricted psp.

This happens not just in the db deployment but in many deployments within the harbor chart. Any reference on how we can go about it? Thanks.

**PS:** I tried with both harbor-helm and bitnami helm chart and both has issues with this. Raised an issue in the harbor-helm repo as well: https://github.com/goharbor/harbor-helm/issues/756

**Comment by juan131** [comment]
Hi @tvvignesh 

You have two alternatives for setting the right permissions in the volume attached to PosgreSQL pods:

- Option A) Use the init container to adapt them. As you said, this is incompatible the policy "MustRunAsNonRoot"
- Option B) Use the securityContext so K8s provisions volumes with the "fsGroup" already adapted. To use this option, you K8s cluster should be able to provide dynamically PVs that support this feature (learn more at https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods)

**Comment by tvvignesh** [comment]
@juan131 Thanks. Hadn't tried option B. Will try it and see if it works.

**Comment by snailxr** [comment]
When I try Option B add fsGroup, but the initContainer still starts failed

`chmod: changing permissions of '/dev/shm': Operation not permitted`
