### ISSUE TITLE
Bitnami opencart helm chart CSS and PHP issue

### ISSUE THREAD

**Issue by Nikhils09** [bitnami/charts#3858]
**Which chart**:
Bitnami/opencart

**Describe the bug**
I have deoloyed opencart on my Kubernetes cluster (v1.18) but it's not loading css properly as well as only homepage is loading, other pages shows php error

**Comment by marcosbc** [comment]
@Nikhils09 Could you make sure that you are setting the proper value to the `opencartHost` option? Could you also share more details on how you deployed your solution?

Finally, it would be really useful to know what is happening. Please open your browser (Chrome or Firefox) and open the developer console, go to the Network tab and reload to see what is happening with all requests. What do you see happening?

**Comment by Nikhils09** [comment]
Hi @marcosbc, thanks, I have configured OpencartHost and it's working fine now.
