### ISSUE TITLE
Influxdb not starting chown: missing operand after

### ISSUE THREAD

**Issue by YunaBraska** [bitnami/charts#3863]
**Which chart**:
Bitnami 0.6.7

**Describe the bug**
The influxDB pod is not starting cause of `chown: missing operand after '0:0'`
Since the fix on https://github.com/bitnami/charts/pull/2417 the new `find` command is broken and returns an empty string instead of the directories cause of `-mindepth 1` needs to be `-mindepth 0`

**To Reproduce**
1) setting `volumePermissions.enabled` to `true`
2) `helm template` && `kubectl apply`

**Expected behavior**
The `find` command should find the folders to pass it to the `xargs chown` command.
Pod should start up

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
2.16.5
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Since implementation of: https://github.com/bitnami/charts/pull/2417

**Comment by andresbono** [comment]
Hi @YunaBraska, thanks for reporting this issue!

I could reproduce it with:

```console
$ helm install influxdb bitnami/influxdb --version 0.6.8 --set volumePermissions.enabled=true
$ kubectl logs influxdb-87db4fcb5-wv7f6 -c init-chmod-data
chown: missing operand after '1001:1001'
Try 'chown --help' for more information.
```

Would you like to open a PR addressing the change? Contributions are more than welcome!

**Comment by YunaBraska** [comment]
@andresbono sure - here you go: https://github.com/bitnami/charts/pull/3903

**Comment by andresbono** [comment]
Thanks so much! 🎉  The PR will be reviewed and merged soon.
