### ISSUE TITLE
Zookeeper namespace override

### ISSUE THREAD

**Issue by danielburrell** [bitnami/charts#3864]
**Which chart**:
The name (and version) of the affected chart.
zookeeper current.

**Is your feature request related to a problem? Please describe.**

Our Chart architecture:

`Our application chart -> Stardog chart -> zookeeper chart`.

This shows that Zookeeper is a dependency of stardog, which is a dependency of own application chart. 

We currently deploy our application using `helm install --namespace somenamespace`. As a result of zookeeper's chart using `{{.Release.Namespace}}` zookeeper is deployed to the same namespace. We really benefit from the way helm allows us to declare dependent charts, however we need to be able to place zookeeper in a separate namespace. We're currently able to customize the stardog namespace, but it's currently not possible with zookeeper.

**Describe the solution you'd like**
We would like the zookeeper chart to be modified such that the `{{.Release.Namespace}}` continues to be used as a default, but it is additionally possible to specify a .Values.namespace override. This would be used by our application's `Values.yaml` by setting `zookeeper.namespace` or some similar variable name. This would allow zookeeper to be deployed at the same time as our application but in a different namespace.

**Describe alternatives you've considered**
- We have considered deploying zookeeper as a separate piece of infrastructure with it's own helm install release process in order to allow its own namespace to be defined, but this is undesirable as it adds to the complexity of the release process. As zookeeper is a dependency of our dependency, we would like to distance ourselves from the implementation details of those dependencies in terms of what needs to be deployed. We feel that since helm is designed to provide flexibility to kubernetes manifests, that namespaces are probably a good thing to allow customization for.
- We have also considered forking the chart, but again, we'd rather not do this as we believe in re-use where possible and the additional overhead of keeping the fork up to date would be undesirable.

**Additional context**
This is the chart that actually uses zookeeper (although it doesn't use bitnami currently there is a ticket open to migrate, bitnami being a likely candidate). https://github.com/stardog-union/helm-charts/issues/30 This chart had the same problem around namespace customization, we made a similar request to them and they were happy to make the change (change is still being implemented), but pointed out to us that zookeeper as a dependency would need the same change.

I understand development time is precious, so I'm happy to provide a pull request with the appropriate changes if you confirm that such a feature would be accepted in principle.

**Comment by miguelaeh** [comment]
Hi,
Thank you very much for the explanation of the issue and the PR. We are already taking care of the PR!
Regards.
