### ISSUE TITLE
Add Contour support for Harbor Ingress Controller

### ISSUE THREAD

**Issue by doddatpivotal** [bitnami/charts#3879]
**Which chart**:
Harbor

**Is your feature request related to a problem? Please describe.**
As a VMware Tanzu customer I have entitlement to contour and harbor.  I would like to use contour as the ingress controller for Harbor.

**Comment by andresbono** [comment]
Hi @doddatpivotal, thanks for opening this issue. Could you tell us what have you tried so far to set it up and what are the problems that you are finding?

**Comment by doddatpivotal** [comment]
I found this when reading the readme.

```
ingress.controller | The ingress controller type. Currently supports default, gce and ncp | default
```

I interpreted this as if my ingress controller was not on the list, then it wouldn't work.

**Comment by andresbono** [comment]
Hi @doddatpivotal, the default value `default` should be fine for compatibility with `bitnami/contour`. We did a quick test and we could deploy Contour and Harbor with success:

- Execute the following commands:

```console
$ helm install contour bitnami/contour
$ helm install harbor bitnami/harbor --set service.type=Ingress --set ingress.enabled=true
```

- Go to https://core.harbor.domain after modifying /etc/hosts to point to the contour-envoy LoadBalancer external IP.

Let us know if you find any issues.
