### ISSUE TITLE
Custom opencart templates using Bitnami opencart dockerfile

### ISSUE THREAD

**Issue by Nikhils09** [bitnami/charts#3880]
**Which chart**:
Bitnami Opencart

**Describe the bug**
I'm working on creating custom image using bitnami opencart as base image, I have copied my opencart theme file in /opt/bitnami/opencart directory, but still it's loading default opencart site, somehow I have missed some configuration, can you please explain how can we run our custom opencart site using bitnami opencart Docker and helm?

**Comment by miguelaeh** [comment]
Hi,
You can see how to do it at https://forum.opencart.com/viewtopic.php?t=187122
Have in mind the install dir is `/opt/bitnami/opencart`
