### ISSUE TITLE
[wordpress] If root password for mariadb isn't set, your chart WILL fail

### ISSUE THREAD

**Issue by chrisDeFouRire** [bitnami/charts#3884]
**Which chart**:
wordpress

**Describe the bug**
Install the chart, leave mariadb root password chosen at random... Upgrade, restart servers, and see your mariadb fail to start after that.

Also, nothing shows in the logs...

```
mariadb 08:35:05.43 INFO  ==> Using persisted data
mariadb 08:35:05.73 INFO  ==> Running mysql_upgrade
mariadb 08:35:05.81 INFO  ==> Starting mariadb in background
mariadb 08:35:07.97 INFO  ==> Stopping mariadb
```
is all you've got.

**To Reproduce**
Not sure what kind of upgrade caused it all to fail... but when it happens, it's too late: nothing can be salvaged.

**Expected behavior**
Not setting the root password should not break everything.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I lost a production database and wordpress to this bug.

I think it is critical to state clearly that a root password must absolutely be set for this chart to work properly.

**Comment by mbabauer** [comment]
@chrisDeFouRire  I am having the same issue, I think, but setting the root password doesn't seem to help at all.  Are you setting it via mariadb.rootUser.password?  I have tried 2 different charts, Phacility and Redmine, and both seem to have this issue despite setting the root password.

**Comment by chrisDeFouRire** [comment]
I've had more luck with mariadb.rootUser.password, so mariadb isn't broken anymore... I can connect as root easily, it's working.

But Now it's wordpress that can't connect to mariadb 👎  I can't figure out why (after an upgrade + reboot). 
The user and password for wordpress are correct, yet it won't connect to mariadb.

I'm seriously afraid to host Wordpress myself at this point...

**Comment by marcosbc** [comment]
Hi @chrisDeFouRire @mbabauer, right after you deploy the WordPress chart you should get and store the credentials that are generated for you. Unfortunately it looks like the MariaDB sub-chart NOTES are not rendered so it does not mention anything about it.

If you install with `--render-subchart-notes` then you should see the command to execute to obtain the passwords:

```
Administrator credentials:

  Username: root
  Password : $(kubectl get secret --namespace default mywordpress-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)

...

To upgrade this helm chart:

  1. Obtain the password as described on the 'Administrator credentials' section and set the 'rootUser.password' parameter as shown below:

      ROOT_PASSWORD=$(kubectl get secret --namespace default mywordpress-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
      helm upgrade mywordpress bitnami/mariadb --set rootUser.password=$ROOT_PASSWORD
```

To upgrade the WordPress chart, you should obtain the MariaDB credentials, WordPress MariaDB db connection credentials, and WordPress credentials, corresponding with these values:

* mariadb.db.password
* mariadb.rootUser.password
* wordpressPassword

My recommendations, to make things simpler for you, is to specify all these during deployment instead of relying on random values.

**Comment by tailtwo** [comment]
I just had the same issue with Nextcloud, I set the `mariadb.db.password` in the values.yaml but not the root password. Now mariabdb pod wont come up after an upgrade because the root password got replaced. This is unacceptable and very misleading.

**Comment by andresbono** [comment]
Hi @tailtwo, just to let you know, Nextcloud is not part of our Chart catalog.

We are in the process of adding warning messages in the chart notes that would prevent the installations to be upgraded if the credentials are not passed again.

**Comment by SeWieland** [comment]
I just experienced the exact same thing using your wordpress chart.

**Comment by andresbono** [comment]
Hi @SeWieland, can you detail the steps that you followed so that we can reproduce your issue on our side? Please let us know the chart versions that you are using as well.
