### ISSUE TITLE
[bitnami/odoo] disable demo data import

### ISSUE THREAD

**Issue by ruddy32** [bitnami/charts#3887]
**Which chart**:
Odoo 14.0.20.

**Is your feature request related to a problem? Please describe.**
Cannot start Odoo instance without demo data.

**Describe the solution you'd like**
Odoo service support **without-demo** flag. InitContainer would be able to push this flag into Odoo configuration file. Doing this way clear the current configuration. It might be necessary to update bitnami odoo docker image to add this new configuration parameter.

**Comment by miguelaeh** [comment]
Hi @ruddy32 ,
Thank you very much for the request. I will create an internal task to do it. Nevertheless, I cannot provide an ETA for that.
Regards.

**Comment by ruddy32** [comment]
As I understand, this feature require to update odoo nami configuration and docker image.

**Comment by miguelaeh** [comment]
Hi @ruddy32 ,
I already created the internal task, please have in mind we are a small team and we have limited resources.
We will update this thread once we implement the changes.
Regards.

**Comment by HackbartJoao-ATLA** [comment]
I would like to know if there is any workaround for creating a database without Demo data.

**Comment by ruddy32** [comment]
An issue related to demo on odoo bitnami docker image provide a workaround : https://github.com/bitnami/bitnami-docker-odoo/issues/48#issuecomment-470678360

**Comment by miguelaeh** [comment]
Thanks @ruddy32  for sharing the link to the workaround!
