### ISSUE TITLE
[bitnami/parse] Dashboard Ingress with path /dashboard invalid redirect 

### ISSUE THREAD

**Issue by B-tristan** [bitnami/charts#3892]
**Which chart**:
Parse 12.0.2

**Describe the bug**
When dashbord path is empty / it works
When dashboard path is /dashboard the redirect login is not found ??

Must i add an annotation nginx.ingress.kubernetes.io/  ?
thank you

**Comment by marcosbc** [comment]
Hi @B-tristan, currently it seems like we support those options in the chart (for Ingress) but not in the container image, as it would require to make sure Parse accepts being accessed through those locations.

Is there any reason for accessing in a different path than /?

**Comment by B-tristan** [comment]
Hi marcosbc and thank you for you answer. The only reason is for clean separation of domains and subdomains : 
app.domain.com for client container
dashboard-app.domain.com for dashboard container
api-app.domain.com for parse container

**Comment by B-tristan** [comment]
thank you very much. One last tip, I want to add cloud functions in files/cloud/main.js (not in ConfigMap). What is the right way ?

**Comment by marcosbc** [comment]
@B-tristan To add cloud functions in `files/cloud` in the chart directory, just create the .js script, i.e. `main.js` with the following contents:

```
Parse.Cloud.define("sayHelloWorld", function(request, response) {
    return "Hello world!";
});
```

It is not described for the chart, but it is documented for the container image here: https://github.com/bitnami/bitnami-docker-parse#how-to-deploy-your-cloud-functions-with-parse-cloud-code

>* Once both Parse and Parse Dashboard are running, access Parse Dashboard and browse to 'My Dashboard -> API Console'.
>* Then, send a 'test query' of type 'POST' using 'functions/sayHelloWorld' as endpoint. Ensure you activate the 'Master Key' parameter.
>* Everything should be working now and you should receive a 'Hello World' message in the results.
>
>Find more information about Cloud Code and Cloud functions in the [official documentation](https://docs.parseplatform.org/cloudcode/guide/).
