### ISSUE TITLE
Which Helm Chart Version nad Image Version for RabbitMQ 3.7.5

### ISSUE THREAD

**Issue by SpatialJ** [bitnami/charts#3893]
Hello,
we want to run a 3 Node RabbitMQ 3.7.5 Cluster in K8S. Which Version of the Helm Chart should be use and what would be correct image version / tag?

Thanks

**Comment by carrodher** [comment]
Hi, you should be able to change the image tag just by setting `--set image.tag=3.7.5` when installing the chart or modifying the _values.yaml_. In the same way, to change the number of nodes you should modify the `replicaCount` parameter.
