### ISSUE TITLE
Get the server static content from multiple git repositories

### ISSUE THREAD

**Issue by cuttingedge1109** [bitnami/charts#3895]
**Which chart**:
bitnami/apache

**Describe the solution you'd like**
I am using cloneHtdocsFromGit.enabled=true for the server content from the git repo.
It works well but only for one repo.
I am expecting to get the server static content from multiple git repositories

Regards.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but currently this chart does not support this feature.
  Please, don't hesitate to send  a PR adding this (or other) feature, we will be glad to review and merge it.

Best regards
