### ISSUE TITLE
[bitnami/rabbitmq] Possibility to change port names

### ISSUE THREAD

**Issue by HazemElAgaty** [bitnami/charts#3899]
**Which chart**:
chart: bitnami/rabbitmq
version: 7.6.0

**Is your feature request related to a problem? Please describe.**
Currently there is no way to change the port names in the chart. I am using [istio service mesh](https://istio.io/) and the default ports naming that are used in the chart does not follow the [istio conventions](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/). 

**Describe the solution you'd like**
Option to change port names from the values file.

**Example**:
service:
   - portName: {Name}
   - port: {Port}

**Comment by marcosbc** [comment]
Hi @HazemElAgaty, you seem to be right. Feel free to send a PR to make this change, which seems to be simple. We'd be glad to review anything that helps improve the chart for users!

**Comment by HazemElAgaty** [comment]
@marcosbc Thanks for your quick reply. I am planning to open a PR for this, glad to contribute :)

**Comment by noderat** [comment]
@HazemElAgaty Did you end up getting a PR for this that you can link to this issue?

**Comment by HazemElAgaty** [comment]
@noderat I am planning to open a PR this weekend.
