### ISSUE TITLE
[external-dns] What does this chart do with aws.credentials.secretKey aws.credentials.accessKey ? 

### ISSUE THREAD

**Issue by red8888** [bitnami/charts#3904]
Just want to confirm the behavior  of this. Will this chart create a secrete volume for the aws secrets for you?  Im confused about what its doing: https://github.com/bitnami/charts/blob/be5b30d4b65794d63d36449fc6e8a912bdccbdda/bitnami/external-dns/templates/deployment.yaml#L230

I want to make sure that the aws creds passed in through this chart are handled secretly. What I usually do is create a k8s secret for the username and password and use valuefrom secret for the environment variables

Thanks!

**Comment by FraPazGal** [comment]
Hi @red8888,

Thank you for your question! It is indeed the same secure implementation; it first [creates the secret](https://github.com/bitnami/charts/blob/129493edc0f30870d9f988ac540c36765d9d20e1/bitnami/external-dns/templates/secret.yaml#L13) which is then [mounted](https://github.com/bitnami/charts/blob/be5b30d4b65794d63d36449fc6e8a912bdccbdda/bitnami/external-dns/templates/deployment.yaml#L227) in the pod.
