### ISSUE TITLE
Cluster not created properly with cluster.externalAccess.enabled 

### ISSUE THREAD

**Issue by mn0o7** [bitnami/charts#3914]
**Which chart**:
The name (and version) of the affected chart
redis-cluster
version: 3.2.2

**Describe the bug**
First of all the chart works great without cluster.externalAccess.enabled.
The bug occurs when I install the redis-cluster with cluster.externalAccess.enabled then i upgrade adding the loadbalancer ips, the pods seem to be created but redis-clis shows :

a7edbd9a970134edea7077cb77191432-1882165157.us-east-1.elb.amazonaws.com:6379> set x y
**(error) CLUSTERDOWN Hash slot not served**

**To Reproduce**
1. install the chart 
helm install devops-redis-cluster --set "password=test,cluster.externalAccess.enabled=true,service.type=LoadBalancer" bitnami/redis-cluster

2. Get the external ips of the svc
kubectl get svc | grep devop-redis-cluster

3.  update the deployment with the svc external ips
helm upgrade devops-redis-cluster --set "password=test,global.storageClass=rook-ceph-block-zone,service.type=LoadBalancer,cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com,cluster.externalAccess.service.loadBalancerIP[1]=a9b31b4493c0a4b59aa8453dab2d6913-1737920089.us-east-1.elb.amazonaws.com,cluster.externalAccess.service.loadBalancerIP[2]=a460f18eebc76401c82a630a965924c4-1982185564.us-east-1.elb.amazonaws.com,cluster.externalAccess.service.loadBalancerIP[3]=a80357ff3bdd64424be1c2e6c0fa7332-1148713351.us-east-1.elb.amazonaws.com,cluster.externalAccess.service.loadBalancerIP[4]=ac67916d19b4b40b0bbc263979ed69a8-59780134.us-east-1.elb.amazonaws.com,cluster.externalAccess.service.loadBalancerIP[5]=a7f47ee34ccc34d81a9e763f188bba47-765381766.us-east-1.elb.amazonaws.com" bitnami/redis-cluster

4. Check the logs of the create pod ( my logs are attached )

5. try a redis-cli command 
**Expected behavior**
To have a functioning cluster that i can set keys and get keys, This works perfect without cluster.externalAccess.enabled

**Version of Helm and Kubernetes**:
Helm 3.2.4
Kubeernetes v1.16.9

- Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
I attached logs from cluster update pods because i tried to set addNodes: true and i got some interesting log:
>>> Check slots coverage...
[ERR] Not all 16384 slots are covered by nodes.

Logs from cluster creator:
`vagrant@vagrant:~$ k logs devops-redis-cluster-cluster-create-fsbdx -f
redis-cluster 09:20:34.05
[update.log](https://github.com/bitnami/charts/files/5332763/update.log)

redis-cluster 09:20:34.05 Welcome to the Bitnami redis-cluster container
redis-cluster 09:20:34.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 09:20:34.05 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 09:20:34.05
redis-cluster 09:20:34.05 INFO  ==> ** Starting Redis setup **
redis-cluster 09:20:34.07 INFO  ==> Initializing Redis
redis-cluster 09:20:34.09 INFO  ==> Setting Redis config file
redis-cluster 09:20:34.12 INFO  ==> ** Redis setup finished! **

Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a17a5ff639d2f42e5ac233934f2ed7d0-2049906688.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a9b31b4493c0a4b59aa8453dab2d6913-1737920089.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
Node a9b31b4493c0a4b59aa8453dab2d6913-1737920089.us-east-1.elb.amazonaws.com not ready, waiting for all the nodes to be ready...
The cluster was already created, the nodes should have recovered it`

**Comment by mn0o7** [comment]
I notice also when i try to create the cluster manually using redis-cli --cluster create with 3 nodes for example not all of them join only 2 its really unclear because all nodes have access to each other even though its through the ip of AWS ELB

**Comment by FraPazGal** [comment]
Hi @mn0o7,

Thanks for opening this issue! I haven't been able to reproduce this issue. Could you share the output of `cluster info` and `cluster nodes` using `redis-cli`?

Regarding the misbehaviour adding new nodes, it is known there are some issues with it and #3928 looks to address it, so we should have a solution for that once the PR is merged.

**Comment by mn0o7** [comment]
Hi @FraPazGal,

I found the problem i was using the aws elb hostname instead of an ip in the helm upgrade. Even though it obviously says to provide the loadbalaner-ip in the notes, I think its a good idea to print an error if anything other than an ip is provided or try to do resolving before running the cluster create commands.
Here is was worked for me 

helm upgrade test-redis-cluster --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=172.20.1.245,cluster.externalAccess.service.loadBalancerIP[1]=172.20.2.101,cluster.externalAccess.service.loadBalancerIP[2]=172.20.3.7,cluster.externalAccess.service.loadBalancerIP[3]=172.20.3.167,cluster.externalAccess.service.loadBalancerIP[4]=172.20.1.154,cluster.externalAccess.service.loadBalancerIP[5]=172.20.2.57" ./redis-cluster-external

**Comment by FraPazGal** [comment]
Hi @mn0o7,

I'm glad you resolved your issue! It could indeed be helpful to validate the IPs inputs, we'll discuss it internally for future versions. Thanks for the recommendation!
