### ISSUE TITLE
[bitnami/airflow] Add option to install extra pip packages

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#3920]
**Which chart**:
airflow current version

**Is your feature request related to a problem? Please describe.**
We need to install third party python packages into images.

**Describe the solution you'd like**
We should have an init option so that we can install all these packages before the container gets started.

**Describe alternatives you've considered**
We use bitnami images as base image and install whatever packages we need, and use them with this chart.

**Comment by rafariossaa** [comment]
Hi,
  Could you take a look to https://github.com/bitnami/charts/issues/2588 and see if that works for you ?

**Comment by iamsudip** [comment]
@rafariossaa Thanks. This solves the problem. Can we document it on the chart installation page itself so that it's easily searchable? I can open a PR.

**Comment by rafariossaa** [comment]
@iamsudip , 
  Thank you, that would be great. 
  We will be glad to review and merge it.
  Thanks forehand.

**Comment by iamsudip** [comment]
@rafariossaa 

While working on the documentation PR, I got an idea, what if we create a directory `requirements` inside `files` just like for dags, and allow chart users to keep a `requirements.txt` inside that directory. So, that we can detect it while installing or upgrading chart and add the volumes and volumeMounts?

**Comment by rafariossaa** [comment]
Hi,
  Can you elaborate a bit more ?, I not very sure about the "add the volumes and volumeMounts"  part.

**Comment by iamsudip** [comment]
@rafariossaa Like we do for local dag files, users need to keep their dags here: https://github.com/bitnami/charts/tree/master/bitnami/airflow/files/dags, the chart then picks it up using this volume and volumemounts here: https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/statefulset-worker.yaml#L317,

I want to implement same with requirements.txt, we will create a directory called `requirements` and keep a `README.md`, if a requirements.txt is present in that directory similar to dags, a new volume will be mounted to all airflow containers `/bitnami/python/requirements.txt`, from there on docker image will take care of running `pip install -r /bitnami/python/requirements.txt`

**Comment by rafariossaa** [comment]
Hi,
  I think that would be great.
  Take into account that currently there is a work in progress PR https://github.com/bitnami/charts/pull/4069 that will change several things in the chart. So maybe is better your wait until that PR is merged before you work in your PR.

**Comment by iamsudip** [comment]
@rafariossaa Sure, I will wait for #4069 to get merged first. Thanks for your feedback. :)

**Comment by rafariossaa** [comment]
You are welcome.

**Comment by sudip-moengage** [comment]
@rafariossaa I think it's not implemented in the major refactor. What do you suggest?

**Comment by iamsudip** [comment]
@rafariossaa @juan131 I think it was not part of the refactor. What do you suggest?

**Comment by rafariossaa** [comment]
Hi, 
  The thing about the refactor was to you no be caught in the middle of the change and if you had sent a PR you maybe have had to change it.
  Feel free to sent your PR, we will be glad to review and merge it.
  Sorry for the delay.

**Comment by iamsudip** [comment]
@rafariossaa Since local dag files are no longer supported from v7 and my approach is similar for requirements.txt, I think we should not implement this.
