### ISSUE TITLE
[mongodb] The external service is created in default namespace for replicaset even when a different namespace is used

### ISSUE THREAD

**Issue by deshetti** [bitnami/charts#3921]
**Which chart**:
mongodb (9.2.2)

**Describe the bug**
The external service is always getting created in `default` namespace even when mongodb replicaset is installed in a different namespace using `global.namespaceOverride`

**To Reproduce**
1. Install the chart by overriding the default namespace and replicaset by using the following 

```
    --set global.namespaceOverride=databases \
    --set architecture=replicaset \
    --set externalAccess.enabled=true \
    --set externalAccess.service.type=LoadBalancer \
    --set externalAccess.service.port=27017 \
    --set externalAccess.autoDiscovery.enabled=true \
    --set serviceAccount.create=true \
    --set rbac.create=true \
```
2. The external service is created in the default namespace and not the `databases` namespace for eg based on the above params. Hence it is not able to connected to it externally

**Expected behavior**
The external service should be created in the same namespace as the `global.namespaceOverride` if the namespace is overridden

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I have never written a helm chart before but looks like the following is missing namespace in the metadata: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/external-access-svc.yaml

Need to add the following in metadata:

```
namespace: {{ include "mongodb.namespace" . }}
```

**Comment by miguelaeh** [comment]
Hi @deshetti ,
The above PR should fix that issue.
Thank you very much for reporting it.
Regards.

**Comment by deshetti** [comment]
@miguelaeh Does it take a while to merge this PR? I see that there are some PRs pending for a few weeks and wanted to check if this would be merged any soon for us to use without making those changes on our end manually?

**Comment by miguelaeh** [comment]
Hi @deshetti ,
We try to check all the PRs within 24 hours since they are created. When a PR takes too much time before merging it is either is an internal PR (i.e a PR that has been created by someone from our team) or because the PR makes controversial changes.

**Comment by deshetti** [comment]
@miguelaeh I am running the MongoDB chart with the following command and it is throwing me an error for where you added the namespace:

```
helm install mongodb bitnami/mongodb \
    --version 9.2.3 \
    --set global.namespaceOverride=databases \
    --set metrics.enabled=true \
    --set architecture=replicaset \
    --set replicaCount=2 \
    --set pdb.create=true \
    --set serviceAccount.create=true \
    --set rbac.create=true \
    --set externalAccess.autoDiscovery.enabled=true \
    --set externalAccess.enabled=true \
    --set externalAccess.service.type=LoadBalancer \
    --set externalAccess.service.port=27017 \
```

Following is the error:

```
"bitnami" already exists with the same configuration, skipping
Error: template: mongodb/templates/replicaset/external-access-svc.yaml:13:16: executing "mongodb/templates/replicaset/external-access-svc.yaml" at <include "mongodb.namespace" .>: error calling include: template: mongodb/templates/_helpers.tpl:57:18: executing "mongodb.namespace" at <.Values.global>: can't evaluate field Values in type int
```

Is there anything that needs to be modified here? https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/_helpers.tpl#L53

**Comment by miguelaeh** [comment]
I introduced a typo in the context: https://github.com/bitnami/charts/pull/3965 should fix the error
