### ISSUE TITLE
[bitnami/redis-cluster]: pod without pvc don't rejoin cluster after restart

### ISSUE THREAD

**Issue by tpolekhin** [bitnami/charts#3933]
**Which chart**:
`redis-cluster-3.2.6`

**Describe the bug**
Pod without PVC don't rejoin the cluster after restart

**To Reproduce**
1. `helm install redis-cluster bitnami/redis-cluster --set 'persistence.enabled=false'`
2. `kubectl delete pod redis-cluster-2`
3. `kubectl exec -it redis-cluster-2 -c redis-cluster bash`
4. `I have no name!@redis-cluster-2:/$ redis-cli cluster info`

**Expected behavior**
New Pod should use `REDIS_NODES` environment variable to rejoin the cluster

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12+IKS", GitCommit:"d09005b98837bb6061c0f643a27383c02b003205", GitTreeState:"clean", BuildDate:"2020-09-16T21:47:16Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
After master Pod restarts it doesn't rejoin the cluster if persistence is disabled
```
I have no name!@redis-cluster-2:/$ redis-cli cluster info
cluster_state:fail
cluster_slots_assigned:0
cluster_slots_ok:0
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:0
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
I have no name!@redis-cluster-2:/$ redis-cli cluster slots
(empty array)
```

**Comment by miguelaeh** [comment]
Hi @tpolekhin ,
This is expected since we need to store a map with hosts and nodes IPs in the volume in order to re join the cluster when the pods' IPs change (that happens when you kill a pod).
You can see that logic at https://github.com/bitnami/bitnami-docker-redis-cluster/blob/69b6c5f07db9f616fb07027977b184bfc013a2d3/6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh#L177

**Comment by allen-servedio** [comment]
@miguelaeh - you might be right, but it was suggested otherwise that the REDIS_NODE env might be enough and so this issue was opened: https://github.com/bitnami/charts/issues/3876#issuecomment-704747619

**Comment by tpolekhin** [comment]
@miguelaeh so looking at the logic in the code I can see that the list of nodes is still read from the ENV var here https://github.com/bitnami/bitnami-docker-redis-cluster/blob/69b6c5f07db9f616fb07027977b184bfc013a2d3/6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh#L178
The next operations depends on `nodes.sh` file existing or not
Since this is a new pod without PVC it shouldn't be there
So it should create this file with all of the nodes from the ENV variable here https://github.com/bitnami/bitnami-docker-redis-cluster/blob/69b6c5f07db9f616fb07027977b184bfc013a2d3/6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh#L189

**Comment by miguelaeh** [comment]
The cluster is created by a k8s job. Once that job is executed, the nodes store some configurations in the `nodes.conf` file mapping nodes IDs with IPs. That configuration is used in future restarts (that's where we change the IPs using the nodes.sh if the node IP changes) to  join the cluster again. If you create a pod without a volume, the `nodes.conf` will not persist from the cluster join, so the node will not know how to join the cluster unless you execute a command to join it again.

**Comment by tpolekhin** [comment]
@miguelaeh got it, so without this `nodes.conf` file on PVC new pod will not know it's previous IP address and/or Redis node ID to re-join the cluster and take it's place. Thanks for the explanation!

**Comment by miguelaeh** [comment]
You're welcome!

**Comment by bamaas** [comment]
We've got a similar situation going on right now. How could we safely recover from this? Already tried the 'cluster meet' command but without any success. Pod not becoming ready because the probe is failing (cluster_state:fail). Nodes.conf and nodes.sh are updated with hash to ip mapping.
