### ISSUE TITLE
[bitnami/mysql] and [bitnami/mariadb] custom username not in secret

### ISSUE THREAD

**Issue by timothyclarke** [bitnami/charts#3950]
**Which chart**:
* [bitnami/mysql]  : 6.14.10
* [bitnami/mariadb] : 8.0.3
Possibly others

**Describe the bug**
Custom DB users are not injected via the secret, the custom user is exposed when describing the pod.
It also prevents other charts from being able to use credentials solely from the the secrets (they have to get the user from somewhere else). 

**To Reproduce**
### MySQL
Install chart with `--set db.user=customValue`
### MariaDB
Install chart with `--set auth.username=customValue`

**Expected behavior**
I expect that the custom database user AND custom database password come from the secret rather than splitting the credentials between the secret and an environmental variable

**Version of Helm and Kubernetes**:

Not Applicable

**Additional context**
This appears to be part of the chart design so maybe a feature request, however as this is security related I consider it a bug

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. Just as you said, this was a design decision so I will forward this to the rest of the team for evaluation. Maybe we should consider changing it in all of the charts. I cannot guarantee an ETA, but as soon as we have more news, I will update the ticket.

**Comment by serg-bs** [comment]
That is first question many people ask each other. What should I store in secret? Probably - only secret info. 
You want also USER, But in my python app
But everybode want all settings togethe
 ```
            'HOST': env('MYSQL_HOST', default='mysql'),
            'PORT': env('MYSQL_PORT', default='3306'),
            'NAME': env('MYSQL_DB', default='rot'),
            'USER': env('MYSQL_USER', default='root'),
```
Why you don't want DB name also?
May be put all this settings in secret?
Or may by everything put in configmap? 

I think store only password in secret is right decition.

**Comment by timothyclarke** [comment]
Thank you @serg-bs  You raise a valid point, to which I've got to ask "What information is secret / sensitive"
I'd respond by saying all 4 config elements you reference. 
If I know 3 elements of a 4 element credential then I've only got to crack that 4th element. If I know 0 elements of a 4 element credential then I've got to figure out all 4. 
While I agree that host and port are not generally as sensitive as username and password I try to avoid clear text / dictionary user names as I've encountered FAR too many situations where the password has either been `password` or has been the same as the username

**Comment by javsalgar** [comment]
Hi,

This is interesting. It is something that we've discussed in the past. I think we should reconsider the current standard, as the username (and the database name) makes sense to be in the secret.

**Comment by serg-bs** [comment]
Thanks @timothyclarke for response.  Security reason is not a big argument here. Please notice, that root user is always static. I mean in case of root you can change name and store it in secret. 
You didn't notice about database name. Always we create database in bundle with user password.

**Comment by timothyclarke** [comment]
@javsalgar @serg-bs This one has been open for a while now is there any chance of a decision / statement from bitnami on this one? 
My personal OCD hates having issues open & languishing. esp. in a limbo state. I'd obviously prefer a "Yes this is something we need to do something about", but I can understand a "No we don't think that is a security issue, lets close this ticket"

**Comment by javsalgar** [comment]
Hi,

I re-prioritized this and we will reach a decision during this sprint. Our concern is that this will imply a major change in all of our charts so it may not be something to be implemented in the short term. But at least we think we could devise an action plan in case we want to go ahead with this.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
