### ISSUE TITLE
Last Commit Breaks the chart (bitnami/mongodb)

### ISSUE THREAD

**Issue by Wajdovic** [bitnami/charts#3956]
This command used to work for me, : 

helm install my-release --set auth.rootPassword=**********,architecture=replicaset,externalAccess.enabled=true,externalAccess.service.type=LoadBalancer,serviceAccount.create=true,rbac.create=true,externalAccess.autoDiscovery.enabled=true bitnami/mongodb

Now I got this error : (after the last commit)

Error: template: mongodb/templates/replicaset/external-access-svc.yaml:13:16: executing "mongodb/templates/replicaset/external-access-svc.yaml" at <include "mongodb.namespace" .>: error calling include: template: mongodb/templates/_helpers.tpl:57:18: executing "mongodb.namespace" at <.Values.global>: can't evaluate field Values in type int

**Comment by deshetti** [comment]
Adding the comment from https://github.com/bitnami/charts/issues/3921 to here as well as the other issue was closed.

@miguelaeh I am running the MongoDB chart with the following command and it is throwing me an error for where you added the namespace:

```
helm install mongodb bitnami/mongodb \
    --version 9.2.3 \
    --set global.namespaceOverride=databases \
    --set metrics.enabled=true \
    --set architecture=replicaset \
    --set replicaCount=2 \
    --set pdb.create=true \
    --set serviceAccount.create=true \
    --set rbac.create=true \
    --set externalAccess.autoDiscovery.enabled=true \
    --set externalAccess.enabled=true \
    --set externalAccess.service.type=LoadBalancer \
    --set externalAccess.service.port=27017 \
```

Following is the error:

```
"bitnami" already exists with the same configuration, skipping
Error: template: mongodb/templates/replicaset/external-access-svc.yaml:13:16: executing "mongodb/templates/replicaset/external-access-svc.yaml" at <include "mongodb.namespace" .>: error calling include: template: mongodb/templates/_helpers.tpl:57:18: executing "mongodb.namespace" at <.Values.global>: can't evaluate field Values in type int
```

Is there anything that needs to be modified here? https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/_helpers.tpl#L53

**Comment by miguelaeh** [comment]
I am sorry, I introduced a typo the above PR should fix it
