### ISSUE TITLE
How can I set nodeIP to kafka EXTERNAL IP?

### ISSUE THREAD

**Issue by zulifeng1994** [bitnami/charts#3962]
**Which chart**:
bitnami/kafka

**Is your feature request related to a problem? Please describe.**
How can I set nodeIP to kafka EXTERNAL IP?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by javsalgar** [comment]
Hi,

We have an option for allowing external access in our kafka cluster. Would that work  for your case? https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster

**Comment by zulifeng1994** [comment]
Hey, I did follow this method, but there seem to be some problems.

`$ kubectl exec -it kafka-70-3 -n dev-dev  -- cat /opt/bitnami/kafka/config/server.properties | grep advertised.listeners
advertised.listeners=INTERNAL://kafka-70-3.kafka-70-headless.dev-dev.svc.cluster.local:9093,CLIENT://kafka-70-3.kafka-70-headless.dev-dev.svc.cluster.local:9092,EXTERNAL://211.***.***.*53:32739`

`EXTERNAL://211.***.***.*53:32739` 32739 is node port, but `211.***.***.*53` is not my k8s cluster node ip,It's a public network IP. So I can't access my kafka through `211.***.***.*53:32739`

**Comment by javsalgar** [comment]
Hi,

Did you try using the LoadBalancer-only option of the documentation? https://github.com/bitnami/charts/tree/master/bitnami/kafka#using-loadbalancer-services

**Comment by zulifeng1994** [comment]
Thank you for your patient answer. My problem has been solved.

**Comment by javsalgar** [comment]
Thanks for letting us know!
