### ISSUE TITLE
[bitnami/*] Prefer use of mariadb-galera to mariadb as subchart

### ISSUE THREAD

**Issue by lwj5** [bitnami/charts#3967]
**Which chart**:
There are many charts that I can list that use mariadb as a sub chart (dependency).
Some examples are (not exhaustive):
- spring-cloud-dataflow
- wordpress

**Is your feature request related to a problem? Please describe.**
These apps have no use for a primary/secondary or master/slave DB deployed in mariadb chart as they are only designed to use the primary writer. Moreover, the mariadb chart is not designed to do failover. So setting any number of replicas >1 in these charts does not benefit the deployment.

Using mariadb chart as a sub chart essentially makes them limited to a non HA set up.

Whereas if the mariadb-galera chart was used, you are given a choice. It could be scaled down to 1 for a non-HA deployment and scaled up for a HA one, offering the flexibility in-built into the chart. I understand that you could point the chart to an external maria-galera deployment, but that's not the point I'm trying to make as it doesn't offer out-of-the-box flexibility.

To add on, mariadb sub chart versions are updated quite frequently, each of these causes downtime even if a secondary is used (as it does nothing). If mariadb-galera were to be used instead and multiple replicas are available, there will be no downtime from the rolling update.

**Describe the solution you'd like**
Use maria-galera as a sub chart in new major releases of the main chart.

**Describe alternatives you've considered**
Use an external maria-galera deployment, but doesn't offer out-of-the-box flexibility.

**Additional context**
AFAIK, mariadb-galera can work with a single replica. Please correct me if I'm wrong.
I do not mind contributing if people think that this is a good idea, and there are upcoming major chart releases (like if there are plans to try to move mariadb sub charts from v7 to 8), especially in those charts listed above, it would be better to move from v7 to mariadb-galera.

**Comment by andresbono** [comment]
Hi @lwj5, you are rising an interesting topic. The reason why we are using mariadb instead of mariadb-galera is just to keep things simple for the dependencies of the charts. As you mention, a user can always use the external database parameters if they want to use more advanced options like MariaDB Galera if they feel comfortable with it.
