### ISSUE TITLE
[bitnami/cassandra] Unable to use existingSecret

### ISSUE THREAD

**Issue by ailox** [bitnami/charts#3979]
**Which chart**:
Cassandra, v6.0.1 (latest)

**Describe the bug**
Unable to use an existingSecret, when this attribute is specified the helm chart is no longer able to render.

**To Reproduce**
1. Set `dbUser.existingSecret` to any secret name of your choice
2. Render helm chart (`helm template`)
3. See error:

```Error: render error in "cassandra/templates/NOTES.txt": template: cassandra/templates/NOTES.txt:1:31: executing "cassandra/templates/NOTES.txt" at <include "common.secrets.key" (dict "existingSecret" .Values.dbUser.existingSecret "key" "cassandra-password")>: error calling include: template: cassandra/charts/common/templates/_secrets.tpl:43:24: executing "common.secrets.key" at <.existingSecret.keyMapping>: can't evaluate field keyMapping in type interface {}```

**Expected behavior**
Able to specify a existing secret, so no random password will get generated

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```Version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am currently thinking this bug is caused by the different expected definition of `existingSecret` in https://github.com/bitnami/charts/blob/3e7916d0e39fcc88b13e17bab6144ac90aa7603a/bitnami/cassandra/templates/statefulset.yaml#L125 (expects string), and https://github.com/bitnami/charts/blob/3e7916d0e39fcc88b13e17bab6144ac90aa7603a/bitnami/cassandra/templates/NOTES.txt#L1 (expects object with this layout: https://github.com/bitnami/charts/tree/master/bitnami/common#existingsecret )

I tried working on a fix in PR #3978 , but can not get the linter to pass. I don't have an idea how to reference the 'cassandra-password' attribute without using the '-' (dash) character. Thus I'm currently stuck at this point.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that I was able to reproduce the issue. We will check the PR and provide feedback. Thank you so much for reporting!
