### ISSUE TITLE
[bitnami/discourse] PSA: you cannot have more than one replicas

### ISSUE THREAD

**Issue by stevefan1999-personal** [bitnami/charts#3980]
If you tried to run more than 1 replicas, then "/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid" will be superseded. This will cause a race condition and will eventually be written over and over again, and then this is why "/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid" will be "not found" for subsequent replicas, plus your original first replica will fail, too.

That said, this chart proably need to redesign to handle sidekiq and Discourse RoR app separately & independently to have proper high availability. The Discourse RoR app have stateful data and thus cannot really be spawned by a Deployment. However, sidekiq can be stateless.

**Comment by andresbono** [comment]
Thanks for your input, @stevefan1999-personal. It might make sense to split sidekiq and discourse in different controllers so they can scale independently but I'm not really sure if I understand the problem about `sidekiq.pid` being superseded when replicas are greater than 1. That pid file is not shared along the pods, how would it be causing race conditions?

What are the steps that you followed to scale? You can find this section in the README about replication:

[Setting up replication](https://github.com/bitnami/charts/tree/master/bitnami/discourse#setting-up-replication).

**Comment by stevefan1999-personal** [comment]
@andresbono I see. It's actually `/bitnami/discourse` being shared. I saw discourse and I think it was the shared one. I'll need to investigate a little more.

**Comment by stevefan1999-personal** [comment]
Ah I remember. I have just `mkdir -p /opt/bitnami/discourse-sidekiq/tmp/pids/`.

**Comment by stevefan1999-personal** [comment]
By the way this is just...the log, there's almost nothing.
```
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing discourse-sidekiq
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at zero-postgresql:5432
postgre INFO  PostgreSQL server listening and working at zero-postgresql:5432
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Sidekiq...
discour INFO  Waiting for Discourse service to be ready...
nami    INFO  discourse-sidekiq successfully initialized
Starting discourse-sidekiq...
nami    ERROR Unable to start com.bitnami.discourse-sidekiq: Cannot find pid file '/opt/bitnami/discourse-sidekiq/tmp/pids/sidekiq.pid'.
stream closed
```

**Comment by andresbono** [comment]
I have just installed `bitnami/discourse` `0.5.0` and I didn't find any issues, I didn't have to do any mkdir or chmod operation on the sidekiq container:

```
helm install discoursetest bitnami/discourse --set service.type=ClusterIP --set image.debug=true
```

Are you using different values to install the chart? I assume yes, at least you are modifying `replicaCount`, right?

You can increase the verbosity of the logs by setting `image.debug=true`.
