### ISSUE TITLE
[kube-prometheus] No way to provide sd_configs in this charts

### ISSUE THREAD

**Issue by rajeshneo** [bitnami/charts#3987]
**Which chart**:
kube-prometheus

**Describe the bug**
Community chart of prometheus operator provides a way to define serverFiles in which you can define sd_configs to enable your pods/endpoints to register as a target in prometheus. Is there any similar option here? I have gone through all the options but could not find any such option if it exists here. Is there a plan to support it?

Following is from prometheus config which i am trying to add
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
- serverConfig

     # Example scrape config for pods
      #
      # The relabeling allows the actual pod scrape endpoint to be configured via the
      # following annotations:
      #
      # * `prometheus.io/scrape`: Only scrape pods that have a value of `true`
      # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
      # * `prometheus.io/port`: Scrape the pod on the indicated port instead of the default of `9102`.
      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          - source_labels: [__meta_kubernetes_pod_phase]
            regex: Pending|Succeeded|Failed
            action: drop

**Comment by rajeshneo** [comment]
Found the reason as operator does not support it

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing.
