### ISSUE TITLE
[bitnami/thanos] Enable thanos querier client TLS certificates in a modular way

### ISSUE THREAD

**Issue by fsschmitt** [bitnami/charts#3988]
**Which chart**:
thanos

**Is your feature request related to a problem? Please describe.**
Thanos store TLS client enables the usage of TLS validation only though CA, not requiring a certificate's crt or key, therefore while **highly** recommended, these are not mandatory. 

Due to the fact that currently Thanos only supports a single TLS configuration across all stores (feature requested: https://github.com/thanos-io/thanos/issues/977), it is possible to use TLS with multiple stores through the usage of CA-only validation. This is required for use-cases such as the following:

![image](https://user-images.githubusercontent.com/492108/95775527-80d7aa80-0cba-11eb-8703-9088733477aa.png)

Where, for example, the grpc ingresses are:
- https://thanos-grpc.cluster-a.mycloud.dev
- https://thanos-grpc.cluster-b.mycloud.dev
- https://thanos-grpc.cluster-c.mycloud.dev

**Describe the solution you'd like**
Enable modular templating for CA, Cert and Key on Thanos Querier client TLS secrets and extra ags without breaking any backwards compatibility.

**Additional information**
I will be creating the PR with this solution as soon as possible, just wanted to create the issue so it would be tracked.

**Comment by dani8art** [comment]
Hi @fsschmitt thank you so much for your work here, the PR will be reviewed and merged soon. Let's move the conversation there.
