### ISSUE TITLE
[bitnami/elasticsearch] Add securitySettings configuration support

### ISSUE THREAD

**Issue by itsurkan** [bitnami/charts#3992]
*Which chart**:
elasticsearch-12.8.0 
app version 7.9.2 

**Is your feature request related to a problem? Please describe.**
I'm trying to connect azure storage as a repository for snapshots.
It requires to add secureSettings for account and key.
Currently, there is no option to configure this setting from values.json file.

**Describe the solution you'd like**
Add securitySettings parameter to the chart

**Comment by andresbono** [comment]
Hi @itsurkan, thanks for opening this issue. The Bitnami container for Elasticsearch supports passing an env-var to set secure keys: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables

> `ELASTICSEARCH_KEYS`: Comma, semi-colon or space separated list of key-value pairs (key=value) to store. No defaults.

This is the Bash function that handles it: https://github.com/bitnami/bitnami-docker-elasticsearch/blob/d105e487056ab2fbbbdfd2a6c8674a3e85752bcc/7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh#L541-L562

Is this what you are looking for? To use that in the chart, you can just make use of the `extraEnvVarsSecret` value to pass `ELASTICSEARCH_KEYS` to the container.

Let us know if this is useful for you.

**Comment by itsurkan** [comment]
Hello @andresbono, thanks for the response.
Yes, this is solution for my problem, but there is one point that I'm afraid is not secure.
Environment variable is visible in the list of env variables and not encrypted in any case
![image](https://user-images.githubusercontent.com/6732323/96577218-f9062780-12db-11eb-858b-2f549ef059d2.png)
Is there a solution not to display the variable?
Thanks

**Comment by itsurkan** [comment]
Also, I faced a problem, 
"invalid_key_exception","reason":"invalid_key_exception: Storage Key is not a valid base64 encoded string.", but in the ELASTICSEARCH_KEYS I have specified values in the format: 
azure.client.secondary.account=centra***;azure.client.secondary.key=E9I***4g==

**Comment by miguelaeh** [comment]
Hi @itsurkan ,
> Is there a solution not to display the variable?

Inside the pod I think you will always see the env var information, I think that also happens with normal passwords. But you need to have access to the pod to be able to extract that content.

About the secret you can just create the secret like:
```
apiVersion: v1
kind: Secret
metadata:
  name: <secretname>
  labels: <secret labels>
type: Opaque
data:
  azure.client.secondary.account: <value encoded in base64>
  azure.client.secondary.key: <value encoded in base64>
```

Then execute:
```
kubectl create -f <secretfile>
```

**Comment by itsurkan** [comment]
Hello @miguelaeh ,
Yes, I can create the secret you provided, but in this case I have to add this secret as secureSetting secret:
spec:
  secureSettings:
   - secretName: <secretname>
The problem is, the secureSettings property is not configured from helm chart, and wouldn't be added to the keystore.
So, it would be great to add such a feature.

**Comment by miguelaeh** [comment]
Hi @itsurkan ,
I can see that solution will only work for ECK: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html
I would suggest you to provide the env necessary env vars using the `extraEnvVarsSecret`. In that way the env vars will be taken from the secret, created in a similar way to the one of my previous comment.

**Comment by itsurkan** [comment]
@miguelaeh ,
Yes, I have already done it this way, and use initScripts to add env variables to the keystore
```
initScripts: 
  azureStorageSecrets.sh: |-
    echo $SnapshotAzureStorageAccountName | opt/bitnami/elasticsearch/bin/elasticsearch-keystore add -f azure.client.secondary.account
    echo $SnapshotAzureStorageAccountKey | opt/bitnami/elasticsearch/bin/elasticsearch-keystore add -f azure.client.secondary.key
```
If the helm chart doesn't support secureSettings or it can't be implemented the issue can be closed

**Comment by miguelaeh** [comment]
Hi @itsurkan m
Thank you for confirming and sorry for the inconvenience.
Regards.
