### ISSUE TITLE
[chart/spark] when I submit job,error is :java.nio.file.NoSuchFileException: /examples/jars/spark-examples_2.12-3.0.1.jar

### ISSUE THREAD

**Issue by yangjinlogic** [bitnami/charts#3993]
the command is :
./bin/spark-submit   --class org.apache.spark.examples.SparkPi   --master spark://10.96.254.134:7077 --deploy-mode cluster file:///examples/jars/spark-examples_2.12-3.0.1.jar 1000

error:
java.nio.file.NoSuchFileException: /examples/jars/spark-examples_2.12-3.0.1.jar

the sames:

./bin/spark-submit   --class org.apache.spark.examples.SparkPi   --master spark://10.96.254.134:7077 --deploy-mode cluster file:///opt/spark/examples/jars/spark-examples_2.12-3.0.1.jar 1000

error is same

**Comment by rafariossaa** [comment]
Hi,
  You can run the example following the instructions when the chart is launched.
  Ir you want to run it in a more step by step way, you can do the following:

```
$ export EXAMPLE_JAR=$(kubectl exec -ti --namespace default myspark-worker-0 -- find examples/jars/ -name 'spark-example*\.jar' | tr -d '\r')

$ echo $EXAMPLE_JAR 
examples/jars/spark-examples_2.12-3.0.1.jar
```
Now you can exec into the pod and execute:
```bash 
/opt/bitnami/spark$ spark-submit --master spark://myspark-master-svc:7077 --class org.apache.spark.examples.SparkPi examples/jars/spark-examples_2.12-3.0.1.jar 5
```
Notice that the path for the  spark-examples jar file is relative to the current path `/opt/bitnami/spark`, also you can use `file://` with the full path as follow:
```
/opt/bitnami/spark$ spark-submit --master spark://myspark-master-svc:7077 --class org.apache.spark.examples.SparkPi file:///opt/bitnami/spark/examples/jars/spark-examples_2.12-3.0.1.jar 5
```
Can you try this ?

**Comment by yangjinlogic** [comment]
@rafariossaa ，thank you for your response,I had solved the problem. I deploy tensorflow-resnet in my kubernetes, but i dont know how to  deploy machine learning model in my pod of "tensorflow-resnet"  .Could you help me ? please.

**Comment by rafariossaa** [comment]
Hi @yangjinlogic ,
 I am glad you were able to solve the problem.
 Could you open a new issue for the `tensorflow-resnet` ? I am not very sure if we can help with that, but that will help to keep organized the issues.

Thanks forehand
