### ISSUE TITLE
gh-pages for bitnami incubator chart repository

### ISSUE THREAD

**Issue by dhcdata** [bitnami/charts#401]
It would be great if the incubator charts were available as a maintained public repository that users could add as a dependency.  I think it would help increase adoption and move them to stable status. Here are the steps to do it.

### Setup gh-pages
Add gh-pages branch
```console
git clone --depth=1 git@github.com:bitnami/charts.git 
cd charts
git branch gh-pages && git checkout gh-pages
rm -fr * && rm .gitignore
git commit -am 'initial gh-pages commit' && git push --set-upstream origin gh-pages
```
From within GitHub's settings, find the section on "GitHub Pages".  From the source drop-down, select gh-pages and save.

### To Package
For each chart:
```console
git clone --depth=1 https://github.com/bitnami/charts.git --branch gh-pages tmp_chart
helm package -d ./tmp_chart/ . 
helm repo index tmp_chart --url https://bitnami.github.io/charts
git -C tmp_chart add *.tgz index.yaml &&  git -C tmp_chart commit -am 'new package xyz' && git -C tmp_chart push
rm -fr tmp_chart
```

### Add Bitnami Repo
First add the repo:
```console
helm repo add bitnami-incubator https://bitnami.github.io/charts
```
### Add Dependency
Create `requirements.yaml` file with the following content:
```
#requirements.yaml
dependencies:
- name: tomcat
  version: 0.4.11
  repository: https://bitnami.github.io/charts
  alias: bitnami-tomcat
```

### Override values
At the root level of `values.yaml` add the name of the alias from the dependency `bitnami-tomcat` as a node.
```
#values.yaml
[...]
bitnami-tomcat:
  tomcatUsername: override-user
[...]
```

**Comment by sameersbn** [comment]
@dhcdata thanks for the request. I completely agree with you. 
We are working on this. Will update you as soon as we are ready :slightly_smiling_face:
