### ISSUE TITLE
[bitnami/rabbitmq] Doesn't start on 1.19.1, eats all the CPU

### ISSUE THREAD

**Issue by glothriel** [bitnami/charts#4011]
**Which chart**:
bitnami/rabbitmq 7.6.8

**Describe the bug**
RabbitMQ doesn't start at all, hangs right after ` 13:00:17.57 INFO  ==> ** Starting RabbitMQ **`. The pod's status is `0/1`. Processes named `erl_child_setup` eat all of host CPU, on all cores.

**To Reproduce**
1. Download kind version [0.9.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0)
2. `kind create cluster`
3. `helm install --set image.debug=true my-release bitnami/rabbitmq`

**Expected behavior**
Well, it should start

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

 Not sure if it's chart/rabbitmq/kind error. I was asking my colleagues to reproduce this and no one was able to do this, nor our tests on CI show this behaviour, it seems to be happening only on my PC. I'm running Arch Linux, all the other people are using Debian/Ubuntu systems, but I don't know if it's related. I tried restarting the host, it didn't help. On the same version of kind, but using `1.18.x` nodes everything works as it should.  I tried to run strace and it was spamming about bad file descriptors. I can attach a full container log if it's desirable.

**Comment by glothriel** [comment]
Yes, I can confirm that it's a host problem (Arch Linux and default nofile limit). Thanks @rafariossaa, I'm closing this. If anyone else stumbles upon this problem, [this thread](https://github.com/kubernetes-sigs/kind/pull/760#issuecomment-519270703) describes a workaround.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing !
