### ISSUE TITLE
InfluxDB - single storage - high availability deployment - no data duplication

### ISSUE THREAD

**Issue by Yalafeg** [bitnami/charts#4014]
Hello,

I am trying to figure out if it's feasible to deploy the high availability feature without data duplication. What I need is a scalabality of  InfluxDB but at the same time without data duplication on the storage level. Different pods will be linked to the same storage. Is it feasible?

Regards,

**Comment by javsalgar** [comment]
Hi,

I think this should be confirmed by the InfluxDB devs. My guess is that sharing the same storage could potentially cause data corruption as several nodes would be writing at the same time.

**Comment by Yalafeg** [comment]
Thank you for your reply
