### ISSUE TITLE
[bitnami/prestashop] helm installation issue - parse error in "prestashop/charts/common/templates/_validations.tpl

### ISSUE THREAD

**Issue by marangiop** [bitnami/charts#4018]
**Which chart**:
Bitnami Prestashop 10.0.1

**Describe the bug**
When I try to install the chart with helm using the following command:

`helm install -n prestashop bitnami/prestashop -f values.yaml`

I get this output:

`Error: parse error in "prestashop/charts/common/templates/_validations.tpl": template: prestashop/charts/common/templates/_validations.tpl:39: unexpected "=" in operand
`
This is my values.yaml file

`prestashopHost: prestashop.test.euxdat.eu
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod-cluster-issuer"
  hosts:
  - name: prestashop.test.euxdat.eu
    tls: true
    tlsSecret: prestashop.test.euxdat.eu
prestashopUsername: whatever
prestashopPassword:  whatever #define or suppress and it will produce random password
persistence:
  enabled: true
  prestashop:
    storageClass: manual
mariadb:
  master:
    persistence:
      enabled: true
      storageClass: manual
`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by dani8art** [comment]
Hi @marangiop, I realize you are using helm version `2.9.1`, unfortunately, our charts only support `+v2.12`, please check requirements [here](https://github.com/bitnami/charts/tree/master/bitnami/prestashop#prerequisites)

**Comment by marangiop** [comment]
Hi @dani8art 

Thank you for your reply. I was able to install Prestashop in a different cluster with Helm version 2.16.9.

I installed Prestashop using the following command:

```
[user@host prestashop]$ helm install -n prestashop bitnami/prestashop -f values.yaml
NAME:   prestashop
LAST DEPLOYED: Thu Oct 15 20:08:17 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                DATA  AGE
prestashop-mariadb  1     1s

==> v1/Deployment
NAME        READY  UP-TO-DATE  AVAILABLE  AGE
prestashop  0/1    1           0          0s

==> v1/PersistentVolumeClaim
NAME                   STATUS   VOLUME  CAPACITY  ACCESS MODES  STORAGECLASS  AGE
prestashop-prestashop  Pending  1s

==> v1/Pod(related)
NAME                        READY  STATUS   RESTARTS  AGE
prestashop-c8668d994-5bxvh  0/1    Pending  0         0s
prestashop-mariadb-0        0/1    Pending  0         0s

==> v1/Secret
NAME                TYPE    DATA  AGE
prestashop          Opaque  1     1s
prestashop-mariadb  Opaque  2     1s

==> v1/Service
NAME                TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)         AGE
prestashop          ClusterIP  10.110.217.185  <none>       80/TCP,443/TCP  0s
prestashop-mariadb  ClusterIP  10.101.118.212  <none>       3306/TCP        0s

==> v1/ServiceAccount
NAME                SECRETS  AGE
prestashop-mariadb  1        1s

==> v1/StatefulSet
NAME                READY  AGE
prestashop-mariadb  0/1    0s

==> v1beta1/Ingress
NAME        CLASS   HOSTS                                           ADDRESS  PORTS  AGE
prestashop  <none>  prestashop.local,prestashop.platform.euxdat.eu  80       0s


NOTES:
1. Get the PrestaShop URL by running:

  echo "Store URL: http://127.0.0.1:8080/"
  echo "Admin URL: http://127.0.0.1:8080/administration"
  kubectl port-forward --namespace default svc/prestashop 8080:80

2. Get your PrestaShop login credentials by running:

  echo Admin Email   : user@example.com
  echo Admin Username: euxdat_admin
  echo Admin Password: $(kubectl get secret --namespace default prestashop -o jsonpath="{.data.prestashop-password}" | ba                                                 se64 --decode)
```


However, both of my opencart and opencart-mariadb pods have the following error message:

`0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims`

Any ideas as to why this is happening? Any potential fix?

Thank you in advance!

**Comment by dani8art** [comment]
Sorry, I missed something, have you also installed opencart? or are you referring to prestashop?

**Comment by marangiop** [comment]
Hi @dani8art,

Sorry for the confusion, I am currently trying to install OpenCart and Prestashop in two separate K8S clusters. I am having problems with the installation of both of them, hence this opened issue https://github.com/bitnami/charts/issues/4018 and this one https://github.com/bitnami/bitnami-docker-opencart/issues/84

I suppose that the latest questions in both issues are now related with persistence. I will try to use the same approach you suggested for the OpenCart issue for Prestashop. I will get back to you.

**Comment by dani8art** [comment]
Ok! Do not hesitate to contact us if you find any problems

**Comment by marangiop** [comment]
This is my `values.yaml` file

```
prestashopHost: some.domain.name.eu
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod-cluster-issuer"
  hosts:
  - name: some.domain.name.eu
    tls: true
    tlsSecret: some.domain.name.eu
prestashopUsername: user
prestashopPassword:  password
volumePermissions:
  enabled: true
persistence:
  enabled: true
  storageClass: manual
mariadb:
  volumePermissions:
    enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: manual
```
[xeupmara@prod-001 prestashop]$ helm search prestashop
```
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/prestashop      11.0.1          1.7.6-8         A popular open source ecommerce solution. Professional to...
stable/prestashop       9.1.11          1.7.6-4         DEPRECATED A popular open source ecommerce solution. Prof...
```

[xeupmara@euxdat-prod-001 prestashop]$ helm install -n prestashop bitnami/prestashop -f values.yaml
`Error: YAML parse error on prestashop/templates/deployment.yaml: error converting YAML to JSON: yaml: line 57: did not find expected key`

Any ideas with regards to the reason of this error?

**Comment by dani8art** [comment]
Hi @marangiop thank you for reporting this issue we have just created PR that will fix this error, please, let's move the conversation there.
