### ISSUE TITLE
[bitnami/postgresql] Update / reset admin password

### ISSUE THREAD

**Issue by sparqueur** [bitnami/charts#4025]
**Which chart**:
bitnami/postgresql

**Is your feature request related to a problem? Please describe.**

It is currently not possible to update postgresql password :

```yaml
helm upgrade --install psql --set postgresqlPassword=mypassword1 bitnami/postgresql -n postgresql
helm upgrade --install psql --set postgresqlPassword=mypassword2 bitnami/postgresql -n postgresql
```

=> Can't log with `mypassword2`

**Describe the solution you'd like**
Password is updated

**Describe alternatives you've considered**
Give a procedure in the doc in case of password lost ?

**Additional context**
How to currently handle it (by script) ?

**Comment by FraPazGal** [comment]
Hi @sparqueur,

The parameter `postgresqlPassword` is used at installation time to create a database user and would not modify the user's password at upgrade time. If the password you need to retrieve is the one created at `helm install` time, you could inspect the secret:

`kubectl get secret --namespace default post-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode`

If that isn't the case, you could login as the admin user `postgres` and execute an `ALTER USER` to set a new password to the user you need.

**Comment by sparqueur** [comment]
Thanks a lot for your response.
And what if the secret has already been override (and Lost) ? Maybe i should have a look at postresql documentation 😀

**Comment by juan131** [comment]
> And what if the secret has already been override (and Lost) ? Maybe i should have a look at Postresql documentation

You can try to do a rollback to a previous version of your Helm release. Find more information in the link below:

- https://helm.sh/docs/helm/helm_rollback/
