### ISSUE TITLE
Grafana helm chart error presistence.storageClass typo?

### ISSUE THREAD

**Issue by MrAmbiG** [bitnami/charts#4046]
**Which chart**:
grafana helm chart

**Describe the bug**
typo
 presistence.storageClass should be  persistence.storageClass

**To Reproduce**
install grafana helm chart with presistence.storageClass

**Expected behavior**
storageclass should work

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by carrodher** [comment]
Hi, thanks for reporting this typo. Luckily the typo only affects the README file; everywhere where the parameter is used it has the correct name, for example, https://github.com/bitnami/charts/blob/7a6028fba1bce735ad3916cab2a6bcfac767340f/bitnami/grafana/templates/_helpers.tpl#L149

I will send a PR fixing this issue. Thanks again
