### ISSUE TITLE
Support pod labels for WordPress

### ISSUE THREAD

**Issue by chris13524** [bitnami/charts#4047]
I want to attach a `NetworkPolicy` to my WordPress pods, but there is no way to apply a custom label to the pod. There is `commonLabels`, but this only applies to the [deployment](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/deployment.yaml#L7) and not the pod. There is `podAnnotations`, but annotations are not selectable by a `NetworkPolicy`.

This should be implemented either by a separate `podLabels` value or by applying `commonLabels` to the pod as well.

**Comment by iamsudip** [comment]
@chris13524 You can use `labels`([](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/deployment.yaml#L21)) to label your pods. However, this will not only label the pod but also all other resources. And, yes this is not documented.

**Comment by chris13524** [comment]
@iamsudip I also can't provide `labels` through values, right?

**Comment by miguelaeh** [comment]
Hi @chris13524 ,
I think there is not a way to add custom labels to the pods only at this moment.
Would you like to create a PR adding them?

**Comment by chris13524** [comment]
@migmartri I created PR #4053
