### ISSUE TITLE
How to create hidden node on MongoDB Cluster

### ISSUE THREAD

**Issue by deep1pradee** [bitnami/charts#4051]
**Which chart**:
mongodb-9.2.2

**Is your feature request related to a problem? Please describe.**
When we need to take the backup, we make use of the Hidden node in our existing setup(Plain installation)

**Describe the solution you'd like**
If we can enable the Hidden node while deploying the cluster that would be helpful for the backup jobs.

**Comment by carrodher** [comment]
The Bitnami MongoDB image allows you to use your custom scripts to initialize a fresh instance. To execute the scripts, you can specify them using the `initdbScripts` parameter as dict.

You can also set an external ConfigMap with all the initialization scripts. This is done by setting the `initdbScriptsConfigMap` parameter. Note that this will override the previous option.

In both cases the allowed extensions are `.sh` and `.js`.

Taking a look at the [_values.yaml_](https://github.com/bitnami/charts/blob/fe17b789ada17265d0c59c69a28d8741b2e30c4b/bitnami/mongodb/values.yaml#L168):
```yaml
## initdb scripts
## Specify dictionary of scripts to be run at first boot
## Example:
## initdbScripts:
##   my_init_script.sh: |
##      #!/bin/bash
##      echo "Do something."
initdbScripts: {}

## Existing ConfigMap with custom init scripts
##
# initdbScriptsConfigMap:
```
you can use one of the above methods to pass a custom script. In the first case, you should write the initialization script in the _values.yaml_ file and use this file when installing the chart. In the second one, you should create beforehand a ConfigMap with your script and then use the name of the ConfigMap in the above parameter.

Are you able to configure the hidden node by using one of the mentioned approaches?

**Comment by deveshk0** [comment]
@carrodher initdbScripts allows the customisation but it doesn't create a sperate service for connection, I am think add this. I will submit a PR soon

**Comment by carrodher** [comment]
Thanks, @deveshk0, any PR is more than welcome.

**Comment by deveshk0** [comment]
Added PR for changes in bitnami-docker-mongodb https://github.com/bitnami/bitnami-docker-mongodb/pull/246

**Comment by carrodher** [comment]
Thanks for the PR, we'll review it and provide feedback (if any)

**Comment by deveshk0** [comment]
@carrodher I want to add the hidden node functionality to the mongodb chart as it already merged in upstream [bitnmani-mongo-docker](https://github.com/bitnami/bitnami-docker-mongodb/pull/246)

I am little confused how to structure this, I got three options - 

1. Create another folder `hidden` like we have arbiter,replicaset,standalone 
2. Create a sub folder `hidden` in replicaset
3. Added template files directly to the replicaste folder

I think We will be needing following template  files for setting up hidden replicaset nodes - 

1. Headless svc template  for hidden node
2. Statefule set template  for hidden node
3. Pdb template  for hidden node
4. Setup scipt configmap  for hidden node
5. External svc template  for hidden node

**Comment by juan131** [comment]
Hi @deveshk0 

I'd create a similar structure to the one used for arbiter nodes. I mean, create a `hidden` subdirectory under `templates` and add the manifests below:

- `headless-svc.yaml`
- `statefulset.yaml`
- `pdb.yaml`
- `configmap.yaml`

Just curious: why do you need to provide support for external access to this kind of nodes?

**Comment by deveshk0** [comment]
@juan131 hidden nodes are very good use case for analytical  nodes, so you are not putting analytical workloads on active cluster.

**Comment by deveshk0** [comment]
@juan131 I have added a PR https://github.com/bitnami/charts/pull/5505, I still need to update README.md for variables

**Comment by juan131** [comment]
> @juan131 hidden nodes are very good use case for analytical nodes

Yes, I understand why this kind of nodes are useful. I was more curious about the reasons to expose them externally (out of the cluster).

> @juan131 I have added a PR #5505

Great! It will be assigned to some of the maintainers and be reviewed soon. Thanks so much
