### ISSUE TITLE
MOODLE_SITE_NAME is not exposed in the chart

### ISSUE THREAD

**Issue by samueldmq** [bitnami/charts#4055]
**Which chart**:
Moodle latest

**Describe the bug**
MOODLE_SITE_NAME image var is not exposed in the chart.
https://github.com/bitnami/charts/blob/4082ac08c9b9a6ba829f5b53856c8acd8d9e4e4f/bitnami/moodle/templates/deployment.yaml#L154-L178

Without it, it is not possible to set the Moodle name. It's always set to the image's default "New Site" when using the chart.
https://github.com/bitnami/bitnami-docker-moodle/blob/e96a4fee027401af12f6b43591042b2459d6c9fc/3/debian-10/rootfs/opt/bitnami/scripts/moodle-env.sh#L71

**To Reproduce**
1. Run the chart. There is no place to provide the site name.

**Expected behavior**
There should be a var in the values to provide the site name. Based on the existing values, it could be .Values.moodleSiteName. It is then passed in as MOODLE_SITE_NAME to the image.

**Version of Helm and Kubernetes**:

- Output of `helm version`: Irrelevant.

- Output of `kubectl version`: Irrelevant.

**Additional context**
Nothing additional.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. At the moment, you could use the extraEnvVars array to add that missing environment variable. I think the site name should be a value in the chart, so it is worth adding a `moodleSiteName` value. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by iamsudip** [comment]
@javsalgar I have some time these days, can I work on this?

**Comment by javsalgar** [comment]
Hi,

Sure! We would appreciate the collaboration :D
