### ISSUE TITLE
elasticsearch: use sysctlImage that already includes sysctl command 

### ISSUE THREAD

**Issue by Excpt0r** [bitnami/charts#4062]
Chart version:
elasticsearch-12.8.0

Describe the bug:
The sysctl init container uses as default the debian image, and requires internet access to install the sysctl command.

I suggest to use a sysctlImage by default that already includes the sysctl command.
That will make it work out of the box in offline environments too. I used the following image with success:
docker.io/bitnami/centos-extras-base:7-r535

reference: https://github.com/bitnami/charts/blob/5629e18febe4e81aac9993e9c7f5a32b6ecbf6c4/bitnami/elasticsearch/values.yaml#L50-L54

**Comment by Excpt0r** [comment]
Hi @dani8art, that is exactly what I'm already doing.

My suggestion is to change the default value, that other people using an offline environment don't have to know that procedure.

**Comment by dani8art** [comment]
Sorry but unfortunately we cannot do that, we agree on a standard around auxiliary images so we will always be using `bitnami/minideb` as default, doing that we offer an approach for solving a problem and also exist a way to customize the chart using custom values.

Thanks for the feedback!
