### ISSUE TITLE
Metallb 0.1.27 is running 2 different versions of metallb app

### ISSUE THREAD

**Issue by rchenzheng** [bitnami/charts#4075]
**Which chart**:
metallb 0.1.27

**Describe the bug**
The controller is running `0.9.4-debian-10-r0` and the speaker is still in `0.9.3-debian-10-r198`

https://github.com/bitnami/charts/commit/33521594e39bb59a48e9c00f6cfa473544c23a72

**To Reproduce**
N/A

**Expected behavior**
They should both be in 0.9.4

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. We will work on fixing it and release a new revision.

**Comment by champtar** [comment]
Fixed in https://github.com/bitnami/charts/commit/d2ebf588de92622bf6c8c4cc100297f8491c712d

**Comment by rchenzheng** [comment]
Thanks @javsalgar
