### ISSUE TITLE
[bitnami/node] extraEnv has wrong docs

### ISSUE THREAD

**Issue by samueldmq** [bitnami/charts#4076]
**Which chart**:
Node latest

**Describe the bug**
The docs say extraEnv is a {}, but it is a list in the following format:
- name: EXAMPLE_ENV
  value: 123

**To Reproduce**
Using the format from the docs results in error.

**Expected behavior**
Doc should be fixed.

**Version of Helm and Kubernetes**:

Not relevant.

**Additional context**
No additional info.

**Comment by carrodher** [comment]
Thanks for notifying us about that typo, I just created the above PR fixing the issue.
