### ISSUE TITLE
[bitnami/apache] Support extra env vars

### ISSUE THREAD

**Issue by samueldmq** [bitnami/charts#4078]
**Which chart**:
Apache latest.

**Is your feature request related to a problem? Please describe.**
For some apps, one might want to provide extra envvar, such as a URL to grab some data from.

**Describe the solution you'd like**
Allow for extraEnvVars (as per Moodle chart) or extraEnv (as per Node chart).

**Describe alternatives you've considered**
Support common vars (if they exist) via first-class variables? But still this would not cover the case I mentioned as motivation.

**Additional context**
N/A.

**Comment by dani8art** [comment]
Hi @samueldmq, I've just opened a PR that is adding this new feature, thank you so much for your feedback, please let's move the conversation there ;)
