### ISSUE TITLE
Pulumi / k8s error: chart "bitnami/node" not found in https://charts.bitnami.com/bitnami repository

### ISSUE THREAD

**Issue by dangersorus** [bitnami/charts#4089]
**Which chart**:
Node

**Describe the bug**
When attempting to pull the node chart via Pulumi CLI, it fails with the error output:

Diagnostics:
  pulumi:pulumi:Stack (azure-mean-azure-mean):
    Error: chart "bitnami/node" version "4.0.1" not found in https://charts.bitnami.com/bitnami repository
    (node:16674) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
    (Use `node --trace-warnings ...` to show where the warning was created)
    (node:16674) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)

    error: Error: Command failed: helm pull bitnami/node --untar --version 4.0.1 --destination /var/folders/ll/yjnk2rl11xl7snrrm363084w0000gn/T/tmp-16674E83oYuVy916S --repo https\://charts.bitnami.com/bitnami
    Error: chart "bitnami/node" version "4.0.1" not found in https://charts.bitnami.com/bitnami repository

**To Reproduce**

Using Pulumi to stand up a kubernetes cluster on Azure with CosmosDB. See here for tutorial and exact steps:
https://www.pulumi.com/docs/tutorials/azure/azure-ts-aks-mean/

1. pulumi stack init
2. pulumi config set azure:environment public
3. pulumi config set password --secret [your-cluster-password-here]
4. ssh-keygen -t rsa -f key.rsa
5. pulumi config set sshPublicKey < key.rsa.pub
6. az login
7. pulumi up

**Expected behavior**
    pulumi:pulumi:Stack azure-mean-azure-mean created
    ├─ azure:core:ResourceGroup aks created
    ├─ azure:ad:Application aks created
    ├─ azure:ad:ServicePrincipal aksSp created
    ├─ azure:ad:ServicePrincipalPassword aksSpPassword created
    ├─ azure:cosmosdb:Account cosmosDb created
    ├─ azure:containerservice:KubernetesCluster aksCluster created
    ├─ pulumi:providers:kubernetes aksK8s created
    ├─ kubernetes:core:Secret mongo-secrets created
    └─ kubernetes:helm.sh:Chart node created
    ├─ kubernetes:core:Service node-node created
    └─ kubernetes:extensions:Deployment node-node created

—outputs:— cluster : “aksclusterbfb9388b” frontendAddress: “40.76.25.71”

info: 12 changes performed: + 12 resources created Update duration: 14m33.922322098s

**Version of Helm and Kubernetes**:

- Output of `helm version`:

version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:52:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
I am aware that there is no version 4.0.1 of the node chart. I have tried replacing this with the latest chart version found via "helm search repo node" but that gives the same error.

**Comment by dani8art** [comment]
Hi @dangersorus I was looking at the repo and I found this version released, you can try with 

```console
$ helm repo update && helm pull bitnami/node --untar --version 4.0.1 --destination /tmp/tmp.jDlXAo4OWJ
$ ls -la /tmp/tmp.jDlXAo4OWJ/node/
total 44
drwxr-xr-x 4 bitnami bitnami  4096 Oct 26 16:25 .
drwx------ 3 bitnami bitnami  4096 Oct 26 16:25 ..
drwxr-xr-x 4 bitnami bitnami  4096 Oct 26 16:25 charts
-rw-r--r-- 1 bitnami bitnami   401 Oct 26 16:25 Chart.yaml
-rw-r--r-- 1 bitnami bitnami 11738 Oct 26 16:25 README.md
-rw-r--r-- 1 bitnami bitnami   327 Oct 26 16:25 requirements.lock
-rw-r--r-- 1 bitnami bitnami   229 Oct 26 16:25 requirements.yaml
drwxr-xr-x 2 bitnami bitnami  4096 Oct 26 16:25 templates
-rw-r--r-- 1 bitnami bitnami  3616 Oct 26 16:25 values.yaml
$ cat /tmp/tmp.jDlXAo4OWJ/node/Chart.yaml | grep version
version: 4.0.1
```

Do you know if you previously need to add this repo to your stack or even perform a `helm repo update` action?
