### ISSUE TITLE
[bitnami/tomcat] Allow custom env on tomcat container 

### ISSUE THREAD

**Issue by michaelbonadio** [bitnami/charts#4103]
**Which chart**:
tomcat 6.5.3

**Is your feature request related to a problem? Please describe.**
I need to include custom env variables in my tomcat container

**Describe the solution you'd like**
add a param `env` that can take custom env variables. Inject it's values as yaml under containers.env on the deployment. 
the stable tomcat helm chart allows this, see https://github.com/helm/charts/blob/master/stable/tomcat/templates/appsrv.yaml#L48

**Comment by dani8art** [comment]
Hi @michaelbonadio, thank you for your feedback, I've recently created a PR in order to implement your suggestion, please let's move the conversation there.
