### ISSUE TITLE
Add values.schema.json for Charts

### ISSUE THREAD

**Issue by RichiCoder1** [bitnami/charts#4104]
**Which chart**:
All Charts

**Is your feature request related to a problem? Please describe.**
Currently, there's no validation or feedback if values are misformed. The values documentation can also be inconsistent with the actual values expected.

**Describe the solution you'd like**
Provide a `values.schema.json` for Helm Charts.

**Additional context**
While this was prompted partial by values issue, it was also prompted by a new feature in Artifact Hub that generates a Values UI for charts that provide a values schema.

Example: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub (Click `Values Schema`)
Helpful Links:
* https://codeengineered.com/blog/2020/helm-json-schema/
* https://helm.sh/docs/topics/charts/#schema-files

Bitnami owns a _lot_ of charts, so I'm not expecting any crazy effort, but it'd be nice if this was an enforced thing moving forward.

**Comment by carrodher** [comment]
Thanks for letting us know, we agree that is a good-to-have feautere, in fact, we added this file to some of the Helm Charts in the past:

```console
$ find . -name 'values.schema*'
./spring-cloud-dataflow/values.schema.json
./jenkins/values.schema.json
./ghost/values.schema.json
./drupal/values.schema.json
./joomla/values.schema.json
./wordpress/values.schema.json
./rabbitmq/values.schema.json
./kubeapps/values.schema.json
./mongodb/values.schema.json
./postgresql/values.schema.json
./mariadb/values.schema.json
./mariadb-galera/values.schema.json
./redis/values.schema.json
./apache/values.schema.json
./nginx/values.schema.json
./redmine/values.schema.json
```

But as we are a small team with different priorities, we didn't continue adding them to the whole catalog. I just created an internal task to work on it, again I can't provide an exact ETA for this task as it is going to depend on other priorities and our bandwidth.

In the same way, PRs are welcome if you are interested in collaborating by adding this file to a specific asset.

**Comment by RichiCoder1** [comment]
Considering Bitnami has standardized and similarly structured values, I wonder if there's not some way to assist automating this too. I'll see if I can help at all!

**Comment by carrodher** [comment]
Thanks! I just added the on-hold label to prevent the stale bot from closing this issue

**Comment by nc-ruth** [comment]
Would be a really cool feature to have :) 
Hope it is still on a todo list in 2021 and soon in 2022 🥇

**Comment by carrodher** [comment]
Hi, it's still on our TO-DO list, although to be honest it is not on the top of the list, we have other priorities regarding the maintenance of the catalog and we are a small team.

Being said that, we will be happy to review any PR with this kind of contribution!

**Comment by carrodher** [comment]
Hi, unfortunately, this is not something on our roadmap for the short term. Due to other priorities, the team has and our capacity it is not possible to find bandwidth for this topic.
Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
