### ISSUE TITLE
redis.useAOFPersistence "yes" leaves both AOF and RDB enabled

### ISSUE THREAD

**Issue by larryzhu2018** [bitnami/charts#4107]
**Which chart**:
The name (and version) of the affected chart
redis-cluster
**Describe the bug**
it leaves both AOF and RDB enabled when setting redis.useAOFPersistence "yes" 
**To Reproduce**
set the value redis.useAOFPersistence yes 
check the disk usage that grows over time
look the file sizes
appendonly is 85G and dump.rdb is 44g in a few hours
```
lazhu@lazhu-mac helmfile % kubectl exec -n redis-cluster redis-cluster-1 -c redis-cluster -- ls -al /bitnami/redis/data 
total 127424888
drwxrwsr-x. 3 root 1001        4096 Oct 25 19:02 .
drwxrwxr-x. 3 root root          18 Oct 24 19:32 ..
-rw-r--r--. 1 1001 1001 85236392202 Oct 25 19:03 appendonly.aof
-rw-r--r--. 1 1001 1001 44558224851 Oct 25 19:02 dump.rdb
drwxrws---. 2 root 1001       16384 Oct 25 14:57 lost+found
-rw-r--r--. 1 1001 1001        7982 Oct 25 19:01 nodes.conf
-rw-r--r--. 1 1001 1001        3581 Oct 25 15:05 nodes.sh
-rw-r--r--. 1 1001 1001   688321570 Oct 25 19:03 temp-11136.rdb
```
**Expected behavior**
Please advise how to turn off dump.rdb

**Version of Helm and Kubernetes**:
helm version v2.16.7
k8s version: v1.17.9
- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
lazhu@lazhu-mac helmfile % kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"65bea96239d3fa3dc1d00f3407041719fc736fce", GitTreeState:"clean", BuildDate:"2020-07-30T12:20:29Z", GoVersion:"go1.13.9 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by juan131** [comment]
Hi @larryzhu2018 

There's no such a parameter (`redis.useAOFPersistence`) at https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml. It does exist in the https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/values.yaml though.

As you can see in the link below, that parameter is used to set the `REDIS_AOF_ENABLED` environment variable in the container. 

- https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/redis-statefulset.yaml#L139

That environment variable is defined in the image in script below:

- https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/6.0/debian-10/rootfs/opt/bitnami/scripts/redis-cluster-env.sh#L80

And it's used to set the "appendonly" property in Redis configuration, see:

- https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L378

However, it doesn't modify the default behaviour regarding RDB snapshotting. Please note that you can modify it using the `redis.configmap` parameter of the chart that allows adding additional Redis configuration to the nodes.
