### ISSUE TITLE
[bitnami/postgresql-ha] Log leaks password of repmgr user

### ISSUE THREAD

**Issue by enote-kane** [bitnami/charts#4112]
**Which chart**:
bitnami/postgresql-ha 5.1.0

**Describe the bug**
A new PostgreSQL HA setup leaks password for the "repmgr" user.

**To Reproduce**
1. Install helm chart

**Expected behavior**
Logs do not expose any passwords in plain text.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Excerpts from the log output of the primary initialization:
```
postgresql-repmgr 11:38:59.22 INFO  ==> Creating replication user repmgr
CREATE ROLE
...
postgresql-repmgr 11:38:59.28 INFO  ==> Creating repmgr user: repmgr
2020-10-26 11:38:59.293 GMT [170] ERROR:  role "repmgr" already exists
2020-10-26 11:38:59.293 GMT [170] STATEMENT:  CREATE ROLE "repmgr" WITH LOGIN CREATEDB PASSWORD 'my secret replication password';
ERROR:  role "repmgr" already exists
```

**Comment by dani8art** [comment]
Hi @enote-kane thank you so much for opening this issue, unfortunately, we were not able to see any password using the default option, could you share with us your configuration so that we can try to reproduce it, please?

**Comment by enote-kane** [comment]
In order to see any error output from SQL that is being executed, the debug logging mode needs to be active (which is another issue), so the easiest way to reproduce is:

```bash
helm install my-release --set postgresqlImage.debug=true bitnami/postgresql-ha
```

**Comment by marcosbc** [comment]
Hi @enote-kane, the purpose of `postgresqlImage.debug` is to be able to troubleshoot any issues with the image. In this case, the password is shown while debugging the command used to create the `repmgr` role, which I would say makes sense.

**Note that this option is not meant to be used in production**.

**Comment by enote-kane** [comment]
@marcosbc Sure, but still it will end up in the logs and the argument doesn't really hold, since for debugging it would have to printed for the very first `CREATE ROLE` attempt, not the second one that fails - if you really intend to print out the password. Also, in that regard it is highly inconsistent as no other password gets printed out in debug mode anywhere.

So if you are saying that printing out the password in debug mode is intentional, then please print it out explicitly. Relying on the fact that there are 2 attempts to create the same role and then have the password printed out as a result of printing out the PostgreSQL failed statement log is weird, to say the least.

The second attempt really should be guarded with a `SELECT` to avoid creating the same role twice. Simply put, seeing an error (even if it appears in debug-mode only) in the logs makes me tend to start an investigation what's wrong. However, nothing is wrong in this case.

**Comment by dani8art** [comment]
I agree with @marcosbc this `postgresqlImage.debug` is not meant to be used in production. 

However, I think you find a simple solution that could avoid this problem. 

> The second attempt really should be guarded with a SELECT to avoid creating the same role twice

Do you think you could handle a PR adding this check? It shouldn't be too complicated, the affected method is `repmgr_create_repmgr_user` maybe you could find a great solution and we will be so happy to review it and integrate.

https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/2937b70bb8568779834c9b92c773efacaf12d2e3/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L259-L270

Thank you so much for your feedback!
