### ISSUE TITLE
PostgreSQL extra user random password not saved on secrets

### ISSUE THREAD

**Issue by zauwn** [bitnami/charts#4120]
**Which chart**:
PostgreSQL

**Describe the bug**
If you set _postgresqlUsername_ but not _postgresqlPostgresPassword_  the secret with the passwords will only have 1 random password created instead of 2 (one for the postgres superuser and the other for the extra user)

This happens because of this logic in the templates/secrets.yaml:
```
data:
  {{- if and .Values.postgresqlPostgresPassword (not (eq .Values.postgresqlUsername "postgres")) }}
  postgresql-postgres-password: {{ include "postgresql.postgres.password" . | b64enc | quote }}
  {{- end }}
```

**To Reproduce**
1. Install the helm chart with the values 
```
postgresqlUsername: dbuser
postgresqlDatabase: dbname
```
2. run `kubectl get secrets postgresql -o yaml` and verify that there is only one key: postgresql-password when there should be another key: postgresql-postgres-password with the random password created for user dbuser.

**Expected behavior**
The secret should have 2 keys
- postgresql-password
- postgresql-postgres-password

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @zauwn ,
Thank you for reporting this issue, we are working with the above PR to address it.
Regards
