### ISSUE TITLE
[bitname/nginx] allow to configure http block

### ISSUE THREAD

**Issue by gajus** [bitnami/charts#4121]
**Which chart**:

nginx

**Is your feature request related to a problem? Please describe.**

I need to implement cookie based routing

https://serverfault.com/a/303572/82338

**Describe the solution you'd like**

I would like to configure a custom map

http://nginx.org/en/docs/http/ngx_http_map_module.html

**Describe alternatives you've considered**

N/A

**Additional context**

Need to be able to extend http block.

**Comment by dani8art** [comment]
Hi! thanks for your feedback, 

Did you try this https://github.com/bitnami/charts/tree/master/bitnami/nginx#providing-a-custom-server-block?

Especially in this section:

> you can also set an external ConfigMap with the configuration file

**Comment by gajus** [comment]
Unless I am not understanding the docs, the map can only bet set in the `http` block, and that's a config for `server` block.

**Comment by marcosbc** [comment]
Hi @gajus, you're right as it looks like the chart does not currently support overriding the entire NGINX configuration file (`nginx.conf`), which contains the `http` block.

To fix that there are a few options:

* Add support for overriding nginx.conf as a configmap, in the chart. Feel free to send a PR implementing this feature.
* Mount your custom nginx.conf via extraVolumes/extraVolumeMount.
* Overwrite nginx.conf in the Docker image (by extending bitnami/nginx).
* Overwrite the chart's `command` to replace the file and then start the web server (i.e. via `bash -c "sed -i 's/.../---/' /opt/bitnami/nginx/conf/nginx.conf; /opt/bitnami/scripts/entrypoint/run.sh"`)

**Comment by gajus** [comment]
I've gone with the workaround described in serverfault (that does not rely on `map`), but `extraVolumeMount` is a reasonable workaround here too.

**Comment by gajus** [comment]
@marcosbc By now I've used the `command` override trick many times. It would really handy to have a way to override `nginx.conf`.

**Comment by marcosbc** [comment]
Hi @gajus, in my [previous comment](https://github.com/bitnami/charts/issues/4121#issuecomment-721040121) I suggested some of the alternatives you could follow.

Note that the container already provides a way to override options in both the main `http` block (by mounting files in [`server_blocks`](https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.19/debian-10/rootfs/opt/bitnami/nginx/conf/nginx.conf#L41)) and in the main `server` block (by mounting files in the [`bitnami` folder](https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.19/debian-10/rootfs/opt/bitnami/nginx/conf/nginx.conf#L48)). The only thing you would need to do is specifying them in `extraVolumes`/`extraVolumeMount`.

In any case, if you think implementing a way to specify the `nginx.conf` file in the values or via `--set` could makes sense, feel free to send a PR! It could be a useful feature for many.

**Comment by khanh96le** [comment]
Hi @marcosbc, is your suggestion about "implementing a way to specify the nginx.conf file in the values or via --set" still valid for a PR? 
If so, I am happy to contribute

**Comment by carrodher** [comment]
Yes sure, if it's something that was not implemented during this time we will be happy to review any contribution implementing that feature
