### ISSUE TITLE
[bitnami/cassandra] pods do not start under Openshift 4.5 (via helm3)

### ISSUE THREAD

**Issue by GMerigo** [bitnami/charts#4125]
# Bitnami Cassandra cassandra-6.0.3

Installing the char with some common options under Openshift 4.5 fails. values.yaml attached.
[values-redacted.yaml.txt](https://github.com/bitnami/charts/files/5444052/values-redacted.yaml.txt). To simplify test, I reduced the stateful set to 1 pod.

**To Reproduce**
1. Compile a values.yaml like the attached one with some components (in this case gp2 storage and 2 cpu/4GB limits)
2. Run helm install cassandra -f values.yaml bitnami/cassandra
3. Pods go to CrashLoopBackOff
[cassandra-0.log](https://github.com/bitnami/charts/files/5444069/cassandra-0.log)

**Expected behavior**
The stateful set produces Running pods.

**Version of Helm and Kubernetes**:
Helm version: version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
Oc version: Client Version: openshift-clients-4.5.0-202006231303.p0-16-g3f6a83fb7 - Kubernetes Version: v1.18.3+2fbd7c7

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"3f6a83fb70bfe5c6ef0e0886923c90015a4256bc", GitTreeState:"clean", BuildDate:"2020-10-08T17:43:26Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-09T11:41:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I also tried to reduce limits/requirements but the result is the same. The pod gets scheduled on 32GB nodes that are currently empty in our lab.

**Comment by andresbono** [comment]
Hi @GMerigo, the issue seems the same than this one: https://github.com/bitnami/bitnami-docker-cassandra/issues/73. Can you take a look? Both users resolved the issue by modifying the resource limits. Which values did you try?

**Comment by GMerigo** [comment]
Thank you very much @andresbono - I realized now that the helm chart needed both these parameter sets to work:

```
jvm.extraOpts.maxHeapSize - currently set to 2048m
jvm.extraOpts.newHeapSize - also currently set to 2048m
[...]
resources.limits.memory - currently set to 4Gi
resources.requests.memory - also currently set to 4Gi
```

Unfortunately I'm not accustomed to vanilla kubernetes and as far as I know every JVM in Openshift automatically tunes itself based on Requirements and Limits of the pod, so I did not set my jvm options correctly.

Now the pod is running and I redeployed a sample cluster with three pods, and both from the cqlsh client and nodetool everything seems fine.
