### ISSUE TITLE
Copy/ paste is not working for SSH connection using "Apache Guacamole Certified by Bitnami" on AWS Marketplace

### ISSUE THREAD

**Issue by herveschweitzer** [bitnami/charts#4128]
I found other products based on Apache Guacamole, where the copy/paste inside a ssh session is working, but with the one from Bitnami it is not working.
I like your solution, but if you can't fix this issue, I have to choose another provider. 
And has it's working with other products based on Apache Guacamole, I think it should not so difficult to fix it.

Thanks in advance for your help

**Comment by dani8art** [comment]
I am sorry, but here we provide support for Bitnami Helm Charts and it seems you are not using any Bitnami Helm Chart.
It seems you are using a different Bitnami product, for that kind of assets we provide support in https://community.bitnami.com. Please, can you create the case in that forum? Thanks
