### ISSUE TITLE
Jenkins password secret is overwritten with incorrect password on helm upgrade

### ISSUE THREAD

**Issue by GraysonCAdams** [bitnami/charts#4131]
**Which chart**:
bitnami/jenkins LTS

**Describe the bug**
Whenever I run:

`helm upgrade -f values.yaml jenkins bitnami/jenkins --namespace jenkins`

I get the expected:

>\[...\]  
>  
>2. Login with the following credentials  
>  
>echo Username: user  
>  
>echo Password: $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-password}" | base64 --decode)

The issue is that every time I do a Helm upgrade, the output of that password command changes, as well as the dedicated `jenkins-password` secret. However, the original password from the first deployment is still the actual login credentials.

\---

What I am asking is, should the password be updating on every upgrade, or is that not actually the case and it telling me to login with the new credentials is just a limitation of Helm?.

**To Reproduce**
1. Deploy Jenkins with Helm `helm install my-release bitnami/jenkins`
2. Run `echo Password: $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-password}" | base64 --decode)`
3. Log in with the password to Jenkins
4. Upgrade Jenkins:  `helm upgrade my-release bitnami/jenkins`
5. Run `echo Password: $(kubectl get secret --namespace jenkins jenkins -o jsonpath="{.data.jenkins-password}" | base64 --decode)`
6. Note that the password has changed. Try logging in with the password, it will not work
7. Check Kubernetes jenkins.password secret and find it has also been overwritten with  the new, incorrect password
8. Log in with your original password from the first deployment, it will work
9. Try redeploying containers to see if they pull new secret, but they do not

**Expected behavior**
Either maintain the original password secret since that is the correct one, or actually override the old password with the new one.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @GraysonCAdams 

I saw you also commented at https://github.com/bitnami/bitnami-docker-jenkins/issues/51

We have a guide that explains why the passwords change during upgrades, and how to deal with that, see:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

Could you please take a look?

**Comment by aniketwdubey** [comment]
The issue occurs because the Helm chart defaults to `createSecret: true` and generates new random passwords on each upgrade. 

To fix this, you need to:
Set `createSecret: false` to prevent new secret generation
Specify `existingSecret` to use your existing admin credentials

```
helm upgrade my-release bitnami/jenkins -f values.yaml \
  --set controller.admin.createSecret=false \
  --set controller.admin.existingSecret=jenkins-admin-secret
```
