### ISSUE TITLE
[bitnami/postgresql-ha] Add support for existingSecret for pgpool

### ISSUE THREAD

**Issue by wataruian** [bitnami/charts#4138]
**Which chart**:
bitnami/postgresql-ha

It would be nice to set existing secret for pgpool admin password just like we can set the password for postgresql and repmgr

**Describe the solution you'd like**
Add support for existingSecret for pgpool just like the existing feature for `postgresql.existingSecret`

The idea was related to https://github.com/bitnami/charts/issues/4116

**Comment by dani8art** [comment]
I am sorry, but here we provide support for Bitnami Helm Charts and it seems you are not using any Bitnami Helm Chart.
It seems you are using a different Bitnami product, for that kind of assets we provide support in https://community.bitnami.com. Please, can you create the case in that forum? Thanks

**Comment by marcosbc** [comment]
Hi @wataruian, we encourage users to contribute to Bitnami charts via PRs, to implement features such as the one you mention. It is also the quickest way for requested features to be included, since we currently have a very limited bandwidth for performing such changes. Would you be open for it?
