### ISSUE TITLE
[bitnami/moodle] metrics not working

### ISSUE THREAD

**Issue by developerbuendata** [bitnami/charts#4140]
**Which chart**:
bitnami/moodle

**Describe the bug**
I have installed moodle using kubeapps following the wiki installation process you set in the wiki, 
I have set metrics.enable = true and the load balancer do not expose the port 9117

I did the same in bitnami/wordpress and it's working for bitnami/wordpress, but not working for moodle

**To Reproduce**
Install bitnami moodle with metrics.enable = true

**Expected behavior**
The load balancer shoud expose the 9117 port with apache-exporter metrics

**Comment by FraPazGal** [comment]
Hi @developerbuendata,

Thanks for opening this issue! It seems there is indeed an error in the chart and the service is not publishing the metrics sidecar port. I'll create a PR to address this.
