### ISSUE TITLE
[bitnami/postgresql] unable to mount pre-allocated disk volumes and file shares;    auto-create works but has wrong data lifecycle

### ISSUE THREAD

**Issue by ragatgen** [bitnami/charts#4143]
**Which chart**:
The name (and version) of the affected chart
https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#parameters

**Describe the bug**
After checking the logs and reproducing the situation, effectively the reported error message "mount failed: exit status 32" is part of a known situation creating a race condition between the linux kernel level and provisioning of the Azure File while
associating the POD/Statefulset with the respective PV/PVC."

**To Reproduce**

The easiest process to reproduce:
1) create a storage account and AZ file share in the same resource group as the AKS cluster  (RG should not matter if the K8S secret for the PV is correct)
2) create a PV for the AZ file share
3) create a secret for the PV to access the AZ file share
4) create a PVC for the PV
5) launch the “gitlab” helm chart with a PVC override for redis or postgresql or Prometheus.
 
Alternatively, feel free to look at and dissect the existing cluster in the RG “k8s-gitlab001”

**Expected behavior**
From CX 
My objective in this case is to find a working configuration for AZFile (CIFS share) that mounts on a StateFullSet on AKS with K8S 1.18. (we need the right incantations for storage admission, PV, PVC, PV-secret and StateFullSet).
 
At the moment, “errno=32” with available logs is not telling us root cause of issue
My objective in this case is to find a working configuration for AZFile (CIFS share) that mounts on a StateFullSet on AKS with K8S 1.18. (we need the right incantations for storage admission, PV, PVC, PV-secret and StateFullSet).
 
At the moment, “errno=32” with available logs is not telling us root cause of issue

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"964014daa6eaebac41a54a8e52906c3b7794c4af", GitTreeState:"clean", BuildDate:"2020-09-17T04:13:20Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
Add any other context about the problem here.

**Comment by ragatgen** [comment]
None of the below worked 👍 

effectively the reported error message "mount failed: exit status 32" is part of a known situation creating a race condition between the linux kernel level and provisioning of the Azure File while
associating the POD/Statefulset with the respective PV/PVC.
 
https://docs.microsoft.com/en-us/azure/storage/files/storage-troubleshooting-files-performance#throughput-on-linux-clients-is-significantly-lower-when-compared-to-windows-clients
 
In order to mitigate the situation the arguments for the mount Options should include "- nosharesock"
 
Here are direct examples
 
https://github.com/andyzhangx/demo/blob/master/pv/pv-azurefile-mountoptions.yaml
https://github.com/andyzhangx/demo/blob/master/pv/storageclass-azurefile-mountoptions.yaml

**Comment by andresbono** [comment]
Hi @ragatgen, were are you finding the error message `mount failed: exit status 32`?

> Alternatively, feel free to look at and dissect the existing cluster in the RG “k8s-gitlab001”

Note that we don't have access to the users's cloud resources, we (Bitnami) are just Chart providers.

**Comment by ragatgen** [comment]
Hi @andresbono please check the below:

Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    2m14s  default-scheduler  Successfully assigned gitlab/gitlab001-postgresql-0 to aks-gitlab001np-26684879-vmss000002
  Warning  FailedMount  2m13s  kubelet            MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-rd4f7e12038b84cbeb16e1f079d2ffa71.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  2m11s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r827c04d620a0453bb6a085f1075f6bc1.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  2m9s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r93dfa4d3c9fc4629b22d39cda269b6cf.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  2m7s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r3e984757d1a148309a7d2e63ec1fa6d6.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  2m3s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r3407539a7e4146acb6e67504d2360d55.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  114s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-ra0675d5a841f495b92efb91c38987bbf.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  98s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r458e1f6150d84e4da5d6cdd51d035a32.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  66s  kubelet  MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r981f42052e884863bb0012be2c768250.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  11s  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[dshm default-token-2clnw custom-init-scripts postgresql-password data]: timed out waiting for the condition
  Warning  FailedMount  1s   kubelet  (combined from similar events): MountVolume.SetUp failed for volume "gl-az-files-gitlab-postgresql-state-gitlab-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv --scope -- mount -t cifs -o cache=strict,gid=0,mfsymlinks,nosharesock,uid=0,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //abl02gitlab001sa.file.core.windows.net/gitlab-postgresql-state /var/lib/kubelet/pods/ee93fa02-6fed-4a6f-bfde-d1f2e7c33395/volumes/kubernetes.io~azure-file/gl-az-files-gitlab-postgresql-state-gitlab-pv
Output: Running scope as unit: run-r91a5be5c2edc4188a72a061d52d2fbd2.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

**Comment by ragatgen** [comment]
Hi @andresbono are there any inputs on this regards?

**Comment by andresbono** [comment]
Hi @ragatgen, I can only suggest that you go through this guide [Dynamically create and use a persistent volume with Azure Files in Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) in order to check if your Kubernetes cluster is compatible with Azure Files. In the guide you also have a Pod manifest (`mypod`) that you can use to verify the correct configuration of your storage provider.

**Comment by ragatgen** [comment]
closing

**Comment by ragatgen** [comment]
As per customer:

As stated in the original issue — the dynamic provisioning works.   The pre-allocated AZFILE+k8s_secret+PV+PVC does NOT work — for statefulset

Dynamic provisioning is NOT an option as the data lifecycle must be longer than the existence of a given AKS cluster or namespace

**Comment by ragatgen** [comment]
transfered to https://github.com/Azure/AKS/issues/1906

**Comment by andresbono** [comment]
Thanks for the clarification @ragatgen. It looks like https://github.com/Azure/AKS/issues/1906 is the same issue.
