### ISSUE TITLE
Harbor Helm not using released 2.1.1 image, even if released

### ISSUE THREAD

**Issue by mkuendig** [bitnami/charts#4144]
**Which chart**:
harbor

**Describe the bug**

Harbor Helm, values file doesn't use newest image for harbor-core service:

https://github.com/bitnami/charts/blob/master/bitnami/harbor/values.yaml#L17

lists 2.1.0, but 2.1.1 is used for other services and the image is available on dockerhub.

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @mkuendig ,
The `2,1,1` was released 23 hours ago, probably the CI did not has the time to take it. I will launch the CI jobs manually.
Thanks for the notification.
