### ISSUE TITLE
bitnami/harbor: oidc login fails (State mismatch)

### ISSUE THREAD

**Issue by mdekoster** [bitnami/charts#4154]
**Which chart**:
bitnami/harbor 8.1.1

**Describe the bug**
After upgrading to 8.1.1 OIDC login is failing with 'State mismatch'. See https://github.com/goharbor/harbor/issues/12910.

**To Reproduce**
Install the harbor chat 8.1.1 with OIDC feature (f.e. keycloak). Try to login with OIDC. After login at the OIDC provider, the redirect back to harbor shows the following error in the browser: `{"errors":[{"code":"BAD_REQUEST","message":"State mismatch"}]}-`

**Expected behavior**
OIDC login is successful and the harbor projects are shown.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"
```
- helm chart info
```
harbor  harbor     16              2020-10-26 09:43:41.220111473 +0000 UTC deployed        harbor-8.1.1    2.1.0
```

**Comment by miguelaeh** [comment]
Hi @mdekoster ,
From the threads you shared it seems to be an upstream issue. We will need to wait until it is fixed to release the new images.

**Comment by drewstinnett** [comment]
I think this is an issue with the bitnami chart, using _REDIS_URL instead of _REDIS_URL_CORE.  I tested out some changes in the above PR and that fixed things for me

**Comment by juan131** [comment]
Hi @drewstinnett 

Thanks so much for opening the PR, I just approved your changes, and merge the PR! I'll take a few hours for the chart to be released in the Bitnami charts repo.

Thanks again for your contribution!

**Comment by drewstinnett** [comment]
Glad to help, thank you for the awesome chart and quick approval, y'all rock! 😁
