### ISSUE TITLE
bitnami/harbor should support proxy cache settings

### ISSUE THREAD

**Issue by dubiety** [bitnami/charts#4160]
**Which chart**:

bitnami/harbor

**Describe the bug**

Harbor supports "proxy cache" since v2.1.1+.
Although bitnami adapted Harbor v2.1.1 since chart version 8.1.2, bitnami's Harbor chart cannot enable "proxy cache" in Harbor's "Project" page.

**To Reproduce**

0. Use bitnami/harbor chart version v8.1.2+
1. In Harbor web UI, create a "registry" with provider "Harbor" and endpoint URL "https://demo.goharbor.io"
2. In "Projects" page, click "+New Project" button
3. Fill in a "Project name", enable "proxy cache" and select the source we fill in in step 1. and click "OK"
4. Server replies "bad request: unsupported registry type harbor"

**Expected behavior**

Should be able to save the setting.

The root cause is in `harbor/templates/core/core-cm-envvars.yaml`, we need to add a environment variable:
`PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "docker-hub,harbor"` in the envvars.yaml configMap
This is how Harbor decide which registry type can be a source of proxy cache.

Form Harbor's official site, it only supports `docker-hub` and `harbor` as proxy cache source.

After adding `PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "docker-hub,harbor"` in the chart, I'm able to create proxy cache from either docker hub or Harbor.

**Version of Helm and Kubernetes**:

- Helm version: `v3.3.4`
- Kubectl version: 
  - client: `v1.18.8`
  - server: `v1.18.6`

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this, and also providing the solution.
  Would like to send a PR with the described changes ? We will be glad to review and merge them.

**Comment by dubiety** [comment]
Sure, will do. 👍
