### ISSUE TITLE
[bitnami/tomcat] Allow custom readiness/liveness Probes

### ISSUE THREAD

**Issue by michaelbonadio** [bitnami/charts#4165]
**Which chart**:
tomcat 6.6.0

**Is your feature request related to a problem? Please describe.**
readinessProbe and livenessProbes are hard coded, I would like to pass custom values

**Describe the solution you'd like**
Add path, port, initialDelaySeconds, timeoutSeconds, and periodSeconds/failureThreshold fields for readinessProbe and livenessProbes to the values.yaml, used in the deployment template instead of hard coding these values

**Comment by FraPazGal** [comment]
Hi @michaelbonadio ,

Thanks for using our chart! We are currently updating our charts and adding standardizations, and allowing for probes customisation is one of them. I can't give you an ETA at the moment but, if you want, please create a PR adding this feature. We would be happy to review and include it in our chart!

**Comment by michaelbonadio** [comment]
Will do! I'll drop a comment when the PR is up so you can review

**Comment by michaelbonadio** [comment]
@FraPazGal PR #4167 is up
