### ISSUE TITLE
Special character password with sentinel

### ISSUE THREAD

**Issue by sidinwillis** [bitnami/charts#4170]
**Which chart**:
bitnami/redis 11.2.3

**Describe the bug**
Password with special character not work in sentinel _Liveness_ and _Readiness_ step

```
Liveness probe failed: NOAUTH Authentication required. Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe. Warning: AUTH failed
```

**To Reproduce**

values.yaml
```
sentinel:
  enabled: true
  usePassword: true
```

And try with password:

```
password: "#ai%EQie!^i"
```

**Expected behavior**
Liveness and Readiness responding correctly.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @sidinwillis, thanks for reporting this. We've traced this back to a wrong usage of a `printf` in one of the Sentinel initialization scripts, it should be fixed by #4200.
