### ISSUE TITLE
[bitnami/kube-prometheus] how do i monitor "ALL NAMESPACES"?

### ISSUE THREAD

**Issue by encryptblockr** [bitnami/charts#4171]
Seems by default this prometheus operator is setup to monitor only the namespace it is deployed on

how do i monitor all namespaces? no documentation on this or example of how to set this up

**Comment by FraPazGal** [comment]
Hi @encryptblockr!

There is no option to monitor all namespaces by default, but you can use the envs `prometheus.xxxxxNamespaceSelector` to monitor the resources in those namespaces with specific labels.
