### ISSUE TITLE
[bitnami/kube-prometheus] CPU graph is not displaying

### ISSUE THREAD

**Issue by encryptblockr** [bitnami/charts#4172]
Why is CPU graph not showing ip?

![image](https://user-images.githubusercontent.com/35294766/97763243-6dfa0e00-1ae1-11eb-8d02-00f11c2d2c3e.png)

**Comment by juan131** [comment]
Hi @encryptblockr 

I guess you are using Grafana and some dashboard using the Prometheus instance deployed with the `bitnami/kube-prometheus` as database source. Could you please provide more information? 

- What dashboard are you using?
- How did you configure the data source in Grafana?
- What values did you use to install `bitnami/kube-prometheus` chart?
