### ISSUE TITLE
[bitnami/rabbitmq] GCP k8s does not support portforwarding

### ISSUE THREAD

**Issue by guyarb** [bitnami/charts#4174]
**Which chart**:
bitnami/rabbitmq:7.7.1

**Describe the bug**
Installing the chart on k8s in GCP does not support port forwarding due to wrong target port.

**To Reproduce**

1. install rabbitmq on GCP k8s cluster
2. go to services and ingress
3. go to the service of rabbitmq
4. in that page should appear port forward button for the port 5672
5. edit the yaml of the service, change the target port to 5672 instead of amqp.
6. go back to the page in 3
7. the button will appear

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @guyarb ,
Thank you for the comment, we will continue the thread in the PR.
