### ISSUE TITLE
metrics section in values-production.yaml should change master and slave to primary and secondary

### ISSUE THREAD

**Issue by middlestone** [bitnami/charts#4180]
in mariadb chart, statefuleset.yaml for primary and secondary has used keywords "primary" and "secondary" to refer to the parameters that user can set in values-production.yaml

DATA_SOURCE_NAME="root:${password_aux}@(localhost:3306)/" /bin/mysqld_exporter {{- range .Values.metrics.extraArgs.master }} {{ . }} {{- end }}

but values-production.yaml uses master and slave, they should be changed to primary and secondary. correct? 

extraArgs:
    master: []
    slave: []

**Comment by miguelaeh** [comment]
Thank you for reporting this, I will create a PR to fix it
