### ISSUE TITLE
[bitnami/nginx] allow to add a sidecar

### ISSUE THREAD

**Issue by gajus** [bitnami/charts#4186]
**Which chart**:

[bitnami/nginx]

**Is your feature request related to a problem? Please describe.**

We are using Cloudflare Argo Tunnel

The latter requires that we add `cloudflared` container as a sidecar to our HTTP server, which is nginx.

https://developers.cloudflare.com/argo-tunnel/create-tunnel/kubernetes-sidecar-model

**Describe the solution you'd like**

I would like to be able to append a custom [`containers` block](https://github.com/bitnami/charts/blob/5fe394b15e662566c26abb99735d03242c404907/bitnami/nginx/templates/deployment.yaml#L67).

**Describe alternatives you've considered**

Fork `bitnami/nginx`, which is far from ideal.

**Comment by gajus** [comment]
Apparently another option is to use Kustomize.

https://austindewey.com/2020/07/27/patch-any-helm-chart-template-using-a-kustomize-post-renderer/

**Comment by miguelaeh** [comment]
Hi @gajus,
Would you like to create a PR adding the sidecar? you can see how it is done in other charts like prestashop.

**Comment by gajus** [comment]
I actually like Kustomize approach. It solved my problem. Having tired Kustomize, I am not sure why would this need to be part of Helm chart.
