### ISSUE TITLE
Once I enable TLS, redis-cluster failed to be connected

### ISSUE THREAD

**Issue by drmy** [bitnami/charts#4188]
**Which chart**:
bitnami/redis-cluster

**Describe the bug**
The redis-cluster was running correctly in my lab, however once I enabled TLS with correct certificate, my client failed to connect to the cluster or failed to create a key, showing the following errors while all redis nodes started normally:

**Error occurred when starting application|StackExchange.Redis.RedisServerException: CLUSTERDOWN Hash slot not served**

**Comment by marcosbc** [comment]
Hi @drmy, could you share more information on how you deployed Redis? How did you create your certificate? Could you share the logs?

**Comment by drmy** [comment]
Hi @marcosbc ,

Sure. 

We used the redis-cluster and followed the guide to create a certificate secret and set it to certificatesSecret for use.

The problem is when tls is disabled everything works fine, just when tls is enabled then the client can make connection to redis however once I tried to creaete a key, it will show this error: CLUSTERDOWN Hash slot not served.


kubectl create secret generic redis-cluster-certs -n igt-floornet --from-file=ca.crt=ca_certificate.pem --from-file=tls.crt=server_certificate.pem --from-file=tls.key=server_key.pem

tls:
  enabled: true
  certificatesSecret: redis-cluster-certs

**Comment by dani8art** [comment]
Hi @drmy 

I think it is not possible to install the chert just with these values:

```console
$ helm install redis bitnami/redis-cluster \
>   --set tls.enabled=true \
>   --set certificatesSecret=certificates-tls-secret
Error: template: redis-cluster/templates/NOTES.txt:79:4: executing "redis-cluster/templates/NOTES.txt" at <include "redis-cluster.validateValues" .>: error calling include: template: redis-cluster/templates/_helpers.tpl:246:51: executing "redis-cluster.validateValues" at <fail>: error calling fail:
VALUES VALIDATION:
redis-cluster: TLSSecretMissingSecret
     A secret containing the certificates for the TLS traffic is required when TLS is enabled. Please set the tls.certificatesSecret valueredis-cluster: TLSSecretMissingCert
     A certificate filename is required when TLS is enabled. Please set the tls.certFilename valueredis-cluster: TLSSecretMissingCert
     A certificate filename is required when TLS is enabled. Please set the tls.certFilename valueredis-cluster: TLSSecretMissingCertKey
     A certificate key filename is required when TLS is enabled. Please set the tls.certKeyFilename valueredis-cluster: TLSSecretMissingCertCA
     A certificate CA filename is required when TLS is enabled. Please set the tls.certCAFilename value
```
I followed these steps and it works fine

**Create tls secret**

```console
$ curl -sSlO https://raw.githubusercontent.com/redis/redis/unstable/utils/gen-test-certs.sh && \
  chmod +x gen-test-certs.sh && \
  ./gen-test-certs.sh
$ kubectl create secret generic certificates-tls-secret --from-file=tls.crt=./tests/tls/redis.crt --from-file=tls.key=./tests/tls/redis.key --from-file=ca.crt=./tests/tls/ca.crt
```

**Deploy the chart**

```console
$ helm install redis bitnami/redis-cluster \
  --set tls.enabled=true \
  --set tls.certificatesSecret=certificates-tls-secret \
  --set tls.certFilename=tls.crt \
  --set tls.certKeyFilename=tls.key \
  --set tls.certCAFilename=ca.crt 
```

**Start a client**

```console
$ export REDIS_PASSWORD=$(kubectl get secret --namespace default redis-redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)
$ kubectl run --namespace default redis-redis-cluster-client --restart='Never' --env REDIS_PASSWORD=$REDIS_PASSWORD --image docker.io/bitnami/redis-cluster:6.0.9-debian-10-r0 --command -- sleep infinity
pod/redis-redis-cluster-client created
$ kubectl cp --namespace default ./tests/tls/redis.crt redis-redis-cluster-client:/tmp/client.cert
$ kubectl cp --namespace default ./tests/tls/redis.key redis-redis-cluster-client:/tmp/client.key
$ kubectl cp --namespace default ./tests/tls/ca.crt redis-redis-cluster-client:/tmp/CA.cert
```

```console
$ kubectl exec --tty -i redis-redis-cluster-client  --namespace default -- bash
```

```console
I have no name!@redis-redis-cluster-client:/$ redis-cli -c -h redis-redis-cluster -a $REDIS_PASSWORD --tls --cert /tmp/client.cert --key /tmp/client.key --cacert /tmp/CA.cert
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
redis-redis-cluster:6379>
```

**Comment by drmy** [comment]
Hi @dani8art ,

Actully I used a customized value file to install and in the file I did have the following items.

The problem is not at connection, It can connect to Redis with TLS enabled, but the problem is that when I try to add/set a key I then got the error: "CLUSTERDOWN Hash slot not served". 

It worked fine if I disable TLS.

tls:
  enabled: true
  certificatesSecret: redis-cluster-certs

  # Certificate filename
  certFilename: tls.crt
  #
  # Certificate Key filename
  certKeyFilename: tls.key
  #
  # CA Certificate filename
  certCAFilename: ca.crt
  #

**Comment by dani8art** [comment]
I'm also able to set keys,

```
redis-redis-cluster:6379> set hello world
-> Redirected to slot [866] located at 10.172.0.7:6379
OK
```

Maye, some of the other values could be producing the issue, could you share the entire `values.yaml`, please?

**Comment by drmy** [comment]
> I'm also able to set keys,
> 
> ```
> redis-redis-cluster:6379> set hello world
> -> Redirected to slot [866] located at 10.172.0.7:6379
> OK
> ```
> 
> Maybe some of the other values could be producing the issue, could you share the entire `values.yaml`, please?

Hi @dani8art .

It is working now. It turned out to be my TLS certificates issue.
I followed below link to re-generate a new set of certificate and it can work fine. Is this following instruction the official recommened way to create certificate files?

 https://github.com/redis/redis/blob/unstable/utils/gen-test-certs.sh


Thank you!
Drmy
