### ISSUE TITLE
[bitnami/postgresql-ha] How do I deploy the extension of pgagent 

### ISSUE THREAD

**Issue by zzguang520** [bitnami/charts#4192]
**Which chart**:
The name (and version) of the affected chart.
```[bitnami/postgresql-ha] ```

**Is your feature request related to a problem? Please describe.**
```
I have deployed the DB by helm,
helm install db-test bitnami/postgresql-ha -n postgresql \
    --set postgresql.replicaCount=3 \
    --set pgpool.useLoadBalancing=true
```

**Describe the solution you'd like**
```
I want to customize a job to execute some SQL regularly, I found that the pgagent extension could meet my request, but I didn't know how to deploy it,
I have tried to run : create extension pgagent, 
but the error was:
"ERROR:  could not open extension control file "/opt/bitnami/postgresql/share/extension/pgagent.control": No such file or directory SQL state: 58P01"
```

**Describe alternatives you've considered**

**Additional context**

**Comment by andresbono** [comment]
Hi @zzguang520, pgadmin is not included in the Bitnami postgresql/postgresql-repmgr container, that should be the reason you find that error message.

As you are in a Kubernetes environment, you might want to create a [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to execute the SQL code.

**Comment by musicmuthu** [comment]
Any solution for this issue

**Comment by musicmuthu** [comment]
@zzguang520 have you solved the plugin installation in this postgres image
