### ISSUE TITLE
[kube-prometheus] Prometheus instance not deployed if remoteRead is specified

### ISSUE THREAD

**Issue by alesanmed** [bitnami/charts#4194]
**Which chart**:
bitnami/kube-prometheus-2.2.2

**Describe the bug**
When I specify the remoteRead spec in the `values.yaml` the prometheus CRD is created but the stateful set is not deployed. If I upgrade the chart removing the remoteRead section (leaving `[]`) the prometheus sts is deployed. Then I can upgrade it again with the remoteRead section and nothing happens. Prometheus keeps deployed, but no reboot no nothing. The remote read config is grabbed because it sends the request to influxdb, but no data is shown.

**To Reproduce**

1. Deploy the chart with remoteRead configured
2. No prometheus instance is deployed
3. Upgrade chart to remove remoteRead config
4. Prometheus is deployed

**Expected behavior**
Prometheus should be deployed even if remote read is specificed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
  Can you provide an example on how you are setting `remoteRead` ? Maybe it could be a problem with the yaml

**Comment by alesanmed** [comment]
I'm so sorry, it was indeed a problem with the remote read. I duplicated the key `password`. But it didn't show any errors. Closing the issue.
