### ISSUE TITLE
Failed to upgrade to 3.3.0

### ISSUE THREAD

**Issue by Israphel** [bitnami/charts#4202]
**Which chart**:
redis-cluster 3.3.0

**Describe the bug**
I have the helm chart running on Rancher and I clicked on upgrade to 3.3.0, and this message appeared:

`Error encountered while creating appRevision The POST operation against AppRevision.project.cattle.io could not be completed at this time, please try again.: failed to install app redis-cluster. Error: invalid argument "/kustomize.sh" for "--post-renderer" flag: unable to find binary at /kustomize.sh: exec: "/kustomize.sh": stat /kustomize.sh: no such file or directory`

**To Reproduce**

1. Go to Apps
2. Click on redis-cluster
3. Scroll down to upgrade

**Expected behavior**
redis-cluster chart should be upgraded.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @Israphel, note that Bitnami only provides Helm charts, which can be installed easily via the "helm install" command (and upgraded with "helm upgrade"). Whether or not our charts can be installed via Rancher, the problem you are reporting seems to be related to a missing tool (kustomize) and I'd say it's an issue with your Rancher installation.

I'd recommend you to check with your organization's sysadmins in case they have any clue with respect to how your Rancher installation is configured, and to troubleshoot the error.

**Comment by Israphel** [comment]
Understood. I removed the chart and installed again. Upgrade failed, but clean installation worked, that's enough for me, thanks.
