### ISSUE TITLE
[bitnami/phabricator] Add option to enable SSH for GIT

### ISSUE THREAD

**Issue by VincentPost-TomTom** [bitnami/charts#4204]
**Which chart**: phabricator 9.1.8
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**
I want to use the ssh access to repositories that Phabricator offers.

**Describe the solution you'd like**
Add a switch to the helm chart values, that sets the environment variable for the phabricator container `PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY` to `yes` (or similar acceptable positive values). This could be integrated in the existing LoadBalancer definition.

**Additional context**
[Your docker image](https://github.com/bitnami/bitnami-docker-phabricator) already has the capability to run an SSH server for that purpose but there is no option in the helm chart to enable that.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this.
  I am opening a internal task to study it and implement the changes. However, we are small team and I can't give you an ETA.
  We will come back as soon as we have news. In any case, PR are welcome and we will be glad to review and merge them.
