### ISSUE TITLE
[bitnami/moodle] Cannot enable volumePermissions

### ISSUE THREAD

**Issue by michzimny** [bitnami/charts#4206]
**Which chart**:
bitnamie/moodle 9.0.x

**Describe the bug**
Setting `volumePermissions.enabled` to `true` causes a yaml-to-json-conversion error during `helm install/upgrade`.

**To Reproduce**

1. Download https://github.com/bitnami/charts/blob/master/bitnami/moodle/values.yaml
2. Run: `helm upgrade -i moodle bitnami/moodle --set volumePermissions.enabled=true --debug`
3. See error:

```
Error: YAML parse error on moodle/templates/deployment.yaml: error converting YAML to JSON: yaml: line 53: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 53: did not find expected key
YAML parse error on moodle/templates/deployment.yaml
```

**Expected behavior**

Based on [README](https://github.com/bitnami/charts/blob/master/bitnami/moodle/README.md) (search for `volumePermissions.enabled`), I would expect that `helm upgrade` succeeds with the volume-permission init-container enabled.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Thanks for reporting this, @michzimny. I've identified the bug so I will create a PR fixing it.
