### ISSUE TITLE
How to use these charts as dependencies

### ISSUE THREAD

**Issue by InsOpDe** [bitnami/charts#4208]
Im using the mongodb and rabbitmq chart as a dependency for my chart. Im passing the secrets like this
```yaml
rabbitmq:
  fullnameOverride: rabbitmq
  auth:
    username: rabbitmq
    existingPasswordSecret: rabbitmq-secret
```

and the secret config looks like this.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
{{- if $.Release.IsInstall }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
{{ else }}
  rabbitmq-password: {{ index (lookup "v1" "Secret" $.Release.Namespace "rabbitmq-secret").data "rabbitmq-password" }}
{{- end -}}
```

This way the passwords wont get overwritten when I Upgrade. But even if I do I get
```
Error: UPGRADE FAILED: template: the-kraken/charts/rabbitmq/templates/NOTES.txt:138:4: executing "the-kraken/charts/rabbitmq/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredRabbitmqPasswordErrors) "context" $)>: error calling include: template: the-kraken/charts/microservice-status-db/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.erlangCookie' must not be empty, please add '--set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE' to the command. To get the current value:

        export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace staging rabbitmq-secret -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
```

How would I generate and use dynamic secrets like I do without getting the error?
I dont want to just add a hardcoded `erlangCookie`-value to `values.yaml` as it would make the whole concept of secrets obselete.

Same problem goes with the mongochart

**Comment by InsOpDe** [comment]
Okay, just discovered rabbitmqs-chart-value `existingErlangSecret`. This should be sufficient

as for mongodb, after i updated the chart version from `8.3.0` to `9.3.1` it doesnt complain about the password-values not being present anymore, too.

**Comment by FraPazGal** [comment]
Hello @InsOpDe,

I'm glad you solved it! Feel free to open a new issue if you encounter any new problems!
