### ISSUE TITLE
[bitnami/rabbitmq] when enabling prometheusRule can not upgrade rabbitmq

### ISSUE THREAD

**Issue by muradheydarov** [bitnami/charts#4210]
**Which chart**:
7.5.7

**Describe the bug**
I want to enable prometheusRule I can not upgrade rabbitmq. I am getting this kind of error:

Error: UPGRADE FAILED: failed to create resource: PrometheusRule.monitoring.coreos.com "rabbitmq" is invalid: spec.groups: Invalid value: "null": spec.groups in body must be of type array: "null"

**My helm chart setting is:**

```
helm upgrade rabbitmq \
--version=7.5.7 \
--namespace rabbitmq \
--set auth.username=xxx \
--set auth.password=xxx \
--set auth.erlangCookie=secretcookie \
--set persistence.enabled=true \
--set persistence.storageClass=default \
--set persistence.accessMode=ReadWriteMany \
--set persistence.size=1Gi \
--set ingress.enabled=true \
--set ingress.hostname=hostname \
--set ingress.tls=true \
--set ingress.existingSecret=rabbitmq-tls \
--set metrics.enabled=true \
--set metrics.serviceMonitor.enabled=true \
--set metrics.serviceMonitor.namespace=monitoring \
--set metrics.prometheusRule.enabled=true \
--set memoryHighWatermark.enabled=true \
--set memoryHighWatermark.type="absolute" \
--set memoryHighWatermark.value="400MB" \
--set resources.limits.memory="800Mi" \
--set replicaCount=1 \
--set pdb.create=true \
bitnami/rabbitmq
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.2.4
```

- Output of `kubectl version`:

```
v1.18.5
```

**Comment by marcosbc** [comment]
Hi @muradheydarov, it seems like you could be either using an old deployment of Prometheus Operator that is incompatible with the RabbitMQ chart, or for the CRD to exist without it being used.

I would recommend you to upgrade your Prometheus Operator deployment. Note that you should be able to delete the CRD before re-installing, in case you get any error:

```
$ kubectl delete crd prometheuses.monitoring.coreos.com prometheusrules.monitoring.coreos.com
```

**Comment by muradheydarov** [comment]
> Hi @muradheydarov, it seems like you could be either using an old deployment of Prometheus Operator that is incompatible with the RabbitMQ chart, or for the CRD to exist without it being used.
> 
> I would recommend you to upgrade your Prometheus Operator deployment. Note that you should be able to delete the CRD before re-installing, in case you get any related error:
> 
> ```
> $ kubectl delete crd prometheuses.monitoring.coreos.com prometheusrules.monitoring.coreos.com
> ```

Thanks a lot. I will try upgrade my Prometheus Operator
