### ISSUE TITLE
The Bitnami Helper Tool

### ISSUE THREAD

**Issue by django23** [bitnami/charts#4214]
Hey all,

I would love to know if the The Bitnami Helper Tool (https://docs.bitnami.com/aws/how-to/understand-bnhelper/) is available on the Kubernetes Helm install. I have read the documentation and ways to install it, but when logging in on the server (via Docker and K8s) we have no user: 

`I have no name!@airflow-tools-rkctic2-web-7489cc75d8-mwdhz:/$ `

And also the path to is used:
`ls: cannot access '/opt/bitnami/bnhelper-tool': No such file or directory`

So, is there a possibility to install it, or did you maybe hide the tool somewhere :)?

I forgot to add that I am talking about:
https://github.com/bitnami/charts/tree/master/bitnami/airflow

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, the bnhelper tool it is not included in our containers. It purpose is only for VMs not for containers scenarios.
