### ISSUE TITLE
[bitnami/postgresql] Need superuser

### ISSUE THREAD

**Issue by max3903** [bitnami/charts#4216]
**Which chart**:
postgresql
9.x.x

**Is your feature request related to a problem? Please describe.**
I am using Odoo chart with PostgreSQL as a dependency:
https://github.com/ursais/odoo-template/tree/12.0-openshift/helm/odoo

Some Odoo modules require extensions (like pg_trgm, postgis, etc) to be installed in PostgreSQL.

The postgresqlUsername ("odoo") is not a superuser and cannot install extensions.

**Describe the solution you'd like**
I am open to any solution. Less lines, the better.

**Describe alternatives you've considered**
For local development using docker, we found a way to alter the user through a script:
https://github.com/ursais/odoo-template/blob/12.0-openshift/docker-compose.yml#L13

**Comment by miguelaeh** [comment]
HI @max3903 ,
Thank you for opening this issue.
I have found the following thread about it: https://www.postgresql.org/message-id/h6blkum78rldsrvihgeng2n3.1468471039937%40email.android.com
So it seems we have two options here:
1.- Add a way to provide the necesary privileges to the odoo user, having in mind that there will be a limitation with scalar types.
2.- Create the Odoo user as superuser, that we will need to evaluate the impact of this.

Let's check if @rafariossaa or @juan131 have any other better idea.
Regards

**Comment by rafariossaa** [comment]
Hi,
  First of all,  @max3903 Do you have the list of modules needed ? Maybe some of them are missing in our current postgresql container image.
  I think the best approach is to use the initscripts in postgresql. In the link @miguelaeh provided says that the needed extensions can be added to `template1`, we can explore this. 
  IMHO, giving odoo user superuser privileges is not a good idea, a security issue in oddo can put in risk all your database.

**Comment by max3903** [comment]
Hello @rafariossaa @miguelaeh 

Thank you for your answers. We mostly use pg_trgm, postgis and postgis_topology.

I don't mind installing the extensions in `template1` (even if they may not be used), but my main problem is how to do it during the helm installation of PostgreSQL as a dependency of Odoo?

Thanks.

**Comment by miguelaeh** [comment]
Hi @max3903 ,
Sorry for the delay, it seems we missed this ticket.
To do it at the Helm installation, as @rafariossaa is suggesting you can give a try to this: https://github.com/bitnami/charts/blob/ebc07b91528b63bc9ecec155cdfc7cf1cf52fbcf/bitnami/postgresql/values.yaml#L232

Just add a section in your values.yml for postgresql and add there the postgresql parameters, in this case the `initdbScripts` parameter.
Regards.

**Comment by max3903** [comment]
@miguelaeh Thank you. I will try this and close this issue after.
