### ISSUE TITLE
kube-prometheus: Missing AlertmanagerConfig CRD and clusterrole permissions

### ISSUE THREAD

**Issue by hwoarang** [bitnami/charts#4220]
**Which chart**:
bitnami/kube-prometheus-2.2.3

**Describe the bug**
Using the latest kube-prometheus-2.2.3, we observe the following problems in the operator's output

`E1105 09:55:43.496899       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1alpha1.AlertmanagerConfig: failed to list *v1alpha1.AlertmanagerConfig: alertmanagerconfigs.monitoring.coreos.com is forbidden: User "system:serviceaccount:kube-monitoring:prometheus-operator-operator" cannot list resource "alertmanagerconfigs" in API group "monitoring.coreos.com" at the cluster scope`

**To Reproduce**
Deploy bitnami/kube-prometheus-2.2.3

**Expected behavior**
The AlertmanagerConfig CRD should exist and the clusterole should that the correct permissions to manage it.

**Additional context**
Prometheus operator 0.43.0 introduced a new AlertmanagerConfig CRD
https://github.com/prometheus-operator/prometheus-operator/blob/master/CHANGELOG.md#0430--2020-10-26

> This release introduces a new AlertmanagerConfig CRD that allows to split the Alertmanager configuration in different objects. For now the CRD only supports the PagerDuty, OpsGenie and webhook receivers, other integrations will follow in future releases of the operator. The current version of the CRD is v1alpha1 meaning that testing/feedback is encouraged and welcome but the feature is not yet considered stable and the API is subject to change in the future.

However, this CRD does not exist in the bitnami chart which also misses the related clusterole permissions.

**Comment by juan131** [comment]
Thanks @hwoarang for reporting the issue!!! I just created a PR to update the CRDs
