### ISSUE TITLE
[bitnami/rabbitmq] Add Load definition in values.yaml. Can't auth as user management portal.

### ISSUE THREAD

**Issue by luddskunk** [bitnami/charts#4222]
Hello,

I am using the Helm chart to setup my RabbitMQ cluster. However, I try to add additional policies to the chart in my values.yaml file.

What I do is follow the link as specified in the [documentation](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions).

My values file look like the provided [values template](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml).

With the addition of following: 

```
#Optionally specify extra secrets to be created by the chart.
#This can be useful when combined with load_definitions to automatically create the secret containing the definitions to be loaded.
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "queue-mirroring-two",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "exactly",
              "ha-params": 2
            }
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```

What happens is that when I install the Helm chart, I can see it from the pod that `rabbitmqctl list_policies` that I achieve the setting of this. But my User is wiped and I can no longer login to the management portal with provided password from `kubectl get secret --namespace rabbitmq rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)`

Can anyone tell me what's missing for adding policies and want to be able to login in to the management portal?

**Comment by TimVosch** [comment]
Hi,

I don't think it has something to do with your edit. Simply installing the default chart does not work as well. I assume something chaged in the auth mechanism that the chart does not reflect yet. I am going to try and downgrade  version to see if that works.

-Tim

**Comment by luddskunk** [comment]
Hi,

Auth works fine with `values.yaml`, the user: `user` and the password found with `kubectl get secret --namespace rabbitmq rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode` for me.

I use chart version 7.7.1.

BR

**Comment by andresbono** [comment]
Hi @luddskunk, we can reproduce your issue. It looks like the first start of the pod doesn't finish properly and the container crashes before the user password is properly configured. Then the pod restarts and keeps an undefined password. That's my first assumption, we will investigate it further.

**Comment by andresbono** [comment]
Hi @TimVosch, please feel free to open a new issue if you need help or you find bugs that are not tightly related to this one.

**Comment by andresbono** [comment]
Hi @luddskunk, we haven't found the cause of the issue yet. I have created an internal task to further investigate it. Please let us know if you have any new clues about what is going on.

**Comment by luddskunk** [comment]
> Hi @luddskunk, we haven't found the cause of the issue yet. I have created an internal task to further investigate it. Please let us know if you have any new clues about what is going on.

Hello,

Unfortunately not. I am using the config quite untouched. Glad to hear you're working on it, let me know if you find you find the root cause for this.

Thanks!

**Comment by cheskayang** [comment]
I'm experiencing the same issue with release v8.6.2.

As long as the load definition is added in the yaml file, the user gets removed.

when calling `rabbitmqctl list_users`, an empty result is returned

**Comment by andresbono** [comment]
This is still work in progress, I'm raising the priority right now. If you are providing a load definition, you will probably need to specify the authentication in that load definition:

```
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
```

**Comment by esteban1983cl** [comment]
> Hello,
> 
> I am using the Helm chart to setup my RabbitMQ cluster. However, I try to add additional policies to the chart in my values.yaml file.
> 
> What I do is follow the link as specified in the [documentation](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions).
> 
> My values file look like the provided [values template](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml).
> 
> With the addition of following:
> 
> ```
> #Optionally specify extra secrets to be created by the chart.
> #This can be useful when combined with load_definitions to automatically create the secret containing the definitions to be loaded.
> extraSecrets:
>   load-definition:
>     load_definition.json: |
>       {
>         "vhosts": [
>           {
>             "name": "/"
>           }
>         ],
>         "policies": [
>           {
>             "name": "queue-mirroring-two",
>             "pattern": ".*",
>             "vhost": "/",
>             "definition": {
>               "ha-mode": "exactly",
>               "ha-params": 2
>             }
>           }
>         ]
>       }
> loadDefinition:
>   enabled: true
>   existingSecret: load-definition
> extraConfiguration: |
>   load_definitions = /app/load_definition.json
> ```
> 
> What happens is that when I install the Helm chart, I can see it from the pod that `rabbitmqctl list_policies` that I achieve the setting of this. But my User is wiped and I can no longer login to the management portal with provided password from `kubectl get secret --namespace rabbitmq rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)`
> 
> Can anyone tell me what's missing for adding policies and want to be able to login in to the management portal?

Working on chart version 8.6.0

**Comment by nodesocket** [comment]
When attempting to use `loadDefinition` I still don't think the password is being set correctly. I see authentication failed in the pod logs for user `johndoe`.

```
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
```

Here is my Secret definition:

```json
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "permissions": [
        {
          "configure": ".*",
          "read": ".*",
          "user": "johndoe",
          "vhost": "/",
          "write": ".*"
        },
        {
          "configure": ".*",
          "read": ".*",
          "user": "johndoe",
          "vhost": "maximus",
          "write": ".*"
        }
      ],
      "vhosts": [
        {
          "limits": [],
          "metadata": {
            "description": "Default virtual host",
            "tags": []
          },
          "name": "/"
        },
        {
          "limits": [],
          "metadata": {
            "description": "",
            "tags": []
          },
          "name": "maximus"
        }
      ]
    }
```

**Comment by carrodher** [comment]
What version of the chart are you using? It should be solved in https://github.com/bitnami/charts/pull/5939

**Comment by nodesocket** [comment]
@carrodher thanks for the reply. I am using version `8.11.9`.

**Comment by nodesocket** [comment]
@carrodher I am installing the chart from scratch each time during testing.

My understanding is the load_definition.json I provide should just append to the default config already created, thus no need to provide users again right?

```
  auth:
    username: johndoe
    existingPasswordSecret: rabbitmq-password
    existingErlangSecret: rabbitmq-password
 ```

And my custom `load_defition.json` creates a new vhost and sets permissions for that new vhost:

```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "permissions": [
        {
          "configure": ".*",
          "read": ".*",
          "user": "johndoe",
          "vhost": "/",
          "write": ".*"
        },
        {
          "configure": ".*",
          "read": ".*",
          "user": "johndoe",
          "vhost": "maximus",
          "write": ".*"
        }
      ],
      "vhosts": [
        {
          "limits": [],
          "metadata": {
            "description": "Default virtual host",
            "tags": []
          },
          "name": "/"
        },
        {
          "limits": [],
          "metadata": {
            "description": "",
            "tags": []
          },
          "name": "maximus"
        }
      ]
    }
```

**Comment by nodesocket** [comment]
It appears that when using a custom `load_definition.json` the default user/password specific in the Helm chart is NOT created as expected.

```
2021-05-11 00:23:53.399 [info] <0.659.0> Applying definitions from file at '/app/load_definition.json'
2021-05-11 00:23:53.399 [info] <0.659.0> Asked to import definitions. Acting user: rmq-internal
2021-05-11 00:23:53.400 [info] <0.659.0> Importing concurrently 2 vhosts...
2021-05-11 00:23:53.400 [info] <0.659.0> Importing concurrently 2 permissions...
2021-05-11 00:23:53.401 [warning] <0.654.0> Failed to set permissions for 'johndoe': the user does not exist
2021-05-11 00:23:53.401 [warning] <0.655.0> Failed to set permissions for 'johndoe': the user does not exist
````

**Comment by carrodher** [comment]
Can you try setting the user in the load_definition? According to the [README.md](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-custom-definitions):
> Loading a definition will take precedence over any configuration done through Helm values.

**Comment by nodesocket** [comment]
@carrodher that worked setting:

```
users": [
        {
          "name": "johndoe",
          "password": "supersecrethere",
          "tags": "administrator"
        }
      ],
```

In the `load_definition.json`. That's a bit counterintuitive, I wish the documentation made that a bit more clear that the username and password specified in the chart WILL NOT be created if you provide a custom load definition.

**Comment by carrodher** [comment]
Yes, I agree with that. Since you faced the issue, would you like to contribute to the README? If not I will do it of course, but probably as you feel the frustration produced by this topic you will be able to write what you would have liked to read
