### ISSUE TITLE
Zookeeper is not working in values-production.yaml

### ISSUE THREAD

**Issue by Venkatesh-Ravva** [bitnami/charts#4225]
we have deployed kafka using helm chart version 11.8.6. 
Values-production.yaml file in kafka is working fine.
but we are unable to use  the values-production.yaml file in zookeeper. Neither its showing logs while deployed . Getting Crashloopbackoff issue.
![image](https://user-images.githubusercontent.com/5158816/98280108-e28ceb00-1fc0-11eb-930c-8511eda19187.png)

![image](https://user-images.githubusercontent.com/5158816/98280151-f9334200-1fc0-11eb-8626-bb3e9abe088c.png)

**Comment by dani8art** [comment]
Hi @Venkatesh-Ravva If you are using `values-production.yaml` that enables `tls` support for client connection you have to mount your TLS configuration using `extraVolumes` and `extraVolumeMounts`, you can take this example to start playing: [values.yaml ](https://github.com/bitnami/charts/blob/0fa85d1a7f3a2ee9c19731d2455efca38e783b52/bitnami/zookeeper/values.yaml#L72)

Otherwise, you can also disable the tls configuration:

```console
--set service.tls.client_enable=false,service.tls.quorum_enable=false,service.tls.disable_base_client_port=false
```

Thanks

**Comment by timfeirg** [comment]
suggestion: change title to "zookeeper crashes without any error log when tls certificates is not mounted" or sth like that. @Venkatesh-Ravva 

I've made a PR in attempt to make the debug process somewhat easier: https://github.com/bitnami/bitnami-docker-zookeeper/pull/44, could you take a look at it? this repo seems to be managed by bots. @dani8art

**Comment by dani8art** [comment]
I think a colleague, already reviwed it. 

Could you add more info to reproduce the issue? did you provide TLS files?

**Comment by timfeirg** [comment]
> did you provide TLS files?

I didn't, and i understand now zookeeper cannot start with this setup, but it was difficult to debug and let to this conclusion because there's no relevant error logs pointing to this direction.

**Comment by dani8art** [comment]
You can add `image.debug=true` I don't know if that could help you to debug a bit more.

**Comment by timfeirg** [comment]
there's no other way to enable `set -x` inside scripts, see https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/zookeeper/setup.sh#L8

**Comment by marcosbc** [comment]
Related PR: https://github.com/bitnami/bitnami-docker-zookeeper/pull/44
