### ISSUE TITLE
Document how to transition from official Cassandra chart

### ISSUE THREAD

**Issue by xaocon** [bitnami/charts#4226]
**Which chart**:
Cassandra (current is 6.0.6 but version shouldn't matter here)

**Is your feature request related to a problem? Please describe.**
I'd like to start using this chart but we started off with the helm-incubator Cassandra chart. I'd like this for Cassandra specifically but I think it would be smart to have instructions for most infra that has an "official" chart in the Helm org. In best case scenarios it could be just values that would need to be put in to quickly uninstall the old chart and start using the same storage from the old chart in the new chart. There could also be instructions for how to spin up the Bitnami chart in tandem with the original chart and transition data as seamlessly as possible.

**Describe the solution you'd like**
Just a topic in the README with documentation for how to move from the "official" charts or most used charts. Could help a lot with adoption of Bitnami product.

**Describe alternatives you've considered**
Google how to do it? There are a couple of options here but having something that was up to date and specific to Bitnami charts would be great.

**Additional context**
N/A, I think the idea of the request is pretty straightforward, even if implementation may not be in all cases.

**Comment by FraPazGal** [comment]
Hi @xaocon,

Thanks for bringing this up! It is a really interesting idea and something we are investigating (see this PR https://github.com/bitnami/charts/pull/4215 that has the objective of smoothing the transition from `stable/fuentd` to our chart). That been said, we are a small team and keeping an up-to-date section for each of our charts would be a fairly big enterprise. Another potential problem would be deciding which is the "most popular" chart of a specific asset to create the guide for. Although it is indeed a potential way to attract new users, there are also some drawbacks that we need to keep in mind.

Nevertheless, I agree that such a section would be a great addition to our README and something that the team will evaluate. We also accept any contribution for our users and we would be happy to review and include any PR including said section in our charts!

**Comment by xaocon** [comment]
Hi @FraPazGal,

Thanks for the detailed write up. I certainly realize that solving this documentation issue is a far bigger problem than this small and very general issue makes it seem, but I thought it was worth bringing up anyways.

Feel free to close this if you don't think it's helpful to your team but I think having this as a general goal is worth it to the community and, because I think it would allow other groups to transition to your product more easily, probably worth it to your organization. I'll probably look into how to do this either way so if you leave this open I may have a PR with at least some basic instructions / things to think about at some point in the coming weeks.

You guys would probably want to think about whatever language you'd want included that points out that the instructions are intended to be a guide and not a working step by step manual, since everyones setup will be different and source and destination charts will be in flux.

**Comment by FraPazGal** [comment]
Hi @xaocon,

Indeed, leaving aside whether we can add and maintain these section to our READMEs, I agree that it would be a good goal to work towards. Regarding the language, I think that having a general notice warning about the section being a guide should be enough. 

Again, thanks for opening this discussion and we look forward to the PR!

**Comment by rafariossaa** [comment]
Hi @xaocon 
  I am closing this issue to not have too many opened issues. Please, even if I close it, put a comment here when you have your PR, or just send your PR referring to this issue. We will be glad to review and merge it.
 Thanks
