### ISSUE TITLE
[bitnami/postgresql-ha] pgpool-service is missing component-label

### ISSUE THREAD

**Issue by stoetti** [bitnami/charts#4230]
**Which chart**:
postgresql-ha

**Is your feature request related to a problem? Please describe.**
We need to find the pgpool-service using labels but the label app.kubernetes.io/component is not present on the pgpool-service. Neither is any other label available which uniquely identifies the service.

**Describe the solution you'd like**
Add a lable similar to the label added to the postgresql-service, e.g. app.kubernetes.io/component: postgresql

**Describe alternatives you've considered**
Another possibility would be to add a parameter "pgpool.serviceLabels" which than can be rendered into the service-template.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this feature. 
  I have created a PR to add it. Would you like to take a look to the PR ?

**Comment by stoetti** [comment]
Hi,

the PR looks good.
But is there a reason that the pgpool-service is not getting the 'component'-label as it is assigned for the postgresql-service itself?

**Comment by marcosbc** [comment]
@stoetti I added your comment to the PR, so @rafariossaa can check it whenever he has a chance.
