### ISSUE TITLE
Canvas lsm not finding execution file for window/virtual machines

### ISSUE THREAD

**Issue by mina20** [bitnami/charts#4246]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by carrodher** [comment]
I am sorry, but here we provide support for Bitnami Helm Charts and it seems you are not using any Bitnami Helm Charts.
It seems you are using a different Bitnami product, for that kind of asset we provide support in https://community.bitnami.com. Please, can you create the case in that forum? Thanks
