### ISSUE TITLE
[bitnami/rabbitmq] typo in headless service's tlsPortName

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#4305]
**Which chart**:
bitnami/rabbitmq (7.8.0+)

**Describe the bug**
Chart failed to deploy when enabling tls with error

```
Error: Service "rabbitmq-headless" is invalid: spec.ports[2].name: Required value
```

**To Reproduce**

1. enable auth.tls.enabled
2. deploy

**Expected behavior**
Successful deployment

**Additional context**

Due to typo here (TlsPortName instead of tlsPortName)

https://github.com/bitnami/charts/blob/cb78541495008b3ebc77473a0e526c11b606506d/bitnami/rabbitmq/templates/svc-headless.yaml#L17

**Comment by alemorcuq** [comment]
Thanks for reporting this, @tbnguyen1407. I've created a PR to fix it.

**Comment by javsalgar** [comment]
It seems that the PR was merged, so I'll close the issue.
