### ISSUE TITLE
[bitnami/wordpress] connect to external database via unix domain socket

### ISSUE THREAD

**Issue by kriptor** [bitnami/charts#4306]
Hi,

I'm trying to use proxysql sidecar for database connection and would like to connect to it via unix domain socket `/sockets/proxysql.sock`. What should the configuration look like to achieve this?

Wordpress works if I manually set `define( 'DB_HOST', 'localhost:/sockets/proxysql.sock' );` in `wp-config.php`, but I just can't make this work by configuring the chart:
```
externalDatabase:
    host: localhost:/sockets/proxysql.sock
```
If I use ^^ then chart initialisation just hangs on
`mysql-c INFO  Trying to connect to MySQL server`

Thx

**Comment by dani8art** [comment]
Hi @kriptor, 

You have to take into account during the initialization `mysql-client` tries to connect to the database too, so you should need to ensure that `localhost:/sockets/proxysql.sock` is reachable by this client or `myslq-client` support this connection string. 

Thanks!

**Comment by kriptor** [comment]
@dani8art thx for your reply!

I understand that some init code is trying to check whether the db is reachable. By the time this operation is performed the socket should be ready and listened to by proxysql... I know proxysql starts very quickly but I guess there's still a possibility of race condition. What I suspect is, that this init process might not be configuring mysql-client correctly (namely, to use `-S` instead of `-h` and `-P`)... could you maybe point me in the direction of this code which is performing this db check as well as the code which is doing the wp-config.php configuration/env-variable-substitution... I can't seem to find it.

Thx

**Comment by kriptor** [comment]
I managed to find a workaround ...
I set up host and port for external database, but then overwrite the DB_HOST define in post init script.

I created ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-post-init-scripts
data:
  set_db_host.sh: |
    #!/bin/sh
    DB_HOST_VALUE="localhost:/sockets/proxysql.sock"
    WP_CONFIG_FILE="/bitnami/wordpress/wp-config.php"

    echo "Setting DB_HOST inside ${WP_CONFIG_FILE} to '${DB_HOST_VALUE}' ..."
    sed -i -E "s|'DB_HOST', '.+?'|'DB_HOST', '${DB_HOST_VALUE}'|" "${WP_CONFIG_FILE}"
```

and mount it to container
```
extraVolumes:
  - name: wordpress-post-init-scripts
    configMap:
      name: wordpress-post-init-scripts

extraVolumeMounts:
  - name: wordpress-post-init-scripts
    mountPath: /docker-entrypoint-init.d
```

and it works:
```
wordpress INFO  ==> Sourcing /docker-entrypoint-init.d/..2020_11_11_15_15_31.306446636/set_db_host.sh as it is not executable by the current user, any error may cause initialization to fail
wordpress Setting DB_HOST inside /bitnami/wordpress/wp-config.php to 'localhost:/sockets/proxysql.sock' ...
wordpress [Wed Nov 11 15:16:30.555114 2020] [mpm_event:notice] [pid 71:tid 139771443932032] AH00489: Apache/2.4.46 (Unix) configured -- resuming normal operations
```

**Comment by dani8art** [comment]
Hi @kriptor, a really nice solution! happy to see that worked. Thank you so much for your feedback!

**Comment by kriptor** [comment]
Hey @dani8art,

I just found out...

My hack still works, but unfortunately only for initial start. If wordpress container gets restarted for some reason, it then keeps failing with:
`Error executing 'postInstallation': "port" option should be >= 0 and < 65536: /sockets/proxysql.sock`

It would be really great if there was a proper mysql unix socket support.

**Comment by miguelaeh** [comment]
Hi @kriptor ,
What if you run those commands from the container command instead of in the configmap? Have in mind you will also need to modify it to run the current command after yours to start.
