### ISSUE TITLE
[bitnami/tomcat] Allow custom common labels

### ISSUE THREAD

**Issue by michaelbonadio** [bitnami/charts#4314]
**Which chart**:
tomcat 7.0.0

**Is your feature request related to a problem? Please describe.**
No option to add custom labels. 

**Describe the solution you'd like**
Add commonLabels value to allow custom labels to be passed to tomcat. A couple charts already do this, such as https://github.com/bitnami/charts/tree/master/bitnami/airflow

Not sure if this works with the helper function to define "tomcat.labels", airflow chart seems to avoid using their method

**Comment by alemorcuq** [comment]
I agree this would be nice to have, @michaelbonadio. Thanks for making a PR to implement it!
