### ISSUE TITLE
3rd party libraries cannot import inside plugins

### ISSUE THREAD

**Issue by MarlonAbeykoon** [bitnami/charts#4337]
**Which chart**:
airflow 6.5.1

**Describe the bug**
Installed the 3rd party libraries (Django, sentry etc) by mounting a requirement.txt as explained in the documentation but cannot import them in plugins scripts (custom operators).
Following is the error I get,

> 2020-10-29T07:53:46.94455538Z [2020-10-29 07:53:46,942] {dagbag.py:259} ERROR - Failed to import: /opt/bitnami/airflow/dags/git/key_value_aggregator_sync.py
> 2020-10-29T07:53:46.944572943Z Traceback (most recent call last):
> 2020-10-29T07:53:46.944578904Z   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 256, in process_file
> 2020-10-29T07:53:46.944584647Z     m = imp.load_source(mod_name, filepath)
> 2020-10-29T07:53:46.94458966Z   File "/opt/bitnami/python/lib/python3.6/imp.py", line 172, in load_source
> 2020-10-29T07:53:46.944594717Z     module = _load(spec)
> 2020-10-29T07:53:46.944599568Z   File "<frozen importlib._bootstrap>", line 684, in _load
> 2020-10-29T07:53:46.944605585Z   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
> 2020-10-29T07:53:46.94461098Z   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
> 2020-10-29T07:53:46.944615995Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 2020-10-29T07:53:46.944620926Z   File "/opt/bitnami/airflow/dags/git/key_value_aggregator_sync.py", line 18, in <module>
> 2020-10-29T07:53:46.944625971Z     from operators.sync_to_kva import SyncToKVA
> 2020-10-29T07:53:46.944631185Z   File "/opt/bitnami/airflow/plugins/operators/sync_to_kva.py", line 5, in <module>
> 2020-10-29T07:53:46.944636895Z     from django.conf import settings
> 2020-10-29T07:53:46.944786477Z ModuleNotFoundError: No module named 'django'
> 

Note: key_value_aggregator_sync.py is the Dag name and plugins/operators/sync_to_kva.py is the plugin used inside the Dag.
The same happens for other 3rd party libraries too.

**To Reproduce**

1. Install Django via pip (requirement.txt)
2. Configure the plugin directory. and place the custom operator inside a py filed as follows
     plugins -> operators -> custom_operator.py
3. Add the line `import django`
3. Refer the custom operator via a DAG.

**Expected behavior**
It should load Django (or any other 3rd party library) in plugins with no errors.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
V3
```

- Output of `kubectl version`:

```
version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by alemorcuq** [comment]
Hi, @MarlonAbeykoon. 

Can you check this issue to see #2305? Seems related to your case.
