### ISSUE TITLE
[bitnami/rabbitmq] Management UI not accessible through Ingress AWS ALB.

### ISSUE THREAD

**Issue by GoDllkE** [bitnami/charts#4346]
**Which chart**: bitnami/rabbitmq-7.8.0

**Describe the bug**
Rabbitmq is unable to show the management console through the AWS ALB Ingress. 
When accessing through the IngressResoruce, it returns 404 for all items from the management UI(main.js,main.css, etc). 
But when using kubectl port-forward svc/rabbitmq 15672:15672, the console shows up nicely.

**To Reproduce**
1. Execute: 
`helm install bitnami/rabbitmq --set ingress.annotations="kubernetes.io/ingress.class: alb",ingress.hostname="rabbitmq.yourdomain.com"`
2. Try to access "rabbitmq.yourdomain.com" on your browser.
3. See browser network console for '404' erros.

**Expected behavior**
It should appear the management UI through the Ingress generated like it shows up when using "kubectl port-forward".

**Version of Helm and Kubernetes**: 
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`: 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
Though about filesystem permission access, but turning the pod to run with user:group 0:0 doesn't worked.

**Comment by alemorcuq** [comment]
Hi, @GoDllkE.

Are you setting `ingress.enabled=true`? I'm asking because I don't see that in your instructions.

If so, can you share the output of `kubectl describe <ingress-name>`?

**Comment by vitali-zevako** [comment]
The same issue, able to open it via port-forward, but via ALB ingress getting blank page (and 404 errors to load page scripts)

**Comment by andresbono** [comment]
Hi @vitali-zevako, can you share the commands that you are using to deploy the RabbitMQ chart? Could you also check the question from @alemorcuq? https://github.com/bitnami/charts/issues/4346#issuecomment-728769052

**Comment by vitali-zevako** [comment]
hi @andresbono 
Here is my values.yaml
```
auth:
  username: user
  password: secret
  erlangCookie: secretcookie
ingress:
  enabled: true
  hostname: rabbitmq.mydomain.io
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: public
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
```

Deploying it with:
`helm upgrade rabbitmq bitnami/rabbitmq --install -f values.yaml`

Resulting ingress:
```
kubectl describe ingress/rabbitmq
Name:             rabbitmq
Namespace:        default
Address:          k8s-public-f461be73a9-********.us-east-1.elb.amazonaws.com
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                     Path  Backends
  ----                     ----  --------
  rabbitmq.mydomain.io
                           /   rabbitmq:http-stats (172.18.5.95:15672)
Annotations:
  meta.helm.sh/release-namespace:          default
  alb.ingress.kubernetes.io/group.name:    public
  alb.ingress.kubernetes.io/listen-ports:  [{"HTTPS": 443}]
  alb.ingress.kubernetes.io/target-type:   ip
  kubernetes.io/ingress.class:             alb
  meta.helm.sh/release-name:               rabbitmq
Events:
  Type    Reason                  Age    From     Message
  ----    ------                  ----   ----     -------
  Normal  SuccessfullyReconciled  9m42s  ingress  Successfully reconciled
```

When i opening management endpoint in browser it shows blank page (load only root page and 404 for all js files)

**Comment by andresbono** [comment]
Hi @vitali-zevako, there should be a problem with the annotations that you are using.

If you check the annotations table: https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#annotations

You might be missing `alb.ingress.kubernetes.io/scheme: internet-facing`: [`alb.ingress.kubernetes.io/scheme`](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/#scheme).

Please note that you might end up exposing your rabbitmq to the public internet and that could lead into security issues.

**Comment by vitali-zevako** [comment]
@andresbono tried with this annotation as well (actually it is already set on another ingress resource with the same group name) 
Also tried to not reusing existing ALB, and use dedicated for rabbitmq - still the same.

We do not plan to expose it publicly (it is just fastest option in my sandbox env to play with it)

**Comment by andresbono** [comment]
From a previous message:

> When i opening management endpoint in browser it shows blank page (load only root page and 404 for all js files)

You get a `200` http code for the main page but then when it tries to load other resources, all of them are 404, is that correct?

Can you inspect the web browser console looking for errors? Can you share the specific messages that you are getting?

**Comment by vitali-zevako** [comment]
@andresbono Right, getting 200 for the main and 404 for all others. 

Network tab:

![image](https://user-images.githubusercontent.com/11630328/105808970-da3dbe00-5fb9-11eb-9a09-cdbbce18de14.png)

Response header Server is "Cowboy" on root page, on all 404 pages it is  aws/elb.2.0 (not sure it is important)

Console tab (nothing useful):
![image](https://user-images.githubusercontent.com/11630328/105809165-415b7280-5fba-11eb-97c2-549407aceb38.png)

**Comment by andresbono** [comment]
Hi @vitali-zevako, I'm running out of ideas. I don't have an ALB available for testing but either using port-forwarding or using nginx-ingress, I can reach all the resources. Maybe you can try to get the objects directly with curl to see if the browser is somehow caching the 404 responses...

```
curl -I http://rabbitmq.mydomain.io/
curl -I http://rabbitmq.mydomain.io:/js/ejs-1.0.min.js
```

**Comment by vitali-zevako** [comment]
Hi @andresbono 
Unfortunately the same 404 with curl

```
curl -I http://rabbitmq.mydomain.io/
HTTP/1.1 200 OK
Date: Thu, 28 Jan 2021 10:17:58 GMT
Content-Type: text/html
Content-Length: 2884
Connection: keep-alive
content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'
etag: "411992891"
last-modified: Thu, 28 Jan 2021 10:10:33 GMT
server: Cowboy
vary: origin
```

```
curl -I http://rabbitmq.mydomain.io/js/ejs-1.0.min.js
HTTP/1.1 404 Not Found
Server: awselb/2.0
Date: Thu, 28 Jan 2021 10:19:41 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
```

**Comment by vitali-zevako** [comment]
Finally found problem. Seems it is how ALB ingress controller generate rules for ALB.

Need to changes this:
```
ingress:
  path: /
```
to:
```
ingress:
  path: /*
```

@andresbono thank you a lot of spending time and trying to help

**Comment by andresbono** [comment]
Hi @vitali-zevako, thanks so much for sharing the solution! 🎉  We have created #5379 based on that.
