### ISSUE TITLE
[bitnami/mysql] Allow setting clusterIP to "None" for headless service

### ISSUE THREAD

**Issue by royshouvik** [bitnami/charts#4347]
**Which chart**:
bitnami/mysql (version 6.14.11)

**Describe the bug**
As described in StatefulSets docs [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations), StatefulSets **require** a headless service for network identity of pods. The helm chart should either default to `clusterIP: "None"` when creating a service of type ClusterIP or allow user to override the value. We are facing random connection reset errors when there are idle connections in the pool.

**To Reproduce**
Deploy chart with default values. 

**Expected behavior**
MySQL should work without connection issues out of the box.

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
N/A

**Comment by dani8art** [comment]
Hi @royshouvik thank you for the feedback, we will try to reproduce the issue.

**Comment by dani8art** [comment]
Hi @royshouvik sorry for the late response, I've created a PR adding both headless services so you can access pod DNS directly, please, let's move the conversation there.

Thanks!

**Comment by royshouvik** [comment]
@dani8art Thank you 🙏
