### ISSUE TITLE
[bitnami/rabbitmq] Load Definitions exception  I deployed according to the Helm document and modified rabbitMQ policy and connection number according to the customization. After deployment, I entered the account password and reported an error. What was the reason?

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4351]
06:38:25.97 Welcome to the Bitnami rabbitmq container
 06:38:25.97 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
 06:38:25.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
 06:38:25.98 
 06:38:25.98 INFO  ==> ** Starting RabbitMQ setup **
 06:38:25.99 INFO  ==> Validating settings in RABBITMQ_* env vars..
 06:38:26.01 INFO  ==> Initializing RabbitMQ...
 06:38:26.04 INFO  ==> Starting RabbitMQ in background...
 06:38:40.88 ERROR ==> Couldn't change password for user 'gefuxing'.
 06:38:40.88 INFO  ==> Stopping RabbitMQ...

2020-11-13 06:42:33.201 [warning] <0.1457.0> HTTP access denied: user 'gefuxing' - invalid credentials

extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json

---------------------------------------------------------------------------
I deployed according to the Helm document and modified rabbitMQ policy and connection number according to the customization. After deployment, I entered the account password and reported an error. What was the reason?

**Comment by javsalgar** [comment]
Hi,

Could you provide the full set of values you changed? This would help us reproduce the issue. I recall seeing errors like this before.

**Comment by Gefuxing** [comment]
`
extraSecrets:
  load-definition:
    load_definition.json: |
     {
	"vhosts": [
		{
			"name": "/"
		}
	],
	"parameters": [
		{
			"value": {
				"max-connections": 15000
			},
			"vhost": "/",
			"component": "vhost-limits",
			"name": "limits"
		}
	],
	"policies": [
		{
			"vhost": "/",
			"name": "test",
			"pattern": "^",
			"apply-to": "all",
			"definition": {
				"ha-mode": "all",
				"ha-sync-mode": "automatic"
			},
			"priority": 1
		}
	]
}
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json`
-------------------------------------------------------------
All these have been changed in Values.yaml and then deployed. After the deployment, the browser access will report a logon failure. I just change values.yaml according to the configuration file above, thank you!

**Comment by FraPazGal** [comment]
Hi @Gefuxing,

Thanks for opening this issue! This is a known problem and we are actively looking into it. We will update with new info as soon as possible, thank you for your patience.

**Comment by Gefuxing** [comment]
@FraPazGal Is there any good solution at present? When deploying cluster, it is mirroring mode. Can you offer some Suggestions?For example, debug_execute $RABBITMQ_BIN_DIR/rabbitmqctl set_policy ha-all "^" '{"ha-mode":"all", "ha-sync-mode":"automatic"}'
Is the following feasible?Thank you very much!!

------------------------------------------------------

########################
# Starts RabbitMQ in background and waits until it's ready
# Globals:
#   BITNAMI_DEBUG
#   RABBITMQ_BIN_DIR
# Arguments:
#   None
# Returns:
#   None
#########################
rabbitmq_start_bg() {
    is_rabbitmq_running && return
    info "Starting RabbitMQ in background..."
    local start_command=("$RABBITMQ_BIN_DIR/rabbitmq-server")
    am_i_root && start_command=("gosu" "$RABBITMQ_DAEMON_USER" "${start_command[@]}")
    debug_execute "${start_command[@]}" &
    export RABBITMQ_PID="$!"

  ###   debug_execute $RABBITMQ_BIN_DIR/rabbitmqctl set_policy ha-all "^" '{"ha-mode":"all" , "ha-sync-mode":"automatic"}'
    if ! retry_while "debug_execute ${RABBITMQ_BIN_DIR}/rabbitmqctl wait --pid $RABBITMQ_PID --timeout 5" 10 10; then
        error "Couldn't start RabbitMQ in background."
        return 1
    fi
}

**Comment by FraPazGal** [comment]
Hello @Gefuxing,

At the moment we are still working on a solution, thank you for you patience! I'm not sure if setting a high availability policy at installation time will solve the current issue, could you explain it in more detail?

**Comment by kheraud** [comment]
Any news on this subject ? We are facing the exact same issue

**Comment by javsalgar** [comment]
Hi,

Sorry this issue got closed. Reopening it. Currently it is still in our backlog. Could you provide the exact set of values so I can reproduce?

**Comment by javsalgar** [comment]
This should be fixed in the latest version
