### ISSUE TITLE
[bitnami/mongodb] Have different storage engines for each replicaset member

### ISSUE THREAD

**Issue by krtk6160** [bitnami/charts#4352]
**Which chart**:
mongodb-10.0.0

**Is your feature request related to a problem? Please describe.**
I am unable to find documentation on how to achieve [this](https://docs.mongodb.com/manual/core/inmemory/#replica-set).

**Describe the solution you'd like**
Instructions on how to set up a three member replicaset, in which two members use the in-memory storage engine, while the third one is hidden and uses WiredTiger storage engine.

**Additional context**
I think I can set one member as hidden and priority for it as 0 by using an initDbScript, but I can't figure out how to set the storage engine for each member separately.

**Comment by andresbono** [comment]
Hi @krtk6160, I'd say that customization is not supported by the chart. Can the storage engine be specified other than in the configuration file?

**Comment by krtk6160** [comment]
> Hi @krtk6160, I'd say that customization is not supported by the chart... Can the storage engine be specified other than in the configuration file?

I'm afraid not. There are only two ways that I could find, either through a command line flag, or throught the configuration file.

**Comment by andresbono** [comment]
If it can be set with flags, you may want to try playing with the command that the container receives. Give a try to the following values:

```yaml
architecture: replicaset
replicaCount: 3
command:
  - bash
  - -c
  - |
    if [[ "$MY_POD_NAME" = "{{ include "mongodb.fullname" . }}-2" ]]; then
        export MONGODB_EXTRA_FLAGS+=' --storageEngine=wiredTiger'
    else
        export MONGODB_EXTRA_FLAGS+=' --storageEngine=inMemory'
    fi
    echo "[debug] MONGODB_EXTRA_FLAGS='${MONGODB_EXTRA_FLAGS}'"
    /scripts/setup.sh
```

**Comment by andresbono** [comment]
Bad news. It seems the inMemory storage engine is only available for the enterprise version of MongoDB:

https://docs.mongodb.com/manual/reference/program/mongod/#storage-options
> inMemory | To specify the In-Memory Storage Engine.
> New in version 3.2: Available in MongoDB Enterprise only.

**Comment by krtk6160** [comment]
> Bad news. It seems the inMemory storage engine is only available for the enterprise version of MongoDB:

That's a bummer! Thank you for your help.
