### ISSUE TITLE
password errors when using subcharts

### ISSUE THREAD

**Issue by joshribakoff** [bitnami/charts#4364]
**Which chart**:
postgresql

**Describe the bug**
Installing w/ sub charts work, but I can't upgrade after making changes. I removed mongo sub-chart and tried with postgresql, and it would not even install when I add the dependency to my chart and upgrade. I blew away my k8 namespace and installed w/ the postgresql sub-chart, it worked, but then I can never upgrade (even when passing in the password with --set).

AS a workaround I have to uninstall and re-install to emulate upgrading, albeit with downtime.

**To Reproduce**
https://github.com/bitnami/bitnami-docker-mongodb/issues/238

After the above error, I ripped out mongo and added:

```

dependencies:
  - name: postgresql
    version: 9.8.12
    repository: https://charts.bitnami.com/bitnami

```

I'm met with the same error:

```
✗ helm upgrade bot backend-chart
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/joshribakoff/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/joshribakoff/.kube/config
Error: UPGRADE FAILED: template: chart/charts/postgresql/templates/NOTES.txt:59:4: executing "chart/charts/postgresql/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $passwordValidationErrors) "context" $)>: error calling include: template: chart/charts/mongodb/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'postgresqlPassword' must not be empty, please add '--set postgresqlPassword=$POSTGRESQL_PASSWORD' to the command. To get the current value:

        export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace default bot-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
```

**Expected behavior**
It should install the chart

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.19.2
  StackAPI:         Unknown
```

- Output of `docker info`:

```
Containers: 10
 Running: 3
 Paused: 0
 Stopped: 7
Images: 37
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.786GiB
Name: linuxkit-025000000001
ID: CZ6R:FNE7:MBK7:HWDF:7W7F:K6MC:6XQR:T3XD:3ACR:SS43:YIHF:US3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 49
 Goroutines: 72
 System Time: 2020-11-14T17:28:40.0777384Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

n/a

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

using minikube on mac to test

**Comment by FraPazGal** [comment]
Hi @joshribakoff,

You shared the first error log when the password in not been passed in the `helm upgrade` with `--set`, could you please paste the error you get after executing the following code? Keep in mind that the parameter's name of `postgresqlPassword` may differ in your chart from the one given in the logs given that you are using it as subchart: 

```
$ export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace default bot-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

$ helm upgrade bot backend-chart --set postgresql.postgresqlPassword=$POSTGRESQL_PASSWORD
```

**Comment by joshribakoff** [comment]
Yes the logs had the wrong path. I'd be inclined to keep the issue open because having the wrong logs is not intuitive, but my problem is solved so I'll mark closed (I'd push back on having misleading logs, though!)

Thanks!

**Comment by joshribakoff** [comment]
> You shared the first error log when the password in not been passed in the helm upgrade with --set

Right, I expect this to work, it’s part of the bug. Postgres is being initially installed, as I just added the sub chart. The top level chart was previously installed, but this was the initial install of Postgres. I still contend this is a bug FYI, even though I’m unblocked :)

**Comment by FraPazGal** [comment]
Hi @joshribakoff,

I understand it now; you were upgrading the existing chart adding postgresql as a new subchart when it threw the error, is that right? Indeed, this would be caused because postgresql will check for missing passwords when `.Release.IsUpgrade`, which doesn't cover this case of been initialised as a subchart in an already running installation.

There is already an internal task evaluating password validation behaviour on upgrades, so I will add this issue as a related one to it. Thank you for bringing this up!

**Comment by joshribakoff** [comment]
That's correct, both the postgresql and mongodb bitnami charts have this issue, and I was also using both incorrectly :)

**Comment by skriesch** [comment]
We have got the same issue with PostgreSQL 10.3.17 as a subchart of gitea. That is happening with "helm upgrade" and not with "helm install".

**Comment by alemorcuq** [comment]
Hi, @skriesch.

I haven't been able to reproduce your issue. Here's what I did:

1. Clone `https://gitea.com/gitea/helm-chart`
2. Get the required subcharts running `helm dep build`
3. Install the chart with the default values: `helm install gitea . -f values.yaml`
4. Change the image tag for PostgreSQL in the values file:

```
❯ git diff
diff --git a/values.yaml b/values.yaml
index 99e58e2..2488f49 100644
--- a/values.yaml
+++ b/values.yaml
@@ -266,6 +266,8 @@ postgresql:
       postgresqlUsername: gitea
       postgresqlPassword: gitea
       servicePort: 5432
+  image:
+    tag: 11.12.0-debian-10-r10
   persistence:
     size: 10Gi
 ```

5. Upgrade the chart running `helm upgrade gitea . -f values.yaml`

As you can see, the chart gets upgraded properly:

```
❯ helm upgrade gitea . -f values.yaml
Release "gitea" has been upgraded. Happy Helming!
NAME: gitea
LAST DEPLOYED: Tue Sep  7 12:44:42 2021
NAMESPACE: gitea
STATUS: deployed
REVISION: 3
NOTES:
1. Get the application URL by running these commands:
  echo "Visit http://127.0.0.1:3000 to use your application"
  kubectl --namespace gitea port-forward svc/gitea-http 3000:3000

❯ k get po -w
NAME                               READY   STATUS        RESTARTS   AGE
gitea-0                            1/1     Running       0          6m17s
gitea-memcached-574858645d-wmdgp   1/1     Running       0          6m17s
gitea-postgresql-0                 1/1     Terminating   0          6m17s
gitea-postgresql-0                 0/1     Terminating   0          6m45s
gitea-postgresql-0                 0/1     Terminating   0          6m46s
gitea-postgresql-0                 0/1     Terminating   0          6m46s
gitea-postgresql-0                 0/1     Pending       0          0s
gitea-postgresql-0                 0/1     Pending       0          0s
gitea-postgresql-0                 0/1     ContainerCreating   0          0s
gitea-postgresql-0                 0/1     Running             0          11s
gitea-postgresql-0                 1/1     Running             0          21s
```

Please, let me know if you are doing something different.

**Comment by skriesch** [comment]
I had an old version of the gitea helm-chart without any change of the password. I wanted to upgrade gitea to a new version (which brought also a new PostgreSQL version). A "helm upgrade" said that I would have to provide the current password.
The solution was to use the password twice.
See following issue: https://gitea.com/gitea/helm-chart/issues/219

**Comment by alemorcuq** [comment]
Did you have the password set in your values file?

**Comment by skriesch** [comment]
> Did you have the password set in your values file?

Yes. The solution was to add the password double in the values.yaml.

```
postgresql:
  postgresqlPassword: kLiUz5dd!vGhj4 # <- This would be required for the update
  global:
    postgresql:
      postgresqlDatabase: database
      postgresqlUsername: gitea
      postgresqlPassword: kLiUz5dd!vGhj4
      servicePort: 5432
```
