### ISSUE TITLE
bitnami/postgresql-ha] Service Account for Postgres HA

### ISSUE THREAD

**Issue by ghahramani** [bitnami/charts#4366]
**Which chart**:
Postgres HA

**Is your feature request related to a problem? Please describe.**
To be able to use istio I need to define a serviceAccount for the pods in the namespace, but the chart does not accept any serviceAccount

**Describe the solution you'd like**
Add the support of defining serviceAccount (internal or external)

**Comment by andresbono** [comment]
Hi @ghahramani, thanks for opening this issue. We have some charts that already have istio support and that are meeting all the [requirements](https://istio.io/latest/docs/ops/deployment/requirements/), i.e. [bitnami/elasticsearch](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch).

Based on elasticsearch, would you like to open a PR adding support for service accounts? Contributions are more than welcome!
