### ISSUE TITLE
Please use the offical build of redmine's docker image

### ISSUE THREAD

**Issue by xrow** [bitnami/charts#4368]
**Which chart**:
The name (and version) of the affected chart.
redmine

**Is your feature request related to a problem? Please describe.**

feature

**Describe the solution you'd like**

remove docker.io/bitnami/redmine and use docker.io/redmine
 
**Describe alternatives you've considered**

none

Stay as is

**Additional context**

It si more consistent if there are no two images.

**Comment by alemorcuq** [comment]
Hi, @xrow.

[Our policy](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) is to only use our images in our charts. 

[In this link](https://github.com/bitnami/bitnami-docker-redmine#why-use-bitnami-images) you can find the advantages of using Bitnami images.

**Comment by xrow** [comment]
Allright to bad....
