### ISSUE TITLE
Redis - describe how to upgrade redis release without changing the random password

### ISSUE THREAD

**Issue by tvedtorama** [bitnami/charts#4369]
**Which chart**:
Redis 11.1.0

**Describe the bug**
I created a release using the default random password.  This works perfectly.  The other pods in k8s use the secret to look up the password, but some external parties had their own copy of the password.  Then I needed to adjust some parameters, or generally upgrade, redis.  This caused a new password to be generated.  This passed undetected in k8s, as the pods there would just use the updated secret.  However, the external clients failed - as a new password was generated.

I tried to work around this by `--set existingSecret=redis` but this just failed badly - I think this secret is wiped when upgrading.  I ended up hard coding the old password in the values, which seems a bad idea - as this is not a 'secret'.

**To Reproduce**
Create a redis release with default password.  Then upgrade it.

**Expected behavior**
It should be possible by scanning the documentation quickly, to determine what will happen - and how to avoid changed password.

**Comment by juan131** [comment]
Hi @tvedtorama 

We're working on adapting the charts NOTES, so they provide this information when it's detected during an upgrade that the password is not indicated. For instance, the MariaDB chart uses the validations defined in the "common" chart to implement this:

- https://github.com/bitnami/charts/blob/master/bitnami/mariadb/templates/NOTES.txt#L48
- https://github.com/bitnami/charts/tree/master/bitnami/common

Therefore, if you try to upgrade a MariaDB release without indicating it, you obtain the error below:

```
$ helm upgrade mariadb bitnami/mariadb
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace default mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
```

We will add a very similar solution to this one to Redis in future versions.

**Comment by tvedtorama** [comment]
This sounds like a good solution to this problem.  Thanks for the answer!

But I am a bit uncertain, whether it is advisable, from a security standpoint, to store the password as a helm variable?  Do you know if this is an acceptable practise?

**Comment by juan131** [comment]
Hi @tvedtorama 

Helm will save this information in a secret in the same namespace where it installed the chart. And, if you implement security policies in your cluster, secrets should be protected by RBAC rules so humans don't have access to them. So, I don't think that's a dangerous thing.

That said, we also provide the `existingSecret` and `existingSecretPasswordKey` so you can retrieve the password for an existing secret. This way, helm won't store any information about the password.
