### ISSUE TITLE
[bitnami/phabricator] Upgrading release replaces user password

### ISSUE THREAD

**Issue by VincentPost-TomTom** [bitnami/charts#4375]
**Which chart**:
phabricator: 9.2.0

**Describe the bug**
If the value `phabricatorPassword` is empty a random 10 char password is generated and used for the initial user. If you upgrade the helm chart to change values the field `phabricator-password` in the secret object `<releasename-phabricator>` is again set to a random 10 char password but since the user already exists the password is not changed.

**To Reproduce**

1. `helm install phab bitnami/phabricator --set phabricatorHost="phabricator-dev.example.com"`
2. wait for everything to become ready
3. `kubectl get secret phab-phabricator -o jsonpath="{.data.phabricator-password}" | base64 --decode`
4. `helm install phab bitnami/phabricator --set phabricatorHost="phabricator.example.com"`
5. wait for everything to become ready
6. `kubectl get secret phab-phabricator -o jsonpath="{.data.phabricator-password}" | base64 --decode`
7. Observe that the output of 4 and 6 differs

**Expected behavior**
The secret value should not change

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Well it is not really important since you should change the password anyway but I noticed it during dev.

**Comment by FraPazGal** [comment]
Hi @VincentPost-TomTom,

Thank you for bringing this up! We are indeed aware of the issue of secrets regeneration upon doing another `helm install` or a `helm upgrade` and it is something we are currently investigating to improve. There is already an internal task to address this and the current plan is to to introduce the `lookup` function in our charts after our Helm v2 EOL as explained in https://github.com/helm/charts/issues/5167#issuecomment-641558251.

I can't give you a current ETA at the moment as this affects a big part of our catalog but this is something that we are actively working on fixing. Thanks again for your issue!

**Comment by VincentPost-TomTom** [comment]
Could this issue please receive the label on-hold to exempt this issue form the stale bot.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
