### ISSUE TITLE
Common.labels creates logging and slicing issues with subcharts.

### ISSUE THREAD

**Issue by damienwebdev** [bitnami/charts#4376]
**Which chart**:
RabbitMQ + https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_labels.tpl

**Describe the bug**
When I use a chart as a dependency, my resulting labels on my RabbitMQ pod look like:

```
Labels:   app.kubernetes.io/instance=my-release
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=rabbitmq
              controller-revision-hash=my-release-rabbitmq-74dbfc66d7
              helm.sh/chart=rabbitmq-8.0.2
              statefulset.kubernetes.io/pod-name=my-release-rabbitmq-2
```

**To Reproduce**
Install RabbitMQ chart as a dependency of another chart.

**Expected behavior**
I expected `app.kubernetes.io/instance` to be `app.kubernetes.io/instance=my-release-rabbitmq`

**Version of Helm and Kubernetes**:
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"73ec19bdfc6008cd3ce6de96c663f70a69e2b8fc", GitTreeState:"clean", BuildDate:"2020-09-17T04:17:08Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @damienwebdev 

The `app.kubernetes.io/instance` label is set to the release name (`{{ .Release.Name }}`). This is the default value for this label on Helm charts. You can double-check it by running:

```console
$ helm create foo
$ grep "app.kubernetes.io/instance" foo/templates/_helpers.tpl
app.kubernetes.io/instance: {{ .Release.Name }}
```

See also https://helm.sh/docs/chart_best_practices/labels/
