### ISSUE TITLE
Keep receiving this K8S event: Liveness probe failed: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.

### ISSUE THREAD

**Issue by wufengzlw** [bitnami/charts#4377]
**Which chart**:
The name (and version) of the affected chart
redis-11.0.6

**Describe the bug**
Keep receiving this kubernetes event:
Liveness probe failed: \nWarning: Using a password with '-a' or '-u' option on the command line interface may not be safe.\nWarning: Using a password with '-a' or '-u' option on the command line interface may not be safe.\ntimeout: the monitored command dumped core\n

But seems redis slave pod works fine:
kgp -n xxx | grep redis
redis-master-0                                               2/2     Running     2          34d
redis-slave-0                                                2/2     Running     2          34d
redis-slave-1                                                2/2     Running     2          34d
redis-slave-2                                                2/2     Running     2          34d

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen.(paste your output here)

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
helm version
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by wufengzlw** [comment]
Just a update:
because redis-cli version is 6.0.8 on redis slave pod:
```
I have no name!@redis-slave-0:/$ redis-cli --version
redis-cli 6.0.8
```        
Then this variable is null
```                                                                                                                                                                                     
no_auth_warning=$([[ "$(redis-cli --version)" =~ (redis-cli 5.*) ]] && echo --no-auth-warning)                                                                                                                     
 ```
Then the redis-cli has this error message

**Comment by miguelaeh** [comment]
Hi @wufengzlw ,
I created the above PR that should fix that warning, could you give it a try?

**Comment by wufengzlw** [comment]
@miguelaeh 
Thanks for the quick fix

Just one stupid question, in our deployment, we are using this image:
```
docker.io/bitnami/redis:6.0.8-debian-10-r0
```

Could you tell me which image I should use to test?

**Comment by miguelaeh** [comment]
You can use the lastest tag published [here](https://hub.docker.com/r/bitnami/redis/tags).
But we don't recommend using `latest` since it is a rolling tag and your pods will be updated without your control.
You can use `6.0.9-debian-10-r19` for example, that was released yesterday.

**Comment by wufengzlw** [comment]
Thanks @miguelaeh 

I'll try later today

**Comment by wufengzlw** [comment]
@miguelaeh 

I have tried the image you mentioned:
```
k get statefulset redis-slave -n utility -o yaml | grep image
                f:image: {}
                f:imagePullPolicy: {}
                f:image: {}
                f:imagePullPolicy: {}
        image: docker.io/bitnami/redis:6.0.9-debian-10-r19
        imagePullPolicy: IfNotPresent
        image: docker.io/bitnami/redis-exporter:1.11.1-debian-10-r12
        imagePullPolicy: IfNotPresent
```

Still got this error:
```
I have no name!@redis-slave-2:/health/..data$ ./ping_liveness_local_and_master.sh 5                                                                                                                                
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.                                                                                                                  
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
```

To test this, I updated values in the helm chart to use this image, is their anything wrong with this?

**Comment by miguelaeh** [comment]
Are you using the PR referenced above to install the chart?

**Comment by wufengzlw** [comment]
It's working now, thanks a lot @miguelaeh
