### ISSUE TITLE
[bitnami/mariadb]provide a way to start mysqld with --tc-heuristic-recover

### ISSUE THREAD

**Issue by middlestone** [bitnami/charts#4379]
**Which chart**:
bitnami/mariadb

**Is your feature request related to a problem? Please describe.**

If mariadb node was not shut down properly, when it is power on, the mariadb pod maybe(not always) can not start up, because it has pending transactions.

More details about the error is as blew:

```
2020-11-17  5:44:55 0 [ERROR] Found 1 prepared transactions! It means that mysqld was not shut down properly last time and critical recovery information (last binlog or tc.log file) was manually deleted after a crash. You have to start mysqld with --tc-heuristic-recover switch to commit or rollback pending transactions.
2020-11-17  5:44:55 0 [ERROR] Aborting
```

**Describe the solution you'd like**

Just as information says, I need to start `mysqld with --tc-heuristic-recover`, but from the chart, I can not find the place where I can add the parameter tc-heuristic-recover for mysqld. 

**Describe alternatives you've considered**

At least manually recover can be done.

**Additional context**

**Comment by juan131** [comment]
Hi @middlestone 

I am afraid this is not trivial. I mean, providing am "automatic" way to start MariaDB in recovery method will require several changes in the chart.

That said, I think you can accomplish your goal making use of some the existing parameters:

- Set `secondary.replicaCount` to `0` to ensure there are no secondary nodes while you recover your database.
- Use `primary.command` to overwrite the default command (e.g. using `sleep infinity`). This way, the MariaDB container won't be initialized and you can open a shell (`kubectl exec ... -- bash`) and start the recovery method.
- Set `primary.livenessProbe.enabled` and `primar.readinessProbe.enabled` to `false` to avoid the probes to fail and restart the container while you're recovering your database.

**Comment by middlestone** [comment]
thanks juan131 for your workaround, I will close this issue.
