### ISSUE TITLE
bitnami/rabbitmq  I used the 3.7 RabbitMQ version for deployment, and the cluster showed that the startup failed. The chart I used is the latest version, 8.02. Can I use the old image?Rabbitmq 3.8 by default

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4384]
helm3  install mq --set persistence.storageClass=nfs-storage --set persistence.size=1Gi --set replicaCount=3   --set  image.registry=docker.io --set image.repository=bitnami/rabbitmq  --set image.tag=3.7.7-debian-9-r31  --set service.type=NodePort  
bitnami/rabbitmq

----------------------------------------------------------------------
mq-rabbitmq-0                                    0/1     CrashLoopBackOff   3          3m17s
Events:
  Type     Reason     Age                    From                    Message
  ----     ------     ----                   ----                    -------
  Normal   Scheduled  <unknown>              default-scheduler       Successfully assigned default/mq-rabbitmq-0 to 10.60.128.235
  Normal   Pulling    11m                    kubelet, 10.60.128.235  Pulling image "docker.io/bitnami/rabbitmq:3.7.7-debian-9-r31"
  Normal   Pulled     9m53s                  kubelet, 10.60.128.235  Successfully pulled image "docker.io/bitnami/rabbitmq:3.7.7-debian-9-r31"
  Normal   Started    8m54s (x4 over 9m52s)  kubelet, 10.60.128.235  Started container rabbitmq
  Normal   Created    7m57s (x5 over 9m52s)  kubelet, 10.60.128.235  Created container rabbitmq
  Normal   Pulled     6m28s (x5 over 9m48s)  kubelet, 10.60.128.235  Container image "docker.io/bitnami/rabbitmq:3.7.7-debian-9-r31" already present on machine
  Warning  BackOff    98s (x42 over 9m44s)   kubelet, 10.60.128.235  Back-off restarting failed container

-----------------------------------------------------------------------
**I used the 3.7 RabbitMQ version for deployment, and the cluster showed that the startup failed. The chart I used is the latest version, 8.02. Can I use the old image?Rabbitmq 3.8 by default,thanks a lot!!**

-----------------------------------------
I'll change the image to tag: 3.8.9-debian-10-r0 to make it work

helm3  install mq --set persistence.storageClass=nfs-storage --set persistence.size=1Gi --set replicaCount=3   --set  image.registry=docker.io --set image.repository=bitnami/rabbitmq  **--set image.tag=3.8.9-debian-10-r0**  --set service.type=NodePort  bitnami/rabbitmq 

mq-rabbitmq-0                                    1/1     Running            0          71s
mq-rabbitmq-1                                    1/1     Running            0          13s
mq-rabbitmq-2                                    1/1     Running            0          1s

**Comment by marcosbc** [comment]
Hi @Gefuxing, we only test 3.8 with the RabbitMQ chart version 8.0.4, so we cannot guarantee if everything will work the same.

In any case, it would be great if you could share the logs of the failing 3.7.x pod when installing the chart with that version, to see what's going on.
