### ISSUE TITLE
[bitnami/rabbitmq] The docker run later entrypoint.sh file has not been found

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4386]
Digest: sha256:8f075834a102c90e30ad2e6fd240f8f4bfb4748678cfd04b405af8855412c9d2
Status: Downloaded newer image for bitnami/rabbitmq:3.8.9-debian-10-r22
 09:33:14.34 
 09:33:14.34 Welcome to the Bitnami rabbitmq container
 09:33:14.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
 09:33:14.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
 09:33:14.35 

I have no name!@be6edd89d8e0:/$ ls
bin  bitnami  boot  dev  etc  home  lib  lib64	media  mnt  opt  proc  root  run  sbin	srv  sys  tmp  usr  var
I have no name!@be6edd89d8e0:/$

**Comment by andresbono** [comment]
Hi @Gefuxing, you can find it in `/opt/bitnami/scripts/rabbitmq/entrypoint.sh`. See the Dockerfile:

https://github.com/bitnami/bitnami-docker-rabbitmq/blob/3.8.9-debian-10-r22/3.8/debian-10/Dockerfile#L36

```Dockerfile
ENTRYPOINT [ "/opt/bitnami/scripts/rabbitmq/entrypoint.sh" ]
```
