### ISSUE TITLE
[bitnami/etcd] Pod errors from incrementing statefulset.replicaCount when trying to update existing cluster. 

### ISSUE THREAD

**Issue by sriramg96** [bitnami/charts#4393]
**Which chart**:
etcd-5.0.1

**Describe the bug**
Errors when trying to upgrade the existing etcd cluster by incrementing `statefulset.replicaCount`. Newly created pods get stuck in Error state or CrashLoopBackoff.

**To Reproduce**

1. Get latest chart with `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. Create new etcd cluster with `helm upgrade --install --create-namespace -n etcd etcd bitnami/etcd -f values.yaml`

Output of `cat values.yaml`
```
image:
    registry: docker.io
    repository: bitnami/etcd
    tag: 3.4.13-debian-10-r69
    pullPolicy: IfNotPresent
    debug: true

statefulset:
    replicaCount: 1

resources:
    limits:
        cpu: 4000m
        memory: 8Gi
    requests:
        cpu: 4000m
        memory: 8Gi

persistence:
    enabled: true
    storageClassName: "astra-fast-storage"
```

3. Change the value of `statefulset.replicaCount` in values.yaml to 2.
4. Upgrade existing cluster with `helm upgrade --install --create-namespace -n etcd etcd bitnami/etcd -f values.yaml`
5. The new pod created gets in CrashLoopBackoff or Error state and continually tries to restart. 
```
kubectl logs etcd-1

etcdmain: error validating peerURLs {ClusterID:7876e23ee274fcd6 Members:[&{ID:5e582867b15dbedc RaftAttributes:{PeerURLs:[http://etcd-0.etcd-headless.etcd.svc.cluster.local:2380] IsLearner:false} Attributes:{Name:etcd-0 ClientURLs:[http://etcd-0.etcd-headless.etcd.svc.cluster.local:2379]}}] RemovedMemberIDs:[]}: member count is unequal
```

**Expected behavior**
Expected behavior is for the new pods generated by incrementing `statefulset.replicaCount` to join the existing etcd cluster and to reach Running state successfully without hitting errors

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.2001", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-11-06T18:24:02Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @sriramg96 

Can you try killing the original pod (etcd-0)? That will force it to be recreated and adapted to the new configuration (where 2 nodes are expected). This should avoid the error with the member count differences.

Are you able to reproduce it when installing the chart initially with 2/3 nodes, and the scaling to 3/4?

**Comment by magiejen** [comment]
Hello, I am having the same issue. I can scale from 1 to 2 with no issue, but cannot scale past that without getting the same `error validating peerURLs` error. I tried the suggestion above, force killing etcd-0, but I have the same error.

**Comment by juan131** [comment]
Hi @magiejen 

Are you scaling using `helm upgrade .... --set replicaCount=X` or are you using `kubectl scale ...` command? Please note that only the former is supported.

**Comment by magiejen** [comment]
Hi @juan131 

We are using terraform to manage our helm charts. I am assuming under the hood, `terraform apply` uses `helm upgrade...`. The other helm charts upgrade with no issue and the `envVarsConfigMap` was set in this chart with no issue. 
`
resource "helm_release" "etcd" {
  name            = var.name
  namespace       = kubernetes_namespace.etcd.metadata[0].name
  repository      = "https://charts.bitnami.com/bitnami"
  chart           = "etcd"
  cleanup_on_fail = true

  values = [
    file("${path.module}/helm/etcd.yaml")
  ]

  set {
    name  = "envVarsConfigMap"
    value = kubernetes_config_map.etcd_var_config_map.metadata[0].name
  }

  set {
    name  = "statefulset.replicaCount"
    value = "2"
  }
}
`

Scaling from to 2 pods is fine. However, scaling from 1 to any other greater number results in the `error valiating peerURLs` error. We found that scaling from 2 pods to 3 results in this error in the third pod.
`
 ==> Bash debug is off   
 ==> Detected data from previous deployments...  
 ==> The data directory is already configured with the proper permissions                 
 ==> Updating member in existing cluster...     
 Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex 
 stream closed
`

**Comment by juan131** [comment]
Hi @magiejen 

I was unable to reproduce it doing "progressive" scaling:

- Install the chart:

```console
$ helm install etcd bitnami/etcd
```

- Wait for pod 0 to be ready:

```console
$ kg pods
NAME                       READY   STATUS    RESTARTS   AGE
etcd-0                     1/1     Running   0          52s
```

- Upgrade the chart scaling to 2 replicas (important to set the password):

```console
$ export ETCD_ROOT_PASSWORD=$(kubectl get secret --namespace default etcd -o jsonpath="{.data.etcd-root-password}" | base64 --decode)
$ helm upgrade etcd bitnami/etcd
  --set auth.rbac.rootPassword=$ETCD_ROOT_PASSWORD \
  --set statefulset.replicaCount=2
```

- Wait for pod 0 and 1 to be ready:

```console
$ kg pods
NAME                       READY   STATUS    RESTARTS   AGE
etcd-0                     1/1     Running   0          5m9s
etcd-1                     1/1     Running   1          6m49s
```

- Upgrade the chart scaling to 3 replicas (important to set the password):

```console
$ helm upgrade etcd bitnami/etcd
  --set auth.rbac.rootPassword=$ETCD_ROOT_PASSWORD \
  --set statefulset.replicaCount=3
```

- Wait for pod 0, 1 and 2 to be ready:

```console
$ kg pods
NAME                       READY   STATUS    RESTARTS   AGE
etcd-0                     1/1     Running   0          4m24s
etcd-1                     1/1     Running   0          5m53s
etcd-2                     1/1     Running   1          7m28s
```

**Comment by kd7lxl** [comment]
I'm seeing similar behavior, probably the same issue. It happens on new installs like `helm upgrade .... --set replicaCount=3` most of the time. Sometimes it comes up healthy, but other times two of the three pods go into `CrashLoopBackOff` with errors like this:
```
2020-12-18 20:13:25.261588 I | embed: advertise client URLs = https://runner-konk-etcd-1.runner-konk-etcd-headless.default.svc.cluster.local:2379
2020-12-18 20:13:25.265571 W | etcdserver: could not get cluster response from http://runner-konk-etcd-0.runner-konk-etcd-headless.default.svc.cluster.local:2380: Get http://runner-konk-etcd-0.runner-konk-etcd-headless.default.svc.cluster.local:2380/members: dial tcp 10.244.0.44:2380: connect: connection refused
2020-12-18 20:13:25.266906 W | etcdserver: could not get cluster response from http://runner-konk-etcd-2.runner-konk-etcd-headless.default.svc.cluster.local:2380: Get http://runner-konk-etcd-2.runner-konk-etcd-headless.default.svc.cluster.local:2380/members: dial tcp 10.244.0.45:2380: connect: connection refused
2020-12-18 20:13:25.268078 C | etcdmain: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs
```
It never seems to recover from this.

Using etcd chart version 5.3.2 (latest). Happened on earlier versions too.

**Comment by carrodher** [comment]
It can be something related to the etcd quorum logic? For example:

Install the chart with 3 replicas and wait for them to be up:
```console
$ helm install etcd bitnami/etcd --set statefulset.replicaCount=3
$ kubectl get pods
NAME     READY   STATUS    RESTARTS   AGE
etcd-0   1/1     Running   0          75s
etcd-1   1/1     Running   0          75s
etcd-2   1/1     Running   0          75s
```
Write some data (and check it's fine):
```console
$ kubectl exec -it etcd-0 -- bash
# etcdctl put --user root --password=$ETCD_ROOT_PASSWORD foo bar
Ok
# exit
$ kubectl exec -it etcd-1 -- bash
# etcdctl get --user root --password=$ETCD_ROOT_PASSWORD foo
foo
bar
# exit
```
Upgrade chart scaling it down to 1 replica (important to indicate root password during the upgrade):
```console
$ export ETCD_ROOT_PASSWORD=$(kubectl get secret --namespace default etcd -o jsonpath="{.data.etcd-root-password}" | base64 --decode)
$ helm upgrade etcd bitnami/etcd --set statefulset.replicaCount=1 --set auth.rbac.rootPassword=$ETCD_ROOT_PASSWORD
$ kubectl get pods
NAME     READY   STATUS             RESTARTS   AGE
etcd-0   0/1     CrashLoopBackOff   4          2m50s
```
It seems the cluster is recovered if you scale to 2 replicas:
```console
$ helm upgrade etcd bitnami/etcd --set statefulset.replicaCount=2 --set auth.rbac.rootPassword=$ETCD_ROOT_PASSWORD
$ kg pods
NAME     READY   STATUS    RESTARTS   AGE
etcd-0   1/1     Running   0          1m54s
etcd-1   1/1     Running   0          3m6s
$ kubectl exec -it etcd-1 -- bash
foo
bar
# exit
```
And.. that you can later scale it to 1 replica:
```console
$ helm upgrade etcd bitnami/etcd --set statefulset.replicaCount=1 --set auth.rbac.rootPassword=$ETCD_ROOT_PASSWORD
$ kg pods
NAME     READY   STATUS    RESTARTS   AGE
etcd-0   1/1     Running   0          73s
```

So... it's just a matter of not removing more than (N-1)/2 replicas when scaling down:

- When we scaled from 3 ((N-1)/2=1) to 1, it crashed since we were removing 2 replicas, and only 1 was accepted.
- However, when we scaled from 2 ((N-1)/2=0.5) to 1, we didn't break that limit.

**Comment by ankit9787** [comment]
Is this issue resolved ?

**Comment by ankit9787** [comment]
When i install bitnami/helm with replica=1 it works but for replica=2 or more 
I get error - got unexpected HTTP status code 503 Service Unavailable from http://etcd-deploy-2.etcd-deploy-headless.cortex-ver2.svc.cluster.local:XXXX/raft/probing
{"level":"warn","ts":"2021-08-23T10:21:56.830Z","caller":"etcdserver/server.go:XXXX","msg":"failed to publish local member to cluster through raft","local-member-id":"XXXXX","local-member-attributes":"{Name:etcd-deploy-1 ClientURLs:[http://etcd-deploy-1.etcd-deploy-headless.XXXXXX]}","request-path":"/0/members/a1071c92bd768482/attributes","publish-timeout":"7s","error":"etcdserver: request timed out"}

**Comment by juan131** [comment]
We're trying to address this issue in this PR @ankit9787 : https://github.com/bitnami/bitnami-docker-etcd/pull/21

**Comment by abdennour** [comment]
issue still persist

**Comment by juan131** [comment]
I answered you at https://github.com/bitnami/charts/issues/5771, let's continue the conversation there to avoid duplicated discussions.
