### ISSUE TITLE
[bitnami/rabbitmq] support additional labels for the StatefulSet

### ISSUE THREAD

**Issue by thomas-riccardi** [bitnami/charts#4395]
**Which chart**:
bitnami/rabbitmq 8.0.2

**Is your feature request related to a problem? Please describe.**
I use OPA gatekeeper to enforce some labels on various k8s resources; this bitnami/rabbitmq chart does provide `podLabels` to add labels to the Pods, and `service.labels`, but there is no way to add a label on the main StatefulSet.

**Describe the solution you'd like**
The redis helm chart does have `master.statefulset.labels`.

**Comment by andresbono** [comment]
Hi @thomas-riccardi, thanks for opening this issue.

Would you like to contribute with a PR addressing the changes? You can take `bitnami/redis` as an example. Contributions are more than welcome!

**Comment by thomas-riccardi** [comment]
Hi @andresbono,

It's done in #4449.

**Comment by FraPazGal** [comment]
Thank you again for the PR! 

Please keep in mind that you will need to install a new chart, as doing `helm upgrade` introducing new labels will break the existing installation.

**Comment by thomas-riccardi** [comment]
@FraPazGal it only sets labels to the StatefulSet itself, not to the pod templates or match label selector, so it should be ok for an update, shouldn't it?

**Comment by FraPazGal** [comment]
You are right @thomas-riccardi, it wouldn't be a breaking change in this case. Sorry for the confusion!
