### ISSUE TITLE
[bitnami/rabbitmq] statefulset is missing checksum/config

### ISSUE THREAD

**Issue by zerkms** [bitnami/charts#4402]
**Which chart**:
rabbitmq v8.0.3

**Describe the bug**
At the moment it's only secret and secret-cert secrets are checksummed, so a change in config wouldn't trigger redeploy.

**To Reproduce**
Check https://github.com/bitnami/charts/blob/cfe550523c25cda89dfb5b4d52e3b6fc8eaed070/bitnami/rabbitmq/templates/statefulset.yaml#L24-L33

**Expected behavior**
If a config has been changed it should redeploy

**Version of Helm and Kubernetes**:
N/a

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by marcosbc** [comment]
Hi @zerkms, you seem to be correct. Note that we're open to contributions, and would be happy to review any related PRs that helps improve Bitnami charts. Would you be up for sending a PR with the appropriate changes?

**Comment by zerkms** [comment]
Yep, here it is https://github.com/bitnami/charts/pull/4423 :-)
