### ISSUE TITLE
[bitnami/owncloud] Additional 'hosts' are not respected

### ISSUE THREAD

**Issue by nevets963** [bitnami/charts#4403]
**Which chart**: bitnami/owncloud (latest)

**Describe the bug**
The config.php file within owncloud does not include all hosts defined within the values.yaml.
The hosts are applied correctly to the ingress, so I can access the application, however Owncloud doesn't allow you to use it. Showing this error:
<img width="821" alt="Screenshot 2020-11-17 at 23 33 35" src="https://user-images.githubusercontent.com/1112574/99463589-04c22980-292e-11eb-84be-002d11ad08af.png">

Within the config.php, only 1 host user-defined host is there:
![Screenshot 2020-11-17 at 23 33 49](https://user-images.githubusercontent.com/1112574/99463713-4a7ef200-292e-11eb-8bff-845701abbc31.png)

**To Reproduce**
Add more than 1 host to 'ingress.hosts' within values.yaml

**Expected behavior**
I expect Owncloud to work with more than 1 domain

**Version of Helm and Kubernetes**:
v1.18.6+k3s1

**Additional context**
I can probably fix this issue myself, however I don't see/understand where/how the current config.php script is setup. I.e. to inject the 1 domain that is already there. I guess the other hosts need to be looped over and added to this config.php file

**Comment by andresbono** [comment]
Hi @nevets963,

Right now the container nor the chart are not prepared to receive more than one host to be configured. As the configuration file is persisted in the volume (`/bitnami/owncloud/conf/config.php`), you may want to modify it after initializing the first time and the changes will be persisted.

---

These are the pieces that connect the chart and the container:

https://github.com/bitnami/charts/blob/8a0ac76d9fb6b2c3710a2a308c3cf8db62464d42/bitnami/owncloud/templates/deployment.yaml#L80-L81

https://github.com/bitnami/charts/blob/8a0ac76d9fb6b2c3710a2a308c3cf8db62464d42/bitnami/owncloud/templates/_helpers.tpl#L47-L54


Then the container receives `OWNCLOUD_HOST`. In the first initialization only, the following javascript function is called:

```javascript
$app.helpers.configureHost = function(hostname) {
  const domains = JSON.parse($app.helpers.executeOcc(
    'config:system:get',
    {opts: [], args: ['--output=json_pretty', 'trusted_domains']}
  ));
  const number = Object.keys(domains).length;
  $app.helpers.executeOcc(
    'config:system:set',
    {args: ['trusted_domains', number, '--value', hostname]}
  );
};
```

**Comment by nevets963** [comment]
Thanks @andresbono for the insight! Over the next few days I'll see what I can do, if I can put a PR together to address this

**Comment by andresbono** [comment]
That would be very nice! However, even though the configuration logic of the container image is open-source code, it is not published in any public repository.

We are step by step making that code publicly available on GitHub, i.e. [bitnami/drupal](https://github.com/bitnami/bitnami-docker-drupal/tree/master/9/debian-10/rootfs/opt/bitnami/scripts), but owncloud is still in our TO-DO list.
