### ISSUE TITLE
bitnami/rabbitmq I want to install some commands in the image to prompt me to use root. What is the password? Thank you very much!

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4407]
I want to install some commands in the image to prompt me to use root. What is the password? Thank you very much!
I have no name!@427ca9fd0f09:/$ 
I have no name!@427ca9fd0f09:/$ 
I have no name!@427ca9fd0f09:/$ 
I have no name!@427ca9fd0f09:/$ apt-get install sodu
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
I have no name!@427ca9fd0f09:/$ su -
Password: 
su: Authentication failure
I have no name!@427ca9fd0f09:/$ 
I have no name!@427ca9fd0f09:/$

**Comment by juan131** [comment]
Hi @Gefuxing 

The Bitnami RabbitMQ container is a non-root container, and, therefore, you cannot install packages no running any privilege action. Find more information in the links below:

- https://github.com/bitnami/bitnami-docker-rabbitmq#why-use-a-non-root-container
- https://docs.bitnami.com/tutorials/work-with-non-root-containers/
