### ISSUE TITLE
[bitnami/rabbitmq] Provide multiple users from Chart

### ISSUE THREAD

**Issue by eriktroost070** [bitnami/charts#4410]
**Which chart**:
RabbitMQ 8.06

**Is your feature request related to a problem? Please describe.**
When we deploy RMQ to our cluster, we would like to provide multiple users. The chart only seems to be able to set 1 user.
We would like to set a few extra users

**Describe the solution you'd like**
Be able to define several other users in the chart.

**Describe alternatives you've considered**
We now create the other users by hand after deployement. These will be stored in the persistent storage, so any re-deployment does not remove all the users. But as we deploy RMQ to multiple environment (DTAP), this is still some hand work we would like to prevent.

**Comment by andresbono** [comment]
Hi @eriktroost070, you might want to check this section of the readme: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#user-content-load-definitions

In that definition you can declare as many users as you want. Let us know if that is what you are looking for.

**Comment by eriktroost070** [comment]
@andresbono This is exactly what I was looking for. Thank you very much.

**Comment by andresbono** [comment]
Great! :tada:
