### ISSUE TITLE
Keycloak (re)setting admin password isn't working

### ISSUE THREAD

**Issue by aholbreich** [bitnami/charts#4411]
**Which chart**:
keycloak-0.1.2	

**Describe the bug**
It's not possible to login with provided credentials in the UI

Keycloak is accesses via externaly configured Ingress, the only value give to the chart are

```
auth:
  adminUser: admin
  adminPassword: <notWorkingPassword>

proxyAddressForwarding: true
```

**To Reproduce**

1. helm install keycloak -f values-keycloak.yaml bitnami/keycloak
2. Go to Addmin UI
3. Try to login with user: admin, password: <notWorkingPassword>

"Invalid username or password." is shown..

**Expected behavior**

Login is possible

**Version of Helm and Kubernetes**:
Helm Version:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-07-28T00:00:00Z", GoVersion:"go1.15rc1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by miguelaeh** [comment]
Hi @aholbreich ,
If you are trying to change the password have in mind it will be stored into the PV, and it will not be changed just with a helm upgrade.
You will need to modify it in PV, or using the Keycloack UI, so the stored password is also changed.

**Comment by aholbreich** [comment]
You mean persistent value? 
Means  change of  _adminPassword_ and doiung chart release upgrade do nothing (just restarts keycloak).
maybe at least the this should be detected and some message about this should be generated or if  _adminPassword_  is not set it probaly should not regenerate values of  _adminPassword_  since they don't apply?

**Comment by miguelaeh** [comment]
Hi @aholbreich ,
> Means change of adminPassword and doiung chart release upgrade do nothing (just restarts keycloak).

yes, if the application is already configured the persisted data will be restored (the same with the database) so it will not be configured again.

>maybe at least the this should be detected and some message about this should be generated or if adminPassword is not set it probaly should not regenerate values of adminPassword since they don't apply?

We agree with this. We are working to add warnings to the NOTES.txt when doing an upgrade to show this. It seems we forgot about this one here: https://github.com/bitnami/charts/blob/547d9d7ea5c77833ad350457c04cefe50a732ca0/bitnami/keycloak/templates/NOTES.txt#L75

**Comment by miguelaeh** [comment]
Hi @aholbreich ,
I am sorry I was confused, this chart does not have any PVC and it seems it reconfigures the password with every upgrade.
I will try to reproduce the issue and will get back to you.

**Comment by aholbreich** [comment]
@miguelaeh it utilizes Postgress DB by default. so maybe here we have inconsistency between what chart is doing and prints out and the not changing password once stored in the db...

**Comment by miguelaeh** [comment]
Hi @aholbreich ,
I have been testing this and I found the following:
- Changing the password via the UI, the password is properly changed in my case.
- Changing the password using helm upgrade the password is not changed as expected. I guess because it is stored in the PostgreSQL PVC.

So I think, either the PR above is valid, or we have to check the configuration logic of the container.

**Comment by aholbreich** [comment]
Hi @miguelaeh  Currently after every

`helm upgrade keycloak -f values-keycloak.yaml bitnami/keycloak`

the chart prints you:

```
3. Access the Administration Console using the following credentials:

  echo Username: admin
  echo Password: $(kubectl get secret --namespace mapi keycloak-env-vars -o jsonpath="{.data.KEYCLOAK_ADMIN_PASSWORD}" | base64 --decode)
```
and every time this give you new password... even if it wasn't provided! 

I belive if it not possible to change admin password after the initial setup, thet is the chart should behave different on updates.

On initial setup it should set the initial password and thed return it out of it's store, no overwrites anymore.

**Comment by miguelaeh** [comment]
>and every time this give you new password... even if it wasn't provided!

This is because the secret passwords are autogenerated. But once the application is configured and the password is stored into the PostgreSQL volume, you need to change it using the UI or modifying the PostgreSQL database. Changing the secret will not take effect. The PR above had that purpose, to force the users to set the same password in the upgrades to avoid inconsistencies with the secret. I will re-open it

**Comment by abhinavk07** [comment]
I'm unable to log into keycloak using the initial username password given during helm install: 

"Invalid username or password." is shown on UI with below values. How can this be resolved?

`echo Username: user  
sh-3.2# echo Password: $(kubectl get secret --namespace default my-release-keycloak -o jsonpath="{.data.admin-password}" | base64 --decode)
Password:*******`

I even tried creating a new user from CLI but it doesn't work as well:
`./add-user-keycloak.sh -u admin -p password`

**Comment by abhinavk07** [comment]
I'm unable to log into keycloak using the initial username password given during helm install: 

"Invalid username or password." is shown on UI with below values. How can this be resolved?
```

`echo Username: user  
sh-3.2# echo Password: $(kubectl get secret --namespace default my-release-keycloak -o jsonpath="{.data.admin-password}" | base64 --decode)
Password:*******`

```
I even tried creating a new user from CLI but it doesn't work as well:
```
./add-user-keycloak.sh -u admin -p password
```

**Comment by miguelaeh** [comment]
Hi @abhinavk07 ,
Is that a clean installation? Did you have any PVC before installing it? Try to re-install using a different release name or deleting the PVCs before installing it

**Comment by abhinavk07** [comment]
Yeah I had to bootstrap the entire deployment yesterday from scratch. Removed PV's and PVC's and then deployed KeyCloack again, finally it worked. This way would be catastrophic if it's deployed in production env, what is a recommended approach for deploying it in prod?

**Comment by abhinavk07** [comment]
Hi @miguelaeh 
Yeah I had to bootstrap the entire deployment yesterday from scratch. Removed PV's and PVC's and then deployed KeyCloack again, finally it worked. This way would be catastrophic if it's deployed in production env, what is a recommended approach for deploying it in prod?

**Comment by miguelaeh** [comment]
Hi @abhinavk07 ,
That happened because the environment was not clean. Probably you had a previous installation and the new one was taking the PVC of the previous installation. Since the passwords are stored in the PV the one in the secret did not match the one actually configured.
In a production environment you should be sure that the environment is clean before deploying it. You won't be able to upgrade the chart if you don't specify the old password, and in production I guess you will upgrade it but to delete it and create it a gain, so that should not happen.

**Comment by Code-Dhruv** [comment]
Even I am not able to change the keycloak initial password from helm values,  I am not using a PV either, I am using a postgres database, so what needs to be done to update the initial username and password which is admin admin.
