### ISSUE TITLE
Unable to change jenkin password after the installtion

### ISSUE THREAD

**Issue by mkmrah** [bitnami/charts#4412]
We are facing issue while updating the Jenkin chart values. Note for the testing purpose i have used helm3 CLI on IBM cloud cluster.

1. Jenkin https://charts.bitnami.com/ibm/jenkins-6.0.0.tgzHelm chart installed using the latest helm 3 client (https://github.com/helm/helm/releases/tag/v3.4.1)

2. helm release deployed into Kubernetes cluster and the jenkin server is accessible via the service API as mentioned in the readme document.

3. After the installation, we want to change the jenkin password, so you used "helm release upgrade" (helm upgrade jenkins6b-5045-46 jenkins --reuse-values --set jenkinsPassword=password1212 --debug) command to update the password.

4. There is no error / warning in the console while executing the helm upgrade command.

5. We can see the secret value change in K8 cluster and pod was not re-started.

6. When we use the new credential for jenkin server login then we get the authentication error but old password is working.

7. Tried with --force option and got below error

```
client.go:219: [debug] error updating the resource "jenkins6b-5045-46":
         failed to replace object: PersistentVolumeClaim "jenkins6b-5045-46" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims
client.go:219: [debug] error updating the resource "jenkins6b-5045-46":
         failed to replace object: Service "jenkins6b-5045-46" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

Looks like POD is using the old secret (it is defined as env_value inside the container) and its not refreshed as part of the helm upgrade. So here is my questions

1. How do we update the password after the installation?

2. If its an issue then any work around to manage this?

**Comment by FraPazGal** [comment]
Hello @mkmrah!

As you said, the jenkins password is passed to the container by an env and used only at installation time. When an upgrade is made, the new pod will reuse the persisted data present in the pvc so the container will skip the installation and won't use the secret anymore:

```
$ kubectl logs jenkins-654d5fb9bc-hpvn9

...
nami    INFO  Initializing jenkins
jenkins INFO  Moving plugins to /opt/bitnami/jenkins/jenkins_home...
jenkins INFO  Restoring persisted data...
jenkins INFO  Waiting Jenkins to be deployed...
jenkins INFO
jenkins INFO  ########################################################################
jenkins INFO   Installation parameters for jenkins:
jenkins INFO     Persisted data and properties have been restored.
jenkins INFO     Any input specified will not take effect.
jenkins INFO   This installation requires no credentials.
jenkins INFO  ########################################################################
...
```

To change the password you would need to do it from the application itself, as currently there isn't any method to do it from helm.

**Comment by mkmrah** [comment]
@FraPazGal I think multiple helm charts will have this similar limitation and it would be nice same is updated in the readme doc.

**Comment by FraPazGal** [comment]
Hi @mkmrah,

That is a good point, thank you for the suggestion! I have created an internal task for the team to work on this. Given the upcoming holiday season I can't give you an ETA, but we'll try to work on this as soon as possible!
