### ISSUE TITLE
 bitnami/rabbitmq  How to provide three ports for external access to each RabbitMQ POD in the three-node normal mode, this tutorial only has one service and one access port?

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4419]
I set up a three-node cluster pattern is ordinary, but only expose a service port, connect only one node at a time node, how do I get each pod service, such a connection to a node, the another two nodes are ineffective, how to connect to the three rabbitmq pod, through the corresponding service connection, each service has a rabbitmq pod, thank you very much!

**Comment by FraPazGal** [comment]
Hello @Gefuxing!

Currently that scenario is not considered by our chart, which uses a single service to connect to each of the three pods using its endpoints. Nevertheless, you should be able to configure the whole cluster having access to any of the nodes, shouldn't you?

If you need a service per pod, you could create one for each pod adding `{{ range }}` to `svc.yaml` and modifying the selector using something like:

```yaml
{{range $e := until .Values.replicaCount }}
...
selector:
  statefulset.kubernetes.io/pod-name=rabbitmq-{{ $e }}
...
{{ end }}
```

Would that work for you?

**Comment by Gefuxing** [comment]
Plan as you said, I try the Error: the template: the rabbitmq/templates/SVC yaml: 83:26: executing "the rabbitmq/templates/SVC. Yaml" ats & lt;.Values.replicaCount&gt;: Range can't iterate over 3, for example, a service has three replicaCount. Can you provide a YAML that can iterate over 3 services, thank you very much?I didn't create it

**Comment by Gefuxing** [comment]
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if not (empty .Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: amqp
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.auth.tls.enabled }}
    - name: {{ .Values.service.tlsPortName }}
      port: {{ .Values.service.tlsPort }}
      targetPort: amqp-ssl
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.tlsNodePort)) }}
      nodePort: {{ .Values.service.tlsNodePort }}
      {{- end }}
    {{- end }}
    - name: {{ .Values.service.epmdPortName }}
      port: 4369
      targetPort: epmd
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.epmdNodePort))) }}
      nodePort: {{ .Values.service.epmdNodePort }}
      {{- end }}
    - name: {{ .Values.service.distPortName }}
      port: {{ .Values.service.distPort }}
      targetPort: dist
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.distNodePort))) }}
      nodePort: {{ .Values.service.distNodePort }}
      {{- end }}
    - name: {{ .Values.service.managerPortName }}
      port: {{ .Values.service.managerPort }}
      targetPort: stats
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.managerNodePort))) }}
      nodePort: {{ .Values.service.managerNodePort }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: {{ .Values.service.metricsPortName }}
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- else if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.metricsNodePort))) }}
      nodePort: {{ .Values.service.metricsNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  ##selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    **_{{range $e := until .Values.replicaCount }}
  selector:
       statefulset.kubernetes.io/pod-name={{ include "rabbitmq.fullname" . }}-{{ $e }}
    {{ end }}_**

**Comment by Gefuxing** [comment]
Hope to provide such a YAML, thank you very much

**Comment by FraPazGal** [comment]
Hi @Gefuxing,

My bad, the example I added was not very clear. Here is the `svc.yaml` template:

<details>
  <summary>svc.yaml</summary>

  ```
  {{ range $i, $e := until (int $.Values.replicaCount) }}
  apiVersion: v1
  kind: Service
  metadata:
    name: {{ include "rabbitmq.fullname" $ }}-{{ $e }}
    namespace: {{ $.Release.Namespace | quote }}
    labels: {{- include "common.labels.standard" $ | nindent 4 }}
      {{- if $.Values.service.labels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.service.labels "context" $) | nindent 4 }}
      {{- end }}
    {{- if $.Values.service.annotations }}
    annotations: {{- include "common.tplvalues.render" (dict "value" $.Values.service.annotations "context" $) | nindent 4 }}
    {{- end }}
  spec:
    type: {{ $.Values.service.type }}
    {{- if eq $.Values.service.type "LoadBalancer" }}
    {{- if not (empty $.Values.service.loadBalancerIP) }}
    loadBalancerIP: {{ $.Values.service.loadBalancerIP }}
    {{- end }}
    {{- if $.Values.service.loadBalancerSourceRanges }}
    loadBalancerSourceRanges: {{- toYaml $.Values.service.loadBalancerSourceRanges | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if $.Values.service.externalIPs }}
    externalIPs: {{- toYaml $.Values.service.externalIPs | nindent 4 }}
    {{- end }}
    ports:
      - name: {{ $.Values.service.portName }}
        port: {{ $.Values.service.port }}
        targetPort: amqp
        {{- if (eq $.Values.service.type "ClusterIP") }}
        nodePort: null
        {{- else if and (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) (not (empty $.Values.service.nodePort)) }}
        nodePort: {{ $.Values.service.nodePort }}
        {{- end }}
      {{- if $.Values.auth.tls.enabled }}
      - name: {{ $.Values.service.tlsPortName }}
        port: {{ $.Values.service.tlsPort }}
        targetPort: amqp-ssl
        {{- if (eq $.Values.service.type "ClusterIP") }}
        nodePort: null
        {{- else if and (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) (not (empty $.Values.service.tlsNodePort)) }}
        nodePort: {{ $.Values.service.tlsNodePort }}
        {{- end }}
      {{- end }}
      - name: {{ $.Values.service.epmdPortName }}
        port: 4369
        targetPort: epmd
        {{- if (eq $.Values.service.type "ClusterIP") }}
        nodePort: null
        {{- else if (and (eq $.Values.service.type "NodePort") (not (empty $.Values.service.epmdNodePort))) }}
        nodePort: {{ $.Values.service.epmdNodePort }}
        {{- end }}
      - name: {{ $.Values.service.distPortName }}
        port: {{ $.Values.service.distPort }}
        targetPort: dist
        {{- if eq $.Values.service.type "ClusterIP" }}
        nodePort: null
        {{- else if (and (eq $.Values.service.type "NodePort") (not (empty $.Values.service.distNodePort))) }}
        nodePort: {{ $.Values.service.distNodePort }}
        {{- end }}
      - name: {{ $.Values.service.managerPortName }}
        port: {{ $.Values.service.managerPort }}
        targetPort: stats
        {{- if eq $.Values.service.type "ClusterIP" }}
        nodePort: null
        {{- else if (and (eq $.Values.service.type "NodePort") (not (empty $.Values.service.managerNodePort))) }}
        nodePort: {{ $.Values.service.managerNodePort }}
        {{- end }}
      {{- if $.Values.metrics.enabled }}
      - name: {{ $.Values.service.metricsPortName }}
        port: {{ $.Values.service.metricsPort }}
        targetPort: metrics
        {{- if eq $.Values.service.type "ClusterIP" }}
        nodePort: null
        {{- else if (and (eq $.Values.service.type "NodePort") (not (empty $.Values.service.metricsNodePort))) }}
        nodePort: {{ $.Values.service.metricsNodePort }}
        {{- end }}
      {{- end }}
      {{- if $.Values.service.extraPorts }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.service.extraPorts "context" $) | nindent 4 }}
      {{- end }}
    selector: {{ include "common.labels.matchLabels" $ | nindent 4 }}
      statefulset.kubernetes.io/pod-name: rabbitmq-{{ $e }}
  ---
  {{- end }}
  ```
</details>

Nevertheless, I'm not sure if having a service per each node is necessary. AFAIK, the whole cluster can be configured accessing any of the nodes right?
