### ISSUE TITLE
Airflow Doc update

### ISSUE THREAD

**Issue by coelacanth16** [bitnami/charts#4420]
**Which chart**:
bitnami/airflow

**Is your feature request related to a problem? Please describe.**
The description for _airflow.auth.existingSecret_ is currently "Name of an existing secret containing airflow password and fernet key"
This does not say what the keys should be (_airflow-password_ and _airflow-fernetKey_), like it does for _postgresql.existingSecret_ and _redis.existingSecret_.

**Describe the solution you'd like**
Update the README.md to reflect these keys

**Comment by juan131** [comment]
Hi @coelacanth16 

Thanks so much for your feedback. I include your suggestion as part of the major changes we're including at https://github.com/bitnami/charts/pull/4069
