### ISSUE TITLE
Airflow values.yaml default format for cloneDagFilesFromGit

### ISSUE THREAD

**Issue by coelacanth16** [bitnami/charts#4421]
**Which chart**:
bitnami/airflow

**Describe the bug**
When running _helm install <deploymentName> -f values.yaml  bitnami/airflow_ the script expects the airflow.cloneDagFilesFromGit parameters to be flat keys (repository, name, branch, path) instead of in an array called repositories, as they are defaulted to in the values.yaml and values-production.yaml

**To Reproduce**
set the keys in the values.yaml to:
```
cloneDagFilesFromGit:
    enabled: true
    repositories:
    - repository: "https://github.com/myname/mydagsrepo"
      name: "dags"
      branch: "master"
      path: "dags"
```

**Expected behavior**
Accept an array without error or change the default structure in values.yaml and values-production.yaml to not suggest using an array

**Version of Helm and Kubernetes**:

- Output of `helm version`: 
```version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}```

```
Error: template: airflow/templates/NOTES.txt:80:3: executing "airflow/templates/NOTES.txt" at <include "airflow.validateValues" .>: error calling include: template: airflow/templates/_helpers.tpl:347:51: executing "airflow.validateValues" at <fail>: error calling fail: 
VALUES VALIDATION:
airflow: airflow.cloneDagFilesFromGit.repository
    The repository must be provided when enabling downloading DAG files
    from git repository (--set airflow.cloneDagFilesFromGit.repository="xxx")
airflow: airflow.cloneDagFilesFromGit.branch
    The branch must be provided when enabling downloading DAG files
    from git repository (--set airflow.cloneDagFilesFromGit.branch="xxx")
```

This could have been a future feature that was never implemented in the _helpers.tpl or maybe a merge error?

**Comment by marcosbc** [comment]
Hi @coelacanth16, my understanding is that this was recently changed in #3804, and it should work as you expect if you're using a current chart release (i.e. 6.7.2). Could you verify that you are using the latest chart?

Note that I was able to use your changes to values.yaml without issues in the current chart.

**Comment by coelacanth16** [comment]
I'm using what is getting served up through the repo at https://charts.bitnami.com/bitnami by way of helm - the master branch as of yesterday. No other customizations.

**Comment by marcosbc** [comment]
I have been able to deploy it without issues with the values.yaml file you provided:

```console
$ cat >myvalues.yaml <<EOF
airflow:
  cloneDagFilesFromGit:
    enabled: true
    repositories:
    - repository: "https://github.com/myname/mydagsrepo"
      name: "dags"
      branch: "master"
      path: "dags"
EOF
$ helm install myairflow -f myvalues.yaml --set airflow.baseUrl=http://myairflow.com bitnami/airflow
NAME: myairflow
LAST DEPLOYED: Thu Nov 19 17:07:59 2020
...
```

I can also see it is properly configured with those values:

```console
$ helm template myairflow -f myvalues.yaml --set airflow.baseUrl=http://myairflow.com bitnami/airflow
...
      initContainers:
        - name: git-clone-repository
          image: docker.io/bitnami/git:2.29.0-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/bash
            - -ec
            - |
                git clone https://github.com/myname/mydagsrepo --branch master /dags-dags
          volumeMounts:
            - name: git-cloned-dag-files-dags
              mountPath: /dags-dags
...
```

Could you make sure that your Helm repo is [updated](https://helm.sh/docs/helm/helm_repo_update/)? Let me know if I'm missing anything.

**Comment by coelacanth16** [comment]
After updating my helm repo (which I didn't understand I needed to do, even though you said that first), it works, accepting an array. Thanks for your patience, I think it's safe to close this.
