### ISSUE TITLE
TLS certificate secrets provided via `ingress.secrets` values are not created when installing Airflow

### ISSUE THREAD

**Issue by roanosullivan** [bitnami/charts#4425]
Airflow chart seems to be missing templates/tls-secret.yaml.

**Comment by marcosbc** [comment]
Hi @roanosullivan, we're happy to review any external contributions via PRs to implement new features to Bitnami Helm charts. Would you be open to sending a PR for adding TLS secrets support to the Bitnami AirFlow chart?
