### ISSUE TITLE
Mitigate DockerHub rate limit issue

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#4430]
As described [here](https://www.docker.com/increase-rate-limits), since some days ago the rate limit for Docker images hosted in DockerHub was modified. By default, the Bitnami Helm Charts are using DockerHub (docker.io) as the default repository for the images, so it's possible you face any issue related to the new limits.

If you were affected by these changes you would have received an error message:
```
ERROR: toomanyrequests: Too Many Requests.
```
or
```
You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits.
```

Please, see below different alternatives to solve/relax those issues.

In the _values.yaml_ of every Bitnami Helm Charts we can see a `global` section with, at least, the following parameters:
```yaml
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagepullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
```
as described in the comment, the parameters set under this `global` section are going to be applied to the main chart and all the subcharts, modifying the registry and secret for all the images present in the different charts.

By modifying those parameters we have different ways to solve or relax the rate limit issue:

#### Using a free Docker account

> The rate limits will be progressively lowered to a final state of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts.

The first option is to use a secret with our Docker credentials, using this approach we can pull 200 images per 6 hours instead of the 100 images for anonymous users.

We can [create a secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) with our Docker credentials and use the `global.imagePullSecrets` parameter to use that secret.

#### Using another registry such as gcr.io

All the Bitnami container images are pushed to docker.io but also to other registries like gcr.io. Setting the `global.imageRegistry` parameter we can use a different registry to pull the images from.

In this case, the images can be hosted under a different path in the new registry, if that is the case we need to modify the `image.repository` parameter. For example, in the case of docker.io images are stored under `docker.io/bitnami/APP` while in gcr.io, those images are stored in `gcr.io/bitnami-containers/APP`, in this case, we should modify the path.

We can do it by running `sed -i "s@repository: bitnami/@repository: bitnami-containers/@g" values.yaml`
```diff
-# global:
-#   imageRegistry: myRegistryName
+global:
+  imageRegistry: gcr.io
...
-  repository: bitnami/kong
+  repository: bitnami-containers/kong
...
-   repository: bitnami/kong-ingress-controller
+   repository: bitnami-containers/kong-ingress-controller
```
If it is needed to also modify the `repository` parameter for the subcharts images, we will need to override the parameters in the subchart section, following with the kong example, there are a `postgresql` section and the end of the values; in that section, we need to add the `image.repository` parameter with the new path:
```diff
## PostgreSQL properties
##
postgresql:
+  image:
+    repository: bitnami-containers/postgresql
```

Please, note in some cases both methods should be used together as it's possible to use a new registry that needs credentials, in that case, we need to change the `imageRegistry` as well as the `imagePullSecrets`

**Comment by kacole2** [comment]
I know this isn't a support forum... I've created a Kubernetes secret but when I try to run `helm install kubeapps --namespace kubeapps bitnami/kubeapps --set global.imagePullSecrets=dhsecret` I'm getting a parse error:

```
Error: template: kubeapps/charts/postgresql/templates/statefulset.yaml:45:4: executing "kubeapps/charts/postgresql/templates/statefulset.yaml" at <include "postgresql.imagePullSecrets" .>: error calling include: template: kubeapps/charts/postgresql/templates/_helpers.tpl:309:17: executing "postgresql.imagePullSecrets" at <.Values.global.imagePullSecrets>: range can't iterate over dhsecret
```

Is there something special I need to run at the command line level for this?

**Comment by kacole2** [comment]
I think I found the answer is it requires the use of brackets.

```
helm install kubeapps --namespace kubeapps bitnami/kubeapps --set global.imagePullSecrets={dhsecret}
```

**Comment by dani8art** [comment]
Hi @kacole2 thanks for your comment, yes, it is because the `global.imagePullSecrets` is an array. You could also use:

```
$ helm install kubeapps --namespace kubeapps bitnami/kubeapps --set global.imagePullSecrets[0]=dhsecret
```

**Comment by paulczar** [comment]
I think we've hit the point where it would make sense for vmware/bitnami to run a dedicated repository for Bitnami images, The errors that are created when the dockerhub limits are hit are hidden behind pod statuses, and it would be easy to assume it was a Bitnami error, not a dockerhub rate limits error.

For the sake of a smooth first user experience, its not great that I'd have to figure out the errors, and then google until I find this thread and update global registry settings.

**Comment by carrodher** [comment]
Thanks for the suggestion, we're evaluating different options, but in the meantime, the above instructions are the way to try to avoid (or minimize) the Docker Hub limit. Maybe we can make this pinned issue more visible for users.

**Comment by DavidSpek** [comment]
Open source projects can ask for exceptions to the docker hub rate limiting. You can find out more about this program [here](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/). I’d also like to caution against the ECR Public Gallery at this point in time as I’ve gone into detail about in [this issue](https://github.com/kubeflow/kubeflow/issues/5922). TL;DR, the ECR Public Gallery lacks the basic features needed for a public registry (like a publicly accessible API endpoint for listing tags) and has a rate limit of 500 GB per month, which depending on the image sizes can be very few pulls.

**Comment by carrodher** [comment]
Thanks for the information, I will forward this comment to the appropriate team in order to investigate this path.

**Comment by ctron** [comment]
This is pretty annoying, and I think there are other services out there like quay.io or ghcr.io which would not have this problem.

**Comment by carrodher** [comment]
Bitnami images are pushed by default to different registries, for example:
```console
$ docker images
REPOSITORY                         TAG       IMAGE ID       CREATED        SIZE
public.ecr.aws/bitnami/apache      2.4       3156fbf7dfbd   23 hours ago   176MB
quay.io/bitnami/apache             2.4       3156fbf7dfbd   23 hours ago   176MB
docker.io/bitnami/apache                     2.4       3156fbf7dfbd   23 hours ago   176MB
gcr.io/bitnami-containers/apache   2.4       3156fbf7dfbd   23 hours ago   176MB
```

The GitHub registry (ghcr.io) is very recent so we are not pushing the images there by the moment, but it is also something we are evaluating.

As described above, Helm Charts allow users to choose the registry from where they prefer to pull the images, but a default registry should be set; in this case, the default registry is DockerHub for being the most used platform and that previously did not have these limitations. We are working on different approaches to get rid of this limitation, this thread will be updated with more info once clarify the approach we will follow.

**Comment by ctron** [comment]
> Bitnami images are pushed by default to different registries, …:

This is great. And it should be the default. Otherwise people just run into this problem over and over again.

**Comment by beltran-rubo** [comment]
Bitnami is now part of Docker Verified Published Program, you can read more info at https://blog.bitnami.com/2021/07/vmware-joins-docker-verified-publisher.html 

**Bitnami container and Helm Chart users will benefit from being exempt from the rates limiting from DockerHub**.
