### ISSUE TITLE
[bitnami/cassandra] Support for Casandra 4.0.0

### ISSUE THREAD

**Issue by jemantheiy** [bitnami/charts#4431]
bitnami/cassandra 

Support for the newest Cassandra 4.0.0 when it's no longer in beta.  Some great improvements have been made with Cassandra 4.0 including java 11 and storage utilization.

**Comment by carrodher** [comment]
Our system is tracking https://downloads.apache.org/cassandra/ to detect new Cassandra stable versions, when a new version appears we work on the required changes to release the container images and then update the Helm Chart to use the new containers (usually bumping the chart version in a major).
This process is not 100% automated, some days of delay are expected when it is needed to incorporate a new major version to the catalog.
