### ISSUE TITLE
[bitnami/postgresql-ha] add an option to disable pgpool

### ISSUE THREAD

**Issue by anatoliy-balakirev** [bitnami/charts#4432]
**Which chart**:
`postgresql-ha`

**Is your feature request related to a problem? Please describe.**
I would like to use HA Postgresql in my Spring Boot project. I do not want to use `pgpool`, but the built in Hikari instead. Still, I want to use `pgmgr` (which is part of the `postgresql-ha` helm chart) to have my Postgres instances higly available. Currently I can set `postgresql-ha.pgpool.replicaCount` to 0, but there are still `pgpool` dedicated services and deployments (with 0 pods) created. I would like to have an option to disable it alltogether.

**Describe the solution you'd like**
Introduce a new `postgresql-ha.pgpool.enabled` flag, which is enabled by default, and wrap all resources in the `templates/pgpool` folder with that new flag.

**Describe alternatives you've considered**
Setting `postgresql-ha.pgpool.replicaCount` to 0, but we still have not needed resources created. Also, it looks like it doesn't work well with Helm's `--wait` flag as it fails with timeout eventually even though everything is there (but I'm not 100% sure here).

**Comment by anatoliy-balakirev** [comment]
I could even create a PR if this idea is ok for everyoe.

**Comment by anatoliy-balakirev** [comment]
After further playing with that I realized, that it's not so easy to manually manage connection to the primary postgres node, so not sure if it's actually a good idea to disable pgpool.

**Comment by miguelaeh** [comment]
Hi @anatoliy-balakirev ,
Feel free to ask any question you may have in the future.
Reagards.

**Comment by popen2** [comment]
Hello, I'd actually really like the option to disable the pgpool deployment as I'm running it as a sidecar in my deployment. After some trial and error this configurations seems to work really well:

- postgresql-ha running 3 database nodes with PDB allowing one failure
- pgpool running as a sidecar in the app pod

This can handle database upgrades plus app upgrades, potentially both.

Right now I'm setting the `replicaCount` of pgpool deployment to `0`, but it would still be nice not to deploy it altogether.
