### ISSUE TITLE
kubectl get secret spews out a gibberish from Jenkins

### ISSUE THREAD

**Issue by organicnz** [bitnami/charts#4444]
Hey guys, how to fix this base64 decoding? It spews out this gibberish from `bitnami/jenkins` pod :)

`printf $(kubectl get secret --namespace default jenkins-1605736819 -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo`
`�K��ly�޷�jg���u�ں"�ϵ�N{߯5��#��`

Have tried without decoding, but it hasn't helped so far: 
[https://pastebin.com/n01mWrRC](https://pastebin.com/n01mWrRC)

`kubectl get secret` shows up `jenkins-password` in plain text, however, Jenkins doesn't digest it with the `admin` profile name: [https://pastebin.com/65bMbuED](https://pastebin.com/65bMbuED)

Chart:
`bitnami-jenkins   	default  	1       	2020-11-20 04:52:24.42784 +0300 MSK 	deployed       	jenkins-6.0.0 	2.249.3`

OS:
macOs: 11.01

**Comment by andresbono** [comment]
Hi @organicnz, I'm not really sure what is happening there. When the chart is deployed, some notes are shown with information about the commands that you need to execute to obtain the credentials. You can obtain those notes again by executing:

```
helm get notes YOUR_INSTALLATION_NAME
```

You will find a command like the following one:

```
echo Password: $(kubectl get secret --namespace default YOUR_INSTALLATION_NAME -o jsonpath="{.data.jenkins-password}" | base64 --decode)
```

If you want to do what the command above is doing in a more manual way, you can also get the secret and output as yaml and you will get a plain-text string that is base64-encoded. You need to decode it to get the actual password.

If the implementation of your base64 utility is buggy, just for testing purposes, you can use an online tool like this one: https://emn178.github.io/online-tools/base64_decode.html

Again, this is just for testing purposes, you should never share your password on the internet.

**Comment by organicnz** [comment]
Hi @andresbono,

thanks, mate, that website above did its work it decoded a string right. I'll check out that issue on the new version of macOS 11.0.1.

I'll close that issue for now.
