### ISSUE TITLE
Troubleshooting page linked in bug template does not exist

### ISSUE THREAD

**Issue by morremeyer** [bitnami/charts#4450]
**Which chart**:

None.

**Describe the bug**

The bug template contains:

``` 
<!--
 Before you open the bug report please review the following troubleshooting guide:

 - [Troubleshoot Bitnami Helm Chart Issues](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues)
 -->
``` 

**To Reproduce**

1. [Open a new bug issue](https://github.com/bitnami/charts/issues/new/choose)

**Expected behavior**
The linked document exists.

**Version of Helm and Kubernetes**: irrelevant

**Additional context**

I tried googling the appropriate page, but this only let’s me find missing pages, too.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. It seems that the link was recently changed. It is still under discussion what the final link should be. Just in case, I created a PR to point to the current link.

**Comment by juan131** [comment]
The links are correct now @javsalgar. Check by browsing to https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues
Thanks again for reporting this @morremeyer
