### ISSUE TITLE
[bitnami/postgresql-ha] pgpool.maxPool default value is wrong in docs?

### ISSUE THREAD

**Issue by anatoliy-balakirev** [bitnami/charts#4452]
**Which chart**:
postgresql-ha

**Describe the bug**
In the documentation here: https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/README.md for the parameter `pgpool.maxPool` it says that default value is 15. In the deployment I see it is passed as is, not providing default (https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/pgpool/deployment.yaml#L209-L211):
```
- name: PGPOOL_MAX_POOL
  value: {{ .Values.pgpool.maxPool | quote }}
```
I.e. I assume that the default will be coming from the pgpool itself. Checking docs of pgpool I see the default value for `max_pool` is 4 (https://www.pgpool.net/docs/pgpoolAdmin/en/pgconfig.html).
So there seems to a bug in docs of bitnami.

**Comment by miguelaeh** [comment]
Hi @anatoliy-balakirev ,
this default value comes from the default value of that env var in the bitnami container.
You can check it here: https://github.com/bitnami/bitnami-docker-pgpool/blob/48cde0135e80854881ea48e36a0869832a68f825/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L70
