### ISSUE TITLE
[bitnami/wordpress] externaldb secret name does not match the configured name in deployment

### ISSUE THREAD

**Issue by acim** [bitnami/charts#4454]
**Which chart**:

bitnami/wordpress 10.0.2

**Describe the bug**

Name of the created externaldb secret doesn't match the secret name used to create WORDPRESS_DATABASE_PASSWORD environment variable.

Secret name is defined like this:

https://github.com/bitnami/charts/blob/e383a6e3286c6202f3a09618fb5584b69a8ee98d/bitnami/wordpress/templates/externaldb-secrets.yaml#L5

And in the deployment, there is:

https://github.com/bitnami/charts/blob/e383a6e3286c6202f3a09618fb5584b69a8ee98d/bitnami/wordpress/templates/deployment.yaml#L94

Further, this wordpress.databaseSecretName is defined here:

https://github.com/bitnami/charts/blob/e383a6e3286c6202f3a09618fb5584b69a8ee98d/bitnami/wordpress/templates/_helpers.tpl#L97

```
{{- if .Values.mariadb.enabled }}
    {{- printf "%s" (include "wordpress.mariadb.fullname" .) -}}
{{- else if .Values.externalDatabase.existingSecret -}}
    {{- printf "%s" .Values.externalDatabase.existingSecret -}}
{{- else -}}
    {{- printf "%s-%s" .Release.Name "externaldb" -}}
{{- end -}}
```

So,  {{ printf "%s-externaldb" (include "common.names.fullname" .) }} is not equal to {{- printf "%s-%s" .Release.Name "externaldb" -}}, basically word wordpress is missing in the later one meaning deployment produces crashing pods.

**To Reproduce**

Install chart with external database but without external database existing secret.

mariadb.enabled=false
externalDatabase.existingSecret not defined.

**Expected behavior**

The cart works.

**Version of Helm and Kubernetes**:

Helm 3, exact version not relevant.

- Output of `helm version`:

Not relevant.

- Output of `kubectl version`:

Not relevant.

**Additional context**

**Comment by FraPazGal** [comment]
Hello @acim,

Thanks for bringing up this bug! It seems that if you use a chart name that doesn't contain the application name, the two entries you pointed will indeed have different name. 

I'll create a PR to solve this issue so it is fixed as soon as possible!
