### ISSUE TITLE
Discussion about chart version labels on PodSpec ("helm.sh/chart")

### ISSUE THREAD

**Issue by mkilchhofer** [bitnami/charts#4455]
**Which chart**:
I think all charts are affected for this discussion.

**Is your feature request related to a problem? Please describe.**
I wanted to start a discussion about the labels on Pods.

As far as I can see, all bitnami charts are are putting chart version specific labels both on Deployment/StatefulSet meta level and on PodTemplateSpec level.
On our internal application charts we only put minimal labels inside PodTemplateSpec to allow upgrading the chart version without unnecessary pod restarts. The mentioned "minimal labels" is mostly equivalent to bitnamis common chart function `common.labels.matchLabels`.

**Describe the solution you'd like**
Switch function `common.labels.standard` to `common.labels.matchLabels` on PodTemplateSpec.

**Describe alternatives you've considered**
Provide a new label function without this label:
```yaml
helm.sh/chart: "<chart name>-<chart version>"
```

**Additional context**
`-`

**Comment by juan131** [comment]
Hi @mkilchhofer 

Bitnami charts use the labels recommended by Helm. See https://helm.sh/docs/chart_best_practices/labels/

You can also double-check this by running:

```console
$ helm create foo
```

And inspecting the `foo/templates/_helpers.tpl` file.

Please note that, although we're using `common.labels.standard` in the deploymen/statefulset to set the `spec.template.metadata.labels`, we're using `common.labels.matchLabel` to set the `spec.selector.matchLabels`. Therefore, the pods will be considered as part of the ReplicaSet created by Deployment/Statefulset regardlesss the values set to `"helm.sh/chart"`.

**Comment by mkilchhofer** [comment]
Hi @juan131 
You might be correct for an older version of helm. When I run this command with helm `v3.3.0`, the manifests looks like this:
```console
$ helm3 create foochart
Creating foochart
$ cd foochart/
$ helm3 version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
$ helm3 template .
---
# Source: foochart/templates/serviceaccount.yaml
(..)
---
# Source: foochart/templates/service.yaml
(..)
---
# Source: foochart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-foochart
  labels:
    helm.sh/chart: foochart-0.1.0
    app.kubernetes.io/name: foochart
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foochart
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foochart
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-foochart
      securityContext:
        {}
      containers:
        - "(...)"
---
# Source: foochart/templates/tests/test-connection.yaml
(..)
```
Inside the deployment.yaml it looks like this:
```console
$ cat templates/deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foochart.fullname" . }}
  labels:
    {{- include "foochart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "foochart.selectorLabels" . | nindent 6 }} <----------------------------------- see here
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "foochart.selectorLabels" . | nindent 8 }} <----------------------------------- see here
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "foochart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: (..)
```

**Comment by juan131** [comment]
Hi @mkilchhofer 

You're right.. My comment was based on the skeleton Helm2 used to create.

I gave a try to see if this implies a backwards incompatibility.. It seems it does not:

- Install NGINX:

```
$ helm install nginx bitnami/nginx
```

- Edit NGINX to include your suggested changes, and upgrade the release:

```
$ vim bitnami/nginx/templates/deployment.yaml
$ git diff
diff --git a/bitnami/nginx/templates/deployment.yaml b/bitnami/nginx/templates/deployment.yaml
index 2fd990049..cad90a7ba 100644
--- a/bitnami/nginx/templates/deployment.yaml
+++ b/bitnami/nginx/templates/deployment.yaml
@@ -15,7 +15,7 @@ spec:
     matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
   template:
     metadata:
-      labels: {{- include "common.labels.standard" . | nindent 8 }}
+      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
         {{- if .Values.podLabels }}
         {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
         {{- end }}
$ helm upgrade nginx bitnami/nginx
$ kubectl get deployments
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           17m
$ kubectl get replicaset
NAME               DESIRED   CURRENT   READY   AGE
nginx-649cc6fbc5   1         1         1       53s
nginx-89854f4fc    0         0         0       17m
```

Everything seems to be working as expected after the changes and the solution could be upgraded.

@javsalgar @carrodher what do you think about this?

**Comment by javsalgar** [comment]
My main concern is that if this will affect the immutable fields in a StatefulSet. If they are unaffected, I'm fine by following the default helm 3 skeleton.

**Comment by srueg** [comment]
> My main concern is that if this will affect the immutable fields in a StatefulSet. If they are unaffected, I'm fine by following the default helm 3 skeleton.

Since we don't have to change the `selector` part of the StatefulSet/Deployment and only the `.spec.template.metadata.labels` (which is mutable) it should be fine. I did a quick test setting a new label on an existing StatefulSet and it worked as expected 👍

**Comment by juan131** [comment]
Yes! I think we should go ahead with these changes on every chart.
A final call for core maintainers to double-check this: @carrodher @dani8art @javsalgar

**Comment by rafariossaa** [comment]
I have created an internal task to analyze this request and how it would affect the charts

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
