### ISSUE TITLE
[bitnami/nginx] Add a PodDisruptionBudget

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#4460]
**Which chart**:
The name (and version) of the affected chart.

`bitnami/nginx`

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

It would be nice to have a `PodDisruptionBudget`-option built-in.

**Describe alternatives you've considered**

**Additional context**

**Comment by FraPazGal** [comment]
Hello @aeimer,

That would indeed a good addition to our chart, thanks for bringing this up! That been said, we are a small team and with the coming holiday season it would be difficult to work on this feature. If you would like, you can create a PR to contribute to the chart. You can use one of our charts ([bitnami/cassandra](https://github.com/bitnami/charts/tree/master/bitnami/cassandra) for example) as reference, we will be glad to review it and add it to our repo!

**Comment by aeimer** [comment]
https://github.com/bitnami/charts/pull/4479

Done, I'll test it and tick the things on the checklist.

**Comment by aeimer** [comment]
@FraPazGal can we merge it or are there any things I need to do?

**Comment by aeimer** [comment]
Oh never mind, Ill close the ticket
