### ISSUE TITLE
Airflow initdb and resetdb run on every pod start 

### ISSUE THREAD

**Issue by aditi-agarwal-tw** [bitnami/charts#4466]
**Which chart**:
Bitnami Airflow (web, scheduler, worker), version: 1.10.10-debian-10-r79

**Describe the bug**
We are deploying airflow into Azure AKS using the Bitnami Airflow Helm Chart which calls the following Dockerfile: https://github.com/bitnami/bitnami-docker-airflow-worker/blob/master/1/debian-10/Dockerfile

We noticed that when the container comes up, it always runs airflow initdb and airflow resetdb, even though the DB is available and initialized. We want to understand why does bitnami initialize the db, everytime the container comes up?

Also, we notice that this causes a lot of startup time and the container takes > 15 minutes - 45 minutes (depending on the size of the dag files/how old the Db is?). Can you please help us understand what could be causing the delay?

Thank you

**To Reproduce**
Set the Log-level to DEBUG and check the logs when the container comes up. It runs airlfow initdb.

**Expected behavior**
If the DB is already initialised and has the necessary tables, why are we still running initdb and resetdb commands.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
Helm v2
```
(paste your output here)
```
- Output of `kubectl version`:
Azure Kubernetes - 1.18.8
```
(paste your output here)
```

**Additional context**

**Comment by alemorcuq** [comment]
Hi, @aditi-agarwal-tw. 

Those commands are run to generate an `airflow.cfg` config file when no configuration file is provided. Are you using a custom config file?

**Comment by aditi-agarwal-tw** [comment]
Hello @alemorcuq 

Thank you for getting back. At this moment we are not providing a custom config file. Instead we are setting all the required variables, e.g. DB config, Redis config etc via the env variables.

I understand why initdb is running, however, we also saw that despite us giving the Postgres DB configuration in environment variables, when initdb is run, it is initializing a local sqlite db and running intidb and resetdb against that? Is there a reason for that? We would have expected it to use the Postgres DB config provided.

Thank you.

**Comment by dani8art** [comment]
Hi @aditi-agarwal-tw we were investigating and yes it seems like airflow is performing an `initdb` action against an SQLite every time it is restarted, also `resetdb` is executed.

```
airflow TRACE [runProgram] Executing internal command: '/bin/sh' ["-c","/opt/bitnami/airflow/venv/bin/airflow initdb"]
airflow TRACE [runProgram] RESULT: {"code":0,"stderr":"INFO  [alembic.runtime.migration] Context impl SQLiteImpl.\nINFO...
```

The first time it is initialized, those actions are executed against PostgreSQL as well.

```
airflow TRACE [runProgram] Executing internal command: '/bin/sh' ["-c","/opt/bitnami/airflow/venv/bin/airflow initdb"]
airflow TRACE [runProgram] RESULT: {"code":0,"stderr":"INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.\nINFO
```

We would like to check if those actions are needed or we should remove them. 

Thanks!

**Comment by dani8art** [comment]
Hi @aditi-agarwal-tw we have been checking this and it seems both actions `initdb` and `resetdb` are performed in order to generate initials config files where we apply the corresponding overrides after. They are performed against an SQLlite database because at this point of the initialization logic there is no other database configured. After that, we remove the `db` generated file and configure it properly. Those commands don't only generate configurations related to the database so we need to execute them.

```
$app.helpers.generateConfFile = function() {
  $os.runProgram('venv/bin/airflow', 'initdb', {env: {AIRFLOW_HOME: $app.installdir}});
  $os.runProgram('venv/bin/airflow', 'resetdb', {input: 'y', env: {AIRFLOW_HOME: $app.installdir}});
  $file.delete($file.join($app.installation.root, 'airflow/airflow.db'));
};
```
