### ISSUE TITLE
[bitnami/postgresql] Upgrade from 9.8.12 to 10.1.0 failed

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#4468]
**Which chart**:
The name (and version) of the affected chart
bitnami/postgresql 10.1.0

**Describe the bug**
The helm upgrade from 9.8.12 to 10.1.0 failed (using latest terraform helm provider). I think it would also happen on bare helm upgrade.

*error*
```
cannot patch "postgresql-postgresql" with kind StatefulSet: StatefulSet.apps "postgresql-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**To Reproduce**

1. deploy bitnami/postgresql 9.8.12 chart
2. try to upgrade to 10.1.0
3. see error 

**Expected behavior**
Should simply deploy the update

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

- terraform versions
```hcl
terraform {
  required_providers {
    docker = {
      source  = "terraform-providers/docker"
      version = "2.7.2"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "1.3.2"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "1.13.3"
    }
  }
  required_version = ">= 0.13"
}
```

**Comment by FraPazGal** [comment]
Hello @viceice,

It seems the update instructions on our [README](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#to-1000) could be improved a bit as we also need to take note of the existing PVC given the change from using `master` to `primary`. Could you try the following steps and confirm if the work for you? I'll like to have them added to the README after your input.

Please, create a backup of your database before running any of those actions:

```
$ helm install postgresql bitnami/postgresql --version 9.8.12
$ export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace default postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ export POSTGRESQL_PVC=$(kubectl get pvc -l app.kubernetes.io/instance=postgresql,role=master -o jsonpath="{.items[0].metadata.name}")
$ kubectl delete statefulsets.apps postgresql-postgresql --cascade=false
$ helm upgrade postgresql bitnami/postgresql --set postgresqlPassword=$POSTGRESQL_PASSWORD --set persistence.existingClaim=$POSTGRESQL_PVC
$ kubectl delete pod postgresql-postgresql-0
```

**Comment by viceice** [comment]
ok, just deleting the statefulset before upgrading does the trick, no data loss.

**Comment by mlopez-eb** [comment]
@viceice that is frightening
