### ISSUE TITLE
[harbor] Upgrading to v9.0.0 deletes Postgres database

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#4471]
**Which chart**:
Harbor 9.0.0

**Describe the bug**
When upgrading to chart version 9.0.0, the postgresql statefulsets (and their pvcs) are deleted and recreated with new names - all data is destroyed. 

**To Reproduce**

1. Upgrade from v8 to v9 of the harbor helm chart

**Expected behavior**
Upgrades should not suddenly destroy the database.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @ajchiarello 

All the details and consequences of upgrading to latest major version **9.0.0** are explained in the chart's README.md:

- https://github.com/bitnami/charts/tree/master/bitnami/harbor#to-900

Please take a look when you have a chance.

**Comment by ajchiarello** [comment]
Thanks. I didn't see the upgrades section at the bottom before, but will check it first from now on.
