### ISSUE TITLE
charts/redis-cluster disable persistence

### ISSUE THREAD

**Issue by guiajlopes** [bitnami/charts#4484]
Hi,

Is it possible to disable RDB in the redis-cluster chart? I tried to disable persistence but when I run `config get save` it still shows that it's enabled. Is it possible to disable it? I want to run redis cluster without any storage, only in memory since I'm using only for cache

Thanks

**Comment by javsalgar** [comment]
Hi,

You could try adding your custom redis.conf file in the `redis.configmap` section of the chart. That would allow you to disable whatever setting you need. Also, you could set `persistence.enabled` to false.

**Comment by guiajlopes** [comment]
Thanks @javsalgar, do you have an example of how to use `redis.configmap`?

**Comment by javsalgar** [comment]
You can set it in the values.yaml like this

```
redis:
  configmap: |
     # here put your redis.conf file
```

**Comment by guiajlopes** [comment]
thanks @javsalgar

**Comment by anessi** [comment]
In #13545 support to disable persistence (uses emptyDir instead of a PVC) has been added. This is required if one wants to use Redis with in-memory data only. It makes sense to disable AOF and RDB persistence in the config in that case.

```
redis:
  configmap: |
    
    # Custom Configuration
    # Disable AOF and RDB persistence as we keep everything in memory only, see https://redis.io/topics/persistence
    appendonly no
    # Disable RDB persistence, AOF persistence already disabled above.
    save ""
```
