### ISSUE TITLE
[mongodb-sharded] mongos as statefulset

### ISSUE THREAD

**Issue by alexsergin** [bitnami/charts#4499]
**Which chart**:
mongodb-sharded

**Is your feature request related to a problem? Please describe.**
When using more than 1 replicas of mongos and multiple connections via the service we get cursor not found exception. It happens because queries go to different mongos instances. Especially it happens with Spring Framework and Spring Data.

**Describe the solution you'd like**
The only way to solve the issue is to pass all mongos uris in connection string. But with deployment kind it's now possible because pod name always different. Would be better to convert mongos to StatefulSet so we can use static routes to mongos like `mongos-0.infra-mongodb-sharded.default.svc.cluster.local`

**Describe alternatives you've considered**
We tried to set `sessionAffinity: "ClientIP"` for the service but it doesn't solve the issue at all. Sometimes we still get the error.

**Comment by dani8art** [comment]
Hi @alexsergin it may make all the sense, in fact, we think this should not break backward compatibility.

We will give it a try during the next weeks to have the first approach as PR, however, we would be happy if you have a chance to develop this great improvement and contribute to our charts. Do you think this is possible? if yes, we can guide you.

Thanks

**Comment by alexsergin** [comment]
Hi @dani8art. Yes, guess I will be able to do that next week. Will send the PR.

**Comment by dani8art** [comment]
That's great!! thanks, will keep in touch!

**Comment by alexsergin** [comment]
> That's great!! thanks, will keep in touch!

Hi @dani8art. I've made all changes. Check that out pls.

**Comment by marcosbc** [comment]
Thanks for the PR! We'll check it shortly.
