### ISSUE TITLE
[external-dns] chart in repo is out of date

### ISSUE THREAD

**Issue by bootc** [bitnami/charts#4500]
**Which chart**:
external-dns

**Describe the bug**
The `external-dns` chart in the chart repo is not up to date.

**To Reproduce**
https://artifacthub.io/packages/helm/bitnami/external-dns lists version 4.0.0 is current.

```
$ helm search repo bitnami/external-dns
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                                       
bitnami/external-dns	4.0.0        	0.7.4      	ExternalDNS is a Kubernetes addon that configur...
```

However, https://github.com/bitnami/charts/blob/master/bitnami/external-dns/Chart.yaml is up to version 4.3.1. No updates have made it since https://github.com/bitnami/charts/pull/4424.

**Expected behavior**
Chart version 4.3.1 should be in the repository.

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

This is irrelevant as https://charts.bitnami.com/bitnami/index.yaml does not contain the right version of the chart.

**Comment by juan131** [comment]
Hi @bootc 

Thanks for opening this issue! There's an issue with the tests for this chart that we run before publishing the charts. We are aware of it and we are working on fixing them so we unblock the release.

In the meantime, you can clone the repo and install the version **4.3.1** from local files (instead of using the chart repo). Sorry for the inconveniences.

**Comment by carrodher** [comment]
The issue was solved and the latest version should be present in the repository:
```console
$ helm repo update && helm search repo bitnami/external-dns
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/external-dns	4.3.1        	0.7.4      	ExternalDNS is a Kubernetes addon that configur...
```

Please, feel free to reopen this issue if you are not able to see the latest version in the repository. Thanks

**Comment by bootc** [comment]
Thanks, looks good to me. :pray:

**Comment by HaroonSaid** [comment]
Looks like its gone again!
