### ISSUE TITLE
cassandra-1 pod is crashing

### ISSUE THREAD

**Issue by samaiyayashraj** [bitnami/charts#4512]
**Which chart**:
bitnami/cassandra

CHART                         APP VERSION
cassandra-7.0.1            3.11.9

**Describe the bug**
cassandra-1 pod is going into CrashLoopBackOff

Trying to deploy Cassandra with a replica count of 3 using bitnami/cassandra helm chart.
cassandra-0 pod is running fine. 

Logs of cassandra-1 pod......................

WARN  [main] 2020-11-27 09:35:59,973 SimpleSeedProvider.java:60 - Seed provider couldn't lookup host cassandra-0.cassandra-headless.default.svc.cluster.local
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: The seed provider lists no seeds.
ERROR [main] 2020-11-27 09:35:59,975 CassandraDaemon.java:803 - Exception encountered during startup: The seed provider lists no seeds.
The seed provider lists no seeds.

NAME                  READY   STATUS             RESTARTS   AGE
cassandra-0           1/1     Running            0          41m
cassandra-1           0/1     CrashLoopBackOff   12         40m

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"
```

**Additional context**

**Comment by dani8art** [comment]
Hi @samaiyayashraj I've tried with

```
$ helm install cassandra bitnami/cassandra --set replicaCount=3
$ k get pods
NAME          READY   STATUS    RESTARTS   AGE
cassandra-0   1/1     Running   0          5m5s
cassandra-1   1/1     Running   0          3m31s
cassandra-2   1/1     Running   0          104s
```

I was not able to reproduce the issue, could you share a bit more about your parameters and values.yaml, please?

thanks!

**Comment by samaiyayashraj** [comment]
My bad, it was some networking issue in my environment.  @dani8art Thanks for the help.
