### ISSUE TITLE
Helm install failing when ingress is enabled for latest version (14.0.0) of bitnami/node chart

### ISSUE THREAD

**Issue by goodlime** [bitnami/charts#4516]
**Which chart**:
NAME
bitnami/node

CHART VERSION
14.0.0

APP VERSION
14.15.1

**Describe the bug**
Chart install of the latest version is failing when ingress is enabled with the following error:

`Error: template: node/charts/common/templates/_capabilities.tpl:28:44: executing "common.capabilities.ingress.apiVersion" at <.Capabilities.KubeVersion.GitVersion>: nil pointer evaluating interface {}.KubeVersion`

**To Reproduce**

1. Download the default values.yaml file [https://github.com/bitnami/charts/blob/master/bitnami/node/values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/node/values.yaml)
2. Modify the default values.yaml at line 352 to enable ingress `enabled: true`
3. Install the bitnami/node chart for Helm with the command `helm install node-test -f ./values.yaml bitnami/node`

**Expected behavior**
Helm chart for Node.js installs as expected with ingress support

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The workaround I am using for this issue is to install the previous version of the same helm chart:
`helm install node-test -f ./values.yaml bitnami/node  --version 13.1.2`

**Comment by jwanga** [comment]
Im experiencing the same thing. Had to downgrade to 13.1.2

**Comment by dani8art** [comment]
Hi @goodlime it seems there was a bug in this version, could you try using the latest version, please, take into account that this new version is a major upgrade, you should review its notable changes before upgrading https://github.com/bitnami/charts/tree/master/bitnami/node#to-1400 

```
$ helm search repo bitnami/node
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/node         	14.0.0       	14.15.1    	Event-driven I/O server-side JavaScript environ...
```

**Comment by goodlime** [comment]
@dani8art I'm not sure I follow. You are asking me to try the exact version which was failing for me. I see no subsequent  commits that would have remedied the issue. Am I missing something?

To clarify, I had to downgrade to the previous latest version in order to get my stack to build successfully. The previous version(s) I had been using without issue for months.
```
helm install node-test -f ./values.yaml bitnami/node --version 13.1.2
```

My console output...
```
$ helm search repo bitnami/node
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/node         	14.0.0       	14.15.1    	Event-driven I/O server-side JavaScript environ...
```

**Comment by dani8art** [comment]
Sorry, then I misunderstood something and I've tried with an old version but thinking I was using `14.0.0`, you are right, there is a bug in the `ingress.yaml` template I've just opened a PR, please let's move the conversation there. 

Thanks for reporting it!
