### ISSUE TITLE
Any bitnami charts with backup functionality?

### ISSUE THREAD

**Issue by franklin432** [bitnami/charts#4520]
**Which chart**:
any charts but specifically  for bitnami/mongodb

**Describe the bug**
I wanted to know if there were any helm charts or bitnami charts that have the ability to perform backups wheter manually or automatically with a cron job. I would like to check this out and see if this can be incorporated in the bitnami/mongodb chart.

**Expected behavior**
Upon install of the mongodb helm chart, a cron job also gets ran which is running the backup functionality. The backups get dump to another pod or pvc and can be accessed if something corrupt goes on with the statefulset in which it can be easily restored.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but there is not such automatic functionality in our charts yet. We are studding it but there is not an ETA for this.
  Meanwhile, you can do backups using Velero maybe you would like to take a look to [this guide](https://docs.bitnami.com/tutorials/series/backup-restore-bitnami-velero/).
  I hope this helps.

**Comment by franklin432** [comment]
Thanks for the response @rafariossaa, I'll take a look at the Velero.

**Comment by rafariossaa** [comment]
You are welcome.
I am closing this issue.
