### ISSUE TITLE
[mongodb-sharded] not possible to override mongodb.conf

### ISSUE THREAD

**Issue by alrf** [bitnami/charts#4523]
**Which chart**:
mongodb-sharded (3.1.0)

**Describe the bug**
Not possible to override mongodb.conf file via `config` and `configCM` settings.

1) The `configCM` ConfigMap (`mongodb-configsvr-cfgmap` in my case) is mapped to pod into `/bitnami/mongodb/conf/` folder:
```
Mounts:
      /bitnami/mongodb/conf/ from config (rw)
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      mongodb-configsvr-cfgmap
    Optional:  false
```
https://github.com/bitnami/charts/blob/5d431c8dd6236bd5e51448a1b1df58900bc39169/bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml#L210-L212

and inside of pod I see my `/bitnami/mongodb/conf/mongodb.conf` file, everything fine.

However the pod entrypoint uses **/opt**/bitnami/mongodb/conf/mongodb.conf config file:
```
I have no name!@dev-mongodb-sharded-configsvr-0:/$ ps -ef |grep mongo
1001         1     0  0 21:42 ?        00:00:09 /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf -
```
and **/opt**/bitnami/mongodb/conf/mongodb.conf is hardcoded here:
https://github.com/bitnami/bitnami-docker-mongodb/blob/99cb941a6ebabf04978a0513aa885f3f64c0c147/3.6/debian-9/rootfs/opt/bitnami/scripts/mongodb-env.sh#L62
https://github.com/bitnami/bitnami-docker-mongodb/blob/99cb941a6ebabf04978a0513aa885f3f64c0c147/3.6/debian-9/rootfs/opt/bitnami/scripts/mongodb-env.sh#L70

I tried to use `extraEnvVars` to define MONGODB_CONF_FILE:
```
  extraEnvVars:
    - name: MONGODB_CONF_FILE
      value: /bitnami/mongodb/conf/mongodb.conf
```
but it doesn't work, pod entrypoint uses **/opt**/bitnami/mongodb/conf/mongodb.conf config file again.
So, there are two config files in the end: **/opt**/bitnami/mongodb/conf/mongodb.conf and /bitnami/mongodb/conf/mongodb.conf
and mongod process uses only **/opt**/bitnami/mongodb/conf/mongodb.conf file.
The same behavior for all components: configsvr, mongos, shardsvr.

2) In case I use `config` setting instead of `configCM` and populate it as:
```
config: |-
  storage.dbPath = /bitnami/mongodb/data/db
  storage.journal.enabled = true
  storage.directoryPerDB = false
  systemLog.destination = file
  systemLog.quiet = false
  systemLog.logAppend = true
  systemLog.logRotate = reopen
  systemLog.path = /opt/bitnami/mongodb/logs/mongodb.log
  systemLog.verbosity = 0
  net.port = 27017
  net.unixDomainSocket.enabled = true
  net.unixDomainSocket.pathPrefix = /opt/bitnami/mongodb/tmp
  net.ipv6 = false
  net.bindIpAll = true
  replication.replSetName = dev-mongodb-sharded-configsvr
  replication.enableMajorityReadConcern = true
  sharding.clusterRole = configsvr
  processManagement.fork = false
  processManagement.pidFilePath = /opt/bitnami/mongodb/tmp/mongodb.pid
  setParameter.enableLocalhostAuthBypass = false
  security.authorization = disabled
``` 
the chart fails with error:
```
Error: YAML parse error on mongodb-sharded/templates/config-server/config-server-configmap.yaml: error converting YAML to JSON: yaml: line 12: did not find expected comment or line break
```

**To Reproduce**
See description.

**Expected behavior**
Override mongodb.conf file content via `config` and `configCM` settings.
Change path for mongodb.conf

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @alrf, so it seems you have identified two issues.

The easiest one to fix seems to be the parsing error when using `configsvr.config`:

Just by changing `indent` to `nindent` in the line below seems to do the trick:

https://github.com/bitnami/charts/blob/a1f50de7e444341f62f289f988c0db676670de9a/bitnami/mongodb-sharded/templates/config-server/config-server-configmap.yaml#L10

---

About the other one, the container executes functions to copy the configuration file from `/bitnami` to `/opt/bitnami`. See the links below:

https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/9f85fa9dfebcba46b1324f65e6ea67302e061707/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L51

https://github.com/bitnami/bitnami-docker-mongodb/blob/90e7b61df15ea62f662c9b2697d8539a9d97791d/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L107-L114

For some reason, the copying of the configuration file is not working as expected.

Can you let us know if chaning indent to nindent works on your side? Then, we will continue digging into the other issue.

**Comment by alrf** [comment]
Hi @andresbono 
> Can you let us know if chaning indent to nindent works on your side? Then, we will continue digging into the other issue.
yes, this works, I also found it today before your answer.

**Comment by alrf** [comment]
It seems `MONGODB_MOUNTED_CONF_DIR` comes from:
https://github.com/bitnami/bitnami-docker-mongodb/blob/163ea74fc0c9d05966f9e3cb03c36c95899dbeb9/3.6/debian-9/rootfs/opt/bitnami/scripts/mongodb-env.sh#L83
and `/bitnami/conf` (not `/bitnami/mongodb/conf`) by default:
https://github.com/bitnami/bitnami-docker-mongodb/blob/163ea74fc0c9d05966f9e3cb03c36c95899dbeb9/3.6/debian-9/rootfs/opt/bitnami/scripts/mongodb-env.sh#L61

**Comment by andresbono** [comment]
It seems a bit tricky. I made it work by executing the commands below. However, with different chart parameters or different configuration file, the results can be unexpected:

```console
$ docker run -d --name mongodb-sharded bitnami/mongodb-sharded sleep infinity
$ docker cp mongodb-sharded:/opt/bitnami/mongodb/conf/mongodb.conf mongodb.conf
$ echo "# my custom config file" >> mongodb.conf
$ docker rm -f mongodb-sharded

$ kubectl create configmap mongodb-configsvr-cfgmap --from-file=mongodb.conf

$ cat <<EOF | helm install mongodb-sharded bitnami/mongodb-sharded -f -
configsvr:
  configCM: mongodb-configsvr-cfgmap
  extraEnvVars:
    - name: MONGODB_MOUNTED_CONF_DIR
      value: /bitnami/mongodb/conf
EOF

$ kubectl exec mongodb-sharded-configsvr-0 -- tail -n1 /opt/bitnami/mongodb/conf/mongodb.conf
# my custom config file
```
