### ISSUE TITLE
Naming rule failing the deployment

### ISSUE THREAD

**Issue by rampatnaik** [bitnami/charts#4530]
Hello Redis

I am using version=11.1.1 , the Naming of redis doesnot work as per our project
Name "name":"redis-A-B" not work , it work with "name":"redis-A"
I am using spinnaker , K8s: 17 version with eks

error :
Error from server (Invalid): error when applying patch:
for: "STDIN": StatefulSet.apps "redis-A-B-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error from server (Invalid): error when applying patch:

**Comment by dani8art** [comment]
Hi I answered this on https://github.com/bitnami/bitnami-docker-redis/issues/190#issuecomment-735782949,

thanks!
