### ISSUE TITLE
[spring-cloud-dataflow] provide configurable extraVolume(Mount)s

### ISSUE THREAD

**Issue by stoetti** [bitnami/charts#4534]
**Which chart**:
spring-cloud-dataflow

**Is your feature request related to a problem? Please describe.**
Spring Cloud Dataflow provides the ability to load app-metadata from private container registries. In order to retrieve that information the credentials need to be mounted using a k8s-secret [as stated in the configuration](https://dataflow.spring.io/docs/installation/kubernetes/helm/#private-docker-registry).
The current chart does not have a templating option for add extra volumes or volume mounts for the deployments (skipper, server).

**Describe the solution you'd like**
Either provide a special configuration value for such kind of secrets or generic extraVolumes and extraVolumeMounts which are added to the deployment-template.

**Describe alternatives you've considered**

**Additional context**

**Comment by andresbono** [comment]
Hi @stoetti, thanks for raising this issue.

I don't see any cons on adding new parameters to be able to pass extra volumes to the different pods. In fact, it is a pattern that we try to follow in most of the containers. For instance, see discourse: https://github.com/bitnami/charts/blob/master/bitnami/discourse.

We use the parameters `extraVolumes` and `extraVolumeMounts` to add more flexibility for the chart.

Would you like to draft a PR addressing the changes to incorporate these parameters in this chart? Contributions are more than welcome!

**Comment by stoetti** [comment]
PR created

**Comment by andresbono** [comment]
That's great, @stoetti!! Thanks for your contribution. We will review it soon.
