### ISSUE TITLE
 bitnami/rabbitmq  anxious   I deployed a three-node mirrored cluster test: When I deleted all three RabbitMQ Pods, the cluster couldn't get up. How could I solve this problem?

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4535]
I deployed a three-node mirrored cluster test: When I deleted all three RabbitMQ Pods, the cluster couldn't get up. How could I solve this problem?
mq-rabbitmq-0                                    0/1     Running   0          2m32s
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               <unknown>         default-scheduler        Successfully assigned dev-dev/mq4-rabbitmq-0 to 10.60.128.237
  Normal   SuccessfulAttachVolume  97s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-2dd6ee5e-ad21-4a51-b4fa-b141cad933a7"
  Normal   Pulled                  74s               kubelet, 10.60.128.237   Container image "registry.navinfo.com/base/rabbitmq:3.8" already present on machine
  Normal   Created                 74s               kubelet, 10.60.128.237   Created container rabbitmq
  Normal   Started                 74s               kubelet, 10.60.128.237   Started container rabbitmq
  Warning  Unhealthy               9s (x2 over 39s)  kubelet, 10.60.128.237   Readiness probe failed: Error:
RabbitMQ on node rabbit@mq4-rabbitmq-0.mq4-rabbitmq-headless.dev-dev.svc.cluster.local is not running or has not fully booted yet (check with is_booting)
--------------------------------------------------------------------------

**Comment by Gefuxing** [comment]
You can deploy a case of three-node mirroring mode and wait for it to deploy successfully, delete the three PODS, the cluster will not run anymore, there will only be a -0 in Runnning and 0/1, do you have any good solutions?Thank you very much!!

**Comment by Gefuxing** [comment]
![image](https://user-images.githubusercontent.com/43690953/100592249-d121cf00-3331-11eb-873d-f133a8ef23cb.png)

**Comment by rafariossaa** [comment]
Hi,
  I would like to reproduce this issue.
  Could you indicate you did you started the cluster and the parameters used ?

**Comment by Gefuxing** [comment]
helm3 install mq111 --set persistence.storageClass=nfs-storage --set persistence.size=1Gi --set replicaCount=3 --set auth.username=gefuxing --set auth.password=gefuxing --set service.type=NodePort   bitnami/rabbitmq
----------------------------------
mq111-rabbitmq-0                                 1/1     Running   0          5m28s
mq111-rabbitmq-1                                 1/1     Running   0          3m35s
mq111-rabbitmq-2                                 1/1     Running   0          2m49s
----------------------------------------
kubectl delete pod mq111-rabbitmq-0 mq111-rabbitmq-1   mq111-rabbitmq-2
--------------------------------------------------
pod "mq111-rabbitmq-0" deleted
pod "mq111-rabbitmq-1" deleted
pod "mq111-rabbitmq-2" deleted
[root@10-60-158-72 ~]# kubectl get pod
mq111-rabbitmq-0                                 0/1     Running   0          19s
---------------------------------------------------------------------------
And then the cluster never gets up，I hope to get your help. Thank you very much

**Comment by Gefuxing** [comment]
@rafariossaa  You can reproduce it according to this process. Thank you very much for your help. Please feel free to contact me if you have any progress.

**Comment by Gefuxing** [comment]
I hope you can give me a solution as soon as possible. I am in a hurry. Please help me.

**Comment by machine424** [comment]
Hello,

You may need to look at these comments and the links to they provide:
- https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L138
- https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L315

Plus, I think `kubectl delete pod mq111-rabbitmq-0 mq111-rabbitmq-1 mq111-rabbitmq-2` doesn't guarantee any shutting down order. Only scaling down a StatefulSet achieves ordered and graceful termination (depending on your terminationGracePeriodSeconds) of the pods in the StatefulSet.

**Comment by rafariossaa** [comment]
Hi,
  If you delete the 3 nodes at the same time, it is what you said, it is not guaranteed any order, neither that it is ordered and not done simultaneously. 
 To stop it gracefully you should be using `helm delete`, by running `kubectl delete` with all the pods you simulated a massive fault of the cluster. You can try to recover it by using `force-boot`.

**Comment by rafariossaa** [comment]
Hi,
  Did you have the chance to check this ?
