### ISSUE TITLE
[bitnami/postgresql] doc errata

### ISSUE THREAD

**Issue by Hokwang** [bitnami/charts#4537]
**Which chart**:
postgresql

**Describe the bug**
you mentioned mariadb.

https://github.com/bitnami/charts/blob/10bd8e1fbbe69461a5d90ba61562f72b526c9caf/bitnami/postgresql/README.md#L577
https://github.com/bitnami/charts/blob/10bd8e1fbbe69461a5d90ba61562f72b526c9caf/bitnami/postgresql/README.md#L583

**Comment by andresbono** [comment]
Hi @Hokwang, thanks for spotting this issue! Would you like to open a PR fixing the README erratas?
