### ISSUE TITLE
[mysql] unable to create mysql with initdbScripts

### ISSUE THREAD

**Issue by zhiweiv** [bitnami/charts#4539]
**Which chart**:
mysql 8.0.0

**Describe the bug**
unable to create mysql with  initdbScripts, it works if I remove setting for initdbScripts.

The error is:
`Error: template: mysql/templates/primary/statefulset.yaml:283:21: executing "mysql/templates/primary/statefulset.yaml" at <include "mysql.initdbScriptsCM" .>: error calling include: template: mysql/templates/_helpers.tpl:51:34: executing "mysql.initdbScriptsCM" at <include "mysql.master.fullname" .>: error calling include: template: no template "mysql.master.fullname" associated with template "gotpl`

**To Reproduce**
helm install -f MySQLValues.yaml mysql bitnami/mysql
MySQLValues.yaml
```
auth:
  rootPassword: 1qaz2wsx!@#$

primary:
  nodeSelector: 
    kubernetes.io/os: linux
  
initdbScripts:
  createdb.sql: |-
    CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
```

**Expected behavior**
Able to create mysql with initdbScripts.

**Version of Helm and Kubernetes**:
Helm 3.4.1
Kubernetes 1.19.3

**Comment by jkonecny75** [comment]
I have the same problem :-(

**Comment by dani8art** [comment]
Hi! thanks for reporting the issue, I've just added a commit to this PR #4554 that should fix the issue, please let's move the conversation there.
