### ISSUE TITLE
[rabbitmq] PLAIN login refused: user '<username>' - invalid credentials

### ISSUE THREAD

**Issue by Lebed71** [bitnami/charts#4541]
Hello!
I have some problem with new deploy of rabbitmq chart;

Helm deploy command params:

auth.username=username,
auth.password=password,
rabbitmq.setUlimitNofiles=false,
persistence.existingClaim=rabbitmq-pvc,
volumePermissions.enabled=true

After success deploy I check the auth values:

$(kubectl get secret --namespace test rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)

And value equal with my

But when I try connect to Rabbit with just a connection string:

"amqp://username:password@rabbitmq.general.svc.cluster.local?heartbeat=60000"

I got error:

  PLAIN login refused: user 'username' - invalid credentials

Before this works correct (in older stable helm chart, deprecated now)

**Comment by andresbono** [comment]
Hi @Lebed71, what do you mean by "Later this works correct"? Is it the error transient?

**Comment by Lebed71** [comment]
> Hi @Lebed71, what do you mean by "Later this works correct"? Is it the error transient?

Sorry, I mean "Before", in older stable helm charts. Fixed in top message

**Comment by andresbono** [comment]
Thanks for the clarification.

The error might be caused by the usage of `persistence.existingClaim=rabbitmq-pvc`. As you are using an old PVC, the credentials should be the ones defined in the PVC, not the ones you are specifying with the helm parameters.

If you try a fresh install, you should be able to get a successful connection:

```console
$ kubectl create namespace test2
$ helm install --namespace test2 rabbitmq bitnami/rabbitmq --set auth.username=username --set auth.password=password --set rabbitmq.setUlimitNofiles=false --set volumePermissions.enabled=true
$ kubectl get secret --namespace test2 rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode
password
$ kubectl --namespace test2 exec -it rabbitmq-0 -- curl -u username:password http://localhost:15672/api/users
[{"name":"username","password_hash":"Y2OvrvdR+kshwvQ8PRhakDA2Db+utLB4BsLfz2dbIjZX/eLW","hashing_algorithm":"rabbit_password_hashing_sha256","tags":"administrator"}]
$ kubectl delete namespace test2
```

Can you confirm this works for you?

**Comment by volkmydj** [comment]
It's not work fo me....

**Comment by andresbono** [comment]
Hi @volkmydj, could you share the output that you get when you try to execute the commands above? What is the error that you are getting?

**Comment by mammothbane** [comment]
For my situation this was caused by the image version. With this `values.yaml`:

```yaml
image:
  tag: 3.8.3

auth:
  username: username
  password: password
```

`rabbitmqctl authenticate_user username` would fail on an input of `password`, where with `image.tag` at `3.8.9`, it would work.

**Comment by javsalgar** [comment]
Hi,

Could you check if the password is CHANGEME? I would like to ensure if there are no conflicts with this

```
## Configuration file content: required cluster configuration
## Do not override unless you know what you are doing.
## To add more configuration, use `extraConfiguration` of `advancedConfiguration` instead
##
configuration: |-
  ## Username and password
  default_user = {{ .Values.auth.username }}
  default_pass = CHANGEME
```

**Comment by linnovs** [comment]
Hi,

I got the same problem when deploying a new rabbitmq without any configuration.

**Comment by mammothbane** [comment]
> Could you check if the password is CHANGEME? I would like to ensure if there are no conflicts with this

Yep, I checked that at the time &mdash; it wasn't.

**Comment by javsalgar** [comment]
Hi,

I've been unable to reproduce it. Which client are you using to connect to rabbitmq?

**Comment by franklincodes** [comment]
Just to drop a note, I ran into this issue as well when defining a different image tag/version of RabbitMQ. I switched back to `3.8.9-debian-10-r64` (what's currently defined in this repo) and it worked just fine.

Before switching the version to `3.8.9-debian-10-r64`, I had re-deployed several times (deleting pv/pvc) with no luck.

**Comment by rafariossaa** [comment]
Hi,
  You should stick to the version included in the values, some times a new release appears to fix something in the container and/or chart and they should be used together.
  @Lebed71 , @mammothbane , could you try this latest version ?

**Comment by mammothbane** [comment]
> Hi,
> 
> I've been unable to reproduce it. Which client are you using to connect to rabbitmq?

For debugging purposes, I was using `rabbitmqctl authenticate_user` from within the container, but other services in our cluster were connecting using the [golang client](https://github.com/streadway/amqp) and also had their connections rejected for bad credentials.

>Hi,
>You should stick to the version included in the values, some times a new release appears to fix something in the container and/or chart and they should be used together.
>@Lebed71 , @mammothbane , could you try this latest version ?

I see. It is working for us at the moment with the overridden `image.tag`, and I can't make going back and testing this a priority &mdash; sorry, but I most likely won't get to this anytime in the near future.

**Comment by raphaelquati** [comment]
> Hi,
> 
> Could you check if the password is CHANGEME? I would like to ensure if there are no conflicts with this
> 
> ```
> ## Configuration file content: required cluster configuration
> ## Do not override unless you know what you are doing.
> ## To add more configuration, use `extraConfiguration` of `advancedConfiguration` instead
> ##
> configuration: |-
>   ## Username and password
>   default_user = {{ .Values.auth.username }}
>   default_pass = CHANGEME
> ```

I have the same problem installing the chart version 7.5.8 (uses the image rabbitmq:3.8.6-debian-10-r0)
I'm confirm that default_pass = CHANGEME after helm creation.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce it 

```
I have no name!@rb-rabbitmq-0:/$ env | grep PASS
RABBITMQ_PASSWORD=73elj8hB2c
I have no name!@rb-rabbitmq-0:/$ rabbitmqctl authenticate_user user
Authenticating user "user" ...
Password:
73elj8hB2c
Success
```

**Comment by andrew-vdb** [comment]
Got this issue too (in the past i don't face this, it was just work)
```
helm install --namespace test2 rabbitmq bitnami/rabbitmq --set auth.username=myRabbitUsername --set auth.password=myRabbitPassword --set rabbitmq.setUlimitNofiles=false --set volumePermissions.enabled=true
```
When you do above command

Everything will looks ok in lens/kubernetes

configmaps 
default_user = myRabbitUsername
default_pass = CHANGEME

secrets
rabbitmq-password = myRabbitPassword

Now you try to login to the management portal, **login will fail**

**WORKAROUND**
- Go into pod's shell
- rabbitmqctl list_users
![image](https://user-images.githubusercontent.com/12871379/103912355-77b67800-5107-11eb-91d3-6fe36fe40282.png)
As you can see there is no myRabbitUsername in the list
-  the rest you just need to add the user manually
rabbitmqctl add_user myRabbitUsername myRabbitPassword
- if you want the user can access management portal
set_user_tags myRabbitUsername administrator
- then allow myRabbitUsername to access virtual host / (optional, depend on how secure your setup)

**Comment by aranair** [comment]
I can only reproduce it if persistence is enabled. 

This happens even if I clear out all the pv/pvc/data prior to it, it's ..presumably skipping every step even for an empty state.

```
helm fetch bitnami/rabbitmq --version $RABBITMQ_VERSION 7.6.9
```

```
replicaCount: 1
auth:
  username: someuser
  password: somepassword
image:
  repository: bitnami/rabbitmq
  tag: 3.8.9
persistence:
  enabled: true
  existingClaim: rabbitmq-pvc
```

```
kubectl get secret --namespace default tulip-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode
```
-> somepassword

```
$ rabbitmqctl authenticate_user onprem-user CHANGEME
Authenticating user "onprem-user" ...
Success
$
```

**Comment by aranair** [comment]
Also, I believe this is a regression:

```
helm fetch bitnami/rabbitmq --version 6.7.3
```

```
# instead of auth
rabbitmq:  
  username: someuser
  password: somepassword
image:
  repository: bitnami/rabbitmq
  tag: 3.7.18-debian-9-r1
persistence:
  enabled: true
  existingClaim: rabbitmq-pvc
```

Same scenario:
- persistence enabled, 
- but with no data 

```
Node database directory at /opt/bitnami/... is empty
2021-01-07 23:58:10.744 [info] <0.235.0> Discovered no peer nodes to cluster with
2021-01-07 23:58:10.746 [info] <0.43.0> Application mnesia exited with reason: stopped
2021-01-07 23:58:10.937 [info] <0.235.0> Creating user 'someuser'
...
```

```
$ rabbitmqctl authenticate_user someuser somepassword
Authenticating user "someuser" ...
Success
$
```

**Comment by andresbono** [comment]
@andrew-vdb, what is the version of the chart that you are installing?

```
helm list --all-namespaces
```

---

@aranair, you say that the chart (specifically `7.6.9`) fails when you enable persistence but it's a blank slate (e.g. no data). You are specifying an existing claim, doesn't that existing claim contain data. What do you mean by persistence in blank state? Are you removing `/bitnami/rabbitmq/mnesia/*`?

**Comment by aranair** [comment]
yup, if a pvc/pv is bound but that volume has nothing in it, or has data cleared (for whatever reason). And yup that directory along w some others.

**Comment by andrew-vdb** [comment]
@andresbono latest version? what version i will get if i just run install without specifying version (i already cleaned up my kubernetes too)

helm search repo bitnami/rabbitmq
![image](https://user-images.githubusercontent.com/12871379/104023607-333be280-51c2-11eb-9f67-9f48f539c1db.png)

**Comment by gertjangaillet** [comment]
We have the same issue with chart v7.6.8 (app v 3.8.9). 
When setting `persistence.enabled=false` the credentials set using `auth.username` and `auth.password` are properly configured and accepted.

**Comment by javsalgar** [comment]
Hi,

Does the same issue happen in the latest release of the chart? Version 8.6.2

**Comment by aranair** [comment]
> Hi,
> 
> Does the same issue happen in the latest release of the chart? Version 8.6.2

Yes, I observe the same behaviour with chart 8.6.2 + image 3.8.9
- persistence enabled
- blank slate, no data

**Comment by javsalgar** [comment]
Hi,

I don't get, I try several times and I don't reproduce the issue

```
❯     echo "Username      : bitnami"
Username      : bitnami
❯     echo "Password      : $(kubectl get secret --namespace default myrab-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
Password      : test123123
❯     echo "ErLang Cookie : $(kubectl get secret --namespace default myrab-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"
ErLang Cookie : 3gKaX1HJUvZwA6AMiEWcyeNNUreDxD18
❯ kubectl get pods -w
NAME               READY   STATUS    RESTARTS   AGE
myrab-rabbitmq-0   1/1     Running   0          102s
^C ❲n❳ v12.16.3  /tmp                                                                                11:09:33  jsalmeron
 1 ❯ kubectl exec -ti myrab-rabbitmq-0 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@myrab-rabbitmq-0:/$ env | grep "USER\|PASS"
RABBITMQ_PASSWORD=test123123
RABBITMQ_USERNAME=bitnami
I have no name!@myrab-rabbitmq-0:/$ rabbitmqctl authenticate_user bitnami
Authenticating user "bitnami" ...
Password:
test123123
Success
```

**Comment by aranair** [comment]
Hmm, Do you have persistence enabled (and on top of that no data in the the
volume)?

**Comment by andresbono** [comment]
We have tried in both ways, still unable to reproduce the issue.

Can activate debug by setting the parameter `image.debug=true` and compare the logs in both cases? The logs are very verbose but you should see some lines like these ones:

```
rabbitmq 07:53:41.64 DEBUG ==> Changing password for user 'user'...
Changing password for user "user" ...
2021-01-13 07:53:42.026 [info] <0.1032.0> Successfully changed password for user 'user'
```

Do you see any traces of errors in your case?

It would be great if you can share your complete logs with debug enabled in both scenarios, with and without persistence.

**Comment by TamasGorgics** [comment]
Hello,

I run into this issue too. 
I use chart version: `3.8.9-debian-10-r58`

Auth params are the following:
```
auth:
  username: rabbitmq
  password: rabbitmq
```

`rabbitmq.conf` contains the following:
```
I have no name!@rabbitmq-0:/$ cat /bitnami/rabbitmq/conf/rabbitmq.conf
## Username and password
##
default_user = rabbitmq
default_pass = CHANGEME
## Clustering
##
cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
cluster_formation.node_cleanup.interval = 10
cluster_formation.node_cleanup.only_log_warning = true
cluster_partition_handling = autoheal
# queue master locator
queue_master_locator = min-masters
# enable guest user
loopback_users.guest = false
#default_vhost = voc-vhost
#disk_free_limit.absolute = 50MB
#load_definitions = /app/load_definition.json
## Prometheus metrics
##
prometheus.tcp.port = 9419
```

User list is the following:
```
I have no name!@rabbitmq-0:/$ rabbitmqctl list_users
Listing users ...
user	tags
rabbitmq	[administrator]
```

Password environment variable:
```
I have no name!@rabbitmq-0:/$ env | grep PASS
RABBITMQ_PASSWORD=rabbitmq
```

`kubectl get secret --namespace voc rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 -d` returns with `rabbitmq`


The error I see in the logs is `PLAIN login refused: user 'rabbitmq' - invalid credentials`

**Comment by javsalgar** [comment]
Good to know that you were able to aunthenticate. If you find more information that clarifies the issue with the client, please let us know

**Comment by TamasGorgics** [comment]
I have to make amends again, my issue had nothing to do with the go client after all. 
I managed to reproduce the issue by deleting rabbitmq with helm and then installing it again. This operation broke the authentication, `rabbitmqctl authenticate_user rabbitmq rabbitmq` didn't work anymore. But I managed to fix this by deleting the old PVC before installing rabbitmq again - as someone suggested above. But my real problem is that more often than not the rabbitmq instance cannot start up for the first try, looking at the rabbitmq-0 pod I can see that it restarts 1-4 times before getting stable. In the logs I can also see that the readiness probe keeps failing because the `node 'rabbit' not running at all`. Why does it happen is beyond me but eventually it manages to start and become stable, but the problem is that even if I deleted the old PVC before calling `helm install bitnami/rabbitmq ...` after the first restart there is already an old PVC that breaks the authentication. I assume if I could avoid the restarts, authentication would work just fine.

**Comment by javsalgar** [comment]
Hi,

Not sure if 100% related but could a change in the RabbitMQ cookie be responsible of the authentication break? Do you use the same cookie when reinstalling?

**Comment by aravindabiswal** [comment]
Hi ,

Recently we are also facing this issue in one of our cluster and the issue is intermittent.

Chart: bitnami/rabbitmq
version: 8.5.4

Persistence is disabled in our chart, still we get this issue. 
It works fine after restarting the rabbitmq pod in K8s .

When we tried to authenticate inside the container, it throws error.

$ rabbitmqctl authenticate_user admin
Authenticating user "admin" ...
Password:
"********"
Error:
Error: failed to authenticate user "admin"
user 'admin' - invalid credentials

We use the same chart to deploy to other clusters as well , but didn't face the issue till now .
Please advise how to reproduce & fix the issue.

**Comment by javsalgar** [comment]
Hi,

We're trying to reproduce the issue but were unable to do so. Did you check this? https://github.com/bitnami/charts/issues/4541#issuecomment-769686328

**Comment by aravindabiswal** [comment]
@javsalgar ..thanks for the reply . We use the same cookie to deploy , but every time the installation is in a fresh cluster.

**Comment by javsalgar** [comment]
Hi,

Please let us know the exact set of values that you changed when deploying, let's see if we find the one that's causing the error.

**Comment by TheMysteriousVincent** [comment]
Hi! I *had* the same problems as mentioned above.

The error occurred, because the password is being saved to the the volume (which shouldn't in a containerized environment). Since PVs are not removed by default after they are not used anymore, RabbitMq kept using the same PV and thus an old or even no password.

The password **IS NOT** overriden by it's Helm configuration but relies on the values saved to the PV instead. That is why this error seems like parameters are not applied in the first place - which is kind of correct.

I tried this multiple times with **the same PV** and I only could authenticate the user against the first password that was configured by the first Helm installation. Reinstalling (uninstall, then install) the chart using a new user password did not changed the password used by RabbitMQ.

I suggest that the Password for the user configured over Helm should not be persistently saved - or, at least, an information that the password is saved on the PV would be good, though.

**Comment by javsalgar** [comment]
Hi,

Being able to reset passwords after initialization is something that we don't currently support. From a declarative perspective, we would like to support it but in most infrastructure applications is not trivial. That means that the password you set is, actually, the bootstrap password (maybe it would make sense to change the nomenclature). If you want to deploy a fresh installation, you need to ensure that the PVCs from previous releases have been released as well.

**Comment by mlb5000** [comment]
I get this issue, but ONLY when trying to connect to the RabbitMQ node from INSIDE the K8S network (via `rabbitmq.default.svc`). When I use `rabbitmqctl` to authenticate or run the exact same consumer outside the K8S network t talking to the exposed K8S port on the host, it works fine (using credentials other than `guest`). But inside of the K8S network with those exact same credentials I get:

```Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."```

I know the networking is fine, because I'm also running `bitnami/redis` and it's able to connect to that without issue. I'm not sure how to deal with this problem. `rabbitmq.default.svc` resolves just fine inside the container, it just can't connect to the node.

**Comment by wojtek-viirtue** [comment]
This started happening to me all of sudden as well.  Despite the correct chart properties being set, when persistence is enabled and using the "standard" storageClass on minikube.... the default password "CHANGEME" is used. Logging into the container I can see that the env variables are set correctly to the password and erlanCookie I set, but authentication fails unless the default passwrod "CHANGEME" is used.  Baffled.

I can't explain how or why this started happening...still investigating.

**Comment by javsalgar** [comment]
Hi,

I also used minikube when trying to reproduce the issue and found no problems. I imagine that the credentials were working on the first deployment, right? Or it was using CHANGEME from the beginning?

**Comment by filoe** [comment]
Same problem here. Username and password is configured correct in the secrets. The output of the helm install prints the bash statement to output the password. Running these outputs the correct password but authentication fails. If I change the password from the pods bash using rabbitmqctl change_password user xxx it works.

**Comment by javsalgar** [comment]
I think there is an issue when setting the password initially? If the issue persists, could you try launching it with `image.debug=true` to see if more information appears?

**Comment by filoe** [comment]
I've deployed a complete new chart coming from stable/rabbitmq.
The config I use is

```
fullnameOverride: rabbitmq
replicaCount: 1
serviceAccount:
  create: false
rbac:
  create: false

## RabbitMQ Authentication parameters
##
auth:
  ## RabbitMQ application username
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  username: user

  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  password: xxx

  ## Erlang cookie to determine whether different nodes are allowed to communicate with each other
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  erlangCookie: yyy

plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s rabbitmq_shovel rabbitmq_shovel_management"

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 300m
```

Also trie dot set existingPasswordSecret and existingErlangSecret with the same result. The output when installing the chart is correct but the configuration inside the pod is not.

**Comment by javsalgar** [comment]
Hi,

In this case, you are not setting the Kubernetes RBAC settings so it is highly likely that the rabbitmq Kubernetes plugin is failing . I launched it with your settings and `image.debug=true` and got this

```
rabbitmq-0 rabbitmq 2021-03-25 09:06:00.049 [error] <0.269.0> Peer discovery returned an error: "403". Will retry after a delay of 500 ms, 3 retries left...
rabbitmq-0 rabbitmq 2021-03-25 09:06:00.554 [error] <0.269.0> Failed to fetch a list of nodes from Kubernetes API: 403
rabbitmq-0 rabbitmq 2021-03-25 09:06:00.562 [error] <0.269.0> Peer discovery returned an error: "403". Will retry after a delay of 500 ms, 2 retries left...
rabbitmq-0 rabbitmq 2021-03-25 09:06:01.067 [error] <0.269.0> Failed to fetch a list of nodes from Kubernetes API: 403
rabbitmq-0 rabbitmq 2021-03-25 09:06:01.071 [error] <0.269.0> Peer discovery returned an error: "403". Will retry after a delay of 500 ms, 1 retries left...
```

Any reason for not enabling RBAC and the ServiceAccount?

**Comment by dcardozoo** [comment]
I had the same issue with the latest Helm Chart version 8.11.3.  I was upgrading my old rabbitMQ instance from the OLD stable chart to the Bitnami. 

As I had persistence enabled and when upgrading to the new chart I noticed that the `auth.password` value was not configured at all and could not login or connect. 

I noticed this was not the case on a fresh install with new PVC. There the`auth.password` value was successfully configured and everything worked as normal. 

What happened is that for some reason when using the new Chart, the rabbitmq password was set up as CHANGEME, which is the one configured on `/bitnami/rabbitmq/conf/rabbitmq.conf ` and not `/bitnami/rabbitmq/mnesia/config/generated/rabbitmq.conf` 

I fixed everything by manually changing the pw from CHANGEME to the one configured on the secret. After that the new password is stored in the volume.

**Comment by nhuray** [comment]
I also have the same problem. :(

**Comment by javsalgar** [comment]
Hi,

This issue should be fixed in the latest version of the chart. Are you using load definitions as well?

**Comment by KunaZoli** [comment]
> Hi,
> 
> This issue should be fixed in the latest version of the chart. Are you using load definitions as well?

I think that the load_definition.json: |
        {
          "users": [
Should play a role in this issue.
