### ISSUE TITLE
[bitnami/mysql] load csv file into bitnami/mysql helm chart

### ISSUE THREAD

**Issue by mortenko** [bitnami/charts#4542]
**Which chart**:
bitnami/mysql

**Describe the bug**
I'm trying to load csv files into bitnami/mysql instance but getting following mysql error:

 **ERROR 3948 (42000) at line 1: Loading local data is disabled; this must be enabled on both the client and server sides**

Here is my cnf file 

```
[mysqld]
local_infile=1

[client]
loose-local-infile=1
```

Here is my CI/CD script in  yml file:

```
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm upgrade mysql-db bitnami/mysql
      --install
      --version 7.1.0
      --set image.repository=mysql
      --set image.tag=8.0.22
      --namespace namespace1
      --set db.user=mysql_user
      --set fullnameOverride=mysql123
      --set db.password=passwd
      --set root.password=root_passwd
      --set db.name=tech_db
      --set-file master.config=db/my.cnf  // here Im setting up my custom config file 
      --set initdbScriptsConfigMap=mysql-db-schema
```

Here is my bash script (Im executing it via kubectl exec in script part of gitlab CI/CD):  

`mysql -u ${MYSQL_USER} --password=${MYSQL_PASSWORD} ${MYSQL_DATABASE} -h ${MYSQL_HOST}  -e "LOAD DATA LOCAL INFILE '/tmp/init_data/$file' INTO TABLE $table_name FIELDS TERMINATED BY ';' ENCLOSED BY '\"' IGNORE 1 LINES";`

**Expected behavior**
Should insert data from csv file into mysql
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
 3.2.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:40:44Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I think it does not consume my custom cnf file because otherwise I shouldn't get this error.

**Comment by mortenko** [comment]
version of chart 7.1 but actually migrating to 8.0

**Comment by rafariossaa** [comment]
Hi,
  Could you try adding `--local_infile=1` to your `mysql` command ?

**Comment by mortenko** [comment]
Hi, this solve only problem on client side.

**Comment by mortenko** [comment]
@rafariossaa  I already solved it but in different way.  I used this flag --local_infile=1 on client side and before it I access  to mysql db as root and set global variable local_infile  on server side.

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to solve the issue. Thank you very much for sharing your findings.

  I am not very sure about the `my.cnf` file, but did you check you got that setting loaded in mysql ?
  You can check the value with `SHOW GLOBAL VARIABLES LIKE 'local_infile';`

**Comment by mortenko** [comment]
I know and that was the problem that global variable wasn't set to ON value :).

**Comment by juan131** [comment]
Great! @mortenko I proceed to close the issue as solved, please feel free to reopen it if you require further help.
