### ISSUE TITLE
ServiceAccount for wordpress

### ISSUE THREAD

**Issue by MilanDasek** [bitnami/charts#4544]
**Which chart**:
charts/bitnami/wordpress/

**Describe the solution you'd like**
Is it possible to add service-account or deployment?
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

thank you

MD

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. We will work on adding serviceAccount support in the deployment. I cannot guarantee an ETA, but if you want to speed up the process, feel free to send a PR and we will review it.

**Comment by javsalgar** [comment]
Hi,

Please check this PR that adds the feature you requested https://github.com/bitnami/charts/pull/4582
