### ISSUE TITLE
[metrics-server] Documentation says not to create API endpoint

### ISSUE THREAD

**Issue by baderbuddy** [bitnami/charts#4546]
**Which chart**:
The name (and version) of the affected chart
metrics-server@5.3.0

**Describe the bug**
The documentation says that `apiService.create` should not be necessary with K8S >= 1.8, but the API server isn't automatically created. This is at a minimum needed for things like VPA, but I have to imagine Prometheus would need the API server too.

**To Reproduce**

Install the chart. `kubectl get apiservice` see that there is no metrics service.

**Expected behavior**
Maybe make it the default to create the API service. But at the very least remove the line in the docs that encourages people to not use it.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi, 
  After installing, for example with: `helm install my-release bitnami/metrics-server`, if you run `kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes" `, what do you get ?

**Comment by crosbymichael1** [comment]
@rafariossaa would that be the same thing as running `kubectl top node` ?

**Comment by crosbymichael1** [comment]
Also I agree that there should more descriptions about why its not needed in k8s v1.18 and how to validate whether or not its needed before discouraging the install.

**Comment by dani8art** [comment]
Hi, would it means that there are still cases where the API server is not automatically created, right? and then the docs must be changed to "in most of the cases" or something?

**Comment by pydo** [comment]
I think the API endpoint should be created by default. I installed the helm chart on a digital ocean kubernetes cluster (k8s v1.19) and no metrics were available because the `apiService` wasn't created. Furthermore the upstream metrics-server repo's manifest creates the `apiService` by default https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml .

**Comment by dani8art** [comment]
Oh yes, you are right, there are cases where apiServer must be created because of that we have the option in the chart but this is not relelated to whether it should be `true` or `flase` by default. 

I mean, if we are changing it to `true` by default, we will still have cases where it is not needed, so I think the best approach is to update the documentation taking into account that this doesn't depend on the k8s version only but in the cluster provider as well.

Don't you think so?

**Comment by pydo** [comment]
> Oh yes, you are right, there are cases where apiServer must be created because of that we have the option in the chart but this is not relelated to whether it should be true or flase by default.
>
> I mean, if we are changing it to true by default, we will still have cases where it is not needed, so I think the best approach is to update the documentation taking into account that this doesn't depend on the k8s version only but in the cluster provider as well.

I've only really tested this in a couple of k8s providers, so I guess if the flag isn't needed with some vendors then you are right that this is just a documentation issue. :+1:

**Comment by rafariossaa** [comment]
Hi, 
 @baderbuddy any other thought ?

**Comment by baderbuddy** [comment]
I'm so sorry I missed all of this discussion going on or I would have chimed in. Yeah I was primarily concerned from a documentation standpoint. The current wording is so strong that it discourages a user from even thinking they should change that value. At least in my opinion.

**Comment by baderbuddy** [comment]
I think where I first saw this was on an EKS cluster. I definitely see it on a KIND cluster when running locally. What's the harm in creating the API service if it's not necessary?

**Comment by dani8art** [comment]
> What's the harm in creating the API service if it's not necessary?

I would say the installation could fail to say that it already exists. 

Yes, I think this the main question if we would like to have it `true` by default, but I think the default value is not that important but we should write good documentation where this is clear, I think a better question would be, how do we know that we have to create the API service?

**Comment by antonincms** [comment]
I have the same issue with the chart v5.3.4 on EKS: 
```
~ $ kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"
Error from server (NotFound): the server could not find the requested resource
```
I guess it is a vendor thing... Maybe the documentation could be improved as follows ?
```yaml
apiService:
  ## Specifies whether the v1beta1.metrics.k8s.io API service should be created
  ## This should not be necessary in k8s version >= 1.8, but depends on vendors and cloud providers.
  ##
  create: false
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the suggestion. 
  I have sent a PR, to add more info to the REAMDE and also to the values.yaml
