### ISSUE TITLE
Cannot access keycloak with args like -Dkeycloak.profile.feature.<feature name>=enabled

### ISSUE THREAD

**Issue by CarlosAugustoAlves** [bitnami/charts#4548]
I need to add some configuration like upload_scripts, impersonation, token_exchange, but I was not able to use this in the chart.

Please let me know the proper way to fix this.

**Comment by javsalgar** [comment]
Hi,

In order to enable these settings, you would need to add flags to the `standalone.sh` command? Am I right? If that's the case, we should find a way to enable extra flags in the container. Would something like `KEYCLOAK_EXTRA_ARGS` work for you?

**Comment by CarlosAugustoAlves** [comment]
Yes, KEYCLOAK_EXTRA_ARGS  looks good to me.

**Comment by javsalgar** [comment]
Awesowe, I will open a task for implemeting it.

**Comment by CarlosAugustoAlves** [comment]
Thank you!

**Comment by apizzoni** [comment]
Hi,
I need to configure -Dkeycloak.profile.feature.scripts = enabled, will this implementation resolve this problem? Can I achieve this now in other way?

**Comment by CarlosAugustoAlves** [comment]
Hi,

At this moment I need specifically of admin_fine_grained_authz and token_exchange.

Follow list: https://github.com/keycloak/keycloak-documentation/blob/master/server_installation/topics/profiles.adoc

**Comment by javsalgar** [comment]
Hi,

I'm working on the feature in the container. In the meantime, could you check this PR for the chart? https://github.com/bitnami/charts/pull/4583

**Comment by CarlosAugustoAlves** [comment]
Thank you seems good for me.

> Hi,
> 
> I'm working on the feature in the container. In the meantime, could you check this PR for the chart? #4583



> Hi,
> 
> I'm working on the feature in the container. In the meantime, could you check this PR for the chart? #4583

Thank you seems good for me.

**Comment by javsalgar** [comment]
Hi, the latest release of the container should include the variable, please let us know if you find any other issues.

**Comment by CarlosAugustoAlves** [comment]
Thank you so much! I'll test it.

**Comment by apizzoni** [comment]
Thank you so much!, Can I use it like this?

```
extraStartupArgs:
  - upload_scripts: enabled
```

**Comment by marcosbc** [comment]
@apizzoni Unfortunately that format is not currently supported by this image, it has to be a string. However, feel free to send a PR with the change, we'd be glad to review it! (in that case, make sure passing it as string is also compatible to avoid a breaking change)
