### ISSUE TITLE
Dynamic update of prometheus jobs

### ISSUE THREAD

**Issue by Gunakk** [bitnami/charts#4552]
Brief:
No provision to add more Jobs while prometheus deployment is running

1.  As of now, the prometheus config reloader is taking it's configuration from /etc/prometheus/config/prometheus.env.yaml.gz whose directory is read only file system.
2.  On a running kubernetes deployment, I want to be able to mount a prometheus configuration file to host (something like prometheus.yaml), which on editing on hostpath, should be loaded by prometheus also. As far as I know, this is not possible.

Can someone please let me know if this is possible, if yes, how ?

Thanks,
Guna

**Comment by javsalgar** [comment]
Hi,

Just to ensure, are you talking about the `kube-prometheus` chart or the `stable/prometheus` chart? We maintain the kube-prometheus operator, which is in charge of deploying the prometheus instances. In that case, I don't think the operator has hostPath support. In the operator, everything is meant to be done using the Kubernetes API, so using a hostPath would cause the state to be out of sync.

**Comment by Gunakk** [comment]
HI,

Thank you for the response. 

I am using kube-prometheus. The important job of config reloader is to check if there is any change in prometheus.yaml configuration and send a reload request to prometheus.  I want to understand on a running deployment, if I want add an additional job, How do I do it ?

I am new to prometheus. Please excuse if I am missing something.

Thanks,
Guna

**Comment by javsalgar** [comment]
Hi,

> The important job of config reloader is to check if there is any change in prometheus.yaml configuration and send a reload request to prometheus

The image is configmap-reload, so it would detect changes in the prometheus configmap. I'm not a Prometheus expert, but did you check the ServiceMonitor object? https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md

I think these may cover your use case, as the new target would make Prometheus reload. Also, did you check the Prometheus object that the chart creates?

```
kubectl get prometheus -o yaml 
```

There you can see several settings.
