### ISSUE TITLE
[bitnami/grafana] Add support for supplying smtp hostname in Helm chart

### ISSUE THREAD

**Issue by kristinnardal2** [bitnami/charts#4557]
**Which chart**:
bitnami/grafana

**Is your feature request related to a problem? Please describe.**
When setting up smtp for Grafana you usually need to change the host from the default `localhost:25`. There are already settings in the Helm chart for enabling smtp and setting username and password. It's possible to set the host in other ways but an option to set it easily would be nice to have.

**Describe the solution you'd like**
I'd like a new field in the `values.yaml` file, `smtp.host`, which when set will set the GF_SMTP_HOST environment variable in the Grafana deployment to the value provided in the field `smtp.host`.

**Describe alternatives you've considered**
I've considered two alternatives:
1. Add the GF_SMTP_HOST environment variable with the `extraEnvVars` field in the `values.yaml` file
2. Add the smtp host in a `config.ini` file

I don't particularily like option 2 as it splits up the config of smtp into two places, the `config.ini` provided to the deployment as a configmap, and environment variables set in the Helm chart.

Option 1 is acceptable as the config is at least all in the same file but the smtp configuration is still fragmented.

**Comment by dani8art** [comment]
Hi @kristinnardal2 thank you so much for the feedback, I've created a PR to add this feature to the chart, please, let's move the conversation there.
