### ISSUE TITLE
K8s List: Helm linter fails due to missing name

### ISSUE THREAD

**Issue by oliverbaehler** [bitnami/charts#4559]
**Which chart**:
kafka
kube-prometheus/templates
kubernetes-event-exporter

**Describe the bug**

Yesterday I upgraded to the latest helm version (v3.4.1) and tried to lint a chart I wrote myself, which contains a Kubernetes list. Suddenly I got this linting error:

```
templates/list.yaml: object name must be between 0 and 253 characters: ""
```

This relates to this [Issue](https://github.com/helm/helm/issues/9019) or atleast someone else is having the same problems. I figured that this error occured, because my list resource didn't have any metadata at all (because it's not really of any use). This is what the list looked like while getting this error:

```
apiVersion: v1
kind: List
items:
  ....
```
After adding a name, the lint won't fail anymore:

```
apiVersion: v1
kind: List
metadata:
  name: "list"
items:
  ....
```

I was thinking of the kafka chart, since I know that it also implements kubernetes list. So I wanted to bring this to your attention. I made i quick grep over the chart directory and discovered, that currently three charts implement lists without having a name:

```
$ grep -R "kind: List" bitnami/*
  bitnami/kafka/templates/extra-list.yaml:kind: List
  bitnami/kube-prometheus/templates/prometheus/additionalPrometheusRules.yaml:kind: List 
  bitnami/kubernetes-event-exporter/templates/extra-list.yaml:kind: List
```

Now i am not quiet sure which approach you would chose to fix it. I see other charts with an `èxtraResource``functionality don't implement a kubernetes list (eg.  https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/extradeploy.yaml). Changing the named charts to this functionality would already resolve the issue. Or you could just simple give the lists a name, as far as I am aware this doesn't affect any of the items or anything else. It's just the helm validation that throws this error.

**To Reproduce**

1. Install the latest helm release
2. Create a chart and add a simple list:

```
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: build-robot
    automountServiceAccountToken: false
```
3. Try to lin it (`helm lint .`)

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-15T17:26:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Before I made a contribution I wanted to ask for your opinion on this.

**Comment by javsalgar** [comment]
Hi,

I've seen the Airflow approach and looks good to me, it would make sense to replace the current extra list with that.

```
{{- range .Values.extraDeploy }}
---
{{ include "common.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
```

**Comment by oliverbaehler** [comment]
@javsalgar Thanks for your response. Created PR, I just put all the changes into one PR. If that's not okay let me know and I will create for each chart a separate one.

**Comment by javsalgar** [comment]
Thank you so much! We'll take a look
