### ISSUE TITLE
[mongodb-sharded] authorization is properly enabled on primaries only

### ISSUE THREAD

**Issue by alrf** [bitnami/charts#4560]
**Which chart**:
mongodb-sharded (3.1.0)

**Describe the bug**
Authorization is properly enabled on primaries only.
On all secondaries the `/opt/bitnami/mongodb/conf/mongodb.conf` file contains `authorization: disabled`:
```
security:
  authorization: disabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile
```

which caused by `unset MONGODB_ROOT_PASSWORD` command here:
https://github.com/bitnami/charts/blob/8a88fda6fabbeb8775e5a03cbd6b86671ecf6818/bitnami/mongodb-sharded/templates/replicaset-entrypoint-configmap.yaml#L26

And `mongodb_set_auth_conf` function depends on `MONGODB_ROOT_PASSWORD` value here:
https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/f6aa35eb807c51713bdf125dfe6f80be471dc804/3.6/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh#L430
https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/f6aa35eb807c51713bdf125dfe6f80be471dc804/3.6/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh#L436

**Expected behavior**
Authorization is also enabled on secondaries, mongodb.conf contains `authorization: enabled`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @alrf, thanks for raising this issue. Do you have any suggestions to fix the issue? Did you try by removing the `unset MONGODB_ROOT_PASSWORD` line? I'm not sure if that would have any side effects, but it's worth trying.

**Comment by alrf** [comment]
Hi @andresbono Yes, I tried to remove `unset MONGODB_ROOT_PASSWORD` line and it caused the secondary pods crashes with error: `MONGODB_ROOT_PASSWORD shouldn't be set on a 'non-primary' node` from here: https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/f6aa35eb807c51713bdf125dfe6f80be471dc804/3.6/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh#L58

As workaround I used
```
extraEnvVars:
  - name: MONGODB_PASSWORD
    value: "yes"
```
in the `common` section of my `values.yaml` file.

But it would be really great to change the `mongodb_set_auth_conf` function so that it doesn't depend on these variables.

**Comment by andresbono** [comment]
> But it would be really great to change the mongodb_set_auth_conf function so that it doesn't depend on these variables.

If you want, you can open a PR changing that, but I'm not really sure of the drawbacks for that change. We will need to review it in depth. Also, if the function doesn't depend on `MONGODB_ROOT_PASSWORD` and `MONGODB_PASSWORD`, what other variables would you suggest as an alternative?

In addition to that, does the authorization setting in a secondary node has any effect? Doesn't the primary configuration apply instead?

**Comment by alrf** [comment]
Maybe makes sense to simply enable authorization on secondaries, because it was already enabled on primaries (and this is behavior "by default"). It seems just confusing to see the different settings on pods.

**Comment by andresbono** [comment]
Yes, it's true that it can be confusing if not all the nodes of the cluster have the same settings. Would you like to open a PR drafting the changes that you consider would be needed?
