### ISSUE TITLE
[bitnami/grafana] Setting smtp.enabled doesn't enable smtp

### ISSUE THREAD

**Issue by kristinnardal2** [bitnami/charts#4561]
**Which chart**:
bitnami/grafana

**Describe the bug**
Setting `smtp.enabled` to true when installing the Grafana Helm chart doesn't actually enable the smtp config. It only makes it so that username and password are set using environment variables.

**To Reproduce**

1. Install the bitnami/grafana Helm chart with the following values
    ```yaml
    smtp:
        enabled: true
        user: <username>
        password: <password>
    ```
2. Access the Grafana instance
3. Navigate to 'Server Admin' -> 'Settings'
4. Under the smtp header you will see that smtp is not enabled

**Expected behavior**
I expect that smtp will be enabled when I set `smtp.enabled: true` in the `values.yaml` file.

**Additional context**
You can still enable smtp by either providing a config.ini file where `smtp.enabled` is set to true or by setting the environment variable `GF_SMTP_ENABLED` to "true" using the `extraEnvVars` field in the `values.yaml` file.

Currently setting `smtp.enabled` to true sets the environment variables `GF_SMTP_USER` and `GF_SMTP_PASSWORD`, we can just make it also set the `GF_SMTP_ENABLED` environment variable.

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for spotting this.
  I am sending a PR to fix it.

**Comment by rafariossaa** [comment]
Hi, 
  I merged it, could you try the new release and see if it fixes the issue for you ?

**Comment by kristinnardal2** [comment]
Thanks for the quick fix, there was however an error in the PR as all environment variables need to be strings.
When trying to install now I get the following error:
```console
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true},{"nam|..., bigger context ...|fana-admin"}}},{"name":"GF_SMTP_ENABLED","value":true},{"name":"GF_SMTP_USER","valueFrom":{"secretKe|...
```

To fix this quote the `true` in the PR.

**Comment by kristinnardal2** [comment]
I can confirm that this is working after #4566

**Comment by rafariossaa** [comment]
Hi,
  I am happy this was fixed and worked for you.
