### ISSUE TITLE
[mongodb-sharded] extraEnvVars are not passed into shard-data-statefulset.yaml and shard-arbiter-statefulset.yaml

### ISSUE THREAD

**Issue by alrf** [bitnami/charts#4563]
**Which chart**:
mongodb-sharded (3.1.0)

**Describe the bug**
`extraEnvVars` are not passed into `shard-data-statefulset.yaml` and `shard-arbiter-statefulset.yaml`, but for other components they are.

For example, `extraEnvVars` are passed for configsvr:
https://github.com/bitnami/charts/blob/3f6054c1c9633d0aa78d15d2a3e3ea009c35940f/bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml#L152-L157

The same for others, except `shard-data-statefulset.yaml` and `shard-arbiter-statefulset.yaml` files.

**Expected behavior**
`shard-data-statefulset.yaml` and `shard-arbiter-statefulset.yaml` files contain the code for `extraEnvVars`.

**Comment by FraPazGal** [comment]
Hello @alrf,

Thanks for catching this! I'll create a PR to solve this issue and merge it as soon as possible.
