### ISSUE TITLE
_helper.tpl for wordpress chart is missing "wordpress.fullname" and "wordpress.tplValue" as referenced in template configmap.yaml

### ISSUE THREAD

**Issue by malagant** [bitnami/charts#4568]
**Which chart**:
latest Wordpress chart

**Describe the bug**
When adding `customPostInitScripts` like in https://github.com/bitnami/charts/issues/4255#issuecomment-730520452 the `_helper.tpl` for wordpress chart is missing `wordpress.fullname` and `wordpress.tplValue` as referenced in template `configmap.yaml`

**To Reproduce**

Apply some valid yaml to the `customPostInitScripts` like in https://github.com/bitnami/charts/issues/4255#issuecomment-730520452

Then you get the error `Error: template: wordpress/templates/configmap.yaml:5:20: executing "wordpress/templates/configmap.yaml" at <{{template "wordpress.fullname" .}}>: template "wordpress.fullname" not defined`

**Expected behavior**
Template should render properly.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.6-r1-CCE2.0.30.B001", GitCommit:"3270aae40a24cd434ea48f594746f020c7473203", GitTreeState:"clean", BuildDate:"2020-01-08T10:05:41Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  It seems to be some issue with the indentation in the yaml file.
  I added this to `values.yaml` and got it rendered without issues:
```
##     ...
##
## NOTE: Combined with extraVolume and extraVolumeMounts to mount the configmap to /docker-entrypoint-init.d where custom user init scripts are looked for
customPostInitScripts:
  enable-multisite.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    wp core multisite-install --url=example.com --title="Welcome to the WordPress Multisite" --admin_user="doesntmatternotreallyused" --admin_password="doesntmatternotreallyused" --admin_email="user@example.com"
    cat /docker-entrypoint-init.d/.htaccess > /bitnami/wordpress/.htaccess
    chmod -w bitnami/wordpress/wp-config.php
  update_db.query: |
    USE bitnami_wordpress;
    UPDATE `bitnami_wordpress`.`wp_blogs` SET `domain` = 'localhost' WHERE (`blog_id` = '1');
    UPDATE `bitnami_wordpress`.`wp_site` SET `domain` = 'localhost' WHERE (`id` = '1');
  .htaccess: |
    <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]

    # add a trailing slash to /wp-admin
    RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
    RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
    RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
    RewriteRule . index.php [L]
    </IfModule>
```
  Coudl you give it a try ?

**Comment by malagant** [comment]
Sorry, for me it doesn't work because helm is complaining about the missing includes I mentioned before. If you have a look at _helper.tpl you'll see they are missing.

**Comment by rafariossaa** [comment]
Hi,
  Could you update your clone of the the chart repository ? 
  As you can see in the [configmap.yaml](https://github.com/bitnami/charts/blob/d06e73d8a94a383aa5c02a4ebea8b9ea99e53219/bitnami/wordpress/templates/configmap.yaml#L5) , there is not reference to `wordpress.fullname`.

**Comment by malagant** [comment]
Thanks a lot. 😀

**Comment by cauldyclark15** [comment]
> Thanks a lot.

Hi, did you able to solve this issue?

**Comment by rafariossaa** [comment]
Hi @malagant 
  If you was not able to solve it this way, please feel free to reopen it or create a new one.

**Comment by cauldyclark15** [comment]
> Hi @malagant
> If you was not able to solve it this way, please feel free to reopen it or create a new one.

@rafariossaa 
Hi, thanks for this great library, but I am still having the exact issue using the latest chart

**Comment by rafariossaa** [comment]
Hi @cauldyclark15 ,
  Could you indicate the chart version and command/settings you are using ?, just to double check.
