### ISSUE TITLE
Upgrade spring-cloud-dataflow chart to SCDF OSS v2.7

### ISSUE THREAD

**Issue by sabbyanandan** [bitnami/charts#4570]
**Which chart**:
[spring-cloud-dataflow](https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/README.md)

**Describe the solution you'd like**
We would like to request to update the [spring-cloud-dataflow](https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/README.md) chart to the next minor release of SCDF OSS, which is at 2.7 GA as of today.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. We're working on packaging the new version. I will update this ticket as soon as it is ready.

**Comment by chrisjs** [comment]
in https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/templates/server/deployment.yaml#L129 

`SPRING_CLOUD_DATAFLOW_TASK_COMPOSED_TASK_RUNNER_URI` has been deprecated (but still remains) in the current release so we should move that over to `SPRING_CLOUD_DATAFLOW_TASK_COMPOSEDTASKRUNNER_URI`

**Comment by javsalgar** [comment]
Thanks for the input! I will forward it to the team

**Comment by dani8art** [comment]
Hi,

`bitnami/spring-cloud-dataflow@2.2.0` has been released, this version includes the next version of SCDF 2.7 and adapts some environment variables to match this new version.

You can find it in bitnami chart repo

```console
$ helm repo update
$ helm search repo bitnami/spring-cloud-dataflow
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/spring-cloud-dataflow	2.2.0        	2.7.0      	Spring Cloud Data Flow is a microservices-based...
```

Please, don't hesitate to contact us if you find any problem or have any suggestion.

Thanks!

**Comment by sabbyanandan** [comment]
Nicely done, @dani8art! Thanks.
