### ISSUE TITLE
[bitnami/harbor] Unable to use notary and clair with an external PGSQL12 DB

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#4574]
**Which chart**:
Harbor 9.x ( i havent tested older Versions, most likely they have the same bugs)

**Describe the bug**
- For Clair:
Clair itself wont connect to an PGSQL12 DB and fails with the following logline:
```
 09:36:14.40 INFO  ==> ** Starting Harbor Clair **
{"Event":"pgsql: could not open database: pq: unknown authentication response: 10","Level":"fatal","Location":"main.go:97","Time":"2020-12-02 09:36:14.459981"}
```
This would normally indicate an incompatibility with SCRAM-SHA-256, but we have testwise reverted everything back to MD5 and faced the same error.

- For Notary:
Both notary-server and notary-signer fail in the migration process with the following loglines repeating over and over:
```
error: pq: unknown authentication response: 10
/opt/bitnami/harbor-notary-server/migrations/migrate.sh: 16: /opt/bitnami/harbor-notary-server/migrations/migrate.sh: [[: not found
waiting for postgres://harbor_notaryserver_adm:start123@10.90.50.6:5432/harbor_notaryserver?sslmode=require to come up.
```
This would normally indicate an incompatibility with SCRAM-SHA-256, but we have testwise reverted everything back to MD5 and faced the same error.
Calling the migrate binary manually condenses it to this logline:
```error: pq: unknown authentication response: 10````

**To Reproduce**

1. Deploy the Helm chart with an external PostgresDB (12.3 in our case)

**Expected behavior**
Pods communicate fine with the DB, like harbor core and other componnents do.

**Additional context**
I will file the same issue for the affected containers, ass that whould also apply to a standalone docker usage of them

**Comment by marcosbc** [comment]
Hi @MaxRink, our understanding is that Harbor does not yet support PostgreSQL 12. In fact, their official Helm chart still uses 9.6 but we were able to update that to 11.x.

It seems like the PostgreSQL driver would need to be updated on Harbor's side in order to work properly, and that's something we don't control unfortunately.

**Comment by MaxRink** [comment]
HArbor itself works fine btw, only dependencies that are sourced externally are affected

**Comment by marcosbc** [comment]
Sure, in the end Notary and Clair are optional parts of Harbor so the main application itself is functioning.

However, [Notary](https://github.com/theupdateframework/notary) seems to still recommend PG 9.6 (according to it's docker-compose for PG).
As for [Harbor Clair Scanner](https://github.com/goharbor/harbor-scanner-clair/blob/master/go.mod) you can see it uses a quite [old version](https://github.com/lib/pq/releases/tag/v1.2.0) of the pq library (which supposedly supports SCRAM-SHA-256 as of [1.1.0](https://github.com/lib/pq/releases/tag/v1.1.0)) but it might not be working properly.

**Comment by mouradev1** [comment]
Resolvido seguindo esses passos:

Mudar "password_encryption" para "md5" no arquivo "postgresql.conf"

Mudar as primeiras 3 ocorrências de "scram-sha-256" para "trust" no arquivo "pg_hba.conf"

# "local" é somente para conexões de soquete de domínio Unix
"local   all             all                                     trust"
# conexões locais IPv4:
"host    all             all             127.0.0.1/32            trust"
# conexões locais IPv6:
"host    all             all             ::1/128                 trust"

Reiniciar o serviço postgresql

Executar "psql -U postgres" (você não será solicitado a senha)

Alterar a senha com o comando "\password nome_de_usuario"

Mudar as primeiras 3 ocorrências de "trust" para "md5" no arquivo "pg_hba.conf"

# "local" é somente para conexões de soquete de domínio Unix
"local   all             all                                     md5"
# conexões locais IPv4:
"host    all             all             127.0.0.1/32            md5"
# conexões locais IPv6:
"host    all             all             ::1/128                 md5"

Reiniciar o serviço postgresql"
