### ISSUE TITLE
SocketException、SCRAM-SHA-1、did not become available

### ISSUE THREAD

**Issue by huisebug** [bitnami/charts#4584]
I configured 2 rs copies and 1 arbiter, and turned on metrics. When my helm is established, the first pod of the statefulset can always be successfully established, and then the second pod is always restarting, and the second pod There are error messages in 2 containers in
mongodb:
Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused

metrics:
Liveness probe failed: time="2020-12-03T02:03:06Z" level=error msg="Can't connect to MongoDB: Cannot get buildInfo() for MongoDB using uri mongodb://root:mongodb@localhost:27017 /admin?: connection(): auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed." source="mongodb_exporter.go:72"

Then cause the arbiter log to print
ERROR ==> Node mongodb-cluster-0.mongodb-cluster-headless.yire.svc.cluster.local did not become available

**Comment by huisebug** [comment]
![Uploading image.png…]()

**Comment by huisebug** [comment]
I have solved my problem and provided my yaml


[values-cluster.yaml.txt](https://github.com/bitnami/charts/files/5635301/values-cluster.yaml.txt)

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to solve the issue, and thanks for sharing your `values.yaml`
  Could you provide more info on what the solution was ?

**Comment by huisebug** [comment]
After running for 12 hours, the mongodb rs cluster is normal, but the metrics of the second pod keep showing errors, and it is still being studied.
![image](https://user-images.githubusercontent.com/27762438/101109004-d6706980-3610-11eb-9f62-1fcb80375ad5.png)

**Comment by huisebug** [comment]
externalAccess:
Will affect the value of the variable MONGODB_ADVERTISED_HOSTNAME, which is the value of the rs.conf() command (member.host) of the rs cluster that the cluster rs node joins to the cluster.
  # If it is turned on and the exposure method is Nodeport, the domain needs to be set, and the domain can only write one, which will cause the node to be unable to fully join
  # If you open and do not set the domain when the exposure mode is Nodeport, it will be MONGODB_ADVERTISED_HOSTNAME=$(curl -s https://ipinfo.io/ip), this is a public IP, and the cluster will not run
  # Open the affected template files: templates/replicaset/scripts-configmap.yaml and templates/replicaset/statefulset.yaml
  # If it is not turned on, the pod host name will be used as the value of MONGODB_ADVERTISED_HOSTNAME, and the cluster can run successfully

So there are 2 options for running the cluster,
Solution 1: Do not open externalAccess
Solution 2: Open externalAccess, but do not configure the domain, and modify the templates/replicaset/scripts-configmap.yaml
#export MONGODB_ADVERTISED_HOSTNAME=$(curl -s https://ipinfo.io/ip)
As:
 export MONGODB_ADVERTISED_HOSTNAME="$MY_POD_NAME.$K8S_SERVICE_NAME.$MY_POD_NAMESPACE.svc.{{ .Values.clusterDomain }}"
与此原文有关的更多信息要查看其他翻译信息，您必须输入相应原文

**Comment by huisebug** [comment]
Below is the modified yaml
[scripts-configmap.yaml.txt](https://github.com/bitnami/charts/files/5640491/scripts-configmap.yaml.txt)
[values-cluster.yaml.txt](https://github.com/bitnami/charts/files/5640492/values-cluster.yaml.txt)

**Comment by huisebug** [comment]
The reason for the SocketException is that the cluster is running normally and externalAccess is turned on and not configured correctly

SCRAM-SHA-1 is an error prompted by metrics and the cluster is not configured correctly. Previously, a mongodb-cluster-0.mongodb-cluster-headless.yire.svc.cluster.local was configured at externalAccess.service.doamin, which would As a result of the two pods in the cluster, only the mongodb container of mongodb-cluster-0 can be added to the cluster, so the mongodb of mongodb-cluster-1 cannot join the cluster, and the metrics container of mongodb-cluster-1 also fails the authentication. You can use the following The command to debug:
 export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace yire mongodb-cluster -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
    kubectl run --namespace yire mongodb-cluster-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.2 -debian-10-r0 --command - bash
  mongo admin --host "mongodb-cluster-1.mongodb-cluster-headless.yire.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
Connected to the rs cluster, indicating that the cluster has joined successfully

 Arbiter will first connect to the PRIMARY node, which is mongodb-cluster-0
, If mongodb-cluster-0 is not running normally, arbiter will prompt an error,
