### ISSUE TITLE
bitnami/redis 12.1.1 - Once I enable redis.tls and Metrics, I got errors of "bad certificate" and No metrics data shown on Grafana

### ISSUE THREAD

**Issue by drmy** [bitnami/charts#4585]
**Which chart**:
The name (and version) of the affected chart
bitnami/redis 12.1.1

**Describe the bug**
Once I enable TLS and Metrics, then in the Redis log I see the following errors:

**Error accepting a client connection: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate**

And, no metrics data can be shown on my Grafana, even though I can see that Prometheus has successfully detected the redis nodes with metrics, e.g. this is green: http://10.244.7.76:9121/metrics

I saw there was a bug - **Redis Metrics Exporter doesn't fully support TLS** below:
[https://github.com/oliver006/redis_exporter/issues/387](url)
This bug seems to have been fixed included into the 12.1.1, however I still see the issue.

**Comment by drmy** [comment]
Does anyone have the same problem? I just won't be able to enable Redis TLS and Metrics at the same time, I am using bitnami/redis with the sentinel mode.

So,
If I disable TLS and enable metrics, metrics can work fine
If I enable TLS and disable metrics, redis logs are good, with no errors, TLS works fine.
If I enable TLS and enable metrics, metrics won't work, and redis log keeps writting "bad certificates" erros but actually TLS can work fine with my redis client.

**Comment by marcosbc** [comment]
Hi @drmy, it looks like you also need to specify TLS option to the Redis Metrics tool. You can do that via [`metrics.extraArgs`](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L651).

You can find the Redis Metrics CLI flags for TLS [here](https://github.com/oliver006/redis_exporter#command-line-flags).

**Comment by drmy** [comment]
> Hi @drmy, it looks like you also need to specify TLS option to the Redis Metrics tool. You can do that via [`metrics.extraArgs`](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L651).
> 
> You can find the Redis Metrics CLI flags for TLS [here](https://github.com/oliver006/redis_exporter#command-line-flags).


Thank you very much @marcosbc . It works now.

In my case, I just put the following item in the metrics section of value file to skip tls verification for redis exporter:

  extraArgs:
    skip-tls-verification: true

**Comment by dani8art** [comment]
That's cool! but it would be good to have some lines at this section in the README.md https://github.com/bitnami/charts/tree/master/bitnami/redis#securing-traffic-using-tls just saying what Marcos added 

> You can do that via `metrics.extraArgs`. You can find the Redis Metrics CLI flags for TLS here.

would you like to contribute with a PR to the repo?

**Comment by drmy** [comment]
> That's cool! but it would be good to have some lines at this section in the README.md https://github.com/bitnami/charts/tree/master/bitnami/redis#securing-traffic-using-tls just saying what Marcos added
> 
> > You can do that via `metrics.extraArgs`. You can find the Redis Metrics CLI flags for TLS here.
> 
> would you like to contribute with a PR to the repo?

Yeah. Let me learn how to make a PR...

And my use case is simple since I can accept to skip client TLS authentication so I take: skip-tls-verification: true
But I think in case of requiring the client TLS authentication then we might need to set some other key/values:
tls-client-key-file
tls-client-cert-file
tls-ca-cert-file
[https://github.com/oliver006/redis_exporter#command-line-flags)]
I haven't got an environment to test that yet.

**Comment by dani8art** [comment]
Yep, you are completely right, let me check and I could add some guidance about how to add those flags. 

BTW, you could start working on the PR, please take a look at this file: https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md

Thanks!

**Comment by dani8art** [comment]
Hi @drmy did you have a chance to work on this?

**Comment by drmy** [comment]
> Hi @drmy did you have a chance to work on this?

Hi @dani8art , I am sorry for the slow resoponse because I was busy in some work stuff. Yes, I am working on that and plan to make it by this week, will keep you updated.

**Comment by dani8art** [comment]
That's great! thanks!

**Comment by drmy** [comment]
Hi @dani8art ,

I have created a PR for the redis README.md change for the metrics parameter usage:

https://github.com/bitnami/charts/pull/5207

**Comment by drmy** [comment]
> Hi @dani8art ,
> 
> I have created a PR for the redis README.md change for the metrics parameter usage:
> 
> #5207

Hi,

Thank you for the PR merging. However, I just found that I made a markdown mistake affecting the following line in the readme.md file. I think we will need to open a new issue to fix the bug and we can also merge the correct changes to the redis-cluster helm Chart. I apologize for that.

https://github.com/bitnami/charts/tree/master/bitnami/redis#metrics

### Host Kernel Settings

**Comment by dani8art** [comment]
Ok sure, let's create it then. Thanks for reporting it!

**Comment by drmy** [comment]
> Ok sure, let's create it then. Thanks for reporting it!

I created a PR and the fix has been merged:
https://github.com/bitnami/charts/pull/5232
