### ISSUE TITLE
[mongodb] Liveness and readiness probes spam the logging too much

### ISSUE THREAD

**Issue by yule-cao** [bitnami/charts#4587]
**Which chart**:
mongodb

**Is your feature request related to a problem? Please describe.**
The liveness and readiness probes spam the logging with a lot of connection messages. It is difficult to find relevant logs because you have to scroll through a lot of pages of the same messages over and over again before you find the important messages.

**Describe the solution you'd like**
The liveness and readiness probes can work silently.

**Comment by FraPazGal** [comment]
Hello @yule-cao,

It is true that the health checks can create a lot of noise, but I'm not sure if we should have them without verbose by default as their function as a heartbeat can be really useful. If you prefer to change their default behaviour, probes can also be customised using the parameters `customLivenessProbe` and `customReadinessProbe`.

**Comment by yule-cao** [comment]
Hi @FraPazGal ,

I tried with TCP probe but it still brought a lot of noise.
Is there any other way to probe appropriately while keeping the log clean?

**Comment by marcosbc** [comment]
Hi @yule-cao, I guess you are referring to the "Connection accepted" and "Connection ended" log lines, right? Unfortunately I don't know of any way to disable those lines only for the health check, as they make a connection to MongoDB to check whether it is alive.

I would recommend you to look into the [`systemLogVerbosity` and `disableSystemLog` chart options](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L128) instead, although it would affect all connections (not only health check).

Alternatively, you could always check whether MongoDB is alive/ready with another command (such as checking whether the 27017 port is open), although it would not be as accurate and could cause some downtime. To do that check the [`customLivenessProbe` and `customReadinessProbe` chart options](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L364).
