### ISSUE TITLE
bitnami/rabbitmq  Set the error   -- Set podManagementPolicy=Parallel

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#4590]
helm3 install mqsh --set persistence.storageClass=nfs-storage --set persistence.size=1Gi --set replicaCount=3 --set auth.username=gefuxing --set auth.password=gefuxing --set service.type=NodePort    --set podManagementPolicy=Parallel bitnami/rabbitmq

When I set -- Set podManagementPolicy=Parallel, login to the UI, why only show two POD node and I set three replicas

![image](https://user-images.githubusercontent.com/43690953/100987988-26581d80-358a-11eb-9651-b0d3e3709f21.png)
How can I solve it?

**Comment by Gefuxing** [comment]
You can try to deploy, follow the deployment command, log in to the UI interface, and see?

**Comment by Gefuxing** [comment]
## RabbitMQ should be initialized one by one when building cluster for the first time.
## Therefore, the default value of podManagementPolicy is 'OrderedReady'
## Once the RabbitMQ participates in the cluster, it waits for a response from another
## RabbitMQ in the same cluster at reboot, except the last RabbitMQ of the same cluster.
## If the cluster exits gracefully, you do not need to change the podManagementPolicy
## because the first RabbitMQ of the statefulset always will be last of the cluster.
## However if the last RabbitMQ of the cluster is not the first RabbitMQ due to a failure,
## you must change podManagementPolicy to 'Parallel'.
## ref : https://www.rabbitmq.com/clustering.html#restarting
##
podManagementPolicy: OrderedReady

**Comment by Gefuxing** [comment]
![image](https://user-images.githubusercontent.com/43690953/100988938-3fad9980-358b-11eb-8630-e3153133df77.png)

**Comment by rafariossaa** [comment]
Hi,
  How many rabbitmq pods do you have ? Are any of them showing errors in the logs ?
  If you don't set the podManagementPolicy parameter, do you get the same behavior ?

**Comment by Gefuxing** [comment]
There are three PODS in total, check the log and find no exception, all are normal, if I do not set podManagementPolicy, it is ok, but the creation is slow, it takes about five minutes, or longer, so set podManagementPolicy=Parallel

**Comment by rafariossaa** [comment]
Can you leave the `podManagementPolicy` as `OrderedReady` and enable debug ?
Let's see if you get some timeouts (or other errors) in the log.
