### ISSUE TITLE
[bitnami/kafka]  Understanding zookeeper role

### ISSUE THREAD

**Issue by dfgrosso** [bitnami/charts#4592]
Hello everyone.

We have installed kakfa chart on our cluster and our client applications are using spring connector to connect with kafka.

Everything is working fine but we would like to better understand this kafka architecture, namely, the role of zookeeper. We've been crawling the web but different articles give different roles to zookeeper in the kafka platform. Some of them suggest the its role has been changing over time.

Given that we have version 2.5 installed, can anyone please point me out to some documentation that covers in a trustful way how kafka and zookeeper work together in this version, in both perspectives: production/consumption.

Thanks ;)

Regards,
Daniel

**Comment by marcosbc** [comment]
Hi @dfgrosso, ZooKeeper serves as a metadata server for Kafka, and is also used to perform broker elections. The most relevant page I could find on the official site is this: https://kafka.apache.org/documentation/#impl_zookeeper (based on [this answer](https://stackoverflow.com/questions/54039166/what-is-the-actual-role-of-zookeeper-in-kafka-2-1)).

**Comment by dfgrosso** [comment]
Thank you @marcosbc !
