### ISSUE TITLE
[kube-prometheus]  When operator.enabled: false, Prometheus is not deployed

### ISSUE THREAD

**Issue by pbrissaud** [bitnami/charts#4593]
**Which chart**:
kube-prometheus 2.2.3

**Describe the bug**
When installing the chart with `operator.enabled: false`  the prometheus statefulset is not deployed. If I want to not have the Prometheus Operator , I have install the chart with `operator.enabled: true` then upgrade with `operator.enabled: false` and its works.

**To Reproduce**

1. Download charts (air-gapped environnement 😅 )
2. Set `operator.enabled: false` in values-production.yaml
3. `helm install prom charts/kube-prometheus -f charts/kube-prometheus/values-production.yaml`
4. `kubectl get pods`
5. `kubectl get statefulset.apps`
6. No output in step 4 & 5

**Expected behavior**
The statefulset is deployed 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v.3.3.4", GitCommit:"a61ce5633af9970817141435ed49547cf05013d",  GitTreeState: "clean", GoVersion: "go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

I am afraid this is not possible. The chart is not deploying any Prometheus instance, it is the operator the one that deploys it. If you want to have Prometheus without the operator, my advice would be using the stable/prometheus chart. Our current offer is only the operator.

**Comment by pbrissaud** [comment]
Hi, 
Thanks for your answer ! I was thinking so but the documentation confused me : 
> Only one instance of the Prometheus Operator component should be running in the cluster. If you wish to deploy this chart to manage multiple instances of Prometheus in your Kubernetes cluster, you have to disable the installation of the Prometheus Operator component using the operator.enabled=false chart installation argument.

Maybe this part should be better explained ! 

Best regards,

Paul

**Comment by javsalgar** [comment]
Thanks for the feedback! We'll take a look and see if the wording can be improved

**Comment by ArtemChekunov** [comment]
what's the point to have the option then **operator.enabled=false** ?

**Comment by javsalgar** [comment]
It could be used for deploying a Prometheus object or Alertmanager object in case you already have the operator deployed in the cluster.
