### ISSUE TITLE
Bitnami charts repository has no updates

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/charts#4602]
**Which chart**:
[bitnami/influxdb]

**Describe the bug**
 Current repository version is 1.0.0 but in git repo we have 1.1.1

**To Reproduce**
Try to install bitnami/influxdb 1.1.1

**Expected behavior**
New chart version contained in repository and installs normally

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by beltran-rubo** [comment]
HI @Antiarchitect, thanks for reporting it and sorry for the delay. We are working on InfluxDB version 2 and that blocked our pipeline to release this Helm Chart with the latest changes. We are looking into it to fix it and continue releasing version 1 for the Chart as soon as possible. We will keep you in the loop.

**Comment by Antiarchitect** [comment]
Repo has been updated. Thank you!
