### ISSUE TITLE
Missing Pod for Trivy Stateful Set

### ISSUE THREAD

**Issue by parth-pandit** [bitnami/charts#4606]
**Which chart**:
The name (and version) of the affected chart
my-tac-repo/harbor
2.1.1 - my-tac-repo

**Describe the bug**
When I deploy an instance of Harbor on my TKGm cluster, I see all pods coming up except the pod for Trivy. There is no pod under Trivy Stateful Set, which shows 0/0 pods. There is no error that can be tracked. The pod is completely missing for Trivy. And possibly because of that I cannot login to Harbor portal using the username as `admin` and password obtained using `$(kubectl get secret --namespace default panditlabs-harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)`.

**To Reproduce**

1. Deploy Harbor Helm Chart for the version given above. 
2. Look at the running stateful sets using `kubectl get statefulset` in the namespace where the deployment was done. 
3. See that Stateful set for Trivy shows `0/0` pods running.

**Expected behavior**
There should be one pod for Trivy running fine under its stateful set

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:21Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2+vmware.1", GitCommit:"9da25ece4c3bd1aa2e9c77ba28f92dbfe3945dcb", GitTreeState:"clean", BuildDate:"2020-05-07T18:49:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I had to change the default configuration to update below items.

1. host names for Harbor components
2. volume permissions to allow Harbor and Postgres create required directories
3. default password for Harbor and Postgres DB

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Could you check if `kubectl describe sts <name of the trivy statefulset>` provides any meaningful information?
