### ISSUE TITLE
[bitnami/mongodb] Not able to configure own SSL CA certificate and Key

### ISSUE THREAD

**Issue by navneet066** [bitnami/charts#4607]
**Which chart**:
Helm Chart version 10.1.3

**Is your feature request related to a problem? Please describe.**
There is no option of applying my own SSL certificate and key. It always uses a self-signed certificate generated by `genCA` and `genSignedCert` function.

**Describe the solution you'd like**
The cluster should accept the SSL Certificate and key.

**Describe alternatives you've considered**
I Tried to put some hardcoded values in the `secrets-ca.yaml` file for the above but no success.

**Additional context**
NA

**Comment by marcosbc** [comment]
Hi @navneet066, currently it is not a feature supported by MongoDB like you mention, but we'd be glad to review any PR that implements such feature. Would you be open for contributing those changes?
