### ISSUE TITLE
Trivy scanner is not working when using proxy

### ISSUE THREAD

**Issue by cloux** [bitnami/charts#4608]
Trivy scanner fails in an airgapped environment with:

"FATAL - failed to download vulnerability DB: failed to list releases..."

Trivy container currently ignores proxy settings. Trivy should use the same proxy as Clair, see here: https://github.com/bitnami/charts/blob/beaaf129536ef28b3b52d8fda3ed8d4992751701/bitnami/harbor/values-production.yaml#L646-L650

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. Could you check this PR? https://github.com/bitnami/charts/pull/4609 it should fix the issue.
