### ISSUE TITLE
Scaling down zookeeper kills the cluster

### ISSUE THREAD

**Issue by hatharom** [bitnami/charts#4614]
**Which chart**:
bitnami kafka v11.3.4 with its  embedded zookeeper chart

**Describe the bug**
-Installing the chart with default settings ( but setting replicaCount to 3 both for ZK and Kafka).
-Wait to be everything up and running. At this point no error, they can communicate.
-Scale down: `kubectl scale statefulsets wrinkled-hare-zookeeper --replicas=1`
-**Results:** It kills the zookeeper. I can login to the remaining ZK pods and run` ./zkCli` but any operation like `'ls /' ` shows **_connection loss error_**

**Expected behavior**
Remain operable

**Version of Helm and Kubernetes**:
helm2, kubernetes v1.18

**Zookeeper log**
```
2020-12-04 15:15:07,954 [myid:1] - ERROR [LearnerHandler-/172.17.0.1:57084:LearnerHandler@707] - Unexpected exception causing shutdown while sock still open
java.io.EOFException
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:96)
        at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
        at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:134)
        at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:643)
```
**Kafka log**
```
{"@timestamp":"2020-12-04T15:18:02.279Z","source_host":"wrinkled-hare-kafka-0","file":"ClientCnxn.java","method":"run","level":"INFO","line_number":"1240","thread_name":"main-SendThread(wrinkled-hare-zookeeper:2181)","@version":1,"logger_name":"org.apache.zookeeper.ClientCnxn","message":"Unable to read additional data from server sessionid 0x100496c1af00003, likely server has closed socket, closing socket connection and attempting reconnect","class":"org.apache.zookeeper.ClientCnxn$SendThread","mdc":{"myid":"wrinkled-hare-zookeeper:2181"}}
```

**Comment by juan131** [comment]
Hi @hatharom 

You shouldn't use `kubectl scale sts ...` but `helm upgrade ... --set zookeeper.replicaCount=1` instead.

The reason is that, by using `helm upgrade`, the Zookeeper setting `ZOO_SERVERS` will be automatically adjusted to the new number of replicas (while it's not adjusted when running `kubectl scale`), see:

- https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/statefulset.yaml#L138

**Comment by hatharom** [comment]
Thanks!

**Comment by juan131** [comment]
You're welcome!!
I proceed to close the issue as solved, please feel free to reopen it if you require further help.
