### ISSUE TITLE
[bitnami/influxdb] udp support out of the box

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/charts#4616]
**Which chart**:
[bitnami/influxdb] 

**Is your feature request related to a problem? Please describe.**
Proxmox i.e. has only UDP InfluxDB support: https://pve.proxmox.com/wiki/External_Metric_Server

**Describe the solution you'd like**
UDP is turned on (or optionally) by default in this chart. I thought about a PR but it seems the default config for influxdb is contained inside the bitnami influxdb image - so any solution involving only chart modification will be ugly.

**Comment by marcosbc** [comment]
Hi @Antiarchitect, it'd be awesome if you could contribute this change, we'd be glad to review it and help with the release!

For the container image, you can find the source code for the initialization scripts (based on Bash) in the [`rootfs` directory](https://github.com/bitnami/bitnami-docker-influxdb/tree/master/1/debian-10/rootfs/opt/bitnami/scripts) of the container repo. Once a PR is merged, we'd launch our internal CI to perform the container image release, at which point the chart changes could also be merged.

**Comment by Antiarchitect** [comment]
Possibly I could do it after I check my own patched version works internally for me.
