### ISSUE TITLE
bitnami/discourse how to install plugins

### ISSUE THREAD

**Issue by enibache** [bitnami/charts#4624]
Dear bitnami support, 

thanks first for the wonderful job/effort you guys are putting in here. I realized that bitnami leaverages helmcharts for tools like discourse, which is supposedly a good endeavor, but discourse doesn't seem to encourage this at all as any questios regarding the bitnami/discourse helmcharts are immediately rejected by discourse and refered to bitnami(inofficial). There is a difference in the file structures depending on which deployment method followed thereby leading to differing approaches to resolve issues such as installing plugins. This guide for example doesn't help:

> $ cd /opt/bitnami/apps/discourse/htdocs
> $ sudo su bitnami
> $ RAILS_ENV=production bundle exec rake plugin:install repo=PLUGIN_REPO_URL
> $ RAILS_ENV=production bundle exec rake assets:precompile 

namely because the directory _/opt/bitnami/apps/discourse/htdocs_ does not exist in the docker container while using the bitnami/discourse helm chart deployment.

Well, i won't want to mention the click-performance in this deployment yet, as i guess it's better to do so in another post.
Please help with the plugins if possible.

thanks and cheers,
\enc

**Comment by marcosbc** [comment]
@enibache It seems you are following the documentation for Bitnami cloud images and installers. In the case of containers, the paths differ so you need to run the commands like this:

```
$ cd /opt/bitnami/discourse
$ RAILS_ENV=production bundle exec rake plugin:install repo=PLUGIN_REPO_URL
$ RAILS_ENV=production bundle exec rake assets:precompile
```

Refer to this related issue: https://github.com/bitnami/bitnami-docker-discourse/issues/28

**Comment by enibache** [comment]
HI Marcos,

Many thanks for your assistance and I truly appreciate your relentless
community efforts. I's able to resolve this issue earlier, but
unfortunately there's still some issues with the deployment namely:

- the performance(click performance)
- backup uploading (doesn't work)
- plugins installation successful but not usable(e.g data-explorer:
installed but not able to use as described in doc)

thus the client is feeling quite reluctant to continue the forum but rather
requesting for further search unless the aforementioned issues are
resolved. Any assistance would be greatly appreciated.

Thanks and kind regards,
\enc

---
Emmanuel Niba Che
(Dipl.-Ing.)
DevOps Engineer
Am Neumarkt 21
22041 Hamburg
+49-15141317665

**Comment by andresbono** [comment]
@enibache, we are always open to continue improving our assets so if you describe the problems you are facing in more detail, we can investigate if there is something we can do to improve the functionalities of our chart.

Starting with the original issue, can you share the commands that you are using to install the `data-explorer` plugin? Can you point us to the documentation that you are following and that is not working for you?

**Comment by mattcg** [comment]
On some systems you will need to `chown -R discourse:discourse /opt/bitnami/discoursetmp/cache` after running the precompile command. This is incredibly hacky and really not what I imagine k8s is for... feels like no matter how much fancy stuff you add to the stack we remain stuck in 1996.

> @enibache It seems you are following the documentation for Bitnami cloud images and installers. In the case of containers, the paths differ so you need to run the commands like this:
> 
> ```
> $ cd /opt/bitnami/discourse
> $ RAILS_ENV=production bundle exec rake plugin:install repo=PLUGIN_REPO_URL
> $ RAILS_ENV=production bundle exec rake assets:precompile
> ```
> 
> Refer to this related issue: [bitnami/bitnami-docker-discourse#28](https://github.com/bitnami/bitnami-docker-discourse/issues/28)

**Comment by echel0n** [comment]
How is it possible to install plugins when using a helm chart, would one do this using a sidecar or init container, and if so how?

Thanks!

**Comment by enibache** [comment]
yes, either of those methods should be possible but afaik bitnami/charts
don't implement neither of those yet at least for bitnami/discourse because
the only provided working solution is  by "kubectl exec" into the running
docker container and manually installing the plugin from a git repository
by running 2 ruby commands:

$ cd /opt/bitnami/discourse
$ RAILS_ENV=production bundle exec rake plugin:install repo=PLUGIN_REPO_URL
$ RAILS_ENV=production bundle exec rake assets:precompile

sorry if this doesn't satisfy your curiosity...

**Comment by andresbono** [comment]
@mattcg, can you give us more details on the operation that you were trying to do that needed the extra `chown` command?

**Comment by mattcg** [comment]
Hey Andres, I was installing the [discourse-openid-connect](https://github.com/discourse/discourse-openid-connect) plugin. I ran the rake precompile from a shell opened via Rancher. That seemed to create the the precompiled assets with permissions too strong for Discourse to use.

**Comment by andresbono** [comment]
@mattcg, another option would be executing the rake commands as `discourse` from start, but in that case, there are different permissions errors:

```console
$ cd /opt/bitnami/discourse
$ gosu discourse bash -c 'RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/discourse/discourse-openid-connect'
$ gosu discourse bash -c 'RAILS_ENV=production bundle exec rake assets:precompile
...
Errno::EACCES: Permission denied @ rb_sysopen - /opt/bitnami/discourse/public/assets/locales/fa_IR-fa50561be50fce3dd6e04aba97ed1f05a997d21ec5d7961107b86736fabfddf5.js.47312813622420.1886.901309
```

So the chown to `tmp/cache` is cleaner than my alternative.

**Comment by mattcg** [comment]
Sure... overall I don't understand what this chart is for. It seems no one is actually using it, because it is nowhere near production ready and Bitnami does not seem to be making any attempt to take it there. Our experience with the Wordpress chart has also also been mind-blowingly awful.

**Comment by echel0n** [comment]
It would make more sense to add the ability to set an array of plugins we wish to have added in via chart values instead of manually having to do this, just my 2 cents on this.

**Comment by enibache** [comment]
Yes, I agree. including the possibility of adding a list of plugins to be
installed via the values.yaml file would be the ideal solution, yet the
bulk of work would still lie in translating this in the logic behind the
scenes(-> code, deployment.yaml, docker image ...). Wondering if the
bitnami "Angels ;-)" are planning to include or already have such a in
backlog. Something similar to the Jenkins helm chart:

  *# List of plugins to be install during Jenkins master start*
*  installPlugins:*
*    - kubernetes:1.25.7*
*    - workflow-job:2.39*
*    ...*
*see:
https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
<https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml>*

**Comment by andresbono** [comment]
Thanks for your suggestion @echel0n, @enibache. We think adding a new parameter in the values.yaml to ease the installation of plugins makes sense so we have just created an internal task to implement that feature and to address the usability problems related to that. We will be updating this thread with any news or updates we have.

In principle it would be something like an init script that is executed during the first initialization of the container and that runs the required commands to install the plugins.

---

@enibache, in a previous message https://github.com/bitnami/charts/issues/4624#issuecomment-742809087 you mention other issues (backup and performance). Would you like to create new issues for those topics? That way we keep this one specifically for the installation of plugins issue.

---

@mattcg we are always willing to keep improving our chart catalog. Please let us know about any other issues that you find in both the discourse or wordpress charts. You can also help with pull requests.

**Comment by echel0n** [comment]
Any further progress or timeline as to when this will be completed?

**Comment by andresbono** [comment]
Hi @echel0n, no progress so far, I'm afraid. The task is still in our backlog and I cannot guarantee an ETA due to different priorities of our engineering team.

**Comment by sbkg0002** [comment]
What would be the correct way to integrate this? Running a init-container?

**Comment by andresbono** [comment]
Hi @sbkg0002, I'm not sure if it would be feasible to do it with an init-container. What was discussed was to implement a script or a function to install the plugins during the first initialization of Discourse.

Here you have an example of other application that does something similar: 

https://github.com/bitnami/bitnami-docker-rabbitmq/blob/bab4bd8a57aaafec7a0be5414d6f043db7451049/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L497-L505

**Comment by opensorceror** [comment]
@enibache For the sake of curiosity, what do you mean exactly by "click performance"? Is this an analytics thing, or a general performance (or lack of it) thing?

**Comment by enibache** [comment]
click performance is reaction time(time taken for site to completely load
after a click)

**Comment by ramonduraes** [comment]
A great idea to use parameters. Waiting for news.

**Comment by echel0n** [comment]
any update on this?

**Comment by marcosbc** [comment]
@echel0n Unfortunately not. However, we recently open-sourced the initialization scripts in the [`rootfs` folder](https://github.com/bitnami/bitnami-docker-discourse/tree/master/2/debian-10/rootfs) of the [`bitnami-docker-discourse` repo](https://github.com/bitnami/bitnami-docker-discourse), which contain the installation scripts for this chart, meaning it would now be possible for you to contribute with any improvements to support installation of plugins, for example, if you would like to.

**Comment by dotnetnate** [comment]
Ditto for the updates on this, but even with following the instructions above w/ running the rake commands via kubectl, while it looks like it "installed" the plugins, they aren't showing up in the dashboard. According to the docs there's a need to run ./launcher rebuild or something like that - can't find any files like that in the container though, so how does one get the plugins to actually take effect when deployed from the helm charts into k8s (AKS)?

**Comment by marcosbc** [comment]
@dotnetnate Could you provide the steps you followed to install the plugin in your chart? Note that it might be required to reload the Discourse service after installation of the plugin, e.g. by recreating the pod.

**Comment by dotnetnate** [comment]
So awkward to be eagerly awaiting a reply, only to realize you left your response sitting in a random notepad instance...


```
cd /opt/bitnami/discourse
RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/discourse/discourse-spoiler-alert.git
RAILS_ENV=production bundle exec rake assets:precompile
```

I did eventually get to running

`kubectl delete pod discourse-757871a2-8f2b-48f1-b8d3-7a2de`

after the deployment and it picked it up. Seems a little awkward to have to incur an outage to install a plugin - not sure if that's a function of discourse's deployment model or what.

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to make it work.
  I am not sure either, I guess it would depend on what it needed for the plugin, I mean, for example if it is something that need to be loaded before the rest of discourse start running.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/discourse#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by 0cwa** [comment]
I've been trying to run a postStart Lifecycle hook to add plugins, but I always get an out of memory response, despite running it on a 6GB node.

```
│   Warning  FailedPostStartHook  13s   kubelet             Exec lifecycle hook ([sh -c cd /opt/bitnami/discourse; for i in discourse-reactions; do RAILS_ENV=production bundle exec │
│  rake plugin:install repo=https://github.com/discourse/$i; done; RAILS_ENV=production bundle exec rake assets:precompile]) for Container "discourse" in Pod "wp-forum-discourse-65 │
│ b65d7fbf-65582_wp-forum(e9ecec72-bbb5-4ad2-80c3-bc0216f8d401)" failed - error: command 'sh -c cd /opt/bitnami/discourse; for i in discourse-reactions; do RAILS_ENV=production bun │
│ dle exec rake plugin:install repo=https://github.com/discourse/$i; done; RAILS_ENV=production bundle exec rake assets:precompile' exited with 137: Cloning into '/opt/bitnami/disc │
│ ourse/plugins/discourse-reactions'...                                                                                                                                              │
│ , message: "Cloning into '/opt/bitnami/discourse/plugins/discourse-reactions'...\n"                                                                                                │
│   Normal  Killing  13s                kubelet  FailedPostStartHook
```

It worked once, but it was slow... and haven't been able to replicate it working

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/discourse#community-supported-solution). If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by tetienne** [comment]
@0cwa Did you succeed finally?

**Comment by 0cwa** [comment]
Yeah, all I had to do in the end was shell into it and run the command to install the plugins from there :D

Feb 23, 2023 3:42:01 AM Thibaut ***@***.***>:
