### ISSUE TITLE
bitnami/kafka no possibility to set an arbitrary KAFKA_CFG_MIN_BROKER_ID

### ISSUE THREAD

**Issue by antonmatsiuk** [bitnami/charts#4626]
**Which chart**:
bitnami/kafka

**Is your feature request related to a problem? Please describe.**
In current kafka chart it is not possible to set an arbitrary `KAFKA_CFG_MIN_BROKER_ID` for a stateful set with multiple pods. The `KAFKA_CFG_BROKER_ID` value is hardcoded via `/scripts/setup.sh` to the ID of the pod in the stateful set. This makes impossible to provision a stretched cluster where two separate helm releases form a single kafka cluster, because BROKER_IDs in the stateful set always start from zero. Such stretched clusters are absolutely needed in zero-downtime migration scenarios.
 
**Describe the solution you'd like**
A possibility to set `KAFKA_CFG_MIN_BROKER_ID` variable in the chart. Brokers derive their IDs from the following formula: `KAFKA_CFG_BROKER_ID = KAFKA_CFG_MIN_BROKER_ID + POD_ID`, e.g. if KAFKA_CFG_MIN_BROKER_ID=10, brokers get ID=10,11,12 etc.
If `KAFKA_CFG_MIN_BROKER_ID`variable is set in the chart `setup.sh` script [here](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml) takes it into account while setting `KAFKA_CFG_BROKER_ID`.

**Describe alternatives you've considered**
A current alternative is to deactivate `/scripts/setup.sh` in the chart completely, set `KAFKA_CFG_BROKER_ID` in the chart manually and provision a separate stateful set per broker, what leads to huge management overhead.

**Comment by marcosbc** [comment]
@antonmatsiuk Thanks for the suggestion! Indeed it looks like what you are asking for is not currently supported.

Would you be open to contributing such change? We'd be happy to review the PR and help with the release of the chart with those changes. That way, this could be implemented faster than by conventional means, due to our currently huge backlog.

I guess that something like this could work if you define "minBrokerId" in values.yaml:

```bash
export KAFKA_CFG_BROKER_ID="$((ID + {{ .Values.minBrokerId }}))"
```

**Comment by antonmatsiuk** [comment]
@marcosbc here is the [PR](https://github.com/bitnami/charts/pull/4683), pls review. A similar PR for zookeeper will follow.

**Comment by dani8art** [comment]
Hi @antonmatsiuk thanks for this contribution, please, let's move the conversation there!
