### ISSUE TITLE
Need annotations for PVC minio helm chart

### ISSUE THREAD

**Issue by nvthuong1996** [bitnami/charts#4646]
I can't add annotations for PVC minio from values.
I need some some config to helm can't delete pvc when destroy minio

**Comment by miguelaeh** [comment]
Hi @nvthuong1996 ,
I understand you cannot upgrade the Helm Chart specifying the new annotations, is that right?
The parameter to do that is https://github.com/bitnami/charts/blob/c698500677082a747718e5abbe3ddb07c5c04eea/bitnami/minio/values.yaml#L322. Are you getting any error with it?

**Comment by nvthuong1996** [comment]
please check template. annotations can't setup
https://github.com/bitnami/charts/blob/e726d647527b61ce25dce90f37e4fa451bd1c7d4/bitnami/minio/templates/pvc-standalone.yaml#L4

**Comment by miguelaeh** [comment]
Hi @nvthuong1996 ,
I see, the PVC annotations parameter is not being properly set.
Please check the above PR it should be setting it properly.

**Comment by nvthuong1996** [comment]
I see. Thank you.
