### ISSUE TITLE
[mongodb-sharded] mongodb.conf vs mongod.conf

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#4648]
https://github.com/bitnami/charts/blob/278809cea48028b945a7f2236c197cb9f25544c3/bitnami/mongodb-sharded/templates/shard/shard-data-configmap.yaml#L9

Should it be mongod.conf instead?

**Comment by alemorcuq** [comment]
Hi, @maxisam!

The `bitnami/mongodb-sharded` container is configured to use a `mongodb.conf` file by default, so that is fine. Why are you asking? Did you find any issues?

**Comment by maxisam** [comment]
Well, in the end, my issue is actually this one https://github.com/bitnami/charts/issues/4523

But I feel like we should use mongod.config anyway since they have changed it for a while.

Anyway this is not really a big deal. : )
