### ISSUE TITLE
[postgresql-ha] postgresql-postgres-password from existingSecret is ignored if postgresql.postgresPassword is not set

### ISSUE THREAD

**Issue by kirschem** [bitnami/charts#4655]
**Expectation:**
I can set the the postgres user's password by setting the key `postgresql-postgres-password` inside a secret referenced by `existingSecret`.

**Reality:**
I also need to specify any value in  postgresql.postgresPassword (default is nil), so that the secret gets referenced inside the envs, see
https://github.com/bitnami/charts/blob/6257aa55ca352a9aecac99cdf8491d4cccfa4102/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L120

**Comment by miguelaeh** [comment]
Hi @kirschem ,
Thank you very much for reporting this. Could you give a try to the above PR?
