### ISSUE TITLE
[kube-prometheus] kube-prometheus-alertmanager: server returned HTTP status 404 Not Found with Istio

### ISSUE THREAD

**Issue by danvy** [bitnami/charts#4661]
**Which chart**:
bitnami/kube-prometheus version 3.3.0

**Describe the bug**
kube-prometheus-alertmanager is returning a 404 error in Prometheus.
It is deployed in a Kubernetes cluter using Istio.
Every other endpoint is working properly.

**To Reproduce**
1. Deploy using helm upgrade kube-prometheus bitnami/kube-prometheus --install --version 3.3.0 --namespace monitoring
2. Goto to Prometheus http://localhost:9090/targets#pool-monitoring/kube-prometheus-alertmanager/0
3. See error : Target is down.
![chrome_vCJtKrITdO](https://user-images.githubusercontent.com/190267/101632906-d0222900-3a26-11eb-99a9-c0af9d68981c.png)

**Expected behavior**
Target should be up.

**Version of Helm and Kubernetes**:
Helm version 3.4.0
Kubernetes version 1.18.10
Istio 1.8

- Output of `helm version`:
*version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
N/A

**Comment by danvy** [comment]
I found this solution:
helm upgrade kube-prometheus bitnami/kube-prometheus --install --version 3.3.0 --namespace monitoring alertmanager.listenLocal=true

**Comment by andresbono** [comment]
Thanks for sharing your way to solve it, @danvy!! Other users will benefit from your comment.
