### ISSUE TITLE
[bitnami/redis] Missing feature to add custom annotations to statefulsets

### ISSUE THREAD

**Issue by langered** [bitnami/charts#4666]
**Which chart**:
[bitnami/redis] version 12.1.3

**Is your feature request related to a problem? Please describe.**
I need to add a custom annotation to the master and slave statefulsets of redis over the `values.yaml` or `values-production.yaml`

**Describe the solution you'd like**
Adding a property to the `values.yaml` named annotation, which will copy the given annotations into the statefulsets:
* master.statefulset.annotations
* slave.statefulset.annotations

**Describe alternatives you've considered**
Since using the `values.yaml` is the preferred way to customise the redis deployment, there is no other convenient way to do so.

**Prepared fix:**
I created a PR with my suggested fix: #4667

**Comment by juan131** [comment]
Thanks for the contribution! I just approved and landed your PR
