### ISSUE TITLE
[bitnami/rabbitmq] Upgrade Strategy?

### ISSUE THREAD

**Issue by mltsy** [bitnami/charts#4668]
**Which chart**:
rabbitmq 8.5.1

**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a documentation problem or a missing feature, but given the variability and complexity involved in [upgrade strategies for rabbitmq](https://www.rabbitmq.com/upgrade.html#basics) I want to be able to specify / confirm the upgrade behavior when I upgrade this chart (i.e. does it perform a full-stop upgrade or a rolling upgrade?  In a rolling upgrade, can I tell it to sync mirrored queues during the upgrade and wait for the sync to finish?  What about waiting for quorum-critical nodes to become non-critical before shutting them down? What other options are there?)

**Describe the solution you'd like**
1. I think there should be a value called something like `upgradeStrategy` with allowed values of `full_stop` or `rolling`.
1. In the case of a full_stop upgrade, the chart should designate an "upgrader" node and make sure that node is the last one stopped and the first one started, as described in [the notes for a full stop upgrade](https://www.rabbitmq.com/upgrade.html#full-stop-upgrades).
1. In the case of a rolling upgrade, the chart should also support the following options:
    - `upgradeOptions.autoSyncMirrors`: true/false.  If true, it should call a sync command on all classic mirrored queues and wait for the sync to complete after restarting each node. (And document that this will make the queues temporarily unavailable) (default: true)
    - `upgradeOptions.waitOnQuorumCritical`: true/false.  If true, the chart should wait until a node is not quorum_critical before shutting it down, as described in [the notes for upgrading quorum queues](https://www.rabbitmq.com/upgrade.html#quorum-queues). (default: true)
1. In either case, the chart should support the following options:
    - `upgradeOptions.rebalanceMaster`: true/false.  If true, the chart should issue a `rabbitmq-upgrade post_upgrade` command to automatically rebalance masters on all mirrored queues [as described in the notes](https://www.rabbitmq.com/upgrade.html#mirrored-queue-masters-rebalance) after the upgrade is complete.

**Describe alternatives you've considered**
The only alternative I've considered is a manual upgrade, after which I'm not sure how to get the chart in sync again... there are probably other ways to organize this functionality, and maybe there's already something built in?  It looks like the chart performs some version of a rolling upgrade by default: https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values-production.yaml#L339

But it's not clear whether this waits for the right things or performs the recommended actions in between each node restart... 

**Additional context**
It's also worth considering whether the automated route is just too risky, and perhaps the upgrade strategy should be changed to `OnDelete` so that the user must perform the steps manually and consciously in between each node being restarted.  However, this would seem to prevent the option of a full-stop upgrade, since the StatefulSet would automatically spin up a new pod as soon as you kill one of the old ones.

**Comment by mltsy** [comment]
It occurs to me that some of these things may not be possible to implement purely in a helm chart 😄  In this case, perhaps just some documentation about how to configure or perform the various kinds of upgrades within the context of the chart would be sufficient!

**Comment by andresbono** [comment]
Hi @mltsy, there are other issues and contributions tightly related to the topic that you are raising. They are covering most of your concerns:

- https://github.com/bitnami/charts/issues/3931
- https://github.com/bitnami/charts/pull/4470
- https://github.com/bitnami/bitnami-docker-rabbitmq/pull/142

I think that you might find them interesting.

**Comment by mltsy** [comment]
Ah!  Indeed - thank you!  Those basically cover everything I mention here except for the options.  I see the rebalance thing is already an option under `clustering.rebalance`.  I still think there may need to be an option to disable waiting for sync in some cases (when the cluster shuts down unexpectedly, not in an ordered fashion)... however I guess if the waiting only occurs ass a pre-stop hook, then the option may not be necessary!  So I'll close this and address that question in the other tickets.  Thanks :)
