### ISSUE TITLE
Unable to template jasperreports with subchart mariadb disabled in version 9.1.0

### ISSUE THREAD

**Issue by ujoergen** [bitnami/charts#4673]
Hi

Trying to setup the jasperreports with an external MariaDB - but getting the following error:

```
Error: template: jasperreports/templates/deployment.yaml:27:25: executing "jasperreports/templates/deployment.yaml" at <include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $)>: error calling include: template: no template "common.affinities.pods" associated with template "gotpl"

Use --debug flag to render out invalid YAML
```

Seems both jasperreports and mariadb charts depend on a common subchart - but that dependency is not explicit for the jasperreports chart - but is satisfied through the mariadb subchart. If the mariadb subchart is disabled then the common templates are not available.

To reproduce set 
```
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  ##
  enabled: false
```
in the values.yaml and try to template the chart. Seems to work in 9.0.0.

**Comment by andresbono** [comment]
Thanks for reporting this issue, @ujoergen. We have submitted #4680 to fix the problem.
