### ISSUE TITLE
[mongodb-sharded] unable to build kubernetes objects from release manifest

### ISSUE THREAD

**Issue by alrf** [bitnami/charts#4684]
**Which chart**:
mongodb-sharded (3.1.0)

**Describe the bug**
In case of `initScriptsSecret` using, the chart deployment fails with:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.volumes[2].secret): unknown field "name" in io.k8s.api.core.v1.SecretVolumeSource
```

Caused by `name` in templates, e.g.: https://github.com/bitnami/charts/blob/061390f825386f546e384126fdf6509816cef7f4/bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml#L323

**Expected behavior**
Chart is deployed.

**Comment by andresbono** [comment]
Thanks for reporting and fixing this issue, @alrf!!
