### ISSUE TITLE
[bitnami/eventrouter] move eventrouter from helm/stable to bitnami

### ISSUE THREAD

**Issue by Timvissers** [bitnami/charts#4696]
**Which chart**:
A new one to be moved to bitnami: eventrouter. See https://github.com/helm/charts/tree/master/stable/eventrouter

**Is your feature request related to a problem? Please describe.**
Yes, helm/stable deprecation, see https://github.com/heptiolabs/eventrouter/issues/121

**Describe the solution you'd like**
Bitnami to provide a new home for the eventrouter helm chart

PR: https://github.com/bitnami/charts/pull/4698

**Comment by juan131** [comment]
Hi @Timvissers 

Thanks so much for opening this issue! I added some general comments about the procedure to follow to incorporate the new chart at https://github.com/bitnami/charts/pull/4698
