### ISSUE TITLE
[bitnami/rabbitmq] Sometimes does not accept admin password

### ISSUE THREAD

**Issue by glothriel** [bitnami/charts#4710]
**Which chart**:
RabbitMQ

**Describe the bug**
I run nightly builds of my whole platform, which includes Bitnami's RabbitMQ helm chart. ~5-10% of builds fail because of RabbitMQ not accepting admin credentials that have been set in the helm chart's values. The only common denominator of all the failed builds I managed to notice, is fact, that the pod gets restarted once in the meantime, I'm not sure if it's caused by Liveness probe, bu it looks like so. The (1 node) cluster is starting up around 10 minutes, which is suspiciously slow. 
The test environment has very slow disk performance, which may be related, especially iops (ceph).

**To Reproduce**

1. Deploy the helm chart on environment with low disk performance

**Expected behavior**

The cluster eventually starts, but does not accept the admin password, that was set in the helm chart values.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Cluster is 1.19.3 on KIND
```

**Additional context**

I have pod's logs/describe/yaml, but I'm not sure if the pod doesn't get recreated in the meantime and the logs of the failed one are lost.

[describe-devenv-rabbitmq-0.txt](https://github.com/bitnami/charts/files/5683278/describe-devenv-rabbitmq-0.txt)
[logs-devenv-rabbitmq-0.log](https://github.com/bitnami/charts/files/5683279/logs-devenv-rabbitmq-0.log)
[yaml-devenv-rabbitmq-0.txt](https://github.com/bitnami/charts/files/5683280/yaml-devenv-rabbitmq-0.txt)

**Comment by Cirrith** [comment]
I was also getting this when deploying the chart into Docker Desktop Kubernetes. I was able to reliably reproduce (5/5) the error until resetting the cluster.

```bash
$ helm install rabbitmq bitnami/rabbitmq
```

```bash
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Hi, @Cirrith.

Can you provide the logs of the previous instance of the container? I want to see if RabbitMQ is correctly deployed before it is restarted. You can get them passing the `-p` flag to `kubectl logs`.

On the other hand, can you try disabling the liveness and readiness probes? It may be possible that the pod is being restarted before being ready, as you say your node has a very low disk performance.

**Comment by Cirrith** [comment]
@alemorcuq I believe so. As I said, I deployment the chart into a cluster running on my laptop and was unable to access the running instance with the created password both through the management portal and Python pika module. Looking through the logs it said something along the lines of `bad credentials for 'user'`.

I'm not experiencing this anymore, but I figured I'd add another data point to this issue.

**Comment by alemorcuq** [comment]
Oh, I see. Thanks, @Cirrith. From the top of my head, that could be due to a bad initialization or to the existence of some persisted data from a previous deployment with a different passwords. If you experience it again it would be great if you could post some logs and information about it.

**Comment by Cirrith** [comment]
@alemorcuq Got the error again locally, in hindsight it should have obvious, looks like when I uninstalled the helm chart it left the PVs around so when I redeployed it the old password was still present in the file system. I don't know if this is the same problem or even an issue.

**Comment by alemorcuq** [comment]
I think you are right and that is why you got the error. Everything is fine after deleting the PVs, right?

**Comment by Cirrith** [comment]
Yes, after deleting the PV everything deploys fine.

**Comment by glothriel** [comment]
Hi @alemorcuq 

Here is the log of the original container: https://gist.github.com/glothriel/cdec7c564d8baec781ab9e6fd2d77d07

**Comment by glothriel** [comment]
The most relevant part seems to be: 
```
BOOT FAILED
===========
Exception during startup:

    rabbit:start/2 line 857
    rabbit_boot_steps:run_boot_steps/1 line 20
    rabbit_boot_steps:'-run_boot_steps/1-lc$^0/1-0-'/1 line 19
    rabbit_boot_steps:run_step/2 line 46
    rabbit_boot_steps:'-run_step/2-lc$^0/1-0-'/2 line 41
    rabbit_mnesia:init/0 line 76
    rabbit_mnesia:init_with_lock/3 line 111
    rabbit_mnesia:run_peer_discovery_with_retries/2 line 138
error:{badmatch,ok}
```

**Comment by alemorcuq** [comment]
Have you tried disabling the probes in case they are killing the pod before it is able to properly start?

**Comment by RefusesNames** [comment]
I have the same (or similar?) issue. In my case before the image is pulled, a rescale is triggered (which slows the startup similar to the slow disk in this issue). After the container has started, I am unable to authenticate via
```
rabbitmqctl authenticate_user [my username] [my password]
```
This also affects the management UI. If I kill or delete the pod, the restarted version will have the credentials loaded properly. I created a liveness probe to check if this restart can be automated, but after a restart from the liveness probe, my credentials still don't work.

Some details worth noting:

- Persistence is disabled, so it should not be an issue of an old PV getting attached (also the credentials did not change for months).
- The environment variables in my pod containing the credentials (`RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD`) that are used by the docker image, are set and contain the correct values. For some reason they are not used by the docker image.

**Comment by RefusesNames** [comment]
I also tried disabling the probes according to @alemorcuq 's comment. Nothing changed: credentials don't work, I delete the pod to restart it and they start working.

**Comment by alemorcuq** [comment]
I'm not sure what you mean with "before the image is pulled, a rescale is triggered", could you specify?

**Comment by RefusesNames** [comment]
These are the events that I got from `describe` during startup:
```
Events:
   Type     Reason            Age        From                       Message
   ----     ------            ----       ----                       ------- 
   Warning  FailedScheduling  <unknown>  default-scheduler          0/9 nodes are available: 9 Insufficient memory.     
   Warning  FailedScheduling  <unknown>  default-scheduler          0/9 nodes are available: 9 Insufficient memory.     
   Warning  FailedScheduling  <unknown>  default-scheduler          0/11 nodes are available: 2 node(s) had taints that the pod didn't tolerate, 9 Insufficient memory.
   Warning  FailedScheduling  <unknown>  default-scheduler          0/11 nodes are available: 2 node(s) had taints that the pod didn't tolerate, 9 Insufficient memory.
   Normal   Scheduled         <unknown>  default-scheduler          Successfully assigned release-name/rabbitmq-0 to aks-memorypool-x
   Normal   TriggeredScaleUp  3m22s      cluster-autoscaler         pod triggered scale-up: [{aks-memorypool-x 3->4 (max: 10)}] 
   Normal   TriggeredScaleUp  3m12s      cluster-autoscaler         pod triggered scale-up: [{aks-memorypool-x 4->5 (max: 10)}]
   Normal   Pulling           55s        kubelet, aks-memorypool-x  Pulling image "docker.io/bitnami/rabbitmq:3.8.9-debian-10-r0" 
   Normal   Pulled            29s        kubelet, aks-memorypool-x  Successfully pulled image "docker.io/bitnami/rabbitmq:3.8.9-debian-10-r0"
   Normal   Created           24s        kubelet, aks-memorypool-x  Created container rabbitmq
   Normal   Started           24s        kubelet, aks-memorypool-x  Started container rabbitmq
   Warning  Unhealthy         7s         kubelet, aks-memorypool-x  Readiness probe failed: Error: unable to perform an operation on node 'rabbit@rabbitmq-0.rabbitmq-headless.release-name.svc.cluster.local'. Please see diagnostics information and suggestions below.

**Comment by alemorcuq** [comment]
I don't think that cluster autoscaling thing has anything to do with the issue. Could you share the exact command and values file you are using so I can try to reproduce the issue myself?

**Comment by RefusesNames** [comment]
Neither do I think that the autoscaling on it's own is at fault. I just see the parallel to the original issue about since in both cases the startup seems to take very long.

I would love to provide a command to reproduce this issue, but so far I have failed to reproduce it outside of our development setup which I am unable to share. Do you maybe have any hints/thoughts on where I can look to find out, why credentials are not set in the container? This might also be an issue with the docker image, as the required environment variables are being set, but they are not used properly. Is there maybe some trigger that needs to happen?

**Comment by alemorcuq** [comment]
You can find the initialization logic in the images' repository: https://github.com/bitnami/bitnami-docker-rabbitmq/blob/05f7e9fa05158f8238ace3e864528c238fc4ebfd/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L661

It's very weird that this is only happening in your environment, I don't know what could be causing the issue.

**Comment by tsterker** [comment]
@alemorcuq I have now taken over the sporadic investigation of the problem that @RefusesNames describes.

Unfortunately, so far I did not get around reproducing the issue and e.g. **compare the logs of a successful deployment with a failing one** and cross-reference this with the [initialization logic you linked to](https://github.com/bitnami/charts/issues/4710#issuecomment-763800143), e.g.

![image](https://user-images.githubusercontent.com/1156230/108568650-c06a6f00-730a-11eb-8cf7-50dc53c3ba4e.png)


## But...
 I noticed this [2021-02-08 release note from Azure](https://github.com/Azure/AKS/releases/tag/2021-02-08), where our cluster is running on:

> The AKS default storage class behavior now will be to **delay the creation of a Persistent Volume** until a pod is created.

Because this addresses a **timing issue during pod creation** and this is what we suspected as the potential culprit, I just went ahead and triggered multiple deployments, which triggered a **nodepool scale-up**. This previously seemed to be always part of a failed rabbitmq install, but I **did not run into issues this time**.

This is a **complete shot in the dark**, but I thought it is worth mentioning seeing that [others](https://github.com/bitnami/charts/issues/4541) are having similar issues without a clear indication why.

**Comment by alemorcuq** [comment]
Thanks for the information, @tsterker! Let's hope the issues are solved with that update. Please, keep us updated.

**Comment by glothriel** [comment]
As for my problem, we dramatically increased `initialDelaySeconds` and the issue for now seems to be gone, we ran the tests ~200 times in the last weeks and it did not reappear.

**Comment by alemorcuq** [comment]
This indeed looks to be an issue of the liveness probe restarting the pod before it has completed initialization and leaving it in an incorrect state.
