### ISSUE TITLE
[bitnami/nats] Invalid list when using Values.extraFlags

### ISSUE THREAD

**Issue by sanderma** [bitnami/charts#4712]
When you try to use extraFlags the resulting statefulset is invalid. There is a missing `-` in front of the line.

It should be:
```
{{- range $key, $value := .Values.extraFlags }}
- --{{ $key }}{{ if $value }}={{ $value }}{{ end }}
{{- end }}
```

https://github.com/bitnami/charts/blob/c769471995517bd2e352537c4cd986fb18a7e01c/bitnami/nats/templates/statefulset.yaml#L81

If it's helpful, I can create a PR with the change.

Best regards,
Sander

**Comment by FraPazGal** [comment]
Hi @sanderma,

You are right, there is a missing hyphen there and also on `deployment.yaml` A PR would be appreciated, thanks for catching this!
