### ISSUE TITLE
Does redis or redis-cluster support Istio?

### ISSUE THREAD

**Issue by drmy** [bitnami/charts#4713]
**Which chart**:

bitnami/redis
bitnami/redis-cluster

**Describe the bug**

Hi,
I tested to enable Istio for my bitnami/redis (Sentinel mode) and another redis-cluster, both failed on issue of communication between master and slaves.

I searched Internet and got the Istio official post as below:
**[https://istio.io/latest/faq/applications/#redis](url)**

I got three other posts more about this topic:

**[istio-redis-culster](https://github.com/zhaohuabing/istio-redis-culster)**
[deploying-redis-cluster](https://rancher.com/blog/2019/deploying-redis-cluster)
[migrating-to-redis-cluster-using-envoy-93a87ae79dc3](https://medium.com/@fr33m0nk/migrating-to-redis-cluster-using-envoy-93a87ae79dc3)
[Implement REPLACE operation for EnvoyFilter patch](https://github.com/istio/istio/pull/27426/)

**I also saw another post saying we might need to enable hostNetwork for the Redis nodes to share the host network IP and port.**

Do we have a document or guide on how to setup the bitnami/redis with Sentinel or redis-cluster to be able to run in Istio?

**Comment by javsalgar** [comment]
Hi,

Thanks for using Bitnami! Could you let us know which error appeared when enabling Istio? In principle, there shouldn't be any issue when enabling Istio.

**Comment by drmy** [comment]
> Hi,
> 
> Thanks for using Bitnami! Could you let us know which error appeared when enabling Istio? In principle, there shouldn't be any issue when enabling Istio.

Hi @javsalgar ,

I am using the redis-cluster (6 nodes) with disabled TLS and it is running in a Istio 1.8.1 environment.

The problem is that when my client app (written by StackExchange.Redis in .Net Core) connects to the Redis cluster, it can connect but is followed up with the following log errors, while Redis log is clear. 

I am thinking if we have to do some thing mentioned in the pages below manually?
**[istio-redis-culster](https://github.com/zhaohuabing/istio-redis-culster)**
The Istio 1.8.1 does have included the PR mentioned above.
OR:
**[istio applications faq - redis](https://istio.io/latest/faq/applications/#redis)**

My client app errors:
2020-12-14 15:31:42.9326|INFO|IConnectionMultiplexer|Redis Client is trying to connect with TLS = False, Available Hosts : Unspecified/redis-cluster:6379
2020-12-14 15:31:43.1558|INFO|IConnectionMultiplexer|Redis successfully connected.
2020-12-14 15:31:43.2643|WARN|IConnectionMultiplexer|Redis error message received. endpoint : Unspecified/redis-cluster:6379, message : CLUSTERDOWN Hash slot not served
2020-12-14 15:31:43.2907|ERROR|Program|Error occurred when starting application|StackExchange.Redis.RedisServerException: CLUSTERDOWN Hash slot not served

**Comment by javsalgar** [comment]
Hi,

Checking the documentation, I saw this

https://istio.io/latest/faq/applications/#redis

```
echo "" >> /opt/bitnami/redis/etc/replica.conf
echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/etc/replica.conf
```

You could set this value:

```
slave:
  extraEnvVars:
  - name: "POD_IP"
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
   preExecCmds:  | 
     echo "" >> /opt/bitnami/redis/etc/replica.conf
     echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/etc/replica.conf
```

Could you check if it works for you?

**Comment by drmy** [comment]
> Hi,
> 
> Checking the documentation, I saw this
> 
> https://istio.io/latest/faq/applications/#redis
> 
> ```
> echo "" >> /opt/bitnami/redis/etc/replica.conf
> echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/etc/replica.conf
> ```
> 
> You could set this value:
> 
> ```
> slave:
>   extraEnvVars:
>   - name: "POD_IP"
>     valueFrom:
>       fieldRef:
>         fieldPath: status.podIP
>    preExecCmds:  | 
>      echo "" >> /opt/bitnami/redis/etc/replica.conf
>      echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/etc/replica.conf
> ```
> 
> Could you check if it works for you?

Hi @javsalgar,
Thank you for the help. 

As you suggested I set the value in my redis-cluster StatefulSet, it indeed created the env variable POD_IP with correct value. 
However I see those errors as below:

**2020-12-15 13:00:38.1076|WARN|IConnectionMultiplexer|Redis error message received. endpoint : Unspecified/redis-cluster:6379, message : CLUSTERDOWN Hash slot not served**

**Comment by javsalgar** [comment]
Hi,

I see. So, just to confirm and create enough information for the investigation ticket. With the values I mentioned it works without issues without Istio, right?

**Comment by drmy** [comment]
> Hi,
> 
> I see. So, just to confirm and create enough information for the investigation ticket. With the values I mentioned it works without issues without Istio, right?

Hi @javsalgar ,

That is correct. The values you mentioned can work correctly to create the POD_IP env with correct ip address.

My Redis is running in a namespace. 
1) If I enable the Istio auto-injection by set label istio-injection=enabled to the namespace, then the Redis will run with a istio side-car and get this problem -- as I described in last post - redis-cluser and redis sentinel got different errors.
2) If I remove the istio-injection label from the namespace then my Redis is running well and can accept clients' connection.

Both test cases are with the values of POP_IP.

Thank you very much for helping me to look into this issue, @javsalgar .
Really appreciated.

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about the clients you are using to connect? Could it be that you forced istio mtls and it won't work from clients without it?

**Comment by drmy** [comment]
> Hi,
> 
> Could you provide more details about the clients you are using to connect? Could it be that you forced istio mtls and it won't work from clients without it?

My redis is configured to use the following peer authentication with port 6379 on PERMISSIVE mode. And I disabled the Redis tls.authClients.
My client is written by the Stackexchange.redis lib.

kind: PeerAuthentication
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ template "common.names.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  mtls:
    mode: STRICT
  portLevelMtls:
    '6379':
      mode: PERMISSIVE
    '9121':
      mode: PERMISSIVE

**Comment by javsalgar** [comment]
Hi,

If you remove the PeerAuthentication object, does it work even if it has the istio sidecar?

**Comment by drmy** [comment]
> Hi,
> 
> If you remove the PeerAuthentication object, does it work even if it has the istio sidecar?

Hi @javsalgar ,
Thanks for asking.
I tried to not apply the PeerAuthentication object, it still didn't work.

I am thinking that this may not be an issue of Redis supporting Istio, it could be an issue with Istio for supporting Redis.
Because I saw some posts said that Istio doesn't work well with supporting headless-service, StatefulSet on Redis, RabbitMQ, etc. when mTLS is enabled. (I tried to set mTLS=DISABLE and it also failed.) 

So far, below is the only article I read, which states that his customized redis-cluster can work with Istio:
https://github.com/zhaohuabing/istio-redis-culster

Using the bitnami helm chart of redis sentinel or redis-cluster, I haven't made it work yet.
If anyone can confirm this is an issue with Istio or Redis charts, It would be much appreciated.
Thank you.

**Comment by dani8art** [comment]
Hi I was doing some researches and it seems there could be some missing istio requirements that affect the service port name. Currently, we have it like

```yaml
  ports:
    - name: redis
      port: {{ .Values.redisPort }}
      targetPort: redis
  {{- if .Values.sentinel.enabled }}
    - name: redis-sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: redis-sentinel
  {{- end }}
```

But it seems that it should be prefixed by the protocol like `http-redis` and `tcp-redis-sentinel` regarding this PR: https://github.com/bitnami/charts/pull/2286/files

Do you think it could work?

**Comment by drmy** [comment]
> Hi I was doing some researches and it seems there could be some missing istio requirements that affect the service port name. Currently, we have it like
> 
> ```yaml
>   ports:
>     - name: redis
>       port: {{ .Values.redisPort }}
>       targetPort: redis
>   {{- if .Values.sentinel.enabled }}
>     - name: redis-sentinel
>       port: {{ .Values.sentinel.port }}
>       targetPort: redis-sentinel
>   {{- end }}
> ```
> 
> But it seems that it should be prefixed by the protocol like `http-redis` and `tcp-redis-sentinel` regarding this PR: https://github.com/bitnami/charts/pull/2286/files
> 
> Do you think it could work?

Hi @dani8art ,

Thank you for the info. I havn't got a chance to test with the PR changes but I remembered that I ever made a similar try of code changes to the charts before -- rename the port name from "redis" to "tcp-redis" -- I wished Istio to select TCP protol for redis rather than the "redis protocol" that is supposed to be used only in the redis-cluster mode? I am not sure but my that test was still failed. Looking at the following Istio page, the official states that the "redis" protocol is disabled by default, and if the port name doesn't match those explicit supported protocols by Istio then TCP protocol will be selected by default, therefore I am not sure if changing the port name in the Redis chart would actually make any difference for my issue.

https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection

**Comment by dani8art** [comment]
Could you try to give a try to these changes, please? if no, we can evaluate the differences between our chart and the manifest you shared.

> So far, below is the only article I read, which states that his customized redis-cluster can work with Istio:
https://github.com/zhaohuabing/istio-redis-culster

Thanks!

**Comment by drmy** [comment]
> Could you try to give a try to these changes, please? if no, we can evaluate the differences between our chart and the manifest you shared.
> 
> > So far, below is the only article I read, which states that his customized redis-cluster can work with Istio:
> > https://github.com/zhaohuabing/istio-redis-culster
> 
> Thanks!

Absolutely, that is what I am going to try. I will let you know my test result.
Thank you @dani8art .

**Comment by dani8art** [comment]
Hi @drmy did you have a chance to work on this?

**Comment by MichaelHudgins** [comment]
@dani8art  I ran into a very similar issue requiring much of what was discussed here.  I have outlined what I needed to do here: https://github.com/bitnami/charts/issues/5016

**Comment by javsalgar** [comment]
Thank you for the information!

**Comment by drmy** [comment]
> Hi @drmy did you have a chance to work on this?

Hi @dani8art ,
I applogize for the late since busying in my work recently. I was trying to test that solution however I didn't succeed yet by following those instructions. I many need more time to research on that, will keep you updated once I get something new.

**Comment by javsalgar** [comment]
Thank you! Please update the ticket with you findings

**Comment by miguelaeh** [comment]
Hi guys!
We have fixed the issue with Redis Cluster and Istio. You can check this PR https://github.com/bitnami/charts/pull/5158
Please let us know if you find any issue with the new changes.
Regards.

**Comment by drmy** [comment]
> Hi guys!
> We have fixed the issue with Redis Cluster and Istio. You can check this PR #5158
> Please let us know if you find any issue with the new changes.
> Regards.

Thank you @migmartri ,
Found this PR has been released to redis-cluster-4.2.7, I will test it.

**Comment by drmy** [comment]
> Hi guys!
> We have fixed the issue with Redis Cluster and Istio. You can check this PR #5158
> Please let us know if you find any issue with the new changes.
> Regards.

Hi @miguelaeh ,

Thank you for changes, I just had a quick test and found that it is now working better undser some conditions:

1, disable redis.tls and disable cluster.externalAccess -- tested passed, all clients can connect to the istio-enabled redis-cluster
2. once I enable redis.tls or cluster.externalAccess -- tested failed, I got CLUSTERDOWN Hash slot not served.

**Comment by miguelaeh** [comment]
Hi @drmy ,
Thank you for testing the changes.
I have tried to reproduce your issue but with no luck. Y deployed it using externalAccess and Istio. The cluster creation job shows the following in the logs: 
```
...
   replicates 779f1c24ccd908fcc6b6d325e2c9f636eab96bed
M: 779f1c24ccd908fcc6b6d325e2c9f636eab96bed 40.76.164.52:6379
   slots:[5461-10922] (5462 slots) master
   1 additional replica(s)
S: fe73a98ca2cf18e7c1ba166445b03fc364c792e0 40.76.163.143:6379
   slots: (0 slots) slave
   replicates e144f56a62a7a2959257691f20d083768f3001a6
S: ea080b98d26beea48da52eaf36fd03faff6b1422 40.76.165.131:6379
   slots: (0 slots) slave
   replicates bbbebd9c0c074f9f01dfb196f2e28813378c8225
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
Cluster correctly created
```

As you can see it shows the cluster was created. To double check it I executed inside the pod the cluster nodes command:
```
11:15:36 › k exec -it redis-redis-cluster-4 bash
I have no name!@redis-redis-cluster-4:/$ redis-cli cluster nodes
ea080b98d26beea48da52eaf36fd03faff6b1422 40.76.165.131:6379@16379 slave bbbebd9c0c074f9f01dfb196f2e28813378c8225 0 1611659755000 3 connected
779f1c24ccd908fcc6b6d325e2c9f636eab96bed 40.76.164.52:6379@16379 master - 0 1611659756704 2 connected 5461-10922
e144f56a62a7a2959257691f20d083768f3001a6 40.76.164.116:6379@16379 master - 0 1611659755701 1 connected 0-5460
fe73a98ca2cf18e7c1ba166445b03fc364c792e0 40.76.163.143:6379@16379 myself,slave e144f56a62a7a2959257691f20d083768f3001a6 0 1611659752000 1 connected
bbbebd9c0c074f9f01dfb196f2e28813378c8225 40.76.166.69:6379@16379 master - 0 1611659754000 3 connected 10923-16383
4178b77dbf56b9c786583e5e3e6cb5c26a718854 40.76.162.11:6379@16379 slave 779f1c24ccd908fcc6b6d325e2c9f636eab96bed 0 1611659754698 2 connected
```

And it reported back all the nodes. Could you share the output for the cluster creation job in your case please?

**Comment by drmy** [comment]
Hi @miguelaeh ,
Thank you for the info. I am recreating my lab, will retest and gather the logs.

**Comment by miguelaeh** [comment]
Thank you @drmy , let us know whatever you find.
Regards.

**Comment by drmy** [comment]
> Thank you @drmy , let us know whatever you find.
> Regards.

Hi @miguelaeh ,

I am sorry for late response because I was busy in my work recently.
I just retested this and still got some failures. Please find my test results as below.
Appreciate if you can take a look at and provide some suggestions. Thank you!


1) Case 1 -- SUCCEEDED: enable Istio, disable TLS, disable externalAccess
2) Case 2 -- SUCCEEDED: disable Istio, enable TLS, enable externalAccess
------------------------------------------------------------------------------------------------------
3) Case 3 -- FAILED: enable Istio, enable TLS, disable externalAccess
the initJob logged message: Could not connect to Redis at mynet-redis-cluster-0.mynet-redis-cluster-headless:6379: **SSL_connect failed: Connection reset by peer**

4) Case 4 -- FAILED: enable Istio, enable TLS, enable externalAccess
the initJob logged message: Could not connect to Redis at 10.222.42.33:6379: **SSL_connect failed: Connection reset by peer**

5) Case 5 -- FAILED: enable Istio, disable TLS, enable externalAccess
the initJob failed to complete the cluster creation with the following messages:
 
 
Subscribe to project updates by watching  
Submit issues and feature requests at  
 
 ==> ** Starting Redis setup ** 
 ==> Initializing Redis 
 ==> Setting Redis config file 
 ==> ** Redis setup finished! ** 
 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.33:6379: Connection refused 
Node 10.222.42.33 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.35:6379: Connection refused 
Node 10.222.42.35 not ready, waiting for all the nodes to be ready... 
Could not connect to Redis at 10.222.42.35:6379: Connection refused 
Node 10.222.42.35 not ready, waiting for all the nodes to be ready... 
Waiting 0s before querying node ip addresses 
>>> Performing hash slots allocation on 9 nodes... 
Master[0] -> Slots 0 - 5460 
Master[1] -> Slots 5461 - 10922 
Master[2] -> Slots 10923 - 16383 
Adding replica 10.222.42.37:6379 to 10.222.42.33:6379 
Adding replica 10.222.42.38:6379 to 10.222.42.33:6379 
Adding replica 10.222.42.39:6379 to 10.222.42.34:6379 
Adding replica 10.222.42.43:6379 to 10.222.42.34:6379 
Adding replica 10.222.42.44:6379 to 10.222.42.35:6379 
Adding replica 10.222.42.36:6379 to 10.222.42.35:6379 
M: 87e1053b5d36c81de7097f8ad86600ce665d29f2 10.222.42.33:6379 
   slots:[0-5460] (5461 slots) master 
M: 36a3e21ec0add365114befd31272ac186effcb6e 10.222.42.34:6379 
   slots:[5461-10922] (5462 slots) master 
M: 9d260578786238183670b24aa94794188726f9fa 10.222.42.35:6379 
   slots:[10923-16383] (5461 slots) master 
S: e4d0ae7a6028ebcb6401485bdc18dc52e22d5412 10.222.42.36:6379 
   replicates 9d260578786238183670b24aa94794188726f9fa 
S: 7c23830316dd4180f6076b44f73cf453399d7d85 10.222.42.37:6379 
   replicates 87e1053b5d36c81de7097f8ad86600ce665d29f2 
S: 32f52716a3bb97126ca01047d21ef5094e1aef27 10.222.42.38:6379 
   replicates 87e1053b5d36c81de7097f8ad86600ce665d29f2 
S: 4999424249843afa56a0fdbf46a711acd518295a 10.222.42.39:6379 
   replicates 36a3e21ec0add365114befd31272ac186effcb6e 
S: 5f49a6b609ffe1ed9a2638d122a2342e2b7e7de1 10.222.42.43:6379 
   replicates 36a3e21ec0add365114befd31272ac186effcb6e 
S: 0c02b0b15e5acf730ee156e41e44f285d782b15b 10.222.42.44:6379 
   replicates 9d260578786238183670b24aa94794188726f9fa 
**>>> Nodes configuration updated 
>>> Assign a different config epoch to each node 
>>> Sending CLUSTER MEET messages to join the cluster 
Waiting for the cluster to join**

**Comment by miguelaeh** [comment]
Hi @drmy ,
Thank you very much for sharing the use cases, I will re open a task to chek those scenarios you shared.

**Comment by KeithTt** [comment]
It is strange that Istio is enabled by default now? 

I deploy a sentinel arch, I even do not find any `istio` word in the chart files.

How to disable istio?

**Comment by ricosega** [comment]
This issue still happens in version 15.6.10 of the Redis chart.
Do you have an update of what we have to do to make it work with Istio?

In my case am getting this messages when deployed in Sentinel mode:

```
1:S 07 Jan 2022 13:43:09.965 * Connecting to MASTER :0
1:S 15 Jan 2022 13:43:09.965 # Unable to connect to MASTER: Invalid argument
```
