### ISSUE TITLE
[bitnami/external-dns] Update deprecated "apiextensions.k8s.io/v1beta1" in CRD

### ISSUE THREAD

**Issue by ramrodo** [bitnami/charts#4723]
**Which chart**:
bitnami/external-dns

**Is your feature request related to a problem? Please describe.**
As described in the Kubernetes [v1.19 release notes](https://v1-19.docs.kubernetes.io/docs/setup/release/notes/#deprecation-4), `apiextensions.k8s.io/v1beta1` is deprecated in favor of `apiextensions.k8s.io/v1` and unavailable from k8s `1.22+`

We use that API version in the [CRD template](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/crd.yaml#L2) in `external-dns`.

**Describe the solution you'd like**
We can update the CRD definition and API version to the new `v1`

**Describe alternatives you've considered**
We can have both CRDs definitions to support both k8s versions `< 1.19` and `1.19+`

**Additional context**
For more information about this deprecation see [kubernetes#82022](https://github.com/kubernetes/kubernetes/issues/82022)

**Comment by FraPazGal** [comment]
Hello @ramrodo,

Thanks for bringing this up! It is true that `apiextensions.k8s.io/v1beta1` have been deprecated but it seems that [upstream](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/contributing/crd-source/crd-manifest.yaml) is still using that version. Given that `v1beta1` is still valid, I would think that we should hold of until upstream adopts the new `apiVersion`. What do you think?

Nevertheless, it is true that we will need an action plan to move from `v1beta1` before k8s `1.22`, thanks for the heads up!

**Comment by ramrodo** [comment]
Sounds good. Let's wait until the upstream upgrade.

Thanks for sharing the upstream repo, I'll keep an eye there too.

**Comment by pinkfloydx33** [comment]
Upstream was updated [in March](https://github.com/kubernetes-sigs/external-dns/commit/544d245464bfda2d61b986c4e9a5cb8bca0e2056#diff-88876bb9cc0374fa8b8a12782200c4da97d81a4bb27d4afa0f682be43c0fddce). Any chance this can be fixed on this end now?

@ramrodo @FraPazGal
