### ISSUE TITLE
[bitnami/rabbitmq] Question - probes misconfigured ? 

### ISSUE THREAD

**Issue by jBouyoud** [bitnami/charts#4731]
**Which chart**:
Chart: rabbitmq bitnami v8.5.2
Image tag: 3.8.9-debian-10-r37

**Describe the bug**

I'm have some doubt about this default configuration. 

Does it voluntary or must be inverted ? 

Since `ping` seems doesn't check if the rabbitmq process can answer clients. 
[RabbitMQ Doc](https://www.rabbitmq.com/monitoring.html#health-checks) says for `ping` : 
> a very basic check that will succeed for the nodes that are currently waiting for a peer to sync schema from

But `check_running` seems to do this.
> will exit with an error for the nodes that are currently waiting for a peer to sync schema tables from

> rabbitmq-diagnostics check_running is a check that makes sure that the runtime is running and the RabbitMQ application on it is not stopped or paused.`

If it's voluntary could you explain me for which reasons we need to keep it as it.

**To Reproduce**

1. `helm install my-release bitnami/rabbitmq`

**Probable behavior**

* `rabbitmq-diagnostics -q ping` for liveness probe
* `rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms` for readiness probe

Based on [rabbitmq checks descriptions](https://www.rabbitmq.com/monitoring.html#readiness-probes)

It could be also nice to offer to your charts users the availability to define a startupProbe (with the same mechanism of `customReadinessProbe`). For now, there is also a workaround, by using the `sidecars` property to inject the `startupProbe` with the right indentation.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
 I'll be glad to create a PR on this issue if you confirm the misconfiguration and add support of startupProbe.

**Comment by miguelaeh** [comment]
Hi @jBouyoud ,
Thank you for bringing this up.
I have been checking the chart and it seems we are setting them in a reverse way. We set `liveness` using `check_running` and `readiness` using `ping`. I think they should be in the reverse order. i.e. Liveness: ping and readiness:`check_running`.

> It could be also nice to offer to your charts users the availability to define a startupProbe (with the same mechanism of customReadinessProbe). For now, there is also a workaround, by using the sidecars property to inject the startupProbe with the right indentation.

About this, it is actually supported. See https://github.com/bitnami/charts/blob/042c1c4fc81d49c2a8d97a0a9f3bf362c048e107/bitnami/rabbitmq/values.yaml#L451

**Comment by jBouyoud** [comment]
Ok great. I think this too. 
I'll open a PR on that subject.

**Comment by miguelaeh** [comment]
Thank you very much!
