### ISSUE TITLE
[bitnami/nginx-ingress-controller] Enabling namespace scoping makes application unable to look at Kubernetes resources outside of its namespace

### ISSUE THREAD

**Issue by kristinnardal2** [bitnami/charts#4732]
**Which chart**:
bitnami/nginx-ingress-controller, all versions

**Describe the bug**
Using the scope fields in the `values.yaml` file disables the cluster role binding and cluster role from being created. This means that the ingress controller only has access to resources in its own namespace. If we also want to deploy the ingress controller in a different namespace than the ingresses we want to use are in the Helm chart stops working.

```yaml
scope:
  enabled: true
  namespace: "ingress-namespace"
```

The pods never become ready and they start crash-looping.

**To Reproduce**
Steps to reproduce the behaviour:

1. Install the chart with `scope.enabled=true` and `scope.namespace` equal to a different namespace than the one its being installed in.
  ```
  helm install ingressctl bitnami/nginx-ingress-controller --set scope.enabled=true --set scope.namespace=ingress-namespace
  ```
2. Look at logs from ingress controller pod
  ```
  kubectl logs <pod-name>
  ```

**Expected behavior**
I expect nginx ingress controller to be able to manage the ingresses from the namespace I specified without me having to manually create a role and role binding for it.

Maybe the easiest thing to do is create the cluster role and cluster role bindings when `scope.namespace` is set to something.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Here is a sample of the error from nginx

```
E1215 15:13:42.900424       1 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:core:ingressctl-nginx-ingress-controller" cannot list resource "endpoints" in API group "" in the namespace "ingress-namespace"
E1215 15:13:42.900464       1 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:core:ingressctl-nginx-ingress-controller" cannot list resource "configmaps" in API group "" in the namespace "ingress-namespace"
E1215 15:13:42.900483       1 reflector.go:127] k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:core:ingressctl-nginx-ingress-controller" cannot list resource "services" in API group "" in the namespace "ingress-namespace"
```

**Comment by kristinnardal2** [comment]
There are some strange things in the `clusterrole.yaml` file, first of all it's not rendered if `scope.enabled` is true but at the same time we have this section:
https://github.com/bitnami/charts/blob/f489bbc92a3bcb2a91ae48543677c67c60422480/bitnami/nginx-ingress-controller/templates/clusterrole.yaml#L26-L35

That part will never be rendered because of the "if" conditional around the whole content of the file:
https://github.com/bitnami/charts/blob/f489bbc92a3bcb2a91ae48543677c67c60422480/bitnami/nginx-ingress-controller/templates/clusterrole.yaml#L1

This seems to indicate that there is a bug there since we have dead code in the template.

**Comment by alemorcuq** [comment]
Hi, @kristinnardal2.

Thanks for reporting this. You are right, there's definitely something wrong here. Have you tried if changing this:

https://github.com/bitnami/charts/blob/f489bbc92a3bcb2a91ae48543677c67c60422480/bitnami/nginx-ingress-controller/templates/clusterrole.yaml#L1

To this:

```
{{- if and .Values.rbac.create -}} 
```

Solves the issue?

**Comment by kristinnardal2** [comment]
For the moment I am using a workaround to the problem by using `extraArgs` to set the `watch-namespace` flag. This works but obviously isn't really what we want.

If we want to limit this to a specific namespace we should be creating a role binding in that namespace instead of a cluster role binding. From my knowledge of Helm though it's not really recommended for one release to install resources in two namespaces.

From the cluster role created it seems it's trying to limit the scope by restricting access to the namespace resource. I would think that even though we can only get certain namespaces we could still have access to resources in other namespaces.

Maybe you have a better understanding of how cluster roles work with regard to namespaced resources.

**Comment by marcosbc** [comment]
Sorry for the late response, due to winter holidays things are a bit slower than usual.

Note that the official NGINX Ingress Controller chart is doing exactly the same ([link](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/clusterrole.yaml#L1), so if you're able to identify an improvement, we'd suggest to send a PR and get it merged there beforehand.
Note that we track changes in this external chart to copy them over to the Bitnami chart, so any fix would make it to the Bitnami chart as well (usually after a couple of days).

**Comment by kristinnardal2** [comment]
There is a slight difference in how the official NGINX Ingress Controller chart does this and how this is done here, there are two scope values, `.Values.rbac.scope` and `.Values.controller.scope`.

This difference makes it so that the official chart does not have dead code while this one does.

I haven't checked whether what the official chart does actually solves the issue, it's been a while since I looked at this so I'll have to get back to you about that.
