### ISSUE TITLE
DokuWiki Ingress custom annotations don't work anymore

### ISSUE THREAD

**Issue by sidguptajhs** [bitnami/charts#4735]
Issue is with **dokuwiki** **10.0.3**

Version 10.0.3 breaks the ingress annotations support. Previously it used to iterate over host annotations using `.annotations` and this worked before it was under a `range` section. Now that line is removed from chart 10.0.3. So we cannot add custom annotations anymore.
Problem lies in https://github.com/bitnami/charts/commit/61fc060c2637fda568c8b72b41b7a7e681663af7 Line 2

**Comment by dani8art** [comment]
Hi @sidguptajhs 

Thank you for reporting it, I've created a PR please let's move the conversation there.
