### ISSUE TITLE
Fix a metrics configuration issue with spring-cloud-dataflow chart

### ISSUE THREAD

**Issue by tzolov** [bitnami/charts#4751]
**Which chart**:
[spring-cloud-dataflow](https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/README.md)

**Describe the bug**

The resent  SCDF OSS v2.7 release introduced some minor but breaking changes to the SCDF metrics configuration. 

- The grafanaInfo.url property doesn't exist anymore and has to be replaced by metricsDashboard.url instead.
- Starting with 2.7 SCDF provides Dataflow and Skipper servers metrics, but current bitnnami configuration doesn't allow enabling them.
- The existing Stream and Task metrics configuration are redundant, as with 2.7 those are replicated from the SCDF's own metrics conf.

**To Reproduce**

Install SCDF with metrics enabled and try to click on the Dashboard button.

**Comment by juan131** [comment]
Thanks for opening the issue @tzolov !! The team will review the associated PR and help you with the merging/release process.
