### ISSUE TITLE
Not able to view WordPress on a public IP address

### ISSUE THREAD

**Issue by SolutionsDEV** [bitnami/charts#4753]
**Which chart**:
WordPress on IBM Kebernete at https://cloud.ibm.com/catalog/content/wordpress

**Describe the bug**
I followed every step mentioned in the document at https://docs.bitnami.com/kubernetes/get-started-charts-iks/#step-2-provide-an-external-host-for-your-application
The public IP address is not accessible. I used the command "echo "WordPress Admin URL: http://$SERVICE_IP/admin"", I got the public IP address and made sure that it is the correct one, but when visiting the link in the browser, the error given is that the website cannot be reached.

I have done many additional settings, but none has worked while in the documentation above it shows as straight forward, but still cannot access the WordPress installation.

Is there any additional things to do?

Thanks  a lot.

**Comment by carrodher** [comment]
In the above guide, step 2 is not needed for WordPress but for other web applications like OwnCloud (that is the example shown). In the case of WordPress, this step is not required and you should skip this section and navigate directly to step 3.

Once deployed WordPress Helm Chart using the UI, you should be able to obtain the logs and see the installation notes. For that, run the commands shown to obtain the service’s public IP address and credentials (if randomly generated) to log in to WordPress, something like

```
** Please be patient while the chart is being deployed **

Your WordPress site can be accessed through the following DNS name from within your cluster:

    wordpress-1608203874.default.svc.cluster.local (port 80)

To access your WordPress site from outside the cluster follow the steps below:

1. Get the WordPress URL by running these commands:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w wordpress-1608203874'

   export SERVICE_IP=$(kubectl get svc --namespace default wordpress-1608203874 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
   echo "WordPress URL: http://$SERVICE_IP/"
   echo "WordPress Admin URL: http://$SERVICE_IP/admin"

2. Open a browser and access WordPress using the obtained URL.

3. Login with the following credentials below to see your blog:

  echo Username: user
  echo Password: $(kubectl get secret --namespace default wordpress-1608203874 -o jsonpath="{.data.wordpress-password}" | base64 --decode)
```

**Comment by SolutionsDEV** [comment]
Thanks for your response. I already did all the instructions skipping step 2 before I post this issue for help, I got the IP address and I made sure that it is the correct IP address, but the page does not open.

**Comment by carrodher** [comment]
It's weird as the IP from the service should be correct in that case. Do you know if there is any kind of limitation regarding networking/connectivity at the cluster level?

Can you run some commands to check if there is something not configured as expected?
```console
$ helm ls # To obtain the release name
$ kubectl get svc
$ helm get notes RELEASE_NAME
```
