### ISSUE TITLE
bitnami/owncloud Chart -- Memory Cache

### ISSUE THREAD

**Issue by mikeyGlitz** [bitnami/charts#4754]
**Which chart**:
owncloud/bitnami 8.3.2

**Is your feature request related to a problem? Please describe.**
I'm trying to set up memory caching with Owncloud as detailed in the [Documentation](https://doc.owncloud.com/server/admin_manual/configuration/server/caching_configuration.html)

**Describe the solution you'd like**
 Provide memory caching configuration via environment variables. Kubernetes Secrets or ConfigMap.

**Describe alternatives you've considered**
I checked the [values.yml](https://github.com/bitnami/charts/blob/master/bitnami/owncloud/values.yaml) and the [README.md](https://github.com/bitnami/charts/blob/master/bitnami/owncloud/README.md).
Neither provided any way to mount/override  or otherwise provide configuration for OwnCloud in order to provide memory caching.

Is there a way to provide memory caching configuration via environment variables? Kubernetes Secrets? or ConfigMap?

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this.
  Could you send an example of what needs to be configured ?
  I can see there are several options.

**Comment by mikeyGlitz** [comment]
I found another issue. The image itself would not support a memory cache.
The following PHP modules would need to be installed
- php-memcached
- php-apcu
- php-redis

My suggestion would be to provide the configuration via a series of environment variables to the container like the [Official Owncloud image](https://github.com/owncloud-docker/server)
```
OWNCLOUD_REDIS_DB
OWNCLOUD_REDIS_ENABLED false
OWNCLOUD_REDIS_FAILOVER_MODE
OWNCLOUD_REDIS_HOST redis
OWNCLOUD_REDIS_PASSWORD
OWNCLOUD_REDIS_PORT 6379
OWNCLOUD_REDIS_READ_TIMEOUT
OWNCLOUD_REDIS_SEEDS
OWNCLOUD_REDIS_SESSION_LOCKING_ENABLED 1
OWNCLOUD_REDIS_SESSION_LOCK_RETRIES 750
OWNCLOUD_REDIS_SESSION_LOCK_WAIT_TIME 20000
OWNCLOUD_MEMCACHED_ENABLED false
OWNCLOUD_MEMCACHED_HOST memcached
OWNCLOUD_MEMCACHED_OPTIONS
OWNCLOUD_MEMCACHED_PORT 11211
OWNCLOUD_MEMCACHE_LOCAL ${OWNCLOUD_CACHING_CLASS:-\\OC\\Memcache\\APCu}
OWNCLOUD_MEMCACHE_LOCKING
```
https://github.com/owncloud-docker/base#available-environment-variables

This seems to generate the following in `config.php` on the volume mounted on the image:

For example with Redis:

```php
'memcache.local' => '/OC/Memcache/APCu',
'memcache.distributed' => '/OC/Memcache/Redis'
'memcache.locking' => '/OC/Memcache/Redis',
'redis' => array(
    'host' => '{ OWNCLOUD_REDIS_HOST }',
    'port' => 6379,
    'timeout' => 0,
    'password' => '{ OWNCLOUD_REDIS_PASSWORD }', 
    'dbindex' => 0 ,
),
```

**Comment by marcosbc** [comment]
Hi, just wanted to update this issue to let you know that we just released [ownCloud `10.6.0-debian-10-r18`](https://github.com/bitnami/bitnami-docker-owncloud/#1060-debian-10-r18), which initialization scripts has been open-sourced in the [`rootfs` folder of the bitnami-docker-owncloud repo](https://github.com/bitnami/bitnami-docker-owncloud/tree/master/10/debian-10/rootfs).

Now it should be a lot simpler to contribute, so if you're open for contributing these (or other) changes to the Bitnami Docker image for ownCloud, it would be great and also help make these changes available sooner. We'd be happy to help in the review and release process for any such change.

**Comment by skillpoint-dev** [comment]
hi, is there a solutions for this? The documentation of the bitnami chart as well as docker image is really bad regarding this. When I provide the suggested environment variables in the values.yaml in the "extraEnvVars" section of the chart nothing for memcaching is generated in the config.php...

**Comment by rafariossaa** [comment]
Hi,
  I created an internal task to add the neded php-redis module for this feature.
  Unfortunately, it is in our backlog and I can not provide an ETA.

**Comment by imrj** [comment]
any ETA yet?

**Comment by carrodher** [comment]
There are no updates regarding this task, it is still on the backlog. Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-owncloud#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by icebrian** [comment]
Also hit this issue. Anyone have any suggestion?

**Comment by inetshell** [comment]
I'm also getting this issue
