### ISSUE TITLE
[bitnami/postgresql-ha] Chart-generated passwords become out of sync with database passwords

### ISSUE THREAD

**Issue by gabriellemadden** [bitnami/charts#4756]
**Which chart**:
postgresql-ha version 5.2.0 (we looked at the changes between this version and 6.3.0 and decided that there were no changes that would fix our problem)

**Describe the bug**
It is possible for the helm chart postgres/repmgr passwords to get out of sync with the postgres/repmgr user passwords stored in the postgres database PVC, where pods end up crashlooping without being able to authenticate and generating new passwords each time (none of which match the original passwords stored in the database)

**To Reproduce**
1. Install the helm chart without a secret for postgres and repmgr passwords (it will randomly generate these passwords)
1. Add some important data to the db/PVC that you would not be happy if you had to delete
1. Something happens (we aren't sure what caused this, see Additional Context for our thoughts) where your pods start crashlooping and the helm template starts trying to assign random passwords, which are not in sync with the database
1. Decide that you would actually like to be able to have control of your postgres and repmgr passwords and not have them randomly generated when pods start

**Expected behavior**
When changing the password AFTER the initial helm chart install, there should be some sort of step/check to ensure that the database passwords are in sync with your defined passwords.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
v3.4.1+gc4e7485
```

- Output of `kubectl version`:

```
v1.17.8
```

**Additional context**
We are using ArgoCD for automatic deployment, where we use this chart as a dependency. ArgoCD applies the charts via a `helm template` command. It's likely that we made a small change to the chart values, and that when ArgoCD reapplied the chart via the template command, new passwords were randomly generated which did not align with the passwords in the postgres database.

ArgoCD version information:
```json
{
    "Version": "v1.8.1+c2547dc",
    "BuildDate": "2020-12-10T02:59:21Z",
    "GitCommit": "c2547dca95437fdbb4d1e984b0592e6b9110d37f",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Our Ideas**
We believe this chart is not using the recommended way to store the passwords of the three described [here](https://repmgr.org/docs/current/configuration-password-management.html). If the dedicated password file option is used, it would be easier to manage passwords when re-applying helm charts.

**For Others Who Experienced Passwords Rotating**
(Some of this could be automated to solve this bug when charts are installed/applied)
We were able to resolve this without completely deleting the PVC/reinstalling the chart from scratch by doing the following:
1. Have this chart deployed in Kubernetes and managed by ArgoCD, tracking some branch (if you aren't using ArgoCD, some of these steps will need to be modified to work for your environment)
1. Define new passwords in a Kubernetes secret so that they don't rotate when `helm template` is run (use the `postgresql.existingSecret` value), commit/push to the branch ArgoCD is tracking
1. Disable liveness/readiness probes in `values.yaml` because if the pods are crashlooping, they will attempt to connect to the postgres db and kick out anyone else attempting to connect to them.
    ```yaml
    postgresql:
       livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
     pgpool:
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
    ```
    Commit and push.
1. Put both the `postgres` statefulset and `pgpool` deployment into a sleeping state (we did this by adding the below to the containers in the deployments/statefulsets). We did this by editing the live manifest of the statefulset and the deployment in ArgoCD, and adding the following to the containers:
   ```yaml
   command:
       - sh
       - "-c"
       - "while true; do sleep 10; done;"
   ```
1. Save the edited manifest and make sure the pods restart
1. Start a shell in the container in each postgres pod
1. Find `pg_hba.conf`, change `md5` to `trust` for all users, start postgres, and sign in to postgres without a password. We dove into the bitnami startup scripts to figure out how postgres is started, and compiled all the important steps to run below:
   ```shell
    # From /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh 
    # Load libraries
    . /opt/bitnami/scripts/liblog.sh
    . /opt/bitnami/scripts/libbitnami.sh
    . /opt/bitnami/scripts/libpostgresql.sh
    . /opt/bitnami/scripts/librepmgr.sh
    
    # Load PostgreSQL & repmgr environment variables
    . /opt/bitnami/scripts/postgresql-env.sh
    export MODULE=postgresql-repmgr
    
    print_welcome_page
    
    # Enable the nss_wrapper settings
    postgresql_enable_nss_wrapper

    # From /opt/bitnami/scripts/postgresql-repmgr/setup.sh
    # Load Libraries
    . /opt/bitnami/scripts/libpostgresql.sh
    . /opt/bitnami/scripts/librepmgr.sh
    
    # Load PostgreSQL & repmgr environment variables
    . /opt/bitnami/scripts/postgresql-env.sh
    
    # Ensure PostgreSQL & repmgr environment variables settings are valid
    repmgr_validate
    postgresql_validate
    
    # Set the environment variables for the node's role
    eval "$(repmgr_set_role)"

    # Prepare PostgreSQL default configuration
    repmgr_postgresql_configuration
    # Prepare repmgr configuration
    repmgr_generate_repmgr_config
    # Initialize PostgreSQL & repmgr
    repmgr_initialize

    # From /opt/bitnami/scripts/postgresql-repmgr/run.sh
    . /opt/bitnami/scripts/liblog.sh
    . /opt/bitnami/scripts/libpostgresql.sh
    . /opt/bitnami/scripts/librepmgr.sh
    
    # Load PostgreSQL & repmgr environment variables
    . /opt/bitnami/scripts/postgresql-env.sh

    # Create configuration so you don't need a password to access postgres when postgres is started with this conf
    perl -pne s/md5/trust/ /opt/bitnami/postgresql/conf/pg_hba.conf > /tmp/pg_hba.conf
    
    # Start postgres with all users trusted
    /opt/bitnami/postgresql/bin/postgres -D /bitnami/postgresql/data --config-file=/opt/bitnami/postgresql/conf/postgresql.conf --external_pid_file=/opt/bitnami/postgresql/tmp/postgresql.pid --hba_file=/tmp/pg_hba.conf &
    psql -U postgres
   ```
1. Reassign the passwords for postgres and repmgr to the passwords you have defined in your secret:
    ```sql
    ALTER USER postgres WITH PASSWORD <new_postgres_password>;
    ALTER USER repmgr WITH PASSWORD <new_repmgr_password>;
    -- You can see the old password currently stuck in the repmgr table:
    SELECT node_id, conninfo FROM nodes;
     node_id |                                                                                                                    conninfo                                                                                 
    ---------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        1000 | user=repmgr password=xS9zhYiMyw host=postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.postgres.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
        1001 | user=repmgr password=xS9zhYiMyw host=postgres-postgresql-ha-postgresql-1.postgres-postgresql-ha-postgresql-headless.postgres.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
    (2 rows)

    UPDATE nodes SET conninfo='...password=<new_repmgr_password>...ha-postgresql-0...' WHERE node_id=1000;
    UPDATE nodes SET conninfo='...password=<new_repmgr_password>...ha-postgresql-1...' WHERE node_id=1001;
    -- Repeat above for your number of replicas...
    ```
1. Stop postgres:
   ```shell
   pg_ctl stop  -D /bitnami/postgresql/data
   ```
1. Re-enable your liveness/readiness probes and remove the sleep command from running containers, commit and push, make sure pods restart and watch as things become happy

**Logs we saw in order to come to these conclusions**

```
2020-12-14 23:54:01.005 GMT [159] FATAL:  password authentication failed for user "repmgr"
2020-12-14 23:54:01.005 GMT [159] DETAIL:  Password does not match for user "repmgr".
Connection matched pg_hba.conf line 1: "host     all            repmgr    0.0.0.0/0    md5"
[2020-12-14 23:54:01] [ERROR] connection to database failed
[2020-12-14 23:54:01] [DETAIL]
FATAL:  password authentication failed for user "repmgr"
[2020-12-14 23:54:01] [DETAIL] attempted to connect using:
user=repmgr password=xS9zhYiMyw connect_timeout=5 dbname=repmgr host=postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.postgres.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
```

**Comment by dani8art** [comment]
Hi @gabriellemadden, 

That's true our charts generate passwords and they will become out of sync. We recommend users whether to provide this password via helm values or existing secret. 

You can find some tips [here](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/) 

Personally, I would go for an existing secret. If you need to add those secrets to a git repo in other to use argo then you can also use [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets).

Thanks!
