### ISSUE TITLE
[bitnami/memcached] Persistence is redundant

### ISSUE THREAD

**Issue by kfirfer** [bitnami/charts#4757]
Hello

Memcached doesn't have persistence, his all data places on RAM without any persistence capabilities

It is redundant

Can be found here:
https://github.com/bitnami/charts/blob/fcb97a729ebe856605e3156dba8b6ffe7b270362/bitnami/memcached/values.yaml#L173

**Comment by kfirfer** [comment]
Created pull request:
https://github.com/bitnami/charts/pull/4758

**Comment by FraPazGal** [comment]
Hi @kfirfer, thanks for the PR! I see a colleague already reviewed it so we'll continue any discussion there.

**Comment by kfirfer** [comment]
@FraPazGal alright 
closing this issue
