### ISSUE TITLE
[bitnami/logstash] Provide a way to modify JVM heap size

### ISSUE THREAD

**Issue by jeff51419** [bitnami/charts#4764]
**Which chart**:
bitnami/logstash

**Is your feature request related to a problem? Please describe.**
Yes, i found default heap limit is 1G. When the logstash heap reach 763MB, it will restart and affect the log 

![image](https://user-images.githubusercontent.com/18411883/102479643-1f590100-409a-11eb-994f-e5f1ca21782c.png)

**Describe the solution you'd like**
provide logstashJavaOpts in value that we can modify it. Just like https://github.com/elastic/helm-charts/blob/master/logstash/values.yaml#L78

**Comment by marcosbc** [comment]
Hi @jeff51419, we're working on a new release of the Bitnami Logstash chart that will explicitly have support for setting the heap size (via the `LOGSTASH_HEAP_SIZE` environment variable). We expect the Logstash container image with tag `
7.10.1-debian-10-r9` to contain support for the new flag.

> NOTE: The official image uses `LS_JAVA_OPTS`, which is an environment variable supported natively by Logstash, meaning you can also use it in the Bitnami chart.

In the meantime, with a previous container image version, you can see how to set it to a value like 2G with the below example:

```
--set "extraEnvVars[0].name=LS_JAVA_OPTS" --set "extraEnvVars[0].value=-Xmx2g -Xms2g"
```

Feel free to send a PR implementing support for an `logstashJavaOpts` option using the newly supported `LOGSTASH_HEAP_SIZE` option in the Bitnami Logstash chart! We'd be happy to review and help with the release.

**Comment by jeff51419** [comment]
thanks for your info.
