### ISSUE TITLE
[InfluxDB] Error: failed to start container "relay"

### ISSUE THREAD

**Issue by oo00spy00oo** [bitnami/charts#4765]
**Which chart**:

InfluxDB - 1.1.4

**Describe the bug**

I am using values from https://github.com/bitnami/charts/blob/master/bitnami/influxdb/values-production.yaml

```Error: failed to start container "relay": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/influxdb_relay": stat /influxdb_relay: no such file or directory: unknown```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi,
   Could you indicate the parameters used ?
   In which log did that message appear ?

**Comment by stefan-fast** [comment]
Hey, I just came accross the same issue. It works fine with chart version `1.1.2` but starting with `1.1.3` I get the same error output. The message appears in the events of the pod when calling `kubectl describe` on it. Because of this issue the influxdb-relay pod is unable to start and stuck in a crash loop.

I used the folllowing to install the chart:
`helm install my-release bitnami/influxdb --namespace test --create-namespace --set architecture=high-availability`

The chart is installed on Docker Desktop's Kubernetes running on MacOS.

- Docker Desktop (MacOS) Version: `3.0.2 (50996)`
- Docker Engine Version: `20.10.0`
- `helm version`: 
   ```
   version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
   ```
- `kubectl version`:
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by hern16** [comment]
It was a typo in the deployment template https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/relay/deployment.yaml#L54

It sould be `/influxdb-relay` (hyphen) not `/influxdb_relay` (underscore)

You can patch with:

- **influx-relay-patch.yaml**
```
spec: 
  template:
    spec:
      containers:
        - name: relay
          image: docker.io/bitnami/influxdb-relay:0.20200717.0-scratch-r7
          command:
          - /influxdb-relay
 ```

Then

`kubectl patch deploy my-release-influxdb-relay --namespace test --patch "$(cat influx-relay-patch.yaml)"`

**Comment by rafariossaa** [comment]
Hi,
  @hern16 thanks you very much for spotting this and sending a patch.
  @stefan-fast  Could you try the new chart version and see if it fixes the bug for you ?

**Comment by stefan-fast** [comment]
Yes, that fixed the issue :)
Thanks @hern16 and @rafariossaa for the quick fix and release!
