### ISSUE TITLE
Redis ACL

### ISSUE THREAD

**Issue by Raynbag** [bitnami/charts#4772]
Redis-Cluster
v4.2.1

Including access control lists in the chart is a little difficult, especially when appending them to the config file with the passwords being plaintext in the config map created.

What's the best way to handle these please?

Many thanks in advance

**Comment by marcosbc** [comment]
Hi @Raynbag, currently the only way to configure it to the chart is to mount the required files.

To simplify the process on your side, you could try [loading an external ACL file via `aclfile`](https://redis.io/topics/acl#using-an-external-acl-file), and then mount this file via `redis.extraVolumes`/`redis.extraVolumeMounts`. That would allow you to store the file in a volume.

To make it more secure, you could always [mount the volume from a secret](https://kubernetes.io/docs/concepts/configuration/secret/#use-case-dotfiles-in-a-secret-volume).

Hope it helps!

**Comment by Raynbag** [comment]
Hi @marcosbc 

Thanks very much for getting back to me and happy new year!

This worked perfectly, thank you so much for your help, really appreciate it.

**Comment by trung674** [comment]
Hi @marcosbc

Is there anyway to mount an ACL file in Redis helm chart instead?

**Comment by marcosbc** [comment]
Hi @trung674, I assume you refer the Bitnami Redis chart, right? If so the tips in [my previous comment](https://github.com/bitnami/charts/issues/4772#issuecomment-747997013) should work.

**Comment by trung674** [comment]
It seems to me that Bitnami Redis chart does not provide support for mounting extra files via `redis.extraVolumes/redis.extraVolumeMounts`. Maybe it is better to raise an issue regarding this?

**Comment by marcosbc** [comment]
It looks like it is missing, as it is only present in redis-cluster. If so feel free to create a new issue.

Note that due to winter holidays we're a bit overwhelmed right now, considering we have lots of things on our plate. If you feel confident you could always contribute by sending a PR, we'd be happy to help with the review and release with the changes.

**Comment by nishantgreendeck** [comment]
how to provide location of aclfile to redis in bitnami redis helm chart
