### ISSUE TITLE
[bitnami/kube-prometheus]

### ISSUE THREAD

**Issue by rbs4ba** [bitnami/charts#4774]
**Which chart**:
kube-prometheus:3.3.2

**Is your feature request related to a problem? Please describe.**
This is related to a problem I am having with the prometheus operator, link here: https://github.com/prometheus-operator/prometheus-operator/issues/3747

I have found a fix/workaround of explicitly setting the namespaces that the operator works with, via the `--namespaces` flag: https://github.com/prometheus-operator/prometheus-operator/blob/master/cmd/operator/main.go#L180

**Describe the solution you'd like**
I would like to see support added to the operator deployment (https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml#L61-L79) to either:
- 1) support the `namespaces` argument
- 2) support "extraArgs" in general, letting users specify any additional arguments that they want to set for the operator dpeloyment.

**Describe alternatives you've considered**
At the moment, this seems to be the only solution that I have found.

**Additional context**
The reason I need to set the namespace explicitly is because there is _something_ wrong with one of the namespaces that the operator is watching. I am not yet sure what the issue is on that front and will be continuing to investigate. But in the meantime, it would be nice if there could be support for these additional arguments

**Comment by rafariossaa** [comment]
Hi,
  Thank for your detailed description. I hope you will find the issue.
  Would you like to send a PR adding this ? We will be glad to review and merge it.
