### ISSUE TITLE
[bitnami/rabbitmq] [bitnami/common] deprecation warning for ingress apiVersion networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by maartenmensink** [bitnami/charts#4775]
**Which chart**:
[bitnami/rabbitmq]  [bitnami/common]

**Describe the bug**
A deprecation warning occurs when deploy [bitnami/rabbitmq] with ingress enabled on a K8S 1.19 cluster

**To Reproduce**
1. Take a K8S with version 1.19
2. configure the values.yaml with ingress enabled
3. deploy helm chart

**Expected behavior**
Expected to see apiVersion networking.k8s.io/v1 

**Actual behavior**
apiVersion networking.k8s.io/v1beta1

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
-

**Related issues**
https://github.com/bitnami/charts/issues/4723

**Comment by alemorcuq** [comment]
Thanks for the PR!
