### ISSUE TITLE
[keycloak] Ingress apiVersion is deprecated

### ISSUE THREAD

**Issue by ralph089** [bitnami/charts#4784]
**Which chart**:
bitnami/keycloak - latest version

**Describe the bug**
Helm lint throws an error, because Ingress apiVersion is deprecated:

```
PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: lint (4 bytes)
  2: /var/folders/6v/r3gwkvsd23qfrp3f3hr9c6cw0000gn/T/091834623/keycloak/bitnami/keycloak/1.1.0/keycloak (99 bytes)
  3: --values (8 bytes)
  4: /var/folders/6v/r3gwkvsd23qfrp3f3hr9c6cw0000gn/T/values527722578 (64 bytes)
  5: --values (8 bytes)
  6: /var/folders/6v/r3gwkvsd23qfrp3f3hr9c6cw0000gn/T/secret935206281 (64 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: 1 chart(s) linted, 1 chart(s) failed

COMBINED OUTPUT:
  Error: 1 chart(s) linted, 1 chart(s) failed
  ==> Linting /var/folders/6v/r3gwkvsd23qfrp3f3hr9c6cw0000gn/T/091834623/keycloak/bitnami/keycloak/1.1.0/keycloak
  [ERROR] templates/ingress.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"
```
**To Reproduce**

1. Enable Ingress
2. Lint the chart

**Expected behavior**
Linting throws no error =)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-03-29T19:36:35Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dani8art** [comment]
Hi @ralph089, 

It is because of your server version `v1.11.0` the requested ingress version is `extensions/v1beta1` so we auto calculate it using:

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl#L27

You would need to upgrade your server or downgrade your helm client in order to have the compatible versions.

Thanks!

**Comment by ralph089** [comment]
Hi @dani8art,

Unfortunately it isn't possible to upgrade our cluster. I'll install an older helm client then, thank you.

Just two sidenotes that caught my eye during analysis of this issue: 

- the GitVersion attribute used in the _capabilities.tpl is deprecated, see: https://github.com/helm/helm/blob/master/pkg/chartutil/capabilities.go#L65
- in the Keycloak chart the apiVersion is hardcoded: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/ingress.yaml#L2

Thanks
Ralph

**Comment by dani8art** [comment]
O yes! Thank you so much for the feedback!
