### ISSUE TITLE
How to use Bitnami MySQL and Bitnami PostreSQL with Azure Virtual (serverless) Kubernetes Cluster Nodes?

### ISSUE THREAD

**Issue by siegfried01** [bitnami/charts#4787]
**Which chart**:
See title.

**Is your feature request related to a problem? Please describe.**
Maybe

**Describe the solution you'd like**
Please see [https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli](url). Looks like the yaml for serverless needs to be enhanced with special nodeselectors (is this possible on the helm command line?) and a tolerations clause (is this possible presently via the helm command line?)

**Describe alternatives you've considered**
Just use the old fashioned kubernetes cluster nodes.

**Additional context**
Nope!

**Comment by FraPazGal** [comment]
Hello @siegfried01,

From what the link's guide explains, you need to add the `tolerations` and `nodeSelector` parameters in your `deployment/statefulSet`, is that right? You can do that changing the related parameters in `values.yaml` or by adding `--set primary/secondary.tolerations/nodeSelector` for our MySQL chart and `--set primary/readReplicas.tolerations/nodeSelector` for PostgreSQL.

**Comment by siegfried01** [comment]
Thanks FraPazGal... I plan to give that a try. (Unfortunately, I have had a few distractions).

**Comment by FraPazGal** [comment]
Hi @siegfried01,

Glad to hear from you! Don't worry, I'll reopen this and wait for your feedback.
