### ISSUE TITLE
Does Bitnami support Azure SQL Serverless Databases?

### ISSUE THREAD

**Issue by siegfried01** [bitnami/charts#4788]
**Which chart**:
The MSSQL chart for stateful sets.

**Is your feature request related to a problem? Please describe.**
I want to save money and use serverless.

**Describe the solution you'd like**
Please see [https://docs.microsoft.com/en-us/azure/azure-sql/database/serverless-tier-overview](url) and I'm told that this describes how to use serverless in a K8 stateful set: [https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15](url). Hmm.... I don't see anything special in this last link for serverless but maybe I missed it. 

It would be very nice to see bitnami support serverless SQL databases...

**Describe alternatives you've considered**
Use the old fashioned kind...

**Additional context**
None.

**Comment by marcosbc** [comment]
Hi @siegfried01, unfortunately we don't have any chart that currently supports MSSQL, except for [Spring Cloud DataFlow](https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow).

Note that most of our application charts (i.e. WordPress) usually support only one of MariaDB/MySQL or PostgreSQL. My understanding is that Azure offers a service for those databases (Azure Database for MariaDB/MySQL/PostgreSQL), but I'm not aware of them supporting the Serverless tier.

**Comment by siegfried01** [comment]
For the immediate future I'm going to try using the MSSSQL serverless service as described here [https://docs.microsoft.com/en-us/azure/azure-sql/database/single-database-create-quickstart?tabs=azure-cli](url).

If that works I might try experimenting by making an MS SQL stateful set and then editing the deployment as described here:  [https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#deploy-a-sample-app](url). If anyone else wants to try it, please let me know if it works...
