### ISSUE TITLE
Version issue with bitnami/airflow helm chart

### ISSUE THREAD

**Issue by VORUSRIK000** [bitnami/charts#4789]
We are using bitnami helm chart for airflow deployment on Azure AKS, connecting to https://charts.bitnami.com/bitnami repository. When we check the bitnami/ariflow version in the repo, it shows 1.10.13. Verified this running the command - "helm search repo bitnami/airflow". But on the github, we see that helm chart shows the version as 1.10.14.

We ran "helm repo update" and it showed the repo got updated successfully, but still shows the airflow version as 1.10.13.

Can you provide any info on this issue?

**Comment by alemorcuq** [comment]
Hi, @VORUSRIK000.

Version `1.10.14` is now published in the repo. Keep in mind that there can be some delay in the repository compared to GitHub as we update the repositories several times during the day.

Regards,
Alejandro

**Comment by VORUSRIK000** [comment]
Thanks Alejandro for the update.
I updated the repo listing and checked the version that is reflecting. Still shows as 1.10.13. Attaching the image below FYR. I will try to run the refresh later in the day, assuming their might be some delay in reflecting on the repo. But let me know if I need run any specific step to reflect the latest.

![image](https://user-images.githubusercontent.com/12094673/102926486-ee861c80-4449-11eb-9a79-c2acbc27d77a.png)

**Comment by rafariossaa** [comment]
Hi,
  This is published through our pipeline and we are currently having some issues in the testing stage. 
  I am not sure this will be published today, but it will soon.

**Comment by VORUSRIK000** [comment]
As suggested, will try to refresh later in the week assuming it would get deployed to repo post testing.
