### ISSUE TITLE
[bitnami/zookeeper] extraInitContainers

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#4793]
**Which chart**:

bitnami/zookeeper

**Is your feature request related to a problem? Please describe.**

When deploying in a cluster with readOnlyRootFilesystem, conf folder is not writable. Mounting an emptyDir volume there will override all config files inside.

**Describe the solution you'd like**

Ability to define extraInitContainers would enable copying original config files to a shared emptyDir volume which is mounted to /opt/bitnami/zookeeper/conf to ensure folder is writable with all original config files

**Describe alternatives you've considered**

Manually mounting original config files as secret but they are not writable (even with defaultMode 0777). Also maintaining external config files is a burden between version upgrades.

**Additional context**

This also makes it consistent with other bitnami charts which allow extraInitContainers in values.yaml

**Comment by dani8art** [comment]
Hi @tbnguyen1407 thanks for your feedback I've created a PR to add this for zookeeper chart, let's move the conversation there, please.
