### ISSUE TITLE
Does Bitnami support GitLab Runner ? 

### ISSUE THREAD

**Issue by ysicing** [bitnami/charts#4794]
**Which chart**: `GitLab Runner`

**Is your feature request related to a problem? Please describe.** 

Official helm seems to be less clear and useful than Bitnami's structure

**Comment by FraPazGal** [comment]
Hi @ysicing,

Thanks for reaching out! Currently, we don't have plans to include `Gitlab Runner` to our catalog, but we will discuss this internally for any possible changes mid/long-term.

**Comment by ysicing** [comment]
Ok, thank you.
