### ISSUE TITLE
[bitnami/redis-cluster]Permission denied error for tls enabled redis-cluster deployment using redis helm chart 4.2.1? 

### ISSUE THREAD

**Issue by bharat15-ml** [bitnami/charts#4799]
I have deployed redis-cluster with helm chart in kubernetes cluster..
I am using helm version - "v3.2.1"
And kubernetes version - "v1.18.2".

Have followed the below link for redis-cluster deployment- https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster

Using values-production.yaml file without any modifications works fine, and it deployed redis-cluster successfully. 

Now I am exploring on how to enable tls feature, and for that have made below modifications in values-production.yaml file--

![IMG_20201221_122105](https://user-images.githubusercontent.com/76279928/102747989-57589080-4387-11eb-992a-1351d208212e.jpg)

After this changes when I am trying to deploy redis-cluster, getting below error--

![IMG_20201221_122656](https://user-images.githubusercontent.com/76279928/102748277-dfd73100-4387-11eb-900a-fc5e4e06a565.jpg)

I have successfully  created the storage-class and have verified was working fine with values-production.yaml file deployment. 

I have also created certificates using "gen-test-certs.sh" scripts specified in "https//redis.io/topics/encryption" and generated certificates-tls-secrets as per specified in --https://docs.bitnami.com/kubernetes/infrastructure/redis-cluster/administration/enable-tls
![IMG_20201221_124424](https://user-images.githubusercontent.com/76279928/102749610-51b07a00-438a-11eb-8f94-ff8c1f045538.jpg)

After logging to running pod able to see that certificates got placed at location- "/opt/bitnami/redis/certs/" And also checked that in redis.conf file all the relevant changes got reflected.. 

Pls help me on this how to resolve this issue and also let me know if I want to write the logs inside the container at this location - /opt/bitnami/redis/logs/ how to enable it this as well?? 

I am running with non root image and user-1001.. 

#

**Comment by marcosbc** [comment]
Hi @bharat15-ml, I've tried to reproduce your issue but couldn't. It seems like you are mounting `/opt/bitnami/redis/etc/redis.conf` at some point, which is something the chart does not do, do you have more info on this? Also please share any other modifications to the values.yaml you did to be able to be of further help.

**Comment by singhbharat** [comment]
Haven't made much changes in values-production.yaml except for TLS section, password, and storageClass.

One more thing, when I have made below changes to instead of running as 1001 user to root user (0) in the values-production.yaml file

    podSecurityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
And also made changes for 

    containerSecurityContext:
      enabled: true
      runAsUser: 0

Getting below error- chown: changing ownership of '/bitnami/redis/deta: operation not permitted.. 

As per my understanding, whenever, for any configuration changes( like for tls feature) making changes in values-production.yaml, 1001 user not having privilege to make modification in redis.conf inside the container?? 

Please, let me know on this, possible way for resolution.

**Comment by bharat15-ml** [comment]
Haven't made much changes in values-production.yaml except for TLS section, password, and storageClass. 

After the deployment after logging to running pod inside the container can see that "/opt/bitnami/redis/etc/redis.conf file got created.. I guess this should be logic written for docker image-

![IMG_20201228_131336](https://user-images.githubusercontent.com/76279928/103198521-8a160200-490e-11eb-9ac4-1d103150d28a.jpg)

Further more on this.. Have seen redis.conf having owner permission (1001) and group permission (1001). 

![IMG_20201228_131816](https://user-images.githubusercontent.com/76279928/103198775-32c46180-490f-11eb-85a4-25af2cf598a3.jpg)


One more thing, when I have made below changes to instead of running as 1001 user to root user (0) in the values-production.yaml file

    podSecurityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
And also made changes for 

    containerSecurityContext:
      enabled: true
      runAsUser: 0

Getting below error- chown: changing ownership of '/bitnami/redis/deta: operation not permitted.. 

As per my understanding, whenever, for any configuration changes( like for tls feature) making changes in values-production.yaml, 1001 user not having privilege to make modification in redis.conf inside the container?? 

Please, let me know on this, possible way for resolution.

**Comment by bharat15-ml** [comment]
Hi @**marcosbc**  after deleting all older PV and PVC for a particular storageClass this issue is resolved.. Have tested the selfsigned ssl certificates, working fine.. 

One more thing wanted to know, how to enable redis-cluster logs?? 

As, per documentation it is mentioned it should be written to "/opt/bitnami/redis/logs/redis.log".. 

Currently logs are disabled, how can I enable this?? Haven't found specific entry in values-production.yaml file. Thanks!!

**Comment by marcosbc** [comment]
>One more thing wanted to know, how to enable redis-cluster logs??
>
>As, per documentation it is mentioned it should be written to "/opt/bitnami/redis/var/log/redis-server.log"..

You can get Redis Cluster logs via "kubectl logs", i.e. if the release name is `my-release`:

```
$ kubectl logs my-release-redis-cluster-0
```

**Comment by bharat15-ml** [comment]
Thanks **marcosbc**!! This means, logs not required for redis-cluster booting process?? Agree to close this incidence...

**Comment by marcosbc** [comment]
That is correct, those Redis Server logs are not required for the booting process. Closing this issue.
