### ISSUE TITLE
[bitnami/spark] How to access Application Detail UI from remote kubectl client

### ISSUE THREAD

**Issue by echang0929** [bitnami/charts#4810]
**Which chart**:
bitnami/spark

**Is your feature request related to a problem? Please describe.**
Not any problem, but it is necessary to monitor applications submitted to spark cluster

**Describe the solution you'd like**
We could access master and workers UI with kubectl port-forward command. But look like Application Detail UI use headless services. How could access them from client browser?

Spark context Web UI available at http://test-spark-master-0.test-spark-headless.spark-ext.svc.cluster.local:4040
Spark context available as 'sc' (master = spark://test-spark-master-svc.spark-ext.svc.cluster.local:7077, app id = app-20201222025555-0001).

**Comment by carrodher** [comment]
Are you able to follow the installation notes that are shown when the chart is installed the first time? You can see those instructions at any moment by running `kubectl get notes MY_RELEASE`, in those notes, you should see all the required steps to access the application. Are you missing any step in those notes or are you following them but there is any issue during the process?

**Comment by echang0929** [comment]
Thank you, @carrodher . 
```
➜ helm get notes test-spark
NOTES:
1. Get the Spark master WebUI URL by running these commands:

  kubectl port-forward --namespace spark-ext svc/test-spark-master-svc 80:80
  echo "Visit http://127.0.0.1:80 to use your application"

2. Submit an application to the cluster:

  To submit an application to the cluster the spark-submit script must be used. That script can be
  obtained at https://github.com/apache/spark/tree/master/bin. Also you can use kubectl run.

  export EXAMPLE_JAR=$(kubectl exec -ti --namespace spark-ext test-spark-worker-0 -- find examples/jars/ -name 'spark-example*\.jar' | tr -d '\r')

  kubectl exec -ti --namespace spark-ext test-spark-worker-0 -- spark-submit --master spark://test-spark-master-svc:7077 \
    --class org.apache.spark.examples.SparkPi \
    $EXAMPLE_JAR 5

** IMPORTANT: When submit an application from outside the cluster service type should be set to the NodePort or LoadBalancer. **

** IMPORTANT: When submit an application the --master parameter should be set to the service IP, if not, the application will not resolve the master. **

** Please be patient while the chart is being deployed **
```

As you see, this note does not contain information how to access Web UI of the cluster.

**Comment by echang0929** [comment]
I found, however, you could get an internal link to the application submitted on Spark master WebUI, which is based on headless service of this cluster and a pod name with port 4040. Then you could port-forward it via: 
```
k port-forward <pod-name> 4040:4040
```
Then you could access this Spark application WebUI .
