### ISSUE TITLE
[bitnami/redis] Redis with sentinel enabled can have separate masters

### ISSUE THREAD

**Issue by berkayoz** [bitnami/charts#4819]
**Which chart**:
bitnami/redis:12.2.4

**Describe the bug**
There can be seperate masters with varying slaves(usually none) when the statefulset is starting up or recovering from a failure with no pods running which results in master-slave sync failure. This also causes data loss upon failure/shutdown if `redis` service redirects to a master that has no slaves. Also redis user when cannot be created which outputs a permission error.

**To Reproduce**

1. Watch the endpoints by `kubectl get endpoints -w`.
2. Deploy the helm chart using `helm install redis bitnami/redis -f values-production.yaml`. (Only differences from the original file are `sentinel.enabled=true`, `metrics.serviceMonitor.enabled=true`.
3. Check the pod logs for each StatefulSet node by `kubectl logs redis-node-* -c redis`. ( * can be 0,1,2 ... replicaCount-1)
4. First pod has the logs shown below and some slave pods might also have the same logs which points that `redis-headless` service can't be resolved by the dns at the time and the running node is set as master.
```
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
chown: invalid user: 'redis'
 Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Could not connect to Redis at redis-headless.default.svc.cluster.local:26379: Name or service not known
I am master
redis 19:46:57.77 INFO  ==> ** Starting Redis **
1:C 22 Dec 2020 19:46:57.779 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 22 Dec 2020 19:46:57.779 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 22 Dec 2020 19:46:57.779 # Configuration loaded
1:M 22 Dec 2020 19:46:57.781 * Running mode=standalone, port=6379.
1:M 22 Dec 2020 19:46:57.781 # Server initialized
1:M 22 Dec 2020 19:46:57.782 * Ready to accept connections
```
5. Delete all the slave nodes by `kubectl delete po redis-node-1 redis-node-2` (Include all the slave node names) 
6. After deletion and recreation of the pods, connections to master node as slaves are successfull since headless-service registered it's ip address to the relative Endpoints object which enables slaves to resolve the `redis-headless` service.

**Expected behavior**
A successful startup without having to restart slave nodes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This seems like a race condition. [Headless services with selectors](https://kubernetes.io/docs/concepts/services-networking/service/#with-selectors) in kubernetes creates Endpoints records in the API, and modifies the DNS configuration to return records (addresses) that point directly to the Pods backing the Service. This record is created after the pod is ready (readinessProbe is met) unless headless service contains `publishNotReadyAddresses: true` in it's spec. The StatefulSet node pods have `readinessProbe`s as local ping checks for both the `redis` and the `sentinel` containers. Which means that any node that boots up properly can be ready and let the waiting nodes creations continue. The first node to boot up will always be the master since no ip address is registered on the Endpoints object. But the slaves might bootup in a chain even before kubernetes can register the ip for the pod that just got ready which causes dns resolves in slaves to fail and get an empty response. In that case "slaves" also declare themselves as masters which breaks the synchronization. 

Failure for user creation is caused by a missing `nil` check in the helm template. [This line](https://github.com/bitnami/charts/blob/28701368ae0d7c5a08b4439254bf54700f1e8e06/bitnami/redis/templates/configmap-scripts.yaml#L45) casts the variable to integer which results in nil being converted to `0`. Since we want to create a user if we have our user set to `root`, not having a `runAsUser` property in our `values.yaml` causes these line to be added since nil is casted to 0 and the condition is met. But we don't actually have our user as root in the container which results in a permission error when trying to create a user.

**Comment by marcosbc** [comment]
I see you sent a PR fixing, thanks for contributing! So this issue will be closed automatically once it is merged.
