### ISSUE TITLE
[bitnami/keycloak] cannot create directory '/opt/bitnami/keycloak/certs': Permission denied

### ISSUE THREAD

**Issue by jgallucci32** [bitnami/charts#4821]
**Which chart**:
keycloak 1.1.4

**Describe the bug**
When deploying helm chart for Keycloak with TLS enabled, the keycloak pod fails to start with the following error
```
mkdir: cannot create directory '/opt/bitnami/keycloak/certs': Permission denied
```

**To Reproduce**

1. Enable TLS settings by configuring `answers.yaml` as follows
```
auth.tls.enabled: true
auth.tls.jksSecret: keycloak-jks
auth.tls.keystorePassword: <password>
auth.tls.truststorePassword: <password>
```
2. Deploy helm chart per instructions

**Expected behavior**
Keycloak deploys with custom TLS configuration

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Using Rancher catalog (unsure which version of Helm is under the hood)
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Red Hat Enterprise Linux 7.8
Rancher Kubernetes 17.5.1
Rancher Management 2.4.3

**Comment by jgallucci32** [comment]
I believe I have discovered the root cause. The default configuration for the chart is to enable security context as a non-root user
```yaml
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
```
however, the directory `/opt/bitnami/keycloak` inside the container is owned by root
```
I have no name!@c615b1fd9f69:/$ ls -ld /opt/bitnami/keycloak/
drwxr-xr-x. 1 root root 59 Nov 24 19:47 /opt/bitnami/keycloak/
```
Two proposed solutions to fix this:
1. Run the container as root or disable security context altogether (not preferred)
2. Directly mount the kubernetes secret to `/opt/bitnami/keycloak/certs` rather than having to copy them directly before the entrypoint

I don't fully understand the context of why the replica counts are needed for keycloak certs (i.e. keycloak-[id].keystore.jks) so perhaps one of the developers can shed some light on that. My thought is this is done to allow each replica to have a custom TLS cert, but considering most deployments are behind a loadbalancer with a single URL I would think the same TLS cert can be used. If having a different cert for each replica is not needed then the second option would be preferred to allow direct mounting of the kubernetes secret to avoid having to have custom scripts create a directory before the entrypoint.

**Comment by FraPazGal** [comment]
Hello @jgallucci32,

Thank you for bringing this up and for your suggestions! I have been able to reproduce the issue and this can indeed be solved by running as root, though not recommended. 

I would say that is indeed the use case for having independent keystores, but I'm reticent to remove that funcionality even if niche. Another solution could be to have the `/certs` folder created at container's build-time. I will ask the team and get back to you with a definite answer, thanks!

**Comment by FraPazGal** [comment]
Hi @jgallucci32,

We have opened an internal task to address both this issue and the one you found testing our container https://github.com/bitnami/bitnami-docker-keycloak/issues/2. Like my colleague told you, although our workload right now won't permit us to work on this, we are always happy to review and include user's additions! Thank you for your understanding.

**Comment by jgallucci32** [comment]
Thanks @FraPazGal and @marcosbc for confirming the issue. I should be able to work a PR on this as I have uncovered a few other related issues (such as incorrect env vars in the config maps) and been able to get it partially working.

Before I go down this route, I wanted to get some feedback on Keycloak 12.x switching to Quarkus and if fixing these issues would be worth the effort. Given these configuration settings are specific to Wildfly, they will no longer be relevant once 12.x hits with Quarkus I would imagine so I am curious the timeline before the switchover in the bitnami stack.

**Comment by javsalgar** [comment]
Hi,

Currently, we are using the server bundled by default in the keycloak tarball. That means that, the moment they switch to Quarkus, we'll work on adapting it immediately. We have internal SLAs for the differen types of assets. When it is a major version, we expect to deliver it during the weeks after it is generally available.

**Comment by dennisfleischmann** [comment]
We have the same issue as stated by @jgallucci32. When will be a fix available?

**Comment by javsalgar** [comment]
Hi,

If Keycloak + Quarkus will take a while, maybe it makes sense to add the changes that @jgallucci32 suggests.

**Comment by jgallucci32** [comment]
I've come up with a 3rd option and I think will satisfy security and functionality requirements. The container is designed to have `/opt/bitnami/keycloak/certs` mounted by the container runtime rather than have data copied into the directory. Since all the files from /opt/bitnami and all the lower levels are owned by root we should keep it that way. The executing user is `1001` and can only execute files and not access them as root (good security practice). So instead of mounting the certs directory to `/certs` and issuing a `cp` command to move the data over to a root-protected directory we can accomplish this in 2 steps using an init container
1. Use init container and mount the configMap for certs used by primary container
2. Create a symbolic link for the key using the ${ID} environment variable. Example:
```
ln -s /certs/keycloak-${ID}.keystore.jks /opt/bitnami/keycloak/certs/keycloak.keystore.jks
```
By using an init container we can properly configure the keystores in a shared mount point without having to modify file permissions or the security context of the pod.

**Comment by FraPazGal** [comment]
Hi @jgallucci32,

That solution looks promising, thanks for the input! The team will work on the container related issue in the following weeks. Would you still like to create a PR addressing this? We would be happy to review it.

**Comment by jgallucci32** [comment]
@FraPazGal Yes I will work a PR for the specific chart issue. I'll make sure it aligns with what the container expects so both can be changed independently.

**Comment by FraPazGal** [comment]
Great to hear that @jgallucci32!

We'll work on fixing the container issue and help with your PR if needed.

**Comment by jgallucci32** [comment]
My third option of symbolic links with a configMap is out. Kubernetes mounts configMaps volumes as read-only by design. See https://github.com/kubernetes/kubernetes/issues/62099 for more details.

The more I dig into this the less I understand the need for the niche use case of unique certificates per replica. Kubernetes is designed to scale applications through replica sets and they need to be stateless. By creating a unique cert per replica set the app is no longer stateless and will only be able to scale by the number of pre-determined certs which have been configured. This goes against the principles of Kubernetes replicas which is why I feel like I keep running into these limitations.

Considering the container itself was non-functional until recently, I do not expect there to be any impact as it wasn't possible to configure Keycloak on K8s in this manner (it still technically isn't until we fix it with a PR). My recommendation is to update the instructions to specify only a single ssl cert/key pair as the server SSL cert rather than have one per replica.

**Comment by jgallucci32** [comment]
@FraPazGal Please take a look at my PR when you get a chance. I decided to go with the simplified approach to show exactly what the fixed chart would look like using a single TLS cert. My thought was since multiple TLS certs is not working now anyways, if we take this approach and if it is actually needed it can be fixed in a different PR at a later time.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know! We will check the PR

**Comment by jgallucci32** [comment]
@FraPazGal One minor change is required to tie in the two issues (helm chart issue + docker image issue) to make TLS fully capable. The image needs to be bumped from `r59` to at least `r63`. For now I can easily patch it and verified it work as intended with the recent PR. If there are near-term plans to bump the image version we can either way or create a new PR to do it now.

Also very minor, the env var `MY_INSTANCE_NAME` was not removed from the init container. It does nothing but waste code space. Was thinking we could yank it out when the container version gets bumped.

**Comment by javsalgar** [comment]
Hi! I just triggered a release of the keycloak chart. Once released, it should have the latest container with the requested feature. I will take a look to the extra env var as well.

**Comment by jgallucci32** [comment]
@javsalgar I just tested 1.4.3 chart version with `r81` image release and it works as expected. Thanks!

**Comment by javsalgar** [comment]
Awesome! Thanks for letting us know
