### ISSUE TITLE
MariaDB ARM64 version

### ISSUE THREAD

**Issue by airmonitor** [bitnami/charts#4825]
**Which chart**:
mariadb

**Describe the solution you'd like**
Installing your version of nextcloud on my k8s cluster based on rpi 4 can succeed when using mariadb as a database :)

**Comment by FraPazGal** [comment]
Hello @airmonitor,

Currently, our containers do not support the arm64 architecture. We are aware of the growing interest in this architecture and there are ongoing internal discussions regarding a possible support for it, but there is no fixed decision yet.

There is not a simple way to support it. A possible way is to build the container on your own: get a Debian or any distro that supports arm64 and you can download the binaries for arm64 from https://github.com/etcd-io/etcd/releases Then would be required to configure it, but that is basically building the container from scratch.

**Comment by criscola** [comment]
I would be interested in having this, we can now create very cheap clusters with a few raspberry pi 4 8gb and k3s or microk8s.

**Comment by alemorcuq** [comment]
Thanks for the feedback, @criscola. This is in our roadmap. Thanks to the community, we recently merged a PR adding ARM support to our minideb images: https://github.com/bitnami/minideb/pull/90

**Comment by morganchristiansson** [comment]
Using mariadb upstream image fails with:
```
2021-04-05 18:17:27+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
        You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```
this chart provides MARIADB prefixed env var
```    Environment:
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'redmine-mariadb'>  Optional: false
```

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
