### ISSUE TITLE
[bitnami/tomcat] updateStrategy not working as described

### ISSUE THREAD

**Issue by mrgasco** [bitnami/charts#4829]
Commets are incorrect in values.yaml
values can be overridden just as such

```
## Strategy to use to update Pods
##
## Can be set to RollingUpdate or Recreate
updateStrategy: RollingUpdate
```

**Comment by marcosbc** [comment]
Hi @mrgasco, those are the correct options, see this for more info: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

Note sure what you mean by this though:

>  values can be overridden just as such

To specify a different value, just modify the values.yaml file, or deploy with the `--set updateStrategy=RollingUpdate` option. If you specify a wrong value, then the deployment will fail.

**Comment by mrgasco** [comment]
The issue is: master branch is not showing actual values.yaml that is located on bitnami/tomcat!
I have done helm pull bitnami/tomcat and compared with values.yaml on bitami tomcat master branch and values.yaml are not the same. Is this your purpose choise? Is this explained in documentation?

**Comment by marcosbc** [comment]
Hi @mrgasco, unfortunately I could not reproduce your issue:

```console
$ wget https://raw.githubusercontent.com/bitnami/charts/master/bitnami/tomcat/values.yaml
$ helm pull bitnami/tomcat
$ tar xzf tomcat-8.0.0.tgz
$ diff values.yaml tomcat/values.yaml && echo 'No differences found!'
No differences found!
```

It could be that you have not updated your Helm chart repo, to do this run the below command:

```
$ helm repo update
```

**Comment by mrgasco** [comment]
You were right, sorry i did not update the chart. I close the issue Thanks
