### ISSUE TITLE
[bitnami/thanos] Error installing thanos charts

### ISSUE THREAD

**Issue by sb1975** [bitnami/charts#4837]
**Which chart**:
thanos

**Describe the bug**

Below pods stay in Crashloopbackoff
 `$ kubectl get pods
NAME                                     READY   STATUS             RESTARTS   AGE
grafana-5856ddf954-2vnb4                 1/1     Running            0          15m
thanos-bucketweb-697dc5bf84-7c5qr        1/1     Running            0          16m
thanos-compactor-6c5499cb64-kqc9s        0/1     CrashLoopBackOff   7          16m
thanos-minio-5cfd46d5c4-9qlp5            0/1     CrashLoopBackOff   7          16m
thanos-query-7c6468ccf4-77pwb            1/1     Running            0          16m
thanos-query-frontend-555476fbdc-vrfvm   1/1     Running            0          16m
thanos-ruler-0                           1/1     Running            0          16m
thanos-storegateway-0                    0/1     CrashLoopBackOff   7          16m`

$ kubectl describe pod/thanos-minio-5cfd46d5c4-9qlp5
..
Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Warning  FailedScheduling        16m (x3 over 16m)   default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               16m                 default-scheduler        Successfully assigned default/thanos-minio-5cfd46d5c4-9qlp5 to gke-data-aggregator-default-pool-7ac003ca-899v
  Normal   SuccessfulAttachVolume  16m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-d9a59df1-fc1d-4c1d-bb6f-3c359b2b12d1"
  Normal   Pulling                 16m                 kubelet                  Pulling image "docker.io/bitnami/minio:2020.12.12-debian-10-r0"
  Normal   Pulled                  15m                 kubelet                  Successfully pulled image "docker.io/bitnami/minio:2020.12.12-debian-10-r0"
  Warning  Unhealthy               15m (x3 over 15m)   kubelet                  Liveness probe failed: Get http://10.4.1.14:9000/minio/health/live: dial tcp 10.4.1.14:9000: connect: connection refused
  Warning  Unhealthy               15m (x4 over 15m)   kubelet                  Readiness probe failed: dial tcp 10.4.1.14:9000: connect: connection refused
  Normal   Created                 14m (x4 over 15m)   kubelet                  Created container minio
  Normal   Started                 14m (x4 over 15m)   kubelet                  Started container minio
  Normal   Pulled                  14m (x3 over 15m)   kubelet                  Container image "docker.io/bitnami/minio:2020.12.12-debian-10-r0" already present on machine
  Warning  BackOff                 58s (x70 over 15m)  kubelet                  Back-off restarting failed container

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:
- Output of `kubectl version`:

``$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4901", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-11-06T18:22:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}`
(paste your output here)
```


```
(paste your output here)
```

**Additional context**
Add any other context about the problem here.

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. Could you specify the values you used for installing the chart?
