### ISSUE TITLE
Introduce Tempo chart

### ISSUE THREAD

**Issue by jjangga0214** [bitnami/charts#4838]
[Tempo](https://github.com/grafana/tempo) is an open-source distributed tracing backend, recently announced by Grafana.

I think it'd be good if its chart is introduced.

Reference chart is implemented [here](https://github.com/grafana/tempo/tree/master/operations/helm) with separate [example docs](https://github.com/grafana/tempo/tree/master/example/helm).

How do you think?

Thanks.

**Comment by beltran-rubo** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time. Any contributions to this repository will be also welcome.

**Comment by carrodher** [comment]
I'm closing this issue since we already added Grafana Tempo to the Bitnami Helm Charts, catalog. See https://github.com/bitnami/charts/tree/master/bitnami/grafana-tempo
