### ISSUE TITLE
redmine with helm ingress error

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/charts#4840]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
 There is a problem with ingress when I use ingress: true in helm chart
 Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]

**Comment by javsalgar** [comment]
Hi,

Could you please check this PR? It tries to address the issues using our common library https://github.com/bitnami/charts/pull/4850

**Comment by thanhtai9606** [comment]
thank for you reply!

**Comment by thanhtai9606** [comment]
It doesn't work. I tried it again but it not working??
`helm install redmine -n kubeapps bitnami/redmine -f sources/apps/redmine/1.redmine-values.yaml 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]`

**Comment by andresbono** [comment]
Thanks @thanhtai9606, we will be releasing a new version of the chart to fix the issue.

**Comment by thanhtai9606** [comment]
> Thanks @thanhtai9606, we will be releasing a new version of the chart to fix the issue.
Thank you so much

**Comment by marcosbc** [comment]
Hi, this issue should have been fixed some months ago, so I'm proceeding to close it.
