### ISSUE TITLE
[bitnami/discourse] sendmail not present

### ISSUE THREAD

**Issue by mattcg** [bitnami/charts#4845]
**Which chart**:

discourse chart 2.0.3

**Describe the bug**

Scheduled emails are marked as sent in Discourse's own logs but are never delivered. Looking at the log viewer in `/logs/`, I can see `Job exception: Broken pipe` around the time the emails were supposed to be sent. The last line of the stack trace is `/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:64:in `write'`. A look at the code of the mail gem shows that this is where mail shells out to the `sendmail` executable. The executable, however, is not in the default location of `/usr/sbin/sendmail`.

**To Reproduce**

1. Install Discourse using the Bitnami helm chart.
2. Configure SMTP delivery.
3. Confirm that an email can be sent by using the Discourse function to send a test email to yourself.
4. Grand admin to an existing user, which should trigger a scheduled/queued email in Sidekiq.
5. The email is never delivered and an error is shown in the logs.

**Additional context**

Regardless, shouldn't it be possible to configure the mail gem to send mail using direct SMTP rather than sendmail? If so, how does one do this?

**Comment by mattcg** [comment]
This same issue was previously raised in a comment on another issue: https://github.com/bitnami/charts/issues/3035#issuecomment-659222087.

**Comment by alemorcuq** [comment]
Hi, @mattcg. Did you configure SMTP in the Sidekiq as well?

**Comment by mattcg** [comment]
hi Ale, this is what I have in my values YAML for discourse:
![image](https://user-images.githubusercontent.com/282964/103299936-00456200-49fe-11eb-8c89-36744b178160.png)
Scrolling down further, this is the sidekiq section:
![image](https://user-images.githubusercontent.com/282964/103299972-17844f80-49fe-11eb-93c7-16970fa2d139.png)
When I `cat /opt/bitnami/discourse/conf/discourse.conf` in the discourse pod, I can see that `smtp_address` is set to the correct host and all of the other SMTP vars are set correctly. I assume that sidekiq should be using these variables.

**Comment by alemorcuq** [comment]
According to the documentantion of the `bitnami/discourse` container (https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration), you need to set the SMTP variables for both `discourse` and `discourse-sidekiq`.

**Comment by mattcg** [comment]
Thanks for pointing that out. Done. I'll report back on whether this works or not before closing the issue.

**Comment by mattcg** [comment]
That did it! Thank you.
