### ISSUE TITLE
bitnami/elasticsearch

### ISSUE THREAD

**Issue by Doreamans** [bitnami/charts#4848]
chart:13.05
elasticsearch

**Is your feature request related to a problem? Please describe.**
I use this chart to deploy a cluster of es+kibana,and i add   xpack.security.enabled: true  ,but it doesn't work.I don't know how to make it work.
Can you give me some help?
Thanks!

**Comment by rafariossaa** [comment]
Hi,
  Could take a look to https://github.com/bitnami/charts/issues/3208 ?

**Comment by Doreamans** [comment]
> 
> 
> Hi,
> Could take a look to #3208 ?

OK. Thanks !
