### ISSUE TITLE
[bitnami/nginx-ingress-controller] Searching IngressClass is forbidden

### ISSUE THREAD

**Issue by kevin96666** [bitnami/charts#4851]
**Which chart**:
bitnami/nginx-ingress-controller:7.0.6

**Describe the bug**
nginx-ingress-controller pod can't search for ingressclass

Searching IngressClass" err="ingressclasses.networking.k8s.io "nginx" is forbidden.
 

> User "system:serviceaccount:default:nginx-ingress-controller" cannot get resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

**To Reproduce**
1. Install the chart
2. See error in the nginx-ingress-controller pod logs

**Expected behavior**
User "system:serviceaccount:default:nginx-ingress-controller" to be able to get resource ingressclasses

**How to fix**
Add rules for ingressclasses in nginx-ingress-controller/templates/clusterrole.yaml ?

**Comment by alemorcuq** [comment]
Hi, @kevin96666. Thanks for reporting this. I will create a PR fixing it.
