### ISSUE TITLE
[bitnami/nginx] Add geoIP module to nginx

### ISSUE THREAD

**Issue by DanTulovsky** [bitnami/charts#4857]
**Which chart**: nginx

**Is your feature request related to a problem? No

**Describe the solution you'd like**
nginx populates the geoip_country_code variable.

**Additional context**

I am looking for a way to add the https://docs.nginx.com/nginx/admin-guide/dynamic-modules/geoip2/ module into the nginx helm chart. Is this possible?   One way I guess is to create my own nginx image and override the one that the chart uses.

thank you!
dan

**Comment by marcosbc** [comment]
Hi @DanTulovsky, GeoIP is already included in `bitnami/nginx`:

```
$ nginx -V | grep geoip
configure arguments: ... --with-http_geoip_module ...
```

In `/opt/bitnami/nginx/modules/` you will find these files:

```
$ ls /opt/bitnami/nginx/modules/
ngx_http_geoip2_module.so  ngx_stream_geoip2_module.so
```

And to enable it, you would add something like `load_module modules/ngx_http_geoip2_module.so;` to your `nginx.conf` configuration.

Hope it helps!

**Comment by DanTulovsky** [comment]
Thank you.  It doesn't seem to be possible to add the load statement using the bitnami helm chart though. The docs say:

"To load the module into NGINX Plus, add the load_module directive in the top‑level (main) context of your nginx.conf configuration file (not within the http or stream context):"

server_blocks are included inside the http {} stanza.  Is there a way, using the helm chart, to add top level config directives?

On Wed, Dec 30, 2020, at 3:57 AM, Marcos Bjoerkelund wrote:
> 

> Hi @DanTulovsky <https://github.com/DanTulovsky>, GeoIP is already included in `bitnami/nginx`:

> `$ nginx -V | grep geoip
configure arguments: ... --with-http_geoip_module ...
`
> In `/opt/bitnami/nginx/modules/` you will find these files:

> `$ ls /opt/bitnami/nginx/modules/
ngx_http_geoip2_module.so  ngx_stream_geoip2_module.so
`

**Comment by marcosbc** [comment]
You could always try and mount the `nginx.conf` configuration file using [`extraVolumes`/`extraVolumeMounts`](https://github.com/bitnami/charts/blob/master/bitnami/nginx/values.yaml#L285).

**Comment by DanTulovsky** [comment]
Yes, I was considering that.. just wondering if I am missing something simple.. perhaps the chart can be improved to allow setting arbitrary values at the top level as wel...

**Comment by marcosbc** [comment]
For now it is not supported by the chart, but feel free to contribute with a PR if you have any idea on how to make it simpler, we'd be glad to help with the review and release of the chart.

**Comment by DanTulovsky** [comment]
Just to be clear, the database itself is also not shipped as part of the image and the chart does not provide any way to add it?

**Comment by DanTulovsky** [comment]
Oh, for those that might be here for the same reason, to mount nginx.conf as an extra volume:

```
extraVolumes:
  - name: nginx-conf-volume
    configMap:
      name: nginx-conf
      items:
        - key: nginx.conf
          path: nginx.conf
extraVolumeMounts:
  - name: nginx-conf-volume
    mountPath: /opt/bitnami/nginx/conf/nginx.conf
    subPath: nginx.conf
```

And the following will install the config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: web
data:
  nginx.conf: |
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
    # user              www www;  ## Default: nobody;

    load_module modules/ngx_http_geoip2_module.so;
    load_module modules/ngx_stream_geoip2_module.so;

    worker_processes  auto;
    error_log         "/opt/bitnami/nginx/logs/error.log";
    pid               "/opt/bitnami/nginx/tmp/nginx.pid";

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status  $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    "/opt/bitnami/nginx/logs/access.log";
        add_header    X-Frame-Options SAMEORIGIN;

        client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
        proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
        fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
        scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
        uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        off;
        gzip               on;
        gzip_http_version  1.0;
        gzip_comp_level    2;
        gzip_proxied       any;
        gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
        keepalive_timeout  65;
        ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers        HIGH:!aNULL:!MD5;
        client_max_body_size 80M;
        server_tokens off;

        include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";

    }
```

**Comment by marcosbc** [comment]
> Just to be clear, the database itself is also not shipped as part of the image and the chart does not provide any way to add it?

Using NGINX's GeoIP2 module requires some additional files to be generated for your specific setup, for more info see this: https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-by-geoip/

Unfortunately the databases are not pre-downloaded, and there is no flag to enable them in NGINX configuration. However, by mounting NGINX configuration files and the database files, it should be enough to get started.
