### ISSUE TITLE
[bitnami/postgresql-ha] can't set pgpool's child_life_time to 0 with pgpool.childLifeTime chart's setting.

### ISSUE THREAD

**Issue by GytisT** [bitnami/charts#4864]
**Which chart**:
bitnami/postgresql-ha (6.3.3)

**Describe the bug**
It is impossible to set pgpool's `child_life_time` setting to 0 with `Values.pgpool.childLifeTime`, which is considered a valid value by pgpool. This is because of a flaw in `templates/pgpool/deployment.yaml`. Specifically this part:
```
{{- if .Values.pgpool.childLifeTime }}
    - name: PGPOOL_CHILD_LIFE_TIME
        value: {{ .Values.pgpool.childLifeTime | quote }}
{{- end }}
```
I am guessing that 0 gets converted to false and everything inside the block gets skipped.

**To Reproduce**

1. Install chart with setting pgpool.childLifeTime set to 0

**Expected behavior**
pgpool's setting child_life_time to be set to 0 with chart's setting pgpool.childLifeTime set to 0.

**Comment by marcosbc** [comment]
Hi @GytisT, thanks for reporting this. You seem to be right as the chart would not detect value 0. This could probably work:

```
{{- if or .Values.pgpool.childLifeTime (eq "0" .Values.pgpool.childLifeTime) }}
```

Since you found the issue, it would be great if you contributed the fix. We're always open for external contributions via PRs and would be glad to help with the code review and release. Would you be up for it?

**Comment by rafariossaa** [comment]
Hi,
  I have just merged a change to fix this issue, could you give it a try ?

**Comment by rafariossaa** [comment]
Hi @GytisT ,
  Did you have any change to check this after the merge ?

**Comment by rafariossaa** [comment]
Hi,
  Due to the lack of feedback in a while I am closing this issue. 
  Please, don't hesitate to reopen it if needed.
