### ISSUE TITLE
[bitnami/wordpress] customise caching options

### ISSUE THREAD

**Issue by huang-jy** [bitnami/charts#4871]
**Which chart**:
The name (and version) of the affected chart.
Wordpress (latest)

**Is your feature request related to a problem? Please describe.**
While checking the chart out, I noticed the logs mention Varnish being setup when the pod starts up. Does the chart (or Wordpress itself) have caching enabled, or is Varnish doing the caching? If so, can we have an option to configure the caching rules?

**Describe the solution you'd like**
Options to configure caching (or mounting a config map with the caching rules)

**Describe alternatives you've considered**
CDN in front of the application (Cloudfront/Google CDN/Fastly)

**Additional context**

**Comment by andresbono** [comment]
Hi @huang-jy, the caching that the chart supports out-of-the-box is based on opcache. The WordPress plugin [w3-total-cache](https://wordpress.org/plugins/w3-total-cache/) is also included in the container (but not activated by default). This plugin can be used to configure several CDNs. Is that what you are looking for?

**Comment by huang-jy** [comment]
I thought so too, but w3-total-cache throws a series of errors and complains it cannot update files when activated, asking for changes to be made manually, so seems like something is not configured correctly.

**Comment by andresbono** [comment]
We don't allow writes in the config.php by default, so that's the issue. You can do the following:

1. Activate the plugin.
2. Grant write permissions for the user in `wp-config.php`:

```
kubectl exec -it wp-wordpress-5776fdf68f-bgzhw -- chmod u+w /bitnami/wordpress/wp-config.php
```

3. Go to the settings of the plugin /wp-admin/admin.php?page=w3tc_general and verify there are no errors now
4. Revert the permissions of the `wp-config.php` file:
```
kubectl exec -it wp-wordpress-5776fdf68f-bgzhw -- chmod u-w /bitnami/wordpress/wp-config.php
```

Let us know if this works for you.

**Comment by huang-jy** [comment]
Would the permissions change reset if the pod is deleted/restarted/evicted?

**Comment by andresbono** [comment]
No, that shouldn't be an issue because the `wp-config.php` file is persisted in a volume.

**Comment by huang-jy** [comment]
Great. I will give that a go later and report back, thanks!

**Comment by huang-jy** [comment]
Thanks, this also fixed some other issues I had, like with the "media offloader" plugin where they recommended putting the AWS keys in the config file.

**Comment by andresbono** [comment]
That's great to hear, @huang-jy!!
