### ISSUE TITLE
[ghost] replicaCount value is not used, unable to set replicaCount for deployment

### ISSUE THREAD

**Issue by sculley** [bitnami/charts#4872]
ghost:11.2.0

replicaCount is listed as a parameter in the ghost [README](https://github.com/bitnami/charts/tree/master/bitnami/ghost#ghost-parameters) but not used in the [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/ghost/values.yaml) meaning we can't set how many replicas the deployment should have.

We should be able to set the `replicaCount` value using the command line flag or by updating the `values.yaml`

```shell
helm install ghost bitnami/ghost --set replicaCount=3
```

```
$cat values.yaml
..
## Number of ghost replicas to deploy
replicaCount: 1
..
```

**Comment by alemorcuq** [comment]
Good catch, thanks for the PR!
