### ISSUE TITLE
[bitnami/cassandra] Multiple Rack Support

### ISSUE THREAD

**Issue by jemantheiy** [bitnami/charts#4874]
**Which chart**:
bitnami/cassandra

**Is your feature request related to a problem? Please describe.**
Like the orange helm chart, they have rack awareness and topology description build it.  Be nice to have this with Bitnami for a few reasons:

1.  All the helm charts I use are bitnami.
2. You guys do a great job of keeping charts mature and optimize.
3.  Only add to the value of the Cassandra helm chart.  
4. Adds to the high availability and disaster recovery of Cassandra

**Describe the solution you'd like**
I add labels to my k8s nodes for what rack they are, then I do the following in the yaml:

topology:
rack:
  name: 1
  label: rack/1

Etc.  Then when I deploy, pods get their rack awareness from the label and know what rack they are.  So replication and network topology work as expected.

**Describe alternatives you've considered**

Orange casskop but it's still very raw and immature.  Lots of bugs and issues I've found thru two different versions.  And they use custom images.  

Other charts just aren't as mature.  
**Additional context**

**Comment by marcosbc** [comment]
Hi @jemantheiy, thanks for the suggestion! I'm not sure how this would work in a Helm chart, as it's supposed to deploy a template with set characteristics.

Maybe you could workaround this by deploying one Helm chart per rack via [nodeAffinityPreset](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml#L319)?

**Comment by jemantheiy** [comment]
what could be done is in the cluster section of the values, we could set rackByLabel: cassandra/rack or some other customer k8s label.  Then it pulls that label to determine the rack.  This way on creation of the pod, it can set the rack its on and replication can be rackware and do more fault tolerant rack awareness like keyspace test token 2 is replicated on node 1 rack 1, node 2 rack 2 and node 3 rack 3.  

I tried node affinity but couldn't set the rack in cassandra.yaml.

**Comment by marcosbc** [comment]
Hi @jemantheiy, if it could be implemented it would certainly be great, however I have my concerns over if this is even compatible with Helm charts.

As for node affinity, note that what I'm mentioning in my previous comment is that it would be necessary to deploy one chart per-DC and per-rack (i.e. if you have 2 DC and 3 racks -> 6 Helm deployments), and to configure node affinity to only deploy to the node that contains the specific label for each rack. It is not the best / optimal solution but may work for your use case.
