### ISSUE TITLE
[bitnami/redis] useradd: Permission denied

### ISSUE THREAD

**Issue by Mutantt** [bitnami/charts#4882]
**Which chart**:
bitnami/redis

**Describe the bug**
permission denied for useradd

**To Reproduce**
just use default values for the chart.use one redis pod without any slave

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
i see below error when i check the redis logs . is this ok or i must change something to solve this error?

useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
chown: invalid user: 'redis'

**Comment by juan131** [comment]
Hi @Mutantt 

The Redis chart uses by default the Bitnami Redis container, which is a non-root container by default. See:

- https://github.com/bitnami/bitnami-docker-redis#why-use-a-non-root-container

Therefore, privileges action cannot be performed in the container unless you modify the security context of the Redis statefulset.

Just curious, why would you like to add a new user in a container such as this? No new user should be required.

**Comment by Mutantt** [comment]
hi
i dont want to add any user,i just installed the chart with below values:

cluster:
  enabled: false
usePassword: false
metrics:
  enabled: true
master:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m

**Comment by Skaronator** [comment]
I have the same issue when trying to upgrade from 12.1.1 to 12.3.0.

**Comment by juan131** [comment]
Hi @Mutantt @Skaronator 

I'm unable to reproduce the issue, are you modifying the default Pod/Container Security Context while installing/upgrading the Redis chart? I mean, are you setting any value in the `securityContext` or `containerSecurityContext` parameters or are you using the default ones?

The only reason I can find for the image to execute a `useradd` command is that you're running the container as "root", see the line below:

- https://github.com/bitnami/bitnami-docker-redis/blob/master/6.0/debian-10/rootfs/opt/bitnami/scripts/redis/setup.sh#L21

However, that shouldn't apply unless you modify the Security Context(s).

**Comment by Mutantt** [comment]
thank you for your reply,i have tested the chart on two different environment(minikube and production like env) and the result was same. i shared the value file that i used so i didnt change the security context,eveything is default except those values that iv shared.i see other ones logs also have these three lines,you can check below links:(issue: 4805 & 4819)
https://github.com/bitnami/charts/issues/4805
https://github.com/bitnami/charts/issues/4819

**Comment by Skaronator** [comment]
Hi,

I don't set any security context. Here is my values.yaml

```yaml
password: xxx

cluster:
  enabled: true
  slaveCount: 3

slave:
  resources:
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 32Mi

sentinel:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 32Mi

volumePermissions:
  enabled: true

podDisruptionBudget:
  enabled: true
```

I just tried upgrading again from 12.1.1 to 12.3.1 and this is the log of one of the new pods:

```
$ k logs docker-cache-redis-node-2 redis
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
chown: invalid user: 'redis'
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
```

Sentinel logs looks fine. Just 2 warnings:
```
$ k logs docker-cache-redis-node-2 sentinel
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
```

I did search in the code but couldn't find anything which could cause issues between 12.1.1 and 12.1.2.


@Mutantt could you try to install the 12.1.1 version and see if that version works for you?

**Comment by juan131** [comment]
Hi @Skaronator @Mutantt 

I just found out this PR that explains very well the issue, and tries to propose a solution:

- https://github.com/bitnami/charts/pull/4820

I'll raise the priority to review/land this issue ASAP

**Comment by juan131** [comment]
The PR was merged, please give a try to the latest chart version @Skaronator @Mutantt 
The issue should be solved now.

**Comment by Mutantt** [comment]
hi
yes, i installed the latest chart without the issue,thank you for your help.
