### ISSUE TITLE
Cannot deploy rabbitmq using OpenShift restricted SCC

### ISSUE THREAD

**Issue by namloc2001** [bitnami/charts#4884]
**Which chart**:
I'm using rabbitmq-8.0.2.tar, which is specified as a requirement of OWASP DefectDojo Helm chart (https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/requirements.yaml).

**Describe the bug**
I was previously using rabbit-6.18.2.tar and was able to set a value in the parent chart (DefectDojo) to override the security Context being set in the rabbitmq sub-chart. I could set `securityContext.enabled=false` in the parent chart and thus not use `fsGroup: 1001` nor `runAsUser: 1001` when deploying the chart:
```
securityContext:
  enabled: false
  fsGroup: 1001
  runAsUser: 1001
  extra: {}
```

This allows me to deploy in OpenShift, using the restricted SCC which automatically assigns an arbitrary (and non-root) UID to the container.

Since trying the deployment with 8.0.2 (and I've checked this still applies to the latest rabbit chart (8.6.1)) I cannot override this setting from the parent chart, as the rabbit values.yaml has been updated to:
```
podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
```

**To Reproduce**

1. Deploy chart to OpenShift, using a serviceAccount that is only permitted to use the restricted SCC
2. View the stateful set: `oc describe sts <name>` and see following event:
```
create Pod defect-dojo-rabbitmq-0 in StatefulSet defect-dojo-rabbitmq failed error: pods "defect-dojo-rabbitmq-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000640000, 1000649999]]
```

**Expected behavior**
I expect to be able to enable/disable the securityContext of rabbitmq both within rabbitMQ chart, and parent chart.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+ac53d20", GitCommit:"ac53d20", GitTreeState:"clean", BuildDate:"2020-10-31T17:54:45Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Output of `oc version`:

```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server
kubernetes v1.18.3+ac53d20
```

**Comment by alemorcuq** [comment]
Hi, @namloc2001. Can't you just override those settings from the parent chart by declaring them in the `rabbitmq` section of the `values.yaml`?

**Comment by namloc2001** [comment]
Hi @alemorcuq I need to ***disable*** these settings, rather than change the UID/GID values, so I need to have access to a  `podSecurityContext.enabled` type setting. This is because I need OpenShift to automatically assign them from the UID block associated with the project I am deploying into (see "Support Arbitrary User IDs" [here](https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/creating_images/creating-images-guidelines) and also as per [here](https://docs.openshift.com/container-platform/3.6/admin_guide/manage_scc.html):
>The restricted SCC uses MustRunAsRange strategy for constraining and defaulting the possible values of the securityContext.runAsUser field. The admission plug-in will look for the openshift.io/sa.scc.uid-range annotation on the current project to populate range fields.

If, in parent values.yaml, I comment them out, such as:
```
rabbitmq:
  enabled: true
  replicaCount: 1
  ...
  podSecurityContext: {}
    #fsGroup: 1001
    #runAsUser: 1001
```

Then the parent chart doesn't override the rabbit subchart and I get:
```
create Pod defect-dojo-rabbitmq-0 in StatefulSet defect-dojo-rabbitmq failed error: pods "defect-dojo-rabbitmq-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000640000, 1000649999]]
```

Likewise, if I set the parent values.yaml as follows:
```
rabbitmq:
  enabled: true
  replicaCount: 1
  ...
  podSecurityContext:
    #fsGroup: 1001
    #runAsUser: 1001
```

I get the same message: `1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001` in the "`FailedCreate`" event, whereby the values are again taken from the rabbitmq subchart.

**Comment by alemorcuq** [comment]
What if you set `rabbitmq.podSecurityContext=null`?

```
❯ helm template bitnami/rabbitmq --set podSecurityContext={} | grep securityContext | wc -l
       1

❯ helm template bitnami/rabbitmq --set podSecurityContext=null | grep securityContext | wc -l
       0
```

**Comment by namloc2001** [comment]
Hi @alemorcuq I just tried this and same result:
```
create Pod defect-dojo-rabbitmq-0 in StatefulSet defect-dojo-rabbitmq failed error: pods "defect-dojo-rabbitmq-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000640000, 1000649999]]
```

**Comment by namloc2001** [comment]
@alemorcuq - I just spotted I hadn't used to the correct `--set` value in my `helm install...` command. I've now used:
```
helm install defect-dojo --set rabbitmq.podSecurityContext=null ./
```

And it appears to be deploying.

**Comment by namloc2001** [comment]
@alemorcuq so I have to do:
```
helm install defect-dojo --set rabbitmq.podSecurityContext=null ./
```

with a values.yaml of:
```
rabbitmq:
  enabled: true
  replicaCount: 1
  ...
  podSecurityContext:
    #fsGroup: 1001
    #runAsUser: 1001
```

I.e. with `fsGroup` and `runAsUser` commented out.

**Comment by Javid907** [comment]
@namloc2001 Hi.  Could you find fix for these issue?

**Comment by namloc2001** [comment]
@Javid907 the only way I can get this to work is as per my previous comment, so I think this basically offers up two options regarding the list of keys/values in parent values.yaml chart:

**Option A:** Make `fsGroup` and `runAsUser` accessible in parent values.yaml but comment them out so that `--set rabbitmq.podSecurityContext=null` can be used in `helm install command`.
```
rabbitmq:
  enabled: true
  replicaCount: 1
  ...
  podSecurityContext:
    #fsGroup: 1001
    #runAsUser: 1001
```

**Option B:** Don't include the `rabbitmq.podSecurityContext` key in parent chart, and then clarify in documentation that installer needs to use the `--set rabbitmq.podSecurityContext=null` override if required.

In my opinion neither mechanism is very clean. The Bitnami PostgreSQL chart handles this in a much cleaner way, using the `enabled` key. I would request rabbitmq is updated to bring back the securityContext configuration that we had access to in 6.18.2.

**Comment by alemorcuq** [comment]
Doesn't setting the `values.yaml` to:

```
rabbitmq:
  enabled: true
  replicaCount: 1
  ...
  podSecurityContext: null
```

work as well?

**Comment by namloc2001** [comment]
Hi @alemorcuq it may well do, but we have to leave the default settings in the parent chart (DefectDojo) for "the masses", i.e. those deploying to K8s rather than OpenShift (via the restricted SCC).

But like I said, regardless of the way it is set as per the previous few comments, this is not a clean style, an `enabled` setting it much more deliberate/intentional and aligns with the postgreSQL chart from Bitnami.

**Comment by Javid907** [comment]
@namloc2001 Did you test with this config when persistent is enable ? 

rabbitmq:
  enabled: true
  replicaCount: 1
  ...
  podSecurityContext:
    #fsGroup: 1001
    #runAsUser: 1001

**Comment by namloc2001** [comment]
@Javid907 yes, the rabbit chart has persistence enabled and we didn't overwrite it.

**Comment by Javid907** [comment]
@namloc2001 Did you try these values?

podSecurityContext: null
#fsGroup: 1001
#runAsUser: 1001

**Comment by alemorcuq** [comment]
I agree with you, @namloc2001, this is not as clean. I will create a PR adding the `enabled` toggle.

**Comment by namloc2001** [comment]
@alemorcuq thanks very much.
