### ISSUE TITLE
[bitnami/metallb] invalid references to metallb.tplValue

### ISSUE THREAD

**Issue by ghudiczius** [bitnami/charts#4885]
**Which chart**:

bitnami/metallb, versions 2.0.0 - 2.0.2

**Describe the bug**

In case the speaker.nodeSelector is set in the values, helm templating fails with the following error message:
`Error: template: metallb/templates/speaker/daemonset.yaml:112:49: executing "metallb/templates/speaker/daemonset.yaml" at <include "metallb.tplValue" (dict "value" .Values.speaker.nodeSelector "context" $)>: error calling include: template: no template "metallb.tplValue" associated with template "gotpl"`

**To Reproduce**

1. helm install --set speaker.nodeSelector=whatever some-name bitnami/metallb

**Expected behavior**

The chart should be installed with no error message displayed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce56", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

While I haven't checked it, the same issue is likely to happen if any of the following values are set:
- speaker.extraEnvVarsSecret (line 67)
- speaker.extraEnvVars (line 72)
- speaker.nodeSelector (line 112)
- speaker.affinity (line 116)

**Comment by juan131** [comment]
Thanks for reporting it, and the fix! I already accepted/merged your PR
