### ISSUE TITLE
[bitnami/cassandra] Unable to set commit logs and data directory to two different paths

### ISSUE THREAD

**Issue by jemantheiy** [bitnami/charts#4888]
**Which chart**:
bitnami/cassandra: latest
**Describe the bug**

I know you can set the data and commit logs by either $Cassandra_home env or not.  However, there isn't an easy way to set the commitlogs and data directories to different paths.  This is ideal for production Cassandra.  

**To Reproduce**

1. Set CASSANDRA_HOME in env
2. Add Extra Volume/Volume Mount to chart and set it to what Cassandra Home is.
3. You'll see you can set both data and commit logs to be the same spot but never different.  

**Expected behavior**
Be able to set commit logs seperate.  

**Version of Helm and Kubernetes**:
helm 3 version 1.15

**Comment by miguelaeh** [comment]
Hi @jemantheiy ,
thank you very much for the suggestion. I will create an internal task to add this feature.
It would be necessary to add the logic to modify the `commitlog_directory` configuration option to the image.

**Comment by andresbono** [comment]
Hi @jemantheiy,

`bitnami/cassandra 7.3.2` https://github.com/bitnami/charts/commit/33ee5f8f2bbefa39f98f544c5822b04d93214797 has updated the container images to include the changes required for this to work:
- https://github.com/bitnami/bitnami-docker-cassandra/pull/86
- https://github.com/bitnami/bitnami-docker-cassandra/pull/87

Please give it a try and let us know. Thanks again for the contribution to the container image!
