### ISSUE TITLE
[bitnami/mysql] any plan to support mysql shell and expose the default port 33060

### ISSUE THREAD

**Issue by sivasaiIT** [bitnami/charts#4890]
**Which chart**:
bitnami/mysql

**Is your feature request related to a problem? Please describe.**
As mysql server supports storing json document store. Can we expect support for mysql shell and x Protocol so that client applications can store NoSQL data using bitnami/mysql chart

**Additional context**
I am completely new to hosting databases in kubernetes. So If mysqlsh is already supported in this chart Can you please let me know how to test it

**Comment by alemorcuq** [comment]
Hi, @sivasaiIT.

At the momento there is no support for MySQL Shell in the container and there are no immediate plans to add it. We will evaluate it, but I can't give you an ETA.

**Comment by javsalgar** [comment]
Not stale
