### ISSUE TITLE
[Bitnami/cassandra] Property overrides

### ISSUE THREAD

**Issue by jemantheiy** [bitnami/charts#4895]
**Which chart**:
Bitnami/Cassandra

**Is your feature request related to a problem? Please describe.**
At the moment, its not easy to just override or add a config to the cassandra.yaml.  You have to override the entire file or use envs that are supported.  For example, I want to just add dynamic_snitch: false.  

**Describe the solution you'd like**
Set properties in an array field and then logic overrides or adds those to cassandra.yaml.  

**Describe alternatives you've considered**
-env in cassandra.yaml (breaks chart)
-special init script that isn't super straight forward.

**Comment by marcosbc** [comment]
Hi @jemantheiy, we usually only support the scenarios you mention.

In some cases we have also created a new environment variable for adding extra config lines to the configuration file, but it's not common. Instead we usually prefer if you mount the entire configuration file if you want to extend further.

In any case, you could always contribute the changes to support the new proposed scenario, we'd be glad to review and include these changes into Bitnami Docker images. You can find the source code for the initialization scripts of the Docker image in the [bitnami-docker-cassandra repo's `rootfs` directory](https://github.com/bitnami/bitnami-docker-cassandra/tree/master/3/debian-10/rootfs).
