### ISSUE TITLE
bitnami/solr helm chart

### ISSUE THREAD

**Issue by gkulkarni32** [bitnami/charts#4896]
**Which chart**:
New chart request for bitnami/solr

**Is your feature request related to a problem? Please describe.**
Currently we do not have a helm chart for solr, we see the need to have one.

**Describe the solution you'd like**
helm chart using the bitnami solr docker image

**Describe alternatives you've considered**
No chart from bitnami

**Additional context**

**Comment by beltran-rubo** [comment]
Thanks @gkulkarni32, this is already in our to-do list but any contribution or PR will be welcome to speed up the process.

**Comment by gkulkarni32** [comment]
Thanks @beltran-rubo 
Few questions on the solr chart: 
1. If I want to use a zookeeper along with this docker image for solr, what should be the environment variables that i should be setting? I dont see anything mentioned in the docker environment variables.
2. If i want to create a statefulset, where should i be mounting the data?

**Comment by beltran-rubo** [comment]
- Currently the Solr container does not support the configuration with Zookeeper but you can extend that container with a PR
- Not sure about the specific data you want to mount, but you can check other Charts and the approach we are following in the other Charts.
- We do not have a Solr metrics exporter yet, I assume we will use the official approach from Solr https://lucene.apache.org/solr/guide/7_3/monitoring-solr-with-prometheus-and-grafana.html
