### ISSUE TITLE
Typo in documentation about clustering rabbitmq

### ISSUE THREAD

**Issue by jeanpoelie** [bitnami/charts#4897]
**Which chart**:
Bitnami RabbitMQ chart

**Describe the bug**
It isn't really a bug more a documentation typo.
![image](https://user-images.githubusercontent.com/10237926/103762872-50817d00-5019-11eb-9e86-956f574cda27.png)

**To Reproduce**
Go to the url 
https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq
scroll down to clustering

**Expected behavior**
A different explaination for forceboot

**Comment by alemorcuq** [comment]
Thanks for reporting this. I will create a PR fixing it.
