### ISSUE TITLE
[bitnami/owncloud] unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend

### ISSUE THREAD

**Issue by blinkiz** [bitnami/charts#4907]
**Which chart**:
bitnami/owncloud 10.0.0

**Describe the bug**
When trying to deploy owncloud it fails with this error message.
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]`

**To Reproduce**
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install owncloud1234 bitnami/owncloud --version 10.0.0 --set "ingress.enabled=true"
```

**Expected behavior**
No error message

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```bash
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:
```bash
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:32Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This is related to #4866, #4899, #4791, #4870, #4859, #4889.
Probably missing is the same changes made in #4889 for bitnami/keycloak.

**Workaround**
Use ApiVersion.
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install owncloud1234 bitnami/owncloud --version 10.0.0 \
--set "ingress.enabled=true" --set "ingress.apiVersion=networking.k8s.io/v1beta1"
```

**Comment by FraPazGal** [comment]
Hello @blinkiz,

Thanks for the heads up! We will create a PR addressing this shortly. Until then, please keep using the workaround you found.

**Comment by viceice** [comment]
Same for phpmyadmin

https://github.com/bitnami/charts/blob/51b056ff67b99f9e98d7df6e618e01a8e31d0ff9/bitnami/phpmyadmin/templates/ingress.yaml#L29-L31

**Comment by FraPazGal** [comment]
Thank you for reaching out @viceice,

 The first batch was done in #4870, and we are pending for newer batches to be completed ATM. We expect to continue this week, thank you for your understanding!
