### ISSUE TITLE
[bitnami/redis] Add support for Redis Sentinel metrics

### ISSUE THREAD

**Issue by ricoberger** [bitnami/charts#4909]
**Which chart**:

redis (12.3.2)

**Is your feature request related to a problem? Please describe.**

When Redis is deployed with Redis Sentinel, it would be good to also get some Prometheus metrics for Redis Sentinel.

**Describe the solution you'd like**

Similar to the Redis metrics exporter this can be solved with the [leominov/redis_sentinel_exporter](https://github.com/leominov/redis_sentinel_exporter). When a user enables Redis Sentinel an additional sidecar with the Redis Sentinel Exporter image can be added.

This can be controlled by a new key named `metrics` under the `sentinel` section and similar options like the ones for the Redis Exporter.

**Describe alternatives you've considered**

Currently the Redis Sentinel Exporter must be deployed as additional component. This works, but isn't optimal.

**Additional context**

If this feature request is accepted, I can come up with a PR to add support for the Redis Sentinel Exporter.

**Comment by marcosbc** [comment]
Hi @ricoberger, great suggestion! We agree that this is something that makes a lot of sense.

Feel free to send the PR, in the meantime, we will work on creating the container image as described in our [Contributing Guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) so the new chart can be added to the Bitnami Charts catalog. I have also created an internal task for such purpose and tracking of this issue.

Thanks!

**Comment by ricoberger** [comment]
Hi @marcosbc, the PR is ready #4916.

Please let me know, when your image is ready, so that I can adjust the PR.

**Comment by marcosbc** [comment]
That's awesome, thanks! We're going to plan the addition of the new image shortly and will keep you posted with any update here or to #4916.

**Comment by ricoberger** [comment]
Hi @marcosbc, sorry for annoying you: Is there an update regarding the image for the Redis Sentinel Exporter?

**Comment by rafariossaa** [comment]
Hi @ricoberger ,
  I can tell that we are currently working on it, but I can't give an ETA.

**Comment by AbbasHallal** [comment]
Hello @rafariossaa, what is the status regarding this request?

**Comment by rafariossaa** [comment]
Hi,
  This was implemented, but later it was removed because the upstream exporter is not maintained:
https://hub.docker.com/r/bitnami/redis-sentinel-exporter
