### ISSUE TITLE
[bitnami/discourse] "Migrating database..." takes 15 minutes for tiny DB

### ISSUE THREAD

**Issue by mattcg** [bitnami/charts#4912]
Each time Discourse is restarted, it gets stuck on "Migrating database..." for what seems like a disproportionate amount of time (15m+). Our database is microscopic and the underlying system is powerful. Why is this migration step run each time the app is started?

Chart v2.0.3.

**Comment by miguelaeh** [comment]
Hi @mattcg ,
To be honest I don't know why it takes that long. What is executed behind the scenes is `ruby rake db:migrate`

**Comment by thomaswmanion** [comment]
I see the same thing. Any ideas?

**Comment by miguelaeh** [comment]
Hi @thomaswmanion ,
Are you persisting the data? The first discourse installation is very slow so in case you are not persiting the data the application will be reinstalled with each restart

**Comment by rohansingh** [comment]
I see the same behavior, using a external (persistent) Postgres instance as well as persistent volumes for storage. Haven't dug deeper than that, because it's not a show-stopper, but it does take about 7 minutes for an instance to be ready.

**Comment by miguelaeh** [comment]
Hi @rohansingh ,
As I commented, this is something expected in the first deployment since the application has to be installed. For the following ones, it should not take so long. Could you confirm this happens for every restart? Have in mind data must be persisted, if not the installation will be done again.

**Comment by rohansingh** [comment]
Yeah, we have data persisted to an external Postgres instance, as well as an NFS volume. This happens on every restart anyway.

Actually I realized it's a real issue when we got a spike in traffic last night. I scaled up the deployment but each additional replica took about 10 minutes to become usable.

**Comment by rohansingh** [comment]
Here's what the startup looks like by the way:

```
Welcome to the Bitnami discourse container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues

nami    INFO  Initializing postgresql-client
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at 10.75.1.2:5432
postgre INFO  PostgreSQL server listening and working at 10.75.1.2:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
discour INFO  Configuring Redis...
discour INFO  Setting up SMTP in Discourse...
discour INFO  Migrating database...
discour INFO
discour INFO  ########################################################################
discour INFO   Installation parameters for discourse:
discour INFO     Persisted data and properties have been restored.
discour INFO     Any input specified will not take effect.
discour INFO   This installation requires no credentials.
discour INFO  ########################################################################
discour INFO
nami    INFO  discourse successfully initialized
Starting discourse...
```

**Comment by rohansingh** [comment]
@miguelaeh Does the database migration actually need to be run at every startup? I don't see why it's necessary to always run it.

**Comment by AliMirlou** [comment]
I have the same issue @rohansingh is experiencing.
I'm persisting data on an OpenEBS volume with a reclaim policy of "Retain" and getting the same logs as him. Every time I have to restart the pod (for any reasons like scaling down to zero because of low resources and bringing it up later again), the database migration step takes a very long time.
It takes so much time that the readiness probe fails completely and the pod keeps getting restarted. I had to set the readiness initial delay to a very high value to make it work!

**Comment by miguelaeh** [comment]
>Does the database migration actually need to be run at every startup? I don't see why it's necessary to always run it.

Currently, I would say yes, there is not way to know if you are running a new installation or if it is the first. 
We could try to implement some logic to query the database, check if there is already data, and in the case that the database version is the same skip the upgrade.

**Comment by marcosbc** [comment]
Hi, FYI we just released a chart version, [4.0.0](https://github.com/bitnami/charts/tree/master/bitnami/discourse#to-400). The initialization logic has received a major refactor, and scripts for the container image are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

Could you check if this is still happening? If it is, could you enable `image.debug=true` and check the extra debug output for the migration step?

**Comment by mattcg** [comment]
This is what we're getting attempting to go from 2.1.1 to 4.0.0:

```
helm upgrade --history-max=5 --install=true --namespace=discourse --timeout=10m0s --values=/home/shell/helm/values-discourse-4.0.0.yaml --version=4.0.0 --wait=true discourse /home/shell/helm/discourse-4.0.0.tgz
checking 17 resources for changes
error updating the resource "discourse-redis-master":
	 cannot patch "discourse-redis-master" with kind StatefulSet: StatefulSet.apps "discourse-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error: UPGRADE FAILED: cannot patch "discourse-redis-master" with kind StatefulSet: StatefulSet.apps "discourse-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**Comment by mattcg** [comment]
After deleting the redis statefulSet, the upgrade succeeded and there was no database migration that took this long.

**Comment by tommaniongenmills** [comment]
How does that fix it @mattcg ? I wonder if that is just related to upgrading your chart
