### ISSUE TITLE
[bitnami/redmine] Can't run Repository.fetch_changesets

### ISSUE THREAD

**Issue by dfgrosso** [bitnami/charts#4914]
Hi everyone

According to https://www.redmine.org/projects/redmine/wiki/HowTo_setup_automatic_refresh_of_repositories_in_Redmine_on_commit I should be able to run the command bellow in order to refresh repos in redmine.

`ruby /path_to_redmine/redmine/script/rails runner "Repository.fetch_changesets" -e production > /dev/null 2>&1 &.`

However I can't seem to find a way to do this because I cannot find this runner script in this chart redmine's image.

Any help?

Thank you.

Regards,
Daniel

**Comment by alemorcuq** [comment]
The `rails` should be under `/opt/bitnami/redmine/bin`. Can you check it?

**Comment by dfgrosso** [comment]
Hello @alemorcuq 

Yes it is. Thank you. I was able to find it yesterday. I'll describe here what I needed to do to make it work. The problem is (since I'm not a RubyOnRails guy) I don't have a clue if the following steps could somehow harm the redmine application. 
Hopefully someone can doublecheck them.

1. Replaced the `/path_to_redmine/redmine/script/rails` with `/opt/bitnami/redmine/bin` and ran the command again

`ruby /opt/bitnami/redmine/bin runner "Repository.fetch_changesets" -e production`

( the initial "ruby" expression seems to be irrelevant)

This prints out the rails command usage info as if there's a problem on the syntax:

```
Usage:
  rails new APP_PATH [options]

Options: (...)
```

2. Put myself in `/opt/bitnami/redmine/bin` and wrote './rails' to get the usage again but this time I got more info

```
Beginning in Rails 4, Rails ships with a `rails` binstub at ./bin/rails that
should be used instead of the Bundler-generated `rails` binstub.

If you are seeing this message, your binstub at ./bin/rails was generated by
Bundler instead of Rails.

You might need to regenerate your `rails` binstub locally and add it to source
control:

 rails app:update:bin           # Bear in mind this generates other binstubs
                                          # too that you may or may not want (like yarn)
```

3. Ran `./rails app:update:bin` as instructed (without having a clue of what I was doing).
4. Got a prompt and replied "a" (as in always)

```
       exist  bin
    conflict  bin/bundle
Overwrite /opt/bitnami/redmine/bin/bundle? (enter "h" for help) [Ynaqdhm] a
       force  bin/bundle
    conflict  bin/rails
       force  bin/rails
    conflict  bin/rake
       force  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
```

5. Now the `/opt/bitnami/redmine/bin runner "Repository.fetch_changesets" -e production` command works fine.

Regards,
Daniel

**Comment by juan131** [comment]
Hi @dfgrosso 

Thanks so much for sharing you solved it! I'm sure it'll very helpful for other users.

Checking how the default scripts load/set the environment might also help you for the future, see: 

- https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/init.sh
- https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/run.sh
