### ISSUE TITLE
[bitnami/rabbitmq] Wrong v1 ingress spec

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#4920]
**Which chart**:
bitnami/rabbitmq (8.6.2)

**Describe the bug**
Deploying with ingress on k8s v1.20 failed with error message

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown me" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend
```

**To Reproduce**
1. enable ingress
2. deploy

**Expected behavior**
Successful deployment

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}```
```

**Additional context**

Wrong v1 ingress spec here (using v1beta1 spec):

https://github.com/bitnami/charts/blob/041428f73785a4a121cf3a6f8be6b70c5ba83cff/bitnami/rabbitmq/templates/ingress.yaml#L21-L24

Should be:
```
- path: {{ .Values.ingress.path }}
  pathType: Prefix
  backend:
    service: {{ template "rabbitmq.fullname" . }}
    port:
      name: http-stats
```

**Comment by alemorcuq** [comment]
Hi, @tbnguyen1407. We have an internal task where we are tracking the progress of this work. Unfortunately, due to winter holidays this has been delayed and could not be completed immediately.

Note: The first batch was done in #4870, and we are pending for newer batches to be completed ATM. We expect to continue early next week. If you need a fix sooner feel free to send a PR, we'd be happy to help with the review and release of the new chart(s).

**Comment by sergeyshaykhullin** [comment]
Fix https://github.com/bitnami/charts/pull/5007
