### ISSUE TITLE
rabbitmq parse error at (rabbitmq/templates/statefulset.yaml:1): unclosed action

### ISSUE THREAD

**Issue by huisebug** [bitnami/charts#4921]
I think this piece is very unfriendly. Just copy the example you provided, and I will add it myself. I always prompt you:
parse error at (rabbitmq/templates/statefulset.yaml:1): unclosed action

**Comment by huisebug** [comment]
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          },
          {
            "name": "LiveShow_Store",
            "password": "LiveShow_Store.MQ.PWD_123*",
            "tags": "monitoring"
          },
          {
            "name": "LiveShow_Fans",
            "password": "LiveShow_Fans.MQ.PWD_123*",
            "tags": "monitoring"
          } 
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "globalParameters": [
          {
            "name": "cluster_name",
            "value": "rabbitmq-ha"
          }
        ],
        "permissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "topicPermissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          }
        ]
      }

**Comment by huisebug** [comment]
`extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          },
          {
            "name": "LiveShow_Store",
            "password": "LiveShow_Store.MQ.PWD_123*",
            "tags": "monitoring"
          },
          {
            "name": "LiveShow_Fans",
            "password": "LiveShow_Fans.MQ.PWD_123*",
            "tags": "monitoring"
          } 
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "globalParameters": [
          {
            "name": "cluster_name",
            "value": "rabbitmq-ha"
          }
        ],
        "permissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "topicPermissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          }
        ]
      }  `

**Comment by huisebug** [comment]
`
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          },
          {
            "name": "LiveShow_Store",
            "password": "LiveShow_Store.MQ.PWD_123*",
            "tags": "monitoring"
          },
          {
            "name": "LiveShow_Fans",
            "password": "LiveShow_Fans.MQ.PWD_123*",
            "tags": "monitoring"
          } 
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "globalParameters": [
          {
            "name": "cluster_name",
            "value": "rabbitmq-ha"
          }
        ],
        "permissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "topicPermissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          }
        ]
      }  
`

**Comment by huisebug** [comment]
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          },
          {
            "name": "LiveShow_Store",
            "password": "LiveShow_Store.MQ.PWD_123*",
            "tags": "monitoring"
          },
          {
            "name": "LiveShow_Fans",
            "password": "LiveShow_Fans.MQ.PWD_123*",
            "tags": "monitoring"
          } 
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "globalParameters": [
          {
            "name": "cluster_name",
            "value": "rabbitmq-ha"
          }
        ],
        "permissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "topicPermissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          }
        ]
      }

**Comment by huisebug** [comment]
`
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          },
          {
            "name": "LiveShow_Store",
            "password": "LiveShow_Store.MQ.PWD_123*",
            "tags": "monitoring"
          },
          {
            "name": "LiveShow_Fans",
            "password": "LiveShow_Fans.MQ.PWD_123*",
            "tags": "monitoring"
          } 
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "globalParameters": [
          {
            "name": "cluster_name",
            "value": "rabbitmq-ha"
          }
        ],
        "permissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "topicPermissions": [
          {
            "user": "LiveShow_Store",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          },
          {
            "user": "LiveShow_Fans",
            "vhost": "/",
            "exchange": "",
            "write": ".*",
            "read": ".*"
          }
        ]
      }  


`

**Comment by huisebug** [comment]
extraSecrets:
  load-definition:
    load_definition.json: |


The content defined below is difficult to parse, and the parsed plug-ins need to be optimized

**Comment by FraPazGal** [comment]
Hello @huisebug,

Besides `extraSecrets`, you will also need to set a few others parameters. The example provided in `values.yaml` is a very basic snippet. For an extended guide, please refer to our [README](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions).

We are always happy to improve our solutions, could you please provide some more feedback on the proposed optimisations?

**Comment by huisebug** [comment]
Yes, I followed the readme file you provided, but I feel that the detection mechanism is very strong. I want to add a lot of content, even if it is very small, it is exactly the same as the readme file you provided, but I have to write it by hand. I am wrong

**Comment by FraPazGal** [comment]
Hello @huisebug,

I'm not sure I understand what your are referring to when you say detection mechanism, could you provide an example? You could also update the configuration using the UI, but you will need to write it by hand in both cases, it doesn't come to mind another way to do it.

**Comment by huisebug** [comment]
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": [
        {
          "name": "user",
          "password": "CHANGEME",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ]
    }
Finally, I used the method of passing the self built secret
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }

If let the chart create the secret is used, the component will always prompt me that the format is incorrect. I will create it completely according to the example, which shows that the detection mechanism of the component providing this method is very strong

**Comment by FraPazGal** [comment]
Hello @huisebug,

I tested your example and the chart is installed properly, without any error on my logs. Could you please share the error? Does it appear at chart installation time? Keep in mind that when using `extraSecrets` in `values.yaml`, it is being read as a template, so you need to maintain its format:

```yaml
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "user",
            "password": "CHANGEME",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```

**Comment by huisebug** [comment]
OK, this is mine value.yaml
[Uploading values.yaml…]()

**Comment by huisebug** [comment]
![image](https://user-images.githubusercontent.com/27762438/104298135-98634100-54fe-11eb-9b7c-d4612781840f.png)

I found that the problem is that {} is written in the provided example Values.auth.username }}, will prompt the error, the explanation is not allowed to write like this

**Comment by FraPazGal** [comment]
I tried the same `load_definition.json`, with `"name": "{{ .Values.auth.username }}" and "password": "{{ .Values.auth.password }}"` and there doesn't seem to be any errors. Are you setting the value of `auth.password`? By default this parameter's value is `nil`. You would need to set the password for your code to work like so:

```yaml
auth:
  ## RabbitMQ application username
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  username: user

  ## RabbitMQ application password
  ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
  ##
  password: changeme
```

**Comment by huisebug** [comment]
If I set it up, I will still report an error. I will give my answer value.yaml You can point me out

**Comment by huisebug** [comment]
[values.txt](https://github.com/bitnami/charts/files/5806253/values.txt)

**Comment by FraPazGal** [comment]
Hello @huisebug,

I was able to reproduce your issue with your `values.yaml`. It seems the configuration your are copying into the `yalm` has `\n` in it and that is causing the error. This seems to be an error with helm https://github.com/helm/helm/issues/6161 and there isn't much we can do to fix it. A solution to avoid having to rewrite all the configuration file in `values.yalm` could be to create the secret yourself using an already existing `load_definition.json` file:

```
$ kubectl create secret generic load-definition --from-file=load_definition.json
```

**Comment by huisebug** [comment]
Yes, I am using the method of external secret now, so I say that the detection mechanism of components is very strong. Do you want to ignore these symbols

**Comment by FraPazGal** [comment]
Hi,

I would say that this error comes from the helm bug that I previously linked, rather being the consecuence of a strong detection mechanism. 

I'm not entirely sure how a workaround would need to be implemented to fix this and, given that there is two methods to input the configuration, I would say that this can wait until Helm provides a fix. Nevertheless, we are always happy to include user additions, so if you want to tackle this feel free to create a PR, will review it as soon as possible.
