### ISSUE TITLE
[bitnami/redis-cluster] tuning cluster stability upon pod restart

### ISSUE THREAD

**Issue by cschockaert** [bitnami/charts#4926]
**Which chart**:
redis-cluster

**Is your feature request related to a problem? Please describe.**
Hello, pleased to see that redis-cluster chart is almost working as i expected. But after doing some chaos monkey, like deleting all pod in the cluster, i got in a situation where new redis pods with new (dynamic ips) could not rejoin the cluster.
Seems, that when i delete only one pod, the new one is rejoining fine (his new ip is correctly known from the other members) but when we delete more than one pod at once (ex scale sts to 3 pod, break the cluster, then go again to 6 pod)

**Describe the solution you'd like**
however i found a solution, i used the external access in an obvious way, to get redis working not with dynamically associated IP by k8S but using, static IP (allocated ONCE when a service is created):

![image](https://user-images.githubusercontent.com/8597973/104027158-48ffd680-51c7-11eb-9b35-95069b92b2a1.png)

Can you consider adding this feature more OOTB, coz i think im not using the chart as it would be normally used. (using external access with clusterIP mode :))

**Comment by andresbono** [comment]
Hi @cschockaert, I'm not really sure if I'm understanding the proposal. It seems like you are specifying that the service for external access is of type `ClusterIP`, but at the same time, you are trying to modify the `loadBalancerIP` field. However, as per the [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#servicespec-v1-core):


loadBalancerIP string | Only applies to Service Type: LoadBalancer [...]
-- | --

So it won't have any effect, right?

**Comment by cschockaert** [comment]
Hmm yes you are right, but after some more tests i found that my real problem was that when persistance is off, a new pod would not automatically join the redis cluster again (as stated in this issue https://github.com/bitnami/charts/issues/3933) 
i naively though that using a static service ip instead of pod dynamic ip in the redis announce ip would correct this thing but seems that it's not the case...

This chart is really nice, but would be great to easily control the cluster with just scaling up the statefulset, new pod would join automatically the cluster as slave node for example (or other..) and be able to control the cluster, add/remove node with for example an arbitrer pod with some usefulls scripts inside, and not rely on an helm upgrade doing a post upgrade job (which cannot be started again).

**Comment by cschockaert** [comment]
Saying that, coz helm is fine for fast install package on a k8s cluster, but so many teams are using helm package as dependency with requirement feature, and are updating the requirements not always with helm upgrade command but with live kubectl command in production. So be able to troubleshoot a redis-cluster with easy accessible command (without running helm again) would be a great add to this chart

**Comment by andresbono** [comment]
Hi @cschockaert, thanks for sharing your thoughts on the usability of the chart. Could you please share the sequence of commands that you would expect to work and they don't? I cannot guarantee it will be supported, but at least we can have a look at it.

**Comment by cschockaert** [comment]
Ok for example, making a helm install redis-cluster with default values (3 master, 3 replicas).

Then k scale sts/redis-cluster --replicas=8 (6->8)

node 7 and 8 (redis-cluster-6 and redis-cluster-7)  would not join the cluster after the startup, but just start a redis with an empty pvc, would make him spawn as a master standalone pod.

Access an redis-cluster-arbitrer pod with the following scripts:

- redis-cluster addNode redis-cluster-6  (will make redis-cluster-6 join the cluster as a replicas of any master)
- redis-cluster addNode redis-cluster-7 (will make redis-cluster-7 join the cluster as a replicas of any master)
- redis-cluster recreate <nb-of-nodes> <nb-of-replicas>  
ex : redis-cluster recreate 8 1 would create 4 master and 1 replicas for each.

**Comment by andresbono** [comment]
Hi @cschockaert, we have been thinking about your proposal and we see to main blockers:

- `templates/update-cluster.yaml` uses helm templates to support different configurations. i.e. TLS or external-access. It would be complex to move from helm to the container and it would require many extra env-vars to be taken into account.
- We would like to keep k8s specific logic in the Helm context and leave the container as clean as possible. We use the container in other scenarios as well, i.e. docker-compose.

**Comment by cschockaert** [comment]
Well thanks for the quick reply, @andresbono ,

just found this article on medium https://medium.com/swlh/scaling-redis-cluster-via-kubernetes-horizontal-pod-autoscaler-852541c01b29

this is what we are looking for, but i dont know if there is a such thing (in production grade) already existing.

**Comment by andresbono** [comment]
We have HPA for some of the charts, but not in the case of `redis-cluster`: See [bitnami/kong ](https://github.com/bitnami/charts/tree/master/bitnami/kong)for instance.

**Comment by cschockaert** [comment]
Hmm, ok, i dont get it, what has kong to do with the ability to autoscale a redis-cluster?
Or you are just pointing to a chart with some HPA k8s crd written in it?

**Comment by andresbono** [comment]
Sorry for the confusion, @cschockaert. I was just pointing to a chart with HPA capabilities, but `bitnami/redis-cluster` doesn't support it.

A requirement that is needed for HPA is to support scaling through the `statefulset` directly, without additional `helm upgrade` commands.

We will be glad to review implementation proposals (or even PRs) that would add scaling in the `statefulset` but taking into account the blockers stated here: https://github.com/bitnami/charts/issues/4926#issuecomment-759348078.

**Comment by mislayming** [comment]
so...   how to resolve this problem?
I have the same problem that I forced reboot a node of k8s, and then the slave node of redis pod can't started because of dirty data was generated. so I deleted the PV of this pod and the pod instance.

after this pod is rescheduled by K8s (the IP of this pod has been changed), it can't rejoin the cluster.

**Comment by andresbono** [comment]
Hi @mislayming, please check this section of the README: [Adding a new node to the cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#adding-a-new-node-to-the-cluster)
