### ISSUE TITLE
Magento via Kubeapps on Minikube

### ISSUE THREAD

**Issue by lilbumblebear** [bitnami/charts#4933]
**Which chart**: Magento Chart v16.0.3

**Describe the bug**
I am unable to view the magento frontend or admin, I get errors during the upgrade step for finishing the installation.  When I have tried hardcoding the values I still cannot figure out how to get to the frontend or admin pages. 

**To Reproduce**

1. Follow instructions for installing kubeapps
2. Install Magento via kubeapps
3. Follow instructions once pods are ready

**Expected behavior**
After following the instructions, I would be able to access the installation via the nodeport defined

**Version of Helm and Kubernetes**: 

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
1) I have adjusted the yaml config to NodePort instead of LoadBalancer (as said to for the minikube installation)
2) The instructions ask to export the APP_PORT and APP_HOST, but APP_PORT is not used in the next step
3) When you run the commands EXACTLY as specified, there is an error that you cannot update type statefulset.  I was able to get past this by deleting the stateful set using `kubectl delete sts --cascade=false mariadb-service-name` but then the service is no longer type NodePort

**Comment by juan131** [comment]
Hi @lilbumblebear 

A similar situation can be reproduced using helm cli:

```console
$ helm install magento bitnami/magento --set service.type=NodePort
NAME: magento
LAST DEPLOYED: Mon Jan 11 14:11:42 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
###############################################################################
### ERROR: You did not provide an external host in your 'helm install' call ###
###############################################################################

This deployment will be incomplete until you configure Magento with a resolvable
host. To configure Magento with the URL of your service:

1. Get the Magento URL by running:

  export APP_PORT=$(kubectl get svc --namespace default magento -o jsonpath="{.spec.ports[0].nodePort}")
  export APP_HOST=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
  export APP_PASSWORD=$(kubectl get secret --namespace default magento -o jsonpath="{.data.magento-password}" | base64 --decode)
  export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace default magento-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
  export MARIADB_PASSWORD=$(kubectl get secret --namespace default magento-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)

2. Complete your Magento deployment by running:

  helm upgrade magento bitnami/magento --namespace default \
    --set magentoHost=$APP_HOST,magentoPassword=$APP_PASSWORD,mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD,mariadb.auth.password=$MARIADB_PASSWORD
```

You're right, the **APP_PORT** is not used, and it doesn't provide instruction to obtain **APP_PASSWORD**. The upgrade command should look like this:

```console
$ helm upgrade magento bitnami/magento --namespace default \
    --set magentoHost=$APP_HOST \
    --set magentoPassword=$APP_PASSWORD \
    --set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD \
    --set mariadb.auth.password=$MARIADB_PASSWORD \
    --set service.type=NodePort \
    --set service.nodePort=$APP_PORT
```

I'll make a PR to fix it.

**Comment by lilbumblebear** [comment]
Thank you @juan131!  I tried with the new commands and get this error after I run the upgrade:
`Error: UPGRADE FAILED: cannot patch "magento-mariadb" with kind StatefulSet: StatefulSet.apps "magento-mariadb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

I got around this using this command before running the upgrade:
`kubectl delete sts --cascade=false magento-mariadb`

After I do this, I see the Store URL and Admin URL, but I when I go to them in a browser I get:
`This site can't be reached, IP took too long to respond, ERR_CONNECTION_TIMED_OUT`  

Am I missing a step?  I know that it works a little differently with minikube vs something like GKE.

**Comment by juan131** [comment]
Hi @lilbumblebear 

It look like you're upgrading between different versions of Magento. I mean, when you installed Magento through Kubeapps, an old version of the chart was installed. However, when you run the `helm upgrade` a recent version of the chart was used. This is highly likely to be related with an outdated repository used on Kubeapps.

As it's explained in the guide below, Kubeapps should update the repositories quite frequently, so it's likely that you didn't create the required RBAC resources for Kubeapps to update them.

- https://github.com/kubeapps/kubeapps/blob/master/docs/user/syncing-apprepository-webhook.md

What is the version of Magento chart that Kubeapps lists you?

**Comment by lilbumblebear** [comment]
Magento Chart v16.0.3, I am using all of the default repositories and have not included any private/3rd party repositories.  

I also tried hardcoding the variables (MagentoHost, MagentoPassword, etc.) into the yaml so I did not have to run an upgrade after running the install.  When I did this, the pods all appear to be running, but I still cannot get to the Magento frontend.  I get the same error as I mentioned above.  

All I am trying to do is run the Magento helm chart on a Minikube cluster locally for testing/development. I have no ingress set up or any additional/different configuration parameters. 

Any help is greatly appreciated!

**Comment by juan131** [comment]
...reopening the issue since it was closed after merging the PR fixing the NOTES.txt

Regarding your issue @lilbumblebear, could you please share the exact `helm install` and `helm upgrade` command you're using?

**Comment by lilbumblebear** [comment]
Here are the commands I am running (I am using minikube, I stopped using Kubeapps to make sure I isolate any issues)
1) 
```
helm install bitnami-test bitnami/magento --set service.type=NodePort
```
2) 
```
export APP_PORT=$(kubectl get svc --namespace default bitnami-test-magento -o jsonpath="{.spec.ports[0].nodePort}")
export APP_HOST=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
export APP_PASSWORD=$(kubectl get secret --namespace default bitnami-test-magento -o jsonpath="{.data.magento-password}" | base64 --decode)
export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace default bitnami-test-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
export MARIADB_PASSWORD=$(kubectl get secret --namespace default bitnami-test-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)
```
3) 
```
helm upgrade bitnami-test bitnami/magento --namespace default \
    --set magentoHost=$APP_HOST \
    --set magentoPassword=$APP_PASSWORD \
    --set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD \
    --set mariadb.auth.password=$MARIADB_PASSWORD \
    --set service.type=NodePort \
    --set service.nodePort=$APP_PORT
```

When I go to the Store URL (an IP in my case) it says:
```
This site can’t be reached
IP took too long to respond.
ERR_CONNECTION_TIMED_OUT
```

Thank you for your help @juan131

**Comment by juan131** [comment]
Hi @lilbumblebear 

Please follow these steps:

```console
# Start Minikube
$ minikube start
...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
# Install the chart
$ helm install bitnami-test bitnami/magento --set service.type=NodePort
...
# Export credentials and check they're correctly set
$ export APP_PORT=$(kubectl get svc --namespace default bitnami-test-magento -o jsonpath="{.spec.ports[0].nodePort}")
$ export APP_HOST=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
$ export APP_PASSWORD=$(kubectl get secret --namespace default bitnami-test-magento -o jsonpath="{.data.magento-password}" | base64 --decode)
$ export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace default bitnami-test-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
$ export MARIADB_PASSWORD=$(kubectl get secret --namespace default bitnami-test-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)
$ echo "$APP_HOST:$APP_PORT $APP_PASSWORD $MARIADB_ROOT_PASSWORD $MARIADB_PASSWORD"
192.168.49.2:30530 xFQ4Qn4SM6 vszc5eh6vm oaAioTJu9g
# Check that indeed the APP_HOST reports the same IP as "minikube ip" command
$ minikube ip
192.168.49.2
# Upgrade the chart
$ helm upgrade bitnami-test bitnami/magento --namespace default \
    --set image.debug=true \
    --set magentoHost=$APP_HOST \
    --set magentoPassword=$APP_PASSWORD \
    --set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD \
    --set mariadb.auth.password=$MARIADB_PASSWORD \
    --set service.type=NodePort \
    --set service.nodePort=$APP_PORT
# Wait for Magento pod to be ready
$ kubectl get pods -l app.kubernetes.io/name=magento,app.kubernetes.io/instance=bitnami-test -w
NAME                                    READY   STATUS              RESTARTS   AGE
...
bitnami-test-magento-777d87d9c6-xb2dq   1/1     Running   0          4m50s
```

Then, open a browser (e.g. Chrome or Firefox) and browse to the IP. 

If, for some reason, the Magento pod doesn't reach the "ready" status, the please share the output of running the command below:

```console
$ kubectl logs $(kubectl get pods -l app.kubernetes.io/name=magento,app.kubernetes.io/instance=bitnami-test -o jsonpath='{.items[0].metadata.name}') 
```

I warn you that Magento uses MariaDB and ElasticSearch as dependencies (which normally require a lot of CPU/RAM), so it's very likely that, in the case Magento doesn't reach the "ready" status, it might be related with low resources on Minikube.

**Comment by lilbumblebear** [comment]
Thank you @juan131 

I ran the commands exactly as directed, here are a couple of things I noticed:

1) APP_HOST is different than the minikube IP, 
APP_HOST = 192.168.49.2
minikube IP = 127.0.0.1

2) The Magento pod does take a few minutes to get to the ready state, but it does complete and become "Ready" 

3) When I check the logs after the pod is ready I see a lot of this over and over:
```
172.17.0.1 - - [13/Jan/2021:14:42:55 +0000] "GET /index.php HTTP/1.1" 200 6152
```

4) I am unable to get to the APP_HOST IP via the browser, it shows 
```
ERR_CONNECTION_TIMED_OUT
```

5) I also tried running the minikube service command to tunnel into the NodePort (since the IPs were different):
```
minikube service bitnami-test-magento --url
```
When I did this, the URL redirects to the APP_HOST IP and adds /index.php onto the end (that seemed good!) but I still get the timeout response

It does not seem like I am running into a resource constraint.  I am not sure if it is a Magento configuration issue?

**Comment by juan131** [comment]
Hi @lilbumblebear 

> APP_HOST is different than the minikube IP

As it's mentioned at https://minikube.sigs.k8s.io/docs/handbook/accessing/#getting-the-nodeport-using-kubectl:

> The minikube VM is exposed to the host system via a host-only IP address, that can be obtained with the `minikube ip` command.

Depending on the driver you used to start Minikube it can be `127.0.0.1` or a different IP (`192.168.49.2` in my case using `docker` driver).

Regardless the IP it returns, please ensure when you run the `helm upgrade` command that value you set at `APP_HOST` is the same one as the value returned by `minikube ip` command.

> I am unable to get to the APP_HOST IP via the browser, it shows

Are you accessing to the Magento including the port in the URL? For instance, http://127.0.0.1:33333

> When I check the logs after the pod is ready I see a lot of this over and over:
>
> 172.17.0.1 - - [13/Jan/2021:14:42:55 +0000] "GET /index.php HTTP/1.1" 200 6152

That's normal. That's due to the readiness/liveness probes.

**Comment by lilbumblebear** [comment]
Thank you for all of your help @juan131 

I tried adjusting the upgrade command and using the minikube IP
```
export APP_HOST=$(minikube ip)
```

Then waited for the pod to be ready. This time I get 
```
ERR_CONNECTION_REFUSED
```

It seems like I can use the commands I sent previously using 192.168.49.2 IP for APP_HOST and then running
```
minikube service bitnami-test-magento --url
```
gets me closer to seeing Magento.  

I still am unable to get to the Magento interface :-(

I really appreciate your help, it has been frustrating spending so much time on this when it feels like it should be a relatively easy thing to setup.

**Comment by juan131** [comment]
Hi @lilbumblebear 

Let's try this:

```console
$ helm install bitnami-test bitnami/magento --set service.type=NodePort
$ minikube service bitnami-test-magento --url
🏃  Starting tunnel for service bitnami-test-magento.
|-----------|----------------------|-------------|------------------------|
| NAMESPACE |         NAME         | TARGET PORT |          URL           |
|-----------|----------------------|-------------|------------------------|
| default   | bitnami-test-magento |             | http://127.0.0.1:50528 |
|-----------|----------------------|-------------|------------------------|
http://127.0.0.1:50528
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

Now, open a second terminal (keeping the 1st one running with the `minikube service...` command), and run:

```console
$ export APP_PORT=$(kubectl get svc --namespace default bitnami-test-magento -o jsonpath="{.spec.ports[0].nodePort}")
$ export APP_PASSWORD=$(kubectl get secret --namespace default bitnami-test-magento -o jsonpath="{.data.magento-password}" | base64 --decode)
$ export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace default bitnami-test-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
$ export MARIADB_PASSWORD=$(kubectl get secret --namespace default bitnami-test-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)
$ helm upgrade bitnami-test bitnami/magento --namespace default \
    --set image.debug=true \
    --set magentoHost=127.0.0.1 \
    --set service.type=NodePort \
    --set service.nodePort=$APP_PORT \
    --set magentoPassword=$APP_PASSWORD \
    --set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD \
    --set mariadb.auth.password=$MARIADB_PASSWORD
```

> Please note I'm forcing `magentoHost=127.0.0.1` 

Once, Magento pod is ready, run the command below and share the output:

```console
$ curl -LI http://127.0.0.1:50528 
```

**Comment by lilbumblebear** [comment]
Yes! That got me somewhere
```
HTTP/1.1 200 OK
Date: Fri, 15 Jan 2021 14:31:44 GMT
Server: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.25
X-Powered-By: PHP/7.3.25
Expires: Wed, 15 Jan 2020 14:31:45 GMT
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Pragma: no-cache
X-Magento-Cache-Control: max-age=86400, public, s-maxage=86400
X-Magento-Cache-Debug: MISS
X-Magento-Tags: cat_c,store,cms_b,cms_p_2,FPC
Content-Length: 26171
Content-Security-Policy-Report-Only: font-src 'self' 'unsafe-inline'; form-action secure.authorize.net test.authorize.net geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com *.amazon.com *.amazon.co.uk *.amazon.co.jp *.amazon.jp *.amazon.it *.amazon.fr *.amazon.es yotpo.com www.yotpo.com p.yotpo.com staticw2.yotpo.com w2.yotpo.com 'self' 'unsafe-inline'; frame-ancestors 'self' 'unsafe-inline'; frame-src secure.authorize.net test.authorize.net geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com www.paypal.com www.sandbox.paypal.com *.amazon.com *.amazon.co.uk *.amazon.co.jp *.amazon.jp *.amazon.it *.amazon.fr *.amazon.es *.payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.payments-amazon.es *.dotdigital-pages.com *.dotdigital.com cdn.dnky.co webchat.dotdigital.com yotpo.com www.yotpo.com p.yotpo.com staticw2.yotpo.com w2.yotpo.com 'self' 'unsafe-inline'; img-src widgets.magentocommerce.com www.googleadservices.com www.google-analytics.com www.paypalobjects.com t.paypal.com *.ftcdn.net *.behance.net data: www.paypal.com fpdbs.paypal.com fpdbs.sandbox.paypal.com *.vimeocdn.com s.ytimg.com d3sbl0c71oxeok.cloudfront.net dhkkzdfmpzvap.cloudfront.net d2bpzs5y44q6e0.cloudfront.net d37shgu97oizpd.cloudfront.net d1zlqll3enr74n.cloudfront.net d1jynp0fpwn93a.cloudfront.net d2cb3tokgpwh3v.cloudfront.net d1re8bfxx3pw6e.cloudfront.net d35u8xwkxs8vpe.cloudfront.net d13s9xffygp5o.cloudfront.net d388nbw0dwi1jm.cloudfront.net d11p2vtu3dppaw.cloudfront.net d3r89hiip86hka.cloudfront.net dc7snq0c8ipyk.cloudfront.net d5c7kvljggzso.cloudfront.net d2h8yg3ypfzua1.cloudfront.net d1b556x7apj5fb.cloudfront.net draz1ib3z71v2.cloudfront.net dr6hdp4s5yzfc.cloudfront.net d2bomicxw8p7ii.cloudfront.net d3aypcdgvjnnam.cloudfront.net d2a3iuf10348gy.cloudfront.net *.ssl-images-amazon.com *.ssl-images-amazon.co.uk *.ssl-images-amazon.co.jp *.ssl-images-amazon.jp *.ssl-images-amazon.it *.ssl-images-amazon.fr *.ssl-images-amazon.es *.media-amazon.com *.media-amazon.co.uk *.media-amazon.co.jp *.media-amazon.jp *.media-amazon.it *.media-amazon.fr *.media-amazon.es yotpo.com www.yotpo.com p.yotpo.com staticw2.yotpo.com w2.yotpo.com 'self' 'unsafe-inline'; script-src assets.adobedtm.com secure.authorize.net test.authorize.net www.googleadservices.com www.google-analytics.com www.paypalobjects.com js.braintreegateway.com www.paypal.com geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.sandbox.paypal.com t.paypal.com s.ytimg.com video.google.com vimeo.com www.vimeo.com www.youtube.com *.payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.payments-amazon.es *.trackedlink.net *.trackedweb.net *.dotdigital-pages.com cdn.dnky.co api.comapi.com webchat.dotdigital.com yotpo.com www.yotpo.com p.yotpo.com staticw2.yotpo.com w2.yotpo.com 'self' 'unsafe-inline' 'unsafe-eval'; style-src getfirebug.com cdn.dnky.co webchat.dotdigital.com yotpo.com www.yotpo.com p.yotpo.com staticw2.yotpo.com w2.yotpo.com 'self' 'unsafe-inline'; object-src 'self' 'unsafe-inline'; media-src 'self' 'unsafe-inline'; manifest-src 'self' 'unsafe-inline'; connect-src geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com *.amazon.com *.amazon.co.uk *.amazon.co.jp *.amazon.jp *.amazon.it *.amazon.fr *.amazon.es *.amazonpay.com *.amazonpay.co.uk *.amazonpay.co.jp *.amazonpay.jp *.amazonpay.it *.amazonpay.fr *.amazonpay.es mws.amazonservices.com mws.amazonservices.co.uk mws.amazonservices.co.jp mws.amazonservices.jp mws.amazonservices.it mws.amazonservices.fr mws.amazonservices.es *.trackedlink.net *.trackedweb.net *.dotdigital-pages.com api.comapi.com webchat.dotdigital.com yotpo.com www.yotpo.com p.yotpo.com staticw2.yotpo.com w2.yotpo.com 'self' 'unsafe-inline'; child-src http: https: blob: 'self' 'unsafe-inline'; default-src 'self' 'unsafe-inline' 'unsafe-eval'; base-uri 'self' 'unsafe-inline';
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: IE=edge
Content-Type: text/html; charset=UTF-8
```

I can get to the frontend when I go to 127.0.0.1:SERVICE_PORT (49252 in my case).  The last issue I have is that it will not load any of the styling/resource files.  Ex:
```
http://127.0.0.1/pub/static/version1610724466/frontend/Magento/luma/en_US/images/logo.svg
```
I get `ERR_CONNECTION_REFUSED` Any ideas how to fix this issue?  If I try to load the file manually and add the SERVICE_PORT into the URL it works. 

Thank you so much @juan131

**Comment by juan131** [comment]
Hi @lilbumblebear 

Correct. As you said, Magento is not generating the URLs with the right port. 
As it's explained [in this link](https://github.com/bitnami/bitnami-docker-magento#user-and-site-configuration), there are two env. variables that can help defining the external port to use: `EXTERNAL_HTTP_PORT_NUMBER` and `EXTERNAL_HTTPS_PORT_NUMBER`

We're missing the corresponding parameter in the chart to configure that setting, so you can use the `extraEnvVars` as a workaround as shown below:

```console
helm upgrade bitnami-test bitnami/magento --namespace default \
    --set image.debug=true \
    --set magentoHost=127.0.0.1 \
    --set service.type=NodePort \
    --set service.nodePort=$APP_PORT \
    --set magentoPassword=$APP_PASSWORD \
    --set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD \
    --set mariadb.auth.password=$MARIADB_PASSWORD \
    --set extraEnvVars[0].name=EXTERNAL_HTTP_PORT_NUMBER \
    --set extraEnvVars[0].value="49252"
```

So you have to:

- Uninstall Magento (and remove existing PVCs)
- Install Magento.
- Obtain the required env. variables
- Upgrade Magento using the command above (remember to update the port if it's different from 49252)

**Comment by lilbumblebear** [comment]
Ok, I tried that and get:
```
Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 5, error found in #10 byte of ...|,"value":58939}],"im|..., bigger context ...|no"},{"name":"EXTERNAL_HTTP_PORT_NUMBER","value":58939}],"image":"docker.io/bitnami/magento:2.4.1-de|...
```
I tried setting value="PORT" and value=PORT, seems like a very simple syntax error on my part now but SO CLOSE!

**Comment by lilbumblebear** [comment]
I think the above error is related to: https://github.com/kubernetes/kubernetes/issues/82296

If I try quoting, then I can get past this issue, but the pod crashes because Magento does not like the quoted port.  Any other way around this?

**Comment by juan131** [comment]
Hi @lilbumblebear 

Did you try "escaping" the quote characters? I mean: `--set extraEnvVars[0].value=\"49252\"`

**Comment by lilbumblebear** [comment]
I can get past the upgrade error, but the pod fails. I believe it is failing because the port should not have quotes when Magento gets it (makes sense) but the quotes are required in the upgrade command

```
TRACE Error: Error executing 'postInstallation': 
In InstallCommand.php line 274:
                               
  [InvalidArgumentException]   
  Parameter validation failed 
```
(above the error I can see this)
```
Executing: /opt/bitnami/php/bin/php magento,setup:install,-v,--base-url,http://127.0.0.1:"60644"/,-
```

**Comment by juan131** [comment]
Okay @lilbumblebear .. Let's try with a custom **values.yaml** instead of using parameters:

- Uninstall Magento (and remove existing PVCs)
- Install Magento.
- Obtain the required env. variables (APP_PASSWORD, APP_PORT, MARIADB_ROOT_PASSWORD, and MARIADB_PASSWORD)
- Create the custom values.yaml using the command below:

```console
$ cat > values.yaml << EOF
image:
  debug: true
magentoHost: 127.0.0.1
magentoPassword: $APP_PASSWORD
service:
  type: NodePort
  nodePort: $APP_PORT
extraEnvVars:
  - name: EXTERNAL_HTTP_PORT_NUMBER
    value: "49252"
mariadb:
  auth:
    rootPassword: $MARIADB_ROOT_PASSWORD
    password: $MARIADB_PASSWORD
EOF
```

- Upgrade Magento using the command below:

```console
$ helm upgrade bitnami-test bitnami/magento --namespace default -f values.yaml
```
