### ISSUE TITLE
RabbitMQ deployed as subchart fails on upgrade with "common.errors.upgrade.passwords.empty" error

### ISSUE THREAD

**Issue by ValeriiVozniuk** [bitnami/charts#4939]
**Which chart**:
rabbitmq, 8.6.2

**Describe the bug**
After rabbitmq chart upgrade from 7.5.6 to 8.6.2 I've faced an issue with chart upgrade when rabbitmq is used as subchart. The primary chart is initially deployed with several components replicaCount set to 0, so they would not start till the database restore process job is completed. So, when restore process is completed, I run the upgrade command, and now I'm getting the following error
```
Error: UPGRADE FAILED: template: reportportal/charts/rabbitmq/templates/NOTES.txt:138:4: executing "reportportal/charts/rabbitmq/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredRabbitmqPasswordErrors) "context" $)>: error calling include: template: reportportal/charts/postgresql/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.erlangCookie' must not be empty, please add '--set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE' to the command. To get the current value:

        export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace reportportal reportportal-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
```

**To Reproduce**

1. Deploy rabbitmq as a subchart with following initial values file
```rabbitmq:
  replicaCount: 0
  auth:
    username: rabbitmq
    password: 123456789a
```
2. Try to upgrade the chart with same values file with replicaCount: 1
3. Upgrade fails with the error above

**Expected behavior**
Upgrade runs fine as it was before

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.1-dirty", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"dirty", BuildDate:"2020-11-19T13:01:01Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
As a temporary workaround I've just removed the block having Values.auth.existingErlangSecret in it in rabbitmq/templates/NOTES.txt file, and upgrade went just fine, but would like to see the proper fix for this issue in rabbitmq chart

**Comment by miguelaeh** [comment]
Hi @ValeriiVozniuk ,
That's not an error. It is meant to avoid the passwords to be changed on the secrets while maintaining the old ones configured in the volumes. Forcing users to set the same passwords when upgrading maintains the secrets synced with the volumes.
That's why we added a function to make the upgrade fail if the user does not provide the password when upgrading.

**Comment by ValeriiVozniuk** [comment]
Hi Miguel,

I understand your point, and what issue you are trying to solve, but for the case I've described current behavior creates a deadlock. As I said, for now I've solved the issue for me just by removing the validation, so all is up to you, if you want to support/handle such scenario automatically.
Anyway, as I'm leaving the current project, I'm not really care what your decision will be :)

**Comment by miguelaeh** [comment]
Hi @ValeriiVozniuk ,
Sorry I am not sure about which the issue is. Using the chart as subchart you can set the old pasword by using: `--set rabbimq.auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE`. Note the prefixed `rabbitmq` that should be name used for the dependency

**Comment by ValeriiVozniuk** [comment]
Hi Miguel,

The issue is that **there is no erlangCookie yet**, because initial deploy was with replicas=0, so rabbitmq did not create it **yet**. And if you pass the name for erlangCookie which should be created, then you will get a failure as there is no data there **yet** -> deadlock

**Comment by miguelaeh** [comment]
Hi @ValeriiVozniuk ,
The erlanCookie is created by Kubernetes in a secret not by RabbitMQ, so even if you have `replicas` set to `0` it should exist. YOu must obtain it executing something like:
```
 kubectl get secret --namespace <our-namespace> <release>-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode
```

**Comment by ValeriiVozniuk** [comment]
Hi Miguel,

Thank you for your time, I've tried to reproduce the issue I've initially had with passing `--set rabbimq.auth.erlangCookie`, and was unable to do so. Today all was working fine, and I didn't saw the error I've initially had (it was different from "'auth.erlangCookie' must not be empty", so now I'm not sure what was causing it. I'm closing this for now, thanks again
