### ISSUE TITLE
Question - How to add a Redis instance to the Magento Chart?

### ISSUE THREAD

**Issue by lilbumblebear** [bitnami/charts#4944]
**Which chart**:
Magento Chart v 16.0.3

**Is your feature request related to a problem? Please describe.**
Magento has several options to use things like Redis, RabbitMQ, etc. to improve performance or add features.  It would be helpful to have a "How To" guide to show something like Redis (or any other bitnami helm chart) added to a Magento installation

**Describe the solution you'd like**
A "How To" guide to show how to implement question above. 

**Describe alternatives you've considered**
I think this might involve editing/extending the Magento Helm Chart. It would be great to have a How To that shows where you can edit the Magento configuration to use the Redis (or other service).

**Comment by FraPazGal** [comment]
Hello @lilbumblebear,

Thanks for using our chart! From what I understand, an example of a "How to" guide would be to add Redis as cache as explained in the [documentation](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html), right? We are not planning to add this type of content in the short-term though I agree that it could be a good addition to our chart and we will be happy to review any PR implementing those changes.

**Comment by lilbumblebear** [comment]
Thank you for your reply @FraPazGal 

If you can give me a high-level overview of what would need to be done, I would be happy to create a PR once I have an example up and running.  

I assume that to do what I want, I will be modifying the Magento helm chart and adding a dependency on the Redis chart as well.  I would then expect to modify the Magento configuration to point to the Redis network info.  Does this sound correct?

**Comment by FraPazGal** [comment]
Hi @lilbumblebear,

Yes, that would be the general steps to follow. The redis host will be its service name, much as it is done with mariadb. You would also need to have set the redis configuration options by hand. We are currently finishing this asset migration to bash, which would be an overhaul of its docker image and change several things in the chart. This migration will make customising this asset easier, so I recommend you to wait a bit to its release.

**Comment by marcosbc** [comment]
Hi @lilbumblebear, for adding support to Redis you'd need to update your Magento chart to [17.0.0](https://github.com/bitnami/charts/tree/master/bitnami/magento#1700), and specify `MAGENTO_EXTRA_INSTALL_ARGS` (i.e. via `--set magentoExtraInstallArgs`) to an appropriate value. In this issue you can find an example of the required flags: https://github.com/bitnami/bitnami-docker-magento/issues/165#issue-726598549

Feel free to send a PR implementing or documenting how to add support for this. We'd be glad to review and help with the release of the chart with the changes.
