### ISSUE TITLE
Bitnami/Redis istio-proxy problem

### ISSUE THREAD

**Issue by bikej** [bitnami/charts#4945]
**Which chart**:
bitnami/redis

**Describe the bug**
Istio-proxy can't connect to istiod cluster ip.

**To Reproduce**
Everything done according to https://docs.bitnami.com/tutorials/deploy-redis-sentinel-production-cluster/
After deployment everything is up (redis, sentinel, metrics) except istio-proxy. 

**Expected behavior**
Redis sentinel cluster deployed.

**Version of Helm and Kubernetes**:

```
(version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"})
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
Envoy logs

2021-01-11T19:22:40.797714Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, no healthy upstream
2021-01-11T19:22:40.797754Z     warning envoy config    Unable to establish new stream
2021-01-11T19:22:50.389964Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, no healthy upstream
2021-01-11T19:22:50.390010Z     warning envoy config    Unable to establish new stream
2021-01-11T19:22:55.154117Z     error   citadelclient   Failed to create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.111.83.192:15012: i/o timeout"
2021-01-11T19:22:55.154156Z     error   cache   resource:default request:a9955424-1046-4ce0-a427-23bd403eaf72 CSR retrial timed out: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.111.83.192:15012: i/o timeout"
2021-01-11T19:22:55.154193Z     error   cache   resource:default failed to generate secret for proxy: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.111.83.192:15012: i/o timeout"
2021-01-11T19:22:55.154204Z     error   sds     resource:default Close connection. Failed to get secret for proxy "sidecar~192.168.179.111~redis-node-0.default~default.svc.cluster.local" from secret cache: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.111.83.192:15012: i/o timeout"
2021-01-11T19:22:55.154458Z     warning envoy config    StreamSecrets gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.111.83.192:15012: i/o timeout"

k get svc -n istio-system | grep istiod
istiod                 ClusterIP      10.111.83.192    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,853/TCP

Istio-proxy works from every other service in the same namespace. Example with redis and hello world.

[root@k8# k exec -it redis-node-0 -c istio-proxy -- /bin/bash
istio-proxy@redis-node-0:/$ curl -v telnet://10.111.83.192:15012
* Rebuilt URL to: telnet://10.111.83.192:15012/
*   Trying 10.111.83.192...
* TCP_NODELAY set

[root@k8]# k exec -it hello-world-59966754c9-9v74d -c istio-proxy -- /bin/bash
istio-proxy@hello-world-59966754c9-9v74d:/$ curl -v telnet://10.111.83.192:15012
* Rebuilt URL to: telnet://10.111.83.192:15012/
*   Trying 10.111.83.192...
* TCP_NODELAY set
* Connected to 10.111.83.192 (10.111.83.192) port 15012 (#0)

Just to mention, deployed also bitnami/redis-cluster and istio-proxy starts there but there is a problem with cluster joining but thats for another ticket.

Appreciate any help.

**Comment by javsalgar** [comment]
Hi,

Could you let us know the Istio settings that you have? Or you did not add any istio object or configuration apart from the ones set during istio installation?

**Comment by bikej** [comment]
Istio profile dump in attach. No, nothing added, just default.

I can also confirm that bitnami/redis-cluster deployed succesfully (cluster join) as soon as I removed istio injection label.

[istio.log](https://github.com/bitnami/charts/files/5801293/istio.log)

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. I will open a task for investigating the issue. As soon as we have more news, we will update the ticket. Thanks for reporting.

**Comment by MichaelHudgins** [comment]
@javsalgar The service part of this https://github.com/bitnami/charts/issues/5016 may have to do with the direct ip denials.

**Comment by bikej** [comment]
Thx guys

**Comment by miguelaeh** [comment]
Hi guys!
We have fixed the issue with Redis Cluster and Istio. You can check this PR #5158
Please let us know if you find any issue with the new changes.
Regards.

**Comment by bikej** [comment]
Thx very much. Now both istio-proxy and redis are up and running.

The only thing I have now is this.

`[root@k8]# helm install redis bitnami/redis-cluster --values values.yaml`
`Error: failed post-install: timed out waiting for the condition`

`pod/redis-redis-cluster-cluster-create-zc4mf   1/2     NotReady`

It doesn't seem to have any impact on the deployment and cluster joins with success.

`[root@k8]# helm list`
`NAME    NAMESPACE       REVISION        UPDATED                                 STATUS  CHART                   APP VERSION`
`redis   redis-cluster   1               2021-01-25 11:33:54.057282212 +0100 CET **failed**  redis-cluster-4.2.7     6.0.10`

**Comment by miguelaeh** [comment]
Hi @bikej ,
The problem is that the job took more time to finish than the Helm command timeout, but it actually does not affect the deployments. To fix it you can just add to the helm install command `--timeout 600` or whatever number appropiate for your cluster. You can find how to do it on the README.md if you have more doubts about it.

**Comment by bikej** [comment]
Actually I tried it already with no luck.

`NAME                                           READY   STATUS     RESTARTS   AGE   IP`
`pod/redis-redis-cluster-cluster-create-v74n4   1/2     NotReady   0          73s   192.168.14.16 `

`[root@k8 redis-cluster]# kubectl get events --sort-by=.metadata.creationTimestamp | grep 192.168.14.16`
`79s         Warning   Unhealthy          pod/redis-redis-cluster-cluster-create-v74n4   Readiness probe failed: Get "http://192.168.14.16:15021/healthz/ready": dial tcp 192.168.14.16:15021: connect: connection refused`

Probe is failing so pod is never ready and the job never finishes.

**Comment by miguelaeh** [comment]
Hi @bikej ,
Could you try giving to the initial probes more time? The Redis cluster needs to go throgh an initial state where the cluster is in an inconsistent state. I think just giving it more time to finish that process should be enough.

**Comment by bikej** [comment]
Thx, I will close this issue.
