### ISSUE TITLE
[bitnami/phpmyadmin] Typo in template name causes error when providing db.chartName 

### ISSUE THREAD

**Issue by OmriHarary** [bitnami/charts#4946]
Attempting to install the chart when setting `db.chartName` results in the following error:
```
Error: template: phpmyadmin/templates/deployment.yaml:75:25: executing "phpmyadmin/templates/deployment.yaml" at <include "phpmyadmin.dbfullnamee" .>: error calling include: template: no template "phpmyadmin.dbfullnamee" associated with template "gotpl"
```

The culprit is the typo on the following line:
https://github.com/bitnami/charts/blob/d504676bbadaf70d21f41c6a0c45d869893fb542/bitnami/phpmyadmin/templates/deployment.yaml#L75

**Comment by juan131** [comment]
Thanks for reporting the issue! I just created a PR to fix it.
