### ISSUE TITLE
[bitnami/redis] Sentinel deployment has no method to add envs or preExecCmds

### ISSUE THREAD

**Issue by MichaelHudgins** [bitnami/charts#4970]
Which chart:
redis

The redis chart has methods to add extra envs and preExecCmds to master or slaves but does not contain a method to add these options if sentinel is enabled.

See: https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-node-statefulset.yaml

Expected behavior
The ability to add extra envs and preExecCmds to the statefulset when using sentinel.

Additional context
Was attempting to fix some issues when using istio as outlined here #4713 I noticed POD_IP was not being injected, nor were the additional commands. Looking at the chart it appears if sentinel is enabled some options of the chart are not available.

**Comment by miguelaeh** [comment]
Hi @MichaelHudgins ,
Thank you for reporting this. The PR above should address the changes you requested. Please take a look to it.
Reagards.

**Comment by MichaelHudgins** [comment]
Hi @miguelaeh that worked for the start-sentinel.sh but it looks like start-node.sh is still missing its ability to inject preExectCmds.  I think based upon slave's values being used for start-node.sh it needs this near the bottom
```
    {{- if .Values.slave.preExecCmds }}
    {{ .Values.slave.preExecCmds | nindent 4}}
    {{- end }}
```

**Comment by MichaelHudgins** [comment]
Added additional pr for adding commands to start-node.sh https://github.com/bitnami/charts/pull/5035

**Comment by miguelaeh** [comment]
Thank you very much!
Let's move to the PR, we have already take care of it
