### ISSUE TITLE
[bitnami/harbor] volumePermissions.enabled: true leads to "job-logs" volume missing in Trivy StatefulSet

### ISSUE THREAD

**Issue by titou10titou10** [bitnami/charts#4976]
**Which chart**:
harbor v 9.3.0

**Describe the bug**
When we enable`volumePermissions.enabled:true` and Trivy (`trivy.enabled: true`), the StetfulSet generated declares this for the`volume-permissions` initContainer:

    volumeMounts:
    - name: job-logs
      mountPath: /var/log/jobs

But there is no equivalent`"volume"`for`"job-logs"`in the manifest. The section for the `"volume"`is missing from the template

**To Reproduce**

    helm install harbor --set volumePermissions.enabled:true, trivy.enabled: true

Then check that the STS for Trivy does not start and this event is generated: 

    create Pod harbor-trivy-0 in StatefulSet harbor-trivy failed error: Pod "harbor-trivy-0" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "job-logs"

**Expected behavior**
Trivy pods up and running because an equivalent "volume" section for the `job-logs volumeMount`is present in the STS manifest 

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
    version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl (OpenShift) version`:

```
Client Version: 4.6.3
Server Version: 4.6.4
Kubernetes Version: v1.19.0+9f84db3
```

**Additional context**
The `volumeMount`is generated from this stanza in`charts/bitnami/harbor/templates/trivy/trivy-sts.yaml` with no corresponding "`volume`section:

    {{- if and .Values.volumePermissions.enabled .Values.persistence.enabled }}
    - name: volume-permissions
      image: {{ include "harbor.volumePermissions.image" . }}
      ...
      volumeMounts:
      - name: job-logs
        mountPath: /var/log/jobs
        subPath: {{ .Values.persistence.persistentVolumeClaim.jobservice.subPath }}
    {{- end }}

**Comment by FraPazGal** [comment]
Hi @titou10titou10,

Thanks for catching this! We will create a PR addressing this shortly.
