### ISSUE TITLE
[kube-prometheus] Error Templating Ingress

### ISSUE THREAD

**Issue by rbs4ba** [bitnami/charts#4977]
**Which chart**:
kube-prometheus:3.3.3

**Describe the bug**
Upon upgrading to version 3.3.3 of the kube-prometheus chart, we are encountering the following errors on the templating step of a deploy:
```
coalesce.go:196: warning: cannot overwrite table with non table for tls (map[])
```
```
error calling include: template: kube-prometheus/charts/common/templates/_capabilities.tpl:44:14: executing "common.capabilities.ingress.apiVersion" at <.Values.ingress.apiVersion>: nil pointer evaluating interface {}.apiVersion
```

**To Reproduce**
1. Aside from the default values.yaml, we're setting the following in our own manifest
```
prometheus:
  ingress:
    enabled: true
    annotations:
      <annotations>
    hosts:
      <host>
    tls:
      <tls>
```
2. Deploy kube-prometheus with chart version 3.3.3

**Expected behavior**
Expecting a successful deploy.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
v3.4.1+gc4e7485
```

- Output of `kubectl version`:
```
v1.17.8
```

**Additional context**
We are using the same config to successfully deploy with 3.3.2. It _seems_ like the issue is with `common`, but if it is then we're surprised that other charts & users aren't experiencing the same issue.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting. The issue here is that the common is assuming that ingress.apiVersion is accessed using `.Values.ingress.apiVersion`, however this is not the case in kube-prometheus. I will work on fixing the library so this case is covered.
