### ISSUE TITLE
[bitnami/kong] Add nodeselector for migrate job and postgresql statefulsets

### ISSUE THREAD

**Issue by aaronsssya** [bitnami/charts#4980]
**Which chart**:
bitnami/kong 3.1.0

**Is your feature request related to a problem? Please describe.**
yes. due to we have multiple type node. We leverage label to assign node. Therefore, we would like to add nodeSelector for migrate job an postgresql statefulsets. Thanks

**Describe the solution you'd like**
Add nodeselector in the global OR in the job/statefulset. therefore, those pods will run on specific node.

**Comment by carrodher** [comment]
Thanks for the suggestion, do you like to contribute to this repo by creating a PR?
