### ISSUE TITLE
airflow: add support for different nodeSelectors for different airflow components

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#4983]
**Which chart**:
airflow chart all versions.

**Is your feature request related to a problem? Please describe.**
We need to run workers on different nodes and web/scheduler on different nodes.

**Describe the solution you'd like**
Make nodeSelector variable component scoped instead of current global scoped.

**Describe alternatives you've considered**
Trivial for now, so we are still running all of them at same type of nodes.

**Additional context**

**Comment by iamsudip** [comment]
@dani8art Can we do this? I can share a PR.

**Comment by miguelaeh** [comment]
Hi @iamsudip ,
We are always happy to review PRs, please feel free to open it
Thanks!

**Comment by joraojr** [comment]
Hi, 

 I think you forgot to add the support to `nodeSelector `to [pod_template.yaml](https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/config/configmap.yaml).  When I try to use the KubernetExecutor, the worker pod is not created at the specified `worker.nodeSelector`.

**Comment by miguelaeh** [comment]
Hi @joraojr,
I created that PR that should solve it, could you take a look?

**Comment by joraojr** [comment]
Hi @miguelaeh ,
 Thank you! It should solve my problem.
