### ISSUE TITLE
Redis Cluster Ldap Authentication

### ISSUE THREAD

**Issue by 8297530225** [bitnami/charts#4992]
HI Team.. I have deployed Redis Cluster using bitnami helm chart and wanted to know if it Supports LDAP or not.  

If supports can anyone tell what configuration paramaters need to be used in deployment file.

I have used following parameters in deployment file and deployed. Pods came up and running but not sure how to connect to redis database by passing username and password. Can someone help me how to pass username and password through redis-cli?
**ldap.url**
**ldap.binddn** 
**ldap.bind_password**

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Looking at the documentation, LDAP is only available for Redis Enterprise. 

https://docs.redislabs.com/latest/rs/administering/designing-production/security/ldap-integration/

I'm afraid that it is not possible to use LDAP in the Open Source Redis version.

**Comment by 8297530225** [comment]
Thanks for your Quick response @javsalgar. Is there any other alternative way to achieve it in open source either with keycloak or something else. And do we need any license for using bitnami redis in production?

**Comment by javsalgar** [comment]
Hi,

At the moment, we are unaware of a way to achieve Keycloak and Redis integration. About using Bitnami Redis in production, there is no license required. For production workloads and adaptation to your needs we recommend you to take a look at Tanzu Application Catalog, where you can build you catalog with the customizations and OS you require https://tanzu.vmware.com/application-catalog
