### ISSUE TITLE
[bitnami/external-dns]: Missing namespace on various resources

### ISSUE THREAD

**Issue by nabadger** [bitnami/charts#5017]
**Which chart**:

[external-dns](https://github.com/bitnami/charts/tree/master/bitnami/external-dns)

**Describe the bug**

When using Helm Templating (either via `helm template` or underlying libs), the `--namespace` scope is not respected for various resources.

This results in those resources being deployed to the `default` namespace.

For example, the `Deployment ` resource [here](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/deployment.yaml#L3
)

The solution (I think) is to to make use of Helm built-in `Release.Namespace`. and ensure all namespace-scoped resources specify this.

**To Reproduce**

```
helm template --namespace foo
```
Note that following resources are missing a namespace `foo`

- ServiceAccount
-  Service
-  Deployment

**Version of Helm and Kubernetes**:

Using `v3.3.4` (this is all local, so k8s version does not matter)

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this. If you run `helm install ... --namespace test` you will get all the components created in that namespace.
```
$ kubectl get all --namespace test
NAME                                     READY   STATUS    RESTARTS   AGE
pod/mydns-external-dns-c7bff5cc9-2889k   0/1     Running   0          23s

NAME                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/mydns-external-dns   ClusterIP   10.104.219.36   <none>        7979/TCP   23s

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mydns-external-dns   0/1     1            0           23s

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/mydns-external-dns-c7bff5cc9   1         1         0       23s

$ kubectl get serviceaccount --namespace test
NAME                 SECRETS   AGE
default              1         2m34s
mydns-external-dns   1         92s
```
```
$ kubectl get all --namespace default
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   70d

NAME                                            COMPLETIONS   DURATION   AGE
job.batch/myclus-redis-cluster-cluster-create   1/1           53s        27d

$ kubectl get serviceaccount --namespace default
NAME      SECRETS   AGE
default   1         70d
```
  Will that work for you ?

**Comment by nabadger** [comment]
Sadly not, since my workflow only uses `helm template`, but not `helm install`.

I'm actually using https://tanka.dev/helm which uses `helm template` underneath.

**Comment by rafariossaa** [comment]
Hi,
  I understand.
  We are a small team, and I can not provide a ETA for this. Would you like to send a PR and add support for this ? We will be glad to review and merge it.

**Comment by nabadger** [comment]
I can do that no problem - I'll give it a go over the weekend :)

**Comment by rafariossaa** [comment]
Hi,
  Thanks forehand
