### ISSUE TITLE
make new chart versions github releases

### ISSUE THREAD

**Issue by jurgenweber** [bitnami/charts#5019]
**Which chart**:
All charts

**Is your feature request related to a problem? Please describe.**
The releases page is a RSS/Atom feed, I take that feed and put it into Vienna so I can easily watch a bunch of repos for new releases... Since I use a good 5 or so bitnami charts i'd like to be able to monitor this repo.

**Describe the solution you'd like**
Everytime a release is completed/a version bump is completed on any chart in this repo.. a github release is made.

**Describe alternatives you've considered**
right now, I am doing it manually and that sucks. :)

**Additional context**
![image](https://user-images.githubusercontent.com/3013734/104514559-8cce6200-5645-11eb-8772-cd70776ddea0.png)

**Comment by miguelaeh** [comment]
Hi @jurgenweber ,
The main problem I can see with that is that each chart has its own versioning. Which version would we use on the release page?
Also, every PR merged must have a version bump (except when it only affects the README). It is our internal pipeline wo does the releases to `https://charts.bitnami.com/bitnami`. Maybe there is any way to track the releases there.

**Comment by jurgenweber** [comment]
> The main problem I can see with that is that each chart has its own versioning.

that is not a problem, that is the point? The idea? Its like.. the feature. Each chart, each version, to release.

You could do it like [eks-charts](https://github.com/aws/eks-charts) I suppose, it works with the idea but I would just run with every chart, new release.

> every PR merged must have a version bump

again that is the point. 

> https://charts.bitnami.com/bitnami
Is it a RSS/Atom feed? That is just the chart index... hmm.

**Comment by miguelaeh** [comment]
Hi @jurgenweber ,
this is something we are starting to do for the repositories of the images.
I am going to create an internal task to evaluate how to do this for the Helm Chart repository but I cannot provide and ETA since we would need to evaluate the effort and decide if it is something where we should invest the time of the team.
Regards.
