### ISSUE TITLE
[bitnami/rabbitmq] Allow nil selectors in ServiceMonitor to allow full scan of kubernetes cluster services.

### ISSUE THREAD

**Issue by philippevidal80** [bitnami/charts#5021]
**Which chart**:
bitnami/rabbitmq

**Is your feature request related to a problem? Please describe.**
One `ServiceMonitor` can scan all RabbitMQ services in a cluster.

**Describe the solution you'd like**
Allow `nil` selectors in `ServiceMonitor` to allow full scan of kubernetes cluster services.

**Describe alternatives you've considered**
Manually add matching pattern (namespace for example) in `ServiceMonitor` manifest when deployed.

**Additional context**
Snippet where template is concerned:
https://github.com/bitnami/charts/blob/9813d48141f2b7800e365ba74ef060c35c3d5102/bitnami/rabbitmq/templates/servicemonitor.yaml#L30-L35

**Comment by dani8art** [comment]
Hi @philippevidal80 thanks for the feedback, I think that could make sense in some scenarios, would you mind to open a PR making the changes, and w'll discuss the solution there?

thanks!!
