### ISSUE TITLE
Subcharts with bitnami/common dependecy conflicts

### ISSUE THREAD

**Issue by beniamin** [bitnami/charts#5022]
**Which chart**:
all charts that use bitnami/common

**Describe the bug**
I have one master-chart that uses kube-prometheus as subchart at version 2.2.1.
I wanted to add mysql in my master-chart, but it failed because both mysql and kube-prometheus depends on bitnami/common, but on different version. Kube-prometheus depends on v0.x.x version and mysql depends on v1.x.x.
I tried to upgrade kube-prometheus chart to v3.0.1, but without success because this versions uses v1.0.0 of bitnami/common which is also incompatible with v1.x.x.

I am not able to upgrade to a greater version of kube-prometheus because the crds are changed and I may impact all the prometheus instances deployed on the cluster.

The issue seems to be the fact that both versions of bitnami/common uses the same 

**To Reproduce**
1. Create a new chart
2. Add an older version of kube-prometheus, let's say 2.2.1
3. Add latest mysql version 
4. Install the master chart
5. See error:

`Error: UPGRADE FAILED: template: master-chart/charts/prometheus/templates/prometheus/ingress.yaml:3:15: executing "master-chart/charts/prometheus/templates/prometheus/ingress.yaml" at <include "common.capabilities.ingress.apiVersion" .>: error calling include: template: master-chart/charts/mysql/charts/common/templates/_capabilities.tpl:44:14: executing "common.capabilities.ingress.apiVersion" at <.Values.ingress.apiVersion>: nil pointer evaluating interface {}.apiVersion`

**Expected behavior**
Succesfull install

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I was able to install version 7.0.1 of the mysql charts, because this version does not depends on bitnami/common subchart.
I think this issue may occur with any combinations of bitnami charts that depends on bitnami/common.

**Comment by FraPazGal** [comment]
Hello @beniamin,

From the upgrade error you shared, this seems to be related to a change we introduced in bitnami/common regarding ingress rules in #4859. We are updating our whole catalog, though it may take a few days. As a workaround, please try adding the parameter `ingress.apiVersion` to you `values.yaml`, that should solve it for now.

**Comment by beniamin** [comment]
It worked. I used the following params for my prometheus subchart(this is the oldest one):
```
kube-prometheus:
   ingress:
      apiVersion: "networking.k8s.io/v1beta1"
```

Thank you!
