### ISSUE TITLE
Charts Access Denied

### ISSUE THREAD

**Issue by atsai1220** [bitnami/charts#5028]
**Which chart**:
The name (and version) of the affected chart
https://charts.bitnami.com/bitnami

**Describe the bug**
Unable to access charts from Rancher UI. However it is possible with Helm3 CLI.

```
❯ helm3 repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
❯ helm3 search repo bitnami
NAME                             	CHART VERSION	APP VERSION  	DESCRIPTION
bitnami/bitnami-common           	0.0.9        	0.0.9        	DEPRECATED Chart with custom templates used in ...
bitnami/airflow                  	7.1.1        	1.10.14      	Apache Airflow is a platform to programmaticall...
bitnami/apache                   	8.1.1        	2.4.46       	Chart for Apache HTTP Server
...
...
```

**To Reproduce**

```
❯ curl https://charts.bitnami.com/bitnami

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>347D7C41A5BCFBCB</RequestId><HostId>TRl1TU7j8OnROf38VEpTeyWBVyJ6UYHkK5OfmqZk+7Q7FvQuCPouZCH1OMoe80uT5DnWlNhWHO8=</HostId></Error>
```

Add Chart to Rancher Catalog 
![image](https://user-images.githubusercontent.com/14171643/104619247-7e327b80-5642-11eb-8fe3-6a32e32c470b.png)

**Expected behavior**
Expecting to see the index.html

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**
Seems related to these from a week ago but doesn't look like anyone else is running into this issue?

- https://github.com/bitnami/charts/issues/4922
- https://github.com/bitnami/charts/issues/4908

**Comment by juan131** [comment]
Hi @atsai1220 

It seems you closed the issue. Did you solve it? 
Is there anything we can help you with?

**Comment by atsai1220** [comment]
It was a firewall issue on our side. I still have access denied in my browser (which doesn't matter) and accessing from Helm and Rancher works fine now :) Thank you!

**Comment by juan131** [comment]
Glad to hear that!! Thanks
