### ISSUE TITLE
[bitnami/cassandra] Adding DB users via Helm (Kubernetes secrets)

### ISSUE THREAD

**Issue by brianrudolf** [bitnami/charts#5029]
**Which chart**:
bitnami/cassandra-7.1.2

**Is your feature request related to a problem? Please describe.**
I am currently developing an application with this chart, and am using the super user credentials for my various services that access the DB. I would like to transition to using dedicated user credentials for each service (first to avoid using the super user, but also to be able to provision some read only access). I do not see a way to accomplish this through the Helm chart interface, and assume that I will need to run `cqlsh` commands inside the container either manually or via a script run in the init container. 

**Describe the solution you'd like**
I think it would be very powerful to be able to reference existing Kubernetes secrets (or have Helm create new secrets) and to configure Cassandra to create users with permissions from those secrets.

**Describe alternatives you've considered**
Manual administration of user creation. This may be out of the scope / purpose of the application installation that Helm provides - I would welcome thoughts on how far to take the use of Helm for a (Cassandra) database install. 

**Additional context**
This work could be done in the same context of the super-user creation, though that is not a part of the chart that I am familiar with currently.

**Comment by marcosbc** [comment]
Hi @brianrudolf, I guess you're looking for something like [initDBConfigMap](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml#L227) or [initDBSecret](https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml#L232). Those scripts will be executing only during the first initialization so it should work for the creation of initial users / DB schema.

Hope it helps!

**Comment by brianrudolf** [comment]
@marcosbc this looks like a great way to accomplish this. I will close the issue as this is definitely an appropriate way to accomplish my needs.
