### ISSUE TITLE
[kafka] I'm using kafka in bitnami, but prometheus metric is not perfect.

### ISSUE THREAD

**Issue by tom1005** [bitnami/charts#5034]
Hi.

I'm using kafka in bitnami, but prometheus metric is not perfect.

Can you check this issue?

The below is prometheus exporter curl result.

[curl_result.log](https://github.com/bitnami/charts/files/5818114/curl_result.log)

**Comment by tom1005** [comment]
Hi. @alemorcuq 

I think that kafka metric information (via exporter) is less appears.
Please, can you check "curl_result.log"?

**Comment by alemorcuq** [comment]
Yes, I've seen `curl_result.log`, but to be honest I don't know what to look for there. Do you mean the exporter is retrieving less metrics than it should? Why do you think that? Could you give me some information?

**Comment by scleep** [comment]
Hey guys. :D 
What @tom1005  wants to say is that there are only two kafka metrics.
`# HELP kafka_brokers Number of Brokers in the Kafka Cluster.
# TYPE kafka_brokers gauge
kafka_brokers 1
# HELP kafka_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which kafka_exporter was built.
# TYPE kafka_exporter_build_info gauge
kafka_exporter_build_info{branch="HEAD",goversion="go1.9",revision="d8a8460163f4fe9316044f4581503f30a739936f",version="1.2.0"} 1`

https://github.com/danielqsj/kafka_exporter
Other metrics can be found in the description of kafka-exporter in the above url.
(e.g. kafka_topic_partitions, kafka_topic_partition_replicas, kafka_consumergroup_current_offset..) 

But there are only two metrics in curl_result.log, can you tell which setting(such as configuration) to check?

**Comment by tom1005** [comment]
Ops...

I'm sorry.... I have a mistake;;;;

It's normal.

thanks response @scleep @alemorcuq
