### ISSUE TITLE
Redis cluster on ipv6 based kubernetes binds to 0.0.0.0 not ipv6

### ISSUE THREAD

**Issue by kunalkushwaha** [bitnami/charts#5036]
**Which chart**:
redis-cluster

**Describe the bug**
While setting up the Redis Cluster on the Kubernetes cluster (ipv6 based). In spite of passing "::" for bind-address, the Redis server binds to 0.0.0.0

- To pass bind-address, the values.yaml passed to helm charts have the following settings.
```
configmap: |-
  bind ::
  protected-mode no
  port 6379
```

**To Reproduce**
But once pods are up, I found the Redis server is bound to 0.0.0.0, though the values in redis.conf are set properly through helm charts.
```
$ k exec -it xxxxxxx-redis-cluster-0 -- bash
I have no name! @ xxxx-redis-cluster-0:/$ ps -ax
   PID TTY      STAT   TIME COMMAND
     1 ?        Ssl    0:14 redis-server 0.0.0.0:6379 [cluster]
 10902 pts/0    Ss+    0:00 bash
 24157 pts/1    Ss     0:00 bash
 24170 pts/1    R+     0:00 ps -ax


$ k describe cm xxxxxx-redis-cluster-default | grep bind
# By default, if no "bind" configuration directive is specified, Redis listens
# the "bind" configuration directive, followed by one or more IP addresses.
# bind 192.168.1.100 10.0.0.1
# bind 127.0.0.1 ::1
# internet, binding to all the interfaces is dangerous and will expose the
# following bind directive, that will force Redis to listen only into
# bind :: 0.0.0.0
# 1) The server is not binding explicitly to a set of addresses using the
#    "bind" directive.
# are explicitly listed using the "bind" directive.
bind ::
```
**Expected behavior**

Redis should bind to ipv6 (IP passed in configmap

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by FraPazGal** [comment]
Hello @kunalkushwaha,

Currently, this asset is not 100% ready to be used with IPv6, so we can't ensure it to work correctly. Although it is in our backlog to support it across our catalog, we are not yet able to give an ETA on this.

**Comment by kunalkushwaha** [comment]
Hi @FraPazGal , Thanks for the quick update.

It would be great if someone can give me for code, where config map settings get translated to the pod config.

I can try to fix and make a PR for the same but am unable to understand the flow of how it is overwriting the settings.

**Comment by FraPazGal** [comment]
Hi @kunalkushwaha,

The code where the mounted `redis-default.conf` file is used to configure the cluster by the container can be found [here](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/5.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L358). You would need to make some changes to that code as, from what I can see, the bind IP is being hardcoded to `0.0.0.0`.

**Comment by kunalkushwaha** [comment]
Hi FraPazGal <https://github.com/FraPazGal>,

Thanks, It will be really helpful.
I will try to fix it and create a PR.

Thanks,
Kunal
