### ISSUE TITLE
Phabricator pod never gets deployed even after an hour

### ISSUE THREAD

**Issue by MrAmbiG** [bitnami/charts#5037]
**Which chart**:
The name (and version) of the affected chart
phabricator --version 10.2.2
**Describe the bug**
mariadb pods gets deployed and running. phabriactor pod never gets deployed. phabricator service is created.

**To Reproduce**

helm -n phabricator install phabricator bitnami/phabricator --version 10.2.2
kubectl -n phabricator get pod -w

**Expected behavior**
Phabricator gets deployed
**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
v3.3.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
6 NODE baremetal RKE kubernetes cluster
rook-ceph dynamic storage backend (filesystem type)

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about the Kubernetes platform you are using? Could you provide more details about the volume provisioning you are using? Most of the issues appear because of the PVC technology used.

**Comment by MrAmbiG** [comment]
> Hi,
> 
> Could you provide more details about the Kubernetes platform you are using? Could you provide more details about the volume provisioning you are using? Most of the issues appear because of the PVC technology used.

- Just updated the environment details. I wish I could get more logs or info but since the pod never gets deployed, I am not sure how to get more info on this. 
- All our applications, microservices, builds are all using the dynamic pvc by ceph with all upto 10+ TB SSD

**Comment by javsalgar** [comment]
We are currently working on a major bump of the chart. Stay tuned as the new release may fix the issues you are experiencing.

**Comment by juan131** [comment]
Hi @MrAmbiG 

I just wanted to let you know that we just released the new major version (see https://github.com/bitnami/charts/pull/5159) @javsalgar mentioned you on a previous message.

Could you please give it a try and let us know if the issue persists? Thanks in advance.

**Comment by MrAmbiG** [comment]
`helm install -n mynamespace phabricator bitnami/phabricator --version 11.0.1`
no go. only pod/phabricator-mariadb-0 is deployed and running but no other pods get deployed.

**Comment by juan131** [comment]
Hi @MrAmbiG 

Did you take a look to the instructions you obtain after installing the chart? You just need to follow them to understand the reason why Phabricator is not deployed.
