### ISSUE TITLE
Redmine crashloopbackoff forever

### ISSUE THREAD

**Issue by MrAmbiG** [bitnami/charts#5038]
**Which chart**:
redmine 15.0.3

**Describe the bug**
mariadb deployed.
redmine service created.
redmine pod crashloopbackoff error.

**To Reproduce**

describe pod    
```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m33s                   default-scheduler  Successfully assigned phabricator/redmine-67f7fc756d-d9n5c to 10.216.55.145
  Normal   Pulling    8m32s                   kubelet            Pulling image "docker.io/bitnami/redmine:4.1.1-debian-10-r189"
  Normal   Pulled     8m11s                   kubelet            Successfully pulled image "docker.io/bitnami/redmine:4.1.1-debian-10-r189"
  Normal   Created    6m31s (x3 over 8m9s)    kubelet            Created container redmine
  Normal   Started    6m31s (x3 over 8m9s)    kubelet            Started container redmine
  Warning  Unhealthy  6m11s (x10 over 8m1s)   kubelet            Readiness probe failed: Get http://IPADDRESS:3000/: dial tcp 10.42.131.148:3000: connect: connection refused
  Normal   Pulled     5m38s (x3 over 7m29s)   kubelet            Container image "docker.io/bitnami/redmine:4.1.1-debian-10-r189" already present on machine
  Warning  BackOff    3m28s (x11 over 6m50s)  kubelet            Back-off restarting failed container
```

**Expected behavior**
Redmine pod runs.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Error for the newest versiion 15.0.1 for the redmine pod
```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at redmine-mariadb:3306
mysql-c INFO  MySQL server listening and working at redmine-mariadb:3306
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/redmine/public/plugin_assets'
```

**Comment by juan131** [comment]
Hi @MrAmbiG 

Let's try to debug what's going on. Please provide us a little more information:

- What kind K8s cluster are you using to deploy Redmine (e.g. Minikube, GKE, AKS, etc.)?
- Could you please share the exact command you used to install the Redmine chart?
- Could you please also share the logs of the Redmine container? Just share the output of running the command below replacing the `REDMINE_POD` placeholder with the actual pod name:

```console
$ kubectl logs REDMINE_POD
```

**Comment by MrAmbiG** [comment]
> Hi @MrAmbiG
> 
> Let's try to debug what's going on. Please provide us a little more information:
> 
> * What kind K8s cluster are you using to deploy Redmine (e.g. Minikube, GKE, AKS, etc.)?
> * Could you please share the exact command you used to install the Redmine chart?
> * Could you please also share the logs of the Redmine container? Just share the output of running the command below replacing the `REDMINE_POD` placeholder with the actual pod name:
> 
> ```
> $ kubectl logs REDMINE_POD
> ```

- 6 node baremetal k8s, installed using RKE with ceph storage backend.
- helm -n SECRETNAMESPACE install redmine bitnami/redmine --version 15.1.0 [copy paste from here https://artifacthub.io/packages/helm/bitnami/redmine?modal=install]
- Since the pod keeps crashing, I cannot get logs (it says such pod doesn't exist), I could only get the describe [kubectl describe REDMINEPODNAME]

**Comment by MrAmbiG** [comment]
Just tried the newest 15.1.0 released today and the error for the redmine pod is...
```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at redmine-mariadb:3306
mysql-c INFO  MySQL server listening and working at redmine-mariadb:3306
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/redmine/public/plugin_assets'
```

**Comment by juan131** [comment]
Hi @MrAmbiG 

It looks like a permissions issue. You have two alternatives to ensure the PVC added to the Redmine container has the appropriate permissions for it to work:

- Option A (enabled by default in the chart): Use SecurityContexts by setting the `podSecurityContext.enabled` and `containerSecurityContext.enabled` to `true`.
- Option B (if your cluster doesn't support adapting PVCs based on security contexts). Use a init container that changes volume permissions. To do that, set the `volumePermissions.enabled` to `true` (see https://github.com/bitnami/charts/tree/master/bitnami/redmine#volume-permissions-parameters for more information).

**Comment by MrAmbiG** [comment]
`helm -n jira upgrade -i redmine bitnami/redmine --set "volumePermissions.enabled=true,redminePassword=MYPASS,mariadb.auth.password=M4r14db,mariadb.auth.rootPassword=MYPASSroot,podSecurityContext.enabled=false" `

`helm -n jira upgrade -i redmine bitnami/redmine --set "volumePermissions.enabled=true,redminePassword=MYPASS,mariadb.auth.password=M4r14db,mariadb.auth.rootPassword=MYPASSroot,podSecurityContext.enabled=true" `

Same problem.

**Comment by juan131** [comment]
Hi @MrAmbiG 

I just discovered that we introduce a regression on the major version bump.. Please wait for the fix I just sent to be published or install the chart running the command below:

```console
$ helm -n jira upgrade -i redmine bitnami/redmine \
    --set redminePassword=MYPASS \
    --set mariadb.auth.password=M4r14db \
    --set mariadb.auth.rootPassword=MYPASSroot \
    --set containerSecurityContext.enabled=false \
    --set podSecurityContext.enabled=false
```

**Comment by juan131** [comment]
Thanks for reporting it
