### ISSUE TITLE
Upgrading PostgreSQL helm chart to v12 or v13

### ISSUE THREAD

**Issue by unreliability** [bitnami/charts#5061]
Apologies if this has already been covered or documented, but my organization uses both the PostgreSQL and PostgreSQL HA charts internally for various services (i,e GitLab). We are looking to upgrade our installed charts to the latest major release of postgres (v13.x) but there doesn't seem to be any documentation on the best way to do this. It also doesn't seem like there's a means of installing the chart with a version of PostgreSQL beyond v11.x as even a fresh deployment comes with this version.

Several of our services will be deprecating support for v11.x in favor of more recent versions, making this an issue for us that needs to be addressed. Is there any current way to go about this? If migration is not possible on a live chart, is there any current/planned support for these newer versions?

Thanks in advance for any assistance.

**Comment by javsalgar** [comment]
Hi,

In this kind of scenarios, switching the PostgreSQL will not work as the `initdb` command will fail. In this sense, I would advise you to deploy a fresh PostgreSQL and perform a manual backup/restore from one instance to the other. Did you try performing backup-restore operations?

**Comment by ljohnston** [comment]
@javsalgar - The upgrade process you describe make sense.

I'm more interested in the following from the original post:

>  It also doesn't seem like there's a means of installing the chart with a version of PostgreSQL beyond v11.x as even a fresh deployment comes with this version.

The latest bitnami/postgresql chart, `10.2.6` is for PostgreSQL `11.10.0`. Will there be a chart coming anytime soon that will support PostgreSQL v12?

**Comment by javsalgar** [comment]
Hi,

Even though we officially support PostgreSQL 11 in the chart, and that's the one we currently update, the chart should be able to work with PostgreSQL 12 by switching the image tag in the values. Did you try that? Did you find any issue?

**Comment by ljohnston** [comment]
I was hoping that might be the case. I was asking for a project I'm about to start in the next week or two. I will give it a try. Thanks.

**Comment by angelsantillana94** [comment]
Hello @unreliability , 

Did you find a solution to your problem? I have the same situation that you indicate at the beginning of the issue.

Thanks!

**Comment by javsalgar** [comment]
Hi, did you try this? https://github.com/bitnami/charts/issues/5061#issuecomment-762103416
