### ISSUE TITLE
  Issue after enabling kafka external access

### ISSUE THREAD

**Issue by avanichy25** [bitnami/charts#5064]
**Which chart**:
version: 11.8.3
appVersion: 2.6.0

**Describe the bug**
Trying to enable kafka to access outside the cluster and followed the link below but it gives an error like added below:
https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster
```
 Starting Kafka **
[2021-01-18 03:18:26,894] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2021-01-18 03:18:31,702] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2021-01-18 03:18:31,997] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Listener with name PLAINTEXT defined in inter.broker.listener.name not found in listener.security.protocol.map.
        at kafka.server.KafkaConfig.$anonfun$getInterBrokerListenerNameAndSecurityProtocol$1(KafkaConfig.scala:1637)
        at scala.collection.immutable.Map$Map3.getOrElse(Map.scala:181)
        at kafka.server.KafkaConfig.getInterBrokerListenerNameAndSecurityProtocol(KafkaConfig.scala:1636)
        at kafka.server.KafkaConfig.interBrokerListenerName(KafkaConfig.scala:1524)
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1698)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1674)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1238)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1218)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29)
        at kafka.Kafka$.main(Kafka.scala:68)
        at kafka.Kafka.main(Kafka.scala)
```

Configuration:
```
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "kafka-zookeeper"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CLIENT:SSL,EXTERNAL:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094"
```

2) i have service created with loadbalancer as mentioned below how can i use it to access though application outside the cluster?
```
kafka-0-external                               LoadBalancer   xx.xx.77.128   xxxx   9094:30422/TCP                                                    14m
kafka-1-external                               LoadBalancer   xxx.xx.76.137    xxxx  9094:30979/TCP                                                    14m
kafka-2-external                               LoadBalancer   xx.xx.xx.240   xxxx   9094:32099/TCP                                                    14m

**Comment by carrodher** [comment]
Can you share with us the values you are using to deploy the chart (via file or in the `helm install` command)? In the same way, there are some installation notes you can consult where there is some information about how to access the cluster according to the values you used. You can check those notes by executing `helm get notes RELEASE_NAME`

**Comment by avanichy25** [comment]
@carrodher Thanks. Now i can connect to the application with load balancers but the question is that, i have 3 pods running for the kafka and it created 3 external service with load balancers.

When i give all three loadbalancers ip:port to my application it takes always the first broker. How about if the first pod, then our application wont work.  This should be handled in the application or if there any way ?

**Comment by carrodher** [comment]
It depends on the configuration, are you using the `autoDiscovery` parameter? In [this section](https://github.com/bitnami/charts/tree/master/bitnami/kafka#using-loadbalancer-services) of the README, you can find the differences. With `autoDiscovery` there is an initContainer looking for the IPs, while without it you need to know beforehand the IPs and set them in the `externalAccess.service.loadBalancerIPs[]` array.

Apart from that the chart allows you to set different listeners (even for external communications), in that case, the auth method is handled directly by the listener, you can take a look at this section https://github.com/bitnami/charts/tree/master/bitnami/kafka#listeners-configuration

**Comment by avanichy25** [comment]
@carrodher We have enabled the `autodiscovery` and init container does the job for us.  But still the question is, if I run 3 pods it generates the 3 external load balancer ips. In my application I need to use all three external load balancers and write a logic to select which one is master before i do anything or is there any other way we can handle the same within the kafka itself ?

**Comment by carrodher** [comment]
What is the result of `helm get notes RELEASE_NAME`? The output of that command should show the instructions to access Kafka from inside and outside the cluster depending on the custom parameters you're using.

I don't know what is your specific use case or the application, but as a general rule, Kafka is used as a "peer to peer" architecture and there is no master/slave or primary/secondary configuration. In the client, you need to specify the list of nodes those are the instructions that the notes should show, maybe it is something wrong if that is not the case
