### ISSUE TITLE
Artifacthub.io -> Verified Publisher Tag

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#5067]
**Which chart**:
All charts of bitnami are indexed by the artifacthub.
As of today they are not verified.
It could be that someone entered the repository into artifacthub.
To really allow users to see that its a verified repository from bitnami.

* [Claim Ownership](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#ownership-claim)
* [Verified Publisher](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#verified-publisher)

When you claimed the repository CVE scanning could also be setup.
This gives users more insights from the helm charts and the used images.

* [CVE Scanning setup](https://github.com/artifacthub/hub/blob/master/docs/helm_annotations.md)

**Is your feature request related to a problem? Please describe.**

The artifacthub shows the Helm Charts from bitnami but currently it is not indicating them as Verified Publisher.
* [artifacthub.io/bitnami](https://artifacthub.io/packages/search?page=1&org=bitnami)

**Comment by miguelaeh** [comment]
Hi @Cellebyte ,
Thank you very much for notifying about this. The team is checking it.

**Comment by beltran-rubo** [comment]
thanks for your suggestion @Cellebyte, we are working on it, it should be ready pretty soon.

**Comment by beltran-rubo** [comment]
Bitnami is now a ´verified publisher´ in Artifacthub https://artifacthub.io/packages/search?page=1&ts_query_web=bitnami
