### ISSUE TITLE
Kafka: "SSL handshake failed" on producer console when auth/encryption enabled

### ISSUE THREAD

**Issue by sentry-gun** [bitnami/charts#5072]
**Which chart**:
Kafka 11.8.9

**Describe the bug**
SSL Handshake error when trying to work with kafka-console-producer.sh, getting lots of logs similar to
```
[2021-01-18 19:36:43,697] WARN [Producer clientId=console-producer] Bootstrap broker kafka-0.kafka-headless.kafka.svc.cluster.local:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```
and the pod logs show
```
[2021-01-18 19:37:05,392] INFO [SocketServer brokerId=0] Failed authentication with /<POD_IP> (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

**To Reproduce**

* Run script found in documentation ([here](https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh)) to generate trust- and keystores, answering `kafka-0.kafka-headless.kafka.svc.cluster.local` for everything but 2 letter codes, and using password `test1234`
* Rename keystore with `mv kafka.keystore.jks kafka-0.keystore.jks` (otherwise get an error aboud the keystore not being found)
* Deploy the chart and set the following values
```
auth.clientProtocol           = sasl_tls
auth.interBrokerProtocol      = sasl_tls
auth.jksSecret                = kafka-vanilla
auth.jksPassword              = test1234
zookeeper.persistence.enabled = false
persistence.enabled 	        = false

auth.jaas.interBrokerUser     =	brokeruser
auth.jaas.interBrokerPassword =	brokerpass
auth.jaas.zookeeperUser       =	zookeeperuser
auth.jaas.zookeeperPassword   =	zookeeperpass
auth.jaas.clientUsers[0]      = clientuser
auth.jaas.clientPassword[0]   = clientpass

zookeeper.auth.enabled          = true
zookeeper.auth.clientUser       = zookeeperuser
zookeeper.auth.clientPassword   = zookeeperpass
zookeeper.auth.serverUsers      = zookeeperuser
zookeeper.auth.serverPasswords  = zookeeperpass

auth.tlsEndpointIdentificationAlgorithm=
```
* Once zookeeper and kafka have started, exec into the pod with `kubectl exec -n kafka kafka-0 --stdin --tty`
* Create a new topic with `./opt/bitnami/kafka/bin/kafka-topics.sh --create --topic newtopic kafka-0.kafka-headless.kafka.svc.cluster.local:9092 --zookeeper kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:2181 --partitions 1 --replication-factor 1`
* Finally, try to send messages to the topic with `./opt/bitnami/kafka/bin/kafka-console-producer.sh --topic newtopic --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9092`
* Watch handshake errors fill the screen

**Expected behavior**
No errors while using the producer

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v2.16.8-rancher1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
* Running in a Rancher 2.4.8 cluster
* I've tried using FQDN, hostname, and localhost when creating the certificates
* I've tried `sasl`, `sasl_tls`, and `tls`
* I've scoured SO and issues with 'kafka' in them, but none of the possible solutions have done the trick
* I've tried with and without `auth.tlsEndpointIdentificationAlgorithm`
* Plaintext works correctly, so I don't suspect the commands I'm using to test
* I've tried adding `-Djavax.net.debug=ssl:handshake:verbose` to `KAFKA_OPTS` with `sasl_tls`, and I've been running with `image.debug=true` for most of my tests, but no extra information seems to appear in the log pods

To be honest, this is most likely user error, probably with the certs, but I'm just out of ideas at this point
Please let me know if more information is needed

Thank you for your time

**Comment by FraPazGal** [comment]
Hello @sentry-gun,

Thank you for the detailed info! I'll work on reproducing this and come back with my findings!

**Comment by FraPazGal** [comment]
Hi @sentry-gun!

I followed your steps and it is true that there is a handshake error. That is coming from a few missing configuration steps. For my testing environment I used the values given as example in our [README](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper), using `auth.clientProtocol=sasl` and `auth.interBrokerProtocol=tls`. Keep in mind there is a typo in a couple of parameters `auth.certificatesSecret -> auth.jksSecret` and `auth.certificatesPassword -> auth.jksPassword`.

I used `kafka-0(1).kafka-headless.kafka.svc.cluster.local` as FQDN ("first / last name") for both my keystore files. I added the truststore and both keystore files to the `bitnami/kakfa/files` folder in my forked repo for the secret to be created automatically and then I followed the instructions given after chart installation:

```
$ helm install kafka . --namespace kafka

# Conf files for the kafka client
$ cat > kafka_jaas.conf <<EOF
KafkaClient {
org.apache.kafka.common.security.scram.ScramLoginModule required
username="user"
password="$(kubectl get secret kafka-jaas -n kafka -o jsonpath='{.data.client-passwords}' | base64 --decode | cut -d , -f 1)";
};
EOF
$ cat > client.properties <<EOF
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
EOF

# Copy the files to the pod and configure a global env
$ kubectl cp --namespace kafka ./client.properties kafka-0:/tmp/client.properties
$ kubectl cp --namespace kafka ./kafka_jaas.conf kafka-0:/tmp/kafka_jaas.conf
$ kubectl exec --tty -i kafka-0 --namespace kafka -- bash
$ export KAFKA_OPTS="-Djava.security.auth.login.config=/tmp/kafka_jaas.conf"

I have no name!@kafka-0:/$ kafka-console-producer.sh \
            --producer.config /tmp/client.properties \
            --broker-list kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092 \
            --topic test
> create
### Transient error ###
[2021-01-26 15:15:25,373] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 3 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
> test
> topic

I have no name!@kafka-0:/$ kafka-console-consumer.sh \
            --consumer.config /tmp/client.properties \
            --bootstrap-server kafka.kafka.svc.cluster.local:9092 \
            --topic test \
            --from-beginning
create
test
topic
```

I tested both using an existing pod and creating a `kafka-client` one as suggested by the installation instructions with 
```
kubectl run kafka-client --restart='Never' --image docker.io/bitnami/kafka:2.7.0-debian-10-r1 --namespace kafka --command -- sleep infinity
```

From the commands you shared, I think you didn't use the configuration files `kafka_jaas.conf/client.properties` right? Could you try this approach to see if this solves the issue?

**Comment by sentry-gun** [comment]
Yes, this works, thank you so much!

So `/opt/bitnami/kafka/config/kafka_jaas.conf` should use `org.apache.kafka.common.security.scram.ScramLoginModule required` instead of `org.apache.kafka.common.security.plain.PlainLoginModule required` for `KafkaClient`, got it

As for producer & consumer, I see there is a `producer.properties` and `consumer.properties` within `/opt/bitnami/kafka/config`, but when I try to stick the contents of `client.properties` in there, we're back to the same error

Is there an extra option that is needed in `KAFKA_OPTS` to use those files as default? I also tried to put it inside the `Client` section of `kafka_jaas.conf` to no avail

Thanks again for the help!

**Comment by FraPazGal** [comment]
Hello @sentry-gun,

If I understood you correctly, you want to have the content of `client.properties` added to `consumer/producer.properties`, right? It worked for me doing the following inside the pod:

```
$ cat << EOF >> /opt/bitnami/kafka/config/consumer.properties

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
EOF

$ cat << EOF >> /opt/bitnami/kafka/config/producer.properties

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
EOF

I have no name!@kafka-0:/$ kafka-console-producer.sh \
            --producer.config /opt/bitnami/kafka/config/producer.properties \
            --broker-list kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092 \
            --topic test

I have no name!@kafka-0:/$ kafka-console-consumer.sh \
            --consumer.config /opt/bitnami/kafka/config/consumer.properties \
            --bootstrap-server kafka.kafka.svc.cluster.local:9092 \
            --topic test \
            --from-beginning
```

It is a bit messy and done manually, but it should get you started.

**Comment by sentry-gun** [comment]
Yes, but what I wanted to avoid was that manual part
I hoped that there was a way to configure the environment for the producer/consumer to use a .properties file by default

In any case, its not a problem -- maybe this is something Kafka can't do (I haven't found anything online either)

Thank you for all the help so far, I'll close the issue now
