### ISSUE TITLE
Can't apply custom postgresql.config values

### ISSUE THREAD

**Issue by bborovan** [bitnami/charts#5075]
**Which chart**:
The name (and version) of the affected chart
postgresql-ha 13.1.0

**Describe the bug**

We've been trying to setup the PostgreSQL HA Bitnami Helm Chart in our dev environment in a three node cluster and have had no luck getting the helm chart to recognize our customer parameters and/or a customized version of the postgresql.config file. We followed the directions on your site to place a copy of the postgresql,config file in a subdirectory name "files" and it totally ignores our settings. We also tried placing a subset of the config file in the files/conf.d/ directory and this was also ignored. We don't see any clear step-by-step instructions on how to make this work.

**To Reproduce**

1. Place a new config file in a files or files/conf.d/ subdirectory (as noted in your directions at https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha/#installing-the-chart).

2. Run:
helm install my-release -f values.yaml bitnami/postgresql-ha

Note: we specified settings in the values.yaml and also the specific postgresql.conf values we also wanted in the files or files/conf.d/ directory. Neither approach worked, with our postgresql.conf file settings NOT being applied as expected.

**Expected behavior**

We expected the postgresql.conf values to be applied.

**Version of Helm and Kubernetes**:
Helm version: 3.4.0
Kubernetes k3s version v1.18.9+k3s1

- Output of `helm version`:
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Specifically, for example we want to adjust the following values (and no luck doing so, after many attempts following your directions):

max_connections = 200
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 2621kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 4
max_parallel_workers_per_gather = 2
max_parallel_workers = 4
max_parallel_maintenance_workers = 2

Thank you for your assistance!

**Comment by juan131** [comment]
Hi @bborovan 

Did you clone the repository before putting your custom configuration files under the `files` directory? I mean, the custom files should be included in the directory below:

- https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha/files

By the way, I don't recommend to follow this method to set the custom configuration. Instead, I would update the value of the `pgpool.configuration`, `postgresql.configuration`, `postgresql.pgHbaConfiguration`, and `postgresql.repmgrConfiguration` parameters in the **values.yaml** (see https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L429)

**Comment by bborovan** [comment]
Hi @juan131 

Thank you for the reply and assistance. 

No we did not clone the repository and simply created a "files/" directory as described in your documentation. Do we need to clone the entire repository and if so how exactly do we run the helm command in that case?  The documentation only shows how to pull it from the helm repository, but no examples of running it from a local copy with custom config files, that I saw in the instructions (unless I am missing something ;) ). 

Also, we tried setting the postgresql.configuration values in the helm command as such for example:
helm install my-release -f values.yaml bitnami/postgresql-ha --set postgresql.configuration="shared_buffers = 1GB"

But the values in the "set" parameter were ignored and not applied, and also the documentation is unclear on how to add multiple configuration parameters via the command line. For example, how would I add all of the following via the command line when installing the helm chart?

e.g. All these values:
max_connections = 200
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 2621kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 4
max_parallel_workers_per_gather = 2
max_parallel_workers = 4
max_parallel_maintenance_workers = 2

Your help is greatly appreciated! 

Thank you,
Brent

**Comment by juan131** [comment]
Hi @bborovan 

> No we did not clone the repository and simply created a "files/" directory as described in your documentation. Do we need to clone the entire repository and if so how exactly do we run the helm command in that case? The documentation only shows how to pull it from the helm repository, but no examples of running it from a local copy with custom config files, that I saw in the instructions (unless I am missing something ;) ).

It's not mandatory to clone the repo but, at least, you have to fetch the chart (`helm fetch ...`) an have a copy of it in your working directory. We know this is confusing and many users commit the same mistake, that's why we're starting to remove this feature from the charts and the reason why I told you to update the **values.yaml** instead.

> Also, we tried setting the postgresql.configuration values in the helm command as such for example:
helm install my-release -f values.yaml bitnami/postgresql-ha --set postgresql.configuration="shared_buffers = 1GB"
> But the values in the "set" parameter were ignored and not applied, and also the documentation is unclear on how to add multiple configuration parameters via the command line. For example, how would I add all of the following via the command line when installing the helm chart?

I don't recommend you to pass this kind of complex object through the command line (I mean using `--set ...`) since it can become quite complex. Instead you can do sth like this:

```console
$ cat > my-custom-values.yaml << 'EOF'
postgresql:
  configuration: |=-
    max_connections = 200
    shared_buffers = 1GB
    effective_cache_size = 3GB
    ... (continue with the rest of options)
EOF
$ helm install -f my-custom-values.yaml my-release bitnami/postgresql-ha 
```

**Comment by bborovan** [comment]
Thank you @juan131 for the help.

I am trying your latter suggestion with adding the change to the config file as follows (similar to the syntax you showed):
postgresql:
  configuration: |=-
    max_connections = 200
    shared_buffers = 1GB
    effective_cache_size = 3GB
    maintenance_work_mem = 256MB
    checkpoint_completion_target = 0.7
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 2621kB
    min_wal_size = 1GB
    max_wal_size = 4GB
    max_worker_processes = 4
    max_parallel_workers_per_gather = 2
    max_parallel_workers = 4
    max_parallel_maintenance_workers = 2


However, this too throws an error in Helm when I run:
helm install -f my-custom-values.yaml postgresql-ha bitnami/postgresql-ha

I get this from Helm:
Error: failed to parse my-custom-values.yaml: error converting YAML to JSON: yaml: line 132: did not find expected comment or line break

Not seeing much regarding what this means when searching online, so guessing the syntax may not be correct?

Thanks again,
Brent

**Comment by juan131** [comment]
Ups sorry!! There was at typo (a `=` symbol introduced by mistake) @bborovan 

Please use:

```console
$ cat > my-custom-values.yaml << 'EOF'
postgresql:
  configuration: |-
    max_connections = 200
    shared_buffers = 1GB
    effective_cache_size = 3GB
    ... (continue with the rest of options)
EOF
```

**Comment by bborovan** [comment]
Hi @juan131 Thank you for letting me know. I tried without exactly as you show above, but it still does not work and I get another error stating "Error: template: postgresql-ha/templates/postgresql/configmap.yaml:25:48: executing "postgresql-ha/templates/postgresql/configmap.yaml" at <.Values.postgresql.configuration>: range can't iterate over max_connections = 200 ", as seen here:

![image](https://user-images.githubusercontent.com/44975810/105229598-93c00d80-5b3a-11eb-9915-fb17cd2012b2.png)

I have no idea what that means or what the problem is in this case also. Is there something else perhaps wrong?

Thank you again,
Brent

**Comment by juan131** [comment]
Hi @bborovan 

You're 100% right.. For reasons that I don't really understand, this configuration parameter was implemented in a different way on this chart and it expects the values as a dict and using camelCase (see https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L437):

```yaml
  ## Specify runtime configuration parameters as a dict, using camelCase, e.g.
  ## {"sharedBuffers": "500MB"}
```

So I tried using the values below and it worked:

```console
$ cat > my-custom-values.yaml << 'EOF'
postgresql:
  configuration:
    maxConnections: 200
    sharedBuffers: 1GB
    effectiveCacheSize: 3GB
EOF
```

A configMap like the one below was created:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-release-postgresql-ha-postgresql-configuration
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-6.3.7
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
data:
  postgresql.conf: |
    effective_cache_size=3GB
    max_connections=200
    shared_buffers=1GB
```

So it seems that you need to transform configuration options in snakecase (e.g.  `effective_io_concurrency`) into camelCase (`effectiveIoConcurrency`). 

Could you give it a try?

**Comment by bborovan** [comment]
Hi @juan131 

Thank you kindly for all your help! That works now and great to see! 

Would be good if someone can update the documentation on this so that others don't get confused too ;)

Thanks again!
Brent

**Comment by juan131** [comment]
Hi @bborovan 

I'm glad you could get it working!!

Indeed, I'd say that we need to stop using this `camelCase -> sneakcase` transformation because I can't really find any advantage on using it, and I find it very confusing. 

I'll create a PR to address this.

**Comment by bborovan** [comment]
Hi @juan131 

It seems I spoke too soon, and after further investigation it seems the Helm chart ran fine now after your suggested changes to the syntax, however, any time that I add the configuration section as you described the Postgresql cluster does not start up.

For example if i run:
helm install -f test.yaml postgresql-ha bitnami/postgresql-ha --set postgresql.password=MYPASSWORD

And the test.yaml contains only this:
![image](https://user-images.githubusercontent.com/44975810/105517739-c9393800-5cad-11eb-921e-f22f2ed5b76c.png)

Or even if i just have ANY one of line beneath the the "configuration:" line using the syntax as shown, the pods do not start and I see the following when I run "kubectl get pods":
![image](https://user-images.githubusercontent.com/44975810/105518046-29c87500-5cae-11eb-8f39-254e000796c3.png)

When I then look at the logs of the pod using "kubectl logs postgresql-ha-postgresql-0 postgresql" I get:
![image](https://user-images.githubusercontent.com/44975810/105518249-70b66a80-5cae-11eb-8ec0-25f0ce5ca634.png)

I am not sure what this means:
postgresql-repmgr 16:26:41.50 INFO  ==> ** Starting repmgrd **
[2021-01-22 16:26:41] [NOTICE] repmgrd (repmgrd 5.2.0) starting up
[2021-01-22 16:26:41] [ERROR] unable to write to shared memory
[2021-01-22 16:26:41] [HINT] ensure "shared_preload_libraries" includes "repmgr"

And don't see much online as to what the cause could be or how to fix it.

Also, when I do not have the config file set when installing the Helm chart it starts up fine, so it is definitely something to do with the config file in this case / format.

Do you happen to know what can be done to resolve this additional error?

Thank you kindly,
Brent

**Comment by juan131** [comment]
Hi @bborovan

When you set the `postgresql.configuration` parameter, the container skips several parts of the initialization logic, see:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/12/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L577

As you can see in that script there are several functions only executed if `is_boolean_yes "$create_conf_file"` returns `true`. 

In other words, it relies on you 100% on configuring many aspects of PostgreSQL and it's highly likely that something fails booting the cluster.

I think it's much better for you to set the `postgresql.extendedConf` parameter instead. This paramater extends the configuration generated by the container on a "normal" initialisation instead of replacing it. Find more info in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf

**Comment by SamDecrock** [comment]
For anyone looking for an example. This is how you add extra config using the values file:

```yaml
primary:
  ## @param primary.extendedConfiguration Extended PostgreSQL Primary configuration (appended to main or default configuration)
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf
  ##
  extendedConfiguration: |
    log_min_error_statement = DEBUG5
    log_min_messages DEBUG5
    log_error_verbosity = VERBOSE
    log_statement = all
```

Doing this adds an extra ConfigMap named `<my-release>-postgresql-extended-configuration` with a file called `override.conf` which is mounted to `/bitnami/postgresql/conf/conf.d/`

**Comment by SamDecrock** [comment]
@sriram15690 
```yaml
primary:
  ## @param primary.extendedConfiguration Extended PostgreSQL Primary configuration (appended to main or default configuration)
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf
  ##
  extendedConfiguration: |
    encryptionKey = someKey
```

**Comment by henricook** [comment]
Did you find out how to update `shared_buffers`? This extendedConfiguration is working for me for max connections but shared buffers always seems to get set to 4MB even though it accepts the key as valid
