### ISSUE TITLE
[bitnami/mariadb-galera] After all nodes were down and restarted, the create_time of information_schema.tables changed

### ISSUE THREAD

**Issue by Bryce-huang** [bitnami/charts#5076]
**Which chart**:
The name (and version) of the affected chart
mariadb-galera-5.0.1 
**Describe the bug**

After all nodes were down and restarted, the create_time of `information_schema.tables` changed

create_time of `information_schema.tables` becomes the time to rebuild the cluster

**To Reproduce**

1.  create a database and table.
2. query the create_time of information_schema.tables. eg: `select TABLE_NAME,CREATE_TIME from TABLES where TABLE_SCHEMA='your database'`;
3.  reboot all node
4. query create_time of information_schema.tables again

**Expected behavior**
The time when the table was actually created.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"299b6af", GitTreeState:"clean", BuildDate:"2020-11-26T03:58:41Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by Bryce-huang** [comment]
this situation appears in a 3-node kubernetes cluster, and set `safe_to_bootstrap: 0` to `safe_to_bootstrap: 1` 
After checking the `grastate.dat` file, I controlled which node can be started first

**Comment by marcosbc** [comment]
Hi @Bryce-huang, are you forcing a safe-to-bootstrap? If so it could be possible for the create_time of information_schema.tables to be reset.

**Comment by Bryce-huang** [comment]
yes ,I set up safe-to-bootstrap, like this:
```yaml
```

**Comment by Bryce-huang** [comment]
Hi@marcosbc, can you reproduce this problem? I cannot reproduce this problem in a non-container environment. So I think this is a bug.
This is my configuration under non-container：
```ini
[mysqld]
server_id=1
datadir=/data
user=mysql
skip-external-locking
skip-name-resolve
character-set-server=utf8

[galera]
wsrep_on=ON
wsrep_causal_reads=ON
wsrep_provider_options="gcache.size=1G"
wsrep_certify_nonPK=ON
wsrep_provider=/usr/lib64/galera-4/libgalera_smm.so
wsrep_cluster_name=My-Cluster
wsrep_cluster_address="gcomm://20.20.3.70,20.20.3.71,20.20.3.72"
wsrep_node_name=node1
wsrep_node_address=20.20.3.70
wsrep_slave_threads=1
wsrep_sst_method=mariabackup
wsrep_sst_auth='root:123456'
default_storage_engine=InnoDB
log-bin=/data/mysql-bin
log_slave_updates=1
binlog_format=row
query_cache_size=0
innodb_autoinc_lock_mode=2
innodb_flush_log_at_trx_commit=0
innodb_buffer_pool_size=128M
```

Result after restart：

```
+------------+---------------------+
| table_name | create_time         |
+------------+---------------------+
| operator4  | 2021-01-21 09:00:06 |
| operator2  | 2021-01-21 09:00:13 |
| operator1  | 2021-01-21 09:00:45 |

```
My restart steps：
1. checking `grastate.dat` file
2.  If all nodes are: `safe_to_bootstrap: 0`
3. Then select the node with the largest seqno to update `safe_to_bootstrap: 0` and execute `galera_new_cluster` command
 4 Other nodes execute, systemctl start mariad

**Comment by marcosbc** [comment]
Hi @Bryce-huang, thanks for the details.

I don't have any idea why this happen, it could be a bug in how MariaDB is initialized, so I've created an internal task to further investigate this issue. Unfortunately I cannot give an ETA for when we will start working on that, as we are a small team and have a huge backlog.

If you want to investigate on your side, you can find the source for the initialization logic in the [rootfs folder](https://github.com/bitnami/bitnami-docker-mariadb-galera/tree/master/10.5/debian-10/rootfs/opt/bitnami/scripts) for the specific MariaDB Galera branch in the [bitnami-docker-mariadb-galera repo](https://github.com/bitnami/bitnami-docker-mariadb-galera).

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
