### ISSUE TITLE
Fluentd chart has a typo in the ingress.yaml template

### ISSUE THREAD

**Issue by holleyism** [bitnami/charts#5077]
**Which chart**:
fluentd 3.4.0

**Describe the bug**
When trying to apply the fluentd aggregator and enabling the ingress, an error occurs:
Error: failed to create resource: Ingress.extensions "fluentd-aggregator" is invalid:
```
spec.rules[0].http.paths[0].backend.serviceName: Invalid value: "$serviceName": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```
The reason this appears to happen is because `$serviceName` is quoted so is not replaced.

**To Reproduce**
1. Update the values.yaml to enable ingress
2. `helm install my-release -f values.yaml bitnami/fluend`

**Expected behavior**
The chart would be deployed and an ingress created.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by carrodher** [comment]
Thanks for reporting the issue and creating the associated PR, the team will review it

**Comment by holleyism** [comment]
Closing since the PR was merged.
