### ISSUE TITLE
[bitnami/redmine, bitnami/pgadmin] cannot create redmine with persistentVolumeClaim

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/charts#5080]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**
I cannot create redmine when I enable persistentVolume. Although It already bound persistent volume with dynamic nfs-client-provisioner?

**To Reproduce**

**Expected behavior**
I already used dynamic nfs provisioner for persistent volume and it work fine on bitnami/wordpress. But it doesn't work on helm chart bitnami/redmine and bitnami/rabitmq??
Some body help me!! please 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @thanhtai9606 ,
Could you please the errors you are getting? Try to share the describe of the pods and pvc please.

**Comment by thanhtai9606** [comment]
this is describe my redmine pop
`Name:         redmine-56854df6f5-wktg2
Namespace:    kubeapps
Priority:     0
Node:         k8s-worker-2/192.168.104.5
Start Time:   Tue, 19 Jan 2021 14:12:38 +0700
Labels:       app.kubernetes.io/component=redmine
              app.kubernetes.io/instance=redmine
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=redmine
              helm.sh/chart=redmine-15.0.3
              pod-template-hash=56854df6f5
Annotations:  cni.projectcalico.org/podIP: 10.233.74.197/32
              cni.projectcalico.org/podIPs: 10.233.74.197/32
Status:       Pending
IP:           10.233.74.197
IPs:
  IP:           10.233.74.197
Controlled By:  ReplicaSet/redmine-56854df6f5
Init Containers:
  volume-permissions:
    Container ID:  docker://441457d44b34fa1d1190680d4aeded5c2dcaac8cce41d7fcc181ecb77c319054
    Image:         docker.io/bitnami/minideb:buster
    Image ID:      docker-pullable://bitnami/minideb@sha256:0071b4efc7aae20b69dab23da9553a5911fa23cdf9fb4cf131bae5f5cd1bebec
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      mkdir -p "/bitnami/redmine"
      chown -R "1001:1001" "/bitnami/redmine"
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 20 Jan 2021 06:11:34 +0700
      Finished:     Wed, 20 Jan 2021 06:11:34 +0700
    Ready:          False
    Restart Count:  189
    Environment:    <none>
    Mounts:
      /bitnami/redmine from redmine-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redmine-token-pbmqq (ro)
Containers:
  redmine:
    Container ID:   
    Image:          docker.io/bitnami/redmine:4.1.1-debian-10-r209
    Image ID:       
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:http-redmine/ delay=300s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http-redmine/ delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      REDMINE_DB_POSTGRES:     postgres-postgresql.kubeapps.svc
      REDMINE_DB_NAME:         bitnami_redmine
      REDMINE_DB_USERNAME:     postgres
      REDMINE_DB_PASSWORD:     <set to the key 'postgresql-password' in secret 'redmine-externaldb'>  Optional: false
      REDMINE_DB_PORT_NUMBER:  5432
      REDMINE_USERNAME:        user
      REDMINE_PASSWORD:        <set to the key 'redmine-password' in secret 'redmine'>  Optional: false
      REDMINE_EMAIL:           thanhtai42@gmail.com
      REDMINE_LANG:            en
    Mounts:
      /bitnami/redmine from redmine-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redmine-token-pbmqq (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  redmine-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-redmine
    ReadOnly:   false
  redmine-token-pbmqq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redmine-token-pbmqq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                   Message
  ----     ------   ----                    ----                   -------
  Warning  BackOff  2m55s (x4355 over 16h)  kubelet, k8s-worker-2  Back-off restarting failed container
`
this is my pv,pvc
`
Name:            pvc-e0f22f53-ddd1-4de0-b4c1-9dacac634da3
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: cluster.local/nfs-client-nfs-client-provisioner
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    nfs-client
Status:          Bound
Claim:           kubeapps/pvc-redmine
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        8Gi
Node Affinity:   <none>
Message:         
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    192.168.104.3
    Path:      /srv/nfs/kubedata/kubeapps-pvc-redmine-pvc-e0f22f53-ddd1-4de0-b4c1-9dacac634da3
    ReadOnly:  false
Events:        <none>

`
this is my pvc
`
Name:          pvc-redmine
Namespace:     kubeapps
StorageClass:  nfs-client
Status:        Bound
Volume:        pvc-e0f22f53-ddd1-4de0-b4c1-9dacac634da3
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-client-provisioner
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      8Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    redmine-56854df6f5-wktg2
Events:        <none>
`
I work fine when I try deploy jenkin. But this is not working
Please help me

**Comment by thanhtai9606** [comment]
I solved my problem, /etc/exports miss this no_root_squash,no_all_squash on NFS. This is the problem
`/srv/nfs/kubedata  *(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)`
Thank you!!
