### ISSUE TITLE
RabbitMQ not installing - Error: roles.rbac.authorization.k8s.io

### ISSUE THREAD

**Issue by tweetysat** [bitnami/charts#5081]
I'm trying to install RabbitMQ chart on my company kubernetes cluster.

I already managed to install (also from bitnami) redis and consul charts.

But there is a problem with the rabbitmq chart.

I first pulled the chart to modify the repository because the image must be pulled from internal harbor repository (I also pushed the image there).

So when trying

`helm install my-rabbitmq .`

I have

```
Error: roles.rbac.authorization.k8s.io "my-rabbitmq-endpoint-reader" is forbidden: user "oidc:toto" (groups=[...]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["events"], Verbs:["create"]}
```

I'm quite new with kubernetes.  What can I do ?

**Comment by alemorcuq** [comment]
I think you may need to contact your cluster's admin. It looks like you don't have permissions to do this.

**Comment by tweetysat** [comment]
Ok, but till now I managed to install lot of things. 
So what's the specificity of that chart ?  Which part of the chart requires a 'special' permission that I wouldn't have ?

**Comment by tweetysat** [comment]
It seems the "problem" comes from roles.yaml
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
I commented those 3 lines and now everything seems working.
What could be the impact of doing so ?
I can connect to the console.
I will now try to use it with my application.

**Comment by alemorcuq** [comment]
That will prevent the chart from creating events. However, I can't tell you if that is going to break something in the application if it depends on those events to function. It's possible that some k8s native features don't work as expected.

**Comment by fredgate** [comment]
A chart itself does not create events.  
The role `my-rabbitmq-endpoint-reader` is binded to user account declared in the chart, and this service account is attached to the statefulset :
https://github.com/bitnami/charts/blob/7932e1b2a7d9387d5eb8d1e7ec455c6cda4fde93/bitnami/rabbitmq/templates/statefulset.yaml#L43
I don't see why the RabbitMQ Docker image (in Statefulset) needs to run with a service account having the `create event` permission. If someone could explain that.

This permission is blocking us as the chart is deployed in a namespace of the cluster by a service account that is binded to role `admin` and this role has only actions `get, list, watch` for resource `event`. The role `cluster-admin` has all permissions for `event`.

**Comment by andresbono** [comment]
Hi @fredgate, the rule to create events seems required for the `rabbitmq_peer_discovery_k8s` plugin. Please check the PR where it was added: https://github.com/bitnami/charts/pull/2173.

Maybe you can set `rbac.create=false` when installing and upgrading the helm chart and manually create k8s manifests for `Role` and `RoleBinding` that suit the requirements in your cluster.

**Comment by manisha-tanwar** [comment]
Hi I'm also facing the same error, it used to work earlier. This is what I've configured. 
```
rabbitmq:
  enabled: true
  rbac:
    create: false
  serviceAccount:
    create: false
    name: rabbitmq    
```

getting error:

> Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: roles.rbac.authorization.k8s.io "stackstorm-rabbitmq-ha" is forbidden: User "system:serviceaccount:linuxandvirtualisation:linuxandvirtualisation-deploy" cannot get resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "stackstorm-test"
helm.go:81: [debug] roles.rbac.authorization.k8s.io "stackstorm-rabbitmq-ha" is forbidden: User "system:serviceaccount:linuxandvirtualisation:linuxandvirtualisation-deploy" cannot get resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "stackstorm-test"

**Comment by andresbono** [comment]
Hi @manisha-tanwar, if those values were working earlier but not now, it means that now your cluster enabled RBAC. You either need to configure the rules manually or let the chart configure them for you.

**Comment by manisha-tanwar** [comment]
Thanks for the response @andresbono 
```
Rbac:
  Create: false
```
resolved issue for me!

**Comment by fredgate** [comment]
I am using GitLab dynamic environments, and I want to deploy the rabbitmq chart using a service account scoped to a dynamic namespace with the ClusterRole `admin`. This is a predefined Kubernetes role that can do a lot of things in the namespace, but it can only read Event resources (list, get, watch).

**Comment by andresbono** [comment]
Hi @fredgate, what are the parameters that you are using to deploy the chart? Are you using the [RBAC parameters](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#rbac-parameters)?

**Comment by fredgate** [comment]
For moment I use the default parameters. But the problem is that I am in CI job that has the token of a service account with a RoleBinding for the ClusterRole `admin` (predefined by k8s)

**Comment by andresbono** [comment]
Then, in your case, you will need to install the chart with the following values:

```
rbac:
  create: false
serviceAccount:
  create: false
  name: <the_existing_service_account>
```

But keep in mind that, as @alemorcuq [said](https://github.com/bitnami/charts/issues/5081#issuecomment-763801251), some k8s features might not work as expected. The `create` rule for `Event was introduced here: https://github.com/bitnami/charts/pull/2173, required for the `rabbitmq_peer_discovery_k8s` plugin.

**Comment by zerthimon** [comment]
I'm trying to install rabbitmq chart as a dependency in a dynamic environment of gitlab.
Gitlab installs charts under ClusterRole `admin`, which doesn't have the `create` verb for resource `events`, the chart fails to install.

Having `--set rbac.create=false` helps, but the container crashes, because `rabbit_peer_discovery_k8s` plugin cannot authenticate with kube API.
Tried to disable the `rabbit_peer_discovery_k8s` plugin with `--set plugins=rabbitmq_management` made the container crash also. This is probably because of the `cluster_formation.*` lines in the config.

Is there a way to disable clustering entirely via helm's values ?

**Comment by marcosbc** [comment]
Hi @zerthimon, it seems like it is not possible to disable those lines at the moment.

However, it seems like that may have an easy fix. By modifying the lines around [`values.yaml` L207](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L207) adding a conditional (and a new `clustering.enabled` option) it should be able to do what you ask. Would you be up for contributing any required changes via a PR?

**Comment by zerthimon** [comment]
> Would you be up for contributing any required changes via a PR?

Sure, would the `clustering.enabled` option suffice, or should it also depend on `rbac.create` of `plugins` values ?

**Comment by marcosbc** [comment]
I think that `clustering.enabled` would be more than enough, even if it needs to be combined with other options like `plugins`. As long as it gives the possibility to disable those configurations, one way or another, it is fine.

**Comment by zerthimon** [comment]
> Would you be up for contributing any required changes via a PR?
@marcosbc 
Done

**Comment by pmorch** [comment]
A very similar issue was filed as #2227 and `clustering.enabled: false` from PR #6129 also fixed that issue.
