### ISSUE TITLE
[bitnami/harbor] Image version update to fix proxy cache bug

### ISSUE THREAD

**Issue by ioannissavvaidis** [bitnami/charts#5089]
**Which chart**:
Harbor 9.4.1

**Describe the bug**
The bug is already described and fixed in : https://github.com/goharbor/harbor/issues/13740#

pull requests from Docker 20.10 via proxy-cache get :
```
Error response from daemon: missing or empty Content-Type header
```
From the mentioned issue, Harbor v2.1.3 contains this fix.
In the latest Bitnami's Harbor chart the appVersion is: https://github.com/bitnami/charts/blob/20a02814afda5b4bc1b447f5d2cb0fa472f24223/bitnami/harbor/Chart.yaml#L4

While some images are in the previous version: https://github.com/bitnami/charts/blob/20a02814afda5b4bc1b447f5d2cb0fa472f24223/bitnami/harbor/values.yaml#L17

Can you please sync the image versions, in order to get the bug fix?

Thank you!

**Comment by marcosbc** [comment]
Hi @ioannissavvaidis, thanks for reporting this. I've launched Harbor 2.1.3 container image releases, so hopefully it should be updating during the night or tomorrow.

**Comment by ioannissavvaidis** [comment]
Hi @marcosbc, thanks for your response!

**Comment by ioannissavvaidis** [comment]
Hi @marcosbc 
New chart version fixed the issue! 

Thank you!
