### ISSUE TITLE
Notice: New Helm version prerequisite

### ISSUE THREAD

**Issue by FraPazGal** [bitnami/charts#5091]
Bitnami Helm Charts will be bumping the required Helm version from `3.0-beta3+` to `Helm v3.1.0`. This comes from our implementation of a new functionality, `lookup` function, that was introduced on Helm 3.1. This new feature will allow us to improve password's management during upgrades.

You can find more information about our implementation at https://github.com/bitnami/charts/pull/4831.

**Comment by Babakbabak952** [comment]
###
