### ISSUE TITLE
[bitnami/harbor] JobService should be a statefulset

### ISSUE THREAD

**Issue by Antiarchitect** [bitnami/charts#5092]
According to the current behavior (cannot increase jobservice.replicas to 2 because of the multiattach volume error) JobService should be a statefulset. I can submit a PR if I am actually correct and it should be a STS.

**Comment by andresbono** [comment]
Hi @Antiarchitect, thanks for opening this issue. Could you please share what is the particular error and how can we reproduce it?

I have just installed the helm chart with 2 replicas for the jobservice but I didn't get any errors:

```
helm install harbor bitnami/harbor --set jobservice.replicas=2
```

**Comment by Antiarchitect** [comment]
```
  Normal   Scheduled           43s   default-scheduler        Successfully assigned app-xxx-public-registry/app-xxx-public-registry-harbor-jobservice-69b4bd57b-2l9nk to worker-5.prod.xxx
  Warning  FailedAttachVolume  44s   attachdetach-controller  Multi-Attach error for volume "pvc-515be9ea-7a74-481c-9eab-25767dc0a18b" Volume is already used by pod(s) app-xxx-public-registry-harbor-jobservice-549ff45db8-srz7l
  ```

**Comment by Antiarchitect** [comment]
Even when jobservice image is updated it cannot spawn new generation of pods because of this error sts should solve this problem

**Comment by andresbono** [comment]
Hi @Antiarchitect, but would it make sense to use different volumes for each replica? I'm thinking on the following alternatives:

- Set the `jobservice.jobLogger` value to a different value than `file`.
- Use a different storage class with ReadWriteMany access.
- Modify the affinity settings so that all the replicas are scheduled in the same node.

**Comment by Antiarchitect** [comment]
@andresbono I see now. Missed jobLogger parameter. Thank you so much!
