### ISSUE TITLE
[memcached] Always mount an emptyDir on /tmp

### ISSUE THREAD

**Issue by judge-red** [bitnami/charts#5094]
**Which chart**:
memcached

**Describe the bug**
There's three ways to configure the architecture and persistence:
1. `architecture: standalone`
2. `architecture: high-availability` AND `persistence.enabled: true`
3. ` architecture: high-availability` AND `persistence.enabled: false`

With the third configuration, NO `emptyDir` is mounted under `/tmp`. This becomes an issue if `securityContext.readOnlyRootFilesystem` is set to `true`, as the docker images requires a writable `/tmp`.

Thus, kindly always mount an `emptyDir` on `/tmp`. Or at least do so when `securityContext.readOnlyRootFilesystem` is set to `true`.

**To Reproduce**

1. Configure `architecture: high-availability`
2. Configure `persistence.enabled: false`
3. Configure `securityContext.readOnlyRootFilesystem: true`
4. Install Chart with those settings
5. See error in logs

The error will look something like this:
`/run.sh: line 28: cannot create temp file for here-document: Read-only file system`

**Expected behavior**
No error / crash, because `/tmp` is writable.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-12-11T15:42:23Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This is a follow up / precision to my earlier issue #5065 as well as my report against the `bitnami-docker-memcached` image (https://github.com/bitnami/bitnami-docker-memcached/issues/68).

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for spotting this.
  I will create a PR to fix this issue.

**Comment by ANGkeith** [comment]
fixed by #5047

**Comment by rafariossaa** [comment]
Hi,
  @ANGkeith thanks for mentioning this.
  @judge-red I am sorry, This issue got untracked and I did not provide the patch. Could you check if it is fixed for you too ?.

**Comment by judge-red** [comment]
@rafariossaa Yes, works for me now, thanks
