### ISSUE TITLE
Redis ACl and Client Connection

### ISSUE THREAD

**Issue by 8297530225** [bitnami/charts#5140]
Hi Team,

I have deployed Bitnami Redis cluster in our environment. As LDAP is not possible in open source bitnami I have created multiple ACL users and given permissions for those users.

So,
1. Is there any way to connect directly to Redis DB with those ACL users through redis client.
Currently when I try to connect through redis client am using following connection string:
redis-cli -h hostid -p 6379 -a password
But with this, first am logging to redis db default user and from there again I need to use AUTH to switch to that particular user.

But I dont want my clients to  directly connect to redis default user as it is not secure to give(they can change default user password). Please suggest me if clients can directly connect to particular ACL USER .

If this is not possible please suggest me if anything else can be done to secure the client connection. Thanks

**Comment by dani8art** [comment]
Hi @8297530225,

Thanks for opening this issue. Have you tried to execute the command with those parameters?

```
  --user <username>  Used to send ACL style 'AUTH username pass'. Needs -a.
  --pass <password>  Alias of -a for consistency with the new --user option.
```

**Comment by 8297530225** [comment]
Hi @dani8art ,

I have tried with the following format through redis client pod but its saying authentication failed:
I have set the ACL user test with password and used in the connection string.

 redis-cli -h host id -p 6379 --user test --pass <password>

**Comment by dani8art** [comment]
Could you share with us your ACL configuration, please?

**Comment by 8297530225** [comment]
I have configured acl users  in redis db with the following command

Acl setuser test on >redis1234

Where redis1234 is password and test is username

 Using Auth test redis1234 ..am switching to that user.. but am unable to
coonect through client to acl user directly.. I do not want default user to
come in between.. please help

**Comment by dani8art** [comment]
It seems by default ACL are created the most restrictive as possible try to give some access to the user like: https://redis.io/topics/acl#what-happens-calling-acl-setuser-multiple-times

**Comment by ThWoywod** [comment]
Any news about this issue? I noticed the same problem.

**Comment by juan131** [comment]
Hi @ThWoywod 

My colleague @dani8art pointed to the Redis instructions explaining how to create users (see https://redis.io/topics/acl#creating-and-editing-users-acls-with-the-acl-setuser-command). As you can see, by default the users created have restrictive permissions:

> New users are created with restrictive permissions by default. Starting with Redis 6.2, ACL provides Pub/Sub channels access management as well. To ensure backwards compatibility with version 6.0 when upgrading to Redis 6.2, new users are granted the 'allchannels' permission by default. The default can be set to reset channels via the acl-pubsub-default configuration directive.

And then it explains how to provide access to that users to some commands so it can run actions such as "GET". Did you follow these steps?
