### ISSUE TITLE
[bitnami/harbor] Bugs in the deployed version of Trivy reporting false positives for npm and RubyGems

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#5142]
**Which chart**:
Harbor 9.4.1

**Describe the bug**
The chart deploys the harbor-scanner-trivy version v0.14.1, which has bugs in how it reports npm and RubyGem vulnerabilities (due to using trivy 0.9.2). They resolved this issue in Trivy 0.13.0, which is included in the harbor-scanner-trivy plugin from version v0.15.0 on; the current version is v0.17.0. 

**To Reproduce**
Use the built-in trivy to scan a container with RubyGems with suffixed versions (see issue here: https://github.com/aquasecurity/trivy/issues/108). 
 
**Expected behavior**
The built-in trivy to scan without issues. Upgrading the built-in version of the harbor-scanner-trivy plugin to version 0.15.0 or greater should resolve this.

**Comment by alemorcuq** [comment]
Hi, @ajchiarello.

We are using versions `0.9.2` and `0.14.1` of Trivy and the scanner as they are the ones that Harbor 2.1.3 (the latest version of Harbor and the one included in the chart) uses. See: https://github.com/goharbor/harbor/blob/v2.1.3/Makefile#L107

We will update them when Harbor releases a new version.
