### ISSUE TITLE
PmaAbsoluteUri as in https://docs.phpmyadmin.net/en/latest/config.html#cfg_PmaAbsoluteUri

### ISSUE THREAD

**Issue by larryzhu2018** [bitnami/charts#5144]
**Which chart**:
The name (and version) of the affected chart
6.5.7   
**Describe the bug**
how do I set PmaAbsoluteUri so that I can put this under reverse proxy?

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by larryzhu2018** [comment]
Please help. I tried  PMA_ABSOLUTE_URI as follows, and it did not have any effective.

extraEnvVars:
    - name: PMA_ABSOLUTE_URI
      value: https://services.adp.p.c.scs.us-ashburn-1.ocs.oracleiaas.com/phpmyadmin/

**Comment by juan131** [comment]
Hi @larryzhu2018 

Currently we don't support any env. variable to configure that setting using env. vars. Could you please open an issue at https://github.com/bitnami/bitnami-docker-phpmyadmin//issues requesting it to be added? Thanks in advance.

**Comment by larryzhu2018** [comment]
> Hi @larryzhu2018
> 
> Currently we don't support any env. variable to configure that setting using env. vars. Could you please open an issue at https://github.com/bitnami/bitnami-docker-phpmyadmin//issues requesting it to be added? Thanks in advance.

I sent a PR to add the support https://github.com/bitnami/bitnami-docker-phpmyadmin/pull/30/files

now I got back "URL not found" instead of timing out. can you please give a hint how to troubleshoot this new error after setting PmaAbsoluteUri

**Comment by larryzhu2018** [comment]
the issues were resolved when I enabled URL rewrite in the ingress level :-). So this is resolved. thanks.

**Comment by larryzhu2018** [comment]
the issues were resolved via PR  https://github.com/bitnami/bitnami-docker-phpmyadmin/pull/30/files

**Comment by juan131** [comment]
Great!! Thanks so much for the PR!! Someone from the team will review it and ensure they're included in next revisions of the image.
