### ISSUE TITLE
QUESTION: Airflow helm chart support for remote logging to Azure Blob

### ISSUE THREAD

**Issue by VORUSRIK000** [bitnami/charts#5148]
Apache Airlfow supports configuring remote logging, and integrate with Azure Blob as the sink for all logs and metrics. (https://airflow.apache.org/docs/apache-airflow/1.10.14/howto/write-logs.html?highlight=logging#writing-logs-to-azure-blob-storage)

Is this supported through bitnami helm?

**Comment by rafariossaa** [comment]
HI,
  I am sorry, currently our chart does not support remote logging. 
  I am creating a internal task to review this kind of features, and maybe adding then in a future.

**Comment by beltran-rubo** [comment]
@VORUSRIK000 we are also open for pull requests or any contributions to the catalog, any suggestion or change will be welcome and reviewed! Thanks

**Comment by VORUSRIK000** [comment]
Thank you for the update. We are looking at a way to have custom logging enabled. Will revert back if we come up with a way to achieve it using custom helm.

**Comment by rafariossaa** [comment]
That will be great. Thanks forehand .
