### ISSUE TITLE
[bitnami/postgresql-ha] FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by zzguang520** [bitnami/charts#5151]
**Which chart**:
The name (and version) of the affected chart
[root@master ~]# helm list -n test
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
postgresql-ha   test           1               2021-01-20 16:10:31.327186118 +0800 CST deployed        postgresql-ha-6.3.6     11.10.0

**Describe the bug**
error from pod logs:
[root@master ~]# kubectl logs postgresql-ha-postgresql-0 -n test
postgresql-repmgr 09:15:17.37
postgresql-repmgr 09:15:17.37 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 09:15:17.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 09:15:17.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 09:15:17.38
postgresql-repmgr 09:15:17.40 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 09:15:17.42 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 09:15:17.43 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 09:15:17.43 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 09:15:17.47 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 09:15:17.48 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 09:15:17.48 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 09:15:17.66 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 09:15:17.67 INFO  ==> Initializing Repmgr...
postgresql-repmgr 09:15:17.67 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 09:15:17.68 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql-repmgr 09:15:17.69 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 09:15:17.69 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 09:15:17.77 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 09:15:17.80 INFO  ==> Configuring replication parameters
postgresql-repmgr 09:15:17.83 INFO  ==> Configuring fsync
postgresql-repmgr 09:15:17.84 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 09:15:17.87 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-01-20 09:15:18.003 GMT [150] LOG:  pgaudit extension initialized
2021-01-20 09:15:18.004 GMT [150] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-01-20 09:15:18.004 GMT [150] LOG:  listening on IPv6 address "::", port 5432
2021-01-20 09:15:18.071 GMT [150] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-01-20 09:15:18.215 GMT [150] LOG:  redirecting log output to logging collector process
2021-01-20 09:15:18.215 GMT [150] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-01-20 09:15:18.268 GMT [152] LOG:  database system was interrupted; last known up at 2021-01-20 09:10:04 GMT
..2021-01-20 09:15:20.270 GMT [152] LOG:  database system was not properly shut down; automatic recovery in progress
2021-01-20 09:15:20.324 GMT [152] LOG:  invalid record length at 0/1659678: wanted 24, got 0
2021-01-20 09:15:20.325 GMT [152] LOG:  redo is not required
2021-01-20 09:15:20.548 GMT [150] LOG:  database system is ready to accept connections
 done
server started
2021-01-20 09:15:20.623 GMT [161] FATAL:  password authentication failed for user "postgres"
2021-01-20 09:15:20.623 GMT [161] DETAIL:  User "postgres" has no password assigned.
        Connection matched pg_hba.conf line 8: "local    all              all                    md5"
2021-01-20 09:15:20.623 GMT [161] LOG:  could not send data to client: Broken pipe
postgresql-repmgr 09:15:20.62 INFO  ==> ** Starting repmgrd **
[2021-01-20 09:15:20] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
2021-01-20 09:15:20.640 GMT [164] FATAL:  password authentication failed for user "repmgr"
[2021-01-20 09:15:20] [ERROR] connection to database failed
2021-01-20 09:15:20.640 GMT [164] DETAIL:  Role "repmgr" does not exist.
[2021-01-20 09:15:20] [DETAIL]
        Connection matched pg_hba.conf line 1: "host     all            repmgr    0.0.0.0/0    md5"
FATAL:  password authentication failed for user "repmgr"

[2021-01-20 09:15:20] [DETAIL] attempted to connect using:
  user=repmgr password=zaq12wsx connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.test.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=

**To Reproduce**
use helm to install pgsql-ha:
helm install postgresql-ha bitnami/postgresql-ha -n test \
    --set global.storageClass=nfs-client \
    --set global.postgresql.password=zaq12wsx \
    --set global.postgresql.repmgrPassword=zaq12wsx 

storage class nfs-client has been helm to install:
helm install nfs-storage stable/nfs-client-provisioner -n nfs \
   --set nfs.server=x.x.x.x \
   --set nfs.path=/data/nfs-storage

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
[root@master ~]# helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:
```
[root@master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by zzguang520** [comment]
same errors after tried to changed other version of charts

**Comment by alemorcuq** [comment]
This looks similar to #4986 so let's continue in that thread.
