### ISSUE TITLE
I am getting an error while installing the minio chart

### ISSUE THREAD

**Issue by rakeshnambiar** [bitnami/charts#5152]
**Which chart**:
bitnami/minio

**Describe the bug**
I am getting an error while installing the chart.
`Error: parse error at (minio/charts/common/templates/_secrets.tpl:82): function "lookup" not defined`

**To Reproduce**
helm install my-release bitnami/minio -n my-namespace

**Expected behavior**
Installation should be a success

**Version of Helm and Kubernetes**:

K8s - Minor:"17", GitVersion:"v1.17.0"
Helm - Version:"v3.0.2"
- Output of `helm version`:

```
Error: parse error at (minio/charts/common/templates/_secrets.tpl:82): function "lookup" not defined
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
N/A

**Comment by FraPazGal** [comment]
Hi @rakeshnambiar,

Yes, this is a reported issue that has been discussed in #5032. You would need to update your helm version to `3.1` to install the chart. 

I'll be closing this issue as there is already an open one. Please refer to it if you need further help.

**Comment by rakeshnambiar** [comment]
Thanks. That worked.
