### ISSUE TITLE
Kubewatch key tolerations missing in deployment.yaml template

### ISSUE THREAD

**Issue by mariantrifu** [bitnami/charts#5155]
**Which chart**:
Kubewatch versions 3.0.0 to 3.0.4

**Describe the bug**
tolerations key is missing in deployment.yaml template

**To Reproduce**

1. Deploy the chart with values.yaml containing tolerations key
2. Have a node with taint
3. See in error in events that: 1 node(s) had taint {node-group: monitoring}, that the pod didn't tolerate

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting! We will work on adding this to the template. If you want to speed up the process, feel free to open a PR and we will review it.

**Comment by javsalgar** [comment]
Hi,

I created this PR that should fix the issue https://github.com/bitnami/charts/pull/5187

**Comment by mariantrifu** [comment]
Hi, 
Thanks, I'm waiting for PR to be accepted and I'll try again.
