### ISSUE TITLE
When service type is load balancer and the architecture is high availability, the clusterIP is left at 'None' and complains

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#5160]
For memcached 5.4.2, setting...

```
  service:
    type: LoadBalancer
  architecture: high-availability
```

...yields...

`Error: Service "<release>-memcached" is invalid: spec.clusterIP: Invalid value: "None": may not be set to 'None' for LoadBalancer services`

...due to ...

```
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.architecture "high-availability" }}
  clusterIP: None
  {{- end }}
  {{- if and (not (empty .Values.service.loadBalancerIP)) (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
```

I do not need to choose a cluster IP on high availability setting if the service type is ClusterIP, why should I have to make that choice when the service type is LoadBalancer? What do I choose?

**Comment by FraPazGal** [comment]
Hello @zenbones,

This was indeed a bug in the chart. It was addressed in https://github.com/bitnami/charts/pull/5047 and should now be solved. Thanks for reporting this!

**Comment by zenbones** [comment]
I'll close this then. Thanks.
