### ISSUE TITLE
Requesting a 11.x series release for Redis 6.0.10

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [bitnami/charts#5162]
**Which chart**:
redis 11.3.4

**Is your feature request related to a problem? Please describe.**
We're looking to upgrade GitLab from Redis 5.0.9 to 6.0.10. As part of this upgrade, we'd also like to upgrade the chart.

However, we still need to support Helm 2. AFAIK, this means we need to use the 11.x series of the chart (as 12.x is Helm 3 only).

The latest release in that series is `11.3.4`, which defaults to Redis 6.0.9.

**Describe the solution you'd like**
We'd like to get a 11.3.5 release which bumps the Redis version to 6.0.10.

**Describe alternatives you've considered**
We could override `image.tag`, but we'd rather use the default values from the chart if possible.

**Additional context**
Downstream issue: [Bump Redis chart to Redis 6.0.10](https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/1772)

**Comment by carrodher** [comment]
As you rightly said, the last version previous to the Helm 3 changes is `11.3.4` that includes Redis `6.0.9`. From that point, `12.0.0` was released removing the Helm 2 support.
You can use a previous chart major version, such as `11.3.4` but with a recent Redis version by setting a custom `image.tag` value, i.e `image.tag=6.0.10`.

About the tagging policy for images, there is an immutable tag released on a daily basis, such as `6.0.10-debian-10-r3` and then there are some rolling tags that are updated to point to the latest immutable one, for example `6.0` today is pointing to `6.0.10-debian-10-r3`, tomorrow `6.0.10-debian-10-r3` and maybe in a couple of weeks to `6.0.11-debian-10-r0`. There is also `6.0.10` that is going to be updated to the latest daily revision but not to the next patch version. [+info](https://github.com/bitnami/bitnami-docker-redis#supported-tags-and-respective-dockerfile-links)

About releasing the previous chart major version updating the bundled images to the latest version, it is not something supported at this moment by our CI/CDs. What is the reason for not using the above proposal? Is it something we can help with this?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@carrodher Thanks for the in-depth response, we'll go with `image.tag` pinning for now. I'll go ahead and close this.
