### ISSUE TITLE
Helm Chart Variable Misspelling

### ISSUE THREAD

**Issue by cinglese** [bitnami/charts#5166]
The following lines have a variable misspelling:
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml#L342
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml#L344

It currently reads: **.Values.postgresqlTcpKeealivesCount**

The variable should read: **.Values.postgresqlTcpKeepalivesCount**

**Comment by FraPazGal** [comment]
Hello @cinglese,

Thank you for catching this! We have created a PR fixing the typo, it should be merged fairly soon!
