### ISSUE TITLE
[bitnami/keycloak] externalDatabase password could be fetched from existing secret

### ISSUE THREAD

**Issue by hieulengoc** [bitnami/charts#5173]
**Which chart**:
keycloak v1.2.0

**Is your feature request related to a problem? Please describe.**
when using externalDatabase, normally we already have the secret and configmap which contains all information to connect to that database. However, the current chart doesn't support a way to specify those configmap and secret directly but putting the values into the values.yaml. 

**Describe the solution you'd like**
As I can see from the common chart, there is a way to use this existing secret already (https://github.com/bitnami/charts/tree/master/bitnami/common#existingsecret). It would be nice to have this feature.

**Describe alternatives you've considered**
The second way of doing this is checking in the statefulset if another value (e.g .Values.externalDatabase.passwordFromExistingSecret.[secretName, secretKey]) then it will use this value; otherwise, use the current envVar KEYCLOAK_DATABASE_PASSWORD

**Additional context**
N/A

What do you think which way is better?

**Comment by dani8art** [comment]
Hi @hieulengoc, I've created a PR, please let's move the conversation there!

Thanks for the feedback!
