### ISSUE TITLE
airflow install KubernetesExecuter redis.enable=false not working

### ISSUE THREAD

**Issue by cocampbe** [bitnami/charts#5179]
**Which chart**:
airflow 7.1.3

**Describe the bug**
When I run helm install to use the KubernetesExecutor with the seetings per the docs, I get the following error.

```
helm -n airflow install airflow bitnami/airflow --set service.type=LoadBalancer --set executor=KubernetesExecutor --set redis.enabled=false --set rbac.create=true --set serviceAccount.create=true

Error: template: airflow/templates/config/secret-external-redis.yaml:15:54: executing "airflow/templates/config/secret-external-redis.yaml" at <b64enc>: invalid value; expected string
```

**To Reproduce**

1. Run 'helm -n airflow install airflow bitnami/airflow --set service.type=LoadBalancer --set executor=KubernetesExecutor --set redis.enabled=false --set rbac.create=true --set serviceAccount.create=true'

**Expected behavior**
I expect airflow to deploy using the KubernetesExecutor

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
(v3.3.0
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2-6+38ac483e736488", GitCommit:"38ac483e736488517dd754156441b89e0b2060e2", GitTreeState:"clean", BuildDate:"2020-07-07T13:54:17Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5+vmware.1", GitCommit:"1abde2b816bac0da89c6c71360799c681094ca0e", GitTreeState:"clean", BuildDate:"2020-06-29T22:31:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I believe the issue is with the logic in the template. When redis.enabled is set to false the error occurs. When set to true it errors.

**Comment by rafariossaa** [comment]
Hi,
 Thank your for spotting this. 
  Yes, currently the logic fails in the case you don't need redis.
  We will come back with a fix for this. Meanwhile if you want to send a PR we will be glad to review and merge it.

**Comment by dani8art** [comment]
Hi @cocampbe we wanted to check if you were working on this in order to no start working in parallel, did you work on this or are you planning to do it?

Thanks!

**Comment by cocampbe** [comment]
I have not made any changes.

**Comment by dani8art** [comment]
Hi

I've just created a PR, please let's move the conversation there. Thanks!
