### ISSUE TITLE
Best way to purge installation including statefulset PVC?

### ISSUE THREAD

**Issue by migmartri** [bitnami/charts#5199]
Hi!

I am wondering what's the best way to purge the installation of a chart that contains a PVC provisioned by the statefulset controller.

For example in WordPress

```bash
$ helm install wordpress bitnami/wordpress

# I get two PVCs
$ k get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-wordpress-mariadb-0   Bound    pvc-23d5fe75-ecd5-45dc-9bc0-b00f5b0edc6a   8Gi        RWO            standard       11m
wordpress                  Bound    pvc-e9d0a722-9c53-4339-9a3a-4cc2601742fb   10Gi       RWO            standard       11m

# I uninstall the Chart
$ helm delete wordpress 
release "wordpress" uninstalled

# but the MariaDB PVC is still there and that can make new installations of the chart fail.
$ k get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-wordpress-mariadb-0   Bound    pvc-23d5fe75-ecd5-45dc-9bc0-b00f5b0edc6a   8Gi        RWO            standard       13m
```

What's the best way to delete all the chart resources including the ones created by a statefulset that will not require me to delete the statefulset manually?

I could use labels and such but I am wondering if there is something it can be down in the Helm Chart (set ownerReference) to make sure that it gets deleted along with the rest of the resources of the chart.

Thanks!

**Comment by FraPazGal** [comment]
Hi @migmartri!

Unfortunately, doing `helm delete/uninstall` won't delete the persistent volume claims, as they are treated as external resources to the chart installation itself and not managed by Helm. This is the default behaviour and something that may be addressed in Helm 4 https://github.com/helm/helm/issues/5156. For now, I'm afraid you will have to delete the PVCs manually with a `kubectl delete pvc`.
