### ISSUE TITLE
[bitnami/memcached] High availability does not consistently hash

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#5201]
memcached 5.4.3

I have a setup with 2 replicas in high availability. The clients use the service endpoint, which seems to do round robin selection between the 2 instances, which means that keys inserted by one client are not visible to the other half the time. The service endpoint behavior is expected, but because Memcached has no clustering of its own, I would think part of the high availability installation would include mcrouter, or some equivalent. What exactly is the difference between high availability and stand alone then?

**Comment by migruiz4** [comment]
Hi @zenbones,
This chart doesn't implement any mechanism to sync data between replicas.
When installing the Memcached using 'high-availability' architecture, the default service will be configured as a headless service, in other words, it configures K8s to generate a FQDN for each Memcached replica.
I'd recommend configuring your clients to reach the pods individually using the FQDN created by the headless service:
```php
<?php
$m = new Memcached();
$m->addServers(array(
    array('memcached-0.memcached.default.svc.cluster.local', 11211, 20),
    array('memcached-1.memcached.default.svc.cluster.local', 11211, 80),
));
?>
```
