### ISSUE TITLE
Magento GCP Linux BUG

### ISSUE THREAD

**Issue by sportmma** [bitnami/charts#5202]
Hello. Updated Magento GCP to version 2.4.1-6 by mistake. According to your changelog, the latest version is 2.4.1-3. Version 2.4.1-6 is for OS X and sneaks into GCP Linux. I am asking for a quick solution to this problem.

**Comment by javsalgar** [comment]
Hi,

Could you provide more context about this? Which is the instance you were using and how did you perform the upgrade?

**Comment by javsalgar** [comment]
If you are using a Cloud Image, then I suggest you to go to community.bitnami.com. This is for issues with containers and charts.
