### ISSUE TITLE
MYSQL Helm chart - function "lookup" not defined

### ISSUE THREAD

**Issue by entrymon** [bitnami/charts#5205]
**Which chart**:
MySQL chart

**Describe the bug**
Copied latest values.yaml and added password in it from repo - https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml

helm install mysql  bitnami/mysql -f mysql-values.yaml --namespace=default

**To Reproduce**
Copied latest values
try install repo

**Expected behavior**
helm chart should have got deployed

**Version of Helm and Kubernetes**:
Using latest microk8s having k8s - Major:"1", Minor:"19+", GitVersion:"v1.19.5-34+8af48932a5ef06"
Using microk8s helm versions - version.BuildInfo{Version:"v3.0.2"

**Additional context**
Error on console

Error: parse error at (mysql/charts/common/templates/_secrets.tpl:84): function "lookup" not defined
helm.go:76: [debug] parse error at (mysql/charts/common/templates/_secrets.tpl:84): function "lookup" not defined

**Comment by vyshkov** [comment]
same issue on helm chart

**Comment by Pagten** [comment]
Also occurring on the wordpress chart.

**Comment by andresbono** [comment]
Hi all, as @Pagten mentioned, you would need to update your helm version to `3.1` to install the chart as notified in https://github.com/bitnami/charts/issues/5091. 

This is a reported issue that has been discussed in #5032. I'll be closing this issue given that there is already an open one. Please refer to it if you need further help.
