### ISSUE TITLE
[bitnami/influxdb] Cannot mount extra volumes.

### ISSUE THREAD

**Issue by soonoo** [bitnami/charts#5211]
**Which chart**:
bitnami/influxdb

Unlike other charts in bitnami repository, there is no way to mount extra volumes.   
`extraVolumes` and `extraVolumeMounts` properties exist in [bitnami/nginx](https://github.com/bitnami/charts/tree/master/bitnami/nginx) for instance.  
  
Extra volumes are needed to specify [https-certificate](https://docs.influxdata.com/influxdb/v1.8/administration/config/#http-endpoints-settings) configuration in influxdb.

**Comment by dani8art** [comment]
Hi @soonoo thank you so much for your feedback, we are going to merge this PR https://github.com/bitnami/charts/pull/5097 soon and we plan to include this feature as part of it. Would it be fine for you?

**Comment by soonoo** [comment]
It's fine. Thanks a lot @dani8art 
One more question, is there a plan to support [`--ssl` option](https://docs.influxdata.com/influxdb/v1.8/tools/shell/#influx-arguments) in `livenessProbe` and `readinessProbe`?
With `https-enabled` option enabled in influxdb configuration, `livenessProbe` and `readinessProbe` always fail.

**Comment by dani8art** [comment]
There could be a solution if when we release this PR using `custom<liveness|readiness>Probe` properties, something like:
https://github.com/bitnami/charts/blob/master/bitnami/opencart/values.yaml#L477-L483, do you think it could fit your requirements?
