### ISSUE TITLE
Install postgreSQL in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/charts#5225]
PostgreSQL-HA is a powerful, open source object-relational database system that uses and extends the SQL language with High Availability (HA). This documentation will guide you on how to install postgreSQL on the IBM Cloud using the Kubernetes Service. Simple and effective.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105751851-904ecc80-5f14-11eb-9848-1f05642a4438.png)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105751859-92189000-5f14-11eb-9646-187efe4e39ff.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105751891-9a70cb00-5f14-11eb-9882-a7538c672a0e.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105751902-a066ac00-5f14-11eb-9fda-4de8a6ef821a.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105751908-a3fa3300-5f14-11eb-9e56-7900082dc7e8.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105751922-a9f01400-5f14-11eb-84df-53dbd4969377.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105751942-aeb4c800-5f14-11eb-84ed-d93bd255e7b7.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105751951-b2e0e580-5f14-11eb-938a-cb17c505f49d.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105751961-b7a59980-5f14-11eb-8d93-a232c77d216c.PNG)

## Step 3: Install postgreSQL HA

* Click on the search section at the top of the main page, type postgreSQL HA, and click on it.

![post1](https://user-images.githubusercontent.com/70336951/105752915-e4a67c00-5f15-11eb-8536-d493180e5bf2.PNG)

* A new window opens, select the cluster and enter the name you want for the PostgreSQL HA workspace; in this case, it will be called _postgresql-ha-example_; then, go to the bottom to find the workspace parameters.

You can modify the different installation parameters at the bottom. We will leave them by default except for the user password for PostgreSQL and its pool, which you will need to access your PostgreSQL console and work with your databases. You can read more about setting up the parameters, including defining the number of PostgreSQL motors inside the pool [here](https://cloud.ibm.com/catalog/content/postgresql-ha "here").

Make sure you set up a password in the _postgresqlPassword_ and the pgpool.adminPassword variable. 

![psqlha4](https://user-images.githubusercontent.com/70336951/105752004-c4c28880-5f14-11eb-937f-399f23b4f066.PNG)

![psqlha5](https://user-images.githubusercontent.com/70336951/105752019-c8eea600-5f14-11eb-92a5-c6441baf7d26.PNG)

You can create an additional non-admin user if you edit the _postgresql.username_ variable. The admin user will continue to be 'Postgres.' 

![psqlha3](https://user-images.githubusercontent.com/70336951/105752029-cc822d00-5f14-11eb-969c-64ed6ae9bf1b.PNG)

When you're done, accept the terms, and click on *Install*.

![psqlha2](https://user-images.githubusercontent.com/70336951/105752042-d015b400-5f14-11eb-8ec2-41ff91af4eef.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105752122-e3c11a80-5f14-11eb-8f4b-87b03da3c2ec.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105752145-e91e6500-5f14-11eb-99e5-a95daf23a2b3.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105752160-ecb1ec00-5f14-11eb-9194-f13224bffa6d.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105752171-f0457300-5f14-11eb-99f5-8402f8b6927e.PNG)

* Once you have installed the terminal, open it and type the following command. It will show you the workspaces of your cluster. You can see *postgresql-ha-example* is now active.

`$ kubectl get ns`

![testpsqlha1](https://user-images.githubusercontent.com/70336951/105752195-f8051780-5f14-11eb-9563-2bcb99a71a8e.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testpsqlha2](https://user-images.githubusercontent.com/70336951/105752209-fc313500-5f14-11eb-8ff2-43b92b406a86.PNG)

* Find the port of your elected pod, you will need it to start using PostgreSQL. In this case, we will use the PostgreSQL pool pod.

`$ kubectl get service -n NAME SERVICE`

![testpsqlha3](https://user-images.githubusercontent.com/70336951/105752232-02bfac80-5f15-11eb-843a-cd4401084f3c.PNG)

* Select the pod within your service using bash so you can start using PostgreSQL from the terminal.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testpsqlha4](https://user-images.githubusercontent.com/70336951/105752239-06533380-5f15-11eb-96d9-ad91c53d9cf8.PNG)

* Once you're inside the pod terminal, you can execute the following command to login into PostgreSQL and create and manage your databases. Use your previously created password. You can do the same with the other PostgreSQL databases systems or pods within the High Availability installation.

`$ psql -h localhost -U postgres --password -p 5432`

![testpsqlha5](https://user-images.githubusercontent.com/70336951/105752256-0c491480-5f15-11eb-9b3d-b4fffff796a2.PNG)

You have finished the installation, enjoy your PostgreSQL HA installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
