### ISSUE TITLE
Airflow setup on AKS with external PostgreSQL and Redis using SSL

### ISSUE THREAD

**Issue by VORUSRIK000** [bitnami/charts#5226]
We are setting up Airflow on AKS using bitnami helm charts. We are using a dedicated PostgreSQL and Redis resources on azure and configured helm install parameters accordingly. But, our company mandates using SSL only on PostgreSQL and Redis. On enabling this, airflow containers were not getting started due to connection issues.

Wanted to check if this is supported in the current setup? If yes, what are the right settings we need to enable? If not, is there a workaround to support SSL only?

**Comment by dani8art** [comment]
Hi @VORUSRIK000,

Regarding airflow container docs you could use https://github.com/bitnami/bitnami-docker-airflow#use-an-existing-database

```
- AIRFLOW_DATABASE_USE_SSL: Set to yes if the database is using SSL. Default: no
- AIRFLOW_REDIS_USE_SSL: Set to yes if Redis uses SSL. Default: no
```

It seems these values have not been mapped to the charts yet, however, you can use `extraEnvVars` to set them up

```
extraEnvVars:
  - name: AIRFLOW_DATABASE_USE_SSL
    value: yes
  - name: AIRFLOW_REDIS_USE_SSL
    value: yes
```

Thanks!

**Comment by VORUSRIK000** [comment]
This is working. Thx.

**Comment by rafariossaa** [comment]
Hi,
  I am happy it worked for you.

**Comment by VORUSRIK000** [comment]
Apologise for re-opening this. But facing some issues lately with Redis and want to check on it. Initially, when we set the above env variables, all components were working properly. Recently, we started seeing issue with Worker not able to connect to Redis using SSL. Error is "ERROR/MainProcess] consumer: Cannot connect to redis://:**@<REDIS URL>:6380/1: Error while reading from socket: (104, 'Connection reset by peer')."
I checked the redis connectivity using console and it is working fine. No events logged in Azure portal either. No change happened on the settings or keys.
Now, am getting same error when I removed and re-installed airflow.
SQL Connection is working fine with SSL and no issues with it.

Any pointers?

**Comment by rafariossaa** [comment]
Hi,
  That `connection reset by peer` lead me think that it could it be that redis is closing connections due to inactivity.
  I found a similar issue [here](https://github.com/andymccurdy/redis-py/issues/1186) .
  Does this make sense in your scenario ?

**Comment by VORUSRIK000** [comment]
I did look at this, and it is possible redis is closing idle connections. I checked azure logs for redis resource, but didnt find any errors or message indicating this. 
Also, most of the suggestions in the attached thread refer to the code changes related to calling redis cache and setting "health_check_interval". Considering we are using Airflow OOB, assume this is already handled within the framework code.
I assume, it must be some additional configuration enabled (did check airflow image config values, but didnt find any), or some setting on the redis itself that we need to do.
I tried uninstalling and installing airflow and facing same error now.
Also tried creating a new redis cache instance and used that during installation, and still same issue.
Any thoughts?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry I don't know that details about airflow. Is this only happening when using SSL ?
  I think it is not a matter of an error in your current deployment but in how it works. 
  Did you tried to post the question in airflow forums ? Maybe they can provide some clues.
