### ISSUE TITLE
[bitnami/redis] update README.md for the usage of metrics.extraArgs when redis tls is enabled

### ISSUE THREAD

**Issue by drmy** [bitnami/charts#5228]
**Which chart**:
[bitnami/redis]

**Describe the bug**
There is a typo introduced in the PR #5207 - https://github.com/bitnami/charts/pull/5207

**To Reproduce**
Browse the page:
https://github.com/bitnami/charts/tree/master/bitnami/redis#metrics

**Expected behavior**
Host Kernel Settings is a in a separate section.

**Version of Helm and Kubernetes**:
bitnami/redis 12.6.4

**Comment by carrodher** [comment]
Thanks for the quick fix
