### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Proxy configuration

### ISSUE THREAD

**Issue by CEDDM** [bitnami/charts#5235]
**Which chart**:
spring-cloud-dataflow

**Is your feature request related to a problem? Please describe.**
Dealing with company proxy is quite painfull to make SCDF communicate with Maven and Docker Hub for starter apps, for instance

**Describe the solution you'd like**
Having parameters in the chart, like the JVM params (proxyHost, proxyPort, proxyUser, proxyPwd, nonProxyHosts) to automatically configure the proxy for SCDF

**Describe alternatives you've considered**
Today we have to edit the SCDF deployment yaml after the installation and modify several parameters to add proxy configuration for Maven metadata jar and Docker Labels.

**Comment by miguelaeh** [comment]
Hi @CEDDM ,
thank you very much for the suggestion. Would you like to create a PR doing the needed modifications?

**Comment by CEDDM** [comment]
Hi @miguelaeh ,
I would be happy to help but I'm not familiar with Helm Charts. I just tried by cloning the GitHub repo but I have trouble with dependencies when making a dry-run with my local files (missing index.yaml I think). I don't know how to test my changes ...

**Comment by miguelaeh** [comment]
HI @CEDDM 
To test the changes locally you should execute `helm dependencies update` from the chart directory to fetch the dependencies before install it using sominthing like:
```
helm install release-name .
```

**Comment by CEDDM** [comment]
Thanks ! That helps !
I will try to submit a PR shortly

**Comment by CEDDM** [comment]
First PR for me ! Hope I did it right ...

**Comment by miguelaeh** [comment]
Thank you very much @CEDDM ,
We will take of it, so let's move the thread there.
