### ISSUE TITLE
[bitnami/keycloak] typo in readme documentation

### ISSUE THREAD

**Issue by snoopfab** [bitnami/charts#5237]
There's a typo in the  Database parameters section of the documentation : 

| `postgresql.postgresqlPassword`  | Password for the **Dicourse** user - ignored if existingSecret is provided       | `some-password`    |

Dicourse => PostgreSQL

**Comment by FraPazGal** [comment]
Hi @snoopfab,

Thanks for pointing this out! We'll create a PR fixing this shortly.

**Comment by snoopfab** [comment]
Thanks for the quick fix !
