### ISSUE TITLE
[bitnami redis-cluster] liveness probe does not check if redis cluster creation was successful

### ISSUE THREAD

**Issue by f18m** [bitnami/charts#5262]
**Which chart**:
Redis-cluster version 12.1.1

**Describe the bug**
In my case I misconfigured the redis cluster by providing "cluster.nodes: 3" and "cluster.replicas: 1".
In such configuration redis-cli will refuse to create a cluster saying that to have 1 replica at least 6 nodes are required to maintain the minimum of 3 master nodes present in the cluster.
However detecting such misconfiguration required me to issue the "cluster info" command, see that the cluster was in "fail" state and then inspect the logs of the init job to find out the reason.

**To Reproduce**

1. Install bitnami redis-cluster chart with invalid configuration, e.g. 3 nodes and 1 replicas
2. Inspect the init job logs

**Expected behavior**
I would expect instead the cluster liveness probe to fail in such a case... a quick inspect of the "/scripts/ping_liveness_local.sh" script reveals that it's sending a simple "ping" command... can we enhance that liveness probe to also check for redis cluster health by using "cluster info | grep cluster_state" ?

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12+k3s1", GitCommit:"56cd36302dc3188f21f9877d1309df7d80cd8b7d", GitTreeState:"clean", BuildDate:"2020-11-13T06:12:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by migruiz4** [comment]
Hi @f18m ,

Thank you for reporting this issue and for the detailed instructions to reproduce it.
As you described, the pods will show as up and ready, even though the cluster status has failed:
```
redis-cluster-0                         1/1     Running       0          28s
redis-cluster-1                         1/1     Running       0          27s
redis-cluster-2                         1/1     Running       0          27s
redis-cluster-cluster-create-89v77      0/1     Completed     0          27s
```

```sh
I have no name!@redis-cluster-0:/$ redis-cli
127.0.0.1:6379> CLUSTER INFO
cluster_state:fail
cluster_slots_assigned:0
cluster_slots_ok:0
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:0
cluster_current_epoch:0
cluster_my_epoch:0
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
```

I will create an internal task to solve this issue.
