### ISSUE TITLE
[open edx koa.1] fail to create AWS instance

### ISSUE THREAD

**Issue by maxsmadt** [bitnami/charts#5264]
I tried to create an Open Edx Koa.1 instance following this page [https://bitnami.com/stack/edx/cloud](url). However, I got stuck every time in `Create key pair 24%`.
![Screenshot 2021-01-27 at 11 17 20 AM](https://user-images.githubusercontent.com/67141360/105937817-46d7bc00-6091-11eb-8729-16bd333f3ff4.png)

**Comment by maxsmadt** [comment]
Aws::EC2::Errors::AuthFailure : AWS was not able to validate the provided access credentials

**Comment by juan131** [comment]
Hi @maxsmadt 

Please note this is the Bitnami Helm charts repository. This repository is intended to share the Bitnami solutions for Kubernetes, and help users using them.

For questions related to Bitnami SingleVMs or Cloud Image, we provide support through our Community website:

- https://community.bitnami.com/

You'll find a lot of information about edX and other solutions there, and our team will be glad to help you.

I also recommend you to visit the edX documentation for AWS in the link below:

- https://docs.bitnami.com/aws/apps/edx/
