### ISSUE TITLE
default config：helm install mysql bitnami/mysql error

### ISSUE THREAD

**Issue by tulid** [bitnami/charts#5265]
**Which chart**:
The name (and version) of the affected chart
bitnami/mysql latest and some other versions

**Describe the bug**
mysql logs：
```
mysql 06:39:08.27 
mysql 06:39:08.27 Welcome to the Bitnami mysql container
mysql 06:39:08.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 06:39:08.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 06:39:08.27 
mysql 06:39:08.28 INFO  ==> ** Starting MySQL setup **
mysql 06:39:08.29 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 06:39:08.30 INFO  ==> Initializing mysql database
mysql 06:39:08.31 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 06:39:08.31 INFO  ==> Using persisted data
mysql 06:39:08.34 INFO  ==> Running mysql_upgrade
mysql 06:39:08.35 INFO  ==> Starting mysql in background
```

kubernetes describe

```
Warning	Unhealthy	Readiness probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure. mysqladmin: connect to server at 'localhost' failed error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)' Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!	4 minutes ago
Warning	BackOff	Back-off restarting failed container	9 minutes ago
Normal	Pulled	Container image "docker.io/bitnami/mysql:8.0.23-debian-10-r0" already present on machine	18 minutes ago
Warning	Unhealthy	Readiness probe failed: cannot exec in a stopped state: unknown	24 minutes ago
Warning	Unhealthy	Liveness probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure. mysqladmin: connect to server at 'localhost' failed error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)' Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!	39 minutes ago
```
**To Reproduce**
```
helm install mysql bitnami/mysql
```

**Comment by carrodher** [comment]
Hi, I am not able to reproduce this issue on my side. In order to try to reproduce the issue on our side, can you provide the following information?
- What k8s cluster are you using?
- Are you installing the chart from scratch or it is not the first time? If you installed it previously with the same name (even it was not successful), can you check if there are some stuck resources? Mainly check if there are some PV/PVCs related to MySQL, in that case, please, take into account `helm delete` doesn't delete PV/PVC and you need to manually remove them by running `kubectl delete pvc` before trying to install it again reusing the release name

**Comment by tulid** [comment]
> Hi, I am not able to reproduce this issue on my side. In order to try to reproduce the issue on our side, can you provide the following information?
> 
> * What k8s cluster are you using?
> * Are you installing the chart from scratch or it is not the first time? If you installed it previously with the same name (even it was not successful), can you check if there are some stuck resources? Mainly check if there are some PV/PVCs related to MySQL, in that case, please, take into account `helm delete` doesn't delete PV/PVC and you need to manually remove them by running `kubectl delete pvc` before trying to install it again reusing the release name

**Comment by tulid** [comment]
$  docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
--------------------------------------------------------------------------------------------------------------
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
--------------------------------------------------------------------------------------------------------------
The volume is based on nfs.
And the nfs permissions is as follow:
$ ls -hl /mnt/ | grep nfs
drwxr-xr-x 12 root root 4.0K Jan 27 20:15 nfs-server
--------------------------------------------------------------------------------------------------------------
Before I  try installing the chart every time，i will delete related pvc and pv。

**Comment by soufianebenali** [comment]
Hi have the same issue and enabling the debug mode I can provide more details:

```
mariadb 12:10:12.13 
mariadb 12:10:12.13 Welcome to the Bitnami mariadb container
mariadb 12:10:12.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 12:10:12.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 12:10:12.14 
mariadb 12:10:12.15 INFO  ==> ** Starting MariaDB setup **
mariadb 12:10:12.17 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 12:10:12.17 INFO  ==> Initializing mariadb database
mariadb 12:10:12.18 DEBUG ==> Ensuring expected directories/files exist
mariadb 12:10:12.19 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 12:10:12.20 INFO  ==> Using persisted data
mariadb 12:10:12.23 INFO  ==> Running mysql_upgrade
mariadb 12:10:12.23 INFO  ==> Starting mariadb in background
2021-01-28 12:10:12 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.5.8-MariaDB) starting as process 50 ...
2021-01-28 12:10:12 0 [Note] InnoDB: Using Linux native AIO
2021-01-28 12:10:12 0 [Note] InnoDB: Uses event mutexes
2021-01-28 12:10:12 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-01-28 12:10:12 0 [Note] InnoDB: Number of pools: 1
2021-01-28 12:10:12 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-01-28 12:10:12 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
2021-01-28 12:10:12 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2021-01-28 12:10:12 0 [Note] InnoDB: Completed initialization of buffer pool
2021-01-28 12:10:12 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2021-01-28 12:10:12 0 [Note] InnoDB: 128 rollback segments are active.
2021-01-28 12:10:12 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-01-28 12:10:12 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-01-28 12:10:12 0 [Note] InnoDB: 10.5.8 started; log sequence number 48794; transaction id 20
2021-01-28 12:10:12 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2021-01-28 12:10:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-01-28 12:10:12 0 [Note] Server socket created on IP: '127.0.0.1'.
2021-01-28 12:10:12 0 [Note] InnoDB: Buffer pool(s) load completed at 210128 12:10:12
2021-01-28 12:10:12 0 [Warning] 'proxies_priv' entry '@% root@myapp-mariadb-0' ignored in --skip-name-resolve mode.
2021-01-28 12:10:12 0 [Note] Reading of all Master_info entries succeeded
2021-01-28 12:10:12 0 [Note] Added new Master_info '' to hash table
2021-01-28 12:10:12 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.5.8-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2021-01-28 12:10:14 3 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
FATAL ERROR: Upgrade failed
mariadb 12:10:14.28 INFO  ==> Stopping mariadb
2021-01-28 12:10:14 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
2021-01-28 12:10:14 0 [Note] Event Scheduler: Purging the queue. 0 events
2021-01-28 12:10:14 0 [Note] InnoDB: FTS optimize thread exiting.
2021-01-28 12:10:14 0 [Note] InnoDB: Starting shutdown...
2021-01-28 12:10:14 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
2021-01-28 12:10:14 0 [Note] InnoDB: Buffer pool(s) dump completed at 210128 12:10:14
2021-01-28 12:10:14 0 [Note] InnoDB: Shutdown completed; log sequence number 48806; transaction id 21
2021-01-28 12:10:14 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-01-28 12:10:14 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
```

And I have this issue only when I override the following on values.yaml:

```
auth:
  rootPassword: "myrootpassword"
  database: myapp-mariadb
  username: "myapp-db"
  password: "mypassword"
```

**Comment by carrodher** [comment]
@tulid are you deploying the chart with some custom parameters (via `--set` or by modifying the _values.yaml_)?

Although the container is stopped, sometimes it is something expected as part of the initialization process. BTW @soufianebenali please note you are using MariaDB instead of MySQL so it is a different chart and probably a different issue, can you please create a separate issue for that?

**Comment by soufianebenali** [comment]
oh thanks @carrodher I created a [new issue for mariadb](https://github.com/bitnami/charts/issues/5314).

**Comment by soufianebenali** [comment]
Hi @tulid,
Can you please check [the issue I opened](https://github.com/bitnami/charts/issues/5314), basically I had to delete the pvc and install again my db.

Thanks

**Comment by tulid** [comment]
pls, what's meaning of "As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001."
i think the mysql chart deployed failed, may be caused by the permissions as below.
can you take a few minutes to tell me what‘s meaning of it. 
tks

**Comment by carrodher** [comment]
[Here](https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/#root-and-non-root-containers) you can find a tutorial explaining some good practices for hardening containers, one of the most important ones is related to root VS non-root containers, I hope that this section is useful to understand the use of these images as well as their relationship with the user 1001

**Comment by tulid** [comment]
Hi author, today i test use distributed storage -- longhorn, then the mysql deployed succeess. pls tell me, whether the ha mysql only can use distributed storage. before, the storage system i used is NFS.
pls, help me to confirm it.  tks a lo.

**Comment by carrodher** [comment]
The Bitnami MySQL image stores the MySQL data and configurations at the `/bitnami/mysql` path of the container.

The chart mounts a Persistent Volume (PV) volume at this location. The volume is created using dynamic volume provisioning by default. An existing PersistentVolumeClaim (PVC) can also be defined for this purpose. Apart from that, other methods can be used, the main requisite is that the permissions are properly configured, see https://docs.bitnami.com/kubernetes/infrastructure/mysql/configuration/chart-persistence/

**Comment by utkuozdemir** [comment]
I am facing the same issue on chart version `8.4.4` app version `8.0.23`.

**Comment by carrodher** [comment]
Are you facing the issue in a fresh installation or during an upgrade? Not only during an upgrade but also if you re-installed the chart with the same name. `helm delete` doesn't remove the PVCs where the password is stored, you need to manually remove it with `kubectl delete pvc`.

Please take a look at the solutions provided in the guide below and let us know if they're helping to solve your problem:

https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

**Comment by utkuozdemir** [comment]
I think it was a false alarm - I'm not sure but probably I didn't pass `volumePermissions.enabled=true` as I claimed to. I have uninstalled the release, removed the PVC and reinstalled, making sure that `volumePermissions.enabled=true`, and it seems to be working ok this time. I'll report it again if I can reproduce it. Sorry for taking your time.

**Comment by carrodher** [comment]
I'm glad you were able to fix the issue by customizing the probes
