### ISSUE TITLE
Redis bitnami audit logging

### ISSUE THREAD

**Issue by 8297530225** [bitnami/charts#5266]
HI Team,

Wanted to know if open source bitnami  is providing audit logging or not. 
Please let me know if these  auditable events shall be configured to record the following information
- Timestamp  
- User ID (when applicable the id of the end user, for example, SIGNUM)
- System ID (ID of the system that generated the log record)
- Client IP (IP address of the end user terminal)
- For data processing events only: Document/object identifier (filename, URL, document number or other applicable ID).
- Destination IP address and port
- Accounting details of the changes that are made to perimeter security devices should also be recorded and managed centrally, e.g., nature of exact rule change made on the fi+G57rewall

**Comment by andresbono** [comment]
Hi @8297530225, I'm afraid that audit logging is a feature of Redis Enterprise, a commercial solution that we are not distributing.

Let us know if you have any other questions.
