### ISSUE TITLE
[bitnami/mongodb] How to configure Ingress with mongodb replicaset in order to have external access without using LoadBalancer or NodePort ?

### ISSUE THREAD

**Issue by percenuage** [bitnami/charts#5307]
**Which chart**:
bitnami/mongodb@10.5.1

**Is your feature request related to a problem? Please describe.**
In my production cluster on GKE, my nodes are private (no external IP) except Ingress IP. I'm trying to configure **Mongodb** **Replicaset** mode with external access. Neither `LoadBalancer` nor `NodePort` are suit for me (maybe I'm not using it well).

`NodePort` will not work on private node and `LoadBalancer` will create new public IPs and I have to configure domains for every client I have in production.

In `standalone` mode, everything works perfectly. I just added a new ingress entry mapped to the mongodb service with tls certificate. Sadly, Ingress do not support TCP and UDP services (https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/). I just added a TCP configmap with port forward.

In `statefulset` mode, everything works perfectly when I request the headless service within the cluster (ex. `mongo "mongodb://root:admin@hyper-db-headless/admin?replicaSet=rs0"`).

**Describe the solution you'd like**
So in my dream, I would like to have an ingress option in chart values for **Mongodb RS** and provide my domain/fqdn (ex. `mongo.yolo.org`) to access externally to the RS with this command: `mongo "mongodb+srv://root:admin@mongo.yolo.org/admin?replicaSet=rs0"`.

**Describe alternatives you've considered**
Maybe using Mongodb srv uri is difficult/impossible with ingress, I could use domains for each mongo statefulset pod like  `mongo "mongod://root:admin@mongo0.yolo.org,mongo1.yolo.org/admin?replicaSet=rs0"`. And in my own DNS provider, add SRV entry to fit my dream^^.

**Additional context**
- GKE cluster with private node on production
- Distributed architecture with more than 10 microservices which should connect to single Mongodb Replicaset instance (database are split for each MS)
- 1 namespace by client with same architecture for each (so for 4 clients, I have 4 independents Mongodb Replicaset instances)
- For each client / namespace, I need one domain with access to mongodb instance like `mongo.<client>.yolo.org`
- OVH is our DNS provider
- Ingress are configured with one GKE public IPs (chart version **ingress-nginx-3.13.0** / app version **0.41.2**)
- SSL certificate are provided by cert-manager with Ingress

**Comment by migruiz4** [comment]
Hi @percenuage,

Thank you for the detailed description of your use case, I'm looking for a solution that fulfills your requirements.
I will get back to you as soon as possible.

Sorry for the incovenience.

**Comment by javsalgar** [comment]
Hi,

Just as you mentioned, currently Ingress would not support the MongoDB traffic. I know that there are some guides to configure HAProxy as a load balancer for MongoDB https://www.programmersought.com/article/92561851648/. With that, I'm not entirely sure if you could configure ingress to access HAProxy and then HAProxy forward to MongoDB. I imagine this could add some extra overhead and, as it is not officially supported, we do not have plans to add it to the chart.

It could be great if, at the GKE level, it could be possible to define a static IP that could be binded to a Kubernetes service. This way you could use the `service.loadBalancerIP` value to an expected static IP so you don't have to change the DNS entry. 

Hope these thoughts help
