### ISSUE TITLE
[bitnami/kafka] Unable to set extraEnvVars of KAFKA_CFG_ZOOKEEPER_clientCnxnSocket = "org.apache.zookeeper.ClientCnxnSocketNetty" in Kafka helm chart"

### ISSUE THREAD

**Issue by yash-gupta-comprinno** [bitnami/charts#5325]
**Which chart**:
Kafka helm chart Application version 2.7.0 , chart version 12.7.3

**Describe the bug**
i am not able to set extraEnvvars parameters specifically for KAFKA_CFG_ZOOKEEPER_clientCnxnSocket , its showing null value whenever i check the kafka-0 logs.

**To Reproduce**

`helm install kafka --set-string extraEnvVars[0].name=KAFKA_CFG_zookeeper_clientCnxnSocket,extraEnvVars[0].value="org.apache.zookeeper.ClientCnxnSocketNetty" bitnami/kafka`

`kubectl logs kafka-0 | grep zookeeper.clientCnxnSocket`  then check for parameter zookeeper.clientCnxnSocket it shows null value always.

**Expected behavior**
The null value shoud have been replaced with "org.apache.zookeeper.ClientCnxnSocketNetty"

**Version of Helm and Kubernetes**:
Helm version 3.4.2 and kubernetes cluster is EKS v1.18.9-eks-d1db3c

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
Find below screenshot
![Screenshot from 2021-01-28 21-13-48](https://user-images.githubusercontent.com/74037110/106162171-d4103300-61ad-11eb-8a12-e01b777f02a7.png)

**Comment by rafariossaa** [comment]
Hi,
  Have you tried with the name of the environment variable in uppercase ? 
  Reference: https://github.com/bitnami/bitnami-docker-kafka#user-content-configuration

**Comment by yash-gupta-comprinno** [comment]
Hi,
Yes I have tried with uppercase also.

**Comment by rafariossaa** [comment]
Hi,
  I have found the issue. Kafka container is always converting to lower case the setting name.
  I will fix it and make a new release of the container.
  I will come back as soon as it is released.

**Comment by yash-gupta-comprinno** [comment]
> Hi,
> I have found the issue. Kafka container is always converting to lower case the setting name.
> I will fix it and make a new release of the container.
> I will come back as soon as it is released.

Thanks @rafariossaa!

**Comment by rafariossaa** [comment]
Hi @yash-gupta-comprinno ,
  We had made a new release fixing this. Could you try it ? It is 2.7.0-debian-10-r42.

**Comment by yash-gupta-comprinno** [comment]
Thanks @rafariossaa! It's working now.

**Comment by rafariossaa** [comment]
Hi,
  I am glad this worked for you.
  Thanks.
