### ISSUE TITLE
Non latin-7 character in values.yaml

### ISSUE THREAD

**Issue by bagnaram** [bitnami/charts#5326]
https://github.com/bitnami/charts/blob/40ba37da944ce809a8cb3cb736ef3787a6a84db6/bitnami/kube-prometheus/values.yaml#L1106

The apostrophe is causing parse issues due to encoding in certain applications. Suggest changing `’` character  to `'`

**Comment by miguelaeh** [comment]
Hi @bagnaram ,
Please feel free to Open a PR changing it
