### ISSUE TITLE
Nginx values.yaml security context swapped between pod and container

### ISSUE THREAD

**Issue by Hardvor7** [bitnami/charts#5327]
**NGINX Chart**:

In values.yaml **podSecurityContext** and **containerSecurityContext** are swapped

Under **podSecurityContext** the differents parameters (`runAsUser`, `runAsNonRoot`, ...) are for a **containerSecurityContext**
Under **containerSecurityContext** the parameter `fsGroup` is for a **podSecurityContext**

**Comment by dani8art** [comment]
Hi @Hardvor7, you are completely right, thank you so much for the feedback.

Would you like to contribute to this fix? we will be happy to handle your PR if you wanted to do it.

**Comment by Hardvor7** [comment]
It's done, I hope it's good ! :)
