### ISSUE TITLE
wordpress chart - embed uploads in a custom image

### ISSUE THREAD

**Issue by florinceleapca** [bitnami/charts#5330]
Hello,
I am using bitnami/wordpress chart
I am looking for a way to use a custom image wich embed a specific wp app state (plugins + themes + uploads) ... I know that for themes and plugins can be use a script to do that ... but want to embed it all :)

I tried this: 
- starting from https://github.com/bitnami/bitnami-docker-wordpress.git
- using docker-compose I installed locally wp using volumes
- all the generated wp content I copied it to rootfs folder then build and tag my custom image, then docker push to my repo
- updated values.yaml to use my custom image
After helm install and wait for wordpress pod to be ready ... the pod does not contain the uploads files

Thanks for your time

**Comment by ZeldOcarina** [comment]
Hey @florinceleapca did you ever figure this out in the following years?

**Comment by florinceleapca** [comment]
Hey @ZeldOcarina, probably yes, but honestly, I don't remember
