### ISSUE TITLE
Elasticsearch - Support metrics without a coordinating-only node

### ISSUE THREAD

**Issue by Pikabanga** [bitnami/charts#5337]
**Which chart**:
[elasticsearch-14.0.0](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch)

**Is your feature request related to a problem? Please describe.**

When you deploy a cluster with no coordinating-only nodes (`coordinating.replicas: 0`), the metrics pod fails to start because it's hard coded to query the coordinating-only nodes. It would be nice to be able to have metrics without coordinating-only nodes.

Here is the log output from the metrics pod:

```
level=warn ts=2021-01-29T13:05:45.363072036Z caller=cluster_health.go:270 msg="failed to fetch and decode cluster health" err="failed to get cluster health from http://some-elasticsearch-coordinating-only:9200/_cluster/health: Get http://some-elasticsearch-coordinating-only:9200/_cluster/health: dial tcp 10.233.32.219:9200: connect: connection refused"
```

**Describe the solution you'd like**
An option on the metrics config to point at another node/url. Here's the code in question that would need to become configurable: https://github.com/bitnami/charts/blob/038862f1d35e826784031b77caa88dd3e16f22cf/bitnami/elasticsearch/templates/metrics-deploy.yaml#L37

**Describe alternatives you've considered**
Right now we are deploying a coordinating-only node so we can have metrics, but for the size of the cluster the coordinating-only nodes really just adds extra overhead.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback. I'll open a task for investigating the issue. I cannot guarantee an ETA as it is not a critical feature, but we will update the ticket as soon as we have more news.

**Comment by javsalgar** [comment]
Hi,

I created this PR to solve the issue https://github.com/bitnami/charts/pull/5364

**Comment by Pikabanga** [comment]
That was fast, thank you very much!
