### ISSUE TITLE
Redis Maintenance Activities

### ISSUE THREAD

**Issue by 8297530225** [bitnami/charts#5352]
Hi team, 

Wanted to know what maintenance activities needs to be done for Redis in production. Please revert.

**Comment by carrodher** [comment]
Hi, you can find all the parameters and configuration options supported by the Bitnami Helm Chart in the [README.md file](https://github.com/bitnami/charts/blob/master/bitnami/redis/README.md). For questions related to the application itself, I recommend you to visit the Redis community forum at https://redis.io/community
