### ISSUE TITLE
bitnami/rabbitmq Chrome cannot connect to two UI interfaces that create RabbitMQ clusters simultaneously,Why

### ISSUE THREAD

**Issue by Gefuxing** [bitnami/charts#5355]
chart 8.5.4

helm3 install gemq1 --namespace=dev-prod --set replicaCount=3  --set persistence.storageClass=iscsi  --set service.type=NodePort  --set auth.username=test1 --set auth.password=test1 --set resources.limits."cpu"=1.0 --set resources.limits."memory"=2048Mi --set resources.requests."cpu"=1.0 --set resources.requests."memory"=2048Mi --set persistence.size=2Gi --set podLabels."app"=mq83 --set service.labels."app"=mq83  bitnami/rabbitmq --version 8.5.4

helm3 install gemq2 --namespace=dev-prod --set replicaCount=3  --set persistence.storageClass=iscsi  --set service.type=NodePort  --set auth.username=test2 --set auth.password=test2 --set resources.limits."cpu"=1.0 --set resources.limits."memory"=2048Mi --set resources.requests."cpu"=1.0 --set resources.requests."memory"=2048Mi --set persistence.size=2Gi --set podLabels."app"=mq83 --set service.labels."app"=mq83  bitnami/rabbitmq --version 8.5.4

Execute the above two helm3 commands to get the SVC port and connect with Chrome

Why do you deploy two RabbitMQ clusters and only connect one at a time to the UI interface connecting to RabbitMQ clusters? Chrome can't connect to two clusters at the same time.
What if you connect two clusters with two browsers, one for Chrome and one for Edge,it is ok,can connecting ,Why
![image](https://user-images.githubusercontent.com/43690953/106411670-c514d380-6480-11eb-8fe7-b929b77a130d.png)

![image](https://user-images.githubusercontent.com/43690953/106411708-d8c03a00-6480-11eb-93a6-abb8fc5e0bc6.png)

The above two cluster connections are using Chrome, error?

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

**Comment by Mauraza** [comment]
Hi @Gefuxin

You have two clusters, but it seems that the extension of chrome are you using doesn't allow it. You can add a support case in that plugin for that since Rabittmq is working properly, isn't it?
 

Regards,
Ibone.

**Comment by Gefuxing** [comment]
Hello, it seems not, because I downloaded 3 browsers and connected to the cluster I created, but none of them could connect to more than two clusters at the same time. This may have been set when the cluster was created, have you tried it?
Want an answer?Thank you very much!

**Comment by Mauraza** [comment]
Hi @Gefuxing, 

I'm tested and you a right
![image](https://user-images.githubusercontent.com/17168510/106583090-fbb42200-6544-11eb-865f-9f88c1b8b4a0.png)
It seems there an error with the sessions, but the clusters rabittmq is working properly. 
You can ask in the rabbitmq community 
https://www.rabbitmq.com/contact.html#community-resources

Regards,
Ibone.

**Comment by Gefuxing** [comment]
thanks ,
Encountered a problem, again today when I create a three-node rabbitmq cluster, in K8S can see three pod, but when I connect the rabbitmq UI management, I see only a pod, what this and set about, sometimes you can see three pod, sometimes only one pod, the probability of a pod 1/2, but can you tell me how to solve?

Expect results:
![image](https://user-images.githubusercontent.com/43690953/106908234-169bb780-673a-11eb-9cab-80dede7f4d85.png)

Error reporting interface:
![image](https://user-images.githubusercontent.com/43690953/106908652-72664080-673a-11eb-8aeb-b168ca532fdc.png)


helm3 install gemq1 --namespace=dev-prod --set replicaCount=3 --set persistence.storageClass=iscsi --set service.type=NodePort --set auth.username=test1 --set auth.password=test1 --set resources.limits."cpu"=1.0 --set resources.limits."memory"=2048Mi --set resources.requests."cpu"=1.0 --set resources.requests."memory"=2048Mi --set persistence.size=2Gi --set podLabels."app"=mq83 --set service.labels."app"=mq83 bitnami/rabbitmq --version 8.5.4


version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

What should I do, please?

**Comment by Gefuxing** [comment]
![image](https://user-images.githubusercontent.com/43690953/106980928-0caaa080-679c-11eb-810f-c1050828e42b.png)
**It's here again today**

**Comment by Mauraza** [comment]
Hi @Gefuxing,

Could you add more information, such as the logs of the pods? and anything you think could be relevant.

Regards,
Ibone.

**Comment by Gefuxing** [comment]
![image](https://user-images.githubusercontent.com/43690953/107137645-7f0cb380-6949-11eb-91f0-2ac094254d18.png)
Is there any difference in how these two volumes are mounted? Thank you very much!

**Comment by Mauraza** [comment]
Hi @Gefuxing,

the two volumes are the same, both have the same size and the same `storageClass`  you can check it running the following command:

`kubectl get pvc -n dev-dev`

I hope that helps you.
