### ISSUE TITLE
Elasticsearch authentication via search-guard or SSL

### ISSUE THREAD

**Issue by jilleJr** [bitnami/charts#5358]
**Which chart**:
elasticsearch   14.0.0

**Is your feature request related to a problem? Please describe.**
One of our services has a security hole where a user can specify an URL and the service will send a GET request to that endpoint. The result can then be shown by the user. We're also storing information in our Elasticsearch cluster that should not be accessible by all users due to different security zones. While we're trying to fix the security hole, we still can not allow any traffic (even only internal) to access the data if they're not providing authentication.

We're confused of how bad adding the plugin [Search Guard](https://search-guard.com/) would impact the deployment. There are all the different services, including the `elasticsearch-exporter`; we're confused of how to properly have all traffic authenticated throughout the stack?

**Describe the solution you'd like**
Basic username+password authentication to Elasticsearch, or setting up SSL.

Do you have any tips on setting up [Search Guard](https://search-guard.com/) or SSL with the bitnami elasticsearch helm chart?

We need authentication, such as via search-guard, setup to the elasticsearch instance, and deployed via the `bitnami/elasticsearch` Helm chart. Is this possible?

**Describe alternatives you've considered**
Jumping over to Elasticsearch's official helm chart (https://github.com/elastic/helm-charts/tree/master/elasticsearch) as they seem to support a more granular configuration to allow adding in search-guard at every level.

**Additional context**
We come from using KubeDB previously to setup Elasticsearch in our Kubernetes clusters. KubeDB does by default ship with the Search-guard plugin installed and correctly configured, and we haven't thought about it previously and just assumed that Elasticsearch had basic authentication as a feature.

**Comment by Pikabanga** [comment]
Hi,

Just to clarify, the official ES helm charts don't support search-guard out of the box but rather elasticsearch's built-in support for basic auth. See https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/security

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the SSL and authentication features require using the commercial plugin x-pack, which we do not include by default. We do not have experience with this third party solution Search Guard. If this enables basic authentication, we would need to configure in the metrics exporter the ability to add a username and password. That's something we can work on. If you want to speed up the process, feel free to create a PR adding username and password support in the `metrics` section and we will review it.

**Comment by jilleJr** [comment]
> @javsalgar
> I'm afraid that the SSL and authentication features require using the commercial plugin x-pack

Seems like that they've added back security to free license, at least for their "BASIC - FREE AND OPEN" license.
Blog post: https://www.elastic.co/blog/security-for-elasticsearch-is-now-free

What's your stand on the "FREE AND OPEN" vs the "BASIC - FREE AND OPEN" tiers? Do you only want to support the FREE AND OPEN, or allow what assumably seems to be x-pack for free but via the "BASIC - FREE AND OPEN" tier?

**Comment by javsalgar** [comment]
Hi,

From what I see, the Basic tier uses the Elastic license. This is something we are currently evaluating as we may not be able to freely redistribute it. As soon as there is a decision on this, we will let you know.

**Comment by drorventura** [comment]
Hi, 
any updates regarding this?
will x-pack be supported?

**Comment by javsalgar** [comment]
Hi,

We checked and I'm afraid we cannot distribute x-pack. In the current scenario, that's something we cannot support.

**Comment by javsalgar** [comment]
Hi,

Just another update on this. From our internal team we ended up having green light on redistributing x-pack. That means that a major version of our chart will include x-pack support.

**Comment by omardoma** [comment]
Now that x-pack is supported, is there any example on how to use it in the chart? I am struggling to find any references.

**Comment by javsalgar** [comment]
Hi,

Right now we are working on making some x-pack features available using environment variables. When this is done, @migruiz4 will add more information in the chart readme.

**Comment by lpmatos** [comment]
Hi @javsalgar @migruiz4!

Any news about this? I'm in a scenario similar to @omardoma

**Comment by migruiz4** [comment]
Hi @lpmatos,

We continue working on it and expect to release a new version of the Elasticsearch chart and Docker image during the next week.

We will keep you updated!
