### ISSUE TITLE
Kafka chart sometimes fails on first deployment

### ISSUE THREAD

**Issue by heyts** [bitnami/charts#5366]
**Which chart**:
kafka

**Describe the bug**
When the helm chart is installed, it also install the zookeeper chart. Sometimes, Kafka is created before Zookeeper is available, resulting in Kafka not being able to start

**To Reproduce**
`helm install bitnami/kafka`

**Expected behavior**
- Kafka is started and available

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2020-09-14T08:18:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
This has been tested with a kind cluster and **most of the time** Kafka is failing to start on first attempt, but succeeds on the next. Rarely, it does succeeds on first try.

It seem that a simple readiness check to ensure zookeeper is available would fix this issue

**Comment by Mauraza** [comment]
Hi @heyts,

I tried and you are right Kafka starts with an error, but if you wait the pod will be started. 

```
$ kubectl get po -w
NAME                READY   STATUS              RESTARTS   AGE
kafka-0             0/1     ContainerCreating   0          8s
kafka-zookeeper-0   0/1     ContainerCreating   0          8s
kafka-0             0/1     Running             0          21s
kafka-0             0/1     Error               0          32s
kafka-0             0/1     Running             1          33s
kafka-zookeeper-0   0/1     Running             0          37s
kafka-0             0/1     Error               1          43s
kafka-zookeeper-0   1/1     Running             0          47s
kafka-0             0/1     CrashLoopBackOff    1          47s
kafka-zookeeper-0   1/1     Running             0          55s
kafka-0             0/1     Running             2          63s
kafka-0             0/1     Running             2          66s
kafka-zookeeper-0   1/1     Running             0          66s
kafka-0             1/1     Running             2          68s
```
Let's check the `describe` of the pod of Kafka

```
$ kubectl describe pod kafka-0
....
vents:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  3m35s                  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         3m35s                  default-scheduler  Successfully assigned default/kafka-0 to minikube
  Normal   Pulling           3m34s                  kubelet            Pulling image "docker.io/bitnami/kafka:2.7.0-debian-10-r35"
  Normal   Pulled            3m15s                  kubelet            Successfully pulled image "docker.io/bitnami/kafka:2.7.0-debian-10-r35" in 19.000353361s
  Warning  Unhealthy         2m57s (x2 over 3m7s)   kubelet            Readiness probe failed: dial tcp 172.17.0.3:9092: connect: connection refused
  Warning  BackOff           2m48s (x2 over 2m52s)  kubelet            Back-off restarting failed container
  Normal   Created           2m33s (x3 over 3m15s)  kubelet            Created container kafka
  Normal   Started           2m33s (x3 over 3m15s)  kubelet            Started container kafka
  Normal   Pulled            2m33s (x2 over 3m3s)   kubelet            Container image "docker.io/bitnami/kafka:2.7.0-debian-10-r35" already present on machine
```
The pod restart because the "Readiness probe failed: dial tcp 172.17.0.3:9092: connect: connection refused", 

So Kafka has a readiness but it fails.

is this what you meant by readiness or something else?

Regards,
Ibone.

**Comment by heyts** [comment]
Hi @Mauraza, yes that's what I meant by readiness and I observe the same thing, Kafka fails to start but eventually restarts and the pod runs fine on 2nd try. Maybe just extending the readiness probe `initialDelaySeconds` would be sufficient to solve this. Currently the readiness probe is set to this by default:
```yaml
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  failureThreshold: 6
  timeoutSeconds: 5
```

**Comment by Mauraza** [comment]
Hi @heyts,

I don't think that increase `initialDelaySeconds` solves the problem. 

> Looking a bit more into it, I think what happen may be that in some cases, Zookeeper isn't ready when Kafka queries it, which makes Kafka readiness probe fail and the pod restart.

I agree with that.

**Comment by Deepanshu6dec** [comment]
Have we find this solution on this issue, I also faced same issue Kafka chart fails on first deployment after restart it start working

**Comment by Umashankar-Philips** [comment]
I am facing this issue, Kafka is failing initially

**Comment by Umashankar-Philips** [comment]
@javsalgar any comments on that ?

**Comment by fevisera** [comment]
Hi @Umashankar-Philips @Deepanshu6dec,

I tried to reproduce the issue but I could not:
```
$ helm install kafka bitnami/kafka
$ kubectl get pod -w
NAME      READY   STATUS              RESTARTS   AGE
kafka-0   0/1     ContainerCreating   0          28s
kafka-0   0/1     Running             0          40s
kafka-0   1/1     Running             0          53s
```

If you encounter any problems with bitnami/kafka deployment, please report them separately with more detailed information. This issue was reported a while ago, and since then, kafka has undergone various changes. Therefore, if the problem persists, it may be due to a different underlying cause that needs to be investigated.

Thank you.
