### ISSUE TITLE
Moodle Upgrade in Kubernetes Helm Chart Version

### ISSUE THREAD

**Issue by GeraldST** [bitnami/charts#5367]
**Chart**:
Moodle, version 11.0.0

**Problem**
I don't know if this is a bug or feature request, but my problem is that I don't know how to REALLY upgrade Moodle in the Bitnami Helm Chart that I am running on Azure. I have spent some time on the web trying to find information but I think all those instructions don't work in real life for this Kubernetes Chart versions.

What I have learned by now: It does not help simply taking an new helm chart version with the newest Docker image because this WILL NOT affect my already installed and therefore persisted version of the installation files in the /bitnami/moodle directory. Although there is a new version of Moodle delivered within the newer image I simply cannot use it because it is deleted at the time firing up the pod and is always replaced by those already existing files of my persistant volume claim.  So basically the Moodle version is never changed after first time install. Hmh, I see the necessity - this enables having custom plugins installed, but a huge bit of a drawback for upgrading Moodle.

For the docker container the [README](https://github.com/bitnami/bitnami-docker-moodle) says :
_Since Moodle(TM) 3.4.0-r1, the application upgrades should be done manually inside the docker container following the official documentation. As an alternative, you can try upgrading using an updated Docker image. However, any data from the Moodle(TM) container will be lost and you will have to reinstall all the plugins and themes you manually added._

So I tried upgrading the Moodle version in the docker container inside the pod of the the helm chart and following the [upgrade instructions here](https://docs.bitnami.com/azure/apps/moodle/administration/upgrade):
But those instructions are not working for me because:

- There is neither a WGET in the container (okay replaced it by CURL) nor SUDO command available (okay not needed because I am root)
- Most of all you cannot simply MV the moodle installation directory because it is mounted from the PVC
- And if you still try to move its content away and replace it by the new Moodle version, in the meantime Kubernetes will detect that the app is not working and restarts the pod resulting in a "crashloopbackoff" situation, because the installation got corrupt during updating.
- Apache cannot be stopped out of the same reason - Kubernetes will instantly restart the pod.

So how on earth am I supposed to "manually upgrade the Moodle application inside the Kubernetes Pod / Docker Container"?

The only way I see at the moment is a VERY inconvenient one: Run a fresh and clean Moodle installation with the newest helm chart and Moodle image and then migrate all the existing data into it. But this is no feasIble way of supporting a production app that needs to get updated serveral times a year with zero downtime.

I hoped by running Moodle in Kubernetes the upgrade process will become easier by simply replacing the image and deploying a new helm chart but on the contrary this seems to be quite a nightmare.

Could somebody PLEASE shed a light on how Moodle is supposed to be upgraded in a chart version and point me to instructions that work?

Thank you very much for your help.
Gerald

**Comment by migruiz4** [comment]
Hi @GeraldST,

To prevent the pod from getting into 'crashloopbackoff' status while performing the upgrade, you will have to disable the livenessProbe.

It can be done by executing `helm upgrade` with the option `--set livenessProbe.enabled=false`.

Once the liveness probe is disabled, you can upgrade Moodle following the [official documentation](https://docs.moodle.org/37/en/Upgrading). 

The upgrade steps would be similar to these:
```sh
#Open a bash inside your pod
kubectl exec -it my_moodle_pod -- bash

#Create a backup of your current installation (moving the content and not the folder)
mkdir /opt/bitnami/moodle.backup
mv /opt/bitnami/moodle/* /opt/bitnami/moodle.backup

#Download and uncompress Moodle
curl -o /opt/moodle.tgz https://download.moodle.org/download.php/direct/stableX.Y/moodle-latest-X.Y.tgz
cd /opt
tar -xzf moodle.tgz

#Move Moodle to /opt/bitnami/moodle and copy your configuration and custom files
mv /opt/moodle/* /opt/bitnami/moodle/
cp /opt/bitnami/moodle.backup/config.php /opt/bitnami/moodle
cp -pr /opt/bitnami/moodle.backup/theme/mytheme /opt/bitnami/moodle/theme/mytheme
cp -pr /opt/bitnami/moodle.backup/mod/mymod /opt/bitnami/moodle/mod/mymod
```

Once the upgrade is completed, your pod should show as Ready again.
If you'd like to, you can reenable the liveness probe again using helm upgrade` with the option `--set livenessProbe.enabled=true`.

I hope this helps.

**Comment by GeraldST** [comment]
Hi @migruiz4,

excellent answer, thank you very much! I finally made it with your help :-)
I do think this should become part of the documentation for the helm chart.

I figured out most of the modifications already on my own but the missing part was disabling the LivenessProbe.
Just for reference these are my steps - I changed directories a bit ("tmp" for downloading the files and "moodledata" for backup just in case to have it on the persistent storage) and recreated permissions because I am running the chart as a root-container (I need the Moodle cron jobs).

```
curl http://download.moodle.org/download.php/direct/stable310/moodle-latest-310.tgz -o /tmp/moodle.tgz

mkdir /bitnami/moodledata/moodle.backup
mv /bitnami/moodle/* /bitnami/moodledata/moodle.backup

tar -xzf /tmp/moodle.tgz -C /bitnami/moodle --strip 1

cp -a /bitnami/moodledata/moodle.backup/config.php /bitnami/moodle/
cp -a /bitnami/moodledata/moodle.backup/theme/MY_THEME /bitnami/moodle/theme/
cp -a /bitnami/moodle.backup/mod/MY_MOD /bitnami/moodle/mod/

#set file permissions because I am running a root-container
chown -R daemon:root /bitnami/moodle
chown -R daemon:root /bitnami/moodledata

rm -r /bitnami/moodledata/moodle.backup
```

**Comment by migruiz4** [comment]
I'm happy to help!

I'm going to close the issue now as it seems to be resolved, if you have any further questions don't hesitate to let us know.

Also, I'd like to mention that the upgrading process is currently a known issue and we have plans to change it at some point in the future.

**Comment by ernani** [comment]
I get that this might work since /bitnami is suppposed to be a PVC or NFS volume. So all running pods would map the PHP files to that storage area.

Instead of that, if using a custom image where moodle PHP codebase is not within /bitnami/moodle or if you just mount the /bitnami/moodledata as the NFS mount, when actually running a new container image, I am almost sure it would understand itself that there is a new version running and it would execute the necessary steps to upgrade the db tables within the schema.

I do believe that using it this way you can build a CI/CD pipeline where whenever a new image changes, it will build a new image, with themes and such, and run them within this new image tag/version, so it will do a rolling upgrade on running pods and voila. Nothing changes in moodledata since it is a NFS share, your images have the new version or theme or new plugins, etc.

And then if there is a new version coming by, moodle is "smart enought" to detect it is an upgrade and will make the db changes itself.

I will need to run some tests to report back.

Cheers!

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ewithak** [comment]
Something to note in case anyone has to maintain a moodle instance running in Kubernetes: I used the above instructions from @migruiz4 and @GeraldST to successfully update the container and THEN I updated the moodle helm chart to deploy an image based on the same version.

ie: Manually updated to version 4.2.2, then updated to helm chart version 17.1.0 which uses the image docker.io/bitnami/moodle:4.2.2-debian-11-r5.

During my testing I found that upgrading the helm chart first would trigger a database upgrade script on startup that exited prematurely, causing the CrashLoopBackoff. If the pod is updated first then the helm chart is updated and the versions match, the script is skipped, and the pod starts as expected.

Not ideal, but now security updates on both moodle and the container image are complete and I can move on to other things.

**Comment by fcecagno** [comment]
Hey, for the benefit of others, I'm testing upgrade Moodle using a initContainer run by the helm chart:
```
initContainers:
  - name: update-version
    image: alpine:3.16
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - |
      set -xe
      apk --update add curl
      if [ ! -f /bitnami/moodle/.installed_version_md5 ] || [ "$(cat /bitnami/moodle/.installed_version_md5)" != "${MOODLE_DOWNLOAD_MD5}" ]; then
        curl -s ${MOODLE_DOWNLOAD_URL} -o /tmp/moodle.tgz
        CALCULATED_CHECKSUM=$(md5sum /tmp/moodle.tgz | cut -d' ' -f1)
        if [ ${CALCULATED_CHECKSUM} != "${MOODLE_DOWNLOAD_MD5}" ]; then
          echo "Invalid checksum: ${CALCULATED_CHECKSUM}"
          exit 1
        fi

        # https://github.com/bitnami/charts/issues/5367#issuecomment-772888088
        BACKUP_DIR=/bitnami/moodledata/moodle-$(date "+%Y%m%d")
        if [ ! -d "${BACKUP_DIR}" ]; then
          echo "Copying moodle files to backup directory ${BACKUP_DIR}"
          cp -r /bitnami/moodle ${BACKUP_DIR}
        fi
        rm -r /bitnami/moodle/*
        tar -xzf /tmp/moodle.tgz -C /bitnami/moodle --strip 1

        # restore important files
        cp -a ${BACKUP_DIR}/config.php /bitnami/moodle/
        cp -a ${BACKUP_DIR}/theme/moove /bitnami/moodle/theme/
        # cp -a ${BACKUP_DIR}/mod/MY_MOD /bitnami/moodle/mod/

        # restore permissions
        chown daemon:root -LR /bitnami/moodle /bitnami/moodledata
        chmod -R g+rwX /bitnami/moodle /bitnami/moodledata
        chown root /bitnami/moodle/config.php
        chmod 640 /bitnami/moodle/config.php

        echo -n "${MOODLE_DOWNLOAD_MD5}" > /bitnami/moodle/.installed_version_md5
        echo "Finished installation!"
      else
        echo "Version match, do nothing..."
      fi
    env:
      # see https://download.moodle.org/releases/latest/
      - name: MOODLE_DOWNLOAD_URL
        value: https://packaging.moodle.org/stable403/moodle-4.3.3.tgz
      - name: MOODLE_DOWNLOAD_MD5
        value: dc9253f298789bef7b5b452813731923
    volumeMounts:
      - mountPath: /bitnami/moodle
        name: moodle-data
        subPath: moodle
      - mountPath: /bitnami/moodledata
        name: moodle-data
        subPath: moodledata
```
Worker like a charm, and keep a backup copy in moodledata. It was inspired by https://github.com/bitnami/charts/issues/5367#issuecomment-772888088.
In order to upgrade Moodle, you just update the envs and apply the chart again.
