### ISSUE TITLE
How can we use dagsConfigMap in helm bitnami airflow char

### ISSUE THREAD

**Issue by apalmercari** [bitnami/charts#5368]
There's no example for it

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback! Suppose you have a `my_dag.py` file. You could do the following.

```
kubectl create cm dags --from-file=my_dag.py
```

With that, you would have a configmap called dags in the cluster, and you can use that name in `dagsConfigMap`

```
helm install airflow bitnami/airflow --set dagsConfigMap=dags
```

**Comment by apalmercari** [comment]
Thank you :)
