### ISSUE TITLE
[bitnami/redis-cluster] How to enable logs and stored at specific location?

### ISSUE THREAD

**Issue by bharat15-ml** [bitnami/charts#5369]
**Which chart**:
redis-cluster-4.3.1

**Is your feature request related to a problem? Please describe.**
As per requirement of log analysis wanted to enable redis-cluster logs to specific location.

**Describe the solution you'd like**
Wanted to store logs at location- "/bitnami/redis/logs/redis.log"

**Describe alternatives you've considered**
 In the current helm chart redis-cluster-4.3.1, I have made the modification in configmap.yaml file at logfile: "/bitnami/redis/logs/redis.log"

 Also have created the extra Volume and volumeMount path - "/bitnami/redis/logs" by specifying in values.yaml.

**Additional context**
 Unable to file redis.log file at specified location, please let me know if there is any workaround for this to enable logs?

**Comment by juan131** [comment]
Hi @bharat15-ml 

By default, the Bitnami RabbitMQ image throughs logs to stdout/stderr. This is quite a common practice in container/kubernetes environment since containers are designed to be ephemeral. You can find more information in the link below:

- https://github.com/bitnami/bitnami-docker-rabbitmq#logging

We highly recommend avoid storing the logs in the container and, instead, run an appropriate logging stack in your Kubernetes cluster (e.g. EFK or ELK) that allows you to collect the container logs, aggregate them, and store them to analyze them later.

One of my colleagues wrote an article about this topic a year ago:

- https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/

**Comment by bharat15-ml** [comment]
Thanks Juan, for a quick thought!! Well understood this. 

One thing, just wanted to know. What will be the procedure to enable a redis cluster log and to store at this location- /bitnami/redis/logs/redis.log

Assume I have already created the log dir- /bitnami/redis/logs through extraVolume args. 

Thanks for your time!!

**Comment by juan131** [comment]
Hi @bharat15-ml 

If you take a look to the default configuration (the command below assumes the chart has been installed with release name `redis-cluster`):

```console
$ kubectl exec $(kubectl get pods -l app.kubernetes.io/instance=redis-cluster,app.kubernetes.io/name=redis-cluster -o jsonpath='{.items[0].metadata.name}') -- grep "log" /opt/bitnami/redis/etc/redis.conf
...
# Specify the log file name. Also the empty string can be used to force
# Redis to log on the standard output. Note that if you use standard
# output for logging but daemonize, logs will be sent to /dev/null
logfile ""
...
```

This configuration comes from the configmap that's mounted in the container, see:

- https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/configmap.yaml#L254

The chart doesn't provide, at this very moment, an easy way to do this change. As a workaround, you can manually edit the configmap (again, assuming the chart has been installed with release name `redis-cluster`):

```console
$ kubectl get configmap
NAME                    DATA   AGE
redis-cluster-default   1      15m
$ kubectl edit configmap redis-cluster-default
```

- Apply the changes below and save:

```diff
-logfile ""
+logfile /bitnami/redis/logs/redis.log
```

Then, delete the existing pods (one by one), so they're recreated using the new configuration. Wait around 30 seconds between pod deletions.

```console
$ kubectl delete pod redis-cluster-5
$ kubectl delete pod redis-cluster-4
$ kubectl delete pod redis-cluster-3
$ kubectl delete pod redis-cluster-2
$ kubectl delete pod redis-cluster-0
```

After that, the configuration changes should be applied and Redis should redirect the logs to the volume you attached.

**Comment by bharat15-ml** [comment]
Thanks Jaun!! So mostly for redis related configuration changes, I have  to look to the same configmap.
