### ISSUE TITLE
Allow setting of additional properties for kafka helm chart

### ISSUE THREAD

**Issue by zaf187** [bitnami/charts#5372]
**Which chart**:
bitnami/kafka master

**Is your feature request related to a problem? Please describe.**
I am trying to set the following kafka properties but cannot find equivalents to set in the values.yaml of the chart;
`replica.fetch.max.bytes`
`max.partition.fetch.bytes`

How can i set these if they're not available in the yaml?

**Describe the solution you'd like**
Provide 2 new properties in the values.yaml;
`replicaFetchMaxBytes`
`maxPartitionFetchBytes`
which map to the corresponding kafka properties;
`replica.fetch.max.bytes`
`max.partition.fetch.bytes`

**Describe alternatives you've considered**
Is it possible to pass in my own complete `kafka-server.properties` file in a mount or a configMap?

**Comment by zaf187** [comment]
I see there's also a way to pass them in using `extraEnvVars` does anyone know how to pass in multiple values?

**Comment by rafariossaa** [comment]
Hi,
  Could you take a look to [this]https://github.com/bitnami/charts/tree/master/bitnami/kafka#user-content-setting-custom-parameters) ? There you can find how to set other settings in kafka via `KAFKA_CFG_` environment variables.

**Comment by zaf187** [comment]
Yes thank you, that fits fine as a work around.

**Comment by yogeshg** [comment]
Looks like the link to user-content-setting-custom-parameters is broken, what's the current way for setting such parameters?

**Comment by yogeshg** [comment]
is it fair to assume that passing the following environment variables via `broker.extraEnvVars`
KAFKA_CFG_REPLICA_FETCH_MAX_BYTES will map to replica.fetch.max.bytes
KAFKA_CFG_MAX_PARTITION_FETCH_BYTES will map to max.partition.fetch.bytes?
