### ISSUE TITLE
Redis Chart

### ISSUE THREAD

**Issue by sebaszczen** [bitnami/charts#5376]
**Redis Chart**:
Redis Chart

**Describe the bug**
Pod keep pending.

kubectl get pods:
NAME                        READY   STATUS    RESTARTS   AGE
my-release-redis-client     1/1     Running   0          3h6m
my-release-redis-master-0   0/1     Pending   0          20s
my-release-redis-slave-0    0/1     Pending   0          20s

kubectl get pvc
NAME                                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
redis-data-my-release-redis-master-0   Pending                                      local-path     9s
redis-data-my-release-redis-slave-0    Pending                                      local-path     9s

`kubectl describe pvc redis-data-my-release-redis-slave-0
Name:          redis-data-my-release-redis-slave-0
Namespace:     default
StorageClass:  local-path
Status:        Pending
Volume:        
Labels:        app=redis
               component=slave
               heritage=Helm
               release=my-release
               role=slave
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
               volume.kubernetes.io/selected-node: sebastian-latitude-3410
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       my-release-redis-slave-0
Events:
  Type    Reason                Age               From                         Message
  ----    ------                ----              ----                         -------
  Normal  WaitForFirstConsumer  2m                persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  13s (x9 over 2m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator`

**To Reproduce**

1. helm install my-release bitnami/redis

**Expected behavior**
All pods running.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

Am i missing something? 

According to " waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator", should i modify chart somehow?

**Comment by Mauraza** [comment]
Hi @sebaszczen,

Could you check if the `storageClass`  "rancher.io/local-path exits? 
`kubectl get storageclass`
