### ISSUE TITLE
how-to-install-default-distribution-of-kibana-bitnami-chart-in-elk

### ISSUE THREAD

**Issue by KSumanth-LD** [bitnami/charts#5378]
Hi All,

When i tried to deploy the kibana chart.. by default is deploying in oss distribution mode. Unfortunately **oss** distribution doesn't support to save the logs.

I want to change my distribution to Default distribution so that I can have access most of the free options in kibana. Please let me know how to create a distribution..? (i tried with 7.1.2 version). please let me know which version i should use or what config changes should i make to fix the issue.

Thanks

**Comment by juan131** [comment]
Hi @KSumanth-LD 

The Kibana chart is based on the Bitnami Kibana Docker Image (see https://github.com/bitnami/bitnami-docker-kibana) which packages the OSS distribution of Kibana. This container is released under the Apache2 license and all the components included on it are open source.

To use a different distribution, you can substitute the Bitnami Kibana Docker Image with any image you want adapting the `image.*` parameters in the **values.yaml**, see:

- https://github.com/bitnami/charts/blob/master/bitnami/kibana/values.yaml#L14

**Comment by KSumanth-LD** [comment]
Hi @juan131 

Okay. But my problem is with the OSS distribution of kibana, I am not able to save logs in csv format. Is there any solution for this. I mean any alternate solution available.. to fix the issue.

**Comment by juan131** [comment]
Hi @KSumanth-LD 

It seems this feature is included in X-Pack, and this extension is not open-source. Therefore, it's an extension we cannot include in the image.

Answering your question: there's no way to export your logs data using the current Bitnami Kibana image as it's by default. You'll have to use an image including X-Pack or install the extension in the image. We support a way to install extensions during the deployment of Kibana, see:

- https://github.com/bitnami/charts/tree/master/bitnami/kibana#installing-plugins

> Note: you'll need a license to install X-Pack extension in Kibana.

**Comment by KSumanth-LD** [comment]
Hi @juan131 

Thanks for the information. I will use a docker image as per my need.
