### ISSUE TITLE
[Question] Rabbitmq amqps / tls

### ISSUE THREAD

**Issue by mscbpi** [bitnami/charts#5381]
This is not a bug or feature request.

I struggle to find information about the best/easiest way to manage certificate rotation for amqps connection, in case of rabbit deployed on k8s.

We need to expose rabbitmq publicly and would like client to connect through a tls connection, ideally with a valid server certificate. 

While http workload (incl. rabbit admin) is easily handled with cert-manager and ingress, when it comes to amqps behind a LB, is there a better way but update the secret manually every year with a new cert?

Also considering this valid certificate would not be that valid for internal connections (inside the cluster where rabbit runs), since it uses ClusterIP endpoint (rabbit.namespace.svc.cluster.local). Internal connections could still use amqp though.

How would you manage your tls certs for this use case?

Remark : it runs on azure aks where it seems impossible to have 2 LB services sharing the same External IP but different ports. Otherwise I guess  I could have ingress and rabbit on the same IP and have the same hostname for rabbit http admin and amqp, thus could reuse the cert generated for publishing the admin with ingress using certmanager...

Thanks for any feedback !

**Comment by andresbono** [comment]
Hi @mscbpi, thanks for your question. The key point is that http certs managed by cert-manager can be validated automatically. The question is... could you validate automatically the internal ones for amqp? How are you generating those ones right now?

**Comment by mscbpi** [comment]
We are setting things up, so we actually are wondering how to deal with that ! 

We can't validate neither the external or internal with cert-manager:
- external: can't validate against an AMQP endpoint, lets encrypt needs to connect with https on the server requesting the certificate, and no https is published with rabbitmq-server. So actually we don't know how to generate this cert automatically when it comes to AMQP.
- internal: well, it's internal. I don't think we can get any of `*.svc.cluster.local` certificate valid in any form. 
- Plus, I don't think we can differentiate internal or external, without having some kinds of proxy / delegation for external connections.
- Plus, it would be wrong that my pods inside the same cluster use the public FQDN / go out-and-in

So at the moment we think of having a valid certificate configured for external AMQPS, renew it manually yearly (painful), and use non-TLS amqp connection for internal-cluster communications with RMQ. 

However I would be very surprised in an all-automated world that I am not missing something that helps auto-rotation of certificates for a K8s-deployed RabbitMQ.

**Comment by mscbpi** [comment]
Ok I think I have to use cert-manager with dns challenge to automate creation/renewal of a certificate whose hostname is not targeting an ingress controller (since it targets amqp rabbit)

https://gist.github.com/marcopaga/1b6d045d85099cbf32456443a6e3cdf7

**Comment by mscbpi** [comment]
Ok I managed to deal with the question "how to use cert-manager with ACME and have automatic provisioning of certificate, when hostname does not resolve to an http endpoint" => using DNS01 challenge instead of HTTP01. So I have a valid Certificate object and results is stored in a secret. This question was more of a lack of knowledge on cert-manager.

It appears I would not have this problem if I could have the same public IP shared between Ingress LB and RabbitMQ LB, [which is not possible at the moment but will be on AKS with k8s 1.20.](https://github.com/Azure/AKS/issues/1621). Never mind this limitation, one may not want to share the same IP between both services anyway.


RabbitMQ related: 
- I assume the deployment of rabbitmq with this helm chart will refresh the certs when the secret is refreshed ?
- I don't think I can distinguish amqp connection coming from neighbor pods which will use amqp(s)://rabbitmq.namespace.svc.cluster.local as URL and external clients that will use amqps://rabbit.mycompany.com and have different certificates.
- So I guess I'd better use non-TLS connection for intra-cluster communication, which is ok.

**Comment by andresbono** [comment]
> * I assume the deployment of rabbitmq with this helm chart will refresh the certs when the secret is refreshed ?

Actually, the file might be auto updated within the container because of the way the certificate is mounted. However, the application itself might need to reload the certificate by restarting RabbitMQ.

> * I don't think I can distinguish amqp connection coming from neighbor pods which will use amqp(s)://rabbitmq.namespace.svc.cluster.local as URL and external clients that will use amqps://rabbit.mycompany.com and have different certificates.

I don't think so either. You would need to have a multi-domain certificate, but you are not going to be able to validate the internal domain `cluster.local`.

**Comment by mscbpi** [comment]
When using the operator, it renews automatically. Is it specific to operator deployment ?

>RabbitMQ can reload certificates produced by the same CA without a node restart. This makes on-the-fly certificate rotation (renewal) possible. To rotate the TLS certificate, update the TLS Secret object with the new certificate directly and this change will be picked up by the RabbitMQ pods within several minutes.

**Comment by andresbono** [comment]
Yes, that's specific to the operator. For example, in Helm, you can make use of checksum annotations: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments.

It's basically a calculation of the sha256sum of some helm template files. If any of them change, that will trigger an update of the statefulset. However, the calculation is done when you execute a helm install/upgrade action.

It's somehow similar to what you want, but probably not enough.

**Comment by mscbpi** [comment]
Thank you for your answer,

So it is 200% sure that the helm-deployed rabbit will not refresh its certificate when secret is updated ?

Thanks

**Comment by andresbono** [comment]
I assume it is not done that way, but I haven't tested it. Most servers need to be reloaded to be aware of new configuration options provided in configuration files. The same should happen if certificates change.

**Comment by mscbpi** [comment]
To be checked but this is the answer I got from rabbit-mq 
https://github.com/rabbitmq/rabbitmq-server/discussions/2788#discussioncomment-429675
> Rotating without restarting the server is a function from the rabbitmq-server, so not limited from using the cluster operator.

So we should be OK when renewing the certs also with a helm-deployed rabbitmq !
