### ISSUE TITLE
RabbitMQ pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by amin224** [bitnami/charts#5382]
The name (and version) of the affected chart

helm install my-release bitnami/rabbitmq

**description**

I cannot change PVC parameters present in statefulset configuration file, nor can I delete the volumeClaimTemplate and try to create my own PVC. I am trying to add a storageclass command to link my PVC with a PV that I created but it does not let me.

**Expected behavior**

I need to deploy 3 instances of a rabbitmq statefulset pods to my cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version --short`:

```
Client Version: v1.19.4
Server Version: v1.18.9-eks-d1
```

**Comment by miguelaeh** [comment]
Hi @amin224 ,
Did you tr to use the `persistence.existingClaim` parameter?

**Comment by amin224** [comment]
@miguelaeh Thank you so much I included the parameter persistence=existingClaim=(pvc name) when installing the helm chart and it let me use my own pvc that I created before.

I am trying to fix this error that I am receiving after the volumeMount has been taken care of

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  57s   default-scheduler  Successfully assigned default/my-release-rabbitmq-0 to ip.compute.internal
  Normal   Pulling    52s   kubelet            Pulling image "docker.io/bitnami/rabbitmq:3.8.11-debian-10-r0"
  Normal   Pulled     45s   kubelet            Successfully pulled image "docker.io/bitnami/rabbitmq:3.8.11-debian-10-r0"
  Normal   Created    44s   kubelet            Created container rabbitmq
  Normal   Started    44s   kubelet            Started container rabbitmq
  Warning  Unhealthy  8s    kubelet            Readiness probe failed: Error: unable to perform an operation on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: ['rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local']

rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local:
  * connected to epmd (port 4369) on my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-909-rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local'
 * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq
 * Erlang cookie hash: ST74ojJeJEdN==
```
Logs:
```
kubectl logs -f my-release-rabbitmq-0 
rabbitmq 12:48:44.15 
rabbitmq 12:48:44.15 Welcome to the Bitnami rabbitmq container
rabbitmq 12:48:44.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 12:48:44.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 12:48:44.16 
rabbitmq 12:48:44.16 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 12:48:44.18 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 12:48:44.19 INFO  ==> Initializing RabbitMQ...
rabbitmq 12:48:44.21 INFO  ==> Starting RabbitMQ in background...
rabbitmq 12:50:35.36 ERROR ==> Couldn't start RabbitMQ in background.
```



Do I need to edit my statefulset configuration file that has been deployed by helm install?

**Comment by amin224** [comment]
Following up on the issue, I found out that I need to change the nodename from` /opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq-env.conf` and the tcp listener from `/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.config`.

But I am not sure what the values should be changed to depending on my environment. Any support would be appreciated.

**Comment by miguelaeh** [comment]
Hi @amin224 ,
Checking the logs it seems that rabbimq did not start so that's why the readiness probe fails.
I am not totally sure about what are you trying to achieve, could you please share the detailed steps (commands you executed and modified configuration) from the beggining so I can try to reproduce the issue please? Also, could you tell us more aobut your environment?

**Comment by amin224** [comment]
I am trying to run a rabbitmq 3 instance cluster on AWS EKS environment using bitnami helm chart. I setup 3 ec2 instances for each rabbitmq pod, where I changed the replicas to 3 in the stateful set configuration file after installing helm chart.

**I used the persistence.existingClaim parameter in order to setup my own PVC and PV to resolve the volumeMount problem**
1. `helm install my-release bitnami/rabbitmq --set persistence.existingClaim=efs-claim`

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 8Gi
```
PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-rabbitmq-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-bccb8dc4
```

**As you may see I am using a File system storage type for my rabbitmq cluster**
```
kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
my-release-rabbitmq-0   0/1     Running   0          46s
```
2. As you can see the rabbitmq pod is in the running status but shorty after checking the logs mentioned above I am receiving an error on the readiness probe, which I am trying to resolve.
```
kubectl describe pod my-release-rabbitmq-0
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  57s   default-scheduler  Successfully assigned default/my-release-rabbitmq-0 to ip-192-.compute.internal
  Normal   Pulling    52s   kubelet            Pulling image "docker.io/bitnami/rabbitmq:3.8.11-debian-10-r0"
  Normal   Pulled     45s   kubelet            Successfully pulled image "docker.io/bitnami/rabbitmq:3.8.11-debian-10-r0"
  Normal   Created    44s   kubelet            Created container rabbitmq
  Normal   Started    44s   kubelet            Started container rabbitmq
  Warning  Unhealthy  8s    kubelet            Readiness probe failed: Error: unable to perform an operation on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: ['rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local']

rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local:
  * connected to epmd (port 4369) on my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-909-rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local'
 * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq
 * Erlang cookie hash: 4ojJe==
```
After reading the diagnostics I figured the problem could be due to the difference of node names mentioned in the events so I entered my pod using `kubectl exec --stdin --tty my-release-rabbitmq-0 -- /bin/bash` and my nodename value in rabbitmq-env.conf was `NODENAME=rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local` **Please your thoughts on this part**

Please note that I changed the readinessProbe and livenessProbe in the statefulset to try and fix this issue but I don't think it matters: 
```
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
```

**Comment by amin224** [comment]
@miguelaeh While reading the documentation I noticed that by default the node name is set to localhost which should not cause a problem as the /etc/hosts on the node is set to localhost. It makes me wonder why in the events the target node is causing this issue.

`RABBITMQ_NODE_NAME: Node name and host. E.g.: node@hostname or node (localhost won't work in cluster topology). Default rabbit@localhost. If using this variable, ensure that you specify a valid host name as the container wil fail to start otherwise. If using a fully qualified domain name, RABBITMQ_USE_LONGNAME needs to be set to true as well.`

cat /etc/hosts
```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
```

**Comment by amin224** [comment]
While reading on how to change a rabbitmq node name from here [nodename](https://sleeplessbeastie.eu/2020/02/03/how-to-specify-rabbitmq-node-name/)
It clearly states that entering the configuration file rabbitmq-env.conf and changing the nodename would resolve this issue, but what is absurd the fact that the nodename value is in fact `NODENAME=rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local`
But, as mentioned above, in the events of the describe pod my rabbitmq cluster is showing that the node name is `node name: 'rabbitmqcli-909-rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local`

**Comment by miguelaeh** [comment]
>After reading the diagnostics I figured the problem could be due to the difference of node names mentioned in the events so I entered my pod using kubectl exec --stdin --tty my-release-rabbitmq-0 -- /bin/bash and my nodename value in rabbitmq-env.conf was NODENAME=rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local Please your thoughts on this part

The node name seems to be properly configured. I don't think it is the actual issue.

>Can I include the rabbitmq node_name when installing the helm chart?

Since it is an statefulset the nodenames are pre-defined, so the idea is that the users must not modify them. Also, I don't hink there is any issue with the node name in your deployment. From the docs:

>For example, rabbit@node1.messaging.svc.local is a node name with the prefix of rabbit and hostname of node1.messaging.svc.local.

And, from the logs you shared: 

>attempted to contact: ['rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local']

That seems to be totally correct.

The issue here seems to be that the RabbitMQ pod has crashed, and because of that, the probes cannot contact the node. You will need to find why the pod has crashed instead of why the probe fails. I recommend to temporarily disable the probes setting `livenessProbe.enabled=false` and `readinessProbe.enabled=false`. Also, to be able to see more infor in the logs of the pod set `image.debug=true`. That should log more information about why the pod is failing. 

> I setup 3 ec2 instances for each rabbitmq pods

Also, could you clarify this? Are you creating your custom k8s cluster?

**Comment by amin224** [comment]
> I recommend to temporarily disable the probes setting livenessProbe.enabled=false and readinessProbe.enabled=false. Also, to be able to see more infor in the logs of the pod set image.debug=true. That should log more information about why the pod is failing.

After applying the above commands I am getting the actual errors, as you were correct regarding the issue not being the node name. I will try and fix them, thank you for your continued support @miguelaeh 

```
kubectl logs -f my-release-rabbitmq-0 
rabbitmq 11:20:34.86 
rabbitmq 11:20:34.86 Welcome to the Bitnami rabbitmq container
rabbitmq 11:20:34.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 11:20:34.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 11:20:34.86 
rabbitmq 11:20:34.86 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 11:20:34.87 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 11:20:34.89 INFO  ==> Initializing RabbitMQ...
rabbitmq 11:20:34.89 DEBUG ==> Creating environment file...
rabbitmq 11:20:34.89 DEBUG ==> Creating enabled_plugins file...
rabbitmq 11:20:34.90 DEBUG ==> Creating Erlang cookie...
rabbitmq 11:20:34.90 DEBUG ==> Ensuring expected directories/files exist...
rabbitmq 11:20:34.91 INFO  ==> Starting RabbitMQ in background...
Waiting for erlang distribution on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local' while OS process '45' is running
Configuring logger redirection
11:20:37.345 [warning] Failed to write PID file "/bitnami/rabbitmq/mnesia/rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local.pid": permission denied
11:20:37.477 [error] Failed to create Ra data directory at '/bitnami/rabbitmq/mnesia/rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local/quorum/rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local', file system operation error: enoent
11:20:37.478 [error] CRASH REPORT Process <0.244.0> with 0 neighbours exited with reason: {error,"Ra could not create its data directory. See the log for details."} in ra_system_sup:init/1 line 43
11:20:37.478 [error] Supervisor ra_sup had child ra_system_sup started with ra_system_sup:start_link() at undefined exit with reason {error,"Ra could not create its data directory. See the log for details."} in context start_error
11:20:37.478 [error] CRASH REPORT Process <0.238.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,ra_system_sup,{error,"Ra could not create its data directory. See the log for details."}}},{ra_app,start,[normal,[]]}} in application_master:init/4 line 138
{"Kernel pid terminated",application_controller,"{application_start_failure,ra,{{shutdown,{failed_to_start_child,ra_system_sup,{error,\"Ra could not create its data directory. See the log for details.\"}}},{ra_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,ra,{{shutdown,{failed_to_start_child,ra_system_sup,{error,"Ra could not create its data directory. See the log for details."}

Crash dump is being written to: erl_crash.dump...Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local' while OS process '45' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local' while OS process '45' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local' while OS process '45' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local' while OS process '45' is running
Error:
process_not_running
Waiting for erlang distribution on node 'rabbit@my-release-rabbitmq-0.my-release-rabbitmq-headless.default.svc.cluster.local' while OS process '45' is running
Error:
process_not_running
rabbitmq 11:22:26.08 ERROR ==> Couldn't start RabbitMQ in background.
```

**Comment by amin224** [comment]
I resolved this issue by editing the statefulset yaml file by changing the value of runAsUser from 1001 to 0 so that the container of the Pod can be run as root and will not get permission denied. 
```
    securityContext:
      runAsUser: 0
```

Thank you so much @miguelaeh I wouldn't have been able to reach here without you.

**Comment by miguelaeh** [comment]
I am glad you found the issue @amin224.
As a recomendation, since the issue finally seems to be the permissions with the persistent volume, you could try to use `volumePermissions.enabled=true` instead of changing the securityContext. That will allow your rabbitMQ container to run as non-root and an init container will change the permissions of the volume so RabbitMQ should be able to write.

**Comment by rakeshnambiar** [comment]
Hi @amin224 in my case, I have 3 nodes that use 3 PVCs. In this scenario, how do I specify the value for `persistence.existingClaim`?

**Comment by miguelaeh** [comment]
Hi @rakeshnambiar ,
I think that would not be possible since the existingClaim is to provide the same PVC for all the pods, while to use a different PVC per pod the volumeClainTemplate is used.

**Comment by rakeshnambiar** [comment]
@miguelaeh Thanks for your reply. Sad to hear that it won't possible. The old `stable/rabbitmq-ha` normally supports it. It's a shame isn't it?

**Comment by miguelaeh** [comment]
Hi @rakeshnambiar ,
Would you like to create a PR adding such a feature? We will be more than happy to review it
