### ISSUE TITLE
[postgresql-ha] verbose naming causes errors with pgpool...

### ISSUE THREAD

**Issue by TJM** [bitnami/charts#5387]
**Which chart**: 
* Name:`postgresql-ha`
* Version: `6.5.0`

**Describe the bug**

```console
postgresql-ha: Nodes hostnames
    PostgreSQL nodes hostnames (artifactory-ha-db-postgresql-ha-postgresql-00.artifactory-ha-db-postgresql-ha-postgresql-headless.artifactory.svc.cluster.local:1234) exceeds the characters limit for Pgpool: 128.
    Consider using a shorter release name or namespace.
```

Apparently it is (release-name)-(chart-name)-postgresql-00.(release-name)-(chart-name)-postgresql-headless.(namespace).svc.cluster.local:1234 ?

That seems overly verbose, right? Can it be shortened (truncated?) automatically?

I have seen other templates that "trim" the generated names when they exceed a certain length, that seems like it would be useful. Alternatively, instead of spelling out "postgresql" 4 times in the hostname, maybe that could be shortened (pg) (psql) (pgsql)? *(shrug)*

**To Reproduce**

1. Deploy postgresql-ha helm chart with release name over 14 chars like `artifactory-db` in a namespace `artifactory`
2. See Error

**Expected behavior**
The name should be trimmed or PGPOOL should be modified to support longer names

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```console
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-gke.6600", GitCommit:"cfb955f37f5546d5bf811091337d2025e2a79267", GitTreeState:"clean", BuildDate:"2020-09-17T09:21:09Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The release name is currently limited to *53* characters, but may soon be allowed to be as long as 256!? - https://github.com/helm/helm/issues/6006

https://github.com/bitnami/charts/blob/ecdb402ebb45dfa7a0589b663bf6d8685e37c1c0/bitnami/postgresql-ha/templates/_helpers.tpl#L3-L17

Perhaps the "trunc" here needs to be smaller until PGPOOL can be fixed?

ALSO: the port number should be `5432` .... I have to admit I was looking around for what the heck was using port 1234 ;)

**Comment by TJM** [comment]
OMFG, I was going to file a followup issue for PGPOOL to request an enhancement to raise the limit from 128 to maybe 256 or something super crazy huge like that :P ... but I am *not* joining a mailing list to do so. We are too spoiled by GitHub :)

**Comment by carrodher** [comment]
Hi @TJM, thanks for letting us know. I just created the above PR, please, can you give it a try? It would be very useful for us to check if it covers your specific use case, we have some automated tests, but not all the use cases are covered.
