### ISSUE TITLE
InfluxDB s3 backup option

### ISSUE THREAD

**Issue by ErwinSteffens** [bitnami/charts#5388]
**Which chart**:
influxdb

**Is your feature request related to a problem? Please describe.**
Add a back-up upload provider for uploading to a S3 bucket. 

**Describe the solution you'd like**
The same as the Azure/Google backup cronjob script but use an AWS cli container to upload to S3. 

**Describe alternatives you've considered**
Maybe there is some other way that this is already possible, but that I could not find. 

**Additional context**
See the chart supplied by InfluxData: 
https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/backup-cronjob.yaml#L128

**Comment by andresbono** [comment]
Hi @ErwinSteffens, thanks for proposing this feature request! It makes sense! Would you like to open a PR implementing the changes? Contributions are more than welcome! We can help you in the process.

The chart should use Bitnami based container images but we already have a container for AWS CLI: https://github.com/bitnami/bitnami-docker-aws-cli
