### ISSUE TITLE
[bitnami/mongodb] Steps to take in order to increase the size of the db

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/charts#5391]
Hi friends,

When i initially setup mongo using this helm chart i set the `persistence.size` to be 50Gi. With my setup. when i deployed this chart it automatically created a PVC called ` datadir-mongo-prod-mongodb-0 ` with a capacity of `50Gi`.

Today my requirements have changed and i need the size of my mongo to be larger - 250Gi. 

I have two questions.

1. If i change the value of `persistence.size` from 50Gi to 250Gi and redeploy, what happens?
2. What steps do i need to take with this chart to increase the size of my database and how will it affect the data?

I'm just looking for some guidance on how i can go about increasing the size of my mongo database. Is there a seemless way to do this that involves simply increasing the  size of the existing PVC or would it create a new PVC which would require manual backing up and restoring of the data.

thank you

**Comment by miguelaeh** [comment]
Hi @kaykhancheckpoint ,
To do that, the storage class you are using must be configured to allow volume expansion. Check this: https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by kaykhancheckpoint** [comment]
@miguelaeh " sorry, can you explain a bit more? 

So my storage class has volume expansion enabled, im just looking for a bit more explanation, is it possible to do what ive described above with changing the value of persistence.size and will mongo recognize the increased storage.

**Comment by miguelaeh** [comment]
Hi @kaykhancheckpoint ,

>is it possible to do what ive described above with changing the value of persistence.size

If you volume has the expansion properly configured it should be expanded editing the persistence.size. Theorically no more actions would be needed, but I recommend you to test it before making those changes in a production environment, so in case something goes wrong it will not have fatal consecuences.
