### ISSUE TITLE
setting rabbitmq password not working with helm release command

### ISSUE THREAD

**Issue by besha100** [bitnami/charts#5396]
**Which chart**:
rabbitmq chart 8.9.2 

**Describe the bug**
setting the password is not working when doing helm release 

**To Reproduce**
1- helm release
$ helm install my-release \
  --set auth.username=admin,auth.password=secretpassword,auth.erlangCookie=secretcookie \
    bitnami/rabbitmq

2- when trying to login the password remains "CHANGEME", and is not changed to "secretpassword"

**Expected behavior**
Expected to login with the new set passoword  "secretpassword"

**Version of Helm and Kubernetes**:

kuberenetes 1.17.16 and helm version 3 

- Output of `helm version`:

version.BuildInfo Version:"v3.2.4"

- Output of `kubectl version`:

Client Version: version.Info Major:"1", Minor:"18", GitVersion:"v1.18.3",

**Comment by juan131** [comment]
Thanks for opening the issue, I added some comments in the PR

**Comment by besha100** [comment]
@juan131 I have tried that but the logic somewho is not working. When I execute 
 helm install my-release
--set auth.username=admin,auth.password=secretpassword,auth.erlangCookie=secretcookie
bitnami/rabbitmq

the password is not reset to the secretpassword I have, and remains "CHANGEME". I needed to changed default_pass to {{ .Values.auth.password }} for it to work!

**Comment by juan131** [comment]
Hi @besha100 

Did you remove the PVC from previous installations? It's very likely that you're facing the error described in the Troubleshooting guide, see:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases
