### ISSUE TITLE
[bitnami/mysql] in flie bitnami/mysql charts，the value in values.yaml and templates/primary(or secondary ) file do not match

### ISSUE THREAD

**Issue by tulid** [bitnami/charts#5398]
**Which chart**:
The name (and version) of the affected chart
bitnami/mysql

**Describe the bug**

Wait helm template failed. Error: template: mysql/templates/secondary/pdb.yaml:1:58: executing "mysql/templates/secondary/pdb.yaml" at <.Values.secondary.pdb.enabled>: nil pointer evaluating interface {}.pdb Use --debug flag to render out invalid YAML : exit status 1

**Reason**
the value in values.yaml and templates/primary(or secondary ) file do not match
details as below:
in values.yaml 
```
primary:
  pdb:
      created: false
secondary:
  pdb:
      created: false
```
but 
in `templates/primary/pdb.yaml`
```
{{- if .Values.primary.pdb.`enabled` }}
```
in `templates/seconary/pdb.yaml`
```
{{- if and (eq .Values.architecture "replication") .Values.secondary.pdb.`enabled` }}
```

**Comment by andresbono** [comment]
Hi @tulid, thanks for reporting this issue. The helm templates used in the pdb files and the values specified in the `README.md` and in the `values.yaml` don't match. We are going to fix it by opening a new PR.

**Comment by andresbono** [comment]
This should be fixed now. Please use `enabled` instead of `create` from now on. Thanks for reporting the bug.

**Comment by tulid** [comment]
Can you tell me how to get the root permissions of mysql container ? Or, tell me how test the bitnami mysql containers performance using other way.  because i want to test the mysql container performance by installing the tool of sysbench as below. Thanks a lot.
"
wget https://github.com/akopytov/sysbench/archive/1.0.zip -O "sysbench-1.0.zip"
unzip sysbench-1.0.zip
cd sysbench-1.0
yum install automake libtool –y
./autogen.sh
./configure
export LD_LIBRARY_PATH=/usr/local/mysql/include 
make
make install
[root@test sysbench-1.0]# sysbench --version
sysbench 1.0.9
"



jinquan.wu@foxmail.com
 
发件人： Andrés Bono
发送时间： 2021-02-09 18:31
收件人： bitnami/charts
抄送： easyfont; Mention
主题： Re: [bitnami/charts] [bitnami/mysql] in flie bitnami/mysql charts，the value in values.yaml and templates/primary(or secondary ) file do not match (#5398)
This should be fixed now. Please use enabled instead of create from now on. Thanks for reporting the bug.

**Comment by miguelaeh** [comment]
Hi @tulid ,
If you want to run them as root you can change the `securityContext.runAsUser` parameter
