### ISSUE TITLE
On a 3 node multinode setup 2 redis pods are acting as MASTER

### ISSUE THREAD

**Issue by mahanam** [bitnami/charts#5400]
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

**Which chart**:
name: redis
version: 11.1.0
appVersion: 6.0.8

**Describe the bug**
We observed that on a 3 node setup 2 Redis pods are acting as a MASTER.

**To Reproduce**
1. Deployed the Redis pods on 3 nodes
2. Removed the failed node where Redis master was running.
3. After removing the node, other Redis slave became master on another node as expected.
4. At this stage bring a new node and attach it to the k8s cluster.
5. Once the new node comes up, Redis pod on that pod acting as a master.
6. This should not be expected.

**Expected behavior**
There should be only a single master Redis pod.

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl exec -it redis-master-node-2 redis-cli info replication
Defaulting container name to redis.
Use 'kubectl describe pod/redis-master-node-2 -n default' to see all of the containers in this pod.
# Replication
role:slave
master_host:10.233.64.28
master_port:6379
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
slave_repl_offset:3242729
slave_priority:100
slave_read_only:1
connected_slaves:0
master_replid:5a5461f6ba3104eafce2df94aeccab22134a41ac
master_replid2:d381d264b51bdb9633850474fcdf27f9d169660d
master_repl_offset:3242729
second_repl_offset:828357
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2194154
repl_backlog_histlen:1048576

$ kubectl exec -it redis-master-node-1 redis-cli info replication
Defaulting container name to redis.
Use 'kubectl describe pod/redis-master-node-1 -n default' to see all of the containers in this pod.
# Replication
role:master
connected_slaves:1
slave0:ip=10.233.68.30,port=6379,state=online,offset=3243299,lag=1
master_replid:5a5461f6ba3104eafce2df94aeccab22134a41ac
master_replid2:d381d264b51bdb9633850474fcdf27f9d169660d
master_repl_offset:3243299
second_repl_offset:828357
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2194724
repl_backlog_histlen:1048576

$ kubectl exec -it redis-master-node-0 redis-cli info replication
Defaulting container name to redis.
Use 'kubectl describe pod/redis-master-node-0 -n default' to see all of the containers in this pod.
# Replication
role:master
connected_slaves:0
master_replid:3424592d0e34a3c4b654dd0114c478b0f0216a69
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

**Comment by miguelaeh** [comment]
Hi @mahanam ,
It seem you are using a really old version of the Redis Chart. You are using `11.1.0` while the latest one is `12.7.4`.
Could you give a try to update it?
