### ISSUE TITLE
[bitnami/phpbb] volumePermissions paramter

### ISSUE THREAD

**Issue by per-lind** [bitnami/charts#5401]
The volumePermissions does not work as the name on the volume is invalid. I belive it should be named _phpbb-data_

https://github.com/bitnami/charts/blob/74f2fd8f163cb4a9aa48bae1cb2a674ce4de2ae4/bitnami/phpbb/templates/deployment.yaml#L80

`Error: UPGRADE FAILED: cannot patch "fopw-phpbb" with kind Deployment: Deployment.apps "fopw-phpbb" is invalid: [spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "data", spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"fopw", "app.kubernetes.io/name":"phpbb"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]

`

**Comment by per-lind** [comment]
@javsalgar just a heads up on this issue

**Comment by miguelaeh** [comment]
Hi @per-lind ,
It seems you are right, the volume name seems to be wrong. Would you like to create a PR fixing it?
