### ISSUE TITLE
[bitnami/thanos] receive Ingress is broken?

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#5404]
https://github.com/bitnami/charts/blob/41be44c267b104762815b6963bae864fdc0b91d0/bitnami/thanos/templates/receive/ingress.yaml#L2

Helm upgrade failed: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.extensions.v1beta1.IngressBackend

**Comment by javsalgar** [comment]
Thank you so much for the PR! Already merged. It seems we forgot to change the API Version when updating the Ingress rules.
