### ISSUE TITLE
Cluster configuration issues when the chart is a su-chart.

### ISSUE THREAD

**Issue by mumbley** [bitnami/charts#5405]
**Which chart**:
MongoDB version 10.16.1
**Describe the bug**
Secrets and other components fail to deploy as expected when the chart is a sub-chart of a master chart
**To Reproduce**
1. Create a master chart
2. Create a `requirements.yaml` in the master chart including the mongo chart
```
...
- name: mongodb
  alias: mongo
  condition: global.manifests.beekeeper.enabled
  version: "10.6.1"
  repository: "https://charts.bitnami.com/bitnami"
  ...
```
3. deploy master chart
4. Check secrets `kubectl get secrets`
If the chart is run standalone then it has a set of secrets thus:
```
kubectl get secrets
NAME                          TYPE                                  DATA   AGE
default-token-lrqd5           kubernetes.io/service-account-token   3      3d3h
mongo-mongodb                 Opaque                                3      67m
mongo-mongodb-token-6lfxz     kubernetes.io/service-account-token   3      67m
sh.helm.release.v1.mongo.v1   helm.sh/release.v1                    1      67m
```
but if I deploy as a sub-chart these secrets do not get created. 

**Expected behavior**
I would expect that the features of the chart get deployed as if this was a master chart.

**Version of Helm and Kubernetes**:
Helm v3.2.4
Kubernetes v1.18.9
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I suspect this may be because master charts only cascade through one set of dependancies and that this had it's own sub-charts that provide rules on deployment (i.e. they govern what is deployed and how)

**Comment by juan131** [comment]
Hi @mumbley 

I installed the [Bitnami Node chart](https://github.com/bitnami/charts/tree/master/bitnami/node) that uses the MongoDB chart as dependency to try to reproduce your issue.

As you can see in the commands below, everything is working as expected:

```console
$ helm install node bitnami/node
NAME: node
LAST DEPLOYED: Mon Feb  8 10:08:32 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the URL of your Node app  by running:

  kubectl port-forward --namespace default svc/node 80:80
  echo "Node app URL: http://127.0.0.1:80/"

$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
node-8645ff9cc4-l5f25           1/1     Running   2          2m31s
node-mongodb-849f56768d-lgmnj   1/1     Running   0          2m31s
$ kubectl get secrets
NAME                         TYPE                                  DATA   AGE
default-token-ttc5j          kubernetes.io/service-account-token   3      6m25s
node-mongodb                 Opaque                                2      2m43s
node-mongodb-token-xbktj     kubernetes.io/service-account-token   3      2m43s
sh.helm.release.v1.node.v1   helm.sh/release.v1                    1      2m43s
```

**Comment by mumbley** [comment]
@juan131 Thanks for this. I read through the chart and it looks like the problem was PEBKAC.  :) I have re-written the values we use to override the values.yaml and it now works fine.  Your response helped me to ignore what was just a false positive and focus elsewhere so thanks for that.

**Comment by juan131** [comment]
You're welcome @mumbley! I'm very glad you were able to identify the issue
Please don't hesitate to let us know if you require further help.
