### ISSUE TITLE
[bitnami/wordpress] Option to use SSL-enforced External Database

### ISSUE THREAD

**Issue by aks-wp** [bitnami/charts#5409]
**Which chart**:
https://charts.bitnami.com/bitnami 10.0.7

**Is your feature request related to a problem? Please describe.**
We use an Azure-managed mySQL external database. When enforcing SSL, there doesn't appear to be a straightforward way of having WordPress add the required CA cert and update the wpconfig to use SSL

**Describe the solution you'd like**
Provide database parameters to use SSL and include a secret (for the cert) 

**Describe alternatives you've considered**
Steps:

1. Get cert from https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
2. Convert to .crt
3. Copy it to _/usr/local/share/ca-certificates/_ 
4.  Run `update-ca-certificates `
5. Update wp-config.php with `define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);`

Are there any better alternatives which we could try meanwhile?

**Comment by rafariossaa** [comment]
Hi,
  Thanks for you suggestion, I am creating an internal task to implement this feature.
  I am sorry I can not give an ETA for this task.
  In the meanwhile, would you like to send a PR implementing this ? We will be glad to review and merge it.

**Comment by aks-wp** [comment]
Thank you for your quick response @rafariossaa 
Do you have any recommendations to implement the work-around? Since the DB connection needs to be initialized first, it wouldn't be possible to use the `customPostInitScripts` feature for steps 3-5 mentioned above.

**Comment by rafariossaa** [comment]
Hi,
  Yes, you should be able to that using `customPostInitScripts` as workaround.

**Comment by aks-wp** [comment]
@rafariossaa So that was my question - We already use `customPostInitScripts`  for another purpose and as expected, this runs AFTER the DB has been initialized. In this context, we need this right at the start.  Included logs to clarify. 

Also, on a related note, we weren't able to change the permissions on  /usr/local/share/ca-certificates/ to run steps 3 and 4.
There's no problem with updating the wp-config.php file though 

wordpre INFO  ==> Preparing Varnish environment
wordpre DEBUG Deleting the Varnish example configuration file
wordpre INFO  ==> Preparing Apache environment
wordpre DEBUG Creating the Apache configuration vhost file
wordpre DEBUG Creating the Apache configuration https vhost file
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
......
runs all initialization steps
........
then
.........
app-entrypoint.sh 04:47:06.63 INFO  ==> Starting gosu... 
shell.sh 04:47:06.64 INFO  ==> Executing /docker-entrypoint-init.d/..2021_02_11_04_46_05.336975571/custom-post-init.sh
Updating wp-config file

**Comment by rafariossaa** [comment]
Hi,
  With the current logic it is not possible to run scripts at other points.
  Maybe you would like to create your image and customize `app-entrypoint.sh` .
  For the SSL, Did you try by setting `WORDPRESS_DATABASE_SSL_CA_FILE` [environment variable](https://github.com/bitnami/bitnami-docker-wordpress#user-content-connect-wordpress-docker-container-to-an-existing-database) ?

**Comment by aks-wp** [comment]
Thank you! @rafariossaa That's exactly what we were looking for. Works great and takes care of the steps outlined, including updating the wp-config.php file with SSL related configuration. 

`  extraEnvVars: 
     - name: WORDPRESS_DATABASE_SSL_CA_FILE
       value: /mnt/certs/cert.pem`
