### ISSUE TITLE
don't create random password every time on default postgresql install

### ISSUE THREAD

**Issue by Morriz** [bitnami/charts#5412]
**Which chart**:
postgresql: 11.10.0

**Is your feature request related to a problem? Please describe.**
The default values result in the chart getting a diff every time. 

**Describe the solution you'd like**
I would expect at least to be told how to avoid that, but preferably I would be told to provide secrets myself.

**Comment by juan131** [comment]
Hi @Morriz 

To avoid that, it's as simple as indicating the passwords everytime you upgrade the PostgreSQL chart. Indeed, in recent versions we included some validations that will block the upgrade process unless you pass the to avoid issues with the credentials.

You can find more information in the README.md file, see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#upgrading
And, also, in the Troubleshooting Guide, see https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

> preferably I would be told to provide secrets myself.

This helm chart already provides this feature. Check the `existingSecret` parameter in the [parameter list](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#parameters).

**Comment by Morriz** [comment]
Does that imply chart users need to pre-create a secret? That would be tedious. I would expect this chart to provide all of the functionality needed to have a good UX from automation/devops perspective.

I strongly suggest to give chart users the option to provide their secret value, and let the chart do what it needs. If that involves creating a secret, the chart should be responsible for it imo.

**Comment by juan131** [comment]
Hi @Morriz 

> Does that imply chart users need to pre-create a secret? 

Yes, if you use the `existingSecret` parameter, the secret must exist beforehand.

> I strongly suggest to give chart users the option to provide their secret value, and let the chart do what it needs

The chart also provides this option. Check the `postgresqlPostgresPassword`, `postgresqlUsername`, `postgresqlPassword`, `postgresqlDatabase` parameters in the [parameter list](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#parameters).

**Comment by Morriz** [comment]
Thanks a lot, of course I did not do my homework.

**Comment by Morriz** [comment]
Well, I have to revisit this, as it does not work as intended. I have to provide `existingSecret` to create one on the fly with that name. Confusing, and not according to the docs.
