### ISSUE TITLE
Keycloak - can't change http port

### ISSUE THREAD

**Issue by tampler** [bitnami/charts#5414]
**Which chart**: keycloak-2.0.0 ( Keycloak app version is 12.0.2)

**Describe the bug**
When I set `--set containerPorts.http=8885`, the http port changes in `statefulset`, but not the `service`. As a result, `pod` won't boot properly and I can't do port-forward for my port `8885`

STS:
```
    Image:       docker.io/bitnami/keycloak:12.0.2-debian-10-r6
    Ports:       **8885/TCP**, 8443/TCP, 9990/TCP
```

SVC:
```
NAME                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
keycloak            ClusterIP   10.104.93.79   <none>        **80/TCP**,443/TCP   29m
```
**To Reproduce**
```
helm install --namespace ${ns} ${package} bitnami/keycloak \
--set service.type=ClusterIP \
--set containerPorts.http=8885 \
--set postgresql.enabled=false \
.... / Postgres Setup/
```
**Expected behavior**
SVC port is 8885

**Version of Helm and Kubernetes**:
Kube : 1.20.2
Helm : 3.5.2

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by carrodher** [comment]
There are different parameters to customize the [container port](https://github.com/bitnami/charts/tree/master/bitnami/keycloak#keycloak-deploymentstatefulset-parameters) and the [service port](https://github.com/bitnami/charts/tree/master/bitnami/keycloak#exposure-parameters). In the first case (`containerPorts.*`), the parameter is going to change the port used by the container itself, while in the second case (`service.*`) the service port is going to be modified.

Depending on your use case and what you want to achieve with the change, you will need to change only the container port, only the service port, or both.

**Comment by tampler** [comment]
@carrodher Thanks, I overlooked those settings. This solves my problem.

Kind regards,
Boris
