### ISSUE TITLE
Is it possible to use cephfs shared storage on a elastic search cluster ?

### ISSUE THREAD

**Issue by chromafunk** [bitnami/charts#5416]
Hi, I wanted to thank you first for putting together the elasticsearch cluster chart. Everything is working well so far, but I have a question, and is that if it would be possible to use a shared filesystem PV like cephfs for the data nodes, since the nature of the cluster is master load balanced, I was wondering if sharing a common volume for the data nodes would be possible

Thanks

**Comment by rafariossaa** [comment]
HI,
  I am not very sure on the internals of elasticsearch, but my guess is that it won't be possible because each node should hold its own state and data. My suggestion is to post this question on elasticsearch forum were you may have a better answer.
