### ISSUE TITLE
[bitnami/external-dns] Add the PodDisruptionBudget

### ISSUE THREAD

**Issue by SatoruItaya** [bitnami/charts#5417]
**Which chart**:
`bitnami/external-dns`

**Is your feature request related to a problem? Please describe.**
Safe eviction is not guaranteed because of the lack of the `PodDisruptionBudget`.

**Describe the solution you'd like**
I would like to add the `PodDisruptionBudget` in the Helm Chart.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Mauraza** [comment]
Hi @SatoruItaya, 

we always open to contribution, would you like to create a pull request adding `PodDisruptionBudget` to the chart `external-dns`?

**Comment by SatoruItaya** [comment]
@Mauraza 
Thanks for your response.
Yes, I would like to do.
I will create a PR later.

**Comment by Mauraza** [comment]
Hi @SatoruItaya,

great! looking forward to seeing the PR.

Thanks!!

**Comment by joebowbeer** [comment]
What's the utility of pdb with 1 replicas?

https://github.com/kubernetes-sigs/external-dns/pull/3632#issuecomment-1568061095
