### ISSUE TITLE
[redis-cluster] question on persistence

### ISSUE THREAD

**Issue by f18m** [bitnami/charts#5436]
**Which chart**:
redis-cluster 4.2.7

**Describe the bug**
I deployed the redis cluster with persistence enabled. The cluster creation completes successfully.
However I noticed that, if I remove the chart, and reinstall it, the new chart will fail the redis cluster creation because the init job will complain about shards having some keys inside them.

How am I supposed to have redis-cluster data with persistence and still be able to uninstall&reinstall/upgrade the Bitnami chart?

Thanks!

**Comment by rafariossaa** [comment]
Hi,
  When reinstalling and keeping data, you have to provide the same password you used. If you didn't set it an new random one is generated and it won't be able to connect to redis as the password won't match.
