### ISSUE TITLE
[mongodb-sharded] Support for global.namespaceOverride

### ISSUE THREAD

**Issue by fredlebel** [bitnami/charts#5439]
**Which chart**:
mongodb-sharded (3.3.1)

**Is your feature request related to a problem? Please describe.**
Would like to support multiple installs in different namespaces.

**Describe the solution you'd like**
Add support for `global.namespaceOverride` as the non-sharded Mongo chart supports.

**Describe alternatives you've considered**
Alternative is to use different name overrides.

**Comment by Mauraza** [comment]
Hi @fredlebel,

thanks for the suggestions, could you create a pull request with this change? You can follow this [guide](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) to contribute.
