### ISSUE TITLE
[bitnami/etcd] ETCD cluster fails after restart due to member remove

### ISSUE THREAD

**Issue by Excpt0r** [bitnami/charts#5443]
**Which chart**:
etcd 5.6.0

changes in values.yaml:
```
debug: true
replicaCount: 3
auth:
  rbac:
     enabled: false
```

**Describe the bug**
Issue #1908 is not really fixed. Situations with upgrade/rollout where a majority etcd nodes remain running might work, but not the following:

With a 3 node etcd cluster installed, when pods are terminated, they call a `member remove` by the script `prestop-hook.sh`.
This leads to issues when starting the cluster again with existing persistent data, the members are rejecting each other, because the were removed before.

**To Reproduce**
Steps to reproduce the behavior (in bitnami/etcd chart folder):

1. `helm install --name-template etcd .` and wait until the pods are Running and in Ready state
2. `helm uninstall etcd` and wait until all pods are terminated, PV content must be kept
3. `helm install --name-template etcd .` again
4. See that some pods keep restarting with failure (etcd-0 and etcd-2 in my attachment, etcd-2 was just restarting again. etcd-1 ist Running and Ready, and rejecting other members).
[etcd-0.log](https://github.com/bitnami/charts/files/5957660/etcd-0.log)
[etcd-1.log](https://github.com/bitnami/charts/files/5957661/etcd-1.log)
[etcd-2.log](https://github.com/bitnami/charts/files/5957662/etcd-2.log)

**Expected behavior**
A restart (uninstall + install) of the etcd cluster should be possible, reading of the existing persistent data should be possible.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-05-20T13:09:31Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
A hotfix that was already mentioned in #1908 is to comment out the `member remove` line [here](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/scripts-configmap.yaml#L220).
Not sure if the chart is currently scalable, and `member remove` is needed therefore.
But I would consider it more important to be able to read persistent data after a complete restart or failure. I suggest to include the hotfix, until a better solution is there.

**Comment by marcosbc** [comment]
Thanks for creating this issue! I've created an internal task for looking into this issue to determine what is happening. Unfortunately I cannot give an ETA for when we fix it.

**Comment by marcosbc** [comment]
https://github.com/bitnami/charts/issues/1513 is also related

**Comment by ChiefAlexander** [comment]
I think a quick bandaid here for those that are experiencing a problem is to have a flag to disable this pre-stop hook completely. Would that be acceptable?

**Comment by marcosbc** [comment]
It was implemented for disaster recovery, so my understanding is that it was required if you wanted to be able to restore a cluster, so I don't think it's ideal. @juan131 can you confirm?

**Comment by juan131** [comment]
Hi everyone,

I'm currently working on improving the logic in the scripts that boot etcd since we're observing a flaky behaviour under certain circumstances, expect news from me about this in the following days.

> I think a quick bandaid here for those that are experiencing a problem is to have a flag to disable this pre-stop hook completely. Would that be acceptable?

We could include a flag like that, I don't see any problem on it. That said, it shouldn't be necessary. I mean, the logic should be able whether the "pre-stop" hook was successfully completed or not, and act accordingly when bringing up the container again.

**Comment by ChiefAlexander** [comment]
I think that users should be able to decide if they want an etcd member to be removed on pod stop or not. Regardless of the need of this script always working as intended.

**Comment by juan131** [comment]
I agree with you @ChiefAlexander 

I'll add the possibility to remove the container lifecycle hooks in the PR I'm working on.

**Comment by juan131** [comment]
We just released a new major version of the etcd chart (**6.0.0**) including new features and introducing changes in the etcd that attempt to improve the stability of the chart on operations such as scaling or updating the etcd cluster, see the link:

- https://github.com/bitnami/charts/tree/master/bitnami/etcd#to-600

We also improve the [docs](https://docs.bitnami.com/kubernetes/infrastructure/etcd), and create a specific section that explains details about how this chart works on operation such as bootstrapping or scaling (not available in the doc system yet), see

- https://github.com/bitnami/charts-docs/blob/main/charts/etcd/_understand_default_configuration.md.erb

Please give a try to the new major version, and share feedback about it. Thanks in advance!
