### ISSUE TITLE
[bitnami/redis-cluster] How to run backup script as cron job (daily)?

### ISSUE THREAD

**Issue by bharat15-ml** [bitnami/charts#5448]
**Which chart**:
redis-cluster-4.3.1

**Is your feature request related to a problem? Please describe.**
I am trying to run backup-script as a cron job on each pod daily. have tested the backup script working fine on each pod from location [/opt/bitnami/redis/backup-scripts/redis_backup_local.sh].

Wanted to know three things-
1. How I can schedule this script as a cron job on daily basis on each pod?
2. Current deployment having one persistent storage, i.e.- "/bitnami/redis/data", similarly I wanted to create one more backup storage to store daily backup data. how I can create one more persistent storage(backup)? (wanted to enable service specific storage , have read about **Velero** cluster backup, but it's not applicable as per current requirement)
3.  What is subPath in persistence section of helm chart, how it can be used?

Please provide me a comment on above points to get better clarity on it.

**Comment by miguelaeh** [comment]
Hi @bharat15-ml ,

> How I can schedule this script as a cron job on daily basis on each pod?

The only wy I can think right now it to add a sidecar container with the cronjob configuration that executes your script and stores the result in a new volume. Check the `sidecars` parameter from the Values.yaml

> Current deployment having one persistent storage, i.e.- "/bitnami/redis/data", similarly I wanted to create one more backup storage to store daily backup data. how I can create one more persistent storage(backup)? (wanted to enable service specific storage , have read about Velero cluster backup, but it's not applicable as per current requirement)

You can try to use the `extraVolumes` and `extraVolumeMounts` parameters, mount the new volume into the sidecar container and configure the script to store the data into that new volume.

> What is subPath in persistence section of helm chart, how it can be used?

The subpath is used when a volume is shared to avoid writting into the volume root. It will indicate to write into the specified subpath inside the volume root mount point.


I hope that information is usefull for your use case.

**Comment by bharat15-ml** [comment]
Thanks Miguelaeh for the info. Coming to the second point, I wanted one more persistent path for backup data, through extraVolumes and extraVolumeMounts that location depends on podlifecycle.

 How I can create one more persistent path to store backup data??

**Comment by javsalgar** [comment]
Hi,

I think that using the `extraDeploy` section, you could add the YAML of a cron job that performs the backup to a volume of your choice. You could reference it to an existing PVC or even add the code for deploying the PVC yaml. In the kafka README.md we have an example of how to use the this value. https://github.com/bitnami/charts/tree/master/bitnami/kafka#deploying-extra-resources

The redis-cluster chart also contains this value so you could adapt it to your needs.
