### ISSUE TITLE
[bitnami/drupal] Site doesn't render correctly when configured with SMB share

### ISSUE THREAD

**Issue by rickrain** [bitnami/charts#5450]
**Which chart**
- helm.sh/chart=drupal-10.2.1
- Image: docker.io/bitnami/drupal:9.1.3-debian-10-r0

**Describe the bug**
When I configure Drupal to mount an SMB File Share PVC for site content and configuration, the site doesn't render (CSS) correctly over http.  However, if I access the site over https, then it does render correctly.

I believe this is related to the SMB share because if I use the default persistence configuration whereby site content and configuration is stored in the container file system, then it works as expected for both http/s.

**To Reproduce**

1. Create a single node cluster on Azure AKS.

2. Change [this section](https://github.com/bitnami/charts/blob/eaffdc080719c891827aad846dd8d35baaaefd40/bitnami/drupal/values.yaml#L367) of `values.yaml` as shown here:4

```yaml
persistence:
  enabled: true
  storageClass: "azurefile-premium"
  accessMode: ReadWriteMany
  size: 100Gi
  hostPath:
```
3. Install the helm chart with my updated values:

```yaml
helm install my-release -f <path to my values.yaml file> bitnami/drupal
```

4. After the site is initialized, open a browser and navigate to `http://<public IP of site>/`

**Expected behavior**
The site should render correctly.  Instead, it renders as shown.  Also, notice the response body is invalid.

![Screenshot from 2021-02-09 18-02-10](https://user-images.githubusercontent.com/3990654/107536558-87eac880-6b87-11eb-8008-092e00826574.png)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}```
```
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Something I just observed this morning is that when I install the chart with my `values.yaml` changes above, the drupal container retstarts 1 time before the site finishes initialization and becomes available.  If I deploy the chart using the default values, it doesn't restart during initialization.  When I look at the logs from the previous container instance (before the restart) I see a number of `setfacl` errors.

``` 
drupal 00:12:40.57 
drupal 00:12:40.57 Welcome to the Bitnami drupal container
drupal 00:12:40.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
drupal 00:12:40.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues
drupal 00:12:40.57 
drupal 00:12:40.58 INFO  ==> ** Starting Drupal setup **
drupal 00:12:40.60 INFO  ==> Configuring the HTTP port
drupal 00:12:40.61 INFO  ==> Configuring the HTTPS port
drupal 00:12:40.64 INFO  ==> Configuring PHP options
drupal 00:12:40.66 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 00:12:40.73 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
drupal 00:12:40.79 INFO  ==> Trying to connect to the database server
drupal 00:12:40.86 INFO  ==> Configuring file permissions for Drupal
drupal 00:12:40.87 INFO  ==> Installing Drupal site
drupal 00:13:33.13 INFO  ==> Flushing Drupal cache
drupal 00:13:49.52 INFO  ==> Persisting Drupal installation
setfacl: sites: Operation not permitted
setfacl: sites/README.txt: Operation not permitted
setfacl: sites/default: Operation not permitted
setfacl: sites/default/default.services.yml: Operation not permitted
setfacl: sites/default/default.settings.php: Operation not permitted
setfacl: sites/default/files: Operation not permitted
setfacl: sites/default/files/.htaccess: Operation not permitted
setfacl: sites/default/files/styles: Operation not permitted
setfacl: sites/default/files/config_K5r4ho9OPinoAXTvksblh3QBV9QQI2M2Ktc_GuHJCdvICZ__NpSOI6XRjLwrqUd3yrg0INhyeA: Operation not permitted
setfacl: sites/default/files/config_K5r4ho9OPinoAXTvksblh3QBV9QQI2M2Ktc_GuHJCdvICZ__NpSOI6XRjLwrqUd3yrg0INhyeA/sync: Operation not permitted
setfacl: sites/default/files/config_K5r4ho9OPinoAXTvksblh3QBV9QQI2M2Ktc_GuHJCdvICZ__NpSOI6XRjLwrqUd3yrg0INhyeA/sync/README.txt: Operation not permitted
setfacl: sites/default/files/config_K5r4ho9OPinoAXTvksblh3QBV9QQI2M2Ktc_GuHJCdvICZ__NpSOI6XRjLwrqUd3yrg0INhyeA/sync/.htaccess: Operation not permitted
setfacl: sites/default/settings.php: Operation not permitted
setfacl: sites/development.services.yml: Operation not permitted
setfacl: sites/example.sites.php: Operation not permitted
setfacl: sites/example.settings.local.php: Operation not permitted```
```

I also modified settings in `values.yaml` to externalize the database to use my `Azure Database for MariaDB` instead of deploying the mariadb image.  It works as expected and don't believe it's related to this issue, but just wanted to be fully transparent about my environment.

**Comment by rickrain** [comment]
UPDATE: I was able to fix the `setfacl` errors shown above by creating a new StorageClass with `UID: 1001` (per the note I found in the documentation), and then deriving my PV and PVC from this StorageClass.  However the original problem still exists with the site not rendering correctly.

**Comment by Mauraza** [comment]
Hi @rickrain,

now you fix the error with `setfacl`, could you share again the logs of drupal? Did you change something more apart from the persistence and the external database?

**Comment by rickrain** [comment]
Hi @Mauraza, here are the logs after I fixed the UID configuration on my StorageClass.  And no, other than externalizing the database, the only other changes to `values.yaml` are the changes I listed above.

```
drupal 19:40:45.15 
drupal 19:40:45.15 Welcome to the Bitnami drupal container
drupal 19:40:45.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
drupal 19:40:45.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues
drupal 19:40:45.16 
drupal 19:40:45.16 INFO  ==> ** Starting Drupal setup **
drupal 19:40:45.18 INFO  ==> Configuring the HTTP port
drupal 19:40:45.20 INFO  ==> Configuring the HTTPS port
drupal 19:40:45.22 INFO  ==> Configuring PHP options
drupal 19:40:45.23 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 19:40:45.35 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
drupal 19:40:45.41 INFO  ==> Trying to connect to the database server
drupal 19:40:45.59 INFO  ==> Configuring file permissions for Drupal
drupal 19:40:45.59 INFO  ==> Installing Drupal site
drupal 19:41:34.30 INFO  ==> Flushing Drupal cache
drupal 19:41:47.59 INFO  ==> Persisting Drupal installation
drupal 19:41:53.32 INFO  ==> ** Drupal setup finished! **

drupal 19:41:53.34 INFO  ==> ** Starting Apache **
[Wed Feb 10 19:41:53.398744 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 10 19:41:53.399296 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 10 19:41:53.433259 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 10 19:41:53.433773 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 10 19:41:53.461459 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.26 configured -- resuming normal operations
[Wed Feb 10 19:41:53.461509 2021] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
10.244.2.1 - - [10/Feb/2021:19:42:02 +0000] "GET /user/login HTTP/1.1" 200 2731
10.244.2.1 - - [10/Feb/2021:19:42:07 +0000] "GET /user/login HTTP/1.1" 200 2733
10.244.2.1 - - [10/Feb/2021:19:41:57 +0000] "GET /user/login HTTP/1.1" 200 2726
10.244.2.1 - - [10/Feb/2021:19:42:12 +0000] "GET /user/login HTTP/1.1" 200 2733
```

**Comment by javsalgar** [comment]
Hi,

This is very strange. I don't see a reason for working over HTTPS and not over HTTP because of the filesystem. Could it be that you had resources cached in your browser and that's why you see it in HTTPS and not HTTP. My intuition tells me that it should fail in both HTTP and HTTPS if it's because of the filesystem.

**Comment by rickrain** [comment]
Hi @javsalgar, I cleared my browser cache.  Even tried new in-private browser sessions.  It didn't change anything.

**Comment by Mauraza** [comment]
Hi @rickrain,

did you change something in the configuration of Drupal? I found this thread https://groups.drupal.org/node/194543, could you check it?

**Comment by rickrain** [comment]
Hi @Mauraza, no changes to Drupal.  I'm going to redeploy to a new/clean cluster to see if that helps.  I'll report back here afterwards.  Thanks for your help.

**Comment by Mauraza** [comment]
Hi @rickrain, I hope this try works.

**Comment by Mauraza** [comment]
Hi @rickrain,

could you run this command in site the pod of drupal `ls -la /opt/bitnami/drupal/sites/default/files/css/`?
the output should be:
```bash
$ ls -la /opt/bitnami/drupal/sites/default/files/css/
total 116
drwxrwxr-x 2 1001 root  4096 Mar 10 10:48 .
drwxrwxr-x 6 1001 root  4096 Mar 10 10:47 ..
-rw-rw-r-- 1 1001 root 53993 Mar 10 10:47 css_3V6J_r_PTht_o1AwEAK5H1GPwWEaEBu0a2228ToEXnc.css
-rw-rw-r-- 1 1001 root 10306 Mar 10 10:47 css_3V6J_r_PTht_o1AwEAK5H1GPwWEaEBu0a2228ToEXnc.css.gz
-rw-rw-r-- 1 1001 root   509 Mar 10 10:47 css_Z5jMg7P_bjcW9iUzujI7oaechMyxQTUqZhHJ_aYSq04.css
-rw-rw-r-- 1 1001 root   274 Mar 10 10:47 css_Z5jMg7P_bjcW9iUzujI7oaechMyxQTUqZhHJ_aYSq04.css.gz
-rw-rw-r-- 1 1001 root  8754 Mar 10 10:47 css_ae7UPIbd_IVJyK4q6Bo1deBGLSQmYVfqayVz97QzYwU.css
-rw-rw-r-- 1 1001 root  2548 Mar 10 10:47 css_ae7UPIbd_IVJyK4q6Bo1deBGLSQmYVfqayVz97QzYwU.css.gz
-rw-rw-r-- 1 1001 root  9029 Mar 10 10:48 css_v18WUm75dSk_A-DeLZcRjivGVxxUXl9PCwLE_JJpyIk.css
-rw-rw-r-- 1 1001 root  2610 Mar 10 10:48 css_v18WUm75dSk_A-DeLZcRjivGVxxUXl9PCwLE_JJpyIk.css.gz
```

**Comment by rickrain** [comment]
Here you go @Mauraza,

```bash
ls -la /opt/bitnami/drupal/sites/default/files/css  
total 88
drwxrwxrwx 2 1001 1001     0 Mar 10 17:04 .
drwxrwxrwx 2 1001 1001     0 Mar 10 17:03 ..
-rwxrwxrwx 1 1001 1001 53993 Mar 10 17:04 css_3V6J_r_PTht_o1AwEAK5H1GPwWEaEBu0a2228ToEXnc.css
-rwxrwxrwx 1 1001 1001 10306 Mar 10 17:04 css_3V6J_r_PTht_o1AwEAK5H1GPwWEaEBu0a2228ToEXnc.css.gz
-rwxrwxrwx 1 1001 1001   509 Mar 10 17:04 css_Z5jMg7P_bjcW9iUzujI7oaechMyxQTUqZhHJ_aYSq04.css
-rwxrwxrwx 1 1001 1001   274 Mar 10 17:04 css_Z5jMg7P_bjcW9iUzujI7oaechMyxQTUqZhHJ_aYSq04.css.gz
-rwxrwxrwx 1 1001 1001  8754 Mar 10 17:04 css_ae7UPIbd_IVJyK4q6Bo1deBGLSQmYVfqayVz97QzYwU.css
-rwxrwxrwx 1 1001 1001  2548 Mar 10 17:04 css_ae7UPIbd_IVJyK4q6Bo1deBGLSQmYVfqayVz97QzYwU.css.gz
-rwxrwxrwx 1 1001 1001  9029 Mar 10 17:04 css_v18WUm75dSk_A-DeLZcRjivGVxxUXl9PCwLE_JJpyIk.css
-rwxrwxrwx 1 1001 1001  2610 Mar 10 17:04 css_v18WUm75dSk_A-DeLZcRjivGVxxUXl9PCwLE_JJpyIk.css.gz
I have no name!@drupal-release-9dd798698-ldxv4:/$ 
```

**Comment by rickrain** [comment]
@Mauraza, something else I should mention is that when I deploy this as described [here](https://github.com/bitnami/charts/issues/5450#issuecomment-794048064), the SSL certificate is not valid.  I have to give an exception in my browser for it to work and the certificate is for `example.com`.  This happens _only_ if I deploy without using a PVC SMB File Share.  If you want to look for yourself, I have this running in Azure now, which you can access at https://20.42.26.33/.

**Comment by Mauraza** [comment]
Hi @rickrain,

In your deployment, I found this 
![image](https://user-images.githubusercontent.com/17168510/110760738-4d8c4e00-824f-11eb-95e0-53e1cd39c35e.png)

Appears this errors:
```
20.42.26.33/:14 Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "http://20.42.26.33/sites/default/files/css/css_v18WUm75dSk_A-DeLZcRjivGVxxUXl9PCwLE_JJpyIk.css".
20.42.26.33/:15 Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "http://20.42.26.33/sites/default/files/css/css_3V6J_r_PTht_o1AwEAK5H1GPwWEaEBu0a2228ToEXnc.css".
20.42.26.33/:16 Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "http://20.42.26.33/sites/default/files/css/css_Z5jMg7P_bjcW9iUzujI7oaechMyxQTUqZhHJ_aYSq04.css".
```

And I found this old issue https://www.drupal.org/project/jstools/issues/72561, could you check it?
the other thing you can try is to change this parameter `gid=1001` to `gid=root` to try to have the same output of `ls -la /opt/bitnami/drupal/sites/default/files/css`

**Comment by rickrain** [comment]
Still has the same results.

**Comment by Mauraza** [comment]
Hi @rickrain,

Could you try to change the `file_mode=0664`and `dir_mode=0775`?

**Comment by rickrain** [comment]
Hi @Mauraza, I already did.  I did when I tried the other idea above.  Forgot to mention it.  But, still got the same result.

**Comment by Mauraza** [comment]
Hi @rickrain,

Did you try with these `mountOptions`?
```
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
```

**Comment by rickrain** [comment]
Hi @Mauraza, unfortunately, same result.

**Comment by Mauraza** [comment]
Hi @rickrain,

Did you try [this](https://www.drupal.org/forum/support/installing-drupal/2015-12-31/drupal-801-no-css-displaying-after-install)?
```
drush -y config-set system.performance css.preprocess 0 
drush -y config-set system.performance js.preprocess 0
```
