### ISSUE TITLE
[bitnami/kafka] log4j configuration syntax - 12.7.5

### ISSUE THREAD

**Issue by syepes** [bitnami/charts#5452]
Hello,

I have been tying to change some of the default log4j config values, but I have not managed to find out what is the exact syntax.  #4181
I am getting the following error:

`Error: template: kafka/templates/log4j-configmap.yaml:15:8: executing "kafka/templates/log4j-configmap.yaml" at <include "kafka.tplValue" (dict "value" .Values.log4j "context" $)>: error calling include: template: no template "kafka.tplValue" associated with template "gotpl"
` 

I have tried the following:

1)
```
log4j:
  - name: log4j.rootLogger
    value: "WARN, stdout, kafkaAppender"
```

2)
```
log4j:
  - log4j.rootLogger=WARN, stdout, kafkaAppender
```

3)
```
log4j: |
  log4j.rootLogger=WARN, stdout, kafkaAppender
```

4)
```
log4j:
  log4j.rootLogger: "WARN, stdout, kafkaAppender"
```

Could someone please help me figure out what would be the correct way.

**Comment by javsalgar** [comment]
Hi,

Thank you for reporting. I will work on fixing it. I will update this ticket as soon as we have more news.

**Comment by javsalgar** [comment]
Hi, I created a PR fixing the tplValues issue
