### ISSUE TITLE
[postgresql-ha] additional node will not come online (live/readiness probe too aggressive?)

### ISSUE THREAD

**Issue by TJM** [bitnami/charts#5453]
**Which chart**: 
postgresql-ha 6.5.0

**Describe the bug**
We had a problem which caused the second node to restart, but now it will not restart, it is stuck in a CrashBackoff, we think because it is taking too long to replicate the data from the primary.

```
k logs artifactr-hadb-postgresql-ha-postgresql-1 postgresql --previous
postgresql-repmgr 18:35:11.11 
postgresql-repmgr 18:35:11.11 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 18:35:11.11 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 18:35:11.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 18:35:11.12 
postgresql-repmgr 18:35:11.15 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 18:35:11.17 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 18:35:11.18 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 18:35:11.19 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 18:35:11.28 INFO  ==> Auto-detected primary node: 'artifactr-hadb-postgresql-ha-postgresql-0.artifactr-hadb-postgresql-ha-postgresql-headless.artifactory.svc.cluster.local:5432'
postgresql-repmgr 18:35:11.29 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 18:35:11.29 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 18:35:11.44 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 18:35:11.44 INFO  ==> Initializing Repmgr...
postgresql-repmgr 18:35:11.45 INFO  ==> Waiting for primary node...
postgresql-repmgr 18:35:11.51 INFO  ==> Cloning data from primary node...
```
... it just stops there every time, no further information.

**To Reproduce**

1. Install postgresql-ha chart (with 2 replicas)
2. Add some data (ours is ~42GB on disk)
3. scale down to one replica
4. DELETE PVC (to ensure it will have to sync) -- this is in lieu of having extremely dynamic data in the database
5. scale up to two replicas

**Expected behavior**

1. There should be *some* output indicating what it is doing: is it failing to connect to the primary? Did it connecting to the primary and retrieving data? progress?
2. It should be allowed to finish its operation before being killed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-gke.6600", GitCommit:"cfb955f37f5546d5bf811091337d2025e2a79267", GitTreeState:"clean", BuildDate:"2020-09-17T09:21:09Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**
Add any other context about the problem here.

**Comment by juan131** [comment]
Hi @TJM 

> ... we think because it is taking too long to replicate the data from the primary.

Correct! It looks like that. You can play with the readinessProbes/livenessProbes default values so you give the new replicas more time to clone the data before they're restarted, see:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L294

In [this issue](https://github.com/bitnami/charts/issues/4894) we are discussing about possible alternatives such as using init containers for cloning the data, so we avoid this behaviour when working with large database. Let's continue the conversation there.
