### ISSUE TITLE
Keycloak chart notes contains invalid information 

### ISSUE THREAD

**Issue by kaspernielsen** [bitnami/charts#5464]
**Which chart**:
Bitnami/Keycloak 2.0.0

**Describe the bug**
When deploy keycloak chart. The notes contain

3. Access the Administration Console using the following credentials:
  echo Username: user
  echo Password: $(kubectl get secret --namespace nnnt keycloak-env-vars -o jsonpath="{.data.admin-password}" | base64 --decode)"

When calling this command you get

Error from server (NotFound): secrets "keycloak-env-vars" not found

**To Reproduce**
Install the bitnami wildfly chart and read the notes

**Expected behavior**
Expected a valid command to execute. This has worked in previous versions.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Thanks for reporting the issue, I just created the above PR fixing it
