### ISSUE TITLE
Configurable metrics container port and metrics service port name in MongoDB chart

### ISSUE THREAD

**Issue by fam0x** [bitnami/charts#5469]
**Which chart**:
MongoDB (also Zookeeper)

**Is your feature request related to a problem? Please describe.**
Yes. I need to be able to modify the container port for metrics service and the port name for the metrics service.

**Describe the solution you'd like**
In zookeeper chart we can set values like "metrics.containerPort". Require the same configuration in mongodb.
Also require a "metrics.service.port.name" in both zookeeper and mongodb

**Describe alternatives you've considered**

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input. We will work on adding this feature. We cannot guarantee an ETA as it is not a critical feature. However, if you want to speed up the process, feel free to submit a PR and we will review it. Could you explain in more detail your use case, by the way?

**Comment by javsalgar** [comment]
Hi,

I just added the feature in both charts. Please let us know if you find any issue

**Comment by fam0x** [comment]
Thanks a lot for adding this feature. It has been really helpful!!
