### ISSUE TITLE
[bitnami/mysql] helm chart nodeSelector on either primary or secondary doesn't seem to work.

### ISSUE THREAD

**Issue by liquidtoon01** [bitnami/charts#5479]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**

**To Reproduce**

Run the values.yaml file with a change to the nodeSelector variable and deploy. Alternatively add --set secondary.nodeSelector.{SELECTIONCRITERIA} to your helm install

**Expected behavior**
helm install with custom nodeSelector parameters should deploy pods to stated nodes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
doing a helm template to see the yaml files doesn't produce any instance of nodeSelector.

**Comment by migruiz4** [comment]
Hi @liquidtoon01 ,

Could you please share more details about your issue?

Any error message or a more detailed example of your `helm install` command would be helpful.

In my case, I tried to reproduce the issue using the following command and both `helm template` and `helm install` were executed successfully:
```
> helm template test-mysql bitnami/mysql --set architecture=replication --set secondary.nodeSelector."kubernetes\.io/role"=node | grep nodeSelector -A4
      nodeSelector:
        kubernetes.io/role: node
      securityContext:
        fsGroup: 1001
      containers:

------------

> helm install miruiz-mysql bitnami/mysql --set architecture=replication --set secondary.nodeSelector."kubernetes\.io/role"=node
...
> kubectl describe pod test-mysql-secondary-0 | grep Node-Selectors
Node-Selectors:  kubernetes.io/role=node
```

**Comment by liquidtoon01** [comment]
Hi @migruiz4 I'm trying to have this all in the values.yaml file, when I add the nodeSelector like this it doesn't seem to work;

```
nodeSelector:
    beta.kubernetes.io/os: linux
    agentpool: golinuxz
```

**Comment by liquidtoon01** [comment]
Looks like I've got it working, I think it may have been an indentation issue. Thanks!

**Comment by migruiz4** [comment]
Hi @liquidtoon01 ,

I'm glad the issue is now resolved, if you need any further help don't hesitate to let us know.
