### ISSUE TITLE
Keycloak admin console login fails

### ISSUE THREAD

**Issue by tampler** [bitnami/charts#5488]
**Which chart**:
Keycloak chart 2.0.0 

**Describe the bug**
I'm able to reach the admin console, but login fails due to invalid credentials:

`
09:46:35,274 WARN  [org.keycloak.events] (default task-3) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=1c956109-eede-4342-9842-195792332a71, ipAddress=***, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://name/auth/admin/master/console/, code_id=81e843d1-2f01-45dd-9241-4102d19c3523, username=user, authSessionParentId=81e843d1-2f01-45dd-9241-4102d19c3523, authSessionTabId=Y3B1gsEi9N0
`

I'm sure that this is a Bitnami config bug, since I'm able to deploy a standalone docker container for `Keycloak` and it works

**To Reproduce**
1. Use the following config:
`  
    helm install --namespace ${ns} ${app} bitnami/keycloak \
  --set proxyAddressForwarding=true \
  --set service.type=ClusterIP \
  --set image.debug=true \
  --set auth.adminPassword=abc \
  --set postgresql.enabled=false \
  --set externalDatabase.host=pg-postgresql.postgres.svc.cluster.local \
  --set externalDatabase.port=5432 \
  --set externalDatabase.user=bku \
  --set externalDatabase.password=gggggggggggggg \
  --set externalDatabase.database=accounts \

`
2. Validate deployment:
```
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
keycloak            ClusterIP   10.98.205.248    <none>        80/TCP,443/TCP   34m
keycloak-headless   ClusterIP   None             <none>        80/TCP           34m
```

3. Validate installed pass for `user`:
```
echo Password: $(kubectl get secret --namespace ns0 keycloak -o jsonpath="{.data.ad[55/722]
word}" | base64 --decode)                                                                                                                             
Password: abc          
```

4. Go to browser with: `https://comany.name/auth/`, navigate to admin login page and enter credentials
5. Get an error `invalid credentials`
6. Validate `kycloak` logs with: kubectl  -n ns0 logs keycloak-0 and see the following:
`
09:46:35,274 WARN  [org.keycloak.events] (default task-3) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=1c956109-eede-4342-9842-195792332a71, ipAddress=***, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://name/auth/admin/master/console/, code_id=81e843d1-2f01-45dd-9241-4102d19c3523, username=user, authSessionParentId=81e843d1-2f01-45dd-9241-4102d19c3523, authSessionTabId=Y3B1gsEi9N0
`

**Expected behavior**
Login succeeds for `user` with a preset password

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.5.2+g167aac7
```

- Output of `kubectl version`:

```
Client Version: v1.20.2
Server Version: v1.20.2
```

**Additional context**

**Comment by Mauraza** [comment]
Hi @tampler,

it seems is related to the configuration of Keycloak, could you check this documentation https://www.keycloak.org/docs/latest/server_installation/#verify-configuration?

**Comment by tampler** [comment]
Hi, Mauraza 

Thanks for your reply. I tried that Keycloak test, but have no idea how it could be helpful. For reference, you can check the test results [here](https://drive.google.com/file/d/1HsNz3T-i5VTU8Q_uzK6iJb7joPdaceN0/view)

Any more ideas? 
Thanks !

**Comment by Mauraza** [comment]
Hi @tampler, 

did you try to create a topic in https://keycloak.discourse.group/? I think that the question is related to the application itself

**Comment by deefdragon** [comment]
I am also having trouble logging in with the bitnami chart when there is more than 1 replica. I get `login attempt has timed out` when logging in, but also another error sometimes.

**Comment by Mauraza** [comment]
Hi @deefdragon,

It seems is not the same problem, could you open a new issue with all the information about your trouble? Thanks

**Comment by arjo-xfa** [comment]
Hi,

I think I have the same issue, login failed

Do you have received any answer ?

Xavier

**Comment by Mauraza** [comment]
Hi @arjo-xfa,

Could you add more information about your issue? you could add the logs

**Comment by arjo-xfa** [comment]
Hi @Mauraza  ,

I install keycloak with the following command :
`helm install --namespace test-admin my-release bitnami/keycloak`

When I try to connect to the interface, I have an login error
![Capture](https://user-images.githubusercontent.com/75482681/110113763-dcaee700-7db3-11eb-8264-143dc9894bae.JPG)

I get the password with the following command :
```
kubectl get secret --namespace test-admin my-release-keycloak -o jsonpath="{.data.admin-password}" | base64 --decode
And this is the default user
```

There is log for pod **my-release-keycloak-0**  (I remove IP address in this log)

`12:07:23,022 WARN  [org.keycloak.events] (default task-1) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=8cab6191-434a-47e6-b8a6-136148398b80, ipAddress=..., error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=http://..../auth/admin/master/console/, code_id=da2504c3-1f99-4088-9703-eed728abcd2d, username=user, authSessionParentId=da2504c3-1f99-4088-9703-eed728abcd2d, authSessionTabId=f4brcGeFJzQ`


Regards

Xavier

**Comment by Mauraza** [comment]
Hi @arjo-xfa,

I wasn't able to reproduce the issue. There is another WAR in the logs?

**Comment by emrekgn** [comment]
Hi, 

I'm also having the same issue. Here is my configuration:

* Custom `values.yml` :

```
replicaCount: 2
serviceDiscovery:
  enabled: true
postgresql:
  enabled: false
networkPolicy:
  enabled: true
externalDatabase: 
  host: postgres-release-postgresql-ha-pgpool.default.svc.cluster.local
  port: 5432
  user: "keycloak"
  password: "secret"
  database: "keycloak_db"
proxyAddressForwarding: true
auth:
  createAdminUser: true
  adminUser: "keycloak"
  existingSecret:
    name: "keycloak-secret"
ingress:
  enabled: true
```

* `keycloak-secret.yml` :

```
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  # base64 encoded value of 'secret'
  admin-password: c2VjcmV0Cg==
  management-password: c2VjcmV0Cg==
  database-password: c2VjcmV0Cg==
```

Running `helm install -f values.yml keycloak-release bitnami/keycloak` starts up two keycloak nodes using the external database but during login (username: keycloak, password: secret) I get the same error.

Here is the Keycloak log:

```
16:38:47,899 WARN  [org.keycloak.events] (default task-5) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=c4cecb10-2e6e-4d99-9c36-b20383e677b4, ipAddress=192.168.49.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=http://keycloak.local/auth/admin/master/console/, code_id=51f3fa8d-0acd-4b48-b2b5-a001094d5132, username=keycloak, authSessionParentId=51f3fa8d-0acd-4b48-b2b5-a001094d5132, authSessionTabId=skffpeYAbFw
```

But I can confirm Keycloak created necessary db tables and records:

* Confirmation that keycloak initialized db schema:

```
kubectl exec -it postgres-release-postgresql-ha-postgresql-0 bash
I have no name!@postgres-release-postgresql-ha-postgresql-0:/$ psql -h localhost -p 5432 -d keycloak_db -U keycloak -p secret
keycloak_db=# select table_name from information_schema.tables where table_schema='public';
```

* Confirmation that *keycloak* user created:
```
keycloak_db=# select id, realm_id, enabled from user_entity where username = 'keycloak';
                  id                  | realm_id | enabled 
--------------------------------------+----------+---------
 c4cecb10-2e6e-4d99-9c36-b20383e677b4 | master   | t
(1 row)

keycloak_db=# select credential_data, secret_data from credential where user_id = 'c4cecb10-2e6e-4d99-9c36-b20383e677b4';
                                 credential_data                                 |                                                          
                 secret_data                                                                            
---------------------------------------------------------------------------------+----------------------------------------------------------
--------------------------------------------------------------------------------------------------------
 {"hashIterations":100000,"algorithm":"pbkdf2-sha256","additionalParameters":{}} | {"value":"5ZQlOWY8rXwc/Xv7wTDogcSG0lE27Ux4awvtJgJT+l1MgB4
DIyZp46f1/f0JRNu2k7M4Qru29BpGtzkWgE1thw==","salt":"Hk/GUtKCTnX+Wk7++e5dSQ==","additionalParameters":{}}
(1 row)
```

Regarding the issue, I'm not %100 sure but I have a guess:

According to the last query, Keycloak uses *pbkdf2-sha256* with 100k number of iterations and a salt.
If I use these parameters and generate the encoded secret value from plaint text "secret" (that is the `admin-password` from *keycloak-secret*), I get a different result than the secret_data value. 

So is it possible that bitnami chart does not use provided `admin-password` at all, and randomly auto-generates some password? 

Thanks.

**Comment by Mauraza** [comment]
Hi @emrekgn,

could you add the `describe` of the `statefulsets` of keycloak?

**Comment by emrekgn** [comment]
Hi @Mauraza,

Here is the `describe` of the `statefulsets` of keycloak:

```
Name:               keycloak-release
Namespace:          default
CreationTimestamp:  Wed, 17 Mar 2021 16:02:07 +0300
Selector:           app.kubernetes.io/component=keycloak,app.kubernetes.io/instance=keycloak-release,app.kubernetes.io/name=keycloak
Labels:             app.kubernetes.io/component=keycloak
                    app.kubernetes.io/instance=keycloak-release
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=keycloak
                    helm.sh/chart=keycloak-2.3.0
Annotations:        meta.helm.sh/release-name: keycloak-release
                    meta.helm.sh/release-namespace: default
Replicas:           2 desired | 2 total
Update Strategy:    RollingUpdate
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/component=keycloak
                    app.kubernetes.io/instance=keycloak-release
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=keycloak
                    helm.sh/chart=keycloak-2.3.0
  Annotations:      checksum/configmap-env-vars: 467e3c28d9454fb698c468f4763131d2d7e3f47b57952143e76bc1588e08db31
  Service Account:  keycloak-release
  Containers:
   keycloak:
    Image:       repo.internal.ouva.co/repository/docker-hosted/ouva-keycloak:latest
    Ports:       8080/TCP, 8443/TCP, 9990/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Liveness:    http-get http://:http/auth/ delay=300s timeout=5s period=1s #success=1 #failure=3
    Readiness:   http-get http://:http/auth/realms/master delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      keycloak-release-env-vars  ConfigMap  Optional: false
    Environment:
      KUBERNETES_NAMESPACE:           (v1:metadata.namespace)
      BITNAMI_DEBUG:                 true
      KEYCLOAK_ADMIN_PASSWORD:       <set to the key 'admin-password' in secret 'keycloak-secret'>       Optional: false
      KEYCLOAK_MANAGEMENT_PASSWORD:  <set to the key 'management-password' in secret 'keycloak-secret'>  Optional: false
      KEYCLOAK_DATABASE_PASSWORD:    <set to the key 'database-password' in secret 'keycloak-secret'>    Optional: false
      KEYCLOAK_EXTRA_ARGS:           -Dkeycloak.frontendUrl=http://keycloak.local/auth
    Mounts:                          <none>
  Volumes:                           <none>
Volume Claims:                       <none>
Events:
  Type    Reason            Age    From                    Message
  ----    ------            ----   ----                    -------
  Normal  SuccessfulCreate  4m17s  statefulset-controller  create Pod keycloak-release-0 in StatefulSet keycloak-release successful
  Normal  SuccessfulCreate  4m17s  statefulset-controller  create Pod keycloak-release-1 in StatefulSet keycloak-release successful
```

It looks like environment variables are correctly set.

(I forgot to mention previously but of course I've also uninstalled postgres chart and deleted any related `PVC`s, so this is a clean installation of postgres and keycloak charts)

**Comment by emrekgn** [comment]
Nope, I've tried another clean installation, this time using *bitnami/keycloak:latest* image but still cannot log into the admin console.

Here is the `describe` of the `statefulsets`:
```
Name:               keycloak-release
Namespace:          default
CreationTimestamp:  Wed, 17 Mar 2021 16:42:13 +0300
Selector:           app.kubernetes.io/component=keycloak,app.kubernetes.io/instance=keycloak-release,app.kubernetes.io/name=keycloak
Labels:             app.kubernetes.io/component=keycloak
                    app.kubernetes.io/instance=keycloak-release
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=keycloak
                    helm.sh/chart=keycloak-2.3.0
Annotations:        meta.helm.sh/release-name: keycloak-release
                    meta.helm.sh/release-namespace: default
Replicas:           2 desired | 2 total
Update Strategy:    RollingUpdate
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/component=keycloak
                    app.kubernetes.io/instance=keycloak-release
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=keycloak
                    helm.sh/chart=keycloak-2.3.0
  Annotations:      checksum/configmap-env-vars: 467e3c28d9454fb698c468f4763131d2d7e3f47b57952143e76bc1588e08db31
  Service Account:  keycloak-release
  Containers:
   keycloak:
    Image:       docker.io/bitnami/keycloak:latest
    Ports:       8080/TCP, 8443/TCP, 9990/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Liveness:    http-get http://:http/auth/ delay=300s timeout=5s period=1s #success=1 #failure=3
    Readiness:   http-get http://:http/auth/realms/master delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      keycloak-release-env-vars  ConfigMap  Optional: false
    Environment:
      KUBERNETES_NAMESPACE:           (v1:metadata.namespace)
      BITNAMI_DEBUG:                 true
      KEYCLOAK_ADMIN_PASSWORD:       <set to the key 'admin-password' in secret 'keycloak-secret'>       Optional: false
      KEYCLOAK_MANAGEMENT_PASSWORD:  <set to the key 'management-password' in secret 'keycloak-secret'>  Optional: false
      KEYCLOAK_DATABASE_PASSWORD:    <set to the key 'database-password' in secret 'keycloak-secret'>    Optional: false
      KEYCLOAK_EXTRA_ARGS:           -Dkeycloak.frontendUrl=http://keycloak.local/auth
    Mounts:                          <none>
  Volumes:                           <none>
Volume Claims:                       <none>
Events:
  Type    Reason            Age    From                    Message
  ----    ------            ----   ----                    -------
  Normal  SuccessfulCreate  9m20s  statefulset-controller  create Pod keycloak-release-0 in StatefulSet keycloak-release successful
  Normal  SuccessfulCreate  9m20s  statefulset-controller  create Pod keycloak-release-1 in StatefulSet keycloak-release successful
```

**Comment by Mauraza** [comment]
Hi @emrekgn, 

could you try to add another user and try to login with this new user?
```
kubectl exec -ti keycloak-0 -- bash
```
in the pod
```
cd /opt/bitnami/keycloak/
./bin/add-user-keycloak.sh --user YourUser --password YourNewPass --realm YourRealm
```

**Comment by emrekgn** [comment]
Hi @Mauraza ,

Sure. I've added user `test`:

```
I have no name!@keycloak-release-0:/opt/bitnami/keycloak$ ./bin/add-user-keycloak.sh --user test --password testpwd --realm master
Added 'test' to '/opt/bitnami/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
```

Currently, it did not create the user. I guess it'll be done during server restart?
But how can I safely restart the server as indicated in the log? If I kill the process by its *pid*, the pod just gets restarted.

Contents of the `keycloak-add-user.json` file:
```
[ {
  "realm" : "master",
  "users" : [ {
    "username" : "test",
    "enabled" : true,
    "credentials" : [ {
      "type" : "password",
      "secretData" : "{\"value\":\"IgjqU6FJdxIUBSFH34o6Qosx2zJLIlo8jUYg6qgwdOBzf040G9oyXIIbKQg4G0H3alRQ4f8gMQZ0DyJvM0dlVQ==\",\"salt\":\"SJu9aCd7iVxr5YAkiQL9BA==\",\"additionalParameters\":{}}",
      "credentialData" : "{\"hashIterations\":100000,\"algorithm\":\"pbkdf2-sha256\",\"additionalParameters\":{}}"
    } ],
    "realmRoles" : [ "admin" ]
  } ]
} ]
```


BTW, I just implemented another script to cross-check these `secretData.value`s in the generated JSON files. 
I can confirm the generated `secretData.value` for user `test` like this and the results match:

```
$ python3 encode_pwd.py testpwd SJu9aCd7iVxr5YAkiQL9BA==
$ Encoded pwd: IgjqU6FJdxIUBSFH34o6Qosx2zJLIlo8jUYg6qgwdOBzf040G9oyXIIbKQg4G0H3alRQ4f8gMQZ0DyJvM0dlVQ==
```

But, if I check the initial JSON file of the user `keycloak` during pod startup:

```
[ {
  "realm" : "master",
  "users" : [ {
    "username" : "keycloak",
    "enabled" : true,
    "credentials" : [ {
      "type" : "password",
      "secretData" : "{\"value\":\"q981To1e99EtkMSd/r7oBTCdMnWu3dEZBVqIWZsW4lSzUX55TxB9EQYkaa2UKAt4N+DSvYhyRo+m8QOqT+U9mg==\",\"salt\":\"ZdrrSJNzeYdBVy/979HEnQ==\",\"additionalParameters\":{}}",
      "credentialData" : "{\"hashIterations\":100000,\"algorithm\":\"pbkdf2-sha256\",\"additionalParameters\":{}}"
    } ],
    "realmRoles" : [ "admin" ]
  } ]
} ]
```

The results do not match:
```
$ python3 encode_pwd.py secret ZdrrSJNzeYdBVy/979HEnQ==
$ Encoded pwd: fH4A/FcK7+uLA/haInU9OasFPFoKZZ1DqSzJ1kPw5Shp1uqCgFCHGgIYkie7BiLBT9+rTKKpLRvfzXICll4oSg==
```

And when I update `secretData.value` of user `keycloak` with the value above (`fH4A/FcK7+uLA/haInU9OasFPFoKZZ1DqSzJ1kPw5Shp1uqCgFCHGgIYkie7BiLBT9+rTKKpLRvfzXICll4oSg==`) in database, I can login successfully.

Here is my script to generate encoded password and to cross-check results:

```
#!/usr/bin/python

import hashlib
import argparse
import base64
import logging


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("password", help="plain text password string to encode")
    parser.add_argument("salt", help="base64 encoded salt string")
    parser.add_argument("-r", "--rounds", type=int, default=100000, help="number of rounds")
    parser.add_argument("-k", "--key_size", type=int, default=64, help="key size in bytes")
    return parser.parse_args()


def main():
    args = get_args()
    logging.basicConfig(
        format="%(asctime)s - %(module)s.%(funcName)s - %(levelname)s - %(message)s",
        level=getattr(logging, "INFO", None)
    )
    logging.info(f"Starting with params: {args}")

    salt_decoded = base64.b64decode(args.salt.encode())
    dk = hashlib.pbkdf2_hmac('sha256', args.password.encode(), salt_decoded, iterations=args.rounds, dklen=args.key_size)
    result = base64.b64encode(dk).decode()
    logging.info(f"Encoded pwd: {result}")


if __name__ == "__main__":
    main()


```

Is it somehow because of using `secret` as the password? Or is it related to environment variables?

**Comment by emrekgn** [comment]
I finally figured out what's going on, it is the encoded `secret` which has a newline character at the end. That's why `add-user-keycloak.sh` does not work during startup but works afterward when manually called.
Well, this was embarrassing for me :sweat_smile: 

I'm just posting this for reference. To encode a password, this should be used: `echo -n secret | base64 -w 0` instead of `echo secret | base64`. 
Here is more info [why it contains ending characters](https://superuser.com/a/1225139)

@Mauraza Thank you so much for your help!

**Comment by Mauraza** [comment]
Hi @emrekgn,

I'm glad you found the issue!!

**Comment by deepanjan90** [comment]
@emrekgn I am facing the same issue as you were (unable to login with the default user/password)

Did adding the user via the `add-user-keycloak.sh` finally work for you ? And also how were you able to safely restart the server ?

**Comment by arjo-xfa** [comment]
Hello,

One of my colleague test on his side. For me, the problem was if you launch 2 times helm install, the chart generate 1 password for the first time and it store in database.
When you launch the second time the chart, chart generate a second password, but the password store in db is the first.
If I use the first password, it's ok.

Regards

Xavier

**Comment by deepanjan90** [comment]
@arjo-xfa 
I did a `helm delete` before doing an another `helm install`. So the postgresql definitely is fresh. Unless helm is saving thepasword somewhere else. The data base that you are referring to, is it something else ?

**Comment by Mauraza** [comment]
Hi @arjo-xfa and @deepanjan90,

when you did a `helm delete` remember that the `persistent volume claim` is not deleted, you need to delete manually.
You can check it after you did a `helm delete`, run this command `kubectl get pvc`

**Comment by deepanjan90** [comment]
@Mauraza that worked, when I cleaned the pvc as well and did a fresh install.

Thanks for the help

**Comment by jmicans** [comment]
Thanks, this was useful thread.
I had the same issue but for different reasons. My previous kubernetes stack with a keycloak instance was broken and reinstalled, but installing keycloak with `helm install` with new admin password did not update admin user settings in keycloak db, even if username and password was specified in helm values. 
Since the previous password was lost, I was able to encode the new password using the ` add-user-keycloak.sh` script and then do manual update to `credential` table in keycloak db. After the update and pod restart it was possible to log in to keycloak admin console.

**Comment by QuiTran86** [comment]
I also faced this issue in testing, the reason is when you uninstall keycloak chart, the persistent volume is still be there and the old password of the uninstalled chart still exist, it causes conflict when you try to re-install the chart. For testing purpose, just try to delete the pv and pvc before reinstalling the chart can overcome the problem.
