### ISSUE TITLE
[Bitnami/Airflow] infinite redirect loop on web UI

### ISSUE THREAD

**Issue by Yinabled** [bitnami/charts#5492]
**Which chart**:
bitnami/airflow 8.0.4

**Describe the bug**
The Airflow chart was installed onto our cluster without any additional configuration. Accessing the web UI (via `bitnami-airflow:8080`) results in an infinite redirect loop between the `/` and `/home` paths.

**To Reproduce**
1. Install the Airflow chart in your cluster, without any additional configuration beyond the base config. (We use Terraform, so this was configured as a `helm_release` resource.)
2. (Configure ingress - this doesn't seem related to the issue, but including regardless. We use Envoy, so we exposed `bitnami-airflow:8080` via a subdomain.)
3. Access the web UI via the exposed subdomain. Observe an infinite redirect loop (`ERR_TOO_MANY_REDIRECTS`), which looks to be redirecting the user between `/` and `/home`.

**Expected behavior**
The loaded web UI.

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.6000", GitCommit:"b02f5ea6726390a4b19d06fa9022981750af2bbc", GitTreeState:"clean", BuildDate:"2020-11-18T09:16:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresbono** [comment]
Hi @Yinabled, can you share the specific values that you are using to deploy the chart? In addition to that, can you do queries to the different services and endpoints to see where the redirection loop is happening?

- Endpoint
- Service
- Ingress

To obtain the endpoint and service IPs you can execute:

```console
$ kubectl get endpoints,services
NAME                                    ENDPOINTS          AGE
endpoints/airflow                       10.244.2.3:8080    4m7s

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/airflow                       ClusterIP   10.96.20.207    <none>        8080/TCP   4m7s
```

Then, you can exec into the airflow web container and do the queries:

```console
$ kubectl exec -it airflow-web-7568b77f9b-66z2n -- curl -LI 10.244.2.3:8080
HTTP/1.1 302 FOUND
Location: http://10.244.2.3:8080/home

HTTP/1.1 302 FOUND
Location: http://10.244.2.3:8080/login/?next=http%3A%2F%2F10.244.2.3%3A8080%2Fhome

HTTP/1.1 200 OK

$ kubectl exec -it airflow-web-7568b77f9b-66z2n -- curl -LI 10.96.20.207:8080
HTTP/1.1 302 FOUND
Location: http://10.96.20.207:8080/home

HTTP/1.1 302 FOUND
Location: http://10.96.20.207:8080/login/?next=http%3A%2F%2F10.96.20.207%3A8080%2Fhome

HTTP/1.1 200 OK

# External to cluster
$ curl -LI http://airflow.fuf.me
HTTP/1.1 302 FOUND
Location: http://airflow.fuf.me/home

HTTP/1.1 302 FOUND
Location: http://airflow.fuf.me/login/?next=http%3A%2F%2Fairflow.fuf.me%2Fhome

HTTP/1.1 200 OK
```

We only found 2 redirections. Maybe it has to do with the cookies in the web browser. To do the testing above, we installed airflow with the following command.

```
$ helm install airflow bitnami/airflow --set "ingress.enabled=true" --set "ingress.hosts[0].name=airflow.fuf.me"
```

**Comment by Yinabled** [comment]
Thanks @andresbono. The specific values used when deploying the chart are the default chart values, except for `"service.type=ClusterIP"`. Here's our Airflow `helm_release` Terraform configuration (the `set` blocks correspond to `--set` arguments when installing the chart):
```
resource "helm_release" "airflow" {
  name       = "bitnami"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "airflow"
  version    = "8.0.4"

  set {
    name  = "service.type"
    value = "ClusterIP"
  }
}
```

Additionally, I tried each of the queries you mentioned. `curl`ing Airflow from within the cluster (both hitting the Airflow endpoint directly and the cluster IP) produced the same output as what you had mentioned above (i.e. redirecting from `/home` to `/login`). However, `curl`ing the subdomain external to the cluster resulted in the infinite redirect that I had mentioned:

```
HTTP/2 302 
server: envoy
date: Tue, 16 Feb 2021 21:03:11 GMT
content-type: text/html; charset=utf-8
content-length: 217
location: http://airflow.abc.xyz/home
x-frame-options: DENY
vary: Cookie
set-cookie: session=XYZ; Expires=Thu, 18-Mar-2021 21:03:11 GMT; HttpOnly; Path=/; SameSite=Lax
x-envoy-upstream-service-time: 6

HTTP/1.1 301 Moved Permanently
location: https://airflow.abc.xyz/
date: Tue, 16 Feb 2021 21:03:11 GMT
server: envoy
transfer-encoding: chunked

HTTP/2 302 
server: envoy
date: Tue, 16 Feb 2021 21:03:11 GMT
content-type: text/html; charset=utf-8
content-length: 217
location: http://airflow.abc.xyz/home
x-frame-options: DENY
vary: Cookie
set-cookie: session=XYZ; Expires=Thu, 18-Mar-2021 21:03:11 GMT; HttpOnly; Path=/; SameSite=Lax
x-envoy-upstream-service-time: 2

HTTP/1.1 301 Moved Permanently
location: https://airflow.abc.xyz/
date: Tue, 16 Feb 2021 21:03:11 GMT
server: envoy
transfer-encoding: chunked

...

curl: (47) Maximum (50) redirects followed
```

It seems as if Airflow is redirecting from the HTTPS root path to `http://airflow.abc.xyz/home` via 301/302 redirects. Should something be configured within Airflow to enable SSL?

**Comment by Yinabled** [comment]
I ended up resolving this issue by switching to the [airflow-helm implementation](https://github.com/airflow-helm/charts/tree/main/charts/airflow) since I was familiar with how to set the Airflow config via values, and then setting `ENABLE_PROXY_FIX=True` on that chart. However, I'd like to use Bitnami's chart since it seems more consistently-maintained - how would I go about enabling this setting using this chart's values?

**Comment by andresbono** [comment]
If you want to set that, you should be able to use the following parameter in your values: `web.extraEnvVars`.

https://github.com/bitnami/charts/blob/1b3b6ea089dfa8239bce9011f5490db2148806e6/bitnami/airflow/values.yaml#L121-L123

In yaml, it would be:

```yaml
web:
  extraEnvVars:
  - name: AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX
    value: 'True'
```

You can check if it is enabled by executing:

```
$ kubectl exec <airflow-web-pod> -- airflow config get-value webserver enable_proxy_fix
True
```

For reference:
- https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#enable-proxy-fix
- https://github.com/bitnami/bitnami-docker-airflow#environment-variables

Let us know if that solves the issue.

**Comment by barmanand** [comment]
@andresbono I am also facing the same issue, But setting up this env variable is not making any impact. I am still getting redirect issue. Can you please check, how we can avoid this issue. Thanks!

**Comment by andresbono** [comment]
Hi @Yinabled, were you able to resolve the issue in the end? Do you have any suggestions for @barmanand?

@barmanand, are you also using envoy? What is the redirect loop?

**Comment by barmanand** [comment]
Hi @andresbono I get the issue, somehow the tables with names starting with ab_ are getting created, But they are not getting populated with default data, so thats why I am etting redirect issue as user is not having any permissions setup.
Do you have any idea why tables are not getting populated with 1.10.12 airflow version? It is working if I don't specify any airflow version, it picks latest one.

**Comment by andresbono** [comment]
Hi @barmanand, I'm not fully understanding the issue. Can you give us more details to reproduce your problem?

**Comment by viniciusesteter** [comment]
Hi guys, the issue still continue for me. Anybody can help me please?
