### ISSUE TITLE
[Bitnami/Postgres] Storage class option for master and replica

### ISSUE THREAD

**Issue by electrical** [bitnami/charts#5494]
**Which chart**:
postgres

**Is your feature request related to a problem? Please describe.**
Currently when using persistence for the data, it's not possible to have a separate storageClass or other settings.
Although size would make sense since it's a 1 to 1 replica, i want to have the master on ceph backed storage, and the replica on local lvm backed storage.
Currently this is not possible

**Describe the solution you'd like**
Separate config setting for at least the `storageClass`

**Describe alternatives you've considered**
Alternative would be to copy the helm chart and store it locally :-(

**Comment by miguelaeh** [comment]
Hi @electrical ,
I am not sure to understand the issue. Isn't this parameter enough to configure the sorage class? https://github.com/bitnami/charts/blob/951c82830ed1b973d43e17c72b51b741bc1e955d/bitnami/postgresql/values.yaml#L405

**Comment by electrical** [comment]
My apologies for not adding a title, I must have overlooked that :-)
The StorageClass option works indeed but it sets it for both the master and replica the same.
You can't configure it in a way that the master uses one StorageClass option and that the replica's use another one.

**Comment by miguelaeh** [comment]
Hi @electrical ,
Thank you for the clarification, that seems to not be supported, would you like to acreate a PR adding that change? We will really appreciate it

**Comment by electrical** [comment]
@miguelaeh sorry for the delay. More than happy to add the support for it.
I presume backwards compatibility is required?
The cleanest solution would be for both the primary and readreplica's to have their own persistence part.

**Comment by miguelaeh** [comment]
Hi @electrical ,
Thank you very much!!
> I presume backwards compatibility is required?

Yes, we always prefer to maintain it until breaking it is totally necessary.
