### ISSUE TITLE
Issue in installation of [Grafana/Prometheus]

### ISSUE THREAD

**Issue by netdip** [bitnami/charts#5495]
When we try to install grafana/prometheus we are getting error.

diptenh:~/kube-vnext(OV-14569/st4-grafana⚡) » helm install grafana -f environment/release4/apps/grafana/values.yaml bitnami/grafana --dry-run                                                    1 ↵
Error: parse error at (grafana/charts/common/templates/_secrets.tpl:84): function "lookup" not defined

----------
diptenh:~/kube-vnext(OV-14569/st4-grafana⚡) » helm install  prometheus -f environment/release4/apps/prometheus/values.yaml bitnami/kube-prometheus --dry-run
Error: parse error at (kube-prometheus/charts/common/templates/_secrets.tpl:84): function "lookup" not defined

**Comment by Mauraza** [comment]
Hi @netdip,

what version of `helm` are you using?
```
helm version
```

**Comment by netdip** [comment]
Hi

It is helm V3.

**Comment by netdip** [comment]
Thanks for reply. After upgrading to latest helm version issue has been resolved.

version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
