### ISSUE TITLE
[bitnami/mariadb-galera] mariabackup replication auth credentials visible in log output

### ISSUE THREAD

**Issue by m-guest** [bitnami/charts#5497]
**Which chart**:
mariadb-galera 5.5.1 (also tested with version 5.4.0, but probably more versions affected)

**Describe the bug**
mariabackup replication credentials (username and **password**) are visible in Pod logs.

**To Reproduce**

1. Install chart with default settings:
`helm install galera-test bitnami/mariadb-galera`
2. After all startup completed and all Pods ready, check logs of joiner Pod:
`kubectl logs galera-test-mariadb-galera-1 |grep mariabackup`
  SST authentication credentials are logged as:
  `... --wsrep_sst_auth=mariabackup:4JLDwkM2O9'`
  Log line example:
```
2021-02-15  9:09:06 0 [Note] WSREP: Running: 'wsrep_sst_mariabackup --role 'joiner' --address '10.1.1.227' --datadir '/bitnami/mariadb/data/' --defaults-file '/opt/bitnami/mariadb/conf/my.cnf' --parent '1' --binlog 'mysql-bin' --mysqld-args --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid --wsrep_node_name=galera-test-mariadb-galera-1 --wsrep_node_address=10.1.1.227 --wsrep_cluster_name=galera --wsrep_cluster_address=gcomm://galera-test-mariadb-galera-headless.default.cluster.local --wsrep_sst_method=mariabackup --wsrep_sst_auth=mariabackup:4JLDwkM2O9'
```

**Expected behavior**
Replication credentials must not be visible in log output.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11", GitCommit:"436254b798f772bcb8e67dcfe122e46500eeb254", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:28Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
As standard MariaDB Galera clusters using the `mariabackup` SST method are not logging this information, this issue is probably related to the Chart implementation or the Docker image [bitnami-docker-mariadb-galera](https://github.com/bitnami/bitnami-docker-mariadb-galera). In particular the log output seems to contain information same as the `dbExtraFlags` variable in Docker image [bitnami-docker-mariadb-galera](https://github.com/bitnami/bitnami-docker-mariadb-galera) script [libmariadbgalera.sh](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/9e933392f799747f2738122b8d4b7c93135ffd38/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L64). Tested with image tags `latest` `10.5` `10.4` with same results.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. I was able to reproduce the issue. We will work on fixing it. I will update the ticket when we have more details.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
