### ISSUE TITLE
[bitnami/mongodb] ReplicaSet not initialized when using NodePort and externalAccess is enabled

### ISSUE THREAD

**Issue by menevs** [bitnami/charts#5508]
**Which chart**:
bitnami/mongodb 10.7.0

**Describe the bug**
When MongoDB tries to initialize a replicaset it uses the value set in $MONGODB_ADVERTISED_HOSTNAME. Using NodePort  for external access results in
```

WARN  ==> Problem initiating replica set
            request: rs.initiate({"_id":"rs0", "members":[{"_id":0,"host":"mongodb.k8s-dev.example.com:27017","priority":5}]})
            response: MongoDB shell version v4.4.4
connecting to: mongodb://127.0.0.1:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("67002c19-b3c3-4beb-ae22-25dcf9fd89d0") }
MongoDB server version: 4.4.4
{
	"ok" : 0,
	"errmsg" : "No host described in new configuration with {version: 1, term: 0} for replica set rs0 maps to this node",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}
```

Regardless of using autodiscovery or not, setting externalAccess.enabled=true and using NodePort won't create a working mongo replicaset. externalAccess.enabled=false will create a working replicaset but there is no way to access it from outside our Kubernetes.

**To Reproduce**

1. install the mongodb Helm Chart using this values.yaml:
```yaml
fullnameOverride: testdb

replicaCount: 3

architecture: replicaset

auth:
  enabled: true
  rootPassword: "root"
  database: "demodb"
  username: "demouser"
  password: "password123"
  replicaSetKey: "xndbbu2x0f"

arbiter:
  enabled: true
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  storageClass: "rbd"

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    type: "NodePort"
    domain: "mongodb.k8s-dev.example.com"
    nodePorts:
      - "30210"
      - "30211"
      - "30212"

serviceAccount:
  create: false

rbac:
  create: true

metrics:
  enabled: false

pdb:
  create: false

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 512Mi

```
helm upgrade --install demo-mongo bitnami/mongodb -f test.yaml

2. kubectl logs -f testdb-0 will show the rs initializing error above after the mongo has configured itself

**Expected behavior**
I would expect the mongoDB initializes correctly and will be accessible from within the cluster and from outside.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Our Kubernetes runs on premise and the mongodb will only be accessed from within our private network. Not setting a value in externalAccess.service.domain will result in an ip lookup with our external ip which won't work. I've also tried using the domain name and ip of one of the nodes which also won't work. The domain specified in the values.yaml will be forwarded from our Netscaler towards the Kubernetes cluster.

**Comment by marcosbc** [comment]
Hi @menevs, it seems this is related to #4073. We have an internal task where we're tracking this issue but unfortunately we haven't made any progress yet. I'll add a note that it is also happening here.

**Comment by zeemba** [comment]
Hi, Just checking if there's any update on this issue @menevs as as I'm currently facing the same problem

**Comment by marcosbc** [comment]
Unfortunately no progress yet.

**Comment by lionants02** [comment]
I am experiencing the same problem.

I'm deploy with docker service.
mount /bitnami/mongodb to /data/mongo1
rs.initiate();
command
vvvvvvvvv

```shell
export DOCKER_IMAGE=bitnami/mongodb:4.4
export SERVICE_NAME=mongo_primary

docker service create --replicas 1 \
  --name ${SERVICE_NAME} \
  --mount type=bind,src=/data/mongo1,dst=/bitnami/mongodb \
  --publish published=30120,target=30120 \
  --health-cmd='echo '"'"'db.runCommand("ping").ok'"'"' | mongo 127.0.0.1:30120/test --quiet' \
  --health-timeout=10s \
  --health-retries=3 \
  --health-interval=5s \
  --health-start-period=40s \
  --env "MONGODB_ADVERTISED_HOSTNAME=healthcare1" \
  --env "MONGODB_PORT_NUMBER=30120" \
  --env "MONGODB_ROOT_PASSWORD=xxxx" \
  --env "MONGODB_REPLICA_SET_MODE=primary" \
  --env "MONGODB_REPLICA_SET_KEY=healthcare1" \
  ${DOCKER_IMAGE}
```

Problem
```shell
thanachai@Telemedicine:~/telehealth/a-med-telehealth-deploy/deploy$ docker exec -it ff660609ea8f /bin/bash
I have no name!@ff660609ea8f:/$ mongo -u "root" -p "xxxx" --host "127.0.0.1:30120"
MongoDB shell version v4.4.5
connecting to: mongodb://127.0.0.1:30120/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("b4e245f8-d264-4be7-9eb2-dd3cf0fa4a39") }
MongoDB server version: 4.4.5
---
The server generated these startup warnings when booting:
        2021-04-28T01:50:48.382+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
---
---
        Enable MongoDB's free cloud-based monitoring service, which will then receive and display
        metrics about your deployment (disk utilization, CPU, operation statistics, etc).

        The monitoring data will be available on a MongoDB website with a unique URL accessible to you
        and anyone you share the URL with. MongoDB may use this information to make product
        improvements and to suggest MongoDB products and deployment options to you.

        To enable free monitoring, run the following command: db.enableFreeMonitoring()
        To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
>
> rs.initiate(
Display all 188 possibilities? (y or n)
> rs.initiate()
{
        "ok" : 0,
        "errmsg" : "No host described in new configuration with {version: 1, term: 0} for replica set replicaset maps to this node",
        "code" : 93,
        "codeName" : "InvalidReplicaSetConfig"
}
>

```

**Comment by marcosbc** [comment]
Thanks for sharing. Unfortunately we have not made any progress fixing this issue yet.

**Comment by lionants02** [comment]
I'm cured.
I edited "MONGODB ADVERTISED HOSTNAME" from "host.xxx.in.th" to "care-primary". And changed "MONGODB_REPLICA_SET_KEY" from "healthcare1" to "takecare". And remove all data.

command
```shell
#!/bin/bash

export DOCKER_IMAGE=bitnami/mongodb:4.4
export SERVICE_NAME=mongo_primary

docker service scale ${SERVICE_NAME}=0
docker service rm ${SERVICE_NAME}
#docker pull ${DOCKER_IMAGE}
docker service create --replicas 1 \
  --name ${SERVICE_NAME} \
  --mount type=bind,src=/data/mongo1,dst=/bitnami/mongodb \
  --mount type=bind,src=/etc/hosts,dst=/etc/hosts,readonly \
  --publish published=30120,target=30120 \
  --health-cmd='echo '"'"'db.runCommand("ping").ok'"'"' | mongo 127.0.0.1:30120/test --quiet' \
  --health-timeout=10s \
  --health-retries=3 \
  --health-interval=5s \
  --health-start-period=40s \
  --env "MONGODB_ADVERTISED_HOSTNAME=care-primary" \
  --env "MONGODB_PORT_NUMBER=30120" \
  --env "MONGODB_ROOT_PASSWORD=xxxxxxxxxx" \
  --env "MONGODB_REPLICA_SET_MODE=primary" \
  --env "MONGODB_REPLICA_SET_KEY=takecare" \
  ${DOCKER_IMAGE}
```

report
```shell
thanachai@Telemedicine:~/telehealth/a-med-telehealth-deploy/deploy$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                    PORTS       NAMES
f7daaa49702e   bitnami/mongodb:4.4    "/opt/bitnami/script…"   34 seconds ago   Up 32 seconds (healthy)   27017/tcp   mongo_primary.1.xyfzocten01fi6d0bsnz7hgrg
320c31488de1   bitnami/redis:latest   "/opt/bitnami/script…"   40 hours ago     Up 40 hours (healthy)     6379/tcp    redis.1.l0w2ntoewa6eyfwa34fk47tam
thanachai@Telemedicine:~/telehealth/a-med-telehealth-deploy/deploy$ docker exec -it f7daaa49702e /bin/bash
I have no name!@f7daaa49702e:/$ mongo -u "root" -p "xxxxxxxxxx" --host "127.0.0.1:30120"
MongoDB shell version v4.4.5
connecting to: mongodb://127.0.0.1:30120/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("36e0d34d-2613-4075-a27f-c7e348ac0249") }
MongoDB server version: 4.4.5
---
The server generated these startup warnings when booting:
        2021-04-28T20:23:01.470+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
---
---
        Enable MongoDB's free cloud-based monitoring service, which will then receive and display
        metrics about your deployment (disk utilization, CPU, operation statistics, etc).

        The monitoring data will be available on a MongoDB website with a unique URL accessible to you
        and anyone you share the URL with. MongoDB may use this information to make product
        improvements and to suggest MongoDB products and deployment options to you.

        To enable free monitoring, run the following command: db.enableFreeMonitoring()
        To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
replicaset:PRIMARY>
replicaset:PRIMARY>
replicaset:PRIMARY>
replicaset:PRIMARY> rs.status()
{
        "set" : "replicaset",
        "date" : ISODate("2021-04-28T20:26:46.331Z"),
        "myState" : 1,
        "term" : NumberLong(2),
        "syncSourceHost" : "",
        "syncSourceId" : -1,
        "heartbeatIntervalMillis" : NumberLong(2000),
        "majorityVoteCount" : 1,
        "writeMajorityCount" : 1,
        "votingMembersCount" : 1,
        "writableVotingMembersCount" : 1,
        "optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1619641602, 1),
                        "t" : NumberLong(2)
                },
                "lastCommittedWallTime" : ISODate("2021-04-28T20:26:42.664Z"),
                "readConcernMajorityOpTime" : {
                        "ts" : Timestamp(1619641602, 1),
                        "t" : NumberLong(2)
                },
                "readConcernMajorityWallTime" : ISODate("2021-04-28T20:26:42.664Z"),
                "appliedOpTime" : {
                        "ts" : Timestamp(1619641602, 1),
                        "t" : NumberLong(2)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1619641602, 1),
                        "t" : NumberLong(2)
                },
                "lastAppliedWallTime" : ISODate("2021-04-28T20:26:42.664Z"),
                "lastDurableWallTime" : ISODate("2021-04-28T20:26:42.664Z")
        },
        "lastStableRecoveryTimestamp" : Timestamp(1619641552, 1),
        "electionCandidateMetrics" : {
                "lastElectionReason" : "electionTimeout",
                "lastElectionDate" : ISODate("2021-04-28T20:23:02.651Z"),
                "electionTerm" : NumberLong(2),
                "lastCommittedOpTimeAtElection" : {
                        "ts" : Timestamp(0, 0),
                        "t" : NumberLong(-1)
                },
                "lastSeenOpTimeAtElection" : {
                        "ts" : Timestamp(1619641379, 8),
                        "t" : NumberLong(1)
                },
                "numVotesNeeded" : 1,
                "priorityAtElection" : 5,
                "electionTimeoutMillis" : NumberLong(10000),
                "newTermStartDate" : ISODate("2021-04-28T20:23:02.656Z"),
                "wMajorityWriteAvailabilityDate" : ISODate("2021-04-28T20:23:02.760Z")
        },
        "members" : [
                {
                        "_id" : 0,
                        "name" : "care-primary:30120",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 225,
                        "optime" : {
                                "ts" : Timestamp(1619641602, 1),
                                "t" : NumberLong(2)
                        },
                        "optimeDate" : ISODate("2021-04-28T20:26:42Z"),
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "electionTime" : Timestamp(1619641382, 1),
                        "electionDate" : ISODate("2021-04-28T20:23:02Z"),
                        "configVersion" : 1,
                        "configTerm" : 2,
                        "self" : true,
                        "lastHeartbeatMessage" : ""
                }
        ],
        "ok" : 1,
        "$clusterTime" : {
                "clusterTime" : Timestamp(1619641602, 1),
                "signature" : {
                        "hash" : BinData(0,"nClbslPr/QX8T+pmefquetH4xTs="),
                        "keyId" : NumberLong("6956306754053341189")
                }
        },
        "operationTime" : Timestamp(1619641602, 1)
}
replicaset:PRIMARY>

```

hosts file
```shell
127.0.0.1       localhost
203.xx.xx.xx   care-primary
# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by DanPhonovation** [comment]
Still experiencing this on latest Helm chart.

Is there a K8 equivalent solution of the above?

**Comment by Mauraza** [comment]
Hi @DanPhonovation,

We have not yet been able to make progress on this. We update the thread when we have more information.

**Comment by GeorgeL231** [comment]
Hello,

When using a helm chart, the only way i got it working is by first installing it without externalAccess parameters and then configuring them after with helm upgrade.

helm install my-mongodb-instance bitnami/mongodb \
--create-namespace --namespace my-mongodb-instance \
--set architecture="replicaset" \
--set replicaCount=2 \
--set resources.limits.memory="2048M" \
--set metrics.enabled=true

helm upgrade my-mongodb-instance bitnami/mongodb \
--namespace my-mongodb-instance \
--set architecture="replicaset" \
--set replicaCount=2 \
--set resources.limits.memory="2048M" \
--set metrics.enabled=true \
--set externalAccess.enabled=true \
--set externalAccess.service.type=NodePort \
--set externalAccess.service.nodePorts[0]=<port1> \
--set externalAccess.service.nodePorts[1]=<port2> \
--set auth.rootPassword=<rootPass_from install> \
--set auth.replicaSetKey=<key_from_install>

Hope it helps.

**Comment by Mauraza** [comment]
Hi @GeorgeL231,

Thanks for sharing!

**Comment by xeroc** [comment]
I changed `MONGODB ADVERTISED HOSTNAME` to `localhost` on the **primary** and it started working.

**Comment by Mauraza** [comment]
Hi @xeroc,

Did you still have the issue?

**Comment by xeroc** [comment]
> Did you still have the issue?

I got it resolved by using

    MONGODB_ADVERTISED_HOSTNAME = "mongo-primary"

and adding `mongo-primary` (resolving to `localhost`) to my `/etc/hosts`.

The setup still doesn't sync entirely though

**Comment by gongzhao2** [comment]
Hi,

For my case, I just disable the "externalAccess.enabled" parameter.
Then I use below shell script to create separate service for each mongodb
```
#!/bin/bash

replicaCount=3
namespace=mongodb

for i in $(seq 0 $[replicaCount-1])
do
    cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: mongodb-$i-external
  namespace: $namespace
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mongodb
    nodePort: `expr $i + 30071`
    port: 27017
    protocol: TCP
    targetPort: mongodb
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
    statefulset.kubernetes.io/pod-name: mongodb-$i
  sessionAffinity: None
  type: NodePort
EOF
done
```
Then we can use node-ip to access MongoDB.
```
mongo admin --host "node-ip:30071,node-ip:30072,node-ip:30073" --authenticationDatabase admin -u root -p ***
```

Just in case someone still suffers from this issue.

**Comment by Mauraza** [comment]
Hi @gongzhao2,

Thanks for your contribution!

**Comment by adithep** [comment]
Hi @gongzhao2,

Just curious are you able to connect to replica set from external shell like so?

`mongo "root:***@node-ip:30071,node-ip:30072,node-ip:30073/admin?replicaSet=rs0`

**Comment by GeorgeL231** [comment]
Hi,

If you are connecting with something like MongoDB Compass, you need to connect to the primary node:

mongodb://root:***@primary-node-ip:30071/admin

I believe there is an issue with version 1.23 so i connect with 1.26.

Thank you.

**Comment by gongzhao2** [comment]
> Hi @gongzhao2,
> 
> Just curious are you able to connect to replica set from external shell like so?
> 
> `mongo "root:***@node-ip:30071,node-ip:30072,node-ip:30073/admin?replicaSet=rs0"`

yes, you should able to connect MongoDB via below address.
```
root:***@node-ip:30071,node-ip:30072,node-ip:30073/admin?authSource=admin&gssapiServiceName=mongodb
```

**Comment by Mauraza** [comment]
Hi @oldluke92,

Thanks for sharing your workaround!

**Comment by deveshk0** [comment]
So With support of `MONGODB_ADVERTISED_PORT`  and some changes in helm chart, NodePort works fine.

**Comment by Mauraza** [comment]
Hi @deveshk0,

Thanks for the contribution! The issue will be closed when the PR gets merged.

**Comment by sunxunkang** [comment]
problem still exists on Chart version: 10.31.5

**Comment by marcosbc** [comment]
@sunxunkang If you continue finding issues, I encourage you to open a new issue so we can understand further what might be happening in your case. Please also make sure to link to this issue, just in case.

**Comment by sunxunkang** [comment]
> 

my fault，I build my mongo replicaset cluster before turn on externalAccess，and I store mongo data in pv，so I have to use rs.reconfig() to change rs member info

**Comment by andrejvanderzee** [comment]
The nodeport workaround does work until your Kubernetes nodes are rotated and get new IPs. The replicaset config will still hold the old IPs and the mongodb nodes will fail to initialize.

@Mauraza Is there any progress in fixing external access via LoadBalancer services?

**Comment by rcmonitor** [comment]
I can confirm that the issue still exists on 

- bitnami/mongodb v13.18.1
- docker-desktop for Windows v4.22.1 (118664)
- Docker Engine v24.0.5
- Windows 11 Pro 22H2 build	22621.2215
- Kubernetes v1.27.2

> If you continue finding issues, I encourage you to open a new issue so we can understand further what might be happening in your case. Please also make sure to link to this issue, just in case.

I can't see any good reason to open a new issue besides _MOAR ISSUES TO GODS OF ISSUES_ as the description will be totally identical. So for me, issues with same STR and behavior are the one issue.
Regarding merged [FIX](https://github.com/bitnami/charts/pull/8515#top) I believe it only supposed to be called **FIX** if it actually fixes the original issue. Otherwise it is more likely to be a fix-candidate.

I believe, the source of an issue here - is that `rs.initiate()` is trying to set a replica using hostnames provided via `externalAccess.service.domain` but on host-machine it righteousnessly resolves to 127.0.0.1 which leads to the fact that mongodb instance in a container that supposed to be primary is looking for secondaries on the local host.
Instead, rs.initiate() should use cluster-wise hostnames (`pod.namespace.svc.cluster.local`) and may still be externally accessible as it listens on all ips.

**Comment by rafariossaa** [comment]
Hi,
  @rcmonitor as it seems you found the cause of the issue, would you like to contribute and send a PR fixing it ?. We will be glad to review and merge it.

**Comment by rcmonitor** [comment]
> Hi, @rcmonitor as it seems you found the cause of the issue, would you like to contribute and send a PR fixing it ?. We will be glad to review and merge it.

Unfortunately, I'm not dived deeply into specifics of MongoDB replica implementation to submit a PR here(
Maybe, there's some broken logic in mongosh itself, as now I'm trying to further explore the issue and it is kinda strange:
- I deployed `bitnami/mongodb` replica set (2 instances, 1 arbiter) with NO external access
- I forwarded ports directly to pods of a `mongo-mongodb` stateful set
- I'm trying to connect to a replica set via those ports forwarded to a localhost
- 
``` 
> mongosh mongodb://root:very_strong_password@localhost:32031,localhost:32032/admin
Current Mongosh Log ID: 6509ef60f8af919dcddc6e44
Connecting to:          mongodb://<credentials>@localhost:32031,localhost:32032/admin?serverSelectionTimeoutMS=2000&appName=mongosh+1.10.3
MongoNetworkError: getaddrinfo ENOTFOUND mongo-mongodb-0.mongo-mongodb-headless.mongons.svc.cluster.local
```
 
This clearly indicates that `mongosh` is gaining access to a knowledge of a replica set internal configuration, but AFAIC, it MUST NOT.

Then I tried really stupid thing and added required hosts one by one to a `hosts` file to point to `127.0.0.1` as that's the cluster external address for docker-desktop on Windows:

```
127.0.0.1		mongo-mongodb-0.mongo-mongodb-headless.mongons.svc.cluster.local
127.0.0.1		mongo-mongodb-1.mongo-mongodb-headless.mongons.svc.cluster.local
127.0.0.1		mongo-mongodb-arbiter-0.mongo-mongodb-arbiter-headless.mongons.svc.cluster.local
```

The last host in the list was also required by `mongosh` or othrewise raises an `ENOTFOUND` error which means that not only mongosh is trying to address mongo instances by its internal declaration from `rs.initiate()`, but it also wants to somehow participate in a voting process, which is a complete nonsense.

Later assumption got proven immediately by the following error:

```
mongosh mongodb://root:some_strong_password@localhost:32031,localhost:32032/admin?replicaSet=rs0
Current Mongosh Log ID: 6509f764720dcbfcaa1b701e
Connecting to:          mongodb://<credentials>@localhost:32031,localhost:32032/admin?replicaSet=rs0&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.3
MongoServerSelectionError: Server selection timed out after 2000 ms
```
And I know for sure that replica set is healthy and primary is chosen.

So, either I completely don't know what I'm doing, or something is totally off in this connecting logic.

I'll try to spend some more time on exploring.
Also, feel free to enquire more info on issue or tests of any possible hot-fixes.

**Comment by rafariossaa** [comment]
Does the same happens when you try con connect from a pod ?

I deployed mongodb with: 
```
helm install mymongo bitnami/mongodb  --set architecture=replicaset
```

and once deployed:
```
$ export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mymongo-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 -d)

$ kubectl run --namespace default mymongo-mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:6.0.10-debian-11-r0 --command -- bash
```
and in the pod:
```
$ source ./opt/bitnami/scripts/mongodb-env.sh

$ mongosh admin --host mymongo-mongodb-0.mymongo-mongodb-headless.default.svc.cluster.local:27017,mymongo-mongodb-1.mymongo-mongodb-headless.default.svc.cluster.local:27017 --authenticationDatabase admin -u root -p YCw948A6Tq
Current Mongosh Log ID: 650aad8347f27f288fb8debe
Connecting to:          mongodb://<credentials>@mymongo-mongodb-0.mymongo-mongodb-headless.default.svc.cluster.local:27017,mymongo-mongodb-1.mymongo-mongodb-headless.default.svc.cluster.local:27017/admin?authSource=admin&appName=mongosh+1.10.6
Using MongoDB:          6.0.10
Using Mongosh:          1.10.6
...

```
As you can see in the `mongosg` log, it is not connecting to the arbiter.

**Comment by rcmonitor** [comment]
> Does the same happens when you try con connect from a pod ?

No.
I can easily connect to this replica from ANY pod within cluster using pod internal hostnames:

```
> mongosh mongodb://root:some_strong_password@mongo-mongodb-0.mongo-mongodb-headless.mongons.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.mongons.svc.cluster.local:27017/admin
Current Mongosh Log ID: 650a09ec1ff36d971fc10406
Connecting to:          mongodb://<credentials>@mongo-mongodb-0.mongo-mongodb-headless.mongons.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.mongons.svc.cluster.local:27017/admin?appName=mongosh+2.0.1
Using MongoDB:          6.0.9
Using Mongosh:          2.0.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

------
   The server generated these startup warnings when booting
   2023-09-17T08:41:20.517+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2023-09-17T08:41:21.592+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
   2023-09-17T08:41:21.592+00:00: vm.max_map_count is too low
------

rs0 [primary] admin>
```

> As you can see in the `mongosg` log, it is not connecting to the arbiter.

If you are talking about this chunk of my log:

```
mongosh mongodb://root:some_strong_password@localhost:32031,localhost:32032/admin?replicaSet=rs0
Current Mongosh Log ID: 6509f764720dcbfcaa1b701e
Connecting to:          mongodb://<credentials>@localhost:32031,localhost:32032/admin?replicaSet=rs0&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.3
MongoServerSelectionError: Server selection timed out after 2000 ms
```

I believe, that's not the case: I removed arbiter's hostname from `hosts` file and error changed to `ECONNREFUSED 127.0.0.1:27017`

Finally, I managed to hack into and connect to this F%^(&*G replica set from outside just because I really need it to perform development debug before deployment.

So, what I did is: 
- I duplicated 2 internal cluster pod's hostnames on the outside via `hosts` file
```
127.0.0.1		mongo-mongodb-0.mongo-mongodb-headless.mongons.svc.cluster.local
127.0.0.1		mongo-mongodb-1.mongo-mongodb-headless.mongons.svc.cluster.local
```
- I forwarded ports of this TWO pods THREE times:
```
> kubectl port-forward -n mongons pod/mongo-mongodb-0 32031:27017
> kubectl port-forward -n mongons pod/mongo-mongodb-1 32032:27017
> kubectl port-forward -n mongons pod/mongo-mongodb-0 27017:27017
```
- I connected just like recommended in docs:
```
> mongosh mongodb://root:some_strong_password@localhost:32031,localhost:32032/admin?replicaSet=rs0
Current Mongosh Log ID: 650acd820c83841b3cbc7659
Connecting to:          mongodb://<credentials>@localhost:32031,localhost:32032/admin?replicaSet=rs0&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.3
Using MongoDB:          6.0.9
Using Mongosh:          1.10.3

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

------
   The server generated these startup warnings when booting
   2023-09-17T08:41:20.517+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
   2023-09-17T08:41:21.592+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
   2023-09-17T08:41:21.592+00:00: vm.max_map_count is too low
------

rs0 [primary] admin>
```
This solution is TOTALLY inappropriate as it implies `mongo-mongodb-0` is always `primary`. 
Once it got `secondary` state, you'll end up connecting to a secondary and lose the ability to write.

For now, my initial guess 100% confirmed: `mongosh` got to internals of replica set configuration, learns hostnames and ports of instances out of it, and trying to connect using this addresses.
As ports on the pods are configured to 27017 (or omitted, which is the same) mongosh is looking for an elected primary at `mongo-mongodb-0.mongo-mongodb-headless.mongons.svc.cluster.local:27017` from the host machine whereas instead it should be dialing to `localhost:32031` as specified in connection string.

Got no idea how to fix this so far if there is no distinction in `rs.initiate()` between internal connection strings and external, or some flag to `mongosh` (and all the library driver implementations out there) to ignore internal connection settings and use only ones provided.

**Comment by rafariossaa** [comment]
Hi,
  Maybe you could bring that question to mongodb maintainers.
