### ISSUE TITLE
[btinami/kafka] Combination of Zookeeper with jaas-SASL and client with mTLS not possible

### ISSUE THREAD

**Issue by sveba** [bitnami/charts#5523]
This block is dependent from settings for client and interbroker protocol. 
https://github.com/bitnami/charts/blob/ec76369dec2948a2b14e5a05b6156ff75384b389/bitnami/kafka/templates/statefulset.yaml#L225-L235

This makes the usage of ZK with SASL (Username + Pass) in combination with client/interbroker mTLS not possible

**Comment by alemorcuq** [comment]
Hi, @sveba. Do you mind elaborating a bit? I'm afraid I don't understand the issue with that block.

**Comment by sveba** [comment]
> Hi, @sveba. Do you mind elaborating a bit? I'm afraid I don't understand the issue with that block.

sure, 
the problem is that the Zookeeper auth block depends from the https://github.com/bitnami/charts/blob/ec76369dec2948a2b14e5a05b6156ff75384b389/bitnami/kafka/templates/statefulset.yaml#L213

So if you need a SASL (Username:Pass) between the brokers and the zookeeper you **must** use SASL for the client or the interbroker communication.

I have the case that I use mTLS for the client and the interbroker authentication and SASL between Kafka-broker and Zookeeper.

**Comment by sveba** [comment]
@alemorcuq was my comment useful?

**Comment by alemorcuq** [comment]
Yes, @sveba, thank you very much!
