### ISSUE TITLE
[bitnami/redis-cluster] init job labels same as pods

### ISSUE THREAD

**Issue by noe-charmet** [bitnami/charts#5526]
**Chart**:
redis-cluster @ 4.3.1

**Bug**:
The pods managed by the StatefulSet as well as the Job used to initialize the cluster share some common labels. These labels being the ones that are used as selector by other resources.

This causes confusion on some resources and unexpected behaviors. For now I have identified:
- The init Job is seen as being a children of the StatefulSet as  its selector matches.
- PodDisruptionBudget can not be applied as they consider the Job even when terminated to be part of the observed pods. They will throw events stating that they can not find the controller for the pod.

**To Reproduce**
Deploy the chart with a PodDisruptionBudget and then run `kubectl describe` on that PodDisruptionBudget.

**Expected behavior**
To avoid selector confusion, Primary pods that are actual children of the StatefulSet should have some supplementary labels, or the init Job should not use the same labels.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by migruiz4** [comment]
Hi @noe-charmet ,

I'm sorry for the late response. I have created this PR #5593 that should fix this issue by adding a filter to the PodDisruptionBudget to not match the initJob using the label `job-name`.

Would the fix would work for your case?

**Comment by noe-charmet** [comment]
thanks for taking time to resolve the issue ;)

This would indeed fix the immediate issue of PodDisruptionBudget matching the job.

I would however personally vouch to extend this to other selectors in the chart that need to select only the children of the StatefulSet.

Namely:
- Headless service
- Network policies
- Redis service
- External access service

Effect would be quite negligible in most cases, but it would avoid any possible confusion or issue on this aspect.

Maybe that adding a label to the jobs, similarly to how it is done on the metrics exporter, would be more in line with the general approach of Bitnami charts.

Anyways the PR would fix my immediate issue, so if you see it as enough it's all good for me.
