### ISSUE TITLE
https://charts.bitnami.com/bitnami access denied

### ISSUE THREAD

**Issue by StanleyP** [bitnami/charts#5527]
Hello,

I am getting access denied on bitnami chart repo https://charts.bitnami.com/bitnami:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8G1Q0J1K2XFZ5T6R</RequestId>
<HostId>
FfnwYpA3ny4ZdMPIE+BIFv/sJ7Ke9FmWuQlkYXAf2bfzTRoSd3fZp2JLJQ7RsttMTa7VBObZIN0=
</HostId>
</Error>
```
3 hours ago it was still working.

Is it an outage? Or change of endpoint? Thanks for any info, currently our CI/CD builds are blocked.

**Comment by javsalgar** [comment]
Hi,

I just tried again and it seems to work now, I imagine it was something transient. Could you please check again?

**Comment by StanleyP** [comment]
Hello, yes, I can confirm that is works.

**Comment by shirivgb** [comment]
Hi,

It happens to me now. any ideas?

**Comment by marcosbc** [comment]
Hi @shirivgb, it works for me now (using `helm repo update`), so it is probably something transient like mentioned above. Could you try again?

**Comment by shirivgb** [comment]
Hi,
I can confirm that it works now. thanks!

**Comment by oniram88** [comment]
Hi,
It happens to me now, any one else?

**Comment by javsalgar** [comment]
Could you try again? It seems transient. I found no isses

**Comment by makapszenna** [comment]
Hi, It happens to me since yesterday also. What is wrong?

**Comment by carrodher** [comment]
Thanks for letting us know, we are facing some **transient** issues with the Helm registry, it should work if you retry it:
```console
$ helm repo add bitnami2 https://charts.bitnami.com/bitnami
"bitnami2" has been added to your repositories
```

Please note this issue was already reported at #8433, I will maintain this one as closed in order to keep all the conversations in a single place. Thanks!
