### ISSUE TITLE
solr deployment fails when trying to install it with exporters

### ISSUE THREAD

**Issue by gkulkarni32** [bitnami/charts#5537]
**Which chart**:
bitnami/solr

**Describe the bug**
When I try to deploy the solr chart with exporters, it fails.

**To Reproduce**

1. Run : `helm install dp -n dp  bitnami/solr --set authentication.enabled=false,exporter.enabled=true`
2. See error: ```Error: Deployment.apps "dp-solr-exporter" is invalid: spec.template.spec.containers[0].livenessProbe.successThreshold: Invalid value: 15: must be 1``` 

**Expected behavior**
Deployment should go through. The successThreshold value set in values.yaml is not correct, needs to be changed. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by marcosbc** [comment]
Thanks for reporting @gkulkarni32! We just fixed this in #5548. For now, to workaround this while the new chart is released, you could deploy with `--set exporter.livenessProbe.successThreshold=1`.
