### ISSUE TITLE
Error executing 'postInstallation': ENOSPC: no space left on device, mkdir '/opt/bitnami/airflow/tmp'

### ISSUE THREAD

**Issue by edikmkoyan** [bitnami/charts#5538]
**Which chart**:
The name (and version) of the affected chart 8.0.4 - Feb 12, 2021

**Describe the bug**
The scheduler and the web are not being Initialized due to small amount of disk space.

**To Reproduce**
helm install airflow

**Comment by andresbono** [comment]
Hi @edikmkoyan, it looks like the node where the pod is deployed is running low in disk space. Could you check that?
