### ISSUE TITLE
[Bitnami/ElasticSearch] How can I run only one replica per node ?

### ISSUE THREAD

**Issue by chromafunk** [bitnami/charts#5541]
**Which chart**:
[Bitnami/ElasticSearch] 14.2.1

Is it possible to run only one replica of coordinating / master / data nodes, only ONE replica per node ?

Right now by default I am getting two replicas stuffed on the same node, and it's killing my resources. I have 3 worker nodes and I would like to run only one of each per worker node on the cluster.

Any hints on how to achieve this would be great, as I can't find any option for this in the chart values

Thanks !

**Comment by alemorcuq** [comment]
Hi, @chromafunk.

You need to set up pod anti-affinities for that. You can read more about them here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity

In particular for our charts, you can try using the `hard` preset for pod anti-affinity: https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#setting-pods-affinity
