### ISSUE TITLE
Airflow: Connections and variables in the charts values

### ISSUE THREAD

**Issue by mailtobash** [bitnami/charts#5544]
The airflow/stable version has support for `connections` and `variables` to be passed to it [as per the chart here](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/scheduler/scheduler-deployment.yaml) but the current version of bitnami charts seem to be missing it.
Any guidance on how this can be configured when deploying the chart would be great.

Example how can I perform:
```scheduler:
    connections:
    - id: aws_default
      type: aws
      extra: '{"region_name": "ap-southeast-2"}'
```

**Comment by juan131** [comment]
Hi @mailtobash 

Please note the charts behaviour is different.

It seems that chart you shared mounts some JSON files including pools, variables, connections, etc. and then adds them to Airflow during the initialisation, see:

- https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/scheduler/scheduler-deployment.yaml (lines 253 to 264)

The Bitnami chart, allows to specify any custom environment variable using `scheduler.extraEnvVar`, `scheduler.extraEnvVarsCM`, or`scheduler.extraEnvVarsSecret` parameters. And, as it's explained [here](https://github.com/bitnami/bitnami-docker-airflow-scheduler#environment-variables) all the parameters from the Airflow configuration file can be overwritten by using environment variables with this format: `AIRFLOW__{SECTION}__{KEY}`.
You can also use the `scheduler.extraVolumeMounts` and `scheduler.extraVolumes` parameters to mount any custom files (e.g. mounting JSON files from custom configmaps) in the container.

**Comment by mailtobash** [comment]
Thank you @juan131 ,
The `AIRFLOW__{SECTION}__{KEY}` helps to mount the extraVariables.
For the connections,however lines 257 to 260 in the template, there is not an equivalent in the bitnami chart :
```              
{{- if or (.Values.scheduler.connections) (.Values.scheduler.existingSecretConnections) }}
               && echo "*** adding Airflow connections..." \
               && /home/airflow/connections/add-connections.sh \
{{- end }} 
```

**Comment by juan131** [comment]
Hi @mailtobash 

You're right. There's no easy or direct way to do this using the Bitnami Airflow chart. You can try adding a sidecar container to the scheduler pods, see:

- https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml#L292

This container could try configure the connections automatically using a command such as the one below:

```console
airflow connections --add --conn_id ...
```

That said, it's likely that you'll find issues using this approach. I agree this is something to be properly implemented in the scheduler container/charts. I'd open an internal task to add this feature.

**Comment by mailtobash** [comment]
Thank you @juan131 .

I was able to get this going by doing the below.I dont think it is the perfect solution. If bitnami could add provisions for a script in the airflow container I think that is the better solution. The scheduler is waiting in ContainerCreating state until worker comes up.

1. Create a config map as secret containing the script to add connections. The key here was to make sure that the webserver is all set up and running, which is the curl command that looks for a healthy web pod. Used the `/health` enpoint to detect it.
```
apiVersion: v1
kind: Secret
metadata:
  name: additional-scripts
type: Opaque
stringData:
  add-connections.sh: |
    #!/usr/bin/env bash
    max_tries=0
    while : ; do
      health_count=$(curl -s "http://${AIRFLOW_WEBSERVER_HOST}:${AIRFLOW_WEBSERVER_PORT_NUMBER}/health" |  grep status | grep -wc "healthy")
      echo "Health count is ${health_count}" | tee -a /opt/bitnami/airflow/bootstrap.log
      
      if [[ ${health_count} -ne 2 ]]; then
        echo "Not healthy yet: Sleeping 5 seconds. Max tries is ${max_tries} / 60" | tee -a /opt/bitnami/airflow/bootstrap.log
        max_tries=$((max_tries+1))
        sleep 5
      fi

      if [[ ${health_count} -eq 2 ]] || [[ ${max_tries} -eq 60 ]]; then
        break
      fi

    done

    if [[ ${max_tries} -eq 60 ]]; then
      echo "Airflow did not come up, exiting bootstrap ... " | tee -a /opt/bitnami/airflow/bootstrap.log
      exit 1
    fi

    # remove any existing connection
    airflow connections delete "aws_default" | tee -a /opt/bitnami/airflow/bootstrap.log
  
    # re-add your custom connection
    airflow connections add "aws_default" --conn-type "aws" --conn-extra "{\"region_name\":\"ap-southeast-2\"}" | tee -a /opt/bitnami/airflow/bootstrap.log

    # Add our variables
    airflow variables set email_notification "True" | tee -a /opt/bitnami/airflow/bootstrap.log
```

2. Add a `lifecycle` property to scheduler config that will run this script:
```
scheduler:
  extraVolumeMounts:
    - name: airflow-scheduler
      mountPath: /opt/bitnami/airflow/dags
    - name: additional-scripts
      mountPath: /bitnami/python/
  extraVolumes:
    - name: airflow-scheduler
      persistentVolumeClaim:
          claimName: airflow-claim
    - name: additional-scripts
      secret:
        secretName: additional-scripts
        defaultMode: 0755
  lifecycle:
    postStart:
      command: "/bitnami/python/add-connections.sh"
```

3. Modify the `scheduler/deployment.yaml` for scheduler to add the postStart lifecycle step.
```
{{- if .Values.scheduler.lifecycle }}
          lifecycle:
            {{- if .Values.scheduler.lifecycle.postStart }}
            postStart:
              exec:
                command: [ {{ .Values.scheduler.lifecycle.postStart.command }} ]
 {{- end }}
```

**Comment by juan131** [comment]
That's great @mailtobash. Thanks so much for sharing this solution!

It'll be very helpful for us to implement the final solution in the Bitnami Airflow image. As I said in my last message I opened a task to work on this feature, and it's in our backlog. We'll notify you about our progress.

**Comment by gcalmettes** [comment]
I got a similar need, thanks @mailtobash I will try your workaround.

**Comment by carrodher** [comment]
Unfortunately, since we are a small team we didn't find the bandwidth to spend time on this topic nor there are plans to work on it in the short/middle term.
PRs are welcome, the team will be happy to review them and provide feedback.

**Comment by kodeine** [comment]
is this not going to be implemented?

**Comment by kodeine** [comment]
@carrodher 
is this not going to be implemented?

**Comment by kodeine** [comment]
@mailtobash how did you setup the vars can you please give me an example?

**Comment by mailtobash** [comment]
@kodeine my above post is how I implemented it.
Adding the `lifecycle.postStart.command` as an additional value and mount the secret with the script that set up the variables

```  lifecycle:
    postStart:
      command: "/bitnami/python/add-connections.sh"
```

**Comment by rafariossaa** [comment]
@kodeine I am sorry, but not by now. 
As @carrodher indicated, we are a small team and we have not bandwidth right now, but feel free to send a PR implementing this. We will be glad to review and merge it.
