### ISSUE TITLE
Joomla Kubernetes on Digital Ocean

### ISSUE THREAD

**Issue by wittydan** [bitnami/charts#5545]
I am trying to get joomla setup with Kubernetes on Digital Ocean. I keep running into the same error after running "helm install my-release bitnami/joomla." The error says "Kubernetes cluster unreachable: Get http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1.8080: connect: connection refused."

**Comment by andresbono** [comment]
Can you make sure that kubectl is using the correct context?

```
kubectl config get-contexts
```
