### ISSUE TITLE
[bitnami/thanos] receive component is broken

### ISSUE THREAD

**Issue by haghabozorgi** [bitnami/charts#5549]
**Which chart**:
Thanos 3.11.1

**Describe the bug**
Template seems to be broken at https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/statefulset.yaml#L80

**To Reproduce**
set `receive.enabled` to `true`
trying to apply the helm charts returns 
```
Error: template: thanos/templates/receive/statefulset.yaml:80:24: executing "thanos/templates/receive/statefulset.yaml" at <eq .Values.receive.replicaCount 1>: error calling eq: incompatible types for comparison
```

**Expected behavior**
I expected the component to deploy. I believe the cause was introduced in this PR https://github.com/bitnami/charts/pull/5504

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by haghabozorgi** [comment]
this actually does not seem to be an issue with the helm chart and is perhaps the way we are using terraform to apply this chart. going to close for now.

**Comment by ThoreKr** [comment]
@haghabozorgi can you elaborate on this?

We are facing the same issue, but with a flux helmrelease pipeline and it seems to break with the default values.yaml.

**Comment by haghabozorgi** [comment]
@ThoreKr  for example, when using terraform we were supplying values to the `helm_release` provider using 
```
  values = [
    <<YAML
receive:
  enabled: true
  replicaCount: 1
YAML
    ,
  ]
```
From what I gathered it seems helm possibly thinks the value provided is a string not an int??? I did not go down the rabbit hole deep enough to find out for sure though. Oddly it seemed using `set` does work as expected though.
```
  set {
    name  = "receive.replicaCount"
    value = 1
  }
```
Let me know if you have any questions. Hope this helps.

**Comment by ThoreKr** [comment]
Ok, so basically got to the same point (except I only have yaml at hand) but I'm also getting this error while not explicitly overriding it, so I'd still say it's a bug?

**Comment by haghabozorgi** [comment]
@ThoreKr not sure I followed that, are you using terraform(helm provider) in your setup? Note, when I tried applying this chart without explicitly setting the `replicaCount` I was getting the same error. 
I tested the thanos helm chart by rendering it using `helm template` with the default values.yaml and it rendered as expected, so it certainly seems helm was working as expected? I came to conclusion there was something funky with terraform helm provider.

**Comment by ThoreKr** [comment]
@haghabozorgi Interesting. We are using flux, so it's a HelmRelease resource definition, which pipes the values.yaml from a configmap into the helm deployment service.

The configmap is stored as a multiline yaml text block.

In the end it looks like this.
```YAML
--
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-configmap
  namespace: thanos
data:
  values.yaml: |
    receive:
      ## Set to true to enable Thanos Receive component
      ##
      enabled: true

      ## Number of Thanos Receive replicas to deploy
      ##
      replicaCount: 1
 ```
 
 But even when the replicaCount is commented out, it throws the same error.

**Comment by haghabozorgi** [comment]
@ThoreKr, I dont know too much about flux's helmrelease resource, but it is curious you are also seeing the same issue. while not using the same mechanism. I wonder if terraform helm provider and flux helmrelease resource are doing something funky or if this is indeed a bug in the chart with how the conditional is being done. have you tried in that yaml to do `replicaCount: ""1""` or something like `replicaCount: !!integer 1`?

**Comment by haghabozorgi** [comment]
Given @ThoreKr experience, we may want to confirm if this is indeed a bug

**Comment by ThoreKr** [comment]
@haghabozorgi It's the same issue with both. I notified @Cellebyte to share how they are configuring this.

**Comment by haghabozorgi** [comment]
my guess is something in the way go templating language differs in various versions of helm? Thanks for notifying him. @ThoreKr  can you confirm what version of helm you are seeing this with?

**Comment by ThoreKr** [comment]
As far as I can tell it should be sourced here https://github.com/fluxcd/helm-controller/blob/v0.6.1/go.mod#L16 3.5.0, but that's just an slightly educated guess.

**Comment by Cellebyte** [comment]
@ThoreKr i will fix it by doing a typecast.

**Comment by miguelaeh** [comment]
Thank you very much guys for the detailed discussion and create the fix!!! ❤️ 
We really appreciate it!

**Comment by Cellebyte** [comment]
@haghabozorgi do you want to test? I can provide you with a custom build.

**Comment by Cellebyte** [comment]
@miguelaeh the fix is now tested and is working as @ThoreKr tested it.
