### ISSUE TITLE
[Bitnami/Kibana] Readiness probe failed

### ISSUE THREAD

**Issue by mazzespazze** [bitnami/charts#5550]
**Which chart**:
bitnami/kibana

**Describe the bug**
Running Kubernetes on DigitalOcean.
I have already installed "bitnami/elasticsearch" that works perfectly. I wanted to attach Kibana to it, but when I run this command:
`helm install kibana --set elasticsearch.hosts[0]=http://elasticsearch-elasticsearch-coordinating-only --set elasticsearch.port=9200 bitnami/kibana` 

I am keep getting a: `Readiness probe failed: HTTP probe failed with statuscode: 503`

**To Reproduce**
I installed elasticsearch with the following commands:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install elasticsearch --set \ 
name=elasticsearch,master.replicas=3,coordinating.service.type=LoadBalancer bitnami/elasticsearch

helm install kibana --set elasticsearch.hosts[0]=http://elasticsearch-elasticsearch-coordinating-only --set elasticsearch.port=9200 bitnami/kibana
```

The service name (elasticsearch-elasticsearch-coordinating-only) I took it by executing: 

```
kubectl get service
NAME                                                                TYPE                CLUSTER-IP      EXTERNAL-IP     ...
elasticsearch-elasticsearch-coordinating-only   LoadBalancer   10.245.186.51    MY_IP ...
```

Since it failed I also tried by setting the IP instead of the service name (but it leads to the exact same Readiness Probe error)

`helm install kibana --set elasticsearch.hosts[0]=http://MY_IP --set elasticsearch.port=9200 bitnami/kibana`

**Expected behavior**
I was expecting Kibana to spin up and being connected to my ES cluster instance, instead of getting a readiness probe issue.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T18:56:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I'm running a Kubernetes cluster on DigitalOcean. 7 nodes, 4GB RAM each.

**Comment by alemorcuq** [comment]
Hi, @mazzespazze.

Please, remove the `http` from the host:

```
helm install kibana --set elasticsearch.hosts[0]=elasticsearch-elasticsearch-coordinating-only --set elasticsearch.port=9200 bitnami/kibana
```

That should work.

**Comment by mazzespazze** [comment]
@alemorcuq and that was it. Thousand thanks! Now it feels such a silly issue...

I have a follow up question though, feel free to open a new "issue" if you feel it is not related at all and it is not a bug.

I would like to *protect* my ES LoadBalancer with a password, since now anyone could potentially access the IP and add and delete indexes. Looking a bitnami/elasticsearch and https://github.com/bitnami/charts/tree/master/bitnami/common there are many variables, but nothing really shines up to me. 

Do you have a documentation written anywhere to address this problem? Or a snippet of code? 

If I remember correctly with the official "quickstart" from https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html you get an endpoint that is protected by password. But it seems that there is "implicit". 

Thanks again for any help

**Comment by alemorcuq** [comment]
Unfortunately, due to licensing issues we can't ship X-Pack in our charts. A common way of protecting Elasticsearch without X-Pack is to set up and Apache proxy with HTTP authentication that will forward the requests to Elasticsearch.
