### ISSUE TITLE
Kubernetes OwnCloud Certificate

### ISSUE THREAD

**Issue by lipere123** [bitnami/charts#5554]
Hello:
This post come from :
https://community.bitnami.com/t/kubernetes-owncloud-certificate/92185

It is for this chart :
https://hub.kubeapps.com/charts/bitnami/owncloud

**Describe the bug**
I have done the quick and easy install command line.
Now I want to generate a let-encrypt certificate for it.
There is no internal command in the container for doing it and the port is 8443, which is not good for certbot.
I also I am pretty dumb when it come to certificate.

**To Reproduce** ==> Here what I did

helm install bitnami/owncloud --version 10.2.1 --generate-name
NAME: owncloud-1613357
LAST DEPLOYED: Mon Feb 15 02:53:34 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
###############################################################################
###############################################################################

This deployment will be incomplete until you configure ownCloud with a resolvable
host. To configure ownCloud with the URL of your service:

1. Get the ownCloud URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w owncloud-1613357'

  export APP_HOST=$(kubectl get svc --namespace default owncloud-1613357 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  export APP_PASSWORD=$(kubectl get secret --namespace default owncloud-1613357-o jsonpath="{.data.owncloud-password}" | base64 --decode)
  export DATABASE_ROOT_PASSWORD=$(kubectl get secret --namespace default owncloud-1613357-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
  export APP_DATABASE_PASSWORD=$(kubectl get secret --namespace default owncloud-1613357-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)

2. Complete your ownCloud deployment by running:

  helm upgrade owncloud-1613357 bitnami/owncloud \
    --set owncloudHost=$APP_HOST,owncloudPassword=$APP_PASSWORD,mariadb.auth.rootPassword=$DATABASE_ROOT_PASSWORD,mariadb.auth.password=$APP_DATABASE_PASSWORD

PS : I just scramble a bit the number 1613357 for this post.

**Comment by miguelaeh** [comment]
Hi @lipere123 ,
Are you just trying to serve the request over `https`? Did you consider using Ingress?

**Comment by lipere123** [comment]
Hello.
Thanks for your reply.

Frankly, I use metallb with the internet IP directly for accessing my service.
Witch mean I have a VPS like system and I like to keep that way please.
As it is, I can build sort of 16 VPS with kubernetes for less then 1€ per VPS, each with it own internet IP.

So, no, I am not considering Ingress, what I do need it the methodology for working directly on the chart a apply a new let-ecrypt certificate every one-two week.
I also like to keep the 8443 port.
Frankly it is working well as it is, I just need to improve the certificate side.
Right I have no probelm except change the self certificate to a let-encrypt one at regular interval.

Thanks by advance.
Best Regards.
Benjamin.

**Comment by miguelaeh** [comment]
Hi @lipere123 ,
In that case, I think that a possible solution would be to mount the certificates as a volume, then mount that volume in the OwnCloud certificate directory but also in a sidecar container that would be in charge of updating the certificate.
Would it fit your case?

**Comment by lipere123** [comment]
Hello.
Thanks for your answer.
To late, I did rebuild my OwnCloud chart from a docker-compose.yml and kompose then install OwnCloud myself via Ansible.
So now I have the certificate.

One suggestion, perhaps :
==> Make things obvious, easy, and very automated.
Because, now, that I have Kompose, I am going to use it for all my services. (^^)
It is that easy for me, but yes much more work.

Thanks by advance.
Best Regards.
Benjamin.
