### ISSUE TITLE
[bitnami/grafana-operator] grafana.adminPassword being ignored

### ISSUE THREAD

**Issue by vassie79** [bitnami/charts#5560]
**Which chart**:
bitnami/grafana-operator

**Describe the bug**
The `grafana.adminPassword` field is being ignored, I have set a custom password in clear text but it still generates a random password

**To Reproduce**

1. Set `grafana.adminPassword` to a custom password
2. Deploy to cluster
3. Custom password is ignored and I have to inspect the secret

**Expected behavior**
I expect `admin` to accept my custom password when accessing Grafana

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
N/A

**Comment by miguelaeh** [comment]
Hi @vassie79 ,
Are you setting it in the first Helm install or in an upgrade?

**Comment by vassie79** [comment]
@miguelaeh Yes, this is fresh install and I have set the following in `values.yaml`

```
  ## Grafana admin username
  ## Ref: https://github.com/bitnami/charts/blob/master/bitnami/grafana-operator/crds/grafanas.yaml#L40
  ##
  adminUsername:

  ## Grafana admin password (plain text)
  ## Ref: https://github.com/bitnami/charts/blob/master/bitnami/grafana-operator/crds/grafanas.yaml#L43
  ##
  adminPassword: test-password
```

Upon deployment `test-password` does not work and I have to inspect the secret

**Comment by miguelaeh** [comment]
Hi @vassie79 ,
Not sure where did you find those parameters, maybe an old version of the chart? The admin section should be like this one: https://github.com/bitnami/charts/blob/5e600624c066378c5fc6393348894f2a0ebfda7d/bitnami/grafana/values.yaml#L57
So you should use 
```
admin: 
  ...
   password: xxx
```

**Comment by vassie79** [comment]
@miguelaeh Those setting are for `bitnami/grafana`, I'm using `bitnami/grafana-operator`

**Comment by miguelaeh** [comment]
Hi @vassie79 ,
Sorry for my confusion. I have checked the Grafana operator, and I am able to reproduce the issue. Nevetheless, checking the CRDs code it seems to be set properly. And from the upstream operator I can see it is set in the same way: https://github.com/integr8ly/grafana-operator/blob/dd8e55750558061224dae7c52e39fde314ad13c3/deploy/crds/Grafana.yaml#L43
We would need to check this in deeper, I will open an internal task to check if it is an error in the operator code or on our Helm Chart.

**Comment by migruiz4** [comment]
Hi @vassie79,

To configure Grafana's admin user and password, you should use instead `grafana.config.security.admin_user` and `grafana.config.security.admin_user`.

The values `grafana.adminPassword` and `grafana.adminUser` seem to be a typo in the grafana-exporter CRD and do not work as expected.

More information can be found here: #5661

Thank you for reporting this issue.
