### ISSUE TITLE
[Bitnami/prestashop] container down after a back office modification

### ISSUE THREAD

**Issue by Balde-ak47** [bitnami/charts#5561]
**Which chart**:
bitnami/prestashop

**Describe the bug**
The bug is when i am in the back office. And change the default configuration. like the language or currenty and clic on save the container is down.

**To Reproduce**

1. Go to 'back office'
2. Click on 'international'
3. Click on 'localization'
4. import a new language- currency.
4. Scroll down to 'configuration'
5. change the values
6. Save

**Expected behavior**
[Sun Feb 14 18:32:24.205334 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.3.26 configured -- resuming normal operations
[Sun Feb 14 18:32:24.205381 2021] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
135.125.93.148 - - [14/Feb/2021:18:32:56 +0000] "GET /login HTTP/1.1" 404 36960
135.125.93.148 - - [14/Feb/2021:18:33:01 +0000] "GET /login HTTP/1.1" 404 36960
135.125.93.148 - - [14/Feb/2021:18:33:06 +0000] "GET /login HTTP/1.1" 404 36960

**helm version**
`version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

**kubectl version** 
`Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Balde-ak47** [comment]
After clicking on save, the container are not working and my web site is down too.

**Comment by Balde-ak47** [comment]
**A kubectl describe pod <pod name> give me this :**

Name:         my-realase-prestashop-764fb9dd64-wr2k7
Namespace:    default
Priority:     0
Node:         nodepool***************************
Start Time:   Fri, 19 Feb 2021 13:48:28 +0100
Labels:       app.kubernetes.io/instance=my-realase
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=prestashop
              helm.sh/chart=prestashop-13.1.0
              pod-template-hash=764fb9dd64
Annotations:  cni.projectcalico.org/podIP: 10.2.3.58/32
              prometheus.io/port: 9117
              prometheus.io/scrape: true
Status:       Running
IP:           10.2.3.58
IPs:
  IP:           10.2.3.58
Controlled By:  ReplicaSet/my-realase-prestashop-764fb9dd64
Containers:
  my-realase-prestashop:
    Container ID:   **********************************************************************
    Image:          docker.io/bitnami/prestashop:1.7.7-1-debian-10-r0
    Image ID:       docker-pullable://bitnami/prestashop
    Ports:          8080/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 19 Feb 2021 13:48:44 +0100
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      300m
      memory:   512Mi
    Liveness:   http-get http://:http/login delay=600s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/login delay=30s timeout=3s period=5s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                    false
      ALLOW_EMPTY_PASSWORD:             yes
      APACHE_HTTP_PORT_NUMBER:          8080
      APACHE_HTTPS_PORT_NUMBER:         8443
      PRESTASHOP_COOKIE_CHECK_IP:       no
      PRESTASHOP_COUNTRY:               us
      PRESTASHOP_LANGUAGE:              en
      PRESTASHOP_DATABASE_HOST:         my-realase-mariadb
      PRESTASHOP_DATABASE_PORT_NUMBER:  3306
      PRESTASHOP_DATABASE_NAME:         bitnami_prestashop
      PRESTASHOP_DATABASE_USER:         bn_prestashop
      PRESTASHOP_DATABASE_PASSWORD:     <set to the key 'mariadb-password' in secret 'my-realase-mariadb'>  Optional: false
      PRESTASHOP_SKIP_BOOTSTRAP:        no
      PRESTASHOP_HOST:                  ************
      PRESTASHOP_USERNAME:              user@example.com
      PRESTASHOP_PASSWORD:              <set to the key 'prestashop-password' in secret 'my-realase-prestashop'>  Optional: false
      PRESTASHOP_EMAIL:                 user@example.com
      PRESTASHOP_FIRST_NAME:            Bitnami
      PRESTASHOP_LAST_NAME:             User
    Mounts:
      /bitnami/prestashop from prestashop-data (rw,path="prestashop")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6s6zt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  prestashop-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-realase-prestashop-prestashop
    ReadOnly:   false
  default-token-6s6zt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6s6zt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Normal   Scheduled               4m33s                  default-scheduler        Successfully assigned default/my-realase-prestashop-764fb9dd64-wr2k7 to nodepool-fceff3ff-1706-49ed-b0-node-1e9b8d
  Normal   SuccessfulAttachVolume  4m30s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "ovh-managed-kubernetes-e4fzdm-pvc-3a4c3a3b-24d5-4fc1-9ea3-e88b58f0ac42"
  Normal   Pulling                 4m19s                  kubelet                  Pulling image "docker.io/bitnami/prestashop:1.7.7-1-debian-10-r0"
  Normal   Pulled                  4m18s                  kubelet                  Successfully pulled image "docker.io/bitnami/prestashop:1.7.7-1-debian-10-r0" in 1.139741599s
  Normal   Created                 4m18s                  kubelet                  Created container my-realase-prestashop
  Normal   Started                 4m18s                  kubelet                  Started container my-realase-prestashop
  Warning  Unhealthy               3m11s (x8 over 3m46s)  kubelet                  Readiness probe failed: Get "http://10.2.3.58:8080/login": dial tcp 10.2.3.58:8080: connect: connection refused
  Warning  Unhealthy               3m3s                   kubelet                  Readiness probe failed: Get "http://10.2.3.58:8080/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy               26s (x12 over 79s)     kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 404

**Comment by alemorcuq** [comment]
Hi, @Balde-ak47.

Which version of the chart are you using? Which values did you use to install it?

**Comment by Balde-ak47** [comment]
I used the default one. And I change some values like the language and country I put "fr" for France. But always the same problem.

**Comment by Balde-ak47** [comment]
I solve it by doing
helm upgrade <release-name> bitnami/prestashop --set livenessProbe.enabled=false --set readinessProbe.enabled=false

**Comment by alemorcuq** [comment]
Nice to hear that, @Balde-ak47! It's possible that you need to fine tune those probes so that they work correctly in your environment.
