### ISSUE TITLE
Deploying a new MariaDB Slave (Secondary instance) in a different Kubernetes cluster

### ISSUE THREAD

**Issue by bogdan-ionescu** [bitnami/charts#5562]
I'm trying to configure a geo-distributed system in which the writes always go to a master MariaDB node, but more slaves can be deployed when needed to different data centers across the globe, for improved read performance. Some replication latency is acceptable, as long as the reads are fast.

I've successfully deployed a master-slave configuration with the default settings to one Kubernetes cluster, but now I'm trying to deploy one more slave to a different cluster and connect it the the master. I expect I will need to configure the master's public IP into the slave, however, I could not easily find how to do this.

Which file should I be looking into?
Also, what would be a good approach to manage any custom configuration files that I might need, without diverging too much from the standard Bitnami MariaDB package?

**Comment by Mauraza** [comment]
Hi @bogdan-ionescu,

Sorry, right now is something we don't support in our chats and there isn't a plan to work it anytime soon. 
Maybe you can try this as you already have a full deploy master-slave configuration, now you can deploy a slave with deployment or statefulset indicate the values of the master (https://github.com/bitnami/bitnami-docker-mariadb#setting-up-a-replication-cluster) and check that the master can communicate with the slave.
