### ISSUE TITLE
[bitnami/wordpress] Updating wordpressExtraConfigContent  with helm upgrade isn't saved

### ISSUE THREAD

**Issue by 98christianp** [bitnami/charts#5563]
**Which chart**:
The name (and version) of the affected chart

* name: bitnami/wordpress
* version 10.6.7

**Describe the bug**
Adding to the `wordpressExtraConfigContent` works during helm install but not when doing upgrades

**To Reproduce**

1. run helm install with the production values.yaml 

2. Add something to `wordpressExtraConfigContent`

3. do a `helm upgrade`

   

**Expected behavior**

I want to update the wp-config.php file after the first install using a helm upgrade command. I would expect that the changes would be reflected in the configuration file, but it is not.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+IKS", GitCommit:"7801b1132095b75d52104472f21cc27406e00724", GitTreeState:"clean", BuildDate:"2021-01-15T06:20:15Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by juan131** [comment]
Hi @98christianp 

Thanks so much for opening this issue!

The `wp-config.php` file is generated during the 1st boot of the WP container based on the environment variables you set. Once it's created, it's persisted in the volume attached to WP containers along with the WP data saved under the `wp-content` directory.

After that, every-time the container is restarted or recreated (which is the case of doing a `helm upgrade`), the container is able to detect that there's persisted data and it reuses it. So, the behaviour you experienced it's expected.

To introduce changes in the **wp-config.php** after the 1st initialisation you'll have to access the WP container and manually edit it. I agree there's room for improvement in this development experience.

**Comment by 98christianp** [comment]
Hi @juan131,

Thank you for the reply, that makes total sense.
