### ISSUE TITLE
[elasticsearch] Not creating different data/master node folders in Persistence Volume

### ISSUE THREAD

**Issue by Sharathmk99** [bitnami/charts#5567]
**Which chart**:
Chart: `elasticsearch`
Version: `12.6.1`

**Describe the bug**
Trying to create elasticsearch chart with 2 master node and 3 data node with Azure File Share as Persistence Volume. 
helm command: 
`helm install elk bitnami/elasticsearch --set master.replicas=2,coordinating.service.type=ClusterIP,data.replicas=3,master.persistence.existingClaim=persistent-volume-elk-master-claim,master.persistence.size=8Gi,data.persistence.existingClaim=persistent-volume-elk-data-claim,data.persistence.size=16Gi`

Status of pods
`kubectl get pods -n elk`
```
NAME                                                   READY   STATUS             RESTARTS   AGE
elk-elasticsearch-coordinating-only-569d4c777c-2c4bk   1/1     Running            0          4m11s
elk-elasticsearch-coordinating-only-569d4c777c-dbgfr   1/1     Running            0          4m12s
elk-elasticsearch-data-0                               1/1     Running            0          4m11s
elk-elasticsearch-data-1                               1/1     Running            0          4m11s
elk-elasticsearch-data-2                               1/1     Running            0          4m11s
elk-elasticsearch-master-0                             1/1     Running            1          4m11s
elk-elasticsearch-master-1                             0/1     CrashLoopBackOff   3          4m11s
```
Master-0 is running fine. But master-1 is failing. 
Master-0 error,
`Caused by: java.nio.file.NoSuchFileException: /bitnami/elasticsearch/data/nodes/0/_state/segments_2n`

Data node also has errors,
`can't add node {elk-elasticsearch-data-1}{V32X0SBrS5Kb5D74BjxKLw}{K4iHbDsjSMaMvkGidyZ88g}{10.244.3.81}{10.244.3.81:9300}{dr}, found existing node {elk-elasticsearch-data-2}{V32X0SBrS5Kb5D74BjxKLw}{X6nCGLenTLKMIx59soJeTg}{10.244.0.73}{10.244.0.73:9300}{dr} with the same id but is a different node instance`

When i check the Azure File Share, i can see only one folder("0") under "nodes" folder. Both in master and data File share i can see only one folder "0" under "nodes". Based on my understanding, it has to create folders for every node/pod.

**To Reproduce**

helm command: 
`helm install elk bitnami/elasticsearch --set master.replicas=2,coordinating.service.type=ClusterIP,data.replicas=3,master.persistence.existingClaim=persistent-volume-elk-master-claim,master.persistence.size=8Gi,data.persistence.existingClaim=persistent-volume-elk-data-claim,data.persistence.size=16Gi`

**Expected behavior**
Should create multiple folders under "nodes" folder.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-
09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-
22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by alemorcuq** [comment]
Do you see any errors when describing the pod?

```
kubectl describe po elk-elasticsearch-master-1   
```

**Comment by andysousa** [comment]
@Sharathmk99 any chance you ever got this resolved? I am having the same issue.  I am using Azure file share with a single RWX claim.  The data nodes keep failing with the same error

**Comment by javsalgar** [comment]
Hi,

Which is the exact error that you see?
