### ISSUE TITLE
[Airflow] k8s executor fails to spin up worker pods due to timeout to web service

### ISSUE THREAD

**Issue by tseruga** [bitnami/charts#5569]
**Which chart**:
airflow-8.0.4

**Describe the bug**
When using the KubernetesExecutor, worker pods fail to initialize due to a timeout from `k8s-executor-init-config` failing to reach the airflow web service.

Logs from the `k8s-executor-init-config` service:
```
  nami    INFO  Initializing airflow-worker                                                                                                                                          
  airflow INFO  ==> No injected configuration files found. Creating default config file...                                                                                           
  airflow INFO  ==> Configuring Airflow database...                                                                                                                                  
  airflow INFO  ==> Setting Airflow Fernet key...                                                                                                                                    
  airflow INFO  ==> Deploying Airflow from scratch...                                                                                                                                
  postgre INFO  Trying to connect to PostgreSQL server                                                                                                                               
  postgre INFO  Found PostgreSQL server listening at mini-af-postgresql:5432                                                                                                       
  postgre INFO  PostgreSQL server listening and working at mini-af-postgresql:5432                                                                                                 
  airflow INFO  ==> Waiting for Airflow Webserver host...                                                                                                                            
  Error executing 'postInstallation': Failed to connect to airflow:8080 after 36 tries                                                                                               
  stream closed
```

This is running on minikube, k8s v1.20.2.

**To Reproduce**

1. Create yaml file to enable K8s executor, per readme on this repo:
```
executor: KubernetesExecutor

redis:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true
```
2.  `helm install mini-af -f values.yaml bitnami/airflow`
3. Run a DAG
4. Observe the worker pods fail to initialize

**Expected behavior**
Worker pods should be able to connect to web server and finish their initialization

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by don4of4** [comment]
This is interesting.  I also am seeing this config fail, but for a different reason:
```

*** Trying to get logs (last 100 lines) from worker pod  ***

*** Unable to fetch logs from worker pod  ***
(403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '7f57b952-c4c6-41ad-bc4d-54909d875272', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 22 Feb 2021 00:05:48 GMT', 'Content-Length': '290'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:default:dna-airflow\\" cannot list resource \\"pods/log\\" in API group \\"\\" in the namespace \\"default\\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n'

```

**Comment by juan131** [comment]
Hi @don4of4 @tseruga 

Could you please share al the changes you introduced in your **values.yaml**?
- Did you install any custom plugin in Airflow (see [loading custom plugins](https://github.com/bitnami/charts/tree/master/bitnami/airflow#loading-plugins))? 
- Are you using the default `pod_template.yaml` or did you set the `worker.podTemplate` parameter to customize it?

**Comment by don4of4** [comment]
No I am not doing either, the above configuration in the original request captures the settings.   

This may be related:
https://github.com/bitnami/charts/issues/5413

**Comment by tseruga** [comment]
Using the default pod_template, and the only other settings in my `values.yaml` were related to git sync.

**Comment by don4of4** [comment]
Based on https://github.com/apache/airflow/issues/14266 I think we may need to look at the container definition for the webserver -- there might be something amiss. 

I am on ` repository: bitnami/airflow tag: 2.0.1-debian-10-r4`, and tried to go to r14, but looks like that image didn't make it to the azure helm repo.  _I am surprised since the helm chart has the repo param in there, but it doesn't appear to work._

@tseruga  what web container image are you using?

**Comment by juan131** [comment]
There's definitely something wrong here with the latest version of `bitnami/airflow` and the `KubernetesExecutor` executor. I'll open an internal task to properly investigate this.

I'll keep you updated about our progress./

**Comment by mukubi01** [comment]
Facing the same issue as @don4of4. Stuck and not able to make progress on our project. Hopefully to get a resolution or path forward from thorough this thread.

**Comment by juan131** [comment]
I'll try to increase the priority of the associated task so we can have a solution available as soon as possible, but I'm afraid I cannot provide you any ETA

**Comment by cris-b** [comment]
i managed to work around this by adding:

airflow:
  worker:
    extraEnvVars:
    - name: AIRFLOW_WEBSERVER_HOST
      value: "{{ include \"common.names.fullname\" . }}"
    - name: AIRFLOW_WEBSERVER_PORT_NUMBER
      value: "{{ .Values.service.port }}"


to the values.yaml.  It seems its missing setting these for the init container, leaving the container default of airflow:8080

**Comment by juan131** [comment]
cc @migruiz4

**Comment by migruiz4** [comment]
Hi @cris-b ,

Thank you very much for sharing your solution. Indeed the variables `AIRFLOW_WEBSERVER_HOST` and `AIRFLOW_WEBSERVER_PORT_NUMBER`, causing the worker pods to get stuck with the status 'Init:Error'.

I have created this PR fixing this issue: #5722
