### ISSUE TITLE
Request to support the `portName` field on both AlertManager and Prometheus

### ISSUE THREAD

**Issue by petersin0422** [bitnami/charts#5571]
**Which chart**:
Name: kube-prometheus
Version: 2.2.1

**Is your feature request related to a problem? Please describe.**
The chart currently will create both `Prometheus` and `AlertManager` with the default `portName`, which defaults to `web`, resulting in two kubernetes service objects using the same port but different port name (**for example, a `ClusterIP` service with `TCP/9090 = http` and a `Headless` service with the same port called `web`**). This is causing issue with the Istio Envoy sidecar. I have manually patch the `Prometheus` and `AlertManager` object afterward to match the port name and problem is resolved.

**Describe the solution you'd like**
Addition of `alertmanager.portName` and `prometheus.portName`

**Describe alternatives you've considered**
Manual patching the objects after deployment. Not elegant but it works for now.

**Comment by miguelaeh** [comment]
Thank you very much for the PR!
We will take care of it!
