### ISSUE TITLE
Request to support the `routePrefix` field on AlertManager

### ISSUE THREAD

**Issue by petersin0422** [bitnami/charts#5572]
**Which chart**:
Name: kube-prometheus
Version: 2.2.1

**Is your feature request related to a problem? Please describe.**
I was trying to expose `AlertManager` via an Istio ingress gateway using a sub path, but I notice `alertmanager.routePrefix` isn't supported today. Even though it is a supported option for `Prometheus`.

**Describe the solution you'd like**
Addition of `alertmanager.routePrefix`

**Describe alternatives you've considered**
Manually patching the object after deployment.

**Comment by alemorcuq** [comment]
Thanks for opening a PR!
