### ISSUE TITLE
[bitnami/kube-prometheus] Prometheus Operator Reloader image weird behavior

### ISSUE THREAD

**Issue by EtienneBarbier** [bitnami/charts#5584]
**Which chart**:
kube-prometheus 4.0.1

**Describe the bug**
In file `templates/_helpers.yml` i do not understant why we have a different behavior for Prometheus Operator Reloader image name. (See below)
Why do we have this conditional on this image and not on others ?

```
{{/*
Return the proper Prometheus Operator Reloader image name
*/}}
{{- define "kube-prometheus.prometheusConfigReloader.image" -}}
{{- if and .Values.operator.prometheusConfigReloader.image.registry (and .Values.operator.prometheusConfigReloader.image.repository .Values.operator.prometheusConfigReloader.image.tag) }}
{{- include "common.images.image" (dict "imageRoot" .Values.operator.prometheusConfigReloader.image "global" .Values.global) }}
{{- else -}}
{{- include "kube-prometheus.image" . -}}
{{- end -}}
{{- end -}}

{{/*
Return the proper Prometheus Image name
*/}}
{{- define "kube-prometheus.prometheus.image" -}}
{{- include "common.images.image" (dict "imageRoot" .Values.prometheus.image "global" .Values.global) }}
{{- end -}}

{{/*
Return the proper Thanos Image name
*/}}
{{- define "kube-prometheus.prometheus.thanosImage" -}}
{{- include "common.images.image" (dict "imageRoot" .Values.prometheus.thanos.image "global" .Values.global) }}
{{- end -}}
```

**Comment by marcosbc** [comment]
Hi @EtienneBarbier, it seems to be a way to allow for non-default behavior. Refer to [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/values.yaml#L247) for more info.

```
  ## Prometheus Configmap-reload image to use for reloading configmaps
  ## defaults to Bitnami Prometheus Operator (ref: https://hub.docker.com/r/bitnami/prometheus-operator/tags/)
  ##
  prometheusConfigReloader:
    image: {}
```

If you specify a value there, then the default container image will be overridden for config reloading.

**Comment by EtienneBarbier** [comment]
Hi @marcosbc, i'm ok with thr non-default behavior.
My problem is that the default behavior is to use prometheus-operator image for prometheusConfigReloader.
Is it mean than prometheus-operator image include prometheusConfigReloader feature ?
If not, then the default behavior is wrong and should be removed. 

```
{{/*
Return the proper Prometheus Operator image name
*/}}
{{- define "kube-prometheus.image" -}}
{{- include "common.images.image" (dict "imageRoot" .Values.operator.image "global" .Values.global) }}
{{- end -}}
```

**Comment by marcosbc** [comment]
@EtienneBarbier What that will do is add the image to specify `--prometheus-config-reloader` flag when running `prometheus-operator`.

Note that when Prometheus Operator deploys the image specified by `prometheusConfigReloader.image`, [it will override the Docker image's `ENTRYPOINT` to run `/bin/prometheus-config-reloader`](https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/operator/statefulset.go#L103).

And since the `bitnami/prometheus-operator` already includes the `/bin/prometheus-config-reloader` image, it will work without problems:


```console
$ docker run -ti --entrypoint=bash bitnami/prometheus-operator -c "ls /bin/prometheus-config-reloader"
/bin/prometheus-config-reloader
```

**Comment by EtienneBarbier** [comment]
@marcosbc Thank you for this explanation, it is clear to me now :)
Il will update chart to be able to run container with default registry #5582

It will give something like this:
```
{{/*
Return the proper Prometheus Operator Reloader image name
*/}}
{{- define "kube-prometheus.prometheusConfigReloader.image" -}}
{{- if and .Values.operator.prometheusConfigReloader.image.repository .Values.operator.prometheusConfigReloader.image.tag }}
{{- include "common.images.image" (dict "imageRoot" .Values.operator.prometheusConfigReloader.image "global" .Values.global) }}
{{- else -}}
{{- include "kube-prometheus.image" . -}}
{{- end -}}
{{- end -}}
```
