### ISSUE TITLE
init sql script not working in postgresql-ha when persistence enabled and the application redeployed/upgraded

### ISSUE THREAD

**Issue by DevvG** [bitnami/charts#5588]
**Which chart**:
postgresql-ha 6.5.5

**Describe the bug**
When installing the application for the first time with persistence enabled, init db scripts works fine and creates relevant database and tables. After that modifications made in init db scripts and then the application reinstalled after deleting only application and keeping persistence volume claims or upgraded with helm upgrade command does not reflect the changes intended by the script. 

**To Reproduce**

1. Update the initdbscript in values.yaml file for postgres:
   initdbScripts:
     my_init_script.sql: |
       CREATE DATABASE mydb;
2. Install postgres-ha with persistence enabled.
3. Modify the init db cripts:
  initdbScripts:
     my_init_script.sql: |
       DROP DATABASE mydb;
4. Either delete the application keeping persistence volume claim or helm upgrade with the modified chart.
5. Check for the mydb table, it should exist despite dropping it.

**Expected behavior**
Postgres should reflect the changes which is mydb should be dropped.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+vmware.2", GitCommit:"9d9a7637ad75801f9296a1cebe63120c020305d4", GitTreeState:"clean", BuildDate:"2020-09-22T22:55:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @DevvG ,
I would say it is because the file `"$POSTGRESQL_VOLUME_DIR"/.user_scripts_initialized` exists. Try deleting that file from your volume and the scripts should be executed again in the next restart. 
If you want them to be run always you can build your custom image deleting this line from the original code: https://github.com/bitnami/bitnami-docker-postgresql/blob/20f01a4b3199035aa2b9d7d0a297678f476613f5/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L710
