### ISSUE TITLE
[bitnami/Airflow] JAVA not found

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/charts#5590]
I am trying to run bashOperator in Airflow (*.Jar file) but I got error java not found. it seems that the image doesn't have java.

**Comment by Mauraza** [comment]
Hi @raefezzeldin,

That's right, airflow doesn't have installed java. If you want java, you can create a new container using the image base `docker.io/bitnami/airflow:2-debian-10`

**Comment by raefezzeldin** [comment]
I have created a new image and I have installed Java on it.
