### ISSUE TITLE
[bitnami/redis]

### ISSUE THREAD

**Issue by kevin96666** [bitnami/charts#5594]
**Which chart**:
bitnami/redis 12.7.4 (latest)

**Describe the bug**
Warning Logs on Redis launch
 
WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128

WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').

**To Reproduce**

1. Deploy the chart in Kubernetes
2. Check Logs on Pod launch

**Comment by marcosbc** [comment]
Hi @kevin96666, that error is expected. Refer to the [README](https://github.com/bitnami/charts/tree/master/bitnami/redis#host-kernel-settings) for more info.

**Comment by kevin96666** [comment]
Hi @marcosbc thanks, but still facing an issue. After setting properly securityContext.sysctls,  I face a new issue when launching the pod : 

**forbidden sysctl: "net.core.somaxconn" not whitelisted**

Your help is highly appreciate

**Comment by marcosbc** [comment]
Hi @kevin96666, you would need to deploy kubelets via `allowed-unsafe-sysctls`, refer to [the official documentation](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls) for more info.
