### ISSUE TITLE
Ingress ressource not scheduled

### ISSUE THREAD

**Issue by julienbruitte** [bitnami/charts#5608]
**Which chart**:
nginx-controller : 0.44
**Describe the bug**
When deploying more than 5 ingress ressources, they are not consumed by the pod.

hello, on a cluster when we try to deploy more than 5 ingress ressources on one nginx controller, they are not consumed. No IP and no events.

And when we log on the pod, we can see the 5 first ressources (event.go on line 282).

Is there any limitations ?

**Comment by Mauraza** [comment]
Hi @julienbruitte 

could you add more information about this? for example the logs of the pod and where are you deploy these resources.

**Comment by julienbruitte** [comment]
Hi @Mauraza 

Thank you for your reply.

First the ingress ressources list : 

NAMESPACE  NAME                                    CLASS    HOSTS          ADDRESS          PORTS     AGE
ingress1   secretive-servant--app                  <none>   ingress1.net   IP OK   	    80, 443   47d
ingress2   various-edge-various-edge-app           <none>   ingress3.app           	    80, 443   19h
ingress3   tender2-rainstorm-tender-rainstorm-app  <none>   ingress2.app           	    80, 443   5d20h
ingress4   strange-plants-strange-plants-app       <none>   ingress4.app   IP OK            80, 443   44d
ingress5   nappy-floor--app                        <none>   admin-demo.app IP OK            80, 443   44d
ingress6   agreeable-crime-agreeable-crime-app     <none>   api-demo.app   IP OK            80, 443   44d

As you can see, the ingress2 and ingress3 does not have an IP.

Logs ingress controller : 

I0224 16:49:03.735987       1 nginx.go:254] "Starting NGINX Ingress controller"
I0224 16:49:04.843260       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"ingress1", Name:"secretive-servant--app", UID:"d462cf1a-e86d-479b-9284-464426b7dbd1", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"466522580", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0224 16:49:04.845477       1 backend_ssl.go:66] "Adding secret to local store" name="ingress1/-app-crt"
I0224 16:49:04.845635       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"ingress4", Name:"strange-plants-strange-plants-app", UID:"ebfdcc71-c0fb-48af-ac2c-b71024b145e5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"466522578", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0224 16:49:04.845876       1 backend_ssl.go:66] "Adding secret to local store" name="ingress4/letsencrypt-prod"
I0224 16:49:04.845960       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"ingress5", Name:"nappy-floor--app", UID:"8cd0a4f9-08f2-425c-8504-943411fba154", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"466522579", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0224 16:49:04.846307       1 backend_ssl.go:66] "Adding secret to local store" name="ingress5/-app-crt"
I0224 16:49:04.846624       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"ingress6", Name:"agreeable-crime-agreeable-crime-app", UID:"46756bbb-eec1-41b5-966e-79cf9acfcd23", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"466522576", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0224 16:49:04.846682       1 backend_ssl.go:66] "Adding secret to local store" name="ingress6/letsencrypt-prod"
I0224 16:49:04.846822       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"old-namespace", Name:"efficacious-governor--app", UID:"0bf7211f-3e2e-4921-9973-22e8719e2397", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"466522591", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
W0224 16:49:04.846927       1 backend_ssl.go:46] Error obtaining X.509 certificate: no object matching key "old-namespace/-app-crt" in local store
I0224 16:49:04.938178       1 nginx.go:296] "Starting NGINX process"

You can see on the log, that there is a strange behaivour : 
- The ingress 2 & 3 are not consumed before starting nginx
- An old ingress (deleted / namsepace deleted) is consumed.

Is there a reason ?

**Comment by Mauraza** [comment]
Hi @julienbruitte,

you are right it's strange could you add the `describe` of these resources, to check if there some event there?

```
kubectl describe ingress -n ingress2 various-edge-various-edge-app
kubectl describe ingress -n ingress3 tender2-rainstorm-tender-rainstorm-app
```

**Comment by julienbruitte** [comment]
Hi @julienbruitte,
`Name:            tender2-rainstorm-tender-rainstorm-app
Namespace:        ingress3
Address:          
Default backend:  default-http-backend:80 (<none>)
TLS:
  letsencrypt-prod terminates api-preppy.origami-marketplace.net
Rules:
  Host                                Path  Backends
  ----                                ----  --------
 ingress2.app  
                                      /   ttender2-rainstorm-tender-rainstorm-app:8080 (<none>)
Annotations:
  cert-manager.io/acme-challenge-type:  http01
  cert-manager.io/cluster-issuer:       letsencrypt-prod
  kubernetes.io/ingress.class:          nginx
  kubernetes.io/tls-acme:               true
  meta.helm.sh/release-name:            tender-rainstorm
  meta.helm.sh/release-namespace:       ingress3
Events:                                 <none>
`

No events, and thats the problem :)

**Comment by Mauraza** [comment]
Hi @julienbruitte, 
Did you have something different in this ingress?. all the `describe` are the same?

**Comment by julienbruitte** [comment]
@Mauraza Hello Mauraza, sorry for not answering you.
The problem was actually located on our configuration which was not in adequacy with the version of the nginx controller.
Sorry to have bothered you.

**Comment by Mauraza** [comment]
Hi @julienbruitte,

I'm glad you solve the problem, do not hesitate to write us back if you have any other issue.
