### ISSUE TITLE
[bitnami/postgresql] Installing custom modules

### ISSUE THREAD

**Issue by Pjstaab** [bitnami/charts#5610]
**Which chart**:
bitnami/postgresql 10.3.5

**Describe the bug**
Unable to install custom modules to the library folder using initdbScripts.

**To Reproduce**
Create initdbScripts to copy files to /opt/bitnami/postgresql/lib during initialization.

**Expected behavior**
Files are copied to the folder

**Version of Helm and Kubernetes**:
Helm 3.1.2
K8s 1.15.14

**Additional context**
I'm trying to setup nominatim and it requires a custom module for postgresql. The user for initdbscripts doesn't have access to the /opt/bitnami/postgresql/lib folder so the operation fails. Currently I'm making a custom image to copy it in but that seems overkill. What's the best way to install files to the lib folder?

**Comment by javsalgar** [comment]
Hi,

In principle, for security reasons, we don't allow writing in the `lib/` folder, only at build time or launching the container as root. At the moment, the recommended approach is that of building a custom image. I'm not sure how common the use case of adding modules with initscripts is. Another option that comes to mind is using the extraVolumes and extraVolumeMounts values where you can add the extra .so files in the lib folder (or even mount a `lib` folder directly). If copying modules using initscripts is a common use case, then we could evaluate it. But at the moment, I have my concerns.

**Comment by Pjstaab** [comment]
That's what I figured. I'll look at extraVolumes and extraVolumeMounts. Thanks!
