### ISSUE TITLE
[bitnami/redis-cluster] how to change default data dir - /bitnami/redis/data and enabling logs??

### ISSUE THREAD

**Issue by bharat15-ml** [bitnami/charts#5615]
**Which chart**:
bitnami/redis-cluster-4.3.1

**Describe the bug**
Want to change default persistent data dir- "/bitnami/redis/data" To "/redis/data/$HOSTNAME", so that each pod will have different persistent location based on $HOSTNAME?? 

**To Reproduce**

1. In values.yaml have made below changes in line-157
    extraEnvVars:
    -  name: REDIS_DATA_DIR
       value: /redis/data/$HOSTNAME
 
2. Installed helm chart with above changes.. 
3. Pod went into crashloopbackoff state with permission error unable to create dir- /redis/data/$HOSTNAME

**Expected behavior**
After logging to pod it should create persistent data director - /redis/data/$HOSTNAME

**Comment by marcosbc** [comment]
Hi @bharat15-ml, could you share more on your use case? Pods shouldn't be sharing the persistent directory so that's why it's not supported currently.

**Comment by bharat15-ml** [comment]
Hi @marcosbc, I wanted to run a script for each pod to take a backup of data, for that have added a extra deployment in to values.yaml, ultimately this extra deployment is  running as cronjob pod at specific interval.

Currently facing Two Problems, Pls provide your thoughts on this:-

1. cronjob pod is having a seperate persistent location to take a backup of each pod. for example- "/persistent/backup/daily/pod-0/" ; Similarly for each pod it have separate location.
Problem here is- cronjob pod not able to access source redis data directory i.e."/bitnami/redis/data"

2. Here we have source data dir path "/bitnami/redis/data"; what changes will be required to make data dir path such as "/redis/data/$HOSTNAME", So that each pod will have a seperate data location and then it will be like copying file from source location to destination (backup) location through cronjob for each pod?

Pls provide some feasible way to achieve this. Thank You!!

**Comment by marcosbc** [comment]
>1. cronjob pod is having a seperate persistent location to take a backup of each pod. for example- "/persistent/backup/daily/pod-0/" ; Similarly for each pod it have separate location.
>Problem here is- cronjob pod not able to access source redis data directory i.e."/bitnami/redis/data"

That is something more in an "operator" area, not something that is usually handled by charts.

It is not as simple, as you would first need the volume to be mounted as read-write-many. Next, you would need to create a cron-job per node which manually mounts all used volumes, for backing up. 

Alternatively, you could try and define a sidecar container for running alongside the nodes, which via a script would always be running and create the backups at the scheduled time.

>2. Here we have source data dir path "/bitnami/redis/data"; what changes will be required to make data dir path such as "/redis/data/$HOSTNAME", So that each pod will have a seperate data location and then it will be like copying file from source location to destination (backup) location through cronjob for each pod?

Couldn't you just copy the `data` directory into a directory named after the pod (or its hostname)? I.e.:

```
cp -r /bitnami/redis/data/. /redis/data/$HOSTNAME/$(date +%s)
```

That will create a backup for the specific pod into `/redis/data`, in a subfolder depending on the hostname for the pod, and in another subfolder that contains the current unix timestamp to make sure the directory is unique.

**Comment by bharat15-ml** [comment]
Thanks @marcosbc for help.  What is the way to change default redis data dir location "/bitnami/redis/data" to something else. Example- "/redis/data/$HOSTNAME"

**Comment by marcosbc** [comment]
>1. What is the way to change default redis data dir location "/bitnami/redis/data" to something else. Example- "/redis/data/$HOSTNAME"

Unfortunately it's not possible with the current chart (nor container image), currently. I'd recommend you to update your backup/restore scripts so they can backup the data directory to the proper location (find some recommendations in my previous comment).

>2. how to enable redis cluster logs - which I want to store to different persistent location other than data, for analysis purpose. tried making changes into configMap which populates redis.conf. Have made changes for value logfile: "" to logfile: /persistent/redis/logs/redis.log; but these changes not reflecting.

Redis logs are printed to the container's stdout/stderr. If you use a service like fluentd you will be able to parse them automatically.

As for the changes in Redis configuration, you could check if the `redis.conf` configuration file contains those changes. If not, it means you're not mounting the configuration file properly.

**Comment by bharat15-ml** [comment]
Hi @marcosbc, have made the changes in confignap, for logfile location-/persistent/redis/logs/redis.log and able to see the logs. 
One question here- will this logfile contains complete cluster logs or it is pod specific log with the same name; because when I have checked the size of log file (redis.log) from each pod is having different size of log file.

**Comment by bharat15-ml** [comment]
Hi @marcosbc, have made the changes in confignap, for logfile location-/persistent/redis/logs/redis.log and able to see the logs. 
One question here- will this logfile contains complete cluster logs or it is pod specific log with the same name; because when I have checked the size of log file (redis.log) from each pod is having different size of log file.

**Comment by marcosbc** [comment]
> One question here- will this logfile contains complete cluster logs or it is pod specific log? (Because on configmap at only one place I did this change logfile /persistent/redis/logs/redis.log).

Each Redis node will show its own logs (that is, that redis.log will include pod-specific logs).

>Other thing is when I have checked the size of log file (redis.log) from each pod is having different size of log file. Why so??

Like mentioned earlier, the log file is not shared between the nodes, because each redis.log includes the logs of the specific Redis node.

**Comment by bharat15-ml** [comment]
Thanks @marcosbc, for your patience guide and feedback, I am new to redis and helm chart, exploring, understanding and on learning path.
