### ISSUE TITLE
Bitnami/rabbitmq not displaying metrics on RabbitMQ-Overview dashboard

### ISSUE THREAD

**Issue by amin224** [bitnami/charts#5617]
**Which chart**:
helm install my-release bitnami/rabbitmq

**Describe the bug**
I have a working bitnami/rabbitmq server working on my Kubernetes cluster but the graphs displayed on Grafana are not enough, I found this dashboard [RabbitMQ-Overview](https://grafana.com/grafana/dashboards/10991) which has sufficient details that can be very useful for my bitnami/rabbitmq server but unfortunately there is no data showing on the dashboard. The issue here is I cannot see my metrics on this dashboard, can someone please suggest a work-around approach for my case. Please note I am using the kube-prometheus-stack helm chart for Prometheus+Grafana services.

**To Reproduce**
1. I enabled the rabbitmq_prometheus for all my rabbitmq nodes by entering the Pods
`rabbitmq-plugins enable rabbitmq_prometheus`
**Output:**
:/$ rabbitmq-plugins list
Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@rabbitmq-0.broker-server
 |/
[E*] rabbitmq_management               3.8.9
[e*] rabbitmq_management_agent         3.8.9
[  ] rabbitmq_mqtt                     3.8.9
[e*] rabbitmq_peer_discovery_common    3.8.9
[E*] rabbitmq_peer_discovery_k8s       3.8.9
[E*] rabbitmq_prometheus               3.8.9

2. Made sure I was using the same data source for prometheus used in my grafana

3. I tried creating a prometheus-rabbitmq-exporter to get the metrics from rabbitmq and send them to RabbitMQ-Overview dashboard but no data was displayed.

**Expected behavior**
I expected to have my RabbitMQ metrics displayed on this dashboard
![image](https://user-images.githubusercontent.com/57595423/109172436-701c6280-778b-11eb-9ee2-2f045db4a156.png)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version --short`:

```
Client Version: v1.19.4
Server Version: v1.18.9-eks-d1
```

**Comment by carrodher** [comment]
There is a metrics exporter already bundled in the RabbitMQ Helm Chart, but it is not enabled by default, you need to manually enable and configure it, for that, you can take a look at [this section in the README](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#metrics-parameters) where the different parameters are listed. In the same way, you can have more info by directly looking at the values.yaml, see https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L803

**Comment by amin224** [comment]
@carrodher The RabbitMQ Overview dashboard works by getting metrics from the rabbitmq_prometheus plugin, after deploying my servers I enabled that plugin by entering to each pod and typing `rabbitmq-plugin enable rabbitmq_prometheus` but there are no data in the dashboard. I think the plugin did not work while running, I will try to restart the helm chart with rabbitmq_prometheus plugin enabled.

**Comment by amin224** [comment]
@carrodher Please note that I re-installed a fresh installation for helm chart with this command. Can you please suggest any ideas to fix this issue. I noticed that there was no ServiceMonitor or PodMonitor created which is supposed to enable the Prometheus target on the RabbitMQ Pod or is it not needed.

`helm install -f values.yml broker bitnami/rabbitmq --namespace default --set nodeSelector.test=rabbit --set volumePermissions.enabled=true --set livenessProbe.enabled=false --set readinessProbe.enabled=false --set replicaCount=1 --set metrics.enabled=true`

values.yml:

```
## Plugins to enable
##
plugins: 'rabbitmq_management rabbitmq_prometheus rabbitmq_tracing
  rabbitmq_event_exchange
  rabbitmq_top rabbitmq_peer_discovery_k8s'

## Community plugins to download during container initialization.
## Combine it with extraPlugins to also enable them.
##
communityPlugins: |
  https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.8.9/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez

## Extra plugins to enable
## Use this instead of `plugins` to add new pluginsmv ra  
##
extraPlugins: |
  rabbitmq_auth_backend_ldap 
  rabbitmq_delayed_message_exchange
```

But the outcome is still no data on the RabbitMQ Overview dashboard
![image](https://user-images.githubusercontent.com/57595423/109527653-92302080-7abc-11eb-9c24-8f1b747f0b42.png)

**Comment by amin224** [comment]
Data showing after including this command `--set metrics.serviceMonitor.enabled=true`

> [this section in the README](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#metrics-parameters)

Thank you @carrodher for the reference.

**Comment by sarasensible** [comment]
I also had to add a release label for prometheus as documented in https://stackoverflow.com/questions/66383251/rabbitmq-overview-dashboard-no-metrics-data-shown.  

This can be added in the helm like so:

```
metrics:
  serviceMonitor:
    labels:
      release: prometheus
```
