### ISSUE TITLE
Multiple external-dns releases in separate namespaces conflict

### ISSUE THREAD

**Issue by pentago** [bitnami/charts#5624]
Installing of multiple `external-dns` releases in separate namespaces conflicts because both releases require `ClusterRole` to function properly (_I have no luck making Clouflare and Gogole CloudDNS to work on GKE without RBAC_).

I tried even making the proper ordering by installing one release with ClusterRole enabled and second one (_in other namespace_) with ClusterRole disabled, needles to say, second release didn't work as it jus fails to update DNS and pod start restarting.

If I enable CLusterRole and RBC on both releases, I get this message when installing second release:
```
Release "external-dns" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "external-dns" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "external-dns-google": current value is "external-dns-cloudflare"
```

At this point, I'm clueless on how it's possible to have multiple `external-dns` releases running at the same time in a single cluster. Any ideas/suggestions?

Thanks in advance!

**Comment by Mauraza** [comment]
Hi @pentago, 

Are you using the same name to deploy in both `external-dns` in different namespaces? 
If you using differents namespaces to deploy there shouldn't be any problem.

**Comment by pentago** [comment]
Hi @Mauraza,

Godamn, how I didn't think of that earlier :D
I reinstalled charts, each with a different name and it works now.

Thanks a ton!
