### ISSUE TITLE
Keycloak missing schema environment variable / configuration

### ISSUE THREAD

**Issue by doctorpangloss** [bitnami/charts#5626]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/keycloak
All versions
**Describe the bug**
Cannot set `DB_SCHEMA`.

**To Reproduce**
 1. Try to set the `DB_SCHEMA` environment variable or add the appropriate configuration to all three `xml` files.
 2. Observe the schema is not used.

**Expected behavior**
Use the specified schema as the upstream keycloak image does.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by marcosbc** [comment]
Hi @doctorpangloss, currently the Bitnami Docker image for Keycloak does not support that environment variable, as it's from the [official](https://github.com/keycloak/keycloak-containers/) Docker image.

It seems like adding support for it would only require you to modify [L105 of `libkeycloak.sh`](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/12/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh#L105). Would you be up for contributing a PR to add support for this environment variable?

**Comment by andresbono** [comment]
Hi @doctorpangloss, a new version of the `bitnami/keycloak` container image was released including the changes from your PR. The chart was also updated. Please check the `2.2.3` version:

- Container: https://github.com/bitnami/bitnami-docker-keycloak/commit/925665cc7a5589c636be6f5e44335ddd4b0f0461
- Chart: https://github.com/bitnami/charts/commit/dc58d7f586f4b9a2a949a6dc413ba932c594ef9a
