### ISSUE TITLE
Document generation methods

### ISSUE THREAD

**Issue by SiegfredRodriguez** [bitnami/charts#5628]
This is more of question, I am trying to generate documentation for my charts, and your charts are wonderfully documented.
I have tried Frigate for that, and i ran into a few limitations here and there.

TLDR; What is your documentation generation method and tools? Generating values.yaml documentation in particular.

**Comment by alemorcuq** [comment]
Hi, @SiegfredRodriguez. At the moment everything is manual, but we are working on adding some metadata to the `values.yaml` files so that we can generate the documentation for them.

**Comment by SiegfredRodriguez** [comment]
i couldn't believe it is manual, thanks.
