### ISSUE TITLE
blockdev configuration für Cassandra Helm Charts

### ISSUE THREAD

**Issue by mehmetsalgar** [bitnami/charts#5636]
**Which chart**:
Cassandra Charts

**Is your feature request related to a problem? Please describe.**
We are trying to bring our current Cassandra Production environment to Cloud and I am experimenting with Bitnmai Charts. Our current Cassandra Cluster is really sensitive to 'Read Ahead' configurationen für Storage and requires specific values to be set with blockdev. I could not find any mechanism in Cassandra Helm charts to set read ahead value for underlying Linux Image. I can't even see what is the actually in the image because the image is configured to run Cassandra on a non root user, so I don't have admin user to ask the system the current values or to modifiy those.

**Describe the solution you'd like**
A possiblity to set the 'blockdev - read ahead' value with an environment variable or modifiy the initcontainer to do that.

**Describe alternatives you've considered**
I  can't see an alternative way to do this.

**Comment by mehmetsalgar** [comment]
Hi,

you can read the concepts of the read ahead here....

[Cassandra Read Ahead](https://cassandra.apache.org/doc/latest/getting_started/production.html)

> Read Ahead
>Read ahead is an operating system feature that attempts to keep as much data loaded in the page cache as possible. The goal >is to decrease latency by using additional throughput on reads where the latency penalty is high due to seek times on spinning >disks. By leveraging read ahead, the OS can pull additional data into memory without the cost of additional seeks. This works >well when available RAM is greater than the size of the hot dataset, but can be problematic when the hot dataset is much >larger than available RAM. The benefit of read ahead decreases as the size of your hot dataset gets bigger in proportion to >available memory.
>
>With small partitions (usually tables with no partition key, but not limited to this case) and solid state drives, read ahead can >increase disk usage without any of the latency benefits, and in some cases can result in up to a 5x latency and throughput 
>performance penalty. Read heavy, key/value tables with small (under 1KB) rows are especially prone to this problem.

>We recommend the following read ahead settings:
>Hardware | Initial Recommendation
>-- | --
>Spinning Disks | 64KB
>SSD | 4KB
>
>Read ahead can be adjusted on Linux systems by using the blockdev tool.
>
>For example, we can set read ahead of ``/dev/sda1` to 4KB by doing the following:
>
>blockdev --setra 8 /dev/sda1
>Note: blockdev accepts the number of 512 byte sectors to read ahead. The argument of 8 above is equivilent to 4KB.

For ex, in our Linux distribution, out of the box value for Read Ahead was 256KB and we were using SSDs, hte consequence was, Cassandra try to load the data, it tought we will need but we didn't and it throwed it directly away but that cause lots of strain on the IO.

I look to the Docker Image, but they are quite complex and I could not find a direct way to configure that, the easiest way seems to me to manipulate the initContainer in the Helm Chart and use the command

`blockdev --setra 8 /dev/sda1`

Naturally 8 must be a configurable value on the Helm Chart and I guess it should be set for all available devices

**Comment by andresbono** [comment]
I see, so by using the `blockdev` linux utility, you want to do some `ioctls` calls to the system to configure the way block devices are accessed, is that correct?

What kind of storage are you using in your cluster?  In Kubernetes, you don't always mount volumes as raw block devices. See here the storage plugins with raw block volume support:

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support

Even if you are using a compatible storage plugin, I'm not sure if the calls made by `blockdev` inside a container would make any effect or if you would need to run those containers as privileged.

**Comment by mehmetsalgar** [comment]
Hi, while my first try was to fire up the container to be able to see what are the actual values Linux Dist uses but while the container is initialized with user 1001, I don't have an access to root user to check actual values. So I tought I will set the parameter anyway because if the values are not set correctly it has a super deterioriating effect on our application in production.

We are planning use Azure Disks in the Cloud Environment and off course I am not sure this setting is supported at Linux or Kubernetes level, StorageClass etc, but our application definetely needs the correct value or the performance deteriorated like %30...

**Comment by mehmetsalgar** [comment]
I check the links you provided, it seem raw-block-volume is a better way to configure a Storage for Cassandra but it seems helm chart for Cassandra at bitnami the option is no there....

    `volumeClaimTemplates:
        - metadata:
              name: data
              labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
              {{- if .Values.persistence.annotations }}
              annotations: {{- toYaml .Values.persistence.annotations | nindent 10 }}
              {{- end }}
          spec:
             accessModes:
             {{- range .Values.persistence.accessModes }}
             - {{ . | quote }}
             {{- end }}
          resources:
             requests:
                storage: {{ .Values.persistence.size | quote }}`

must get the option

        volumeMode: Block

so it will look like this

    `volumeClaimTemplates:
        - metadata:
           name: data
           labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
           {{- if .Values.persistence.annotations }}
           annotations: {{- toYaml .Values.persistence.annotations | nindent 10 }}
           {{- end }}
          spec:
             accessModes:
             {{- range .Values.persistence.accessModes }}
             - {{ . | quote }}
              {{- end }}
              volumeMode: Block
              resources:
              requests:
                  storage: {{ .Values.persistence.size | quote }}
             {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}`

**Comment by andresbono** [comment]
Hi @mehmetsalgar, thanks for further looking into this. Could you add the new property on your side to see if it actually improves the performance of Cassandra and enables you to configure read ahead as you would expected?

We will be happy to include this new feature to the chart if it can be of help.
