### ISSUE TITLE
A second VolumeClaimTemplate with an additional storageClass for commit log directories

### ISSUE THREAD

**Issue by mehmetsalgar** [bitnami/charts#5637]
**Which chart**:
Cassandra Chart

**Is your feature request related to a problem? Please describe.**
It is recommended in Cassandra documentation to seperate the storage for data (SSTable, etc) and the Commit Log Sorage.
[Commit Log Storage](https://cassandra.apache.org/doc/latest/architecture/storage_engine.html)
```
* NOTE: In the event of an unexpected shutdown, Cassandra can lose up to the sync period or more if the sync is delayed. If using “batch” mode, it is recommended to store commitlogs in a separate, dedicated device.
* ```
So I like to configure another StorageClass and and Volume/VolumeMount for Commit Log Storage but unfortunately volumeClaimTemplates in statefulset.yaml is not design that way. Is it possible to changes it so it will be possible.

**Describe the solution you'd like**
Another volumeClaimTemplate placed into the statefulset.yaml, like following
```
        name: commitlog
        labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations: {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- include "common.commitlog-storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}
```

**Describe alternatives you've considered**
I can't see an alternative way to realise this.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by miguelaeh** [comment]
Hi @mehmetsalgar ,
Would you like to create a PR adding that feature? We will be happy to review it!

**Comment by mehmetsalgar** [comment]
Sure I can do it...

**Comment by mehmetsalgar** [comment]
Here ist die PR...

https://github.com/bitnami/charts/pull/5653

**Comment by miguelaeh** [comment]
Thank you very much for the PR!! 
We will take care of it!
