### ISSUE TITLE
Making Memcached play nicely with Kiali

### ISSUE THREAD

**Issue by larsrnielsen** [bitnami/charts#5640]
**Which chart**:
Memcached

Using memcached chart 5.5.1 I am unable to achieve the following with Kiali ("Istio dashboard"): based on label `app.kubernetes.io/name` group workloads that include memcached together, as memcached matchLabels are defined as:

```
{{- define "common.labels.matchLabels" -}}
app.kubernetes.io/name: {{ include "common.names.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
```

Say I have a Helm chart X for my-app with:
-  deployment of pod A and B 
- memcached as dependency
and I want to use `app.kubernetes.io/name=my-app` for all of it then memcached's matchLabel will match out my pod A and B as well as memcached pods. 

If I would overwrite the matchLabels for memcached then I could include e.g., `app.kubernetes.io/component=cache` to make sure I only match memcached pods. 

I can also go the longer road to make Kiali use some other label to group workloads as applications - like the default `app` - but how can I then add this extra label to memcached?

Lars

**Comment by juan131** [comment]
Hi @larsrnielsen 

You're looking for a way to add custom labels to every resource (apart of using the default ones), right? Sth like the `commonLabels` parameter that we have in other charts such as NGINX:

- https://github.com/bitnami/charts/tree/master/bitnami/nginx#common-parameters

**Comment by larsrnielsen** [comment]
> Hi @larsrnielsen
> 
> You're looking for a way to add custom labels to every resource (apart of using the default ones), right? Sth like the `commonLabels` parameter that we have in other charts such as NGINX:
> 
> * https://github.com/bitnami/charts/tree/master/bitnami/nginx#common-parameters

correct. If I had `commonLabels` available then I would be able to use an `app` label to tie workloads like memcached,  together in Kiali.

**Comment by juan131** [comment]
All right! I'll send a PR adding this feature during the day.

**Comment by juan131** [comment]
Hi @larsrnielsen 

As you can see, my PR was just merged, and a new version of the chart will be released in the next few hours including these messing paramaters.

**Comment by larsrnielsen** [comment]
> Hi @larsrnielsen
> 
> As you can see, my PR was just merged, and a new version of the chart will be released in the next few hours including these messing paramaters.

thanks, but can you also add the labels to the pod? I can only find commonLabels on the STS/Deployment, not on the related pods.

metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "common.names.fullname" . }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
      {{- if or .Values.podAnnotations (and .Values.metrics.enabled .Values.metrics.podAnnotations) }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if and .Values.metrics.enabled .Values.metrics.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.metrics.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}

**Comment by juan131** [comment]
I just commented in the new issue you opened @larsrnielsen
