### ISSUE TITLE
Contour chart 4.1.3 does not finish install

### ISSUE THREAD

**Issue by techgnosis** [bitnami/charts#5643]
**Which chart**:
Contour 4.1.3

**Describe the bug**
The Contour and Envoy Pods deploy and it looks successful but the `helm install` command hangs and eventually fails

**To Reproduce**
```
helm upgrade --install contour contour \
--repo https://charts.trials.tac.bitnami.com/demo \
--create-namespace \
--namespace contour \
--version 4.1.3 \
--wait
```

**Expected behavior**
I expect `helm install` to succeed and a `helm status` to show success instead of failure

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Fails on TKGI 1.10 and Minikube 1.17.1

**Comment by miguelaeh** [comment]
Hi @techgnosis ,
Could you try increasing the timeout? using `--timeout` in the Helm Install command.
