### ISSUE TITLE
Airflow Chart - How to pass Personal Access Token from Bitbucket for git clone of DAGs

### ISSUE THREAD

**Issue by brunojus** [bitnami/charts#5645]
Hello Everyone, 

Is there a possibility to clone a private repository on-premise as a DAG repository? I am able to export the git token for it. I am using Openshift as my k8s platform, how can I use this secret with a token in my values.yaml?

**Comment by zaistev** [comment]
explained in the documentation
https://github.com/bitnami/charts/tree/master/bitnami/airflow#option-2-get-your-dag-files-from-a-git-repository

u gotta get a deployment token from bitbucket, then update your values.yml to use it.

**Comment by brunojus** [comment]
> explained in the documentation
> https://github.com/bitnami/charts/tree/master/bitnami/airflow#option-2-get-your-dag-files-from-a-git-repository
> 
> u gotta get a deployment token from bitbucket, then update your values.yml to use it.

I tried like this, but I got an erro on Openshift, I think it is because of the internal bitbucket. Is it possible to pass it as a secret?

**Comment by RaedShabbir** [comment]
If using bitbucket, it has to be 

`@bitbucket.org`, .com didn't work
