### ISSUE TITLE
CeleryKubernetesExecutor crashloop

### ISSUE THREAD

**Issue by jagusztinl** [bitnami/charts#5646]
**Which chart**:
The name (and version) of the affected chart

bitnami/airflow 

**Describe the bug**

Schduler crash in case of CeleryKubernetesExecutor config. Other executors work well

**To Reproduce**

helm install -f bitnami_values.yaml airflow bitnami/airflow --set executor=CeleryKubernetesExecutor   --set rbac.create=true --set serviceaccount.create=true --set auth.username=my-user --set auth.password=my-passsword --set loadExamples=true

**Expected behavior**
start airflow

**Version of Helm and Kubernetes**:

- Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

```
(paste your output here)
```

- Output of `kubectl version`:
lient Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f3012a10f16eb86fdce6330433adf6c9ee", GitTreeState:"clean", BuildDate:"2021-02-13T03:54:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3", GitCommit:"9cdca7b", GitTreeState:"clean", BuildDate:"2020-10-02T23:12:03Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```
(paste your output here)
```

**Additional context**

Sheduler log:
[0m
[0m[1mWelcome to the Bitnami airflow-scheduler container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-airflow-scheduler[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-airflow-scheduler/issues[0m
[0m
[37mnami   [39m [32mINFO [39m Initializing airflow-scheduler
[36mairflow[39m [32mINFO [39m ==> No injected configuration files found. Creating default config file...
[36mairflow[39m [32mINFO [39m ==> Enabling examples...
[36mairflow[39m [32mINFO [39m ==> Configuring Airflow database...
[36mairflow[39m [32mINFO [39m ==> Setting Airflow Fernet key...
[36mairflow[39m [32mINFO [39m ==> Deploying Airflow from scratch...
[36mpostgre[39m [32mINFO [39m Trying to connect to PostgreSQL server
[36mpostgre[39m [32mINFO [39m Found PostgreSQL server listening at airflow-postgresql:5432
[36mpostgre[39m [32mINFO [39m PostgreSQL server listening and working at airflow-postgresql:5432
[36mairflow[39m [32mINFO [39m ==> Waiting for Airflow Webserver host...
[36mairflow[39m [32mINFO [39m
[36mairflow[39m [32mINFO [39m ########################################################################
[36mairflow[39m [32mINFO [39m  Installation parameters for airflow-scheduler:
[36mairflow[39m [32mINFO [39m    Webserver URL: airflow:8080
[36mairflow[39m [32mINFO [39m  This installation requires no credentials.
[36mairflow[39m [32mINFO [39m ########################################################################
[36mairflow[39m [32mINFO [39m
[37mnami   [39m [32mINFO [39m airflow-scheduler successfully initialized
[0m[38;5;2mINFO [0m ==> Starting airflow-scheduler... 
Waiting for db...
Database is ready
[0m[38;5;2mINFO [0m ==> Starting airflow...
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-03-01 20:30:21,961] {scheduler_job.py:1247} INFO - Starting the scheduler
[2021-03-01 20:30:21,962] {scheduler_job.py:1252} INFO - Processing each file at most -1 times
[2021-03-01 20:30:21,963] {kubernetes_executor.py:473} INFO - Start Kubernetes executor
[2021-03-01 20:30:21,963] {scheduler_job.py:1298} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1272, in _execute
    self.executor.start()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/celery_kubernetes_executor.py", line 60, in start
    self.kubernetes_executor.start()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/executors/kubernetes_executor.py", line 475, in start
    raise AirflowException("Could not get scheduler_job_id")
airflow.exceptions.AirflowException: Could not get scheduler_job_id
[2021-03-01 20:30:21,965] {dag_processing.py:451} WARNING - Ending without manager process.
[2021-03-01 20:30:21,965] {scheduler_job.py:1301} INFO - Exited execute loop

**Comment by migruiz4** [comment]
Hi @jagusztinl ,

I'm sorry but the `bitnami/airflow` chart does not have support for `CeleryKubernetesExecutor` yet.
The allowed executor values are: `SequentialExecutor`, `Local Executor`, `CeleryExecutor`, `KubernetesExecutor`

I have created an internal task to evaluate this feature request and develop it, but I can not give you an ETA for it to be ready.

If you want to contribute, feel free to send a PR with your changes and we will be very happy to review it!

**Comment by jagusztinl** [comment]
I see, thank you.
