### ISSUE TITLE
[bitnami/wordpress] WP_HOME

### ISSUE THREAD

**Issue by luigi-13** [bitnami/charts#5654]
Hello,

Im using the bitnami wordpress chart, and i dont know how i can configure the WP_HOME ? 
Im using an existing wordpress database where the siteurl and home options are well configured. 
The home option url is https://www.mysite.com/blog.

But when im going in the wp-admin, the field is on readonly and it is https://www.mysite.com/.
So all the pages are broken because they redirect to https://www.mysite.com/page1 and not to https://www.mysite.com/blog/page1

I dont use the ingress of the chart but my global ingress is like this : 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  labels:
    app: app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: www.mysite.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: app-svc
              servicePort: 80
          - path: /blog/?(.*)
            backend:
              serviceName: blog-wordpress
              servicePort: 80
          - path: /(wp.*)
            backend:
              serviceName: blog-wordpress
              servicePort: 80
  tls:
  - secretName: tls-www-mysitecom-cert
    hosts:
    - www.mysite.com
    - mysite.com

   
   
Anyone can help me ?
Thanks

**Comment by migruiz4** [comment]
Hi @luigi-13,

Currently, the image used for this chart [bitnami/wordpress](https://github.com/bitnami/bitnami-docker-wordpress) does not have an environment variable to configure `WP_HOME` and `WP_SITEURL`. 

But it is possible to use `/docker-entrypoint-init.d` to run a script that executes `wp-cli` or uses a regex to modify `wp-config.php` replacing the definitions of `WP_HOME` and `WP_SITEURL.`

For more information, please check these related issues:
- https://github.com/bitnami/bitnami-docker-wordpress/issues/155
- https://github.com/bitnami/bitnami-docker-wordpress/issues/236

When using the bitnami/wordpress chart, the scripts can be added by modifying `customPostInitScripts` at `values.yaml`.

https://github.com/bitnami/charts/blob/0999bfc9d83a22598ae3ebde49fd94320da3167f/bitnami/wordpress/values.yaml#L687-L706

**Comment by luigi-13** [comment]
Hi @migruiz4,

Thank you for your feedback, I have initialized a script as you recommended to me and it works well!
Here is the script for those interested. (I only needed to change the WP_HOME)
`customPostInitScripts: 
  wp-home-blog.sh: |
    #!/bin/bash
    chmod +w /bitnami/wordpress/wp-config.php
    sed -i "s|define(\x27WP_HOME\x27, \x27http:\/\/\x27 \. \$_SERVER\[\x27HTTP_HOST\x27\] \. \x27\/\x27);|define(\x27WP_HOME\x27, \x27http:\/\/\x27 \. \$_SERVER\[\x27HTTP_HOST\x27\] \. \x27\/blog\x27);|g" /bitnami/wordpress/wp-config.php
    wp cli cache clear
    chmod -w bitnami/wordpress/wp-config.php`

**Comment by migruiz4** [comment]
Awesome! Thank you very much for sharing your solution.

I'm going to close this as the issue seems to be resolved, if you have any further questions don't hesitate to let me know.
