### ISSUE TITLE
Not able to login AKS-Airflow web frontend // Getting: Invalid login. Please try again. 

### ISSUE THREAD

**Issue by KYHS-BOX** [bitnami/charts#5655]
**Which chart**:
airflow-aks bitnami/airflow

**Describe the bug**
Invalid login. Please try again (web frontend)
User and Pass Are Not working.

**To Reproduce**

1. az aks create --name aks-cluster --resource-group rg-aks-cluster --node-count 2 --generate-ssh-keys
2. az aks get-credentials --name aks-cluster --resource-group rg-aks-cluster
3. run this helm command:
helm install airflow-aks bitnami/airflow 
  --set service.type=LoadBalancer 
  --set loadExamples=true 
  --set web.baseUrl=http://mydomain.nl:8080 
  --set postgresql.enabled=false 
  --set redis.enabled=false 
  --set externalDatabase.host=servername.postgres.database.azure.com 
  --set externalDatabase.user=airflow_user@servername.postgres.database.azure.com 
  --set externalDatabase.database=airflow 
  --set externalDatabase.password=thedatabasepassword 
  --set externalDatabase.port=5432 
  --set externalRedis.host=redisname.redis.cache.windows.net 
  --set externalRedis.port=6379 
  --set externalRedis.password=theredispassword
  --set auth.username=user 
  --set auth.password=myuserpassword 
  --set auth.fernetKey=fernetkey

4. Open in Browser: http://mydomain.nl:8080 login with auth. username and auth.password. The error on the web frontend is: Invalid login. Please try again. 
5. export AIRFLOW_PASSWORD=$(kubectl get secret --namespace "default" airflow-aks -o jsonpath="{.data.airflow-password}" | base64 --decode)
6. echo $AIRFLOW_PASSWORD <- I copied the output, it's the same password as in auth.password=myuserpassword 

**Expected behavior**
Able to Login with auth.username and auth.password

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
I am testing for production but stucked n login on de web services. After troublelshooting for (more then) 1 day I like to post my issue for advise.  The error on the web frontend is: Invalid login. Please try again. I have (re) created a new basic AKS cluster with 2 nodes. I have carefully followed your helm chart documentation from airflow on github.

The run output is as expected.

NAME: airflow-aks
LAST DEPLOYED: Tue Mar  2 18:50:50 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the Airflow URL by running:

  echo URL  : http://mydomain.nl:8080

2. Get your Airflow login credentials by running:
  export AIRFLOW_PASSWORD=$(kubectl get secret --namespace "default" airflow-aks -o jsonpath="{.data.airflow-password}" | base64 --decode)
  echo User:     user
  echo Password: $AIRFLOW_PASSWORD
PS C:\Users\DAW\Documents\VSCode> 

Bit still no luck, cannot login the airflow web frontend .
Can you please help me a bit further?

thx in advance.
Best regards,
Rene  van den Wijngaard.

**Comment by javsalgar** [comment]
Hi,

Just to discard possible issues, are you able to make it work when not using the external database and the external redis? Instead, using the bundled redis and postgresql

**Comment by KYHS-BOX** [comment]
(@javsalgar) Hi Javier, Also not possible to use internal Postgress and Reds..

Container Live Log: Error executing 'postInstallation': Failed to connect to airflow-aks-next-postgresql:5432 after 36 tries (see help command I used specified below)

helm install airflow-aks-next bitnami/airflow `
  --set service.type=LoadBalancer `
  --set executor=KubernetesExecutor `
  --set loadExamples=true `
  --set web.baseUrl=http://mydomain.nl:8080 `
  --set auth.username=user `
  --set auth.password=MY-PASSWORD  

p.s.
The external PostgreSQL is connecting successfull, It's reported all working fine in the container live log I can check and see that it's creating all stuff and passing  the username and password. Kubernetesexector or default celery is not making anu difference. I have added a firewall rule to PostgresSQL security settings in Azure allow all Azure services, allow all Ip's. I run Postgress version 10. Any ideá?
you suggests which is:

**Comment by javsalgar** [comment]
Hi,

I remember that, for other applications that we packaged that used Azure Database for PostgreSQL, the support was not direct. For example, it would need to have the proper SSL CA in the client and the application must have support for SSL databases. Did you ever work with other SSL databases and Airflow?

**Comment by KYHS-BOX** [comment]
> 
> 
> Hi,
> 
> I remember that, for other applications that we packaged that used Azure Database for PostgreSQL, the support was not direct. For example, it would need to have the proper SSL CA in the client and the application must have support for SSL databases. Did you ever work with other SSL databases and Airflow?

No never before, I remember in de chart description to not use/fors SSL connections in Azure PostgreSQL config. Anyhow, again many Thanks for your update. I will take all your suggestions with me, you have point me to the right directions again (connection problemns maybe caused by SSL/certificate requirements on one of the side's). need to put the LOG on the service in Azure to identify the root cause, and if this is the case. For now I will close this case until further notice. cheers René.

**Comment by KYHS-BOX** [comment]
closing.
