### ISSUE TITLE
bitnami/mysql - podLabels not applied to Primary and Secondary

### ISSUE THREAD

**Issue by npande** [bitnami/charts#5662]
**Which chart**:
bitnami/mysql
https://bitnami.com/stack/mysql/helm

**Describe the bug**
Install bitnami/mysql helm chart and then upgrade helm chart to apply podLabels. 
Outcome: podLabels not applied to Primary and Secondary

**To Reproduce**

In the MySQL-values.yaml add following to help configure podLabels. This is done based on documentation provided at https://github.com/bitnami/charts/tree/master/bitnami/mysql/#mysql-primary-parameters

```
primary:
  podLabels:
    engine: "mysql"
    databasecluster: "devapp1"
secondary:
  podLabels:
    engine: "mysql"
    databasecluster: "devapp1"
```

Upgrade the helm chart with following command
$ helm upgrade --install mysql-release bitnami/mysql -f mysql-values.yaml

**Expected behavior**
We should be able to see the label applied on the pod with 
$ kubectl describe pods <podname>

I don't see the pod labels applied on the pod.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

- Output of `kubectl version`:

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
Able to apply pod label with kubectl command
Label a pod
$ kubectl label pod mysql-release-0 engine=mysql

Get pods with with engine label and value as mysql 
$ kubectl get pods --selector engine=mysql

**Comment by frankreno** [comment]
while `primary.podLabels` and `secondary.podLabels` is documented as a valid parameter, no template is currently using this label.  Try `commonLabels` instead.

```

**Comment by npande** [comment]
Thnx @frankreno 
**commonLabels** worked like a charm.

**Comment by alemorcuq** [comment]
Thanks, @frankreno !

We will add the missing `podLabels` to the templates. Is any of you interested on creating a PR?

**Comment by maninderCiena** [comment]
I am assuming if both commonLabels and primary.podLabels/secondary.podLabels is given later one will take priority !!

**Comment by maninderCiena** [comment]
@alemorcuq why this is marked as on-hold is there any major refactoring changes in process ?

**Comment by ManinderSinghRajput** [comment]
@alemorcuq Is there any major change is in progress for this repo ?

**Comment by alemorcuq** [comment]
No, @ManinderSinghRajput. No major change in progress.
