### ISSUE TITLE
[bitnami/wildfly] replicaCount value is not used, unable to set replicaCount for deployment

### ISSUE THREAD

**Issue by JohannesMattsson91** [bitnami/charts#5666]
Wildfly 8.1.1
replicaCount is listed as a parameter in the readme but not used in the [template/deployment.yaml](https://github.com/bitnami/charts/blob/master/bitnami/wildfly/templates/deployment.yaml) file.

**Comment by JohannesMattsson91** [comment]
https://github.com/bitnami/charts/pull/5667

**Comment by juan131** [comment]
Thanks for reporting it @JohannesMattsson91 ! I just approved/merged your PR
