### ISSUE TITLE
bitnami/mongodb - replicaset -  error of usage the previous value of external host name

### ISSUE THREAD

**Issue by AlexDag** [bitnami/charts#5671]
**Which chart**:
The name (and version) of the affected chart
bitnami/mongodb:   mongodb-10.4.1 	4.4.3  
**Describe the bug**
mongodb pod use values  of external host (LoadBalancer) of the the **previous** helm installation.

**To Reproduce**

1.  "helm install mongodb .....  bitnami/mongodb" replicaset cluster with external ends on aws eks.
2. Successfully connect to aws eks mongodb from my mongo desktop client.
3. "helm delete mongodb"
4. clean/ drain k8s node
5. run command form 1.
6. Can not connect to mongo from any client > by external url, by internal k8s mongo client
7. Error >

> 

```
{"t":{"$date":"2021-03-03T21:32:33.900+00:00"},"s":"I",  "c":"REPL",     "id":40445,   "ctx":"TopologyVersionObserver","msg":"Started TopologyVersionObserver"}
{"t":{"$date":"2021-03-03T21:32:33.900+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/opt/bitnami/mongodb/tmp/mongodb-27017.sock"}}
{"t":{"$date":"2021-03-03T21:32:33.901+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
{"t":{"$date":"2021-03-03T21:32:33.901+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
{"t":{"$date":"2021-03-03T21:32:33.931+00:00"},"s":"W",  "c":"NETWORK",  "id":21207,   "ctx":"ReplCoord-0","msg":"getaddrinfo() failed","attr":{"host":"a37998290083541fd88da070c125ec4f-2087836054.us-east-2.elb.amazonaws.com","error":"Name or service not known"}}
{"t":{"$date":"2021-03-03T21:32:33.944+00:00"},"s":"I",  "c":"NETWORK",  "id":4834700, "ctx":"ReplCoord-0","msg":"isSelf could not connect via connectSocketOnly","attr":{"hostAndPort":"a37998290083541fd88da070c125ec4f-2087836054.us-east-2.elb.amazonaws.com:27017","error":{"code":6,"codeName":"HostUnreachable","errmsg":"couldn't connect to server a37998290083541fd88da070c125ec4f-2087836054.us-east-2.elb.amazonaws.com:27017, connection attempt failed: HostNotFound: Could not find address for a37998290083541fd88da070c125ec4f-2087836054.us-east-2.elb.amazonaws.com:27017: SocketException: Host not found (authoritative)"}}}
{"t":{"$date":"2021-03-03T21:32:33.944+00:00"},"s":"W",  "c":"REPL",     "id":21405,   "ctx":"ReplCoord-0","msg":"Locally stored replica set configuration does not have a valid entry for the current node; waiting for reconfig or remote heartbeat","attr":{"error":{"code":74,"codeName":"NodeNotFound","errmsg":"No host described in new configuration with {version: 1, term: 1} for replica set rs0 maps to this node"},"localConfig":{"_id":"rs0","version":1,"term":1,"protocolVersion":1,"writeConcernMajorityJournalDefault":true,"members":[{"_id":0,"host":"a37998290083541fd88da070c125ec4f-2087836054.us-east-2.elb.amazonaws.com:27017","arbiterOnly":false,"buildIndexes":true,"hidden":false,"priority":5.0,"tags":{},"slaveDelay":0,"votes":1}],"settings":{"chainingAllowed":true,"heartbeatIntervalMillis":2000,"heartbeatTimeoutSecs":10,"electionTimeoutMillis":10000,"catchUpTimeoutMillis":-1,"catchUpTakeoverDelayMillis":30000,"getLastErrorModes":{},"getLastErrorDefaults":{"w":1,"wtimeout":0},"replicaSetId":{"$oid":"603fdc524bfee561ed63b58e"}}}}}
```
> 

The  external host "a37998290083541fd88da070c125ec4f-2087836054.us-east-2.elb.amazonaws.com" of the error message is the value from first helm installation.
Deleting and installing many times bitnami/mongodb  the error message always shows that host name of the first installation.
For example> the actual external hosts> 
> k get services
a0d2c2c7066db4162a65eb642d5ff524-602078637.us-east-2.elb.amazonaws.com   27017:31536/TCP 
af98121ee309a48f5a61f942b6adb9e6-794359958.us-east-2.elb.amazonaws.com   27017:31071/TCP

**Expected behavior**
Correct usage of external host replicaset
**Version of Helm and Kubernetes**:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
- Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```
(paste your output here)
```

- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
(paste your output here)
```

**Additional context**

**Comment by alemorcuq** [comment]
Can you share the full command you are using to install the chart?

**Comment by AlexDag** [comment]
helm install mongo-eks  --set\
 architecture=replicaset\
,volumePermissions.enabled=false\
,replicaCount=2\
,externalAccess.enabled=true\
,externalAccess.service.type=LoadBalancer\
,externalAccess.service.port=27017\
,externalAccess.autoDiscovery.enabled=true\
,serviceAccount.create=true\
,rbac.create=true bitnami/mongodb

**Comment by alemorcuq** [comment]
I've tried to reproduce your issue in the latest version of the chart (`10.10.0`) and I couldn't. Can you confirm you are still having the issue in the latest chart?

**Comment by AlexDag** [comment]
I've switched to "no public external url" configuration  and I use this chart through private aws vpc.

**Comment by alemorcuq** [comment]
Sorry, I didn't understand. Are you still having the issue?

**Comment by AlexDag** [comment]
I'm not working now with "bitnami/mongodb external IP" as I made this issue. If you does not have any solution - I still having this problem.

**Comment by alemorcuq** [comment]
I will try to reproduce it in a different environment to see if I get the same behavior.
