### ISSUE TITLE
[bitnami/mongodb] Root User not created

### ISSUE THREAD

**Issue by ghost** [bitnami/charts#5690]
**Which chart**:
bitnami/mongodb 10.9.0

**Describe the bug**
After Installing the Chart and retrieving the root password, auth for root fails

**To Reproduce**
```
helm install bitnami/mongodb -f values.yaml --generate-name
```
my values:
```yaml
image:
  tag: 4.4.4-debian-10-r21
architecture: replicaset
fullnameOverride: mongodb-companyname
annotations:
  sidecar.istio.io/inject: "false"
podAnnotations:
  sidecar.istio.io/inject: "false"
auth:
  enabled: true
replicaSetName: rs0
replicaCount: 3
nodeSelector:
  agentpool: core
  kubernetes.io/os: linux
persistence:
  size: 25Gi
rbac:
  create: true
metrics:
  enabled: false
```
With Mongo Compass installed locally
```
kubectl port-forward -n edgraph svc/service-name 27017:27017
```
Attempt to connect mongodb://root:ROOTPASSWORD@localhost:27017/admin

Log Output
```
{"t":{"$date":"2021-03-05T04:22:59.807+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn48","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","principalName":"root","authenticationDatabase":"admin","client":"127.0.0.1:54554","result":"UserNotFound: Could not find user \"root\" for db \"admin\""}}
```

**Expected behavior**
Able to connect to the ReplicaSet

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
I was trying to reproduce the issue on my side; for that, I used the same values you provided except the parameters related to annotations and selectors:
```yaml
 image:
   tag: 4.4.4-debian-10-r21
 architecture: replicaset
 fullnameOverride: mongodb-companyname
 auth:
   enabled: true
 replicaSetName: rs0
 replicaCount: 3
 persistence:
   size: 25Gi
 rbac:
   create: true
 metrics:
   enabled: false
```

- Then I installed the chart with the following command:
```console
$ helm install bitnami/mongodb -f my-values.yaml --generate-name

$ helm ls
NAME                             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
mongodb-1614939414               	default  	1       	2021-03-05 10:17:00.319307497 +0000 UTC	deployed	mongodb-10.9.1              	4.4.4

$ kubectl get pods
NAME                                            READY   STATUS      RESTARTS   AGE
mongodb-companyname-0                           1/1     Running     0          4m36s
mongodb-companyname-1                           1/1     Running     0          3m59s
mongodb-companyname-2                           1/1     Running     0          3m7s
mongodb-companyname-arbiter-0                   1/1     Running     0          4m36s
```

- According to the notes that are generated based on the specified values, those are the required steps to connect to the database:

1. To get the root password run:
```console
 $ export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongodb-companyname -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
```
2. To connect to your database, create a MongoDB(R) client container:
```console
$ kubectl run --namespace default mongodb-companyname-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.4-debian-10-r21 --command -- bash
```
3. Then, run the following command inside the container:
```console
 $ mongo admin --host "mongodb-companyname-0.mongodb-companyname-headless.default.svc.cluster.local:27017,mongodb-companyname-1.mongodb-companyname-headless.default.svc.cluster.local:27017,mongodb-companyname-2.mongodb-companyname-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```

- I was able to follow the above steps and connect to the database from the client container:
```console
$ mongo admin --host "mongodb-companyname-0.mongodb-companyname-headless.default.svc.cluster.local:27017,mongodb-companyname-1.mongodb-companyname-headless.default.svc.cluster.local:27017,mongodb-companyname-2.mongodb-companyname-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
MongoDB shell version v4.4.4
connecting to: mongodb://mongodb-companyname-0.mongodb-companyname-headless.default.svc.cluster.local:27017,mongodb-companyname-1.mongodb-companyname-headless.default.svc.cluster.local:27017,mongodb-companyname-2.mongodb-companyname-headless.default.svc.cluster.local:27017/admin?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("b765a2e6-ff97-43da-b58c-3698b8c2871d") }
MongoDB server version: 4.4.4
---
The server generated these startup warnings when booting:
        2021-03-05T10:17:34.998+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
---
---
        Enable MongoDB's free cloud-based monitoring service, which will then receive and display
        metrics about your deployment (disk utilization, CPU, operation statistics, etc).

        The monitoring data will be available on a MongoDB website with a unique URL accessible to you
        and anyone you share the URL with. MongoDB may use this information to make product
        improvements and to suggest MongoDB products and deployment options to you.

        To enable free monitoring, run the following command: db.enableFreeMonitoring()
        To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
rs0:PRIMARY>
```

In order to access the cluster from outside the cluster, you need to set different parameters, you can take a look at the available options in [this section of the README](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#replicaset-accessing-mongodb-nodes-from-outside-the-cluster).

**Comment by accu-joeykarns** [comment]
@carrodher Thank you for looking into this. I did also try the mongodb client container and followed the same commands and still got 
Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1

Logs:
{"t":{"$date":"2021-03-05T13:40:11.984+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn3398","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","principalName":"root","authenticationDatabase":"admin","client":"10.11.19.112:45246","result":"UserNotFound: Could not find user \"root\" for db \"admin\""}}

**Comment by accu-joeykarns** [comment]
@carrodher Did you have any issues with the readiness probe?

**Comment by accu-joeykarns** [comment]
@carrodher I cleared everything out and changed from the namespace I was using to default. The namespace I was using was Istio enabled. So something with the chart breaks if installed on an istio enabled namespace.

**Comment by carrodher** [comment]
Not sure if it is related to istio or because you were using the same release name and namespace, because `helm` doesn't delete the PVC where the password is stored, and the PVC with the old password is reused with the new deployment; but the new deployment generates a new random password that is not the same stored in the PVC, causing a conflict.

[Here](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases) is explained in a better way.

Can it be the issue? Can you try again in the istio namespace but with a different name or removing the PVCs with `kubectl delete pvc ...`

**Comment by accu-joeykarns** [comment]
@carrodher Yep...let me try

**Comment by accu-joeykarns** [comment]
@carrodher Ok...I've got it working but I had to have some istio destination rules to disable TLS on port 27017

`apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mongo-db-hosts-connection
spec:
  host: "*.SERVICENAME.NAMESPACE.svc.cluster.local"
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 27017
      tls:
         mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mongo-db-connection
spec:
  host: SERVICENAME.NAMESPACE.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 27017
      tls:
         mode: DISABLE
`

**Comment by carrodher** [comment]
I'm glad the issue is solved. We are accepting some PRs implementing some changes in the Helm Charts doing them compatible with the istio service names, such as https://github.com/bitnami/charts/pull/5679. It is not something included on our backlog to work on in the short term, but we are open to review external contributions.

**Comment by zzswang** [comment]
Same issue happened in our setup.

```
k8s + ceph

chart_ref: bitnami/mongodb
chart_version: 10.11.0

mongodb_architecture: replicaset
mongodb_replicas: 3
mongodb_root_password: 12345678
mongodb_storage_size: 12Gi
```

log

```
{"t":{"$date":"2021-05-16T12:23:42.178+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn839","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","principalName":"root","authenticationDatabase":"admin","client":"10.42.0.18:44458","result":"UserNotFound: Could not find user \"root\" for db \"admin\""}}
{"t":{"$date":"2021-05-16T12:23:42.179+00:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn839","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-1","principalName":"root","authenticationDatabase":"admin","client":"10.42.0.18:44458","result":"UserNotFound: Could not find user \"root\" for db \"admin\""}}
{"t":{"$date":"2021-05-16T12:23:42.179+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn839","msg":"Connection ended","attr":{"remote":"10.42.0.18:44458","connectionId":839,"connectionCount":0}}
```

**Comment by carrodher** [comment]
Can you look at this troubleshooting guide just in case you are facing some of the mentioned issues?
https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues, mainly the "Persistence Volumes (PVs) Retained From Previous Releases"

**Comment by zzswang** [comment]
I've tried on a newly setup k3s cluster on cloud, same error.

Reproduce steps:

1. setup an k3s cluster on cloud. 
2. setup mongodb as replicaset, with  

```yaml
auth:
    enabled: true
    rootPassword: 12124
replicaCount: 3
persistence:
  storageClass: local-path
```

3. failed. `result":"UserNotFound: Could not find user \"root\" for db \"admin\"`

**Comment by zzswang** [comment]
I've tried several times.

Reinstall OS each time with new disk.

**Comment by zzswang** [comment]
One thing, I'm running helm on my local machine. 

Does it store something in my local machine?

**Comment by carrodher** [comment]
Running Helm on a local machine shouldn't affect, the requirements for this chart are:
- Kubernetes 1.12+
- Helm 3.1.0
- PV provisioner support in the underlying infrastructure 

And those requirements can be satisfied in a local machine, in fact, I am testing it in my local machine using minikube, but also in a GKE cluster; unfortunately, I am not able to reproduce the issue.

A couple of things you can try: 
- Can you use the latest version (`10.15.2`)? Just in case it is something fixed since `10.11.0`
- Are you facing the same issue if you install the chart with the default values? Just by running `helm install my-release2 bitnami/mongodb`
- If the previous item works, can you try then adding your custom parameters little by little? Just to identify what is the parameter causing the issue

**Comment by zzswang** [comment]
Thanks for your help.

> Can you use the latest version (10.15.2)? Just in case it is something fixed since 10.11.0

I'll try it later. 

> Are you facing the same issue if you install the chart with the default values? Just by running helm install my-release2 bitnami/mongodb

Yes, default values will work.

> If the previous item works, can you try then adding your custom parameters little by little? Just to identify what is the parameter causing the issue

First two work, last one not work.

```yaml
auth:
    enabled: true
    rootPassword: 12124
architecture: standalone
persistence:
  storageClass: ceph
```
work

```yaml
auth:
    enabled: false
architecture: replicaset
replicaCount: 3
persistence:
  storageClass: ceph
```
work

```yaml
auth:
    enabled: true
    rootPassword: 12124
architecture: replicaset
replicaCount: 3
persistence:
  storageClass: ceph
```
not work

**Comment by zzswang** [comment]
I've tested for three times, the result is stable.

Environment:

1. k3s 1.19 (init with k3sup)
2. ceph [install with rook](https://github.com/rook/rook/blob/master/Documentation/helm-operator.md)
3. ubuntu 20.04

It is no matter `ceph` or other storage-class, while `loca-path` has the same result.

**Comment by zzswang** [comment]
@carrodher
Thanks for your help.

At last I found, it is not the issue of this chart. It is because I use ansible to manage my vaults, but it has some problem in templating values.yaml.

**Comment by carrodher** [comment]
I'm glad you were able to identify the issue!
