### ISSUE TITLE
Not able to run command passing as postgresqlInitdbArgs in latest binami postgresql

### ISSUE THREAD

**Issue by prakashmnnit81** [bitnami/charts#5692]
I am passing the  the below command as argument
echo -e "psql -c \"CREATE DATABASE testdb;\"\npsql  -d \"testdb\" -f \"/tmp/testscript/test.sql\"" > /docker-entrypoint-initdb.d/init-user-db.sh && chmod a+x /docker-entrypoint-initdb.d/init-user-db.sh && cat /docker-entrypoint-initdb.d/init-user-db.sh && docker-entrypoint.sh postgres -N 500
but unable to run this command 
I am passing the test.sql using /temp/testscript/test.sql using config map which is present in container I have verified 

any reason why container is not able to execute the command as argument?

**Comment by miguelaeh** [comment]
Hi @prakashmnnit81 ,
Are you passing that command into the `test.sql` file? If that's the case try renaming the file to `test.sh` instead.
The `extraInidDbArgs` are not intended to be used like that, it seems you are passing a full bash command, while it expects the db arguments, check this section https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#specifying-initdb-arguments
It seems you are looking for this section https://github.com/bitnami/bitnami-docker-postgresql#on-container-start

**Comment by prakashmnnit81** [comment]
Thanks @miguelaeh  for replying,
I am able to create database, I have put my all command in test.sql. I want it should be created after db created.
 I am using bitnami/postgresql 10.3.8 as subchart .So I have only option to  create table using above approach, so could you please describe in detail to achieve my task

**Comment by miguelaeh** [comment]
Hi @prakashmnnit81 ,
I am sorry maybe I misunderstood the issue. I am not sure about what you mean by:
```
I want it should be created after db created
```

Could you detail that please?

**Comment by prakashmnnit81** [comment]
@miguelaeh 
after creating the db I want to create connect the db  and initialize the table using below command psql -c "CREATE DATABASE testdb;"\npsql -d "testdb" -f "/tmp/testscript/test.sql"" could it possible using initdbScipt command?
