### ISSUE TITLE
Thanos Chart Labels 

### ISSUE THREAD

**Issue by kirinnee** [bitnami/charts#5695]
**Which chart**:
Thanos Chart (all)

**Is your feature request related to a problem? Please describe.**
Add custom labels to all pods 

**Describe the solution you'd like**
Have labels in `values.yaml` to provide additional labels to resource to deployed 

**Describe alternatives you've considered**
pipe to kustomize, but not workable with ArgoCD

**Comment by migruiz4** [comment]
Hi @kirinnee ,

I have created this PR #5718 adding `PodLabels` to the Thanos Chart, would that work for use case?

**Comment by kirinnee** [comment]
Hello this would, thank you very much!!
