### ISSUE TITLE
[bitnami/aiflow] Unzip Archive file issue

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/charts#5696]
when I try to unzip an archive file that contains sub directories it keeps giving me an permission denied

**Comment by juan131** [comment]
Could you please give us more context @raefezzeldin ?
 
 - How can we reproduce the same issue?
 - What version of the Airflow chart are you using?
 - What parameters are you setting?

**Comment by raefezzeldin** [comment]
When I try to unzip or create directory in the pods it gives me permission denied. the version I am using 8.0.6

**Comment by juan131** [comment]
Hi @raefezzeldin 

The Bitnami Airflow container is a non-root container (learn more about non-root containers in [our docs](https://docs.bitnami.com/tutorials/work-with-non-root-containers/)). As a consequence, there are very few directories where write permissions are granted.

What are you exactly trying to achieve? Manually accessing running containers and executing commands is highly discouraged and should be avoided if possible.

**Comment by raefezzeldin** [comment]
I am running Talend jobs which contain shell script and several jar files , so what I need to do is to archive the files and share it with airflow nodes then unzip the archive to run the shell script

**Comment by juan131** [comment]
Hi @raffaelespazzoli 

I guess yo need to mount these ZIP files (including the JAR and scripts) in the workers, right? I guess you could use the `worker.extraVolumeMounts` and `worker.extraVolumes` parameters to do so.

Parameter | Description | Default
-- | -- | --
worker.extraVolumeMounts | Array of extra volume mounts to be added (evaluated as template). Normally used with extraVolumes. | nil
worker.extraVolumes | Array of extra volumes to be added (evaluated as template). | nil

Once you have the ZIP mounted. You can extract them (e.g at `/tmp`) and execute them.

**Comment by raefezzeldin** [comment]
Hi @juan131 

Can you provide an example how edit this two values in the values.yaml file.

**Comment by juan131** [comment]
@rafariossaa you can find an example below:

```yaml
worker:
  extraVolumes:
    - name: scripts-and-jars
      persistentVolumeClaim:
            claimName: "YOUR_PVC_NAME"
  extraVolumeMounts:
    - mountPath: /vol/scripts-and-jars
      name: scripts-and-jars
```
