### ISSUE TITLE
[bitnami/mongodb] extraFlags overrides MONGODB_EXTRA_FLAGS set by tls.enabled=true

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/charts#5698]
**Which chart**:
bitnami/mongodb:10.7.2

**Is your feature request related to a problem? Please describe.**
If I set tls.enabled=true, the chart automatically set  MONGODB_EXTRA_FLAGS=--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert"

If I set tls.enabled=true *and* I set extraFlags, the chart set two times the same variable : 

```
- name: MONGODB_EXTRA_FLAGS
  value: --tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
- name: MONGODB_EXTRA_FLAGS
  value: --tlsAllowConnectionsWithoutCertificates
```
To make my replicatset work, I must manually set in my extraFlags values : 
```
extraFlags:
  - --tlsMode=requireTLS
  - --tlsCertificateKeyFile=/certs/mongodb.pem
  - --tlsCAFile=/certs/mongodb-ca-cert
  - --tlsAllowConnectionsWithoutCertificates
```
which results to : 

```
- name: MONGODB_EXTRA_FLAGS
  value: --tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
- name: MONGODB_EXTRA_FLAGS
  value: --tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
        --tlsAllowConnectionsWithoutCertificates

```

Moreover, when changing the extraFlags value and upgrading a release, one of the two env variable is randomly changed, so it can not guarantee that the pod will take the correct value.

**Describe the solution you'd like**
In this case I think the tls flags and the extra flags need to be concatenated.
Or this is attented, the documentation should state that the tls flags needs to be manually added (and the first variable should not be added to the template)

**Comment by marcosbc** [comment]
Hi @olivierboudet, in this case it seems like the chart should support setting `--tlsAllowConnectionsWithoutCertificates` if a boolean option is set when `tls.enabled=true`, right?

Another thing is that we should probably avoid setting EXTRA_FLAGS two times like you mention, and just concatenate.

Those changes look simple, would you be up for contributing any of these features with a PR?

**Comment by olivierboudet** [comment]
Hi, thanks, I will send a PR with the concatenation for EXTRA_FLAGS.

I am not sure the `--tlsAllowConnectionsWithoutCertificates` should have a specific setting. In this case, all `tls*`flags may need one, which can be quickly cumberstone ?
