### ISSUE TITLE
ibm cloud toolchain drupal

### ISSUE THREAD

**Issue by theodore-chronopoulos** [bitnami/charts#5699]
Hello. I have created a kubernetes cluster in ibmcloud and on top of that I configured Drupal. When I finished, drupal website was running perfectly, but I wanted to create a toolchain in order to automate code delivery. When I created a toolchain, you are asked to provide a git url to clone or otherwise it clones a git repo with a dummy app. What I want is the git repo that is created with my toolchain to have the code (deployment, services etc files) of my drupal app. I also tried first to create the toolchain, and after that to configure drupal, but it didnt work. Does anyone know how to accomplish that goal?

**Comment by andresbono** [comment]
Hi @theodore-chronopoulos, I'm not really sure if we can help you here... Note this is the repository for the Helm Charts that we provide, we are used to offer support for the way the applications like Drupal are configured but I can't give you advice on the toolchain matter you are talking about...

**Comment by theodore-chronopoulos** [comment]
@andresbono in the yaml files, many values are defined in https://charts.bitnami.com/bitnami. How could I have acces to tha code?

**Comment by andresbono** [comment]
Hi @theodore-chronopoulos, you can either check the code in this repository (https://github.com/bitnami/charts) or you can also execute the following command to get a tarball archive with all the files for the chart:

```
helm fetch bitnami/drupal
```
