### ISSUE TITLE
Simple Question on Architecture

### ISSUE THREAD

**Issue by venomone** [bitnami/charts#5710]
Hey folks,

can smb quickly explain to me why there is a elasticsearch-master and elasticsearch-data?!?
Are elasticsearch-data containers/Pods just the slaves of elasticsearch-master?
Would be awesome to see some documentation that points out the Architecture this setup uses

Thanks in advance

**Comment by marcosbc** [comment]
Hi @venomone, `elasticsearch-data` refer to Elasticsearch pods with a `data` role. Refer to the official docs for more info: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-node

**Comment by venomone** [comment]
@marcosbc Thank you very much for this explination and link :)
So data nodes basically do the work and master nodes coordinate the cluster. I first thought that elasticsearch-data is only realted to this bitnami chart, my bad. Thx again.
