### ISSUE TITLE
[bitnami/airflow] CSRF Token missing error

### ISSUE THREAD

**Issue by ashishmgofficial** [bitnami/charts#5711]
Helm install for latest airflow chart gets successful. Im hosting arflow web behind an ingress. in 8.0.2 chart with airflow 2.0.0. Everything works fine but with the latest chart with airflow 2.0.1, Im getting **CSRF Token missing error** right after Login from Airflow Login screen

**Comment by carrodher** [comment]
I'm sorry but I am not able to reproduce the issue.

```console
$ helm ls
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
airflow	default  	1       	2021-03-08 08:25:30.660319 +0100 CET	deployed	airflow-8.0.7	2.0.1
```

![Screenshot 2021-03-08 at 08 28 46](https://user-images.githubusercontent.com/13216600/110288514-6b0bae80-7fe8-11eb-8681-101d9ff3e122.png)
![Screenshot 2021-03-08 at 08 29 00](https://user-images.githubusercontent.com/13216600/110288517-6c3cdb80-7fe8-11eb-8213-8d48a338eb69.png)

Are you facing this issue installing the chart from scratch or doing an upgrade? If it is not an upgrade, are you facing this issue in a fresh deployment (new namespace, without previous PVCs, etc) or are you reusing the release name (and PVCs) from a previous deployment?

Are you able to see any errors in the web pod logs?
