### ISSUE TITLE
[redis] [feature-request] give redis modules support

### ISSUE THREAD

**Issue by humblewolf** [bitnami/charts#5744]
**Which chart**:
bitnami/redis

**Is your feature request related to a problem? Please describe.**
We use redisearch redis module (https://oss.redislabs.com/redisearch/) along with redis, AFAIK Bitnami charts does not provide any out of the box support for redis modules, which is a big deal for us.

**Describe alternatives you've considered**
We are writing our own images and kubernetes objects.

**Comment by marcosbc** [comment]
Hi @humblewolf, currently we don't include any non-default pre-built module for Redis, unfortunately.

Have you considered creating a Docker image based on `bitnami/redis` adding the built module on top? Note that you should be able to compile the module without, as documented here: https://docs.bitnami.com/aws/infrastructure/redis/configuration/install-modules/

**Comment by humblewolf** [comment]
Hey @marcosbc this is something we are currently doing but this involves writing our own layers and some sort of keeping track of versions which is why we look towards bitnami images/charts.This is not a bug or issue but kind of a feature-request. Include it into your roadmap if you guys think it will help a lot of people like me. Thanks

**Comment by marcosbc** [comment]
Hi @humblewolf, thanks for the feedback! I've created an internal task for evaluation, will share any updates here.

**Comment by marcosbc** [comment]
Hi @humblewolf, after a quick evaluation, it looks like RediSearch does not have an open-source license. Instead, it is based on the [RSAL](https://redislabs.com/legal/licenses/) license.

This means that unfortunately we will not be able to include it in the Bitnami Container Catalog for legal reasons.
