### ISSUE TITLE
[bitnami/harbor] Support cert-manager annotations

### ISSUE THREAD

**Issue by chrisbsmith** [bitnami/charts#5753]
**Which chart**:
bitnami/harbor

**Is your feature request related to a problem? Please describe.**
I deployed the bitnami/discourse chart recently using cert-manager, and leveraged the `ingress.certManager` value to automatically add the `kubernetes.io/tls-acme: true` annotation. I have been reviewing the harbor chart in preparation to deploy and noticed that it does not have the same `ingress.certManager` flag. 

**Describe the solution you'd like**
Provide an option for `ingress.certManager` that automatically templates the annotation, like https://github.com/bitnami/charts/blob/cee4f7c9027ab68973660a2bc92d00db175fed59/bitnami/discourse/templates/ingress.yaml#L18-L20

**Describe alternatives you've considered**
The harbor chart does provide an option for annotations through `.Values.ingress.annotations`.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! We will work on adding the feature. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by javsalgar** [comment]
Hi! Please check this PR, it should cover the use case
