### ISSUE TITLE
[bitnami/etcd] - Add Extra Containers Section in Helm Template

### ISSUE THREAD

**Issue by disfluxly** [bitnami/charts#5761]
**Which chart**:
bitnami/etcd

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to define extra containers that will run as a sidecar to the etcd container. 

**Additional context**
It'd be nice to have the ability to run sidecar containers to etcd. One example would be running telegraf as a sidecar to gather prometheus metrics / pprof metrics. This is especially useful when you don't have metrics server running in the K8S cluster to grab the prom metrics.

This can be handled in a similar manner to how Cortex does it here: https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/ingester-statefulset.yaml#L102-L103

**Comment by juan131** [comment]
We're doing a major refactoring at https://github.com/bitnami/charts/pull/5682
Please wait for the new major version to be released

**Comment by juan131** [comment]
We just released the new major version of the etcd chart (**6.0.0**) including new features and introducing changes in the etcd that attempt to improve the stability of the chart on operations such as scaling or updating the etcd cluster, see the link:

- https://github.com/bitnami/charts/tree/master/bitnami/etcd#to-600

We also improve the [docs](https://docs.bitnami.com/kubernetes/infrastructure/etcd), and create a specific section that explains details about how this chart works on operation such as bootstrapping or scaling (not available in the doc system yet), see

- https://github.com/bitnami/charts-docs/blob/main/charts/etcd/_understand_default_configuration.md.erb

Please give a try to the new major version, and share feedback about it. Thanks in advance!

**Comment by disfluxly** [comment]
@juan131  - Awesome, thank you. Noticing a problem with the new helm chart but will spin up a different issue.
