### ISSUE TITLE
Enable metrics for reids chart with prometheus-community/helm-charts while installation

### ISSUE THREAD

**Issue by sujeet-agrahari** [bitnami/charts#5764]
I have already setup  prometheus-community / helm-charts in a namespace `monitoring`.

How can I enable metrics to be shown on grafana dashboard?

What needs to be provided while installation?

**Comment by andresbono** [comment]
Hi, @sujeet-agrahari, you can specify `metrics.enabled=true` and the Redis chart will start exposing metrics:

https://github.com/bitnami/charts/tree/master/bitnami/redis#parameters

metrics.enabled | Start a side-car prometheus exporter
-- | -- 

Additional info: https://github.com/bitnami/charts/tree/master/bitnami/redis#metrics

**Comment by sujeet-agrahari** [comment]
Thanks @andresbono  Do I need to do any other setup besides setting `metrics.enabled=true`?

**Comment by andresbono** [comment]
On the Redis, side, that should be all, @sujeet-agrahari 👍  Let us know if you find any issues.

**Comment by sujeet-agrahari** [comment]
@andresbono Thanks, I did the same. How can I get the data in grafana dashboard? I have setup [prometheus-community](https://github.com/prometheus-community/helm-charts).

**Comment by andresbono** [comment]
Oh, in order to get the metrics in a Grafana Dashboard, you need to configure Grafana for that, at application level. Here you have a tutorial that might be useful for you:

https://docs.bitnami.com/tutorials/monitor-mariadb-replication-prometheus-grafana/
