### ISSUE TITLE
[bitnami/airflow] web args modification cause an error

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/charts#5777]
I am updating values .yaml with the following answers 👍 

`  web:
    args: 
      - 
        name: "AIRFLOW__WEBSERVER__WEB_SSL_CERT"
        value: "/mnt/MyAzureFileShare/Certs/tls.crt"
      - 
        name: "AIRFLOW__WEBSERVER__WEB_SSL_KEY"
        value: "/mnt/MyAzureFileShare/Certs/tls.key"
`

this error appears to me while deployment 

Failed to install app airflow. Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[1].args[0]): invalid type for io.k8s.api.core.v1.Container.args: got "map", expected "string", ValidationError(Deployment.spec.template.spec.containers[1].args[1]): invalid type for io.k8s.api.core.v1.Container.args: got "map", expected "string"]

**Comment by javsalgar** [comment]
Hi,

It seems you are setting the args value with environment variables. For that you should use the `extraEnvVars` value that you can see in the chart. You could try if that works
