### ISSUE TITLE
[bitnami/kong] Document how-to enable db-less mode (readme)

### ISSUE THREAD

**Issue by texano00** [bitnami/charts#5778]
**Which chart**:
kong: 3.4.4

**Is your feature request related to a problem? Please describe.**
There isn't info about how to enable Kong in db-less mode as described in the official guide.

**Describe the solution you'd like**
I write here the snippet to add on the README.md of the project. The solution is tested (and it works) by me.
Anything else is necessary in order to enable db-less kong mode.

```
### DB-less

#### TL; DR
1. Set `Value.database` with any value other than "postgresql" or "cassandra". For example `Value.database: "off"`
2. Set
```
Value.kong.extraEnvVars:
- name: KONG_DATABASE
  value: "off"
```

#### Short Story
Kong 1.1 added the capability to run Kong without a database, using only in-memory storage for entities: we call this DB-less mode. When running Kong DB-less, the configuration of entities is done in a second configuration file, in YAML or JSON, using declarative configuration (ref. [Link](https://docs.konghq.com/gateway-oss/1.1.x/db-less-and-declarative-config/)).
On the step 4 of [kong official docker installation](https://docs.konghq.com/install/docker#db-less-mode),
just change the config of docker run command FROM -e "KONG_DATABASE=postgres" TO -e "KONG_DATABASE=off" and you can go ahead!
```

I've also attached the full readme (updated with the new chapter).

[README.txt](https://github.com/bitnami/charts/files/6136958/README.txt)

**Comment by juan131** [comment]
Thanks so much for your feedback @texano00 ! We really appreciate it!
Do you mind creating a PR (see https://github.com/bitnami/charts/pulls) adding these suggestions? We'll be glad to review them and help you through the process to contribute to enrich the README.md
