### ISSUE TITLE
[bitnami/spring-cloud-dataflow] make upgrade possible without rabbitmq deployed

### ISSUE THREAD

**Issue by brjos** [bitnami/charts#5781]
**Which chart**:
spring-cloud-dataflow (2.8.0)

**Describe the bug**
Upgrading the chart when initially installed with "rabbitmq.enabled=false" leads to the following Error:
```
Error: UPGRADE FAILED: template: spring-cloud-dataflow/templates/NOTES.txt:88:4: executing "spring-cloud-dataflow/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordErrors "context" $)>: error calling include: template: spring-cloud-dataflow/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'mariadb.auth.rootPassword' must not be empty, please add '--set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "scdf" scdf-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)

    'rabbitmq.auth.password' must not be empty, please add '--set rabbitmq.auth.password=$RABBITMQ_PASSWORD' to the command. To get the current value:

        export RABBITMQ_PASSWORD=$(kubectl get secret --namespace "scdf" scdf-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)

    'rabbitmq.auth.erlangCookie' must not be empty, please add '--set rabbitmq.auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE' to the command. To get the current value:

        export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace "scdf" scdf-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
```

**To Reproduce**

1. install the chart with "rabbitmq.enabled=false"
  e.g. `helm install scdf . --set rabbitmq.enabled=false`
2. change anything and do a "helm upgrade"
  e.g. `helm upgrade scdf . --set rabbitmq.enabled=false --set server.livenessProbe.enabled=false`
4. upgrade will not succeed and post the error

**Expected behavior**
A helm upgrade should be possible, even when there is no rabbitmq used.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+350770ed07a558", GitCommit:"350770ed07a558ba1ce8202a6f9ea849f9a75f06", GitTreeState:"clean", BuildDate:"2021-02-11T20:10:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment]
Hi @brjos,
  Thanks for reporting the bug and making a PR.
   I have seen that @alemorcuq put some comments on your PR, could you take a look to them ?.

**Comment by brjos** [comment]
hello @rafariossaa
The change in the above-mentioned PR was unfortunately not correct, as it was based on a missunderstanding on my part.
For this reason, the PR was closed.

**Comment by rafariossaa** [comment]
When you install the chart, random passwords are generated by the chart. These password(s) are used in the initialization logic. The error indicates that you need to provided the generated password in order to be able to update, because the chart doesn't know about the older ones.

**Comment by brjos** [comment]
But if both rabbitmq.enabled and externalRabbitmq.enabled are set to false, no rabbitmq password should be needed to be able to upgrade, right?

**Comment by rafariossaa** [comment]
Hi, 
 That makes sense. Let's wait the PR to be reviewed and  approved
