### ISSUE TITLE
[bitnami/harbor] metric exporter is missing

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#5784]
**Which chart**:
Harbor 9.7.x
**Describe the bug**
The metrics exporter added with appVersion 2.2.0 is missing
**To Reproduce**

install harbor, notice no metgric exporter
**Expected behavior**
The metric exporter is installed.

**Additional context**
metric exporter in officvial chart: https://github.com/goharbor/harbor-helm/tree/master/templates/exporter
release notes adding the exporter: https://github.com/goharbor/harbor/releases/tag/v2.2.0

**Comment by Mauraza** [comment]
Hi @MaxRink,

I going to create an internal to include, we will update this thread when we have more information.
Thanks for reporting!

**Comment by ioannissavvaidis** [comment]
Hi @Mauraza ,

This issue is really helpful for observability harbor in production, do you have any update on this progress?

**Comment by Mauraza** [comment]
Hi @iamaverrick,

We have no news about this yet, we will update this thread when metrics are available.

**Comment by MaxRink** [comment]
any progess on this so far? It has been a while :)

**Comment by Mauraza** [comment]
Hi @MaxRink,

We are working on it. We will update the thread when metrics will be available.

**Comment by jgerry2002** [comment]
This really needs to be pushed up priority if possible. The bitnami harbor chart is fantastic to use otherwise, but its just missing the ability to expose metrics that have been available since the harbor 2.2 release. Please let us know if this will be added. Thanks!

**Comment by Mauraza** [comment]
Hi @jgerry2002,

Sorry, there is no update, I can't give you an ETA, but when there is an update, we will update the thread.

**Comment by ninjaslothx** [comment]
Any progress on this? I'm in the same boat as the other users and would really need this feature to properly monitor our instance with this chart.

**Comment by Mauraza** [comment]
Hi @ninjaslothx,

I am sorry there is still no progress.

**Comment by holzman** [comment]
+1 to adding this.  I'd be glad to contribute a patch, but how Bitnami builds the harbor-core static binary get built are opaque to me.

**Comment by carrodher** [comment]
I can share some updates: The task for this topic was promoted from the backlog to In progress, which means we are currently working on the addition of the harbor-exporter container image. Unfortunately, I can't provide an ETA for the release, but definitely is something we are working on.
