### ISSUE TITLE
Airflow Git-Sync volume name has "git-" prefix

### ISSUE THREAD

**Issue by kcz12** [bitnami/charts#5788]
**Which chart**:
Airflow 8.0.9
**Is your feature request related to a problem? Please describe.**
While using the Git-Sync functionality of the chart, the name if the volume gets prefixed with "git-" (_git_helpers.tpl line 36) As the "-" is not a supported symbol it makes it hard to use import statements for code that gets copied ower

**Describe the solution you'd like**
Change the prefix to an underscore to allow imports (from "git-" to "git_")

**Describe alternatives you've considered**
We could take away the prefix out altogether, and just leave the name that gets passed in.

**Additional context**
The issue is ModuleNotFoundError

**Comment by javsalgar** [comment]
Hi,

We are performing several changes in our Airflow container. I will forward this to @miguelaeh so he can take it into account when performing changes in the chart. Thanks for the info!

**Comment by kcz12** [comment]
Hello, has there been any updates on this ? I tried to download the chart locally and change the "git-" to "git_" and it indeed worked, so I could raise a PR for it

**Comment by miguelaeh** [comment]
Hi @kcz12 ,
I think that should be something that will not affect the container so I think you can create that PR safely. Thank you very much for the info. We will be happy to review it!
