### ISSUE TITLE
bitnami/solr exporter deployment fails even with authentication disabled

### ISSUE THREAD

**Issue by gkulkarni32** [bitnami/charts#5789]
**Which chart**:
bitnami/solr

**Describe the bug**
If you try to deploy solr with exporter.enabled=true and authentication disabled, the exporter pod does not come up as the zookeeper value is not correctly passed.

**To Reproduce**

1. `helm install solr bitnami/solr --set service.type=LoadBalancer,exporter.enabled=true,authentication.enabled=false`
2. `kubectl get all`
3.  Solr exporter pod does not come up as the zookeeper parameter in the exporter is not correctly passed.

**Expected behavior**
solr exporter pod should come up.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14+vmware.1", GitCommit:"bbf52cd6cf83a50507e943b717ed321d383a37b5", GitTreeState:"clean", BuildDate:"2020-08-19T23:48:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by juan131** [comment]
Hi @gkulkarni32 

I was able to reproduce the issue. I obtained the error below:

```
Exception. => java.lang.IllegalArgumentException: Unable to canonicalize address solr-zookeeper:2181:2181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:78)
java.lang.IllegalArgumentException: Unable to canonicalize address solr-zookeeper:2181:2181 because it's not resolvable
```

I just created a PR to fix it. Thanks so much for reporting it.

**Comment by gkulkarni32** [comment]
Thank you @juan131 for checking. Additionally, please check the NOTES.txt for the Solr exporter service. It should be ideally set to: `solr-exporter.<namespace>.svc.cluster.local:9983/metrics`. But the instruction mentions `solr-exporter.solr.svc.cluster.local:9983/solr`

**Comment by juan131** [comment]
I guess that's because you installed the chart in the `solr` namespace, right @gkulkarni32 ? I mean, the block below will resolver `{{ .Release.Name }}` with whatever namespace you're using to install the chart: 

```
** Solr Prometheus metrics are exported to the following endpoints: **

  * Internally, within the kubernetes cluster on:

{{ include "solr.exporter-name" . }}.{{ .Release.Name }}.svc.{{ .Values.clusterDomain }}:{{ .Values.exporter.port }}/solr
```

**Comment by juan131** [comment]
Oh, I just saw you're talking about the subpath. It should be `metrics` instead of `solr`. All right, adding it to the PR

**Comment by gkulkarni32** [comment]
yes, the subpath should be metrics. But for some reason when i deployed it in 'default' namespace also, it gave 'solr' instead of the namespace. Can you please check that too?

**Comment by juan131** [comment]
That's weird @gkulkarni32 .. Could you share the exact command you're using to install the Solr chart?

**Comment by gkulkarni32** [comment]
I ran this command, basically trying to deploy this in the default namespace.
`helm install solr bitnami/solr --set service.type=LoadBalancer,exporter.enabled=true,authentication.enabled=false`

**Comment by juan131** [comment]
Yes, it should be `.Release.Namespace`, you're totally right. This definitely confirms that I wasn't very focused when I took a look at this yesterday, my apologizes.

I'll send a new PR fixing this.

**Comment by gkulkarni32** [comment]
Thank you @juan131 ! Appreciate it!

**Comment by juan131** [comment]
Thank you for reporting it!
