### ISSUE TITLE
bitnami/moodle + mariadb docker / kubernetes persistent volumes

### ISSUE THREAD

**Issue by Choogster1** [bitnami/charts#5797]
This isn't a bug and not sure where else to ask this question:

When using the bitnami/docker container and mounting the /bitnami/moodle directory to a persistent volume, the contents of the folder are copied to the shared folder (local directory or nfs drive). 

How would I get the same behaviour from a kubernetes persistent volume, copying the moodle installation to the volume from the container, and thus if you add any apps to the persistent directory, it then updates the container as well. It doesn't seem to work the same way, and I can't seem to find any documentation on this anywhere. 

This also applies to the bitnami/mariadb container, the same question as above. Any help would be appreciated.

**Comment by miguelaeh** [comment]
Hi @Choogster1 ,
You will need to create the volume and use an existing PVC pointing to the previously created volume. To create that volume uploading a local folder you should go to your cluster provider docs (f.e. GKE, AKS, etc)

**Comment by Choogster1** [comment]
So I would have to copy the moodle folder manually from the moodle container to the PVC previously created volume first?

**Comment by miguelaeh** [comment]
yes, to move a local volume data to the cloud you need to upload it to the K8s volume, then create a PVC to match that volume and specify that PVC to be used by the chart

**Comment by Choogster1** [comment]
Is there any instructions online you can direct me to - in the case of an existing mariadb or postgresql database, or moodle installation.

**Comment by javsalgar** [comment]
Maybe a solution like this could work for you: https://okteto.com/
