### ISSUE TITLE
Symlink in the chart repository

### ISSUE THREAD

**Issue by a-nldisr** [bitnami/charts#5800]
**Which chart**:
metrics-server

**Describe the bug**
We tried to import the github repository for testing our PR's, but we ran into issues because Rancher gives an error that there is a symlink in the repository. 

**To Reproduce**

1. Setup Rancher
2. Click on 'Apps' in cluster explorer.
3. Try to import the github repository directly instead of using the charts webpage
4. See error: `symlink found at path management-state/git-repo/bitnami-symlink-test/760ab41eef8b4545d286988ac8f6603204ad0112ac874dfd7c6ee131a119d32a/bitnami/metrics-server/ci/ct-values.yaml`

Is this symlink necessary? We can remove it in our tests and creates a bit of overhead when we want to make PR's, but its the only chart that has this so it could be unintended.

**Comment by javsalgar** [comment]
Hi,

Thank you for reporting. I think we can remove this symlink as it does not add any value.
