### ISSUE TITLE
[bitnami/kibana] Test trying to use wget on minideb

### ISSUE THREAD

**Issue by lorisepita** [bitnami/charts#5801]
**Which chart**:
kibana

**Describe the bug**
Helm test cannot work due to missing wget binary on the docker image used for the connection test.

**To Reproduce**

1. `helm install elasticsearch bitnami/elasticsearch`
2. `helm install kibana bitnami/kibana --set elasticsearch.hosts[0]=<Hostname of your ES instance> --set elasticsearch.port=9200`
3. `helm test kibana`

**Expected behavior**
The test should pass.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The `wget` binary is not installed on the minideb image.

Here is the relevant output from `kubectl describe pod`:
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  21s   default-scheduler  Successfully assigned default/kibana-test-connection to kind-control-plane
  Normal   Pulling    22s   kubelet            Pulling image "bitnami/minideb"
  Normal   Pulled     20s   kubelet            Successfully pulled image "bitnami/minideb" in 2.239534995s
  Normal   Created    20s   kubelet            Created container wget
  Warning  Failed     20s   kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "wget": executable file not found in $PATH: unknown
```

Solving this issue could be done by changing the docker image used for the connection test.

**Comment by juan131** [comment]
Hi @lorisepita 

Thanks so much for reporting this issue! I just created a PR addressing it!

**Comment by lorisepita** [comment]
Hi @juan131, 

Thank you very much for this fix !
Is it possible to generate a new Chart.lock file for the elasticsearch chart (https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/Chart.lock) in order to have it use the last version of kibana ?

Thanks a lot !

**Comment by juan131** [comment]
Hi @lorisepita 

That's automatically done by the pipeline when a new version of the Elasticsearch chart is released, so it should be a matter of time for it to be updated.

That said, you can force it to be updated by submitting a PR bumping the patch version in the Elasticsearch's **Chart.yaml** and running the `helm dep update` command.
