### ISSUE TITLE
[bitnami/memcached] Add service account to memcache charts 

### ISSUE THREAD

**Issue by infa-mhadiman** [bitnami/charts#5811]
**Describe the bug**
memcached helm chart seems to use the default service account. Please add a dedicated SA instead of using the default service account.

This is part of the best practices and is also a compliance thing for many of the certifications such as Fedramp. 

**Expected behavior**
memcached helm chart should use it's own SA

**Version of Helm and Kubernetes**:
```
helm - 3.4.2
K8s - 1.18
```

**Comment by Mauraza** [comment]
Hi @infa-mhadiman,

I going to create an internal task to do it, but If you want you can create a PR with the change.
