### ISSUE TITLE
bitnami/influxDB v1: Option to add collectd listener (UDP:25826)

### ISSUE THREAD

**Issue by bhakta0007** [bitnami/charts#5816]
I want to add collectd listener on port 25826 so I can have collectd populate metrics into influx. I can add this change in influxdb.conf, but how do I expose this port? I don't see the configuration option for exporting udp:25826.

```
[[collectd]]
  enabled = true
  bind-address = ":25826" # the bind address
  database = "collectd" # Name of the database that will be written to
  retention-policy = ""
```

**Comment by javsalgar** [comment]
Hi,

I'm afraid there's no currenty way to add extra container ports or extra service ports. I think that could be an interesting feature. I will add a task in our backlog but I cannot guarantee a stict ETA. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by bhakta0007** [comment]
@javsalgar 
I got this to work in my local K8 repository. I have submitted a pull request (https://github.com/bitnami/charts/pull/5851)
Note: I am very new to helm charts - I am not sure If I have done this the right way - welcome comments.

**Comment by javsalgar** [comment]
Thank you so much for the contribution!
