### ISSUE TITLE
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)

### ISSUE THREAD

**Issue by bhkamath** [bitnami/charts#5817]
**Which chart**:

- mysql-8.4.4	
- App Version 8.0.23

**Describe the bug**

```
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)
```

**To Reproduce**

1. Kubernetes On-Premise cluster
2. Install MySQL chart: `helm install my-sql bitnami/mysql`
3. Create MySQL client container: `kubectl run my-sql-mysql-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mysql:8.0.23-debian-10-r28 --namespace default --command -- bash`
4. Try to access the database: 

```console
$ mysql -h my-sql-mysql.default.svc.cluster.local -uroot -p my_database`
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)

[with service IP address]
mysql -h 10.108.82.91 -uroot -p my_database
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '10.108.82.91' (111)
```

5.  Get pods:

```console
$ kubectl get pods
my-sql-mysql-0                      0/1     Pending   0          19m
my-sql-mysql-client                 1/1     Running   0          17m
```

6. Get service:

```console
$ kubectl get svc
my-sql-mysql             ClusterIP      10.108.82.91     <none>           3306/TCP       20m
my-sql-mysql-headless    ClusterIP      None             <none>           3306/TCP       20m
```

Firewall, SELinux disabled
 
**Expected behavior**
MySQL client connection with MySQL server should have been established

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.5.3+g041ce5a
```

- Output of `kubectl version`:

```
Client Version: v1.18.5
Server Version: v1.18.16
```

**Comment by juan131** [comment]
Hi @bhkamath 

I wasn't able to reproduce the issue on a GKE cluster following the same exact steps you shared.

What password are you using to access MySQL? Did you obtain it by running the command below as suggested in the installation notes?

```console
$ echo Password: $(kubectl get secret --namespace default my-sql-mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode)
```

It's so weird that you're obtaining a `111` error since that means: _connection refused_. That usually happens when MySQL server is configured to listen only on the "localhost" interface for connections, but your MySQL server should be configured to listen any interface. You can check it by running: 

```console
$ kubectl exec my-sql-mysql-0 -- grep "bind-address" /opt/bitnami/mysql/conf/my.cnf
bind-address=0.0.0.0
```

Do you have any networkpolicy(ies) defined in your cluster?

**Comment by bhkamath** [comment]
Hi Juan,

The Kubernetes cluster that I use is not GKE but on Baremetal environment.

There are no security policies defined.  I also tried installing Helm chart of stable/mysql and was successful accessing the MySql server.  I specified persistence.existingClaim at the time of helm installation.

The base64 decode of root password did expose normal string.  However, in Bitnami scenario I get a base64 coded string.

I later revised my experimentation by specifying a pre-created Persistent Volume Claim, this had no difference.  Instead I notice, 'data-my-sql-mysql-0' pvc appearing in pending state.

kubectl get  pv
b-mysql-pv   2Gi        RWO,ROX        Retain           Bound    default/b-mysql-pvc                           15m

kubectl get pvc
b-mysql-pvc   Bound    b-mysql-pv   2Gi        RWO,ROX                       15m

kubectl describe pv b-mysql-pv
Name:            b-mysql-pv
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    
Status:          Bound
Claim:           default/b-mysql-pvc
Reclaim Policy:  Retain
Access Modes:    RWO,ROX
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/mysql
    HostPathType:  
Events:            <none>

helm install my-sql --set mysqlRootPassword=passwd,mysqlUser=mysql,mysqlPassword=my-password,mysqlDatabase=mydb,persistence.existingClaim=b-mysql-pvc  bitnami/mysql 
NAME: my-sql
LAST DEPLOYED: Thu Mar 18 15:41:06 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Tip:

  Watch the deployment status using the command: kubectl get pods -w --namespace default

Services:

  echo Primary: my-sql-mysql.default.svc.cluster.local:3306

Administrator credentials:

  echo Username: root
  echo Password : $(kubectl get secret --namespace default my-sql-mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode)

To connect to your database:

  1. Run a pod that you can use as a client:

      kubectl run my-sql-mysql-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mysql:8.0.23-debian-10-r28 --namespace default --command -- bash

  2. To connect to primary service (read/write):

      mysql -h my-sql-mysql.default.svc.cluster.local -uroot -p my_database

To upgrade this helm chart:

  1. Obtain the password as described on the 'Administrator credentials' section and set the 'root.password' parameter as shown below:

      ROOT_PASSWORD=$(kubectl get secret --namespace default my-sql-mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode)
      helm upgrade my-sql bitnami/mysql --set auth.rootPassword=$ROOT_PASSWORD

echo Password : $(kubectl get secret --namespace default my-sql-mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode)
Password : KEX8FJ388x.  [ I was expecting 'passwd' string to appear]

kubectl run my-sql-mysql-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mysql:8.0.23-debian-10-r28 --namespace default --command -- bash
If you don't see a command prompt, try pressing enter.
I have no name!@my-sql-mysql-client:/$  mysql -h my-sql-mysql.default.svc.cluster.local -uroot -p my_database
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)
I have no name!@my-sql-mysql-client:/$  mysql -h my-sql-mysql.default.svc.cluster.local -uroot -p my_database
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)
I have no name!@my-sql-mysql-client:/$ exit
exit
pod "my-sql-mysql-client" deleted
pod default/my-sql-mysql-client terminated (Error)

kubectl get pvc
NAME                  STATUS    VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS   AGE
b-mysql-pvc           Bound     b-mysql-pv   2Gi        RWO,ROX                       18m
data-my-sql-mysql-0   Pending                                                         2m6s

 kubectl run my-sql-mysql-client --rm --tty -i --restart='Never' --image  docker.io/bitnami/mysql:8.0.23-debian-10-r28 --namespace default --command -- bash
If you don't see a command prompt, try pressing enter.
I have no name!@my-sql-mysql-client:/$ mysql -h my-sql-mysql.default.svc.cluster.local -uroot -p mydb [db name - as specified at the creation of helm install]
Enter password:   [ password used base64 version ]
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)
I have no name!@my-sql-mysql-client:/$ mysql -h my-sql-mysql.default.svc.cluster.local -uroot -p mydb
Enter password:   [ password used normal text, 'passwd'; refer to helm install command above]
ERROR 2003 (HY000): Can't connect to MySQL server on 'my-sql-mysql.default.svc.cluster.local' (111)
I have no name!@my-sql-mysql-client:/$

**Comment by juan131** [comment]
Hi @bhkamath 

PVCs are not removed after you uninstall a release, they have to be manually created. This is a known limitation on Helm (see https://github.com/helm/helm/issues/5156). This is something to have in mind as it's explained in the Troubleshooting guide below:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases

The Bitnami MySQL creates the users/passwords exclusively when there's no persisted data (only 1st boot of the container). On container restarts, or when you mount an already populated volume, it skips this step and reuses the data as it's.

This is the reason why you found issues with the passwords when you installed the chart with the command below:

```
$ helm install my-sql --set mysqlRootPassword=passwd,mysqlUser=mysql,mysqlPassword=my-password,mysqlDatabase=mydb,persistence.existingClaim=b-mysql-pvc  bitnami/mysql 
```

You were assuming that the root password should be `passwd`, but it was actually reusing whatever root password was set when the data in the existing PVC was created.

**Comment by bhkamath** [comment]
Hi Juan,

Maybe I confused you stating multiple situations.

Helm deployment and client interaction by bitnami/MySQL version fails, while client interaction with stable/MySQL deployment succeeds.

I suspect it to be due to not having configured dynamic storage.  When I specify storage as part of helm install command it doesn't get used.

I have created a persistent volume to work around issue, but persistent volume claim (data-my-sql-mysql-0) doesn't bind with it.  What attributes does PVC look for that of PV as part of binding process.  I could not find any such details in your configuration or troubleshooting guide.

Also, in your Helm install reference,  it states a set of pre-requisite but fail to explain on storage configuration details.

If you can throw some light on storage requirements of bitnami/MySQL I will try to experiment further.

Thanks.

**Comment by juan131** [comment]
Hi @bhkamath 

> When I specify storage as part of helm install command it doesn't get used

How did you do that? Using the `primary.persistence.existingClaim` parameter? I did a test using this parameter and I can confirm it works, see:

```console
$ helm template mysql bitnami/mysql --set primary.persistence.existingClaim=foo -s templates/primary/statefulset.yaml
...
      volumes:
        - name: config
          configMap:
            name: mysql
        - name: data
          persistentVolumeClaim:
            claimName: foo
```

> I have created a persistent volume to work around issue, but persistent volume claim (data-my-sql-mysql-0) doesn't bind with it. What attributes does PVC look for that of PV as part of binding process. I could not find any such details in your configuration or troubleshooting guide.

You will have to create both the PVC and the PV when using the `persistence.existingClaim` parameter. Do not expect the chart to create a PVC for you when setting this parameter.

**Comment by bhkamath** [comment]
Hi Juan,

I have performed helm install mysql --set mysqlRootPassword=password,mysqlDatabase=mydatabase,persistence.existingClaim=mysql-pvc bitnami/mysql

PV and PVC was created prior to performing helm install.

In your description, you make a reference to usage of 'helm template'.   The other difference between install and deploy statement is specification of StatefulSet.

Am I not supposed to use install verb ?  Is StatefulSet specification a must for PVC needs?

**Comment by juan131** [comment]
Hi @bhkamath 

> I have performed helm install mysql --set mysqlRootPassword=password,mysqlDatabase=mydatabase,persistence.existingClaim=mysql-pvc bitnami/mysql

You shouldn't be using `persistence.existingClaim=mysql-pvc` but `primary.persistence.existingClaim=mysql-pvc` instead as you can see in the example I shared before.

> In your description, you make a reference to usage of 'helm template'. The other difference between install and deploy statement is specification of StatefulSet.
> Am I not supposed to use install verb ? Is StatefulSet specification a must for PVC needs?

No, you should use `helm install`. It was just an example using `helm template` (see https://helm.sh/docs/helm/helm_template/) that's useful to see the exact manifests you're going to deploy in Kubernetes when using `helm install`.
The StatefulSet specification was just to show you that the command was working and a `foo` PVC was being used.

**Comment by bhkamath** [comment]
Hi Juan,

I finally solved the issue by performing the following -

1. Changed the mode of Hostpath - /tmp/mysql to 777 
2. Specifying primary.persistence.existingClaim 
3. The password used was base64 value (as stated in the documentation)

Thanks for your guidance.

Regards,

**Comment by igortas** [comment]
What's the minimal set of steps to make mysql working? 
Why this is not working, and I'm facing the same issue:
```
helm upgrade mysql bitnami/mysql --set auth.rootPassword=kfhjsdfkjhs, auth.password=kfhjsdfkjhshs, auth.username=root,auth.database=test
```
Password is base64, I'm gettingo into mysql pod, but after that I can't connect to mysql, after entering the password...

**Comment by juan131** [comment]
Hi @igortas 

> Password is base64

You shouldn't use the base64 encoded string but the actual passwords that were set when installing the chart.

> What's the minimal set of steps to make mysql working?

The chart provides you precise instructions to upgrade your release. Example:

```
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
```

In any case, if you're struggling with the upgrade process and you lost the original passwords, you can always revert your chart release to a previous one. Find more info in our troubleshooting guide:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

**Comment by igortas** [comment]
> Hi @igortas
> 
> > Password is base64
> 
> You shouldn't use the base64 encoded string but the actual passwords that were set when installing the chart.
> 
> > What's the minimal set of steps to make mysql working?
> 
> The chart provides you precise instructions to upgrade your release. Example:
> 
> ```
> PASSWORDS ERROR: you must provide your current passwords when upgrade the release
>     'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:
> 
>         export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
> ```
> 
> In any case, if you're struggling with the upgrade process and you lost the original passwords, you can always revert your chart release to a previous one. Find more info in our troubleshooting guide:
> 
> * https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

I can't understand how to make it work. From fresh install with removed volume, I've upgraded mysql chart as steps are saying. When I log into the temporary mysql pod, after that i can't connect to mysql. I've followed the troubleshoot and I don't see that I'm doing something different.
The chart is saying to export the password and set rootPassword, which what I do.(password in that case is base64)
Whatsoever, even is not explained, I'm setting also auth.database and auth.username, even auth.password, i'm not sure if is same as rootPassword, and it's not working. tried two different upgrades, first time auth.password to be base64 from what kubectl command returns, and next time auth.password to be plain password.

**Comment by igortas** [comment]
> Hi @igortas
> 
> > Password is base64
> 
> You shouldn't use the base64 encoded string but the actual passwords that were set when installing the chart.
> 
> > What's the minimal set of steps to make mysql working?
> 
> The chart provides you precise instructions to upgrade your release. Example:
> 
> ```
> PASSWORDS ERROR: you must provide your current passwords when upgrade the release
>     'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:
> 
>         export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)
> ```
> 
> In any case, if you're struggling with the upgrade process and you lost the original passwords, you can always revert your chart release to a previous one. Find more info in our troubleshooting guide:
> 
> * https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

Ok, I've tried once more from start, I've connected to the default db. Why on upgrade steps, not creating new db, i can see them with ```helm get values mysql`` command

**Comment by bhkamath** [comment]
Is it because of file permissions ?  Can you try with chmod 777 on the folder & file ?

**Comment by juan131** [comment]
Hi @igortas 

> Ok, I've tried once more from start, I've connected to the default db and installed with provides values for password and database.

That worked, right?

> On upgrade step I'm not sure how to replace my own password or db for example, cuz when I upgrade, i see the changed password, but I can't connect.

Do you mean that you set a different password from the one used (whether provided or auto-generated by the chart) when installing the chart?

**Comment by igortas** [comment]
> Hi @igortas
> 
> > Ok, I've tried once more from start, I've connected to the default db and installed with provides values for password and database.
> 
> That worked, right?
> 
> > On upgrade step I'm not sure how to replace my own password or db for example, cuz when I upgrade, i see the changed password, but I can't connect.
> 
> Do you mean that you set a different password from the one used (whether provided or auto-generated by the chart) when installing the chart?

Yes, after the initial install if the password is auto-generated or not, on upgrade step, I see user provided values, with  ```helm get values``` command, and it's not working as expected. Inside the mysql pod, after entering the mysql password I can connect.

**Comment by balianurag** [comment]
i have been facing some similar issue i have deployed mysql innodbcluster on a k8s cluster having 3 server and 2 routers pod running on it, the moment it goes into a restarting state after that i am never able to log into again. the only solution i am left with is redeploy it again and go through the data migration over and over again. Please suggest some solution to me !?
