### ISSUE TITLE
Failure to get external access working with load balancer for the bitnami mongodb replicaset

### ISSUE THREAD

**Issue by howardtangck** [bitnami/charts#5818]
I am not able to get external access working with load balancer for the bitnami mongodb replicaset. Please advise.
```console
$ helm install my-release \                
--set architecture=replicaset,replicaCount=3,externalAccess.enabled=true,externalAccess.service.type=LoadBalancer,externalAccess.service.port=27017,externalAccess.autoDiscovery.enabled=true,rbac.create=true \
bitnami/mongodb
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/howardtang/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/howardtang/.kube/config
Private key passphrase:
NAME: my-release
LAST DEPLOYED: Wed Mar 17 17:31:39 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

MongoDB(R) can be accessed on the following DNS name(s) and ports from within your cluster:

    my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017
    my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017
    my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-release-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database, create a MongoDB(R) client container:

    kubectl run --namespace default my-release-mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.4-debian-10-r30 --command -- bash

Then, run the following command:
    mongo admin --host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

To connect to your database nodes from outside, you need to add both primary and secondary nodes hostnames/IPs to your Mongo client. To obtain them, follow the instructions below:

  NOTE: It may take a few minutes for the LoadBalancer IPs to be available.
        Watch the status with: 'kubectl get svc --namespace default -l "app.kubernetes.io/name=mongodb,app.kubernetes.io/instance=my-release,app.kubernetes.io/component=mongodb,pod" -w'

    MongoDB(R) nodes domain: You will have a different external IP for each MongoDB(R) node. You can get the list of external IPs using the command below:

        echo "$(kubectl get svc --namespace default -l "app.kubernetes.io/name=mongodb,app.kubernetes.io/instance=my-release,app.kubernetes.io/component=mongodb,pod" -o jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}' | tr ' ' '\n')"

    MongoDB(R) nodes port: 27017

$ kubectl get all          
Private key passphrase:
NAME                               READY   STATUS     RESTARTS   AGE
pod/my-release-mongodb-0           0/1     Init:0/1   9          31m
pod/my-release-mongodb-arbiter-0   1/1     Running    3          31m

NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)           AGE
service/get-ip                                LoadBalancer   10.96.159.181   193.123.230.25   80:30050/TCP      6d
service/kubernetes                            ClusterIP      10.96.0.1       <none>           443/TCP           10d
service/my-release-mongodb-0-external         LoadBalancer   10.96.57.97     <pending>        27017:32105/TCP   31m
service/my-release-mongodb-1-external         LoadBalancer   10.96.64.87     <pending>        27017:30307/TCP   31m
service/my-release-mongodb-2-external         LoadBalancer   10.96.189.229   <pending>        27017:31574/TCP   31m
service/my-release-mongodb-arbiter-headless   ClusterIP      None            <none>           27017/TCP         31m
service/my-release-mongodb-headless           ClusterIP      None            <none>           27017/TCP         31m

NAME                                          READY   AGE
statefulset.apps/my-release-mongodb           0/3     31m
statefulset.apps/my-release-mongodb-arbiter   1/1     31m

$ kubectl logs -f my-release-mongodb-0 
Private key passphrase:
Error from server (BadRequest): container "mongodb" in pod "my-release-mongodb-0" is waiting to start: PodInitializing

$ kubectl logs -f my-release-mongodb-arbiter-0
Private key passphrase:
mongodb 09:58:06.12 
mongodb 09:58:06.12 Welcome to the Bitnami mongodb container
mongodb 09:58:06.12 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:58:06.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:58:06.12 
mongodb 09:58:06.13 INFO  ==> ** Starting MongoDB setup **
mongodb 09:58:06.15 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:58:06.16 INFO  ==> Initializing MongoDB...
mongodb 09:58:06.18 INFO  ==> Deploying MongoDB from scratch...
mongodb 09:58:07.36 INFO  ==> Creating users...
mongodb 09:58:07.37 INFO  ==> Users created
mongodb 09:58:07.37 INFO  ==> Writing keyfile for replica set authentication...
mongodb 09:58:07.39 INFO  ==> Configuring MongoDB replica set...
mongodb 09:58:07.40 INFO  ==> Stopping MongoDB...
mongodb 09:58:09.94 INFO  ==> Trying to connect to MongoDB server my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"

$ kubectl get all                             
Private key passphrase:
NAME                               READY   STATUS                  RESTARTS   AGE
pod/my-release-mongodb-0           0/1     Init:CrashLoopBackOff   11         47m
pod/my-release-mongodb-arbiter-0   1/1     Running                 5          47m

NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)           AGE
service/get-ip                                LoadBalancer   10.96.159.181   193.123.230.25   80:30050/TCP      6d
service/kubernetes                            ClusterIP      10.96.0.1       <none>           443/TCP           10d
service/my-release-mongodb-0-external         LoadBalancer   10.96.57.97     <pending>        27017:32105/TCP   47m
service/my-release-mongodb-1-external         LoadBalancer   10.96.64.87     <pending>        27017:30307/TCP   47m
service/my-release-mongodb-2-external         LoadBalancer   10.96.189.229   <pending>        27017:31574/TCP   47m
service/my-release-mongodb-arbiter-headless   ClusterIP      None            <none>           27017/TCP         47m
service/my-release-mongodb-headless           ClusterIP      None            <none>           27017/TCP         47m

NAME                                          READY   AGE
statefulset.apps/my-release-mongodb           0/3     47m
statefulset.apps/my-release-mongodb-arbiter   1/1     47m
```
Regards,
Howard Tang
howardtangck@gmail.com

**Comment by howardtangck** [comment]
It works without external access but that is not what I want.

howardtang@Howards-Air ~ % helm install my-release \                                
--set architecture=replicaset,replicaCount=3 \                                                                                                                                                           
bitnami/mongodb
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/howardtang/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/howardtang/.kube/config
Private key passphrase:
NAME: my-release
LAST DEPLOYED: Wed Mar 17 20:31:22 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

MongoDB(R) can be accessed on the following DNS name(s) and ports from within your cluster:

    my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017
    my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017
    my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-release-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database, create a MongoDB(R) client container:

    kubectl run --namespace default my-release-mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.4-debian-10-r30 --command -- bash

Then, run the following command:
    mongo admin --host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
howardtang@Howards-Air ~ % kubectl get all           
Private key passphrase:
NAME                               READY   STATUS              RESTARTS   AGE
pod/my-release-mongodb-0           0/1     ContainerCreating   0          33s
pod/my-release-mongodb-arbiter-0   1/1     Running             0          33s

NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)        AGE
service/get-ip                                LoadBalancer   10.96.159.181   193.123.230.25   80:30050/TCP   6d2h
service/kubernetes                            ClusterIP      10.96.0.1       <none>           443/TCP        10d
service/my-release-mongodb-arbiter-headless   ClusterIP      None            <none>           27017/TCP      33s
service/my-release-mongodb-headless           ClusterIP      None            <none>           27017/TCP      33s

NAME                                          READY   AGE
statefulset.apps/my-release-mongodb           0/3     34s
statefulset.apps/my-release-mongodb-arbiter   1/1     34s
howardtang@Howards-Air ~ % kubectl logs -f my-release-mongodb-arbiter-0
Private key passphrase:
mongodb 12:31:28.43 
mongodb 12:31:28.43 Welcome to the Bitnami mongodb container
mongodb 12:31:28.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 12:31:28.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 12:31:28.43 
mongodb 12:31:28.43 INFO  ==> ** Starting MongoDB setup **
mongodb 12:31:28.45 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 12:31:28.47 INFO  ==> Initializing MongoDB...
mongodb 12:31:28.48 INFO  ==> Deploying MongoDB from scratch...
mongodb 12:31:29.67 INFO  ==> Creating users...
mongodb 12:31:29.67 INFO  ==> Users created
mongodb 12:31:29.67 INFO  ==> Writing keyfile for replica set authentication...
mongodb 12:31:29.69 INFO  ==> Configuring MongoDB replica set...
mongodb 12:31:29.70 INFO  ==> Stopping MongoDB...
mongodb 12:31:32.25 INFO  ==> Trying to connect to MongoDB server my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local...
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
cannot resolve host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local": lookup my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local: no such host
mongodb 12:32:07.32 INFO  ==> Found MongoDB server listening at my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017 !
mongodb 12:35:06.23 ERROR ==> Node my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local did not become available
mongodb 12:35:06.23 INFO  ==> Stopping MongoDB...
howardtang@Howards-Air ~ % kubectl get all                             
Private key passphrase:
NAME                               READY   STATUS    RESTARTS   AGE
pod/my-release-mongodb-0           1/1     Running   0          3m59s
pod/my-release-mongodb-1           1/1     Running   0          3m15s
pod/my-release-mongodb-2           1/1     Running   0          2m28s
pod/my-release-mongodb-arbiter-0   1/1     Running   1          3m59s

NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)        AGE
service/get-ip                                LoadBalancer   10.96.159.181   193.123.230.25   80:30050/TCP   6d3h
service/kubernetes                            ClusterIP      10.96.0.1       <none>           443/TCP        10d
service/my-release-mongodb-arbiter-headless   ClusterIP      None            <none>           27017/TCP      3m59s
service/my-release-mongodb-headless           ClusterIP      None            <none>           27017/TCP      3m59s

NAME                                          READY   AGE
statefulset.apps/my-release-mongodb           3/3     3m59s
statefulset.apps/my-release-mongodb-arbiter   1/1     3m59s
howardtang@Howards-Air ~ %

**Comment by marcosbc** [comment]
Hi @howardtangck, I know there is currently an open issue with respect to external access and MongoDB in #4073. Checking the error ("Node ... did not become available") it looks like the same issue.

**Comment by howardtangck** [comment]
@marcosbc I also realized that the root login is failing. It was working in earlier helm installs. 

howardtang@Howards-Air ~ % helm install my-release \
--set architecture=replicaset,replicaCount=3 \
bitnami/mongodb
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/howardtang/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/howardtang/.kube/config
Private key passphrase:
NAME: my-release
LAST DEPLOYED: Thu Mar 18 16:31:55 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

MongoDB(R) can be accessed on the following DNS name(s) and ports from within your cluster:

    my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017
    my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017
    my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-release-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database, create a MongoDB(R) client container:

    kubectl run --namespace default my-release-mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.4-debian-10-r30 --command -- bash

Then, run the following command:
    mongo admin --host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
howardtang@Howards-Air ~ % export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default my-release-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
Private key passphrase:
howardtang@Howards-Air ~ % kubectl run --namespace default my-release-mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.4-debian-10-r30 --command -- bash
Private key passphrase:
If you don't see a command prompt, try pressing enter.
I have no name!@my-release-mongodb-client:/$ mongo admin --host "my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
MongoDB shell version v4.4.4
connecting to: mongodb://my-release-mongodb-0.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-1.my-release-mongodb-headless.default.svc.cluster.local:27017,my-release-mongodb-2.my-release-mongodb-headless.default.svc.cluster.local:27017/admin?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1

**Comment by marcosbc** [comment]
Hi @howardtangck, if root credentials don't work, it most likely means that you re-installed MongoDB without cleaning up PVCs, which are not removed with `helm delete`.

You can confirm that behavior checking the logs of the main MongoDB pod, where you would see something like this in the upper side of logs:

```
mongodb 15:05:29.35 INFO  ==> Deploying MongoDB with persisted data...
```

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
