### ISSUE TITLE
Contour helm chart needs to include ingressclasses

### ISSUE THREAD

**Issue by enyo** [bitnami/charts#5824]
**Which chart**:
contour

**Describe the bug**

Contour recently [started watching ingressclasses](https://github.com/projectcontour/contour/pull/3266), but looks like the helm chart’s RBAC hasn’t been updated to include it

**Additional context**

Needs to be added here: https://github.com/bitnami/charts/blob/master/bitnami/contour/templates/contour/rbac.yaml

**Comment by miguelaeh** [comment]
Hi @enyo ,
Thank you for the information. Would you like to create a PR adding that?

**Comment by enyo** [comment]
#5836

**Comment by Mauraza** [comment]
Hi @enyo,

As the PR was merged I going to close the issue. Thanks for the contribution!!
