### ISSUE TITLE
Multi-Attach error with Thanos compactor

### ISSUE THREAD

**Issue by mbrancato** [bitnami/charts#5826]
**Which chart**:
Thanos

**Describe the bug**
There is a conflict in mounting the PVC when an existing pod is already attached.

**To Reproduce**
I'm guessing a node pool resize causes this. But effectively you need to trigger a RollingUpdate of the compactor.

**Expected behavior**
I suspect that since `compactor.strategyType` defaults to `RollingUpdate` and `compactor.persistence.accessModes` defaults to `["ReadWriteOnce"]` that this prevents true RollingUpdates (grow then shrink).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**
From `kubectl describe pod`:
``` Warning  FailedAttachVolume  37m                 attachdetach-controller  Multi-Attach error for volume "pvc-********-8a0b-45e8-8944-e82e********" Volume is already used by pod(s) monitoring-thanos-compactor-67f9d78d5d-m5hpz```

**Comment by alemorcuq** [comment]
Hi, @mbrancato.

This happens when the new pod is spawned in another node. You can set some affinity rules to ensure the new pod is spawned in the same node so that the volume can be attached. For example, you can try with the `compactor.podAffinityPreset: hard` preset.

**Comment by mbrancato** [comment]
Hey @alemorcuq - Thanks, that would probably fix it - I set the strategy instead since this isn't a critical service. 

```
compactor:
  strategyType: Recreate
```

I understand why this occurred. I guess my point was really that the defaults of `RollingUpdate` and `ReadWriteOnce` have a possibility to run into this. Obviously `ReadWriteMany` is not a solution, so don't you think the default strategy should be `Recreate` to prevent this in the most generic sense? That would lead to the most usability, especially for clusters where it is prone to have the replacement pod from the ReplicaSet spin up on a different node.

It is somewhat surprising that since a `RollingUpdate` strategy and `ReadWriteOnce` PVCs are a known contention issue, that these would be defaults.

**Comment by alemorcuq** [comment]
The reason we opted to go for `RollingUpdate` instead of `Recreate` for the default update strategy is that, while it is true that the `RollingUpdate` may fail, it won't cause any downtime to the user. In the end it is a tradeoff and we decided to go for the availability route.
