### ISSUE TITLE
[bitnami/keycloak] ExternalDatabase use with secret

### ISSUE THREAD

**Issue by boxcee** [bitnami/charts#5834]
**Which chart**:
[bitnami/keycloak] `2.3.0`

**Is your feature request related to a problem? Please describe.**
I would like to avoid saving plaintext database credentials in the helm `values.yaml`.

**Describe the solution you'd like**
Like it is already implemented with the embedded PostgreSQL, I would like to see a key where I can pass a secret reference to the `values.yaml` instead of the plaintext values.

**Comment by andresbono** [comment]
Are `auth.existingSecret` and `auth.existingSecretPerPassword` what you are looking for?

https://github.com/bitnami/charts/tree/master/bitnami/keycloak#keycloak-parameters

**Comment by boxcee** [comment]
No, not really.
Looking at this block in particular:
```
externalDatabase:
  host: somehost
  user: someuser
  password: somepassword
  database: somedatabase
```
My understanding from `auth.existingSecret` and `auth.existingSecretPerPassword` is that I can only set the password via secret reference.

My concrete use-case is a managed SQL in GCP. The credentials are stored using the GCP Secrets Manager. Then we use the https://github.com/external-secrets/kubernetes-external-secrets operator to resolve the secrets in cluster and afterwards mount them to our pods.

Meaning all credentials are in one secret.

**Comment by boxcee** [comment]
@andresbono #5844 is what I have in mind.

**Comment by andresbono** [comment]
Thanks for creating the PR, @boxcee!! A member of our team will review it soon.

**Comment by boxcee** [comment]
Has been merged.
