### ISSUE TITLE
[bitnami/kafka] Adding option to gracefully shutdown sidecar container in provisioning pod

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#5835]
**Which chart**:
Bitnami Kafka 12.11.1

**Is your feature request related to a problem? Please describe.**
My cluster is using Istio for traffic control/shaping, and Kafka works really well with Istio.
I have an issue with the provisioning job, the provisioning job is not marked as completed due to the sidecar container staying in a running state.

See more about the issue here: 
https://github.com/istio/istio/issues/11659 
https://github.com/istio/istio/issues/15041 
https://github.com/istio/istio/issues/6324

**Describe the solution you'd like**
I see two different approaches that might solve the issue:

_Allow the provisioning job to run without the Istio sidecar._ 
With the use of podAnnotations to the pod generated by the kafka-provisioning job, and adding the annotation: 
sidecar.istio.io/inject: "false" (See example here: https://github.com/istio/istio/issues/11659#issuecomment-625263887 ) 

The disadvantage with this approach is:
- Istio will not be used for communication between the kafka topic provisioning pod and the kafka brokers 
- Istio's mutual TLS (mTLS) feature will not work between Kafka topic provisioning pod and the kafka brokers.
- Istio can not be run in a strict mTLS mode. 

The advantage with this approach is:
- Easiest "solution" to implement. Adding the possibility to set podAnnotations to the generated pod by the job. (See example here for the kafka-provisioning job: https://github.com/nc-ruth/charts/commit/2da7bf2025464f3c1e90feca7ad1cdc122231a9c ) 

_Allow the provisioning job to run code after finished provisioning of topics._
I don't know how to implement this, the most efficient way? 

**Describe alternatives you've considered**
I have exec'ed into the sidecar container, and curl'ed to quitquitquit endpoint, which afterwards shutdowns the sidecar container and completes the job successfully. 

**Additional context**
```kubectl get pods```
![Kafka-cluster-with-provisioning](https://user-images.githubusercontent.com/41048990/111614083-7d9f9800-87df-11eb-8f46-20f999fe0fc8.png)

```kubectl logs <topic-provisioning-pod> # just finished```
![Topic provisioning succeeded](https://user-images.githubusercontent.com/41048990/111614243-a6c02880-87df-11eb-9234-6938b76028ba.png)

```kubectl get pods # after the provisioning job is done```
![status-state-not-ready](https://user-images.githubusercontent.com/41048990/111614346-c6575100-87df-11eb-9527-091c189dd7f2.png)

```kubectl describe pod <topic-provisioning-pod> # just finished provisioning topics - shows the provisioning container state```
![provisioning-job-succeded](https://user-images.githubusercontent.com/41048990/111614401-d96a2100-87df-11eb-95e5-ffe5914c60be.png)

```kubectl describe pod <topic-provisioning-pod> # just finished provisioning topics - shows the Istio sidecar container state```
![istio-proxy-running](https://user-images.githubusercontent.com/41048990/111614518-f9014980-87df-11eb-9b0f-502b93e1e79d.png)

```kubectl exec -it <topic-provisioning-pod> -c istio-proxy -- curl -fsI -X POST http://localhost:15020/quitquitquit```
![exit-the-sidecar-gracefully](https://user-images.githubusercontent.com/41048990/111615660-4e8a2600-87e1-11eb-8475-8b18e355ac22.png)

```kubectl get pods # after sidecar has been terminated```
![pod-status-after-terminated](https://user-images.githubusercontent.com/41048990/111620403-f3f3c880-87e6-11eb-893b-eec4fec84562.png)

**Comment by juan131** [comment]
Hi @nc-ruth 

Thanks for bringing up this topic!

First of all, our charts are not designed to work with Istio. That said, they can be integrated with Istio since they can be extended adding custom sidecar containers, labels, annotations, etc.
I want to be clear on this because we don't test the integration Istio in our pipeline and, therefore, we don't officially support it. As a consequence, we cannot guarantee that we will not break the compatibility with Istio in the future since we're not taking into account during the development process any possible consequence affecting this integration.

---

Sticking to the topic you brought up, please correct me if I'm wrong but basically your goal is to mark the provisioning job as "completed" regardless the state of the sidecar container that Istio injects in every pod, right?

> Allow the provisioning job to run code after finished provisioning of topics.

What is the purpose of this? Doing some "curl" call that shutdowns the Istio sidecar? I guess we could implement some `provisioning.command`/`provisioning.args` parameters that allow you to overwrite the default ones, so you can add any piece of code you want. Would that work?

**Comment by nc-ruth** [comment]
Hi @juan131,

Thank you very much for your answer!

I completely understand that your charts are not designed to work with Istio, and it's a bonus if it works with Istio. 
It was not the intention of this issue, to "hardcode" in the istio-sidecar annotation into the chart. I apologize, if you understood the issue as that. 

I make sense that your pipelines does not test the Kafka chart with Istio integration, and it makes no sense to do so. I mean, there is a lot of integrations, and if your pipeline had to test each one out (and in combination), it would be a nightmare. 

I understand that you can't guarantee the compability with Istio in the future.

----

Back to the topic, the solution you are bringing up will solve our issue (the usecase). This is actually the solution I prefer. Is there any other charts, that have some similar implementation with provisioning.command / provisioning.args? 

How would it work, if it is only extending the already supported and tested command (within your pipeline)?

**Comment by juan131** [comment]
Hi @nc-ruth 

Thanks for your consideration.

Regarding the issue, please take a look to the PR I just created. Using these changes, you should be able to set in your **values.yaml** any custom command or args you want to use in the provisioning container.

**Comment by nc-ruth** [comment]
Hi @juan131,

Thank you for the PR!

I have pulled down your PR, and tested the base case (without any args or commands specified) and it works well.
I have tested the PR with specifiying ```provisioning.args``` and that works as intended. 

What is needed for this PR to be accepted and merged into master? 

Once again, thank you for the PR and answers :)

**Comment by juan131** [comment]
Hi @nc-ruth 

The PR was just merged! Thanks for your feedback and helping us to improve the chart.

Thanks also for sharing the **values.yaml** you used to manage the Istio integration!
