### ISSUE TITLE
 I can't create a new database from web interface in odoo

### ISSUE THREAD

**Issue by rghoubentini** [bitnami/charts#5838]
I used bitnami helm chart for odoo and I deployed odoo with success but when I tried to create a new db from web interface the creation of database was failed 
<img width="531" alt="db_error" src="https://user-images.githubusercontent.com/79690166/111650484-a044a780-8805-11eb-8d6a-2ca707a56e47.PNG">

**Comment by juan131** [comment]
Hi @rghoubentini 

Could you please share the exact command you used to install the Odoo chart?
I'm specially interested on what parameters you modified, you can obtain the exact list by running:

```console
$ helm get values RELEASE_NAME
```

> Note: replace the RELEASE_NAME placeholder with the actual name of your Odoo release

**Comment by rghoubentini** [comment]
Hi @juan131 
I installed odoo chart via kubeapps.

**Installation Values**

affinity: {}
args: []
command: []
commonAnnotations: {}
commonLabels: {}
containerSecurityContext:
  enabled: false
  runAsUser: 1001
customLivenessProbe: {}
customReadinessProbe: {}
existingSecret: null
externalDatabase:
  host: localhost
  password: ""
  port: 5432
  user: postgres
extraEnvVars: []
extraEnvVarsCM: null
extraEnvVarsSecret: null
extraVolumeMounts: []
extraVolumes: []
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/odoo
  tag: 13.0.20201010-debian-10-r0
ingress:
  annotations: null
  certManager: false
  enabled: false
  hosts:
  - name: odoo.local
    path: /
    tls: false
    tlsSecret: odoo.local-tls
  secrets: null
initContainers: []
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 600
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
nodeAffinityPreset:
  key: ""
  type: ""
  values: []
nodeSelector: {}
odooEmail: user@example.com
odooUsername: user@example.com
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 1Gi
podAffinityPreset: ""
podAnnotations: {}
podAntiAffinityPreset: soft
podLabels: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
postgresql:
  enabled: true
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 1Gi
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
service:
  externalTrafficPolicy: Cluster
  nodePort: "30250"
  port: 80
  type: NodePort
sidecars: []
tolerations: []

**Comment by juan131** [comment]
Hi @rghoubentini 

I think the issue here is that Odoo doesn't have admin privileges in the PostgreSQL database, instead it creates a `bn_odoo` user with restricted permissions. Therefore, it cannot creates new databases.

There's no much we can do here since we're using this setup for security reasons (avoiding Odoo to connect to the database with admin privileges). I know it clearly affects the UX.

I guess you'll have to connect to the PostgreSQL container and create the needed databases manually.

**Comment by rghoubentini** [comment]
Ok and thank you @juan131  for the response.
