### ISSUE TITLE
[bitnami/memcached] Generated service should not default to a headless configuration when service.clusterIP is not specified

### ISSUE THREAD

**Issue by jgregmac** [bitnami/charts#5843]
**Which chart**:
bitnami/memcached version 5.7.0

**Describe the bug**
When installing from the chart, the default setting for service.clusterIP is "Nil", but when running "helm install" without overriding this value, the service that is generated actually specifies "clusterIP: None".  This is not desirable, because we effectively get a "headless service" instead of a normal kubernetes service.  The only way to create a normal service is to specify a fixed IP address in the value service.clusterIP; but generally, we do not want to manage the assignment of internal cluster IP addresses.

ADDITIONALLY, there needs to be a `metrics.service.clusterIP` value that can be set at deployment time to *enforce* the creation of a headless metrics service.  In a high-availability deployment, a headless service is *necessary* for accurate collection of metrics from each memcached pod in the cluster.  Prometheus metrics vary greatly per-pod, so scraping metrics from random pods results in garbled and useless metric data.

**To Reproduce**

1. use `helm install bitnami/memcached` to install a new memcached instance with default settings.
2. use `kubectl get service [serviceName] -o yaml` and observe the value returned for clusterIP for the generated memcached service.

**Expected behavior**
You should have to specify "service.clusterIP: None" to generate a headless service.  

If you do not specify service.clusterIP, the default behavior should be that the service manifest does have the `clusterIP:` line defined, resulting in a "normal" service that will bind to a randomly-assigned cluster IP address.  

Note that the "metrics" service does not have this *same* problem.  The metrics service does not have a clusterIP setting *at all*.  It assigns a random clusterIP to the service at creation time.  There is *no* option to set `metrics.service.clusterIP: None`, and so no ability to deploy a headless metrics service.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}
```

- Output of `kubectl version`:

(Note:  I am deploying to a supported Red Hat OpenShift 3.11.x cluster)

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-12-11T15:42:23Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jgregmac** [comment]
I updated the original bug report with details concerning the need for a "metrics.service.clusterIP" setting.  Adding this information pushes this more in the direction of a "Feature Request".

There is a workaround... I can re-deploy the Helm-generated services manually, but it would be preferable to be able to get services defined they way we need them to be defined at deploy time.

**Comment by andresbono** [comment]
Hi @jgregmac, thanks for opening this issue. I think I'm not fully understanding the issue. If I execute the following commands:

```console
$ helm install memcached bitnami/memcached --version 5.7.0
$ kubectl get svc/memcached -o jsonpath='{.spec.clusterIP}'
10.96.117.171
$ kubectl get svc/memcached
NAME        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
memcached   ClusterIP   10.96.117.171   <none>        11211/TCP   2m11s
```

I obtain a regular ClusterIP service, not a headless one... Is it different for you?

**Comment by jgregmac** [comment]
Yes, I get a different result. If I do not specify a value in `service.clusterIP:`, the value gets set to "None" in the deployed service, so I cannot create a regular service without specifying a fixed IP.

This issue may be specific to OpenShift 3.11, which is running an older Kubernetes API version.  I think the related issue with the `metrics.service.clusterIP` will stand, though.  I'll give it a try on my more up-to-date dev instance and see...

**Comment by jgregmac** [comment]
Here are my results from a microk8s local install, using Kubernetes 1.20 with Helm 3.5.2.  The results are the same as on OpenShift.

I am finding that if I deploy the chart using the --values argument, and add the option `architecture: high-availability` , the service deploys as a headless service, whereas if I do not provide values (or if I comment out "architecture"), I get a regular service.

Based on the output of helm, this appears to have been a deliberate default choice.  This is a good default for an HA deploy, but you should be able to override it.  The bigger problem, though, that you _cannot_ force creation of a headless service for the metrics service.  The metrics service _definitely_ should default to a headless service in a HA config.

```bash
$  helm install test-memcached bitnami/memcached
...
NOTES:
** Please be patient while the chart is being deployed **
Memcached can be accessed on port 11211 on the following DNS name from within your cluster: test-memcached.default.svc.cluster.local
...
$ kubectl get svc/test-memcached
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
test-memcached   ClusterIP   10.152.183.83   <none>        11211/TCP   16s

$ helm uninstall test-memcached

$ helm install test-memcached bitnami/memcached --values memcached_values.yaml
...
NOTES:
** Please be patient while the chart is being deployed **
Memcached endpoints are exposed on the headless service named: test-memcached.
...
$ kubectl get svc/test-memcached
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
test-memcached   ClusterIP   None         <none>        11211/TCP   17m
```

Here are the contents of my "memcached_values.yaml" file:

```yaml
architecture: high-availability
replicaCount: 2
resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    memory: 256Mi
    cpu: "1"
extraEnv:
  - name: MEMCACHED_CACHE_SIZE
    value: "1024"
metrics:
  enabled: true
```

**Comment by andresbono** [comment]
Thanks for the clarification, @jgregmac. You are right, if you specify the `architecture: high-availability` parameter, then the service defaults to headless.

Isn't memcached clients usually require to specify the memcached nodes one by one? I imagine that's the objective of defining the service as headless. In any case, if you have a different use case, we will be happy to incorporate changes in the chart to make it more complete.

Would you like to open a PR contributing with the changes that you require for your case? Contributions are more than welcome!!
