### ISSUE TITLE
[bitnami/etcd] - Probe not working with 

### ISSUE THREAD

**Issue by kaflake** [bitnami/charts#5846]
If activating secureTransport the probes are not working any more. The problems seems, that the probe do not use the ca file, cause --cacert is only added if enableAuthentication is activate (_helpers.tpl), too.

**Comment by juan131** [comment]
Hi @kaflake 

Assuming you're using the latest chart release that relies on the etcd container logic, the healthcheck uses `etcdctl_auth_flags` function to calculate the flags to add to `etcdctl` command, see:

- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/etcd/healthcheck.sh

This function will add the `--cacert` flag if the environment variable `ETCD_TRUSTED_CA_FILE` is defined and it contains the path to an existing CA file, see:

- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L148

When you install the chart using `auth.client.secureTransport=true`, and setting the `auth.client.certFilename`, `auth.client.certKeyFilename` and `auth.client.caFilename` parameters this environment variable should be set, see:

- https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L194
- https://github.com/bitnami/charts/tree/master/bitnami/etcd#etcd-parameters

Could you please double-check this?

**Comment by kaflake** [comment]
Thank you for the fast help.
I saw the version of the chart was 5.6.2 and update not working, cause of Kubernetes 1.18 I use prometheus operator in an older version, which do not support TLS-settings on PodMonitor.
But I hope I get an update of kubernetes next time, than I also try it with the newest version.

**Comment by jtackaberry** [comment]
Is it expected that setting `auth.client.useAutoTLS` should also require manually configuring `auth.client.certFilename`, `auth.client.certKeyFilename` and `auth.client.caFilename`?   I would have expected that to be, well, automatic, but indeed these chart values also result in failed probes.

```yaml
auth:
  client:
    secureTransport: true
    useAutoTLS: true
  peer:
    secureTransport: true
    useAutoTLS: true
```

**Comment by kaflake** [comment]
I do not useAutoTLS and the settings are defined correct. It only not use the ca-File for the probes.

**Comment by juan131** [comment]
> Is it expected that setting `auth.client.useAutoTLS` should also require manually configuring `auth.client.certFilename`, `auth.client.certKeyFilename` and `auth.client.caFilename`?

No, **etcd** should create its own certificates when setting `auth.client.useAutoTLS=true`. In that case, the **etcdctl** expect them to be created at `"${ETCD_DATA_DIR}/fixtures/client/cert.pem"`, see:

- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L153

>  It only not use the ca-File for the probes.

Could you please confirm if the `ETCD_TRUSTED_CA_FILE` environment variable is correctly defined in your **etcd** pods?
