### ISSUE TITLE
[bitnami/rabbitmq] How to Autoscale 

### ISSUE THREAD

**Issue by lvilca-tekton** [bitnami/charts#5853]
**Which chart**:
rabbitmq ( 8.11.1) 

**Is your feature request related to a problem? Please describe.**
How to AUTO SCALE rabbitmq based on cpu or memory usage

**Comment by andresbono** [comment]
Hi @lvilca-tekton, I'm afraid that the auto scale feature is not implemented by the RabbitMQ chart. In general, you use HPA features https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ to do so.

You can see some examples that charts that implement it, for instance, Kong: https://github.com/bitnami/charts/blob/master/bitnami/kong/templates/hpa.yaml.

**Comment by lvilca-tekton** [comment]
But is it just safe to use so? Or are there some requirements to get HPA and to prevent data loss?

**Comment by lvilca-tekton** [comment]
@andresbono  With the HPA is gonna be able to replicate the first behaviour of : https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/#horizontal-scaling ?
I am wondering if I have to put the 
```
auth.password="$RABBITMQ_PASSWORD"
auth.erlangCookie="$RABBITMQ_ERLANG_COOKIE"
```
In the HPA file and where?

**Comment by andresbono** [comment]
After having a second look, RabbitMQ is using a statefulset, and the volumes are tied to specific pods of it. Scaling up and down automatically might cause issues because of that.

**Comment by lvilca-tekton** [comment]
Even right now I am trying to upscale it (manually) to 4 replicas (started with 1) and the 3rd replica has been on pending for 20 min. Any way to debug this or why could this be happening?

**Comment by andresbono** [comment]
Could it be that your cluster is running out of resources to schedule the pod? You can try to obtain more information by executing:

```
kubectl describe pod PENDING_POD
```
