### ISSUE TITLE
Uninstalling bitnami/redis-cluster left a job and a pod behind

### ISSUE THREAD

**Issue by ak2766** [bitnami/charts#5856]
**Which chart**:
`bitnami/redis-cluster`
`version: 4.4.1`

**Describe the bug**
Uninstalling the chart left a pod running:
```
$ kubectl get po -A | grep redis
default               redis-redis-cluster-cluster-create-wmkgs        0/1     Completed   0          2d1h
$ kubectl get job -A | egrep redis-redis
default     redis-redis-cluster-cluster-create   1/1           44s        2d1h
```

**To Reproduce**
1. Install chart : `helm install redis bitnami/redis-cluster`
2. Uninstall the cluster : `helm delete redis`

**Expected behavior**
I expected that uninstalling a Helm chart would leave the cluster in the exact state it was before the chart was installed.

**Version of Helm and Kubernetes**:
```
$ helm version --short
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

$ kubectl version --short
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @ak2766,

You are right, this job is a hook and helm don't delete this type of job, you can check this issue https://github.com/helm/helm/issues/4434
We are working to eliminate these hooks. But we don't know when they will be available.
