### ISSUE TITLE
[bitnami/redis-cluster] How to enable logrotate feature?

### ISSUE THREAD

**Issue by bharat15-ml** [bitnami/charts#5859]
**Which chart**:
redis-cluster-4.4.1

**Is your feature request related to a problem? Please describe.**
I have enabled the logs feature for log analysis (* knew its not recommended). Wanted to know how we can enable log rotation based on size (10KB) and on daily basis ?

**Describe the solution you'd like**
for log rotation haven't found any configuration parameter in redis.conf, So is there any other way to achieve log roation in current helm chart. Where and what needs to changed in values.yaml file?

**Describe alternatives you've considered**
Have directly specified redis logs in values.yaml mentioned in below link- https://ws1.netbraintech.com/download/onlinehelp/how-to-rotate-logs.htm
but it haven't worked.

Please help me on this how it is possible to achieve logrotation in current helm chart?

**Comment by juan131** [comment]
Hi @bharat15-ml 

The Bitnami Redis image redirects its log to `stdout/stderr` by default. In other words, it doesn't store them inside the Redis container. See:

- https://github.com/bitnami/bitnami-docker-redis-cluster#logging

In a container/k8s environment storing the logs in the containers is highly discouraged. Instead, a system to collect/aggregate the logs from every container in the cluster is highly recommended. We have a tutorial where we talk broadly about this topic:

- https://docs.bitnami.com/tutorials/integrate-logging-kubernetes-kibana-elasticsearch-fluentd/

**Comment by bharat15-ml** [comment]
Thabks@juan131, have went through the blogs and got this point as well. 

Working on specific requirements, so have enabled the logs and stored at different persistent location. Only thing is this log file is keep on increasing in size, so wanted to know how or what changes required on image or helm chart parameter level to implement this logrotate feature?? 

Also went through this blogs -https://ws1.netbraintech.com/download/onlinehelp/how-to-rotate-logs.htm, 

Which suggest to put logrotate configuration file in etc/logrotate.d/ folder to take in effect on service start. 

Please, let me know, with what changes we can Implement this use case??

**Comment by juan131** [comment]
Hi @bharat15-ml 

The Bitnami Redis image is, by default, a non-root container and it has some implications. Find more information in the link below:

- https://docs.bitnami.com/tutorials/work-with-non-root-containers

---

First, you'll have to install `logrotate`, since it's not included in the image by default. For instance, you can use the Dockerfile below to create your custom image:

```Dockerfile
FROM bitnami/redis-cluster

## Change user to perform privileged actions
USER 0
## Install 'logrotate'
RUN install_packages logrotate
## Revert to the original non-root user
USER 1001
```

Then, you can try to configure `logrotate`, but it's very likely you'll find permissions issues since the default non-root user won't have write permissions in some directories (e.g. `/etc/logrotate.d/`). You can try to workaround it modifying the previous Dockerfile as shown below:

```diff
FROM bitnami/redis-cluster

## Change user to perform privileged actions
USER 0
## Install 'logrotate'
RUN install_packages logrotate
+ Add your custom actions here to configure logrotate
## Revert to the original non-root user
USER 1001
```

**Comment by bharat15-ml** [comment]
Hi @Juan131, I have tried your suggested way to implement logrotate feature.
Below is dockerfile:
    
    From bitnami/redis-cluster
    USER root
    RUN install_packages logrotate
    COPY redis_logrotate /etc/logrotate.d/
    RUN chmod 777 -R /etc/logrotate.d/*  /var/lib/*
    USER 1001
Have created redis_logrotate file and kept inside /etc/logrotate.d/ folder.
This is the content of redis_logrotate file-

    /persistent/redis/logs/*.log {
    create 0644 1001
    daily
    rotate 15
    compress
    size 10K
    dateext
    dateformat -%Y%m%d
    missingok
    }

Have tried to dry run to check on its way of working, getting following error-

    logrotate -d -v redis_logrotate
        Error: Logrotate UID is not in passwd file.
        Reading state from file: /var/lib/logrotate/status
        Allocating hash table for state file, size 64 emtries

        Handling 0 logs

Please suggest on this, what will be the workaround to fix this issue.
Also have read this thread and read your comment - https://github.com/bitnami/bitnami-docker-nginx/issues/130

**Comment by Mauraza** [comment]
Hi @bharat15-ml,

Could you follow this guide to try to find what is happening https://access.redhat.com/solutions/32831?

**Comment by bharat15-ml** [comment]
Hi @Mauraza, Have followed the mentioned link. error is same - Logrotate UID is not in passwd file.

status:

    # cat /var/lib/logrotate/status
    output: logrotate state -- version 2
     
output of debug mode of execution is:

    # /usr/sbin/logrotate -d /etc/logrotate.conf
    Error: Logrotate UID is not in passwd file.
    Reading state from file: /var/lib/logrotate/status
    Allocating hash table for state file, size 64 emtries

    Handling 0 logs

Not getting what,why on this Error- "Logrotate UID is not in passwd file " and how to resolve?

**Comment by bharat15-ml** [comment]
Hi All, As bitnami images are running as non-root user and haven't found any entry in /etc/passwd file for default user-1001.

An alternative, Have added new user "redis" to existing image.  After logging to any pod, switched to new user "redis" and then tried to execute logrotate in debug mode. got following error-

**Comment by Mauraza** [comment]
Hi @bharat15-ml,

Could you try to use your new user redis? the permission of the file should be `-rw-------` ()

**Comment by carrodher** [comment]
There is a function in the container image to start cron as a daemon, not sure if you can use it or customize the image to cover your use case:

```bash
########################
# Start cron daemon
# Arguments:
#   None
# Returns:
#   true if started correctly, false otherwise
#########################
cron_start() {
    if [[ -x "/usr/sbin/cron" ]]; then
        /usr/sbin/cron
    elif [[ -x "/usr/sbin/crond" ]]; then
        /usr/sbin/crond
    else
        false
    fi
}
````
https://github.com/bitnami/bitnami-docker-redis-cluster/blob/d3eedfd390ca2d34bdac1076a804b6a4e3b3fba8/6.2/debian-10/prebuildfs/opt/bitnami/scripts/libservice.sh#L72

**Comment by fzyzcjy** [comment]
Hi, did you solve it?
