### ISSUE TITLE
pg pool pod is not accessible and gets stuck in terminating state

### ISSUE THREAD

**Issue by YoshithaR** [bitnami/charts#5867]
`CASE1:`

replicaCount on pgpool is 1, replicaCount on postgresql is 3. there are 3 nodes(vms). The pgpool is on node2 and if node2 goes down , new pgpool pod is created (pgpool-7859d5f5fc-62gm7   1/1     Running) but the old pod does not terminate completely (pgpool-7859d5f5fc-6n8fc   1/1     Terminating) and new pgpool pod is not accessible with its port. the postgresql pod on node2 is also stuck with terminating status.

1) psql accessed from dnsutils
 
 psql -h <namespace> -U postgres
psql: could not connect to server: Operation timed out
Is the server running on host "<namespace>" () and accepting
TCP/IP connections on port 5432?

2) pod status
```
        NAME                               READY   STATUS    RESTARTS   AGE
         pgpool-74cfbdb75c-rddgt   1/1     Terminating    0                  17m
         pgpool-74cfbdb75c-rz82n   1/1     Running        0                  6m31s
         postgresql-0                        1/1     Running        0                  17m
         postgresql-1                        1/1     Terminating    0                 17m
         postgresql-2                        1/1     Running        0                   17m
```

expected behavior:

the expected behavior was to psql pool be accessible after coming up on node3

Case2:   

replicaCount on pgpool is 1, replicaCount on postgresql is 2. there are 3 nodes(vms). The pgpool is on node2 and if node2 is goes down the pgpool creates new pod (pgpool-7859d5f5fc-62gm7   1/1     Running) but the old pod does not terminate completely (pgpool-7859d5f5fc-6n8fc   1/1     Terminating) and new pgpool pod is not accessible with its port. the postgresql pod on node2 is also stuck with terminating status and does not recreate pod on node3 or node1.

1) pod status:
NAME                            READY   STATUS  RESTARTS   AGE  IP  NODE   NOMINATED NODE READINESS GATES
pgpool-74cfbdb75c-rddgt   1/1     Terminating   0          18m     <IP> node2   <none>                       <none>
pgpool-74cfbdb75c-rz82n   1/1     Running       0          7m51s   <IP>   node3   <none>                    <none>
postgresql-0                        1/1     Running       0          18m     <IP>    node1   <none>                    <none>
postgresql-1                        1/1     Terminating   0          18m     <IP>   node2   <none>                   <none>
postgresql-2                        1/1     Running       0          18m     <IP>   node3   <none>                    <none>

expected behavior:

the expected behavior was to psql pool be accessible after coming up on node3 and postgresql-1 to come up on node1 or node3

**Comment by javsalgar** [comment]
Hi,

This seems to be more related to how the kube-controller-manager is not properly detecting that a node has gone down. However, the new pgpool node should be accessible without issues. Could you execute `kubectl get endpoints` to see to which pods the service is forwarding the requests?

**Comment by YoshithaR** [comment]
response of kubectl get endpoints->
BEFORE
```
sql       postgres-postgresql-ha-pgpool                10.233.108.51:5432                                                                60s
sql       postgres-postgresql-ha-postgresql            10.233.108.52:5432,10.233.67.177:5432                              60s
sql       postgres-postgresql-ha-postgresql-headless   10.233.108.52:5432,10.233.67.177:5432                        60s
```

AFTER bringing down node2 :

```
sql       postgres-postgresql-ha-pgpool                10.233.104.151:5432                                                12m
sql      postgres-postgresql-ha-postgresql            10.233.67.177:5432                                                 12m
sql      postgres-postgresql-ha-postgresql-headless   10.233.67.177:5432                                                 12m
```

LOGS on pg-pool pod:

2021-03-24 08:40:41: pid 138: LOG:  failover or failback event detected
2021-03-24 08:40:41: pid 138: DETAIL:  restarting myself
2021-03-24 08:40:41: pid 141: LOG:  failover or failback event detected
2021-03-24 08:40:41: pid 141: DETAIL:  restarting myself
2021-03-24 08:40:41: pid 142: LOG:  failover or failback event detected
2021-03-24 08:40:41: pid 142: DETAIL:  restarting myself
2021-03-24 08:40:41: pid 1: LOG:  fork a new child process with pid: 1369
2021-03-24 08:40:41: pid 1: LOG:  child process with pid: 126 exits with status 256
2021-03-24 08:40:41: pid 1: LOG:  fork a new child process with pid: 1370
2021-03-24 08:40:41: pid 1: LOG:  child process with pid: 131 exits with status 256
2021-03-24 08:40:41: pid 1: LOG:  fork a new child process with pid: 1371
2021-03-24 08:40:41: pid 1: LOG:  child process with pid: 132 exits with status 256
2021-03-24 08:40:41: pid 1: LOG:  fork a new child process with pid: 1372
2021-03-24 08:40:41: pid 1: LOG:  child process with pid: 133 exits with status 256

**Comment by javsalgar** [comment]
I see that the issue with the nodes stuck on terminating has been reported in the Kubernetes channel. 

https://github.com/kubernetes/kubernetes/issues/72226

I pinged in the thread so they can provide more feedback. I guess that, in the meantime, you may need to run helm upgrade to redeploy the pods.
