### ISSUE TITLE
Install Apache Airflow and Certificates

### ISSUE THREAD

**Issue by javsalgar** [bitnami/charts#5876]
Copied from here https://github.com/bitnami/kube-prod-runtime/issues/1145

> I am trying to install bitnami Airflow on BKPR to utilize the tls , logging and authorization features after install the image this error appears to me

> Error parsing headers: 'limit request headers fields size'

> but how to set ssl certificates for the webserver?

```
"AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT"
"AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY"
```

cc @raefezzeldin

**Comment by javsalgar** [comment]
About setting the SSL certificates for the web server, is it actually necessary if you are using Ingress?

**Comment by raefezzeldin** [comment]
I have removed as I am using Ingress and I hve enabled both flag ingress and certmanager and I am still getting the below error:

Error parsing headers: 'limit request headers fields size'

**Comment by raefezzeldin** [comment]
when I removed the following lines from the ingress it worked 👍 

nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User, X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-signin: https://auth.xxxxx.xxxxxx/oauth2/start?rd=%2F$server_name$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.XXXX.XXXXX/oauth2/auth

however I need to authenticate to LDAP first

**Comment by javsalgar** [comment]
Hi,

Good to know! Then, do you think there's anything we would need to change in the chart or it was a configuration issue?

**Comment by raefezzeldin** [comment]
Hi @javsalgar 

It was configuration issue. But I think we are missing some thing in the configuration in order to enable Oauth on airflow.

**Comment by javsalgar** [comment]
I'm curious if this error only happens in Airflow or you can see it in other applications you have deployed.

**Comment by raefezzeldin** [comment]
It is only for Airflow. The other applications is working fine (Grafana , Kibana)

**Comment by javsalgar** [comment]
I know that we are currently fixing an issue with Airflow and LDAP, not sure if it is related. cc @alvneiayu

**Comment by javsalgar** [comment]
You can set these keys by using the `extraEnvVars` section in the chart. Additionally, you could create a secret beforehand (or use the `extraDeploy` value) and mount it  with the `extraVolumes` and `extraVolumeMounts` values.
