### ISSUE TITLE
Scaling Bitnami/Moodle helm chart on Kubernetes cluster problem

### ISSUE THREAD

**Issue by Choogster1** [bitnami/charts#5880]
I'm having problems scaling Moodle which is deployed with the Bitnami/Moodle helm chart. I've deployed it with persistent storage along with Bitnami/MariaDB-Galera also with persistent storage. 

If I try to scale up the deployment, all the new containers that are created fall over with errors and never complete the ready state.

Is there a specific process for scaling up Moodle deployed with a helm chart? I know that the 'MoodleSkipInstall' flag is needed when using docker, but doesn't seem to have any effect if I  upgrade the helm chart with this set to true and then try scaling the deployment again.

Any pointers would be appreciated.

**Comment by juan131** [comment]
Hi @Choogster1 

As it's mentioned in the [Prerequisites](https://github.com/bitnami/charts/tree/master/bitnami/moodle#prerequisites), you need ReadWriteMany volumes for scaling. 

There's a blog post that explains how to do this using WordPress. A similar approach can be applied to Moodle. See:

- https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

**Comment by Choogster1** [comment]
Thanks, I'll take a look at the link. 

My persistent storage are all ReadWriteMany volumes.

**Comment by juan131** [comment]
> My persistent storage are all ReadWriteMany volumes.

In that case, please ensure you 1st install Moodle with only one replica. Once the pod reaches the "ready" status, scale your deployment to N replicas.

It's important since Moodle performs operations during the 1st boot that should be skipped once the data is generated.
