### ISSUE TITLE
Please fix solr chart volume permissions init container command

### ISSUE THREAD

**Issue by artur-reaboi** [bitnami/charts#5885]
**Which chart**:
solr

**Describe the bug**
The volume permissions init container command is wrong in solr StatefulSet.

**To Reproduce**
Just install the chart with volumePermissions.enabled=true.
The volume-permissions container logs the error:
`sh: 0: Can't open c`

**Expected behavior**
Volume permissions init container command must be successfully run.
This probably requires simply fixing the second parameter to be "-c" instead of just "c" in the following line:
https://github.com/bitnami/charts/blob/78a1a10eae089e7553494ba2dbdfc12f02601429/bitnami/solr/templates/statefulset.yaml#L72

**Version of Helm and Kubernetes**:
Helm 3.5.2
Kubernetes 1.20.4

**Comment by rafariossaa** [comment]
Hi,
  Thank you for spotting this.

**Comment by rafariossaa** [comment]
Hi,
  Could you check if this if fixed for you ?
