### ISSUE TITLE
Spark Pods Currently Spin Up One At A Time

### ISSUE THREAD

**Issue by drinkemc** [bitnami/charts#5887]
**Which chart**:
bitnami/spark helm chart

**Is your feature request related to a problem? Please describe.**
I am currently running a standalone spark cluster deployed with the bitnami/spark helm chart and noticed that during pod creation each pod waits for the one before it to complete its health check prior to being created which causes the cluster spin up time to increase dramatically when deploying a decent number of worker pods.  Is that intended behavior or is this something that I may have mis-configured?  

**Describe the solution you'd like**
Ideally all of the pods would spin up at the same time, but if that is not possible, then at least to spin up a bit faster.  Again, if this is something configurable that I have missed I would very much appreciate any adivce that you can offer.

**Comment by alemorcuq** [comment]
It is the intended behavior since we are using StatefulSets to manage the pods. It should be possible to support parallel deployment of pods changing the `podManagementPolicy` of the StatefulSets, but I don't know if that will work here. I will test it and come back to you.

**Comment by drinkemc** [comment]
Thanks so much!  I am currently trying to expand my knowledge of K8S and this is super helpful.

**Comment by alemorcuq** [comment]
I've created a PR adding a setting that will allow you to deploy the worker pods in parallel.
