### ISSUE TITLE
Support for OpenTelemetry

### ISSUE THREAD

**Issue by DanTulovsky** [bitnami/charts#5891]
**Which chart**:
Keycloak

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for OpenTelemetry.  It looks like OpenTracing is already supported (https://gist.github.com/thomasdarimont/43df478331d21ef4cc0a72241c257070), so perhaps being able to enable that is enough for now.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by migruiz4** [comment]
Hi @DanTulovsky ,

I think it would be possible to configure OpenTracing as described in the link you shared using the features the chart already has.

You could run `jaegertracing/all-in-one` using `kubectl run` or even add it as a sidecar container for keycloak, modify keycloak configuration using the `configuration` value or an `existingConfigmap`, and you could use an init container to run the jboss-cli in non-interactive mode (`./jboss-cli.sh --file=commands.cli`) and create the other files mentioned in the guide. 

Adding official support seems complicated considering it is a user guide and there is no information about this feature coming from official sources either from OpenTracing, OpenTelemetry, or Keycloak itself.

**Comment by timotoger** [comment]
I'd like to propose reevaluating to support this feature as it seems to have grown more mature in the upstream project:

https://www.keycloak.org/observability/tracing

Thank you kindly for your efforts

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
