### ISSUE TITLE
[bitnami/mongodb] How To Add Secondary Replica on New Node After Initial Replica Set Creation

### ISSUE THREAD

**Issue by asanderson** [bitnami/charts#5904]
**Which chart**:
bitnami/mongodb 10.10.1

**Describe the bug**
There does not seem to be a way to configure mongodb helm chart to add a secondary replica to an existing repliacset, since all replicas in a replicaset must be created simultaneously via initial *helm install*; i.e. when architecture is set to *replicaset* a primary replica is created which creates a new replicaset instead of adding to an existing one.  If there is a way to configure the helm chart to add a new *secondary replica* to an existing replicaset, please document how ito configure both in the readme file and documentation.

**To Reproduce**

1. Configure an initial replicaset on one node with a single replica and *helm install*.
2. Configure another replica on a different node and *helm install*.
3. Separate replicasets are created on each node instead of a single replicaset.

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:  v3.3.0

- Output of `kubectl version`:  client: v1.20.0, server: v1.19.4

**Additional context**
Also using Rancher v2.5.3 with authorized endpoint.

**Comment by andresbono** [comment]
Hi @asanderson, you should be able to execute the following commands to scale the MongoDB replicaset:

Install MongoDB with 2 replicas, 3 members (primary, secondary and Arbiter)
```console
$ helm install mongodb bitnami/mongodb \
    --set architecture=replicaset \
    --set auth.replicaSetKey=myreplicasetkey \
    --set auth.rootPassword=myrootpassword

$ kubectl exec -it mongodb-0 -- mongo --quiet -u root -p myrootpassword --eval 'rs.status().members.length'
3
```

Scale the replicaset with the `replicaCount` parameter and wait some time
```console
$ helm upgrade mongodb bitnami/mongodb \
    --set architecture=replicaset \
    --set auth.replicaSetKey=myreplicasetkey \
    --set auth.rootPassword=myrootpassword \
    --set replicaCount=3

$ kubectl exec -it mongodb-0 -- mongo --quiet -u root -p myrootpassword --eval 'rs.status().members.length'
4
```

**Comment by asanderson** [comment]
So, how do you specify the new replica goes on the new node?

**Comment by andresbono** [comment]
Oh, I forgot about that. Please check the affinity settings for that purpose: [Setting Pod's affinity](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#setting-pods-affinity).
