### ISSUE TITLE
Setting emptyDir keys/values in values.yaml

### ISSUE THREAD

**Issue by mavenir-labs** [bitnami/charts#5907]
Hi,
We are deploying etcd as our key store DB using helm 2 charts.
recently we stumbled upon performance issues . we saw that setting persistence: false  without setting volume to         emptyDir:
          medium: Memory  , did not actually changed anything .
However , setting the emptyDir keys is not possible w/o actually opening the chart , editing the statefulset.yaml and installing it.
I Would like to have an option to control the emptyDir keys/values outside the helm chart during install using --set ....
Or, advise for an optional way to do so,

Thanks,
Avi

**Comment by alemorcuq** [comment]
Hi, @mavenir-labs.

Thanks for the suggestion. Are you interested in contributing with a PR?
