### ISSUE TITLE
Add podManagementPolicy setting

### ISSUE THREAD

**Issue by artur-reaboi** [bitnami/charts#5912]
**Which chart**:
solr - master version

**Is your feature request related to a problem? Please describe.**
I think a podManagementPolicy setting in values would be helpful to control solr pods deployment. This would be in line with zookeeper chart, but actually very useful for the default case with cloudEnabled and cloudBootstrap set to true, which would give the first solr pod (solr-0) time to bootstrap the collection in zookeeper before starting next pods.

**Describe the solution you'd like**
Add podManagementPolicy with OrderedReady as default value in values.yaml.

**Comment by migruiz4** [comment]
Hi @artur-reaboi ,

Thank you for your suggestion

I have created this PR #5914 adding the podManagementPolicy feature as requested.

Let me know if it works for you.

**Comment by artur-reaboi** [comment]
Thanks!
