### ISSUE TITLE
[bitnami/solr] Solr stateful set pods crashing in loop

### ISSUE THREAD

**Issue by artur-reaboi** [bitnami/charts#5915]
**Which chart**:
solr 0.2.5

**Describe the bug**
Solr pods crash in loop, except the first one in the stateful set. Solr helm chart fails to install.

**To Reproduce**
1. Install solr helm chart with default options, using 'solr' as release name.
2. First pod in stateful set is running fine with the following log:
```
solr 09:51:13.85 
solr 09:51:13.86 Welcome to the Bitnami solr container
solr 09:51:13.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr 09:51:13.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr 09:51:13.86 
solr 09:51:13.86 INFO  ==> ** Starting solr setup **
solr 09:51:13.87 INFO  ==> Validating settings in SOLR_* env vars...
solr 09:51:13.88 INFO  ==> Initializing Solr ...
solr 09:51:13.91 INFO  ==> Configuring file permissions for Solr
solr 09:51:13.93 INFO  ==> Deploying Solr Cloud from scratch
solr 09:51:13.93 INFO  ==> Waiting for Zookeeper to be up
solr 09:51:25.95 INFO  ==> Waiting for solr root in zookeeper
solr 09:51:43.08 INFO  ==> Persisting Solr installation
solr 09:51:56.55 INFO  ==> ** solr setup finished! **
solr 09:51:56.56 INFO  ==> ** Starting solr **
...
```

3. After the first pod in stateful set is ready, other pods continuously fail with the following error:
```
solr 09:58:33.84 
solr 09:58:33.84 Welcome to the Bitnami solr container
solr 09:58:33.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr 09:58:33.84 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr 09:58:33.84 
solr 09:58:33.84 INFO  ==> ** Starting solr setup **
solr 09:58:33.86 INFO  ==> Validating settings in SOLR_* env vars...
solr 09:58:33.86 INFO  ==> Initializing Solr ...
solr 09:58:33.87 INFO  ==> Restoring persisted Solr installation
rm: cannot remove '/opt/bitnami/solr/server/solr/configsets/_default/conf/lang': Directory not empty
rm: cannot remove '/opt/bitnami/solr/server/solr/configsets/sample_techproducts_configs/conf/lang': Directory not empty
rm: cannot remove '/opt/bitnami/solr/server/solr/configsets/sample_techproducts_configs/conf/velocity': Directory not empty
rm: cannot remove '/opt/bitnami/solr/server/solr/configsets/sample_techproducts_configs/conf/xslt': Directory not empty
```
4. Helm installation finishes with error:
`Error: timed out waiting for the condition`

**Expected behavior**
Helm chart installation should succeed.

**Version of Helm and Kubernetes**:
Helm 3.5.2, Kubernetes 1.20.4, Rancher 2.5.7

**Comment by carrodher** [comment]
Hi, I am not able to reproduce the issue. Is it the first installation or are you reusing the name/namespace from a previous one? In that case, can you try removing the existing PVCs?

If the issue is not solved, can you also provide the output of `kubectl describe pod` in one of the failing pods?

**Comment by artur-reaboi** [comment]
No, it happens in a new namespace and I always delete the PVCs on retry. Could it be because of NFS used for volumes?
Anyway, let me try in another similar cluster.

**Comment by artur-reaboi** [comment]
Hmm, it works on another cluster. I will try to find out the difference between them and update this issue if concludent.
