### ISSUE TITLE
[bitnami/airflow] Add strict toleration and affinity settings on worker pods template 

### ISSUE THREAD

**Issue by tlperini** [bitnami/charts#5923]
**Which chart**:
name: airflow
version: 8.1.3

**Is your feature request related to a problem? Please describe.**
We need different toleration and affinity rules for worker pods. The idea is to run worker pods over one "kind" of k8s nodes and the web and scheduler pods over other "kind" of k8s nodes. Today we use toleration and node affinity rules in order to perform it.

**Describe the solution you'd like**
Add toleration and affinity settings inside the worker block in values.yaml. These settings should supersede the global settings.

**Additional context**
I'm already working on a PR.

**Comment by alemorcuq** [comment]
Thanks for the PR!
