### ISSUE TITLE
[bitnami/wordpress] how change default data path "/bitnami/wordpress"

### ISSUE THREAD

**Issue by corend** [bitnami/charts#5928]
**Which chart**:
wordpress

**Is your feature request related to a problem? Please describe.**
No, this is not related to a problem.

**Describe the solution you'd like**
I would like to have a parameter/values in the Wordpress values.yaml allowing to change the default path from "/bitnami/wordpress" to whatever we want "/anything/wordpress". I didn't find it in the current values, maybe I missed something. For Production purpose it could be really interesting to be able to do it.

**Describe alternatives you've considered**
Nothing.

**Comment by Mauraza** [comment]
Hi @corend,

The folder `/bitnami/wordpress`  is where the container saves the data https://github.com/bitnami/bitnami-docker-wordpress#persisting-your-application. This is something configured in the container image, no a variable.

**Comment by corend** [comment]
Indeed you're right, it should be fixed by making my custom container image. Thx
