### ISSUE TITLE
[btinami/kafka] Kafka-Exporter doesn't start with read only rootfs

### ISSUE THREAD

**Issue by sveba** [bitnami/charts#5931]
**Which chart**:
kafka 12.13.2 

**Describe the bug**
Kafka-Exporter Container dies with following log msg:
`bash: cannot create temp file for here-document: Read-only file system`

**To Reproduce**
create a PSP with norootfs and assign to default serviceuser

**Expected behavior**
Container can start with read-only root filesystem 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

The problem is here 
https://github.com/bitnami/charts/blob/4a55a6f18c53ada9b87db23819ed2df7527dddd2/bitnami/kafka/templates/kafka-metrics-deployment.yaml#L41

I start the container with `/bin/bash -c sleep infinity`
`I have no name!@kafka-exporter-647c66c687-lstrf:/opt/bitnami/kafka-exporter$ read -r -a sasl_passwords <<< "$(tr ',;' ' ' <<< "${SASL_USER_PASSWORD}")"
bash: cannot create temp file for here-document: Read-only file system
`

**Comment by marcosbc** [comment]
Thanks for reporting this @sveba! We usually don't support read-only FS where not even `/tmp` is writable, it is not a scenario we are testing so we cannot guarantee that it won't work in all cases.

That said, we are happy to accept external contributions like #5932 to fix or workaround any issues to get it working properly.
