### ISSUE TITLE
[bitnami/postgres-ha] Old primamry node is going in to out of sync If I delete primary node reapeatly

### ISSUE THREAD

**Issue by krishnachalla-hv** [bitnami/charts#5943]
**Which chart**:
Postgres-HA 6.7.0

**Describe the bug**
When we delete the primary nodes repeatedly old primary nodes are going int to out of sync state.

**To Reproduce**
I have installed the Postgres-HA chart with replica count as 4. For the 1st time **pg-0** elected as primary, I have accessed the application from UI And added a recorded into to one of the DB table. Immediately I deleted this primary, Now pg pool elected **Pg-1** as primary and I once again created another record in table and deleted it immediately. This time pg pool elected **pg-0** as primary, created the record once again deleted it immediately and pg pool elected elected **pg-1** as primary. Again created one other record in table deleted this primary also. Now pg pool elected **pg-2** as primary, **pg-0** and **pg-1** both are in out of sync.

**Expected behavior**
Data should 

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", 
GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Adding the screen shots and pg pool logs.

![Postgres replication issue-1](https://user-images.githubusercontent.com/60733731/112846701-f5b16c00-90c3-11eb-9292-ae08a137dfa3.png)
![postgres replication issue-2](https://user-images.githubusercontent.com/60733731/112846692-f34f1200-90c3-11eb-9151-314c797d5b64.png)
![postgres replication issue-3](https://user-images.githubusercontent.com/60733731/112846697-f518d580-90c3-11eb-85bd-fe4dbb4002b3.png)
![postgres repliction issue-4](https://user-images.githubusercontent.com/60733731/112846707-f64a0280-90c3-11eb-8e7b-be2778fcba3b.png)

**Pg pool log:**
[pgpool.log](https://github.com/bitnami/charts/files/6222137/pgpool.log)

**Comment by migruiz4** [comment]
Hi @krishnachalla-hv,

I tried to reproduce your issue but I wasn't able to.

Are you using a script to produce this behavior?

**Comment by krishnachalla-hv** [comment]
No I am using our own application UI which is connected to postgres DB. I am able to reproduce this issue like this, as soon as a record is created in primary node table I deleted primary node immediately then one of the salve become primary(Actually I ran spark job which write the data into postgres DB). I kept doing this for almost 5-6 times.

**Comment by marcosbc** [comment]
Hi @krishnachalla-hv, I've created an internal task to further investigate this.

However, note that PostgreSQL RepMgr takes some time for nodes to get in sync after you delete a primary, so if you delete it before the other nodes are aware of the new primary, this issue may happen. PostgreSQL with RepMgr is not a cloud-native app so it was not designed for removing/adding nodes quickly.

**Comment by krishnachalla-hv** [comment]
@marcosbc Thanks for the quick response!
I tried deleting the primary for only one time when the postgres cluster is up and running in healthy state and all the stands by are connected to primary, in that case also the old primary gone into out of sync state.

**Comment by marcosbc** [comment]
That seems rather strange, it is the first time I've seen something like that happening after deleting the primary for the first time.

Is it something you are able to reproduce easily after a new deployment? Or is it just something that happened once in one of your test cases? Please let us know if there is anything else that would be required for reproducing your scenarios, such as specific Helm inputs (`--set`) and configurations.

**Comment by rafariossaa** [comment]
Hi @krishnachalla-hv ,
  Did you have a chance to take a look to what @marcosbc indicated ?

**Comment by krishnachalla-hv** [comment]
Hi @rafariossaa,
Sorry, I didn't get a chance to work on this. I was busy little busy with the release. I will reproduce it and post my results here.

**Comment by krishnachalla-hv** [comment]
Hi @marcosbc,

Not always, It happened very few times. When I continuously deleted the primary node to test it and after that cleaned everything installed the chart again. Then I deleted the primary again, I ran into this issue.

**Comment by migruiz4** [comment]
Hi @krishnachalla-hv ,

Sorry for the late response, I tried again to reproduce this issue but I wasn't able to.

I ran the following commands as quickly as possible, but still the cluster didn't get out of sync:
```
#Install Posgresql-HA
helm install pg bitnami/postgresql-ha --set postgresql.replicaCount=4

#Start postgresql client
export POSTGRES_PASSWORD=$(kubectl get secret --namespace default pg-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run pg-postgresql-ha-client --rm --tty -i --restart='Never' --image docker.io/bitnami/postgresql-repmgr:11.11.0-debian-10-r58 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h pg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

#In postgresql CLI
select * from pg_stat_replication;
show pool_nodes;

CREATE TABLE sample (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255)
);

INSERT INTO 
    sample (username, firstname, lastname)
VALUES
    ('user1','Firstname','Lastname'),
    ('user2','Firstname','Lastname'),
    ('user3','Firstname','Lastname');

SELECT * FROM sample;

exit

#Had to run this twice, otherwise pgpool would select the same primary because of the node recovering too fast
kubectl delete pod pg-postgresql-ha-postgresql-0

export POSTGRES_PASSWORD=$(kubectl get secret --namespace default pg-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run pg-postgresql-ha-client --rm --tty -i --restart='Never' --image docker.io/bitnami/postgresql-repmgr:11.11.0-debian-10-r58 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h pg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

#In postgresql CLI again
select * from pg_stat_replication;
show pool_nodes;

INSERT INTO 
    sample (username, firstname, lastname)
VALUES
    ('user4','Firstname','Lastname'),
    ('user5','Firstname','Lastname'),
    ('user6','Firstname','Lastname');

exit

#Had to run this multiple times, otherwise pgpool would select the same primary because of the node recovering too fast
kubectl delete pod pg-postgresql-ha-postgresql-1

export POSTGRES_PASSWORD=$(kubectl get secret --namespace default pg-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run pg-postgresql-ha-client --rm --tty -i --restart='Never' --image docker.io/bitnami/postgresql-repmgr:11.11.0-debian-10-r58 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h pg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

#In postgresql CLI
select * from pg_stat_replication;
show pool_nodes;

INSERT INTO 
    sample (username, firstname, lastname)
VALUES
    ('user7','Firstname','Lastname'),
    ('user8','Firstname','Lastname'),
    ('user9','Firstname','Lastname');

exit

kubectl delete pod pg-postgresql-ha-postgresql-0

export POSTGRES_PASSWORD=$(kubectl get secret --namespace default pg-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run pg-postgresql-ha-client --rm --tty -i --restart='Never' --image docker.io/bitnami/postgresql-repmgr:11.11.0-debian-10-r58 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h pg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

#In postgresql CLI
select * from pg_stat_replication;
show pool_nodes;
```

As you suggested in your last comment, also tried to repeat the process after running
```
helm uninstall pg
kubectl delete pvc ...
```
But the result was the same.

**Comment by migruiz4** [comment]
It would be helpful if you could point out if we are doing something different or provide with the exact steps you are following, as it looks to me as if this issue only happens when forcing Postgresql into an specific race condition.
