### ISSUE TITLE
[bitnami/metallb] network policy support is broken

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#5945]
**Which chart**:
metallb 2.3.6

**Describe the bug**
enabling network policies causes helm intsall to fail with 

```
Helm upgrade failed: template: metallb/templates/networkpolicy.yaml:5:11: executing "metallb/templates/networkpolicy.yaml" at <include "metallb.fullname" .>: error calling include: template: no template "metallb.fullname" associated with template "gotpl"  
```
**To Reproduce**

Enable network policy supoport in the values.yaml

**Expected behavior**
network policies get created

**Comment by alvneiayu** [comment]
hi @MaxRink 

I did a patch to fix this issue. Let me know if you still have problems.

Thanks for your time

Álvaro
