### ISSUE TITLE
Mongo Credentials using credential file injected using vault.

### ISSUE THREAD

**Issue by gau31rav** [bitnami/charts#5948]
Which chart:
bitnami/mongodb 

Is your feature request related to a problem? Please describe.
We are trying to get Vault agent injector to provide the credentials used by Mongo so that there's a single source of truth for the secrets used in cluster. (https://www.vaultproject.io/docs/platform/k8s/injector)

Describe the solution you'd like
When the CredentialsFile is avaiable, it would be nice if mongo reads the credentials from the file mounted by Vault and then pass it as the required env variables. The format of credentials files can be made generic.

Same request has been made for other charts earlier.
https://github.com/bitnami/charts/issues/4422

**Comment by miguelaeh** [comment]
Hi @gau31rav ,
Would you like to create the PR adding that feature?
