### ISSUE TITLE
Nested Module dag issue 

### ISSUE THREAD

**Issue by reviewerTeam** [bitnami/charts#5952]
**Which chart**:
[airflow] version  v2.0.1

**Describe the bug**
In house nested Module in dag files throwing error .

`Broken DAG: [/opt/bitnami/airflow/dags/git-xyz-ftf/dxc/ftf_sil/operators/create_k8s_operators.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/git-xyz-ftf/dxc/ftf_sil/operators/create_k8s_operators.py", line 9, in <module>
    from xyz.ftf_sil.operators.adopted_K8s_op       import AdoptedK8sOperator
ModuleNotFoundError: No module named 'xyz'`

**To Reproduce**

- deploy helm chart
- add dags  from Github repo
- run dag with dependency

 xyz/dags/dagfiles
xyz/dxc/python module files
 

**Expected behavior**
**AdoptedK8sOperator** module found

.

**Additional context**
This very well may be a lack of my understanding of Airflow. This python module should be used by nested dag file/python code which is present in same folder

**Comment by carrodher** [comment]
In order to reproduce the issue on our side we would need the same code, dags, and more detailed steps; but looking into the error message it seems something related to the python code itself, I am not sure if it is going to be related to the Helm Chart or even the container image

**Comment by lukasstankiewicz** [comment]
@reviewerTeam I think you may be missing PYTHONPATH to your dags clone from repo;
 ```
      - name: PYTHONPATH
      value: "${PYTHONPATH}:/opt/bitnami/airflow/dags/:/opt/bitnami/airflow/dags/git-data-airflow-pipelines/:/opt/bitnami/python/lib/python3.8/site-packages/"
```
