### ISSUE TITLE
[bitnami/airflow] pip install of apache-airflow-providers-odbc fails / mssql access not possible

### ISSUE THREAD

**Issue by ShawnMcGough** [bitnami/charts#5970]
**Which chart**:
airflow 8.1.3

**Describe the bug**
Generally, the image does not provide a solution for accessing mssql databases. The image contains the `apache-airflow-providers-microsoft-mssql` provider, implying support.

Specifically, the `apache-airflow-providers-odbc` provider fails to install (see detailed output below)

**To Reproduce**
1. Attempt to use pre-installed mssql provider (see below for sample DAG).
and/or
2. `pip install apache-airflow-providers-odbc`

**Expected behavior**
1. pre-installed mssql provider allows mssql access
and/or
2. `apache-airflow-providers-odbc` installs successfully with no errors.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The pre-installed `apache-airflow-providers-microsoft-mssql` provider has been deprecated in favor of the `apache-airflow-providers-odbc` provider.

When attempting to utilize the pre-installed `apache-airflow-providers-microsoft-mssql` provider, the following DAG fails to import.

```python
import datetime as dt
import time
from airflow import DAG
from airflow.providers.microsoft.mssql.operators.mssql import MsSqlOperator

default_args = {
    'owner': 'airflow',
    'start_date': dt.datetime(2019, 11, 8, 23, 00, 00),
    'concurrency': 1,
    'retries': 0
}

dag = DAG(
    dag_id='test_mssql',
    default_args=args,
    schedule_interval=None,
    start_date=datetime(2020, 1, 1),
    tags=['example'],
)

sql_command = """SELECT @@SERVERNAME AS 'Server Name';"""
t1 = MsSqlOperator(task_id='selecting_server_name',
                   mssql_conn_id='mssql_default',
                   sql=sql_command,
                   dag=dag,
                   database='dbname',
                   autocommit=True)

t1
```
*Error message*
```
Broken DAG: [/opt/bitnami/airflow/dags/git_dna/test_mssql_simple.py] Traceback (most recent call last):
  File "/opt/bitnami/airflow/dags/git_dna/test_mssql_simple.py", line 5, in <module>
    from airflow.providers.microsoft.mssql.operators.mssql import MsSqlOperator
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 23, in <module>
    from airflow.providers.odbc.hooks.odbc import OdbcHook
ModuleNotFoundError: No module named 'airflow.providers.odbc'
```
**Deprecation of apache-airflow-providers-microsoft-mssql**

The Airflow docs state:
>This module is deprecated due to the discontinuation of the pymssql project. See https://github.com/pymssql/pymssql/issues/668. Support for pymssql will be removed in Airflow 2.0. Please use odbc.

Additionally, the MSSQL Driver is required:
>This connection type uses pyodbc, which has some system dependencies, as documented on the pyodbc wiki. You must also install a driver.
http://airflow.apache.org/docs/apache-airflow-providers-odbc/stable/connections/odbc.html

**Detailed error**
```
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py): started
  Building wheel for pyodbc (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/bitnami/airflow/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q4cw5y98
       cwd: /tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -s -s -fPIC -DPYODBC_VERSION=4.0.30 -I/opt/bitnami/airflow/venv/include -I/opt/bitnami/python/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc, azure-storage-blob, azure-mgmt-datafactory, apache-airflow-providers-odbc, apache-airflow-providers-microsoft-azure
    Running setup.py install for pyodbc: started
    Running setup.py install for pyodbc: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/bitnami/airflow/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xfu4azcc/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bitnami/airflow/venv/include/site/python3.8/pyodbc
         cwd: /tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/
    Complete output (10 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -s -s -fPIC -DPYODBC_VERSION=4.0.30 -I/opt/bitnami/airflow/venv/include -I/opt/bitnami/python/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bitnami/airflow/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eaqmhwr6/pyodbc_437ff2b7991d45f5b01e74d774ce3dca/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xfu4azcc/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bitnami/airflow/venv/include/site/python3.8/pyodbc Check the logs for full command output.
```

**Comment by alemorcuq** [comment]
Hi, @ShawnMcGough.

Unfortunately, due to license issues we can't ship the MS SQL ODBC driver in our images. You would need to extend our image to install it and the ODBC provider yourself. 

Regarding the error you are getting when installing the ODBC provider:

```
    unable to execute 'gcc': No such file or directory
```

You need to install `gcc` in order to build the provider.

**Comment by ShawnMcGough** [comment]
@alemorcuq Thanks. I didn't consider licensing issues. 

I had already started down the path of extending the image to install the handful of requirements to enable mssql support. Are you aware of any documentation on best practices for extending bitnami images?

**Comment by marcosbc** [comment]
Hi @ShawnMcGough, for the Airflow container it doesn't look like we have added any "Customize this image" section in the README.

However, you can find an [example for the Apache container here](https://github.com/bitnami/bitnami-docker-apache#customize-this-image).

We haven't collected any set of best practices though. But in general, I would recommend this:

* Reproducible builds: If possible, avoid rolling tags in the `FROM` command (and instead use full tag name, i.e. `2.4.46-debian-10-r214`). If needed to update, you can do that manually by changing the tag and re-building.
* Non-root user: If you override `USER` then reset it to the previous value afterwards.
* Permissions: Make sure to install files with protective permissions. Readable files would generally be owned by `root:root` with `644` permissions (`755` for folders) while writable files would need the additional `g+x` permission.

**Comment by ShawnMcGough** [comment]
@marcosbc thanks,very helpful.

I will close this issue.

I do think removing the `apache-airflow-providers-microsoft-mssql` provider from the image(s) would clear up some confusion.  Let me know if you'd like me to create a seperate issue for that (perhaps on the [bitnami-docker-airflow repo](https://github.com/bitnami/bitnami-docker-airflow/)).
