### ISSUE TITLE
Could not access Kafka brokers from outside the cluster using NodePort option

### ISSUE THREAD

**Issue by zbeedatm** [bitnami/charts#5975]
**Which chart**:
bitnami/kafka
https://github.com/bitnami/charts/tree/master/bitnami/kafka/#installing-the-chart

**Describe the bug**
Could not accessing Kafka brokers from outside the cluster using NodePort option

**To Reproduce**

Note: using minikube on Windows

We followed the instruction in section "Using NodePort service" in the link: https://github.com/bitnami/charts/tree/master/bitnami/kafka/#installing-the-chart

$ helm install kafka bitnami/kafka --set externalAccess.enabled=true --set externalAccess.service.type=NodePort --set externalAccess.autoDiscovery.enabled=true --set serviceAccount.create=true --set rbac.create=true

$ kubectl get pods
NAME                READY   STATUS    RESTARTS   AGE
kafka-0             1/1     Running   0          5m5s
kafka-zookeeper-0   1/1     Running   0          5m5s

$ kubectl get svc
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kafka                      ClusterIP   10.103.19.3     <none>        9092/TCP                     5m29s
kafka-0-external           NodePort    10.111.165.26   <none>        9094:30860/TCP               5m29s
kafka-headless             ClusterIP   None            <none>        9092/TCP,9093/TCP            5m29s
kafka-zookeeper            ClusterIP   10.97.173.24    <none>        2181/TCP,2888/TCP,3888/TCP   5m29s
kafka-zookeeper-headless   ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   5m29s
kubernetes                 ClusterIP   10.96.0.1       <none>        443/TCP                      6m8s

Port forwarding (for NodePort - https://minikube.sigs.k8s.io/docs/start/):
$  kubectl port-forward service/kafka-0-external 9094:9094
Forwarding from 127.0.0.1:9094 -> 9094
Forwarding from [::1]:9094 -> 9094

Trying to create topic with python:

`
   from kafka.admin import KafkaAdminClient, NewTopic
   admin_client = KafkaAdminClient(
       bootstrap_servers="127.0.0.1:9094",
       client_id='0',
   )
   topic_list = []
   topic_list.append(NewTopic(name="example_topic1", num_partitions=1, replication_factor=1))
   admin_client.create_to
`

and getting:

> Traceback (most recent call last):
........
 packages\kafka\conn.py", line 1240, in check_version
    raise Errors.NodeNotReadyError()
kafka.errors.NodeNotReadyError: NodeNotReadyError

**Expected behavior**
Should access the external brocker and a topic should be created. Since:
1. We defined external access -as described for NodePort-
2. All the services are up and running (as shown above)

Important::
When using LoadBalancer option for external access -instead of NodePort- it works.
(We used a minikube tunnel in this case)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by marcosbc** [comment]
Hi @zbeedatm, note that by using NodePort, you are supposed to access the Kafka client via `<node IP>:<node port>`, not doing a local port forward. It won't work that way.

Also, it would be useful if you could try the official Kafka clients and check the errors, they are usually more verbose.

**Comment by tampler** [comment]
Hello! I'm facing the same issue

Kuber: 1.20.5
Helm: 3.5.3
Istio: 1.9.2
Image: docker.io/bitnami/kafka:2.7.0-debian-10-r100

I'm launching Kafka with the following:
```bash
        @helm install --namespace ${ns} ${name} bitnami/kafka \        
        --set image.debug=true \
        --set externalAccess.enabled=true \
        --set externalAccess.service.type=NodePort \
        --set externalAccess.service.nodePorts[0]='30887' \
```
And I'm able to access it externally, which I test the following way:
`curl -v telnet://<LoadBalancer-IP>:30887`

And getting this in the Kafka pod:
```bash
grant-kafka-0 kafka [2021-04-02 16:57:27,572] WARN [SocketServer brokerId=0] Unexpected error from /127.0.0.1; closing connection (org.apache.kafka.common.network.Selector)
grant-kafka-0 kafka org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1634952294 larger than 104857600)
grant-kafka-0 kafka     at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
grant-kafka-0 kafka     at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
grant-kafka-0 kafka     at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
grant-kafka-0 kafka     at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
```
Which is **OKAY**, since I'm sending a trash with `curl` connection to this port.

However, my `kafka` clients can't read broker topics and I don't know how to debug this.

Please advice

Best,
Boris

**Comment by zbeedatm** [comment]
> Hi @zbeedatm, note that by using NodePort, you are supposed to access the Kafka client via `<node IP>:<node port>`, not doing a local port forward. It won't work that way.
> 
> Also, it would be useful if you could try the official Kafka clients and check the errors, they are usually more verbose.

ًًWe installed minikub in windows (https://minikube.sigs.k8s.io/docs/start/) and following step 4, we need to do port forwoard since we do not have access from outside for the service IP

**Comment by marcosbc** [comment]
@tampler and @zbeedatm  Could you try running the official Kafka client(s) and check what output is shown?

Like I mentioned earlier, they are more verbose and are likely to show more useful errors.

**Comment by tampler** [comment]
Hello @marcosbc 

Yes, I'll try official Kafka client now. Meanwhile, could you provide any links to github projects/blogs/articles, which use this Kafka chart? Perhaps, we are missing smth and a good example will do the job

Thanks !

**Comment by tampler** [comment]
After looking into the container config, I found the following: 

`kubectl exec -it grant-kafka-0 -n kafka -- cat /opt/bitnami/kafka/config/server.properties | grep advertised.listeners`

---
`advertised.listeners=INTERNAL://grant-kafka-0.grant-kafka-headless.kafka.svc.cluster.local:9093,CLIENT://grant-kafka-0.grant-kafka-headless.kafka.svc.cluster.local:9092,EXTERNAL://:30887`

So it seems like the default chart doesn't allow external access thru a pod FQDN, even after I deploy this with the following config:

```bash
 @helm install --namespace ${ns} ${name} bitnami/kafka \
  --set image.debug=true \
  --set externalAccess.enabled=true \
  --set externalAccess.service.type=NodePort \
  --set externalAccess.service.nodePorts[0]='30887' \
```

**Comment by tampler** [comment]
I finally figured out a solution, using [this](https://github.com/bitnami/charts/issues/4240) issue. My chart looks like this now:
```bash
        @helm install --namespace ${ns} ${name} bitnami/kafka \        
        --set externalAccess.enabled=true \
        --set externalAccess.service.type=NodePort \
        --set externalAccess.service.nodePorts[0]=${kafka_nodePort} \
        --set rbac.create=true \
        -f init.yml
```
And the `init.yml` looks like this:
```yaml
externalAccess:
  enabled: true
  service:
    type: NodePort
  autoDiscovery:
    enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
```
Which yields in a nice auto detection and a working Kafka:

```shell
Use 'kubectl describe pod/grant-kafka-0 -n kafka' to see all of the containers in this pod.
advertised.listeners=INTERNAL://grant-kafka-0.grant-kafka-headless.kafka.svc.cluster.local:9093,CLIENT://grant-kafka-0.grant-kafka-headless.kafka.svc.cluster.local:9092,EXTERNAL://10.205.0.137:30887
```

**Comment by marcosbc** [comment]
That's awesome! Thanks for sharing it.

**Comment by rightx2** [comment]
@tampler I've followed your solution but `./kafka-topics.sh --list MY_LOCAL_STATIC_IP:30887` gave me an timeout error... which might be better because it was not connection error at least..
