### ISSUE TITLE
Postgresql Helm Chart doesn't expose password by default as subchart dependency

### ISSUE THREAD

**Issue by seekheart** [bitnami/charts#5978]
**Which chart**:
postgresql

**Is your feature request related to a problem? Please describe.**
I would like to request that the postgresql helm chart have a way to pass the generated password to a parent chart that uses it as a dependency. Currently the default values file has the password params in the `values.yaml` commented and thus cannot be overridden when being used as a subchart.

**Describe the solution you'd like**
I would like either the `postgresqlPassword` kv to be exposed by default or a kv that allows me to access generated password or to override with a password of my own.

**Describe alternatives you've considered**
n/a

**Additional context**
I need this for creating my own app chart that needs a postgresql db.

**Comment by marcosbc** [comment]
Hi @seekheart, unfortunately I don't think there's any way to support that. You could, however, provide an existing secret name to the chart via [`existingSecret`](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L146). That way, you would have to create it before deploying, but the PostgreSQL password could then be used by both the PostgreSQL chart and the parent chart.

**Comment by seekheart** [comment]
> Hi @seekheart, unfortunately I don't think there's any way to support that (mostly due to Helm limitations). You could, however, provide an existing secret name to the chart via [`existingSecret`](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L146). That way, you would have to create it before deploying, but the PostgreSQL password could then be used by both the PostgreSQL chart and the parent chart.

The problem though is if we look at [ values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L146) `existingSecret` is also commented out so there's nothing to link...

**Comment by javsalgar** [comment]
Hi,

I'm not sure if I follow. The fact that the value is commented out doesn't mean it will not be used. If you set `postgresqlPassword` in your parent chart, that value will be passed to the subchart and you can use it in your parent chart for creating secrets or whatever your deployment requires. Am I missing anything?

**Comment by seekheart** [comment]
> Hi,
> 
> I'm not sure if I follow. The fact that the value is commented out doesn't mean it will not be used. If you set `postgresqlPassword` in your parent chart, that value will be passed to the subchart and you can use it in your parent chart for creating secrets or whatever your deployment requires. Am I missing anything?

I've tried doing so, but it still does not render the password, it just autogenerates a new one.

**Comment by miguelaeh** [comment]
Hi @seekheart ,
As @javsalgar commented, it should be possible to specify it from the parent chart. Could you share how are you setting it? It is difficult to tell you why it is not working for you without the context.

**Comment by seekheart** [comment]
> Hi @seekheart ,
> As @javsalgar commented, it should be possible to specify it from the parent chart. Could you share how are you setting it? It is difficult to tell you why it is not working for you without the context.

Sure, this the part of my chart that calls the subchart.

```
postgresql:
  postgresqlUsername: "blah"
  postgresqlPassword: "some password"
```

**Comment by miguelaeh** [comment]
Hi @seekheart ,
I re-checked that there is not an issue in the PostgreSQL chart. In principle what you shared seems to be correct, but you can check for example the redmine chart of this repo which uses postgresql and the password is properly set.
