### ISSUE TITLE
[bitnami/kafka] Add serviceAccount to Kafka metrics deployment

### ISSUE THREAD

**Issue by mehta-ankit** [bitnami/charts#5980]
**Which chart**:
bitnami/kafka - 12.15.0

**Is your feature request related to a problem? Please describe.**
Currently there is no way to attach a serviceAccount to the kafka exporter pod

**Describe the solution you'd like**
Similar to how Kafka statefulset has serviceAccount attached to it:https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L97
we should have it for kafka metrics deployment: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/kafka-metrics-deployment.yaml

**Describe alternatives you've considered**

**Additional context**
If using the same serviceAccount is fine for metrics deployment, i am happy to spin up a PR.

**Comment by marcosbc** [comment]
Hi @mehta-ankit, it looks like a fairly simple change, would you be up for contributing the fix via a PR?

**Comment by mehta-ankit** [comment]
Yup, i ll be happy to. 👍🏻
