### ISSUE TITLE
[bitnami/nginx-ingress-controller] default defaultBackend returns HTTP 200 on /

### ISSUE THREAD

**Issue by NMFR** [bitnami/charts#5981]
**Which chart**:
bitnami/nginx-ingress-controller:7.4.8

**Describe the bug**
According to https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/ the defaultBackend should return:
- HTTP 200 for the `/healthz` endpoint.
- HTTP 404 for the `/` endpoint. 
- Not referenced in the docs but other endpoints should return HTTP 404.

The bitnami/nginx-ingress-controller:7.4.8 default defaultBackend returns HTTP 200 for endpoints where it should return HTTP 404.

**To Reproduce**
For example, if we install the nginx-ingress-controller:
```
helm upgrade ingress-controller bitnami/nginx-ingress-controller --install
``` 

and grab the IP of the ingress controller service: 
```
kubectl get service
```

making calls to the IP directly should call the defaultBackend:

`curl`ing `/` should give HTTP 404, but it incorrectly returns HTTP 200:
```
curl http://172.31.0.6/ -I         
HTTP/1.1 200 OK
```

`curl`ing `/index.html` should give HTTP 404, but it incorrectly returns HTTP 200:
```
curl http://172.31.0.6/index.html -I
HTTP/1.1 200 OK
```

`curl`ing `/50x.html` should give HTTP 404, but it incorrectly returns HTTP 200:
```
curl http://172.31.0.6/50x.html -I  
HTTP/1.1 200 OK
```

**Expected behavior**
The default defaultBackend should follow the behaviour described in https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/ .

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:03:54Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The default defaultBackend is a bitnami/nginx image with not special configuration. This image already includes a index.html and a 50x.html files. The existence of this files or the usage of the default nginx configuration is causing this issue.

Also as an additional note (perhaps this should be discussed in a separate issue?): There is no way to customize the defaultBackend volumes in this chart. This means that the only way to customize the HTTP 404 html page is creating a custom container image. If it was possible to configure volume mounts (from a `ConfigMap` for example) for the defaultBackend a simple mount on `/opt/bitnami/nginx/conf/bitnami/nginx.conf` and `/app` would allow to configure custom HTML error pages without the need to create a new container image for this purpose.

**Comment by NMFR** [comment]
I am available to help in a PR.

**Comment by marcosbc** [comment]
Hi @NMFR, thanks for reporting this! It indeeds look like a minor bug. We should be able to provide a custom NGINX configuration to reproduce the expected  functionality of the official image:

* HTTP 200 for the /healthz endpoint.
* HTTP 404 for the / endpoint.

I.e. by mounting a server block like this:

```
server {
  listen 0.0.0.0:8080;
  # Catch-all server block
  # See: https://nginx.org/en/docs/http/server_names.html#miscellaneous_names
  server_name _;
  location /healthz {
    return 200;
  }
  location / {
    return 404;
  }
```

If you think it makes sense and would be available for contributing via a PR, that would be awesome!

**Comment by NMFR** [comment]
Hello, makes sense.

### Solution 1:

Adding a new `defaultBackend.serverBlockConfig` value who's default would be:

```
location /healthz {
  return 200;
}

location / {
  return 404;
}
```

This value would end up in a `ConfigMap` that would be mounted in the defaultBackend @ `/opt/bitnami/nginx/conf/bitnami/defaultBackend.conf`. This works because the `bitnami/nginx` image's main nginx configuration does a `include  "/opt/bitnami/nginx/conf/bitnami/*.conf";` inside the default server block.

This solution allows the chart user to change the nginx configuration of the defaultBackend as he pleases.

The drawback is that we kind of assume that everyone will be using a `bitnami/nginx` image as a defaultBackend. This kind of breaks the use case of the charts user changing the `defaultBackend.image`.

### Solution 2:

Create a `bitnami/nginx-ingress-controller-default-backend` image. This would be based off the `bitnami/nginx` image and we just would be adding the:

```
location /healthz {
  return 200;
}

location / {
  return 404;
}
```

nginx conf.
This new `bitnami/nginx-ingress-controller-default-backend` image would became the default `defaultBackend.image` of the bitnami/nginx-ingress-controller chart.
Additionally we could add `defaultBackend.extraVolumes` and `defaultBackend.extraVolumeMounts` helm values to help users further customize the defaultBackend.

Any thoughts?
Once i get feedback i can start working on a PR for this.

**Comment by marcosbc** [comment]
From our point of view, solution 1 is better because it requires less maintainability, solution 2 would require to maintain a new Docker image that just contains NGINX (meaning it would be almost a duplicated image).

>The drawback is that we kind of assume that everyone will be using a `bitnami/nginx` image as a `defaultBackend`. This kind of breaks the use case of the charts user changing the `defaultBackend.image`.

Well, if a user changes `defaultBackend.image`, the only difference would be there existing a new file in the `/opt/bitnami/nginx/conf/bitnami`, right? Wouldn't that work with any non-Bitnami image anyways? I think that the only thing that would happen is that non-Bitnami images would not get that configuration applied.

**Comment by NMFR** [comment]
I still see solution 2 as the optimal one. But i do trust in your experience in measuring gain vs cost & maintainability. 

I will be doing a PR for solution 1.
