### ISSUE TITLE
[bitnami/airflow] 502 Bad Gateway with Airflow 2.x

### ISSUE THREAD

**Issue by phodamentals** [bitnami/charts#5982]
Hi. Has anyone had issues with Airflow 2.x on EKS with Application Load Balancer (using NodePort)? 

Getting 502s when hitting the ingress address. Security Groups, IAM policy, and RBAC look good as well.

I've re-created policies, cluster deployment, roles, policies, and paths and still get the same result.

**Comment by marcosbc** [comment]
Hi @phodamentals, could you describe your setup in further depth? Also, I'm a bit confused with this:

> ... (using **NodePort**)?
> Getting 502s when hitting the **ingress** address

Do you mean that you are using the ingress address with the nodeport?
