### ISSUE TITLE
[bitnami/elasticsearch] Allow adding arguments to exporter in order to enable metrics

### ISSUE THREAD

**Issue by lorisepita** [bitnami/charts#5987]
**Which chart**:
elasticsearch

**Is your feature request related to a problem? Please describe.**
Some metrics are not enabled (e.g.: snapshot metrics, indices metrics...) by default on the exporter and the are no way to enable them.
For now, the exporter enable `es.all` which does not enable **all** metrics.

**Describe the solution you'd like**
There are a few ways to solve this:
- add a `metrics.extraArgs` empty by default that allows to add args.
- add a `metrics.exportedMetrics` that contains by default `es.all`.
The changes would mainly be done in [this file](https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/metrics-deploy.yaml#L47)

**Describe alternatives you've considered**
I have considered making my own docker image of the exporter and using it instead of the bitnami one, but considering this feature would not change to the default behavior of the exporter and be useful to other users, I have decided to open an issue.

**Comment by javsalgar** [comment]
Hi,

I think that `extraArgs` is the solution that is more consistent with other chars. Would you like to submit a PR adding that feature? It would speed up the process of having that feature in the chart.

**Comment by lorisepita** [comment]
Hi,

Thank you for you answer ! I am working on it, I'll submit it as soon as it is ready.
