### ISSUE TITLE
[bitnami/MongoDB]Unable to connect to the MongoDB database using a username/password

### ISSUE THREAD

**Issue by SellamiRami** [bitnami/charts#5993]
**Which chart**:
The MongoDB Helm Chart  (V10.11.1)

**Describe the bug**
I want to integrate the Helm Chart of MongoDB with Adminer. 
I assume that I correctly configured the values.yaml of MongoDB Helm Chart. When, I try to access to the database using the new user credentials (`admin/password1`), I get an "authentication failed" message. 
I want to highlight that the user is correctly created in the MongoDB database because I'm able to see it when I am connected as a `root` in Adminer (See the screenshot below).

<img width="1440" alt="Capture d’écran 2021-04-02 à 15 17 53" src="https://user-images.githubusercontent.com/3645720/113418907-b25a4480-93c6-11eb-9750-a4407ed4c825.png">

The values.yaml:
```yaml
...
mongodb:
  enabled: true
  clusterDomain: "fadi-mongodb"
  persistence:
    enabled: true
  auth:
    enabled: true
    username: "admin"
    rootPassword: "password1"
    password: "password1"
    database: "fadi"
...
```
The chart.yaml:
```yaml
...
dependencies:
...
- name: mongodb
  version: ~10.11.1
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
```
**Expected behavior**
Being able to connect in adminer using the credentials `admin/password1` in the database called `fadi`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Could you please help me in fixing my problem. I'm very thankful in advance for your help.

**Comment by migruiz4** [comment]
Hi @SellamiRami ,

Please keep in mind that the custom username and database will only take effect when the MongoDB pod runs for the first time: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run

If you already had a MongoDB PVC when configured them, these settings won't take effect:
```
    rootPassword: "password1"
    password: "password1"
    database: "fadi"
```

You can check if your custom username and database are properly configured using the following commands:
```bash
$ kubectl run --namespace default mongo-test-mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.4.4-debian-10-r41 --command -- bash

$ mongo -u admin -p password1 --authenticationDatabase fadi --host "your_mongo_servicename"
```


The expected output would be:
```bash
$ kubectl run --namespace default mongo-test-mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.4.4-debian-10-r41 --command -- bash

I have no name!@mongo-test-mongodb-client:/$ mongo -u admin -p password1 --authenticationDatabase fadi --host "mongo-test-mongodb" 
MongoDB shell version v4.4.4
connecting to: mongodb://mongo-test-mongodb:27017/?authSource=fadi&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("d6f9749a-e95c-4941-9301-673b47b162dc") }
MongoDB server version: 4.4.4
```

**Comment by SellamiRami** [comment]
Hello @migruiz4 , Thank you for your detailed response. 

I did not get the expected output like you. I get an error message when I run the `mongo` command line.

```
I have no name!@mongo-test-mongodb-client:/$ mongo -u admin -p password1 --authenticationDatabase fadi --host "mongo-test-mongodb"
MongoDB shell version v4.4.4
connecting to: mongodb://mongo-test-mongodb:27017/?authSource=fadi&compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server mongo-test-mongodb:27017, connection attempt failed: HostNotFound: Could not find address for mongo-test-mongodb:27017: SocketException: Host not found (authoritative) :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
```
Do you have an idea about this error?
Thank you in advance for your response.
Rami.

**Comment by migruiz4** [comment]
In your command, I see you used `--host "mongo-test-mongodb"`:
> mongo -u admin -p password1 --authenticationDatabase fadi --host "mongo-test-mongodb"

You will need to replace `mongo-test-mongodb` with your mongo service name. You can get it using the command `kubectl get service`, and the name should be `<release_name>-mongodb`.

**Comment by SellamiRami** [comment]
I get the same error message : 

```
I have no name!@fadi-mongodb:/$ mongo -u admin -p password1 --authenticationDatabase fadi --host "fadi-mongodb"
MongoDB shell version v4.4.4
connecting to: mongodb://fadi-mongodb:27017/?authSource=fadi&compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server fadi-mongodb:27017, connection attempt failed: SocketException: Error connecting to fadi-mongodb:27017 (172.17.0.8:27017) :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
```
I suppose that the configuration of the new username is not correctly set up. Is there some other configuration that I should add ?

**Comment by SellamiRami** [comment]
I want to highlight that when I create a new database from Adminer using the root account, the database is not created. I'm wondering if it is related to the creation of the accounts or it is another problem?

**Comment by migruiz4** [comment]
Looks like your MongoDB is refusing the connection coming from the client pod. Maybe you could try connecting directly from the MongoDB pod:

```
$ kubectl exec -it <your_mongodb_pod> -- bash
$ mongo -u admin -p password1 --authenticationDatabase fadi
```

Although, that should not be required unless you modified your MongoDB configuration. 
Do you have any additional configuration to the specified in your first comment? Does this issue happen when installing the MongoDB chart standalone?

**Comment by SellamiRami** [comment]
Hello @migruiz4 thank you for your response. Yes I succeeded to access in the MongoDB pod and to access to the `fadi` database following your recommendation. 
I want also to precise that installing MongoDB chart in a standalone way works without any problem. 
I think that the problem here is linked to the connection between Adminer and MongoDB.

**Comment by migruiz4** [comment]
Hi @SellamiRami,

Being able to log in using the mongodb client but not Adminer aims that this could be an issue with your chart/application or with Adminer itself. If that is the case, I may not be able to help you fix the issues with Adminer as it would be out of our scope.

I'd recommend checking Adminer forums looking for similar issues or contacting them there with your issues: https://sourceforge.net/p/adminer/discussion/

**Comment by SellamiRami** [comment]
Yes, I agree with you that the problem should be related more to the Adminer configuration. I've posted an issue in the Adminer forum and I hope that I get efficient  help and support like here. 
Thank you very much @migruiz4

**Comment by migruiz4** [comment]
You're welcome! 

I hope you find a fix for this issue soon and I'm glad you found my help useful. 
If you have any further issues we will be happy to help.

**Comment by SellamiRami** [comment]
Hello @migmartri , hello all, 
I come back to my issue since I still have the same problem. I'm not very sure that the problem is related to the Adminer. In fact, I dropped Adminer and I am testing MongoDB Compass. 

I am using the values.yaml above. 

I make the port forward using the following command `kubectl port-forward -n default svc/fadi-mongodb 27017:27017`. 

In Compass, I succeeded to connect using the root account using `mongodb://root:password1@localhost:27017/admin` connection string.

Howeve, when I want to connect using the new username (admin/password1), I get the same error message in Adminer `Authentication failed`. I want to highlight that when I am connected as a root, I did not find the database `fadi ` that I specified in my values.yaml.

Do you have an idea about this issue?

**Comment by migruiz4** [comment]
Hi @SellamiRami ,

To troubleshoot this issue, could you please follow these steps?

- Uninstall your release and clean up the Mongodb PVC
```bash
#Uninstall your chart
$ helm uninstall <my_release>
#Clean up your PVCs for a fresh install
$ kubectl get pvc
$ kubectl delete pvc <mongodb-pvc>
```

- Reinstall your chart using these values:
```
#Use this values
$ cat values.yaml
mongodb:
  enabled: true
  persistence:
    enabled: true
  auth:
    enabled: true
    username: "admin"
    rootPassword: "password1"
    password: "password1"
    database: "fadi"
#
$ helm install <my_release> <my_chart> -f values.yaml
```

- Start a MongoDB client
```bash
$ export MONGODB_ROOT_PASSWORD="password1"
$ kubectl run mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.4.5-debian-10-r0 --command -- bash
## Inside the client pod, run the following commands
# Open a mongoshell session as user 'root'
$ mongo admin --host "<my_release>-mongodb" --authenticationDatabase admin -u root -p "password1"
...
# Get all users and check user 'admin' exists in DB 'fadi'
> db.system.users.find()
{ "_id" : "admin.root", "userId" : UUID("57e51070-bb1f-4893-9d29-2e29adc4409c"), "user" : "root", "db" : "admin", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "s2lRwSuAy7lXCU4GRpedNw==", "storedKey" : "Tf+ykkyRWbb13AgNR/rKaXJ+SfE=", "serverKey" : "4GpFLR1A3Aaur81G448A+z2Z46w=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "Cppttvy8tNQzZHgYQwdWdt8B3IYu5YKdRITbgw==", "storedKey" : "gGviqQnZ+F8ucWYDGaw92BTdfK6HvsvHtNJ6eGImHvA=", "serverKey" : "lPRimybi/DCbtIqmuHqClFX80XHyH786Q3ipYaI0pGI=" } }, "roles" : [ { "role" : "root", "db" : "admin" } ] }
{ "_id" : "fadi.admin", "userId" : UUID("49ac1a12-fb8b-403f-baf6-aa140a7183e2"), "user" : "admin", "db" : "fadi", "credentials" : { "SCRAM-SHA-1" : { "iterationCount" : 10000, "salt" : "HrGcS5OyN2ocn6J6iewyKQ==", "storedKey" : "GGkWSvvpTBnS2noHUl1seUz+vfs=", "serverKey" : "GsoKPFugUXJPWRblneYn82FHx40=" }, "SCRAM-SHA-256" : { "iterationCount" : 15000, "salt" : "6NzJDdGUb6auq94OmXwjbYjgmaM2bCWsP4Qg5Q==", "storedKey" : "PEZQQ/bhvEV0jmegsItLmDLfEP53a8WcW06/NycgdW8=", "serverKey" : "6WPFNjw3vZe/o8PMekjBp7urJwbk4hZyfnC/Yg7nIJo=" } }, "roles" : [ { "role" : "readWrite", "db" : "fadi" } ] }
> exit
# Open a mongoshell session as user 'admin'
mongo -u admin -p password1 --authenticationDatabase fadi --host "<my_release>-mongodb"
# Create a new test collection
>use fadi
>db.myNewCollection1.insertOne( { x: 1 } ) 
```

- Check in Compass if DB 'fadi' appears. Maybe it wasn't showing previously because of this issue: https://stackoverflow.com/questions/33446340/mongo-shell-not-showing-all-dbs

- Try to log in again using `admin` user. But keep in mind user 'admin' only has readWrite permissions in db 'fadi', and maybe Adminer and Compass requires a user with elevated privileges (or at least access to the admin Database).

Try to follow these steps until you run into an error, as you can see, using the standalone chart without any existing PVC works fine.

Note: I used `<>` for strings that you'll need to replace with the values of your environment.

**Comment by SellamiRami** [comment]
Hello @migruiz4 ,
Thank you for your detailed reply. 
I get the error when I reach the step to connect in compass using the `admin` user. I agree with you about the error is raised because of the `readWrite` permission role.
Is it possible to give another role in Helm chart? If yes, could you please tell me how?
Thank you in advance for your response.

**Comment by migruiz4** [comment]
Thank you for following the troubleshooting instructions, in that case, I think it is almost certain that the issue is caused by the MongoDB custom user not having access to the admin database.

I'm afraid the username provided with `auth.username` can not be configured with a different role than ReadWrite access to the database specified with `auth.database`

https://github.com/bitnami/bitnami-docker-mongodb/blob/4c41649dd3bdb3b38474503cb33235214be05068/4.0/debian-9/rootfs/opt/bitnami/scripts/libmongodb.sh#L499-L529

But you could configure a custom initscript that modifies its permissions during the first execution, or creates a new user if it doesn't exist using the value `initdbScripts`:

https://github.com/bitnami/charts/blob/f9a663e472e5ac8f8ad3b8856d8543a25c271ffc/bitnami/mongodb/values.yaml#L199-L207

**Comment by SellamiRami** [comment]
Hello @migruiz4, I agree with your conclusion. 
Now I'm tryin to make the configuration of the new user via `initdbScripts `. However, it is not trivial. 
Indeed, I updated the values.yaml as follow:
```yaml
mongodb:
  enabled: true
  persistence:
    enabled: true
  auth:
    enabled: true
    rootPassword: "password1"
  initdbScripts: 
    my_init_script: |  
      use admin 
      db.createUser({ user: "admin" , pwd: "password1", roles: ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]})
      use mongodb
      db.user.insert({name: "Ada Lovelace", age: 205})

```
I want to highlight that the MongoDB commands works when I'm inside the MongoDB pod (see commands below). Added to that, I succeeded to connect with the new username below  in Adminer. 

```shell
$ kubectl run mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.4.5-debian-10-r0 --command -- bash

$ mongo --host "fadi-mongodb" --authenticationDatabase admin -u root -p "password1"

> use admin
switched to db admin
>       db.createUser({ user: "admin" , pwd: "password1", roles: ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]})
Successfully added user: {
	"user" : "admin",
	"roles" : [
		"userAdminAnyDatabase",
		"dbAdminAnyDatabase",
		"readWriteAnyDatabase"
	]
}
> use mongodb
switched to db mongodb
> db.user.insert({name: "Ada Lovelace", age: 205})
WriteResult({ "nInserted" : 1 })
```
I think that the problem is related to the values.yaml.

**Comment by migruiz4** [comment]
Sorry for the misunderstanding.

`initdbScripts` is used to load custom shell script in the entrypoint. 
To run MongoDB shell commands, you could use the following `values.yaml`:
```yaml
mongodb:
  persistence:
      enabled: true
  auth:
      enabled: true
      rootPassword: "password1"
  initdbScripts:
      create_admin_user.sh: |
          $MONGODB_BIN_DIR/mongo admin --host 127.0.0.1 --port $MONGODB_PORT_NUMBER -u root -p $MONGODB_ROOT_PASSWORD << EOF
          db.createUser({ user: "admin" , pwd: "password1", roles: ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]})
          EOF

**Comment by SellamiRami** [comment]
Hello @migruiz4, It works now. Thank you very much for your valuable help. 
I think it is important to add this information in the documentation of the Helm Chart. Indeed, it is not mentioned anywhere. 
Thanks again :) Have a nice week

**Comment by migruiz4** [comment]
I'm happy to help, have a nice week too!

I agree it would be a good idea to provide more details about the custom user permissions in the Readme. I will add it to prevent other users from running into this issue again.

**Comment by SellamiRami** [comment]
Great ! I thank you for your involvement :).
I will close the issue
