### ISSUE TITLE
Airflow does not start after K8S restart , clone-repositories init container failed

### ISSUE THREAD

**Issue by jagusztinl** [bitnami/charts#5995]
**Which chart**:

The name (and version) of the affected chart

- `bitnami/airflow`, latest

**Describe the bug**

**Apache Airflow version**:

- v2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

- 1.19

**What happened**:

Deployed Airflow to K8S:

```console
$ helm install -f bitnami_values.yaml airflow-k8s bitnami/airflow \
--set executor=KubernetesExecutor \
--set redis.enabled=false \
--set rbac.create=true \
--set serviceaccount.create=true \
--set auth.username=my-user \
--set auth.password=my-passsword \
--set git.dags.enabled=true \
--set git.dags.repositories[0].repository=https://github.com/apache/airflow \
--set git.dags.repositories[0].branch=master \
--set git.dags.repositories[0].path=airflow/example_dags \
--set git.dags.repositories[0].name=Examples \
```

Worked perfectly. Then stopped the K8S cluster, and started again.  Airflow containers did not start, the clone-repositories init container failed:

```
fatal: destination path '/dags-examples' already exists and is not an empty directory.
```

clone-repositories init container not handling well the restarts

**How to reproduce it**:

Install Airflow (described above) start some workflow then and restart K8S

**Anything else we need to know**:

Reproducible every time

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", 
GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f3012a10f16eb86fdce6330433adf6c9ee", GitTreeState:"clean", BuildDate:"2021-02-13T03:54:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-rc.2.1077+43983cda8af930-dirty", GitCommit:"43983cda8af9307abb027aeaf3f10b86ff1887c4", GitTreeState:"dirty", BuildDate:"2020-11-19T19:32:24Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @jagusztinl 

The custom DAGs are cloned via git in an "emptyDir" volume, see:

- https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/_git_helpers.tpl#L56
- https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/_git_helpers.tpl#L14

It looks like during the cluster restart these volumes' content wasn't removed and, therefore, when the init-container tried to clone again the repo found the error you shared.

We'll have to change the init-container logic to avoid tryin to clone the repos when it detects they're already there. Thanks for reporting it.

In the meantime, you can simply remove the worker pods. Once, they're recreated the volumes will be empty and the das cloning should work.
