### ISSUE TITLE
Invalid docker image version mentioned for accessing psql access

### ISSUE THREAD

**Issue by balaji-balu** [bitnami/charts#6001]
**Which chart**:
postgresql-10.3.14 

**Describe the bug**
invalid docker image version mentioned for accessing psql from ouside the cluster. 

**To Reproduce**

1. install the postgres helm chart 
2. once the installation is complete, set of instructions to access the database from outside the cluster (see the attachment)
3. tried to connect to the postgres using the commands mentioned in step 2. 
4. kubectl get pods shows status as ImagePullBackOff
5. I checked the tags for this image at https://hub.docker.com/r/bitnami/postgresql.
6. I could not find this version of image ( 11.11.0-debian-10-r50 ) at docker.io/bitnami/postgresql  

**Expected behavior**
After the installation, correct image version (11.11.0-debian-10-r54) 

need to be mentioned on the console 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
![bitnami postgres install using helm 3](https://user-images.githubusercontent.com/22535075/113480834-02fb9b80-94b4-11eb-8a2b-a9d16db5ef68.png)

```

**Additional context**

**Comment by balaji-balu** [comment]
![bitnami postgres install using helm 3](https://user-images.githubusercontent.com/22535075/113481243-0132d780-94b6-11eb-9826-75bb817ee2c5.jpg)

**Comment by Mauraza** [comment]
Hi @balaji-balu,

I wasn't able to reproduce your issue:
```bash
$ kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r50 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host my-release-postgresql -U postgres -d postgres -p 5432
If you don't see a command prompt, try pressing enter.

postgres=# 
```

Could you try to run this command `docker pull docker.io/bitnami/postgresql:11.11.0-debian-10-r50`?
