### ISSUE TITLE
psql: FATAL:  password authentication failed for user "postgresqlUsername"

### ISSUE THREAD

**Issue by patsevanton** [bitnami/charts#6002]
**kubectl version**
``
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
``
``
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
``

**helm version**
`version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`

**Add helm repo**
`helm repo add bitnami https://charts.bitnami.com/bitnami`

**Install**
`helm install my-release --set postgresqlUsername=testuser,postgresqlPassword=secretpassword,postgresqlDatabase=my-database bitnami/postgresql`

**export POSTGRES_PASSWORD**
`export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-release-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)`

**To connect to your database run the following command:**
``
kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r54 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host my-release-postgresql -U testuser -d my-database -p 5432
``
output
```
psql: FATAL:  password authentication failed for user "testuser"
pod "my-release-postgresql-client" deleted
pod default/my-release-postgresql-client terminated (Error)
```

**kubectl logs my-release-postgresql-0**
```
postgresql 04:34:40.61
postgresql 04:34:40.61 Welcome to the Bitnami postgresql container
postgresql 04:34:40.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 04:34:40.61 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 04:34:40.62
postgresql 04:34:40.63 INFO  ==> ** Starting PostgreSQL setup **
postgresql 04:34:40.65 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 04:34:40.66 INFO  ==> Loading custom pre-init scripts...
postgresql 04:34:40.66 INFO  ==> Initializing PostgreSQL database...
postgresql 04:34:40.68 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 04:34:40.68 INFO  ==> Generating local authentication configuration
postgresql 04:34:40.69 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 04:34:40.70 INFO  ==> Configuring replication parameters
postgresql 04:34:40.73 INFO  ==> Configuring fsync
postgresql 04:34:40.77 INFO  ==> Loading custom scripts...
postgresql 04:34:40.78 INFO  ==> Enabling remote connections
postgresql 04:34:40.79 INFO  ==> ** PostgreSQL setup finished! **

postgresql 04:34:40.81 INFO  ==> ** Starting PostgreSQL **
2021-04-04 04:34:40.846 GMT [1] LOG:  pgaudit extension initialized
2021-04-04 04:34:40.847 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-04-04 04:34:40.847 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-04-04 04:34:40.869 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-04-04 04:34:40.918 GMT [89] LOG:  database system was shut down at 2021-04-04 04:33:52 GMT
2021-04-04 04:34:40.940 GMT [1] LOG:  database system is ready to accept connections
2021-04-04 04:34:52.937 GMT [101] FATAL:  password authentication failed for user "testuser"
2021-04-04 04:34:52.937 GMT [101] DETAIL:  Role "testuser" does not exist.
        Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

**kubectl get pvc -l "app=postgresql" --all-namespaces**
`No resources found`

**Comment by migruiz4** [comment]
Hi @patsevanton ,

I haven't been able to reproduce your issue in a fresh install.

I think you have an existing PVC that is causing this issue because of this log:
> 2021-04-04 04:34:40.918 GMT [89] LOG:  database system was shut down at 2021-04-04 04:33:52 GMT

Could you use this command to search for an existing PVC?
```
kubectl get pvc -l "app.kubernetes.io/name=postgresql" --all-namespaces
```

Default labels used by the PVC should be `app.kubernetes.io/instance=my-release,app.kubernetes.io/name=postgresql,role=primary`

**Comment by patsevanton** [comment]
Hi! @migruiz4 
I can not reproduce issue now. i am sicking.
Please write to me on next week

**Comment by patsevanton** [comment]
@migruiz4 
I try on clean k8s

**Add repo**
`helm repo add bitnami https://charts.bitnami.com/bitnami`

**Install**
```
helm install my-release --set postgresqlUsername=testuser,postgresqlPassword=secretpassword,postgresqlDatabase=my-database bitnami/postgresql
export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-release-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r62 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host my-release-postgresql -U testuser -d my-database -p 5432
```

------ WORK postgresqlUsername=testuser,postgresqlPassword=secretpassword -------
**test**
```
kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r62 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host my-release-postgresql -U testuser -d my-database -p 5432
kubectl get pvc -l "app.kubernetes.io/name=postgresql" --all-namespaces
helm uninstall my-release
```

------ WORK postgresqlUsername=testuser,postgresqlPassword=secretpassword -------
**Install**
`helm install my-release --set postgresqlUsername=testuser,postgresqlPassword=secretpassword,postgresqlDatabase=my-database bitnami/postgresql`
**test**
```
export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-release-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r62 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host my-release-postgresql -U testuser -d my-database -p 5432
helm uninstall my-release
```


------ DON`T WORK postgresqlUsername=xxx,postgresqlPassword=zzzzzz -------
**Install**
helm install my-release --set postgresqlUsername=xxx,postgresqlPassword=zzzzzz,postgresqlDatabase=my-database bitnami/postgresql
**test**
```
export POSTGRES_PASSWORD=$(kubectl get secret --namespace default my-release-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r62 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host my-release-postgresql -U xxx -d my-database -p 5432
psql: FATAL:  password authentication failed for user "xxx"
pod "my-release-postgresql-client" deleted
pod default/my-release-postgresql-client terminated (Error)
```


**pvc**
```
kubectl get pvc -l "app.kubernetes.io/name=postgresql" --all-namespaces
NAMESPACE   NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
default     data-my-release-postgresql-0   Bound    pvc-71f88718-ffa4-4e58-82a1-880b2faecb51   8Gi        RWO            microk8s-hostpath   10m
```

**Comment by migruiz4** [comment]
Hi @patsevanton 

Let me shed some light on what is happening here:

On the first install, there is no existing PV, so Postgresql is installed with credentials `testUser:secretPassword`and stores his data in a new PV.

Then, when reinstalling for the second time, Postgresql will reuse the previous PV. But, as you provided the same credentials, Postgresql will be able to use it as if the application were upgraded.

Although, the third time you reinstalled, it also used the previous PV but because you provided different credentials, Postgresql fails because username and password can only be configured the first time the application runs.

To prevent this issue, you need to do the following:
```
#Uninstall the previous release
helm uninstall my-release
#Delete the existing PVC
kubectl -n default delete data-my-release-postgresql-0
#Reinstall Postgresql with the new settings
helm install my-release --set postgresqlUsername=xxx,postgresqlPassword=zzzzzz,postgresqlDatabase=my-database bitnami/postgresql
```

Note: I'm assuming this is a test environment, in production environments make sure you have a backup of your application data before deleting the PV as this step is irreversible.

For more information, I'd recommend checking the section 'Persistence Volumes (PVs) retained from previous releases' of the Helm Chart troubleshooting guide:https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/

**Comment by patsevanton** [comment]
OK. Thanks! I will try

**Comment by Zhang21** [comment]
> Hi @patsevanton
> 
> Let me shed some light on what is happening here:
> 
> On the first install, there is no existing PV, so Postgresql is installed with credentials `testUser:secretPassword`and stores his data in a new PV.
> 
> Then, when reinstalling for the second time, Postgresql will reuse the previous PV. But, as you provided the same credentials, Postgresql will be able to use it as if the application were upgraded.
> 
> Although, the third time you reinstalled, it also used the previous PV but because you provided different credentials, Postgresql fails because username and password can only be configured the first time the application runs.
> 
> To prevent this issue, you need to do the following:
> 
> ```shell
> #Uninstall the previous release
> helm uninstall my-release
> #Delete the existing PVC
> kubectl -n default delete data-my-release-postgresql-0
> #Reinstall Postgresql with the new settings
> helm install my-release --set postgresqlUsername=xxx,postgresqlPassword=zzzzzz,postgresqlDatabase=my-database bitnami/postgresql
> ```
> 
> Note: I'm assuming this is a test environment, in production environments make sure you have a backup of your application data before deleting the PV as this step is irreversible.
> 
> For more information, I'd recommend checking the section 'Persistence Volumes (PVs) retained from previous releases' of the Helm Chart troubleshooting guide:https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/

<br/>

Yes! Because of the time of liveness and readness is too small, which less than the time of pgsql init, the k8s health check is failed, so the container is restart.

We should change the `initialDelaySeconds` larger, it should greater than 60, such 100s, 120s, to wait pgsql init successfully.

```yaml
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
```

**Comment by Zhang21** [comment]
Same issue to me. We should change the `initialDelaySeconds` larger.

**Comment by patsevanton** [comment]
May be add this info to Readme https://github.com/bitnami/charts/tree/master/bitnami/postgresql ?

**Comment by migruiz4** [comment]
Hi @patsevanton and @Zhang21,

If I understand correctly, this issue only happens during the Postgresql initialization, right?

For that case, I think enabling the startupProbe would suit better, so it is not necessary to increase the default values for the liveness or readiness Probes.

```
startupProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
```

P.S.: Support for startupProbe was added in version 10.3.0 of the postgresql chart.

**Comment by Zhang21** [comment]
> Hi @patsevanton and @Zhang21,
> 
> If I understand correctly, this issue only happens during the Postgresql initialization, right?
> 
> For that case, I think enabling the startupProbe would suit better, so it is not necessary to increase the default values for the liveness or readiness Probes.
> 
> ```
> startupProbe:
>   enabled: true
>   initialDelaySeconds: 120
>   periodSeconds: 10
>   timeoutSeconds: 5
>   failureThreshold: 6
>   successThreshold: 1
> ```
> 
> P.S.: Support for startupProbe was added in version 10.3.0 of the postgresql chart.

<br>

Yes. Two answers:

1. Enable startupProbe.
2.  Disabled startupProbe, change the initialDelaySeconds larger.

**Comment by patsevanton** [comment]
I think need Enable startupProbe by default

**Comment by Zhang21** [comment]
The default startupProbe of pgsql is disabled, so cause this issue.

The docs should mention this.

**Comment by migruiz4** [comment]
Hi,

I consider enabling startupProbe and tuning initialDelaySeconds to be a user decision to adapt their deployment to their needs and not necessarily should require changing the defaults.

In addition, the issue initially described by @patsevanton is unrelated to the liveness or startup probes, as the error `psql: FATAL: password authentication failed for user "postgresqlUsername"` was caused by trying to re-install the chart without providing the pvc (or previously deleting them for a clean install)

**Comment by patsevanton** [comment]
Ok
