### ISSUE TITLE
couple errors in values.yaml file for kafka

### ISSUE THREAD

**Issue by nervouscat** [bitnami/charts#6005]
Hello there,
I noticed an error in the values.yaml file when i first run it:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.securityContext): unknown field "enabled" in io.k8s.api.core.v1.PodSecurityContext`

it seems to be related to this section:

`
....
podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
....
`
removing enabled: true resolved the error.

A second error i found (which was during runtime) while running the chart was:

`org.apache.kafka.common.config.ConfigException: Invalid value _10000 for configuration log.flush.interval.messages: Not a number of type LONG`

In order to fix it I simply changed:
logFlushIntervalMessages: _10000
to
logFlushIntervalMessages: 10000

Please let me know if i took the right steps to resolving the above issues

Best regards,
Tarek M

**Comment by juan131** [comment]
Hi @nervouscat 

What version of the chart are you using? It looks to me like you're using the latest **values.yaml** but using an old version of the chart.

Could you please double-check it?

**Comment by nervouscat** [comment]
Hi Juan, 
Thank you for the quick response!

I'm currently using the values.yaml from the master repo: https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml

it seems I'm also having multiple other issues with regards to external access with the LoadBalancer with 3 replicas. hopefully This issue is also related to me using an older file, else will open a new issue for it. 

Thank you in advance!

**Comment by nervouscat** [comment]
solved by doing 'helm repo update'

Thank you!

**Comment by juan131** [comment]
Great! Glad to hear that @nervouscat
