### ISSUE TITLE
additionalLabels for nginx serviceMonitor

### ISSUE THREAD

**Issue by CarTerr** [bitnami/charts#6006]
**Which chart**:
nginx

**Is your feature request related to a problem? Please describe.**
need to add an additional label (release: monitoring) to the monitor service for Prometheus work

**Additional context**
works like postgresql chart
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring

**Comment by marcosbc** [comment]
Hi @CarTerr, aren't you looking for something like [`commonLabels`](https://github.com/bitnami/charts/blob/master/bitnami/nginx/values.yaml#L61)?

**Comment by CarTerr** [comment]
problem solved by using
      selector:
        release: monitoring
