### ISSUE TITLE
[bitnami/redis] Incorrect description about Sentinel mode in README.md

### ISSUE THREAD

**Issue by zhiweiv** [bitnami/charts#6007]
In https://github.com/bitnami/charts/blob/master/bitnami/redis/README.md
> Master-Slave with Sentinel
> When installing the chart with cluster.enabled=true and sentinel.enabled=true, it will deploy a RedisTM master StatefulSet (only one master allowed) and a RedisTM slave StatefulSet.

Actually, it will only create a StatefulSet with name xxx-node from template [redis-node-statefulset.yaml](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-node-statefulset.yaml).

It uses slaveCount as the StatefulSet replicas value, there is no description about this also.  

For best practice, the instance of sentinel is at least 3, but the default value of slaveCount is 2, I think it is also not good enough.

**Comment by carrodher** [comment]
Thanks for letting us know, would you like to contribute by sending a PR addressing the topics you mention? We will be happy to review it!

**Comment by zhiweiv** [comment]
@carrodher
It is better for someone else to update the document, I found one more error in latest content.
`When installing the chart with architecture=architecture and sentinel.enabled=true`
I guess it should be architecture=replication

**Comment by carrodher** [comment]
Some days ago we released a new major version of the Bitnami Redis Helm Chart (`14.0.0`, see https://github.com/bitnami/charts/pull/6102) addressing different issues and suggestions, as well as standardizing the chart applying some best practices.

Apart from that, I just fixed the typo in the README in this commit https://github.com/bitnami/charts/commit/6a787e2edec4a2760a3579369307cb7a7e1d94a7
