### ISSUE TITLE
additionalLabels for redis serviceMonitor

### ISSUE THREAD

**Issue by CarTerr** [bitnami/charts#6008]
Which chart:
redis

Is your feature request related to a problem? Please describe.
need to add an additional label (release: monitoring) to the servicemonitor for Prometheus work

Additional context
works like postgresql chart
metrics:
enabled: true
serviceMonitor:
enabled: true
additionalLabels:
release: monitoring

**Comment by rafariossaa** [comment]
Hi,
  Could you try by using `Values.metrics.serviceMonitor.selector` ? You should be able to generate the labels you need. 
Ref: https://github.com/bitnami/charts/blob/a20680fb97656eebc6443c7e7a288b36a29d41d0/bitnami/redis/templates/metrics-prometheus.yaml#L16
It is similar to what is done in postgresql https://github.com/bitnami/charts/blob/a20680fb97656eebc6443c7e7a288b36a29d41d0/bitnami/postgresql/templates/servicemonitor.yaml#L11

**Comment by CarTerr** [comment]
problem solved by using
      selector:
        release: monitoring

**Comment by rafariossaa** [comment]
Hi,
  I am happy you where able to solve the issue.
  Thanks for providing feedback with your solution.
