### ISSUE TITLE
[bitnami/nginx] how to configure worker_connections?

### ISSUE THREAD

**Issue by gajus** [bitnami/charts#6016]
It is not clear having read the entire documentation how does one configure [`worker_connections`](http://nginx.org/en/docs/ngx_core_module.html#worker_connections).

It is supposed to go to the `events` block, but there appears to be no way to configure the events block. 🧐

**Comment by marcosbc** [comment]
Hi @gajus, you seem to be right. At this moment, the only thing to do is either replace it manually when initializing the NGINX container, or override the entire `nginx.conf` via `extraVolumes`/`extraVolumeMounts`, both approaches are described [here](https://github.com/bitnami/charts/issues/4121#issuecomment-721040121).

Note that contributions are welcome, if you have a suggestion for any improved way (such as specifying the file in values.yaml or via `--set`), I'm sure it will be useful for many.

**Comment by marcosbc** [comment]
Related issue: #4121
