### ISSUE TITLE
[bitnami/airflow] How to avoid  pod restart cause by sync-repositories container sporadic network error

### ISSUE THREAD

**Issue by nonpool** [bitnami/charts#6018]
**Which chart**:
bitnami/airflow 2.0.1 (all version should exists this issue)

**Describe the bug**
Sync-repositories container sometimes will encounter network cause synchronize code failed, so that the related pod(airflow-worker/airflow-web/airflow-scheduler) will restart. 
This will greatly affect my work. the airflow web page cannot be opened during restart, and the logs stored on the work will disappear.

**To Reproduce**

**Expected behavior**
Given a parameter to configuration git sync max sync failures just like `kubernetes/git-sync` image `--max-sync-failures` parameter, and support retry forever after the initial sync.  
This will be very useful for users with bad internet

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"2cbb16c", GitTreeState:"", BuildDate:"2021-01-27T02:20:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I don’t know if it will be work to directly use `kubernetes/git-sync` instead of `bitnami/git`

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this enhancement. 
  I am  opening a internal task to check `kubernetes/git-sync` behavior and see how we can improve this.
  We are a small team and I can not provide an ETA for this.
  Meanwhile, don't hesitate to send a PR, we will be glad to review and merge it.
