### ISSUE TITLE
[bitnami/etcd] Set `configuration` in `values.yaml` leads to Helm parse error

### ISSUE THREAD

**Issue by rgroemmer** [bitnami/charts#6023]
**Which chart**:
bitnami/etcd 6.1.4

**Describe the bug**
If `configuration` attribute in `values.yaml` is set *(line 171)*, helm crashes with following error:

```txt
Error: YAML parse error on etcd/templates/configmap.yaml: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
helm.go:81: [debug] error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
YAML parse error on etcd/templates/configmap.yaml
```

**Solution**
Problem is a small typo in the `templates/configmap.yaml` in `name` field *(line 5)*.
The dash at the end of the line results in a missing newline.

```txt
# actual
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) -}}
                                                                                                                    ^
# should be
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) }}
```

**To Reproduce**

1. Go to 'values.yaml' of bitnami/etcd
2. set etcd configuration *(line 171)*
3. add config or use example *(line 167 - 170)*
4. helm install / upgrade / template

**Expected behavior**
Helm should create a valid `configmap.yaml` with the specified configuration for the `etcd.conf.yml`. 

**Additional context**
Will create a PR for this bug.

**Comment by migruiz4** [comment]
Hi @rgroemmer ,

Thank you for reporting this issue and submitting a PR fixing it.

I tested it and works like a charm:
```
> helm template bitnami/etcd
...
---
# Source: etcd/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-etcd-configuration
  namespace: default
  labels:
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-6.1.4
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
data:
  etcd.conf.yml: |-
    foo: bar
    baz:
---
...
```
