### ISSUE TITLE
[bitnami/redmine] Wrong indent in cronjob.yml

### ISSUE THREAD

**Issue by puhbooh** [bitnami/charts#6028]
**Which chart**:
bitnami/redmine 15.2.8

**Describe the bug**
https://github.com/bitnami/charts/blob/a20680fb97656eebc6443c7e7a288b36a29d41d0/bitnami/redmine/templates/cronjob.yaml#L91

value for "redmine.database.host" has wrong indent. so if enable mailReceiver i got this error: 
Error: YAML parse error on redmine/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 68: did not find expected '-' indicator

**To Reproduce**
1. enable mailReceiver

```
mailReceiver:
  enable: true
```

2. deploy chart ->  see error

**Comment by juan131** [comment]
Thanks for reporting this bug @puhbooh !! Would you contribute a PR fixing this typo?

**Comment by puhbooh** [comment]
yes i can do it

**Comment by juan131** [comment]
Thanks! I'll be glad to review it
