### ISSUE TITLE
[bitnami/cassandra] How to NetworkTopologyStrategy?

### ISSUE THREAD

**Issue by turowicz** [bitnami/charts#6044]
Cassandra documentation mentions that production clusters should be using the NetworkTopologyStrategy for keyspaces. After deploying a cassandra cluster using the helm chart with replicas=2 I am unable to use the NetworkTopologyStrategy. When I try to select data from a newly created table in the desired keyspace I get the error saying that 0 out of 1 necessary replicas are available.

**Comment by migruiz4** [comment]
Hi @turowicz,

Could you please share more details about your issue? Steps to reproduce, version of the chart,  and content of your values.yaml would be helpful.

I tried to reproduce your issue using:
```
helm install my_release bitnami/cassandra --set replicaCount=2,cluster.endpointSnitch=GossipingPropertyFileSnitch
```
> Note: cluster.endpointSnitch=GossipingPropertyFileSnitch is required when using NetworkTopologyStrategy, otherwise nodes won't share their `cassandra-rackdc.properties` 
> Ref: https://cassandra.apache.org/doc/latest/operating/snitch.html

With the above configuration, I was able to create a keyspace with NetworkTopologyStrategy and use it:
```bash
I have no name!@cass-2-cassandra-client:/$ cqlsh -u cassandra -p $CASSANDRA_PASSWORD cass-2-cassandra
Connected to cassandra at cass-2-cassandra:9042.
[cqlsh 5.0.1 | Cassandra 3.11.10 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> CREATE KEYSPACE "my_ks" WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': 1};
cassandra@cqlsh> USE my_ks;
cassandra@cqlsh:my_ks> CREATE TABLE test(
         ...    ent_id int PRIMARY KEY,
         ...    ent_name text,
         ...    ent_phone varint
         ...    );
cassandra@cqlsh:my_ks> SELECT * FROM test;

 ent_id | ent_name | ent_phone
--------+----------+-----------

(0 rows)
cassandra@cqlsh:my_ks> INSERT INTO test (ent_id, ent_name, ent_phone) VALUES (1, 'John',123456789);
cassandra@cqlsh:my_ks> SELECT * FROM test;

 ent_id | ent_name | ent_phone
--------+----------+-----------
      1 |     John | 123456789

(1 rows)
cassandra@cqlsh:my_ks> 
```

**Comment by turowicz** [comment]
Hey @migruiz4 thank you so much this worked!
