### ISSUE TITLE
Unable To Connect External Database

### ISSUE THREAD

**Issue by SrikanthSrinivasamurthy** [bitnami/charts#6061]
**Which chart**:
magento-17.2.5.tgz

**Environemtn**:
Windows 10
Docker-Desktop 3.2.2
Mariadb Version  10.4.18-MariaDB (Remote login is enabled )
 
**Describe the bug**
Unable to connect to external database by providing externalDatabase properties in override file

**To Reproduce**

1. Create override file 
2. Edit override-file  and provide externalDatabase properties to point external database. see below properties
```
externalDatabase:
  host: 10.XXX.XXX.XXX
  port: 3306
  user: bn_magento
  password: motive
  database: bitnami_magento
mariadb:
  enabled: false
```
3. set mariadb.enabled to false and leave other mariadb properties as it is
4. Now deploy application , pod unable to connect external database which leads it to CrashLoopBackOff status.
5.  Below is the logs of pod which ran in debug mode
```
PS > kubectl get po
NAME                                        READY   STATUS             RESTARTS   AGE
ingress-nginx-controller-7fc74cf778-8b7tx   1/1     Running            21         7d3h
magento-79765fb4df-8s7th                    0/1     CrashLoopBackOff   3          11m

PS > kubectl.exe logs -f magento-79765fb4df-8s7th
magento 11:07:12.75
magento 11:07:12.76 Welcome to the Bitnami magento container
magento 11:07:12.76 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento 11:07:12.76 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento 11:07:12.77
magento 11:07:12.77 INFO  ==> ** Starting Magento setup **
magento 11:07:12.84 DEBUG ==> Validating settings in APACHE_* environment variables
magento 11:07:12.87 INFO  ==> Configuring the HTTP port
magento 11:07:12.87 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/httpd.conf
magento 11:07:12.89 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/bitnami/bitnami.conf
magento 11:07:12.90 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/vhosts/00_status-vhost.conf
magento 11:07:12.91 INFO  ==> Configuring the HTTPS port
magento 11:07:12.92 DEBUG ==> Configuring port 8443 on file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
magento 11:07:13.01 INFO  ==> Configuring PHP options
magento 11:07:13.01 INFO  ==> Setting PHP memory_limit option
magento 11:07:13.11 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento 11:07:13.30 DEBUG ==> Validating settings in MAGENTO_* environment variables...
magento 11:07:13.61 INFO  ==> Restoring persisted Magento installation
magento 11:07:38.07 INFO  ==> Trying to connect to the database server
magento 11:07:38.09 DEBUG ==> Getting configuration path '/db/connection/default/dbname' from Magento configuration
magento 11:07:38.23 DEBUG ==> Getting configuration path '/db/connection/default/username' from Magento configuration
magento 11:07:38.35 DEBUG ==> Getting configuration path '/db/connection/default/password' from Magento configuration
magento 11:07:38.48 DEBUG ==> Getting configuration path '/db/connection/default/host' from Magento configuration
magento 11:07:38.63 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'magento-mariadb' (-3)
magento 11:07:49.67 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'magento-mariadb' (-3)
magento 11:08:00.71 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'magento-mariadb' (-3)
magento 11:08:11.76 DEBUG ==> Executing SQL command:
SELECT 1
ERROR 2005 (HY000): Unknown MySQL server host 'magento-mariadb' (-3)
magento 11:08:22.83 DEBUG ==> Executing SQL command:
```

**Expected behavior**
Magento pod should be up and running

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Global privilege is  provided with any remote connection. i can able to connect through client with ip
![image](https://user-images.githubusercontent.com/19665217/114174702-9a4e6c00-9956-11eb-8ba4-c7e1fc3379cc.png)

**Comment by rafariossaa** [comment]
Hi,
  I think it is not picking the right database hostname, and this can be due to persisted data.
  In the log you can see:
```
 Unknown MySQL server host 'magento-mariadb' (-3)
```
 but you are using an IP as hostname:
```
externalDatabase:
  host: 10.XXX.XXX.XXX
```

Could you try to delete the PVCs and try to deploy it again ?. Have into account that this will remove any data.

**Comment by SrikanthSrinivasamurthy** [comment]
Hi @rafariossaa 
yeah magento data persistence was enabled persistence.enabled=true.  if disabled and ran  with IP its connecting , Up & Running.
```
PS > kubectl.exe get po                                                                                                                                                                                               NAME                                        READY   STATUS    RESTARTS   AGE
ingress-nginx-controller-7fc74cf778-8b7tx   1/1     Running   22         8d
magento-58974d788c-pbqfq                    1/1     Running   0          5m46s
```
Isn't that bug since I have connected to VPN each time when connect it changes it IP.
so my persisted data we cant use,  like if payment gateway is integrated than after re-deploy again it needs to be reinstalled.

**Comment by rafariossaa** [comment]
Hi,
  As it is persisted, to change the configuration, I would suggest to set the `initialDelaySeconds` of the probes to a very high value, this way you will be able to get into the pods and change the configuration manually.

**Comment by SrikanthSrinivasamurthy** [comment]
How to change configuration manually means what the environment variables or files we need to change ?

**Comment by rafariossaa** [comment]
The  persisted configuration file is `/opt/bitnami/magento/app/etc/env.php`

**Comment by SrikanthSrinivasamurthy** [comment]
Yeah go that file so basically if we change value in that and volume mount also that will work.

**will this issue be addressed so that we need not to do all this manual work.**

**Comment by rafariossaa** [comment]
If you install using external database from the first time the file should be configured accordingly, but if you are using a previous PVC, the installation logic will no change the existing settings.
