### ISSUE TITLE
[Redis-Cluster] Disabled snapshots

### ISSUE THREAD

**Issue by remenaker** [bitnami/charts#6065]
**Which chart**:
Redis-Cluster 5.0.0

**Describe the bug**
I would like to disable the snapshot feature of Redis as my use case does not need it. I was thinking that turning persistence to false would do the trick but it is still enabled when I run the command of `redis-cli config get save`. Do the charts have a way to turn off this feature so that the Redis Cluster does not snapshot the database?

**To Reproduce**
Update values.yaml to have persistence: false
Deploy cluster
Run command `redis-cli config get save` and see that it is enabled

**Expected behavior**
Snapshot feature is disabled and shows disabled from the redis-cli tool and commented out in the redis.conf

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"41d24ec9c736cf0bdb0de3549d30c676e98eebaf", GitTreeState:"clean", BuildDate:"2021-01-18T09:12:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @remenaker,

Persistence is the data of Redis https://github.com/bitnami/charts/tree/master/bitnami/redis#persistence
If you want to disable the snapshot in the configuration file appears:
> Note: you can disable saving completely by commenting out all "save" lines.

Could you try this?

**Comment by remenaker** [comment]
Yes that is what needs to happen, just did not know if there was a way using the chart to get this disabled during deployment. I see that the config file is stored as a config map and by default those lines our not commented out.

**Comment by Mauraza** [comment]
Hi @remenaker

the `configmap` adds lines to `redis.conf`. You use this command `sed -e '/save/,+4 s/^/#/' -i /opt/bitnami/redis/etc/redis.conf`
