### ISSUE TITLE
[bitnami/airflow] Initialization error when git sync is enabled

### ISSUE THREAD

**Issue by echang0929** [bitnami/charts#6068]
**Which chart**:
airflow

**Describe the bug**
When I enabled "git.dags.enabled" and "git.plugins.enabled" I got error:

```
/bin/bash: -c: line 2: conditional binary operator expected
```

**To Reproduce**
When I install this helm chart with: 

```
helm install app-aflow ./bitnami/airflow \
  --set global.storageClass=ibmc-file-gold \
  --set postgresql.livenessProbe.initialDelaySeconds=200 \
  --set postgresql.readinessProbe.initialDelaySeconds=200 \
  --set postgresql.volumePermissions.enabled=true \
  --set redis.volumePermissions.enabled=true \
  --set git.dags.enabled=true \
  --set "git.dags.repositories[0].branch=master" \
  --set "git.dags.repositories[0].repository=https://\$(git-user):\$(git-token)@github.ibm.com/zyibj/aflowstuff.git" \
  --set "git.dags.repositories[0].path=dags" \
  --set "git.dags.repositories[0].name=aflowdags" \
  --set git.plugins.enabled=true \
  --set "git.plugins.repositories[0].branch=master" \
  --set "git.plugins.repositories[0].repository=https://\$(git-user):\$(git-token)@github.ibm.com/zyibj/aflowstuff.git" \
  --set "git.plugins.repositories[0].path=plugins" \
  --set "git.plugins.repositories[0].name=aflowplugins" \
  --set git.clone.extraEnvVarsSecret=github-secrets 
```

I got this error. However, I think this error was led by new changes on _git_helpers.tpl file:

https://github.com/bitnami/charts/commit/0f533353344384d8729b71001fc230cf8c7865a7#

since I could install it successfully with the previous version.

**Expected behavior**

**Additional context**

**Comment by javsalgar** [comment]
Hi, 

Just a note to let you know that I was able to reproduce the issue. We will work on fixing it.

**Comment by javsalgar** [comment]
Fix created, please check if the latest version works https://github.com/bitnami/charts/pull/6070

**Comment by echang0929** [comment]
Thank you for the quick fix. I've verified it is good now.

**Comment by javsalgar** [comment]
Thanks for confirming!
