### ISSUE TITLE
Password not set even though it is provided

### ISSUE THREAD

**Issue by moby04** [bitnami/charts#6075]
**Which chart**:
Chart bitnami/rabbitmq
Version: 8.11.3

**Describe the bug**
RabbitMQ deployed with chart does not change the password and stays with default value. 

I used `rabbitmq.auth.existingPasswordSecret` value but it seems that the problem would exist also with plain text password. See description below.

**To Reproduce**

1. Prepare values file containing following fields:
```yaml
rabbitmq:
  auth:
    username: user
    existingPasswordSecret: mailer-rabbit-passwd
    erlangCookie: 
```
2. Create secret `mailer-rabbit-passwd` containing key `rabbitmq-password` and some random password
3. Deploy chart 

RabbitMQ will not accept the password provided via secret

**Expected behavior**
RabbitMQ should respect user and password provided in the configuration.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

Initially I tried connecting to RabbitMQ pod from Symfony application running on a Pod within the same namespace. Once I encountered problems I tried running separate pod with Ubuntu:

```
$ kubectl run test -n staging-mailer --image=ubuntu sleep infinity
(...)
$ kubectl -n staging-mailer exec -it test bash
(...)
root@test:/# apt update && python3-pip
(...)
root@test:/# pip3 install amqp_client_cli
(...)
root@test:/# amqpcli config add_user  
User: jmt-rabbit-user
Password: 
vhost? [/]: 
root@test:/# amqpcli send -u jmt-rabbit-user -m test mailer-rabbitmq 5672 foo 12
Connecting to queue @ jobleads-mailer-rabbitmq:5672... FAILED!
Failure reason: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
```

After that I decided to go directly to RabbitMQ container and look for issue there:
```
$ kubectl -n staging-jobleads-mailer exec -it jobleads-mailer-rabbitmq-0 bash
(...)
I have no name!@mailer-rabbitmq-0:/$ printenv | grep -i pass
RABBITMQ_PASSWORD=0hoVtMj0A1
I have no name!@mailer-rabbitmq-0:/$ rabbitmqctl authenticate_user jmt-rabbit-user 0hoVtMj0A1
Authenticating user "jmt-rabbit-user" ...
Error:
Error: failed to authenticate user "jmt-rabbit-user"
```

As you can see in output above the password in environmental variable was passed correctly (the same value as in my secret) but it was not accepted even locally via rabbitmqctl. 

I changed the password using `rabbitmqctl`:

```
I have no name!@mailer-rabbitmq-0:/$ rabbitmqctl change_password jmt-rabbit-user 0hoVtMj0A1
Changing password for user "jmt-rabbit-user" ...
I have no name!@mailer-rabbitmq-0:/$ rabbitmqctl authenticate_user jmt-rabbit-user 0hoVtMj0A1
Authenticating user "jmt-rabbit-user" ...
Success
```

From now on also Ubuntu container and Symfony app succeeded with connection.

The last thing I checked was contents of `rabbitmq.conf`:

```
I have no name!@mailer-rabbitmq-0:/bitnami/rabbitmq/conf$ cat rabbitmq.conf 
## Username and password
##
default_user = jmt-rabbit-user
default_pass = CHANGEME
## Clustering
##
(...)
```

As you can see above this configuration contained properly set `defaut_user` but wrong value of `default_pass` - despite the fact that environmental variable with `RABBITMQ_PASSWORD` exists in container's context.

**Comment by carrodher** [comment]
Thanks for the detailed explanation. Are you facing this issue in the first installation or did you deployed the chart previously?

If it is an installation from scratch it is something I will try to reproduce on my side, but usually, this kind of issue is produced because it a second installation with the same name/namespace (or an upgrade). When deleting a deployment with `helm delete`, the PVCs are not removed (it is how helm works), so the second installation is going to use the existing PVC. If the second installation contains a different password, there is going to be a mismatch between the first password stored in the PVC and the new one (passed as a parameter, secret, etc). If this is the issue, can you take a look at this [troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases)?

**Comment by moby04** [comment]
I was just going to add information that I have found the issue: there was leftover PVC from failed Helm deployment (it timed out because Rabbit starts quite long with EFS as storage class). When I manually deleted it the password was set properly so the issue can be closed. :)

**Comment by arcanis** [comment]
I've been trying to get past this to no avail - when I tried to follow the procedure `kubectl delete pv --all` hanged without doing anything (even though I tried to shutdown everything I could), so I then completely erased the cluster (`kubectl config delete-cluster my-cluster`), its image, and recreated it (`kind create cluster --name my-cluster`). Nothing appeared with `kubectl get pv`, but once Rabbit finished booting I had the same issue, no passing auth 😥

**Comment by carrodher** [comment]
Can you share what command are you using to deploy it? Are you using a hardcoded password or relying on the randomly generated ones? Did you customize the values.yaml or provide any extra parameters with `--set`?

**Comment by arcanis** [comment]
I finally found the issue (https://github.com/loft-sh/devspace/issues/1476) - in essence, my `values.yml` was:

```yaml
auth.username: foo
```

Instead of being:

```yaml
auth:
  username: foo
```

Since the dot-values are documented, as an helm newbie I had no idea the values weren't meant to be literal when using the `-f` flag. I only understood it after looking at your default one (but I think the tools, either DevSpace or Helm, should make it an error; it's far too easy to get wrong imo).
