### ISSUE TITLE
[bitnami/redis] Fresh install of version redis 13.0.1 chart causes standard_init_linux.go:219: exec user process caused: exec format error on both pods

### ISSUE THREAD

**Issue by shaharl-sternum** [bitnami/charts#6076]

**Comment by shaharl-sternum** [comment]
Update: The containers doesn't work with the a1 machine types but works with the t3.

**Comment by rafariossaa** [comment]
Hi @shaharl-sternum ,
  A1 machines uses ARM processors and our images are for amd64 architecture, on the other hand T3 machines are amd64 based.

**Comment by rafariossaa** [comment]
Hi @shaharl-sternum 
  Did you have the chance to check the architectures ?

**Comment by rafariossaa** [comment]
Hi,
  I am closing this issue. 
  In any case, you can reopen or open a new one if needed.
