### ISSUE TITLE
[worpress] deployment strategy recreate 

### ISSUE THREAD

**Issue by djgrubson** [bitnami/charts#6078]
worpress halm chart unable to use

`updateStrategy:
  type: Recreate
  `
as default chart value has following values:
`updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}`

actual error
Error: UPGRADE FAILED: cannot patch "wordpress" with kind Deployment: Deployment.apps "wordpress" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'

**Comment by alemorcuq** [comment]
Hi, @djgrubson.

What is the upgrade command you are trying to run and what are the values you are changing?

**Comment by djgrubson** [comment]
actual command was 
helm upgrade akupunktura-wp -n prod -f wordpress-values.yaml bitnami/wordpress
and my wordpress-values.yaml had
`updateStrategy: 
    type: Recreate`

**Comment by alemorcuq** [comment]
Ok. I think I understand it now. Can you try to upgrade using this values for the `updateStrategy` parameter?

```
updateStrategy:
  type: Recreate
  rollingUpdate: nil
```

**Comment by dmitry-mightydevops** [comment]
So I tried this and got this

```
updateStrategy:
  type: Recreate
  rollingUpdate: nil

error validating data: ValidationError(Deployment.spec.strategy.rollingUpdate): invalid type for io.k8s.api.apps.v1.RollingUpdateDeployment: got "string", expected "map"
```

**Comment by alemorcuq** [comment]
Hi, @dmitry-mightydevops.

My mistake, it should be `rollingUpdate: null` instead of `rollingUpdate: nil`.
