### ISSUE TITLE
Hi! Where can I get the /opt/bitnami/airflow/airflow.cfg?

### ISSUE THREAD

**Issue by bugzyz** [bitnami/charts#6083]
Hi, I want to take a look at the cfg to confirm the authentication setting. But I got this message from the airflow web. 

Should I login to the pod and which pod and where can I get this .cfg file? 

![image](https://user-images.githubusercontent.com/31982774/114520476-0d682300-9c74-11eb-818b-d2a3d83da215.png)

**Comment by javsalgar** [comment]
Hi,

You would need to enter the airflow-web pod using `kubectl exec -ti`

**Comment by bugzyz** [comment]
@javsalgar Thanks! I found it by specifying the target container name to login the container.
The reason that I didn't find it is that I use the `kubectl exec -it pod-xxx bash` which will lead me to the default git clone container.

**Comment by bugzyz** [comment]
Found the config file now, thanks for the helping
