### ISSUE TITLE
[bitnami/postgresql-ha] Cannot set externalTrafficPolicy

### ISSUE THREAD

**Issue by wolf31o2** [bitnami/charts#6091]
**Which chart**:
postgresql-ha 6.8.4

**Describe the bug**
Cannot set externalTrafficPolicy. This is necessary when using a NLB on AWS to pass client addresses to the Pods.

**To Reproduce**

1. Configure `service.externalTrafficPolicy to Local` in values.yaml
2. `helm template` to see the externalTrafficPolicy is not configured as expected

**Expected behavior**
Adds `spec.externalTrafficPolicy` with value `Local` in `Service` resource for pgpool.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by migruiz4** [comment]
Hi @wolf31o2 ,

Thank you for your feature request.

The Postgresql-Ha didn't have that feature, so I created this PR adding it: https://github.com/bitnami/charts/pull/6106

That should fix your issue.
