### ISSUE TITLE
[bitnami/MongoDB] add periodic volumesnapshots for CSI drivers 

### ISSUE THREAD

**Issue by halradaideh** [bitnami/charts#6092]
as stated in the title, it would be nice to support volumesnapshot feature for mongoDB to take backup and restore them on demand

you know that you can create a PVC based on a volumesnapshotcontent in k8s > 1.17
that would make backup / restore easier for the DB

and a cronjob to take the snapshot periodically would be nice too !

**Comment by alvneiayu** [comment]
hi @halradaideh 

Thanks a lot for the proposal. Let me investigate your suggestion and we will discuss it internally.

Thanks a lot again.

Álvaro

**Comment by halradaideh** [comment]
@alvneiayu  I have created a PR for an example template that i have developed to do this feature, please feel free to have a look.

**Comment by alvneiayu** [comment]
hi @halradaideh 

After our internal discussion. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot for your proposal again.

Álvaro

**Comment by halradaideh** [comment]
@alvneiayu Thank you again, I just wanted to help you with the PR for some ideas or a base if you want to continue on it.

Feel free to check PR #6109 .

**Comment by alvneiayu** [comment]
hi @halradaideh

Sure, I mean thanks a lot for your PR. We will investigate the feature and we are going to take into account your solution, for sure.

Thanks again

Álvaro

**Comment by halradaideh** [comment]
@javsalgar the PR #6109 also add volumesnapshot object ...

**Comment by javsalgar** [comment]
Hi,

We've been evaluating it, and currently, we decided to have the following approach in the chart:

   - Allow the maximum flexibility by allowing customization of almost everything, even allowing deploying extra objects by using `extraDeploy`. 
   - At the same time, limit the amount of extra features (such as automatic backups) unless there's a huge demand from the community. The reason is that, in the past, we had several issues trying to maintain features like that and, in the end, only covered certain use cases and not all. 

Because of that, we prefer that users that want to have automatic backups can use features like extraDeploy (being conscious that it is not as straightforward as setting two values when deploying), which can tweak to their liking. In order to support the backups you proposed, it's true that the dataSource field was missing, and that's why I added it in the PR above.

This issue was closed automatically before I was able to give the explanation to you, as the author of the original PR. We appreciate the effort that you put in your PR. I will leave here how this would look like if you were using `extraDeploy`

```
extraDeploy:  |
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: {{ include "mongodb.fullname" . }}-volume-snapshot
  spec:
    schedule: "{{ .Values.volumeSnapshot.cron }}"
    jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName: {{ template "mongodb.serviceAccountName" . }}
            containers:
              - name: backup-cron
                env:
                  - name: M_RELEASE_NAME
                    value: {{ include "mongodb.fullname" . }}
                  - name: M_PORT
                    value: {{ .Values.service.port | toString | quote }}
                  - name: M_ROOT_PASSWORD
                    value: {{ .Values.auth.rootPassword | toString | quote }}
                  - name: VSC_NAME
                    value: {{ .Values.volumeSnapshot.volumeSnapshotClass }}
                image: {{ .Values.volumeSnapshot.image }}
                imagePullPolicy: IfNotPresent
                command:
                  - /bin/bash
                  - -i
                  - -c
                  - |
                      set -e
                      echo alias M_CMD=\'mongo admin --host ${M_RELEASE_NAME}-1.{{ include "mongodb.service.nameOverride" . }}:${M_PORT} {{- if .Values.auth.enabled }} --authenticationDatabase admin -u root -p ${M_ROOT_PASSWORD} {{- end }} --quiet --eval\' >> ~/.bashrc
                      source ~/.bashrc
                      echo -e "[+] Check if it is a Primary node to make it stepDown\n"
                      if [[ `M_CMD " db.runCommand( { isMaster: 1 } )['ismaster']"` != "false" ]]
                      then
                        echo -e "[+] Stepping Down\n"
                        M_CMD "rs.stepDown()"
                      fi
                      echo -e "[+] Send Slave to Freeze\n"
                      M_CMD "rs.freeze(99999999999)"
                      export E_TIME=$(date +%s)
                      echo -e "[+] Creating snapshot object\n"
                      cat <<EOF | kubectl apply -f -
                      apiVersion: snapshot.storage.k8s.io/v1beta1
                      kind: VolumeSnapshot
                      metadata:
                        name: snapshot-${M_RELEASE_NAME}-${E_TIME}
                      spec:
                        volumeSnapshotClassName: ${VSC_NAME}
                        source:
                          persistentVolumeClaimName: datadir-${M_RELEASE_NAME}-1
                      EOF
                      echo -e "[+] Waiting for snapshot to finish\n"
                      while : ; do
                        result=$(kubectl get volumesnapshot   -o custom-columns='READY:.status.readyToUse' --field-selector metadata.name=snapshot-${M_RELEASE_NAME}-${E_TIME} | grep -v READY)
                        [[ "${result}" == "true" ]] && break
                        echo "[-] still waiting for snapshot to be ready .. "
                        sleep 1
                      done
                      echo -e "[+] Snapshot finished, unfreeze Slave\n"
                      M_CMD "rs.freeze(0)"
                      echo -e "[+] Snapshotting finished successfully\n"
            restartPolicy: OnFailure 
```

**Comment by halradaideh** [comment]
Understood, the only limitation in extraDeploy that we need to add extra access in the role too

**Comment by javsalgar** [comment]
I see. You may need to add the RBAC objects in the extraDeploy section as well. As it is  an array you could add it there.
