### ISSUE TITLE
[bitnami/mongodb] service.type parameter is ignored in templates

### ISSUE THREAD

**Issue by verymichael** [bitnami/charts#6093]
There is `service.type` parameter in Readme.md and values.yaml:
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/README.md#exposure-parameters
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L513

But in template there is fixed value `ClusterIP`:
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/headless-svc.yaml#L13

I believe either parameter should be added into template or removed from docs and values.yaml.

**Comment by javsalgar** [comment]
Hi,

Note that the `service.type` is used for standalone mode. If you are using the cluster mode and want external access, then you should set the `externalAccess` section and the `externalAccess.service.type` value.  Find more details here https://docs.bitnami.com/kubernetes/infrastructure/mongodb/configuration/configure-external-access-replicaset/
