### ISSUE TITLE
[bitnami/discourse] How to configure the smtp settings

### ISSUE THREAD

**Issue by RaphaelMui** [bitnami/charts#6095]
I installed bitname/discourse into my EKS cluster using 2.6.4 chart.  Everything seems working fine except the smtp email.  May I know to set my smtp host, port, username and password?

**Comment by marcosbc** [comment]
Hi @RaphaelMui, could you share more details on how you're configuring SMTP?

Note that if you are using Gmail and have 2-factor authentication enabled, you need to specify an App Password as the password for the account in the SMTP credentials: https://support.google.com/mail/answer/185833?hl=en

**Comment by RaphaelMui** [comment]
Hi @marcosbc, I haven't configured SMTP.  I just ran,

$ helm install --generate-name bitnami/discourse --namespace MYNAMESPACE

I am going to use AWS SES but I can't find any parameter in the helm chart which I can set my SMTP host and port.

**Comment by marcosbc** [comment]
I see. It seems like we have not added those options to `values.yaml`/`deployment.yaml` like for [other](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L152) [solutions](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/deployment.yaml#L162) (if you think this is useful, feel free to send a PR! we'd be happy to help with the release of those changes).

However, we do support the [`extraEnvVars`/`extraEnvVarsCM`/`extraEnvVarsSecret` options](https://github.com/bitnami/charts/blob/master/bitnami/discourse/values.yaml#L141) that you can use to specify the [SMTP configuration for this container image](https://github.com/bitnami/bitnami-docker-discourse#smtp-configuration). With that, you should be able to get it working.

**Comment by bensodenkamp** [comment]
Working on this..

**Comment by gammons** [comment]
@marcosbc I've been trying to use these by way of populating `extraEnvVars`.

I've tried a couple of different combinations:

1. Using `SMTP_HOST`, `SMTP_PORT`, etc, as listed in the SMTP configuration for the container image.
2. Using `DISCOURSE_SMTP_HOST`, `DISCOURSE_SMTP_PORT`, etc, [as described here](https://meta.discourse.org/t/troubleshooting-email-on-a-new-discourse-install/16326).
3. Using `SMTP_URL` [as described here](https://github.com/discourse/discourse_docker/blob/master/README.md).

**Results of Option 1 and 3:**

I get an error:
```
Welcome to the Bitnami discourse container                                                                           
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-discourse                         
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-discourse/issues                     
                                                                                                                     
nami    INFO  Initializing postgresql-client                                                                         
nami    INFO  postgresql-client successfully initialized                                                             
nami    INFO  Initializing discourse                                                                                 
discour INFO  Patching Discourse...                                                                                  
postgre INFO  Trying to connect to PostgreSQL server                                                                 
postgre INFO  Found PostgreSQL server listening at discourse-postgresql:5432                                         
postgre INFO  PostgreSQL server listening and working at discourse-postgresql:5432                                   discour INFO  Preparing Discourse environment...                                                                     
discour INFO  Configuring the Discourse database files...                                                            
discour INFO  Configuring Redis...                                                                                   
discour INFO  Setting up SMTP in Discourse...                                                                        
Error executing 'postInstallation': You should specify host and port for SMTP configuration  
```
Strangely, I cannot find what actually generates that error.

**Results of option 2**

The container boots and runs.  However, `discourse.conf` does not include the values provided by `DISCOURSE_SMTP_HOST`, etc.  It seems to include a stock set of values.  Additionally, the [GlobalSetting](https://github.com/discourse/discourse/blob/master/app/models/global_setting.rb#L357) class seems to not evaluate env vars if a `discourse.conf` file exsts.  So even if there is not a value provided by the configuration file, discourse will **not** evaluate an env var to see if there's a value there.

So right now I am stuck.  I don't know what script runs to generate discourse.conf.  To me, I believe there's a bug in that script that generates that file.  I am happy to submit a PR but right now I don't know where this script lives.  Grepping around in this repo for strings like `You should specify a host and port` comes up empty...

**Comment by RaphaelMui** [comment]
@marcosbc, I set the extraEnvVars as below and the smtp works now.  However when I try to reset the default user's password or set an alternate email, it keeps sending the confirmation email to user@example.com.  It seems that the --set discourse.email does not work.

```
$ helm upgrade bitnami/discourse \
...
--set discourse.email=me@gmail.com ^
--set discourse.extraEnvVars[0].name=SMTP_HOST,discourse.extraEnvVars[0].value=smtp.gmail.com \
--set discourse.extraEnvVars[1].name=SMTP_PORT,discourse.extraEnvVars[1].value='587' \
--set discourse.extraEnvVars[2].name=SMTP_USER,discourse.extraEnvVars[2].value=me@gmail.com \
--set discourse.extraEnvVars[3].name=SMTP_PASSWORD,discourse.extraEnvVars[3].value=<mygmailpassword> \
--set sidekiq.extraEnvVars[0].name=SMTP_HOST,sidekiq.extraEnvVars[0].value=smtp.gmail.com \
--set sidekiq.extraEnvVars[1].name=SMTP_PORT,sidekiq.extraEnvVars[1].value='587' \
--set sidekiq.extraEnvVars[2].name=SMTP_USER,sidekiq.extraEnvVars[2].value=me@gmail.com \
--set sidekiq.extraEnvVars[3].name=SMTP_PASSWORD,sidekiq.extraEnvVars[3].value=<mygmailpassword>
```

**Comment by marcosbc** [comment]
@RaphaelMui Unfortunately it is not possible to change user password or e-mail after the initial deployment, because that data is stored in the database. We have only implemented logic to create a user, but not modify it.

In your case, you would need to modify the user e-mail or password manually, either in the Discourse app's admin panel or in the database.

The SMTP credentials, however, can be changed after a re-deployment because they are written to a configuration file, which is regenerated each time the container is recreated.

**Comment by gammons** [comment]
ah ha!  ok, disregard my above post, this is now working for me.  I was accidentally using `SMTP_ADDRESS` instead of `SMTP_HOST` :facepalm: 

Therefore option 1 above did work for me.

**Comment by vekariyabhargav** [comment]
helm upgrade my-release bitnami/discourse \
    --set discourse.host=$DISCOURSE_HOST \
    --set discourse.password=$DISCOURSE_PASSWORD \
    --set postgresql.postgresqlPassword=$POSTGRESQL_PASSWORD \
    --set discourse.email=demo@gmail.com \
    --set discourse.extraEnvVars[0].name=SMTP_HOST,discourse.extraEnvVars[0].value=smtp.gmail.com \
    --set discourse.extraEnvVars[1].name=SMTP_PORT,discourse.extraEnvVars[1].value=587 \
    --set discourse.extraEnvVars[2].name=SMTP_USER,discourse.extraEnvVars[2].value=demo@gmail.com \
    --set discourse.extraEnvVars[3].name=SMTP_PASSWORD,discourse.extraEnvVars[3].value=password \
    --set sidekiq.extraEnvVars[0].name=SMTP_HOST,sidekiq.extraEnvVars[0].value=smtp.gmail.com \
    --set sidekiq.extraEnvVars[1].name=SMTP_PORT,sidekiq.extraEnvVars[1].value=587 \
    --set sidekiq.extraEnvVars[2].name=SMTP_USER,sidekiq.extraEnvVars[2].value=demo@gmail.com \
    --set sidekiq.extraEnvVars[3].name=SMTP_PASSWORD,sidekiq.extraEnvVars[3].value=password

using above command and getting below error

Error: UPGRADE FAILED: cannot patch "my-release-discourse" with kind Deployment:  "" is invalid: patch: Invalid value: "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"deployment.kubernetes.io/revision\":\"1\",\"meta.helm.sh/release-name\":\"my-release\",\"meta.helm.sh/release-namespace\":\"default\"},\"creationTimestamp\":\"2021-06-15T13:03:19Z\",\"generation\":1,\"labels\":{\"app.kubernetes.io/instance\":\"my-release\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"discourse\",\"component\":\"discourse\",\"helm.sh/chart\":\"discourse-2.3.0\"},\"managedFields\":[{\"manager\":\"Go-http-client\",\"operation\":\"Update\",\"apiVersion\":\"apps/v1\",\"time\":\"2021-06-15T13:03:19Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:meta.helm.sh/release-name\":{},\"f:meta.helm.sh/release-namespace\":{}},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/instance\":{},\"f:app.kubernetes.io/managed-by\":{},\"f:app.kubernetes.io/name\":{},\"f:component\":{},\"f:helm.sh/chart\":{}}},\"f:spec\":{\"f:progressDeadlineSeconds\":{},\"f:replicas\":{},\"f:revisionHistoryLimit\":{},\"f:selector\":{\"f:matchLabels\":{\".\":{},\"f:app.kubernetes.io/instance\":{},\"f:app.kubernetes.io/name\":{},\"f:component\":{}}},\"f:strategy\":{\"f:rollingUpdate\":{\".\":{},\"f:maxSurge\":{},\"f:maxUnavailable\":{}},\"f:type\":{}},\"f:template\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:checksum/config\":{},\"f:checksum/secrets-database\":{},\"f:checksum/secrets-discourse\":{},\"f:checksum/secrets-redis\":{}},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/instance\":{},\"f:app.kubernetes.io/managed-by\":{},\"f:app.kubernetes.io/name\":{},\"f:component\":{},\"f:helm.sh/chart\":{}}},\"f:spec\":{\"f:affinity\":{\".\":{},\"f:podAntiAffinity\":{\".\":{},\"f:preferredDuringSchedulingIgnoredDuringExecution\":{}}},\"f:containers\":{\"k:{\\\"name\\\":\\\"discourse\\\"}\":{\".\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"DISCOURSE_PASSWORD\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:secretKeyRef\":{\".\":{},\"f:key\":{},\"f:name\":{}}}},\"k:{\\\"name\\\":\\\"DISCOURSE_POSTGRESQL_PASSWORD\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:secretKeyRef\":{\".\":{},\"f:key\":{},\"f:name\":{}}}},\"k:{\\\"name\\\":\\\"POSTGRESQL_ROOT_PASSWORD\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:secretKeyRef\":{\".\":{},\"f:key\":{},\"f:name\":{}}}}},\"f:envFrom\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:livenessProbe\":{\".\":{},\"f:failureThreshold\":{},\"f:httpGet\":{\".\":{},\"f:path\":{},\"f:port\":{},\"f:scheme\":{}},\"f:initialDelaySeconds\":{},\"f:periodSeconds\":{},\"f:successThreshold\":{},\"f:timeoutSeconds\":{}},\"f:name\":{},\"f:ports\":{\".\":{},\"k:{\\\"containerPort\\\":3000,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:name\":{},\"f:protocol\":{}}},\"f:readinessProbe\":{\".\":{},\"f:failureThreshold\":{},\"f:httpGet\":{\".\":{},\"f:path\":{},\"f:port\":{},\"f:scheme\":{}},\"f:initialDelaySeconds\":{},\"f:periodSeconds\":{},\"f:successThreshold\":{},\"f:timeoutSeconds\":{}},\"f:resources\":{},\"f:securityContext\":{},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{},\"f:volumeMounts\":{\".\":{},\"k:{\\\"mountPath\\\":\\\"/bitnami/discourse\\\"}\":{\".\":{},\"f:mountPath\":{},\"f:name\":{},\"f:subPath\":{}}}},\"k:{\\\"name\\\":\\\"sidekiq\\\"}\":{\".\":{},\"f:args\":{},\"f:command\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"DISCOURSE_HOST\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"DISCOURSE_PASSWORD\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:secretKeyRef\":{\".\":{},\"f:key\":{},\"f:name\":{}}}},\"k:{\\\"name\\\":\\\"DISCOURSE_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"DISCOURSE_POSTGRESQL_PASSWORD\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:secretKeyRef\":{\".\":{},\"f:key\":{},\"f:name\":{}}}}},\"f:envFrom\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:livenessProbe\":{\".\":{},\"f:exec\":{\".\":{},\"f:command\":{}},\"f:failureThreshold\":{},\"f:initialDelaySeconds\":{},\"f:periodSeconds\":{},\"f:successThreshold\":{},\"f:timeoutSeconds\":{}},\"f:name\":{},\"f:readinessProbe\":{\".\":{},\"f:exec\":{\".\":{},\"f:command\":{}},\"f:failureThreshold\":{},\"f:initialDelaySeconds\":{},\"f:periodSeconds\":{},\"f:successThreshold\":{},\"f:timeoutSeconds\":{}},\"f:resources\":{},\"f:securityContext\":{},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{},\"f:volumeMounts\":{\".\":{},\"k:{\\\"mountPath\\\":\\\"/bitnami/discourse\\\"}\":{\".\":{},\"f:mountPath\":{},\"f:name\":{},\"f:subPath\":{}}}}},\"f:dnsPolicy\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{},\"f:serviceAccount\":{},\"f:serviceAccountName\":{},\"f:terminationGracePeriodSeconds\":{},\"f:volumes\":{\".\":{},\"k:{\\\"name\\\":\\\"discourse-data\\\"}\":{\".\":{},\"f:name\":{},\"f:persistentVolumeClaim\":{\".\":{},\"f:claimName\":{}}}}}}}}},{\"manager\":\"kube-controller-manager\",\"operation\":\"Update\",\"apiVersion\":\"apps/v1\",\"time\":\"2021-06-15T13:06:42Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\"f:deployment.kubernetes.io/revision\":{}}},\"f:status\":{\"f:availableReplicas\":{},\"f:conditions\":{\".\":{},\"k:{\\\"type\\\":\\\"Available\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Progressing\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:observedGeneration\":{},\"f:readyReplicas\":{},\"f:replicas\":{},\"f:updatedReplicas\":{}}}}],\"name\":\"my-release-discourse\",\"namespace\":\"default\",\"resourceVersion\":\"41273\",\"uid\":\"897a579b-b840-4e69-9503-99bf0649cbcf\"},\"spec\":{\"progressDeadlineSeconds\":600,\"replicas\":1,\"revisionHistoryLimit\":10,\"selector\":{\"matchLabels\":{\"app.kubernetes.io/instance\":\"my-release\",\"app.kubernetes.io/name\":\"discourse\",\"component\":\"discourse\"}},\"strategy\":{\"type\":\"RollingUpdate\",\"rollingUpdate\":{\"maxUnavailable\":\"25%!\(MISSING)",\"maxSurge\":\"25%!\(MISSING)"}},\"template\":{\"metadata\":{\"annotations\":{\"checksum/config\":\"c17d79be4d33a3b5af0db6be35e990f3f9d422f005f858e3ff154cfe214a8a6d\",\"checksum/secrets-database\":\"01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b\",\"checksum/secrets-discourse\":\"a0829ea6dfd0706dcf88676a7ac19a4e72fa7b80f36dc86c85799a4414c6e2b5\",\"checksum/secrets-redis\":\"01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b\"},\"creationTimestamp\":null,\"labels\":{\"app.kubernetes.io/instance\":\"my-release\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"discourse\",\"component\":\"discourse\",\"helm.sh/chart\":\"discourse-2.3.0\"}},\"spec\":{\"affinity\":{\"podAntiAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"weight\":1,\"podAffinityTerm\":{\"labelSelector\":{\"matchLabels\":{\"app.kubernetes.io/instance\":\"my-release\",\"app.kubernetes.io/name\":\"discourse\"}},\"namespaces\":[\"default\"],\"topologyKey\":\"kubernetes.io/hostname\"}}]}},\"containers\":[{\"env\":[{\"name\":\"DISCOURSE_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"discourse-password\",\"name\":\"my-release-discourse-discourse\"}}},{\"name\":\"DISCOURSE_POSTGRESQL_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"postgresql-password\",\"name\":\"my-release-postgresql\"}}},{\"name\":\"POSTGRESQL_ROOT_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"postgresql-postgres-password\",\"name\":\"my-release-postgresql\"}}},{\"name\":\"SMTP_HOST\",\"value\":\"smtp.gmail.com\"},{\"name\":\"SMTP_PORT\",\"value\":587},{\"name\":\"SMTP_USER\",\"value\":\"bantudo9@gmail.com\"},{\"name\":\"SMTP_PASSWORD\",\"value\":\"cpegmpkffefritsh\"}],\"envFrom\":[{\"configMapRef\":{\"name\":\"my-release-discourse\"}}],\"image\":\"docker.io/bitnami/discourse:2.6.1-debian-10-r5\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"failureThreshold\":6,\"httpGet\":{\"path\":\"/\",\"port\":\"http\"},\"initialDelaySeconds\":500,\"periodSeconds\":10,\"successThreshold\":1,\"timeoutSeconds\":5},\"name\":\"discourse\",\"ports\":[{\"containerPort\":3000,\"name\":\"http\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":6,\"httpGet\":{\"path\":\"/\",\"port\":\"http\"},\"initialDelaySeconds\":30,\"periodSeconds\":10,\"successThreshold\":1,\"timeoutSeconds\":5},\"securityContext\":{},\"volumeMounts\":[{\"mountPath\":\"/bitnami/discourse\",\"name\":\"discourse-data\",\"subPath\":\"discourse\"}]},{\"args\":[\"nami\",\"start\",\"--foreground\",\"discourse-sidekiq\"],\"command\":[\"/app-entrypoint.sh\"],\"env\":[{\"name\":\"DISCOURSE_HOST\",\"value\":\"127.0.0.1\"},{\"name\":\"DISCOURSE_PORT\",\"value\":\"3000\"},{\"name\":\"DISCOURSE_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"discourse-password\",\"name\":\"my-release-discourse-discourse\"}}},{\"name\":\"DISCOURSE_POSTGRESQL_PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"postgresql-password\",\"name\":\"my-release-postgresql\"}}},{\"name\":\"SMTP_HOST\",\"value\":\"smtp.gmail.com\"},{\"name\":\"SMTP_PORT\",\"value\":587},{\"name\":\"SMTP_USER\",\"value\":\"bantudo9@gmail.com\"},{\"name\":\"SMTP_PASSWORD\",\"value\":\"cpegmpkffefritsh\"}],\"envFrom\":[{\"configMapRef\":{\"name\":\"my-release-discourse\"}}],\"image\":\"docker.io/bitnami/discourse:2.6.1-debian-10-r5\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"exec\":{\"command\":[\"/bin/sh\",\"-c\",\"nami status discourse-sidekiq\"]},\"failureThreshold\":6,\"initialDelaySeconds\":500,\"periodSeconds\":10,\"successThreshold\":1,\"timeoutSeconds\":5},\"name\":\"sidekiq\",\"readinessProbe\":{\"exec\":{\"command\":[\"/bin/sh\",\"-c\",\"nami status discourse-sidekiq\"]},\"failureThreshold\":6,\"initialDelaySeconds\":30,\"periodSeconds\":10,\"successThreshold\":1,\"timeoutSeconds\":5},\"securityContext\":{},\"volumeMounts\":[{\"mountPath\":\"/bitnami/discourse\",\"name\":\"discourse-data\",\"subPath\":\"discourse\"}]}],\"dnsPolicy\":\"ClusterFirst\",\"restartPolicy\":\"Always\",\"schedulerName\":\"default-scheduler\",\"securityContext\":{},\"serviceAccount\":\"default\",\"serviceAccountName\":\"default\",\"terminationGracePeriodSeconds\":30,\"volumes\":[{\"name\":\"discourse-data\",\"persistentVolumeClaim\":{\"claimName\":\"my-release-discourse\"}}]}}},\"status\":{\"observedGeneration\":1,\"replicas\":1,\"updatedReplicas\":1,\"readyReplicas\":1,\"availableReplicas\":1,\"conditions\":[{\"type\":\"Available\",\"status\":\"True\",\"lastUpdateTime\":\"2021-06-15T13:06:42Z\",\"lastTransitionTime\":\"2021-06-15T13:06:42Z\",\"reason\":\"MinimumReplicasAvailable\",\"message\":\"Deployment has minimum availability.\"},{\"type\":\"Progressing\",\"status\":\"True\",\"lastUpdateTime\":\"2021-06-15T13:06:42Z\",\"lastTransitionTime\":\"2021-06-15T13:03:19Z\",\"reason\":\"NewReplicaSetAvailable\",\"message\":\"ReplicaSet \\\"my-release-discourse-6df9d8499c\\\" has successfully progressed.\"}]}}": v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 5, error found in #10 byte of ...|,"value":587},{"name|..., bigger context ...|e":"smtp.gmail.com"},{"name":"SMTP_PORT","value":587},{"name":"SMTP_USER","value":"bantudo9@gmail.co|...

**Comment by marcosbc** [comment]
Hi @vekariyabhargav, since your issue does not look related, could you open a new one? Also please provide more info like the version you are upgrading from, the version you are upgrading to and any additional info that may help us reproduce this issue, in addition to filling in the form in the New Issue page.

**Comment by vekariyabhargav** [comment]
i guess my issue is related to this only because i am also trying to use SMTP config in discourse. i am trying solution provided by @RaphaelMui. Please help me. Thanks in advance

**Comment by RaphaelMui** [comment]
@vekariyabhargav,  the chart expects the SMTP_PORT is a string.  I guess you should quote the value 587.

**Comment by marcosbc** [comment]
@vekariyabhargav Like suggested by @RaphaelMui (thanks!), you should change `--set discourse.extraEnvVars[1].name=SMTP_PORT,discourse.extraEnvVars[1].value=587` by `--set-string ...` (and the same for sidekiq), or specify it in quotes like how it was done above.
