### ISSUE TITLE
Kibana chart throws error , unable to deploy it.

### ISSUE THREAD

**Issue by faisalbasha1982** [bitnami/charts#6099]
**Which chart**:
The name (and version) of the affected chart
Elastic , Kibana charts

**Describe the bug**
Deploying the kibana chart with the following command line:

helm install kibana kibana -n test --set sysctlImage.enabled=true,global.kibanaEnabled=true --set elasticsearch.hosts[0]=elasticsearch-coordinating-only --set elasticsearch.port=9200 --set service.type=LoadBalancer

results in the following issue:

kibana 10:27:05.28
kibana 10:27:05.29 Welcome to the Bitnami kibana container
kibana 10:27:05.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kibana
kibana 10:27:05.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kibana/issues
kibana 10:27:05.30
kibana 10:27:05.30 INFO  ==> ** Starting Kibana setup **
kibana 10:27:05.32 ERROR ==> An invalid port was specified in the environment variable KIBANA_PORT_NUMBER: value is not an integer

**To Reproduce**

1. helm upgrade elasticsearch elasticsearch -n test -f elasticsearch/values.yaml --install

2.  helm install kibana kibana -n test --set sysctlImage.enabled=true,global.kibanaEnabled=true --set elasticsearch.hosts[0]=elasticsearch-coordinating-only --set elasticsearch.port=9200 --set service.type=LoadBalancer

**Expected behavior**
Expected the pod to be running but I this is what I see:

```
NAME                                                                           READY    STATUS               RESTARTS   AGE
elasticsearch-coordinating-only-d7696bd55-5kc68      1/1       Running                    0          127m
elasticsearch-coordinating-only-d7696bd55-c6vdj       1/1       Running                    0          127m
elasticsearch-data-0                                                       1/1       Running                    0          127m
elasticsearch-data-1                                                       1/1       Running                    0          127m
elasticsearch-master-0                                                   1/1       Running                    0          127m
elasticsearch-master-1                                                   1/1       Running                    0          127m
kibana-55748b448f-ggkj9                                              0/1       CrashLoopBackOff    7          12m

```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @faisalbasha1982 ,
It seems that you are mixing options between the charts. The `kibanaEnabled` option must be passed to the Elasticsearch chart, not the kibana one.

Could you describe what are you trying to achieve?

**Comment by faisalbasha1982** [comment]
ok I solved this issue with installing helm charts, I had to use another name for kibana other than kibana, 
yet I have another issue with Logstash, 

trying to install logstash with pipeline scripts & conf, but there isnt an option to enable persistence in logstash values.yaml file.
What can I do about that? how do I persist data files so that logstash can read this from a mounted volume on its pod?

**Comment by miguelaeh** [comment]
Hi @faisalbasha1982 ,
The Logstash helm chart saves into a volume its configuration only. To save anything else you can use the `extraVolumeMounts` parameter.

**Comment by davejhahn** [comment]
I'm running into the same error:
` An invalid port was specified in the environment variable KIBANA_PORT_NUMBER: value is not an integer`

Not sure where this is coming from, not a parameter I need to set as far as I know.

**Comment by miguelaeh** [comment]
Hi @davejhahn ,
Could you share the steps you followed to get the error please?
