### ISSUE TITLE
[bitnami/kubeapps] kubeapps-postgresql-read-0 is stuck in a CrashLoopBackOff due to Postgresql not starting.

### ISSUE THREAD

**Issue by TikvahTerminator** [bitnami/charts#6107]
**Which chart**:
Bitnami/Kubeapps v 6.0.1

**Describe the bug**
Installing from fresh on Amazon EKS results in kubeapps-postgresql-read-0 becoming stuck in CrashLoopBackOff due to Readiness & Liveness checks failing. This is caused by Postgresql not being started on the pod, as the PGDATA directory; /bitnami/postgresql/data is empty. 

**To Reproduce**

1. Install Kubeapp's helm chart as described on [the repo's README](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps#installing-the-chart)

**Expected behavior**
All pods come up successfully and kubeapps is deployed into cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Could you show the logs of the pod? This would give us more insight about the error. Which PVC technology are you using?

**Comment by TikvahTerminator** [comment]
Good morning,

Thank you for your reply,

postgresql 10:43:08.07 Welcome to the Bitnami postgresql container
postgresql 10:43:08.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 10:43:08.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 10:43:08.07 
postgresql 10:43:08.09 INFO  ==> ** Starting PostgreSQL setup **
postgresql 10:43:08.10 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:43:08.11 INFO  ==> Loading custom pre-init scripts...
postgresql 10:43:08.11 INFO  ==> Initializing PostgreSQL database...
postgresql 10:43:08.13 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 10:43:08.14 INFO  ==> Generating local authentication configuration
postgresql 10:43:08.14 INFO  ==> Waiting for replication master to accept connections (60 timeout)...
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response
kubeapps-postgresql:5432 - no response

I believe we are using the AWS EBS CSI Driver, but when I run get pvc against the kubeapps namespace, nothing comes up. Should there be entries for a pvc?

Thanks Again,

**Comment by TikvahTerminator** [comment]
Apologies,

After testing we've discovered a Network Policy issue was the cause of our error

Thank you for your help!

**Comment by ChrisTomAlx** [comment]
@TikvahTerminator any chance you remember what exactly you did to fix this issue? I am debugging the exact same issue currently and any help would be greatly appreciated!
