### ISSUE TITLE
[etcd] Remove unnecessary dependency on persistence.enabled with disasterRecovery.enabled

### ISSUE THREAD

**Issue by mkhpalm** [bitnami/charts#6110]
**Which chart**:
etcd:6.1.5

**Is your feature request related to a problem? Please describe.**

**disasterRecovery** should have no requirement on StatefulSet **persistence** being set

https://github.com/bitnami/charts/blob/45e82dd9dc139e62ae034d667ca2b1d91d209de9/bitnami/etcd/templates/_helpers.tpl#L145-L152

**Describe the solution you'd like**

Remove this section since the dependency on persistence isn't necessary.

https://github.com/bitnami/charts/blob/45e82dd9dc139e62ae034d667ca2b1d91d209de9/bitnami/etcd/templates/_helpers.tpl#L145-L152

etcdctl snapshot save doesn't know or care how the node's storage was set up. When disasterRecover is used thats a completely different PVC all together. Somebody might want to rely on emptyDir with etcd redundancy with worst case scenario... snapshots as their safety net if they ever lose quorum.

**Comment by juan131** [comment]
Hi @mkhpalm 

Thanks for the feedback!

As you mentioned, the "snapshotter" cronjob uses its own PVC to store the snapshost. Therefore, a user could potentially to rely on a "emptyDir" volume.

That said, I think persistence is mandatory for this feature due to our current logic to detect when the cluster needs to recover itself using snapshots, see:

https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L399-427

To start this "recovery process", first it check if there's persistent data in the data volume. This would work using an "emptyDir" volume on container restarts, but it won't work if the pod is reallocated on a different K8s node.

**Comment by mkhpalm** [comment]
Oh, I guess maybe I didn't realize the `disasterRecovery` option was overloaded in meaning. Its not just making and storing snapshots, its also trying to dynamically decide if it should restore a **new** cluster automatically. I wish there was a way to *just* do snapshots and leave the running cluster alone as **existing**. Then let us decide if we want to enable restoreSnapshot for whatever reason to recover a completely failed cluster.

Something else worth noting is both local volume types (persistence: true) behave no differently than emptyDir (persistence: false) in relation to moving pods. So this disasterRecovery feature in this chart isn't supported depending on what storage class somebody is using (has to be remote storage)?

https://kubernetes.io/docs/concepts/storage/volumes/#local

Also, there seems to be a bug in the scripts causing it to try and restore the cluster regardless of whether a cluster is healthy or not. 

* This part: https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L405-L406
* Calls this function and tries to not call itself: https://github.com/bitnami/bitnami-docker-etcd/blob/f3e8a5669e23f95fcd91f5cb01a74cd4d82643ab/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L265
* But somehow always results in a `Cluster not responding!` and proceeds to restore the node from a snapshot. Once it does that it will never recover from it until manual intervention is done. I suspect the condition to not call itself never matches and thats why... etcd isn't started yet so there is no way it can respond to the init script.

Example of a 3 node cluster that is easily reproducable. All I did was restart a pod on an existing healthy cluster. It has persistence (rbd) and disasterRecovery both enabled. Snapshots are RWX on Gluster and I see no issue there, nor do I see a .disaster_recovery trigger existing before restarting the pod.
 
```
etcd 17:54:57.50 
etcd 17:54:57.50 Welcome to the Bitnami etcd container
etcd 17:54:57.51 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 17:54:57.51 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 17:54:57.51 
etcd 17:54:57.52 INFO  ==> ** Starting etcd setup **
etcd 17:54:57.56 INFO  ==> Validating settings in ETCD_* env vars..
etcd 17:54:57.57 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 17:54:57.57 INFO  ==> Initializing etcd
etcd 17:54:57.59 INFO  ==> Detected data from previous deployments
etcd 17:54:57.60 DEBUG ==> Setting data directory permissions to 700 in a recursive way (required in etcd >=3.4.10)
etcd 17:55:07.81 DEBUG ==> etcd-coredns-0.etcd-coredns-headless.ops.svc.cluster.local:2379 endpoint is active
etcd 17:55:07.85 DEBUG ==> etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2379 endpoint is active
etcd 17:55:07.85 WARN  ==> Cluster not responding!
etcd 17:55:07.87 INFO  ==> Restoring etcd cluster from snapshot
{"level":"info","ts":1618509313.0610576,"caller":"netutil/netutil.go:112","msg":"resolved URL Host","url":"http://etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2380","host":"etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2380","resolved-addr":"10.32.10.84:2380"}
{"level":"info","ts":1618509313.061258,"caller":"netutil/netutil.go:112","msg":"resolved URL Host","url":"http://etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2380","host":"etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2380","resolved-addr":"10.32.10.84:2380"}
{"level":"info","ts":1618509313.0614073,"caller":"snapshot/v3_snapshot.go:296","msg":"restoring snapshot","path":"/snapshots/db-2021-04-15_17-30","wal-dir":"/bitnami/etcd/data/member/wal","data-dir":"/bitnami/etcd/data","snap-dir":"/bitnami/etcd/data/member/snap"}
{"level":"info","ts":1618509313.2041075,"caller":"membership/cluster.go:392","msg":"added member","cluster-id":"7aa62d502d5dc00a","local-member-id":"0","added-peer-id":"7f08a0e29b73d2ba","added-peer-peer-urls":["http://etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2380"]}
{"level":"info","ts":1618509313.2042568,"caller":"membership/cluster.go:392","msg":"added member","cluster-id":"7aa62d502d5dc00a","local-member-id":"0","added-peer-id":"8872f627485531a8","added-peer-peer-urls":["http://etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2380"]}
{"level":"info","ts":1618509313.2043478,"caller":"membership/cluster.go:392","msg":"added member","cluster-id":"7aa62d502d5dc00a","local-member-id":"0","added-peer-id":"fa49eb086fe3290e","added-peer-peer-urls":["http://etcd-coredns-0.etcd-coredns-headless.ops.svc.cluster.local:2380"]}
{"level":"info","ts":1618509313.2786045,"caller":"snapshot/v3_snapshot.go:309","msg":"restored snapshot","path":"/snapshots/db-2021-04-15_17-30","wal-dir":"/bitnami/etcd/data/member/wal","data-dir":"/bitnami/etcd/data","snap-dir":"/bitnami/etcd/data/member/snap"}
etcd 17:55:13.29 INFO  ==> ** etcd setup finished! **
```

Now its in a crash loop...

**Comment by mkhpalm** [comment]
Sorry, that last test was with the prestop lifecycle hook disabled. I forgot I was trying something there but regardless that looks like a bug based on the script.

If I enable the prestop lifecycle hook (all back to chart defaults with persistence and disasterrecovery enabled) and do the exact same test as before:

```
etcd 19:56:17.22 
etcd 19:56:17.22 Welcome to the Bitnami etcd container
etcd 19:56:17.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 19:56:17.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 19:56:17.23 
etcd 19:56:17.23 INFO  ==> ** Starting etcd setup **
etcd 19:56:17.28 INFO  ==> Validating settings in ETCD_* env vars..
etcd 19:56:17.28 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 19:56:17.29 INFO  ==> Initializing etcd
etcd 19:56:17.31 INFO  ==> Detected data from previous deployments
etcd 19:56:17.32 DEBUG ==> Setting data directory permissions to 700 in a recursive way (required in etcd >=3.4.10)
etcd 19:56:27.52 DEBUG ==> etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2379 endpoint is active
etcd 19:56:27.56 DEBUG ==> etcd-coredns-0.etcd-coredns-headless.ops.svc.cluster.local:2379 endpoint is active
etcd 19:56:27.57 INFO  ==> Updating member in existing cluster
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
```

Now its in a crash loop again...

So the way to get around stuff like this is manually remove the member, delete the etcd and clobber its pvcs it'll finally be able to make it through all of the init scripts. Which is the reason it just seemed easier to use emptyDir/persistence=false cuz I wouldn't have to manually clobber the pod + the pvcs. We could just move the pod somewhere else.

**Comment by juan131** [comment]
Thanks for the feedback @mkhpalm 

> Oh, I guess maybe I didn't realize the disasterRecovery option was overloaded in meaning. Its not just making and storing snapshots, its also trying to dynamically decide if it should restore a new cluster automatically.

IMHO, the "disaster recovery" name is quite descriptive. I mean, it implies that is trying to do something to recover the cluster when something bad happens.

By the way, we also have a docs site explaining this feature:

- https://docs.bitnami.com/kubernetes/infrastructure/etcd/administration/enable-disaster-recovery

>  I wish there was a way to just do snapshots and leave the running cluster alone as existing. Then let us decide if we want to enable restoreSnapshot for whatever reason to recover a completely failed cluster.

That's currently not possible. Honestly, I didn't consider that use case when developing this feature. I guess you can use the `extraDeploy` parameter as a workaround to deploy your custom cronjob to create the snapshots, see:

- https://github.com/bitnami/charts/tree/master/bitnami/etcd#deploying-extra-resources

The `startFromSnapshot.*` parameters can help you with the second part. I mean, currently it's possible to start a new cluster from a snapshot if you previously created it, see:

- https://github.com/bitnami/charts/tree/master/bitnami/etcd#snapshotting-parameters

> Something else worth noting is both local volume types (persistence: true) behave no differently than emptyDir (persistence: false) in relation to moving pods.

Well, there is a difference between local volumes and emptyDir: emptyDir data will only survive on container restarts, while local volumes support pods reallocation as far as they're scheduled in the same K8s node. For instance: when doing a rolling update to update the etcd container version, data will survive using local volumes while it won't using emptyDir.

> So this disasterRecovery feature in this chart isn't supported depending on what storage class somebody is using (has to be remote storage)?

If you want to permit reallocating pods on any node: yes, you need a remote storage.

> Now its in a crash loop again...

What exact version of the etcd chart are you using? I remember I introduced some enhacements to avoid this error: `Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex`

**Comment by mkhpalm** [comment]
> What exact version of the etcd chart are you using? I remember I introduced some enhacements to avoid this error: Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

Chart version is listed at the top of the ticket:

> etcd:6.1.5

But more appropriately in this specific test the restore snapshot in the tagged image was hard coded to `FOO`, so I bumped the tag to `3.4.15-debian-10-r37` to get this. (the only change between the default and that version)

https://github.com/bitnami/bitnami-docker-etcd/commit/1afa27a9710caac5ef799d4ce939664de306863d#diff-cb004e553561f53933dbb9f85b8c88532908cd40de43fca9ef0f48b4dc34ce70

**Comment by juan131** [comment]
> When the etcd pod starts up there is a chance you'll temporarily see the ptr from `etcdctl member list`. I'm wondering if the issues of trying to identify itself go away if matched on hash or `NAME` rather than `PEER ADDR` or `CLIENT ADDR` values.

I don't fully understand what you mean. What does "ptr" stand for?

**Comment by mkhpalm** [comment]
> > When the etcd pod starts up there is a chance you'll temporarily see the ptr from `etcdctl member list`. I'm wondering if the issues of trying to identify itself go away if matched on hash or `NAME` rather than `PEER ADDR` or `CLIENT ADDR` values.
> 
> I don't fully understand what you mean. What does "ptr" stand for?

https://www.cloudflare.com/learning/dns/dns-records/dns-ptr-record/

Basically in the internals of etcd itself it may or may not respond with the "A" record for peers when you ask it "member list". The script line here assumes it will always return the "A" to not call itself.

https://github.com/bitnami/bitnami-docker-etcd/blob/f3e8a5669e23f95fcd91f5cb01a74cd4d82643ab/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L265

But you can see in the debug output here that is not always the case
```
etcd 18:05:27.50 DEBUG ==> 10-32-7-24.etcd-coredns.ops.svc.cluster.local:2379 endpoint is active <--- PTR
etcd 18:05:27.54 DEBUG ==> etcd-coredns-0.etcd-coredns-headless.ops.svc.cluster.local:2379 endpoint is active <--- A
```

The A record for the example above would be "etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2379"

**Comment by juan131** [comment]
Hi @mkhpalm 

Thanks so much for the detailed explanation, I can see the whole picture now.

> Proposed fix: use the member hashes (preferably) or names (should work) to identify etcd members since those are static fields. Instead of peer or client urls since those fields are derived and dynamic.

That would be an option, but the problem is that we don't know in advance other members hashes.

As you mentioned, both the A record and PTR record resolve to proper location. What about comparing if the obtained PTR record points to the same IP that any of the A records listed at `ETCD_ADVERTISE_CLIENT_URLS` environment variable?

**Comment by mkhpalm** [comment]
> That would be an option, but the problem is that we don't know in advance other members hashes.
> 
> As you mentioned, both the A record and PTR record resolve to proper location. What about comparing if the obtained PTR record points to the same IP that any of the A records listed at `ETCD_ADVERTISE_CLIENT_URLS` environment variable?

Hmmm, good question actually. I thought `/bitnami/etcd/data/member_id` was supposed to be populated with the id/hash and you could just use that to omit calling itself.

Where I thought it was getting set: https://github.com/bitnami/bitnami-docker-etcd/blob/8a12db98546a66cbe8e3a09ecf6a1884bf3062dc/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L172-L183

Live example has nothing in there for me (probably explains the other issue in this ticket too):
```
I have no name!@etcd-coredns-1:/opt/bitnami/etcd$ ls -l /bitnami/etcd/data/member_id 
-rw-r--r-- 1 1001 1001 0 Apr 15 19:48 /bitnami/etcd/data/member_id
I have no name!@etcd-coredns-1:/opt/bitnami/etcd$ cat /bitnami/etcd/data/member_id
```

Maybe something along these lines to align it with member name somewhere?

```bash
echo "http://etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2380" | awk -F / '{print $3}' | cut -d . -f 1
etcd-coredns-1

etcdctl member list --write-out=table
+------------------+---------+----------------+------------------------------------------------------------------------+------------------------------------------------------------------------+------------+
|        ID        | STATUS  |      NAME      |                               PEER ADDRS                               |                              CLIENT ADDRS                              | IS LEARNER |
+------------------+---------+----------------+------------------------------------------------------------------------+------------------------------------------------------------------------+------------+
| 514f7ff17a6705de | started | etcd-coredns-2 | http://etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2380 | http://etcd-coredns-2.etcd-coredns-headless.ops.svc.cluster.local:2379 |      false |
| 8ff417ad0225ffc2 | started | etcd-coredns-1 | http://etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2380 | http://etcd-coredns-1.etcd-coredns-headless.ops.svc.cluster.local:2379 |      false |
| 9d163a52232220d1 | started | etcd-coredns-0 | http://etcd-coredns-0.etcd-coredns-headless.ops.svc.cluster.local:2380 | http://etcd-coredns-0.etcd-coredns-headless.ops.svc.cluster.local:2379 |      false |
+------------------+---------+----------------+------------------------------------------------------------------------+------------------------------------------------------------------------+------------+
```

**Possible ideas?**

I wonder if just populating the `member_id` file to contain the hash and then using the id/hash value inside there for anywhere that uses `ETCD_ADVERTISE_CLIENT_URLS` would solve a lot of problems? In this case we are just now talking about... call every endpoint that *doesn't* have the hash inside member_id similar to what its doing now.

_P.S. Sorry I'm kinda all over the place in this ticket. It started with "I wish it wouldn't restore over itself or I could use emptyDir and move failing pods to fix them" but that has gotten deeper as I learn more and look at things._

**Comment by juan131** [comment]
@mkhpalm 

As you said the "etcd_store_member_id" function is meant to obtain the ID and store it in the persistent volume. This is used during container restarts (or pods reallocations) to decide if a member should be added or updated in the cluster.

However, when executing the "is_healthy_etcd_cluster" we haven't obtained the ID yet, therefore it's not an option to use it.

---

I've been thinking about this... The "is_healthy_etcd_cluster" is based on asking every to every endpoint reported by the function "etcdctl_get_endpoints" whether the endpoint is safe or not. This "etcdctl_get_endpoints" obtains the endpoints by consulting the DNS (this is the reason why in rare occasions it returns PTR records).

In case a PTR record is reported, [this line](https://github.com/bitnami/bitnami-docker-etcd/blob/8a12db98546a66cbe8e3a09ecf6a1884bf3062dc/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L265) will always match the 1st condition (even when the record points to the pod that's being initialized, which is wrong):

```
        if [[ "$e" != "$ETCD_ADVERTISE_CLIENT_URLS" ]] && etcdctl endpoint health "${extra_flags[@]}" >/dev/null 2>&1; then
```

This is not problematic to check if other members are alive (which is the purpose of the function), and it should not be problematic either when it attempts to check the health on itself since the second condition will fail.
