### ISSUE TITLE
Need levers to set kubernetes secrets in logstash chart

### ISSUE THREAD

**Issue by arvin6msd** [bitnami/charts#6111]
**Which chart**: 
bitnami/logstash

**Is your feature request related to a problem? Please describe.**
When we authenticate ES with username and password it is desirable to pull them from secrets as opposed to hard coding them. The readme does not seem to have a way to attach custom CM or kubernetes secrets.

**Describe the solution you'd like**
A way to set custom secrets to the env `envFrom`

**Describe alternatives you've considered**
Ugly Hardcoding of credentials

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure on how you will be using the user/password. 
  Could you provide and example? or better, would you like to send an PR ? We will be glad to review and merge it.

**Comment by arvin6msd** [comment]
Hi @rafariossaa, thanks for responding. An example is given below.

```output {
    elasticsearch {
      hosts => ["${ES_HOST}"]
      user => "${ES_USER}"
      password => "${ES_PASSWORD}"
      index => "%{source}_catalog_%{+YYYY.ww}"
      retry_on_conflict => 5
      ilm_enabled => false
      document_id => "%{[mad_id]}"
      action => "update"
      doc_as_upsert => true
      manage_template => false
    }```

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for the PR.
  Let's wait until it gets reviewed and merged.
