### ISSUE TITLE
Multiple Persistent Volume Claims

### ISSUE THREAD

**Issue by derekrprice** [bitnami/charts#6124]
**Which chart**:
kafka 12.17.3

**Is your feature request related to a problem? Please describe.**
I would like to spread my broker data across multiple persistent volume claims.  The issue is that, at least in Azure, accessing four disks simultaneously can be considerably faster than four threads accessing a single disk.  Looking at the Azure pricing page here, notice for example that 4x 128GB disks can Burst to 14000 IOPS and 680MB/s, compared to 3500 IOPS and 170MB/s for a single 512GB disk.  For my VM size, this is actually supported up to accessing 8 disks concurrently.
![image](https://user-images.githubusercontent.com/5413632/114936184-13900800-9e0a-11eb-97b9-fd40bada64fd.png)

**Describe the solution you'd like**
I would like to propose two possible solutions.  The first, and easiest for the user, is to add a `persistence.numDisks` option which would automatically allocate and mount multiple persistent volume claims of `persistence.size`, mount them at `/bitnami/kafka/data-{i}`, where `i` is a disk index, and set `logDirs` to the list of all of the mounted data directories.

The second possible solution is to process the `extraVolumes` and `extraVolumeMounts` parameters as templates so that I can manage the storage myself and still have each replica mount a different set of data directories.

**Describe alternatives you've considered**
The Confluent Platform Helm chart is configurable per my first proposal but much less friendly in other ways, so I would prefer an updated Bitnami chart.  The other option is just to pay for a much larger VM & disk than I otherwise need in order to get the increased IOPS and  throughput from Azure.

**Additional context**
I'm not actually sure that I am reading this Azure pricing & performance page correctly, but I think the implication is that each disk connected to my VM is actually limited to 500 IOPS, so 4x128GB disks are actually 4x as fast as a single 512GB disk, even under sustained usage.
![image](https://user-images.githubusercontent.com/5413632/114937799-46d39680-9e0c-11eb-8f9d-5f6d9ceab7f0.png)

**Comment by migruiz4** [comment]
Hi @derekrprice,

First of all, I think you are ignoring one important thing here. 

Attaching all 8 disks to a single pod won't multiply (x8) the number of IOPS as Kafka can only write data to a single path.
In this case, Kafka is configured to store its data at `/bitnami/cassandra` where we are mounting the `data` volume.

Only 1 disk can be mounted in that path, so you would have 1 operative disk working at 500 IOPS and 7 idle disks.

Additionally, I'd like to ask you about your Kubernetes cluster and what kind of StorageClass are you using for your PCVs, all your approach would use the host storage as StorageClass for your pods, which would not be recommended for production environments.

**Comment by derekrprice** [comment]
Unless I am misreading your documentation, the current PVC is mounted at `/bitnami/kafka`, but Kafka is actually configured to store its topic partition data across a comma-separated list of directories which defaults to `/bitnami/kafka/data` (via the Bitnami `logDirs` chart setting).

It is easy to find multiple sources recommending using Kafka's `log.dirs` configuration option to spread topic partitions across multiple disks as a best practice.  Here are just the top 3 hits:

* https://docs.confluent.io/platform/current/kafka/deployment.html#disks
* https://community.cloudera.com/t5/Community-Articles/Kafka-Best-Practices/ta-p/249371#toc-hId--1712957133
* https://stackoverflow.com/questions/36061426/how-to-spread-existing-kafka-topic-partitions-into-more-directories

I am suggesting that the Bitnami chart's `logDirs` be updated automatically when my new suggested `persistence.numDisks` setting is used, in order to take advantage of Kafka's ability to spread data across multiple disks.

Finally, to answer your question, I created a custom storage class in order to locate my PVCs in a specific Azure Resource Group and I reference it in `persistence.storageClass`.  It should create Azure's Premium SSD Managed Disk instances.  I haven't tested it with Bitnami yet, but it works fine with the corresponding setting in the Confluent chart:

    allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: kafka-data
    parameters:
      kind: Managed
      resourceGroup: Production-Dynamic-Storage
      storageaccounttype: Premium_LRS
    provisioner: kubernetes.io/azure-disk
    reclaimPolicy: Retain
    volumeBindingMode: Immediate

**Comment by migruiz4** [comment]
Hi @derekrprice,

I'm sorry for the misunderstanding, I didn't know Kafka could be configured to have multiple data directories.

In that case, it would be interesting to add the feature you suggested. 

Currently, it could be possible to configure it using an `extraEnvVar` to set `KAFKA_LOGS_DIRS` and then add the extra PVCs as ExtraVolumeMount, but I will create an internal task with this feature request to implement it so it can be configured with a single value and create multiple data PVCs, for example `data-0, data-1, ...`

**Comment by derekrprice** [comment]
I mentioned the extraVolumeMount possibility in my original suggestion.  It should work fine as long as you only have a single broker pod, I think.  Unfortunately, if you want to use multiple brokers, then this would leave them all sharing the same data disks, unless I am again misreading the docs.  To be able to mount different disks on each broker, I think that this helm chart would need to interpret the extraVolumeMounts variable as a template like it does some other settings.  Overall, using `persistence.numDisks` to create multiple, separate PVCs for each broker sounds much easier to configure from a user perspective.

**Comment by migruiz4** [comment]
That's correct, using `extraVolumeMount` would not work when using multiple brokers.

We will work to add the feature `persistence.numDisks` or similar for the Kafka Helm chart, but I can not give you an ETA for it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
