### ISSUE TITLE
Grafana-Operator cluster-role missing permissions

### ISSUE THREAD

**Issue by shalomcbouncex** [bitnami/charts#6125]
**Which chart**:
grafana-operator

**Describe the bug**
The clusterrole for the operator is missing 2 permissions that I found so far:
create for events
patch for grafanadashboards

**To Reproduce**

1. Deploy the operator with all namespace CRD lookup.
2. Create grafana via the operator.
3. Create Dashboard via the grafanadashboard CRD in a different namespace than the one grafana operator is installed on.
4. Watch the logs of the operator, it just claims to fail to patch the dashboard and create events.

**Expected behavior**
Grafana operator should not run into missing permissions, at the moment it is trying to do things that are missing in the clusterrole (therefore fails by default).

**Version of Helm and Kubernetes**:
Latest(0.3.0)

**Additional context**
I saw it specifically with dashboard CRD on a different namespace - that's why refer to the cluster role(this should be a common scenario).

**Comment by alvneiayu** [comment]
hi @shalomcbouncex 

Could you share the logs with me, please?
What is the dashboard that you are selecting?
Could you share with me the values that you are using, please?

Thanks

Álvaro

**Comment by shalomcbouncex** [comment]
Sure, Here are some of the logs that I noticed:
{"level":"error","ts":1618521404.814642,"logger":"controller_grafanadashboard","msg":"error updating dashboard","error":"unable to obtain dashboard contents","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).manageError\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:366\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:274\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
E0415 21:16:44.817802       1 event.go:260] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"istio-mesh.16762495cae7d1c2", GenerateName:"", Namespace:"istio-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"GrafanaDashboard", Namespace:"istio-system", Name:"istio-mesh", UID:"a6ffbee6-cc30-4290-82b5-57e249037135", APIVersion:"integreatly.org/v1alpha1", ResourceVersion:"739586795", FieldPath:""}, Reason:"ProcessingError", Message:"unable to obtain dashboard contents", Source:v1.EventSource{Component:"controller_grafanadashboard", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc016491f73362fc2, ext:101064041764882, loc:(*time.Location)(0x2297020)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc016492f308e2702, ext:101126997198187, loc:(*time.Location)(0x2297020)}}, Count:8, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "istio-mesh.16762495cae7d1c2" is forbidden: User "system:serviceaccount:ops:grafana-operator" cannot patch resource "events" in API group "" in the namespace "istio-system"' (will not retry!)
{"level":"error","ts":1618521414.814459,"logger":"dashboard-istio-mesh","msg":"failed to request dashboard url, falling back to raw json","error":"request failed with status 404","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*DashboardPipelineImpl).obtainJson\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_pipeline.go:117\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*DashboardPipelineImpl).ProcessDashboard\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_pipeline.go:56\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:270\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
{"level":"error","ts":1618521414.8145363,"logger":"controller_grafanadashboard","msg":"cannot process dashboard istio-system/istio-mesh","error":"unable to obtain dashboard contents","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:273\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
{"level":"error","ts":1618521414.8145986,"logger":"controller_grafanadashboard","msg":"error updating dashboard","error":"unable to obtain dashboard contents","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/hstefans/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).manageError\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:366\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).reconcileDashboards\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:274\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.(*ReconcileGrafanaDashboard).Reconcile\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:136\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func1\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:86\ngithub.com/integr8ly/grafana-operator/v3/pkg/controller/grafanadashboard.add.func2\n\tgrafana-operator/pkg/controller/grafanadashboard/dashboard_controller.go:92"}
E0415 21:16:54.818018       1 event.go:260] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"istio-mesh.16762495cae7d1c2", GenerateName:"", Namespace:"istio-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"GrafanaDashboard", Namespace:"istio-system", Name:"istio-mesh", UID:"a6ffbee6-cc30-4290-82b5-57e249037135", APIVersion:"integreatly.org/v1alpha1", ResourceVersion:"739586795", FieldPath:""}, Reason:"ProcessingError", Message:"unable to obtain dashboard contents", Source:v1.EventSource{Component:"controller_grafanadashboard", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc016491f73362fc2, ext:101064041764882, loc:(*time.Location)(0x2297020)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc0164931b08d83e7, ext:101136997156422, loc:(*time.Location)(0x2297020)}}, Count:9, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "istio-mesh.16762495cae7d1c2" is forbidden: User "system:serviceaccount:ops:grafana-operator" cannot patch resource "events" in API group "" in the namespace "istio-system"' (will not retry!)

**Comment by alvneiayu** [comment]
hi @shalomcbouncex 

Just to be in the same line than you. Are you using the default values inside the grafana chart no?. If not, please share with me your values. I am investigating the issue and trying to reproduce your problem.

Thanks for your help and time

Álvaro
