### ISSUE TITLE
[bitnami/logstash] provide namespace in metadata

### ISSUE THREAD

**Issue by dafik** [bitnami/charts#6130]
[bitnami/logstash] 3.2.3

if you have access to more than one namespace , chart is installed in current namespace

Add 
```
metadata:
  namespace: {{ .Release.Namespace }}

```
in all templates

bitnami/keycloak has this implemented:
https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/service.yaml#L5

**Comment by miguelaeh** [comment]
Hi @dafik ,
Would you like to create a PR by adding it?

**Comment by miguelaeh** [comment]
Hi @dafik ,
Any news on this?
Will you create a PR?
