### ISSUE TITLE
Missing extraDeploy in Mediawiki chart

### ISSUE THREAD

**Issue by dudefellah** [bitnami/charts#6139]
**Which chart**:
Mediawiki 12.2.4 - and probably a lot of others

**Describe the bug**
README and values.yaml present `extraDeploy` as an option, but there's no template to render it. I see there was previously a bug similar to this for some other charts [#5041], so this might just be one that got missed.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this.
  Would you like to send a PR ?, We will be glad to review and merge it.
