### ISSUE TITLE
[bitnami/prestashop] More than 1 Replica Count in values yaml file

### ISSUE THREAD

**Issue by deeco** [bitnami/charts#6141]
Which chart:
https://github.com/bitnami/charts/tree/master/bitnami/prestashop

Describe the bug
unable to add additional replicas to values.yaml

Deployed the prestashop with helm chart on eks in GCP and have the site running , when check with kubectl command I only see 1 pod running even though ive added 3 replicas to values.yaml

replicaCount: 3

Following article https://bitnami.com/stack/prestashop/helm

To Reproduce

add replicas to value.yaml file does not apply

Version of Helm and Kubernetes:
gke v1.18
Helm 3

**Comment by setood** [comment]
work with old style: 
```yaml
statefulset:
  replicaCount: 3
```

**Comment by alemorcuq** [comment]
Hi, @deeco.

Which guide are you using? The link you shared (https://bitnami.com/stack/prestashop/helm) does not show how to add more replicas.

**Comment by deeco** [comment]
@alemorcuq  that was the question of feature I was asking about, is this possible to add more replicas to deployment via the values.yaml file ?

**Comment by deeco** [comment]
@setood is the supported ?

```
statefulset:
  replicaCount: 3
```

**Comment by alemorcuq** [comment]
How are you installing the chart, @deeco ? Are you using a Load Balancer service that requires you to run an upgrade command to finish the installation? If that's the case, keep in mind that you should also specify the replica count value to the upgrade command.

**Comment by deeco** [comment]
@alemorcuq  I am installing via helm command line 

`helm install prestashop --namespace prestashop -f values.yaml bitnami/prestashop`

**Comment by deeco** [comment]
I have tried updated the replica set after deployment , but this value always returns to 1

**Comment by alemorcuq** [comment]
When you start the chart, some information should appear with some instructions to run. Do those instructions ask you to run a `helm upgrade`? If so, that `helm upgrade` command should also have the `replicaCount` value set to 3.
