### ISSUE TITLE
Slave is unable to connect to master - Redis Chart

### ISSUE THREAD

**Issue by njaisw** [bitnami/charts#6143]
**Which chart**:
https://harbor-repo.vmware.com/harbor/projects/71/helm-charts/redis/versions/12.9.0

**Describe the bug**
Slave is crashing because it is unable to connect to the master.
1:S 16 Apr 2021 10:52:37.419 # Unable to connect to MASTER: Invalid argument
1:S 16 Apr 2021 10:52:38.421 * Connecting to MASTER tcops-redis-master-0.tcops-redis-headless.vmware-smarts.svc.cluster.local:6379
1:S 16 Apr 2021 10:52:38.424 # Unable to connect to MASTER: Invalid argument
1:S 16 Apr 2021 10:52:39.427 * Connecting to MASTER tcops-redis-master-0.tcops-redis-headless.vmware-smarts.svc.cluster.local:6379
1:S 16 Apr 2021 10:52:39.429 # Unable to connect to MASTER: Invalid argument

**To Reproduce**
1. helm repo add tac-photon https://harbor-repo.vmware.com/chartrepo/tac-photon
2. Copy the values locally  from https://harbor-repo.vmware.com/harbor/projects/71/helm-charts/redis/versions/12.9.0
and modify the value : 
volumePermissions:
  enabled: true
3.  helm install tcops-redis tac-photon/redis -f values_photon_1.yaml 
   NAME: tcops-redis
LAST DEPLOYED: Fri Apr 16 07:08:53 2021
NAMESPACE: vmware-smarts
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **
Redis(TM) can be accessed via port 6379 on the following DNS names from within your cluster:

tcops-redis-master.vmware-smarts.svc.cluster.local for read/write operations
tcops-redis-slave.vmware-smarts.svc.cluster.local for read-only operations
......
4. [clusteradmin@vmware-photon-os ~]$ kubectl get po | grep redis
tcops-redis-master-0                     1/1     Running            0          2d10h
tcops-redis-slave-0                      0/1     CrashLoopBackOff   922        2d10h

[clusteradmin@vmware-photon-os ~]$ kubectl get svc  | grep redis
tcops-redis-headless    ClusterIP   None              <none>        6379/TCP                               2d11h
tcops-redis-master      ClusterIP   192.168.243.142   <none>        6379/TCP                               2d11h
tcops-redis-slave       ClusterIP   192.168.242.11    <none>        6379/TCP                               2d11h

[clusteradmin@vmware-photon-os redis]$ kubectl logs tcops-redis-slave-0
redis 10:51:35.05 INFO  ==> ** Starting Redis **
1:C 16 Apr 2021 10:51:35.075 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 16 Apr 2021 10:51:35.075 # Redis version=6.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 16 Apr 2021 10:51:35.075 # Configuration loaded
1:S 16 Apr 2021 10:51:35.076 * Running mode=standalone, port=6379.
1:S 16 Apr 2021 10:51:35.076 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:S 16 Apr 2021 10:51:35.076 # Server initialized
1:S 16 Apr 2021 10:51:35.077 * Ready to accept connections
1:S 16 Apr 2021 10:51:35.077 * Connecting to MASTER tcops-redis-master-0.tcops-redis-headless.vmware-smarts.svc.cluster.local:6379
1:S 16 Apr 2021 10:51:35.086 # Unable to connect to MASTER: Invalid argument
    

**Expected behavior**
Slave to start properly

**Version of Helm and Kubernetes**:

- Output of `helm version`:

[clusteradmin@vmware-photon-os ~]$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

- Output of `kubectl version`:

[clusteradmin@vmware-photon-os ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17+vmware.1", GitCommit:"50b742aefffae9c8786aeb9ada99d4ff6f902ac9", GitTreeState:"clean", BuildDate:"2021-01-19T23:03:36Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17+vmware.1", GitCommit:"50b742aefffae9c8786aeb9ada99d4ff6f902ac9", GitTreeState:"clean", BuildDate:"2021-01-19T23:00:23Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by njaisw** [comment]
[clusteradmin@vmware-photon-os redis]$ kubectl get ep | grep redis
tcops-redis-headless    192.168.246.84:6379                                                           2d12h
tcops-redis-master      192.168.246.84:6379                                                           2d12h
tcops-redis-slave                                                                                     2d12h

**Comment by migruiz4** [comment]
Hi @njaisw,

Thank you for reporting this issue. Could you please run the following commands to check if the slave pods are able to connect with the master?

```
export REDIS_PASSWORD=$(kubectl get secret tcops-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
kubectl exec -it tcops-redis-slave-0 -- redis-cli -h tcops-redis-master-0.tcops-redis-headless.vmware-smarts.svc.cluster.local -p 6379 -a $REDIS_PASSWORD info
```

This should help us determine if it is a connectivity issue between pods.

Additionally, does your container have any other log after these lines, or do they repeat until the pod crashes?

```
1:S 16 Apr 2021 10:51:35.077 * Connecting to MASTER tcops-redis-master-0.tcops-redis-headless.vmware-smarts.svc.cluster.local:6379
1:S 16 Apr 2021 10:51:35.086 # Unable to connect to MASTER: Invalid argument
```

This message usually appears before the synchronization between master and slave starts, and it could be possible that the issue is happening when synchronizing and not while connecting.

**Comment by njaisw** [comment]
I could resolve the problem, the issue was cluster domain defined in values.yaml file was cluster.local but actual configured cluster domain on k8s was cluster.omega.local. I changed the values also to cluster.omega.local. It seems to be working.

**Comment by migruiz4** [comment]
Hi @njaisw,

I'm glad you were able to find a fix to this issue.
Thank you for letting us know and sharing your solution.

If you find any further issue don't hesitate to let us know.
