### ISSUE TITLE
redis sentinel masterset should not be hardcoded

### ISSUE THREAD

**Issue by tom-schoener** [bitnami/charts#6145]
**Which chart**:
bitnami/redis v12.10.1 

**Describe the bug**
You can set the sentinel masterset with `sentinel.masterSet` which defaults to `mymaster`. However, in
 https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/configmap-scripts.yaml#L313-L319 this value is hardcoded in two places, but should actually be `{{ .Values.sentinel.masterSet }}`.

**Comment by javsalgar** [comment]
Hi,

That's true, thank you for detecting the issue! As you discovered it, would you like to open a PR with the fix? If not, we will work on it.

**Comment by tom-schoener** [comment]
> Hi,
> 
> That's true, thank you for detecting the issue! As you discovered it, would you like to open a PR with the fix? If not, we will work on it.

Thanks for your reply. I'll create a PR and link it to this issue.
