### ISSUE TITLE
[bitnami/logstash] persistence storage

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#6150]
**Which chart**:
logstash

**Is your feature request related to a problem? Please describe.**
It can't store data for initial_sequence

**Describe the solution you'd like**
add a persistence storage

**Comment by alemorcuq** [comment]
Hi, @maxisam. Thanks for the suggestion. Are you interested in contributing with a PR?

**Comment by maxisam** [comment]
not at the moment, sorry.

**Comment by juan131** [comment]
Hi @maxisam 

Thanks for your feedback!

I'll share it with someone with more experienced with Logstash since I'm not familiar at all with it all. Please expect a responde regarding this topic in the following days.

**Comment by maxisam** [comment]
You're welcome. I love most of the chart bitnami provides. Keeps up the good work!

**Comment by migruiz4** [comment]
Hi @maxisam,

Sorry for the late response.

Following up on this, we are working on adding support to persist the Logstash data directory to both the Logstash image and the chart. 

I expect it to be ready in the following days, I will let you know when a new version of the chart including this feature is released. Thank you very much for your suggestion!
