### ISSUE TITLE
[bitnami/redis-cluster] initJob podAnnotations to disable istio sidecar injection

### ISSUE THREAD

**Issue by jasonatball** [bitnami/charts#6151]
**Which chart**:
redis-cluster: 4.2.5

**Describe the bug**
Documentation is incorrect in values.yaml at https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/values.yaml#L300 to disable istio sidecar injection.

I believe it should be ```podAnnotations```:
```
  initJob:
    podAnnotations:
      sidecar.istio.io/inject: "false"
```

**Comment by Mauraza** [comment]
Hi @jasonatball,

I checked the Istio documentation and it appears in annotations https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/. Maybe we missed something, could you add a link to the Istio documentation about this o something similar?

**Comment by jasonatball** [comment]
The annotation needs to be the ```spec.template.metadata.annotations``` section. When I look at the [init-cluster](https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/init-cluster.yaml) template there are two annotation sections. The one at the top ```metadata.annotations``` uses the ```.Values.initJob.annotations```. The one under ```spec.template.metadata.annotations``` uses ```.Values.initJob.podAnnotations```. Thus to match the istio documentation we need to set the ```initJob.podAnnotations```.

**Comment by jasonatball** [comment]
Also I tried both and podAnnotations works while simply annotations does not. :-)

**Comment by Mauraza** [comment]
I just create a PR to fix the documentation.
