### ISSUE TITLE
Ingress documentation link in the wordpress chart readme is broken

### ISSUE THREAD

**Issue by WoLpH** [bitnami/charts#6162]
**Which chart**:
wordpress: master, currently: c7b389f

**Describe the bug**

The link `Learn more about configuring and using Ingress.` is broken: https://github.com/bitnami/charts/tree/master/bitnami/wordpress/#ingress

**To Reproduce**

1. Go to https://github.com/bitnami/charts/tree/master/bitnami/wordpress/#ingress
2. Click on `Learn more about configuring and using Ingress.`
3. See error

**Expected behavior**

A working documentation page

I can't seem to find it in the docs anywhere: https://docs.bitnami.com/search/?in=general&a=wordpress&q=ingres

**Comment by carrodher** [comment]
Thanks for letting us know, we will fix it.

**Comment by WoLpH** [comment]
Thank you for the quick fix!
