### ISSUE TITLE
[bitnami/rabbitmq]How to set RabbitMQ password from external secret?

### ISSUE THREAD

**Issue by acidos** [bitnami/charts#6163]
The rabbit helm chart documentation says that if I configure
``` 
     auth:
        existingPasswordSecret
        existingErlangSecret
```
then rabbit will pick up these secrets from existing resources. This actually works until I enable loadDefinition in order to pre-configure virtual hosts upon chart installation:
```
    extraSecrets:
      load-definition:
        load_definition.json: |
          {
            "users": [
              {
                "name": "user",
                "tags": "administrator"
              }
            ],
            "vhosts": [
                {
                    "name": "development"
                },
                {
                    "name": "staging"
                },
                {
                    "name": "/"
                }
            ],
            "permissions": [
                {
                    "user": "user",
                    "vhost": "development",
                    "configure": ".*",
                    "write": ".*",
                    "read": ".*"
                },
                {
                    "user": "user",
                    "vhost": "/",
                    "configure": ".*",
                    "write": ".*",
                    "read": ".*"
                },
                {
                    "user": "user",
                    "vhost": "staging",
                    "configure": ".*",
                    "write": ".*",
                    "read": ".*"
                }
            ],
```

After enabling rabbit is not using password from external secret and password is empty.
My question - how can I still use existing secret for defining password AND preconfigure 
vhosts, permissions, etc? Is existing secret usage compatible with load_definition?

I've also tried to remove "users" block from definition, but then rabbit is crashing right after installation.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but the current logic does not allow that, you can take a took to [these lines](https://github.com/bitnami/charts/blob/c7b389f161c95ef64257e008ad1e9903007e7180/bitnami/rabbitmq/templates/statefulset.yaml#L169). If you provide the definitions the user password is not read from the secret.
