### ISSUE TITLE
[bitnami/mongodb] Configuring a GUI to manage data in MongoDB via the Helm chart

### ISSUE THREAD

**Issue by SellamiRami** [bitnami/charts#6168]
**Which chart**:
The MongoDB Helm Chart (V10.11.1)
**Is your feature request related to a problem? Please describe.**
I want to configure and install a GUI (for example MongoDB Compass, Adminer, etc.) with MongoDB in order to be able to easily manage my data. I tried to install Adminer. However, Adminer rises an error when it comes to connect new users. I didn't find a helm chart to install MongoDB Compass.

**Describe the solution you'd like**
A helm chart for a GUI-based solution to manage data in a MongoDB database.

**Describe alternatives you've considered**
I've tried to set up Adminer which has some limitations with MangoDB.

**Comment by javsalgar** [comment]
Hi!

Thanks for the feedback! I will forward this request for evaluation. If we decide to implement a solution for MongoDB Compass, we will let you know

**Comment by SellamiRami** [comment]
Hello @javsalgar thank you for your reply :)

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
