### ISSUE TITLE
[bitnami/metrics-server] - bump app version to v0.4.3

### ISSUE THREAD

**Issue by Constantin07** [bitnami/charts#6176]
**Which chart**:
metrics-server v0.4.2

**Is your feature request related to a problem? Please describe.**
See release notes here https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.4.3

**Describe the solution you'd like**
Upgrade metrics-server to v0.4.3

**Describe alternatives you've considered**
Not using Bitnami helm charts.

**Additional context**
None.

**Comment by alvneiayu** [comment]
hi @Constantin07 

Thanks for your message. A new version of the chart is already published.
Version 5.8.5 includes metrics-server 0.4.3.

BR

Álvaro

**Comment by Constantin07** [comment]
thanks @alvneiayu
