### ISSUE TITLE
MetalLB speaker not up to date

### ISSUE THREAD

**Issue by champtar** [bitnami/charts#6180]
**Which chart**:
bitnami metallb 2.3.4

**Describe the bug**
controller version is 0.9.6
https://github.com/bitnami/charts/commit/5f90e27c8492198eea027194aba577f71bf5505b#diff-906ddc6bdf654346f7098ef7e8ec91468e7eaf529285d370362168a1abbb20adR88
speaker version is 0.9.5
https://github.com/bitnami/charts/commit/5f90e27c8492198eea027194aba577f71bf5505b#diff-906ddc6bdf654346f7098ef7e8ec91468e7eaf529285d370362168a1abbb20adR274

**To Reproduce**

**Expected behavior**
controller and speaker components are always at the same revision

**Version of Helm and Kubernetes**:

**Additional context**
This already happened in the past: https://github.com/bitnami/charts/commit/33521594e39bb59a48e9c00f6cfa473544c23a72#r43423375

**Comment by carrodher** [comment]
Thanks for letting us know, I just trigger a new release of the chart fixing the issue, see https://github.com/bitnami/charts/commit/cbfed08075a84d7c6a9723c2e2c66bfa199c755d
