### ISSUE TITLE
What is the purpose for having the /cache-state

### ISSUE THREAD

**Issue by HuangYejing** [bitnami/charts#6183]
Hi 
The documentation describe that if we use 'architecture:"high-availability"', images will stores the cache-state at '/cache-state' path.
I might have a question what does the 'cache-state' here mean and what exactly will be save in that path? will it save the key value in the /cache-state filesystem instead of memory? will data for key and value in memcached doesn't lose if we set the '/cache-state'?

Thank you in advance

**Comment by alvneiayu** [comment]
hi @HuangYejing 

This is a feature added from the community. I investigated a little bit and enabling:

```
'architecture:"high-availability"
persistence.enabled=true
```

You are going to enable the "Restartable Cache"

```
memcached --help
...
-e, --memory-file=<file>  (EXPERIMENTAL) mmap a file for item memory.
                          use only in ram disks or persistent memory mounts!
                          enables restartable cache (stop with SIGUSR1)
...
```
Here you can find an article explaining the "Restartable Cache". Maybe the article can help you to find some answers to your questions.

https://memcached.org/blog/persistent-memory/

Indeed, we are using memcached as an binary from this project. I suggest you to visit the mailing list in the project, maybe you can find more information about it. Link of the mailing list [here
](https://groups.google.com/g/memcached)

Sorry and thanks for your time.

Álvaro

**Comment by HuangYejing** [comment]
Hi Álvaro
thanks for your answer
