### ISSUE TITLE
Hi! Any tutorial about running airflow without git repo instead of a mounted volume that can be manipulated by user directly(locally on k8s node)?

### ISSUE THREAD

**Issue by bugzyz** [bitnami/charts#6186]

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure what you need, but you can get into the pod by running `kubectl exec -it <name-of-the-pod> bash` and manipulate it.

**Comment by bugzyz** [comment]
@rafariossaa Thanks! Sorry for not having a clear question. Let me elaborate the detail of my question.

We got a requirement that: 
first, we have a k8s cluster, contains 1 master, 3 worker vms
second, there's a NFS folder contains several dag files that is a PV in our k8s cluster.

And, our requirement is that, we want that airflow service to consume the dags in the NFS PV.
So, my question is that. does this charts support those scenario like this without modifying the charts now? Or user can provide their well-configured values.yaml and easily make airflow created by this charts work?

For a workaround, of course user can login to the airflow container, and manipulate the dags folder, which I think this is the way that you mentioned in you previous comment. But I think, this may not be a nice way to do that since it's too troublesome.

**Comment by rafariossaa** [comment]
Hi,
  Could you take a to to the `xxxx.extraVolumeMounts` and `xxxx.extraVolumes` ?  Maybe that works for your use case.

**Comment by bugzyz** [comment]
@rafariossaa Thanks! Got your point. Is it OK for us to mount an external volume and configure the dags path through `configurationConfigMap` configuration in vlaues.yaml? Or there's an easier way to do so?

**Comment by rafariossaa** [comment]
Hi,
  I think yes, it is a good way to use it.

**Comment by bugzyz** [comment]
thank you！

**Comment by rafariossaa** [comment]
You are welcome.
