### ISSUE TITLE
Airflow DAG Logs Not Showing in the UI or Log Directory 

### ISSUE THREAD

**Issue by ecda909** [bitnami/charts#6194]
**Which chart**:
airflow:8.2.3 (CeleryExecutor)

**Describe the bug**
Logs are not showing in the UI or the pod. The path in the pod I've been checking for logs is /opt/bitnami/airflow/logs/scheduler/latest/dags and /opt/bitnami/airflow/logs/scheduler/<date>/dags. While there are logs within these directories, none are specific to the Python in the DAG's that were run. instead they show common logs for scheduling the tasks like so...

```
[2021-04-22 19:16:37,288] {scheduler_job.py:182} INFO - Started process (PID=2620) to work on /opt/bitnami/airflow/dags/dags/s3_sensor.py
[2021-04-22 19:16:37,289] {scheduler_job.py:629} INFO - Processing file /opt/bitnami/airflow/dags/dags/s3_sensor.py for tasks to queue
[2021-04-22 19:16:37,290] {logging_mixin.py:104} INFO - [2021-04-22 19:16:37,290] {dagbag.py:448} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/dags/s3_sensor.py
[2021-04-22 19:16:37,577] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['s3_dag_test']) retrieved from /opt/bitnami/airflow/dags/dags/s3_sensor.py
[2021-04-22 19:16:37,669] {logging_mixin.py:104} INFO - [2021-04-22 19:16:37,669] {dag.py:1818} INFO - Sync 1 DAGs
[2021-04-22 19:16:37,680] {logging_mixin.py:104} INFO - [2021-04-22 19:16:37,680] {dag.py:2273} INFO - Setting next_dagrun for s3_dag_test to None
[2021-04-22 19:16:37,686] {scheduler_job.py:190} INFO - Processing /opt/bitnami/airflow/dags/dags/s3_sensor.py took 0.401 seconds
```

UI Logs Display...

```
*** Log file does not exist: /opt/bitnami/airflow/logs/s3_dag_test/check_s3_for_file_in_s3/2021-04-22T18:56:50.228272+00:00/2.log
*** Fetching from: http://:8793/log/s3_dag_test/check_s3_for_file_in_s3/2021-04-22T18:56:50.228272+00:00/2.log
*** Failed to fetch log file from worker. Invalid URL 'http://:8793/log/s3_dag_test/check_s3_for_file_in_s3/2021-04-22T18:56:50.228272+00:00/2.log': No host supplied
```

I have upgraded the resource request and limit to these specs for scheduler and worker...
```
   limits:
      cpu: 300m
      memory: 1Gi
    requests:
      memory: 300Mi
      cpu: 300m
```

**To Reproduce**

1. Run the bitnami Airflow Helm deployment and configure the values like so...
Configure bitnami HELM deployment with CeleryExecutor and deploy using the image...

```
image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.0.1-debian-10-r37
```

and the limit/requests:

```
limits:
      cpu: 300m
      memory: 1Gi
    requests:
      memory: 300Mi
      cpu: 300m
```
[values.yaml.zip](https://github.com/bitnami/charts/files/6360888/values.yaml.zip)

**Expected behavior**
Error logs specific to DAG's need to be shown within the UI. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @ecda909 ,
I see you are getting:
```
*** Log file does not exist: /opt/bitnami/airflow/logs/s3_dag_test/check_s3_for_file_in_s3/2021-04-22T18:56:50.228272+00:00/2.log
```

I am not sure if that file should be created by the airflow worker itself. Does the folder `/opt/bitnami/airflow/logs/s3_dag_test/check_s3_for_file_in_s3` exist? Could you try creating it manually in case it does not exist?

**Comment by ecda909** [comment]
Hi @miguelaeh I have created the directory inside of the scheduler, but it is still not populating with logs. I think it should be populated automatically? But I'm new to Airflow so I don't really know?

<img width="1920" alt="Screen Shot 2021-04-23 at 10 58 24 AM" src="https://user-images.githubusercontent.com/20650573/115890336-d556a200-a422-11eb-81e7-f0043c1a9cbc.png">
<img width="905" alt="Screen Shot 2021-04-23 at 10 58 36 AM" src="https://user-images.githubusercontent.com/20650573/115890355-dab3ec80-a422-11eb-97f1-01849244a2f1.png">

**Comment by juan131** [comment]
Hi @ecda909 

It looks like the UI is trying to fetch the log file from the worker, so the 1st thing I would check is whether the log is actually in the **worker** container or not (it seems you were looking for it in the scheduler one).

Could you please connect to the worker container and look for `*.log` files in it?

**Comment by ecda909** [comment]
Hi @juan131  I’ve checked on the worker and did not see the log file there. I also tried creating the directory there and that didn’t work to have the log file generated.

**Comment by juan131** [comment]
Hi @ecda909 

What command did you use to look for the log file @ecda909 ? Did you run sth like tike this?

```console
$ find /opt/bitnami/airflow -name *.log
```

According to [Airflow docs](https://airflow.apache.org/docs/apache-airflow/2.0.0/logging-monitoring/logging-tasks.html#logging-for-tasks) the log directory can be customized setting the `base_log_folder` property. You can try running the command below in the Airflow worker to obtain more information about the logging properties:

```
$ airflow info
$ airflow config list
```

**Comment by ecda909** [comment]
The command returns no log files... and the log files path is /opt/bitnami/airflow/logs, but there are only scheduler logs there...

<img width="526" alt="Screen Shot 2021-04-27 at 4 11 33 PM" src="https://user-images.githubusercontent.com/20650573/116306580-3cea5580-a773-11eb-8a2d-2cb08f857e5b.png">

<img width="747" alt="Screen Shot 2021-04-27 at 4 10 58 PM" src="https://user-images.githubusercontent.com/20650573/116306518-280dc200-a773-11eb-9ba0-dc2b2cec8c75.png">

<img width="774" alt="Screen Shot 2021-04-27 at 4 10 00 PM" src="https://user-images.githubusercontent.com/20650573/116306415-06143f80-a773-11eb-8f66-c1e888b40aeb.png">

**Comment by ecda909** [comment]
<img width="1041" alt="Screen Shot 2021-04-27 at 4 12 53 PM" src="https://user-images.githubusercontent.com/20650573/116306720-6dca8a80-a773-11eb-99fb-f01827d47992.png">

**Comment by juan131** [comment]
Hi @ecda909 

I wonder if the issue is that the directory `/opt/bitnami/airflow/logs/dag_processor_manager` doesn't exist and it's unable to write logs there. Could you try to manually create the directory, and give write permissions on it? Just follow these commands inside the worker:

```bash
mkdir -p /opt/bitnami/airflow/logs/dag_processor_manager
chmod -R g+rwX /opt/bitnami/airflow/logs/
```

**Comment by ecda909** [comment]
This is what I see after making those changes. Doesn't seem to have worked...

<img width="734" alt="Screen Shot 2021-04-28 at 9 54 13 AM" src="https://user-images.githubusercontent.com/20650573/116415747-b16ed400-a807-11eb-8ffc-8f15b93c7b96.png">
<img width="1920" alt="Screen Shot 2021-04-28 at 9 56 44 AM" src="https://user-images.githubusercontent.com/20650573/116416091-0d395d00-a808-11eb-9c6f-f7527334a327.png">
<img width="673" alt="Screen Shot 2021-04-28 at 9 57 13 AM" src="https://user-images.githubusercontent.com/20650573/116416149-1cb8a600-a808-11eb-8702-1c9f5f438a48.png">

**Comment by juan131** [comment]
Hi @ecda909 

I'd like to reproduce the same scenario on my own cluster. I saw in your **values.yaml** that you're mounting your custom DAGs in the scheduler (by the way there are other ways to add your dags see [this section](https://github.com/bitnami/charts/tree/master/bitnami/airflow#load-dag-files)):

```yaml
scheduler:
  extraVolumes:
    - name: dags
      hostPath:
        path: "/Users/edermazariegos/Public/apache/airflow/bitnami-helm-celery"
```

Could you share with me (if possible) the DAGs you're mounting so I can give it a try?

**Comment by ecda909** [comment]
Yeah, sure!

`"""
S3 Sensor Connection Test
"""
import logging
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.operators.email_operator import EmailOperator
from datetime import datetime, timedelta
from airflow.sensors.s3_key_sensor import S3KeySensor

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2016, 11, 1),
    'email': ['<email>'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 5,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG('s3_dag_test', default_args=default_args, schedule_interval= '@once')

t1 = BashOperator(
    task_id='bash_test',
    bash_command='echo "hello, it should work" > s3_conn_test.txt',
    dag=dag)

sensor = S3KeySensor(
    task_id='check_s3_for_file_in_s3',
    bucket_key='*',
    wildcard_match=True,
    bucket_name='eders-portfolio',
    aws_conn_id='s3_connection',
    timeout=18*60*60,
    poke_interval=120,
    dag=dag)

t1.set_upstream(sensor)
`

**Comment by juan131** [comment]
Hi @ecda909 

I am unable to reproduce the issue.

- I installed Airflow using the values.yaml below:

```yaml
dagsConfigMap: custom-dags
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-dags
    data:
      s3dag.py: |
        import logging
        from airflow import DAG
        from airflow.operators.bash_operator import BashOperator
        from airflow.operators.email_operator import EmailOperator
        from datetime import datetime, timedelta
        from airflow.sensors.s3_key_sensor import S3KeySensor

        default_args = {
            'owner': 'airflow',
            'depends_on_past': False,
            'start_date': datetime(2016, 11, 1),
            'email': ['<email>'],
            'email_on_failure': False,
            'email_on_retry': False,
            'retries': 5,
            'retry_delay': timedelta(minutes=5)
        }

        dag = DAG('s3_dag_test', default_args=default_args, schedule_interval= '@once')

        t1 = BashOperator(
            task_id='bash_test',
            bash_command='echo "hello, it should work" > s3_conn_test.txt',
            dag=dag)

        sensor = S3KeySensor(
            task_id='check_s3_for_file_in_s3',
            bucket_key='*',
            wildcard_match=True,
            bucket_name='eders-portfolio',
            aws_conn_id='s3_connection',
            timeout=18*60*60,
            poke_interval=120,
            dag=dag)

        t1.set_upstream(sensor)
```

- Once Airflow was ready, I accessed the UI and trigger the "s3_dag_test" DAG. 
- After that, I accessed the worker pod:

```console
$ kubectl exec -it airflow-worker-0 -- bash
```

- And look fo the logs:

```console
$ $ ls -la /opt/bitnami/airflow/logs/s3_dag_test/check_s3_for_file_in_s3/
total 16
drwxr-xr-x 4 1001 root 4096 May  6 09:27 .
drwxr-xr-x 3 1001 root 4096 May  6 09:27 ..
drwxr-xr-x 2 1001 root 4096 May  6 09:32 2016-11-01T00:00:00+00:00
drwxr-xr-x 2 1001 root 4096 May  6 09:32 2021-05-06T09:26:20.587601+00:00
$ ls -la /opt/bitnami/airflow/logs/s3_dag_test/check_s3_for_file_in_s3/2021-05-06T09:26:20.587601+00:00
total 24
drwxr-xr-x 2 1001 root 4096 May  6 09:32 .
drwxr-xr-x 4 1001 root 4096 May  6 09:27 ..
-rw-rw-rw- 1 1001 root 7574 May  6 09:27 1.log
-rw-rw-rw- 1 1001 root 7574 May  6 09:32 2.log
```

- As you can see the logs were there
