### ISSUE TITLE
[bitnami/postgresql-ha] postgresql.extendedConf requires volumePermissions.enabled to work properly 

### ISSUE THREAD

**Issue by Librazy** [bitnami/charts#6197]
**Which chart**:
- name: postgresql-ha
  repository: https://charts.bitnami.com/bitnami
  version: 6.9.0

**Describe the bug**
This is a regression of #1961
While #2140 fixed #1961, initContainers init-chmod-data requires volumePermissions.enabled to be truly, see https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L73 . But this behavior is nether documented nor corrected in the chart. 

**To Reproduce**

Deploy postgresql-ha with non-empty postgresql.extendedConf and volumePermissions.enabled=false, and monitor the -postgresql-ha-postgresql-0 pod. It will crash with the same error in #1961 .

**Expected behavior**

postgresql.conf file generates correctly in the first run.

**Version of Helm and Kubernetes**:

<details>

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
N/A
</details>

**Comment by miguelaeh** [comment]
Hi @Librazy ,
Not sure if that's an actual issue or just a documentation lack. Setting the `volumePermissions.enabled` it should work, doesn't it?

**Comment by Librazy** [comment]
Yes it works if `volumePermissions.enabled=true`. I'd suggest two approach to address this issue:

1. Document that `volumePermissions.enabled` is required when using `postgresql.extendedConf`
2. Modify the chart to enable the init container `init-chmod-data` when `postgresql.extendedConf` is not empty or `volumePermissions.enabled` is truly.

Personally I'm in favor of the second one so that setting `postgresql.extendedConf` just works.

**Comment by miguelaeh** [comment]
Thank you very much for the PR, we will take care of it
