### ISSUE TITLE
Thanos compactor creates duplicate deployment

### ISSUE THREAD

**Issue by ekhaydarov** [bitnami/charts#6199]
**Which chart**:
bitnami/thanos  3.15.0

**Describe the bug**
When updating a chart and making a change to the compactor, you will then create a second pod in deployment. IF you look at the yaml of the deployment it states replicas = 1 but the kube status is 1/2 for the deployment. Scaling up and down does not resolve the issue it seems

**To Reproduce**
Steps to reproduce the behavior: create a thanos chart with compactor enabled. update compactor yaml and redeploy. check the deployment it should be 1/2 available pods not 1/1

**Expected behavior**
An update to compactor chart should not introduce and pod and make the previous pod undeletable

**Version of Helm and Kubernetes**: helm 3.4.2 kubernetes 1.20.2

**Comment by rafariossaa** [comment]
Hi,
  Could you provide how did you deploy the chart?
  Is there any errors in the logs ?

**Comment by ekhaydarov** [comment]
Hi, thanks for response.
The chart is deployed through helm. There are no errors in the logs, or any indication that something is different when deploying.

**Comment by rafariossaa** [comment]
Which change you did when updating the compactor ?
could you send the pods, deployment status before and after the upgrade ?

**Comment by ekhaydarov** [comment]
it seemed to be a transient error on the storegateway statefulset. we scaled it to 0 and left it overnight and it managed to sort itself out somehow. can chalk it up to weird sts behaviour

**Comment by rafariossaa** [comment]
Hi,
  Thanks for letting us know.
  Don't hesitate to reopen it if the issue appears again.
