### ISSUE TITLE
EXTERNAL-IP pending for contour

### ISSUE THREAD

**Issue by huangyingw** [bitnami/charts#6209]
**Which chart**:
contour

**Describe the bug**
I install contour from source with following command:

```
cd ./contour
helm dependency update ./
helm install contour ./
```

But the EXTERNAL-IP section is pending for 7m19s

```
kubectl get svc contour-envoy --namespace default
NAME            TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
contour-envoy   LoadBalancer   10.100.202.157   <pending>     80:31222/TCP,443:32409/TCP   7m19s
```

**Expected behavior**
get an EXTERNAL-IP.

**Version of Helm and Kubernetes**:
My kubernetes is a single-node cluster on my bare-metal
kubectl taint nodes --all node-role.kubernetes.io/master-

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"20
21-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"20
21-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

It seems that you are using a bare-metal cluster. Did you configure an external IP provider such as MetalLB?

**Comment by huangyingw** [comment]
> Hi,
> 
> It seems that you are using a bare-metal cluster. Did you configure an external IP provider such as MetalLB?
how to 
````
configure an external IP provider such as MetalLB
````?
it is a physical machine at my home, with a dhcp IP address, like 192.168.1.8 from my wifi router.

**Comment by javsalgar** [comment]
My advice would be to check with the MetalLB devs to configure LoadBalancer IPs for your case. https://metallb.universe.tf/installation/

About Contour itself, did you see any issue in the pods?

**Comment by huangyingw** [comment]
> My advice would be to check with the MetalLB devs to configure LoadBalancer IPs for your case. https://metallb.universe.tf/installation/
> 
> About Contour itself, did you see any issue in the pods?

I don't see any issue in the pods.
thanks for your info, I am trying with MetalLB

**Comment by huangyingw** [comment]
great thanks, after installing and configuring the MetalLB, this chart works at my local cluster.

**Comment by javsalgar** [comment]
Great to know!!
