### ISSUE TITLE
[bitnami/elasticsearch] How to use x-pack v15+ of the chart?

### ISSUE THREAD

**Issue by omardoma** [bitnami/charts#6211]
**Which chart**:
ElasticSearch v15

**Is your feature request related to a problem? Please describe.**
Now that x-pack is supported and installed by default in both the Bitnami ElasticSearch Docker image and Bitnami ElasticSearch chart, I can't really find any references or figure out how to use it to enable authentication in both ElasticSearch and the Kibana sub-chart. I know it is mentioned that we should follow the official ES guide for that, but there is no clear way to know how it can be integrated with this chart.

**Describe the solution you'd like**
Improved docs or an example configuration that we can take as reference.

**Describe alternatives you've considered**
The only alternative I can see is to not use Bitnami's chart and use ElasticSearch's, but I would really like to use Bitnami's.

**Comment by marcosbc** [comment]
Hi @omardoma, we are currently working on implementing X-Pack security in #6010. Unfortunately I can't give an ETA for when it's going to be merged.

**Comment by omardoma** [comment]
@marcosbc Thanks a lot for the info, good to know that its being worked on, will the PR also cover authentication for Kibana and metrics?

**Comment by marcosbc** [comment]
Hi @omardoma, I assume that metrics will be included in the PR, but I will add a comment just in case. As for Kibana, it should be handled in #6014. I will add a comment there as well. If you find any other thing that you think may be missing, feel free to add a comment in the respective PR. Thanks!
