### ISSUE TITLE
[bitnami/airflow] hostAliases ignored for worker

### ISSUE THREAD

**Issue by kohonen** [bitnami/charts#6212]
it seems that the hostAliases section in values.yaml doesn't work for the airflow workers. i can't see any entries in either /etc/hosts file inside the pod or in the pod specifications. 
hostAliases works for scheduler and web though. so i guess there is something wrong in the helm worker template configuration?

**Comment by carrodher** [comment]
Thanks for letting us know, I was taking a look but the code seems similar in the different cases, so it is really weird it works in some pods but not in others:
```console
$ ag 'hostAliases' -C 1 templates
templates/worker/statefulset.yaml
45:      {{- if .Values.worker.hostAliases }}
46:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.worker.hostAliases "context" $) | nindent 8 }}
47-      {{- end }}

templates/metrics/deployment.yaml
29:      {{- if .Values.metrics.hostAliases }}
30:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.hostAliases "context" $) | nindent 8 }}
31-      {{- end }}

templates/web/deployment.yaml
32:      {{- if .Values.web.hostAliases }}
33:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.web.hostAliases "context" $) | nindent 8 }}
34-      {{- end }}

templates/scheduler/deployment.yaml
33:      {{- if .Values.scheduler.hostAliases }}
34:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.hostAliases "context" $) | nindent 8 }}
35-      {{- end }}
```

Are you able to see any difference that I am missing? Are you deploying the chart with any custom parameters?

**Comment by kohonen** [comment]
> Thanks for letting us know, I was taking a look but the code seems similar in the different cases, so it is really weird it works in some pods but not in others:
> 
> ```
> $ ag 'hostAliases' -C 1 templates
> templates/worker/statefulset.yaml
> 45:      {{- if .Values.worker.hostAliases }}
> 46:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.worker.hostAliases "context" $) | nindent 8 }}
> 47-      {{- end }}
> 
> templates/metrics/deployment.yaml
> 29:      {{- if .Values.metrics.hostAliases }}
> 30:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.hostAliases "context" $) | nindent 8 }}
> 31-      {{- end }}
> 
> templates/web/deployment.yaml
> 32:      {{- if .Values.web.hostAliases }}
> 33:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.web.hostAliases "context" $) | nindent 8 }}
> 34-      {{- end }}
> 
> templates/scheduler/deployment.yaml
> 33:      {{- if .Values.scheduler.hostAliases }}
> 34:      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.hostAliases "context" $) | nindent 8 }}
> 35-      {{- end }}
> ```
> 
> Are you able to see any difference that I am missing? Are you deploying the chart with any custom parameters?

custom parameters - not really, just simple kubernetesexecutor with git-sync 

only difference i could find (also visible in your output) is that the airflow worker kubernetes type is statefulset, whereas the others are deployment

**Comment by kohonen** [comment]
i just realized that the very first line in worker/statefulset.yaml says

`{{- if eq .Values.executor "CeleryExecutor" }}`

does it mean the entire file is not applicable in case of kubernetesexecutor? if yes, what do we need in order to have a working hostaliases in the worker pods?
thanks

**Comment by carrodher** [comment]
In the end, workers execute `Celery` to launch tasks, so it is used when configured with `CeleryExecutor`. On the other hand, `KubernetesExecutor` launch tas in kubernetes pods.

In the case of the Helm Chart configuration, as you rightly said, the templates under the `worker/` dir are only executed when the selected executor is `CeleryExecutor`.

You can find more information about the different executors in the following link https://github.com/bitnami/charts/tree/master/bitnami/airflow#executors

**Comment by kohonen** [comment]
> In the end, workers execute `Celery` to launch tasks, so it is used when configured with `CeleryExecutor`. On the other hand, `KubernetesExecutor` launch tas in kubernetes pods.
> 
> In the case of the Helm Chart configuration, as you rightly said, the templates under the `worker/` dir are only executed when the selected executor is `CeleryExecutor`.
> 
> You can find more information about the different executors in the following link https://github.com/bitnami/charts/tree/master/bitnami/airflow#executors

thanks for the explanation, i understand the theory, but how can we now achieve to have a working hostaliases setup in the kubernetesexecutor worker pods?

**Comment by carrodher** [comment]
There is a `scheduler.hostAliases` value that is applied to the deployment when `KubernetesExecutor` is set, see https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/scheduler/deployment.yaml#L34

I am not sure if it is going to be propagated to the workers deployed by the scheduler, do you have any idea about this @javsalgar?

**Comment by kohonen** [comment]
> There is a `scheduler.hostAliases` value that is applied to the deployment when `KubernetesExecutor` is set, see https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/scheduler/deployment.yaml#L34
> 
> I am not sure if it is going to be propagated to the workers deployed by the scheduler, do you have any idea about this @javsalgar?

it is most likely not being propagated to workers, since `scheduler.hostAliases` is configured in our `values.yaml` file. 
scheduler itself does contain the records in `/etc/hosts` file, but the workers don't.

**Comment by javsalgar** [comment]
I don't think that the workers would inherit the hostAliases. That would be need to be configured in the scheduler settings, but I don't know if it supports adding hostAliases to the deployed pods.
