### ISSUE TITLE
[bitnami/mongodb] the headless service is connecting to secondary node

### ISSUE THREAD

**Issue by theaayushanand** [bitnami/charts#6213]
Hello,
After i install the bitnami/mongodb chart , i am trying to connect to the master replica using the service from within the cluster . but the service is taking me to a secondary replica instead. how can i get connection string for the primary replica from the chart deployment ? or is there a way i can make the service point to the primary node instead ?
Thanks in advance

**Comment by rafariossaa** [comment]
Hi,
  Could you share how did you deploy it and how are you trying to connect to it ?

**Comment by rafariossaa** [comment]
Hi,
  Please don't hesitate to reopen this issue if needed.
