### ISSUE TITLE
[bitnami/wordpress] Conflict between customHTAccess and allowOverrideNone

### ISSUE THREAD

**Issue by ondrejpolach** [bitnami/charts#6215]
**Which chart**:
Wordpress latest chart

**Describe the bug**
There is conflict in customHTAccess and allowOverrideNone. I need use custom HTAccess from configmap. In values.yaml file for property customHTAccessCM is "ConfigMap with custom wordpress-htaccess.conf file (requires allowOverrideNone to true)". When I set allowOverrideNone to true, validation error occured: 

wordpress: customHTAccessCM
    You are trying to use custom htaccess rules but Apache was configured
    to prohibit overriding directives with htaccess files. To use this feature,
    allow overriding Apache directives (--set allowOverrideNone=false).

If I set to false, chart does not set volume for configmap.

**To Reproduce**

1. Set allowOverrideNone to true
2. Create Configmap for custom HTAccess
3. Set customHTAccessCM to name of config map
4. Helm install/upgrade

**Expected behavior**
Wordpress will use configmap volume with custom htaccess

**Version of Helm and Kubernetes**: 
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", 
Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by ondrejpolach** [comment]
I think that [this commit](https://github.com/bitnami/charts/commit/e89085368fcd6ea6bb84ea4f9ae7ef3409ab610c) contains source of this bug - added validation for customHTAccess and allowOverrideNone.

**Comment by miguelaeh** [comment]
Hi @ondrejpolach ,
It seems that the validation is correct and helps to prevent unexpected behaviors. Setting both `allowOverride` to `None` and `customHtaccess` will end in the `customHtaccess` not taking effect since it is not allowed to be overridden.
I think you will need to change your configuration to make it correct instead.

**Comment by ondrejpolach** [comment]
Hi @miguelaeh,
I understand, but in values.yaml example on line 185 is customHTAccessCM with description that for activate config map with custom htaccess you must set allowOverrideNone to true. And validation deny this setting. In previous version of chart it is working. 
Question is, how use custom htaccess in latest version of chart?

**Comment by miguelaeh** [comment]
Hi @ondrejpolach ,
The above PR should be fixing the comment. Thank you very much for reporting!

**Comment by ondrejpolach** [comment]
You're welcome @miguelaeh. 
Hovewer, check templates/deployment.yaml on line 224. When set allowOverrideNone to false, validation pass but config map will not be mounted. Right? How use custom ht access now?

Thanks

**Comment by miguelaeh** [comment]
Hi @ondrejpolach ,
You are right I thought it was only the docs, but the logic was also inverted. The above PR should be fixing it.
Thank you very much.
