### ISSUE TITLE
[bitnami/postgresql] Ability to specify multiple users and databases when installing

### ISSUE THREAD

**Issue by nodesocket** [bitnami/charts#6218]
**Which chart**:
postgres version 10.3.18

**Is your feature request related to a problem? Please describe.**
Is it possible to bootstrap a database with two user password combinations and databases? For example I am looking to create:

User: `acme-inc` `somepasswordhere`
User: `fusionauth` `someotherpasswordhere`

Database: `acme-inc` which user `acme-inc` has full access to.
Database: `fusionauth` which user `fusionauth` has full access to.

**Comment by Mauraza** [comment]
Hi @nodesocket,

You can use a script or a configMap, please check this https://github.com/bitnami/charts/tree/master/bitnami/postgresql#initialize-a-fresh-instance?.

**Comment by nodesocket** [comment]
@Mauraza thanks for the reply. I did see that documentation, but was not able to find an example of using `initdbScriptsConfigMap`.

Can I just use `cli` commands like:

```
CREATE USER johndoe WITH PASSWORD 'supersecure';
createdb foobar -O johndoe
```

Would you be able ro provide an example of using `initdbScriptsConfigMap`?

**Comment by Mauraza** [comment]
Hi @nodesocket,

you can use something similar to this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
data:
  script.sql: |
     CREATE USER johndoe WITH PASSWORD 'supersecure';
     CREATE DATABASE foobar -O johndoe
```

**Comment by nodesocket** [comment]
Thanks @Mauraza the following worked:

```
{{- $def := index .Values "default" -}}
{{ if .Values.postgresql.initdbScriptsConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
data:
  init.sql: |
     CREATE USER johndoe WITH PASSWORD '{{ $def.POSTGRESQL_PASSWORD }}';
     CREATE DATABASE foobar WITH OWNER johndoe;
{{- end }}
```

**Comment by JoshuaSmeda** [comment]
No need to edit the template directly.

You can pass your requirement directly into the Helm chart, something like this:

```
primary:
  persistence:
    enabled: false
  initdb:
    scripts:
      00_init_database.sql: |
        CREATE USER johndoe WITH PASSWORD 'supersecure';
        CREATE DATABASE foobar OWNER johndoe;
```

Which translates to the following log, indicating success:

```
postgresql 10:06:38.26 DEBUG ==> Executing /docker-entrypoint-initdb.d/..2024_10_08_10_06_29.66656945/00_init_database.sql
CREATE ROLE
CREATE DATABASE
```

And actually works:

```
I have no name!@postgresql-0:/$ PGPASSWORD=supersecure psql -h postgresql.postgresql.svc -U johndoe -d foobar
psql (17.0)
Type "help" for help.

foobar=> 
```

**Comment by josedev-union** [comment]
> There's a better way to do this (at least nowadays). No need to edit the template directly.
> 
> You can pass your requirement directly into the Helm chart, something like this:
> 
> primary:
>   initdb:
>     scripts:
>       00_init_database.sql: |
>         CREATE USER johndoe WITH PASSWORD 'supersecure';
>         CREATE DATABASE foobar OWNER johndoe;
> Which translates to the following log, indicating success:
> 
> ```
> postgresql 10:06:38.26 DEBUG ==> Executing /docker-entrypoint-initdb.d/..2024_10_08_10_06_29.66656945/00_init_database.sql
> CREATE ROLE
> CREATE DATABASE
> ```
> 
> And actually works:
> 
> ```
> I have no name!@postgresql-0:/$ PGPASSWORD=supersecure psql -h postgresql.postgresql.svc -U johndoe -d foobar
> psql (17.0)
> Type "help" for help.
> 
> foobar=> 
> ```

this approach works but keeping plain credentials in helm values and k8s configmap is unsecure. Still need prod-level solution

**Comment by josedev-union** [comment]
i can see `initdb.scriptsSecret` and it is enough
