### ISSUE TITLE
New version installation error reported

### ISSUE THREAD

**Issue by alion-wen** [bitnami/charts#6219]
Readiness probe failed:
Readiness probe failed: Get "http://172.16.1.66:10254/healthz": dial tcp 172.16.1.66:10254: connect: connection refused

**Comment by migruiz4** [comment]
Hi @alion-wen,

This information is not enough for us to help you solve your issue, could you please fill the issue template?

```
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
- Output of `kubectl version`

**Additional context**
Add any other context about the problem here.
```

**Comment by alion-wen** [comment]
https://charts.bitnami.com/bitnami
chat: kong-3.5.0
app version: 2.3.3
k8s version：1.18.4
helm version: 3.5.0

**Comment by alion-wen** [comment]
kubectl describe pod/kong-675dd4ccb7-qx9bq -n kong

Successfully assigned kong/kong-675dd4ccb7-qx9bq to 172.19.16.35
Container image "docker.io/bitnami/kong:2.1.4-debian-10-r22" already present on machine
Created container kong
Started container kong
Container image "docker.io/bitnami/kong-ingress-controller:0.10.0-debian-10-r28" already present on machine
Created container kong-ingress-controller
Started container kong-ingress-controller
Readiness probe failed:
Readiness probe failed: Get "http://172.16.1.63:10254/healthz": dial tcp 172.16.1.63:10254: connect: connection refused

**Comment by alion-wen** [comment]
kong It keeps restarting

**Comment by alion-wen** [comment]
I installed KONG normally last Monday, but this problem occurred today when I reinstalled it

**Comment by alion-wen** [comment]
I wonder if this issue is related to the previous day's update

**Comment by alion-wen** [comment]
I don't know if this problem has anything to do with the last few days update

**Comment by migruiz4** [comment]
Hi @alion-wen,

Your issue is caused because your Kong release is using the Postgresql PV from your previous installation.

If you get the pod logs, you will probably see the following:
```
> kubectl logs kong-test-84c46bbc5-9mdwp -c kong
kong 08:31:39.59 
kong 08:31:39.59 Welcome to the Bitnami kong container
kong 08:31:39.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kong
kong 08:31:39.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kong/issues
kong 08:31:39.60 
kong 08:31:39.60 INFO  ==> ** Starting Kong setup **
kong 08:31:39.61 INFO  ==> Validating settings in KONG_* env vars
kong 08:31:39.65 INFO  ==> Initializing Kong
kong 08:31:39.65 INFO  ==> Waiting for database connection to succeed
```
To solve this issue, you'll have to uninstall your Kong release and delete the Postgresql PVC:
```
> helm uninstall kong-test                      
release "kong-test" uninstalled
> kubectl get pvc                               
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-kong-test-postgresql-0   Bound    pvc-4993da69-8e3b-4472-af6b-cb99229e310c   8Gi        RWO            hostpath       9m7s
> kubectl delete pvc data-kong-test-postgresql-0
persistentvolumeclaim "data-kong-test-postgresql-0" deleted
```

Note: Deleted PVCs can not be restored, using this method will install Kong with no data. Any data from your previous installation will be lost.

You can find more information in our troubleshooting guide (Section: Persistence Volumes (PVs) retained from previous releases): https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/

**Comment by alion-wen** [comment]
I need the data from the old PVC. What should I do

**Comment by alion-wen** [comment]
There is another question that I need to modify the log format of Kong. The default log format cannot meet my requirements. What should I do

**Comment by migruiz4** [comment]
Restoring the previous PVC might be a bit complicated, as when uninstalling kong you probably also removed the secret containing the passwords for your postgresql database.

In case you had a backup of those passwords, you could create a Secret with the Postgresql password of the previous installation and provide it using the value `postgresql.existingSecret` when installing the Kong chart. 

For example:
```bash
#Create a secret with the password for your previous
kubectl create secret generic kong-test-postgresql-restored --from-literal=postgresql-password=my_pass --from-literal=postgresql-postgres-password=my_pass
#Re-install the chart providing the existing secret
helm install kong-test bitnami/kong --set postgresql.existingSecret=kong-test-postgresql-restored
```

This will configure everything with the previous password, Postgresql should reattach the previous PVC and Kong should be able to connect to it.

Regarding the Kong log format, I'd recommend checking their documentation: https://docs.konghq.com/gateway-oss/2.4.x/logging/
You can use the features `kong.extraVolumes` and `kong.extraVolumeMounts` to overwrite the Kong configuration or add additional files if needed,  and add custom initScripts using `kong.initScriptsCM`.

**Comment by alion-wen** [comment]
Hello, I have a problem, please ask me. I need to mount a PVC into Kong POD, may I ask how to do this? When I modify the Kong Deployment YAML file, an error of password authentication will appear. What should I do, please?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitnami/charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitnami/charts] New version installation error reported (#6219)





 
Hi @alion-wen,
 
Your issue is caused because your Kong release is using the Postgresql PV from your previous installation.
 
If you get the pod logs, you will probably see the following:
 &gt; kubectl logs kong-test-84c46bbc5-9mdwp -c kong kong 08:31:39.59  kong 08:31:39.59 Welcome to the Bitnami kong container kong 08:31:39.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kong kong 08:31:39.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kong/issues kong 08:31:39.60  kong 08:31:39.60 INFO  ==&gt; ** Starting Kong setup ** kong 08:31:39.61 INFO  ==&gt; Validating settings in KONG_* env vars kong 08:31:39.65 INFO  ==&gt; Initializing Kong kong 08:31:39.65 INFO  ==&gt; Waiting for database connection to succeed  
To solve this issue, you'll have to uninstall your Kong release and delete the Postgresql PVC:
 &gt; helm uninstall kong-test                       release "kong-test" uninstalled &gt; kubectl get pvc                                NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE data-kong-test-postgresql-0   Bound    pvc-4993da69-8e3b-4472-af6b-cb99229e310c   8Gi        RWO            hostpath       9m7s &gt; kubectl delete pvc data-kong-test-postgresql-0 persistentvolumeclaim "data-kong-test-postgresql-0" deleted  
Note: Deleted PVCs can not be restored, using this method will install Kong with no data. Any data from your previous installation will be lost.
 
You can find more information in our troubleshooting guide (Section: Persistence Volumes (PVs) retained from previous releases): https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/

**Comment by migruiz4** [comment]
It won't be necessary to modify the deployment YAML.

If you use the same release name, the chart will reuse the previous PVC. But, as I mentioned before, the main problem would be that the secret containing the Postgresql password to access the database in the Postgresql PVC was deleted when you uninstalled the chart, and re-installing it will generate a new secret with a random password that won't work with the previous PVC and causing the issue you are having.

The possible solutions are:
- Deleting the PVC and have the chart installed from zero losing the data from your previous installation.
- Manually re-create the secret with the deleted passwords, using a backup if you have any, and configure it using the value "postgresql.existingSecret".
- If you don't have a backup of your password, maybe you could somehow reset the Postgresql password, but I may not be able to help you do that.
  For that purpose you could use the `postgresql.*` settings, all the settings available can be found in the postgresql chart documentation here: https://github.com/bitnami/charts/tree/master/bitnami/postgresql

**Comment by alion-wen** [comment]
Thank you very much. I have found the solution




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitnami/charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitnami/charts] New version installation error reported (#6219)





 
It won't be necessary to modify the deployment YAML.
 
If you use the same release name, the chart will reuse the previous PVC. But, as I mentioned before, the main problem would be that the secret containing the Postgresql password to access the database in the Postgresql PVC was deleted when you uninstalled the chart, and re-installing it will generate a new secret with a random password that won't work with the previous PVC and causing the issue you are having.
 
The possible solutions are:
  
Deleting the PVC and have the chart installed from zero losing the data from your previous installation.
 
Manually re-create the secret with the deleted passwords, using a backup if you have any, and configure it using the value "postgresql.existingSecret".
 
If you don't have a backup of your password, maybe you could somehow reset the Postgresql password, but I may not be able to help you do that.
 For that purpose you could use the postgresql.* settings, all the settings available can be found in the postgresql chart documentation here: https://github.com/bitnami/charts/tree/master/bitnami/postgresql

**Comment by alion-wen** [comment]
Your reply is very helpful. Thank you




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "bitnami/charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上6:59
***@***.***&gt;;
抄送： &nbsp;“ Ty” ***@***.***&gt;;“ Mention” ***@***.***&gt;;
主题： &nbsp;Re：[bitnami / charts]报告了新版本的安装错误（＃6219）





 
无需修改部署YAML。
 
如果使用相同的发行版名称，则图表将重复使用先前的PVC。但是，正如我之前提到的，主要问题是，当您卸载图表时，包含用于访问Postgresql PVC中数据库的Postgresql密码的机密已被删除，然后重新安装它会生成一个带有随机密码的新机密，无法与先前的PVC配合使用，并导致出现问题。
 
可能的解决方案是：
  
删除PVC并从零开始安装图表，这将丢失先前安装中的数据。
 
使用备份（如果有的话）手动使用删除的密码重新创建密码，并使用值“ postgresql.existingSecret”对其进行配置。
 
如果您没有密码的备份，也许您可​​以通过某种方式重设Postgresql密码，但是我可能无法帮助您。
 为此，您可以使用postgresql.*设置，所有可用的设置都可以在以下PostgreSQL图表文档中找到：https : //github.com/bitnami/charts/tree/master/bitnami/postgresql
   
-
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by migruiz4** [comment]
I'm glad you found my response helpful and you were able to solve your issue!

**Comment by alion-wen** [comment]
Hello, I have one more question for you. Kong have comments like nginx, nginx. Ingress. Kubernetes. IO/configuration - snippet, because I need to judge according to the request url








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitnami/charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitnami/charts] New version installation error reported (#6219)





 
I'm glad you found my response helpful and you were able to solve your issue!

**Comment by migruiz4** [comment]
Hi @alion-wen,
 
For questions regarding Kong configuration, I'd recommend having a look at [Kong's documentation](https://docs.konghq.com/) and its official channels such as their [Github repositories](https://github.com/Kong/kong) and [Forums](https://discuss.konghq.com/), as it would be out of my scope.

If you have any questions regarding how to configure any Kong setting using our chart I will be happy to help you.
