### ISSUE TITLE
[bitnami/rabbitmq] values.yaml documentation inconsistency for ingress property existingSecret

### ISSUE THREAD

**Issue by matbest1** [bitnami/charts#6223]
**Which chart**:
bitnami/rabbitmq v8.12.0

**Describe the bug**
values.yaml documentation for custom ingress tls secret name is inconsistent.

Custom ingress secret name is used if _.Values.ingress.existingSecret_ is populated and not  _.Values.ingress.tls.existingSecret_ as described in [values.yaml documentation](https://github.com/bitnami/charts/blob/70d602fea38010145c20e1ca59be06e4cf32bf80/bitnami/rabbitmq/values.yaml#L764)

Ref: https://github.com/bitnami/charts/blob/70d602fea38010145c20e1ca59be06e4cf32bf80/bitnami/rabbitmq/templates/_helpers.tpl#L95-L104

https://github.com/bitnami/charts/blob/70d602fea38010145c20e1ca59be06e4cf32bf80/bitnami/rabbitmq/values.yaml#L764-L771

**Comment by juan131** [comment]
Hi @matbest1 

You're completely right!! Thanks for reporting it!

I create a PR to improve how to manage certificates for TLS ingress in the chart.
