### ISSUE TITLE
PostgreSQL Pod ends in CrashLoopBackOff (adding SQL statement in initDBScripts)

### ISSUE THREAD

**Issue by roere** [bitnami/charts#6228]
**Which chart**:
bitnami/postgresql 11.11.0

**Describe the bug**
Primary Pod (using 2 replicas) ends in CrashLoopBackOff, if I commit more than one SQL statement in initDBScripts. One statement always runs through smoothly, both with psql - f [file] or psql -c [statement] or with a [name].sql script. 
CLI with e.g. "createuser" or "createdb" are without problems, can be more then one.

**To Reproduce**

1. Create initDBScript
2. e.G.: psql -U postgres -h 127.0.0.1 -c "create database XXX"
3. e.G.: psql -U postgres -h 127.0.0.1 -c "create user XXX with encrypted password 'XXX'"
4. See error: Pod remains in CrashLoopBackOff

**Expected behavior**
Pod to start flawlessly

**Version of Helm and Kubernetes**:
Helm: 3.5.4, Kubernetes 1.21

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  Could you provide your helm install command ? I would like to try to reproduce the issue.

**Comment by roere** [comment]
Hi,
the Helm Command:

> helm install postgresql bitnami/postgresql -f values_cust.yaml

This is my values_cust.yaml:

replication:
  enabled: true
  user: repl_user
  password: XXX
  readReplicas: 2
  \#\# Set synchronous commit mode: on, off, remote_apply, remote_write and local
  \#\# ref: https://www.postgresql.org/docs/9.6/runtime-config-wal.html\#GUC-WAL-LEVEL
  synchronousCommit: 'on'
  \#\# From the number of `readReplicas` defined above, set the number of those that will have synchronous replication
  \#\# NOTE: It cannot be > readReplicas
  numSynchronousReplicas: 1
  \#\# Replication Cluster application name. Useful for defining multiple replication policies
  \#\#
  applicationName: XXX


\#\# PostgreSQL client authentication configuration
\#\# Specify content for pg_hba.conf
\#\# Default: do not create pg_hba.conf
\#\# Alternatively, you can put your pg_hba.conf under the files/ directory
pgHbaConfiguration: |-
    host     all             postgres        127.0.0.1/32            trust
    host     all             all             0.0.0.0/0               md5
    host     all             all             ::/0                    md5
    local    all             all                                     md5
    host     all             all             127.0.0.1/32            md5
    host     all             all             ::1/128                 md5
    host     replication     all             0.0.0.0/0               md5
    host     replication     all             ::/0                    md5



\#\# initdb scripts
\#\# Specify dictionary of scripts to be run at first boot
\#\# Alternatively, you can put your scripts under the files/docker-entrypoint-initdb.d directory
\#\#
initdbScripts:
  peertube_init_script.sh: |
    \#!/bin/sh
    createuser -U postgres -h 127.0.0.1 -d --replication repl_user
    createuser -U postgres -h 127.0.0.1 peertube
    /opt/bitnami/postgresql/bin/psql -U postgres -h 127.0.0.1 -c "ALTER USER peertube WITH ENCRYPTED PASSWORD 'XXX';" -c "ALTER USER repl_user WITH ENCRYPTED PASSWORD 'XXX';"

**Comment by rafariossaa** [comment]
Hi,
  Could you provide the logs from the pod that is crashing ?.

**Comment by roere** [comment]
That's what I got. Actually the message 'role "repl_user" already exists' was misleading. Turned out, that a "$" in my original password was the problem. Escaping the "$" (just in the initDBscript, for the replication.password field it was not necessary) solved my issue and the Pods now start just fine.
Thanks for the help. Actually putting "xxx" here in the description, instead of my original password, put me on the right track!

```
postgresql 09:54:41.31 
postgresql 09:54:41.32 Welcome to the Bitnami postgresql container
postgresql 09:54:41.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 09:54:41.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 09:54:41.33 
postgresql 09:54:41.39 INFO  ==> ** Starting PostgreSQL setup **
postgresql 09:54:41.43 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 09:54:41.45 INFO  ==> Loading custom pre-init scripts...
postgresql 09:54:41.47 INFO  ==> Initializing PostgreSQL database...
postgresql 09:54:41.49 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql 09:54:41.56 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 09:54:41.61 INFO  ==> Configuring replication parameters
postgresql 09:54:41.67 INFO  ==> Configuring fsync
postgresql 09:54:41.74 INFO  ==> Loading custom scripts...
postgresql 09:54:41.75 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 09:54:41.76 INFO  ==> Starting PostgreSQL in background...
createuser: creation of new role failed: ERROR:  role "repl_user" already exists
postgresql 09:54:42.32 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
```

**Comment by rafariossaa** [comment]
Hi,
  I am glad you where able to solve it.
  Spotting this characters that need escaping is not easy.

  I am closing this issue.
