### ISSUE TITLE
[bitnami/nginx] evaluate pullSecrets as template

### ISSUE THREAD

**Issue by DaviGia** [bitnami/charts#6229]
**Which chart**:
bitnami/nginx (v. 8.8.4)

**Is your feature request related to a problem? Please describe.**
I have nginx chart as a dependency of a parent custom chart that creates the docker-registry secrets automatically. 
The parent chart generates the image pull secrets Secret name using the .Release.Name value from helm.
Because neither `.Values.image.pullSecrets` nor `.Values.global.imagePullSecrets` values are evaluated as a template I've no way of declaring the generated Secret name in nginx chart.

**Describe the solution you'd like**
I would like to be able to specify templated strings within `.Values.image.pullSecrets` and/or `.Values.global.imagePullSecrets` to support situations where the the Secrets is generated through helm. This can probably be achieved by changing the `bitnami/common` chart to enable this feature across all bitnami charts.

_Note: I'm not sure if creating image pull secrets from Helm is the right way to do it (after all the credentials, using this approach, are written in plain text within chart values). If this feature is not available on purpose due to security concern I would like to know which approach should be used instead (e.g. the Secret should always be created manually before deploying the chart)._

**Describe alternatives you've considered**
The generated Secret has a static name that does not depends on any Helm value.

**Comment by miguelaeh** [comment]
Hi @DaviGia ,
It should be enough to change the common chart at the `_images.tpl` file. Nevertheless, it is not trivial since the values are rendered inside a range and it will fail with missing the `basePath`.

I was trying adding to line 43 of the `_images.tpl` file the function `"common.tplvalues.render"` in order to render the provided value, but I was not able to make it work yet.

**Comment by DaviGia** [comment]
Hi @miguelaeh,

yes, I've tried myself as well and the result was the same.

I wonder if it would be feasible to pass the context instead of the .Values.global.

``` 
{{ include "common.images.pullSecrets" ( dict "images" (list .Values.path.to.the.image1, .Values.path.to.the.image2) "context" $) }}
...
{{- $globalPullSecrets := $.global.imagePullSecrets -}
```

**Comment by miguelaeh** [comment]
Hi @DaviGia ,
Ideally, we should not change the function signature since it is used in all the Helm Charts and it would require updating all of them. Could you create a PR with that to discuss it and find the best way?

**Comment by DaviGia** [comment]
Hi @miguelaeh, I've created the PR with the changes to the bitnami common chart.

**Comment by miguelaeh** [comment]
Thank you very much @DaviGia ,
We are already taking care of it
