### ISSUE TITLE
[bitnami/postgresql-ha] postgresql cluster still remain the node's metadata which has been scale-in 

### ISSUE THREAD

**Issue by zhl003** [bitnami/charts#6233]
**Which chart**:
postgresql-ha latest

**Describe the bug**

 * when scale-in the node in pg-ha cluster , repmgrd still remain the metadata of the nodes which has been removed

**To Reproduce**

1. create a three node pg-ha cluster 

~~~shell
# kubectl  get pod                                   
NAME                                         READY   STATUS    RESTARTS   AGE
pgha-postgresql-ha-pgpool-6848cd4db9-2k4bf   1/1     Running   1          17h
pgha-postgresql-ha-postgresql-0              1/1     Running   0          17h
pgha-postgresql-ha-postgresql-1              1/1     Running   0          17h
pgha-postgresql-ha-postgresql-2              1/1     Running   0          17h
# repmgr service status
 ID | Name                            | Role    | Status    | Upstream                        | repmgrd | PID | Paused? | Upstream last seen
----+---------------------------------+---------+-----------+---------------------------------+---------+-----+---------+--------------------
 1000 | pgha-postgresql-ha-postgresql-0 | standby |   running | pgha-postgresql-ha-postgresql-1 | running | 1   | no      | 0 second(s) ago    
 1001 | pgha-postgresql-ha-postgresql-1 | primary | * running |                                 | running | 1   | no      | n/a                
 1002 | pgha-postgresql-ha-postgresql-2 | standby |   running | pgha-postgresql-ha-postgresql-1 | running | 1   | no      | 0 second(s) ago 
~~~

2. helm upgrade the cluster to scale-in the cluster

   ~~~shell
    helm upgrade pgha bitnami/postgresql-ha --set postgresql.password=${POSTGRES_PASSWORD} --set postgresql.repmgrPassword=${REPMGR_PASSWORD} --set postgresql.replicaCount=2
   ~~~

3. wait the upgrade done and then check the cluster status 

   ~~~shell
   kubectl  get pod
   NAME                                        READY   STATUS    RESTARTS   AGE
   pgha-postgresql-ha-pgpool-9dbbdf6d9-hpqh7   1/1     Running   1          2m35s
   pgha-postgresql-ha-postgresql-0             1/1     Running   2          2m
   pgha-postgresql-ha-postgresql-1             1/1     Running   0          2m31s
   kubectl exec -it pgha-postgresql-ha-postgresql-0 bash
   alias repmgr="/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf"
   repmgr service status
    ID | Name                            | Role    | Status        | Upstream                          | repmgrd | PID | Paused? | Upstream last seen
   ----+---------------------------------+---------+---------------+-----------------------------------+---------+-----+---------+--------------------
    1000 | pgha-postgresql-ha-postgresql-0 | standby |   running     | pgha-postgresql-ha-postgresql-1   | running | 1   | no      | 1 second(s) ago    
    1001 | pgha-postgresql-ha-postgresql-1 | primary | * running     |                                   | running | 1   | no      | n/a                
    1002 | pgha-postgresql-ha-postgresql-2 | standby | ? unreachable | ? pgha-postgresql-ha-postgresql-1 | n/a     | n/a | n/a     | n/a                
   
   WARNING: following issues were detected
     - unable to  connect to node "pgha-postgresql-ha-postgresql-2" (ID: 1002)
     - node "pgha-postgresql-ha-postgresql-2" (ID: 1002) is registered as an active standby but is unreachable
   ~~~

   the status show can seen the node002 register info  in repmgrd 

**Expected behavior**

**Comment by zhl003** [comment]
maybe we can add some code to the pre-stop.sh ,that when a pod exit , after waiting  the new primary ready , by exec  repmgr unregister to  update the metadata

**Comment by migruiz4** [comment]
Hi @zhl003,

You can unregister the repmgr node manually by executing the following command:
```
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf standby unregister --node-id=1002
```
Ref: https://repmgr.org/docs/4.0/repmgr-standby-unregister.html

We can not add the unregister command to the `pre-stop.sh` script because that would cause all the nodes to unregister when stopped, not only the pods that won't be started again. (https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)

**Comment by zhl003** [comment]
Thank you for your attention. @migruiz4  So the point is how to specify the pod is been stopped which will start runing again or stopped  never start again. If we run a schedule job to  check the node count and unregister the node which has been removed? Or just the health check script

**Comment by migruiz4** [comment]
The only safe way I can think to do that would be to provide the script with the number of replicas and then check that `number of replicas < number of cluster nodes` and, whenever that happened, unregister the disconnected node. 
But still, that wouldn't be enough to unregister a node safely, because it could be the case where the cluster is not stable for some reason and a node is accidentally removed.

I think this feature is not appropriate to be part of the chart default behavior but, users that needed it could use `extraDeploy` to do it.
