### ISSUE TITLE
[bitnami/Moodle/Mariadb-Galera] crashing 

### ISSUE THREAD

**Issue by DSWijenayake** [bitnami/charts#6234]
I'm using Bitnami Moodle with Mariadb-Galera. The following command is used to deploy them.

`helm install moodle --set allowEmptyPassword=false,persistence.accessMode=ReadWriteMany,mariadb.enabled=false,externalDatabase.host=mariadb-galera,externalDatabase.password=Moodle@1,moodlePassword=Moodle@1,externalDatabase.user=root,externalDatabase.database=moodle,image.debug=true,podSecurityContext.fsGroup=0,containerSecurityContext.runAsUser=0 bitnami/moodle`

`helm install mariadb-galera --set db.user=moodle,db.password=Moodle@1,db.name=moodle,galera.bootstrap.forceSafeToBootstrap=true,galera.bootstrap.bootstrapFromNode=knode3,rootUser.password=Moodle@1,galera.mariabackup.password=Moodle@1 bitnami/mariadb-galera`

After a successful Moodle installation, it works. But after scaling Moodle, hours later, Moodle (sometimes Mariadb too) pods are restarting. According to the logs, as there Mariadb is having too many connections, the Moodle user is blocked. 

I appreciate your kind help on this.

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake

Are you scaling removing pods or increasing the pods? how many pods do you have in total? It seems that your problem can be:

* You are having a lot of users and the BD can not handle all the requests.
* A third party plugin consuming connections with the BD.
* the last one, some connections are not closing properly (Moodle with MariaDB connections).

I suggest you to ask what is the backend requirements for your specific scenario in [Moodle forums](https://moodle.com/community/). Maybe they can help you adjusting the number of pods.

I hope that I have helped you and thanks a lot for your time. Let me know If I can help you with something else.

Thanks

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

Thanks for your reply. In scaling, I have increased the number of pods.  Have 3 Moodle pods with 3 Mariadb-Galera pods.

This installation is in test-bed with default admin user only. Most of the configurations are default. Therefore, the problem is likely to be the 2nd and/or 3rd of your suggestions. 

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake 

I suggest you to install from zero the project, increase the number of pods and then include one by one the plugins/content/users to try to reproduce the problem. Maybe will be more easy to find the reason.

Thanks again and If you need something else, just let me know.

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu 

I have done two deployments. The first one with 2 Moodle pods and 3 Mariadb pods. The second is 3 Moodle pods with 4 Mariadb pods. The first one crashed with the following logs (I put the last part of the log as it is too long). The second one works so far. It seems like with this new configuration too many connections error is not there, and now it is another. 

`[Thu Apr 29 10:09:17.159453 2021] [core:warn] [pid 1] AH00045: child process 283 still did not exit, sending a SIGTERM
[Thu Apr 29 10:09:17.159457 2021] [core:warn] [pid 1] AH00045: child process 284 still did not exit, sending a SIGTERM
[Thu Apr 29 10:09:17.159460 2021] [core:warn] [pid 1] AH00045: child process 285 still did not exit, sending a SIGTERM
[Thu Apr 29 10:09:17.159464 2021] [core:warn] [pid 1] AH00045: child process 286 still did not exit, sending a SIGTERM
[Thu Apr 29 10:09:17.159468 2021] [core:warn] [pid 1] AH00045: child process 288 still did not exit, sending a SIGTERM
[Thu Apr 29 10:09:18.160513 2021] [core:notice] [pid 1] AH00051: child pid 156 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160550 2021] [core:notice] [pid 1] AH00051: child pid 157 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160599 2021] [core:notice] [pid 1] AH00051: child pid 158 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160690 2021] [core:notice] [pid 1] AH00051: child pid 159 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160736 2021] [core:notice] [pid 1] AH00051: child pid 160 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160821 2021] [core:notice] [pid 1] AH00051: child pid 161 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160843 2021] [core:notice] [pid 1] AH00051: child pid 162 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160916 2021] [core:notice] [pid 1] AH00051: child pid 163 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.160937 2021] [core:notice] [pid 1] AH00051: child pid 167 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161009 2021] [core:notice] [pid 1] AH00051: child pid 168 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161030 2021] [core:notice] [pid 1] AH00051: child pid 169 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161109 2021] [core:notice] [pid 1] AH00051: child pid 170 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161129 2021] [core:notice] [pid 1] AH00051: child pid 171 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161208 2021] [core:notice] [pid 1] AH00051: child pid 172 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161229 2021] [core:notice] [pid 1] AH00051: child pid 173 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161244 2021] [core:notice] [pid 1] AH00051: child pid 174 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161258 2021] [core:notice] [pid 1] AH00051: child pid 175 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161323 2021] [core:notice] [pid 1] AH00051: child pid 176 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161344 2021] [core:notice] [pid 1] AH00051: child pid 180 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161425 2021] [core:notice] [pid 1] AH00051: child pid 181 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161446 2021] [core:notice] [pid 1] AH00051: child pid 182 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161526 2021] [core:notice] [pid 1] AH00051: child pid 183 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161547 2021] [core:notice] [pid 1] AH00051: child pid 184 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161624 2021] [core:notice] [pid 1] AH00051: child pid 185 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161644 2021] [core:notice] [pid 1] AH00051: child pid 186 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161718 2021] [core:notice] [pid 1] AH00051: child pid 187 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161740 2021] [core:notice] [pid 1] AH00051: child pid 192 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161800 2021] [core:notice] [pid 1] AH00051: child pid 193 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161862 2021] [core:notice] [pid 1] AH00051: child pid 194 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161883 2021] [core:notice] [pid 1] AH00051: child pid 195 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161949 2021] [core:notice] [pid 1] AH00051: child pid 196 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.161971 2021] [core:notice] [pid 1] AH00051: child pid 197 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162028 2021] [core:notice] [pid 1] AH00051: child pid 198 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162088 2021] [core:notice] [pid 1] AH00051: child pid 199 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162109 2021] [core:notice] [pid 1] AH00051: child pid 200 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162183 2021] [core:notice] [pid 1] AH00051: child pid 204 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162204 2021] [core:notice] [pid 1] AH00051: child pid 205 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162263 2021] [core:notice] [pid 1] AH00051: child pid 206 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162281 2021] [core:notice] [pid 1] AH00051: child pid 207 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162295 2021] [core:notice] [pid 1] AH00051: child pid 208 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162461 2021] [core:notice] [pid 1] AH00051: child pid 209 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162555 2021] [core:notice] [pid 1] AH00051: child pid 210 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162648 2021] [core:notice] [pid 1] AH00051: child pid 211 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162746 2021] [core:notice] [pid 1] AH00051: child pid 212 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162840 2021] [core:notice] [pid 1] AH00051: child pid 213 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.162934 2021] [core:notice] [pid 1] AH00051: child pid 214 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163027 2021] [core:notice] [pid 1] AH00051: child pid 218 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163091 2021] [core:notice] [pid 1] AH00051: child pid 219 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163112 2021] [core:notice] [pid 1] AH00051: child pid 220 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163185 2021] [core:notice] [pid 1] AH00051: child pid 221 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163208 2021] [core:notice] [pid 1] AH00051: child pid 223 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163269 2021] [core:notice] [pid 1] AH00051: child pid 224 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163332 2021] [core:notice] [pid 1] AH00051: child pid 225 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163353 2021] [core:notice] [pid 1] AH00051: child pid 226 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163418 2021] [core:notice] [pid 1] AH00051: child pid 230 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163440 2021] [core:notice] [pid 1] AH00051: child pid 231 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163498 2021] [core:notice] [pid 1] AH00051: child pid 232 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163565 2021] [core:notice] [pid 1] AH00051: child pid 234 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163587 2021] [core:notice] [pid 1] AH00051: child pid 235 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163654 2021] [core:notice] [pid 1] AH00051: child pid 236 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163676 2021] [core:notice] [pid 1] AH00051: child pid 237 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163736 2021] [core:notice] [pid 1] AH00051: child pid 242 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163797 2021] [core:notice] [pid 1] AH00051: child pid 244 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163818 2021] [core:notice] [pid 1] AH00051: child pid 245 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163885 2021] [core:notice] [pid 1] AH00051: child pid 246 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163906 2021] [core:notice] [pid 1] AH00051: child pid 250 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163921 2021] [core:notice] [pid 1] AH00051: child pid 251 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.163934 2021] [core:notice] [pid 1] AH00051: child pid 252 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164001 2021] [core:notice] [pid 1] AH00051: child pid 253 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164021 2021] [core:notice] [pid 1] AH00051: child pid 254 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164087 2021] [core:notice] [pid 1] AH00051: child pid 255 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164108 2021] [core:notice] [pid 1] AH00051: child pid 256 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164166 2021] [core:notice] [pid 1] AH00051: child pid 257 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164202 2021] [core:notice] [pid 1] AH00051: child pid 258 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164257 2021] [core:notice] [pid 1] AH00051: child pid 263 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164280 2021] [core:notice] [pid 1] AH00051: child pid 279 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164348 2021] [core:notice] [pid 1] AH00051: child pid 280 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164369 2021] [core:notice] [pid 1] AH00051: child pid 281 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164428 2021] [core:notice] [pid 1] AH00051: child pid 283 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164444 2021] [core:notice] [pid 1] AH00051: child pid 284 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164562 2021] [core:notice] [pid 1] AH00051: child pid 285 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164583 2021] [core:notice] [pid 1] AH00051: child pid 286 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164665 2021] [core:notice] [pid 1] AH00051: child pid 288 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Thu Apr 29 10:09:18.164799 2021] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down
`

**Comment by alvneiayu** [comment]
hi @DSWijenayake 

Perfect, let me know if I can help you with something.

Thanks a lot for your time

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

I have reproduced the problem and the logs are as follows. I put the last part of the log as it is too long.

Moodle Log

```
[Fri Apr 30 08:16:07.167964 2021] [core:notice] [pid 1] AH00051: child pid 155 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168135 2021] [core:notice] [pid 1] AH00051: child pid 156 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168161 2021] [core:notice] [pid 1] AH00051: child pid 157 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168185 2021] [core:notice] [pid 1] AH00051: child pid 158 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168208 2021] [core:notice] [pid 1] AH00051: child pid 159 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168232 2021] [core:notice] [pid 1] AH00051: child pid 160 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168280 2021] [core:notice] [pid 1] AH00051: child pid 1195 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168300 2021] [core:notice] [pid 1] AH00051: child pid 307 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168317 2021] [core:notice] [pid 1] AH00051: child pid 308 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168338 2021] [core:notice] [pid 1] AH00051: child pid 309 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168376 2021] [core:notice] [pid 1] AH00051: child pid 310 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168392 2021] [core:notice] [pid 1] AH00051: child pid 1196 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168408 2021] [core:notice] [pid 1] AH00051: child pid 1197 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168422 2021] [core:notice] [pid 1] AH00051: child pid 1198 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168435 2021] [core:notice] [pid 1] AH00051: child pid 1199 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168449 2021] [core:notice] [pid 1] AH00051: child pid 1200 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168460 2021] [core:notice] [pid 1] AH00051: child pid 1201 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168477 2021] [core:notice] [pid 1] AH00051: child pid 1202 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168494 2021] [core:notice] [pid 1] AH00051: child pid 1203 exit signal Segmentation fault (11), possible coredump in /opt/bitnami/apache
[Fri Apr 30 08:16:07.168571 2021] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down
```

Mariadb-Galera log 

```
# User@Host: root[root] @  [192.168.74.235]
# Thread_id: 9233  Schema: moodle  QC_hit: No
# Query_time: 0.000350  Lock_time: 0.000144  Rows_sent: 0  Rows_examined: 0
# Rows_affected: 0  Bytes_sent: 173
SET timestamp=1619770504;
SELECT DISTINCT id, id AS id2
                  FROM mdl_question_usages
                 WHERE id IN (SELECT quba.id FROM mdl_question_usages quba WHERE quba.component = 'core_question_preview'
                    AND NOT EXISTS (
                        SELECT 1
                          FROM mdl_question_attempts      subq_qa
                          JOIN mdl_question_attempt_steps subq_qas ON subq_qas.questionattemptid = subq_qa.id
                          JOIN mdl_question_usages        subq_qu  ON subq_qu.id = subq_qa.questionusageid
                         WHERE subq_qa.questionusageid = quba.id
                           AND subq_qu.component = 'core_question_preview'
                           AND (subq_qa.timemodified > '1619684104'
                                    OR subq_qas.timecreated > '1619684104')
                    )
            );
2021-04-30  8:15:04 6 [ERROR] WSREP: FSM: no such a transition COMMITTED -> COMMITTED
210430  8:15:04 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
To report this bug, see https://mariadb.com/kb/en/reporting-bugs
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.
Server version: 10.5.9-MariaDB-log
key_buffer_size=33554432
read_buffer_size=131072
max_used_connections=5
max_threads=502
thread_count=11
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 1137856 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.
Thread pointer: 0x7fb1f40099f8
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7fb29d385e18 thread_stack 0x49000
/opt/bitnami/mariadb/sbin/mysqld(my_print_stacktrace+0x2e)[0x5613c765fd2e]
/opt/bitnami/mariadb/sbin/mysqld(handle_fatal_signal+0x485)[0x5613c7121255]
2021-04-30  8:16:06 9259 [Warning] Aborted connection 9259 to db: 'moodle' user: 'root' host: '192.168.74.235' (Got an error reading communication packets)
# Time: 210430  8:16:10
# User@Host: root[root] @  [192.168.37.239]
# Thread_id: 9264  Schema: moodle  QC_hit: No
# Query_time: 0.000710  Lock_time: 0.000104  Rows_sent: 519  Rows_examined: 519
# Rows_affected: 0  Bytes_sent: 18113
SET timestamp=1619770570;
SELECT name,value FROM mdl_config;
# User@Host: root[root] @  [192.168.37.239]
# Thread_id: 9264  Schema: moodle  QC_hit: No
# Query_time: 0.001722  Lock_time: 0.000087  Rows_sent: 414  Rows_examined: 1941
# Rows_affected: 0  Bytes_sent: 18918
SET timestamp=1619770570;
SELECT * FROM mdl_config_plugins WHERE name = 'version';
```
I appreciate your kind help on this.

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake 

I need some information. Did you include something inside the Moodle or the Moodle is empty (clean install)? Share with me the steps that you followed to reproduce the issue, please.

Moreover I suggest you to use a odd number of mariaDB pods. Just to avoid "split brain" situations.

Could you check the memory space that you have in your host? To be sure that your host has enough space.

Thanks a lot

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

I have only added a course name to Moodle after the installation. 

The steps are as in the following order.

Install Mariadb-Galera. (this will produce 3 Pods by default which is an odd number)

`helm install mariadb-galera1 --set db.user=moodle,db.password=Moodle@1,db.name=moodle,galera.bootstrap.forceSafeToBootstrap=true,galera.bootstrap.bootstrapFromNode=kworker-3,rootUser.password=Moodle@1,galera.mariabackup.password=Moodle@1 bitnami/mariadb-galera`

Install Moodle

`helm install moodle --set allowEmptyPassword=false,persistence.accessMode=ReadWriteMany,mariadb.enabled=false,externalDatabase.host=mariadb-galera1,externalDatabase.password=Moodle@1,moodlePassword=Moodle@1,externalDatabase.user=root,externalDatabase.database=moodle,image.debug=true,podSecurityContext.fsGroup=0,containerSecurityContext.runAsUser=0 bitnami/moodle `

Scale Moodle after the Moodle pod becomes ready.

`kubectl scale deployment moodle --replicas=2`

Scale Moodle again after the second Moodle pod becomes ready.

`kubectl scale deployment moodle --replicas=3`

There is 10GB RAM per K8s node.

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake 

Following your steps, I can not reproduce your problem:

```
kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
mariadb-galera1-0         1/1     Running   0          80m
mariadb-galera1-1         1/1     Running   0          79m
mariadb-galera1-2         1/1     Running   0          78m
moodle-5599d48546-2lv42   1/1     Running   0          68m
moodle-5599d48546-cs8xb   1/1     Running   0          70m
moodle-5599d48546-vp2q5   1/1     Running   0          76m
```
All the pods are working properly, without any segfault. In which cluster you are running your deployment?

Thanks

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

Thanks for your attempt to reproduce the problem. Actually, it takes few hours to happen. As I experienced sometimes it takes more than 5 hours to happen. Anyway, most probably it will happen within a day. 

My Kubernetes cluster information is as follows.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake 

Wow. Ok, so I am going to repeat again the test waiting more than 5 hours. I will come back with some information.

Thanks again

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

Ok. I am looking forward to see your updates.

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake

I am still reproducing the problem. I didn't see the problem yet. Just to tell you that I am working on it.

Thanks for your patience. 

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

Did you run it for more than a day? Just log in to moodle and create a course and see. Sometimes it may help to see the problem. Mostly the problem is happening when the deployment is idle (without using moodle). 

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake

I reproduced the problem in local (using minikube) and using GKE. It seems that it is a problem with the Apache configuration but I created an internal task to investigate and fix the problem and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot for the patience and for your help to reproduce the problem.

Álvaro

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

Ok. I am looking forward to see your updates.

Thanks.

**Comment by DSWijenayake** [comment]
Hi @alvneiayu,

Do you have any updates?

Thanks.

**Comment by alvneiayu** [comment]
hi @DSWijenayake

We are still working on it. I will let you know when we find the reason and the solution.

Thanks a lot for your patience.

Álvaro

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by DSWijenayake** [comment]
Hi, Thank you for the update. I have solved the problem by using my own solutions with some other Bitnami charts.

**Comment by TH-C013** [comment]
@DSWijenayake 

I'm facing similar issue with my deployment with 2 Moodle replicas and 1 Mariadb.
I'm getting the same error 
![image](https://user-images.githubusercontent.com/71526018/154709877-fe925565-3652-4140-8fc4-c77aa800f74b.png)


Please can you share some insight on your resolution ?
