### ISSUE TITLE
[Bitnami/Wordpress/Memcached] Memcached pod is executed on random node instead of taking into account nodeSelector value

### ISSUE THREAD

**Issue by corend** [bitnami/charts#6241]
**Which chart**:
Wordpress with Memcached configured

**Describe the bug**
When you configure a nodeSelector and Memcached for Wordpress, the Memcached is randomly choosing the node instead of being executing on a node configured for that. 

**To Reproduce**
- configure two pools of nodes
- one pool of nodes is labeled with for example "type=wp"
- the second pool of nodes if configured to have the label "type=storage"
- activate the Memcached for Wordpress in your YAML
- configure the YAML values with nodeSelector set to use "type=wp" only
- execute your YAML
- Wordpress is correctly running on "type=wp"
- Memcached is not running on the configured nodeSelector (should be "type=wp" but is actually running on "type=storage")

```YAML
nodeSelector:
  type: wp
wordpressConfigureCache: true
memcached:
  enabled: true
  service:
    port: 11211
```
**Expected behavior**
Memcached has to be executed on the nodeSelector as it is correctly the case for Wordpress

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Version:"v3.5.4"
```

- Output of `kubectl version`:

```
Client Version:"v1.20.2" - Server Version:"v1.20.4"
```

**Comment by rafariossaa** [comment]
Hi,
  As it is using memcached as a subchart and it also has the nodeSelector properties, could you try the following ?
```console
 $  helm install mywp bitnami/wordpress --set memcached.enabled=true --set memcached.nodeSelector="type: wp" --set nodeSelector="type: wp"
```
