### ISSUE TITLE
Can i disable TOMCAT_PASSWORD?

### ISSUE THREAD

**Issue by Tehacz** [bitnami/charts#6250]
Hello,

I dont want to use TOMCAT_PASSWORD everytime when i uprgrade the chart, is there any solution to just turn it off?

**Comment by carrodher** [comment]
Hi, I'm sorry but this is not possible, the password is set during the first installation and it should be maintained when upgrading the Helm Chart, in the following links you can find more information about this topic:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases
