### ISSUE TITLE
Error: Chart.yaml file is missing

### ISSUE THREAD

**Issue by samwho** [bitnami/charts#6269]
**Which chart**:
metallb 2.3.6

**Describe the bug**
I have the following in a terraform file called `provider.tf`:

```
provider "helm" {
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = "localkube"
  }
}

provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = "localkube"
}

resource "kubernetes_namespace" "metallb" {
  metadata {
    name = "metallb"
  }
}

resource "helm_release" "metallb" {
  name       = "metallb"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "metallb"
  version    = "2.3.6"
  namespace  = "metallb"

  values = [
    "${file("metallb/values.yml")}"
  ]
}
```

The content of `metallb/values.yml`:

```
controller:
  image:
    repository: metallb/controller
    tag: v0.9
speaker:
  image:
    repository: metallb/speaker
    tag: v0.9
configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 10.245.0.0/16
```

I'm using those images for arm support.

**To Reproduce**

1. Run `terraform apply`

**Expected behavior**
metallb to be installed successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-04-09T16:47:30Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/arm"}
```

- Output of `terraform version`:

```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/helm v2.1.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
```

**Additional context**
The output from terraform is:

```
helm_release.metallb: Creating...
╷
│ Error: Chart.yaml file is missing
│ 
│   with helm_release.metallb,
│   on provider.tf line 124, in resource "helm_release" "metallb":
│  124: resource "helm_release" "metallb" {
│ 
╵
```

Oddly this did work earlier in the evening. When I try to hit https://charts.bitnami.com/bitnami in my browser I see the following:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>X6RSHVTPZWT5BM4W</RequestId>
<HostId>6BBusDaE9DhJb0XaU9ZjtwlqnRxnQxcjYCpMgnLuax/m0B8Tgd4db9nhN0E6rig/OoWLkTw0rKs=</HostId>
</Error>
```

**Comment by samwho** [comment]
Oddly `helm install -f metallb/values.yml --namespace metallb metallb bitnami/metallb` works just fine, so perhaps this is a terraform bug.

**Comment by miguelaeh** [comment]
Hi @samwho ,
This issue does not seem to be related to the Helm Chart itself. Locally a helm install should be working.
Executing
```
helm install metallb bitnami/metallb
```
Seems to work fine. Could you share the output of that command from your local machine? If it works it is probably related to terraform which I can't provide support on. Also, please have in mind if you use images that are not from bitnami we cannot provide support if any issue appears related to the images

**Comment by samwho** [comment]
Yeah, I did notice that that works. I'll close this and go ask the Terraform folks. Thanks for getting back to me :)

**Comment by samwho** [comment]
For anyone stumbling on this, the answer is over here: https://github.com/hashicorp/terraform-provider-helm/issues/735.
