### ISSUE TITLE
[bitnami/airflow] resources ignored for worker in KubernetesExecutor

### ISSUE THREAD

**Issue by diegoami** [bitnami/charts#6279]
**Which chart**:
Airflow

**Which version**:
2.0.2-debian-10-r7

**Describe the bug**
I don't know if this is intentional, but when using KubernetesExecutor ```worker.resources``` in ```values.yaml``` is ignored. 
This is a problem for instance in openshift, when administrators have set up default limits for containers, because then you would regularly run out of memory.

**To Reproduce**
Just start a worker and verify the YAML file that is generated when starting a worker with KubernetesExecutor - you will see that ```worker.resources```  is empty, even if you have defined it in your values.yaml

**Expected behavior**
I would expect resources settings in ```values.yaml``` to be taken into consideration, or at least get a warning that when using KubernetesExecutor it will be ignored.
The fix is easy, if this is not intentional. Just include in ```template/config/configmap.yml``` the resources

```
 containers:
        - name: airflow-worker
          image: {{ include "airflow.workerImage" . }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          {{- if .Values.worker.resources }}
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- end }}
          env:
```

**Comment by carrodher** [comment]
Yes, it makes sense to have control over the worker resources even when the workers are launched by the KubernetesExecutor. Would you like to contribute by creating a PR? We will be happy to review it.

**Comment by diegoami** [comment]
Ok, sure
