### ISSUE TITLE
[bitnami/mariadb-galera] Add support to Vault secrets

### ISSUE THREAD

**Issue by diegoep** [bitnami/charts#6287]
**Which chart**: bitnami/mariadb-galera

**Is your feature request related to a problem? Please describe.**
I'm trying to wire mariadb-galera to Vault and it's being difficult to load passwords from Vault secrets since there's no option  to load passwords as files (similar to what is available in the chart bitnami/mariadb).

**Describe the solution you'd like**
Implement for chart bitnami/mariadb-galera the same solution that was done for the chart bitnami/mariadb to add support to Vault secrets. 
Ref: https://github.com/bitnami/charts/commit/898fff4a3073f29bf50cd061d8d0c8879a6e0885#diff-6d62c7a43b5cb76e55c421916a663077c37576e66f6771157b51cac3c3868c5a

**Additional context**
Is there any reason for the solution implemented for bitnami/mariadb was not replicated to bitnami/mariadb-galera?

**Comment by juan131** [comment]
Thanks for this great suggestion @diegoep !! I agree that's something we should also support in the MariaDB Galera chart.
I'll create a PR, and adapt the image tu support it.
