### ISSUE TITLE
fluentd + fluent-bit

### ISSUE THREAD

**Issue by kfox1111** [bitnami/charts#6289]
**Which chart**:
fluentd

**Is your feature request related to a problem? Please describe.**
Fluentd takes a bunch of memory for the forwarder on each node. Fluent-bit is lighter weight and can perform the same job in a lot of cases.

**Describe the solution you'd like**
It would be great if the forwarder was selectable between fluentd and fluent-bit while leaving the aggregator to be fluentd.

**Comment by carrodher** [comment]
Hi, thanks for the suggestion. Currently, using the bitnami/fluentd Helm Chart is possible to deploy it in "aggregator only" mode by disabling the forwarder. With this approach, you should be able to deploy an external fluent-bit and configure it to send logs to the aggregator.

I don't feel very confident with the idea of deploy fluent-bit as part of the fluentd Helm Chart, at this moment we don't have bitnami/fluent-bit in our catalog, but maybe this is a possible solution for the long term
