### ISSUE TITLE
[bitnami/airflow] Web server replicas fail indeterminately when connecting to either local or external Postgres

### ISSUE THREAD

**Issue by dontspamterry** [bitnami/charts#6303]
**Which chart**:
bitnami/airflow
Chart version: 10.0.1

**Describe the bug**
When I configure >1 web server replicas, at least one replica will come up successfully, but other replicas enter in to a CrashLoopBackoff state and is unable to recover, i.e. the replica pod will restart and continuously result in an Error and then CrashLoopBackoff. I checked the logs of the web server replica and see this:

```
│ airflow-web airflow 17:14:35.38                                                                                                                               │
│ airflow-web airflow 17:14:35.38 Welcome to the Bitnami airflow container                                                                                      │
│ airflow-web airflow 17:14:35.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow                                    │
│ airflow-web airflow 17:14:35.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues                                │
│ airflow-web airflow 17:14:35.39                                                                                                                               │
│ airflow-web airflow 17:14:35.39 INFO  ==> Enabling non-root system user with nss_wrapper                                                                      │
│ airflow-web airflow 17:14:35.40 INFO  ==> ** Starting Airflow setup **                                                                                        │
│ airflow-web airflow 17:14:35.42 INFO  ==> Initializing Airflow ...                                                                                            │
│ airflow-web airflow 17:14:35.44 INFO  ==> No injected configuration file found. Creating default config file                                                  │
│ airflow-web airflow 17:14:36.09 INFO  ==> Configuring Airflow webserver authentication                                                                        │
│ airflow-web airflow 17:14:36.12 INFO  ==> Configuring Airflow database                                                                                        │
│ airflow-web airflow 17:14:36.15 INFO  ==> Waiting for PostgreSQL to be available at tsiu-too-airflow-postgresql:5432...
│ airflow-web stream closed   
```
It seems like an attempt to make a connection to the Postgres pod fails and then the pod errors out and a retry is attempted again. I've seen this same, exact behavior when I configure an external Postgres DB as well.

Even if I kill the web server replica pod, the new pod spun up exhibits the same symptoms.

Some things to note:
* The Airflow app is still accessible as there is always at least one web server replica that starts up successfully
* The error above does not happen all the time, but enough that I decided to file this issue. This kind of makes me wonder if there is a race condition where sometimes multiple web server replicas start up fine and sometimes they don't
* What puzzles me is why even after killing the failing pod, the new pod spun up shows the same symptoms

I end up tearing down the deploy and re-deploy with only web server replica. If that succeeds, I then incrementally bump up the number of replicas to my target number.

**To Reproduce**
Based on my description above, it's hard to come up with a reproducible scenario, but here are my `values.yaml` overrides:

```
executor: KubernetesExecutor
redis:
  enabled: false
rbac:
  create: true
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: <IRSA role ARN>

loadExamples: false

scheduler:
  replicaCount: 2

web:
  baseUrl: <base_url>
  extraEnvVars:
  - name: AIRFLOW__WEBSERVER__SECRET_KEY
    value: <secret_key>
  replicaCount: 3

```

1. Deploy the Airflow Helm chart with the above values overrides. Sometimes the web server replicas all start up, sometimes only one does

**Expected behavior**
All three of my web server replicas specified in my `values.yaml` override should start up.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
none

**Comment by miguelaeh** [comment]
Hi @dontspamterry ,
I have tried with your values and it seems to be working fine in my case.
Could there be something cutting traffic on your cluster to produce that `stream closed` error?

**Comment by dontspamterry** [comment]
Hi @miguelaeh ,
I don't believe there is anything cutting traffic as startup does work sometimes when I specify >1 web replicas. One of the challenges I faced when trying to look in to this was determining if the logging could provide more detailed information. The pod logs don't say much so I tried dropping the logging level to debug hoping to capture more information, but that did not produce additional pod logs. And when this scenario hits, I can only shell in to the container for a short duration before it errors out and enters CrashLoopBackoff. Any pointers on how I might be able to obtain/access more detailed logging?

**Comment by miguelaeh** [comment]
Hi @dontspamterry ,
You can increase the verbosity setting [this](https://github.com/bitnami/charts/blob/d9954d6065f922f180dcc17e8e1898398b40b181/bitnami/airflow/values.yaml#L83) to `true`. The same parameter exists for the scheduler image.
Could you also share the PostgreSQL logs? Just to see if there is any hint there

You could try to create a pod with the same configuration as the ones deployed by the Chart and execute `/opt/bitnami/scripts/airflow/entrypoint.sh /opt/bitnami/scripts/airflow/run` which is the command executed by the container and you will see.
To do that, you can use something like:
```
kubectl get pod -o yaml <pod-name> > /tmp/pod.yaml
```

Edit the yaml and then 
```
kubectl create -f /tmp/pod.yaml
```

**Comment by dontspamterry** [comment]
Thank you for the pointer to that setting, @miguelaeh . That setting might also help me understand another issue I'm facing. I'll circle back to this issue later, but again, thx for providing some great pointers!
