### ISSUE TITLE
Airflow DAG Import Errors on Web UI but Able to Run Dag on CLI 

### ISSUE THREAD

**Issue by RaedShabbir** [bitnami/charts#6304]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**
I required a way to install a private python package using a setup.py similar to https://github.com/bitnami/charts/issues/3533#issuecomment-832791435.

To do this I extended and installed the relevant packages on the following images 
bitnami/airflow
scheduler -> bitnami/airflow-scheduler:2.0.2-debian-10-r7
web -> FROM bitnami/airflow:2.0.2-debian-10-r0
worker -> FROM bitnami/airflow-worker:2.0.2-debian-10-r7

I then used git to sync the dags repo. I also tried passing in the dag as a configMap but recieve the same error. 

The error seen on the UI is as follows; 
```
Broken DAG: [/opt/bitnami/airflow/dags/git_private-dags/private_dag.py] Traceback (most recent call last):
  File "/home/docker/<private package>/__init__.py", line 1, in <module>
AttributeError: module 'google.cloud.speech' has no attribute 'RecognitionConfig'
```

When running the dag via an interactive shell on the web container, no errors are thrown and I can even run the dag with airflow CLI.

**To Reproduce**
You would not be able to reproduce this considering the private package. But could probably create a similar example with the google cloud speech package on pip. 

**Expected behavior**
Expected Web UI to load things properly 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
"v3.5.3"
```

- Output of `kubectl version`:

```
v1.20.5
```
Any help would be appreciated,
 would restarting just the web UI be a possible solution? What would be the best way to accomplish this?

**Comment by RaedShabbir** [comment]
Also as a follow up question, which of the airflow images in specific require the private packages to be installed?

**Comment by alemorcuq** [comment]
Sorry for the late response, @RaedShabbir, I lost track of this ticket. Can you check this comment from another ticket? https://github.com/bitnami/charts/issues/3533#issuecomment-793625324
