### ISSUE TITLE
[bitnami/moodle] Highly available Moodle

### ISSUE THREAD

**Issue by DSWijenayake** [bitnami/charts#6312]
**Which chart**:
moodle 3.10.3

**The problem:**
It seems like the high availability (running identical multiple pods of both moodle and mariadb on multiple Kubernetes nodes whereas if one node fails the other pod[s] can replace it without any downtime) is not addressed by the bitnami/moodle chart.

**Required solution:**
Want to have highly available moodle deployment in Kubernetes. 

**The considered alternatives:** 

- bitnami/moodle chart - the moodle part is highly available whereas the mariadb is not (single master - multiple slaves; if master fails moodle may experience some downtime )

- bitnami/moodle chart with bitnami/mariadb chart- the same problem as above

- bitnami/moodle chart with bitnami/mariadb-galera chart- the problem is described in #6234

**Comment by rafariossaa** [comment]
Hi,
  The way to try to achieve that what you are trying by using galera. Let's see how #6234 progress.
  In any case, I think you are not going to have zero downtime / errors. The reason that lead me to think this is that most probably moodle is not handling database re-connections. So, in case a database error, the user will need to reload the page to moodle reconnect again. Even if you have galera, you will find some of this issues.
  Please, take this a a thought not as a sure thing, I don't know the moodle's internals, but this is the very typical behavior of php applications.

**Comment by DSWijenayake** [comment]
Hi,

I agree with your views about the behavior of web applications. But, here, a big problem is because of this crashing, sometimes, the deployment is corrupted. As a result, the pods are crashing when they scaled up, the administrator cannot log in, etc. The errors cannot be solved by reloading the page.

**Comment by rafariossaa** [comment]
Let's see how stable it becomes after #6234 is solved.
