### ISSUE TITLE
[bitnami/fluentd] Set custom terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by adrian-catana** [bitnami/charts#6313]
**Which chart**:
bitnami/fluentd

**Is your feature request related to a problem? Please describe.**
The default 30 seconds are just not enought for us for all the buffers to be sent on termination, is there a way to set a custom terminationGracePeriodSeconds?

**Describe the solution you'd like**
exposing terminationGracePeriodSeconds as a variable to both aggregator and forwarder

**Comment by miguelaeh** [comment]
Hi @adrian-catana ,
Please feel free to send a PR adding it
