### ISSUE TITLE
[bitnami/nginx-ingress-controller] Nginx ingress chart with memcached for distributed rate limit

### ISSUE THREAD

**Issue by radoslav-stefanov** [bitnami/charts#6315]
Hello,

Does the Nginx Ingress helm chart support rate limiting using memcached? https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#global-rate-limit

I can't find anything related to it in docs.

For some reason I can't make it work while the regular rate limiting works fine.

`2021/05/07 12:26:55 [error] 181#181: *8831 lua entry thread aborted: runtime error: ...ua/lib/lua/5.1/resty/global_throttle/store/memcached.lua:1: module 'resty.memcached' not found:`

Thanks!

**Comment by migruiz4** [comment]
Hi @radoslav-stefanov,

Thank you for letting us know about your issue. Looks like the image `bitnami/nginx-ingress-controller` is missing the module [resty.memcached](https://github.com/openresty/lua-resty-memcached) which is necessary to use Memcached global for rate limiting.

I have created an internal task to add it as soon as possible.

I will keep you updated.

**Comment by radoslav-stefanov** [comment]
Thanks @migruiz4!

**Comment by radoslav-stefanov** [comment]
Hi guys,

Do you have any plans in adding the resty.memcached? I am considering to modify myself if it cant be done this year.

Thanks! :)

**Comment by migruiz4** [comment]
Hi @radoslav-stefanov,

I'm sorry for the late response. We are a small team that has to prioritize this feature along with other tasks and couldn't find the time to fix it. 

I will try to push this and see if we can find a slot during the next weeks, but I can not give an ETA at the moment.

**Comment by carrodher** [comment]
Unfortunately, after evaluating the addition of this feature internally, we didn't consider it to be addressed in the short/mid-term. As pointed out before, we are a small team in charge of maintaining different apps so we should select where to put effort.

Any PR is welcome for the Helm chart or container image in order to support new features, the team will be happy to review them and provide feedback.
