### ISSUE TITLE
Grafana pod CrashLoopBackOff periodically

### ISSUE THREAD

**Issue by debu99** [bitnami/charts#6321]
**Which chart**:
Bitnami Grafana 5.2.11

**Describe the bug**
Three 3 Grafana pod in 3 different EKS cluster crash at almost the same time, they are using external RDS as the database and prometheus as the data source, and I checked the event log the pod is due to healthcheck failed, not OOM

**To Reproduce**
Tried to setup on 3 clusters, they crash at the same time?! i increased the resource usage but they event don't use that much resource.
```
  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 800m
      memory: 2048Mi
```

**Expected behavior**
The pod should not crash

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  Did you check the logs ? Is it happening to the 3 pods at the same time ? How long does it take to crash from the deployment ? Is it immediate or does it take several hours/days/.. ?

**Comment by debu99** [comment]
it took server hours, sometimes several times a time, average I think once per day, I don't collect grafana logs, but I collect K8s events, from the events I can see it is because the healthcheck failure, but the funny thing is that i receive the alerts for 3 clusters almost at the same time

**Comment by rafariossaa** [comment]
Could you collect the grafana logs too ? That would be very helpful.

**Comment by debu99** [comment]
i tried on one K8s, and there is not new logs in the last few minutes, looks like the grafana process already stop, I will try to enable debug log

**Comment by debu99** [comment]
I got the issue, i use argocd for k8s management, when there is configuration change for components in k8s, even that is not related with grafana, the argocd found grafana configuration drift and re-deployed grafana, I am not sure why other application doesn't have this issue

**Comment by debu99** [comment]
looks there are multiple rs are created for grafana, but grafana deployment and grafana-image-renderer don't change

![image](https://user-images.githubusercontent.com/25805758/117825256-c20c5900-b2a1-11eb-98a1-da377193a377.png)

**Comment by debu99** [comment]
due to the random password issue
