### ISSUE TITLE
[bitnami/redis] Nodes do not start with ipv6+ipv4 addresses assigned

### ISSUE THREAD

**Issue by aureus1** [bitnami/charts#6329]
**Which chart**:
bitnami/redis, 14.1.1

**Describe the bug**
We use multis to assign ipv6+ipv4 interfaces to pods.  Nodes fail to start, continually logging a message of:
`WARN  ==> redis-test-headless.default.svc.cluster.local does not contain the IP of this pod: 2620:aa:0:fef9:1000:cfcf:1:ed78 172.16.237.138`

It looks like this is due to how the grepping for the node ip is set up in start-node.sh.  hostname -i returns in a format of "ipv6_ip ipv4_ip" in the case that both interfaces are configured.  Whereas getent ahosts only shows the ipv4 interface.

Example:
```
I have no name!@redis-test-node-0:/opt/bitnami/scripts/start-scripts$ hostname -i
2620:aa:0:fef9:1000:cfcf:1:6759 172.16.103.103
I have no name!@redis-test-node-0:/opt/bitnami/scripts/start-scripts$ getent ahosts "$HEADLESS_SERVICE"
172.16.103.103  STREAM redis-test-headless.default.svc.cluster.local
172.16.103.103  DGRAM
172.16.103.103  RAW
172.16.103.118  STREAM
172.16.103.118  DGRAM
172.16.103.118  RAW
172.16.78.80    STREAM
172.16.78.80    DGRAM
172.16.78.80    RAW
```

Hence the grep fails, and it never attempts to actually start redis

**To Reproduce**

1. Set up kubernetes in dual-stack mode, ensure that newly created pods are assigned an ipv4 and ipv6 interface
2. execute `helm install redis-test --set "master.persistence.enabled=false,replica.persistence.enabled=false,usePassword=false,sentinel.enabled=true,sentinel.masterSet=mymaster,cluster.slaveCount=3" --version 14.1.1 bitnami/redis`
3. Pod fails to start, kubectl logs will show warning message

**Expected behavior**
redis and sentinel should both start successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

It seems that the issue is here

```
        if [[ -z "$(getent ahosts "$HEADLESS_SERVICE" | grep "^${myip}" )" ]]; then
```

If we remove the `^`, that should work I believe. Could you try changing that in scripts-configmap.yaml and let us know if that works? If so, we would create a PR.

**Comment by aureus1** [comment]
> If we remove the `^`, that should work I believe. Could you try changing that in scripts-configmap.yaml and let us know if that works? If so, we would create a PR.

Turns out the fix was a *little* more complex than that.  There were a few more assumptions in the charts that needed to be corrected (like "hostname -i" not being used directly for "ipv4 address of this node").  Pull request opened with a fix.

**Comment by javsalgar** [comment]
Thank you so much! We will take a look to it and provide feedback :D
