### ISSUE TITLE
[bitnami/redis-cluster] helm-v2 can not deploy bitnami/redis-cluster.I want to deloy on helm v2. only deploy in v3 is so bad design

### ISSUE THREAD

**Issue by felix0080** [bitnami/charts#6332]
**Which chart**:
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by carrodher** [comment]
Thanks for creating this issue. Unfortunately, only Helm v3 is supported, please take a look at this issue where the different reasons behind this decision are described https://github.com/bitnami/charts/issues/3867

**Comment by felix0080** [comment]
thank you . I have solve this problem but I belive there are still people who have this problem

**Comment by carrodher** [comment]
Thanks for letting us know, as this is something we can't do anything else since the Helm version is a requirement for this project, I'm closing the issue.
