### ISSUE TITLE
[bitnami/rabbitmq] commonAnnotations in values

### ISSUE THREAD

**Issue by Avaar0032** [bitnami/charts#6334]
**Which chart**:
bitnami/rabbitmq: 8.13.1

**Is your feature request related to a problem? Please describe.**
I am trying to make helm chart with myapp which has rabbitmq and redis as dependencies, and rabbitmq, redis must be started when myapp pod created. I add redis to helm pre-install hook through adding commonAnnotations field in values, but in rabbitmq chart where is no such field. There is field podAnnotations but it sets on statefullset pod and i cannot manage with it statefullset creation order. Is there any reason why you not adding commonAnnotations field to rabbitmq chart like in redis or postgresql charts?

**Describe the solution you'd like**
Add commonAnnotations to values.yaml which apply to all rabbitmq resources.

**Comment by alemorcuq** [comment]
Hi, @Avaar0032.

We can add support for commonAnnotations in the RabbitMQ chart as we do in other charts. Are you interested in contributing with a PR?

**Comment by Avaar0032** [comment]
Thank you for response!
I create PR #6359 with commonAnnotations.

**Comment by alemorcuq** [comment]
Thank you!
