### ISSUE TITLE
[bitnami/prestashop] Health check fails on other languages

### ISSUE THREAD

**Issue by FJEANNOT** [bitnami/charts#6337]
**Which chart**:
bitnami/prestashop, version 13.1.9

**Describe the bug**
When selecting an other language than english, the chart fails to deploy because the path /login used for the healthcheck is replaced by the word in the language (for instance, the login path is /connexion in french)

**To Reproduce**

Deploy the chart with the parameter prestashopLanguage="fr"

**Expected behavior**
Health check success and pod get to a healthy state

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
A quickfix is to edit the chart probes in the values file to change the path from /login to /

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. We will work changing the probe path to `/`. As you are already aware of the issue, would you like to submit a PR fixing it? We are open for contributions :D
