### ISSUE TITLE
[bitnami/jupyterhub] wrong template path in templates/NOTES.txt line 11

### ISSUE THREAD

**Issue by Tolya1** [bitnami/charts#6339]
**Which chart**:
bitnami/jupyterhub 1.4.0 (latest at the time of writing)

**Describe the bug**
 trying to deploy the Bitnami JupyterHub chart and *I think* there might be a bug in the Bitnami JupyterHub chart, in templates/NOTES.txt

Namely line 11:
echo "JupyterHub URL: http{{ if .Values.ingress.tls }}s{{ end }}://$HOSTNAME/"

The chart values sets up ingress in proxy.ingress.enabled: true which leaves the field ingress.tls undefined causing this error:

Error: Failed to render chart: exit status 1: Error: template: jupyterhub/templates/NOTES.txt:11:42: executing "jupyterhub/templates/NOTES.txt" at <.Values.ingress.tls>: nil pointer evaluating interface {}.tls

adding an additional key ingress.enabled=true fixes this but it's not in line with the documentation nor proxy chart templating logic.

**To Reproduce**
set proxy.ingress.enabled=true and then

1. Run a clean install using: helm3 install jupyterhub bitnami/jupyterhub --set proxy.ingress.enabled=true
2. Observe error

**Expected behavior**
Should install without any problems

**Version of Helm and Kubernetes**:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```
```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @Tolya1, you seem to be right as there is no `ingress:` object in the root values.yaml file, so instead of `.Values.ingress` it should be `.Values.proxy.ingress`. Since you found the bug, would you be up for sending a PR with the fix? Thanks!

**Comment by Tolya1** [comment]
Hey @marcosbc I have published a PR with this change. Hope I conformed to all of the guidelines, since this is my first github contribution :) Good day and thanks for the assist.
