### ISSUE TITLE
kube-prometheus -> nodeselector for node-exporter

### ISSUE THREAD

**Issue by malikumaliku** [bitnami/charts#6345]
In a mixed windows+linux cluster if using the chart kube-prometheus, node-exporter gets scheduled in a windows node.
The nodeSelector is only available for the other pods, but not for the exporter

**Comment by Mauraza** [comment]
Hi @malikumaliku,

if you are using values.yaml you can do something similar to this:
```yaml
node-exporter:
  nodeSelector: {}
```
or
```bash
helm install kube-prometheus bitnami/kube-prometheus --set node-exporter.nodeSelector.selector=value
```

**Comment by malikumaliku** [comment]
helm install kube-prometheus bitnami/kube-prometheus --create-namespace --namespace kube-prometheus --set operator.nodeSelector."kubernetes\\.io/os"=linux --set operator.nodeSelector."kubernetes\\.io/arch"=amd64 --set prometheus.nodeSelector."kubernetes\\.io/os"=linux --set prometheus.nodeSelector."kubernetes\\.io/arch"=amd64 --set alertmanager.nodeSelector."kubernetes\\.io/os"=linux --set alertmanager.nodeSelector."kubernetes\\.io/arch"=amd64 --set node-exporter.nodeSelector.selector=."kubernetes\\.io/os"=linux --set node-exporter.nodeSelector.selector=."kubernetes\\.io/arch"=amd64

fails with
Error: DaemonSet.apps "kube-prometheus-node-exporter" is invalid: spec.template.spec.nodeSelector: Invalid value: ".kubernetes.io/arch=amd64": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

**Comment by Mauraza** [comment]
Hi @malikumaliku,

you need to change:
`--set node-exporter.nodeSelector.selector."kubernetes\\.io/os"=linux --set node-exporter.nodeSelector.selector."kubernetes\\.io/arch"=amd64` 
to 
`--set node-exporter.nodeSelector."kubernetes\\.io/os"=linux --set node-exporter.nodeSelector."kubernetes\\.io/arch"=amd64`

The word selector is no need it, `.selector=value` was an example.

**Comment by malikumaliku** [comment]
it owrks
