### ISSUE TITLE
connection timed out on helm repo add "bitnami" https://charts.bitnami.com/bitnami

### ISSUE THREAD

**Issue by houstondapaz** [bitnami/charts#6346]
**Which chart**:
All charts

**Describe the bug**
When I try to add bitnami chat to my helm repo, after a long period, helm return read: connection timed out
**To Reproduce**

1. exec `repo add "bitnami" https://charts.bitnami.com/bitnami`
2. Wait...
3. See error `Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: read tcp 172.28.127.26:49952->13.226.51.9:443: read: connection timed out`

**Expected behavior**
Bitnami repo added to my repos

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.4900", GitCommit:"2812f9fb0003709fc44fc34166701b377020f1c9", GitTreeState:"clean", BuildDate:"2021-03-19T09:19:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

It was working about 3 days ago

**Comment by migruiz4** [comment]
Hi @houstondapaz,

Could you please double-check it is not a connectivity issue in your host?

Maybe you have something restricting your outgoing traffic that is blocking your connection (firewall block, outbound rules, etc.).

**Comment by houstondapaz** [comment]
Hi @migruiz4 , thanks for reply

When I call `curl https://charts.bitnami.com/bitnami` the server responds, the timeout occurs only I call by helm

I'm using WSL2 on windows 10, and this issue occurs at both

**Comment by migruiz4** [comment]
I'm sorry for the late response.

I still think this issue may be caused by some network-related issue in the connection between your host and the helm repository as if it were an issue with the repository itself many users would be reporting the same problem.

I found this issue that may be related to yours: https://github.com/helm/helm/issues/4293

**Comment by houstondapaz** [comment]
The problem was my connectivity, when I use 1.1.1.1 DNS (cloudflare) the route stop to work, changing to 8.8.8.8 DNS it is works

thanks for the replies
