### ISSUE TITLE
Company Official Website Shut Down

### ISSUE THREAD

**Issue by EBCMED** [bitnami/charts#6351]
Dear Bitnami,
Our company official website: [www.ebcmed.com](url) has been closed abruptly, during the updates of plugins, and we don't have access to the websites currently. When we use SSH to login and see an index.php file in the plugin folder. We don't know why?
Could you please kindly solve this issue?
Thanks.
EBCMED

**Comment by carrodher** [comment]
Hi, in this GitHub repo we provide support about Helm Charts, if you are using a single VM or any other Bitnami product different than Helm Charts or container images, please, can you create a ticket in our [community support forum](https://community.bitnami.com/)?

If you are using a Helm Chart, can you provide more information about it using the following template?

> **Which chart**:
> The name (and version) of the affected chart
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Version of Helm and Kubernetes**:
> 
> - Output of `helm version`:
> 
> ```
> (paste your output here)
> ```
> 
> - Output of `kubectl version`:
> 
> ```
> (paste your output here)
> ```
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by EBCMED** [comment]
Sorry, we did it at the forum, but no response. Is there anyone can help it? Thanks. EBCMED

**Comment by carrodher** [comment]
Hi, our support team provides support within 24 hours in business days; I just saw an answer in the ticket, can you check it?. I will close this issue since the support is being provided in a different place. Thanks.
