### ISSUE TITLE
[bitnami/postgresql-ha] postgresql-ha validation didn't account for global parameters 

### ISSUE THREAD

**Issue by Librazy** [bitnami/charts#6352]
**Which chart**:
postgresql-ha@7.3.1

**Describe the bug**

A bit like https://github.com/bitnami/charts/pull/3460

https://github.com/bitnami/charts/pull/6280/files introduces password value validation but didn't account for global values.

**To Reproduce**

Install postgres-ha with
```yaml
global:
  postgresql:
    password: "somerandompassword"
    repmgrPassword: "anotherrandompassword"
  pgpool:
    adminPassword: "randompasswordagain"
```
it works.

Then upgrade the same chart using the same value and it fails with

<details>
<summary>password validation errors</summary>

```
Error: template: postgresql-ha/templates/NOTES.txt:68:4: executing "postgresql-ha/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $)>: error calling include: template: postgresql-ha/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'postgresql.password' must not be empty, please add '--set postgresql.password=$POSTGRESQL_PASSWORD' to the command. To get the current value:

        export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace "test" RELEASE-NAME-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

    'postgresql.repmgrPassword' must not be empty, please add '--set postgresql.repmgrPassword=$REPMGR_PASSWORD' to the command. To get the current value:

        export REPMGR_PASSWORD=$(kubectl get secret --namespace "test" RELEASE-NAME-postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

    'pgpool.adminPassword' must not be empty, please add '--set pgpool.adminPassword=$ADMIN_PASSWORD' to the command. To get the current value:

        export ADMIN_PASSWORD=$(kubectl get secret --namespace "test" RELEASE-NAME-postgresql-ha-pgpool -o jsonpath="{.data.admin-password}" | base64 --decode)

```
 </details>

Or simply do a `helm template --is-upgrade` with global values will reproduce it.

**Expected behavior**

It installs and upgrades.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this.
  I am creating an internal task to look for the best approach to address this in our charts.
  I can not provide an ETA, but we will come back as soon as we have news.

**Comment by B3arp** [comment]
Any update on this?

**Comment by Kaelten** [comment]
So we don't have the ability to upgrade this reliabily then?  How could this be okay for almost a year?

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
