### ISSUE TITLE
[Bitnami/Moodle]Does Moodle have any Volume requirements?

### ISSUE THREAD

**Issue by hanleirx** [bitnami/charts#6356]
**Which chart**:
Moodle:latest

**Is your feature request related to a problem? Please describe.**

I want to know whether Moodle have any Volume requirements. Because when I use block storage with ReadWriteOnce, it can run successfully but not support many pods.
So I changed the volume to NFS and object storage with ReadWriteMany mode. Firstly I just run one pod, but it can't be running and restart always.
I don't know why and how to deal with it. Because there is no error in my log. Thanks!

```yaml
[38;5;6mmoodle [38;5;5m09:23:28.38 [0m
[38;5;6mmoodle [38;5;5m09:23:28.38 [0m[1mWelcome to the Bitnami moodle container[0m
[38;5;6mmoodle [38;5;5m09:23:28.38 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-moodle[0m
[38;5;6mmoodle [38;5;5m09:23:28.39 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-moodle/issues[0m
[38;5;6mmoodle [38;5;5m09:23:28.39 [0m
[38;5;6mmoodle [38;5;5m09:23:28.39 [0m[38;5;2mINFO [0m ==> ** Starting Moodle setup **
[38;5;6mmoodle [38;5;5m09:23:28.42 [0m[38;5;2mINFO [0m ==> Configuring the HTTP port
[38;5;6mmoodle [38;5;5m09:23:28.44 [0m[38;5;2mINFO [0m ==> Configuring the HTTPS port
[38;5;6mmoodle [38;5;5m09:23:28.47 [0m[38;5;2mINFO [0m ==> Configuring PHP options
[38;5;6mmoodle [38;5;5m09:23:28.49 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_CLIENT_* env vars
[38;5;6mmoodle [38;5;5m09:23:28.52 [0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
[38;5;6mmoodle [38;5;5m09:23:28.57 [0m[38;5;2mINFO [0m ==> Ensuring Moodle directories exist
[38;5;6mmoodle [38;5;5m09:23:28.59 [0m[38;5;2mINFO [0m ==> Trying to connect to the database server
[38;5;6mmoodle [38;5;5m09:23:28.61 [0m[38;5;2mINFO [0m ==> Running Moodle install script
```

**Comment by juan131** [comment]
Hi @hanleirx 

As it's explained in the "Prerequisites" section of the chart, you need PV provisioner support to run the chart:

- https://github.com/bitnami/charts/tree/master/bitnami/moodle#prerequisites

Also, to scale and have multiple replicas, you must use "ReadWriteMany" volumes (e.g. using NFS). In the past we wrote an article explaining how to scale WordPress using a NFS provisioner, see:

- https://docs.bitnami.com/tutorials/deploy-applications-nfs-kubernetes

The same article is applicable replacing WordPress with Moodle.

**Comment by hanleirx** [comment]
OK, thx
