### ISSUE TITLE
Deleting DAG runs through the UI causes incomplete deletion of DAG runs details that affect tasks logging

### ISSUE THREAD

**Issue by darthale** [bitnami/charts#6357]
**Which chart**:
bitnami/airflow, version 2.0.2

**Describe the bug**
When deleting a DAG run through the Web UI, the entries in the table task_instance (Airflow DB) don't get deleted. 

I have noticed this whilst testing the logging to S3. When the DAG runs the first time, the logs are generated and stored to S3 (and Airflow UI) successfully. 
When the DAG run is deleted and the DAG runs again, the logs are not generated. 

I did some debugging and I have noticed that deleting the DAG run through the UI doesn't delete the entries for the tasks in the task_instance table. Deleting those entries manually, before the DAG runs again, has fixed the logging problem (logs are written again to S3 and UI). 

**To Reproduce**

1. Run a DAG once
2. Check that the logs have been written
3. Delete the DAG run
4. Check that no log has been written

**Expected behavior**

Deleting a DAG run through the UI should re-trigger the DAG run and the logs for the tasks in that run should be written to the destination that have been setup.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I wonder if this is bitnami/airflow chart problem or else a problem that should be raised in apache/airflow repo directly.

**Comment by juan131** [comment]
Hi @darthale 

> I wonder if this is bitnami/airflow chart problem or else a problem that should be raised in apache/airflow repo directly.

Taking a look to the description of the issue I have the same feeling. I don't think this is related to our packaging but a limitation in Airflow instead.

I also noticed you opened [this issue](https://github.com/apache/airflow/issues/15818) in Airflow. It seems Airflow developers already provided you a workaround.

**Comment by darthale** [comment]
hey @juan131, it is indeed. I'm going to close this bug if you don't mind?

**Comment by juan131** [comment]
Sure, let's close it.
