### ISSUE TITLE
no ingress in mongodb chart, vs https://github.com/helm/charts/blob/master/stable/mongodb/templates/ingress.yaml

### ISSUE THREAD

**Issue by korenlev** [bitnami/charts#6358]
**Which chart**:
mongodb

**Describe the bug**
no ingress in mongodb chart, vs https://github.com/helm/charts/blob/master/stable/mongodb/templates/ingress.yaml

**To Reproduce**

1. look at the chart

**Expected behavior**
ingress available

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by korenlev** [comment]
https://github.com/helm/charts/tree/master/stable/mongodb notes deprecated and suggestion to move to bitmani, but birmani mongodb has no ingress option, only exposing the service internally to the cluster

**Comment by korenlev** [comment]
also per README : https://github.com/bitnami/charts/tree/master/bitnami/mongodb : "his chart has been tested to work with NGINX Ingress" but it has no ingress.yaml nor example of a working ingress values

**Comment by juan131** [comment]
Hi @korenlev 

This chart used to have the possibility of exposing MongoDB through an Ingress rule. But that feature was dropped in the PR below where I completely refactored the way to expose MongoDB:

- https://github.com/bitnami/charts/pull/2918

Find the the reasons behind this decision in the PR description.

You can also find the information about how to expose MongoDB outside the cluster in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#exposure-parameters

> also per README : https://github.com/bitnami/charts/tree/master/bitnami/mongodb : "this chart has been tested to work with NGINX Ingress" but it has no ingress.yaml nor example of a working ingress values

Thanks for bringing this up! This is something that I clearly missed to remove from the **README.md** when I refactored the chart. I will remove that.

**Comment by korenlev** [comment]
Ingress no longer supported since the mentioned PR, readme updated

**Comment by aventi-lasith** [comment]
Hi,
Sorry for re-opening this. Is there a way to connect to the replicaset using seedlist (mongodb+srv)?
