### ISSUE TITLE
pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156

### ISSUE THREAD

**Issue by alion-wen** [bitnami/charts#6368]
E0514 11:32:40.467128      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:32:41.673305      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:32:44.246688      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:32:50.379676      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:32:59.138668      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:33:12.168873      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:33:51.827545      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)
E0514 11:34:30.340998      13 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.0/tools/cache/reflector.go:156: Failed to watch *v1.KongCredential: failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)

When I was installing KONG, I encountered this log, which caused the kong-ingress-controller to be in an abnormal state all the time. Could you please help me to see what the problem is? thank you

**Comment by alvneiayu** [comment]
hi @alion-wen 

It seems that you don't have the crds already installed. Could you share with me the crds installed?

```
kubectl get crds
```

Verify that you have the kong crds installed. Moreover, share with me your k8s version:

```
kubectl version
```

I think that I have an idea why you are having problems and I need some information.

Thanks a lot

Álvaro
