### ISSUE TITLE
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.

### ISSUE THREAD

**Issue by manjunath-vuyyuru** [bitnami/charts#6375]
Deployed Kafka helm chart with 3 replicas and I see the 1st replica kafka-0 works fine, But kafka-1 and kafka-2 fails with error 
```
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
-----------------
As per my understanding if there is a issue with certificates it should fail on all 3 pods, but it fails only kafka-1 and kafka-2 but works fine on kafka-0  which is this issue.
------------------
kafka-0                                   1/1     Running            0          34m
kafka-1                                   0/1     CrashLoopBackOff   6          7m20s
kafka-2                                   0/1     CrashLoopBackOff   6          7m
---------------------
```

[new.zip](https://github.com/bitnami/charts/files/6487897/new.zip)

I have created the certs using this script  kafka-generate-ssl.sh and created copy of kafka.keystore.jks of 3 more using simple cp command has these 2 files
1) kafka-1.keystore.jks
2) kafka-2.keystore.jks

Correct if I am doing here, Suggest me how to create the 3 keytstore.jks files using this script.

**Comment by manjunath-vuyyuru** [comment]
Helm install works fine only when I deploy 1 Broker pod per installation but when we have replicas it is failing 

This is the values.yaml I am using 

[values.yaml.zip](https://github.com/bitnami/charts/files/6487908/values.yaml.zip)

**Comment by miguelaeh** [comment]
Hi @manjunath-vuyyuru ,

You should have created 3 keystore files, from `kafka-0.keystore` to `kafka-2.keystore` I.e. one per kafka broker. The example [here](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper) showed only the creation when you have 2 brokers.
After that, create the secret as explained in the guide above and provide the values explained in the guide adapted to your case.

**Comment by manjunath-vuyyuru** [comment]
@miguelaeh,

I am creating the keystore and truststore using this script - https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh

After executing the script I got 1 keystore and 1 truststore file, Later I have copied the kafka.keystore.jks as kafka-0.keystore.jks and kafka-1.keystore.jks and created the secret key using this command as per the link https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper
kubectl create secret generic kafka-jks --from-file=./kafka.truststore.jks --from-file=./kafka-0.keystore.jks --from-file=./kafka-1.keystore.jks

**When I start the pod I am seeing these errors** 

Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.

**Comment by miguelaeh** [comment]
Hi @manjunath-vuyyuru ,
That's correct except that you also need to copy it one more time to have `kafka-2.keystore.jks` since you have 3 brokers.

Apart from that you have to provide the parameters described at [the guide](https://github.com/bitnami/charts/tree/master/bitnami/kafka#enable-security-for-kafka-and-zookeeper) when installing the chart, are you providing them?
