### ISSUE TITLE
[redis-cluster] If persistence is not enabled (with the option set to false) when PODS are removed, the newly generated PODS cannot join the cluster.

### ISSUE THREAD

**Issue by felix0080** [bitnami/charts#6380]
**Which chart**:
The name (and version) of the affected chart
redis-cluster
**Describe the bug**
If persistence is not enabled (with the option set to false) when PODS are removed, the newly generated PODS cannot join the cluster.
**To Reproduce**

1. create cluster redis in  no persistence mode
2. delete a pod 
3. exec in pod 
4. See cluster nodes

**Expected behavior**
can auto join the cluster 
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"archive", BuildDate:"2021-04-12T12:27:27Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

I'm afraid that, by the way the cluster initialization works (using `redis cluster create`, this is something expected. For the solution to have resiliency it is necessary that persistence is enabled. The case where persistence is not enabled is more for basic testing purposes.

**Comment by felix0080** [comment]
> Hi,
> 
> I'm afraid that, by the way the cluster initialization works (using `redis cluster create`, this is something expected. For the solution to have resiliency it is necessary that persistence is enabled. The case where persistence is not enabled is more for basic testing purposes.

Thank you very much!
