### ISSUE TITLE
Scheduler Unavalaible when Postgresql Restarts

### ISSUE THREAD

**Issue by armandleopold** [bitnami/charts#6387]
**Which chart**:
Airflow

**Describe the bug**
We have the error message : "Scheduler is unavailable" on the airflow frontend

**To Reproduce**
1. Install the default bitnami/airflow chart
2. Restart the postgresql database
3. Check the frontend

**Expected behavior**
Scheduler reconnect to postgresql db an continues to run tasks

**Additional context**
It may be interesting to add a health check to the scheduler & web pod. That check le liveness of the postgresql pod.
If it has been unavailable or restarted, restart scheduler & frontend.

**Comment by Mauraza** [comment]
Hi @armandleopold,

When the connection with the database is lost an error occurs. And this error causes airflow to be unable to function normally. Even if you have liveness airflow, airflow will still fail.

Maybe is more interesting to change the database with a deployment with a pod to a database in HA.

**Comment by armandleopold** [comment]
Ok merci @Mauraza ! 
We will try  this  [https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha)
