### ISSUE TITLE
dump.rdb file is exist when RDB persistence disabled (default installation)

### ISSUE THREAD

**Issue by kuzm1ch** [bitnami/charts#6389]
**Which chart**:
redis

**Describe the bug**
dump.rdb file exists when RDB persistence disabled on fresh installation

**To Reproduce**
1. Install redis `helm install redis bitnami/redis`
2. Execute shell on it `kubectl exec -it redis2-master-0 /bin/bash`
3.  Check data dir
```
I have no name!@redis-master-0:/$ ls /data
appendonly.aof	dump.rdb
I have no name!@redis-master-0:/$ ls -la  /data
total 16
drwxrwxrwx 2 root root 4096 May 17 13:06 .
drwxr-xr-x 1 root root 4096 May 17 13:06 ..
-rw-r--r-- 1 1001 root  818 May 17 13:17 appendonly.aof
-rw-r--r-- 1 1001 root  175 May 17 13:06 dump.rdb
```

**Expected behavior**
If RDB persistence is disabled then my **assumption** that there should be no dumb.rdb file as aof is in use or documentation/comments in values.yaml should be extended.

**Additional context**
Why I took attention to this. 
```
I have no name!@redis-master-0:/$ cat /opt/bitnami/redis/etc/redis.conf 
# User-supplied configuration:
# Enable AOF https://redis.io/topics/persistence#append-only-file
appendonly yes
# Disable RDB persistence, AOF persistence already enabled.
save ""I have no name!@redis-master-0:/$ ls -lha /data
total 6.0G
drwxrwsrwx 2 root 1001 4.0K May 17 06:11 .
drwxr-xr-x 1 root root 4.0K May 15 18:54 ..
-rw-r--r-- 1 1001 1001 3.3G May 17 08:35 appendonly.aof
-rw-r--r-- 1 1001 1001 2.8G May 15 18:58 dump.rdb
```
RDB file is quite big on dev instance and maybe it shouldn't exist at all and save some space on disk.
I am not pointing this as an example(focus on a fresh install) because probably somebody could save rdb file manually via redis-cli or api.

**Comment by kuzm1ch** [comment]
https://redislabs.com/ebook/part-2-core-concepts/chapter-4-keeping-data-safe-and-ensuring-performance/4-1-persistence-options/4-1-3-rewritingcompacting-append-only-files/

**Comment by shlomitubul** [comment]
same here. I reviewed sentinel & redis config but didn't understand the root cause

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
