### ISSUE TITLE
[bitnami/template] readme tool is not public

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#6391]
**Which chart**:
The new chart template
**Describe the bug**
The new chart template links to https://github.com/bitnami-labs/readmenator which is not public and has retired the old table.
**To Reproduce**
https://github.com/bitnami/charts/tree/master/template/CHART_NAME
**Expected behavior**
The tooling is accessible

**Comment by carrodher** [comment]
Sorry, we are still following an internal review & approval process to make it public, in the meantime the table should be created manually as before, just copying it from an existing chart and updating the parameters.

**Comment by MaxRink** [comment]
Do you have any eta for that?

**Comment by carrodher** [comment]
We just make it public using a different name, you can find it here: https://github.com/bitnami-labs/readme-generator-for-helm

In the same way, we updated the scaffolding for new charts pointing to the new URL. Thanks for your patience
