### ISSUE TITLE
[Moodle] Fully Support Portuguese Language installation by Kubernetes

### ISSUE THREAD

**Issue by wellyngtonteixeira** [bitnami/charts#6393]
**How config full support language in moodle kubernetes image?** I tried install with portuguese language but in the text month (Calendar module) don't work. Someone can help me?

**Comment by miguelaeh** [comment]
Hi @wellyngtonteixeira ,
Could you please give more information about what are you doing, which steps didi you follow, the results obtained, etc.

Also please add a descriptive title to the issue.
