### ISSUE TITLE
kubeapps chart fails installation due to missing pinnipedProxy.service.port

### ISSUE THREAD

**Issue by dlaloue-vmware** [bitnami/charts#6398]
**Which chart**:
kubeapps  7.0.0

**Describe the bug**
when running helm install, with pinnipedProxy.enable true in values.yaml, the installation fails as the value pinnipedProxy.service.port does not exist.

**To Reproduce**
update values file to have pinnipedProxy.enable set to true
do a helm install

**Expected behavior**
expected chart to be installed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
the section pinnipedProxy has a property "containerPort" similar to how it is done in other pods of the chart.
some files are using that containerPort property, but other files (frontend service.yaml, frontend configmap.yaml and kubeops deployment.yaml) are referencing pinnipedProxy.service.pod instead.

there is a workaround which is to add the service/port manually.

**Comment by javsalgar** [comment]
Hi!

Thank you for using Bitnami. I see that there is a PR that should fix the issue. We expect to merge it very soon.
