### ISSUE TITLE
Improve documentation for the auth.tls section about keystore/truststore creation

### ISSUE THREAD

**Issue by dlaloue-vmware** [bitnami/charts#6399]
**Which chart**:
keycloak   v 3.0.0

**Is your feature request related to a problem? Please describe.**
In the auth.tls section, regarding configuring the keystore/truststore there is a link pointing to documentation on the keycloak github project.
the documentation is not generic enough (it references OpenShift) and is also obsolete. it uses the deprecated format of jks instead of using pkcs12 and it is also showing how to create certificates with common name instead of SAN certificates. Common name based certificates have been deprecated a while ago and are not accepted by some servers and browsers anymore.
following this documentation was a painful process and in the end it was a waste of time as the certificate generated was not compatible.

**Describe the solution you'd like**
i can see different options:
 - point to a more up-to-date documentation from keycloak
 - point to an external documentation/blog/... with more up-to-date instructions
 - point to a bitnami written documentation
 - remove the link so users do their own research

**Describe alternatives you've considered**
alternative is to just remove the link and force users to do their own research

**Comment by juan131** [comment]
Hi @dlaloue-vmware 

Thank so much for reporting this! I guess you're referring to the line below, am I right?

- https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L123

It seems we're also referring to these docs at https://github.com/bitnami/bitnami-docker-keycloak#tls-encryption

I guess we could point to [these docs](https://www.keycloak.org/docs/latest/server_installation/#_truststore), although they don't provide detailed instructions to generate the keystore/truststore.

---

Did you open an issue at https://github.com/keycloak/keycloak-documentation/issues claiming they have deprecated docs?

**Comment by dlaloue-vmware** [comment]
correct, i was referring to the link in values.yaml.

and no, i did not open an issue with the keycloak project (still new to open source projects, so going step by step :-)

**Comment by juan131** [comment]
All right @dlaloue-vmware !!

I just updated the links to point to https://www.keycloak.org/docs/latest/server_installation/#_truststore

In any case, I'll mark this issue to be reviewed by the docs team, just in case they have bandwidth to create some guide at our [docs site](https://docs.bitnami.com/kubernetes/) with accurate instructions to create the keystore and truststore. Thanks for reporting it!

I proceed to close the ticket as "solved" but please feel free to reopen it if you require further help.

**Comment by dlaloue-vmware** [comment]
the link you have referenced is for outbound SSL, while the issue is about server SSL.
i think the following linke would be a better fit:  https://www.keycloak.org/docs/latest/server_installation/#_setting_up_ssl

**Comment by juan131** [comment]
Done @dlaloue-vmware !! I just updated to point to https://www.keycloak.org/docs/latest/server_installation/#_setting_up_ssl
Thanks for the feedback!
