### ISSUE TITLE
influx showing 500 time out error

### ISSUE THREAD

**Issue by mohanagandlla** [bitnami/charts#6400]
Hi team I am getting this error daily and the data is coming from Prometheus write
```
ts=2021-05-18T03:55:28.145581Z lvl=error msg="[500] - \"timeout\"" log_id=0UAZIvxG000 service=httpd
```

**Comment by rafariossaa** [comment]
Hi,
  Could you provide more information ? Which is your set up ? which versions are you using ? And any other thing you consider relevant to try to reproduce and debug the issue.

**Comment by mohanagandlla** [comment]
yes I am using influx 1.8 on kubernetes layer version 1.18 and I dint fount any bugs its just saying like the above error and after some time influxdb server is not responding until i restart the pod
