### ISSUE TITLE
InfluxDB 2 - Backup does not pull the right image

### ISSUE THREAD

**Issue by bartlomiejwulff** [bitnami/charts#6401]
Hello,

I think I have found a wrong declaration of the influxdb image inside the cronjob-backup.yaml file as linked below:

https://github.com/bitnami/charts/blob/2a547f9bdfe9319ea95dcbe553f1b20ebf202605/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml#L79

I believe the right value for the image for the container `influxdb-backup-dummy-container` should be `image: {{ include "influxdb.image" . }}` and not `image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"` as it does not work if you use a private registry:

```
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  Failed   31m (x1009 over 4h19m)  kubelet  Error: ImagePullBackOff
  Normal   BackOff  68s (x1141 over 4h19m)  kubelet  Back-off pulling image "hub.docker.com/bitnami/influxdb:2.0.6-debian-10-r0"
```  

The right image path should be:

`harbor.xxx.xxx.de/hub.docker.com/bitnami/influxdb:2.0.6-debian-10-r0`

**Comment by miguelaeh** [comment]
Thank you very much @bartlomiejwulff  for creating the PR, we will review and continue the conversation there 👏
