### ISSUE TITLE
[discourse] UPGRADE FAILED: cannot patch "discourse-redis-master" with kind StatefulSet

### ISSUE THREAD

**Issue by mattcg** [bitnami/charts#6410]
**Which chart**:

Discourse chart version 2.1.1

**Describe the bug**

Attempting to upgrade to the latest chart version (3.0.4) yields the following fatal error:

```
Error: UPGRADE FAILED: cannot patch "discourse-redis-master" with kind StatefulSet: StatefulSet.apps "discourse-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**To Reproduce**

1. Install Discourse chart 2.1.1
2. Attempt to upgrade to 3.0.4
3. See error

**Expected behavior**

The upgrade succeeds.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.13+rke2r1", GitCommit:"4c00c3c459261e8ff3381c1070ddf798f0131956", GitTreeState:"clean", BuildDate:"2020-12-15T17:44:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Additional context**

Using Rancher 2

**Comment by rafariossaa** [comment]
Hi, 
  Could you take a look to [this note ](https://github.com/bitnami/charts/tree/master/bitnami/discourse#user-content-to-300) ?
  There are breaking changes when upgrading to 3.0.0 due to redis subchart changes.

**Comment by mattcg** [comment]
> Could you take a look to [this note ](https://github.com/bitnami/charts/tree/master/bitnami/discourse#user-content-to-300) 

Thanks @rafariossaa. I looked at the note but it didn't help. The workaround was to delete the statefulSet so that the upgrade could go ahead.

**Comment by rafariossaa** [comment]
Hi,
  I am glad you were able to solve the issue.
  Thanks for sharing.
