### ISSUE TITLE
[bitnami/magento] 502 Bad Gateway using Ingress

### ISSUE THREAD

**Issue by mahgo** [bitnami/charts#6414]
**Which chart**:
Magento

**Describe the bug**
I'm having issues using the built in ingress, when using ingress.enabled=true and also setting ingress.hostname to my hostname.

I'm using the ingress-nginx/ingress-nginx chart as such:
```helm install nginx-ingress ingress-nginx/ingress-nginx \
    --namespace default \
    --set controller.replicaCount=2 \
    --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set controller.admissionWebhooks.patch.nodeSelector."beta\.kubernetes\.io/os"=linux \
    --set controller.service.loadBalancerIP="20.191.210.62" \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="magento"
```

When I describe the ingress, it says it is pointing to backend "magento:http (10.1.0.27:8080)", and also when I check the logs for the ingress controller it confirms that IP:
`Endpoints found for Service "default/magento": [{10.1.0.27 8080 &ObjectReference{Kind:Pod,Namespace:default,Name:magento-759b45f986-txb7q,UID:7d1ed40d-88f9-40fb-85b2-ba1bc449356a,APIVersion:,ResourceVersion:4210,FieldPath:,}}]`

However, when I check the service using `kubectl get services`, the IP listed under Cluster-IP is a different one (10.0.216.9), and none of the other services have that IP either. Is there something I'm missing or is it possible that the IP changed at some point?

The logs themselves also seem to point to not being able to find it:
```2021/05/19 06:18:21 [debug] 39#39: *936 http proxy status 404 "404 Not Found"
2021/05/19 06:18:21 [debug] 39#39: *936 http proxy header: "Date: Wed, 19 May 2021 06:18:21 GMT"
2021/05/19 06:18:21 [debug] 39#39: *936 http proxy header: "Content-Type: text/html"
2021/05/19 06:18:21 [debug] 39#39: *936 http proxy header: "Content-Length: 146"
2021/05/19 06:18:21 [debug] 39#39: *936 http proxy header: "Connection: keep-alive"
2021/05/19 06:18:21 [debug] 39#39: *936 http proxy header done
2021/05/19 06:18:21 [debug] 39#39: *936 lua header filter for user lua code, uri "/favicon.ico"
2021/05/19 06:18:21 [debug] 39#39: *936 code cache lookup (key='header_filter_by_lua_nhli_803cd74e9d568018c83d620326995b86', ref=-1)
2021/05/19 06:18:21 [debug] 39#39: *936 code cache miss (key='header_filter_by_lua_nhli_803cd74e9d568018c83d620326995b86', ref=-1)
2021/05/19 06:18:21 [debug] 39#39: *936 lua capture header filter, uri "/favicon.ico"
2021/05/19 06:18:21 [debug] 39#39: *936 headers more header filter, uri "/favicon.ico"
2021/05/19 06:18:21 [debug] 39#39: *936 HTTP/1.1 404 Not Found
```
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

I've checked other issues and it could be related to the header size. Could you check if you see in the logs a message similar to "upstream sent too big header while reading response header from upstream". If so, could you check if this works? https://andrewlock.net/fixing-nginx-upstream-sent-too-big-header-error-when-running-an-ingress-controller-in-kubernetes/#how-to-configure-the-nginx-ingress-controller

**Comment by mahgo** [comment]
Fantastic! That was the problem, and that fixed it. Thanks very much!
