### ISSUE TITLE
[bitnami/mysql] Write your my_custom.cnf file with the following content.

### ISSUE THREAD

**Issue by serg-bs** [bitnami/charts#6423]
**Which chart**:
bitnami/mysql 

**Is your feature request related to a problem? Please describe.**
I need add to replica some additional config 
```replicate-ignore-table=logtable```
or on master 
```
[mysqld]
max_allowed_packet=32M
```
like describe 
https://github.com/bitnami/bitnami-docker-mysql#step-1-write-your-my_customcnf-file-with-the-following-content

**Comment by miguelaeh** [comment]
Hi @serg-bs ,
Thank you very much for the PR we are already taking care of it.
