### ISSUE TITLE
[bitnami/rabbitmq] port 15674 is not accessable

### ISSUE THREAD

**Issue by webcane** [bitnami/charts#6427]
**Which chart**:
rabbitmq v.3.8.16
chart v.8.15.0

**Describe the bug**
stomp-ws port 15674 is not accessible if required rabbitmq plugins enabled and port exposed:

```
extraPlugins: "rabbitmq_stomp rabbitmq_web_stomp"
```
```
service:
  extraPorts:
    - name: stomp-ws
      protocol: TCP
      port: 15674
      targetPort: stomp-ws
    - name: stomp-tcp
      protocol: TCP
      port: 61613
      targetPort: stomp-tcp
```

**To Reproduce**

1. connect to one of pods in a cluster who have curl installed
2. run following command
```
curl -i -N http://my-app-rabbitmq.rq.svc:15674/rq/ws -H 'Connection: Upgrade' -H 'Upgrade: websocket'
```
3. See response
```
curl: (7) Failed to connect to my-app-rabbitmq.rq.svc port 15674: Connection refused
```

**Expected behavior**
websocket connection (using STOMP protocol) to rabbitmq is working. 
15674 port exposed and related endpoint is configured.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-dispatcher", GitCommit:"a39a896b5018d0c800124a36757433c660fd0880", GitTreeState:"clean", BuildDate:"2021-01-28T22:25:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The rabbitmq-ha installed before from the [stable](https://github.com/helm/charts/tree/master/stable/rabbitmq) helm chart did necessary job by simple configuration: 
```
rabbitmqSTOMPPlugin:
   enabled: true
rabbitmqWebSTOMPPlugin:
   enabled: true
```
Websockets (STOMP) was working and 15674 port was exposed and configured automatically. But stable chart is deprecated.

[bitnami](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq) chart have significant configuration changes and this is not completely clear how to get working `stomp-ws` with it.

**rabbitmq-deploy.sh**
```
...
helm version
helm repo add bitnami https://charts.bitnami.com/bitnami
if [[ $? -ne 0 ]]
then
  echo "ERROR Helm repo add failed."
  exit 5
fi

helm repo update

HELM_CMD="helm upgrade ${APP_NAME} bitnami/rabbitmq \
  --wait \
  --install \
  --timeout ${TIMEOUT} \
  --namespace \"${NAMESPACE}\" \
  --values rabbitmq-values.yaml \
  --set auth.username=\"${RMQ_USER}\" \
  --set auth.password=\"${RMQ_PASSWORD}\""

if [[ -z ${RABBITMQ_ERLANG_COOKIE} ]]
then
  echo "RABBITMQ_ERLANG_COOKIE not defined yet."
else
  HELM_CMD="$HELM_CMD --set auth.erlangCookie=\"${APP_NAME}-rabbitmq\""
fi

eval $HELM_CMD

if [[ $? -ne 0 ]]
then
  echo "ERROR Helm upgrade failed."
  exit 6
fi
```

**rabbitmq-values.yaml**
```
# https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml

plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s"

extraPlugins: "rabbitmq_stomp rabbitmq_web_stomp"

prometheus:
  exporter:
    enabled: false
  operator:
    enabled: false

replicaCount: 3

service:
  extraPorts:
    - name: stomp-ws
      protocol: TCP
      port: 15674
      targetPort: stomp-ws
    - name: stomp-tcp
      protocol: TCP
      port: 61613
      targetPort: stomp-tcp

resources:
  requests:
    cpu: 220m
    memory: 250Mi
  limits:
    cpu: 220m
    memory: 250Mi

## RabbitMQ containers' liveness and readiness probes.
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  enabled: false
  initialDelaySeconds: 180
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1
customReadinessProbe:
  exec:
    command:
      - sh
      - -c
      - rabbitmq-diagnostics -q check_running
  initialDelaySeconds: 60
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 20
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1
customLivenessProbe:
  exec:
    command:
      - sh
      - -c
      - rabbitmq-diagnostics -q check_running
  initialDelaySeconds: 60
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 6
  successThreshold: 1

loadDefinition:
  enabled: false

extraConfiguration: |-
  ##
  ## Web MQTT configuration:
  ##
  web_stomp.cowboy_opts.max_keepalive = 0
  web_stomp.cowboy_opts.max_header_value_length = 16000


extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "permissions": [
          {
            "user": "{{ .Values.auth.username }}",
            "vhost": "/",
            "configure": "^stomp-subscription-.*",
            "write": "^stomp-subscription-.*",
            "read": ".*"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }

ldap:
  enabled: false

```

**Comment by migruiz4** [comment]
Hi @webcane!

Thank you for reporting this issue and the detailed description.

Your `values.yaml` is missing an additional setting to configure the container ports. Adding the following should solve this issue:
```
extraContainerPorts:
    - name: stomp-ws
      containerPort: 15674
    - name: stomp-tcp
      containerPort: 61613
```

**Comment by webcane** [comment]
now looks better but not perfect.
I can connect to stomp-ws port but there is no answer

```
curl: (52) Empty reply from server
```

**Comment by migruiz4** [comment]
Hi @webcane,

I think your issue is caused by this settings in your configuration:

```
extraConfiguration: |-
  ##
  ## Web MQTT configuration:
  ##
  web_stomp.cowboy_opts.max_keepalive = 0
  web_stomp.cowboy_opts.max_header_value_length = 16000
``` 

Maybe setting `max_keepalive = 0` is causing connection to close before being established by clients.
Increasing that number to, for example, 200 as in the [web-stomp documentation example](https://www.rabbitmq.com/web-stomp.html) should fix the issue:
```
curl -i -N http://rabbit-rabbitmq.default.svc:15674/ws -H 'Connection: Upgrade' -H 'Upgrade: websocket'
HTTP/1.1 400 Bad Request
content-length: 0
date: Mon, 24 May 2021 12:40:25 GMT
server: Cowboy
```

**Comment by webcane** [comment]
@migruiz4 Hello Miguel, Thanks a lot for support! You was right about `max_keepalive`. This is required to initiate connection.

**Comment by migruiz4** [comment]
I'm glad it is now working. 

Happy to help!

**Comment by NicklasWallgren** [comment]
@migruiz4 How do we expose the added ports via the ingress?

I have defined `extraContainerPorts` and `extraPorts`, but only 15672 is available via ingress.

![image](https://user-images.githubusercontent.com/1784879/155529233-84d3a6d1-1515-49c6-82d9-14076cc909a1.png)

![image](https://user-images.githubusercontent.com/1784879/155529405-526b97a5-cb66-45f3-8f37-7195891d8bfd.png)

**Comment by NicklasWallgren** [comment]
I solved it by changing `service.type` to NodePort.

**Comment by migruiz4** [comment]
Hi @NicklasWallgren,

To expose additional ports via ingress, you will need to use the value `ingress.extraHosts` or `ingress.extraPaths` to modify the default `ingress.yaml`:

https://github.com/bitnami/charts/blob/6c698dfcf39233b54139661458f0813a8df60e6a/bitnami/rabbitmq/templates/ingress.yaml#L22-L45

For example, you can configure a different path in your ingress that used a different service port as backed.

**Comment by NicklasWallgren** [comment]
@migruiz4 Thanks for the reply. 

I tried with the following;
```
extraHosts:
    - name: ws.rabbitmq.10.144.100.38.nip.io
      path: /ws
      backend:
        serviceName: rabbitmq
        servicePort: 15674
```

But I cannot get it to work, the service port points to 15672 instead of 15674.

![image](https://user-images.githubusercontent.com/1784879/155554046-b3ccb250-68a1-46d8-83a7-127017828220.png)

**Comment by migruiz4** [comment]
I'm sorry for the late response @NicklasWallgren.

I'm sorry my previous answer wasn't very accurate, as the `extraHosts` value does not allow changing the backend port.
I have submitted this PR #9276 adding a new feature `extraRules`, that would allow the addition of ingress rules evaluated entirely as a template.

**Comment by NicklasWallgren** [comment]
@migruiz4 Great, thank you!

**Comment by Aurorxa** [comment]
@migruiz4 @migruiz4 i am sorry，i do not know how to use extraRules，please give me a example，thanks ！

**Comment by idasilva** [comment]
Hi there, i was looking for something like this, thanks, i could do this, see a exemplo:
```terraform
 ingress:
    enabled: true
    path: /
    ingressClassName: nginx
    hostname: ${var.managment_domain}
    tls: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    extraRules:
    - host: ${var.domain}
      http:
        paths:
        - backend:
            service:
              name: rabbitmq
              port:
                name: amqp
          path: /
          pathType: ImplementationSpecific
```
https://github.com/bitnami/charts/pull/9276

**Comment by Aurorxa** [comment]
@idasilva Thanks
