### ISSUE TITLE
need to add sidecar that know who is primary for any external access needs

### ISSUE THREAD

**Issue by korenlev** [bitnami/charts#6428]
https://github.com/combor/k8s-mongo-labeler-sidecar

will it be worth adding to the chart ?

**Comment by alvneiayu** [comment]
hi @korenlev 

If you need a sidecar and this solution applies in your use of case, you can try to use it with the chart and share with us the experience. We don't have experience with this project.

Let me know If I can help you with something else.

Thanks a lot

Álvaro

**Comment by korenlev** [comment]
Solution implemented, issue closed
