### ISSUE TITLE
AWS EKS with Seconday IP Range 100.64.0.0/10 - whitelist?

### ISSUE THREAD

**Issue by haarchri** [bitnami/charts#6432]
Hello,

we are using AWS EKS with Seconday IP Range 100.64.0.0/10 and we need to enable ssl-required: external - now we have the problem that in AWS EKS we using 100.64.0.0/10 as private - can you tell us how we whitelist 100.64.0.0/10 - any ideas ?

https://aws.amazon.com/de/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/
https://lists.jboss.org/pipermail/keycloak-user/2018-October.txt
https://lists.jboss.org/pipermail/keycloak-user/2016-November/008455.html

**Comment by carrodher** [comment]
Hi, I'm sorry but I don't know how this issue can be addressed from the Helm Chart point of view, can you try by asking in an AWS support forum or maybe in the support channels of the application itself? If it is something related the to the Helm Chart we can try to fix the issue, but in this case I am not sure if there is something to do from our side
