### ISSUE TITLE
support external access to MongoDB primary pod on a replica-set

### ISSUE THREAD

**Issue by korenlev** [bitnami/charts#6434]
**Which chart**:
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by miguelaeh** [comment]
Hi @korenlev ,
THank you for the PR we are already taking care of it

**Comment by korenlev** [comment]
Hi miguel, u mean the chart already allow service access to the primary ?
How ?

בתאריך יום ו׳, 21 במאי 2021, 11:03, מאת Miguel Ángel Cabrera Miñagorri ‏<
***@***.***>:

**Comment by miguelaeh** [comment]
Hi @korenlev ,
I mean a colleague is already reviewing the PR
