### ISSUE TITLE
[bitnami/nginx-ingress-controller] defaultBackend.podAnnotations breaks the chart

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#6439]
**Which chart**:
The name (and version) of the affected chart

`bitnami/nginx-ingress-controller`

**Describe the bug**

I wanted to add annotations to the pods:
```yaml
# This does not work
defaultBackend:
  podAnnotations:
    k8s.com/promtail-ignore: "true"

# This does work
podAnnotations:
  k8s.com/promtail-ignore: "true"
```
which leads to an error when running helm or helmfile:

```log
PATH:
  /usr/local/bin/helm
ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --reset-values (14 bytes)
  4: --allow-unreleased (18 bytes)
  5: nginx-ingress-ctrl-main (23 bytes)
  6: bitnami/nginx-ingress-controller (32 bytes)
  7: --version (9 bytes)
  8: 7.6.6 (5 bytes)
  9: --namespace (11 bytes)
  10: ingress-main (12 bytes)
  11: --values (8 bytes)
  12: /tmp/helmfile996300720/ingress-main-nginx-ingress-ctrl-main-values-7b78897698 (77 bytes)
  13: --values (8 bytes)
  14: /tmp/helmfile287465295/ingress-main-nginx-ingress-ctrl-main-values-f4db6c966 (76 bytes)
  15: --values (8 bytes)
  16: /tmp/helmfile510586466/ingress-main-nginx-ingress-ctrl-main-values-6986f6f7cb (77 bytes)

# [...]

Error: template: nginx-ingress-controller/templates/default-backend-deployment.yaml:23:23: executing "nginx-ingress-controller/templates/default-backend-deployment.yaml" at <include "nginx-ingress-controller.annotations" (dict "annotations" .Values.defaultBackend.podAnnotations "context" $)>: error calling include: template: no template "nginx-ingress-controller.annotations" associated with template "gotpl"
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

**To Reproduce**

1. create a yaml file with the values showed above
2. deploy that helmchart with the values

**Expected behavior**

The annotation should be added to both pods of the deployment: ingress-controller and default-backend.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
$ helmfile version
helmfile version v0.139.6
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

I think the defaultBE should have the same style of annotations like the deployment right?

https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/templates/controller-deployment.yaml#L30

vs

https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml#L23

**Comment by juan131** [comment]
You're totally right @aeimer 

The [default-backend-deployment](https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml) is using a macro (`"nginx-ingress-controller.annotations"`) which doesn't exist. I just created a PR to fix it.

**Comment by aeimer** [comment]
Thanks for the quick fix 👍🏻
