### ISSUE TITLE
Pod fails to start when elasticsearch_custom.yml is mounted with read-only permissions

### ISSUE THREAD

**Issue by lightnet328** [bitnami/charts#644]
ConfigMap volumes have been read-only since Kubernetes 1.9.4. 
https://github.com/kubernetes/kubernetes/pull/58720

Then Pod outputs the following error and exits.

```
Welcome to the Bitnami elasticsearch container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing elasticsearch
Error executing 'postInstallation': EROFS: read-only file system, chown '/bitnami/elasticsearch/conf/elasticsearch_custom.yml'
```

Is there any solution to this?

**Comment by javsalgar** [comment]
Hi,

Could you open the issue in https://github.com/bitnami/bitnami-docker-elasticsearch/issues. It may seem related with the elasticsearch container.

**Comment by lightnet328** [comment]
Thank you for your quick response.

I opened issue in `bitnami/bitnami-docker-elasticsearch`.
https://github.com/bitnami/bitnami-docker-elasticsearch/issues/44
