### ISSUE TITLE
[redis-cluster] Unable to start a new cluster using externalAccess due to readiness probe failures

### ISSUE THREAD

**Issue by beef3333** [bitnami/charts#6443]
**Which chart**:
Chart: redis-cluster
Version: 6.1.0

**Describe the bug**
A recent update here (https://github.com/bitnami/charts/commit/0ade812deb74acdf1b9c79c52bfec735cd285f6c#diff-6d33b789b472cb77cbbb07ae24e3c76a0f462414f967c4498497f01efb57b392) seems to break cluster startup if you are using external access.  From what I can tell when trying to set this up in GCP everything is fine until the pod-0 tries to setup the cluster and wont be able to talk to itself even though the external IP it now has.

The issue is that the nodes do not ever show up as ready so when the job tries to reach out through the external IP its denied since it has no healthy pod to send traffic to.  

**To Reproduce**
1. Follow the instructions on setting up an external access cluster here (https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology)
2. Once you set the IP's and re-deploy the nodes never go ready
3. Cluster is stuck in fail 

**Expected behavior**
Nodes should show up as ready so that traffic can route to them form the external IP's and the cluster will form.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.4900", GitCommit:"2812f9fb0003709fc44fc34166701b377020f1c9", GitTreeState:"clean", BuildDate:"2021-03-19T09:19:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I was able to work around this for now by going back to chart version (6.0.5) but I think the readiness changes needs some work and would be nice to revert them so people can get latest updates without it breaking.

**Comment by migruiz4** [comment]
Hi @beef3333 ,

Thank you for reporting this issue.

I have created this PR #6453 that should fix the issue when using `cluster.externalAccess.enabled=true`.
