### ISSUE TITLE
[mysql] add startupProb

### ISSUE THREAD

**Issue by yelhouti** [bitnami/charts#6444]
**Which chart**:
Mysql

**Is your feature request related to a problem? Please describe.**
Mysql can take too long to startup, depending on Hard drive, init script, and other cases, example:
https://github.com/bitnami/bitnami-docker-mysql/issues/121

**Describe the solution you'd like**
Having a startup probe would improve the experience without damaging the the other probes

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Comment by miguelaeh** [comment]
Hi @yelhouti ,
Please feel free to open a PR adding that new feature

**Comment by yelhouti** [comment]
@Miguelaeh here it is :)

**Comment by miguelaeh** [comment]
Hi @yelhouti ,
Perfect!` thank you very much , we will take a look.
