### ISSUE TITLE
Unable to install ejbca chart as mariadb pod going in CrashLoopBackOff

### ISSUE THREAD

**Issue by prateekkohli2112** [bitnami/charts#6448]
**Which chart**:
ejbca:latest

**Describe the bug**
mariadb pod going in CrashLoopBackOff error while installing ejbca chart

**To Reproduce**
1) Intalling ejbca chart using the below command:
helm install ejbca --namespace em bitnami/ejbca -f values.yaml

Only changed ejbcaAdminPassword, mariabd.auth.rootPassword and mariabd.auth.password in the sample values.yaml.
Also enabled BITNAMI_DEBUG logging.

Below are the mariaDb pod logs:

sles@seliicbl00723:~/certs/EJBCA/EJBCA_K8S> kubectl logs ejbca-mariadb-0 -nem
mariadb 08:39:46.98
mariadb 08:39:46.99 Welcome to the Bitnami mariadb container
mariadb 08:39:46.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 08:39:46.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 08:39:46.99
mariadb 08:39:46.99 INFO  ==> ** Starting MariaDB setup **
mariadb 08:39:47.03 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 08:39:47.03 INFO  ==> Initializing mariadb database
mariadb 08:39:47.03 DEBUG ==> Ensuring expected directories/files exist
mariadb 08:39:47.05 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 08:39:47.05 DEBUG ==> Cleaning data directory to ensure successfully initialization
mariadb 08:39:47.08 INFO  ==> Installing database
Installing MariaDB/MySQL system tables in '/bitnami/mariadb/data' ...

Installation of system tables failed!  Examine the logs in
/opt/bitnami/mariadb/logs/mysqld.log or /bitnami/mariadb/data for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /opt/bitnami/mariadb/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /opt/bitnami/mariadb/sbin/mysqld --skip-grant-tables --general-log &

and use the command line tool /opt/bitnami/mariadb/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /opt/bitnami/mariadb/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /bitnami/mariadb/data that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at https://mariadb.org/jira

**Expected behavior**
MariaDb pod should e deployed successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
version.BuildInfo{Version:"v3.3.3", GitCommit:"597229301293487c18abdaf1d0a94f19718ad233", GitTreeState:"clean", GoVersion:"go1.13.10"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:48:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:40:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by migruiz4** [comment]
Hi @prateekkohli2112,

Could you please share what type of storage are you using?

This error could be caused by a permission error caused, for example, when using an NFS as the storage class.
