### ISSUE TITLE
definition 

### ISSUE THREAD

**Issue by zerols** [bitnami/charts#6451]
database， like mysql mongo influx or other sql , what should i config to attach after creat pods in k8s auto creat table or key-value ,and some Storage strategy or definition ? And i use vscode , is there any pulgins when i edit helm files show me the values of template ?  everytime after  i edit config , i need to helm....-dry-run, very inconvenient 。

**Comment by juan131** [comment]
Hi @zerols 

It depends on the database, but please refer to each chart's README.md. For instance, for MariaDB consult the README.md below:

- https://github.com/bitnami/charts/blob/master/bitnami/mariadb/README.md

You'll notice there are two alternatives to accomplish what you're looking for:

- Using `auth.database`, `auth.username` and `auth.password` parameters to create a custom database and user.
- Using custom init scripts where to include any custom SQL statements you want to execute the 1st time the database is launched: https://github.com/bitnami/charts/blob/master/bitnami/mariadb/README.md#initialize-a-fresh-instance
