### ISSUE TITLE
[bitnami/prestashop] Prestashop installation takes forever on pod 

### ISSUE THREAD

**Issue by diegojfdez** [bitnami/charts#6452]
**Which chart:**
bitnami/prestashop, version 13.1.10

`$ helm ls`
`NAME	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART             	APP VERSION`
`dps 	default  	1       	2021-05-24 18:45:29.265154083 +0200 CEST	deployed	prestashop-13.1.10	1.7.7-4`

**Describe the bug**
When installing the chart on my local minikube, prestashop installation never gets completed. I have to increase delay for readiness prooves several times (atm 1200 secs), but the installation keeps getting stopped by the restart of the pod.

**To Reproduce**
Deploy the chart on a minikube cluster.
OS Debian 10
Host CPU i7 6700K
Host Memory 40GB

**Expected behavior**
Installation completes on pod and then health check success and pod get to a healthy state.

**Version of Helm and Kubernetes:**

- Output of helm version:

`version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

- Output of kubectl version:

`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

**Additional context**
pod logs:
`prestashop 17:07:04.54 Welcome to the Bitnami prestashop container`
`prestashop 17:07:04.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop`
`prestashop 17:07:04.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues`
`prestashop 17:07:04.55 `
`prestashop 17:07:04.55 INFO  ==> ** Starting PrestaShop setup **`
`prestashop 17:07:04.56 DEBUG ==> Validating settings in APACHE_* environment variables`
`prestashop 17:07:04.56 INFO  ==> Configuring the HTTP port`
`prestashop 17:07:04.56 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/httpd.conf`
`prestashop 17:07:04.57 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/bitnami/bitnami.conf`
`prestashop 17:07:04.57 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/vhosts/00_status-vhost.conf`
`prestashop 17:07:04.57 INFO  ==> Configuring the HTTPS port`
`prestashop 17:07:04.57 DEBUG ==> Configuring port 8443 on file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf`
`prestashop 17:07:04.58 INFO  ==> Configuring PHP options`
`prestashop 17:07:04.59 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars`
`prestashop 17:07:04.61 DEBUG ==> Validating settings in PRESTASHOP_* environment variables...`
`prestashop 17:07:04.61 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.`
`prestashop 17:07:04.64 INFO  ==> Ensuring PrestaShop directories exist`
`prestashop 17:07:04.64 INFO  ==> Trying to connect to the database server`
`prestashop 17:07:04.65 DEBUG ==> Executing SQL command:`
`SELECT 1`
`1`
`prestashop 17:07:04.65 INFO  ==> Running install script`

Events on pod:
`Events:`
`  Type     Reason     Age                From               Message`
  ----     ------     ----               ----               -------
`  Normal   Scheduled  34m                default-scheduler  Successfully assigned default/dps-prestashop-689cc445c5-ckwwc to minikube`
`  Warning  Unhealthy  13m (x6 over 14m)  kubelet            Liveness probe failed: Get "http://172.17.0.5:8080/": dial tcp 172.17.0.5:8080: connect: connection refused`
`  Normal   Killing    13m                kubelet            Container dps-prestashop failed liveness probe, will be restarted`
`  Warning  Unhealthy  13m (x9 over 14m)  kubelet            Readiness probe failed: Get "http://172.17.0.5:8080/": dial tcp 172.17.0.5:8080: connect: connection refused`
`  Normal   Pulled     13m (x2 over 34m)  kubelet            Container image "docker.io/bitnami/prestashop:1.7.7-4-debian-10-r8" already present on machine`
`  Normal   Created    13m (x2 over 34m)  kubelet            Created container dps-prestashop`
`  Normal   Started    13m (x2 over 34m)  kubelet            Started container dps-prestashop`

**Comment by marcosbc** [comment]
Hi @diegojfdez, I see that you have enabled debug mode, which is helpful. It seems like `Running install script` is not really showing anything.

Therefore I would recommend you to follow these steps:

* Redeploy with `commands` set to a command that never ends (i.e. `sleep inifinity`, but note it needs to be in array format).
* While it is getting deployed, `kubectl exec` into the pod and run these commands:

    ```bash
    /opt/bitnami/scripts/prestashop/entrypoint.sh /opt/bitnami/scripts/prestashop/run.sh
    ```

* If it gets stuck at the same point, with no obvious output, try this:

    ```bash
    set -x
    . /opt/bitnami/scripts/prestashop/setup.sh
    ```

    And it should show the actual installation command used by Prestashop (i.e. `php /opt/bitnami/prestashop/install/index_cli.php ...`).

    * Run that command in your terminal and see if you get any output.
    * If you see no output, try options like `--help` or even `php --help` to see if it's really PHP the one to be malfunctioning.

**Comment by diegojfdez** [comment]
Hi @marcosbc, first of all thanks for your assistance and prompt response.

I got prestashop pod sleeping and entered into a shell to run the requested commands:

`/opt/bitnami/scripts/prestashop/entrypoint.sh /opt/bitnami/scripts/prestashop/run.sh`

But fails cause  /opt/bitnami/scripts/prestashop/run.sh does not exist. Did you mean to run:

`/opt/bitnami/scripts/prestashop/entrypoint.sh /opt/bitnami/scripts/prestashop/setup.sh`

Which gets this output:
`prestashop 07:56:19.52 `
`prestashop 07:56:19.53 Welcome to the Bitnami prestashop container`
`prestashop 07:56:19.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop`
`prestashop 07:56:19.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues`
`prestashop 07:56:19.54 `
`prestashop 07:56:19.57 DEBUG ==> Validating settings in PRESTASHOP_* environment variables...`
`prestashop 07:56:19.57 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.`
`prestashop 07:56:19.60 INFO  ==> Ensuring PrestaShop directories exist`
`prestashop 07:56:19.60 INFO  ==> Trying to connect to the database server`
`prestashop 07:56:19.61 DEBUG ==> Executing SQL command:`
`SELECT 1`
`1`
`prestashop 07:56:19.61 INFO  ==> Running install script`

And it still gets stuck till not readiness restart...

Same happens with the second tip, here's the output:
[https://pastebin.com/w90heVUN](url)

As you see, it's still getting stuck till it dies.

**Comment by marcosbc** [comment]
Thanks for pointing it out, it was indeed a mistake, I meant `/opt/bitnami/scripts/apache/run.sh`.

As for the installation getting stuck, could you try and execute this script manually on your side inside the container? (basing on the complete command from the log you shared)

    $ php /opt/bitnami/prestashop/install/index_cli.php --db_user=bn_prestashop ...

Note that PrestaShop is only expected to print a result once it is finished and that it takes some time (see below). And unfortunately it's not possible to increase the verbosity, even [PrestaShop debug mode](https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/) does not show more logs.

```
root@f77890fae604:/opt/bitnami/prestashop# php /opt/bitnami/prestashop/install/index_cli.php --db_user=...
-- Installation successful! --
```

If you continue finding it getting stuck after some time (i.e. 5-10 minutes), please check if there is an issue with the PHP or PrestaShop CLI on your computer:

```
$ php /opt/bitnami/prestashop/install/index_cli.php # no arguments here
$ php --version
```

**Comment by diegojfdez** [comment]
Sadly, we've got the same results. No matter how I run install script it gets stuck, even with 1 hour readiness timer:

1.- Apache script

`I have no name!@dps3-prestashop-97456cd89-pcz6s:/$ **/opt/bitnami/scripts/prestashop/entrypoint.sh /opt/bitnami/scripts/apache/run.sh** `
`prestashop 18:40:59.83 `
`prestashop 18:40:59.83 Welcome to the Bitnami prestashop container`
`prestashop 18:40:59.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop`
`prestashop 18:40:59.84 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues`
`prestashop 18:40:59.84 `
`prestashop 18:40:59.88 INFO  ==> ** Starting PrestaShop setup **`
`prestashop 18:40:59.92 DEBUG ==> Validating settings in APACHE_* environment variables`
`prestashop 18:40:59.95 INFO  ==> Configuring the HTTP port`
`prestashop 18:40:59.95 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/httpd.conf`
`prestashop 18:40:59.97 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/bitnami/bitnami.conf`
`prestashop 18:41:00.00 DEBUG ==> Configuring port 8080 on file /opt/bitnami/apache/conf/vhosts/00_status-vhost.conf`
`prestashop 18:41:00.02 INFO  ==> Configuring the HTTPS port`
`prestashop 18:41:00.03 DEBUG ==> Configuring port 8443 on file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf`
`prestashop 18:41:00.07 INFO  ==> Configuring PHP options`
`prestashop 18:41:00.08 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars`
`prestashop 18:41:00.12 DEBUG ==> Validating settings in PRESTASHOP_* environment variables...`
`prestashop 18:41:00.12 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety `reasons, do not use this flag in a production environment.
`prestashop 18:41:00.19 INFO  ==> Ensuring PrestaShop directories exist`
`prestashop 18:41:00.20 INFO  ==> Trying to connect to the database server`
`prestashop 18:41:00.21 DEBUG ==> Executing SQL command:`
`SELECT 1`
`1`
`prestashop 18:41:00.32 INFO  ==> Running install script`
`command terminated with exit code 137`

2.- PHP scripts directly:
`$ kubectl exec --stdin --tty dps3-prestashop-97456cd89-5fsbt -- /bin/bash`
`I have no name!@dps3-prestashop-97456cd89-5fsbt:/$ php /opt/bitnami/prestashop/install/index_cli.php --db_user=bn_prestashop --db_password=3aGAgFQ742 --db_server=dps3-mariadb:3306 --db_name=bitnami_prestashop --domain=djps --firstname=Bitnami --lastname=User --password=p1234567.D --email=user@example.com --timezone=America/Los_Angeles --country=us --language=en --newsletter=0`
`command terminated with exit code 137`
`$`

Btw, no PHP installed on host:
`$ php --version`
`bash: php: orden no encontrada`
`$ `

Want me to try Prestashop installation on host?

Thx. for your time.

**Comment by diegojfdez** [comment]
I also tried to reproduce this error using an Ubuntu 20.04 VM on top of our proxmox and I must admit I was unable.

Prestashop Installation finishes and readness test finally succeded, so there must be something related to my personal box. Please see:
[kubectl get all](https://pastebin.com/8xFyezSD)

Thx for your time and effort. Imo, since it's something punctual and local there's no need for further investigation, we can close  the issue.
