### ISSUE TITLE
[bitnami/minio] accessKey and secretKey are required but unused when using gateway

### ISSUE THREAD

**Issue by glentakahashi** [bitnami/charts#6456]
**Which chart**:
Minio 6.7.10

**Describe the bug**
The chart errors about accessKey and secretKey being unset when deploying in gateway mode, even though the credentials are unused.

```
Error: template: charts/minio/templates/NOTES.txt:86:4: executing "charts/minio/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredMinioPasswordErrors) "context" $)>: error calling include: template: charts/minio/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'accessKey.password' must not be empty, please add '--set accessKey.password=$ACCESS_KEY' to the command. To get the current value:

        export ACCESS_KEY=$(kubectl get secret --namespace "develop" develop-minio -o jsonpath="{.data.access-key}" | base64 --decode)

    'secretKey.password' must not be empty, please add '--set secretKey.password=$SECRET_KEY' to the command. To get the current value:

        export SECRET_KEY=$(kubectl get secret --namespace "develop" develop-minio -o jsonpath="{.data.secret-key}" | base64 --decode)
```

When using chart in gateway mode, MINIO_ROOT_USER and MINIO_ACCESS_KEY are pulled from `minio.gateway.auth.s3.accessKey` and `minio.gateway.auth.s3.secretKey` respectively https://github.com/bitnami/charts/blob/70d602fea38010145c20e1ca59be06e4cf32bf80/bitnami/minio/templates/_helpers.tpl#L56

**To Reproduce**

Deploy the helm chart with empty values for `accessKey.password` and `secretKey.password`. Have `gateway.enabled: true` and valid credentials in auth.

**Expected behavior**
Either one of the following:
1. accessKey/secretKey are not required when using gateway:enabled OR
2. accessKey/secretKey are still used for authenticating against minio and gateway auth is provided via a separate secret.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```
(paste your output here)
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @glentakahashi ,
Could you check if the above PR is what you was expecting?

**Comment by glentakahashi** [comment]
Ah yea @miguelaeh that looks perfect
