### ISSUE TITLE
[airflow] option to mention dnsConfig and generate FQDN for postgres and redis if enabled

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#6474]
**Which chart**:
airflow (all versions)

**Is your feature request related to a problem? Please describe.**
1. We run our pods with:
```
dnsconfig:
  options:
  - ndots: 2
```
And we try to use fqdn as much as possible. We can't specify dnsconfig in current chart.

2. the postgresql and redis deployed along with this chart should always generate fqdn, currently it doesn't.

**Describe the solution you'd like**
1. dnsconfig options if specified should be passed along to all resources created by this chart, can be global setting or component wise, either would work. We have a mutation webhook controller to do this.
2. Generate FQDN if redis/postgres enabled in the secrets.

**Describe alternatives you've considered**
decoupled external dependencies like postgres and redis from airflow and mention the hostname as FQDN.

**Additional context**

**Comment by juan131** [comment]
Hi @iamsudip 

This chart has already support for using an "external" Redis or PostgreSQL database, see:

- https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml#L931
- https://github.com/bitnami/charts/issues/6474

Or:

- https://github.com/bitnami/charts/tree/master/bitnami/airflow#airflow-database-parameters

Wouldn't that work for you? You can use any existing Redis or PostgreSQL backend you already have in your cluster (or outside the cluster) and use FQDN(s) for the `externalRedis.host` and `externalDatabase.host` parameters.

**Comment by iamsudip** [comment]
@juan131 Yes, I'm aware of that and doing exactly as you suggested. But, if I create postgresql and redis using airflow chart itself, then the fqdn is autogenerated by the chart which doesn't contain <namespace>.svc.cluster.local, only contains service name (<release_name>-postgresql or <release_name>-redis)

**Comment by juan131** [comment]
>  if I create postgresql and redis using airflow chart itself, then the fqdn is autogenerated by the chart which doesn't contain .svc.cluster.local, only contains service name (<release_name>-postgresql or <release_name>-redis)

Correct, and that should be compatible with almost every K8s cluster unless you're using a custom DNS service.

- What K8s platform are you using?
- Are you using CoreDNS?

---

Have you tried to do sth like this?

```console
$ helm install postgresql bitnami/postgresql \
    --set postgresqlUsername=bn_airflow \
    --set postgresqlDatabase=bitnami_airflow \
    --set postgresqlPassword=XXXXX
$ helm install redis bitnami/redis \
    --set auth.enabled=true \
    --set auth.password=YYYYY
$ helm install airflow bitnami/airflow \
    --set postgresql.enabled=false \
    --set externalDatabase.host=postgresql.default.svc.cluster.local \
    --set externalDatabase.port=5432 \
    --set externalDatabase.user=bn_airflow \
    --set externalDatabase.password=XXXXX \
    --set externalDatabase.database=bitnami_airflow \
    --set redis.enabled=false \
    --set externalRedis.host=redis-master.default.svc.cluster.local \
    --set externalRedis.port=6379 \
    --set externalRedis.password=YYYYY
```

**Comment by iamsudip** [comment]
@juan131 I had `postgresql.enabled=true` and `redis.enabled=true` so host was getting autogenerated. Now I do it exacly like you suggested.

I'm using EKS and using coredns

**Comment by miguelaeh** [comment]
Hi @iamsudip ,
Maybe I am missing something but when you create a pod it willhave a FDQN by default as documented here https://kubernetes.io/docs/concepts/services-networking/dns-pod-service
The FQDN will be the `pod-name.namespace.svc.cluster-domain.example`.
What does it mean that it does not generate FQDN? If you exec into a pod in your cluster you can't ping that address?

**Comment by juan131** [comment]
Hi @iamsudip 

So, it's just a matter to reduce the number o DNS queries, right? I mean, do you see any other advantage on using FQDN vs the "reduced" hostname equivalent?

> but I'm still not able to pass along dnsConfig to all airflow components

What do you mean with that? Could you provide more details?

**Comment by iamsudip** [comment]
@juan131 Yes, you are right. Only reduced number of DNS queries if we use FQDN.

By propagation of dnsConfig it's yet another config like nodeSelector or any other configuration. If we don't specify dnsConfig in deployment/statefulset/pod spec, by default it is:
```
      dnsConfig:
        options:
          - name: ndots
            value: '5'
```
and you don't get to see it in spec. It's implicit.

I want to change dnsConfig for all airflow components, and inject the following to worker sts in here: [L52](https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/worker/statefulset.yaml#L52) and same places for all other components as well. If you want a PR, I can open.
```
      dnsConfig:
        options:
          - name: ndots
            value: '2'
```

**Comment by juan131** [comment]
Hi @iamsudip 

Thanks for providing the whole context, I appreciate it.

Please go ahead and submit a PR, I think it's an interesting feature to support in the chart. Please go for option two: each component should be set its custom dnsConfig.

**Comment by iamsudip** [comment]
@juan131 Yes, I'll add dnsConfig support for all pods.

What about FQDN generation, instead of generating hosts like `<release-name>-postgresql` or `<release-name>-redis-master`, can we generate `<release-name>-postgresql.<namespace>.svc.cluster.local` or `<release-name>-redis-master.<namespace>.svc.cluster.local`? But, this will only work for coredns managed clusters, not other service discoveries like consul where they have other suffixes.

**Comment by juan131** [comment]
Hi @iamsudip 

By default hosts should not include the `.<namespace>.svc.cluster.local` suffix. That said, we can implement a parameter to explicitly indicate the chart to include the suffix when the user requests it.
