### ISSUE TITLE
SuiteCRM - Installation fails with existing external MySQL database

### ISSUE THREAD

**Issue by jcordes73** [bitnami/charts#6480]
**Which chart**:
bitnami/suitecrm

**Describe the bug**
When using an external MySQL database, the SuiteCRM installation wizard is failing, with image.debug=true it shows in the logs:

<div id='sysCheckMsg' style="display:none">
                    <p>The provided Database Name already exists.<br>You can either:<br>1. Click on the Cancel button and choose a new database name, or <br>2. Click the Accept button and continue. All existing tables in the database will be dropped. <strong>This means that all of the tables and pre-existing data will be blown away.</strong></p>
                    <input id='accept_btn' type='button' class='button' onclick='confirm_drop_tables(true)' value="I Accept">
                    <input type='button' class='button' onclick='confirm_drop_tables(false)' id="button_cancel_dbConfig" value="Cancel">
          </div>

**To Reproduce**

1. Create external MySQL database
2. Install SuiteCRM helm chart

**Expected behavior**
Installation completes successfully

**Version of Helm and Kubernetes**:
helm version
- Output of `helm version`:
version.BuildInfo{Version:"v3.2.3+4.el8", GitCommit:"2160a65177049990d1b76efc67cb1a9fd21909b1", GitTreeState:"clean", GoVersion:"go1.13.4"}

- Output of `kubectl version`:
oc version
Client Version: 4.7.8
Server Version: 4.7.2
Kubernetes Version: v1.20.0+5fbfd19

**Additional context**
OpenShift 4.7.2
MySQL 8.0.21

**Comment by alvneiayu** [comment]
hi @jcordes73 

Could you share with me the suitecrm values.yaml, please? to try to reproduce the problem and investigate it. could you share with me also logs?

Thanks a lot

Álvaro

**Comment by jcordes73** [comment]
Here are the steps I have used for deployment:

oc new-project <your-project>

export SUITECRM_PROJECT=$(oc project -q)
export SUITECRM_RELEASE=tmf629

oc new-app mysql-persistent -p DATABASE_SERVICE_NAME=suitecrm-mysql -p MYSQL_USER=bn_suitecrm -p MYSQL_PASSWORD=bn_suitecrm -p MYSQL_ROOT_PASSWORD=bn_suitecrm -p MYSQL_DATABASE=bitnami_suitecrm

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install $SUITECRM_RELEASE bitnami/suitecrm \
    --set image.debug=true,mariadb.enabled=false,externalDatabase.user=bn_suitecrm,externalDatabase.password=bitnami_suitecrm,externalDatabase.database=bitnami_suitecrm,externalDatabase.host=suitecrm-mysql

export APP_HOST=$(oc get route $SUITECRM_RELEASE -o jsonpath="{.spec.host}")
export APP_PASSWORD=$(oc get secret --namespace $SUITECRM_PROJECT $SUITECRM_RELEASE-suitecrm -o jsonpath="{.data.suitecrm-password}" | base64 --decode)
export DATABASE_ROOT_PASSWORD=$(oc get secret --namespace $SUITECRM_PROJECT suitecrm-mysql -o jsonpath="{.data.database-root-password}" | base64 --decode)
export APP_DATABASE_PASSWORD=$(oc get secret --namespace $SUITECRM_PROJECT suitecrm-mysql -o jsonpath="{.data.database-password}" | base64 --decode)

helm upgrade $SUITECRM_RELEASE bitnami/suitecrm --set image.debug=true,suitecrmHost=$APP_HOST,suitecrmPassword=$APP_PASSWORD,mariadb.enabled=false,externalDatabase.user=bn_suitecrm,externalDatabase.database=bitnami_
suitecrm,externalDatabase.password=$APP_DATABASE_PASSWORD,externalDatabase.host=suitecrm-mysql


Attached you can also find the log from the container:

[log (24).txt](https://github.com/bitnami/charts/files/6569470/log.24.txt)

**Comment by alvneiayu** [comment]
hi @jcordes73

In this case, I suggest you to set up the key suitecrmSkipInstall to true. Enabling this key, you will skip the wizard and I think that your problem will be solved. Test it and let me know if you still have problems.

Thanks a lot

Álvaro

**Comment by jcordes73** [comment]
Unfortunately this issue also exists with a new installation and a "freshly" deployed external database.

I tried the following steps so far (without success):

- Install external database with suitecrm schema in place
- Install suitecrm via helm chart
- Update suitecrm helm chart
- Delete schema on external database (this is leading to "errors" on the suitecrm installation as it complains about missing database schema
- Create database schema

This fails with the same error originally reported.

**Comment by alvneiayu** [comment]
hi @jcordes73 

Did you test enabling the flag that I suggested you?

https://github.com/bitnami/charts/issues/6480#issuecomment-851879610

Thanks a lot

Álvaro
