### ISSUE TITLE
[bitnami/redis-cluster] External Access on microk8s with metalb

### ISSUE THREAD

**Issue by dj4n60** [bitnami/charts#6482]
**Which chart**:
Chart: Redis Cluster 
Version: 13.0.1

**Describe the bug**
Following all the steps the pods failing on microk8s, despite the fact that other loadbalancer service with pods works. 

**To Reproduce**
`$ helm install redis --set cluster.externalAccess.enabled=true bitnami/redis-cluster`
`$ kubectl get svc = microk8s.kubectl get svc`

  Output:
```
NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)                          AGE
kubernetes                     ClusterIP      10.152.183.1     <none>            443/TCP                          2d21h
redis-redis-cluster-headless   ClusterIP      None             <none>            6379/TCP,16379/TCP               4m19s
redis-redis-cluster            ClusterIP      10.152.183.185   <none>            6379/TCP                         4m19s
redis-redis-cluster-0-svc      LoadBalancer   10.152.183.2     192.168.134.201   6379:30550/TCP,16379:30475/TCP   4m19s
redis-redis-cluster-1-svc      LoadBalancer   10.152.183.228   192.168.134.202   6379:31182/TCP,16379:31690/TCP   4m19s
redis-redis-cluster-2-svc      LoadBalancer   10.152.183.202   192.168.134.203   6379:32187/TCP,16379:30498/TCP   4m19s
redis-redis-cluster-3-svc      LoadBalancer   10.152.183.107   192.168.134.204   6379:31059/TCP,16379:30417/TCP   4m19s
redis-redis-cluster-4-svc      LoadBalancer   10.152.183.205   192.168.134.205   6379:32497/TCP,16379:32113/TCP   4m19s
redis-redis-cluster-5-svc      LoadBalancer   10.152.183.138   192.168.134.206   6379:32578/TCP,16379:30595/TCP   4m19s
```
`$ export REDIS_PASSWORD=$(kubectl get secret --namespace "default" redis-redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)`

`$ helm upgrade redis --set "cluster.externalAccess.enabled=true,cluster.externalAccess.service.type=LoadBalancer,cluster.externalAccess.service.loadBalancerIP[0]=192.168.134.201,cluster.externalAccess.service.loadBalancerIP[1]=192.168.134.202,cluster.externalAccess.service.loadBalancerIP[2]=load-192.168.134.203,cluster.externalAccess.service.loadBalancerIP[3]=load-192.168.134.204,cluster.externalAccess.service.loadBalancerIP[4]=192.168.134.205,cluster.externalAccess.service.loadBalancerIP[5]=192.168.134.206" bitnami/redis-cluster --set password=$REDIS_PASSWORD`

`$ kubectl get pods`
   Output:
```
redis-redis-cluster-0   0/1     Running   0          8m10s
redis-redis-cluster-1   0/1     Running   0          8m10s
redis-redis-cluster-3   0/1     Running   0          8m10s
redis-redis-cluster-5   0/1     Running   0          8m10s
redis-redis-cluster-4   0/1     Running   0          8m10s
redis-redis-cluster-2   0/1     Running   0          8m10s
```

**Expected behaviour**
I want to achieve a redis-cluster with 3 master 3 replicas deployment on-premise installation, so I can access it from the network currently the network is defined from the metallb and the other VM on the can see other deployment. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+df7df22a741dbc", GitCommit:"df7df22a741dbc18dc3de3000b2393a1e3c32d36", GitTreeState:"clean", BuildDate:"2021-05-12T21:08:20Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+df7df22a741dbc", GitCommit:"df7df22a741dbc18dc3de3000b2393a1e3c32d36", GitTreeState:"clean", BuildDate:"2021-05-12T21:09:51Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

Also the logs from the pods:
`Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...
Could not connect to Redis at 192.168.134.201:6379: No route to host
Node 192.168.134.201 not ready, waiting for all the nodes to be ready...`


```

redis-cluster 08:59:48.89 
redis-cluster 08:59:48.90 Welcome to the Bitnami redis-cluster container
redis-cluster 08:59:48.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 08:59:48.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 08:59:48.91 
redis-cluster 08:59:48.91 INFO  ==> ** Starting Redis setup **
redis-cluster 08:59:48.94 INFO  ==> Initializing Redis
redis-cluster 08:59:48.96 INFO  ==> Setting Redis config file
redis-cluster 08:59:49.00 INFO  ==> ** Redis setup finished! **
1:C 27 May 2021 08:59:49.051 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 27 May 2021 08:59:49.052 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 27 May 2021 08:59:49.052 # Configuration loaded
1:M 27 May 2021 08:59:49.053 * monotonic clock: POSIX clock_gettime
1:M 27 May 2021 08:59:49.054 * No cluster configuration found, I'm 2b8807d8206c5cdd89cfd4764cdc4ad59e3c545b
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 6.2.3 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               
1:M 27 May 2021 08:59:49.056 # Server initialized
1:M 27 May 2021 08:59:49.057 * Ready to accept connections

```

**Comment by dj4n60** [comment]
I could find what was the problem so I reinstalled the whole microk8s with some tweaks 
_I followed this guide_ 
https://wiki.onap.org/display/DW/Deploy+OOM+and+SDC+%28or+ONAP%29+on+a+single+VM+with+microk8s+-+Honolulu+Setup
! Until the Step 3

After I enabled the metallb and change the configuration for the network from range I change to CIDR, it was 192.168.*.*-192.168.*.* and I change it to 192.168.*.*/24

_At last I run the following commands_

`sudo ufw allow in on cni0 && sudo ufw allow out on cni0`
`sudo ufw default allow routed`
After that, the loadbalancer seems to work and the

**Comment by marcosbc** [comment]
Thanks for sharing! It does indeed look like the network was not properly configured. I'm glad you were able to fix it though, and I'm certain that others users who discover the same issue will find the response useful.
