### ISSUE TITLE
[bitnami / postgresql] Bug: No restart taking place after (PVC-related?) fatal error

### ISSUE THREAD

**Issue by sjoodin** [bitnami/charts#6490]
**Which chart**:
bitnami / postgresql-10.4.3

**Describe the bug**
We are getting this error at the postgresql pod at runtime: "FATAL: could not open relation mapping file "global/pg_filenode.map". Restarting the pod got it running again, but the same problem returned a few weeks later. Severity of the error increases because the pod keeps running instead of entering a failed state so that it can be automatically restarted.

**To Reproduce**
We do not know exactly what caused the error (possibly related to the PVC mount). However it happened unexpectedly after the pod had been running successfully for many days / weeks. Has happened twice so far, with varying durations from start to crash.

**Expected behavior**
It would be very helpful if the postgresql pod entered a failed state when encountering this error so that the pod could be auto-restarted by kubernetes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version: "v3.5.4", GitCommit: (cut out), GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion: "v1.18.19", GitCommit: (cut out), GitTreeState:"clean", BuildDate: "2021-05-13T02:32:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform: "linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion: "v1.18.8", GitCommit: (cut out), GitTreeState:"clean", BuildDate: "2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform: "linux/amd64"}
```

**Additional context**
Log output from the postgres pod, which does not enter a failure state:
![image](https://user-images.githubusercontent.com/47199287/119897141-47e60080-bf40-11eb-84bc-f03fae8e92fe.png)

Log output example from the client pod (django), which repeatedly crashes due to bad response from the postgres pod:
![117812198-cb75d100-b261-11eb-9b8f-3268c2ff0420](https://user-images.githubusercontent.com/47199287/119890529-3c8ed700-bf38-11eb-8d21-91d7c1536c8b.png)

From the above, it seems that there is some problem happening with the PVC?
How to best avoid consequences of this error? Perhaps this problem could be detected by a liveness probe?

**Comment by sjoodin** [comment]
Seems like a common kubernetes problem that storage sometimes gets remounted read-only on the containers and need to be restarted (as mentioned here: https://github.com/arangodb/kube-arangodb/issues/684 )

**Comment by sjoodin** [comment]
Testing to add a custom livenessprobe to my custom-values file. The custom liveness probe is imitating the default one, but adding this text at the end:

![image](https://user-images.githubusercontent.com/47199287/119909438-1cb9dc00-bf55-11eb-8fd5-be6046da61f2.png)

This should return an error if the PVC volume stops being readable. Unsure if it solves the Input/output error.

Guess I will have to wait and see if the error happens again, and if the livenessprobe doesn't make the pod restart, I will have to enter the pod and see if I can come up with some command triggering an error.

I suppose if the livenessprobe tried to read one of the files mentioned in the log this should trigger an error even if the PVC is mounted but failing for some other reason...

**Comment by alvneiayu** [comment]
hi @sjoodin

Until you reproduced the problem with your custom livenessProbes. I found some cases facing the same error "FATAL: could not open relation mapping file "global/pg_filenode.map"".

https://github.com/bitnami/charts/issues/4623
https://github.com/bitnami/bitnami-docker-postgresql/issues/220

I don't know if maybe those can help you. I will be looking forward you test result.

Thanks a lot for your time

Álvaro
