### ISSUE TITLE
[bitnami/postgresql] StatefulSet livenessProbe use wrong tls certs?

### ISSUE THREAD

**Issue by qtomato3** [bitnami/charts#6491]
**Which chart**:
bitnami/postgresql, version: `10.2.1`

**Describe the bug**
livenessProbe of `statefulset.yaml` seems to use the wrong certs when `tls.certCAFilename` is specified.
```
                - exec pg_isready -U {{ include "postgresql.username" . | quote }} {{- if and .Values.tls.enabled .Values.tls.certCAFilename }} -d "sslcert={{ include "postgresql.tlsCert" . }} sslkey={{ include "postgresql.tlsCertKey" . }}"{{- end }} -h 127.0.0.1 -p {{ template "postgresql.port" . }}
```
From https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#securing-postgresql-traffic 
and https://www.postgresql.org/docs/12/ssl-tcp.html, the cert/key pair represents **server** certificate. 
- postgresql.tlsCert  
- postgresql.tlsCertKey

With wrong certs specified, every 10 second (default) `pg_isready` or livenessProbe will cause a failed connection attempt logged in Postgresql Pod. For example:
- `abc`: username
- `my-postgresql` is Postgresql service name, which is included as **CN** when generating server certificates.
```
2021-05-28 00:40:46.208 GMT [24992] [abc:localhost] LOG:  provided user name (abc) and authenticated user name (my-postgresql) do not match
2021-05-28 00:40:46.209 GMT [24992] [abc:localhost] FATAL:  certificate authentication failed for user "abc"
2021-05-28 00:40:46.209 GMT [24992] [abc:localhost] DETAIL:  Connection matched pg_hba.conf line 1: "hostssl     all             all             0.0.0.0/0               cert"
```

**To Reproduce**

1. Define CA cert variable 
```
  tls:
    enabled: true
    certificatesSecret: "postgresql-cert"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    certCAFilename: "ca.crt"
```

**Expected behavior**
- Remove the certs usage in livenessProbe.
- a simple cmd like `exec pg_isready -U "abc" -d "dbname=postgres" -h 127.0.0.1 -p 5432` will generate single log line: 
```
2021-05-28 00:41:01.704 GMT [25027] [abc:localhost] FATAL:  connection requires a valid client certificate
```

**Version of Helm and Kubernetes**:
- Postgresql Docker image: `bitnami/postgresql:12-debian-10`
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you for opening the issue. Let me see if I understand the issue correctly. The problem is the fact that it is using the server certificate instead of a client certificate to authenticate in the pg_isready command, right? Instead, it should either use a client certificate or use no certificates at all for authentication. The thing is, if authenticating using certs is forced, it may be the way for pg_isready to work correctly. Could you confirm that my analysis is correct?

**Comment by qtomato3** [comment]
According to https://www.postgresql.org/docs/12/app-pg-isready.html
> It is not necessary to supply correct user name, password, or database name values to obtain the server status; however, if incorrect values are provided, the server will log a failed connection attempt.

What I tried: manual test inside `postgresql` container with `pg_isready -U "abc" -d "dbname=<db_name>" -h 127.0.0.1 -p 5432` returns 0 but still got failed attempt logged. 

```
// kubectl exec -ti ... postgresql -- /bin/sh
$ pg_isready -U "abc" -d "dbname=<db_name>" -h 127.0.0.1 -p 5432
127.0.0.1:5432 - accepting connections

// kubectl logs
2021-05-28 00:41:01.704 GMT [25027] [abc:localhost] FATAL:  connection requires a valid client certificate
```

**Comment by javsalgar** [comment]
I see. My concern is that then the readiness probe and liveness probe would add a lot of noise in the PostgreSQL logs. I presume that's the main reason we want to have successful authentication attempts.

**Comment by diego-leapyear** [comment]
Can someone re-open this issue?
The livenessprobe is actually misconfigured. Our workaround was to remove `certCAFilename` from the values file in the helm chart, modify the chart, and add an extra environment variable from postgres which is `PGSSLROOTCERT` https://www.postgresql.org/docs/12/libpq-envars.html

```
extraEnv:
  - name: PGSSLROOTCERT
    value: /opt/bitnami/postgresql/certs/ca.crt
```
Once we added this, the pod started without problems.

**Comment by marcosbc** [comment]
@diego-leapyear For now, let's continue the discussion in #8026. Thanks for checking this!
