### ISSUE TITLE
Kafka: Chart values for KIP-500, no zoo keeper ?

### ISSUE THREAD

**Issue by iangregsondev** [bitnami/charts#6492]
Hi,

With kafka 2.8.0 it appears you can use kafka without zookeeper, I notice the helm chart uses 2.8.0, does anybody know how to enable kafka using KRaft (KIP-500) so there is no dependency on zookeeper.

I couldn't find anything.

Thanks in advance.

**Comment by carrodher** [comment]
Thanks for your suggestion, there is an open issue in the Kafka container repository, see https://github.com/bitnami/bitnami-docker-kafka/issues/159.

Because of this issue we already created an internal task to investigate it, but due to the size of the team and other priorities we didn't start looking into it, so unfortunately I can't provide an ETA for this task.

**Comment by iangregsondev** [comment]
Ok thanks for the quick response, I will keep my eye on it then.

Cheers

**Comment by pavelbrylov** [comment]
https://github.com/bitnami/bitnami-docker-kafka/pull/235
Looks like docker support is there now? ;)

**Comment by rafariossaa** [comment]
yes, let wait until that is solved

**Comment by whithajess** [comment]
@rafariossaa This is now available in all the latest releases of `bitnami-docker-kafka` I created then PR, and while I don't have a need for a helm chart if you need any help with configuration or looking over a change to add it to the chart I am happy to help 👍

**Comment by rafariossaa** [comment]
Hi @whithajess,
  Thanks for your offering. Please feel free to send PRs we will be glad to review and merge them.

**Comment by jasine** [comment]
is there a plan to support kraft in helm chart?

**Comment by rafariossaa** [comment]
Hi, I am sorry but not for now.

**Comment by AntonOfTheWoods** [comment]
@rafariossaa , so you are no longer interested in PRs? Or just VMWare won't be authoring any new ones for this? 

This seems curious, as the plan for Kafka 4.0, which might appear in as early as one year's time (https://cwiki.apache.org/confluence/display/KAFKA/KIP-833%3A+Mark+KRaft+as+Production+Ready), is to completely remove zookeeper support and only leave kraft.

**Comment by rafariossaa** [comment]
Hi @AntonOfTheWoods ,
  Thanks for providing that reference, I am updating our internal task on this.
  This should be implemented sooner or later.  Meanwhile feel free to send a PR if you like. We will be glad to review and merge it.

**Comment by cten** [comment]
Is there another issue I can reference for this work or that I might submit a PR against if I get time?

**Comment by jotamartos** [comment]
Hi all,

Just a quick note to let you know that we recently updated the Bitnami Kafka Chart to use Kraft by default 

https://github.com/bitnami/charts/pull/15768

Regards.

**Comment by javsalgar** [comment]
Hi,

That's it. It would be in the latest version of the supported branches
