### ISSUE TITLE
[bitnami/mysql] :mysqladmin: connect to server at 'localhost' failed

### ISSUE THREAD

**Issue by yingjunxu** [bitnami/charts#6493]
**Which chart**:
The name (and version) of the affected chart.
mysql  8.5.5
**Is your feature request related to a problem? Please describe.**
```console
[root@local ~]# kube125 get pod -n test-su
NAME                    READY   STATUS    RESTARTS   AGE
mysql0528-primary-0     1/1     Running   0          67s
mysql0528-secondary-0   0/1     Running   0          67s

[root@local ~]# kube125 describe pod mysql0528-secondary-0 -n test-su
Name:         mysql0528-secondary-0
Namespace:    test-su
Priority:     0
Node:         host-10-1-234-127/10.1.234.127
Start Time:   Fri, 28 May 2021 08:14:28 +0000
Labels:       app.kubernetes.io/component=secondary
              app.kubernetes.io/instance=mysql0528
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mysql
              controller-revision-hash=mysql0528-secondary-f4c584b74
              helm.sh/chart=mysql-8.5.5
              statefulset.kubernetes.io/pod-name=mysql0528-secondary-0
Annotations:  checksum/configuration: 68d425e115328182b0bf208bef4351440b1ef3de8c6f496ff41e78515d54edb1
              cni.projectcalico.org/podIP: 10.244.158.177/32
              cni.projectcalico.org/podIPs: 10.244.158.177/32
Status:       Running
IP:           10.244.158.177
IPs:
  IP:           10.244.158.177
Controlled By:  StatefulSet/mysql0528-secondary
Containers:
  mysql:
    Container ID:   docker://d28ccf3ba9d52e612d2b53f1ac2507e670d39de8e0eceff49264864b3b50ea74
    Image:          docker.io/bitnami/mysql:8.0.24-debian-10-r0
    Image ID:       docker-pullable://bitnami/mysql@sha256:15bed7368d6729d232e582bde6bc59ad6705b1d0144d34c9222ac6c669072bb8
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 28 May 2021 08:14:31 +0000
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -ec password_aux="${MYSQL_MASTER_ROOT_PASSWORD:-}"
if [[ -f "${MYSQL_MASTER_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MYSQL_MASTER_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [/bin/bash -ec password_aux="${MYSQL_MASTER_ROOT_PASSWORD:-}"
if [[ -f "${MYSQL_MASTER_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MYSQL_MASTER_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:               false
      MYSQL_REPLICATION_MODE:      slave
      MYSQL_MASTER_HOST:           mysql0528-primary
      MYSQL_MASTER_PORT_NUMBER:    3306
      MYSQL_MASTER_ROOT_USER:      root
      MYSQL_REPLICATION_USER:      replicator
      MYSQL_MASTER_ROOT_PASSWORD:  <set to the key 'mysql-root-password' in secret 'mysql0528'>         Optional: false
      MYSQL_REPLICATION_PASSWORD:  <set to the key 'mysql-replication-password' in secret 'mysql0528'>  Optional: false
    Mounts:
      /bitnami/mysql from data (rw)
      /opt/bitnami/mysql/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from mysql0528-token-ttb78 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-mysql0528-secondary-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      mysql0528-secondary
    Optional:  false
  mysql0528-token-ttb78:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mysql0528-token-ttb78
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  37s                     default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  37s                     default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         34s                     default-scheduler  Successfully assigned test-su/mysql0528-secondary-0 to host-10-1-234-127
  Normal   Pulled            44s                     kubelet            Container image "docker.io/bitnami/mysql:8.0.24-debian-10-r0" already present on machine
  Normal   Created           44s                     kubelet            Created container mysql
  Normal   Started           43s                     kubelet            Started container mysql
  Warning  Unhealthy         <invalid> (x4 over 4s)  kubelet            Readiness probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
```
**Describe the solution you'd like**
the salve mysql pod  running 

**Describe alternatives you've considered**

**Additional context**
install ///
```console
helm  install mysql0528 --kubeconfig /root/.kube/config125  -n test-su  DEV_cbm/mysql --set architecture=replication,global.storageClass=sc-nfs-10-1-234-131-sd1
```

**Comment by yingjunxu** [comment]
the master mysql is running

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate the changes you added to the values.yml ? I would like to try to reproduce it.
  Most of the time this kind of issues are due to having deployed it previously with other password. Keep in mind that if you don't indicate a password a random one will be generated.
  Maybe you can try to deploy it again but deleting previously the PVCs.

**Comment by yingjunxu** [comment]
> Hi,
> Could you indicate the changes you added to the values.yml ? I would like to try to reproduce it.
> Most of the time this kind of issues are due to having deployed it previously with other password. Keep in mind that if you don't indicate a password a random one will be generated.
> Maybe you can try to deploy it again but deleting previously the PVCs.

--set architecture=replication,global.storageClass=sc-nfs-10-1-234-131-sd1
value.yaml I do not modify it.

**Comment by yingjunxu** [comment]
> Hi,
> Could you indicate the changes you added to the values.yml ? I would like to try to reproduce it.
> Most of the time this kind of issues are due to having deployed it previously with other password. Keep in mind that if you don't indicate a password a random one will be generated.
> Maybe you can try to deploy it again but deleting previously the PVCs.

delete the PVCs,and deploy it again,the issue is still

**Comment by yingjunxu** [comment]
> Hi,
> Could you indicate the changes you added to the values.yml ? I would like to try to reproduce it.
> Most of the time this kind of issues are due to having deployed it previously with other password. Keep in mind that if you don't indicate a password a random one will be generated.
> Maybe you can try to deploy it again but deleting previously the PVCs.

Hi,I am replace the image to docker.io/bitnami/mysql:8.0.23-debian-10-r0 ,the slave mysql pod is running.

**Comment by rafariossaa** [comment]
Hi,
  I was not able to reproduce it. I used 8.0.23, 8.0.24 and 8.0.25 and worked.
  Could you used the latest chart version `8.0.10`, delete the PVCs, and enable debug `--set image.debug=true` ?
  Once the debug is enabled it should provide more information in the pods logs.

**Comment by kuisathaverat** [comment]
We have the same issue we use the following configuration on a GKE cluster

```
HELM_CHART="bitnami/mysql"
HELM_CHART_VER="8.5.10"
HELM_CHART_VALUES="--values helm-values.yml"
NAME="db-mysql"
NAMESPACE="default"

helm upgrade --install  --namespace "${NAMESPACE}"  --version "${HELM_CHART_VER}"  ${HELM_CHART_VALUES}  "${NAME}" "${HELM_CHART}"
```

helm-values.yml
```
---
imageTag: 8.0.25
mysqlDatabase: myDB
serviceAccount:
  create: true
existingSecret: mysql-creds
resources:
  requests:
    cpu: 0.1
    memory: 256Mi
  limits:
    cpu: 0.8
    memory: 512Mi
configurationFiles:
  mysql_custom.cnf: |-
    [mysqld]
    log_warnings=2
    log_error_verbosity=3

```

mysql-creds.yml
```
apiVersion: v1
data:
  mysql-root-password: REDACTED
  user: REDACTED
kind: Secret
metadata:
  name: mysql-creds
  namespace: default
type: Opaque
```

**Comment by yingjunxu** [comment]
use the image : docker.io/bitnami/mysql:8.0.23-debian-10-r0

**Comment by rafariossaa** [comment]
Hi,
  I saw that @alemorcuq answer you in #6394, do you mind if we follow the issue there ?

**Comment by yingjunxu** [comment]
ok

**Comment by kuisathaverat** [comment]
@rafariossaa I cannot replicate the issue anymore after deleting the PVC and the PV, so I am not sure what happens.

**Comment by rafariossaa** [comment]
Hi, 
 @kuisathaverat , don't worry, feel free to reopen or to create a new issue if you have further problems.

**Comment by ComradePashka** [comment]
Hi, I had similar problem when redeploy with changed password. at first I updated password via phpmyadmin, but still had some issues in another PODs deployed from same chart, and even when I found mention about PV/PVC and removed 'em I still had issues, until completely wiped all the data in mounted directory and finally had deployed one more time from scratch.

so I just leave it here if someone encouter same trouble.

**Comment by GeethSampath** [comment]
helm install mysql bitnami/mysql --set auth.rootPassword=root --set primary.startupProbe.enabled=false --set primary.readinessProbe.enabled=false --set primary.livenessProbe.enabled=false --set secondary.replicaCount=0

**Comment by MetaverseMan** [comment]
Same Issue.
kubectl describe pod/my-mysql-dev-0 -n payment-dev
`achine
  Normal   Created                 44m (x2 over 46m)    kubelet                  Created container mysql
  Normal   Started                 44m (x2 over 46m)    kubelet                  Started container mysql
  Warning  Unhealthy               11m (x120 over 46m)  kubelet                  Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'`

i am very sure the rootPassword in value.yaml was set and correct,but still having this problem.
I am using mysql:8.4.3-debian-12-r0
<img width="960" alt="image" src="https://github.com/user-attachments/assets/b48557ef-ac54-4d84-a10c-d994bf89b9fb">
