### ISSUE TITLE
[bitnami/kube-prometheus] Helm chart version 5.0.3 (operator 0.48.0) incompatible and not working

### ISSUE THREAD

**Issue by BernhardGruen** [bitnami/charts#6495]
The operator in version 0.48.0 uses new labels for its prometheus deployment / statefulset (see
https://github.com/prometheus-operator/prometheus-operator/blob/master/CHANGELOG.md#0480--2021-05-19)

The service uses a fixed match selector (see https://github.com/bitnami/charts/blob/015d1f14823d59a59ce0f329e4bcabeb4837f232/bitnami/kube-prometheus/templates/prometheus/service.yaml#L42).

The label has to be changed to `app.kubernetes.io/name: prometheus`.

**Comment by miguelaeh** [comment]
Hi @BernhardGruen ,
Thank you very much for reporting the issue, it seems @mboutet created a PR fixing it, we will take a look.

**Comment by miguelaeh** [comment]
We need to wait until a new version of the operator is released

**Comment by BernhardGruen** [comment]
I think this issue is obsolete now. I'll close it.
