### ISSUE TITLE
Feature Request: Wordpress: consider Wordpress maintenance mode not as a Pod failure

### ISSUE THREAD

**Issue by corend** [bitnami/charts#6498]
**Which chart**:
Wordpress image from Bitnami

**Is your feature request related to a problem? Please describe.**
Avoid readinessProbe issues when WP is entering in maintenance mode which create a loop in the Pods restart process until the maintenance mode is over.
WP consider the maintenance mode as an HTTP 5xx but actually the website or the WP app is not down, it is really running background tasks that must continue to run. We cannot consider the Pods are down.

**Describe the solution you'd like**
Consider the WPMM (Wordpress Maintenance Mode) as normal behavior and do not consider WPMM as this is a breaking issue.
Change the Maintenance Mode response code to 200 simply by adding this to functions.php by default:
add_filter( 'wpmm_status_code', 200 ); 

**Describe alternatives you've considered**
Only by setting the readinessProbe check to "false". But we cannot anticipate if a user or automatic process will update WP, so this is not a long term good workaround.
Or, maybe you could (but how?) adapt the readinessProbe check for this specific case, will be of course better than changing WP functions, but I don't see how.

**Additional context**
It will help the Wordpress hosting world providers to consider to switch to Kubernetes architecture and it will avoid too many support questions for the same topic. Something that can be changed and can help end users is simply beneficial for the community.

**Comment by Mauraza** [comment]
Hi @corend,

Could you try to update the chart and change the `livenessProbe.httpGet.path` value?

**Comment by corend** [comment]
Hi @Mauraza,

I don't see how to adapt it?

**Comment by Mauraza** [comment]
Hi @corend,

What version of the chart have you installed? https://github.com/bitnami/charts/blob/2671c7a1d6d88c82bad186ec9b58bc213088eaeb/bitnami/wordpress/values.yaml#L387-L392
Could you check this issue https://github.com/bitnami/charts/issues/3019?

**Comment by corend** [comment]
Hi @Mauraza,

Whatever the version of the chart you use you will have the issue because of the architecture of wordpress. If you also try to check /wp-admin/install.php I'm afraid you will have the same issue as WP is putting the entire website in maintenance mode and not only few pages, isn't it the case?
(for your info, chart I recently used: WP 5.7.2-debian-10-r10)
Indeed the issue https://github.com/bitnami/charts/issues/3019 can be linked as same issue, if you have plugins updates or WP core update putting the site in maintenance mode it will be consider as pod is down which is actually not the case because the website needs to be run to execute the updates and this is a maintenance mode activated temporarly on pupose. So, if the pods crash/restart due to a bad interpretation of the WPMM then the update will take longer than expected to be applied.

**Comment by Mauraza** [comment]
Hi @corend,

for now, the only thing maybe helps you are using a `customLivenessProbe` using a script with the probes you considered necessary. https://github.com/bitnami/charts/blob/2671c7a1d6d88c82bad186ec9b58bc213088eaeb/bitnami/wordpress/values.yaml#L437-L439

**Comment by corend** [comment]
Hi @Mauraza,
Thank you. I will give it a try.
However this is not really the point, the point is more: WPMM architecture is defined but the default configuration chart is not taking this architecture as a given and ask to us to take it into consideration via workarounds.
In my opinion, the WPMM should be taken correctly into consideration by default by the chart without a workaround.
It will avoid such cases when you discover that your pods are failing/restarting due to a normal WPMM behavior, and then it will avoid some questions coming from new users implementing the chart on their infra.

**Comment by Mauraza** [comment]
Hi @corend,

I'm going to create an internal task to investigate more about. We will update this thread when we have more information.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
