### ISSUE TITLE
[bitnami/tomcat] initContainers template generation is broken

### ISSUE THREAD

**Issue by cache-sk** [bitnami/charts#6501]
**Which chart**:
bitnami/tomcat 9.2.7, problem exist since 9.2.4

Note: few minutes after posting this i found, that there is new 9.2.8 version, but problem persist
Note 2: after another few minutes i noticed, that very similar poblem is with sidecars, from version 9.2.4 too

**Describe the bug**
Broken template generation with initContainers in values

**To Reproduce**
1. create values yaml file with initContainers, for example init.yaml with this:
```
tomcatPassword: password123456789
initContainers:
    - name: init-test
      image: docker.io/bash:latest
      imagePullPolicy: "IfNotPresent"
      command:
          - sh
          - -c
          - ls -la
```

2. install tomcat chart, or test template, for example like this:
`helm template test-tomcat bitnami/tomcat -f init.yaml --debug > test-template.yaml`

3. result of previous command is:
```
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/cache/.cache/helm/repository/tomcat-9.2.7.tgz

Error: YAML parse error on tomcat/templates/deployment.yaml: error converting YAML to JSON: yaml: line 49: did not find expected '-' indicator
helm.go:81: [debug] error converting YAML to JSON: yaml: line 49: did not find expected '-' indicator
YAML parse error on tomcat/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
        helm.sh/helm/v3/pkg/action/install.go:245
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:242
main.newTemplateCmd.func2
        helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

3. part of generated yaml with initContainers:
```
      initContainers:- command:
        - sh
        - -c
        - ls -la
        image: docker.io/bash:latest
        imagePullPolicy: IfNotPresent
        name: init-test 
```

**Expected behavior**
Generate initContainers with correct indent.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

**Comment by cache-sk** [comment]
I just found out that even version 9.2.3 generates a correct yaml, it does not have a correct structure for kubernetes and install will fail. Seems like version 9.1.0 is latest, if you want to use initContainers/sidecars..

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. The issue is in the `_pod.tpl` file.

```
{{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) }}
```

It should be 

```
{{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 4 }}
```

We will add it to the chart. However, as you discovered the issue, would you like to submit a PR fixing it?

**Comment by cache-sk** [comment]
Can do.

**Comment by javsalgar** [comment]
Hi! 

Mi colleague @migruiz4 will continue checking. Thank you so much for creating the PR! By the way, I was wrong with the nindent parameter, it should be 0 in this case. Sorry about that
