### ISSUE TITLE
[bitnami/kafka, bitnami/zookeeper] Use label selector to further filter the set of volumes

### ISSUE THREAD

**Issue by mmenbawy** [bitnami/charts#6506]
**Which chart**:
`bitnami/kafka` and `bitnami/zookeeper`

**Is your feature request related to a problem? Please describe.**
One can not use the selector feature of the Persistent Volume Claim to filter existing Persistent Volumes.
This is a problem if you're managing an on premise cluster and you manually manage your volumes with the absence of dynamically created Persistent Volumes. 

**Describe the solution you'd like**
Adding the selector key to Kafka and Zookeeper helm charts under the `volumeClaimTemplates` key.
Same solution/ feature is implemented in [bitnami/postgres](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) chart [here](https://github.com/bitnami/charts/blob/2e63633cdce4ac1483eca8e65aed96f8f1ae2710/bitnami/postgresql/templates/statefulset.yaml#L609).

**Describe alternatives you've considered**
Currently, one can not use the `volumeClaimTemplates` key to create PVCs for the statefulset. Alternatively, one can use manually created PVCs and use the `existingClaim` helm value to pass it to the statefulset.

**Additional context**

**Comment by mmenbawy** [comment]
https://github.com/bitnami/charts/pull/6503
https://github.com/bitnami/charts/pull/6505

**Comment by alemorcuq** [comment]
Thanks for creating these PRs, @mmenbawy !
