### ISSUE TITLE
cant access my account 

### ISSUE THREAD

**Issue by satyam8518** [bitnami/charts#6508]
i connected my website via google cloud plateform, and i cant login using provided credentials by bitnami vm in google cloud. kindly please help us to connect,

**Comment by migruiz4** [comment]
Hi @satyam8518,

This is the repository for Bitnami Helm charts.
For issues with Bitnami VMs please use our community channel: https://community.bitnami.com/

Although, I'd recommend having a look at the following link in case it may help you: https://docs.bitnami.com/google/faq/get-started/find-credentials/

If you find further issues please share them in the community channel.
