### ISSUE TITLE
 externalAccess does not work for mongodb replica set

### ISSUE THREAD

**Issue by korenlev** [bitnami/charts#6518]
**Which chart**:
mongodb latest

**Describe the bug**
https://docs.bitnami.com/kubernetes/infrastructure/mongodb/configuration/configure-external-access-replicaset/ - 
using this settings fails - replica-set does not establish as members can not connect to each other using new services nor using headless DNS service.

**To Reproduce**

1. Deploy mongodb replicaset chart with above changes for externalAccess

**Expected behavior**
replica set setup successful

**Version of Helm and Kubernetes**:

-  ANY

**Comment by alvneiayu** [comment]
hi @korenlev 

I think that you are reproducing a problem with externalAccess that we are working on it.

https://github.com/bitnami/charts/issues/4073

I am working in a solution and I hope to release the solution ASAP.

Thanks a lot for reporting the issue @korenlev

Álvaro

**Comment by korenlev** [comment]
Cool stuff

בתאריך יום ג׳, 1 ביוני 2021, 10:11, מאת alvneiayu ***@***.***

**Comment by alvneiayu** [comment]
hi @korenlev 

I am going to move this issue to "on hold" until I released the solution.

Thanks a lot again

Álvaro

**Comment by korenlev** [comment]
solved
