### ISSUE TITLE
s3 access

### ISSUE THREAD

**Issue by laurent6** [bitnami/charts#6521]
**Which chart**:
elstacticseacrh version 15.2.1

**Is your feature request related to a problem? Please describe.**
I want to add s3 snapshot. To do this, we must configure elsticsearch: 
https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-client.html 
I want add keystore. I try with expect in init_scrupt but elasticsearch-keystore add  s3.client.default.access_key need confirmation. Expect command not install in all images elasticsearch. 

**Describe the solution you'd like**
Add configuration s3 with integrated s3 key et secret.

**Comment by juan131** [comment]
Hi @laurent6 

You can use the `plugins` to indicate the list of plugins to install during Elasticsearch initialization. I assume you used that parameter in combination with the `initScripts` parameter to use some script to automate the configuration of the S3 settings, am I right?

I assume the API offers a non-interactive mode for this operation, or you can try to use the workaround below using the [yes command](https://linuxhint.com/bash_yes_command):

```console
yes | YOUR_REST_COMMAND
```
