### ISSUE TITLE
redis-cluster: create STS per Master/Replica pair

### ISSUE THREAD

**Issue by Nefelim4ag** [bitnami/charts#6540]
Redis cluster:
Currently when cluster provisioned all nodes randomly joined and we can't correctly handle podAntiAffinity in cluster.

So my proporse doing something like:
Sts per group of hosts, example:
numNodes: 8
replica: 2
```
M - redis-0-0
S - redis-0-1
M - redis-1-0
S - redis-1-1
M - redis-2-0
S - redis-2-1
M - redis-3-0
S - redis-3-1
```

So that's look easy to add new nodes, manage replicas and do any sort of internal antiAffinity
As we have labels on STS pods, we can continue use current code to build up cluster

But i'm not sure about replica migration behaviour

**Comment by miguelaeh** [comment]
Hi @Nefelim4ag ,
Thank you very much for the request. We are always happy to receive PRs of that type. Would you like to create one adding such feature?

**Comment by Nefelim4ag** [comment]
I will try, then i have some free time

**Comment by plachta11b** [comment]
Hi, I would prefer labelling pods as `helm.sh/replication: master` or `helm.sh/replication: replica` and having separate label for *shard*/*partition* as `helm.sh/shard: 0` or `helm.sh/shard: master-0-hash` to avoid wildcards in podAntiAffinity/topologySpreadConstraints. So redis-2-1 would be something like `helm.sh/replication: replica`, `helm.sh/shard: 2`. I don't have much free time this month but i would love to help with this PR.
