### ISSUE TITLE
Web server logs get filled with OSError: [Errno 0] Error

### ISSUE THREAD

**Issue by Jagadeepkosuri** [bitnami/charts#6541]
**Which chart**:
Airflow 9.0.4

**Describe the bug**
When I use web SSL certificates and SSL keys, web server logs are filled as below

![image](https://user-images.githubusercontent.com/25528123/120488130-2370a500-c3d4-11eb-8908-c797e3b8bdab.png)

I don't receive these logs if I don't use SSL certificates and SSL keys.

**To Reproduce**
I have added SSL certificates and keys to image and refer those paths in airflow.cfg
web_server_ssl_cert=/usr/local/share/ca-certificates/airflow_certificate.pem
web_server_ssl_key=/usr/local/share/ca-certificates/airflow_key.pem

Everything works well, I can see the webserver UI using https, certificate is valid. 

**Expected behavior**
I shouldn't get these logs in webserver

**Version of Helm and Kubernetes**:

- Output of `helm version`:

Helm 3

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by alvneiayu** [comment]
hi @Jagadeepkosuri 

Could you share with me the values that you are using to reproduce your problem, please? Moreover, if you can share with me complete logs maybe I can see something else.

Thanks a lot

Álvaro

**Comment by Jagadeepkosuri** [comment]
> hi @Jagadeepkosuri
> 
> Could you share with me the values that you are using to reproduce your problem, please? Moreover, if you can share with me complete logs maybe I can see something else.
> 
> Thanks a lot
> 
> Álvaro

https://drive.google.com/drive/folders/1uemfpazwFlIEamanUFgeMtSc726PkbGo?usp=sharing 

You can find the values.yaml file and webserver logs attached.  I have configured airflow to throw all the error logs into another file. That file is filled with the logs I pasted in the description. It repeats the same errors multiple time (200 MB in a single day). 

Once again reminding, this is happening only if i add webserver SSL certificates and Keys only.

**Comment by alvneiayu** [comment]
hi @Jagadeepkosuri 

I am not expert in Airflow, I found this stackoverflow case that maybe it can help you:

https://stackoverflow.com/questions/51619559/socket-error-processing-request-with-flask-gunicorn-docker-and-azure

Could you do a test disabling the liveness probes to check that you can reproduce the same problem?

Thanks a lot and I hope that I have helped you

Álvaro

**Comment by Jagadeepkosuri** [comment]
hi @alvneiayu 

I have removed both liveness probe and readiness probe for webserver. Still the same logs are showing.

**Comment by alvneiayu** [comment]
hi @Jagadeepkosuri 

Let me reproduce the problem and I will come back as soon as possible.

Thanks a lot for the values.yaml and logs and sorry for the late reply

Álvaro

**Comment by alvneiayu** [comment]
hi @Jagadeepkosuri 
I am trying to reproduce the ssl problem that you mentioned. I saw the logs and I am quite confuse:
```
[2021-06-03 12:20:04,504] {plugins_manager.py:189} ERROR - Failed to import plugin /opt/bitnami/airflow/plugins/Party_Migration/Functions.py
[2021-06-03 12:20:04,889] {plugins_manager.py:188} ERROR - No module named 'pypyodbc'
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/plugins_manager.py", line 182, in <module>
    m = imp.load_source(namespace, filepath)
  File "/opt/bitnami/python/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/bitnami/airflow/plugins/Party_Migration/Test_Stories.py", line 5, in <module>
    import Functions as fn
  File "/opt/bitnami/airflow/plugins/Party_Migration/Functions.py", line 10, in <module>
    import pypyodbc
ModuleNotFoundError: No module named 'pypyodbc'
```
The problem that you are reproducing in the log is different. It seems that pypyodbc is missing.

Thanks

Álvaro

**Comment by alvneiayu** [comment]
hi @Jagadeepkosuri 

I can not reproduce your problem. I generated the key and the cert using this command:

```
openssl req -newkey rsa:2048 -nodes -keyout domain.key -x509 -days 365 -out airflow.crt
```

I generated my own image setting up the keys to enable SSL:
```
I have no name!@airflow-web-6655dbc4f5-4s9lv:/$ cat /opt/bitnami/airflow/airflow.cfg | grep ssl
web_server_ssl_cert=/opt/bitnami/airflow/airflow.crt
web_server_ssl_key=/opt/bitnami/airflow/airflow.key
```

and I can not reproduce the problem:
```
$ k logs pod/airflow-web-6655dbc4f5-4s9lv
airflow 08:23:25.57 
airflow 08:23:25.57 Welcome to the Bitnami airflow container
airflow 08:23:25.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
airflow 08:23:25.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
airflow 08:23:25.57 
airflow 08:23:25.57 INFO  ==> Enabling non-root system user with nss_wrapper
airflow 08:23:25.58 INFO  ==> ** Starting Airflow setup **
airflow 08:23:25.59 INFO  ==> Initializing Airflow ...
airflow 08:23:25.60 INFO  ==> No injected configuration file found. Creating default config file
airflow 08:23:26.13 INFO  ==> Configuring Airflow webserver authentication
airflow 08:23:26.15 INFO  ==> Configuring Airflow database
airflow 08:23:26.16 INFO  ==> Configuring Celery Executor
airflow 08:23:26.17 INFO  ==> Waiting for PostgreSQL to be available at airflow-postgresql:5432...
airflow 08:23:35.35 INFO  ==> Creating Airflow admin user
airflow 08:23:41.25 INFO  ==> Persisting Airflow installation
airflow 08:23:41.27 INFO  ==> ** Airflow setup finished! **
airflow 08:23:41.29 INFO  ==> ** Starting Airflow **
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-06-18 08:23:44,412] {dagbag.py:487} INFO - Filling up the DagBag from /dev/null
[2021-06-18 08:23:47 +0000] [206] [INFO] Starting gunicorn 20.1.0
[2021-06-18 08:23:47 +0000] [206] [INFO] Listening at: https://0.0.0.0:8080 (206)
[2021-06-18 08:23:47 +0000] [206] [INFO] Using worker: sync
[2021-06-18 08:23:47 +0000] [208] [INFO] Booting worker with pid: 208
[2021-06-18 08:23:47 +0000] [209] [INFO] Booting worker with pid: 209
[2021-06-18 08:23:47 +0000] [210] [INFO] Booting worker with pid: 210
[2021-06-18 08:23:47 +0000] [222] [INFO] Booting worker with pid: 222
```
Maybe I am missing something. Do you have an ingress or something like this? Maybe something external doing requests to your Airflow?

Thanks a lot

Álvaro

**Comment by Jagadeepkosuri** [comment]
> hi @Jagadeepkosuri
> 
> I can not reproduce your problem. I generated the key and the cert using this command:
> 
> ```
> openssl req -newkey rsa:2048 -nodes -keyout domain.key -x509 -days 365 -out airflow.crt
> ```
> 
> I generated my own image setting up the keys to enable SSL:
> 
> ```
> I have no name!@airflow-web-6655dbc4f5-4s9lv:/$ cat /opt/bitnami/airflow/airflow.cfg | grep ssl
> web_server_ssl_cert=/opt/bitnami/airflow/airflow.crt
> web_server_ssl_key=/opt/bitnami/airflow/airflow.key
> ```
> 
> and I can not reproduce the problem:
> 
> ```
> $ k logs pod/airflow-web-6655dbc4f5-4s9lv
> airflow 08:23:25.57 
> airflow 08:23:25.57 Welcome to the Bitnami airflow container
> airflow 08:23:25.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
> airflow 08:23:25.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
> airflow 08:23:25.57 
> airflow 08:23:25.57 INFO  ==> Enabling non-root system user with nss_wrapper
> airflow 08:23:25.58 INFO  ==> ** Starting Airflow setup **
> airflow 08:23:25.59 INFO  ==> Initializing Airflow ...
> airflow 08:23:25.60 INFO  ==> No injected configuration file found. Creating default config file
> airflow 08:23:26.13 INFO  ==> Configuring Airflow webserver authentication
> airflow 08:23:26.15 INFO  ==> Configuring Airflow database
> airflow 08:23:26.16 INFO  ==> Configuring Celery Executor
> airflow 08:23:26.17 INFO  ==> Waiting for PostgreSQL to be available at airflow-postgresql:5432...
> airflow 08:23:35.35 INFO  ==> Creating Airflow admin user
> airflow 08:23:41.25 INFO  ==> Persisting Airflow installation
> airflow 08:23:41.27 INFO  ==> ** Airflow setup finished! **
> airflow 08:23:41.29 INFO  ==> ** Starting Airflow **
>   ____________       _____________
>  ____    |__( )_________  __/__  /________      __
> ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
> ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
>  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
> [2021-06-18 08:23:44,412] {dagbag.py:487} INFO - Filling up the DagBag from /dev/null
> [2021-06-18 08:23:47 +0000] [206] [INFO] Starting gunicorn 20.1.0
> [2021-06-18 08:23:47 +0000] [206] [INFO] Listening at: https://0.0.0.0:8080 (206)
> [2021-06-18 08:23:47 +0000] [206] [INFO] Using worker: sync
> [2021-06-18 08:23:47 +0000] [208] [INFO] Booting worker with pid: 208
> [2021-06-18 08:23:47 +0000] [209] [INFO] Booting worker with pid: 209
> [2021-06-18 08:23:47 +0000] [210] [INFO] Booting worker with pid: 210
> [2021-06-18 08:23:47 +0000] [222] [INFO] Booting worker with pid: 222
> ```
> 
> Maybe I am missing something. Do you have an ingress or something like this? Maybe something external doing requests to your Airflow?
> 
> Thanks a lot
> 
> Álvaro

No, I don't have any ingress setup. I'm using azure external load balancer. And the for the above "pyodbc" error, try to install pyodbc pip package.

**Comment by alvneiayu** [comment]
hi @Jagadeepkosuri 

The logs that you shared with me is showing this error with pyodbc, I am not reproducing this error. I can not see your SSL errors in the logs shared with me. Could you share with me complete logs reproducing the problem? Please, could you try to reproduce the generating the certificates again using the command that I shared you before?

```
openssl req -newkey rsa:2048 -nodes -keyout domain.key -x509 -days 365 -out airflow.crt
```

Thanks a lot for your time and waiting your feedback.

Álvaro
