### ISSUE TITLE
Bad Request - Invalid Method 'Invalid HTTP method: 'ET''

### ISSUE THREAD

**Issue by rjribeiro** [bitnami/charts#6543]
**Which chart**:
airflow 10.0.8

**Describe the bug**
when I press the trigger button on the home screen, the message appears: Bad Request.
Invalid Method 'Invalid HTTP method: 'ET''.

When refreshing the screen, it is seen that the dag was started correctly.

**To Reproduce**

1. helm install my-release bitnami/airflow --set airflow.loadExamples=true
2. Go to web ui
3. Click in triger button of any dag

**Expected behavior**
dont show error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**
Using GCP GKE

**Comment by rafariossaa** [comment]
Hi,
  I was not able to reproduce this issue, I tried:
```
helm install my-release bitnami/airflow --set loadExamples=true
```
  in minikube and in a GKE cluster and I had not any issues to trigger the DAG.

![image](https://user-images.githubusercontent.com/11049367/120611841-ded91e00-c454-11eb-828d-2c4beec89db0.png)

**Comment by rafariossaa** [comment]
That `ET` message seems to be part of `GET` that your browser should be sending in the request.

Could you take a look to the headers sent by your browser when clicking the `Trigger DAG` button ?

**Comment by rjribeiro** [comment]
> That `ET` message seems to be part of `GET` that your browser should be sending in the request.
> 
> Could you take a look to the headers sent by your browser when clicking the `Trigger DAG` button ?

Hi @rafariossaa

This is the response

Request URL: https://8080-xxxxxxxxxxxxxxx.cs-us-east1-omte.cloudshell.dev/home
Request Method: GET
Status Code: 400 Bad Request
Remote Address: xx.xxx.xxx.xxx:443
Referrer Policy: strict-origin-when-cross-origin

I am using web preview of google cloud shell

**Comment by rafariossaa** [comment]
This is a weird issue.
Could you try deploying other chart, for example wordpress, or in gce directly ? I would like to discern if it is related to that environment.

**Comment by rjribeiro** [comment]
i think this happens because of the cloudshell. I deploy in cloudshell

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing. I am happy you were able to solve the issue.
