### ISSUE TITLE
kubectl port-forward dont run in background

### ISSUE THREAD

**Issue by rjribeiro** [bitnami/charts#6544]
**Which chart**:
airflow 10.0.8

**Describe the bug**
kubectl port-forward --namespace default svc/my-release 8080:8080
dont run in background. I use nohup, but at some point the port forward stops and I can no longer access airflow home

**To Reproduce**

1. helm install my-release bitnami/airflow 
2. kubectl port-forward --namespace default svc/my-release 8080:8080
3. The process dont run in background

**Expected behavior**
Run in background without nohup 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**
Using GCP GKE

**Comment by miguelaeh** [comment]
Hi @rjribeiro ,
Please add a `&` after the port-forward command

**Comment by rjribeiro** [comment]
> Hi @rjribeiro ,
> Please add a `&` after the port-forward command

Ji @miguelaeh i have tried this but it only works while the bash terminal is active. If I close the terminal, I can no longer log into airflow

**Comment by miguelaeh** [comment]
Hi @rjribeiro ,
That's expected, the process will be a child of the current terminal, if you close it the child processes will be killed.
When the parent process dies the child process will be sent a SIGHUP signal. To avoid that you can use the `nohup` command that will prevent the process to be killed.

**Comment by rjribeiro** [comment]
> Hi @rjribeiro ,
> That's expected, the process will be a child of the current terminal, if you close it the child processes will be killed.
> When the parent process dies the child process will be sent a SIGHUP signal. To avoid that you can use the `nohup` command that will prevent the process to be killed.

After a while the kubectl port-forward process started by nohup is terminated. Is there any way for nohup to rerun the process if it is interrupted?

**Comment by miguelaeh** [comment]
>After a while the kubectl port-forward process started by nohup is terminated. Is there any way for nohup to rerun the process if it is interrupted?

About this, I am not about what your issue could be, but there are some situation where nohup processes are killed, you can search the on the Internet.

> Or Is there any way to make port forwarding automatic?

I am not sure about this either, but you can try to configure a services as NodePort o LoadBalancer in order to avoid forwarding the ports manually
