### ISSUE TITLE
(postgresql-ha) Statefulset: The node name does not follow the required format

### ISSUE THREAD

**Issue by voarsh2** [bitnami/charts#6548]
**Which chart**:
postgresql-ha 

**Describe the bug**

Occasionally I have run into this problem. 
Upgrading the chart seems to "solve" this problem ,

```
postgresql-repmgr 08:09:39.73 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **

repmgr 08:09:39.85 INFO  ==> Validating settings in REPMGR_* env vars...

repmgr 08:09:39.85 ERROR ==> The node name does not follow the required format. Valid format: ^.*+-+$

/librepmgr.sh: line 118: $(MY_POD_NAME): syntax error: operand expected (error token is "$(MY_POD_NAME)")

repmgr 08:09:39.86 ERROR ==> The node id is required. Set the environment variable REPMGR_NODE_ID with the node id.
```

**To Reproduce**

Uncertain. Happens often when Longhorn volume is used and struggles to start up.

**Expected behavior**

Should pick up the 0 and 1 from statefulset in the pod

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3-rancher3", GitCommit:"657df59bbba1d9e175cf5080d4885bd57d037906", GitTreeState:"clean", GoVersion:"go1.13.15"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  That error came from [this check](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/b517cdd985ec4be9cac311e4f60786f0c8a8e578/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L98), and `REPMGR_NODE_NAME` is set with the node name in the chart.
  Could you check the name of the pods when this happen ?

**Comment by voarsh2** [comment]
They're all correct.


Running 
```
helm upgrade postgresql-ha bitnami/postgresql-ha --set postgresql.password=$POSTGRESQL_PASSWORD --set pgpool.adminPassword=$ADMIN_PASSWORD --set postgresql.repmgrPassword=$REPMGR_PASSWORD
```
Seems to 'bring it back' 

All the pods are named properly, as they are statefulsets.:

```
postgresql-ha-postgresql-0
postgresql-ha-postgresql-1
```

**Comment by rafariossaa** [comment]
Could you enable the debug and provide them when this happens again ?
