### ISSUE TITLE
Unable to get HELM_CHART.NO_DETAIL and helm fetch and helm install when install harbors

### ISSUE THREAD

**Issue by FighterLD** [bitnami/charts#6549]
Unable to get HELM_CHART.NO_DETAIL and helm fetch and helm install when install harbors

fail to get chart version: not found

{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
Could you please elaborate on what are you doing, commands, etc please?

**Comment by FighterLD** [comment]
1、curl call API get the chart information:
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/
[{"name":"nginx-ingress","home":"https://github.com/kubernetes/ingress-nginx","sources":["https://github.com/kubernetes/ingress-nginx"],"version":"0.21.0","description":"An nginx Ingress controller that uses ConfigMap to store the nginx configuration.","keywords":["ingress","nginx"],"maintainers":[{"name":"jackzampolin","email":"jack.zampolin@gmail.com"},{"name":"mgoodness","email":"mgoodness@gmail.com"}],"icon":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png","apiVersion":"v1","appVersion":"0.21.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress-0.21.0.tgz"],"created":"2021-06-03T09:33:10.565621902Z","digest":"6045e6e93212a6f1bab8b9b6f44f1f98d527ff6f7f23fcd56fd1bae1615f591c","labels":[]}]
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/0.21.0
{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}


2、Web UI opens the chart version of the times was wrong：
fail to get chart version: not found

HELM_CHART.NO_DETAIL

**Comment by FighterLD** [comment]
I used the official helm when the deployment is chart, when you call the API for chart information, the information is as follows

$curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs
[{"name":"openebs","home":"http://www.openebs.io/","sources":["https://github.com/openebs/openebs"],"version":"2.6.0","description":"Containerized Storage for Containers","keywords":["cloud-native-storage","block-storage","iSCSI","storage"],"maintainers":[{"name":"kmova","email":"kiran.mova@openebs.io"},{"name":"prateekpandey14","email":"prateek.pandey@openebs.io"}],"icon":"https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png","apiVersion":"v1","appVersion":"2.6.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs-2.6.0.tgz"],"created":"2021-06-03T09:12:38Z","digest":"a946abe17e9ec5dfd6cfd039c0f165c71f12217ed7254a98120e0ba51fc36e06","labels":[]}]
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs/2.6.0
{"metadata":{"name":"openebs","home":"http://www.openebs.io/","sources":["https://github.com/openebs/openebs"],"version":"2.6.0","description":"Containerized Storage for Containers","keywords":["cloud-native-storage","block-storage","iSCSI","storage"],"maintainers":[{"name":"kmova","email":"kiran.mova@openebs.io"},{"name":"prateekpandey14","email":"prateek.pandey@openebs.io"}],"icon":"https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png","apiVersion":"v1","appVersion":"2.6.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs-2.6.0.tgz"],"created":"2021-06-03T09:12:38Z","digest":"a946abe17e9ec5dfd6cfd039c0f165c71f12217ed7254a98120e0ba51fc36e06"},

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
I still don't know what you are trying to do, please try to explain it.
It seems you are requesting a chart version that has not been uploaded. You need to manually upload the chart version before trying to fetch it.

**Comment by FighterLD** [comment]
I installed harbor in the following way, and the installation was successful, and successfully uploaded the chart package, I tried to use harbor's api to obtain the helm chart version information that had been manually uploaded to the harbor project, will report the error;

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install harbor bitnami/harbor

helm repo add xxx --username=yyy--password=zzz http://xxx.yyy.com/chartrepo/xxx
helm push nginx-ingress-0.21.0.tgz xxx
Pushing nginx-ingress-0.21.0.tgz to xxx...
Done.

1、curl call API get the chart information:
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/
[{"name":"nginx-ingress","home":"https://github.com/kubernetes/ingress-nginx","sources":["https://github.com/kubernetes/ingress-nginx"],"version":"0.21.0","description":"An nginx Ingress controller that uses ConfigMap to store the nginx configuration.","keywords":["ingress","nginx"],"maintainers":[{"name":"jackzampolin","email":"jack.zampolin@gmail.com"},{"name":"mgoodness","email":"mgoodness@gmail.com"}],"icon":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png","apiVersion":"v1","appVersion":"0.21.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress-0.21.0.tgz"],"created":"2021-06-03T09:33:10.565621902Z","digest":"6045e6e93212a6f1bab8b9b6f44f1f98d527ff6f7f23fcd56fd1bae1615f591c","labels":[]}]
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/0.21.0
{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}

2、Web UI opens the chart version of the times was wrong：
fail to get chart version: not found

HELM_CHART.NO_DETAIL


After I deployed through the harbor official helm chart, the same api calls and web ui access to the chart version information were normal;

$curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs
[{"name":"openebs","home":"http://www.openebs.io/","sources":["https://github.com/openebs/openebs"],"version":"2.6.0","description":"Containerized Storage for Containers","keywords":["cloud-native-storage","block-storage","iSCSI","storage"],"maintainers":[{"name":"kmova","email":"kiran.mova@openebs.io"},{"name":"prateekpandey14","email":"prateek.pandey@openebs.io"}],"icon":"https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png","apiVersion":"v1","appVersion":"2.6.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs-2.6.0.tgz"],"created":"2021-06-03T09:12:38Z","digest":"a946abe17e9ec5dfd6cfd039c0f165c71f12217ed7254a98120e0ba51fc36e06","labels":[]}]
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs/2.6.0
{"metadata":{"name":"openebs","home":"http://www.openebs.io/","sources":["https://github.com/openebs/openebs"],"version":"2.6.0","description":"Containerized Storage for Containers","keywords":["cloud-native-storage","block-storage","iSCSI","storage"],"maintainers":[{"name":"kmova","email":"kiran.mova@openebs.io"},{"name":"prateekpandey14","email":"prateek.pandey@openebs.io"}],"icon":"https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png","apiVersion":"v1","appVersion":"2.6.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/openebs-2.6.0.tgz"],"created":"2021-06-03T09:12:38Z","digest":"a946abe17e9ec5dfd6cfd039c0f165c71f12217ed7254a98120e0ba51fc36e06"},

**Comment by miguelaeh** [comment]
Can you see on the UI that the Chart version si properly uploaded?

**Comment by FighterLD** [comment]
You can see the normal upload, I have tried to pain helm xxx.tgz and manually uploaded through the web ui page, and can return to sucess, but when I View Chart Version Details, will report errors(fail to get chart version: not found HELM_CHART.NO_DETAIL), through the command call api query version information is also wrong;

curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/
[{"name":"nginx-ingress","home":"https://github.com/kubernetes/ingress-nginx","sources":["https://github.com/kubernetes/ingress-nginx"],"version":"0.21.0","description":"An nginx Ingress controller that uses ConfigMap to store the nginx configuration.","keywords":["ingress","nginx"],"maintainers":[{"name":"jackzampolin","email":"jack.zampolin@gmail.com"},{"name":"mgoodness","email":"mgoodness@gmail.com"}],"icon":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png","apiVersion":"v1","appVersion":"0.21.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress-0.21.0.tgz"],"created":"2021-06-03T09:33:10.565621902Z","digest":"6045e6e93212a6f1bab8b9b6f44f1f98d527ff6f7f23fcd56fd1bae1615f591c","labels":[]}]
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/0.21.0
{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
Could you try cleaning the redis cache and re-uploading the chart?

**Comment by FighterLD** [comment]
I've had redis caches and tried to remove redis, reinstall them, and the problem is the same

**Comment by FighterLD** [comment]
I've tried deploying with the official harbor helm chart package, and that's not a problem；

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
I tried to reproduce your issue but it seems to be working fine in my case. I deployed the Harbor Helm chart, uploaded a new chart manually and then I can use the curl request properly for both API versions `1` and `2`:
```
bitnami@dockerdev [~]
11:24:48 › curl -Lk https://admin:<password>@core.g.dev.bitnami.net/api/v2.0/chartrepo/library/charts/elasticsearch/15.3.0/labels
[]%

bitnami@dockerdev [~]
11:28:01 › curl -Lk https://admin:<password>@core.g.dev.bitnami.net/api/v2.0/chartrepo/library/charts/elasticsearch/
{"errors":[{"code":"NOT_FOUND","message":"path /api/v2.0/chartrepo/library/charts/elasticsearch/ was not found"}]}

bitnami@dockerdev [~]
11:28:08 › curl -Lk https://admin:<password>@core.g.dev.bitnami.net/api/chartrepo/library/charts/elasticsearch/
[{"name":"elasticsearch","home":"https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch","sources":["https://github.com/bitnami/bitnami-docker-elasticsearch","https://www.elastic.co/products/elasticsearch"],"version":"15.3.0","description":"A highly scalable open-source full-text search and analytics engine","keywords":["elasticsearch"],"maintainers":[{"name":"Bitnami","email":"containers@bitnami.com"}],"icon":"https://bitnami.com/assets/stacks/elasticsearch/img/elasticsearch-stack-220x234.png","apiVersion":"v2","appVersion":"7.13.1","annotations":{"category":"Analytics"},"dependencies":[{"name":"common","version":"1.x.x","repository":"https://charts.bitnami.com/bitnami","tags":["bitnami-common"]},{"name":"kibana","version":"8.x.x","repository":"https://charts.bitnami.com/bitnami","condition":"global.kibanaEnabled"}],"urls":["charts/elasticsearch-15.3.0.tgz"],"created":"2021-06-10T10:37:51.460880546Z","digest":"11807c02623d0a520cd0156ac700fec1070dbeda85282fc95573d339ff79726e","labels":[]}]%
```

**Comment by FighterLD** [comment]
The first thing I described was getting information about the chart package, but not getting a specific version of the information, and you can look at my previous commands：
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/
[{"name":"nginx-ingress","home":"https://github.com/kubernetes/ingress-nginx","sources":["https://github.com/kubernetes/ingress-nginx"],"version":"0.21.0","description":"An nginx Ingress controller that uses ConfigMap to store the nginx configuration.","keywords":["ingress","nginx"],"maintainers":[{"name":"jackzampolin","email":"jack.zampolin@gmail.com"},{"name":"mgoodness","email":"mgoodness@gmail.com"}],"icon":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png","apiVersion":"v1","appVersion":"0.21.0","urls":["http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress-0.21.0.tgz"],"created":"2021-06-03T09:33:10.565621902Z","digest":"6045e6e93212a6f1bab8b9b6f44f1f98d527ff6f7f23fcd56fd1bae1615f591c","labels":[]}]
$ curl -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/0.21.0
{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}


I also use the commands you provided to see, the same problem, can get the chart package information, but can not get the specific version of the information：
 $ curl -Lk http://admin:Harbor12345@xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/
[{"name":"nginx-ingress","home":"https://github.com/kubernetes/ingress-nginx","sources":["https://github.com/kubernetes/ingress-nginx"],"version":"0.21.0","description":"An nginx Ingress controller that uses ConfigMap to store the nginx configuration.","keywords":["ingress","nginx"],"maintainers":[{"name":"jackzampolin","email":"jack.zampolin@gmail.com"},{"name":"mgoodness","email":"mgoodness@gmail.com"}],"icon":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png","apiVersion":"v1","appVersion":"0.21.0","urls":["http://xxx.yyy.com/chartsrepo/zzz/charts/nginx-ingress-0.21.0.tgz"],"created":"2021-06-07T02:31:09.975106372Z","digest":"ef90d3df06400fdad8c055b320e6775b36c07bc92d45ab478e32eeb0fdec4253","labels":[]}]

$ curl -Lk http://admin:Harbor12345@xxx.yyy.com/api/chartrepo/zzz/charts/nginx-ingress/0.21.0
{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
Getting the specific version also works in my case, you can see the partial output below:
```
10:11:44 › curl -Lk https://admin:<password>@core.g.dev.bitnami.net/api/chartrepo/library/charts/elasticsearch/15.3.0
{"metadata":{"name":"elasticsearch","home":"https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch","sources":["https://github.com/bitnami/bitnami-docker-elasticsearch","https://www.elastic.co/products/elasticsearch"],"version":"15.3.0","description":"A highly scalable open-source full-text search and analytics engine","keywords":["elasticsearch"],"maintainers":[{"name":"Bitnami","email":"containers@bitnami.com"}],"icon":"https://bitnami.com/assets/stacks/elasticsearch/img/elasticsearch-stack-220x234.png","apiVersion":"v2","appVersion":"7.13.1","annotations":{"category":"Analytics"},"dependencies":[{"name":"common","version":"1.x.x","repository":"https://charts.bitnami.com/bitnami","tags":["bitnami-common"]},{"name":"kibana","version":"8.x.x","repository":"https://charts.bitnami.com/bitnami","condition":"global.kibanaEnabled"}],"urls":["charts/elasticsearch-15.3.0.tgz"],"created":"2021-06-10T10:37:51.460880546Z","digest":"11807c02623d0a520cd0156ac700fec1070dbeda85282fc95573d339ff79726e"},"dependencies":[{"name":"common","version":"1.x.x","repository":"https://charts.bitnami.com/bitnami","tags":["bitnami-common"]},{"name":"kibana","version":"8.x.x","repository":"https://charts.bitnami.com/bitnami","condition":"global.kibanaEnabled"}],"values":{"clusterDomain":"cluster.local","coordinating.autoscaling.enabled":false,"coordinating.autoscaling.maxReplicas":11,"coordinating.autoscaling.minReplicas":2,"coordinating.heapSize":"128m","coordinating.hostAliases":[],"coordinating.livenessProbe.enabled":false,"coordinating.nodeAffinityPreset.key":"","coordinating.nodeAffinityPreset.type":"","coordinating.nodeAffinityPreset.values":[],"coordinating.podAffinityPreset":"","coordinating.podAntiAffinityPreset":"","coordinating.readinessProbe.enabled":false,"coordinating.replicas":2,"coordinating.resources.requests.cpu":"25m","coordinating.resources.requests.memory":"25
```

**Comment by FighterLD** [comment]
OK ，thank you ，Which harbor charts version do you use?

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
I installed the version `10.1.0` of the chart.

**Comment by FighterLD** [comment]
Hi @miguelaeh 

When I set the relative path, I do get verison information, but I want to get absolute path to version information;

$ curl -Lk -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/postgresql-ha/7.4.0
{"metadata":{"name":"postgresql-ha","home":"https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha","sources":["https://github.com/bitnami/bitnami-docker-postgresql","https://www.postgresql.org/"],"version":"7.4.0","description":"Chart for PostgreSQL with HA architecture (using Replication Manager (repmgr) and Pgpool).","keywords":["postgresql","repmgr","pgpool","postgres","database","sql","replication","cluster","high availability"],"maintainers":[{"name":"Bitnami","email":"containers@bitnami.com"}],"icon":"https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png","apiVersion":"v2","appVersion":"11.11.0","annotations":{"category":"Database"},"dependencies":[{"name":"common","version":"1.x.x","repository":"https://charts.bitnami.com/bitnami"}],"urls":["charts/postgresql-ha-7.4.0.tgz"],

but "urls":["charts/postgresql-ha-7.4.0.tgz"] is relative path； I want get absolute path is "urls":["http://xxx.yyy.com/chartrepo/zzz/charts/postgresql-ha-7.4.0.tgz"] 

if i set  registry.relativeurls: true；it will return this message：
$ curl -Lk -uusername:password http://xxx.yyy.com/api/chartrepo/zzz/charts/postgresql-ha/7.4.0
{"errors":[{"code":"NOT_FOUND","message":"fail to get chart version: not found"}]}

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
Could you share the exact parameters you are using to deploy the chart so I can reproduce the issue please?

**Comment by FighterLD** [comment]
Hi @miguelaeh

the exact parameters with my harbor chart：

service:
  type: ClusterIP
  tls:
    enabled: true

ingress:
  enabled: true
  hosts:
    core: xxx.yyy.com
    notary: xxx.zzz.com
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'

externalURL: https://xxx.yyy.com
harborAdminPassword: "xxxxxx"
persistence:
  imageChartStorage:
    disableredirect: true
    type: s3
    filesystem:
      rootdirectory: /storage
    s3:
      region: us-west-1
      bucket: registry
      accesskey: xxxxxx
      secretkey: xxxxxxxx
      regionendpoint: http://minio:9000
      encrypt: false
      secure: false
      skipverify: false
      v4auth: true
      chunksize: "5242880"
      rootdirectory: /
      multipartcopychunksize: "33554432"
      multipartcopymaxconcurrency: 10000
      multipartcopythresholdsize: "33554432"

redis:
  enabled: false
externalRedis:
  host: redis-ha-haproxy.component
  port: 6379
  sentinel:
    enabled: true
    masterSet: 'mymaster'
    hosts: 'redis-ha-announce-0.component:26379,redis-ha-announce-1.component:26379,redis-ha-announce-2.component:26379'
  password: 'sensetime'

postgresql:
  enabled: false
externalDatabase:
  host: postgresql-ha-pgpool.component
  user: postgres
  password: 'postgres'
  port: 5432
  sslmode: disable
  coreDatabase: registry
  clairDatabase: clair
  clairUsername: postgres
  clairPassword: postgres
  notaryServerDatabase: notary_server
  notaryServerUsername: postgres
  notaryServerPassword: postgres
  notarySignerDatabase: notary_signer
  notarySignerUsername: postgres
  notarySignerPassword: postgres

portal:
  enabled: true
  replicas: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      cpu: 400m
      memory: 1Gi

core:
  enabled: true
  replicas: 2
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      cpu: 400m
      memory: 1Gi

jobservice:
  enabled: true
  replicas: 2
  jobLogger: database
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      cpu: 400m
      memory: 1Gi

registry:
  enabled: true
  replicas: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      cpu: 400m
      memory: 1Gi

chartmuseum:
  absoluteUrl: true
  chartRepoName: 'chartsrepo'
  enabled: true
  replicas: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      cpu: 400m
      memory: 1Gi

trivy:
  enabled: false
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 1Gi

notary:
  enabled: true
  server:
    replicas: 2
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        cpu: 400m
        memory: 1Gi
  signer:
    replicas: 2
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        cpu: 400m
        memory: 1Gi

**Comment by FighterLD** [comment]
Hi @miguelaeh
When I do mirror synchronization, the following errors appear, synchronization failure;
failed to fetch artifacts: failed to list artifacts of repository 'xxxx/yyyy': http error: code 403, message {"errors": [{"code": "FORBIDDEN", "message": "forbidden"}]}

**Comment by miguelaeh** [comment]
Hi @FighterLD ,
`403` is a permission error, so probably you are using the wrong credentials in the requests
