### ISSUE TITLE
[bitnami/magento] Persistent MySQL Connection

### ISSUE THREAD

**Issue by mahgo** [bitnami/charts#6550]
**Which chart**:
bitnami/magento, latest.

**Is your feature request related to a problem? Please describe.**
It would be good to be able to turn on persistent connection to the MySQL database, so that Magento keeps reusing the existing connection instead of creating a new one for every request.  This can be achieved by adding the following line in the db section of the env.php file: `'persistent' => '1'`. See https://docs.microsoft.com/en-us/azure/architecture/example-scenario/magento/magento-azure#database-connection

**Describe the solution you'd like**
Being able to set externalDatabase.persistent = true

**Describe alternatives you've considered**
This is definitely the easiest way to achieve this. The only way I could think of doing this is to make my own image but that's a lot of work for something this simple.

**Comment by miguelaeh** [comment]
Hi @mahgo ,
Would you like to create a PR adding that property? It would be nice if you can default it to how it is currently set and add a new env var to use persistent connections

**Comment by mahgo** [comment]
Hi @miguelaeh,

Sure I'll give it a go.

**Comment by mahgo** [comment]
I'm actually struggling to find any Magento documentation on this feature - does it still exist in Magento?

**Comment by alemorcuq** [comment]
Hi, @mahgo. I suggest you to ask this question in the Magento Community (https://magento.com/community) as we are not experts on the application itself.

**Comment by mahgo** [comment]
Thanks - will do.
