### ISSUE TITLE
[bitnami/magento], [bitnami/redis] Add HorizontalPodAutoscaler to chart

### ISSUE THREAD

**Issue by mahgo** [bitnami/charts#6551]
Edit: added Redis to feature suggestion as well.

**Which chart**:
bitnami/magento, bitnami/redis, latest

**Is your feature request related to a problem? Please describe.**
It'd be good to be able to enable a HPA for Magento + Elasticsearch, and Redis and not having to create and manage one manually.

**Describe the solution you'd like**
Being able to enable autoscaling and set settings via helm chart values would be good. Something like https://github.com/kubernetes/ingress-nginx/blob/9e89951ec76045f69058a6bd68692715364627d5/charts/ingress-nginx/values.yaml#L318

**Describe alternatives you've considered**
Creating manually, but doing this means it is managed separately which is not ideal.

**Comment by alvneiayu** [comment]
hi @mahgo 

This is a really good idea, we already have HPA in others charts We are open to receive PRs. I will be really glad to review it and to help you.

Thanks a lot

Álvaro

**Comment by mahgo** [comment]
Hi @alvneiayu,

Sure I'll give it a go.

**Comment by mahgo** [comment]
Hi @alvneiayu,

I've added a Redis HPA pull request: https://github.com/bitnami/charts/pull/6556 however I wasn't able to test it, as the Redis chart pods were CrashLoopBackOff'ing even before I made any changes. Does this occur for you?

I'll start on magento HPA now

**Comment by alvneiayu** [comment]
hi @mahgo 

I am not reproducing this problem. Let me check it but Redis is working fine for me. I will test the HPA PR in my local and I will come back with some info.

Thanks a lot for your work

Álvaro

**Comment by alvneiayu** [comment]
hi @mahgo 

I can not reproduce your problem, Redis is working properly and the hpa is created as well.

Thanks a lot

Álvaro
