### ISSUE TITLE
[bitnami/postgres-ha] - Having multiple primaries after killing main process on primary pod

### ISSUE THREAD

**Issue by giladneiger** [bitnami/charts#6555]
**Which chart**:
bitnami/postgres-ha:7.6.0

**Describe the bug**
After killing (for HA testing purposes) the main process (pid 1) there are 2 primary replicas in the cluster. Moreover, we are getting 2 different results from 2 different replicas.

replica 0:
![image](https://user-images.githubusercontent.com/40278137/120675317-a01b8600-c49d-11eb-9481-8bc4698fad02.png)

replica 1:
![image](https://user-images.githubusercontent.com/40278137/120673443-d9eb8d00-c49b-11eb-833e-ef4ab6d6dfd4.png)

**To Reproduce**

1. We used the following image tags:
        - bitnami/pgpool:4.2.3-debian-10-r2
        - bitnami/postgresql-repmgr:12.6.0-debian-10-r85
2. Install helm chart with postgres replicas count set to 3
3. Run the following command on the primary postgres pod: `kubectl exec -i postgresql-0 -- kill -2 1`
4. `kubectl exec` to a postgres replica and run the following command: `/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show`. You will probably see multiple primaries. If not - try running the command again on a different replica (1 or 2). It's inconsistent.
5. This error is inconsistent. Sometimes it happens and sometimes not.

**Expected behavior**
We expected to have 1 primary replica. And also expected to have the same response from the replicas.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by miguelaeh** [comment]
Hi @giladneiger ,
thank you very much for reporting the issue. I agree that should not happen, do you know if after some time the primaries come back to only one? I mean, is it a transient state or will the cluster remain on that state forever?

**Comment by arimiz** [comment]
Hi @miguelaeh , no the cluster remaining in split brain state..

**Comment by miguelaeh** [comment]
Thank you very much for reporting the issue, I will create an internal task to investigate it.

**Comment by sulin-cogiot** [comment]
I meet the same problem.

**Comment by ltsbkuster** [comment]
I encountered the same issue some time ago. The problem was "bad timing". While the standby nodes are deciding whos going to be the new primary, the old primary is already up again and checking for a new primary. However it does not find that new primary yet and abd decides to be primary itself. *However I did not kill the postgres process itself, i killed the whole pod for recovery testing.*

It also depends how fast your pvc is attached to your pods (on minikube this goes really fast, so the failed primary is up again pretty fast). On azure i observed this process takes some longer time, attaching the disk to the underlying node, and not always leading to this issue.

I solved it by tweaking `postgresql.repmgrReconnectInterval=2`, so standby are failbacking faster, and hopefully are ready when the failed primary is coming up again. I hope this might help investigating this issue.

**Comment by miguelaeh** [comment]
Thank you very much @ltsbkuster ! We will take that into account

**Comment by MortenGredal** [comment]
For what it's worth, I've been able to replicate this behaviour consistently by:
- Use default values
- While running some script that inserts data using the pgpool as proxy (in this case I used a spring boot hibernate application)
- Kill node 0.
- The script fails inserts for 5-10 seconds postgresql-ha does the primary switcheroo from node-0 to node-1.
- Node 0 comes back up and is registered healthy by k8s
- pgpool now proxies to **both** nodes as primary

I also observed that if I kill node-1 after the split brain starts occurring, node-1 will on startup once again be marked as standby.

**Comment by miguelaeh** [comment]
Hi guys,
Thank you very much for the additional information.
I am afraid we are small team so we didn't have the time to work on this yet. I will try to rise the priority of this, but we cannot provide an ETA.

**Comment by vincentchong1** [comment]
can I set auto_failback?  Is it going to function as design?

helm version - 
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

kubectl version - 
lient Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

postgresql-ha version -
chart - postgresql-ha-7.5.3
app version -  11.12.0

even though follow command completed without issue, but some parameters are not set accordingly, i.e maxReplicationSlots, audit.logHostname, autoFailback.  At least they are not set in conf file.

`helm install postgresql \
--set \
replication.enabled=true,\
persistence.enabled=false,\
pgpool.childLifeTime=0,\
pgpool.replicaCount=2,\
pgpool.logHostname=false,\
pgpool.numInitChildren=250,\
pgpool.autoFailback=true,\
postgresql.audit.logHostname=false,\
postgresql.maxReplicationSlots=16,\
postgresql.maxConnections=500 \
--version 7.5.3 localrepo/postgresql-ha
`

**Comment by miguelaeh** [comment]
Hi @vincentchong1 ,
You can add the parameters that exist [here](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml). `autoFailback` does not seem to exist so the chart won't know about it.
Nevertheless, you can use [this parameter](https://github.com/bitnami/charts/blob/45d3857997a3b3b30817379cbc946b6dc599d710/bitnami/postgresql-ha/values.yaml#L864) to add configuration to PgPool.

**Comment by jpsn123** [comment]
@miguelaeh  I also encountered split-brain and it resulted in the loss of production data. 😣   Inspired by @vincentchong1 
 ,  how about param `detach_false_primary` in pgpool conf.

**Comment by vishrantgupta** [comment]
@jpsn123 I tried the `detach_false_primary` but I was getting the following issue:

```
primary 1 does not connect to standby 2
primary 1 owns only 0 standbys out of 1
```

I changed the PostgreSQL config to:

```
synchronous_commit = remote_apply
```

and pgpool config to:

```
failover_on_backend_error = 'on'
search_primary_node_timeout = 0
```

and this recommendation https://github.com/bitnami/charts/issues/5589#issuecomment-966162463

After these changes, I am not seeing multiple primaries issue.

**Comment by miguelaeh** [comment]
Hi @vishrantgupta ,
Thank you very much for your investigation!
I will try to elevate the priority of this task again

**Comment by carrodher** [comment]
I'm closing this issue since different PRs were merged in order to solve this issue (for example https://github.com/bitnami/charts/pull/9035).
Please, don't hesitate to reopen it if you are still facing this issue using the latest Helm chart version. If you face a different issue, please create a new ticket.
