### ISSUE TITLE
[bitnami/mongodb] no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by ttwwaaoo** [bitnami/charts#6558]
https://github.com/bitnami/charts/blob/2f9d3b27500a02397b2a6ecbada0fef9773234f6/bitnami/mongodb/values.yaml#L1200

will get error `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

should keep the same name with kind of servicemonitor.yaml in templates

**Comment by marcosbc** [comment]
@ttwwaaoo Note that it is part of the official CRD: https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

You can try and recreate the CRD on your side. You can perform action on CRDs via `customresourcedefinition` objects on Kubectl, for instance:

```
$ kubectl get customresourcedefinition
```

**Comment by enterpriseSoftware** [comment]
I'm having this problem as well along with other issues that are similar.  What is the resolution?
[unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
helm.go:75: [debug] [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]

**Comment by ShawnMcGough** [comment]
I solved by downloading all [these](https://github.com/prometheus-operator/prometheus-operator/tree/master/example/prometheus-operator-crd) yaml files and installing each one.

```bash 
for i in *.yaml; do
    [ -f "$i" ] || break
    kubectl apply -f $i
done
```
