### ISSUE TITLE
[bitnami/thanos] Allow for `alertmanagers.config` to be specified instead of `alertmanagers.url`

### ISSUE THREAD

**Issue by jandersen-plaid** [bitnami/charts#6570]
**Which chart**:
bitnami/thanos  v3.17.7 (specifically the ruler component

**Describe the bug**
The `alertmanagers.url` value is mandatory when creating the `ruler` component for the chart, but this unfortunately does not allow for specifying `alertmanagers.config` or `alertmanagers.config-file` as extra flags (see [the docs](https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#flags) for the mutual exclusion). 

**To Reproduce**

Install the Thanos ruler chart without an `alertmanagers.url` array, and the installation will fail. Or, install the chart with an `alertmanagers.url` array and set the `--alertmanagers.config-file` to anything under the `extraFlags` of the ruler. You will receive the error:

```
--alertmanagers.url and --alertmanagers.config* parameters cannot be defined at the same time
main.registerRule.func1
	/app/cmd/thanos/rule.go:176
main.main
	/app/cmd/thanos/main.go:129
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
preparing rule command failed
main.main
	/app/cmd/thanos/main.go:131
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

**Expected behavior**
The chart should allow for users to omit `alertmanagers.url` if they give a config or config file instead -- especially useful for cases where Alertmanagers could be behind basic auth or need a bearer token.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T12:01:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
```

**Additional context**
I will submit a PR with a patch that effectively makes the 3 options mutually exclusive with each other in the chart values (though the `config file` may be a `bring your own secret` situation.

**Comment by alemorcuq** [comment]
Thanks for the PR, @jandersen-plaid. We will review it as soon as possible.
