### ISSUE TITLE
[bitnami/discourse] 127.0.0.1 being used as hostname in attachment previews

### ISSUE THREAD

**Issue by mattcg** [bitnami/charts#6572]
**Which chart**:
discourse 4.0.0

**Describe the bug**
We used chart v2.1.1 for months with no problems. After upgrading to 4.0.0, when creating posts with image uploads, the preview URLs are created by Discourse with a hostname of 127.0.0.1. Both `discourse.host` and `discourse.hostname` are set in the values YAML.

For example:

```
<img src="https://127.0.0.1/secure-media-uploads/optimized/2X/5/[redacted].png" alt="[redacted]" data-base62-sha1="[redacted]" width="500" height="500" class="d-lazyload d-lazyload-hidden">
```

**To Reproduce**

As above.

**Expected behavior**

The preview URLs are created as before, with the correct hostname.

**Version of Helm and Kubernetes**:

- Output of `kubectl version`:

v1.21.1

**Comment by marcosbc** [comment]
Hi @mattcg, thanks for reporting this. We have been able to reproduce this issue and are working on merging a fix and launching a new release. Stay tuned for new `bitnami/discourse` chart releases.
