### ISSUE TITLE
[bitnami/mysql] Chat applies Service annotations to headless service

### ISSUE THREAD

**Issue by wolf31o2** [bitnami/charts#6576]
**Which chart**:
bitnami/mysql 8.5.9

**Describe the bug**
Chart applies configured Service annotations to headless services, which can cause problems with some other cluster applications, such as external-dns.

**To Reproduce**
Configure `primary.service.annotations` with `external-dns.alpha.kubernetes.io/hostname: foo` and the annotation will appear on both the `mysql-primary` and `mysql-primary-headless` services, which will compete/race in external-dns to see which service owns the hostname and registers in DNS.

**Expected behavior**
Annotations are only applied to the `mysql-primary` service and the `mysql-primary-headless` service is treated as internal-only without the annotations. Alternative: a set of annotations for each

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @wolf31o2, thanks for reporting! It does indeed seem to be an issue with your use case. Would you be open to contributing a fix via PR?
