### ISSUE TITLE
[postgresql-ha] Cannot start postgresql-ha stack

### ISSUE THREAD

**Issue by idealtech-i3dlabs** [bitnami/charts#6579]
**Which chart**:
```
bitnami/postgresql-ha	7.6.1        	11.12.0    	Chart for PostgreSQL with HA architecture
```

**Describe the bug**

In the logs for pgpool pod (after helm successfully launches the chart) I get:
```
2021-06-05 11:25:13: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
2021-06-05 11:25:13: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
2021-06-05 11:25:13: pid 1: ERROR:  failed to make persistent db connection
2021-06-05 11:25:13: pid 1: DETAIL:  connection to host:"postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless:5432" failed
2021-06-05 11:25:13: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
2021-06-05 11:25:13: pid 1: LOG:  child process with pid: 157 exits with status 256
2021-06-05 11:25:13: pid 1: LOG:  fork a new child process with pid: 172
```

Service defined after launch:
```
dev        postgresql-ha-pgpool                LoadBalancer   10.110.178.124   10.2.172.180   5432:32691/TCP           14m
dev        postgresql-ha-postgresql            ClusterIP      10.109.13.215    <none>         5432/TCP                 14m
dev        postgresql-ha-postgresql-headless   ClusterIP      None             <none>         5432/TCP                 14m
```

In the logs for statefulset I get:
```
postgresql-repmgr 11:34:19.53 
postgresql-repmgr 11:34:19.53 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:34:19.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 11:34:19.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 11:34:19.54 
postgresql-repmgr 11:34:19.56 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:34:19.59 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:34:19.60 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:34:19.60 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:34:19.72 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 11:34:19.73 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 11:34:19.92 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 11:34:19.94 INFO  ==> Initializing Repmgr...
postgresql-repmgr 11:34:19.94 INFO  ==> Waiting for primary node...
```

Statefulsets are as follows:
```
dev           postgresql-ha-pgpool-5d56969d59-cv5bb               0/1     CrashLoopBackOff   9          22m
dev           postgresql-ha-postgresql-0                          0/1     CrashLoopBackOff   9          22m
dev           postgresql-ha-postgresql-1                          0/1     CrashLoopBackOff   8          22m
```

Describing the pod result in:
```
Events:
  Type     Reason                  Age                     From                     Message
  ----     ------                  ----                    ----                     -------
  Normal   Scheduled               9m38s                   default-scheduler        Successfully assigned dev/postgresql-ha-postgresql-0 to node04
  Normal   SuccessfulAttachVolume  9m39s                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-bc6c986f-8ce9-468b-ae59-90ac6def9afa"
  Normal   Pulled                  7m35s (x5 over 9m35s)   kubelet                  Container image "docker.io/bitnami/postgresql-repmgr:11.12.0-debian-10-r20" already present on machine
  Normal   Created                 7m35s (x5 over 9m34s)   kubelet                  Created container postgresql
  Normal   Started                 7m35s (x5 over 9m34s)   kubelet                  Started container postgresql
  Warning  BackOff                 4m34s (x24 over 9m18s)  kubelet                  Back-off restarting failed container
```
pgpool:
```
psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off
  Warning  Unhealthy  14m (x93 over 24m)  kubelet  Readiness probe failed: psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off
```

**To Reproduce**
deploy using helm and these parameters:

**helm install postgresql-ha bitnami/postgresql-ha \
  --set persistence.existingClaim=my-pvc-100gb \
  --set service.type=LoadBalancer \
  --set securityContext.runAsUser=0 \
  --set securityContext.fsGroup=0 \
  --namespace dev**

**Expected behavior**
Statefulsets all launch and PG is avaiable in the cluster

**Version of Helm and Kubernetes**:
Kubernetes 1.20 on Ubuntu 20.04 LTS (bare-metal)

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ngpestelos** [comment]
Ran into the same problem today. I think this is DNS-related:

<img width="1413" alt="Screen Shot 2021-06-05 at 8 35 43 PM" src="https://user-images.githubusercontent.com/5047/120891891-a0eb1e00-c63d-11eb-8ede-fa3283f0b760.png">

**Comment by erpel** [comment]
As far as I understand, there is an additional potential problem in your values:

> helm install postgresql-ha bitnami/postgresql-ha
> --set persistence.existingClaim=my-pvc-100gb
> --set service.type=LoadBalancer
> --set securityContext.runAsUser=0
> --set securityContext.fsGroup=0
> --namespace dev

Setting persistence.existingClaim causes the volume to be shared between both pods of the statefulset. This is likely to cause problems. I think that what's currently going wrong might be unrelated though.

You could try a chart version before 7.1.0 (like 7.0.0), which modified the backend hostnames to confirm the DNS suspicion.

**Comment by miguelaeh** [comment]
Hi guys, 
the persistence.existingClaim is for special cases only, be sure that's what you want as @erpel said. 
apart from that, I just deployed the chart with the same setting except for the persistence and it seems to work.  I see you are using a bare metal cluster, could you check if there is any connectivity issue in your cluster?

**Comment by idealtech-i3dlabs** [comment]
Thanks for your reply. 
I absolutely need to establish persistence, I can't have the data die if the deployment dies. Unless I'm missing something ? If I remove this parameter, I get this error now
```
Events:
  Type    Reason         Age                 From                         Message
  ----    ------         ----                ----                         -------
  Normal  FailedBinding  20s (x42 over 10m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

**Comment by idealtech-i3dlabs** [comment]
Indeed, I don't have the "standard" storage class. How can I create it, is there an example? Isn't the helm chart responsible to create one? Might it be useful to change the error message and mention that one needs the "standard" storage class?

**Comment by erpel** [comment]
The whole storage world is something you might need to freshen up on: https://kubernetes.io/docs/concepts/storage/storage-classes/

Basically, a cluster ideally has one or more storage provisioners configured (something that can create volume on demand, both the Kubernetes resource and a backing storage like a folder on an NFS server or a network volume on some IAAS platform)

Storageclasses are how a PVC can define which provisioner should fulfil the request for a volume, a default storage class is the one that is used, if none is chosen.

I believe the error you're seeing is not directly related to the storage issue though.

Alternatively to configuring a provisioner, you might also be able to just create 2 Volumes and let the statefulset create PVCs that match these volumes so they get bound automatically.

**Comment by miguelaeh** [comment]
Hi @idealtech-i3dlabs ,
> Isn't the helm chart responsible to create one? 

No, the helm chart is not responsible of creating the storage class, it is responsible of your cluster administrator.

> Might it be useful to change the error message and mention that one needs the "standard" storage class?

I don't think so, the `standard` storage class is something that is usually created by default in any K8s cluster, I think you just don't have it because you are deploying your own bare metal cluster. I recommend you to read https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by idealtech-i3dlabs** [comment]
Ah, could be why. OK, thank you, I'll look into it.
