### ISSUE TITLE
[bitnami/common] extend common.labels.matchLabels with .Values.commonMatchLabels

### ISSUE THREAD

**Issue by kuznero** [bitnami/charts#6588]
**Which chart**: redis, `v14.3.4`

**Is your feature request related to a problem? Please describe.**
When some charts (e.g. redis, etc.) are used multiple times as sub-charts (with different aliases) in an umbrella chart, matching labels confusing pods from these sub-charts.

**Describe the solution you'd like**
It is possible to introduce additional set of matching labels that can be supplied through values files, that can remove this confusion.

**Comment by miguelaeh** [comment]
We will continue the thread into the PR
