### ISSUE TITLE
[bitnami/postgresql-ha] Enabling metrics container on Nodeport Service

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#6595]
**Which chart**:
postgresql-ha helm chart

**Describe the bug**

I have deployed the postgresql-ha helm chart with metrics image enabled ,metrics image is enabled with ClusterIP service by default but my prometheus server is running outside Kubernetes cluster so I cannot access the PostgreSQL metrics from outside the cluster.

I did not see the option in the values.yaml to configure the service as NodePort for postgresql metrics container, Please can you let me know how I can implement metrics  container service as NodePort so that I can access the metrics from outside Cluster.

I am able to edit the service and change the ServiceType to NodePort but we have multiple environments ,it would be difficult to track the random generated Node Port for multiple environments.

Please see the output

[root@masternode1 ~]# kubectl get svc -n test3-iamdb
NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
postgresql-ha-pgpool                NodePort    10.43.46.170    <none>        5432:31258/TCP   4d7h
postgresql-ha-postgresql            ClusterIP   10.43.166.226   <none>        5432/TCP         4d7h
postgresql-ha-postgresql-headless   ClusterIP   None            <none>        5432/TCP         4d7h
**postgresql-ha-postgresql-metrics    ClusterIP   10.43.77.204    <none>        9187/TCP         4d7h**

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. Indeed, it seems that the metrics service only allows ClusterIP at the moment. I think we should create a `metrics.service` section where we can make it more customizable, and set elements like `metrics.service.type` or `metrics.service.loadBalancerIP`. This is similar to what we have in other charts. As you reported the issue, would you like to submit a PR implementing the change?

**Comment by parvaths1118** [comment]
Hi @javsalgar , Thank you very much for your response.

Kindly can you help me to raise the PR for this ?

Regards
SridharP

**Comment by javsalgar** [comment]
cc-ing @pablogalegoc  has he will lead the efforts of creating the PR. When he creates it, you could take a look to ensure that it applies to your use case.

**Comment by parvaths1118** [comment]
Thank you @javsalgar ,Please can you let me know if there is any ETA for this PR. Thank you so much for your help.

**Comment by javsalgar** [comment]
I'm afraid we can't provide an ETA, but as soon as we have more news, @pablogalegoc will update the ticket.
