### ISSUE TITLE
Maria Galera - big import - can't use ephemeral storage

### ISSUE THREAD

**Issue by voarsh2** [bitnami/charts#6596]
**Which chart**:
mariadb-galera:5.8.2

**Describe the bug**

I cannot change the values.yaml to make a ephemeral storage mount for mysql cli to import a large file

**To Reproduce**

curl 'http://192.168.100.5/matomo2.sql' | mysql -u root - matomo

Or file import to mysql

Kubernetes will kill the pod for overuse of ephemeral storage (requests 0)

**Comment by juan131** [comment]
Hi @voarsh2 

Could you please give us more context about how you're installing the MariaDB Galera chart and importing the database? 

- Are you using a custom init script to initialize the database as it's explained [here](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#initialize-a-fresh-instance) to import that backup? 
- Or.. are you using a "mysql client" pod" to do so?
