### ISSUE TITLE
[bitnami/wordpress] enable volume Permissions for mariadb when using wordpress with integrated mariadb

### ISSUE THREAD

**Issue by bottkars** [bitnami/charts#6600]
**Which chart**:
bitnami/wordpress

**Is your feature request related to a problem? Please describe.**
Bitnami Wordpress char has an otion to enable init containres to set permissions vor PVC Mounts
Hoiwever, when using integrated mariadb, this is mot passed to the mariad chart

**Describe the solution you'd like**
Expand the Chart to set 
**mariadb:
  volumePermissions:
    enabled: true
**
whenever init contaiers are enabled
**Describe alternatives you've considered**
Right now putting it manually in the values.yaml

So at least this needs to get documented or added to values.yaml

![image](https://user-images.githubusercontent.com/8255007/121167417-365efb80-c852-11eb-90e3-c59278d9b925.png)

**Comment by alemorcuq** [comment]
Hi, @bottkars. 

You can actually pass any parameter available for the MariaDB chart to the WordPress chart under the `mariadb` section. So setting this, as you suggested, will work:

```
mariadb:
  volumePermissions:
    enabled: true
```

See:

```
❯ helm install wp bitnami/wordpress --set mariadb.volumePermissions.enabled=true
NAME: wp
LAST DEPLOYED: Wed Jun  9 08:54:34 2021
NAMESPACE: amoreno
STATUS: deployed
REVISION: 1
...

❯ k describe po wp-mariadb-0
...
Init Containers:
  volume-permissions:
    Container ID:  docker://601bd256f8ed188db31d2658a9db402cd8eb2f216fe94f7cee76aa21e83800e6
    Image:         docker.io/bitnami/bitnami-shell:10-debian-10-r91
    Image ID:      docker-pullable://bitnami/bitnami-shell@sha256:7b9f4afc11568d2a51dde353a001dbf186ed564abc79f3e0fa93b264571bc82f
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -ec
      chown -R 1001:1001 /bitnami/mariadb

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 09 Jun 2021 08:55:07 +0200
      Finished:     Wed, 09 Jun 2021 08:55:07 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /bitnami/mariadb from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from wp-mariadb-token-8s2hw (ro)
...
```

**Comment by bottkars** [comment]
Thanks Alejandro
thats what i used to deploy.
my above statement was to add exactly that do the chart / or at least documentation ...

**Comment by alemorcuq** [comment]
I'm not sure about adding specifically that to the README as I think it's more related to Helm (you can set custom values for the dependent charts) than to Bitnami in particular.
