### ISSUE TITLE
Set an additional CA in keycloak's trust bundle

### ISSUE THREAD

**Issue by Nox-404** [bitnami/charts#6602]
**Which chart**:

keycloak

**Is your feature request related to a problem? Please describe.**

Hello there,

I need to use keycloak for user federation and idp provider.
The idp and federation services uses self signed certificates.

I need keycloak to validates thoses certs and thus need to add the self-signed CA to keycloak's trust store.

Can you give me pointers on how to implement this ?

PS: It's more of a doc request than a feature request

**Comment by alvneiayu** [comment]
hi @Nox-404 

Inside the Readme of the chart, you can see a section:

```
  tls:                                                                                                                  
     enabled: false                                                                                                      
     ## Name of the existing secret containing the truststore and one keystore per Keycloak replica                      
     ## Create this secret following the steps below:                                                                    
     ## 1) Generate your trustore and keystore files (more info at https://www.keycloak.org/docs/latest/server_installation/#_setting_up_ssl)
     ## 2) Rename your truststore to `keycloak.truststore.jks`.                                                          
     ## 3) Rename your keystores to `keycloak-X.keystore.jks` where X is the ID of each Keycloak replica                 
     ## 4) Run the command below where SECRET_NAME is the name of the secret you want to create:                         
     ##       kubectl create secret generic SECRET_NAME --from-file=./keycloak.truststore.jks --from-file=./keycloak-0.keystore.jks --from-file=./keycloak-1.keystore.jks ...
     ##                                                                                                                  
     # jksSecret:                                                                                                        
     ## Password to access the keystore when it's password-protected.                                                    
     ##                                                                                                                  
     keystorePassword: ""                                                                                                
     ## Password to access the truststore when it's password-protected.                                                  
     ##                                                                                                                  
    truststorePassword: ""   
```

You need to create a secret adding the trustore and keystore files. You need to include the secret name using the jksSecret key. Moreover, keystorePassword and truststorePassword to set up the password used.

Let me know if I can help you with something else.

Álvaro

**Comment by Nox-404** [comment]
Hi, thanks for your reply.
I saw that section but isn't it to setup TLS on the keycloak server ?

**Comment by alvneiayu** [comment]
hi @Nox-404 

I found you document that maybe can help you to configure the keycloak as you want.

https://keycloak.discourse.group/t/keycloak-connecting-to-msad-ldap-over-ssl/1921
https://www.keycloak.org/docs/latest/server_admin/#connect-to-ldap-over-ssl

I think that you have two different way:
* Mount an extraVolume and extraVolumeMount. Create a init-script adding SPI to Wildfly and configure the SPI using the interface.
* Include the ca.crt inside the Truststore of Auth and use it in keycloak-server using SPI.

I suggest you the first one. I am not expert in Keycloak but I think that with the links shared, you won't have any problem.

Thanks a lot

Álvaro

**Comment by merlin-tc** [comment]
We are facing the same problem right now.

We want to keep as close as possible to upstream so don't want to change too much.
So we did import the certificates the way described above and then tried import our certificates in the main cacerts store.

It failed because we were not logged in as root and because we are not quite sure how we would run that command when we deploy via kubernetes.
Any help or nudge in the right direction would be greatly appreciated.

`/opt/bitnami/java/bin/keytool/keytool -importkeystore -srckeystore /opt/bitnami/keycloak/certs/keycloak.truststore.jks -srcstorepass secretpassword -destkeystore /opt/bitnami/java/lib/security/cacerts -deststorepass changeit`

**Comment by alvneiayu** [comment]
hi @merlin-tc 

First of all, sorry for the late reply.

I need to evaluate it (I am not an expert in Keycloak chart) but I think that maybe is a good a idea to include an initContainer executing the command line and to generate the jks files directly to /opt/bitnami/keycloak/certs/. You can include it (the initContainer) using the values.yaml and you will be close to upstream. Like this you can skip the permissions and privileges problems. We are doing something like this in our autoGenerated support that you can see [here](https://github.com/bitnami/charts/blob/7827fdf806476b721c7fc1fda35b90cdcd87ec93/bitnami/keycloak/templates/statefulset.yaml#L75).

I didn't test it but let me know if you have problems and I will help you

Thanks a lot

Álvaro
