### ISSUE TITLE
[Thanos]support for installing thanos grafana dashboards via helm

### ISSUE THREAD

**Issue by gowrisankar22** [bitnami/charts#6604]
**Which chart**:
Thanos

**Is your feature request related to a problem? Please describe.**
We are deploying thanos using bitnami helm chart and it works like a charm. It would be really nice if you can include the installation of grafana dashboards with feature flags to make the monitoring easier.

**Describe the solution you'd like**
Implement adding Thanos grafana dashboards via helm install via feature flag.
https://github.com/thanos-io/thanos/tree/main/examples/dashboards

**Comment by javsalgar** [comment]
Hi,

In several of our charts we include the `extraDeploy` value that allows you to deploy as many extra objects as you like. With that, it could be possible for you to deploy configmaps or scripts with Grafana dashboards. With that, and using `extraVolumes` and `extraVolumeMounts`, with a simple helm install, you could also have the dashboards for your use case. Would that work for you?
