### ISSUE TITLE
Bitnami chart repository doesn't work

### ISSUE THREAD

**Issue by agadelshin** [bitnami/charts#6610]
**Describe the bug**
https://charts.bitnami.com/bitnami return access denied error
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>VYF9Q9ZF7C28DS67</RequestId>
<HostId>iYIGDWWvRDYjkBvwQwSz6oyHxAwk1bmTUKCyjdCktjUDmVQLMdEHz0sq7XdOG+xwMwtBkOWixJY=</HostId>
</Error>
```

**Expected behavior**
It should return 200 and charts

**Comment by carrodher** [comment]
The Helm Charts repository is not accessible via web browser, you should add it using the Helm client:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm search repo bitnami
$ helm install my-release bitnami/<chart>
```

Using the web browser you can access https://charts.bitnami.com/bitnami/index.yaml and download the index.yaml, but that's all
