### ISSUE TITLE
[bitnami/discourse] backup permission denied after upgrading to most recent chart

### ISSUE THREAD

**Issue by searsaw** [bitnami/charts#6619]
**Which chart**:

`bitnami/discourse v4.0.1`

**Describe the bug**

After upgrading from v2.2.1 of the chart, backups no longer work. The error is:

```
[2021-06-09 16:47:01] EXCEPTION: lib/discourse.rb:93:in `exec': tar: /opt/bitnami/discourse/public/backups/default/our-backup.tar: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
```

Backups were working before. This is known because we took a backup through the UI and downloaded it fine before we did the upgrade.

**To Reproduce**

1. Upgrade from an old version to the newest version.
1. Go to `/admin/backups`
1. Click on "Backup".
1. Click on "Yes".
1. Allow backup process to finish.
1. See error near the bottom.

**Expected behavior**

A backup would be made, and I would receive an email about it.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:19:22Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

We are running three replicas of the Discourse pod. Therefore, we needed to setup and use the NFS provisioner as suggested [in the documentation for the chart](https://github.com/bitnami/charts/tree/e9b786f98dfd8b51e2d89e36a7603e54d7442aa4/bitnami/discourse#setting-up-replication). The PVC backing the NFS controller and, therefore, the Discourse pods was not deleted when we did the upgrade for fear of data loss.

Also I considered updating the volume permissions using the `initContainer` in the chart [as suggested here](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#solve-issue-2), but as far as I can tell, this particular chart doesn't support this functionality.

**Comment by javsalgar** [comment]
cc @marcosbc as he recently worked on the Discourse major version

**Comment by mattcg** [comment]
Getting the exact same error after upgrading from v2 to v4. Backups previously worked fine.

**Comment by marcosbc** [comment]
Hi @mattcg, I've been able to reproduce this issue. It is happening because the `discourse` user UID is now 999 instead of 1001, so persisted data does not match. This change was done in order to support non-root in the future (although it is not currently supported).

For now, we are going to add support for the `initContainer` for fixing permissions during deployment. We will also document this in the "Upgrade" section. We'll link the PR to this issue.

**Comment by mattcg** [comment]
hi @marcosbc, I upgraded to chart v4.1.2 but this is still a problem. The error when attempting a backup is:

```
EXCEPTION: lib/discourse.rb:93:in `exec': Failed to move database dump file.
mv: cannot create regular file
```

Is there a manual fix that has to be applied?

**Comment by marcosbc** [comment]
@mattcg Did you upgrade to 4.1.2 with `volumePermissions.enabled=true`? If so, could you check that files in `/bitnami/discourse` belong to `1001`?

**Comment by mattcg** [comment]
Sorted. Thank you. I hadn't switched `volumePermissions.enabled` to `true`.
