### ISSUE TITLE
[bitnami/mongodb] replicaset does not properly set `bindIp` in the config file.

### ISSUE THREAD

**Issue by mxplusb** [bitnami/charts#6620]
**Which chart**:

```yaml
dependencies: 
  - name: mongodb
    version: "10.12.0"
    repository: "https://charts.bitnami.com/bitnami"
```

**Describe the bug**

According to the [MongoDB docker image](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb/setup.sh#L41), the `start.sh` script in the scripts configmap is supposed to set `net.bindIpAll: true` and `net.bindIp: 0.0.0.0` [here](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L432) when `MONGODB_REPLICA_SET_MODE` is a non-zero string.

You can see the variable is set here:

```sh
$ kctl describe cm hurricane-mongo-scripts
Name:         hurricane-mongo-scripts
Namespace:    pine
Labels:       app.kubernetes.io/component=mongodb
              app.kubernetes.io/instance=hurricane-server
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mongodb
              helm.sh/chart=mongodb-10.12.0
Annotations:  meta.helm.sh/release-name: hurricane-server
              meta.helm.sh/release-namespace: pine

Data
====
setup-hidden.sh:
----
#!/bin/bash
echo "Advertised Hostname: $MONGODB_ADVERTISED_HOSTNAME"
echo "Configuring node as a hidden node"
export MONGODB_REPLICA_SET_MODE="hidden"
export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD="$MONGODB_ROOT_PASSWORD"
export MONGODB_INITIAL_PRIMARY_PORT_NUMBER="$MONGODB_PORT_NUMBER"
export MONGODB_ROOT_PASSWORD="" MONGODB_USERNAME="" MONGODB_DATABASE="" MONGODB_PASSWORD=""
exec /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh
setup.sh:
----
#!/bin/bash

echo "Advertised Hostname: $MONGODB_ADVERTISED_HOSTNAME"

if [[ "$MY_POD_NAME" = "hurricane-mongo-0" ]]; then
    echo "Pod name matches initial primary pod name, configuring node as a primary"
    export MONGODB_REPLICA_SET_MODE="primary"
else
    echo "Pod name doesn't match initial primary pod name, configuring node as a secondary"
    export MONGODB_REPLICA_SET_MODE="secondary"
    export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD="$MONGODB_ROOT_PASSWORD"
    export MONGODB_INITIAL_PRIMARY_PORT_NUMBER="$MONGODB_PORT_NUMBER"
    export MONGODB_ROOT_PASSWORD="" MONGODB_USERNAME="" MONGODB_DATABASE="" MONGODB_PASSWORD=""
```

But this is the rendered config:

```sh
$ kctl exec -ti hurricane-mongo-1 -- cat /opt/bitnami/mongodb/conf/mongodb.conf
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false

# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: false
  bindIp: 127.0.0.1

# replica set options
#replication:
  #replSetName: replicaset
  #enableMajorityReadConcern: true

# sharding options
#sharding:
  #clusterRole:

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: true

# security options
security:
  authorization: disabled
  #keyFile: replace_me
```

**To Reproduce**

**GIVEN**

This `values.yaml`:

```yaml
  image:
    tag: 4.4-debian10
    debug: true
  arbiter:
    enabled: false
  architecture: replicaset
  replicaCount: 3
  auth:
    username: test
    password: test
    rootPassword: test
    replicaSetKey: test
    database: test
```

**WHEN**

You run `helm install bitnami/mongodb -f values.yml`

**THEN**

You can see Mongo is not exposed on all IPs in the configuration when you run `kctl exec -ti <mongo-pod> -- cat /opt/bitnami/mongodb/conf/mongodb.conf`

**Expected behavior**

IPs to be bound properly.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @mxplusb 

Thanks so much for opening this issue!!

When using the "replicaset" architecture, the default's container **entrypoint.sh** is overwritten, see:

- https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml#L204

And a custom "setup.sh" script is called that's mounted from a ConfigMap as you pointed (the one defined at [scripts-configmap.yaml](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L57)). This custom "setup.sh" sets some env. vars and then calls the container's original **entrypoint.sh** with the original args.

The original **entrypoint.sh** invokes [this script](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb/setup.sh) which calls the `mongodb_initialize` function defined [here](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1078).

Then, this function calls the `mongodb_set_listen_all_conf` that you pointed out which sets `net.bindIpAll: true` and `net.bindIp: 0.0.0.0` **unless a custom config file has been mounted, which is NOT the case of the chart with the default values** (it would be the case if you set the `configuration` or `existingConfigmap` parameters).

I installed the chart using the values below:

```yaml
arbiter:
  enabled: false
architecture: replicaset
replicaCount: 3
auth:
  username: testuser
  password: testpassword
  rootPassword: testrootpassword
  replicaSetKey: testreplicasetkey
  database: testdatabase
```

and everything seems fine:

```console
$ k exec -ti mongodb-0 -- cat /opt/bitnami/mongodb/conf/mongodb.conf
(...)
# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
  #bindIp:
```

**It's also important to recall that `mongodb_initialize` will skip calling `mongodb_set_listen_all_conf` if the data directory is not empty** (see [this line](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1089)). So, it's possible that, if you had exiting PVCs from previous releases, it's skipping this step (see [this guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#persistence-volumes-pvs-retained-from-previous-releases) for more info). 

---

A question:

- What is the `start.sh` script you are referring to? Or did you mean the `setup.sh`?
