### ISSUE TITLE
[bitnami/discourse] Unable to specify database user for external PostgreSQL

### ISSUE THREAD

**Issue by kxesd** [bitnami/charts#6621]
**Which chart**:
bitnami/discourse 4.0.1

**Describe the bug**
When deploying bitnami/discourse using an externalDatabase (PostgreSQL) with a database user specified, the install does not use the specified user it instead defaults to `bn_discourse`.

**To Reproduce**

1. Specify a user different from the default in `externalDatabase.user`.
2. Install the helm chart.
3. Check the logs in PostgreSQL server to confirm the install is using the default user rather than the specified user.

**Expected behavior**
The install uses the specified user for the PostgreSQL connection.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-10T12:53:33Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The configMap that is generated by the helm chart creates an env var `DISCOURSE_DATABASE_USERNAME`
-> https://github.com/bitnami/charts/blob/master/bitnami/discourse/templates/configmaps.yaml#L24
However the script in the docker image that sets up the env is looking for `DISCOURSE_DATABASE_USER` or `DISCOURSE_POSTGRESQL_USERNAME`
-> https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/discourse-env.sh#L148-L149

Renaming `DISCOURSE_DATABASE_USERNAME` to `DISCOURSE_DATABASE_USER` in the configMap resolved the issue.

**Comment by marcosbc** [comment]
Good catch, and thanks for the PR!
