### ISSUE TITLE
ETCD use hostPath instead of emptyDir

### ISSUE THREAD

**Issue by tiagolobocastro** [bitnami/charts#6624]
**Which chart**: etcd

**Is your feature request related to a problem? Please describe.**
We use emptyDir for testing which seems to sometime loose data when we rebooting nodes and such. Would it be possible to use hostPath instead of emptyDir? (if the pod antiaffinity is set to hard, I guess)

**Describe the solution you'd like**
A variable/(s) to enable hostPath and specify the path to use, instead of using emptyDir

**Describe alternatives you've considered**
We could use the "manual" storage class and manually provision PV before installing etcd, though this way with the hostPath directly would perhaps be easier to use.

I'm happy to take a stab at this myself is this request is deemed acceptable.

**Comment by miguelaeh** [comment]
Hi @tiagolobocastro ,
`emptydir` volumes are used only in the case you are passing `persistence.enabled=false`. If not, a `volumeClaimTemplate` is used. A volume created from the Volume claim template will not disappear when rebooting nodes, while an `emptydir` only exists during the pod life.

Using `hostPath` volumes is generally not a good idea since it will not work if the pod is moved between nodes.

**Comment by tiagolobocastro** [comment]
Hi @miguelaeh, yes you're right ofc, it's not a great idea to use. For me it would be just a testing setup when I have no real pvc's to make use of. `emptyDir` is also not that good because its data is tied to the pod life as you said. 

So both `hostPath` and `emptyDir` are bad, I guess it depends on the use case.
Would it be possible to "pin" the pods to a node so that if the pod is restarted it gets recreated on the same node? If not then yeah, then there's really no point in adding hostPath...

**Comment by miguelaeh** [comment]
Hi @tiagolobocastro ,
Yes, you can "pin a pod to a node" by using affinity rules.
In any case, you can modify the chart locally by cloning the repo for your testing purpose, but adding hostpath volumes by default to the chart is something we will probably not accept on a PR.

**Comment by tiagolobocastro** [comment]
Yes I understand, I did not want to make it default, just making it possible as an option which is not possible atm other than cloning the repo and changing it like you said. Would it be acceptable to add another option for persistence turned off that would basically let the user choose what to place in "volumes: " ?

**Comment by miguelaeh** [comment]
Hi @tiagolobocastro ,
 you can try using the `extraVolumes` and `extraVolumeMounts`. https://github.com/bitnami/charts/blob/da9f873283e6ab4f1e6e7b3ff37594af5a23330d/bitnami/etcd/values.yaml#L301

**Comment by tiagolobocastro** [comment]
Ah right thanks, although the volume "data" will already be used (either by the volume template) or the emptyDir?

**Comment by miguelaeh** [comment]
I think you could use the `persistence.enabled=false` and then add the extra volumes on the mountpoint the data volumes were being mounted.
