### ISSUE TITLE
Multiple vulnerabilities found for the mongodb chart

### ISSUE THREAD

**Issue by amirh** [bitnami/charts#6625]
**Which chart**:
mongodb 10.19.0

**Describe the bug**
The artifact hub page shows that the vulnerability scan detected multiple vulnerabilities including critical ones:

![image](https://user-images.githubusercontent.com/1024117/121438645-400f5e80-c939-11eb-9777-49f4d0f8a749.png)

Full report: https://artifacthub.io/packages/helm/bitnami/mongodb?modal=security-report

**Comment by alemorcuq** [comment]
Hi, @amirh.

As you can see in the report, those vulnerabilities are present in system packages from the Debian repositories and don't have a fix yet. As soon as Debian releases a new version fixing the vulnerability, our internal pipeline will trigger and release a new container with the fixed packages.
