### ISSUE TITLE
[bitnami/mariadb] PVC not removed when uninstalling chart

### ISSUE THREAD

**Issue by mahgo** [bitnami/charts#6626]
**Which chart**:
bitnami/mariadb, latest.

**Describe the bug**
When you uninstall this chart, the PVC remains, and unless you manually delete it, installing the chart again will cause it to not start successfully. Note: I am using this chart via the bitnami/magento chart.

**To Reproduce**

1. Install chart
2. Uninstall chart
3. Install chart
4. Notice it isn't starting succcessfully

**Expected behavior**
Pod to start successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @mahgo,

It's normal behavior. Could you check this issue in helm https://github.com/helm/helm/issues/5156. Maybe is a good idea to create a script to delete de chart.

**Comment by mahgo** [comment]
Hi @Mauraza,

When you say it is normal behaviour, do you mean its normal behaviour for all helm charts or specifically database helm charts? I know for example, the bitnami/magento chart has a PVC which is removed when you uninstall that chart.

**Comment by Mauraza** [comment]
Hi @mahgo,

The chart bitnami/magento is a deployment and in this case, is easy to delete all the objects related but in the case of statefulset as MariaDB is different, is more difficult. 
In this issue, https://github.com/helm/helm/issues/8634 explained in more detail

**Comment by mahgo** [comment]
Hi @Mauraza,

Thanks for sending this through.

Maybe showing an error message for when this occurs could be an improvement? Currently, you only see the following and have to set the chart to debug to see what is going on:
```
mariadb 01:12:42.62
mariadb 01:12:42.62 Welcome to the Bitnami mariadb container
mariadb 01:12:42.63 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 01:12:42.63 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 01:12:42.63
mariadb 01:12:42.63 INFO  ==> ** Starting MariaDB setup **
mariadb 01:12:42.66 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 01:12:42.66 INFO  ==> Initializing mariadb database
mariadb 01:12:42.68 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 01:12:42.68 INFO  ==> Using persisted data
mariadb 01:12:42.71 INFO  ==> Running mysql_upgrade
mariadb 01:12:42.72 INFO  ==> Starting mariadb in background
mariadb 01:12:44.79 INFO  ==> Stopping mariadb
```

**Comment by Mauraza** [comment]
Hi @mahgo,

Could you try adding the value `image.debug=true`  to the installation of the chart? https://github.com/bitnami/charts/blob/c6aeae0a3e09e603940a1422ecf0f8a18a03186c/bitnami/mysql/values.yaml#L33

**Comment by mahgo** [comment]
Hi Mauraza,

Yeah I worked out this issue once I set image.debug to be true, but should an issue like this have to have image.debug true to get any idea what is causing the pod restart loop?

**Comment by mahgo** [comment]
Hi @Mauraza,

Thanks for clarifying this.
