### ISSUE TITLE
Ingress isn't working, can access to airflow UI with port-forward only.

### ISSUE THREAD

**Issue by sagisd** [bitnami/charts#6627]
**Which chart**:
bitnami/airflow airflow-9.0.5

**Describe the bug**
Unable to access the airflow without running kubectl port-forward it seems that ingress isn't working?

**To Reproduce**

1. Go to http://airflow.example.com
2. Got error 404
3. Run kubectl port-forward 
4. Go to http://airflow.example.com
5. Able to see the airflow ui

**Expected behavior**
My understanding is that ingress should handle requests outside the cluster with the pods.
I don't want to run the kubectl port-forward command forever on the machine

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
```console
kubectl get ingress
NAME      CLASS    HOSTS                 ADDRESS   PORTS   AGE
airflow   <none>   airflow.example.com             80      12m
```

```console
kubectl describe ingress/airflow
Name:             airflow
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                 Path  Backends
  ----                 ----  --------
  airflow.example.com
                       /   airflow:http (10.200.36.141:8080)
Annotations:           kubernetes.io/ingress.class: nginx
                       meta.helm.sh/release-name: airflow
                       meta.helm.sh/release-namespace: default
Events:                <none>
```

**Comment by migruiz4** [comment]
Hi @sagisd,

In order to enable Ingress you need first an Ingress-controller to handle it: https://kubernetes.io/docs/concepts/services-networking/ingress/#prerequisites

You could easily deploy an Ingress-controller installing our nginx-ingress-controller chart:
```
helm install nginx-ingress-controller bitnami/nginx-ingress-controller
```

After setting up an ingress-controller, your Ingress should look like this:
```console
$ kubectl describe ingress/airflow                   
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             airflow
Namespace:        default
Address:          x.x.x.x
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host           Path  Backends
  ----           ----  --------
  airflow.local  
                 /   airflow:http (10.1.7.145:8080)
Annotations:     meta.helm.sh/release-name: airflow
                 meta.helm.sh/release-namespace: default
Events:
  Type    Reason  Age                From                      Message
  ----    ------  ----               ----                      -------
  Normal  Sync    14m (x2 over 15m)  nginx-ingress-controller  Scheduled for sync

$ kubectl get ingress/airflow
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME      CLASS    HOSTS           ADDRESS        PORTS   AGE
airflow   <none>   airflow.local          x.x.x.x             80      20m
```

**Comment by sagisd** [comment]
Thanks @migruiz4 

I did what you said, after installing the bitnami/nginx-ingress-controller I can see the address in my ingress but still can't access to airflow UI

```console
kubectl describe ingress/airflow
Name:             airflow
Namespace:        default
Address:          x.x.x.x
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                 Path  Backends
  ----                 ----  --------
  airflow.storedot.us
                       /   airflow:http (10.200.36.141:8080)
Annotations:           kubernetes.io/ingress.class: nginx
                       meta.helm.sh/release-name: airflow
                       meta.helm.sh/release-namespace: default
Events:
  Type    Reason  Age                From                      Message
  ----    ------  ----               ----                      -------
  Normal  Sync    39m (x2 over 40m)  nginx-ingress-controller  Scheduled for sync
```
```console
kubectl get ingress/airflow
NAME      CLASS    HOSTS                 ADDRESS         PORTS   AGE
airflow   <none>   airflow.example.com   x.x.x.x   80      43m
```
```console
curl http://airflow.example.com
curl: (7) Failed to connect to airflow.example.com port 80: Connection refused
```

**Comment by migruiz4** [comment]
Hi again,

The Ingress does not configure the DNS automatically either. It assigned one of the IPs in your Kubernetes nodes for the Airflow Ingress, and will redirect traffic with a Header matching your Ingress Host (airflow.example.com) to Airflow-web service.

To test it works properly, you could modify your `/etc/hosts`, adding the following entry:
```
x.x.x.x airflow.example.com
```
More information here: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource

If you'd like to expose your Ingress publicly or in your private network, you will need a DNS record for airflow.example.com using the Ingress address (x.x.x.x).

**Comment by sagisd** [comment]
@migruiz4 
Hi, I changed the DNS to the ingress IP but still can't reach the airflow

Here are some outputs:
```console
sagi@KM1:/$ kubectl get ingress/airflow
NAME      CLASS    HOSTS                 ADDRESS         PORTS   AGE
airflow   <none>   airflow.example.com   192.168.16.93   80      26h
```
```console
sagi@KM1:/$ ping airflow.example.com
PING airflow.example.com (192.168.16.93) 56(84) bytes of data.
64 bytes from kw2.example.com (192.168.16.93): icmp_seq=1 ttl=64 time=0.243 ms
^C
--- airflow.example.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.243/0.243/0.243/0.000 ms
```
```console
sagi@KM1:/$ curl http://airflow.example.com
curl: (7) Failed to connect to airflow.example.com port 80: Connection refused
```

Thanks!

**Comment by migruiz4** [comment]
Hi @sagisd,

I will need some more details about your environment in order to help you.

Are you running Kubernetes in the cloud or in a local environment?

To help you troubleshoot this issue, I'd recommend troubleshooting following these steps:
1. Open a bash terminal in your Kubernetes host, and try to connect with your ingress-controller using `localhost`.
```
$ curl http://localhost
```
2. Try reaching the Ingress IP
```
$ curl http://192.168.16.93
```
3. Then finally try using the DNS:
```
$ curl http://airflow.example.com
```

**Comment by sagisd** [comment]
Hi @migruiz4 

I'm running on self VMware server, 3 servers in the cluster - one for master and two workers
I saw the ingress address is the IP of one of the workers. (is it fine? what if the worker will be unreachable?)
I tried to use the curl command for localhost from all the servers (master and two workers) and got the same error
```console
sagi@kw2:~$ hostname -I | awk '{print $1}'
192.168.16.93
```
```console
sagi@kw2:~$ curl http://localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
```

**Comment by migruiz4** [comment]
That is weird, I was expecting the Ingress-controller to at least reply to the curl command. Similar to this:
```console
$ curl http://localhost:80
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Could you please share the output of `kubectl get service`,`kubectl get pods` and `kubectl describe ingress/airflow`?

Especially, I'm looking to see services corresponding to the Ingress-controller, the Ingress-Controller pods in charge of replying to the requests, or any Ingress event we should care about.

**Comment by cdibble** [comment]
We had a similar issue as a result of our ingress path setting. Our AWS EKS application load balancer was handling the ingress and we could hit that endpoint and get the initial redirect to `home` and we could see that request in the webserver logs, but then we 404'd from there, unable to get the redirects to the login page, etc.

Switching from `ingress.web.path='/'` to `ingress.web.path='/*'` solved the problem.
