### ISSUE TITLE
[bitnami/nginx] Add securityContext to metrics

### ISSUE THREAD

**Issue by MrKrabat** [bitnami/charts#6628]
**Which chart**:
Latest bitnami/nginx chart

**Is your feature request related to a problem? Please describe.**
The metrics configuration for the nginx-exporter does not contain a securityContext section.

**Describe the solution you'd like**
The same way as bitnami/postgresql, see https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L802

**Comment by alvneiayu** [comment]
hi @MrKrabat 

We are opened to receive PRs, I will be glad to review it.

Thanks a lot

Álvaro
