### ISSUE TITLE
[bitnami/mariadb] How to connect from another machine to a replication cluster?

### ISSUE THREAD

**Issue by stefnats** [bitnami/charts#6629]
Hey there,

i'm not that experienced, just learning.

How would i solve this to be able to (temporarily?) expose an endpoint in the kubernetes cluster which allows me to read/write on the kubernetes mariadb cluster, using `architecture: replication`?

Thanks in advance!

**Comment by pablogalegoc** [comment]
Hi @stefnats! What you are looking for is a way to temporarily expose a MariaDB service inside the Kubernetes cluster to outside the cluster or a way to temporarily expose the MariaDB service to other services from within the cluster?
