### ISSUE TITLE
[bitnami/minio] Add full securityContext support

### ISSUE THREAD

**Issue by MrKrabat** [bitnami/charts#6630]
**Which chart**:
Latest bitnami/minio chart

**Is your feature request related to a problem? Please describe.**
Currently this chart does not allow to set additional securityContext values.
See the relevant parts:
https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/standalone/deployment.yaml#L59
https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/standalone/deployment.yaml#L91

**Describe the solution you'd like**
I want the ability to set more securityContext values.
As example bitnami/nginx:
https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L58
https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L129

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the suggestion. We will work on it. If you want to speed up the process, would you like to submit a PR? We are open to contributions :D
