### ISSUE TITLE
pod_template mounting as directory in scheduler pod

### ISSUE THREAD

**Issue by Jagadeepkosuri** [bitnami/charts#6634]
**Which chart**:
Airflow 10.0.8

**Describe the bug**
When using Kubernetes Executor, I found that _**pod_template.yaml**_ file is mounting as directory instead of file.

![image](https://user-images.githubusercontent.com/25528123/121534166-999d8900-ca1e-11eb-9b2a-04b25fe09711.png)

If I try to run a DAG, scheduler throws the below logs 

![image](https://user-images.githubusercontent.com/25528123/121534625-044ec480-ca1f-11eb-9d8f-77152b9257b7.png)

DAG tasks will remain in queued state forever, they will not get scheduled.

And in the webserver UI, it shows like below

_The scheduler does not appear to be running. Last heartbeat was received a few seconds ago.
The DAGs list may not update, and new tasks will not be scheduled._

**To Reproduce**
Use the default values.yaml file and test any of your DAG and see if new pods are created or not.

**Expected behavior**
DAG tasks should be scheduled and new task pods should be created.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Jagadeepkosuri** [comment]
The following steps worked for me. Not sure, if  followed the correct process or not. 

In templates/scheduler/deployment.yaml file, I have renamed the volumemount as custom1-configuration-file instead of custom-configuration file. Since there is another volumeMount with same name.

```
{{- if $kube }}
            - name: custom1-configuration-file
              mountPath: /opt/bitnami/airflow/pod_template.yaml
              subPath: pod_template.yaml
```
In volumes, I have added the below

```
 {{- if $kube }}
        - name: custom1-configuration-file
          configMap:
          name: airflow-release-configuration
      {{- end }}
```

Then, pod_template.yaml file is mounted as file inside the scheduler pod

![image](https://user-images.githubusercontent.com/25528123/121538620-8e4c5c80-ca22-11eb-9246-fc8854e4da34.png)

I'm aware that I shouldn't hardcode the configmap name of pod_template.yaml. But I'm new to Helm. Someone help me, how I couldn't generalize it.

**Comment by carrodher** [comment]
I'm sorry but I am not able to reproduce the issue using the latest version, those are the steps I followed:
```console
$ helm install airflow bitnami/airflow --set executor="KubernetesExecutor"
NAME: airflow
LAST DEPLOYED: Fri Jun 11 09:28:50 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the Airflow URL by running:

  echo URL  : http://127.0.0.1:8080
  kubectl port-forward --namespace default svc/airflow 8080:8080

2. Get your Airflow login credentials by running:
  export AIRFLOW_PASSWORD=$(kubectl get secret --namespace "default" airflow -o jsonpath="{.data.airflow-password}" | base64 --decode)
  echo User:     user

$ helm ls
NAME                             	NAMESPACE	REVISION	UPDATED                                  	STATUS  	CHART                       	APP VERSION
airflow                          	default  	1       	2021-06-11 09:28:50.557718732 +0000 UTC  	deployed	airflow-10.0.8              	2.1.0

$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
airflow-postgresql-0                  1/1     Running            0          84s
airflow-redis-master-0                1/1     Running            0          84s
airflow-scheduler-6bb64d7b78-898l4    1/1     Running            1          84s
airflow-web-75b86999fc-w5vbj          1/1     Running            1          84s

$ kubectl exec -it airflow-scheduler-6bb64d7b78-898l4 -- /bin/bash
I have no name!@airflow-scheduler-6bb64d7b78-898l4:/$ ls -la /opt/bitnami/airflow
total 104
drwxrwxr-x 1 root root  4096 Jun 11 09:29 .
drwxrwxr-x 1 root root  4096 May 23 15:56 ..
-rw-r--r-- 1 1001 root 41845 Jun 11 09:29 airflow.cfg
drwxrwxr-x 2 root root  4096 May 23 15:57 dags
lrwxrwxrwx 1 1001 root    21 Jun 11 09:29 data -> /bitnami/airflow/data
drwxrwxr-x 1 root root  4096 Apr 26 17:34 licenses
drwxrwxr-x 1 root root  4096 Jun 11 09:30 logs
-rw-r--r-- 1 1001 root    13 Jun 11 09:29 nss_group
-rw-r--r-- 1 1001 root    57 Jun 11 09:29 nss_passwd
-rw-r--r-- 1 root 1001  4763 Jun 11 09:28 pod_template.yaml
drwxrwxr-x 2 root root  4096 May 23 15:57 tmp
drwxrwxr-x 1 root root  4096 Apr 26 17:34 venv
-rw-rw-r-- 1 1001 root  4700 Jun 11 09:29 webserver_config.py
```

Are you able to reproduce those steps? Can you install it using a different name just in case there is an existing volume? Take into account `helm delete` doesn't remove the existing PV/PVCs, you need to manually remove them or use a different name or namespace when installing the chart the second time
