### ISSUE TITLE
kafka.errors.NodeNotReadyError: NodeNotReadyError, when using service type = NodePort

### ISSUE THREAD

**Issue by zbeedatm** [bitnami/charts#6640]
**Which chart**:
image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 2.8.0-debian-10-r30

**Describe the bug**
I tried to install kafka from the [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml) and did some changes on it basically to run it as NodePort ([here](https://pastebin.com/FzTx0meJ))

The minikube was started as `minikube start --driver=none --apiserver-ips <9.x.x.x>`, and I'm configuring the kafka instanace to connect to the kafka server `<9.x.x.x>:<port>` where the port is taken from `minikube service list`. (from range 30000-)  

example:

    |-----------|--------------------------|----------------|---------------------------|
    | NAMESPACE |           NAME           |  TARGET PORT   |            URL            |
    |-----------|--------------------------|----------------|---------------------------|
    | test      | kafka                    | No node port   |
    | test      | kafka-0-external         | tcp-kafka/9094 | http://10.x.x.x:30189 |
    | test      | kafka-headless           | No node port   |
    | test      | kafka-zookeeper          | No node port   |
    | test      | kafka-zookeeper-headless | No node port   |
    | test      | minio                    | minio/9000     | http://10.x.x.x:32439 |
    |-----------|--------------------------|----------------|---------------------------|

But when trying to run the code I'm failing on this line:

    self.admin_client = KafkaAdminClient(
                bootstrap_servers=server,
                client_id=self.client_id
            )

with this error:

> File "C:\Program Files\Python36\lib\site-packages\kafka\admin\client.py", line 218, in __init__
    self._refresh_controller_id()
  File "C:\Program Files\Python36\lib\site-packages\kafka\admin\client.py", line 278, in _refresh_controller_id
    controller_version = self._client.check_version(controller_id, timeout=(self.config['api_version_auto_timeout_ms'] / 1000))
  File "C:\Program Files\Python36\lib\site-packages\kafka\client_async.py", line 909, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "C:\Program Files\Python36\lib\site-packages\kafka\conn.py", line 1240, in check_version
    raise Errors.NodeNotReadyError()
**kafka.errors.NodeNotReadyError: NodeNotReadyError**
Exception ignored in: <bound method NativeKafkaEventStreamer.__del__ of <src.event_stream.kafka_native_event_streamer.NativeKafkaEventStreamer object at 0x00000221DDDBEE10>>
Traceback (most recent call last):

**To Reproduce**
As described above

**Expected behavior**
Should be able to connect to external kafka

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
NA

**Comment by alemorcuq** [comment]
Hi, @zbeedatm.

I understand you are trying to access Kafka from outside the cluster. Please, read this README section on that topic: https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster

**Comment by zbeedatm** [comment]
Hi, thanks for replying.
I added these to my values.yaml:

> serviceAccount:
       create: true
externalAccess:
       enabled: true
       service:
           type: NodePort
           nodePorts: [30001]
       autoDiscovery.enabled: true

**Note**: I had the rbac.create=true already and I had to add nodePorts cause I was getting this error when trying to install it:

> Number of replicas and nodePort array length must be the same. Currently: replicaCount = 1 and nodePorts = 0

But the kafka-0 is not loading up and it's getting into CrashLoopBackOff, when looking at the log I can see:

> ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Missing required configuration `zookeeper.connect` which has no default value.
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1901)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1896)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1389)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1327)
        at kafka.Kafka$.buildServer(Kafka.scala:67)
        at kafka.Kafka$.main(Kafka.scala:87)
        at kafka.Kafka.main(Kafka.scala)


I'm afraid that I caused issue with my env when I tried to deal with the config (of server.properties) manually, I tried someting like this earlier:

> #Kafka Configuration
#Specify content for server.properties
#NOTE: This will override any KAFKA_CFG_ environment variables (including those set by the chart)
#The server.properties is auto-generated based on other parameters when this parameter is not specified
#config:
    #listeners=PLAINTEXT://9.148.244.4:9092
    #advertised.host.name=9.148.244.4

**Comment by zbeedatm** [comment]
If you can advise regarding it please, I'm straggling with configuring it to work with NodePort for the last few days.
I also took a look at this [issue](https://github.com/bitnami/charts/issues/5975), which he says that it worked for him and I still can't find what is missing in my case!

**Comment by zbeedatm** [comment]
After configuring:

> listeners: [EXTERNAL://:9094, INTERNAL://:9092]
advertisedListeners: [EXTERNAL://9.x.x.x:9094, INTERNAL://kafka:9092]
listenerSecurityProtocolMap: PLAINTEXT:plaintext,INTERNAL:plaintext,EXTERNAL:plaintext,CLIENT:plaintext
allowPlaintextListener: true

Passed the `kafka.errors.NodeNotReadyError` but now failing on something else:

> AssertionError: Broker id -1 not in current metadata

Any hints?!!!

**Comment by alemorcuq** [comment]
Can you give some step by step instructions to reproduce the issue, @zbeedatm ?

**Comment by zbeedatm** [comment]
sure:
1) ip a --> to get the ip address (of linux machine) of auth0 (with the format 9.x.x.x)
2) start minikube with: `minikube start --driver=none --apiserver-ips 9.x.x.x`
3) helm install kafka bitnami/kafka -f [values_kafka.yaml](https://pastebin.com/KGZdgNTm)
4) wait for pods to be ready, and `minikube service list` to get the url of kafka

After doing that kafka is deployed successfully and all pods are up, but within my python code I manage to create a consumer and a producer, but failing on creating the AdminClient and getting that exception:

in my config the url is configured to the ip 9.x.x.x (from step 1) and port 3xxxx (from step 4) 

`
    def __init__(self, config):
        """
        :param config:
        """
        self.url = config['url']
        server = self.url

        client_id = config['client_id'] if config['client_id'] != "" else "default_client"
        group_id = config['group_id'] if config['group_id'] != "" else "default_group"

        self.producer = None
        self.consumer = None
        self.admin_client = None

        try:
            self.producer = KafkaProducer(
                bootstrap_servers=[server],
                # api_version=(0, 10, 1),
                value_serializer=lambda x: dumps(x).encode('utf-8')
            )
        except Exception as e:
            print(" ")
            print('Error: Create producer failed')
            print(" ")
            raise

        try:
            self.consumer = KafkaConsumer(
                auto_offset_reset="earliest",
                bootstrap_servers=[server],
                enable_auto_commit=True,
                # auto_commit_interval_ms=1,
                group_id=group_id,
                # api_version=(0, 10, 1),
                value_deserializer=self.forgiving_json_deserializer)
                # value_deserializer=lambda x: loads(x.decode('utf-8')))

        except Exception as e:
            print(" ")
            print('Error: Create consumer failed')
            print(" ")
            raise

        try:
            self.admin_client = KafkaAdminClient(
                bootstrap_servers=server,
                client_id=client_id)
        except Exception as e:
            print(" ")
            print('Error: Create Admin Client failed')
            print(" ")
            raise
`

**Comment by alemorcuq** [comment]
As I don't have the same environment as you I didn't follow the same steps as you. This is what I did to access the Kafka cluster from the outside the cluster using NodePorts:

1. I created a `my.yml` file with these values:

```
externalAccess:
  enabled: true
  service:
    type: NodePort
  autoDiscovery:
    enabled: true
serviceAccount:
  create: true
rbac:
  create: true
```

2. I installed the chart running `helm install kf bitnami/kafka -f my.yaml`

3. I'm running on `minikube`, so I got its IP:

```
❯ minikube ip
172.16.47.5
```

4. I checked which port was set as NodePort for the Kafka cluster:

```
❯ kubectl get svc
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kf-kafka                ClusterIP   10.103.227.210   <none>        9092/TCP                     15m
kf-kafka-0-external     NodePort    10.101.185.235   <none>        9094:32638/TCP               15m
kf-kafka-headless       ClusterIP   None             <none>        9092/TCP,9093/TCP            15m
kf-zookeeper            ClusterIP   10.97.34.160     <none>        2181/TCP,2888/TCP,3888/TCP   15m
kf-zookeeper-headless   ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   15m
```

We can see in the `kf-kafka-0-external` service that the port is `32638`.

5. Outside of Minikube I started a Kafka container to try to connect to the Kafka cluster:

```
❯ docker run --rm -ti bitnami/kafka -- bash
 09:48:36.57
 09:48:36.57 Welcome to the Bitnami kafka container
 09:48:36.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 09:48:36.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 09:48:36.58

I have no name!@a40a6a11bdf6:/$ kafka-console-producer.sh --broker-list 172.16.47.5:32638 --topic test-topic
>hi, this is a message
[2021-06-17 09:44:11,513] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 3 : {test-topic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
>and this is another message
I have no name!@a40a6a11bdf6:/$ kafka-console-consumer.sh --bootstrap-server 172.16.47.5:32638 --topic test-topic --from-beginning
hi, this is a message
and this is another message
^CProcessed a total of 2 messages
```

I can connect to the cluster and produce and consume messages.

**Comment by zbeedatm** [comment]
Can you try to create a topic please?
Cause the admin_client (which I'm failing on creating it) is being used to create a topic later.

**Comment by alemorcuq** [comment]
It works as well @zbeedatm:

```
I have no name!@4d5a1a9f103c:/$ kafka-topics.sh --bootstrap-server 172.16.47.5:32638 --create --topic create-test
Created topic create-test.
```

I suggest you to review your configuration and maybe try doing changes in small increments to identify your issue.

**Comment by zbeedatm** [comment]
I took your yaml as is and installed it and still had the same issue.
Maybe the problem is with kafka-python `from kafka.admin import KafkaAdminClient, NewTopic` or some environment issue that is blocking the connection to the broker!

Thanks anyway.

**Comment by alemorcuq** [comment]
Let me know if you end up identifying the issue!
