### ISSUE TITLE
How import sync modules used by dags in airflow

### ISSUE THREAD

**Issue by rjribeiro** [bitnami/charts#6642]
**Which chart**:
airflow 10.0.8

**Describe the bug**
My dags use functions written in a .py file. Even putting the module in the same repository as the dags, it cannot be imported by the dags. The error "Module not found" is returned. I tried putting the module as a plugin, but it doesn't work. 
```
  dags:
    ## Enable in order to download DAG files from git repositories.
    ##
    enabled: true
    repositories:
      - repository: https://xxxxx:xxxxxx@gitlab.com/xxxxx/dags.git
        branch: {{ BRANCH }}
        name: ecdt
        path: dags
  plugins:
    ## Enable in order to download Plugins files from git repositories.
    ##
    enabled: true
    repositories:
      - repository: https://xxxxxx:xxxxxxxx@gitlab.com/xxxxxxx/dags.git
        branch: {{ BRANCH }}
        name: ecdt
        path: plugins
  clone:
    extraEnvVars:
      - name: PYTHONPATH
        value: "/opt/bitnami/airflow/dags/git_ecdt:/opt/bitnami/airflow/git_ecdt"
```
# Structure of repository:
```
repo
├── dags
│   ├── exemplo_dag.py
├── plugins
│   ├── ecdt_utils.py
│   └── __init__.py
└── README.md
```

**To Reproduce**

**Expected behavior**
dags can use functions written in a module

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**
Using GCP GKE

**Comment by migruiz4** [comment]
Hi @rjribeiro,

Could you please share how are you importing the module? 

Using the values.yaml you shared, your chart should clone `repo/plugins` into `/opt/bitnami/airflow/plugins/git_ecdt` and `repo/dags` into `/opt/bitnami/airflow/dags/git_ecdt`.

According to Airflow documentation, both paths should be included in the Airflow Python path by default: https://airflow.apache.org/docs/apache-airflow/stable/modules_management.html
```console
$ airflow info
...
Paths info
airflow_home    | /opt/bitnami/airflow                                                                                                            
system_path     | /opt/bitnami/common/bin:/opt/bitnami/python/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/airflow/venv/bin:/usr/local/sbin:/usr/l
                | ocal/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                          
python_path *   | /opt/bitnami/airflow/venv/bin:/opt/bitnami/airflow/venv/bin:/opt/bitnami/python/lib/python38.zip:/opt/bitnami/python/lib/python3
                | .8:/opt/bitnami/python/lib/python3.8/lib-dynload:/opt/bitnami/airflow/venv/lib/python3.8/site-packages:/opt/bitnami/airflow/dags
                | :/opt/bitnami/airflow/config:/opt/bitnami/airflow/plugins                                                                       
airflow_on_path | True                        
...
```

In this case, you could troubleshoot this issue doing the following:

1- Open a bash terminal in one of the airflow pods, and check the dags and plugins are correct:
```
$ kubectl exec -it airflow-worker-0 -- bash
$ ls -Rla /opt/bitnami/airflow/plugins/
$ ls -Rla /opt/bitnami/airflow/dags/
```
2- Run `airflow plugins` and check airflow can load the plugins.
3- Manually set `PYTHONPATH` and try to import your module:
```
$ export PYTHONPATH="$PYTHONPATH:/opt/bitnami/airflow/dags:/opt/bitnami/airflow/plugins"
$ /opt/bitnami/airflow/venv/bin/python3
>>> import git_ecdt
Hello from airflow_operators
>>>
```
4- If your Dags continue to fail with the same issue, try setting:
```
extraEnvVars:
        - name: PYTHONPATH
           value: "/opt/bitnami/airflow/dags:/opt/bitnami/airflow/plugins"
```
Note: you are currently setting `clone.extraEnvVars`, which is a different setting to `extraEnvVars`.

Let me know if you need any further help.

**Comment by rjribeiro** [comment]
hi @migruiz4 I didn't find this folder /opt/bitnami/airflow In the folder /opt/bitnami there are only common, git, licenses and scripts folders

**Comment by migruiz4** [comment]
Hi @rjribeiro,

When configuring Airflow with Git it will add two additional containers to your Pod.
So your pod will include the following containers:
- An initContainer called `clone-repositories` that is executed when the pod initializes and performs the initial repository clone.
- A sidecar container called `sync-repositories` that updates your repository with any change.
- The Airflow container (airflow-web, airflow-scheduler or airflow-worker).

> I didn't find this folder /opt/bitnami/airflow In the folder /opt/bitnami there are only common, git, licenses and scripts folders

That means that you opened a bash session into the `sync-repositories` container.
To open a Bash session into the Airflow container, you need to add the option `-c <container-name>`. For example, the following command would open a bash terminal in the Airflow worker:
```
kubectl exec -it airflow-worker-0 -c airflow-worker -- bash
```

> About extraEnvVars, the right place for extraEnvVars is in sync.extraEnvVars?

- `clone.extraEnvVars` adds additional environment variables to the `clone-repositories` initContainer.
- `sync.extraEnvVars` adds additional environment variables to the `sync-repositories` initContainer.
- `extraEnvVars` adds additional environment variables to all the Airflow containers.

In this case, PYTHONPATH would be configured in `extraEnvVars` (not nested under any other object), as we want to configure that extraEnvVar for all the Airflow containers.

**Comment by rjribeiro** [comment]
it works, but i cannot import a function from ecdt_utils.py. 
I run ```from git_ecdt.ecdt_utils import *``` and dont work

**Comment by migruiz4** [comment]
I'm sorry but I will need some more information. What do you mean by it works but the module won't import?

I previously provided troubleshooting steps, in what step did you encounter this issue? What is the error message?

Does importing the module without using wildcard work? `import git_ecdt`

**Comment by rjribeiro** [comment]
i add to python path /opt/bitnami/airflow/dags/git_ecdt
It worked

**Comment by migruiz4** [comment]
Great! Thank you for sharing your solution.
