### ISSUE TITLE
Memcached persistence not working at all

### ISSUE THREAD

**Issue by cache-sk** [bitnami/charts#6647]
**Which chart**:
bitnami/memcached

**Describe the bug**

During examining [issue](https://github.com/bitnami/bitnami-docker-memcached/issues/70) in memcached docker image, i have noticed missing space between `-e` and `/cache-state/memory_file` in `statefulset.yaml`.

I was ready to create PR [with fix](https://github.com/cache-sk/charts/commit/57673e3b3eb4c78de6a9acf0478cff2fba3c59a0), but when i test deployed it, memcached crashed with this in log:
```
memcached 21:25:07.45
memcached 21:25:07.54 Welcome to the Bitnami memcached container
memcached 21:25:07.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-memcached
memcached 21:25:07.55 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-memcached/issues
memcached 21:25:07.55

memcached 21:25:07.74 INFO  ==> ** Starting Memcached **
failed to open file for mmap: No such file or directory
```

I am not sure, if this experimental persistence feature work at all, but this is out of my league to resolve..

**Comment by juan131** [comment]
Hi @cache-sk 

Thanks so much for reporting this issue! I could also reproduce and I can confirm that persistence wasn't properly configured.

I just send a PR to address it!
