### ISSUE TITLE
[bitnami/common] add support for policy api version detection

### ISSUE THREAD

**Issue by davidkarlsen** [bitnami/charts#6648]
**Which chart**:
common

**Is your feature request related to a problem? Please describe.**
It would be nice to add version detection for the policy api, similar to what's done for rbac, ingress etc

**Describe the solution you'd like**
add poliicy api functions to https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl

**Describe alternatives you've considered**
N/A

**Additional context**
v1 was made GA in k8s 1.21

**Comment by marcosbc** [comment]
It's a great suggestion, thanks! I'm going to create an internal task to investigate further.

In the meantime, if you'd like to speed the process up, feel free to send a PR with the appropriate changes to bitnami/common and the desired list of charts. We'd be glad to help with the review and release. Afterwards we'd take care of the rest of charts.
