### ISSUE TITLE
[bitnami/mariadb-galera] mariadbConfiguration in default values.yaml not honoured

### ISSUE THREAD

**Issue by CrazyByDefault** [bitnami/charts#6651]
The default values.yaml file exposes a `mariadbConfiguration` section, which is mounted within the container to `/bitnami/conf/my.cnf`, which is never read. Mariadb runs within the `/opt/bitnami/mariadb/` folders, and the config files it uses come from `/opt/bitnami/mariadb/conf/my.cnf`

Seems like this change was introduced in #6567, but the default mariadb datadir/home directory didn't change, causing this issue.

**Comment by miguelaeh** [comment]
Hi @CrazyByDefault ,
Checking the change it seems that the configuration mounted at `/bitnami/conf/my.cnf` should be copied in the `mysql_initialize` function to the `/opt/bitnami/mariadb/conf/my.cnf` file.
Isn't that working properly for you?

**Comment by CrazyByDefault** [comment]
@miguelaeh 

No, it doesn't seem to be. The variables I set do not show up when I run `SHOW VARIABLES;` after connecting. Although I was assuming it was an issue with just my encryption config, even simple params such as `log_warnings` and `log_error` are not being set.

I can ssh into the container and verify in a bit.

**Comment by CrazyByDefault** [comment]
Here is the config I see at `/opt/bitnami/mariadb/conf/my.cnf` - 

```
[mysqladmin]
user=mariadb-root

[mysqld]
skip_host_cache
skip_name_resolve
explicit_defaults_for_timestamp
basedir=/opt/bitnami/mariadb
datadir=/bitnami/mariadb/data
port=3306
tmpdir=/opt/bitnami/mariadb/tmp
socket=/opt/bitnami/mariadb/tmp/mysql.sock
pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
max_allowed_packet=16M
bind_address=0.0.0.0
log_error=/opt/bitnami/mariadb/logs/mysqld.log
character_set_server=utf8
collation_server=utf8_general_ci
plugin_dir=/opt/bitnami/mariadb/plugin
binlog_format=row
log_bin=mysql-bin

[client]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
default_character_set=UTF8
plugin_dir=/opt/bitnami/mariadb/plugin

[manager]
port=3306
socket=/opt/bitnami/mariadb/tmp/mysql.sock
pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid

[galera]
wsrep_on=ON
wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
wsrep_sst_method=mariabackup
wsrep_slave_threads=4
wsrep_cluster_address=gcomm://sx-galera-mariadb-galera-headless.default.svc.cluster.local
wsrep_sst_auth=mariabackup:password
wsrep_cluster_name=sx-galera
wsrep_node_name=sx-galera-mariadb-galera-0
wsrep_node_address=10.80.5.79

[mariadb]
plugin_load_add=auth_pam
!include /opt/bitnami/mariadb/conf/bitnami/my_custom.cnf
```

The include at the bottom links to an empty file, which I'm guessing is the location the config should be mounted at during init.

**Comment by miguelaeh** [comment]
Hi @CrazyByDefault ,
Is that happening to you in the first installation or when trying to upgrade the chart?

**Comment by CrazyByDefault** [comment]
It is happening on both @miguelaeh 

My first deployment of the chart was this weekend, which is when I ran into the issue. I attempted to upgrade the chart a few times with a different set of mariadbConfiguration defined in `values.yaml` and none of them were showing up in the logs/`SHOW VARIABLES;` on the pods.

**Comment by miguelaeh** [comment]
Hi @CrazyByDefault ,
We found the issue. It seems the PR was landed but the images didn;t have the needed changes yet. We are releasing the proper version of the images in order to fix this.
We will ping you once it is done.
sorry for the inconvenience

**Comment by alvneiayu** [comment]
hi @CrazyByDefault 

We have released a new image. Could you test with the new one, please? With the original configmap path, please (/bitnami/conf/my.cnf). I think that you will see mariadb-galera running without problems.

Thanks a lot

Álvaro

**Comment by CrazyByDefault** [comment]
@alvneiayu will test this today! thanks a lot :D

**Comment by CrazyByDefault** [comment]
@alvneiayu this is fixed in the latest version! closing the issue :D
