### ISSUE TITLE
[bitnami/grafana] replicaCount > 1 doesn't works when there are additional plugins deployed

### ISSUE THREAD

**Issue by rbudiharso** [bitnami/charts#6658]
**Which chart**:
bitnami/grafana 5.2.17

**Describe the bug**
When we deploy bitnami/grafana with additional plugins, increasing replicaCount failed for subsequent pods with error `failed to extract plugin archive: failed to extract file: file "<plugin/path>" is in use - please stop Grafana, install the plugin and restart Grafana`

**To Reproduce**

deploy bitnami/grafana with values.yaml:
```yaml
plugins: plugin1,plugin2
replicaCount: 2
```
the second pod would error with similiar message to the above. I've tried to deploy with single replica and then scale up the deployment, also via helm upgrade, all didn't work.
![screenshot-20210614-182023](https://user-images.githubusercontent.com/43447/121884505-36bd3200-cd3d-11eb-9926-03a444997510.png)

**Expected behavior**
subsequent (other than the first) pods deployed successfully. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```          
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
The error happens with every plugin that I tried.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know, it seems to me that the installation should only take place in one of the replicas. There are two options here:

- Change from Deployment to Statefulset, so we have a clear identifier of which the `instance-0` is and then install the plugins only in that one.
- If the number of replicas is above 1, then set an environment variable to not crash the container if the `in use` message appears.

I think that the less breaking feature would be option 2, thoughts?

**Comment by rbudiharso** [comment]
Hi,
Yes, I don't know how grafana start up procedure is, but I think options 2 is the better option.

**Comment by javsalgar** [comment]
Great. I will create a task for this. I cannot guarantee an ETA, but as soon as there are more news, I'll let you know.

**Comment by fmulero** [comment]
Hi @rbudiharso

I am trying to reproduce this issue with latest version of the chart and I am not able to reproduce it. There were several changes in the grafana container and chart since this issue was opened. Could you try to reproduce the issue again? If you can reproduce it, Could you share your `values.yaml`?

Regards
