### ISSUE TITLE
[bitnami/mongodb-sharded] numactl issue in all instances 

### ISSUE THREAD

**Issue by F43RY** [bitnami/charts#6660]
**Which chart**:
bitnami/mongodb-sharded:4.5.0

**Is your feature request related to a problem? Please describe.**
logging into a mogodb through a POD, client complains NUMA settings are missing,

**Describe the solution you'd like**
Is it possible add an external variable in values.yaml that can help to launch instances with numactl set as complained?

**Additional context**
The following lines with the issue from client:
```
The server generated these startup warnings when booting: 
        2021-06-14T14:41:46.196+00:00: You are running on a NUMA machine. We suggest launching mongod like this to avoid performance problems: numactl --interleave=all mongod [other options]
        2021-06-14T14:41:46.196+00:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
```

Thx
F43RY

**Comment by marcosbc** [comment]
Hi @F43RY, those are warnings and not errors, MongoDB is going to work fine with them.

As for running MongoDB with those options in Bitnami charts, unfortunately it is not currently supported. To do that you would have to:

* Extend the existing Bitnami [`mongodb-sharded` container image](https://github.com/bitnami/bitnami-docker-mongodb-sharded/) and install Numa packages, for `numactl` to exist as a command.
* Update the chart template and override `command:` in the statefulsets, prepending to the [original commands](https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/master/4.4/debian-10/Dockerfile#L31).

**Comment by marcosbc** [comment]
If you wish to get support for Numa for Bitnami MongoDB Sharded images, feel free to send a PR to each respective repo! We'd be glad to help with the review and release.

**Comment by F43RY** [comment]
Hi,
sorry for this late post but I don't have much time....
As first step I sent the following [PR](https://github.com/bitnami/bitnami-docker-mongodb-sharded/pull/17) in order to include numactl in docker and enabled by an env var. Afterwards, if OK th PR I'm trying to code this repo
