### ISSUE TITLE
[bitnami/airflow]: Airflow variable "does not exist" after creating it

### ISSUE THREAD

**Issue by knightoftheshadows** [bitnami/charts#6663]
This problem refers to the Airflow chart.
I configured the chart to download DAGs from a git repo. After the deploy process, naturally the DAGs are broken because no airflow variables exist.

But I imported Airflow variables manually and the problem persists!

Error message >> KeyError: 'Variable env does not exist'

But the variable exists. Executing ``` airflow variables get env ``` in the pod shell returns the correct content value.

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```
**Additional context**
Using GCP GKE

**Comment by miguelaeh** [comment]
Hi @knightoftheshadows ,
Could you elaborate on what `no variables exist in the environment` means?

**Comment by knightoftheshadows** [comment]
It means that the variables page in airflow web is empty after deploying.

**Comment by miguelaeh** [comment]
Hi @knightoftheshadows ,
Checking the docs these are the variables that should exist by default: https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html Could you confirm you are talking about those ones? 
Also, could you share the DAGs you are using? I can see the get function has a `default` parameter in case the variables don't exist: https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/models/variable.html
Could you also share how to reproduce the issue step by step?

**Comment by maryampashmi** [comment]
Hello. seems I have a similar issue, here is my code, very simple. after executing i am receiving this error. We are using airflow 2.1.2

A  json, uploaded to variable: 
{
	"example_variables_config": {
		"var1": "value1",
		"var2": [1, 2, 3],
		"var3": {
			"k": "value3"
		}
	}
}
```
import airflow
from datetime import datetime

from airflow import DAG
from airflow.models import Variable 
from airflow.operators.dummy import DummyOperator
from airflow.operators.bash import BashOperator

default_args = {
    'owner': 'airflow',
    'start_date': datetime(2021, 2, 15),
    'end_date': datetime(2021, 2, 15)    
}

dag = DAG('example_variables', 
    schedule_interval="@once", 


## upload a json file, and we create just one connection
# Access like a dictionary
dag_config = Variable.get("example_variables_config", deserialize_json=True)
var1 = dag_config["var1"]
var2 = dag_config["var2"]
var3 = dag_config["var3"]

start = DummyOperator(
    task_id="start",
    dag=dag
)

# To test this task, run this command:
# docker-compose run --rm webserver airflow test example_variables get_dag_config 2019-02-15
t1 = BashOperator(
    task_id="get_dag_config",
    bash_command='echo "{0}"'.format(dag_config),
    dag=dag,
)

# You can directly use a variable from a jinja template
## {{ var.value.<variable_name> }}

t2 = BashOperator(
    task_id="get_variable_value",
    bash_command='echo {{ var.value.var3 }} ',
    dag=dag,
)

## {{ var.json.<variable_name> }}
t3 = BashOperator(
    task_id="get_variable_json",
    bash_command='echo {{ var.json.example_variables_config.var3 }} ',
    dag=dag,
)

start >> [t1, t2, t3]
```

**we recently uploaded the helm
https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md

**Comment by miguelaeh** [comment]
Hi @maryampashmi ,
I am bit confused, the Chart you referenced is not the bitnami Helm Chart, but a different one. Could you clarify if you are using the bitnami chart?

**Comment by maryampashmi** [comment]
hello , sorry . It's not <bitnami> . I may remove the issue

**Comment by abhishektrivedi-hs** [comment]
hello, i had the same issue. even after passing the right variable airflow was keep displacing the variable not found error. 
after checking database, i saw 1 entry in below table-
select * from import_error

removed the entry from db and issue fixed.

**Comment by pablogalegoc** [comment]
@abhishektrivedi-hs thanks for sharing!

**Comment by akhikolla** [comment]
@abhishektrivedi-hs  can you please elaborate more on removing the entry from the database. Right now I am not using any database as such, I am trying to create a new data table for Big Query.  

In a case like this what should be the resolution for "KeyError: 'Variable owner does not exist'"
