### ISSUE TITLE
postgreSQL backup running in kubernetes environment

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#6664]
**Which chart**:

postgresql-ha helm chart

**Describe the bug**

we have deployed postresql-ha helm chart in production kubernetes environment and planning to execute the regular backup from postgresql database. I was looking for documentation for doing backup and did not find something that is relevant to my requirement. Please can you let me know if you have any suggestion or steps to execute for the backup.

I have deployed metrics side car container along with with the postgresql . Please can you check below output and provide your suggestion ?

**[root@portal-worker-app11 .kube]# kubectl get po -n test6-iamdb**
NAME                                   READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-bfc847fd4-5cgrw   1/1     Running   0          6d23h
postgresql-ha-pgpool-bfc847fd4-qrs29   1/1     Running   0          6d23h
**postgresql-ha-postgresql-0             2/2     Running   0          6d23h
postgresql-ha-postgresql-1             2/2     Running   0          6d23h**

**Version of Helm and Kubernetes**:

**[root@portal-worker-app11 .kube]# kubectl version**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.17) exceeds the supported minor version skew of +/-1
[root@portal-worker-app11 .kube]# 

**Additional context**

**Comment by erpel** [comment]
I don't really see how backing up PostgreSQL with the postgresql-ha chart is any different from backing up any other PostgreSQL server.
I suggest you check out the regular documentation, especially pg_dump and apply it to the server running in your cluster.

**Comment by alemorcuq** [comment]
Hi, @parvaths1118.

As @erpel said, you can back it up like any other PostgreSQL server. For example, you can use a tool like [Velero](https://velero.io/) to [backup your Kubernetes deployments](https://docs.bitnami.com/kubernetes/infrastructure/postgresql-ha/administration/backup-restore/).
