### ISSUE TITLE
[bitnami/external-dns] Add Go-Daddy Provider support

### ISSUE THREAD

**Issue by vrabbi** [bitnami/charts#6669]
**Which chart**:
bitnami/external-dns

**Is your feature request related to a problem? Please describe.**
we use Go Daddy as a DNS provider and External DNS has added support for it however it does not exist in the values.yaml and is not handled today by this chart

**Describe the solution you'd like**
add support for godaddy configuration

**Describe alternatives you've considered**
deploy manually external dns not using the bitnami chart

**Comment by pablogalegoc** [comment]
Hello @vrabbi,

This would be a good addition to the chart, would you be open to contributing this change via a PR? We'd be glad to review and help with the release!
