### ISSUE TITLE
[bitnami/postgresql-ha] existing secret setting for ldap bindpw doesn't work

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#6671]
**Which chart**:
[bitnami/postgresql-ha] 

**Describe the bug**

ldap existingSecret doesn't work

**To Reproduce**

Set ldap existingSecret and use bind-password as key in the secret and run install. It will throw errors like

```sh
VALUES VALIDATION:
postgresql-ha: LDAP
    Invalid LDAP configuration. When enabling LDAP support, the parameters "ldap.uri",
    "ldap.base", "ldap.binddn", and "ldap.bindpw" are mandatory. Please provide them:
```

**Version of Helm and Kubernetes**:

3

1.19

**Additional context**

I think it is caused by incorrect validation 

https://github.com/bitnami/charts/blob/ce18927b7cf4e1d2ea9d01711b3727ac709a330c/bitnami/postgresql-ha/templates/_helpers.tpl#L600

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. So, if I'm not mistaken, the test should be like this.

Instead of 

`(empty .Values.ldap.bindpw)`

it should be 

`(and (empty .Values.ldap.bindpw) (empty .Values.ldap.existingSecret))`

Is that correct?

**Comment by maxisam** [comment]
@javsalgar  I think so.

**Comment by javsalgar** [comment]
Awesome, we'll work on it. However, as you discovered the issue. Would you like to submit a PR fixing it?

**Comment by maxisam** [comment]
done https://github.com/bitnami/charts/pull/6692
