### ISSUE TITLE
[bitnami/keycloak] TLS only working for service type LoadBalancer

### ISSUE THREAD

**Issue by lbrue** [bitnami/charts#6677]
**Which chart:**
keycloak
Version 3.0.4 (keycloak appVersion 13.0.1)

**Describe the bug**
Cannot reach the Admin console or any other endpoint of keycloak over the https port when using a different `service.type` than `LoadBalancer`. 

I am trying to activate the keycloak TLS feature using these values:

```yaml
auth:
  tls:
    enabled: true
    jksSecret: test-keycloak
    keystorePassword: <MyPwd>
    truststorePassword: <MyPwd>
```
It works as long as I do not change the `service.type`, which is default `LoadBalancer`. With the Load Balancer I am able to access the admin console through the https port.

If I change the `service.type` to `ClusterIP` or `NodePort` the admin console is only reachable through the http port, not though https. On the https port I can't reach anything. The logs say, that the Undertow https listener is listening on the https port. I can't see any differences in the logs compared to using the LoadBalancer.

Am I not understanding something right or is this a bug?

**Expected behavior**
Being able to reach the admin console over https via a NodePort or ClusterIP service as it works with a LoadBalancer service.

**Version of Helm and Kubernetes:**
- Output of `helm version`:
`version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}`
- Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

**Additional context**
Using minikube

**Comment by alemorcuq** [comment]
Hi, @lbrue.

I've tested it with version `3.1.0` (that version is already published in this GitHub repository but has not been published to the registry yet) and it works for me using a ClusterIP service. Can you wait a bit for `3.1.0` to be released and try again (or you can try it using the code from this repository)?

**Comment by lbrue** [comment]
Hi @alemorcuq,

thanks for your response!

I tried using the version 3.1.0. Interestingly I got the NodePort to work as well. Seems like the way I was forwarding the ports was not correct (used Lens IDE and `kubectl port-forward` with the same results).  Using the NodePort ports directly was working now.

Therefore I assume the chart should be working. 
Can you maybe share your setup with that you got the ClusterIP running (espacially how you did the port forwarding)? Did you test with minikube? 

The goal I try to achive is to be able to sign in as a keycloak user from outside the cluster via a browser. I have it running using an ingress as the TLS termination and wanted to switch to keycloaks own TLS. The reason for that is that I need a cluster internal keycloak TLS connection from another pod and I don't wanna reroute the traffic over the ingress and therefore outside of the cluster.

**Comment by lbrue** [comment]
Ok figured out my problem, I made a http request instead of a https request from my browser... 
The chart is fully working!

Sorry for the waste of your time and thanks for your response!
