### ISSUE TITLE
Bitnami Rabbitmq helm upgrade

### ISSUE THREAD

**Issue by amin224** [bitnami/charts#6678]
**Which chart**:
The name (and version) of the affected chart
chart: rabbitmq-8.6.0
version: 3.8.9

**Describe the issue**
Hello, I have 3 bitnami/rabbitmq instances running with incoming traffic on them. I need to make a change for the nodeSelector parameter in the statefulset in order to change nodes for the instances. I assume I have to upgrade my helm chart with the same command I used when I installed the chart, but will this upgrade stop all my rabbitmq instances at the same time and I lose traffic? Or should I edit the statefulset file instead?

Please suggest the best way to change nodes for my helm chart without downtime for my rabbitmq instances.

**To Reproduce**

1. Initial command used to setup: helm install -f values.yml rabbitmq-server bitnami/rabbitmq --namespace rabbitmq-namespace --set nodeSelector.assigned=broker-node --set volumePermissions.enabled=true --set replicaCount=3

2. helm upgrade rabbitmq-server bitnami/rabbitmq  --set nodeSelector.assigned=broker-node-2

**Expected behavior**

I am hoping not to lose any messages when upgrading my helm chart.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4fa5b2f242645aaf629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: v1.18.9-eks-d1
Server Version: v1.18.9-eks-d1

```

**Additional context**

I had an alternative solution of creating a new release of my rabbitmq cluster and changing the connection string for my application that is sending the messages to rabbitmq. But I wanted to know if the upgrade feature can do the job with no loses to the messages.

**Comment by amin224** [comment]
When trying to upgrade my bitnami/rabbitmq helm chart to change the nodeSelector of my rabbitmq instances I recieved this error.

`Error: UPGRADE FAILED: cannot patch "broker-test-rabbitmq" with kind StatefulSet: StatefulSet.apps "broker-test-rabbitmq" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

**Comment by amin224** [comment]
As an example mentioned here 

> https://artifacthub.io/packages/helm/bitnami/postgresql#to-9-0-0

I assume I will have to delete my running statefulset in order to be able to upgrade my nodeSelector, but in theory this will stop my rabbitmq and I will lose traffic.

**Comment by Mauraza** [comment]
Hi @amin224,

Could you check this issue https://github.com/bitnami/charts/issues/3723?

**Comment by amin224** [comment]
Thank you @Mauraza , I will post my issue progress there [#3723](https://github.com/bitnami/charts/issues/3723)
