### ISSUE TITLE
NATS client instructions fail

### ISSUE THREAD

**Issue by howardjohn** [bitnami/charts#6680]
**Which chart**:
bitnami/nats

**Describe the bug**
Chart description says:
```
You can create a Golang pod to be used as a NATS client:

      kubectl run nats-client --restart='Never' --image docker.io/bitnami/golang --namespace custom-gateway-helm --command -- sleep infinity
      kubectl exec --tty -i nats-client --namespace custom-gateway-helm -- bash
      go get github.com/nats-io/nats.go
      cd $GOPATH/src/github.com/nats-io/nats.go/examples/nats-pub && go install && cd
      cd $GOPATH/src/github.com/nats-io/nats.go/examples/nats-echo && go install && cd
      nats-echo -s nats://nats-client.custom-gateway-helm.svc.cluster.local:4222 SomeSubject
      nats-pub -s nats://nats-client.custom-gateway-helm.svc.cluster.local:4222 -reply Hi SomeSubject "Hi everyone"
```

**To Reproduce**
Follow steps above. End up with error:
```
root@nats-client:/go#       cd $GOPATH/src/github.com/nats-io/nats.go/examples/nats-pub && go install && cd
bash: cd: /go/src/github.com/nats-io/nats.go/examples/nats-pub: No such file or directory
```

I think probably new golang version is not populating GOPATH

**Expected behavior**
Client is created properly

**Comment by howardjohn** [comment]
Should probably be `go install github.com/nats-io/nats.go/examples/nats-pub@latest`

But once I do that:
```
#       nats-echo -s nats://nats-client.custom-gateway-helm.svc.cluster.local:4222 SomeSubject
nats: Authorization Violation
```

**Comment by howardjohn** [comment]
Add `nats://user:password@...` works

**Comment by migruiz4** [comment]
Hi @howardjohn, I'm sorry for the late response.

Did you solve the issue or does the problem persist?

**Comment by howardjohn** [comment]
Hey , I was able to get things working, but the instructions (output after helm install) are incorrect so they probably need to be updated

**Comment by migruiz4** [comment]
Thanks for the heads up @howardjohn!

I have created a PR fixing the chart notes displayed after `helm install`.
