### ISSUE TITLE
[bitnami/redis] make it possible to use redis chart multiple times in an umbrella chart

### ISSUE THREAD

**Issue by kuznero** [bitnami/charts#6683]
**Which chart**: bitnami/redis, v14.4.0

**Is your feature request related to a problem? Please describe.**
When bitnami/redis chart is used multiple times in an umbrella chart `matchLabels` are confused.

**Describe the solution you'd like**
This PR adds support for `.Values.extraMatchLabels` which allows to specify additional match labels per sub-chart in an umbrella chart. This way it will be possible to ensure that `matchLabels` are unique per redis sub-chart.

**Additional context**
In order to be able to completely extend `matchLabels` in bitnami/redis chart it was necessary to extend `common.affinities.pods.*` templates to allow for additional labels. This change was merged with #6589.

**Comment by pablogalegoc** [comment]
Hi @kuznero! I see you've already opened a PR to address the issue, thank you!
