### ISSUE TITLE
[bitnami/redis] "LOADING Redis is loading the dataset in memory" on ready replicas

### ISSUE THREAD

**Issue by kuznero** [bitnami/charts#6685]
**Which chart**: bitnami/redis

**Describe the bug**

In short: it is possible to relatively easy get in a situation when a client that had just established a connection with Redis replica gets *"LOADING Redis is loading the dataset in memory"* error for some time.

Full description:

In some cases (presumably when the amount of data to load is significant, i.e. let's say over 500 MB) after initial delay of 5 seconds, default readiness probe for replicas (`probe_readiness_local.sh` or `probe_readiness_local*master.sh` that send *PING* commands to *localhost*) might produce the following sequence of results:

- *PONG* (exit code: `0`)
- *PONG* (exit code: `0`)
- *PONG* (exit code: `0`)
- *LOADING Redis is loading the dataset in memory* (exit code: `!= 0`)
- *LOADING Redis is loading the dataset in memory* (exit code: `!= 0`)
- *LOADING Redis is loading the dataset in memory* (exit code: `!= 0`)
- *LOADING Redis is loading the dataset in memory* (exit code: `!= 0`)
- *PONG* (exit code: `0`)
- *PONG* (exit code: `0`)
- *PONG* (exit code: `0`)

So, consider the following scenario:

- a particular replica pod can be marked *Ready* by its readiness probe within the first group of *PONG* responses
- and there will be some clients connecting to this pod (since it is now available through its service as an active and ready endpoint), e.g. there will be TCP connections established from clients to Redis replica running in this particular pod
- as replica goes into *LOADING...* stage and depending on the amount of data, readiness probe has a chance to turn this pod into *Not Ready*
- regardless whether this pod is getting *NotReady* or staying *Ready*, TCP connections are still alive, and connected clients can send commands to this Redis replica

Such commands result in the *"LOADING Redis is loading the dataset in memory"* error propagated to clients.

**To Reproduce**

1. make sure replicas have some data to load (in my case it took 15-20 seconds)
2. make sure to have some active clients trying to connect as soon as connection is lost
3. provoke a rolling update on replicas statefulset

**Expected behavior**
It is expected that clients should be able to connect (i.e. a replica pod should be marked *Ready*) only when it has completed loading data in memory, and thus can be considered *Ready* to serve clients commands.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
... server k8s version: v1.18.8
```

**Additional context**

It is possible to increase default `initialDelaySeconds` of the readiness probe for replicas statefulset to let's say `60` (one minute). This should ensure that data *started* loading. It is ok, that data will not complete loading after one minute - in this case readiness probe will be negative, and thus there will be no clients connecting.

The downside of this approach is that it will take longer to go through a rolling update.

It would be a lot better if it would be possible to reliably mark Redis replica as *Ready* when it is really *Ready* to accept commands from clients without any artificial delays (caused by possibly big `initialDelaySeconds` of readiness probe).

**Comment by juan131** [comment]
Hi @kuznero 

Thanks so much for the detailed analysis of the scenario.

I have a couple of questions:

- I presume that you're reproducing the scenario only when a new replica is created and it's loading the data. But I guess it could also be reproduce if it's a client the one loading a big amount of data after the replica is ready. Am I right?
- Are you suggesting that `ping_readiness_XXX.sh` scripts defined at the [health-configmap.yaml](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/health-configmap.yaml) should be "clever enough" to detect a `"..  loading the dataset in memory"` situation and avoid marking the pod as "ready"?

---

Side note: the chart provides the parameters `master.customReadinessProbe` and `replica.customReadinessProbe` that allow you to define an custom readiness probe you might want to implement.

**Comment by kuznero** [comment]
Hi @juan131,

* the exact scenario is when I run a rolling update on replicas, and fresh clients connect to replicas that just became *Ready*. I am not sure if it is an issue when Redis had already started and loaded its data, my guess is that it will sync with master instead, and that will be unnoticed by consumers connected to a replica. So, my main focus is on startup phase for a replica.
* I was trying to see if it is possible to extend `ping_readiness_*.sh` scripts to take into account this feature of Redis, but I am simply uncertain if that is generic enough, and if it should not instead be part of Redis project itself.

The reason for uncertainty on the second point is that I can easily imagine Redis configurations that run without a disk, in which case it will not get into the same issue. Thus, I am not certain where exactly it should (or even can) be fixed.

But having all these thoughts, I consider increasing `initialDelaySeconds` from `5` to `60` seconds on `replicas.customReadinessProbe` as my current solution (or workaround). This is tested and seems to be working nicely. The biggest worry I have with this approach is that I don't know if the dataset size that replica is loading affects the time when it starts loading it, i.e. I want to ensure that regardless if replica is loading 5 MB or 5 TB, loading process will start within a first minute. This is my assumption at the moment.

If you consider this a good default assumption, it then might make sense to increase the default `initialDelaySeconds` to something bigger than `5` seconds.

**Comment by juan131** [comment]
Hi @kuznero 

Thanks again for providing so many details!

IMHO, increasing the `initialDelaySeconds` is more a workaround rather than a solution to the problem.

The current probe is using the [redis-cli](https://redis.io/topics/rediscli) "ping" command (which seems the right command to use), but we might be running it too soon and the sequence you mentioned in the issue description can potentially happen. I don't know if there's a way to detect if a certain replica has already synced the data from the master node and wait for that moment before running the first "ping" command.

@rafariossaa I'd like you to share your thoughts about this.

**Comment by rafariossaa** [comment]
Hi,
  I think this could be a good use case for startup probes. I know they are recent because they were supported as a beta in Kubernetes v.1.18, and we should maintain compatibility with previous versions of kubernetes.
  In this case, I think we could follow the approach you proposed to make `ping_readines_xxxx` more intelligent.

**Comment by kuznero** [comment]
Hi @rafariossaa, making `ping_readiness_*.sh` smarter might not be trivial as it might depend on Redis configuration whether LOADING will happen at all or if it will take time.

But, I can potentially imagine introducing a flag (e.g. `.Values.waitUntillDataLoaded`) that can trigger startup probe to wait for some time (let's say `default .Values.waitUntilDataLoaded.timeoutSeconds 60`) to wait until PING will start responding with LOADING. As soon as first LOADING is encountered, startup probe can successfully complete and hand over to readiness probe that will turn a pod into `Ready` as soon as LOADING responses are not coming any longer and it receives PONG. And in cases when startup probe never sees LOADING responses, it will wait max `default .Values.waitUntilDataLoaded.timeoutSeconds 60` and then successfully hand over to readiness probe.

This approach will allow to go through LOADING phase a lot faster than with a fixed `.Values.replicas.customReadinessProbe.initialDelay` in the cases when data loads fast (most of the cases I would guess).

Please let me know if you think this approach makes sense and then I can sketch a PR.

**Comment by juan131** [comment]
Hi @kuznero 

Your approach makes sense but I found it very specific. I mean, we should cover in the chart the most common scenarios and provide flexibility for users that wan to customize the solution for their specific needs.

So, IMHO, I think we should add support for `master.customStartupProbe` and `replica.customStartupProbe` parameters (in a similar way we already have support for custom liveness/readiness probes) so this logic can be implemented.

**Comment by dunn** [comment]
This issue is still present on the current Redis chart.

**Comment by migruiz4** [comment]
Hi @dunn,

As mentioned in this thread, making `ping_readiness_xxxx` aware of this scenario may not be trivial, considering the behavior `OK -> Loading -> OK` and checking the configuration being the only method to determine whether there is data to load or not.

Support for `startupProbes` has been available for some time, so my recommendation would be tunning them depending on your use case.
