### ISSUE TITLE
Rabbitmq wont login when behind nginx reversed proxy

### ISSUE THREAD

**Issue by mjordanovski** [bitnami/charts#6689]
**Which chart**:
rabbitmq
**Describe the bug**
I deployed rabbitmq chart, and when I do port-forwarding of rabbitmq and access it's service on localhost, there is no problem logging in. But I also deployed nginx reverse proxy, and set rabbitmq to be on location:
https://my-public-domain.com/rabbitmq/
When I access this location, I see rabbitmq login page, but when I try to login it fails:

![image](https://user-images.githubusercontent.com/73869959/122367111-6f872200-cf5c-11eb-9b7b-0698dfe29f3a.png)

My nginx conf:
```
location /rabbitmq/api/ {
         rewrite ^ $request_uri;
         rewrite ^/rabbitmq/api/(.*) /api/$1 break;
         return 400;
         proxy_pass http://rabbitmq$uri;
        }
    location /rabbitmq {
          rewrite ^/rabbitmq$ /rabbitmq/ permanent;
          rewrite ^/rabbitmq/(.*)$ /$1 break;
          proxy_pass http://rabbitmq:15672;
          proxy_buffering                    off;
          proxy_set_header Host              $http_host;
          proxy_set_header X-Real-IP         $remote_addr;
          proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
        }
```
```
My rabbitmq.conf:
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    queue_master_locator = min-masters
    loopback_users.guest = false
    management.cors.allow_origins.1 =
    https://my-public-domain.com
```

Don't know if this is relevant, but I see these logs on nginx controller when this failed login happens:
[error] 190#190: *85336 rabbitmq could not be resolved (3: Host not found), client: 100.124.0.0, server: _, request: "GET /rabbitmq/api/auth HTTP/1.1", host: "https://my-public-domain.com"
"GET /rabbitmq/api/auth HTTP/1.1" 502 552
[error] 189#189: *85302 rabbitmq could not be resolved (3: Host not found), client: 100.100.0.0, server: _, request: "GET /rabbitmq/api/whoami HTTP/1.1", host: "https://my-public-domain.com"
"GET /rabbitmq/api/whoami HTTP/1.1" 502 552

**Comment by rafariossaa** [comment]
Hi,
  That error means that the proxy you deployed is not able to solve the host set in `proxy_pass` directive.
  Could you check if from the proxy node you are able to run the following ?
```
$ ping rabbitmq

$ curl http://rabbitmq:15672
```
  The `ping` command should return the rabbitmq service IP.

**Comment by mjordanovski** [comment]
Hi @rafariossaa , thanks for the reply.
Seems like /rabbitmq/api was not accessible with the current nginx conf. Managed to fix it by updating location /rabbitmq/api :
`location ~* /rabbitmq/api/(.*?)/(.*) {
        proxy_pass http://rabbitmq:15672$request_uri;
        proxy_buffering                    off;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }`

**Comment by rafariossaa** [comment]
Hi @mjordanovski ,
  Thanks for sharing your solution.
  I am happy you were able to solve the issue.
