### ISSUE TITLE
[bitnami/nginx] chart overwrites preexisting server_blocks

### ISSUE THREAD

**Issue by DaviGia** [bitnami/charts#6693]
**Which chart**:
nginx:9.2.0

**Describe the bug**
The chart always mounts `/opt/bitnami/nginx/conf/server_blocks` path. This mean that any preexisting *.conf file are ignored.

**To Reproduce**

1. create a custom [bitnami nginx docker image](https://github.com/bitnami/bitnami-docker-nginx)
2. customize the image by placing additional *.conf files in `/opt/bitnami/nginx/conf/server_blocks` (or in any subdirectory)
3. deploy the chart using the custom docker image
4. the pod may fail (e.g. the missing server_block declared a variable using `map`; the variable is not found during initialization) or behave unexpectedly (e.g. the missing server block exposed something else on a different port; nginx does not reply to the port)

**Expected behavior**
The chart should not mount the path `/opt/bitnami/nginx/conf/server_blocks` by default. It should do that only if it requires to write additional files to it (i.e. if one of those values are declared: `.Values.serverBlock`, `.Values.ldapDaemon.enabled`. `.Values.existingServerBlockConfigmap`).

https://github.com/bitnami/charts/blob/0960099f543a76037ee2f09b3ee853154e2d4ac3/bitnami/nginx/templates/deployment.yaml#L187-L197

Another solution would be to allow the user to disable the mount with an additional value.

NOTE: this bug can currently be circumvented by declaring the same server block using the `.Values.serverBlock` value.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Mauraza** [comment]
Hi @DaviGia,

If you check that content of the `/opt/bitnami/nginx/conf/server_blocks` of the image of bitnami there is this file:
```bash
$ cat /opt/bitnami/nginx/conf/server_blocks/server-blocks-paths.conf 
include  "/opt/bitnami/nginx/conf/server_blocks/ldap/*.conf";
include  "/opt/bitnami/nginx/conf/server_blocks/common/*.conf"
```
Maybe you don't need to customize the image to get all the *.conf files only add that configuration to `serverBlock`
https://github.com/bitnami/charts/blob/da613f5fa40810a915d615ed60b1edd8a829e313/bitnami/nginx/values.yaml#L155-L171

**Comment by DaviGia** [comment]
Hi @Mauraza,

my goal is to customize the preexisting default server block, I don't want to specify an additional server block (the default already take cares of the prometheus endpoint and it may specify something that I don't want to lose; i.e. it's safe to not overwrite the entire block).

To explain better what I want to do, here is the default nginx.conf from the docker image: 

https://github.com/bitnami/bitnami-docker-nginx/blob/236e09a9937664082d1707e43cacaa26e1c45aef/1.21/debian-10/rootfs/opt/bitnami/nginx/conf/nginx.conf#L41-L56

and that snippet represents what I need to add into the conf file:

``` diff
http {
  include       mime.types;
  # ......
  server_tokens off;

  # map content type to cache expiration
+ map $sent_http_content_type $expires {
+   default     off;
+   text/html   epoch;
+   text/css    epoch;
+   application/javascript  epoch;
+ }

  # HTTP Server
  server {
     # Port to listen on, can also be set in IP:PORT format
     listen  80;

     # send cache-control header
+   expires $expires;

     location /status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
     }
  }
}
```

both changes can be made by simply declaring two additional *.conf files in the directories that are included by default:

```
include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
```

while server_blocks can be populated from the chart itself, the second import needs to be changed from the docker image (no chart value can be used to declare additional conf file in this directory. This currently means that I need to declare custom configuration in two different artifacts, that's not ideal IMHO.

**Comment by Mauraza** [comment]
Hi @DaviGia,

I just created a PR fixing it. I hope that helps you.

**Comment by DaviGia** [comment]
Hi @Mauraza,

Thank you for the PR. I will wait for the artifact to be available to test it but it looks exactly what I wanted.

**Comment by DaviGia** [comment]
Hi @Mauraza,

As far as I can see the chart version 9.3.2 is still not avaiable through the official [repository](https://artifacthub.io/packages/helm/bitnami/nginx) (nor the 9.3.1). Is there a problem with the build or only minor version changes triggers the build?

**Comment by Mauraza** [comment]
Hi @DaviGia,

You are right, I'm going to investigate what is happened

**Comment by Mauraza** [comment]
Hi @DaviGia.

The last version is released. Could you check it?

**Comment by DaviGia** [comment]
> Hi @DaviGia.
> 
> The last version is released. Could you check it?

I can confirm that the new version is up and that the problem is fixed. Thank you!
