### ISSUE TITLE
Memcached metrics not working, if authentication is used.

### ISSUE THREAD

**Issue by cache-sk** [bitnami/charts#6695]
**Which chart**:
bitnami/memcached

**Describe the bug**

When `memcachedUsername` and `memcachedPassword` is set, it also activates binary protocol. I am wondering, if `memcached-exporter` supports binary protocol. And it looks like `memcachedUsername` and `memcachedPassword` is also not provided.

Log looks like this:

```
level=info ts=2021-06-17T17:47:39.946Z caller=main.go:53 msg="Starting memcached_exporter" version="(version=0.9.0, branch=HEAD, revision=887a783c7d6d7a53cd1e626789b8a276f3accde1)"
level=info ts=2021-06-17T17:47:39.946Z caller=main.go:54 msg="Build context" context="(go=go1.16.2, user=root@399c01cb5f27, date=20210326-06:21:24)"
level=info ts=2021-06-17T17:47:39.946Z caller=main.go:88 msg="Listening on address" address=:9150
level=info ts=2021-06-17T17:47:39.947Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=error ts=2021-06-17T17:47:50.121Z caller=exporter.go:577 msg="Failed to collect stats from memcached" err="read tcp 127.0.0.1:35420->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:47:51.121Z caller=exporter.go:582 msg="Could not query stats settings" err="read tcp 127.0.0.1:35442->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:47:58.319Z caller=exporter.go:577 msg="Failed to collect stats from memcached" err="read tcp 127.0.0.1:35466->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:47:59.321Z caller=exporter.go:582 msg="Could not query stats settings" err="read tcp 127.0.0.1:35474->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:00.119Z caller=exporter.go:577 msg="Failed to collect stats from memcached" err="read tcp 127.0.0.1:35480->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:01.119Z caller=exporter.go:582 msg="Could not query stats settings" err="read tcp 127.0.0.1:35500->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:03.471Z caller=exporter.go:577 msg="Failed to collect stats from memcached" err="read tcp 127.0.0.1:35512->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:04.472Z caller=exporter.go:582 msg="Could not query stats settings" err="read tcp 127.0.0.1:35518->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:10.119Z caller=exporter.go:577 msg="Failed to collect stats from memcached" err="read tcp 127.0.0.1:35546->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:11.120Z caller=exporter.go:582 msg="Could not query stats settings" err="read tcp 127.0.0.1:35554->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:13.471Z caller=exporter.go:577 msg="Failed to collect stats from memcached" err="read tcp 127.0.0.1:35570->127.0.0.1:11211: i/o timeout"
level=error ts=2021-06-17T17:48:14.472Z caller=exporter.go:582 msg="Could not query stats settings" err="read tcp 127.0.0.1:35576->127.0.0.1:11211: i/o timeout"
...
```

Also, k8s says, it is not started:

```console
Readiness probe failed: Get http://10.244.3.41:9150/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**To Reproduce**

Install Memcached helm chart with these values:

```yaml
memcachedUsername: admin
memcachedPassword: adminpass
metrics:
  enabled: true
```

**Comment by alvneiayu** [comment]
hi @cache-sk 

I can reproduce the problem. I am checking the memcached-exporter image. As you said, it seems that the memcached-exporter doesn't support credentials. Let me take a look.

About the binary protocol, I am not an expert in Memcached. We are using the memcached from memcached.org. Maybe you can find something in the [mailing list ](https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped) or in the [wiki](https://github.com/memcached/memcached/wiki).

I found this wiki article:

https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped

maybe it can help you with your question.

Thanks

Álvaro

**Comment by alvneiayu** [comment]
hi @cache-sk

I created an internal task and added it to the backlog. As you mentioned, the memcached-exporter doesn't have credential support implemented yet and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot for reporting the problem and for your time.

Álvaro

**Comment by cache-sk** [comment]
Hi @alvneiayu 

I am not an expert on memcached, I am just evaluating it for our next project and trying all possibilities 😀

SASL (authentication) is enabled via `-S` parameter, which automatically enables binary protocol, according [this blog](https://blog.couchbase.com/sasl-memcached-now-available/) and I tested it with [this library](https://pypi.org/project/python-binary-memcached/), so what I ment was, that memcached-exporter should support binary protocol too - afaik exporter connects to memcached and get STATS data (correct me if I am wrong).

**Comment by alvneiayu** [comment]
hi @cache-sk

I am not an expert in this chart/Memcached but seeing the code I think that you are right.

We will update this thread once we have news about the solution of this issue.

Thanks a lot

Álvaro

**Comment by carrodher** [comment]
Unfortunately, since we are a small team we didn't find the bandwidth to spend time on this topic nor there are plans to work on it in the short/middle term.
PRs are welcome, the team will be happy to review it and provide feedback.

**Comment by cache-sk** [comment]
Just final note: this is not problem of this chart and it is not solvable by bitnami team.
Problem is, that prometheus exporter is using gomemcache, which does not support nor binary protocol, nor sasl - https://github.com/prometheus/memcached_exporter/issues/25
