### ISSUE TITLE
[mariadb] The probe can not perceive after the occurrence of brain fissure in the cluster.

### ISSUE THREAD

**Issue by hamishliu** [bitnami/charts#6698]
The probe can not perceive after the occurrence of brain fissure in the cluster.

- mariadb-0 wsrep_cluster_size=2
- mariadb-1 wsrep_cluster_size=1
- mariadb-2 wsrep_cluster_size=2

Three copies pod status is runing（1/1）,  Service still distributes traffic to three pod, Resulting in business access to two inconsistent clusters

**Comment by juan131** [comment]
Hi @hamishliu 

Thanks for opening the issue!

On question: Are you using MariaDB or MariaDB Galera chart?

---

As a I side note, please note you can us the `xxx.customReadinessProbe` and `xxx. customLivenessProbe` parameters to define your custom probes so you can detect advanced issues such as brain fissures.

**Comment by hamishliu** [comment]
MariaDB Galera helm

**Comment by juan131** [comment]
Hi @hamishliu 

Could you please provide the instructions you followed to reproduce the issue? I'd like to reproduce the same scenario on my side. Thanks in advance.

**Comment by hamishliu** [comment]
![image](https://user-images.githubusercontent.com/79596614/122703227-ab372a00-d283-11eb-95f0-c84ff5e0b924.png)
![image](https://user-images.githubusercontent.com/79596614/122703234-aecab100-d283-11eb-82a7-2e9d2908ab79.png)
![image](https://user-images.githubusercontent.com/79596614/122703240-b1c5a180-d283-11eb-80d1-0f3ec0535f7d.png)

**Comment by hamishliu** [comment]
[galera mariadb cluster logs.zip](https://github.com/bitnami/charts/files/6683853/galera.mariadb.cluster.logs.zip)
Attached are the logs of the three nodes of galera mariadb cluster. Mysql-0 is expelled from the cluster to become a separate cluster, and mysql-1 and mysql-2 become a separate cluster.

**Comment by hamishliu** [comment]
After the brain fissure occurs in mysql-0, K8S service still distributes traffic to mysql-0, which has a great impact on the business side.

**Comment by juan131** [comment]
Thanks for the details @hamishliu 

My question is: how did brain fissure happened and `mysql-0` was expelled? I want to understand why this happened.

- Did it run any command to force the eviction of that node? 
- Did it happen without your intervention?

**Comment by hamishliu** [comment]
No intervention. Pod did not restart

**Comment by hamishliu** [comment]
Can I see the code in the log file I uploaded? The first node has an error log before the brain fissure. I don't know if it is the direct cause of the brain fissure.

2021-06-15 18:00:05 12 [Warning] WSREP: BF applier failed to open_and_lock_tables: 1213, fatal: 0 wsrep = (exec_mode: 2 conflict_state: 0 seqno: 7429427)
2021-06-15 18:00:05 12 [ERROR] Slave SQL: Error executing row event: 'Deadlock found when trying to get lock; try restarting transaction', Internal MariaDB error code: 1213
2021-06-15 18:00:05 12 [Warning] WSREP: Event 6 Write_rows_v1 apply failed: 1213, seqno 7429427
2021-06-15 18:00:05 12 [ERROR] WSREP: Failed to apply write set: gtid: ea0fbefc-c900-11eb-985c-73e8207693a5:7429427 server_id: 343e6f35-c901-11eb-8aca-8ea754675f17 client_id: 351300 trx_id: 85948409 flags: 3 (start_transaction | commit)
# User@Host: coding[coding] @  [10.42.0.72]

**Comment by juan131** [comment]
Hi @hamishliu 

Thanks so much for the info!!

Could you share the output of running the command below in every pod?

```console
$ kubectl exec -it POD_NAME -- cat /bitnami/mariadb/data/grastate.dat
```

Please also share the exact chart and image version you're using.

---

Side note: we highly encourage to periodically backup the database, it can be extremely useful in case some event such as the one you suffered occurs.

**Comment by hamishliu** [comment]
I have no name!@mysql-2:/$ cat /bitnami/mariadb/data/grastate.dat
# GALERA saved state
version: 2.1
uuid:    bc4149ca-d274-11eb-b4e7-cf915b00a038
seqno:   -1
safe_to_bootstrap: 0

**Comment by juan131** [comment]
Could you share the output of the other two pods too? We want to double-chek whether the UID is the same one on every replica.

**Comment by hamishliu** [comment]
There is no information about the fault at that time. I recently used chaos mesh hybrid engineering to inject the fault recurrence problem, blocking the communication between mariadb-0 and mariadb-1, and blocking the communication between mariadb-0 and mariadb-2. This is the time for mariadb -0 will be evicted from the cluster, because the default health detection of bitnamo only checks whether mysql is logged in normally, and does not check the status in the cluster, so restart will not be triggered here. I made an optimization solution because I found that the cluster appears every time Split-brain, the node that is evicted from the cluster cannot read and write the database, and can only log in to mysql,So I modified the content in livenessProbe, and changed mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD to mysql -uroot -p$MARIADB_ROOT_PASSWORD-e"select * from mysql.wsrep_cluster_members;", by querying any of the built-in tables, when the cluster A split brain will trigger meter reading failure, trigger pod restart, and cut off the traffic from svc to the failed pod.

**Comment by hamishliu** [comment]
![image](https://user-images.githubusercontent.com/79596614/123447568-96a0bc00-d60c-11eb-891f-642eb8c72114.png)
![image](https://user-images.githubusercontent.com/79596614/123447614-a3251480-d60c-11eb-8999-f37542bdcd69.png)

**Comment by hamishliu** [comment]
Pull requests：   https://github.com/bitnami/charts/pull/6769

**Comment by juan131** [comment]
Hi @hamishliu 

Thanks so much for giving us the context and providing a possible solution. I'll ping @rafariossaa and @javsalgar to check the PR and give you feedback about it.
