### ISSUE TITLE
[minio] MINIO_PROMETHEUS_AUTH_TYPE: public is not public =/

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/charts#6704]
**Which chart**:
minio:7.1.0? Can be earlier

**Describe the bug**
I found that my grafana dashboard for minio is empty, tried to find that the problem might be and found, that minio is not exposing metrics on `/minio/v2/metrics/cluster`

MINIO_PROMETHEUS_AUTH_TYPE: public
![image](https://user-images.githubusercontent.com/46970457/122565279-f3213b80-d04e-11eb-99d6-4d04dc766eee.png)

**To Reproduce**

1. Install minio in distributed mode
2. Enable servicemonitor/add pod/service annotations
3. Query `http://$host/minio/v2/metrics/cluster`
4. Login screen loaded =\

**Expected behavior**
Public metrics should be public

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I found that https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html#2-configure-authentication-type-for-prometheus-metrics, last section `curl https://play.min.io/minio/v2/metrics/cluster` is also returning login page, so maybe it is minio regression or breaking change

**Comment by rafariossaa** [comment]
Hi,
  I could get the metrics, I am not very sure if I am missing something.
  I installed minio with by running:
```
$ helm install myminio bitnami/minio --set metrics.serviceMonitor.enabled=true
```
  Once the pod was running, I got into the pod and run the following:
```
$ kubectl exec -it myminio-56b6d8b65-f2jrh -- bash

I have no name!@myminio-56b6d8b65-f2jrh:/opt/bitnami/minio-client$ curl http://localhost:9000/minio/v2/metrics/cluster 
# HELP minio_cluster_disk_free_inodes Total free inodes.
# TYPE minio_cluster_disk_free_inodes gauge
minio_cluster_disk_free_inodes{disk="/data",server="127.0.0.1:9000"} 0
# HELP minio_cluster_nodes_offline_total Total number of MinIO nodes offline.
# TYPE minio_cluster_nodes_offline_total gauge
...
```
and using the service name:
```
I have no name!@myminio-56b6d8b65-f2jrh:/opt/bitnami/minio-client$ curl http://myminio:9000/minio/v2/metrics/cluster        
# HELP minio_cluster_disk_free_inodes Total free inodes.
# TYPE minio_cluster_disk_free_inodes gauge
minio_cluster_disk_free_inodes{disk="/data",server="127.0.0.1:9000"} 0
# HELP minio_cluster_nodes_offline_total Total number of MinIO nodes offline.
# TYPE minio_cluster_nodes_offline_total gauge
...
```
Could you try this ?

**Comment by sergeyshaykhullin** [comment]
Hmm... Yes, both queries are worked for me to...

I am using port-forwarding and querying from host windows machine

![image](https://user-images.githubusercontent.com/46970457/122582712-2076e500-d061-11eb-9bc7-f5d73d3dcf13.png)

**Comment by sergeyshaykhullin** [comment]
![image](https://user-images.githubusercontent.com/46970457/122583425-e1955f00-d061-11eb-9e28-de4faec4c0db.png)

**Comment by sergeyshaykhullin** [comment]
But inside k8s is all working, so maybe i have trouble somewhere else...

**Comment by sergeyshaykhullin** [comment]
I found a problem, wrong scrape config, my bad...

Also i tried wsl and it is working

![image](https://user-images.githubusercontent.com/46970457/122586494-6d5cba80-d065-11eb-87e9-43dbec291ec3.png)

I think it is not a problem with minio or helm chart... PEBKAC (and windows curl)
