### ISSUE TITLE
Bitnami wildfly helm chart isuue

### ISSUE THREAD

**Issue by chirathb** [bitnami/charts#6705]
**Which chart**:
Bitnami/Wildfly helm chart 

**Is your feature request related to a problem? Please describe.**
I am using Bitnami wildfly helm chart. I already create pv(using nfs). alredy mount pv and pvc. when i used bitnami/wildfly mount path pod was Crashloopbackoff. when i used another mount path (used /tmp path) pod was running But all the files in the tmp folder will be deleted automatically.

**Describe the solution you'd like**
I need mount bitnami/wildflly path to nfs.

**Describe alternatives you've considered**
I used fsgroup and runas user 1000 and try with 0. my vm user was 1000.

**Comment by miguelaeh** [comment]
Hi @chirathb ,
Which error are you getting when mounting it in a path different from `tmp`?
Also, Your VM user should not affect to anything inside the chart

**Comment by chirathb** [comment]
A
![Screenshot from 2021-06-21 13-42-36](https://user-images.githubusercontent.com/38857483/122729717-163e2c00-d297-11eb-826a-628516721968.png)
fter volumePermissions true, we can fix that issue. But we can't access Administration Console.

Issue
Unable to redirect.
An automatic redirect to the Administration Console is not currently available. This is most likely due to the administration console being exposed over a network interface different from the one to which you are connected to.

To access the Administration console you should contact the administrator responsible for this WildFly installation and ask them to provide you with the correct address.

**Comment by miguelaeh** [comment]
Hi @chirathb ,
Could you share the steps you followed (including the parameters used to deploy the chart) and the environment where you are deploying Wildfly? Also, the URL to where you are connecting to get that error

**Comment by chirathb** [comment]
we used default bitnami helm chart. Used default value.yaml file.
