### ISSUE TITLE
[bitnami/prometheus] support setting rules config through configmap

### ISSUE THREAD

**Issue by rbudiharso** [bitnami/charts#6707]
**Which chart**:
bitnami/prometheus

**Is your feature request related to a problem? Please describe.**
Configuring recording and alerting rules via `additionalPrometheusRules` can be tedius and error prone for high number of rules. Setting it through a configmap should make it more manageable, similar to `additionalScraoeConfigs` but for configmap.

**Describe the solution you'd like**
Configure recording and alerting rule through a configmap.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Mauraza** [comment]
Hi @rbudiharso,

We agree that this would be a good addition to the asset, would you be open to contributing to this change via a PR? We'd be glad to review and help with the release.

**Comment by rbudiharso** [comment]
Sure, I'd love to help out, but I'm not familiar with helm chart development, any hint to get started?

**Comment by Mauraza** [comment]
Hi @rbudiharso,

Now, you can set  the `additionalPrometheusRules` in this way:
https://github.com/bitnami/charts/blob/632dee0b4a1d4f0efd90ce9a24c2edf284bafebe/bitnami/kube-prometheus/values.yaml#L806-L848

and this will be in this template
https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/templates/prometheus/additionalPrometheusRules.yaml

What would you like `additionalPrometheusRules` to look like?
