### ISSUE TITLE
Enable root access for jenkins pod

### ISSUE THREAD

**Issue by ayush121195** [bitnami/charts#6708]
I have installed Jenkins in AWS EKS via helm. Everything works well. Now I need to install Docker and other tools in Jenkins. But I am not able to do it. I have defined this in Jenkins.yaml.

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

These are the default settings, what exactly I need to change in the conf? or what is the jenkins root password for ssh?

Could anyone know?

**Comment by migruiz4** [comment]
Hi @ayush121195,

Please keep in mind that containers differ from virtual machines, and changes performed during runtime will be lost except for persisted volumes.

So by changing the container user to `root` might allow you to install additional components but changes will be lost if the container is restarted.

Instead, I would recommend creating your custom Docker image based on bitnami/jenkins, and configure the Helm chart to use them with the values `image.repository` and `image.tag`.

For example:
```Dockerfile
FROM bitnami/jenkins:latest

# Change user to root, install additional packages then switch back to 1001
USER 0
RUN install_packages ...
USER 1001
```
