### ISSUE TITLE
Unable to redirect wildfly Administration Console

### ISSUE THREAD

**Issue by ruwan1235** [bitnami/charts#6716]
**Which chart**:
using Bitnami/wildfly

**Is your feature request related to a problem? Please describe.**
I Need access wildfly Administration Console dashboard.

I already successfully deploy wildfly service using helm chart.(Used wildlfly/bitnami helm chart)  But i cant access Administration Console dashboard. I already mount bitnami/wildfly location.  
![Screenshot from 2021-06-21 13-42-36](https://user-images.githubusercontent.com/86238699/122762233-b9ed0380-d2ba-11eb-80e5-d76dd6cbcfa1.png)

**Comment by rafariossaa** [comment]
Hi, 
  Could you indicate which url are you using to access the console ?
  The url is shown in the instructions returned by the `helm install` command:

```
...
1. Get the WildFly URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w mywildfly'

  export SERVICE_IP=$(kubectl get svc --namespace default mywildfly --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "WildFly URL:            http://$SERVICE_IP/
  echo "WildFly Management URL: http://$SERVICE_IP:443/

...
```

**Comment by chirathb** [comment]
[vm1@vm1 wildfly]$ helm install wf .
NAME: wf
LAST DEPLOYED: Mon Jun 21 12:14:59 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

1. Get the WildFly URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w wf-wildfly'

  export SERVICE_IP=$(kubectl get svc --namespace default wf-wildfly --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "WildFly URL:            http://$SERVICE_IP/
  echo "WildFly Management URL: http://$SERVICE_IP:443/

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace default wf-wildfly -o jsonpath="{.data.wildfly-password}" | base64 --decode)

**Comment by chirathb** [comment]
[vm1@vm1 wildfly]$ helm install wf .
NAME: wf
LAST DEPLOYED: Mon Jun 21 12:14:59 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

1. Get the WildFly URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w wf-wildfly'

  export SERVICE_IP=$(kubectl get svc --namespace default wf-wildfly --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "WildFly URL:            http://$SERVICE_IP/
  echo "WildFly Management URL: http://$SERVICE_IP:443/

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace default wf-wildfly -o jsonpath="{.data.wildfly-password}" | base64 --decode)

**Comment by ruwan1235** [comment]
[vm1@vm1 wildfly]$ helm install wf .
NAME: wf
LAST DEPLOYED: Mon Jun 21 12:14:59 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

1. Get the WildFly URL by running:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w wf-wildfly'

  export SERVICE_IP=$(kubectl get svc --namespace default wf-wildfly --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "WildFly URL:            http://$SERVICE_IP/
  echo "WildFly Management URL: http://$SERVICE_IP:443/

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace default wf-wildfly -o jsonpath="{.data.wildfly-password}" | base64 --decode)

**Comment by ruwan1235** [comment]
anyone have solution for this issue

**Comment by rafariossaa** [comment]
Hi,
  Could you try the new chart version ?
