### ISSUE TITLE
[bitnami/owncloud] the name of the existingSecret is ignored in the deployment template

### ISSUE THREAD

**Issue by cyrilcros** [bitnami/charts#6719]
**Which chart**:
Owncloud v10.2.13

**Describe the bug**

The `existingSecret` is not respected for `OWNCLOUD_SMTP_PASSWORD` and `OWNCLOUD_PASSWORD`,  the charts looks instead for the secret `bitnami-owncloud`.
https://github.com/bitnami/charts/blob/6d1999e327fe9e1c1aaf0251d2dda13c192a3beb/bitnami/owncloud/templates/deployment.yaml#L130

**To Reproduce**

1. Use the `existingSecret` parameter and do not have a `bitnami-owncloud` secret in your namespace
2. There is a `CreateContainerConfigError`

**Expected behavior**
The deployment template gets the password secrets from `.Values.existingSecret` when it exists.

**To correct**
The `deployment.yaml` should use around lines 130/140 a conditional: if `existingSecret` exists then grab values from it, otherwise use the `bitnami-owncloud` secret

**Version of Helm and Kubernetes**:

- Output of `kubectl version`: 1.21.1

**Comment by migruiz4** [comment]
Thank you very much for reporting this issue @cyrilcros!

I have created this PR #6721 that should fix the problem.
Let me know if it works for you.
