### ISSUE TITLE
NetworkPolicy for mysql

### ISSUE THREAD

**Issue by bynare** [bitnami/charts#6720]
**Which chart**:
mysql

**Describe the solution you'd like**
Similar to the [postgresql chart's](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/networkpolicy.yaml), would it be possible to implement a policy for this chart too?

Let me know, as I'm happy to attempt creating a merge request ;)

Thanks!

**Comment by alvneiayu** [comment]
hi @bynare 

I think that it is a really good idea. We are opened to receive PRs and I will be really to review it.

Thanks a lot for the proposal

Álvaro
