### ISSUE TITLE
[bitnami/harbor] Ingress is wrong for harbor 2.3.0+

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#6723]
**Which chart**:
harbor 10.1.1 (i think older versions are failing too)

**Describe the bug**
Harbor v2.3.0+ is using a new `common.xxxxx.js` file, which is catched by wrong ingres rule:
https://github.com/bitnami/charts/blob/25585c7a042c48ad4b1e8a877c9c3d9b7db6228f/bitnami/harbor/templates/ingress/ingress.yaml#L22
https://github.com/bitnami/charts/blob/25585c7a042c48ad4b1e8a877c9c3d9b7db6228f/bitnami/harbor/templates/ingress/ingress.yaml#L91

**To Reproduce**
Can currently not reproduced, because the new v2.3.0 images of bitnami for harbor are not yet available.

**Expected behavior**
Should work, see goharbor/harbor#14495 and goharbor/harbor-helm#873

**Version of Helm and Kubernetes**: 

- Output of `helm version`: 

```
doesn't matter
```

- Output of `kubectl version`:

```
doesn't matter
```

**Additional context**

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the heads up. It will be very useful for the team that is working on the new version. As you detected the issue, would you like to submit a PR with the change?

**Comment by viceice** [comment]
Sure, maybe later today.

**Comment by viceice** [comment]
#6767 🎉

**Comment by javsalgar** [comment]
Thank you so much!!
