### ISSUE TITLE
Frequent restarts

### ISSUE THREAD

**Issue by CoMaDaniel** [bitnami/charts#6729]
**Which chart**:
Mongodb 

**Describe the bug**
Hello. I'm trying to use the MongoDB chart together with Graylog. It all went well for a couple of days, with the default values, but then my machine started hanging because of high MongoDB resource consumption (with nothing using Graylog or Mongo). My solution was to reinstall the MongoDB chart specifying the limits. 
Now, the Mongo pod has a lot of frequent restarts, my guess is that it's reaching the limits and K8s is thus restarting it. This causes downtime for Graylog as well.
Is this normal behavior, or is there any other configuration I need to do?
I have some machines with limited resources, so giving Mongo the default limit consumption is not an option.

**To Reproduce**

1. Install chart using helm:
    helm upgrade --install mongodb bitnami/mongodb  --set architecture=replicaset --set persistence.storageClass=nfs-client --set persistence.size=2Gi --set replicaCount=1 --set resources.limits.cpu=100m --set resources.limits.memory=128Mi --set resources.requests.cpu=100m --set resources.requests.memory=128Mi 
2. In a couple of days I have over 30 restarts; we are not even using graylog at this point, it's just the idle behaviour

**Expected behavior**
Pod does not have such frequent restarts

**Version of Helm and Kubernetes**:

- Output of `helm version`:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

Thanks!

**Comment by miguelaeh** [comment]
Hi @CoMaDaniel ,
This does not seem to be an issue with the chart. If your machines have limited resources you would need to set them according to what your machines can support instead of the default values. There is not too much we can do here
