### ISSUE TITLE
[bitnami/airflow] Helm deploy fails if  worker.image.tag is a numeric string

### ISSUE THREAD

**Issue by dontspamterry** [bitnami/charts#6731]
**Which chart**:
bitnami/airflow 10.2.1

**Describe the bug**
I extended the `bitnami/airflow-worker` image to pre-install additional Python libraries and generated a Docker image with a shortened Git commit hash. This particular hash just happened to have only numeric characters. When I override the worker image config with my custom image and use this numeric-char hash, I received the following error when deploying:

```
.....
v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 6, error found in #10 byte of ...|,"value":67761135},{|..., bigger context ...|RFLOW__KUBERNETES__WORKER_CONTAINER_TAG","value":67761135},
.....
``` 

Looks like the value in this [line](https://github.com/bitnami/charts/blob/58197c00e2c552a96e332fa5825d4ee75a5b3474/bitnami/airflow/templates/_helpers.tpl#L318) needs to be wrapped in quotes when setting the `AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG` env var on the worker pod.

**To Reproduce**

1. In a values.yaml override, specify
    ```
    worker:
      image:
        tag: "67761135"
    ``` 
2. Deploy the helm chart and you will see the error reported above.

**Expected behavior**
The deploy should go through regardless if the tag contains just numeric characters as the tag value needs to be treated as a string.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
The image tag was sourced from the `CI_COMMIT_SHORT_SHA` property of Gitlab

**Comment by alemorcuq** [comment]
Hi, @dontspamterry.

I'm not able to reproduce your issue. Here's what I did:

1. I created a `my.yaml` file with the following contents:

```
$ cat my.yaml
worker:
  image:
    tag: "67761135"
```

2. I installed the chart using that values file:

```
$ helm install af bitnami/airflow -f my.yaml
NAME: af
LAST DEPLOYED: Wed Jun 23 10:19:46 2021
NAMESPACE: amoreno
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the Airflow URL by running:

  echo URL  : http://127.0.0.1:8080
  kubectl port-forward --namespace amoreno svc/af-airflow 8080:8080

2. Get your Airflow login credentials by running:
  export AIRFLOW_PASSWORD=$(kubectl get secret --namespace "amoreno" af-airflow -o jsonpath="{.data.airflow-password}" | base64 --decode)
  echo User:     user
  echo Password: $AIRFLOW_PASSWORD



WARNING: Rolling tag detected (bitnami/airflow-worker:67761135), please note that it is strongly recommended to avoid using rolling tags in a production environment.
+info https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/
```

As you can see, I got no errors.

In any case, can you test locally the change in the line you mentioned? Just make it look like this:

```
  value: {{ .Values.worker.image.tag | quote }}
```

**Comment by dontspamterry** [comment]
Hi @alemorcuq ,

Thanks for testing. I'll try to test your proposed change locally when I get some time. Will try to report back soon!

Thanks again!
