### ISSUE TITLE
bitnami/kafka helm external access via OpenShift Route

### ISSUE THREAD

**Issue by cdattnecindia** [bitnami/charts#6735]
How we can access externally helm bitnami/kafka in OpenShift Environment. 
Accessing it via Load Balancer IP Address is already tested But the one of the Project needed to access Kafka externally via It's Route in OpenShift Environment.

**Comment by alvneiayu** [comment]
hi @cdattnecindia 

Sorry, I don't understand your question. Are you having problem to access to the Kafka with that it is already exposed? or are you installed the Kafka in a Openshift environment and you want to know how to expose the chart?

https://docs.openshift.com/container-platform/3.3/dev_guide/getting_traffic_into_cluster.html

I am not expert in Openshift. I found this guide explaining how to expose a cluster in Openshift. Maybe it can help you. Let me know if I can help you with something.

Sorry again and thanks

Álvaro

**Comment by cdattnecindia** [comment]
Thank You @alvaro for your valuable comments.

Basically if I am assigning any Public IP to its External/LB IP, we are able to access kafka from outside of the cluster, externally. 

But the issue is when we are creating any Route for the Kafka Service then we are not able to access Kafka service from outside of the cluster.

I already raised a Case for the same on RedHat OpenShift, But they also suggesting they need to know from bitnami/kafka side that how they can integrate Bitnami/Kafka with OpenShift for accessing it from outside through its Route only.

$ oc get svc -n kafka
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kafka                ClusterIP   172.30.117.19   <none>        9092/TCP                     5d16h
kafka-headless       ClusterIP   None            <none>        9092/TCP,9093/TCP            5d16h
zookeeper            ClusterIP   172.30.5.192    <none>        2181/TCP,2888/TCP,3888/TCP   5d18h
zookeeper-headless   ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   5d18h
2021-06-23 04:08:13 ~
$
2021-06-23 04:08:14 ~

$ oc get route -n kafka
NAME                        HOST/PORT                                                        PATH   SERVICES    PORT   TERMINATION   WILDCARD
kafka                       kafka-kafka.apps.ocpdev01-aramco.necdp.com                              kafka       9092   edge          None
route-passthrough-secured   route-passthrough-secured-kafka.apps.ocpdev01-aramco.necdp.com          kafka       9092   passthrough   None
zookeeperext                zookeeperext-kafka.apps.ocpdev01-aramco.necdp.com                       zookeeper   2181   edge          None
zookeeperext1               zookeeperext1-kafka.apps.ocpdev01-aramco.necdp.com                      zookeeper   2181   passthrough   None
zookeeperinternal1          zookeeperinternal1-kafka.apps.ocpdev01-aramco.necdp.com                 zookeeper   2181   edge/Allow    None
2021-06-23 04:08:21 ~
 
Regards,
Chandra

**Comment by alvneiayu** [comment]
hi @cdattnecindia 

It seems that the OpenShift Route are like an Ingress (correct me if I am wrong) and I think that you can not use just a Route. Kafka needs an access point for each replica and the Kafka client must know all the endpoints ([here more info](https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster)). You can not use just an Openshift Route and I think that this is your problem (but this is an impression, I am not expert in OpenShift). I am going to investigate also a little bit in my side.

Thanks a lot

Álvaro

**Comment by cdattnecindia** [comment]
Hi @alvneiayu,

Thanks for your suggestion, currently we are able to access kafka from outside from OpenShift cluster by using NodePort configuration.

--set externalAccess.enabled=true
--set externalAccess.service.type=NodePort  
--set externalAccess.service.domain='X.X.X.X'
--set externalAccess.service.nodePorts[0]='nodeport'
--set externalAccess.service.nodePorts[1]='nodeport'
--set externalAccess.service.nodePorts[2]='nodeport'

**Comment by alvneiayu** [comment]
hi @cdattnecindia 

Good to hear that. Thanks a lot for sharing your solution

Thanks again

Álvaro
