### ISSUE TITLE
[bitnami/external-dns] deployment with azure-private-dns leads to CreateContainerConfigError with chart-version 5.1.1

### ISSUE THREAD

**Issue by PatrickSpies** [bitnami/charts#6738]
**Which chart**:
bitnami/external-dns 5.1.1

**Describe the bug**
Deployment with provider azure-private-dns stucks in `CreateContainerConfigError` with message `Error: couldn't find key azure_aad_client_secret in Secret external-dns/external-dns`.

**To Reproduce**
Deploy external-dns 5.1.1 with following values:
```yaml
provider: azure-private-dns
azure:
  subscriptionId: "someSubscriontId"
  resourceGroup: "someResourceGroup"
  tenantId: "someTenantId"
  aadClientId: "someClientId"
  aadClientSecret: "someClientSecret"
```

Pod stucks with `CreateContainerConfigError` and message `Error: couldn't find key azure_aad_client_secret in Secret external-dns/external-dns`.

Secret contains only one key `azure.json`.

**Expected behavior**
Pod gets deployed successful.
Either secret has to contain missing keys or deployment does not need those env-vars.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
`bitnami/external-dns/templates/deployment.yaml` defines env-vars `AZURE_CLIENT_SECRET` and `AZURE_CLIENT_ID` from secret (keys `azure_aad_client_secret` and `azure_aad_client_id`), but with commit https://github.com/bitnami/charts/commit/16598faadab4ed555402fcc24ebe4fe185b82fc4#diff-ca5a996701c8f8c6fe904120752cead45b3c4820e48e597566781b4c5f2501d1 the creation of those keys was deleted from `bitnami/external-dns/templates/secret.yaml`.

Manually removing both env-vars fixes the deployment

**Comment by pablogalegoc** [comment]
Hi @PatrickSpies!

Thank you for flagging this issue, we'll open a PR to address it.
