### ISSUE TITLE
Openshift Client Jenkins plugin usage error on Bitmani/jenkins provisioned through helm chart

### ISSUE THREAD

**Issue by vaddepalli2** [bitnami/charts#6752]
**Which chart**:
bitnami/jenkins tag: 2.289.1-debian-10-r0

**Describe the bug**
While trying to execute a Pipeline using bitnami/jenkins instance with version tag: 2.289.1-debian-10-r0 by leveraging the OpenShift Client Jenkins Plugin v1.0.35. I am getting an error below. Need your assistance in resolving this issue.

FATAL: Cannot run program “oc”: error=2, No such file or directory
java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

**To Reproduce**

1. Go to 'jenkins instance'
2. Click on 'create job '
3. In general tab, Build step use openshift generic oc invocation 
4. give the details of cluster and key 
5. In script running get pods 

**Expected behavior**
Have to list all the pods that are in the cluster 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(version.BuildInfo{Version:"v3.5.2",)
```

- Output of `kubectl version`:

```
(Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.19+IKS", GitCommit:"ca41a6aa2f321ddfba985b3aeb43693371964571", GitTreeState:"clean", BuildDate:"2021-05-14T22:53:20Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"})
```

**Additional context**

**Comment by migruiz4** [comment]
Hi @vaddepalli2,

According to the Openshift Client plugin for Jenkins:
> Before running a job, you may also need to ensure your Jenkins nodes have the 'oc' binary installed. And for Linux users, there can be some additional requirements for running 'oc' based on which Linux distribution you are using.

Ref: https://github.com/openshift/jenkins-client-plugin#installing-and-developing

Looks like installing the Openshift CLI tool is a pre-requirement for the plugin. You can find instructions for how to install the 'oc' binary here: https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-on-linux_cli-developer-commands

The Bitnami Jenkins image does not include the Openshift CLI tool, so you may need to either build your custom image, mount the 'oc' binary using `extraVolumes` or use a custom entrypoint.

Additionally, you may need the binary to be in your container $PATH.
