### ISSUE TITLE
Helm InfluxDB - backup pod ignores nodeSelectors

### ISSUE THREAD

**Issue by bartlomiejwulff** [bitnami/charts#6765]
Hi there guys,

unfortunately the pod triggered by [cronjob-backup.yam](https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml) ignores the nodeSelectors defined inside values.yaml.

**Comment by Mauraza** [comment]
Hi @bartlomiejwulff,

I am sorry to hear this. 
I will do some testing and will update the thread when I know more.

**Comment by bartlomiejwulff** [comment]
> Hi @bartlomiejwulff,
> 
> I am sorry to hear this.
> I will do some testing and will update the thread when I know more.

Hi @Mauraza 

thx. I have created a PR, ready to review. Please have a look on this.

Thanks!

**Comment by Mauraza** [comment]
Hi @bartlomiejwulff,

Thanks for the contribution!!
