### ISSUE TITLE
Contour helm chart does not work when creating an internal and external ingress

### ISSUE THREAD

**Issue by itustanic** [bitnami/charts#6773]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/contour

**Describe the bug**
I am trying to create an external and internal ingress controller using the contour helm chart using 2 resources and terraform. However, when I run `terraform plan`, what happens is that the internal controller gets created, however this happens next:

` Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "extensionservices.projectcontour.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "contour-external": current value is "contour-internal"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "contour-external": current value is "contour-internal"`

It seems that I can not have 2 resources using the same CustomResourceDefinition, since the names conflict. 

I'm not sure how to fix this.

**To Reproduce**

Create 2 contour resources, external and internal. Run plan, the conflict occurs.

**Expected behavior**

Both external and internal resources should work.

**Version of Helm and Kubernetes**:

Latest

- Output of `kubectl version`:

Latest

**Comment by carrodher** [comment]
If the error is the same as posted above it seems there is an already existing resource in the cluster from a previous deployment: `...rendered manifests contain a resource that already exists...`

Can you clean up the resources from previous installations? Specifically the CRDs, in the same way, it can be useful to deploy the chart in a specific namespace and remove it between deployments (if it's possible in your use case)
