### ISSUE TITLE
Kafka - Datadog intergrations issues

### ISSUE THREAD

**Issue by asaf-upstream** [bitnami/charts#6775]
**chart**:
kafka - 12.9.0

**Describe the bug**
I suspect the DD-Kafka integration is not working using the chart.
Tried to use the following guide:
https://docs.datadoghq.com/agent/guide/autodiscovery-with-jmx/?tab=containeragent

WIthout success.
We run the kafka chart on 'kafka' namespace, and DD chart on 'monitoring'.

Tried to add the following podAnnotations:
      ad.datadoghq.com/jmx-exporter.check_names: '["kafka"]'
      ad.datadoghq.com/jmx-exporter.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
      ad.datadoghq.com/jmx-exporter.instances: '[{"host": "%%host%%","port":"5556","namespace":"kafka"}]'
      ad.datadoghq.com/kafka.logs: '[{"source":"kafka","service":"kafka"}]'

      ad.datadoghq.com/kafka.check_names: '["kafka"]'
      ad.datadoghq.com/kafka.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
      ad.datadoghq.com/kafka.instances: '[{"host": "%%host%%","port":"5556","namespace":"kafka"}]'
      ad.datadoghq.com/kafka.logs: '[{"source":"kafka","service":"kafka"}]'

      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: JAVA_OPTS
        value: >-
          -Dcom.sun.management.jmxremote
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.ssl=false
          -Dcom.sun.management.jmxremote.local.only=false
          -Dcom.sun.management.jmxremote.port=5556
          -Dcom.sun.management.jmxremote.rmi.port=5556
          -Djava.rmi.server.hostname=$(POD_IP) \ 0.0.0.0\ 127.0.0.1

Output of the DD agent proves no data is collected:
========
JMXFetch
========

  Information
  ==================
  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

If I use 'kubectl port-forward' on the kafka pod, I can see the metrics on jconsole.

**Expected behavior**
Monitoring on DD should be presented.

- Output of `helm version`:
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}

- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by migruiz4** [comment]
Hi @asaf-upstream,

Setting up the Datadog Kafka integration would be out of my scope, but I will try to help you.

To expose JMX metrics, try adding the following extraEnvVars:
```
extraEnvVars:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: JMX_PORT
    value: "5556"
  - name: KAFKA_JMX_OPTS
    value: >-
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.port=5556
      -Dcom.sun.management.jmxremote.rmi.port=5556
      -Djava.rmi.server.hostname=$(POD_IP)
```

With that, you should have your Kafka pod exposing JMX metrics at port 5556 as described in the documentation link you shared.

Let me know if it helps.

**Comment by asaf-upstream** [comment]
hi @migruiz4 , thx a lot for trying to help!!

I have done what you have asked, and now I am getting:
 k logs kafka-0 -c kafka
 13:09:59.04
 13:09:59.04 Welcome to the Bitnami kafka container
 13:09:59.04 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
 13:09:59.04 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
 13:09:59.04
 13:09:59.04 INFO  ==> ** Starting Kafka setup **
 13:09:59.08 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
 13:09:59.09 INFO  ==> Initializing Kafka...
 13:09:59.09 INFO  ==> No injected configuration files found, creating default config files
 13:09:59.25 INFO  ==> Configuring Kafka for inter-broker communications with PLAINTEXT authentication.
 13:09:59.25 WARN  ==> Inter-broker communications are configured as PLAINTEXT. This is not safe for production environments.
 13:09:59.25 INFO  ==> Configuring Kafka for client communications with PLAINTEXT authentication.
 13:09:59.26 WARN  ==> Client communications are configured using PLAINTEXT listeners. For safety reasons, do not use this in a production environment.
 13:09:59.26 INFO  ==> ** Kafka setup finished! **

 13:09:59.27 INFO  ==> ** Starting Kafka **
Error: JMX connector server communication error: service:jmx:rmi://kafka-0:5556
jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 5556; nested exception is:
	java.net.BindException: Address already in use (Bind failed)
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:820)
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:479)
	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
Caused by: java.rmi.server.ExportException: Port already in use: 5556; nested exception is:
	java.net.BindException: Address already in use (Bind failed)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
	at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234)
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap$PermanentExporter.exportObject(ConnectorBootstrap.java:203)
	at java.management.rmi/javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:153)
	at java.management.rmi/javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:138)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:473)
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:816)
	... 3 more

Again not sure what I miss here... the jmx-exporter container is starting successfully:
k describe pod kafka-0
 jmx-exporter:
    Container ID:  docker://b1d56de07781d550a7f6aac80befcb6b5a6587166a4a0eb14f736f6c6c335315
    Image:         docker.io/bitnami/jmx-exporter:0.15.0-debian-10-r1
    Image ID:      docker-pullable://bitnami/jmx-exporter@sha256:cd553daa4ac6e9ff958664e7b93b84f9089a9e54c4485408dbd09565213288df
    Port:          5556/TCP
    Host Port:     0/TCP
    Command:
      java
      -XX:+UnlockExperimentalVMOptions
      -XX:+UseCGroupMemoryLimitForHeap
      -XX:MaxRAMFraction=1
      -XshowSettings:vm
      -jar
      jmx_prometheus_httpserver.jar
      5556
      /etc/jmx-kafka/jmx-kafka-prometheus.yml
    State:          Running

Why do I get this biding error? shouldn't the Kafka container connect to the jmx-export one?

**Comment by migruiz4** [comment]
Hi @asaf-upstream,

I'm sorry, I thought you were trying to configure the Datadog integration alone, not both the Datadog integration AND the Kafka JMX prometheus exporter.

If you want to use both simultaneously, change the Kafka JMX port to 5555:  
```yaml
extraEnvVars:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: JMX_PORT
    value: "5555"
  - name: KAFKA_JMX_OPTS
    value: >-
      -Dcom.sun.management.jmxremote
      -Dcom.sun.management.jmxremote.authenticate=false
      -Dcom.sun.management.jmxremote.ssl=false
      -Dcom.sun.management.jmxremote.local.only=false
      -Dcom.sun.management.jmxremote.port=5555
      -Dcom.sun.management.jmxremote.rmi.port=5555
      -Djava.rmi.server.hostname=$(POD_IP)
```

And don't forget to also update the JMX port in the podAnnotations accordingly:
```
ad.datadoghq.com/jmx-exporter.check_names: '["kafka"]'
ad.datadoghq.com/jmx-exporter.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
ad.datadoghq.com/jmx-exporter.instances: '[{"host": "%%host%%","port":"5555","namespace":"kafka"}]'
ad.datadoghq.com/kafka.logs: '[{"source":"kafka","service":"kafka"}]'
```

The Kafka JMX exporter for Prometheus (`metrics.jmx.enabled=true`) collects metrics from port 5555 and exposes them at port 5556. That is why you were getting the binding error when trying to configure Kafja JMX at 5556.

They both are different services and need a different port.

**Comment by asaf-upstream** [comment]
Hi @migruiz4 ,
sadly this is still no go...

No matter what, seems that the auto-discovery of DD is not working:
========
JMXFetch
========

  Information
  ==================
  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

Could there be anything else?
Also, what do you mean by "Datadog integration alone" ? 
All we need is metrics of the Kafka brokers, isn't it a must to get it from the Kafka JMX prometheus exporter?

**Comment by migruiz4** [comment]
I'm sorry but I think there has been some misunderstanding here.

The Bitnami Kafka Helm charts provides two different methods to export metrics:
- Using kafka_exporter (https://github.com/danielqsj/kafka_exporter), enabled with the value `metrics.kafka.enabled`. Will create a deployment and a service (your-release-kafka-metrics), to serve metrics via HTTP at port 9308.
- Using jmx-exporter (https://github.com/prometheus/jmx_exporter), enabled with the value `metrics.jmx.enabled` + extraEnvVar KAFKA_JMX_OPTS (from my previous comment). Configures Kafka containers to export JMX raw metrics (port 5555) and a sidecar container collecting them and serving them for Prometheus consumption at port 5556. Also creates the service your-release-kafka-jmx-metrics.

The DataDog integration is only required if you'd like to monitor your data using Datadog instead of Prometheus.

**Comment by migruiz4** [comment]
Expected output of the JMX exporter should look like this:
```bash
$ curl localhost:5556
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.15.0",name="jmx_prometheus_httpserver",} 1.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP kafka_server_brokertopicmetrics_total_invalidoffsetorsequencerecordspersec_count Attribute exposed for management (kafka.server<type=BrokerTopicMetrics, name=InvalidOffsetOrSequenceRecordsPerSec><>Count)
# TYPE kafka_server_brokertopicmetrics_total_invalidoffsetorsequencerecordspersec_count untyped
kafka_server_brokertopicmetrics_total_invalidoffsetorsequencerecordspersec_count 0.0
# HELP kafka_server_replicamanager_total_underreplicatedpartitions_value Attribute exposed for management (kafka.server<type=ReplicaManager, name=UnderReplicatedPartitions><>Value)
# TYPE kafka_server_replicamanager_total_underreplicatedpartitions_value untyped
kafka_server_replicamanager_total_underreplicatedpartitions_value 0.0
# HELP kafka_server_fetchsessioncache_total_numincrementalfetchpartitionscached_value Attribute exposed for management (kafka.server<type=FetchSessionCache, name=NumIncrementalFetchPartitionsCached><>Value)
# TYPE kafka_server_fetchsessioncache_total_numincrementalfetchpartitionscached_value untyped
kafka_server_fetchsessioncache_total_numincrementalfetchpartitionscached_value 0.0
...
```

**Comment by asaf-upstream** [comment]
Hi @migruiz4 ,
Many thanks for this, I think you are correct and I have made a mess with the JMX and Prometheus.
We only need the DataDog integration, therefore no need for both JMX options that eventually Prometheus pulls the data from.

Guess I need to take it with DataDog, as there auto-discovery service seems not to work.
Many thanks for your input, please let me know if you think I have missed something, otherwise I will close this.
Thanks again!

**Comment by migruiz4** [comment]
You are welcome @asaf-upstream!

If you have any further questions let us know.

**Comment by karthikeayan** [comment]
@asaf-upstream I am running into the same problem, were you able to successfully integrate Kafka with Datadog?

**Comment by asaf-upstream** [comment]
Hi @karthikeayan , we ended up adding these annotations:
```
podAnnotations:
     ad.datadoghq.com/jmx-exporter.check_names: '["kafka"]'
     ad.datadoghq.com/jmx-exporter.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
     ad.datadoghq.com/jmx-exporter.instances: '[{"host": "%%host%%","port":"5555"}]'
```
Also added these extraEnvVars:
```
extraEnvVars:
     - name: POD_IP
       valueFrom:
         fieldRef:
           fieldPath: status.podIP
     - name: KAFKA_JMX_OPTS
       value: >-
         -Dcom.sun.management.jmxremote
         -Dcom.sun.management.jmxremote.authenticate=false
         -Dcom.sun.management.jmxremote.ssl=false
         -Dcom.sun.management.jmxremote.local.only=false
         -Dcom.sun.management.jmxremote.port=5555
         -Dcom.sun.management.jmxremote.rmi.port=5555
         -Djava.rmi.server.hostname=$(POD_IP)
     - name: JMX_PORT
       value: "5555"
```
Once both configured, we could see Kafka data in our DD dash.
Hope this helps.
