### ISSUE TITLE
[bitnami/redis] I restart redis node-0 failed when the sentinal is enabled

### ISSUE THREAD

**Issue by liyuanjob** [bitnami/charts#6777]
1,node-0 is master and restart failed, the pod keeps restarting.
2,node-1 and node-2 get slave number is zero.
3, the master can not failover to slave

**Comment by pablogalegoc** [comment]
Hi @liyuanjob!

See if #6165 is the same problem you are facing. If that's the case here is what we used to mitigate the issue:
https://github.com/bitnami/charts/issues/6165#issuecomment-852905670

**Comment by liyuanjob** [comment]
Thanks @pablogalegoc , This temporary solution is very useful. Hope this issue can be completely resolved.
