### ISSUE TITLE
[bitnami/kube-prometheus] Readiness probe and liveness probe fail when setting routePrefix

### ISSUE THREAD

**Issue by ecureuil** [bitnami/charts#6780]
**Which chart**:
kube-prometheus

**Describe the bug**
When setting a value for routePrefix, such as /prometheus1, the readiness probe and liveness probes use a path without routePrefix and fail. It is not possible to configure the probe paths, since the values are hardcoded in the chart template.

**To Reproduce**

1. Set routePrefix with /prometheus1
2. Set livenessProbe.enabled: true and readinessProbe.enabled: true
4. The pod fails to reach the running state cause the probes.

**Expected behavior**
At least, It should be possible to change the probe paths.
Better the probe paths is inferred with the routePath.

**Version of Helm and Kubernetes**:

```
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
None

**Comment by juan131** [comment]
Hi @ecureuil 

Thanks so much for reporting this issue and submitting a PR! I'll take a look to the PR and follow the conversation there.
