### ISSUE TITLE
[bitnami/common]

### ISSUE THREAD

**Issue by docktermj** [bitnami/charts#6785]
**Which chart**:
bitnami/common

**Is your feature request related to a problem? Please describe.**
Your bitnami/common is well thought out and useful.   As such I'd like to declare it as a dependency in my `Chart.yaml` file.   However, I already have a "common" package so the package names conflict, rendering the reuse of your wonderful asset unusable to me.

Hi have a great deal of respect for Bitnami and was wondering if you would support correcting the issue identified by @desaintmartin at https://github.com/helm/helm/issues/7413.  It is affecting my work, too.

I can't imagine asking you to rename your `common` directory, so the I would think that the appropriate move forward would to be to ask the folks at Helm to handle package name collision.

I'm not sure there's anything you can do,  but I thank you for considering this issue.

**Comment by alvneiayu** [comment]
hi @docktermj 

As you know, rename our common folder will generate a really big impact in our charts and also in our pipeline. This is a limitation in Helm and I think that the Helm developers should try to take a look this.

Thanks a lot for sharing with us the problem and I hope that you can finally find a good result on this.

Álvaro

**Comment by docktermj** [comment]
Hi @alvneiayu 

I appreciate that it would be a big change for you as for any consumer of Helm.  So as you point out, this is something that the good folks at Helm need to address for all of us.  Perhaps if you and the good folks at Bitnami could add :+1: to https://github.com/helm/helm/issues/7413 it might grab the attention of @bacongobbler

**Comment by alvneiayu** [comment]
hi @docktermj 

I did it. I hope that you can finally find a good result on this.

Thanks

Álvaro
