### ISSUE TITLE
arbitrary sidecar container in elasticsearch chart

### ISSUE THREAD

**Issue by antonmatsiuk** [bitnami/charts#6790]
**Which chart**:
bitnami/elasticsearch-15.6.0

**Is your feature request related to a problem? Please describe.**
To forward extended elasticsearch logs (slowlog, gc, depreation audit logs) outside the elasticsearch container via `filebeat` to a monitoring system a sidecar container is needed. `filebeat` sidecar container can forward elasticsearch logs to monitoring ELK stack as described here: https://www.elastic.co/guide/en/beats/filebeat/7.12/filebeat-module-elasticsearch.html

**Describe the solution you'd like**
Elasticsearch helm chart needs to have an arbitrary sidecar container feature as other helm charts (e.g. kibana, mysql) currently do. This side container can be used to run filebeat service which will forward elasticsearch logs located (by default) under `/opt/bitnami/elasticsearch/logs/` to a separate index in the same elasticsearch cluster or to a separate monitoring ELK stack

**Describe alternatives you've considered**
Forwarding elasticsearch slowlog to stdout/stderr of the main container. The option is not preferable as log streams mix together and become messy. 

**Additional context**
mysql or kibana charts may be used as a template

**Comment by juan131** [comment]
Thanks for the feedback @antonmatisuk

I just created a PR to address the missing feature.
