### ISSUE TITLE
[bitnami/redis] Unable to configure custom scripts for the metrics sidecar container

### ISSUE THREAD

**Issue by 0xDEC0DE** [bitnami/charts#6792]
**Which chart**:
```
name: redis
version: 14.4.0
```
**Is your feature request related to a problem? Please describe.**
If one configured a Redis deployment with `metrics.enabled: true`, it is possible to run a custom Lua script in the sidecar container via the `metrics.extraArgs.script` parameter.  This is part of the documented behavior. 

However, if a user configures this and sets the value to a script that does not exist in the container, the container crashes at startup and the pod does not start.  This can easily be hand-waved away under "don't do that, then", but there is no mechanism in the chart to get a volume mounted in the sidecar container, so that the script can be deployed with the chart.

**Describe the solution you'd like**
In a perfect world, one would be able to define the custom script in the chart via YAML here-doc, and the chart would "just handle" getting it installed in a mounted volume in the sidecar container.

A less-than-perfect-yet-still-acceptable solution would involve the chart being able to pass volumes down into the metrics sidecar, whereby operators could set them up via `extraVolumes`/`extraVolumeMounts` parameters.

**Describe alternatives you've considered**
A seemingly straightforward workaround to this is to maintain a private docker registry with a modified `redis-exporter` container image that contains the custom script, and configure that image via the `metrics.image.tag` parameter.  However, doing this correctly requires an additional source code repository and Docker registry to maintain the image assets, as well as requiring modifications to be coordinated among all three for deployments; I would argue that its straightforwardness is illusory.

**Comment by marcosbc** [comment]
Hi @0xDEC0DE, the most feasible implementation I can see is by using `extraVolumes`/`extraVolumeMounts`. However, in the current chart, the `metrics` container is not using `extraVolumeMounts` so it doesn't currently work, right?

If so, I don't see any red flag for mounting those volumes into the metrics service. What do you think? If you agree, feel free to contribute with a PR.

**Comment by 0xDEC0DE** [comment]
> If so, I don't see any red flag for mounting those volumes into the metrics service. What do you think? If you agree, feel free to contribute with a PR.

As you wish:

https://github.com/bitnami/charts/pull/6806

**Comment by marcosbc** [comment]
Hi @0xDEC0DE, it seems like we requested changes in #6808 but didn't get any response back. Could you look into them?
