### ISSUE TITLE
External DB SSL?

### ISSUE THREAD

**Issue by kirkre** [bitnami/charts#6795]
**Which chart**:
bitnami/drupal

**Is your feature request related to a problem? Please describe.**
No option to set client certificate for external db ssl

**Describe the solution you'd like**
An option to add a client certificate and key for external db authentication

Is there no way to specify a client certificate and key to connect to an external db? 

Thanks,

Kirk

**Comment by miguelaeh** [comment]
Hi @kirkre ,
It seems the env var to configure it is not available in the Helm Chart. In the container, we have `MYSQL_CLIENT_ENABLE_SSL` which should configure the database connection using SSL.
Would you like to create a PR adding that to the Helm Chart?

**Comment by kirkre** [comment]
Thanks miguelaeh. Just getting back to this and forgot to check up on this until now. Let me give this a try and if I can get it working I'll create a PR.

**Comment by alvneiayu** [comment]
thanks @kirkre
