### ISSUE TITLE
[bitnami/mongodb] generated certs should be valid for clients from different namespace

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#6798]
**Which chart**:

bitnami/mongodb (10.20.5)

**Is your feature request related to a problem? Please describe.**

Current SANs are only valid if client is in the same namespace

https://github.com/bitnami/charts/blob/f17a8030703d221ab207c19c2d8d645f2058f73a/bitnami/mongodb/templates/standalone/dep-sts.yaml#L141-L146

Connecting from a different namespace, the cert validation will fail as the hostname does not match the SANs

e.g. mongodb://mongodb-headless.ns-db:27017/admin?tls=true

**Describe the solution you'd like**

Generated cert should include following SANs:
* $svc.$MY_POD_NAMESPACE
* $svc.$MY_POD_NAMESPACE.svc.cluster.local

**Describe alternatives you've considered**

Workaround: deploy client in same namespace as mongo server

**Additional context**

ClusterIP service should also be included in SANs, not just headless service so clients can also connect using
* mongodb
* mongodb.ns-db
* mongodb.ns-db.svc.cluster.local

Another option is expose a config to include extra SANs, so that custom external DNS can also be added.

**Comment by Mauraza** [comment]
Hi @tbnguyen1407,

It would be great to have this feature. We are open a PR.
I going to create an internal task to add this feature and we will update this thread when we have news.

**Comment by pbtrudel** [comment]
We are having this issue as well. Using a standalone deployment or a statefulset produces the same issue. If client services are in a different namespace, certificate SANs do not match and prevents connections. Our current workaround was to modify the helm templates to be able to specify our own SANs that match the service_name.namespace.

**Comment by Mauraza** [comment]
Hi @pbtrudel,

Thanks for sharing your workaround!

**Comment by alemorcuq** [comment]
#7627 added a `tls.extraDnsNames` to specify extra domain names, as suggested by @tbnguyen1407. Therefore, I'm closing this issue as solved.
