### ISSUE TITLE
[bitnami/influxdb] error converting YAML to JSON

### ISSUE THREAD

**Issue by bartlomiejwulff** [bitnami/charts#6802]
**Which chart**:
[bitnami/influxdb]

**Describe the bug**
Seems I've introduced an indentation error with my last PR.

**To Reproduce**
Install influxDB Chart incl. backup function

**Expected behavior**
-

**Version of Helm and Kubernetes**:

- Output of `helm version`: -

```
(paste your output here)
```

**Additional context**
Chart:
    Spec:
      Chart:     influxdb
      Interval:  1m
      Source Ref:
        Kind:       HelmRepository
        Name:       helm-bitnami
        Namespace:  default
      Version:      2.2.10

Conditions:
    Last Transition Time:  2021-06-30T03:41:15Z
    Message:               HelmChart 'schiff-tenant/influx-influxdb2' is not ready
    Reason:                ArtifactFailed
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-06-30T03:41:15Z
    Message:               Helm upgrade failed: YAML parse error on influxdb/templates/influxdb/cronjob-backup.yaml: error converting YAML to JSON: yaml: line 51: did not find expected '-' indicator

**Comment by alvneiayu** [comment]
hi @bartlomiejwulff 

I created a PR fixing the problem. Could you take a look, please? I tested in local and I think that everything is fixed now.

Thanks a lot

Álvaro

**Comment by bartlomiejwulff** [comment]
Hi @alvneiayu 

great PR, thanks!

**Comment by alvneiayu** [comment]
thanks @bartlomiejwulff. Waiting the review from my colleagues.
