### ISSUE TITLE
[bitnami/redis] Can't open the append-only file: Permission denied

### ISSUE THREAD

**Issue by rnkhouse** [bitnami/charts#6809]
**Which chart**:
redis-14.6.2

**Describe the bug**
I am trying to install helm chart using below command:

>helm install redis bitnami/redis --set global.redis.password=test123 --set auth.password=test123

And getting Can't open the append-only file: Permission denied in pod logs.

**Expected behavior**
It should install redis successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"ca992926ba9f76abd853859a64b5b04a1b562362", GitTreeState:"clean", BuildDate:"2021-05-19T22:29:12Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @rnkhouse ,
Could you please share the pod's log?

**Comment by rnkhouse** [comment]
@miguelaeh 

1:C 01 Jul 2021 13:48:32.325 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 01 Jul 2021 13:48:32.325 # Redis version=6.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 01 Jul 2021 13:48:32.325 # Configuration loaded
1:M 01 Jul 2021 13:48:32.326 * monotonic clock: POSIX clock_gettime
1:M 01 Jul 2021 13:48:32.326 # Can't open the append-only file: Permission denied

**Comment by miguelaeh** [comment]
Hi @rnkhouse ,
Which kind of cluster are you using? 
Could you give a try to setting `volumePermissions.enabled=true`?

**Comment by rnkhouse** [comment]
@miguelaeh It's working now. Thanks. But, in the old version of the chart, I wasn't setting this flag.
