### ISSUE TITLE
[bitnami/mongodb-sharded] mongos fails reconnect when configsvr-0 down

### ISSUE THREAD

**Issue by copelaje** [bitnami/charts#6810]
**Which chart**:
mongodb-sharded v3.7.0

**Describe the bug**
I’ve got a mongodb-sharded instance using the latest version of the helm chart (3.7). I’m configured with 5 configsvr replicas 4 mongos instances, each shard has 3 dataNode replicates and 2 arbiter aiming for resilliance to a 2 node failure scenario. Today I had a situation where the node hosting configsvr-0 of the stateful set was taken out of commission for a period of time (several hours). This instance was also the PRIMARY at the time of node failure. For some reason the configsvr instances did not fail over I’d have hoped (still investigating), and I had to manually connect in and update the rs.config() to remove this member and get another primary elected. That’s another issue I’m still in process of investigating, but I believe I’ve found a clear deficiency in the helm chart.

I found that mongos instances which restarted during this period got stuck in restart cycles. The fundamental problem seemed to be they were configured in /opt/bitnami/mongodb/conf/mongos.conf under sharding.configDB to only speak to configsvr-0 and ONLY that instance to bootstrap. From the mongo docs it seems that ideally all replicates would be configured there to be resilient to this kind of issue. The value in the conf file seems to originate from the setting of the MONGODB_CFG_PRIMARY_HOST environment variable which is populated by the helm chart but the various uses through the startup scripts prevent this from having multiple hosts listed.

Is there a recommended way to make the bitnami mongodb-sharded deployment resilient to node failure of configsvr-0?

**To Reproduce**

1. helm deploy with configsvr replicate set
2. kill configsvr-0 instance
3. restart mongos instances while configsvr-0 down
4. mongos instance goes into restart loop unable to find configsvr-0

**Expected behavior**

new mongos instances to succeed using configsvr replicates.

**Comment by alemorcuq** [comment]
Hi, @copelaje. I will try to reproduce your issue and get back to you.

**Comment by copelaje** [comment]
@alemorcuq , were you able to reproduce?  There may be better ways to keep configsvr-0 down, but if you use local PVCs to keep instances locked to a node and then make the node hosting configsvr-0 unschedulable it'll stay down when killed.

**Comment by alemorcuq** [comment]
Hi, @copelaje. Sorry for the delay, I lost track of this ticket. I was able to reproduce your issue, but only for the brief moment `configsvr-0` was down. After it came back up, everything worked again:

```
mongodb 10:33:26.94 INFO  ==> Trying to connect to MongoDB server mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local...
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
cannot resolve host "mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local": lookup mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local: no such host
mongodb 10:34:42.24 INFO  ==> Found MongoDB server listening at mg-mongodb-sharded-configsvr-0.mg-mongodb-sharded-headless.amoreno.svc.cluster.local:27017 !
```

Was this your experience as well?

**Comment by copelaje** [comment]
In my case configsvr is backed with a local storage PVC which means once k8s schedules it the first time that node will be the only one suitable for rescheduling of that instance.  If the node is down for maintenance the problem period will not be brief even through in my case there are 4 other replicates (one of which is the new primary).  There is no amount of replication that can prevent this single node failure as configsvr-0 is "special".  If configured properly to bootstrap with all instances and not just configsvr-0 this would not be an issue.

**Comment by alemorcuq** [comment]
I understand. I will open an internal task to try to figure out a solution for this. Thanks for reporting it.

**Comment by carrodher** [comment]
As it is a very isolated issue that is not always happening and due to other priorities the team has, we didn't have time to look into it. Since the issue was created it seems there are no more users reporting the same issue, so we can assume it was a corner case happening at a very specific timing.

Being said that, contributions are welcome just in case you want to collaborate by sending a PR, the team will be happy to review it and provide feedback.

**Comment by Mgonand** [comment]
Hey, this is driving us crazy too. It's a single point failure that can't be avoided and misses the point of having a very complicated sharded replicated database infrastructure for achieve high availability.

When the configsvr-0 goes down mongo becomes inoperative, what is the point of having 3 replicas if only one of them is the real deal?

I mean, with this issue you don't have a HA solution.

Is there some kind of workaround?

**Comment by copelaje** [comment]
No real work around for our setup. Pray not to lose config-0? :)

Agree it's not really HA if a single component loss can bring it down. It's particularly bad if you're using local PVs as you config-0 can't just reschedule on an alternate node.  You're stuck until that node is recovered or you manually intervene.

Unfortunately I don't have time to try patch up the chart myself at present, and it also appears to not a priority for the team.

**Comment by Mgonand** [comment]
I don't even know where to start and right now I'm focused on building mongodb-sharded as multiarch dockerimage with support to arm64.

I will give it a shot when I have time, but I'm far from being an expert here.
