### ISSUE TITLE
Airflow Missing Postgresql SSL Mode Option

### ISSUE THREAD

**Issue by treyhendon** [bitnami/charts#6820]
**Which chart**:
Airflow (10.2.2)

**Describe the bug**
The option to set Postgres SSL Mode via a value is missing.  Alternatively, we tried using the Global Additional Env Vars, but the Metrics container does not receive them.

**To Reproduce**

1. Use external Postgres with SSL Mode Require (i.e. Azure Postgresql).
2. Add `AIRFLOW_PROMETHEUS_POSTGRES_SSL_MODE` to `extraEnvVars`.
3. Deploy Helm Chart.
4. Look at the `airflow-exporter` pod's logs
5. See constant errors about SSL mode.

**Expected behavior**
Best case, the helpers would generate an `airflow.sslMode` value that the Metric Exporter Deployment would use.  Alternatively, the Metric Exporter should receive the global env vars that the other pods are receiving.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Using Azure DevOps hosted agent: Helm 3.6.1
```

- Output of `kubectl version`:

```
Client: Using Azure DevOps hosted ageint: Kubectl 1.20.1-5-g76a04fc

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4a4913e790a033f1101af2f0fb7be189b106e3ae", GitTreeState:"clean", BuildDate:"2021-05-25T17:37:03Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Hosted in AKS using Azure Postgresql for external Airflow Database.

**Comment by treyhendon** [comment]
As a workaround for now, I've build a custom Dockerfile with 2 lines and am referencing it as my metrics image:

```
FROM bitnami/airflow-exporter
ENV AIRFLOW_PROMETHEUS_POSTGRES_SSL_MODE="require"
```

**Comment by carrodher** [comment]
It seems there is not an option for configuring that env. variable at this moment, if you would like to contribute to this feature we will be happy to review any PR in https://github.com/bitnami/bitnami-docker-airflow. Then, once added the env. variable in the container another PR here in bitnami/charts will be needed to add the env. variable to the pod.

**Comment by treyhendon** [comment]
Apologies, we had a product release and I was out of office for an extended period so I've not been able to follow up on this.

The environment variable I'm referencing is a natively supported value, so it should not require any changes to the `bitnami-docker-airflow-exporter` image.  My workaround with the custom image was simply to prevent branching the entire Helm chart to add the ENV value (since the chart supports overriding the image).

I'll will work on a PR for this Helm chart to resolve this.  Thanks!

**Comment by pablogalegoc** [comment]
Thanks for your contribution @treyhendon!
