### ISSUE TITLE
[bitnami/common] Extra common labels

### ISSUE THREAD

**Issue by EtienneBarbier** [bitnami/charts#6821]
Hi,
Is it possible to have a common way to declare extra labels for all manifest of a chart ?

Most of the chart use template "common.labels.standard" to declare theirs labels. This template do not take parameter from values file yet. And it's not possible to add custom labels.

In kube-prometheus we call "kube-prometheus.labels" wich call "common.labels.standard" and add custom label from .Values.global.labels

```
{{/*
Common Labels
*/}}
{{- define "kube-prometheus.labels" -}}
{{ include "common.labels.standard" . }}
{{- if .Values.global.labels }}
{{ toYaml .Values.global.labels }}
{{- end }}
{{- end -}}
```

I want to be able to add custom labels for many charts but i'm lazy and i want to factor.

Is it possible to modify the common library like this or is not so easy ?
```
{{/*
Kubernetes standard labels
*/}}
{{- define "common.labels.standard" -}}
app.kubernetes.io/name: {{ include "common.names.name" . }}
helm.sh/chart: {{ include "common.names.chart" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.global.labels }}
{{ toYaml .Values.global.labels }}
{{- end }}
{{- end -}}
```

I can do the job if it's a good solution.
Regards,
Etienne.

**Comment by rafariossaa** [comment]
Hi,
  It seems that this feature is missing in the kube-prometheous chart.
 We usually have something [like this](https://github.com/bitnami/charts/blob/dd531ff115d04c8357e5009f8366b254645ef1d7/bitnami/mariadb/templates/secrets.yaml#L4):
```
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: COMPONENT_NAME
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
```
  And you can add the labels you need by using `commonLabels` [in the values.yaml](https://github.com/bitnami/charts/blob/dd531ff115d04c8357e5009f8366b254645ef1d7/bitnami/mariadb/values.yaml#L53).

  It is a different approach than the one you propose, but for the same functionality.

  If that would work for you, would you like to send a PR to add it to kube-prometheus ? We will be glad to review and merge it.

**Comment by EtienneBarbier** [comment]
Hi,
I think i was not clear enough.

We are able to add labels in kube-prometheus. For that, _helper.tpl define intermediate template to include labels.
```
metadata:
  name: {{ template "kube-prometheus.operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-prometheus.operator.labels" . | nindent 4 }}
```
```
{{/*
Common Labels
*/}}
{{- define "kube-prometheus.labels" -}}
{{ include "common.labels.standard" . }}
{{- if .Values.global.labels }}
{{ toYaml .Values.global.labels }}
{{- end }}
{{- end -}}

{{/*
Labels for operator
*/}}
{{- define "kube-prometheus.operator.labels" -}}
{{ include "kube-prometheus.labels" . }}
app.kubernetes.io/component: operator
{{- end -}}
```

I want to add labels to `kube-state-metrics` and `node-exporter` where nothing in implemented to do that.

The question is: How implement commonLabels for `kube-state-metrics`, `node-exporter` and all other charts ?

I see 3 solutions:
1. kube-prometheus way with intermediate template. (need to update all manifests)
2. mariadb way as @rafariossaa describe. (need to update all manifests)
3. By editing `common.labels.standard` to factor the feature. (Label will be set with same way for all chart)

**Comment by rafariossaa** [comment]
Hi,
  I would stick to the option 2. That is the way it is implemented in all the charts of our catalog.
