### ISSUE TITLE
After specify values.yml error occured

### ISSUE THREAD

**Issue by csib** [bitnami/charts#6824]
**Which chart**:
elasticsearch - 7.13.2

**Describe the bug**
I just wanted to install the chart.
wget https://raw.githubusercontent.com/bitnami/charts/master/bitnami/elasticsearch/values.yaml
helm install elasticsearch -f values.yaml  elastic/elasticsearch -n logging
```
coalesce.go:163: warning: skipped value for image: Not a table.
Error: template: elasticsearch/templates/statefulset.yaml:15:24: executing "elasticsearch/templates/statefulset.yaml" at <include "elasticsearch.esMajorVersion" .>: error calling include: template: elasticsearch/templates/_helpers.tpl:59:78: executing "elasticsearch.esMajorVersion" at <.Values.image>: wrong type for value; expected string; got map[string]interface {}
```

**To Reproduce**
1. wget https://raw.githubusercontent.com/bitnami/charts/master/bitnami/elasticsearch/values.yaml
2. helm install elasticsearch -f values.yaml  elastic/elasticsearch -n logging

**Version of Helm and Kubernetes**: Helm 3.5.3 Kubernetes: 1.19.9

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

```

Without the -f values.yaml I am able to install it.

**Comment by alemorcuq** [comment]
It looks you are trying to install a non-Bitnami chart (`elastic/elasticsearch`), so the `values.yaml` file for the Bitnami chart won't work with that one.

**Comment by csib** [comment]
Ohh, god. It was the end of a 12 hours working day. 
Close this issue. Thank you.
