### ISSUE TITLE
[ bitnami/external-dns] AWS Route53 permissions problem after installing the chart

### ISSUE THREAD

**Issue by victor-sudakov** [bitnami/charts#6825]
**Which chart**:
bitnami/external-dns

**Describe the bug**
After installing the chart in a kops-managed cluster, I see that the external-dns pod is running, but it never creates the DNS RRs in Route53 specified in the service manifest. In the external-dns pod logs, I see messages about AWS insufficient permissions (see them below).

Not sure if this is the problem with kops or bitnami/external-dns chart or something is amiss in the [installation documentation](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/README.md). The installation of kops is pretty vanilla and seems to work normally otherwise.

**To Reproduce**
```
$ kops create cluster  --networking calico --network-cidr 172.29.0.0/16 --zones=... # wait for the cluster to become operational
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install extdnstest1 --set provider=aws --set aws.zoneType=public --set txtOwnerId=Z02623112NLL1ROIOIX5T --set domainFilters[0]=k8s.MYDOMAIN.EXAMPLE bitnami/external-dns
$ kubectl --namespace=default get pods -l "app.kubernetes.io/name=external-dns,app.kubernetes.io/instance=extdnstest1"
NAME                                       READY   STATUS    RESTARTS   AGE
extdnstest1-external-dns-76bc77d96-r9d4k   1/1     Running   0          16s
$ kubectl apply -f hello-with-dns.yaml
```
The `host` command shows that the expected RR has never been created. In the logs:
```
time="2021-07-02T02:52:17Z" level=error msg="records retrieval failed: failed to list hosted zones: AccessDenied: User: arn:aws:sts::286855394570:assumed-role/nodes.k8s.MYDOMAIN.EXAMPLE/i-080ef63eb5df3b537 is not authorized to perform: route53:ListHostedZones\n\tstatus code: 403, request id: b91745a7-4a50-4263-a0cf-ccd3cdd050c6"
time="2021-07-02T02:52:17Z" level=error msg="records retrieval failed: failed to list hosted zones: AccessDenied: User: arn:aws:sts::286855394570:assumed-role/nodes.k8s.MYDOMAIN.EXAMPLE/i-080ef63eb5df3b537 is not authorized to perform: route53:ListHostedZones\n\tstatus code: 403, request id: 108bc35b-fbe3-44f6-a603-e2a2868e6e6e"
```
**Expected behavior**
A DNS A record for hello.MYDOMAIN.EXAMPLE should appear after several minutes.

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
Maybe IAM permissions are incorrect? Should not the chart installation docs mention them, or handled automatically?

**Comment by victor-sudakov** [comment]
And yes, i do have the AllowExternalDNSUpdates policy as specified in https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md. It's the chart not applying it to the external-dns pod or what?

**Comment by Mauraza** [comment]
Hi @victor-sudakov,

It seems you have a permission problem:
```
User: arn:aws:sts::286855394570:assumed-role/nodes.k8s.MYDOMAIN.EXAMPLE/i-080ef63eb5df3b537 is not authorized to perform: route53:ListHostedZones\n\tstatus code: 403,
```

You can add the parameters  `aws.credentials.accessKey`,  `aws.credentials.secretKey`, `aws.credentials.mountPath` to solve it.

**Comment by victor-sudakov** [comment]
> Hi @victor-sudakov,
> 
> It seems you have a permission problem:
> 
> ```
> User: arn:aws:sts::286855394570:assumed-role/nodes.k8s.MYDOMAIN.EXAMPLE/i-080ef63eb5df3b537 is not authorized to perform: route53:ListHostedZones\n\tstatus code: 403,
> ```
> 
> You can add the parameters `aws.credentials.accessKey`, `aws.credentials.secretKey`, `aws.credentials.mountPath` to solve it.

HI @Mauraza 

What should I put under  `aws.credentials.mountPath` ? And whose accessKey and secretKey should I use (what user or role)?

**Comment by Mauraza** [comment]
Hi @victor-sudakov,

you can check the parameter in the [README.md](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/README.md#parameter)
```markdown
aws.credentials.accessKey | When using the AWS provider, set aws_access_key_id in the AWS credentials (optional) | ""
-- | -- | --
aws.credentials.secretKey | When using the AWS provider, set aws_secret_access_key in the AWS credentials (optional) | ""
aws.credentials.mountPath | When using the AWS provider, determine mountPath for credentials secret | "/.aws"
```
You don't need all with one of these should be enough.

**Comment by victor-sudakov** [comment]
> Hi @victor-sudakov,
> 
> you can check the parameter in the [README.md](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/README.md#parameter)
> 
> ```gfm
> aws.credentials.accessKey | When using the AWS provider, set aws_access_key_id in the AWS credentials (optional) | ""
> -- | -- | --
> aws.credentials.secretKey | When using the AWS provider, set aws_secret_access_key in the AWS credentials (optional) | ""
> aws.credentials.mountPath | When using the AWS provider, determine mountPath for credentials secret | "/.aws"
> ```
> 
> You don't need all with one of these should be enough.

@Mauraza Do you mean that I should create some arbitrary IAM user, associate the AllowExternalDNSUpdates policy with that user, and specify that user's aws_access_key_id and aws_secret_access_key when installing the chart?

**Comment by victor-sudakov** [comment]
Thank you all who have lead me through this!

I've created an IAM user, associated the AllowExternalDNSUpdates policy with that user, and specified that user's aws_access_key_id and aws_secret_access_key when installing the chart, and now everything works. The final helm command line was like
```
helm install extdnstest1 --set provider=aws --set aws.zoneType=public --set txtOwnerId=XXX \
        --set domainFilters[0]=k8s.XXX\
        --set aws.credentials.accessKey=XXX \
        --set aws.credentials.secretKey=XXX bitnami/external-dns
```

The documentation could have been more clear about the internals of all this.
