### ISSUE TITLE
[bitnami/influxdb] Again same issue like #6401

### ISSUE THREAD

**Issue by bartlomiejwulff** [bitnami/charts#6826]
https://github.com/bitnami/charts/blob/dd531ff115d04c8357e5009f8366b254645ef1d7/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml#L93

This line is again wrong! It has been fixed in #6401 but now the value is again wrong!

It should be:
```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

Instead of:

```
image: {{ include "influxdb.image" . | quote }}
```

**Comment by migruiz4** [comment]
Hi @bartlomiejwulff,

I'm sorry but I don't understand what you mean.

In this issue #6401, you reported the same line should be:
```diff
- image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
+ image: {{ include "influxdb.image" . }}
```
And the change was applied in this PR https://github.com/bitnami/charts/pull/6404.

Now you say that the change should be reverted? Why is "influxdb.image" wrong?

**Comment by bartlomiejwulff** [comment]
Sorry my bad. Everything is fine here.
