### ISSUE TITLE
[bitnami/postgresql-ha] Not able to change wal_level='logical' in postgresql.conf

### ISSUE THREAD

**Issue by kabiraj-fareye** [bitnami/charts#6830]
I am not able to change wal_level='logical' in postgresql.conf. The wal_level changes to 'hot_standby' (replica) automatically when the server starts even after overriding with value 'logical'

Steps to produce
1. Override the entire postgresql.conf by specifying the below key value pairs in postgresql.configuration
```bash
postgresql:
      configuration: |-
        listen_addresses = '*'
        port = '5432'
        max_connections = '25000'
        wal_level = 'logical'
        fsync = 'on'
        max_wal_size = '400MB'
        archive_mode = 'on'
        archive_command = '/bin/true'
        max_wal_senders = '16'
        wal_keep_segments = '12'
        max_replication_slots = '10'
        logging_collector = 'on'
        log_directory = '/opt/bitnami/postgresql/logs'
        log_filename = 'postgresql.log'
        log_connections = 'false'
        log_disconnections = 'false'
        log_hostname = 'true'
        client_min_messages = 'error'
        include_dir = 'conf.d'
        pgaudit.log_catalog = 'off'
        shared_preload_libraries = 'repmgr'
        hot_standby = 'off'
```
2. Install the helm charts and wait for the primary and secondary nodes to come up.
3. Exec into any node (primary or secondary) and execute cat /opt/bitnami/postgresql/conf/postgresql.conf. You will see below:
listen_addresses = '*'
port = '5432'
max_connections = '25000'
**wal_level = 'hot_standby'**
fsync = 'on'
max_wal_size = '400MB'
archive_mode = 'on'
archive_command = '/bin/true'
max_wal_senders = '16'
wal_keep_segments = '12'
max_replication_slots = '10'
logging_collector = 'on'
log_directory = '/opt/bitnami/postgresql/logs'
log_filename = 'postgresql.log'
log_connections = 'false'
log_disconnections = 'false'
log_hostname = 'true'
client_min_messages = 'error'
include_dir = 'conf.d'
pgaudit.log_catalog = 'off'
shared_preload_libraries = 'repmgr'
**hot_standby = 'on'**

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 

I included the configuration like this:
```
diff --git a/bitnami/postgresql-ha/values.yaml b/bitnami/postgresql-ha/values.yaml
index 801d4d27e..f69c9035f 100644
--- a/bitnami/postgresql-ha/values.yaml
+++ b/bitnami/postgresql-ha/values.yaml
@@ -480,7 +480,29 @@ postgresql:
   ##   port = '5432'
   ##   ...
   ##
-  configuration: ""
+  configuration: |-
+    listen_addresses = '*'
+    port = '5432'
+    max_connections = '25000'
+    wal_level = 'logical'
+    fsync = 'on'
+    max_wal_size = '400MB'
+    archive_mode = 'on'
+    archive_command = '/bin/true'
+    max_wal_senders = '16'
+    wal_keep_segments = '12'
+    max_replication_slots = '10'
+    logging_collector = 'on'
+    log_directory = '/opt/bitnami/postgresql/logs'
+    log_filename = 'postgresql.log'
+    log_connections = 'false'
+    log_disconnections = 'false'
+    log_hostname = 'true'
+    client_min_messages = 'error'
+    include_dir = 'conf.d'
+    pgaudit.log_catalog = 'off'
+    shared_preload_libraries = 'repmgr'
+    hot_standby = 'off'
 
   ## PostgreSQL client authentication configuration
   ## You can use this parameter to specify the content for pg_hba.conf
```
I checked the postgresql.conf inside the postgresql-ha-postgresql-0 :
```
$ cat ./bitnami/postgresql/conf/postgresql.conf
listen_addresses = '*'
port = '5432'
max_connections = '25000'
wal_level = 'logical'
fsync = 'on'
max_wal_size = '400MB'
archive_mode = 'on'
archive_command = '/bin/true'
max_wal_senders = '16'
wal_keep_segments = '12'
max_replication_slots = '10'
logging_collector = 'on'
log_directory = '/opt/bitnami/postgresql/logs'
log_filename = 'postgresql.log'
log_connections = 'false'
log_disconnections = 'false'
log_hostname = 'true'
client_min_messages = 'error'
include_dir = 'conf.d'
pgaudit.log_catalog = 'off'
shared_preload_libraries = 'repmgr'
hot_standby = 'off'
```
And I can not reproduce the issue. I am using postgresql-ha 7.7.2 version.

Thanks a lot

Álvaro

**Comment by kabiraj-fareye** [comment]
@alvneiayu Hi, i am using postgresql 12.7.0 and below is my entire configuration. I can see the correct config in configmap, but those changes are not being reflected inside pods.

```bash
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: dev-team
spec:
  serviceAccountName: dev-team
  interval: 5m
  releaseName: pgsql
  chart:
    spec:
      chart: postgresql-ha
      version: 7.6.3
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: dev-team
      interval: 1m
  values:
    global:
      postgresql:
        existingSecret: postgresql-secret
      pgpool:
        existingSecret: pgpool-secret
    postgresql:
      maxConnections: 25000
      configuration: |-
        listen_addresses = '*'
        port = '5432'
        max_connections = '25000'
        wal_level = 'logical'
        fsync = 'on'
        max_wal_size = '400MB'
        archive_mode = 'on'
        archive_command = '/bin/true'
        max_wal_senders = '16'
        wal_keep_segments = '12'
        max_replication_slots = '10'
        logging_collector = 'on'
        log_directory = '/opt/bitnami/postgresql/logs'
        log_filename = 'postgresql.log'
        log_connections = 'false'
        log_disconnections = 'false'
        log_hostname = 'true'
        client_min_messages = 'error'
        include_dir = 'conf.d'
        pgaudit.log_catalog = 'off'
        shared_preload_libraries = 'repmgr'
        hot_standby = 'off'

  #    replicaCount: 3
  #    livenessProbe:
  #      enabled: false
  #      periodSeconds: 900
  #    readinessProbe:
  #      enabled: false
  #      periodSeconds: 900
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 4000m
          memory: 16Gi
    pgpool:
      numInitChildren: 250
      maxPool: 100
      replicaCount: 2
      livenessProbe:
  #      enabled: false
        periodSeconds: 300
      readinessProbe:
  #      enabled: false
        periodSeconds: 300
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 5000m
          memory: 5Gi
  #  metrics:
  #    resources:
  #      requests:
  #        cpu: 250m
  #        memory: 256Mi
  #      limits:
  #        cpu: 500m
  #        memory: 512Mi
    postgresqlImage:
      tag: 12.7.0
    persistence:
      mountPath: /postgresql
      size: 20Gi 
```
Attached configmap file and output of /opt/bitnami/postgresql/conf/postgresql.conf.
[postgres-conf-primary-node.txt](https://github.com/bitnami/charts/files/6755479/postgres-conf-primary-node.txt)
[postgres-configmap.txt](https://github.com/bitnami/charts/files/6755480/postgres-configmap.txt)

**Comment by kabiraj-fareye** [comment]
I just ran chart version 7.7.2 and got the same result.

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 

I think that I know why you are reproducing the problem. If you take a look the bash scripts inside our postgresql-repmgr docker:

[here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/561192a0cf0d18bec7cb096ff06bed9a2902d797/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L367)

```
postgresql_configure_replication_parameters() {
    local -r psql_major_version="$(postgresql_get_major_version)"
    info "Configuring replication parameters"
    postgresql_set_property "wal_level" "hot_standby"
    postgresql_set_property "max_wal_size" "400MB"
    postgresql_set_property "max_wal_senders" "16"
    if ((psql_major_version >= 13)); then
        postgresql_set_property "wal_keep_size" "128MB"
    else
        postgresql_set_property "wal_keep_segments" "12"
    fi
    postgresql_set_property "hot_standby" "on"
}
```

This function is creating a configuration file in case that a mounted configuration file is not detected:

[here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/561192a0cf0d18bec7cb096ff06bed9a2902d797/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L565)
```
    if postgresql_is_file_external "postgresql.conf"; then
        info "Custom configuration $POSTGRESQL_CONF_FILE detected"
        create_conf_file=no
    fi
```

[here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/561192a0cf0d18bec7cb096ff06bed9a2902d797/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L507)

```
postgresql_is_file_external() {
    local -r filename=$1
    if [[ -d "$POSTGRESQL_MOUNTED_CONF_DIR" ]] && [[ -f "$POSTGRESQL_MOUNTED_CONF_DIR"/"$filename" ]]; then
        return 0
    else
        return 1
    fi
}
```
Are you including any change inside the chart? It seems that the configmap is not mounted in the path expected.

With this values file:

```
$ cat values-new.yaml 
postgresql:
  maxConnections: 25000
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 16Gi
  configuration: |-
    listen_addresses = '*'
    port = '5432'
    max_connections = '25000'
    wal_level = 'logical'
    fsync = 'on'
    max_wal_size = '400MB'
    archive_mode = 'on'
    archive_command = '/bin/true'
    max_wal_senders = '16'
    wal_keep_segments = '12'
    max_replication_slots = '10'
    logging_collector = 'on'
    log_directory = '/opt/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = 'false'
    log_disconnections = 'false'
    log_hostname = 'true'
    client_min_messages = 'error'
    include_dir = 'conf.d'
    pgaudit.log_catalog = 'off'
    shared_preload_libraries = 'repmgr'
    hot_standby = 'off'
```

and installing the chart like this:

```
helm install test bitnami/postgresql-ha -f values-new.yaml
```

I can not reproduce the problem.

Thanks a lot and waiting your feedback

Álvaro

**Comment by kabiraj-fareye** [comment]
hi @alvneiayu, thanks for replying. As per the files attached in my previous comment, i am passing custom postgresql.conf from values like below
```bash
postgresql:
      configuration: |-
        listen_addresses = '*'
        port = '5432'
        max_connections = '25000'
        wal_level = 'logical'
        fsync = 'on'
        max_wal_size = '400MB'
        archive_mode = 'on'
        archive_command = '/bin/true'
        max_wal_senders = '16'
        wal_keep_segments = '12'
        max_replication_slots = '10'
        logging_collector = 'on'
        log_directory = '/opt/bitnami/postgresql/logs'
        log_filename = 'postgresql.log'
        log_connections = 'false'
        log_disconnections = 'false'
        log_hostname = 'true'
        client_min_messages = 'error'
        include_dir = 'conf.d'
        pgaudit.log_catalog = 'off'
        shared_preload_libraries = 'repmgr'
        hot_standby = 'off'
```
The above config is also reflecting fine in configmap.

kabiraj@ip-172-31-13-149:~$ kubectl describe configmap pgsql-postgresql-ha-postgresql-configuration -n dev-team
Name:         pgsql-postgresql-ha-postgresql-configuration
Namespace:    dev-team
Labels:       app.kubernetes.io/component=postgresql
              app.kubernetes.io/instance=pgsql
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=postgresql-ha
              helm.sh/chart=postgresql-ha-7.6.3
              helm.toolkit.fluxcd.io/name=postgresql
              helm.toolkit.fluxcd.io/namespace=dev-team
Annotations:  meta.helm.sh/release-name: pgsql
              meta.helm.sh/release-namespace: dev-team

Data
====
postgresql.conf:
----
listen_addresses = '*'
port = '5432'
max_connections = '25000'
wal_level = 'logical'
fsync = 'on'
max_wal_size = '400MB'
archive_mode = 'on'
archive_command = '/bin/true'
max_wal_senders = '16'
wal_keep_segments = '12'
max_replication_slots = '10'
logging_collector = 'on'
log_directory = '/opt/bitnami/postgresql/logs'
log_filename = 'postgresql.log'
log_connections = 'false'
log_disconnections = 'false'
log_hostname = 'true'
client_min_messages = 'error'
include_dir = 'conf.d'
pgaudit.log_catalog = 'off'
shared_preload_libraries = 'repmgr'
hot_standby = 'off'
Events:  <none>

I am sure that its detecting the custom config as you can see all other params are being updated properly except wal_level='logical and hot_standby='off'

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 

Please, could you set up postgresqlImage.debug=true and send me complete log from one of the postgresql pod?

Could you do a test, remove the PVCs (Caution: you are going to delete all the data) and reinstall again the chart? please, share with me the commands that you are executing to reproduce the problem.

Thanks a lot

Álvaro

**Comment by flokli** [comment]
I'm also running into this, and opened https://github.com/bitnami/charts/issues/6830.

**Comment by alvneiayu** [comment]
hi @flokli 

Please, close the new issue, we can continue here. Share with me pod logs, please. This is something related to the scripts and the configmap but I can not reproduce it. I am missing something. 

Thanks a lot

Álvaro

**Comment by flokli** [comment]
The linked issue is about explicitly being able to set this option, by starting the container with an environment variable.

Accepting that option in the container init scripts is a requirement for this to be settable in the helm charts (what this issue is about).

I don't really want to pass in an entirely different configuration file, but would like to set /only that value/. Entirely replacing the config file, and debugging why other hardcoded assumptions clash with it is really just a workaround.

**Comment by kabiraj-fareye** [comment]
Hi @alvneiayu,sorry for replying late. Previously I already removed pvc and reinstalled helm release and got the same result. I will enable postgresqlImage.debug=true and do the same steps again. I will share the logs soon.

**Comment by alvneiayu** [comment]
hi @flokli and @kabiraj-fareye 

No, we don't have this support right now. Now, you need to set up a complete config file. If you want, let me open an internal task to try to investigate and develop a support to try to set up those variables with env vars.

@kabiraj-fareye, please share with me the logs and I will take a look the issue that you are reproducing.

Thanks a lot

Álvaro

**Comment by flokli** [comment]
I was able to set (only) this in the `postgresql` chart, via `postgresqlExtendedConf`.

I didn't check if setting it via `postgresql.extendedConf` in this chart did work, though.

**Comment by kabiraj-fareye** [comment]
Hi @alvneiayu , Please find the attached logs in debug mode for primary and secondary nodes.
[secondary_node_debug.log](https://github.com/bitnami/charts/files/6776954/secondary_node_debug.log)
[primary_node_debug.log](https://github.com/bitnami/charts/files/6776955/primary_node_debug.log)

**Comment by flokli** [comment]
> Hi @flokli, as per the documentation, postgresql.extendedConf only appends additional config to the existing config and will not override any existing config. So, how did it work for you? Did you remove below two from main config and appended them to main config using postgresql.extendedConf?

Again, as written in https://github.com/bitnami/charts/issues/6830#issuecomment-874950068, this was `postgresqlExtendedConf` in the `postgresql` chart, not `postgresql.extendedConf` in the `postgresql-ha` chart.

There, I only had to set it in `postgresqlExtendedConf`. I didn't touch the main config file at all.

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 
Here is the problem:
```
postgresql-repmgr 11:54:08.36 INFO  ==> Configuring replication parameters
```
This function is modifying the values but it is really curious because the configuration is detected:
```
postgresql-repmgr 11:54:06.30 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
```
and this check:
```
is_boolean_yes "$create_conf_file" && postgresql_configure_replication_parameters 
```
will be false because create_conf_file is no
```
    if postgresql_is_file_external "postgresql.conf"; then                                                              
        info "Custom configuration $POSTGRESQL_CONF_FILE detected"                                                      
        create_conf_file=no                                                                                             
    fi    
```
It is really strange this. It seems that the value of create_conf_file is missing or the function is_boolean_yes is not working properly and I can not reproduce it.

In which environment, are you executing the chart? (Linux, Mac or Windows) Are you using minikube, kind, AWS, etc?

It is so strange because we use this script (the same one) in other assets and also we test them in AWS, AKS, etc.

Thanks a lot

Álvaro

**Comment by kabiraj-fareye** [comment]
Hi @alvneiayu, we use this in EKS.

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 

I tested with EKS and in a linux environment and I can not reproduce the behavior that you are talking about. I am still investigating about it.

Thanks a lot

Álvaro

**Comment by kabiraj-fareye** [comment]
Hi @alvneiayu, could you post your values.yaml file here from which you are able to change wal_level='logical'?

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 

I tested modifying the values.yaml doing the changes like [this](https://github.com/bitnami/charts/issues/6830#issuecomment-873057970), directly in the chart values.yaml. And also installing the chart with this values-new.yaml:

[values-new.zip](https://github.com/bitnami/charts/files/6799461/values-new.zip)

Installing the chart doing:

```
helm install test bitnami/postgresql-ha -f values-new.yaml
```
Thanks a lot

Álvaro

**Comment by flokli** [comment]
There's now a [dedicated option](https://github.com/bitnami/bitnami-docker-postgresql/issues/292) in the container image.

Should this be also added to the helm charts?

**Comment by alvneiayu** [comment]
hi @flokli 

To use a env variable with your chart, you can use the postgresql.extraEnvVarsCM key. You can define the env var with the specific value that you want. By doing this, it should work. 

Thanks a lot for your PR and thanks a lot for your help

Álvaro

**Comment by kabiraj-fareye** [comment]
Hi @alvneiayu So i should set POSTGRESQL_WAL_LEVEL=logical in postgresql.extraEnvVarsCM key? Like below? I don't see any documentation. Also, will it work for image tag 12.7.0?
```bash
postgresql:
  extraEnvVarsCM:
    POSTGRESQL_WAL_LEVEL=logical
```

**Comment by alvneiayu** [comment]
hi @kabiraj-fareye 

You need to use extraEnvVars. Inside the values.yaml, you can see an example:

https://github.com/bitnami/charts/blob/4ecb582b1563e17a34509b99af1cdd8c389b5eb9/bitnami/postgresql-ha/values.yaml#L219

And yes, it will work with the tag 12.7.0-debian-10-r64.

Thanks

Álvaro

**Comment by kabiraj-fareye** [comment]
Hi @alvneiayu just to be clear, do I have to pas something like below? Also, as per doc, this will just add the env variable, so will it replace the wal_level in postgresql.config?
```bash
extraEnvVars:
	- name: POSTGRESQL_WAL_LEVEL
	  value: logical
```

**Comment by alvneiayu** [comment]
hi @alvneiayu 

If you are in the version (12.7.0-debian-10-r64) that I shared with you, yes. Setting up the variable POSTGRESQL_WAL_LEVEL, you can modify the postgresql.config.

Thanks

Álvaro

**Comment by dare-mr** [comment]
What is the proper way to change the WAL level to logical using this chart? 
I don't see this environment variable (POSTGRESQL_WAL_LEVEL) defined anywhere in the documentation for the docker image used in this chart.

**Comment by javsalgar** [comment]
Hi,

Here you can see the code that uses the env var

https://github.com/bitnami/containers/blob/main/bitnami/postgresql/12/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L380
