### ISSUE TITLE
[bitnami/airflow] If using KubernetesExecutor redis deployed is not used, so it should not be created

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#6831]
**Which chart**:
airflow all charts

**Describe the bug**
airflow: if using KubernetesExecutor redis deployed is not used, so it should not be created

**To Reproduce**
Deploy with kubernetesexecutor and redis will get created and won't be used anywhere internally. If I'm wrong here please close this ticket.

**Expected behavior**
if kubernetesexecutor don't deploy redis if it's not being used

**Comment by pablogalegoc** [comment]
Hi @iamsudip!

There's a section in the README where we describe the appropriate parameters when using `KubernetesExecutor`:
https://github.com/bitnami/charts/tree/master/bitnami/airflow#kubernetesexecutor
One of them is `redis.enabled=false` as you point out  🙂
