### ISSUE TITLE
[bitnami/grafana] Option to specify pod labels (podLabels)

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#6842]
**Which chart**:
bitnami/grafana 6.0.1

**Is your feature request related to a problem? Please describe.**
We would like to add extra labels to the pod generated by the deployment.

**Describe the solution you'd like**
We would like the possibility to set podLabels in values.yaml, that would be applied as a label to pods generated by the deployment. 

An example implemented in the Kafka chart. 
values.yaml: https://github.com/bitnami/charts/blob/c631461ad1244a82e1ed1de56773b82e8a6dc5d3/bitnami/kafka/values.yaml#L447
statefulset.yaml (would be deployment.yaml in grafana):
https://github.com/bitnami/charts/blob/c631461ad1244a82e1ed1de56773b82e8a6dc5d3/bitnami/kafka/templates/statefulset.yaml#L42-L44

**Describe alternatives you've considered**
No alternatives investigated.

**Additional context**
A lot of other Bitnami charts have already this implemented, so I think it is just getting this chart up-2-date on podLabel front.

**Comment by juan131** [comment]
Thanks @nc-ruth for pointing this out! I just created a PR to add the missing parameter
