### ISSUE TITLE
wrong heapSize key for master

### ISSUE THREAD

**Issue by bharthur** [bitnami/charts#685]
https://github.com/bitnami/charts/blob/5f80d6e3517952637455a2fd2872714415aa8107/bitnami/elasticsearch/templates/master-deploy.yaml#L66

**Comment by juan131** [comment]
Hi @bharthur 

Thanks for reporting it. I just created a PR to fix it.

**Comment by juan131** [comment]
The PR has just been merged and the issue fixed. Please re-open the issue if you consider it necessary
