### ISSUE TITLE
I need upgrade and downgrade my wildfly repository in RKE 

### ISSUE THREAD

**Issue by ruwan1235** [bitnami/charts#6852]
I alredy used rancher bitnami wildfly latest helm repository. We have own git lab account and we added bitnami wildfly helm chart there. And deployed wildfly and start service and it is working fine. But we can't upgrade and downgrade using rke. we need fix that issue. we need add own update add our own update version.

**Comment by Mauraza** [comment]
Hi @ruwan1235,

Could you add more information about this, as the error you get?

**Comment by ruwan1235** [comment]
![Screenshot from 2021-07-06 14-03-48](https://user-images.githubusercontent.com/86238699/124568851-027ff180-de63-11eb-847b-623ad094a873.png)

this image show only last chart version.  We committed more chart version in my gttlab. we need show all commit versions

**Comment by ruwan1235** [comment]
we used custom gitlab repo @Mauraza

**Comment by chirathb** [comment]
@Mauraza any update

**Comment by ruwan1235** [comment]
any update @Mauraza

**Comment by ruwan1235** [comment]
anyone have solution for this issue

**Comment by Mauraza** [comment]
Hi @ruwan1235,

In helm, we only have one version of the chart
```bash
$ helm search repo wildfly
NAME           	CHART VERSION	APP VERSION	DESCRIPTION      
bitnami/wildfly	11.0.1       	24.0.0     	Chart for Wildfly
```
Maybe is a good idea to ask the Rancher team for more information about this.

**Comment by ruwan1235** [comment]
@Mauraza then  how to upgrade and downgrade helm version

**Comment by Mauraza** [comment]
Hi @ruwan1235,

You can find this command in the documentation of helm:
- https://helm.sh/docs/helm/helm_rollback/
- https://helm.sh/docs/helm/helm_upgrade/
For the last one, you can find an example in the [README.md](https://github.com/bitnami/charts/tree/master/bitnami/wildfly#upgrading)

**Comment by ruwan1235** [comment]
@Mauraza  do we need add bitnami/wildfly helm chart to my own gitlab repo. Is it posibel?

**Comment by Mauraza** [comment]
Hi @ruwan1235,

I guess so, but I don't know exactly what you want to add to your GitLab repository.

**Comment by ruwan1235** [comment]
yes i need add my own repositary. I alredy updated my own repo and change Chart.yaml. in rancher show last repo only. can you provide any solution

**Comment by ruwan1235** [comment]
> Hi @ruwan1235,
> 
> I guess so, but I don't know exactly what you want to add to your GitLab repository.

yes i need add my own repositary. I alredy updated my own repo and change Chart.yaml. in rancher show last repo only. can you provide any solution

**Comment by Mauraza** [comment]
Hi @ruwan1235,

sorry, we are not experts RKE, we can help you with any problem with the chart, maybe you can ask at https://forums.rancher.com/ probably someone with more experience and knowledge about it can help you.
