### ISSUE TITLE
[influxdb] pullSecret for azure backup job not defined and backup job cannot be triggered at the moment

### ISSUE THREAD

**Issue by daneb255** [bitnami/charts#6856]
**Which chart**:
2.2.11

**Describe the bug**
At the moment there is a bug in the azure-cli bitnami container -> https://github.com/bitnami/bitnami-docker-azure-cli/issues/1
So I need to deploy my own azure-cli container to create a azure backup. In your documentation is a optional tag for helm to configure a pullSecret for a custom azure image. But in the helm chart is no reference to values.yaml ->
https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml#L28
spec.jobTemplate.spec.template.spec.imagePullSecrets

**To Reproduce**

1. deploy current helm chart in azure aks cluster with custom azure backup image (also set backup.uploadProviders.azure.image.PullSecrets)
2. trigger a backup job

**Expected behavior**
Backup is saved to azure blob

**Version of Helm and Kubernetes**:
1.20.7 (also 1.20.5)

- Output of `helm version`:
```
3.6.0
```

- Output of `kubectl version`:
```
v1.21.1
```

**Additional context**

**Comment by daneb255** [comment]
I downloaded the helm chart and edit the following values -> 

In upload-azure.sh script -> 

az config set extension.use_dynamic_install=yes_without_prompt
az storage azcopy blob sync --source {{ .Values.backup.directory }} --container {{ .Values.backup.uploadProviders.azure.containerName }}

and also added imagePullSecrets in cronjob-backup.yaml (spec.jobTemplate.spec.template.spec.imagePullSecrets)

But now I´m able to create an influxdb backup with my edited container

**Comment by pablogalegoc** [comment]
Hi @daneb255,

If I understand correctly, you uncommented the following line in `backup.uploadProviders.azure.image` of the `values.yaml`:
https://github.com/bitnami/charts/blob/309c7c6e5eaab649a1f878c2f59198510086ef37/bitnami/influxdb/values.yaml#L907
So that you could use your custom azure-cli image here
https://github.com/bitnami/charts/blob/090b2fe171ed9e3f1e18a97312902e9bb44d322b/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml#L112
Also modified `upload-azure.sh` to work with AzCopy. Now this configuration is working for you or is there anything else where I can help?

**Comment by daneb255** [comment]
Hey @pablogalegoc ,

thanks for your message. There is no issue to set a new azure image. But if the new azure image is in a private registry, there is no setting for pullSecret  (but in values.yaml you can set a secret). So in cronjob-backup.yaml is a missing reference for the secret. There is also a second issue with the upload-azure.sh (checking at the moment -> https://github.com/bitnami/bitnami-docker-azure-cli/issues/1) .
So for now the helm chart is not working for azure backup :/ 

Greetings
@daneb255

**Comment by pablogalegoc** [comment]
Hi @daneb25,

It is true that in the `values.yaml` the key `backup.uploadProviders.azure.image.pullSecrets` is commented but it can be used anyway and should be picked up by:
https://github.com/bitnami/charts/blob/9e5aa0bdcb9ab6a375ffe90d14b9cd40ac797e13/bitnami/influxdb/templates/_helpers.tpl#L32-L37
This variable is available and documented in the README but we understand that this inconsistency can be confusing and we are in the middle of a transformation to make every key in the README have its clear counterpart in the `values.yaml` 🙂
