### ISSUE TITLE
Add bitnami repo add my own gitlab repo and version upgrade 

### ISSUE THREAD

**Issue by ruwan1235** [bitnami/charts#6861]
I added bitnami/wildfly latest helm chart to my own gitlab repositary.

After deploy that using rancher and it is working fine.

But i need upgrade that chart. I updated chart and changed the Chart.yaml and add new version number.

In rancher ui show only last version. now show any previous version. 
![Screenshot from 2021-07-06 14-13-31](https://user-images.githubusercontent.com/86238699/124608087-0d02b100-de8c-11eb-9fa4-9be95008acb8.png)

**Comment by carrodher** [comment]
Hi, I don't know how we (from Bitnami) can help you with this issue, it seems something to be asked in any Rancher/GitLab forum. We release the Wildfly Helm chart and push new versions to the bitnami repository (https://charts.bitnami.com/bitnami).

At this moment the latest published versions in the repository are:
```console
$ helm search repo bitnami/wildfly -l
NAME           	CHART VERSION	APP VERSION    	DESCRIPTION
bitnami/wildfly	11.0.1       	24.0.0         	Chart for Wildfly
bitnami/wildfly	11.0.0       	24.0.0         	Chart for Wildfly
bitnami/wildfly	10.0.6       	23.0.2         	Chart for Wildfly
bitnami/wildfly	10.0.4       	23.0.2         	Chart for Wildfly
bitnami/wildfly	10.0.3       	23.0.2         	Chart for Wildfly
bitnami/wildfly	10.0.2       	23.0.2         	Chart for Wildfly
bitnami/wildfly	10.0.1       	23.0.2         	Chart for Wildfly
bitnami/wildfly	10.0.0       	23.0.1         	Chart for Wildfly
bitnami/wildfly	9.0.1        	23.0.1         	Chart for Wildfly
bitnami/wildfly	9.0.0        	23.0.0         	Chart for Wildfly
...
```

But apart from that, we don't manage anything else related to Rancher nor GitLab, the different versions are present in the Helm Chart repository as shown above. I recommend you to move your question to another forum specialized in Rancher and/or GitLab, unfortunately, I don't think we can help you with this topic.

**Comment by ruwan1235** [comment]
@carrodher i alredy used bitnami/wildfly 11.0.1 and create my own gitlab repo and add bitnami/wildfly fills. and change Chart.yaml file and change version and add new commits. After i can't see old repo in rancher. can you give any solution? and do we need change any other places in bitnami/wildfly helm?

**Comment by carrodher** [comment]
I'm sorry but we are not familiar with Rancher or custom repositories hosted in another platform, as it seems it is not an issue with the Helm Chart itself, I don't know how we can help you. That is why I think you can find a proper answer in Rancher/GitLab forums.

**Comment by ruwan1235** [comment]
@carrodher after commit currunt repo do we need change only Chart.yaml?

**Comment by ruwan1235** [comment]
I already used custom repo which places do we need changed?
![Screenshot from 2021-07-07 20-52-39](https://user-images.githubusercontent.com/86238699/124786524-668ade80-df65-11eb-8e3b-6495e93976ab.png)

**Comment by carrodher** [comment]
Hi @ruwan1235, I'm sorry but we can't help you with this topic since it is not an issue with the chart and we don't have knowledge about how third-party services like Rancher or GitLab works. I recommend you to open a ticket in the support platform of those services.

I'm closing this issue because, unfortunately, it's something that we can't fix nor guide you in the proper direction.
