### ISSUE TITLE
etcd snapshot restore is failing if we have more than 2GB of data

### ISSUE THREAD

**Issue by PayalSasmal10** [bitnami/charts#6871]
Hi Team,

We have 2.6GB of AWS Dynamodb data which we migrated in etcd format. We want to restore those data in the GCP etcd operator. We are using etcd bitnami helm version as CR and etcd operator. But while trying to restore with the below command, we are getting an error. In the same way, we can restore snapshots if we have less than 2 GB of data.
Could you please help us? we need the solution urgent basis.

etcdctl snapshot restore /bitnami/etcd/snapshot/db
--data-dir /bitnami/etcd/data
--name etcdl
--initial-cluster ":2380"
--initial-cluster-token ""
--initial-advertise-peer-urls :2380
--skip-hash-check=true

{"level":"info","ts":1625570287.9687092,"caller":"snapshot/v3_snapshot.go:287","msg":"restoring snapshot","path":"/bitnami/etcd/snapshot/db","wal-dir":"/bitnami/etcd/data/member/wal","data-dir":"/bitnami/etcd/data","snap-dir":"/bitnami/etcd/data/member/snap"}
unexpected fault address 0x7f2cd61ce008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f2cd61ce008 pc=0x84d537]

goroutine 1 [running]:
runtime.throw(0xd45b2f, 0x5)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0002f0dd8 sp=0xc0002f0da8 pc=0x42c862
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:387 +0x47e fp=0xc0002f0e08 sp=0xc0002f0dd8 pc=0x44144e
go.etcd.io/bbolt.(*freelist).read(0xc000262180, 0x7f2cd61ce000)
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/freelist.go:265 +0x37 fp=0xc0002f0e98 sp=0xc0002f0e08 pc=0x84d537
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:316 +0xd1 fp=0xc0002f0ed0 sp=0xc0002f0e98 pc=0x857931
sync.(*Once).Do(0xc0003de168, 0xc0002f0f10)
/usr/local/go/src/sync/once.go:44 +0xb3 fp=0xc0002f0f00 sp=0xc0002f0ed0 pc=0x46f483
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0003de000)
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:309 +0x56 fp=0xc0002f0f30 sp=0xc0002f0f00 pc=0x8488a6
go.etcd.io/bbolt.Open(0xc0001d6930, 0x26, 0xc000000180, 0xc0002f11d8, 0xc0002f1048, 0xc0002f1058, 0x4355cf)
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:286 +0x326 fp=0xc0002f0ff0 sp=0xc0002f0f30 pc=0x848376
go.etcd.io/etcd/mvcc/backend.newBackend(0xc0001d6930, 0x26, 0x5f5e100, 0x2710, 0x0, 0x0, 0x280000000, 0x0, 0x0)
/tmp/etcd-release-3.4.7/etcd/release/etcd/mvcc/backend/backend.go:154 +0xfe fp=0xc0002f1238 sp=0xc0002f0ff0 pc=0x87cbfe
go.etcd.io/etcd/mvcc/backend.NewDefaultBackend(...)
/tmp/etcd-release-3.4.7/etcd/release/etcd/mvcc/backend/backend.go:143
go.etcd.io/etcd/clientv3/snapshot.(*v3Manager).saveDB(0xc000138a80, 0x0, 0x0)
/tmp/etcd-release-3.4.7/etcd/release/etcd/clientv3/snapshot/v3_snapshot.go:382 +0x463 fp=0xc0002f13d0 sp=0xc0002f1238 pc=0xb3fe33
go.etcd.io/etcd/clientv3/snapshot.(*v3Manager).Restore(0xc000138a80, 0x7ffcd8b5b3b8, 0x19, 0x7ffcd8b5b3d9, 0xc, 0x7ffcd8b5b5e1, 0x17, 0xc0001d66c0, 0x22, 0xc0001c6b10, ...)
/tmp/etcd-release-3.4.7/etcd/release/etcd/clientv3/snapshot/v3_snapshot.go:294 +0x89b fp=0xc0002f1b98 sp=0xc0002f13d0 pc=0xb3efdb
go.etcd.io/etcd/etcdctl/ctlv3/command.snapshotRestoreCommandFunc(0xc00030f180, 0xc0001f0180, 0x1, 0xc)
/tmp/etcd-release-3.4.7/etcd/release/etcd/etcdctl/ctlv3/command/snapshot_command.go:160 +0x2a5 fp=0xc0002f1d30 sp=0xc0002f1b98 pc=0xb6a6c5
github.com/spf13/cobra.(*Command).execute(0xc00030f180, 0xc0001f00c0, 0xc, 0xc, 0xc00030f180, 0xc0001f00c0)
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae fp=0xc0002f1e18 sp=0xc0002f1d30 pc=0xab99fe
github.com/spf13/cobra.(*Command).ExecuteC(0x14b8240, 0xb, 0xc000168b20, 0xb7f801)
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec fp=0xc0002f1ee8 sp=0xc0002f1e18 pc=0xaba64c
github.com/spf13/cobra.(*Command).Execute(...)
/home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
go.etcd.io/etcd/etcdctl/ctlv3.Start()
/tmp/etcd-release-3.4.7/etcd/release/etcd/etcdctl/ctlv3/ctl_nocov.go:25 +0x81 fp=0xc0002f1f18 sp=0xc0002f1ee8 pc=0xb7f6c1
main.main()
/tmp/etcd-release-3.4.7/etcd/release/etcd/etcdctl/main.go:35 +0x77 fp=0xc0002f1f98 sp=0xc0002f1f18 pc=0xb809b7
runtime.main()
/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0002f1fe0 sp=0xc0002f1f98 pc=0x42e1cc
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0002f1fe8 sp=0xc0002f1fe0 pc=0x459211

goroutine 11 [syscall]:
os/signal.signal_recv(0x459216)
/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 81 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0001c54a0)
/tmp/etcd-release-3.4.7/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
/tmp/etcd-release-3.4.7/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

**Comment by javsalgar** [comment]
Hi,

Checking what the SIGBUS error is, it doesn't seem to be related with how the chart is deployed, at least in principle. Not sure if the PVCs that you are using are running out of space or the cluster does not work as expected when dealing with huge data transfers. I've seen issues with SIGBUS in other etcd tickets https://github.com/etcd-io/etcd/issues/10426. I would advise you to check first with the etcd developers so they can check if it is a limitation on their side.

**Comment by PayalSasmal10** [comment]
Hi @javsalgar,

Thank you so much for the quick reply.

I have already gone through etcd-io/etcd#10426 and tried however they mentioned. But it did not work for me.  
I hope etcd developers will help me with this.

**Comment by vperi1730** [comment]
I could find a configuration option in the etcd documentation, Is there a way we can leverage this, Please suggest?

https://etcd.io/docs/v3.4/op-guide/configuration/

https://github.com/etcd-io/etcd/blob/release-3.4/etcd.conf.yml.sample

**Comment by javsalgar** [comment]
Thanks! Do you know which of these setting would fix the issue reported here?

**Comment by vperi1730** [comment]
Ideally **quota-backend-bytes: 0** (this needs to be changed according to the use case, keeping in mind a max of 8GB).

I am yet to try this approach to see if restoring >2GB snapshot can be consumed by etcd.

**Comment by javsalgar** [comment]
Cool, please let us know the results of your experiment

**Comment by vperi1730** [comment]
Sure thing

**Comment by vperi1730** [comment]
So guys, I was able to configure the quota-bytes to 8GB and could launch the etcd cluster. Now how do I check if it has considered 8GB or not, any etcdctl commands we have that can show us the details?

```
$ etcdctl endpoint status
{"level":"warn","ts":"2021-07-12T06:23:23.070Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection closed"}
Failed to get the status of endpoint 127.0.0.1:2379 (context deadline exceeded)

```

Do we also have any idea why am I seeing this error and what needs to be done to fix this?

**Comment by javsalgar** [comment]
It would be great if @PayalSasmal10 confirms if that works for their use case.

**Comment by vperi1730** [comment]
@PayalSasmal10 is presently out of the assignment and I had to take over this use case. Before I trigger the ask what Payal has mentioned i.e. about restoring the AWS backup of 2.6GB I would like to check that my etcd is running on 8GB memory instead of the earlier default value.

So my question is, how do I check that. Would you be able to assist me with this?

**Comment by javsalgar** [comment]
Hi,

I've checked and that should appear in the application logs:

```
{"level":"info","ts":"2021-07-12T07:55:20.004Z","caller":"etcdserver/quota.go:94","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
```

Could you check the logs of the pods to see what it shows?

**Comment by vperi1730** [comment]
Unfortunately, I couldn't find any log message of such a thing, If you are aware of etcd/etcdctl command that can print us the quota, please let me know.

Also, how can we resolve the context deadline exceeded issues, though etcd is up and running, check on endpoint health results in the unhealthy cluster?

**Comment by vperi1730** [comment]
```
$ ETCDCTL_API=3 etcdctl --endpoints=240.0.12.183:2379,240.0.2.168:2379 endpoint status -w table
{"level":"warn","ts":"2021-07-12T11:21:30.905Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///240.0.12.183:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection closed"}
Failed to get the status of endpoint 240.0.12.183:2379 (context deadline exceeded)
{"level":"warn","ts":"2021-07-12T11:21:35.906Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///240.0.2.168:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection closed"}
Failed to get the status of endpoint 240.0.2.168:2379 (context deadline exceeded)
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

Need assistance on this issue

**Comment by javsalgar** [comment]
Did you try running the health command inside the pod or with an external client?

**Comment by abdennour** [comment]
same thing here. where should we set the arg `--quota-backend-bytes` ? 

REF: https://etcd.io/docs/v3.3/dev-guide/limit/

**Comment by carrodher** [comment]
In the following links you can take a look at the different options available to restore/backup etcd:

- [List of parameters in the README](https://github.com/bitnami/charts/tree/master/bitnami/etcd#snapshotting-parameters)
- [Detailed section in values.yaml](https://github.com/bitnami/charts/blob/d63c26cff705339f54ab997b0dab721b43ed3e27/bitnami/etcd/values.yaml#L676)
- [Documentation](https://github.com/bitnami/charts/tree/master/bitnami/etcd#backup-and-restore-the-etcd-keyspace)

Please note there are some built-in features in the chart but other methods can be done just using the etcd snapshot methods and providing a volume with the snapshot, in those cases we highly recommend checking forums and user guides made available by the project behind the application or the technology.
