### ISSUE TITLE
minio credentials broken

### ISSUE THREAD

**Issue by xriser** [bitnami/charts#6876]
**Which chart**:
minio 7.1.1

**Describe the bug**
The new version of minio using new environment variables for authentification
MINIO_ROOT_USER
MINIO_ROOT_PASSWORD
instead of MINIO_ACCESS_KEY MINIO_SECRET_KEY

https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#envvar.MINIO_ACCESS_KEY

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this. I am creating an internal task to update this.
  I can see in the link you provided that the mentioned environment variables are deprecated but not removed, so they should still work.
  I tested the provided `docker-compose-distributed.yml` that set the user and password and it worked for me.
  Is it broken for you ?

**Comment by xriser** [comment]
It doesn't work in K8s

**Comment by rafariossaa** [comment]
Hi,
  Could you detail how are you setting the the values and deploying the chart ?  I would like to try to reproduce the issue.

**Comment by xriser** [comment]
I have successfully setup v7.1.3 and it is works fine.
Just complains at start
`14:14:38.26 
 14:14:38.26 Welcome to the Bitnami minio container
 14:14:38.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 14:14:38.26 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 14:14:38.26 
 14:14:38.27 INFO  ==> ** Starting MinIO setup **
 14:14:38.29 INFO  ==> Starting MinIO in background...
 14:14:48.29 INFO  ==> Adding local Minio host to 'mc' configuration...
 14:14:48.52 INFO  ==> Stopping MinIO...
 14:14:48.76 INFO  ==> ** MinIO setup finished! **

 14:14:48.79 INFO  ==> ** Starting MinIO **
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD

 You are running an older version of MinIO released 2 weeks ago 
 Update: Run `mc admin update` 

`
but works
Thank you for support.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing your findings.
