### ISSUE TITLE
Not possible to use existing pvc with dokuwiki

### ISSUE THREAD

**Issue by lboclboc** [bitnami/charts#6891]
**Which chart**:
dokuwiki-11.1.7.

**Is your feature request related to a problem? Please describe.**
The current helm version will either create a pvc or use empty dir if persistence is enabled. But what if you want to use an existing pvc, or delete the release and run it again but keep the pvc. 

**Describe the solution you'd like**
I would like to have a persistence.existingClaim value that the release can use as PVC

**Describe alternatives you've considered**
Haven't really find a way. Even if you disable persistence it will create an emptyDir volume

**Additional context**
N.A.

**Comment by migruiz4** [comment]
Hi @lboclboc,

Thank you for reporting this issue.

I have created this PR #6899  adding support for `persistence.existingClaim`.
Would that work for you?

**Comment by lboclboc** [comment]
Thanks, that would be perfect. 

Regards Lars​

Den 9 juli 2021 08:44, kI 08:44, Miguel Ruiz ***@***.***> skrev:
