### ISSUE TITLE
Any planning for postgres 12+ ?

### ISSUE THREAD

**Issue by dharmendrakariya** [bitnami/charts#6900]
**Which chart**:
[bitnami/postgres]

**Is your feature request related to a problem? Please describe.**
We want Postgres version 12+ for our gitlab latest version(ie 14.05)!

**Describe the solution you'd like**
Updated chart would be helpful.

**Describe alternatives you've considered**
Planning to update the available version 12 on dockerhub ```bitnami/postgres```

**Comment by Mauraza** [comment]
Hi @dharmendrakariya, 

We will update but I can't give you an ETA, but you can find all the versions of PostgreSQL here https://github.com/bitnami/bitnami-docker-postgresql#supported-tags-and-respective-dockerfile-links. The last version 12 is already released.

**Comment by dharmendrakariya** [comment]
@Mauraza so is it straight forward to just change the image tag ? It won't break anything right?

**Comment by Mauraza** [comment]
Hi @dharmendrakariya,

The chart is for PostgreSQL 11 not for PostgreSQL 12, so if it could be break something.
