### ISSUE TITLE
error during helm repo add: INTERNAL_ERROR

### ISSUE THREAD

**Issue by aschleifer** [bitnami/charts#6903]
I occasionally see the following error:
```
helm repo add --force-update bitnami https://charts.bitnami.com/bitnami
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR
```

This is with helm3 against kubernetes 1.16 clusters. Most of the time a simple retry helps to fix this.

**Comment by rafariossaa** [comment]
Hi,
  I suspect this can be related to a DNS issue or that one of the IPs is failing for some reason.
  Could you try to download the index manually ?
```$ wget "https://charts.bitnami.com/bitnami/index.yaml"        
--2021-07-12 07:44:34--  https://charts.bitnami.com/bitnami/index.yaml
Resolving charts.bitnami.com (charts.bitnami.com)... 52.85.144.40, 52.85.144.43, 52.85.144.60, ...
Connecting to charts.bitnami.com (charts.bitnami.com)|52.85.144.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8648821 (8.2M) [binary/octet-stream]
Saving to: ‘index.yaml’

```
  Maybe it fails to you with some of the IPs, I tried several and it is working well for me, so maybe I didn't hit the one it is failing to you.

**Comment by aschleifer** [comment]
Hm I currently can't reproduce it. I tried to add the `--debug` flag to the command but I didn't see any debug output.

How many ips/nodes/pods are behind this domain (charts.bitnami.com)? if they aren't too many, maybe they could each be tested via curl directly to the IP with a host header?

**Comment by rafariossaa** [comment]
This is currently server  through cloudfront:
```
$ nslookup charts.bitnami.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
charts.bitnami.com      canonical name = d1xe8nqhpmcyfh.cloudfront.net.
Name:   d1xe8nqhpmcyfh.cloudfront.net
Address: 99.86.230.18
Name:   d1xe8nqhpmcyfh.cloudfront.net
Address: 99.86.230.116
Name:   d1xe8nqhpmcyfh.cloudfront.net
Address: 99.86.230.25
Name:   d1xe8nqhpmcyfh.cloudfront.net
Address: 99.86.230.21
```
Sometimes cloudfront have some issues in some of their nodes.

**Comment by aschleifer** [comment]
Hm then I guess it is hard to debug this. as it could be almost anywhere in the cloudfront network.

Since this is only a sporadic issue I'm fine with just closing the issue.

**Comment by rafariossaa** [comment]
Hi,
  Yes, I agree.
  I am closing the issue.
  Don't hesitate to open a new issue if you have further problems.
  Thanks.
