### ISSUE TITLE
Shared preload libraries like pg_cron is not working with bitnami/postgresql helmchart

### ISSUE THREAD

**Issue by cathyalex** [bitnami/charts#6916]
**Which chart**:
 bitnami/postgresql

**Describe the bug**
Shared libraries like pg_cron is not working with bitnami/postgresql helmchart

**To Reproduce**
1. Updated the below parameter in values.yaml file
    **postgresqlSharedPreloadLibraries: "pgaudit,pg_cron"**

2. Tried to create extension.
    **CREATE EXTENSION pg_cron;**

3. Got the below error. Seems like pg_cron control files and sql files are missing in the mentioned container path.
    **ERROR:  could not open extension control file "/opt/bitnami/postgresql/share/extension/pg_cron.control": No such file or directory**

4. Copied the pg_cron.control and pg_cron.sql files manually inside container using kubectl cp command as shown below.
**kubectl cp pg_cron.control pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring
kubectl cp pg_cron.sql pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring
kubectl cp pg_cron--1.0--1.1.sql pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring
kubectl cp pg_cron--1.0--1.1.sql pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring
kubectl cp pg_cron--1.1--1.2.sql pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring
kubectl cp pg_cron--1.2--1.3.sql pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring
kubectl cp pg_cron--1.3--1.4.sql pg-postgresql-0:/opt/bitnami/postgresql/share/extension/ -n monitoring**

5. Again tried creating extension and got the below error
**ERROR:  extension "pg_cron" has no installation script nor update path for version "1.4"**

**Expected behavior**
Shared preload libararies like pg_cron should load successfully without any errors and should be able to create a cron jobs with postgres.

**Version of Helm and Kubernetes**:
**- Output of `helm version`:**
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.7"}
**- Output of `kubectl version`:**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by rafariossaa** [comment]
Hi,
  Have into account that apart from those files you will also need the pg_cron bin file in lib directory.

**Comment by cathyalex** [comment]
Hi,
1.Getting the below error even after copying the "pg_cron.so" manually in the path -/opt/bitnami/postgresql/lib.
kubectl cp pg_cron.so pg-postgresql-0:/opt/bitnami/postgresql/lib -n monitoring

**ERROR: unrecognized configuration parameter "cron.database_name"CONTEXT: PL/pgSQL function inline_code_block line 3 at IF**

Please note that we could not install the postgres by adding the below pg_cron value in values.yaml file. 
**postgresqlSharedPreloadLibraries: "pgaudit,pg_cron"**
So we removed the 'pg_cron' value and started the postgres with only 'pgaudit' default value.
**postgresqlSharedPreloadLibraries: "pgaudit"**

Once postgres started, we copied the above mentioned .control files and .sql files in /opt/bitnami/postgresql/share/extension/ and pg_cron.so file in /opt/bitnami/postgresql/lib. Tried to create pg_cron extension, but still we are getting the same error.
**ERROR: unrecognized configuration parameter "cron.database_name"CONTEXT: PL/pgSQL function inline_code_block line 3 at IF**

2. Please let know if any other files need to be copied to any other path inside container apart from above mentioned files.

3. Also, let know if there is anyway to copy these files while starting the container via values.yaml file, instead of copying manually after the pod is started like i did above (kubectl cp).

4. If we create our own postgres image, how to use that image in values.yaml file. 
   For instance, we have a customized postgres image which includes pg_cron extension in our server, but we are not able to use the image from our server in the values.yaml file provided by bitnami.
   Tried to use the customized image as shown below but since 'registry' parameter default value is set to 'docker.io', it is not taking the image from server. It is showing image pull error. Tried changing the image pull policy to 'Never' as well.

image:
  #registry: docker.io
  #repository: bitnami/postgresql
  #tag: 12.7.0-debian-10-r47
  repository: custom-postgres
  tag: 1.0
  pullPolicy: IfNotPresent
 
Thanks

**Comment by rafariossaa** [comment]
Hi,
  Regarding 1 and 2, I am not sure if some other files are needed, maybe you can ask in pg_cron's forums.

> 3. Also, let know if there is anyway to copy these files while starting the container via values.yaml file, instead of copying manually after the pod is started like i did above (kubectl cp).

   I think the best way is to create your own image.

> 4. If we create our own postgres image, how to use that image in values.yaml file. ...

You need to push the image to a repository, and set that repository in the `repository` parameters in the values.yaml.
You can use a public repository, like dockerhub or set your own private repository.

**Comment by cathyalex** [comment]
ok thank you for the suggestion. Will try to use a customized image and proceed further.

**Comment by rafariossaa** [comment]
You are welcome. 
I am closing this issue. Please don't hesitate to reopen it, or to create a new one if needed.
