### ISSUE TITLE
Discourse with SSL Offloading via Load Balancer

### ISSUE THREAD

**Issue by FriedCircuits** [bitnami/charts#6932]
**Which chart**:
Discourse 4.2.3

**Describe the bug**
Long story short I found that the helm chart adds a port to the `DISCOURSE_HOST` in the configmap if the port is not `80`. In this case I am using 443 for SSL offloading on a AWS NLB. This breaks avatar images from working after you upload them. If I remove the port from the configmap directly on the cluster that fixes the issue. But any images uploaded before the change can't be used again. Even spent time trying to delete them from the file system and clearing assets and running precompile again. Spent way to much time on this. The problem is unless you change the SHA of an image you can never upload that image again. Even if I reverted the change but then images don't load. 

https://github.com/bitnami/charts/blob/131fa45f5fdf59adb3ddb00ca440143eff889260/bitnami/discourse/templates/configmaps.yaml#L14

Line 14 is where it adds the port in. From what I can gather there shouldn't be a port there at all, this value is just the hostname of the instance of discourse. 

I think removing that port should work. I can do a PR tomorrow if that won't break anything else?

**To Reproduce**

Use port 443 
1. deploy discourse
2. upload a logo, avatar, etc.
3. Edit the configmap to remove the extra port in DISCOURSE_HOST
4. Restart pod
5. Previous images don't show so clear and reupload and they still won't work
6. Change the image or upload a different image and those work fine

**Expected behavior**
Image/Avatars work out of the box, including profile menu icons etc. 

**Version of Helm and Kubernetes**:

Kubernetes 1.19 on EKS

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Using AWS Network load balancer with ACM on port 443

**Comment by alvneiayu** [comment]
hi @FriedCircuits 

I was investigating about this problem, I found this topic in Discourse. Could you test with the solution shared by the users, please?

https://meta.discourse.org/t/our-domain-name-changed-where-do-i-edit-the-hostname/104022/5

I am still investigating about this problem. Thanks a lot

Álvaro

**Comment by FriedCircuits** [comment]
Thanks for the link. We are in the middle of hackweek so I can't mess around now that it is working. I can probably mess with it more next week.

**Comment by alvneiayu** [comment]
hi @FriedCircuits 

No problem, I will wait. Let me know if you can solve the problem with this solution and if not I will try to help you.

Thanks a lot

Álvaro

**Comment by FriedCircuits** [comment]
I set up a new instance and used my local copy that does not set the port at the end of the `DISCOURSE_HOST` and everything worked fine in EKS with Ambassador ALB with SSL.

**Comment by alvneiayu** [comment]
hi @FriedCircuits

Sorry, I explained really bad. Could you test including the port, please? Just to verify that the problem persists.

Thanks a lot and sorry again.

Álvaro

**Comment by alvneiayu** [comment]
Hi @FriedCircuits 

I already included a change in our chart. Could you test it, please? Let me know if I solved your problem

Thanks a lot

Álvaro

**Comment by FriedCircuits** [comment]
I had a modified chart with the same exact change and it worked perfectly in a new environment.

**Comment by alvneiayu** [comment]
hi @FriedCircuits 

Perfect then, thanks a lot

Álvaro
