### ISSUE TITLE
[bitnami/external-dns] Add support for regex domain filter & exclusion

### ISSUE THREAD

**Issue by cikupin** [bitnami/charts#6934]
**Which chart**:
external-dns

**Is your feature request related to a problem? Please describe.**
Currently we cannot use regex-domain-filter on external-dns chart version 5.1.4. Meanwhile it's already supported on external-dns app version 0.8.0. 

- https://github.com/kubernetes-sigs/external-dns/blob/v0.8.0/main.go#L150
- https://github.com/kubernetes-sigs/external-dns/blob/v0.8.0/pkg/apis/externaldns/types.go#L373

**Describe the solution you'd like**
Please add regex domain filter parameters in the helm chart

```
regexDomainFilter: "your-regex-pattern"
regexDomainExclusion: "your-regex-pattern"
```

**Comment by pablogalegoc** [comment]
Hi @cikupin!

This would be a good addition to the asset! Would you be open to contributing this change via a PR? We'd be glad to review and help with the release 🙂

**Comment by cikupin** [comment]
@pablogalegoc sure, I'll submit the PR when it's finished

**Comment by cikupin** [comment]
Hi @pablogalegoc I've just added its PR above

**Comment by pablogalegoc** [comment]
Thank you very much @cikupin!
