### ISSUE TITLE
[bitnami/keycloak] - Mixed content behind ingress

### ISSUE THREAD

**Issue by rafaelbielawski** [bitnami/charts#6940]
hi everyone,

I'm having trouble connecting to the keycloak admin page, would it be a bug?

**Which chart**:
keycloak-4.0.2

**Describe the bug**
Mixed Content: The page at 'https://keycloak.dev.trademaster.com.br/auth/admin/master/console/' was loaded over HTTPS, but requested an insecure script 'http://keycloak.dev.trademaster.com.br/auth/js/keycloak.js?version=7a4is'. This request has been blocked; the content must be served over HTTPS

thanks

**Comment by rafaelbielawski** [comment]
solution:

extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.xxx"

**Comment by jonathan-strzalka-saggs** [comment]
I was able to get this working after reading the keycloak documentation, though I had to the following:

`
extraEnvVars:
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: FRONTEND_URL
      value: "https://keycloak.xxx"

ingress:
    servicePort: https
`

**Comment by miguelaeh** [comment]
Hi @jonathan-strzalka-saggs ,
Glad to hear that!

**Comment by jack1902** [comment]
For anyone else running into this, if you have something like LB -> Nginx -> keycloak then you might need to think about setting the `use-forwaded-headers=true` on nginx. I had it set to the default which was breaking keycloak for me when running behind an external LB

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers

**Comment by brsolomon-deloitte** [comment]
We have found that, in some situations, in addition to setting `KEYCLOAK_PROXY_ADDRESS_FORWARDING` and `KEYCLOAK_FRONTEND_URL`, you will also need to set a number of HTTP headers for Keycloak to indicate that it should be served over HTTPS. (Or more accurately, that HTTPS is what the downstream client originally requested).

- `X-Forwarded-Proto` -> https
- `X-Forwarded-Scheme` -> https
- `X-Forwarded-Port` -> 443

One setup where this applies is when using `ingress-nginx` with [TLS termination on the Network Load Balancer](https://kubernetes.github.io/ingress-nginx/deploy/#network-load-balancer-nlb). In this case, Nginx controller is sending a plain HTTP request to the backend (upstream) apps such as Keycloak. Without some wrangling of configuration, it will (inaccurately) send Keycloak `X-Forwarded-Proto: http`.

The steps to set these headers with `ingress-nginx` are described here:

https://github.com/kubernetes/ingress-nginx/issues/6358#issuecomment-1008902987

**Comment by sk880624** [comment]
Hi Guys,

Does anyone know how to fix it for Istio-Gateway and virtualservices setup which would be behind GCP Load Balancer (tls termination happens on Load Balancer)
