### ISSUE TITLE
Odoo - Embedding issue

### ISSUE THREAD

**Issue by nunodsfernandes** [bitnami/charts#6948]
**Which chart**:
bitnami/odoo

**Describe the bug**
While embedding the in a iframe, it displays error.

On the browser window:
![image](https://user-images.githubusercontent.com/75372015/125624851-8106df36-131e-4005-b4e2-bd508aeeae64.png)

On the browser inspect console:
```
Refused to display 'http://<app ip here>:31787/' in a frame because it set 'X-Frame-Options' to 'deny'.
```

Chart values:
| Parameter | Value |
| -- | -- |
| resources.limits.cpu | 500m |  
| persistence.enabled | false |  
| resources.limits.memory | 512Mi |  

Chart Services:
| Name | Ports | Type |
| -- | -- | -- |
| odoo-postgresql-headless | tcp-postgresql 5432 | ClusterIP |
| odoo-postgresql | tcp-postgresql 5432 | ClusterIP |
| odoo | http 80 | LoadBalancer |

**To Reproduce**

Not sure how you could reproduce this..

**Expected behavior**

Application could be opened embedded.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
No other context

**Comment by rafariossaa** [comment]
Hi,
  It doesn't seem to be a issue with the chart. I would suggest you to ask in odoo forums, I think they can provide better support in this kind of issue.

**Comment by nunodsfernandes** [comment]
@rafariossaa thanks, i'll look further.

**Comment by rafariossaa** [comment]
Hi,
  Thanks. Please, don't hesitate to come back and share your findings.

**Comment by nunodsfernandes** [comment]
Hi @rafariossaa 
Apparently, i don't need to chase them.
Application does not allow embedding, and it states it right on the error on `'X-Frame-Options' to 'deny'.`, so, yeah..
We can close this.

Thanks!
