### ISSUE TITLE
Bitnami/Thanos

### ISSUE THREAD

**Issue by zlee113** [bitnami/charts#6952]
I installed the bitnami [prometheus-operator and thanos](https://tanzu.vmware.com/developer/guides/kubernetes/prometheus-multicluster-monitoring/) onto a test cluster I have setup using the bitnami helm chart. I got the querier working perfectly fine, but for some reason I can't seem to the storegateway, minio, or compactor to not crash. 

For setting up the prometheus-operator:
        
        helm install prometheus-operator \
          --set prometheus.thanos.create=true \
          --set operator.service.type=ClusterIP \
          --set prometheus.service.type=ClusterIP \
          --set alertmanager.service.type=ClusterIP \
          --set prometheus.thanos.service.type=LoadBalancer \
          --set prometheus.externalLabels.cluster="data-producer-0" \
          bitnami/prometheus-operator

Thanos Values.yaml:
        
        objstoreConfig: |-
          type: s3
          config:
            bucket: thanos
            endpoint: {{ include "thanos.minio.fullname" . }}.monitoring.svc.cluster.local:9000
            access_key: minio
            secret_key: KEY
            insecure: true  
        querier:
          stores:
            - 10.233.55.59:10901
          LivenessProbe:
            initialDelaySeconds: 120
          ReadinessProbe:
            initialDelaySeconds: 120
        bucketweb:
          enabled: true
        compactor:
          enabled: true
        storegateway:
          enabled: true
        ruler:
          enabled: true
          alertmanagers:
            - http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
          config: |-
            groups:
              - name: "metamonitoring"
                rules:
                  - alert: "PrometheusDown"
                    expr: absent(up{prometheus="monitoring/prometheus-operator"})    
        minio:
          enabled: true
          Limits:
            memory: 2Gi
          Requests:
            cpu: 250m
            memory: 2Gi
          accessKey:
            password: "minio"
          secretKey:
            password: "KEY"
          defaultBuckets: "thanos"

After the setup I created pv's for each and bound them to the pvc, and then the storegateway, minio, and compactor all get into crashloops. 

Compactor logs:

        level=info ts=2021-07-14T17:13:06.32072261Z caller=factory.go:46 msg="loading bucket configuration"
        level=info ts=2021-07-14T17:13:06.321866927Z caller=compact.go:363 msg="retention policy of raw samples is enabled" duration=720h0m0s
        level=info ts=2021-07-14T17:13:06.321937782Z caller=compact.go:366 msg="retention policy of 5 min aggregated samples is enabled" duration=720h0m0s
        level=info ts=2021-07-14T17:13:06.321954586Z caller=compact.go:369 msg="retention policy of 1 hour aggregated samples is enabled" duration=87600h0m0s
        level=info ts=2021-07-14T17:13:06.323745657Z caller=compact.go:537 msg="starting compact node"
        level=info ts=2021-07-14T17:13:06.323781029Z caller=intrumentation.go:48 msg="changing probe status" status=ready
        level=info ts=2021-07-14T17:13:06.32412707Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
        level=info ts=2021-07-14T17:13:06.32415996Z caller=http.go:63 service=http/server component=compact msg="listening for requests and metrics" address=0.0.0.0:10902
        level=info ts=2021-07-14T17:13:06.324581076Z caller=compact.go:942 msg="start sync of metas"
        level=info ts=2021-07-14T17:13:06.324940959Z caller=tls_config.go:191 service=http/server component=compact msg="TLS is disabled." http2=false
        level=error ts=2021-07-14T17:13:06.331281108Z caller=compact.go:469 msg="retriable error" err="compaction: sync: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=warn ts=2021-07-14T17:13:06.333238101Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="syncing metas: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:13:06.333284785Z caller=http.go:74 service=http/server component=compact msg="internal server is shutting down" err="syncing metas: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=error ts=2021-07-14T17:13:06.333367522Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:13:06.334570271Z caller=http.go:93 service=http/server component=compact msg="internal server is shutdown gracefully" err="syncing metas: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:13:06.334619517Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="syncing metas: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=error ts=2021-07-14T17:13:06.334738122Z caller=main.go:156 err="BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host\nsyncing metas\nmain.runCompact.func6\n\t/app/cmd/thanos/compact.go:380\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:75\nmain.runCompact.func12\n\t/app/cmd/thanos/compact.go:511\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\ncompact command failed\nmain.main\n\t/app/cmd/thanos/main.go:156\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"

Storegateway logs:

        level=info ts=2021-07-14T17:11:23.644602493Z caller=factory.go:46 msg="loading bucket configuration"
        level=info ts=2021-07-14T17:11:23.645348038Z caller=inmemory.go:172 msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=262144000 maxItems=maxInt
        level=info ts=2021-07-14T17:11:23.645903403Z caller=options.go:24 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
        level=info ts=2021-07-14T17:11:23.649334268Z caller=store.go:425 msg="starting store node"
        level=info ts=2021-07-14T17:11:23.649494116Z caller=store.go:360 msg="initializing bucket store"
        level=info ts=2021-07-14T17:11:23.649545631Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
        level=info ts=2021-07-14T17:11:23.649637389Z caller=http.go:63 service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:10902
        level=info ts=2021-07-14T17:11:23.650002822Z caller=tls_config.go:191 service=http/server component=store msg="TLS is disabled." http2=false
        level=warn ts=2021-07-14T17:11:23.656899055Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:11:23.656955264Z caller=http.go:74 service=http/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:11:23.657033877Z caller=intrumentation.go:48 msg="changing probe status" status=ready
        level=info ts=2021-07-14T17:11:23.657159382Z caller=grpc.go:123 service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:10901
        level=info ts=2021-07-14T17:11:23.658178304Z caller=http.go:93 service=http/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:11:23.658248257Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=warn ts=2021-07-14T17:11:23.658300226Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:11:23.658318523Z caller=grpc.go:130 service=gRPC/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=info ts=2021-07-14T17:11:23.658341445Z caller=grpc.go:143 service=gRPC/server component=store msg="gracefully stopping internal server"
        level=info ts=2021-07-14T17:11:23.658428932Z caller=grpc.go:156 service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
        level=error ts=2021-07-14T17:11:23.658640276Z caller=main.go:156 err="Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host\nBaseFetcher: iter bucket\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata\n\t/app/pkg/block/fetcher.go:377\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch.func2\n\t/app/pkg/block/fetcher.go:438\ngithub.com/golang/groupcache/singleflight.(*Group).Do\n\t/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20200121045136-8c9f03a8e57e/singleflight/singleflight.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/app/pkg/block/fetcher.go:436\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/app/pkg/block/fetcher.go:497\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/app/pkg/store/bucket.go:437\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/app/pkg/store/bucket.go:506\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:362\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/app/pkg/store/bucket.go:507\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:362\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nbucket store initial sync\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:364\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nstore command failed\nmain.main\n\t/app/cmd/thanos/main.go:156\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"

Minio logs:

         17:12:46.52 
         17:12:46.53 Welcome to the Bitnami minio container
         17:12:46.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
         17:12:46.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
         17:12:46.53 
         17:12:46.53 INFO  ==> ** Starting MinIO setup **
         17:12:46.56 INFO  ==> Starting MinIO in background...
         17:12:56.57 INFO  ==> Adding local Minio host to 'mc' configuration...
         17:12:56.64 INFO  ==> MinIO is already stopped...

I've just begun learning Thanos, and Kubernetes in general so I don't have a great grasp on everything, but thanks for any response and let me know if you need any additional info!

**Comment by zlee113** [comment]
If you want to replicate the issue the kube-state-metrics was also not working and I had to edit the deployment and set hostNetwork to false as well.

Now the pods looks like the following:

        NAME                                                      READY   STATUS             RESTARTS   AGE
        alertmanager-prometheus-operator-alertmanager-0           2/2     Running            0          12d
        grafana-757f8985dd-8vpxw                                  1/1     Running            0          12d
        prometheus-operator-kube-state-metrics-68b686db75-7c746   1/1     Running            0          25h
        prometheus-operator-node-exporter-4w4pn                   1/1     Running            0          12d
        prometheus-operator-node-exporter-c87w4                   1/1     Running            0          12d
        prometheus-operator-node-exporter-jnrtm                   1/1     Running            0          12d
        prometheus-operator-operator-7fdd58ddc9-4bvtg             1/1     Running            0          12d
        prometheus-prometheus-operator-prometheus-0               4/4     Running            1          12d
        thanos-bucketweb-568fb56c4c-bgpz6                         1/1     Running            0          138m
        thanos-compactor-54ffdfd686-6v4lc                         0/1     CrashLoopBackOff   31         138m
        thanos-minio-84db747946-hwfmz                             0/1     CrashLoopBackOff   29         130m
        thanos-query-864cf79dcb-cqr67                             1/1     Running            0          138m
        thanos-query-frontend-8559fbfcb9-spj9c                    1/1     Running            0          138m
        thanos-ruler-0                                            1/1     Running            0          138m
        thanos-storegateway-0                                     0/1     CrashLoopBackOff   31         138m

**Comment by pablogalegoc** [comment]
Hi @zlee113!

I think the problems you are facing are related, if MinIO can't start then Compactor can't find it:
```bash
level=error ts=2021-07-14T17:13:06.331281108Z caller=compact.go:469 msg="retriable error" err="compaction: sync: BaseFetcher: iter bucket: Get \"http://thanos-minio.monitoring.svc.cluster.local:9000/thanos/?location=\": dial tcp: lookup thanos-minio.monitoring.svc.cluster.local on 169.254.25.10:53: no such host"
```
In my case MinIO is starting without issues with your configuration. In which environment are you setting up the cluster? Have you tried removing the limits and requests fields from MinIO and see if it still fails? Let me know! Once we got this out of the way the other problems should be _easier_ 🙂

**Comment by zlee113** [comment]
Hey @pablogalegoc !

So I retried it removing the requests and limits fields and unfortunately same issue. Also I did not setup the cluster personally but I do know it was done using kubespray and the version is 1.21.1.

**Comment by pablogalegoc** [comment]
Hi again @zlee113,
Sorry for the late response, let’s add under the minio configuration in the `values.yaml`  a
```yaml
image:
  debug: true
```
to enable the debug mode and see if we can get a hint of what’s causing the container to fail
