### ISSUE TITLE
[bitnam/postgresql] Allow ability to create services for each read-replica

### ISSUE THREAD

**Issue by deefdragon** [bitnami/charts#6954]
**Which chart**:
[bitnam/postgresql]

**Is your feature request related to a problem? Please describe.**
My program manages round-robin of read-replicas by itself. Currently, being forced to use one service, I end up using only as many read-replicas as I have pods, if I get lucky and the requests go to different replicas at all.

**Describe the solution you'd like**
the ability to create services for each read-replica

**Describe alternatives you've considered**
HA-postgresql may be an alternative, but I would still encounter the situation where I dont have individual connections, relying on pg-pool configuration.

**Comment by miguelaeh** [comment]
Hi @deefdragon ,
Thank you for the feature request. Would you like to create a PR adding it?

**Comment by deefdragon** [comment]
Assuming it would be accepted. Im not super familiar with helm charts, but ill give it a try.
Would adding a `range` over the number of read replicas in the svc-read.yaml file work (inside an if enabled of course.)? Basically duplicating the existing service, but with numbered names?

**Comment by miguelaeh** [comment]
Hi @deefdragon ,
We do that in other charts like kafka, you can check how we implement it for example [here](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/svc-external-access.yaml).
I would create a new file for this feature and ensure the normal service is not created when this feature is enabled, so you remove the need of counting the replicas, i.e. enabling the content of one file adding several services or the current file only.
Let me know if you have any doubt. Thanks!!

**Comment by deefdragon** [comment]
> ensure the normal service is not created when this feature is enabled

I was actually planning on leaving the default read service enabled because then someone who only sometimes needs to manage the read-only directly, can still rely on the default service to take care of not overloading one. I'll add an option for disabling it tho.

Thanks for the example. I will take a look in a week or so and see if I can get something working.

**Comment by deefdragon** [comment]
Should I put the new variables under 
- `readReplicas.service.unique` and `readReplicas.service.single` or 
- `replication.uniqueServices` and `replication.singleService` ?

I am leaning the latter as that appears to be where the control points for replication are, where as readReplicas.X appears to be for customization of the created components.

**Comment by deefdragon** [comment]
Also, is there any particular reason that we don't have podManagementPolicy set to parallel for the read replicas? I really don't see a reason as to why they need to be spun up in order.

**Comment by javsalgar** [comment]
Thank you for the PR! We will check it and provide feedback. AFAIK I see no reason for changing the PodManagementPolicy, but I'm not sure if that would break upgrades because of immutable fields.
