### ISSUE TITLE
Access Denied: https://charts.bitnami.com/bitnami

### ISSUE THREAD

**Issue by BoBiene** [bitnami/charts#6955]
**Which chart**:
All

**Describe the bug**
I receive a "Accedd Denied" when i try to use the Helm Chart repository under Access Denied: https://charts.bitnami.com/bitnami

**To Reproduce**
helm dep update or navigate to https://charts.bitnami.com/bitnami with the browser.

![image](https://user-images.githubusercontent.com/23037659/125742467-afeef4ed-342f-4c1f-b999-e885dafc60e0.png)

**Comment by migruiz4** [comment]
Hi @BoBiene,

The charts repository is not intended to be accessed using the web browser.

You need to install Helm (https://helm.sh/) and add the Bitnami repository as it follows:

```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```

Then, you can search all the applications available in the repository using:
```console
$ helm search repo bitnami
```

And deploy an applications in your Kubernetes using:
```console
$ helm install my-release bitnami/<package-name>
```

You can find more information here: https://github.com/bitnami/charts#before-you-begin

**Comment by BoBiene** [comment]
ok, i faced this error during helm dep up:

````
Downloading redis from repo https://charts.bitnami.com/bitnami

Downloading mongodb from repo https://charts.bitnami.com/bitnami

Save error occurred:  could not find : chart rabbitmq not found in https://charts.bitnami.com/bitnami: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR

Deleting newly downloaded charts, restoring pre-update state

Error: could not find : chart rabbitmq not found in https://charts.bitnami.com/bitnami: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR
````

it is gone now. So maybe there was some server / network issues.
