### ISSUE TITLE
[bitnami/fluentd] aggregator is a statefulset and not daemonset

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#6959]
Hi,

This line is saying daemonset, when it is really a statefulset. 
https://github.com/bitnami/charts/blob/87c43a2aa61f0e756f2f6be2092eb3e2c5997894/bitnami/fluentd/values.yaml#L494

Best regards,
Ruba

**Comment by pablogalegoc** [comment]
Hi @nc-ruth!

Thanks for flagging this! I'll open a PR to fix it 🙂
