### ISSUE TITLE
[bitnami/kibana] wordpress is mentioned but why?

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#6960]
Hi Bitnami,

This line contains the word "wordpress", and I assume it is a copy/paste error, and has nothing to do with Kibana.
https://github.com/bitnami/charts/blob/87c43a2aa61f0e756f2f6be2092eb3e2c5997894/bitnami/kibana/values.yaml#L163

Best regards,
Ruba

**Comment by pablogalegoc** [comment]
Hi @nc-ruth!

Thanks for flagging this! I'll open a PR to fix this also 🙂
