### ISSUE TITLE
mongodb chart: specify that externalAccess applies only for replica-set

### ISSUE THREAD

**Issue by Andrei-Stepanov** [bitnami/charts#6981]
Hello,

```
helm search repo bitnami/mongodb --versions                           
NAME                   	CHART VERSION	APP VERSION   	DESCRIPTION                                       
bitnami/mongodb        	10.22.0      	4.4.6         	NoSQL document-oriented database that stores JS...
```

https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L597

Has documentation:

```
## External Access to MongoDB(R) nodes configuration
##
externalAccess:
  ## @param externalAccess.enabled Enable Kubernetes external cluster access to MongoDB&reg; nodes
  ##
  enabled: false
```

But nowhere is stated that this is actual only for replica-set. Please add clarification that this applies only for replicaset architecture.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. As you spotted it, would you like to contribute with a PR?

**Comment by javsalgar** [comment]
PR created: https://github.com/bitnami/charts/pull/7135
