### ISSUE TITLE
Jenkins allow for selection of serviceAccount jenkins runs on.

### ISSUE THREAD

**Issue by jeffellin** [bitnami/charts#6983]
**Which chart**:
Jenkins 2.289.2 

**Is your feature request related to a problem? Please describe.**
When deploying jenkins recently with the bitnami chart, I ended up having to fork the chart so I could change the service account that the app runs on could be changed.  When using using Kubernetes as a build agent the user the service account uses must be able to launch pods.

**Describe the solution you'd like**
Allow specification of a specific service account in the container pod. 

**Additional context**

```
spec:
  serviceAccountName: kpack-deploy-sa

**Comment by Mauraza** [comment]
Hi @jeffellin,

We are open to contributions. If you have a fork would you like to create a PR with that change?

**Comment by jeffellin** [comment]
I don't at the moment, but I can certainly get one going.

**Comment by Mauraza** [comment]
Hi @jeffellin,

that would be great.
