### ISSUE TITLE
Scripts in docker-entrypoint-initdb.d do not get deployed for the mongodb chart

### ISSUE THREAD

**Issue by petilodie** [bitnami/charts#6985]
I'm using mongodb chart and trying to run init scripts to seed the database. I cloned the mongodb chart into my project folder and added a `files/docker-entrypoint-initdb.d` folder in it.

So the `import.sh` script is in the `/charts/mongodb/files/docker-entrypoint-initdb.d` folder.

I deploy the chart without problems. I then get a shell to the container and check the docker-entrypoint-initdb.d folder only to find out it's empty.

Is there something else that needs to be done to make this work? I may be following a wrong path, since I couldn't find a single example on how to use this with mongodb and tried the information shared under postgresql and mariadb.

**Comment by pablogalegoc** [comment]
Hi petilodie!

See if [Customize a new MongoDB instance](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#customize-a-new-mongodb-instance) is what you are looking for. In the case of `initdbScripts`, you can find an example on the `values.yaml` file:
https://github.com/bitnami/charts/blob/2a7003154f50945ef4f5bafcb331473881ca88b3/bitnami/mongodb/values.yaml#L267-L275
Let me know if you run into any issues
