### ISSUE TITLE
multi-arch images support (AMD/ARM) for metrics-server

### ISSUE THREAD

**Issue by tiwarisuraj9** [bitnami/charts#6988]
**Which chart**:
Metrics Server

**Is your feature request related to a problem? Please describe.**
Deploying metrics-server on ARM machines doesn't work.

**Comment by Mauraza** [comment]
Hi  @tiwarisuraj9,

Currently, our containers do not support the arm64 architecture. You can check this similar issue https://github.com/bitnami/charts/issues/5803 with a little more information about this.

**Comment by carrodher** [comment]
Hi all, we are more than happy to announce that from now on **the Bitnami container catalog is available as multi-arch in [Docker Hub](https://hub.docker.com/u/bitnami)** 🎉 🎉 

<img width="1293" alt="Screenshot 2023-02-24 at 08 16 50" src="https://user-images.githubusercontent.com/13216600/221133041-4499b10c-e57e-4756-b20c-69867a97fb5c.png">

This means you don’t need to specify anything when pulling the container images from [Docker Hub](https://hub.docker.com/u/bitnami), Docker (or any other software) will automatically pull the container image matching the host platform from which the pull command was issued.

[Here](https://blog.bitnami.com/2023/02/bitnami-arm-containers-available-at.html) you can find more info about this announcement.

-----

As usual, please create a new GitHub issue if you would like to report any bug or problem or directly contribute by creating a PR. [Here](https://github.com/bitnami/containers/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
