### ISSUE TITLE
[bitnami/redis] Improve wording around Redis Sentinel in redis README

### ISSUE THREAD

**Issue by jiyoon-koo** [bitnami/charts#6996]
**Which chart**:
[redis](https://github.com/bitnami/charts/tree/master/bitnami/redis)

**Is your feature request related to a problem? Please describe.**
Not a problem, just a suggestion on README wording :)

Under [Choosing between redis helm chart and redis-cluster helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redis#choose-between-redistm-helm-chart-and-redistm-cluster-helm-chart), it states:

```While RedisTM Helm Chart will deploy a master-slave cluster using RedisTM Sentinel...```

The first part of this sentence makes it appear that `Redis` helm chart will deploy with Redis Sentinel by default, but `sentinel.enabled` is false by default, if you scroll down to the [Sentinel parameter section](https://github.com/bitnami/charts/tree/master/bitnami/redis#redistm-sentinel-configuration-parameters)

![image](https://user-images.githubusercontent.com/12419157/126241373-adefa3b3-0b24-404e-9ebe-7f10f720f9c6.png)

**Describe the solution you'd like**
Perhaps a better wording could be 
```While RedisTM Helm Chart will deploy a master-slave cluster, with the option of enabling RedisTM Sentinel``` ? 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alemorcuq** [comment]
Thanks, @jiyoon-koo. Are you interested in contributing with a PR?

**Comment by jiyoon-koo** [comment]
[Here](https://github.com/bitnami/charts/pull/7005) is the PR. Thanks for allowing me to contribute! 😄
