### ISSUE TITLE
Interacting with bitnami spark cluster in Jupyter produces strange behavior

### ISSUE THREAD

**Issue by lambertsbennett** [bitnami/charts#7001]
**Which chart**:
bitnami/spark, version spark-5.6.1.tgz

**Describe the bug**
After deploying to kubernetes cluster I am able to connect to my spark instances through PySpark, however when I try to run a simple read.csv I get the following. (Code included)

![image](https://user-images.githubusercontent.com/46295426/126326610-8ead93b2-c6e7-43df-bba6-fe37b8c25357.png)

When I check the spark UI I see the following:

![image](https://user-images.githubusercontent.com/46295426/126326799-0df0d29a-b5d6-423a-9345-11ed76ec653b.png)

This happens forever as the operation just hangs. It seems that it continues to start executors and then kill them. Some operations appear as 'completed', but in the jupyter notebook the message of 'initial job has not accepted any resources ...' continues to be spit out. 

The same problem occurs when I try to submit an example pyspark script included with spark. 

**To Reproduce**
1. Install helm chart.
2. Connect to cluster as shown in code above **or**
3. Run kubectl command shown as output when spark is installed via helm with a python example. 

**Expected behavior**
I connect to spark cluster and am able to run interactive analyses in Jupyter.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+vmware.1", GitCommit:"9a9f80f2e0b85ce6280dd9b9f1e952a7dbf49087", GitTreeState:"clean", BuildDate:"2021-01-19T22:59:52Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Additional context**
We are using a Tanzu grid cluster. 

Thanks for any information.

**Comment by pablogalegoc** [comment]
Hi @lambertsbennett!

I'll try to reproduce the issue and will get back to you in case I found what could be causing it or need more information

**Comment by lambertsbennett** [comment]
Great thanks @pablogalegoc !

**Comment by pablogalegoc** [comment]
Hi again @lambertsbennett,

> [...] or run kubectl command shown as output when spark is installed via helm with a python example

I'm running the default installation of the Spark chart and using the output command with with `pi.py` which would be something like:
```
kubectl exec -ti --namespace default spark-worker-0 -- spark-submit --master spark://spark-master-svc:7077 \
    --class org.apache.spark.examples.SparkPi \
    examples/src/main/python/pi.py 5
```
If I grep the output I get the result correctly: `Pi is roughly 3.139160`

Could you confirm if that fails in your case?

**Comment by lambertsbennett** [comment]
Hi @pablogalegoc, this example does work for me.

**Comment by lambertsbennett** [comment]
@pablogalegoc using the above approach the sql examples work as well. This is not the command listed as the standard output when the chart is installed though. Using that command was what caused strange behaviour.

```
kubectl run --namespace ds spark-client --rm --tty -i --restart='Never' \
    --image docker.io/bitnami/spark:3.1.2-debian-10-r18 \
    -- spark-submit --master spark://$SUBMIT_IP:7077 \
    --deploy-mode client \
    --class org.apache.spark.examples.SparkPi \
    examples/src/main/python/pi.py 5
```

**Comment by pablogalegoc** [comment]
>This is not the command listed as the standard output when the chart is installed though

Could you share the `values.yaml` that you are using for the chart installation? By installing with `helm install spark bitnami/spark` I got the above command (although with a `spark-examples_2.12-3.1.2.jar` instead of `pi.py`). I may have misunderstood you at the beginning, sorry.

**Comment by lambertsbennett** [comment]
My values.yaml:

```yaml
worker:
  replicaCount: 4
  autoscaling:
    enabled: true
service:
  type: LoadBalancer
``` 

Sorry the example actually has a java jar as you mention, but I changed it to try a python example. Because pyspark doesn't work in cluster mode  I also specify client mode instead of cluster mode.

**Comment by pablogalegoc** [comment]
@lambertsbennett Finally I've been able to reproduce your issue. I'll set aside some time today to investigate further since I'm not really an expert on Spark, thank you very much for your patience

**Comment by lambertsbennett** [comment]
@pablogalegoc thanks very much all of your help!

**Comment by pablogalegoc** [comment]
@lambertsbennett there's always someone with the same issue: https://github.com/bitnami/charts/issues/2946#issuecomment-658574054
Didn't try it on a jupyterhub notebook but I can confirm that running
```
kubectl run --namespace ds spark-client --rm --tty -i --restart='Never' \
    --image docker.io/bitnami/spark:3.1.2-debian-10-r18 \
    -- /bin/bash
```
checking the pod IP and then running
```
spark-submit --master spark://spark-master-svc:7077 \
    --conf spark.driver.host=$POD_IP \
    --deploy-mode client \
    --class org.apache.spark.examples.SparkPi \
    examples/src/main/python/pi.py 5
```
I finally could get the `Pi is roughly 3.139160` again

**Comment by jmmoreu** [comment]
Hi! I am having the same issue experienced by @lambertsbennett. I was able to run the commands provided by @pablogalegoc properly but I am not sure what to do next in order to run pyspark from jupyter notebook...

Please, can anyone provide more detail on what should be done next? Does the jupyter-notebook instance need to fulfill any requirements?

**Comment by sunscorch** [comment]
> Hi! I am having the same issue experienced by [@lambertsbennett](https://github.com/lambertsbennett). I was able to run the commands provided by [@pablogalegoc](https://github.com/pablogalegoc) properly but I am not sure what to do next in order to run pyspark from jupyter notebook...
> 
> Please, can anyone provide more detail on what should be done next? Does the jupyter-notebook instance need to fulfill any requirements?

I think the problem is pretty same to mine, I try to deploy pyspark in another pod , but when use pyspark to connect spark master service it will show 
```
25/07/13 21:12:10 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
25/07/13 21:12:25 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
```
the problem is that I found in the worker , it will connect the spark driver in host name , but the issue is that we don't have any DNS record for my pod in the K8S cluster. so I try to enforece the driver host using IP (otherwise it will the driver host name)


`pyspark --master spark://my-spark-master-svc:7077  --conf spark.driver.host=10.244.2.56
`

from my understanding, you should add the try to enforce the driver host to be your juptyer notebook pod IP
from pyspark.sql import SparkSession
from pyspark import SparkConf, SparkContext


```
conf = (
    SparkConf()
    .setMaster("spark://my-spark-master-svc:7077")
    .setAppName("MyApp")
    .set("spark.driver.host", "<your-jupyter-pod-ip>")
)


spark = SparkSession.builder \
    .config(conf=conf) \
    .getOrCreate()

df = spark.range(10)
df.count()

```
