### ISSUE TITLE
Upgrade cluster from stable chart

### ISSUE THREAD

**Issue by shiranpoz** [bitnami/charts#7002]
**Which chart**:
bitnami/rabbitmq:8.17.0 (RabbitMQ v3.8.19)

**Describe the bug**
I have a rabbitmq cluster with 3 replicas on GCE deployed with the stable\rabbitmq chart.
Seeing as the chart is deprecated and and it's readme suggests using the bitnami chart we have tried to upgrade with the chart stated above (via helm upgrade) with minimal downtime.

After the upgrade the new STS has created new PVCs with new PVs and has not retained any data.
I couldn't find a way to reuse the Volumes.
Is there a method to reuse the volumes in a Helm upgrade between the charts? 
If there isn't what is the best way to migrate the data while minimizing down time?

**To Reproduce**

1. Install stable\rabbitmq chart on GCE with StorageClass that has provisioner: kubernetes.io/gce-pd.
2. Try to upgrade with bitnami chart with compatible values from previous step.
    ```helm upgrade <RELEASE_NAME> bitnami/rabbitmq -f values.yaml```
3. Try to access a previously existing queue.

**Expected behavior**
Expected the Upgrade to retain the data.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-gke.2200", GitCommit:"57abd34107618fca2a09cf95bee535fa0c27c1dc", GitTreeState:"clean", BuildDate:"2021-06-11T09:25:45Z", GoVersion:"go1.15.12b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I tried to use the name override value as well as some other methods to reuse the volumes after the first attempts but it was unsuccessful for different reasons, mostly trying to change immutable fields.

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the upgrade between the stable/rabbitmq and bitnami/rabbitmq will not be that straightforward, as it has been a year a half since it was deprecated. The cleanest solution that comes to mind would be to spin up a new RabbitMQ cluster and migrate the data between the two clusters. This guide should be helpful https://www.rabbitmq.com/backup.html

**Comment by shiranpoz** [comment]
Alright thank you. We'll probably just do it this way and bite the bullet on the down time.
