### ISSUE TITLE
Add the startupProbe parameter value support

### ISSUE THREAD

**Issue by isfong** [bitnami/charts#7008]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/kafka

**Is your feature request related to a problem? Please describe.**
 k8s livenessProbe strangle the pod

**Describe the solution you'd like**
Add the startupProbe parameter value support

**Describe alternatives you've considered**

**Additional context**

**Comment by alvneiayu** [comment]
hi @isfong 

Thanks a lot for your feature request, we are open to receive PRs and I will be really happy to review it.

Thanks a lot

Álvaro
