### ISSUE TITLE
[bitnami/mediawiki] Does helm chart support SMTP endpoints that do not require authentication?

### ISSUE THREAD

**Issue by rednevals** [bitnami/charts#7016]
**Which chart**: mediawiki version 12.3.4

**Describe the bug**
In a recent [issue(#97)](https://github.com/bitnami/bitnami-docker-mediawiki/issues/97) and resulting [PR(#98)](https://github.com/bitnami/bitnami-docker-mediawiki/pull/98) that I authored for the **bitnami-docker-mediawiki**, a change was made to fully support SMTP endpoints that **do not** require authorization parameters(_username/password_). How is this supported using the Helm chart and **values.yaml**?

**Expected behavior**
With docker-compose, I am able to set the environment variables as shown below:

```
      - MEDIAWIKI_SMTP_HOST=<our-smtp-host>
      - MEDIAWIKI_SMTP_HOST_ID=<our-smtp-domain>
      - MEDIAWIKI_SMTP_PORT=25
      - MEDIAWIKI_ENABLE_SMTP_AUTH=no
```
This resulted in the following code being appended to the deployed LocalSettings.php:

```
# Configure SMTP server
$wgSMTP = array(
'host' => <our-smtp-host>',
'IDHost' => '<our-smtp-domain>',
'port' => 25,
'username' => '',
'password' => '',
'auth' => false
);
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alvneiayu** [comment]
hi @rednevals 

I think that you are looking for the key extraEnvVars. With this key, you can define all the env variables that you want to set up inside the Mediawiki container. You can see how to do it inside the values.yaml:

https://github.com/bitnami/charts/blob/f3d2497a3d8706b80a191323959adcdfe5980a23/bitnami/mediawiki/values.yaml#L123

and also in the Readme

https://github.com/bitnami/charts/tree/master/bitnami/mediawiki#adding-extra-environment-variables

I think that this is what are you looking for no?

Let me know if I can help you with something else.

Thanks a lot

Álvaro

**Comment by rednevals** [comment]
I could add this one extra parameter as you describe, but I'm not sure the chart will make use of it. The current assumption is that the SMTP server always requires credentials, which is not the case. In order to fix this in the Docker Compose scenario, changes were made to remove the hard coded value of **MEDIAWIKI_ENABLE_SMTP_AUTH**. Now you can specify **yes** or **no**. At deploy time, the scripts save this to the MediaWiki configuration parameter **$wgSMTP.auth** as **true**/**false**, instead of the original hard coded value of **true**. Now Mediawiki will ignore the username/password values as they are not required in this case.

With the Helm chart, we are in the same situation. It supports all of the Mediawiki SMTP parameters except  **$wgSMTP.auth**:

### Mediawiki SMTP parameters

| Name                 | Description                                                          | Value                 |
| -------------------- | -------------------------------------------------------------------- | --------------------- |
| `smtpHost`           | SMTP host                                                            | `nil`                 |
| `smtpPort`           | SMTP port                                                            | `nil`                 |
| `smtpHostID`         | SMTP host ID                                                         | `nil`                 |
| `smtpUser`           | SMTP user                                                            | `nil`                 |
| `smtpPassword`       | SMTP password                                                        | `nil`                 |

I can see where they are processed starting here: https://github.com/bitnami/charts/blob/c443ded691a1184a72af7b812759fad54b240ae9/bitnami/mediawiki/templates/deployment.yaml#L102

Are you saying that I can add/inject a new parameter in **_values.yaml_** as SMTP_AUTH, and it will appear in the generated LocalSettings.php?

```
# Configure SMTP server
$wgSMTP = array(
'host' => <our-smtp-host>',
'IDHost' => '<our-smtp-domain>',
'port' => 25,
'username' => '', # <= NOT USED
'password' => '',  # <= NOT USED
'auth' => false
);
```

It looks like the chart needs some changes to enable that...

**Comment by rednevals** [comment]
@alvneiayu It appears that there are other parameters not being loaded from a custom **values.yaml** when it is used to install a MediaWiki release. I set the following in my **values.yaml**(_helm install test-wiki -f values.yaml bitnami/mediawiki_):

```
mediawikiUser: test
...
mediawikiPassword: tester1234
...
mediawikiName: "RNDC Wiki"
```

Only **mediawikiPassword** is set. So, I can login using the default(user) with the new password. The others values are not set. But, they can be manually set using 'helm upgrade ...' after the initial release.  Can anyone explain this inconsistency in how values are loaded from **values.yaml**?

**Comment by rednevals** [comment]
I must be missing something...

With a local image registry installed (registry:2), I have deployed a custom Docker image of bitnami/mediawiki. I can deploy this using Docker from the local registry without issue. When I configure **values.yaml** to point to this image and attempt to create a Helm release, it is ignored and the default image is pulled from docker.io as before.

```
...
image:
  registry: localhost:5000
  repository: rndc-mediawiki
  tag: latest
...
```
The resulting node is using this image: **docker.io/bitnami/mediawiki:1.36.1-debian-10-r0** instead. Actually, this is not even the latest release. It must be the latest that docker.io has. I was hoping to use the latest that includes my recent PR changes.

Any help in understanding how to utilize **values.yaml** would be greatly appreciated.

**Comment by pablogalegoc** [comment]
Hi @rednevals, I'll try to address all your questions, let me know if I forget something:

> I could add this one extra parameter as you describe, but I'm not sure the chart will make use of it

Right now it should, yesterday a new release updated the container image tag and set one that already includes the new `MEDIAWIKI_ENABLE_SMTP_AUTH` parameter https://github.com/bitnami/charts/blob/90c81ac55e7b35709b04ea551bc54a40453ce630/bitnami/mediawiki/values.yaml#L56

So setting it like this should work

```yaml
extraEnvVars:
  - name: MEDIAWIKI_ENABLE_SMTP_AUTH
    value: no
```
On our part, now we should probably add a `smtpEnableAuth` parameter or similar to the `values.yaml`

> After digging further, it looks like the chart is not handling any of the SMTP parameters

You are absolutely right, the chart is setting
https://github.com/bitnami/charts/blob/c443ded691a1184a72af7b812759fad54b240ae9/bitnami/mediawiki/templates/deployment.yaml#L115
instead of `MEDIAWIKI_SMTP_USER` (same with the other SMTP parameters). I'll open a PR to address this inconsistency.
In the meantime you can modify those variable names in the deployment. Sorry about this!

> Only mediawikiPassword is set. So, I can login using the default(user) with the new password

I couldn't reproduce this behaviour with the latest version of the chart. Using `helm install test-wiki -f values.yaml bitnami/mediawiki` I see both `MEDIAWIKI_USERNAME` and `MEDIAWIKI_PASSWORD` with my custom values.

> The resulting node is using this image: docker.io/bitnami/mediawiki:1.36.1-debian-10-r0 instead

This is strange, you can try adding `--dry-run --debug` to the install command and probably find what is causing it.

**Comment by rednevals** [comment]
I pulled the latest bitnami/charts repo, and copied the values.yaml  file, re-adding my changes:
```
image:
  registry: docker.io
  repository: bitnami/mediawiki
  tag: 1.36.1-debian-10-r25

mediawikiPassword: tester1234
mediawikiName: Test Wiki
smtpHost: <our-smtp-host>
smtpHostID: <our-smtp-domain>
smtpPort: 25
extraEnvVars:
  - name: MEDIAWIKI_ENABLE_SMTP_AUTH
    value: no
```
A dry run with debug reports:
```
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/mediawiki
  tag: 1.36.1-debian-10-r25

mediawikiName: Test Wiki
mediawikiPassword: tester1234
smtpHost: <our-smtp-host>
smtpHostID: <our-smtp-domain>
smtpPort: 25
extraEnvVars:
- name: MEDIAWIKI_ENABLE_SMTP_AUTH
  value: false
```
I am now using the newer image.  These changed values are present in the  But as I suspected, none of the SMTP values make it into in the deployed **LocalSettings.php**. This code seems have not been executed as is done when deploying using docker-compose:

https://github.com/bitnami/bitnami-docker-mediawiki/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/libmediawiki.sh#L267 

Ihe emdiikiName is also not getting propogated. Injecting/processing of the SMTP parameters still needs some work.

**Bonus Issue:** I'm using Docker Desktop(Engine v20.10.7) with Kubernetes(v1.21.2) enabled. Every time I uninstall a Helm release I have to go into Docker Desktop and "Reset Kubernetes Cluster". If I don't, successive installs fail. Do you have any idea why this is> Maybe there are some remnants from the previous install/uninstall cycle left behind.

**Comment by pablogalegoc** [comment]
Hey @rednevals,

Double-checked the SMTP variables and, as they are right now in the chart, they should work because `SMTP_*` are declared as well as `MEDIAWIKI_SMTP_*`. If I set:
```yaml
smtpHost: smtpHosttest
smtpPort: 43243
smtpHostID: smtpHostIDtest
smtpUser: smtpUsertest
smtpPassword: smtpPasswordtest
```
and execute the following I see them set in `LocalSettings.php`
```bash
❯ kubectl exec -it pod/mediawiki-pod-id -- tail /bitnami/mediawiki/LocalSettings.php
$wgUsePathInfo = true;
// Configure SMTP server
$wgSMTP = array(
'host' => 'smtpHosttest',
'IDHost' => 'smtpHostIDtest',
'port' => 43243,
'username' => 'smtpUsertest',
'password' => 'smtpPasswordtest',
'auth' => true
);
```

> If I don't, successive installs fail. Do you have any idea why this is

I would check if there are PVCs bound from the previous installation, removing them should allow you to reinstall without issues

**Comment by rednevals** [comment]
I started from scratch, resetting the cluster and deleting the local image cache:
![image](https://user-images.githubusercontent.com/7444378/127154398-54300def-3918-48d3-9cf4-3ee1c88df4d4.png)

After installing the chart, I see that none of the SMTP values were appended:
![image](https://user-images.githubusercontent.com/7444378/127154206-88fe4cac-512c-4a62-8b92-b4d1eb370b56.png)

To get back to a truly clean state, what else do you suggest. I agree, it seems like there is something preventing it...

**Comment by rednevals** [comment]
I did find a clue. Looking at the release I see two pods deployed, and one marked as 'superseded'. Inspecting that one shows:
```
smtpHost:  <our-smtp-host>
smtpHostID:  <our-smtp-domain>
smtpPassword: null
smtpPort: 25
smtpUser: null
...
extraEnvVars:
- name: MEDIAWIKI_ENABLE_SMTP_AUTH
  value: false
```
Interesting. What would cause this to be **_superseded_**...

**Comment by rednevals** [comment]
Ok, I get it...

In the initial install the custom values get used. The successive **_upgrade_** to set the needed passwords causes all of the customizations in values.yaml to be replaced with the defaults. Looks like I missed adding '-f values.yaml ' to the upgrade step. That seems to have fixed my issue.

But, I still have to reset the cluster before re-install. The db starts but the wiki pod keeps restarting repeatedly.





```
$ helm history test-wiki 
REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION     
1               Tue Jul 27 10:25:03 2021        superseded      mediawiki-12.3.6        1.36.1          Install complete
2               Tue Jul 27 10:25:06 2021        deployed        mediawiki-12.3.6        1.36.1          Upgrade complete
```

**Comment by pablogalegoc** [comment]
@rednevals could you paste the output of `kubectl describe pod/mediawiki-pod-id` that is restarting?

**Comment by rednevals** [comment]
Fresh boot and cluster start... steps:

1. Install test-wiki
2. Uninstall test-wiki
3. Re-install test-wiki

Both pods continuously restart their respective containers. If I reset the cluster, I can reinstall the chart without error.

MariaDB:
```
Name:         test-wiki-mariadb-0
Namespace:    default
Priority:     0
Node:         docker-desktop/192.168.65.4
Start Time:   Thu, 29 Jul 2021 09:31:45 -0400
Labels:       app.kubernetes.io/component=primary
              app.kubernetes.io/instance=test-wiki
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mariadb
              controller-revision-hash=test-wiki-mariadb-9564d774
              helm.sh/chart=mariadb-9.3.17
              statefulset.kubernetes.io/pod-name=test-wiki-mariadb-0
Annotations:  checksum/configuration: 0c9d765cf36f30282aa5023b434326efbea42e691bba8726fa03aaf3375862ab
Status:       Running
IP:           10.1.1.153
IPs:
  IP:           10.1.1.153
Controlled By:  StatefulSet/test-wiki-mariadb
Containers:
  mariadb:
    Container ID:   docker://37359dd9686af4987bfb1594284e18725c3b0cdc65eaba916d364cb64a313ef4
    Image:          docker.io/bitnami/mariadb:10.5.11-debian-10-r0
    Image ID:       docker-pullable://bitnami/mariadb@sha256:160902dddb9c7d9640dcfc33ae0dbbed9346f786eeb653fa1b427c76f4673126
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 29 Jul 2021 09:43:00 -0400
      Finished:     Thu, 29 Jul 2021 09:43:03 -0400
    Ready:          False
    Restart Count:  7
    Liveness:       exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [/bin/bash -ec password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:          false
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'test-wiki-mariadb'>  Optional: false
      MARIADB_USER:           bn_mediawiki
      MARIADB_PASSWORD:       <set to the key 'mariadb-password' in secret 'test-wiki-mariadb'>  Optional: false
      MARIADB_DATABASE:       bitnami_mediawiki
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ngl2m (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-test-wiki-mariadb-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      test-wiki-mariadb
    Optional:  false
  kube-api-access-ngl2m:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15m                default-scheduler  Successfully assigned default/test-wiki-mariadb-0 to docker-desktop
  Normal   Pulled     13m (x5 over 15m)  kubelet            Container image "docker.io/bitnami/mariadb:10.5.11-debian-10-r0" already present on machine
  Normal   Created    13m (x5 over 15m)  kubelet            Created container mariadb
  Normal   Started    13m (x5 over 15m)  kubelet            Started container mariadb
  Warning  BackOff    5s (x73 over 15m)  kubelet            Back-off restarting failed container
```

Mediawiki:
```
Name:         test-wiki-mediawiki-68d586cd5b-fxkrs
Namespace:    default
Priority:     0
Node:         docker-desktop/192.168.65.4
Start Time:   Thu, 29 Jul 2021 09:31:52 -0400
Labels:       app.kubernetes.io/instance=test-wiki
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mediawiki
              helm.sh/chart=mediawiki-12.3.6
              pod-template-hash=68d586cd5b
Annotations:  <none>
Status:       Running
IP:           10.1.1.154
IPs:
  IP:           10.1.1.154
Controlled By:  ReplicaSet/test-wiki-mediawiki-68d586cd5b
Containers:
  test-wiki-mediawiki:
    Container ID:   docker://1670d15c46e4f6cad544d1a3a93b06aceea3f564f2bde4921ebe6e11d5ea6281
    Image:          localhost:5000/rndc-mediawiki:latest
    Image ID:       docker-pullable://localhost:5000/rndc-mediawiki@sha256:ce6e26130f5959d76b7a41158cfe97c055ed4f307377a8d02a63217887c4e46d
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 29 Jul 2021 09:45:08 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 29 Jul 2021 09:41:09 -0400
      Finished:     Thu, 29 Jul 2021 09:42:22 -0400
    Ready:          False
    Restart Count:  6
    Requests:
      cpu:      300m
      memory:   512Mi
    Liveness:   http-get http://:http/api.php%3Faction=query&meta=siteinfo&format=none delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/api.php%3Faction=query&meta=siteinfo&format=none delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      ALLOW_EMPTY_PASSWORD:         yes
      MARIADB_HOST:                 test-wiki-mariadb
      MARIADB_PORT_NUMBER:          3306
      MEDIAWIKI_DATABASE_NAME:      bitnami_mediawiki
      MEDIAWIKI_DATABASE_USER:      bn_mediawiki
      MEDIAWIKI_DATABASE_PASSWORD:  <set to the key 'mariadb-password' in secret 'test-wiki-mariadb'>  Optional: false
      MEDIAWIKI_HOST:               localhost
      MEDIAWIKI_USERNAME:           user
      MEDIAWIKI_PASSWORD:           <set to the key 'mediawiki-password' in secret 'test-wiki-mediawiki'>  Optional: false
      MEDIAWIKI_EMAIL:              user@example.com
      MEDIAWIKI_WIKI_NAME:          RNDC Wiki
      SMTP_HOST_ID:                 rndc-usa.com
      SMTP_HOST:                    relay1.rndc-usa.com
      SMTP_PORT:                    25
      MEDIAWIKI_ENABLE_SMTP_AUTH:   no
    Mounts:
      /bitnami/mediawiki from mediawiki-data (rw,path="mediawiki")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zvrhj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mediawiki-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-wiki-mediawiki-mediawiki
    ReadOnly:   false
  kube-api-access-zvrhj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned default/test-wiki-mediawiki-68d586cd5b-fxkrs to docker-desktop
  Normal   Pulled     11m (x3 over 14m)     kubelet            Container image "localhost:5000/rndc-mediawiki:latest" already present on machine
  Normal   Created    11m (x3 over 14m)     kubelet            Created container test-wiki-mediawiki
  Normal   Started    11m (x3 over 14m)     kubelet            Started container test-wiki-mediawiki
  Warning  BackOff    10m (x4 over 11m)     kubelet            Back-off restarting failed container
  Warning  Unhealthy  4m15s (x24 over 13m)  kubelet            Readiness probe failed: Get "http://10.1.1.154:8080/api.php?action=query&meta=siteinfo&format=none": dial tcp 10.1.1.154:8080: connect: connection refused
```

**Comment by rednevals** [comment]
@pablogalegoc I did notice that MariaDB left behind a PV with an attached PVC. After deleting this I was able to reinstall. Shouldn't that be able to be reused?

**Comment by pablogalegoc** [comment]
> I did notice that MariaDB left behind a PV with an attached PVC. After deleting this I was able to reinstall. Shouldn’t that be able to be reused?

If you try again install+uninstall+reinstall but this time setting the following parameters in the `values.yaml`:
```yaml
mariadb:
  image:
    debug: true
```
You’ll probably see the same error message as me when reinstalling:
```
❯ kubectl logs pod/mediawiki-mariadb-0
[...]
2021-07-29 22:18:03 3 [Warning] Access denied for user ‘root’@‘localhost’ (using password: YES)
```
Setting `mariadb.auth.rootPassword` and `mariadb.auth.password`, you should be able to reuse the volume. This is also why `helm upgrade` requires both parameters. If you leave blank both, the chart will generate random ones and reinstallation/upgrade will break because they do not match.

**Comment by rednevals** [comment]
@pablogalegoc Thanks for the info. This is the final piece of the puzzle for me...
