### ISSUE TITLE
Cannot upgrade helm if the password comes from global.redis.password

### ISSUE THREAD

**Issue by gildas** [bitnami/charts#7018]
**Which chart**:
It affects charts version ~14.3 

**Describe the bug**
When you use the redis chart as a dependency of another chart and you store the redis password in `global.redis.password`, you cannot run `helm upgrade` later on.

**To Reproduce**

1. create your own chart.
2. Add Bitnami's redis in the dependencies
3. In your  `config.yaml`, configure the password with:  
```yaml
global:
  redis:
    password: s3cr3t
```
4. Run `helm install --values config.yaml ...`, everything goes fine
5. Make changes in your chart, and produce a new version.
6. run `helm upgrade --values config.yaml ...`, Bitnami's Helm  chart will complain about missing credentials although they are set in the global section.

**Expected behavior**
Bitnami's Helm Chart should upgrade fine without complaining as the credentials ARE supplied.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-34+984a1cd176537e", GitCommit:"984a1cd176537e2d36d7db36e49e787e1c42a0aa", GitTreeState:"clean", BuildDate:"2021-06-11T05:08:05Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. I spotted the issue with the passwords. In the NOTES.txt file, line 180, instead of 

```
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
```
It should be

```
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) (not .Values.global.redis.password) -}}
```
As you were the one that detected the issue, would you like to submit a small PR with the fix? If not, we will work on it.

**Comment by gildas** [comment]
@javsalgar, sure I will do that tomorrow or so.
