### ISSUE TITLE
[nginx-ingress] Nginx ingress restarting

### ISSUE THREAD

**Issue by knyttl** [bitnami/charts#7020]
**Which chart**:
nginx-ingress-controller:0.47

**Describe the bug**
We have five controller replicas set with default helm values:

```
NAME                                                              READY   STATUS    RESTARTS   AGE
nginx-prod-nginx-ingress-controller-6b8c57bf5f-89m7d              1/1     Running             3          6d17h
nginx-prod-nginx-ingress-controller-6b8c57bf5f-cmz97              1/1     Running             0          6d17h
nginx-prod-nginx-ingress-controller-6b8c57bf5f-dh9q6              1/1     Running             11         6d17h
nginx-prod-nginx-ingress-controller-6b8c57bf5f-kjzxq              1/1     Running             0          6d17h
nginx-prod-nginx-ingress-controller-6b8c57bf5f-qndtz              1/1     Running             0          6d17h
```

You can notice the restart count on two of the pods.

`describe pod` on the first (which restarted two minutes before) says:

```
  Type     Reason     Age                    From                      Message
  ----     ------     ----                   ----                      -------
  Warning  Unhealthy  2m47s (x31 over 5d4h)  kubelet                   Readiness probe failed: Get http://10.24.4.106:10254/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2m46s (x24 over 5d4h)  kubelet                   Liveness probe failed: Get http://10.24.4.106:10254/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Normal   Killing    2m46s (x3 over 5d4h)   kubelet                   Container controller failed liveness probe, will be restarted
  Warning  Unhealthy  108s (x9 over 5d4h)    kubelet                   Readiness probe failed: HTTP probe failed with statuscode: 500
  Normal   Created    105s (x4 over 6d17h)   kubelet                   Created container controller
  Normal   Pulled     105s (x3 over 5d4h)    kubelet                   Container image "docker.io/bitnami/nginx-ingress-controller:0.47.0-debian-10-r25" already present on machine
  Normal   RELOAD     44s (x2 over 95s)      nginx-ingress-controller  NGINX reload triggered due to a change in configuration
```

Is there a way to debug this? I always just notice this once the incident is just over (it lasts usually just few tens of seconds).

**To Reproduce**
I am not sure how to reproduce this, it happens in  our production setup with multiple nodes, tens of pods, the cause might be anything. I guess I need a way to debug this.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.17-gke.1901", GitCommit:"b5bc948aea9982cd8b1e89df8d50e30ffabdd368", GitTreeState:"clean", BuildDate:"2021-05-27T19:56:12Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I previiusly opened the issue here, but I was told it is not relevant: https://github.com/kubernetes/ingress-nginx/issues/7384

**Comment by rafariossaa** [comment]
Hi,
  This is not going to be easy to debug, there are too many causes that can produce this kind of issues.
  First of all, are you setting different values for the liveness/readiness than the provided ones ?
  Did you check the log of the pod ?  Maybe that can give some clues.
  Also, I would check the there is some relation between the restarted pods and the k8s nodes where they are deployed. It could happen that those k8s nodes are more loaded.

**Comment by knyttl** [comment]
> First of all, are you setting different values for the liveness/readiness than the provided ones ?

I did not change liveness/readiness, nor the requests/limits. This is default helm settings.

> Did you check the log of the pod ? Maybe that can give some clues.

Yes, there is nothing, no errors :/

> Also, I would check the there is some relation between the restarted pods and the k8s nodes where they are deployed

The nodes are constantly under 20 % load, so that should not be a problem.

> Readiness probe failed: HTTP probe failed with statuscode: 500

The strange thing is that this error is not logged, is there a way to
- get it logged
- somehow see the full 500 result

?

**Comment by rafariossaa** [comment]
> The nodes are constantly under 20 % load, so that should not be a problem.
Maybe it is memory an not CPU, or a network issue.


Did you tried to get previous logs with: `kubectl logs <podname> --previous` ? I think if it is a 500 error it should be in the nginx logs.

To get it logged I happen to me that you can use a custom liveness prove that curls the health url and write the output to a file in a persisted volume. You will need to add those to the chart.

**Comment by knyttl** [comment]
Debugging two different pods with --previous

1. https://gist.github.com/knyttl/401ff74f7e2ef352d68bebae9d6d6e00 - it seems it died very quickly
2. Has no errors in `--previous` logs and also grepping with `healthz` it yields no rows. Is the healthcheck logged?

**Comment by juan131** [comment]
Hi @knatsakis 

It seems the POD is receiving a `SIGTERM` signal, which is very likely related to some failing probes. Is your default backend up and ready (I'm assuming you installed the chart setting `defaultBackend.enabled=true`)?

> Is the healthcheck logged?

Yes, it's saved as a POD event. Indeed, you obtained the logs when you run the `helm describe pod ...` command:

```console
   Warning  Unhealthy  108s (x9 over 5d4h)    kubelet                   Readiness probe failed: HTTP probe failed with statuscode: 500
```

**Comment by knyttl** [comment]
> I'm assuming you installed the chart setting defaultBackend.enabled=true

I don't see this config in the chart, so it must be of default value. However, I can se the default backend existing and healthy:

```
nginx-prod-nginx-ingress-controller-6b8c57bf5f-89m7d              1/1     Running   3          11d
nginx-prod-nginx-ingress-controller-6b8c57bf5f-cmz97              1/1     Running   0          11d
nginx-prod-nginx-ingress-controller-6b8c57bf5f-dh9q6              1/1     Running   23         11d
nginx-prod-nginx-ingress-controller-6b8c57bf5f-kjzxq              1/1     Running   0          11d
nginx-prod-nginx-ingress-controller-6b8c57bf5f-qndtz              1/1     Running   0          11d
nginx-prod-nginx-ingress-controller-default-backend-677f65fdk95   1/1     Running   0          11d
```

> Yes, it's saved as a POD event.

I meant if I can see the HC calls in the pod log. Meaning - if I could see also the 200/500 in nginx logs and I could grep the individual HC calls.. It seems it is not there?

**Comment by juan131** [comment]
Hi @knyttl 

If you access the controller container and run a `ps aux`, you'll notice there are two main proceses:

```console
$ kubectl exec -it CONTROLLER-POD-NAME -- bash
I have no name!@ CONTROLLER-POD-NAME:/opt/bitnami/nginx-ingress-controller$ ps aux
1001           1  0.3  0.5 740864 38344 ?        Ssl  08:46   0:14 nginx-ingress-controller /nginx-ingress-controller --default-backend-service=kube-system/nginx-ingress-controller-default-backend --election-id=ingress-controller-leader --ingress-class=nginx --configmap=k
1001          21  0.0  0.4 157568 38160 ?        S    08:46   0:00 nginx: master process /usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf
```

The controller itself, and an NGINX process started by the controller. The process serving the `/health` endpoint (the one used in the probes) is the controller, NGINX is actually listening in the port 80:

```console
I have no name!@ CONTROLLER-POD-NAME:/opt/bitnami/nginx-ingress-controller$ curl http://127.0.0.1:10254/healthz
ok
I have no name!@ CONTROLLER-POD-NAME:/opt/bitnami/nginx-ingress-controller$ curl http://127.0.0.1/
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Therefore, to obtain more info in the logs about why it returns a 500 error, we need to increase the verbosity of the logs in the controller (this can be done through the `--v` flag). You can do so installing the chart with the values.yaml below:

```yaml
extraArgs:
  v: 5
```

Find more info at: https://kubernetes.github.io/ingress-nginx/troubleshooting/#debug-logging

Could you give that a try?

**Comment by knyttl** [comment]
I tried this, but it logs way tooooo much stuff and given the fact that this happens only once in a few days, the logs become completely unusable :/

**Comment by juan131** [comment]
Hi @knyttl 

You can also try with level 3 in the verbosity. Please play a little bit with different levels until you obtain the information you're looking for in the logs.
