### ISSUE TITLE
Keycloak - unable to use externalDatabase with an existing secret for the password

### ISSUE THREAD

**Issue by geoffo-dev** [bitnami/charts#7025]
**Which chart**:
Keycloak - v4.0.2

**Describe the bug**
When specifying that you wish to use an external database and try to specify an existing secret for the password, you are not able to. This appears to be an issue within the config-env-vars.yaml where the env variables are not set for the database if .Values.externalDatabase.existingSecret is specified. 

**To Reproduce**

1. Set .Values.postgresql.enabled = false
2. Add Values.externalDatabase.existingSecret = "xxxxx"
3. Add additional configuration such as "Values.externalDatabase.host"

**Expected behavior**
When specifiying the .Values.externalDatabase.existingSecret, it should use the configuration specified for the external database. 

However it appears to refer to a 'default' configuration and does tries to connect to the postgresql host.

I believe this is because in the block config-env-vars.yaml - it does not set the env vars if a secret is specified.

``` 
 {{- if (not .Values.externalDatabase.existingSecret) }}
  KEYCLOAK_DATABASE_HOST: {{ include "keycloak.databaseHost" . | quote }}
  KEYCLOAK_DATABASE_PORT: {{ include "keycloak.databasePort" . }}
  KEYCLOAK_DATABASE_NAME: {{ include "ç" . | quote }}
  KEYCLOAK_DATABASE_USER: {{ include "keycloak.databaseUser" . | quote }}
  {{- end }}
```

If I set the password directly within .Values.postgresql.password - this works fine

**Comment by migruiz4** [comment]
Hi @geoffo-dev,

I'm sorry for the inconvenience, but I think there's been some misunderstanding caused by the `externalDatabase.existingSecret` value, probably because its description is not very clear.

The `externalDatabase.existingSecret` is a reference to a secret containing the ExternalDatabase environment variables, and not only the database password:
https://github.com/bitnami/charts/blob/54b5946f7653ccf9781ae993617c7928c4a2e3ab/bitnami/keycloak/templates/statefulset.yaml#L255-L258

So, to use this value, you will need to create a secret containing the environment variables `KEYCLOAK_DATABASE_HOST`, `KEYCLOAK_DATABASE_PORT`, `KEYCLOAK_DATABASE_NAME`, `KEYCLOAK_DATABASE_USER`.

You could use the following command to create the secret:
```
kubectl create secret generic external-database-secret --from-literal=KEYCLOAK_DATABASE_HOST='host' --from-literal=KEYCLOAK_DATABASE_PORT='port' --from-literal=KEYCLOAK_DATABASE_NAME='pass' --from-literal=KEYCLOAK_DATABASE_USER='user'
```

**Comment by geoff-contino** [comment]
Hi @migruiz4,

No worries at all! :-) thank you for your help and getting back to me so quickly!

Ahhh I see - sorry I must admit I am not a helm/k8s ninja so I didnt realise that was what was going on! Is that the same for all the secrets? I was trying to do something similar with the auth.existingSecrets too - although this looks like a map from a secrets file...

Thanks again!

**Comment by migruiz4** [comment]
The `auth.existingSecret` is a bit different, in this case, you can provide a secret with your Keycloak passwords (Admin, management, database, TLS keystore and truststore)

I'd recommend having a look at the example:
```
  ## @param auth.existingSecret An already existing secret containing auth info
  ## e.g:
  ## existingSecret:
  ##   name: mySecret
  ##   keyMapping:
  ##     admin-password: myPasswordKey
  ##     management-password: myManagementPasswordKey
  ##     database-password: myDatabasePasswordKey
  ##     tls-keystore-password: myTlsKeystorePasswordKey
  ##     tls-truestore-password: myTlsTruestorePasswordKey
```

You only need to provide the keyMapping for the passwords you will use, for example:

- Your secret was created like this:
```
kubectl create secret generic keycloak-secret --from-literal=admin-password='pass1' --from-literal=management-password='pass2' --from-literal=database-password='pass3'
```
- Then, you would need to configure `auth.existingSecret` like this:
```
   existingSecret:
     name: keycloak-secret
     keyMapping:
       admin-password: admin-password
       management-password: management-password
       database-password: database-password
```

Hope it helps!

**Comment by geoffo-dev** [comment]
Thank you so much! super helpful! Really appreciate it :-)
