### ISSUE TITLE
[zookeeper] liveness probe succeeds even when zkServer is not running

### ISSUE THREAD

**Issue by samene** [bitnami/charts#7026]
**Which chart**:
bitnami/zookeeper 3.7.0

**Describe the bug**
```zkServer.sh status``` returns the server is not running but the liveness probe is successful and so the pod never restarts.

**To Reproduce**
```
I have no name!@zookeeper-1:/$ echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok
imok
I have no name!@zookeeper-1:/$ zkServer.sh status
/opt/bitnami/java/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
Client port found: 2181. Client address: localhost. Client SSL: false.
Error contacting service. It is probably not running.
I have no name!@zookeeper-1:/$
```

**Expected behavior**
Maybe change the liveness probe. If zkServer is not running then pod should be restarted.

**Version of Helm and Kubernetes**:
Helm 3.4
Kubernetes 1.21

**Comment by alvneiayu** [comment]
hi @samene 

We are open to receive PR. If you want to send us a PR modifying the LivenessProbe, we can evaluate the solution and we will be really happy to review the change.

Thanks a lot

Álvaro
