### ISSUE TITLE
[bitnami/zookeeper] Allow specifying keystore and truststore keys for existingSecrets

### ISSUE THREAD

**Issue by wiegandf** [bitnami/charts#7028]
**Which chart**:
bitnami/zookeeper 7.0.9

**Is your feature request related to a problem? Please describe.**
I want to use cert-manager for issuing certificates for zookeeper quorum tls communication. Using the `tls.quorum.autoGenerated` flag generates new certs for every helm upgrade. So I wanted to use my own certs (generated by cert-manager).

Cert-manager writes the keystore and truststore to a secret with fields keystore.jks and truststore.jks. But the helm chart requires it to be `zookeeper.keystore.jks` (see [statefulset.yaml](https://github.com/bitnami/charts/blob/907669f327d7b320119ae87b1fad539d26860eca/bitnami/zookeeper/templates/statefulset.yaml#L145)).

If that's not the case, the pod will fail within the init-certs container. What's the point of init-certs at all if using existing secrets? It's clashing with the option to specify custom keystorePath and truststorePath.

**Describe the solution you'd like**
Either we simply change to the more generic keys keystore.jks and truststore.jks or, even better, we introduce new fields that let you specify under which key the keystore and truststore can be found in the existingSecret.

**Describe alternatives you've considered**
As a workaround I have created a fake secret with empty trust and keystore so that init-certs container doesn't fail. The real trust and keystore are mounted via extraVolumes and extraVolumeMounts and are pointed to via `tls.quorum.keystorePath ` and `tls.quorum.truststorePath`

**Comment by rafariossaa** [comment]
Hi,
 Yes, you are right, there are some bugs there. I have created an internal task to look into them.
 The workaround you implemented is the right one in the current state. Thanks for mentioning it and for reporting this issue.

**Comment by gberl001** [comment]
It should probably also be mentioned that if autoGenerated is false, the container is looking specifically for jks files, it shouldn't matter what the keystore type is, previous ZK chart versions support multiple keystore types.

Applying this workaround from @wiegandf still works with PKCS12 since, as mentioned, the init-certs container doesn't really matter if you're supplying your own certs.

**Comment by rafariossaa** [comment]
Hi,
  Thanks @gberl001 for the info.
