### ISSUE TITLE
[bitnami/mongodb] Chart version 10.23.2 not available

### ISSUE THREAD

**Issue by MatushkaRossiya** [bitnami/charts#7029]
Newest version of the `mongodb` chart (10.23.2) seems to be not available from the repository, while the previous one (10.23.1) is.

**Comment by filipwiechowski-tomtom** [comment]
It appears that this version is now present in the chart repository, issue can be closed.

**Comment by MatushkaRossiya** [comment]
It appears that this version is now present in the chart repository, issue can be closed.

**Comment by MatushkaRossiya** [comment]
It appears that this version is now present in the chart repository, issue can be closed.
