### ISSUE TITLE
[bitnami/keycloak] Allow setting the Keycloak <web-context> in Helm chart

### ISSUE THREAD

**Issue by carolili** [bitnami/charts#7031]
**Which chart**:
[bitnami/keycloak](https://github.com/bitnami/charts/tree/master/bitnami/keycloak)

**Is your feature request related to a problem? Please describe.**
In order to change the `web-context` ([base path of where Keycloak is running](https://www.keycloak.org/docs/latest/server_installation/index.html#manage-subsystem-configuration)) from `/auth` to something else there seems to be two solutions available:

1. To create a custom image and edit the `web-context` (see https://github.com/bitnami/charts/issues/6774, UPDATE 3)
2. To provide a `configMap` that contains a full `standalone-ha.xml` configuration file for Keycloak.
 
The custom image solution is not ideal as it requires hosting and maintaining the custom image, and the `configMap` solution overrides any `standalone-ha.xml` configuration file changes set through the Helm chart.

**Describe the solution you'd like**
I would like to set the `web-context` using a parameter in the Helm chart. E.g.
```
web-context: my-custom-path/auth
```

**Describe alternatives you've considered**
Maybe this could alternatively be addressed by adding an environment variable to the Keycloak image that we can customize with an `extraEnv` in the Helm chart.

**Additional context**
None

**Comment by alvneiayu** [comment]
hi @carolili 

In this case, you have other option. If you don't want to set up a complete configuration using the configuration key inside values.yaml, we have a key called initdbScripts. You can set up this initdbScripts variable in values.yaml and you can execute specific bash commands.

To change this variable, Keycloak provides a .cli support to modify the web-context but we are working in an internal issue to support this kind of command. I think that the best workaround is to execute a sed command to modify the specific key in the standalone-ha.xml.

Let me know if this fixes your problem.

Thanks a lot

Álvaro
