### ISSUE TITLE
[bitnami/mongodb] Unable to setup MongoDB Replica-Set to use both ClusterIP services AND use DNS Replica-Set Members

### ISSUE THREAD

**Issue by zonnie** [bitnami/charts#7037]
**Which chart**:
MongoDB 10.20.0

**Describe the bug**
I'm trying to make my MongoDB replica-set use DNS names for members and not IP as IPs are ephemeral in k8s.
I'm unable to allow a service exposure (with `ClusterIP`) AND get the `replicaSetHostnames` enabled.
- I don't understand why this is not allowed
- How do I get service per MongoDB node exposed AND allow these DNS names to be used in the replica set configuration

**To Reproduce**

1. Use the following in `values.yaml`
```
externalAccess:
            enabled: true
...
replicaSetHostnames: true
```
2. `kubectl get pod mongodb-0 -o yaml`
3. The `env` **doesn't** contain the `MONGODB_ADVERTISED_HOSTNAME` variable to be injected into the container

**Expected behavior**
I should be able to have both
- Services per replica set instance with a `ClusterIP` (due to `externalAccess.enabled: true`)
- `MONGODB_ADVERTISED_HOSTNAME` to be injected into the bitnami MongoDB container

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.700", GitCommit:"8924a6876b2ff4905020e178132365eca3164869", GitTreeState:"clean", BuildDate:"2021-06-28T09:20:44Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
None

**Comment by pablogalegoc** [comment]
Hi @zonnie,

I'll cc/ @juan131 on this since he included this constraint in https://github.com/bitnami/charts/pull/2918 and I'm sure he is going to have more context on it

**Comment by juan131** [comment]
Hi @zonnie 

> **Expected behavior**
> 
> I should be able to have both
> 
> - Services per replica set instance with a `ClusterIP` (due to `externalAccess.enabled: true`)
> - `MONGODB_ADVERTISED_HOSTNAME` to be injected into the bitnami MongoDB container

I have question regarding this expected behaviour ⏫ . When you use `externalAccess.enabled=true`, only `NodePort` or `LoadBalancer` service types are allowed. I mean, it makes no sense to have one service per MongoDB replica if that service is not exposed outside the cluster.
Could you explain why did you choose `ClusterIP`?

On the other hand, when you set `replicaSetHostnames=true`, the `MONGODB_ADVERTISED_HOSTNAME` is set with the associated AAAA record for the POD since we're using a headless service (find more info about this topic in the [k8s documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods)). Why would like to se that env. variable with an **internal hostname** when you want to access MongoDB from outside the cluster?

**Comment by zonnie** [comment]
When you want to allow clients to access MongoDB replica set you need to specify all the instances addresses.
I need to access the replica set from inside the cluster by several clients - not sure what's so strange, why does the replica set need to be **only** accessible from the outside ?
To clarify - I don't need external access, just need to access the replica set from within the cluster via DNS.

**Comment by pablogalegoc** [comment]
@zonnie if you don't need access from outside the cluster, having `architecture=replicaset` and `replicaSetHostnames=true` will create a headless service that will make every replica reachable under 
```
$(MY_POD_NAME).$(K8S_HIDDEN_NODE_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.{{ .Values.clusterDomain }}
```
like
```
mongodb-0.mongodb-headless.default.svc.cluster.local
```

**Comment by zonnie** [comment]
@pablogalegoc but in which case can a MongoDB client access (i.e.) `mongodb-0.mongodb-headless.default.svc.cluster.local` - will this conform with MongoDB's protocol ? it expects to get a list of all nodes.

**Comment by pablogalegoc** [comment]
It should, once you install the chart you get the commands to run a pod with the mongo client and to connect to the replicaset. An example for two replicas:
```
mongo admin --host "mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```

**Comment by zonnie** [comment]
@pablogalegoc I tried this and it doesn't work from a different angle now.
When looking in MongoDB's configuration I expected to see the URLs similar to `mongodb-0.mongodb-headless.default.svc.cluster.local` but instead see IPs.

What does the MongoDB Helm + Docker do when `replicaSetHostnames=true` and `architecture=replicaset` ?
How are the members being injected to remain dynamic in MongoDB's `rs.conf` ?

For reference I'm getting
```
{
	"_id" : "gc_replica_set",
	"version" : 210718,
	"protocolVersion" : NumberLong(1),
	"writeConcernMajorityJournalDefault" : true,
	"members" : [
		{
			"_id" : 0,
			"host" : "10.68.17.98:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 5,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 1,
			"host" : "10.68.17.95:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatIntervalMillis" : 2000,
		"heartbeatTimeoutSecs" : 10,
		"electionTimeoutMillis" : 10000,
		"catchUpTimeoutMillis" : -1,
		"catchUpTakeoverDelayMillis" : 30000,
		"getLastErrorModes" : {

		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		},
		"replicaSetId" : ObjectId("60ed9f5da59a0c8a549b5578")
	}
}
```
These are literal IPs instead of DNS...

What am I missing ?

**Comment by pablogalegoc** [comment]
That’s strange, if I set `architecture: replicaset` (`replicaSetHostnames: true` is already the default) and use the commands in the release notes to log into a mongodb client I see this:
<pre>
rs0:PRIMARY> rs.conf()
{
	“_id” : “rs0",
	“version” : 3,
	“term” : 2,
	“protocolVersion” : NumberLong(1),
	“writeConcernMajorityJournalDefault” : true,
	“members” : [
		{
			“_id” : 0,
			“host” : <b>“mongodb-0.mongodb-headless.default.svc.cluster.local:27017"</b>,
			“arbiterOnly” : false,
			“buildIndexes” : true,
			“hidden” : false,
			“priority” : 5,
			“tags” : {
			},
			“slaveDelay” : NumberLong(0),
			“votes” : 1
		},
		{
			“_id” : 1,
			“host” : <b>“mongodb-arbiter-0.mongodb-arbiter-headless.default.svc.cluster.local:27017"</b>,
			“arbiterOnly” : true,
			“buildIndexes” : true,
			“hidden” : false,
			“priority” : 0,
			“tags” : {
			},
			“slaveDelay” : NumberLong(0),
			“votes” : 1
		},
		{
			“_id” : 2,
			“host” : <b>“mongodb-1.mongodb-headless.default.svc.cluster.local:27017"</b>,
			“arbiterOnly” : false,
			“buildIndexes” : true,
			“hidden” : false,
			“priority” : 1,
			“tags” : {
			},
			“slaveDelay” : NumberLong(0),
			“votes” : 1
		}
	],
</pre>
Are you setting any other parameter apart from those?

**Comment by lszxyz** [comment]
have the same problem, this is my values.yaml
```yaml
global:
  storageClass: "csi-rbd-sc"

architecture: replicaset

persistence:
  storageClass: "csi-rbd-sc"
  size: 4Gi
  resourcePolicy: "keep"

auth:
  rootUser: root
  rootPassword: "xxxx"

replicaCount: 2

externalAccess:
  enabled: true
  service:
    domain: mongodb
    type: NodePort
    nodePorts:
     - xxxxx
     - xxxxx
```
I had use helm template use compare use nodeport and clusterip，one more line in the configmap mongodb-scripts
```sh
export MONGODB_ADVERTISED_HOSTNAME=$MY_POD_HOST_IP
```
Will this cause this to not take effect? 
![image](https://github.com/bitnami/charts/assets/93818344/ca1218ad-e3a6-4bf1-96f6-77ac6a211a11)
