### ISSUE TITLE
redis: wrong documentation for pdb.create

### ISSUE THREAD

**Issue by mrksngl** [bitnami/charts#7043]
**Which chart**:
Redis 14.8.3

**Describe the bug**
File `values.yaml` contains documentation
```yaml
## @param pdb.create Specifies whether a ServiceAccount should be created
```

**To Reproduce**
Not applicable

**Expected behavior**
Should rather be `PodDisruptionBudget` instead of `ServiceAccount`

**Version of Helm and Kubernetes**:
Not applicable

**Comment by Mauraza** [comment]
Hi @mrksngl,

thanks for reporting! I just create a PR to fix it.
