### ISSUE TITLE
[bitnami/postgresql-ha] How to generically connect to the postgresql-ha cluster

### ISSUE THREAD

**Issue by martinatptc** [bitnami/charts#7056]
**Which chart**:
Bitnami posgresql-ha

**Describe the bug**
Documentation does not explain multicluster usage.

**To Reproduce**
Explained below.

**Expected behavior**
There should be a generic way to connect to the postgresql-ha cluster from outside (not just using ip address).

**Version of Helm and Kubernetes**:
All recent versions.

**Additional context**
Using minikubes for testing, I have created a postgresql-ha cluster using helm install the bitnami pg-ha chart.  So there is a postgresql-ha-pgpool deployment and service.  I changed the service to be Nodeport and specified the nodeport as 30100.  Now if i do kubectl describe pod <name of pgpool pod> i can see what the api of the pgpool node is.  For instance if the ip of the node is 192.168.39.37, then i can connect to the postgresdb from my app using host=192.168.39.37:30100.  

The host is running on another minikube.  Hardwiring this ip and port works so in theory this should be possible.  My deployment, once i have this working, would have two clusters deployed in a public cloud, with frontend app, and backend postgresql cluster.  The frontend talks to the backend by opening the postgresql connection.  

However I can't for the life of me figure out how to connect to the postgres cluster generically.  I can't just hardwire the ip address to the server (unless i use a static ip address from the cloud provider and somehow map it to the node address of the pgpool, but not really clear about these details either).   I have looked into different CNI plugins but does not seem so simple, tried using Skupper but this also doesn't seem to work for this use case (unless again i'm missing something on how to use Skupper).

**Comment by pablogalegoc** [comment]
Hi @martinatptc!

So you have your app in one Kubernetes cluster (which for development purposes is a Minikube) and the postgresql-ha chart installed on another cluster (another Minikube), right? Just to know, on which host OS are these Minikubes and which driver (`--driver` option) are you using to start them?

> However I can't for the life of me figure out how to connect to the postgres cluster generically

What do you mean by this? Using a domain name instead of an IP address? I'm not familiar with Skupper but it hints me that you are maybe trying setup "multicluster services"?.

Our charts are designed to be installed on one cluster (except for Thanos as far as I know) so having documentation on multicluster setups is somewhat out of scope but I'll try to help in what I can 🙂

**Comment by martinatptc** [comment]
Hey @pablogalegoc,

I'm using Ubuntu 16.04.6, and start minikube with kvm2 driver.

Yes, trying to setup multicluster.  Domain mapping seems like promising idea, didn't really need it though as backend cluster with postgres should only be accessed by frontend cluster (except if i'm debugging the backend cluster which i can do anyway using the connection options given by the Readme).

Yes, would be great if there were some other examples of this type of usage (multicluster, how to access the postgres cluster generically).

Thanks!

**Comment by martinatptc** [comment]
Trying to make this simpler and changing gears a little bit, I have recreated the configuration to have one single cluster (simulated with one minikube), with the the api server and postgresql-ha nodes all together.

I guess now i'd just like to connect generically to the postgres host, presumably pg_pool?  Obviuously i can't just hardwire an ip address.  So sort of same question applies, how can this be done?  (please let me know if i should paste the kubectl describe output for any of the resources involved).

**Comment by martinatptc** [comment]
Okay, i was able to get the one cluster case working (connection from within cluster) using <my release name>-postgresql-ha-postgresql-headless:5432

I still feel this would be a valid use case:  could the chart support external access somehow?

**Comment by pablogalegoc** [comment]
> could the chart support external access somehow?

Yes! External access can be either setting the service type to NodePort, as you already tried, or LoadBalancer. If by _generically connect to the cluster_ you mean via a domain name, depending on the load balancer provider it may also offer publishing a domain name for your service under their DNS servers. For something more advanced setups you probably should take a look at something like [external-dns](https://github.com/bitnami/charts/tree/master/bitnami/external-dns). Hope this is what you are looking for!

**Comment by martinatptc** [comment]
> > could the chart support external access somehow?
> 
> Yes! External access can be either setting the service type to NodePort, as you  
...
>For something more advanced setups you probably should take a look at >something like [external-dns]
>(https://github.com/bitnami/charts/tree/master/bitnami/external-dns). Hope >this is what you are looking for!

Thanks.  Yeah, finally have the basic use case of one big cluster working (and tested locally from my app), going forward I may just stick with the single cluster architecture but will still try using either external-dns or skupper as that should also work now that the proper handle to pg_pool (through the headless service, not sure why that works but I found this by basically trying everything until that did) is being used.

**Comment by pablogalegoc** [comment]
Happy to hear that, I'll close this issue but feel free to reopen it or a new one in case you face any extra issues
