### ISSUE TITLE
Kibana chart should have service account

### ISSUE THREAD

**Issue by jeff-hammel-leapyear** [bitnami/charts#7059]
**Which chart**:
The name (and version) of the affected chart.

Kibana latest

**Is your feature request related to a problem? Please describe.**

In order to give service accounts the fine-grained access control that they need and not just give the default service account permissions, a service account should be defined for a deployment's pods.  In the case of kibana, in some environments it needs the anyuid security context constraint.  We may not want to provide this to default, plus doing so may be blocked by auditing + infosec.

**Describe the solution you'd like**

Like the elasticsearch chart, for the kibana chart there should be a `serviceAccount` section with two key-values: name (string), and create (bool).  If not specified, the default service account may be used.

**Describe alternatives you've considered**

I think adding the above should be straightforward enough.  We're using the kibana subchart with `kibanaEnabled: true` from the elasticsearch chart, so things ShouldJustWork.  One alternative is not to use the kibana subchart and go with the official kibana chart from elasticsearch.

**Additional context**

We're installing on openshift and aiding openshift customers to do so.  They have infosec requirements that we do not control.

**Comment by alemorcuq** [comment]
Thanks for the PR, @jeff-hammel-leapyear!
