### ISSUE TITLE
Having another single service for externalAccess and clusterIP

### ISSUE THREAD

**Issue by jipe35** [bitnami/charts#7064]
**Which chart**:
mongodb: 10.23.4

**Is your feature request related to a problem? Please describe.**
Not a problem but the mongo uri would be more simple for application conf by addressing direclty a global service.

**Describe the solution you'd like**
You'd only have to add a Service before (or after) the range with the full name without the indice in mongodb/templates/replicaset/external-access-svc.yaml and mongodb/templates/replicaset/svc.yaml.

**Describe alternatives you've considered**

**Additional context**

**Comment by juan131** [comment]
Hi @jipe35 

I guess you're deploying MongoDB using a "replicaset" architecture, right? Please note that using the "standalone" architecture you can expose MongoDB through a single service and the configuration you described would be possible.

However, when using a "replicaset" architecture your application must know what node is playing the **primary** role, and what nodes are simply playing a **secondary** role.
The reason: only the **primary** node can receive write operations. Therefore, your application must send write queries exclusively to the **primary** node, while it can choose between any of the **secondary** nodes for read queries.

**Comment by jipe35** [comment]
Hi
I talked with one of our MongoDB experts in Orange. It’s right that we can only write on primary but if we specify replicaset in the uri, giving a global service will permit the driver to do the job.
What I didn’t know was that a service headless was also accessible based on its name, so my suggestion of service is not useful.

Regards

Jean-Philippe

**Comment by juan131** [comment]
Hi @jipe35

> It’s right that we can only write on primary but if we specify replicaset in the uri, giving a global service will permit the driver to do the job.

Please note a unique service loadbalancing the requests between every MongoDB node (both primary and secondary ones) won't have any mechanism to detect whether requests are write or read ones. How does the driver manage that?

> What I didn’t know was that a service headless was also accessible based on its name, so my suggestion of service is not useful.

What do you mean? Please note that headless services are meant to assign **internal** hostnames to the pods so each one has its own FQDN.

**Comment by jipe35** [comment]
Hi
My previous mail was only to clarify why I asked the evolution and I agree it was not useful.
See my answers lower.

Regards

Jean-Philippe

**Comment by juan131** [comment]
Thanks for the clarification @jipe35 ! I proceed to close the ticket but please feel free to reopen if you require further assitance.
