### ISSUE TITLE
[bitnami/oauth2-proxy] Deploying the chart with `authenticatedEmailsFile: true` cause an error in the deployment.yaml template file. 

### ISSUE THREAD

**Issue by Brulogaz** [bitnami/charts#7068]
**Which chart**:
bitnami/oauth2-proxy 0.1.2

**Describe the bug**
Deploying the chart with `authenticatedEmailsFile: true` cause an error in the `deployment.yaml` template file. The template adds an `items:` entry on https://github.com/bitnami/charts/blob/master/bitnami/oauth2-proxy/templates/deployment.yaml#L238 without the required `path` parameter, which cause a validation error when deploying  the chart.

The chart deploy without issues when the `authenticatedEmailsFile` property is set to `false`.  

**To Reproduce**
1. Populate the chart's required properties in the `values.yaml` file.
2. Set `authenticatedEmailsFile:` to `true`, instead of `false`.
3. Deploy the chart.

**Expected behavior**
The chart should deploy without validation errors.

**Comment by miguelaeh** [comment]
Hi @Brulogaz ,
Thank you very much for reporting this error.
The above PR should be fixing the issue.

**Comment by Brulogaz** [comment]
Thank you for merging the fix @miguelaeh !

I am experiencing a weird issue with the new published version though. It would seem that the tarball that has been published on https://charts.bitnami.com/bitnami/oauth2-proxy-0.1.4.tgz does not match what is currently on Github. The `version` in `Chart.yaml` is correct, but the rest of the chart appears to be out of date. 

This issue first popped on my Azure cluster while updating the chart, and downloading the tarball locally confirmed that the fix is indeed not included in the new archive.

It is really odd to be honest, my first intuition was that something is wrong on my end, but the fact that the tarball has the correct version but none of the recent yaml files let me believe that maybe a "rogue" version `0.1.4` previously existed on the tarball registry, though this is pure speculation on my part.

**Comment by miguelaeh** [comment]
Hi @Brulogaz ,
We are sorry for the inconveninece, I just checked and it seems there was some race condition that produced the issue. I will try to force a new run of the job in order to release the correct code.

**Comment by Brulogaz** [comment]
Version 0.1.5 appears to have been published with the correct code. Thank you!

**Comment by miguelaeh** [comment]
You're welcome!!
