### ISSUE TITLE
Rabbitmq -> Adding service.annotations

### ISSUE THREAD

**Issue by michelefa1988** [bitnami/charts#7073]
**Which chart**:
bitnami/rabbitmq 8.18.1

**Describe the bug**
I am trying to add run the rabbitmq and adding 2 service.annotations, however the chart throws an error and does not install. The problematic annotations is `beta.kubernetes.io/azure-loadbalancer-internal: true` (boolean is creating the problem)

**Command**
`helm upgrade --namespace rabbitmq-prod --install --values --set service.annotations.external-dns\.alpha\.kubernetes\.io\/hostname=rabbitmq.service.prod.net,service.annotations.beta\.kubernetes\.io\/azure-loadbalancer-internal=True --create-namespace --version=8.18.1 rabbitmq-prod bitnami/rabbitmq`

**Problem**
When running the above command,  I get an error 
`##[error]Error: UPGRADE FAILED: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|nternal":true,"exter|..., bigger context ...|"beta.kubernetes.io/azure-loadbalancer-internal":true,"external-dns.alpha.kubernetes.io/hostname":"r|...`

**Expected behavior**
The above command should work fine

- Output of `helm version`:

```
 v3.5.2
```

**Fix/ WorkAround**

After alot of tries I figure out that these two annotations can be added by using --set-string instead of --set. 

I do not think that this should be the case since I never needed to use --set-string on other charts

**Comment by alvneiayu** [comment]
hi @michelefa1988 

Could you test using quotes, please? Example:

```
helm template . --set "service.annotations.external-dns\.alpha\.kubernetes\.io\/hostname=rabbitmq.service.prod.net","service.annotations.beta\.kubernetes\.io\/azure-loadbalancer-internal=True" -s templates/svc.yaml
```

Thanks a lot

Álvaro
