### ISSUE TITLE
After reconstruct configsvr-0, configsvr replicaSet become two .

### ISSUE THREAD

**Issue by chungchaotsai** [bitnami/charts#7075]
**Which chart**:
The name (and version) of the affected chart
bitnami/mongodb-sharded/3.4.4

**Describe the bug**

while configsvr-1, configsvr2 working, and there is a primary.  configsvr-0 rebuild will build another replicaSet, and will show 
{“lastHeartbeatMessage” : “replica set IDs do not match, ours: xxx; remote node’s:xxx”}

**To Reproduce**

We set values.yaml configsvr replicas:3, pv/pvc was build by storageclass,
We run the chart for couple month and working smoothly. After 1 week ago we shutdown server and reboot , configsvr-1, configsvr-2 still contact each other and configsvr-2 is replica primary, but configsvr-0 abnormal to sync, we decide to rebuild configsvr-0, so we use kubectl delete pod, pv, and pvc, and kubernetes rebuild it automatically. 

configsvr-0 show log : “lastHeartbeatMessage” : “replica set IDs do not match, ours: xxx; remote node’s:xxx” , and command 
 rs.conf() on configsvr-0 and configsvr-2 get different replicaSetId.

configsvr-0 show it is a replica primary, and get only one member while command rs.status(), I think replicaSet become 2 while configsvr-0 initiate , so I edit replicaset-entrypoint.sh by configmap

```
if [[ $HOSTNAME =~ (.*)-0$ ]]; then
     ## export MONGODB_REPLICA_SET_MODE=primary
     export MONGODB_REPLICA_SET_MODE=secondary
     export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD="$MONGODB_ROOT_PASSWORD"
      unset MONGODB_ROOT_PASSWORD

```
Manual delete configsvr-0 pod,pv,pvc  and rebuild automatically, and configsvr become normal.

**Expected behavior**
while replicaSet exist, configsvr-0 do not build new replicaSet.

While exist 

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5fe16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by pablogalegoc** [comment]
Hi @chungchaotsai,

I've set the replicas of configsvr to 3 and did a fresh install of the chart, deleted the `pod/mongodb-sharded-configsvr-0` multiple times but it joins the replicaset correctly. The issue you are describing showed when I deleted the PVC, my guess is that it is trying to initialise another replicaset since it finds the data-dir empty:
https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/fcd9e78f5de5ba7128a2f008d07a77d68e3f4958/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L53-L54
If that's the case I don't think there's an easy way to solve it programatically. In fact it might be the best way to recover doing what you said, forcing the pod to start as secondary.

**Comment by chungchaotsai** [comment]
> Hi @chungchaotsai,
> 
> I've set the replicas of configsvr to 3 and did a fresh install of the chart, deleted the `pod/mongodb-sharded-configsvr-0` multiple times but it joins the replicaset correctly. The issue you are describing showed when I deleted the PVC, my guess is that it is trying to initialise another replicaset since it finds the data-dir empty:
> https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/fcd9e78f5de5ba7128a2f008d07a77d68e3f4958/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb-sharded.sh#L53-L54
> If that's the case I don't think there's an easy way to solve it programatically. In fact it might be the best way to recover doing what you said, forcing the pod to start as secondary.

I had delete the pvc for reasons I don't remember. But I think the path of replicaSet primary node should use a static file to info the new coming node where to join.

**Comment by pablogalegoc** [comment]
> But I think the path of replicaSet primary node should use a static file to info the new coming node where to join

Could you elaborate on this? Where would be that file and how would a new node know where to look for it? I think it would complicate the initialisation logic but maybe I'm missing something.
