### ISSUE TITLE
[rabbitmq][docs] Broken link on Artifacthub.io

### ISSUE THREAD

**Issue by carlosjgp** [bitnami/charts#7078]
The link to know more about scaling RabbitMQ is broken
https://docs.bitnami.com/kubernetes/infrastructure/rabbitmq/administration/scale-out/

https://artifacthub.io/packages/helm/bitnami/rabbitmq#scale-horizontally
![image](https://user-images.githubusercontent.com/1277613/127316591-4a5bd007-ba4b-4920-897e-9aab463917af.png)

**Comment by carrodher** [comment]
Thanks for letting us know, I just created the above PR fixing the link. Once released a new version of the chart, it should be automatically updated in the artifacthub since it is ingesting the README present in this repository. Thanks again
