### ISSUE TITLE
[bitnami/keycloak] Make the TLS key/crt file names configurable

### ISSUE THREAD

**Issue by michaeljmarshall** [bitnami/charts#7086]
**Which chart**:
bitnami/keycloak: version 4.0.3

**Is your feature request related to a problem? Please describe.**
I would like to configure TLS with existing certs, but I am finding the helm chart does not easily support certs created outside of the keycloak helm chart. I am using Cert-Manager to create certificates (and keystores/truststores). The current keycloak helm chart requires that the `.Values.auth.tls.existingSecret` have secret keys in the form of `keycloak-${ID}.key`, `keycloak-${ID}.crt`, and `ca.crt`. The `ca.crt` is standard, so that isn't an issue. However, I'm unable to get cert manager to create secrets with custom `keycloak-${ID}.key` and `keycloak-${ID}.crt` names. Further, cert manager will create a `keystore.jks` and a `truststore.jks` file, but these names are not configurable either.

Here is the relevant template: https://github.com/bitnami/charts/blob/38438c70afa090a5ac1733af724abfe7eb5f4fd9/bitnami/keycloak/templates/statefulset.yaml#L86-L114

Additionally, it's relevant to point out that because the `/cert` directory is mounted with limited file system permissions, it is not possible to create a keystore/truststore in an earlier init container and then have those stores used by keycloak.

In some cases, I would also like to use the host's default trusted ca certificate store, as the ca certs are for well know issuers.

**Describe the solution you'd like**
I am new to this helm chart, so I don't have a strong sense of what the "right" solution should be. Below, I share some ideas.

It could be possible to add a conditional block to the above `initContainer` where end users can supply the names of the `.key` and `.crt` files via the `.Values` file to use when creating the `truststore.jks` and the `keystore.jks`.

Similarly, the truststore and keystore file names could be configurable values supplied by end users.

**Comment by javsalgar** [comment]
Hi,

So, from what I read, it would be great if we could add values like these: `truststoreFilename` `keystoreFilename` and `caFilename`, so these could be configurable at any moment, could you confirm that?

**Comment by michaeljmarshall** [comment]
> So, from what I read, it would be great if we could add values like these: `truststoreFilename` `keystoreFilename` and `caFilename`, so these could be configurable at any moment, could you confirm that?

Those would be great. It'd also be great to add these two values: `keycloakCrtFilename` and `keycloakKeyFilename`.

**Comment by javsalgar** [comment]
Could you explain the difference of keycloakCrtFilename and keycloakKeyFilename compared to the truststore and keystore?

**Comment by bchrao** [comment]
Sorry for posting a Newbie question. What is the proper way to add certs to the truststore? We have 2 realms:
1 realm with ADFS (requires ADFS cert)
1 realm with Active Directory (private keycloak connectivity only) with LDAPS
We tried a couple ways like pv but could only get LDAPS working with -D javax options which broke SMTP with gmail.

**Comment by javsalgar** [comment]
Did you include your custom certificates in a secret? Could you also provide the settings you changed in the values.yaml file?

**Comment by bchrao** [comment]
So following info from charts/values.yaml:
`kubectl create secret generic keycloak-test-store --from-file=./keycloak.truststore.jks --from-file=./keycloak.keystore.jks -n namespace`
Our values.tpl.yaml:
```
auth:
  adminUser: admin
  adminPassword: ${admin_password}
  tls:
    enabled: true
    existingSecret: keycloak-test-store
    keystorePassword: ********
    trustStorePassword: *********
```
From init container:
`Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.`

**Comment by javsalgar** [comment]
Hi,

I think the issue is here:

```
            if [[ -f "/certs/keycloak.truststore.jks" ]] && [[ -f "/certs/keycloak-${ID}.keystore.jks" ]]; then
                cp "/certs/keycloak.truststore.jks" "/opt/bitnami/keycloak/certs/keycloak.truststore.jks"
                cp "/certs/keycloak-${ID}.keystore.jks" "/opt/bitnami/keycloak/certs/keycloak.keystore.jks"
            else
                echo "Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled."
                exit 1
            fi
```

It seems that it is doing an incorrect check with the ${ID} variable. @alvneiayu  could you check it?

**Comment by alvneiayu** [comment]
hi all

There are two different problems here. About the problem that you are reproducing @bchrao, it seems that you are not creating the secret as expected. Do it like this:

```
 kubectl create secret generic keycloak-test-store --from-file=./keycloak.truststore.jks --from-file=./keycloak-0.keystore.jks -n namespace
```
 
This is the command using the default values.yaml (replicaCount=1). If you increase the replicaCount you need to create a secret with replicaCount - 1 keystore files. Here you can find some explanation, inside the values.yaml:

https://github.com/bitnami/charts/blob/c10c7f4015d1ed0bf52ed10f9cd0cc6fb7d94910/bitnami/keycloak/values.yaml#L140

About the @michaeljmarshall problem. We are using the ID to set up different Keystore per pod. So, I think that the solution suggested by @javsalgar is a good one.

https://github.com/bitnami/charts/issues/7086#issuecomment-888951475

Let me take a look to find the best way to include those variables.

Thanks a lot

Álvaro

**Comment by michaeljmarshall** [comment]
> Could you explain the difference of keycloakCrtFilename and keycloakKeyFilename compared to the truststore and keystore?

A user can currently provide existing TLS certificates with the following value: `auth.tls.existingSecret`. The helm chart then converts those certificates into the keystore and the truststore in an init container. By allowing users to configure the `keycloakCrtFilename` and the `keycloakKeyFilename`, they can continue to use `auth.tls.existingSecret` without the requirement that secrets conform to a specific file name pattern.

I think the above functionality makes sense in addition to the truststoreFilename and the keystoreFilename because users might not have a truststore/keystore available in a secret.

> We are using the ID to set up different Keystore per pod. So, I think that the solution suggested by @javsalgar is a good one.

@alvneiayu - I agree the ID per pod is the root of this issue, thanks for putting together a PR.

**Comment by alvneiayu** [comment]
hi @michaeljmarshall 

The init container that we have inside our chart is only used with the autoGenerated key. We generate self signed certificates and then we transform those certificates to jks. If you want to use your own certificates, the only way (for auth) is to use secret with the jks. We don't have a support inside the chart to transform custom certs files mounted using secrets to jks. So I think that we the keys proposed by @javsalgar, you will have everything that you need to use cert-manager with our chart.

And your welcome about the PR. Waiting the review from my colleagues.

Thanks a lot

Álvaro

**Comment by michaeljmarshall** [comment]
@alvneiayu - makes sense, thanks for explaining.
