### ISSUE TITLE
[bitnami/redis-cluster]

### ISSUE THREAD

**Issue by antoineozenne** [bitnami/charts#7097]
**Which chart**:
redis-cluster 6.3.1

**Describe the bug**
Error when installing with `--set networkPolicy.ingressNSMatchLabels: foo`.

**To Reproduce**
Just install the chart with `--set networkPolicy.ingressNSMatchLabels: foo`.

**Additional context**
It seems to be an indentation error in line 46 in networkpolicy.yaml.

**Comment by juan131** [comment]
Thanks for reporting the issue @antoineozenne !! Creating a PR to address it.
