### ISSUE TITLE
[bitnami/kibana] did not provide the Elasticsearch external host or port in your 'helm install' call even though it is there

### ISSUE THREAD

**Issue by JustinGuese** [bitnami/charts#7105]
**Which chart**:
kibana

**Describe the bug**
Providing an external elastic host the helm chart still says the host has not been provided

**To Reproduce**

```
helm install logging-kibana bitnami/kibana \
    --set elasticsearch.enabled=false \
    --set "elasticsearch.external.hosts[0]=logging-elasticsearch-coordinating-only.default.svc.cluster.local" \
    --set elasticsearch.external.port=9200 \
    --set persistence.enabled=false \
    --set service.type=ClusterIP
```

**Expected behavior**
`
ES is provided, so just take it

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.6.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7"
```

**Additional context**

**Comment by alvneiayu** [comment]
hi @JustinGuese 

Are you using the bitnami Elasticsearch chart or another solution? Could you share with me Kibana logs, please? If you are using the ElasticSearch Bitnami solution, share with me also logs, please?

Thanks a lot 

Álvaro
