### ISSUE TITLE
[mongodb]: TLS transport and certificate from valid root certificate authority

### ISSUE THREAD

**Issue by Andrei-Stepanov** [bitnami/charts#7115]
Hello.

How do I enable TLS transport?
I do have cert/key.
Cert is issued by DigiCert root CA.
This cert is valid all over the Internet.

I enable option: 

`tls.enabled: true`

Then init-container `generate-tls-certs` will start no matter what: 

https://github.com/bitnami/charts/blob/a9074525f83c97df584fb7ebfe408d57cbb06b22/bitnami/mongodb/templates/standalone/dep-sts.yaml#L118

Please explain, why this init container starts all the time? What the purpose of this container when certificate comes from root CA?

Let's go to official documentation :  [--sslCAFile](https://docs.mongodb.com/manual/reference/program/mongo/#std-label-mongo-shell-tls) :

` if --tlsCAFile or net.tls.CAFile (or their aliases --sslCAFile or ssl.CAFile) is not specified, the system-wide CA certificate store will be used when connecting to an TLS/SSL-enabled server.`

==> `--tlsCAFile` can be skipped at all, however we have:

https://github.com/bitnami/charts/blob/a9074525f83c97df584fb7ebfe408d57cbb06b22/bitnami/mongodb/templates/standalone/dep-sts.yaml#L237

`--tlsCAFile=/certs/mongodb-ca-cert` why? Why this string is present if I have world-wide trusted cert file?

Moreover, mongodb helm chart just doesn't allow specify existing cert + key. 

PS. 
Using function: `buildCustomCert` at is very strange: https://github.com/bitnami/charts/blob/a9074525f83c97df584fb7ebfe408d57cbb06b22/bitnami/mongodb/templates/secrets-ca.yaml#L23

Why do you require to do base64 enc of PEM format? This is not functional. Yaml supports:

```
cert: |
    -----BEGIN CERTIFICATE-----
    MIIIFTCCBv2gAwIBAgIQCra4Kst7
    ....
    -----END CERTIFICATE-----
```

The helm comment for values says:  https://github.com/bitnami/charts/blob/a9074525f83c97df584fb7ebfe408d57cbb06b22/bitnami/mongodb/values.yaml#L168

`@param tls.caCert Custom CA certificated (base64 encoded)` 
How do I know that you want base64 encoded PEM certificate, that already inside has base64 encode certificate?
What is purpose of encoding PEM-files?
:-(

**Comment by miguelaeh** [comment]
Hi @Andrei-Stepanov ,

> Please explain, why this init container starts all the time? What the purpose of this container when certificate comes from root CA?

The init container starts all the time because by default `tls.autoGenerated` is set to `true`, so when you enable TLS if you don't want the certificates to be autogenerated you need to set that to `false`.

In order to provide your own certificates, you can provide an existing secret containing the certificates with `tls.existingSecret`, [link](https://github.com/bitnami/charts/blob/ebbc39cb04f7e5e92de0e89b40587ebf312d1058/bitnami/mongodb/values.yaml#L163)


About the base64, I am not totally sure why it is not being done in the secret creation instead of requesting it on base64, I will investigate this and let you know

**Comment by Andrei-Stepanov** [comment]
Hello, `tls.existingSecret` has zero impact on deployment: https://github.com/bitnami/charts/blob/ebbc39cb04f7e5e92de0e89b40587ebf312d1058/bitnami/mongodb/templates/standalone/dep-sts.yaml

**Comment by miguelaeh** [comment]
Hi @Andrei-Stepanov ,
It has an impact through the `_helpers.tpl` file. If you check [this line](https://github.com/bitnami/charts/blob/ebbc39cb04f7e5e92de0e89b40587ebf312d1058/bitnami/mongodb/templates/standalone/dep-sts.yaml#L433), and find that function in the helpers, you will see that it has into account the `tls.existingSecret`

**Comment by Andrei-Stepanov** [comment]
Hi, I am sorry, 2 things:

1. The attached storage will be not used by mongodb server. That code just attached storage. Files in that storage will not be used in any way.
2. There is no support for a certificate from valid root certificate authority. In this case option: `tlsCAFile` + code is useless. The certificate comes from well known trusted root CA. This certificate is valid all over the Internet.

```
            - key: mongodb-ca-cert
              path: mongodb-ca-cert
              mode: 0600
            - key: mongodb-ca-key
              path: mongodb-ca-key
              mode: 0600
```

**Comment by miguelaeh** [comment]
Hi @Andrei-Stepanov ,
> The attached storage will be not used by mongodb server. That code just attached storage. Files in that storage will not be used in any way.

They are provided as extra flags, please check [this line](https://github.com/bitnami/charts/blob/ebbc39cb04f7e5e92de0e89b40587ebf312d1058/bitnami/mongodb/templates/standalone/dep-sts.yaml#L229)

> There is no support for a certificate from valid root certificate authority. In this case option: tlsCAFile + code is useless. The certificate comes from well known trusted root CA. This certificate is valid all over the Internet.

About this, let me re-check it

**Comment by miguelaeh** [comment]
Hi @Andrei-Stepanov ,
It is probable that in [this line](https://github.com/bitnami/charts/blob/a9074525f83c97df584fb7ebfe408d57cbb06b22/bitnami/mongodb/templates/standalone/dep-sts.yaml#L117) there is a missing condition and it should be something like `{{- if and .Values.tls.enabled Values.tls.autoGenerated }}`

**Comment by miguelaeh** [comment]
Hi @Andrei-Stepanov ,
Did you have the time to check what I mentioned in my last comment?
