### ISSUE TITLE
[bitnami/postgres] FATAL: unsupported frontend protocol in PostgreSQL logs

### ISSUE THREAD

**Issue by Homopatrol** [bitnami/charts#7121]
**Which chart**:
Postgresql 11.7

**Describe the bug**
I've deployed [this](https://github.com/Oteemo/charts/tree/master/charts/sonarqube) chart containing PostgreSQL 11.7 and have noticed the following error `FATAL: unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0` occurring frequently in the PostgreSQL log.

I am not sure if this is an error in this charts configuration of PostgreSQL as this error does not appear in any of my other deployments that also use PostgreSQL 11.

I have followed the discussion in this thread [#51](https://github.com/petere/homebrew-postgresql/issues/51) and tried setting the env variables `PGGSSENCMODE=disable` and  `GSSENCMODE=disable` in the PostgreSQL container however the error still persisted.

Additionally, the above thread suggests upgrading to PostgreSQL 12 to resolve this bug , I am aware there is discussion about the upgrading to PostgreSQL 12+ #6900 hopefully this bug can be fixed with this update.

**To Reproduce**
1. Install [this](https://github.com/Oteemo/charts/tree/master/charts/sonarqube) chart that includes PostgreSQL
2. After pods have finished starting up check the postgresql logs `oc logs <release_name>-postgresql-0 -f`
3. See PostgreSQL start followed by `FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0` multiple times
...

**Expected behavior**
I expect the PostgreSQL logs to a correct startup and not include this `FATAL` message.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Helm v3.5.2
```

- Output of `kubectl version`:

```
Kubernetes 1.19.0
```

**Logs**

```
oc logs <release_name>-postgresql-0 -f

postgresql 16:00:00.44 
postgresql 16:00:00.45 Welcome to the Bitnami postgresql container
postgresql 16:00:00.45 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 16:00:00.45 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 16:00:00.45 Send us your feedback at containers@bitnami.com
postgresql 16:00:00.46 
postgresql 16:00:00.46 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:00:00.55 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:00:00.56 INFO  ==> Loading custom pre-init scripts...
postgresql 16:00:00.57 INFO  ==> Initializing PostgreSQL database...
postgresql 16:00:00.57 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 16:00:00.64 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 16:00:00.68 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 16:00:00.68 INFO  ==> Generating local authentication configuration
postgresql 16:00:00.70 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 16:00:00.74 INFO  ==> Configuring replication parameters
postgresql 16:00:00.79 INFO  ==> Configuring fsync
postgresql 16:00:00.80 INFO  ==> Loading custom scripts...
postgresql 16:00:00.81 INFO  ==> Enabling remote connections
postgresql 16:00:00.82 INFO  ==> Stopping PostgreSQL...
postgresql 16:00:00.85 INFO  ==> ** PostgreSQL setup finished! **

postgresql 16:00:01.00 INFO  ==> ** Starting PostgreSQL **
2021-08-02 16:00:01.069 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-02 16:00:01.069 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-08-02 16:00:01.094 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-08-02 16:00:01.116 GMT [167] LOG:  database system was interrupted; last known up at 2021-08-02 15:56:07 GMT
2021-08-02 16:00:01.175 GMT [167] LOG:  database system was not properly shut down; automatic recovery in progress
2021-08-02 16:00:01.179 GMT [167] LOG:  redo starts at 0/2400BC0
2021-08-02 16:00:01.187 GMT [167] LOG:  invalid record length at 0/241EED0: wanted 24, got 0
2021-08-02 16:00:01.187 GMT [167] LOG:  redo done at 0/241EE98
2021-08-02 16:00:01.187 GMT [167] LOG:  last completed transaction was at log time 2021-08-02 15:57:07.649512+00
2021-08-02 16:00:01.232 GMT [1] LOG:  database system is ready to accept connections
2021-08-02 16:00:13.970 GMT [181] FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0
2021-08-02 16:00:16.016 GMT [183] FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0
2021-08-02 16:00:21.970 GMT [181] FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0
2021-08-02 16:00:25.016 GMT [183] FATAL:  unsupported frontend protocol 1234.5680: server supports 2.0 to 3.0
....
....
```

**Comment by pablogalegoc** [comment]
Hi @Homopatrol,

I see this behaviour as well, seems like a backward compatibility issue between [clients and “older servers”](https://www.postgresql.org/message-id/a3fdc44e-21a1-7493-46c4-a1a76465bb9e%402ndquadrant.com). Hopefully after updating to +11 version this problem will be solved. Right now there’s a work in progress at #6863 to move to version 13.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
