### ISSUE TITLE
[bitnami/redis] Password auth does not work without auth.usePasswordFiles	

### ISSUE THREAD

**Issue by Startouf** [bitnami/charts#7123]
**Which chart**:
Bitnami/redis
Chart Version 14.8.7
App version 6.2.5

**Describe the bug**
Booting the redis service without auth.usePasswordFiles = true does not work when using auth.secret + secret key

**To Reproduce**

Sample value file: 

```
image:
  tag: 6.2.5
architecture: standalone
auth:
  enabled: true
  existingSecret: staging-secrets
  existingSecretPasswordKey: redis-password
```

then following the instructions from the NOTES after installing the chart to start a redis client container connect using the password

**Expected behavior**
Fix the bug if it really is one, or otherwise explain the behavior regarding `usePasswordFiles: true` in the readme since it makes the chart works

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**
Add any other context about the problem here.

**Comment by juan131** [comment]
Hi @Startouf 

I was unable to reproduce the issue. These are the steps I followed:

- Create a secret with Redis credentials:

```console
$ kubectl create secret generic my-redis-secret --from-literal=redis-password=somesecretpassword
```

- Install the chart using the existing secret:

```console
$ helm install redis bitnami/redis \
  --set architecture=standalone \
  --set auth.enabled=true \
  --set auth.usePasswordFiles=true \
  --set auth.existingSecret=my-redis-secret \
  --set auth.existingSecretPasswordKey=redis-password
```

Then I followed the installation notes and I could create a Redis client and connect to the Redis server using the suggested credentials.
