### ISSUE TITLE
[Support]: influxdb with ingress

### ISSUE THREAD

**Issue by bhushanamk** [bitnami/charts#7126]
Hello I am trying to setup HA influxdb with ingress but getting error when accessing the application
# Installation of ingress controller:
helm install nginx-release --set defaultBackend.enabled=false bitnami/nginx-ingress-controller
# kubectl get svc 
nginx-release-nginx-ingress-controller        LoadBalancer   172.20.24.179    afb8d3df47a424cc590a0fa256a0737e-613715148.ap-south-1.elb.amazonaws.com   80:30467/TCP,443:30479/TCP   33m

# Installation of influxdb HA :
helm install greenkoinfluxhelm-release \
--set influxdb.service.sessionAffinity="ClientIP" \
--set  architecture="high-availability"  \
--set ingress.enabled=true \
--set ingress.hostname="afb8d3df47a424cc590a0fa256a0737e-613715148.ap-south-1.elb.amazonaws.com" \
--set auth.admin.username==##### \
--set auth.admin.password=##### \
--set relay.replicaCount=3 \
--set auth.admin.bucket="adminbucket"  \
--set auth.user.bucket="userbucket"  \
--set auth.admin.org="="#####" \
--set auth.user.org="#####" \
--set auth.readUser.username="#####" \
--set auth.readUser.password="#####" \
--set auth.writeUser.username="#####" \
--set auth.writeUser.password="#####" \
--set influxdb.replicaCount="3" \
--set metrics.enabled="true" \
--set influxdb.service.type="ClusterIP" \
--set relay.service.type="ClusterIP" \
--set metrics.service.type="ClusterIP" \
bitnami/influxdb
# error
![image](https://user-images.githubusercontent.com/73978482/128068492-a085e119-50e6-4eb7-8210-48b5110edfbf.png)

**Comment by rafariossaa** [comment]
Hi,
  Could you share the ingress object that was created?
```
kubectl get ingress greenkoinfluxhelm-release-influxdb  -o yaml
```

**Comment by bhushanamk** [comment]
@rafariossaa , Sure. below is the ingress object

`[ec2-user@ip-10-0-0-151 ~]$ kubectl get ingress greenkoinfluxhelm-release-influxdb  -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: greenkoinfluxhelm-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-08-03T17:59:09Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: greenkoinfluxhelm-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.3.2
  name: greenkoinfluxhelm-release-influxdb
  namespace: default
  resourceVersion: "936053"
  uid: 0ce220eb-67c4-4513-8f33-330cb1e9e67e
spec:
  rules:
  - host: afb8d3df47a424cc590a0fa256a0737e-613715148.ap-south-1.elb.amazonaws.com
    http:
      paths:
      - backend:
          service:
            name: greenkoinfluxhelm-release-influxdb-relay
            port:
              name: http
        path: /write
        pathType: ImplementationSpecific
      - backend:
          service:
            name: greenkoinfluxhelm-release-influxdb
            port:
              name: http
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.90
`

**Comment by rafariossaa** [comment]
Hi,
  I have just merged the fix for this, could you give it a try ?
