### ISSUE TITLE
[bitnami/external-dns] Add Kerberos support

### ISSUE THREAD

**Issue by pipeworks-asmith** [bitnami/charts#7127]
**Which chart**:
external-dns 5.2.2

**Is your feature request related to a problem? Please describe.**
The application supports configuring the rfc2136 provider with authentication over Kerberos, but no equivalent option is possible in the Helm chart.

**Describe the solution you'd like**
Add variables to the values.yaml to allow configuration over rfc3645 (Kerberos)

**Describe alternatives you've considered**
Configure the application by hand and stop using the Helm chart

**Additional context**
PR forthcoming...

**Comment by miguelaeh** [comment]
Hi @pipeworks-asmith ,
Thank you very much for the PR, we will take a look.
