### ISSUE TITLE
how to change synchronous_commit = remote_write

### ISSUE THREAD

**Issue by vincentchong1** [bitnami/charts#7129]
I use streaming application, and will like to change synchronous_commit = remote_write

will like to know where I should place that configuration in the values.yaml file.

I am using
pgpool-II version 4.2.3 (chichiriboshi)
repmgr 5.2.1
postgres (PostgreSQL) 11.12

**Comment by vincentchong1** [comment]
found a post that address this issue

**Comment by vishrantgupta** [comment]
@vincentchong1 could you please link the post with this ticket?

**Comment by Mauraza** [comment]
Hi @vishrantgupta,

If you check the documentation https://www.postgresql.org/docs/14/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT you need to change the value in the configuration file `postgresql.conf` you can follow this [part of the README.md ](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#postgresqlconf--pg_hbaconf-files-as-configmap)

**Comment by vishrantgupta** [comment]
I could add an extended configmap and override the config from there.

**Comment by Mauraza** [comment]
Or you can add the parameters you need with `postgresqlExtendedConf`. All the information is in https://github.com/bitnami/charts/tree/master/bitnami/postgresql#postgresqlconf--pg_hbaconf-files-as-configmap
