### ISSUE TITLE
How to change default tomcat server configuration

### ISSUE THREAD

**Issue by chemckenna** [bitnami/charts#7138]
**Which chart**:
bitnami/tomcat latest

**Describe the bug**
Opening as per request here: https://community.bitnami.com/t/how-to-change-default-tomcat-server-configuration/98097

I am looking to change the tomcat configuration settings, either at install time or after install and have them persist:

**To Reproduce**
I have deployed Apache Tomcat successfully from https://github.com/bitnami/charts/tree/master/bitnami/tomcat with:
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/tomcat
```
on AWS / EKS and I can copy files to the pod, which can subsequently be accessed and downloaded.

However, I can not figure out how to make changes to the default configuration, for instance adding BASIC authentication. When I copy files to the pod and restart Tomcat, I am back to square one. I understand why that is the case, but do not know how to work around it

2 specific examples of changes I want to make are updates to web.xml and tomcat-users.xml, at least for starters.

Can anyone advise?

**Expected behavior**
To be confirmed.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by carrodher** [comment]
You should mount your configuration files as volumes in the pod, for that you can use the `extraVolumes` and `extraVolumeMounts` parameters.

See this section from the image README: 
- https://github.com/bitnami/bitnami-docker-tomcat#configuration-files
And also those ones from the Helm Chart README: 
- https://github.com/bitnami/charts/tree/master/bitnami/tomcat#tomcat-deployment-parameters
- https://github.com/bitnami/charts/tree/master/bitnami/tomcat#persistence

**Comment by chemckenna** [comment]
Thank you @carrodher for your suggestion.

I have been unable to get this working.

The only successful mounting I have been able to do is to `/bitnami/tomcat` (not `/opt/bitnami/tomcat`). Once done, I can see my files in `/bitnami/tomcat/conf/`, but that is course is not where I need them.

Here is the only change from the default [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/tomcat/values.yaml) file:


```
271,277c271
< extraVolumes:
<   - name: web
<     configMap:
<       name: web
<   - name: tomcat-users
<     configMap:
<       name: tomcat-users
---
> extraVolumes: []
283,290c277
< extraVolumeMounts:
<   - name: web
<     mountPath: /bitnami/tomcat/conf/web.xml
<     subPath: web.xml
<   - name: tomcat-users
<     mountPath: /bitnami/tomcat/conf/tomcat-users.xml
<     subPath: tomcat-users.xml
< 
---
> extraVolumeMounts: []
```

where I have created ConfigMaps for my 2 files.

I'm clearly not seeing what needs to be done here. Have I overlooked a step? Can you advise further please? Thanks.

**Comment by chemckenna** [comment]
If I try to mount with:

```
extraVolumeMounts:
  - name: web
    mountPath: /opt/bitnami/tomcat/conf/web.xml
    subPath: web.xml
  - name: tomcat-users
    mountPath: /opt/bitnami/tomcat/conf/tomcat-users.xml
    subPath: tomcat-users.xml
```

I get the following in the logs:

```
tomcat 11:59:17.82 
tomcat 11:59:17.82 Welcome to the Bitnami tomcat container
tomcat 11:59:17.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat 11:59:17.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat 11:59:17.83 
tomcat 11:59:17.83 INFO  ==> ** Starting tomcat setup **
tomcat 11:59:17.85 INFO  ==> Initializing Tomcat server...
tomcat 11:59:17.86 INFO  ==> Persisted webapps detected.
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/tomcat/conf/tomcat-users.xml: Read-only file system
```

**Comment by migruiz4** [comment]
Hi @chemckenna,

I'm sorry for the inconvenience. Indeed there is an issue when trying to mount the file `tomcat-users.xml` externally.

During initialization, the Tomcat container will try to write the file, causing the "Read-only" issue.

I have created an internal task to review this, implement the "Mounted configuration" feature and release a new version of the image.

As a temporary workaround, you will need to clone the repository https://github.com/bitnami/bitnami-docker-tomcat and build your image omitting this line from `libtomcat.sh`: https://github.com/bitnami/bitnami-docker-tomcat/blob/14511be602138b22e41480ee74ba1bc69355b6f6/10/debian-10/rootfs/opt/bitnami/scripts/libtomcat.sh#L286

Then, use the values `image.repository` and `image.tag` to provide the helm chart with your custom image.

**Comment by chemckenna** [comment]
@migruiz4 - thanks for your reply.

So can I ask: with the change you intend to make, is mounting as I have with:

```
extraVolumeMounts:
  - name: web
    mountPath: /opt/bitnami/tomcat/conf/web.xml
    subPath: web.xml
  - name: tomcat-users
    mountPath: /opt/bitnami/tomcat/conf/tomcat-users.xml
    subPath: tomcat-users.xml
```

is the way to make such changes?

I will also look to enable SSL with changes to `/opt/tomcat/conf/server.xml`, so just wanted to ask if the above would be the correct method for that too.

Thank you.

**Comment by pablogalegoc** [comment]
@chemckenna unfortunately for the time being you'll probably have to use the temporary workaround pointed by @migruiz4 because the fix could take some time to be released.

> With the change you intend to make, is mounting as I have with [...] the way to make such changes?

Probably but, for instance, there are other charts that implement a "existingConfiguration" feature that makes it easier to use an existing configMap, so we can't tell 100% right now sorry.

**Comment by chemckenna** [comment]
Thanks @pablogalegoc and @migruiz4 for your help.

I have done as directed, using both the 8.5 and 10 versions.

I can achieve the following:

1. using the updated image, get tomcat running.
2. using the updated image, get tomcat running where I have provided modified files only containing new comments (to validate that my `extraVolumes` and `extraVolumeMounts` changes are correct and taking effect).

However, when I made configuration changes, I initially got the following:

`30-Aug-2021 13:47:12.970 WARNING [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.validateSecurityRoles Security role name [tomcat] used in an <auth-constraint> without being defined in a <security-role>`

with the following:

```
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Normal   Scheduled               8m42s                  default-scheduler        Successfully assigned che/tomcat85-basic-security-rolewq-bf59c7fdf-4866q to ip-172-31-52-195.us-west-2.compute.internal
  Normal   SuccessfulAttachVolume  8m40s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c1796b55-e2f4-41b7-9ea3-5c0397e3e639"
  Normal   Pulled                  8m33s                  kubelet                  Container image "docker.io/chemckenna/tomcat85:v1" already present on machine
  Normal   Created                 8m33s                  kubelet                  Created container tomcat
  Normal   Started                 8m33s                  kubelet                  Started container tomcat
  Warning  Unhealthy               6m24s                  kubelet                  Liveness probe failed: HTTP probe failed with statuscode: 401
  Warning  Unhealthy               3m31s (x49 over 8m1s)  kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 401
```

Having rectified this with an update to web.xml:

```
	<security-role>
		<role-name>tomcat</role-name>
	</security-role>
```

the Liveness probe failed and Readiness probe failed persist.

Looking at the logs, the only difference between a helm install with no changes and my changes is:

```
tomcat 14:35:03.03 
tomcat 14:35:03.03 Welcome to the Bitnami tomcat container
tomcat 14:35:03.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat 14:35:03.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat 14:35:03.03 
tomcat 14:35:03.03 INFO  ==> ** Starting tomcat setup **
tomcat 14:35:03.05 INFO  ==> Initializing Tomcat server...
tomcat 14:35:03.06 INFO  ==> Deploying Tomcat from scratch...
tomcat 14:35:03.08 INFO  ==> ** tomcat setup finished! **

tomcat 14:35:03.09 INFO  ==> ** Starting Tomcat **
```

and

```
tomcat 14:05:06.18 
tomcat 14:05:06.18 Welcome to the Bitnami tomcat container
tomcat 14:05:06.18 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat 14:05:06.19 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat 14:05:06.19 
tomcat 14:05:06.19 INFO  ==> ** Starting tomcat setup **
tomcat 14:05:06.20 INFO  ==> Initializing Tomcat server...
tomcat 14:05:06.21 INFO  ==> Persisted webapps detected.
tomcat 14:05:06.22 INFO  ==> ** tomcat setup finished! **

tomcat 14:05:06.23 INFO  ==> ** Starting Tomcat **
```

with no indication of where the problem is. The logs give no clue and having made the changes to overcome 
`30-Aug-2021 13:47:12.970 WARNING [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.validateSecurityRoles Security role name [tomcat] used in an <auth-constraint> without being defined in a <security-role>`

it suggests that how I am providing my config changes is OK.

Any ideas or suggestion?

Thanks.

**Comment by pablogalegoc** [comment]
@chemckenna we can try to use the `BITNAMI_DEBUG` environment variable on the container and see if there's a hint. Enable it with:
```yaml
image:
  debug: true
```

**Comment by chemckenna** [comment]
> @chemckenna we can try to use the `BITNAMI_DEBUG` environment variable on the container and see if there's a hint. Enable it with:
> 
> ```yaml
> image:
>   debug: true
> ```

Unfortunately that provides no  additional information, unless I need to access it in a different manner than `kubectl logs <pod name>`?

Thanks.

**Comment by chemckennaibm** [comment]
> Hi @chemckenna,
> 
> I'm sorry for the inconvenience. Indeed there is an issue when trying to mount the file `tomcat-users.xml` externally.
> 
> During initialization, the Tomcat container will try to write the file, causing the "Read-only" issue.
> 
> I have created an internal task to review this, implement the "Mounted configuration" feature and release a new version of the image.
> 
> As a temporary workaround, you will need to clone the repository https://github.com/bitnami/bitnami-docker-tomcat and build your image omitting this line from `libtomcat.sh`: https://github.com/bitnami/bitnami-docker-tomcat/blob/14511be602138b22e41480ee74ba1bc69355b6f6/10/debian-10/rootfs/opt/bitnami/scripts/libtomcat.sh#L286
> 
> Then, use the values `image.repository` and `image.tag` to provide the helm chart with your custom image.

Hi @migruiz4 - just checking in to see if this has been addressed yet? As you can see from above, I can't progress this any further. @pablogalegoc made the suggestion of changing the logging settings, but as I can not get the pods running successfully (having made my config changes), these logging changes don't help to progress the issue.

Ultimately I am trying to just enable SSL on a tomcat server, perhaps there is another route to get there? Thanks.

**Comment by chemckenna** [comment]
Hi @pablogalegoc & @migruiz4

I know this is not a useful solution for many, but I worked around the issue by simply disabling the Liveness and Readiness probes. Pod came up as expected and the changes to the config I had made with mounted volumes were reflected in the behaviour. Just posting as it might be useful to some... my needs do not require these to run, for the time being at least.

**Comment by chemckenna** [comment]
> > unless I need to access it in a different manner than kubectl logs ?
> 
> Nope, should have showed up in the output of that command if there was anything.
> 
> If you are willing to investigate deeper maybe changing the parameters in `/opt/bitnami/tomcat/conf/logging.properties` provides more info on the Tomcat startup logs ([logging](https://tomcat.apache.org/tomcat-10.0-doc/logging.html)). I would like to point you to specific logging settings that could help you debug but I’m not really an expert on Tomcat, sorry.

Thanks for the suggestion @pablogalegoc

**Comment by chemckenna** [comment]
Hello @migruiz4 - perhaps this question is best posed to you seeing as you provided the workaround previously.

As per my comments above, I have been able to implement BASIC AUTH with changes to `web.xml` and `tomcat-users.xml`. Attempting to progress this with changes to `server.xml` in an attempt to configure SSL, however, appear to bring me back to where I was earlier:

```
tomcat 12:00:50.01 
tomcat 12:00:50.01 Welcome to the Bitnami tomcat container
tomcat 12:00:50.01 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat 12:00:50.01 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat 12:00:50.01 
tomcat 12:00:50.01 INFO  ==> ** Starting tomcat setup **
tomcat 12:00:50.03 INFO  ==> Initializing Tomcat server...
tomcat 12:00:50.04 INFO  ==> Persisted webapps detected.
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/tomcat/conf/server.xml: Read-only file system
```
Can you suggest any workaround similar to that which worked by [here](https://github.com/bitnami/charts/issues/7138#issuecomment-897658148) which commented out a line in `libtomcat.sh`?

Thanks in advance for any assistance you can give.

**Comment by migruiz4** [comment]
Hi @chemckenna,

It is the same issue you encountered with `tomcat-users.xml`, but in this case `libtomcat.sh` is trying to modify the file `server.xml` in the function `tomcat_configure_ports`.

In this case, you would have to omit this line from `libtomcat.sh`:
https://github.com/bitnami/bitnami-docker-tomcat/blob/3a1374af278a084ff5596a8321c9589f4d02654f/10/debian-10/rootfs/opt/bitnami/scripts/libtomcat.sh#L284

But, in order to avoid further issues resulting from this change, make sure to configure the ports manually in your `server.xml` by replacing these ports with the values of these variables if altered:

```bash
tomcat_configure_ports() {
    replace_in_file "$TOMCAT_CONF_FILE" "port=\"8080\"" "port=\"$TOMCAT_HTTP_PORT_NUMBER\""   ## Default: 8080
    replace_in_file "$TOMCAT_CONF_FILE" "port=\"8005\"" "port=\"$TOMCAT_SHUTDOWN_PORT_NUMBER\"" ## Default: 8005
    replace_in_file "$TOMCAT_CONF_FILE" "port=\"8009\"" "port=\"$TOMCAT_AJP_PORT_NUMBER\"" ## Default: 8009
}
```

**Comment by chemckenna** [comment]
> Hi @chemckenna,
> 
> It is the same issue you encountered with `tomcat-users.xml`, but in this case `libtomcat.sh` is trying to modify the file `server.xml` in the function `tomcat_configure_ports`.
> 
> In this case, you would have to omit this line from `libtomcat.sh`: https://github.com/bitnami/bitnami-docker-tomcat/blob/3a1374af278a084ff5596a8321c9589f4d02654f/10/debian-10/rootfs/opt/bitnami/scripts/libtomcat.sh#L284
> 
> But, in order to avoid further issues resulting from this change, make sure to configure the ports manually in your `server.xml` by replacing these ports with the values of these variables if altered:
> 
> ```shell
> tomcat_configure_ports() {
>     replace_in_file "$TOMCAT_CONF_FILE" "port=\"8080\"" "port=\"$TOMCAT_HTTP_PORT_NUMBER\""   ## Default: 8080
>     replace_in_file "$TOMCAT_CONF_FILE" "port=\"8005\"" "port=\"$TOMCAT_SHUTDOWN_PORT_NUMBER\"" ## Default: 8005
>     replace_in_file "$TOMCAT_CONF_FILE" "port=\"8009\"" "port=\"$TOMCAT_AJP_PORT_NUMBER\"" ## Default: 8009
> }
> ```

Hi @migruiz4 - thanks again for your response. I presume I should make this latest change _in addition_ to the existing change and not in isolation? Thanks.

**Comment by chemckenna** [comment]
Thank you @carrodher, pablogalegoc & @migruiz4 for your help with this.

Posting here to confirm that the assistance above helped me solve the problems with respect to configuration of the Tomcat servers I had to install.

👍

**Comment by migruiz4** [comment]
Thank you @chemckenna for your feedback! 

I'm happy that our comments helped you solve this issue.
