### ISSUE TITLE
How to install postgres-ha of Postgres version 10.16 ？

### ISSUE THREAD

**Issue by lixwlixw** [bitnami/charts#7142]
How to install postgres-ha of Postgres version 10.16 ？ thanks.

**Comment by carrodher** [comment]
You can use the `image.tag` parameter by using the `--set` flag in your `helm install` command or modifying directly the _values.yaml_ and using `-f myvalues.yaml`. See https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#change-postgresql-version

**Comment by lixwlixw** [comment]
Has been successfully installed, thank you

**Comment by Mauraza** [comment]
I'm glad the question is solved. Closing this out now, do not hesitate to write us back if you have any other questions.
