### ISSUE TITLE
[bitnami/jenkins] Ingress TLS not configured when tls secret created separately

### ISSUE THREAD

**Issue by digglife** [bitnami/charts#7143]
**Which chart**:
`bitnami/jenkins 8.0.4`

**Describe the bug**
Ingress TLS not configured when I create the tls secret separately.

**To Reproduce**

1. Create a kubernetes secret named `mydomain.com-tls` according to [this guide](https://docs.bitnami.com/kubernetes/apps/jenkins/administration/enable-tls-ingress/)
    > If managing TLS secrets separately, it is necessary to create a TLS secret with name INGRESS_HOSTNAME-tls (where INGRESS_HOSTNAME is a placeholder to be replaced with the hostname you set using the ingress.hostname parameter).
2. Deploy the chart with the following ingress values:
    ```yaml
    ingress:
      enabled: true
      hostname: mydomain.com
      tls: true
    ```

**Expected behavior**

TLS should be configured for `mydomain.com` host in the ingress.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9+IKS", GitCommit:"3a2e6dc045e7e73277e9d1d88684f9cddb54ad78", GitTreeState:"clean", BuildDate:"2021-07-16T18:04:03Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I think the condition for configuring tls section does not work as described. In this case, when `ingress.tls` is `true`, if neither `certManager` nor `selfSigned` is `true`, TLS will not be configured. That rules out the condition that we configure the secret for the hostname separately as described above.

https://github.com/bitnami/charts/blob/c10c7f4015d1ed0bf52ed10f9cd0cc6fb7d94910/bitnami/jenkins/templates/ingress.yaml#L48-L58

**Comment by migruiz4** [comment]
Hi @digglife

Thank you very much for reporting this issue and submitting a PR!

I will take a look and get back to you as soon as possible.
