### ISSUE TITLE
airflow Failed to fetch log file from worker. 503 Server Error: Service Unavailable for url:

### ISSUE THREAD

**Issue by gowdra01** [bitnami/charts#7152]
I am trying to use apache airflow bitnami. 
I am having an issue where the logs of the dags are not working
its showing Failed to fetch log file from worker. 503 Server Error: Service Unavailable for url:
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/75704248/128442738-f150b0c8-eb79-44c6-98c1-8504cc6dfe0d.png">

what could be the reason ? I can access the logs on the worker pods directly its there.

**Comment by migruiz4** [comment]
Hi @gowdra01,

I would like to ask you for some additional information about your issue:
 
- Could you please check the status of your airflow pods? Is the 'worker-0' ready?
- Output of `cat /etc/resolv.conf` in any of the pods. I'd like to check that your Kubernetes cluster domain is `cluster.local`.
- Any additional details about your configuration that could help us troubleshoot your issue, for example, what airflow executor are you using.

**Comment by gowdra01** [comment]
airflow-idev-worker-0        2/2     Running            2          19h

$ cat /etc/resolv.conf
nameserver xx.xx.xx.xx
search dwh.svc.cluster.local svc.cluster.local cluster.local xxx.xx.xx.com 
options ndots:5

 executor: CeleryExecutor

let me know if you need more info..

**Comment by gowdra01** [comment]
it could be similar to this issue https://github.com/apache/airflow/pull/6722 ?

**Comment by migruiz4** [comment]
Hi @gowdra01,

Not sure it is related to that issue, I think it could be related to the container configuration.

Could you please share the custom `values.yaml` you used to deploy the chart?
