### ISSUE TITLE
postgres-ha enables tls, the client cannot connect through pgpool

### ISSUE THREAD

**Issue by lixwlixw** [bitnami/charts#7158]
postgres-ha enables tls   
the client cannot connect through pgpool(psql: server does not support SSL, but SSL was required)   
the client can to connect postgresql-0

**Comment by alemorcuq** [comment]
Hi, @lixwlixw.

Please, be more specific with your issue. When you create a new issue in this repository, there's a template you can fill to provide us with some information so we can help you.

**Comment by lixwlixw** [comment]
I installed postgres-ha and enabled tls.   
Connect directly to postgres-master:

**Comment by lixwlixw** [comment]
I installed postgres-ha and turned on tls.    
Connect directly to postgres-master:    
postgres@-db-test-0:~$ psql "postgres://postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless:5432/postgres?sslmode=require"   
Password:    
psql (10.16 (Debian 10.16-1.pgdg90+1))   
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)   
Type "help" for help.   

postgres=#    


Connect using pgpool:   
postgres@db-test-0:~$ psql "postgres://postgresql-ha-pgpool:5432/postgres?sslmode=require"   
psql: server does not support SSL, but SSL was required

**Comment by alemorcuq** [comment]
Could you give me some instructions to reproduce your issue? How did you install the chart?
