### ISSUE TITLE
Nuke Harbor Project

### ISSUE THREAD

**Issue by aaron-geospock** [bitnami/charts#7162]
Hi All,

We have an issue where we do not have access to delete a signed tag in a project and therefore are not able to delete the project. We are using an external RDS database but everything else had been built using the default helm values.
Is there any way that we can delete the project without having to first delete the signed tag or a way to get around the error when we try to remove the signed tag using docker trust revoke?

could not remove signature for <reponame>: you are not authorized to perform this operation: server returned 401.

**Comment by alemorcuq** [comment]
Hi, @aaron-geospock.

As I understand it, I think this isn't an issue with the Bitnami Helm Chart but with Harbor itself. Am I right? 

If that is the case, I suggest you to ask this question in the [Harbor Community](https://goharbor.io/community/). We mainly provide support in this repository to solve problems related to the Bitnami charts or the containers. For information regarding the application itself or customization of the content within the application, we highly recommend checking forums and user guides made available by the project behind the application.

**Comment by aaron-geospock** [comment]
Sorry you are correct. I managed to resolve this issues this morning by killing the notary services and then deleting the signed tag and then restarting the notary services. Ill close the ticket but leave the "solution" here in case anyone else has this issue.
