### ISSUE TITLE
How to set rabbitmq to enable mirror queue Mode in the deploy parameters

### ISSUE THREAD

**Issue by hamishliu** [bitnami/charts#7168]
For example, the manual open mode is as follows:

rabbitmqctl set_policy ha-all "^" '{"ha-mode":"all"}'

**Comment by alemorcuq** [comment]
Hi, @hamishliu.

I think you should be able to use the `loadDefinitions` parameter to set up the policy. Check this issue: #6276

**Comment by hamishliu** [comment]
Thank you very much. Could you tell me how to modify the bitnami helm pod time zone?

**Comment by hamishliu** [comment]
Are there any encapsulated variables or configuration parameters？

**Comment by alemorcuq** [comment]
I guess that is something specific of your cluster. There should be some documentation for changing pod timezones in your cluster, there's not an universal way of doing that. If it involves setting an environment variable or mounting a volume, you can do that easily in the Bitnami chart with `extraEnvVars`, `extraVolumes` and `extraVolumeMounts`.
