### ISSUE TITLE
[bitnami/argo-cd] repo-server configuration error

### ISSUE THREAD

**Issue by gongyho** [bitnami/charts#7173]
https://github.com/bitnami/charts/blob/4e6c20d5d5eac90caf257feb516a669854aac0bc/bitnami/argo-cd/templates/application-controller/deployment.yaml#L128

This place may be configured incorrectly

`- {{ include "argocd.repo-server" . }}:{{ .Values.repoServer.service.port }}`

**Comment by migruiz4** [comment]
Hi @gongyho,

Thank you for reporting this issue! Indeed it seems to be a typo in the argo-cd chart.

Would you like to contribute to our repository by sending a PR? 

You can find information about how to create a PR in our contributing guidelines: https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md

**Comment by gongyho** [comment]
yes, I like doing it. I'll sending a PR.

**Comment by migruiz4** [comment]
Thank you very much for your contribution!
