### ISSUE TITLE
[bitnami/elasticsearch]java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#7180]
**Which chart**:
The name (and version) of the affected chart

Helm Chart : elasticsearch-14.5.3
version : 7.10.2  

**Describe the bug**

we are using persistence enabled to true ,but we are getting the following error in elastic search

ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/bitnami/elasticsearch/data/nodes];
**Likely root cause: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes**
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)

As per the suggestion , I have tried to enable the volumePermissions.enabled to true but we are getting the following error while deploying the helm chart..

sparvathala@sparvathala bitnami % helm install elastic bitnami/elasticsearch -f elasticsearch/values.yaml -n default
coalesce.go:200: warning: cannot overwrite table with non table for extraInitContainers (map[])
coalesce.go:200: warning: cannot overwrite table with non table for extraInitContainers (map[])
**Error: YAML parse error on elasticsearch/templates/data-statefulset.yaml: error converting YAML to JSON: yaml: line 64: found character that cannot start any token**

**Expected behavior**

Helm chart should be deployed when we enable the volumePermission initContainer image enabled.

****Version of Helm and Kubernetes**:**

version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Kuberete version : v1.17.17

(paste your output here)
```

- Output of `kubectl version`:

sparvathala@sparvathala bitnami % kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
sparvathala@sparvathala bitnami % 


**Additional context**
Add any other context about the problem here.

**Comment by marcosbc** [comment]
Hi, when I deploy I'm able to get it working without issues:

```
$ helm template elastic -n default bitnami/elasticsearch
```

Which makes me think it is related to your `values.yaml`. Please check that it is properly formatted and try again.
