### ISSUE TITLE
[bitnami/redis]range can't iterate over ReadWriteOnce

### ISSUE THREAD

**Issue by wajika** [bitnami/charts#7185]
```
[root@k8s-master pv-pvc]# helm install redis \
> bitnami/redis \
> --kubeconfig=../kubeconfig-dev \
> --set master.persistence.storageClass=nas \
> --set master.persistence.accessModes=ReadWriteOnce \
> --set master.persistence.size=5Gi \
> --set replica.persistence.storageClass=nas \
> --set replica.persistence.accessModes=ReadWriteOnce \
> --set replica.persistence.size=5Gi
```

`Error: template: redis/templates/replicas/statefulset.yaml:415:25: executing "redis/templates/replicas/statefulset.yaml" at <.Values.replica.persistence.accessModes>: range can't iterate over ReadWriteOnce`

Why is "replica.persistence.accessModes=ReadWriteOnce" wrong?

**Comment by marcosbc** [comment]
@wajika That is because it is defined as an array. If you instead set `replica.persistence.accessModes[0]=ReadWriteOnce` it should work.

**Comment by wajika** [comment]
> replica.persistence.accessModes[0]=ReadWriteOnce

Thanks for your help, it works.
