### ISSUE TITLE
myetcd-0.myetcd-headless.test.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded

### ISSUE THREAD

**Issue by tutuV** [bitnami/charts#7190]
I don't know why this happened, not familiar with Bitnami/ETCD, my intention was to create an ETCD cluster in K8s.

helm install myetcd bitnami/etcd \
  --set statefulset.replicaCount=3 \
  --set persistence.enabled=true \
  --set persistence.storageClass=nfs-sc \
  --set persistence.size=8Gi \
  --set auth.rbac.rootPassword=etcdmima \
  --namespace test

helm search repo etcd
NAME            CHART VERSION   APP VERSION     DESCRIPTION
bitnami/etcd    6.3.3           3.5.0           etcd is a distributed key value store that prov...

kubectl get all -n test                                                                              Wed Aug 11 19:56:05 2021

NAME           READY   STATUS    RESTARTS   AGE
pod/myetcd-0   0/1     Running   4          10m

NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/myetcd            ClusterIP   10.111.109.130   <none>        2379/TCP,2380/TCP   10m
service/myetcd-headless   ClusterIP   None             <none>        2379/TCP,2380/TCP   10m

NAME                      READY   AGE
statefulset.apps/myetcd   0/1     10m

 kubectl describe pod/myetcd-0 -n test | tail -n 10                                                                            Wed Aug 11 19:55:32 2021

^[38;5;6metcd ^[38;5;5m11:50:42.89 ^[0m^[38;5;1mERROR^[0m ==> Unhealthy endpoint!
  Warning  Unhealthy  4m50s  kubelet  Readiness probe failed: {"level":"warn","ts":1628682642.9338675,"logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000f6a80/#initially=[myetcd-0.myetcd-headless.test.svc.cluster.local:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest
balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.244.3.5:2379: connect: connection refused\""}
myetcd-0.myetcd-headless.test.svc.cluster.local:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
^[38;5;6metcd ^[38;5;5m11:50:42.93 ^[0m^[38;5;1mERROR^[0m ==> Unhealthy endpoint!
  Warning  Unhealthy  4m41s  kubelet  Readiness probe failed: Terminated
^[38;5;6metcd ^[38;5;5m11:50:51.10 ^[0m^[38;5;1mERROR^[0m ==> Unhealthy endpoint!
  Warning  BackOff  4m39s                  kubelet  Back-off restarting failed container
  Normal   Created  4m27s (x3 over 7m38s)  kubelet  Created container etcd
  Normal   Pulled   4m27s (x3 over 7m38s)  kubelet  Container image "docker.io/bitnami/etcd:3.5.0-debian-10-r38" already present on machine

**Comment by marcosbc** [comment]
Hi @tutuV, I just installed etcd using this command and it deployed successfully:

```
$ helm install myetcd bitnami/etcd --set replicaCount=3 --set persistence.enabled=true --set persistence.size=8Gi --set auth.rbac.rootPassword=etcdmima
```

I noticed that you were using the value `statefulset.replicaCount` instead of `replicaCount`. Not sure if that is the reason, but I'd recommend you to try deploying with the command I shared above and see if it works for you.

**Comment by tutuV** [comment]
@marcosbc  Yes, this command works.In addition, I made a mistake here with PV, and now we're good.

**Comment by marcosbc** [comment]
Awesome, thanks for letting us know! In that case I'll proceed to close the issue.
