### ISSUE TITLE
Set kafka namespace through values.yaml

### ISSUE THREAD

**Issue by adonaiarruda** [bitnami/charts#7191]
**Which chart**:
The name (and version) of the affected chart.
[kafka 14.0.1](https://github.com/bitnami/charts/tree/master/bitnami/kafka)

**Is your feature request related to a problem? Please describe.**
I am trying to add the Kafka chart as a dependency of another chart and I would like to run them in different namespaces. e.g: My chart running on namespace my-namespace and Kafka running on kafka-namespace.
Seems this is not possible using the _values.yaml_ because _templates/statefulset.yaml_ doesn't have `metadata.namespace` config.
There is another way to solve this using helm3 as a dependency?

**Describe the solution you'd like**
Include the `metadata.namespace` field in the _templates/svc.yaml_ and _templates/statefulset.yaml_ files in order to set a namespace for kafka using the _values.yaml_

**Comment by alemorcuq** [comment]
Hi, @adonaiarruda.

We can add a `global.namespaceOverride` parameter like the one you can find in the ZooKeeper and the MongoDB charts. Would you be interested in contributing with a PR?

**Comment by adonaiarruda** [comment]
Sure! I will contribute to the project.
