### ISSUE TITLE
[Mongodb] custom port not working 

### ISSUE THREAD

**Issue by ahdzesq** [bitnami/charts#7196]
**Which chart**:
bitnami/mongodb version=10.23.10

**Describe the bug**

When the service port is distinct to 27017 in example 37017, the pods never reach running.

**To Reproduce**

1. change the port for the services to anything distinct of 27017
2. deploy the chart
3. check the logs of the first pod/mongodb-0

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Hi, @ahdzesq.

I wasn't able to reproduce your issue. This is the command I run to install the chart:

```
helm install mongo bitnami/mongodb --set service.port=37017
```

As you can see, the pod is running:

```
$ kubectl get po
NAME                             READY   STATUS    RESTARTS   AGE
mongo-mongodb-76bd47bb77-4ngbk   1/1     Running   0          2m29s
```

How did you install the chart?

**Comment by ahdzesq** [comment]
> 
> 
> Hi, @ahdzesq.
> 
> I wasn't able to reproduce your issue. This is the command I run to install the chart:
> 
> ```
> helm install mongo bitnami/mongodb --set service.port=37017
> ```
> 
> As you can see, the pod is running:
> 
> ```
> $ kubectl get po
> NAME                             READY   STATUS    RESTARTS   AGE
> mongo-mongodb-76bd47bb77-4ngbk   1/1     Running   0          2m29s
> ```
> 
> How did you install the chart?

Hello Thanks for your reply

I'm installing the chart like this:

```
helm install --create-namespace --values ./deployment.yaml --namespace mongodb mongodb bitnami/mongodb
```

I think is a little bit more complicated than using the standard values, I have a few more changes in order to enable external access, I have enabled a load balancer to access outside from the cluster, also I have changed the port for the load balancer for 37017 but seeing the logs of the pod mongodb-0 is trying to connect to the IP of the load balancer but on the port 27017

```
[mongodb-0 mongodb] mongodb 14:47:47.39 WARN  ==> Problem initiating replica set 
[mongodb-0 mongodb]             request: rs.initiate({"_id":"VF_Replicaset_0", "members":[{"_id":0,"host":"172.30.120.1:27017","priority":5}]}) 
[mongodb-0 mongodb]             response: MongoDB shell version v4.4.8 
[mongodb-0 mongodb] connecting to: mongodb://127.0.0.1:27017/admin?compressors=disabled&gssapiServiceName=mongodb 
[mongodb-0 mongodb] {"t":{"$date":"2021-08-12T14:47:44.042Z"},"s":"W",  "c":"NETWORK",  "id":23237,   "ctx":"js","msg":"You have an IP Address in the DNS Name field on your certificate. This formulation is deprecated."} 
[mongodb-0 mongodb] Implicit session: session { "id" : UUID("09d481b1-ac64-4c98-89e3-22512e41b98b") } 
[mongodb-0 mongodb] MongoDB server version: 4.4.8 
[mongodb-0 mongodb] { 
[mongodb-0 mongodb]     "ok" : 0, 
[mongodb-0 mongodb]     "errmsg" : "No host described in new configuration with {version: 1, term: 0} for replica set VF_Replicaset_0 maps to this node", 
[mongodb-0 mongodb]     "code" : 93, 
[mongodb-0 mongodb]     "codeName" : "InvalidReplicaSetConfig" 
[mongodb-0 mongodb] } 
[mongodb-0 mongodb] bye 
```
Also, something that I see is that the container port is 27017 and not 37017

```
kubectl describe pod/mongodb-0 -n mongodb

Containers:
  mongodb:
    Container ID:  docker://7c2baecd2821f98f807b3c405e54c7c596c0622f88245d0d4f7361eea1b67153
    Image:         docker.io/bitnami/mongodb:4.4.8-debian-10-r0
    Image ID:      docker-pullable://bitnami/mongodb@sha256:5f2d13c8dbcde332f82a1ed60146f4baf6f4561237ec36e31f3a6a2f9ae0b0e4
    Port:          27017/TCP
    Host Port:     0/TCP
```
Hope this can help to recreate the issue

Thanks!

**Comment by javsalgar** [comment]
Hi,

The service port being 37017 and container port 27017 is expected, as they are different elements. However, could you explain the use case for using port 37017 instead of 27017?

**Comment by ahdzesq** [comment]
> Hi,
> 
> The service port being 37017 and container port [27017](tel:27017) is expected, as they are different elements. However, could you explain the use case for using port [37017](tel:37017) instead of 27017?

The use case is hardening the database

**Comment by javsalgar** [comment]
Could you share your deployment.yaml file so I can reproduce the issue?
