### ISSUE TITLE
[external-dns] Resources are applied to a wrong namespace

### ISSUE THREAD

**Issue by arodriguezdlc** [bitnami/charts#7210]
**Which chart**:
The name (and version) of the affected chart
external-dns

**Describe the bug**
When using helm template command, the namespace metadata associated to namespaced resources is not consistent. For example, the deployment has set the namespace, but configmaps and secret don't, so the apply of these manifests could result in pods deployed on a different namespace than other resources. 

I think all namespaced objects should have set the namespace metadata to avoid this situation. 

**To Reproduce**

1. Execute helm template to generate k8s manifests using the option --namespace to indicate a specific one.
2. Apply these manifests with kubectl (but with a default namespace configured with a different namespace). 
3. You can see that the deployment has been deployed to the namespace indicated to helm, but other resources as configmaps or secrets have been deployed to the kubectl default namespace. 

**Expected behavior**
All resources should be deployed to the namespace specified via helm. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-17T16:37:00Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**
Add any other context about the problem here.

**Comment by pipeworks-asmith** [comment]
Good catch! I can fix this up quickly.
