### ISSUE TITLE
postgresql-ha with nfs-provisioner

### ISSUE THREAD

**Issue by vincentchong1** [bitnami/charts#7215]
anyone has lesson learned from using dynamic persistent volume for postgresql-ha with nfs-provisioner?
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

I have a 1 master and 2 worker node k8s cluster that are openstack instance, and I am thinking of exportfs from the master as my container persistent volume

pvc created dynamically, i observe /bitnami/postgresql is written to the master NFS successfully.  But the pod will shutdown after a short while, I think it is because statefulset can not be fulfilled, or the standby postgresql is not ready.

pgpool-II version 4.2.3 (chichiriboshi)
postgres (PostgreSQL) 11.12
repmgr 5.2.1
helm v3.3.0
kubectl v1.20.6

FYI, using example from nfs-provisioner, the testing work fine as below, SUCCESS is written to the master NFS.
kubectl create -f deploy/test-claim.yaml -f deploy/test-pod.yaml

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but we don't have a similar platform were to test this.
  Maybe it is a problem with the timing if the nfs pvc take some time to initialize. In this case, you can increase the time for the readiness/liveness probes.
  Could you provide some logs from the pods and the kubectl describe of the pods and pvcs ? maybe something happens to me.

**Comment by vincentchong1** [comment]
not actively looking to make this work at this time.

**Comment by rafariossaa** [comment]
Don't hesitate to come back and share your findings.
