### ISSUE TITLE
[bitnami/memcached] HPA for memcached

### ISSUE THREAD

**Issue by cabrinha** [bitnami/charts#7216]
**Which chart**:
memcached

**Is your feature request related to a problem? Please describe.**
It'd be nice to have Horizontal Pod Autoscaler built into the chart.

**Describe the solution you'd like**
Horizontal Pod Autoscaler objects built into the chart.

**Describe alternatives you've considered**
At the moment, I need to wrap the chart and deploy my own HPA objects.

**Additional context**
Thanks.

**Comment by juan131** [comment]
Hi @cabrinha 

Thanks so much or this great suggestion! Would you like to contribute with a PR adding this feature to the chart?

**Comment by cabrinha** [comment]
> Hi @cabrinha
> 
> Thanks so much or this great suggestion! Would you like to contribute with a PR adding this feature to the chart? You can use other charts with support for it available in this catalog as a reference.

Sure: https://github.com/bitnami/charts/pull/7251

**Comment by juan131** [comment]
Thanks! Taking a look @cabrinha
