### ISSUE TITLE
https://charts.bitnami.com/bitnami repo AccessDenied

### ISSUE THREAD

**Issue by danielllek** [bitnami/charts#7230]
**Which chart**:
Repo inaccessible

**Describe the bug**
```
$ curl https://charts.bitnami.com/bitnami
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>89YGX63PFE9EK2B1</RequestId><HostId>voZQNsRHuH27gP8jeufx0NMN6XqKdQnzSJBGXVswh/K+SvUmJ1kI8IcHsG7BLkV/XpEBNwjvSNM=</HostId></Error>
```

**Expected behavior**
Should be accessible :)

**Comment by carrodher** [comment]
This URL is designed to be added by using the helm client:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```

If you want to work with it by using `curl`, `wget` or a web browser you can find the _index.yaml_ by using https://charts.bitnami.com/bitnami/index.yaml

**Comment by beltran-rubo** [comment]
Hi @danielllek 

The issue is there is not any index.html there but the index.yaml required for the repository. You can check `https://charts.bitnami.com/bitnami/index.yaml` directly or just add to the list of your repositories:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
```

I hope it helps.

**Comment by danielllek** [comment]
Helm client failed like this:
`Error: Looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR`

It works now :)

Maybe it was some network problem (and testing with curl fooled me that it still doesn't work).

Sorry for bothering.
