### ISSUE TITLE
All messages get time stamped to 1970

### ISSUE THREAD

**Issue by lboclboc** [bitnami/charts#7231]
**Which chart**:
fluentd-3.7.3

**Describe the bug**
The timestamp for messages becomes dated to 1970

**To Reproduce**

1. install the release with standard values.
2. look in the aggregators log, all dates are 1970.

**Expected behavior**
Expected correct date for messages as from when they where generated.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 
```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi! I see that you contributed with a PR. Thank you so much! We will take a look
