### ISSUE TITLE
Set priorityClassName for Harbor pods?

### ISSUE THREAD

**Issue by brianmajor** [bitnami/charts#7237]
Hello,

Is it possible to set the priorityClassName on each of the harbor pods?  I've only found a solution for redis so far:

```
redis:
  master:
    priorityClassName: <name>
```

Even though core.priortyClassName (for example) is supported in the harbor helm chart, the following does not work in the bitnami charts:

```
core:
  priorityClassName: <name>
```
  
Many thanks,
Brian

**Comment by javsalgar** [comment]
Hi,

Thank you for reporting. Definitely, I believe this is a feature that should be available in the chart (we have this in other charts). Ideally, it should be possible to define a prorityClassName for each component (core, chartmuseum... and so on). Would you like to contribute with a PR? If not, we will work on that.

**Comment by brianmajor** [comment]
Hi, thanks for the quick response.  No, sorry, I cannot contribute with a PR, but I'll be watching this for when the feature becomes available.

**Comment by javsalgar** [comment]
Ok! Then I will create a task in our backlog to tackle this. I cannot guarantee an ETA but as soon as we have more news we will update the ticket.

**Comment by migruiz4** [comment]
Hi @brianmajor,

The feature `priorityClassName` has been added for all the harbor components in this PR #7986.

**Comment by brianmajor** [comment]
Fantastic, thanks @migruiz4
