### ISSUE TITLE
[bitnami/wordpress] Add volumePermissions init container for included MariaDB

### ISSUE THREAD

**Issue by tomaszn** [bitnami/charts#7239]
**Which chart**:
wordpress 12.1.0

**Is your feature request related to a problem? Please describe.**
Yes. Using rancher.io/local-path volume provider results in:
```
(...)
mariadb 21:45:22.62 INFO  ==> Initializing mariadb database         
mkdir: cannot create directory '/bitnami/mariadb': Permission denied
```

**Describe the solution you'd like**
Possibility to enable the same init container as for the main Wordpress persistence:
```
volumePermissions:
  enabled: true
```
The issue [is already solved for bitnami/mariadb](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#adjust-permissions-of-persistent-volume-mountpoint).

**Describe alternatives you've considered**
I could deploy bitnami/mariadb separately. It has that feature.

**Additional context**
This would need to be done for both `primary` and `secondary` instances in the Wordpress chart.
Could be also added to all charts that include MariaDB.

**Comment by marcosbc** [comment]
Hi @tomaszn, since MariaDB is installed as a subchart, it would be enough for you to specify `--set mariadb.volumePermissions.enabled=true` when deploying, or adding the following entry in your `values.yaml`:

```yaml
mariadb:
  ...
  volumePermissions:
    enabled: true
```

**Comment by tomaszn** [comment]
@marcosbc Works flawlessly! Thank you for the explanation.

**Comment by marcosbc** [comment]
Sure! No problem!
