### ISSUE TITLE
[bitnami/thanos] Support dual-mode Thanos receive

### ISSUE THREAD

**Issue by ethernoy** [bitnami/charts#7240]
**Which chart**:
Thanos (5.3.1)

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Support dual-mode Thanos receive described in https://github.com/thanos-io/thanos/blob/release-0.22/docs/proposals-accepted/202012-receive-split.md. 

**Describe alternatives you've considered**
N/A

**Comment by rafariossaa** [comment]
Hi,
  Thanks for proposing this.
  I am opening an internal task to study it, however I can not provide an ETA for this.
  We will come back as soon as we have news.

**Comment by smazurov** [comment]
see #7148

**Comment by rafariossaa** [comment]
Ok, thanks.
Then, let's wait until the PR get merged.

**Comment by carlosjgp** [comment]
PR is now merged

Close?
