### ISSUE TITLE
[bitnami/testlink]  Ingress is broken

### ISSUE THREAD

**Issue by pgorlewar** [bitnami/charts#7242]
Helm upgrade failed: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.extensions.v1beta1.IngressBackend

**Comment by pablogalegoc** [comment]
Thanks for flagging this @pgorlewar! I see you've already opened a PR to fix this issue so a member of the team will review it
