### ISSUE TITLE
Galera mariadb deadlock

### ISSUE THREAD

**Issue by hamishliu** [bitnami/charts#7243]
1、While mariadb is running, it is suddenly unable to read or write, so it is completely stuck.Excuse me, is there a location method?

**Comment by hamishliu** [comment]
![image](https://user-images.githubusercontent.com/79596614/129694579-a31aac95-4fed-4871-ac1d-ef55fe624bcd.png)

**Comment by hamishliu** [comment]
It is suspected that the anomaly in Synchronize caused the whole database cluster to get stuck.

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about how to reproduce the issue? I don't recall seeing this issue in the past.

**Comment by hamishliu** [comment]
In the process of running, the three database nodes are read-only, cannot write any data, and are completely stuck.

**Comment by javsalgar** [comment]
This is strange. Do you have the values that you used to deploy?
