### ISSUE TITLE
Does ElasticSearch helm support hot-warm-cold architecture?

### ISSUE THREAD

**Issue by QuanTran91** [bitnami/charts#7244]
**Which chart**:
ElasticSearch

**Describe the issue**
I could find any configuration/parameter of the chart to config hot-warm-cold data tier.
Does anyone know how to config it? Thanks.

**Comment by juan131** [comment]
Hi @QuanTran91 

That architecture needs supporting (at least) two different types of data nodes: hot and warm.

Currently this chart supports installing a Elasticsearch cluster with "master", "data", "ingest" and "coordinating-only" nodes. However, there's no support for different types of data nodes so far.

**Comment by QuanTran91** [comment]
Thank @juan131 , seems I need to use the ECK helm chart to deploy instead.

**Comment by vrajannagari** [comment]
Any plans to implement this or have the chart support the hot-warm-cold architecture ?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but there is not plan support this feature at this moment.
  In any case, PRs are welcome and we will be glad to review and merge it.

**Comment by davidtaback** [comment]
Hello,
Has this decision, to not support the hot-warm-cold architecture, been changed?

**Comment by QuanTran91** [comment]
@davidtaback I suggest you'd better start with ECK instead.

**Comment by davidtaback** [comment]
Thanks @QuanTran91. We have deployed a few ECK environments but we were specifically asked to use Helm with the Charts from Bitnami - mostly because Elastic haven't published Helm charts since 8.5.1 and recommend using community supported charts.

**Comment by juan131** [comment]
Hi everyone!

Supporting this feature is a low priority and I'm afraid we don't have bandwidth to work on it.

That said, we welcome you to create a pull request adding support for it. The Bitnami team would be excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
