### ISSUE TITLE
When deploy mongodb by this charts,I can’t init some database

### ISSUE THREAD

**Issue by ZhuoSiChen** [bitnami/charts#7254]
mongodb
After mongodb have be create I want to create some database for my app 
for example:
use myshinynewdb
db.user.insert({name: "Ada Lovelace", age: 205})

**Comment by juan131** [comment]
Hi @ZhuoSiChen 

You can use the following parameters to create a custom database during the 1st installation of the MongoDB chart and set the corresponding credentials: `auth.rootPassword`, `auth.username`, `auth.password`, and `auth.database`. Find more information in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#mongodb-parameters

You can also load your custom init scripts as explained in the section below of the README.md:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#customize-a-new-mongodb-instance

**Comment by ZhuoSiChen** [comment]
Thanks you !
