### ISSUE TITLE
Postgresql-ha, root

### ISSUE THREAD

**Issue by maxinfosoft** [bitnami/charts#7255]
I really need your help in using your helm chart postgresql-ha (https://bitnami.com/stack/postgresql-ha/helm).
Since, your containers are non-root, I can't make changes to them (I need to add my .so libs and run my .sql inside the container).
I tried using postgresql.initdbScripts & postgresql.initdbScriptsCM parameters, but could not succeed because it is not documented anywhere and I found no textbook example on how to use it properly.
Please help with any info and example how I can use instead of your bitnami containers for postgresql-ha where there is non-root rights with other containers or how to help me with info how i can get root rights in your docker-images to build my docker-images based on them which will have my .so-libs & my sql scripts. 
After these changes, I will be able to do a helm upgrade with the new parameters (image.registry, image.repository).
I would really appreciate any information, recipe, best practice on how I can add my .so libs to your docker-images and use in my kubernetes cluster.

**Comment by rafariossaa** [comment]
Hi,
  The initscripts are run with the image's user, `1001` by default, if you need to run your scripts as root, you will need to create your own image. You can use the [dockerfile](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/11/debian-10/Dockerfile) and add your logic in the `postunpack.sh` script, but it would depend on what you need to do.
  Then you would need to push your image to a repository and change the `image.registry` , `image.repository`, `image.tag` accordingly.
