### ISSUE TITLE
[bitnami/postgresql-ha] Unable to restore if the pg_basebackup was taken with primary node different than pod -0

### ISSUE THREAD

**Issue by lpaarup** [bitnami/charts#7259]
**Which chart**:
The chart is bitnami/postgresql-ha and the version I'm using is 6.0.0. I've looked at the latest versions and I see the same problem.

**Is your feature request related to a problem? Please describe.**
For me it's a problem. I have a cron job to take daily backups using `pg_basebackup` through the pgpool. I normally run **2 replicas** of the repmgr.

As far as I understand, by default the pod -0 will become the primary and -1 will be a standby. I guess this is determined (among other things) by the `REPMGR_PRIMARY_HOST` env variable which is hardcoded to the headless -0 in the chart.

If I do the backup when the pod -0 is the primary, then I have no problem with the restore. My restore procedure is to scale the statefulset down, replace the data folder of pod -0 with the backup contents, erase the data folder of -1 and scale up. When I scale up, -0 will try to become master and -1 will clone/replicate the data from it. Everything works fine.

When -1 is the primary when I take the backup, of course the data contained in the backup indicates that -1 is primary and -0 is standby. When I restore, I would scale the sts to 0, replace the data in -1 with the backup, erase the data in -0 and scale up. The problem is that -1 will let -0 become the primary and wait for it:

```
postgresql-repmgr 10:11:15.41 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 10:11:15.45 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 10:11:15.46 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 10:11:15.48 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 10:11:15.87 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 10:11:15.89 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 10:11:16.23 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 10:11:16.26 INFO  ==> Initializing Repmgr...
postgresql-repmgr 10:11:16.28 INFO  ==> Waiting for primary node...
```

Pod -0 will also come up, be elected as primary, start with an empty db and initialize it. Then, -1 will be `Cloning data from primary node...` and we end up with both replicas with empty data (not the data from the backup).

As by default pod -0 will be elected as primary, another option is to copy the backup into the data PV of pod -0. If I do this and leave the data of -1 empty, pod -1 will wait for primary (as before) but pod -0 will output the following and die:

```
postgresql-repmgr 10:16:20.05 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 10:16:20.10 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 10:16:20.11 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 10:16:20.12 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 10:16:20.21 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 10:16:20.24 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 10:16:20.26 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 10:16:20.93 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 10:16:20.95 INFO  ==> Initializing Repmgr...
postgresql-repmgr 10:16:20.97 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 10:16:21.01 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 10:16:21.02 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 10:16:21.11 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 10:16:21.21 INFO  ==> Configuring replication parameters
postgresql-repmgr 10:16:21.43 INFO  ==> Configuring fsync
postgresql-repmgr 10:16:21.49 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 10:16:21.55 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-08-18 10:16:21 GMT [142] : [1-1] [0] user=,db= LOG:  pgaudit extension initialized
2021-08-18 10:16:21 GMT [142] : [2-1] [0] user=,db= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-08-18 10:16:21 GMT [142] : [3-1] [0] user=,db= LOG:  listening on IPv6 address "::", port 5432
2021-08-18 10:16:21 GMT [142] : [4-1] [0] user=,db= LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-08-18 10:16:21 GMT [142] : [5-1] [0] user=,db= LOG:  redirecting log output to logging collector process
2021-08-18 10:16:21 GMT [142] : [6-1] [0] user=,db= HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-08-18 10:16:21 GMT [144] : [1-1] [0] user=,db= LOG:  database system was interrupted; last known up at 2021-08-16 12:22:01 GMT
2021-08-18 10:16:21 GMT [144] : [2-1] [0] user=,db= LOG:  redo starts at 0/2F000180
2021-08-18 10:16:21 GMT [144] : [3-1] [0] user=,db= LOG:  consistent recovery state reached at 0/2F016E38
2021-08-18 10:16:21 GMT [144] : [4-1] [0] user=,db= LOG:  redo done at 0/2F016E38
2021-08-18 10:16:21 GMT [144] : [5-1] [0] user=,db= LOG:  last completed transaction was at log time 2021-08-16 12:23:42.994011+00
2021-08-18 10:16:22 GMT [142] : [7-1] [0] user=,db= LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 10:16:22.15 INFO  ==> ** Starting repmgrd **
[2021-08-18 10:16:22] [NOTICE] repmgrd (repmgrd 5.2.0) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-08-18 10:16:22] [NOTICE] starting monitoring of node "postgresql-ha-postgresql-0" (ID: 1000)
[2021-08-18 10:16:22] [ERROR] connection to database failed
[2021-08-18 10:16:22] [DETAIL] 
could not translate host name "postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.ns.svc.cluster.local" to address: Name or service not known

[2021-08-18 10:16:22] [DETAIL] attempted to connect using:
  user=repmgr password=.. connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.ns.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
[2021-08-18 10:16:22] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2021-08-18 10:16:22] [HINT] upstream node must be running before repmgrd can start
```

**NOTE**: I've removed some parts of the service names not to include the ns and the helm release name.

Pod -0 will keep on `CrashLoopBackOff` forever because it reads the data and determines from the data that -0 is a standby (which was the case when the backup was taken). Therefore it tries to replicate from -1 (which is the primary according to the data), but -1 has not even started, it is `Waiting for primary node...`.

**Describe alternatives you've considered**
In order to try to fix this, I've added the following values to the helm chart:

```
postgresql:
    extraEnvVars:
    - name: REPMGR_PRIMARY_HOST
      value: postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.ns.svc.cluster.local
```

This way I overwrite the REPMGR_PRIMARY_HOST in all the replicas with the headless of -1, which was the master when the backup was taken.

In this case, when I copy the backup data into -1 and leave -0 empty, during the negotiation -1 will become master, read it's consistent data while -0 waits and clones.

**Question**

Is this the only way to solve it or has another alternative been considered? It seems weird that I need to upgrade the helm release in order to do the restore...

**Comment by rafariossaa** [comment]
Hi,
  I think this approach is a valid one, maybe something can be done in the chart/container logic to let the user choose which node is the primary. I could not tell right now, this has to be analyzed.
  In any case, as `pg_basebakcup` copies the files where the postgresql status is stored maybe another approach could be to backup only the databases you needed with `pg_dump`. Have you considered this option ? I am not sure if that would be an option in your scenario.
