### ISSUE TITLE
https://charts.bitnami.com/bitnami access denied

### ISSUE THREAD

**Issue by grygiel** [bitnami/charts#7267]
Hi -
I am getting access denied on bitnami chart repo https://charts.bitnami.com/bitnami:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>KX70K25YJ0AAXD89</RequestId>
<HostId>t8HtREX3CVvrZ1w18Uo6SJ9rTgwck3Mms9I2Ja2r3HlzNrW5X4QEodwoMF9RbXQu1dGTeyeYPVI=</HostId>
</Error>
```

I have tried helm repo update and  I get a success message
I have tried helm search repo bitnami and I get a list of repositories

But if I try to curl the site I get access denied or if I try 
```
helm install my-release --namespace nodetest bitmani/node
```
I get 
```
Error: failed to download "bitmani/node"
```
Any help would be appreciated.

**Comment by carrodher** [comment]
This URL is designed to be used by the helm client:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
```

In your `helm install` command it seems there is a typo in the repository name, if you fix the typo you should be able to install the chart without any issue.

If you want to work with it by using `curl`, `wget` or a web browser you can find the _index.yaml_ by accessing https://charts.bitnami.com/bitnami/index.yaml but that's all.

**Comment by grygiel** [comment]
Yup that was the issue had it right everywhere else and reversed the letter on the install.
