### ISSUE TITLE
[bitnami/keycloak] Database password for Postgress defaults to "some-password"; Should be random

### ISSUE THREAD

**Issue by michaeljmarshall** [bitnami/charts#7279]
**Which chart**:
Bitnami/keycloak 4.2.0 (current, at time of issue creation)

**Is your feature request related to a problem? Please describe.**
The keycloak helm chart has a default password (`some-password`) for the postgres database.

It's possible that this value hasn't been changed to prevent breaking changes for users. I'm not familiar enough with how this password is used to speak authoritatively on whether or not this password can safely be changed during an upgrade. However, as a new consumer of this chart, I wouldn't expect to see a default password for my keycloak database.

**Describe the solution you'd like**
I'd like to see a random password (or at least be forced to provide my own password) when deploying keycloak. The documentation already suggests that the password will be random:

https://github.com/bitnami/charts/blob/cf14b39f0cfd52c68481f024703d7c80bd45a4ce/bitnami/keycloak/values.yaml#L869-L873

**Describe alternatives you've considered**
Alternatively, I could override the default. However, I am writing a chart that uses this one as a dependency. Thus, I would prefer for this chart to just use a random password.

**To Observe Behavior**
Steps to observe the behavior:

1. Template the keycloak helm chart without overriding any values.
2. Inspect the result of the `templates/secrets.yaml`.
3. Decode `database-password` to see that it is `some-password`.

**Additional context**
It seems to me that the default value for `.Values.postgresql.postgresqlPassword` should be `""`, as it is for other passwords in the keycloak chart. Then, because the `database-password` is generated with a function (shown below), I'd modify the function as follows:

```tpl
{{/*
Return the Database encrypted password
*/}}
{{- define "keycloak.databaseEncryptedPassword" -}}
{{- if .Values.postgresql.enabled }}
    {{- (.Values.postgresql.postgresqlPassword | default (randAlphaNum 10)) | b64enc | quote -}}
{{- else -}}
    {{- .Values.externalDatabase.password | b64enc | quote -}}
{{- end -}}
{{- end -}}
```
This behavior would match the behavior for other secrets in the keycloak helm chart: https://github.com/bitnami/charts/blob/cf14b39f0cfd52c68481f024703d7c80bd45a4ce/bitnami/keycloak/templates/secrets.yaml#L27-L33

If my solution is accepted, I'd be happy to contribute a patch with the above logic. Thanks!

**Comment by michaeljmarshall** [comment]
Additionally, I noticed that the bitnami/harbor helm chart simply defers the password selection: https://github.com/bitnami/charts/blob/6340bff66f93c8c797bda3ca0842e4bf770059f1/bitnami/harbor/templates/_helpers.tpl#L813-L828

The bitnami/postgresql chart also uses a function to create a random password: https://github.com/bitnami/charts/blob/112db1c509fcd74623fd8f25c61c660a5918564d/bitnami/postgresql/templates/_helpers.tpl#L65-L76

I don't feel that one solution is better than the other. I would just like to avoid a single default password.

**Comment by randradas** [comment]
Hello @michaeljmarshall, first of all let me thank you for such well explained issue. You are completely right in your analysis. We discussed it internally and we agree with you in setting `.Values.postgresql.postgresqlPassword` like `""`. This kind of contributions are very valuable for Bitnami charts so I would like to strongly encourage you to participate to this creating a PR with this change, would it be possible you to have time in order to create a PR with this change?

**Comment by michaeljmarshall** [comment]
Hi @randradas - thank you, I'm happy to contribute. I opened a PR and linked it to this issue.

**Comment by randradas** [comment]
this is great! I will review it ASAP. thank you! let's keep the issue open till the PR is merged and tested. I'll be back soon.
