### ISSUE TITLE
[bitnami/thanos] Ingress secretName and Name of Object Secret not corresponding for TLS

### ISSUE THREAD

**Issue by jfpucheu** [bitnami/charts#7280]
**Which chart**: thanos-5.3.11

**Describe the bug**
Deploying ingress with custom certificates on query-frontend component, the secret created Name Object is not corresponding to the SecretName setup in the ingress.yaml

**To Reproduce**
 Deploy ingress TLS with custom certificate setup.

In ingress.yaml:
`secretName: {{ printf "%s-tls" .Values.queryFrontend.ingress.hostname }}`

in tls-secret.yaml:

```
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-query-frontend
```

**Expected behavior**
The SecretName in the Ingress.yaml should be the same as the Secret Object Name Created.

**Version of Helm and Kubernetes**: 

- Output of `helm version`: v3.4.1

```
v3.4.1
```

- Output of `kubectl version`:

```
v1.20.6
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. As you discovered the issue, would you like to contribute with a PR?

**Comment by javsalgar** [comment]
Hi, please check this PR https://github.com/bitnami/charts/pull/7442
