### ISSUE TITLE
[bitnami/keycloak] Make it possible to remove the http port on the keycloak service

### ISSUE THREAD

**Issue by michaeljmarshall** [bitnami/charts#7288]
**Which chart**:
bitnami/keycloak version 5.0.1

**Is your feature request related to a problem? Please describe.**
The current helm chart opens the `http` port on the keycloak service without the option to disable it. Since that service is a load balancer by default, it means that a plaintext port is open. This could allow for a user to accidentally send credentials over an insecure connection.

**Describe the solution you'd like**
I'd like to be able to remove this plaintext port from the service. It could be pretty simple. A boolean value like `.service.http.enabled` could determine whether or not to add the port to the service.

This solution would not close the http port on the container. It will only remove it from the service. Since the http port is used for health checks and isn't reachable from outside the cluster, I think it is fine to leave the port open on the container.

**Describe alternatives you've considered**
You could use an ingress controller that forces redirects to the https endpoint. However, I am looking at using the kubernetes service of type load balancer. This service will open up ports on the load balancer for all ports on the service.

**Additional context**
I am happy to help submit a PR, if necessary.

**Comment by Mauraza** [comment]
Hi @michaeljmarshall,

We are open to contributions. If you want we are more than happy to review a PR.
