### ISSUE TITLE
[bitnami/kafka] How can I set the "advertised.listener" for each broker with server.config?

### ISSUE THREAD

**Issue by midi79** [bitnami/charts#7291]
**Which chart**:
Kafka

**Is your feature request related to a problem? Please describe.**
I am trying to install the kafka in the Kubernetes cluster which has three brokers.
And I'd like to add to "advertised.listener" for each broker's "server.config" file.
However, I cannot add that config when the kafka starts.
I added "Value.yaml" which has options for "advertised.listener", but it didn't work.
When I added the "advertised.listener=XXXXXX" in the config option, the brokers didn't run.
And I tried to add the "advertisedListeners:" option, but it also didn't work.
I saw the additional options generated dynamically on the "setup.sh" file when I install or upgrade helm chart.
BUT, the "setup.sh" script didn't execute when the kafka broker started.
How can I add the advertised.listener option for each broker?

**Describe the solution you'd like**
The "setup.sh" script have to run when the broker start.

**Describe alternatives you've considered**
When I install or upgrade the helm chart, the helm should make "server.config" file dynamically with "advertised.listener=XXXXXX" 

**Additional context**

**Comment by pablogalegoc** [comment]
Hi @midi79!

Could you share the parameters you are setting on the `values.yaml` file? Thanks!

**Comment by pablogalegoc** [comment]
@midi79 sorry for the late response, have you tried setting the `advertisedListeners` like this:
```yaml
advertisedListeners:
  - "INTERNAL://test:9093"
  - "CLIENT://test:9092"
```
I can see them being picked by the kafka pod:
```
❯ kubectl describe pod/kafka-0 | grep KAFKA_CFG_ADVERTISED_LISTENERS
      KAFKA_CFG_ADVERTISED_LISTENERS:                      INTERNAL://test:9093,CLIENT://test:9092
```

**Comment by akshaysolank** [comment]
Hi Team I am also facing the same issue 
could you please explain me a bit more details that what I have to add in my kafka value.yaml file to connect it conduktor 

`listeners: []
## @param advertisedListeners The address(es) (hostname:port) the broker will advertise to producers and consumers. Auto-calculated it's set to an empty array
## When it's set to an empty array, the advertised listeners will be configured
## based on the authentication protocols (auth.clientProtocol, auth.externalClientProtocol and auth.interBrokerProtocol parameters)
##
advertisedListeners: []
## @param listenerSecurityProtocolMap The protocol->listener mapping. Auto-calculated it's set to nil
## When it's nil, the listeners will be configured based on the authentication protocols (auth.clientProtocol, auth.externalClientProtocol and auth.interBrokerProtocol parameters)
##
listenerSecurityProtocolMap: ""
## @param allowPlaintextListener Allow to use the PLAINTEXT listener
##
allowPlaintextListener: true
## @param interBrokerListenerName The listener that the brokers should communicate on
##
interBrokerListenerName: INTERNAL
## @param command Override Kafka container command`

**Comment by carrodher** [comment]
Could you please create a new issue filling the template with your specific scenario so we can provide better support? Thanks in advance
