### ISSUE TITLE
Cassandra repairs

### ISSUE THREAD

**Issue by koovee** [bitnami/charts#7294]
**Which chart**:
charts/bitnami/cassandra 8.0.2

**Is your feature request related to a problem? Please describe.**
Not sure if this is already possible and I'm just not able to find correct configuration.

I'm not able to run `nodetool repair` remotely (or use e.g. Cassandra Reaper) to keep Cassandra nodes in sync.

**Describe the solution you'd like**
Enable remote JMX with or without authentication. This should be configurable in values.yaml.

**Describe alternatives you've considered**

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. If I understand correctly, you would like that the JMX port is accessible in the service defined in service.yaml, is that correct?

**Comment by koovee** [comment]
It would be enough if cassandra process inside the container would enable remote access to jmx (by default it binds to localhost -> nodetool can be only run from inside the container). So if this behaviour could be controlled in values.yaml it would be great. I think it's semi hardcoded in cassandra-env.sh script inside the container).

**Comment by javsalgar** [comment]
From what I see, this is something that can be set in the JMV_OPTS env var. Did you try setting JVM_OPTS using the extraEnvVars value?

https://stackoverflow.com/questions/50397844/bind-cassandra-jmx-to-ip

**Comment by koovee** [comment]
Thanks, I'll try that..
