### ISSUE TITLE
UPGRADE FAILED from 7.7.1 version to 8.20.2

### ISSUE THREAD

**Issue by Brafgard** [bitnami/charts#7295]
**Which chart**:
8.20.2

**Describe the bug**
On attempting to upgrade rabbitmq helm chart from 7.7.1 version to 8.20.2
an error received:
"
Error: 
UPGRADE FAILED: 
    template: 
        rabbitmq/templates/statefulset.yaml:51:25:
            executing "rabbitmq/templates/statefulset.yaml" at <include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $)>:
                error calling include: template: rabbitmq/charts/common/templates/_affinities.tpl:97:9:
                    executing "common.affinities.pods" at <eq .type "soft">:
                        error calling eq: incompatible types for comparison
"

**To Reproduce**
install rabbitmq using helm chart version 7.7.1
run helm upgrade $releaseName rabbitmq --namespace $namespace --repo https://charts.bitnami.com/bitnami --version 8.20.2 --wait --reuse-values -f -

**Expected behavior**

RabbitMQ is upgraded successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"e1d093448d0ed9b9b1a48f49833ff1ee64c05ba5", GitTreeState:"clean", BuildDate:"2021-06-03T00:20:57Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by juan131** [comment]
Hi @Brafgard 

You're using the flag `reuse-values` and that means you're using some values that aren't supported anymore in the new chart version. Could you please share the values that you were using in your release? You can do it by sharing the output of the command below:

```console
$ helm get values $releaseName
```

**Comment by Brafgard** [comment]
Hello @juan131 ! Thanks for the response.
Correct, I use the 'reuse-values' parameters, but I'm not sure that this is the case.
Because I install version 7.7.1 and then try to upgrade, so - no modifications of chart values from my side.
Way to reproduce:
1) run "helm install rabbitmq bitnami/rabbitmq --namespace default --version 7.7.1"
2) run "helm upgrade rabbitmq rabbitmq --namespace default --repo https://charts.bitnami.com/bitnami --version 8.20.2 --wait --reuse-values"
And also there is result of executing "helm get values $releaseName"
"USER-SUPPLIED VALUES:
null"

**Comment by juan131** [comment]
Hi @Brafgard 

I can confirm it's related with the `--reuse-values` flag. Please try the commands below to upgrade your release:

```console
$ export RABBITMQ_PASSWORD=$(kubectl get secret --namespace "default" rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)
$ export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace "default" rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
$ helm upgrade rabbitmq bitnami/rabbitmq --namespace default --version 8.20.2 --set auth.password=$RABBITMQ_PASSWORD --set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE
```

Once you're in the `8.x` series, you can use again the `--reuse-values` flag but it's not possible between these two major versions due to incompatibilities in the values.yaml structure.
