### ISSUE TITLE
bitnami nginx image -- unable to run as non-root

### ISSUE THREAD

**Issue by dili-pk** [bitnami/charts#7302]
I am using nginx Bitnami image for one of my application in my organization and as per the platform guidelines, we are not allowed to run any containers with root permissions. 
I am trying to pull the chart using helm and using a values.yaml file where i define the securityContexts. I am using the same values.yaml as below:
https://github.com/bitnami/charts/blob/master/bitnami/nginx/values.yaml

also tried setting the helm arguments as below

```
 --set podSecurityContext.enabled=true
--set podSecurityContext.fsGroup=1001
--set containerSecurityContext.enabled=true
--set containerSecurityContext.runAsUser=101
--set containerSecurityContext.runAsNonRoot=true
```

Though my deployment is successful, there is no way the securityContexts are being updated.. 

**Which chart**:
The name (and version) of the affected chart

https://github.com/bitnami/charts/tree/master/bitnami/nginx

**Describe the bug**
Unable to apply securityContext to this image.. 
though you enable it, it doesn't work.. 
there is no security context in the podspec.. 

**To Reproduce**

Apply runAsNonRoot and allowPrivilegeEscalation: false for the nginx bitnami image.

**Expected behavior**

The securityContext should be updated to the pod level and also container level. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version                                                                                                     
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
k version --short                                                                                                
Client Version: v1.22.0
```

**Additional context**

**Comment by Mauraza** [comment]
Hi @dili-pk,

I try to deploy Nginx with this command:
```
helm install nginx bitnami/nginx --set podSecurityContext.enabled=true --set podSecurityContext.fsGroup=1001 --set containerSecurityContext.enabled=true --set containerSecurityContext.runAsUser=1001 --set containerSecurityContext.runAsNonRoot=true
```
and it's working.

In your arguments appeas: `--set containerSecurityContext.runAsUser=101` I think you missed a '0' the argument should be `--set containerSecurityContext.runAsUser=1001`

**Comment by dili-pk** [comment]
@Mauraza,
Thanks for replying.. I managed to fix the issue by adding securitycontext to the containers.. However, I noticed that my application doesn't run with this image.. 
```
 04:38:57.50
 04:38:57.50 Welcome to the Bitnami nginx container
 04:38:57.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
 04:38:57.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
 04:38:57.70 Send us your feedback at containers@bitnami.com
 04:38:57.80
 04:38:57.80 INFO  ==> ** Starting NGINX setup **
 04:38:58.30 INFO  ==> Validating settings in NGINX_* env vars...
 04:38:58.40 INFO  ==> Initializing NGINX...
 04:38:58.80 WARN  ==> 'nginx.conf' is not writable by current user. Skipping modifications...

 04:38:59.10 INFO  ==> ** NGINX setup finished! **
 04:38:59.50 INFO  ==> ** Starting NGINX **
2021/08/25 04:38:59 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /opt/bitnami/nginx/conf/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /opt/bitnami/nginx/conf/nginx.conf:2
2021/08/25 04:38:59 [emerg] 1#0: mkdir() "/opt/bitnami/nginx/tmp/client_body" failed (13: Permission denied)
nginx: [emerg] mkdir() "/opt/bitnami/nginx/tmp/client_body" failed (13: Permission denied)
````
The pod ends up in crash loop.. was wondering if this image works as non-root user? or should i consider a different image?

**Comment by Mauraza** [comment]
Hi @dili-pk,

```bash
2021/08/25 04:38:59 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /opt/bitnami/nginx/conf/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /opt/bitnami/nginx/conf/nginx.conf:2
```
You can use the directive user without super-user privileges, which is a rule of Nginx.

No matter what image are you using if it's running as non-root, you are going to get the same error.

**Comment by vk-98** [comment]
@Mauraza What could be done for running nginx without root user privileges? Any fix or solution for it?

**Comment by dili-pk** [comment]
> @Mauraza What could be done for running nginx without root user privileges? Any fix or solution for it?

@vk-98 .. I got this resolved by enabling containerSecurityContext and by default it will run as user "1001".. 
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
