### ISSUE TITLE
[bitnami/influxdb] error converting YAML to JSON when `persistance.enabled` = false and `backup.enabled` = true

### ISSUE THREAD

**Issue by elunic** [bitnami/charts#7327]
**Which chart**:
The name (and version) of the affected chart
influxdb, 2.3.7

**Describe the bug**
Setting `backup.enabled = true` when `persistence.enabled = false` leads to a YAML error.
```
Message: Helm upgrade failed: YAML parse error on influxdb/templates/influxdb/cronjob-backup.yaml: error converting YAML to JSON: yaml: line 35: mapping values are not allowed
```

The error seems to be in this line, reducing the indentation by one block resolves the error: https://github.com/bitnami/charts/blob/da425504d2f42713dd969d4035eae8cc6a14e981/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml#L53

**To Reproduce**

Use a configuration with all default values and:
```yaml
persistence:
  enabled: false
backup:
  enabled: true
```

**Expected behavior**
The mentioned error should not be thrown.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
(helm used via Terraform Helm Provider, version 2.2.0)

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"e1d093448d0ed9b9b1a48f49833ff1ee64c05ba5", GitTreeState:"clean", BuildDate:"2021-06-03T00:20:57Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by elunic** [comment]
Thanks a lot!

**Comment by rafariossaa** [comment]
You are welcome.
