### ISSUE TITLE
[bitnami/redis] Add relabelings parameter to ServiceMonitor

### ISSUE THREAD

**Issue by Vaproc** [bitnami/charts#7330]
**Which chart**:
[bitnami/redis:15.0.1](https://github.com/bitnami/charts/tree/master/bitnami/redis)

**Is your feature request related to a problem? Please describe.**
I want to relable a metric before scraping. The serviceMonitor resource inside the chart does only provide `metricRelabelings`.

**Describe the solution you'd like**
Add `relabelings` parameter to the serviceMonitor (e.g. #7082 , #6511, #6221)

**Describe alternatives you've considered**
Using the existing `metricRelabelings` functionality, but this does not solve my issue.

**Additional context**
-

**Comment by alvneiayu** [comment]
hi @Vaproc 

Thanks a lot for sending us a PR. My colleague is reviewing your change.

Again, thanks a lot for your help and your time

Álvaro

**Comment by alvneiayu** [comment]
hi @Vaproc 

Thanks a lot for your PR and your time.

Álvaro
