### ISSUE TITLE
[bitnami/postgres] Backup all the databases using pg_dumpall

### ISSUE THREAD

**Issue by tropicallydiv** [bitnami/charts#7339]
Hi
I installed postgres on openshift using bitnami helm charts .

I am trying to take backup of all the databases using pg_dumpall;

however on executing the command

```
I have no name!@postgresql-postgresql-0:/opt/bitnami/postgresql/bin$ pg_dumpall -U postgres -f /db-backup/postgres/dump.out
Password: 
pg_dumpall: could not connect to database "template1": FATAL:  password authentication failed for user "postgr
```
The password for simplicity is postgres defined in a secret  

`postgresql-password  --  postgres`

Running as pgadmin. I presume the below error is due to the fact that the user is not a superuser.  

```
opt/bitnami/postgresql/bin
I have no name!@postgresql-postgresql-0:/opt/bitnami/postgresql/bin$ pg_dumpall -U pgadmin -f /db-backup/postgres/dump.out
Password: 
pg_dumpall: query failed: ERROR:  permission denied for table pg_authid
pg_dumpall: query was: SELECT oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolconnlimit, rolpassword, rolvaliduntil, rolreplication, rolbypassrls, pg_catalog.shobj_description(oid, 'pg_authid') as rolcomment, rolname = current_user AS is_current_user FROM pg_authid WHERE rolname !~ '^pg_' ORDER BY 2
```
```
pgdb=> \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 pgadmin   | Create DB                                                  | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

How can I get pg_dumpall to work?

TIA.

**Comment by pablogalegoc** [comment]
Hi @tropicallydiv!

Could you try using `postgresql-postgres-password` instead of `postgresql-password` in the secret?

**Comment by tropicallydiv** [comment]
Hi
I don't see that password setting anywhere. 

Here is my yaml setting
global:
..
..
postgresql:
    postgresqlDatabase: "pgdb"
    postgresqlUsername: "postgres"
    existingSecret: ""
    postgresqlPassword: "postgres"
    servicePort: ""
    replicationPassword: "postgres"

..
..
..

## @param postgresqlPostgresPassword PostgreSQL admin password (used when `postgresqlUsername` is not `postgres`, in which case`postgres` is the admin username)
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run (see note!)
postgresqlPostgresPassword: ""
## @param postgresqlUsername PostgreSQL user (has superuser privileges if username is `postgres`)
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
##
postgresqlUsername: postgres
## @param postgresqlPassword PostgreSQL user password
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
##
postgresqlPassword: ""
## @param existingSecret Name of existing secret to use for PostgreSQL passwords
## The secret has to contain the keys postgresql-password which is the password for postgresqlUsername when it is
## different of postgres, postgresql-postgres-password which will override postgresqlPassword,
## postgresql-replication-password which will override replication.password and postgresql-ldap-password which will be
## used to authenticate on LDAP. The value is evaluated as a template.
## e.g:
## existingSecret: secret
##
existingSecret: ""
## @param usePasswordFile Mount PostgreSQL secret as a file instead of passing environment variable
##
usePasswordFile: false
## @param postgresqlDatabase PostgreSQL database
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run
##
postgresqlDatabase: ""


Where do I set that password?

Thank you for your time in helping out on this issue. 
tropicallydiv...

**Comment by pablogalegoc** [comment]
> The password for simplicity is postgres defined in a secretpostgresql-password -- postgres

Ah sorry, I understood that you were creating a secret and using `postgresql-password` instead of `postgresql-postgres-password`:
https://github.com/bitnami/charts/blob/4040ce1d323ad286e2dd52bc0bfc74e7dc431e79/bitnami/postgresql/templates/secrets.yaml#L15-L17

You can set it in the `values.yaml` with `postgresqlPostgresPassword`
