### ISSUE TITLE
[bitnami/mongodb] Add relabelings / metricRelabelings to ServiceMonitor

### ISSUE THREAD

**Issue by Malenczuk** [bitnami/charts#7342]
**Which chart**:
[bitnami/mongodb:10.23.13](https://github.com/bitnami/charts/tree/master/bitnami/mongodb)

**Is your feature request related to a problem? Please describe.**
I want to relabel metrics before scraping / ingestion.

**Describe the solution you'd like**
Add `relabelings`/`metricRelabelings` parameter to the `ServiceMonitor` (e.g. #7082 , #6511)

**Describe alternatives you've considered**
The `ServiceMonitor` resource inside the chart does not provide any means of relabeling.

**Additional context**

**Comment by migruiz4** [comment]
Hi @Malenczuk,

Thank you for your feature request. It is in our plans to standardize the `relabelings`/`metricRelabelings` values in all of our charts but I can not give you an ETA for when it would be ready for MongoDB.

If you'd like to contribute, feel free to send a PR with the necessary changes and we will be happy to review it and help with anything you need.

**Comment by Malenczuk** [comment]
Hi @migruiz4,

Thanks for response. Please feel free to check my PR.

**Comment by migruiz4** [comment]
Hi @Malenczuk, sorry for the late response.

I see my colleague  @alemorcuq already reviewed and merged the PR. Thank you very much for your contribution!

I will then close this issue.
