### ISSUE TITLE
RabbitMQ - `RABBITMQ_PASSWORD` env var value never gets used

### ISSUE THREAD

**Issue by btlyken** [bitnami/charts#7347]
**Which chart**:
RabbitMQ 8.20.5

**Describe the bug**
The [documentation for the Rabbit chart](https://artifacthub.io/packages/helm/bitnami/rabbitmq) recommends setting `auth.password` in order to set the admin user's password. After deploying this chart release to upgrade from release 6.25.9, we found that this password value was not being respected and a default value of `CHANGEME` was being used instead. The `auth.password` value sets the `RABBITMQ_PASSWORD` env variable but it doesn't look like that env var gets used anywhere else in the codebase.

**To Reproduce**

1. Update `auth.password` to a password value other than `CHANGEME`
2. Deploy the chart
3. Port forward to 15672 on the Rabbit pod and try to login with the password from step 1

**Expected behavior**
We expected that providing a value to `auth.password` would set the password for `user`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68e3e47dad98b808ba41087c0c62e80cd4fcec36", GitTreeState:"clean", BuildDate:"2021-05-25T02:41:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mahaffey** [comment]
We are also seeing this behavior, albiet intermittently. Some of my deployments take the provided password and others don't.

```
cat /bitnami/rabbitmq/conf/rabbitmq.conf
## Username and password
##
default_user = admin
default_pass = CHANGEME```

https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L371

**Comment by mahaffey** [comment]
This issue seems related:
https://github.com/bitnami/charts/issues/3095

**Comment by yilmi** [comment]
Thanks @btlyken for reporting this issue! Are you by any chance using custom load definitions?

As you can see, this would change the password setting logic:
- [RABBITMQ_LOAD_DEFINITIONS use](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L365)

It is also showing in the documentation:
> RABBITMQ_LOAD_DEFINITIONS: Whether to load external RabbitMQ definitions. This is incompatible with setting the RabbitMQ password securely. Default: no.

If you can confirm that I'll try reproducing the issue.

Thanks,
Yass

**Comment by btlyken** [comment]
I can confirm that the deployed Statefulset and a Helm dry-run both show that `RABBITMQ_LOAD_DEFINITIONS` is set to `no`.
![image](https://user-images.githubusercontent.com/69008486/131531320-83a032dc-4586-4fc3-9330-12e4623ca79f.png)

**Comment by btlyken** [comment]
> We are also seeing this behavior, albiet intermittently. Some of my deployments take the provided password and others don't.
> 
> Note in the rabbit conf file this default value that occurs here
> 
> ```
> cat /bitnami/rabbitmq/conf/rabbitmq.conf
> ## Username and password
> ##
> default_user = admin
> default_pass = CHANGEME
> ```
> 
> https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L371

We're seeing this too. We copied/pasted the `.Values.configuration` section in the default values file and changed the `default_pass` line to `default_pass = {{ .Values.auth.password }}`. This fixed a test deployment to a new environment but we're not sure if it will fix it when upgrading an existing install. We'll find out today though.

**Comment by btlyken** [comment]
It looks like there are two other issues reporting the same or similar behavior. It seems like it all comes down to this configuration value and there not being something that overrides it to set it to the value that's passed in `Values.auth.password`.

https://github.com/bitnami/charts/issues/3095
https://github.com/bitnami/bitnami-docker-rabbitmq/issues/131

**Comment by yilmi** [comment]
Thanks for the follow up @btlyken! Let me try to reproduce this on my end following your steps and get back to you 👍

**Comment by yilmi** [comment]
Hi @btlyken,

The only way I could reproduce this issue was by keeping a pvc where I used a different password or didn't use a password, and got an autogenerated password instead.

I successfully updated from 6.25.9 to 8.20.5
- Install rabbitmq chart with version 6.25.9: 
> helm install rmq6 bitnami/rabbitmq --set rabbitmq.password=secretpassword,rabbitmq.erlangCookie=secretcookie --version 6.25.9
- Upgrade to rabbitmq chart with version 8.20.5:
> helm install rmq6 bitnami/rabbitmq --set auth.password=secretpassword,auth.erlangCookie=secretcookie --version 6.25.9

As you probably already know, the keys for the values used to set authentication were updated from:
- 6.25.9 used `rabbitmq.password`
- 8.20.5 uses `auth.password`

If you follow the code pointed by @mahaffey, you'll see that `rabbitmq_create_config_file()` is only executed if no configuration file is found ([see here](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L711)).

The layout of the filesystem changed between the 6.25.9 and 8.20.5 charts, which means, the file was recreated the first time 8.20.5 pods started.

Which is why I think that what may actually have happened is:
- helm install of 6.25.9 using `rabbitmq.password`
- helm upgraded to 8.20.5 using `rabbitmq.password` as a key for the password 
  - As this key doesn't exist anymore and auth.password is empty, we generated a password (see [code handling password generation](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/secrets.yaml#L17))
  - As the file system layout changed (config file location), we didn't find the previous configuration file and generated a new one using the generated password
- Even if you found a way to push `auth.password` that wouldn't be taken into consideration as the config file now exist 

From there on, the file holding the new password should now be `/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf`

Output from a search for the rabbitmq.conf files default_pass value:
```bash
user@rabbitmq-6-0:/$ find / -name rabbitmq.conf -exec grep -H default_pass {} \; 2>/dev/null
/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf:default_pass=secretpassword
/opt/bitnami/rabbitmq/conf/..2021_09_01_14_30_50.754877945/rabbitmq.conf:default_pass=CHANGEME
/opt/bitnami/rabbitmq/conf/rabbitmq.conf:default_pass=CHANGEME
```
If you could run the same command to confirm that would be great.

Thanks,
Yass

**Comment by btlyken** [comment]
Hey @yilmi,

Thanks for digging into this further and sorry about slow reply. I was out on PTO this past week.

I just tested a fresh env deployment starting with 6.25.9. Here's the Rabbit config file info before 8.20.5. The blurred password is the correct one we're expecting. The login works with the password expected, and the password was passed using the `rabbitmq.password` value.
![image](https://user-images.githubusercontent.com/69008486/132570087-c8c22db1-8e1d-4bde-9a91-9b64eca2d539.png)

Then I deployed 8.20.5 to upgrade the version and using the `auth.password` value. This was without overriding the default `.Values.configuration` config. Somehow - still not sure how - I was able to log in with the right password, except all the config files show the `CHANGEME` default.
![image](https://user-images.githubusercontent.com/69008486/132573375-aeb26e94-c732-4c8e-909d-8cf5ec9e3bfc.png)

For all of our other lanes, we overwrote the default `.Values.configuration` config with a slightly modified one replacing the `default_pass` line with `default_pass = {{ .Values.auth.password }}` instead. After this change, none of our other environments had this password issue.

As for the `auth.password` change, we did notice that early on before the deployment. Thankfully our PR Helm dry-run validation found that before we went further.

My question is, since it's creating a new config file anyway because the file structure changed and the old config file isn't being used anymore, why didn't it use the password we provided?

**Comment by btlyken** [comment]
I think I see the issue now. In that [script you linked](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L371) on line 371. In that image I linked earlier with the Helm dry-run values that are getting used in the deployment, we have `RABBITMQ_SECURE_PASSWORD` set to `yes` because of the logic around[ this line in this file](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/statefulset.yaml#L184), which would prevent our password from getting used.

This seems like a bug. If we set `.Values.loadDefinition.enabled` to `no` and are expected to pass in a password to `auth.password`, but then `RABBITMQ_SECURE_PASSWORD` is set to `yes` which prevents `RABBITMQ_PASSWORD` from being used in that bash script. Am I understanding this right or am I missing something?

**Comment by yilmi** [comment]
Hi @btlyken, thanks for the detailed feedback!

In the line you point out, we check that `RABBITMQ_SECURE_PASSWORD` is not set to yes if we have `LOAD_DEFINITIONS` set, as described int he documentation:
> Whether to load external RabbitMQ definitions. This is incompatible with setting the RabbitMQ password securely. Default: no.

The part where the password gets set can be found on line [751-752 of librabbitmq.sh](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L751). If we have persisted data we won't set the password, otherwise, we do set it if `RABBITMQ_SECURE_PASSWORD` is set to yes, for this we are calling `rabbitmq_change_password()` passing `RABBITMQ_PASSWORD`

I hope this answers your question, let me know if you still have any!

**Comment by btlyken** [comment]
Interesting... so it looks like in this case:
- The config file gets created with the default password `CHANGEME` since secure password is automatically set to `yes` since `LOAD_DEFINITIONS` is `no`
- Once Rabbit starts up, it checks if there is already data on the mounted PV and uses RabbitCtl to set the password if no data exists

That must be where this is having trouble. During our initial troubleshooting, we noticed that the logs showed the line `Persisted data detected. Restoring...` because it was reusing the same PV as the old version. That fresh environment test I did yesterday has that same line in the logs. Here's the opening sequence of logs:

```
[38;5;6mrabbitmq [38;5;5m19:14:43.40 [0m
[38;5;6mrabbitmq [38;5;5m19:14:43.48 [0m[1mWelcome to the Bitnami rabbitmq container[0m
[38;5;6mrabbitmq [38;5;5m19:14:43.49 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-rabbitmq[0m
[38;5;6mrabbitmq [38;5;5m19:14:43.49 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-rabbitmq/issues[0m
[38;5;6mrabbitmq [38;5;5m19:14:43.49 [0m
[38;5;6mrabbitmq [38;5;5m19:14:43.50 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ setup **
[38;5;6mrabbitmq [38;5;5m19:14:43.58 [0m[38;5;2mINFO [0m ==> Validating settings in RABBITMQ_* env vars..
[38;5;6mrabbitmq [38;5;5m19:14:43.70 [0m[38;5;2mINFO [0m ==> Initializing RabbitMQ...
**[38;5;6mrabbitmq [38;5;5m19:14:43.87 [0m[38;5;2mINFO [0m ==> Persisted data detected. Restoring...**
[38;5;6mrabbitmq [38;5;5m19:14:43.88 [0m[38;5;2mINFO [0m ==> ** RabbitMQ setup finished! **

[38;5;6mrabbitmq [38;5;5m19:14:43.92 [0m[38;5;2mINFO [0m ==> ** Starting RabbitMQ **
Configuring logger redirection
2021-09-08 19:15:02.973 [debug] <0.289.0> Lager installed handler error_logger_lager_h into error_logger
2021-09-08 19:15:03.070 [debug] <0.292.0> Lager installed handler lager_forwarder_backend into error_logger_lager_event
2021-09-08 19:15:03.070 [debug] <0.295.0> Lager installed handler lager_forwarder_backend into rabbit_log_lager_event
2021-09-08 19:15:03.070 [debug] <0.298.0> Lager installed handler lager_forwarder_backend into rabbit_log_channel_lager_event
2021-09-08 19:15:03.070 [debug] <0.301.0> Lager installed handler lager_forwarder_backend into rabbit_log_connection_lager_event
2021-09-08 19:15:03.070 [debug] <0.304.0> Lager installed handler lager_forwarder_backend into rabbit_log_feature_flags_lager_event
2021-09-08 19:15:03.070 [debug] <0.307.0> Lager installed handler lager_forwarder_backend into rabbit_log_federation_lager_event
2021-09-08 19:15:03.070 [debug] <0.310.0> Lager installed handler lager_forwarder_backend into rabbit_log_ldap_lager_event
2021-09-08 19:15:03.074 [debug] <0.313.0> Lager installed handler lager_forwarder_backend into rabbit_log_mirroring_lager_event
2021-09-08 19:15:03.076 [debug] <0.316.0> Lager installed handler lager_forwarder_backend into rabbit_log_prelaunch_lager_event
2021-09-08 19:15:03.081 [debug] <0.319.0> Lager installed handler lager_forwarder_backend into rabbit_log_queue_lager_event
2021-09-08 19:15:03.085 [debug] <0.322.0> Lager installed handler lager_forwarder_backend into rabbit_log_ra_lager_event
2021-09-08 19:15:03.089 [debug] <0.325.0> Lager installed handler lager_forwarder_backend into rabbit_log_shovel_lager_event
2021-09-08 19:15:03.093 [debug] <0.328.0> Lager installed handler lager_forwarder_backend into rabbit_log_upgrade_lager_event
```

That `Persisted data detected. Restoring...` line shows up when we first experienced this issue and during my test yesterday, which according to section around lines [751-752 of librabbitmq.sh](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L751) means that the set password command didn't get run. Is that accurate?

I couldn't find where `RABBITMQ_DATA_DIR` is being set.

**Comment by yilmi** [comment]
@btlyken, indeed, the `Persisted data detected.` means indeed that the container picked some existing conf/data. Regarding `RABBITMQ_DATA_DIR` it is defined in a different script that should defines all the environment variables used by the container. 

The definition of this variable happens in [rabbitmq-env.sh - L88-L91](https://github.com/bitnami/bitnami-docker-rabbitmq/blob/6977a2a71dcb3a8d95819c9bb6773277b0c3864b/3.8/debian-10/rootfs/opt/bitnami/scripts/rabbitmq-env.sh#L88-L91) and should be `/bitnami/rabbitmq/mnesia`

**Comment by miraculixx** [comment]
The rationale and resolution is described here https://github.com/bitnami/charts/pull/3155#issuecomment-685403289

**Comment by danvy** [comment]
A hard reset as described by @miraculixx works but it is far from being acceptable in production.
A little bit less harmful way is to delete the PVC then delete the RabbitMQ Pod. No need to re-deploy the chart.
