### ISSUE TITLE
[bitnami/concourse] Allow PostgreSQL image registry setting to be set

### ISSUE THREAD

**Issue by ekultails** [bitnami/charts#7349]
**Which chart**:
Concourse and all existing versions of it.

**Is your feature request related to a problem? Please describe.**
The `global.imageRegistry` value does not get inherited into the PostgreSQL Helm chart which is installed as a dependency. This leads to Concourse being deployed without a working database in our Internet-restricted environment. Concourse is not usable without a database.

**Describe the solution you'd like**
Configurable values to add to the Concourse Helm chart regarding the PostgreSQL dependency:
- Image repository
- Image name
- Image version

**Describe alternatives you've considered**
Currently, we disable PostgreSQL and manually install it separately.

**Comment by marcosbc** [comment]
Hi @ekultails, it should be possible to configure such options by prepending `postgresql.` to any of the options supported by the [PostgreSQL chart](https://github.com/bitnami/charts/blob/master/bitnami/postgresql), even if it does not appear in Concourse's `values.yaml` file.

For instance, `postgresql.global.imageRegistry` or `postgresql.image.repository`.

**Comment by ekultails** [comment]
Thank you for the quick response! I did not realize that all the options were exposed like that. I will close this GitHub issue for now and test it out in my lab. If I have any issues I will reopen this issue. Thanks again!
