### ISSUE TITLE
persistence.annotations not applied to PVC

### ISSUE THREAD

**Issue by afhtan** [bitnami/charts#7351]
I am setting persistence annotations via a values file and noticed that they are not being applied to the provisioned pvc.

The pvc.yaml template should be updated to check for persistence.annotations and apply them
https://github.com/bitnami/charts/blob/bc571361bffe4706f9c7182446ceca3d667658e4/bitnami/mongodb/templates/standalone/pvc.yaml#L13

```yaml
{{- if or .Values.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.persistence.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.persistence.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
```

**Comment by miguelaeh** [comment]
Thank you very much for reporting the issue, I created the PR reflecting those changes
