### ISSUE TITLE
unable to connect existing postgresql

### ISSUE THREAD

**Issue by yehaotong** [bitnami/charts#7357]
I have a pgsql and redis on my sql,and I want to use this for database,but when I set the env:
DISCOURSE_DATABASE_HOST:xxx.cluster.local(it is my pgsql host on k8s), and the database start failed,it failed log include:
Hostname postgresql.xxx.cluster.local could not be resolved, this could lead to connection issues;
ERROR ==> Could not connect to the database;
How can I use discourse to connect my pgsql

**Comment by yehaotong** [comment]
this host is a postgresql pod on k8s with service hostname,and this hostname can be resolvve and connect by other pod,
Therefore, I don't know whether the environment variables are configured incorrectly. The environment variables I configured in deployment are:
DISCOURSE_HOST: discourse.xxx.com
DISCOURSE_DATABASE_HOST: xxx.staging.svc.cluster.local
DISCOURSE_DATABASE_PORT_NUMBER: "5432"
DISCOURSE_DATABASE_USER: postgres
DISCOURSE_DATABASE_NAME: postgres
DISCOURSE_DATABASE_PASSWORD: xxx123
DISCOURSE_REDIS_HOST: redis-xxx.staging.svc.cluster.local
DISCOURSE_REDIS_PORT_NUMBER: "6379"
DISCOURSE_SMTP_HOST: smtp.gmail.com
DISCOURSE_SMTP_PORT: "587"
DISCOURSE_SMTP_USER: xxx@gmail.com
DISCOURSE_SMTP_PASSWORD: discourse123
DISCOURSE_SMTP_PROTOCOL: tls

**Comment by Mauraza** [comment]
Hi @yehaotong,

Could you tell us if you can connect to Postgresql with the following command? 

Remember to change the NAMESPACE and POSTGRES_PASSWORD

```bash
kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace NAMESPACE --image docker.io/bitnami/postgresql:11.13.0-debian-10-r12 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host postgresql -U postgres -d postgres -p 5432
```
