### ISSUE TITLE
[bitnami/redis] Sentinel containers in a sentinel deployment does not have the ability to add additional environment variables

### ISSUE THREAD

**Issue by gareth-horstmann** [bitnami/charts#7359]
**Which chart**:
bitnami/redis 15.2.0

**Is your feature request related to a problem? Please describe.**
#4970 was originally logged to add the extraEnvVars to sentinel but this only included the redis container.  It would also be useful to have the ability to add additional environment variables to the sentinel container too

**Describe the solution you'd like**
The *extraEnvVars*, *extraEnvVarsCM* and *extraEnvVarsSecret* added to the sentinel section of the sentinel/statefulset.yml

**Describe alternatives you've considered**
The *usePasswordFiles* property adds some of the environment variables that are needed to set the password from file but adds additional mapping that we do not need or will conflict with volume mounts we use for vault. 

**Additional context**
Our use case is that we integrate with hashicorp vault.  The credentials are pulled from vault and stored on a volume that we then mount to all of the relevant containers.  We need to be able to set the *REDIS_PASSWORD_FILE* in all of the relevant containers, pointing to the vault files.

**Comment by gareth-horstmann** [comment]
I have [forked](https://github.com/gareth-horstmann/charts) the project and made and tested the required changes with our use case.  I'll be happy to create a PR if that helps.

**Comment by alvneiayu** [comment]
hi @gareth-horstmann 

We are open to receive PRs and I will be really happy to review them. I invite you to do it.

Thanks a lot for your time and help

Álvaro
