### ISSUE TITLE
[bitnami/redis] sentinel hpa is now always created, besides that it is not used (15.2.X)

### ISSUE THREAD

**Issue by schmitch** [bitnami/charts#7360]
the last commit for redis always enabled the hpa: https://github.com/bitnami/charts/commit/a34880b435c1406b9654da25cb7e4adcd360331c#diff-315db354f46568e44ac1247c85cf17e873c3e75966985515cb4790e625ee5d49 however this is bad since hpa now is configured but will always fail since no `targetCPU` or `targetMemory` is configured.
autoscaling should be disabled if either both of these are `""` or if it is explictly disabled.
cluster tooling does not like hpa failures.

**Comment by dp-42** [comment]
I noticed the same issue - it applies to `sentinel` **and** also to `replicas`.

**Comment by pablogalegoc** [comment]
Thank you very much for spotting this folks, I've sent a PR to fix it
