### ISSUE TITLE
[bitnami/mongodb] Add runtimeClass support 

### ISSUE THREAD

**Issue by MixITGit** [bitnami/charts#7361]
**Which chart**:
Mongodb 10.24.1

**Is your feature request related to a problem? Please describe.**
It is currently not possible to specify custom runtimeClassName for mongodb resources

**Describe the solution you'd like**
Add runtimeClassName to helm chart

**Additional context**
With the ability to specify runtime class it will be possible to run this chart on clusters that support multiple runtimes such as runc alongside gVisor and/or FireCracker

**Comment by randradas** [comment]
Hi @MixITGit thank you for your feature request, it looks very interesting. I would like to encourage you to create a PR with the change needed, we would be glad to review it in order to add it to the next release.

**Comment by MixITGit** [comment]
Hello! I have already created a PR recently: https://github.com/bitnami/charts/pull/7362
I think this actually could be useful in other charts too :)
