### ISSUE TITLE
[bitnami/minio] persistence.mountPath not respected

### ISSUE THREAD

**Issue by matsch01** [bitnami/charts#7363]
**Which chart**:
minio 7.1.9

**Describe the bug**
Even though I'm setting persistence.mountPath, minio is still writing to /data inside the minio pod. When I check the deployed deployment yaml, the mountPath is set correctly.

```
volumeMounts:
            - name: data
              mountPath: /my-data
```

And the directory /my-data is created. In my case it is successfully bound to an nfs share and working.

However, minio still creates buckets in /data despite the fact that I don't see /data anywhere in my deployed yaml.

**To Reproduce**
1. Override persistence.mountPath 
2. Deploy chart
3. Create bucket
4. Exec into minio pod and see where the bucket was created. Was it created in persistence.mountPath, or /data?

**Expected behavior**
Buckets should be created in persistence.mountPath.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

- Output of `kubectl version`:

```
(Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by matsch01** [comment]
I figure this out. I left the persistence.mountPath as default (/data), then I had to change the runAs user and group to 1000 (ubuntu).

```
podSecurityContext:
    fsGroup: 1000
containerSecurityContext:
    runAsUser: 1000
```

And finally I had to change the owner of the NFS directory to ubuntu.

**Comment by matsch01** [comment]
I figure this out. I left the persistence.mountPath as default (/data), then I had to change the runAs user and group to 1000 (ubuntu).

```
podSecurityContext:
    fsGroup: 1000
containerSecurityContext:
    runAsUser: 1000
```

And finally I had to change the owner of the NFS directory to ubuntu.

**Comment by javsalgar** [comment]
Hi,

Looking at the container code, it currently doesn't make any sense to allow setting the mountPath. As you can see here, it's hardcoded https://github.com/bitnami/bitnami-docker-minio/blob/master/2021/debian-10/rootfs/opt/bitnami/scripts/libminio.sh#L30

I'm thinking of removing that value to avoid confusions. Out of curiosity, is there any reason why you would like to change the mountPath in this case?

**Comment by matsch01** [comment]
I attempted to change it because I was getting permission errors when I left it at /data. I was just fumbling around and trying things until I finally discovered the real issue. So no, I have to reason to change it. Thanks.
