### ISSUE TITLE
Add support for ingressClassName

### ISSUE THREAD

**Issue by AlexanderBabel** [bitnami/charts#7364]
**Which chart**:
For me personally: thanos (current version)
_But this should be done for all bitnami charts._

**Is your feature request related to a problem? Please describe.**
The old annotation `kubernetes.io/ingress.class` is deprecated and `ingressClassName` is the replacement. For further information see: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

**Describe the solution you'd like**
Add support for the `ingressClassName` property.

**Describe alternatives you've considered**
None.

**Additional context**
Related to: https://github.com/bitnami/charts/issues/5514 https://github.com/bitnami/charts/issues/5074 
PRs: https://github.com/bitnami/charts/pull/6848 https://github.com/bitnami/charts/pull/6849

**Comment by juan131** [comment]
Hi @AlexanderBabel 

Thanks so much for bringing us this topic! 

We should definitely adapt our charts parameters adding support to customize the "ingressClassName" when K8s > 1.18. Our charts should also be intelligent enough to ignore this field when it's not supported. Luckily, we already have a macro "common.ingress.supportsIngressClassname" in our common library that can help us with that and it's used in charts such as WordPress, see:

- https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_ingress.tpl#L45
- https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/ingress.yaml#L23

So.. it's just a matter to extend this approach to every Bitnami chart.

---

We have an ongoing task to standardize several features in the catalog that are only present in specific charts, so I'm going to add this topic to the list to ensure my colleagues also tackle this.

Thanks again for reporting it.

**Comment by randradas** [comment]
PR associated here: https://github.com/bitnami/charts/pull/7374

**Comment by brianmay** [comment]
It looks like this is required for ingress-nginx chart 4.0 and above.

**Comment by juan131** [comment]
Hi @brianmay 

As I mentioned on a previous comment, we have an ongoing task to standardize several features in the charts catalog. The team is currently working on the list of items that should be standardized, and once we have the final list we'll start adding al these feature ordered by priority. I can already advance you that adding the `ingressClassName` on every Ingress manifest is on that list.

**Comment by knyttl** [comment]
Migrating to https://github.com/kubernetes/ingress-nginx fixed this for me.

**Comment by juan131** [comment]
Our efforts on the standardization are WIP, you just need to browse the "open prs" and search for the ones including _"Chart standarized"_, see:

- https://github.com/bitnami/charts/pulls?q=is%3Apr+is%3Aopen++Chart+standarized

As you can see in these PRs, we're adding the `ingressClassName` as part of this work. Soon a PR do the same for Thanos will be created.

**Comment by brsolomon-deloitte** [comment]
bitnami/spark would benefit from this also, not seeing it on that list at the moment.

**Comment by juan131** [comment]
Yes, the plan also includes Spark @brsolomon-deloitte 
We've been slower than expected working on this standardization due to huge amount of changes that it implied for certain charts, but we're still working on it and sooner or later every chart will include these features.
