### ISSUE TITLE
[bitnami/contour] Contour ingressClass values.yaml confusion

### ISSUE THREAD

**Issue by mihaisee** [bitnami/charts#7372]
**Chart**
[[bitnami/contour](https://github.com/bitnami/charts/tree/master/bitnami/contour)]

**Describe the bug**
The values spec has the [`ingressClass`](https://github.com/bitnami/charts/blob/f01935dbde4e3bd9e38106e264e201372ccac710/bitnami/contour/values.yaml#L264
) under `contour` key but the [template implementation](https://github.com/bitnami/charts/blob/f01935dbde4e3bd9e38106e264e201372ccac710/bitnami/contour/templates/contour/deployment.yaml#L71) expects the `ingressClass` at top level -> `{{- if .Values.ingressClass }}`

**To Reproduce**
Install the chart with values as specified in the `values.yaml`:
```yaml
contour:
  ingressClass: contourcustom
```
The parameter is ignored and the deployment misses the `--ingress-class-name` arg.

The deployment should use the specs stated in `values.yaml` or the `values.yaml` should be updated to avoid confusion.

Thanks!
Let me know if there are additional details needed.

**Comment by alvneiayu** [comment]
hi @mihaisee 

I created a PR to fix the problem reported. If you want to take a look the solution.

Thanks a lot for your help and time.

Álvaro
