### ISSUE TITLE
[bitnami/redis-cluster] Recreated deleted node not joining to redis cluster

### ISSUE THREAD

**Issue by ashok-shukla** [bitnami/charts#7377]
**Which chart:**
bitnami/redis-cluster
version: 4.2.5

**Configuration**
 redis cluster with 9 nodes( 3 master and 2 replica for each master). 

**Describe the bug**
During os update redis nodes are recreated and these recreated nodes are not joining back to redis cluster. So all 9 nodes become  individual master node with no slots.  We are doing os update of one VM at a time. This causes the complete outage for us.

Same happens when a node got deleted and recreated. (This can be used as reproducer of the issue.)

**Expected behavior**
I am expecting to add the recreated node as replica to the cluster and forget the failed nodes. So that by default recreated node will join replica of some available master which did not has right number of replicas.

I am open to suggestions/ideas.

**Comment by ashok-shukla** [comment]
Any suggestion/ideas on the issue i am facing? Let me know if more info needed.

**Comment by pablogalegoc** [comment]
Hi @ashok-shukla! Sorry for the late response, we had an outage on our support service last week and lost some cases.

> We are doing os update of one VM at a time. This causes the complete outage for us.

One VM for every master and replicas or one VM for all 9 nodes?

> So all 9 nodes become individual master node with no slots. [...]
Same happens when a node got deleted and recreated. (This can be used as reproducer of the issue.)

If I understand correctly, this behaviour is happening with the deletion of any node at any time?

**Comment by ashok-shukla** [comment]
Hi @pablogalegoc 

It is one VM for one node (master/replica). 

Yes it is happening with deletion of any node at any time.

**Comment by pablogalegoc** [comment]
@ashok-shukla I've tried to reproduce the issue but I've not been able to in my environment. When I kill a master and its replicas I see them rejoin the cluster. Could you paste the command you've used for the installation and what you are using for draining the Kubernetes node before OS upgrade? Also, any interesting logs you see could be very useful. Right now I'm a bit lost on what can be happening. Thanks!

**Comment by ashok-shukla** [comment]
Hi @pablogalegoc To reproduce the issue, run  kubectl delete pod redis-default-0 -n <namespace> command to delete the pod. It is any pod you delete (master or replica) like this, the newly created pod is not joining back to cluster. I do not see any interesting in the logs, as the node not joined to cluster. Just individual master with no slots.

For redis installation we used the provided helm chart with kubernetes artifacts(statefulset, services, post install job)  to create the cluster.  Helm command

helm upgrade --install  --namespace "asshukla" --timeout 3600s --force --set global.useSingleNamespace=true -f "values.yaml"  asshukla-redis .

We are using kubectl drain command to drain the node in os upgrade.

Let me know if you need more info to reproduce.

**Comment by pablogalegoc** [comment]
Here's what I'm doing
- Command to install:

`helm install redis-cluster bitnami/redis-cluster --set cluster.nodes=9 --set cluster.replicas=2 --version 4.2.5`
- Output of `cluster slots`:
```
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.244.1.16"  ← Master that is going to be killed
      2) (integer) 6379
      3) "6ce84c6c1aa93a15439aea2130fafc077e0ceee3"
   4) 1) "10.244.3.19"
      2) (integer) 6379
      3) "f05702cceb62159ce0bdb449a5d315391bee9c72"
   5) 1) "10.244.1.19"
      2) (integer) 6379
      3) "74f63d755545bcd4814f9b296f5ef2138245ab1e"
[...]
```
`10.244.1.16` corresponds to `pod/redis-cluster-0`
- Kill `pod/redis-cluster-0` with `kubectl delete pod/redis-cluster-0 --force`
- Logs of one of its replicas:
```
1:S 24 Sep 2021 11:49:16.161 # Connection with master lost.
1:S 24 Sep 2021 11:49:16.161 * Caching the disconnected master state.
1:S 24 Sep 2021 11:49:16.591 * Connecting to MASTER 10.244.1.21:6379
1:S 24 Sep 2021 11:49:16.591 * MASTER <-> REPLICA sync started
1:S 24 Sep 2021 11:48:11.968 # Address updated for node 6ce84c6c1aa93a15439aea2130fafc077e0ceee3, now 10.244.1.21:6379
1:S 24 Sep 2021 11:48:12.339 * Connecting to MASTER 10.244.1.21:6379
[...]
```
- Output of `cluster slots`:
```
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.244.1.21" ← New master
      2) (integer) 6379
      3) "6ce84c6c1aa93a15439aea2130fafc077e0ceee3"
   4) 1) "10.244.3.19" ← Replica that will take over in the next step
      2) (integer) 6379
      3) "f05702cceb62159ce0bdb449a5d315391bee9c72"
   5) 1) "10.244.1.19"
      2) (integer) 6379
      3) "74f63d755545bcd4814f9b296f5ef2138245ab1e"
[...]
```
Even after forcing a failover election:
```
1:S 24 Sep 2021 11:49:16.161 # Connection with master lost.
1:S 24 Sep 2021 11:49:16.161 * Caching the disconnected master state.
1:S 24 Sep 2021 11:49:16.591 * Connecting to MASTER 10.244.1.21:6379
1:S 24 Sep 2021 11:49:16.591 * MASTER <-> REPLICA sync started
1:S 24 Sep 2021 11:49:38.780 * FAIL message received from 8b99332080f4041622172e04a05c15fc1f154013 about 6ce84c6c1aa93a15439aea2130fafc077e0ceee3
1:S 24 Sep 2021 11:49:38.780 # Cluster state changed: fail
1:S 24 Sep 2021 11:49:38.781 # Start of election delayed for 588 milliseconds (rank #0, offset 84).
1:S 24 Sep 2021 11:49:39.383 # Starting a failover election for epoch 10.
1:S 24 Sep 2021 11:49:39.386 # Failover election won: I'm the new master.
1:S 24 Sep 2021 11:49:39.387 # configEpoch set to 10 after successful failover
1:M 24 Sep 2021 11:49:39.387 * Discarding previously cached master state.
1:M 24 Sep 2021 11:49:39.387 # Setting secondary replication ID to 2dc9e00ebdc5381de0206551c3d61a2066b021d5, valid up to offset: 85. New replication ID is f476d7eff1fd48f63036d31463f6b7b7c1c169f0
1:M 24 Sep 2021 11:49:39.387 # Cluster state changed: ok
[...]
```
That replica took over as master and the cluster is state is correct:
```
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.244.3.19" ← Replica promoted to master
      2) (integer) 6379
      3) "f05702cceb62159ce0bdb449a5d315391bee9c72"
   4) 1) "10.244.1.19"
      2) (integer) 6379
      3) "74f63d755545bcd4814f9b296f5ef2138245ab1e"
   5) 1) "10.244.1.22"
      2) (integer) 6379
      3) "6ce84c6c1aa93a15439aea2130fafc077e0ceee3"
```
Could you share the results of this same procedure but on your environment?

**Comment by ashok-shukla** [comment]
did  redis-cluster-0 joined back cluster?

**Comment by ashok-shukla** [comment]
1) Installation (values.yaml has the number of nodes and replica)
`helm upgrade --install --namespace "bitnami" --timeout 3600s --force --set global.useSingleNamespace=true -f "values.yaml" bitnami-redis .`

2) Before shutdown of node
2.1) kubectl exec -it redis-default-0 -n bitnami  -- redis-cli cluster slots

```
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "xxx.xxx.5.20"
      2) (integer) 6379
      3) "53ad970ee67f7057cd21cfc5a2e34e3ac1325354"
   4) 1) "xxx.xxx.6.14"
      2) (integer) 6379
      3) "0a761b926fd90400c35636c30b5e4c2fd68ba5f0"
   5) 1) "xxx.xxx.7.176"
      2) (integer) 6379
      3) "8f8d6fc83ab3b998282ab330c399d31dcf5e8051"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "xxx.xxx.8.27"
      2) (integer) 6379
      3) "4c20e10fa58eb8656943eac32ca4bb549eb9d91a"
   4) 1) "xxx.xxx.0.17"
      2) (integer) 6379
      3) "bb1dcd0722534ae891bd76a3943432d162b9c775"
   5) 1) "xxx.xxx.5.201"
      2) (integer) 6379
      3) "4992786f637e615820ee5c27d87c3dcc9485aff1"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "xxx.xxx.9.20"
      2) (integer) 6379
      3) "5ef5852df0e478ea80e3d3c9d9e741c322d512e9"
   4) 1) "xxx.xxx.3.80"
      2) (integer) 6379
      3) "2e8b1b741edd1642f081018bf3ba547911f34096"
   5) 1) "xxx.xxx.7.94"
      2) (integer) 6379
      3) "739c266b1729060689ce04dcc90615db6d8ff890"
```
     

3) delete redis-default-1  (4c20e10fa58eb8656943eac32ca4bb549eb9d91a)

`kubectl delete pod redis-default-1 -n bitnami --force`

4) After shutdown of redis-default-1
4.1) kubectl exec -it redis-default-0 -n bitnami  -- redis-cli cluster slots

```
1) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "xxx.xxx.5.20"
      2) (integer) 6379
      3) "53ad970ee67f7057cd21cfc5a2e34e3ac1325354"
   4) 1) "xxx.xxx.6.14"
      2) (integer) 6379
      3) "0a761b926fd90400c35636c30b5e4c2fd68ba5f0"
   5) 1) "xxx.xxx.7.176"
      2) (integer) 6379
      3) "8f8d6fc83ab3b998282ab330c399d31dcf5e8051"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "xxx.xxx.0.17"
      2) (integer) 6379
      3) "bb1dcd0722534ae891bd76a3943432d162b9c775"
   4) 1) "xxx.xxx.5.201"
      2) (integer) 6379
      3) "4992786f637e615820ee5c27d87c3dcc9485aff1"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "xxx.xxx.9.20"
      2) (integer) 6379
      3) "5ef5852df0e478ea80e3d3c9d9e741c322d512e9"
   4) 1) "xxx.xxx.3.80"
      2) (integer) 6379
      3) "2e8b1b741edd1642f081018bf3ba547911f34096"
   5) 1) "xxx.xxx.7.94"
      2) (integer) 6379
      3) "739c266b1729060689ce04dcc90615db6d8ff890"
```

4.2) recreated pod redis-default-1  log

```
redis-cluster 20:47:23.54 Welcome to the Bitnami redis-cluster container
redis-cluster 20:47:23.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 20:47:23.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 20:47:23.54 
redis-cluster 20:47:23.55 INFO  ==> ** Starting Redis setup **
redis-cluster 20:47:23.58 INFO  ==> Initializing Redis
redis-cluster 20:47:23.61 INFO  ==> Setting Redis config file
redis-cluster 20:47:23.66 INFO  ==> ** Redis setup finished! **

1:C 24 Sep 2021 20:47:23.690 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Sep 2021 20:47:23.690 # Redis version=6.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Sep 2021 20:47:23.690 # Configuration loaded
1:M 24 Sep 2021 20:47:23.691 * No cluster configuration found, I'm 700b7ba7ac1748192f8056b29ce7d611f88eae72
          _._                                                  
     _.-``__ ''-._                                             
_.-``    `.  `_.  ''-._           Redis 6.0.10 (00000000/0) 64 bit
.-`` .-```.  ```\/    _.,_ ''-._                                   
(    '      ,       .-`  | `,    )     Running in cluster mode
|`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
|    `-._   `._    /     _.-'    |     PID: 1
`-._    `-._  `-./  _.-'    _.-'                                   
|`-._`-._    `-.__.-'    _.-'_.-'|                                  
|    `-._`-._        _.-'_.-'    |           http://redis.io        
`-._    `-._`-.__.-'_.-'    _.-'                                   
|`-._`-._    `-.__.-'    _.-'_.-'|                                  
|    `-._`-._        _.-'_.-'    |                                  
`-._    `-._`-.__.-'_.-'    _.-'                                   
`-._    `-.__.-'    _.-'                                       
    `-._        _.-'                                           
        `-.__.-'                                               

1:M 24 Sep 2021 20:47:23.717 # Server initialized
1:M 24 Sep 2021 20:47:23.717 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 24 Sep 2021 20:47:23.718 * Ready to accept connections
```
      
5) cluster slots are fine when 1 or 2 nodes deleted. After delete of all nodes, slots are not ok, as all nodes are individual master.
5.1) kubectl exec -it redis-default-0 -n bitnami  -- redis-cli cluster slots
`(empty array)`


Let me k now if you need more info

**Comment by pablogalegoc** [comment]
I'll set some time aside to look into this more closely. Will get back to you if I find something or need more info. Thanks!

**Comment by pablogalegoc** [comment]
Hi @ashok-shukla,

I've been able to reproduce your problem when `persistence.enabled=false`. The default configuration is generated and loaded but it obviously doesn't have any info about the cluster. Do you by any chance have installed the chart without persistence?

**Comment by ashok-shukla** [comment]
Hi @pablogalegoc yes we have made persistence.enabled=false. As per our requirement, we do not want to store data in disk. We are storing data in database.

is it possible only store cluster info in disk and data in database?

**Comment by pablogalegoc** [comment]
Currently that it is not supported and the problem lies in the redis-custer image. If during the setup the container doesn't find a [node.sh](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh#L189) then tries to reinitialize the cluster. A workaround could be persisting the specific paths of the `nodes.sh` and `nodes.conf`. However, I'm going to file an internal issue to study a proper way to have this feature.

**Comment by ashok-shukla** [comment]
Hi @pablogalegoc we have enabled the persistence in values.yaml file. Also we have edited the redis conf to make save "" and rdb-del-sync-files yes.  We see data is not stored in the disk (for some period of time it may store data in disk to sync with replica, which is accepted). is this configuration fine to not store data in disk?

As a org requirement we need to know, what redis cluster configuration is stored in disk. Please provide more details on this.

**Comment by juan131** [comment]
Hi @ashok-shukla 

You can inspect what data is persisted by exploring the files under the `/bitnami/redis/data` directory since this is the default path used to mount the persistent volumes, see:

- https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/values.yaml#L280

**Comment by carrodher** [comment]
Thanks for reporting this issue.
After some time and due to other priorities the team has, this task was not prioritized and there are no signs that it will be prioritized in the mid-term. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
