### ISSUE TITLE
[bitnami/mongodb] Option for using emptyDir with medium: memory

### ISSUE THREAD

**Issue by MikaelElkiaer** [bitnami/charts#7382]
**Which chart**:
mongodb

**Is your feature request related to a problem? Please describe.**
I am using mongodb as a cache running in memory only.

**Describe the solution you'd like**
I would like to set the emptyDir which is used in case of `persistence: false` to `medium: memory`.

**Describe alternatives you've considered**
Well, using something else than mongo. :)

**Additional context**

**Comment by MikaelElkiaer** [comment]
This is not really useful unless #5752 gets fixed.

**Comment by pablogalegoc** [comment]
Hi @MikaelElkiaer! Sorry for the late response, we had an outage on our support service last week and lost some cases.
Indeed the issue you point is going to be blocking for this. Those kind of reworks in the Docker images may take time. I'm going to mention your use case in the task and see if it can get some traction but, as my teammate said, we can't give an ETA, sorry.

**Comment by MikaelElkiaer** [comment]
No problem.

**Comment by MikaelElkiaer** [comment]
Actually, I don't think this is an image change - correct me if I am wrong.
It is a mater of switching from using emptyDir in memory, as opposed to the node's filesystem.
Unless I am wrong, it should be a matter of changing the template to allow switching between default and memory when having persistence to false (i. e. using emptyDir).

**Comment by pablogalegoc** [comment]
IMO we'll have to change the logic of the initialization scripts in the image. If `pod-0` loses its data, for example by having set `emptyDir` but being rescheduled on another cluster node, the MongoDB cluster won't be able to recover because when `pod-0` is restored, it will be again configured as a Primary replica and then reconnected to the cluster, which has already assigned a new Primary replica automatically.

**Comment by MikaelElkiaer** [comment]
Isn't that a separate problem? Running emptyDir will cause that problem, no matter if it is memory or local fs.

I am already running a single node replica set due to that problem, so in my case it won't matter.

**Comment by pablogalegoc** [comment]
Ah, my bad, I misunderstood what you wanted here once I started to dive into the issue linked above. I'm sorry 🤦 
> Running emptyDir will cause that problem, no matter if it is memory or local fs.

Yes, you are 100% right. However we usually don't provide this as a configurable parameter. We use it in special cases like [this](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/README.md#use-a-volume-for-devshm) or for ssl certs:
https://github.com/bitnami/charts/blob/3d7ca74b3b732b0620497ae7b399545117510209/bitnami/testlink/templates/deployment.yaml#L319-L325
Right now the only exception is Redis:
https://github.com/bitnami/charts/blob/a9a4154cf96041c3f6a7261ebe77ef21ea5a6de7/bitnami/redis/values.yaml#L364-L366
If you think this is an interesting addition to the MongoDB you are very welcome to submit a PR! Redis should be a good example

**Comment by MikaelElkiaer** [comment]
@pablogalegoc I added a PR #8238.
