### ISSUE TITLE
Redis liveness and readiness probes shell scripts do not exist in container

### ISSUE THREAD

**Issue by mschuchard** [bitnami/charts#7388]
**Which chart**:
Redis 15.3.0

**Describe the bug**
Redis liveness and readiness probes shell scripts do not exist in container

**To Reproduce**

1. `helm install <release-name> bitnami/redis`

Note that this is a standalone architecture with no persistence.

**Expected behavior**
The liveness and readiness probe scripts exist in the container.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
3.5.4
```

- Output of `kubectl version`:

```
1.22.1
```

**Additional context**
`kubcetl describe`
> Readiness probe failed: sh: /health/ping_readiness_local.sh: not found
Liveness probe failed: sh: /health/ping_liveness_local.sh: not found

in container:
`ls -l /health`
> lrwxrwxrwx    1 root     root            29 Sep  2 13:58 ping_liveness_local.sh -> ..data/ping_liveness_local.sh
lrwxrwxrwx    1 root     root            40 Sep  2 13:58 ping_liveness_local_and_master.sh -> ..data/ping_liveness_local_and_master.sh
lrwxrwxrwx    1 root     root            30 Sep  2 13:58 ping_liveness_master.sh -> ..data/ping_liveness_master.sh
lrwxrwxrwx    1 root     root            30 Sep  2 13:58 ping_readiness_local.sh -> ..data/ping_readiness_local.sh
lrwxrwxrwx    1 root     root            41 Sep  2 13:58 ping_readiness_local_and_master.sh -> ..data/ping_readiness_local_and_master.sh
lrwxrwxrwx    1 root     root            31 Sep  2 13:58 ping_readiness_master.sh -> ..data/ping_readiness_master.sh

in container:
`ls -l /data`
> empty directory

in Helm chart for Redis master statefulset:
```yaml
...
volumeMounts:
  - name: redis-data
    mountPath: /data
...
volumes:
  - name: redis-data
    emptyDir: {}
```

which would appear to be root cause.

Update: indeed, disabling persistence will cause an empty `/data` and breaks the probes.

**Comment by pablogalegoc** [comment]
Hi @mschuchard!

If I understand correctly, these are the settings you are using:
```yaml
architecture: standalone
master:
  persistence:
    enabled: false
```
If I execute `kubectl describe`
```
Liveness:       exec [sh -c /health/ping_liveness_local.sh 5] delay=20s timeout=6s period=5s #success=1 #failure=5
Readiness:      exec [sh -c /health/ping_readiness_local.sh 1] delay=20s timeout=2s period=5s #success=1 #failure=5
```
But I see an interesting difference in my output of `ls -l /health`:
```diff
- lrwxrwxrwx 1 root root 29 Sep 2 13:58 ping_liveness_local.sh -> ..data/ping_liveness_local.sh
+ lrwxrwxrwx 1 root 1001 29 Sep  3 08:47 ping_liveness_local.sh -> ..data/ping_liveness_local.sh
```
Could you confirm if the parameters above are those that you are using? Thanks!

**Comment by mschuchard** [comment]
Yes, disabling persistence causes broken symlinks to the health checks from the configmap. In the interim, I will just override the built in probes with some custom probes when persistence is disabled.

**Comment by pablogalegoc** [comment]
@mschuchard the thing is that with the parameters I've set above I do see the probes being picked without issues running `kubectl describe`. It's true that if I `ls -l /data` I just see
```
total 0
-rw-r--r-- 1 1001 1001 0 Sep  6 11:22 appendonly.aof
```
However, `..data` is not `/data`. The symlink of `/health/ping_liveness_local.sh` points to `..data/ping_liveness_local.sh`. If you run  `ls -l /health/..data` you should see something like
```
lrwxrwxrwx 1 root 1001 31 Sep  6 11:22 /health/..data -> ..2021_09_06_11_22_10.106623712
```
and, finally, if you `ls -l /health/..2021_09_06_11_22_10.106623712`:
```
I have no name!@redis-master-0:/$ ls -l /health/..2021_09_06_11_22_10.106623712
total 24
-rwxr-xr-x 1 root 1001 402 Sep  6 11:22 ping_liveness_local.sh
-rwxr-xr-x 1 root 1001 177 Sep  6 11:22 ping_liveness_local_and_master.sh
-rwxr-xr-x 1 root 1001 460 Sep  6 11:22 ping_liveness_master.sh
-rwxr-xr-x 1 root 1001 331 Sep  6 11:22 ping_readiness_local.sh
-rwxr-xr-x 1 root 1001 179 Sep  6 11:22 ping_readiness_local_and_master.sh
-rwxr-xr-x 1 root 1001 389 Sep  6 11:22 ping_readiness_master.sh
```
So my guess is that either we are setting different parameters or the issue is with `root root` vs `root 1001`. Could you paste your `values.yaml`? Thanks!

**Comment by mschuchard** [comment]
Ok I will try it again for self-reproduction purposes and let you know the results. If I can work the group owner angle and that resolves the issue, then I will try to dig further in that direction. Otherwise, I will surely share the `values.yaml` diff from the default. Thanks!

**Comment by pablogalegoc** [comment]
Sounds good! Happy to help whenever needed

**Comment by mschuchard** [comment]
Ok I am rolling with persistence enabled now, so that is indeed not root cause because the issue persists. The group owner for the symlinks in `/health` is still `root`. Interestingly, the group owners for the files in `/health..data` is `1337`. Since these differ without any software provisioning during container initialization, it would be reasonable to assume it is due to image and not the container. In that case, it probably is more relevant to mention I am using the official Redis images and not the Bitnami images for the master and replicas (but the Bitnami image for the Prometheus exporter).

Another interesting note is that while the same error occurs during container initialization, if I exec into the container with a generic shell, I can actually execute the scripts from the `/health` directory. That would also imply permissions I would believe.

I tried changing the `fsGroup` and `runAsUser` values for the master and replicas to `1337`, and unfortunately the same `file not found` errors are thrown for the health check scripts. I note that those values are not configurable for the exporter, but cannot conceive of a situation where I would not be using the Bitnami image for that use case.

**Comment by migruiz4** [comment]
Hi @mschuchard,

I'm sorry but we can not provide further support if you are using different images, as we can not ensure the chart will work properly. 

We test our chart using Bitnami images, so finding issues during operation when using different images could be expected.

Does the issue persist using the image `bitnami/redis`?

**Comment by mschuchard** [comment]
Ok I did not see anything about that in the documentation, but I can continue using the custom health checks. I would have imagined changing the user and group from `1001` to `1337`, but I guess that is another mystery.

Thanks for the time and effort in the interim.
