### ISSUE TITLE
[bitnami/redis] Wrong sentinel description in README

### ISSUE THREAD

**Issue by FloLaco** [bitnami/charts#7390]
**Which chart**:
The name (and version) of the affected chart : redis

**Describe the bug**
The README say : 

> When installing the chart with architecture=replication and sentinel.enabled=true, it will deploy a Redis™ master StatefulSet (only one master allowed) and a Redis™ replicas StatefulSet.

But there is only 1 StatefulSet deployed : 
```
$ helm install redis-dev -f values.yaml bitnami/redis
$ kubectl get statefulsets.apps
NAME             READY   AGE
redis-dev-node   1/1     10m
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. This is definitely a leftover from the previous architecture, where we did deploy two StatefulSets. As you discovered it, would you like to submit a PR fixing it?
