### ISSUE TITLE
[bitnami/redis] Sentinel container fails on 2nd redis-ha node

### ISSUE THREAD

**Issue by HighWatersDev** [bitnami/charts#7392]
**Which chart**:
Redis:15.3.0

**Describe the bug**
When installing Redis, redis-ha-node-0 gets deployed just fine with all its containers running. When 2nd node redis-ha-node-1 gets deployed, sentinel container keeps crashing with the following error:

```
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Could not connect to Redis at redis-ha.default.svc.cluster.local:26379: Connection refused

*** FATAL CONFIG FILE ERROR (Redis 6.2.5) ***
Reading the configuration file, at line 3
>>> 'sentinel monitor masterset 2'
Unrecognized sentinel configuration statement.
```

**To Reproduce**

helm install redis-ha bitnami/redis -f redis-ha-values
[redis-ha-values.txt](https://github.com/bitnami/charts/files/7100306/redis-ha-values.txt)

**Expected behavior**

Expected all services to be running

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-16T01:10:02Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by HighWatersDev** [comment]
Additional info: this seems to only happen when I add this section to values.yaml

```
tls:
  enabled: true
  authClients: true
  autoGenerated: true
```

**Comment by HighWatersDev** [comment]
Any update on this? It seems there are some issues running Redis Sentinel with TLS enabled.

**Comment by marcosbc** [comment]
Hi @HighWatersDev, thanks for reporting this issue, I've been able to reproduce it with your instructions.

It seems like when enabling TLS, the configuration in `/opt/bitnami/redis-sentinel/etc/sentinel.conf` is wrongly populated:

```
dir "/tmp"
port 26379
sentinel monitor mymaster   2
sentinel down-after-milliseconds mymaster 60000
sentinel failover-timeout mymaster 18000
sentinel parallel-syncs mymaster 1
# User-supplied sentinel configuration:
# End of sentinel configuration
sentinel auth-pass mymaster PASSWORD
requirepass PASSWORD
sentinel myid de8841619c756ad415b6e38b07143777125ea94a

sentinel known-sentinel mymaster 10.x.y.z 26379 e2f8fd2cf25173b0854eb276d26a85fd9dfd9551

sentinel known-replica mymaster 10.x.y.z 6379

sentinel known-replica mymaster 10.x.y.z 6379
```

The expected format should be more similar to this:

```
dir "/tmp"
port 26379
sentinel monitor mymaster 10.x.y.z 6379 2
sentinel down-after-milliseconds mymaster 60000
sentinel failover-timeout mymaster 18000

# User-supplied sentinel configuration:
# End of sentinel configuration
sentinel auth-pass mymaster PASSWORD
requirepass "PASSWORD"
sentinel myid b1d6145c0d067baa31e621703d6d55971b29de14

sentinel known-sentinel mymaster 10.x.y.z 26379 fc850ebd73b5f4178bdce71f4675b694eb6fe534

sentinel known-replica mymaster 10.x.y.z 6379
# Generated by CONFIG REWRITE
protected-mode no
user default on #c8abe99dd79a9428876d3ceafc97134ee690328bd9088f9b11e038d7e0cf9b96 ~* &* +@all
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel known-replica mymaster 10.x.y.z 6379
sentinel current-epoch 0
```

Unfortunately I don't know what is wrong at this moment, so I'm going to create an internal task for investigating this issue.

**Comment by HighWatersDev** [comment]
Hi,

Any update on this issue?

**Comment by marcosbc** [comment]
Unfortunately not @HighWatersDev. We also received a similar report in #7431 but we have not had the chance to start looking into this yet.

**Comment by marcosbc** [comment]
That is great @giovannibaratta! Would you be up to contributing that fix via a PR? We'd be glad to help with the review and release of the changes.

**Comment by miguelaeh** [comment]
Hi guys,
could you check if the above PR solves the issue, please?
I tested it and it removes some TLS errors with the sentinel containers

**Comment by david-sykora** [comment]
Thank you for the great implementation of this feature! I have been testing it since merge and it works well. The only thing I noticed is that the master service is not compatible with `useHostnames: false` ([used as a work around for tilt mode problems](https://github.com/bitnami/charts/issues/7431)) because of the way how **start-node.sh** script gets the pod name ([this regex ](https://github.com/bitnami/charts/blob/55e4ffce3fbf03a8fd7ae7f9750de7b265ad31f0/bitnami/redis/templates/scripts-configmap.yaml#L372)does not work for IP addresses for obvious reasons). I'll try to fix this issue.

**Comment by david-sykora** [comment]
This patch apparently solved the issue:
```
diff --git a/bitnami/redis/templates/scripts-configmap.yaml b/bitnami/redis/templates/scripts-configmap.yaml
index 082de68..6671036 100644
--- a/bitnami/redis/templates/scripts-configmap.yaml
+++ b/bitnami/redis/templates/scripts-configmap.yaml
@@ -369,7 +369,11 @@ data:
     {{- if .Values.sentinel.service.createMaster }}
     if [[ "${REDIS_REPLICATION_MODE}" == "master" ]]; then
         # Add isMaster label to master node for master service
+        {{- if .Values.useHostnames }}
         echo "${REDIS_MASTER_HOST/.*}" > /etc/shared/current
+        {{- else }}
+        echo "${HOSTNAME}" > /etc/shared/current
+        {{- end }}
     fi
     {{- end }}
```
I'll do more testing and let you know what will be the results of longer-term usage.
