### ISSUE TITLE
[bitnami/ghost] upgrade ghost into container

### ISSUE THREAD

**Issue by qdupuy** [bitnami/charts#7400]
Hello,

I would like to update the ghost instance but I am having various problems.

Here is the error message :

```
ghost@pods-6d97f85fff-jsbvb:/opt/bitnami/ghost$ ghost udpate
✔ Checking system Node.js version - found v14.17.3
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✔ Checking for latest Ghost version

# 4.12.1

* 🐛 Fixed validation error when saving pages in admin area - Kevin Ansfield

---

View the changelogs for full details:
* Ghost - https://github.com/tryghost/ghost/compare/v4.12.0...v4.12.1
* Admin - https://github.com/tryghost/admin/compare/v4.12.0...v4.12.1

✔ Fetched release notes
✖ Downloading and updating Ghost to v4.12.1
An error occurred.
Message: 'EACCES: permission denied, mkdir '/opt/bitnami/ghost/versions/4.12.1''


Debug Information:
    OS: Debian GNU/Linux, v10
    Node Version: v14.17.3
    Ghost Version: 4.8.4
    Ghost-CLI Version: 1.17.3
    Environment: production
    Command: 'ghost udpate'

Additional log info available in: /.ghost/logs/ghost-cli-debug-2021-09-03T13_15_17_107Z.log

Try running ghost doctor to check your system for known issues.
```

I wanted to use the sudo command but it is not available and I can't install it.

I also played with the runas to run as root but ghost asks me to mount the version only with a non-root user

Is there a method to update your image?

Don't tell me to change the version on the image, it won't work. I have to migrate my sql schema from my ghost instance, so I need to update it before changing the image to the version I want to install

thank you for your advance

**Comment by yilmi** [comment]
Hi @qdupuy,

Thanks for reporting this issue! 

When using the Bitnami charts the way to upgrade is through the `helm upgrade` command, upgrading inside the container is not supported and defeats the purpose of consuming releases through docker images.

If you have an issue when performing the upgrade, I would suggest follow the [Ghost project procedure, updating to the latest minor before jumping to a major](https://ghost.org/docs/update/).

Based on their documentation, you'd need to check which is the Ghost version for each of our Chart release (APP VERSION):
```
# helm search repo bitnami/ghost --version ^14 -l
NAME         	CHART VERSION	APP VERSION	DESCRIPTION                                       
bitnami/ghost	14.0.13      	4.12.1     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.12      	4.12.1     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.10      	4.11.0     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.9       	4.10.2     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.7       	4.10.1     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.6       	4.10.1     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.5       	4.10.0     	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.4       	4.9.3      	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.3       	4.9.2      	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.2       	4.9.1      	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.1       	4.9.0      	A simple, powerful publishing platform that all...
bitnami/ghost	14.0.0       	4.8.4      	A simple, powerful publishing platform that all...
```

Again, following their documentation and looking at the APP VERSION, you could upgrade through the following versions:
1. Upgrade to version Ghost 4.9.3 (Chat version 14.0.4)
2. Upgrade to version Ghost 4.10.2 (Chat version 14.0.9)
3. Upgrade to version Ghost 4.11.0 (Chat version 14.0.10)
5. Upgrade to version Ghost 4.12.1 (Chat version 14.0.13)

I assume they require that to ensure, schema changes are applied consistently.

To provide the target chart version when upgrading, you can use the `--version` switch:
```
# helm upgrade your-chart-name bitnami/ghost --version 14.0.4 
```

I hope this is helpful, otherwise please try to tell us more about the issue you're having. I would also recommend checking Ghost's asks on the web.

Thanks,
Yass

**Comment by qdupuy** [comment]
What you say is the end goal I want however when I migrate to 4.9.x I get an error on the sql migration `Error occurred while executing the following migration: 03-add-products-benefits-table.js` Saying that he can't create the table because of the foreign key

**Comment by beltran-rubo** [comment]
In that case it looks an application specific issue. Please check this report and request for help there https://github.com/TryGhost/Ghost/issues/13138

**Comment by qdupuy** [comment]
Hello,

No, it doesn't help me.

On the next production run, I'll give you the whole output

**Comment by qdupuy** [comment]
I have just tried a migration :

```
- Inspecting operating system
[2021-09-10 11:42:46] INFO Ghost is running in production...
[2021-09-10 11:42:46] INFO Your site is now available on https://x/
[2021-09-10 11:42:46] INFO Ctrl+C to shut down
[2021-09-10 11:42:46] INFO Ghost server started in 1.126s
[2021-09-10 11:42:47] WARN Database state requires migration.
[2021-09-10 11:42:49] INFO Creating database backup
[2021-09-10 11:42:49] INFO Database backup written to: /bitnami/ghost/content/data/x-blog.ghost.2021-09-10-11-42-49.json
[2021-09-10 11:42:49] INFO Adding posts_meta.feature_image_alt column
[2021-09-10 11:42:49] INFO Adding posts_meta.feature_image_caption column
[2021-09-10 11:42:49] INFO Adding "portal_products" record to "settings" table with product - 6092756d29bf23000188d5d7
[2021-09-10 11:42:49] INFO Skipping migration of newsletter_show_header setting. Matches new defaults
[2021-09-10 11:42:49] INFO Deleting newsletter_show_header setting
[2021-09-10 11:42:49] INFO Adding permission for resetAllPasswords:authentication
[2021-09-10 11:42:49] WARN Adding permission(Reset all passwords) to role(Administrator)
[2021-09-10 11:42:49] INFO Adding table: benefits
[2021-09-10 11:42:50] INFO Adding table: products_benefits
[2021-09-10 11:42:50] INFO Dropping table: products_benefits
[2021-09-10 11:42:50] INFO Dropping table: benefits
[2021-09-10 11:42:50] INFO Removing permission(Reset all passwords) from role(Administrator)
[2021-09-10 11:42:50] INFO Removing permission for resetAllPasswords:authentication
[2021-09-10 11:42:50] INFO Adding newsletter_show_header setting
[2021-09-10 11:42:50] INFO Deleting newsletter_show_header_{title,icon} settings
[2021-09-10 11:42:50] INFO Reverting portal_products setting to empty array
[2021-09-10 11:42:50] INFO Removing posts_meta.feature_image_caption column
[2021-09-10 11:42:50] INFO Removing posts_meta.feature_image_alt column
[2021-09-10 11:42:50] ERROR alter table `products_benefits` add constraint `products_benefits_product_id_foreign` foreign key (`product_id`) references `products` (`id`) on delete CASCADE - ER_CANT_CREATE_TABLE: Can't create table `x_blog_ghost`.`products_benefits` (errno: 150 "Foreign key constraint is incorrectly formed")

alter table `products_benefits` add constraint `products_benefits_product_id_foreign` foreign key (`product_id`) references `products` (`id`) on delete CASCADE - ER_CANT_CREATE_TABLE: Can't create table `x_blog_ghost`.`products_benefits` (errno: 150 "Foreign key constraint is incorrectly formed")

{"config":{"transaction":false},"name":"03-add-products-benefits-table.js"}
"Error occurred while executing the following migration: 03-add-products-benefits-table.js"

Error ID:
    300

Error Code: 
    ER_CANT_CREATE_TABLE

----------------------------------------

InternalServerError: alter table `products_benefits` add constraint `products_benefits_product_id_foreign` foreign key (`product_id`) references `products` (`id`) on delete CASCADE - ER_CANT_CREATE_TABLE: Can't create table `x_blog_ghost`.`products_benefits` (errno: 150 "Foreign key constraint is incorrectly formed")
    at DatabaseStateManager.makeReady (/opt/bitnami/ghost/versions/4.9.3/core/server/data/db/state-manager.js:98:32)
    at async initDatabase (/opt/bitnami/ghost/versions/4.9.3/core/boot.js:57:5)
    at async bootGhost (/opt/bitnami/ghost/versions/4.9.3/core/boot.js:320:9)
 ```

**Comment by yilmi** [comment]
Hi @qdupuy, please note that we are not maintainer of the Ghost upstream project. We provide an easy way to consume and run the project and if there's an issue with the container image or chart, that's where we can help. But we can't realistically be expected to maintain upstream projects, given the complexity and diverse technologies used.

What seems to be happening here is that you're hitting an issue during Ghost's migration scripts execution, in your case the following script is failing: `03-add-products-benefits-table.js`
>"Error occurred while executing the following migration: 03-add-products-benefits-table.js"

The issue @beltran-rubo directed you to is another migration issue, very similar to yours (just happening one migration script earlier).

What you could do to progress here?
- If you have updated from 4.8.4 to 4.9.3, try smaller increments just in case migration scripts between bigger increments are missing some changes
- Get help from Ghost's project community and perhaps open an issue after [reviewing the existing ones](https://github.com/TryGhost/Ghost/issues)
- You could also depending on the urgency, try to understand what constraint are blocking the update and get them

I'm sure you already have them, but it's always worth mentioning, make sure you have backups just in case

**Comment by qdupuy** [comment]
I'm trying to make the 4.8.4 version to the 4.9.3 version but I still have my problem.

And on the Internet, I find everything and anything that doesn't necessarily help me.
