### ISSUE TITLE
[bitnami/kibana] Deployment fails

### ISSUE THREAD

**Issue by loristo** [bitnami/charts#7410]
**Which chart**:
kibana/latest

**Describe the bug**
The deployment fails when deploying the chart with the following log:
`Error: template: kibana/templates/deployment.yaml:95:109: executing "kibana/templates/deployment.yaml" at <.>: wrong type for value; expected bool; got string`

**To Reproduce**
1. `helm repo update`
2. `helm install kibana bitnami/kibana --set 'elasticsearch.hosts[0]=localhost' --set 'elasticsearch.port=9200`

**Expected behavior**
Chart is deployed.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Thanks for letting us know, a PR fixing the issue was created a couple of hours ago. It is being tested by our automated test & release pipeline, if everything works as expected it should be merged and the chart release soon
