### ISSUE TITLE
[bitnami/nginx] - metrics.port - equivalence on main image

### ISSUE THREAD

**Issue by fabriciolos** [bitnami/charts#7413]
My serverBlock configuration listens to the default 8080 port (in order to duplicate all requests on the reverse proxy so I can feed a secondary database while still transparently processing said requests on the default application in Production.

Because of that, as stated on the example shown on the README.md, I can't generate metrics with the exporter because it fails to query the /status endpoint.

I'm trying to solve this by publishing the /status endpoint on a different port and setting it to be accessed by the exporter. I'm aware of how instructing the exporter to query another port for the /status endpoint, but I'm not sure how to publish it on a different port. Is there something like the nginx-status-port argument for the nginx ingress controller?

If not, is there a way of having an exception to keep the /status endpoint as it should originally be treated, in my serverBlock?

```yaml
  serverBlock: |  
      upstream snmp {
          server webhook-snmp.proxy-namespace.svc.cluster.local;
      }

      upstream database {
          server recorder.db-namespace.svc.cluster.local;
      }

      server {
        listen 8080;

        location = / {
            mirror /mirror;
            proxy_pass http://snmp;
        }
        location = /mirror {
            internal;
            proxy_pass http://database$request_uri;
        }
      }
  ```

**Comment by marcosbc** [comment]
Hi @fabriciolos, since you are overwriting the server block, without adding any `alias`, it would cause it to be a catch-all server block.

Therefore I'd recommend you to directly add the configuration to enable the status page in that server block, i.e.:

```
        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }
```

**Comment by fabriciolos** [comment]
Thank you for the answer! I wasn't aware of how to call the local status endpoint and stub_status worked perfectly.
