### ISSUE TITLE
 [bitnami/postgres] - metrics.enabled - does not enable metrics for the read replica

### ISSUE THREAD

**Issue by kirancodify** [bitnami/charts#7416]
**Which chart**:
Chart: postgresql
Version: 10.4.10

**Describe the bug**
The metrics.enabled=true, will only add the exporter as sidecar to the primary and not on the read replica

**Expected behavior**
The postgres exporter should run as a sidecar on the read replica too.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:06:25Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by alemorcuq** [comment]
Thanks for the suggestion. Are you interested in contributing with a PR?

**Comment by kirancodify** [comment]
Sure.Will give it a try.
