### ISSUE TITLE
[bitnami/rabbitmq] Streams x-max-age not working

### ISSUE THREAD

**Issue by MarjanJordanovski** [bitnami/charts#7420]
Hello, I deployed rabbitmq version 3.9, and tried to test message retention on streams, but it's not working.

Steps when adding new queue:

- Set type to stream: stream
- Set x-max-age argument to 10s (string)

When stream is created, i bind it with existing exchange (fanout type)

Then I start pushing logs to this stream, and it is successfully getting them, but messages are not deleted after 10 seconds. 
When I try this but with classic queues, it's working (in that case I used x-message-ttl argument.

Am I doing something wrong or is this a bug?
Thanks!

**Comment by pablogalegoc** [comment]
Hi @MarjanJordanovski!

I'm not an expert on RabbitMQ but I think we will be able to find out if this is an issue with the chart, RabbitMQ itself or there's something wrong in the usage. Are you running the default installation of the chart? If not, could you share the parameters you are setting? Also, it would be very useful if you could share the commands you are using to perform those operations on RabbitMQ. Thanks!

**Comment by MarjanJordanovski** [comment]
Hello @pablogalegoc 

I'm running almost default installation of the chart. I only had couple of things changed in the values.yaml file:

- plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s rabbitmq_stream"  # rabbitmq_stream plugin is added
- username: guest # this is under auth section
- password: guest 
- erlangCookie: guest

In the rabbitmq management console, I created new queue of type stream, called it test-stream, and added argument x-max-age to have value 10s 
I created new exchange called testexchange, and bound it to test-stream (without any arguments).

Then from fluentd I started pushing logs to the exchange, and exchange is successfully copying logs to test-stream. 
Problem is just that number of Ready and Total messages in test-stream is rising, and messages older then 10 seconds seems like are not deleted.

**Comment by pablogalegoc** [comment]
Hi again @MarjanJordanovski, I've been able to reproduce the issue.

Just for reference, the part of creating an exchange and the message generation can be replaced with multiple calls to the API:
`curl -i -u user:pass http://IP:15672/api/exchanges/%2f/amq.default/publish -d '{"properties":{}, "routing_key":"test-stream", "payload":"message test", "payload_encoding":"string"}'`

My guess is that this is what's happening: https://github.com/rabbitmq/rabbitmq-server/pull/3087
Policies are taking precedence over the arguments we are setting at queue creation.

**Comment by michelveloso** [comment]
Same problem here, the messages is never deleted

![image](https://user-images.githubusercontent.com/346317/160959329-32cb4f37-ce30-412b-b4ce-c4c44676e88f.png)

**Comment by rafariossaa** [comment]
Hi @michelveloso ,
  As this seems not to be an issue with the chart or the containers, I would suggest you to ask in rabbitmq forums why this could be happening.

**Comment by mkuratczyk** [comment]
I know it's a very late reply but I just noticed this question and it still doesn't contain the answer. Streams are append-only structures and therefore messages are not removed from within a segment file (a file where stream content is stored). Retention is applied at the segment file level - if a segment contains only expired messages, it gets deleted. Moreover, retention evaluation is performed when a segment file is full and a new segment is created. Therefore, if you stop publishing, expired messages won't be removed (no new messages -> no new segment files -> not retention evaluation process).

https://www.rabbitmq.com/streams.html#retention

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but I have not a different suggestion. I would ask in rabbitmq forums about this issue.

**Comment by mkuratczyk** [comment]
I left the answer so that people who find this issue don't have to ask anywhere - this is RabbitMQ Streams working as designed.
