### ISSUE TITLE
[bitnami/jupyterhub] JupyterHub notebook cannot be saved

### ISSUE THREAD

**Issue by nerilau** [bitnami/charts#7427]
**Which chart**:
jupyterhub v0.1.18

**Describe the bug**
Saving the notebook fails after ~1h and a new cookie creates.

**Expected behavior**
What I want to achieve is to save the notebook after 1hour of working with it.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

**Additional context**
That's how my cookies looks within 1 hour window: 
![image](https://user-images.githubusercontent.com/53757827/132359998-66925402-4000-471c-92cc-6cd06d494b59.png) 
(cookie content is not empty)

And that's how it looks after 1 hour:
![image](https://user-images.githubusercontent.com/53757827/132363816-4aaacaf5-30e1-4456-95cc-b6cfd067cb32.png) 
(cookie content is empty)

Also, attaching a screenshot of what I can see in the jupyterhub UI: 
![image](https://user-images.githubusercontent.com/53757827/132364117-0ec28427-8b9b-4aaa-bd48-5291329da2ef.png)

debug command to see single-user instance logs:
`$ kubectl logs jupyterhub-jupyter-user -n jupyterhub`
```
[I 2021-09-07 14:36:29.386 SingleUserNotebookApp log:189] 200 GET /user/user/api/contents/Untitled.ipynb?content=0&_=1631020407442 (user@2a02:4780:4:0:a8ce:44c5:47a5:a471) 1.30ms
[I 2021-09-07 14:36:29.471 SingleUserNotebookApp handlers:164] Saving file at /Untitled.ipynb
[I 2021-09-07 14:36:29.486 SingleUserNotebookApp log:189] 200 PUT /user/user/api/contents/Untitled.ipynb (user@2a02:4780:4:0:a8ce:44c5:47a5:a471) 16.32ms
[I 2021-09-07 14:36:29.572 SingleUserNotebookApp log:189] 201 POST /user/user/api/contents/Untitled.ipynb/checkpoints (user@2a02:4780:4:0:a8ce:44c5:47a5:a471) 1.42ms
[W 2021-09-07 14:37:55.692 SingleUserNotebookApp auth:314] No Hub user identified for request
[W 2021-09-07 14:37:55.693 SingleUserNotebookApp auth:552] Token stored in cookie may have expired
[W 2021-09-07 14:37:55.693 SingleUserNotebookApp handlers:617] Forbidden
[W 2021-09-07 14:37:55.694 SingleUserNotebookApp log:189] 403 GET /user/user/api/contents/Untitled.ipynb?content=0&_=1631020407443 (@2a02:4780:4:0:a8ce:44c5:47a5:a471) 19.65ms
[W 2021-09-07 14:37:55.882 SingleUserNotebookApp auth:552] Token stored in cookie may have expired
[W 2021-09-07 14:37:55.882 SingleUserNotebookApp handlers:617] Forbidden
[W 2021-09-07 14:37:55.883 SingleUserNotebookApp log:189] 403 PUT /user/user/api/contents/Untitled.ipynb (@2a02:4780:4:0:a8ce:44c5:47a5:a471) 1.29ms
```

**Comment by javsalgar** [comment]
Hi,

I'm trying to reproduce the issue locally. I'll let you know if I get the same issue. Are you using ingress or service IPs?

**Comment by nerilau** [comment]
Ngnix ingress is used to access jupyterhub.

**Comment by nerilau** [comment]
Hi @javsalgar, I also noticed that when I refresh the jupyterhub page and go to the notebook page, I can save the notebook. Maybe that could help. Did you manage to reproduce the problem? Any kind of update would be very interesting.

**Comment by javsalgar** [comment]
I was unable to reproduce it with the default installation. Could it be the related to the authenticator?

**Comment by javsalgar** [comment]
Hi,

We were unable to reproduce the issue after several attempts. Could you add more details about how the issue occurs and a way to reproduce it?
