### ISSUE TITLE
can zookeeper add tls pem option ?

### ISSUE THREAD

**Issue by caoheyang** [bitnami/charts#7439]
**Which chart**:
zookeeper 7.4.3 

**Is your feature request related to a problem? Please describe.**
I need to configure tls.type=pem for the zookeeper cluster. Because my zookeeper client only support tls pem.

**Describe the solution you'd like**
Maybe we cat add a custom config option. like kafka ssl config ,  like 
https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls

**Comment by miguelaeh** [comment]
Hi @caoheyang ,
Thank you very much for the suggestion, would you like to create a PR adding it?

**Comment by caoheyang** [comment]
Sure, no problem, use a new version to implement it?

**Comment by miguelaeh** [comment]
Thank you very much!
Yes, any kind of change in the chart must have a version bump
