### ISSUE TITLE
[bitnami/airflow] Let k8s-executor-init-config container have custom requests and limits

### ISSUE THREAD

**Issue by Davide95** [bitnami/charts#7446]
**Which chart**:
bitnami/airflow 10.3.2

**Describe the bug**
We are running your helm chart on Kubernetes using the KubernetesExecutor. Due to custom policies in our cluster, no pods or containers without requests and limits cannot be executed.
The issue is that every time you execute a Task of a DAG, the scheduler returns this error:
```
kubernetes.client.rest.ApiException: (403) Reason: Forbidden HTTP response headers: HTTPHeaderDict({'Audit-Id': '8535760e-8760-4b35-adff-a1bdff05d544', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '0613cb93-4fd5-4839-9b1f-fd2d4dd1817d', 'X-Kubernetes-Pf-Prioritylevel-Uid': '6de44d72-39de-47df-a5e7-8798fd7dc181', 'Date': 'Thu, 09 Sep 2021 11:25:46 GMT', 'Content-Length': '368'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by container-limits] container \u003ck8s-executor-init-config\u003e has no resource limits","reason":"[denied by container-limits] container \u003ck8s-executor-init-config\u003e has no resource limits","code":403} 
```

I've already configured limits and requests on the pod:
```yaml
worker:
  resources:
    requests: 
        memory: "512Mi"
        cpu: "125m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
```
The issue is that the `k8s-executor-init-config` container does not have requests and limits that can be specified (I've tried to search inside the configs from the [README.md](https://github.com/bitnami/charts/blob/master/bitnami/airflow/README.md) and read the source code of [configmap.yaml](https://github.com/bitnami/charts/blob/ccae74f2316acf0fe879b10a914739047a874178/bitnami/airflow/templates/config/configmap.yaml)).

**To Reproduce**

1. Deploy Airflow on Kubernetes with KubernetesExecutor
2. Configure admission webhooks to block the deployment of resources without requests and limits
3. Read the logs of Airflow's executor

**Expected behavior**
Containers should have requests and limits configurable

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
You're 100% right @Davide95 !! The current ConfigMap (`pod_template.yaml` definition) doesn't take into account define the resource requests/limits based on the values.yaml.

Thanks for reporting this limitation.

Sending a PR to fix it.

**Comment by Davide95** [comment]
Hi @juan131, everything works as expected. I just want to say "thank you"

**Comment by juan131** [comment]
You're welcome @Davide95 ! I'm glad that it worked.
