### ISSUE TITLE
[bitnami/external-dns] etcd parameters should be external-dns parameters

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#7453]
Hi Bitnami,

Please rename this line from etcd to external-dns
https://github.com/bitnami/charts/blob/2f783cb15faf07479a9f3c839a34f330b4cceb21/bitnami/external-dns/values.yaml#L29

Best regards,
Ruba

**Comment by carrodher** [comment]
Thanks for letting us know, we just fixed the issue
