### ISSUE TITLE
Can't Upgrade from Helm 2.0.2 to 4.2.4 

### ISSUE THREAD

**Issue by enibache** [bitnami/charts#7456]
Dear bitnami Angels, perhaps you've already come across the issue mentioned in the title and have a solution for it! According to the Upgrade procedure here: https://github.com/bitnami/charts/tree/master/bitnami/discourse/#installing-the-chart at the paragraph "Upgrading", i followed the instructions there but resulted to the following error:

`Error: UPGRADE FAILED: cannot patch "discourse-redis-master" with kind StatefulSet: StatefulSet.apps "discourse-redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

If redis is enabled, must the upgrade procedure in the link be augmented with redis pvc as well?
Any assistance/tips ?
Many thanks and cheers,
\enc

**Comment by rafariossaa** [comment]
Hi,
  Did you try to upgrade from 2.0.2 to 4.2.4 directly or did you try to upgrade from 2.0.2 to 3.x.x and then to 4.2.4 ?

**Comment by enibache** [comment]
Hi Rafael,
thanks for your prompt response. I tried a direct upgrade from 2... to 4... Shouldn't this be possible?

**Comment by rafariossaa** [comment]
Hi,
  Maybe yes, maybe no. I mean, the process is always thought to work with the previous version. Sometimes it could work jumping versions but this is not guarantee nor tested.
  We test upgrading from mayor to next mayor, but not jumping releases. 
  Could you try to upgrade first to v3 ?

**Comment by enibache** [comment]
Hi Rafael,
i tried this and ran into yet another problem with the redis cluster. It seems like i have to remount the redis PVC slaves but i don't seem to understand how these should be remounted. Could you perhaps hint me on how to upgrade a running discourse instance without loosing any of its PVCs. I'd really appreciate this...
Many thanks !

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure about your current issue. 
  Could you indicate the steps you followed and what you have found ? I would like to try the same to see how I can help you .

**Comment by enibache** [comment]
Hi, sorry for the late reply. Finally I had to delete and get rid of the
installed version 2.0.2 before redeploying version 4.2.4 successfully
instead of doing an upgrade thereby losing the actual PVCs/PVs. Fortunately
I had taken a backup of the current state, so restoring the backup on the
new version was successfully. We had to live with the down time!
Cheers,
\enc

**Comment by rafariossaa** [comment]
Hi,
  I am glad you were able to solve the issue.
  Thanks for sharing.
