### ISSUE TITLE
Installation will fail if "nameOverride" and "fullnameOverride" is used for dependencies (for most charts)

### ISSUE THREAD

**Issue by mamiu** [bitnami/charts#7457]
**Which chart:**
Almost every chart. Let's take `[bitnami/wordpress]` as an example for this ticket.

**Bug description:**

If the name of a dependency is getting overridden that will cause a failing and stuck installation because it cannot be found by other resources anymore.

**To Reproduce:**

Let's say we want to override the name of `mariadb` (one of the `wordpress` chart dependencies) like so:

```yaml
mariadb:
  nameOverride: "custom-mariadb-name"
```

... or even worse:

```yaml
mariadb:
  fullnameOverride: "custom-mariadb-name"
```

This will break the installation of the WordPress chart.

But the same fragile configuration can be applied to a lot of other charts in this repository as well (e.g. [`magento`](https://github.com/bitnami/charts/blob/f88d9fae4eaeba918df2aec7a76efb268e3d0318/bitnami/magento/templates/_helpers.tpl#L24), [`drupal`](https://github.com/bitnami/charts/blob/0ddf6435115c0047aaa6b23542415bda77f254cb/bitnami/drupal/templates/_helpers.tpl#L6), [`discourse`](https://github.com/bitnami/charts/blob/0ddf6435115c0047aaa6b23542415bda77f254cb/bitnami/discourse/templates/_helpers.tpl#L7), etc. - I just randomly picked a few).

**Expected behavior:**

Don't break the installation even if `nameOverride` or `fullnameOverride` is used for any chart dependency.

This could be easily achieved with a simple template like that one:

```tpl
{{/*
Create a default fully qualified app name for a dependency.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.

Usage:
{{ include "common.names.dependency.fullname" (dict "chartName" "dependency-chart-name" "chartValues" .Values.dependency-chart "context" $) }}

*/}}
{{- define "common.names.dependency.fullname" -}}
{{- if .chartValues.fullnameOverride -}}
{{- .chartValues.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .chartName .chartValues.nameOverride -}}
{{- if contains $name .context.Release.Name -}}
{{- .context.Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .context.Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

This is a customized version of the already existing [`common.names.fullname`](https://github.com/bitnami/charts/blob/0ddf6435115c0047aaa6b23542415bda77f254cb/bitnami/common/templates/_names.tpl#L16-L32) template in the [`_names.tpl`](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_names.tpl) helper file of the `common` chart.

With our example from above this template could be used like that:

```tpl
{{ include "common.names.dependency.fullname" (dict "chartName" "mariadb" "chartValues" .Values.mariadb "context" $) }}
```

**Version of Helm and Kubernetes:**

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miguelaeh** [comment]
Hi @mamiu ,
Thank you very much for reporting this issue.
The above PRs are adding the new function to common and using it for Wordpress.
We will continue adding it for the rest of charts

**Comment by mamiu** [comment]
@miguelaeh Wow that was fast! Thanks a lot mate! 😃👍
