### ISSUE TITLE
[bitnami/postgresql-ha]PostgreSQL standby POD is not coming UP

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#7458]
**Which chart**:
Helm chart : postgresql-ha-6.8.0

**Describe the bug**

We have deployed the PostgreSQL HA helm chart with one primary and stanby instances in our production environment, and it was running for several months, recently we have noticed one pod health check is not good so currently PostgreSQL HA is running with only one instance. Please check the output below.

```
sparvathala@sparvathala ~ % kubectl get po -n dev-iamdb
NAME                                    READY   STATUS             RESTARTS   AGE
postgres-ha-postgresql-ha-client        1/1     Running            0          4m59s
postgresql-ha-pgpool-56d67c5d7d-55smb   1/1     Running            3          48m
postgresql-ha-pgpool-56d67c5d7d-gzjtv   1/1     Running            132        93d
**postgresql-ha-postgresql-0              1/2     CrashLoopBackOff   13         47m**
postgresql-ha-postgresql-1              2/2     Running            2          93d
sparvathala@sparvathala ~ % 

Please check the event logs for the  postgresql-ha-postgresql-0  instance which is Failure instance. I have tried to reboot the worker node hosted this pod and  also tried deleting it so that it would recreated from scratch  but that did not help. Kindly can you please help how can i bring the other pod instance running.

Please can you help on this as we are running this in production .

**kubectl describe po postgresql-ha-postgresql-0 -n dev-iamdb**

Events:
  Type     Reason     Age                From                          Message
  ----     ------     ----               ----                          -------
  Normal   Scheduled  <unknown>          default-scheduler             Successfully assigned dev-iamdb/postgresql-ha-postgresql-0 to portal-worker-app21
  Normal   Pulling    47m                kubelet, portal-worker-app21  Pulling image "docker.io/bitnami/bitnami-shell:10-debian-10-r92"
  Normal   Pulled     47m                kubelet, portal-worker-app21  Successfully pulled image "docker.io/bitnami/bitnami-shell:10-debian-10-r92"
  Normal   Created    47m                kubelet, portal-worker-app21  Created container init-chmod-data
  Normal   Started    47m                kubelet, portal-worker-app21  Started container init-chmod-data
  Normal   Created    47m                kubelet, portal-worker-app21  Created container postgresql
  Normal   Pulled     47m                kubelet, portal-worker-app21  Container image "docker.io/bitnami/postgresql-repmgr:10.17.0-debian-10-r18" already present on machine
  Normal   Started    47m                kubelet, portal-worker-app21  Started container postgresql
  Normal   Pulled     47m                kubelet, portal-worker-app21  Container image "docker.io/bitnami/postgres-exporter:0.9.0-debian-10-r78" already present on machine
  Normal   Created    47m                kubelet, portal-worker-app21  Created container metrics
  Normal   Started    47m                kubelet, portal-worker-app21  Started container metrics
  Warning  Unhealthy  46m (x9 over 47m)  kubelet, portal-worker-app21  Readiness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  46m (x6 over 47m)  kubelet, portal-worker-app21  Liveness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
  Normal   SandboxChanged  43m                kubelet, portal-worker-app21  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         43m                kubelet, portal-worker-app21  Pulling image "docker.io/bitnami/bitnami-shell:10-debian-10-r92"
  Normal   Pulled          43m                kubelet, portal-worker-app21  Successfully pulled image "docker.io/bitnami/bitnami-shell:10-debian-10-r92"
  Normal   Created         43m                kubelet, portal-worker-app21  Created container init-chmod-data
  Normal   Started         43m                kubelet, portal-worker-app21  Started container init-chmod-data
  Normal   Started         43m                kubelet, portal-worker-app21  Started container postgresql
  Normal   Created         43m                kubelet, portal-worker-app21  Created container postgresql
  Normal   Pulled          43m                kubelet, portal-worker-app21  Container image "docker.io/bitnami/postgresql-repmgr:10.17.0-debian-10-r18" already present on machine
  Normal   Pulled          43m                kubelet, portal-worker-app21  Container image "docker.io/bitnami/postgres-exporter:0.9.0-debian-10-r78" already present on machine
  Normal   Created         43m                kubelet, portal-worker-app21  Created container metrics
  Normal   Started         43m                kubelet, portal-worker-app21  Started container metrics
  Warning  Unhealthy       42m (x6 over 43m)  kubelet, portal-worker-app21  Liveness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
  Warning  BackOff    8m34s (x76 over 33m)   kubelet, portal-worker-app21  Back-off restarting failed container
  Warning  Unhealthy  3m39s (x130 over 43m)  kubelet, portal-worker-app21  Readiness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
sparvathala@sparvathala ~ % 



Currently deployed Helm chart as shown below:

sparvathala@sparvathala ~ % helm ls -n dev-iamdb
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
postgresql-ha	dev-iamdb	1       	2021-06-08 15:29:40.052501526 -0400 EDT	deployed	postgresql-ha-6.8.0	11.11.0    
sparvathala@sparvathala ~ % kubectl get po -n dev-iamdb


**postgres=# show pool_nodes;**
 node_id |                                         hostname                                         | port | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay | replication_state | replication_sync_state | last_status_chan
ge  
---------+------------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------------------+-------------------+-------------------+------------------------+-----------------
----
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.dev-iamdb.svc.cluster.local | 5432 | **down**   | 0.500000  | standby | 0          | false             | 0                 |                   |                        | 2021-09-10 14:52
:52
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.dev-iamdb.svc.cluster.local | 5432 | up     | 0.500000  | primary | 8448       | true              | 0                 |                   |                        | 2021-09-10 14:52
:32
(2 rows)

postgres=# 
```

**Comment by parvaths1118** [comment]
Hello,

Kindly can someone look into this and help on how to recover another PostgreSQL pod that is in the crashed state, it happened to another HA cluster today.

we are worried production HA is running with only one  PostgreSQL pod instance.

Following log noticed in the crashed PostgreSQL instance.

postgresql-repmgr 12:26:50.27 
postgresql-repmgr 12:26:50.27 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 12:26:50.27 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 12:26:50.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 12:26:50.28 
postgresql-repmgr 12:26:50.29 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 12:26:50.32 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 12:26:50.32 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 12:26:50.33 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 12:26:50.38 INFO  ==> Auto-detected primary node: 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.dev-iamdb.svc.cluster.local:5432'
postgresql-repmgr 12:26:50.39 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 12:26:50.39 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 12:26:50.49 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 12:26:50.50 INFO  ==> Initializing Repmgr...
postgresql-repmgr 12:26:50.51 INFO  ==> Waiting for primary node...
postgresql-repmgr 12:26:50.57 INFO  ==> Cloning data from primary node...

**Comment by alemorcuq** [comment]
Hi, @parvaths1118.

Is that the full log from the crashed pod? Looking at it it's doing some work at the moment, so nothing seems to be wrong there. If that is indeed the full log, then it's very likely that the liveness probe is killing the pod before it has the time to start. I can see this event in your first message so I think this can be the cause:

```
 Warning  Unhealthy       42m (x6 over 43m)  kubelet, portal-worker-app21  Liveness probe failed: psql: could not connect to server: Connection refused 
        Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 5432?
```

I suggest you to temporarily disable the liveness and readiness probes to see if the node gets up properly, and then you can enable the probes back after tweaking the timings to something more appropriate to your scenario.

**Comment by parvaths1118** [comment]
Hi @alemorcuq ,

Thank you for the response.

Yes, that is the full log from the crashed pod.

Please can you suggest the steps on how do I disable the liveness and readiness probes only for the crashed pod, please note that this is happening in the production environment so would like to check with you how to disable them without disturbing another running instance?

Thank you for your help.

**Comment by alemorcuq** [comment]
First and foremost, I recommend you to make a backup in case anything goes wrong: https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/backup-restore/

After that, you can use `kubectl edit` to disable the probes of the affected pod.

**Comment by parvaths1118** [comment]
Hi @alemorcuq  , Thank you for your response. Sorry for the delay in getting back to you.

I was looking for the commands to restart the PostgreSQL HA database in bitnami documentation but I could not find them. Please can you share how do I restart the PostgreSQL HA database that was deployed through bitnami PostgreSQL HA helm chart?

**Comment by alemorcuq** [comment]
What do you mean by "restart", @parvaths1118? If you want to restart a pod you can kill it and Kubernetes will schedule a new one.

**Comment by jpsn123** [comment]
@alemorcuq 
> I suggest you to temporarily disable the liveness and readiness probes to see if the node gets up properly, and then you can enable the probes back after tweaking the timings to something more appropriate to your scenario.

if you disabled probe, all things go working.
however, this issue not cause by probe, i externed initialDelaySeconds in live and read probe. this problem also show. there is no K8S Event about probe, but repmgr clone process down, logs show same as @parvaths1118 . 
if you disabled read probe, and all things will be right again. clone job will soon be done.

so, i think , repmgr process use pod DNS name to connect itself, by pod was not ready,  pod name can't be resvoled, lead to repmgr timeout.

but i can't find out whice param to controller this. so can you help me.

**Comment by alemorcuq** [comment]
There is an event about probes in what @parvaths1118 shared:

```
  Warning  Unhealthy  46m (x9 over 47m)  kubelet, portal-worker-app21  Readiness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
  Warning  Unhealthy  46m (x6 over 47m)  kubelet, portal-worker-app21  Liveness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
```

Probes are not succeeding, and because of that the pod is getting restarted. Logs show the cloning process is running when the pod is restarted.

I'm not sure I understand what you are trying to say about DNS. Repmgr is cloning from the current primary, which should be ready and running, thus accepting connections. Again, from the information shared in the first message:

```
sparvathala@sparvathala ~ % kubectl get po -n dev-iamdb
NAME                                    READY   STATUS             RESTARTS   AGE
postgres-ha-postgresql-ha-client        1/1     Running            0          4m59s
postgresql-ha-pgpool-56d67c5d7d-55smb   1/1     Running            3          48m
postgresql-ha-pgpool-56d67c5d7d-gzjtv   1/1     Running            132        93d
**postgresql-ha-postgresql-0              1/2     CrashLoopBackOff   13         47m**
postgresql-ha-postgresql-1              2/2     Running            2          93d
```

Only one pod is failing: the one that is trying to clone from the current primary, which is running. So, the failing pod should be able to connect to the primary to clone data, but while the clone is running the liveness probes gets to its limit and restarts the pod.

Setting the environment variable `BITNAMI_DEBUG=true` should show more information in the pod logs.
