### ISSUE TITLE
metrics-server feature request: make caBundle and insecureSkipTLSVerify parameterized in the chart

### ISSUE THREAD

**Issue by techstep** [bitnami/charts#7460]
**Which chart**:
metrics-server 5.9.3

**Is your feature request related to a problem? Please describe.**
As a user of metrics-server, I want to be able to properly use certificates between metrics-server and the API service to be checked. In the `metrics-api-service.yaml` template, `caBundle` is not set, and `insecureSkipTLSVerify` is hardcoded to `true`. Hence, no matter if the certificate is valid, it will be ignored. Since we are running this on our own environment where we can generate certificates, this would be good to set to `false`.

Along those lines, a parameter that allows us to set the `caBundle` would be great, so that we can pass in the entire chain.

**Describe the solution you'd like**
Within the `metrics-api-service.yaml` template, I would like to see (for example) `{{ .Values.apiService.insecureSkipTLSVerify | default 'true' }}`, and `{{ .Values.apiService.caBundle | default '' }}` or something similar. Parameters that map have the default behavior as things stand now, but offer the flexibility of change.

**Describe alternatives you've considered**
We could maintain a separate fork of the charts, but that would be difficult to the extent that we use a number of other charts unmodified. We have also looked at continuing to ignore certificates, but we would like to avoid doing that and take a more secure stance.

**Comment by migruiz4** [comment]
Hi @techstep,

Thanks for your suggestions. It would be a great addition to the `metrics-server` chart. Would you like to contribute with a PR for adding those parameters?

We will be very happy to review it and help with any questions you may have.

I would also like to recommend you to have a look at our contribution guidelines [here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md)

**Comment by techstep** [comment]
Thank you for responding!

I'll make a PR soon, as things allow. And thanks for pointing me to the guidelines!

**Comment by migruiz4** [comment]
Thank you for the PR @techstep!

As PR #7590 was merged, I will close this issue.
