### ISSUE TITLE
[bitnami/postgresql-ha] pre-stop.sh script fails to wait for new primary node.

### ISSUE THREAD

**Issue by GuoqiangZ** [bitnami/charts#7464]
**Which chart**:
postgresql-ha

**Describe the bug**
As commented in the pre-stop.sh script, when the primary node terminates it should wait for the new primary to come up. 

https://github.com/bitnami/charts/blob/a5fee544b20ceb8cd6131d511e221a74e2a89998/bitnami/postgresql-ha/templates/postgresql/hooks-scripts-configmap.yaml#L61-L72

But during the experiments, the primary node leaves before the new primary coming up.

The root cause is in the following line 

https://github.com/bitnami/charts/blob/a5fee544b20ceb8cd6131d511e221a74e2a89998/bitnami/postgresql-ha/templates/postgresql/hooks-scripts-configmap.yaml#L61

If you take a look into `repmgr_get_primary_node ` in [librepmgr.sh](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/4c84b71236e429435fbe5e7dc66379a76171e7a7/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L199-L238), you can find that, when executed in primary node, the returned primary node is `"" <port>`,  so https://github.com/bitnami/charts/blob/a5fee544b20ceb8cd6131d511e221a74e2a89998/bitnami/postgresql-ha/templates/postgresql/hooks-scripts-configmap.yaml#L67 always returns `false`. This results in primary node never waiting for the new one and leaving the cluster immediately. This occasionally leads to split brain issue from our observation.

**To Reproduce**

1. Prepare configuration files for 3 replicas of Postgres node.
2. Append following lines in `pre-stop.sh` and set env `BITNAMI_DEBUG` to be `true` for postgresql container.
```
info "Primary node is $primary_node"
info "Primary host is $primary_host"

# Output logs into a FailedPreStopHook event
exit 1
```
3. Apply configuration and wait for all 3 nodes coming up. Then terminate the primary node.
4. Find logs in FailedPreStopHook event.

```
pre-stop-hook 23:26:43.80 DEBUG ==> Configuring libnss_wrapper...
pre-stop-hook 23:26:43.81 INFO  ==> Querying all partner nodes for common upstream node...
pre-stop-hook 23:26:43.82 DEBUG ==> Checking node 'postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'...
pre-stop-hook 23:26:43.82 DEBUG ==> Executing SQL command:
SELECT conninfo FROM repmgr.show_nodes WHERE (upstream_node_name IS NULL OR upstream_node_name = '') AND active=true
pre-stop-hook 23:26:43.85 DEBUG ==> Pretending primary role node - 'postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'
pre-stop-hook 23:26:43.85 DEBUG ==> Pretending primary set to 'postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'!
pre-stop-hook 23:26:43.85 DEBUG ==> Checking node 'postgres-postgresql-ha-postgresql-1.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'...
pre-stop-hook 23:26:43.86 DEBUG ==> Executing SQL command:
SELECT conninfo FROM repmgr.show_nodes WHERE (upstream_node_name IS NULL OR upstream_node_name = '') AND active=true
pre-stop-hook 23:26:43.88 DEBUG ==> Pretending primary role node - 'postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'
pre-stop-hook 23:26:43.88 DEBUG ==> Checking node 'postgres-postgresql-ha-postgresql-2.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'...
pre-stop-hook 23:26:43.88 DEBUG ==> Executing SQL command:
SELECT conninfo FROM repmgr.show_nodes WHERE (upstream_node_name IS NULL OR upstream_node_name = '') AND active=true
pre-stop-hook 23:26:43.91 DEBUG ==> Pretending primary role node - 'postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'
pre-stop-hook 23:26:43.91 INFO  ==> Auto-detected primary node: 'postgres-postgresql-ha-postgresql-0.postgres-postgresql-ha-postgresql-headless.psql.svc.cluster.local:5432'
pre-stop-hook 23:26:43.91 INFO  ==> This node was acting as a primary before restart!
pre-stop-hook 23:26:43.92 INFO  ==> Can not find new primary. Starting PostgreSQL normally...
pre-stop-hook 23:26:43.92 INFO  ==> Stopping PostgreSQL...
pre-stop-hook 23:26:44.23 INFO  ==> Standby node doesn't need to wait, leaving the cluster.
pre-stop-hook 23:26:44.23 INFO  ==> Primary node is
5432
pre-stop-hook 23:26:44.23 INFO  ==> Primary host is 5432
```

**Expected behavior**
In the logs you should see `Primary node need to wait for a new primary node before leaving the cluster` instead of `Standby node doesn't need to wait, leaving the cluster.` and `primary_node` value should contain two args (`<host> <port>`)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Consider replacing https://github.com/bitnami/charts/blob/a5fee544b20ceb8cd6131d511e221a74e2a89998/bitnami/postgresql-ha/templates/postgresql/hooks-scripts-configmap.yaml#L61 with 
```
primary_node="$(repmgr_get_upstream_node)"
```
or checking the number of returned args by `repmgr_get_primary_node `

**Comment by javsalgar** [comment]
Hi! Thank you  so much for the feedback! We have plans on working on the split-brain issues that several users reported and this definitely seems like something worth checking. I will forward this to the team.

**Comment by rafariossaa** [comment]
Hi, 
 I have create an internal task to study this issue.
  We will come back as soon as we have news.

**Comment by carrodher** [comment]
I'm closing this issue since different PRs were merged in order to solve this issue (for example https://github.com/bitnami/charts/pull/9035).
Please, don't hesitate to reopen it if you are still facing this issue using the latest Helm chart version. If you face a different issue, please create a new ticket.
