### ISSUE TITLE
[bitnami/minio] Prometheus exporter connects to a wrong metrics port

### ISSUE THREAD

**Issue by GRomR1** [bitnami/charts#7474]
**Which chart**:

**Describe the bug**
ServiceMonitor manifest use `minio-console` port (9001), it is wrong. 
![image](https://user-images.githubusercontent.com/10095462/133096349-4e52ac05-3a54-4517-839e-ac2b9a5db47c.png)

**To Reproduce**
It could be tested with next commands.

Deploy a chart:
```
helm install minio bitnami/minio  \
  --version 8.0.0 \
  --set metrics.serviceMonitor.enabled=true
```

Get access to the service:
```
kubectl port-forward --namespace minio svc/minio 9000:9000
```

Get metrics:
```
curl http://127.0.0.1:9000/minio/v2/metrics/cluster 
# HELP minio_bucket_objects_size_distribution Distribution of object sizes in the bucket, includes label for the bucket name.
# TYPE minio_bucket_objects_size_distribution gauge
...
```

**To Fix**
Changing a name to [`minio`](https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/servicemonitor.yaml#L23) (9000) in specification of ServiceMonitor will fix the gathering metrics.
```
spec:
  endpoints:
  - interval: 30s
    path: /minio/v2/metrics/cluster
    port: minio
```
![image](https://user-images.githubusercontent.com/10095462/133099235-6c239d64-802e-465a-96a3-1a461caaac63.png)

**Comment by Mauraza** [comment]
Hi @GRomR1,

Thanks for reporting!! A colleague has created a PR to solve the issue.
