### ISSUE TITLE
[bitnami/mongodb-sharded] issue with numactl flag for numa hardware

### ISSUE THREAD

**Issue by henrifroese** [bitnami/charts#7479]
In PR #7083 support for launching with `numactl --interleave=all` was added. In the template it sets

```bash
            - name: MONGODB_ENABLE_NUMACTL
              value: {{ ternary "yes" "no" $.Values.common.mongodbEnableNumactl | quote }}
```

but then in the corresponding PR for the docker image (https://github.com/bitnami/bitnami-docker-mongodb-sharded/pull/17/files) it does
```bash
export MONGODB_ENABLE_NUMACTL="${MONGODB_ENABLE_NUMACTL:-false}"
````

and then
```bash
        if [ "${MONGODB_ENABLE_NUMACTL}" = true ]; then
            debug_execute numactl --interleave=all "$MONGODB_BIN_DIR/mongod" "${flags[@]}"
        else
            debug_execute "$MONGODB_BIN_DIR/mongod" "${flags[@]}"
        fi
````

So as far as I can tell the flag wouldn't work as the env var is set to "yes", not "true".

**Comment by henrifroese** [comment]
Sorry accidentally opened the same issue twice (https://github.com/bitnami/charts/issues/7478), closed that one

**Comment by juan131** [comment]
Hi @henrifroese 

Thanks for reporting it!

We're going to fix in the container side! The `MONGODB_ENABLE_NUMACTL` should actually accept `yes/no` as supported values. I'll ping you as soon as there's a new release of the `bitnami/mongodb-sharded` container released.

**Comment by henrifroese** [comment]
Awesome thanks! Just opened another issue there that's closely related so maybe that can be bundled (https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues/22)

**Comment by juan131** [comment]
For the record, the changes that I'm introducing in the image are pretty simple:
```diff
    if am_i_root; then
-       if [ "${MONGODB_ENABLE_NUMACTL}" = true ]; then
+       if is_boolean_yes "$MONGODB_ENABLE_NUMACTL"; then
            debug_execute gosu "$MONGODB_DAEMON_USER" numactl --interleave=all "$MONGODB_BIN_DIR/mongod" "${flags[@]}"
        else
            debug_execute gosu "$MONGODB_DAEMON_USER" "$MONGODB_BIN_DIR/mongod" "${flags[@]}"
        fi
    else
-       if [ "${MONGODB_ENABLE_NUMACTL}" = true ]; then
+       if is_boolean_yes "$MONGODB_ENABLE_NUMACTL"; then
            debug_execute numactl --interleave=all "$MONGODB_BIN_DIR/mongod" "${flags[@]}"
        else
            debug_execute "$MONGODB_BIN_DIR/mongod" "${flags[@]}"
        fi
    fi
```
The `is_boolean_yes` handles both `true/false` and `yes/no` values correctly. See: https://github.com/bitnami/bitnami-docker-mongodb-sharded/blob/master/5.0/debian-10/prebuildfs/opt/bitnami/scripts/libvalidations.sh#L55

**Comment by henrifroese** [comment]
Could you also do the change in `run.sh`, should roughly be 

```bash
info "** Starting MongoDB **"
if am_i_root; then
    exec gosu "$MONGODB_DAEMON_USER" "$cmd" "${flags[@]}"
else
    exec "$cmd" "${flags[@]}"
fi
````

to 

```bash
info "** Starting MongoDB **"
if am_i_root; then
    if is_boolean_yes "$MONGODB_ENABLE_NUMACTL"; then
        exec gosu "$MONGODB_DAEMON_USER" numactl --interleave=all "$cmd" "${flags[@]}"
    else
        exec gosu "$MONGODB_DAEMON_USER" "$cmd" "${flags[@]}"
    fi
else
    if is_boolean_yes "$MONGODB_ENABLE_NUMACTL"; then
        exec numactl --interleave=all "$cmd" "${flags[@]}"
    else
        exec "$cmd" "${flags[@]}"
    fi
fi
```

**Comment by juan131** [comment]
sure

**Comment by juan131** [comment]
@henrifroese fixed at https://github.com/bitnami/bitnami-docker-mongodb-sharded/commit/1a2f3018fe9e7fbd67e6966df1b1cb73ede4afb5 and https://github.com/bitnami/bitnami-docker-mongodb-sharded/commit/0e76a9a0307472c9d136af0c2f5ce279ce301ac1

Use the image tag `5.0.2-debian-10-r15` to run these chanes.

**Comment by henrifroese** [comment]
Just tried it out, works great 👌 

In the `README`, it still says `common.mongodbEnableNumactl` has a default of `false`, that should probably be `no`

**Comment by juan131** [comment]
Hi @henrifroese 

I'm lad the new image worked! I proceed to close the issue as "solve"

> In the README, it still says common.mongodbEnableNumactl has a default of false, that should probably be no

Both `true/false` and `yes/no` should work since `is_boolean_yes` handles both. In any case, feel free to drop a PR improving the README.md if you consider it necessary, I'll be glad to review it.
