### ISSUE TITLE
[bitnami/redis] sentinel doesn't resolve correct ip adress - even with resolv.config ndots set to 1

### ISSUE THREAD

**Issue by Bjego** [bitnami/charts#7483]
**Which chart**:
redis - 15.6.3

**Describe the bug**
All urls are generated with FQDNs based on the given clusterDomain. In our on premises cluster, pods are resolving incorrect ipadresses using the FQDN.
When I set the resolv.conf in the pods to be:
```
cat /etc/resolv.conf
nameserver xxx.xxxx.xxx.xxx
search NAMESPACE.svc.CLUSTERDOMAIN svc.CLUSTERDOMAIN CLUSTERDOMAIN yyyy.ZZZ.org
options ndots:1
```
The redis pods themselfs are resolving the right ip adresses and are working fine. But the sentinel, also with ndots:1, still resolves a wrong ip adress.

When I'm setting
```yaml
clusterDomain:
```
then the chart generates names and urls ending with **svc.** instead of **svc**. Where I could use the namespace internal name resolution. This would fix the issue.

**To Reproduce**
See my description. Guess this behaviour is hard to reorganise.

**Expected behavior**
I'd like to find a way to use namespace internal name resolution, or to find a way to configure sentinel to just work.

Guess fixing the urls when clusterDomain is set to "" or null is easier.
Something like {{if not empty .Values.clusterDomain}}.{{ .Values.clusterDomain}}{{end}} could do the trick to use namespace internal nameresolution.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I tried to fix this issue on my local machine to create a PR - but I haven't done any helm scripts yet and running the helm source locally ends in an error
```
PS C:\Git\Redis> helm install redis -f ./values.yaml -f .\namespace.yaml  C:\Git\BitnamiCharts\charts-master\bitnami\redis
Error: found in Chart.yaml, but missing in charts/ directory: common
```

**Comment by rafariossaa** [comment]
Hi,
  Not very sure if I understood completely the issue.
  Kubernetes has it internal DNS has should resolve those FQN. 
  Which DNS server are you configuring in the resolv.conf. 
  
  Regarding the message: `Error: found in Chart.yaml, but missing in charts/ directory: common`    you need to run first: `helm dependency update` so it download the dependencies, in this case it is a chart called `common`

**Comment by Bjego** [comment]
hi,
yeah that's right, my clusterdomain is "Test". Haven't looked for the DNS server yet, but when I'm using the fqdn pod names the nameserver resolves an wrong ip address for the services. For the redis containers in the pod this is fixed by setting ndots to 1 in resolv.conf. But somehow this doesn't work for the sentinal pods. They are still getting issued ip adresses for their connected redis container.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ 

Therefore I'm asking , if it's possible to update the chart to have the opportunity to use namespace internal names without an clusterdomain.

When you are setting the clusterdomain to "" - the chart generates invalid urls as those are ending with "svc." instead of "svc" which would be valid. I think this could solve at least my nameresolution issues with an minimal impact, as I have to null the clusterdomain property.

Or is there any reason, I might haven't seen yet, why the chart is using FQDN domains instead of namespace internal resolution?

**Comment by rafariossaa** [comment]
Hi,
  Yes, this chart won't work as it is if you empty `clusterDomain`, it is uses to generated the name of the services and then to set the proper environment variables in `templates/scripts-configmaps`.
  When you deploy the cluster with: `helm install myredis bitnami/redis` you can reach the services at:
```
    myredis-master.default.svc.cluster.local for read/write operations (port 6379)
    myredis-replicas.default.svc.cluster.local for read-only operations (port 6379)
```
 but from inside the kubernetes cluster you should be able to use just `myredis-master`, like it is indicated when deployed:
```
...
2. Connect using the Redis&trade; CLI:
   redis-cli -h myredis-master -a $REDIS_PASSWORD
   redis-cli -h myredis-replicas -a $REDIS_PASSWORD
...
```

**Comment by Bjego** [comment]
@rafariossaa yeah I understand. But all the pods, services and containers could reach each other just with:
`
myredis-master.default.svc for read/write operations (port 6379)
myredis-replicas.default.svc for read-only operations (port 6379)
- or - 
myredis-master for read/write operations (port 6379)
myredis-replicas for read-only operations (port 6379)
`
These domain names should be reachable from every namespace in the cluster as well.


And if you want to reach the redis from outside you can open it up with the :
master / replica / sentinel / metrics .service.type = LoadBalancer

https://github.com/bitnami/charts/blob/614748a0cf3b43be2c42251c1e453e5887a945a2/bitnami/redis/values.yaml#L404
https://github.com/bitnami/charts/blob/614748a0cf3b43be2c42251c1e453e5887a945a2/bitnami/redis/values.yaml#L709
https://github.com/bitnami/charts/blob/614748a0cf3b43be2c42251c1e453e5887a945a2/bitnami/redis/values.yaml#L909
https://github.com/bitnami/charts/blob/614748a0cf3b43be2c42251c1e453e5887a945a2/bitnami/redis/values.yaml#L1168

So maybe it would be less hardcoded - if the clusterdomain would be optional? And kubernetes would do the trick about nameresolving and stuff. And due to that it the chart would be less error prone and easier to handle?

As I googled around regaring the helm syntax something like :
https://github.com/bitnami/charts/blob/2250929f9e278ae4f6d4f6b7166691313b2be0a8/bitnami/redis/templates/scripts-configmap.yaml#L29

```
instead of:
HEADLESS_SERVICE="{{ template "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"

this maybe could make clusterdomain optional (haven'd done helm before): 
HEADLESS_SERVICE="{{ template "common.names.fullname" . }}-headless.{{ .Release.Namespace }}.svc{{- if not empty .Values.clusterDomain }}.{{ .Values.clusterDomain }}{{-end}
```
What's your oppinon on that?

**Comment by rafariossaa** [comment]
> @rafariossaa yeah I understand. But all the pods, services and containers could reach each other just with:
>
>myredis-master.default.svc for read/write operations (port 6379)
>myredis-replicas.default.svc for read-only operations (port 6379)
>or
>myredis-master for read/write operations (port 6379)
>myredis-replicas for read-only operations (port 6379)
>
>These domain names should be reachable from every namespace in the cluster as well.

Yes, from inside the kubernetes cluster, you can use:
```
$ kubectl exec --tty -i redis-client --namespace default -- bash

I have no name!@redis-client:/$  redis-cli -h myredis-master -a $REDIS_PASSWORD
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
myredis-master:6379> 
```
or 
```
I have no name!@redis-client:/$  redis-cli -h myredis-master.default.svc -a $REDIS_PASSWORD
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
myredis-master.default.svc:6379> 
```


>And if you want to reach the redis from outside you can open it up with the :
> master / replica / sentinel / metrics .service.type = LoadBalancer
> ...

From outside the cluster you need to add an entry in your DNS to point to the clusterIP, because from outside the cluster you can not reach the kubernertes internal DNS.

I am sorry, but I still don't understand the use case.

You can use, for example `myredis-master.default.svc`, and that would be cluster independent, and from outside the cluster you can add an entry with the clusterIP being resolved as `myredis-master.default.svc`.

**Comment by Bjego** [comment]
Yeah and in the end - even without external access - I can't run the chart, with a sentinal as the sentinal sidecars don't resolve their attached services. 
So if I try to run the helm chart as it is, with sentinel in HA. It doesn't come up. Sentinal can't resolve the clusterip based name, I don't know why..
Right now I'm running a single node redis with external loadbalancer access, but in the future I'd like to run for cluster internal usage Redis in HA with sentinel. As I'm going to ship all the legacy apps to kubernetes anyway.

Therefore I'd like to blank the clusterIp - to be cluster independend and to get the HA setup up and running.

**Comment by rafariossaa** [comment]
> So if I try to run the helm chart as it is, with sentinel in HA. It doesn't come up. Sentinal can't resolve the clusterip based name, I don't know why..
For this, which k8s cluster are you using ?. Could you try deploying the chart in, for example, minikube ?

Regarding blanking the clusterIP, I don't see point of the usage for this. The application that use redis should have a parameter to set this. If you want to use this just as: `myredisserver` and work in all the clusters, you may face different issues as the name resolver can add behind that string other search base strings. Also, if you have several deployments (develpment, testing, production) you won't know which one you are pointing to. To be safe, you should use the FQN or at least longer strings.

**Comment by Bjego** [comment]
@rafariossaa you are maybe right - and it looks like this behaviour/feature isn't really bothering anyone else. 

As I have single node redis up and running for now - I guess we can close this issue. I'll have a second look how I can run the sentinel setup in our cluster in future - seems to be a very specific issue anyway.

Have a nice weekend!

**Comment by rafariossaa** [comment]
Hi,
  Thanks!, same to you.
