### ISSUE TITLE
Add a simple variable to the nginx-ingress-controller which enables verbose logging

### ISSUE THREAD

**Issue by justinmchase** [bitnami/charts#7486]
**Which chart**:
nginx-ingress-controller

**Is your feature request related to a problem? Please describe.**
I'm having an issue and would like to increase the logging so I can identify what is going wrong

**Describe the solution you'd like**
A simple variable on the chart that enables more verbose logging. 

**Describe alternatives you've considered**
I tried using `extraArgs` but looking at [this documentation](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments) it doesn't seem to map one to one and its not obvious how to just increase the logging. There seems to be a lot of variation based on the version of nginx etc.

**Additional context**
What I really want to see is why a request I'm making is getting a 404 rather than being proxied to my service, I think everything is correct yet its not working and I need more information to understand why. I can see in the logs that it is loading my `Ingress` resource without errors yet it's not working.

**Comment by miguelaeh** [comment]
Hi @justinmchase ,
Setting the extra args should work to provide more CLI parameters than the default ones. In the docs you referenced the following appears:
```
-nginx-debug

		Enable debugging for NGINX. Uses the nginx-debug binary. Requires 'error-log-level: debug' in the ConfigMap.
```

Nevertheless, I am not sure if adding that debug mode will show any errors for a wrong proxy configuration. I think you could try using `strace` checking the `connect()` calls.
