### ISSUE TITLE
PodDisruptionBudget api version change for 1.21+

### ISSUE THREAD

**Issue by gwvandesteeg** [bitnami/charts#7488]
As per:
W0915 16:39:49.374539 2196940 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

This affects probably many charts, but in particular:

https://github.com/bitnami/charts/blob/5c7942235d3169332e8dadb380cd757416f28946/bitnami/mariadb-galera/templates/pdb.yaml#L2

**Comment by alvneiayu** [comment]
hi @gwvandesteeg 

I created an internal task to remove those warning messages and added it to backlog. I am not able to give you an ETA. We will update this thread once we have news. Moreover, we are open to receive PR.

Thanks a lot for your time and help

Álvaro

**Comment by nc-ruth** [comment]
@alvneiayu do you have any update on this?

**Comment by purvaldur** [comment]
This seems to have been fixed for Kafka in https://github.com/bitnami/charts/commit/5776fdbe0217d20d0cded059072396597d5d7385

**Comment by juan131** [comment]
The PR I just created should fix this for MariaDB Galera

**Comment by purvaldur** [comment]
Fixed for the Kafka chart in v.2.8.1 https://github.com/bitnami/charts/commit/94bc49b9bbb2fc59c96c9686140d2f5961a52a37

**Comment by juan131** [comment]
Hi everyone!!

I sent a PR per chart to avoid hardcoding the version in the whole catalog. Find the PRs using the filter below:

- https://github.com/bitnami/charts/pulls?q=is%3Apr+author%3Ajuan131+%22Do+not+hardcode+PDB+apiVersion%22
