### ISSUE TITLE
[bitnami/postgresql-ha] ERROR:  permission denied for table

### ISSUE THREAD

**Issue by maxinfosoft** [bitnami/charts#7494]
What reasons can cause "Error: Permission Denied for Table" error during any database operation (even SELECT) located in slave-pod postgresql-ha-postgresql-1?
If the request is performed on master postgresql-ha-postgresql-0, it does not occur errors. How to investigate this problem, what settings need to be changed?

Cluster is deployed in AWS and my microservice apps use the address to access the database: postgresql-ha-pgpool.default.svc.cluster.local:5432
Through port-forward I execute any sql-query to postgresql db without errors with any IDE, but when working with database from my cluster microservices and the request hits the slave (postgresql-ha-postgresql-1), I get "ERROR:  permission denied for table my_table".

**Comment by juan131** [comment]
Hi @maxinfosoft 

> What reasons can cause "Error: Permission Denied for Table" error during any database operation (even SELECT) located in slave-pod postgresql-ha-postgresql-1?

You should be able to run read-only queries in the ~slave~ read replicas nodes. That said, using PostgreSQL HA every client request should be done through the Pgpool nodes that should later on spread the queries among nodes.

Could you run the following query through the Pgpool node and share the output?

```
show pool_nodes
```

Then, access each backend pod individually and run these queries (share also the output):

```
SELECT * FROM repmgr.nodes;
SELECT * FROM pg_stat_replication;
```

**Comment by maxinfosoft** [comment]
Yes, thank you very much, of course.

After executing the locally this command:
kubectl port-forward --namespace default svc/postgresql-ha-pgpool 5432:5432

show pool_nodes;

0	postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless	5432	up	0.500000	primary	38014	true	0			2021-09-12 12:17:30
1	postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless	5432	up	0.500000	standby	35170	false	3997216			2021-09-12 12:17:30

SELECT * FROM repmgr.nodes;

1000		f	postgresql-ha-postgresql-0	primary	default	100	user=repmgr password=l5G7WACYfX host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5	repmgr	repmgr_slot_1000	/opt/bitnami/repmgr/conf/repmgr.conf
1001		t	postgresql-ha-postgresql-1	primary	default	100	user=repmgr password=l5G7WACYfX host=postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5	repmgr	repmgr_slot_1001	/opt/bitnami/repmgr/conf/repmgr.conf

SELECT * FROM pg_stat_replication;
Returns an empty table.

**Comment by juan131** [comment]
Hi @maxinfosoft 

There are two weird things I see in your output:

The "replication_delay" value for the `postgresql-ha-postgresql-1` is `3997216` according to the "show pool_nodes" command... That indicates that the ~slave~ read replicas node  cannot keep up with the updates occurring on the primary node.

Also.. The node `postgresql-ha-postgresql-0` appears as `active = false` according to the "SELECT * FROM repmgr.nodes" command; and there's no info in the "SELECT * FROM pg_stat_replication" one..

This clearly indicates that something went wrong... And your data is not being replicated between your replicas.

One question: did you run any "helm upgrade" action? What do you obtain when running the command below?

```
$ helm history postgresql-ha
```

**Comment by maxinfosoft** [comment]
helm history postgresql-ha
REVISION        UPDATED                         STATUS          CHART                   APP VERSION DESCRIPTION
1               Sat Sep 11 15:19:24 2021        superseded      postgresql-ha-7.9.3     11.13.0     Install complete
2               Sat Sep 11 15:23:31 2021        superseded      postgresql-ha-7.9.3     11.13.0     Upgrade complete
3               Sun Sep 12 00:53:29 2021        superseded      postgresql-ha-7.9.3     11.13.0     Upgrade complete
4               Sun Sep 12 15:17:15 2021        deployed        postgresql-ha-7.9.3     11.13.0     Upgrade complete

**Comment by juan131** [comment]
Hi @maxinfosoft 

I'd give a try to rolling back to a previous revision (e.g. revision 3) to see if sth went wrong during the last upgrade. Find more information about rollbacks in the link below:

- https://helm.sh/docs/helm/helm_rollback

In any case, I'd recommend you to backup your PVC(s) so you don't lose any data. Find information about how to do so using Velero in the link below:

- https://docs.bitnami.com/kubernetes/infrastructure/postgresql-ha/administration/backup-restore/

**Comment by juan131** [comment]
Hi @maxinfosoft 

I'm glad you were able to solve the issue by doing an upgrade. A couple of questions:

- Did the error "permission denied for table" disappeared? 
- Did you lose any data?

The Bitnami Pgpool image uses the "streaming replication mode", see:

- https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L416

Therefore, it's normal to see the "replication_delay" value.
