### ISSUE TITLE
[bitnami/mongo-sharded] Name overrides blocks Mongos

### ISSUE THREAD

**Issue by fam0x** [bitnami/charts#7502]
**Which chart**: mongo-sharded:3.9.5

**Describe the bug**
Setting either `nameOverride` or `fullnameOverride` causes `mongos` to be hung on `Found MongoDB server listening at...`. It does not proceed to `MongoDB server listening and working at...`. This causes only the config server to be up and every thing else is in Not Ready state.

**To Reproduce**
Deploy with either of `fullnameOverride` or `nameOverride` set.

**Expected behavior**
All pods to be in `Ready` state.

**Version of Helm and Kubernetes**

- Output of `helm version`:

```
`version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}`
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.12-gke.2101", GitCommit:"c8d75ae17b4628860e58bcdbe73c1f29dae62361", GitTreeState:"clean", BuildDate:"2021-08-18T18:42:22Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alvneiayu** [comment]
hi @fam0x 

I think that I am reproducing the same bug than you. Could you share with me logs from the pod to verify it? Just to verify that I am in the same line than you.

Thanks a lot

Álvaro

**Comment by alvneiayu** [comment]
hi @fam0x 
Sorry, it was a problem in my minikube with the persistent volumes. I can not reproduce your problem, I installed the chart using this command in GKE:
```
helm install mymongo bitnami/mongodb-sharded --set nameOverride=mongotest
```
and the pods are running without problems:
```
pod/mymongo-mongoalvaro-configsvr-0               1/1     Running   0          2m28s
pod/mymongo-mongoalvaro-mongos-7f65879b9d-bf55t   1/1     Running   0          2m29s
pod/mymongo-mongoalvaro-shard0-data-0             1/1     Running   0          2m28s
pod/mymongo-mongoalvaro-shard1-data-0             1/1     Running   0          2m28s
```
Could you share with me the values that you are using to install the chart, please?

Thanks a lot

Álvaro

**Comment by fam0x** [comment]
Can you try with release name same as override? I forgot to mention that.
Here is my command
```
helm install mongo bitnami/mongodb-sharded -f values.yaml
```
And 'values.yaml` has `nameOverride: mongo`

**Comment by alvneiayu** [comment]
hi @fam0x 

I tried with your same name and I can not reproduce your problem:

```
helm install mymongo bitnami/mongodb-sharded --set nameOverride=mongo
```

and I tried using the values.yaml:

```
git diff
diff --git a/bitnami/mongodb-sharded/values.yaml b/bitnami/mongodb-sharded/values.yaml
index 1e2ff9cf6..d777d1b2c 100644
--- a/bitnami/mongodb-sharded/values.yaml
+++ b/bitnami/mongodb-sharded/values.yaml
@@ -20,7 +20,7 @@ global:
 
 ## @param nameOverride String to partially override mongodb.fullname template (will maintain the release name)
 ##
-nameOverride: ""
+nameOverride: "mongo"
 ## @param fullnameOverride String to fully override mongodb.fullname template
 ##
 fullnameOverride: ""
```
and I tried with this values.yaml and I can not reproduce the problem.

I am trying with the 3.9.6 version. Could you share with me the version that you are using, please?

Thanks a lot

Álvaro

**Comment by fam0x** [comment]
I used 3.9.5.

**Comment by alvneiayu** [comment]
hi @fam0x 

Could you test with the last version (3.9.6), please?

Thanks

Álvaro

**Comment by fam0x** [comment]
I believe this was a transient error. I could not reproduce this again. Will close the issue

**Comment by alvneiayu** [comment]
perfect @fam0x. No prob and thanks a lot
