### ISSUE TITLE
Ceph Object Storage

### ISSUE THREAD

**Issue by J-L-I** [bitnami/charts#7518]
Struggling to set up thanos with ceph as my object storage.  I have rook ceph set up.  Using the helm chart to deploy thanos.  I can't seem to figure out where to put the objstore yaml info in values.yml file.  Any help would be appreciated.  Thanks.

**Comment by miguelaeh** [comment]
Hi @J-L-I ,
I think you are looking fo this line: https://github.com/bitnami/charts/blob/59d16cc6947a438573cbb554ffe8246827f403fd/bitnami/thanos/values.yaml#L66

**Comment by J-L-I** [comment]
> Hi @J-L-I ,
> I think you are looking fo this line:
> 
> https://github.com/bitnami/charts/blob/59d16cc6947a438573cbb554ffe8246827f403fd/bitnami/thanos/values.yaml#L66

Thanks, how exactly do I format the info there?

**Comment by miguelaeh** [comment]
Hi @J-L-I ,

That expects a string so it should be like:
```
objstoreConfig: |
  your configuration
  file here
```
