### ISSUE TITLE
[bitnami/postgresql-ha] Duplicate value in init container names when tls & persistance are enabled

### ISSUE THREAD

**Issue by druesendieb** [bitnami/charts#7522]
**Which chart**:
postgresql-ha
7.9.4

**Describe the bug**
Currently, there are 2 init containers defined with the same name: `init-chmod-data`
One for setting permissions on tls certificates, one for setting permissions to all data.
When tls & persistence is activated, the statefulset controller can't spawn pods due to duplicate init container names.

**To Reproduce**

1. set `postgresql.tls.enabled`
2.  set `persistence.enabled`
3. deploy the chart
4. `kubectl describe $(STATEFULSET)`

```
Events:
  Type     Reason            Age                From                    Message
  ----     ------            ----               ----                    -------
  Normal   SuccessfulCreate  16s                statefulset-controller  create Claim data-dbname-postgresql-0 Pod dbname-postgresql-0 in StatefulSet dbname-postgresql success
  Warning  FailedCreate      6s (x12 over 16s)  statefulset-controller  create Pod dbname-postgresql-0 in StatefulSet dbname-postgresql failed error: Pod "dbname-postgresql-0" is invalid: spec.initContainers[1].name: Duplicate value: "init-chmod-data"
```

**Expected behaviour**
The stateful set should spawn successfully, with working init containers setting the correct file permissions.

**Possible solution**
My quickfix was to rename the tls init container from `init-chmod-data` to `init-chmod-tls` in `helm/templates/postgresql/statefulset.yaml`

```
      initContainers:
      {{- if .Values.postgresql.tls.enabled }}
        - name: init-chmod-tls
          image: {{ template "postgresql-ha.volumePermissionsImage" . }}
```

Another viable option would be to merge these 2 containers and add more templating logic.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14", GitCommit:"0fd2b5afdfe3134d6e1531365fdb37dd11f54d1c", GitTreeState:"clean", BuildDate:"2021-08-11T18:02:17Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
-

**Comment by alvneiayu** [comment]
hi @druesendieb 

As you said this is a bug in our chart, do you want to send us a PR fixing this, please? I think that your quickfix solution is a good one.

Thanks a lot for your time and your help

Álvaro

**Comment by druesendieb** [comment]
> hi @druesendieb
> 
> As you said this is a bug in our chart, do you want to send us a PR fixing this, please? I think that your quickfix solution is a good one.
> 
> Thanks a lot for your time and your help
> 
> Álvaro

Yeah no problem, happy to help!

**Comment by alvneiayu** [comment]
thanks a lot @druesendieb
