### ISSUE TITLE
allow users to leave certCAFilename empty

### ISSUE THREAD

**Issue by fernandosierrap** [bitnami/charts#7524]
**Which chart**:
redis-cluster

**Is your feature request related to a problem? Please describe.**
TLS: if people use to generate the certificate something like letsencrypt, the generated secret haven't got the CA cert and is not possible to use the TLS. 

**Describe the solution you'd like**
leave clear the certCAFilename to use the internal ca from K8s cluster.

**Describe alternatives you've considered**

**Additional context**

**Comment by yilmi** [comment]
Hi @fernandosierrap, For these cases, we have described how to [create the secret with the certificates files](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#securing-traffic-using-tls). But I'm not sure to completely understand your use case here.

**Comment by fernandosierrap** [comment]
I have a traefik that creates my own certificates automatically and generate a secret with the cert and key files, but not with the CA. I need to get the CA from my internal pod an create this new secret. I think that the CA file could be get it from the cluster automatically by redis. or it is mandatory to use the CA file?

**Comment by yilmi** [comment]
Hi @fernandosierrap, yes it seems that the CA file is required, if you look a bit at the redis-cluster container, you can see that we check if it is provided: https://github.com/bitnami/bitnami-docker-redis-cluster/search?q=REDIS_TLS_CA_FILE

We also pass it to the redis-cli, which in turn uses it to establish their SSLContext [as you can see here](https://github.com/redis/hiredis/blob/master/ssl.c#L272) and also [here]( https://github.com/redis/redis/blob/unstable/deps/hiredis/ssl.c#L236). This in turns call an OpenSSL function, that fails if not CA File or CA Path is passed. You can see the return values of OpenSSL function they use in the [project documentation for this function](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_load_verify_locations.html).

**Comment by fernandosierrap** [comment]
thank you so much
