### ISSUE TITLE
[bitnami/minio] Bump image tag

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/charts#7525]
**Which chart**:
bitnami/minio

**Describe the bug**
Fixed console address for distributed mode
- https://github.com/bitnami/bitnami-docker-minio/pull/24
- https://github.com/bitnami/bitnami-docker-minio/issues/22

**Expected behavior**
Need to bump image tag to `2021.9.9-debian-10-r5` or above

**Additional context**
As i understand version bump is automated and i need some help from bitnami members, because i am not familiar with internal tools

**Comment by migruiz4** [comment]
Hi @sergeyshaykhullin,

The next MinIO PR https://github.com/bitnami/charts/pull/7526 will also update the MinIO image version bump automatically.

**Comment by sergeyshaykhullin** [comment]
Thanks
