### ISSUE TITLE
Some upstream charts are broken due to old templates

### ISSUE THREAD

**Issue by prydonius** [bitnami/charts#753]
The logic we have that syncs upstream Bitnami charts (developed out of https://github.com/helm/charts) to the upstream folder in this repo appears to only sync new changes and not delete files that are no longer used.

I found that the Redis chart is affected by this, a `helm install bitnami/redis` will fail with the following error:

```
render error in \"redis/templates/svc.yaml\": template: redis/templates/svc.yaml:11:14: executing \"redis/templates/svc.yaml\" at \u003c.Values.service.anno...\u003e: can't evaluate field annotations in type interface {}
```

When looking for this template in the upstream repo, I found that templates/svc.yaml doesn't exist (removed in https://github.com/helm/charts/pull/4662/files), however the Redis in this repo still has the svc.yaml and deployment.yaml that got removed upstream (https://github.com/bitnami/charts/tree/master/upstreamed/redis/templates). This results in a currently broken chart.

We need to fix the sync logic to ensure we delete any files removed upstream (e.g. rsync with `--delete` option), and we need to manually resync every chart.

**Comment by juan131** [comment]
Thanks for reporting it @prydonius !!

We already have an internal task associated to this issue and we'll work on it asap. We will update this issue as soon as we have more news.

**Comment by juan131** [comment]
Every extra file has been removed from `upstreamed` charts. We updated the CI logic that retrieves the changes on the chart from https://github.com/helm/charts and, from now on, when a file is removed from the templates, it will be removed on this repo too.

I proceed to close this issue. Please feel free to reopen it if you find extra files that belong to previous versions of the charts again.
