### ISSUE TITLE
Metrics with an "exported_" prefix

### ISSUE THREAD

**Issue by rodrigoscferraz** [bitnami/charts#7534]
**Which chart**:
kube-prometheus - 6.1.8

**Describe the bug**
I don't think this is a bug, maybe i'm missing something ... I'm receiving metrics with an "exported_" prefix for namespace, pod and service. I saw some issues related to this but nothing specific about how to solve this question.

**To Reproduce**
A fresh install of k3d with kube-prometheus install
when i query something like:
`kube_pod_status_phase{phase="Running}`

All query results come with the "exported_" prefix for namespace, pod and service. 

**Expected behavior**
Query results with the correct namespace, pod and service in their respective labels

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by migruiz4** [comment]
Hi @rodrigoscferraz,

I think the setting you are looking for is the ServiceMonitor parameter `honorLabels` (https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#endpoint). 
From [Prometheus documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/):
```
# honor_labels controls how Prometheus handles conflicts between labels that are
# already present in scraped data and labels that Prometheus would attach
# server-side ("job" and "instance" labels, manually configured target
# labels, and labels generated by service discovery implementations).
#
# If honor_labels is set to "true", label conflicts are resolved by keeping label
# values from the scraped data and ignoring the conflicting server-side labels.
#
# If honor_labels is set to "false", label conflicts are resolved by renaming
# conflicting labels in the scraped data to "exported_<original-label>" (for
# example "exported_instance", "exported_job") and then attaching server-side
# labels.
#
# Setting honor_labels to "true" is useful for use cases such as federation and
# scraping the Pushgateway, where all labels specified in the target should be
# preserved.
#
# Note that any globally configured "external_labels" are unaffected by this
# setting. In communication with external systems, they are always applied only
# when a time series does not have a given label yet and are ignored otherwise.
[ honor_labels: <boolean> | default = false ]
```

**Comment by rodrigoscferraz** [comment]
@migruiz4 thx man! That's exactly what i'm looking for.
