### ISSUE TITLE
[bitnami/spring-cloud-data-flow] - Pod running Composed Task shouldhave status as Completed, instead of Running, when Task is finished

### ISSUE THREAD

**Issue by AbhijitBhattacharya** [bitnami/charts#7539]
**Which chart**:
bitnami/spring-cloud-data-flow

**Is your feature request related to a problem? Please describe.**
Pods representing Wrapper Task of the Composed-Task-Runner keeps on Running, even after Composed Tasks have finished. So it gives inaccurate description of the status of the launched Job on Minikube Dashboard.

**Describe the solution you'd like**
We can set the following spring property in ConfigMap of Dataflow, so that finished Composed Tasks (Parent Wrapper Task created by Composed-Task-Runner) have Pod status as Completed.
`spring.cloud.task.closecontextEnabled=true`
Referred: - https://github.com/spring-cloud/spring-cloud-dataflow/issues/3745
We might provide values configuration for this property, but in my Opinion it is a nice of have as default feature, with no side effects.

**Describe alternatives you've considered**
I had to update the above spring property directly in ConfigMap yaml file for dataflow, in order to achieve this. 
I tried to set this property using values override yaml file, but it is not working, and need research for first time users of this chart.
```
  extraEnvVars: 
    - name: spring.cloud.task.closecontextEnabled
      value: true
```

**Additional context**
Before applying the fix of above Spring property,  checked the pods status on local minikube cluster after launching Composed Task, with first-task and second-task getting completed, but Wrapper Task sample-loader pod still Running, after Task Execution marked as Complete on Spring Cloud Data Flow Dashboard.
-- --
sample-loader-16jjv3joq6                              1/1     Running     0          4m3s    10.244.2.13   multinode-kube-m03   <none>           <none>
sample-loader-first-task-85rrm57zom              0/1     Completed   0          94s     10.244.0.5    multinode-kube       <none>           <none>
multinode-kube-m02   <none>           <none>
sample-loader-second-task-eqll1qg8gl                      0/1     Completed   0          54s     10.244.1.9    multinode-kube-m02   <none>           <none>
-- --
After updating the above Spring property, all 3 Pods got Completed Status.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! If it is only adding the value in the configmap, would you like to submit a PR adding it?

**Comment by AbhijitBhattacharya** [comment]
> Hi,
> 
> Thank you so much for the feedback! If it is only adding the value in the configmap, would you like to submit a PR adding it?

Submitted PR:- https://github.com/bitnami/charts/pull/7567

**Comment by AbhijitBhattacharya** [comment]
PR has been merged. Closing the issue now.
