### ISSUE TITLE
Bitnami Elastic Search Cluster using azure terraform

### ISSUE THREAD

**Issue by maulinshah-cmd** [bitnami/charts#7540]
I'm trying to find to way deploy bitnami elastic search cluster on azure terraform with debian vm but not finding any way so if there is any way to create using using Azure terraform then it would be helpful.

**Comment by juan131** [comment]
Hi @maulinshah-cmd 

I think you're looking for our Multitier solution for Azure, see::

- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.elasticsearch-cluster
- https://docs.bitnami.com/azure-templates/apps/elasticsearch/get-started/multitier-intro/

**Comment by maulinshah-cmd** [comment]
> Hi @maulinshah-cmd
> 
> I think you're looking for our Multitier solution for Azure, see::
> 
> * https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.elasticsearch-cluster
> * https://docs.bitnami.com/azure-templates/apps/elasticsearch/get-started/multitier-intro/

Hi @juan131 

Can you please provide me any way to create Bitnami Elastic search cluster using azure Terraform?

**Comment by juan131** [comment]
Hi @maulinshah-cmd 

I'm afraid we don't have such a solution for Azure in our portfolio.

Our MultiTier solutions for Azure use [ARM Templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/overview).

**Comment by maulinshah-cmd** [comment]
@juan131 If you have any solution with ARM Templates then please provide me I will integrate it using terraform

**Comment by juan131** [comment]
@maulinshah-cmd it's the one I shared on my first comment:

- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.elasticsearch-cluster

Although it's a little bit hidden to be honest. To get it follow these setps:

- Open the link and click on "Get it now":

![Screenshot 2021-09-21 at 09 35 15](https://user-images.githubusercontent.com/6740773/134131061-d3a303b7-0fa9-4325-9443-2def5705a4f5.png)

- In the next page, click on "Create":

![Screenshot 2021-09-21 at 09 36 24](https://user-images.githubusercontent.com/6740773/134131026-8e2397c3-2fb7-4b64-a116-e39d0340868d.png)

- Then, fill the required information in "Basics" and "Environment Configuration" tabs and, finally, before creating the solution, there's an option to download the template:

![Screenshot_2021-09-21_at_09_43_26](https://user-images.githubusercontent.com/6740773/134131705-2dd04adc-c391-4111-b414-e88b21df169d.png)

There, you'll find the generated ARM template.
