### ISSUE TITLE
[bitnami/spring-cloud-data-flow] - Provide values configuration to skip database tables creation on startup

### ISSUE THREAD

**Issue by AbhijitBhattacharya** [bitnami/charts#7541]
**Which chart**:
bitnami/spring-cloud-data-flow

**Is your feature request related to a problem? Please describe.**
When we have external Database already having dataflow/skipper schema and tables created, then while re-installing spring-cloud-dataflow again in local minikube cluster using externalDatabase, values configuration is required to skip Dataflow/Skipper Database Table creation on startup.

**Describe the solution you'd like**
Following Spring property can be used in ConfigMap of server for dataflow & skipper, which skips database tables creation
`spring.flyway.enabled=false`

**Describe alternatives you've considered**
I had to update the above spring property directly in ConfigMap yaml file for dataflow, after install.

**Additional context**

**Comment by marcosbc** [comment]
Hi @AbhijitBhattacharya, this seems like a good improvement. Would you be up for contributing the change via a PR? You can find the sources of the chart in the [`templates`](https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow/templates) folder in the GitHub repo. We'd be glad to help getting your changes released into the chart.

**Comment by AbhijitBhattacharya** [comment]
> Hi @AbhijitBhattacharya, this seems like a good improvement. Would you be up for contributing the change via a PR? You can find the sources of the chart in the [`templates`](https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow/templates) folder in the GitHub repo. We'd be glad to help getting your changes released into the chart.

Submitted PR: - https://github.com/bitnami/charts/pull/7570

**Comment by AbhijitBhattacharya** [comment]
PR has been merged. Closing the issue now.
