### ISSUE TITLE
Unmarshall Errors

### ISSUE THREAD

**Issue by J-L-I** [bitnami/charts#7544]
Both the compactor and storegateway pod logs show this error:

level=error ts=2021-09-20T14:21:32.447141843Z caller=main.go:130 err="yaml: unmarshal errors:\n  line 8: cannot unmarshal !!seq into map[string]string\ncreate s3 client\ngithub.com/thanos-io/thanos/pkg/objstore/client.NewBucket\n\t/app/pkg/objstore/client/factory.go:77\nmain.runCompact\n\t/app/cmd/thanos/compact.go:202\nmain.registerCompact.func1\n\t/app/cmd/thanos/compact.go:92\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\npreparing compact command failed\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371

Not sure how to troubleshoot this one.  Any help is much appreciated.  Thanks.

**Comment by rodrigoscferraz** [comment]
@J-L-I i had a similar issue, but with prometheus, it was an error in my yaml file. I just removed the first line `scrape_config` and it works. Maybe you have the same problem. Review your yaml file, or post the file here so we can see what's happening.


`
scrape_config:
# Additional ISTIO jobs
  - job_name: 'istiod'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istiod;http-monitoring
`

**Comment by juan131** [comment]
Hi @J-L-I 

I noticed you closed the issue. Were you able to solve the problem with Thanos?
