### ISSUE TITLE
[bitnami/thanos] compactor and storegateway ingress does not include common name

### ISSUE THREAD

**Issue by stephenrlouie** [bitnami/charts#7546]
**Which chart**:
Thanos - 6.0.1

**Describe the bug**
Compactor and storegateway do not include the common name into the backend service decalration.

Working Example:
- [Query](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query/ingress.yaml#L32)
- [Query](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query/ingress.yaml#L42)

Failing Examples:
- [Compactor](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/compactor/ingress.yaml#L27)
- [Compactor](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/compactor/ingress.yaml#L37)
- [Storegateway](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/storegateway/ingress.yaml#L27)
- [Storegateway](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/storegateway/ingress.yaml#L37)

**To Reproduce**
1. Deploy compactor and storegateway with a ingress enabled

**Expected behavior**
The ingress should point at the correct service name but it does not. It seems hard coded to `thanos-storegateway` and `thanos-compactor`.

**Comment by carrodher** [comment]
Thanks for creating the PR, we will review it and provide feedback during the day. Thanks again!

**Comment by stephenrlouie** [comment]
@carrodher : Just wanted to see if there was anything I could do to help move this along

**Comment by carrodher** [comment]
Sorry, it seems due to an issue in the integration between GitHub and our internal system we didn't detect the PR. I just reviewed it and launched some internal tests, if everything works fine it should be automatically merged and pushed to the Helm registry after some time (this issue will be automatically merged as well).
