### ISSUE TITLE
[bitnami/harbor] not compatible with [bitnami/redis-cluster] ?

### ISSUE THREAD

**Issue by jmaaks** [bitnami/charts#7549]
I don't see anything in the [bitnami/harbor] Helm chart that mentions this, but it doesn't appear to be compatible with [bitnami/redis-cluster].  When using redis-cluster, core and jobservice pods restart repeatedly, and logs seem to say it can't follow a "moved" status from redis (I'm guessing this is the svc doing redirects to a redis cluster node).  Simply re-deploying Harbor using [bitnami/redis] works perfectly.

This [Harbor Helm page](https://github.com/goharbor/harbor-helm/blob/master/docs/High%20Availability.md) states:

> As the Redis client used by Harbor's upstream projects doesn't support Sentinel, Harbor can only work with a single entry point Redis. You can refer to this guide to setup a HAProxy before the Redis to expose a single entry point.

Is this also the case with [bitnami/harbor] ?

**Comment by rafariossaa** [comment]
Hi,
 Harbor chart uses bitnami/redis chart as subchart, but not redis-cluster. 
 As you quoted, this is not related to the chart but to harbor implementation that is not aware of redis sentinels.

**Comment by rafariossaa** [comment]
Hi,
  You are welcome, I am glad to help.
  I am closing this issue.
