### ISSUE TITLE
Bitnami opencart3.0.3.8-1 base herf

### ISSUE THREAD

**Issue by loveckrs** [bitnami/charts#7552]
Hello, I want to enable https,But when I try to modify config and admin/config Make it point https,opening the website base href Still http,Backstage ssl Also turned on,
Config When the modification is completed, it sometimes changes back to http.
![Screenshot_2021-09-21-13-04-15-24](https://user-images.githubusercontent.com/73698202/134114378-7cb42414-acfd-435b-9f55-60ee49e0de8d.jpg)
![IMG_20210921_130654](https://user-images.githubusercontent.com/73698202/134114523-78e35d23-3b62-4b80-bf1c-abdce7f7088d.jpg)

**Comment by Mauraza** [comment]
Hi @loveckrs,

Could you share the values are you using to deploy the chart?

**Comment by loveckrs** [comment]
deploy the chart Where to get it
this opencart All default values Only modify config inside http to https and Backstage ssl Turn on
Feel modified config Doesn't work

Thanks for reply

**Comment by Mauraza** [comment]
Hi @loveckrs,

Do you want to enable HTTPS by default? Could you try with `OPENCART_ENABLE_HTTPS` https://github.com/bitnami/bitnami-docker-opencart#user-and-site-configuration
