### ISSUE TITLE
[Request] Federated Queues

### ISSUE THREAD

**Issue by Scorito-Dev** [bitnami/charts#7553]
**Is your feature request related to a problem? Please describe.**
We currently only have 1 queue per node, if a node fails we lose the queue as well until the node is recovered, RabbitMQ has something for this which is called Federated Queue's (read here: https://www.rabbitmq.com/federated-queues.html) is this something you can implement?

**Comment by migruiz4** [comment]
Hi @Scorito-Dev,

The RabbitMQ chart has the values `plugins` and `communityPlugins` that can be used to enable the federation plugin.

I may be wrong, but based on your comment and by looking at the Federation plugin documentation, I think that what you are looking for is Quorum queues (https://www.rabbitmq.com/quorum-queues.html) that would provide you with high availability in case of node failure.

**Comment by Scorito-Dev** [comment]
This worked indeed, by adding the plugin to 'extraPlugins' it is now available in the UI, apparently it was already available to us but we needed to change the x-queue-type to 'quorem'
