### ISSUE TITLE
Zookeeper Statefulsets does not work with custom namespace.

### ISSUE THREAD

**Issue by ingared8** [bitnami/charts#758]
Zookeeper statefulsets does not work with custom namespaces . Service Discovery fails.

In the statefulset.yaml , the following needs to be rectified 

 - name: Zookeeper
  value: zk-zookeeper-0.zk-zookeeper-headless.**default**.svc.cluster.local:2888:3888

 - name: Zookeeper
   value: zk-zookeeper-0.zk-zookeeper-headless.**my_namespace**.svc.cluster.local:2888:3888

This might be also breaking Kafka when installing with a custom namespace.

**Comment by juan131** [comment]
Hi @ingared8 

You're right! There's a bug on the template and it's assuming you always use the default namespace. I just created [this PR](https://github.com/bitnami/charts/pull/760) to fix it.

Thanks so much for reporting it.

**Comment by juan131** [comment]
Hi @ingared8

We just landed the changes. Could you please give the new chart a try? Please let us know if you face any issue deploying it on a custom namespace.
