### ISSUE TITLE
Cassandra Helm Chart JMX expose for remote access

### ISSUE THREAD

**Issue by aeg12345** [bitnami/charts#7584]
**Which chart**:
The name (and version) of the affected chart.
Cassandra Helm chart:
https://github.com/bitnami/charts/tree/master/bitnami/cassandra/
**Is your feature request related to a problem? Please describe.**
I want to expose my JMX port for remote access for monitoring purposes.

**Describe the solution you'd like**
I want to be able to access JMX from a jumpbox vm outside kubernetes cluster.

**Describe alternatives you've considered**
I tried the solutions mentioned in previous issues none of them worked.

**Additional context**
Greetings, I have the same need of exposing the JMX service for monitoring purposes.
The monitoring tool is on a jumpbox which is outside kubernetes network therefore I want to expose it via nodeport.
This can be done easiliy for cqlsh port 9042 but jmx server refuses remote connections.

I also investigated this [issue](https://github.com/bitnami/charts/issues/5294) but it did help resolution.

I tried solution mentioned in this [issue](https://github.com/bitnami/charts/issues/5574) by setting remote hostname parameters but I was not able to achieve success. 

My values yaml is:
image:
  debug: true
dbUser:
  user: cassandra
  forcePassword: false
  password: "cassandra"
cluster.seedCount: 2
replicaCount: 2
extraEnvVars:
  - name: JVM_OPTS
    value: "-Dcom.sun.management.jmxremote.authenticate=true -Dcassandra.jmx.remote.login.config=CassandraLogin -Djava.security.auth.login.config=/opt/bitnami/cassandra/conf/cassandra-jaas.config -Dcassandra.jmx.authorizer=org.apache.cassandra.auth.jmx.AuthorizationProxy -Djava.rmi.server.hostname=cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local -Dcassandra.jmx.remote.port=7199"
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: true
  runAsUser: 1000640001

I tried setting both JVM_OPTS and CASSANDRA_CFG_ENV_JVM_OPTS both was not able to succeed.
I also tried server.hostname as 0.0.0.0 or set the cluster ip address of the nodeport service that did not work either. 

I tried setting custom configuration mentioned [here](https://docs.bitnami.com/kubernetes/infrastructure/cassandra/configuration/customize-new-instance/) but the configmap values are not mentioned I tried setting configmap value as: 

cassandra-env.sh: "JMX values"

but it failed so I guess it only customizes the cassandra.yaml.
There was no documentation about what config files can be set and which one are configurable I would be grateful if you can provide me with some if I missed it.

The cassandra yaml parameters about authorizer and authenticator were already set correctly for JMX with cassandra authentication so I did not meddle with it.

I would be grateful if you can guide me through a way to enable remote JMX

Thanks,
Regards,

**Comment by marcosbc** [comment]
Hi, when you mention that it doesn't work, could you be more specific? I.e. could you check that the port was actually opened?

**Comment by aeg12345** [comment]
Greetings,
Thanks for the reply,
Actually I can check the port is listening via nodetool from the pods's terminal, I can see the pod's ip and 
cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local set to pod's ip in the pod's /etc/hosts file but my stateful set 2 replicas when I try to connect to other pod it gives connection refused. But I can access locally via nodetool.

$ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.128.2.26     cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local      cassandra-test-0

### Local connection from cassandra-test-0
$ nodetool -u cassandra -pw cassandra status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load        Tokens  Owns (effective)  Host ID                               Rack 
UN  10.128.2.26   247.82 KiB  256     100.0%            361232fc-879a-433d-b083-236538c23b58  rack1
UN  10.129.2.124  378.25 KiB  256     100.0%            31ae961f-8480-4c96-8d2e-a543b8dbc9ff  rack1

$ hostname 
cassandra-test-0
$ nodetool -h cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local -u cassandra -pw cassandra status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load        Tokens  Owns (effective)  Host ID                               Rack 
UN  10.128.2.26   247.82 KiB  256     100.0%            361232fc-879a-433d-b083-236538c23b58  rack1
UN  10.129.2.124  378.25 KiB  256     100.0%            31ae961f-8480-4c96-8d2e-a543b8dbc9ff  rack1

### From cassandra-test-1 to cassandra-test-0 remote JMX connection

$ hostname
cassandra-test-1
$ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.129.2.124    cassandra-test-1.cassandra-test-headless.ksps248.svc.cluster.local      cassandra-test-1
$ nodetool -h cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local -u cassandra -pw cassandra status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load        Tokens  Owns (effective)  Host ID                               Rack 
UN  10.128.2.26   247.82 KiB  256     100.0%            361232fc-879a-433d-b083-236538c23b58  rack1
UN  10.129.2.124  276.49 KiB  256     100.0%            31ae961f-8480-4c96-8d2e-a543b8dbc9ff  rack1

### From cassandra-test-0 to cassandra-test-1 remote jmx connection

$ hostname
cassandra-test-0
$ nodetool -h cassandra-test-1.cassandra-test-headless.ksps248.svc.cluster.local -u cassandra -pw cassandra status
nodetool: Failed to connect to 'cassandra-test-1.cassandra-test-headless.ksps248.svc.cluster.local:7199' - ConnectException: 'Connection refused (Connection refused)'.


### My values.yaml
image:
  debug: true
dbUser:
  user: cassandra
  forcePassword: false
  password: "cassandra"
cluster.seedCount: 2
replicaCount: 2
extraEnvVars:
  - name: JVM_OPTS
    value: "-Dcom.sun.management.jmxremote.authenticate=true -Dcassandra.jmx.remote.login.config=CassandraLogin -Djava.security.auth.login.config=/opt/bitnami/cassandra/conf/cassandra-jaas.config -Dcassandra.jmx.authorizer=org.apache.cassandra.auth.jmx.AuthorizationProxy -Djava.rmi.server.hostname=cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local -Dcassandra.jmx.remote.port=7199"
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: true
  runAsUser: 1000640001


I also tried setting rmi.server.hostname to 0.0.0.0 but that did not help either.

**Comment by marcosbc** [comment]
Hi @aeg12345, it seems from that like your Kubernetes cluster hostnames are not publicly accessible. If so, it is likely a network configuration error. I recommend to check your cluster's network configuration, and ensure that the expected hostnames are public, or at least accessible in the private network you want to access the pods from.

**Comment by aeg12345** [comment]
Greetings, 
The jumpbox and worker nodes share the same network so connectivity is not the issue here, I can access the data port 9042 via cqlsh with nodeport service. 
The concert is about what to enter rmi.server.hostname parameter because normally this is set to ip but would not be logical in a container environment and all pods must have its own since it will be injected to stateful set. 

Therefore I need your guidance on how to set the rmi.server.hostname parameter

**Comment by marcosbc** [comment]
Hi @aeg12345, if you need to set a dynamic rmi.server.hostname, one per pod, you could always overwrite the command. For instance, check [this Solr example](https://github.com/bitnami/charts/blob/master/bitnami/solr/templates/statefulset.yaml#L155):

```yaml
          command:
            - bash
            - -ec
            - |
              {{- if .Values.cloudBootstrap }}
              NODE_ID="${MY_POD_NAME#"{{ include "solr.fullname" . }}-"}"
              if [[ "$NODE_ID" -eq "0" ]]; then
                export SOLR_CLOUD_BOOTSTRAP=yes
              fi
              {{- end }}
              # Use hostname instead of IP to register in Zookeeper
              export SOLR_HOST="${MY_POD_NAME}.{{ include "solr.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
              /opt/bitnami/scripts/solr/entrypoint.sh /opt/bitnami/scripts/solr/run.sh
```

So instead you would set `JVM_OPTS` and call `/opt/bitnami/scripts/cassandra/entrypoint.sh /opt/bitnami/scripts/cassandra/run.sh`.

**Comment by aeg12345** [comment]
If anyone else is faced with the same problem the steps we used to resolve is:

sed -i 's|LOCAL_JMX=yes|LOCAL_JMX=no|' /etc/cassandra/conf/cassandra-env-test.sh
sed -i '\|JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.password.file=/etc/cassandra/jmxremote.password"|s|^|#|g' /etc/cassandra/conf/cassandra-env-test.sh
sed -i '\|JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.remote.login.config=CassandraLogin"|s|^#||g' /etc/cassandra/conf/cassandra-env-test.sh
sed -i '\|JVM_OPTS="$JVM_OPTS -Djava.security.auth.login.config=$CASSANDRA_CONF/cassandra-jaas.config"|s|^#||g' /etc/cassandra/conf/cassandra-env-test.sh
sed -i '\|JVM_OPTS="$JVM_OPTS -Dcassandra.jmx.authorizer=org.apache.cassandra.auth.jmx.AuthorizationProxy"|s|^#||g' /etc/cassandra/conf/cassandra-env-test.sh

Also change the JMX_PORT parameter to something higher than 3000 to match the nodeport value to your JMX_port value

Changed these parameters in the default cassandra-env.sh and mapped it as configMap in the values.yaml

kubectl create configmap cassandra-env.sh --from-file cassandra-env.sh

Add below parameter to values.yaml:
existingConfiguration: "cassandraenv.sh"

Then edit statefulset template in the helm packages to location as explained by marco above:
 if [[ $POD_NAME =~ (.*)-0$ ]]; then
                  echo "Setting node as password seeder"
                  export CASSANDRA_PASSWORD_SEEDER=yes
              else
                  # Only node 0 will execute the startup initdb scripts
                  export CASSANDRA_IGNORE_INITDB_SCRIPTS=1
              fi
              #export JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=${POD_IP}"
              export JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=${POD_NAME}"
              echo $JVM_OPTS
              /opt/bitnami/scripts/cassandra/entrypoint.sh /opt/bitnami/scripts/cassandra/run.sh

We used pod name to expose the jmx and set to hostname to worker node ip in the etc/hosts of the vm outside of the kubernetes cluster that will access via nodetool.

Install the modified local helm chart and create the nodeport service with specific port binding
  ports:
    - port: 30490
      targetPort: 30490
      nodePort: 30490

In service use selector to apply which pod you will access to and expose jmx.

Access with pod name with nodetool
nodetool -h podname -p 30490 -u cassandra -pw cassandra_pass status
