### ISSUE TITLE
[bitnami/kafka] Probing node 0 broker version,  line 1240, in check_version , raise Errors.NodeNotReadyError()

### ISSUE THREAD

**Issue by maximx-git** [bitnami/charts#7595]
**Which chart**:
bitnami/kafka/ release 14.1.1

**Describe the bug**
Could not access Kafka brokers from outside the cluster using random NodePorts option. The problem exists only  after initial deployment and disappears after all brokers redeployed. 

ERROR OUTPUT:
<BrokerConnection node_id=0 host=X.X.X.X:31350 <connecting> [IPv4 ('X.X.X.X', 31350)]>: connecting to X.X.X.X:31350 [('X.X.X.X', 31350) IPv4]
Probing node 0 broker version
Traceback (most recent call last):
  File "C:\script.py", line 68, in <module>
    admin = KafkaAdminClient(bootstrap_servers=KAFKA_NODE)
  File "C:\Users\mfinex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kafka\admin\client.py", line 218, in __init__
    self._refresh_controller_id()
  File "C:\Users\mfinex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kafka\admin\client.py", line 278, in _refresh_controller_id
    controller_version = self._client.check_version(controller_id, timeout=(self.config['api_version_auto_timeout_ms'] / 1000))
  File "C:\Users\mfinex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kafka\client_async.py", line 909, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "C:\Users\mfinex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kafka\conn.py", line 1240, in check_version
    raise Errors.NodeNotReadyError()
kafka.errors.NodeNotReadyError: NodeNotReadyError

**To Reproduce**
1. Deployment is on Rancher platform using RancherCLI.
2. Deploy Zookeeper 
./rancher apps install bitnami-zookeeper zookeeper --version 7.4.3 --values zookeeper.values.yaml --namespace kafka
3. Deploying Kafka
./rancher apps install bitnami-kafka kafka --version 14.1.1 --values kafka.values.yaml --namespace kafka

**Expected behavior**
Python KafkaAdminClient should connect to broker:

CORRECT OUTPUT:
<BrokerConnection node_id=0 host=X.X.X.X:32521 <connecting> [IPv4 ('X.X.X.X', 32521)]>: connecting to X.X.X.X:32521 [('X.X.X.X', 32521) IPv4]
Probing node 0 broker version
<BrokerConnection node_id=0 host=X.X.X.X:32521 <connecting> [IPv4 ('X.X.X.X', 32521)]>: Connection complete.
Broker version identified as 2.5.0
Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup

**Additional context**
Nodeports in server.properties and in "auto-discovery" init containers for each broker are different from NodePorts in External services , but become the same after brokers redeployed.

**Version of Helm**:
helm_v3,  master branch

**Version of Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"

**Python Client description**:
kafka-python 2.0.2 package installed

from kafka.admin import NewTopic
from kafka import KafkaAdminClient, KafkaProducer, KafkaConsumer
admin = KafkaAdminClient(bootstrap_servers='hostname:9094')
admin.list_topics()

**zookeeper.values.yaml**
https://github.com/maximx-git/bitnami_kafka_issue_7595/blob/6b5fd8cb14d34f634749c8c428b773f2d164b63a/zookeeper.values.yaml

**kafka.values.yaml**
https://github.com/maximx-git/bitnami_kafka_issue_7595/blob/6b5fd8cb14d34f634749c8c428b773f2d164b63a/kafka.values.yaml

**Comment by randradas** [comment]
hello @maximx-git would it be possible to reproduce the error using k8s directly? although bitnami charts should work on Rancher currently we do not test on Rancher officially. Thank you!

**Comment by maximx-git** [comment]
Hello @randradas  !
In release version 14.0.1 all files worked on Rancher as well with no issues.
I guess the issue can be reproduced in k8s (and I can try) but it shouldn't be different (as my usage is quite basic), and eventually I wonder what is this timing issue and how can I fix it , as it keeps me from moving forward at my job (and I have to solve this on Rancher), thanks !

**Comment by maximx-git** [comment]
Solved.
Rancher keeps a cache of helm charts from previous deployment so previous port number of External Service NodePort passes to broker's server.properties and autodiscovery init container.
