### ISSUE TITLE
[bitnami/elasticsearch] Add support for topologySpreadConstraints 

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#7600]
**Which chart**:
elasticsearch 17.0.4

**Is your feature request related to a problem? Please describe.**
Whilst the chart allows you to set affinity, and anti-affinity it restricts me to a number of replicas to the number of nodes i have. Whilst I have tried to use preferred for the softer approach, I still get the majority of my pods scheduled onto one node which results in my node dying with OOM errors

**Describe the solution you'd like**

I'd suggest to add a topologySpreadConstraints configuration (see https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) to allow spreading the pods evenly.

**Describe alternatives you've considered**
Reduce my number of replicas to the number of nodes i have using anti-affinity for the label on the pod itself and increase the available resources to each replica (i'd rather have more replicas though)

**Additional context**
Relates to: https://github.com/bitnami/charts/issues/7391

**Comment by juan131** [comment]
Thanks so much for the suggestion @jack1902 

As I mentioned at https://github.com/bitnami/charts/issues/7391, this topic is added to the list of features to standardize in the catalog. Expect a PR in the next days from one of my colleagues adding it.
