### ISSUE TITLE
[bitnami/minio] missing values to configure s3 gateway caching

### ISSUE THREAD

**Issue by DaviGia** [bitnami/charts#7602]
**Which chart**:
bitnami/minio:8.1.2

**Is your feature request related to a problem? Please describe.**
I currently use this chart in S3 gateway mode within my cluster. I would like to enable [disk caching](https://docs.min.io/docs/minio-disk-cache-guide.html) but currently there is no way to do it from chart values.

I could circumvent this limitation by specifying the envvars manually using the following values:

``` yaml
extraEnv:
  - name: MINIO_CACHE
    value: on
  - name: MINIO_CACHE_DRIVES
    value: /data/cache
```

But the problem is that the chart does not create persistent volume claims if s3 gateway is active (there is a condition within the helper function to prevent it).  This means that the cache directory is not persisted.

**Describe the solution you'd like**
I would like to be able to configure MinIO disk caching through the chart and have the persistency for the configured cache path.

**Describe alternatives you've considered**
See above.

**Comment by carrodher** [comment]
Thanks for your suggestion, would you like to contribute with a PR? We will be happy to review a PR adding this feature
