### ISSUE TITLE
On installation wp-content directory does not get created. Also unable to copy the themes and plugins to wp-content directory.

### ISSUE THREAD

**Issue by JigneshRawal** [bitnami/charts#7604]
**Describe the bug**
The directory /opt/bitnami/wordpress/wp-content is not created with the bitami/wordpress image.
The container does not have internet access. So i need to push the wp-content/* contents via bitbucket.
But i am unable to copy the contents of from local git to the container /opt/bitnami/wordpress/wp-content location.

**To Reproduce**
i am using the image /bitnami/wordpress:5.8.0-debian-10-r18

**Expected behavior**
i should have been able to copy to the wp-content folder else i cannot installed locally developed theme and plugins.

**Additional context**
I have tried the following:
(to create the folder)
 customPostInitScripts:
    create-wp-content.sh: |
      #!/bin/bash
      mkdir -p /bitnami/wordpress/wp-content/themes/
      mkdir -p /bitnami/wordpress/wp-content/plugins/
But in no way i can copy the wp-content locally created to the container.
I have tried to COPY test.txt /bitnami/wordpress/wp-content/plugins/ - this does not work either.

**Comment by rafariossaa** [comment]
Hi,
  How did you copy the file into the pod ? Did you get any error ? Could you check what is the content of the directory after copying it ?

**Comment by JigneshRawal** [comment]
Hi ,
I was expecting the directory wp-content to be created under /bitnami/wordpress on running the docker image.
But the directory is not created.
i wrote a postinit script as below to create the directory. But chown given operation not permitted as with the script the directory is created with root:root (cant change this to daemon:root) for apache to read write.
the volume is a persistent volume.
Copying the content to /bitnami/wordpress is not helpfull.

`customPostInitScripts:
    create-wp-content.sh: |
      #!/bin/bash
      mkdir -p /bitnami/wordpress/wp-content/themes
      mkdir -p /bitnami/wordpress/wp-content/plugins
      cp -r /tmp/themes/* /bitnami/wordpress/wp-content/themes
      cp -r /tmp/plugins/* /bitnami/wordpress/wp-content/plugins`

values.yaml
`## Persistence Parameters
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
  persistence:
    ## @param persistence.enabled Enable persistence using Persistent Volume Claims
    ##
    enabled: true
    ## @param persistence.storageClass Persistent Volume storage class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
    ##
    storageClass: ""
    ## @param persistence.accessModes [array] Persistent Volume access modes
    ##
    accessModes:
      - ReadWriteMany
    ## @param persistence.accessMode Persistent Volume access mode (DEPRECATED: use `persistence.accessModes` instead)
    ##
    accessMode: ReadWriteMany
    ## @param persistence.size Persistent Volume size
    ##
    size: 10Gi
    ## @param persistence.dataSource Custom PVC data source
    ##
    dataSource: {}
    ## @param persistence.existingClaim The name of an existing PVC to use for persistence
    ##
    existingClaim: ""
## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the podSecurityContext/containerSecurityContext parameters
##
  volumePermissions:
    ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
    ##
    enabled: false
    ## Bitnami Shell image
    ## ref: https://hub.docker.com/r/bitnami/bitnami-shell/tags/
    ## @param volumePermissions.image.registry Bitnami Shell image registry
    ## @param volumePermissions.image.repository Bitnami Shell image repository
    ## @param volumePermissions.image.tag Bitnami Shell image tag (immutable tags are recommended)
    ## @param volumePermissions.image.pullPolicy Bitnami Shell image pull policy
    ## @param volumePermissions.image.pullSecrets Bitnami Shell image pull secrets
    ##`

I am badly stuck with these for weeks now :( Please help

**Comment by rafariossaa** [comment]
Hi,
 I added this to `values.yaml` :

```diff
$ git diff values.yaml
diff --git a/bitnami/wordpress/values.yaml b/bitnami/wordpress/values.yaml
index 70c606f00..dd0dff349 100644
--- a/bitnami/wordpress/values.yaml
+++ b/bitnami/wordpress/values.yaml
@@ -177,7 +177,14 @@ existingApacheConfigurationConfigMap: ""
 ##     RewriteBase /
 ##     ...
 ##
-customPostInitScripts: {}
+customPostInitScripts:
+    create-wp-content.sh: |
+      #!/bin/bash
+      mkdir -p /bitnami/wordpress/wp-content/themes
+      mkdir -p /bitnami/wordpress/wp-content/plugins
        ls -l /bitnami/wordpress/*
+      cp -r /tmp/themes/* /bitnami/wordpress/wp-content/themes
+      cp -r /tmp/plugins/* /bitnami/wordpress/wp-content/plugins
+
 ## SMTP mail delivery configuration
 ## ref: https://github.com/bitnami/bitnami-docker-wordpress/#smtp-configuration
 ## @param smtpHost SMTP server host
```

  And the directories got created, I got an error because I have not mounted the  `/tmp/ dir with the needed files to copy from.

```
...
wordpress 08:01:55.53 INFO  ==> Persisting WordPress installation
wordpress 08:01:57.27 INFO  ==> Executing /docker-entrypoint-init.d/..2021_09_27_08_01_13.561783176/create-wp-content.sh
-r--r----- 1 1001 root 4357 Sep 27 08:01 /bitnami/wordpress/wp-config.php

/bitnami/wordpress/wp-content:
total 24
-rw-rw-r--  1 1001 root   28 Sep 27 08:01 index.php
drwxrwxr-x  2 1001 root 4096 Sep 27 08:01 languages
drwxrwxr-x 12 1001 root 4096 Sep 27 08:01 plugins
drwxrwxr-x  5 1001 root 4096 Sep 27 08:01 themes
drwxrwxr-x  2 1001 root 4096 Sep 27 08:01 upgrade
drwxrwxr-x  3 1001 root 4096 Sep 27 08:01 uploads
cp: cannot stat '/tmp/themes/*': No such file or directory
cp: cannot stat '/tmp/plugins/*': No such file or directory
wordpress 08:01:57.28 ERROR ==> Failed to execute /docker-entrypoint-init.d/..2021_09_27_08_01_13.561783176/create-wp-content.sh
...
```

Could you try that ?

**Comment by rafariossaa** [comment]
Hi, 
  I am closing this issue, feel free to reopen it or create a new one if needed.
