### ISSUE TITLE
[ingress-controller] chart name regex issue

### ISSUE THREAD

**Issue by mohammadasim** [bitnami/charts#7605]
Hi 
I am using the latest Bitnami Ingress Controller chart to install the ingress controller. However, the helm install command is failing I am getting the following error:
```
Error: ConfigMap "nginx-ingress-controller-1632400074" is invalid: data[gzip-types"]: Invalid value: "gzip-types\"": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```
The command that I am using is
`helm install bitnami/nginx-ingress-controller -f new_prod_values.yml --generate-name -n config`

**Comment by miguelaeh** [comment]
Hi @mohammadasim ,
It seems that into your values.yaml there is a typo in a field. Search for `gzip-types`, it seems to be an unterminated string

**Comment by mohammadasim** [comment]
thanks, @miguelaeh, indeed that was the issue.
