### ISSUE TITLE
FluentD lifecycle commands

### ISSUE THREAD

**Issue by Forbzy** [bitnami/charts#7612]
**Which chart**:
FluentD

**Is your feature request related to a problem? Please describe.**
Can you update the chart to allow for lifecycle commands to be added. For my use case I have some fluent gems I need to install post start.

**Describe alternatives you've considered**
An alternative I've found is creating a new docker image with the gems and using that in my helm chart.

```
FROM docker.io/bitnami/fluentd:latest
LABEL maintainer "Bitnami <containers@bitnami.com>"

## Install custom Fluentd plugins
RUN fluent-gem install fluent-plugin-grok-parser
```

**Comment by alvneiayu** [comment]
hi @Forbzy

If you want to send us a contribution including the lifecycle, we are open to receive PRs. I will be really happy to review it. Please let me know.

Thanks a lot

Álvaro

**Comment by Forbzy** [comment]
Sure would I need permissions to push a feature branch to the repo?

**Comment by alvneiayu** [comment]
hi @Forbzy 

I think that all the users already have permissions. Take a look [this](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md), I think that it will help you.

Thanks a lot for your help and time

Álvaro

**Comment by Forbzy** [comment]
Hi @alvneiayu can you review my pull request?

**Comment by alvneiayu** [comment]
hi @Forbzy 

My colleague @carrodher is reviewing the change. So, he will handle your PR. Again, thanks a lot for your PR and your time.

Álvaro
