### ISSUE TITLE
[bitnami/mongodb] password lifecycle improvment

### ISSUE THREAD

**Issue by maulal** [bitnami/charts#7617]
**Which chart**:
mongodb

**Is your feature request related to a problem? Please describe.**
I want to think of a way to manage the password lifecycle. I'm maybe wrong, but i do not see any way to change a password efficiently in the chart ? All passwords are initialized by the chart installation, and even if we change the password inside the secret, it will not be applied and even worse, maybe some component will not work anymore (metrics for ex).

**Describe the solution you'd like**
For all mongodb users, except the root one, it's only a matter of updating the user password (if needed) with a root authentication. So we could make the chart doing those change (if needed) when a pod restart (to be at least sure that the secret match with the mongodb credentials).
For the root one, it's more complex... we need to store the old and the new password... i do not see any good way for doing this...

**Additional context**
I can try to help for this part with a PR ? if it looks good for the maintainer team.
Again great job ^^

**Comment by yilmi** [comment]
Hi @maulal,

Thanks for bringing this up, we'd love to see you contribute to our charts!

Before I just want to understand the context and  make sure you're considering the different [deployment architectures available](https://github.com/bitnami/charts/tree/master/bitnami/mongodb#architecture).
 
Also, as the credentials are passed through environment variables to our MongoDB container image, and used in the following script: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/5.0/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh

On my end, I assume that updating the secret (through the charts) would work because it wouldn't affect the existing pods and would let you manually update the passwords of the running instances, I'm adding a couple of references below:

At the container level, we don't create users in a configuration file but in the DB, so a change should be picked by all the pods. See below a truncated snippet of the function doing this work.
```bash
########################
# Create the appropriate users
# Globals:
#   MONGODB_*
# Arguments:
#   None
# Returns:
#   None
#########################
mongodb_create_users() {
    local result

...
            mongodb_execute "" "" "" "127.0.0.1" <<EOF
db.getSiblingDB('admin').createUser({ user: '$MONGODB_ROOT_USER', pwd: '$MONGODB_ROOT_PASSWORD', roles: [{role: 'root', db: 'admin'}] })
....
            mongodb_execute "$MONGODB_ROOT_USER" "$MONGODB_ROOT_PASSWORD" "" "127.0.0.1" <<EOF
db.getSiblingDB('$MONGODB_DATABASE').createUser({ user: '$MONGODB_USERNAME', pwd: '$MONGODB_PASSWORD', roles: [{role: 'readWrite', db: '$MONGODB_DATABASE'}] })
....
            mongodb_execute 'root' "$MONGODB_ROOT_PASSWORD" "" "127.0.0.1" <<EOF
db.getSiblingDB('admin').createUser({ user: '$MONGODB_METRICS_USERNAME', pwd: '$MONGODB_METRICS_PASSWORD', roles: [{role: 'clusterMonitor', db: 'admin'},{ role: 'read', db: 'local' }] })
...
    info "Users created"
}
```


At the chart level, we recreate the secret unless a previous one was provided: 
```mustache
{{/*
Return true if a secret object should be created for MongoDB&reg;
*/}}
{{- define "mongodb.createSecret" -}}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
    {{- true -}}
{{- else -}}
{{- end -}}
{{- end -}}
```

Thanks,
Yassine

**Comment by maulal** [comment]
Hey @yilmi ^^
First of all, i was aware about available architectures :) and what was in my mind is not related to a dedicated architecture, but it's more related to a security concern about password lifecycle that should be changed frequently.

All things (code) i've seen in the chart (or in the container) are only for the users creation. I did not saw anything for updating them ? Is it explained somewhere (the way to update mongodb passwords) ? maybe i have missed this part ?

If not, i can try to make a PR for updating them. something like `if exist update else create`. At the end, updating passwords (except for the admin/root one) should just be a matter of updating the secret and restart the pod.

Thanks,
Alexis

**Comment by yilmi** [comment]
Hi @maulal,

Could you please be more specific about the exact issues you have and the update flow you have in mind? 

Keep in mind that a chart can't be responsible for everything, there is container logic involved (see references in my previous comment) but most importantly you can't expect the first two to cover for application limitations/constraints. 
So far, it seems that your opinion is that the chart should be responsible for this rotation, but for that the container scripts would need to support what you want to do. 

I kindly invite you to look at our container scripts to understand in which cases the values provided may be applied.

I understand your concern about password rotation but I don't see how this is something that you can't do today, and what value your proposal would bring. Right now, the process of rotation would be:
- Update the secret at the K8S cluster level (through the chart)
- Update the password at the MongoDB Server level

From there on, scaling up, or restarting pods should be possible as the new pods will be given the newly updated password.

Regarding your comment:
> If not, i can try to make a PR for updating them. something like if exist update else create. At the end, updating passwords (except for the admin/root one) should just be a matter of updating the secret and restart the pod.

I would love to see you contribute, but I also want to make it worth your and our time. No it's not, please look at our container initialization function for more info on how we manage persisted data: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/5.0/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1098

Thanks!
Yass

**Comment by maulal** [comment]
Hi again @yilmi,
Ok, i understand now. Sorry to disturb you, i was not totally aware of the mechanism...
What i understand, is that, the mongodb password is not managed by the chart except for the initialization. I was hopping of a way to manage it.

Thanks for your answer :)
Alexis

**Comment by yilmi** [comment]
No worries @maulal, just wanted to make sure I understood your use case, I didn't want you to work on a contribution that wouldn't end up merged.

But we do need help for sure, so please keep looking for improvements looking at both our chart + docker scripts, I'm sure you'll have some good ideas in this area.

Thanks,
Yass
