### ISSUE TITLE
consul ui ingress resource only works if set to /

### ISSUE THREAD

**Issue by vtuson** [bitnami/charts#764]
I tried many many combinations of annotations but basically consul-ui always redirects to to /ui/ so the only way to get the ingress to work (that I have found) is to math path / (wont work for example if you make it /consul/)

This is due to a long standing issue with consul, seems that was fixed but broke again with the new UI - https://github.com/hashicorp/consul/issues/1930

Also it might be possible to work around this added a custom config  snippet (https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet) but I dont know enough about nginx to suggest a solution

**Comment by juan131** [comment]
Hi @vtuson 

Thanks for opening this issue! It seems there's no way to configure the UI path on the application itself, therefore, it's sth we could fix by adding some kind of env. variable to the container to use a custom path for the UI.

As you mentioned, a possible workaround would be using a configuration snippet so we can modify the way NGINX handle the proxy redirection. 

However, this configuration snippet will be including on the Ingress annotations (which are different depending on the Ingress solution you're using). Hence, my doubts about this approach. We could add some annotations for NGINX that will be ignored by other Ingress Controllers...

**Comment by vtuson** [comment]
you are right, that they wouldnt be generic, not sure if it is worth adding nginx as it is the standard upstream provided or not? but might be worth documenting it in the readme

**Comment by juan131** [comment]
What do you think @sameersbn @prydonius ?

**Comment by prydonius** [comment]
Perhaps the simplest thing for now is to document that Consul UI can only be exposed on the root in an Ingress. FYI, we have the same issue in Kubeapps, the Dashboard currently cannot be mounted in a subpath due to the way the React app loads things and uses routes.

**Comment by juan131** [comment]
Are you ok with just documenting it @vtuson ? We could also modify the `NOTES.txt` so we show a warning in case we detect someone is using a different path on the Ingress Rule.

**Comment by mumubin** [comment]
Is there a solution？

**Comment by juan131** [comment]
Hi @mumubin 

We didn't document anything so far. There are other users requesting similar features for other charts. If you take a look to the issue below, you'll find out there's a way to play with Ingress annotations so you add extra configuration with redirections:

https://github.com/helm/charts/issues/17196
