### ISSUE TITLE
[postgresql-ha] pgpool service name not working

### ISSUE THREAD

**Issue by stanltam** [bitnami/charts#7640]
I tired to install the helm chart in openshift, it is working if I connect to the db pod individually.
However, when I tried to connect to pgpool service(posdb-postgresql-ha-pgpool), it is not working.

Here is the step I produce:
If using the pgpool service
```oc port-forward --namespace db-test svc/posdb-postgresql-ha-pgpool 5432:5432

psql -h 127.0.0.1 -p 5432 -U postgres -c "select 1"
psql: error: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

If using individual pods:
```
oc port-forward posdb-postgresql-ha-postgresql-0 5432:5432

psql -h 127.0.0.1 -p 5432 -U postgres -c "select 1"
 ?column?
----------
        1
(1 row)

```

**Comment by marcosbc** [comment]
Hi @stanltam, you mentioned you are using the pgpool service but when you execute it, you are using localhost:

> If using the pgpool service
>```
>$ psql -h 127.0.0.1 -p 5432 -U postgres -c "select 1"
>...
>```

Make sure to specify the proper IP/port configuration.
