### ISSUE TITLE
How do one prepare/uncompress the backup when there's no required qpress present?

### ISSUE THREAD

**Issue by pentago** [bitnami/charts#766]
Here's the proof: https://i.imgur.com/7uPGKdh.png

**Comment by juan131** [comment]
Hi @pentago 

Could you create an issue on https://github.com/bitnami/bitnami-docker-mariadb? 

Please note that MariaDB chart uses that Docker Image and, therefore, we should discuss on that repo about missing packages/tools on the image. 

Thanks in advance

**Comment by pentago** [comment]
I just did, thanks!
https://github.com/bitnami/bitnami-docker-mariadb/issues/153
