### ISSUE TITLE
Add PVC to s3 bucket 

### ISSUE THREAD

**Issue by salinaaaaaa** [bitnami/charts#7678]
Jenkins chart: add s3 url to mount volume for Jenkins 

connecting to RDS would be great to

**Comment by alvneiayu** [comment]
hi @salinaaaaaa 

I am not expert in this topic. So I was investigating and reading some documents about this:

https://cloudian.com/blog/easily-provision-s3-buckets-on-hyperstore-with-kubernetes/
https://github.com/ctrox/csi-s3

I can not find any K8s official support (correct me if I am wrong). I can find several projects working in some solutions to this.

Following the cloudian example, I think that you can use the extraVolumes to define the StorageClass part but I have doubts about the specific bucket object definition (I think that we don't have support to include this part). I think that you have to include the bucket object definition yaml directly generating the template code (helm template) and the installing it.

It would be nice integrate something like this but I think that this support is still in progress (correct me if I am wrong). If you have more information about this, I can read a little bit more and we can find a possible solution to this.

thanks a lot 

Álvaro

**Comment by salinaaaaaa** [comment]
I’m looking into longhorn and minio

**Comment by alvneiayu** [comment]
hi @salinaaaaaa 

Could you provide me documentation about this, please? Just to have more context about your request.

Moreover, we are open to receive PRs and I will be really happy to review it.

Thanks a lot

Álvaro

**Comment by salinaaaaaa** [comment]
I’m just going to mount volumes to s3 & persist my data there.

**Comment by salinaaaaaa** [comment]
has anyone looked into the minio operator?
