### ISSUE TITLE
Kafka

### ISSUE THREAD

**Issue by Tenseiga** [bitnami/charts#768]
Hi Is there a provision to chnage the number of zookeeper nodes?

**Comment by Tenseiga** [comment]
Hi juan131 ,

The ```replicaCount``` only works for the kafka nodes and not the zookeper nodes.
BTW, if I need to scale the Kafka Nodes separately ?

**Comment by juan131** [comment]
Hi @Tenseiga 

Could you try by running the command below? Please note that you need to substitute X and Y with the number of nodes you desire for Kafka and Zookeeper, respectively. 

```
helm install bitnami/kafka --name my-release --set replicaCount=X,zookeeper.replicaCount=Y
```

Once deployed, you can modify the number of replicas by running:

```
kubectl scale statefulset my-release-kafka --replicas X
kubectl scale statefulset my-release-zookeeper --replicas Y
```
