### ISSUE TITLE
[bitnami/kube-prometheus] kube-state-metrics exported labels

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#7690]
**Which chart**:
kube-prometheus 6.1.10

**Describe the bug**
Relates to: https://github.com/bitnami/charts/issues/7534

When deploying this chart, not having the following set:

```yaml
kube-state-metrics:
  serviceMonitor:
    # without this, container=kube-state-metrics instead of container=app for example
    honorLabels: true
```

results in metrics being pulled with `exported_` in the name. This is confusing for the kube-state-metrics information since ideally the `container` name and `namespace` would be that of your actual application rather than that of `kube-state-metrics`. Setting `kube-state-metrics.serviceMonitor.honorLabels: true` fixes this issue entirely

**To Reproduce**

1. Deploy `kube-prometheus` chart with the default values 
2. Navigate to prometheus and run the following query (replace release-name with the release name you deployed with)

```
increase(kube_pod_container_status_restarts_total{job="RELEASE-NAME-kube-state-metrics"}[10m]) > 0 and kube_pod_container_status_waiting{job="RELEASE-NAME-kube-state-metrics"} == 1
```

3. Scroll down to a result and observe container=`kube-state-metrics` and `exported_container=YOUR_APP`

**Expected behavior**
I'd expect the default values to give me sane results and make prometheus queries re-usable from other sources

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by randradas** [comment]
Hello @jack1902 thank you for your issue, it is really appreciate. As you may consider it is difficult to set a default value that satisfy every use case so we need to make a decision here.

From the [Prometheus Documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) you can see that the default value is 'false':
`[ honor_labels: <boolean> | default = false ]`

For us it makes sense to adopt an approach that 'by default' does not modify the upstream defaults, it is useful to manage expectations properly and avoid weird configurations that are not expected in a 'default' scenario by users that are used to Prometheus' default configs.

**Comment by jack1902** [comment]
I get that the honor_labels being false by default for particular use-cases but this case it doesn't fit. By having it set to `false` it means that resulting alerts always look to be coming from the kube-state-metrics pod and you have to then look at the `exported_container` which is confusing when seeing alerts.

If the honor_labels was set to `true` by default then it would ensure that the labels coming from the actual pod that kube-state-metrics is pulling from are supplied to prometheus, it results in useable alerts without having to configure things to look at the `exported_*` fields. As can be seen from the related issue I'm not the first to run into this (if it wasn't for the related issue i would have been scratching my head for a little while until i realised it was due to that label field)

**Comment by randradas** [comment]
okey In understand, It was not clear to me and it looks like it completely makes sense in this deployment architecture. would you like to submit a PR for this? otherwise I can do it myself, just let me know :).
