### ISSUE TITLE
Helm chart for External-dns 0.10.0

### ISSUE THREAD

**Issue by admoca60** [bitnami/charts#7693]
**Which chart**:
external-dns chart. Currently taking the 0.9.0 core version.

**Is your feature request related to a problem? Please describe.**
Due kubernetes 1.22, external-dns 0.9.0 is not working. Now, fm 0.10.0 is supposed to be fixed.

**Describe the solution you'd like**
Release the chart version with external-dns 0.10.0 image

**Comment by juan131** [comment]
Hi @admoca60 

Thanks for reporting it! 

Our team is actually working on the new release but it seems they're solving some testing issues in our internal pipeline that appeared with this new version, we'll keep you updated about our progress and let you know as soon as it's released.

**Comment by juan131** [comment]
Hi @admoca60 

Please check the comment below bumping the image and chart version:

- https://github.com/bitnami/charts/commit/a07a97b9b58ce53c4d6b28e818625ea1864eb740

You should be able to use `0.10.0` image using the chart `5.4.9` version

> Note: please expect some delay in the release of this version of the chart in the Bitnami charts repository due to some ongoing issues in our internal pipeline

**Comment by admoca60** [comment]
> Hi @admoca60
> 
> Please check the comment below bumping the image and chart version:
> 
> * [a07a97b](https://github.com/bitnami/charts/commit/a07a97b9b58ce53c4d6b28e818625ea1864eb740)
> 
> You should be able to use `0.10.0` image using the chart `5.4.9` version
> 
> > Note: please expect some delay in the release of this version of the chart in the Bitnami charts repository due to some ongoing issues in our internal pipeline

Thank you!! I will wait a few days!

**Comment by juan131** [comment]
@admoca60 the new chart version is now available:

```console
$ helm repo update bitnami && helm search repo bitnami/external-dns
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/external-dns	5.4.9        	0.10.0     	ExternalDNS is a Kubernetes addon that configur...
```
