### ISSUE TITLE
[bitnami/elasticsearch] Add support for priorityClassName

### ISSUE THREAD

**Issue by slamdev** [bitnami/charts#7702]
**Which chart**:
elasticsearch

**Is your feature request related to a problem? Please describe.**
It is not possible to define priorityClassName for master and data statefulsets

**Comment by yilmi** [comment]
Hi @slamdev, thanks for this suggestion, just to set expectations, this may take some time before someone can start working on it given. If you want to submit a pull request to add this property to our chart that may be faster.

Would you like to submit a PR for this?

**Comment by yilmi** [comment]
Hi @slamdev, I opened an internal tracker for this request 👍
