### ISSUE TITLE
[bitnami/postgresql]: password authentication failed for user "postgres"; User "postgres" has no password assigned.

### ISSUE THREAD

**Issue by ahgraber** [bitnami/charts#7705]
**Chart**: bitnami/postgresql

**Bug Report**
I am setting `pg_hba.conf` and `postgresql.conf` using `configurationConfigMap`.  
Regardless of whether I set `postgres` user password using `global.postgresql.postgresqlPassword`, `global.postgresql.existingSecret`, `postgresqlPassword`, or `existingSecret`, it appears that the manual pg_hba.conf is applied prior to the hooks that update the `postgres` user password, and because my `pg_hba.conf` forces `md5` instead of `trust`, the password update hook fails on server initialization.

**To Reproduce**

1. Apply the following `pg_hba.conf` using `configurationConfigMap`

```yaml
apiVersion: v1
metadata:
  annotations:
    meta.helm.sh/release-name: postgresql
    meta.helm.sh/release-namespace: postgresql
  name: configmap-postgresql-conf
  namespace: postgresql
kind: ConfigMap
data:
  pg_hba.conf: |
      host     all             all         0.0.0.0/0          md5
      host     all             all         ::/0               md5
      local    all             all                            md5
      host     all             all         127.0.0.1/32       md5
      host     all             all         ::1/128            md5
      host     all             all         0.0.0.0/0          md5

      host     replication     postgres    0.0.0.0/0          md5
      host     replication     postgres    ::/0               md5
      local    replication     postgres                       md5
      host     replication     postgres    127.0.0.1/32       md5
      host     replication     postgres    ::1/128            md5
      host     replication     postgres    0.0.0.0/0          md5

```

2. Attempt to set `postgres` user password using any method
3. See error:

```
[38;5;6mpostgresql [38;5;5m08:20:04.53 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m08:20:04.54 [0m[38;5;5mDEBUG[0m ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
[38;5;6mpostgresql [38;5;5m08:20:04.55 [0m[38;5;2mINFO [0m ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
[38;5;6mpostgresql [38;5;5m08:20:04.55 [0m[38;5;2mINFO [0m ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
[38;5;6mpostgresql [38;5;5m08:20:04.55 [0m[38;5;5mDEBUG[0m ==> Ensuring expected directories/files exist...
[38;5;6mpostgresql [38;5;5m08:20:04.59 [0m[38;5;2mINFO [0m ==> Deploying PostgreSQL with persisted data...
[38;5;6mpostgresql [38;5;5m08:20:04.60 [0m[38;5;2mINFO [0m ==> Loading custom scripts...
[38;5;6mpostgresql [38;5;5m08:20:04.61 [0m[38;5;2mINFO [0m ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
[38;5;6mpostgresql [38;5;5m08:20:04.61 [0m[38;5;2mINFO [0m ==> Starting PostgreSQL in background...
waiting for server to start....2021-10-05 12:20:04.659 GMT [56] LOG: pgaudit extension initialized
2021-10-05 12:20:04.660 GMT [56] LOG: listening on IPv4 address "0.0.0.0", port 5432
2021-10-05 12:20:04.660 GMT [56] LOG: listening on IPv6 address "::", port 5432
2021-10-05 12:20:04.663 GMT [56] LOG: listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-10-05 12:20:04.674 GMT [57] LOG: database system was shut down at 2021-10-05 12:19:22 GMT
2021-10-05 12:20:04.678 GMT [56] LOG: database system is ready to accept connections
done
server started
2021-10-05 12:20:04.755 GMT [66] FATAL: password authentication failed for user "postgres"
2021-10-05 12:20:04.755 GMT [66] DETAIL: User "postgres" has no password assigned.
Connection matched pg_hba.conf line 3: "local all all md5"
2021-10-05 12:20:04.755 GMT [66] LOG: could not send data to client: Broken pipe
```

**Expected behavior**
I would expect that the password update happens prior to setting a custom pg_hba.conf, or that a workaround is provided in the documentation that does not require manual intervention at runtime (i.e., should be able to use gitOps to start the postgres statefulset).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11+k3s1", GitCommit:"b247e74e36248fc047e5253fe7f94c6db07a5e1e", GitTreeState:"clean", BuildDate:"2021-09-20T16:15:27Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ahgraber** [comment]
seems like #7440 may be related?

**Comment by marcosbc** [comment]
Hi @ahgraber, unfortunately this issue is caused by a limitation of the current design. When mounting a configuration file, our logic is programmed not to change anything. Therefore, if you mount the configuration file, PostgreSQL will start with the specified security policy.

Have you tried to apply the configmap to a running deployment? That may help to workaround this issue.

Note that there can be made improvements in the logic (i.e. by starting with a temporary conf file), so feel free to contribute any change for improving the current container, we'd be glad to help getting them merged.

**Comment by ahgraber** [comment]
Thanks for the reply & confirming that I'm not misconfiguring things 😅  

I've been trying to avoid applying a subsequent configmap or manually running a job to update the deployment (though I ultimately may have to) because the cluster is run with gitops that are supposed to manage state, therefore it's counter to the management paradigm and policy to have to manually intervene.

Sadly, I do not have the skill to grok the full init logic in the container or helm chart, nor do I really understand the postgres-side implications of altering the init workflow.  It simply struck me that if a password was requested/set (especially for the `postgres` user), it should be applied as part of the init process (and therefore before the application of configuration files like `pg_hba.conf` that would then prevent the connection to the server and therefore the update of the password).  I guess this leaves the issue as a #wontfix?  Or should I create an issue on the bitnami postgres docker repo?
