### ISSUE TITLE
[bitnami/rabbitmq] enable amqp and mqtt port only for cluster internal usage

### ISSUE THREAD

**Issue by xpicio** [bitnami/charts#7712]
**Which chart**:
bitnami/rabbitmq 8.22.4

**Is your feature request related to a problem? Please describe.**
I would not open the amqp and mqtt (i'm using it as extraPorts) port on the external LoadBalancer, for security reason i would only use these ports from the pod deployed in the cluster.

**Describe the solution you'd like**
I would configure which ports are exposed through the external LoadBalancer and which ports are exposed to the pod as ClusterIP

**Comment by alemorcuq** [comment]
Hi, @xpicio. Would setting the service to Cluster IP and then creating an additional service with `extraDeploy` work for your use case?

**Comment by juan131** [comment]
@xpicio please keep us updated and let us know if the workaround suggested by @alemorcuq helped you.

**Comment by alvneiayu** [comment]
hi @xpicio

Happy to hear that the solution proposed by @alemorcuq works for you. If you want to send us a contribution, we are open to receive PRs. I will be really happy to review it. Please let me know.

Thanks a lot

álvaro
