### ISSUE TITLE
Bitnami keyloak - unable to assign private IP address to Ingress (Azure Application gateway)

### ISSUE THREAD

**Issue by Srkvmv** [bitnami/charts#7715]
**Which chart**:
https://charts.bitnami.com/bitnami/bitnami/keycloak

**Describe the bug**
I am trying to expose keycloak over a private IP in Azure application gateway. But the ingress is not getting assigned with the IP address. The application gateway has a private IP configured and it is working fine for other standalone applications.
I am facing this issue only with bitnami chart.

**To Reproduce**
Install keycloak using bitnami chart by providing the below values.

**### values.yaml**
**auth:
  adminPassword: User@123
  adminUser: user
  managementPassword: Manager@123
  managementUser: manager
externalDatabase:
  database: postgres
  host: keycloak-ingress.postgres.database.azure.com
  password: Admin@123
  user: keycloak@keycloak-ingress
postgresql:
  enabled: false
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: ""
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"**

**Expected behavior**
The private IP address should be assigned.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"8dc42052754bfacb111a0426830122dd9cc9cfa0", GitTreeState:"clean", BuildDate:"2021-08-31T00:01:04Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Could you check that the deployed ingress rule object has the expected annotations? `kubectl get ingress -o yaml`. If it has it, I'm not sure what could be different from other applications in this case. Does it happen with other bitnami charts?

**Comment by Srkvmv** [comment]
@javsalgar I haven't tried with other charts. PFB the output of **kubectl get ingress -o yaml**

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    meta.helm.sh/release-name: my-keycloak
    meta.helm.sh/release-namespace: keycloak
  creationTimestamp: "2021-10-06T07:50:26Z"
  generation: 1
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: my-keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-5.1.2
  name: my-keycloak
  namespace: keycloak
  resourceVersion: "76983"
  uid: 8293152f-8799-430c-9873-a74239334389
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-keycloak
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}

**Comment by Srkvmv** [comment]
Hi Javier,

The issue is resolved. The watchNamespace of AGIC controller was referring to some other namespace. 

Thanks for your time and help.
