### ISSUE TITLE
[bitnami/postgresql-ha] - restart/switchover

### ISSUE THREAD

**Issue by itmwiw** [bitnami/charts#7725]
Hello,
This is not really an issue but rather a question.
When performing a restart of my postgres primary, I noticed a small downtime. From what I understand to do the restart you should use the pre-stop.sh script and that's what I did. So my question is, is there automatically a downtime when performing a primary pod restart, or is it something due to a misconfiguration from my side?
Thanks in advance

**Comment by miguelaeh** [comment]
Hi @itmwiw ,
I guess when you perform the restart a new primary needs to be elected, so probably during that time you will not be able to write (since there is no primary) but I am not sure about the read requests, they should not be affected.

**Comment by miguelaeh** [comment]
Hi @jansmets ,
I think you are asking about 2 different topics. One is the recovery after a primary dies, and the other is a split brain.
A split-brain should not be happening at any moment, are you experiencing it? Could you share more details?
About the primary recovery, if you kill the pod, it is normal that the connections to that pod will be lost. After all, if you shut down a server to which you are connected to, you will lose the connection. Maybe I misunderstood the question?
