### ISSUE TITLE
[bitnami/nginx-ingress-controller] using nameOverride results in k8s permissions errors

### ISSUE THREAD

**Issue by d-shi** [bitnami/charts#7737]
**Which chart**:
The name (and version) of the affected chart:
nginx-ingress-controller v7.6.21

**Describe the bug**
When setting `nameOverride` in the helm values, the k8s role for the nginx-ingress-controller does not take it into account, but the code does. I believe the offending line is here: https://github.com/bitnami/charts/blob/bd250cae5c94fd74ce3b491bd1e489535b647922/bitnami/nginx-ingress-controller/templates/role.yaml#L62

The error from the logs looks like this:

```
E1007 17:22:43.055832       1 leaderelection.go:361] Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:kube-system:ingress-nginx-ingress-nginx-internal" cannot update resource "configmaps" in API group "" in the namespace "kube-system"
```

**To Reproduce**

Set `nameOverride` to some none empty string and deploy the chart.

**Expected behavior**
The nginx-ingress-controller should be able to update the lock on the `ingress-controller-leader` configmap.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

(we are also running some very old k8s clusters so that's why kubectl is old)

**Comment by d-shi** [comment]
Actually I'm wrong, it looks like setting `ingressClass` is the issue.

**Comment by d-shi** [comment]
It's actually not clear to me what the correct fix is, and I'm not familiar with how the configmap is created. It seems to be created when the ingress-nginx pod comes up, as it has `create` permission on any configmap. Note that this configmap is also orphaned and left behind in the cluster after deleting this Helm chart. It seems to always get created with the name `ingress-nginx-internal` no matter what the runtime flags are. However, the chart template for the kube role wants to append the `ingressClass` at the end. I don't see how this ever worked, but according to git blame it's been this way for 3 years, and people have successfully used the chart, so it feels like I'm doing something wrong.

**Comment by rafariossaa** [comment]
Hi,
  In that case I am closing the issue.
  Feel free to post a new comment and it will be examined and reopened, or open a new issue if you consider it.
Thanks
