### ISSUE TITLE
Minio gateway S3 with IAM Role 

### ISSUE THREAD

**Issue by Mahesh81** [bitnami/charts#7738]
Hi Team
We were able to configure minio using PVC and application able to store data . We want to configure S3 as an options using IAM Role and to avoid accesskey/secret key

**Configuration details:**
Usecase: I want to deploy minio using helm in EKS with gateway s3 and IAM Role configured instead of accesskey and secretkey

I have created a EKS and deployed minio 7.1.9 using helm.

Configured IAM Role in Node and Masters with AmazonS3fullaccess (Just for testing )

Values.yaml has following configuration ## Authentication configuration for S3. Ignored unless type=s3

```
s3:
accessKey: "" ##didnt provide access and secret key as i want to connect to S3 using IAM Role attached to cluster and nodes
secretKey: ""
serviceEndpoint: https://s3.amazonaws.com
```
```
helm install minio --set accessKey.password=accesskey,secretKey.password=secretkey ./minio-7.1.9.tgz
```
```
kubectl port-forward --namespace default svc/minio 9000:9000
```
**Expected Behavior**
Able to access http://127.0.0.1:9000/minio
Expect to access S3 in my account from minio running in EKS
**Current Behavior**
Im able to connect to node and do aws s3 ls to get list of buckets, no access issue from node

Not able to view the S3 buckets from my account
When i create a bucket, it uses PVC instead of s3

**Comment by schwichti** [comment]
Is there something new to this? I am struggeling with this https://github.com/minio/minio/discussions/14123

**Comment by schwichti** [comment]
@Mahesh81 @juan131 I got it running with version 6.7.7 and 9.3.0 (with app version 2022.1.8-debian-10-r6 but I guess it will also work with the default 2021.12.29). See details in the link above.

**Comment by juan131** [comment]
Hi @schwichti 

Correct me if I'm wrong but all we need to is to add the missing `AWS_ROLE_SESSION_NAME` env. variable that you added using the `extraEnvVars` parameter, am I right? Would you like to contribute with a PR adding support for it?

**Comment by schwichti** [comment]
@juan131 it works as it is. no PR needed. it seems that `AWS_ROLE_SESSION_NAME` is not even necessary. 
All you need to do is create the IAM role and IAM policy and deploy the chart 9.3.0 with these values (I have provided a [bash script](https://github.com/minio/minio/discussions/14123#discussioncomment-2005579) that sets up everything correctly):

```nodeSelector:
    "kubernetes.io/os": linux
auth:
  rootPassword: asdjasjdoiajfoijf
  rootUser: admin
gateway:
  replicaCount: 1
  enabled: true
  type: s3
  auth:
    s3:
      accessKey: "dummy_key"
      secretKey: "dummy_key"
image:
  tag: 2022.1.8-debian-10-r6
serviceAccount:
  name: minio
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::************:role/minio-role"
```
Then I can login into console with username "dummy_key" and password "dummy_key".

**Comment by juan131** [comment]
That's awesome @schwichti !! Thanks so much for providing this solution, I'm pretty sure that'd be very helpful for other users facing the same challenge.
