### ISSUE TITLE
Add a Chart for Pinniped

### ISSUE THREAD

**Issue by vrabbi** [bitnami/charts#7741]
**Which chart**:
Pinniped

**Is your feature request related to a problem? Please describe.**
Pinniped is an awesome tool in the K8s ecosystem for authentication and solves alot of issues for many environments.
Pinniped does not have a helm chart and many users in the community have raised the request to have a chart out there for pinniped.

**Describe the solution you'd like**
Pinniped is gaining traction in the community and would make a great addition to the Bitnami HELM Chart catalog.
pinniped is even used in the Bitnami Kubeapps Chart to support authentication.
Also, if the chart is created, it could even be added as a sub chart to Kubeapps down the road to make the installation process of pinniped based auth for kubeapps that much more streamlined and simple like it is the the other sub charts used in kubeapps today.

**Describe alternatives you've considered**
A community based helm chart. while this is an option, as it is gaining traction and is a really awesome tool, not a difficult chart based on looking at the manifests of pinniped and that it is an OSS tool coming out from VMware as well, it would be a shame to not have a good VMware backed chart for a tool like pinniped.

**Additional context**
One of multiple conversations on this matter in the K8s slack channel for pinniped: https://kubernetes.slack.com/archives/C01BW364RJA/p1633551477164900

**Comment by recena** [comment]
@vrabbi Pinniped was already added to the **Bitnami Application Catalog**.
