### ISSUE TITLE
[Keycloak] Add support for using host's ca certs

### ISSUE THREAD

**Issue by michaeljmarshall** [bitnami/charts#7744]
**Which chart**:
Keycloak 5.1.2.

**Is your feature request related to a problem? Please describe.**
When using TLS, the keycloak helm chart expects a user to supply both a `keystore.jks` and a `truststore.jks`. If the cert is an ACME certificate, the root CA is well known and will already be bundled in the docker image here, `/opt/bitnami/java/lib/security/cacerts`, when using `docker.io/bitnami/keycloak:15.0.2-debian-10-r0`. In order to make it work using the ACME private key for TLS, I had to also supply mount the `cacerts` file in as the `truststore.jks`. I would prefer to be able to skip the step where I bundle a well known ca.

**Describe the solution you'd like**
I would like to be able to easily use ACME certificates. I have not found any documentation on how to do this. From what I can tell, I think the best solution would be to make it possible to rely on the host's `cacerts` file, found here: `/opt/bitnami/java/lib/security/cacerts`.

This solution will work fine in the case of a single pod statefulset, but I don't understand keycloak's HA deployment well enough to know if this solution will work with multiple keycloak pods.

**Describe alternatives you've considered**
The alternative is to format your own `truststore.jks` with the right ca cert and then mount it in to the container. Because the root ca is well known in this case, it'd be great to have a solution that doesn't require me to look up and then format the `truststore.jks`.

**Comment by q-b** [comment]
Is there still interest on this feature? We also rely on an overly complex setup (custom init script to generate the truststore based on the host ca) to validate TLS connections. While I understand this is not high priority atm, the issue is closed. Would it be possible to keep it open for future improvement?

**Comment by Nold360** [comment]
The original keycloak image has a simple init script which generates the Truststore. And you can simply add a cert by using the env `X509_CA_BUNDLE=/path/to/my/ca.crt`. Why is this so complicated here >.< ....

See: https://github.com/keycloak/keycloak-containers/blob/main/server/tools/x509.sh

**Comment by javsalgar** [comment]
I reopened the issue. In case you want to speed up the process, feel free to provide a PR and we will review it.
