### ISSUE TITLE
[bitnami/harbor] Running "helm upgrade" breaks OIDC Provider Authentication / Secret Key

### ISSUE THREAD

**Issue by harrishcris** [bitnami/charts#7749]
**Which chart**:
bitnami/harbor

**Describe the bug**
We have the OCID provider configured to use Cognito and everything works as expected until we run a "helm upgrade" command to make any changes. Once helm upgrade has been run, the OCID provider gets reset/cleared and no longer works. We add back in the OCID provider however any existing user CLI secrets are now changed / corrupted and no longer work until we manually set them.

**To Reproduce**
Deploy Harbor, confgure the OCCID provider and run a helm upgrade

**Expected behavior**
The OCCID provider to stay persistent during a helm upgrade

**Version of Helm and Kubernetes**: v3.7.0 and 1.21

**Comment by aaron-geospock** [comment]
Just to add to this here is an example of the cli secret after an helm upgrade command is run. This has also happened even after a simple kubectl pods delete to recreate a pod. 
Corrupt CLI secret - �q��UwN�

We also see issues where the OIDC Client Secret is deleted / corrupted and we have to log in using the built in admin account. Paste the OIDC Client Secret value back in before we are able to log in via OIDC. I am assuming that the two are connected but it does mean that our customers regularly have to reset their CLI secret which is not a good experience for them.
