### ISSUE TITLE
We need mysql 5.6 version, can we provide a image

### ISSUE THREAD

**Issue by clcc2019** [bitnami/charts#7754]
We need mysql 5.6 version, can we provide a image

**Comment by khunder** [comment]
add these line to extra env vars serction

```
- name: "DB_VENDOR"
    value: "MYSQL"
- name: "DB_ADDR"
  value: "host_addr"
- name: "DB_PORT"
  value: "3306"
- name: "DB_DATABASE"
  value: "keycloak"
- name: "DB_USER"
  value: "kck-user"
- name: "DB_PASSWORD"
  value: "kck-pwd"
- name: JDBC_PARAMS
  value: "useSSL=false" 

```

**Comment by clcc2019** [comment]
> Hello @clcc2019 could you explain your request with detail? during the issue creation you should be able to fill up a template that try to guide you to provide specific information that can be useful for us to help you.

We hope to deploy mysql based on helm, bitnami provides mysql above 5.7, but we need version 5.6
