### ISSUE TITLE
[redis-cluster]Error in ServiceMonitor

### ISSUE THREAD

**Issue by antoineozenne** [bitnami/charts#7764]
**Which chart**:
redis-cluster 7.0.0

**Describe the bug**
`.Values.serviceMonitor.jobLabel` [l.26](https://github.com/bitnami/charts/blob/28d43a871cbae2e1aa2cdcbc35124a2fd06526d6/bitnami/redis-cluster/templates/metrics-prometheus.yaml#L26) and [l.27](https://github.com/bitnami/charts/blob/28d43a871cbae2e1aa2cdcbc35124a2fd06526d6/bitnami/redis-cluster/templates/metrics-prometheus.yaml#L27) should be `.Values.metrics.serviceMonitor.jobLabel`.

**Comment by yilmi** [comment]
Hi @antoineozenne, thanks for report it this issue! The fix should be pretty straightforward, do you feel like contributing and opening a PR for this one?

**Comment by antoineozenne** [comment]
Hi @yilmi, yes, this is exactly that I wanted to do, but I couldn't figure out how to do it (I'm not allowed to push a new branch in this repo, and I'm not surprised about this).

**Comment by antoineozenne** [comment]
Thank you @yilmi, see my PR above.
