### ISSUE TITLE
[bitnami/rabbitmq] RabbitMQ server occasionally returns  "attempt to reuse consumer tag" error

### ISSUE THREAD

**Issue by dmitsh** [bitnami/charts#7768]
**Which chart**:
rabbitmq-8.22.4

**Describe the bug**
I deployed RabbitMQ cluster using azure-marketplace/rabbitmq helm chart in AKS.
I'm running a simple test application with two threads - a publisher and a subscriber - communicating via 3 topics.
When I scale the application up and down, I occasionally see  "attempt to reuse consumer tag" errors in the log of the rabbitmq server and wrong bindings in the management UI.

**To Reproduce**

1. Deploy AKS cluster
2. Deploy RabitMQ server in AKS
3. Deploy a simple pubsub application:
    - a simple executable with two threads (a publisher and a subscriber)
    - the publisher publishes messages to 3 fanout exchanges every 0.5 seconds. Each exchange has 1:1 binding to a queue.
4. Scale the application up and down a few times
5. Monitor the rabbitmq server log; observe "attempt to reuse consumer tag" error
6. Monitor management UI for queues; observe more than one binding in some queues.

**Expected behavior**
The management UI maintains 1:1 bindings

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by dmitsh** [comment]
Hi @miguelaeh, thank you for responding.
The only way I could reproduce this issue is by scaling up the workload.
Regarding 1:1 binding, it should be possible if you create a queue per topic.

**Comment by miguelaeh** [comment]
Hi @dmitsh ,
could you share the full error in from the logs please?
