### ISSUE TITLE
[bitnami/redis] Configuration files are mounted on disk

### ISSUE THREAD

**Issue by catalin-me** [bitnami/charts#7773]
**Which chart**:
Redis - 14.0.0 - Sentinel setup

**Describe the bug**
Some startup configuration files are mounted in an `emptyDir` volume in `/tmp` and pods remain hanging when allocated on nodes with no available disk space.

**To Reproduce**

1. Deploy a Bitnami Redis sentinel cluster with persistence disabled on nodes with no available disk space.
2. Observe how the pods remain hanging as the configuration files cannot be mounted due to the lack of disk space.

**Expected behavior**
Is there a way to overcome this issue and maybe provide the possibility to use persistent volumes for startup configuration files?

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**

**Comment by carrodher** [comment]
Thanks for the PR, the team will review it within a business day and provide feedback. Thanks again!
