### ISSUE TITLE
[bitnami/postgres] svc name truncates to 24

### ISSUE THREAD

**Issue by deyceg** [bitnami/charts#780]
can someone confirm if this is still necessary? 

deploying the chart as a subchart means that svc name gets completely foobarred as it will pick up the release name, tag on `postgres` then truncate to 24 characters.

e.g.
`hhs-feature-devops-64-en` when it was supposed to be `hhs-feature-devops-64-env-postgres`.

The only workaround I have (which is a horrible one) is all my charts have to implement the same truncation.

original issue: https://github.com/kubernetes/kubernetes/pull/25041

**Comment by carrodher** [comment]
It seems at this moment we can use `64` instead of `24`, thanks for pointing it.
Do you want to send us a PR with the changes?

**Comment by deyceg** [comment]
@carrodher I'll do it one evening this week!

**Comment by gtseres** [comment]
Hello! Motivated by Hacktoberfest, I though I could give this a try. You can find the PR [here](https://github.com/bitnami/charts/pull/848).
