### ISSUE TITLE
kube-prometheus prometheus ingress secretName is hardcoded

### ISSUE THREAD

**Issue by mtricolici** [bitnami/charts#7800]
chart: kube-prometheus
file: templates/prometheus/ingress.yaml

secretName: is hardcoded.
problems:
1. We cannot modify/customize this
2. We can't omit this (we have situations when we need an ingress without secret! i.e. default secret (wildcard cert) is used).

workarounds:
- don't define prometheus.ingress.tls
- just define: prometheus.ingress.extraTls

but I guess this is a hack. Right? :)

**Comment by carrodher** [comment]
The current logic enables the `tls` section if `prometheus.ingress.tls` or `prometheus.ingress.extraTls` are set. In the first case, there are some parameters pre-defined (`hosts` and `secretName`). Both are filled with the information provided in the `tls` object:
```yaml
prometheus:
  tls:
    - hosts:
      - thanos.prometheus.local
    secretName: thanos.prometheus.local-tls
```

Using the information from the above object, the template is going to be rendered:
```yaml
   {{- if or .Values.prometheus.ingress.tls .Values.prometheus.ingress.extraTls }}
   tls:
     {{- if .Values.prometheus.ingress.tls }}
     - hosts:
         - {{ .Values.prometheus.ingress.hostname }}
       secretName: {{ printf "%s-tls" .Values.prometheus.ingress.hostname }}
     {{- end }}
     {{- if .Values.prometheus.ingress.extraTls }}
     {{- include "common.tplvalues.render" ( dict "value" .Values.prometheus.ingress.extraTls "context" $ ) | nindent 4 }}
     {{- end }}
   {{- end }}
```

In the case of `extraTls` there are not any predefined parameters so you should be able to set the values you want.

Using a combination of both options it should be possible to customize the `secretName`. If you think this approach is not a good option for your use case, would you like to contribute by creating a PR? We will be happy to review it
