### ISSUE TITLE
[bitnami/jupyterhub] Image pull secrets incorrectly passed to KubeSpawner

### ISSUE THREAD

**Issue by dariogoetz** [bitnami/charts#7809]
**Which chart**:
bitnami/jupyterhub

**Describe the bug**
Image pull secrets for single-user images are not passed properly to the KubeSpawner. The rendered hub config (rendered from `Values.hub.configuration`) contains an extra hierarchy layer "imagePullSecrets" that is not accounted for in the configmap script (`jupyterhub_config.py`):

```yaml
singleuser:
    image:
      pullSecrets:
        imagePullSecrets:
          - name: secret-name
```
This is due to `jupyterhub.imagePullSecrets` helper referencing `common.images.pullSecrets` which inserts the `imagePullSecrets` section.

In the configmap script, the pull secrets are passed to the KubeSpawner using 
```python
    if get_config("singleuser.image.pullSecrets"):
        image_pull_secrets.extend(get_config("singleuser.image.pullSecrets"))
```
which results in a dictionary with a key "imagePullSecrets" at top level. The KubeSpawner, however, expects a list of dictionaries of the form `{"name": "some_value"}` or a list of strings.

I believe this can be fixed by changing the configmap and adding a `.imagePullSecrets` there:
```python
    if get_config("singleuser.image.pullSecrets.imagePullSecrets"):
        image_pull_secrets.extend(get_config("singleuser.image.pullSecrets.imagePullSecrets"))
```
I do not know, if such a change needs to be implemented for the other cases in the configmap's `jupyterhub_config.py` script (`get_config("imagePullSecrets")` and `get_config("imagePullSecret.automaticReferenceInjection")`).

**To Reproduce**
1. Define a pull secret for a single-user image in the values file and a corresponding private image for the single-user image
2. Install the helm chart
3. Try spawning a jupyterhub single-user notebook server
4. Pulling the underlying image should fail (even though "pre-pulling" the image by the image-puller works fine)

**Expected behavior**
The jupyterhub spawner should successfully spawn a single-user notebook server with the specified image.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yilmi** [comment]
@dariogoetz, I'm closing this as we didn't hear back from you. Please open a new issue if you need further help!
