### ISSUE TITLE
[bitnami/mongodb] Time Zone

### ISSUE THREAD

**Issue by fdarif** [bitnami/charts#7811]
**Which chart**:
Mongodb Helm Chart ( mongodb-10.26.3)

**Describe the bug**
Time zone in mongodb container seems to be not the same as host time zone `Time zone: Europe/Paris (CEST, +0200)`
Exemple.
mongodb container's log:
`mongodb 07:47:24.58 INFO  ==> Deploying MongoDB from scratch... `
mongodb container always use UTC0 as TZ instead of local time TZ (Europe/Paris)
```

$ timedatectl
      Local time: Thu 2021-10-14 09:48:29 CEST
  Universal time: Thu 2021-10-14 07:47:24 UTC
        RTC time: Thu 2021-10-14 07:47:24
       Time zone: Europe/Paris (CEST, +0200)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2021-03-28 01:59:59 CET
                  Sun 2021-03-28 03:00:00 CEST
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2021-10-31 02:59:59 CEST
                  Sun 2021-10-31 02:00:00 CET
```

**Comment by fayssaldarif** [comment]
Hello @carrodher

This the date in the container 
`Thu 14 Oct 2021 12:40:58 PM UTC`
So , as you can see above the container is using UTC instead of local TZ (UTC +2) .

I don't khnow if it's possible to make container change the TZ during at the starting  time.
