### ISSUE TITLE
Please introduce stream protocol service endpoints. 

### ISSUE THREAD

**Issue by herrbpl** [bitnami/charts#7814]
**Which chart**:
rabbitmq 8.23.1

**Is your feature request related to a problem? Please describe.**
Cannot use stream protocol now without manually creating service endpoint per stateful pod

**Describe the solution you'd like**
Service endpoints for stream exposed with chatr deployment:
- for each stateful pod, there should be service exposing stream endpoint ports (5551, 5552). 
- name of service should be pod name of stateful pod and label selector like:
  statefulset.kubernetes.io/pod-name: podname, for example rabbitmq-0

**Describe alternatives you've considered**
- Currently deploying those services manually.

**Comment by herrbpl** [comment]
Sure: https://www.rabbitmq.com/stream.html
Rancher docker team was already kind enough to expose stream protocol ports on container images: https://github.com/bitnami/bitnami-docker-rabbitmq/issues/181#event-5462736095

**Comment by rafariossaa** [comment]
Hi,
  Would you like to send a PR adding this ? We will be glad to review and merge it .
