### ISSUE TITLE
 [cassandra] templates/NOTES.txt doesn't reference right values for cql port

### ISSUE THREAD

**Issue by aurelgcmoi** [bitnami/charts#7816]
**Which chart**: cassandra 4.0.1

**Describe the bug**

names of values in values.yaml have been changed from
```yaml
service:
  port: 9042
```
to
```yaml
service:
  ports:
    cql: 9042
```
the values in _templates/NOTES.txt_ references `{{ .Values.service.port }}` they should reference `{{ .Values.service.ports.cql }}`

**To Reproduce**
execute chart :
`helm install my-release bitnami/cassandra`

See error
```
kubectl port-forward --namespace default svc/cassdb-cassandra : &
cqlsh -u cassandra -p $CASSANDRA_PASSWORD 127.0.0.1
```

**Expected behavior**
```
kubectl port-forward --namespace default svc/cassdb-cassandra 9042:9042 &
cqlsh -u cassandra -p $CASSANDRA_PASSWORD 127.0.0.1 9042
```

**Comment by carrodher** [comment]
Thanks for letting us know, I just created the above PR fixing the issue
