### ISSUE TITLE
how to set up postgresql.conf parameters

### ISSUE THREAD

**Issue by vincentchong1** [bitnami/charts#7820]
**Which chart**:
helm version Version:"v3.3.0"
kubectl version Major:"1", Minor:"20", GitVersion:"v1.20.6"

**Is your feature request related to a problem? Please describe.**
a lot of the conf parameters are not changeable through the helm chart values.yaml

**Describe the solution you'd like**
provide a generic way to accept all change request for valid configurable value 

**Describe alternatives you've considered**
none

**Additional context**
```console
$ sudo helm search repo postgresql
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
localrepo/postgresql-ha 7.10.1          11.13.0         Chart for PostgreSQL with HA architecture (usin...

$ helm ls | grep postgresql
postgresql      default         1               2021-10-14 16:04:01.042309568 +0000 UTC deployed        postgresql-ha-7.10.1    11.13.0

$ grep -iE "tag|repository" ~/kube-artifacts/bitnami-helm-charts/postgresql-ha/values.yaml | grep -iv "#"
  repository: bitnami/postgresql-repmgr
  tag: 11.13.0-debian-10-r53
  repository: bitnami/pgpool
  tag: 4.2.5-debian-10-r22
  repository: bitnami/postgres-exporter
  tag: 0.10.0-debian-10-r82
  repository: bitnami/bitnami-shell
  tag: 10-debian-10-r214

$ grep -nE "^postgresql|^pgpool|^ *configuration:|min_wal_size|max_wal_size" ~/kube-artifacts/bitnami-helm-charts/postgresql-ha/values.yaml
110:postgresqlImage:
131:postgresql:
476:  configuration: |-
477:    max_wal_size = '16000'
478:    min_wal_size = '4000'
564:pgpoolImage:
585:pgpool:
889:  configuration: {}

$ kubectl exec postgresql-postgresql-ha-postgresql-0 -- bash -c "PGPASSWORD=<omitted> psql -U postgres -c '\
> select name,setting from pg_settings;'" | grep wal
 max_wal_senders                        | 16
 max_wal_size                           | 400
 min_wal_size                           | 80
 wal_block_size                         | 8192
 wal_buffers                            | 32
 wal_compression                        | off
 wal_consistency_checking               |
 wal_keep_segments                      | 12
 wal_level                              | replica
 wal_log_hints                          | off
 wal_receiver_status_interval           | 10
 wal_receiver_timeout                   | 60000
 wal_retrieve_retry_interval            | 5000
 wal_segment_size                       | 16777216
 wal_sender_timeout                     | 60000
 wal_sync_method                        | fdatasync
 wal_writer_delay                       | 200
 wal_writer_flush_after                 | 128

$ kubectl exec postgresql-postgresql-ha-postgresql-1 -- cat /opt/bitnami/postgresql/conf/postgresql.conf | grep -iE "min_wal_size|max_wal_size"
max_wal_size = '400MB'
#min_wal_size = 80MB
```

**Comment by alvneiayu** [comment]
hi @vincentchong1

I am a little bit lost, sorry. I applied this change in our values.yaml:

```
diff --git a/bitnami/postgresql-ha/values.yaml b/bitnami/postgresql-ha/values.yaml
index 7c7f98a0f..5ef1e3a76 100644
--- a/bitnami/postgresql-ha/values.yaml
+++ b/bitnami/postgresql-ha/values.yaml
@@ -472,7 +472,11 @@ postgresql:
   ##   port = '5432'
   ##   ...
   ##
-  configuration: ""
+  configuration: |-
+    listen_addresses = '*'
+    port = '5432'
+    max_wal_size = '16000MB'
+    min_wal_size = '4000MB'
   ## @param postgresql.pgHbaConfiguration PostgreSQL client authentication configuration
   ## You can use this parameter to specify the content for pg_hba.conf
   ## Otherwise, a repmgr.conf will be generated based on the environment variables
```
and I installed the chart and I can see the configuration in the pod:

```
I have no name!@post-postgresql-ha-postgresql-1:/$ cat ./bitnami/postgresql/conf/postgresql.conf
listen_addresses = '*'
port = '5432'
max_wal_size = '16000MB'
min_wal_size = '4000MB
```

Could you share with me the pod logs, please? Moreover, could you share with me also the values that you are executing and the way that you are installing the chart?

Thanks a lot

Álvaro

**Comment by alvneiayu** [comment]
hi @vincentchong1 

The configuration key inside the values is going to replace the PostgreSQL configuration. Right now, your configuration has only the values max_wal_size and min_wal_size removing the other ones needed to boot up the PostgreSQL pod and it seems that the configuration is not enough to do it well.

I suggest you to boot up our PostgreSQL chart without your custom configuration and take a look the default one that we are using. Copy the values that we are using to use it in the values and replace the max_wal_size and min_wal_size as you want.

Let me know if I can help you with something else.

Thanks a lot

Álvaro

**Comment by BenManifold** [comment]
https://artifacthub.io/packages/helm/reportportal/postgresql?modal=values

The default values for the chart do not show up here, and it's not actually clear at all how to satisfy the above suggestion. We need to be able to tune these configurations without wasting a lot of extra time on finding what the defaults we're overriding are for the chart that's packaged with the chart for this app.

**Comment by BenManifold** [comment]
We can't actually see any default values when we look at the chart in github.
https://github.com/bitnami/charts/blob/postgresql/10.9.4/bitnami/postgresql/values.yaml

There's actually no indication there for HOW to tune max_wal_size, for the operator in a hurry.

**Comment by BenManifold** [comment]
What we actually see there, is an empty map for configurations.
