### ISSUE TITLE
[bitnami/rabbitmq] Deadlock when running rabbitmq >=3.8.18 with the postStart hook enabled

### ISSUE THREAD

**Issue by machine424** [bitnami/charts#7825]
**Which chart**:
rabbitmq 8.22.3

**Describe the bug**

Hello,

With the new `init_with_lock` mechanism https://github.com/rabbitmq/rabbitmq-server/pull/3075/files that was added to rabbitmq >=3.8.18 and enabled for k8s peer discovery, a virgin node should be discoverable (should belong to the headless service's endpoints: https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.18/deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl#L73) so it can acquire the lock to initialize/join the cluster.

 The problem is that the node will never be a part of the endpoints until the postStart finishes because the corresponding Pod will not have a `Status.PodIP` until postStart finishes: https://github.com/kubernetes/kubernetes/issues/85966 and the kube endpoints controller will not add a Pod without a `Status.PodIP` to the endpoint: https://github.com/kubernetes/kubernetes/blob/v1.19.14/pkg/controller/endpoint/endpoints_controller.go#L411.

Of course, to finish/return, postStart needs rabbitmq to be running on the node. Which leads to a deadlock.

**To Reproduce** (tested on kube v1.19.9)
1. Deploy a 2-nodes cluster with the chart rabbitmq v8.22.3 (make sure you run rabbitmq >=3.8.18) with `clustering.rebalance=true`
2. the first Pod should hang on ContainerCreating (this is because postStart in hanging), if you have access to its logs you'll see something like:
```
Failed to lock with peer discovery backend rabbit_peer_discovery_k8s: "Local node rabbit@xxx.xxx-headless.xxx.svc.cluster.local is not part of discovered nodes []
```
([] -> it is not discoverable)
3. the second Pod will have the same problem, at the end (lock timeout) we will have two clusters (don't know if this is the desired behaviour of the new `init_with_lock` (I'd rather refuse creating the second node))

**Expected behavior**
The postStart should not depend on rabbitmq being up (run the rebalance after rabbitmq being up, maybe put in the entrypoint)

**Version of Helm and Kubernetes**:
kube v1.19.9

**Comment by yilmi** [comment]
Hi @machine424,

Thanks for reporting this issue, I'm opening an internal tracker such that one of us can pick this work item later.

In the meantime, feel free to open a pull request if you know which changes could fix this problem.

Thanks
Yass

**Comment by carrodher** [comment]
Hi,

Just a note to let you know that we released a new revision that gets rid of the postStart hook.
