### ISSUE TITLE
[bitnami/grafana] Admin credentials not working

### ISSUE THREAD

**Issue by mathias-ewald** [bitnami/charts#7850]
**Which chart**:
bitnami/grafana 6.3.3

**Describe the bug**
The properties `admin.user` and `admin.existingSecret` are not working. The chart deploys successfully but I cannot login to Grafana. The logs of the grafana pod show

```
t=2021-10-19T06:46:21+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="user not found" remote_addr=10.0.20.145
```

**To Reproduce**

1. Get a K8s cluster
2. Deploy the bitnami/grafana helm chart
3. Try to log in with admin / hs4jk2t

**values.yaml**
```
global:
  storageClass: nfs-client
admin:
  user: admin
  existingSecret: grafana-credentials
  existingSecretPasswordKey: password
ingress:
  enabled: true
  hostname: grafana.app.mewald.io
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    ingress.kubernetes.io/force-ssl-redirect: "false"
  tls: true
  ingressClassName: contour
```
```
$ kubectl -n prometheus get secret grafana-credentials -o yaml
apiVersion: v1
data:
  password: aHM0amsydAo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"aHM0amsydAo="},"kind":"Secret","metadata":{"annotations":{},"name":"grafana-credentials","namespace":"prometheus"},"type":"Opaque"}
  creationTimestamp: "2021-10-19T06:32:23Z"
  name: grafana-credentials
  namespace: prometheus
  resourceVersion: "528145"
  uid: 1ac71188-6ebd-480e-9d7e-bf06ff41dd72
type: Opaque
```

```
$ echo "aHM0amsydAo=" | base64 -d
hs4jk2t
```

**Expected behavior**
The username "admin" with the password "hs4jk2t" should work for login

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am deploying via the helm operator of FluxCD, but that shouldn't make a difference.

**Comment by rafariossaa** [comment]
Hi,
  Feel free to add a comment to reopen the issue or to open a new issue.

**Comment by mathias-ewald** [comment]
I found the problem. Execing into the container, I looked at the environment variables:

```
$ kubectl exec -it grafana-78f6474667-h94cn -- bash
$ env
... 
BITNAMI_APP_NAME=grafana
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
GF_SECURITY_ADMIN_PASSWORD=hs4jk2t

GF_SECURITY_ADMIN_USER=admin
...
```

Apparently, there was a new line at the end of the password. I must have done 

`echo "hs4jk2t" | base64`

instead of 

`echo -n "hs4jk2t" | base64`

generating the password.

Big face palm ...

**Comment by rafariossaa** [comment]
Hi,
  I am glad you were able to find the issue. This is one of the difficult ones to discover. :clap:

**Comment by nofacer** [comment]
<img width="369" alt="image" src="https://github.com/bitnami/charts/assets/8757916/06cbe4f6-3aaf-48ca-a059-9ef38e3438e0">
<img width="644" alt="image" src="https://github.com/bitnami/charts/assets/8757916/0a3d4925-f406-4efc-ac10-c0b4dcdd5ee2">
meet same issue but without a breaking line
