### ISSUE TITLE
Minio gateway fails with AccessDenied  to S3 issue with EKS cluster while reading parquet file

### ISSUE THREAD

**Issue by nareshurs** [bitnami/charts#7859]
**Which chart**:
The name (and version) of the affected chart : Bitnami minio 8.1.4

**Describe the bug**
Using spark with MinioGateway. Trying to read a parquet file and . Works fine in local docker-desktop cluster but it fails on EKS with error
```
getFileStatus on s3a://mybucket/myfolder/testfile.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 16AF7645EF5E52AD; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden
```

**To Reproduce**

1. Using Bitnami minio helmchart
2. 
```yaml
minio:
  gateway:
    enabled: true
    type: s3
    auth:
      s3:
        accessKey: minio
        secretKey: minio
        serviceEndpoint: http://s3.amazonaws.com
```
3. Created spark session with params
```
    sparkConf.set("fs.s3a.endpoint", "minio-k8s-service':9000");
    sparkConf.set("fs.s3a.connection.ssl.enabled", "false");
    sparkConf.set("fs.s3a.signing-algorithm", "S3SignerType");
    sparkConf.set("s.s3a.connection.timeout", "100000");
    sparkConf.set("spark.master", "k8sSchedulerURL");
    sparkConf.set("spark.deploy.mode", "cluster");
    sparkConf.set("fs.s3a.committer.staging.conflict-mode", "replace");
```
4. Reading parquet file as below.
```
  sparkSession().read().load("s3a://mybuecket/myfolder/testFile.parquet")
```
5. Run on EKS cluster. (Works fine in a local docker-desktop cluster)
6. Even after launching with correct credentials results in  Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 1223XYZ2223; S3 Extended Request ID: null), S3 Extended Request ID: null

**Expected behavior**
It should read a parquet file

**Version of Helm and Kubernetes**:8.1.4

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**
I have spent days of time. I tried everything like using correct spark params and correct version of hadoop/aws jar files and versions. Is there anything we still need to do to make it work on the EKS cluster?

**Comment by javsalgar** [comment]
Hi,

I'm not sure if I understood correctly, could you share the docker-compose file you used for docker-desktop?

**Comment by fabi-alstom** [comment]
Sorry to comment on a closed issue, but I'm getting the same error.  I have a spark app running on K8s. It reads from a minio server and writes to another minio server.

I was able to connect (list the files) by using the signing-algorithm S3SignerType (apparently my destination minio is using the the S3v2 instead S3v4, and I cannot change it, it's a company-wide minio server).
However, I cannot see the contents for the files (I have a writestream to console). Also, It just writes parquet ouput files instead of jsons. However, the weird thing is that I'm able to see it processes 2 files, but then in the console nothing gets printed. 

@nareshurs, were you able to read files?
