### ISSUE TITLE
Add bitnami container images for Pixie

### ISSUE THREAD

**Issue by aimichelle** [bitnami/charts#7860]
Hello! I'm part of the Pixie team (https://github.com/pixie-io/pixie).
We were hoping to have Pixie added as a bitnami chart, and saw that the first step was to use Bitnami-based container images.

What is the process for getting those set up? 

Thank you!

**Comment by pablogalegoc** [comment]
I'l put the "on-hold" label to prevent the bot from closing this issue.
By the way, on a personal note, I've seen the _Debugging in Prod Without (Lots Of) Pain_ talk at DevX Day and it looks awesome so 🤞
