### ISSUE TITLE
Resize /storage in Harbor Chart

### ISSUE THREAD

**Issue by bab5470** [bitnami/charts#7873]
How can I resize an existing ext4 volume 5GB in the bitnami harbor chart? I resized the PVC and I see a new larger PV now (30GB):

```
lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda           8:0    0   40G  0 disk
|-sda1        8:1    0    1G  0 part
`-sda2        8:2    0   39G  0 part
  |-cl-root 253:0    0   35G  0 lvm   /var/lib/registry
  `-cl-swap 253:1    0    4G  0 lvm
sdb           8:16   0   30G  0 disk
`-mpatht    253:2    0   30G  0 mpath /storage
sdc           8:32   0   30G  0 disk
`-mpatht    253:2    0   30G  0 mpath /storage
sdd           8:48   0   30G  0 disk
`-mpatht    253:2    0   30G  0 mpath /storage
sde           8:64   0   30G  0 disk
`-mpatht    253:2    0   30G  0 mpath /storage
 ```
But looking at the filesystem I still see the smaller size:

```
df -h
Filesystem           Size  Used Avail Use% Mounted on
overlay               36G   16G   20G  46% /
tmpfs                 64M     0   64M   0% /dev
tmpfs                3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/mapper/mpatht   4.9G  223M  4.4G   5% /storage
```

Normally I believe I'd have to use resize2fs but it doesn't seem like that's installed in the bitnami container/pod. I tried to install it with apt but it tells me i'm not root. So I tried sudo su to switch to root but then I'm prompted for a password for the root account which I don't know. 

I assume I could somehow unmount the volume, mount it to another pod which has resize2fs installed then unmount and reattach it but besides being a lot of work that would be disruptive to harbor. Is there some easier way to do this?

Thanks,
Brad

**Comment by pablogalegoc** [comment]
Hi @bab5470!

Take a look at [Resizing a volume containing a file system](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-a-volume-containing-a-file-system) and [Resizing an in-use PersistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-an-in-use-persistentvolumeclaim). I think it has to do more with Kubernetes than with the chart itself.
