### ISSUE TITLE
Metric tls is impossible ? 

### ISSUE THREAD

**Issue by laurent6** [bitnami/charts#7882]
**Which chart**:
Elesticsearch 17.0.3

**Describe the bug**
We-ve got problem with metric which  use http insteadof  https. 
in coordinating pod log we'll see this probblem: 
```[2021-10-21T07:52:56,443][WARN ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [elasticsearch-coordinating-only-0] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=0.0.0.0/0.0.0.0:9200, remoteAddress=/10.233.91.1:54694}```

As we can see in code there aren't option to tls: 
``` args:
            {{- if gt (int .Values.coordinating.replicas) 0 }}
            # Prefer coordinating only nodes to do the initial metrics query
            - --es.uri=http://{{ template "elasticsearch.coordinating.fullname" . }}:{{ .Values.coordinating.service.port }}
            {{- else }}
            # Using master nodes as there are no coordinating only nodes
            - --es.uri=http://{{ include "elasticsearch.master.fullname" . }}:{{ .Values.master.service.port }}
            {{- end }}
            - --es.all
            {{- if .Values.metrics.extraArgs }}
            {{- toYaml .Values.metrics.extraArgs | nindent 12 }}
            {{- end }}```

**To Reproduce**
Steps to reproduce the behavior:

Just activate security 

**Expected behavior**
https must be add

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**
Add any other context about the problem here.

**Comment by miguelaeh** [comment]
Hi @laurent6 ,
Thank you very much for reporting this. Would you like to create a PR supporting it?
