### ISSUE TITLE
MySQL and Elasticsearch Templates Conflict

### ISSUE THREAD

**Issue by rmckayfleming** [bitnami/charts#789]
The MySQL and Elasticsearch templates have conflicting templates. They both define a "master.fullname" template which take a different number of arguments to printf. This is an issue if you're using the charts as subcharts since elasticsearch's template expects 3 arguments to printf while mysql only expects 2. The elasticsearch one seemed to take precedence for the chart I was building yielding invalid names for the MySQL yaml files.

The templates should have namespaces (such as the PostgreSQL templates).

**Comment by rmckayfleming** [comment]
Hi Juan,

To clarify, the Elasticsearch helper template "master.fullname" passes three arguments to printf and the MySQL helper template "master.fullname" passes two. When I tried to do a deployment with them, it failed since the configuration ended up with the following:
```yaml
metadata:
  name: testing-mysql-%!s(<nil>)
```

What I mean by namespacing is exactly what you suggest, "master.fullname" should likely be "mysql.master.fullname" and "es.master.fullname" (which is what the PostgreSQL chart does as it has a "postgresql.master.fullname" helper template).

In the interim, I've added a master.name to my chart's values.yaml that fixes the issue. But this should likely be fixed at the source.

**Comment by juan131** [comment]
Hi @rmckayfleming 

Sorry for the confusion with what "namespace" means... Yes, I see your point and I'm opening some PRs to implement that solution. Thanks so much for opening the issue. You can find the PRs in the links below:

- https://github.com/bitnami/charts/pull/816
- https://github.com/bitnami/charts/pull/817

**Comment by juan131** [comment]
We just update the charts including the changes you suggested! Please feel free to use the new charts and reopen the issue if you continue facing issues with the macros.
