### ISSUE TITLE
Can't connect to mongo in helm-2.0

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/charts#79]
$ kubectl get svc
NAME                      CLUSTER-IP       EXTERNAL-IP      PORT(S)           AGE
enervated-koala-mongodb   10.227.250.19    <none>           27017/TCP         3m

$ kubectl run ouch --tty -i --rm --image bitnami/mongodb --command -- /bin/bash
# mongo 10.227.250.19
MongoDB shell version: 3.2.7
connecting to: 10.227.250.19/test

2016-08-09T22:40:37.598+0000 W NETWORK  [thread1] Failed to connect to 10.227.250.19:27017 after 5000 milliseconds, giving up.
2016-08-09T22:40:37.598+0000 E QUERY    [thread1] Error: couldn't connect to server 10.227.250.19:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:231:14
@(connect):1:6

exception: connect failed

**Comment by sameersbn** [comment]
The `mongo ping` command seems to have been removed since release `3.2` due to which the liveness and readiness probes were failing. Updated the probe commands to fix the issue. Thanks for checking reporting :smile:
