### ISSUE TITLE
[elasticsearch] Documentation needed around using auto-generated TLS certs

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#7900]
Setting `security.tls.autoGenerated` will create the CA cert at a place such as:

/opt/bitnami/elasticsearch/config/certs/..2021_10_22_17_10_20.213831280/ca.crt

What's the suggested way for other applications to actually use this cert? The https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch doc could use some barebones prescriptive info of how to go about this.

Let's say that I want to `curl -u elastic:changeme --cacert ca.crt -fsSL https://host:9200` if my `service/elasticsearch-coordinating-only` is exposed as a `NodePort`. Am I supposed to `kubectl cp` the `ca.crt` from the `pod/elasticsearch-coordinating-only-0` ?

**Comment by sjegancbe** [comment]
@Mauraza Can you please elaborate more on how to specify the existingSecret setting, does that mean we need to specify the path of the cert file in the existingSecret parameter or do we need to explicitly load the certs as Secrets and specify the secret name here?

**Comment by rafariossaa** [comment]
Hi,
  You need to create a secret and specify the name there.

**Comment by sjegancbe** [comment]
@rafariossaa Thank you

**Comment by rafariossaa** [comment]
You are welcome
