### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Skipper ConfigMap missing imagePullSecret property

### ISSUE THREAD

**Issue by fiidim** [bitnami/charts#7902]
**Which chart**:
spring-cloud-dataflow (all versions)

**Is your feature request related to a problem? Please describe.**
The configMap generated for Skipper does not expose spring.cloud.skipper.server.platform.kubernetes.accounts.default.imagePullSecret.  The usage of this parameter is documented in the latest guide [Helm Installation](https://dataflow.spring.io/docs/installation/kubernetes/helm/).  This allows skipper to add the pullSecret to the default account.  Without this line, images from private repositories controlled by a docker-registry pullSecret will not work correctly.

**Describe the solution you'd like**
Perhaps a chart parameter called `skipper.defaultImagePullSecret` would suffice, with supporting code in the template.

**Describe alternatives you've considered**

**Additional context**
Upon successful registration, the skipper logs will show:
`Added 'Kubernetes' platform account 'default' into deployer repository.`

**Comment by CEDDM** [comment]
Hi, interested with this one !
I just submit a PR. Hope that will help
