### ISSUE TITLE
ETCD statefulset failing to scale - error #0: dial tcp: lookup lumpy-tarsier-etcd-0 on 10.96.0.10:53: server misbehaving

### ISSUE THREAD

**Issue by fmrtl73** [bitnami/charts#791]
When trying to scale the statefulset to 2 from 1 the container logs reports:
```
==> The ID of the host is 1
==> Creating data dir...
==> Adding member to existing cluster.
==> Adding new member
client: etcd cluster is unavailable or misconfigured; error #0: dial tcp: lookup lumpy-tarsier-etcd-0 on 10.96.0.10:53: server misbehaving
```

10.96.0.10:53 is my Kube DNS server

When I do an nslookup with lumpy-tarsier-etcd-0 it doesn't resolve but when I do an nslookup with lumpy-tarsier-etcd-0.lumpy-tarsier-etcd-headless.default.svc.cluster.local it works fine.

**Comment by tompizmor** [comment]
hi @fmrtl73,

I was able to reproduce the issue. We will take a look to the chart to see what is happening. 
In the meantime, you can install the chart directly with 3 replicas using this command:

```
helm install bitnami/etcd --statefulset.replicaCount=3
```

**Comment by tompizmor** [comment]
Hi @fmrtl73,

I just merged a PR that fixes the issue. Please let us know if it works for you or not.
Remember to use the latest version of the chart by running `helm repo update`
