### ISSUE TITLE
Add InfluxDB2 and telegraf charts

### ISSUE THREAD

**Issue by abhi1693** [bitnami/charts#7914]

**Comment by brsolomon-deloitte** [comment]
@carrodher confused, are you saying that InfluxDB2 is fully supported? By "creating a new chart" are you referring to telegraph? I see that there is a bitnami/influxdb chart which uses an influxdb 2.x.x container but it appears to be misconfigured for 2.x.x.

**Comment by carrodher** [comment]
Yes, **InfluxDB 2.0** is fully supported, both as [container/docker-compose](https://github.com/bitnami/bitnami-docker-influxdb) and as [Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/influxdb), if you find any problem with this asset please open an issue with the information about the error you're having.

About **Telegraph** as it is not part of the catalog it should be evaluated internally, I created a task for that.

**Comment by jcpunk** [comment]
It appears a bitnami telegraf container is built up at https://github.com/bitnami/containers/tree/main/bitnami/telegraf.  Alas I lack the time to generate a chart from this image.  I'm hopeful others will have the ability to make a chart for this component.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review of Telegraf, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
