### ISSUE TITLE
[thanos] Helm chart version 7.0.1 is broken for the Receive component

### ISSUE THREAD

**Issue by skarj** [bitnami/charts#7924]
**Which chart**:
Thanos 7.0.1

**Describe the bug**
Thanos Receive component is broken:
1. Problem with `updateStrategyType` during the chart update for Thanos receive
Workaround: add  `updateStrategyType: RollingUpdate` to chart values.
2. Thanos receive starts, but with warning: `hashring has changed; server is not ready to receive web requests` and doesn't receive metrics.

**To Reproduce**
Deploy chart version 6.0.28 with 
```
receive.enabled: true
```
Update to 7.0.1

**Expected behavior**
Thanos receive continue working without any problems

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
First problem is probably related to forgotten [change](https://github.com/bitnami/charts/commit/91120ea463e0d7212b737f29458804accb0fe1b4#diff-588e356f5358cc5d1343b4e3735f939b23e0e812c0827a3605d4321eb628b057L15-R21) to the receive statefulset 
Second problem was resolved by rollback to 6.0.28

**Comment by javsalgar** [comment]
Closing it as the PR was merged
