### ISSUE TITLE
sync-repositories can't specify branch and tag

### ISSUE THREAD

**Issue by chwongeric** [bitnami/charts#7932]
**Which chart**:
    helm:
      version: 11.1.3
    image:
      # https://hub.docker.com/r/bitnami/airflow/tags?page=1&ordering=last_updated
      web_tag: 2.2.0-debian-10-r0
      # https://hub.docker.com/r/bitnami/airflow-scheduler/tags?page=1&ordering=last_updated
      scheduler_tag: 2.2.0-debian-10-r0
      # https://hub.docker.com/r/bitnami/airflow-worker/tags?page=1&ordering=last_updated
      worker_tag: 2.2.0-debian-10-r0

**Is your feature request related to a problem? Please describe.**
Need a way to specify tag in addition to branch for `sync-repositories` container.
For example:  following point to git repo works if specifying just branch. 

> git:
>   dags:
>     enabled: true
>     repositories:
>       - name: workflow
>         repository: https://user:passwd@bitbucket.org/developers/workflow.git
>         branch: develop
>         path: src/dags
> 

However, if I specify branch and tag name like `branch: develop/nightly-2.11.74` or `branch: develop nightly-2.11.74` , the `sync-repositories` container will output following error complaining unable to pull from branch

> fatal: not a git repository (or any parent up to mount point /)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> 

How do I specify git branch + tag here for `sync-repositories` container ?

**Describe the solution you'd like**
Wish there is a way for value.yaml config for `sync-repositories` container to pull code specifying branch and tag of this branch

**Describe alternatives you've considered**
Trying to exhaust all alternatives and use branch and tag name like `branch: develop/nightly-2.11.74` or `branch: develop nightly-2.11.74`  but no luck.

**Additional context**

**Comment by chwongeric** [comment]
Hi @miguelaeh ,

Thanks a lot for your reply and confirmation.  I think this is already enhancement request.  However, as for PR I am not familiar with airflow code base so perhaps need you or other community to support it.   thank you!

**Comment by miguelaeh** [comment]
Hi @chwongeric ,
Let’s keep this issue open so other users that might be interested in this feature have the opportunity to contribute a PR to address it.
