### ISSUE TITLE
new chart: keydb

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#7945]
**Which chart**:
Did not yet exist

**Is your feature request related to a problem? Please describe.**
I like to use the keydb redis drop in, which is a fully ha active redis without sentinel requirements

https://artifacthub.io/packages/helm/enapter/keydb

**Describe the solution you'd like**
Please add a keydb chart. 

**Describe alternatives you've considered**
Currently using the chart linked above

**Additional context**
no

**Comment by AlexisDucastel** [comment]
Hi ! I just wanted to upvote this request ! 
KeyDB is now totally Opensource after being bought by Snapchat ([source](https://docs.keydb.dev/news/2022/05/12/keydb-joins-snap/)). It would really be awesome to have a bitnami chart as your charts are very high quality maintained charts.


Thanks in advance !

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Comment by viceice** [comment]
can we provide a community PR to get it in?

**Comment by carrodher** [comment]
The main blocker is the container images more than the Helm chart templates. Those container images need to be integrated into our internal test & release pipeline and it is not something that can be done outside the Bitnami organization.

**Comment by carrodher** [comment]
Finally KeyDB was added to the catalog as container and Helm chart.
