### ISSUE TITLE
Helm upgrade fails if mysql root password is unknown !

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#7953]
**Which chart**:
The latest one! - version doesn't matter here.

**Describe the bug**
I rotated the root password of my MySQL database via hasicorp-vault. So the root password is unknown to me.

**To Reproduce**
1. Run bitnami/mysql chart with root password as "Hello@123" in values.yaml.
2. Rotate root password with the help of vault - ( https://www.vaultproject.io/docs/secrets/databases/mysql-maria )
3. Helm upgrade and restart the MySQL pod.
4. Mysql pod went into CrashLoopBackOff.

**Expected behaviour**
Helm upgrade should not ask for a root password as the root password is the "ROOT-PASSWORD" which is a secret and should not be shared at every helm upgrade.

**Version of Helm and Kubernetes**:
Doesn't matter.

**Comment by rafariossaa** [comment]
Hi,
  This kind of functionality using vaults is not supported. It acts as an external client and the chart deployment doesn't know anything about the new password, and this password is needed in the initialization scripts.
