### ISSUE TITLE
mariadb pod is in crashloop

### ISSUE THREAD

**Issue by ramendra-psingh** [bitnami/charts#7960]
**Which chart**:
bitnami/wordpress , version:12.1.25

**Describe the bug**
maridb pod is in crashloop state when we you used wordpress chart with version:12.1.25.

**To Reproduce**
cmd : helm install testapp3 bitnami/wordpress   --set persistence.size=1Gi --set mariadb.primary.persistence.size=1Gi --set persistence.accessModes={ReadWriteMany} --set volumePermissions.enabled=true 

[~]# kubectl logs testapp3-mariadb-0
mariadb 12:24:31.74 
mariadb 12:24:31.75 Welcome to the Bitnami mariadb container
mariadb 12:24:31.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 12:24:31.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 12:24:31.76 
mariadb 12:24:31.76 INFO  ==> ** Starting MariaDB setup **
mariadb 12:24:31.79 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 12:24:31.79 INFO  ==> Initializing mariadb database
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

**Expected behavior**
mariadb and wordpress pod should be running fine.
It was working 10 days before.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
[ ~]# helm version 
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

```

- Output of `kubectl version`:

```
[~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by alemorcuq** [comment]
I can see there's no init container being run in the MariaDB pod, which I suspect you need as you are getting a permission error. Have you tried setting `mariadb.volumePermissions.enabled=true` too?

**Comment by ramendra-psingh** [comment]
Thanks a lot . Looks like mariadb pod is working for me. I was missing this parameter because ```mariadb.volumePermissions.enabled=true```  is not mentioned in wordpress helm doc.
Can we add this ?

Here is my o/p:

```

helm install testapp1 bitnami/wordpress --set persistence.size=1Gi --set mariadb.primary.persistence.size=1Gi --set persistence.accessModes={ReadWriteMany} --set volumePermissions.enabled=true --set mariadb.volumePermissions.enabled=true  --set image.debug=True

[~]# kubectl get pods | grep -i testapp1
testapp1-mariadb-0                   1/1     Running       0          8m22s
testapp1-wordpress-566f76d54-hl4fj   1/1     Running       0          8m22s
[~]#


```

**Comment by alemorcuq** [comment]
Overriding subchart values from a parent chart is a common practice in Helm, you can read more about it here: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

We can't mention all the values in the table, but we have the most common ones or those that are overridden by default written there.

I'll bring your suggestion to the team to discuss it. Thanks for the feedback!
