### ISSUE TITLE
[apache] Init container fails to clone the git repo again

### ISSUE THREAD

**Issue by cuttingedge1109** [bitnami/charts#7966]
**Which chart**:
Apache

**Describe the bug**
I clone htdocs from Github and use `emptyDir` as the volume type.
It works at the first time but once the pod is restarted, then the initContainer `git-clone-repository` failed with the following error.
```
fatal: destination path '/app' already exists and is not an empty directory.
```
So I can see that the initContainer clones the git repo in `/app` path. But that is already there because that path is emptyDir volume.

**To Reproduce**
Rollout, scale down and up again deployments are not the cases. Also to delete the pod is not the case because those actions will delete the emptyDir. EmptyDir is removed once the pod is removed from the node.

Only when the same pod is restarted, we get the issue. This can be reproduced when memory usage of the pod is over, OOM killed.

**Expected behavior**
It would be good to remove all contents in the `/app` before the clone.
```
        initContainers:
        - command:
          - /bin/bash
          - -ec
          - |
            cd /app
            rm -rf ..?* .[!.]* *
            git clone ****
```

**Version of Helm and Kubernetes**:
Not related to helm or kubectl version.
Thanks.

**Comment by miguelaeh** [comment]
Hi @cuttingedge1109 ,
It is true, I updated the PR, I think it should work now
