### ISSUE TITLE
Add bitnami container images for Dapr

### ISSUE THREAD

**Issue by geffzhang** [bitnami/charts#7969]
**Which chart**:
dapr-system

**Is your feature request related to a problem? Please describe.**
I like to use the dapr chart in bitnami , now chart repo is 
https://github.com/dapr/dapr/tree/master/charts/dapr

**Describe the solution you'd like**
Please add a dapr chart.

**Describe alternatives you've considered**
Currently using the chart linked above

**Additional context**
no

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities, this solution was not considered to be added to the catalog in the short/mid-term.

We apologize for the inconvenience. We will be sure to reconsider it in the future.

Thanks for your suggestion!
