### ISSUE TITLE
argo-cd clusterDomain

### ISSUE THREAD

**Issue by fbacker** [bitnami/charts#7971]
**Which chart**:
chart: bitnami/argo-cd
version: 2.0.9

**Describe the bug**
chart ignores common parameter 'clusterDomain' for redis connection string

**To Reproduce**

1. Create values.yaml 
2. add ```clusterDomain: prod-cluster.local``` to values.yaml
3. Generate output ```helm template argo-cd bitnami/argo-cd -n argocd -f ./values.yaml  > ./manifest.yaml```
3. Scroll down to line 1774
4. key ```REDIS_MASTER_HOST``` is ```argo-cd-redis-master-0.argo-cd-redis-headless.argocd.svc.cluster.local```. 

**Expected behavior**
key REDIS_MASTER_HOST should be ```argo-cd-redis-master-0.argo-cd-redis-headless.argocd.svc.prod-cluster.local```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Have you tried setting `redis.clusterDomain` as well?

**Comment by fbacker** [comment]
Yes. That worked. Didn't see that one in the docs or base yaml 
https://github.com/bitnami/charts/blob/master/bitnami/argo-cd/values.yaml

**Comment by alemorcuq** [comment]
Great! Since the Argo CD chart also installs the Redis chart, all values from the Redis chart can be specified under the `redis` section in Argo CD's values.yaml.

**Comment by fbacker** [comment]
Maybe only me that missed that in the docs.

Suggestion. To the table of values configuration. Add 'redis' as a key with this description and a link to the redis chart.

cheers for awesome charts

**Comment by alemorcuq** [comment]
Overriding subchart values from a parent chart is a common practice in Helm, you can read more about it here: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

We can't mention all the values in the table, but we have the most common ones or those that are overridden by default written there.

I'll bring your suggestion to the team to discuss it. Thanks for the feedback!
