### ISSUE TITLE
argo-cd missing CustomResourceDefinitions

### ISSUE THREAD

**Issue by fbacker** [bitnami/charts#7972]
**Which chart**:
chart: bitnami/argo-cd
version: 2.0.9

**Describe the bug**
When deploying argo-cd on a new kluster the **CustomResourceDefinitions** are missing. 

***argo-cd-app-controller*** logs
```
E1029 10:53:23.702741       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Application: failed to list *v1alpha1.Application: the server could not find the requested resource (get applications.argoproj.io)
E1029 10:53:23.703046       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *v1alpha1.AppProject: failed to list *v1alpha1.AppProject: the server could not find the requested resource (get appprojects.argoproj.io)

```

***argo-cd-server*** logs
```
{"level":"fatal","msg":"the server could not find the requested resource (post appprojects.argoproj.io)","time":"2021-10-29T10:53:04Z"}
```

Looking at the installation manifest from argocd https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml we can see the ```applications.argoproj.io``` and ```appprojects.argoproj.io``` at the top. Guessing these needs to be added with the chart.

**To Reproduce**

1. Create empty values.yaml
2. Generate output helm template argo-cd bitnami/argo-cd -n argocd -f ./values.yaml > ./manifest.yaml
3. manifest.yaml are missing CustomResourceDefinition

**Expected behavior**
The CustomResourceDefinition for ```applications.argoproj.io``` and ```appprojects.argoproj.io``` should be in the manifest

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by migruiz4** [comment]
Hi @fbacker,

Both `applications.argoproj.io` and `appprojects.argoproj.io` CRDs are included in the chart at https://github.com/bitnami/charts/tree/master/bitnami/argo-cd/crds.

Your problem is related to this issue: https://github.com/helm/helm/issues/6930

To include CRDs, you should run `helm template` with the flag `--include-crds`.

**Comment by fbacker** [comment]
Thanks, That worked.
