### ISSUE TITLE
argo-cd invalid api version

### ISSUE THREAD

**Issue by fbacker** [bitnami/charts#7973]
**Which chart**:
chart: bitnami/argo-cd
version: 2.0.9

**Describe the bug**
missing character in ```repository-credentials-secret.yaml``` for api version.

File shows ```piVersion: v1``` when it should be ```apiVersion: v1```

**To Reproduce**

1. Create values.yaml 
2. Generate output ```helm template argo-cd bitnami/argo-cd -n argocd -f ./values.yaml  > ./manifest.yaml```
3. Scroll down to # Source: argo-cd/templates/repo-server/repository-credentials-secret.yaml
4. next line is  ```piVersion: v1```

**Expected behavior**
Should be ```apiVersion: v1```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pablogalegoc** [comment]
Thanks for reporting it @fbacker!
