### ISSUE TITLE
Cannot upgrade jenkins with ClusterIP service type

### ISSUE THREAD

**Issue by alexz75** [bitnami/charts#7987]
bitnami/jenkins chart

**Describe the bug**
During upgrade of jenkins getting the error  
error updating the resource "jenkins": cannot patch "jenkins" with kind Service: Service "jenkins" is invalid: spec.ports[2].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'

**To Reproduce**
Upgrade jenkins with the service.type=ClusterIP

**Expected behavior**
Upgrade should be pass

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-16T02:43:21Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"0cc86139598f54b72130881efa5b77b78acf3c39", GitTreeState:"clean", BuildDate:"2021-10-09T03:57:17Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

According to the source code, the source of the problem could be following (in svc.yaml):
```
 {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
```
nodePort: null - not accepted by the Kubernetes (1.19, AKS)

**Comment by pablogalegoc** [comment]
Hi @alexz75

I've run the following with no issues:
```
$ helm install jenkins bitnami/jenkins --set service.type=NodePort
$ export JENKINS_PASSWORD=$(kubectl get secret --namespace "default" jenkins -o jsonpath="{.data.jenkins-password}" | base64 --decode)
$ helm upgrade jenkins --set service.type=ClusterIP --set jenkinsPassword=$JENKINS_PASSWORD
```

**Comment by alexz75** [comment]
@pablogalegoc ,
Was not able to reproduce the issue on clean environment
Also the didn't see the problem during upgrade to jenkins-8.0.18 from 8.0.17
