### ISSUE TITLE
Rabbitmq Scaling down replicaCount

### ISSUE THREAD

**Issue by michelefa1988** [bitnami/charts#7993]
**Which chart**:
rabbitmq-8.18.1 

**Describe the bug**
I have a rabbitmq cluster with a `replicaCount=3` which works fine. However when I decided to update the chart and set `replicaCount=1`, the cluster did scale down normally, however when I logged into Rabbitmq page, I see an error `NODE NOT RUNNING`. Some queues become available. 

To fix I need to set the back to `replicaCount=3`

**Expected behavior**
I can scale down and up my cluster how I please and I expect the node Rabbitmq cluster to evict nodes which no longer exist and not expect them to be there

**Comment by miguelaeh** [comment]
Hi @michelefa1988 ,
I am not too familiar with RabbitMQ cluster, but does it happen only scaling down to `1` replica? Could it be a cluster quorum problem?
