### ISSUE TITLE
Duplicate records in elasticsearch with bitnami fluentd chart

### ISSUE THREAD

**Issue by msinha251** [bitnami/charts#7997]
**Which chart**:
bitnami/fluentd 4.2.2

**Describe the bug**
I am using EFK stack (helm for elastic & kibana from elastic and fluentd from bitnami). I am seeing duplicate records in kibana and that's why the elastic index is growing very fast. 

**To Reproduce**

1. Deployed elasticsearch and kibana from https://github.com/elastic/helm-charts 
2. Deployed fluentd from https://github.com/bitnami/charts/tree/master/bitnami/fluentd with below config:
Fluentd config:
`configMapFiles:
      fluentd.conf: |
        # Ignore fluentd own events
        <match fluent.**>
          @type null
        </match>
        @include fluentd-inputs.conf
        @include fluentd-output.conf
        {{- if .Values.metrics.enabled }}
        @include metrics.conf
        {{- end }}
      fluentd-inputs.conf: |
        # HTTP input for the liveness and readiness probes
        <source>
          @type http
          port 9880
        </source>
        # Get the logs from the containers running in the node
        <source>
          @type tail
          tag kubernetes.*
          read_from_head true
          path /var/log/containers/*dev*.log
          # exclude Fluentd logs
          exclude_path /var/log/containers/*fluentd*.log
          pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
          <parse>
            @type json
            time_key "time"
            time_type string
            time_format "%Y-%m-%dT%H:%M:%S.%NZ"
            keep_time_key true
          </parse>
        </source>
        # enrich with kubernetes metadata
        <filter kubernetes.**>
          @type kubernetes_metadata
        </filter>
        <match kubernetes.var.log.containers.**fluentd**.log>
          @type null
        </match>
        <match kubernetes.var.log.containers.**kube-system**.log>
          @type null
        </match>
        <match kubernetes.var.log.containers.**efk**.log>
          @type null
        </match>
      fluentd-output.conf: |
        # Throw the healthcheck to the standard output instead of forwarding it
        <match fluentd.healthcheck>
          @type stdout
        </match>
        {{- if .Values.aggregator.enabled }}
        # Forward all ml containing namespaces logs to ml index
        <match **dev**>
          @type elasticsearch
          host "elasticsearch-master.efk-logs.svc.cluster.local"                                               # CHANGE ME WITH K8S NAMESPACE (efk-logs)
          port "9200"
          user "#{ENV['ELASTIC_USERNAME']}"
          password "#{ENV['ELASTIC_PASSWORD']}"
          ssl_verify "true"
          index_name "dev"
          <buffer>
            @type file
            path /opt/bitnami/fluentd/logs/buffers/dev.buffer
            flush_thread_count 2
            flush_interval 5s
          </buffer>
        </match>
        # Forward all ml containing namespaces logs to dev-test index
        <match **dev**>
          @type elasticsearch
          host "#{ENV['ELASTIC_HOST']}"
          port "#{ENV['ELASTIC_PORT']}"
          user "#{ENV['ELASTIC_USERNAME']}"
          password "#{ENV['ELASTIC_PASSWORD']}"
          ssl_verify "true"
          index_name "dev"
        </match>
        {{- end }}
      metrics.conf: |
        # Prometheus Exporter Plugin
        # input plugin that exports metrics
        <source>
          @type prometheus
          port {{ .Values.metrics.service.port }}
        </source>
        # input plugin that collects metrics from MonitorAgent
        <source>
          @type prometheus_monitor
          <labels>
            host #{hostname}
          </labels>
        </source>
        # input plugin that collects metrics for output plugin
        <source>
          @type prometheus_output_monitor
          <labels>
            host #{hostname}
          </labels>
        </source>
        # input plugin that collects metrics for in_tail plugin
        <source>
          @type prometheus_tail_monitor
          <labels>
            host #{hostname}
          </labels>
        </source>`
3. Deploy test application:
`kubectl create namespace dev
kubectl apply -f https://raw.githubusercontent.com/DenisBiondic/DockerLogGenerator/master/deploy.yaml -n dev`

4. If delete the EFK and PVC and redeploy all with above steps, records will be double duplicated.   

**Expected behavior**
Duplicate logs shouldn’t be there.

**Version of Helm and Kubernetes**:
elasticsearch: 7.14.0
kibana: 7.14.0
fluentd: 4.2.2
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

![image](https://user-images.githubusercontent.com/31616939/139747394-8b474814-ae5a-4bb8-b759-21159df48f98.png)

**Comment by javsalgar** [comment]
Hi,

So, if I understand correctly, the issue appears when you redeploy, is that correct? When you deploy just the first time you don't see duplicated entries. Something tells me it is due to the fact that the logs from the previous containers were not deleted from the Kubernetes host system, and therefore you see the logs from both containers. Could that be the reason?

**Comment by msinha251** [comment]
Thanks for quick response. No I don't think of duplicate containers causing this because on redeployment I am only redeploying the EFK stack. Log containers is same. 

Also just to clarify it. I have also check the logs in fluentd containers and I don't see any duplicates there.

**Comment by msinha251** [comment]
Also I have noticed today that the record's are getting copied again and again without redeployment as well. 
If I deploy EFK stack once and leave it then the record's are duplicating itself.
Within 5  min I have seen around 25x duplicate records.

**Comment by javsalgar** [comment]
I would like to reprdoduce the issue. Could you clean the format of the fluentd configuration on the original post, is it different from the default one we provide?
