### ISSUE TITLE
Why not include pagecache in this script as part of the setup? 

### ISSUE THREAD

**Issue by webdz9r** [bitnami/charts#7998]
https://github.com/bitnami/charts/blob/451b208726e4c0350252e40661e537b471b1624d/bitnami/wordpress/templates/postinit-configmap.yaml#L32

**Comment by miguelaeh** [comment]
Hi @webdz9r ,
Could you please add a proper description of the issue, why is that needed, why do you thin w should add it, etc?

**Comment by webdz9r** [comment]
> Hi @webdz9r ,
> Could you please add a proper description of the issue, why is that needed, why do you think we should add it, etc?

Hi Miguel, a big part of caching is page caching and there is no way to enable it via the chart, so adding the option to enable the chart using code like the other caching options would be helpful and just make sense.

**Comment by miguelaeh** [comment]
Would you like to create a PR adding that feature to the chart?
