### ISSUE TITLE
Unable to parse eks logs

### ISSUE THREAD

**Issue by msinha251** [bitnami/charts#8008]
**Which chart**:
bitnami/fluentd 4.2.2

**Describe the bug**
I am unable to parse eks logs. While creating the index pattern, getting "don't contain any time fields." 

Logs are coming from airflow and multiple other applications.
airflow logs looks like this:
`[2021-11-02 08:03:49 +0000] [44] [INFO] Handling signal: ttou`

**To Reproduce**

1. Deployed elasticsearch and kibana from https://github.com/elastic/helm-charts

2. Deployed fluentd from https://github.com/bitnami/charts/tree/master/bitnami/fluentd

**Expected behavior**
index pattern should show the time field.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by marcosbc** [comment]
Hi @msinha251, it seems like you have not configured Fluentd properly. You can find an example here for forwarding logs to Elasticsearch: https://github.com/bitnami/charts/tree/master/bitnami/fluentd#forwarding-the-logs-to-another-service

That said, you seem to be configuring a very complex scenario with Elasticsearch, Kibana, Fluentd and Airflow. I recommend checking in official Elastic forums if you find issues configuring them to communicate with Fluentd.
