### ISSUE TITLE
[bitnami/jasperreports] SMTP settings do not work

### ISSUE THREAD

**Issue by tgeci** [bitnami/charts#8020]
**Which chart**: bitnami/jasperreports

**Describe the bug**
In the helm repo of the jasperreports it is intended to override the SMTP server. However, this does not work. Despite deep analysis of the Helm templates and the corresponding Dockerfile I did not find a way to get the correct values into the `js.quartz.properties`.

**To Reproduce**
Set `smtpHost: custom-smtp.my.domain` in the `values.yaml`. Then look in the config file `/bitnami/tomcat/data/jasperserver/WEB-INF/js.quartz.properties` and see that still `report.scheduler.mail.sender.host=mail.example.com` is set.

**Expected behavior**
The value `report.scheduler.mail.sender.host=custom-smtp.my.domain` in `/bitnami/tomcat/data/jasperserver/WEB-INF/js.quartz.properties`.

**Version of Helm and Kubernetes**:

- Output of `helm version`: 
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:10:45Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
I took a closer look at the [Dockerfile](https://github.com/bitnami/bitnami-docker-jasperreports) and thought it was because of the naming of the variables. But also the attempt to set the SMTP settings via `JASPERREPORTS_SMTP_HOST` and the `extra_envs` parameter in values.yaml failed. Behavior was the same like before.

**Comment by migruiz4** [comment]
Hi @tgeci,

The bitnami/jasperreports image does configure SMTP settings in `js.quartz.properties`, but those settings will only take effect if jasperreports volume hasn't been initialized yet.

You can check the container logic [here](https://github.com/bitnami/bitnami-docker-jasperreports/blob/e504635a2f4121074f16f142c3be8d3825fb2660/7/debian-10/rootfs/opt/bitnami/scripts/libjasperreports.sh#L252-L283).

Here is the output of a quick test in a fresh installed JasperReports:
```console
$ cat /opt/bitnami/tomcat/webapps/jasperserver/WEB-INF/js.quartz.properties
...
report.scheduler.mail.sender.host=custom-smtp.my.domain
report.scheduler.mail.sender.username=user
report.scheduler.mail.sender.password=pass
report.scheduler.mail.sender.from=user
report.scheduler.mail.sender.protocol=
report.scheduler.mail.sender.port=1234
```

**Comment by dharma-rise** [comment]
any solution regarding this case?

**Comment by igstbagusdharmaputra** [comment]
any solution regarding this case?
