### ISSUE TITLE
TLS doesn't work properly. StatefulSet livenessProbe is misconfigured

### ISSUE THREAD

**Issue by diego-leapyear** [bitnami/charts#8026]
Following on the issue mentioned in https://github.com/bitnami/charts/issues/6491
The livenessprobe is misconfigured. 
When using self-signed certificates (not sure about non-self signed), our workaround was to remove `certCAFilename` from the values file in the helm chart, modify the chart, and add an extra environment variable from postgres which is `PGSSLROOTCERT` https://www.postgresql.org/docs/12/libpq-envars.html

```
extraEnv:
  - name: PGSSLROOTCERT
    value: /opt/bitnami/postgresql/certs/ca.crt
```
Once we added this, the pod started without problems.

_Originally posted by @diego-leapyear in https://github.com/bitnami/charts/issues/6491#issuecomment-961510291_

**Comment by marcosbc** [comment]
Thanks for reporting this @diego-leapyear! Would you be up to contributing the fix via a PR? We'd be glad to help with the code review and release of the changes!

**Comment by avinal** [comment]
Hello, I believe this issue is still not resolved. I faced this while trying to configure self-signed certs. I am interested in contributing. A little direction into where is the related code/config exists would be helpful.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
