### ISSUE TITLE
[bitnami/minio] Question: Expanding minio

### ISSUE THREAD

**Issue by sergeyshaykhullin** [bitnami/charts#8028]
**Which chart**: bitnami/minio

**Is your feature request related to a problem? Please describe.**
Does the sts.zones is an alternative of minio-operator server pools? And can be used for expanding existing installation capacity? 

It seems like it is, but i need a confirmation 😅
https://github.com/bitnami/charts/blob/89d9d7df53e89f8657c907a13b9c4fdb144f9512/bitnami/minio/templates/distributed/statefulset.yaml#L132

**Additional context**
https://github.com/minio/operator/blob/b3fe304878dcf42a9f2d82c1c49daa2b1cca5141/helm/minio-operator/values.yaml#L80

https://docs.min.io/minio/baremetal/introduction/minio-overview.html#minio-intro-server-pool

**Comment by miguelaeh** [comment]
Hi @sergeyshaykhullin ,
As stated in the `values.yaml`, the `statefulset.zones` parameter indicates the number of zones.
I am not totally sure what is the question, could you clarify?

**Comment by sergeyshaykhullin** [comment]
@miguelaeh Does the zones is a parameter i need to increase to expand minio cluster capacity?

**Comment by miguelaeh** [comment]
Hi @sergeyshaykhullin ,
I think it depends on what you are trying to achieve, from the minio docs:

> Each zone consists of an independent pool of hosts and their locally-attached storage. MinIO presents all zones in the tenant as a single storage resource for applications to access.

**Comment by sergeyshaykhullin** [comment]
Yes, it is what i need, thanks!
