### ISSUE TITLE
Bitnami/logstash chart runs logstash metrics service as a headless service for clusterIP

### ISSUE THREAD

**Issue by sarvani95** [bitnami/charts#8029]
**Which chart**:
Bitnami/logstash

**Describe the bug**
Currently the Bitnami/logstash chart runs the logstash-metrics service as a headless service by default, due to this Wavefront collector isn't able to collect metrics as clusterIP of the logstash-metrics service is set to None. Is there any specific reason for running logstash-metrics service as headless service by default? 

**To Reproduce**
 Run the Bitnami/logstash helm chart with logstash metrics service type as clusterIP.

**Additional context**

**Comment by alemorcuq** [comment]
Hi, @sarvani95. Looking at the metrics service (https://github.com/bitnami/charts/blob/master/bitnami/logstash/templates/metrics-svc.yaml) it doesn't seem to be a headless service. Are you sure the metrics service is headless? Could you share more info on it?

**Comment by sarvani95** [comment]
Hi @alemorcuq, it's not added in the metrics-sac.yaml, but the attribute "clusterIP: None" is added to the logstash.metrics.service section in the charts.yaml file [](https://github.com/bitnami/charts/blob/master/bitnami/logstash/values.yaml) (line number 673)

**Comment by alemorcuq** [comment]
You are right. I've created a PR to fix it.
