### ISSUE TITLE
[sonarqube] CrashLoopBack & OOMKills

### ISSUE THREAD

**Issue by arthurlogilab** [bitnami/charts#8030]
**Which chart**:

```
$ helm ls 
[snip]
sonarqube   	namespace	2       	2021-11-05 10:54:40.449756594 +0000 UTC	deployed	sonarqube-0.1.0     	9.1.0      
```

**Describe the bug**

Trying to deploy sonarqube via this helm chart it's failing to deploy with Crash LoopBack and sometimes OOMKill as the pod status. 

```
sonarqube 11:20:13.99 
sonarqube 11:20:14.00 Welcome to the Bitnami sonarqube container
sonarqube 11:20:14.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube 11:20:14.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube 11:20:14.00 
sonarqube 11:20:14.01 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube 11:20:14.06 INFO  ==> Creating SonarQube configuration
sonarqube 11:20:14.13 INFO  ==> Trying to connect to the database server
sonarqube 11:20:14.17 INFO  ==> Restoring persisted SonarQube installation
sonarqube 11:20:14.21 INFO  ==> Setting heap size to -Xmx2048m -Xms1024m
sonarqube 11:20:14.24 INFO  ==> ** SonarQube setup finished! **

sonarqube 11:20:14.26 INFO  ==> ** Starting SonarQube **
Running SonarQube...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/bitnami/sonarqube/temp
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:35993]
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/bitnami/sonarqube/elasticsearch]: /opt/bitnami/sonarqube/elasticsearch/bin/elasticsearch
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
jvm 1    | 2021.11.05 11:20:16 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137
jvm 1    | 2021.11.05 11:20:16 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
jvm 1    | 2021.11.05 11:20:16 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
wrapper  | <-- Wrapper Stopped
```

I would expect the `request.memory` to warn if the 2Go are not available for the deployment to work. 

The 2 nodes have an allocatable capacity of 2.8Go. 

Am I missing something ? could the `sysctl` sidecar be failing silently ? 

**To Reproduce**

Install via https://bitnami.com/stack/sonarqube/helm

**Expected behavior**

Deployment in Running state

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by Mauraza** [comment]
Hi @arthurlogilab,

You can change `image.debug` to true to add more information to the logs.
Could you please add the values are you using to deploy sonarqube?

**Comment by arthurlogilab** [comment]
The logs aren't more verbose with this option set to "true".

**Comment by Mauraza** [comment]
Hi @arthurlogilab,

Could you try with this https://github.com/bitnami/charts/tree/master/bitnami/sonarqube#additional-environment-variables?

**Comment by portswigger-tim** [comment]
If you discover this issue, the following guidance might help:

A couple of things to note with Sonarqube and the Sonarqube Helm chart...

1. Sonarqube uses twice the amount of memory than what you have set as minHeapSize and maxHeapSize. The same values are used for Sonarqube and the Elasticsearch instance that runs in the Sonarqube container. This means that you need to set memory resources to at least double those heap settings. 

2. The JMX exporter needs sensible heap and resources configuration. 

As with pretty much all JVM based applications the advice I usually give is:

Set memory requests and limits to the same value and set heap min and max to the same value. Set a reasonably low cpu request and do not set a cpu limit.

Most Java apps are busiest when starting up and allowing them to use as much cpu as available ensures a reasonably quick JVM startup. 

Memory, in Kubernetes is not a resource that can be throttled or compressed like cpu usage can. Kubernetes will decide which pods to kill based on memory over-usage. The more you use above the limits setting, the higher up your container is bumped on the kill list. So, always set memory requests and limits values to the same value.
