### ISSUE TITLE
[bitnami/prometheus] Chart proposal

### ISSUE THREAD

**Issue by day1118** [bitnami/charts#8035]
**Which chart**:
Prometheus (proposed chart)

**Is your feature request related to a problem? Please describe.**
Bitnami charts already supports the Prometheus Operator (kube-prometheus), and have a Bitnami based Prometheus image, but do not have a Prometheus Helm chart. 

The kube-prometheus chart relies on using and operator & CRDs which are not practical for me unfortunately (or necessary).

The prometheus-community/prometheus chart does not use the `tpl` function as much as the bitnami charts, and does not use any `global` values (eg - pull secrets).

**Describe the solution you'd like**
If I work to adapt the existing prometheus-community/prometheus chart to match the bitnami, templates, would it be accepted?

**Describe alternatives you've considered**
1. Raising PRs to the prometheus-community repo: They have many charts that follow the same formats, and the changes may not be backward compatible.
2. Maintaining my own fork: Last resort.

**Additional context**
The use of templating and global variables make the bitnami charts easy to use as subcharts in more complex applications.

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users."

**Comment by day1118** [comment]
Hi @carrodher - thanks for your message.

I am happy to adapt it to meet the Bitnami scaffolding, but want to be sure that it is likely to be accepted before I invest the time. Can you confirm that it will likely be accepted?

Thanks

**Comment by carrodher** [comment]
Thanks, @day1118, I just forwarded this topic to the team in charge of this kind of evaluation. There is some work needed on our side to include a new Helm chart in our internal test & release pipeline, although the container images are already available and the chart PR can be done by community contributors. That is the main blocking issue, so there is an internal team that needs to evaluate the feasibility, interest, or traction this solution can have, detect red flags, etc as well as check the team capacity to afford the required changes.

I'll post here any news I receive from the team in charge at this moment.

**Comment by day1118** [comment]
Makes sense, thanks.
I noticed that you have a `grafana` chart and separate `grafana-operator`, but not the same strategy for `prometheus`.

**Comment by carrodher** [comment]
We have several assets following this approach:
- Contour and Contour Operator
- Grafana, Grafana Operator and Grafana Tempo
- RabbitMQ and RabbitMQ Cluster Operator
(apart from Redis/Redis Cluster; Postgresql/PostgreSQL HA; MongoDB/MongoDB Sharded; MariaDB/MariaDB Galera; etc).

Although in those cases always the simple chart was released first and then after some time the operator or complex solution was requested by the community or any customer. I think it is the first time we are doing the opposite. I personally agree with having the Prometheus chart without an operator, but the decision is based on different topics so let's see what is the answer I get from the dedicated team.

**Comment by day1118** [comment]
Make sense @carrodher. My key motivators are:

- Avoid CRDs (not accepted in some restricted environments as they are not namespaced)
- Greater customisation of the deployment (not all configuration options can be passed to the operator to be added to the pod)
- Faster to deploy (as there is one deployment, not two sequential ones)

Hopefully this helps

**Comment by carrodher** [comment]
Thanks for letting us know, I just shared this info with the appropriate team.

**Comment by carrodher** [comment]
Hi, after checking internally we found interesting the addition of this `bitnami/prometheus` Helm chart to the catalog. As there is already a container image for that solution there is not a lot of extra work on our side (but there is something), so feel free to create the PR, we will be happy to review it and provide feedback, then we will work on the internal changes according to our bandwidth and capacity

**Comment by fmulero** [comment]
Hi

We've just released the new [Prometheus chart](https://github.com/bitnami/charts/tree/main/bitnami/prometheus). Please give it a try and share your thoughts, any comment is welcome.
