### ISSUE TITLE
[wordpress] Support of PriorityClassName

### ISSUE THREAD

**Issue by timbrd** [bitnami/charts#8037]
I couldn't find a way to define [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) for wordpress containers. Please add the setting to the [deployment](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/deployment.yaml) in it's helm chart.

**Comment by miguelaeh** [comment]
Hi @timbrd ,
It should be easy to add, would you like to create a PT adding it?
