### ISSUE TITLE
how can I use kafka helm chart without any auth？

### ISSUE THREAD

**Issue by ZQHcode** [bitnami/charts#8040]
how can I use kafka helm chart without any auth？what should I do to deploy my kafka helm chart ? what configuration needs to be changed?

**Comment by migruiz4** [comment]
Hi @ZQHcode,

Kafka has authentication disabled by default for both client and interbroker communications (values `auth.clientProtocol` and `auth.interBrokerProtocol` set to `plaintext`).

For instructions about how to install the chart or some configuration examples, please refer to our [documentation](https://docs.bitnami.com/kubernetes/infrastructure/kafka/get-started/install/).

**Comment by yod527** [comment]
As this issue is found via google really well, I will type answer here:

Add to `values.yaml` of your chart next config, and this will disable auth for internal clients:
```
listeners:
  client:
    protocol: 'PLAINTEXT'
  controller:
    protocol: 'PLAINTEXT'
```
