### ISSUE TITLE
[contour] Adding --ingress-class-name to the contour depeloyment was a critical breaking change 

### ISSUE THREAD

**Issue by Legion2** [bitnami/charts#8041]
By adding `--ingress-class-name` to the contour depeloyment, contour then uses this value to filter Ingress and HttpProxy objects and thereby ignores object which where included before. Resulting in a potenially disruptive behavior.
 `--ingress-class-name` was added in 176f1891ca4a78b2d1ba8bf146c4a4f67ef59221

https://github.com/bitnami/charts/blob/1829119eceba799634b1a8fdf8ff1d204aeec6ac/bitnami/contour/templates/contour/deployment.yaml#L71

**Comment by Legion2** [comment]
@devholic could you please open a PR to make the `--ingress-class-name` flag of contour optional again?

**Comment by devholic** [comment]
@Legion2 Thanks for figuring out this issue 🙏
I'll send a PR to fix this.

**Comment by pablogalegoc** [comment]
Thanks to both of you folks, someone from the team will review the PR shortly
