### ISSUE TITLE
[bitnami/kibana] Add custom labels to the service in Kibana chart

### ISSUE THREAD

**Issue by abdullah7** [bitnami/charts#8044]
**Which chart**:
bitnami/kibana

**Is your feature request related to a problem? Please describe.**
Adding custom labels to Kibana service is not possible as there is only the common labels are applied while creating the release.

**Describe the solution you'd like**
In Kibana service config values, expose another param named 'labels' and add those label after common labels are added to the service.

**Comment by juan131** [comment]
Thanks @abdullah7 !! I just reviewed the associated PR

**Comment by abdullah7** [comment]
Thanks for the prompt review and feedback!
