### ISSUE TITLE
[bitnami/mariadb-galera] Revert PR #7202 to allow upgrades from chart 5.9.0 to function

### ISSUE THREAD

**Issue by gwvandesteeg** [bitnami/charts#8048]
**Which chart**:
mariadb-galera

**Describe the bug**

The PR causes more issues than it resolves, the previous behaviour was easier to work with (even though it causes problems).

**To Reproduce**

See additional notes in #7198  added after close
See additonal notes in #7202 added after close

In the 5.9.0 version of the chart (as per #7198) the cluster was not reading the configuration file specified due to incorrect path usage.
When upgrading from this version to a newer version which changes the mount path of the volume the pod init scripts can no longer update the generated configuration of the cluster since the now mounted ConfigMap is read only (and shared amongst all replicas, whilst each replica has node specific changes to this file).

**Expected behavior**

Working mariadb-galera cluster than can be upgraded from chart version 5.9.0 to any newer version without causing the cluster to fail.

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
k8s clusters in use:
- `kind v0.11.1 go1.16.4 linux/amd64`
- `AWS EKS 1.20`
- `AWS EKS 1.21`

**Comment by migruiz4** [comment]
Hi @gwvandesteeg, 

Thank you for letting us know. I tested it myself and indeed the PR #7202 is affecting the upgrades.

At the moment, this change should fix the upgrading issue, but the setting `mariadbConfiguration` or `configurationConfigMap` won't take effect except if the workaround proposed in #7198 is used.

A proper solution would require changes in the MariaDB image adding something similar to what you suggested, for example:
```
!include /opt/bitnami/mariadb/conf/bitnami/extended.cnf
```

And replacing the settings `mariadbConfiguration` and `configurationConfigMap` with `extendedConf` and `extendedConfConfigMap` (to be inline with similar value in the `bitnami/postgresql` chart).

We currently don't have the manpower to address this issue and it could take some time until we fix this feature.
If you would like to contribute, feel free to send a PR and we will be very happy to review them.

**Comment by migruiz4** [comment]
Hi @gwvandesteeg, sorry for the late response.

I have created this PR #8271 reverting #7202

**Comment by miguelaeh** [comment]
Hi @gwvandesteeg ,
I tried to reproduce the issue, with the old version, but it seems to be working fine.
Where are you adding the `max_allowed_packet` ?
I edited the `values.yaml` to set `4M` and it is properly taken. Nevertheless, take into account that the configuration parameters are applied in cascade, so, the last one will take precedence if it is duplicated. In the case of `max_allowed_packet` it is already set in the `values.yaml` to `16M`, so if instead of editing that field you add a new one before it, it will never be applied.

You can edit in the `values.yaml` the following section of the MariaDB configuration:

```
## Safety
##
skip_host_cache
skip_name_resolve
max_allowed_packet=16M
```

and after editing the `max_allowed_packet` you can execute your command inside the database to check the new value is properly set.
In my case, as I said, setting `4M`:
```
MariaDB [(none)]> SHOW VARIABLES where Variable_name like 'max_allowed_packet%';
+--------------------+---------+
| Variable_name      | Value   |
+--------------------+---------+
| max_allowed_packet | 4194304 |
+--------------------+---------+
1 row in set (0.001 sec)
```

**Comment by miguelaeh** [comment]
Since the version in master does not have yet the revert mentioned above by @migruiz4 , you need to apply this change to master to check it:
```diff
--- a/bitnami/mariadb-galera/templates/statefulset.yaml
+++ b/bitnami/mariadb-galera/templates/statefulset.yaml
@@ -291,7 +291,7 @@ spec:
             {{- end }}
             {{- if or (.Files.Glob "files/my.cnf") .Values.mariadbConfiguration .Values.configurationConfigMap }}
             - name: mariadb-galera-config
-              mountPath: /opt/bitnami/mariadb/conf/my.cnf
+              mountPath: /bitnami/conf/my.cnf
               subPath: my.cnf
             {{- end }}
             {{- if .Values.tls.enabled }}
diff --git a/bitnami/mariadb-galera/values.yaml b/bitnami/mariadb-galera/values.yaml
index 08c109db6..024d60b5b 100644
--- a/bitnami/mariadb-galera/values.yaml
+++ b/bitnami/mariadb-galera/values.yaml
@@ -336,7 +336,7 @@ mariadbConfiguration: |-
   ##
   skip_host_cache
   skip_name_resolve
-  max_allowed_packet=16M
+  max_allowed_packet=4M
   max_connect_errors=1000000
   sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
   sysdate_is_now=1
```
