### ISSUE TITLE
[bitnami/mariadb-galera] cannot upgrade the image tag

### ISSUE THREAD

**Issue by gwvandesteeg** [bitnami/charts#8049]
**Which chart**:

mariadb-galera, any of the 5.x in the 5.9.0 to 5.14.0 range have been tested

**Describe the bug**

The chart cannot be upgraded nor can the image tag be upgraded (even between minor versions).

**To Reproduce**

1. Create `kind` cluster using a configuration with persistent volume support such as the [config file here](https://gist.github.com/gwvandesteeg/15e5dc4b81eea73774d4534484705145)
2. Using the supplied `values.yml` [file content here](https://gist.github.com/gwvandesteeg/6ac15f7dee5feedb194c07d9d3179715) create an instance of the database using `helm upgrade --install mariadb-galera bitnami/mariadb-galera --version 5.14.0 -f values.yml` (this works for any version in 5.9.x to 5.14.x range of the helm chart, newer versions have not been tested but are expected to have the same problem).
3. Wait for the deployment to start
4. Change the image tag to the commented value in the `values.yml` file and update the deployment using the same command as in step 2.

**Expected behavior**

Graceful updates of the database worker nodes in the replicaset with the new image tag starting with the last node

**Actual behaviour**
The worker node restarts with the new image and fails to reconnect to the galera cluster and goes into a reboot loop.
The logs are also filled with entries like these, which occur anytime you try to connect to the DB as root from that point forward (even to those not currently being replaced). These same root creds are also used by the liveness and readiness probes.
```2021-11-08  3:31:21 12 [Warning] Access denied for user 'root'@'localhost' (using password: YES)```
Attempting to connect to any of the other nodes in the replicaset (which have not yet been updated) with the `mysql` client will also fail as it no longer allows root access to the cluster using the root user name and password as provided by the environment variables.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

- k8s clusters in use:
- `kind v0.11.1 go1.16.4 linux/amd64`

**Additional context**

**Comment by alemorcuq** [comment]
To perform an upgrade you need to specify the passwords again. Since your values has no passwords set, Helm tries to create new credentials for the chart. You should get your passwords from the secrets and pass them when performing the upgrade.

**Comment by gwvandesteeg** [comment]
Of course, the secret is pre-generated and populated in prod using gitops, but testing the upgrade doesn't use gitops.. thanks for the extra eyes to find the mistake. (Don't debug before breakfast and caffeine).
