### ISSUE TITLE
[bitnami/discourse] discourse connect avatar update issue: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by aerott** [bitnami/charts#8051]
**Which chart**:
discourse/5.0.5

**Image version**:
discourse:2.7.8

**Describe the bug**

We've got enabled option ‘discourse connect overrides avatar’ for Discourse Connect. In general everythins works fine except for one thing - the avatar updating.

**Error output**:

Below is error logs from administrative panel which indicate some certificate validation issue. Our certificate is issued by a trusted issuer (all browsers trusts this certificate).

```
Job exception: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

stack:
/opt/bitnami/ruby/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/http.rb:932:in `start'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/http.rb:606:in `start'
/opt/bitnami/discourse/lib/final_destination.rb:444:in `safe_session'
/opt/bitnami/discourse/lib/final_destination.rb:395:in `safe_get'
/opt/bitnami/discourse/lib/final_destination.rb:133:in `get'
/opt/bitnami/discourse/lib/file_helper.rb:56:in `download'
/opt/bitnami/discourse/app/models/user_avatar.rb:98:in `import_url_for_user'
/opt/bitnami/discourse/app/jobs/regular/download_avatar_from_url.rb:18:in `execute'
/opt/bitnami/discourse/app/jobs/base.rb:232:in `block (2 levels) in perform'
rails_multisite-3.0.0/lib/rails_multisite/connection_management.rb:80:in `with_connection'
/opt/bitnami/discourse/app/jobs/base.rb:221:in `block in perform'
/opt/bitnami/discourse/app/jobs/base.rb:217:in `each'
/opt/bitnami/discourse/app/jobs/base.rb:217:in `perform'
sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/opt/bitnami/discourse/lib/sidekiq/pausable.rb:138:in `call'
sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
sidekiq-6.2.1/lib/sidekiq/processor.rb:163:in `block in process'
sidekiq-6.2.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112:in `local'
sidekiq-6.2.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
sidekiq-6.2.1/lib/sidekiq/rails.rb:14:in `block in call'
activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
activesupport-6.1.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
activesupport-6.1.3.2/lib/active_support/reloader.rb:71:in `wrap'
sidekiq-6.2.1/lib/sidekiq/rails.rb:13:in `call'
sidekiq-6.2.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
sidekiq-6.2.1/lib/sidekiq/processor.rb:257:in `stats'
sidekiq-6.2.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13:in `call'
sidekiq-6.2.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
```

**Comment by migruiz4** [comment]
Hi @aerott, 
Could you please add more information about your issue?

Does this issue not happen with SSO (Discourse Connect) enabled but `discourse connect overrides avatar` disabled?
<img width="860" alt="image" src="https://user-images.githubusercontent.com/37381070/140948823-b6429055-9254-4b03-a671-6a9b274ed6eb.png">

Is the communication with your SSO provider using a valid certificate? 
The image includes the `ca-certificates` package, and it could be validated using `k exec -it <pod_name> -c discourse -- bash` and `k exec -it <pod_name> -c sidekiq -- bash`

Maybe enabling some Discourse connect verbose logs help you find more details of what request is triggering the 'verification failed' error.

**Comment by aerott** [comment]
Hi @migruiz4,

We can upload own image and it works, but our aim is usage SSO to image updating.

Actually, we found workaround in our case, but still it's just workaround..

When URL to image updating is 
https://sadyriprod.blob.core.windows.net/images/card-profile-photo-e699306d-1c81-49dc-871d-973686ef838c.png
everytings works well. But following URL is no longer OK..
https://cdn.otoagent.pl/images/card-profile-photo-e699306d-1c81-49dc-871d-973686ef838c.png

W are aware that these two URLs got different SSL certificates, and which means that one of them is not valid? 

ps. How can we enable extended Discourse connect verbose logs? Is there some application flags to enabling or something that?

**Comment by migruiz4** [comment]
Hi @aerott,

The problem is caused by the second URL not having a valid SSL certificate. Discourse forces SSL verification by default, so either you will need to add the untrusted CA certificate of that URL to your container, or disable Discourse SSL verification (not recommended).

Here you can see that it is not a problem with the image or Discourse but with the image source:
```console
$ docker run --rm -it bitnami/minideb bash
$ install_packages curl ca-certificates
...
$ curl -o /tmp/test https://sadyriprod.blob.core.windows.net/images/card-profile-photo-e699306d-1c81-49dc-871d-973686ef838c.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:100 72436  100 72436    0     0  85118      0 --:--:-- --:--:-- --:--:-- 85018
(Succeeds)
$ curl -o /tmp/test https://cdn.otoagent.pl/images/card-profile-photo-e699306d-1c81-49dc-871d-973686ef838c.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
(Fails because of untrusted certificate)
```

**Comment by migruiz4** [comment]
> We are aware that these two URLs got different SSL certificates, and which means that one of them is not valid?

By invalid I mean that the response from `https://cdn.otoagent.pl` are not signed by a Certification Authority (CA) that is included in the trusted certificates for Debian (package `ca-certificates` installed in the image).

As you can see, the curl command also fails because of the same problem with the URL. 

> ps. How can we enable extended Discourse connect verbose logs? Is there some application flags to enabling or something that?

There is an option in the Discourse Connect settings, but it would not be necessary since the URL you shared was already being displayed.

**Comment by aerott** [comment]
@migruiz4 - oh, fair enough. Thank you for your reply :)

Whether we decide to add the untrusted CA certificate or disabling Discourse SSL verification, we need to build custom image based on bitnami/discourse to achieve this?

**Comment by miguelaeh** [comment]
Hi @aerott ,
You could try to mount the new certificates into `/usr/local/share/ca-certificates` and then run as root `update-ca-certificates`.
I guess you could do that providing an extra init container to the chart and sharing a volume between the init container and the discourse container for `/usr/local/share/ca-certificates`.
In that way you could avoid building your custom image.

**Comment by aerott** [comment]
@miguelaeh - It souns good. If it will works like you said, it should be enough for us :) We need to check this out.
