### ISSUE TITLE
[bitnami/postgresql-ha]

### ISSUE THREAD

**Issue by maxinfosoft** [bitnami/charts#8053]
I need the installation of the pgcrypto module for PostgreSQL 12. In the available https://github.com/bitnami/charts/tree/master/Bitnami/postgreSQL-HA#parameters
there is no possibility to specify this option.
How is this module installed correctly for this chart and the script required for its operation /usr/share/postgresql/12/contrib/pgcrypto.sql is launched?

Thanks. I really hope for your fast answer ...

**Comment by maxinfosoft** [comment]
Thanks, alvneiayu!
You are absolutely right! Errors result in my database was incorrect restore the database from a backup dump.
The problem is solved!

**Comment by alvneiayu** [comment]
hi @maxinfosoft 

you're welcome and thanks a lot for your time.

Álvaro
