### ISSUE TITLE
[bitnami/sonarqube] Extra properties for LDAP are not properly set

### ISSUE THREAD

**Issue by Samuel-Schober-USU** [bitnami/charts#8054]
**Which chart**:
sonarqube/0.1.0

**Which image**:
docker.io/bitnami/sonarqube:9.1.0-debian-10-r41

**Describe the bug**
When I add values with commas to the extraProperties, the value is not probably set in the sonar.properties. 
This is critical when configuring the LDAP connection since the bindDn has commas.

**To Reproduce**

1. Create following values.yaml
```yaml
extraProperties:
  - "sonar.security.realm=LDAP"
  - "ldap.url=ldap://127.0.0.1"
  - "ldap.bindDn=\"uid=sonarqube,ou=people,dc=example,dc=com\""
  - "ldap.bindPassword=1234"
  - "ldap.authentication=simple"
  - "ldap.user.baseDn=ou=people,dc=example,dc=com"
  - "ldap.user.request=(&(uid={login})(memberof=cn=sonarqube-users,ou=groups,dc=example,dc=com))"
  - "ldap.user.realNameAttribute=cn"
  - "ldap.user.emailAttribute=mail"
  - "ldap.group.baseDn=ou=groups,dc=example,dc=com"
  - "ldap.group.request=(&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))"
  - "ldap.group.idAttribute=cn"
```
2. Install the chart with the values set`
```sh
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install sonarqube bitnami/sonarqube -f values.yaml
```

**Expected behavior**
The sonar.properties of the pod has the properly set values

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
![image](https://user-images.githubusercontent.com/74423194/140717814-345bbde7-bc03-4f96-9026-ab9a5a42e4e6.png)
![image](https://user-images.githubusercontent.com/74423194/140717808-4a5be487-8667-40c3-9948-34e1c34a4cd6.png)

**Comment by pablogalegoc** [comment]
Hi @Samuel-Schober-USU!

Looking at the logs of the pod:
```
❯ k logs pod/sonarqube-6dc69c67c8-tgf5b -n sonarqube
sonarqube 16:09:37.17
sonarqube 16:09:37.17 Welcome to the Bitnami sonarqube container
sonarqube 16:09:37.17 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube 16:09:37.18 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube 16:09:37.18
sonarqube 16:09:37.19 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube 16:09:37.22 INFO  ==> Creating SonarQube configuration
sonarqube 16:09:37.27 INFO  ==> Adding properties provided via SONARQUBE_EXTRA_PROPERTIES to sonar.properties
grep: Unmatched ( or \(
grep: Unmatched ( or \(
sonarqube 16:09:37.39 INFO  ==> Trying to connect to the database server
sonarqube 16:09:37.40 INFO  ==> Ensuring SonarQube directories exist
sonarqube 16:09:37.43 INFO  ==> Starting SonarQube in background
sonarqube 16:09:37.98 INFO  ==> Waiting for SonarQube to start...
```
This is the function of the container that sets the extra properties in the container: [sonarqube_conf_set](https://github.com/bitnami/bitnami-docker-sonarqube/blob/bd038cefb8b98dee2bc84b10c6cb5f3c16acdf78/8/debian-10/rootfs/opt/bitnami/scripts/libsonarqube.sh#L245)

**Comment by luizjr** [comment]
I Have Same problem

**Comment by luizjr** [comment]
> Hi @Samuel-Schober-USU!
> 
> Looking at the logs of the pod:
> 
> ```
> ❯ k logs pod/sonarqube-6dc69c67c8-tgf5b -n sonarqube
> sonarqube 16:09:37.17
> sonarqube 16:09:37.17 Welcome to the Bitnami sonarqube container
> sonarqube 16:09:37.17 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
> sonarqube 16:09:37.18 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
> sonarqube 16:09:37.18
> sonarqube 16:09:37.19 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
> sonarqube 16:09:37.22 INFO  ==> Creating SonarQube configuration
> sonarqube 16:09:37.27 INFO  ==> Adding properties provided via SONARQUBE_EXTRA_PROPERTIES to sonar.properties
> grep: Unmatched ( or \(
> grep: Unmatched ( or \(
> sonarqube 16:09:37.39 INFO  ==> Trying to connect to the database server
> sonarqube 16:09:37.40 INFO  ==> Ensuring SonarQube directories exist
> sonarqube 16:09:37.43 INFO  ==> Starting SonarQube in background
> sonarqube 16:09:37.98 INFO  ==> Waiting for SonarQube to start...
> ```
> 
> This is the function of the container that sets the extra properties in the container: [sonarqube_conf_set](https://github.com/bitnami/bitnami-docker-sonarqube/blob/bd038cefb8b98dee2bc84b10c6cb5f3c16acdf78/8/debian-10/rootfs/opt/bitnami/scripts/libsonarqube.sh#L245)

Same message for me.

**Comment by javsalgar** [comment]
Hi,

Could you set the variable BITNAMI_DEBUG=true so we can see the issue with the value?

**Comment by luizjr** [comment]
> 

It's breaking at the comma. And LDAP has some settings that must have a comma.

**Comment by javsalgar** [comment]
Could you provide example values that trigger the  issue?

**Comment by luizjr** [comment]
> Could you provide example values that trigger the issue?

```yaml
extraProperties:
  - "sonar.forceAuthentication=true"
  - "sonar.security.realm=LDAP"
  - "ldap.url=ldap://ldapserver.com"
  - "ldap.windows.auth=true"
  - "ldap.user.baseDn=OU=example,DC=example,DC=local"
  - "ldap.user.request=(&(objectClass=user)(sAMAccountName={login}))"
  - "ldap.user.realNameAttribute=givenName"
  - "ldap.user.emailAttribute=mail"
  - "ldap.bindDn=alm"
  - "ldap.bindPassword=PasswordHere"
  - "ldap.group.idAttribute=sAMAccountName"
  - "ldap.group.baseDn=OU=ALM,OU=Example,DC=Example,DC=local"
  - "ldap.group.request=(&(objectClass=group)(member={dn}))"
  - "sonar.lf.enableGravatar=true"
  ```

**Comment by luizjr** [comment]
> Hi,
> 
> I found the value that is causing the issue
> 
> ```
> ldap.group.request=(&(objectClass=group)(member to '(&(objectClass=group)(member={dn}))
> ```
> 
> I will open a task for investigating it, thanks for reporting!

I noticed that when there are commas in between, it also breaks the line, and for LDAP this shouldn't happen.

**Comment by Samuel-Schober-USU** [comment]
Hello together,

sorry for the late response from my side. I somehow lost sight of this issue.
After having a look into it, I am not sure if this repo is the correct place for the issue or if it should be moved to https://github.com/bitnami/bitnami-docker-sonarqube since the problem seems to be with the dockerfile not the Helm chart.

@luizjr In case you need a workaround, I solved my problem by using the `extraEnvVars`:
```
# LDAP configuration
  extraEnvVars:
    ## General Configuration
    - name: SONAR_SECURITY_REALM
      value: "LDAP"
    - name: LDAP_URL
      value: "..."
    - name: LDAP_BINDDN
      value: "..."
    - name: LDAP_BINDPASSWORD
      value: "..."
    - name: LDAP_AUTHENTICATION
      value: "..."
    ## User Configuration
    - name: LDAP_USER_BASEDN
      value: "..."
    - name: LDAP_USER_REQUEST
      value: "..."
    - name: LDAP_USER_REALNAMEATTRIBUTE
      value: "..."
    - name: LDAP_USER_EMAILATTRIBUTE
      value: "..."
    ## Group Configuration
    - name: LDAP_GROUP_BASEDN
      value: "..."
    - name: LDAP_GROUP_REQUEST
      value: "..."
    - name: LDAP_GROUP_IDATTRIBUTE
      value: "..."
```

**Comment by javsalgar** [comment]
Yes, I agree that this is more related to the container. Thank you for sharing a workaround!

**Comment by luizjr** [comment]
> Hello together,
> 
> sorry for the late response from my side. I somehow lost sight of this issue. After having a look into it, I am not sure if this repo is the correct place for the issue or if it should be moved to https://github.com/bitnami/bitnami-docker-sonarqube since the problem seems to be with the dockerfile not the Helm chart.
> 
> @luizjr In case you need a workaround, I solved my problem by using the `extraEnvVars`:
> 
> ```
> # LDAP configuration
>   extraEnvVars:
>     ## General Configuration
>     - name: SONAR_SECURITY_REALM
>       value: "LDAP"
>     - name: LDAP_URL
>       value: "..."
>     - name: LDAP_BINDDN
>       value: "..."
>     - name: LDAP_BINDPASSWORD
>       value: "..."
>     - name: LDAP_AUTHENTICATION
>       value: "..."
>     ## User Configuration
>     - name: LDAP_USER_BASEDN
>       value: "..."
>     - name: LDAP_USER_REQUEST
>       value: "..."
>     - name: LDAP_USER_REALNAMEATTRIBUTE
>       value: "..."
>     - name: LDAP_USER_EMAILATTRIBUTE
>       value: "..."
>     ## Group Configuration
>     - name: LDAP_GROUP_BASEDN
>       value: "..."
>     - name: LDAP_GROUP_REQUEST
>       value: "..."
>     - name: LDAP_GROUP_IDATTRIBUTE
>       value: "..."
> ```

I haven't tested it yet, but it seems that this solution is suitable.

**Comment by aoterolorenzo** [comment]
Hi @Samuel-Schober-USU,

Thanks again for taking the time to file the issue. Finally, we have implemented support for LDAP through chart values, as we already have in some other applications. This will allow us to pass the LDAP parameters in a more consistent and cohesive way, and the initial issue is not present anymore using these values.
