### ISSUE TITLE
[bitnami/etcd] after poweroff or reboot pods maybe start error with bad member ID arg 

### ISSUE THREAD

**Issue by zerols** [bitnami/charts#8055]
**Which chart**:
[bitnami/etcd]

**Describe the bug**:
after helm install i have 5 node , every node have one etcd pods,  sometimes i poweroff or reboot one node , the pod of this node maybe not start sucess and show me :
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

k8s version: v1.21.3 
os: redhat7.5

**Comment by yilmi** [comment]
Hi @zerols, this seem to be more a problem with your kubernetes platform rather than the chart itself. Restarting a node shouldn't cause issues.

If you can provide clear repro steps, regardless of your kubernetes platform I can investigate, otherwise I'd advise you troubleshoot this issue further to narrow down the possible cause and we could also discuss it with you.

**Comment by yilmi** [comment]
@zerols, actually it looks like this was reported earlier in https://github.com/bitnami/charts/issues/6251.

Would you mind reviewing this issue to see if you can find a workaround or a fix merged there? Feel free to add reproduction details there too to help us fix all the possible cases.

Thanks!

**Comment by yilmi** [comment]
Some more related issues:
- https://github.com/bitnami/charts/issues/6110
- https://github.com/bitnami/charts/issues/7048
- https://github.com/bitnami/charts/issues/6943

**Comment by adomenech73** [comment]
We are experiencing exactly the same issue.

k8s: v1.21.12-eks-a64ea69
bitnami/etcd chart: 8.2.6

The only workaround that works for us to recover the situation is to scale down the statefulset to 0 and scale back up to 3

**Comment by rafariossaa** [comment]
Hi @adomenech73 
  Do you mind opening  a new issue ? this way we could track your issue better.

Thanks forehand.
