### ISSUE TITLE
Recover cluster fails

### ISSUE THREAD

**Issue by mbendtsen** [bitnami/charts#8056]
**Which chart**:
rabbitmq

**Describe the bug**
We're testing disaster recovery using RabbitMQ in AKS. 
We were testing what would happen if we have 2 nodes in the cluster and both pods crashes (restarts).

**To Reproduce**

1. Install chart using replicaCount=2
2. Wait for the pods, volumes and Statefulset to be up and running
3. Delete both pods

**Expected behavior**
`rabbitmq-0` is recreated, but RabbitMQ fails to start, stating that the second node `rabbit@rabbitmq-1.rabbitmq-headless.rabbitmq.svc.cluster.local` could not be found. `rabbitmq-1` is never recreated.

According to [this](https://www.rabbitmq.com/clustering.html#restarting-schema-sync) RabbitMQ waits for 5 minutes (default) for other nodes to sync, but in Kubernetes, only the first pod is creating, propably waiting for the pod to go green before it creates the second pod. But this result in an unsolveble state. 

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

I think this could be related to the fact that 

```
podManagementPolicy: OrderedReady
```

Could you try repeating the process but changing the value `podManagementPolicy` to `Parallel`? If that's the issue, then we could consider changing that default value.

**Comment by mbendtsen** [comment]
Hi @javsalgar 

That helped. When all pods are connecting parallel the cluster becomes online. 

Thanks
