### ISSUE TITLE
problems with common dependency when using bitnami charts through chart proxies

### ISSUE THREAD

**Issue by itsmethemojo** [bitnami/charts#8081]
As company requirement i have to pull helm charts from the "outer world" through a helm chart proxy. See https://www.jfrog.com/confluence/display/JFROG/Remote+Repositories

So this all works nice until helm charts define requirements also from the "outer world", because the proxy will just pass through the chart artifact without modifing for example source uris in the dependecies list.

What bothers me is that mostly the only dependency is the common chart which does not hold much more then some templates which also could be added through a bitnami chart wide build process.

## My questions are: 

1. Do you have any recommendations how to deal with this? 
2. Do you know any other clients/organizations using your charts facing this problems?

**Comment by migruiz4** [comment]
Hi @itsmethemojo,

I don't have much experience with Helm repo proxies, but I think that what you are looking for is the section 'Automatically Rewriting External Dependencies' of https://www.jfrog.com/confluence/display/JFROG/Kubernetes+Helm+Chart+Repositories

The description of the section matches with what you described in this issue, and appears that it can be used to rewrite the dependencies URL to point to your proxy server.

**Comment by itsmethemojo** [comment]
Hi @migruiz4 

this is exactly what i needed. Thanks for helping me out
