### ISSUE TITLE
replicaCount: 3 is not respected when using values.yaml

### ISSUE THREAD

**Issue by koo9** [bitnami/charts#8083]
run helm install redis-sentienel bitnami/redis -values values.yaml 
even though the replicaCount: 3 but there are two replicas created. 

redis-sentinel-node-0     ●           2/2                            0 Running           10.244.1.97            
redis-sentinel-node-1     ●           2/2                            0 Running           10.244.1.98         

anything I am missing?

**Comment by pablogalegoc** [comment]
Cloning the repo and runing `helm install redis-sentinel bitnami/redis -f values.yaml` in `charts/bitnami/redis` I get:
```
NAME                            READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
pod/redis-sentinel-master-0     1/1     Running   0          96s   10.0.0.251   minikube   <none>           <none>
pod/redis-sentinel-replicas-0   1/1     Running   0          96s   10.0.0.187   minikube   <none>           <none>
pod/redis-sentinel-replicas-1   1/1     Running   0          54s   10.0.0.131   minikube   <none>           <none>
pod/redis-sentinel-replicas-2   1/1     Running   0          27s   10.0.0.206   minikube   <none>           <none>
```

**Comment by koo9** [comment]
it looks like I have a custom pod speading contraints on the cluster. I will look into that. thx

**Comment by pablogalegoc** [comment]
I'll close this issue then, feel free to reopen it or open another if you face other problems
