### ISSUE TITLE
[thanos] TLS secrets generation is inconsistent

### ISSUE THREAD

**Issue by dennybaa** [bitnami/charts#8094]
The secret resource type is `type: kubernetes.io/tls` which does not allow usage of **anything but `tls.crt`, `tls.key` and `ca.crt`**

**version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600"...}**

```
COMBINED OUTPUT:
  Release "thanos" does not exist. Installing it now.
  Error: Secret "thanos-query-grpc-client" is invalid: [data[tls.crt]: Required value, data[tls.key]: Required value]
```

```
  {{- $cert := genSignedCert $hostname nil (list $hostname) 365 $ca }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  {{- else }}
  tls-cert: {{ .Values.query.grpc.client.tls.cert | b64enc | quote }}
  tls-key: {{ .Values.query.grpc.client.tls.key | b64enc | quote }}
  ca-cert: {{ .Values.query.grpc.client.tls.ca | b64enc | quote }}
  {{- end }}
```

**Comment by yilmi** [comment]
Hi @dennybaa, would you like to open a pull request for this change? Did you test changing this values locally and then using the local version of the chart to confirm the fix.

**Comment by dennybaa** [comment]
Hi @yilmi, yup this looks good for me.

**Comment by dennybaa** [comment]
Yes, I'm able to deploy components with `autoGenerated: false`.

**Comment by yilmi** [comment]
Thanks for the contribution @dennybaa! I'm closing this issue, but feel free to reopen if needed 👍
