### ISSUE TITLE
[bitnami/kafka] confusion for auth.tls.jksKeystoreSAN in 14.3.0

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#8097]
**Which chart**:
bitnami/kafka 14.3.0

**Describe the bug**

Docs is unclear if jksKeystoreSAN key should be in
* `auth.tls.existingSecret` (deprecated) or
* `auth.tls.jksTruststoreSecret`

https://github.com/bitnami/charts/blob/897ff948a0d54d8667ec01ba59ecb28550492824/bitnami/kafka/README.md#L138

https://github.com/bitnami/charts/blob/897ff948a0d54d8667ec01ba59ecb28550492824/bitnami/kafka/README.md#L450

Currently if not specifying `existingSecret` and only `jksTruststoreSecret`, an error is raised

```
Error: UPGRADE FAILED: execution error at (kafka/templates/NOTES.txt:256:4):
VALUES VALIDATION:

kafka: auth.tls.existingSecret
    A secret containing the Kafka JKS keystores and truststore is required
    when TLS encryption in enabled and TLS format is "JKS"
```

**To Reproduce**

```
~ values.override.yaml ~
auth:
  tls:
    jksTruststoreSecret: my-secret
    password: my-password
```

**Expected behavior**

Clearer docs on TLS with SAN certs

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
3.7.1
```

- Output of `kubectl version`:

```
1.22.2
```

**Additional context**

**Comment by marcosbc** [comment]
Hi @tbnguyen1407, unfortunately I could not reproduce this issue. By only specifying `auth.tls.jksTruststoreSecret` and `auth.tls.password` parameters in a new Kafka deployment, it works fine for me.

Could you share the sequence of commands you were using to deploy, where you are able to reproduce this issue?

**Comment by tbnguyen1407** [comment]
@marcosbc sorry missed 1 parameter `auth.clientProtocol` to reproduce

```
helm upgrade -i kafka bitnami/kafka \
  --set auth.clientProtocol=tls \
  --set auth.tls.jksTruststoreSecret=my-secret \
  --set auth.tls.jksKeystoreSAN=my-key.jks \
  --dry-run --debug
```

Output

```
Error: execution error at (kafka/templates/NOTES.txt:256:4):
VALUES VALIDATION:

kafka: auth.tls.existingSecret
    A secret containing the Kafka JKS keystores and truststore is required
    when TLS encryption in enabled and TLS format is "JKS"
helm.go:88: [debug] execution error at (kafka/templates/NOTES.txt:256:4):
VALUES VALIDATION:

kafka: auth.tls.existingSecret
    A secret containing the Kafka JKS keystores and truststore is required
    when TLS encryption in enabled and TLS format is "JKS"
```

**Comment by marcosbc** [comment]
Hi @tbnguyen1407, checking the logic:

```
{{- if and (include "kafka.tlsEncryption" .) (eq .Values.auth.tls.type "jks") (empty .Values.auth.tls.existingSecrets) (empty $secretName) (not (.Files.Glob "files/tls/*.jks}")) }}
kafka: auth.tls.existingSecret
    A secret containing the Kafka JKS keystores and truststore is required
```

It seems like in your case you are missing the `auth.tls.existingSecrets` option. Note that this configuration does not persist when you run `helm upgrade`, so you will always need to specify it.
