### ISSUE TITLE
getaddrinfo ENOTFOUND mongodb-0.mongodb-headless.prod.svc.cluster.local

### ISSUE THREAD

**Issue by amleshk66** [bitnami/charts#8098]
I have installed Bitnami/Mongo DB MongoDB shell version v4.4.10.

while accessing the DB outside through LB, I am getting getaddrinfo ENOTFOUND mongodb-0.mongodb-headless.prod.svc.cluster.local this issues and also when doing migration through compass after 70-80% its giving conenction timeout error.

Please suggest it's bit urget.
Any suggestions would be greate help.

**Comment by carrodher** [comment]
When installing the Helm chart there are some notes shown in the console, in those notes you can see the connection instruction depending on the values you used for installing the chart.
You can get those notes at any time by running
```
$ helm get notes RELEASE_NAME -n NAMESPACE
```

The information appearing in that notes is based on the values used at install time via `helm install --set foo` or via modifying the _values.yaml_ and installing the chart with `helm install -f values.yaml`.
If you didn't perform any other manual modification that can affect the way the chart is accessed, you should be able to connect to the containers from inside or outside the cluster (depending on the configuration you used).
