### ISSUE TITLE
redis-cli master-replica-setup failover

### ISSUE THREAD

**Issue by SpikePy** [bitnami/charts#8101]
In the helm chart version 15.5.4 i have a master/replica-setup of redis. problem is that a sync between to the replica is not possible because the URL is wrong. it seems the variable HEADLESS_SERVICE is missing that is used to sync master and replica.

1:S 11 Nov 2021 12:00:56.764 # Unable to connect to MASTER: Invalid argument
1:S 11 Nov 2021 12:00:56.864 * Connecting to MASTER redis-replicas-0.:6379

This variable seems to fail in the statefulset of the master and replica.

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate the commands and parameters you used to deploy it ? I would like to reproduce the issue.

**Comment by SpikePy** [comment]
Ok sorry I don't even know where to start, the whole chart does not seem to be build to make a redis master-replica-setup work when doing a failover.

So this is my values.yaml
```
auth:
  enabled: false

master:
  persistence:
    storageClass: default

replica:
  replicaCount: 1
  persistence:
    storageClass: default
```

I apply it with `helm install -f redis_values.yaml debug bitnami/redis`

When redis is running I create an entry with `redis-cli set foo bar`. After this I switch to the replicas cli and test if the key is there with `redis-cli get foo`. So far so good, that is working. 

Now the problems pile up. Running `redis-cli failover` to switch master and replica is stuck with `redis-cli replication` returns `master_failover_state:failover-in-progress`. So I abort the failover with `redis-cli failover abort` and do a manual switch. on replica: `redis-cli replicaof no one` master: `redis-cli replicaof debug-redis-replicas-0.debug-redis-headless.default.svc.cluster.local 6379`. now I have switched the master and replica. I know this "solution" is bad but the best I can do in this moment. now the problem is that the redis services thats still used by the shop (spryker) uses the service *debug-redis-master* and I can't change this without restarting the application so I have to patch the services so that the master-service selects the replica pod. So now my shop can still work even if the redis-master pod has problems. 

Now I could fix that master pod while the shop is using the replica-pod with the master role but when you change the config of the master pod (because it crashes or you just scale it down) it restarts and the liveness- and readinessprobe of the replica fails because the master is not running and now the replica stops working too! My workaround for this is to disable replica liveness- and readinessprobe --> not cool.

So after you disable that and fix the redis-master you want to switch back via `redis-cli failover`. This time it kind of worked for me (even `info replication` shows `slave0:ip=debug-redis-replicas-0.,port=6379,state=online,offset=852,lag=1` this is where the variable HEADLESS_SERVICE seems to be missing) but you have to manually change the service selectors back (so that the master-service directs to the master pod).

Also a problem is that the statefulsets updatestrategy is set to **rolling** by default which makes a downtime free failover not possible when you change something on the helm chart because most of the times this affects the master and replica pod so both will be down at the same time. So you have to overwrite the updatestrategy to **OnDelete** which is a bit tricky because you have to unset the value `updateStrategy,rollingUpdate: null` set in bitnamis values.yaml (the one in your git repo). without that setting `updateStrategy.type: RollingUpdate` will result in an invalid statefulset manifest.

**Comment by rafariossaa** [comment]
Hi,
  Have you tried having more replicas ? with just 2 nodes it is not possible to get the needed quorum to elect a new master.

**Comment by SpikePy** [comment]
I found nothing that says you have to have at least 2 replicas. Do you have a source for that?

So I changed the replica count to 2 but when I run `redis-cli failover` its again stuck saying `master_failover_state:failover-in-progress` ...
```
role:slave
master_host:debug-redis-replicas-0.
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_read_repl_offset:182
slave_repl_offset:182
master_link_down_since_seconds:-1
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:failover-in-progress
```

also take a look at `master_host:debug-redis-replicas-0.`

**Comment by rafariossaa** [comment]
Hi,
  To be able to change the master you should enable sentinel (and you will need at least 3 nodes to be able to get quorum). The reason is that to get quorum you need that half of the cluster size plus 1 agree on which node is going to be the new master.
  Could you give it a try ?

**Comment by SpikePy** [comment]
I did not enable Sentinal and can't because the shop using redis does not support this mode.

**Comment by rafariossaa** [comment]
> Now the problems pile up. Running redis-cli failover to switch master and replica is stuck with redis-cli replication returns master_failover_state:failover-in-progress

I am not very sure why you need to switch roles. Without setinels, the master pod will be always the master one. If it fails kubernetes will restart it again as master.

**Comment by SpikePy** [comment]
What if I want to use a new configuration for redis or a new image but without downtime? Yes the master will come up again but it will take some minutes until it loaded it's 20gb rdb file again into memory.

**Comment by rafariossaa** [comment]
This chart is not suitable for that scenario, that is one of the reasons to use the one with sentinels.
It is difficult to cover all possible scenarios. If you like to send a PR we will be glad to review and merge it.
