### ISSUE TITLE
Need to modify only some attribute in cassandra.yaml config

### ISSUE THREAD

**Issue by myvelmurugan** [bitnami/charts#8102]
Hi All,

We need to tune some of the parameters for cassandra.yaml, We use 5 replicas cassandra statefulset and we use default cassandra.yaml. It is not mounted as persistent volume or configmap. 

I need to modify this value `file_cache_size_in_mb` in the cassandra.yaml file and I don't see any environment value for this attribute to update the env. it should be modified in the file it seems.

I also tried using exsitingConfiguration with configmap, But it completely using the same content. So that "listen address" will be a problem since I am having multiple replicas of cassandra instance. 

How can I change this value and other config it should populated automatically (seeds and listen address) ?  

I appreciate if you anyone shed some light on this issue.

**Comment by myvelmurugan** [comment]
@juan131 can you please help me with this solution.?

**Comment by alemorcuq** [comment]
I don't see a way of setting that without overwriting the whole `cassandra.yaml`. Perhaps a new environment variable can be added for that setting, there are some variables for other settings as well.

**Comment by myvelmurugan** [comment]
I dont think this attribute support the env variable, Its related to offheap setting no even from jvm options.

**Comment by alemorcuq** [comment]
Why? Can't an envvar be used to pass the value to the container and write it to the `cassandra.yaml` file?
