### ISSUE TITLE
ARM64 MongoDB / Readiness probe failed: bash: line 2: /opt/bitnami/scripts/libversion.sh: No such file or directory

### ISSUE THREAD

**Issue by AdyGCode** [bitnami/charts#8128]
## **Which chart**:
- mongodb (latest)
- `https://github.com/bitnami/charts/tree/master/bitnami/mongodb`

## **Describe the bug**

After using Helm to install MongoDB using this chart, the container runs, but the readiness probe fails due to missing `libversion.sh`.

From further investigation it appears that the whole `/opt/bitnami/` folder is missing.

## **To Reproduce**

Set Binami Helm repo:
```script
helm repo add bitnami https://charts.bitnami.com/bitnami
```
Install `mongodb` using 4-focal tag (latest tag fails to get beyond "start" of container):

```shell
helm install mongo bitnami/mongodb --set persistence.enabled=true --set image.repository=arm64v8/mongo --set persistence.mountPath=/data/db --set image.tag=4-focal
```

MongoDB container pulled, container created, container starts, readiness probe fails.

### Output from Rancher UI

Reason | Updated | Message
-- | -- | --
Unhealthy (175) | 4 mins ago | Readiness probe failed: bash: line 2: /opt/bitnami/scripts/libversion.sh: No such file or directory
Started | 39 mins ago | Started container mongodb
Created | 39 mins ago | Created container mongodb
Pulled | 39 mins ago | Container image "docker.io/arm64v8/mongo:4.4.10-focal" already present on machine
Scheduled | 39 mins ago | Successfully assigned default/mongo-mongodb-6dcb7d674c-8gfgp to chicken-pi

## **Expected behavior**

- Containerised MongoDB runs and is available.
- Runs in standalone (default) configuration

## **Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:29Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:29Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}

```

## **Additional context**

Hardware:
- Raspberry Pi 4B, ARM64

OS: 
- Raspberry OS 10 Buster, 64bit enabled

Containerisation: 
- K3s, 
- Docker, 
- Helm, 
- Rancher (for UI)

Have attempted to delay container readiness probe by 6 minutes, no difference.

**Comment by alemorcuq** [comment]
It looks that you are using a custom image not from Bitnami, and thus it doesn't have the required `libversion.sh` file.
