### ISSUE TITLE
httpd helm chart issue

### ISSUE THREAD

**Issue by rbs-cloud** [bitnami/charts#8136]
Hi Team,

i have deployed the httpd helm in kubernets environment but i dont see any folders inside container but by default some folders will be available  like var ,usr and tmp etc...do we need to do any changes to get this files inside containar.

helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/apache

> kubectl exec -it my-release-apache-5f4bc7965-zzcnl  -n ns sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
$ ls -lh
total 0
$

**Comment by javsalgar** [comment]
Hi,

This chart uses the bitnami/apache container, which follows the convention of having the applications in /opt/bitnami/, as well as using /bitnami for persistence. Did you check the instructions for deploying a custom application here? https://github.com/bitnami/charts/tree/master/bitnami/apache#deploying-a-custom-web-application

**Comment by rbs-cloud** [comment]
Hi @javsalgar ,

we have added the repository and installed the chart in kubernets environment like below
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/apache
But the problem is ,we are unable to find the chart in the cluster to modify in the cluster
