### ISSUE TITLE
external-dns 0.9.0

### ISSUE THREAD

**Issue by stumueller** [bitnami/charts#8140]
**Which chart**:
external-dns 5.4.15, app version 0.10.1

**Describe the bug**
0.10.1 of external-dns has a bug related to managed service identities which stops it being able to register DNS addresses.

Would it be possible to make available the bitnami helm chart that is running 0.9.0 as well as 0.10.1

Thanks

**Comment by Mauraza** [comment]
Hi @stumueller,

To use another tag, you only have to change this value. 
```
helm install external-dns bitnami/external-dns --set image.tag=0.9.0-debian-10-r62
```

https://github.com/bitnami/charts/tree/master/bitnami/external-dns#external-dns-parameters
