### ISSUE TITLE
Add ingressClass options to the kube-prometheus ingresses

### ISSUE THREAD

**Issue by cyrilcros** [bitnami/charts#8142]
**Which chart**:
kube-prometheus:6.3.1, possibly all Bitnami charts

**Is your feature request related to a problem? Please describe.**
You usually specify which ingress controller an ingress should use via an annotation like  `kubernetes.io/ingress.class: nginx` on the ingress. In Kubernetes 1.22, such annotations like are now deprecated in favor of a `.spec.ingressClass` field. Cf https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/ ingress part.
Newer versions of controllers like `nginx-ingress` would by default give 404 error if `ingressClass` isn't set. https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now , you would need the flag '--watch-ingress-without-class' set to true (default is false).

**Describe the solution you'd like**
Add  `.Values.XXX.ingress.ingressClass` parameters, check ` .capabilities.ingress.apiVersion` and set the `ingressClass` in the templates if using `networking.k8s.io/v1`. `XXX` would be `prometheus`, `thanos`, `alertmanager`.
Even better, test that `kubernetes.io/ingress.class` and `ingressClass` are not both set, since this isn't allowed.

**Context**
Other separate charts are incorporating this (contour, nginx-ingress).

**Comment by migruiz4** [comment]
Hi @cyrilcros,

I have created this PR #8147 adding support for `IngressClassName` to the bitnami/kube-prometheus chart.

Please let me know if it works for you.

**Comment by cyrilcros** [comment]
@migruiz4 Thanks for the PR!
