### ISSUE TITLE
[bitnami/spark] Spark does not pick up number of cores correctly (finds 1, should be 16)

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#8146]
**Which chart**:

spark

**Describe the bug**

spark does not pick up number of cores correctly.

Please let me know if this is more appropriately filed in Spark upstream.

```
argocd app create spark \
    --repo https://charts.bitnami.com/bitnami \
    --helm-chart spark \
    --dest-server https://kubernetes.default.svc \
    --insecure \
    --helm-set 'worker.replicaCount=3' \
    --dest-namespace redacted \
    --revision '5.7.9'

argocd app sync spark
```

Logs from `spark-worker-0`:

```
Spark Command: /opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master-svc:7077
========================================
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/11/15 20:51:13 INFO Worker: Started daemon with process name: 37@spark-worker-1.spark-headless.redacted.svc.cluster.local
...
21/11/15 20:51:14 INFO Utils: Successfully started service 'sparkWorker' on port 39635.
21/11/15 20:51:14 INFO Worker: Worker decommissioning not enabled.
21/11/15 20:51:14 INFO Worker: Starting Spark worker xx.xx.xx.xx:39635 with 1 cores, 58.3 GiB RAM
21/11/15 20:51:14 INFO Worker: Running Spark version 3.2.0
21/11/15 20:51:14 INFO Worker: Spark home: /opt/bitnami/spark
```

Notice `Starting Spark worker xx.xx.xx.xx:39635 with 1 cores, 58.3 GiB RAM`.

There are in fact 16 vCPUs:

```
$ k exec -it -n redacted spark-worker-0 -- python -c 'import multiprocessing as mp; print(mp.cpu_count())'
16
```

These are AWS EKS m5.4xlarge worker nodes.

**Expected behavior**

If not set, `spark.deploy.defaultCores` is supposed to get all available cores.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

Probably unrelated: I've also noticed a `ps aux` on `spark-worker-0` shows

```
/opt/bitnami/java/bin/java -cp /opt/bitnami/spark/conf/:/opt/bitnami/spark/jars/* -Xmx1g org
.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master-svc:7077
```

The `-Xmx1g` stood out as that seems to disagree with the worker being launched with "all available ram".

**Comment by juan131** [comment]
Hi @brsolomon-deloitte 

We expose the `worker.memoryLimit` and `worker.coreLimit` parameters so you can set the maximum memory & number of cores the workers can use. Did you give a try to then?

**Comment by brsolomon-deloitte** [comment]
> Hi @brsolomon-deloitte
> 
> We expose the `worker.memoryLimit` and `worker.coreLimit` parameters so you can set the maximum memory & number of cores the workers can use. Did you give them a try?

Yes - when passing e.g. `worker.coreLimit: "4"`, that is picked up successfully and I can see `Registering worker xx.xx.xx.xx:35285 with 4 cores, 4.0 GiB RAM`. The issue is when that parameter is left as the empty string; in that case, Spark is supposed to [default to all available cores](https://spark.apache.org/docs/latest/spark-standalone.html), but it only detects a single core when there are 16 vCPUs.

Thinking about it, this is probably better filed in the Apache Spark upstream as the `worker.coreLimit` does do what is advertised.

**Comment by juan131** [comment]
Hi @brsolomon-deloitte 

> Yes - when passing e.g. `worker.coreLimit: "4"`, that is picked up successfully and I can see `Registering worker xx.xx.xx.xx:35285 with 4 cores, 4.0 GiB RAM`

Great, I'm glad you could workaround it setting the parameters.

> Thinking about it, this is probably better filed in the Apache Spark upstream as the worker.coreLimit does do what is advertised.

I agree with you, the name is very confusing.
