### ISSUE TITLE
SQL script in initdbScripts is not executed

### ISSUE THREAD

**Issue by yemkay** [bitnami/charts#8159]
I've a chart with dependency to postgresql chart. My values.yaml is as below:

```
postgresql:
  initdbScripts:
    00_init_dir.sh: |
      #!/bin/sh
      cd $PGDATA/pg_tblspc
      mkdir cp
      echo "Created directories."

    01_init_user.sql: |
      CREATE USER cp WITH SUPERUSER CREATEDB ENCRYPTED PASSWORD 'blahBlah';
      \set tblspc `echo "$PGDATA/pg_tblspc/cp"`
      create tablespace cp owner cp location :'tblspc';

    02_init_db.sh: |
      echo "Creating databases..."
      export PGPASSWORD=$POSTGRES_PASSWORD
      createdb cp --owner=cp --tablespace=cp -U postgres
```

When I run kubectl logs, following is seen:
```
postgresql 17:39:45.21 INFO  ==> Starting PostgreSQL in background...
Created directories.
Creating databases...
createdb: database creation failed: ERROR:  tablespace "cp" does not exist
postgresql 17:39:45.31 INFO  ==> Stopping PostgreSQL...
```
It seems 02_init_db.sh is executed before 01_init_user.sql. Am I missing something?

**Comment by pablogalegoc** [comment]
Hi @yemkay,

Here's the source for the execution of the init scripts [libpostgresql.sh#L676](https://github.com/bitnami/bitnami-docker-postgresql/blob/5a5a0283b40c278093b98577d61dd67837d20d4f/11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L676). That `sort` should guarantee that those scripts are executed in the correct order. Also, it's weird that the logs don't show the other [INFO messages](https://github.com/bitnami/bitnami-docker-postgresql/blob/5a5a0283b40c278093b98577d61dd67837d20d4f/11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L672-L675):
```
info "Loading custom scripts..."
[...]
info "Loading user's custom files from $POSTGRESQL_INITSCRIPTS_DIR ..."
```
Justo confirm, are you configuring any other values apart from `initdbScripts`?

**Comment by yemkay** [comment]
Hi @pablogalegoc,

I was missing a semi-colon in the first line of SQL script. This line I had removed for brevity while posting here. After fixing that, it went through. All fine now. Thanks for this.
