### ISSUE TITLE
Contour v7.0.x doesn't serve traffic with default chart values

### ISSUE THREAD

**Issue by noelbundick-msft** [bitnami/charts#8160]
**Which chart**: 
contour (7.0.1)

**Describe the bug**
The contour chart, in its default configuration, does not serve traffic for k8s Ingress objects

The change made in https://github.com/bitnami/charts/pull/8065/files to run envoy as a non-root user prevents it from using ports < 1024. But ports 80 and 443 are still the default chart values. At runtime, envoy logs show that it is trying to listen on `0.0.0.0:80` and failing

I have to set `containerSecurityContext.runAsUser: 0` (or do something else) to serve traffic

**To Reproduce**

1. Deploy the contour chart v7.0.1
2. Run nginx

```
kubectl run nginx --image=nginx --port=80 --expose=true
```

3. Create an ingress object

```
kubectl create ingress nginx --rule=/=nginx:80
```

4. Try to use it. Watch it fail

```
$ kubectl get ingress
NAME    CLASS     HOSTS   ADDRESS        PORTS   AGE
nginx   contour   *       20.72.216.75   80      63s
```

5. Look at the envoy logs to see the `0.0.0.0:80` failure

**Expected behavior**

I expected the default install of the contour ingress controller to serve traffic

**Version of Helm and Kubernetes**:

- Output of `helm version`: n/a, using flux for deployments

- Output of `flux version`:
```
flux version 0.19.1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Hi! I wasn't able to reproduce the error in my environment: installing the chart with the default parameters for Envoy's container ports worked well.

However, I've noticed that upstream (https://github.com/projectcontour/contour/blob/main/examples/contour/03-envoy.yaml) container ports are set by default to 8080 and 8443. Could you try setting the container ports to those values and run the container as 1001?

**Comment by noelbundick-msft** [comment]
Looks like this got resolved yesterday via https://github.com/bitnami/charts/pull/8166

Closing, thanks for your time!

**Comment by alemorcuq** [comment]
Yes, I merged a PR recently. Thanks for reporting it!
