### ISSUE TITLE
[minio] Azure server endpoint not supported by Helm chart

### ISSUE THREAD

**Issue by jgallucci32** [bitnami/charts#8161]
**Which chart**:
The name (and version) of the affected chart
minio/9.2.0

**Describe the bug**
The MinIO Helm chart only supports Azure gateway mode using the default endpoint https://core.windows.net. There is no way to add the endpoint for a custom URL as supported by MinIO.

**To Reproduce**
n/a

**Expected behavior**
The user should be able to specify the Azure server endpoint using a variable such as `gateway.auth.azure.serviceEndpoint` in the Helm values.

**Version of Helm and Kubernetes**:
n/a

**Additional context**
This issue was addressed in https://github.com/minio/minio/issues/8585

**Comment by jgallucci32** [comment]
For reference, here is the help context showing how to use a custom endpoint
```
NAME:
  minio gateway azure - Microsoft Azure Blob Storage

USAGE:
  minio gateway azure [FLAGS] [ENDPOINT]

FLAGS:
  --address value              bind to a specific ADDRESS:PORT, ADDRESS can be an IP or hostname (default: ":9000")
  --listeners value            bind N number of listeners per ADDRESS:PORT (default: 1)
  --console-address value      bind to a specific ADDRESS:PORT for embedded Console UI, ADDRESS can be an IP or hostname
  --certs-dir value, -S value  path to certs directory (default: "/.minio/certs")
  --quiet                      disable startup information
  --anonymous                  hide sensitive information from logging
  --json                       output server logs and startup information in json format
  --help, -h                   show help

ENDPOINT:
  Azure server endpoint. Default ENDPOINT is https://core.windows.net

EXAMPLES:
  1. Start minio gateway server for Azure Blob Storage backend on custom endpoint.
     $ export MINIO_ROOT_USER=azureaccountname
     $ export MINIO_ROOT_PASSWORD=azureaccountkey
     $ minio gateway azure https://azureaccountname.blob.custom.azure.endpoint
```

**Comment by juan131** [comment]
Hi @jgallucci32 

You're right. We don't offer any parameter to configure the endpoint to use under the Gateway parameters for Azure, see:

- https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml#L972

Would you like to contribute with a PR adding this missing feature? Thanks in advance.

**Comment by jgallucci32** [comment]
@juan131 Thanks for confirming. Yes, I'll see if I can work a PR on this.

**Comment by juan131** [comment]
Thanks @jgallucci32 !! I accepted your PR and merge it. Expect a release of the new chart version in the next few hours.
