### ISSUE TITLE
[bitnami/influxdb] Backup using rclone

### ISSUE THREAD

**Issue by abhi1693** [bitnami/charts#8163]
**Which chart**:
bitnami/influxdb

**Is your feature request related to a problem? Please describe.**
The current implementation for backups only allow google or azure as the providers. This limits us as we prefer to use either mega.nz or minio for backups and restoration.

**Describe the solution you'd like**
Use [rclone](https://rclone.org/) as this has options to use about 15+ different providers

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by carrodher** [comment]
Thanks for the suggestion, it can be a good feature since Bitnami already has a container image for rclone, see https://github.com/bitnami/bitnami-docker-rclone.

Would you like to create a PR adding this feature? The Bitnami team will be happy to review it and provide feedback

**Comment by abhi1693** [comment]
@carrodher Since the image exist, would it make more sense to have a chart for rclone and use it as a dependency on influx? This can later be used for other charts like minio, postgres, redis etc

**Comment by carrodher** [comment]
Creating a new chart is something we should discuss internally because it implies several changes in our automated test & release pipeline not only the Helm chart templates that are present in this repo. In the end, this decision will require a proper roadmap, product discussions, etc.

On the other hand, adding a new feature to an existing chart simplifies the process, just creating a PR and the review is needed.

**Comment by abhi1693** [comment]
@carrodher Before I jump into adding rclone as a feature, could you take a look at https://github.com/influxdata/helm-charts/pull/321
I had proposed the same on the official repo chart as well but it's just sitting there and eating dust at the moment. Does something like this should be added here?

**Comment by carrodher** [comment]
I don't see any red flag in this approach, I would suggest you go ahead by creating the PR. Probably you will need to adapt the existing PR a little bit since both charts are different but the overall approach looks good to me

**Comment by abhi1693** [comment]
not stale, I have submitted the PR

**Comment by juan131** [comment]
Thanks @abhi1693 ! My colleague @javsalgar will help you with the review process

**Comment by msecker** [comment]
+1 for this feature as rclone would allow google drive as well
