### ISSUE TITLE
Upgrade autoscaling to autoscaling/v2beta2

### ISSUE THREAD

**Issue by farconada** [bitnami/charts#8165]
**Which chart**:
wordpress

**Is your feature request related to a problem? Please describe.**
v2beta1 is deprecated in 1.19 and you should use v2beta2 going forward.
Also, v2beta2 added the new api field spec.behavior in 1.18 which allows you to define how fast or slow pods are scaled up and down.
autoscaling/V2beta2 allows users to autoscale based on custom metrics. It allow autoscaling based on metrics coming from outside of Kubernetes

**Describe the solution you'd like**
Upgrade autoscaling to autoscaling/v2beta2

**Comment by miguelaeh** [comment]
Hi @farconada ,
I guess you refer to the HPA. Would you like to create a PR?
