### ISSUE TITLE
reorder metrics in HPA so CI/CD tools dont fail

### ISSUE THREAD

**Issue by farconada** [bitnami/charts#8167]
**Which chart**:
wordpress and may be other

**Describe the bug**
With HorizontalPodAutoscaler place memory metric before CPU so CI/CD tools dont fail
that this is an issue for GitOps-style synchronization of HPA objects.

**To Reproduce**
Use wordpress chart with argoCD and autoscaling enabled

**Additional context**
This is a known bug related to kubernetes, ArgoCD and other tools with just need to reorder the declaration of the metrics.

https://github.com/jaegertracing/helm-charts/pull/258
https://github.com/argoproj/argo-cd/issues/1079
https://github.com/kubernetes/kubernetes/issues/74099

**Comment by Mauraza** [comment]
Hi @farconada,

I see you have already created another issue https://github.com/bitnami/charts/issues/8165 about this, rigth?

**Comment by farconada** [comment]
I've done the PR by just updated the api version and a bit more but indeed with #8179 HPA could be more than monitor cpu/mem (not done with this PR)

**Comment by Mauraza** [comment]
Hi @farconada,

Thanks for the contribution ❤️ !! we review it!
