### ISSUE TITLE
[bitnami/grafana-operator] Missing arguments in deployment

### ISSUE THREAD

**Issue by 1naboki1** [bitnami/charts#8169]
**Which chart**:
bitnami/grafana-operator 1.3.6

**Is your feature request related to a problem? Please describe.**
Not directly, it would improve investigating problems.

**Describe the solution you'd like**
Support of all args of the grafana-operator in the value.yaml

https://github.com/bitnami/charts/blob/2580b0bce48024684b1e880828f0b15edd0fb305/bitnami/grafana-operator/templates/deployment.yaml#L61-L70

but misses

- --zap-devel                                     Enable zap development mode (changes defaults to console encoder, debug log level, disables sampling and stacktrace from 'warning' level)
- --zap-encoder encoder                           Zap log encoding ('json' or 'console')
- --zap-level level                               Zap log level (one of 'debug', 'info', 'error' or any integer value > 0) (default info)
- --zap-sample sample                             Enable zap log sampling. Sampling will be disabled for integer log levels > 1
- --zap-stacktrace-level level                    Set the minimum log level that triggers stacktrace generation (default error)
- --zap-time-encoding timeEncoding                Sets the zap time format ('epoch', 'millis', 'nano', or 'iso8601') (default )

**Describe alternatives you've considered**
The alternative is to manually put the args in every release inside the deployment.yaml. At least steering the log level would benefit to the whole deployment procedure.

**Comment by migruiz4** [comment]
Hi @1naboki1,

I have created this PR #8177 adding the missing values and an extraArgs feature to add other arguments if needed.

Let me know if it works for you.
