### ISSUE TITLE
[thanos] CA should be optional when doing client TLS

### ISSUE THREAD

**Issue by ArchiFleKs** [bitnami/charts#8172]
**Which chart**:
thanos: > 8.0

**Describe the bug**

I did not had any issue with client TLS and mTLS when running version <8.

specifying CA used to be optionnal [here](https://github.com/bitnami/charts/blob/89d9d7df53e89f8657c907a13b9c4fdb144f9512/bitnami/thanos/templates/query/tls-client-secret.yaml#L24) and [now it set as empty]() when unspecified but the [flag is still in used](https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query/deployment.yaml#L144) and point to an empty file specified in the secret.

This behavior seems to break mTLS, I'm using an Nginx ingress secure by Let's encrypt on the other hand, and it was working fine without specifying the CA, when I remove the flag, my TLS querier are working as expected.

I think specifying a CA should be optional like before.

**Expected behavior**
TLS client is working without having to specify CA, only Key and Cert

**Version of Helm and Kubernetes**:

Kubernetes 1.21 and terraform-provider-helm 2.4.1

**Comment by javsalgar** [comment]
Hi,

I agree that, if it is possible to make it work without CA, it should continue as it is. As you discovered the issue, would you like to submit a PR with the fix? If not, we will work on it.

**Comment by ArchiFleKs** [comment]
> Hi,
> 
> I agree that, if it is possible to make it work without CA, it should continue as it is. As you discovered the issue, would you like to submit a PR with the fix? If not, we will work on it.

I'll try to make a PR shortly

**Comment by javsalgar** [comment]
Thank you!!

**Comment by rlees85** [comment]
Its a shame this is closed as stale. I have the same problem and am tempted to submit a PR to work around it. I cannot think of a 'clean' approach to do this though.

Maybe something like a `systemCa` flag under `client` that is default to `false` (to keep existing behaviour). Then we can set it to `true` to skip adding the extra command line for the client CA certificate.

**Comment by javsalgar** [comment]
Hi!

If you had a PR in mind, do not hestitate to send it and we can iterate on it :D
