### ISSUE TITLE
[postgresql-ha] How do I update releases correctly with PVC saving?

### ISSUE THREAD

**Issue by maxinfosoft** [bitnami/charts#8176]
I tried dozens of releases of this chart in EKS (AWS Kubernets), as well as various combinations --set pgpoolimage.tag = and --set postgresqlimage.tag =
and I cannot achieve the correct work of this chart with any of the releases.

The main problems are:
1) Replicas work incorrectly - replication_delay for standby or incorrect pgpool work that incorrectly distributes data queries (SQL SELECT can report that data is available and in the next query after a second that it is no longer available).

2) Cannot make the correct helm upgrade postgresql-ha bitnami/postgresql-ha with new versions -> always error CrashLoopBack.
Upgrade helm only works correctly if I specify the same image version for  "-set pgpoolImage.tag=" and "-set postgresqlImage.tag=" from which this chart was installed.

Due to these problems, I ask you to redirect to a URL with a description or write here how to do this task correctly with this helm chart:
How to perform the upgrade procedure using helm upgrade to update the release to the latest version with new versions of images for pgpool & repmgr to save the PVC with the database.  Or it is impossible and it is assumed that I should do it yourself to migrate data from the PVC of an old release into a new PVC, which is created after deploying a new release?

**Comment by carrodher** [comment]
You can find the documentation of this Helm chart in [the README](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/README.md), for example, there is a section about how to upgrade it, see https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/README.md#upgrading

**Comment by maxinfosoft** [comment]
Thanks, carrodher.
Of course, we've looked at this documentation before, but it doesn't answer any of my questions above.
How to update postgresql-ha releases and still keep the old PVC with the database by switching the new release to this old database during "helm upgrade"?
How can I make sure that new releases are guaranteed to pick up and work correctly without errors?

**Comment by carrodher** [comment]
PVC management is handled by Helm itself, when you upgrade a deployment with PVs/PVCs those are maintained and attached to the new release as they were in the previous one. In fact, that's the reason why you need to specify the password parameters in your `helm upgrade` command.

**Comment by maxinfosoft** [comment]
Why does data desynchronization occur between two replicas even though replication_delay (show pool_nodes;) field is 0 ?
When accessed through postgresql-ha-pgpool.default.svc.cluster.local:5432, there may or may not be data, depending on which replica the request was sent to.
How to research this problem and solve it?

**Comment by carrodher** [comment]
When the chart is deployed (with default params) there are 3 pods: 1 for pgpool and 2 for posgres
```console
$ helm ls
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
psql	default   	1       	2021-11-25 07:35:32.212126506 +0000 UTC	deployed	postgresql-ha-8.0.1	11.14.0

$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
psql-postgresql-ha-pgpool-9cff9887f-gtcjq   1/1     Running   1          138m
psql-postgresql-ha-postgresql-0             1/1     Running   0          138m
psql-postgresql-ha-postgresql-1             1/1     Running   0          138m
```

I am trying to reproduce the issue by accessing the different containers with the instructions provided in the notes but everything seems to be fine:
```console
$ helm get notes psql
NOTES:
CHART NAME: postgresql-ha
CHART VERSION: 8.0.1
APP VERSION: 11.14.0
** Please be patient while the chart is being deployed **
PostgreSQL can be accessed through Pgpool via port 5432 on the following DNS name from within your cluster:

    psql-postgresql-ha-pgpool.default.svc.cluster.local

Pgpool acts as a load balancer for PostgreSQL and forward read/write connections to the primary node while read-only connections are forwarded to standby nodes.

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default psql-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To get the password for "repmgr" run:

    export REPMGR_PASSWORD=$(kubectl get secret --namespace default psql-postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run psql-postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:11.14.0-debian-10-r0 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h psql-postgresql-ha-pgpool -p 5432 -U postgres -d postgres

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/psql-postgresql-ha-pgpool 5432:5432 &
    psql -h 127.0.0.1 -p 5432 -U postgres -d postgres
```

Did you perform any customization? Are you able to reproduce the issue by using a deployment from scratch without upgrades and changes in the images?
