### ISSUE TITLE
[bitnami/influx] ingress.path is not prefixed to write path

### ISSUE THREAD

**Issue by gboor** [bitnami/charts#8178]
**Which chart**:
bitnami/influxdb v 2.4.1

**Describe the bug**
When setting `ingress.path` to something other than the default `/`, the path is only used for reads. The `/write` endpoint is still on `/write` instead of `/{path}/write`.

**To Reproduce**
1. helm install influx2 bitnami/influxdb --set ingress.enabled=true --set ingress.path=/influx --set architecture=high-availability
2. kubectl get ingress influx2-influxdb -o yaml
3. Note that 2 paths are defined; `/write` and `/influx`, but no `/influx/write`

**Expected behavior**
The `ingress.path` to be prefixed to the `/write` endpoint as well.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am running a bare metal k8s cluster for on-site control. This cluster has no DNS and several services that need exposing, which means I can only use paths to separate them. As such, I want the entire influxdb service on `/influx/*`

**Comment by miguelaeh** [comment]
Hi @gboor ,
Would you like to create a PR fixing it?
