### ISSUE TITLE
Maria Galera - CrashLoopBackOff when all pods deleted or host restart

### ISSUE THREAD

**Issue by tdeslauriers** [bitnami/charts#8181]
I did read all the guidance and tried the suggested solve with no success: 
`helm upgrade MY-RELEASE bitnami/mariadb-galera --set volumePermissions.enabled=true`

**Which chart**:
The name (and version) of the affected chart

```
CHART NAME: mariadb-galera
CHART VERSION: 6.0.3
APP VERSION: 10.6.4
```

**Describe the bug**

If you install the tl;dr version, `helm install my-release bitnami/mariadb-galera`, and you delete all the pods at once, or restart the host, all three instances/replicas will go into  CrashLoopBackOff.   I have tried the same on the regular version,` helm install my-release bitnami/mariadb`, and this is not the case.   In that case the persistent volume seems to work and the single pod comes back up.

**To Reproduce**

1. Using either Kind or Minikube (tried both), on Linux Mint 20.2 Cinnamon
2. Installing the tl;dr version of the mariadb-galera: `helm install my-release bitnami/mariadb-galera`
3. Wait for it to complete and all 3 pods statuses set to 'Running'
4. Either enter the command `kubectl delete --all pods <your release name>` or restart your machine.
5. Enter the command `kubectl get all` and see all pods are in CrashLoopBackOff

- **Note**: the solve from the troubleshooting guide does not resolve behavior, either by following the exact instructions: `helm upgrade MY-RELEASE bitnami/mariadb-galera --set volumePermissions.enabled=true` or by setting volumePerminssions.enabled=true at fresh install.

**Expected behavior**

I would like the pods to restart and enter the status 'Running', instead of CrashLoopBackOff

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-29T02:41:56Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by migruiz4** [comment]
Hi @tdeslauriers,

Have you tried with the following section of the README? It may help you with this issue: https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#bootstraping-a-node-other-than-0

MariaDB is not a cloud-native application and often suffers from issues caused by unclean shutdown when the pods are stopped ungracefully, and it may require manual intervention to recover from critical scenarios. 

These are some related issue that may also help you: https://github.com/bitnami/charts/issues/2260 https://github.com/bitnami/charts/issues/4929

**Comment by tdeslauriers** [comment]
@migruiz4 : Thank you very much!!!!  I am set.   *Sorry that the relevant reading was literally in the ReadMe.   _*facepalm_  That said, linking me to 2260 is actually what ended up working for me, so double thanks for that!
