### ISSUE TITLE
[bitnami/harbor] harbor-chartmuseum fails with s3 backend

### ISSUE THREAD

**Issue by Dragnell87** [bitnami/charts#8184]
**Which chart**:
The name (and version) of the affected chart
bitnami/harbor 11.1.0
**Describe the bug**

Unable to acces to project options,  due to the chartmuseum error with s3 :

```
ERROR [283] AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'cdf-lan-nas'.
Thu, Nov 18 2021 5:04:51 pm | status code: 400, request id: 16B8C333AEFAD9DB, host id: {"repo": "library", "reqID": "78d24d66-e934-4884-a26d-e413829e8b55"}
Thu, Nov 18 2021 5:04:51 pm | 2021-11-18T22:04:51.304Z ERROR [283] Request served {"path": "/library/index.yaml", "comment": "", "clientIP": "10.251.0.196", "method": "GET", "statusCode": 500, "latency": "128.724288ms", "reqID": "78d24d66-e934-4884-a26d-e413829e8b55"}
```

**To Reproduce**
helm install bitnami-harbor -f values.yaml --set harborAdminPassword=12345678 bitnami/harbor

**Version of Helm and Kubernetes**:
RKE2 1.21.6
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-29T02:41:56Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+rke2r1", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-28T16:49:09Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
    s3:
      region: "cdf-nas-lan"
      bucket: "harbor"
      accesskey: "xxxxr"
      secretkey: "xxxxxxxx"
      regionendpoint: "https://minio-fqdn"
      encrypt: ""
      keyid: ""
      secure: "true"
      skipverify: ""
      v4auth: "true"
      chunksize: ""
      rootdirectory: ""
      storageClass: ""
      sse: ""

**Comment by javsalgar** [comment]
Hi,

Do the minio logs show any meaningful error? Also, I see that the name of the region in the values.yaml is cdf-nas-lan and the error says that it should be cdf-lan-nas
