### ISSUE TITLE
[bitnami/redis] Support for operator based deployment for redis operator

### ISSUE THREAD

**Issue by budanm** [bitnami/charts#8187]
**Which chart**:
bitnami/redis

**Is your feature request related to a problem? Please describe.**
Currently, the bitnami redis is a standalone deployment via helm charts. Can there be an operator around it such that lifecycle management-related functionalities can be handled ?

**Describe the solution you'd like**
Currently not sure , whether the non-operator based deployment will be able to support the basic cloud qualities like HA , DR and fault tolerance. The intention is to have a self-managed redis operator based sentinel/cluster deployment

**Describe alternatives you've considered**
Have tried working with some other redis operators , it does not work in an istio compatible setup.

**Additional context**

**Comment by carrodher** [comment]
Currently there are two Redis solutions: [bitnami/redis](https://github.com/bitnami/charts/tree/master/bitnami/redis) and [bitnami/redis-cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster)

[Here](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#choose-between-redis-helm-chart-and-redis-cluster-helm-chart) you can find the difference, I hope it helps to decide what is the best solution for your use case. Regarding an operator, there are no plans in the short-term to add a third solution for redis-operator
