### ISSUE TITLE
[bitnami/apache] CrashLoop as soon as cloneHtdocsFromGit is utilized

### ISSUE THREAD

**Issue by jmConan** [bitnami/charts#8190]
**Which chart**:
| NAME             |       	CHART VERSION |	APP VERSION |	DESCRIPTION            |      
| --- |  --- | ---- | ---- |                     
| bitnami/apache      |   	8.9.3        |	2.4.51    | 	Chart for Apache HTTP Server   |

**Describe the bug**
chart not starting correctly with cloneHtdocsFromGit set. 
CrashLoopBackOff on pod. 
internal container git-repo-syncer crashing.

initContainer works fine, pull remote repo.
apache works fine, /app folder populated with remote repo content.
service/pod unreachable via URL due to crahsloop.

**To Reproduce**
content of helm-config-frontend-dev-mini-v2.yaml:
```
cloneHtdocsFromGit:
  enabled: true
  repository: "https://github.com/mdn/beginner-html-site-styled.git"
  branch: "master"
  interval: 60
```
test repo used from docs:
https://docs.bitnami.com/kubernetes/infrastructure/apache/get-started/deploy-custom-application/

`helm install pp-frontend-dev24 -f helm-config-frontend-dev-mini-v2.yaml bitnami/apache --debug`

**Logs:**
`kubectl describe pod pp-frontend-dev24-apache-5bdb58bdd4-x4jgx` 
 (https://gist.github.com/jmConan/dc24d585d5a69923bd6699534a15d122)

`kubectl logs pp-frontend-dev24-apache-5bdb58bdd4-x4jgx git-clone-repository -f `
Cloning into '/tmp/repo'...

`kubectl logs pp-frontend-dev24-apache-5bdb58bdd4-x4jgx apache -f ` (https://gist.github.com/jmConan/35e1b3ea0a7a33adc2917a04f6ba9c5e)

`kubectl logs pp-frontend-dev24-apache-5bdb58bdd4-x4jgx git-repo-syncer -f`
**fatal: not a git repository (or any parent up to mount point /)**
**Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).**

**Expected behavior**
demo charts with demo repo loading in browser, showing opf the fancy firefox icon.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version           
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

```

- Output of `kubectl version`:

```
kubectl version    
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by jwleon** [comment]
This commit / change might have introduced that behavior:

https://github.com/bitnami/charts/commit/df4fe38f535992798554218847014d5b41f68837#diff-0f11982ded45642a46eac2038c0aefdee76e0166dc0b8546752e4a307eacce58

**Comment by miguelaeh** [comment]
Hi,
Thank you for reporting the issue. I think the above PR should fix it.
