### ISSUE TITLE
[external-dns] It only process ingress from default namespace

### ISSUE THREAD

**Issue by botzill** [bitnami/charts#8191]
Hi

I did install `5.4.16` of this chart and I see that it process the ingress only from `default` namespace. Are there any options I miss related to this?

For other I get in logs :

```
No endpoints could be generated from ingress monitoring/grafana
```

**Comment by juan131** [comment]
Hi @botzill 

You can use the `sources` and `namespace` parameters to decide what objects to watch and from which namespaces, see:

- https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml#L66
- https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml#L80

Also, if your k8s cluster has RBAC support, you should set `rbac.create` and `rbac.clusterRole` to `true` to ensure the required ClusterRole/ClusterRoleBinding are created and ExternalDNS has permissions to watch every namespace, see:

- https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml#L715
