### ISSUE TITLE
[bitnami/thanos] make storegateway service port configurable in ingress

### ISSUE THREAD

**Issue by skydacremam** [bitnami/charts#8193]
**Which chart**:
thanos 8.0.3

**Is your feature request related to a problem? Please describe.**
Yes, I'm trying to expose storegateway to external querier but ingress definition specify http as port name for service forwarding requests to http endpoint and not to the grpc one.

**Describe the solution you'd like**
It would be nice to pass which service port you want to use

**Comment by migruiz4** [comment]
Hi @skydacremam,

I have created this PR #8209 adding a GRPC ingress for the Store Gateway, similar to how GRPC ingress is configured for the Thanos Query GRPC service. 

Please let me know if it works for you.

**Comment by skydacremam** [comment]
Hi @migruiz4,
yes it works for me.

Thank you
