### ISSUE TITLE
bitnami/kafka:2.8.1-debian-10-r31

### ISSUE THREAD

**Issue by racheldaguenethahn** [bitnami/charts#8194]
Hello,

I followed the readme file to deploy the helm chart.
Previously, I created a PVC for Kafka and a PVC for zookeeper (To notice that the existing-claim cannot be defined for zookeeper -> I created it with the name used)
When installing the chart:
- after some time, zookeeper is running correctly. Meanwhile, kafka was in error because it was waiting for zookeeper
- then, zookeeper restarts (I don't know exaclty why at it was running) and then it fails becasue of a read-only error
- > mkdir: cannot create directory '/bitnami/zookeeper/data': Read-only file system

As I'm new in k8s and don't know exactly what is the problem...

Thankls for any rersponse 

Rachel

**Comment by racheldaguenethahn** [comment]
About defining the existing PVC for zookeeper => my bad, I found it
I enabled volumePermissions on both kafka and zookeeper.

No I have an error on kafka pod
  mkdir: cannot create directory '/bitnami/kafka/config': Read-only file system

**Comment by alvneiayu** [comment]
hi @racheldaguenethahn 

Could you share with us the values that you are using, please?

Thanks a lot

Álvaro

**Comment by racheldaguenethahn** [comment]
Hi, yes of course thank you for your response!
Here are the custom values used:

`global:
  imageRegistry: "xxx"
  imagePullSecrets: [xxx]

replicaCount: 1

persistence:
  enabled: true
  existingClaim: "kafka-data"

volumePermissions:
  enabled: true

zookeeper:
  enabled: true
  persistence:
    enabled: true
    existingClaim: "zookeeper-data"
  volumePermissions:
    enabled: true
    image:
      tag: 10-debian-10-r234`

And the PVC config:
For Kafka
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
spec:
  storageClassName: disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: xxx`

For Zookeeper
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
spec:
  storageClassName: disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: xxx`

**Comment by miguelaeh** [comment]
Hi @racheldaguenethahn ,
Did you try enabling the `volumePermissions` init container of the chart?

**Comment by racheldaguenethahn** [comment]
Hi, finally I resolved by removing the "existingClaim" parameter and defining a selector.

`
persistence: 
  enabled: true 
  accessModes: 
    - ReadWriteOnce 
  selector: 
    matchLabels: 
      mev-pvname: kafka-pv 
`
