### ISSUE TITLE
[bitnami/postgresql] how to invoke helm install with scripts to run on 1st boot

### ISSUE THREAD

**Issue by jcourtat** [bitnami/charts#8196]
**Chart**:
bitnami/postgresql 10.5.2

**Describe the bug**
I don't think it's a bug, must be my lake of helm skills. I want to run some scripts (.sh) on postgresql first boot. As declared in documentation, scripts located in files/docker-entrypoint-initdb.d are automatically run. But since i install the chart from a repo, i don't know how to tell helm where to find my files.

**To Reproduce**
```
ls files/docker-entrypoint-initdb.d/
  01_install.sh  02_compile.sh  Alarm

 helm repo add bitnami https://charts.bitnami.com/bitnami
 helm search repo bitnami
 helm install  --namespace verizon --set persistence.existingClaim="cephfs-postgresql-1" \
                                                       --set volumePermissions.enabled=true psql-vz \
                                                       --set image.tag="12.9.0-debian-10-r7" \
                                                       bitnami/postgresql
```
**Expected behavior**
new databases created and seen in my psql client

**Version of Helm and Kubernetes**:

```
(version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
i tryed to clone charts repository, copy my files to charts/bitnami/postgresql/files/docker-entrypoint-initdb.d/
then
```
cd charts
helm install  --namespace verizon --set persistence.existingClaim="cephfs-postgresql-1"         
                                                         --set volumePermissions.enabled=true psql-vz      
                                                              --set image.tag="12.9.0-debian-10-r7"          
                                                              ./bitnami/postgresql
Error: INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: common
```
I don't know what to do to have scripts taken into account
regards

**Comment by rafariossaa** [comment]
Hi,
  You should go cloning the repository. The error you got: `Error: INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: common` is because you need to run: `helm dependency update` before installing, so it gets a subchart called `common`.

**Comment by jcourtat** [comment]
hi,
thank you, i ran the `helm dependency update` command successfully, so now i can helm install from the clone.
But the install doesn't seem to see my files in charts/bitnami/postgresql/files/docker-entrypoint-initdb.d/
here is the content of the install with --debug

> aqsacom@k8s-node-0:~/postgresql/charts$ helm install --debug  --namespace verizon --set persistence.existingClaim="cephfs-postgresql-1"                                                                    --set volumePermissions.enabled=true                                                                     --set image.tag="12.9.0-debian-10-r7"      psql-vz         ./bitnami/postgresql
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/aqsacom/postgresql/charts/bitnami/postgresql
client.go:128: [debug] creating 5 resource(s)
NAME: psql-vz
LAST DEPLOYED: Mon Nov 22 11:14:03 2021
NAMESPACE: verizon
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
image:
  tag: 12.9.0-debian-10-r7
persistence:
  existingClaim: cephfs-postgresql-1
volumePermissions:
  enabled: true
...
\#Source  postgresql/templates/initialization-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-vz-postgresql-init-scripts
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.13.8
    app.kubernetes.io/instance: psql-vz
    app.kubernetes.io/managed-by: Helm
  namespace: verizon
data:
\#Source: postgresql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-vz-postgresql
  labels:
    app.kubernetes.io/name: postgresql  
    helm.sh/chart: postgresql-10.13.8   
    app.kubernetes.io/instance: psql-vz 
    app.kubernetes.io/managed-by: Helm  
    app.kubernetes.io/component: primary
  annotations:
  namespace: verizon
spec:
  serviceName: psql-vz-postgresql-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: psql-vz
      role: primary
  template:
    metadata:
      name: psql-vz-postgresql
      labels:
        app.kubernetes.io/name: postgresql
        helm.sh/chart: postgresql-10.13.8
        app.kubernetes.io/instance: psql-vz
        app.kubernetes.io/managed-by: Helm
        role: primary
        app.kubernetes.io/component: primary
...
          volumeMounts:
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
              subPath:
      volumes:
        - name: custom-init-scripts
          configMap:
            name: psql-vz-postgresql-init-scripts
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: cephfs-postgresql-1

But it seems the psql-vz-postgresql-init-scripts configMap is empty:

> aqsacom@k8s-node-0:~/postgresql/charts$ kubectl --namespace verizon describe configmaps psql-vz-postgresql-init-scripts
Name:         psql-vz-postgresql-init-scripts
Namespace:    verizon
Labels:       app.kubernetes.io/instance=psql-vz
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=postgresql
              helm.sh/chart=postgresql-10.13.8
Annotations:  meta.helm.sh/release-name: psql-vz
              meta.helm.sh/release-namespace: verizon
Data
====
Events:  <none>

Do i have to set an additional value to tell the chart to look into the files/docker-entrypoint-initdb.d/ ?
regards
Julien

**Comment by jcourtat** [comment]
i have been able to load my sql files from files/docker-entrypoint-initdb.d, but i now face a kind of limit on their size

`Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728`

i have 121 files for a total of 13MB, i tryed to gzip my files with no luck, the result is the same.
Can i raise the limit of 3145728 ?

**Comment by rafariossaa** [comment]
In that case, you can add the files to a volume and the use the `extraVolumes` / `extraVolumeMounts` to attach it to the pod.

**Comment by jcourtat** [comment]
Hi @rafariossaa ,
according to your advice, i created a persistentVolumeClaim where i put all my sql files.
i also created a script in bitnami/postgresql/files/docker-entrypoint-initdb.d/1st-boot.sh
`#!/bin/sh
cd /mnt/1st-boot-scripts
for f in `ls`
do
  PGPASSWORD="foobar" psql --host 127.0.0.1 -f $f -U postgres -p 5432
done`

then invoked helm
`helm install  --namespace att \`
`             --set persistence.existingClaim="cephfs-postgresql-1"  \`
`             --set volumePermissions.enabled=true \`
`              --set image.tag="12.9.0-debian-10-r7" \`
`              --set postgresqlPassword="Sesame#1" \`
`              --set primary.extraVolumes=["cephfs-postgresql-start-script"] \`
`              --set primary.extraVolumeMounts=["/mnt/1st-boot-scripts"] \`
`              --debug --dry-run \`
`               psql-vz bitnami/postgresql`

with unsuccessfull status:

install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/aqsacom/postgresql/charts/bitnami/postgresql
Error: INSTALLATION FAILED: YAML parse error on postgresql/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 159: could not find expected ':'
helm.go:88: [debug] error converting YAML to JSON: yaml: line 159: could not find expected ':'
YAML parse error on postgresql/templates/statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:259
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:265
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371

If i remove the --set primary.extraVolumes and --set primary.extraVolumeMounts from the helm invocation, then it doesn't fails.
Is it good to provide a persistentVolumeClaim to primary.extraVolumes or should i use another storageClass ?
regards

**Comment by jcourtat** [comment]
i think i howled too early.
helm install  --namespace att \
              --set persistence.existingClaim="cephfs-postgresql-1" \
              --set volumePermissions.enabled=true \
              --set image.tag="12.9.0-debian-10-r7" \
              --set postgresqlPassword="Sesame#1" \
              --set primary.extraVolumes[0].name=1stboot,primary.extraVolumes[0].persistentVolumeClaim.claimName=cephfs-postgresql-start-script \
              --set primary.extraVolumeMounts[0].mountPath=/mnt/1st-boot-scripts,primary.extraVolumeMounts[0].name=1stboot \
              --debug --dry-run \
               psql-vz bitnami/postgresql

made the chart install not complaining
