### ISSUE TITLE
[bitnami/influxdb] 

### ISSUE THREAD

**Issue by jakoberpf** [bitnami/charts#8197]
**Which chart**:
`bitnami/influxdb --version 2.3.9`

We are experiencing this bug, if we are not the only ones and somebody else could reproduce this I would see if I can make a PR/fix for it.

**Describe the bug**
Helm chart deployment (`helm deploy influxdb bitnami/influxdb`) fails if the variable `diagnosticMode.enabled` is unset/not set to either `true` or `false`. Running the deploy with either `--set "diagnosticMode.enabled=true"` or `--set "diagnosticMode.enabled=false"` (the activation of the diagnostic mode acknowledged).

**To Reproduce**
On a vanilla cluster run `helm deploy influxdb bitnami/influxdb` --> deployment will fail
On a vanilla cluster run `helm deploy influxdb bitnami/influxdb --set "diagnosticMode.enabled=false"` --> deployment will succeed

**Expected behavior**
On a vanilla cluster run `helm deploy influxdb bitnami/influxdb` --> deployment should succeed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
```

**Additional context**
Tested with istio and without istio sidecars in a Rancher and Minikube cluster.

**Comment by miguelaeh** [comment]
Hi @jakoberpf ,
Could you share some logs with the error it throughs please?

I can see that `diagnosticMode.enabled` by default is set to `false`

**Comment by jakoberpf** [comment]
Hi @miguelaeh,

my bad forgot these. The following logs were shown when `diagnosticMode.enabled` was not set to either `true` or `false`. When it was set to `true`, no logs were present.

```
influxdb 10:04:51.90 Welcome to the Bitnami 
influxdb 10:04:51.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-influxdbTue
influxdb 10:04:52.11 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-influxdb/issuesTue
influxdb 10:04:52.13 INFO ==> ** Starting InfluxDB setup
influxdb 10:04:53.37 DEBUG ==> Calculate branch with: Influx CLI 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z
influxdb 10:04:53.39 DEBUG ==> Validating settings in INFLUXDB_* env vars...
influxdb 10:04:53.78 DEBUG ==> Calculate branch with: Influx CLI 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z
influxdb 10:04:53.83 INFO ==> Initializing InfluxDB in branch: 2...
influxdb 10:04:53.84 INFO ==> No injected configuration files found. Creating default config files...
influxdb 10:04:53.92 INFO ==> Starting InfluxDB in background...
timeout reached before the port went into state "inuse"
influxdb 10:05:24.71 INFO ==> Stopping InfluxDB...
Terminated
```

**Comment by miguelaeh** [comment]
Hi @jakoberpf ,
I don't understand which is the issue then, could you please clarify?

From the latest logs you shared, before stopping InfluxDB there is a log:
```
timeout reached before the port went into state "inuse"
```

That log is produce by `wait-for-port` calls. It seems in you case it is thrown [here](https://github.com/bitnami/bitnami-docker-influxdb/blob/a8fa76b85080e82d3bdf941a106d67edde2a4c1f/2/debian-10/rootfs/opt/bitnami/scripts/libinfluxdb.sh#L400). Check your `INFLUXDB_HTTP_PORT_NUMBER` and `INFLUXDB_PORT_NUMBER` variables

**Comment by jakoberpf** [comment]
Hey @miguelaeh,

thats quite helpfull. I check the envs in the pod via the shell and `echo $INFLUXDB_HTTP_PORT_NUMBER` which are empty. For `INFLUXDB_HTTP_PORT_NUMBER` it should be `8086` I guess but I don't know about `INFLUXDB_PORT_NUMBER`
