### ISSUE TITLE
Rabbitmq service not using the right port

### ISSUE THREAD

**Issue by prydonius** [bitnami/charts#82]
It is hardcoded to 15672, but it should honour `.Values.rabbitmqNodeport`

**Comment by sameersbn** [comment]
the management port is served on `15672`, I've added a `rabbitmqManagerport` param in values.toml to customize it to users preferences. The `rabbitmqNodeport` (default: `5672`) is the APMQ port, was not being published on the service. This has been fixed and the value of `rabbitmqNodeport` will be respected by the chart.
