### ISSUE TITLE
Rabbitmq failed to cluster with rebalance set to true

### ISSUE THREAD

**Issue by jchenship** [bitnami/charts#8200]
**Which chart**:

```
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.9.1
```

image `docker.io/bitnami/rabbitmq:3.8.11-debian-10-r0` (should be the default)

**Describe the bug**

We are deploying sentry's helm chart https://github.com/sentry-kubernetes/charts/blob/12.0.0/sentry/Chart.yaml.

And we are using the default values set by the sentry chart.

```
rabbitmq:
  ## If disabled, Redis will be used instead as the broker.
  enabled: true
  clustering:
    forceBoot: true
    rebalance: true
  replicaCount: 3
  auth:
    erlangCookie: pHgpy3Q6adTskzAT6bLHCFqFTF7lMxhA
    username: guest
    password: guest
  nameOverride: ""
```

But when installing the chart via argocd, the pod hangs in ContainerCreating stage, basically the rebalance script in the postStart stage of the pod lifecycle is timing out.

After timing out the pod will become unhealthy and kubelet will restart it. After restart, it immediately become healthy, each rabbitmq node can function normally individually, but the 3 nodes don't cluster at all (e.g. each node only sees itself in the cluster), restarting the pod doesn't join the nodes to the cluster.

There's no useful logs in stdout, because rabbitmq is stuck in the booting process, the std just says something like "starting rabbitmq in the background" "could not start rabbitmq in the background" (Sorry I didn't keep that log).

The only logs I see in the pod is this

```
I have no name!@sentry-rabbitmq-0:/opt/bitnami/rabbitmq/var/log/rabbitmq/log$ cat crash.log
2021-11-16 01:51:55 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.268.0>
    registered_name: []
    exception exit: {{{badmatch,ok},{rabbit,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.267.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.269.0>,normal}]
    links: [<0.267.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 380
  neighbours:
```

Also I ensure this is not a problem with my network or DNS because after setting `rebalance` to `false` we no longer have this issue, the nodes can auto cluster as expected.

**To Reproduce**

Deploy this https://github.com/sentry-kubernetes/charts/tree/12.0.0/sentry

**Expected behavior**

The rabbitmq nodes should be auto clustered.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
argocd@argocd-repo-server-646dfbb9-h6hfk:~$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alvneiayu** [comment]
hi @jchenship

I am reproducing the problem as you explained. Therefore, I have created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot

Álvaro

**Comment by FalconerTC** [comment]
I'm also seeing `rebalance` not working at all. rebalance sets the following on the chart
```
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -ec
                  - |
                    until rabbitmqctl cluster_status >/dev/null; do
                        echo "Waiting for cluster readiness..."
                        sleep 5
                    done
                    rabbitmq-queues rebalance "all"
```
But this just hangs forever. I assume this loop happens before `rabbitmqctl start` occurs

```
❯ k exec -it rabbitmq-0 -c rabbitmq bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@rabbitmq-0:/$ rabbitmqctl cluster_status
Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
	cluster_status

Usage

rabbitmqctl [--node <node>] [--longnames] [--quiet] cluster_status [--timeout <timeout>]
I have no name!@rabbitmq-0:/$
```

**Comment by marcosbc** [comment]
Hi @FalconerTC, unfortunately there hasn't been any progress in the task yet, however it is one of the next tasks we plan to complete in order of priority. Unfortunately I cannot give an ETA of when that will happen.

**Comment by carrodher** [comment]
Hi, just a note to let you know that we released a new revision that gets rid of the postStart hook which should solve this kind of issue
