### ISSUE TITLE
Ghost: Can't load API - mixed content

### ISSUE THREAD

**Issue by NicolaiSchmid** [bitnami/charts#8201]
**Which chart**:
ghost v4.22.3
**Describe the bug**
When installing the ghost chart with ingress access, the website throws an error about mixed content when accessing the ghost api, since the URLs are created with an http:// prefix.

values.yaml:
```
ghostUsername: <>
ghostPassword: <>
ghostEmail: <>
ghostBlogTitle: Wasc's Blog
ghostHost: blog.wasc.io

# ghostEnableHttps: true

image:
  tag: 4.22.3-debian-10-r0
  debug: true

service:
    type: ClusterIP

ingress:
  enabled: true
  hostname: blog.wasc.io
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls: true
  certManager: true

persistence:
  size: 20Gi

mariadb:
  image: 
    debug: true
  auth:
    rootPassword: <>
    password: <>
``` 

When `ghostUseHttps` is disabled, the described error occurs. When it's enabled, the ingress controller can't access the service any more and fails with: `Service "blog/wasc-blog-ghost" does not have any active Endpoint.`
**To Reproduce**
Install the chart with the provided values. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

When you set `ghostEnableHttps` to true, do you see if the containers pass the readyness/liveness probes?

**Comment by NicolaiSchmid** [comment]
No, they kept failing.
I found a solution, patching the chart's liveness, readiness and startup probes like this:
```yaml
readinessProbe:
   httpGet:
     path: /
     port: {{ ternary "https" "http" .Values.ghostEnableHttps | quote }}
     httpHeaders:
        - name: x-forwarded-proto
          value: https
     scheme: http
```
Since the ghost server doesn't reply with https, I had to set the scheme to http and pass the `x-forwarded-proto` header, since the ghost endpoint sends a 301 to redirect to https if it doesn't get notified that https was terminated previously

**Comment by javsalgar** [comment]
Hi,

Thank you for this! Would you like to contribute with a PR with the fix?

**Comment by NicolaiSchmid** [comment]
Sure, but it'll take a week or two

**Comment by javsalgar** [comment]
No problem, we can wait :D
