### ISSUE TITLE
[bitnami/jenkins]Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by mreyesjonmarco** [bitnami/charts#8203]
**Which chart**:
The name (and version) of the affected chart
Jenkins Latest
**Describe the bug**
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
**To Reproduce**

I've tried building my own image using the Dockerfile Below

```
FROM bitnami/jenkins
LABEL maintainer "Bitnami <containers@bitnami.com>"
USER 0
RUN apt-get update && apt-get install -y docker 
USER 1001

```

I also tried

```
FROM bitnami/jenkins
LABEL maintainer "Bitnami <containers@bitnami.com>"

USER 0
RUN install_packages docker
USER 1001
```

I then built the image using
`docker build -t mreyesjonmarco/jenkins:latest .`

I have this global tool configuration

![image](https://user-images.githubusercontent.com/88312943/142800208-bdd21475-5de9-4459-a3f5-d45e2c9f9700.png)

but when I run it on my local machine I have this issue:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Expected behavior**
Docker should build the image

**Version of Helm and Kubernetes**:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by mreyesjonmarco** [comment]
I used #6875 as a reference

**Comment by marcosbc** [comment]
@mreyesjonmarco Note that in order to execute Docker commands inside Jenkin, you will need to configure the Docker host to allow running Docker containers inside Docker (DinD): https://www.docker.com/blog/docker-can-now-run-within-docker/

**Comment by mreyesjonmarco** [comment]
It seems that my previous solution is more complicated than I anticipated it to be.

As a solution to my original problem, I just utilized volumeMounts / volumes to mount the hosts docker info and use that instead of DinD setup.

Thanks for clarifying!

**Comment by mdileepkr** [comment]
I am also facing the same issue, Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. can anyone who got the exact solution please guide me ?
