### ISSUE TITLE
Please Help with tls in charts/bitnami/elasticsearch/

### ISSUE THREAD

**Issue by aviadco11** [bitnami/charts#8206]
HI,
I have my own certificate and I create tls secret as : 
kubectl create secret tls secret-elk --cert <<cert-file>> --key <<key-file>>

then in the helm chart I try to use this secret with parameter - "security.tls.master.existingSecret".
but get error - pod is crash and in logs write : 
```
"ERROR -> in order to configure the tls encryption for elasticsearch you must provide your node key, certificate and a valid certification_authority certificate"...
```

please your help

**Comment by miguelaeh** [comment]
Hi @aviadco11 ,
Did you mount an unsigned certificate? It seems your ES is trying to validate the certificate against the CA certificate and it can't. You can try setting this: https://github.com/bitnami/charts/blob/e24d53ec260755e5e94ecc8d193f10685edc7e7c/bitnami/elasticsearch/values.yaml#L1331 or providing the CA certificate

**Comment by aviadco11** [comment]
HI, NO, I supply signed certificate by ROOT CA and CA certificate and still get this error///

that mean parameter "# ssl_no_validate: True ", its look it's refer to curator and not to the es.

**Comment by miguelaeh** [comment]
Hi @aviadco11 ,
Could you share the values you are overriding from the default ones? Is your certificate PEM protected? In that case, you need to pass `security.tls.keyPassword`

**Comment by aviadco11** [comment]
[values.txt](https://github.com/bitnami/charts/files/7594836/values.txt)

I had values.txt (is yaml file), and the certificate  isn't protected.

THANK'S. AVIAD

**Comment by kszymans** [comment]
I have exactly the same issue. With autogenerated self signed certificates (`security.tls.autoGenerated`) ES startups normally and uses HTTPS, but wih my own certificate it does shout with the mentioned error.
ES chart version 17.1.0
`
values:
  name: elastic
  security:
    enabled: true
    tls:
      restEncryption: true
      autoGenerated: false
      verificationMode: none
      usePemCerts: true
      master:
        existingSecret: preview-io-tls
      data:
        existingSecret: preview-io-tls
      coordinating:
        existingSecret: preview-io-tls
    elasticPassword: dummy
  master:
    replicas: 1
    persistence:
      enabled: false
  data:
    replicas: 1
    persistence:
      enabled: false
  coordinating:
    replicas: 1
    `

**Comment by migruiz4** [comment]
Hi,

The TLS certificate must contain 3 Keys:
- `tls.crt` including the nodes certificate.
- `tls.key` including the nodes private key.
- `ca.crt` including the CA certificate uses to validate the certs.

Creating the certificate using `kubectl create secret tls` won't work since it doesn't contain the `ca.crt` file.

I would recommend using `kubectl create secret generic` to create a secret with the keys mentioned a above.

**Comment by aviadco11** [comment]
HI,
can you please send the full syntax for this command  **kubectl create secret generic.... ?

**Comment by miguelaeh** [comment]
https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by aviadco11** [comment]
HI, do you have any specific example from generic secret : i'm not sure about the field key...

kubectl create secret generic tls-secret --from-file=tls.crt=/path/to/cc.pem --from-file=tls.key=/path/to/.ssh/ddd.key --from-file=ca.crt=/path/to/chain.crt        ?? do you mean like this ?? thank's

**Comment by migruiz4** [comment]
Hi @aviadco11,

The following example should work
```
kubectl create secret generic secret-elk --from-file=tls.crt=/path/to/my_cert.crt --from-file=tls.key=/path/to/my_cert.key --from-file=ca.crt=/path/to/my_ca.crt
```

You can check the secret generated using: `kubectl get secret secret-elk -o yaml`.

**Comment by aviadco11** [comment]
Ok, thank's .. if i use pem file and not crt file... it's also should be work ? 

Thank's, Aviad

**Comment by migruiz4** [comment]
Sorry if I may have caused some confusion with the file extensions.

`.pem` and `.crt` usually refer to the same, but `.crt` refers to a PEM formatted file containing just the public certificate, while `.pem` may also include the private key.

Same for `.key`, it is a PEM formatted file containing just the private key.

**Comment by aviadco11** [comment]
Thank's.. i did as you say... now I have new error : 
"elasticsearchSecurityException [failed to load SSL configuration [xpack.security.transport.ssl]; nested : ElasticsearchException[failed to initialize SSL keyManager - not permitted to read key file [/opt/bitnami/elasticsearch/config/certs/tls/key]]; nested: accessDeniedExecption..    

Do you have any idea ?

**Comment by migruiz4** [comment]
Could you please share full error?

**Comment by fuergaosi233** [comment]
If I use p12 files, how should I configure them?

**Comment by migruiz4** [comment]
Hi @fuergaosi233,

To provide `.p12` files, create a Kubernetes secret using the command `kubectl create secret generic my_secret_name --from-file=my_keystore.p12=/path/to/my_keystore --from-file=my_truststore.p12=/path/to/my_truststore`.

Then, configure the chart with your secret and your certificate filename:
```yaml
security:
  enabled: true
  elasticPassword: "secret_password"
  tls:
    restEncryption: true
    verificationMode: "full"
    master:
      existingSecret: "my_secret"
    data:
      existingSecret: "my_secret"
    ingest:
      existingSecret: "my_secret"
    coordinating:
      existingSecret: "my_secret"

    keystorePassword: "<PKCS12 keystore pass>"
    truststorePassword: "<PKCS12 truststore pass>"
    keystoreFilename: my_keystore.p12
    truststoreFilename: my_truststore.p12
```

According to [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-settings.html#transport-tls-ssl-settings), Elasticsearch will automatically determine certificates are PKCS12 based on the extension, so make sure that your filename ends with `.p12`:
```
 ssl.keystore.type
    (Static) The format of the keystore file. It must be either jks or PKCS12. If the keystore path ends in ".p12", ".pfx", or ".pkcs12", this setting defaults to PKCS12. Otherwise, it defaults to jks. 
```
