### ISSUE TITLE
mongodb chart ingress for metrics (mongodb-exporter)

### ISSUE THREAD

**Issue by baryluk** [bitnami/charts#8211]
**Which chart**:
`mongodb`

**Is your feature request related to a problem? Please describe.**
It would be really useful to be able to configure ingress for mongodb-exporter, so it can be easily accessed outside of the cluster (with or without rbac proxy).

It is useful when you have prometheus outside of k8s cluster, and it is also useful when developing new rules and alerts, as this allows me to easily run a test instance (i.e. on local machine, or some other staging machine).

I have a rather involved alerting system based on Prometheus and dynamic dependency, that cannot be easily fit into existing Prometheus in the k8s, so I need to ingest Mongo data to it too.

**Describe the solution you'd like**
Configurable ingress for the `mongodb-exporter` (port 9216).

**Describe alternatives you've considered**
Manual port forwarding works, but requires another component, and is fragile.

Scraping from Thanos (i.e. in OKD) is very expensive and cumbersome (it provides REST API for queries, but then it cannot be easily processed on a fly, as it requires JSON parsing, uses a LOT of memory in thanos, and is in general slow), as it does not provide federate API itself.

**Comment by juan131** [comment]
Hi @baryluk 

Exporting metrics outside the cluster is discouraged in terms of security. IMHO this is an option we should not cover in the chart.

Please note that you can achieve your goal using the `extraDeploy` parameter that allows to deploy any extra manifest with the chart (e.g. an extra Ingress rule), see:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#add-extra-deployment-options

**Comment by baryluk** [comment]
@juan131 `extraDeploy` should do the trick. I will check if it works.
