### ISSUE TITLE
Minioclient pod restarting repeatedly

### ISSUE THREAD

**Issue by Bharath4297** [bitnami/charts#8217]
**Additional context**
Minio pod is restarting repeatedly. I read some documents related to this issue, that they mentioned regarding volume issue

storageclass:
  name: manual

can we mention in the above manner?

if so, lemme know the reason for the issue?

**Comment by javsalgar** [comment]
Hi,

Could you let us know the exact steps you took in order to get to the issue? Which values did you modify from the defaults? Which is the Kubernetes platform you are using?

**Comment by Bharath4297** [comment]
Pod miniioclient keeps restarting every couple of hours. but the Pod miniioclient should not reboot.As microservice minioclient is having only one pod for the deployment, restart of that pod will cause service interruption for us. we are using ubuntu.

**Comment by javsalgar** [comment]
Hi,

Do you have any logs that show any error? I would like to reproduce the issue on my side, which are the installation steps you followed?

**Comment by Bharath4297** [comment]
Hii @javsalgar ,

We are not getting any log errors. We are no knowing the exact issue of why the minioclient pod is restarting frequently. We wrote the piece of code in yaml.

**Comment by Bharath4297** [comment]
Hi @javsalgar ,

miniostorageobject:
  port: 9000
  nodePort: 30012
  name: manual
  capacity: 10Gi
  hostpath: "/home/themis/minio/minio_data"
  resources:
    requests:
      storage: 3Gi 

In the above code do you see any kind of misinterpretation?

**Comment by javsalgar** [comment]
Hi,

From my experience, I'd say that the hostPath volume might be causing problems. Probably the permissions in that folder are not compatible with non-root containers. Could you ensure that the folder has write permissions for any random user?

**Comment by Bharath4297** [comment]
Hi javsalgar,

We didn't use any hostpath volume. we use sep for storage.

**Comment by javsalgar** [comment]
Hi,

I don't have much context about this type of storage. Do you know if it is compatible with the `fsGroup` Kubernetes security settings?

**Comment by Bharath4297** [comment]
Hi,

Ok. we actually used ceph storage. No, I dont know regarding that.

**Comment by javsalgar** [comment]
Hi,

My advice would be checking that, as it seems to be an issue with the volume provider.
