### ISSUE TITLE
How can existing secret be used for Ingress SSL certificate with RabbitMQ

### ISSUE THREAD

**Issue by JayCallas** [bitnami/charts#8225]
**Which chart**:
RabbitMQ

**Is your feature request related to a problem? Please describe.**
We already have secrets configured for SSL certificates with out nginx Ingress controller. As far as I can tell, the RabbitMQ chart only supports creating self-signed certs. Looking at the configuration options (and reading through the code in `ingress.yaml` (around line 51) does not seem to show a way to specify an existing secret.

**Describe the solution you'd like**
Specify an existing secret to use for Ingress tls

**Describe alternatives you've considered**
I thought that the `ingress.extraTls` parameter may be useful according to line 54 of `ingress.yaml`, then output is "templated" and I cannot figure out how to specify a value using the `--set` parameter. (We are performing deployments using Azure DevOps and our existing release pipeline does not use `values.yaml`.)

**Comment by marcosbc** [comment]
Hi @JayCallas have you taken a look into the `ingress.selfSigned` parameter in the `values.yaml` file for RabbitMQ? My understanding is that it is what you are asking for: https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L909

**Comment by JayCallas** [comment]
@marcosbc I appreciate the response but your suggestion is not at all what I was referring to. I am **not** looking to create a new certificate. My posting is about how to use an **existing** secret for the certificate. In other words, I want to **pass in** a value to `secretName` on line 51 of `ingress.yaml`.

As a more concrete example, if I run `helm install` with the following (example) parameter `--set tls.existingSecret=my-wildcard-cert`, the `Ingress` output will look like

```
...
spec:
  rules:
   ...
  tls:
    - secretName: my-wildcard-cert

```

**Comment by marcosbc** [comment]
I see, thanks for clarifying @JayCallas. In your case you would need to specify `ingress.extraTls`. I'm not sure what is your problem, but this is an example of how you would set it via CLI:

```
--set 'ingress.extraTls[0].secretName=rabbitmq.local-tls' --set 'ingress.extraTls[0].hosts[0]=rabbitmq.local'
```
