### ISSUE TITLE
How to rename the pgpool service

### ISSUE THREAD

**Issue by ralleman-quasarsat** [bitnami/charts#8226]
Is there any way to change the pgpool kubernetes service name in postgresql-ha from **postgresql-postgresql-ha-pgpool**.<namespace>.... to something a little more friendly, like **customer**.<namespace>....?

**Comment by juan131** [comment]
Hi @ralleman-quasarsat 

Yes! Please take a look to the `fullnameOverride` parameter:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L55

**Comment by ralleman-quasarsat** [comment]
Thanks.

It's gotten me part way there: **customer-pgpool.postgresql.svc.cluster.local**

Do you know how to get rid of the **-pgpool** part?

**Comment by juan131** [comment]
You cannot get rid of that part @ralleman-quasarsat

In any case, please note the service name is just `customer-pgpool`. The rest of the fields that create the FQDN are the namespace you're using (`postgresql"`), plus `svc`, plus the cluster domain (`cluster.local`).
