### ISSUE TITLE
[mariadb-galera] bash: /opt/bitnami/scripts/mariadb-galera/entrypoint.sh: No such file or directory

### ISSUE THREAD

**Issue by jav333** [bitnami/charts#8229]
**Which chart**:
bitnami/mariadb-galera

**Describe the bug**
I don't know this is bug or not.

**To Reproduce**

Centos version:
![image](https://user-images.githubusercontent.com/79013136/143200131-01242bd2-3f7d-436f-b8e7-ec2b695c39a9.png)
Docker version:
![image](https://user-images.githubusercontent.com/79013136/143200067-30798ba0-7999-4d8e-8a65-06c4ee2412b0.png)

We are using Gluserfs storage for PV:
![image](https://user-images.githubusercontent.com/79013136/143211534-76e765d3-a592-4a75-add5-814ba382107d.png)
![image](https://user-images.githubusercontent.com/79013136/143211586-26467c2b-eb18-4f16-9352-8d085e1ce9a8.png)
![image](https://user-images.githubusercontent.com/79013136/143211647-35ac9fa0-60dd-49ff-99fc-e4109f9e45ca.png)
![image](https://user-images.githubusercontent.com/79013136/143211673-ebbb89c1-c87b-4de4-8c08-c244ae5653ec.png)

You can download the file here: vaules-production.yaml: https://files.fm/u/xk7hq8s4r

Helm install galera -f values-production.yaml bitnami/mariadb-galera
![image](https://user-images.githubusercontent.com/79013136/143198724-a2e6f6c9-8e46-47b4-8101-8064caab19c2.png)

You can download the file vaules-production.yaml: https://files.fm/u/xk7hq8s4r

The status is CrashLoopBackOff
![image](https://user-images.githubusercontent.com/79013136/143198901-2e56b77e-4710-4e8a-b17a-717f94002638.png)

Describe showing back-off
![image](https://user-images.githubusercontent.com/79013136/143198991-e6178784-f732-4eca-9c20-2fe106733c2b.png)

The node only contain one galera-mariadb-galera-0
![image](https://user-images.githubusercontent.com/79013136/143199063-6177ae1b-4563-4081-9138-501f4caaaa37.png)

Log:
![image](https://user-images.githubusercontent.com/79013136/143199237-938205c0-7757-4e92-a5d8-a8dcad4b62db.png)

**Expected behavior**
no cashback?

**Version of Helm and Kubernetes**:
helm version:
![image](https://user-images.githubusercontent.com/79013136/143198382-378218fb-9f3c-47d5-9dc1-e27c6aaa1723.png)

- Output of `kubectl version`:
k8s version:
![image](https://user-images.githubusercontent.com/79013136/143198441-d527acf6-d51c-48f6-a842-eb62c76f3eff.png)

Thanks!

**Comment by miguelaeh** [comment]
Hi @jav333 ,
I am not sure what could be happening, the `entrypoint.sh` is a file that the image ships inside, you can find it here: https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.6/debian-10/rootfs/opt/bitnami/scripts/mariadb-galera/entrypoint.sh
Maybe you are overriding the content of the scripts directory?
Are you customizing the image in any way?

I cannot fully reproduce your environment since I cannot use glusterfs in our dev cluster

**Comment by leiw324** [comment]
Hello @miguelaeh,

No, I don't know how to customizing the image and not overriding the content of the script.

How can I copy this entrypoint.sh to the the pod?

Thanks

> Hi @jav333 , I am not sure what could be happening, the `entrypoint.sh` is a file that the image ships inside, you can find it here: https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.6/debian-10/rootfs/opt/bitnami/scripts/mariadb-galera/entrypoint.sh Maybe you are overriding the content of the scripts directory? Are you customizing the image in any way?
> 
> I cannot fully reproduce your environment since I cannot use glusterfs in our dev cluster

**Comment by jav333** [comment]
Can someone help?

**Comment by miguelaeh** [comment]
Hi @jav333 ,
It seems you are using a pretty old mariadb-galera image version. Is it possible for you to upgrade it?

**Comment by jav333** [comment]
Hello @miguelaeh ,

Do you mean I have to modify image tag 10.6.5-debian-10-r0 in the values-production.yaml file?

Thanks

**Comment by leiw324** [comment]
OK, I used  tag: 10.6.5-debian-10-r11
But displaying already present on machine ?
![image](https://user-images.githubusercontent.com/33790160/143476226-436d168e-cba7-45e5-8e56-7659711590b1.png)

**Comment by jav333** [comment]
Hello,

I checked log:
mariadb 07:13:34.37 Welcome to the Bitnami mariadb-galera container
mariadb 07:13:34.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
mariadb 07:13:34.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
mariadb 07:13:34.39
mariadb 07:13:34.39 INFO  ==> ** Starting MariaDB setup **
mariadb 07:13:34.49 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 07:13:34.63 INFO  ==> Initializing mariadb database
mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied

About the Permission denied issue, I have searched google, someone said is storage issue, I am using Glusterfs cluster, can someone help?

Thanks

**Comment by miguelaeh** [comment]
Hi @jav333 ,
About the permissions denied issue, you can run an init container to change the volume permissions.

**Comment by leiw324** [comment]
Hello @miguelaeh ,

Can you tech me how to do init container in value file?

Thanks!!

**Comment by leiw324** [comment]
Do you know how to delete pending pvc?
![image](https://user-images.githubusercontent.com/33790160/143679525-99d78317-3c14-46e3-9c4d-ab94d8bfb45e.png)
Thanks

**Comment by miguelaeh** [comment]
Hi @leiw324 ,
you can provide an extra init container using [this](https://github.com/bitnami/charts/blob/eafb5bd5a2cc3aaf04fc1e8ebedd73f420d76864/bitnami/mariadb-galera/values.yaml#L563).

About deleting PVC use `kubectl delete PVC <pvc-name>`.

**Comment by jav333** [comment]
Hello @miguelaeh ,

1. Sorry, I never use extraInitContainers, the below param is correct ?
extraInitContainers:
 - name: permission
   image: bitnami/mariadb-galera
   command: ['chmod 755 /bitnami/mariadb/data']

2. I know the remove pvc command, but that is cannot remove those pvc.
Thanks

**Comment by jav333** [comment]
I just added above extraInitContainers param, but ...

![image](https://user-images.githubusercontent.com/79013136/144022113-b07282b3-b9bb-4d86-b0f4-3920ac0b9a4a.png)
![image](https://user-images.githubusercontent.com/79013136/144022137-fd9d09e5-5422-4dd2-94c4-1a95b3cbd67a.png)
![image](https://user-images.githubusercontent.com/79013136/144022185-1f38b822-84c7-4414-841d-6daee44a2975.png)
![image](https://user-images.githubusercontent.com/79013136/144022217-bf673b8f-b25f-42b5-82ec-8a04a5b11064.png)
![image](https://user-images.githubusercontent.com/79013136/144023409-0f2f25f0-5727-42c3-a096-116325d76b33.png)

The bitnami-mysql-pvc  is bounding, why 0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.?


Thanks

**Comment by miguelaeh** [comment]
Hi @jav333 ,
That is not an issue with the chart. You should check why your K8s volume provisioning is not working as expected.

**Comment by jav333** [comment]
Hi @miguelaeh ,

Our glusterfs is not provisioniog, thanks,.
