### ISSUE TITLE
[bitnami/grafana] Fix volumePermissions initContainer

### ISSUE THREAD

**Issue by toonalbers** [bitnami/charts#8231]
**Which chart**:
bitnami/grafana  (8.2.5)

~~**Is your feature request related to a problem? Please describe.**~~
**Describe the bug**
Since the Bitnami containers (by default, but rightfully so) don't run as root, containers can have trouble writing to mounted volumes. The recommended approach is to set the `securityContext` [[0]](https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/) [[1]](https://github.com/bitnami/charts/issues/5568#issuecomment-897419540). However, there are cases where this may not work, which is why many Bitnami charts have implemented a `volumePermissions` template, creating an (root) initContainer to write the appropriate file permissions [[2]](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#solve-issue-222).

Two issues are present:
1. The volumePermissions template looks up `.Values.containerSecurityContext.runAsUser` and `.Values.podSecurityContext.fsGroup` but these do not exist in the Grafana values.yaml.
2. The initContainer tries to `chown` the grafana directory but fails if it does not exist.

~~**Describe the solution you'd like**~~
~~Please also add the `volumePermissions`  to the Grafana chart. It can probably be copied from other charts like [mongodb](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml#L92) and [influxdb](https://github.com/bitnami/charts/blob/5c9f6e3e46921dcc2aead5676a8b9dcb8e62ece8/bitnami/influxdb/templates/influxdb/deployment-standalone.yaml#L58).~~

~~**Describe alternatives you've considered**~~
~~Only using `securityContext` is not sufficient as not all platforms and storage classes support it (which is what I am running into).~~

**Comment by Mauraza** [comment]
Hi @toonalbers,

Did you try with `runAsUser`? but we are open to contributions, would you be open to contributing to this change via a PR? We'd be glad to review!.

**Comment by toonalbers** [comment]
Hi @Mauraza! Yes, however `runAsUser` is not sufficient in this case. First I made the mistake of using an older version of the chart.. The latest version has `volumePermissions` however it was not working as intended. I have opened PR #8251 to fix it, but please see the possible drawbacks section and let me know what you think.

**Comment by miguelaeh** [comment]
Hi @toonalbers ,
Thank you for the PR we will review it and continue the conversation there

**Comment by nc-ruth** [comment]
Hi @miguelaeh,
How far are you with the review process?
