### ISSUE TITLE
[bitnami/etcd] Etcd pods failing at readiness probe script (healthcheck.sh)

### ISSUE THREAD

**Issue by jas02** [bitnami/charts#8233]
**Which chart**:
etcd-6.10.3

app version 3.5.1

**Describe the bug**
After the helm chart installation:

```
helm install etcd bitnami/etcd -n <namespace> -f etcd-values.yaml
```
Pod(s) are deployed and started, but readiness probe is failing repeatably, so the pod never fully starts.

Problem is, that health check script `/opt/bitnami/scripts/etcd/healthcheck.sh` is returning empty string on lines:

```
host="$(parse_uri "$ETCD_ADVERTISE_CLIENT_URLS" "host")"
port="$(parse_uri "$ETCD_ADVERTISE_CLIENT_URLS" "port")"
```

so, at the end of the script, following error is raised:

```
{"level":"warn","ts":1637757853.7868419,"logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003b0a80/:","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp :0: connect: connection refused\""}
: is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
etcd 12:44:13.79 ERROR ==> Unhealthy endpoint!
```

I guess, that `parse_uri()` in `/opt/bitnami/scripts/libnet.sh` doesn't support multiple values in ETCD_ADVERTISE_CLIENT_URLS environment variable. 

Content of my $ETCD_ADVERTISE_CLIENT_URLS env variable is as follows.

```
http://etcd-etcd-0.cortex-etcd-headless.etcd-prod.svc.eng-prod.local:2379,http://etcd-etcd.etcd-prod.svc.eng-prod.local:2379
```

When I change the env variable like this:

```
http://etcd-etcd-0.etcd-etcd-headless.etcd-prod.svc.eng-prod.local:2379
```

everything works.

I don't know, why there is second value, which is etcd k8s service URL. 

**To Reproduce**

1. `helm install etcd bitnami/etcd -n <namespace> -f etcd-values.yaml`

**Expected behavior**
parse_uri would parse ETCD_ADVERTISE_CLIENT_URLS variable successfully.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by javsalgar** [comment]
Hi,

It seems to me that, if the variable has more than one URL, it should be enough to parse the first one, is that correct. Maybe in the script we should split first the string and then do the rest of the instructions. Thoughts on this?

**Comment by jas02** [comment]
@javsalgar Created [PR](https://github.com/bitnami/bitnami-docker-etcd/pull/25) that would handle this scenario nicely. We'll see what maintainers have to say 🤔

**Comment by thangamani-arun** [comment]
This issue still open. Consider merging the [PR#25 ](https://github.com/bitnami/bitnami-docker-etcd/pull/25)

**Comment by awuetz** [comment]
hi does anyone know how far this fix is, I ran also into this issue, with the very same message and behavior.

@jas02 how did you workaround this? As I understood from your message you did set the `ETCD_ADVERTISE_CLIENT_URLS` to a single value. But if I try this using the helm `extraEnvVars` it seems impossible to me to change it this way..

**Comment by javsalgar** [comment]
Hi,

I reopened this PR https://github.com/bitnami/bitnami-docker-etcd/pull/25 in case @jas02 (or someone else ) can continue with it

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
