### ISSUE TITLE
BUG: Wordpress chart error when update chart value

### ISSUE THREAD

**Issue by nvthuong1996** [bitnami/charts#8243]
**Which chart**:
wordpress 12.2.0

**Describe the bug**
When i install wordpress chart with out provide mariadb password, 1 random password will generate . after it store in wordpress-xxxxx-mariadb secret
=> But when i change chart value and update chart 
=> secret password change to random other value 
=> but when secret change, mariadb pod don't  restart 
=> If for some reason mariadb restarts (ex: restart node) 
=> maridb can't start because password change
![image](https://user-images.githubusercontent.com/24992586/143516473-4a80e395-1be4-4c84-922e-9509493b492e.png)

**Expect**
Password generated once when creating chart and don't change when update chart

**Comment by miguelaeh** [comment]
Hi @nvthuong1996 ,
You should have seen some messages warning about that when performing the `helm upgrade`. See [this](https://github.com/bitnami/charts/blob/9860242c4ceb2da203bbad31043bd60eba4374a7/bitnami/wordpress/templates/NOTES.txt#L96)

**Comment by nvthuong1996** [comment]
I use lens to manage my cluster. i don't understand how lens perform. But i see secret value change when i update release.
After mariadb will error when it restart

https://user-images.githubusercontent.com/24992586/143559781-1f8456de-4421-4749-ba21-46a59bd3303d.mp4

![image](https://user-images.githubusercontent.com/24992586/143560495-f8e70640-9d71-45fa-a224-350fec8e90a8.png)


I expect mariadb secret password don't change when i update release. I can do that by setting the password value for mariadb chart. but it will error when i don't provide password value

**Comment by miguelaeh** [comment]
Hi @nvthuong1996 ,
I am not familiar with lens, our charts force the users to provide the passwords in the upgrades to avoid changing the secrets, since the passwords are persisted, if you change the secret it won't match the actual password.

> I expect mariadb secret password don't change when i update release. I can do that by setting the password value for mariadb chart. but it will error when i don't provide password value

So, you need to pass the old passwords

**Comment by nvthuong1996** [comment]
thank you.
