### ISSUE TITLE
[bitnami/mariadb-galera] node failure: donor hits "Access denied for mariabackup"

### ISSUE THREAD

**Issue by matpen** [bitnami/charts#8256]
**Which chart**:
name = `bitnami/mariadb-galera`
version = `6.0.1`

**Describe the bug**
After a node failure, the cluster cannot recover because WSREP syncing fails.

**To Reproduce**

1. [Install](https://bitnami.com/stack/mariadb-galera/helm) the chart with default values, except `replicaCount`: e.g. `helm install galera bitnami/mariadb-galera --set replicaCount=2`
2. Insert some data into the cluster (add databases, etc);
3. Wait for some time (eg. 1 week): this seems not reproducible on freshly installed clusters, but I did manage to replicate on two independent production clusters (totally different kubernetes clusters);
3. Simulate a node failure by scaling down the `StatefulSet` and removing the volume: 
```
kubectl scale sts galera-mariadb-galera --replicas=1
kubectl delete pvc data-galera-mariadb-galera-1 # this removes the PV, too (checked)
kubectl scale sts galera-mariadb-galera --replicas=2
```
4. The failed replica enters a crash loop, which can be checked with `kubectl get pod`
```
NAME                      READY   STATUS             RESTARTS   AGE
galera-mariadb-galera-0   1/1     Running            0          15m32s
galera-mariadb-galera-1   0/1     CrashLoopBackOff   4          3m36s
```
(see below for further investigation results)

**Expected behavior**
Expected the failed node to re-sync with the cluster automatically.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T02:34:11Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I managed to collect the logs from two independent production clusters. In the **donor** we see the `Access denied` entry
```
WSREP_SST: [INFO] Streaming with mbstream (20211128 17:57:09.855)
WSREP_SST: [INFO] Using socat as streamer (20211128 17:57:09.860)
WSREP_SST: [INFO] Using '/opt/bitnami/mariadb/tmp/tmp.Bh5w0LMuYV' as mariabackup temporary directory (20211128 17:57:09.872)
WSREP_SST: [INFO] Using '/tmp/tmp.1Y8o8s6jCx' as mariabackup working directory (20211128 17:57:09.877)
WSREP_SST: [INFO] Streaming GTID file before SST (20211128 17:57:09.882)
WSREP_SST: [INFO] Evaluating '/opt/bitnami/mariadb//bin/mbstream' -c 'xtrabackup_galera_info' | socat -u stdio TCP:10.0.1.190:4444; RC=( ${PIPESTATUS[@]} ) (20211128 17:57:09.887)
WSREP_SST: [INFO] Sleeping before data transfer for SST (20211128 17:57:09.894)
2021-11-28 17:57:11 0 [Note] WSREP: (58c80db0-8ccd, 'tcp://0.0.0.0:4567') turning message relay requesting off
WSREP_SST: [INFO] Streaming the backup to joiner at 10.0.1.190:4444 (20211128 17:57:19.899)
WSREP_SST: [INFO] Evaluating /opt/bitnami/mariadb//bin/mariabackup --defaults-file='/opt/bitnami/mariadb/conf/my.cnf'   --backup --no-version-check --databases-exclude='lost+found'  --tmpdir='/opt/bitnami/mariadb/tmp/tmp.Bh5w0LMuYV'  --innodb-data-home-dir='./' --log-bin='mysql-bin' --user='mariabackup' --socket='/opt/bitnami/mariadb/tmp/mysql.sock' --galera-info --stream=mbstream --target-dir='/tmp/tmp.1Y8o8s6jCx' --datadir='/bitnami/mariadb/data' --mysqld-args '--basedir=/opt/bitnami/mariadb' '--pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid' '--wsrep-node-name=galera-mariadb-galera-1' '--wsrep-node-address=10.0.1.142' '--wsrep-cluster-name=galera' '--wsrep-cluster-address=gcomm://' '--wsrep-sst-method=mariabackup' '--wsrep-sst-auth=mariabackup:<hidden>' 2> '/bitnami/mariadb/data/mariabackup.backup.log' | socat -u stdio TCP:10.0.1.190:4444; RC=( ${PIPESTATUS[@]} ) (20211128 17:57:19.902)
2021-11-28 17:57:19 20 [Warning] Access denied for user 'mariabackup'@'localhost' (using password: YES)
WSREP_SST: [ERROR] mariabackup finished with error: 1.  Check syslog or '/bitnami/mariadb/data/mariabackup.backup.log' for details (20211128 17:57:19.917)
WSREP_SST: [ERROR] Cleanup after exit with status:22 (20211128 17:57:19.921)
```
and in the **joiner** the process fails:
```
2021-11-28 17:33:00 0 [Warning] WSREP: 1.0 (galera-mariadb-galera-1): State transfer to 0.0 (galera-mariadb-galera-2) failed: -22 (Invalid argument)
2021-11-28 17:33:00 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_group.cpp:gcs_group_handle_join_msg():1170: Will never receive state. Need to abort.
2021-11-28 17:33:00 0 [Note] WSREP: gcomm: terminating thread
2021-11-28 17:33:00 0 [Note] WSREP: gcomm: joining thread
2021-11-28 17:33:00 0 [Note] WSREP: gcomm: closing backend
2021-11-28 17:33:00 0 [ERROR] WSREP: Process completed with error: wsrep_sst_mariabackup --role 'joiner' --address '10.0.0.41' --datadir '/bitnami/mariadb/data/' --defaults-file '/opt/bitnami/mariadb/conf/my.cnf' --parent '1' --binlog 'mysql-bin' --mysqld-args --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid --wsrep-node-name=galera-mariadb-galera-2 --wsrep-node-address=10.0.0.41 --wsrep-cluster-name=galera --wsrep-cluster-address=gcomm://galera-mariadb-galera-headless.mariadb-galera.svc.cluster.local --wsrep-sst-method=mariabackup --wsrep-sst-auth=mariabackup:<hidden> --old-mode=: 2 (No such file or directory)
2021-11-28 17:33:00 0 [ERROR] WSREP: Failed to read uuid:seqno and wsrep_gtid_domain_id from joiner script.
```

Full logs attached: [donor](https://github.com/bitnami/charts/files/7614234/scratch-kPslbi.txt) and [joiner](https://github.com/bitnami/charts/files/7614230/scratch-gwxmYg.txt).

**Comment by miguelaeh** [comment]
Hi @matpen ,
I think this could be related to the fact that you are deleting the volume. If you just delete the node, without deleting the volume, what happens?

**Comment by matpen** [comment]
Thank you, @miguelaeh,

This is definitely related to deleting the volume. If the volume is not deleted, the service restarts correctly.
However, the scenario of the volume going lost (eg. the whole instance on where it sits crashes, or hardware failure) must still be covered in an HA setup.

**Comment by miguelaeh** [comment]
Hi @matpen ,
The volume management cannot be in hands of the chart. The administrator of the cluster must handle it in the most convenient way. If there is hardware failure and your cluster goes down, it does not imply that the volume will be deleted, once the node is up again, unless you stored your volumes in memory, the data should continue there.

**Comment by matpen** [comment]
Perhaps I was not clear in my message above. The chart very well manages the volumes, by setting up the PVC (PersistentVolumeClaims): see [the related values in the chart](https://github.com/bitnami/charts/blob/fe5fa10334febb84a5a0fd31550121618dd2a51e/bitnami/mariadb-galera/values.yaml#L523-L559). Therefore, in the case of the simulated "instance crash" above, this is the sequence of events:
* the cluster runs normally;
* one machine crashes completely and goes offline, destroying the volume and the container in the process;
* the cluster autoscaler notices this, and brings up a completely new machine;
* because of the PVC mentioned above, a new (empty) volume is provisioned automatically by k8s;
* k8s also restarts the container in the new node, which therefore starts with an empty volume.

> In the case your volumes live in a k8s cluster node, if there is a hardware failure and your cluster goes down, it does not imply that the data will be deleted, once the node is up again, unless you stored your volumes in memory, the data should continue there

The scenario I just described would entail that the new volume is empty. In any case, let me describe another plausible scenario: where the admin simply decides to scale up the StatefulSet, and add a new replica. In this case, a very similar process happens:
* the new replica is associated with a new PVC;
* because of the PVC, a new empty volume is provisioned;
* the container starts with this empty state, and therefore needs to sync with the rest of the Galera cluster.

My question is therefore: why does MariaDB complain about missing permissions (`Access denied`)? Can someone familiar with the chart suggest a way for me to check these permissions (e.g. manually login with those credentials)?

**Comment by miguelaeh** [comment]
Hi @matpen ,
I think you are describing two different things.
1. The volumes management. Volumes do not have to live in the K8s cluster nodes. For example, if you use AWS, the volumes are provided by lsb so they can survive a cluster disaster.
2. The mariadb-galera cluster escalation. In this case, the image ships the [logic](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/5ccce2f74f107b269e8ab5e61df33adbc073c978/10.6/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L198) to join an existing cluster or create a new one in case it already exists.

Apart from that, the passwords are stored in secret. Is it possible that, your secret changed the password value before scaling the cluster? In that case, the password for the new replica will differ from the password of the rest of the replicas.

**Comment by matpen** [comment]
@miguelaeh 

> I think you are describing two different things

The two things are related in the context of the problem I am describing. 

> The volumes management. Volumes do not have to live in the K8s cluster nodes. For example, if you use AWS, the volumes are provided by lsb so they can survive a cluster disaster.

k8s supports various different environments, even bare metal. For example, the volume may be provisioned as a local director, or as OpenEBS volume. In these cases (and many more) the volume will be lost. If we reason along the line that "AWS protects your from disaster" then why do we need HA at all?

In fact, in my specific case (my cluster is on AWS), the volume somehow became corrupted, and therefore I had to replace it. I expected the sync to happen automatically, but this was not the case.

In any case, we can ignore this point, if you think it makes things difficult. I was just explaining the condition I am in, hoping to provide as much information as possible, so that it is easier to reproduce.

The point is, there is a (not necessarily new) cluster node which suddenly has an empty volume. This seems to me as a perfectly reasonable case to be considered in a HA setup.

> The mariadb-galera cluster escalation. In this case, the image ships the logic to join an existing cluster or create a new one in case it is the bootstrap node.

This is the point where it fails for me, and where I hope to get some help from someone who knows the internals of the helm chart and/or the Galera image better than me.

> Apart from that, the passwords are stored in secrets. Is it possible that, your secret changed the password value before scaling the cluster? In that case, the password for the new replica will differ from the password of the rest of the replicas.

If that happened, it definitely was done automatically by the chart. That is why I was investigating [these settings](https://github.com/bitnami/charts/blob/fe5fa10334febb84a5a0fd31550121618dd2a51e/bitnami/mariadb-galera/values.yaml#L246-L257), but I cannot find much information about it.
Do you have any idea on how I can test the credentials (I could find them in the k8s secret) and/or how exactly I should interpret [this sentence](https://github.com/bitnami/charts/blob/fe5fa10334febb84a5a0fd31550121618dd2a51e/bitnami/mariadb-galera/values.yaml#L254-L255)?

**Comment by javsalgar** [comment]
Hi,

The mariadb-galera chart has a diagnostic mode that would deploy all nodes with a sleep command. That would help you to manually debug and test the issues that are happening. Did you try it? It is set with diagnosticMode.enabled=true

**Comment by matpen** [comment]
Hi Javier,

thanks for your input. I did not know about the `diagnosticMode`, but that can indeed come in handy. However, I am not sure how to leverage it in this case: the donor node stays up, so it is no problem to exec into that and check the `mariabackup` credentials (which of course do work). The joiner does CrashLoop, but I believe this is due to the fact that it is not receiving updates from the donor.

Here is my hypothesis so far on what happened:
* the donor backed up the data at some point in time using the original `mariabackup` credentials;
* the password of `mariabackup` was changed by the chart after the backup was taken: the reason could be a chart upgrade and [the setting](https://github.com/bitnami/charts/blob/fe5fa10334febb84a5a0fd31550121618dd2a51e/bitnami/mariadb-galera/values.yaml#L246-L257) I mentioned earlier;
* during sync the donor node is trying to read the backup: I see no reason for this, because the donor node did not crash and is up-to-date;
* the sync therefore fails because the donor node has a new password, not the same with which the backup was taken: this of course sounds weird, because I am wondering where the old password is stored (I have checked the auth against the DB, the k8s secret, and even the [wsrep_sst_auth](https://mariadb.com/kb/en/mariabackup-sst-method/): they all match the "new" password).

Not having enough experience with Galera and/or the chart, I am out of ideas. Does the above pattern even make sense?

**Comment by juan131** [comment]
Hi @matpen 

If your hypothesis is right and the issue is that the password changed during the upgrade, there's a workaround:

As it's explained in [our Troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases), you can run a `helm rollback` to recover the "original" password that was randomly generated by Helm during the 1st chart installation.

**Comment by matpen** [comment]
Thank you, @juan131. I will give it a shot, and report back if the issue persists.

**Comment by matpen** [comment]
This is happening again.

The cluster in question is a 3-node galera cluster, setup as per OP. Node 0 is crash-looping with an error very similar (if not identical) to the one described in this issue. [Attached](https://github.com/bitnami/charts/files/7706952/scratch-HlOsvv.txt) is the complete crash log.

From which I would like to highlight the following snippet:
```
[...]
2021-12-13 20:32:42 0 [Note] WSREP: Member 2.0 (galera-mariadb-galera-0) requested state transfer from '*any*'. Selected 0.0 (galera-mariadb-galera-1)(SYNCED) as donor.
2021-12-13 20:32:42 0 [Note] WSREP: Shifting PRIMARY -> JOINER (TO: 65715)
2021-12-13 20:32:42 2 [Note] WSREP: Requesting state transfer: success, donor: 0
2021-12-13 20:32:42 2 [Note] WSREP: Resetting GCache seqno map due to different histories.
[...]
2021-12-13 20:32:52 0 [ERROR] WSREP: Process completed with error: wsrep_sst_mariabackup --role 'joiner' --address '10.0.0.26' --datadir '/bitnami/mariadb/data/' --defaults-file '/opt/bitnami/mariadb/conf/my.cnf' --parent '1' --binlog 'mysql-bin' --mysqld-args --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid --wsrep-node-name=galera-mariadb-galera-0 --wsrep-node-address=10.0.0.26 --wsrep-cluster-name=galera --wsrep-cluster-address=gcomm://galera-mariadb-galera-headless.mariadb-galera.svc.cluster.local --wsrep-sst-method=mariabackup --wsrep-sst-auth=mariabackup:<redacted> --old-mode=: 2 (No such file or directory)
2021-12-13 20:32:52 0 [ERROR] WSREP: Failed to read uuid:seqno and wsrep_gtid_domain_id from joiner script.
[...]
2021-12-13 20:32:52 2 [ERROR] WSREP: Application state transfer failed. This is unrecoverable condition, restart required.
```

So apparently this time around the problem is `(No such file or directory)`. However, I cannot seem to find further information on what file (or directory) may be missing.

Since I do not see any permission problems this time, this seems to contradict [my hypothesis](https://github.com/bitnami/charts/issues/8256#issuecomment-989715754). Also, I can confirm that the password used for `--wsrep-sst-auth` is the same I manually specified in the chart.

Can someone please suggest some debugging steps to figure out what the problem can be? I am out of ideas.

**Comment by matpen** [comment]
Sorry, I wrote too soon. Inspecting the donor (see [attached log](https://github.com/bitnami/charts/files/7707034/scratch-dNkxsy.txt)) reveals the same `Access denied` problem, and also an `Invalid argument`:

```
[...]
WSREP_SST: [INFO] Streaming the backup to joiner at 10.0.0.26:4444 (20211213 21:04:44.384)
WSREP_SST: [INFO] Evaluating /opt/bitnami/mariadb//bin/mariabackup --defaults-file='/opt/bitnami/mariadb/conf/my.cnf'   --backup --no-version-check --databases-exclude='lost+found'  --tmpdir='/opt/bitnami/mariadb/tmp/tmp.e4BHW4zRNt'  --innodb-data-home-dir='./' --log-bin='mysql-bin' --user='mariabackup' --socket='/opt/bitnami/mariadb/tmp/mysql.sock' --galera-info --stream=mbstream --target-dir='/tmp/tmp.LH3EUUp3Yu' --datadir='/bitnami/mariadb/data' --mysqld-args '--basedir=/opt/bitnami/mariadb' '--pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid' '--wsrep-node-name=galera-mariadb-galera-1' '--wsrep-node-address=10.0.1.88' '--wsrep-cluster-name=galera' '--wsrep-cluster-address=gcomm://galera-mariadb-galera-headless.mariadb-galera.svc.cluster.local' '--wsrep-sst-method=mariabackup' '--wsrep-sst-auth=mariabackup:<redacted>' '--old-mode=' 2> '/bitnami/mariadb/data/mariabackup.backup.log' | socat -u stdio TCP:10.0.0.26:4444; RC=( ${PIPESTATUS[@]} ) (20211213 21:04:44.387)
2021-12-13 21:04:44 184156 [Warning] Access denied for user 'mariabackup'@'localhost' (using password: YES)
WSREP_SST: [ERROR] mariabackup finished with error: 1.  Check syslog or '/bitnami/mariadb/data/mariabackup.backup.log' for details (20211213 21:04:44.410)
WSREP_SST: [ERROR] Cleanup after exit with status:22 (20211213 21:04:44.413)
[...]
2021-12-13 21:04:44 0 [Note] WSREP: Server status change donor -> joined
2021-12-13 21:04:44 0 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
2021-12-13 21:04:44 0 [ERROR] WSREP: Command did not run: wsrep_sst_mariabackup --role 'donor' --address '10.0.0.26:4444/xtrabackup_sst//1' --local-port '3306' --socket '/opt/bitnami/mariadb/tmp/mysql.sock' --datadir '/bitnami/mariadb/data/' --defaults-file '/opt/bitnami/mariadb/conf/my.cnf' --gtid '5397831d-507e-11ec-b9bb-e70e5db89b6b:65890' --gtid-domain-id '0' --binlog 'mysql-bin' --mysqld-args --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid --wsrep-node-name=galera-mariadb-galera-1 --wsrep-node-address=10.0.1.88 --wsrep-cluster-name=galera --wsrep-cluster-address=gcomm://galera-mariadb-galera-headless.mariadb-galera.svc.cluster.local --wsrep-sst-method=mariabackup --wsrep-sst-auth=mariabackup:<redacted> --old-mode=
2021-12-13 21:04:44 0 [Note] WSREP: Donor monitor thread ended with total time 10 sec
2021-12-13 21:04:44 0 [Warning] WSREP: 0.0 (galera-mariadb-galera-1): State transfer to 1.0 (galera-mariadb-galera-0) failed: -22 (Invalid argument)
2021-12-13 21:04:44 0 [Note] WSREP: Shifting DONOR/DESYNCED -> JOINED (TO: 65890)
[...]
```

Again though, the password printed in the logs is the correct one. How can I recover from this situation? Is there a way to manually test whatever the sync process is doing (eg. trying authentication or backup) and to get to the bottom of this?

**Comment by juan131** [comment]
Hi @matpen 

Do the passwords set in the env. variables `MARIADB_ROOT_PASSWORD`, `MARIADB_PASSWORD` and `MARIADB_GALERA_MARIABACKUP_PASSWORD` match the values in the `galera-mariadb-galera` secret?

> lso, I can confirm that the password used for --wsrep-sst-auth is the same I manually specified in the chart.

Is it the one you specified during the 1st installation of the chart, or is it the same one you specified when upgrading the chart?

**Comment by matpen** [comment]
Thank you for your input, @juan131. I just double checked and

* `MARIADB_ROOT_PASSWORD`: matches the secret, and login as root works with it;
* `MARIADB_PASSWORD`: is unset, which **does not** match the secret (which has a value, different from `MARIADB_ROOT_PASSWORD`);
* `MARIADB_GALERA_MARIABACKUP_PASSWORD`: matches the secret, the logs, and is equal to the password I manually set into the chart while upgrading;

Not sure whether the state of `MARIADB_PASSWORD` is correct, but if I understand [the docs](https://github.com/bitnami/bitnami-docker-mariadb#creating-a-database-user-on-first-run) correctly, this is only used to create a database on first run (which I disabled in the chart). `MARIADB_PASSWORD_FILE` is also unset.

**Comment by juan131** [comment]
Hi @matpen 

> Not sure whether the state of MARIADB_PASSWORD is correct, but if I understand the docs correctly, this is only used to create a database on first run (which I disabled in the chart). MARIADB_PASSWORD_FILE is also unset.

Yes, that's correct.

> `MARIADB_GALERA_MARIABACKUP_PASSWORD`: matches the secret, the logs, and is equal to the password I manually set into the chart while upgrading...

This is what worries me... It's equal to the password you manually set when upgrading but it could be different to the one you set when installing the chart for the 1st time. If that's the case, that's the reason why you find the error below:

```
Access denied for user 'mariabackup'@'localhost' (using password: YES)
```

**Comment by matpen** [comment]
> This is what worries me... It's equal to the password you manually set when upgrading but it could be different to the one you set when installing the chart for the 1st time.

Indeed that is what seems to have happened. I will summarize the situation and my understanding, in the hope that it helps someone who may have the same problem in the future:

1. During my initial setup I did **not** supply a password for user `mariabackup` using **these settings**: this was a mistake, because the chart will by default generate a random password, which will **change at every chart upgrade**;
2. Unaware of the risk, I upgraded the chart once: this worked well on the surface, but behind the scenes the chart only updates the **image environment** and the **kubernetes secret**; it will **not** update the credentials of the **mysql user**, which therefore is unable to login;
3. The problem emerges if one of the nodes crashes, and when it comes back up, tries to synchronize with the rest of the cluster: the cluster will select a "healthy" node (called "donor") to provide the up-to-date database state to the node which is attempting the sync (called "joiner"); however, to provide the database state, the donor will need the credentials of `mariabackup`, which no longer works. The result is that the joiner crash-loops forever, and the donor is unable to help (it will log an `Access denied` error similar to the one in the [previous comment](https://github.com/bitnami/charts/issues/8256#issuecomment-994691661))

The workaround:
1. get a shell into each cluster node: (`kubectl exec ... -- bash`)
2. print the current value of the `mariabackup` password: (`echo $MARIADB_GALERA_MARIABACKUP_PASSWORD`)
3. login as root into mysql: `mysql -u root -p"$MARIADB_ROOT_PASSWORD"`
4. change the password for the `mariabackup` user to the value obtained at step 2: `set password for 'mariabackup'@'localhost' = password('...');` 
5. test that it worked: `mysql -u mariabackup -p"$MARIADB_GALERA_MARIABACKUP_PASSWORD"`
6. after the above, the joiners should automatically resync with the cluster and exit the crash-loop

I would also dare to suggest a few solutions to the chart maintainers (whom I hereby thank for the support in this issue, especially @juan131 for his last comment), in order of preference:
1. on chart upgrade, automatically update of the MariaDB system (i.e. change the credentials of the `mariabackup` user, in similar way as I did in my workaround);
2. if the previous is not possible, make the [galera.mariabackup.password](https://github.com/bitnami/charts/blob/fe5fa10334febb84a5a0fd31550121618dd2a51e/bitnami/mariadb-galera/values.yaml#L253) setting mandatory: it is very dangerous to not supply one, as explained above;
3. if the previous is not possible / desired, at least reformulate the [comments](https://github.com/bitnami/charts/blob/fe5fa10334febb84a5a0fd31550121618dd2a51e/bitnami/mariadb-galera/values.yaml#L246-L257) in the chart and in the docs, by providing a big warning and the explanation that not supplying a password is not suitable for production.

**Comment by juan131** [comment]
Hi @matpen 

I'm very glad you were able to solve the issue by manually changing the `mariabackup` password exec'ing into the container. Thanks so much for sharing the steps you followed by the way.

Thanks also for the solutions you shared. We know this is a very common issue that users tend to commit, and that's why did several initiatives to avoid it such as:

- Including a warning in the [chart installation notes](https://github.com/bitnami/charts/blob/master/bitnami/mariadb-galera/templates/NOTES.txt#L77) to warn about it.
- Include a specific section about this topic in the [Troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/).
- In some charts the "helm upgrade" fails throwing an error when it detects it's missing an expected password (unfortunately "MariaDB Galera" chart doesn't include this yet). For instance, the Redis chart includes this as you can reproduce it following the steps below:

```console
$ helm install redis bitnami/redis
(...)
$ helm upgrade redis bitnami/redis
Error: UPGRADE FAILED: execution error at (redis/templates/NOTES.txt:191:4):
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.password' must not be empty, please add '--set auth.password=$REDIS_PASSWORD' to the command. To get the current value:

        export REDIS_PASSWORD=$(kubectl get secret --namespace "default" redis -o jsonpath="{.data.redis-password}" | base64 --decode)
```

**Comment by matpen** [comment]
> Including a warning in the chart installation notes to warn about it.

Missed that, probably because I am managing the chart via [Terraform](https://www.terraform.io/).

> Include a specific section about this topic in the Troubleshooting guide.

The problem with the "Troubleshooting guides" is that they are used when troubleshooting... in this case, that was too late. That is why option 3 above suggested some bigger warning in the [setup guide](https://github.com/bitnami/charts/issues/8256#issuecomment-995893306).

> In some charts the "helm upgrade" fails throwing an error when it detects it's missing an expected password

Yepp, that is a nice feature. The `RabbitMQ` chart does the same.

**Comment by juan131** [comment]
Hi @matpen 

I just sent a PR to include this feature in MariaDB Galera. After that, it'll work as Redis or RabbitMQ and it'll prevent users to upgrade their releases if they don't provide the required passwords.

**Comment by matpen** [comment]
This is very, very valuable, @juan131: thank you so much for working on this!

On my side, I made sure that a fixed password is always provided through the IaC stack: but I am sure you just saved lots of trouble to many future users. Keep up the good work!

**Comment by juan131** [comment]
Thank you very much!
