### ISSUE TITLE
[kube-prometheus] support multiple prometheus instances in two namespaces in one cluster

### ISSUE THREAD

**Issue by niv0** [bitnami/charts#8265]
**Which chart**:
kube-prometheus, version 6.4.1

**Is your feature request related to a problem? Please describe.**
I am trying to install two prometheus charts on two namespaces, e.g. namespaceA and namespaceB. Promehteus operators are not configured to manage only prometheus and alertmanager pods in their namespaces, so it comes to continous restarts of both managed pods. 

This is though configurable as launch parameter in operator deployment:
`
- --prometheus-instance-namespaces=namespaceA
- --alertmanager-instance-namespaces=namespaceA
`

**Describe the solution you'd like**
Alternative chart by prometheus-community is supporting this see

* https://github.com/prometheus-community/helm-charts/blob/prometheus-15.0.1/charts/kube-prometheus-stack/values.yaml#L1469
* https://github.com/prometheus-community/helm-charts/blob/7a8be84aae4fbe24562f367e7b1e7cb52fa70fd1/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L84

Would be great if you can support this options as well.

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for suggesting this.
  We are a small team very busy right now. I am creating an internal task in our back log to support this.
  However, I can not provide an ETA for this. We will come back as soon as we have news.
  Meanwhile, feel free to send a PR we will be glad to review and merge it.
