### ISSUE TITLE
[bitnami/postgresql-ha] SCRAM AuthN changes in bitnami-docker-pgpool causing restarts on entropy exhaustion

### ISSUE THREAD

**Issue by conzetti** [bitnami/charts#8269]
**Which chart**:
`bitnami/postgresql-ha`: `8.0.3`

---
**Describe the bug**
`pgpool` Pods restart on a frequent basis with zero configuration changes introduced. 

SCRAM authentication was introduced to `bitnami-docker-pgpool` in [this PR](https://github.com/bitnami/bitnami-docker-pgpool/pull/63), which defines a new environment variable ([`PGPOOL_AES_KEY`](https://github.com/bitnami/bitnami-docker-pgpool/pull/63/files#diff-638c577faffa5ed32aebed5a4ec9c865e7288564a159461bdbc862fe285ceeb9R83)) and sets the value to random data from `/dev/random` _if_ undefined.

When the liveness probe executes for the `pgpool` Pod, [a herdoc of environment variables is set](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/pgpool/healthcheck.sh#L16). This results in a scenario where calls to `/dev/random` are executed on a regular basis and cause entropy exhaustion (eventually). This manifests itself as failing liveness probes, which means that we have restarting `pgpool` Pods.

---
**To Reproduce**

1. Deploy `bitnami/postgrsql-ha` chart
2. Run `kubectl get pods` to witness the pgpool pods restarting
3. Run `kubectl describe pod postgresql-ha-pgpool-<UUID>` to view the pod status and subsequently failed liveness probe
4. Wait for Pod to restart ... 
5. Run kubectl exec -it postgresql-ha-pgpool-<UUID> -- ps aux | grep random to see the hung process

---
**Expected behavior**
`pgpool` Pods do not restart.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.1"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2021-10-28T06:55:39Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8+vmware.1", GitCommit:"3e397df2f5dadadfa35958ec45c14b0e81abc25f", GitTreeState:"clean", BuildDate:"2021-06-21T16:59:40Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

Workaround:
Set:
```
postgresql:
  extraEnvVars:
  - name: PGPOOL_AES_KEY
    value: phony	
```

Happy to help introduce a PR to fix this (introducing a default, phony value), but leaning towards correcting it in the image directly. Looking for some strong opinions on where we should introduce the change.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. So, from what I see, the variable should not have a default value in the `pgpool_env` function. Instead, if it is not defined by the time it is used, then we should set a random value, that is, at this point.

https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L551

That should solve the issue. Would you like to contribute with a PR? If not, we will work on it.
