### ISSUE TITLE
[bitnami/kafka] Missing resources for init container

### ISSUE THREAD

**Issue by Revellski** [bitnami/charts#8274]
**Which chart**:
Kafka version 13.0.2

**Describe the bug**
The Kafka chart does not specify resources for the `wait-for-available-kafka` init container.

https://github.com/bitnami/charts/blob/b7bcf26c8a89214f1ee8bcffa45a2ba55d344343/bitnami/kafka/templates/kafka-provisioning.yaml#L36-L50

**To Reproduce**
1. helm install --set provisioning.enabled=true kafka bitnami/kafka  

**Expected behavior**
The `wait-for-available-kafka` init container should set resources

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @Revellski 

Sorry but the we lose the track of this issue. This was amended at https://github.com/bitnami/charts/pull/8276 (thanks for the PR) and we can considered this issue done now.
