### ISSUE TITLE
[bitnami/redis] How to mount .conf

### ISSUE THREAD

**Issue by vanhoutenbos** [bitnami/charts#8275]
**Which chart**:
bitnami/redis latest version

**Is your feature request related to a problem? Please describe.**
I am trying to set the number of databases to 32 but am unable to or am not understanding the documentation correctly.

**Describe the solution you'd like**
A way to mount the redis.conf file with specific settings.

**Describe alternatives you've considered**
Setting the value after startup using CONFIG SET but no way to add this to the args without errors.

**Comment by vanhoutenbos** [comment]
It seems like using `--set replica.configuration="databases 32"` is the resolution

**Comment by rafariossaa** [comment]
Hi,
  I am happy you were able to solve it.
  Thanks for sharing.

**Comment by CN-Henny** [comment]
using --set master.configuration="databases 32" and --set replica.configuration="databases 32"

It doesn't seem to solve the problem

**Comment by rafariossaa** [comment]
Hi @CN-Henny ,
  This issue was close time ago and maybe for recent version the solution is other. Would you mind opening a new issue ?
