### ISSUE TITLE
[bitnami/magento] Notes: print https when magentoUseHttps or magentoUseSecureAdmin are true

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/charts#8279]
**Which chart**:
`magento-19.0.9`

**Describe the bug**
In in the Magento's Helm chart [`templates/NOTES.txt`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/templates/NOTES.txt#L62), [`Store URL`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/templates/NOTES.txt#L62) and [`Admin URL`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/templates/NOTES.txt#L63) are hard-coded to `http` regardless of the [`magentoUseHttps`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/values.yaml#L130) / [`magentoUseSecureAdmin`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/values.yaml#L134) values.

**Expected behavior**
* If [`magentoUseHttps`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/values.yaml#L130) is set to `true`, print `https` for [`Store URL`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/templates/NOTES.txt#L62), and `http` otherwise.
* If [`magentoUseSecureAdmin`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/values.yaml#L134) is set to `true`, print `https` for [`Admin URL`](https://github.com/bitnami/charts/blob/c086dc83209ec3f6b978c6f2dc3743289802dcae/bitnami/magento/templates/NOTES.txt#L63), and `http` otherwise.

**Comment by migruiz4** [comment]
Hi @hussam-qasem,

Thank you for reporting this issue. 

Would you like to contribute with us by sending a PR making the necessary changes to the Magento's NOTES.txt? 
We will be happy to review it and help with anything if needed.

**Comment by hussam-qasem** [comment]
Thank you @migruiz4 . Would be honored to contribute. I have created my first [PR#8292](https://github.com/bitnami/charts/pull/8292).

I did not update `Chart.yaml`. Please let me know if I need to do that as well.

**Comment by migruiz4** [comment]
Thank you very much @hussam-qasem, really appreciate the contribution!

> I did not update Chart.yaml. Please let me know if I need to do that as well.

Yes, we bump versions following the [semver](https://semver.org/) guidelines. In this case, a patch version would be required.
