### ISSUE TITLE
Support setting ipFamilyPolicy in charts

### ISSUE THREAD

**Issue by keliansb** [bitnami/charts#8288]
**Which chart**:
All charts.

**Is your feature request related to a problem? Please describe.**
Kubernetes 1.21 added support for IPv4/IPv6 dual-stack. Services can have both IPv4 and IPv6 by setting `.spec.ipFamilyPolicy` to `PreferDualStack` or `RequireDualStack`, see [https://kubernetes.io/docs/concepts/services-networking/dual-stack/](https://kubernetes.io/docs/concepts/services-networking/dual-stack/).

**Describe the solution you'd like**
Add an option in the `values.yaml` file to set the value of `ipFamilyPolicy`. This implies modifying the template of the service as well.

**Describe alternatives you've considered**
I can't see anyway of currently setting this value in the helm chart through the configurable values.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this.
  I have created an internal task to analyze the best approach to add this to all our charts.
  We will come back as soon as we have news.

**Comment by mnj** [comment]
Same, would also appreciate having this available to set for our dual stack clusters.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your request. I am updating our internal task. 
  We are a small team and this can take a while, I can not provide an ETA for this. 
  Meanwhile, feel free to send a PR implementing this. We will be glad to review and merge it.

**Comment by carrodher** [comment]
Thanks for this suggestion. After internal evaluation and due to other priorities, if this feature was not implemented during this time, it is very unlikely we will have the bandwidth to work on it in the mid-term.

Being said that, if you would like to contribute, feel free to create a PR to solve this issue. The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by cerebrate** [comment]
I have this issue myself, running a dual-stack cluster.

I'd be happy to submit a PR addressing this, but while I can make the changes and PR for the charts I use, I don't really have the time to make and test the same changes for all the charts I don't use. Would that still be an acceptable PR/PRs?

**Comment by javsalgar** [comment]
Hi,

Any PR that you provide will be appreciated. Feel free to just submit it for the charts you use and then this could be moved to other charts in the future.
