### ISSUE TITLE
Add "redistimeseries" to the Redis Helm charts

### ISSUE THREAD

**Issue by vikram-yerneni** [bitnami/charts#8290]
**Which chart**: Redis

**Is your feature request related to a problem? Please describe.**
Is there a way to in-corporate redistimeseries docker images into Redis Helm charts (https://hub.docker.com/r/redislabs/redistimeseries/)

**Describe the solution you'd like**
Please see above feature request.

**Comment by miguelaeh** [comment]
check the `extraSidecars`: https://github.com/bitnami/charts/blob/aff9b031e933e8aef40fc6af2beb1b63e7f2952f/bitnami/redis/values.yaml#L336

**Comment by nearnode-fan** [comment]
> check the extraSidecars:
This is not the correct answer ^ 

You just flip the main `image:` for the Redis server and the helm chart will automatically create new `StatefulSet` that runs the pre-built image for TimeSeries.

I even tested that with `Stack-Server` and works just fine.

**Comment by tferrari92** [comment]
> > check the extraSidecars:
> > This is not the correct answer ^
> 
> You just flip the main `image:` for the Redis server and the helm chart will automatically create new `StatefulSet` that runs the pre-built image for TimeSeries.
> 
> I even tested that with `Stack-Server` and works just fine.

hey, what image exactly did you use? I can't find a bitnami/redis image that includes timeseries module
