### ISSUE TITLE
grafana-operator CRDs fail to install on Kubernetes 1.22

### ISSUE THREAD

**Issue by d-m** [bitnami/charts#8291]
**Which chart**:
`grafana-operator`

**Describe the bug**
The Helm chart fails to install on 1.22 with the following error:

```
Error: failed to install CRD crds/grafanadashboards.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**To Reproduce**

1. find a Kubernetes 1.22 cluster
2. `helm install grafana-operator bitnami/grafana-operator`

Alternatively:

1. find a Kubernetes 1.22 cluster
2. `kubectl apply -f  https://raw.githubusercontent.com/bitnami/charts/master/bitnami/grafana-operator/crds/grafanadashboards.yaml`

**Expected behavior**
The Helm chart should install successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This is because the beta CRD API was removed in 1.22 (https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes)

**Comment by d-m** [comment]
I just saw a few PRs that will fix this, closing.

https://github.com/bitnami/charts/pull/8059
https://github.com/bitnami/charts/pull/7896

**Comment by migruiz4** [comment]
Hi @d-m,

Thank you for reporting this issue. Indeed we are working on it and hopefully will be fixed soon.
