### ISSUE TITLE
Add support for ingressClass to oauth2-proxy

### ISSUE THREAD

**Issue by joaocc** [bitnami/charts#8299]
**Which chart**:
oauth2-proxy 1.1.2

**Is your feature request related to a problem? Please describe.**
The oauth2-proxy chart is missing support for ingressClass.
This support is already implemented in the upstream chart

**Describe the solution you'd like**
Something along the lines of the upstream chart
https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/_ingress.tpl

**Describe alternatives you've considered**
Adding ingress class as annotation no longer supported in kubernetes 1.22+

**Comment by migruiz4** [comment]
Hi @joaocc,

Thank you for reporting this issue. I have created this PR #8301 adding the value `ingress.ingressClassName`.

Please let me know if it works for you.

**Comment by joaocc** [comment]
Looking good. Thx for the quick response.
