### ISSUE TITLE
Drupal files mount to PV

### ISSUE THREAD

**Issue by elvis2** [bitnami/charts#8302]
**Which chart**:
Drupal

**Is your feature request related to a problem? Please describe.**
I'm knew to helm and PVs. I don't understand how to move "all" drupal files into the PV mount. They way I develop locally is via composer, which writes files:
./vendor/
./web/modules
./web/themes
./web/sites
etc

**Describe the solution you'd like**
I'm sure this question is due to me being new to kubernetes / helm, my apologies in advance... The documentation is not clear on how to move other drupal directories. The docs mention that the mount should point to /path/to/sites. Does this means the drupal-data volume only stores the "sites" directory? 

This also begs the question, what should the SDLC look like if the only thing a developer is doing is pushing changes into the PV. Also, in drupal, module updates might require a database update. Normally I run these updates in drush. Upon a PV change, how would one automate a single drush updb run (considering you have multiple drupal pods)?

**Describe alternatives you've considered**
Build a docker image and use it in the helm chart yaml values file: global.image

**Additional context**
Screenshot attached.
<img width="1174" alt="CleanShot 2021-12-03 at 02 55 50@2x" src="https://user-images.githubusercontent.com/117609/144574269-167b3168-bdb8-4adf-89f3-7a9707711469.png">

**Comment by juan131** [comment]
Hi @elvis2 

> This also begs the question, what should the SDLC look like if the only thing a developer is doing is pushing changes into the PV.

Please note that, in the container world, you should try to adopt an "inmutable" mindset. I mean, if you change anything that's not persisted in the container (we persist the `sites`, `themes`, `modules` and `profile` directories in the Bitnami image), you should create build a custom image including your changes.

With that in mind, the SDLC will consist on having two different Drupal installations (one for production and for development) on different kubernetes clusters or namespaces. You'll work on your "development" installation and work on your changes and, once you're happy with them, move them to the "production" one.
You can use different strategies for remotely development, that's up to you (e.g. you can use Oketo, see https://okteto.com/blog/vs-code-remote-development-in-kubernetes).
Other changes such as updating Drupal will be managed by simply upgrading your chart releases that will include the latest changes in the Bitnami Drupal images.

> Upon a PV change, how would one automate a single `drush updb run` (considering you have multiple drupal pods)?

Please note that you can only scale the solution and deploy several Drupal pods if you have support for RWX volumes (e.g. using NFS). This requirement is specified in the chart pre-requisites:

- https://github.com/bitnami/charts/tree/master/bitnami/drupal#prerequisites

I mean, the same NFS volume will be mounted in every Drupal pod to ensure the changes in the filesystem are synced.

**Comment by elvis2** [comment]
Hi @juan131,

Thanks for responding. In our case, we push code changes in by (1) baking an image (2) using ArgoCD + a helm chart + 
a values.yaml file.

I still have a few concerns that maybe you can address, related to the typical drupal SDLC cycle:

1. Drupal core team and community recommends using composer to manage vendors, modules and themes. Making those changes locally in a docker-compose is not a concern. Running composer commands locally adds changes either to (a) docroot/sites|themes|modules and/or the vendor directory, which is recommended to live outside of the docroot.

In bitnami's drupal image setup, that means the vendor directory needs to live at /opt/bitnami/vendor, right? And the docroot lives at /opt/bitnami/drupal ? Because the vendor needs to live outside of the docroot. If this is the case, how do we get these files mapped locally to the proper destination using the helm chart values?

2. The docs / readme don't really explain how to lay "your drupal code" onto the pod or PV?  Since PVs are used in this helm chart, it seems the file changes in "sites" directory is not pushed to a container but a volume. It would be nice to see a working example that shows what the values.yaml should look like for drupal php code changes and sites/* file changes. I checked the bitnami website and other resources but I can't find a good working example. 

3. Drupal website maintainers rely on using drush heavily. I know you can setup drush aliases on a local box that pushes up drush commands to the remove box (kubernetes pod in this case). Normally drush commands are ran locally, but certain commands need to run on the actually pod. For example, to update the database due to module changes, this will need to be done within a pod using a drush command. I'm wondering what update / upgrade workflows other maintainers might have when running drupal in a container?

**Comment by rafariossaa** [comment]
Hi,

> 1. Drupal core team and community recommends using composer to manage vendors, modules and themes...

As we don't develop on drupal, I can not provide a good answer for where the `vendors` folder need to be. Maybe you can provide more background on this,  and what would be needed.

> 2. The docs / readme don't really explain how to lay "your drupal code" onto the pod or PV?...

This would depend on how you develop and how you are going to use the later on production. For example you can build you own image based on ours and add all the needed files, and the use that image in the chart. Other options are, use a side container that will provide the files to the drupal container. Or you can use shell scripts in `/docker-entrypoint-init.d` that will be executed [after the setup](https://github.com/bitnami/bitnami-docker-drupal/blob/95135e88441e9a3ef111cf8b6bc769c493e118fc/9/debian-10/rootfs/opt/bitnami/scripts/drupal/entrypoint.sh#L26).

> 3. Drupal website maintainers rely on using drush heavily. I know you can...

I am sorry, I can not tell about what other developers are using. I think you can use the scripts in `/docker-entrypoint-init.d` to run the `drush` command you would need.

**Comment by elvis2** [comment]
Thanks @rafariossaa.

A few updates / comments on the above.

1) After reviewing the directory structure of the bitnami drupal image, I changed my composer.json setup to put the vendor libs to be in the docroot/vendor with sites/ and the other drupal directories. It's recommended to keep vendors out of the docroot for security reasons.

2) I tried using the bitnami drupal docker image as a base but kept having strange issues. For example:
```shell
drupal 09:32:46.01 INFO  ==> ** Starting Drupal setup **
realpath: /bitnami/apache/conf: No such file or directory
drupal 09:32:46.11 INFO  ==> Configuring PHP options
drupal 09:32:46.15 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 09:32:46.38 INFO  ==> Trying to connect to the database server
drupal 09:32:46.43 INFO  ==> Configuring file permissions for Drupal
drupal 09:32:46.45 INFO  ==> An already initialized Drupal database was provided, configuration will be skipped
```
And within a few minutes the container would go offline. Here is the dockerfile I used:
```Dockerfile
FROM bitnami/drupal:9.2.10

ENV DRUPAL_DATABASE_HOST=mariadb
ENV DRUPAL_DATABASE_NAME=drupal
ENV DRUPAL_DATABASE_USER=drupal
ENV DRUPAL_DATABASE_PASSWORD=drupal
ENV DRUPAL_SKIP_BOOTSTRAP=yes
ENV DRUPAL_DATABASE_TLS_CA_FILE=/opt/bitnami/drupal/fake-ssl

WORKDIR /opt/bitnami/drupal

COPY website/web  /opt/bitnami/drupal # This does a full copy as expected
# COPY website/web  /bitnami/drupal # This gives an error.
```
I had to put in a tls ca (DRUPAL_DATABASE_TLS_CA_FILE) file otherwise the other run scripts would fail.

I did try providing an entrypoint or simple cmd but that did not stop the container from stopping. Based on what I've read the run scripts, once the copy command takes place, the run scripts are not able to finalize.

So, this leads me to a different approach. The bitnami drupal helm chart docs says (I think) you can persist data to the PV. I see three configs that might support this but since there is no example to work off of, I'm not entirely sure. Here they are:
```
persistence.hostPath | If defined, the drupal-data volume will mount to the specified hostPath.

extraVolumes | Array of extra volumes to be added to the deployment (evaluated as template). Requires setting extraVolumeMounts

extraVolumeMounts | Array of extra volume mounts to be added to the container (evaluated as template). Normally used with extraVolumes.
````
A few questions around these configuration options:

persistence.hostPath: Can I persist the entire local docroot? In my case, relative to where I run the helm command: website/web, which has all of the files drupal needs to run.

extraVolumes: I believe this option is to separate out specific directories. I'm thinking vendors and sites/ would be candidates. Thoughts?

3) I think this idea will satisfy the need. Thanks!

**Comment by rafariossaa** [comment]
> 2. I tried using the bitnami drupal docker image as a base but kept having strange issues. ...

I can not see any strange issue there. If you do `docker-compose up`  using the provide docker-compose file you will get the same messages.

I am not very sure on what are you copying into  the container with `COPY website/web  /opt/bitnami/drupal`. Maybe you want to take a look first what is there. Have into account that the initialization scripts expect some files to exists. Maybe you want to take a look to the initialization scripts to get a better idea on how the whole thing works.

Regarding the config parameters you indicated:
- hostPath: It is used to mount a path from the host where you are running the pod into the pod.
- extraVolume / extraVolumeMounts, you can provide other PVC and use these parameter to mount them on the pod.

I would suggest you to take a look to kubernetes documentation on PV/PVC to get a better idea on how all this works, sometimes is kind of confusing if you are new to kubernetes.

You can use them if you think it suits you better, but this very dependent on how is your development workflow.

Maybe you can try first with docker and once you have it working the way you need, then move to kubernetes.

**Comment by elvis2** [comment]
@rafariossaa 

> I can not see any strange issue there. If you do docker-compose up using the provide docker-compose file you will get the same messages.

What I mean by that is that the container build was not completed. The scripts stopped at the point. I did review the .sh files and found many more steps should have been executed but were not.

> I am not very sure on what are you copying into the container with COPY website/web /opt/bitnami/drupal. Maybe you want to take a look first what is there. 

I did standup a drupal helm chart build to see the files and directory structure. The drupal related files are just the core files. What about when you need to add modules, themes, site/default/settings.php chagnes? See the image below for the file structure I want to sit on the PV.

<img width="310" alt="CleanShot 2021-12-15 at 11 21 38@2x" src="https://user-images.githubusercontent.com/117609/146235873-1acf401a-61d4-42b3-8e9c-22d9c6c8f990.png">

> I would suggest you to take a look to kubernetes documentation on PV/PVC to get a better idea on how all this works, sometimes is kind of confusing if you are new to kubernetes.

I did read up on PV/PVC today. It seems like what I'm asking for is supported by ConfigMaps. I noticed in the other bitnami helm charts configmaps are being utilized but not in the drupal helm chart.

> Maybe you can try first with docker and once you have it working the way you need, then move to kubernetes.

I've built the stack with docker-compose, but with a different image (wodby). Due to the user and directory structure that bitnami uses for the drupal helm chart, I had to change my local development setup so I can build the image with bitnami's docker image as a base. If I can solve building and running the image successfully, locally, I think I would be satisfied to put the image in kubernetes.

**Comment by rafariossaa** [comment]
Hi,
  If you  build upon the bitnami's image you should be able to use it in the chart without problems.

  You can try using configMaps, I am not sure if that would be the best approach as we don't develop on drupal. It it works for you, maybe you would like to send a PR to add that to the chart. We will be glad to review and merge it.

**Comment by KoalityJustin** [comment]
@elvis2 Dropping here from out of nowhere: did you ever resolve this issue?

Currently playing around with the Drupal chart and running into almost *exactly* the same issue. Seems to hit that same line but then none of the other scripts run and then the container ends up in a "CrashLoopBackOff" state.

**Comment by leonspringer** [comment]
In case anyone runs into this issue, I had success using both COPY lines at the same time. 

e.g.
```
COPY website/web  /opt/bitnami/drupal  # and the following line
COPY website/web  /bitnami/drupal 
```

**Comment by colans** [comment]
Because we came across this, and couldn't get past it, we wrote a Terraform module instead.  See details at [Want to Run Drupal in Kubernetes? Try Our New Terraform Module](https://backupscale.com/posts/drubernetes-terraform-module-for-kubernetes-clusters/).
