### ISSUE TITLE
redmine fails to use externalDatabase

### ISSUE THREAD

**Issue by avkoval** [bitnami/charts#8314]
**Which chart**: bitnami/redmine

**Describe the bug**
Template helpers point to `.Values.externalDatabase.name` instead of `Values.externalDatabase.database`

**To Reproduce**
Try to install bitnami/redmine with externalDatabase specified

**Expected behavior**

value of `name: REDMINE_DATABASE_NAME` to be populated properly

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Bug fix is ready, will be provided.

**Comment by juan131** [comment]
Thanks so much for opening the issue to report the issue, and also opening an associated PR to address it. Please take a look to the comments we added in the PR when you have a chance.

**Comment by carrodher** [comment]
As the associated PR is merged I think we can safely close this issue
