### ISSUE TITLE
RabbitMQ ignore username and password via secrets if container fail during initialization step

### ISSUE THREAD

**Issue by cinesia** [bitnami/charts#8326]
**Which chart**
rabbitmq 8.24.0

**Describe the bug**
RabbitMQ ignore username and password via secrets (auth.username and auth.existingPasswordSecret) if rabbitmq container fail during the initialization step. The user is instead created using default user and password from rabbitmq.conf.

**To Reproduce**

1. Install rabbitmq chart passing _auth.username_ and _auth.existingSecret_ values to create an user at bootstrap.
2. Kill the container during _Initializing RabbitMQ..._ using: 
`kubectl exec POD_NAME -c CONTAINER_NAME -n NAMESPACE /sbin/killall5`
3. Wait for the container to restart.
4. Wait for rabbitmq to finish bootstrap steps.
5. Check if exists an user with the values defined below.

**Expected behavior**
Rabbitmq should overwrite the default password with the one defined in auth.existingSecret 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"32a137c122b0474c719988922410f4027a4b002e", GitTreeState:"clean", BuildDate:"2021-11-01T16:43:17Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
If the container is not killed (or fail) the user is created correctly.

**Comment by juan131** [comment]
Hi @cinesia 

If RabbitMQ fails to initialize and it's restarted, the changes in the filesystem will persist. Therefore, the RabbitMQ container initialization logic will reuse whatever changes were previously done to the configuration files, see:

- https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L728

My question is: what's causing the initialization to fail when install the chart? I mean, if you address whatever issue is causing the initialization to fail, you'll avoid any misconfiguration, am I right?

**Comment by cinesia** [comment]
Hi @juan131,
We are not using persistence at the moment so the config is stored in an _emptyDir_  volume.
The failure at the initialization step is caused by our scheduled _scale-to-zero_ policy. 
During the night our clusters are reduced to zero nodes and then the day after in the morning are scaled up again.
During the scale-up, the rabbitmq pods try to go in a *Running* state but sometimes fail the first time and the container is restarted (the container NOT the pod). In the second restart, rabbitmq shows _Persistent data detected_. and skip the setting of our credentials served by secrets.
It's like Rabbitmq is in an inconsistent state.

Expected behaviour: 
1. Init
2. Configuration is saved to storage
3. Failure.
4. Init.
5. Detected persisted data.
6. Credentials are changed based on secrets. 

Actual behaviour: 
1. Init
2. Configuration is saved to storage
3. Failure.
4. Init.
5. Detected persisted data.
6. Change of credentials is skipped.

**Comment by miguelaeh** [comment]
Hi @cinesia ,
I re-checked the logic and seems to be correct. If any file exists into the data directory, it is not empty, so the logic assumes rabbitmq has already been configured. In the first initialization, the configuration file is written, you can check that it should contain the password from the secret (checking the Helm Chart and the container logic, the password from the existing secret should be properly configured).
Could you share the logs of the failing initialization? Also, check that the configuration file contains the proper password before killing the pod

**Comment by cinesia** [comment]
Hi @miguelaeh,
Thanks for your time.
The logic is correct but if the initialization fails anywhere between these lines (https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L728-L756), the change of password is skipped on the next restart, leading to an inconsistent situation.

At the restart, the configuration file doesn't contain the proper password for the reason I described above.

As a workaround, I moved to definition files to override the password. The definitions are applied after the initialization steps so they are independent of a crash during the starting phase.

What I would like to underline is that this line (https://github.com/bitnami/bitnami-docker-rabbitmq/blob/master/3.9/debian-10/rootfs/opt/bitnami/scripts/librabbitmq.sh#L769) is not enough robust to failures.

Thanks again!

**Comment by miguelaeh** [comment]
Hi @cinesia ,
could you suggest a more robust approach for the password change? We will really appreciate it.

**Comment by cinesia** [comment]
Hi @miguelaeh, 
There are several approaches I thought about it, I will cite some of them: 
- Force the change of password even if persisted data are detected, giving to the user/password provided by the chart the highest priority.
- Adopt an atomic approach, as you said, using a checkpoint system based on atomic write/read of flags on a _checkpoints' file_ .

About the second one, I would take notes for each step, if it was successful or not, using atomic read/write operations (https://itectec.com/unixlinux/bash-performing-atomic-write-operations-in-a-file-in-bash/). 
During a restart, after a failed initialization, I would consider the checkpoints' file above to decide which operation to skip, undo/redo or simply do.

**Comment by miguelaeh** [comment]
Thanks for the details @cinesia , the first approach would be simple, would you like to create a PR?

**Comment by cinesia** [comment]
Hi @miguelaeh ,
Should I create the PR on this repo https://github.com/bitnami/bitnami-docker-rabbitmq ??

**Comment by miguelaeh** [comment]
Sure! thank you!!
