### ISSUE TITLE
Webserver POD restarting 

### ISSUE THREAD

**Issue by JagadeepK01** [bitnami/charts#8327]
**Which chart**:
Airflow 10.3.1

**Describe the bug**
I'm running Airflow on AKS. I mounted Azure file shares for dags, plugins and logs.
Dags file share is having around 300 dags. Webserver pod doesn't complete get into running state. It stucks at airflow db init step. It stucks there for 5mins and again the webserver pod restarts.

If I remove the dag file share or put few dags in fileshare like 50, webserver pod gets into running state.

**To Reproduce**
Install airflow on AKS and use file shares . Put some 300+ dags in file share and restart webserver.

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.5.3
```

- Output of `kubectl version`:

```
1.13.15
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Does the same issue happen when you use less DAGs? This could be related to the Azure filesystem maybe.

**Comment by JagadeepK01** [comment]
Hi @javsalgar 
Yes, In the airflow helm chart , we have two options of making the dags / plugins available to pods. One is Git containers and the other one is by mounting file shares to pods. 
1) If I use Git containers, airflow init db doesn't take more than 3-4 minutes. (300 + dags)
2) If I use File shares, airflow init db takes more than 9-10 minutes. 

What can be the reason for this? Because every time you restart pods, airflow web server takes 10 minutes for airflow init db to finish and be available to receive requests.

**Comment by JagadeepK01** [comment]
> Due to the lack of activity in the last 5 days since it was marked as "stale", we proceed to close this Issue. Do not hesitate to reopen it later if necessary.

reopen this issue

**Comment by javsalgar** [comment]
Hi,

Did you try modifying the readiness/liveness probes so they take more time before forcing a pod restart? In this case, due to the amount of DAGs, it should take more to get started.
