### ISSUE TITLE
Change K8s API from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by kmezynski** [bitnami/charts#8333]
**Which chart**:
grafana-operator

**Describe the bug**
After trying to install Helm chart I get the following error:
```
Error: INSTALLATION FAILED: failed to install CRD crds/grafanadashboards.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**To Reproduce**
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install grafana-operator bitnami/grafana-operator
```

**Expected behavior**
Helm charts installs without errors.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Output of `minikube version`:

```
minikube version: v1.24.0
```

**Additional context**
As it's said in [Kubernetes docs reference](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122):

> apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22

Solution would be to change existing API **apiextensions.k8s.io/v1beta1** to **apiextensions.k8s.io/v1**. It seems the same applies to the **kong** chart.

**Comment by javsalgar** [comment]
Thank you so much for reporting. Would you like to submit a PR with the fix?

**Comment by kmezynski** [comment]
Sure, I can try! I'll familiarise myself with the contributing rules then.

**Comment by juan131** [comment]
To be solved at https://github.com/bitnami/charts/pull/8059
