### ISSUE TITLE
internal loadbalancer annotation not working! 

### ISSUE THREAD

**Issue by Mukesh9092** [bitnami/charts#8334]
I am trying to use below helm command to setup kafka with internal loadbalancer using annotation for aws -

```console
$ helm install my-release bitnami/kafka --set zookeeper.enabled=true --set zookeeper.replicaCount=2 --set replicaCount=3 --set --set-string service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"=true deleteTopicEnable=true --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer --set externalAccess.service.port=80 --set externalAccess.autoDiscovery.enabled=true --set serviceAccount.create=true --set rbac.create=true
```

After applying above command it doesn't create internal loadbalancer, it creates ELB with public access.

**Comment by Mukesh9092** [comment]
@Mauraza , I was just following your suggestion provided by you earlier -
https://github.com/bitnami/charts/issues/1894

And it still doesn't work, could you please help me

**Comment by juan131** [comment]
Hi @Mukesh9092 

You're enabling external access. Therefore, you don't need to set the custom annotations for ELB using the `service. annotations` parameter but the `externalAccess.service.annotations` parameter instead, see: 

- https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L745

**Comment by mthakur-mdsol** [comment]
Thanks @juan131 for prompt help, it's working now.

**Comment by juan131** [comment]
Great! I proceed to close the issue but please reopen it if you require further assistance.
