### ISSUE TITLE
InfluxDB Replicating Data Across All InfluxDB Servers

### ISSUE THREAD

**Issue by Tolga-Karahan** [bitnami/charts#8335]
**Which chart**:
bitnami/influxdb 2.4.1

**Is your feature request related to a problem? Please describe.**
Yes. Bucket is sometimes created in a database other times it is created in another database. I want same data across all db instances.

**Describe the solution you'd like**
I want the data replicated across all InfluxDB servers.

**Describe alternatives you've considered**
No alternative is considered for this case.

As I gave information above is there a capability in this chart for replicating data across all database servers? If something is written to any database it must be replicated in others as well. I want same data across all databases.

Thanks!

**Comment by javsalgar** [comment]
Hi,

It looks to me this has to do with how InfluxDB is configured. Did you try checking with the upstream influxdb support to see what configuration flags are necessary? This way, if there's something we can do to change the configuration it would be easier for us to implement it.
