### ISSUE TITLE
[bitnami/thanos] I want to pass the Thanos s3 storage information in secret.

### ISSUE THREAD

**Issue by HanHoRang** [bitnami/charts#8338]
I want to enter s3 information in the Thanos chart through Kubernetes Secret.
```
existingObjstoreSecret: ""
## @param existingObjstoreSecretItems Optional item list for specifying a custom Secret key. If so, path should be objstore.yml
##
existingObjstoreSecretItems: []
```
How do you know where to stand if you have options?

**Comment by javsalgar** [comment]
Hi,

Is the s3 information set in the in the objstore.yml file? If so, you can set it using the value you mention above.
