### ISSUE TITLE
Joomla 4.x support

### ISSUE THREAD

**Issue by dukeofgaming** [bitnami/charts#8347]
**Which chart**: 
Joomla 10.2.2

**Is your feature request related to a problem? Please describe.**
Support for Joomla 4.x

**Describe the solution you'd like**
Currently there is only a Helm chart for Joomla 3.x

**Describe alternatives you've considered**
Creating my own chart with a bitnami Joomla 4.x image

**Additional context**
There is already a Joomla 4.x image: https://github.com/bitnami/bitnami-docker-joomla/tree/4.0.4-debian-10-r35/4

**Comment by juan131** [comment]
Hi @dukeofgaming 

You're 100% right @dukeofgaming 

We found some issues when trying to release the chart using the 4.x image, and we created a task to investigate the issues and find a solution. However, it seems this task wasn't addressed yet. 

I'll sync with the team and try to raise the priority of the task so we can have a chart compatible with 4.x ASAP.

**Comment by dukeofgaming** [comment]
Any word on this?

**Comment by juan131** [comment]
This task has been already assigned to one of our engineers after I raised the priority. That said, we're a small team and christmas vacations are approaching so this could delay a little bit the release. Stay tune for the next few weeks.

**Comment by carrodher** [comment]
A new major version of the Joomla Helm chart was released (`11.0.0`), this version is including the latest app version (`4.0.5`), see #8514. Please note once merged the changes in GitHub there can be some hours of delay until the new chart appears in the Helm chart registry.

Please, feel free to reopen this issue if something is not working as expected.
