### ISSUE TITLE
[mongodb] WiredTiger errors when using EFS backed PV on AWS EKS

### ISSUE THREAD

**Issue by Nuru** [bitnami/charts#8350]
**Which chart**:
mongodb 10.30.6

**Describe the bug**
New deployment of MongoDB fails to initialize EFS-backed storage under AWS EKS (Amazon Web Services' Elastic Kubernetes Service).

**To Reproduce**

- Create EKS cluster using Kubernetes 1.21
- Create EFS file system
- Deploy https://github.com/kubernetes-sigs/aws-efs-csi-driver and create `efs-sc` Storage Class
- Deploy MongoDB using 
```yaml
    persistence:
      enabled: true
      storageClass: efs-sc
      accessModes:
      - ReadWriteOnce
      size: "100M"
```

**Expected behavior**
MongoDB should initialize and work with a Persistent Volume backed by Amazon's Elastic File System.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:05:33Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

The weird error message is 
```
"connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists"
```
MongoDB creates the `WiredTiger.wt` but then cannot open it? Then it complains that it finds the file already exists when it goes to create it, so it renames the existing file and the cycle repeats. At the end the directory has a handful of empty `WiredTiger.wt.n` files and a valid `WiredTiger` and `WiredTiger.lock` file. 

```
[root@ip-10-138-24-106 db]# cat WiredTiger
WiredTiger
WiredTiger 10.0.0: (March 18, 2020)
```

#### Logs
<details><summary>Click to reveal logs</summary>

```log
mongodb 09:23:38.02 
mongodb 09:23:38.04 Welcome to the Bitnami mongodb container
mongodb 09:23:38.04 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:23:38.04 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:23:38.04 
mongodb 09:23:38.04 INFO  ==> ** Starting MongoDB setup **
mongodb 09:23:38.06 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:23:38.14 INFO  ==> Initializing MongoDB...
mongodb 09:23:38.16 INFO  ==> Enabling authentication...
mongodb 09:23:38.17 INFO  ==> Deploying MongoDB with persisted data...
mongodb 09:23:38.24 INFO  ==> ** MongoDB setup finished! **

mongodb 09:23:38.26 INFO  ==> ** Starting MongoDB **
```
```json
{"t":{"$date":"2021-12-09T09:23:38.350+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2021-12-09T09:23:38.350+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-12-09T09:23:38.359+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-12-09T09:23:38.363+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2021-12-09T09:23:38.363+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"pritunl-mongodb-d654f7876-2vpwg"}}
{"t":{"$date":"2021-12-09T09:23:38.363+00:00"},"s":"W",  "c":"CONTROL",  "id":20720,   "ctx":"initandlisten","msg":"Available memory is less than system memory","attr":{"availableMemSizeMB":1024,"systemMemSizeMB":3874}}
{"t":{"$date":"2021-12-09T09:23:38.363+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.4","gitVersion":"8db30a63db1a9d84bdcad0c83369623f708e0397","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2021-12-09T09:23:38.363+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.4.156-83.273.amzn2.x86_64"}}}
{"t":{"$date":"2021-12-09T09:23:38.363+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/opt/bitnami/mongodb/conf/mongodb.conf","net":{"bindIp":"*","ipv6":false,"port":27017,"unixDomainSocket":{"enabled":true,"pathPrefix":"/opt/bitnami/mongodb/tmp"}},"processManagement":{"fork":false,"pidFilePath":"/opt/bitnami/mongodb/tmp/mongodb.pid"},"security":{"authorization":"enabled"},"setParameter":{"enableLocalhostAuthBypass":"false"},"storage":{"dbPath":"/bitnami/mongodb/data/db","directoryPerDB":false,"journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"logRotate":"reopen","path":"/opt/bitnami/mongodb/logs/mongodb.log","quiet":false,"verbosity":0}}}}
{"t":{"$date":"2021-12-09T09:23:38.375+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=256M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2021-12-09T09:23:40.242+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1639041820:242959][1:0x7fb507284140], connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists"}}
{"t":{"$date":"2021-12-09T09:23:40.249+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.3"}}
{"t":{"$date":"2021-12-09T09:23:40.259+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1639041820:259472][1:0x7fb507284140], connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
{"t":{"$date":"2021-12-09T09:23:40.309+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1639041820:309840][1:0x7fb507284140], connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists"}}
{"t":{"$date":"2021-12-09T09:23:40.316+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.4"}}
{"t":{"$date":"2021-12-09T09:23:40.322+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1639041820:322071][1:0x7fb507284140], connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
{"t":{"$date":"2021-12-09T09:23:40.368+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":17,"message":"[1639041820:368308][1:0x7fb507284140], connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists"}}
{"t":{"$date":"2021-12-09T09:23:40.375+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.5"}}
{"t":{"$date":"2021-12-09T09:23:40.382+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1639041820:382042][1:0x7fb507284140], connection: __posix_open_file, 808: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
{"t":{"$date":"2021-12-09T09:23:40.389+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
{"t":{"$date":"2021-12-09T09:23:40.389+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
{"t":{"$date":"2021-12-09T09:23:40.390+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":1123}}
{"t":{"$date":"2021-12-09T09:23:40.390+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
```

**Comment by juan131** [comment]
Hi @Nuru 

The logs you shared indicate:

```console
mongodb 09:23:38.17 INFO  ==> Deploying MongoDB with persisted data...
```

This mean these are the logs after the MongoDB container has been restarted and it detected persisted data in the volume. It's very likely that it was restarted during the 1st initialization of the container because the readiness/liveness probes failed.

The probes could be failing during the 1st boot for several reasons but a very common one is that the filesystem is very slow for "write" operations and the container simply needs more time than expected to complete the initialization. To discard the issue is related to this, please follow the steps below:

- Uninstall the MongoDB chart.
- Manually remove the PVC that was created to satisfy the MongoDB persistence needs (please note `helm uninstall` doesn't remove them).
- Install the MongoDB chart again increasing the timeout for the readiness/liveness probes. E.g. using the values.yaml below:

```yaml
livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 20
readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 20
persistence:
  enabled: true
  storageClass: efs-sc
  accessModes:
    - ReadWriteOnce
  size: 100M
```

Now the containers have much more time to initialize during the 1s boot.

**Comment by Nuru** [comment]
I increased initial delay to 300 seconds and no meaningful difference. Note that in the log excerpt in the OP, 
```
unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.3
```
repeats with `...wt.4` and `...wt.5`, and all the files are zero bytes. The issue is whatever is causing Mongo not to be able to use the `WiredTiger.wt` it creates. I verified it can CRUD files, but maybe it needs more than that?

**Comment by juan131** [comment]
Hi @Nuru 

That's so weird.. Could you please install the chart setting the parameter `image.debug` to `true` (to increase log verbosity) and share the whole container logs? Thanks in advance.

**Comment by Nuru** [comment]
Looking further into EFS, I found you could set the UID and GID for the access point (with caveats: see [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/567)). After setting the UID and GID to 1001 to match the fsGroup of the MongoDB deployment in the chart, this problem went away.

I don't know what the critical difference is between having RWX permissions on the EFS mount and owning the mount, but it is something significant.

Better error messages and better documentation would be helpful here. Hopefully there is a fix that does not require owning the EFS mount point.

**Comment by juan131** [comment]
Hi @Nuru 

Thanks for sharing your finding!

> Better error messages and better documentation would be helpful here. Hopefully there is a fix that does not require owning the EFS mount point.

For those StorageClasses that aren't compatible with automatically modifying the filesystem ownership based on the Pod SecurityContext, we offer the possibility of using a init-container to adapt them, see:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb

**Comment by Nuru** [comment]
> For those StorageClasses that aren't compatible with automatically modifying the filesystem ownership based on the Pod SecurityContext, we offer the possibility of using a init-container to adapt them, see:
> 
>     * https://github.com/bitnami/charts/tree/master/bitnami/mongodb#volume-permissions-parameters

I am not positive, and it will be a couple of weeks before I can double-check, but I do not think the init-container is capable of solving the problem when using the [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver). The driver sets the volume owner and I do not think the root user can later change it.

**Comment by vivektrivediiii** [comment]
Issue is still in mongodb with efs mount or have some solution ?? 
 i f you please put here so help for us.

**Comment by mzeeshan1** [comment]
I am facing the same issue, is there some solution other than changing uid and gid, as these are set on storage class level and not on PVC level. Other apps using same storage class can have issue

**Comment by juan131** [comment]
Hi @mzeeshan1 

As I mentioned some years ago, a possibility would be using init containers to adapt the permissions:

> For those StorageClasses that aren't compatible with automatically modifying the filesystem ownership based on the Pod SecurityContext, we offer the possibility of using a init-container to adapt them, see:
> 
> * https://github.com/bitnami/charts/tree/master/bitnami/mongodb#volume-permissions-parameters

You could also change the `podSecurityContext.fsGroup` and `containerSecurityContext.runAsUser`/`containerSecurityContext.runAsGroup` parameter so they match whatever uid/gid used on the PVCs created with the storage class you're using.

**Comment by mzeeshan1** [comment]
@juan131 With efs-csi-driver, the init container approach doesn't seem to work. I am getting this error:
`2024-10-17T19:16:30.263+0000 E  STORAGE  [initandlisten] WiredTiger error (1) [1729192590:263664][1:0x7f290ffafb00], connection: __posix_open_file, 667: /data/db/WiredTigerLAS.wt: handle-open: open: Operation not permitted Raw: [1729192590:263664][1:0x7f290ffafb00], connection: __posix_open_file, 667: /data/db/WiredTigerLAS.wt: handle-open: open: Operation not permitted`
This file (WiredTigerLAS.wt) is being created at runtime and only the user specified on the storage class has read-write access for it. mongodb user can't open this file.
Have you tried init-container approach with efs-csi-driver?

**Comment by juan131** [comment]
@mzeeshan1 I haven't tried this approach with particular volume type. That said, what you reported isn't unusual, depending on the filesystem the init-container approach couldn't work.

In this case, I guess you'll have to adapt the pod' security context and container' security context so the `fsGroup` and `runAsUser` UID/GID are aligned with the ones the `efs-csi-driver` expects
