### ISSUE TITLE
[postgresql-ha] pgpool.configuration syntax errors silently discarded

### ISSUE THREAD

**Issue by meln5674** [bitnami/charts#8375]
**Which chart**:
postgresql-ha version 8.0.4

**Describe the bug**
Syntax errors in the field pgpool.configuration cause the pgpool pod to fail without any error, and one must set BITNAMI_DEBUG to 'true' for this to be observable. This is compounded by the fact that the README lists the default value of this field to be an empty object ("{}"), which seems to indicate that the field should be a map of configuration fields to values, where inspecting the values.yaml file reveals it is actually meant to be a string.

**To Reproduce**
1. Set pgpool.configuration to an invalid value (non-string, or a string containing syntax errors)

**Expected behavior**
1. A concise explanation of the error to be reported to stdout/stderr (i.e. visible in kubectl logs) without needing to enable any debugging features.
2. The README to correctly state (or imply through its default value) that the pgpool.configuration field is, in fact, a string, which will have the helm tpl function applied to it (not terribly relevant to pgpool configuration files, but good to note nonetheless)

**Version of Helm and Kubernetes**:
Irrelevant

**Additional context**
None

**Comment by juan131** [comment]
Hi @meln5674 

As you mentioned you can always set `BITNAMI_DEBUG` to `true` (setting the `pgpoolImage.debug` parameter to `true`) to increase the verbosity of the logs and obtain more info.

That said, you're completely right.. The examples does indicate the object expects a string but we're setting an empty object by default. This is confusing:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L898

I'll send a PR to amend this.
