### ISSUE TITLE
[bitnami/zookeeper] init-certs container referencing old .Values.securityContext

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#8386]
**Which chart**:

bitnami/zookeeper (7.5.0)

**Describe the bug**

The commit which introduced new pod/container securityContext missed updating `.Values.securityContext` to `.Values.containerSecurityContext`

(https://github.com/bitnami/charts/blob/c98cd88e0fbf84fe5da3a4d5ceca807c882220b5/bitnami/zookeeper/templates/statefulset.yaml#L117-L120)

**To Reproduce**

1. Deploy chart with tls enabled

```
Error: template: zookeeper/templates/statefulset.yaml:117:24: executing "zookeeper/templates/statefulset.yaml" at <.Values.securityContext.enabled>: nil pointer evaluating interface {}.enabled
```

**Expected behavior**

Chart is deployed successfully

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
3.7.2
```

- Output of `kubectl version`:

```
1.22.4
```

**Additional context**

**Comment by juan131** [comment]
Hi @tbnguyen1407 

Thanks for reporting this bug! Fortunately, this was was fixed by @marcosbc yesterday at this PR: https://github.com/bitnami/charts/pull/8391
