### ISSUE TITLE
elasticsearch data pod need more setting types to support different storageClass settings.

### ISSUE THREAD

**Issue by xykong** [bitnami/charts#8406]
**Which chart**:
The name (and version) of the affected chart.

>**elasticsearch**

**Is your feature request related to a problem? Please describe.**

>**I need many different storageClass, size settings for data pod, to support hot, warm data architecture.**

**Describe the solution you'd like**

>**Declare my different data pod  description in values.yaml**

**Describe alternatives you've considered**

>**Make data section  in values to became array.**

**Additional context**

>**This feature request is used to implement ILM easily. https://www.elastic.co/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management"**

**Comment by Mauraza** [comment]
Hi @xykong,

Did you try with `extraVolumes`?
 ttps://github.com/bitnami/charts/blob/8ba3d2a6027f6507e34bbcc2c05cec23b09fed2a/bitnami/elasticsearch/values.yaml#L185-L190

**Comment by xykong** [comment]
> Hi @xykong,
> 
> Did you try with `extraVolumes`? ttps://github.com/bitnami/charts/blob/8ba3d2a6027f6507e34bbcc2c05cec23b09fed2a/bitnami/elasticsearch/values.yaml#L185-L190

Hi @Mauraza 
	Thanks for your replay!
	I think  extraVolumes is not for my case.  extraVolumes is used for mount file system to every pod. Typically used for "[use a shared file system to store snapshots](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch/#snapshot-and-restore-operations)"
But in my case, I want to create multiple type data pod for elasticsearch to implement hot-warm data architecture.
For example 4x1000G HDD for warm data, 2x500G SSD for hot data. 

I'm not very familiar with this chart, If I'm misunderstand with you,  please fix me.

**Comment by Mauraza** [comment]
Hi @xykong,

>  extraVolumes is used for mount file system to every pod. Typically used for "use a shared file system to store snapshots"

That is one of the cases you can use `extraVolumes`.

with `extraVolumes` and `extraVolumeMounts` is the only way to add more volumes to the chart:

https://github.com/bitnami/charts/blob/6c645054c3437b71b25b12e9eee5e41d14d3af49/bitnami/elasticsearch/values.yaml#L178-L191

**Comment by xykong** [comment]
> Hi @xykong,
> 
> > extraVolumes is used for mount file system to every pod. Typically used for "use a shared file system to store snapshots"
> 
> That is one of the cases you can use `extraVolumes`.
> 
> with `extraVolumes` and `extraVolumeMounts` is the only way to add more volumes to the chart:
> 
> https://github.com/bitnami/charts/blob/6c645054c3437b71b25b12e9eee5e41d14d3af49/bitnami/elasticsearch/values.yaml#L178-L191

Hi @Mauraza 
	What could I do if I have done setting multiple extraVolumes, extraVolumeMounts? I think this can't add more data node and can't make different settings too.

    I'm not familiar with create helm chart, but I think make data section to array is an easy and clearly solution.

Thinks for your replay.

**Comment by juan131** [comment]
Hi @xykong 

Sorry but I don't think I fully understand what you're trying to achieve.

Do you want to have different kind of Elasticsearch data node? Please note this isn't supported in this chart as I mentioned previously in this issue: https://github.com/bitnami/charts/issues/7244

**Comment by xykong** [comment]
> Hi @xykong
> 
> Sorry but I don't think I fully understand what you're trying to achieve.
> 
> Do you want to have different kind of Elasticsearch data nodes? Please note this isn't supported in this chart as I mentioned previously in this issue: #7244

Hi @juan131 

    Yes, I want to build a hot-warm-architecture following this post: https://www.elastic.co/cn/blog/hot-warm-architecture-in-elasticsearch-5-x.

    I realize this helm chart can't achieve this architecture, same as you mentioned in #7424.

    I extend this chart by duplicate data section in values.yaml and related files in templates. It works fine.

    Thanks for your replay. Hope this will support in the future.

**Comment by Mauraza** [comment]
Hi @xykong,

I'm glad you found the way to build the architecture. Closing this out now, do not hesitate to write us back if you have any other questions.

**Comment by CasperTDK** [comment]
> > Hi @xykong
> 
> > 
> 
> > Sorry but I don't think I fully understand what you're trying to achieve.
> 
> > 
> 
> > Do you want to have different kind of Elasticsearch data nodes? Please note this isn't supported in this chart as I mentioned previously in this issue: #7244
> 
> 
> 
> Hi @juan131 
> 
> 
> 
> Yes, I want to build a hot-warm-architecture following this post: https://www.elastic.co/cn/blog/hot-warm-architecture-in-elasticsearch-5-x.
> 
> 
> 
> I realize this helm chart can't achieve this architecture, same as you mentioned in #7424.
> 
> 
> 
> I extend this chart by duplicate data section in values.yaml and related files in templates. It works fine.
> 
> 
> 
> Thanks for your replay. Hope this will support in the future.
> 
> 

Can you share your solution?
