### ISSUE TITLE
Bitnami/spark: Not able to access master web UI when ssl is enabled 

### ISSUE THREAD

**Issue by sarvani95** [bitnami/charts#8417]
**Which chart**:
Bitnami/spark

**Describe the bug**
When ssl is enabled, master web UI is not accessible on 80 or 8480 ports

**To Reproduce**

set ssl to true in values.yaml file and access the master UI.

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by gkulkarni32** [comment]
Just wanted to add to the above issue, what we observed is the `https` port is missing in both the statefulset and the service yamls, so the container and service both dont have the port. Due to this we are unable to access the ssl url.

**Comment by migruiz4** [comment]
Hi @sarvani95,

Thank you for reporting this issue. Indeed, the Spark container SSL configuration is missing the `spark.ssl.port` setting, which default as `0` (a random port will be used).

https://github.com/bitnami/bitnami-docker-spark/blob/cc41d1caa11c607c244653bafd868239c0f34f36/3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh#L229-L245

The Statefulset uses SPARK_WEBUI_PORT to configure the Spark port, but the HTTPS port needs to be configured separately, and can't be done with just an env variable.

If you'd like to contribute, feel free to send PRs modifying the Spark chart and image and we will be happy to review it.

**Comment by migruiz4** [comment]
Sorry for the late response. An internal task has been created to adapt the Spark container and chart adding support for the HTTPS web UI port.

Due to the current team workload, I can not give an ETA for this, but in the meantime PRs are welcome and we will be happy to review any contribution.
