### ISSUE TITLE
[bitnami/rabbitmq] Cpu throttling although not near limit

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#8420]
- name: rabbitmq
    version: 8.20.2
    repository: https://charts.bitnami.com/bitnami

I have the request and limit set to 1000m, datadog reports the container never uses more than 300m, but it also reports that the cpu is being consistently cf throttled. I know this was a problem in some earlier linux versions, but I believe Debian Buster 10.10 should have the fix. Do you guys see this? Any solutions?

**Comment by carrodher** [comment]
In order to be able to reproduce the issue on our side, can you please provide the information below?
- k8s version
- _values.yaml_ used to deploy the chart(or the `--set` parameters)
