### ISSUE TITLE
Solr chart does not create a custom core

### ISSUE THREAD

**Issue by mohanlon-iai** [bitnami/charts#8425]
**Which chart**:
Solr version 2.x

**Describe the bug**
I used the `coreName: prod` variable, but Solr does not have a core with that name when it starts. Additionally, I cannot create it when I use the core admin. 

**To Reproduce**

1. Use the coreName variable to create a new core
2. Go to Solr admin page
3. See that core is not created.

**Expected behavior**
A core by the given name to the variable "coreName" should be present.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-dispatcher", GitCommit:"283881f025da4f5b3cefb6cd4c35f2ee4c2a79b8", GitTreeState:"clean", BuildDate:"2021-09-14T05:16:08Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
![image](https://user-images.githubusercontent.com/33632874/146220291-e3f9ba61-44d0-470f-98fc-441579a4d957.png)

**Comment by juan131** [comment]
Hi @mohanlon-iai 

Could you please provide the information below?

- The **values.yaml** (or equivalent parameters sets via `--set`) you are using to install the chart.
- Are you able to reproduce the when performing a `helm install` on a clean environment or do you only reproduce it while running `helm upgrade` on existing releases?

**Comment by mohanlon-iai** [comment]
Hi @juan131 
Please close out this issue. This was probably an issue with Docker Desktop. I had to go into the file system where Docker keeps volumes and clear everything myself. Once I did that, I was able to use the "coreName" variable to create a custom core. Sorry for the trouble!
