### ISSUE TITLE
[mongo-sharded] RollingUpgrade doesn't wait for the index to be created

### ISSUE THREAD

**Issue by Lp-Francois** [bitnami/charts#8435]
**Which chart**:
name: mongodb-sharded
version: 3.10.0 

**Describe the bug**
Not really a bug, more like an unwanted behavior:
When a rolling update happens, I would expect the cluster to wait to have the indexes generate dand ready for the secondary restart before taking down the primary (which leads to a few hours where the cluster doesn't have indexes)

**To Reproduce**

Set up the helm chart with:
2 mongoS
2 replicas per shard, 1 arbiter
3 replicas for cfgsrv
Docker image: 5.0.5-debian-10-r13 
Deployment is made with FluxCD V2, but helm upgrade --install will show the same behavior

I have a mongo cluster with 5 shards, roughly 23GB of RAM on each shard being used (limit to 28BG).
Data-wise, it is ~300 GB uncompressed.

When I bumped the docker image from 5.0.5-debian-10-r0 to 5.0.5-debian-10-r13, and deploy the new chart values,
I got a rolling update (default values from the chart) with taking down my arbiter and my secondary for each shard. But once they got up, my primary was taken down directly as well, without waiting for all the indexes to be generated (see my screenshot)
I would expect the primary to be upgraded after the indexes are generated. It leads to having all the queries being run without indexes as the new primary doesn't have time to generate the indexes (it takes a few hours).

Should I do the upgrade manually then? And update the docker image for one shard, restart it, wait for the indexes to be generated, do the same for the primary, etc and then next shard. 
What would you advise?

**Expected behavior**
I expect the primary to go down only once the secondary recovers from the upgrade & all the indexes being re-created

**Version of Helm and Kubernetes**:
Helm: version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
K8s: 1.21.5-do.0 (managed Digital Ocean)

**Additional context**

Screenshot of the second member of shard 0 going down, and then indexes in memory are reseted (normal behavior)
<img width="1262" alt="Screenshot 2021-12-16 at 17 32 50" src="https://user-images.githubusercontent.com/32224751/146411086-d2534fc0-3f02-47b6-bb26-2e465608e188.png">

The first member of shard 0, being restarted with the new mongo before the second member indexes are getting ready. Therefore the indexes in memory are almost inexistent and all queries are slow.
<img width="1262" alt="Screenshot 2021-12-16 at 17 32 48" src="https://user-images.githubusercontent.com/32224751/146412004-c6cdb46f-c913-4a70-ace6-f9eff54f6c6d.png">

Best regards

**Comment by miguelaeh** [comment]
Hi @Lp-Francois ,
I understand the problem here is that, when the controller restarts the MongoDB pods it does not know anything about what those pods are performing, so it kills the primary before the indexes are re-generated.
Do you have any suggestions on how could we address the issue?

**Comment by Lp-Francois** [comment]
Hi @miguelaeh 👋 
Is there a way to let the controller knows that the pod is not ready? So maybe setting a startupProbe that would listen to the index state?
The only downside is a rolling update would take hours with big indexes (as it needs to restart, generate the indexes, restart the other member of the replica set, re-index).

How do people address this problem in production?

As a workaround, is there a way to "pause" the controller, and do the rolling upgrade by hand?
- stop controller
- stop traffic to be sent to secondaries
- Update the mongo image version of all secondaries, restart the pods
- Wait a few hours the indexes are ready
- Let requests reach to secondaries
- Do the same for the primaries
- Resume the controller

**Comment by rafariossaa** [comment]
Hi,
  Maybe you can use startupProbes and scaling down and later sacaling up.

**Comment by Lp-Francois** [comment]
Hello @rafariossaa 

Could you develop your idea?

**Comment by rafariossaa** [comment]
I think that for startup probes you got the idea. They are used to check when the service has started and then start running liveness and readiness probes.  Maybe you can use [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) as reference.

For the scaling up and down, I was thinking in reducing the size of the cluster by removing nodes. But now that I rethink on this, I won´t make a difference for a rolling upgrade.

This is an interesting use case for me, I would like to know more to see how can I help you or how we can improve the chart to handle this use cases. When you talk about ¨big indexes", how big are they ?

**Comment by Lp-Francois** [comment]
Hi @rafariossaa,

So we have indexes of ~60GB of data in the cluster, with one database per client (~100). Some are few MBs, some are few GBs.

It is not just setting the pod as ready when the index is not created on a "fresh" pod, but seems like worse: I noticed after the restart, it does not recreate the index at all. As you can see in my screenshot, there are 3 steps:

1. yesterday, I manually re-create the indexes of one database running on shard 2 (after a rolling update, the indexes are not getting recreated). That's why the memory is low.
2. From 9h50 to 11h05, I manually recreated all the indexes of 1 database running on shard2. 5~10min are enough to generate the indexes.
3. From 11h05 on, I start a rolling update to modify the docker image from 5.0.5-debian-10-r13 to 5.0.5-debian-10-r12. After each pod restart, the index seems "stale". The memory doesn't increase as it is supposed to be.

<img width="1578" alt="Screenshot 2021-12-28 at 14 14 02" src="https://user-images.githubusercontent.com/32224751/147569887-16d3322b-a428-4a54-8db1-7ddffdd4f774.png">

How are people using this chart if image upgrade is bringing down any traffic requests? Or is there a setting to set at a mongo cluster DB level to automatically generate the indexes when a pod restarts?

**Comment by rafariossaa** [comment]
Hi,
  Did you check the logs in the pods ? Maybe there is a clue to what is happening.
  That chart is from the mongo exporter, isn't it ? Maybe you would need to check also what is happening at k8s node level. If the node is 16GB, maybe you are running out of memory at node level, or it is swapping and is very very slow.

  As we don't have an internal mongodb deployment, I couldn't tell how others are using this chart. I hope someone that read this can share his/hers experience. Also, I would suggest you to ask in mongodb related forums, I guess this is an problem that appears in all kind of deployments not only in kubernetes.

**Comment by Lp-Francois** [comment]
Yes, first thing but nothing showing up :/ 

The chart is from the mongo-sharded chart, here: https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded

But sadly (happily?), we use managed Kubernetes so we don't have access to the underlying nodes :( 
Nevertheless, we use nodes with ~4 CPU and 32GB of RAM, so it should be enough for our workload 🤔 (and I monitor these nodes with grafana to be sure we don't get throttle or OOM)

But good advice, I will have a look at the MongoDB community directly. Until now, I didn't find a similar use-case, I'll update this issue if anything shows up 👌

**Comment by rafariossaa** [comment]
@Lp-Francois ,  thanks for sharing. 

> Yes, first thing but nothing showing up :/

That's a pity. Maybe there is something at k8s level.

> Nevertheless, we use nodes with ~4 CPU and 32GB of RAM, so it should be enough for our workload thinking (and I monitor these nodes with grafana to be sure we don't get throttle or OOM)

I thought your nodes were big enough, but I asked just in case. There are many possibilities for bugs and we need to discard them, even if they seem to be silly or trivial.

Please, don´t hesitate to come back and share you findings.
