### ISSUE TITLE
[redis-cluster] master-replica distribution

### ISSUE THREAD

**Issue by RysoBeco** [bitnami/charts#8441]
**Which chart**:
redis-cluster 7.0.13

**Is your feature request related to a problem? Please describe.**
I'd like to make sure that pods responsible for given shard (master and its replicas) are never placed on same k8s node (if number of nodes > number of replicas + 1). This is required to meet fault tolerance requirements on clusters.

**Describe the solution you'd like**
Some cluster building policy that would check whether master and its replica aren't placed on the same node. Feature should allow to define topologyKey to determine "same node" condition.

Policy should allow given node to contain both masters and replicas from separate shards.

**Describe alternatives you've considered**
Making sure to have more k8s nodes than redis.cluster.nodes. That is unfortunately hardware solution.

**Additional context**
Perhaps requested feature is possible to accomplish using already defined charts. If so I'd be grateful for description of how to achieve it.

**Comment by juan131** [comment]
Hi @RysoBeco 

Did you give a try to pod anti-affinity policies? They'll allow you to distribute the pods so no pods are scheduled on nodes where there are already other Redis Cluster pods. Find more info in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#setting-pods-affinity

**Comment by RysoBeco** [comment]
I tried anti-affinity, but I think it is not enough to solve this issue (I have described it as an 'alternative solution'). Anti-affinity has a limitation: number of nodes must be greater than or equal to number of pods.

This feature is about some kind of anti-affinity internal to Redis Cluster that would affect not how pods are distributed between nodes but how roles (i.e. "master of shard A", "replica of shard B") are assigned to specific pod based on running node. 

More precisely: Redis Cluster building rules should make sure that every member (master/replica) responsible for specific shard is placed on pod that is operating on node with different "topologyKey" value. Cluster members responsible for different shards may be placed on the same node.

This configuration would require also defining spread constraints to make sure that pods are evenly distributed.

**Comment by juan131** [comment]
Hi @RysoBeco 

I don't think that complex scenario you described isn't possible using the current chart since every Redis node (every master and replicas nodes for every shard) is part of the same statefulset. Therefore, it isn't possible to define specific anti-affinity policies per shard.

**Comment by RysoBeco** [comment]
I'm aware of that, but AFAIK inside docker image there are multiple tools in /opt/bitnami/scripts. I'm not sure how they work in details, but I assume, that it is possible to enforce some rules while building cluster. From chart perspective you could expose value of topologyKey as environment variable. 

Perhaps there is an easier solution to achieve same functionality. I agree this one is challenging. But I also think it is an important functionality because fault tolerance is usually a must have. Redis nodes aren't very heavy weight pods and usually single pod is not able to utilize compute resources provided for single VM or physical device.

**Comment by juan131** [comment]
Hi @RysoBeco

> I'm aware of that, but AFAIK inside docker image there are multiple tools in /opt/bitnami/scripts. I'm not sure how they work in details, but I assume, that it is possible to enforce some rules while building cluster. From chart perspective you could expose value of topologyKey as environment variable.

IMHO, we shouldn't tackle this at container level, I mean it's out of the scope of the container's init logic to deal with this. The K8s scheduler is the unique one that should decide where to schedule new pods. We can modify the scheduler behaviour by using native properties exposed by K8s objects such as topologySpreadConstraints, nodeSelector, tolerations, affinity, etc. See:

- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node

All these properties can be customized using Bitnami charts.
