### ISSUE TITLE
[bitnami/jasperreports] using persistence.existingClaim dont work

### ISSUE THREAD

**Issue by NiasSt90** [bitnami/charts#8455]
**Which chart**:
bitnami/jasperreports v11.1.2

**Describe the bug**
install the chart with existing PVC for jasperreports don't work.

**To Reproduce**
````
helm install ot-jrs --set persistence.enabled=true --set persistence.existingClaim=jrs-data-pvc  bitnami/jasperreports
````

**Expected behavior**
start jrs deployment with using the PVC "jrs-data-pvc" but it wants a PVC with name "ot-jrs-jasperreports" (common.names.fullname)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.16) exceeds the supported minor version skew of +/-1
```

**Additional context**
the sub-chart PVC mariadb.primary.persistence.existingClaim=... works as expected.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/jasperreports#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
