### ISSUE TITLE
Postgres Data directory permissions overwritten after setting volumePermissions.enabled=true

### ISSUE THREAD

**Issue by breadnarz** [bitnami/charts#8456]
**Which chart**:
The name (and version) of the affected chart
Postgres/Latest 

**Describe the bug**

I have two different helm charts that use two different Postgres Databases. I'm deploying both Postgres Databases with volumePermissions.enabled=true. Originally when the chart is deployed everything works well and the permissions are correct: 
$ ls -l /bitnami/postgresql/
drwx------. 19 1001 1001  4096 Dec 19 18:26 data

But after some time (usually overnight) the permissions on /bitnami/postgresql/data change: 
$ ls -l /bitnami/postgresql/
drwx--S---. 19 root 1001  4096 Dec 20 13:13 data

When logging on the next day after permissions have been changed I get many errors and warnings in the Potsgres pod related to permission denied and the applications lose connection to the database.  I have tested this many times. It happens for both databases (running in separate namespaces and on separate worker nodes). 

I'm using longhorn for a storage class: 
https://longhorn.io/

**To Reproduce**
helm install postgres bitnami/postgresql -n MYNAMESPACE --set volumePermissions.enabled=true
wait 

**Expected behavior**
Postgres to stay up and running 

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+rke2r1", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-19T17:26:11Z", GoVersion:"go1.16.10b7", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Did any restarts happen before the permissions change occur? It seems strange to me that the process with ID 1001 changes the permissions to root all of a sudden. In the past we've seen issues with Longhorn in other github cases. This is a storage provider we don't actively test (we test the default PVC provider in all major k8s distributions: GKE, AKS, IKS, TKG...), so I'm not sure if someone from the community has more experience with it and can provide some input.
