### ISSUE TITLE
[bitnami/minio] Crash on Run, No Logs

### ISSUE THREAD

**Issue by jimmybrancaccio** [bitnami/charts#8457]
**Which chart**:

https://github.com/bitnami/charts/tree/master/bitnami/minio
minio v9.2.5

**Describe the bug**

I have this deployed on my k3s cluster. It was working fine up until a few days ago. Now it just attempts to start but then stop with no useful information in the logs. I have enabled `BITNAMI_DEBUG = true` but that doesn't result in any further logs or information. This issue appears to be the same or similar to bitnami/bitnami-docker-minio#3, however I did try removing the PVC and that still didn't resolve the issue. The only logs I see are:

```
2021-12-20 08:58:34 | 14:58:34.01 Welcome to the Bitnami minio container
2021-12-20 08:58:34 | 14:58:34.02 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
2021-12-20 08:58:34 | 14:58:34.02 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
2021-12-20 08:58:34 | 14:58:34.02
2021-12-20 08:58:34 | 14:58:34.02 INFO ==> ** Starting MinIO setup **
2021-12-20 08:58:34 | minio 14:58:34.07 INFO ==> Starting MinIO in background...
2021-12-20 08:58:44 | minio 14:58:44.08 INFO ==> Adding local Minio host to 'mc' configuration...
2021-12-20 08:58:44 | minio 14:58:44.28 INFO ==> MinIO is already stopped...
```

**To Reproduce**

1. Run `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. Run
    ```bash
    helm install --name minio-external \
      --namespace default \
      --set auth.rootUser=minio-admin \
      --set auth.rootPassword=minio-secret-password \
        bitnami/minio
3. Once the pod is up, observe its logs.

**Expected behavior**

I expect that the Minio pod/container comes up without issue.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

**Additional context**

If there's anything else I can provide to help troubleshoot this please don't hesitate to let me know!

**Comment by rafariossaa** [comment]
Hi,
  Could you share you logs ? 
  I used the following command and I got no errors.
```
helm install  minio-external  \
  --set auth.rootUser=minio-admin   \
  --set auth.rootPassword=minio-secret-password   \
  bitnami/minio
```

**Comment by jimmybrancaccio** [comment]
Hi @rafariossaa I ended up using Amazon S3 for my object storage in the end. If I end up using MinIO again via the Bitnami chart and this happens again I will open a new issue. Closing this one for now.

**Comment by rafariossaa** [comment]
@jimmybrancaccio , thans for comming back and sharing. 
Yes, don't hesitate to open an issue when needed.

**Comment by kissyoudyb** [comment]
Which chart:

https://github.com/bitnami/charts/tree/master/bitnami/minio
minio v9.3.0  9.3.0 [2021.12.29]

Describe the bug

I have this deployed on my k8s cluster. It was working fine up until a few days ago. Now it just attempts to start but then stop with no useful information in the logs. I have enabled BITNAMI_DEBUG = true but that doesn't result in any further logs or information. This issue appears to be the same or similar to bitnami/bitnami-docker-minio#3, however I did try removing the PVC and that still didn't resolve the issue. The only logs I see are:
![image](https://user-images.githubusercontent.com/10389241/148529534-4c7129bf-56b8-4fd6-bd9f-8b6d0fe08eec.png)

**Comment by carrodher** [comment]
Thanks for the comment, it can be the same issue or not so we will need to investigate it. In order to try to reproduce the issue on our side, can you please share the command used to deploy the chart as well as the _values.yaml_ or parameters used via `--set` (if any)?

**Comment by fuergaosi233** [comment]
I have the same problem. V10.0.0 
![image](https://user-images.githubusercontent.com/22197568/148937708-28cac29e-ef2f-4dbe-ae07-fe31aff8c196.png)

**Comment by rafariossaa** [comment]
Hi @fuergaosi233 ,
  Could you provide the command used to deploy the chart as well as the values.yaml or parameters used via --set (if any)?

**Comment by kfox1111** [comment]
I'm seeing this too.

**Comment by rafariossaa** [comment]
@kfox1111 
Could you provide the command used to deploy the chart as well as the values.yaml or parameters used via --set (if any)? We would like to try to reproduce the issue in our side.

**Comment by kfox1111** [comment]
```
minikube version: v1.25.1
commit: 3e64b11ed75e56e4898ea85f96b2e4af0301f43d
```
new cluster with:
```
minikube start
```

This works:
```
helm upgrade --install minio bitnami/minio --set accessKey.password=minio-access-key --set secretKey.password=minio-secret-key --version 7.3.0
```

This is currently entering the crashloop:
```
helm upgrade --install minio bitnami/minio --set accessKey.password=minio-access-key --set secretKey.password=minio-secret-key --version 7.3.1
```

Something changed between:
bitnami/minio:2021.6.17-debian-10-r58 and bitnami/minio:2021.9.3-debian-10-r1

Any chart past 7.3.1 all the way up to 10.1.7 is failing for me most of the time. Before 7.3.0, solid.

**Comment by rafariossaa** [comment]
Hi @kfox1111 ,
  Is this the same you reported [here](https://github.com/bitnami/charts/issues/9013) ?

**Comment by kfox1111** [comment]
It may be. I could have sworn I saw it working reliably where the release minio would work, but otherminio release wouldn't. but maybe its a bit racy and I didn't look long enough. Right now, its consistently failing every time on these versions no matter how often I try.

**Comment by rafariossaa** [comment]
Let's continue the discussion in that issue.
