### ISSUE TITLE
Simple Problem In Documentation

### ISSUE THREAD

**Issue by Namphibian** [bitnami/charts#8461]
In the documentation of the PgSQL-HA chart  you mention the following:

Additionally, if persistence.resourcePolicy is set to keep, you should manually delete the PVCs.

However I am unable to find this in the values.yaml.  It would be helpful for testing the charts as you dont have to delete the PVC/PV each time. If it is not supposed to be there could we remove it from the docs?

**Comment by javsalgar** [comment]
Hi,

Thanks for spotting the issue. Indeed, this value is not present so it should be removed from the docs. Would you like to submit a PR fixing it?

**Comment by Namphibian** [comment]
Hey mate. 

Will update and submit PR over the next few days just swamped with last minute roll-outs before xmas. Loads of fun for this time of year.

**Comment by Namphibian** [comment]
I branched off but when trying to push this up for a pr I am getting the following:
13:21:59.319: [bitnami] git -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/Simple_Problem_In_Documentation_#8461:refs/heads/Simple_Problem_In_Documentation_#8461 --set-upstream
remote: Permission to bitnami/charts.git denied to Namphibian.
fatal: unable to access 'https://github.com/bitnami/charts.git/': The requested URL returned error: 403

**Comment by carrodher** [comment]
Can you try cloning the repo via [HTTPS](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls) instead of [SSH](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-ssh-urls)?
