### ISSUE TITLE
Add Triggerer support in Airflow

### ISSUE THREAD

**Issue by amirhalatzi** [bitnami/charts#8462]
**Which chart**:
bitnami/airflow: 11.1.11
**Is your feature request related to a problem? Please describe.**
In Airflow 2.2.2 a new component was added, named 'Triggerer'. It is currently isn't part of the chart.

**Describe the solution you'd like**
Add support for this component in the chart.

**Describe alternatives you've considered**
Installing the default chart instead of bitnami's

**Additional Context**
* The service template in Apache's chart: https://github.com/apache/airflow/blob/main/chart/templates/triggerer/triggerer-deployment.yaml
* Parameters description: https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html?highlight=triggerer#triggerer

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the input! I will open a task for the engineering team to evaluate this. As it is not a critical feature, we cannot guarantee an ETA. However, as soon as we have more news, we will update this ticket.

**Comment by amirhalatzi** [comment]
Hi @javsalgar :)

Can I submit a pull request with the relevant changes?

**Comment by rafariossaa** [comment]
@amirhalatzi , Sure, we will be glad to review and merge it.

**Comment by pastushenkoy** [comment]
@rafariossaa , I would also be glad to help implementing this feature, but as far as I know, first we will need to implement separate docker image for triggerer. This image should store in separate repository like [bitnami-docker-airflow-worker](https://github.com/bitnami/bitnami-docker-airflow-worker), [bitnami-docker-airflow-scheduler](https://github.com/bitnami/bitnami-docker-airflow-scheduler) or [bitnami-docker-airflow](https://github.com/bitnami/bitnami-docker-airflow). But I cannot create new repository in bitnami organization.

Can you create new repository for bitnami-docker-airflow-triggerer or explain how should I do without it?

**Comment by fmulero** [comment]
Hi @pastushenkoy thanks a lot for your enthusiasm.

You can work in your own repository and share it with us using this issue for example.  Adding a new container to the bitnami catalog is not an easy task. It requires an internal process and it could take some time.

I'll try increase the priority of our internal task about this new airflow component.

**Comment by mkrdip** [comment]
Hello there, 

any update on this?

**Comment by tseruga** [comment]
Just want to add that this is also wanted by me.

Airflow has deprecated Smart Sensors, and thus adding triggerer support is necessary to use the replacement.

**Comment by tseruga** [comment]
Just adding a notice that Smart Sensors are being deprecated in Airflow 2.4.0 (the next minor release).

https://github.com/apache/airflow/milestone/53

The PR has already been merged in.

**Comment by sgrzemski** [comment]
Any update here? @carrodher 
I can prepare the PR if needed

**Comment by carrodher** [comment]
Sorry for the late response, unfortunately, due to other priorities the team has we were not able to spend the required time to add this new feature. Taking a look at our roadmap it is very unlikely we will find the bandwidth to do it in the mid-term.

That's the reason why we will close this issue as not planned.

**Comment by bhayden53** [comment]
The triggerer is a core airflow service and required for running deferrable operators, such as the ones in the official airflow kafka operator. It should really be a part of the bitnami helm chart, one way or another.

**Comment by carrodher** [comment]
We finally added support for Triggerer at https://github.com/bitnami/charts/pull/30211.

In the same way, please note we are refactoring the Bitnami Airflow Helm chart so there is a single container acting as Worker, Scheduler, Triggerer, etc instead of having separate containers, see https://github.com/bitnami/charts/pull/30137
