### ISSUE TITLE
Unable to deploy static site with nginx helm chart

### ISSUE THREAD

**Issue by jaxxstorm** [bitnami/charts#8466]
**Which chart**:
bitnami/nginx latest

**Describe the bug**
I am trying to deploy a helm chart with a simple static site under a `/healthy` ingress

My `values.yaml` looks like this:

```
staticSiteConfigmap: healthy
serverBlock: |-
  server {
   root /app;
   server_name _;
   location / {
     index index.html;
   }
  }
ingress:
  enabled: true
  hostname: tst.aws.briggs.work
  pathType: Exact
  path: /health
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: true
```

I only added the serverblock because I believed I'd configured something incorrectly, but it still doesn't work.

This creates an ingress rule that looks correct, and the ingress controller forwards the request to the nginx instance correctly. However, the nginx configuration in this helm chart isn't correct, and I get the following error in the nginx logs:

```
2021/12/21 11:04:18 [error] 26#26: *144 open() "/opt/bitnami/nginx/html/healthy" failed (2: No such file or directory), client: 10.1.0.44, server: , request: "GET /healthy HTTP/1.1", host: "tst.aws.briggs.work"
```

It is unclear to me why this ingress rules results in nginx trying to open the configuration at `/opt/bitnami/nginx/html/healthy`

I can see the `index.html` under `/app` in the container. Where does the above configuration come from?

**Comment by javsalgar** [comment]
Hi,

Could you share with us the example site you are using so we can reproduce the issue?

**Comment by jaxxstorm** [comment]
Hi @javsalgar 

I created the static site like so:

```
echo '<html><head><title>Hello World</title></head><body>healthy</body></html>' > /tmp/index.html
kubectl create configmap healthy --from-file=/tmp/index.html
```

It's a very very simple static site.

If you examine the deployment from helm, you can see the configmap is mounted correctly in the deployment, so it definitely exists.

**Comment by jaxxstorm** [comment]
This is my fault, I hadn't set the rewrite target on the ingress, it should have been:

```
staticSiteConfigmap: healthy
serverBlock: |-
  server {
   root /app;
   server_name _;
   location / {
     index index.html;
   }
  }
ingress:
  enabled: true
  hostname: tst.aws.briggs.work
  pathType: Exact
  path: /health
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  tls: true
```

**Comment by javsalgar** [comment]
Thanks for letting us know!
