### ISSUE TITLE
redis as External Ip on gke

### ISSUE THREAD

**Issue by aqibfayyaz** [bitnami/charts#8468]
Hi, i want to use redis with feast and for that i need redis to be available as LoadBalancer rather than ClusterIP. i have cloned the repo and changed the value in values-production.yaml file for redis master from ClusterIP to LoadBalancer but when i deploy the chart on gke using command 
```
helm install my-release bitnami/redis --values redis/values-production.yaml
```
i get the following error
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].command): invalid type for io.k8s.api.core.v1.Container.command: got "string", expected "array"
```

**Comment by javsalgar** [comment]
Hi,

The values-production.yaml file was deprecated about a year ago. Could you ensure that you are using the latest version of the chart? I checked the repository and the values-production.yaml file is not present.

**Comment by aqibfayyaz** [comment]
https://github.com/bitnami/charts/tree/1af52330f32b233bf953f17599c4f8fd87c2d1d3/bitnami/redis

**Comment by aqibfayyaz** [comment]
if i want to use the current version how can i do than? by setting the value of this flag sentinel.service.type to LoadBalencer?

**Comment by carrodher** [comment]
The commit you are pointed to is from a really old Helm chart version:
```yaml
version: 10.5.14
appVersion: 5.0.8
```
versus the latest one
```yaml
version: 15.6.8
appVersion: 6.2.6
```

If you want to use the latest version you have several options:
- Install it directly from the registry, see https://github.com/bitnami/charts/tree/master/bitnami/redis#tldr
- Clone this repo and use the latest commit in the `master` branch.
- Get the compressed packaged (for example via `helm fetch`) and install it with `helm install` once uncompressed.

Please, refer to the [official Helm documentation](https://helm.sh/docs/) to find more information about how to deploy Helm charts, the different options available. In the same doc site, you will find information about how to customize Helm charts by using your desired parameters (using `-f YAML_FILE` or `--set VALUE`)
