### ISSUE TITLE
Zombie Process Running in Azure AKS Worker Node -  [redis-cli] <defunct>

### ISSUE THREAD

**Issue by zohebs341** [bitnami/charts#8475]
Redis is running as pod in Azure AKS cluster.

Redis Server Version : 
```console
$ redis-server --version
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=331b3b4f519a5508
```
Just wanted to check, if there any bug in this version. Why because, there is one Zombie process running in Azure AKS worker node.
```console
$ ps aux | grep redis
    Z    06:01   0:00 [redis-cli] <defunct>
```
Will it cause any issues for other microservices running?

In one microservice, I've noticed in logs.
```
 09:55:09[lettuce-nioEventLoop-6-1][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379
 09:55:09[lettuce-nioEventLoop-6-1][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379

 10:55:09[lettuce-nioEventLoop-6-2][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379
 10:55:09[lettuce-nioEventLoop-6-2][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379

 12:55:09[lettuce-eventExecutorLoop-1-1][, ][INFO]i.l.c.p.ConnectionWatchdog:: Reconnecting, last destination was alpha-redis-master.redis.svc.cluster.local/10.0.31.251:6379
 12:55:09[lettuce-nioEventLoop-6-1][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379
 12:55:09[lettuce-nioEventLoop-6-1][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379

13:55:09[lettuce-nioEventLoop-6-2][, ][INFO]i.l.c.p.ReconnectionHandler:: Reconnected to alpha-redis-master.redis.svc.cluster.local:6379
```

**Comment by javsalgar** [comment]
Hi,

This seems to be the remainders of a health check process. You shouldn't expect any issues with that.

**Comment by zohebs341** [comment]
@javsalgar Thanks for your response.

The reason behind creating this issue is, there is a difference in memory consumption.

I mean to say memory utilization of kuberetes node is showing 75% utilized, but when I enter/exec into the node, I can see the actual memory utilization is 50% only. So there is a difference.

Is that zombie process at Kubernetes worker node is causing this memory issue? I mean that zombie process is causing this mismatch?

**Comment by javsalgar** [comment]
I'm not an expert, but I don't think that could be the reason of the mismatch. Did you check if the defuct process is actually consuming any memory? (for example with top)
