### ISSUE TITLE
[bitnami/rabbitmq] updateStrategyType RollingUpdate seems not possible 

### ISSUE THREAD

**Issue by christopheblin** [bitnami/charts#8479]
**Which chart**:

CHART rabbitmq-8.6.0

APP VERSION 3.8.9

**Describe the bug**

follow up to #8415 

from my understanding, rabbitmq does not support to share a filesystem between 2 running instances, so it is not correct to have 2 pods that use the same PVC at the same time (and so, RollingUpdate seems not possible to me even if the storage class supports to be attached to multiple pods like 'azurefile read-write-many' for ex)

in the same time, it is absolutely necessary to have a PVC so that when we update the helm deployment the new pod keeps the definitions and the unconsumed messages

the proper thing to do seems to change updateStrategyType to OnDelete and to indicate in the doc that to proceed to a modification the correct way is `helm update blabla && kubectl delete pod rabbitmq-0 && kubectl delete pod rabbitmq-1 && ...`

be aware that if replicaCount==1, it means there will be a downtime (but no corruption of the rabbit files)

**Comment by alemorcuq** [comment]
Hi, @christopheblin.

I don't understand. A RollingUpdate strategy means that one pod is deleted and then a new pod is created. Once this new pod is up and running, another one is deleted and then a new pod is created. There's never 2 pods trying to use the same PVC. Am I missing something?

**Comment by christopheblin** [comment]
@alemorcuq  in my experience with azuredisk (a PVC that do not allow 2 pods to attach simultaneously), when the rolling update is started, the new pod never starts because it fails to attach to the PVC (I dont have the error anymore because I switched to OnDelete strategy)

so, I am not a k8s expert but I would say that rolling update does not delete the pod then restart a new one (it does something like creating the new pod then deleting the old pod when the new one is ready)

hence, there is a moment during which 2 pods are using the same underlying disk

moving to OnDelete solved my issue as mentioned in #8415

**Comment by rafariossaa** [comment]
Maybe, the volume is on other k8s node and the volume doesn´t allow  mount it on other k8s node where the new pod is trying to start.
Could this be the issue ?

**Comment by christopheblin** [comment]
@rafariossaa yes it is exactly the issue using "managed-premium" on azure for ex

however, if you use "azurefile" (which perfectly supports 2 pods attached at the same time),  as I said in the previous comemnt, you still have an issue because RollingUpdate will start the new pod BEFORE killing the old one

so there is a (short) amount of time while 2 rabbitmq are using the same underlying storage -> this is wrong (to me)

this is solved by using OnDelete

**Comment by rafariossaa** [comment]
Hi,
  I've doing some testing using gcloud. But I couldn't reproduce the issue, and it worked as expected. 
  I am guessing here, but maybe the issue is that when using that kind of storage is only attached to one of the k8s cluster nodes. So, let's say that when you start rabbitmq the pod and its PVC it is attached to k8s' node-0, but when you upgrade, the new pod is schedule on node-1 and the volume can not be moved to node-1.
  The `RollingUpgrade`, will proceed from the latest to the first of the pods, deleting it and creating the replacement, once it is up, will proceed with the next pod.
  This is what I tried. I used the default `values.yaml`, changes are passed using `--set`:
```
$ helm install myrabbit -f values.yaml --set persistence.enabled=true --set replicaCount=3 .
```
Wait until nodes are up
```
$ kubectl get pods
NAME                  READY   STATUS    RESTARTS   AGE
myrabbit-rabbitmq-0   1/1     Running   0          6m13s
myrabbit-rabbitmq-1   1/1     Running   0          5m12s
myrabbit-rabbitmq-2   1/1     Running   0          4m10s
````
Prepare the upgrade, in this case I just set a label for the pods
```
$ export RABBITMQ_PASSWORD=$(kubectl get secret --namespace "default" myrabbit-rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)
$ export RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace "default" myrabbit-rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)
$ helm upgrade myrabbit -f values.yaml --set podLabels="test: test" --set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE --set auth.password=$RABBITMQ_PASSWORD --set replicaCount=3 .
```
Check the progress:
```
$ kubectl get pods --show-labels 
NAME                  READY   STATUS              RESTARTS   AGE     LABELS
myrabbit-rabbitmq-0   1/1     Running             0          6m56s   app.kubernetes.io/instance=myrabbit,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=rabbitmq,controller-revision-hash=myrabbit-rabbitmq-6849dd54f7,helm.sh/chart=rabbitmq-8.26.0,statefulset.kubernetes.io/pod-name=myrabbit-rabbitmq-0
myrabbit-rabbitmq-1   1/1     Running             0          5m55s   app.kubernetes.io/instance=myrabbit,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=rabbitmq,controller-revision-hash=myrabbit-rabbitmq-6849dd54f7,helm.sh/chart=rabbitmq-8.26.0,statefulset.kubernetes.io/pod-name=myrabbit-rabbitmq-1
myrabbit-rabbitmq-2   0/1     ContainerCreating   0          3s      app.kubernetes.io/instance=myrabbit,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=rabbitmq,controller-revision-hash=myrabbit-rabbitmq-c5dd57676,helm.sh/chart=rabbitmq-8.26.0,statefulset.kubernetes.io/pod-name=myrabbit-rabbitmq-2,test=test
```
As you can see the node `myrabbit-rabbitmq-2` it's being created with the label `test=test`.

Wait until all the the nodes are updated
```
$ kubectl get pods --show-labels 
NAME                  READY   STATUS    RESTARTS   AGE     LABELS
myrabbit-rabbitmq-0   1/1     Running   0          74s     app.kubernetes.io/instance=myrabbit,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=rabbitmq,controller-revision-hash=myrabbit-rabbitmq-cd5b46ff9,helm.sh/chart=rabbitmq-8.26.0,statefulset.kubernetes.io/pod-name=myrabbit-rabbitmq-0,test=test
myrabbit-rabbitmq-1   1/1     Running   0          2m34s   app.kubernetes.io/instance=myrabbit,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=rabbitmq,controller-revision-hash=myrabbit-rabbitmq-cd5b46ff9,helm.sh/chart=rabbitmq-8.26.0,statefulset.kubernetes.io/pod-name=myrabbit-rabbitmq-1,test=test
myrabbit-rabbitmq-2   1/1     Running   0          3m22s   app.kubernetes.io/instance=myrabbit,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=rabbitmq,controller-revision-hash=myrabbit-rabbitmq-cd5b46ff9,helm.sh/chart=rabbitmq-8.26.0,statefulset.kubernetes.io/pod-name=myrabbit-rabbitmq-2,test=test
```

**Comment by christopheblin** [comment]
@rafariossaa Thanks for your time, I really really appreciate !

Unfortunately, I dont have time anymore on my side to dig deeper but you've convinced me that I'm doing something wrong somewhere with PVC/PV and/or storageClass so I'll close this issue

I'll use the OnDelete strategy for the moment because it works, and I hope I can grab some time in the future to switch back to proper RollingUpdate

I want to thank you again for your time and for the very relevant and brilliant stuff you've put here :+1:

**Comment by rafariossaa** [comment]
Hi @christopheblin, 
  You are welcome, thanks you. This kind of issues are not easy to debug because they use to be k8s cluster related.
  Please, don't hesitate to reopen this issue is you get more information on it.

**Comment by imjoseangel** [comment]
Hi! I can say, the issue is related to how managed disk in Azure are working. When doing rabbitmq upgrade there are no issues.

The issue comes when having a cluster upgrade.

Here is properly explained: https://portworx.com/blog/understand-resolve-warning-failed-attach-volume-warning-failed-mount-errors-kubernetes-azure/
