### ISSUE TITLE
[RabbitMQ] Headless port name hard coded

### ISSUE THREAD

**Issue by danvy** [bitnami/charts#8481]
**Which chart**:
RabbitMQ 8.21.12
**Describe the bug**
https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/svc-headless.yaml
Is actually
spec:
  clusterIP: None
  ports:
    - name: {{ .Values.service.epmdPortName }}
      port: 4369
      targetPort: epmd
    {{- if or (.Values.service.portEnabled) (not .Values.auth.tls.enabled) }}
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
    {{- end }}
And should be
spec:
  clusterIP: None
  ports:
    - name: {{ .Values.service.epmdPortName }}
      port: 4369
      targetPort: epmd
    {{- if or (.Values.service.portEnabled) (not .Values.auth.tls.enabled) }}
    - name: {{ .Values.service.portName}}
      port: {{ .Values.service.port }}
      targetPort: amqp
    {{- end }}

**To Reproduce**
1. Deploy the chart
2. check headless port name

**Expected behavior**
.Values.service.portName should be applied to headless service too

**Version of Helm and Kubernetes**:

- Output of `helm version`:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
This would prevent Istio warning :)

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. Would you like to submit a PR with the fix?
