### ISSUE TITLE
[bitnami/elasticsearch] Support custom labels for servicemonitor.

### ISSUE THREAD

**Issue by FuyuanChu** [bitnami/charts#8485]
**Which chart**:
The name (and version) of the affected chart.

`bitnami/elasticsearch` `17.5.2`

**Is your feature request related to a problem? Please describe.**

Prometheus-operator allows Prometheus to scrape ServiceMonitors which match labels in `serviceMonitorSelector`.
Custom labels need to add to the ServiceMonitor if Prometheus in a cluster configured `serviceMonitorSelector`.

**Describe the solution you'd like**

Add a new value to support custom labels for servicemonitor.

**Comment by javsalgar** [comment]
Hi,

In other charts we have the serviceMonitor.selector value, would that work?

**Comment by FuyuanChu** [comment]
`serviceMonitor.selector` is used to select the endpoint of pods. But on the other hand, Prometheus also has a selector to select the serviceMonitor.

```
prometheus --- select by label ---> serviceMonitor --- select by label ---> endpoints
```

If there are many dedicated Prometheus instances for different workloads, Prometheus will use a `serviceMonitorSelector` to select `serviceMonitors`  by labels. That's why we need to add custom labels to `serviceMonitor`.

**Comment by juan131** [comment]
I see @FuyuanChu 

I think you're looking for the `metrics.serviceMonitor.labels` property that we have in chart such as Geode, see:

- https://github.com/bitnami/charts/blob/master/bitnami/geode/values.yaml#L1030

Would you like to contribute a PR adding this parameter?

**Comment by FuyuanChu** [comment]
Yes, my pleasure. I will be working on this.
