### ISSUE TITLE
[bitnami/rabbitmq] Liveness probe fails and crashes the pod?

### ISSUE THREAD

**Issue by ST-Apps** [bitnami/charts#8487]
**Which chart**:
rabbitmq-8.24.12

**Describe the bug**
Installed the chart yesterday, woke up and found 130+ restarts on my pod.
The events list contains an infinite sequence of "Unhealthy" -> "Killing" -> "Created".

This is the liveness command: `/bin/bash -ec rabbitmq-diagnostics -q ping`.

I did some testing, here are my results:

1. Running the command manually in a pod's shell: the pod crashes
2. Running `/bin/bash rabbitmq-diagnostics -q ping`: `/opt/bitnami/rabbitmq/sbin/rabbitmq-diagnostics: line 21: rabbitmq-diagnostics/rabbitmq-env: No such file or directory`
3. Running `rabbitmq-diagnostics -q ping`: `Ping succeeded`

**To Reproduce**

1. Install the chart
2. Leave it running for a while to see it restarting
3. Eventually follow the steps in the previous paragraph

**Expected behavior**
Liveness should work.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server is at 1.20.11 but I don't have networking on my work pc now so I can't paste it here.
```

**Comment by carrodher** [comment]
I'm not able to reproduce the issue on my side, after some time, the pod is up and running without any issue. I was checking the code and those probes were added 1 year ago (see https://github.com/bitnami/charts/pull/4747), so it shouldn't be an issue with the command used to check if the pod is healthy.

What values are you using to install the chart?

**Comment by QuingKhaos** [comment]
@ST-Apps can you show your `values.yaml` you're using to install the chart? Are you overriding the rabbitmq image to a non bitnami-one?
