### ISSUE TITLE
[Nginx ingress] How do I add a custom configmap to nginx ingress controller?

### ISSUE THREAD

**Issue by dc232** [bitnami/charts#8511]
Hi I would like to add a custom Nginx configmap to the bitnami helm chart for Nginx
currently, in terraform I have created a config map that gets added into the default namespace before the helm chart is installed, however for some reason despite this the  ingress controller ignores the config map until I delete the pod and allow the deployment to "rebuild" the pod

config so far

```
resource "kubernetes_config_map_v1" "example" {
  metadata {
    name = "nginx-ingress-controller"
  }

  data = {
    ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
    ssl-protocols: "TLSv1.2 TLSv1.3"
    ssl_prefer_server_ciphers: "false"
    proxy-connect-timeout: "300"
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
    client-max-body-size: "80m"
  }
}
```
```
resource "helm_release" "nginx_ingress" {
  depends_on = [kubernetes_config_map_v1.example]
  name       = "nginx-ingress-controller"

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "nginx-ingress-controller"
```

Question:
can I add the above config map into nginx-ingress-controller resource directly so that the config map is created and loaded at the same time as ingress creation?

**Comment by javsalgar** [comment]
Hi,

In the chart we have the `extraDeploy` array that allows you to add custom objects when deploying the chart. Could you try using that?

**Comment by dc232** [comment]
Hi @javsalgar thank you, was wondering which template makes use of the extraDeploy params?and are there any examples of what the array should like syntactically?

**Comment by javsalgar** [comment]
Hi,

This example is for RabbitMQ Cluster Operator, but the syntax is just the same. It's an array with objects

https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq-cluster-operator#deploying-extra-resources
