### ISSUE TITLE
[bitnami/etcd] --quota-backend-bytes can't be set

### ISSUE THREAD

**Issue by jianhaiqing** [bitnami/charts#8516]
**Which chart**:
all of versions

**Is your feature request related to a problem? Please describe.**
The default quota-size-bytes of etcd is 0, and corresponding  quota is set 2GB, and the value can be confirmed from metrics etcd_server_quota_backend_bytes. 

**Describe the solution you'd like**
Custom the quota-size-bytes 8GB

**Describe alternatives you've considered**
corresponding env is  ETCD_QUOTA_BACKEND_BYTES;

**Additional context**

**Comment by marcosbc** [comment]
Hi @jianhaiqing, you should be able to set that option with `extraEnvVars`/`extraEnvVarsCM`/`extraEnvVarsSecret`, or via `--set 'args[0]=--quota-backend-bytes' --set 'args[1]=...'. Refer to the [README](https://github.com/bitnami/charts/tree/master/bitnami/etcd) for the complete list of flags.

**Comment by abdennour** [comment]
it does not :(  work @marcosbc 

it says

```sh
/opt/bitnami/scripts/etcd/entrypoint.sh: line 26: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

i didn't the same as you suggested: 

```yaml
args:
  - --quota-backend-bytes
  - 8GB
```

600+ employees are now blocked. Thank you for your support

**Comment by marcosbc** [comment]
@abdennour You are right, there was a typo in my message. It should be like this when using CLI arguments:

```
--set 'args[0]=/opt/bitnami/scripts/etcd/run.sh' --set 'args[1]=--quota-backend-bytes' --set 'args[2]=...'
```

The reason is that the entrypoint script calls `exec` with the arguments provided by the container's `CMD`, but it does not call the `etcd` script automatically (which is done by `run.sh`).
