### ISSUE TITLE
How to Enabling MirrorMaker 2.0 with TLS

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#8517]
Hi All,
 
We are trying to enableTLS for MirrorMaker 2.0(connect-mirror-maker.sh) for apache Kafka 3.0.I have used below parameters but it has not succeeded.
 
Please confirm the points below. 

TLS feature is available for MirrorMaker 2.0(connect-mirror-maker.sh),If yes can you please share a blog/configuration to enable it.
```
source.ssl.truststore.location=/home/kafka.truststore.jks
source.ssl.truststore.password=********
source.ssl.keystore.location=/home/kafka.keystore.jks
source.ssl.keystore.password=******
source.ssl.key.password=******
source.security.inter.broker.protocol=SSL
source.ssl.endpoint.identification.algorithm=
target.ssl.truststore.location=/home//kafka.truststore.jks
target.ssl.truststore.password=*******
target.ssl.keystore.location=/home/kafka.keystore.jks
target.ssl.keystore.password=******
target.ssl.key.password=******
target.security.inter.broker.protocol=SSL
target.ssl.endpoint.identification.algorithm=
```
Thanks,
Bharath Reddy

**Comment by javsalgar** [comment]
Hi,

As far as I'm concerned, the container does not have automatic support for MirrorMaker. I'm afraid I don't have experience with MirrorMaker, but if you have the exact steps that to enable it, then it would be something worth adding as a PR.
