### ISSUE TITLE
Add a pre-commit hook or CI check to ensure we don't change the kubeapps or upstreamed charts

### ISSUE THREAD

**Issue by prydonius** [bitnami/charts#852]
The charts in the upstream/ folder and the Kubeapps chart in bitnami/kubeapps are synced from upstream sources, and so should not be changed in this repo.

In order to ensure changes like https://github.com/bitnami/charts/commit/a3cccff4fd868eca938b975270dd499f23fc54b9#diff-c07caee8dd3223fc9f3e6f2f73efce75R22 don't happen, we should add a pre-commit hook or CI script to ensure that there are no changes being made in upstream/ or bitnami/kubeapps.

cc @andresmgot @carrodher @migmartri

**Comment by juan131** [comment]
I think @andresrc worked on this integration. Any thoughts?

**Comment by prydonius** [comment]
A pre-commit hook might be harder, since the sync jobs will need to be able to commit. Adding a CI job might be simpler since that way we can just check for changes to those charts in PRs and fail them if there are.
