### ISSUE TITLE
[bitnami/elasticsearch] How to add nodes to existed elasticsearch cluster

### ISSUE THREAD

**Issue by revengel** [bitnami/charts#8526]
I have already installed elasticsearch cluster (from bitnami elasticsearch chart).
How I can add elasticsearch nodes with another storage class to this cluster elasticsearch nodes with another storage?
I want to move old indices (via curator) to es nodes with slow disk...

**Comment by carrodher** [comment]
You can use the `master.replicas` value to set the desired number of Elasticsearch master-eligible nodes. Consider using an odd number of master nodes to prevent "split brain" situation. See: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/modules-discovery-voting.html.
In the same way, using `coordinating.replicas` you can customize the number of Elasticsearch coordinating-only nodes.
And, you can also do the same for Elasticsearch data nodes using `data.replicas` and Elasticsearch ingest nodes using `ingest.replicas`.

Whit the above commands you will be able to customize the number of nodes deployed for every kind.

Then you can customize the StorageClass for the master or data nodes by setting `master.persistence.storageClass` and/or `data.persistence.storageClass`

**Comment by revengel** [comment]
Sorry, but I have a different problem.

I need to have different types of data nodes in one ES cluster (**ES Hot-Warm-Cold Architecture**) (for example):

* 3 **HOT** es data nodes (with fast ssd disks)
* 3 **WARM** es data nodes (with hdd disks) - for old indexes
* 3 **FROZEN** es data nodes (with hdd disks) - for old indexes

Is it possible to achieve this using bitnami elasticsearch helm chart?

**Comment by Mauraza** [comment]
Hi @revengel,

Please note ES Hot-Warm-Cold Architecture isn't supported in this chart as can see in previously in this issue: #7244

**Comment by fmulero** [comment]
To be perfectly blunt, at the moment we don't have any plan to support it. Anyway If you would like to contribute to this Helm chart, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
