### ISSUE TITLE
[bitnami/kibana] manage TLS ingress certificate outside of chart

### ISSUE THREAD

**Issue by discostur** [bitnami/charts#8528]
**Which chart**:
bitnami/kibana latest version

**Describe the bug**
Regarding the values.yaml file it should be possible to manage certificates outside of the cluster: 

https://github.com/bitnami/charts/blob/master/bitnami/kibana/values.yaml#L335

However, the secrets-array 

```bash
secrets: []
``` 

is not even referenced in the helm template files - so it is not used. Also i cannot see more details in the README.md ... 

I thought that i can provide any existing secret which is managed outside of the helm chart. 

Regards,
Kilian

**Comment by migruiz4** [comment]
Hi @discostur,

Thank you very much for reporting this issue! I have created this PR #8536 fixing the issue with `ingress.secrets`.

Let me know if it works for you.

**Comment by discostur** [comment]
@migruiz4 looks good to me - thanks for the PR ;)
