### ISSUE TITLE
[bitnami/logstash] Use of K8s Secret in input block of logstash.conf Configmap

### ISSUE THREAD

**Issue by chferng** [bitnami/charts#8529]
I have successfully configured and launched the Logstash with the input/filter/output block in the **logstash.conf** mounted as configmap but without TLS enabled. I have created the `.crt` and `.key` as "logstash-crt-key" as K8s secret mounting it via "secretVolumes" in the values YAML file:

```yaml
secretVolumes: # will be be mounted to /etc/secrets/<name>
  -logstash-crt-key
```

whereas in the logstash.conf CM, I referenced them in the following input block

```
tcp {
    port => 5054
    codec => "json"
    ssl => true
    ssl_certificate_authorities => ["/etc/secret/logstash-crt-key/tls.crt"]
    ssl_cert => "/etc/secret/logstash-crt-key/tls.crt"
    ssl_key => "/etc/secret/logstash-crt-key/tls.key"
    ssl_verify_mode => "peer"
    tls_min_version => 1.2
  }
```
  
After performing a helm upgrade, the Logstash pod seems to be started properly but then goes into a crash loop until it backs off. When doing pod describe, I noticed the secret volume "logstash-crt-key" is not mounted and suspecting this could be the cause, together with the CM referencing a non-existent secret and found these errors in the logs

```console
This setting must be a path
File does not exist or cannot be opened /etc/secret/logstash-crt-key/tls.crt
ssl_certificate => "/etc/secret/logstash-crt-key/tls.crt"

This setting must be a path
File does not exist or cannot be opened /etc/secret/logstash-crt-key/tls.key
ssl_key => "/etc/secret/logstash-crt-key/tls.key"
```

What is the correct way to mount the secret "logstash-crt-key" in the Bitnami value YAML and reference it in the **logstash.conf**? And what will be the resultant path (still under `/etc/secret`)?

**Comment by juan131** [comment]
Hi @chferng 

It seems it is not an issue related to the Bitnami Logstash chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
