### ISSUE TITLE
[binami/kong] Invalid value: []string(nil): must have at least one stored version]

### ISSUE THREAD

**Issue by thanhtai9606** [bitnami/charts#8535]
**Which chart**: binami/kong  5.0.0
The name (and version) of the affected chart

**Describe the bug**
I already changed from apiextensions.k8s.io/v1beta =>  apiextensions.k8s.io/v1. 
But after install helm chart I received this error

**Version of Helm and Kubernetes**: 1.22

- Output of `helm version`: v3.7.2

```
Error: INSTALLATION FAILED: failed to install CRD crds/custom-resource-definitions.yaml: CustomResourceDefinition.apiextensions.k8s.io "kongclusterplugins.configu
ration.konghq.com" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storag
e version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]
```

**Comment by javsalgar** [comment]
Hi,

It seems to me that the CRDs that we are using might be outdated. If you check these https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml

do you see any difference? If so, would you like to submit a PR changing these CRDs?

**Comment by thanhtai9606** [comment]
I working fine, thank you so much !!!
