### ISSUE TITLE
[bitnami/redmine] Cannot create release with updateStrategy to Recreate

### ISSUE THREAD

**Issue by DeLoWaN** [bitnami/charts#8539]
**Which chart**:
bitnami/redmine 17.1.3

**Describe the bug**
On Kubernetes, cannot create release with updateStrategy to **Recreate**.

**To Reproduce**
Create a deployment of redmine with `updateStrategy.type` set to `Recreate`. You end up with this error:
```
Error: Deployment.apps "redmine" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

**Expected behavior**
The release is created

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by danvy** [comment]
I confirm this problem.
Default values.yaml has updateStrategy.rollingUpdate set to {}. This is not compatible with updateStrategy.type set to Recreate.
https://github.com/bitnami/charts/blob/b16b22c009f1ed052b64cdb9959a26d475311369/bitnami/wordpress/values.yaml#L268

**Comment by carrodher** [comment]
Thanks for creating the PR, the team should review PRs and provide feedback usually within a business day
