### ISSUE TITLE
[redis-cluster]: what SLA  you suggest when we implement this cluster

### ISSUE THREAD

**Issue by avalancheindia** [bitnami/charts#8544]
If you have done tests please do share the result details as possible

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
