### ISSUE TITLE
[bitnami/ghost] Access Denied With New PVC

### ISSUE THREAD

**Issue by JoshuaLyle** [bitnami/charts#8550]
**Which chart**:
Bitnami/ghost 15.1.8

**Describe the bug**
There doesn't seem to be a way to allow a PVC to be recreated if accidentally deleted. It's content only seems to host things like themes and images whereas the core of the website is hosted in the DB. If the PVC for the app gets deleted, recreating it doesn't seem to bring up a workable website (without images/themes). It always errors out with below just like #7014

```
Error: EACCES: permission denied, copyfile '/opt/bitnami/ghost/versions/.../core/frontend/services/settings/default-routes.yaml' -> '/opt/bitnami/ghost/versions/.../content/settings/routes.yaml'
```

I've tried every combination of `ghostSkipInstall`, `volumePermissions.enabled`, setting the fsGroup to 999 and 1001, and setting the user as root and trying to manually chown everything to ghost:ghost or 1001:1001 and haven't gotten anywhere.

**To Reproduce**
1. Deploy new installation of ghost `helm install website bitnami/ghost -n website -f website.yml`
2. Delete the ghost deployment and PVC (not the MariaDB)
3. Upgrade the helm deployment to recreate the ghost deployment and new PVC

**Expected behavior**
I expect the site to come up without the content pointed to by the symlinks in /opt/bitnami/ghost to /bitnami/ghost (images and themes) but the actual text of the website (the articles).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}```
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I'm not sure if this an issue baked into the bitnami ghost image or with something I'm missing with the helm chart, but there I seem to be missing something on how to reinitialize a ghost deployment with an existing DB.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
