### ISSUE TITLE
clusterResourceNamespace like offical chart 

### ISSUE THREAD

**Issue by suikast42** [bitnami/charts#8559]
**Which chart**:
version 0.1.29 bitnami/cert-manager   

The official helm chart of the cert-manager  provides an option called  "clusterResourceNamespace"
For the [values.yaml](https://github.com/helm/charts/blob/master/stable/cert-manager/values.yaml) of the official chart 

`
Override the namespace used to store DNS provider credentials etc. for ClusterIssuer
resources. By default, the same namespace as cert-manager is deployed within is
used. This namespace will not be automatically created by the Helm chart.
clusterResourceNamespace: ""
`

I don't see any option like this in the bitnami charts.

**Comment by alemorcuq** [comment]
Good catch, @suikast42! Would you be interested in contributing with a PR?

**Comment by suikast42** [comment]
I would but I am not so familar with helm
