### ISSUE TITLE
[stable/redis] Making chart deployment HA with Sentinels?

### ISSUE THREAD

**Issue by pentago** [bitnami/charts#856]
Any chance the [stable/redis](https://github.com/helm/charts/tree/master/stable/redis) chart can be refactored to provide genuine HA setup with **Redis Sentinels** (_proper failover and slave promotion to master nodes_)?

Official [stable/redis-ha](https://github.com/helm/charts/tree/master/stable/redis-ha) chart isn't working properly, it's not very production-friendly and PRs are merged at quite slow pace.

I think plenty of people would prefer Bitnami-built Redis HA chart with customizable persistence, unlike [incubator/redis-cache](https://github.com/helm/charts/tree/master/incubator/redis-cache) chart which does Sentinels but not persistence too (_this is a big deal for lots of deployments and companies_). This chart could be used as a starting poing I guess.

Thanks in advance and looking forward to hearing opinions.

**Comment by javsalgar** [comment]
I have my concerns with this. Basically when the a slave gets promoted to master. How will the k8s services point to the correct master? At the moment, the solution that redis-ha proposes is to have some logic in the container that talks to the kubernetes API server and updates the labels accordingly. I am not very convinced by this approach as it is a bit obscure. That's the main reason we prefer using the native kubernetes failover solution in the `redis` chart.

@prydonius @sameersbn  what's your take on this?

**Comment by pentago** [comment]
In fact, when I look into **stable/redis** chart it's totally unclear how it handles failover.
What happens exactly when and if the master fails. I understand that if pod is unhealthy it gets evicted from handling traffic from the service but do any of healthy slaves gets promoted to the master automatically? I guess not, at least it's not clear how and if at all occurs.

**Comment by pentago** [comment]
Yeah, slaves are only read-only after master dies. That's not really HA, more like failover, in a similar way as mysql/mariadb charts work.

**Comment by javsalgar** [comment]
Hi,

I did not know about `redis-sentinel-micro`. I suppose that it would be responsible of updating the k8s labels for the services to point to the new master. If it's properly maintained, using it could make sense to have master promotion. Thanks for sharing :)

**Comment by pentago** [comment]
It doesn't need this  be micro per se, it can be literally anything thats puvlic and vetted as far as I'm concerned. Any other thoughts?

**Comment by javsalgar** [comment]
Ping @prydonius @sameersbn

**Comment by javsalgar** [comment]
PR https://github.com/helm/charts/pull/13112 should cover your use case

**Comment by javsalgar** [comment]
@pentago could you confirm that https://github.com/helm/charts/pull/13112 is what you were looking for?

**Comment by pentago** [comment]
Looks like it but since asking this I used official redis chart which has failover option. Not sure how these two compare but will test when I get some time. Thanks!

**Comment by javsalgar** [comment]
Let us know any feedback you have :)
