### ISSUE TITLE
Airflow initdb taking so much time using  Azure Fileshares

### ISSUE THREAD

**Issue by JagadeepK01** [bitnami/charts#8564]
**Which chart**:
Airflow 10.3.1

**Describe the bug**
I'm running Airflow on AKS. I mounted Azure file shares for dags, plugins and logs.
Dags file share is having around 300 dags. Webserver pod takes more than 9-10 mins to do airflow init db. For the same number of dags, if I use Git side car containers , webserver pod takes around 3-4 minutes to complete airflow init db. Why is airflow init db taking so much to complete init db if using azure file shares. 

Note: As the number of dags increases, init db takes so much time. 

**To Reproduce**
Install airflow on AKS and use file shares . Put some 300+ dags in file share and restart webserver.

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v3.5.3

```

- Output of `kubectl version`:

```
1.13.15

```

**Additional context**

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Airflow Helm chart but about how the application is being persisted using the specific AKS Fileshares technology.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by JagadeepK01** [comment]
@carrodher I have not made these file shares as Persistent Volumes. I have directly mounted them to web / scheduler pods as below

```
- name: azurefileshare-dag
    azureFile:
      secretName: sa-secret
      shareName: airflow-dag
      readOnly: false
```

Do you think mounting these file shares as Persistent Volumes can help in this scenario?

**Comment by carrodher** [comment]
You can give a try to this kind of customization but, to be honest I didn't play with Azure Filseshare system so unfortunately I can't provide any valuable information about this topic
