### ISSUE TITLE
[bitnami/argo-cd] tlsCerts not created or loaded

### ISSUE THREAD

**Issue by WhiteRabbitDE** [bitnami/charts#8567]
**Which chart**:
argo-cd:2.0.20

**Describe the bug**
I think there is a bug in the helm chart regarding the tlsCerts. In the repo-server deployment https://github.com/bitnami/charts/blob/82b3b205e8afce5773c728dbc66fe64094fd5ac2/bitnami/argo-cd/templates/repo-server/deployment.yaml#L210

the mount refers to `{{- if .Values.config.tlsCerts }}`

but the configMap is only created if `{{- if .Values.tlsCerts }}`

https://github.com/bitnami/charts/blob/87c43a2aa61f0e756f2f6be2092eb3e2c5997894/bitnami/argo-cd/templates/tls-certs-cm.yaml#L1

I tried to include my tls certs in the chart and ended up with an error that the configMap is missing. If i move the tlsCerts out of config, the cm is created but my certs are not included.

**To Reproduce**

1. Try a fresh deployment of the chart 
2. Notice that the cm "argocd-tls-certs-cm" is not created

**Expected behavior**
The CM should be created when tlsCerts exists in .Values.config.tlsCerts and the certs should be created in the CM

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
You are right, this seems like a typo. Would you like to file a PR addressing this?
