### ISSUE TITLE
Support for extraArgs 

### ISSUE THREAD

**Issue by suikast42** [bitnami/charts#8569]
I am facing up to this [issue of cert-manager](https://github.com/jetstack/cert-manager/pull/819)
I can't see any extraArgs argument in the helm chart.
A lot of exter[Volume|env] and so on but noting related to the args. 

The only option is the args[] itself bur as I understand, this option override the default right?

**Comment by carrodher** [comment]
You're right, the only option to modify args are:
- `controller.args`
- `webhook.args`
- `cainjector.args`
and the purpose of those parameters is to override the default args of every component.

At this moment there is not a parameter to add extraArgs as we have in other Helm charts. Would you like to create a PR adding this option to this chart?

**Comment by suikast42** [comment]
I would but I am not so familar with helm.

**Comment by carrodher** [comment]
I just created an internal task to do it on our side, since it is a new feature and not a bug we will work on it according to other priorities the team has, that's why I can't provide an ETA.
To prevent the issue from being closed automatically by the stale bot I will add the `on-hold` label

**Comment by apeschel** [comment]
@carrodher I think this is actually a bug: https://github.com/bitnami/charts/issues/10574
