### ISSUE TITLE
[bitnami/postgresql] Allow usage of different StorageClass between primary and readReplicas

### ISSUE THREAD

**Issue by link-webcreations** [bitnami/charts#8573]
**Which chart**:
```
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.14.4
```

**Is your feature request related to a problem? Please describe.**
We are using AKS, so we have a limited amount of AzureDisk by nodes (SKU limit).
As we are using AzureDisks for postgresql persistence, we cannot enable replication in order to benefit of a read replicas for backup/operations purpose (it will use too many disks).

Since some month we have now the ability to create VHD disks on Azure Storage Accounts. Unfortunatly the chart do not allow to have different StorageClass between the primary and the readReplicas. 

So the idea would be to have for instance:
```
primary.persistence.storageClass = azuredisk-csi-premium
readReplicas.persistence.storageClass = vhd-westeurope-standard
```

**Describe the solution you'd like**
New values impacting both `statefulset.yaml` and `statefulset-readreplicas.yaml`:
`primary.persistence.storageClass` emptyString by default (overrides `persistence.storageClass` if present)
`readReplicas.persistence.storageClass` emptyString by default  (overrides `persistence.storageClass` if present)

**Extra**
This would be useful for others DB engine, like mariadb and mongodb :)

**Comment by carrodher** [comment]
Thanks for explaining your use case, would you like to create a PR adding this feature? Bitnami team will be happy to review it and provide feedbacl
