### ISSUE TITLE
Redis persistence 

### ISSUE THREAD

**Issue by bmgante** [bitnami/charts#8578]
Hello,
I am using this redis helm chart with 3 nodes redis-sentinel and persistence enabled.
TTL of data inserted is set to 7 days but i noticed that while older data is being deleted in PVC associated to replica nodes it is not happening for PVC associated to master node, till it crashes with no available space.

I have the same size for master and replicas pvc (50GB).

Is is expected thata PVC associated with master node has a higher storage consumption and could explain this behaviour?

Thanks

**Comment by bmgante** [comment]
Example that confirms aof file for nifi-redis-0 is much bigger than for nifi-redis-1 and nifi-redis-2.

nifi-redis-**node-0**:/data$ ls -lrth
total 22G
drwxrws--- 2 root 1001  16K Dec 24 10:56 lost+found
-rw-r--r-- 1 1001 1001 4.0G Jan  5 08:13 dump.rdb
-rw-rw-r-- 1 1001 1001  18G Jan  5 17:39 appendonly.aof


nifi-redis-**node-1**:/data$ ls -lrth
total 12G
drwxrws--- 2 root 1001  16K Dec 24 10:56 lost+found
-rw-r--r-- 1 1001 1001 4.0G Jan  5 08:11 dump.rdb
-rw-r--r-- 1 1001 1001 7.8G Jan  5 17:37 appendonly.aof

nifi-redis-**node-2**:/data$ ls -lrth
total 12G
drwxrws--- 2 root 1001  16K Dec 24 10:57 lost+found
-rw-r--r-- 1 1001 1001 4.0G Jan  5 08:13 dump.rdb
-rw-r--r-- 1 1001 1001 7.8G Jan  5 17:40 appendonly.aof

**Comment by bmgante** [comment]
Problem is due to the fact that aof rewrite is not running automatically on master node.

Forcing rewrite, aof file decreases to the same size of replica nodes.

BEFORE:
```
I have no name!@nifi-redis-node-0:/data$ ls -lrth
total 22G
drwxrws--- 2 root 1001 16K Dec 24 10:56 lost+found
-rw-r--r-- 1 1001 1001 4.0G Jan 5 08:13 dump.rdb
-rw-rw-r-- 1 1001 1001 18G Jan 5 18:53 appendonly.aof
```

FORCE RE-WRITE:
```
I have no name!@nifi-redis-node-0:/data$ redis-cli -h 127.0.0.1 BGREWRITEAOF
Background append only file rewriting started
```

AFTER:
```
I have no name!@nifi-redis-node-0:/data$ ls -lrth
total 8.0G
drwxrws--- 2 root 1001 16K Dec 24 10:56 lost+found
-rw-r--r-- 1 1001 1001 4.0G Jan 5 08:13 dump.rdb
-rw-r--r-- 1 1001 1001 4.1G Jan 5 18:58 appendonly.aof
```

Now the question is why rewirte is not running automatically in master node as happens in replica? 3 nodes have the same config:

```
I have no name!@nifi-redis-node-0:/data$ redis-cli -h 127.0.0.1 config get auto-aof-rewrite-percentage
1) "auto-aof-rewrite-percentage"
2) "100"
I have no name!@nifi-redis-node-0:/data$ redis-cli -h 127.0.0.1 config get auto-aof-rewrite-min-size
1) "auto-aof-rewrite-min-size"
2) "67108864"
```

Using redis 6.2.4.

**Comment by carrodher** [comment]
Thanks for the detailed information, after reading it I'm not sure if it is something related to the Bitnami Helm charts or the application itself since it seems the configuration is being properly applied to the different nodes.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by bmgante** [comment]
Indeed i´ve already understood the root cause, it is due to our daily shutdowns of the pods in staging environement (at night). 
The same problem is described here: https://github.com/sourcegraph/sourcegraph/issues/3300

Is there some place in the helm chart we could configure a command to be executed immediatly after container is running?

I´d need to run the command "redis-cli -h 127.0.0.1 BGREWRITEAOF" to manually for aof rewrite every time there is a restart.

**Comment by carrodher** [comment]
I'm glad you were able to solve the issue 🎉
