### ISSUE TITLE
A real distributed mem cache setup is required

### ISSUE THREAD

**Issue by schroedt** [bitnami/charts#8584]
**Which chart**:
`:latest` via helm

**Describe the bug**
Any page redirects to "A real distributed mem cache setup is required":

![image](https://user-images.githubusercontent.com/6430367/148385431-ba5db0a4-a5ee-478d-a387-473bfbc6925a.png)

**To Reproduce**

1. Install via helm (latest with external MariaDB and SMTP configuration):
```
helm upgrade --install -f ./iac/values.yaml owncloud bitnami/owncloud --namespace ds-owncloud
```

2. Install OIDC from Marketplace
3. Error occured on all pages

**Expected behavior**
Owncloud works

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
lachlanevenson/k8s-helm:latest
```

- Output of `kubectl version`:

```
lachlanevenson/k8s-kubectl:latest
```

**Additional context**
Fresh install.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-owncloud#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
