### ISSUE TITLE
[bitnami/keycloak] Feature keycloak.extraContainers[] in order to use SQL proxy

### ISSUE THREAD

**Issue by Jojoooo1** [bitnami/charts#8586]
**Which chart**:
[bitnami/keycloak] 6.0.0

**Is your feature request related to a problem? Please describe.**
It would be very useful to use an keycloak.extraContainers[] parameters in order to use additional sidecar containers, e. g. for a database proxy, such as Google's cloudsql-proxy.
This feature seems to be available in codecentric chart for example.

**Describe the solution you'd like**
Add an extraContainers[] parameters

**Comment by carrodher** [comment]
Thanks for doing this suggestion. Would you like to contribute by creating a PR to add this feature to the Helm chart? This approach is already used in other Bitnami charts so you can reuse the same code. The Bitnami team will be happy to review it and provide feedback.
