### ISSUE TITLE
Sonarqube externaldatabase.host extra quotes issue

### ISSUE THREAD

**Issue by Avtarsingh127** [bitnami/charts#8587]
I disabled the postgresql by adding the following in my values file.
```yaml
postgresql:
     enabled: false
```
Now when I pass `externalDatabase.host` (RDS DB endpoints), code is adding extra double quotes. Pod is failing because of the following error.

```
psql: error: could not translate host name ""development-xxxxxxxxxxxx.us-east-2.rds.amazonaws.com"" to address: Name or service not known
sonarqube 11:46:09.35 DEBUG ==> Executing SQL command:
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by Avtarsingh127** [comment]
> Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

Sure, I will create a PR for the fix.
