### ISSUE TITLE
Redis Sentinel container unable to run libos.sh calls due to read only /tmp folder

### ISSUE THREAD

**Issue by ghollies** [bitnami/charts#8588]
**Which chart**:
Redis Helm Chart 15.5.5 from sha `6d6b4d724f8501c1c235f90e4f967e20a4ff91cc`

**Describe the bug**
Summary:
The start-sentinel.sh script currently cannot run the retry_while function in libos.sh do to the following error:
`/opt/bitnami/scripts/libos.sh: line 358: cannot create temp file for here-document: Read-only file system`
This is preventing the sentinel startup script from retrying DNS requests, which can cause downstream problems during a small percentage of Redis deployments.

when running in sentinel mode, we noticed some race conditions when starting up pods which caused the sentinels to not all agree on who the master node was. Upon inspecting the pod logs we noticed:

```
$ kubectl logs redis-node-0 sentinel
/opt/bitnami/scripts/libos.sh: line 358: cannot create temp file for here-document: Read-only file system
1:X 06 Jan 2022 16:02:48.724 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 06 Jan 2022 16:02:48.724 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 06 Jan 2022 16:02:48.724 # Configuration loaded
1:X 06 Jan 2022 16:02:48.724 * monotonic clock: POSIX clock_gettime
1:X 06 Jan 2022 16:02:48.725 * Running mode=sentinel, port=26379.
1:X 06 Jan 2022 16:02:48.725 # Sentinel ID is 2a09ba7abbb41ee71e79087310d75f9809c3c815
...
```
the first line seems to be a failure to properly run the libos script attempting to retry dns lookups.
We have resolved it by adding an additional mount to the sentinel container by using `extraVolumeMounts`:
```yaml
sentinel:
  enabled: true
  extraVolumeMounts:
  - name: tmp
    mountPath: "/tmp"
```
note that the volume seems to already be defined and used by the redis container in the same pod

**To Reproduce**
helm deploy the chart with a values.yaml including
```yaml
sentinel:
  enabled: true
```

**Expected behavior**
No error in log on startup, and successful retries on dns lookups as needed

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:23:02Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Unfortunately, I'm not able to reproduce the issue using the latest version of the chart (15.7.1):
```console
$ helm install redis -n redis --create-namespace --set sentinel.enabled=true bitnami/redis

$ kubectl get pods -n redis
NAME           READY   STATUS    RESTARTS   AGE
redis-node-0   2/2     Running   0          4m28s
redis-node-1   2/2     Running   0          3m32s
redis-node-2   2/2     Running   0          2m20s
```

Can you try the same approach by using a clean namespace and the latest available chart version?

**Comment by guizaols** [comment]
@carrodher I tried the installation in a brand new namespace over here and the pods are still not running

**Comment by ghollies** [comment]
It looks like the line which was calling out to `libos.sh` as part of dns look up was removed, so i doubt this will happen exactly the same in the latest version:
https://github.com/bitnami/charts/commit/cfeb69f00d229cd957c387f382a1a42805e494a7#diff-8bf2ebfa2494dc7e62169b760334cb7ae0812a59a6a0d11e436b7d040e7e30caL308

but I guess is there a reason not to have /tmp as an empty dir for sentinel for these types of issues where bash needs to use /tmp for here-doc processing? It would also match what the redis container is already doing

**Comment by fmulero** [comment]
Sorry @ghollies I can't reproduce the issue in version 15.5.5 and neither in 15.7.1. Not sure where is the problem reported, but there is no reason at the moment to have that empty dir for `/tmp`

**Comment by guizaols** [comment]
I'm using the Redis sentinel in the GKE and after I allow the ports `6379 and 26379` in the firewall, uninstalled and installed again it's start to work.

I thought this very curious because I  have a Redis Cluster in the same cluster and namespace and this wasn't needed. Anyway now the things are running well over here.
