### ISSUE TITLE
Kafka Chart has a typo in StatefulSet EnvVars for KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS

### ISSUE THREAD

**Issue by osowski** [bitnami/charts#8589]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/kafka Version: 14.9.0

**Describe the bug**
The [Kafka StatefulSet](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L300) has a typo in the Line 300, attempting to set the `KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS` value. However, it should be `KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS` with no 'S' on INTERVAL.

You can see the desired setting in the Kafka documentation via https://kafka.apache.org/documentation/#brokerconfigs_log.retention.check.interval.ms

**To Reproduce**

Setting `.Values.logRetentionCheckIntervalMs` has no effect on the internal Kafka property `log.retention.check.interval.ms`, even though `KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS` is set.

**Expected behavior**

Setting `.Values.logRetentionCheckIntervalMs` should set the internal Kafka property `log.retention.check.interval.ms` correctly via the environment variable `KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS` (no S on INTERVAL)

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
_None_

**Comment by carrodher** [comment]
Thanks for reporting this issue, would you like to create a PR to fix the typo? The Bitnami team will be happy to review it and provide feedback!
