### ISSUE TITLE
Kafka Chart Has Incorrect Condition When It Configured to be Used With ".Values.auth.tls.existingSecrets" Parameter

### ISSUE THREAD

**Issue by phbruce** [bitnami/charts#8593]
## Which chart
https://github.com/bitnami/charts/tree/master/bitnami/kafka Version: 14.9.0

## Describe the bug
When setted the `.Values.auth.tls.existingSecrets` parameter, returns the follow error:

```bash
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
```

### 1. Use an Existing or Generate Keystores and Truststores

Scripts to Creation: https://github.com/confluentinc/confluent-platform-security-tools.

### 2. Create Secrets in Kubernetes

```bash
kubectl create secret generic dp-ume-kafka-secrets-0 --from-file=kafka.truststore.jks=./truststore/kafka.truststore.jks --from-file=kafka.keystore.jks=./keystore/kafka-0.keystore.jks
kubectl create secret generic dp-ume-kafka-secrets-1 --from-file=kafka.truststore.jks=./truststore/kafka.truststore.jks --from-file=kafka.keystore.jks=./keystore/kafka-1.keystore.jks
kubectl create secret generic dp-ume-kafka-secrets-2 --from-file=kafka.truststore.jks=./truststore/kafka.truststore.jks --from-file=kafka.keystore.jks=./keystore/kafka-2.keystore.jks
```

### 3. Install the Chart

```bash
helm install dp bitnami/kafka \
    --set replicaCount=3 \
    --set rbac.create=true \
    --set externalAccess.enabled=true \
    --set externalAccess.autoDiscovery.enabled=true \
    --set auth.clientProtocol=tls \
    --set auth.interBrokerProtocol=tls \
    --set "auth.tls.existingSecrets[0]=dp-ume-kafka-secrets-0" \
    --set "auth.tls.existingSecrets[1]=dp-ume-kafka-secrets-1" \
    --set "auth.tls.existingSecrets[2]=dp-ume-kafka-secrets-2" \
    --set auth.tls.password=$PASSWORD
```

## Expected Behavior

Setting `.Values.auth.tls.existingSecrets` should set the existing Secrets Kafka property correctly.

## How to fix

The config file bellow has a incorrect condition on the line 121. The correct way to check should be `{{- if (empty .Values.auth.tls.existingSecrets) }}` instead of `{{- if not (empty .Values.auth.tls.existingSecrets) }}`.

https://github.com/bitnami/charts/blob/2a9e44a916e760068326e541f907687201417089/bitnami/kafka/templates/scripts-configmap.yaml#L121

**Comment by carrodher** [comment]
Thanks for reporting this issue and the detailed explanation. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by arasic** [comment]
Just a small note for those using a yaml file, **existingSecrets** values should look like:

```
auth:
  interBrokerProtocol: tls
  clientProtocol: tls
  tls:
    type: jks
    existingSecrets: ["dp-ume-kafka-secrets-0", "dp-ume-kafka-secrets-1", "dp-ume-kafka-secrets-2"]
```
