### ISSUE TITLE
Redis chart not working with Istio

### ISSUE THREAD

**Issue by ricosega** [bitnami/charts#8596]
This issue still happens in version 15.6.10 of the Redis chart.
Do you have an update of what we have to do to make it work with Istio?

In my case am getting this messages when deployed in Sentinel mode:

```
1:S 07 Jan 2022 13:43:09.965 * Connecting to MASTER :0
1:S 15 Jan 2022 13:43:09.965 # Unable to connect to MASTER: Invalid argument
```

_Originally posted by @ricosega in https://github.com/bitnami/charts/issues/4713#issuecomment-1007349929_

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by ricosega** [comment]
@carrodher I do not think is an application issue caused by Redis or Istio itself, is more related in how Bitnami start scripts are made.

First of all I noticed the difference in the start of the nodes when istio-injection is enabled and disabled.

Here the log of the redis nodes when Istio is **disabled**:
```
└─[14:51]-(%)-[$] k -n redis logs -f redis-node-2 redis
 12:28:00.10 WARN  ==> redis-headless.redis.svc.cluster.local does not contain the IP of this pod: 192.168.225.72
 12:28:05.11 WARN  ==> redis-headless.redis.svc.cluster.local does not contain the IP of this pod: 192.168.225.72
 12:28:10.12 DEBUG ==> redis-headless.redis.svc.cluster.local has my IP: 192.168.225.72
 12:28:10.13 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD redis-cli -h redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
 12:28:10.15 INFO  ==> printing REDIS_SENTINEL_INFO=(redis-node-0.redis-headless.redis.svc.cluster.local,6379)
 12:28:10.15 DEBUG ==> Starting as replica node
1:C 07 Jan 2022 12:28:10.176 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Jan 2022 12:28:10.176 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Jan 2022 12:28:10.176 # Configuration loaded
1:S 07 Jan 2022 12:28:10.176 * monotonic clock: POSIX clock_gettime
1:S 07 Jan 2022 12:28:10.179 * Running mode=standalone, port=6379.
1:S 07 Jan 2022 12:28:10.179 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:S 07 Jan 2022 12:28:10.180 # Server initialized
1:S 07 Jan 2022 12:28:10.180 * Ready to accept connections
1:S 07 Jan 2022 12:28:10.180 * Connecting to MASTER redis-node-0.redis-headless.redis.svc.cluster.local:6379
1:S 07 Jan 2022 12:28:10.181 * MASTER <-> REPLICA sync started
```

And here the log of the redis nodes when Istio is **enabled**:
```
 14:12:08.20 DEBUG ==> redis-headless.redis.svc.cluster.local has my IP: 192.168.123.35
 14:12:08.23 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD redis-cli -h redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at redis.redis.svc.cluster.local:26379: Connection refused
 14:12:08.24 INFO  ==> printing REDIS_SENTINEL_INFO=(,)
 14:12:08.24 DEBUG ==> Starting as replica node
1:C 07 Jan 2022 14:12:08.264 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Jan 2022 14:12:08.264 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Jan 2022 14:12:08.264 # Configuration loaded
1:S 07 Jan 2022 14:12:08.265 * monotonic clock: POSIX clock_gettime
1:S 07 Jan 2022 14:12:08.266 * Running mode=standalone, port=6379.
1:S 07 Jan 2022 14:12:08.266 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:S 07 Jan 2022 14:12:08.266 # Server initialized
1:S 07 Jan 2022 14:12:08.266 * Ready to accept connections
1:S 07 Jan 2022 14:12:08.267 * Connecting to MASTER :0
1:S 07 Jan 2022 14:12:08.268 # Unable to connect to MASTER: Invalid argument
```

The difference is when istio is enabled the variable **REDIS_SENTINEL_INFO** is empty, this happens because istio-proxy sidecar container takes some seconds to be ready, until that moment any network connection to any other service will fail and that's why we get the message `Could not connect to Redis at redis.redis.svc.cluster.local:26379: Connection refused` therefore the variable REDIS_SENTINEL_INFO is empty and the connection fails.

In the start scripts the function **get_sentinel_master_info** is not exiting when value is empty or connection can't be established, there should be a retry on function or a check for the variables to be filled.
Anyway the best solution when working with Istio is to check if the sidecar container is ready.

I opened a PR with an example we could work on.

**Comment by carrodher** [comment]
Thanks for creating the PR, the team will review it during the day and share any feedback!

**Comment by ricosega** [comment]
PR #8598 rejected and closed. (No support for istio approved)
Created new PR #8641 which solves the issue adding a retry_while to the function get_sentinel_master_info to ensure it gets values or exits the script.
