### ISSUE TITLE
[bitnami/redis-cluster] slave can't find the new master after kubernetes nodes changed

### ISSUE THREAD

**Issue by ssolid2014** [bitnami/charts#8605]
**Which chart**:
redis-cluster

**Describe the bug**

I deployed the redis-cluster chart on my aws EKS cluster, and after I deleted one node and add a new node in the eks cluser, some redis-cluster pods got restarted and moved to other machines.

And now 2 slaves seem to have the master info on the old node that has been shutdown and can't connect to the new master.

Below is the info output of one of the slave
```
# Replication
role:slave
master_host:192.168.168.17
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_repl_offset:99088411
master_link_down_since_seconds:717231
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
```
The master host "192.168.168.17" actually does not exist anymore.

But the command "cluster info" & " cluster nodes" can show that the cluster info is correct, like this:
```
127.0.0.1:6379> CLUSTER INFO
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:12
cluster_my_epoch:8
cluster_stats_messages_ping_sent:4324494
cluster_stats_messages_pong_sent:4359098
cluster_stats_messages_sent:8683592
cluster_stats_messages_ping_received:4359098
cluster_stats_messages_pong_received:4324490
cluster_stats_messages_received:8683588
127.0.0.1:6379>
127.0.0.1:6379>
127.0.0.1:6379>
127.0.0.1:6379> cluster nodes
ee3e507a04a0509039a43084afc7a5012e5ce8e5 192.168.177.51:6379@16379 master - 0 1641659548000 12 connected 5461-10922
37cfbd1164a792ca8b3147c49fa23a1daa0a616f 192.168.238.52:6379@16379 slave ee3e507a04a0509039a43084afc7a5012e5ce8e5 0 1641659546157 12 connected
20adc2bdba125aed482a78863c88e96f837896bb 192.168.177.52:6379@16379 master - 0 1641659546000 11 connected 0-5460
86714b7d23a19186cfa3c57ef1b17863ed82ca19 192.168.172.129:6379@16379 master - 0 1641659548169 8 connected 10923-16383
bfe005fcd24119e570d3c3174d86bbce46e2ce79 192.168.238.53:6379@16379 slave 20adc2bdba125aed482a78863c88e96f837896bb 0 1641659547165 11 connected
a2bbe47ff95e7a1fd7fef8c0503b86fcf1fc44f3 192.168.238.54:6379@16379 myself,slave 86714b7d23a19186cfa3c57ef1b17863ed82ca19 0 1641659546000 8 connected
```

Is there a way to reform the cluster without losing data and let those 2 slaves connect to the correct master?

Thanks!

**To Reproduce**

1. deploy the redis cluster on EKS
2. add a new node into the kubernetes cluster
3. delete one node in the cluster
4. wait for the redis-cluster get restarted and moved to the new node

**Expected behavior**
the redis-cluster can connect to the correct master after the pods are restarted

**Version of Helm and Kubernetes**:

- Output of `helm version`:

3.7.2

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:35:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
In order to try to reproduce the issue on our side, can you share with us the parameters used to deploy the Helm chart? I mean, any values file or parameters used via `--set`

**Comment by ssolid2014** [comment]
@carrodher sorry for the late reply, I actually did not make much change, below are the diff result of the values.yaml:

`@@ -682,7 +685,7 @@ cluster:
 metrics:
   ## @param metrics.enabled Start a side-car prometheus exporter
   ##
-  enabled: false
+  enabled: true
   ## @param metrics.image.registry Redis&trade; exporter image registry
   ## @param metrics.image.repository Redis&trade; exporter image name
   ## @param metrics.image.tag Redis&trade; exporter image tag
@@ -723,7 +726,7 @@ metrics:
   serviceMonitor:
     ## @param metrics.serviceMonitor.enabled If `true`, creates a Prometheus Operator ServiceMonitor (also requires `metrics.enabled` to be `true`)
     ##
-    enabled: false
+    enabled: true
     ## @param metrics.serviceMonitor.namespace Optional namespace which Prometheus is running in
     ##
     namespace: ""
@@ -796,10 +799,15 @@ metrics:
 sysctlImage:
   ## @param sysctlImage.enabled Enable an init container to modify Kernel settings
   ##
-  enabled: false
+  enabled: true
   ## @param sysctlImage.command sysctlImage command to execute
   ##
-  command: []
+  command:
+    - /bin/sh
+    - -c
+    - |-
+      sysctl -w net.core.somaxconn=10000
+      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
   ## @param sysctlImage.registry sysctlImage Init container registry
   ## @param sysctlImage.repository sysctlImage Init container repository
   ## @param sysctlImage.tag sysctlImage Init container tag
@@ -820,7 +828,7 @@ sysctlImage:
   pullSecrets: []
   ## @param sysctlImage.mountHostSys Mount the host `/sys` folder to `/host-sys`
   ##
-  mountHostSys: false
+  mountHostSys: true
`

And after I deleted those 2 slave pods, the new slave pods can get the correct master info.

Thanks!

**Comment by carrodher** [comment]
I was trying to reproduce the issue but it is difficult to reach the same situation, it seems more a question about k8s itself and cluster management. For this kind of topic, we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
