### ISSUE TITLE
Different postgres.conf files for primary and read

### ISSUE THREAD

**Issue by leforthomas** [bitnami/charts#8606]
**Which chart**:
Postgresql

**Is your feature request related to a problem? Please describe.**
Is it possible to specify different postgres.conf values for primary and replicas. Typically I would like to have larger values for my read instances, more extended RAM for instance. At the moment it looks like the postgres.conf customisation applies to both.

**Describe the solution you'd like**
A specific section in the read readReplicas to specify postgres.conf values.

**Describe alternatives you've considered**

**Additional context**
My master is used to build the database and only the replicas are used for external queries.

**Comment by juan131** [comment]
Hi @leforthomas 

I'm afraid this scenario isn't supported. Currently, you can't use different configuration files depending on the node type when overriding the `postgresql.conf ` file using the `postgresqlConfiguration` parameter.

**Comment by leforthomas** [comment]
OK, thanks. I will try to tweak the chart files then.
