### ISSUE TITLE
Couchdb healthcheck(_up) cannot be used from a loadbalancer

### ISSUE THREAD

**Issue by ngspinu** [bitnami/charts#8617]
Unless require_valid_user=false you can't ping the VSI to see if couch is alive.
Would be nice to have an endpoint running for healtchecks.

**Comment by carrodher** [comment]
Can you double-check what asset are you using? CouchDB is not part of the Bitnami catalog

**Comment by ngspinu** [comment]
Apologies. This should've been on the Couchdb Repo not on charts. Closing.
