### ISSUE TITLE
Changelogs for helm charts?

### ISSUE THREAD

**Issue by mowies** [bitnami/charts#8620]
**Which chart**:

MongoDB (no specific version)

**Is your feature request related to a problem? Please describe.**
Where can I find the changelog for bitnami helm charts? I know that in the different READMEs, there are some notes on upgrading between major versions but I could not find any detailed changelog.

**Comment by javsalgar** [comment]
Hi,

I'm afraid we currently don't have a changelog document in our charts. The closest we would have is to check the history of the Chart.yaml file.

Example: https://github.com/bitnami/charts/commits/master/bitnami/airflow/Chart.yaml

**Comment by mowies** [comment]
That's unfortunate, but thanks for the hint though :)
Closing this then.
