### ISSUE TITLE
[bitnami/grafana-operator] Missing deployment.skipCreateAdminAccount field in grafana.yaml

### ISSUE THREAD

**Issue by yardenshoham** [bitnami/charts#8629]
**Which chart**:

grafana-operator

**Describe the bug**

One cannot control the deployment.skipCreateAdminAccount field of grafana.yaml

**Comment by carrodher** [comment]
`skipCreateAdminAccount` is part of the CRD which are not used to be customizable using values:

https://github.com/bitnami/charts/blob/d87dec202858e218f08470a8a28d5397426b6a6c/bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml#L4579

What is your use case? Do you have something in mind to be able to modify its value?

**Comment by yardenshoham** [comment]
This https://github.com/grafana-operator/grafana-operator/issues/659
