### ISSUE TITLE
[IMPROVEMENT] Support of min.insync.replicas configuration in parameters

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#8638]
**Which chart**:

The Kafka chart on 14.9.0 version.

**Is your feature request related to a problem? Please describe.**

I would like to have a parameter to override the [min.insync.replicas](https://kafka.apache.org/documentation/#brokerconfigs_min.insync.replicas) configuration. Currently, the only way to do it is to have an extra environment variable to set it.

The environment variable fulfills my use case, I just wanted to have everything set with the chart's parameters. This is a minor improvement.

**Describe the solution you'd like**

```yml
minInsyncReplicas: 1
```

**Describe alternatives you've considered**

```yml
extraEnvVars:
  - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
    value: "1"
```

**Comment by javsalgar** [comment]
Hi! Thanks for the feedback. Would you like to submit a PR adding the value?

**Comment by jaudiger** [comment]
I opened this MR to add this parameter, plus another one.
