### ISSUE TITLE
[bitnami/mariadb-galera] MariaDB Galera Cluster galera.cache file getting bigger than specified gcache.size

### ISSUE THREAD

**Issue by AlexNuSan** [bitnami/charts#8639]
**Which chart**:

[bitnami/mariadb-galera] 0.8.5 (10.4.12.-debian-10-r42 Docker image)

**Describe the bug**
The cluster runs behind 2 HAProxy PODs configured so, all queries are executed on the first POD/node of the galera cluster if available, and the other 2 nodes, provide HA (HA Proxy backend backup nodes). In the my.cnf file, gcache.size is configured to 5 GB, and when a new node is deployed, galera.cache file is 5.1GB so, it seems to get that configuration correctly. However, what we are seeing is galera.cache growing in size up to 80 GBs or more for that first node of the cluster. As far as we know, this file should not increase in size. The problem is also reproduced when scaling the cluster down to one only node. It does not stop growing.

**To Reproduce**

These are the wsrep provider options specified in my.cnf:
```
wsrep_on=ON
wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
wsrep_provider_options="gcache.size=5G"
wsrep_sst_method=mariabackup
wsrep_slave_threads=4
wsrep_cluster_address=gcomm://
wsrep_cluster_name=galera
wsrep_sst_auth="root:"
innodb-flush-log-at-trx-commit=2
wsrep_replicate_myisam=ON
```
This is the haproxy.cfg relevant info:
```
defaults
mode tcp
timeout client 60s
timeout server 60s
timeout connect 10s
maxconn 5000
default-server init-addr last,libc,none

frontend frontend_galera_write
bind *:3306
default_backend backend_galera_write
backend backend_galera_write
balance leastconn
default-server inter 2s downinter 5s rise 3 fall 2 slowstart 60s maxconn 256 maxqueue 128 weight 100
server mariadb-galera3-0 mariadb-galera3-0.mariadb-galera3.ccoc.svc.cluster.local:3306 check resolvers rancher
server mariadb-galera3-1 mariadb-galera3-1.mariadb-galera3.ccoc.svc.cluster.local:3306 check resolvers rancher backup
server mariadb-galera3-2 mariadb-galera3-2.mariadb-galera3.ccoc.svc.cluster.local:3306 check resolvers rancher backup
```
**Expected behavior**

The galera.cache file should not grow over the specified size in my.cnf

**Additional context**

I understand that this may not be related to the bitnami chart and that it is quite outdated now, however I've tried to get support from MariaDB (see https://jira.mariadb.org/browse/MDEV-27457) and other forums like Percona and dba.stackexchange.com, with no luck so far. I tried with a Bitnami Chart that was using Docker image 10.3.22-debian-10-r1 before and, upgraded to the specified Chart version here, to see if the problem was related to that 10.3.22 version, but the problem is still there with 10.4. I am wondering now if it may be related to the way we configure the HAProxy to point to a single node. But it still does not make much sense, the galera.cache file should not grow over the specified size in my.cnf, and that's Galera MariaDB circular buffer file not working as expected I guess? Could anybody try to reproduce this behavior? We've been dealing with this issue for a while now and would be happy to provide any further information that may be required in order to reproduce it. For now, we have a workaround: we can remove the first POD and then the galera.cache is recreated so, we free disk space. The first node syncs through IST with any of the other 2 nodes and the HAProxy points to a backup node meanwhile, and then back to the first node when recovered, with no downtime. However, we want to avoid to do this, obviously. We can't figure out why galera.cache file size increases, there is no documentation nor bug we could find talking about any similar issue. Any help will be much appreciated!

**Comment by carrodher** [comment]
As you said, it seems it is not an issue related to the bitnami/mariadb-galera Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by AlexNuSan** [comment]
Hi @carrodher,

Certainly, it does not seem an issue related to the bitnami/mariadb-galera Helm chart itself but, it could be also related to how MariaDB is installed on the 10.4.12.-debian-10-r42 Docker image, right? I just would like to know if anybody in the community has faced this galera.cache issue so, I would really appreciate if you could pass this issue to some of your colleagues that have worked on this Helm Chart. Thank you.

**Comment by AlexNuSan** [comment]
It seems nobody here has faced ant similar issue. In order to do some further testing, which is the latest Mariadb Bitnami Docker image I could use for a HELMv2 chart (that means before Bitnami galera-mariadb Helm Chart version 5)? I've seen that Helm Chart v4.4.6 uses 10.5.7-debian-10-r0, but that MariaDB version is from Nov 2020 so, a bit old as well. Where could I check the compatible Bitnami galera-mariadb Docker images for Bitnami Helm Chart different versions?

**Comment by carrodher** [comment]
Helm 2 support was dropped around Nov 20th, 2020, you can visit the [commits history](https://github.com/bitnami/charts/commits/master/bitnami/mariadb-galera) for bitnami/mariadb-galera and pick any version previous to that date, for example, 4.4.6; then, you can install it by running `helm install my-release bitnami/mariadb-galera --version 4.4.6`

**Comment by AlexNuSan** [comment]
Solved after upgrading Galera library libgalera_smm.so to 26.4.9 version.
