### ISSUE TITLE
 Crash AH01909

### ISSUE THREAD

**Issue by scorpius81** [bitnami/charts#8645]
I tried to install both Wordpress and PhpMyadmin via HELM. But in both cases it fails.
Here is the log:

```console
$ kubectl logs wordpress-956f8476-8mmjp -f -n website

wordpress 13:36:55.86
wordpress 13:36:55.87 Welcome to the Bitnami wordpress container
wordpress 13:36:55.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 13:36:55.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 13:36:55.96
wordpress 13:36:55.96 INFO ==> ** Starting WordPress setup **
realpath: /bitnami/apache/conf: No such file or directory
wordpress 13:36:56.35 INFO ==> Configuring the HTTP port
wordpress 13:36:56.46 INFO ==> Configuring the HTTPS port
wordpress 13:36:56.65 INFO ==> Configuring PHP options
wordpress 13:36:56.76 INFO ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 13:36:57.36 WARN ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress 13:36:58.77 INFO ==> Restoring persisted WordPress installation
wordpress 13:37:05.76 INFO ==> Trying to connect to the database server
wordpress 13:37:13.01 INFO ==> ** WordPress setup finished! **

wordpress 13:37:13.16 INFO ==> ** Starting Apache **
[Wed Jan 12 13:37:13.661523 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 12 13:37:13.662228 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 12 13:37:13.960321 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 12 13:37:13.960888 2022] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
```

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @scorpius81 

The logs you shared don't indicate any issue in the WordPress container. Could you please provide more information?

- Are the pods mark as "ready"?
- Can you access WordPress via its associated K8s service?

**Comment by scorpius81** [comment]
@juan131 Thanks for the quick response, 

The pods not ready 

kubectl describe pod wppp-wordpress-5957c864b4-l5w4b -n website
Name:         wppp-wordpress-5957c864b4-l5w4b
Namespace:    website
Priority:     0
Node:         webfarm-k8s-worker2/192.168.200.15
Start Time:   Wed, 12 Jan 2022 14:01:16 +0000
Labels:       app.kubernetes.io/instance=wppp
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=wordpress
              helm.sh/chart=wordpress-12.3.1
              pod-template-hash=5957c864b4
Annotations:  cni.projectcalico.org/podIP: 10.244.4.104/32
              cni.projectcalico.org/podIPs: 10.244.4.104/32
Status:       Running
IP:           10.244.4.104
IPs:
  IP:           10.244.4.104
Controlled By:  ReplicaSet/wppp-wordpress-5957c864b4
Containers:
  wordpress:
    Container ID:   containerd://c9be27c7245ae1570e9f76717245e9d358ea89b9691bbb8a5634d579dc8881d0
    Image:          docker.io/bitnami/wordpress:5.8.3-debian-10-r0
    Image ID:       docker.io/bitnami/wordpress@sha256:5b5e7b0492a3b97a84af736993e437226ad81ed08dadb10294dcdd964498202d
    Ports:          8080/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    135
      Started:      Wed, 12 Jan 2022 21:59:40 +0000
      Finished:     Wed, 12 Jan 2022 21:59:44 +0000
    Ready:          False
    Restart Count:  97
    Requests:
      cpu:     300m
      memory:  512Mi
    Environment:
      BITNAMI_DEBUG:                          true
      ALLOW_EMPTY_PASSWORD:                   yes
      MARIADB_HOST:                           wppp-mariadb
      MARIADB_PORT_NUMBER:                    3306
      WORDPRESS_DATABASE_NAME:                bitnami_wordpress
      WORDPRESS_DATABASE_USER:                bn_wordpress
      WORDPRESS_DATABASE_PASSWORD:            <set to the key 'mariadb-password' in secret 'wppp-mariadb'>  Optional: false
      WORDPRESS_USERNAME:                     user
      WORDPRESS_PASSWORD:                     <set to the key 'wordpress-password' in secret 'wppp-wordpress'>  Optional: false
      WORDPRESS_EMAIL:                        user@example.com
      WORDPRESS_FIRST_NAME:                   FirstName
      WORDPRESS_LAST_NAME:                    LastName
      WORDPRESS_HTACCESS_OVERRIDE_NONE:       no
      WORDPRESS_ENABLE_HTACCESS_PERSISTENCE:  no
      WORDPRESS_BLOG_NAME:                    User's Blog!
      WORDPRESS_SKIP_BOOTSTRAP:               no
      WORDPRESS_TABLE_PREFIX:                 wp_
      WORDPRESS_SCHEME:                       http
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT:      
      WORDPRESS_AUTO_UPDATE_LEVEL:            none
      WORDPRESS_PLUGINS:                      none
      APACHE_HTTP_PORT_NUMBER:                8080
      APACHE_HTTPS_PORT_NUMBER:               8443
    Mounts:
      /bitnami/wordpress from wordpress-data (rw,path="wordpress")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gxbtf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  wordpress-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wppp-wordpress
    ReadOnly:   false
  kube-api-access-gxbtf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  2m36s (x2164 over 8h)  kubelet  Back-off restarting failed container

I can't acces Wordpress

exec -n website -it wppp-wordpress-5957c864b4-l5w4b bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@wppp-wordpress-5957c864b4-l5w4b:/$ command terminated with exit code 137

I cant execute curl http://localhost:8080/wp-admin/install.php and curl http://localhost:8080/wp-login.php

Even if I install Phpmyadmin I have the same problem

**Comment by juan131** [comment]
Hi @scorpius81 

Did you enable the diagnostic mode or sth like that @scorpius81 ? I'm missing the liveness/readiness probes information in the `kubectl describe` command.

Could you please share the **values.yaml** (or equivalent command passed via `--set XXX`) to install/upgrade your Helm release?

**Comment by scorpius81** [comment]
I have disable Liveness/readinees, this is the Installation Values:

affinity: {}
allowEmptyPassword: true
allowOverrideNone: false
apacheConfiguration: ''
args: []
autoscaling:
  enabled: false
  maxReplicas: 11
  minReplicas: 1
  targetCPU: 50
  targetMemory: 50
clusterDomain: cluster.local
command: []
commonAnnotations: {}
commonLabels: {}
containerPorts:
  http: 8080
  https: 8443
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
customHTAccessCM: ''
customLivenessProbe: {}
customPostInitScripts: {}
customReadinessProbe: {}
customStartupProbe: {}
diagnosticMode:
  args:
    - infinity
  command:
    - sleep
  enabled: false
existingApacheConfigurationConfigMap: ''
existingSecret: ''
existingWordPressConfigurationSecret: ''
externalCache:
  host: localhost
  port: 11211
externalDatabase:
  database: bitnami_wordpress
  existingSecret: ''
  host: localhost
  password: ''
  port: 3306
  user: bn_wordpress
extraContainerPorts: []
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
global:
  imagePullSecrets: []
  imageRegistry: ''
  storageClass: ''
hostAliases:
  - hostnames:
      - status.localhost
    ip: 127.0.0.1
htaccessPersistenceEnabled: false
image:
  debug: true
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/wordpress
  tag: 5.8.3-debian-10-r0
ingress:
  annotations: {}
  apiVersion: ''
  enabled: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  hostname: wordpress.local
  ingressClassName: ''
  path: /
  pathType: ImplementationSpecific
  secrets: []
  tls: false
initContainers: []
kubeVersion: ''
livenessProbe:
  enabled: false
  failureThreshold: 6
  httpGet:
    httpHeaders: []
    path: /wp-admin/install.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
mariadb:
  architecture: standalone
  auth:
    database: bitnami_wordpress
    password: ''
    rootPassword: ''
    username: bn_wordpress
  enabled: true
  primary:
    persistence:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 8Gi
      storageClass: ''
memcached:
  enabled: false
  service:
    port: 11211
metrics:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.11.0-debian-10-r21
  resources:
    limits: {}
    requests: {}
  service:
    annotations:
      prometheus.io/port: '{{ .Values.metrics.service.port }}'
      prometheus.io/scrape: 'true'
    port: 9117
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    honorLabels: false
    interval: 30s
    namespace: ''
    relabellings: []
    scrapeTimeout: ''
multisite:
  enable: false
  enableNipIoRedirect: false
  host: ''
  networkType: subdomain
nameOverride: ''
networkPolicy:
  egressRules:
    customRules: {}
    denyConnectionsToExternal: false
  enabled: false
  ingress:
    enabled: false
    namespaceSelector: {}
    podSelector: {}
  ingressRules:
    accessOnlyFrom:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
    backendOnlyAccessibleByFrontend: false
    customBackendSelector: {}
    customRules: {}
  metrics:
    enabled: false
    namespaceSelector: {}
    podSelector: {}
nodeAffinityPreset:
  key: ''
  type: ''
  values: []
nodeSelector: {}
pdb:
  create: false
  maxUnavailable: ''
  minAvailable: 1
persistence:
  accessMode: ReadWriteOnce
  accessModes:
    - ReadWriteOnce
  dataSource: {}
  enabled: true
  existingClaim: ''
  size: 10Gi
  storageClass: ''
podAffinityPreset: ''
podAnnotations: {}
podAntiAffinityPreset: soft
podLabels: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
readinessProbe:
  enabled: false
  failureThreshold: 6
  httpGet:
    httpHeaders: []
    path: /wp-login.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
replicaCount: 1
resources:
  limits: {}
  requests:
    cpu: 300m
    memory: 512Mi
schedulerName: ''
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  httpsPort: 443
  httpsTargetPort: https
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    http: ''
    https: ''
  port: 80
  type: LoadBalancer
serviceAccountName: default
sidecars: []
smtpExistingSecret: ''
smtpHost: ''
smtpPassword: ''
smtpPort: ''
smtpProtocol: ''
smtpUser: ''
startupProbe:
  enabled: false
  failureThreshold: 6
  httpGet:
    httpHeaders: []
    path: /wp-login.php
    port: '{{ .Values.wordpressScheme }}'
    scheme: '{{ .Values.wordpressScheme | upper }}'
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
tolerations: []
updateStrategy:
  rollingUpdate: {}
  type: RollingUpdate
volumePermissions:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r303
  resources:
    limits: {}
    requests: {}
  securityContext:
    runAsUser: 0
wordpressAutoUpdateLevel: none
wordpressBlogName: User's Blog!
wordpressConfiguration: ''
wordpressConfigureCache: false
wordpressEmail: user@example.com
wordpressExtraConfigContent: ''
wordpressFirstName: FirstName
wordpressLastName: LastName
wordpressPassword: ''
wordpressPlugins: none
wordpressScheme: http
wordpressSkipInstall: false
wordpressTablePrefix: wp_
wordpressUsername: user

**Comment by Mauraza** [comment]
Hi @scorpius81,

I'm not able to reproduce the issue, could you tell us where are you running WordPress?

**Comment by scorpius81** [comment]
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

This also happens if I try to install phpmyadmin, wordpress, joomla.

But if I install only Apache it works

**Comment by scorpius81** [comment]
I wrote a yaml to deploy an official wordpress image and everything works. replacing with that of bitnami and freezes.
I think it hangs on some procedure it does on OpenSSL.
Can you see the script it executes?

**Comment by Mauraza** [comment]
Hi @scorpius81,

Did you try to check this with a diagnostic mode as @juan131 said? 
https://github.com/bitnami/charts/tree/master/bitnami/wordpress#common-parameters

**Comment by scorpius81** [comment]
Hi @Mauraza 

Thanks to your command I ran the script by hand and saw that it returned:

Bus error (core dumped)

To do a test I set on the worker:

sudo sysctl -w vm.nr_hugepages = 0
and now it looks like it's ready.

**Comment by Mauraza** [comment]
Hi @scorpius81,

I'm glad you solved the problem!!

**Comment by wibed** [comment]
@scorpius81 

i am expiriencing a similar issue.
could you elaborate on how you solved it?

**Comment by wibed** [comment]
> Hi @Mauraza
> 
> Thanks to your command I ran the script by hand and saw that it returned:
> 
> Bus error (core dumped)
> 
> To do a test I set on the worker:
> 
> sudo sysctl -w vm.nr_hugepages = 0 and now it looks like it's ready.

@scorpius81 how did you finally resolve it.
as the redhat documentation points out:

`Setting vm.nr_hugepages=0 in the /etc/sysctl.conf and then rebooting the server does not disable the HugePages.`

https://access.redhat.com/solutions/5313431
