### ISSUE TITLE
Kong installation fails due to "no matches for kind "CustomResourceDefinition""

### ISSUE THREAD

**Issue by cjmckenna** [bitnami/charts#8647]
When installing kong using `helm install my-release bitnami/kong` I am getting the following error.
```
Error: INSTALLATION FAILED: failed to install CRD crds/custom-resource-definitions.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```
v1beta is no longer supported after 1.21 so the install will not work.
```
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:40:11Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @cjmckenna, it seems like the CRDs are outdated so I'm going to create an internal task for updating them.

Unfortunately I cannot provide an ETA for when it will be fixed. If you are up for it, feel free to contribute the changes to support the new CRDs, it would allow them to be merged much sooner. We would be glad to help with the review and release of those changes.

**Comment by carrodher** [comment]
This issue should be solved with the changes at https://github.com/bitnami/charts/pull/9076. Please, feel free to reopen it if something is not working as expected.
