### ISSUE TITLE
helm bitnami/kibana plugin install failed

### ISSUE THREAD

**Issue by ThorSiv** [bitnami/charts#8649]
I try to  install Kibana with `bitnami/kibana` helm chart. But I meet some issues on plugin.

in values.yaml:

```yaml
plugins: 
  - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
  - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
```

 Why install twice? see log 

```console
└─$ kubectl logs -f kibana-c878c89d4-5px2s -n zmslog 
kibana 06:24:15.56 
kibana 06:24:15.56 Welcome to the Bitnami kibana container
kibana 06:24:15.56 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kibana
kibana 06:24:15.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kibana/issues
kibana 06:24:15.56 
kibana 06:24:15.56 INFO  ==> ** Starting Kibana setup **
kibana 06:24:15.59 INFO  ==> Configuring/Initializing Kibana...
kibana 06:24:15.62 INFO  ==> Found mounted configuration directory
kibana 06:24:15.66 INFO  ==> Starting Kibana in background
kibana 06:24:15.66 INFO  ==> Waiting for Kibana to be started and ready
kibana 06:24:42.86 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
==> Plugin installation
Total plugins defined in chart installation: 2
Installing plugin 1 out of 2: https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Error: Client request error: socket hang up
Plugin installation was unsuccessful due to error "Client request error: socket hang up"
Installing plugin 2 out of 2: https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Found previous install attempt. Deleting...
Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Transferring 148945 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete
==> End of Plugin installation
kibana 06:26:47.30 INFO  ==> ** Kibana setup finished! **
```
But ,  plugin is not installed actually. I don't know why .

```
I have no name!@kibana-c878c89d4-5px2s:/$ kibana-plugin list
No plugins installed.
I have no name!@kibana-c878c89d4-5px2s:/$ exit 
```

`metrics.enbaled: true` and `serviceMonitor.enbaled:true`. Because of plugin installing  failed, serviceMonitor else doesn't work. help me, please.

**Comment by juan131** [comment]
Hi @ThorSiv 

The error in the logs indicate that there was an issue when requesting to download the plugin, see:

```console
Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Error: Client request error: socket hang up
Plugin installation was unsuccessful due to error "Client request error: socket hang up"
```

Does your K8s cluster has connectivity to internet? Can you manually launch a container and try to download the plugin manually to see if that's possible? Sth like this:

```console
$ kubectl run -i --tty busybox --image=busybox -- sh
If you don't see a command prompt, try pressing enter.
# wget https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Connecting to github.com (140.82.112.3:443)
wget: note: TLS certificate validation not implemented
Connecting to objects.githubusercontent.com (185.199.108.133:443)
saving to 'kibanaPrometheusExporter-7.16.2.zip'
kibanaPrometheusExpo 100% |***************************************************************************************|  145k  0:00:00 ETA
'kibanaPrometheusExporter-7.16.2.zip' saved
```

**Comment by ThorSiv** [comment]
> Hi @ThorSiv
> 
> The error in the logs indicate that there was an issue when requesting to download the plugin, see:
> 
> ```
> Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
> Error: Client request error: socket hang up
> Plugin installation was unsuccessful due to error "Client request error: socket hang up"
> ```
> 
> Does your K8s cluster has connectivity to internet? Can you manually launch a container and try to download the plugin manually to see if that's possible? Sth like this:
> 
> ```
> $ kubectl run -i --tty busybox --image=busybox -- sh
> If you don't see a command prompt, try pressing enter.
> # wget https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
> Connecting to github.com (140.82.112.3:443)
> wget: note: TLS certificate validation not implemented
> Connecting to objects.githubusercontent.com (185.199.108.133:443)
> saving to 'kibanaPrometheusExporter-7.16.2.zip'
> kibanaPrometheusExpo 100% |***************************************************************************************|  145k  0:00:00 ETA
> 'kibanaPrometheusExporter-7.16.2.zip' saved
> ```

Thanks for your reply.@juan131

"Does your K8s cluster has connectivity to internet? Can you manually launch a container and try to download the plugin manually to see if that's possible? "  --  absolutely yes!

k8s pod logs show me plugin installed successfuly in the end (logs in my first comment)

I found plugin must install twice .

I try to install plugin in pod :
```
└─$ kubectl exec -it kibana-c878c89d4-5px2s -n zmslog -- bash
I have no name!@kibana-c878c89d4-5px2s:/$ kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip
Transferring 148945 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete
I have no name!@kibana-c878c89d4-5px2s:/$ 
```
But why helm install kibana plugin failed?

**Comment by ThorSiv** [comment]
I am so  confusing  in this situation:
`plugins: 
  - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip`

**Comment by ThorSiv** [comment]
Hi @juan131 ,thanks a lot~
I am so confusing in this situation:
first ,      config plugin in values.yaml:
`plugins: 
  - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.16.2/kibanaPrometheusExporter-7.16.2.zip`
 then 
`helm install kibana bitnami/kibana -n logging`
the plugin installed successfully.
but when you config   metrics.enabled=true   metrics.serviceMonitor.enabled=true.
the plugin will install failed.
Why this happen?

**Comment by juan131** [comment]
Hi @ThorSiv 

> but when you config `metrics.enabled=true` `metrics.serviceMonitor.enabled=true`, the plugin will install failed. Why this happen?

That's weird... Does this happen during a new release installation or while upgrading an existing release?
