### ISSUE TITLE
[bitnami/fluentd] Missing cloudwatch_logs plugin

### ISSUE THREAD

**Issue by nsurleraux-railnova** [bitnami/charts#8652]
**Which chart**:

bitnami/fluentd version 4.5.2

**Describe the bug**

The aggregator is missing the cloudwatch_logs plugin.
```
config error file="/opt/bitnami/fluentd/conf/fluentd.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'cloudwatch_logs'. Run 'gem search -rd fluent-plugin' to find plugins
```

**To Reproduce**

1. Deploy this chart with the following fluentd.conf :
```
<match fluent.**>
  @type null
</match>
<source>
  @type tail
  @log_level warn
  enable_stat_watcher false
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  format json
  read_from_head true
</source>
<match kubernetes.**>
  @type cloudwatch_logs
  log_group_name "#{ENV['LOG_GROUP_NAME']}"
  auto_create_stream true
  use_tag_as_stream true
</match>
```
2. See the aggregator failing.

**Expected behavior**

The aggregator should come with the cloudwatch_logs plugin.

**Comment by alemorcuq** [comment]
Hi, @nsurleraux-railnova. Note that you can extend the image to install any plugins you desire. See https://github.com/bitnami/bitnami-docker-fluentd#extend-this-image
