### ISSUE TITLE
[bitnami/thanos] thanos.serviceAccount templating fails for components containing "-"

### ISSUE THREAD

**Issue by yetisage** [bitnami/charts#8657]
**Which chart**:
thanos 8.3.0

**Describe the bug**

The templates `"thanos.serviceAccount.name"` and `"thanos.serviceAccount.useExisting"` fail for components that contain "-".

This causes serviceAccounts for e.g query-frontend to be generated if `queryFrontend.serviceAccount.existingServiceAccount` is set, while `existingServiceAccount` isn't.

Same is true for receive-distributor.

**To Reproduce**

1. Run `helm template`
2. See that `thanos/templates/query-frontend/serviceaccount.yaml` is generated
3. Change `queryFrontend.serviceAccount.existingServiceAccount` to any value
4. See that `thanos/templates/query-frontend/serviceaccount.yaml` is still generated
5. Change line 1 in `thanos/templates/query-frontend/serviceaccount.yaml` from:
```go
{{- if and .Values.queryFrontend.enabled (not (include "thanos.serviceAccount.useExisting" (dict "component" "query-frontend" "context" $))) }}
```
to:
```go
{{- if and .Values.queryFrontend.enabled (not (include "thanos.serviceAccount.useExisting" (dict "component" "queryFrontend" "context" $))) }}
```
6. Run `helm template`
7. See that `thanos/templates/query-frontend/serviceaccount.yaml` is no longer generated

**Expected behavior**

Service account template should not be generated if `$component.serviceAccount.existingServiceAccount` is set. 

`"thanos.serviceAccount.name"` should be set to the value of `$component.serviceAccount.existingServiceAccount`

**Additional context**

The issue seems to stem from the `"thanos.serviceAccount.useExisting"` and `"thanos.serviceAccount.name"` templates assuming that the supplied component name matches the component key in values.yaml.

```go
{{/* Service account name
Usage:
{{ include "thanos.serviceAccount.name" (dict "component" "bucketweb" "context" $) }}
*/}}
{{- define "thanos.serviceAccount.name" -}}
{{- $name := printf "%s-%s" (include "common.names.fullname" .context) .component -}}

{{- if .context.Values.existingServiceAccount -}}
    {{- $name = .context.Values.existingServiceAccount -}}
{{- end -}}

{{- $component := index .context.Values .component -}}
{{- if $component.serviceAccount.existingServiceAccount -}}
    {{- $name = $component.serviceAccount.existingServiceAccount -}}
{{- end -}}

{{- printf "%s" $name -}}
{{- end -}}

{{/* Service account use existing
{{- include "thanos.serviceAccount.useExisting" (dict "component" "bucketweb" "context" $) -}}
*/}}
{{- define "thanos.serviceAccount.useExisting" -}}
{{- $component := index .context.Values .component -}}
{{- if .context.Values.existingServiceAccount -}}
    {{- true -}}
{{- else if $component.serviceAccount.existingServiceAccount -}}
    {{- true -}}
{{- end -}}
{{- end -}}
```

query-frontend is called `queryFrontend` and receive-distributor is called `receiveDistributor` in values.yaml so `$component.serviceAccount.existingServiceAccount` will not match.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.
