### ISSUE TITLE
 Bitnami Kafka: Couldn't find the expected Java Key Stores (JKS) files!

### ISSUE THREAD

**Issue by pierrecoppolino** [bitnami/charts#8660]
Hello,

I find a little mistake in file /bitnami/kafka/templates/scripts-configmap.yaml ligne 123   JKS_KEYSTORE="/certs-${ID}/kafka-keystore.jks"  => should be   JKS_KEYSTORE="/certs-${ID}/kafka.keystore.jks"

Regards 
Pierre

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.
