### ISSUE TITLE
[bitnami/grafana-operator] global storage class not respected

### ISSUE THREAD

**Issue by dc232** [bitnami/charts#8663]
**Which chart**:
bitnami/grafana-operator

**Describe the bug**

 global storage class not respected, the chart defaults to default storage class rather than the one set globally
**To Reproduce**

run via terraform with
```
  set {
    name = "global.storageClass"
    value = "wordpress-storage-class"
  }
```

**Expected behavior**

PVC and PV to be set correctly via name param

**Additional context**
error seems to be here in the naming convention 
https://github.com/bitnami/charts/blob/master/bitnami/grafana/templates/pvc.yaml#L33 
where in the template the name is set to grafana.storageClass as oppose to global.storageClass which can be set via the values.yaml file 
as a result the container is not able to communicate with the storage controller in the proper manner and if the default  sc  is not set the pods will be in constant init state and the endpoints for the svc not set meaning 503 at the ingress

**Comment by carrodher** [comment]
Please note the link you shared is about [bitnami/grafana](https://github.com/bitnami/charts/tree/master/bitnami/grafana) but some lines above you mention the chart used is [bitnami/grafana-operator](https://github.com/bitnami/charts/tree/master/bitnami/grafana-operator).

In the case of bitnami/grafana, the `global.storageClasss` is a valid value, but this value is not present in the bitnami/grafana-operator chart.

**Comment by dc232** [comment]
Hi @carrodher you are correct this is a mistake on my part applogies
