### ISSUE TITLE
[bitnami/tomcat] ValidationError(StatefulSet.spec.volumeClaimTemplates[0]): unknown field "storageClassName" in io.k8s.api.core.v1.PersistentVolumeClaim

### ISSUE THREAD

**Issue by visitingcat** [bitnami/charts#8664]
**Description**

Creating a statefulset with storage class fails.

**Steps to reproduce**

```bash
helm install tomcat-test --set persistence.storageClass="myclass" --set deployment.type=statefulset bitnami/tomcat
```

**Error message**

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.volumeClaimTemplates[0]): unknown field "storageClassName" in io.k8s.api.core.v1.PersistentVolumeClaim
```

**Remarks**

I think this might be due to a wrong indentation in `templates/statefulset.yaml`. I think the `nindent` has to be `8` here instead of `6`:

```yaml
{{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 6 }} 
```

**Comment by juan131** [comment]
You're completely right @visitingcat !!

Would you like to contribute with a PR fixing this?

**Comment by visitingcat** [comment]
Thanks, but I'd rather not. I have no knowledge about helm or go templates ;-)

**Comment by juan131** [comment]
It's fine, I just sent a PR addressing it. Thanks for reporting it.

**Comment by visitingcat** [comment]
Thank you
