### ISSUE TITLE
too many slowlogs

### ISSUE THREAD

**Issue by liyuanjob** [bitnami/charts#8669]
[bitnami/redis]My resource set cpu limit 1 core ,memory limit 6G and slowlog limit 500us. I get too many slowlogs no matter the traffic if heavy.

**Comment by javsalgar** [comment]
Hi,

Could you provide more information on the Kubernetes platform you are using? Could you show the logs of the application? Which of PVC provider are you using?

**Comment by liyuanjob** [comment]
sorry, I missed your comments. The k8s version of my used is v1.18.17. The application logs are normal and I don't enable PVC.

**Comment by Mauraza** [comment]
Hi @liyuanjob,

Could you give us more information? you can use the commands `slowlogs` to get more information like https://redis.io/commands/slowlog-len

**Comment by liyuanjob** [comment]
Hi @Mauraza ,
I output all slow logs to Kibana by filebeat. So command slowlog len show 0. But I can search all slow logs by kibana. The picture shows the number of slow logs in 24h.
![image](https://user-images.githubusercontent.com/33893561/150977189-f666b8e4-412a-4e5b-9c3d-12ffdea290d2.png)

**Comment by liyuanjob** [comment]
This is just the number of slow logs produced by one microservice. We have more than ten microservices. The app container CPU usage will overload when at peak time.

**Comment by Mauraza** [comment]
Hi @liyuanjob,

Did you try to use PVC? 

Maybe it's a good idea to post your question on the official support forum of the Redis https://forum.redis.com/ because this question is more related to the application itself.

Do not hesitate to write us back if you have any other questions.
