### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Error when metrics.enabled=true

### ISSUE THREAD

**Issue by CEDDM** [bitnami/charts#8670]
**Which chart**:

spring-cloud-dataflow 5.0.1

**Describe the bug**

When i set metrics.enabled=true, i have this error :

`Error: UPGRADE FAILED: template: spring-cloud-dataflow/templates/prometheus-proxy/service.yaml:17:6: executing "spring-cloud-dataflow/templates/prometheus-proxy/service.yaml" at <include "common.tplvalues.render" (dict "value" .Values.metrics.service.annotations "context" $)>: error calling include: template: spring-cloud-dataflow/charts/common/templates/_tplvalues.tpl:11:12: executing "common.tplvalues.render" at <tpl (.value | toYaml) .context>: error calling tpl: error during tpl function execution for "prometheus.io/path: /metrics/proxy\nprometheus.io/port: '{{ coalesce .Values.metrics.service.ports.http .Values.metrics.service.httpPort\n }}'\nprometheus.io/scrape: \"true\"": parse error at (spring-cloud-dataflow/templates/prometheus-proxy/service.yaml:2): unclosed action `

**To Reproduce**

`helm3 install scdf-test bitnami/spring-cloud-dataflow --set metrics.enabled=true --dry-run`

**Comment by alemorcuq** [comment]
Thanks for reporting this. I've been able to reproduce it and we are investigating it.
