### ISSUE TITLE
[Question] - How to identify source of bitnami packages?

### ISSUE THREAD

**Issue by lward-lucid** [bitnami/charts#8674]
Hi

I am sure that I have just missed something really obvious but I have searched quite a bit on github and on the different bitnami site and in documents and cannot find the answer.

I am planning to upgrade our version of the [kube-prometheus](https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus) chart. I know this chart pulls in the [kube-state-metrics](https://github.com/bitnami/charts/tree/master/bitnami/kube-state-metrics) chart. I can see the docker image tag/version that the kube-state-metrics chart will use e.g. https://github.com/bitnami/charts/blob/master/bitnami/kube-state-metrics/values.yaml#L81

From here I can look at the docker image and see the kube-state-metric package that will be installed [kube-state-metrics-2.3.0-0-linux-amd64-debian-10.tar.gz](https://registry.hub.docker.com/layers/bitnami/kube-state-metrics/2.3.0-debian-10-r0/images/sha256-18cbfa712e892de4c9351ff13db0a09203f4361dd3a9928f32607b1c5626515b?context=explore).

What I do not know is how to find out which version of `kube-state-metric` that actually is? I would like to ensure that I have checked for any changes. This would normally involve checking the [changelog](https://github.com/kubernetes/kube-state-metrics/blob/950a173907c81a85b552f2f15b9d285a8ffc6fce/CHANGELOG.md) for the updates between versions. I can not work out which kube-state-metrics this bitnami package is actually using?

In addition at the moment cannot see what version I am currently running within the container:
```
/opt/bitnami/kube-state-metrics/bin$ kube-state-metrics --version
kube-state-metrics, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.17.4
  platform:         linux/amd64
```

Any help on where I should be looking to find this information would be appreciated.

Thanks

**Comment by yardenshoham** [comment]
Start here https://github.com/bitnami/charts/tree/master/bitnami/kube-state-metrics

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. The kube-state-metrics package should show the exact version it is shown on the tarball. I will open a task for fixing the compilation so the proper version is shown. Thanks for reporting.

**Comment by lward-lucid** [comment]
Hi,

Thanks for the response, the kube-state-metric does show a package version on the tarball, in the example I shared in my original comment it was `2.3.0-0-linux-amd64-debian-10`. 
I have just realised my mistake, I was looking at on old commit of the [changelog](https://github.com/kubernetes/kube-state-metrics/blob/950a173907c81a85b552f2f15b9d285a8ffc6fce/CHANGELOG.md) from the kube-state-metrics repo and was confused because the latest release version there was showing as `2.0.0` and I didn't see how the bitnami package could be version `2.3.0`.

Again thanks for responding to my question, I knew I was missing something obvious.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision that shows the proper version of `kube-state-metrics`

```
❯ kubectl exec -ti st-kube-state-metrics-58cd699d57-g9nsb -- kube-state-metrics --version
kube-state-metrics, version v2.4.2 (branch: HEAD, revision: ef8bede)
  build user:       bitnami
  build date:       2022-04-13T15:07:33Z
  go version:       go1.18.1
  platform:         linux/amd64
```
