### ISSUE TITLE
Consul: enhancement: ui.service.type.annotations

### ISSUE THREAD

**Issue by Vadim-Zenin** [bitnami/charts#868]
Hello,

Consul: enhancement: ui.service.type.annotations would be nice to have to configure AWS Load Balancer. (example AWS internal ALB or NLB).
References:
https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
https://kubernetes.io/docs/concepts/services-networking/service/#network-load-balancer-support-on-aws-alpha

**Comment by tompizmor** [comment]
@Vadim-Zenin We have just merged this PR https://github.com/bitnami/charts/pull/870 adding annotations support for the ui service. Let us know if you find any issue!
