### ISSUE TITLE
[bitnami/tomcat:10.1.2] extraVolumeMounts: Error: YAML parse error on tomcat/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 95: did not find expected key

### ISSUE THREAD

**Issue by patrickhoefer** [bitnami/charts#8690]
**Which chart**:

bitnami/tomcat:10.1.2

**Describe the bug**

Adding `Values.extraVolumeMounts` lead to helm template syntax error

**To Reproduce**

Add the following Values to your chart and run helm template
```
extraVolumeMounts: 
  - name: nfs
    mountPath: /mnt/nfs

```

**Comment by juan131** [comment]
This is very similar to https://github.com/bitnami/charts/issues/8681
I'll request @migruiz4 to address this at https://github.com/bitnami/charts/pull/8684
