### ISSUE TITLE
[bitnami/mongodb] auth.existingSecret not backwards compatible after change to multiple custom users/passwords

### ISSUE THREAD

**Issue by mowies** [bitnami/charts#8693]
**Which chart**:

MongoDB since #7930

**Describe the bug**

Since the change was made to support multiple custom users/passwords/databases, the `existingSecret` value is not backwards compatible anymore. The values `auth.username`, `auth.password` and `auth.database` were set to deprecated. But after an upgrade to the latest released version of the mongodb chart, the release is not able to start up anymore for me.

The problem is that the credentials secret is not backwards compatible. If I update my helm chart, the secret will still have the old `mongodb-password` inside and not the new `mongodb-passwords`. This will in the end result in a `CreateContainerConfigError` on kubernetes.

**To Reproduce**

1. Install mongodb `10.28.7` using the `auth.existinSecret` value with a secret that has all necessary values defined
`helm install -n mongo mongo bitnami/mongodb --version=10.28.7 --create-namespace --set auth.existingSecret=mongodb-credentials`
2. Upgrade the chart to version `10.29.0` while also using the same credentials secret again

**Expected behavior**

The `auth.existingSecret` value is backwards-compatible and can also support a move from the old `mongodb-password` to the new `mongodb-passwords` value.

**Comment by marcosbc** [comment]
Hi @mowies, thanks for reporting this issue. I have created an internal task for looking into this. Unfortunately I cannot give an ETA for when it would be fixed.

If you are up to it, feel free to send a PR with the fix! We would be glad to help with the review/release processes.

**Comment by alemorcuq** [comment]
A new major version of the chart was released (see #8818). As no more `10.x` versions will be released, this issue doesn't apply anymore.

**Comment by mowies** [comment]
What about upgrades to the new major version?

**Comment by marcosbc** [comment]
@mowies Given the new major, new major changes are expected to happen. While we could fix the upgrade from 10.x to 11.x, it would provide little value since users are already expected to re-deploy the new version.

However, it could be documented to mention this specific issue in the upgrading section with the fix (renaming mongodb-password to mongodb-passwords in the secret), if you think so, feel free to send a PR with the notes.
