### ISSUE TITLE
bitnami/postgresql : What is the steps to expose postgresql service external to cluster 

### ISSUE THREAD

**Issue by Teju367** [bitnami/charts#8696]
I have deployed postgresql on eks 1.20 and looking for steps to expose this service.

Is there any document/steps which you can share with me?

**Comment by carrodher** [comment]
All the documentation related to this Helm chart can be found in the [README file](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md).

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
