### ISSUE TITLE
[bitnami/airflow] Add volumeClaimTemplates for Worker StatefulSet

### ISSUE THREAD

**Issue by thy-vk-dao** [bitnami/charts#8699]
**Which chart**: bitnami/airflow version 11.1.8
Executor: Celery

I'm using airflow helm chart with executor celery. Inside worker containers, logs are stored in `/opt/bitnami/airflow/logs` . However when these containers restart, logs are lost. I would like to add persistent disk volumes to these containers to store these logs.

Because the chart is using statefulSet for the celery workers, using the extraVolumes won't work as it would be one disk shared between all the workers. So I think volumeClaimTemplates should be added to the worker template so each container can have its own disk volume to store data like logs file.

**Comment by rafariossaa** [comment]
Hi,
  Yes,  you are right, you will need that to use a volume per pod for the logs.
  Would you like to send a PR to add this feature ? we will be glad to review and merge it.

**Comment by thy-vk-dao** [comment]
Hi,

I have created PR #8711.

Please have to review and let me know if anything!

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your PR !!
  It will be reviewed.

**Comment by rafariossaa** [comment]
Hi, 
  I am closing this as the PR was merged.
  Don't hesitate to reopen it again if needed.
