### ISSUE TITLE
i want delay- exchange plugin support。 thanks！

### ISSUE THREAD

**Issue by mswinner** [bitnami/charts#8704]
i want delay- exchange plugin support。 thanks！
i want delay- exchange plugin support。 thanks！
i want delay- exchange plugin support。 thanks！

**Comment by carrodher** [comment]
Thanks for the suggestion, unfortunately, we are not used to adding third-party plugins as part of the container image or the Helm chart.
In most Helm charts, there are some parameters to add new plugins when deploying it, if it's not the case of the Helm chart you're using, we would be happy to review any PR adding this feature, PRs are welcome!
