### ISSUE TITLE
[bitnami/grafana-tempo] Add configmap checksum annotation

### ISSUE THREAD

**Issue by symmetriac** [bitnami/charts#8707]
**Which chart**:

grafana-tempo:0.2.17

**Is your feature request related to a problem? Please describe.**

The pods of grafana-tempo don't restart if configmap is changed.

**Describe the solution you'd like**

Add annotation
```
checksum/config: {{ include (print $.Template.BasePath "/tempo-configmap.yaml") . | sha256sum }}
```
to all deployment templates

**Comment by migruiz4** [comment]
Hi @symmetriac,

Thank you very much for reporting this issue.

Would you like to contribute with us by sending a PR? We will be very happy to review it and help with anything if needed.

**Comment by symmetriac** [comment]
Hi @migruiz4, I created a PR.
