### ISSUE TITLE
TimescaleDB, or other postgres extension

### ISSUE THREAD

**Issue by cornel-masson** [bitnami/charts#8713]
I'm using bitnami postgresql helm chart, but want to add the TimescaleDB extension. What is the recommended way to do this?

I see the `postgresqlSharedPreloadLibraries` parameter in values.yaml: normally I would add 'timescaledb' to this setting. However, I first need to get the timescale binaries installed in the postgresql pod. On my Ubuntu machines, outside of k8s, I would follow [these installation instructions](https://docs.timescale.com/install/latest/self-hosted/installation-debian/#installing-self-hosted-timescaledb-on-debian-based-systems), which ends up doing `apt install timescaledb-2-postgresql-14`.

**Comment by juan131** [comment]
Hi @cornel-masson 

It seems it is not an issue related to the Bitnami PostgreSQL chart but about how customize/extend the image. 

For information regarding customization of the content within the container, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology (PostgreSQL in this case).

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by cornel-masson** [comment]
Instead of using the docker image `bitnami/postgresql:14.1.0-debian-10-r59`, could I use e.g. `timescale/timescaledb:latest-pg14` instead? Is your helm deployment dependent on the details of the bitnami/postgresql image?

**Comment by juan131** [comment]
Hi @cornel-masson 

The parameters, env. variables and default mount points used in the PostgreSQL chart are intended to meet the Bitnami PostgreSQL image requirements. That said, the chart also expose parameters to add any custom env. variable or volume and also overwrite the default's command and entrypoint. Therefore, it could be possible to make it compatible with other images, although not trivial at all.

**Comment by javsalgar** [comment]
Hi,

Could you add more details about this pg_partmap extension? Is it part of regular PostgreSQL?

**Comment by spuny** [comment]
Hi, @javsalgar no it is not regular part of psql. You have to compile it with it as mentioned on partman pages.
I found solution somewhere on github. You just have to modify the image from postgres. I'm using bitnami but you can choose which ever you want.
The solution looks something like this:
```
FROM bitnami/postgresql-repmgr:13.2.0-debian-10-r83
ARG PARTMAN_VERSION=4.6.2
USER root
RUN apt-get update && apt-get install -y build-essential
RUN curl -L "https://github.com/pgpartman/pg_partman/archive/refs/tags/v${PARTMAN_VERSION}.tar.gz" --output "pg_partman.tar.gz"
RUN tar -xvf pg_partman.tar.gz && cd pg_partman-${PARTMAN_VERSION} && make install
USER 1001
```
Than just change the chart to use your new image and you are done, ofc some charts needs to load it with preshared libs.
It took a little try and error ;)

Hope this helps

**Comment by halradaideh** [comment]
hey

So I was able to install the timescale on bitnami's PSQL 14 repmgr as follows
```
FROM bitnami/postgresql-repmgr:14-debian-11

# switch to root to use apt
USER root

# install depandanices and postgreSQL required scripts
RUN apt update &&  apt install -y gnupg postgresql-common apt-transport-https lsb-release wget

# configure TS repo
RUN echo "deb https://packagecloud.io/timescale/timescaledb/debian/ bullseye main" >> /etc/apt/sources.list.d/timescaledb.list && \
    wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey |  apt-key add -

# install TS
RUN echo "\n" | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh && apt update && apt install -y timescaledb-2-postgresql-14

# copy required assets to bitnami's postgreSQL directory
RUN cp -r /usr/share/postgresql/14/extension/timescaledb*   /opt/bitnami/postgresql/share/extension/ && \
    cp -r /usr/lib/postgresql/14/lib/timescaledb* /opt/bitnami/postgresql/lib/

# return to the normal user
USER 1001
```

I pushed it to my personal account here https://hub.docker.com/r/mrelite/ts-bitnami-repmgr

you can just modify the values file of the ha helm chart like this 

```
diff values*
105,107c105,107
<     registry:
<     repository: mrelite/ts-bitnami-repmgr
<     tag: v1
---
>     registry: docker.io
>     repository: bitnami/postgresql-repmgr
>     tag: 15.3.0-debian-11-r16
465c465
<   sharedPreloadLibraries: "timescaledb, pgaudit, repmgr"
---
>   sharedPreloadLibraries: "pgaudit, repmgr"
```
