### ISSUE TITLE
Sentinel HPA not used when setting sentinel.enable = true and replica.autoscaling.enabled = true

### ISSUE THREAD

**Issue by javiramos1** [bitnami/charts#8714]
**Which chart**:

Redis 14.8.11

**Describe the bug**

I have setup ` sentinel.enable = true` and `replica.autoscaling.enabled = true`
but the other [HPA](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/replicas/hpa.yaml) is deployed instead.

We get the error:
```
the HPA controller was unable to get the target's current scale: statefulsets.apps "[NAME]-redis-replicas" not found
```

This is because the stateful set name end in `-node` since we are using sentinel.

**To Reproduce**

Set:
```
sentinel:
    enabled: true
replica:
    replicaCount: 3
    autoscaling:
      enabled: true
```
Expected results: 

Sentinel [HPA](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/sentinel/hpa.yaml) deployed.

Actual Results:

The other [HPA](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/replicas/hpa.yaml) is deployed instead.

**Comment by marcosbc** [comment]
Hi @javiramos1, version 14.x of the chart is a bit old. Could you try with the latest version of the chart, 15.7.1?

**Comment by javiramos1** [comment]
Hi, I can confirm that updating the chart solves this issue. Thanks
