### ISSUE TITLE
[bitnami/solr] Ingress no longer works after Chart standardization

### ISSUE THREAD

**Issue by markwooff** [bitnami/charts#8717]
**Which chart**:

[bitnami/solr:3.0.0](https://artifacthub.io/packages/helm/bitnami/solr)

**Describe the bug**

Now that the Ingress template has changed, one can no longer deploy Solr using an Ingress without receiving the following error:

`Error: UPGRADE FAILED: template: solr/templates/ingress.yaml:46:42: executing "solr/templates/ingress.yaml" at <include "solr.ingress.certManagerRequest" .Values.ingress.annotations>: error calling include: template: no template "solr.ingress.certManagerRequest" associated with template "gotpl"`

The error seems to indicate the template for `solr.ingress.certManagerRequest` doesn't exist while it's being referenced from https://github.com/bitnami/charts/blob/master/bitnami/solr/templates/ingress.yaml#L46

**To Reproduce**

1. Deploy a Solr instance using the `bitnami/solr:3.0.0` chart with `ingress.enabled` set to `true`
2. See error

**Expected behavior**

No value was set for `solr.ingress.certManagerRequest` so the error should not be displayed which currently prevents a successful deployment.

**Additional context**

I believe this "standardization" may have attempted to include values for [cert-manager](https://artifacthub.io/packages/helm/cert-manager/cert-manager) however it may not be set up correctly.

**Comment by juan131** [comment]
Thanks so much for reporting it @markwooff ! I'll send a PR addressing this in a couple of hours.
