### ISSUE TITLE
[Keycloak v6.0.0] How to publish wildfly management console on https with https offloading?

### ISSUE THREAD

**Issue by ddzobov** [bitnami/charts#8734]
Hello
we are using OpenShift 4.8 and KeyCloak 15 with chart version 6.0.0.

We are terminating ssl on proxy server before routers.
But when we are trying to connect to wildfly console on https://... we are seeing blank screen after basic auth window.

**Comment by falenn** [comment]
I believe I'm seeing the same thing - right after authentication, a blank screen.  Chart deployed with ingress-nginx with TLS offload as described here: https://github.com/bitnami/charts/tree/master/bitnami/keycloak#use-with-ingress-offloading-ssl

![Screenshot at 2022-01-20 16-19-55](https://user-images.githubusercontent.com/701962/150424549-af9300bc-b23e-4ac5-87b0-4abf7e7445cd.png)

**Comment by falenn** [comment]
Looking more into this, 
app.js line 41 - req.readyState at this point == 2.  The code drops to the req.send()
`        req.onreadystatechange = function () {
            if (req.readyState == 4) {
                if (req.status == 200) {
                    var data = JSON.parse(req.responseText);
                    success && success(data);
                } else {
                    error && error();
                }
            }
        }

        req.send();
    }`

**Comment by falenn** [comment]
I added to ingress-nginx annotations section for ingress the following: 
```
nginx.ingress.kubernetes.io/proxy-pass-headers: "Authorization"
```
and was able to get the page to render!

**Comment by juan131** [comment]
Thanks for sharing your solution @falenn !! @ddzobov could you please give it a try and let us know if that works for you?

**Comment by ddzobov** [comment]
> Thanks for sharing your solution @falenn !! @ddzobov could you please give it a try and let us know if that works for you?

We are using openshift routers based on haproxy (we dont have nginx and pure k8s). So, this solution can not work for us.
