### ISSUE TITLE
[bitnami/minio] White screen (react error) when upgrading to 10.0.x with created (non-root) user

### ISSUE THREAD

**Issue by alanlekah** [bitnami/charts#8737]
**Which chart:**

Minio chart 10.0.x (tested on 10.0.1-3)

**Describe the bug**

We upgraded from chart minio 9.3.0 to 10.0.3. We're seeing with users that aren't the admin/root user that when they try accessing any bucket, that you'll hit a white screen and you'll see a console react error in the webpage.

We get the error:

Getting a react error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

**To Reproduce**

We're using the following helm values:

```
    --set global.storageClass="gp2" 
    --set persistence.size="80Gi" 
    --set mode="distributed"
```

With a read only user created using a custom IAM policy set like the following:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}`

**Actual Results:**

You should see the objects inside the bucket (instead of a white screen and a console error in the browser) when logging in as the readonly user + policy created above

**Comment by javsalgar** [comment]
Hi,

It seems that, during the upgrade of a major version, you hit with a more application-related error, as it seems to be programming error. Could you check with the Minio devs for some advice on this? If we need to change something in the chart configuration, please let us know.

**Comment by alanlekah** [comment]
Looks like a known issue in the latest MinIO 2022.1.8 release. I would highly advise anyone to avoid this version if at all possible until they take care of this problem in the next release.

https://github.com/minio/minio/issues/14151

**Comment by javsalgar** [comment]
Thanks for letting us know!
