### ISSUE TITLE
[bitnami/metallb] enable or disable flag for speaker daemonset on MetalLB chart

### ISSUE THREAD

**Issue by cdino** [bitnami/charts#8742]
**Which chart**: bitnami/metallb

**Describe the solution you'd like**
I've deployed MetalLB with BGP on Kubernetes with Calico CNI, it works fine but the speakers are no more needed because the peering is made from the Controller via Calico and not from MetalLB Speakers.
[https://projectcalico.docs.tigera.io/networking/advertise-service-ips#advertise-service-load-balancer-ip-addresses](url)

Would be nice to have a variable where we can choose to disable the Speaker's deployment.

**Describe alternatives you've considered**

Currently, I deploy the chart, and immediately after I delete the daemonset.

**Comment by javsalgar** [comment]
Hi,

Please, note this asset is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions and releases cadence are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version, supporting the different branches supported by the upstream project as usual.

**Comment by juzerali** [comment]
@cdino @javsalgar can you please reopen this issue?
