### ISSUE TITLE
[bitnami/wordpress] [Q/A] LoadBalancer deployment stuck in pending status

### ISSUE THREAD

**Issue by AlexPresso** [bitnami/charts#8744]
**Which chart**:

bitnami/wordpress

**Describe the bug**
I've set up the wordpress chart on my k3s cluster, behind an `ingress-nginx`, while the website is working perfectly, I've noticed the chart is trying to create a LoadBalancer that redirects ports 80 and 443, but it's stuck in pending status and won't be able to run because the ingress-nginx already has a LoadBalancer running on these ports.

Is there a way to prevent it from creating the LoadBalancer ?

**To Reproduce**

```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace
```

```
helm install wp --namespace test-wordpress --create-namespace bitnami/wordpress \
    --set ingress.enabled=true \
    --set ingress.tls=true \
    --set ingress.ingressClassName=nginx \
    --set ingress.hostname=test-wordpress.com
```

`kubectl get pods -n test-wordpress`

**Expected behavior**

I'm pretty new to the kubernetes ecosystem, but maybe enabling the ingress settings in the Chart values should prevent the creation of a LoadBalancer

**Comment by AlexPresso** [comment]
Oh you mean I can directly use:
```
service:
  type: nginx
``` ?

**Comment by carrodher** [comment]
No, the supported options are `NodePort`, `ClusterIP` or the mentioned `LoadBalancer`. It seems it is not an issue related to the Helm chart but about how the application or environment is being used/configured.

For information about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the technology, such as ["Using a Service to Expose Your App"]( https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/).

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by AlexPresso** [comment]
My bad, I was misunderstanding the difference between `LoadBalancer` and `ClusterIP`, everything works fine :)
