### ISSUE TITLE
[bitnami/rabbitmq] Document how to turn particular metrics on / off

### ISSUE THREAD

**Issue by llech** [bitnami/charts#8745]
**Which chart**:

bitnami/rabbitmq

**Is your feature request related to a problem? Please describe.**

I need to expose metric to the prometheus about the particular queue size in order to use it for autoscaling service that is processing that queue.

**Describe the solution you'd like**

What I miss is the documentation about the exposed metrics and how to turn them on/off.
I've activated metrics and I'm getting Erlang VM metrics, which are not of interest for me - I'd like to turn it off. 
On the other side, the queue sizes are not exposed by default, and I'd like to turn them on.
After reading the documentation I have absolutely no clue how to do that. A more specific description and a rudimentary example would be welcomed.

**Describe alternatives you've considered**

Writing deployment that connects to the Rabbit and exposes that metrics, something like wrouesnel/postgres_exporter, but it would be an absolute overkill since Bitnami Rabbit already exposed Metrics, and *WHAT* I need is most likely written, I'm missing only the know-how *HOW* to activate it

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. The question you are asking seems to be more related with RabbitMQ itself than the chart. What the chart does is just enabling the built-in RabbitMQ metrics available. For more information on how to expose more [metrics within RabbitMQ](https://www.rabbitmq.com/monitoring.html#rabbitmq-metrics), my advice would be to check with the RabbitMQ developers to see if this is actually possible.
