### ISSUE TITLE
Not able to Run Docker build : Permission denied 

### ISSUE THREAD

**Issue by ashokspeelyaal** [bitnami/charts#8747]
**Which chart**:

bitnami/jenkins

**Describe the bug**

I need to run the Jenkins job which will build a docker image and push it to the Docker repository. 
When I do this on a Jenkins instance in a simple container on a host, I simply mount docker.sock as volume to the container. 
But, when I try to do that in Managed Kubernetes,  POD I get permission denied error. 

```
/bitnami/jenkins/home/tools/org.jenkinsci.plugins.docker.commons.tools.DockerTool/Docker/bin/docker login -u **** -p ******** https://mydocker-repo/
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.29/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/auth: dial unix /var/run/docker.sock: connect: permission denied
```

**To Reproduce**

These are the helm values for the volume mount

```yaml
extraVolumes:
  - hostPath:
      path: /var/run
    name: docker-sock
extraVolumeMounts:
   - mountPath: /var/run
     name: docker-sock
```

**Expected behavior**

Docker build should run properly

**Comment by juan131** [comment]
Hi @ashokspeelyaal 

It looks like the kind of operations you're trying to achieve require running the container as "root". Please note that, by default, the containers deployed by the Jenkins chart are executed as "non-root" containers. You can use the `podSecurityContext` & `containerSecurityContext` parameters to customize this. Find more information in the links below:

- https://github.com/bitnami/charts/blob/master/bitnami/jenkins/values.yaml#L239
- https://github.com/bitnami/charts/blob/master/bitnami/jenkins/values.yaml#L248
- https://github.com/bitnami/bitnami-docker-jenkins#why-use-a-non-root-container
