### ISSUE TITLE
Unable to use NodePort/LoadBalancer with Redis-Sentinel on Kubernetes

### ISSUE THREAD

**Issue by ping2kpm** [bitnami/charts#8751]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/redis

**Describe the bug**

I'm using Redis with Sentinel and want to use Nodeport or LoadBalancer, however when I'm changing the service Type to NodePort/LoadBalancer pods are not creating but it is working with ClusterIP. Parameters:

- `master.service.type=NodePort`
- `sentinel.enabled=true`
- `sentinel.service.type=NodePort`

Please help me if I'm missing anything

Thanks & Regards.

**Comment by Mauraza** [comment]
Hi @ping2kpm,

if you check Redis sentinel:
https://github.com/bitnami/charts/blob/74ede1e4bb45d4d5f90b0dba6c298753bd947357/bitnami/redis/templates/sentinel/statefulset.yaml#L1
with `NodePort` it will not be created so you can use `LoadBalancer`.

In master, it appears
https://github.com/bitnami/charts/blob/74ede1e4bb45d4d5f90b0dba6c298753bd947357/bitnami/redis/templates/master/statefulset.yaml#L1

Then if your architecture value is `replication` and you activate `sentinel` the master will not be deployed.

To check that it will be deployed you can use `helm template`.

**Comment by ping2kpm** [comment]
Thanks for the information.
I tried to use LoadBalancer, though pods are being created but the service type remain as ClusterIP.
Could you help me to fix my issue, below are the details.

I'm using one single server and it is single node Kubernetes cluster. I want to configure Redis with Sentinel +Replication  + Metric enabled.

[root@server1 redis]# kubectl get pods -n redis
NAME           READY   STATUS    RESTARTS   AGE
redis-node-0   3/3     Running   0          36m
redis-node-1   3/3     Running   0          35m
redis-node-2   3/3     Running   0          35m

[root@server1 ~]# kubectl get svc -n redis
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                          AGE
redis-headless  ClusterIP   None           <none>         6379/TCP,26379/TCP       35m
redis-metrics    ClusterIP   10.43.57.3     <none>        9121/TCP                         35m
redis                 ClusterIP    10.43.17.170   <none>     6379/TCP,26379/TCP       35m

I want to use NodePort, so I manually changed the service type after deployment, 

After service type change:

[root@server1 ~]# kubectl get svc -n redis
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                          AGE
redis-headless  ClusterIP   None                <none>        6379/TCP,26379/TCP               35m
redis-metrics   ClusterIP   10.43.57.3         <none>        9121/TCP                         35m
redis           NodePort    10.43.17.170   <none>        6379:32315/TCP,26379:31678/TCP   35m
[root@server1 ~]#

Writing from same server over serverIP + NodePort using sentinel

[root@server1 ~]#  kubectl -n redis exec -it redis-node-0 -c sentinel -- bash
I have no name!@redis-node-0:/$ redis-cli -h 192.168.0.1 -p 31678
192.168.0.1:31678> auth passwd
OK
192.168.0.1:31678> info replication
# Replication
role:master
connected_slaves:2
slave0:ip=redis-node-1.redis-headless.redis.svc.cluster.local,port=6379,state=online,offset=18797373,lag=1
slave1:ip=redis-node-2.redis-headless.redis.svc.cluster.local,port=6379,state=online,offset=18798027,lag=0
master_failover_state:no-failover
master_replid:5de2f88da6662bdeaf214aa814dd56b2c41a2f70
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:18798027
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:17749452
repl_backlog_histlen:1048576
192.168.0.1:31678>

Write successful.

192.168.0.1:31678> SET emp2 raja3
OK
192.168.0.1:31678> KEYS *
1) "emp2"
2) "batter2"
192.168.0.1:31678>


From same server my test is successful, however if I'm trying to connect it from outside of the K8S Cluster (note: same network).
Could you tell me how could I connect to Redis sentinel from outside of the K8s Cluster which gives me write access?


Accessing Redis over Sentinel:
=============================
JedisSentinelPool jedisPool = new JedisSentinelPool("mymaster", sentinels);

Caused by: java.net.UnknownHostException: redis-0.redis.redis.svc.cluster.local
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:65)



Thanks & Regards.

**Comment by Mauraza** [comment]
Hi @ping2kpm,

To configure the `loadBalancer` you need to give the `loadBalancerIP` 
https://github.com/bitnami/charts/blob/72691ea3f97610961a822567c291b6f05bd58b0c/bitnami/redis/templates/sentinel/service.yaml#L39-L44

You can't use `redis-0.redis.redis.svc.cluster.local` outside of the cluster. To connect to the cluster outside of the cluster you need to connect with NODE_IP and NODE_PORT.

**Comment by ping2kpm** [comment]
I'm connecting Redis cluster over sentinel from outside the K8S, connection is getting established, however throwing above error.
NodeIP + Sentinel port
192.168.0.1:31678

**Comment by ping2kpm** [comment]
I found a solution, I used HA-Proxy infront of Sentinel, now the issues has been fixed.

https://yaniv-bhemo.medium.com/how-to-setup-haproxy-for-redis-sentinel-on-kubernetes-37ee70e44464
