### ISSUE TITLE
【redis】How to connect to master from outside when sentinel enable

### ISSUE THREAD

**Issue by azui007** [bitnami/charts#8752]
**Which chart**:

bitnami/redis

**Describe the bug**
i set the "master.service.type=NodePort" and kubectl port-forward --namespace default svc/redis-test 6379:6379
but i can't connect the master  from outside .
`D:\redis>redis-cli -h 193.168.1.62 -p 6379
Could not connect to Redis at 193.168.1.62:6379: 対象のコンピューターによって拒否されたため、接続できませんでした。
not connected>`

**To Reproduce**

`helm install redis-test --set global.storageClass=ceph-rbd,global.redis.password=test1234,sentinel.enabled=true,master.service.type=NodePort,master.service.nodePorts.redis=31331,master.service.ports.redis=6379 bitnami/redis`

**Expected behavior**
redis-cli -h 193.168.1.62 -p 6379 or redis-cli -h 193.168.1.62 -p 31331 can connect master database

**Additional context**

none

thank you

**Comment by javsalgar** [comment]
Hi,

Could you translate the error message that appears in Japanese to English? We need it to understand what could be causing the issue.

**Comment by azui007** [comment]
> 

hi
Japanese to English :
Could not be connected because it was rejected by the target computer

**Comment by fmulero** [comment]
Hi @azui007,

If you give a glance to the [documentation in values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L829) you will see that enabling sentinel will disable the master and replicas services. So the configuration you are setting about master service is not being taken into account.

You can configure the sentinel service in the same way but please keep in mind the comments in [values.yaml file](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L998):
```
helm install redis-test --set global.storageClass=ceph-rbd,global.redis.password=test1234,sentinel.enabled=true,sentinel.service.type=NodePort,sentinel.service.nodePorts.redis=31331,sentinel.service.nodePorts.sentinel=32331 bitnami/redis
```

**Comment by azui007** [comment]
> Hi @azui007,
> 
> If you give a glance to the [documentation in values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L829) you will see that enabling sentinel will disable the master and replicas services. So the configuration you are setting about master service is not being taken into account.
> 
> You can configure the sentinel service in the same way but please keep in mind the comments in [values.yaml file](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L998):
> 
> ```
> helm install redis-test --set global.storageClass=ceph-rbd,global.redis.password=test1234,sentinel.enabled=true,sentinel.service.type=NodePort,sentinel.service.nodePorts.redis=31331,sentinel.service.nodePorts.sentinel=32331 bitnami/redis
> ```

Hi fmulero 
Solved my problem. Thank you !
