### ISSUE TITLE
Wordpress postgresql support

### ISSUE THREAD

**Issue by EugenMayer** [bitnami/charts#8768]
Am i right to assume that even with a external database / secret postgresql is not supported in the wordpress chart?

Neither https://github.com/bitnami/bitnami-docker-wordpress hints this nor the ENV variables in https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/deployment.yaml#L130

Thanks for the clarification!

**Comment by carrodher** [comment]
Yes, WordPress requires access to a MySQL or MariaDB database to store information, support for PostgreSQL is not implemented

**Comment by EugenMayer** [comment]
Sorry for the stupid question in the first place. I just realized that Wordpress does not support PG at all - shocking news but well, that obviously explains your setup and chart. Thanks!

You can close the issue anytime
