### ISSUE TITLE
[bitnami/minio] Provisioning Job does not support tolerations

### ISSUE THREAD

**Issue by arunsudhakar** [bitnami/charts#8769]
**Which chart**:

Minio 10.0.3

**Describe the bug**

The current template for the provisioning job does not support tolerations. As a result, when the chart is installed with provisioning enabled, the minio stateful set's get deployed but the provisioning job will be stuck in a pending state.

**To Reproduce**

1. A Cluster which requires tolerations to be set 
2. Update the values.yaml tolerations section with the taint and enable the Provisioning jobs
3. Deploy the chart
4. Provisioning job will be stuck in pending state because the template doesnt add the toleration

**Expected behavior**

The provisioning job should respect the tolerations set in the values.yaml and deploy successfully

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the PR! The team will take a look.
