### ISSUE TITLE
Airflow DAG  task fail because of PodLogOptions 'sinceSecond' not set

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/charts#8770]
Hello,
I'm using bitnami Airflow 2.2.3.

Some of our Airflow DAG tasks fail because the log cannot be written for the pod running the worker airflow service.
In the logs I see that the “sinceSeconds” is not set in the PodLogOptions causing the dag’s task to fail.
 
```
"PodLogOptions \\"taskxxxxx\\" is invalid: sinceSeconds: Invalid value: -45: must be greater than 0"
```
 
I don’t know of any ways to set the “sinceSeconds” value in the charts. Is it something that need to be set at the node level? Do you have any ideas? Any pointers would be welcome.

Thanks in advance

**Comment by juan131** [comment]
Hi @eclipsetalk 

It seems it is not an issue related to the Bitnami Airflow chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by rogerfn** [comment]
@eclipsetalk I'm actually having the same issue at the moment using airflow:2.2.4. Did you figure it out?
