### ISSUE TITLE
Performance tuning parameters

### ISSUE THREAD

**Issue by deokershesh** [bitnami/charts#8776]
Hi All,
I have deployed single node (no cluster, no replica, no sharding) Bitnami MongoDB on GCP. The node has 4 CPU, 15 GB memory and enough SSD storage.

I deployed successfully to use SSD and request for 4 cpu and required memory in the YAML chart.

I run YCSB load which loads 3000 documents each having size 4 MB. Now, I run workload with 50K operations which has 70% READ and 30% MODIFY operations with 5 threads, it takes 2455 seconds for this operation.

What all tuning parameters I can use for Bitnami\MongoDB to improve the performance of above workload which betters 2455 seconds?

Thanks for your help...

**Comment by javsalgar** [comment]
Hi,

I am afraid that this kind of consulting services is out of the scope of our support. We will leave the ticket open in case someone from the community wants to share their experience.
