### ISSUE TITLE
Issue in Kube Prometheus Chart with TLS config for ingress

### ISSUE THREAD

**Issue by vrabbi** [bitnami/charts#8779]
**Which chart**:

kube-prometheus

**Describe the bug**

There are 3 ingress objects that can be created via the helm chart:
1. prometheus
2. thanos
3. alert manager
  
The Helm chart has a different mechanism for configuring the tls for these ingress resources which makes the usage horrible!  
For Thanos it is done correctly by enabling the user to use cert manager via annotations or to add a tls section of yaml pointing to an existing secret.  
For prometheus and Alert Manager you cant point it at an existing secret making the use of a wildcard cert nearly impossible (would require copying the same cert details into the values.yaml multiple times which is not a good idea as multiple secrets will be created with the same cert and when the cert expires updating it will be horrific as it will exist in too many places.).
  
The chart needs to be standardized as currently i need to:
1. create a secret in advance for thanos
2. Get my TLS Key and certs and place those in plain text in a values yaml for prometheus
3. Get my TLS Key and certs and place those in plain text in a values yaml for Alert Manager

Is this a known issue and is it being worked on?

**To Reproduce**

Deploy with TLS for all components with pre created certs
**Expected behavior**

The same UX for ingress TLS config for all components of a single chart

**Additional context**

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by vrabbi** [comment]
@carrodher https://github.com/bitnami/charts/pull/8796 
let me know if there are any issues or how we can push this forwards as i hate using forks of charts and would love to use the official chart again but currently this is a blocker for us to use the upstream chart

**Comment by carrodher** [comment]
Thanks for creating the PR, feedback was provided about some starter points, an in-deep review will be done as well. Thanks again

**Comment by vrabbi** [comment]
@carrodher i addressed the comments in a new PR (#8834) and all tests have passed. let me know if anything else is needed
