### ISSUE TITLE
[rabbitmq] Waiting for erlang distribution on node

### ISSUE THREAD

**Issue by samsalvaticoors** [bitnami/charts#8783]
**Which chart**: 
Name: bitnami/rabbitmq                        
ChartVersion: 8.27.0
AppVersion: 3.9.1

**Describe the bug**

I was trying to deploy the chart using this command
```
$ helm upgrade --install rabbit-test bitnami/rabbitmq --atomic --wait --values values.yaml
```

These are the values I use in *values.yaml* file
```yaml
image:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: 3.9.13-debian-10-r2

  debug: true

plugins: "rabbitmq_management"

clustering:
  enabled: false
 
serviceAccount:
  create: false

rbac:
  create: false

persistence:
  enabled: true
```

Waiting for the pod to start I saw that the readiness probe and the liveness probe both fails.

So I searched for the logs of the pod and this is what I found:
```
rabbitmq 15:46:00.22 DEBUG ==> Ensuring expected directories/files exist...
rabbitmq 15:46:00.59 INFO  ==> Starting RabbitMQ in background...
Waiting for erlang distribution on node 'rabbit@rabbit-test-rabbitmq-0.rabbit-test-rabbitmq-headless.project-dev.svc.cluster.local' while OS process '54' is running
Error: operation wait on node rabbit@rabbit-test-rabbitmq-0.rabbit-test-rabbitmq-headless.project-dev.svc.cluster.local timed out. Timeout value used: 5000
```

#### Pods
```
NAME                     READY   STATUS    RESTARTS   AGE
rabbit-test-rabbitmq-0   0/1     Running   0          16s
```
#### Pod describe
```
 Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Warning  FailedScheduling        14s   default-scheduler        0/8 nodes are available: 8 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        14s   default-scheduler        0/8 nodes are available: 8 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               12s   default-scheduler        Successfully assigned project-dev/rabbit-test-rabbitmq-0 to kub1-dev-wk-04
  Normal   SuccessfulAttachVolume  13s   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-2e1c7deb-837b-4e68-81a3-94e0997b0729"
  Normal   Pulled                  3s    kubelet                  Container image "docker.io/bitnami/rabbitmq:3.9.13-debian-10-r2" already present on machine
  Normal   Created                 2s    kubelet                  Created container rabbitmq
  Normal   Started                 2s    kubelet                  Started container rabbitmq
```

#### SVC
```
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                 AGE
rabbit-test-rabbitmq            ClusterIP   10.43.83.180   <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   101s
rabbit-test-rabbitmq-headless   ClusterIP   None           <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   101s
```
#### PVC
```
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-rabbit-test-rabbitmq-0   Bound    pvc-ff98849c-9ed4-4f23-978e-c6ee76b24176   8Gi        RWO            ceph-ssd       91s
```

#### PV
```
pvc-ff98849c-9ed4-4f23-978e-c6ee76b24176   8Gi        RWO            Delete           Bound    project-dev/data-rabbit-test-rabbitmq-0
              ceph-ssd                2m
```

Thank you
**To Reproduce**

1. Create a *values.yaml* file with the values written in previous section;
2. Run the *helm upgrade* command you can find in the previous section.

**Expected behavior**

Rabbit pods liveness and readiness work fine.

**Additional context**

I think the issue is related to this one [https://github.com/bitnami/bitnami-docker-rabbitmq/issues/112](https://github.com/bitnami/bitnami-docker-rabbitmq/issues/112)

**Comment by rafariossaa** [comment]
Hi
  Which kubernetes cluster are  you using ? I tried minikube and gke and got it up and running with the instructions you provided:

```
rabbitmq 08:28:32.11 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 08:28:32.13 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 08:28:32.15 INFO  ==> Initializing RabbitMQ...
rabbitmq 08:28:32.16 DEBUG ==> Creating environment file...
rabbitmq 08:28:32.16 DEBUG ==> Creating enabled_plugins file...
rabbitmq 08:28:32.17 DEBUG ==> Creating Erlang cookie...
rabbitmq 08:28:32.18 DEBUG ==> Ensuring expected directories/files exist...
rabbitmq 08:28:32.19 INFO  ==> Starting RabbitMQ in background...
Waiting for erlang distribution on node 'rabbit@myrabbit-rabbitmq-0.myrabbit-rabbitmq-headless.default.svc.cluster.local' while OS process '55' is running
Waiting for applications 'rabbit_and_plugins' to start on node 'rabbit@myrabbit-rabbitmq-0.myrabbit-rabbitmq-headless.default.svc.cluster.local'
2022-01-26 08:28:35.444364+00:00 [info] <0.228.0> Feature flags: list of feature flags found:
2022-01-26 08:28:35.456013+00:00 [info] <0.228.0> Feature flags:   [ ] implicit_default_bindings
2022-01-26 08:28:35.456065+00:00 [info] <0.228.0> Feature flags:   [ ] maintenance_mode_status
2022-01-26 08:28:35.456094+00:00 [info] <0.228.0> Feature flags:   [ ] quorum_queue
2022-01-26 08:28:35.456112+00:00 [info] <0.228.0> Feature flags:   [ ] stream_queue
2022-01-26 08:28:35.456192+00:00 [info] <0.228.0> Feature flags:   [ ] user_limits
2022-01-26 08:28:35.456209+00:00 [info] <0.228.0> Feature flags:   [ ] virtual_host_metadata
```

**Comment by samsalvaticoors** [comment]
> Hi Which kubernetes cluster are you using ? I tried minikube and gke and got it up and running with the instructions you provided:
> 
> ```
> rabbitmq 08:28:32.11 INFO  ==> ** Starting RabbitMQ setup **
> rabbitmq 08:28:32.13 INFO  ==> Validating settings in RABBITMQ_* env vars..
> rabbitmq 08:28:32.15 INFO  ==> Initializing RabbitMQ...
> rabbitmq 08:28:32.16 DEBUG ==> Creating environment file...
> rabbitmq 08:28:32.16 DEBUG ==> Creating enabled_plugins file...
> rabbitmq 08:28:32.17 DEBUG ==> Creating Erlang cookie...
> rabbitmq 08:28:32.18 DEBUG ==> Ensuring expected directories/files exist...
> rabbitmq 08:28:32.19 INFO  ==> Starting RabbitMQ in background...
> Waiting for erlang distribution on node 'rabbit@myrabbit-rabbitmq-0.myrabbit-rabbitmq-headless.default.svc.cluster.local' while OS process '55' is running
> Waiting for applications 'rabbit_and_plugins' to start on node 'rabbit@myrabbit-rabbitmq-0.myrabbit-rabbitmq-headless.default.svc.cluster.local'
> 2022-01-26 08:28:35.444364+00:00 [info] <0.228.0> Feature flags: list of feature flags found:
> 2022-01-26 08:28:35.456013+00:00 [info] <0.228.0> Feature flags:   [ ] implicit_default_bindings
> 2022-01-26 08:28:35.456065+00:00 [info] <0.228.0> Feature flags:   [ ] maintenance_mode_status
> 2022-01-26 08:28:35.456094+00:00 [info] <0.228.0> Feature flags:   [ ] quorum_queue
> 2022-01-26 08:28:35.456112+00:00 [info] <0.228.0> Feature flags:   [ ] stream_queue
> 2022-01-26 08:28:35.456192+00:00 [info] <0.228.0> Feature flags:   [ ] user_limits
> 2022-01-26 08:28:35.456209+00:00 [info] <0.228.0> Feature flags:   [ ] virtual_host_metadata
> ```

Hi @rafariossaa we are using an internal cluster managed using Rancher.

Thank you

**Comment by rafariossaa** [comment]
Hi,
  Could you paste more lines from the error ? Maybe there is a clue there.

**Comment by samsalvaticoors** [comment]
> Hi, Could you paste more lines from the error ? Maybe there is a clue there.

Of course, these are all the entries in my log
```
rabbitmq 09:46:03.00 
rabbitmq 09:46:03.09 Welcome to the Bitnami rabbitmq container
rabbitmq 09:46:03.10 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 09:46:03.10 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 09:46:03.10 
rabbitmq 09:46:03.19 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 09:46:03.59 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 09:46:03.89 INFO  ==> Initializing RabbitMQ...
rabbitmq 09:46:04.10 DEBUG ==> Creating environment file...
rabbitmq 09:46:04.12 DEBUG ==> Creating enabled_plugins file...
rabbitmq 09:46:04.33 DEBUG ==> Creating Erlang cookie...
rabbitmq 09:46:04.41 DEBUG ==> Ensuring expected directories/files exist...
rabbitmq 09:46:04.71 INFO  ==> Starting RabbitMQ in background...
Waiting for erlang distribution on node 'rabbit@project-rabbitmq-0.project-rabbitmq-headless.project-dev.svc.cluster.local' while OS process '55' is running
Error: operation wait on node rabbit@project-rabbitmq-0.project-rabbitmq-headless.project-dev.svc.cluster.local timed out. Timeout value used: 5000
Waiting for erlang distribution on node 'rabbit@project-rabbitmq-0.project-rabbitmq-headless.project-dev.svc.cluster.local' while OS process '55' is running
Waiting for applications 'rabbit_and_plugins' to start on node 'rabbit@project-rabbitmq-0.project-rabbitmq-headless.project-dev.svc.cluster.local'
 09:51:02.70 DEBUG ==> RABBITMQ_SYNC_TIMEOUT is 110
```

Thank you for your help

**Comment by rafariossaa** [comment]
Hi,
  Not sure what can be happening here. I guess this can be related to networking or DNS, but I have not way to check this point as my deployments in different k8s cluster don't show this behavior. 
  Maybe you can disable the probes and try something of what is indicated in the diagnostics. Maybe you can also check if you got an IP for `test-rabbit-rabbitmq-0.test-rabbit-rabbitmq-headless.project-dev.svc.cluster.local`, and if the port 4369 is opened there. Just to try, maybe you can run it with a shorter name. Sometimes lengthy names can be problematic for some DNS.
  I would suggest to ask to you sysadmins and check if there is any particularity in your Rancher that can lead to this.

**Comment by samsalvaticoors** [comment]
> Hi, Not sure what can be happening here. I guess this can be related to networking or DNS, but I have not way to check this point as my deployments in different k8s cluster don't show this behavior. Maybe you can disable the probes and try something of what is indicated in the diagnostics. Maybe you can also check if you got an IP for `test-rabbit-rabbitmq-0.test-rabbit-rabbitmq-headless.project-dev.svc.cluster.local`, and if the port 4369 is opened there. Just to try, maybe you can run it with a shorter name. Sometimes lengthy names can be problematic for some DNS. I would suggest to ask to you sysadmins and check if there is any particularity in your Rancher that can lead to this.

Thank you for your help, I'll discuss it with the sysadmins and will update the issue with the possible resolution, if one is found

**Comment by rafariossaa** [comment]
Hi,
  You are welcome.
  Please, don't hesitate to come back and share your findings.
  Thanks.

**Comment by shashankgarg88** [comment]
@samsalvaticoors Were you able to resolve this issue? I am facing the exact same issue. I am trying to deploy is in Openshift env.

**Comment by kevinmnm** [comment]
I'm seeing same issue

**Comment by hubkabel** [comment]
I had the same issue. In my case, the error was the wrong clusterDomain-DNS-Suffix. Fixed it by setting clusterDomain value (see https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq)

e.g.
```
...
clusterDomain: some-other-cluster.local
...
image:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: 3.9.13-debian-10-r2

  debug: true

plugins: "rabbitmq_management"

clustering:
  enabled: false
 
serviceAccount:
  create: false

rbac:
  create: false

persistence:
  enabled: true
```

To determine the clusterDomain you can ask your cluster administrator or lookup into /etc/resolv.conf in any pod

```
cat /etc/resolv.conf
nameserver 10.96.0.10
search <namespace>.svc.cluster.local svc.cluster.local cluster.local <nod-domain>
options ndots:5
```
