### ISSUE TITLE
Redis Cluster with another master in another EKS(Kubernetes) cluster

### ISSUE THREAD

**Issue by angelorobo** [bitnami/charts#8785]
**Which chart**:
redis-cluster

**Describe the solution you'd like**

We have 2 different datacenter serving users from 2 regions. Both are connected via AWS direct connect. How can we expand our Redis cluster with another node from another EKS (Kubernetes) Cluster? So the API server on another EKS cluster can read from Redis much faster.

$ kubectl get all -n redis-ha
NAME                       READY   STATUS    RESTARTS   AGE
pod/redis-ha-1a-server-0   2/2     Running   0          99d
pod/redis-ha-1a-server-1   2/2     Running   0          99d
pod/redis-ha-1a-server-2   2/2     Running   0          99d

NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
service/redis-ha-1a              ClusterIP   None             <none>        6379/TCP,26379/TCP   316d
service/redis-ha-1a-announce-0   ClusterIP   10.100.201.252   <none>        6379/TCP,26379/TCP   316d
service/redis-ha-1a-announce-1   ClusterIP   10.100.157.70    <none>        6379/TCP,26379/TCP   316d
service/redis-ha-1a-announce-2   ClusterIP   10.100.170.195   <none>        6379/TCP,26379/TCP   316d

NAME                                  READY   AGE
statefulset.apps/redis-ha-1a-server   3/3     316d

**Comment by javsalgar** [comment]
Hi,

I'm afraid that the chart does not support this kind of multi-cluster installations out of the box. One option that comes to mind is to allow external access in the Redis cluster so the nodes are accessible. After that, you could try manually deploying another redis node.
