### ISSUE TITLE
[bitnami/minio] Enable Bucket versioning support for provisioning job

### ISSUE THREAD

**Issue by arunsudhakar** [bitnami/charts#8787]
**Which chart**:

Bitnami Minio 10.0.4

**Is your feature request related to a problem? Please describe.**

At the moment there is no option to enable versioning on buckets created using the provisioning job with object locking turned off. (Object Locking automatically enables versioning)

**Describe the solution you'd like**

There should be a parameter during bucket creation to enable bucket versioning  . This can be achieved by updating the provisioning-job.yaml

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the PR! The team will take a look
