### ISSUE TITLE
More documentation on initdbscript

### ISSUE THREAD

**Issue by woj-i** [bitnami/charts#8790]
**Which chart**:

postgres

**Is your feature request related to a problem? Please describe.**

Initdbscript documentation doesn't have some information, i.e.:
1. What is the order of execution of files in Initdbscript? Is it sequential or parallel run?
2. What happens if one of file fails? Are the others executed?
3. When scripts are run? In the middle of initialization of DB or after that? Maybe after readinesProbe?

**Describe the solution you'd like**

Text describing question above should be added here: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#initialize-a-fresh-instance 

**Describe alternatives you've considered**

It might be worth to put it here as well: https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/initialize-instance/

**Comment by juan131** [comment]
Hi @woj-i 

Thanks for bringing up this topic, I agree with you that docs can be improved and make a better job explaining how the initdb scripts work. Would you like to contribute a PR improving these sections? Thanks in advance.

**Comment by woj-i** [comment]
Hi @juan131 ! The problem is I don't know answers for questions I raised. I am looking for them and therefore I raised this ticket.

**Comment by juan131** [comment]
Hi @woj-i 

Let's answer them 🙂 !

> What is the order of execution of files in Initdbscript? Is it sequential or parallel run?

It's sequential and they're executed alphabetically ordered.

> What happens if one of file fails? Are the others executed?

No, the container initialization will stop

> When scripts are run? In the middle of initialization of DB or after that? Maybe after readinesProbe?

After PostgreSQL has been initialized, see:

- https://github.com/bitnami/bitnami-docker-postgresql/blob/master/14/debian-10/rootfs/opt/bitnami/scripts/postgresql/setup.sh#L33

More info at:

- https://github.com/bitnami/bitnami-docker-postgresql/blob/master/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L690

**Comment by bdols** [comment]
are the init scripts ran every time the pod is created? every time the pod is restarted?

**Comment by juan131** [comment]
No @bdols 

They're just executed during the 1st container initialization.

**Comment by juan131** [comment]
Yes @bdols 

During upgrades it's also true if you enabled persistence. As long as the container logic detect there's existing data in the data volumes, they'll skip the initdb scripts.
