### ISSUE TITLE
[bitnami/Postgresql-ha] Deploy on on-premises Kubernetes - Connection failure when deleting a pod

### ISSUE THREAD

**Issue by mp185316** [bitnami/charts#8791]
```
NAME                    CHART VERSION   APP VERSION   
bitnami/postgresql-ha   7.10.1          11.13.0 
```

Checking HA - fault tolerance results in connection failure.

Having a three-node cluster (three pods running) we tried to delete pods while sending a request we got errors like:
```
"Detail": "XX000: failed to create a backend 1 connection"
"Detail": "An exception has been raised that is likely due to a transient failure."
```

Is this the expected behavior? The expected behavior I think is for pgpool to recognize that the pod is down and serve the application request with another pod

**Comment by juan131** [comment]
Hi @mp185316 

Could you please share the **values.yaml** you used to deploy the chart? Thanks in advance.

**Comment by mp185316** [comment]
Hello @juan131,

Thanks for the prompt reply.

I am using the default values.yaml file retrieved from the project as it is.
In addition, I think am getting the error most of the time when I am deleting the primary pod.
Are there any configurations that I must set in order to avoid the failure connection error when deleting a pod?

**Comment by miguelaeh** [comment]
Hi @mp185316 ,
Is it possible that you are trying to perform a write operation that can only be done in the primary node and, in the time you are trying to perform that operation, a new primary election process is in progress?
What happens if you wait some time for the cluster to elect a new primary?

**Comment by mp185316** [comment]
Hello @miguelaeh,

Specifically am doing a GET operation from the backend. Am using a bare metal Kubernetes cluster on-prem and due to this, I don't have any provisioner. I created manually first the persistent volume, then the persistent volume claim, and then I installed Postgres-ha through the command:	
helm install postgresdb bitnami/postgresql-ha --set persistence.existingClaim="name-of-my-claim" --set volumePermissions.enabled=true

If I wait some time for the cluster to elect the new primary, I am getting the response without any error, but I am not sure if this is the correct behavior? I was expecting to don't have any downtime (a GET operation) and get the result through replica pod without the error described above.

**Comment by miguelaeh** [comment]
Hi @mp185316 ,
It is possible that you made the request before PgPool notices the node failure? If you give it a bit more time before performing the request does it work?
It can happen that, if PgPool does not know yet about the node failure and it could be sending the request to the failed node.
