### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] Create a RabbitMQ Instance failed

### ISSUE THREAD

**Issue by clcc2019** [bitnami/charts#8792]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/46099295/151131899-749fde5c-0bc9-4e9b-a75b-be6642665450.png">

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/46099295/151131931-efcf39f8-1c32-4f2b-8632-c3d170b334da.png">

**Comment by carrodher** [comment]
Are you using any custom parameter or are you deploying the chart using the default ones?
Are you able to reproduce the issue by installing it in a clean namespace from scratch? Take into account some PVs, PVCs, CRDs from previous deployments can affect if they're not properly removed
