### ISSUE TITLE
[bitnami/rabbitmq] How to Avoid Exposing Credentials

### ISSUE THREAD

**Issue by bwmills** [bitnami/charts#8820]
Greetings,

We are using: 

* RabbitMQ chart version `8.24.8` 
* Immutable tag: `3.9.10-debian-10-r4`
* Kubernetes `1.21` in EKS

Would like to avoid exposing credentials in our code base ( in _helm-release.yml_ ).

Similar to #6163 and #7766, it would be great to use:

```
    auth:
      username: some_user
      existingPasswordSecret: rabbitmq-credentials
      existingErlangSecret: rabbitmq-credentials
```

where our secret values are stored in AWS Secrets Manager, and also use `load_definitions`:

```
    loadDefinition:
      enabled: true
      existingSecret: load-definition
    extraConfiguration: |-
      load_definitions = /app/load_definition.json
    extraSecrets:
      load-definition:
        load_definition.json: |
          {
            "vhosts": [
              {
                "name": "some_vhost"
              }
            ],
            "users": [
              {
                "name": "{{ .Values.auth.username }}",
                "password": "{{ .Values.auth.existingPasswordSecret }}",
                "tags": "administrator"
              }
            ],
            "permissions": [
              {
                "user": "{{ .Values.auth.username }}",
                "vhost": "some_vhost",
                "configure": ".*",
                "write": ".*",
                "read": ".*"
              }
            ],
            "policies": [
              {
                "name": "ha-lazy",
                "pattern": ".*",
                "vhost": "some_vhost",
                "apply-to": "queues",
                "priority": 1,
                "definition": {
                  "queue-mode": "lazy",
                  "ha-mode": "exactly",
                  "ha-params": 2,
                  "ha-sync-mode": "automatic",
                  "ha-sync-batch-size": 100
                }
              }
            ],
            "queues": [
             ...
```

to further automate the deployment and its config for policies, queues and so forth.

It's clear that this can't be done. That is:

> If you provide the load_definitions the user password is not read from the secret.

This seems to be mutually exclusive by design. 

My question: what is the recommended solution? How can we make use of `load_definitions` while storing credentials only in secrets? Is the best practice to use `extraSecrets:` that reference manually-created secrets?

Would using an init container that creates `load_definition.json` and writes it somewhere in the container to later be copied into `/app` by the main image be viable?

If there is a recommended or even just common solution, please provide a brief example if possible.

**Comment by rafariossaa** [comment]
Hi,
  I think the following could work in you scenario:
  If you have two sources, one for the username and other for the password for that username, you'd need to use the `load_definitions` and generate that file with the username and the password. For that I'd suggest you to use an init container and generate the file in a path. Then, use `extraConfiguration` to indicate where the `load_definitions` file is located.

**Comment by bwmills** [comment]
Many thanks @rafariossaa for this feedback! I will give this a spin today.

**Comment by bwmills** [comment]
Some delays - will follow-up soon.

**Comment by rafariossaa** [comment]
Don't worry. Come back when you have news.
