### ISSUE TITLE
[bitnami/external-dns] Can't deploy to AKS with MSI clusters.

### ISSUE THREAD

**Issue by monaka** [bitnami/charts#8822]
**Which chart**:

external-dns

**Describe the bug**

Can't deploy the chart with error below

```
error validating data: ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[0]): missing required field "mount
Path" in io.k8s.api.core.v1.VolumeMount 
```

**To Reproduce**

Deploy the chart with values to AKS clusters.

```
provider =  azure                                                                                                                            
azure.useManagedIdentityExtension  = true
```

Other values with `azure.` prefix is default.

**Expected behavior**

Deployed with no error.

**Additional context**

I'll send PR soon.

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
