### ISSUE TITLE
Question: support for placing the primaries and the corresponding replicas of the cluster in separate k8s nodes?

### ISSUE THREAD

**Issue by samitpal** [bitnami/charts#8829]
**Which chart:**

Redis Cluster

**Is your feature request related to a problem? Please describe.**

Just curious if the chart supports placing the primaries and the corresponding replicas of the cluster in separate k8s nodes so that it can survive a machine failure.

**Describe the solution you'd like**

In case it is not supported it might be great to provide capabilities that can let us place the primary and the corresponding replicas in separate machines.

**Comment by juan131** [comment]
Duplicate of https://github.com/bitnami/charts/issues/8441
