### ISSUE TITLE
[bitnami/mariadb] list of databases to create if not exist

### ISSUE THREAD

**Issue by ChipWolf** [bitnami/charts#8833]
**Which chart**: mariadb

**Is your feature request related to a problem? Please describe.**

I find myself manually creating databases, everything else is mostly on autopilot.

**Describe the solution you'd like**

I'd like to include a list of databases I expect to be created if they don't already exist in the helm values.
This would allow our team to contribute new database names to our gitops repo rather than having shell access to the container.

**Describe alternatives you've considered**

Continuing to use `kubectl exec mariadb -- mysql .....` to create databases manually.

**Comment by juan131** [comment]
Hi @ChipWolf 

I recommend you to take a look to the section below that describes an alternative to achieve that:

- https://github.com/bitnami/charts/tree/master/bitnami/mariadb#initialize-a-fresh-instance
