### ISSUE TITLE
[MariaDB] create secret for auth secret

### ISSUE THREAD

**Issue by vasanthaganeshk** [bitnami/charts#8836]
**MariaDB**:

Chart version: 10.3.2

**Is your feature request related to a problem? Please describe.**

When I provide auth credentials via the values file in maria-db chart, there is no corresponding secret created. Since there is no secret, I have to manually create one for other services to use one or just pass the db creds again in a different chart.

**Describe the solution you'd like**

Create a new secret with the credentials provided in auth section of the `values.yaml` file

**Describe alternatives you've considered**

Alternative solution is to manually create a secret and pass it to both maria db and other service.

**Additional context**

I'm using maria db with nextcloud, it'd be easier if the secret was created and I could just reuse it with nextcloud.

**Comment by juan131** [comment]
Hi @vasanthaganeshk 

This chart creates a secret with MariaDB credentials by default unless the `auth.existingSecret` parameter is set, see:

- https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml#L122

Could you please provide the `values.yaml` (or equivalent parameters) you're using to deploy the chart?
