### ISSUE TITLE
[bitnami/spring-cloud-dataflow] enable deployer secretRefs

### ISSUE THREAD

**Issue by sergiupantiru** [bitnami/charts#8837]
**Which chart**: bitnami/spring-cloud-dataflow

**Is your feature request related to a problem? Please describe.**

`deployer.<application>.kubernetes.secretRefs` cannot be set via helm chart (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_secret_references)

**Describe the solution you'd like**

It would be nice to be able to se it. 

**Describe alternatives you've considered**

**Additional context**

**Comment by carrodher** [comment]
Thanks for this suggestion. Would you like to contribute by creating a PR to implement this new feature? The Bitnami team will be happy to review it and provide feedback.

**Comment by sergiupantiru** [comment]
I will give it a try ;)

**Comment by sergiupantiru** [comment]
While running `readme-generator -v values.yaml -r README.md` I see more changes to the `README.MD` file. Is this to be expected?

**Comment by carrodher** [comment]
> While running `readme-generator -v values.yaml -r README.md` I see more changes to the `README.MD` file. Is this to be expected? [sergiupantiru@a284046](https://github.com/sergiupantiru/charts/commit/a2840460eddac65972d6ca3cdf4b500ea6038cb5)

Yep, it's normal, it synchronizes the existing README and changes in the values.yaml so some changes can be added as well if it was not executed in some time
