### ISSUE TITLE
[bitnami/oauth2-proxy] Google secret is always created regardless of the enabled flag

### ISSUE THREAD

**Issue by sarahhenkens** [bitnami/charts#8850]
**Which chart**:

bitnami/oauth2-proxy

**Describe the bug**

When the google OIDC intregration is disabled with the following values, the associated secret is still auto created.
```yaml
configuration:
  google:
    enabled: false
```

**To Reproduce**

Deploy the chart with:
```yaml
configuration:
  google:
    enabled: false
```

Inspect the secret:
```bash
$ kubectl get secrets oauth2-proxy-google

NAME                  TYPE     DATA   AGE
oauth2-proxy-google   Opaque   1      68m
```

**Expected behavior**

Expected the `oauth2-proxy-google` secret not be created.

**Additional context**

The underlying problem is the secret yaml template is not using the correct values path in its IF clause:
https://github.com/bitnami/charts/blob/master/bitnami/oauth2-proxy/templates/secret-google.yaml#L1
```yaml
{{- if and .Values.configuration.google (not .Values.configuration.google.existingSecret) }}
```

This should be:
```yaml
{{- if and .Values.configuration.google.enabled (not .Values.configuration.google.existingSecret) }}
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.
