### ISSUE TITLE
[bitnami/redis] Sometimes All Three Pods are Marked as Master After Startup

### ISSUE THREAD

**Issue by jose-galvez** [bitnami/charts#8851]
**Which chart**:

bitnami/redis version: 16.2.1

**Describe the bug**

When the call `get-master-addr-by-name mymaster` to retrieve the master takes more than the timeout of 5 seconds, all nodes decide to become "master"
https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/scripts-configmap.yaml#L101-L107

**To Reproduce**

1. Create a redis cluster using: ` helm upgrade --install --dependency-update redis -n redis-test --create-namespace -f redis-values.yaml ~/repo/charts/bitnami/redis/ --debug`

This is the contents of `redis-values.yaml`:
```image:
  registry: docker.io
  repository: bitnami/redis
  tag: 6.2.6-debian-10-r103

replica:
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 200m
      memory: 100Mi

sentinel:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 6.2.6-debian-10-r100
  downAfterMilliseconds: 3000
  failoverTimeout: 3000
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 50Mi
  extraVolumeMounts:
  - name: tmp
    mountPath: "/tmp"
```

2. Once the redis pods are up, you can see that all 3 are marked as master.

We noticed that in our cluster, the current `timeout 5` was short enough that `get_sentinel_master_info` would always return a non zero exit code for all nodes [here](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/scripts-configmap.yaml#L101-L102), therefore setting them all up to be "master". We noticed that just increasing that timeout to 10 fixes the problem for us.

**Expected behavior**

Only one master should exist. If the command to [get master info](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/scripts-configmap.yaml#L81-L90) timed out it doesn't necessarily mean that there is no master so the logic under https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/scripts-configmap.yaml#L101-L102 could be improved so it handles a timeout different than receiving null from the `get-master-addr-by-name` call, or the timeout could be larger

**Additional context**

We have tried to reproduce in a local minikube or kind but since we don't have any other resources than redis we couldn't reproduce the issue. But we were able to see this consistently on our development AWS cluster. We also noticed that this timeout was added under [this pull request](https://github.com/bitnami/charts/pull/8476) and it was noted that this could be a potential issue.

**Comment by dannylee-** [comment]
@tomislater Looks like it might have been caused by this change - https://github.com/bitnami/charts/pull/8563

**Comment by jose-galvez** [comment]
@alemorcuq if we remove the timeout it works for us, and I agree that it probably shouldn't be there, but it seems like it was added on [this PR](https://github.com/bitnami/charts/pull/8476) fixing [this other issue](https://github.com/bitnami/charts/issues/8451) where it seems like it was hanging on startup so I guess removing it would just introduce that issue again

**Comment by jose-galvez** [comment]
I wanted to do a quick bump on this ticket to see if there's any plans on either removing the timeout or increasing it. We are currently blocked from upgrading to the latest because of this so any insight on it would help us a lot @eigenmannmartin

**Comment by alemorcuq** [comment]
I'd say let's remove the timeout. I see on #8616 it was added to prevent the liveness probe from killing the pod, but I don't think that's the right thing to do. IMO, if the liveness probe is killing the pod before it starts then the probe should be adapted (or even use a startup probe).

Would you like to contribute with a PR?

**Comment by jack1902** [comment]
@alemorcuq Do you have an example startup probe to use here since I can't spinup a redis-sentinel cluster without the `timeout` as the `livenessProbe` kills it.

Raised: https://github.com/bitnami/charts/issues/9227
