### ISSUE TITLE
[bitnami/grafana-operator]

### ISSUE THREAD

**Issue by 1naboki1** [bitnami/charts#8853]
**Which chart**:

bitnami/grafana-operator release: 2.2.2

**Describe the bug**

The grafana-plugins-init-container-image will always mount the baseImage

https://github.com/bitnami/charts/blob/9fb725ce244079fc8a3cfa1c215d2550b9eef268/bitnami/grafana-operator/templates/deployment.yaml#L84-L88

**Expected behavior**

Seperate baseImage/tag from and plugininitimage/tag in deployment,yaml and value.yaml, so that there is no need to manual adjust the deployment yaml with every bitnami grafana-operator release

**Additional context**

https://github.com/grafana-operator/grafana_plugins_init

**Comment by carrodher** [comment]
Thanks for the suggestion! Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by ronleb** [comment]
Hello, I would also be interested in this feature, I submitted a proposal as a PR for review

**Comment by carrodher** [comment]
Thanks for creating the PR, we will review it and provide feedback
