### ISSUE TITLE
bitnami/kafka: tls not working properly with existingSecrets

### ISSUE THREAD

**Issue by richardporras** [bitnami/charts#8856]
bitnami/kafka: 15.0.1

`/scripts/setup.sh` is looking for the keystore `/certs-${ID}/kafka-keystore.jks`. In the chart documentation, this file is spelled with a dot. 
```
kubectl create secret generic kafka-jks-0 --from-file=kafka.truststore.jks=./kafka.truststore.jks --from-file=**kafka.keystore.jks**=./kafka-0.keystore.jks
```
If I create the secret as described in the documentation I got the error:
```
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
```
This is because `/scripts/setup.sh` is expecting `kafka-keystore.jks` and not `kafka.keystore.jks`. 

In my opinion `/scripts/setup.sh` should be modified in the kafka docker image.
Instead of:
```
JKS_KEYSTORE="/certs-${ID}/kafka-keystore.jks"
```
it should be:
```
JKS_KEYSTORE="/certs-${ID}/kafka.keystore.jks"
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.
