### ISSUE TITLE
[influxdb] cert-manager integration broken after upgrade to 3.0.2

### ISSUE THREAD

**Issue by stieler-it** [bitnami/charts#8866]
**Which chart**:

influxdb 3.0.2

**Describe the bug**

After upgrading from 2.x to 3.0.2 the `certManager: true` flag is needed to use TLS with certManager. The value should not be needed since it is deprecated according to documentation: https://github.com/bitnami/charts/blob/master/bitnami/influxdb/values.yaml#L872

**To Reproduce**

Deploy InfluxDB chart, set `tls: true` and configure a cert manager annotation but do NOT set `certManager: true`.

**Expected behavior**

Ingress resource with TLS section is created

**Additional context**

It appears that in the template there are two "and" conditions that lead to this wrong behaviour:
* https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/ingress.yaml#L71
* https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/ingress.yaml#L73

**Comment by carrodher** [comment]
Thanks for reporting this issue, it is due to a standardization done across charts. It's been discussed at https://github.com/bitnami/charts/issues/8630. In order to maintain all the conversations in a single place, I am closing this issue to continue in the mentioned oned
