### ISSUE TITLE
[MongoDB] arbiter extraFlags duplicates MONGODB_EXTRA_FLAGS env var

### ISSUE THREAD

**Issue by yohboy** [bitnami/charts#8872]
**Which chart**:
MongoDB Chart v11.0.1

**Describe the bug**
When adding extraFlags to the MongoDB arbiter with tls enabled, it duplicates the MONGODB_EXTRA_FLAGS env var. One variable contains tls flags added by the chart, and one more variable contains the extraFlags.

**To Reproduce**

Enable tls, replicaset, arbiter, and add extraFlags to both replicaset members and arbiter.

**Expected behavior**
When adding extraFlags to the MongoDB arbiter with tls enabled, I expected to get all flags in the same variable. This is already done for replicaset members.

**Additional context**
Looking at both `statefulset.yaml` in `templates/arbiter` and in `templates/replicaset`, the extraFlags management is different. Is there a reason for that difference?

In `templates/replicaset/statefulset.yaml`:
```      
{{- $extraFlags := .Values.extraFlags | join " " -}}
{{- if .Values.tls.enabled }}
  {{- $extraFlags = printf "--tlsMode=%s --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert %s" .Values.tls.mode $extraFlags  }}
{{- end }}
{{- if ne $extraFlags "" }}
- name: MONGODB_EXTRA_FLAGS
  value: {{ $extraFlags | quote }}
{{- end }}
```

In `templates/arbiter/statefulset.yaml`:
```    
{{- if and .Values.tls.enabled .Values.arbiter.enabled }}
- name: MONGODB_EXTRA_FLAGS
  value: --tlsMode={{ .Values.tls.mode }} --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
{{- end }}
{{- if .Values.arbiter.extraFlags }}
- name: MONGODB_EXTRA_FLAGS
  value: {{ .Values.arbiter.extraFlags | join " " | quote }}
{{- end }}
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by yohboy** [comment]
Hi @carrodher, I'm interested to contribute for sure! I submitted a PR for this bug.

**Comment by carrodher** [comment]
Thanks! The team will review the PR and provide feedback. Thanks again for your contribution
