### ISSUE TITLE
Fail to recover the master node properly after a node failure: replica set IDs do not match.

### ISSUE THREAD

**Issue by vincent-herlemont** [bitnami/charts#8877]
**Which chart**:

MongoDB 11.0.2 [helm/bitnami/mongodb](https://artifacthub.io/packages/helm/bitnami/mongodb)

**Describe the bug**

Fail to recover the master node properly after a node failure.

**To Reproduce**

1. Download and extract the project: [mongodb-prototype.zip](https://github.com/bitnami/charts/files/7987440/mongodb-prototype.zip)
2. Build Helm dependencies `helm dependency build`
3. Start the cluster (with [K3d](https://k3d.io/v5.0.3/)) `k3d cluster create -c ./k3d-config.yaml`. The K8s cluster contains 4 agent nodes.
4. Install the chart helm `helm install mongodb .` The MongoDB cluster has 3 replicas (1 primary, 2 secondary).
5. Wait for all statefulset are ready:
    ```bash
    statefulsets=$(kubectl get statefulset --no-headers -o name)
    [ ! -z "$statefulsets" ] && echo $statefulsets | xargs -n1 kubectl rollout status --watch --timeout=300s
    ```
6. Test if we can make a request on the cluster:
    ```bash
    kubectl exec --stdin --tty svc/mongodb  -- mongo 'mongodb://test_user:test_password@mongodb:27017/test?authSource=admin&replicaSet=rs0&w=majority' --eval "db.accounts.find( { test: 'test' } )"
    MongoDB shell version v4.4.12
    connecting to: mongodb://mongodb:27017/test?authSource=admin&compressors=disabled&gssapiServiceName=mongodb&replicaSet=rs0&w=majority
    Implicit session: session { "id" : UUID("1aa71f56-5d96-4506-b483-ff3afc26a44d") }
    MongoDB server version: 4.4.12
    { "_id" : ObjectId("61fa956b2fc5552d05eb2bb5"), "test" : "test" }
    ```
7. Simulate a node failure, (preferably the master node for me `k3d-mongodb-agent-0`). And kill/delete it:
    ```bash
    docker kill k3d-mongodb-agent-0
    kubectl delete node/k3d-mongodb-agent-0
    ```
8. After the new pod is created in the new node, the connection is slower and we can show erros on logs:
    ```bash
    kubectl logs -f svc/mongodb
    ...
    {"t":{"$date":"2022-02-02T14:38:53.106+00:00"},"s":"I",  "c":"NETWORK",  "id":5940901, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"Stale primary detected, marking its state as unknown","attr":{"primary":"mongodb-0.mongodb.default.svc.cluster.local:27017","incomingElectionIdSetVersion":{"electionId":{"$oid":"7fffffff0000000000000003"},"setVersion":1},"currentMaxElectionIdSetVersion":{"electionId":{"$oid":"7fffffff0000000000000004"},"setVersion":8}}}
    {"t":{"$date":"2022-02-02T14:38:54.693+00:00"},"s":"I",  "c":"REPL_HB",  "id":23974,   "ctx":"ReplCoord-12","msg":"Heartbeat failed after max retries","attr":{"target":"mongodb-0.mongodb.default.svc.cluster.local:27017","maxHeartbeatRetries":2,"error":{"code":93,"codeName":"InvalidReplicaSetConfig","errmsg":"replica set IDs do not match, ours: 61fa9568d23dbaa49b7ef759; remote node's: 61fa97533c00f634840141c7"}}}
    ...
    ```

**Expected behavior**

The statefulset should recreate the missing node and connect to the existing MongoDB cluster without troubleshooting.

**Additional context**

[MongoDB error InvalidReplicaSetConfig - ReplicaSet IDs do not match #4115](https://github.com/bitnami/charts/issues/4115)

**Comment by fmulero** [comment]
Hi @vincent-herlemont, thanks a lot for the detailed explanation, very helpful, I appreciate it.

The issue was reproduced, but due to other priorities we are not able to give you an ETA. Please share any clue  or a PRs if you find the solution, any contribution is always welcome.

**Comment by dtrinf** [comment]
Hi all, I'm experiencing a similar problem, if I deploy the chart, everything works fine, but after that, if I change the external access to LoadBalancer, the chart recreates tue last container into the stateful set, and it is not able to join the cluster.

**Comment by fmulero** [comment]
Hi @dtrinf thanks for sharing

Not sure about your case, because we don't have enough data, but please ensure first that you are not creating a new installation with previous persistent volumes.

Said that, these other tickets could be related:
* #5752
* #6741

**Comment by dtrinf** [comment]
HI @fmulero, thanks for your support.
No, I've done several tests, the first one, create the replicaset with externalAccess as ClusterIP, it works perfect, and after that, change the access to LoadBalancer, this made the last node into the replicaset to fail, but the rest works fine.
After that, I delete all the stack, including PVs and namespace, and deploy the chart with externalAcces as ClusterIP from scratch, it doesn't work at all.
The last test was to destroy and test the chart again with ClusterIP, it works fine.

**Comment by fmulero** [comment]
Hi @vincent-herlemont I can not reproduce your issue with latest chart version(11.1.0), Could you give it a try and share your results?

**Comment by javsalgar** [comment]
Hi @dtrinf , I think this issue can be closed now this fix was merged https://github.com/bitnami/charts/pull/9387

**Comment by rahimalizada** [comment]
Installing helm chart with defaults and replica set enabled (name-rs) and killing one of the replicas changes the replica set name to name-replica-set and marks it as ghost replica

**Comment by fmulero** [comment]
Hi @rahimalizada To keep a better track about that problem, could you open a new issue with that information?
