### ISSUE TITLE
Usage of persistence of Magento in Azure AKS cluster

### ISSUE THREAD

**Issue by atroxix** [bitnami/charts#8880]
**Which chart**: bitnami-aks/magento 19.2.3

**Is your feature request related to a problem? Please describe.**

Persistence is enabled in the default configuration of Magento Helm chart, so I suppose that usage of persistence is considered a best practice?

I’m wondering how are Magento upgrades and scaling meant to be done with persistence enabled? If I understand it correctly then using persistence makes all the pods use the same Magento application files on the same volume, which means that if any one of the pods change anything in there, all the other pods get the update too. So when deploying some code changes then all the pods would be affected by this deployment process - this kind of defeats the idea of rolling updates and independence of pods in general.

Am I missing something in this picture?

**Describe the solution you'd like**

It seems to me that better default behavior would be:
* Set persistence to false by default

**Describe alternatives you've considered**
I don't really know what would be the best practice in this case. One alternative that came to my mind:
* Create a storage snapshot on every pod installation, so that it would be possible to revert to the previous version. Not sure how exactly this should be incorporated into automated upgrade or revert process though.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
