### ISSUE TITLE
Enabling PHP FPM in Magento Azure AKS cluster

### ISSUE THREAD

**Issue by atroxix** [bitnami/charts#8881]
**Which chart**: bitnami-aks/magento 19.2.3

**Is your feature request related to a problem? Please describe.**

I have installed Bitnami Magento with Helm and I’d now like to make Magento pods to use PHP FPM instead of Apache module, but I don’t see any options for this in the Helm chart.

**Describe the solution you'd like**

I see there are some FPM related variables used in scripts/libphp.sh and scripts/php/setup.php, so is it possible to get FPM working by defining some extra environment variables when installing the Magento Helm package?

**Describe alternatives you've considered**

Maybe there’s some documentation about it that I’ve missed?
Should I create some custom Docker image with PHP-FPM enabled and let Apache/Nginx be redirecting to it?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.
