### ISSUE TITLE
[bitnami/postgresql] Chart broken when primary.extendedConfiguration is used.

### ISSUE THREAD

**Issue by jim-barber-he** [bitnami/charts#8884]
**Which chart**:

bitnami/postgresql

**Describe the bug**

If I set the `primary.extendedConfiguration` value for the deployment then Helm dies with the following error:
```
 Error: Failed to render chart: exit status 1: Error: template: postgresql/templates/primary/statefulset.yaml:548:21: executing "postgresql/templates/primary/statefulset.yaml" at <include "postgresql.primary.extendedConfigmapName" .>: error calling include: template: postgresql/templates/_helpers.tpl:161:15: executing "postgresql.primary.extendedConfigmapName" at <printf>: wrong number of args for printf: want at least 1 got 0
```

I'm pretty sure the problem is that `printf` has been entered twice accidentally on line 161 of the `template/_helpers.tpl` file.
```
    {{- printf printf "%s-extended-configuration" (include "postgresql.primary.fullname" .) -}}
```
should be:
```
    {{- printf "%s-extended-configuration" (include "postgresql.primary.fullname" .) -}}
```

**To Reproduce**

I've set this in my values file that I'm passing to the chart.
```
primary:
  extendedConfiguration: |
    effective_cache_size = 1GB
    pg_stat_statements.max = 10000
    pg_stat_statements.track = all
    shared_buffers = 2GB
```

Trying to deploy with Helm results in the error I wrote earlier.

**Expected behavior**

No error when I try to deploy the chart

**Additional context**

None.

**Comment by juan131** [comment]
Hi @jim-barber-he 

Thanks so much for reporting the issue!! That's a bug introduced in the major standardization I did yesterday (see #8827). I just created a PR to address this.
