### ISSUE TITLE
[bitnami/kafka] Redis&trade in comments

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#8888]
https://github.com/bitnami/charts/blob/8dc89066cfa0c09dd3c40d9c1d04af6935290e71/bitnami/kafka/values.yaml#L764

This might be a mistake (or a copy/paste error)?

**Comment by carrodher** [comment]
Thanks for noting this. It is not an issue, `&trade;` is rendered as the trademark symbol (&trade;) in markdown.

Those comments in the `values.yaml` are used to automatically generate the table in the README listing all the available parameters:
![Screenshot 2022-02-04 at 07 50 31](https://user-images.githubusercontent.com/13216600/152484957-36a56c52-a277-4643-b7e8-c01a7c6fc609.png)

So although `&trade;` doesn't have sense in a yaml file, it is used in the markdown

**Comment by carrodher** [comment]
You're totally right, sorry. Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.
