### ISSUE TITLE
[bitnami/harbor]: Passwords dont get saved after helm upgrade

### ISSUE THREAD

**Issue by pascalrimann** [bitnami/charts#8889]
**Which chart**:

bitnami/harbor

**Describe the bug**

After Upgrading the application with helm upgrade the LDAP and dockerhub password is not correct anymore, after adding them again it work again.

**To Reproduce**

1. deploy helm chart
2. add ldap/dockerhub integration over web
3. update helm chart
4. login with ldap not working (invalid credentials)/ pull over harbor from dockerhub not working

**Expected behavior**

LDAP login should work/Pull over harbor from dockerhub is working

**Comment by carrodher** [comment]
What parameters are you specifying during the upgrade? Please note you need to set some values, see
- https://github.com/bitnami/charts/tree/master/bitnami/harbor#configure-the-secrets

Passwords (and other elements) need to be passed, for example:
```
$ export HARBOR_ADMIN_PASSWORD=$(kubectl get secret --namespace default harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)
$ export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace default harbor-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ export POSTGRESQL_PVC=$(kubectl get pvc -l app.kubernetes.io/instance=harbor,app.kubernetes.io/name=postgresql,role=master -o jsonpath="{.items[0].metadata.name}")

$ helm upgrade harbor bitnami/harbor \
    --set harborAdminPassword=$HARBOR_ADMIN_PASSWORD \
    --set postgresql.postgresqlPassword=$POSTGRESQL_PASSWORD \
    --set postgresql.persistence.existingClaim=$POSTGRESQL_PVC
```

Please note the above code is just an example, you need to use the parameters you are setting.

**Comment by pascalrimann** [comment]
it is not about helm values,. it is about the ldap password inside the application

**Comment by alemorcuq** [comment]
Let me try to reproduce this and get back to you.

**Comment by pascalrimann** [comment]
@alemorcuq any updates on this?

**Comment by alemorcuq** [comment]
Yes, @pascalrimann, sorry for the late reply. I was able to reproduce the issue using the chart but not using a docker compose deployment, which leads me to believe this is an issue on our side. Thanks for double checking.

I wasn't able to identify the root cause on my investigation, so I've created an internal task to address it. However, I can't give you an ETA.

**Comment by pascalrimann** [comment]
Hi @alemorcuq is there any updates to this topic?

**Comment by carrodher** [comment]
Not yet, unfortunately this task is still on our backlog

**Comment by pascalrimann** [comment]
we just updated our Harbor to version 2.5 chartversion 12.3.6 and there we do not have this issue.

**Comment by MostafaNegim** [comment]
We face this issue and we want to use version 2.3.*. Do you have any updates about this issue?
