### ISSUE TITLE
[bitnami/postgresql] Secret will not update properly when moving from postgresql Helm chart version 10.16.2 to 11.0.1

### ISSUE THREAD

**Issue by jim-barber-he** [bitnami/charts#8900]
### Name and Version

bitnami/postgresql 11.0.1

### What steps will reproduce the bug?

I'm upgrading the bitnami/postgresql Helm chart from version 10.16.2 to 11.0.1

I've modified the values that I'm supplying to suit the new chart, one of which is changing:
```
postgresqlPassword: password
```
to:
```
auth:
  postgresPassword: password
```

### Are you using any custom parameters or values?

As per the above I'm supplying:
```
auth:
  postgresPassword: password
```

### What is the expected behavior?

That the chart upgrades successfully from 10.16.2 to 11.0.1 once I've made the necessary adjustments to the values that I supply.

### What do you see instead?

Helm is dying with the following error:
```
  Error: UPGRADE FAILED: execution error at (postgresql/templates/secrets.yaml:17:24): 
  PASSWORDS ERROR: The secret "heweb-postgres" does not contain the key "postgres-password"
```

### Additional information

The Helm diff plugin shows that the secret will be changing like so:
```
default, heweb-postgres, Secret (v1) has changed:
...
  kind: Secret
  metadata:
    name: heweb-postgres
+   namespace: default
    labels:
      app.kubernetes.io/name: postgresql
-     helm.sh/chart: postgresql-10.16.2
+     helm.sh/chart: postgresql-11.0.1
      app.kubernetes.io/instance: heweb-postgres
      app.kubernetes.io/managed-by: Helm
-   namespace: default
  type: Opaque
  data:
-   postgresql-password: "password"
+   postgres-password: "password"
+   # We don't auto-generate LDAP password when it's not provided as we do for other passwords
```

So you can see that it intends to modify the `data.postgresql-password` field to be `data.postgres-password` instead.
But the chart is dying on this code in the `templates/secrets.yaml` file.
```
  postgres-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "postgres-password" "providedValues" (list "global.postgresql.auth.postgresPassword" "auth.postgresPassword") "context" $) }}
```

The problem being that it is trying to look at the existing secret prior to it being updated yet.
It would be good if the chart could handle this upgrade automatically without manual intervention since we have a lot of environments to update, including in developer's minikube environments.

**Comment by jim-barber-he** [comment]
Maybe one possible fix is that in the bitnami/common chart in `templates/_secrets.tpl` it has the following code block within the definition of `common.secrets.passwords.manage`
```
{{- if $secretData }}
  {{- if hasKey $secretData .key }}
    {{- $password = index $secretData .key }}
  {{- else }}
    {{- printf "\nPASSWORDS ERROR: The secret \"%s\" does not contain the key \"%s\"\n" .secret .key | fail -}}
  {{- end -}}
{{- else if $providedPasswordValue }}
  {{- $password = $providedPasswordValue | toString | b64enc | quote }}
{{- else }}
```
Where is checks if the secret already exists; then if it has the key then use the value from it, otherwise throw an error about the key missing.
What if instead of throwing the error it does a further check to see if the password has been provided, and if so, use that, otherwise then throw the error.
E.g.
```
{{- if $secretData }}
  {{- if hasKey $secretData .key }}
    {{- $password = index $secretData .key }}
  {{- else }}
    {{- if $providedPasswordValue }}
      {{- $password = $providedPasswordValue | toString | b64enc | quote }}
    {{- else }}
      {{- printf "\nPASSWORDS ERROR: The secret \"%s\" does not contain the key \"%s\"\n" .secret .key and no password value has been provided | fail -}}
    {{- end -}}
  {{- end -}}
{{- else if $providedPasswordValue }}
  {{- $password = $providedPasswordValue | toString | b64enc | quote }}
{{- else }}
```

**Comment by jim-barber-he** [comment]
Or alternatively an even simpler approach is to replace the code block above with:
```
{{- if and $secretData (hasKey $secretData .key) }}
    {{- $password = index $secretData .key }}
{{- else if $providedPasswordValue }}
  {{- $password = $providedPasswordValue | toString | b64enc | quote }}
{{- else }}
```
So if the secret exists and has the key then use it.
Else if the password is provided, use it.
Else auto-generate the password.

**Comment by juan131** [comment]
Hi @jim-barber-he 

This is expected since we introduced several breaking changes. Please check the upgrading notes that explain how to upgrade from `10.x` step by step:

- https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#upgrading-instructions

**Comment by jim-barber-he** [comment]
Ok fair enough.
If I fix this then other things along the way can't be upgraded, so it seems pointless.
Closing.

**Comment by jyono** [comment]
> Hi @jim-barber-he
> 
> This is expected since we introduced several breaking changes. Please check the upgrading notes that explain how to upgrade from `10.x` step by step:
> 
> * https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#upgrading-instructions

that page gives me a 404. do you have an updated link?

**Comment by carrodher** [comment]
> > Hi @jim-barber-he
> > This is expected since we introduced several breaking changes. Please check the upgrading notes that explain how to upgrade from `10.x` step by step:
> > 
> > * https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/#upgrading-instructions
> 
> that page gives me a 404. do you have an updated link?

All the documentation was moved to the READMEs, you can find that specific section at https://github.com/bitnami/charts/tree/main/bitnami/postgresql#upgrading
