### ISSUE TITLE
[bitnami/redis-cluster] node doesn't recover after being recreated 

### ISSUE THREAD

**Issue by alessandro-gandolfi-ors** [bitnami/charts#8908]
### Name and Version

bitnami/redis-cluster 7.2.1

### What steps will reproduce the bug?

1. install the chart
2. wait for all the nodes to be available
3. remove a pod
4. wait for the pod to be up again
5. the redis container in the pod will be up but won't find the cluster configuration, creating a new master with 0 replicas
6. readiness probe won't make the pod available with the error: **Readiness probe failed: cluster_state:fail /scripts/ping_readiness_local.sh: 13: [: 0: unexpected operator /scripts/ping_readiness_local.sh: 29: [: 0: unexpected operator**

### Are you using any custom parameters or values?

```
## @param usePassword Use password authentication
##
usePassword: false

## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## @param persistence.enabled Use a PVC to persist data.
  ##
  enabled: false

## Redis&trade; Cluster settings
##
cluster:
  ## @param cluster.init Enable the initialization of the Redis&trade; Cluster
  ##
  init: true
  ## Number of Redis&trade; nodes to be deployed
  ##
  ## Note:
  ## This is total number of nodes including the replicas. Meaning there will be 3 master and 3 replica
  ## nodes (as replica count is set to 1 by default, there will be 1 replica per master node).
  ## Hence, nodes = numberOfMasterNodes + numberOfMasterNodes * replicas
  ##
  ## @param cluster.nodes The number of master nodes should always be >= 3, otherwise cluster creation will fail
  ##
  nodes: 9
  ## @param cluster.replicas Number of replicas for every master in the cluster
  ## Parameter to be passed as --cluster-replicas to the redis-cli --cluster create
  ## 1 means that we want a replica for every master created
  ##
  replicas: 2
  ## Configuration to access the Redis&trade; Cluster from outside the Kubernetes cluster
  ##
  externalAccess:
    ## @param cluster.externalAccess.enabled Enable access to the Redis
    ##
    enabled: false

## Prometheus Exporter / Metrics
##
metrics:
  ## @param metrics.enabled Start a side-car prometheus exporter
  ##
  enabled: true
```

### What is the expected behavior?

after the pod has been removed and added again, it should start redis as replica of a master missing a replica.

### What do you see instead?

after the pod has been removed and added again, it can't reconnect to the rest of the cluster because it doesn't find the configuration ("No cluster configuration found" in the log), starting redis as master with 0 replicas.

**Comment by alemorcuq** [comment]
Thank you for reporting this. I have been able to reproduce the issue and I've created an internal task to address this issue. I can't give you an ETA but we will try to work on this as soon as possible. In the meantime, please feel free to contribute if you are able to identify the issue.

**Comment by waster** [comment]
The same thing after k8s node was shutting down on power and some redis pods was unable to run while trying to read broken AOF file from PVC. I tried to delete this pods with corresponding PVC but they created a new master with 0 replicas and stuck in Running state.

BTW, how to fix those issues when AOF file or file system on PVC become broken due any hardware issues on k8s node?

**Comment by kvendingoldo** [comment]
any news here? looks like that I have the same issue

**Comment by bunicb** [comment]
Had the same issue around a month ago in a test cluster.
Today the same thing happened in a different cluster, when a node went into a weird network state, and a redis pod restarted into this state.

Any news on this?

**Comment by nixancha** [comment]
Hi,

I am facing the issue here as well. After running the helm upgrade to map LoadBalancerIP, pods are up and running but cluster_state: fail is seen in cluster info.

![image](https://user-images.githubusercontent.com/103242759/174999298-8adc1112-c8a0-423b-8c1a-545ecdd16b2b.png)
Also the IP at this is trying to reach is not matching with external-ip of redis-cluster service. I am not sure why this is happening.
