### ISSUE TITLE
Uninstalling Rabbitmq and installating it again wont work

### ISSUE THREAD

**Issue by ArvindhVenkatraman** [bitnami/charts#8911]
### Name and Version

bitnami/rabbitmq:3.9.12

### What steps will reproduce the bug?

1. install rabbitmq through charts 
2. uninstall/delete helm release 
3. install again. During re-installation, the workloads wont come up unless i delete the pvc. 

### What do you see instead?

when i try to re-install, workloads should come up normally.

**Comment by javsalgar** [comment]
Hi,

This normally has to do with the existing credentials stored in the PVC. Did you check that you set the exact same credentials when reusing the PVC?

**Comment by ArvindhVenkatraman** [comment]
exact credentials but my issue was due to `rabbit_password_hashing_sha256` vs`"hashing_algorithm": "rabbit_password_hashing_md5". Happen to figure it out and fixed it.
