### ISSUE TITLE
[bitnami/ghost] `smtpExistingSecret` value is ignored

### ISSUE THREAD

**Issue by shosti** [bitnami/charts#8916]
### Name and Version

bitnami/ghost 16.0.7

### What steps will reproduce the bug?

```bash
$ helm template ghost bitnami/ghost --version 16.0.7 \
    --set ghostHost=ghost.local \
    --set smtpUser=bob \
    --set smtpExistingSecret=mysecret  | grep -a5 SMTP
```

### Are you using any custom parameters or values?

See the reproduction command.

### What is the expected behavior?

From the documentation, I expected `GHOST_SMTP_PASSWORD` to be set and pull its value from `smtpExistingSecret`.

### What do you see instead?

`GHOST_SMTP_PASSWORD` isn't set unless `smtpPassword` is set. 

### Additional information

I can workaround by setting `smtpPassword` to a junk value, in which case `GHOST_SMTP_PASSWORD` is actually pulled from `existingSecret` (*not* `smtpExistingSecret`):

```bash
$ helm template ghost bitnami/ghost --version 16.0.7 --set ghostHost=ghost.local --set smtpUser=bob --set smtpPassword="-" --set existingSecret=mysecret  | grep -a5 SMTP
              value: "80"
            - name: GHOST_EXTERNAL_HTTPS_PORT_NUMBER
              value: "443"
            - name: GHOST_SKIP_BOOTSTRAP
              value: "no"
            - name: GHOST_SMTP_USER
              value: "bob"
            - name: GHOST_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: smtp-password
```
But this isn't what the documentation would lead me to believe is correct behavior.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
