### ISSUE TITLE
Redis-cluster problem

### ISSUE THREAD

**Issue by oguzhansrky** [bitnami/charts#8917]
### Name and Version

bitnami/redis-cluster:7.2.1

### What steps will reproduce the bug?

I set `persistence` to `false`. I install the rest by default.

After this process, I give the "service" externalip address and enable it to be accessed from outside.

There was no problem until a month ago. I don't understand what happened after the last update. The other does not see the key written by one, and the system does not provide a connection as a cluster.

I'll fetch samples from the system I'm running before and post screenshots. This was working fine.

Whatever you updated????????????????????????????????????**

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/52497227/152662195-a15c894f-c392-43a2-84da-17cb65f02326.png)
![image](https://user-images.githubusercontent.com/52497227/152662206-c6a60fad-48c2-4d1e-ba42-cbe5b0df12e1.png)

### What do you see instead?

```
redis-redis-cluster:6379> set key a
(error) MOVED 12539 10.42.73.79:6379
redis-redis-cluster:6379> get key *
(error) ERR wrong number of arguments for 'get' command
redis-redis-cluster:6379> keys *
(empty array)
redis-redis-cluster:6379> set key a
(error) MOVED 12539 10.42.73.79:6379
redis-redis-cluster:6379> exit
I have no name!@redis-redis-cluster-client:/$ redis-cli -c -h redis-redis-cluster -a $REDIS_PASSWORD
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
redis-redis-cluster:6379> keys *
(empty array)
redis-redis-cluster:6379> set key a
-> Redirected to slot [12539] located at 10.42.73.79:6379
OK
10.42.73.79:6379> keys *
1) "key"
10.42.73.79:6379> 
```

### Additional information

I have never received "moved", "error", "redirected to slot" output on the systems I have installed before.

**Comment by oguzhansrky** [comment]
![redis-cluster](https://user-images.githubusercontent.com/52497227/152663814-90d9c9c0-1f7b-447d-b66c-0275302a2fbc.png)

As I said, I install it in the normal default way, I have installed it this way many times before. now it's giving an error on its head. I didn't need to enter the "-c" parameter beforehand. When compiling code, something like "-c" parameter is added to the software. why is it this way?

And when will this problem be fixed?

**Comment by oguzhansrky** [comment]
What happens when you use the "-c" parameter
![image](https://user-images.githubusercontent.com/52497227/152663924-43f96669-1bbe-4777-905c-c23df59d2e73.png)

**Comment by juan131** [comment]
Hi @oguzhansrky 

The problems started with the chart version `7.2.1`, right? Could you please let us know the chart version you were using before? It's important for us to understand what changes were introduced between these versions so we can point you to the right instructions. Thanks in advance.

**Comment by oguzhansrky** [comment]
Hi,

I found a helm yaml file that I installed 2 months ago. I did the test on the system I installed and the system was working very well there.

I installed the same yaml file in the new environment and faced the same problem again...

How can I see the changes made in the software or packages in the last 2 months?

YAML

cluster:
  externalAccess:
    enabled: false
    service:
      annotations: {}
      loadBalancerIP: []
      port: 6379
      type: ClusterIP
  init: true
  nodes: 6
  replicas: 1
  update:
    addNodes: false
    currentNumberOfNodes: 6
    newExternalIPs: []
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
diagnosticMode:
  args:
    - infinity
  command:
    - sleep
  enabled: false
existingSecret: ''
existingSecretPasswordKey: ''
extraDeploy: []
fullnameOverride: redis-test
global:
  imagePullSecrets: []
  imageRegistry: ''
  redis:
    password: ''
  storageClass: longhorn
image:
  debug: false
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/redis-cluster
  tag: 6.2.6-debian-10-r49
maxUnavailable: ''
metrics:
  enabled: false
  extraArgs: {}
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.31.4-debian-10-r7
  podAnnotations:
    prometheus.io/port: '9121'
    prometheus.io/scrape: 'true'
  podLabels: {}
  priorityClassName: ''
  prometheusRule:
    additionalLabels: {}
    enabled: false
    namespace: ''
    rules: []
  resources: {}
  service:
    annotations: {}
    labels: {}
    loadBalancerIP: ''
    type: ClusterIP
  serviceMonitor:
    annotations: {}
    enabled: false
    interval: ''
    jobLabel: ''
    labels: {}
    metricRelabelings: []
    namespace: ''
    relabelings: []
    scrapeTimeout: ''
    selector: {}
minAvailable: ''
nameOverride: ''
networkPolicy:
  allowExternal: true
  enabled: false
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
password: ''
persistence:
  accessModes:
    - ReadWriteOnce
  annotations: {}
  enabled: true
  matchExpressions: {}
  matchLabels: {}
  path: /bitnami/redis/data
  size: 20Gi
  storageClass: ''
  subPath: ''
podDisruptionBudget: {}
podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  sysctls: []
podSecurityPolicy:
  create: false
rbac:
  create: false
  role:
    rules: []
redis:
  affinity: {}
  args: []
  command: []
  configmap: ''
  containerPorts:
    bus: 16379
    redis: 6379
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: ''
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podManagementPolicy: Parallel
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  shareProcessNamespace: false
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 6
    initialDelaySeconds: 300
    path: /
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  useAOFPersistence: 'yes'
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  labels: {}
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    redis: ''
  ports:
    redis: 6379
  type: ClusterIP
serviceAccount:
  annotations: {}
  automountServiceAccountToken: false
  create: false
  name: ''
sysctlImage:
  command: []
  enabled: false
  mountHostSys: false
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: bitnami/bitnami-shell
  resources:
    limits: {}
    requests: {}
  tag: 10-debian-10-r261
tls:
  authClients: true
  autoGenerated: false
  certCAFilename: ''
  certFilename: ''
  certKeyFilename: ''
  certificatesSecret: ''
  dhParamsFilename: ''
  enabled: false
  existingSecret: ''
updateJob:
  activeDeadlineSeconds: 600
  affinity: {}
  annotations: {}
  args: []
  command: []
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  initContainers: []
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: ''
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  priorityClassName: ''
  resources:
    limits: {}
    requests: {}
  tolerations: []
usePassword: false
usePasswordFile: false
volumePermissions:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10-r261
  resources:
    limits: {}
    requests: {}

**Comment by juan131** [comment]
Hi @oguzhansrky 

> How can I see the changes made in the software or packages in the last 2 months?

The `helm history` can help you with this, see:

- https://helm.sh/docs/helm/helm_history/

**Comment by oguzhansrky** [comment]
not working now. when will it be fixed?

**Comment by alongfield** [comment]
@juan131 Having this same issue as OP.  If you set `cluster.externalAccess.enabled = true` on 7.2.1, the template for svc-cluster-external-access fails:

`helm template testing bitnami/redis-cluster --version 7.2.1 --set cluster.externalAccess.enabled=true`

You get:

`Error: template: redis-cluster/templates/svc-cluster-external-access.yaml:15:24: executing "redis-cluster/templates/svc-cluster-external-access.yaml" at <.Release.Namespace>: can't evaluate field Release in type int`

This works fine on chart version 7.2.0.

`helm template testing bitnami/redis-cluster --version 7.2.0 --set cluster.externalAccess.enabled=true`

The addition of the namespace metadata line blows up in that one Service template file, but I wasn't able to get it to break in a few of the other services changed as part of https://github.com/bitnami/charts/pull/8821.  The other service templates don't have that range logic, either.

**Comment by migruiz4** [comment]
Hi @alongfield,

I have submitted this PR that fixes the issue with externalAccess that was introduced in #8821 as you reported.

@oguzhansrky, what my colleague @juan131 is trying to say is, that it would be helpful if you could share what version are you upgrading from, so we can try to reproduce the error by upgrading from that version to the latest `7.2.1 ` as you did.

**Comment by oguzhansrky** [comment]
Hello, I guess I didn't get the point across.

As I used before, when normal installation is done, only 1 'cluster ip' appears in the 'k8s services' section. This was working when I manually changed it to 'load balancer'. It no longer WORKS at all. I keep getting 'MOVED' ERROR.

If we still can't agree, I will shoot a video and leave a link.

I will take a video and share it in the working version.

The version I installed previously works, but now when I install the same version, it does not work.

Currently this helm chart 'redis-cluster' is NOT WORKING.

You are providing a service. Thank you very much, but Please do your tests well.

**Comment by oguzhansrky** [comment]
<img width="978" alt="Screenshot 2022-02-23 at 13 48 42" src="https://user-images.githubusercontent.com/52497227/155304887-de33efbe-ba3a-41b6-aae2-43b983fad3a3.png">

**Comment by oguzhansrky** [comment]
Whatever development you've done, bring the '7.0.13' version back to when it was first released or test this version as it was when you first released it. You will see for yourself that the system is working. You will understand where the problem is.

**Comment by oguzhansrky** [comment]
external access is available, but will I buy 9 separate ip addresses for 9 pods?

**Comment by migruiz4** [comment]
Hi @oguzhansrky,

I'm sorry for the late response. When trying to access Redis Cluster from outside the Kubernetes cluster, it is necessary to set the value `cluster.externalAccess.enabled=true`.

This is because of how Redis Cluster works, it will try to redirect you to the node where the requested data is stored using the IP of the node. If that IP is not reachable externally, then it will fail to connect.

> external access is available, but will I buy 9 separate ip addresses for 9 pods?

If your goal is to access Redis Cluster externally, individual IPs need to be used with the option `cluster.externalAccess.enabled=true`.

This behavior is not different in version `7.0.13` of the `bitnami/redis-cluster` chart, in case you would like to share more details about your deployment before and after.
