### ISSUE TITLE
[bitnami/harbor] login fail with the showed password returns 401

### ISSUE THREAD

**Issue by justpretty** [bitnami/charts#8919]
### Name and Version

bitnami/harbor 11.2.2

### What steps will reproduce the bug?

1. I have changed nothing but service.existingSecret and externalURL to  fit for my desired domain.
2. i then just run:`  helm install harbor -n harbor .`
3. it turns out a long loadbalancer domain
4.  i change my desired domain's dns to the loadbalancer domain
5. i open my desired domain, and it works
6. i use bellow to show the password:
` echo Password: $(kubectl get secret --namespace harbor harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)`
7. i cannot login with admin and the showed password
8. i reinstall and the result is the same

### Are you using any custom parameters or values?

service.existingSecret: "tls-harbor"
externalURL: https://XX.XX.XX.com

### What is the expected behavior?

login success

### What do you see instead?

user or password incorrect

http xhr return 401 status

**Comment by carrodher** [comment]
Please note passwords are stored in PVC which are not being removed when running `helm delete`. In the same way, if you are running `helm upgrade` at some point, note the password stored in the PVC is not going to change, but the application is going to generate a new random password, causing a conflict.

Can you try to deploy it from scratch in a new namespace or use a different name not used in a previous attempt?

**Comment by justpretty** [comment]
> Please note passwords are stored in PVC which are not being removed when running `helm delete`. In the same way, if you are running `helm upgrade` at some point, note the password stored in the PVC is not going to change, but the application is going to generate a new random password, causing a conflict.
> 
> Can you try to deploy it from scratch in a new namespace or use a different name not used in a previous attempt?

new namespace works, thanks,but if it will be better that  the pvc password can be synced
