### ISSUE TITLE
[bitnami/harbor] Allow to configure ingress annotations separately for each ingress resource

### ISSUE THREAD

**Issue by jowko** [bitnami/charts#8922]
### Name and Version

bitnami/harbor 11.2.2

### What is the problem this feature will solve?

We have two ingress controllers in our cluster and one of them is available publicly and second is available only in our private company network.
Harbor Helm Chart exposes two ingress resources: notary and harbor. We would like to expose harbor in one ingress controller and notary in second. Our cloud provider requires as to configure ingress controller using ingress class annotation.

### What is the feature you are proposing to solve the problem?

We have a `ingress.annotations` property in values.yaml file which can be used to add custom annotations to both ingress resources. So we can put these resources only under one ingress controller.
We could create a additional parameters: `ingress.core.annotations` and `ingress.notary.annotations` to allow custom annotations for each ingress resource. Then we can use different ingress class for each ingress resource. It also allows anyone to apply any other custom configuration to each ingress resource separately.

### What alternatives have you considered?

We could disable ingress in Harbor Helm chart and redefine all ingress resources using `extraDeploy` parameter. But this will be hard to maintain since we need to track any changes in ingress resources and migrate them to our custom objects.

**Comment by fmulero** [comment]
Hi @jowko thanks a lot for sharing this improvement. I've been having a look to the harbor ingress configuration and I think using the `extraDeploy` parameter is the unique workaround for your scenario. In addition to your suggestions, I'd add at least another field, the [ingressClassName](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation), I think it will help you to use one ingress controller or another

I will open a task for the engineering team to evaluate this. As it is not a critical feature, we cannot guarantee an ETA. However, as soon as we have more news, we will update this ticket.

Please don't hesitate to share any PR! 😉

**Comment by carrodher** [comment]
Thanks for the suggestion! After checking with the Engineering team there are no plans to work on this feature in the short term, although we would be happy to review any PR and provide feedback

**Comment by jowko** [comment]
The issue is still valid.
