### ISSUE TITLE
[bitnami/keycloak:16.1.1] Can't change podManagementPolicy in Keycloak deploy

### ISSUE THREAD

**Issue by RafaelTCostella** [bitnami/charts#8924]
### Name and Version

bitnami/keycloak:16.1.1

### What is the problem this feature will solve?

Currently we cannot deploy a custom keycloak image (e.g: with overrides in services) and sustain availability in our API.

The main problem is [here](https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/statefulset.yaml#L17), since `podManagementPolicy` is configured as `Parallel` without a possible overwrite in Values to whatever the final user wants - in my example I would like to use OrderedReady config.

### What is the feature you are proposing to solve the problem?

I would like to allow this option to be something like `podManagementPolicy: {{ .Values.podManagementPolicy }}` and add some documentation to explain this option with a default value as Parallel.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look

**Comment by RafaelTCostella** [comment]
Solved @javsalgar thanks!
