### ISSUE TITLE
[bitnami/postgres] values.yaml file not being applied

### ISSUE THREAD

**Issue by danielsiwiec** [bitnami/charts#8927]
### Name and Version

bitnami/postgres 11.0.2

### What steps will reproduce the bug?

1. Create a new namespace: `kubectl create namespace pg-test`
2. Create the values.yaml file
```
cat > values.yaml << EOF
heredoc> postgresqlPassword: pg
heredoc> EOF
```
3. Install helm chart `helm install my-release bitnami/postgresql -n pg-test -f values.yaml`
4. Read password secret
```
> kubectl get secret --namespace pg-test my-release-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode
y6v1Ux6HEc
```
5. Attempt to connect to the database using the password from values.yaml
```
> kubectl run my-release-postgresql-client --rm --tty -i --restart='Never' --namespace pg-test --image docker.io/bitnami/postgresql:14.1.0-debian-10-r80 --env="PGPASSWORD=pg" \
      --command -- psql --host my-release-postgresql -U postgres -d postgres -p 5432

psql: error: connection to server at "my-release-postgresql" (10.101.204.122), port 5432 failed: FATAL:  password authentication failed for user "postgres"
pod "my-release-postgresql-client" deleted
pod pg-test/my-release-postgresql-client terminated (Error)
```

### Are you using any custom parameters or values?

Yes. I'm passing a password. The contents of the values.yaml are:
```
postgresqlPassword: pg
```

### What is the expected behavior?

The password from the values.yaml should be applied

### What do you see instead?

Instead, a randomly generated password is used

**Comment by juan131** [comment]
Hi @danielsiwiec 

You're using a parameter (`postgresqlPassword`) that's not supported anymore in the chart version `11.x.x`. Please refer to the Upgrading Notes to get more information about the parameters that were deprecated:

- https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/

**Comment by danielsiwiec** [comment]
Thank you @juan131 . I must have been looking at an old version's docs. Thanks!
