### ISSUE TITLE
Inconsistent Service name with nameOverride in postgresql (and maybe common)

### ISSUE THREAD

**Issue by xMAC94x** [bitnami/charts#8931]
### Name and Version

bitnami/postgresql 10.13.4

### What steps will reproduce the bug?

1. any kubernetes 1.21 cluster with helm 3 execute:
2. run
```
helm install foo bitnami/postgresql --version=10.13.4  --set-string nameOverride=a  
helm install bar bitnami/postgresql --version=10.13.4  --set-string nameOverride=a
```

### Are you using any custom parameters or values?

--set-string nameOverride=a

### What is the expected behavior?

3. kubectl get services   
```
foo-a
bar-a
```

both service names should be consistent.

### What do you see instead?

3. kubectl get services   
```
foo-a
bar
```

Why has foo an additional -a behind but bar doesn't ?
Note: On my system i used the names `nextcloud-postgres`and `gitlab-postgres`.

### Additional information

The answer is probably, because `bar`already has a `a` in their name.
I want the names to be as short as possible on my system, thats why i included nameOverride="a" but seeing a different behavior here makes it complicated.

I would guess the feature is to detect a
`helm install foo-postgres bitnami/postgresql --version=10.13.4  --set-string nameOverride=foo`
and dont have a second name here, in that case it prob makes sense. but maybe we should search for nameOverride being enclosed in `-a-`or `-a`or `a-` ? 

I guess that comes from this code in common: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_names.tpl#L46

**Comment by miguelaeh** [comment]
Hi @xMAC94x ,
Good catch.
This feature was designed keeping in mind that a real name would be used. Checking the code, using just a single letter as you suggested is detected as if the name already contains the `nameOverride`, so it is not added.

I would like to understand better your use case so we can re-design this behavior or assume what you exposed can happen in these situations.

**Comment by xMAC94x** [comment]
> Hi @xMAC94x , Good catch. This feature was designed keeping in mind that a real name would be used. Checking the code, using just a single letter as you suggested is detected as if the name already contains the `nameOverride`, so it is not added.
> 
> I would like to understand better your use case so we can re-design this behavior or assume what you exposed can happen in these situations.

My usecase is just trying to get names as short as possible.
I have a Fleet chart for 2 helm charts, nextcloud and gitlab. both require a postgresql.
So by default the database pod is called `gitlab-postgresql-postgresql-0` and i didn't like the double postgresql.

My initital solution was to name the Helm Release `postgresql` and the overWritename "gitlab".
Which resulted in `postgresql-gitlab-0` which i found easier to read.
Though i found out i cant have 2 helm releases with the same release name. So this doesnt work.

Then i named the helm Release `gitlab-postgresql` and the overwrite name 'a' to be very very short. I could not name the release name `gitlab' as it was already taken by Gitlab helm chart itself.

Now i just resigned. I am using the release names `gitlab-postgresql` and `nextcloud-postgresql` and don't use any overwriteName at all. Its not pretty, but i didn't bothered enough.

Anyway, in order to reduce confusion we might want to switch that if to only detect when the name is exactly the same e.g.
`gitlab` and `gitlab` or the name is included with at least one `-` e.g. `gitlab-postgres` and `gitlab`.

**Comment by miguelaeh** [comment]
Hi @xMAC94x ,
Yes, that logic could be improved a bit. Would you like to create a PR?

**Comment by xMAC94x** [comment]
Hi @miguelaeh , unfortunately i dont see myself having enough knowledge in the go yaml templating to work in the common chart, as messing up there could render many charts incorrect :/

**Comment by miguelaeh** [comment]
Thank for for the report @xMAC94x ,
then we would try to fix it once we have the time for that.
