### ISSUE TITLE
[bitnami/rabbitmq] OpenShift: volume-permissions ignore .Values.volumePermissions.securityContext.runAsUser="auto"

### ISSUE THREAD

**Issue by link-webcreations** [bitnami/charts#8932]
### Name and Version

bitnami/rabbitmq 8.28.1

### What steps will reproduce the bug?

OpenShift which has scc with dynamic userids (and 0 is not allowed). We should be able to use another User for volume-permissions container.
We are not abot today to tif those rules because of the following line:

https://github.com/bitnami/charts/blob/6fd94c4b52c442a1e792a5d11a753135c5199d4e/bitnami/rabbitmq/templates/statefulset.yaml#L88

Here my values, but I'm unable to run inside OpenShift Container

### Are you using any custom parameters or values?

```yaml
podSecurityContext:
  enabled: false
containerSecurityContext: null
volumePermissions:
  enabled: true
  securityContext:
    runAsUser: "auto"
```

### What is the expected behavior?

Working on OpenShift

### What do you see instead?

The container are not starting:
```
create Pod fleet-executer-dev-rabbitmq-0 in StatefulSet fleet-executer-dev-rabbitmq failed error: pods "fleet-executer-dev-rabbitmq-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000740000, 1000749999], provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```
### Additional information

I'm able to run MongoDB from bitnami in OpenShift, thanks to the following code:

https://github.com/bitnami/charts/blob/6fd94c4b52c442a1e792a5d11a753135c5199d4e/bitnami/mongodb/templates/standalone/dep-sts.yaml#L113

Is something that ca be fixed please ?
Thanks a lot

**Comment by carrodher** [comment]
As you rightly point, the `securityContext` in the MongoDB Helm chart is customizable but it is not the case with the RabbitMQ one. Would you like to contribute by creating a PR adding this option to the RabbitMQ Helm chart as in MongoDB? The Bitnami team will be happy to review the PR and provide feedback

**Comment by ZKruse** [comment]
Can this be reopened? I'm just running into this issue now trying to run the bitnami helm rabbitmq chart in Openshift. Since I want `persistence.enabled: true` , [that necessitates setting](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/#adjust-permissions-of-the-persistence-volume-mountpoint) `volumePermissions.enabled: true` (otherwise it doesn't remount properly) and thus, the posted error.

**Comment by carrodher** [comment]
Sure, I just reopened the issue. In order to fix it, would you like to contribute by creating a PR adding this option to the RabbitMQ Helm chart as in MongoDB (or others)? The Bitnami team will be happy to review the PR and provide feedback
