### ISSUE TITLE
certManager property in magento chart for the ingress is not deprecated

### ISSUE THREAD

**Issue by edovale** [bitnami/charts#8943]
### Name and Version

bitnami/magento

### What steps will reproduce the bug?

In the sample [values](https://github.com/bitnami/charts/blob/master/bitnami/magento/values.yaml) a comment indicates that using cert-manager annotations is the way to determine whether a cert manager is being used or not. However, this is not true when looking at [tls-secrets.yaml template](https://github.com/bitnami/charts/blob/master/bitnami/magento/templates/tls-secrets.yaml)

### What do you see instead?

After hours of back and forth trying to resolve why my cert was self signed, I realized about this problem where the chart was generating a self signed certificate.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/magento#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
