### ISSUE TITLE
Failover Master not able to rejoin the cluster

### ISSUE THREAD

**Issue by sharique-masood** [bitnami/charts#8952]
### Name and Version

bitnami/redis-cluster 7.2.1
appVersion: 6.2.6

### What steps will reproduce the bug?

I have created a redis cluser of 6 nodes (running on k8) with persistent disabled. When I do manual failover means manually deleting one of the master pod , the slave connected to that master will do failover and become master.
Master Node: 3
Replica Node: 3

When the master comes online (which is slave now), is not able to join the cluster.

```
Could not connect to Redis at IP:6379: Operation timed out
**IP:6379 (687e78b3...) -> 0 keys | 5461 slots | 0 slaves.**
IP:6379 (f24b8a97...) -> 0 keys | 5461 slots | 1 slaves.
IP:6379 (24661d0f...) -> 0 keys | 5462 slots | 1 slaves.

[OK] 0 keys in 3 masters.
0.00 keys per slot on average.
>>> Performing Cluster Check (using node 172.19.36.160:6379)
M: f24b8a970f6a1fae62e949074dfd9477dbac8107 172.19.36.160:6379
  slots:[0-5460] (5461 slots) master
  1 additional replica(s)
M: 24661d0f021bdab8641c5dc3fb83dee8b9f72897 10.75.28.10:6379
  slots:[5461-10922] (5462 slots) master
  1 additional replica(s)
M: 687e78b370c9ca332cfda842569425d326956d05 10.75.27.10:6379
  slots:[10923-16383] (5461 slots) master
S: 97ec5ebb8dd0f0c4e3f99204dda47b638c60e583 10.75.17.10:6379
  slots: (0 slots) slave
  replicates f24b8a970f6a1fae62e949074dfd9477dbac8107
S: fed8d893c1eadbd6228faaf0dabf36d1ef318205 10.75.14.17:6379
  slots: (0 slots) slave
  replicates 24661d0f021bdab8641c5dc3fb83dee8b9f72897
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
```

Now:
Master Node: 2
Replica Node: 3

### Are you using any custom parameters or values?

Persistence disabled

### What is the expected behavior?

The deleted master should rejoin to the cluster as a slave.

### What do you see instead?

The failover happen and slave become master but the master not able to join the cluster due to Readiness probe failed: cluster_state:fail.

```
Warning  Unhealthy  3m53s (x720 over 63m)  kubelet  Readiness probe failed: cluster_state:fail
```

### Additional information

is this expected behaviour for persistent disabled Redis cluster ?

**Comment by rafariossaa** [comment]
Hi,
  Could you share the commands you used ? I would like to follow the same steps you did.

**Comment by rajyadav911** [comment]
@rafariossaa We are passing values from values.yaml . Since we have persistence disabled so via values.yaml we have done 
persistence:
  ## @param persistence.enabled Use a PVC to persist data.
  ##
  enabled: false 

To install redis we are using command 
helm install --timeout 600s redis bitnami/redis-cluster  --values values.yaml

**Comment by rafariossaa** [comment]
Hi,
  I was able to reproduce the issue. Currently, the thing is that persistence is needed as the IPs are stored so a node can check and clean the IP list.
   I am creating an internal task to study this issue and how to solve it. We will come back as soon as we have news.

**Comment by rajyadav911** [comment]
Thanks @rafariossaa

**Comment by javsalgar** [comment]
Just a note to let you know that now persistence is mandatory. After analysis, that's the best option we devised.
