### ISSUE TITLE
[bitnami/jupyterhub] The default configuration in values.yaml does not allow to use the "singleuser.podLabels"

### ISSUE THREAD

**Issue by jmueller42** [bitnami/charts#8954]
### Name and Version

bitnami/jupyterhub 0.4.1

### What steps will reproduce the bug?

Just set singleuser.podLabels to some labels.

e.g.:
singleuser:
  podLabels:
    a: b
    c: d

### What is the expected behavior?

When i use `singleuser.podLabels` i expect the configuration to render the given labels into the single user pod template

### What do you see instead?

the output ist `commonLabels`

### Additional information

I think this is a small copy & paste mistake, if you compare line 199 with 202.

So in order to fix this just change  [line 202](https://github.com/bitnami/charts/blob/df52d4003e8650ac69e6bedeafe25198a5f27821/bitnami/jupyterhub/values.yaml#L202)
from
```
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
```
to
```
        {{- include "common.tplvalues.render" ( dict "value" .Values.singleuser.podLabels"context" $ ) | nindent 4 }}
```

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR! The team will take a look
