### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Add SCDF common application properties configuration

### ISSUE THREAD

**Issue by CEDDM** [bitnami/charts#8955]
### Name and Version

 [bitnami/spring-cloud-dataflow] 5.1.0

### What is the problem this feature will solve?

Today it is not possible to configure SCDF [common application properties](https://docs.spring.io/spring-cloud-dataflow/docs/2.9.1/reference/htmlsingle/#spring-cloud-dataflow-global-properties) with the chart

### What is the feature you are proposing to solve the problem?

Add SCDF common application properties configuration with the chart

**Comment by CEDDM** [comment]
I will try to submit a PR ASAP

**Comment by juan131** [comment]
Thanks @CEDDM, we really appreciate it !! We'll be looking forward for your PR!
