### ISSUE TITLE
Updating mariadb-galera  from 5.x.x to 6.x.x or 7.x.x fails, because statefulset name changes

### ISSUE THREAD

**Issue by mikk150** [bitnami/charts#8957]
### Name and Version

bitnami/mariadb-galera:6.0.0

### What steps will reproduce the bug?

1. Use `bitnami/mariadb-galera:5.x.x` in a chart dependency with alias
2. update to `bitnami/mariadb-galera:6.x.x`
3. observe how since it creates new statefulset with new name, it kills all pods and starts new ones, but now all PVC names are also different

### What is the expected behavior?

I do kind of expect it to fail, but it would be nice to have some kind of update steps to fix it

### What do you see instead?

it creates new PVC s and now my precious data is gone

**Comment by Revellski** [comment]
I believe this is exactly what we're discussing in https://github.com/bitnami/charts/issues/8941. Feel free to try the steps in the last comment, it didn't work for me but your mileage may differ.

**Comment by mikk150** [comment]
> I believe this is exactly what we're discussing in #8941. Feel free to try the steps in the last comment, it didn't work for me but your mileage may differ.

No - as I did try that solution, and it did not work there, as there issue was not that `statefulset` name changes. My issue is that statefulset name changes

**Comment by javsalgar** [comment]
Hi,

Because of this STS changes, the versions are marked as major. In this sense, our recommendation is to backup the data, spin up a new cluster of the latest chart version, and proceed with the migration data.
