### ISSUE TITLE
updateStrategy.type doesn't work when values.yaml is set to Recreate

### ISSUE THREAD

**Issue by webdz9r** [bitnami/charts#8961]
### Name and Version

Helm chart bitnami/wordpress 13.0.9

### What steps will reproduce the bug?

Building with helm template and passing values.yaml 

```replicaCount: 1
updateStrategy:
  type: Recreate
```

 it generates this in the deployment
```
strategy:
    rollingUpdate: {}
    type: Recreate
```

and produces this error: `is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'`

but should generate this: 
```
strategy:
    type: Recreate
```

### Are you using any custom parameters or values?

```
replicaCount: 1
updateStrategy:
  type: Recreate
```
  

### What is the expected behavior?

Should generate this in the deployment manifest

but should generate this: 
```
strategy:
    type: Recreate
```

### What do you see instead?

```
strategy:
    rollingUpdate: {}
    type: Recreate
```

### Additional information

Nope pretty straightforward

**Comment by webdz9r** [comment]
seems it's just adding rollingUpdate regardless of the type used in updateStrategy.type used

**Comment by alemorcuq** [comment]
To [remove a default key in Helm](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key) you need to set it to `null`.

So, setting it like this should work:

```
replicaCount: 1
updateStrategy:
  type: Recreate
  rollingUpdate: null
```
