### ISSUE TITLE
Add Support for serviceAccount.labels

### ISSUE THREAD

**Issue by pinkfloydx33** [bitnami/charts#8967]
### Name and Version

bitnami/external-dns

### What is the problem this feature will solve?

There is currently no way to specify that a generated `ServiceAccount` should have custom `labels` added to it. 

This is a problem for me as the successor to Azure Pod-Identity, [Azure AD Workload Identity](https://github.com/Azure/azure-workload-identity), no longer uses labels added to the _pods_ in order to associate an Azure Identity with containers. Instead, it uses a [combination of labels and annotations](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#service-account) on the `ServiceAccount`. 

The `external-dns` chart does currently support `serviceAccount.annotations`, however **both** labels and annotations are required for the new system.

### What is the feature you are proposing to solve the problem?

Add `serviceAccount.labels` to the `external-dns` chart.

Note that I am not familiar with the other charts hosted in this repository, however the need for both labels and annotations for the `ServiceAccount` will be a requirement for anyone wishing to switch their pod-identity setup. My point is that the feature is likely needed in charts other than this one.

### What alternatives have you considered?

I *could* manage the `ServiceAccount` myself; however that makes things a bit cumbersome. I'd have to manage things partially via the chart and partially manually which would be a bit messy.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! I think that `serviceAccount.labels` is something we have in other charts. Would you like to submit a PR with the feature? If not we will work on it.

**Comment by pinkfloydx33** [comment]
@javsalgar this issue was closed by the bot, but is still very much needed.

That said, there are likely other changes required once `external-dns` adds support for Azure Workload Identity directly in the product itself. [See here](https://github.com/kubernetes-sigs/external-dns/issues/2724) for their open issue which looks to add at least one new flag/option that would need to be handled by this chart. 

Should I open another issue or can this be reopened?

**Comment by javsalgar** [comment]
Hi,

I reopened this issue, I will let the team know about adding this feature.
