### ISSUE TITLE
Where is mysql version 5.7.21 image?

### ISSUE THREAD

**Issue by inix** [bitnami/charts#897]
I examined mysql version in bitnami/mysql [docker image repo](https://github.com/bitnami/bitnami-docker-mysql),there is no mysql version 5.7.21,this version have deployed in our production environment,but version 5.7.21 do not reside in bitnami's repo.

How can I use 5.7.21 version image or can I just replace docker hub official mysql image in values.yaml?

**Comment by juan131** [comment]
Hi @inix 

The **5.7.21** points to the latest revision of that version. If you clone the repo and run the command below:

```
$ git tag -l | grep 5.7.21
5.7.21-r0
5.7.21-r1
5.7.21-r10
5.7.21-r11
5.7.21-r12
5.7.21-r13
5.7.21-r2
5.7.21-r3
5.7.21-r4
5.7.21-r5
5.7.21-r6
5.7.21-r7
5.7.21-r8
5.7.21-r9
```

You'll find that latest image revision is **r13**. Every time we do a release, we publish this images on DockerHub.

**Comment by beltran-rubo** [comment]
Hi,

See how we use rolling tags & immutable tags for Bitnami containers at our docs https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/ 

I hope it helps.

**Comment by inix** [comment]
@juan131 @beltran-rubo 
Ok,Thanks.
This helps me a lot!

**Comment by inix** [comment]
@juan131 
Hi,helm search mysql repo do not have 5.7.21 mysql app version.
I want to build mysql version 5.7.21 with latest debian 9 docker file manually ,but I have no idea to find package name of corresponding docker file from Bitnami website.
I can download mysql 5.7.21 file:
https://downloads.bitnami.com/files/stacksmith/mysql-5.7.21-9-linux-x64-debian-8.tar.gz

Which mysql 5.7.21 file that I can build with debian 9 docker file?

**Comment by juan131** [comment]
Hi @inix 

I found you opened this [issue](https://github.com/bitnami/bitnami-docker-mysql/issues/58) on MySQL repository. Let's continue the discussion there.
