### ISSUE TITLE
Changes to Contour chart for new namespaced-Role (next Contour release)

### ISSUE THREAD

**Issue by sunjayBhatia** [bitnami/charts#8975]
### Name and Version

contour/next release

### What is the problem this feature will solve?

The next release of Contour will switch from using a ClusterRole to a namespace-scoped Role to configure RBAC for leader election resources (Leases and Events). This is a small security change to limit Contour's access footprint in a cluster.

As this change adds a new resource (a new Role) to Contour's base deployment configuration, some steps will need to be taken in the Contour chart to accommodate this.

See https://github.com/projectcontour/contour/pull/4204

### What is the feature you are proposing to solve the problem?

- Ensure the correct namespace is set on the new Role resource
- etc.

### What alternatives have you considered?

N/A

**Comment by juan131** [comment]
Hi @sunjayBhatia 

Thank you so much for warning us in advance, we really appreciate it! Could you please let us know the specific version of Contour that will include these changes?

**Comment by sunjayBhatia** [comment]
The new version should be v1.21.0

**Comment by juan131** [comment]
Thank you @sunjayBhatia !
