### ISSUE TITLE
minio helm chart: Invalid command usage, flag provided but not defined

### ISSUE THREAD

**Issue by betoksoft** [bitnami/charts#8977]
### Name and Version

bitnami/minio 10.1.6

### What steps will reproduce the bug?

When using provisioning section of the chart and i try to set a bucket's quota as following:
```
        quota:
          type: fifo
          size: 14Gi
```
The provisioning pod shows the following error:
mc: <ERROR> Invalid command usage, flag provided but not defined: -fifo

### What is the expected behavior?

Start Minio provisioning
Added `provisioning` successfully.
Bucket created successfully `provisioning/xxx`.
Lifecycle configuration imported successfully to `provisioning/xxx`.

### What do you see instead?

Start Minio provisioning
Added `provisioning` successfully.
Bucket created successfully `provisioning/xxx`.
Lifecycle configuration imported successfully to `provisioning/xxx`.
mc: <ERROR> Invalid command usage, flag provided but not defined: -fifo

**Comment by juan131** [comment]
Hi @betoksoft 

Thanks so much for reporting this issue. Could you please share the complete **values.yaml** you're using so I can reproduce the issue on my side?

**Comment by betoksoft** [comment]
This is the configuration i have in my values.yaml:

`minio:
  mode: distributed
  auth:
    rootUser: "MinioRoot"
    rootPassword: "somepassword123*"
  persistence:
    size: 15Gi
  provisioning:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    buckets:
      - name: xxx
        region: aws
        versioning: false
        withLock: false
        lifecycle:
          - id: TestPrefix7dRetention
            disabled: false
            expiry:
              days: 1
        quota:
          type: fifo
          size: 14Gi
    config:
      - name: region
        options:
          name: minio`

Thank you in advance

**Comment by juan131** [comment]
Hi @betoksoft 

The error is coming from the line below:

- https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/provisioning-job.yaml#L106

As you can see it's executing the command `mc admin bucket quota provisioning/xxx --fifo 14Gi;` but `mc` doesn't accept `--fifo` as a valid flag, see:

- https://docs.min.io/docs/minio-admin-complete-guide.html#bucket

**Comment by betoksoft** [comment]
Thank you for your help!
