### ISSUE TITLE
ping_liveness_local.sh broken on redis-cluster chart

### ISSUE THREAD

**Issue by codervinod** [bitnami/charts#8978]
### Name and Version

bitnami/redis-cluster

### What steps will reproduce the bug?

Please check this file and line, its missing "#!/bin/bash"
https://github.com/bitnami/charts/blob/f92cfe08eebc7dad56062db7f6dc7474b48293c5/bitnami/redis-cluster/templates/scripts-configmap.yaml#L78 

This causes the liveness check to fail as the first parameter is not consumed. Look at https://github.com/bitnami/charts/blob/72691ea3f97610961a822567c291b6f05bd58b0c/bitnami/redis/templates/health-configmap.yaml

Please fix this typo.

### What do you see instead?

I have no name!@redis-cluster-release-0:/scripts$ sh -c /scripts/ping_liveness_local.sh 12 23
timeout: invalid time interval 'redis-cli'
Try 'timeout --help' for more information.
/scripts/ping_liveness_local.sh: 13: [: 125: unexpected operator

**Comment by juan131** [comment]
You're completely right @codervinod ! The script is missing the shebang, thanks for reporting it!!

Would you like to contribute with a PR to fix it?

**Comment by codervinod** [comment]
Yes I can send a fix shortly @juan131

**Comment by juan131** [comment]
thanks @codervinod ! I just accepted and merged your PR
