### ISSUE TITLE
MEAN with OSBA Mongodb instructions need to be updated

### ISSUE THREAD

**Issue by arapulido** [bitnami/charts#898]
For the MEAN stack chart, in the instructions on how to deploy with a CosmosDB (mongodb api) instance using the service broker, this line should be updated from

`$ helm install --name node-app --set mongodb.install=false,externaldb.broker.serviceInstanceName=azure-mongodb-instance bitnami/mean`

to 

`$ helm install --name node-app --set mongodb.install=false,externaldb.broker.serviceInstanceName=azure-mongodb-instance,externaldb.ssl=true bitnami/mean`

**Comment by carrodher** [comment]
I think we have the same issue for the Node stack chart, just in case, can you confirm it @arapulido?

I just created two separate PRs fixing both charts

**Comment by tompizmor** [comment]
Yes, the same for the Node chart
