### ISSUE TITLE
[bitnami/WordPress] Allow for functions.php to be customized through helm

### ISSUE THREAD

**Issue by dc232** [bitnami/charts#8985]
### Name and Version

bitnami/WordPress

### What is the problem this feature will solve?

I would like to have the ability to add support to custom mime types so that it would be possible to upload avif files to the WordPress origin servers, 
more details can be found here 
https://avif.io/blog/tutorials/wordpress/#manuallyuploading

### What is the feature you are proposing to solve the problem?

The addition of a wordpressExtraConfigContentForFunctions
key in the helm chart to allow this to happen based upon user input

### What alternatives have you considered?

The alternative would be to exec into the pod and update the  functions.php manually however when WordPress updates it is possible that this file may not persist

**Comment by juan131** [comment]
Hi @dc232 

Thanks for reporting this feature request. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by dc232** [comment]
Hey @juan131  thanks for getting back to me,
happy to give it a go
will have a look on Saturday UK time

**Comment by dc232** [comment]
Hey @juan131 was wonering for the var ```wordpressExtraConfigContent``` how does the content supplied to the var persist within the volume, it seems a  bit unclear when the var is set via the deployment, I'm planning to use the var as a template for the functions.php on the basis that there is one present and outside of the themes dir

**Comment by juan131** [comment]
Hi @dc232 

You can find in the link below the logic that's used in the container scripts to manage the `WORDPRESS_EXTRA_WP_CONFIG_CONTENT` env. variable:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L260

**Comment by dc232** [comment]
still WIP haven't got round to it
