### ISSUE TITLE
Airfow DAGs existing config map does not work

### ISSUE THREAD

**Issue by ameier38** [bitnami/charts#8986]
### Name and Version

bitnami/airflow 12.0.1

### What steps will reproduce the bug?

Specify a value for `dags.existingConfigmap`

### Are you using any custom parameters or values?

`dags.existingConfigmap=<config map name>`

### What is the expected behavior?

The dags are loaded from the existing config map

### What do you see instead?

```
Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to create chart from template: template: airflow/templates/worker/statefulset.yaml:74:12: executing "airflow/templates/worker/statefulset.yaml" at <include "airflow.loadDAGsInitContainer" .>: error calling include: template: airflow/templates/_helpers.tpl:200:16: executing "airflow.loadDAGsInitContainer" at <.Values.containerSecurityContext.enabled>: nil pointer evaluating interface {}.enabled
```

### Additional information

The value `containerSecurityContext.enabled` does not exist that is referenced in `_helpers.tpl`.

**Comment by fmulero** [comment]
Hi @ameier38, thanks for sharing.

I reproduced the issue using the following  `values.yaml`:
```
dags:
  existingConfigmap: gh8986-test
extraDeploy:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: gh8986-test
    data: 
```
We'll open an internal task to review it but we cannot guarantee an ETA. As soon as there are more news, we'll let you know.

**Comment by fmulero** [comment]
Hi @ameier38,

A new version with the fix has just released. During today it will be available in the helm repository, but if you are eager to use it, you can download it directly from github.

Regards
