### ISSUE TITLE
[bitnami/grafana-operator] grafana.nodeselector is not applied to the grafanas.integreatly.org CRD

### ISSUE THREAD

**Issue by purvaldur** [bitnami/charts#8987]
### Name and Version

bitnami/grafana-operator

### What steps will reproduce the bug?

1. Set a value for grafana.nodeselector:
```yaml
grafana-operator:
  grafana:
    nodeSelector:
      nodepool: "test"
```
2. Deploy grafana-operator
3. Run the command `kubectl get pods -A -o=custom-columns='POD NAME:metadata.name,NODE POOL:spec.nodeSelector.nodepool'` to get pod names and their nodepools.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Node pool for the grafana-deployment pod is `test`

### What do you see instead?

Node pool for the grafana-deployment pod is `<none>`

### Additional information

Manually editing the grafanas.integreatly.org CRD to include the node selector parameter from https://github.com/bitnami/charts/blob/master/bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml and restarting the pod, gives the pod the correct resource pool.

```
kubectl get grafanas.integreatly.org -A
kubectl edit grafanas.integreatly.org XYZ
```

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out.
  Since you already have the changes, Would you like to send a PR ? we will be glad to review and merge it.

Thanks forehand
