### ISSUE TITLE
[bitnami/nginx] ingress.yaml does not have support to include ingressClass under spec of ingress manifest

### ISSUE THREAD

**Issue by nitin8147** [bitnami/charts#8989]
### Name and Version

bitnami/nginx

### What is the problem this feature will solve?

This will allow to pass the ingressClass from the spec field of the ingress manifest instead of using the annotations for the latest versions of kubernetes.

### What is the feature you are proposing to solve the problem?

a way to provide ingressClass name either from annotation or from spec inside the ingress manifest

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! I think it makes sense to implement the feature. If you want to speed up the process, would you like to submit a PR adding the feature?

**Comment by aoterolorenzo** [comment]
Closing this issue: already addressed in #9953
