### ISSUE TITLE
[bitnami/moodle] editing path does no load css and directs to wrong pages

### ISSUE THREAD

**Issue by lru-avershave** [bitnami/charts#8993]
### Name and Version

[bitnami/moodle]

### What steps will reproduce the bug?

Setting the path does not allow css to load as well as all the links on the page are broken

### Are you using any custom parameters or values?

```
  hostname: moodle.local
  ## @param ingress.path The Path to Moodle&trade;. You may need to set this to '/*' in order to use this with ALB ingress controllers.
  ##
  path: /moodle/*
```

### What is the expected behavior?

Expected behavior is for the CSS and all of the links to work on the page.

### What do you see instead?

Broken CSS, links are all broken on the page, etc.

### Additional information

Very new to Kubernetes so I'm still trying to figure out how to fix the path based routing after changing the path.

I've tried the nginx rewrite annotations with no avail. Any chance I can get some help on this?

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
