### ISSUE TITLE
IBM Cloud Kafka deployment fails

### ISSUE THREAD

**Issue by wjbeau** [bitnami/charts#8996]
### Name and Version

bitnami/kafka 15.1.1

### What steps will reproduce the bug?

When deploying to IBM Cloud (using either the IBM Catalog Schematic or directly using Helm) the persistent volume will not provision correctly.

If I use the default ibmc-block-gold storageClass nothing happens despite having the block-storage-plugin installed.  This seems to be caused by: `E0212 23:34:43.787272       1 controller.go:944] provision "default/data-kafka-0" class "ibmc-block-gold": unexpected error getting claim reference: selfLink was empty, can't make reference` because selfLink is no longer supported on K8s 1.21.

If using ibmc-file-bronze storageClass, the PVC is provisioned but I get file permission errors on the mkdir /bitnami/kafka/logs, regardless of whether I enable volumePermissions.enabled=true (which fails in the initContainer) or not.

### Are you using any custom parameters or values?

I tried without custom params but I also tried permutations of --set global.storageClass=ibmc-file-bronze,volumePermissions.enabled=true

### What is the expected behavior?

Kafka should be provisioned, but it isn't

### What do you see instead?

The kafka pod and zookeeper pod end up in a CrashLoopBackoff

**Comment by beltran-rubo** [comment]
Hi @wjbeau, are you using a classic or a VPC IKS cluster? The Bitnami Helm charts are verified in a Classic IKS by default, for VPC IKS the recommended `storageClass` is `ibmc-vpc-block-10iops-tier`. Could you please check if that `storageClass` available with `kubectl get storageClass`?

**Comment by wjbeau** [comment]
I'm using a Classic IKS cluster - ibmc-block-gold/silver/bronze are all available, they just don't provision.  If I query the ibm-cloud-block-storage-plugin logs, it states the selfLink is not supported, which seems to be the case since k8s 1.21

**Comment by javsalgar** [comment]
Hi,

Did you check with the IBM Cloud support for help on this?
