### ISSUE TITLE
Problem with autogenerated certificates

### ISSUE THREAD

**Issue by oktayalizada** [bitnami/charts#8998]
### Name and Version

bitnami/kibana:9.3.2

### What steps will reproduce the bug?

1. create elastic search with 2 replicas with security.tls.autogenerated=true
2. it is possible to connect to this cluster from a browser
3. when creating kibana to connect to it
4. `helm install kibana --set elasticsearch.hosts[0]=es-elasticsearch-master.es.svc.cluster.local,elasticsearch.port=9200,image.tag=7.13.0-debian-10-r4,service.type=NodePort,replicaCount=1,service.nodePort=xxxxx,elasticsearch.security.auth.enabled=true,elasticsearch.security.auth.kibanaPassword=xxxxxxxxxxxxxx,elasticsearch.security.tls.enabled=true,elasticsearch.security.tls.verificationMode=none,persistence.enabled=true bitnami/kibana`
I am getting "Unable to retrieve information from Elasticsearch nodes"

### What is the expected behavior?

KIbana connected to elasticsearch

### What do you see instead?

I am getting "Unable to retrieve information from Elasticsearch nodes"

### Additional information
Alternatively, if I use full how can I use an autogenerated certificate in elasticsearch pod in kibana and where it is located?

**Comment by javsalgar** [comment]
Hi,

Could you add the `image.debug=true` flag to see what the exact error is?

**Comment by oktayalizada** [comment]
Hi @javsalgar 
I am not getting any debug logs
{"type":"log","@timestamp":"2022-02-14T13:24:20+00:00","tags":["warning","plugins","actions","actions"],"pid":51,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2022-02-14T13:24:20+00:00","tags":["warning","plugins","alerting","plugins","alerting"],"pid":51,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2022-02-14T13:24:20+00:00","tags":["info","plugins","monitoring","monitoring"],"pid":51,"message":"config sourced from: production cluster"}
{"type":"log","@timestamp":"2022-02-14T13:24:20+00:00","tags":["info","savedobjects-service"],"pid":51,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-02-14T13:24:21+00:00","tags":["error","savedobjects-service"],"pid":51,"message":"Unable to retrieve version information from Elasticsearch nodes."}

These are the logs that I am getting after setting image.debug=true

**Comment by oktayalizada** [comment]
I figured out the problem the error was in version: 7.13.0-debian-10-r4 image, after upgrading to version: 7.16.3-debian-10-r18 the error was fixed
