### ISSUE TITLE
Customize service.name in Traffic Exposure parameters

### ISSUE THREAD

**Issue by digihunch** [bitnami/charts#8999]
### Name and Version

bitnami/postgresql-ha 8.3.1

### What is the problem this feature will solve?

[Istio](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection) uses named port to identify traffic and apply appropriate authorization rules.  Currently, the [Traffic Exposure Parameters](https://artifacthub.io/packages/helm/bitnami/postgresql-ha/8.3.1#traffic-exposure-parameters) does not include customizing the name of the 5432 port. This prevents Istio from being able to apply authentication.

### What is the feature you are proposing to solve the problem?

The ability to customize port name, or at least add prefix, to the name of (default) port 5432 in the Service Object.

**Comment by javsalgar** [comment]
Hi,

Thank you for using bitnami. Please note that we do not actively test our charts with istio. However, adding a prefix to the port names seems a reasonable change that we've done in other charts. Would you like to contribute with a PR?

**Comment by digihunch** [comment]
Thanks @javsalgar I understand the stance. I cited istio as an example just to make my point on the use case for customizing port name. I submitted PR #9015 for review

**Comment by javsalgar** [comment]
Thank you for the PR! As it is merged, I will close the ticket
