### ISSUE TITLE
failed to install CRD crds/custom-resource-definitions.yaml

### ISSUE THREAD

**Issue by ngingihy** [bitnami/charts#9005]
### Name and Version

bitnami/kong

### What steps will reproduce the bug?

1) With Installing latest version of Kong on a provisioned namespace not on a whole cluster (Not having access to GET/List CRD's), i'm getting the below error 
`Error: INSTALLATION FAILED: failed to install CRD crds/custom-resource-definitions.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:test-kong-helm:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope`

### Are you using any custom parameters or values?

in values.yaml file, i'm just adding my private image url `imageRegistry` & `imagePullSecrets`  (for pks regulations)

### What do you see instead?

`Error: INSTALLATION FAILED: failed to install CRD crds/custom-resource-definitions.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:test-kong-helm:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope`

**Comment by miguelaeh** [comment]
Hi @ngingihy ,
Looks like an RBAC issue. Could you check if it is properly configured? In the log you shared:
```
forbidden: User "system:serviceaccount:test-kong-helm:default" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Comment by ngingihy** [comment]
@miguelaeh , it's configured through my administrator, i cant change it.

**Comment by miguelaeh** [comment]
Hi @ngingihy ,
Then we cannot help too much. You will need to talk with him
