### ISSUE TITLE
Close insecure plain-text port 2181 

### ISSUE THREAD

**Issue by RamyaRohidas** [bitnami/charts#9006]
### Name and Version

zookeeper "3.6.1-ubuntu"

### What steps will reproduce the bug?

1. Make variable ZOO_TLS_CLIENT_ENABLE true.
2. Add condition - if ZOO_TLS_CLIENT_ENABLE is true, then don't enter clientPort at any value at all.
3. Delete clientPort = 2181 from the zoo.cfg file (this line was indeed deleted, but 3 more lines were added by default:
server.1 = platform-nap-zookeeper-0.platform-nap-zookeeper-headless.data.svc.cluster.local: 2888: 3888; 2181
server.2 = platform-nap-zookeeper-1.platform-nap-zookeeper-headless.data.svc.cluster.local: 2888: 3888; 2181
server.3 = platform-nap-zookeeper-2.platform-nap-zookeeper-headless.data.svc.cluster.local: 2888: 3888; 2181).

### What do you see instead?

Delete clientPort = 2181 from the zoo.cfg file (this line was indeed deleted, but 3 more lines were added by default:
server.1 = platform-nap-zookeeper-0.platform-nap-zookeeper-headless.data.svc.cluster.local: 2888: 3888; 2181
server.2 = platform-nap-zookeeper-1.platform-nap-zookeeper-headless.data.svc.cluster.local: 2888: 3888; 2181
server.3 = platform-nap-zookeeper-2.platform-nap-zookeeper-headless.data.svc.cluster.local: 2888: 3888; 2181).

**Comment by alemorcuq** [comment]
Could you give me some detailed steps to reproduce? I'm not really sure I understand this:

> Add condition - if ZOO_TLS_CLIENT_ENABLE is true, then don't enter clientPort at any value at all.

What command are you using to install the chart and which are your custom values?
