### ISSUE TITLE
[bitnami/grafana] Wrong default type in values.yaml for extraConfigmaps and extraEnvVars

### ISSUE THREAD

**Issue by deschmih** [bitnami/charts#9007]
### Name and Version

bitnami/grafana 7.6.9

### What steps will reproduce the bug?

In the **value.yaml** the values **extraEnvVars** and **extraConfigmaps** are defaulted as object and not as array. This leads during helm install to warning `cannot overwrite table with non table for extraConfigmaps and  extraEnvVars `, if vaules are used.  

proposal as bugfix in values.yaml:
``` 
  extraEnvVars: []
  extraConfigmaps: []

```

### Are you using any custom parameters or values?

extraEnvVars and  extraConfigmaps

### What is the expected behavior?

helm install without warning

### What do you see instead?

helm install result with 
warning `cannot overwrite table with non table for extraConfigmaps and  extraEnvVars `

**Comment by marcosbc** [comment]
Hi @deschmih, you are right, it seems like that is a typo in our documentation. Would you be up for sending a PR to fix this issue?

**Comment by deschmih** [comment]
@marcosbc PR is created and is waiting for review.
