### ISSUE TITLE
Specify db schema

### ISSUE THREAD

**Issue by budirec** [bitnami/charts#9014]
### Name and Version

bitnami.sonarqube/0.2.6

### What is the problem this feature will solve?

Permission problem if the db user only has access to specific schema

### What is the feature you are proposing to solve the problem?

Expose db schema to externalDatabase.schema and pass it to JDBC connection of sonarqube

### What alternatives have you considered?

Expose sonarqube jdbc connection

**Comment by budirec** [comment]
Here is the connection that I use
jdbc:postgresql://<HOST>:<PORT>/<DB>?currentSchema=<SCHEMA>

Not sure where the bash script location is

**Comment by javsalgar** [comment]
Hi!

Here is the script https://github.com/bitnami/bitnami-docker-sonarqube/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/libsonarqube.sh
