### ISSUE TITLE
MountVolume.MountDevice failed for volume : rpc error: code = Internal desc = Unable to find device path out of attempted paths

### ISSUE THREAD

**Issue by JamesArthurHolland** [bitnami/charts#9020]
### Name and Version

bitnami/wordpress 13.0.11

### What steps will reproduce the bug?

```
Warning  FailedMount             35s (x5 over 43s)  kubelet  
                MountVolume.MountDevice failed for volume "pvc-5626cc8567a3406f" :
rpc error: code = Internal desc = Unable to find device path out of attempted paths: 
[/dev/disk/by-id/linode-pvc5626cc8567a3406f /dev/disk/by-id/scsi-0Linode_Volume_pvc5626cc8567a3406f]
```

Anyone know why this may be?

3 nodes on linode, only 1 pod for wordpress.

Mariadb can mount its volumes no problem.

Using
https://github.com/bitnami/charts/tree/master/bitnami/wordpress

### What is the expected behavior?

volume should mount

### What do you see instead?

```
MountVolume.MountDevice failed for volume "pvc-5626cc8567a3406f" : rpc error: code = Internal desc = Unable to find device path out of attempted paths: [/dev/disk/by-id/linode-pvc5626cc8567a3406f /dev/disk/by-id/scsi-0Linode_Volume_pvc5626cc8567a3406f]
```

**Comment by juan131** [comment]
Hi @JamesArthurHolland 

Could you please share the values.yaml you're using to install the WordPress chart? Thanks in advance.

**Comment by JamesArthurHolland** [comment]
helm upgrade --install wordpress ./helm/wordpress \
  --set image.debug="true" \
  --set volumePermissions.enabled="false" \
  --set persistence.enabled="false" \
  --set persistence.size="8Gi" \
  --set global.storageClass="linode-block-storage-retain" \
  --set persistence.storageClass="linode-block-storage-retain" \
  --set ingress.enabled="true" \
  --set ingress.hostname="${HOST}" \
  --set service.type="ClusterIP" \
  --set externalDatabase.host="mariadb" \
  --set externalDatabase.port="3306" \
  --set externalDatabase.user="root" \
  --set externalDatabase.password="password" \
  --set memcached.enabled="true" \
  --set ingress.annotations."kubernetes\.io\/ingress\.class"="nginx" \
  --set ingress.annotations."nginx\.ingress\.kubernetes\.io\/affinity"="cookie" \
  --set ingress.annotations."nginx\.ingress\.kubernetes\.io\/affinity-mode"="persistent" \
  --set wordpressPassword="password"

**Comment by migruiz4** [comment]
Hi @JamesArthurHolland,

My first impression is that this is not an issue with the Wordpress chart but with Linode.
I have found this related issue with the same error as you, so I would recommend having a look: https://www.linode.com/community/questions/20010/deploying-postgres-databasa-with-csi-volumes

There, users mention several options to solve the problem:
- Issues may happen if the same volume is not shared between several containers.
- Manually detaching and then reattaching the volume.

I'm sorry but, if it is an issue with Linode I may not be very helpful, so I would recommend also sharing your issue with the Linode community.
