### ISSUE TITLE
[Bitnami/spring-cloud-dataflow] rsocket host configuration

### ISSUE THREAD

**Issue by dadacom379** [bitnami/charts#9021]
### Name and Version

bitnami/spring-cloud-dataflow 2.5.0

### What is the problem this feature will solve?

When installing stream applications (source/processor/task/sink/app) in another Kubernetes namespace using this feature 

- environment variable KUBERNETES_NAMESPACE

All Grafana monitoring stop working by default, in that case you can always need to modify all stream freetext at every deployment. In my case we have more that 60 streams running.(**Change is long**)

### What is the feature you are proposing to solve the problem?

To fix this problem is only to add namespace after the rsocket host in server and skipper configmap.
Modification in this files

- https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml#L27
- https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/templates/server/configmap.yaml#L27

![image](https://user-images.githubusercontent.com/17455054/154075686-7fae59ce-0974-41e5-a377-361e2c7542c0.png)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by carrodher** [comment]
Thanks, there is nothing special about branch naming, [here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines
