### ISSUE TITLE
Missing ingressClassName setting

### ISSUE THREAD

**Issue by foal** [bitnami/charts#9027]
### Name and Version

bitnami/jenkins 8.1.7

### What steps will reproduce the bug?

1. Try to install

### What is the expected behavior?

Configure ingressClassName in the Values

### What do you see instead?

There is no `ingressClassName` setting for Jenkins ingress

**Comment by migruiz4** [comment]
Hi @foal,

This PR adds is currently being reviewed and adds the missing `ingressClassName` https://github.com/bitnami/charts/pull/9003
