### ISSUE TITLE
Both nodes becomes primary causing stale/old data in the Database

### ISSUE THREAD

**Issue by DevvG** [bitnami/charts#9032]
### Name and Version

postgresql-ha 11.10.0

### What steps will reproduce the bug?

Please refer to earlier bug https://github.com/bitnami/charts/issues/7163 for details.

### What do you see instead?

Sometime both nodes becoming primary and data replication not happening properly. Then after switchover , new primary contains only limited amount of old data before both node became primary.

**Comment by DevvG** [comment]
The exact scenario:

/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf node check
postgresql-repmgr 10:03:32.82
postgresql-repmgr 10:03:32.83 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 10:03:32.83 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 10:03:32.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 10:03:32.83

Node "postgres-postgresql-ha-postgresql-0":
        Server role: OK (node is primary)
        Replication lag: OK (N/A - node is primary)
        WAL archiving: OK (0 pending archive ready files)
        Upstream connection: OK (N/A - node is primary)
        Downstream servers: OK (this node has no downstream nodes)
        Replication slots: OK (node has no physical replication slots)
        Missing physical replication slots: OK (node has no missing physical replication slots)
        Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")

---------------------------------------------------------

I have no name!@postgres-postgresql-ha-postgresql-1:/$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf node check
postgresql-repmgr 10:04:01.46
postgresql-repmgr 10:04:01.47 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 10:04:01.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 10:04:01.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 10:04:01.48

WARNING: node "postgres-postgresql-ha-postgresql-0" not found in "pg_stat_replication"
Node "ems5g-postgres-postgresql-ha-postgresql-1":
        Server role: OK (node is primary)
        Replication lag: OK (N/A - node is primary)
        WAL archiving: OK (0 pending archive ready files)
        Upstream connection: OK (N/A - node is primary)
        Downstream servers: CRITICAL (1 of 1 downstream nodes not attached; missing: postgres-postgresql-ha-postgresql-0 (ID: 1000))
        Replication slots: CRITICAL (1 of 1 physical replication slots are inactive)
        Missing physical replication slots: OK (node has no missing physical replication slots)
        Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")

**Comment by rafariossaa** [comment]
Hi,
  I think this is similar to #6555. Could you take a look to it to confirm it ?
  Do you a step sequence that leads to this state ?

**Comment by DevvG** [comment]
Yes it is similar. I able to reproduce it in AWS cluster pretty easily now. One just need to restart primary pod and this is happening immediately or after attempting the same for 2 to 3 times. To me, as some one mentioned in some comments, it is happening due to the restarted pod coming up quickly even realizing that it is standby now and not joining the new primary. 

Although this has to be investigated further from software side, but as workaround, I reduced the repmgrReconnectInterval from 5 seconds to 2 seconds and postgres container's readiness probe's initialDelaySeconds to 30. After this change I haven't able to reproduce the issue. We are testing now by randomly restarting primary with some amount of data and watching the behavior.

**Comment by rafariossaa** [comment]
Hi @DevvG ,
  Thanks for sharing you experience and your workaround.
  As this seems to be timing related it is very dependent on each cluster. In the cases were the default values doesn't work you will need to find the settings that work for you. If more users find that those settings work for them, we can change the default settings in the chart.
  A quick question, which chart version are you using ? Have you tried v 7.0.1?
