### ISSUE TITLE
Mautic packaged by Bitnami Versão: 4.1.2-0 on Debian 10 Problem

### ISSUE THREAD

**Issue by mhaola** [bitnami/charts#9034]
### Name and Version

Mautic packaged by Bitnami Versão: 4.1.2-0 on Debian 10

### What steps will reproduce the bug?

Hello, I recently started using Bitnami's Mautic framework on AWS for my digital marketing agency. The settings seem correct but my first campaign does not trigger the emails. Can you please help me to check what might be happening?

### What do you see instead?

Hello, I recently started using Bitnami's Mautic framework on AWS for my digital marketing agency. The settings seem correct but my first campaign does not trigger the emails. Can you please help me to check what might be happening?

**Comment by carrodher** [comment]
Hi, please note we provide support for Helm charts and containers using GitHub issues, but support for VMs, cloud images, etc is provided at https://community.bitnami.com/. Can you post your question in our community forum? Thanks
