### ISSUE TITLE
Metrics-server `serviceAccount.name` paramter ignored.

### ISSUE THREAD

**Issue by GrigorievNick** [bitnami/charts#9040]
### Name and Version

bitnami/metrics-server 5.11.1

### What steps will reproduce the bug?

create chart with 
```
set {
    name  = "serviceAccount.name"
    value = "metrics-sever-sa"
  }
```

### Are you using any custom parameters or values?

serviceAccount.name yes throug set.

### What is the expected behavior?

Service account `metric-server-sa` created and used.

### What do you see instead?

Service account with the name `metric-server` created. But metric-server try to use `metric-server-sa`

### Additional information

I create this helm chart using terraform.
but I am sure it will be reproduced with pure helm.
here is [code](https://github.com/bitnami/charts/blob/master/bitnami/metrics-server/templates/serviceaccount.yaml#L5) which do not use `Values.serviceAccount.name`. 
but here is the [description](https://github.com/bitnami/charts/tree/master/bitnami/metrics-server#metrics-server-parameters) to `serviceAccount.name` parameter.
```
The name of the ServiceAccount to create
```

**Comment by javsalgar** [comment]
Hi,

I think I found the issue. In `bitnami/metrics-server/templates/serviceaccount.yaml`:

```
  name: {{ template "common.names.fullname" . }}
```

It should be

```
  name: {{ template "metrics-server.serviceAccountName" . }}
```

As you spotted the issue, would you like to submit a PR fixing it?

**Comment by GrigorievNick** [comment]
hi @javsalgar yes, as I also see this code.
I just want not sure how all this is `common. templates` work.
If you say it's safe to just change this variable in the service account template.
I can do it, without a doubt.

**Comment by javsalgar** [comment]
Awesome!

**Comment by javsalgar** [comment]
Hi,

I see that you created a PR but not in our repository, would you like to submit the PR to the bitnami/charts repository?

**Comment by GrigorievNick** [comment]
Yes. But I am from Ukraine. I was busy with more important staff.

пн, 7 мар. 2022 г., 12:12 Javier J. Salmerón-García <
***@***.***>:

**Comment by javsalgar** [comment]
Oh sorry, didn't notice that. We can take the PR from here and apply the change. Best wishes and stay safe.
