### ISSUE TITLE
Example of setting podLabels for postgresql-HA?

### ISSUE THREAD

**Issue by MswPaulDSmith** [bitnami/charts#9044]
### Name and Version

bitnami/postgresql-ha master

### What steps will reproduce the bug?

1. On linux, Kubernetes
2. Add the following to my values.yaml
```
postgresql:
  podLabels:
    app: something
```
3. I expected the resulting kubernetes pod to have a label `app=something` but this label does not appear to get added.
4. No errors were reported, my attempt to create the podLabel simply failed.

Apologies if this is a Kubernetes newbie question but what should I be putting in `values.yaml` to achieve this?  This is similar to the YAML that I use for the non-HA postgresql chart but perhaps the "Evaluated as a template" functionality for the HA chart of tripping me up?

### Are you using any custom parameters or values?

Tried both `values.yaml` and `--set` but cannot figure out the correct syntax for either.

### What is the expected behavior?

Expect to see my Kubernetes pod have the label `app=something`

### What do you see instead?

A lot of standard labels, but not my label.

**Comment by fmulero** [comment]
Hi @MswPaulDSmith, thanks for sharing!

I tried to reproduce the issue without success:
```
helm install postgresql-ha bitnami/postgresql-ha --set postgresql.podLabels."app"=something
```
After that I listed the labels in postgresql-ha pods (keep in mind that this parameter doesn't affect to pgpool pod) and everything looks fine. Please see the following picture:
![image](https://user-images.githubusercontent.com/23502572/154435642-25ff6c8e-7808-4d6c-9f1b-ab8ec973be26.png)

If you tested it with other version or chart, please let us know

**Comment by MswPaulDSmith** [comment]
Well I tried it but it still had no affect.  I notice that you are starting the postgresql chart directly whereas I am using it as a dependency of my project; might this make a difference?  This is the command I use to start my application.  Apologies that it is quite complex; I will be improving it once I figure out how to get the podLabels to work!
```
helm install something --set-string 'name=something,version=0.2.4-13_ha,image=docker-local-mutable.repository.com/image-something,jobs[0].name=something-parsing,jobs[1].name=something-caching,jobs[1].args[2]=something-service:8000,memcached.podLabels.app=something,postgresql.postgresqlDataDir=/var/lib/something/postgresql/data,postgresql.persistence.mountPath=/var/lib/something/postgresql,postgresql.password=secret,postgresql.repmgrPassword=secret,global.postgresql.repmgrPassword=secret,pgpool.adminPassword=secret' --set 'postgresql.podLabels."app"=something' --values ./.kubernetes/something/values.yaml --namespace my-name-space ./.kubernetes/something
```
and here is the result of checking the postgresql pod labels
```
kubectl get pod something-postgresql-ha-postgresql-1 --show-labels
NAME                                     READY   STATUS             RESTARTS   AGE    LABELS
something-postgresql-ha-postgresql-1   0/1     CrashLoopBackOff   4          7m3s   app.kubernetes.io/component=postgresql,app.kubernetes.io/instance=something,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=postgresql-ha,controller-revision-hash=something-postgresql-ha-postgresql-d9cdff8b6,helm.sh/chart=postgresql-ha-8.3.1,statefulset.kubernetes.io/pod-name=something-postgresql-ha-postgresql-1
```
As you can see, my label is not there.  Any suggestions for how I can further debug this?  Also, are the double-quotes aorund the `"app"` significant?  Won't the shell remove them before it calls helm?

**Comment by fmulero** [comment]
I think you are not setting correctly the values for your chart and/or bitnami/postgresql-ha chart. Please [review the values in the release](https://helm.sh/docs/helm/helm_get_values/)
```
helm get values -a something
```

**Comment by MswPaulDSmith** [comment]
Your suggestion was great and I see what is going on.  The config I had in my `values.yaml` was like this:
```
...
postgresql:
  podlabels:
    app: something
```
But it has to be like this:
```
...
postgresql-ha:
  postgresql:
    podLabels:
      app: something
```
Note the extra level of `postgresql-ha`.  This is probably just my misunderstanding of the config and not appreciating that I needed the Chart name before the config parameters described.
Many thanks for your help, especially that final command which I will be noting down for the future!

**Comment by fmulero** [comment]
Great!, I'll close the issue then
