### ISSUE TITLE
Contour controller POD not starting, missing RBAC

### ISSUE THREAD

**Issue by khowling** [bitnami/charts#9047]
### Name and Version

bitnami/contour-7.3.5

### What steps will reproduce the bug?

Installing the latest bitnami contour helm char in kubernetes 1.21.7

### Are you using any custom parameters or values?

```
--set envoy.kind=daemonset     
--set contour.service.externalTrafficPolicy=local     
--set metrics.serviceMonitor.enabled=true     
--set metrics.serviceMonitor.namespace=monitoring
```

### What is the expected behavior?

a working ingress controller

### What do you see instead?

After deploying the helm chart, the contour Controller Logs output: 
```cannot get resource "leases" in API group "coordination.k8s.io"```

and there is no IP address for my Ingresses

**Comment by juan131** [comment]
Hi @khowling 

It seems it's something related to RBAC permissions, the changes at #9030 should fix this issue.
