### ISSUE TITLE
nginx strategy type

### ISSUE THREAD

**Issue by messiahUA** [bitnami/charts#9054]
### Name and Version

bitnami/nginx 9.7.6

### What is the problem this feature will solve?

there is no way to set/define strategy type for the deployment

### What is the feature you are proposing to solve the problem?

provide an ability to change/set strategy type for the deployment

### What alternatives have you considered?

custom chart

**Comment by javsalgar** [comment]
Hi,

The update strategy is something that we have in several charts. I think it makes sense to have it here as well. If you want to speed up the process, would you like to submit a PR?
