### ISSUE TITLE
[bitnami/common] README `common.labels.matchLabels` description isn't compatible

### ISSUE THREAD

**Issue by marpontes** [bitnami/charts#9060]
### Name and Version

bitnami/common 1.11.1

### What steps will reproduce the bug?

1. Go to [README.md](https://github.com/bitnami/charts/tree/master/bitnami/common#labels);
2. Check the description for `common.labels.matchLabels`: 
    1. _Return the proper Docker Image Registry Secret Names_
3. It matches the description for [pullSecrets/renderPullSecrets](https://github.com/bitnami/charts/tree/master/bitnami/common#images)

### What is the expected behavior?

The description should be something like -- as seen [here](/bitnami/charts/blob/master/bitnami/common/templates/_labels.tpl#L13):

```
common.labels.matchLabels: Labels to use on deploy.spec.selector.matchLabels and svc.spec.selector
```

### What do you see instead?

The description matches the text for [pullSecrets/renderPullSecrets](https://github.com/bitnami/charts/tree/master/bitnami/common#images): 

```
common.labels.matchLabels: Return the proper Docker Image Registry Secret Names
```

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will check the issue.
