### ISSUE TITLE
Mariadb Galera Cluster v10.6.5 - Kubernetes StatefulSet Deployment for Production

### ISSUE THREAD

**Issue by udupicloud** [bitnami/charts#9073]
### Name and Version

bitnami/mariadb

### What is the problem this feature will solve?

Hi,
I am beginner to Kubernetes and Bitnami Charts. 
I am looking for a Mariadb Galera Cluster v10.6.5 - Kubernetes StatefulSet deployment for Production.

1. I want yaml file for Mariadb Galera v10.6.5 StatefulSet.
2. I want those deployments with systemd and SSH commands to work (CentOS Stream 8 preferred)
3. I want those pods to be accessible from outside the Kubernetes cluster using SSH.
4. I should be able to use the Cephfs storage as storage class for the pods.
Any link related to the above requirement will be of great help for me to deploy for our production.

My setup is given below:- (On Premise Setup)
1. I have Ceph Storage, using it as file system (cephfs) for Kubernetes Pod Deployment.
2. I have Kubernetes cluster with master and worker nodes.
3.  I have worked on Deployments. But new to StatefulSet.

**I have tried below links, but was not able to do ssh and also could not use the systemd commands. Was getting error as "Failed to get D-Bus connection: Operation not permitted"**

Below given links worked without systemd and ssh.
1. https://artifacthub.io/packages/helm/bitnami/mariadb-galera
2. https://github.com/bitnami/bitnami-docker-mariadb-galera#setting-up-a-multi-master-cluster
3. https://github.com/cgruver/mariadb-galera-okd

Regards,
Mark.

### What is the feature you are proposing to solve the problem?

I do not have any knowledge on programming. I am using on-premise setup for both Ceph and Kubernetes. 
I am here to request for features that may help community and me to deploy a StatefulSet in Kubernetes with MariaDB and have it easily accessible from external network using SSH and run services like systemd commands. I am not sure how do I configure the yaml's.  Also I want to know after the deployment of StatefulSet, if everything works as expected, Will I be able to save the changes and do rolling updates for pods based on changes that we might make in our pods.

Regards,
Mark

**Comment by juan131** [comment]
Hi @udupicloud 

It seems it is not an issue related to the Bitnami MariaDB Galera chart but questions about how to properly use it, please note Bitnami maintainers do not provide consulting services through GitHub. We highly recommend you to read carefully the [Configuration and Installation details](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#configuration-and-installation-details) instructions available in the chart's README.md file.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info for you.

---

> NOTE: Please note this is a K8s environment. **ssh** is not available on containers nor **systemd** since they're not required. You can access every container use `kubectl exec` and there's no need for daemon management since containers are intended to be ephemeral.
