### ISSUE TITLE
[bitnami/redis]  You must provide your current passwords when upgrading the release. even with auth=false

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [bitnami/charts#9075]
### Name and Version

bitnami/redis latest

### What steps will reproduce the bug?

helm upgrade --install redis -f values.yaml bitnami/redis

### Are you using any custom parameters or values?

```yaml
# values.yaml

auth:
  enabled: false
```

### What is the expected behavior?

let it upgrade without problems, since we don't use any password authentication

### What do you see instead?

```
Error: UPGRADE FAILED: execution error at (flave/charts/redis/templates/NOTES.txt:191:4):
  PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                   Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                   Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
      'auth.password' must not be empty, please add '--set auth.password=$REDIS_PASSWORD' to the command. To get the current value:
          export REDIS_PASSWORD=$(kubectl get secret --namespace "flavetestkub1" flave-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
```

### Additional information

Am I wrong with this issue? Please help :)

**Comment by juan131** [comment]
Hi @h0jeZvgoxFepBQ2C 

What version of the Bitnami Redis chart are you using? Is it the latest one?

**Comment by yanndebelgique** [comment]
I'm having same issue. the image is docker.io/bitnami/redis:6.0.12-debian-10-r3

**Comment by juan131** [comment]
Hi @yanndebelgique @h0jeZvgoxFepBQ2C 

I'm asking about the chart version (instead of the image version). The chart isn't including these validations since version `15.6.10`, see:

- https://github.com/bitnami/charts/pull/8518

**Comment by yanndebelgique** [comment]
I was using the latest version v16.4.3. When I specified the
version v16.4.0 then I didn't have the issue anymore

**Comment by yanndebelgique** [comment]
Hi
There wasn't an error shown. Just that other pods who wanted to connect to
REDIS could not because authentication was required.
I got this message when connecting to REDIS:* NOAUTH Authentication
required.*

**Comment by juan131** [comment]
Hi @yanndebelgique 

I'm sorry but I don't think that I understand the whole scenario. Please correct me if I'm wrong in any of the assumptions below:

- You installed the chart (version `16.4.3`) disabling authentication (setting `auth.enabled` to `false`).
- Then, you upgraded your release with the same parameters and you obtained the authentication error.

Am I right?

**Comment by yanndebelgique** [comment]
Correct

**Comment by juan131** [comment]
Hi @yanndebelgique 

I wasn't able to reproduce the issue. These are the steps I followed on a clean environment:

- Install the chart version you mentioned setting `auth.enabled` to `false`:

```bash
helm install redis bitnami/redis --set auth.enabled=false --version 16.4.3
```

- Wait for the pods to be ready, and upgrade to latest version:

```console
$ kubectl get pods
NAME               READY   STATUS    RESTARTS   AGE
redis-master-0     1/1     Running   0          2m30s
redis-replicas-0   1/1     Running   0          2m30s
redis-replicas-1   1/1     Running   0          109s
redis-replicas-2   1/1     Running   0          71s
$ helm upgrade redis bitnami/redis --set auth.enabled=false
```

- Wait for all the replicas to be updated, create a Redis client and connect to Redis master without authentication:

```console
$ kubectl get pods
NAME               READY   STATUS    RESTARTS   AGE
redis-master-0     1/1     Running   0          6m26s
redis-replicas-0   1/1     Running   0          4m37s
redis-replicas-1   1/1     Running   0          5m26s
redis-replicas-2   1/1     Running   0          6m35s
$ kubectl run --namespace default redis-client --restart='Never'  --image docker.io/bitnami/redis:6.2.6-debian-10-r146 --command -- sleep infinity
pod/redis-client created
$ kubectl exec --tty -i redis-client --namespace default -- bash
I have no name!@redis-client:/$ redis-cli -h redis-master
redis-master:6379>
```

**Comment by yanndebelgique** [comment]
Ok sorry then I must have omitted something regarding my setup in my bug
description
