### ISSUE TITLE
[Redmine] Persisted storage mounted in wrong location

### ISSUE THREAD

**Issue by electrical** [bitnami/charts#9078]
### Name and Version

bitnami/redmine

### What steps will reproduce the bug?

1. Install redmine with persisted storage
2. Deploy new version

### What is the expected behavior?

To see new plugins etc

### What do you see instead?

Since the persisted volume is mounted on /bitnami/redmine it overrides anything that we provide for plugins or anything else.
Even an upgraded version of redmine will be overwritten by what's stored in the PVC.

### Additional information

The PVC should be mounted on /bitnami/redmine/files to provide persistent storage for uploaded files

**Comment by electrical** [comment]
Sorry, found. that it's working differently than expected, but even how it works now is very weird.
it's storing everything ( plugins, config, etc ) while this makes no sense

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
