### ISSUE TITLE
[bitnami/elasticsearch] cannot use internal load balancer on AWS

### ISSUE THREAD

**Issue by DaveWHarvey** [bitnami/charts#910]
AWS requires the following for an internal load balancer:
Annotations:              service.beta.kubernetes.io/aws-load-balancer-internal=0.0.0.0/0

coordinating-svc.yaml does not allow this to be specified in values-production.yaml

Got this to work by adding at line 11
  {{- if .Values.coordinating.service.annotations }}
  annotations:
  {{ toYaml .Values.coordinating.service.annotations | indent 4 }}
  {{- end }}

**Comment by juan131** [comment]
Hi @DaveWHarvey 

I just creates this PR to include this feature on the chart: https://github.com/bitnami/charts/pull/915

Thanks for the suggestion!!
