### ISSUE TITLE
[bitnami/kafka] Cannot create fresh install with volumePermissions.enabled=true

### ISSUE THREAD

**Issue by bryopsida** [bitnami/charts#9126]
### Name and Version

bitnami/kafka 15.3.0

### What steps will reproduce the bug?

1. On a fresh install
2. `helm install bitnami/kafka --generate-name --set volumePermissions.enabled=true`

The init container on the Kafka broker will fail with the following error:

```
/bin/chown: missing operand after '1001:1001'
Try '/bin/chown --help' for more information.
```

The issue is on a fresh PVC the chown command fails.

It was changed to use a find that pipes results to a chown here: https://github.com/bitnami/charts/pull/8666/files which fails on fresh installs.

Current code 
``` bash
              mkdir -p "{{ .Values.persistence.mountPath }}" "{{ .Values.logPersistence.mountPath }}"
               find "{{ .Values.persistence.mountPath }}" -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}
               find "{{ .Values.logPersistence.mountPath }}" -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}
           {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
```
Previous working code
``` bash
              chown -R "{{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}" "{{ .Values.persistence.mountPath }}"
               chown -R "{{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}" "{{ .Values.logPersistence.mountPath }}"
           {{- if eq ( toString ( .Values.volumePermissions.securityContext.runAsUser )) "auto" }}
```

### Are you using any custom parameters or values?

volumePermissions.enabled=true

### What is the expected behavior?

The Kafka broker is successfully initialized and the broker starts up.

### What do you see instead?

The volume permissions init container crashes because the chown command is invalid.

**Comment by juan131** [comment]
Hi @bryopsida 

This should be fixed with the changes introduced at https://github.com/bitnami/charts/pull/9134
Please give a try to the chart version `15.3.1`.

**Comment by bryopsida** [comment]
That fixed it. Thank you!
