### ISSUE TITLE
wrong file path in ConfigMap for configure-w3-total-cache.sh

### ISSUE THREAD

**Issue by webdz9r** [bitnami/charts#9146]
### Name and Version

Bitnami/wordpress 13.0.9

### What steps will reproduce the bug?

Enable w3 cache

wordpressConfigureCache: true

### Are you using any custom parameters or values?

nope

### What is the expected behavior?

Needs to point to the right path `chmod a-w /bitnami/wordpress/wp-config.php`

 

### What do you see instead?

It's missing the root path `chmod a-w bitnami/wordpress/wp-config.php`

Needs to be `chmod a-w /bitnami/wordpress/wp-config.php`

### Additional information

simple one char fix please

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look :D

**Comment by javsalgar** [comment]
Hi! Did you have time to check the suggestions from the PR?

**Comment by webdz9r** [comment]
I wasn't aware of any suggestions.
