### ISSUE TITLE
updateStrategy type Recreate does not work.

### ISSUE THREAD

**Issue by pitstop-sirish-bajpai** [bitnami/charts#9152]
### Name and Version

bitnami/wordpress 13.0.13

### What steps will reproduce the bug?

1) Try to upgrade deployment with
```yaml
 updateStrategy:
    type: Recreate
```
Upgrade fails with error:
```
Error: UPGRADE FAILED: cannot patch "pitstop-blog-wordpress" with kind Deployment: Deployment.apps "pitstop-blog-wordpress" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```
2) A dry-run produces the following:
```yaml
spec:
  strategy:
    rollingUpdate: {}
    type: Recreate
```
I believe the problem is caused by a spurious rollingUpdate line. It should be suppressed if the type is Recreate

### What is the expected behavior?

The upgrade should work normally and change updateStrategy from RollingUpdate to Recreate

### What do you see instead?
```
Error: UPGRADE FAILED: cannot patch "pitstop-blog-wordpress" with kind Deployment: Deployment.apps "pitstop-blog-wordpress" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by thehungrycoder** [comment]
This solves the problem
https://github.com/bitnami/charts/issues/8961#issuecomment-1034866839
