### ISSUE TITLE
Cluster not deploying with 12 nodes

### ISSUE THREAD

**Issue by Shujja1746** [bitnami/charts#9153]
### Name and Version

bitnami/redis 6.2.6

### What steps will reproduce the bug?

Install bitnami/redis cluster with 12 nodes 

APP VERSION   6.2.6
 CHART             redis-cluster-7.2.4

### Are you using any custom parameters or values?

using values.yaml file and configuring it to deploy 12 node cluster with 6 master and 6 slave
```

 ## @param cluster.nodes The number of master nodes should always be >= 3, otherwise cluster creation will fail
  ##
  nodes: 12
  ## @param cluster.replicas Number of replicas for every master in the cluster
  ## Parameter to be passed as --cluster-replicas to the redis-cli --cluster create
  ## 1 means that we want a replica for every master created
  ##
  replicas: 1
  ## Configuration to access the Redis&trade; Cluster from outside the Kubernetes cluster
  ##
```

### What do you see instead?
```
redis-2-redis-cluster-0    0/1
redis-2-redis-cluster-1    0/1
redis-2-redis-cluster-10   0/1
redis-2-redis-cluster-11   0/1
redis-2-redis-cluster-2    0/1
redis-2-redis-cluster-3    0/1
redis-2-redis-cluster-4    0/1
redis-2-redis-cluster-5    0/1
redis-2-redis-cluster-6    0/1
redis-2-redis-cluster-7    0/1
redis-2-redis-cluster-8    0/1
redis-2-redis-cluster-9    0/1
```
pod description giving this error
```
Warning  Unhealthy               53s (x173 over 15m)  kubelet, aks-redispool-53995875-vmss00000j  Readiness probe failed: cluster_state:fail
/scripts/ping_readiness_local.sh: 13: [: 0: unexpected operator
/scripts/ping_readiness_local.sh: 29: [: 0: unexpected operator
```
### Additional information
```
Warning: Using a password with '-a' option on the command line interface may not be safe.
Could not connect to Redis at 10.3.0.92:6379: Connection refused
Could not connect to Redis at 10.3.0.92:6379: Connection refused
not connected>
```

**Comment by javsalgar** [comment]
Hi,

Does the issue occur with the default values?

**Comment by Shujja1746** [comment]
@javasalgar

No, default working fine, 

9 nodes working fine (3 maters and 2 replica each)

12 nodes not working (6 masters and 1 replica each)

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue

```
helm install rdcl bitnami/redis-cluster --set cluster.nodes=12

 1 ❯ kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
rdcl-redis-cluster-0    1/1     Running   1          8m45s
rdcl-redis-cluster-1    1/1     Running   1          8m45s
rdcl-redis-cluster-10   1/1     Running   0          8m45s
rdcl-redis-cluster-11   1/1     Running   0          8m45s
rdcl-redis-cluster-2    1/1     Running   1          8m45s
rdcl-redis-cluster-3    1/1     Running   1          8m45s
rdcl-redis-cluster-4    1/1     Running   0          8m45s
rdcl-redis-cluster-5    1/1     Running   0          8m45s
rdcl-redis-cluster-6    1/1     Running   0          8m45s
rdcl-redis-cluster-7    1/1     Running   1          8m45s
rdcl-redis-cluster-8    1/1     Running   1          8m45s
rdcl-redis-cluster-9    1/1     Running   0          8m45s
```

Could you add more details about the platform you are using?

**Comment by Shujja1746** [comment]
@javsalgar

Deploying to aks with nodepool size Standard E32ds v5 (32 vcpus, 256 GiB memory).

12 nodes not coming up, 9 nodes are coming, but i want more masters to hold more data on redis
redis-2-redis-cluster-0    0/1     Running   1          5m54s   10.3.0.39    aks-redispool-53995875-vmss00000o    <none>           <none>
redis-2-redis-cluster-1    0/1     Running   1          5m54s   10.3.0.100   aks-redispool-53995875-vmss00000p    <none>           <none>
redis-2-redis-cluster-10   0/1     Running   0          5m53s   10.3.0.40    aks-redispool-53995875-vmss00000o    <none>           <none>
redis-2-redis-cluster-11   0/1     Running   0          5m53s   10.3.0.42    aks-redispool-53995875-vmss00000o    <none>           <none>
redis-2-redis-cluster-2    0/1     Running   1          5m54s   10.3.0.76    aks-redispool-53995875-vmss00000i    <none>           <none>
redis-2-redis-cluster-3    0/1     Running   1          5m54s   10.3.0.85    aks-redispool-53995875-vmss00000j    <none>           <none>
redis-2-redis-cluster-4    0/1     Running   1          5m54s   10.3.0.72    aks-redispool-53995875-vmss00000i    <none>           <none>
redis-2-redis-cluster-5    0/1     Running   1          5m54s   10.3.0.54    aks-redispool-53995875-vmss00000h    <none>           <none>
redis-2-redis-cluster-6    0/1     Running   1          5m54s   10.3.0.48    aks-redispool-53995875-vmss00000o    <none>           <none>
redis-2-redis-cluster-7    0/1     Running   1          5m53s   10.3.0.86    aks-redispool-53995875-vmss00000j    <none>           <none>
redis-2-redis-cluster-8    0/1     Running   1          5m53s   10.3.0.103   aks-redispool-53995875-vmss00000p    <none>           <none>
redis-2-redis-cluster-9    0/1     Running   0          5m53s   10.3.0.73    aks-redispool-53995875-vmss00000i    <none>           <none>

prod-redis-1-redis-cluster-0    1/1     Running   1          3d      10.3.0.91    aks-redispool-53995875-vmss00000j    <none>           <none>
prod-redis-1-redis-cluster-1    1/1     Running   1          3d1h    10.3.0.65    aks-redispool-53995875-vmss00000h    <none>           <none>
prod-redis-1-redis-cluster-2    1/1     Running   0          3d1h    10.3.0.77    aks-redispool-53995875-vmss00000i    <none>           <none>
prod-redis-1-redis-cluster-3    1/1     Running   0          3d1h    10.3.0.84    aks-redispool-53995875-vmss00000j    <none>           <none>
prod-redis-1-redis-cluster-4    1/1     Running   0          3d1h    10.3.0.51    aks-redispool-53995875-vmss00000h    <none>           <none>
prod-redis-1-redis-cluster-5    1/1     Running   0          3d1h    10.3.0.75    aks-redispool-53995875-vmss00000i    <none>           <none>
prod-redis-1-redis-cluster-6    1/1     Running   0          3d1h    10.3.0.87    aks-redispool-53995875-vmss00000j    <none>           <none>
prod-redis-1-redis-cluster-7    1/1     Running   0          3d      10.3.0.89    aks-redispool-53995875-vmss00000j    <none>           <none>
prod-redis-1-redis-cluster-8    1/1     Running   0          3d1h    10.3.0.55    aks-redispool-53995875-vmss00000h    <none>           <none>


Redis memory issues
I have memory issues in redis, when ever I deployed it crashing with memory after sometime.
If I use 256GB node and with 9 nodes (3masters and 2 replica each) and each 3 pods are running one aks node(total 3 such nodes are running)
Not setting any resource and limits, no max memory policy is set, but still seeing cluster is crashing once it reaching pod memory to 10gb in each pod, that is total sum up to 90GB

Not sure where the memory is getting utilized and it crashing.

Can you please suggest, thanks.

**Comment by javsalgar** [comment]
Just for ensuring, could you please double check the following?

- It is strange that with `--set` it works and not in `values.yaml`.  There must be some extra value that you are changing that may be causing the issue.
- Could you check that you are removing the PVCs from previous installations?

**Comment by kvendingoldo** [comment]
I have the same issue: 
3 nodes, 0 replicas

**Comment by kvendingoldo** [comment]
btw. shouldn't we use `=` instead of `==` for shell scripts?

**Comment by javsalgar** [comment]
Hi @kvendingoldo, as far as I'm concerned, the number of nodes should be at least 6, could you try with more nodes?

**Comment by kvendingoldo** [comment]
checked, it works for 6 nodes (3 master, 3 replicas) and for 3 master, 0 replicas if I setup it up from scratch. 
Can you show me where is the requirement for 6 nodes at least?

**Comment by Shujja1746** [comment]
@javsalgar

Deploying with different name, still not coming.

Deployed with 20 nodes too, not working.

redis-cl-redis-cluster-0              0/1     Running   1          21m
redis-cl-redis-cluster-1              0/1     Running   2          21m
redis-cl-redis-cluster-10             0/1     Running   1          21m
redis-cl-redis-cluster-11             0/1     Running   2          21m
redis-cl-redis-cluster-12             0/1     Running   0          21m
redis-cl-redis-cluster-13             0/1     Running   0          21m
redis-cl-redis-cluster-15             0/1     Running   0          21m
redis-cl-redis-cluster-16             0/1     Running   2          21m
redis-cl-redis-cluster-17             0/1     Running   0          21m
redis-cl-redis-cluster-18             0/1     Running   1          21m
redis-cl-redis-cluster-19             0/1     Running   2          21m
redis-cl-redis-cluster-2              0/1     Running   2          21m
redis-cl-redis-cluster-3              0/1     Running   2          21m
redis-cl-redis-cluster-4              0/1     Running   1          21m
redis-cl-redis-cluster-5              0/1     Running   1          21m
redis-cl-redis-cluster-6              0/1     Running   1          21m
redis-cl-redis-cluster-7              0/1     Running   1          21m
redis-cl-redis-cluster-8              0/1     Running   2          21m
redis-cl-redis-cluster-9              0/1     Running   2          21m

**Comment by migruiz4** [comment]
Hi @Shujja1746,

I have been able to reproduce the initial issue, not by using `helm install` but `helm upgrade` trying to increase the number of replicas.

I have submitted a PR fixing this issue:
```
/scripts/ping_readiness_local.sh: 13: [: 0: unexpected operator
/scripts/ping_readiness_local.sh: 29: [: 0: unexpected operator
```
But it only happens when `cluster_state:fail`, so I still need to investigate the real cause of the issue.

Regarding your second question, what issues are you facing when Redis reaches 30gb?
If it is an issue with Redis configuration and not the chart or the container, I may not be the most appropriate person to help you, but I know Redis has tools like `MEMORY DOCTOR` or `MEMORY STATS` that are useful for these cases.

In addition, I would recommend trying to rebalance and try to grow your cluster horizontally (more cluster nodes), but please wait until we fix the current issue.

**Comment by Shujja1746** [comment]
@migruiz4 

Thanks for replying.

Not sure cluster is going down and coming back

Seeing this at cluster nodes

Do you know how to fix this error
10.3.0.203:6379> cluster nodes
5fda0fe76136fee595039599d0158dd8eea880de 10.3.0.17:6379@16379 slave 6f9243d57d35993b9c3710a686acc7d9ad10e5f9 0 1646330288000 1 connected 
cc154dbee22149d38cd4f6363efbbb9a16af7526 :0@0 master,noaddr - 1646227660968 1646227660968 3 disconnected 10923-16383
3ab392ed7c45cc619a2ad5180b945dea85333821 10.3.0.42:6379@16379 slave 6f9243d57d35993b9c3710a686acc7d9ad10e5f9 0 1646330290000 1 connected 
58855901b515866b690ee988de640b202aa488ce 10.3.0.16:6379@16379 slave 6f9243d57d35993b9c3710a686acc7d9ad10e5f9 0 1646330288969 1 connected 
24c3bb6e6ea73f080483189794508b470431ad6e 10.3.0.57:6379@16379 slave 6438f06401cb72676b48358739e557c40e79ec2f 0 1646330291000 11 connected
6438f06401cb72676b48358739e557c40e79ec2f 10.3.0.64:6379@16379 master - 0 1646330290000 11 connected 5461-10922
a74d503bdbe3f1ba5456958e91ef1ad34dba2382 10.3.0.34:6379@16379 slave cc154dbee22149d38cd4f6363efbbb9a16af7526 0 1646330289000 3 connected 
6f9243d57d35993b9c3710a686acc7d9ad10e5f9 10.3.0.203:6379@16379 myself,master - 0 1646330285000 1 connected 0-5460
10623d36692ba184891969008bb234097d3db45c 10.3.0.201:6379@16379 slave 6f9243d57d35993b9c3710a686acc7d9ad10e5f9 0 1646330291986 1 connected
10.3.0.203:6379> 

Do you know how to fix this error?

I have deployed this cluster on 500 gb nodepool with 4 vms running behind
No maxmemory , resouce and limits were defined.

what you mean by horizontal scaling? 
should i add more masters and replicas?

Last time i faced isse while upgading working cluster, and the cluster never came back, do we have to do init:false while adding more nodes?

Appreciate you reply on this.

Thanks

**Comment by migruiz4** [comment]
Hi @kvendingoldo,

Could you please provide the exact command and sanitized `values.yaml` used to deploy the chart? 

Also, please ensure no remaining data from a previous installation remain in your kubernetes cluster using `kubectl get pvc -n my_namespace`. 
Reusing the same release name and namespace will cause Redis to use existing PVC if any, causing initialization errors if different passwords or configurations are used, which is the case when using randomly generated passwords.

**Comment by kvendingoldo** [comment]
Tried to setup from scratch:

`helm upgrade "redis-main" bitnami/redis-cluster  --install -f example.yaml --version=7.2.7 --namespace=redis`

Values:
```
commonAnnotations:
  sidecar.istio.io/inject: "false"

diagnosticMode:
  enabled: false

image:
  registry: docker.io
  repository: bitnami/redis-cluster
  tag: 6.2.6-debian-10-r138
  pullPolicy: IfNotPresent
  debug: false

networkPolicy:
  enabled: false

serviceAccount:
  create: true
  automountServiceAccountToken: true

rbac:
  create: false
  role:
    rules: []

podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  sysctls: []

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

usePassword: true
existingSecretPasswordKey: "password"
existingSecret: "redis-main-password"
usePasswordFile: true

tls:
  enabled: false

service:
  ports:
    redis: 6379
  type: ClusterIP
  externalTrafficPolicy: Cluster

persistence:
  storageClass: "redis-premium"
  size: 8Gi

volumePermissions:
  enabled: false

podSecurityPolicy:
  create: false

redis:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

  useAOFPersistence: "no"
  containerPorts:
    redis: 6379
    bus: 16379
  resources:
    requests:
      cpu: 1
      memory: 8Gi
    limits:
      cpu: 1
      memory: 8Gi

  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  tolerations:
    - key: dedicated
      operator: Equal
      value: RedisMain
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: agentpool
                operator: In
                values:
                  - rmain

updateJob:
  activeDeadlineSeconds: 600
  tolerations:
    - key: dedicated
      operator: Equal
      value: middleware
      effect: NoSchedule
    - key: kubernetes.azure.com/scalesetpriority
      operator: Equal
      value: spot
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: agentpool
                operator: In
                values:
                  - mw
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 515Mi

cluster:
  init: true
  nodes: 3
  replicas: 0
  externalAccess:
    enabled: false
  update:
    addNodes: false
    currentNumberOfNodes: 3

metrics:
  enabled: false

sysctlImage:
  enabled: false
```

The same if:
`useAOFPersistence: "yes"`

The same if 
```
cluster:
  nodes: 6
  replicas: 1
  update:
    addNodes: false
    currentNumberOfNodes: 6
```

What I'm getting in all cases:
```
➜  ~ kubectl logs -f redis-main-redis-cluster-0
COPYING FILE
redis-cluster 14:20:54.92
redis-cluster 14:20:54.92 Welcome to the Bitnami redis-cluster container
redis-cluster 14:20:54.92 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 14:20:54.92 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 14:20:54.92
redis-cluster 14:20:54.92 INFO  ==> ** Starting Redis setup **
redis-cluster 14:20:54.94 INFO  ==> Initializing Redis
redis-cluster 14:20:54.95 INFO  ==> Setting Redis config file
Storing map with hostnames and IPs
redis-cluster 14:21:05.10 INFO  ==> ** Redis setup finished! **

130:C 04 Mar 2022 14:21:05.131 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
130:C 04 Mar 2022 14:21:05.131 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=130, just started
130:C 04 Mar 2022 14:21:05.131 # Configuration loaded
130:M 04 Mar 2022 14:21:05.131 * monotonic clock: POSIX clock_gettime
130:M 04 Mar 2022 14:21:05.132 * No cluster configuration found, I'm db2d2bcb779871840ed7650f00a645b08e922cb0
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 6.2.6 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 130
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

130:M 04 Mar 2022 14:21:05.136 # Server initialized
130:M 04 Mar 2022 14:21:05.137 * Ready to accept connections
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
Node redis-main-redis-cluster-0.redis-main-redis-cluster-headless not ready, waiting for all the nodes to be ready...
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
Node redis-main-redis-cluster-0.redis-main-redis-cluster-headless not ready, waiting for all the nodes to be ready...
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
Node redis-main-redis-cluster-0.redis-main-redis-cluster-headless not ready, waiting for all the nodes to be ready...
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
Node redis-main-redis-cluster-0.redis-main-redis-cluster-headless not ready, waiting for all the nodes to be ready...
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
Node redis-main-redis-cluster-0.redis-main-redis-cluster-headless not ready, waiting for all the nodes to be ready...
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
Node redis-main-redis-cluster-0.redis-main-redis-cluster-headless not ready, waiting for all the nodes to be ready...
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
```

```
redis-main-redis-cluster-0:/bitnami/redis/data$ cat nodes.conf
94f51414b28486b9b34413794bd5ebc0ce1d0ea3 :0@0 myself,master - 0 0 0 connected
vars currentEpoch 0 lastVoteEpoch 0
```

**Comment by kvendingoldo** [comment]
@migruiz4 thx for you effords, I found the same and described in closed ticket: https://github.com/bitnami/charts/issues/9353

**Comment by Shujja1746** [comment]
@migruiz4 

Any update on this?

https://github.com/bitnami/charts/issues/9153#issuecomment-1058348083

**Comment by migruiz4** [comment]
Hi @Shujja1746,

I'm sorry but since this issue has diverged a lot from the original topic, it would be helpful if we could recap to make sure we are on the same page.

On one side, you reported the chart `bitnami/redis-cluster` not deploying with values: `cluster.nodes=6 / cluster.replicas=1`.
But working fine with `cluster.nodes=9 / cluster.replicas=2` and default values (`cluster.nodes=6 / cluster.replicas=1`).

Was that issue resolved?

Then, you have an additional cluster with 9 nodes (I guess 3 masters, 2 replicas), that fails periodically. 
Do they fail randomly or do they only fail when getting closer to that 30 Gb threshold? Do pods display `CrashLoopBackoff`, show as not ready `Running 0/1`, or do they display a different error? 

For that cluster, it would be useful if you could share logs, pod events, `values.yaml` used to deploy (sanitized), and any other useful information you can provide.
