### ISSUE TITLE
minio security context

### ISSUE THREAD

**Issue by zfrhv** [bitnami/charts#9158]
### Name and Version

bitnami/minio 1.2.3

### What is the problem this feature will solve?

run minio instance on openshift without high scc

### What is the feature you are proposing to solve the problem?

add podSecurityContext and containerSecurityContext options to minio, just as rest of the pods have.

also add some global.podSecurityContext and global.containerSecurityContext to the helm chart,
which will apply the security context to all of the instances.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by zfrhv** [comment]
well its my first time ever creating a pull request, but i really want to try to do it.
so it will probably take me a while to learn how to do it, but i will try my best.

**Comment by carrodher** [comment]
Thanks, you can use any of the existing Helm charts as the base. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines

**Comment by zfrhv** [comment]
hello,
i checked the helm charts and i realized that i got confused.
the minio helm chart is not missing the security context configuration.

i was using the thanos helm chart, and in the [README.md](https://github.com/bitnami/charts/tree/master/bitnami/thanos#minio-chart-parameters) it told only few values about the minio.
i think the right will be to add something like "to see additional minio configurations please refer [here](https://github.com/bitnami/charts/tree/master/bitnami/minio)" to the thanos README.md
but seems like README.md is being generated by [this tool](https://github.com/bitnami-labs/readme-generator-for-helm), so even if i add this commed it will be overridden later.
what should i do?

about the global.containerSecurityContext i want to see after i finish with the first task.

**Comment by zfrhv** [comment]
oh maybe i can add this comment in values.yaml 🤦‍♂️

**Comment by carrodher** [comment]
Sure, feel free to contribute by adding a paragraph in Thano's README pointing to MinIO
