### ISSUE TITLE
Etcd readme overview link is deprecated

### ISSUE THREAD

**Issue by AkhileshK8y** [bitnami/charts#9171]
### Name and Version

bitnami/etcd

### What steps will reproduce the bug?

1. Open bitnami etcd [readme](https://github.com/bitnami/charts/blob/master/bitnami/etcd/README.md). 
2. Click on `Overview of Etcd` This opens https://www.redhat.com/en/technologies/cloud-computing/openshift 
3. The link actually points to https://coreos.com/etcd which is deprecated.
4. Should we point to etcd.io??

### What is the expected behavior?

On clicking overview user should be redirected to etcd docs..

### What do you see instead?

I see redshift page instead..

**Comment by carrodher** [comment]
Thanks for reporting the typo, we just updated it at https://github.com/bitnami/charts/commit/d57e505587e71d058bdce88ab16ca608da138dfb
