### ISSUE TITLE
[bitnami/geode] java.io.EOFException warning in server log

### ISSUE THREAD

**Issue by ojhughes** [bitnami/charts#9175]
### Name and Version

bitnami/geode 1.14.3
kubernetes 1.21 (GKE)
helm 3.7.2

### What steps will reproduce the bug?

Deploy chart using default settings `helm upgrade --install my-release bitnami/geode`

Wait for server pods to come up and check logs, a stack trace is shown in the logs

```
[warn 2022/02/23 12:07:19.895 UTC my-release-geode-server-0 <Handshaker 0.0.0.0/0.0.0.0:40404 Thread 2> tid=0x3f] Cache server: failed accepting client connection java.io.EOFException
java.io.EOFException
	at org.apache.geode.internal.cache.tier.sockets.AcceptorImpl.getCommunicationModeForNonSelector(AcceptorImpl.java:1569)
	at org.apache.geode.internal.cache.tier.sockets.AcceptorImpl.handleNewClientConnection(AcceptorImpl.java:1437)
	at org.apache.geode.internal.cache.tier.sockets.AcceptorImpl.lambda$handOffNewClientConnection$4(AcceptorImpl.java:1348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

I can still connect to the cluster with `gfsh` and see the cluster members using list-members 

### Are you using any custom parameters or values?

no just using defaults

### What is the expected behavior?

Not show any stack traces in the logs

### What do you see instead?

stack trace described above

**Comment by javsalgar** [comment]
Hi,

Could you let us know if this message appears several times or is something that appears only once? It could be a warning due to the configuration.

**Comment by ojhughes** [comment]
Hi the exception is logged repeatedly as long as the server is up. The cluster is operating correctly other than this logging

**Comment by javsalgar** [comment]
Could it be because of the liveness readiness probes? Could you try disabling them and see if the issue is there? It will help us to exactly track the cause of the issue and find a solution afterwards

**Comment by ojhughes** [comment]
I removed the liveness and readiness probes and as you say, the stack trace no longer appears in the log

**Comment by javsalgar** [comment]
Just a note to let you know that I was able to reproduce it. Indeed, the probes are adding noise to the logs, so I think we should revisit them. I will open a task for investigation.

Thank you so much for reporting!
