### ISSUE TITLE
[bitnami/solr] Implement possibility to load plugins

### ISSUE THREAD

**Issue by muffl0n** [bitnami/charts#9177]
### Name and Version

bitnami/solr 3.0.2

### What is the problem this feature will solve?

When trying to add a plugin (GCS in this example), there are some possibilities, that all feel pretty tedious:
* Create custom solrconfig.xml that includes the path of the plugin
* Copy plugin from "dist" to the "lib" directory by creating a custom Docker image
* Mount plugin as a Volume

### What is the feature you are proposing to solve the problem?

There should be a possibility to specify a list of plugins that is copied to the correct directory on Pod creation. As an alternative, there could be an insert into the generated solrconfig.xml

### What alternatives have you considered?

I considered building a custom Docker image. What seems like a good "quick fix" can get tedious on the long run. Also, there are for sure others that are asking themselves the same question on how to activate a plugin.

**Comment by tom-schoener** [comment]
The official HelmChart for the `SolrCloud` CRD has this feature, see https://github.com/apache/solr-operator/tree/main/helm/solr#running-solr -> `solrOptions.solrModules` and `solrOptions.additionalLibs`.
It would be great if you could edit the `solr.xml` configuration file within the `values.yaml` in some way or another.

**Comment by juan131** [comment]
Hi everyone!

I guess we can add support for mounting custom configuration files easily in the image as it's described in the link below:

- https://github.com/bitnami/bitnami-docker-solr#using-your-apache-solr-cores-configuration-files

Would you like to contribute with a PR adding this feature?

**Comment by muffl0n** [comment]
Look like it's already possible! I just added the env-var SOLR_OPTS with this value:
``` 
-Dsolr.sharedLib=/opt/bitnami/solr/contrib/s3-repository/lib/,/opt/bitnami/solr/dist/
```
Plugin is loaded and ready to be used.

Thank you very much for this awesome chart! ❤️

**Comment by juan131** [comment]
That's awesome @muffl0n !! Thanks so much for sharing this solution to load custom plugins.
