### ISSUE TITLE
[minio] minio distributed mode install error

### ISSUE THREAD

**Issue by clcc2019** [bitnami/charts#9187]
### Name and Version

bitnami/minio 10.1.9

### What steps will reproduce the bug?

![image](https://user-images.githubusercontent.com/46099295/155444912-e1b30209-8597-4290-bd73-5200cdc01e3d.png)
![image](https://user-images.githubusercontent.com/46099295/155445033-e7a9db27-3cc6-447a-9a6b-8218dda8bd25.png)

### Are you using any custom parameters or values?

--set mode: distributed
--set defaultBuckets: "bigdata"

### What do you see instead?

Error: Access Denied. (*errors.errorString)

**Comment by juan131** [comment]
Hi @clcc2019 

As it's mentioned in the **values.yaml** you can only use "defaultBuckets" in standalone mode, see:

- https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml#L109

You can try using the provisioning job instead when using the distributed mode:

- https://github.com/bitnami/charts/blob/master/bitnami/minio/values.yaml#L202
