### ISSUE TITLE
logstash-output-syslog plugin installation

### ISSUE THREAD

**Issue by miguelgmedina** [bitnami/charts#9193]
### Name and Version

bitnami/logstash-3.5.5

### What is the problem this feature will solve?

Hi, we need to install a logstash-output-syslog plugin in our logstash deployment. We are using bitnami logstash helm chart for that. We are studing two alternatives:
* Customize the original image to include that output plugin, upload that custom image to our internal container registry and modify the helm chart to point this custom image. We really don't like this becouse, when new chart releases with updated logstash version comes out, we will have to update our custom image.
* Use an initContainer to install the plugin as suggested in chart's readme file: https://github.com/bitnami/charts/tree/master/bitnami/logstash/ 
 But we don't know how to do it. We have used initContainers before for setting files uid/gid, but that is done on a persistent volume that remains when initContainer is complete. Could you please give us an example of how to accomplish this task?

Thank you in advance,
 Miguel

### What is the feature you are proposing to solve the problem?

Include an example in [README.md](https://github.com/bitnami/charts/blob/master/bitnami/logstash/README.md) of how to install logstash plugins using initContainers.

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
