### ISSUE TITLE
[bitnami/mariadb-galera] Add support for setting annotations on the statefulset PVCs

### ISSUE THREAD

**Issue by cwrau** [bitnami/charts#9195]
### Name and Version

bitnami/mariadb-galera 7.0.4

### What is the problem this feature will solve?

We want to continuously test our app, for that we want a clean slate on a daily basis. We kinda accomplished this with `kube-janitor`, which deletes our application, and `flux` redeploys it.

The only things leftover are the PVCs of the `mariadb-galera` helm chart. Which means the DB won't be clean.

 If we could set annotations on the PVC, we could easily set the `kube-janitor` annotation.

### What is the feature you are proposing to solve the problem?

Allow the user to set annotations for the PVCs

### What alternatives have you considered?

Sadly, none come to mind, we somehow mark the PVCs for deletion, but we can't add annotations or labels.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request! If want to speed up the process, feel free to submit a PR and we will review it :D
