### ISSUE TITLE
inconsistent values to specify prometheus rules between different charts

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#9197]
### Name and Version

bitnami/tomcat 10.1.10

### What steps will reproduce the bug?

one of the best feature of these charts is the consistency in values.yaml among the differents components.

I noticed that the templates for prometheusRule have slight differences :

tomcat : 
* guarded by `if and .Values.metrics.jmx.enabled .Values.metrics.prometheusRule.enabled` (notice the `metrics.jmx`)
* `spec.groups.0.name` is `common.names.name` 
* `spec.groups.0.rules` is rendered using `common.tplvalues.render`

ref: https://github.com/bitnami/charts/blob/master/bitnami/tomcat/templates/prometheusrule.yaml

zookeeper: 
* guarded by `if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled .Values.metrics.prometheusRule.rules`
* has label app.kubernetes.io/component: metrics
* `spec.groups.0.name` is `common.names.fullname` 
* `spec.groups.0.rules` is rendered using plain `toYaml`

ref: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/prometheusrule.yaml

thanos: 
* guarded by ` if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled` (same as zookeeper)
* whole `spec` is rendered using `common.tplvalues.render`

ref: https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/prometheusrule.yaml

postgres:
* guarded by `if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled` (same as zookeeper)
* has label app.kubernetes.io/component: metrics
* `spec.groups.0.name` is `common.names.fullname` (same as zookeeper)
* `spec.groups.0.rules` is rendered using `common.tplvalues.render` (same as tomcat)

ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/primary/prometheusrule.yaml

redis:
* guarded by `if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled` (same as zookeeper)
* `spec.groups.0.name is common.names.name` (same as tomcat)
* `spec.groups.0.rules` is rendered using plain `tpl toYaml`

ref: https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/prometheusrule.yaml

mongo:
* guarded by `if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled` (same as zookeeper)
* `spec.groups` is rendered using `common.tplvalues.render` (similar but different from thanos)

ref: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/prometheusrule.yaml

### Are you using any custom parameters or values?

--

### What is the expected behavior?

I would expect consistent `templates` and `values.yml`.

### What do you see instead?

--

### Additional information

--

**Comment by jouve** [comment]
If an option can be agreed, I can implement the changes.

**Comment by javsalgar** [comment]
I personally think the `postgresql` approach is the best among them
