### ISSUE TITLE
README.md link unworkable

### ISSUE THREAD

**Issue by u0324020** [bitnami/charts#9212]
### Name and Version

bitnami/thanos

### What steps will reproduce the bug?

In readme.md line:39, the [configuration](#configuration) not link to the appropriate session.

### What do you see instead?

maybe you mean [configuration](#Configuration and installation details)?

**Comment by javsalgar** [comment]
Hi!

Thanks for reporting! The link should be `#parameters`. Would you like to submit a PR fixing it?
