### ISSUE TITLE
err="getting metadata: fallback fetching info from xxx:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=xxx:10901

### ISSUE THREAD

**Issue by bab5470** [bitnami/charts#9213]
### Name and Version

thanos-9.0.6

### What steps will reproduce the bug?

Deploy bitnami Prometheus in a downstream cluster with a load balancer
Deploy Thanos in an aggregator cluster pointing to the Prometheus downstream cluster. 
Check the logs

### What is the expected behavior?

Thanos should be able to talk to Prometheus

### What do you see instead?

Thanos can't talk to Prometheus in one of our downstream clusters (other clusters work fine)

### Additional information

Changing from DNS name to IP address doesn't help. 
An nc works against the port:
```
nc -z -v xxxx 10901
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to xxxx:10901.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```
Deleting and reinstalling Thanos doesn't help
Deleting and reinstalling Prometheus doesn't help
Deleting and re-creating the load balancer VIP doesn't help

**Comment by bab5470** [comment]
How else can I troubleshoot why this isn't working? Why do my other downstream clusters work but this one doesn't? I've compared values.yml from other clusters they seem identical with the exception of the clusterLabel (Which should be different). There's obviously communication (See NC command above). This error is really generic and I can't seem to find much information on what causes it or what the problem might be.

**Comment by bab5470** [comment]
Cranking up debug logging for the thanos querier to LogLevel: debug hasn't resulted in any more verbose messages as to why its failing.

**Comment by bab5470** [comment]
Is there someway to exec into the container? I tried /bin/sh /bin/bash /bin/ash sh bash ash - nothing seems to work. I am not sure what shell or path the shell is in in this container.

**Comment by bab5470** [comment]
The issue we're encountering sounds suspiciously similar to this: https://discuss.konghq.com/t/grpc-request-block-at-the-proxy-level/6429

**Comment by bab5470** [comment]
Anyone have any ideas or suggestions?

**Comment by karthikeayan** [comment]
@bab5470 Just wanted to check if you found a solution for this, am also running into the same issue.
