### ISSUE TITLE
[bitnami/rabbitmq] With rabbitmq as a dependency, not able to create user reachable from main application

### ISSUE THREAD

**Issue by larsivi** [bitnami/charts#9214]
### Name and Version

bitnami/rabbitmq 8.29.2

### What steps will reproduce the bug?

Running in GCP Kubernetes
Inspired by https://techblog.commercetools.com/prisma-horizontal-scaling-a-practical-guide-3a05833d4fc3, but it is 4 or so years old, and pretty much none of the versions are relevant anymore.

I am setting up a chart for our prisma, that needs rabbitmq as a dependency.

There is a secret file, where I set up a password for the rabbitmq, copied to the setup for prisma.
In `values.yaml` try to create the user prisma-pubsub under rabbitmq:auth

The end result is that prisma tries to connect, but is refused with a message about wrong credentials.

### Are you using any custom parameters or values?

My `values.yaml` is more or less like the one on the above link,  notably with a setup like
```yaml
rabbitmq:
  rabbitmq:
    auth:
    persistence:
    etc:
```
props-for-my-chart

I also tried setting username via `--set`, with slightly different, but still not good results

### What is the expected behavior?

That I am able to create a user and set password, such that I can create the proper login link in my `secrets.yaml`, that is
```yaml
prisma:
  rabbitmqconnector: amqp://prisma-pubsub:xxx@prisma-cluster-rabbitmq:5672
```
and then have prisma be able to login to rabbitmq

It is my impression that this worked in the chart described in the link, but that chart has a version of 2.something

### What do you see instead?

All nodes startup and connect as expected, except for the rabbitmqconnector. The attempt is made, but is refused.

Looking at the container in the Google Console, I can see that the username in the `RABBITMQ_USERNAME` env variable is user if I _don't_ use `--set`, but is in fact prisma-pubsub if I use --set.

`RABBITMQ_PASSWORD` is according to the env variable set to a secret, but not (I think) mine. Extracting the password with `kubectl` it does appear to not be the one I try to set in the `secrets.yaml`.

### Additional information

I am inexperienced with both Kubernetes, Helm and Rabbitmq (but do know Prisma well), so I am almost certain that I have made a mistake somehow, but I really need help in understanding what it is.

Using helm, I have both gone the upgrade route and fresh install route.

**Comment by carrodher** [comment]
Please note the different instructions for the current latest version of the bitnami/rabbitmq Helm chart are present in the [README.md file](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq). If you want to follow external documentation using an old Helm chart you can install a previous version of this helm chart by running `helm install my-rabbit bitnami/rabbitmq --version X.Y.Z`

**Comment by larsivi** [comment]
> Please note the different instructions for the current latest version of the bitnami/rabbitmq Helm chart are present in the [README.md file](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq). If you want to follow external documentation using an old Helm chart you can install a previous version of this helm chart by running `helm install my-rabbit bitnami/rabbitmq --version X.Y.Z`

Thank you! Wrong structure was indeed the issue (and also messed up those that persistent storage). It works now :)
