### ISSUE TITLE
Airflow broken LocalExecutor deployment

### ISSUE THREAD

**Issue by mypa** [bitnami/charts#9220]
### Name and Version

bitnami/airflow 12.0.5

### What steps will reproduce the bug?

1. In a local k8s cluster
2. when installing a Helm release of bitnami/airflow with `executor=LocalExecutor` or `executor=SequentialExecutor`

### What is the expected behavior?

Helm installs an Airflow release using the local executor settings

### What do you see instead?

Helm will not install due to
```
Normal  error  5m33s                helm-controller  Helm upgrade failed: error validating "": error validating data: ValidationError(Service.spec.ports[0]): missing required field "port" in io.k8s.api.core.v1.ServicePort
```
### Additional information

Bug fix:
in `scheduler/service-headless.yaml` set port: `{{ .Values.worker.containerPorts.http }}` instead of port: `{{ .Values.worker.port }}` (which is not defined in values.yaml anymore)

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
