### ISSUE TITLE
[bitnami/contour] auto refresh tls cert before it expires in 365 days

### ISSUE THREAD

**Issue by rohilsurana** [bitnami/charts#9224]
### Name and Version

bitnami/contour 7.3.11

### What is the problem this feature will solve?

Currently the TLS cert used for communication between envoy and contour pods has an expiry of 365 days(certgen default). For releases that are not updated in that time this makes config calls fail b/w contour and envoy pods since the helm hook is set to `pre-install, pre-upgrade`

### What is the feature you are proposing to solve the problem?

Add a cronjob that refreshes the certificate periodically. That would mean changing this job to a cron - [job.yaml](https://github.com/bitnami/charts/blob/master/bitnami/contour/templates/certgen/job.yaml) or adding another one.

### What alternatives have you considered?

Increase the certs lifetime using `certgen` flag `certificate-lifetime`. Right now the chart does not expose this flag as a config.

**Comment by javsalgar** [comment]
Hi,

In my opinion, exposing the certificate-lifetime parameter makes more sense to me that adding an extra cron job deployment. Would you like to submit a PR exposing this parameter in the chart?

**Comment by rohilsurana** [comment]
Sounds good. Let me give this a try.

**Comment by juan131** [comment]
Thanks @rohilsurana ! I just accepted/merged your PR, we really appreciate your time.
