### ISSUE TITLE
[bitnami/redis] latest is broken for a fresh deployment of redis-sentinel

### ISSUE THREAD

**Issue by jack1902** [bitnami/charts#9227]
### Name and Version

bitnami/redis 16.4.4

### What steps will reproduce the bug?

1. helm upgrade -i bitnami/redis --version 16.4.4 --set 'auth.enabled=false,sentinel.enabled=true'
2. observe `redis-node-0` never coming up

This is because a `timeout` has been removed from the script which ensures that the script can continue in this commit: https://github.com/bitnami/charts/commit/d6d66f1458cd7793691d4ea8d1c44da004f9b89d

### Are you using any custom parameters or values?

auth.enabled = false
sentinel.enabled=true

### What is the expected behavior?

A 3 node redis cluster to come online with sentinel working

### What do you see instead?

`INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster`

Will hang indefinitely and eventually the pod will be restarted due failing a liveness probe.

### Additional information

re-adding `timeout 5` to the relevant line fixes the issue, I've resorted to using `16.4.0` as all versions above this are currently broken. Removal of such a flag in a cli IMHO warrents a breaking change, not a "bugfix" version bump as it hides the meat of the work going on under the hood of the chart.

**Comment by jack1902** [comment]
caused by: https://github.com/bitnami/charts/pull/9169

**Comment by jack1902** [comment]
So running `redis-cli` will have a default timeout of 2 minutes according to the following output:

```
I have no name!@redis-client:/$ time redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at redis.default.svc.cluster.local:26379: Connection timed out

real    2m10.075s
user    0m0.003s
sys     0m0.000s
```

**Comment by jack1902** [comment]
looking at the logs, by adding a `startupProbe` with an initialDelay of 220 then it eventually comes online but this is significantly slower than the previous `5` seconds and still runs the risk of having 3 masters running.

```
INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at redis.default.svc.cluster.local:26379: Connection timed out
1:X 28 Feb 2022 15:23:27.103 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 28 Feb 2022 15:23:27.103 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 28 Feb 2022 15:23:27.103 # Configuration loaded
```

values.yaml for reference

```yaml
auth:
  enabled: false

sentinel:
  enabled: true
  startupProbe:
    enabled: true
    initialDelaySeconds: 220

replica:
  startupProbe:
    enabled: true
    initialDelaySeconds: 220
```

**Comment by alemorcuq** [comment]
Hi, @jack1902. Could you please explain this multimaster risk without the timeout command?

**Comment by jack1902** [comment]
so looking at https://github.com/bitnami/charts/issues/8851 , the "fix" was to increase the timeout from the set `5 seconds` to the default 2 minutes which is how long it takes for the command `redis-cli ....` to timeout by default.

No matter what the timeout is, 5 seconds or 2 minutes you still run a risk of multiple masters (as per the linked issue, they observed this when the timeout was 5 seconds but now the chart is extremely slow to deploy OOB as compared to before)

Multi-master ideally is avoided by the `quorum` being set for `sentinel` (if there are 3 nodes, and a quorum of 2 candidates state one of them can become the master, the remaining node that might of suffered a network split can't become the master as it doesn't have a quorum of votes)

Unsure of a smooth way forward but I'm now finding that between 16.4.0 and 16.4.4 a deployment time OOB has increased to +5 minutes which breaks a default helm install without the `--timeout` being increased

**Comment by ndd7xv** [comment]
Having the `timeout 5` seemed to have sporadically caused errors, but it's clear that a 220 second wait definitely increases deployment time. 

If we modify the startup probe to use something like `failureThreshold: 22` and `periodSeconds: 10` as opposed to `initialDelaySeconds: 220` (so liveness/readiness probes start the moment it succeeds as opposed to always waiting 220 seconds) would that improve the deployment times? Perhaps we could account for (or remove) any `initialDelaySeconds` for the liveness and readiness probes as well (if the delay count starts after the startupProbe, which I'm unsure about).

I'm not sure if we should re-add a 5 second timeout since it has caused an issue (and I agree with the sentiment of https://github.com/bitnami/charts/issues/8851#issuecomment-1047910838), but if it's necessary then maybe could the timeout be bumped up to something like 15 or 20 seconds?

**Comment by ndd7xv** [comment]
Also, did you conflate 220 seconds (3m40s) with 2 minutes and 20 seconds, or was that the lowest `initialDelaySeconds` you got to work? I've tried creating an interval of 150 seconds (2m30s), and I'm able to successfully deploy Redis, though I can see how our results could vary for many other reasons.

**Comment by jack1902** [comment]
🤣  i may or may not have confused 220 for 2 minutes 20 as I was briefly looking at updating the version of the redis chart whilst doing some other bits.

Either way, if the `timeout 5` causes other issues then the startupProbe might be better to check quick but only fail after a long period of time to enable the other pods to come online pretty quickly. This doesn't alleviate the "first" deployment or a full cluster restart (an old issue existed whereby if more than one pod was "up" in the headless service then no one would attempt to become the master hence the timeout being used instead).

Unsure of how to ensure that the first `pod` that comes up doesn't have to wait a whole 2 minutes to then become the master, perhaps adding the check of `am I the only pod` back could work here. This would mean the following cases are covered:

- First install of the chart - check if only one pod and assume master ?
- Fully restarting a cluster / Cluster outage - Means that you would wait 2 minutes before someone became the master as non would be reachable
- upgrades of the chart - Master is reachable so would only be waiting whatever the time set for the startupProbe is

Quoting from the k8s docs:

> The kubelet uses startup probes to know when a container application has started. If such a probe is configured, it disables liveness and readiness checks until it succeeds, making sure those probes don't interfere with the application startup. This can be used to adopt liveness checks on slow starting containers, avoiding them getting killed by the kubelet before they are up and running.

Source: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by paulden** [comment]
Thanks @jack1902 for raising this issue, we are encountering the same problem during a fresh Redis install using this chart at version >= 16.4.1 (while using version prior to the deletion of the `timeout 5` does not raise any issue).

I understand the reason why the `timeout 5` was removed but I feel like either way there has to be some mechanism where at some point, no response means you assume the master role (which is now defaulting to the 2 minutes timeout). Adding a parameter to control the timeout as suggested by @alemorcuq seems to be a way to ensure people may adjust that to their network issues.

**Comment by juan131** [comment]
I agree that parametrizing the parameters the timeout would be the best option. Would you like to contribute a PR adding support for a parameter that allows modifying the timeout?

**Comment by jack1902** [comment]
Why not add two bits?

`startupProbe` for those that want the 220 bit but enable the `timeout` to be also set as a separate piece? This way the default is happy and you can tune it down if you want?

**Comment by alemorcuq** [comment]
> Why not add two bits?
> 
> `startupProbe` for those that want the 220 bit but enable the `timeout` to be also set as a separate piece? This way the default is happy and you can tune it down if you want?

Yes, we could do both. We can fine tune the default values for the `startup probe` (as suggested by @ndd7xv) and also support a customizable timeout for the command. Would you be interested in contributing with a PR?
