### ISSUE TITLE
How can I add a license file to ElasticSearch and  add xpack.encryptedSavedObjects.encryptionKey setting

### ISSUE THREAD

**Issue by evhfla** [bitnami/charts#9233]
### Name and Version

bitnami/elasticsearch-17.9.1

### What steps will reproduce the bug?

Deploy bitnami/ElasticSearch chart to AKS Cluster.

### What do you see instead?

No way that I can see to do it.

**Comment by rafariossaa** [comment]
Hi,
  I think you could use the `config` or `extraConfig` [parameters](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#user-content-elasticsearch-parameters).
