### ISSUE TITLE
Key Rotation for RabbitMQ

### ISSUE THREAD

**Issue by thesmashburn** [bitnami/charts#9244]
### Name and Version

bitnami/rabbitmq

### What is the problem this feature will solve?

Since credentials are persisted, doing a helm upgrade with credentials pointing to existing secrets will not rotate the keys. For security reasons, I would like to be able to rotate my keys periodically using helm.

### What is the feature you are proposing to solve the problem?

Is there a way to trigger a force rotate of some kind without deleting the persisted volumes? This would be ideal.

**Comment by miguelaeh** [comment]
Hi @thesmashburn ,
You would need to use the standard rabbitmq process for performing such rotation.
