### ISSUE TITLE
[bitnami/mariadb-galera] Renaming prometheusRule.selector is not applied

### ISSUE THREAD

**Issue by truhojun** [bitnami/charts#9248]
### Name and Version

bitnami/mariadb-galera 7.0.6

### What steps will reproduce the bug?

apply following values.yaml
```mariadb-galera:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      additionalLabel:
        app: kube-prometheus-stack
        release: my-prometheus-stack
      rules:
        - alert: MariaDB-Down
          annotations:
            message: 'MariaDB instance {{ $labels.instance }} is down'
            summary: MariaDB instance is down
          expr: absent(up{job="mariadb-galera"} == 1)
          labels:
            severity: warning
            service: mariadb-galera
          for: 5m
```

### What is the expected behavior?

Prometheus rule registered

### What do you see instead?

Prometheus rule not registered

### Additional information

According to upgrade [guide to 7.0.0](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera#to-700)
`prometheusRule.selector` has been renamed to `prometheusRule.additionalLabels`
And this also applied to [`templates/prometheusrules.yaml`](https://github.com/bitnami/charts/blob/915c246fa7bfb637cdd38b6deaff6ede142c232d/bitnami/mariadb-galera/templates/prometheusrules.yaml#L10)

However, the name of it still remains as [`selector`](https://github.com/bitnami/charts/blob/915c246fa7bfb637cdd38b6deaff6ede142c232d/bitnami/mariadb-galera/values.yaml#L897)

**Comment by alemorcuq** [comment]
Looks like you are setting `additionalLabel` instead of `additionalLabels`, can you check that?

**Comment by truhojun** [comment]
Oh it was mistake. 
But even I fix it to `additionalLabels`, it is same.
Anyway, `prometheusRule.selector` in the values file seems to have to be fixed

**Comment by truhojun** [comment]
Anyone can help?

**Comment by alemorcuq** [comment]
Could you check #9600? It solves some bugs in the rule creation. Also, note that in your custom values you are using `prometheusRule` while it should be `prometheusRules`.

**Comment by truhojun** [comment]
@alemorcuq 
It works properly.
Thank you very much.
