### ISSUE TITLE
[stable/redis] crashLoopBackoff using more than 1 extraFlags

### ISSUE THREAD

**Issue by alessiopiazza** [bitnami/charts#926]
Hi guys, looks like the last stable redis chart fails to start if more than 1 extraFlag is passed

This runs fine:
`helm  upgrade --install redis stable/redis --set master.extraFlags[0]="--maxmemory 256mb"`

and redis throws a warning indicating that REDIS_EXTRA_FLAGS is deprecated
```
INFO  ==> ** Starting Redis setup **
INFO  ==> Initializing Redis...
INFO  ==> Configuring replication mode...
INFO  ==> ** Redis setup finished! **

WARN  ==> REDIS_EXTRA_FLAGS is deprecated. Please specify any extra-flag using '/run.sh --maxmemory 256mb' as command instead
INFO  ==> ** Starting Redis **
```

When trying to set more than 1 extraFlag redis pod goes in crashLoopBackoff, due to a config file error

`helm  upgrade --install redis stable/redis --set master.extraFlags[0]="--maxmemory 256mb" --set master.extraFlags[1]="--maxmemory-samples 5"`

```INFO  ==> ** Starting Redis setup **
INFO  ==> Initializing Redis...
INFO  ==> Configuring replication mode...
INFO  ==> ** Redis setup finished! **

WARN  ==> REDIS_EXTRA_FLAGS is deprecated. Please specify any extra-flag using '/run.sh --maxmemory 256mb --maxmemory-samples 5' as command instead
INFO  ==> ** Starting Redis **

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1322
>>> 'maxmemory 256mb --maxmemory-samples 5'
Bad directive or wrong number of arguments
```

looks like something is wrong wit the concatenation passed to `/run.sh`. The only thing i see so far is that the first argument looses the `--` (but it could be just a logging issue...)
Am i the only having this issue?

**Comment by alessiopiazza** [comment]
It looks like this is not an issue of redis chart itself.
The same error appens wit the last bitnami/redis docker image, even though everything was fine with this hash `8b87072b616764b00f6f7e097b4c0d3a6325a5f0b077974b2a1e353d3b53846b`

**Comment by juan131** [comment]
Hi @alessiopiazza 

Thanks for reporting the issue. We're currently discussing the solution on this PR: https://github.com/bitnami/bitnami-docker-redis/pull/127
