### ISSUE TITLE
Moodle prob endpoints creates a new session each seconds which stored in a db...

### ISSUE THREAD

**Issue by yelhouti** [bitnami/charts#9265]
### Name and Version

bitnami/moodle:12.1.10

### What steps will reproduce the bug?

just install the chart and check:
SELECT COUNT(*) FROM mdl_sessions;

### What is the expected behavior?

probes should be as minimal as possible by default

### What do you see instead?

unjustified disk usage

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
