### ISSUE TITLE
bitnami/common Still validating old postgresql 10.x chart

### ISSUE THREAD

**Issue by MrKrabat** [bitnami/charts#9277]
### Name and Version

bitnami/keycloak 7.0.0

### What steps will reproduce the bug?

1. Install bitnami/keycloak 7.0.0
2. Do a `helm upgrade`

### Are you using any custom parameters or values?

I am using an existing secret.

```yaml
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: ""
    database: bitnami_keycloak
    existingSecret: "keycloak"
```

### What is the expected behavior?

Upgrade should work.

### What do you see instead?

```
Error: UPGRADE FAILED: execution error at (keycloak/templates/NOTES.txt:91:4): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'postgresql.postgresqlPassword' must not be empty, please add '--set postgresql.postgresqlPassword=$POSTGRESQL_PASSWORD' to the command. To get the current value:

        export POSTGRESQL_PASSWORD=$(kubectl get secret --namespace "keycloak" keycloak -o jsonpath="{.data.postgresql-password}" | base64 --decode)
```

### Additional information

If you have a look at https://github.com/bitnami/charts/blob/master/bitnami/common/templates/validations/_postgresql.tpl
This file has not been updated to work with the new Bitnami PostgreSQL helm chart version 11.

**Comment by fmulero** [comment]
Hi @MrKrabat  thanks a lot for sharing this issue.

I've just created a PR to amend this issue in keycloak chart using a different approach, with new version that validation is not needed anymore.  The goal is remove that dependency in new or revisited charts.
