### ISSUE TITLE
[bitnami/haproxy] loadBalancerIP is not used though documented

### ISSUE THREAD

**Issue by paulden** [bitnami/charts#9285]
### Name and Version

bitnami/haproxy 0.3.7

### What steps will reproduce the bug?

- Set `service.loadBalancerIP`.
- No impact on the service created.

### Are you using any custom parameters or values?

```
service:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.2
```

### What is the expected behavior?

The loadBalancerIP is actually set to 10.0.0.2.

### What do you see instead?

loadBalancerIP is not set.

### Additional information

Suggested MR to fix this : https://github.com/bitnami/charts/pull/9284

**Comment by juan131** [comment]
Thanks for reporting the issue and address it @paulden !!
