### ISSUE TITLE
failed to set primary.persistence.existingClaim  variable and build default pvc

### ISSUE THREAD

**Issue by AhmedSRamadan** [bitnami/charts#9292]
### Name and Version

bitnami/postgresql 11.1.3

### What steps will reproduce the bug?

1- create namespace then PV then PVC
2- run helm with setting PVC parameter 
```
$ kubectl create namespace postgresql
$ kubectl apply -f postgresql-pv-0.yaml
$ kubectl apply -f postgresql-pvc-0.yaml
$ helm install postgresql bitnami/postgresql -n postgresql \
    --set primary.persistence.existingClaim=postgresql-pvc-0 \
    --set volumePermissions.enabled=true \
    --set global.postgresql.auth.postgresPassword=xxxxxx
```    

3- Pod pending because of
```
 pod has unbound immediate PersistentVolumeClaims.
```

4- another pvc creating but not bounded because this error 
```
called no persistent volumes available for this claim and no storage class is set
```    

### Are you using any custom parameters or values?
```
helm install postgresql bitnami/postgresql -n postgresql \
    --set primary.persistence.existingClaim=postgresql-pvc-0 \
    --set volumePermissions.enabled=true \
    --set global.postgresql.auth.postgresPassword=xxxxxx
```

### What is the expected behavior?

pod running because of bound PVC I created before running the helm and set it in claim parameter

### What do you see instead?

I see pod pending 
I see default PVC created with this name `data-postgresql-postgresql-0`

### Additional information

N/A

**Comment by marcosbc** [comment]
Hi @AhmedSRamadan, it seems like in your case you may want to look into affinity/anti-affinity options: https://github.com/bitnami/charts/tree/master/bitnami/postgresql

Also see https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/

**Comment by AhmedSRamadan** [comment]
Hi @marcosbc 
Thanks for answering me I installed everything in one namespace and worked with bitnami mysql and mongoddb fine but not working with postgresql
this variable --set primary.persistence.existingClaim=postgresql-pvc-0 not working and create default pvc called data-postgresql-postgresql-o
Kind Regards,
Ahmed

**Comment by jasonyihk** [comment]
I am having the same issue. set `existingClaim: data-postgresql` does not work and statefulset still keep using the default PVC, wihich is `data-postgresql-0`

**Comment by AhmedSRamadan** [comment]
Hello @marcosbc 
I think it's not related to node anfinity it's even igonre the postgresql password values

**Comment by marcosbc** [comment]
@AhmedSRamadan Could you share `postgresql-pv-0.yaml` and `postgresql-pvc-0.yaml` so we can reproduce this issue? Note that you should need to specify the namespace in those YAMLs.

**Comment by AhmedSRamadan** [comment]
Hello @marcosbc ,
Case solved after adding this env variable --set primary.primary.enabled=true  
and also for the password fixed by add this env value  --set auth.postgresPassword=xxxx
