### ISSUE TITLE
Can't helm install redis helm chart

### ISSUE THREAD

**Issue by Docteur-RS** [bitnami/charts#9302]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

```console
$ helm install my-redis bitnami/redis/
Error: INSTALLATION FAILED: failed to download "bitnami/redis/"
```

It seems that the trailing slash is not supported as mentioned in the readme.

### What is the expected behavior?

Helm chart should begin to install

### What do you see instead?
```
Error: INSTALLATION FAILED: failed to download "bitnami/redis/"
```
### Additional information

Remove trailing shlash to fix
```
$ helm install my-redis bitnami/redis/
...
Happy helming
```

Using helm v3.7.0

**Comment by carrodher** [comment]
This is not an issue of the chart but how the Helm CLI is designed, you need to remove the trailing slash from your call:
```console
$ helm install my-release bitnami/redis
```

If you think the trailing slash should be supported by the Helm CLI, please create an issue in the https://github.com/helm/helm repo
