### ISSUE TITLE
Upgrade of the postgresql version from 11.15 to 12 or 13

### ISSUE THREAD

**Issue by InderpreetSaini** [bitnami/charts#9306]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

Hi,
We are planning to deploy the Postgresql Bitnami HA Helm chart for our Postgres DB requirement. Currently the Postgresql version supported by it is 11.15. 

Is there a plan to upgrade it to a newer version, probably 12 or 13 in near future? 

Thanks and Regards,
Inderpreet.

### What do you see instead?

NA

**Comment by juan131** [comment]
Hi @InderpreetSaini 

Yes, we have plan to upgrade to PostgreSQL 14 as the default image. In any case, please note that we build the `bitnami/postgresql-repmgr` for every branch from 10 to 14, see:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr

Therefore, you can easily install the `bitnami/postgresql-ha` by setting the `postgresqlImage.tag` parameter. For instance:

```bash
helm install postgresql-ha bitnami/postgresql-ha --set postgresqlImage.tag=13
```

**Comment by InderpreetSaini** [comment]
> Hi @InderpreetSaini
> 
> Yes, we have plan to upgrade to PostgreSQL 14 as the default image. In any case, please note that we build the `bitnami/postgresql-repmgr` for every branch from 10 to 14, see:
> 
> * https://github.com/bitnami/bitnami-docker-postgresql-repmgr
> 
> Therefore, you can easily install the `bitnami/postgresql-ha` by setting the `postgresqlImage.tag` parameter. For instance:
> 
> ```shell
> helm install postgresql-ha bitnami/postgresql-ha --set postgresqlImage.tag=13
> ```

Thanks @juan131 . I will give it a try.
