### ISSUE TITLE
Sync CRDs version of contour ingress

### ISSUE THREAD

**Issue by lou-lan** [bitnami/charts#9308]
### Name and Version

[bitnami/contour] 7.4.1

### What steps will reproduce the bug?

Fix https://github.com/projectcontour/contour/issues/4374

### What do you see instead?

The app version is updated, but the crd is not.

### Additional information

PR: https://github.com/bitnami/charts/pull/9309

**Comment by javsalgar** [comment]
Hi! 

Thank you so much for the PR! The team will take a look
