### ISSUE TITLE
Access Kafka behind k8s service 

### ISSUE THREAD

**Issue by Zero-2** [bitnami/charts#931]
Hi all,
i installed kafka on azure k8s cluster.
Now i want to expose it to the internal network.
I added a new service to obtain an internal ip via an internal load balancer using Azure annotation : 
> annotations:
>     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
It works and service take an internal ip.
Now when i try to connect to kafka cluster using kafka examples i'm able to see the topic list:

> ./kafka-topics.sh --list --zookeeper xx.yy.zz.tt:2181

But if i try to use another example i give some errors:

>  ./kafka-consumer-perf-test.sh --broker-list xx.yy.zz.tt:9092 --topic test --messages 10
> start.time, end.time, data.consumed.in.MB, MB.sec, data.consumed.in.nMsg, nMsg.sec, rebalance.time.ms, fetch.time.ms, fetch.MB.sec, fetch.nMsg.sec
> [2018-11-19 13:39:27,803] WARN [Consumer clientId=consumer-1, groupId=perf-consumer-16314] Connection to node 2147482644 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
> [2018-11-19 13:39:48,910] WARN [Consumer clientId=consumer-1, groupId=perf-consumer-16314] Connection to node 1003 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
> [2018-11-19 13:40:09,916] WARN [Consumer clientId=consumer-1, groupId=perf-consumer-16314] Connection to node 1001 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
> [2018-11-19 13:40:30,921] WARN [Consumer clientId=consumer-1, groupId=perf-consumer-16314] Connection to node 1002 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
> [2018-11-19 13:40:51,923] WARN [Consumer clientId=consumer-1, groupId=perf-consumer-16314] Connection to node 1001 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

How i should configure kafka in order to do that?
One service for each broker and zookeeper? 
Or other config is needed?

Thanks in advance.

**Comment by javsalgar** [comment]
Hi,

I am not 100% sure, but I think that all kafka nodes must be reachable. Are you able to access when you are using a pod inside the Kubernetes cluster?

**Comment by lonyele** [comment]
Hi, I have a same problem.
I'm using Window with Docker's kubernetes. I could access to kafka node inside of k8s cluster by "my-release-kafka.default.svc.cluster.local:9092" as the NOTES.txt said.  
However I couldn't reach it outside of cluster. I port-forwarded as the instruction, but I couldn't access it.
I tried both default ClusterIp and NodePort.  
Here is the error from kafka-console-producer.bat.

> WARN [Producer clientId=console-producer] Connection to node 1001 (/10.1.0.213:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

From my consumer client.

> 'Broker not available: Broker socket is closed - connect ETIMEDOUT 10.1.0.213:9092'

Here is the result of `kubectl describe service my-release-kafka`

> Name:                     my-release-kafka
> Namespace:                default
> Labels:                   app=kafka
>                           chart=kafka-1.2.1
>                           heritage=Tiller
>                           release=my-release
> Annotations:              <none>
> Selector:                 app=kafka,release=my-release
> Type:                     NodePort
> IP:                       10.98.91.242
> LoadBalancer Ingress:     localhost
> Port:                     kafka  9092/TCP
> TargetPort:               kafka/TCP
> NodePort:                 kafka  30266/TCP
> Endpoints:                10.1.0.213:9092
> Session Affinity:         None
> External Traffic Policy:  Cluster
> Events:                   <none>

I tried to connect kafka from client by localhost:9092, 127.0.0.1:9092, 192.168.65.3:9092, 192.168.65.3:30266     
Since connecting to kafka inside of k8s cluster works fine, I've done something wrong with either Service.yaml or port-forwarding(I guess)
