### ISSUE TITLE
SonarQube TLS secret not hard coded to hostname

### ISSUE THREAD

**Issue by haydockjp** [bitnami/charts#9326]
### Name and Version

bitnami/sonarqube 1.0.0

### What is the problem this feature will solve?

In the ingress configuration for TLS uses the `hostname` for the `secretName`

I have several subdomains on the same certificate and would like to use the same certificate for all of the ingress configurations

```
  tls:
    {{- if and .Values.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )) .Values.ingress.selfSigned) }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
```

### What is the feature you are proposing to solve the problem?

Could you have this as the default, but allow for TLS a way to override it?

**Comment by haydockjp** [comment]
There is a workaround for this, but I don't like using it

```
    hostname: subdomain.domain.com

    extraTls: [
      {
        hosts: [ subdomain.domain.com ],
        secretName: secretname
      }
    ]
```

**Comment by miguelaeh** [comment]
Hi @haydockjp ,
Looks like what you describe is useful in that particular scenario. We provide general-purpose charts, with several configuration options to be fully customizable. As you stated, you can easily configure that using the `extraTls`. Feel free to open a PR if you consider and we will review it.
