### ISSUE TITLE
Add on-premise pod/node

### ISSUE THREAD

**Issue by atunbey** [bitnami/charts#9328]
### Name and Version

Odoo 15

### What is the problem this feature will solve?

I have a odoo installation in azure using kubernetes. can i extend my cluster to include a pod/node on-premise.

### What is the feature you are proposing to solve the problem?

Have a local install using the pos and the cloud running the website.  local could lose internet and still process transactions and then sync up when connection is available again.

### What alternatives have you considered?

KubeEdge

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
