### ISSUE TITLE
Elasticsearch Chart (17.9.8) has many Deprecated values

### ISSUE THREAD

**Issue by metalshanked** [bitnami/charts#9329]
### Name and Version

bitnami/elasticsearch 17.9.8

### What is the problem this feature will solve?

Elastic version 8.x is here and below are few of deprecated items i see in this chart.

![2022-03-07_19-00-46](https://user-images.githubusercontent.com/57646596/157151697-6d9536f1-c849-4d75-8158-8cd6a3b5f3dd.png)

### What is the feature you are proposing to solve the problem?

Will there be chart updates to set the non deprecated versions?

**Comment by alemorcuq** [comment]
Hi, @metalshanked.

Thanks for this. We haven't released a chart for ES 8 yet. I'll redirect this to the appropriate team so they can take it into account.
