### ISSUE TITLE
Document update

### ISSUE THREAD

**Issue by g0pinath** [bitnami/charts#9332]
### Name and Version

thanos:0.25.0

### What steps will reproduce the bug?

Please update https://github.com/bitnami/charts/blob/master/bitnami/thanos/values.yaml#L365-L367 as below
```yaml
      ## @param query.grpc.client.servername Server name to verify the hostname on the returned GRPC certificates
      ##
      servername: ""
```

Capitalized N is not being picked and applied on the query args.
https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query/deployment.yaml#L148-L149 
The above is looking for servername and NOT serverName.

### What do you see instead?

`--grpc-client-server-name=thanos-storegateway.monitor.svc.cluster.local` -- this wont get created when using serverName

**Comment by carrodher** [comment]
Thanks for reporting this issue, I think the change should be in the other direction, keeping `serverName` in the _values.yaml_ but update the deployment template to use the proper value.

Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
