### ISSUE TITLE
DML query hangs indefinitely when synchronous_commit is set to on

### ISSUE THREAD

**Issue by InderpreetSaini** [bitnami/charts#9336]
### Name and Version

bitnami/postgresql-ha

### What steps will reproduce the bug?

Hi,

This is the same issue which is mentioned in [https://github.com/bitnami/charts/issues/1414]. 

I am using the postgres 13.5 image to deploy Postgres HA Helm chart (bitnami/postgresql-repmgr:13.5.0-debian-10-r35).

Synchronous_commit is set to on in this image by default. I have enable syncReplication to true in my Helm chart configuration.

PgPool - 3 pods
Postgres -3 pods

When I am executing any CREATE/INSERT/DROP query by logging into the pod using psql client, the query hangs indefinitely and I have to do Ctrl+C to come out of it.

If I set Synchronous_commit to off in the extendedConf, the query works fine.

### What do you see instead?

NA

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue:

```
❯ helm install psql bitnami/postgresql-ha --set postgresql.syncReplication=true

❯ kubectl exec -ti psql-postgresql-ha-postgresql-0 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@psql-postgresql-ha-postgresql-0:/$ PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres
psql (11.15)
Type "help" for help.

postgres=# select * from pg_stat_replication;
 pid | usesysid | usename |        application_name         | client_addr |        client_hostname
| client_port |         backend_start         | backend_xmin |   state   | sent_lsn  | write_lsn | flush_ls
n | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+---------------------------------+-------------+--------------------------------
+-------------+-------------------------------+--------------+-----------+-----------+-----------+---------
--+------------+-----------+-----------+------------+---------------+------------
 376 |    16384 | repmgr  | psql-postgresql-ha-postgresql-1 | 10.0.0.145  | demo2.intranet.hyperic.net
|       60490 | 2022-03-09 09:07:06.648645+00 |              | streaming | 0/7001118 | 0/7001118 | 0/700111
8 | 0/7001118  |           |           |            |             2 | sync
 381 |    16384 | repmgr  | psql-postgresql-ha-postgresql-2 | 10.0.0.158  | vmlin-012.intranet.hyperic.net
|       43756 | 2022-03-09 09:07:06.960326+00 |              | streaming | 0/7001118 | 0/7001118 | 0/700111
8 | 0/7001118  |           |           |            |             3 | sync
(2 rows)

postgres=# create database test;
CREATE DATABASE
postgres=# \c test;
You are now connected to database "test" as user "postgres".
test=# CREATE TABLE films (
test(#     code        char(5),
test(#     title       varchar(40),
test(#     did         integer,
test(#     date_prod   date,
test(#     kind        varchar(10),
test(#     len         interval hour to minute,
test(#     CONSTRAINT production UNIQUE(date_prod)
test(# );
CREATE TABLE
test=#
test=# CREATE TABLE links (
test(# id SERIAL PRIMARY KEY,
test(# url VARCHAR(255) NOT NULL,
test(# name VARCHAR(255) NOT NULL,
test(# description VARCHAR (255),
test(#         last_update DATE
test(# );
CREATE TABLE
test=#
test=# INSERT INTO links (url, name)
test-# VALUES('https://www.postgresqltutorial.com','PostgreSQL Tutorial');
INSERT 0 1
test=#
test=#
test=# SELECT * FROM links;
 id |                url                 |        name         | description | last_update
----+------------------------------------+---------------------+-------------+-------------
  1 | https://www.postgresqltutorial.com | PostgreSQL Tutorial |             |
(1 row)

```

Could you provide more details about the values.yaml you used and the Kubernetes platform?

**Comment by InderpreetSaini** [comment]
> Hi,
> 
> I was unable to reproduce the issue:
> 
> ```
> ❯ helm install psql bitnami/postgresql-ha --set postgresql.syncReplication=true
> 
> ❯ kubectl exec -ti psql-postgresql-ha-postgresql-0 bash
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
> I have no name!@psql-postgresql-ha-postgresql-0:/$ PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres
> psql (11.15)
> Type "help" for help.
> 
> postgres=# select * from pg_stat_replication;
>  pid | usesysid | usename |        application_name         | client_addr |        client_hostname
> | client_port |         backend_start         | backend_xmin |   state   | sent_lsn  | write_lsn | flush_ls
> n | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
> -----+----------+---------+---------------------------------+-------------+--------------------------------
> +-------------+-------------------------------+--------------+-----------+-----------+-----------+---------
> --+------------+-----------+-----------+------------+---------------+------------
>  376 |    16384 | repmgr  | psql-postgresql-ha-postgresql-1 | 10.0.0.145  | demo2.intranet.hyperic.net
> |       60490 | 2022-03-09 09:07:06.648645+00 |              | streaming | 0/7001118 | 0/7001118 | 0/700111
> 8 | 0/7001118  |           |           |            |             2 | sync
>  381 |    16384 | repmgr  | psql-postgresql-ha-postgresql-2 | 10.0.0.158  | vmlin-012.intranet.hyperic.net
> |       43756 | 2022-03-09 09:07:06.960326+00 |              | streaming | 0/7001118 | 0/7001118 | 0/700111
> 8 | 0/7001118  |           |           |            |             3 | sync
> (2 rows)
> 
> postgres=# create database test;
> CREATE DATABASE
> postgres=# \c test;
> You are now connected to database "test" as user "postgres".
> test=# CREATE TABLE films (
> test(#     code        char(5),
> test(#     title       varchar(40),
> test(#     did         integer,
> test(#     date_prod   date,
> test(#     kind        varchar(10),
> test(#     len         interval hour to minute,
> test(#     CONSTRAINT production UNIQUE(date_prod)
> test(# );
> CREATE TABLE
> test=#
> test=# CREATE TABLE links (
> test(# id SERIAL PRIMARY KEY,
> test(# url VARCHAR(255) NOT NULL,
> test(# name VARCHAR(255) NOT NULL,
> test(# description VARCHAR (255),
> test(#         last_update DATE
> test(# );
> CREATE TABLE
> test=#
> test=# INSERT INTO links (url, name)
> test-# VALUES('https://www.postgresqltutorial.com','PostgreSQL Tutorial');
> INSERT 0 1
> test=#
> test=#
> test=# SELECT * FROM links;
>  id |                url                 |        name         | description | last_update
> ----+------------------------------------+---------------------+-------------+-------------
>   1 | https://www.postgresqltutorial.com | PostgreSQL Tutorial |             |
> (1 row)
> ```
> 
> Could you provide more details about the values.yaml you used and the Kubernetes platform?

Thanks @javsalgar for the response.

From the logs which you have shared, I can see that the version you are using is 11.15. 

I am deploying the chart using the Postgres13.5 Image as we are looking for a higher version of Postgres than 11.

```
 repository: bitnami/postgresql-repmgr-custom
  tag: 13.5.0-debian-10-r35
```

**Comment by javsalgar** [comment]
I tried with the latest 13.x.x image and no issues either

```
 1 ❯ kubectl exec -ti psql-postgresql-ha-postgresql-0 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@psql-postgresql-ha-postgresql-0:/$ PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres
psql (13.6)
Type "help" for help.

postgres=# select * from pg_stat_replication;
 pid | usesysid | usename |        application_name         | client_addr |        client_hostname        |
 client_port |         backend_start         | backend_xmin |   state   | sent_lsn  | write_lsn | flush_lsn
 | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state |          reply_time

-----+----------+---------+---------------------------------+-------------+-------------------------------+
-------------+-------------------------------+--------------+-----------+-----------+-----------+----------
-+------------+-----------+-----------+------------+---------------+------------+--------------------------
-----
 331 |    16384 | repmgr  | psql-postgresql-ha-postgresql-1 | 10.0.0.249  | vm-gw-01.intranet.hyperic.net |
       46002 | 2022-03-11 09:57:02.0915+00   |              | streaming | 0/7000D70 | 0/7000D70 | 0/7000D70
 | 0/7000D70  |           |           |            |             2 | sync       | 2022-03-11 09:58:06.36014
1+00
 351 |    16384 | repmgr  | psql-postgresql-ha-postgresql-2 | 10.0.0.19   | dyn-19.intranet.hyperic.net   |
       44640 | 2022-03-11 09:57:03.803366+00 |              | streaming | 0/7000D70 | 0/7000D70 | 0/7000D70
 | 0/7000D70  |           |           |            |             3 | sync       | 2022-03-11 09:58:06.36015
5+00
(2 rows)

postgres=#
postgres=# create database test;
CREATE DATABASE
postgres=# CREATE TABLE links (
postgres(# id SERIAL PRIMARY KEY,
postgres(# url VARCHAR(255) NOT NULL,
postgres(# name VARCHAR(255) NOT NULL,
postgres(# description VARCHAR (255),
postgres(#         last_update DATE
postgres(# );
CREATE TABLE
postgres=#
postgres=# INSERT INTO links (url, name)
postgres-# VALUES('https://www.postgresqltutorial.com','PostgreSQL Tutorial');
INSERT 0 1
postgres=#
postgres=#
postgres=#
postgres=# SELECT * from links;
 id |                url                 |        name         | description | last_update
----+------------------------------------+---------------------+-------------+-------------
  1 | https://www.postgresqltutorial.com | PostgreSQL Tutorial |             |
(1 row)
```
