### ISSUE TITLE
how to integrate kubernetes-event-exporter with elasticsearch 

### ISSUE THREAD

**Issue by jainpratik163** [bitnami/charts#9366]
### Name and Version

kubernetes-event-exporter

### What is the problem this feature will solve?

NA

### What is the feature you are proposing to solve the problem?

NA

**Comment by juan131** [comment]
Hi @jainpratik163 

Could you please feel the required information available in the issue template? Thanks in advance.

**Comment by jainpratik163** [comment]
@juan131 i want doc which says how we can send events to Elasticsearch as i am not able to find any example.

**Comment by juan131** [comment]
Hi @jainpratik163 

Thanks for the suggestions! Please feel free to improve the docs by submitting a PR updating the [ElasticSearch chart's README.md)]https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/README.md) or the [ElasticSearch docs](https://github.com/bitnami/charts-docs/tree/main/charts/elasticsearch).

**Comment by jainpratik163** [comment]
@juan131 i want to integrate kubernetes-event-exporter with elastic search , so that we can send k8s events to ES and later on we can check issue.

**Comment by javsalgar** [comment]
Hi,

Is the Elasticsearch support documented in the kubernetes-event-exporter official documentation?
