### ISSUE TITLE
make serviceAccount.automountServiceAccountToken: true the default

### ISSUE THREAD

**Issue by ebostijancic** [bitnami/charts#9372]
### Name and Version

bitnami/keycloak 7.1.0

### What is the problem this feature will solve?

The default value set in the values file for `serviceAccount.automountServiceAccountToken` is `false`, however according to Kubernetes documentation the default is `true` (opt-out). Please change the default to `true` so that users does not need to care about this.

### What is the feature you are proposing to solve the problem?

failing to bootstrap a keycloak cluster as nodes are not allowed to find each other using kubernetes.KUBE_PING method.

**Comment by juan131** [comment]
Hi @ebostijancic 

Thanks so much for warning us about this. I agree with you that it should be set to "true" by default.

Would you like to contribute with a PR amending this? Thanks in advance.
