### ISSUE TITLE
[bitnami/kafka] Make certificates work with cert-manager

### ISSUE THREAD

**Issue by rrileyca** [bitnami/charts#9378]
### Name and Version

bitnami/kafka:3.1.0-debian-10-r31

### What is the problem this feature will solve?

`auth.tls.existingSecrets` currently does not work "out of the box" with cert-manager because the `Secret` resource made by cert-manager does not include a `ca.crt` field, which causes the `auto-discovery.sh` script to fail [here](https://github.com/bitnami/charts/blob/3e7c06fdf291753b37603cc27276b53bd173deec/bitnami/kafka/templates/scripts-configmap.yaml#L141). 

### What is the feature you are proposing to solve the problem?

There are many solutions to this problem, but I don't know which will fit best into the Chart. It is also not clear to me whether this CA cert is required. Is there not a central collection of trusted root certificate authorities already in the container? 

Here are some ideas:

1. If there is already a collection of trusted roots, make the `Secret` field `ca.crt` optional and verify the connections against the existing root certs (which could lead to failures if the cert is signed by a non-public CA).
2. Include an environment variable like `TRUSTED_CA_CERTIFICATES` which contains a PEM list file, and split this into multiple files (using something like `csplit certchain.pem '/\-*END CERTIFICATE\-*/+1' '{*}'`) and add these to the central collection of trusted roots.
3. Following the mantra of `auth.tls.existingSecrets`, have a `auth.tls.existingCASecrets` that points to a separate secret that contains a PEM of the CA certificate. Make this optional if there is already trusted roots somewhere.

There are many more ways to solve this, so just listing these to start discussion. I am happy to open a PR with the changes once a solution has been decided on.

### What alternatives have you considered?

There are really only workaround, which generally revolve around editing the script in the `ConfigMap` or adding the CA to the `ca.crt` field in the `Secret` made by cert-manager.

**Comment by rrileyca** [comment]
I should clarify that this becomes especially problematic when cert-manager is using ACME. Although cert-manager has the [ability to creates JKS keystores](https://cert-manager.io/next-docs/reference/api-docs/#cert-manager.io/v1.CertificateKeystores), it can only do so with a non-ACME issuer. When using an ACME issuer, the cert-chain is accessible but not the Root CA. It assumes that each system will already have a configured set of trusted root CA's.

**Comment by rafariossaa** [comment]
Hi,
  This seems related to [this cert-manager issue](https://github.com/cert-manager/cert-manager/issues/1571).
  I think other option is to check `tls.crt` if it includes the CA (or intermediate certs) and extract it from there. Maybe [this comment](https://github.com/cert-manager/cert-manager/issues/1571#issuecomment-486661887) can help.

**Comment by rrileyca** [comment]
Hi @rafariossaa, 

You're right it is related to those issues. I have tried manually copying the certificates in the chain into the `ca.crt` field though I have not been successful.

What I think is specific to this issue is the ability to use this chart without the need for a `ca.crt`. For example, having a flag that specifies the `tls.crt` field in the Secret is a PEM chain, and then having the `setup.sh` script split the certificate. This would enable ACME certificate management.

**Comment by rafariossaa** [comment]
Thanks for your PR. Let's wait until it get merged to close this.
