### ISSUE TITLE
set the retention more than 10d

### ISSUE THREAD

**Issue by rthamrin** [bitnami/charts#9380]
### Name and Version

bitnami/kube-prometheus-6.6.5

### What steps will reproduce the bug?

1. install the Prometheus through helm bitnami/kube-prometheus-6.6.5
2. modify the retention days up to 10d. I have tried to modify to 1y , 90d, 360d 
3. helm upgrade the values

### Are you using any custom parameters or values?

values.yaml

### What is the expected behavior?

saving data metric more than 10d, 90 days for example

### What do you see instead?

the data only stay not even 24 hours

**Comment by javsalgar** [comment]
Hi,

Note that, in this case, we are applying this value to the operator object. Therefore, if it is not applied, maybe the issue has to do with the operator or with changes in the CRD. Did you check with the prometheus-operator devs?
