### ISSUE TITLE
argo-cd does not include ApplicationSet

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9389]
### Name and Version

bitnami/argocd : latest

### What is the problem this feature will solve?

At the argocd site documentation says applicationset is now included in the argocd release as of v2.3:
https://argocd-applicationset.readthedocs.io/en/stable/Getting-Started/

Yet, when I install the bitnami argocd helm chart it doesn't know what a kind of type ApplicationSet is.

### What is the feature you are proposing to solve the problem?

If you have testing as part of your release process add testing of an ApplicationSet.

Include the ApplicationSet implementation in the bitnami argo-cd release.  I don't see an ApplicationSet in the applications.yaml in the crd folder, maybe that's why?

### What alternatives have you considered?

You can try installing the ApplicationSet controller using this:
```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

**Comment by lknite** [comment]
Nevermind, I reviewed available versions and it looks like you already have the newer version in there.

**Comment by lknite** [comment]
If I install using the install script provided by argocd I can view the CRD of the ApplicationSet:
```
$ k get customresourcedefinitions.apiextensions.k8s.io applicationsets.argoproj.io 
NAME                          CREATED AT
applicationsets.argoproj.io   2022-03-13T23:46:51Z
```

If I then delete that and install using the latest bitnami argo-cd helm chart and run the same test:
```
$ k get customresourcedefinitions.apiextensions.k8s.io app
applications.argoproj.io  appprojects.argoproj.io
```

**Comment by migruiz4** [comment]
Hi @lknite,

Thank you for reporting this issue! I have submitted this PR #9413 updating existing CRDs and adding the ApplicationSet CRD.

**Comment by lknite** [comment]
Is there a known eta when this new change will be available via bitnami/argo-cd chart release?
