### ISSUE TITLE
[rabbitmq-cluster-operator] Lack of secret with default user and password

### ISSUE THREAD

**Issue by rafalix1337** [bitnami/charts#9392]
### Name and Version

bitnami/rabbitmq-cluster-operator 2.3.4

### What steps will reproduce the bug?

1. install rabbitmq-cluster-operator by Helm in Kubernetes
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/rabbitmq-cluster-operator
```

### What is the expected behavior?

When we install rabbitmq-cluster-operator by kubectl manifests (https://github.com/rabbitmq/cluster-operator#quickstart) we have a secret with username/password to connect with our rabbitmq.
```
root@DESKTOP-6DGEJ71:~# kubectl get secrets | grep -i rabbitmq
rabbitmq-default-user           Opaque                                7      2m53s
rabbitmq-erlang-cookie          Opaque                                1      2m53s
rabbitmq-server-token-cztzf     kubernetes.io/service-account-token   3      2m53s
```

```
root@DESKTOP-6DGEJ71:~# kubectl get secret rabbitmq-default-user -o yaml
apiVersion: v1
data:
  default_user.conf: hash
  host: hash
  password: hash
  port: hash
  provider: hash
  type: hash
  username: hash
kind: Secret
metadata:
  creationTimestamp: "2022-03-12T22:37:30Z"
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-default-user
  namespace: default
  ownerReferences:
  - apiVersion: rabbitmq.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: RabbitmqCluster
    name: rabbitmq
    uid: b6de3c23-87eb-4b89-b15d-1aa8b9e2b9c4
  resourceVersion: "13704"
  uid: e61b49e3-3c8c-46e4-b5aa-db21ee69d54d
type: Opaque
```

It's described here: https://www.rabbitmq.com/kubernetes/operator/using-operator.html#creds

### What do you see instead?

```
root@DESKTOP-6DGEJ71:~# kubectl get secrets | grep -i rabbitmq
rabbitmq-rabbitmq-cluster-operator-token-9kfph              kubernetes.io/service-account-token   3      31m
rabbitmq-rabbitmq-messaging-topology-operator-token-64q4v   kubernetes.io/service-account-token   3      31m
rabbitmq-rabbitmq-messaging-topology-operator-webhook       kubernetes.io/tls                     3      31m
sh.helm.release.v1.rabbitmq.v1                              helm.sh/release.v1                    1      31m
```
Any of these secrets don't have a username and password to rabbitmq cluster

### Additional information

Automatically generated secret with username and password is very useful to integrate generated rabbitmq and application.

**Comment by rafariossaa** [comment]
Hi,
  The commands you indicated you have used deploy only the operator. In the `quickstart` link you can see that the operator is deployed with the first `kubectl apply` command, and later a `hello-world` CRD is deployed.
  The operator is the one who is creating all the elements when the CRD appears.
