### ISSUE TITLE
bitnami support tool 73e0a87b-8aed-e6db-6b9c-6b3baddecd3d

### ISSUE THREAD

**Issue by rapnics21121** [bitnami/charts#9393]
### Name and Version

bitnami / wordpress 

### What steps will reproduce the bug?

bitnami support tool 73e0a87b-8aed-e6db-6b9c-6b3baddecd3d

[Sat Mar 12 17:56:04.119958 2022] [proxy_fcgi:error] [pid 14752:tid 140133256828672] (70007)The timeout specified has expired: [client **ip_address**:15980] AH01075: Error dispatching request to : (polling), referer: https://tradevits.com/about/ [Sat Mar 12 23:54:40.286434 2022] [proxy_fcgi:error] [pid 14752:tid 140133391111936] (70007)The timeout specified has expired: [client **ip_address**:40862] AH01075: Error dispatching request to : (polling)Press [Enter] to continue: [Sat Mar 12 23:54:43.323769 2022] [proxy_fcgi:error] [pid 2395:tid 140133097367296] (70007)The timeout specified has expired: [client **ip_address**:39032] AH01075: Error dispatching request to : (polling)

### Are you using any custom parameters or values?

[Sat Mar 12 17:56:04.119958 2022] [proxy_fcgi:error] [pid 14752:tid 140133256828672] (70007)The timeout specified has expired: [client **ip_address**:15980] AH01075: Error dispatching request to : (polling), referer: https://tradevits.com/about/ [Sat Mar 12 23:54:40.286434 2022] [proxy_fcgi:error] [pid 14752:tid 140133391111936] (70007)The timeout specified has expired: [client **ip_address**:40862] AH01075: Error dispatching request to : (polling)Press [Enter] to continue: [Sat Mar 12 23:54:43.323769 2022] [proxy_fcgi:error] [pid 2395:tid 140133097367296] (70007)The timeout specified has expired: [client **ip_address**:39032] AH01075: Error dispatching request to : (polling)

### What is the expected behavior?

the website goes up and down, on a day to day basis it goes down 3 to 4 times a day

### What do you see instead?

i already have used cloudflare and put the website to under attack mode but the same still happens

### Additional information

please help me

**Comment by carrodher** [comment]
Please note we provide support for container images and Helm charts in GitHub, but this case seems to be related to native installers, Virtual Machines, MultiTier templates, etc. Support for those products is provided via https://community.bitnami.com/, can you post your question in that forum?
