### ISSUE TITLE
[bitnami/thanos] add support for thanos stateless ruler

### ISSUE THREAD

**Issue by ninjaslothx** [bitnami/charts#9395]
### Name and Version

bitnami/thanos 10.1.1

### What is the problem this feature will solve?

Add support for thanos ruler stateless mode https://thanos.io/tip/components/rule.md/#stateless-ruler-via-remote-write

### What is the feature you are proposing to solve the problem?

Enable to switch between a statefulset and deployment based on using stateless mode with the receiver.

**Comment by carrodher** [comment]
Thanks for this suggestion. Would you like to contribute by creating a PR adding this feature? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
