### ISSUE TITLE
Add annotations for redis' secret only

### ISSUE THREAD

**Issue by jmc171144** [bitnami/charts#9400]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

The idea is to allow to add annotations only on the redis secret. Actually the only way to add annotations to the secret is to use the commonAnnotations value, but this add the annotations to all kubernetes elements so it can be problematic.

### What is the feature you are proposing to solve the problem?

Add a secretAnnotations value to add annotated the secret only.

It can be useful when using secret reflector as describe in [#9363](https://github.com/bitnami/charts/pull/9363)

**Comment by rafariossaa** [comment]
Hi,
  Thanks from bringing this.
  Let's wait until the PR is discussed and merged.

**Comment by jmc171144** [comment]
Hello @rafariossaa, the PR is ready and waiting to be merged
