### ISSUE TITLE
Followup on ZK 3.6.3 with CVEs https://github.com/bitnami/charts/issues/9211

### ISSUE THREAD

**Issue by RamyaRohidas** [bitnami/charts#9403]
### Name and Version

3.6.3

### What steps will reproduce the bug?

zookeeper 3.6.3 when we run twistlock scan
[zookeeper-3-6-3.csv](https://github.com/bitnami/charts/files/8244944/zookeeper-3-6-3.csv)

### What do you see instead?

Many high and critical CVEs

**Comment by carrodher** [comment]
I'm closing this issue in favor of the already opened one (https://github.com/bitnami/charts/issues/9211).
