### ISSUE TITLE
Missing properties for skipper kubernetes deployer

### ISSUE THREAD

**Issue by pluess** [bitnami/charts#9408]
### Name and Version

bitnami/spring-cloud-data-flow 6.0.0

### What is the problem this feature will solve?

The kubernetes deployer for skipper is missing some properties:

1. `entryPointStyle`: When skipper deployes a streaming pod, the entryPointStyle defines how the arguments are passed to the pod and how it is started. See https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style
2. `imagePullPolicy`: When skipper deployes a streaming pod, the imagePullPolicy defines how often the specified image is pulled from the registry. See https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_image_pull_policy

Currently it's not possible to configure this options, which means skipper always uses the default values.

### What is the feature you are proposing to solve the problem?

Make `entryPointStyle `and `imagePullPolicy `configurable as deployer options.

**Comment by rafariossaa** [comment]
Hi,
 Thanks for noticing this.
  Let's wait until the PR is discussed and merged.
