### ISSUE TITLE
Postgresql statefulset.yaml is missing storageClassName directive

### ISSUE THREAD

**Issue by aldemira** [bitnami/charts#9410]
### Name and Version

bitnami/postgresql 11.1.6

### What steps will reproduce the bug?

helm install postgresql bitnami/postgresql 

### Are you using any custom parameters or values?

--set persistence.storageClass=mystg-class

### What is the expected behavior?

Persistent volume claim should be bound and persistent volume is created automatically. 

### What do you see instead?

A pending PVC saying: "no persistent volumes available for this claim and no storage class is set"

### Additional information

In the templates/primary/statefulset.yaml file, under volumeClaimTemplates -> spec 
**storageClassName** should be defined as explained in values.yaml.

**Comment by fmulero** [comment]
Hi @aldemira

You can set the storageClass using the following parameters:
* `global.storageClass`
* `primary.persistence.storageClass`
* `readReplicas.persistence.storageClass`

Please review the [documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#parameters) to know more about them
