### ISSUE TITLE
[bitnami/etcd] rolling restart with no changes

### ISSUE THREAD

**Issue by justinrush** [bitnami/charts#9417]
### Name and Version

bitnami/etcd 6.13.4

### What steps will reproduce the bug?

1. Deploy etcd with a minimal config
2. Run helm upgrade with the same values overrides
3. notice that a rolling restart occurs

This snippit reproduces the issue:

```sh
cat << EOF >values.yaml
auth:
  rbac:
    enabled: false
    create: false
    allowNoneAuthentication: true
replicaCount: 3
EOF

kubectl create ns test
helm install test-etcd bitnami/etcd -n test -f values.yaml

for i in `seq 1 10`; do echo "hit enter when etcd is ready"; read; helm upgrade test-etcd bitnami/etcd -n test -f values.yaml; done
```

### Are you using any custom parameters or values?

Provided above

### What is the expected behavior?

With no changes, no rolling restart should occur

### What do you see instead?

A rolling restart occurs

**Comment by marcosbc** [comment]
Hi @justinrush, thanks for reporting this issue. Does this affect in any way the functionality of the cluster, after being deployed? In addition, could you share more info relative to the reason of the restart that you are seeing? (e.g. some logs about the readines/liveness probes, or a failed initialization).

**Comment by justinrush** [comment]
We wrap helm upgrades along with other kubernetes based changes using a process similar to common GitOps in a mono repo. Any changes to config in that repo will trigger a `helm upgrade` on the instance. The way other charts behave is no changes are observed if there are no changes to the values overrides.

The rolling restart seems to complete fine with no impact to clients consuming the service, however, it does add risk that something can go wrong and we would prefer it not happen.

**Comment by marcosbc** [comment]
This could be the reason you are seeing those upgrades: [statefulset.yaml#L34](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L34)

You could try and disable the `checksum/configuration` and `checksum/token-secret` annotations, if enabled, and see if this behavior stops occurring.

**Comment by justinrush** [comment]
I'll give this a shot next week, thanks

**Comment by alop** [comment]
> This could be the reason you are seeing those upgrades: [statefulset.yaml#L34](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L34)
> 
> You could try and disable the `checksum/configuration` and `checksum/token-secret` annotations, if enabled, and see if this behavior stops occurring.

Checking the values.yaml file, the conditionals that wrap these annotations don't seem to exist anymore.
My statefulset doesn't have these checksums and still exhibits the same behavior - No-op changes cause a redeployment.

**Comment by marcosbc** [comment]
Hi all, in the case described above I was able to reproduce this issue, and it was caused by changes to the checksum as mentioned previously:

```diff
@@ -1,8 +1,8 @@
 NAME: test-etcd
-LAST DEPLOYED: Mon Apr 18 17:09:11 2022
+LAST DEPLOYED: Mon Apr 18 17:11:47 2022
 NAMESPACE: default
 STATUS: deployed
-REVISION: 1
+REVISION: 2
 TEST SUITE: None
 USER-SUPPLIED VALUES:
 auth:
@@ -255,7 +255,7 @@
     app.kubernetes.io/managed-by: Helm
 type: Opaque
 data:
-  jwt-token.pem: "LS0tLS1CRU..."
+  jwt-token.pem: "LS0tLS1CRU..."
 ---
 # Source: etcd/templates/svc-headless.yaml
 apiVersion: v1
@@ -342,7 +342,7 @@
         app.kubernetes.io/instance: test-etcd
         app.kubernetes.io/managed-by: Helm
       annotations:
-        checksum/token-secret: 8e9b635ce5877d91e4c3e944f999a54c6ee4c061cf1e9360ad8a80e158c0f794
+        checksum/token-secret: 4dce8ab0f4bcc747af903b02f85c58c24cf531d584c075b7fc904faf812ccb0f
     spec:

       affinity:
@@ -413,7 +413,7 @@
             - name: ETCD_INITIAL_CLUSTER_TOKEN
               value: "etcd-cluster-k8s"
             - name: ETCD_INITIAL_CLUSTER_STATE
-              value: "new"
+              value: "existing"
             - name: ETCD_INITIAL_CLUSTER
               value: "test-etcd-0=http://test-etcd-0.test-etcd-headless.default.svc.cluster.local:2380,test-etcd-1=http://test-etcd-1.test-etcd-headless.default.svc.cluster.local:2380,test-etcd-2=http://test-etcd-2.test-etcd-headless.default.svc.cluster.local:2380"
             - name: ETCD_CLUSTER_DOMAIN
```

I could get the diff by specifying the `--debug` option to `helm install` and `helm upgrade`.

It is simple to see that the `ETCD_INITIAL_CLUSTER` variable will always change during the first deployment. I don't think this is bad, as it indeed makes sense if you want to actually be able to persist your data. Therefore, after running `helm upgrade` again (for the second time) so it does not appear, this is the difference:

```diff
@@ -1,8 +1,8 @@
 NAME: test-etcd
-LAST DEPLOYED: Mon Apr 18 17:11:47 2022
+LAST DEPLOYED: Mon Apr 18 17:18:40 2022
 NAMESPACE: default
 STATUS: deployed
-REVISION: 2
+REVISION: 3
 TEST SUITE: None
 USER-SUPPLIED VALUES:
 auth:
@@ -255,7 +255,7 @@
     app.kubernetes.io/managed-by: Helm
 type: Opaque
 data:
-  jwt-token.pem: "LS0tLS1CRU..."
+  jwt-token.pem: "LS0tLS1CRU..."
 ---
 # Source: etcd/templates/svc-headless.yaml
 apiVersion: v1
@@ -342,7 +342,7 @@
         app.kubernetes.io/instance: test-etcd
         app.kubernetes.io/managed-by: Helm
       annotations:
-        checksum/token-secret: 4dce8ab0f4bcc747af903b02f85c58c24cf531d584c075b7fc904faf812ccb0f
+        checksum/token-secret: 03769361141f7aa1ce946dc707f1226379b1c6f8960f86d8814a2c1681ace0a9
     spec:

       affinity:
```

You can see that there is indeed a checksum that keeps getting updated, due to the JWT token. The only way to avoid that is to either set a value to `auth.token.privateKey.existingSecret`, or to set `auth.token.type=simple`.

This issue could be avoided by using the Helm lookup feature for getting that secret value, which was mentioned here for Redis: https://github.com/bitnami/charts/issues/9785. PRs are welcome and we would be glad to review any improvements to fix issues like these.

**Comment by OvervCW** [comment]
This issue should be reopened since it's still a problem.

@[marcosbc](https://github.com/marcosbc) What are the security consequences of "simple" versus "jwt"?

**Comment by omerycohe** [comment]
HI,

we are also experiencing this issue, and this is indeed a problem,
can this be reopened?

**Comment by juan131** [comment]
Hi everyone!! This issue was fixed at #12019 

Please ensure that you're running an updated version of the `bitnami/etcd` chart to avoid the JWT checksum to be recreated every-tiem.

**Comment by wilkko** [comment]
> Hi everyone!! This issue was fixed at #12019
> 
> Please ensure that you're running an updated version of the `bitnami/etcd` chart to avoid the JWT checksum to be recreated every-tiem.

Which chart version fixes the issue?

**Comment by juan131** [comment]
> Which chart version fixes the issue?

8.5.2 @wilkko

**Comment by wilkko** [comment]
FYI lookup function doesn't work yet with ArgoCD so it might appear as if this issue has not resolved for Helm charts applied with ArgoCD:  [Helm lookup Function Support](https://github.com/argoproj/argo-cd/issues/5202)

**Comment by mfractal** [comment]
> FYI lookup function doesn't work yet with ArgoCD so it might appear as if this issue has not resolved for Helm charts applied with ArgoCD: [Helm lookup Function Support](https://github.com/argoproj/argo-cd/issues/5202)

just ran into this exact issue. any idea how to resolve it with Argo ? i tried adding the token + checksum to argo ignore list, it works for the token but not for the checksum for some reason

```
spec:
  ignoreDifferences:
  - kind: Secret
    name: apisix-etcd-jwt-token
    namespace: ingress-apisix
    jsonPointers:
    - /data/jwt-token.pem
  - kind: StatefulSet
    name: apisix-etcd
    namespace: ingress-apisix
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1token-secret
```

**Comment by wilkko** [comment]
> > FYI lookup function doesn't work yet with ArgoCD so it might appear as if this issue has not resolved for Helm charts applied with ArgoCD: [Helm lookup Function Support](https://github.com/argoproj/argo-cd/issues/5202)
> 
> just ran into this exact issue. any idea how to resolve it with Argo ? i tried adding the token + checksum to argo ignore list, it works for the token but not for the checksum for some reason
> 
> ```
> spec:
>   ignoreDifferences:
>   - kind: Secret
>     name: apisix-etcd-jwt-token
>     namespace: ingress-apisix
>     jsonPointers:
>     - /data/jwt-token.pem
>   - kind: StatefulSet
>     name: apisix-etcd
>     namespace: ingress-apisix
>     jsonPointers:
>     - /spec/template/metadata/annotations/checksum~1token-secret
> ```

We had to use existing/external private key secret to avoid the re-create of it in ArgoCD 2.8.x:

````yaml
    auth:
      rbac:
        create: false
      token:
        privateKey:
          existingSecret: external-etcd-jwt-token
````

**Comment by javier-ruiz-voxsmart** [comment]
> > > FYI lookup function doesn't work yet with ArgoCD so it might appear as if this issue has not resolved for Helm charts applied with ArgoCD: [Helm lookup Function Support](https://github.com/argoproj/argo-cd/issues/5202)
> > 
> > 
> > just ran into this exact issue. any idea how to resolve it with Argo ? i tried adding the token + checksum to argo ignore list, it works for the token but not for the checksum for some reason
> > ```
> > spec:
> >   ignoreDifferences:
> >   - kind: Secret
> >     name: apisix-etcd-jwt-token
> >     namespace: ingress-apisix
> >     jsonPointers:
> >     - /data/jwt-token.pem
> >   - kind: StatefulSet
> >     name: apisix-etcd
> >     namespace: ingress-apisix
> >     jsonPointers:
> >     - /spec/template/metadata/annotations/checksum~1token-secret
> > ```
> 
> We had to use existing/external private key secret to avoid the re-create of it in ArgoCD 2.8.x:
> 
> ```yaml
>     auth:
>       rbac:
>         create: false
>       token:
>         privateKey:
>           existingSecret: external-etcd-jwt-token
> ```

Do you have an example of how that secret should look like?
We are trying to apply this solution as well.

**Comment by hroost** [comment]
> just ran into this exact issue. any idea how to resolve it with Argo ? i tried adding the token + checksum to argo ignore list, it works for the token but not for the checksum for some reason

FYI
It doesn't work with StatefulSet due to absent `group` field ([docs](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration))

So, the working example would be:

```
spec:
  ignoreDifferences:
  - kind: Secret
    name: apisix-etcd-jwt-token
    namespace: ingress-apisix
    jsonPointers:
    - /data/jwt-token.pem
  - kind: StatefulSet
    group: apps
    name: apisix-etcd
    namespace: ingress-apisix
    jsonPointers:
    - /spec/template/metadata/annotations/checksum~1token-secret
```

**Comment by adityakumaaar** [comment]
@javier-ruiz-voxsmart 
> > 
> > 
> > We had to use existing/external private key secret to avoid the re-create of it in ArgoCD 2.8.x:
> >     auth:
> >       rbac:
> >         create: false
> >       token:
> >         privateKey:
> >           existingSecret: external-etcd-jwt-token
> 
> hi [wilkko](https://github.com/wilkko) Do you have an example of how that secret should look like? We are trying to apply this solution as well.

The K8s secret should look like 

```
apiVersion: v1
data:
  jwt-token.pem: <REDACTED>
kind: Secret
metadata:
  name: apisix-etcd-jwt-token
  namespace: apisix
type: Opaque
```

NOTE : We use ArgoCD + ExternalSecrets to create the secret in K8s cluster
