### ISSUE TITLE
Wordpress Helm Chart using Nginx docker image - Pass configMaps for vhosts for multisite deployments

### ISSUE THREAD

**Issue by webdz9r** [bitnami/charts#9420]
### Name and Version

Bitnami/wordpress:latest

### What is the problem this feature will solve?

Right now I'm using extraHosts and extraTls for vhosts for my multi-site installs. Ideally I'd like to add custom vhosts Nginx configuration values for my deployments. Any advise on this if it's already supported? It would be a great option if not

### What is the feature you are proposing to solve the problem?

passing configMaps for individual hosts

### What alternatives have you considered?

NA

**Comment by carrodher** [comment]
Please note this is something not supported out of the box, the bitnami/wordpress Helm chart uses [this container image](https://github.com/bitnami/bitnami-docker-wordpress) which is based on Apache.

**Comment by cyphunk** [comment]
@webdz9r any hope you could share your configuration. Having issues with extratls multisite and the wordpress bitnami chart.
