### ISSUE TITLE
To set verbosity for logs in redis helm charts

### ISSUE THREAD

**Issue by jmjiji** [bitnami/charts#9427]
### Name and Version

bitnami/redis-14.8.8

### What is the problem this feature will solve?

I am facing some issues in my redis deployment, and what I can see is that there isn't any logs for the particular issue, due to which I can't come to an conclusion if this problem is with redis deployment or something else because of which I want to set a proper verbosity for redis deployment. If this feature is added in the helm chart it would be very helpful and if this feature is present it would be very helpful if someone can explain me how to do it.

### What is the feature you are proposing to solve the problem?

To add the configuration in helm chart itself.

**Comment by miguelaeh** [comment]
Hi @jmjiji ,
you can specify Redis configuration in [this](https://github.com/bitnami/charts/blob/b269c20fd861435a07dbe78eeda3375fc72cc21f/bitnami/redis/values.yaml#L132) parameter

**Comment by jmjiji** [comment]
Hi @miguelaeh 
Thanks for your response.
Can you tell how can I specify log level verbosity to let say "debug" level in the above parameter you mentioned. Your help would be much appreciated.

Thanks

**Comment by miguelaeh** [comment]
You need to add there the configuration for the login level. Check [this](https://www.papertrail.com/help/redis/).

**Comment by jmjiji** [comment]
Hi @miguelaeh 

Thanks for the response.
But the link you have shared I have already seen, the issue what I am facing is and what I need help on is, if you could help me is, how can we add the configuration in the value.yaml file for the bitnami/redis chart.

**Comment by miguelaeh** [comment]
You need to add this to values.yaml:

```diff
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
+ loglevel verbose
```

**Comment by Deepanshu6dec** [comment]
How will we enabled logs in Redis conf file 

provided a common configuration in values.yaml file and its showing as error.

'''
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  maxmemory 300mb               
  #maxclient 1000
  logfile /var/log/redis/redis-server.log

'''

Error:

'''

➜  redis git:(master) ✗ k logs -f redis-node-0
Defaulted container "redis" out of: redis, sentinel
 13:42:35.75 INFO  ==> about to run the command: timeout 220 redis-cli -h redis.csmsc-test.svc.cluster.local -p 26379 sentinel get-master-addr-by-name smscmaster
Could not connect to Redis at redis.csmsc-test.svc.cluster.local:26379: Connection refused
 13:42:35.76 INFO  ==> Configuring the node as master

*** FATAL CONFIG FILE ERROR (Redis 6.2.5) ***
Reading the configuration file, at line 11
>>> 'logfile /var/log/redis/redis-server.log'
Can't open the log file: No such file or directory
```
