### ISSUE TITLE
[bitnami/minio] Add tiering functionality to chart with removal of MinIO Gateway

### ISSUE THREAD

**Issue by jgallucci32** [bitnami/charts#9450]
### Name and Version

bitnami/minio

### What is the problem this feature will solve?

Thee MinIO Gateway for GCS, Azure, HDFS is scheduled for removal on June 1st, 2022 per https://github.com/minio/minio/issues/14331. The recommended migration path is to use MinIO in distributed mode with tiering to backend storage. Configuring the tiering in the chart would provide a similar configuration for using a backend storage such as Azure in Gateway mode (endpoint, secret key, etc.) to make it easier to transition after the deprecation.

### What is the feature you are proposing to solve the problem?

Add the ability for the chart to configuring GCS, Azure, HDFS as tiers to MinIO configured in distributed mode when deployed using the chart.

### What alternatives have you considered?

Not upgrading the software and using the old version forever as recommended by the MinIO developer in https://github.com/minio/minio/issues/14331#issuecomment-1042698816

**Comment by javsalgar** [comment]
Hi! 

The chart already supports distributed mode. Could you let us know what it is required to configure this tiering?

**Comment by javsalgar** [comment]
Hi,

Thank you so much! I created a task for working on it. I cannot guarantee an ETA, but if you want to speed up the process, feel free to submit a PR to bitnami/charts or bitnami/bitnami-docker-minio repos and we will review it :)

**Comment by dpunkturban** [comment]
Hi @javsalgar,

Do you still need help here?

**Comment by javsalgar** [comment]
Hi! It is still in our backlog. If you want to speed up the process, PRs are welcome :D

**Comment by carrodher** [comment]
After internal evaluation and due to other tasks the team is working on, we can't spend time on adding this feature to the MinIO Helm chart.

Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
