### ISSUE TITLE
Postgres HA setup with helm chart

### ISSUE THREAD

**Issue by shubhra27** [bitnami/charts#9457]
### Name and Version

bitnami/postgresql-ha/8.6.0

### What steps will reproduce the bug?

Hi,

I am trying to install bitnami's postgres HA helm chart to my kubernetes environment.
The database version that is available as default is 11.5. I need to use 12.x + version. When I am trying to increment the database's docker image version, the containers are crashing. I am getting below error:
```
ERROR: failed to authenticate with backend using SCRAM
DETAIL: valid password not found
``

Note: I haven't changed any default password values.

Any help/suggestion most welcome.

### What is the expected behavior?

The database should be up and running

### What do you see instead?

The docker containers are crashing

**Comment by marcosbc** [comment]
Hi @shubhra27, unfortunately we are not testing the combination of PostgreSQL HA chart with version 12.x or newer. However, we already have an internal task in our backlog for incrementing the version to 14.x, but unfortunately I cannot give an ETA for when it will be done.

In the meantime, you can set the following environment variables in the `pgpool.extraEnvVars` option (or `pgpool.extraEnvVarsCM`/`pgpool.extraEnvVarsSecret`):

* `PGPOOL_AUTHENTICATION_METHOD=scram-sha-256`
* `PGPOOL_ENABLE_POOL_PASSWD=yes`
* `PGPOOL_PASSWD_FILE=...`

Note that you will need to set a value to `PGPOOL_PASSWD_FILE` as well as mount the passwd file. You can read more about Pgpool configurations [here](https://github.com/bitnami/bitnami-docker-pgpool#configuration).

**Comment by shubhra27** [comment]
> 

Hi @marcosbc thanks for quick response. I wanted to use postgres HA with 12.x + version. That is prerequisite for me. Now I have to think of other options then.

**Comment by FraPazGal** [comment]
Hello @shubhra27,

Our `bitnami/postgresql-ha` chart was just updated to use PostgreSQL 14, also adding our latest standardizations. You can check the changes at https://github.com/bitnami/charts/pull/9777/. Thank you for your patience!

**Comment by shubhra27** [comment]
Hi @FraPazGal Thank you so much. I believe we can use it. It's what we were waiting for.

**Comment by FraPazGal** [comment]
Hi @shubhra27,

We are aware there is an issue in our internal CI blocking the publishing of the new version to the different chart registries and the team is actively working on it. I'll update this thread once the issue is solved.

**Comment by carrodher** [comment]
The new version is now appearing in the [ArtifactHub](https://artifacthub.io/packages/helm/bitnami/postgresql-ha) as well as in the Helm chart repo:
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo bitnami/postgresql-ha
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/postgresql-ha	9.0.2        	14.2.0     	This PostgreSQL cluster solution includes the P...
```
