### ISSUE TITLE
[keycloak] Failed to bind properties under 'import' to de.adorsys.keycloak.config.properties.ImportConfigProperties failed

### ISSUE THREAD

**Issue by hectoralicea** [bitnami/charts#9468]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

running standard helm chart with just keycloakConfigCli enabled on AWS EKS.

### Are you using any custom parameters or values?
```yaml
keycloakConfigCli:
  ## @param keycloakConfigCli.enabled Whether to enable keycloak-config-cli job
  ##
  enabled: true
```
### What is the expected behavior?

should launch

### What do you see instead?

```console
$ kc logs -n keycloak keycloak-keycloak-config-cli-kzcbw
2022-03-17 20:57:12.755  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v4.8.0 using Java 11.0.14 on keycloak-keycloak-config-cli-kzcbw with PID 1 (/opt/bitnami/keycloak-config-cli/keycloak-config-cli-16.1.1.jar started by ? in /opt/bitnami/keycloak-config-cli)
2022-03-17 20:57:12.758  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2022-03-17 20:57:13.486  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 1.264 seconds (JVM running for 1.778)
2022-03-17 20:57:13.888  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-17 20:57:13.922 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'import' to de.adorsys.keycloak.config.properties.ImportConfigProperties failed:

    Property: import.path
    Value: null
    Reason: must not be null


Action:

Update your application's configuration
```

### Additional information

using pretty straightforward.

**Comment by marcosbc** [comment]
@hectoralicea Have you enabled any sample configuration, or an existing configmap with configuration? If not it won't import any config, and it won't work.

Feel free to send any PR to improve the documentation if you think it is confusing.

**Comment by hectoralicea** [comment]
> @hectoralicea Have you enabled any sample configuration, or an existing configmap with configuration? If not it won't import any config, and it won't work.

We have not enabled any sample configuration.  How do we do that?  I'm not sure I've seen that in the documentation, but we will continue researching.

**Comment by marcosbc** [comment]
To enable a custom configuration, you can check the `configuration` option of the Helm chart: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L240

**Comment by hectoralicea** [comment]
@marcosbc 
> To enable a custom configuration, you can check the `configuration` option of the Helm chart: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L240
```
## Example:
configuration: |-
  foo: bar
  baz:
```

I'm sorry.  We have been trying to figure this out.  Can you point to a real-life example?  We have been struggling to figure out what the contents of this configuration file should look like.  We have a very generic out of the box config, with simple authentication to a local departmental LDAP.

**Comment by marcosbc** [comment]
Hi @hectoralicea, according to the documentation it should be the contents of the standalone-ha.xml file to be imported into Keycloak. Here you can find an example: https://github.com/DemocracyOS/keycloak/blob/master/customization/standalone-ha.xml

If you find any error, please share the specific errors you see as well as steps to reproduce it on our side.

**Comment by williepadin** [comment]
@marcosbc Thank you so much for your support of this ticket. I work with @hectoralicea. I just have some quick questions: 1) Where can I find the schema documentation for this standalone-ha.xml? I found it a little more confusing to understand than an export we did of the keycloak server. (On that note --->) 2) We did an export of the configuration (JSON) and it appears to have everything that we need to be able to parameterize ports, realms, ldaps, etc. Would that be a valid approach as well when recreating the keycloak server?

**Comment by marcosbc** [comment]
Actually, please ignore my previous comment. We are using [keycloak-config-cli](https://github.com/adorsys/keycloak-config-cli), which mentions to support both YAML and JSON configurations, but not XML.

You can find some examples for both formats here: https://github.com/adorsys/keycloak-config-cli/tree/main/contrib/example-config

You can see how we are executing it here: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/keycloak-config-cli-job.yaml#L44

**Comment by williepadin** [comment]
@marcosbc Thank you for the links!!! I'll get back to you with progress.

**Comment by hectoralicea** [comment]
@marcosbc Thanks, that helped.  One question.  If there were keycloak cli commands that we wanted to run during the post container init, commands such as sync ldap or others like that, is there a section in the values yaml where we can create that script with cli calls to execute a the end of setup?  We do something similar to that in the wordpress helm chart.

**Comment by tirelibirefe** [comment]
> Hi @hectoralicea, according to the documentation it should be the contents of the standalone-ha.xml file to be imported into Keycloak. Here you can find an example: https://github.com/DemocracyOS/keycloak/blob/master/customization/standalone-ha.xml
> 
> If you find any error, please share the specific errors you see as well as steps to reproduce it on our side.

Hello,
How do you attach/add custom xml file to Helm chart?

**Comment by tirelibirefe** [comment]
> Well, it is possible to mount files in `/docker-entrypoint-initdb.d` but that would only affect the `keycloak` container.
> 
> For the `keycloak-config-cli` you would need to override the `keycloakConfigCli.command` option to add a different command, e.g. `bash -c "java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-VERSION.jar; my_custom_command"` (but note that the option expects an array)

Is it tested on Kubernetes?  I have the same problem on Kubernetes?

**Comment by tirelibirefe** [comment]
the same problem is still exist in Chart v9.0.0

**Comment by tirelibirefe** [comment]
> @marcosbc
> 
> > To enable a custom configuration, you can check the `configuration` option of the Helm chart: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L240
> 
> ```
> ## Example:
> configuration: |-
>   foo: bar
>   baz:
> ```
> 
> I'm sorry. We have been trying to figure this out. Can you point to a real-life example? We have been struggling to figure out what the contents of this configuration file should look like. We have a very generic out of the box config, with simple authentication to a local departmental LDAP.

@hectoralicea Hello,
Were you able to run Keycloak cli? If yes how did you fix the problem? Could you please advise? I need to help.

**Comment by aaroniscode** [comment]
@tirelibirefe @marcosbc  I opened an issue https://github.com/bitnami/charts/issues/10320.

I believe there is a bug in the current chart that prevents keycloak-config-cli from working as the import configuration variables were completed updated in v5.0.0
