### ISSUE TITLE
[Minio] Pods Crash when mode=distributed and set defaultBuckets (Behavior in case of wrong settings, not critical)

### ISSUE THREAD

**Issue by stdll00** [bitnami/charts#9471]
### Name and Version

bitnami/minio:11.1.4

### What steps will reproduce the bug?

k8s pods crash with `mode=distributed` and set `defaultBuckets` 

From documentation, I feel `defaultBuckets` is no effect but the actual behavior is that all pods are crashing.
> Comma, semi-colon or space separated list of buckets to create at initialization (only in standalone mode)

It would be more helpful to either ignore defaultBuckets, display an error message, or add a note in the README saying `Do not set this value in distributed mode`.

### How to reproduce.
I tested Docker-Desktop(On m1 mac) and Kind (amd64)

`helm install minio --version 11.1.4 bitnami/minio --set mode=distributed,defaultBuckets=testbucket`

### What do you see instead?

```console
$ kubectl get po
NAME      READY   STATUS             RESTARTS   AGE
minio-0   0/1     CrashLoopBackOff   6          11m
minio-1   0/1     CrashLoopBackOff   6          11m
minio-2   0/1     CrashLoopBackOff   6          11m
minio-3   1/1     Running            3          11m

$ kubectl logs -f minio-0
 00:49:46.55
 00:49:46.55 Welcome to the Bitnami minio container
 00:49:46.56 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
 00:49:46.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
 00:49:46.56
 00:49:46.56 INFO  ==> ** Starting MinIO setup **
minio 00:49:46.59 INFO  ==> Starting MinIO in background...
minio 00:49:51.62 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 00:49:51.72 INFO  ==> MinIO is already stopped...
```

**Comment by fmulero** [comment]
Hi @stdll00

Thanks for the suggestion. To be perfectly blunt, this kind of improvements has a very low priority in our backlog so it won't be done in short term. Any PR is welcome, please feel free to share the best solution for you and we will be happy to review it
