### ISSUE TITLE
add dnsConfig to rabbitmq statefulset template

### ISSUE THREAD

**Issue by Tajjar** [bitnami/charts#9474]
### Name and Version

bitnami/rabbitmq 8.24.3

### What is the problem this feature will solve?

Would enable modification of **search** and **ndots** options in /etc/resolv.conf for each rabbitmq pod.

### What is the feature you are proposing to solve the problem?

Adding **dnsConfig** to statefulset.yaml template

### What alternatives have you considered?

Having my own custom rabbitmq chart to only have that option available which is not optimal.

**Comment by javsalgar** [comment]
Hi,

Did you try using the `extraVolumes` and `extraVolumeMounts` values? This way you should be able to mount a custom configmap that overrides the resolv.conf file. If you want to add the contents of the resolv.conf file you can use the `extraDeploy` value

**Comment by Tajjar** [comment]
Hi @javsalgar,
sadly my aim is not overwrite resolv.conf but to modify and append. I still feel the necessity of having dnsConfig in the statefulset template.
BR,

**Comment by javsalgar** [comment]
Hi!

I didn't know that field existed! Would you like to submit a PR adding it?

**Comment by Tajjar** [comment]
Hey!
gladly.

**Comment by Tajjar** [comment]
Hi @javsalgar,

Pull request (https://github.com/bitnami/charts/pull/9809) submitted and waiting for review.
Thanks for taking the time.

Cheers,

**Comment by javsalgar** [comment]
Thank you so much! The team will take a look
