### ISSUE TITLE
With new repmgr image 14.2, auth is by default scramsha 256 and not md5 while pgpool conf save as md5, failed when deployed

### ISSUE THREAD

**Issue by tal-efraim** [bitnami/charts#9476]
### Name and Version

bitnami/postgresql-ha 8.6.3

### What steps will reproduce the bug?

1. use same values yaml just add passwords and usernames
2. use repmgr image 14.2 (current latest) instead of 11.15

### What is the expected behavior?

My expectation is if repmgr default encryption for users in database is scram sha-256 then pgpool conf will hold with same encryption and will not fail because of different encryption methods

### What do you see instead?

deployment will fail because of incorrect auth method while database uses scram sha-256 and pgpool holds users in conf file with md5 encryption

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that I reproduced the issue. I will open a task for investigating this. Thank you so much for reporting.

**Comment by smatvienko-tb** [comment]
Hey! I'm preparing the [ThingsBoard](https://thingsboard.io/) cluster setup with fancy Bitnami charts and having the same issue. 

After bumping postgresql-repmgr to 14.2 using helm chart:
```
helm install postgresql bitnami/postgresql-ha --version 8.6.4 \
  --set postgresqlImage.tag=14.2.0-debian-10-r42 \
  --set postgresql.replicaCount=3 \
  --set postgresql.database=thingsboard \
  --set postgresql.maxConnections=120 \
  --set pgpool.replicaCount=1 \
  --set pgpool.numInitChildren=120 \
  --set persistence.size=30Gi \
  --set fullnameOverride=postgresql
```

The **pgpool** is never got a Ready status:
![image](https://user-images.githubusercontent.com/79898499/160473518-eda09a92-3c49-4a56-8415-7fde140e5914.png)

The **pgpool** log output is:
```
2022-03-28 19:29:34.419: child pid 180: ERROR:  failed to authenticate with backend using SCRAM
2022-03-28 19:29:34.419: child pid 180: DETAIL:  valid password not found
2022-03-28 19:29:39.412: child pid 167: ERROR:  failed to authenticate with backend using SCRAM
2022-03-28 19:29:39.412: child pid 167: DETAIL:  valid password not found
2022-03-28 19:29:39.420: child pid 179: ERROR:  failed to authenticate with backend using SCRAM
2022-03-28 19:29:39.420: child pid 179: DETAIL:  valid password not found
2022-03-28 19:29:39.426: main pid 1: LOG:  shutting down
2022-03-28 19:29:39.426: main pid 1: LOG:  terminating all child processes
2022-03-28 19:29:39.439: main pid 1: LOG:  Pgpool-II system is shutdown
```

Will appreciate any fix or workaround. Thank you!

**Comment by carrodher** [comment]
There are in progress plans to move the PostgreSQL HA Helm chart to psql 14, but since it will require a new major version in the Helm chart the changes are not straightforward. We will update this thread once the PR with those changes is created in this repo.

**Comment by Kaelten** [comment]
looking forward to having the ha chart support 14.x; having to choose between HA and modern postgres isn't great :(

**Comment by FraPazGal** [comment]
Hello @Kaelten, @smatvienko-tb, @tal-efraim,

Our `bitnami/postgresql-ha` chart was just updated to use PostgreSQL 14, also adding our latest standardizations. You can check the changes at https://github.com/bitnami/charts/pull/9777/. Thank you all for your patience!
