### ISSUE TITLE
Provision Kafka's topics in parallel

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#9479]
### Name and Version

bitnami/kafka

### What is the problem this feature will solve?

Not sure, if we can call it a feature request, but it's in the middle of a feature request and a bug. We could call it an improvement.

Today the chart can let provision a Kafka cluster with default topics. The problem is when there are dozen of topics to provision (or even hundred of topics), the provisioning job is quite slow. Due to provisioning the topic one by one.

We could enable parallelism at this level, and the number of topic provisioned in parallel could be configured through a parameter.

Here, there are two possibilities:

1. Use the bash parallelism syntax to run multiple commands in parallel
2. Create a job per topic to provision and configure the job to be run in parallel.

What do you think?

### What is the feature you are proposing to solve the problem?

Lower the provisioning job time.

### What alternatives have you considered?

None.

**Comment by jaudiger** [comment]
Sure, I could work on it. I'll try to do a PR this week and link this issue in it. I'll ping you once done, thanks.

**Comment by jaudiger** [comment]
Hi @javsalgar, I just opened this PR: https://github.com/bitnami/charts/pull/9520

**Comment by javsalgar** [comment]
Thank you so much for the PR! The team will take a look
