### ISSUE TITLE
Redis-cluster deployment in multiple availability zone 

### ISSUE THREAD

**Issue by fcbavya** [bitnami/charts#9481]
### Name and Version

bitnami/redis-cluster version: 7.0.2

### What steps will reproduce the bug?

Hi,

We deployed bitnami redis cluster with three master and three slaves. Used node affinity rule to place the master node in different availability zone. However the replica of a master node gets scheduled in the same AZ of master. Is there a way I can force replica nodes to different availability zone of master node.

### What do you see instead?

Master and Slave nodes are getting deployed in the same availability zone

**Comment by javsalgar** [comment]
Hi, 

The issue is that, as we're using the same statefulset, I don't think it is possible to define affinity rules with that level of granularity. It seems to me that you may need to perform some manual intervention in the configuration of the nodes after being deployed.

**Comment by fcbavya** [comment]
Hi,

Thank you for the response. Is there any chance for implementing this feature in bitnami helm future releases?

Thank you,
Bavya

**Comment by javsalgar** [comment]
Hi,

Right now there are no plans on implementing this feature, but in case the community comes up with an idea on how to implement this, PRs are welcome and we will review them :D

**Comment by fcbavya** [comment]
Got it. Thank you.

Bavya

**Comment by WolfspiritM** [comment]
I think this is not only a problem with affinity rules but also pod disruption budges.
https://github.com/bitnami/charts/issues/9722

I think it would be helpful to have master and slaves in different statefulsets but I guess cause of failovers and switching that's not possible?
