### ISSUE TITLE
not able to specify an tls using cert-manager

### ISSUE THREAD

**Issue by sunsong** [bitnami/charts#9489]
### Name and Version

bitnami/magento 19.2.12

### What steps will reproduce the bug?

I am using cert-manger to make multiple kubernetes apps share a single wildcard ssl certificate. But when I deploy mangeto, I   run into issue like this.

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "example.io-tls" in namespace "magento" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "magento"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "magento"
```

That means the scripts are trying to create this secret which I've already had. I read the code and found that

In this file:
https://github.com/bitnami/charts/blob/master/bitnami/magento/values.yaml
```
certManager: false
```
is deprecated. But in here

https://github.com/bitnami/charts/blob/master/bitnami/magento/templates/tls-secrets.yaml

```
{{- if and .Values.ingress.tls (not .Values.ingress.certManager) }}
{{- $ca := genCA "magento-ca" 365 }}
{{- $cert := genSignedCert .Values.ingress.hostname nil (list .Values.ingress.hostname) 365 $ca }}
```

This part still rely on `certManager` to decide whether create a new ssl. When I removed the whole content from this file, the error message is gone. Need to find out a way to properly allow not creating the ssl and use existing ssl instead.

### What do you see instead?

ignoring this.

**Comment by alemorcuq** [comment]
Thanks, will check this.
