### ISSUE TITLE
kube-prometheus, add support for new ingress backend.service.name instead of serviceName

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9491]
### Name and Version

kube-prometheus:latest

### What is the problem this feature will solve?

maintain current kubernetes standard

### What is the feature you are proposing to solve the problem?

check api version and use appropriate style, you can use technique implemented here:
https://github.com/twuni/docker-registry.helm/blob/main/templates/ingress.yaml

**Comment by karezza** [comment]
Closing, yes, the technique you speak of was unfamiliar to me.  It works just fine.
