### ISSUE TITLE
[bitnami/kafka] Add SSL for Zookeeper

### ISSUE THREAD

**Issue by yohboy** [bitnami/charts#9503]
### Name and Version

[bitnami/kafka] 15.5.0

### What is the problem this feature will solve?

Currently, Kafka supports SSL for brokers and clients. The Kafka chart also allows enabling and managing Zookeeper from Kafka chart. However, there are no parameters to configure SSL for Zookeeper quorum and clients (both Kafka side and Zookeeper side).

### What is the feature you are proposing to solve the problem?

I think there are mainly 2 solutions to enable SSL:
- Adding parameters for both Zookeeper and Kafka inside Kafka chart. We can use the same parameters defined in the Zookeeper chart: `tls.*`
- Disabling Zookeeper from Kafka chart and using `externalZookeeper.servers`. The user has to manage its "external" zookeeper server(s). Then, we just need to add some Kafka parameters to connect Zookeeper with SSL.
I think the most interesting (and user-friendly) solution is the first one, but it asks for extra work. I am interested in submitting a PR for this use case, but I would like to have feedback on the solution(s) before implementing it. Thank you!

PS: it is beyond the scope of this issue, but is there any reason why exposed Zookeeper parameters in the Kafka chart are not the same as the ones in the Zookeeper chart? It would be interesting to be able to add metrics for Zookeeper directly from Kafka chart too, but maybe better to use an "external" server in this case? I wonder to know your feelings about that.

### What alternatives have you considered?

N/A

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.
[Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
