### ISSUE TITLE
Azure Private DNS Zone

### ISSUE THREAD

**Issue by techdecline** [bitnami/charts#9507]
### Name and Version

bitnami/external-dns:6.2.1

### What is the problem this feature will solve?

For Alibaba and AWS it is supported to manage private DNS Zones, but this does not work for Azure as you will receive messages that your zone is not suitable: "Ignoring changes to 'nginx.xxx.xxx.com' because a suitable Azure DNS zone was not found".

### What is the feature you are proposing to solve the problem?

There should be a parameter like azure.PrivateDnsZone indicating the given DNS zone should be a private one.

**Comment by techdecline** [comment]
I just realized you can set the provider to "azure-private-dns" and leave everything else as described to implement external-dns for private Azure DNS zones as documented at [the repos documentation](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure-private-dns.md).

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing your findings.
