### ISSUE TITLE
[bitnami/harbor] rollingUpdate may not be specified when strategy `type` is 'Recreate'

### ISSUE THREAD

**Issue by lindhe** [bitnami/charts#9515]
### Name and Version

bitnami/harbor 12.1.3

### What steps will reproduce the bug?

Installing the bitnami/harbor chart with `jobservice.updateStrategy.type` set to `Recreate` causes the following error in Kubernetes:

```shell
The Deployment "foo-harbor-jobservice" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

This is because `rollingUpdate` is set to `{}` [here](https://github.com/bitnami/charts/blob/5b159a70ec71d4a59280be1cdb8091660502e51e/bitnami/harbor/values.yaml#L1627) and the entire `jobservice.updateStrategy` [is included in the template](https://github.com/bitnami/charts/blob/5b159a70ec71d4a59280be1cdb8091660502e51e/bitnami/harbor/templates/jobservice/jobservice-dpl.yaml#L20). It would be a much better user experience if `rollingUpdate` was only included if `type=RollingUpdate`.

## MWE

Here's a minimal "working" example of this bug:
 
```shell
helm template foo bitnami/harbor --version 12.1.3 --set 'jobservice.updateStrategy.type=Recreate' | grep '# Source: harbor/templates/jobservice/jobservice-dpl.yaml' -A 123 | kubectl apply --dry-run=server -f -
```

### Are you using any custom parameters or values?

`--set 'jobservice.updateStrategy.type=Recreate'`

(this ought to be true for all `*.updateStrategy.type` fields, but I have only tried it on `jobservice`)

### What is the expected behavior?

Setting `*.updateStrategy.type=Recreate` should be valid without having to do other things to make sure it works.

### What do you see instead?

The Kubernetes server returns the following error:

```
The Deployment "foo-harbor-jobservice" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

## Workaround

This problem can be worked around by setting `jobservice.updateStrategy.rollingUpdate=null`

## `helm version`

```shell
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

## `kubectl version`

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-17T03:51:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lindhe** [comment]
It seems this bug was introduced with #9263 so perhaps you have this issue in other Charts too?

**Comment by miguelaeh** [comment]
Thank you for the report, the above PR should fix the issue. Looks like in other charts it is correct

**Comment by lindhe** [comment]
Please no stale.
