### ISSUE TITLE
harbor, add oidc configuration to helm chart

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9521]
### Name and Version

bitnami/harbor:latest

### What is the problem this feature will solve?

for a gitops setup it is nice to have all configuration in a repo rather than have to configure something after it is deployed

### What is the feature you are proposing to solve the problem?

.

**Comment by rafariossaa** [comment]
Hi,
  I am creating an internal task to add support for this, however I can not provide an ETA.
  Meanwhile feel free to send a PR adding this. We will be glad to review and merge it.
