### ISSUE TITLE
[bitnami/harbor]: Admin Password Not Update After Reinstall

### ISSUE THREAD

**Issue by weichensun** [bitnami/charts#9524]
### Name and Version

bitnami/harbor

### What steps will reproduce the bug?

1. Helm Install bitnami/harbor
2. Get password with command
    `kubectl get secret --namespace harbor-registry harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode`
    (Remember old password)
4. Helm uninstall bitnami/harbor
5. Helm Install bitnami/harbor again
6. Get password with command
    `kubectl get secret --namespace harbor-registry harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode`
    (Get new password)
7. Login harbor in web console with admin and new password. (Get `Invalid user name or password`)

### Are you using any custom parameters or values?

---
persistence:
  persistentVolumeClaim:
    registry:
      size: "5Gi"
      accessModes:
        - "ReadWriteMany"
    jobservice:
      accessModes:
        - "ReadWriteMany"
    chartmuseum:
      accessModes:
        - "ReadWriteMany"
    trivy:
      accessModes:
        - "ReadWriteMany"
redis:
  master:
    persistence:
      size: "8Gi"
      accessModes:
        - "ReadWriteMany"
postgresql:
  primary:
    persistence:
      size: "8Gi"
      accessModes:
        - "ReadWriteMany"

### What is the expected behavior?

After reinstall harbor.
Should be able to login admin with new password

### What do you see instead?

Invalid user name or password

### Additional information

StorageClass: LongHorn

Cannot login admin with new password.
But able to login admin with old password.

Or remove all pvc before reinstall, but data will be lost.

**Comment by rafariossaa** [comment]
Hi,
  This is intended, if the data are persisted you need to use the password for the first installation, the password is not reset if the chart is redeployed and you reuse the existing PVCs.

**Comment by weichensun** [comment]
Ok, got it. Thanks
