### ISSUE TITLE
[Elasticsearch] Bad Elasticsearch hosts when no coordinating or no data node

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#9527]
### Name and Version

bitnami/elasticsearch 17.9.16

### What steps will reproduce the bug?

The hosts provided through environment variables to the elasticsearch pods do not reflect the real ones. If the data node or the coordinating node is not configured in the chart, the hosts variable is not correctly updated.

The issue seems to come from this code:

```yaml
{{/*
Return the hostname of every ElasticSearch seed node
*/}}
{{- define "elasticsearch.hosts" -}}
{{- $clusterDomain := .Values.clusterDomain }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $masterFullname := include "elasticsearch.master.fullname" . }}
{{- $coordinatingFullname := include "elasticsearch.coordinating.fullname" . }}
{{- $dataFullname := include "elasticsearch.data.fullname" . }}
{{- $ingestFullname := include "elasticsearch.ingest.fullname" . }}
{{- $masterFullname }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }},
{{- $coordinatingFullname }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }},
{{- $dataFullname }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }},
{{- if .Values.ingest.enabled }}
{{- $ingestFullname }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }},
{{- end -}}
{{- end -}}
```

The DNS of the three nodes is always configured.

### Are you using any custom parameters or values?

```yaml
master:
  replicas: 1

coordinating:
  replicas: 0

data:
  replicas: 1
```

### What is the expected behavior?

`ELASTICSEARCH_CLUSTER_HOSTS = alaska-elasticsearch-master.default.svc.cluster.local,alaska-elasticsearch-data.default.svc.cluster.local,`

### What do you see instead?

`ELASTICSEARCH_CLUSTER_HOSTS = alaska-elasticsearch-master.default.svc.cluster.local,alaska-elasticsearch-coordinating-only.default.svc.cluster.local,alaska-elasticsearch-data.default.svc.cluster.local,`

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jaudiger** [comment]
Hi @carrodher,

Sure, I'll create a PR to fix this issue. I'll let you know once create.

**Comment by jaudiger** [comment]
@carrodher, I just opened this PR to fix this issue: https://github.com/bitnami/charts/pull/9530

**Comment by carrodher** [comment]
Thanks! We will review it and provide feedback
