### ISSUE TITLE
[bitnami/redis-cluster] metric container reveals redis password if debug is enabled

### ISSUE THREAD

**Issue by alert101-gof** [bitnami/charts#9531]
### Name and Version

bitnami/redis-cluster 7.4.1

### What steps will reproduce the bug?

Add the following extraArgs to the metrics section and the metrics container will print out the redis password in the log.
```yaml
metrics:
  extraArgs:
    debug: true
```

### What is the expected behavior?

Redis password shouldn't be printed out.

### What do you see instead?

The redis password is printed in the logs.

**Comment by alemorcuq** [comment]
Thanks for reporting this, we will investigate it.

**Comment by alemorcuq** [comment]
I was able to reproduce the issue, @alert101-gof. However, I think this is something intrinsic to the Redis Exporter as it prints all the exporter options when the log level is debug: https://github.com/oliver006/redis_exporter/blob/bc033de94093d5d52a55449d716fcb6d73387832/exporter/exporter.go#L84
