### ISSUE TITLE
harbor, 1.18: request which chart version will work with older kubernetes 1.18 (documentation add)

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9543]
### Name and Version

bitnami/harbor:latest

### What is the problem this feature will solve?

Unfortunately, at the moment I am still working with 1.18.  Recently I unstalled harbor and went to reinstall only to discover too much has changed.  In my attempts to reinstall I keep getting "too many redirects".  In my efforts to resolve this I noticed a requirement of 1.19 has appeared.

Before I troubleshoot too much, it would be helpful to know which at which chart the breaking change occured with 1.18 working before and 1.19 required from then on.

### What is the feature you are proposing to solve the problem?

add a note to the requirements section noting which version works with 1.18

**Comment by carrodher** [comment]
Currently, the way to check what changed from one version to another is by looking at the [commit history](https://github.com/bitnami/charts/commits/master/bitnami/harbor). Notable changes are highlighted in the README, see https://github.com/bitnami/charts/blob/master/bitnami/harbor/README.md#upgrading
