### ISSUE TITLE
WordPress Multisite Certificado por Bitnami y Automattic 5.9.2-1

### ISSUE THREAD

**Issue by codebio** [bitnami/charts#9545]
### Name and Version

WordPress Multisite Certificado por Bitnami y Automattic 5.9.2-1

### What steps will reproduce the bug?

Bitnami Diagnostic tool.

    ? Apache: Found possible issues
    ? Mariadb: Found possible issues
    ✓ Connectivity: No issues found
    ✓ Wordpress: No issues found
    ✓ Resources: No issues found
    ✓ Processes: No issues found
    ✓ Php: No issues found

[Apache]

Found recent error or warning messages in the Apache error log.
```
[Mon Mar 21 14:47:17.402402 2022] [core:error] [pid 2654:tid 140043179882240] 
[client **ip_address**:57219] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Tue Mar 22 20:32:11.052901 2022] [core:error] [pid 15345:tid 140496567531264] 
Press [Enter] to continue:
[client **ip_address**:55623] AH00124: Request exceeded the limit of 10 internal 
redirects due to probable configuration error. Use 'LimitInternalRecursion' to 
increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
 [Wed Mar 23 13:35:15.301488 2022] [authz_core:error] [pid 15792:tid 
140496441640704] [client **ip_address**:46432] AH01630: client denied by server 
configuration: /opt/bitnami/apache/cgi-bin

[Mariadb]

Found recent error messages in the MariaDB error log:
```
2022-03-21 0:57:42 635 [Warning] Aborted connection 635 to db: 
'bitnami_wordpress' user: 'bn_wordpress' host: 'localhost' (Got an error reading 
communication packets)

### Are you using any custom parameters or values?

NA

### What is the expected behavior?

NA

### What do you see instead?

NA

### Additional information

code: 3050ed79-aa79-69bb-0a75-933e28979cc4

**Comment by carrodher** [comment]
Hi, we provide support for containers and Helm charts in GitHub, but the support for different kinds of assets like MultiTiers, VIrtual Machines, native installers, etc is provided in our community forum (https://community.bitnami.com/). Can you please post your question in this forum? Thanks
