### ISSUE TITLE
[apache] Init container fails to clone the git repo again #7966 

### ISSUE THREAD

**Issue by cuttingedge1109** [bitnami/charts#9546]
### Name and Version

bitnami/apache

### What steps will reproduce the bug?

This is not a new issue. I just tried to reopen https://github.com/bitnami/charts/issues/7966.
I added the suggestion https://github.com/bitnami/charts/pull/7970#discussion_r833983812.
Please check.

**Describe bug**
I clone htdocs from Github and use `emptyDir` as the volume type.
It works at the first time but once the pod is restarted, then the initContainer `git-clone-repository` failed with the following error.
```
fatal: destination path '/app' already exists and is not an empty directory.
```
So I can see that the initContainer clones the git repo in `/app` path. But that is already there because that path is emptyDir volume.

**To Reproduce**
Rollout, scale down and up again deployments are not the cases. Also to delete the pod is not the case because those actions will delete the emptyDir. EmptyDir is removed once the pod is removed from the node.

Only when the same pod is restarted, we get the issue. This can be reproduced when memory usage of the pod is over, OOM killed.

### What is the expected behavior?

It would be good to remove all contents in the `/app` before the clone.
```
        initContainers:
        - command:
          - /bin/bash
          - -ec
          - |
            cd /app
            rm -rf ..?* .[!.]* *
            git clone ****
```

### What do you see instead?

I clone htdocs from Github and use `emptyDir` as the volume type.
It works at the first time but once the pod is restarted, then the initContainer `git-clone-repository` failed with the following error.
```
fatal: destination path '/app' already exists and is not an empty directory.
```

### Additional information

Not related to helm or kubectl version.
Thanks.

**Comment by migruiz4** [comment]
Thank you for reporting this issue and for your contribution @cuttingedge1109.

My colleague @javsalgar will review your PR.
