### ISSUE TITLE
bitnami/moodle/

### ISSUE THREAD

**Issue by chris12399** [bitnami/charts#9550]
reference by https://github.com/bitnami/charts/blob/master/bitnami/moodle/values.yaml

**Comment by javsalgar** [comment]
Hi! Thank you for using Bitnami.

Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

**Comment by chris12399** [comment]
> reference by https://github.com/bitnami/charts/blob/master/bitnami/moodle/values.yaml
