### ISSUE TITLE
Redis Plugin Not Enabled

### ISSUE THREAD

**Issue by jesseadev** [bitnami/charts#9554]
### Name and Version

bitnami/moodle:latest

### What steps will reproduce the bug?

ENV: EKS, EFS, RDS.

Issue: Slow page load times and unable to enable Redis Plugin. See image below.

![Redis Highlighted in Grey](https://user-images.githubusercontent.com/101015204/159913000-5f3674c4-5cd0-4465-b845-46b830ce6ca4.png)

### What is the expected behavior?

A green checkbox and "Add Instance" under actions to add the Redis Server configuration.

### What do you see instead?

No checkbox and no way to "Add Instance" under actions to add the Redis Server configuration.

### Additional information

Any workarounds?

_No response_

**Comment by javsalgar** [comment]
Hi! Thank you for using Bitnami. Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.
