### ISSUE TITLE
[postgresql] Nextcloud fails when providing persistence to postgresql

### ISSUE THREAD

**Issue by reavessm** [bitnami/charts#9564]
### Name and Version

bitnami/postgrestql 10.16.2

### What steps will reproduce the bug?

1. Install nextcloud via [nextcloud's helm chart](https://github.com/nextcloud/helm/blob/master/charts/nextcloud/Chart.yaml)
2. configure yaml:

```yaml
postgresql:
  enabled: true
  seviceAccountName: "homelab-nextcloud"
  persistence:
    enabled: true
    storageClass: "nfs-client"
    accessMode: ReadWriteMany
    size: 8Gi
```

3. `helm install -f values.yaml my-nextcloud nextcloud/nextcloud`
4. Watch Postgresql crash loop
5. Change postgresql.persistence.enabled = false
6. `helm uninstall my-nextcloud && helm install -f values.yaml my-nextcloud nextcloud/nextcloud`
7. Watch Postgresql boot correctly

### Are you using any custom parameters or values?

persistence.enabled: true

### What is the expected behavior?

Boot container properly

### What do you see instead?

crashloopBackoff with the following logs:

```
postgresql 18:33:51.40
postgresql 18:33:51.40 Welcome to the Bitnami postgresql container
postgresql 18:33:51.41 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 18:33:51.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 18:33:51.41
postgresql 18:33:51.42 INFO ==> ** Starting PostgreSQL setup **
postgresql 18:33:51.45 INFO ==> Validating settings in POSTGRESQL_* env vars..
postgresql 18:33:51.46 INFO ==> Loading custom pre-init scripts...
postgresql 18:33:51.46 INFO ==> Initializing PostgreSQL database...
postgresql 18:33:51.49 INFO ==> pg_hba.conf file not detected. Generating it...
postgresql 18:33:51.49 INFO ==> Generating local authentication configuration
```

### Additional information

I am running this on Openshift, I had this working on a previous cluster, and pvcs work fine on other containers.

**Comment by javsalgar** [comment]
Hi,

Could you launch the chart with`image.debug=true`? This should provide more logs

**Comment by reavessm** [comment]
@javsalgar adding the debug logs let me know that the issue was with user permissions on the nfs vol that backed the pvc.  A simple chown fixed my issue.  Thank you for pointing that out!
