### ISSUE TITLE
Helm repository reliability

### ISSUE THREAD

**Issue by pascal-vs** [bitnami/charts#957]
**Which chart**:

All

**Description**

The bitnami helm chart repository seems to be not reliable.

**Steps to reproduce the issue:**

Sometimes (not always!), the following commands are stucked:

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm package --dependency-update <ANY_OF_MY_CHARTS>
```

example: after 30 sec. I did "CTRL-C"

```bash
time helm repo add bitnami https://charts.bitnami.com/bitnami
^C
helm repo add bitnami https://charts.bitnami.com/bitnami  0,26s user 0,05s system 0% cpu 37,177 total
```

**Describe the results you received:**

Impossible to install something.

**Describe the results you expected:**

A response received from the repository.

**Additional information you deem important (e.g. issue happens only occasionally):**

Other repositories I tried work fine.
Am I the only one experiencing this issue? At least my colleagues (same IP) have the same behavior.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by andresrc** [comment]
Hi @pascal-vs ,

Thanks for report. A few questions:
* When did you start experiencing the issue?
* Is it still happening?
* Are you behind a proxy?
