### ISSUE TITLE
[bitnami/external-dns] Validation of azure-resource-group not necessary

### ISSUE THREAD

**Issue by ams0** [bitnami/charts#9572]
### Name and Version

bitnami/external-dns 6.2.2

### What steps will reproduce the bug?

In Azure, using Managed Identity (thus, picking up `/etc/kubernetes/azure.json` from the host, it is still possible to override the resource group where the DNS zones resides ([link](https://github.com/kubernetes-sigs/external-dns/blob/570b51659fdc218281e3504a558a437178465f29/pkg/apis/externaldns/types.go#L424); however, the chart fails to render if you specify just:

```
azure:
  resourcegroup: xxx
```

with:

```
Error: execution error at (external-dns/templates/NOTES.txt:11:3):
VALUES VALIDATION:
external-dns: azure.tenantId
    You must provide the Azure Tenant ID when provider="azure" and resourceGroup is set.
    Please set the tenantId parameter (--set azure.tenantId="xxxx")
external-dns: azure.subscriptionId
    You must provide the Azure Subscription ID when provider="azure" and resourceGroup is set.
    Please set the subscriptionId parameter (--set azure.subscriptionId="xxxx")
```

This should be allowed. As a workaround, you can still pas arbitrary options like this:

```
  extraArgs: 
    azure-resource-group: dns
```

### Are you using any custom parameters or values?

extraArgs: 
  azure-resource-group: dns

### What is the expected behavior?

Chart allows for custom resource group even when MSI is used

### What do you see instead?

Fails with error on validation

**Comment by javsalgar** [comment]
Hi,

Thank you reporting. The validations are in _helpers.tpl. Would you like to submit a PR changing the validation?

**Comment by javsalgar** [comment]
Hi!

I created this PR, feel free to take a look
