### ISSUE TITLE
Shared Extra Env Vars Removed from Charts

### ISSUE THREAD

**Issue by ianchudson-caribou** [bitnami/charts#9579]
### Name and Version

bitnami/airflow 12.0.14

### What steps will reproduce the bug?

As part of: [bitnami/airflow] Chart standardization (https://github.com/bitnami/charts/pull/8909)

extraEnvVars shared value was removed from the airflow chart. (not sure why?)

The base values file was left alone leading the user (me) to believe I could still declare shared values across all containers.

This change should be rolled back because this means you have to repeat the same config for things like sidecars and environment values x3 in your config files to attach them to scheduler, worker and web containers.

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

The expected behavior is the ability configure the same across 3 containers.

### What do you see instead?

The values are dropped entirely because the include code was removed.

**Comment by migruiz4** [comment]
Hi @ianchudson-caribou,

Thank you for reporting this issue, and I'm sorry for the inconvenience.

The removal of `Values.extraEnvVars` wasn't intentional, so I will submit a PR fixing this.

**Comment by ianchudson-caribou** [comment]
> Hi @ianchudson-caribou,
> 
> Thank you for reporting this issue, and I'm sorry for the inconvenience.
> 
> The removal of `Values.extraEnvVars` wasn't intentional, so I will submit a PR fixing this.

Awesome, thanks! I wasn't sure if this was expected or accidental so I appreciate the reply. We are using the chart and was very confused when the shared configs weren't working as we expected so I dug through the git history. :)
