### ISSUE TITLE
[grafana] There's NOT an option to connect to a shared database as MySQL or Postgres

### ISSUE THREAD

**Issue by hernan-cision** [bitnami/charts#9587]
### Name and Version

bitnamy/grafana

### What is the problem this feature will solve?

[grafana] There's NOT an option to connect to a shared database as MySQL or Postgres

### What is the feature you are proposing to solve the problem?

In the README file, about High Availability, you suggest to [Set up Grafana for high availability](https://grafana.com/docs/grafana/v7.5/administration/set-up-for-high-availability/#set-up-grafana-for-high-availability)

It says that Setting up Grafana for high availability is fairly simple. You just need a shared database for storing dashboard, users, and other persistent data. So the default embedded SQLite database will not work, you will have to switch to MySQL or Postgres.

https://grafana.com/docs/grafana/v7.5/administration/configuration/

### What alternatives have you considered?

In the Values file shoul be an option to do it

externalDatabase: true
externalDatabaseType: # (MySQL or Grafana)
url: user: password: something else

Is there an option to enable an external database for HA using the Bitnami Grafana or Grafana-operator charts ?

**Comment by rafariossaa** [comment]
Hi,
  [In our README is indicated](https://github.com/bitnami/charts/tree/master/bitnami/grafana#supporting-ha-high-availability) that you need to provide a config file with the database configuration. This can be done [using a custom config file](https://github.com/bitnami/charts/tree/master/bitnami/grafana#using-custom-configuration).
  The links you mentioned are from grafana documentation.
