### ISSUE TITLE
[bitnami/argo-workflows]  cannot run workflows

### ISSUE THREAD

**Issue by luyang93** [bitnami/charts#9588]
### Name and Version

bitnami/argo-workflows:1.1.2

### What steps will reproduce the bug?

1. Deploy  bitnami/argo-workflows:1.1.2 by helm in namespace argohelm.
Submit workflow does not run into running state.
The controler and server get error message.
```
W0327 03:26:27.814504       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1alpha1.WorkflowTaskResult: the server could not find the requested resource (get [workflowtaskresults.argoproj.io](http://workflowtaskresults.argoproj.io/))
E0327 03:26:27.814524       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskResult: failed to list *v1alpha1.WorkflowTaskResult: the server could not find the requested resource (get [workflowtaskresults.argoproj.io](http://workflowtaskresults.argoproj.io/))
```
2. Continue with official command
https://github.com/argoproj/argo-workflows/releases/tag/v3.3.1
```
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.3.1/install.yaml
```
The install yaml create workflowtaskresults.argoproj.io
Then argohelm wolkflow finish successfully.

### What do you see instead?

Create create workflowtaskresults.argoproj.io when installing bitnami/argo-workflows:1.1.2 by helm.

**Comment by luyang93** [comment]
https://github.com/argoproj/argo-workflows/pull/8000

**Comment by alemorcuq** [comment]
Hi, @luyang93.

What do you mean by this?

>  Submit workflow does not run into running state.

Could you provide me with some steps to submit the workflow and reproduce the issue?

**Comment by luyang93** [comment]
https://cloud-native.slack.com/archives/C02097VUKUM/p1648262930247249
The fact that the task is not running is just a superficial phenomenon. The real reason is that argo >= 3.3.0, argo creates new CRDs, workflowtaskresults.argoproj.io, but when bitnami/argo-workflow is installed through helm, workflowtaskresults and the corresponding ClusterRole are not created.

**Comment by luyang93** [comment]
> Hi, @luyang93.
> 
> What do you mean by this?
> 
> > Submit workflow does not run into running state.
> 
> Could you provide me with some steps to submit the workflow and reproduce the issue?

https://cloud-native.slack.com/archives/C02097VUKUM/p1648262930247249
The fact that the task is not running is just a superficial phenomenon. The real reason is that argo >= 3.3.0, argo creates new CRDs, workflowtaskresults.argoproj.io, but when bitnami/argo-workflow is installed through helm, workflowtaskresults and the corresponding ClusterRole are not created.

**Comment by franviera92** [comment]
what is the solution? my job have status pending and never change

**Comment by alemorcuq** [comment]
I can't access to that Slack, @luyang93, but I understand there's some CRD missing from the chart in [this directory](https://github.com/bitnami/charts/tree/master/bitnami/argo-workflows/crds) ?

**Comment by luyang93** [comment]
> I can't access to that Slack, @luyang93, but I understand there's some CRD missing from the chart in [this directory](https://github.com/bitnami/charts/tree/master/bitnami/argo-workflows/crds) ?

Yes, missing this CRD and role binding, https://github.com/argoproj/argo-workflows/blob/master/manifests/base/crds/full/argoproj.io_workflowtaskresults.yaml
![image](https://user-images.githubusercontent.com/39150988/161399850-d06d4e76-e7e2-4066-bf76-e0d375a5cd17.png)

**Comment by luyang93** [comment]
> what is the solution? my job have status pending and never change

Fallback version to 3.2.9?

**Comment by alemorcuq** [comment]
I've created a PR adding the missing CRD. Hope this fixes your issue.

**Comment by franviera92** [comment]
i try worked with chart version 1.1.4 and no is work

**Comment by luyang93** [comment]
> I've created a PR adding the missing CRD. Hope this fixes your issue.

Maybe still missing ClusterRole or  Rolebinding.
[apiGroups](https://github.com/argoproj/argo-workflows/blob/153540fdd0e3b6f00050550abed67cae16299cbe/manifests/install.yaml#L945)

**Comment by alemorcuq** [comment]
Will you be willing to contribute with a PR?

**Comment by luyang93** [comment]
ok, I'll try to do that.I know little about helm templates.
