### ISSUE TITLE
mariadb-galera not starting all pods

### ISSUE THREAD

**Issue by albertkohl-monotek** [bitnami/charts#9591]
### Name and Version

bitnami/mariadb-galera

### What steps will reproduce the bug?

i'm using microk8s with a helm install of bitnami/mariadb-galera.
i had the cluster set to 3 replicas. after changing some system settings for my cluster, i rebooted two of the nodes (at the same time) which basically broke the cluster.

once everything came back up, i deleted the galera pods that were stuck "terminating" with --force. since then, the cluster only spints up galera-0 and wont spin up any of the other pods. all other services in the cluster came back up working properly, so i think it's something specific to galera.

### What is the expected behavior?

for all 3 replicas to spin up

### What do you see instead?

only galera-0 starts. the other two replicas dont even show up with: k get pods -A

### Additional information

any help to get the cluster to start up the other two pods.

sorry if i'm not providing enough info, i'm still learning k8s :)

**Comment by migruiz4** [comment]
Hi @albertkohl-monotek,

Could you please share more information about your deployment?
* What version of the mariadb-galera chart are you using? (`helm list`, field `CHART`)
* Did you deploying the mariadb-galera with any custom value? If so, please share the command used to deploy and custom values.yaml if so.
* Could you please share the logs of the galera pods? You can get them using `kubectl logs <pod_name>` and `kubectl logs -p <pod_name>`. Flag `-p` is used to get logs of the previous instance in case the current one does not return any significant log.
* It would be helpful if you could share the output of `kubectl describe <galera_pod_name>` of at least one of the failing pod, so see if the liveness/readiness probe failed and why.

**Comment by albertkohl-monotek** [comment]
@migruiz4 

- version: **mariadb-galera-7.0.6**
- custom values: **none**
- logs from mariadb-galera-0: [mariadb-galera-0.log](https://github.com/bitnami/charts/files/8363395/mariadb-galera-0.log)
- other galera pods: **no other pods even exists, that's my problem, they dont show up at all as if they were removed from the statefulset. but the statefulset shows 0/3 replicas...**

 Thanks! i appreciate your help!

**Comment by albertkohl-monotek** [comment]
> Hi @albertkohl-monotek,
> 
> In that case, could you please share the output of `kubectl describe statefulset <statefulset_name>`?

i did set the password to use a secret... here's the output:
[mariadb_statefulset.txt](https://github.com/bitnami/charts/files/8364859/mariadb_statefulset.txt)

**Comment by migruiz4** [comment]
Hi @albertkohl-monotek,

Sorry for the late response. One last request from my side to ensure I have all the information I need.

Could you please share the output of `kubectl describe pod <galera_pod_0>` and `kubectl get pods`?

I would like to check if the Galera pod 0 readiness and liveness probes are succeeding or not, and the reason why.

**Comment by albertkohl-monotek** [comment]
@migruiz4, no worries, i'm sure you all are busy. i appreciate the help.

outputs are attached.
[mariadb_pods.txt](https://github.com/bitnami/charts/files/8380927/mariadb_pods.txt)

**Comment by albertkohl-monotek** [comment]
@migruiz4, hello! just following up.
