### ISSUE TITLE
Secondary pods hang at upgrade step and eventually fail

### ISSUE THREAD

**Issue by puckettgw** [bitnami/charts#9592]
### Name and Version

bitnami/mysql 8.8.27

### What steps will reproduce the bug?

Install this chart, scale up secondary statefulset, watch it burn

Hangs at [System] [MY-013381] [Server] Server upgrade from '80028' to '80028' started.

I'm using mysql-8.8.27 chart version.

The PVCs are in a very fast ceph cluster, fast enough to provide backing for numerous game servers, mariadb instances and postgres instances. There's no way it's being caused by the pvcs.

If I set the initialDelayPeriod on all the checks for these secondary pods to something insane like 20 minutes, it still hangs at this point and eventually throws a "MySQL failed to start" error if it stops hanging before the checks fail.
I already have BITNAMI_DEBUG enabled in the statefulset, all I get when it does actually fail out is:

2022-03-27T18:47:05.297912Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-03-27T18:47:08.540219Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-03-27T18:47:09.017335Z 4 [System] [MY-013381] [Server] Server upgrade from '80028' to '80028' started.
mysql 18:57:06.25 ERROR ==> MySQL failed to start
and then the pod dies.

This occurs even if I delete the PVC for the secondary and scale the statefulset to 0/back to 1.

### Are you using any custom parameters or values?

initialDelaySeconds for all probes set to 1200 to see if it'll stop hanging eventually
resources on both statefulsets (primary and secondary) set to 2cpu/4gb ram
storageclass `rook-ceph-block` (ceph-rbd volume)
extraFlags `--bind-address=0.0.0.0`

### What is the expected behavior?

Secondary instances should come up and work.

### What do you see instead?

Secondary instances hang forever and eventually die.

**Comment by fmulero** [comment]
Hi @puckettgw 

Thanks for sharing your issue. There is one thing I don't fully understand, what do you mean with:

> scale up secondary statefulset, watch it burn

Are you working with the `standalone` configuration but trying to spin up manually new instances? Please be aware that they won't work as a cluster. If you want a mysql cluster please set to `replication` the `architecture` parameter
