### ISSUE TITLE
[bitnami/grafana-operator] dashboardlabelselector will not work

### ISSUE THREAD

**Issue by 1naboki1** [bitnami/charts#9597]
### Name and Version

bitnami/grafana-operator:4.2.0

### What steps will reproduce the bug?

1. Deploy grafana operator
2. enable grafana inside the grafana operator 
3. create a dashboard like https://github.com/grafana-operator/grafana-operator/blob/master/documentation/dashboards.md
4. use label app: grafana

### Are you using any custom parameters or values?

dashboardLabelSelector:
  - matchExpressions:
      - { key: app, operator: In, values: [ grafana ] }

### What is the expected behavior?

To select the dashboards based on the label specified in the 

### What do you see instead?

dashboardLabelSelector: null

### Additional information

in templates/grafana.yaml

https://github.com/bitnami/charts/blob/49ac74572f62275a16b68786376e6aabe3c769b3/bitnami/grafana-operator/templates/grafana.yaml#L185

fix it like this:

dashboardLabelSelector: {{- include "common.tplvalues.render" (dict "value" .Values.grafana.dashboardLabelSelector "context" $ ) | nindent 4 }}

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out.
  As  you provide a fix for the issue, would you like to send a PR ?
