### ISSUE TITLE
[metallb] support new FRR / Dualstack mode (v0.12)

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#9598]
### Name and Version

bitnami/metallb 2.6.10

### What is the problem this feature will solve?

I like to test the new dualstack compatibillity with k3s and metallb

https://metallb.universe.tf/release-notes/#version-0-12-1

### What is the feature you are proposing to solve the problem?

Add the same FRR support like the official chart

### What alternatives have you considered?

Use the official chart.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this, but currently it seems that it stills being an experimental feature:
```
Version 0.12.1

Bug Fixes:

    (helm chart) FRR mode disabled by default as the FRR mode is still experimental (can be optionally enabled). ([PR #1222](https://github.com/metallb/metallb/pull/1222))
```

**Comment by viceice** [comment]
I know, will hopefully be stable soon 🙃

Maybe add a short message to the readme, that this isn't yet supported? So users coming from metallb docs will see this early?

**Comment by rafariossaa** [comment]
I am sorry, but it would be impossible to keep track of this kind of things in an automatic way. We are a small team and it is not possible to keep track manually of this.

**Comment by viceice** [comment]
OK, no problem. I'll come back when FRR feature becomes stable. 🤗

**Comment by rafariossaa** [comment]
Thanks for your understanding. 
I am closing this issue by now.
