### ISSUE TITLE
appProtocol in charts for easier service mesh integration

### ISSUE THREAD

**Issue by dasMulli** [bitnami/charts#9601]
### Name and Version

postgresql-ha/8.6.4

### What is the problem this feature will solve?

Service Meshes such as OpenServiceMesh and Istio implement protocol detection in different ways but seem to be centered around utilizing `appProtocol` for explicit protocol detection. This is especially needed for server-first protocols and thus the service port's `appProtocol` field should be influencable from helm charts.

This can currently be achieved by using post-renderes but is still tricky - e.g. we want to avoid setting it for metrics services that are http by default.

### What is the feature you are proposing to solve the problem?

Inflencing the `appProtocol` would be great for many charts (not only postgres for which I'm currently investigating this)

### What alternatives have you considered?

Depending on the systems used, helm post renderes can be used to "kustomize" the rendered yaml - however this is also tricky to avoid misconfiguring metrics services and might not be possible for all methods of deploying a chart (thinking of Rancher's Marketplace UIs for example)

**Comment by miguelaeh** [comment]
Hi @dasMulli ,

We don't officially support Istio or other services, but we sometimes try to add the Istio requirement in the ports naming like `protocol-portName`.
You can always clone this repo and perform your required modifications or send a PR.
