### ISSUE TITLE
Permission denied on /opt/bitnami/redis-sentinel/etc when sentinel.persistance.enable=false + SecurityContext

### ISSUE THREAD

**Issue by lretrain91** [bitnami/charts#9603]
### Name and Version

bitnami redis-chart 16.6.0

### What steps will reproduce the bug?

ligne 414 of redis/templates/sentinel/statefulset.yaml
```yaml
 {{- if .Values.sentinel.persistence.enabled }}
            - name: sentinel-data
              mountPath: /opt/bitnami/redis-sentinel/etc
{{- end }}
```

sentinel-data VolumMount is under conditional on persistence to true.
Then the Volume is never mounted in the case that you don't want persistence.
This is not a problem with the default chart values.yaml but when you want to set a sentinel containerSecurityContext to:
```yaml
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
```
and also a podSecurityContext :
```yaml
  podSecurityContext:
    enabled: true
    fsGroup: 1001
```
Then /opt/bitnami/redis-sentinel/etc path stay with permission root:root
That cause the `cp: cannot create regular file '/opt/bitnami/redis-sentinel/etc/sentinel.conf': Permission denied`

Is there a reason to keep the `{{- if .Values.sentinel.persistence.enabled }}` conditional on sentinel-data VolumeMount?

Removing it fixes the issue.

### What is the expected behavior?
```console
$ kubectl logs redis-node-0 -c sentinel -n visualization  
15:55:32.68 INFO  ==> about to run the command: redis-cli -h redis.visualization.svc.cluster.local -p 26379 sentinel get-master-addr-by-name kastmaster
Could not connect to Redis at redis.visualization.svc.cluster.local:26379: Connection refused
1:X 28 Mar 2022 15:55:33.745 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 28 Mar 2022 15:55:33.745 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 28 Mar 2022 15:55:33.745 # Configuration loaded
1:X 28 Mar 2022 15:55:33.746 * monotonic clock: POSIX clock_gettime
1:X 28 Mar 2022 15:55:33.747 * Running mode=sentinel, port=26379.
1:X 28 Mar 2022 15:55:33.747 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 28 Mar 2022 15:55:33.747 # Sentinel ID is 2a09ba7abbb41ee71e79087310d75f9809c3c815
1:X 28 Mar 2022 15:55:33.747 # +monitor master kastmaster redis-node-0.redis-headless.visualization.svc.cluster.local 6379 quorum 2
```

### What do you see instead?
```console
$ kubectl logs redis-node-0 -c sentinel -n visualization 
cp: cannot create regular file '/opt/bitnami/redis-sentinel/etc/sentinel.conf': Permission denied
/opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 97: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
/opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 126: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
/opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 127: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
/opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 128: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
/opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 129: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
/opt/bitnami/scripts/start-scripts/start-sentinel.sh: line 130: /opt/bitnami/redis-sentinel/etc/sentinel.conf: Permission denied
1:X 28 Mar 2022 11:50:24.256 # Sentinel config file /opt/bitnami/redis-sentinel/etc/sentinel.conf is not writable: Permission denied. Exiting..
```

**Comment by aeber** [comment]
Hi!

I think this is an unintended side-effect of https://github.com/bitnami/charts/pull/9282

In that PR, the previous emptyDir mount over `/opt/bitnami/redis-sentinel/etc` got [removed](https://github.com/bitnami/charts/pull/9282/files#diff-8c384cc283443d7d59806d168ed118c26093f1e319071da23b06eaba2a99f08fL418),
 but the [new emptyDir](https://github.com/bitnami/charts/pull/9282/files#diff-8c384cc283443d7d59806d168ed118c26093f1e319071da23b06eaba2a99f08fR580) only gets mounted if `sentinel.persistence.enabled` is [enabled](https://github.com/bitnami/charts/pull/9282/files#diff-8c384cc283443d7d59806d168ed118c26093f1e319071da23b06eaba2a99f08fR413).

So as you already suggested, the ` {{- if .Values.sentinel.persistence.enabled }}` should be removed in https://github.com/bitnami/charts/blob/2fa5aad2f8028694faac6cb6b1397c64b39495e5/bitnami/redis/templates/sentinel/statefulset.yaml#L419

**Comment by rafariossaa** [comment]
Hi @lretrain91 and @aeber 
  As you have find the issue,  would you like to send a PR fixing it ?. We will be glad to review and merge it.
