### ISSUE TITLE
Error installing latest spring cloud dataflow - found character that cannot start any token

### ISSUE THREAD

**Issue by pravinkumarb84** [bitnami/charts#9605]
### Name and Version

bitnami/spring-cloud-dataflow 6.0.8

### What steps will reproduce the bug?

Hi.

I am trying to install spring-cloud-dataflow chart - version - 6.0.8 as a helm release via terraform. I am on the latest helm version and when I try to install it via terraform, getting the below mentioned error. 

when I try to install the same using `helm install` command from local machine, it works. the error is only during install via terraform.

### Are you using any custom parameters or values?

I have only added custom image repository values in tf file.

### What do you see instead?

getting this error on install:

`Error: YAML parse error on spring-cloud-dataflow/templates/skipper/deployment.yaml: error converting YAML to JSON: yaml: line 140: found character that cannot start any token`

**Comment by rafariossaa** [comment]
Hi,
  Not sure here as we don't use terraform. If it works using `helm install` it should be some parameters that terraform is passing to the templating.
