### ISSUE TITLE
Pods not starting up

### ISSUE THREAD

**Issue by parikshitseth1** [bitnami/charts#9611]
### Name and Version

Bitnami/rabbitmq 3.9.2203282201

### What steps will reproduce the bug?

Pods not starting up when deploying helm chart in IBM Cloud Kubernetes cluster. Getting below error:

Events:
  Type     Reason            Age   From                    Message
  ----     ------            ----  ----                    -------
  Warning  FailedScheduling  2m7s  default-scheduler       0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         2m6s  default-scheduler       Successfully assigned rabbitmq/rabbitmq2-fa91c537-0 to 10.184.254.53
  Warning  Unhealthy         95s   kubelet, 10.184.254.53  Readiness probe failed: Error: unable to perform an operation on node 'rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: ['rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local']

rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local:
  * connected to epmd (port 4369) on rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-286-rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local'
 * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq
 * Erlang cookie hash: ZtNadzlCDvqwGPxJFAv3VA==
  Warning  Unhealthy  65s  kubelet, 10.184.254.53  Readiness probe failed: Error: unable to perform an operation on node 'rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rabbitmq2-fa91c537-0.rabbitmq2-fa91c537-headless.rabbitmq.svc.cluster.local
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

### What do you see instead?

The pods should have started up

### Additional information

kubectl -n rabbitmq get all
NAME                       READY   STATUS    RESTARTS   AGE
pod/rabbitmq2-fa91c537-0   0/1     Running   0          90s

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
service/rabbitmq2-fa91c537            ClusterIP   172.21.212.64   <none>        5672/TCP,4369/TCP,25672/TCP,15672/TCP   90s
service/rabbitmq2-fa91c537-headless   ClusterIP   None            <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   90s

NAME                                  READY   AGE
statefulset.apps/rabbitmq2-fa91c537   0/1     90s
➜  FlyApps kubectl -n rabbitmq get pvc
NAME                        STATUS   VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-rabbitmq2-fa91c537-0   Bound    data-rabbitmq2-block   20Gi       RWO            ibmc-block-gold   102s

**Comment by javsalgar** [comment]
Hi,

This is strange, as we were unable to reproduce the issue. Could you confirm it is a clean deployment and there are no PVCs from other installations? Also, could you try entering the node and see if executing the same command that the readiness probe performs shows a more meaningful error? You could also launch the chart with `diagnosticMode.enabled=true` and launch the initialisation scripts manually.

**Comment by myysophia** [comment]
I did not find this issue, which should belong to the issue of authority, please see
https://github.com/bitnami/charts/issues/13017 @parikshitseth1
