### ISSUE TITLE
[bitnami/wordpress] Add Netapp azure files support [help requested]

### ISSUE THREAD

**Issue by dc232** [bitnami/charts#9613]
### Name and Version

bitnami/wordpress

### What is the problem this feature will solve?

```
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  14m (x6 over 94m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[wordpress-data], unattached volumes=[custom-postinit kube-api-access-x8jcr wordpress-data]: timed out waiting for the condition
  Warning  FailedMount  10m (x50 over 96m)    kubelet  MountVolume.SetUp failed for volume "pvc-f5b15aae-b758-4126-9012-c7f2642d6d36" : rpc error: code = Internal desc = error mounting NFS volume 192.1.0.4:/pvc-f5b15aae-b758-4126-9012-c7f2642d6d36 on mountpoint /var/lib/kubelet/pods/9627f587-b082-4b4b-87aa-ea81151d73f8/volumes/kubernetes.io~csi/
pvc-f5b15aae-b758-4126-9012-c7f2642d6d36/mount: exit status 32
  Warning  FailedMount  5m44s (x23 over 91m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[wordpress-data], unattached volumes=[wordpress-data custom-postinit kube-api-access-x8jcr]: timed out waiting for the condition
  Warning  FailedMount  68s (x11 over 85m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[wordpress-data], unattached volumes=[kube-api-access-x8jcr wordpress-data custom-postinit]: timed out waiting for the condition
```

currently when using the azure  netapp files CSI the following is produced despite having an active VNET

### What is the feature you are proposing to solve the problem?

Current thinking is  to add nfs tag such as in https://stackoverflow.com/questions/70282694/cannot-connect-nfs-server-with-azure-aks

tickets also referencing this problem

https://github.com/Azure/AKS/issues/223
https://github.com/NetApp/trident/issues/707

any additional help with the deployment greatly appreciated

will post output of pvc and pv in the coming days

### What alternatives have you considered?

https://github.com/Azure/AKS/issues/223
https://github.com/NetApp/trident/issues/707

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. It is not clear to me in this case if the issue has to do with the Bitnami packaging (or the chart features, which allow adding labels, annotations and extra objects) or with the Azure cloud itself. Did you create a ticket to Azure with this exact issue? I think they may provide more insight on what to do.
