### ISSUE TITLE
Documentation / Example on how to configure logstash to consume from kafka

### ISSUE THREAD

**Issue by stravi** [bitnami/charts#9616]
### Name and Version

bitnami/logstash 3.8.4

### What is the problem this feature will solve?

I have read the existing README for logstash chart but it is not clear for me how should I set the [`input` parameter for logstash](https://github.com/bitnami/charts/tree/master/bitnami/logstash#logstash-parameters) such that it consumes from a kafka topic. Looking at the default value for the parameter `input` I understand that it is supposed to be a string though reading the documentation for [plugins-inputs-kafka](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html) I understand that it has to be a structure something like:
```
kafka
    {
            bootstrap_servers => "localhost:9092"
            topics => "kafkatest2"
    }
```
Also it's not quite clear how to specify logstash what is the plugin I want it to use for input/output.

### What is the feature you are proposing to solve the problem?

I will be nice if you can provide an example and explain how to use the `input` parameter depending on the plugin one wants to use

**Comment by rafariossaa** [comment]
Hi,
  Sorry, I am not very sure about your question. If it is on how to use the chart or how to configure logstash for your purpose.
If it is about how to configure logstash, as we are not logstash experts,  I would suggest to better ask in logstash forums to get a better answer.

**Comment by stravi** [comment]
You are right, my question came from missing knowledge in both. Now that I made it work, the answer is that in bitnami/logstash values.yaml the `input` parameter has to be a string and it has to contain what ever you want to be contained in [logstash configuration file](https://www.elastic.co/guide/en/logstash/current/config-examples.html).
An example of seting the logstash `input` parameter from Chart values.yaml would be this:
```
  input: |
    kafka {
      bootstrap_servers => "localhost:9092"
      topics => "logstash"
    }
  output: |
    elasticsearch {
      hosts => ["localhost:9002"]
    }
    stdout {}
```
