### ISSUE TITLE
Error adding Bitnami package in Azure

### ISSUE THREAD

**Issue by Rafi-UCW** [bitnami/charts#9620]
### Name and Version

?

### What steps will reproduce the bug?

Trying to add bitnami package in Azure

### What do you see instead?

Error message

### Additional information

![image](https://user-images.githubusercontent.com/28951337/160798024-f15d9c83-195c-42c2-b811-bf23d8584dd8.png)

**Comment by carrodher** [comment]
Please note support for Virtual Machines and Cloud Images is provided at https://community.bitnami.com/ (where your screenshot comes from).
In GitHub, we provide support for Containers and Helm charts. Can you post your question in the above forum? Thanks
