### ISSUE TITLE
error calling include: template: no template "thanos.ingress.certManagerRequest" associated with template "gotpl"

### ISSUE THREAD

**Issue by danielorkabi8** [bitnami/charts#9627]
### Name and Version

bitnami/thanos:10.3.1

### What steps will reproduce the bug?

I was trying to add grpc ingress for the storegateway.
While adding a regular ingress (storegateway.ingress.enabled) things worked properly, however when I tried to add a grpc one (storegateway.ingress.grpc.enabled) I got the following error:

Error: UPGRADE FAILED: template: templates/storegateway/ingress-grpc.yaml:44:60: executing "templates/storegateway/ingress-grpc.yaml" at <include "thanos.ingress.certManagerRequest" .Values.storegateway.ingress.grpc.annotations>: error calling include: template: no template "thanos.ingress.certManagerRequest" associated with template "gotpl"

Comparing to the regular ingress it seems like they both use different helpers (common.ingress vs thanos.ingress).

### What do you see instead?

Error: UPGRADE FAILED: template: templates/storegateway/ingress-grpc.yaml:44:60: executing "templates/storegateway/ingress-grpc.yaml" at <include "thanos.ingress.certManagerRequest" .Values.storegateway.ingress.grpc.annotations>: error calling include: template: no template "thanos.ingress.certManagerRequest" associated with template "gotpl"

Comparing to the regular ingress it seems like they both use different helpers (common.ingress vs thanos.ingress).

**Comment by javsalgar** [comment]
Hi,

It seems to me that both should use the same helper. Would you like to submit a PR fixing it?

**Comment by danielorkabi8** [comment]
Sure :)
