### ISSUE TITLE
ulimitNofiles not working in rabbitmq chart

### ISSUE THREAD

**Issue by sharique-masood** [bitnami/charts#9632]
### Name and Version

 bitnami/rabbitmq:3.9.13-debian-10-r55

### What steps will reproduce the bug?

The parameter `ulimitNofiles: "65536"` in values.yaml  is not setting the ulimit for rabbitmq, the default/current ulimit being set is `1048576`. 

### Are you using any custom parameters or values?

Yes `ulimitNofiles: "65536"` in values.yaml

### What is the expected behavior?

The expected behaviour is that the parameter should set the ulimit value to `65536` in rabbitmq container.

### What do you see instead?

Seeing this value in rabbitmq container `1048576`.

**Comment by FraPazGal** [comment]
Hello @sharique-masood,

Thank you for reporting this error! I was able to reproduce your case and I have opened an internal task for the team to work on this bug. I will leave this ticket open until a fix has been implemented for this.

**Comment by sharique-masood** [comment]
Thanks @FraPazGal  will wait for the fix.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision of the container that fixes the issue with ulimit.

https://github.com/bitnami/bitnami-docker-rabbitmq/commit/5cfd04f2afa335f169b52a749dcf96a570198fc2

The chart is being updated with the latest image, so stay tuned.
