### ISSUE TITLE
MovingVM to another subscription

### ISSUE THREAD

**Issue by boima81** [bitnami/charts#9633]
### Name and Version

Virtual Machine V1

### What steps will reproduce the bug?

Moving Linux (ubuntu 14.04) VM V1 to another subscription is and getting the error " MarketplacePurchaseEligibilityFailed"

Microsoft said the plan (3-2) is no longer on their marketplace. And I should contact the publisher (bitnami).

Is there a workaround to move this VM to a new subscription? 

### What do you see instead?

error " MarketplacePurchaseEligibilityFailed"

**Comment by carrodher** [comment]
Hi, please note the support related to VMs, AMIs, MultiTier solutions, etc is provided in the [Bitnami Community Forum](https://community.bitnami.com/). Could you please post your question there?

In GitHub, we provide support for container images and Helm charts.
