### ISSUE TITLE
wordpressScheme doesn't produce efects in the Wordpress generated URLs

### ISSUE THREAD

**Issue by deoxyseia** [bitnami/charts#9649]
### Name and Version

bitnami/wordpress 13.1.11

### What steps will reproduce the bug?

Install Wordpres chart behind Nginx Ingress.

`helm install wordpress bitnami/wordpress -f values.yaml `

Registry the DNS record with the Nginx LB hostname with `wordpress.example.com`

### Are you using any custom parameters or values?

```yaml
wordpressScheme: https
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  hostname: wordpress.example.com
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
```

### What is the expected behavior?

Be able to load the Wordpress site in a browser using https://wordpress.example.com

### What do you see instead?

The statics fail to load:

![image](https://user-images.githubusercontent.com/1824764/161125013-ea15ea70-af03-4efd-be05-70c65ce268f8.png)

### Additional information

The Nginx Ingress supply and AWS NLB only has the 443 port opened. I'm using LB TLS termination using AWS ACM. The traffic from LB and Nginx is HTTP and the same happens to the service:

**Client** ----https-----> **NLB (TLS termination)** -----http----> **Nginx** ----http---> **Wordpress chart**

To write the Wordpress's URLs with https:// even though is serving using http port I set in _values.yaml_: `wordpressScheme: https` [ref](https://github.com/bitnami/charts/blob/f6b20dc7fdbdc589e8be590f33b03d852c9b0a13/bitnami/wordpress/values.yaml#L123)

The main GET request works well:

![image](https://user-images.githubusercontent.com/1824764/161123494-77b8ffa0-39a7-47f4-9190-103707671e6a.png)

But all the static referred by the index.html have http:// in the schema. Obviously, this fails to load all the static files:

![image](https://user-images.githubusercontent.com/1824764/161124102-73a2636c-b63a-440e-8746-0d4a9836e80f.png)

Testing the same static using CURL with https schema works well.

-------
Checking the template used by the chart [here](https://github.com/bitnami/charts/blob/f6b20dc7fdbdc589e8be590f33b03d852c9b0a13/bitnami/wordpress/templates/deployment.yaml#L166) the value of `wordpressScheme` is set as an environment variable to the Wordpress container but checking the Bitnami Worpress used [here](https://hub.docker.com/r/bitnami/wordpress) this variable is never required or documented.

Is this feature currently active?

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami WordPress Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

Regarding the `wordpressScheme` parameter, at Helm chart level is documented [here](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#wordpress-configuration-parameters). Then in the container, it is used just to change the schema to HTTP or HTTPS, see [those occurrences](https://github.com/bitnami/bitnami-docker-wordpress/search?q=WORDPRESS_SCHEME).
