### ISSUE TITLE
[bitnami/postgres] document (and possibly override) existingSecret keys

### ISSUE THREAD

**Issue by Startouf** [bitnami/charts#9659]
### Name and Version

bitnami/postgres

### What is the problem this feature will solve?

Inform the user of what keys are expected in existingSecret

THe postgres credentials can be confusing because there are
- the admin user "postgres" credentials
- the option non-admin database user often referred to as "postgresql"

When using an existingSecret, it is not clear what the values are for both of those

See the confusion mentioned in some comments there https://github.com/bitnami/charts/issues/2061

### What is the feature you are proposing to solve the problem?

Document the expected keys of existingSecret, like you already have done in most other charts.
Also, some charts let us override the secret key names, maybe this could be added as well ?

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
