### ISSUE TITLE
Running elasticsearch on AKS: Error executing 'postInstallation' - Invalid kernel settings

### ISSUE THREAD

**Issue by fdoxyz** [bitnami/charts#966]
**Chart**

bitnami/elasticsearch

**Description**

I'm trying to run the elasticsearch chart on AKS. I have the bitnami/elasticsearch image in my reposity, the Persistent Volumes are created correctly but when executing I'm running into the following issue (from 'data-0' pod logs):

```
Welcome to the Bitnami elasticsearch container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues

nami    INFO  Initializing elasticsearch
Error executing 'postInstallation': Invalid kernel settings. Elasticsearch requires at least:
- vm.max_map_count = 262144
- fs.file-max = 65536
```

I'm executing the following command to deploy the Chart:

`helm install bitnami/elasticsearch -f elasticsearch-config.yml --namespace logging --name elasticsearch`

And the YAML config file is the following:

```
image:
  repository: bitnami/elasticsearch
  tag: 6
  registry: MY_REGISTRY.azurecr.io
```

**Steps to reproduce the issue:**

1. Deploy AKS cluster
2. Install Helm & Tiller on the cluster
3. Execute as stated in the description (before) using config file

**Describe the results you received:**

Pods crash and the deployment is never working for me (see image below)

![screen shot 2018-12-07 at 10 15 26 am](https://user-images.githubusercontent.com/6045239/49659103-17751980-fa09-11e8-87c8-200bb4f72b7d.png)

**Describe the results you expected:**

Elasticsearch deployment working in the cluster

**Additional information you deem important (e.g. issue happens only occasionally):**

I believe **[this issue](https://github.com/bitnami/bitnami-docker-elasticsearch/issues/43)** contains the fix I need, however this isn't possible (or recommended) to manually execute inside each AKS node. Not sure how I can work around this problem.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tompizmor** [comment]
The kernel error is expected if the node where the elasticsearch container is running does not have the proper parameters.
If you don't want to do that manually, the chart can do it automatically if you deploy with the `--set sysctlImage.enabled=true`. With that option the chart will deploy first an initContainer to change the kernel settings for you.

**Comment by fdoxyz** [comment]
Thanks a lot for pointing it out! It was right under my nose on the README all along. Leaving the link for reference purposes

[https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#troubleshooting](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch#troubleshooting)
