### ISSUE TITLE
External-DNS extraArgs array index bug

### ISSUE THREAD

**Issue by skreienk** [bitnami/charts#9663]
### Name and Version

bitnami/ external-dns:6.2.3

### What steps will reproduce the bug?

Using extraArgs in the values field in the helm chart

### Are you using any custom parameters or values?

extraArgs:
  - --txt-owner-id=k8s
  - --provider=rfc2136

### What is the expected behavior?

Should result in app deployment like:
  containers:
      - args:
        - --txt-owner-id=k8s
        - --provider=rfc2136

### What do you see instead?

    containers:
      - args:
        - --0=--txt-owner-id=k8s
        - --1=--provider=rfc2136

### Additional information

It appears to be printing the array index along with the value.  That causes the pod to error out with CreateContainerConfigError.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Could you try setting it as a map instead of an array?

```
txt-owner-id: k8s
provider: rfc2138
```

**Comment by usrbinsam** [comment]
@javsalgar looks like `extraArgs` needs to be an array or a specific option `values.yaml` entry for the `--zone-id-filter` arg. 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/342758/172532947-668ffd6c-ccab-4e7f-94d2-041aa5f0c27d.png">

**Comment by axlroden** [comment]
This happens to any extraArgs btw.. so so it's completely useless.

**Comment by javsalgar** [comment]
Did you try setting it as a map?

**Comment by axlroden** [comment]
I could, but again.. defeats the purpose of having this config available?

**Comment by javsalgar** [comment]
In order to not perform a breaking change, we could change the processing of the extraArgs variable so it is treated like an array but also allowing the previous map setting. Would that work?
