### ISSUE TITLE
[bitnami/kafka] Access fails on Liveness/Readiness

### ISSUE THREAD

**Issue by ielyanov** [bitnami/charts#9666]
### Name and Version

kafka-16.2.0

### What steps will reproduce the bug?

`helm repo add bitnami https://charts.bitnami.com/bitnami`

```

helm install zookeeper bitnami/zookeeper --namespace kafka-cluster1 \
  --set replicaCount=3 \
  --set auth.enabled=false \
  --set persistence.enabled=false \
  --set zookeeper.persistence.enabled=false \
  --set allowAnonymousLogin=true

```

```
helm install kafka bitnami/kafka --namespace kafka-cluster1  \
 --set replicaCount=3  \
 --set persistence.enabled=false  \
 --set zookeeper.persistence.enabled=false  \
 --set externalZookeeper.servers=zookeeper.kafka-cluster1.svc.cluster.local
```

The installation result on:
`# kubectl describe pod/kafka-0 -n kafka-cluster1`

```
 Liveness probe failed: dial tcp 10.233.66.11:9092: connect: connection refused
 Back-off restarting failed container

Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Normal   Pulled     57m (x27 over 138m)    kubelet  Container image "docker.io/bitnami/kafka:3.1.0-debian-10-r60" already present on machine
  Warning  Unhealthy  13m (x39 over 137m)    kubelet  Liveness probe failed: dial tcp 10.233.66.11:9092: connect: connection refused
  Warning  BackOff    3m6s (x573 over 137m)  kubelet  Back-off restarting failed container
```

### What do you see instead?

Version of Helm and Kubernetes:

- Output of `helm version`:

`version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}`

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

![screenshot](https://user-images.githubusercontent.com/16875523/161385093-5e61ebca-1ef2-4e4c-8b4a-290f17ed8f97.png)

**Comment by javsalgar** [comment]
Hi,

Does the issue happen when enabling persistence? Just to understand the cause of the issue.

**Comment by ielyanov** [comment]
Sorry.  I can't check with PV right now.

It works on Centos7, but it doesn't work on Oracle Linux Server 8.5

**Comment by ielyanov** [comment]
Yes.

Probably is a some problem with my kubernetes cluster.

I reinstalled kubernetes on Oracle Linux Server 8.5

I have a kubernetes cluster with 2 worker nodes.
---

The pods kafka-1, kafka-2, kafka-4, kafka-6  are placed on the kub-node-1 .

The pods kafka-0, kafka-3, kafka-5, kafka-zookeper-0  are placed on the kub-node-2 .


![new](https://user-images.githubusercontent.com/16875523/162933026-969be2e3-9c77-4b9a-aac7-37f69cb0a6f7.png)

**Comment by javsalgar** [comment]
Hi,

What happens if you disable the readiness/liveness probes? Does the container get executed correctly? Just to ensure the issue is in the probes and not something else.

**Comment by ielyanov** [comment]
I`m very sorry.
I reinstalled kubernetes cluster.

Kafka works fine!

Thanks a lot!

![iiii](https://user-images.githubusercontent.com/16875523/163405589-929414d9-1271-448b-8739-a1cc40b796e6.png)
