### ISSUE TITLE
ExternalDNS prefix instructions clarification

### ISSUE THREAD

**Issue by skreienk** [bitnami/charts#9668]
### Name and Version

 external-dns:6.2.3

### What steps will reproduce the bug?

Using the RFC2136 provider, both txtPrefix and txtSuffix are marked as optional and both are left to default to null.

### What is the expected behavior?

If using RFC2136 the DNS registration should work after filling in all required parameters. 

### What do you see instead?

DNS updates are rejected with error: rfC2136 update failed: bad return code: YXRRSET

### Additional information

txtPrefix should have a default value.
A clarification should also be made in the documentation that states one of txtPrefix or txtSuffix is required when using the RFC2136 provider.

**Comment by carrodher** [comment]
Thanks for the suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
