### ISSUE TITLE
[bitnami/kubernetes-event-exporter]Enable imagePullSecrets in template files

### ISSUE THREAD

**Issue by badatya14** [bitnami/charts#9674]
### Name and Version

bitnami/kubernetes-event-exporter 1.4.5

### What steps will reproduce the bug?

1. Pulling image `kubernetes-event-exporter:0.11.0-debian-10-r129 `from a private repo needs imagePullSecrets. (Note: We are hosting images in our own public cloud registry)
2. imagePullSecrets [variable](https://github.com/bitnami/charts/blob/master/bitnami/kubernetes-event-exporter/values.yaml#L15) is being passed to the [serviceaccount](https://github.com/bitnami/charts/blob/master/bitnami/kubernetes-event-exporter/templates/serviceaccount.yaml) and [deployment](https://github.com/bitnami/charts/blob/master/bitnami/kubernetes-event-exporter/templates/deployment.yaml) template files
3. However, the template has not been enabled to render/handle the passed variable
4. For example - This should be something like [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/serviceaccount.yaml#L16-L18)

### Are you using any custom parameters or values?

```
global:
  imageRegistry: "path/to/private/image/registry"
  imagePullSecrets:
    - name: myregistrykey
image:
  repository: kubernetes-event-exporter
```

### What is the expected behavior?

The template [files](https://github.com/bitnami/charts/tree/master/bitnami/kubernetes-event-exporter/templates) should be able to process the pasing variable imagePullSecrets

### What do you see instead?

`Failed to pull image "path/to/private/image/registry/kubernetes-event-exporter:0.10.0-debian-10-r0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for path/to/private/image/registry/kubernetes-event-exporter, repository does not exist or may require 'docker login': denied: Permission denied for "0.10.0-debian-10-r0" from request "/v2/path/to/private/image/registry/kubernetes-event-exporter/manifests/0.10.0-debian-10-r0".`

**Comment by miguelaeh** [comment]
Hi @badatya14 ,
Checking the `deployment.yaml` it should be rendering the image pull secrets. Check [this](https://github.com/bitnami/charts/blob/8f470730b42433cebc9a158def75d84ac8008e1d/bitnami/kubernetes-event-exporter/templates/deployment.yaml#L38).
There are two options:
1. Putting them into the `image` object. Check [this](https://github.com/bitnami/charts/blob/8f470730b42433cebc9a158def75d84ac8008e1d/bitnami/kubernetes-event-exporter/values.yaml#L79).
2. Putting them into the `global` object, like [this](https://github.com/bitnami/charts/blob/8f470730b42433cebc9a158def75d84ac8008e1d/bitnami/kubernetes-event-exporter/values.yaml#L15).

**Comment by badatya14** [comment]
@miguelaeh Many thanks taking a look at it. It worked. Thank you 👍
