### ISSUE TITLE
Integration with DNS

### ISSUE THREAD

**Issue by shubhra27** [bitnami/charts#9675]
### Name and Version

bitnami/postgresql-ha/8.6.0

### What is the problem this feature will solve?

Will be able to access postgres through DNS.

Also kindly suggest how to integrate postgres with tolls installed on VM.

### What is the feature you are proposing to solve the problem?

Will be able to access postgres through DNS.

**Comment by shubhra27** [comment]
Hi @rafariossaa Actually I want to access postgres through DNS. Also I want to know about how can I add postgres as database for tools installed on VMs. Not sure if I raised in correct platform, bbut this is my requirement.

Thanks
Shubhra

**Comment by rafariossaa** [comment]
Hi,
  As you may know, containers names are not resolvable outside the container enviroment. So, if for example you have a container running in you laptop, to access it from an application running in your laptop, you have to expose the ports and access it using `localhost`. You could give `localhost` and alias in `/etc/hosts` and use that alias in your application.

**Comment by shubhra27** [comment]
Hi,

I deployed this postgres HA helm chart with loadbalancer service enabled. Now I want to attach DNS to the loadbalancer.
How can I do that?

**Comment by rafariossaa** [comment]
Not very sure what you mean by "attach DNS to the loadbalancer". You should have a name for the loadbalancer service, that name will be reachable inside the k8s cluster.

**Comment by shubhra27** [comment]
I got loadbalancer service IP, not name through which I am connecting to outside. Now I want to connect to postgres through DNS from outside cluster. Is it possible, if yes then how? Also, regarding the loadbalancer name, how can this be configures? I am not getting any documentation regarding this so reaching out to this portal.

**Comment by javsalgar** [comment]
Hi,

That would depend on the cloud you are using for your Kubernetes cluster. Depending on which, they may also create accessible DNS entries for the LoadBalancer service.

**Comment by shubhra27** [comment]
Hi, we are using VMware Tanzu. I have got the DNS created, but now how to attach that to loadbalancer IP, that I am struggling with.

**Comment by javsalgar** [comment]
Hi,

This is more related to the TKG cluster configuration. In this sense, my advice would be to check with the TKG support to explain how to assign a DNS entry to a LoadBalancer service.

https://community.pivotal.io/s/?language=en_US

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
