### ISSUE TITLE
Broken RabbitMQ deploy with enabled RABBITMQ_DEFINITIONS_FILE

### ISSUE THREAD

**Issue by iFshadow** [bitnami/charts#9676]
### Name and Version

bitnami/rabbitmq

### What steps will reproduce the bug?

1. Run in kubernetes cluster
2. `values.yml` file included custom `load_definition.json` definition
3. Run as
```bash
helm upgrade --namespace ${KUBE_NAMESPACE} --install \
        --values /tmp/values.yml rabbitmq bitnami/rabbitmq \
        --set auth.erlangCookie=${RABBITMQ_ERLANG_COOKIE} \
        --set auth.password=${RABBITMQ_AUTH_PASSWORD}
```
4. Error
```
rabbitmq 09:58:12.64 INFO  ==> ** Starting RabbitMQ setup **                                                                                                                                                                               
rabbitmq 09:58:12.67 INFO  ==> Validating settings in RABBITMQ_* env vars..                                                                                                                                                                
rabbitmq 09:58:12.68 ERROR ==> The RABBITMQ_LOAD_DEFINITIONS and RABBITMQ_SECURE_PASSWORD environment variables cannot be enabled at once.
```

### What is the expected behavior?

Success run kubernetes pod

### What do you see instead?

Crashed pod with error
```
The RABBITMQ_LOAD_DEFINITIONS and RABBITMQ_SECURE_PASSWORD environment variables cannot be enabled at once.
```

### Additional information

Three days ago added [commit](https://github.com/bitnami/charts/commit/ac845cb5131c053b9413780428a17a1f85417df0#diff-43f6a9461c81b4dbbf596161ffc298893e558130cf09049a9dd68925e9bee488R184l) with changes for `Values.loadDefinition.enabled` which change behavior start of RabbitMQ with connected external definition file. Now if definition file is connected then `RABBITMQ_SECURE_PASSWORD` variable not will change to `no`.

**Comment by rutkai** [comment]
This one affects us too. Here is how it looked:

            {{- if .Values.loadDefinition.enabled }}
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: "yes"
            - name: RABBITMQ_SECURE_PASSWORD
              value: "no"
            {{- else }}
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: "no"
            - name: RABBITMQ_SECURE_PASSWORD
              value: "yes"
            - name: RABBITMQ_USERNAME
              value: {{ .Values.auth.username | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rabbitmq.secretPasswordName" . }}
                  key: rabbitmq-password
            {{- end }}

Properly toggling the two flags, not it's invalid with `load_definitions`:

            - name: RABBITMQ_LOAD_DEFINITIONS
              value: {{ ternary "yes" "no" .Values.loadDefinition.enabled | quote }}
            - name: RABBITMQ_DEFINITIONS_FILE
              value: {{ .Values.loadDefinition.file | quote }}
            - name: RABBITMQ_SECURE_PASSWORD
              value: "yes"
^^^ this one is outisde of all `if`s.

**Comment by javsalgar** [comment]
Hi,

This bug was fixed here https://github.com/bitnami/bitnami-docker-rabbitmq/commit/4c90fe2b508075c3e70c996023f5164a11469453

It seems that the chart was not updated with the latest image. I will force a release to fix it.

**Comment by Tajjar** [comment]
Hi,
Any update on this? we are also facing this problem.
Thanks!

**Comment by javsalgar** [comment]
Could you ensure that you are using the latest version of the chart? The issue was fixed in https://github.com/bitnami/bitnami-docker-rabbitmq/commit/4c90fe2b508075c3e70c996023f5164a11469453

**Comment by Tajjar** [comment]
@javsalgar using version 8.32.1

**Comment by javsalgar** [comment]
Awesome, thanks!
