### ISSUE TITLE
Install ELASTICSEARCH_PLUGINS with Helm values.yaml

### ISSUE THREAD

**Issue by solstarz** [bitnami/charts#968]
Hi,

Im a Helm newbie here.

How can I add ELASTICSEARCH_PLUGINS in the values.yaml for installation with helm?
And then update the existing elasticsearch installation.

Thanks in advance.

Regards, 

JP

**Comment by juan131** [comment]
Hi @solstarz 

As you can check it's supposed to take very plugin indicated in the parameter "plugins": 
https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/coordinating-deploy.yaml#L80

However, we don't have it documented on the chart properly. Thanks for reporting it, check the PR below when I document it:

https://github.com/bitnami/charts/pull/975

**Comment by solstarz** [comment]
Hi @juan131, 

Thanks for your input.
