### ISSUE TITLE
Any plans for Argo-workflows v.3.3.1 with bitnami chart?

### ISSUE THREAD

**Issue by mikulass** [bitnami/charts#9680]
### Name and Version

bitnami/argo-workflows 0.2.4  

### What is the problem this feature will solve?

Hello, sorry to disturb with this, if this off topic or if I'm missing some info...For our workflow project we would like to use some new feature from Argo workflows v 3.3.1.  For deployment we use bitnami chart, which deploys currently  v 3.2.7. Is there any near future plan/schedule to release updated helm chart which will deploy new Argo workflow 3.3.1? Or is there any guide or recommendation, how to upgrade to the newest Argo workflow release available? Thanks, Best regards, M.

### What is the feature you are proposing to solve the problem?

Chart update, to be able deploy, Argo workflows 3.3.1

**Comment by carrodher** [comment]
Since version 1.1.2, the bitnami/argo-workflows Helm chart uses version 3.3.1 for the container images bundled in the Helm chart, see https://github.com/bitnami/charts/commit/ca9a3ca4597e3d4d1f199bf0aef05b92bd2c78fd.

Probably you need to update your Helm client repo:
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo bitnami/argo-workflows -l
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/argo-workflows	1.1.3        	3.3.1      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	1.1.2        	3.3.1      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	1.1.1        	3.3.0      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	1.1.0        	3.2.9      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	1.0.2        	3.2.9      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	1.0.1        	3.2.9      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	1.0.0        	3.2.8      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	0.2.6        	3.2.8      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	0.2.5        	3.2.8      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	0.2.4        	3.2.7      	Argo Workflows is meant to orchestrate Kubernet...
bitnami/argo-workflows	0.2.3        	3.2.7      	Argo Workflows is meant to orchestrate Kubernet...
...
```

**Comment by mikulass** [comment]
Many thanks
