### ISSUE TITLE
Authentication session notes disappear during registration flow

### ISSUE THREAD

**Issue by anand-kulk** [bitnami/charts#9684]
### Name and Version

bitnami/keycloak 3.0.3

### What steps will reproduce the bug?

We're using keycloak chart and have customized bitnami/keycloak:16.1.0 image with custom authenticator and customized login/registration flows and Postgres enabled. The issue is, during pre-login, we're saving authNotes in authentication session but in next request the notes disappear. The issue intermittently happens on both the pods(we configured 2 pods). From the logs, it seems like browser is able to send the cookies correctly to server but server session can't find auth notes. We use default in-memory sessions.  Any advise on how to fix this?

### What is the expected behavior?

Already saved auth session notes should be retrieved between requests during login/registration flow.

### What do you see instead?

I suspect authentication sessions are dropped on Keycloak side. There is no exception/error in logs.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but we are not keycloak experts. In this case I would suggest you to ask in keycloak forums to get a better answer. My guess is that issue is related to your configuration an not with the default chart and images.
  Please, don't hesitate to come back and share your findings.

**Comment by anand-kulk** [comment]
> Hi, I am sorry, but we are not keycloak experts. In this case I would suggest you to ask in keycloak forums to get a better answer. My guess is that issue is related to your configuration an not with the default chart and images. Please, don't hesitate to come back and share your findings.

Thanks @rafariossaa, I asked on keycloak forum and will update here if I find anything there.

**Comment by rafariossaa** [comment]
Thanks !
