### ISSUE TITLE
RabbitMQ Sercure Password Logic Missing

### ISSUE THREAD

**Issue by deB4SH** [bitnami/charts#9686]
### Name and Version

bitnami/rabbitmq

### What steps will reproduce the bug?

1) deploy after upgrading the helmchart to 8.31.*

### Are you using any custom parameters or values?

Not required for this issue

### What is the expected behavior?

RabbitMQ container is starting with given load_definitions

### What do you see instead?

```

rabbitmq 11:48:40.32 
rabbitmq 11:48:40.32 Welcome to the Bitnami rabbitmq container
rabbitmq 11:48:40.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq 11:48:40.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq 11:48:40.33 
rabbitmq 11:48:40.33 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 11:48:40.36 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 11:48:40.37 ERROR ==> The RABBITMQ_LOAD_DEFINITIONS and RABBITMQ_SECURE_PASSWORD environment variables cannot be enabled at once.
```

### Additional information

The commit: https://github.com/bitnami/charts/commit/ac845cb5131c053b9413780428a17a1f85417df0#diff-43f6a9461c81b4dbbf596161ffc298893e558130cf09049a9dd68925e9bee488 removed the logic of switching between yes/no flags for load_definitions and rabbitmq_secure_password. This results into a startup issue. (see error log under **What do you see instead?**).
Could you please add the logic back in or create a configurable variable for RABBITMQ_SECURE_PASSWORD .

**Comment by deB4SH** [comment]
Issue is already tracked under: https://github.com/bitnami/charts/issues/9676
I'm closing this issue in favor of 9676

**Comment by rafariossaa** [comment]
Thanks
