### ISSUE TITLE
[bitnami/redis-cluster] Opening the temp file for AOF rewrite in rewriteAppendOnlyFile(): Permission denied

### ISSUE THREAD

**Issue by rickwang7712** [bitnami/charts#9693]
### Name and Version

chart version redis-cluster-0.1.2 / app version 6.0.5

### What steps will reproduce the bug?

Apply helm chart with aof enabled and wait a couple days, and then some pods will occur logs like this:
```
1:M 12 Feb 2022 16:49:58.886 * Starting automatic rewriting of AOF on 157422% growth
1:M 12 Feb 2022 16:49:58.887 * Background append only file rewriting started by pid 6625
6625:C 12 Feb 2022 16:49:58.887 # Opening the temp file for AOF rewrite in rewriteAppendOnlyFile(): Permission denied
1:M 12 Feb 2022 16:49:58.987 # Background AOF rewrite terminated with error
1:M 12 Feb 2022 16:49:59.088 * Starting automatic rewriting of AOF on 157422% growth
1:M 12 Feb 2022 16:49:59.089 * Background append only file rewriting started by pid 6626
6626:C 12 Feb 2022 16:49:59.089 # Opening the temp file for AOF rewrite in rewriteAppendOnlyFile(): Permission denied
```

There is another guy get the same issue like this on Stackoverflow: [Deploy bitnami redis-cluster using helm](https://stackoverflow.com/questions/71101957/deploy-bitnami-redis-cluster-using-helm)

### Are you using any custom parameters or values?

          global:
            storageClass: local-ssd
          livenessProbe:
            enabled: true
            timeoutSeconds: 5
          persistence:
            size: 16Gi
          volumePermissions:
            enabled: true

### What is the expected behavior?

I don't expect the permission denied problem happen after a few days of run.

### What do you see instead?

The permission denied problem should happen immediately or never.

### Additional information

I don't know how to debug the permission deny issue, could anyone please give me some advices?

**Comment by rickwang7712** [comment]
I found this issue is related with the config get dir result is wrong:

normal: redis-cli config get dir
```
1) "dir"
2) "/bitnami/redis/data"
```

abnormal: redis-cli config get dir
```
1) "dir"
2) "/etc"
```

After reset the dir:  `redis-cli config set dir /bitnami/redis/data`
everything works again.

**Comment by javsalgar** [comment]
Hi,

This is very strange, I'm not sure how the application may have changed the configuration directory. Does the issue happen consistently after some time?

**Comment by rickwang7712** [comment]
@javsalgar I'm still observing, but it looks like it happens after some random time period.
I'm doubting if there is a security issue, but my redis-cluster doesn't expose on the internet.
Currently I'm grepping 'config' from MONITOR's output, and see if there was an unexpected config set command.

**Comment by rickwang7712** [comment]
After investigation, I finally found that our redis-cluster has NodePort exposed... , and because I didn't add password protection, so I think it is a security problem...

**Comment by rickwang7712** [comment]
I found that the chart I used set's service's type to NodePort as default value.
