### ISSUE TITLE
Fix adding extra volumes and extra volumeMounts

### ISSUE THREAD

**Issue by ghost** [bitnami/charts#9695]
### Name and Version

bitnami/mongodb:11.0.1

### What steps will reproduce the bug?

Change how extraVolumes and extraVolumeMounts are injected in the standalone, arbiter, replicaset and hidden statefulsets.

### Are you using any custom parameters or values?
```
extraVolumeMounts: |
    {{- if $.Values.extraFrmworkVolumeMounts }}
    {{ tpl ($.Values.extraFrmworkVolumeMounts |toYaml) .  }}
    {{- end }}
    {{- if $.Values.projectExtraVolumeMounts }}
    {{ tpl ( $.Values.projectExtraVolumeMounts|toYaml) .  }}
    {{- end }}

extraVolumes: |
    {{- if $.Values.extraFrmworkVolumes }}
    {{ tpl ($.Values.extraFrmworkVolumes |toYaml) . }}
    {{- end }}
    {{- if $.Values.projectExtraVolumes }}
    {{ tpl ($.Values.projectExtraVolumes|toYaml) . }}
    {{- end }}
```
### What is the expected behavior?

extraVolumes and extraVolumeMounts are correctly added to the statefulset generated manifest.

### What do you see instead?
```
volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath: 
            - name: custom-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            |
              {{- if $.Values.extraFrmworkVolumeMounts }}
              {{ tpl ($.Values.extraFrmworkVolumeMounts |toYaml) .  }}
              {{- end }}
              {{- if $.Values.projectExtraVolumeMounts }}
              {{ tpl ( $.Values.projectExtraVolumeMounts|toYaml) .  }}
              {{- end }}

volumes:
        - name: custom-init-scripts
          configMap:
            name: gdp-imdg-validation-mongodb-init-scripts
        |
          {{- if $.Values.extraFrmworkVolumes }}
          {{ tpl ($.Values.extraFrmworkVolumes |toYaml) . }}
          {{- end }}
          {{- if $.Values.projectExtraVolumes }}
          {{ tpl ($.Values.projectExtraVolumes|toYaml) . }}
          {{- end }}
        - name: datadir
          persistentVolumeClaim:
            claimName: gdp-imdg-validation-mongodb
```
### Additional information

The same problem appears on later versions.

**Comment by rafariossaa** [comment]
Hi,
  Could you provide more background of the issue you are finding with the volumes ?

**Comment by migruiz4** [comment]
Hi @ajammali,

Thank you for reporting this issue. This will be addressed in #9648.

Currently, the `extraVolumes` and `extraVolumeMounts` values are not being interpreted as a template, and rendered instead with `toYaml`.

```
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
```

In that PR, we will replace that with
```
          {{- if .Values.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
```

The helper `common.tplvalues.render` acts as a combination of both `tpl` and `toYaml`.

**Comment by ajammali** [comment]
Hello,
@migruiz4 thanks for your reply.
@rafariossaa I think it's more clear now with @migruiz4 answer.

**Comment by rafariossaa** [comment]
Hi,
  Yes it is.
  Let's wait until #9648 is merged.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
