### ISSUE TITLE
bitnami/fluentd readiness and liveness probes connection refused

### ISSUE THREAD

**Issue by Gowlar** [bitnami/charts#9709]
### Name and Version

bitnami/fludent 5.0.15

### What steps will reproduce the bug?

Kubernetes Version: 1.21.2
FluentD: 5.0.15
Hello,

I am running FluentD 5.0.15, and the daemonset forwarders all fail on readiness and liveiness probes.
Furthermore, If i exec into the running pod try and curl 127.0.0.1/fluentd.healthcheck I get connection refused.

After a short period all the pods will get crash loop backoff and get stopped. Therefore being unuseable. 

I have turned off both of the probes in order to use the service.

This occurs without any values being added, as a vanilla install.

### What is the expected behavior?

Readiness and Liveness probes succeed when deployed

### What do you see instead?

Daemonsets are killed by kubernetes as both readiness and liveness probes are getting connection refused

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay.
  Could you indicate the command you are using to run the chart ? Also, How long does it take to start crashing ?. Could you provide the logs ?
