### ISSUE TITLE
Redis Cluster is failing with qurum reached error.

### ISSUE THREAD

**Issue by Shujja1746** [bitnami/charts#9712]
### Name and Version

bitnami/redis-cluster 

### What steps will reproduce the bug?

Deploy the cluster with the latest values.yaml (11 masters and 11 slave)

Load the redis with 30gb data in each redis nodes

After some time redis is failing with qurum reached error

### Are you using any custom parameters or values?

Using value.yaml file with chart version redis-cluster-7.4.3 and app version 6.2.6

### What do you see instead?

![image](https://user-images.githubusercontent.com/100185414/162011119-88b535f8-79f5-43cc-ad23-01306d9ea74d.png)

**Comment by javsalgar** [comment]
Hi,

Do you have a link to a dataset that triggers the issue? We would like to reproduce the issue in our side.
