### ISSUE TITLE
Update or add redis nodes failing the entire redis cluster

### ISSUE THREAD

**Issue by Shujja1746** [bitnami/charts#9713]
### Name and Version

bitnami/redis-cluster latest version 

### What steps will reproduce the bug?

Deploy the redis-cluster with 9 nodes, load the redis cluter with 50 gb ram in each node.

Try to add nodes or upgrade the cluster to premium disk.

The cluster is going into pending state.

### Are you using any custom parameters or values?

Using values.yaml to do helm upgrade

helm upgrade --timeout 600s redis-cluster-name -f "edit vauels.yaml path" bitnami/redis-cluster --set password=$REDIS_PASSWORD

### What do you see instead?

once I add nodes or change the storageclass and do upgrade its going into pending state and never coming up.

### Additional information

Having alot of issues while upgrading or if want to make some changes in production cluster.

**Comment by rafariossaa** [comment]
Hi,
  When upgrading, which versions are you using ?  Regarding the scaling, have you take a look the the [notes here](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#user-content-cluster-topology) ?

**Comment by Shujja1746** [comment]
Hi 

Sure will create one small cluster and will test that from that notes info.

thanks
