### ISSUE TITLE
extraEnvVarsCM not working in bitnami/airflow chart if specified on the global level

### ISSUE THREAD

**Issue by dunefro** [bitnami/charts#9716]
### Name and Version

bitnami/airflow 12.1.5

### What steps will reproduce the bug?

1. Create a `configmap` with any name (let's say `test-cm`).
2. Pass the `configmap` in `.Values.extraEnvVarsCM`.
3. Run the `helm template` command or `helm install`.
4. Configmap is not attached to the pods
5. Passing the configmap in `.Values.scheduler.extraEnvVarsCM` or `.Values.web.extraEnvVarsCM` or `.Values.worker.extraEnvVarsCM` works fine.

### What is the expected behavior?

This should appear in the pod spec of scheduler, worker and web pods 
```
envFrom:
  - configMapRef:
       name: test-cm
```

### What do you see instead?

No section of `envFrom` in the pod spec

### Additional information

Issue can be easily resolved by removing this 
```
 {{- if or .Values.web.extraEnvVarsCM .Values.web.extraEnvVarsSecret }}
```
from the `deployment.yaml` or `statefulset.yaml`. If there is a necessary reason to put these values over there then you might have to add
```
 {{- if or .Values.web.extraEnvVarsCM .Values.extraEnvVarsCM .Values.web.extraEnvVarsSecret }}
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Would you like to submit a PR fixing it?

**Comment by dunefro** [comment]
@javsalgar Yes would surely do that.

**Comment by javsalgar** [comment]
Awesome! Please let us know when you submit it and we'll take a look :D

**Comment by dunefro** [comment]
Please check the [PR](https://github.com/bitnami/charts/pull/9760)
