### ISSUE TITLE
[bitnami/etcd] - Snapshotter job crashing on startup

### ISSUE THREAD

**Issue by cdemi** [bitnami/charts#9720]
### Name and Version

bitnami/etcd v7.0.2

### What steps will reproduce the bug?

Configure bitnami/etcd 7.0.2 with:

```
disasterRecovery:
  enabled: true
```

Wait for the snapshotter job to run.

On starting it will crash:

```
/opt/bitnami/scripts/libetcd.sh: line 267: MY_STS_NAME: unbound variable
```

### Are you using any custom parameters or values?

```
disasterRecovery:
  enabled: true
```

### What do you see instead?

```
/opt/bitnami/scripts/libetcd.sh: line 267: MY_STS_NAME: unbound variable
```

### Additional information

I think this is related to the changes done in #9708 for issue #5771

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting! Indeed, the latest changes are related. In the snapshotter env vars you need to add the following:

```
            - name: MY_STS_NAME
              value: {{ include "common.names.fullname" . | quote }}
```

Would you like to submit a PR fixing the issue?

**Comment by cdemi** [comment]
I have opened PR #9735

This is my first time opening a helm chart PR so I am not sure if it's up to standard. I welcome feedback

**Comment by jaceksan** [comment]
I am affected as well.
I tried to workaround it by setting disasterRecovery.enabled to false, but it does not work, obviously, because it is false by default.
Is there any workaround solution?

**Comment by jaceksan** [comment]
My colleague tried it too (in k3d too) and after some time etcd nodes completely crash reporting missing member_id.

**Comment by jaceksan** [comment]
OK, I used version 7.0.1. I updated to 7.0.2 and now it works.

**Comment by javsalgar** [comment]
@cdemi thank you so much for the PR! The team will take a look
