### ISSUE TITLE
minAvailable not

### ISSUE THREAD

**Issue by WolfspiritM** [bitnami/charts#9722]
### Name and Version

bitnami/redis-cluster 7.4.5

### What steps will reproduce the bug?

1. Use minAvailable of the chart
2. It's not used

### Are you using any custom parameters or values?

minAvailable: 1
maxUnavailable: 1

### What is the expected behavior?

I'd expect it to create a pdb with minAvailable set to that number

### What do you see instead?

Nothing happens

### Additional information

I think this is a bug in the documentation. The minAvailable and maxUnavailable don't seem to be used anywhere at all. I think these values should be nested under podDisruptionBudget instead of the root of the values?!

https://github.com/bitnami/charts/search?q=minAvailable+path%3Abitnami%2Fredis-cluster%2F&type=code

Also especially for the redis-cluster I'm unsure how to specifiy that I want at least 2 replicas and 2 masters running. (Same also applies for the podaffinity to have one master and one replica per node but that's for another issue I guess)

**Comment by WolfspiritM** [comment]
Hi. I can give this a try. I'm however not sure what the best option would be. I can see two ways of doing it:

1. Remove minAvailable and maxUnavailable completly from the values and Readme as it's using the podDisruptionBudget as the spec via toYaml.
2. Change how the pdb is handled by having a "create" or "enabled" flag (that seems to be not consistent between charts). Something like
```
podDisruptionBudget:
  create: false
  minAvailable: 1
  maxUnavailable: ""
```
that would at least be more consistent to other charts as far as I can see however it requires a change in the chart template. And it might be a good idea to also switch to "pdb" instead of "podDisruptionBudget" as that's what the other charts use.

What would be the prefered way?

**Comment by javsalgar** [comment]
Hi,

The standard would be `pdb` and `pdb.create`. We are working on making all the charts consistent and this is the preferred approach.
