### ISSUE TITLE
failed: Connection timed out Is the server running on that host and accepting TCP/IP connections?

### ISSUE THREAD

**Issue by ask664** [bitnami/charts#9726]
### Name and Version
bitnami/postgresql:latest 
### What steps will reproduce the bug?

wget https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz.  # install helm
tar -xvf helm-v3.8.0-linux-amd64.tar.gz
linux-amd64/helm install **feast-postgres-offline-store** bitnami/postgresql  # install postgres with feast-postgres-offline-store release name

Successfully postgres installed. 

# get postgres service log: 
kubectl describe svc **feast-postgres-offline-store-postgresql**
Name:                     **feast-postgres-offline-store-postgresql**
Namespace:                tenant1
Labels:                   app.kubernetes.io/component=primary
                          app.kubernetes.io/instance=feast-postgres-offline-store
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=postgresql
                          helm.sh/chart=postgresql-11.1.17
Annotations:    
                          meta.helm.sh/release-name: feast-postgres-offline-store
                          meta.helm.sh/release-namespace: tenant1
Selector:                 app.kubernetes.io/component=primary,app.kubernetes.io/instance=feast-postgres-offline-store,app.kubernetes.io/name=postgresql
Type:                     NodePort
IP Families:              <none>
IP:                       xxxxxxxxxx
IPs:                      xxxxxxxxxx
Port:                     tcp-postgresql  5432/TCP
TargetPort:               tcp-postgresql/TCP
NodePort:                 tcp-postgresql  30468/TCP
Endpoints:                xxxxxxxxxx:5432
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason  Age   From         Message
  ----    ------  ----  ----         -------
  Normal  xxxxxx   10m   xxxxxxx-agent  Created XXXXXX K8S service
**Postgres configuration** : 
 {'type': 'feast_postgres.PostgreSQLOfflineStore', 'host': 'feast-postgres-offline-store-postgresql', 'port': 5432, 'database': 'postgres', 'db_schema': 'my_schema', 'user': 'postgres', 'password': 'JXAZ8VJIMT'}
Connecting to the database url: 
 postgresql+psycopg2://postgres:JXAZ8VJIMT@feast-postgres-offline-store-postgresql:5432/postgres

Throw Error while connecting postgres database using above url through sqlalchemy => 
OperationalError: connection to server at "feast-postgres-offline-store-postgresql" (10.99.238.53), port 5432 failed: Connection timed out
Is the server running on that host and accepting TCP/IP connections?

When trying to connect again and again then throw error authentication failed even correct password providing.

### Are you using any custom parameters or values?

--set auth.enablePostgresUser=false
--set auth.username=postgres
--set auth.password=postgres
--set auth.database=postgres
--set primary.resources.requests.cpu=100m
--set primary.resources.limits.cpu=100m
--set primary.resources.requests.memory=256Mi
--set primary.resources.limits.memory=256Mi
--set volumePermissions.enabled=true
--set volumePermissions.image.registry=docker.io
--set volumePermissions.image.repository=bitnami/bitnami-shell
--set volumePermissions.image.tag=10-debian-10-r327
--set volumePermissions.resources.requests.cpu=100m
--set volumePermissions.resources.requests.memory=256Mi
--set volumePermissions.resources.limits.cpu=100m
--set volumePermissions.resources.limits.memory=256Mi
--set livenessProbe.enabled=false
--set readinessProbe.enabled=false

### What is the expected behavior?

# Postgres Installation part is correct even with custom password.
linux-amd64/
linux-amd64/helm
linux-amd64/LICENSE
linux-amd64/README.md
NAME: feast-postgres-offline-store
LAST DEPLOYED: Thu Apr  7 19:20:45 2022
NAMESPACE: n
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: postgresql
CHART VERSION: 11.1.17
APP VERSION: 14.2.0

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS names from within your cluster:

    feast-postgres-offline-store-postgresql.tenant1.svc.cluster.local - Read/Write connection

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace tenant1 feast-postgres-offline-store-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run feast-postgres-offline-store-postgresql-client --rm --tty -i --restart='Never' --namespace tenant1 --image docker.io/bitnami/postgresql:14.2.0-debian-10-r54 --env="PGPASSWORD=$POSTGRES_PASSWORD" \
      --command -- psql --host feast-postgres-offline-store-postgresql -U postgres -d postgres -p 5432

    > NOTE: If you access the container using bash, make sure that you execute "/opt/bitnami/scripts/entrypoint.sh /bin/bash" in order to avoid the error "psql: local user with ID 1001} does not exist"

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace tenant1 svc/feast-postgres-offline-store-postgresql 5432:5432 &
    PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432

### What do you see instead?

# create a table and populate it with raw data.
from io import StringIO
import pandas as pd
import yaml
import sqlalchemy

from feast_postgres import PostgreSQLOfflineStoreConfig

df = pd.read_parquet(f'{HOMEDIR}/examples/feast/offline-store/feature_repo/data/driver_stats.parquet')

with open(f'{HOMEDIR}/examples/feast/offline-store/feature_repo/feature_store.yaml', "r") as stream:
    try:
        config = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

offline_config = config["offline_store"]
print(f"Offline postgres store configuration: \n {offline_config}")
 {'type': 'feast_postgres.PostgreSQLOfflineStore', 'host': 'feast-postgres-offline-store-postgresql', 'port': 5432, 'database': 'postgres', 'db_schema': 'my_schema', 'user': 'postgres', 'password': 'JXAZ8VJIMT'}
Connecting to the database url: 
 postgresql+psycopg2://postgres:JXAZ8VJIMT@feast-postgres-offline-store-postgresql:5432/postgres

del offline_config["type"]

offline_config = PostgreSQLOfflineStoreConfig(**offline_config)

# get postgresql connection string through sqlalchemy using offline_config
def get_sqlalchemy_engine(config: PostgreSQLOfflineStoreConfig):
    url = f"postgresql+psycopg2://{config.user}:{config.password}@{config.host}:{config.port}/{config.database}"
    print(f"Connecting to the database url: \n {url}")
    return sqlalchemy.create_engine(url, client_encoding='utf8', connect_args={'options': '-c search_path={}'.format(config.db_schema)})

con = get_sqlalchemy_engine(offline_config)

# create new schema 
schema_name = "my_schema"
con.execute("DROP SCHEMA IF EXISTS " + schema_name + ' CASCADE')
con.execute("Create SCHEMA " + schema_name)

# drop a table is already exist in schema
table = "driver_stats"
con.execute("DROP TABLE IF EXISTS " + table)

# create a new table
create_table_sql = pd.io.sql.get_schema(df, table, con=con)
con.execute(create_table_sql)

# copy from parquet to postgres
buffer = StringIO()
# DataFrame to CSV with no index
df.to_csv(buffer, header=False, index=False, na_rep="\\N")
buffer.seek(0)

# get cursor object from db using raw connection
raw_con = con.raw_connection()
with raw_con.cursor() as cursor:
    cursor.copy_from(buffer, table, sep=",")
raw_con.commit()

this is offline config:
project: feature_repo
registry: data/registry.db
provider: local
offline_store:
    type: feast_postgres.PostgreSQLOfflineStore # MUST be this value
    host: feast-postgres-offline-store-postgresql
    port: 5432              # Optional, default it 5432
    database: postgres
    db_schema: my_schema
    user: postgres
    password: JXAZ8VJIMT

### Additional information
Showing error - 
OperationalError: connection to server at "feast-postgres-offline-store-postgresql" (xxxxxxxxx), port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
<ipython-input-170-82380e7cb16b> in <module>
     32 # create new schema
     33 schema_name = "my_schema"
---> 34 con.execute("DROP SCHEMA IF EXISTS " + schema_name + ' CASCADE')
     35 con.execute("Create SCHEMA " + schema_name)
     36 

<string> in execute(self, statement, *multiparams, **params)

/opt/miniconda/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py in warned(fn, *args, **kwargs)
    399         if not skip_warning:
    400             _warn_with_version(message, version, wtype, stacklevel=3)
--> 401         return fn(*args, **kwargs)
    402 
    403     doc = func.__doc__ is not None and func.__doc__ or ""

_No response_

**Comment by javsalgar** [comment]
Hi,

It seems there are some formatting issues in the issue. Could you fix them so it is properly readable?

**Comment by vyom-soft** [comment]
Hello,
I am seeing the same error. Any pointer.
➜  postgresql git:(main) ✗     kubectl run postgresdb-postgresql-client --rm --tty -i --restart='Never' --namespace test-dev --image docker.io/bitnami/postgresql:15.2.0-debian-11-r5 --env="PGPASSWORD=$POSTGRES_ADMIN_PASSWORD" \
      --command -- psql --host postgresdb-postgresql -U testme -d testdb -p 5432
If you don't see a command prompt, try pressing enter.

psql: error: connection to server at "postgresdb-postgresql" (XX.XXX.XX.117), port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
pod "postgresdb-postgresql-client" deleted
pod test-dev/postgresdb-postgresql-client terminated (Error)
