### ISSUE TITLE
PostgreSQL in `readReplicas` section are missing pgHbaConfiguration and existingClaim parameters

### ISSUE THREAD

**Issue by maleksan** [bitnami/charts#9727]
### Name and Version

bitnami/postgresql 11.1.18

### What steps will reproduce the bug?

PostgreSQL Helm chart version: 11.1.18
https://github.com/bitnami/charts/tree/master/bitnami/postgresql

In [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml) file for `readReplicas` section are missing the following parameters (which are available in `master` section):

- readReplicas.pgHbaConfiguration
- readReplicas.persistence.existingClaim

Is it possible to modify helm chart and add these missing parameters?

### What do you see instead?

Helm chart missing parameters

**Comment by javsalgar** [comment]
Hi,

I believe that the pghba configuration could be added to the chart. My concern would be in the existingClaim section, as it would be shared by all replicas in the statefulset, causing concurrency issues.

**Comment by maleksan** [comment]
> My concern would be in the existingClaim section, as it would be shared by all replicas in the statefulset, causing concurrency issues.

Yes, you are right, adding existingClaim for replica could be possible if there will be only one replica, if more, than as you said - will be concurrency issues...

**Comment by javsalgar** [comment]
Hi,

About the pghba configuration, would you like to add the feature in the chart?

**Comment by maleksan** [comment]
Yes, sure, would like to add
