### ISSUE TITLE
Permissions to vhost / is not granted to user if load_definition feature is used

### ISSUE THREAD

**Issue by amithins** [bitnami/charts#9730]
### Name and Version

bitnami/rabbitmq 8.31.2

### What steps will reproduce the bug?

1. Install the 8.31.2 chart of rabbitmq with load_definition feature enabled
```
helm install rabbitmq-test bitnami/rabbitmq -n rabbitmq-test -f custom-values.yaml  --create-namespace
```
2. Login to rabbitmq pod and list permissions of vhost /
 ```
rabbitmqctl list_permissions --vhost /
```

### Are you using any custom parameters or values?

```
auth:
  username: guest
  password: ""
extraSecretsPrependReleaseName: true
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "apply-to": "all",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic",
            }
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: '<release_name>-load-definition'
extraConfiguration: |
  management.load_definitions = /app/load_definition.json
```

### What is the expected behavior?

In rabbitmq container,
```
  $ rabbitmqctl list_permissions --vhost /
  Listing permissions for vhost "/" ...
  user	configure	write	read
  guest	.*	.*	.*

```

### What do you see instead?

In rabbitmq container,
```
  $ rabbitmqctl list_permissions --vhost /
  Listing permissions for vhost "/" ...
  
```

### Additional information

This is working as expected in chart version `8.11.4` and image version `3.8.14-debian-10-r32`.

**Comment by javsalgar** [comment]
Hi!

Could you show the logs to see if there's anything meaningful?

**Comment by amithins** [comment]
[rabbitmq.log](https://github.com/bitnami/charts/files/8463686/rabbitmq.log)

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue

This is my diff with values.yaml

```
diff --git a/bitnami/rabbitmq/values.yaml b/bitnami/rabbitmq/values.yaml
index 80e6fe001..63c795ebe 100644
--- a/bitnami/rabbitmq/values.yaml
+++ b/bitnami/rabbitmq/values.yaml
@@ -230,7 +230,7 @@ clustering:
 loadDefinition:
   ## @param loadDefinition.enabled Enable loading a RabbitMQ definitions file to configure RabbitMQ
   ##
-  enabled: false
+  enabled: true
   ## @param loadDefinition.file Name of the definitions file
   ##
   file: "/app/load_definition.json"
@@ -238,7 +238,7 @@ loadDefinition:
   ## Can be templated if needed, e.g:
   ## existingSecret: "{{ .Release.Name }}-load-definition"
   ##
-  existingSecret: ""
+  existingSecret: "load-definition"
 
 ## @param command Override default container command (useful when using custom images)
 ##
@@ -409,7 +409,29 @@ extraVolumes: []
 ##         ...
 ##       }
 ##
-extraSecrets: {}
+extraSecrets:
+  load-definition:
+    load_definition.json: |
+      {
+        "vhosts": [
+          {
+            "name": "/"
+          }
+        ],
+        "policies": [
+          {
+            "name": "ha-all",
+            "apply-to": "all",
+            "pattern": ".*",
+            "vhost": "/",
+            "definition": {
+              "ha-mode": "all",
+              "ha-sync-mode": "automatic",
+            }
+          }
+        ]
+      }
+
 ## @param extraSecretsPrependReleaseName Set this flag to true if extraSecrets should be created with <release-name> prepended.
 ##
 extraSecretsPrependReleaseName: false
```

When I entered the container I saw:

```
 1 ❯ kubectl exec -ti rmq-rabbitmq-0 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@rmq-rabbitmq-0:/$ rabbitmqctl list_permissions --vhost /
Listing permissions for vhost "/" ...
user	configure	write	read
user	.*	.*	.*
```

Also, looking at your logs, it seems that the policies and vhost were imported correctly, so it is very weird to me.

**Comment by amithins** [comment]
Thats weird, got this tested by a colleague as well, seeing the same behaviour. Not sure if it makes a difference but the k8s version used is `v1.19.15-eks-9c63c4`.

**Comment by chukka** [comment]
@javsalgar  we tried again with latest 3.19.15 image and chart 8.31.4 ,Still the same issue . This is blocking  issue for us to upgrade to latest chart .

Is there any other info we can provide to debug further ?

cc @amithins

**Comment by javsalgar** [comment]
I'd say to enable the `image.debug=true` value and to check the logs to see if the definition gets loaded.

**Comment by amithins** [comment]
[rabbitmq-debug.log](https://github.com/bitnami/charts/files/8504318/rabbitmq-debug.log)

**Comment by amithins** [comment]
[rabbitmq-debug-no-load-definition.log](https://github.com/bitnami/charts/files/8504360/rabbitmq-debug-no-load-definition.log)
This is the deb log when load-definition is not used.

**Comment by javsalgar** [comment]
Hi,

This is weird, we can see in the logs that it is being imported. Could you please share a values.yaml file that always triggers the issue? I would like to install with that exact values.yaml

**Comment by amithins** [comment]
```
extraSecretsPrependReleaseName: false
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "apply-to": "all",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic",
            }
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: 'load-definition'
image:
  debug: true
```

**Comment by javsalgar** [comment]
Hi,

Ok, I tried again and saw that, indeed, the permissions for `guest` are not applied, but the policies and vhosts are created as expected.

```
I have no name!@rmq2-rabbitmq-0:/$ rabbitmqctl list_policies
Listing policies for vhost "/" ...
vhost	name	pattern	apply-to	definition	priority
/	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
```

I think that these default definitions for guest are not set because of the fact that we are loading definitions:

```
2022-04-19 09:48:58.912919+00:00 [info] <0.228.0> Will not seed default virtual host and user: have definitions to load...
```

**Comment by amithins** [comment]
Was able to get this working with the following workaround in values.yaml,
```
auth:
  username: guest
extraSecretsPrependReleaseName: false
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "permissions": [
          {
            "user": "guest",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "apply-to": "all",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic",
            }
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: 'load-definition'
image:
  debug: true
```

**Comment by javsalgar** [comment]
Thanks for sharing!

**Comment by chukka** [comment]
@javsalgar  can this be reopened as this is still an issue ( we don't have permission to reopen )

cc @amithins

**Comment by javsalgar** [comment]
Hi,

Did you check this comment? I believe that the behaviour was expected https://github.com/bitnami/charts/issues/9730#issuecomment-1102423132

**Comment by Dunge** [comment]
Thanks @amithins for the solution.

Imho, HA policies should be by default. Who want to use a rabbitmq cluster without HA queues? In any case, I believe this chart would be much more user friendly if it had a templating variable and documentation for the policies.

Most people will Google it, end up on #6276, try the solution proposed there, and then end up with this second problem. The [chart doc](https://artifacthub.io/packages/helm/bitnami/rabbitmq) have a section (Configure the default user/vhost) but as mentioned it get ignored if you included load_definition, so most people will end up with the same problem. Yes it is documented:

> NOTE: Loading a definition will take precedence over any configuration done through Helm values.

But if specifying policies (which again, most people will want to) break any over configuration, it's not really the most straightforward chart to use.

**Comment by Dunge** [comment]
Just tried a fresh install from scratch deleting all my pvc beforehand with chart 10.1.11 and no. It create the user yes, but it don't give it permissions to access the vhost unless you also add the user in the `load-definition` section.

Not working:

```
replicaCount: 3

auth:
  username: jl
  password: jl
  erlangCookie: BAxTTl4hvij3VkivFaBtYtzZLNlO7ttN

clustering:
  partitionHandling: pause_minority
  
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "policies": [
          {
            "name": "ha-all",
            "pattern": ".*",
            "vhost": "/",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode":	"automatic",
              "max-length-bytes": 50000000,
            }
          }
        ]
      }

loadDefinition:
  enabled: true
  existingSecret: load-definition

extraConfiguration: |-
  default_vhost = /
  default_permissions.configure = .*
  default_permissions.read = .*
  default_permissions.write = .*
  load_definitions = /app/load_definition.json
```


But adding this section in the `load_definition.json` works:

```
        "permissions": [
          {
            "user": "jamlogic",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
```

**Comment by javsalgar** [comment]
Hi,

I've seen this change in recent versions of RabbitMQ, so it is not clear to me if this is intended in latest versions of RabbitMQ. Did you check with the upstream RabbitMQ devs?

**Comment by Dunge** [comment]
I'm confused. What change did you see exactly? Using a standalone native installation of rabbitmq, you have a default `guest` user that have access to the vhost automatically. This chart force you to set a user in the "auth" section of the values.yaml file, and it doesn't work out of the box. I'm sorry, but I don't plan to be a middle man between the two dev teams, I'm just an user trying to get this service working without too much hassle.

**Comment by javsalgar** [comment]
Hi,

From here: https://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2014-July/037112.html, another source here: https://github.com/docker-library/rabbitmq/issues/365#issuecomment-527984696

> Feature. If you are using the management load-definitions feature then 
> it's assumed you don't also want to be defining some other things elsewhere.



The load definitions feature and the default_user and default_vhost values in the configuration file (known as guest) are not compatible. If you use load definitions then the default `guest` and `vhost` settings will not be applicable. Right now the container will create an extra user if the `users` section in the load definition is not defined. My recommendation would be to use the load_definitions feature directly and define everything there.
