### ISSUE TITLE
RBAC configuration for OpenShift routes missing routes/custom-host resource

### ISSUE THREAD

**Issue by BWagenerGenerali** [bitnami/charts#9731]
### Name and Version

bitnami/grafana-operator 2.3.5

### What steps will reproduce the bug?

In this commit https://github.com/bitnami/charts/commit/d87dec202858e218f08470a8a28d5397426b6a6c?diff=split#r70792073 the resource "routes/custom-host" has been removed from the RBAC configuration.
We assume this is a mistake, the official grafana-operator RBAC configuration contains this resource https://github.com/grafana-operator/grafana-operator/blob/v4.2.0/config/rbac/role.yaml#L154

### What is the expected behavior?

The grafana-operator should have the RBAC permission to create OpenShift Routes with custom hostnames.

### What do you see instead?

The grafana-operator is unable to create an OpenShift Route with custom hostname with the following error:
DEBUG action-runner ( 2) FAILED create grafana route
DEBUG controller-runtime.manager.events Warning 
{"object": {"kind":"Grafana","namespace":"xyz","name":"xyz-grafana","uid":"7aea39e2-eac9-4f48-b4d5-37f346732198","apiVersion":"integreatly.org/v1alpha1","resourceVersion":"3167101"}, 
"reason": "ProcessingError", "message": "Route.route.openshift.io \"grafana-route\" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route"}

**Comment by javsalgar** [comment]
Hi!

Thanks for the PR! The team will take a look
