### ISSUE TITLE
zookeeper instances are in pending state so kafka is also crashing

### ISSUE THREAD

**Issue by sharmavickram** [bitnami/charts#9736]
### Name and Version

bitnami/kafka   tag: 2.8.1-debian-10-r31

### What is the problem this feature will solve?

need 3 brokers kafka to be installed and working

### What is the feature you are proposing to solve the problem?

need 3 brokers kafka to be installed and working

### What alternatives have you considered?

getting zookeeper in pending states only

![image](https://user-images.githubusercontent.com/9397194/162408660-2bb4b439-0641-4155-b398-ac6c8ef7dd22.png)
![image](https://user-images.githubusercontent.com/9397194/162408755-fdd234a7-39df-4452-8e9b-37a6f6364f78.png)

**Comment by javsalgar** [comment]
Hi,

I was not able to reproduce the issue

```
 1 ❯ kubectl get pods -w
NAME                READY   STATUS    RESTARTS   AGE
kafka-0             1/1     Running   1          20m
kafka-1             1/1     Running   1          20m
kafka-2             1/1     Running   1          20m
kafka-zookeeper-0   1/1     Running   0          20m
```

Could you provide more details about the k8s platform and volume provisioners you are using?
