### ISSUE TITLE
Parse Server - Connect to external MongoDB using mongodb+srv protocol

### ISSUE THREAD

**Issue by eelzinaty** [bitnami/charts#9741]
### Name and Version

bitnami/parse 17.0.8

### What is the problem this feature will solve?

Use external MongoDB instead of managing it.

### What is the feature you are proposing to solve the problem?

I want to have the option to set chart values that allows me to connect to external DB using `mongodb+srv` protocol. So in the chart options I can disable deploying MongoDB and use the external one.

### What alternatives have you considered?

Did not consider any. Open to suggestions!

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by Morriz** [comment]
Can this be re-opened? And how much work is it to get this chart to NOT deploy mongo and connect to a running svc?

**Comment by carrodher** [comment]
We didn't evaluate the complexity of this change but feel free to create a PR implementing it, we will review it and provide feedback.
