### ISSUE TITLE
canary development features.

### ISSUE THREAD

**Issue by rthamrin** [bitnami/charts#9743]
### Name and Version

bitnami/nginx-ingress-controller

### What is the problem this feature will solve?

enable canary future through the annotation

I got an error message "404" page not found when added the canary annotation

### What is the feature you are proposing to solve the problem?

support canary cookies, header and weight

### What alternatives have you considered?

snippets and configmap would be the good alternatives.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
