### ISSUE TITLE
bitnami/fluentd make plugins coinfigurable in chart

### ISSUE THREAD

**Issue by tridelt** [bitnami/charts#9744]
### Name and Version

bitnami/fluentd 5.0.15

### What is the problem this feature will solve?

This fluentd chart uses an elasticsearch plugin which is incompatible with elasticsearch 7
I cannot install another fluentd-elasticsearch plugin which would be compatible with elasticsearch 7.

### What is the feature you are proposing to solve the problem?

Make plugins configurable in the elasticsearch helm chart.

### What alternatives have you considered?

Using an older version of this chart which also uses an older fluentd-elasticsearch plugins which still support elasticsearch 7.

**Comment by javsalgar** [comment]
Hi,

In other charts we allow the use of init scripts in order to perform extra operations. Would that work for your use case?

**Comment by tridelt** [comment]
Dear @javsalgar,
thank you for your reply. Currently the elastic-search plugin is 5+ and I would need `4.3.3`.
I believe that the solution you suggested would fix my problem.
Yours 
@tridelt

**Comment by javsalgar** [comment]
Awesome, we will work on it. I cannot guarantee an ETA but as soon as we have more news we will update the ticket. If you want to speed up the process, feel free to submit a PR in the `bitnami-docker-fluentd` and `charts` repositories.

**Comment by tridelt** [comment]
Hi @javsalgar,
if you don't mind me asking I would be curious to find out what is the use-case to have an elastic-search plugin for `bitnami/fluentd 5.0.15` which doesn't support elastic-search 7. Because currently only elastic-search 7 comes as a [bitnami chart](https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch). Please excuse this nooby question. I am only trying to find a potential error in my thought process.
Yours
Tridelt

**Comment by javsalgar** [comment]
Our policy is to use the latest versions of any plugin we ship. Especially for the case of security issues (having an older version of the plugin became very problematic for us in the past). About the chart, while currently it may be pinned to ES version 7, you could change the image to use ES 8 (as we also distribute this version in our registries).  Furthermore, in the future we will change the default version used in the chart.

**Comment by tridelt** [comment]
Dear @javsalgar,
thank you very much for the reply. I greatly appreciate the support and also really like bitnami's charts and the awesome work you put in.
May I ask how I would change the image version to use ES 8?  I was unable to do so. Would you perhaps be so kind and point me to some online resource. : )
Hope you have an awesome day.
Yours Tridelt

**Comment by javsalgar** [comment]
Hi,

In order to change the Elasticsearch image, you can execute the following command for example:

```
helm install bitnami/elasticsearch --set image.tag=8
```

**Comment by tridelt** [comment]
@CeliaGMqrz phenomenal! thank you : )
