### ISSUE TITLE
Uploading custom config set via zookeper

### ISSUE THREAD

**Issue by leonidUH** [bitnami/charts#9745]
### Name and Version

bitnami/solr:8.11.1

### What steps will reproduce the bug?

1 prepare custom config set (CS)
2. upload it via zookeeper
/opt/bitnami/solr/bin/solr zk upconfig -n {CS_NAME} -d {CS_FOLDER} -z {ZK_HOST}:2181
3 create collection with this config set

   https://{SOLR_HOST}:8983/solr/admin/collections?action=CREATE&name= 
  {COLLECTION_NAME}&numShards=1&replicationFactor=1&maxShardsPerNode=1&collection.configName={CS_NAME}&wt=json

### What is the expected behavior?

expected behavior that after I upload a custom config set - I can create new collections with it

### What do you see instead?

I see that solr zk upconfig upload it to path /configs/{CS_NAME} but bitnami solr using /solr/configs/{CS_NAME} path on zookeeper.
Because this when I execute solr create a collection - I got error: Can not find the specified config set : {CS_NAME}

**Comment by leonidUH** [comment]
Hey
I can give you my config set, but that's not the problem. You can use any config set you want.
The problem is when I upload the config set to zookeeper  ( https://solr.apache.org/guide/8_11/using-zookeeper-to-manage-configuration-files.html#uploading-configuration-files-using-binsolr-or-solrj )
it saved under /configs/{CS_NAME} path , but bitnami solr using another /solr/configs/{CS_NAME} path on zookeeper .
I don't know how to change the path with "solr zk upconfig" command and I don't know how to change the zookeeper path that solr uses.
If you have another way to create or upload a custom config set (perhaps via helm values), I'd be happy to hear about it.

**Comment by leonidUH** [comment]
Hi @miguelaeh 
From solr documentation "**upconfig**" have only 3 parameters : 

- -n or -confname <arg>
For upconfig, linkconfig, downconfig: name of the configuration set

- -d or -confdir <path>
For upconfig: a directory of configuration files. For downconfig: the destination of files pulled from ZooKeeper

- -z or -zkhost <locations>
ZooKeeper host address. This parameter is mandatory for all CLI commands.

https://solr.apache.org/guide/8_11/command-line-utilities.html#using-solrs-zookeeper-cli
https://solr.apache.org/guide/8_11/solr-control-script-reference.html#zk-upload-parameters

**Comment by miguelaeh** [comment]
Hi @leonidUH ,
Could you give a try to set the path into the `-z` option like:
```
/opt/bitnami/solr/bin/solr zk upconfig -n {CS_NAME} -d {CS_FOLDER} -z {ZK_HOST}:2181/solr
```

**Comment by leonidUH** [comment]
Hi @miguelaeh 
It works now
Thank you
