### ISSUE TITLE
Allow --aws-zones-cache-duration in external-dns chart

### ISSUE THREAD

**Issue by scalp42** [bitnami/charts#9747]
### Name and Version

bitnami/external-dns 6.2.4

### What is the problem this feature will solve?

It should be possible to cache the API call that list hosted zones on Route53 side by making use of [--aws-zones-cache-duration=3h](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md) as an example.

### What is the feature you are proposing to solve the problem?

Adding a new flag here: https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/deployment.yaml#L177

`.Values.aws.zoneCacheDuration`

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by fmulero** [comment]
As mentioned in the PR, `extraArgs` value allows adding new parameters to external-dns not explicitly supported in the chart. More information in [README.md](https://github.com/bitnami/charts/tree/master/bitnami/external-dns#external-dns-parameters)
