### ISSUE TITLE
[bitnami/elasticsearch] Add the ability to populate the keystore on init

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#9750]
### Name and Version

bitnami/elasticsearch 17.9.25

### What is the problem this feature will solve?

Some plugins as `repository-s3` needs to be provisionned with the S3 credentials to access the repositories. These credentials need to be put inside the keystore. The keystore have to be provisioned before the start of elasticsearch in order to initialize correctly the plugin.

### What is the feature you are proposing to solve the problem?

It should be nice to have two things here:
- the possibility  to initialize the keystore by the chart
- the possibility to set the variables that would go to the keystore

### What alternatives have you considered?

Today, I'm using a pre-init script to configure it:

```bash
#!/bin/sh

elasticsearch-keystore create
echo "${ELASTICSEARCH_S3_CLIENT_ACCESS_KEY}" | elasticsearch-keystore add --stdin s3.client.default.access_key
echo "${ELASTICSEARCH_S3_CLIENT_SECRET_KEY}" | elasticsearch-keystore add --stdin s3.client.default.secret_key
```

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by jaudiger** [comment]
Hi @carrodher, I'll not have time anytime soon to work on this issue. But if I do, I'll let you know here.

**Comment by Rabah-h** [comment]
I'm using elasticsearch 7.17.24, and I'm facing the same problem, I can't find a stable way to put my s3 access key in the keystore.
