### ISSUE TITLE
[bitnami/elasticsearch] Add the possibility for a post init script

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#9751]
### Name and Version

bitnami/elasticsearch 17.9.25

### What is the problem this feature will solve?

Today, there is no possibility to easily do a post initialization once the elasticsearch cluster has booted.

### What is the feature you are proposing to solve the problem?

It could be nice to have a such parameter to let the user runs a post initialization script.

### What alternatives have you considered?

Currently, I'm running a job that wait the initialization of the elasticsearch cluster to run my post initialization script.

**Comment by javsalgar** [comment]
Hi,

Our charts already have init scripts support:

```
## @param initScripts Dictionary of init scripts. Evaluated as a template.
## Specify dictionary of scripts to be run at first boot
## Alternatively, you can put your scripts under the files/docker-entrypoint-initdb.d directory
## For example:
## initScripts:
##   my_init_script.sh: |
##      #!/bin/sh
##      echo "Do something."
##
initScripts: {}
## @param initScriptsCM ConfigMap with the init scripts. Evaluated as a template.
## Note: This will override initScripts
##
initScriptsCM: ""
## @param initScriptsSecret Secret containing `/docker-entrypoint-initdb.d` scripts to be executed at initialization time that contain sensitive data. Evaluated as a template.
##
initScriptsSecret: ""
```

Would that be enough for your use case?

**Comment by jaudiger** [comment]
Hi @javsalgar, if I read correctly the documentation (and from what I tried with this parameter), the init script does only run before the start of elasticsearch to prepare something. What I would like is a post init script that run once the cluster responds it's healthy (so when the readiness probe get the information of the readiness of the elasticsearch).

In this post init script, I need to do post configuration of the cluster through HTTP elasticsearch endpoints.

**Comment by javsalgar** [comment]
Right now, the only thing that comes to mind is to perform the wait for the `cluster healthy` inside the init script itself. As ES is running, it will eventually become to a ready state, so what I'd do is that, perform a loop inside the bash script and then perform the necessary operations.

**Comment by jaudiger** [comment]
I haven't tried yet this solution. Today, what i'm doing is:

- The `init script` is used to initialize the keystore as explained here (https://github.com/bitnami/charts/issues/9750)
- And a Kubernetes job is running when elasticsearch cluster is up.
