### ISSUE TITLE
[bitnami/redis] Slaves external access with Sentinel enabled

### ISSUE THREAD

**Issue by ustundagsemih** [bitnami/charts#9752]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

Trying to create Redis Sentinel instances. However an application outside the cluster can't talk with the slaves because of the clusterIP addresses.

I tried creating seperate services for each pod in order them to be accessible outside the cluster but in sentinel.conf it still shows the cluster IP addresses. 

Is it possible to change these clusterIP values with the newly created service IP addresses?

```
...
protected-mode no
user default on #157f6cb9a43ffc2f1b37c575ad291e18516d8560b7e07a2d97555f51b1ce74be ~* &* +@all
sentinel myid 1498ca445acc0c5f29ed61ae377f5695bccf88ea
sentinel config-epoch mymaster 2531
sentinel leader-epoch mymaster 2531
sentinel current-epoch 2531
sentinel known-sentinel mymaster 192.170.40.9 26379 b97643b725c3cdcb76acbb8d05a0ef9cd8c00fdf
sentinel known-sentinel mymaster 192.170.40.11 26379 8810a3916dcd9385f56528f246765257be6499f7
sentinel known-replica mymaster 192.170.40.9 6379
sentinel known-replica mymaster 192.170.40.11 6379
```

Also is it possible to inject these newly created service IP addresses into the output of `redis-cli info` somehow? When run against master, in slave:ip section, it shows only clusterIP addresses.

```
...
role:master
connected_slaves:2
slave0:ip=192.170.40.3,port=6379,state=online,offset=34617,lag=1
slave1:ip=192.170.40.4,port=6379,state=online,offset=34617,lag=1
...
```

### What do you see instead?

Only clusterIP addresses are available for Redis Sentinel. I would like to use LoadBalancer in order to reach from outside of the cluster.

**Comment by javsalgar** [comment]
Hi,

It seems that the redis container should also configure the `replica-announce-ip` in order to allow this external access. We will work on this, but we cannot guarantee an ETA. If you want to speed up the process, would you like to add support for a REDIS_ANNOUNCE_IP variable via a PR?

https://github.com/bitnami/bitnami-docker-redis/

**Comment by javsalgar** [comment]
Hi,

I believe because the announce ip should be only one, right? The one of the replica itself. Correct me if I'm wrong.
