### ISSUE TITLE
PostgreSQL in readReplicas section missing pgHbaConfiguration parameter

### ISSUE THREAD

**Issue by maleksan** [bitnami/charts#9768]
### Name and Version

bitnami/postgresql 11.1.18

### What is the problem this feature will solve?

PostgreSQL Helm chart version: 11.1.18
https://github.com/bitnami/charts/tree/master/bitnami/postgresql

In [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml) file for `readReplicas` section missing the following parameter (which is available in `master` section):

- readReplicas.pgHbaConfiguration

This will make it possible to configure the replica more granularly, for example, configure users access to replica.

### What is the feature you are proposing to solve the problem?

Please add this parameter/feature to the chart.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by maleksan** [comment]
Sorry, currently I can't do so.
