### ISSUE TITLE
Master and slave not syncing after failover

### ISSUE THREAD

**Issue by grace110693** [bitnami/charts#9774]
### Name and Version

 1.12.0

### What steps will reproduce the bug?

1. maria db is running in kubernetes pod on linux
2. 

### Are you using any custom parameters or values?

 datasource:
        url: jdbc:mysql:sequential://maria-mariadb-primary:3306,maria-mariadb-secondary:3306/grcont

### What is the expected behavior?

1.When slave master goes down and comes backup, sync between slave and master stops even after it comes up

### What do you see instead?

no sync between master and slave

**Comment by javsalgar** [comment]
Hi,

Could you let us know some detailed steps to reproduce the issue? The values you changed from the default, some steps to force the situation you desrcribe. That would be helpful to us to identify the issue.
