### ISSUE TITLE
Kafka chart has two services with the same port and the same labels

### ISSUE THREAD

**Issue by justinmchase** [bitnami/charts#9797]
### Name and Version

bitnami/kafka:15.0.0

### What steps will reproduce the bug?

1. `helm install -n example example bitnami/kafka`
2. `kubectl get -n example services -l app.kubernetes.io/component=kafka`

### Are you using any custom parameters or values?

no

### What is the expected behavior?

I expect there to be a single entry in the service list

```
NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
recovery-kafka            ClusterIP   10.96.118.12   <none>        9092/TCP            4d23h
```

### What do you see instead?

There are actually two entries in the list

```
NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
recovery-kafka            ClusterIP   10.96.118.12   <none>        9092/TCP            4d23h
recovery-kafka-headless   ClusterIP   None           <none>        9092/TCP,9093/TCP   4d23h
```

### Additional information

Label selectors are a common way to select services such as for port forwarding, but there is no way to tell the difference between the two services and they're both listening on port 9092. It would be really nice if there was a unique label on the headless service so they could be distinguished.

https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/svc-headless.yaml#L7
```
    app.kubernetes.io/component: kafka-headless
```

**Comment by javsalgar** [comment]
Hi,

The headless service is meant for the kafka pods to have a DNS entry for communication. Could you add more details about the issue you are facing by not distinguishing both services? Not sure if there are integration errors with another tool.

**Comment by justinmchase** [comment]
I have an application that is attempting to locate services by label selectors and there is no way to distinguish between the two services using label selectors.

It then does a port-forward based on the located service, It would just be nice if the two services each had a distinct label to be able to uniquely identify them.

**Comment by carrodher** [comment]
Thanks for your contribution! We will review the PR and provide feedback if needed
