### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by pagey101** [bitnami/charts#9800]
### Name and Version

bitnami/ejbca 5.1.11

### What steps will reproduce the bug?

Deploy the subject chart with the attached values.

### Are you using any custom parameters or values?

    values:
      persistence:
        enabled: true
        storageClass: longhorn
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hostname: ejbca.local
        annotations:
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: cert-manager-acme-issuer
        path: /*
        tls:
        - hosts:
          - ejbca.local
          secretName: ejbca.local
      mariadb:
        enabled: true
        architecture: standalone
        primary:
          persistence:
            enabled: true
            storageClass: longhorn
          configuration: |
            [mysqld]
            skip-name-resolve
            explicit_defaults_for_timestamp
            basedir=/opt/bitnami/mariadb
            plugin_dir=/opt/bitnami/mariadb/plugin
            port=3306
            socket=/opt/bitnami/mariadb/tmp/mysql.sock
            tmpdir=/opt/bitnami/mariadb/tmp
            max_allowed_packet=16M
            bind-address=0.0.0.0
            pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
            log-error=/opt/bitnami/mariadb/logs/mysqld.log
            character-set-server=UTF8
            collation-server=utf8_general_ci
            slow_query_log=0
            slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
            long_query_time=10.0
            [client]
            port=3306
            socket=/opt/bitnami/mariadb/tmp/mysql.sock
            default-character-set=UTF8
            plugin_dir=/opt/bitnami/mariadb/plugin
            [manager]
            port=3306
            socket=/opt/bitnami/mariadb/tmp/mysql.sock
            pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

### What is the expected behavior?

I expect the URL to be able to visit the URL without the 'internal server error', or see the cause of the error in the log.

### What do you see instead?

Internal server error

### Additional information

The MariaDB configuration is in the values because the default chart binds to IPv6, I'm changing the bind address to bind to IPv4.

Longhorn PVC class is used for persistence.

Traefik is used for ingress.

The pods startup and are in a 'Running' state, however I just get 'internal server error' when visiting https://ejbca.local.

I can't see any obvious errors in the ejbca log during initial startup or when visiting the application URL.

**Comment by javsalgar** [comment]
Hi,

I see several potential causes of errors here, so we should try to discard which one is the responsible.

- Storage: Could you try deploying it with persistence disabled? 
- Database: Could you try using the default database values instead of the custom configuration?
- Ingress: Does it happen when using an external IP instead of using nginx?

**Comment by iamwillbar** [comment]
@pagey101 were you able to solve this? I'm hitting the same issue.

**Comment by pagey101** [comment]
@iamwillbar I did not unfortunately, all I needed was a SCEP server so gave up and turned to [this](https://github.com/micromdm/scep) (which I highly recommend).
