### ISSUE TITLE
Support required for Helm installation for logstash and Kibana in IBM Cloud

### ISSUE THREAD

**Issue by sumcha** [bitnami/charts#9803]
### Name and Version

bitnami/kibana 7.17

### What steps will reproduce the bug?

Hi Team, I am looking for help with IBM opensource cloud offerings, "Logstash by Bitnami" and "Kibana by Bitnami" . I've done the helm installation for both products with default parameters. I can see, the pods for logstash are running but couldn't see a pod for kibana. We are very new to these products. Also, I would like to know how to log in to Kibana and logstash from the UI. We are also planning to deploy an elasticsreach instance by custom docker image in our cluster along with persistent volume. Any help in this regard would be very appreciated.

```console
$ kubectl get all -n sumit-test
NAME                       READY   STATUS    RESTARTS   AGE
pod/logstash2-ac2385b1-0   1/1     Running   0          2d

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/kibana2-d0f61f45              ClusterIP   172.21.187.171   <none>        5601/TCP   42s
service/logstash2-ac2385b1            ClusterIP   172.21.206.120   <none>        8080/TCP   2d
service/logstash2-ac2385b1-headless   ClusterIP   None             <none>        8080/TCP   2d

NAME                                  READY   AGE
statefulset.apps/logstash2-ac2385b1   1/1     2d
```

### Are you using any custom parameters or values?

default parameters provided by the offering

### What is the expected behavior?

How can we log in to logstash and Kibana and why there is no POD showing for Kibana. 

### What do you see instead?
```console
$ kubectl get all -n sumit-test
NAME                       READY   STATUS    RESTARTS   AGE
pod/logstash2-ac2385b1-0   1/1     Running   0          2d

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/kibana2-d0f61f45              ClusterIP   172.21.187.171   <none>        5601/TCP   42s
service/logstash2-ac2385b1            ClusterIP   172.21.206.120   <none>        8080/TCP   2d
service/logstash2-ac2385b1-headless   ClusterIP   None             <none>        8080/TCP   2d

NAME                                  READY   AGE
statefulset.apps/logstash2-ac2385b1   1/1     2d
```

### Additional information

Attached the instance details:
![logstash](https://user-images.githubusercontent.com/103648327/163402068-6753cb44-f6eb-4b16-92a8-a8f31a6cb444.png)
![kibana](https://user-images.githubusercontent.com/103648327/163402357-0abdc91e-50f2-427e-be01-3de2a4a4e85c.png)

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami ASSET container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
