### ISSUE TITLE
Incorrect singular form of affinities in documentation

### ISSUE THREAD

**Issue by krzwiatrzyk** [bitnami/charts#9807]
### Name and Version

bitnami/common 1.13.0

### What steps will reproduce the bug?

Try to include affinities templates according to documentation.

In the `_affinities.tpl` file definitions are spelled with plural form: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_affinities.tpl#L7

but in docs they are in singular: https://github.com/bitnami/charts/blame/master/bitnami/common/README.md#L46-L49 

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Include work

### What do you see instead?

Error:
```
error calling include: template: no template "common.affinities.pod.soft" associated with template "gotpl"
```

**Comment by fmulero** [comment]
Thanks a lot @krzwiatrzyk Would you like to contribute by creating a PR to solve the issue? You already did the hardest work.

[Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by krzwiatrzyk** [comment]
@fmulero I have created a MR: #9821

**Comment by fmulero** [comment]
Great! Thanks a lot for your contribution
