### ISSUE TITLE
pass external secret to be interpreted inside load_definitions file

### ISSUE THREAD

**Issue by Tajjar** [bitnami/charts#9814]
### Name and Version

bitnami/rabbitmq 8.31.4

### What steps will reproduce the bug?
```yaml
 extraSecrets:
   load-definition:
     load_definition.json: |
       {
         "users": [
           {
             "name": "bob",
             "password": "{{ .Values.existingPasswordSecret }}",
             "tags": "management"
           }
         ],
         "vhosts": [
           {
             "name": "/"
           }
         ],
         "permissions":[
           {
             "user":"bob",
             "vhost":"/",
             "configure":"",
             "write":".*",
             "read":".*"
           }
         ]
       }
loadDefinition:
   enabled: true
   existingSecret: load-definition
extraConfiguration: |-
   load_definitions = /app/load_definition.json
```

### What is the expected behavior?

using aws secret manager the expected behavior to defined key/value pair of password/password_value and have this read correctly inside the `load_definition.json` file as of the case where rabbitmq-password/password_value is used in case of `existingPasswrodSecret` under the `auth` section.

### What do you see instead?

as per templating one would get the name of the external secret instead of the value inside it

**Comment by miguelaeh** [comment]
Hi @Tajjar ,
IF I understood it properly, you want to put into the `load_definition.json` the content of a secret?

**Comment by Tajjar** [comment]
Hey @miguelaeh,
exactly, the aim is to be able to use an external secret for password secret just like the main user under àuth`

**Comment by miguelaeh** [comment]
Hi @Tajjar ,
Note the `.Values.existingPasswordSecret` is the name of a secret. Even making the template to render the value, what it will render is the name of the secret, not the content.
I think it is not possible to put the content of the secret there, you will need to put the password directly

**Comment by Tajjar** [comment]
Hey @miguelaeh,
That I know, that's why I am in favor of a solution where the existing secret can be used inside the load_definition.
Should I submit a feature request for that?

**Comment by miguelaeh** [comment]
Hi @Tajjar ,
I don't fully understand what you mean by `the existing secret can be used inside the load_definition`, could you clarify that, please?
Do you know how to render the secret content directly instead of the name?

**Comment by Tajjar** [comment]
Hey @miguelaeh,
I have kubernetes secret that contains username/password and want that to be parsed inside the load definition file.
Sadly, I don't know as of now.

**Comment by miguelaeh** [comment]
I am not sure if that's possible. The alternative I see is to create the secret with the whole content of the file and mount the secret as a file.
