### ISSUE TITLE
No Pod for Kibana found

### ISSUE THREAD

**Issue by mishra157** [bitnami/charts#9816]
### Name and Version

bitnami/kibana

### What steps will reproduce the bug?

We have installed the Kibana Package available on IBM Cloud 
but
We can not see any POD running for that 
whereas we can see the service is running and PVC is created 

deepakmishra@Deepaks-MacBook-Pro accesshub % kubectl get all -n elastic-stack | grep -i kibana
service/kibana2-b6bccb1c                            ClusterIP   172.21.81.20     <none>        5601/TCP            177m
deepakmishra@Deepaks-MacBook-Pro accesshub % 
deepakmishra@Deepaks-MacBook-Pro accesshub % 
deepakmishra@Deepaks-MacBook-Pro accesshub % kubectl get pvc -n elastic-stack | grep -i kibana            
kibana2-b6bccb1c                        Bound    pvc-23838d6a-d38e-4dbc-91a8-15c0e82ceeab   20Gi       RWO            ibmc-block-gold   178m
deepakmishra@Deepaks-MacBook-Pro accesshub % 

### What do you see instead?

We have installed the Kibana Package available on IBM Cloud 
but
We can not see any POD running for that 
whereas we can see the service is running and PVC is created 

deepakmishra@Deepaks-MacBook-Pro accesshub % kubectl get all -n elastic-stack | grep -i kibana
service/kibana2-b6bccb1c                            ClusterIP   172.21.81.20     <none>        5601/TCP            177m
deepakmishra@Deepaks-MacBook-Pro accesshub % 
deepakmishra@Deepaks-MacBook-Pro accesshub % 
deepakmishra@Deepaks-MacBook-Pro accesshub % kubectl get pvc -n elastic-stack | grep -i kibana            
kibana2-b6bccb1c                        Bound    pvc-23838d6a-d38e-4dbc-91a8-15c0e82ceeab   20Gi       RWO            ibmc-block-gold   178m
deepakmishra@Deepaks-MacBook-Pro accesshub %

**Comment by javsalgar** [comment]
Hi,

Could you let us know the values you used for installing the chart? Could you confirm if you installed bitnami/elasticsearch chart or bitnami/kibana chart?

**Comment by mishra157** [comment]
Hi 
We have installed the ES and Kibana provided by Bitnami in IBM Cloud 
Please see the attached screenshot 
<img width="958" alt="Screenshot 2022-04-19 at 4 48 47 PM" src="https://user-images.githubusercontent.com/59172369/163992527-bc0a579a-8935-49e8-a679-981c338cb046.png">
<img width="958" alt="Screenshot 2022-04-19 at 4 49 08 PM" src="https://user-images.githubusercontent.com/59172369/163992541-533e58ad-5dfc-42b4-8fa7-d1285e41b340.png">

**Comment by javsalgar** [comment]
You need to set the `global.kibanaEnabled` value to true in order to deploy Kibana. Is it possible to modify values of the chart or to update an existing release?

**Comment by mishra157** [comment]
ok let me try this

**Comment by mishra157** [comment]
Hi Thanks @javsalgar 
We got the kibana POD running now 

can you please help me how can we access Kibana logstash and ES using GUI ( in Browser)

**Comment by javsalgar** [comment]
In order to access from a browser you may need to change the service type (kibana.service.type value) to LoadBalancer or enable ingress (kibana.ingress.enabled)

**Comment by mishra157** [comment]
ok Thank you @javsalgar 
And what about the ES and Logstash services .? are they also can be accessed via GUI .?

**Comment by rafariossaa** [comment]
Hi,
  Logstash and elasticsearch does have a `service.type` parameter too.
