### ISSUE TITLE
how to trigger graceful shutdown?

### ISSUE THREAD

**Issue by ahu0605** [bitnami/charts#9828]
### Name and Version

bitnami helm kafka

### What is the problem this feature will solve?

kafka graceful shutdown for entire data save disk

### What is the feature you are proposing to solve the problem?

kafka data is not safe, it spend  too much time to restart server , leader and repliace or index need reload

### What alternatives have you considered?

when service stop ,exec shutdown.sh hook

**Comment by marcosbc** [comment]
You could specify `terminationGracePeriodSeconds` to specify the amount of seconds to wait for a pod to be stopped. I don't think something more specific (like executing a stop command) would be supported for Kubernetes.

**Comment by ahu0605** [comment]
> You could specify `terminationGracePeriodSeconds` to specify the amount of seconds to wait for a pod to be stopped. I don't think something more specific (like executing a stop command) would be supported for Kubernetes.

I think the node shutdown should exec kafka-server-stop.sh and wait time ,but I can not find anything in bitnami shell. I do not confirm the terminationGracePeriodSeconds duration can complete shutdown... the server should wait untill the shell be done!

**Comment by marcosbc** [comment]
It could be possible to add a `preStop` hook that executes the `kafka-server-stop.sh` script. However, it does not seem essential to get it working, or we would probably have seen a similar request in the past.

In any case, if you think it makes sense, feel free to contribute the required changes with a PR! We'd be happy to help with the review and release of the changes. You can find an example of `preStop` hooks [here](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/sttefulset.yaml#L279).

**Comment by ahu0605** [comment]
> It could be possible to add a `preStop` hook that executes the `kafka-server-stop.sh` script. However, it does not seem essential to get it working, or we would probably have seen a similar request in the past.
> 
> In any case, if you think it makes sense, feel free to contribute the required changes with a PR! We'd be happy to help with the review and release of the changes. You can find an example of `preStop` hooks [here](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/sttefulset.yaml#L279).

i will try and test

**Comment by jnt2007** [comment]
@ahu0605 Did you found a solution?
