### ISSUE TITLE
[bitnami/redmine] wrong mount path

### ISSUE THREAD

**Issue by ahmetemrebasakcioglu** [bitnami/charts#9837]
### Name and Version

bitnami/redmine 19.0.1

### What steps will reproduce the bug?

After installed with helm chart on my k8s cluster, (using external pvc -- default nfs) , i added external themes under my nfs folder /public/themes , none of the themes show up.
After that i entered the pod's shell, figured out that mounted path was /bitnami/redmine and my templates was under that folder. but program looks out /opt/bitnami/redmine folder.

after copied the themes under /opt/bitnami/redmine/public/themes then   themes show up succesfully.

also i tried to update mount folder with /opt/bitnami/redmine but there is no parameter option for that.

### Are you using any custom parameters or values?
```
replicaCount=1,service.type=NodePort,service.ports.http=xxxx,service.nodePorts.http=xxxx,databaseType=postgresql,mariadb.enabled=false,postgresql.enabled=false,externalDatabase.host=xxx.xxx.xxx.xxx,externalDatabase.user=xxxxx,externalDatabase.password=xxxx,externalDatabase.database=xxxxx,nodeSelector."kubernetes\\.io/hostname"=xxxxxx,persistence.storageClass=my-managed-nfs-storage -n redmine --create-namespace
```
### What is the expected behavior?

to show up copied themes (to clusterwide shared folder :  /bitnami/redmine/public/themes) on admin page theme settings. 

### What do you see instead?

none of the themes show up

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
