### ISSUE TITLE
[bitnami/redmine] k8s replicas causes to re-login after few clicks

### ISSUE THREAD

**Issue by ahmetemrebasakcioglu** [bitnami/charts#9838]
### Name and Version

bitnami/redmine 19.0.1

### What steps will reproduce the bug?

After installed with helm chart on my k8s cluster, (using external pvc -- default nfs) , with 3 replicas, everything work fine but after login, while surfing between pages, sometimes user session broke, and i have to re-login.

After downgrade to 1 replica, problem solved, thus i think it is a session-share issue.

### Are you using any custom parameters or values?

replicaCount=1,service.type=NodePort,service.ports.http=xxxx,service.nodePorts.http=xxxx,databaseType=postgresql,mariadb.enabled=false,postgresql.enabled=false,externalDatabase.host=xxx.xxx.xxx.xxx,externalDatabase.user=xxxxx,externalDatabase.password=xxxx,externalDatabase.database=xxxxx,nodeSelector."kubernetes\.io/hostname"=xxxxxx,persistence.storageClass=my-managed-nfs-storage -n redmine --create-namespace

### What is the expected behavior?

to continue session.

### What do you see instead?

session broke.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Please, note this Helm chart is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm chart. Any new issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

New versions are not going to be affected. Once a new version is released in the upstream project, the Bitnami container image will be updated to use the latest version.
