### ISSUE TITLE
Add metrics to read replicas

### ISSUE THREAD

**Issue by ajammali** [bitnami/charts#9869]
### Name and Version

bitnami/postgresql:11.1.22

### What is the problem this feature will solve?

Metrics are not available for read replica.

### What is the feature you are proposing to solve the problem?

Add the following to the read replica templates:

> Metrics sidecar to read statefulset.
> Metrics configmap for read replica.
> ServiceMonitor for read replica.
> PrometheusRule CRD for both read and primary replicas to avoid double alerting rules.

**Comment by carrodher** [comment]
In order to reproduce the issue on our side, could you share the specific parameters you're using when deploying the Helm chart or any other customization you're applying? In the same way, how are you checking the metrics?

**Comment by ajammali** [comment]
actually the metrics section is missing from the read replication values and the sidecar is not added as well. So there are no values to show.
Also the serviceMonitor and metrics ConfigMap of read replica are not there.
I suggest we add them so we can start have metrics for read replication as well.
I've already implemented them and I can push them today.

**Comment by carrodher** [comment]
Thanks for reporting this issue; yes, that would be nice. If you would like to contribute by creating a PR, the Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your PR. Let's wait until it get reviewed and merged.

**Comment by ajammali** [comment]
Hello, any feedback on this ?

**Comment by carrodher** [comment]
Feedback was provided in the PR, can you take a look?

**Comment by ajammali** [comment]
@carrodher it's all been taken care of :)

**Comment by rafariossaa** [comment]
Hi,
  The PR got reviewed. There are some comments added.
