### ISSUE TITLE
add ability to create minio service accounts by provisioning

### ISSUE THREAD

**Issue by nir-bar-zvi** [bitnami/charts#9876]
### Name and Version

bitnami/minio

### What is the problem this feature will solve?

minio service account can not be provisioned (like regular users can) when `provisioning.enabled` is `true`

### What is the feature you are proposing to solve the problem?

currently, we can define a set of users in `provisioning.users` to be created in minio - service accounts can be defined in a similar list and created using mc

### What alternatives have you considered?

- creating manually 
- running mc in bash post startup

**Comment by carrodher** [comment]
Thanks for this suggestion. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
