### ISSUE TITLE
[bitnami/kube-prometheus] podMetadata or podLabels for operator

### ISSUE THREAD

**Issue by BernhardGruen** [bitnami/charts#9887]
### Name and Version

bitnami/kube-prometheus 6.9.5

### What is the problem this feature will solve?

Currently there is no direct way to set pod labels for the operator. Currently the only way to set pod labels for the operator is to use `global.labels` (which is currently broken, see #9886). But this has the big disadvantage that those labels are then added to way too much pods, services, etc.

### What is the feature you are proposing to solve the problem?

I would like to see something like `operator.podMetadata` or `operator.podLables` to set labels just for the operator.

**Comment by joancafom** [comment]
Hi @BernhardGruen 

We are currently making efforts to standardize all of our charts, adding common and helpful features that should be available across all of them (see https://github.com/bitnami/charts/pull/9441 for example). Indeed, `podLabels` are one of them! 

Hence, you should expect them to be added to this chart eventually, though I can't provide you with an exact ETA. Nevertheless, if this is something you would like to contribute with, you can send a PR adding support for them and we will be more than happy to review it 😊
