### ISSUE TITLE
[bitnami/suitecrm] crontab is not installed

### ISSUE THREAD

**Issue by royanon** [bitnami/charts#9889]
### Name and Version

bitnami/suitecrm

### What steps will reproduce the bug?

Helm chart version
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
xxx        xxx        6               2022-04-11 10:41:35.588616558 +0000 UTC deployed        suitecrm-10.0.11        7.12.5

The scheduler does not run, and no crontab founded

### What is the expected behavior?

scheduler should run

### What do you see instead?

no scheduler run

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/suitecrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by royanon** [comment]
A quick & dirty fix on it without any modification and patch.
Run the container and pod as 0, set RunAsNonRoot false.
The cron tab and necessary script will run correctly except php
To make php run, use lifecycleHooks to change the ownership of /bitnami/suitecrm to owner 1 (daemon)

**Comment by migs35323** [comment]
I am having the same issue
sadly this chart seems like a basic bitnami deployment, the chart feels abandoned and missing plenty of stuff
