### ISSUE TITLE
typo in deployment.yaml causes deployment to fail when `volumePermissions.enabled` is set

### ISSUE THREAD

**Issue by aleofreddi** [bitnami/charts#9890]
### Name and Version

bitnami/redmine 20.0.1

### What steps will reproduce the bug?

1. Run `helm install test bitnami/redmine --set volumePermissions.enabled=true`
2. See the following error:

```
Error: YAML parse error on redmine/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: did not find expected node content
```

### Are you using any custom parameters or values?

`--set volumePermissions.enabled=true`

### What is the expected behavior?

The chart gets installed, or at least the template renders.

### What do you see instead?

```
Error: YAML parse error on redmine/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: did not find expected node content
```

### Additional information

This is caused by a typo in deployment introduced in 228286b12885a06947e57bbb08a229ecce0b1d54.

**Comment by rafariossaa** [comment]
Hi,
  Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback
