### ISSUE TITLE
Prometheus Exporter for Solr Helm chart does not work

### ISSUE THREAD

**Issue by eroji** [bitnami/charts#9892]
### Name and Version

bitnami/solr-4.0.8

### What steps will reproduce the bug?

Install the Helm chart with LoadBalancer service type for Solr and enabling Prometheus Exporter

### Are you using any custom parameters or values?

Using `service.type=LoadBalancer,metrics.enabled=true`

### What is the expected behavior?

Prometheus Exporter sidecar should be deployed along with corresponding service

### What do you see instead?

Prometheus Exporter is completely missing and no corresponding service is created

**Comment by miguelaeh** [comment]
Hi @eroji ,
Are you configuring authentication? If yes, please note that authentication and metrics are not compatible in this Helm Chart.

**Comment by eroji** [comment]
@miguelaeh yes basic auth is enabled. Are you saying that Prometheus exporter cannot be enabled if auth is turned on? If so, any reason why this is?

**Comment by miguelaeh** [comment]
> Are you saying that Prometheus exporter cannot be enabled if auth is turned on? If so, is any reason why this is?

Exactly. The Solr exporter is a script provided by the Solr team, and at the moment of the container and chart creation, it didn't support parameters for authentication.
Checking the docs again, it looks that it is now supported only for Solr cloud.
