### ISSUE TITLE
Helm chart - postgres values

### ISSUE THREAD

**Issue by jefimm** [bitnami/charts#9897]
### Name and Version

latest

### What steps will reproduce the bug?

Deploying superset with helm chart fails

### Are you using any custom parameters or values?

n/a

### What is the expected behavior?

install successful

### What do you see instead?

install fails to init database because superset user is not created

### Additional information

The bitnami helm chart for postgres uses different values than specified in the superset 
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L121-L127

but superset is using 

https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L387-L394

**Comment by javsalgar** [comment]
Hi,

It seems that the superset did not update the values to the new major version. Could you check with the superset team so they can update the  values accordingly?

**Comment by jefimm** [comment]
sorry, this one was supposed to go to superset...
