### ISSUE TITLE
keycloak, getting 404 at /admin

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#9900]
### Name and Version

keycloak:7.1.17

### What steps will reproduce the bug?

Kubernetes 1.23.6

### Are you using any custom parameters or values?

values.yaml
```
keycloak:

  # use to increase logging
  image:
    debug: false

  # required otherwise you get a blank page when visiting the admin console
  proxyAddressForwarding: true

  extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.k.home.net"

  # to specify the ad ca public certificate in order to access ldaps
  auth:
    tls:
      enabled: true
      existingSecret: keycloak-certs
      keystorePassword: changeit
      truststorePassword: changeit

  ingress:
    enabled: true
    hostname: keycloak.k.home.net
    ingressClassName: nginx
    pathType: Prefix
    tls: true
    annotations:
      cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
      cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
      cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

  postgresql:
    enabled: true
    auth:
      password: asdfasdf
```

### What is the expected behavior?

A working keycloak installation.

### What do you see instead?

I can see the main screen at the expected fqdn:  keycloak.k.home.net

However, if I click on Console (which takes me to https://keycloak.k.home.net/admin/) I get a 404.

### Additional thoughts

On a previous install if I highlight the Console link it gives '/auth/admin' rather than the '/admin' this installation is giving.  Could this indicate what the problem is?  If I try typing in '/auth/admin' I get redirected to '/admin/master/console' & still get 404.

**Comment by javsalgar** [comment]
Hi,

Could you try setting it to this?

```
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.k.home.net/auth"
```

**Comment by javsalgar** [comment]
It worked for me 
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1133777/165078091-f937d1a6-8ade-46af-bfbb-cd8bed225128.png">

**Comment by lknite** [comment]
adding /auth to that variable got me to the login prompt, if that's a new change the main documentation page will need to be updated:  https://github.com/bitnami/charts/tree/master/bitnami/keycloak  (down near the bottom)

However, I am unable to login, am getting 'invalid_user_credentials'.  Possibly related?

I'm trying 'user' and the password obtained with:
```
kubectl -n keycloak get secrets keycloak -o jsonpath='{.data.admin-password}' | base64 -d
```

Were you able to login after you got things working by adding '/auth' to the environment variable?

**Comment by javsalgar** [comment]
Hi!

I had no issue with the login

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/1133777/165477144-8a4715c8-6a86-4858-af6c-414f8c679cb1.png">


Could it be that you have volumes from previous installations?

**Comment by lknite** [comment]
Upon investigation my pvc was the exact same age as other processes.  In any case, decided to try your idea, deleted the namespace and allowed everything to come back to life.  Long as '/auth' is added, everything works.

Thank you for your help!
