### ISSUE TITLE
bitnami Mongodb 5.0.7 MongoServerError: reshardCollection command not enabled

### ISSUE THREAD

**Issue by Alansyf** [bitnami/charts#9903]
### Name and Version

bitnami/mongodb-sharded:5.0

### What steps will reproduce the bug?

helm install bitnami/mongodb-sharded:5.0. 

MongoDB version: 
`[direct: mongos] testshard1> db.version()
5.0.7`

`[direct: mongos] testshard1> sh.shardCollection("testshard1.test11", {"_id": 1})
{
  collectionsharded: 'testshard1.test11',
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1650859351, i: 14 }),
    signature: {
      hash: Binary(Buffer.from("5c400bfa41f2a1b8f3acffc5a9d5d83193c566fe", "hex"), 0),
      keyId: Long("7067366190192001047")
    }
  },
  operationTime: Timestamp({ t: 1650859351, i: 3 })
}`

`[direct: mongos] testshard1> sh.reshardCollection("testshard1.test11", {"_id": "hashed"})
MongoServerError: reshardCollection command not enabled
`

### Are you using any custom parameters or values?

No

### What do you see instead?

`[direct: mongos] testshard1> sh.reshardCollection("testshard1.test11", {"_id": "hashed"})
MongoServerError: reshardCollection command not enabled
`

### Additional information

According to document here: https://www.mongodb.com/docs/manual/core/sharding-reshard-a-collection/, we should be able to execute the reshard command however it failed.

**Comment by fmulero** [comment]
Hi @Alansyf thanks for sharing it. QQ Are you testing the changes in this PR #9829?

**Comment by Alansyf** [comment]
> Hi @Alansyf thanks for sharing it. QQ Are you testing the changes in this PR #9829?

No @fmulero . I am just verifying how resharding works in mongo 5.0.

**Comment by fmulero** [comment]
Hi @Alansyf I am trying to reproduce your issue before realising #9829 but I am not able to reproduce it. Are you able to reproduce your issue with those changes?
