### ISSUE TITLE
Custom command is wrongly interpolated in start-node.sh

### ISSUE THREAD

**Issue by baflo** [bitnami/charts#9912]
### Name and Version

bitnami/redis@6.8.7

### What steps will reproduce the bug?

1. Set `.Values.replica.command`
2. Try to install
3. Container `redis` won't start due to error `/opt/bitnami/scripts/start-scripts/start-node.sh: line 147: /[/bin/bash]: No such file or directory`

### Are you using any custom parameters or values?
```
replica:
  command:
    - /bin/bash
```

### What is the expected behavior?

When trying to replace the default command from [sentinel/stateful-set.yaml](https://github.com/bitnami/charts/blob/58f7748479c906fae4310c20bb2bbfe2a89e2fb1/bitnami/redis/templates/sentinel/statefulset.yaml#L108), this should not break the deployment.

### What do you see instead?

Container `redis` won't start due to error `/opt/bitnami/scripts/start-scripts/start-node.sh: line 147: /[/bin/bash]: No such file or directory`

### Additional information

The error seems to be in `scripts-configmap.yaml`, where the command is not parsed for the command line: https://github.com/bitnami/charts/blob/58f7748479c906fae4310c20bb2bbfe2a89e2fb1/bitnami/redis/templates/scripts-configmap.yaml#L620

**Comment by javsalgar** [comment]
Hi,

Thank so you much for reporting! Indeed, the `command` section is not correctly parsed. Actually, I'm not sure if that `if` section in the configmap makes sense. I'd say that scripts-configmap is meant to be used with the default parameters. I'd advocate to remove that if statement, thoughts?
