### ISSUE TITLE
Missing "context" literal in https://github.com/bitnami/charts/blob/master/bitnami/metallb/templates/speaker/daemonset.yaml

### ISSUE THREAD

**Issue by tmeltser** [bitnami/charts#9913]
### Name and Version

bitnami/metallb 3.0.0

### What steps will reproduce the bug?

Install the latest chart, with adding the following customization:
```
speaker:
  tolerations:
  - key: "cattle.io/os"
    operator: "Equal"
    value: "linux"
    effect: "NoSchedule"
```
Helm installation will fail with the following error message:
```
Error: template: metallb/templates/speaker/daemonset.yaml:51:23: executing "metallb/templates/speaker/daemonset.yaml" at <include "common.tplvalues.render" (dict "value" .Values.speaker.tolerations $)>: error calling include: template: metallb/charts/common/templates/_tp
lvalues.tpl:11:34: executing "common.tplvalues.render" at <.context>: wrong type for value; expected chartutil.Values; got interface {}
```

### Are you using any custom parameters or values?

Mentioned above

### What is the expected behavior?

Helm installation should pass successfully.

### What do you see instead?

The error message mentioned above

### Additional information

The problem is in line 51 of the template:
Before the last update it was:
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.speaker.tolerations "**context**" $) | nindent 8 }}
And now (from April 22nd) it is (missing "**context**"):
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.speaker.tolerations $) | nindent 8 }}

Kindly revert to the working version ASAP.

**Comment by rafariossaa** [comment]
Hi,
  I can see you sent a PR to fix this.
  Let's wait until it is reviewed and merged.

**Comment by tmeltser** [comment]
> Hi, I can see you sent a PR to fix this. Let's wait until it is reviewed and merged.

I didn't send any PR, just reported the bug and indicated the exact place and the correction.
