### ISSUE TITLE
[bitnami/nginx] no way to configure ingress without host

### ISSUE THREAD

**Issue by JulienHoullier** [bitnami/charts#9914]
### Name and Version

bitnami/nginx 10.1.3

### What steps will reproduce the bug?

1. expose nginx pod through an Ingress controller using Ingress without host routing
2. activate ingress for chart and set hostname: ""
3. helm install
4. K8S complains since no rules are set for the Ingress. Chart template expect either hostname not empty or a list of extraHost. 

### Are you using any custom parameters or values?

--set ingress.enabled=true --set ingress.hostname="" 

### What is the expected behavior?

An working Ingress without host routing

### What do you see instead?

K8S error since no Ingress rules defined.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporitng. Indeed, right now we are forcing to use a hostname. I believe that we should changed the `{{- if  ... }}` statement in ingress.yaml to allow not using a hostname. Would you like to submit a PR?
