### ISSUE TITLE
Is there a way to use nginx stable (1.20 vs 1.21)?

### ISSUE THREAD

**Issue by rlewkowicz** [bitnami/charts#9924]
### Name and Version

bitnami/nginx-ingress-controller latest 

### What steps will reproduce the bug?

Not a bug, just a question

### What do you see instead?

I would like to see nginx 1.20 if possible.

**Comment by carrodher** [comment]
You can use any valid image tag by specifying `defaultBackend.image.tag`, for example `defaultBackend.image.tag=1.20`. Supported tags are listed at https://github.com/bitnami/bitnami-docker-nginx#supported-tags-and-respective-dockerfile-links.

Please note this configuration is supported but not tested.
