### ISSUE TITLE
[bitnami/etcd] PodDisruptionBudget should be enabled by default

### ISSUE THREAD

**Issue by cdemi** [bitnami/charts#9927]
### Name and Version

bitnami/etcd

### What is the problem this feature will solve?

Without PDBs, every time a cluster is updated, since Kubernetes is not aware of how to handle the application without PDB, it may cause a majority failure. 

According to [the etcd docs on Majority Failure](https://etcd.io/docs/v3.5/op-guide/failures/#majority-failure):
> When the majority members of the cluster fail, the etcd cluster fails and cannot accept more writes.
>
>The etcd cluster can only recover from a majority failure once the majority of members become available. If a majority of members cannot come back online, then the operator must start disaster recovery to recover the cluster.

This means that manual intervention is needed.

### What is the feature you are proposing to solve the problem?

I see that this chart already has PDB configuration set, which is good. However I propose to have PDB be set to default true. Given that "we (chart developers)" are aware of the app we are deploying I don't think we ever want consumers of the chart to enable PDB. The reality is, those who haven't PDB enabled on the chart are most probably unaware how etcd handles a majority failure and if explained to them they will turn it on.

I am pretty new to helm charts so I am not sure if it is possible to automatically set PDB to the minimum of `(N-1)/2` of the replica count

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by cdemi** [comment]
Thanks! I have opened #9929 for your review

**Comment by carrodher** [comment]
Thanks for the PR, we will review it and provide feedback
