### ISSUE TITLE
How to upgrade influxdb from 4.0.11 to 4.0.12 ?

### ISSUE THREAD

**Issue by konopka90** [bitnami/charts#9932]
### Name and Version

bitnami/influxdb 4.0.12

### What steps will reproduce the bug?

1. Environment 
- Kubernetes v1.20.15
- Longhorn 1.2.4

2. Steps to reproduce

I am using influxdb chart 4.0.11 with default values and want to perform the upgrade to 4.0.12 with default values.

```
helm upgrade -i influxdb  ~/Downloads/influxdb-4.0.11.tgz
export ADMIN_USER_PASSWORD=$(kubectl get secret --namespace "default" influxdb -o jsonpath="{.data.admin-user-password}" | base64 --decode
export ADMIN_USER_TOKEN=$(kubectl get secret --namespace "default" influxdb -o jsonpath="{.data.admin-user-token}" | base64 --decode)
helm upgrade -i influxdb  ~/Downloads/influxdb-4.0.12.tgz   --set auth.admin.password=$ADMIN_USER_PASSWORD   --set auth.admin.token=$ADMIN_USER_TOKEN
```

The upgrade is accepted but the newly created Pod is stuck in "Containercreating" status. Volume from the old Pod is not detached and the new Pod cannot mount the existing volume. Am I missing some important k8s configuration about volumes? 

### What is the expected behavior?

Old Pod should be killed and the new Pod should be in status "Running"

### What do you see instead?

![image](https://user-images.githubusercontent.com/5208485/165280170-1bb7b50f-0960-41ae-b761-fb8f6aefa4ed.png)

![image](https://user-images.githubusercontent.com/5208485/165280301-5ddef6ea-29d8-42d1-824b-5caf4ed4ea45.png)

```
FailedMount (9) | 2.2  mins ago | Unable to attach or mount volumes: unmounted  volumes=[data], unattached volumes=[data default-token-r5ltd]: timed out  waiting for the condition
-- | -- | --
FailedMount (2) | 18  mins ago | Unable to attach or mount volumes: unmounted  volumes=[data], unattached volumes=[default-token-r5ltd data]: timed out  waiting for the condition
FailedAttachVolume | 26  mins ago | Multi-Attach error for volume  "pvc-fd6a6c36-065e-4e60-a15b-e8a29c8ee4a9" Volume is already used by  pod(s) influxdb-5c88bbbc44-bmrn5
Scheduled | 26  mins ago | Successfully assigned default/influxdb-65f6ccc9bd-kmfwn to master-gamma
```

**Comment by migruiz4** [comment]
Hi @konopka90,

To avoid having to perform the delete the previous pod manually, you can upgrade with the value `--set influxdb.updateStrategy.type=Recreate`
