### ISSUE TITLE
Error in helm lint

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#9944]
### Name and Version

bitnami/mysql

### What steps will reproduce the bug?

Helm lint

### What is the expected behavior?
```
/templates/_helpers.tpl:114:18: executing "mysql.secretName" at <.Values.auth.existingSecret>: nil pointer evaluating interface {}.existingSecret
```
### What do you see instead?

No helm lint error

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue:

```
❯ helm lint
==> Linting .

1 chart(s) linted, 0 chart(s) failed
 ~/projects/bitnami-charts/bitnami/mysql 
```

Could you ensure you are using the latest version of the chart?

**Comment by pankaj-dahiya** [comment]
Hi @javsalgar  Thanks for reply.
I am using it inside my parent chart. My directory structure is:
BackendApp
    charts
        MySQL
    templates
    charts.yaml
    values.yaml

When I am linting MySQL chart then there is no error. Whereas, when I lint BankendApp chart, then it shows error in Mysql chart!

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MySQL Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
