### ISSUE TITLE
[rabbitmq] auth user tag option

### ISSUE THREAD

**Issue by Tajjar** [bitnami/charts#9945]
### Name and Version

bitnami/rabbitmq 8.32.1

### What is the problem this feature will solve?

Currently we want to have the main rabbitmq user without admin privileges.

### What is the feature you are proposing to solve the problem?

It would be nice to have more flexibility under the `auth` in `values.yaml` to include user `tag` option. 

### What alternatives have you considered?

Tried `extraSecrets` where we would lose the usage of `existingPasswordSecret`

**Comment by carrodher** [comment]
Thanks for the suggestion. Would you like to contribute by creating a PR implementing it? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
