### ISSUE TITLE
Migrate MySql to SQLServer

### ISSUE THREAD

**Issue by ISSebastianRamirez** [bitnami/charts#9956]
### Name and Version

bitnami/redmine 5.0.0

### What is the problem this feature will solve?

Hi, I have a doubt. How can I migrate the database from MySql to SqlServer? I already installed redmine through bitnami but by default it is installed with mysql, what can I do to be able to install it with sqlserver or allow me to migrate it to sqlserver?

### What is the feature you are proposing to solve the problem?

doubt

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by ISSebastianRamirez** [comment]
Where else can I ask for help to solve my question?
