### ISSUE TITLE
[bitnami/argo-cd] Fix issue with server.config kustomize.buildOptions

### ISSUE THREAD

**Issue by pedominguezbr** [bitnami/charts#9957]
### Name and Version

bitnami/argo-cd 

### What is the problem this feature will solve?

in the server.config there is no data kustomize.buildOptions

### What is the feature you are proposing to solve the problem?

enable the kustomize.buildOptions in the server config cm

### What alternatives have you considered?

`
server:
  config: |
    kustomize.buildOptions: "--enable-helm"
`

https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/

**Comment by marcosbc** [comment]
@pedominguezbr Feel free to contribute this feature with a PR. If it is a simple parameter, it shouldn't be very complex to add it.
