### ISSUE TITLE
[bitnami/postgresql] Best / fastest way to do major db updates

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#9959]
### Name and Version

bitnami/postgresql

### What is the problem this feature will solve?

Currently it seems there is no build-in way to upgrade postgresql major versions. I use terraform to deploy all my charts and postgresql is the only image which has no build-in major db upgrade feature.

I know it's not easy. databases are easy to backup and restore, but whats the best ways to also backup / restore or recreate the users and permissions ?

### What is the feature you are proposing to solve the problem?

I like to have a simple build-in way todo major upgrade. Or at least a nice documentation to have some kind of automation.

**Comment by viceice** [comment]
BTW: it would be nicht to have discussions enabled, so i don't need to open an issue for those discussions (the community forum is sending to github for any container help / issues)

**Comment by viceice** [comment]
Velero isn't an option, as postgresql major versions aren't binary compatible and there is no simple migration tool.
So the only options is to export / import sql data. 😕 

So my best idea is to create some sql scripts for the user generation and use the initdb feature to auto create the users and then restore the data.

**Comment by rafariossaa** [comment]
I agree, In that case, that is the only option I can think of right now.
