### ISSUE TITLE
[bitnami/node] Add support for `startupProbe`

### ISSUE THREAD

**Issue by garyng** [bitnami/charts#9976]
### Name and Version

bitnami/node 17.0.21

### What is the problem this feature will solve?

Seems like most of the chart support `startupProbe`, is it possible to add it to `bitnami/node` as well?

### What is the feature you are proposing to solve the problem?

Support specifying `startupProbe` in values file.

**Comment by carrodher** [comment]
Thanks for creating the associated PR, we'll review it and provide feedback
