### ISSUE TITLE
cannot get bitnami/postgresql-ha work on bare-metal server using helm

### ISSUE THREAD

**Issue by ptca89** [bitnami/charts#9980]
### Name and Version

bitnami/postgresql-ha 9.0.3

### What steps will reproduce the bug?

1. set up a 3 nodes on bare-metal servers in house; setup NFS, deploy a storageClass (nfs-client)  using  https://github.com/kubernetes-sigs/[nfs-subdir-external-provisioner]
2. No firewall enabled, tested the environment using helm install with bitnami/postgresql, connection works fine. I can use psql to access the db.
3.  Run `helm install my-release --set global.storageClass=nfs-client bitnami/postgresql-ha`
4. Only  pod `my-release-postgresql-ha-postgresql-0` is READY, the other two postgresql pods and postgresql-ha-pgpool pod fail to start, with error as:
```
Warning  Unhealthy  92s (x1282 over 15h)    kubelet  Liveness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?
```

### Are you using any custom parameters or values?

`--set global.storageClass=nfs-client`

### What is the expected behavior?

all 4 pods should be in READY status

### What do you see instead?
```console
$ kubectl get pod
NAME                                                      READY   STATUS    RESTARTS        AGE
my-nfs-nfs-subdir-external-provisioner-776466db9b-b86xf   1/1     Running            0                 16h
my-release-postgresql-ha-pgpool-69d56bf4cb-qmlrv          0/1     Running            127 (2m53s ago)   15h
my-release-postgresql-ha-postgresql-0                     1/1     Running            0                 15h
my-release-postgresql-ha-postgresql-1                     0/1     Running            211 (76s ago)     15h
my-release-postgresql-ha-postgresql-2                     0/1     CrashLoopBackOff   217 (28s ago)     15h
```

**Comment by ptca89** [comment]
> Hi, Do you mind to proper format the issue ? That way it would be much more readable.

Hi Rafariossaa, I formatted the issue. Thank you.

**Comment by carrodher** [comment]
Are you facing the same issue when deploying the Helm chart with default values? I mean, without using `global.storageClass=nfs-client` which seems to be the only customization you're doing.

**Comment by ptca89** [comment]
> Are you facing the same issue when deploying the Helm chart with default values? I mean, without using `global.storageClass=nfs-client` which seems to be the only customization you're doing.

Hi Carrodher, I am deploying the cluster using my own computers. default storage class does not not work at all.

**Comment by carrodher** [comment]
Unfortunately, I'm not able to reproduce the issue. Deploying the Helm chart without setting the `storageClass` (using defaults) or even setting a custom one, everything is up and running as expected, not sure if it is something related to your environment or any other configuration
