### ISSUE TITLE
[bitnami/prometheus] Prometheus operator clusterrole missing  "- prometheuses/status" line from original chart, causing prometheus-operator errors

### ISSUE THREAD

**Issue by thatguythat1031** [bitnami/charts#9988]
### Name and Version

bitnami/kube-prometheus

### What steps will reproduce the bug?

1. Deploy the chart to an EKS cluster with rbac.enabled set to true (although this error should manifest regardless of the cluster being cloud-provider managed or not)
2. Wait up to 30 minutes for all pods to be running.
3. Check the logs for the prometheus operator pod, you will see errors in the form:
```
level=error ts=2022-04-28T20:18:31.207305054Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"<prometheus-namespace>/prometheus-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"prometheus-kube-prometheus-prometheus\" is forbidden: User \"system:serviceaccount:<prometheus-namespace>:prometheus-kube-prometheus-operator\" cannot update resource \"prometheuses/status\" in API group \"monitoring.coreos.com\" in the namespace \"<prometheus-namespace>\"".
```
This error will reoccur at least every 15 minutes.

This error happens because if you check this rule in the chart: https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml#L29 you'll notice that it's missing a single line from the original chart: https://github.com/prometheus-operator/prometheus-operator/blob/8ebf3f5df3b3d859e1ff87a0b9442e17c5afca60/example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml#L18j. Adding that line should fix this issue. 

### Are you using any custom parameters or values?

rbac.create: true

Disabling other additional parts of the helm chart like the alertmanager and various exporters makes it easier to filter for this error. 

### What is the expected behavior?

Expected behavior is that the prometheus-operator clusterrole has access to prometheuses/status in the api group monitoring.coreos.com as this is needed for the prometheus-operator to manage prometheus. 

### What do you see instead?
``
This error: level=error ts=2022-04-28T20:18:31.207305054Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"<prometheus-namespace>/prometheus-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"prometheus-kube-prometheus-prometheus\" is forbidden: User \"system:serviceaccount:<prometheus-namespace>:prometheus-kube-prometheus-operator\" cannot update resource \"prometheuses/status\" in API group \"monitoring.coreos.com\" in the namespace \"<prometheus-namespace>\""
```
### Additional information

_No response_

**Comment by danielcrisap** [comment]
I opened a PR https://github.com/bitnami/charts/pull/10014 for including this new resource on ClusterRole

**Comment by migruiz4** [comment]
Thanks, @thatguythat1031 for reporting the issue and @danielcrisap for submitting a fix!

The fix looks good to me, so it will be merged and release in the next version of the kube-prometheus chart. Please let me know if the issue can be closed after that.
