### ISSUE TITLE
Setting metrics.enabled to true, causes autoscaling to break

### ISSUE THREAD

**Issue by timofey-momsdish** [bitnami/charts#9994]
### Name and Version

bitnami/wordpress 14.0.4

### What steps will reproduce the bug?

1. Install WordPress chart with values `metrics.enabled: true` and `autoscaling.enabled: true`
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/wordpress --set metrics.enabled="true" --set autoscaling.enabled="true"
```
2. Install metrics-server
```
helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
helm install metrics-server metrics-server/metrics-server
```

### Are you using any custom parameters or values?

helm install my-release bitnami/wordpress `--set metrics.enabled="true"` `--set autoscaling.enabled="true"`

### What is the expected behavior?

HorizontalPodAutoscaler should work.
When you type in `kubectl get hpa -A`, HPA should return the current percentage (%) of memory/cpu being used, see screenshot
<img width="719" alt="Screen Shot 2022-04-30 at 9 59 19 PM" src="https://user-images.githubusercontent.com/98995766/166130583-a40ec3c7-8bf7-4890-9c0b-6a48ea9ddc72.png">
.

### What do you see instead?

HorizontalPodAutoscaler does not work.
When you type in `kubectl get hpa -A`, HPA shows `<unknown>`, see screenshot
<img width="699" alt="Screen Shot 2022-04-30 at 9 58 02 PM" src="https://user-images.githubusercontent.com/98995766/166130634-ae062b0b-0f2b-40c0-9b8c-1e436c9d0a79.png">
t

### Additional information

For HorizontalPodAutoscaler to work, the metrics-server requires all containers to define `resources.requests`. Because WordPress HELM chart by default does not set the values for the metrics sidecar container, when users enable the sidecar, it causes their autoscaler to break.

# Solution:
Set the default values for `metrics.resources.requests.memory` and `metrics.resources.requests.cpu`.

**Comment by timofey-momsdish** [comment]
Here's another example of a similar issue with the Redis image: https://github.com/bitnami/charts/issues/9928

**Comment by rafariossaa** [comment]
Hi,
  The default for `memory` and `cpu` are very dependent on the use case and your infrastructure, so there is not a "right" value for this.
  However, you can [set those parameters](https://github.com/bitnami/charts/blob/8081844e25c71cb01af05eeab771530ab6297247/bitnami/wordpress/values.yaml#L888) and configure them with the values you consider appropriate for your deployment.
