### ISSUE TITLE
Airflow Cannon't connect to Azure Key Vault

### ISSUE THREAD

**Issue by alexisaraya** [bitnami/charts#9997]
### Name and Version

bitnami/airflow 12.2.1

### What steps will reproduce the bug?

1. In the airflow envieroment
2. Config with using Azure Key Vault for secret Backend, configuration via values  
```yaml
  extraEnvVars: |
    - name: AZURE_CLIENT_ID
      value: xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx
    - name: AZURE_TENANT_ID
      value: xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx
    - name: AZURE_CLIENT_SECRET
      value: xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxx
   - name: AZURE_KEYVAULT_URL
      value: "https://xxxxxx.vault.azure.net/"
    - name: AIRFLOW__SECRETS__BACKEND
      value: airflow.providers.microsoft.azure.secrets.azure_key_vault.AzureKeyVaultBackend
    - name: AIRFLOW__SECRETS__BACKEND_KWARGS
      value: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","vault_url":"https://xxxxxx.vault.azure.net"}'
```
3. I run DAG to get the secret stored in Azure Key Vault 
```
from airflow.operators.python_operator import PythonOperator
from datetime import datetime
from airflow.hooks.base_hook import BaseHook
from airflow.providers.microsoft.azure.secrets.key_vault import AzureKeyVaultBackend
from airflow import DAG


def get_secrets(**kwargs):
    variable = AzureKeyVaultBackend().get_variable(key='var_name')
    print(variable)

dag = DAG('azure_key_vault_example_dag', start_date=datetime(2022, 1, 1), schedule_interval=None)

test_task = PythonOperator(task_id='test-task', python_callable=get_secrets, op_kwargs={'var_name': 'BDSQLXXXX'}, dag=dag)

test_task
``` 
![imagen](https://user-images.githubusercontent.com/6661443/166150884-9aad301a-3aa2-4f11-b247-294930950090.png)

### Are you using any custom parameters or values?

values.yaml
```yaml
extraEnvVars: |  
- name: AIRFLOW__SECRETS__BACKEND
      value: airflow.providers.microsoft.azure.secrets.azure_key_vault.AzureKeyVaultBackend
- name: AIRFLOW__SECRETS__BACKEND_KWARGS
      value: '{"connections_prefix":"airflow-connections","variables_prefix":"airflow-variables","vault_url":"https://xxxx.vault.azure.net"}'
```

### What is the expected behavior?

Dag return Secret from Key I Store in Azure Key Vault

### What do you see instead?

Can not connect to azure key vault, error **"vault_url must be the URL of an Azure Key Vault"**

```
[2022-04-29, 18:57:44 UTC] {environment.py:85} INFO - Environment is configured for ClientSecretCredential
[2022-04-29, 18:57:44 UTC] {managed_identity.py:85} INFO - ManagedIdentityCredential will use IMDS
[2022-04-29, 18:57:44 UTC] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/bitnami/airflow/dags/git_komatsuchile/dags/azure_key_vault_example_dag.py", line 9, in get_secrets
    variable = AzureKeyVaultBackend().get_variable(key='var_name')
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/microsoft/azure/secrets/key_vault.py", line 151, in get_variable
    return self._get_secret(self.variables_prefix, key)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/microsoft/azure/secrets/key_vault.py", line 188, in _get_secret
    secret = self.client.get_secret(name=name)
  File "/opt/bitnami/python/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/providers/microsoft/azure/secrets/key_vault.py", line 109, in client
    client = SecretClient(vault_url=self.vault_url, credential=credential, **self.kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/azure/keyvault/secrets/_shared/client_base.py", line 44, in __init__
    raise ValueError("vault_url must be the URL of an Azure Key Vault")
ValueError: vault_url must be the URL of an Azure Key `Vault`
```

### Additional information

When performing a Pod description, the environment variables are passed correctly.

![imagen](https://user-images.githubusercontent.com/6661443/166151072-171fc4af-1e65-4bca-b8c3-782c5e20575b.png)

**Comment by carrodher** [comment]
According to the error
```
vault_url must be the URL of an Azure Key `Vault`
```
it seems the application is trying to use the URL you set but it is not considering it as a valid URL, do you have any way to check that the URL and the service behind that URL is working fine?

**Comment by alexisaraya** [comment]
Hi @carrodher the URL I have tested ok outside airflow

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Airflow container image or Helm chart but about how the application or environment is being used/configured. I was trying to reproduce the issue but had no luck.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by diegolpedro** [comment]
Hi @alexisaraya, have you find the problem? I have the same problem now.
Thanks

**Comment by ay-azara** [comment]
When Airflow starts, at the tippy top of the logs, if it is unable to parse the JSON it should print a message saying so. Brilliantly, it handles this by using an empty `kwargs`. In my case, I was loading the variables from Bash and had the json string wrapped in single quotes which evidently it did not like.

`Failed to parse [secrets] backend_kwargs as JSON, defaulting to no kwargs`
