### ISSUE TITLE
Don't deploy bitnami/rabbitmq when setting metrics.enabled to true

### ISSUE THREAD

**Issue by alzamonn** [bitnami/charts#9998]
### Name and Version

bitnami/rabbitmq latest

### What steps will reproduce the bug?

Hello!
Run:
helm upgrade --install -f values.yaml bitnami/rabbitmq

### Are you using any custom parameters or values?

metrics:
  enabled: true

### What is the expected behavior?

correct deploy

### What do you see instead?

"bitnami" has been added to your repositories
Error: UPGRADE FAILED: template: rabbitmq/templates/svc.yaml:100:22: executing "rabbitmq/templates/svc.yaml" at <.Values.service.ports.metrics.metrics>: can't evaluate field metrics in type interface {}

### Additional information

as I understand it, here mistake https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/svc.yamlр
    {{- if .Values.metrics.enabled }}
    - name: {{ .Values.service.portNames.metrics }}
      **port: {{ .Values.service.ports.metrics.metrics }}**
      targetPort: metrics

**Comment by migruiz4** [comment]
Hi @alzamonn,

Sorry for the inconvenience, I have submitted this PR fixing the issue: https://github.com/bitnami/charts/pull/9987
