### ISSUE TITLE
[argo-cd] kustomize shows unknown version

### ISSUE THREAD

**Issue by niv0** [bitnami/charts#9999]
### Name and Version

bitnami/argo-cd 3.1.16

### What steps will reproduce the bug?

1. Installed helm chart as advised.
2. Go to pod shell (repo-sever)
3. Start kustomize

`1001@redis-argo-cd-repo-server-769ddbdd58-s9bf4:/$ kustomize version`
`{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}`
`1001@redis-argo-cd-repo-server-769ddbdd58-s9bf4:/$`

I am trying to solve a general issue using kustomize in argocd so I saw this problem which might be related to my general one.

### Are you using any custom parameters or values?

Yes, but i this area not.

### What is the expected behavior?

Checkng https://github.com/bitnami/bitnami-docker-argo-cd/blob/master/2/debian-10/Dockerfile#L12 I would expect "4.5.4-0" or similar.

### What do you see instead?

`1001@redis-argo-cd-repo-server-769ddbdd58-s9bf4:/$ kustomize version
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
1001@redis-argo-cd-repo-server-769ddbdd58-s9bf4:/$`

**Comment by rafariossaa** [comment]
Hi,
  `kustomize version` returns the version of the `kustomize` tool, it is not related with the apps in the container or the container itself.
